ZEQ2-Lite: Engine/jpeg-8c/jchuff.c File Reference
jchuff.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct c_derived_tbl
struct huff_entropy_encoder
struct savable_state
struct working_state
Macros
#define ASSIGN_STATE(dest, src) ((dest) = (src))
#define emit_byte_e(entropy, val)
#define emit_byte_s(state, val, action)
#define IRIGHT_SHIFT(x, shft) ((x) >> (shft))
#define ISHIFT_TEMPS
#define JPEG_INTERNALS
#define MAX_CLEN 32 /* assumed maximum initial code length */
#define MAX_COEF_BITS 10
#define MAX_CORR_BITS 1000 /* Max # of correction bits I can buffer */
Typedefs
typedef huff_entropy_encoder * huff_entropy_ptr
Functions
dump_buffer_e (huff_entropy_ptr entropy)
dump_buffer_s (working_state *state)
INLINE emit_ac_symbol (huff_entropy_ptr entropy, int tbl_no, int symbol)
INLINE emit_bits_e (huff_entropy_ptr entropy, unsigned int code, int size)
INLINE emit_bits_s (working_state *state, unsigned int code, int size)
emit_buffered_bits (huff_entropy_ptr entropy, char *bufstart, unsigned int nbits)
INLINE emit_dc_symbol (huff_entropy_ptr entropy, int tbl_no, int symbol)
emit_eobrun (huff_entropy_ptr entropy)
emit_restart_e (huff_entropy_ptr entropy, int restart_num)
emit_restart_s (working_state *state, int restart_num)
encode_mcu_AC_first (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu_AC_refine (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu_DC_first (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu_DC_refine (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu_gather (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_mcu_huff (j_compress_ptr cinfo, JBLOCKROW *MCU_data)
encode_one_block (working_state *state, JCOEFPTR block, int last_dc_val, c_derived_tbl *dctbl, c_derived_tbl *actbl)
finish_pass_gather (j_compress_ptr cinfo)
finish_pass_huff (j_compress_ptr cinfo)
flush_bits_e (huff_entropy_ptr entropy)
flush_bits_s (working_state *state)
htest_one_block (j_compress_ptr cinfo, JCOEFPTR block, int last_dc_val, long dc_counts[], long ac_counts[])
jinit_huff_encoder (j_compress_ptr cinfo)
jpeg_gen_optimal_table (j_compress_ptr cinfo, JHUFF_TBL *htbl, long freq[])
jpeg_make_c_derived_tbl (j_compress_ptr cinfo, boolean isDC, int tblno, c_derived_tbl **pdtbl)
start_pass_huff (j_compress_ptr cinfo, boolean gather_statistics)
Macro Definition Documentation
ASSIGN_STATE
#define ASSIGN_STATE (dest, src) ((dest) = (src))
Definition at line 67 of file jchuff.c.
emit_byte_e
#define emit_byte_e (entropy, val)
Value:
    { *(entropy)->next_output_byte++ = (JOCTET) (val);  \
      if (--(entropy)->free_in_buffer == 0)  \
        dump_buffer_e(entropy); }
Definition at line 262 of file jchuff.c.
emit_byte_s
#define emit_byte_s (state, val, action)
Value:
    { *(state)->next_output_byte++ = (JOCTET) (val);  \
      if (--(state)->free_in_buffer == 0)  \
        if (! dump_buffer_s(state))  \
          { action; } }
Definition at line 255 of file jchuff.c.
IRIGHT_SHIFT
#define IRIGHT_SHIFT (x, shft) ((x) >> (shft))
Definition at line 151 of file jchuff.c.
ISHIFT_TEMPS
#define ISHIFT_TEMPS
Definition at line 150 of file jchuff.c.
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 23 of file jchuff.c.
MAX_CLEN
#define MAX_CLEN 32 /* assumed maximum initial code length */
MAX_COEF_BITS
#define MAX_COEF_BITS 10
Definition at line 35 of file jchuff.c.
MAX_CORR_BITS
#define MAX_CORR_BITS 1000 /* Max # of correction bits I can buffer */
Definition at line 136 of file jchuff.c.
Typedef Documentation
huff_entropy_ptr
typedef huff_entropy_encoder* huff_entropy_ptr
Definition at line 117 of file jchuff.c.
Function Documentation
dump_buffer_e()
dump_buffer_e (huff_entropy_ptr entropy)
Definition at line 284 of file jchuff.c.
 {
   struct jpeg_destination_mgr * dest = entropy->cinfo->dest;
   if (! (*dest->empty_output_buffer) (entropy->cinfo))
     ERREXIT(entropy->cinfo, JERR_CANT_SUSPEND);
   /* After a successful buffer dump, must reset buffer pointers */
   entropy->next_output_byte = dest->next_output_byte;
   entropy->free_in_buffer = dest->free_in_buffer;
 }
References ERREXIT, jpeg_destination_mgr::free_in_buffer, and jpeg_destination_mgr::next_output_byte.
dump_buffer_s()
dump_buffer_s (working_state * state)
Definition at line 269 of file jchuff.c.
 {
   struct jpeg_destination_mgr * dest = state->cinfo->dest;
   if (! (*dest->empty_output_buffer) (state->cinfo))
     return FALSE;
   /* After a successful buffer dump, must reset buffer pointers */
   state->next_output_byte = dest->next_output_byte;
   state->free_in_buffer = dest->free_in_buffer;
   return TRUE;
 }
References FALSE, jpeg_destination_mgr::free_in_buffer, jpeg_destination_mgr::next_output_byte, and TRUE.
emit_ac_symbol()
INLINE emit_ac_symbol (huff_entropy_ptr entropy, int tbl_no, int symbol)
Definition at line 424 of file jchuff.c.
 {
   if (entropy->gather_statistics)
     entropy->ac_count_ptrs[tbl_no][symbol]++;
   else {
     c_derived_tbl * tbl = entropy->ac_derived_tbls[tbl_no];
     emit_bits_e(entropy, tbl->ehufco[symbol], tbl->ehufsi[symbol]);
   }
 }
References c_derived_tbl::ehufco, c_derived_tbl::ehufsi, and emit_bits_e().
Referenced by emit_eobrun(), encode_mcu_AC_first(), and encode_mcu_AC_refine().
emit_bits_e()
INLINE emit_bits_e (huff_entropy_ptr entropy, unsigned int code, int size)
Definition at line 346 of file jchuff.c.
 {
   /* This routine is heavily used, so it's worth coding tightly. */
   register INT32 put_buffer = (INT32) code;
   register int put_bits = entropy->saved.put_bits;
   /* if size is 0, caller used an invalid Huffman table entry */
   if (size == 0)
     ERREXIT(entropy->cinfo, JERR_HUFF_MISSING_CODE);
   if (entropy->gather_statistics)
     return;         /* do nothing if we're only getting stats */
   put_buffer &= (((INT32) 1)<<size) - 1; /* mask off any extra bits in code */
   put_bits += size;     /* new number of bits in buffer */
   put_buffer <<= 24 - put_bits; /* align incoming bits */
   /* and merge with old buffer contents */
   put_buffer |= entropy->saved.put_buffer;
   while (put_bits >= 8) {
     int c = (int) ((put_buffer >> 16) & 0xFF);
     emit_byte_e(entropy, c);
     if (c == 0xFF) {        /* need to stuff a zero byte? */
       emit_byte_e(entropy, 0);
     }
     put_buffer <<= 8;
     put_bits -= 8;
   }
   entropy->saved.put_buffer = put_buffer; /* update variables */
   entropy->saved.put_bits = put_bits;
 }
References emit_byte_e, ERREXIT, and int().
Referenced by emit_ac_symbol(), emit_buffered_bits(), emit_dc_symbol(), emit_eobrun(), encode_mcu_AC_first(), encode_mcu_AC_refine(), encode_mcu_DC_first(), encode_mcu_DC_refine(), and flush_bits_e().
emit_bits_s()
INLINE emit_bits_s (working_state * state, unsigned int code, int size)
Definition at line 307 of file jchuff.c.
 {
   /* This routine is heavily used, so it's worth coding tightly. */
   register INT32 put_buffer = (INT32) code;
   register int put_bits = state->cur.put_bits;
   /* if size is 0, caller used an invalid Huffman table entry */
   if (size == 0)
     ERREXIT(state->cinfo, JERR_HUFF_MISSING_CODE);
   put_buffer &= (((INT32) 1)<<size) - 1; /* mask off any extra bits in code */
   put_bits += size;     /* new number of bits in buffer */
   put_buffer <<= 24 - put_bits; /* align incoming bits */
   put_buffer |= state->cur.put_buffer; /* and merge with old buffer contents */
   while (put_bits >= 8) {
     int c = (int) ((put_buffer >> 16) & 0xFF);
     emit_byte_s(state, c, return FALSE);
     if (c == 0xFF) {        /* need to stuff a zero byte? */
       emit_byte_s(state, 0, return FALSE);
     }
     put_buffer <<= 8;
     put_bits -= 8;
   }
   state->cur.put_buffer = put_buffer; /* update state variables */
   state->cur.put_bits = put_bits;
   return TRUE;
 }
References emit_byte_s, ERREXIT, FALSE, int(), and TRUE.
Referenced by encode_one_block(), and flush_bits_s().
emit_buffered_bits()
emit_buffered_bits (huff_entropy_ptr entropy, char * bufstart, unsigned int nbits)
Definition at line 440 of file jchuff.c.
 {
   if (entropy->gather_statistics)
     return;         /* no real work */
   while (nbits > 0) {
     emit_bits_e(entropy, (unsigned int) (*bufstart), 1);
     bufstart++;
     nbits--;
   }
 }
References emit_bits_e().
Referenced by emit_eobrun(), and encode_mcu_AC_refine().
emit_dc_symbol()
INLINE emit_dc_symbol (huff_entropy_ptr entropy, int tbl_no, int symbol)
Definition at line 411 of file jchuff.c.
 {
   if (entropy->gather_statistics)
     entropy->dc_count_ptrs[tbl_no][symbol]++;
   else {
     c_derived_tbl * tbl = entropy->dc_derived_tbls[tbl_no];
     emit_bits_e(entropy, tbl->ehufco[symbol], tbl->ehufsi[symbol]);
   }
 }
References c_derived_tbl::ehufco, c_derived_tbl::ehufsi, and emit_bits_e().
Referenced by encode_mcu_DC_first().
emit_eobrun()
emit_eobrun (huff_entropy_ptr entropy)
Definition at line 459 of file jchuff.c.
 {
   register int temp, nbits;
   if (entropy->EOBRUN > 0) {    /* if there is any pending EOBRUN */
     temp = entropy->EOBRUN;
     nbits = 0;
     while ((temp >>= 1))
       nbits++;
     /* safety check: shouldn't happen given limited correction-bit buffer */
     if (nbits > 14)
       ERREXIT(entropy->cinfo, JERR_HUFF_MISSING_CODE);
     emit_ac_symbol(entropy, entropy->ac_tbl_no, nbits << 4);
     if (nbits)
       emit_bits_e(entropy, entropy->EOBRUN, nbits);
     entropy->EOBRUN = 0;
     /* Emit any buffered correction bits */
     emit_buffered_bits(entropy, entropy->bit_buffer, entropy->BE);
     entropy->BE = 0;
   }
 }
References emit_ac_symbol(), emit_bits_e(), emit_buffered_bits(), and ERREXIT.
Referenced by emit_restart_e(), encode_mcu_AC_first(), encode_mcu_AC_refine(), finish_pass_gather(), and finish_pass_huff().
emit_restart_e()
emit_restart_e (huff_entropy_ptr entropy, int restart_num)
Definition at line 511 of file jchuff.c.
 {
   int ci;
   emit_eobrun(entropy);
   if (! entropy->gather_statistics) {
     flush_bits_e(entropy);
     emit_byte_e(entropy, 0xFF);
     emit_byte_e(entropy, JPEG_RST0 + restart_num);
   }
   if (entropy->cinfo->Ss == 0) {
     /* Re-initialize DC predictions to 0 */
     for (ci = 0; ci < entropy->cinfo->comps_in_scan; ci++)
       entropy->saved.last_dc_val[ci] = 0;
   } else {
     /* Re-initialize all AC-related fields to 0 */
     entropy->EOBRUN = 0;
     entropy->BE = 0;
   }
 }
References emit_byte_e, emit_eobrun(), flush_bits_e(), and JPEG_RST0.
Referenced by encode_mcu_AC_first(), encode_mcu_AC_refine(), encode_mcu_DC_first(), and encode_mcu_DC_refine().
emit_restart_s()
emit_restart_s (working_state * state, int restart_num)
Definition at line 490 of file jchuff.c.
 {
   int ci;
   if (! flush_bits_s(state))
     return FALSE;
   emit_byte_s(state, 0xFF, return FALSE);
   emit_byte_s(state, JPEG_RST0 + restart_num, return FALSE);
   /* Re-initialize DC predictions to 0 */
   for (ci = 0; ci < state->cinfo->comps_in_scan; ci++)
     state->cur.last_dc_val[ci] = 0;
   /* The restart counter is not updated until we successfully write the MCU. */
   return TRUE;
 }
References emit_byte_s, FALSE, flush_bits_s(), JPEG_RST0, and TRUE.
Referenced by encode_mcu_huff().
encode_mcu_AC_first()
encode_mcu_AC_first (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 628 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   register int temp, temp2;
   register int nbits;
   register int r, k;
   int Se, Al;
   const int * natural_order;
   JBLOCKROW block;
   entropy->next_output_byte = cinfo->dest->next_output_byte;
   entropy->free_in_buffer = cinfo->dest->free_in_buffer;
   /* Emit restart marker if needed */
   if (cinfo->restart_interval)
     if (entropy->restarts_to_go == 0)
       emit_restart_e(entropy, entropy->next_restart_num);
   Se = cinfo->Se;
   Al = cinfo->Al;
   natural_order = cinfo->natural_order;
   /* Encode the MCU data block */
   block = MCU_data[0];
   /* Encode the AC coefficients per section G.1.2.2, fig. G.3 */
   r = 0;            /* r = run length of zeros */
   for (k = cinfo->Ss; k <= Se; k++) {
     if ((temp = (*block)[natural_order[k]]) == 0) {
       r++;
       continue;
     }
     /* We must apply the point transform by Al.  For AC coefficients this
      * is an integer division with rounding towards 0.  To do this portably
      * in C, we shift after obtaining the absolute value; so the code is
      * interwoven with finding the abs value (temp) and output bits (temp2).
      */
     if (temp < 0) {
       temp = -temp;     /* temp is abs value of input */
       temp >>= Al;      /* apply the point transform */
       /* For a negative coef, want temp2 = bitwise complement of abs(coef) */
       temp2 = ~temp;
     } else {
       temp >>= Al;      /* apply the point transform */
       temp2 = temp;
     }
     /* Watch out for case that nonzero coef is zero after point transform */
     if (temp == 0) {
       r++;
       continue;
     }
     /* Emit any pending EOBRUN */
     if (entropy->EOBRUN > 0)
       emit_eobrun(entropy);
     /* if run length > 15, must emit special run-length-16 codes (0xF0) */
     while (r > 15) {
       emit_ac_symbol(entropy, entropy->ac_tbl_no, 0xF0);
       r -= 16;
     }
     /* Find the number of bits needed for the magnitude of the coefficient */
     nbits = 1;          /* there must be at least one 1 bit */
     while ((temp >>= 1))
       nbits++;
     /* Check for out-of-range coefficient values */
     if (nbits > MAX_COEF_BITS)
       ERREXIT(cinfo, JERR_BAD_DCT_COEF);
     /* Count/emit Huffman symbol for run length / number of bits */
     emit_ac_symbol(entropy, entropy->ac_tbl_no, (r << 4) + nbits);
     /* Emit that number of bits of the value, if positive, */
     /* or the complement of its magnitude, if negative. */
     emit_bits_e(entropy, (unsigned int) temp2, nbits);
     r = 0;          /* reset zero run length */
   }
   if (r > 0) {          /* If there are trailing zeroes, */
     entropy->EOBRUN++;      /* count an EOB */
     if (entropy->EOBRUN == 0x7FFF)
       emit_eobrun(entropy); /* force it out to avoid overflow */
   }
   cinfo->dest->next_output_byte = entropy->next_output_byte;
   cinfo->dest->free_in_buffer = entropy->free_in_buffer;
   /* Update restart-interval state too */
   if (cinfo->restart_interval) {
     if (entropy->restarts_to_go == 0) {
       entropy->restarts_to_go = cinfo->restart_interval;
       entropy->next_restart_num++;
       entropy->next_restart_num &= 7;
     }
     entropy->restarts_to_go--;
   }
   return TRUE;
 }
References huff_entropy_encoder::ac_tbl_no, emit_ac_symbol(), emit_bits_e(), emit_eobrun(), emit_restart_e(), huff_entropy_encoder::EOBRUN, ERREXIT, huff_entropy_encoder::free_in_buffer, MAX_COEF_BITS, huff_entropy_encoder::next_output_byte, huff_entropy_encoder::next_restart_num, huff_entropy_encoder::restarts_to_go, and TRUE.
Referenced by start_pass_huff().
encode_mcu_AC_refine()
encode_mcu_AC_refine (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 786 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   register int temp;
   register int r, k;
   int EOB;
   char *BR_buffer;
   unsigned int BR;
   int Se, Al;
   const int * natural_order;
   JBLOCKROW block;
   int absvalues[DCTSIZE2];
   entropy->next_output_byte = cinfo->dest->next_output_byte;
   entropy->free_in_buffer = cinfo->dest->free_in_buffer;
   /* Emit restart marker if needed */
   if (cinfo->restart_interval)
     if (entropy->restarts_to_go == 0)
       emit_restart_e(entropy, entropy->next_restart_num);
   Se = cinfo->Se;
   Al = cinfo->Al;
   natural_order = cinfo->natural_order;
   /* Encode the MCU data block */
   block = MCU_data[0];
   /* It is convenient to make a pre-pass to determine the transformed
    * coefficients' absolute values and the EOB position.
    */
   EOB = 0;
   for (k = cinfo->Ss; k <= Se; k++) {
     temp = (*block)[natural_order[k]];
     /* We must apply the point transform by Al.  For AC coefficients this
      * is an integer division with rounding towards 0.  To do this portably
      * in C, we shift after obtaining the absolute value.
      */
     if (temp < 0)
       temp = -temp;     /* temp is abs value of input */
     temp >>= Al;        /* apply the point transform */
     absvalues[k] = temp;    /* save abs value for main pass */
     if (temp == 1)
       EOB = k;          /* EOB = index of last newly-nonzero coef */
   }
   /* Encode the AC coefficients per section G.1.2.3, fig. G.7 */
   r = 0;            /* r = run length of zeros */
   BR = 0;           /* BR = count of buffered bits added now */
   BR_buffer = entropy->bit_buffer + entropy->BE; /* Append bits to buffer */
   for (k = cinfo->Ss; k <= Se; k++) {
     if ((temp = absvalues[k]) == 0) {
       r++;
       continue;
     }
     /* Emit any required ZRLs, but not if they can be folded into EOB */
     while (r > 15 && k <= EOB) {
       /* emit any pending EOBRUN and the BE correction bits */
       emit_eobrun(entropy);
       /* Emit ZRL */
       emit_ac_symbol(entropy, entropy->ac_tbl_no, 0xF0);
       r -= 16;
       /* Emit buffered correction bits that must be associated with ZRL */
       emit_buffered_bits(entropy, BR_buffer, BR);
       BR_buffer = entropy->bit_buffer; /* BE bits are gone now */
       BR = 0;
     }
     /* If the coef was previously nonzero, it only needs a correction bit.
      * NOTE: a straight translation of the spec's figure G.7 would suggest
      * that we also need to test r > 15.  But if r > 15, we can only get here
      * if k > EOB, which implies that this coefficient is not 1.
      */
     if (temp > 1) {
       /* The correction bit is the next bit of the absolute value. */
       BR_buffer[BR++] = (char) (temp & 1);
       continue;
     }
     /* Emit any pending EOBRUN and the BE correction bits */
     emit_eobrun(entropy);
     /* Count/emit Huffman symbol for run length / number of bits */
     emit_ac_symbol(entropy, entropy->ac_tbl_no, (r << 4) + 1);
     /* Emit output bit for newly-nonzero coef */
     temp = ((*block)[natural_order[k]] < 0) ? 0 : 1;
     emit_bits_e(entropy, (unsigned int) temp, 1);
     /* Emit buffered correction bits that must be associated with this code */
     emit_buffered_bits(entropy, BR_buffer, BR);
     BR_buffer = entropy->bit_buffer; /* BE bits are gone now */
     BR = 0;
     r = 0;          /* reset zero run length */
   }
   if (r > 0 || BR > 0) {    /* If there are trailing zeroes, */
     entropy->EOBRUN++;      /* count an EOB */
     entropy->BE += BR;      /* concat my correction bits to older ones */
     /* We force out the EOB if we risk either:
      * 1. overflow of the EOB counter;
      * 2. overflow of the correction bit buffer during the next MCU.
      */
     if (entropy->EOBRUN == 0x7FFF || entropy->BE > (MAX_CORR_BITS-DCTSIZE2+1))
       emit_eobrun(entropy);
   }
   cinfo->dest->next_output_byte = entropy->next_output_byte;
   cinfo->dest->free_in_buffer = entropy->free_in_buffer;
   /* Update restart-interval state too */
   if (cinfo->restart_interval) {
     if (entropy->restarts_to_go == 0) {
       entropy->restarts_to_go = cinfo->restart_interval;
       entropy->next_restart_num++;
       entropy->next_restart_num &= 7;
     }
     entropy->restarts_to_go--;
   }
   return TRUE;
 }
References huff_entropy_encoder::ac_tbl_no, huff_entropy_encoder::BE, huff_entropy_encoder::bit_buffer, DCTSIZE2, emit_ac_symbol(), emit_bits_e(), emit_buffered_bits(), emit_eobrun(), emit_restart_e(), EOB, huff_entropy_encoder::EOBRUN, huff_entropy_encoder::free_in_buffer, MAX_CORR_BITS, huff_entropy_encoder::next_output_byte, huff_entropy_encoder::next_restart_num, huff_entropy_encoder::restarts_to_go, and TRUE.
Referenced by start_pass_huff().
encode_mcu_DC_first()
encode_mcu_DC_first (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 541 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   register int temp, temp2;
   register int nbits;
   int blkn, ci;
   int Al = cinfo->Al;
   JBLOCKROW block;
   jpeg_component_info * compptr;
   ISHIFT_TEMPS
   entropy->next_output_byte = cinfo->dest->next_output_byte;
   entropy->free_in_buffer = cinfo->dest->free_in_buffer;
   /* Emit restart marker if needed */
   if (cinfo->restart_interval)
     if (entropy->restarts_to_go == 0)
       emit_restart_e(entropy, entropy->next_restart_num);
   /* Encode the MCU data blocks */
   for (blkn = 0; blkn < cinfo->blocks_in_MCU; blkn++) {
     block = MCU_data[blkn];
     ci = cinfo->MCU_membership[blkn];
     compptr = cinfo->cur_comp_info[ci];
     /* Compute the DC value after the required point transform by Al.
      * This is simply an arithmetic right shift.
      */
     temp2 = IRIGHT_SHIFT((int) ((*block)[0]), Al);
     /* DC differences are figured on the point-transformed values. */
     temp = temp2 - entropy->saved.last_dc_val[ci];
     entropy->saved.last_dc_val[ci] = temp2;
     /* Encode the DC coefficient difference per section G.1.2.1 */
     temp2 = temp;
     if (temp < 0) {
       temp = -temp;     /* temp is abs value of input */
       /* For a negative input, want temp2 = bitwise complement of abs(input) */
       /* This code assumes we are on a two's complement machine */
       temp2--;
     }
     /* Find the number of bits needed for the magnitude of the coefficient */
     nbits = 0;
     while (temp) {
       nbits++;
       temp >>= 1;
     }
     /* Check for out-of-range coefficient values.
      * Since we're encoding a difference, the range limit is twice as much.
      */
     if (nbits > MAX_COEF_BITS+1)
       ERREXIT(cinfo, JERR_BAD_DCT_COEF);
     /* Count/emit the Huffman-coded symbol for the number of bits */
     emit_dc_symbol(entropy, compptr->dc_tbl_no, nbits);
     /* Emit that number of bits of the value, if positive, */
     /* or the complement of its magnitude, if negative. */
     if (nbits)          /* emit_bits rejects calls with size 0 */
       emit_bits_e(entropy, (unsigned int) temp2, nbits);
   }
   cinfo->dest->next_output_byte = entropy->next_output_byte;
   cinfo->dest->free_in_buffer = entropy->free_in_buffer;
   /* Update restart-interval state too */
   if (cinfo->restart_interval) {
     if (entropy->restarts_to_go == 0) {
       entropy->restarts_to_go = cinfo->restart_interval;
       entropy->next_restart_num++;
       entropy->next_restart_num &= 7;
     }
     entropy->restarts_to_go--;
   }
   return TRUE;
 }
References compptr, jpeg_component_info::dc_tbl_no, emit_bits_e(), emit_dc_symbol(), emit_restart_e(), ERREXIT, huff_entropy_encoder::free_in_buffer, IRIGHT_SHIFT, ISHIFT_TEMPS, savable_state::last_dc_val, MAX_COEF_BITS, huff_entropy_encoder::next_output_byte, huff_entropy_encoder::next_restart_num, huff_entropy_encoder::restarts_to_go, huff_entropy_encoder::saved, and TRUE.
Referenced by start_pass_huff().
encode_mcu_DC_refine()
encode_mcu_DC_refine (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 739 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   register int temp;
   int blkn;
   int Al = cinfo->Al;
   JBLOCKROW block;
   entropy->next_output_byte = cinfo->dest->next_output_byte;
   entropy->free_in_buffer = cinfo->dest->free_in_buffer;
   /* Emit restart marker if needed */
   if (cinfo->restart_interval)
     if (entropy->restarts_to_go == 0)
       emit_restart_e(entropy, entropy->next_restart_num);
   /* Encode the MCU data blocks */
   for (blkn = 0; blkn < cinfo->blocks_in_MCU; blkn++) {
     block = MCU_data[blkn];
     /* We simply emit the Al'th bit of the DC coefficient value. */
     temp = (*block)[0];
     emit_bits_e(entropy, (unsigned int) (temp >> Al), 1);
   }
   cinfo->dest->next_output_byte = entropy->next_output_byte;
   cinfo->dest->free_in_buffer = entropy->free_in_buffer;
   /* Update restart-interval state too */
   if (cinfo->restart_interval) {
     if (entropy->restarts_to_go == 0) {
       entropy->restarts_to_go = cinfo->restart_interval;
       entropy->next_restart_num++;
       entropy->next_restart_num &= 7;
     }
     entropy->restarts_to_go--;
   }
   return TRUE;
 }
References emit_bits_e(), emit_restart_e(), huff_entropy_encoder::free_in_buffer, huff_entropy_encoder::next_output_byte, huff_entropy_encoder::next_restart_num, huff_entropy_encoder::restarts_to_go, and TRUE.
Referenced by start_pass_huff().
encode_mcu_gather()
encode_mcu_gather (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 1197 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   int blkn, ci;
   jpeg_component_info * compptr;
   /* Take care of restart intervals if needed */
   if (cinfo->restart_interval) {
     if (entropy->restarts_to_go == 0) {
       /* Re-initialize DC predictions to 0 */
       for (ci = 0; ci < cinfo->comps_in_scan; ci++)
     entropy->saved.last_dc_val[ci] = 0;
       /* Update restart state */
       entropy->restarts_to_go = cinfo->restart_interval;
     }
     entropy->restarts_to_go--;
   }
   for (blkn = 0; blkn < cinfo->blocks_in_MCU; blkn++) {
     ci = cinfo->MCU_membership[blkn];
     compptr = cinfo->cur_comp_info[ci];
     htest_one_block(cinfo, MCU_data[blkn][0], entropy->saved.last_dc_val[ci],
             entropy->dc_count_ptrs[compptr->dc_tbl_no],
             entropy->ac_count_ptrs[compptr->ac_tbl_no]);
     entropy->saved.last_dc_val[ci] = MCU_data[blkn][0][0];
   }
   return TRUE;
 }
References huff_entropy_encoder::ac_count_ptrs, jpeg_component_info::ac_tbl_no, compptr, huff_entropy_encoder::dc_count_ptrs, jpeg_component_info::dc_tbl_no, htest_one_block(), savable_state::last_dc_val, huff_entropy_encoder::restarts_to_go, huff_entropy_encoder::saved, and TRUE.
Referenced by start_pass_huff().
encode_mcu_huff()
encode_mcu_huff (j_compress_ptr cinfo, JBLOCKROW * MCU_data)
Definition at line 1016 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   working_state state;
   int blkn, ci;
   jpeg_component_info * compptr;
   /* Load up working state */
   state.next_output_byte = cinfo->dest->next_output_byte;
   state.free_in_buffer = cinfo->dest->free_in_buffer;
   ASSIGN_STATE(state.cur, entropy->saved);
   state.cinfo = cinfo;
   /* Emit restart marker if needed */
   if (cinfo->restart_interval) {
     if (entropy->restarts_to_go == 0)
       if (! emit_restart_s(&state, entropy->next_restart_num))
     return FALSE;
   }
   /* Encode the MCU data blocks */
   for (blkn = 0; blkn < cinfo->blocks_in_MCU; blkn++) {
     ci = cinfo->MCU_membership[blkn];
     compptr = cinfo->cur_comp_info[ci];
     if (! encode_one_block(&state,
                MCU_data[blkn][0], state.cur.last_dc_val[ci],
                entropy->dc_derived_tbls[compptr->dc_tbl_no],
                entropy->ac_derived_tbls[compptr->ac_tbl_no]))
       return FALSE;
     /* Update last_dc_val */
     state.cur.last_dc_val[ci] = MCU_data[blkn][0][0];
   }
   /* Completed MCU, so update state */
   cinfo->dest->next_output_byte = state.next_output_byte;
   cinfo->dest->free_in_buffer = state.free_in_buffer;
   ASSIGN_STATE(entropy->saved, state.cur);
   /* Update restart-interval state too */
   if (cinfo->restart_interval) {
     if (entropy->restarts_to_go == 0) {
       entropy->restarts_to_go = cinfo->restart_interval;
       entropy->next_restart_num++;
       entropy->next_restart_num &= 7;
     }
     entropy->restarts_to_go--;
   }
   return TRUE;
 }
References huff_entropy_encoder::ac_derived_tbls, jpeg_component_info::ac_tbl_no, ASSIGN_STATE, compptr, huff_entropy_encoder::dc_derived_tbls, jpeg_component_info::dc_tbl_no, emit_restart_s(), encode_one_block(), FALSE, huff_entropy_encoder::next_restart_num, huff_entropy_encoder::restarts_to_go, huff_entropy_encoder::saved, and TRUE.
Referenced by start_pass_huff().
encode_one_block()
encode_one_block (working_state * state, JCOEFPTR block, int last_dc_val, c_derived_tbl * dctbl, c_derived_tbl * actbl)
Definition at line 916 of file jchuff.c.
 {
   register int temp, temp2;
   register int nbits;
   register int k, r, i;
   int Se = state->cinfo->lim_Se;
   const int * natural_order = state->cinfo->natural_order;
   /* Encode the DC coefficient difference per section F.1.2.1 */
   temp = temp2 = block[0] - last_dc_val;
   if (temp < 0) {
     temp = -temp;       /* temp is abs value of input */
     /* For a negative input, want temp2 = bitwise complement of abs(input) */
     /* This code assumes we are on a two's complement machine */
     temp2--;
   }
   /* Find the number of bits needed for the magnitude of the coefficient */
   nbits = 0;
   while (temp) {
     nbits++;
     temp >>= 1;
   }
   /* Check for out-of-range coefficient values.
    * Since we're encoding a difference, the range limit is twice as much.
    */
   if (nbits > MAX_COEF_BITS+1)
     ERREXIT(state->cinfo, JERR_BAD_DCT_COEF);
   /* Emit the Huffman-coded symbol for the number of bits */
   if (! emit_bits_s(state, dctbl->ehufco[nbits], dctbl->ehufsi[nbits]))
     return FALSE;
   /* Emit that number of bits of the value, if positive, */
   /* or the complement of its magnitude, if negative. */
   if (nbits)            /* emit_bits rejects calls with size 0 */
     if (! emit_bits_s(state, (unsigned int) temp2, nbits))
       return FALSE;
   /* Encode the AC coefficients per section F.1.2.2 */
   r = 0;            /* r = run length of zeros */
   for (k = 1; k <= Se; k++) {
     if ((temp = block[natural_order[k]]) == 0) {
       r++;
     } else {
       /* if run length > 15, must emit special run-length-16 codes (0xF0) */
       while (r > 15) {
     if (! emit_bits_s(state, actbl->ehufco[0xF0], actbl->ehufsi[0xF0]))
       return FALSE;
     r -= 16;
       }
       temp2 = temp;
       if (temp < 0) {
     temp = -temp;       /* temp is abs value of input */
     /* This code assumes we are on a two's complement machine */
     temp2--;
       }
       /* Find the number of bits needed for the magnitude of the coefficient */
       nbits = 1;        /* there must be at least one 1 bit */
       while ((temp >>= 1))
     nbits++;
       /* Check for out-of-range coefficient values */
       if (nbits > MAX_COEF_BITS)
     ERREXIT(state->cinfo, JERR_BAD_DCT_COEF);
       /* Emit Huffman symbol for run length / number of bits */
       i = (r << 4) + nbits;
       if (! emit_bits_s(state, actbl->ehufco[i], actbl->ehufsi[i]))
     return FALSE;
       /* Emit that number of bits of the value, if positive, */
       /* or the complement of its magnitude, if negative. */
       if (! emit_bits_s(state, (unsigned int) temp2, nbits))
     return FALSE;
       r = 0;
     }
   }
   /* If the last coef(s) were zero, emit an end-of-block code */
   if (r > 0)
     if (! emit_bits_s(state, actbl->ehufco[0], actbl->ehufsi[0]))
       return FALSE;
   return TRUE;
 }
References emit_bits_s(), ERREXIT, FALSE, MAX_COEF_BITS, and TRUE.
Referenced by encode_mcu_huff().
finish_pass_gather()
finish_pass_gather (j_compress_ptr cinfo)
Definition at line 1397 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   int ci, tbl;
   jpeg_component_info * compptr;
   JHUFF_TBL **htblptr;
   boolean did_dc[NUM_HUFF_TBLS];
   boolean did_ac[NUM_HUFF_TBLS];
   /* It's important not to apply jpeg_gen_optimal_table more than once
    * per table, because it clobbers the input frequency counts!
    */
   if (cinfo->progressive_mode)
     /* Flush out buffered data (all we care about is counting the EOB symbol) */
     emit_eobrun(entropy);
   MEMZERO(did_dc, SIZEOF(did_dc));
   MEMZERO(did_ac, SIZEOF(did_ac));
   for (ci = 0; ci < cinfo->comps_in_scan; ci++) {
     compptr = cinfo->cur_comp_info[ci];
     /* DC needs no table for refinement scan */
     if (cinfo->Ss == 0 && cinfo->Ah == 0) {
       tbl = compptr->dc_tbl_no;
       if (! did_dc[tbl]) {
     htblptr = & cinfo->dc_huff_tbl_ptrs[tbl];
     if (*htblptr == NULL)
       *htblptr = jpeg_alloc_huff_table((j_common_ptr) cinfo);
     jpeg_gen_optimal_table(cinfo, *htblptr, entropy->dc_count_ptrs[tbl]);
     did_dc[tbl] = TRUE;
       }
     }
     /* AC needs no table when not present */
     if (cinfo->Se) {
       tbl = compptr->ac_tbl_no;
       if (! did_ac[tbl]) {
     htblptr = & cinfo->ac_huff_tbl_ptrs[tbl];
     if (*htblptr == NULL)
       *htblptr = jpeg_alloc_huff_table((j_common_ptr) cinfo);
     jpeg_gen_optimal_table(cinfo, *htblptr, entropy->ac_count_ptrs[tbl]);
     did_ac[tbl] = TRUE;
       }
     }
   }
 }
References huff_entropy_encoder::ac_count_ptrs, jpeg_component_info::ac_tbl_no, compptr, huff_entropy_encoder::dc_count_ptrs, jpeg_component_info::dc_tbl_no, emit_eobrun(), jpeg_alloc_huff_table(), jpeg_gen_optimal_table(), MEMZERO, NULL, NUM_HUFF_TBLS, SIZEOF, and TRUE.
Referenced by start_pass_huff().
finish_pass_huff()
finish_pass_huff (j_compress_ptr cinfo)
Definition at line 1073 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   working_state state;
   if (cinfo->progressive_mode) {
     entropy->next_output_byte = cinfo->dest->next_output_byte;
     entropy->free_in_buffer = cinfo->dest->free_in_buffer;
     /* Flush out any buffered data */
     emit_eobrun(entropy);
     flush_bits_e(entropy);
     cinfo->dest->next_output_byte = entropy->next_output_byte;
     cinfo->dest->free_in_buffer = entropy->free_in_buffer;
   } else {
     /* Load up working state ... flush_bits needs it */
     state.next_output_byte = cinfo->dest->next_output_byte;
     state.free_in_buffer = cinfo->dest->free_in_buffer;
     ASSIGN_STATE(state.cur, entropy->saved);
     state.cinfo = cinfo;
     /* Flush out the last data */
     if (! flush_bits_s(&state))
       ERREXIT(cinfo, JERR_CANT_SUSPEND);
     /* Update state */
     cinfo->dest->next_output_byte = state.next_output_byte;
     cinfo->dest->free_in_buffer = state.free_in_buffer;
     ASSIGN_STATE(entropy->saved, state.cur);
   }
 }
References ASSIGN_STATE, emit_eobrun(), ERREXIT, flush_bits_e(), flush_bits_s(), huff_entropy_encoder::free_in_buffer, huff_entropy_encoder::next_output_byte, and huff_entropy_encoder::saved.
Referenced by start_pass_huff().
flush_bits_e()
flush_bits_e (huff_entropy_ptr entropy)
Definition at line 397 of file jchuff.c.
 {
   emit_bits_e(entropy, 0x7F, 7); /* fill any partial byte with ones */
   entropy->saved.put_buffer = 0; /* and reset bit-buffer to empty */
   entropy->saved.put_bits = 0;
 }
References emit_bits_e().
Referenced by emit_restart_e(), and finish_pass_huff().
flush_bits_s()
flush_bits_s (working_state * state)
Definition at line 386 of file jchuff.c.
 {
   if (! emit_bits_s(state, 0x7F, 7)) /* fill any partial byte with ones */
     return FALSE;
   state->cur.put_buffer = 0;         /* and reset bit-buffer to empty */
   state->cur.put_bits = 0;
   return TRUE;
 }
References emit_bits_s(), FALSE, and TRUE.
Referenced by emit_restart_s(), and finish_pass_huff().
htest_one_block()
htest_one_block (j_compress_ptr cinfo, JCOEFPTR block, int last_dc_val, long dc_counts[], long ac_counts[])
Definition at line 1122 of file jchuff.c.
 {
   register int temp;
   register int nbits;
   register int k, r;
   int Se = cinfo->lim_Se;
   const int * natural_order = cinfo->natural_order;
   /* Encode the DC coefficient difference per section F.1.2.1 */
   temp = block[0] - last_dc_val;
   if (temp < 0)
     temp = -temp;
   /* Find the number of bits needed for the magnitude of the coefficient */
   nbits = 0;
   while (temp) {
     nbits++;
     temp >>= 1;
   }
   /* Check for out-of-range coefficient values.
    * Since we're encoding a difference, the range limit is twice as much.
    */
   if (nbits > MAX_COEF_BITS+1)
     ERREXIT(cinfo, JERR_BAD_DCT_COEF);
   /* Count the Huffman symbol for the number of bits */
   dc_counts[nbits]++;
   /* Encode the AC coefficients per section F.1.2.2 */
   r = 0;            /* r = run length of zeros */
   for (k = 1; k <= Se; k++) {
     if ((temp = block[natural_order[k]]) == 0) {
       r++;
     } else {
       /* if run length > 15, must emit special run-length-16 codes (0xF0) */
       while (r > 15) {
     ac_counts[0xF0]++;
     r -= 16;
       }
       /* Find the number of bits needed for the magnitude of the coefficient */
       if (temp < 0)
     temp = -temp;
       /* Find the number of bits needed for the magnitude of the coefficient */
       nbits = 1;        /* there must be at least one 1 bit */
       while ((temp >>= 1))
     nbits++;
       /* Check for out-of-range coefficient values */
       if (nbits > MAX_COEF_BITS)
     ERREXIT(cinfo, JERR_BAD_DCT_COEF);
       /* Count Huffman symbol for run length / number of bits */
       ac_counts[(r << 4) + nbits]++;
       r = 0;
     }
   }
   /* If the last coef(s) were zero, emit an end-of-block code */
   if (r > 0)
     ac_counts[0]++;
 }
References ERREXIT, and MAX_COEF_BITS.
Referenced by encode_mcu_gather().
jinit_huff_encoder()
jinit_huff_encoder (j_compress_ptr cinfo)
Definition at line 1557 of file jchuff.c.
 {
   huff_entropy_ptr entropy;
   int i;
   entropy = (huff_entropy_ptr)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 SIZEOF(huff_entropy_encoder));
   cinfo->entropy = (struct jpeg_entropy_encoder *) entropy;
   entropy->pub.start_pass = start_pass_huff;
   /* Mark tables unallocated */
   for (i = 0; i < NUM_HUFF_TBLS; i++) {
     entropy->dc_derived_tbls[i] = entropy->ac_derived_tbls[i] = NULL;
     entropy->dc_count_ptrs[i] = entropy->ac_count_ptrs[i] = NULL;
   }
   if (cinfo->progressive_mode)
     entropy->bit_buffer = NULL; /* needed only in AC refinement scan */
 }
References huff_entropy_encoder::ac_count_ptrs, huff_entropy_encoder::ac_derived_tbls, huff_entropy_encoder::bit_buffer, huff_entropy_encoder::dc_count_ptrs, huff_entropy_encoder::dc_derived_tbls, JPOOL_IMAGE, NULL, NUM_HUFF_TBLS, huff_entropy_encoder::pub, SIZEOF, and start_pass_huff().
Referenced by jinit_compress_master(), and transencode_master_selection().
jpeg_gen_optimal_table()
jpeg_gen_optimal_table (j_compress_ptr cinfo, JHUFF_TBL * htbl, long freq[])
Definition at line 1256 of file jchuff.c.
 {
 #define MAX_CLEN 32     /* assumed maximum initial code length */
   UINT8 bits[MAX_CLEN+1];   /* bits[k] = # of symbols with code length k */
   int codesize[257];        /* codesize[k] = code length of symbol k */
   int others[257];      /* next symbol in current branch of tree */
   int c1, c2;
   int p, i, j;
   long v;
   /* This algorithm is explained in section K.2 of the JPEG standard */
   MEMZERO(bits, SIZEOF(bits));
   MEMZERO(codesize, SIZEOF(codesize));
   for (i = 0; i < 257; i++)
     others[i] = -1;     /* init links to empty */
   freq[256] = 1;        /* make sure 256 has a nonzero count */
   /* Including the pseudo-symbol 256 in the Huffman procedure guarantees
    * that no real symbol is given code-value of all ones, because 256
    * will be placed last in the largest codeword category.
    */
   /* Huffman's basic algorithm to assign optimal code lengths to symbols */
   for (;;) {
     /* Find the smallest nonzero frequency, set c1 = its symbol */
     /* In case of ties, take the larger symbol number */
     c1 = -1;
     v = 1000000000L;
     for (i = 0; i <= 256; i++) {
       if (freq[i] && freq[i] <= v) {
     v = freq[i];
     c1 = i;
       }
     }
     /* Find the next smallest nonzero frequency, set c2 = its symbol */
     /* In case of ties, take the larger symbol number */
     c2 = -1;
     v = 1000000000L;
     for (i = 0; i <= 256; i++) {
       if (freq[i] && freq[i] <= v && i != c1) {
     v = freq[i];
     c2 = i;
       }
     }
     /* Done if we've merged everything into one frequency */
     if (c2 < 0)
       break;
     /* Else merge the two counts/trees */
     freq[c1] += freq[c2];
     freq[c2] = 0;
     /* Increment the codesize of everything in c1's tree branch */
     codesize[c1]++;
     while (others[c1] >= 0) {
       c1 = others[c1];
       codesize[c1]++;
     }
     others[c1] = c2;        /* chain c2 onto c1's tree branch */
     /* Increment the codesize of everything in c2's tree branch */
     codesize[c2]++;
     while (others[c2] >= 0) {
       c2 = others[c2];
       codesize[c2]++;
     }
   }
   /* Now count the number of symbols of each code length */
   for (i = 0; i <= 256; i++) {
     if (codesize[i]) {
       /* The JPEG standard seems to think that this can't happen, */
       /* but I'm paranoid... */
       if (codesize[i] > MAX_CLEN)
     ERREXIT(cinfo, JERR_HUFF_CLEN_OVERFLOW);
       bits[codesize[i]]++;
     }
   }
   /* JPEG doesn't allow symbols with code lengths over 16 bits, so if the pure
    * Huffman procedure assigned any such lengths, we must adjust the coding.
    * Here is what the JPEG spec says about how this next bit works:
    * Since symbols are paired for the longest Huffman code, the symbols are
    * removed from this length category two at a time.  The prefix for the pair
    * (which is one bit shorter) is allocated to one of the pair; then,
    * skipping the BITS entry for that prefix length, a code word from the next
    * shortest nonzero BITS entry is converted into a prefix for two code words
    * one bit longer.
    */
   for (i = MAX_CLEN; i > 16; i--) {
     while (bits[i] > 0) {
       j = i - 2;        /* find length of new prefix to be used */
       while (bits[j] == 0)
     j--;
       bits[i] -= 2;     /* remove two symbols */
       bits[i-1]++;      /* one goes in this length */
       bits[j+1] += 2;       /* two new symbols in this length */
       bits[j]--;        /* symbol of this length is now a prefix */
     }
   }
   /* Remove the count for the pseudo-symbol 256 from the largest codelength */
   while (bits[i] == 0)      /* find largest codelength still in use */
     i--;
   bits[i]--;
   /* Return final symbol counts (only for lengths 0..16) */
   MEMCOPY(htbl->bits, bits, SIZEOF(htbl->bits));
   /* Return a list of the symbols sorted by code length */
   /* It's not real clear to me why we don't need to consider the codelength
    * changes made above, but the JPEG spec seems to think this works.
    */
   p = 0;
   for (i = 1; i <= MAX_CLEN; i++) {
     for (j = 0; j <= 255; j++) {
       if (codesize[j] == i) {
     htbl->huffval[p] = (UINT8) j;
     p++;
       }
     }
   }
   /* Set sent_table FALSE so updated table will be written to JPEG file. */
   htbl->sent_table = FALSE;
 }
References bits(), ERREXIT, FALSE, MAX_CLEN, MEMCOPY, MEMZERO, and SIZEOF.
Referenced by finish_pass_gather().
jpeg_make_c_derived_tbl()
jpeg_make_c_derived_tbl (j_compress_ptr cinfo, boolean isDC, int tblno, c_derived_tbl ** pdtbl)
Definition at line 161 of file jchuff.c.
 {
   JHUFF_TBL *htbl;
   c_derived_tbl *dtbl;
   int p, i, l, lastp, si, maxsymbol;
   char huffsize[257];
   unsigned int huffcode[257];
   unsigned int code;
   /* Note that huffsize[] and huffcode[] are filled in code-length order,
    * paralleling the order of the symbols themselves in htbl->huffval[].
    */
   /* Find the input Huffman table */
   if (tblno < 0 || tblno >= NUM_HUFF_TBLS)
     ERREXIT1(cinfo, JERR_NO_HUFF_TABLE, tblno);
   htbl =
     isDC ? cinfo->dc_huff_tbl_ptrs[tblno] : cinfo->ac_huff_tbl_ptrs[tblno];
   if (htbl == NULL)
     ERREXIT1(cinfo, JERR_NO_HUFF_TABLE, tblno);
   /* Allocate a workspace if we haven't already done so. */
   if (*pdtbl == NULL)
     *pdtbl = (c_derived_tbl *)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                   SIZEOF(c_derived_tbl));
   dtbl = *pdtbl;
   /* Figure C.1: make table of Huffman code length for each symbol */
   p = 0;
   for (l = 1; l <= 16; l++) {
     i = (int) htbl->bits[l];
     if (i < 0 || p + i > 256)   /* protect against table overrun */
       ERREXIT(cinfo, JERR_BAD_HUFF_TABLE);
     while (i--)
       huffsize[p++] = (char) l;
   }
   huffsize[p] = 0;
   lastp = p;
   /* Figure C.2: generate the codes themselves */
   /* We also validate that the counts represent a legal Huffman code tree. */
   code = 0;
   si = huffsize[0];
   p = 0;
   while (huffsize[p]) {
     while (((int) huffsize[p]) == si) {
       huffcode[p++] = code;
       code++;
     }
     /* code is now 1 more than the last code used for codelength si; but
      * it must still fit in si bits, since no code is allowed to be all ones.
      */
     if (((INT32) code) >= (((INT32) 1) << si))
       ERREXIT(cinfo, JERR_BAD_HUFF_TABLE);
     code <<= 1;
     si++;
   }
   /* Figure C.3: generate encoding tables */
   /* These are code and size indexed by symbol value */
   /* Set all codeless symbols to have code length 0;
    * this lets us detect duplicate VAL entries here, and later
    * allows emit_bits to detect any attempt to emit such symbols.
    */
   MEMZERO(dtbl->ehufsi, SIZEOF(dtbl->ehufsi));
   /* This is also a convenient place to check for out-of-range
    * and duplicated VAL entries.  We allow 0..255 for AC symbols
    * but only 0..15 for DC.  (We could constrain them further
    * based on data depth and mode, but this seems enough.)
    */
   maxsymbol = isDC ? 15 : 255;
   for (p = 0; p < lastp; p++) {
     i = htbl->huffval[p];
     if (i < 0 || i > maxsymbol || dtbl->ehufsi[i])
       ERREXIT(cinfo, JERR_BAD_HUFF_TABLE);
     dtbl->ehufco[i] = huffcode[p];
     dtbl->ehufsi[i] = huffsize[p];
   }
 }
References JHUFF_TBL::bits, code, c_derived_tbl::ehufco, c_derived_tbl::ehufsi, ERREXIT, ERREXIT1, JHUFF_TBL::huffval, int(), JPOOL_IMAGE, MEMZERO, NULL, NUM_HUFF_TBLS, si, and SIZEOF.
Referenced by start_pass_huff().
start_pass_huff()
start_pass_huff (j_compress_ptr cinfo, boolean gather_statistics)
Definition at line 1451 of file jchuff.c.
 {
   huff_entropy_ptr entropy = (huff_entropy_ptr) cinfo->entropy;
   int ci, tbl;
   jpeg_component_info * compptr;
   if (gather_statistics)
     entropy->pub.finish_pass = finish_pass_gather;
   else
     entropy->pub.finish_pass = finish_pass_huff;
   if (cinfo->progressive_mode) {
     entropy->cinfo = cinfo;
     entropy->gather_statistics = gather_statistics;
     /* We assume jcmaster.c already validated the scan parameters. */
     /* Select execution routine */
     if (cinfo->Ah == 0) {
       if (cinfo->Ss == 0)
     entropy->pub.encode_mcu = encode_mcu_DC_first;
       else
     entropy->pub.encode_mcu = encode_mcu_AC_first;
     } else {
       if (cinfo->Ss == 0)
     entropy->pub.encode_mcu = encode_mcu_DC_refine;
       else {
     entropy->pub.encode_mcu = encode_mcu_AC_refine;
     /* AC refinement needs a correction bit buffer */
     if (entropy->bit_buffer == NULL)
       entropy->bit_buffer = (char *)
         (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                     MAX_CORR_BITS * SIZEOF(char));
       }
     }
     /* Initialize AC stuff */
     entropy->ac_tbl_no = cinfo->cur_comp_info[0]->ac_tbl_no;
     entropy->EOBRUN = 0;
     entropy->BE = 0;
   } else {
     if (gather_statistics)
       entropy->pub.encode_mcu = encode_mcu_gather;
     else
       entropy->pub.encode_mcu = encode_mcu_huff;
   }
   for (ci = 0; ci < cinfo->comps_in_scan; ci++) {
     compptr = cinfo->cur_comp_info[ci];
     /* DC needs no table for refinement scan */
     if (cinfo->Ss == 0 && cinfo->Ah == 0) {
       tbl = compptr->dc_tbl_no;
       if (gather_statistics) {
     /* Check for invalid table index */
     /* (make_c_derived_tbl does this in the other path) */
     if (tbl < 0 || tbl >= NUM_HUFF_TBLS)
       ERREXIT1(cinfo, JERR_NO_HUFF_TABLE, tbl);
     /* Allocate and zero the statistics tables */
     /* Note that jpeg_gen_optimal_table expects 257 entries in each table! */
     if (entropy->dc_count_ptrs[tbl] == NULL)
       entropy->dc_count_ptrs[tbl] = (long *)
         (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                     257 * SIZEOF(long));
     MEMZERO(entropy->dc_count_ptrs[tbl], 257 * SIZEOF(long));
       } else {
     /* Compute derived values for Huffman tables */
     /* We may do this more than once for a table, but it's not expensive */
     jpeg_make_c_derived_tbl(cinfo, TRUE, tbl,
                 & entropy->dc_derived_tbls[tbl]);
       }
       /* Initialize DC predictions to 0 */
       entropy->saved.last_dc_val[ci] = 0;
     }
     /* AC needs no table when not present */
     if (cinfo->Se) {
       tbl = compptr->ac_tbl_no;
       if (gather_statistics) {
     if (tbl < 0 || tbl >= NUM_HUFF_TBLS)
       ERREXIT1(cinfo, JERR_NO_HUFF_TABLE, tbl);
     if (entropy->ac_count_ptrs[tbl] == NULL)
       entropy->ac_count_ptrs[tbl] = (long *)
         (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                     257 * SIZEOF(long));
     MEMZERO(entropy->ac_count_ptrs[tbl], 257 * SIZEOF(long));
       } else {
     jpeg_make_c_derived_tbl(cinfo, FALSE, tbl,
                 & entropy->ac_derived_tbls[tbl]);
       }
     }
   }
   /* Initialize bit buffer to empty */
   entropy->saved.put_buffer = 0;
   entropy->saved.put_bits = 0;
   /* Initialize restart stuff */
   entropy->restarts_to_go = cinfo->restart_interval;
   entropy->next_restart_num = 0;
 }
References huff_entropy_encoder::ac_count_ptrs, huff_entropy_encoder::ac_derived_tbls, huff_entropy_encoder::ac_tbl_no, jpeg_component_info::ac_tbl_no, huff_entropy_encoder::BE, huff_entropy_encoder::bit_buffer, huff_entropy_encoder::cinfo, compptr, huff_entropy_encoder::dc_count_ptrs, huff_entropy_encoder::dc_derived_tbls, jpeg_component_info::dc_tbl_no, encode_mcu_AC_first(), encode_mcu_AC_refine(), encode_mcu_DC_first(), encode_mcu_DC_refine(), encode_mcu_gather(), encode_mcu_huff(), huff_entropy_encoder::EOBRUN, ERREXIT1, FALSE, finish_pass_gather(), finish_pass_huff(), huff_entropy_encoder::gather_statistics, jpeg_make_c_derived_tbl(), JPOOL_IMAGE, savable_state::last_dc_val, MAX_CORR_BITS, MEMZERO, huff_entropy_encoder::next_restart_num, NULL, NUM_HUFF_TBLS, huff_entropy_encoder::pub, savable_state::put_bits, savable_state::put_buffer, huff_entropy_encoder::restarts_to_go, huff_entropy_encoder::saved, SIZEOF, and TRUE.
Referenced by jinit_huff_encoder().