ZEQ2-Lite: Engine/client/snd_codec.c File Reference
snd_codec.c File Reference
#include "client.h"
#include "snd_codec.h"
Functions
void S_CodecCloseStream (snd_stream_t *stream)
static void * S_CodecGetSound (const char *filename, snd_info_t *info)
void S_CodecInit ()
void * S_CodecLoad (const char *filename, snd_info_t *info)
snd_stream_t * S_CodecOpenStream (const char *filename)
int S_CodecReadStream (snd_stream_t *stream, int bytes, void *buffer)
void S_CodecRegister (snd_codec_t *codec)
void S_CodecShutdown ()
void S_CodecUtilClose (snd_stream_t **stream)
snd_stream_t * S_CodecUtilOpen (const char *filename, snd_codec_t *codec)
Variables
static snd_codec_t * codecs
Function Documentation
S_CodecCloseStream()
void S_CodecCloseStream (snd_stream_t * stream)
Definition at line 176 of file snd_codec.c.
 {
     stream->codec->close(stream);
 }
Referenced by S_Base_StartBackgroundTrack(), S_Base_StopBackgroundTrack(), and S_UpdateBackgroundTrack().
S_CodecGetSound()
static void* S_CodecGetSound (const char * filename, snd_info_t * info) static
Definition at line 37 of file snd_codec.c.
 {
     snd_codec_t *codec;
     snd_codec_t *orgCodec = NULL;
     qboolean    orgNameFailed = qfalse;
     char        localName[ MAX_QPATH ];
     const char  *ext;
     char        altName[ MAX_QPATH ];
     void        *rtn = NULL;
     Q_strncpyz(localName, filename, MAX_QPATH);
     ext = COM_GetExtension(localName);
     if( *ext )
     {
         // Look for the correct loader and use it
         for( codec = codecs; codec; codec = codec->next )
         {
             if( !Q_stricmp( ext, codec->ext ) )
             {
                 // Load
                 if( info )
                     rtn = codec->load(localName, info);
                 else
                     rtn = codec->open(localName);
                 break;
             }
         }
         // A loader was found
         if( codec )
         {
             if( !rtn )
             {
                 // Loader failed, most likely because the file isn't there;
                 // try again without the extension
                 orgNameFailed = qtrue;
                 orgCodec = codec;
                 COM_StripExtension( filename, localName, MAX_QPATH );
             }
             else
             {
                 // Something loaded
                 return rtn;
             }
         }
     }
     // Try and find a suitable match using all
     // the sound codecs supported
     for( codec = codecs; codec; codec = codec->next )
     {
         if( codec == orgCodec )
             continue;
         Com_sprintf( altName, sizeof (altName), "%s.%s", localName, codec->ext );
         // Load
         if( info )
             rtn = codec->load(altName, info);
         else
             rtn = codec->open(altName);
         if( rtn )
         {
             if( orgNameFailed )
             {
                 Com_DPrintf(S_COLOR_YELLOW "WARNING: %s not present, using %s instead\n",
                         filename, altName );
             }
             return rtn;
         }
     }
     Com_Printf(S_COLOR_YELLOW "WARNING: Failed to %s sound %s!\n", info ? "load" : "open", filename);
     return NULL;
 }
References codecs, Com_DPrintf(), COM_GetExtension(), Com_Printf(), Com_sprintf(), COM_StripExtension(), ext, info, MAX_QPATH, NULL, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, and S_COLOR_YELLOW.
Referenced by S_CodecLoad(), and S_CodecOpenStream().
S_CodecInit()
void S_CodecInit ()
Definition at line 123 of file snd_codec.c.
 {
     codecs = NULL;
 #ifdef USE_CODEC_VORBIS
     S_CodecRegister(&ogg_codec);
 #endif
 // Register wav codec last so that it is always tried first when a file extension was not found
     S_CodecRegister(&wav_codec);
 }
References codecs, NULL, S_CodecRegister(), and wav_codec.
Referenced by S_Init().
S_CodecLoad()
void* S_CodecLoad (const char * filename, snd_info_t * info)
Definition at line 161 of file snd_codec.c.
 {
     return S_CodecGetSound(filename, info);
 }
References info, and S_CodecGetSound().
Referenced by S_LoadSound().
S_CodecOpenStream()
snd_stream_t* S_CodecOpenStream (const char * filename)
Definition at line 171 of file snd_codec.c.
 {
     return S_CodecGetSound(filename, NULL);
 }
References NULL, and S_CodecGetSound().
Referenced by S_Base_StartBackgroundTrack().
S_CodecReadStream()
int S_CodecReadStream (snd_stream_t * stream, int bytes, void * buffer)
Definition at line 181 of file snd_codec.c.
 {
     return stream->codec->read(stream, bytes, buffer);
 }
Referenced by S_UpdateBackgroundTrack().
S_CodecRegister()
void S_CodecRegister (snd_codec_t * codec)
Definition at line 150 of file snd_codec.c.
 {
     codec->next = codecs;
     codecs = codec;
 }
References codecs.
Referenced by S_CodecInit().
S_CodecShutdown()
void S_CodecShutdown ()
Definition at line 140 of file snd_codec.c.
 {
     codecs = NULL;
 }
References codecs, and NULL.
Referenced by S_Shutdown().
S_CodecUtilClose()
void S_CodecUtilClose (snd_stream_t ** stream)
Definition at line 228 of file snd_codec.c.
 {
     FS_FCloseFile((*stream)->file);
     Z_Free(*stream);
     *stream = NULL;
 }
References FS_FCloseFile(), NULL, and Z_Free().
Referenced by S_WAV_CodecCloseStream(), and S_WAV_CodecOpenStream().
S_CodecUtilOpen()
snd_stream_t* S_CodecUtilOpen (const char * filename, snd_codec_t * codec)
Definition at line 194 of file snd_codec.c.
 {
     snd_stream_t *stream;
     fileHandle_t hnd;
     int length;
     // Try to open the file
     length = FS_FOpenFileRead(filename, &hnd, qtrue);
     if(!hnd)
     {
         Com_DPrintf("Can't read sound file %s\n", filename);
         return NULL;
     }
     // Allocate a stream
     stream = Z_Malloc(sizeof(snd_stream_t));
     if(!stream)
     {
         FS_FCloseFile(hnd);
         return NULL;
     }
     // Copy over, return
     stream->codec = codec;
     stream->file = hnd;
     stream->length = length;
     return stream;
 }
References Com_DPrintf(), FS_FCloseFile(), FS_FOpenFileRead(), NULL, qtrue, and Z_Malloc.
Referenced by S_WAV_CodecOpenStream().
Variable Documentation
codecs
snd_codec_t* codecs static
Definition at line 27 of file snd_codec.c.
Referenced by S_CodecGetSound(), S_CodecInit(), S_CodecRegister(), and S_CodecShutdown().