ZEQ2-Lite: Tools/MinGW/include/gdiplus/gdiplusflat.h File Reference
gdiplusflat.h File Reference
Functions
GpStatus WINGDIPAPI GdipAddPathArc (GpPath *, REAL, REAL, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipAddPathArcI (GpPath *, INT, INT, INT, INT, REAL, REAL)
GpStatus WINGDIPAPI GdipAddPathBezier (GpPath *, REAL, REAL, REAL, REAL, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipAddPathBezierI (GpPath *, INT, INT, INT, INT, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipAddPathBeziers (GpPath *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipAddPathBeziersI (GpPath *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipAddPathClosedCurve (GpPath *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipAddPathClosedCurve2 (GpPath *, GDIPCONST GpPointF *, INT, REAL)
GpStatus WINGDIPAPI GdipAddPathClosedCurve2I (GpPath *, GDIPCONST GpPoint *, INT, REAL)
GpStatus WINGDIPAPI GdipAddPathClosedCurveI (GpPath *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipAddPathCurve (GpPath *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipAddPathCurve2 (GpPath *, GDIPCONST GpPointF *, INT, REAL)
GpStatus WINGDIPAPI GdipAddPathCurve2I (GpPath *, GDIPCONST GpPoint *, INT, REAL)
GpStatus WINGDIPAPI GdipAddPathCurve3 (GpPath *, GDIPCONST GpPointF *, INT, INT, INT, REAL)
GpStatus WINGDIPAPI GdipAddPathCurve3I (GpPath *, GDIPCONST GpPoint *, INT, INT, INT, REAL)
GpStatus WINGDIPAPI GdipAddPathCurveI (GpPath *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipAddPathEllipse (GpPath *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipAddPathEllipseI (GpPath *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipAddPathLine (GpPath *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipAddPathLine2 (GpPath *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipAddPathLine2I (GpPath *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipAddPathLineI (GpPath *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipAddPathPath (GpPath *, GDIPCONST GpPath *, BOOL)
GpStatus WINGDIPAPI GdipAddPathPie (GpPath *, REAL, REAL, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipAddPathPieI (GpPath *, INT, INT, INT, INT, REAL, REAL)
GpStatus WINGDIPAPI GdipAddPathPolygon (GpPath *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipAddPathPolygonI (GpPath *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipAddPathRectangle (GpPath *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipAddPathRectangleI (GpPath *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipAddPathRectangles (GpPath *, GDIPCONST GpRectF *, INT)
GpStatus WINGDIPAPI GdipAddPathRectanglesI (GpPath *, GDIPCONST GpRect *, INT)
GpStatus WINGDIPAPI GdipAddPathString (GpPath *, GDIPCONST WCHAR *, INT, GDIPCONST GpFontFamily *, INT, REAL, GDIPCONST RectF *, GDIPCONST GpStringFormat *)
GpStatus WINGDIPAPI GdipAddPathStringI (GpPath *, GDIPCONST WCHAR *, INT, GDIPCONST GpFontFamily *, INT, REAL, GDIPCONST Rect *, GDIPCONST GpStringFormat *)
GpStatus WINGDIPAPI GdipBeginContainer (GpGraphics *, GDIPCONST GpRectF *, GDIPCONST GpRectF *, GpUnit, GraphicsContainer *)
GpStatus WINGDIPAPI GdipBeginContainer2 (GpGraphics *, GraphicsContainer *)
GpStatus WINGDIPAPI GdipBeginContainerI (GpGraphics *, GDIPCONST GpRect *, GDIPCONST GpRect *, GpUnit, GraphicsContainer *)
GpStatus WINGDIPAPI GdipBitmapApplyEffect (GpBitmap *, CGpEffect *, RECT *, BOOL, VOID **, INT *)
GpStatus WINGDIPAPI GdipBitmapConvertFormat (GpBitmap *, PixelFormat, DitherType, PaletteType, ColorPalette *, REAL)
GpStatus WINGDIPAPI GdipBitmapCreateApplyEffect (GpBitmap **, INT, CGpEffect *, RECT *, RECT *, GpBitmap **, BOOL, VOID **, INT *)
GpStatus WINGDIPAPI GdipBitmapGetHistogram (GpBitmap *, HistogramFormat, UINT, UINT *, UINT *, UINT *, UINT *)
GpStatus WINGDIPAPI GdipBitmapGetHistogramSize (HistogramFormat, UINT *)
GpStatus WINGDIPAPI GdipBitmapGetPixel (GpBitmap *, INT, INT, ARGB *)
GpStatus WINGDIPAPI GdipBitmapLockBits (GpBitmap *, GDIPCONST GpRect *, UINT, PixelFormat, BitmapData *)
GpStatus WINGDIPAPI GdipBitmapSetPixel (GpBitmap *, INT, INT, ARGB)
GpStatus WINGDIPAPI GdipBitmapSetResolution (GpBitmap *, REAL, REAL)
GpStatus WINGDIPAPI GdipBitmapUnlockBits (GpBitmap *, BitmapData *)
GpStatus WINGDIPAPI GdipClearPathMarkers (GpPath *)
GpStatus WINGDIPAPI GdipCloneBitmapArea (REAL, REAL, REAL, REAL, PixelFormat, GpBitmap *, GpBitmap **)
GpStatus WINGDIPAPI GdipCloneBitmapAreaI (INT, INT, INT, INT, PixelFormat, GpBitmap *, GpBitmap **)
GpStatus WINGDIPAPI GdipCloneBrush (GpBrush *, GpBrush **)
GpStatus WINGDIPAPI GdipCloneCustomLineCap (GpCustomLineCap *, GpCustomLineCap **)
GpStatus WINGDIPAPI GdipCloneFont (GpFont *, GpFont **)
GpStatus WINGDIPAPI GdipCloneFontFamily (GpFontFamily *, GpFontFamily **)
GpStatus WINGDIPAPI GdipCloneImage (GpImage *, GpImage **)
GpStatus WINGDIPAPI GdipCloneImageAttributes (GDIPCONST GpImageAttributes *, GpImageAttributes **)
GpStatus WINGDIPAPI GdipCloneMatrix (GpMatrix *, GpMatrix **)
GpStatus WINGDIPAPI GdipClonePath (GpPath *, GpPath **)
GpStatus WINGDIPAPI GdipClonePen (GpPen *, GpPen **)
GpStatus WINGDIPAPI GdipCloneRegion (GpRegion *, GpRegion **)
GpStatus WINGDIPAPI GdipCloneStringFormat (GDIPCONST GpStringFormat *, GpStringFormat **)
GpStatus WINGDIPAPI GdipClosePathFigure (GpPath *)
GpStatus WINGDIPAPI GdipClosePathFigures (GpPath *)
GpStatus WINGDIPAPI GdipCombineRegionPath (GpRegion *, GpPath *, CombineMode)
GpStatus WINGDIPAPI GdipCombineRegionRect (GpRegion *, GDIPCONST GpRectF *, CombineMode)
GpStatus WINGDIPAPI GdipCombineRegionRectI (GpRegion *, GDIPCONST GpRect *, CombineMode)
GpStatus WINGDIPAPI GdipCombineRegionRegion (GpRegion *, GpRegion *, CombineMode)
GpStatus WINGDIPAPI GdipComment (GpGraphics *, UINT, GDIPCONST BYTE *)
GpStatus WINGDIPAPI GdipConvertToEmfPlus (GDIPCONST GpGraphics *, GpMetafile *, BOOL *, EmfType, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipConvertToEmfPlusToFile (GDIPCONST GpGraphics *, GpMetafile *, BOOL *, GDIPCONST WCHAR *, EmfType, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipConvertToEmfPlusToStream (GDIPCONST GpGraphics *, GpMetafile *, BOOL *, IStream *, EmfType, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipCreateAdjustableArrowCap (REAL, REAL, BOOL, GpAdjustableArrowCap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromDirectDrawSurface (IDirectDrawSurface7 *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromFile (GDIPCONST WCHAR *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromFileICM (GDIPCONST WCHAR *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromGdiDib (GDIPCONST BITMAPINFO *, VOID *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromGraphics (INT, INT, GpGraphics *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromHBITMAP (HBITMAP, HPALETTE, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromHICON (HICON, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromResource (HINSTANCE, GDIPCONST WCHAR *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromScan0 (INT, INT, INT, PixelFormat, BYTE *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromStream (IStream *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateBitmapFromStreamICM (IStream *, GpBitmap **)
GpStatus WINGDIPAPI GdipCreateCachedBitmap (GpBitmap *, GpGraphics *, GpCachedBitmap **)
GpStatus WINGDIPAPI GdipCreateCustomLineCap (GpPath *, GpPath *, GpLineCap, REAL, GpCustomLineCap **)
GpStatus WINGDIPAPI GdipCreateEffect (GDIPCONST GUID, CGpEffect **)
GpStatus WINGDIPAPI GdipCreateFont (GDIPCONST GpFontFamily *, REAL, INT, Unit, GpFont **)
GpStatus WINGDIPAPI GdipCreateFontFamilyFromName (GDIPCONST WCHAR *, GpFontCollection *, GpFontFamily **)
GpStatus WINGDIPAPI GdipCreateFontFromDC (HDC, GpFont **)
GpStatus WINGDIPAPI GdipCreateFontFromLogfontA (HDC, GDIPCONST LOGFONTA *, GpFont **)
GpStatus WINGDIPAPI GdipCreateFontFromLogfontW (HDC, GDIPCONST LOGFONTW *, GpFont **)
GpStatus WINGDIPAPI GdipCreateFromHDC (HDC, GpGraphics **)
GpStatus WINGDIPAPI GdipCreateFromHDC2 (HDC, HANDLE, GpGraphics **)
GpStatus WINGDIPAPI GdipCreateFromHWND (HWND, GpGraphics **)
GpStatus WINGDIPAPI GdipCreateFromHWNDICM (HWND, GpGraphics **)
HPALETTE WINGDIPAPI GdipCreateHalftonePalette (void)
GpStatus WINGDIPAPI GdipCreateHatchBrush (GpHatchStyle, ARGB, ARGB, GpHatch **)
GpStatus WINGDIPAPI GdipCreateHBITMAPFromBitmap (GpBitmap *, HBITMAP *, ARGB)
GpStatus WINGDIPAPI GdipCreateHICONFromBitmap (GpBitmap *, HICON *)
GpStatus WINGDIPAPI GdipCreateImageAttributes (GpImageAttributes **)
GpStatus WINGDIPAPI GdipCreateLineBrush (GDIPCONST GpPointF *, GDIPCONST GpPointF *, ARGB, ARGB, GpWrapMode, GpLineGradient **)
GpStatus WINGDIPAPI GdipCreateLineBrushFromRect (GDIPCONST GpRectF *, ARGB, ARGB, LinearGradientMode, GpWrapMode, GpLineGradient **)
GpStatus WINGDIPAPI GdipCreateLineBrushFromRectI (GDIPCONST GpRect *, ARGB, ARGB, LinearGradientMode, GpWrapMode, GpLineGradient **)
GpStatus WINGDIPAPI GdipCreateLineBrushFromRectWithAngle (GDIPCONST GpRectF *, ARGB, ARGB, REAL, BOOL, GpWrapMode, GpLineGradient **)
GpStatus WINGDIPAPI GdipCreateLineBrushFromRectWithAngleI (GDIPCONST GpRect *, ARGB, ARGB, REAL, BOOL, GpWrapMode, GpLineGradient **)
GpStatus WINGDIPAPI GdipCreateLineBrushI (GDIPCONST GpPoint *, GDIPCONST GpPoint *, ARGB, ARGB, GpWrapMode, GpLineGradient **)
GpStatus WINGDIPAPI GdipCreateMatrix (GpMatrix **)
GpStatus WINGDIPAPI GdipCreateMatrix2 (REAL, REAL, REAL, REAL, REAL, REAL, GpMatrix **)
GpStatus WINGDIPAPI GdipCreateMatrix3 (GDIPCONST GpRectF *, GDIPCONST GpPointF *, GpMatrix **)
GpStatus WINGDIPAPI GdipCreateMatrix3I (GDIPCONST GpRect *, GDIPCONST GpPoint *, GpMatrix **)
GpStatus WINGDIPAPI GdipCreateMetafileFromEmf (HENHMETAFILE, BOOL, GpMetafile **)
GpStatus WINGDIPAPI GdipCreateMetafileFromFile (GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipCreateMetafileFromStream (IStream *, GpMetafile **)
GpStatus WINGDIPAPI GdipCreateMetafileFromWmf (HMETAFILE, BOOL, GDIPCONST WmfPlaceableFileHeader *, GpMetafile **)
GpStatus WINGDIPAPI GdipCreateMetafileFromWmfFile (GDIPCONST WCHAR *, GDIPCONST WmfPlaceableFileHeader *, GpMetafile **)
GpStatus WINGDIPAPI GdipCreatePath (GpFillMode, GpPath **)
GpStatus WINGDIPAPI GdipCreatePath2 (GDIPCONST GpPointF *, GDIPCONST BYTE *, INT, GpFillMode, GpPath **)
GpStatus WINGDIPAPI GdipCreatePath2I (GDIPCONST GpPoint *, GDIPCONST BYTE *, INT, GpFillMode, GpPath **)
GpStatus WINGDIPAPI GdipCreatePathGradient (GDIPCONST GpPointF *, INT, GpWrapMode, GpPathGradient **)
GpStatus WINGDIPAPI GdipCreatePathGradientFromPath (GDIPCONST GpPath *, GpPathGradient **)
GpStatus WINGDIPAPI GdipCreatePathGradientI (GDIPCONST GpPoint *, INT, GpWrapMode, GpPathGradient **)
GpStatus WINGDIPAPI GdipCreatePathIter (GpPathIterator **, GpPath *)
GpStatus WINGDIPAPI GdipCreatePen1 (ARGB, REAL, GpUnit, GpPen **)
GpStatus WINGDIPAPI GdipCreatePen2 (GpBrush *, REAL, GpUnit, GpPen **)
GpStatus WINGDIPAPI GdipCreateRegion (GpRegion **)
GpStatus WINGDIPAPI GdipCreateRegionHrgn (HRGN, GpRegion **)
GpStatus WINGDIPAPI GdipCreateRegionPath (GpPath *, GpRegion **)
GpStatus WINGDIPAPI GdipCreateRegionRect (GDIPCONST GpRectF *, GpRegion **)
GpStatus WINGDIPAPI GdipCreateRegionRectI (GDIPCONST GpRect *, GpRegion **)
GpStatus WINGDIPAPI GdipCreateRegionRgnData (GDIPCONST BYTE *, INT, GpRegion **)
GpStatus WINGDIPAPI GdipCreateSolidFill (ARGB, GpSolidFill **)
GpStatus WINGDIPAPI GdipCreateStreamOnFile (GDIPCONST WCHAR *, UINT, IStream **)
GpStatus WINGDIPAPI GdipCreateStringFormat (INT, LANGID, GpStringFormat **)
GpStatus WINGDIPAPI GdipCreateTexture (GpImage *, GpWrapMode, GpTexture **)
GpStatus WINGDIPAPI GdipCreateTexture2 (GpImage *, GpWrapMode, REAL, REAL, REAL, REAL, GpTexture **)
GpStatus WINGDIPAPI GdipCreateTexture2I (GpImage *, GpWrapMode, INT, INT, INT, INT, GpTexture **)
GpStatus WINGDIPAPI GdipCreateTextureIA (GpImage *, GDIPCONST GpImageAttributes *, REAL, REAL, REAL, REAL, GpTexture **)
GpStatus WINGDIPAPI GdipCreateTextureIAI (GpImage *, GDIPCONST GpImageAttributes *, INT, INT, INT, INT, GpTexture **)
GpStatus WINGDIPAPI GdipDeleteBrush (GpBrush *)
GpStatus WINGDIPAPI GdipDeleteCachedBitmap (GpCachedBitmap *)
GpStatus WINGDIPAPI GdipDeleteCustomLineCap (GpCustomLineCap *)
GpStatus WINGDIPAPI GdipDeleteEffect (CGpEffect *)
GpStatus WINGDIPAPI GdipDeleteFont (GpFont *)
GpStatus WINGDIPAPI GdipDeleteFontFamily (GpFontFamily *)
GpStatus WINGDIPAPI GdipDeleteGraphics (GpGraphics *)
GpStatus WINGDIPAPI GdipDeleteMatrix (GpMatrix *)
GpStatus WINGDIPAPI GdipDeletePath (GpPath *)
GpStatus WINGDIPAPI GdipDeletePathIter (GpPathIterator *)
GpStatus WINGDIPAPI GdipDeletePen (GpPen *)
GpStatus WINGDIPAPI GdipDeletePrivateFontCollection (GpFontCollection **)
GpStatus WINGDIPAPI GdipDeleteRegion (GpRegion *)
GpStatus WINGDIPAPI GdipDeleteStringFormat (GpStringFormat *)
GpStatus WINGDIPAPI GdipDisposeImage (GpImage *)
GpStatus WINGDIPAPI GdipDisposeImageAttributes (GpImageAttributes *)
GpStatus WINGDIPAPI GdipDrawArc (GpGraphics *, GpPen *, REAL, REAL, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawArcI (GpGraphics *, GpPen *, INT, INT, INT, INT, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawBezier (GpGraphics *, GpPen *, REAL, REAL, REAL, REAL, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawBezierI (GpGraphics *, GpPen *, INT, INT, INT, INT, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipDrawBeziers (GpGraphics *, GpPen *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipDrawBeziersI (GpGraphics *, GpPen *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipDrawCachedBitmap (GpGraphics *, GpCachedBitmap *, INT, INT)
GpStatus WINGDIPAPI GdipDrawClosedCurve (GpGraphics *, GpPen *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipDrawClosedCurve2 (GpGraphics *, GpPen *, GDIPCONST GpPointF *, INT, REAL)
GpStatus WINGDIPAPI GdipDrawClosedCurve2I (GpGraphics *, GpPen *, GDIPCONST GpPoint *, INT, REAL)
GpStatus WINGDIPAPI GdipDrawClosedCurveI (GpGraphics *, GpPen *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipDrawCurve (GpGraphics *, GpPen *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipDrawCurve2 (GpGraphics *, GpPen *, GDIPCONST GpPointF *, INT, REAL)
GpStatus WINGDIPAPI GdipDrawCurve2I (GpGraphics *, GpPen *, GDIPCONST GpPoint *, INT, REAL)
GpStatus WINGDIPAPI GdipDrawCurve3 (GpGraphics *, GpPen *, GDIPCONST GpPointF *, INT, INT, INT, REAL)
GpStatus WINGDIPAPI GdipDrawCurve3I (GpGraphics *, GpPen *, GDIPCONST GpPoint *, INT, INT, INT, REAL)
GpStatus WINGDIPAPI GdipDrawCurveI (GpGraphics *, GpPen *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipDrawDriverString (GpGraphics *, GDIPCONST UINT16 *, INT, GDIPCONST GpFont *, GDIPCONST GpBrush *, GDIPCONST PointF *, INT, GDIPCONST GpMatrix *)
GpStatus WINGDIPAPI GdipDrawEllipse (GpGraphics *, GpPen *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawEllipseI (GpGraphics *, GpPen *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipDrawImage (GpGraphics *, GpImage *, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawImageFX (GpGraphics *, GpImage *, GpRectF *, GpMatrix *, CGpEffect *, GpImageAttributes *, GpUnit)
GpStatus WINGDIPAPI GdipDrawImageI (GpGraphics *, GpImage *, INT, INT)
GpStatus WINGDIPAPI GdipDrawImagePointRect (GpGraphics *, GpImage *, REAL, REAL, REAL, REAL, REAL, REAL, GpUnit)
GpStatus WINGDIPAPI GdipDrawImagePointRectI (GpGraphics *, GpImage *, INT, INT, INT, INT, INT, INT, GpUnit)
GpStatus WINGDIPAPI GdipDrawImagePoints (GpGraphics *, GpImage *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipDrawImagePointsI (GpGraphics *, GpImage *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipDrawImagePointsRect (GpGraphics *, GpImage *, GDIPCONST GpPointF *, INT, REAL, REAL, REAL, REAL, GpUnit, GDIPCONST GpImageAttributes *, DrawImageAbort, VOID *)
GpStatus WINGDIPAPI GdipDrawImagePointsRectI (GpGraphics *, GpImage *, GDIPCONST GpPoint *, INT, INT, INT, INT, INT, GpUnit, GDIPCONST GpImageAttributes *, DrawImageAbort, VOID *)
GpStatus WINGDIPAPI GdipDrawImageRect (GpGraphics *, GpImage *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawImageRectI (GpGraphics *, GpImage *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipDrawImageRectRect (GpGraphics *, GpImage *, REAL, REAL, REAL, REAL, REAL, REAL, REAL, REAL, GpUnit, GDIPCONST GpImageAttributes *, DrawImageAbort, VOID *)
GpStatus WINGDIPAPI GdipDrawImageRectRectI (GpGraphics *, GpImage *, INT, INT, INT, INT, INT, INT, INT, INT, GpUnit, GDIPCONST GpImageAttributes *, DrawImageAbort, VOID *)
GpStatus WINGDIPAPI GdipDrawLine (GpGraphics *, GpPen *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawLineI (GpGraphics *, GpPen *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipDrawLines (GpGraphics *, GpPen *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipDrawLinesI (GpGraphics *, GpPen *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipDrawPath (GpGraphics *, GpPen *, GpPath *)
GpStatus WINGDIPAPI GdipDrawPie (GpGraphics *, GpPen *, REAL, REAL, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawPieI (GpGraphics *, GpPen *, INT, INT, INT, INT, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawPolygon (GpGraphics *, GpPen *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipDrawPolygonI (GpGraphics *, GpPen *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipDrawRectangle (GpGraphics *, GpPen *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipDrawRectangleI (GpGraphics *, GpPen *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipDrawRectangles (GpGraphics *, GpPen *, GDIPCONST GpRectF *, INT)
GpStatus WINGDIPAPI GdipDrawRectanglesI (GpGraphics *, GpPen *, GDIPCONST GpRect *, INT)
GpStatus WINGDIPAPI GdipDrawString (GpGraphics *, GDIPCONST WCHAR *, INT, GDIPCONST GpFont *, GDIPCONST RectF *, GDIPCONST GpStringFormat *, GDIPCONST GpBrush *)
UINT WINGDIPAPI GdipEmfToWmfBits (HENHMETAFILE, UINT, LPBYTE, INT, INT)
GpStatus WINGDIPAPI GdipEndContainer (GpGraphics *, GraphicsContainer)
GpStatus WINGDIPAPI GdipEnumerateMetafileDestPoints (GpGraphics *, GDIPCONST GpMetafile *, GDIPCONST PointF *, INT, EnumerateMetafileProc, VOID *, GDIPCONST GpImageAttributes *)
GpStatus WINGDIPAPI GdipEnumerateMetafileDestPointsI (GpGraphics *, GDIPCONST GpMetafile *, GDIPCONST Point *, INT, EnumerateMetafileProc, VOID *, GDIPCONST GpImageAttributes *)
GpStatus WINGDIPAPI GdipFillClosedCurve (GpGraphics *, GpBrush *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipFillClosedCurve2 (GpGraphics *, GpBrush *, GDIPCONST GpPointF *, INT, REAL, GpFillMode)
GpStatus WINGDIPAPI GdipFillClosedCurve2I (GpGraphics *, GpBrush *, GDIPCONST GpPoint *, INT, REAL, GpFillMode)
GpStatus WINGDIPAPI GdipFillClosedCurveI (GpGraphics *, GpBrush *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipFillEllipse (GpGraphics *, GpBrush *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipFillEllipseI (GpGraphics *, GpBrush *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipFillPath (GpGraphics *, GpBrush *, GpPath *)
GpStatus WINGDIPAPI GdipFillPie (GpGraphics *, GpBrush *, REAL, REAL, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipFillPieI (GpGraphics *, GpBrush *, INT, INT, INT, INT, REAL, REAL)
GpStatus WINGDIPAPI GdipFillPolygon (GpGraphics *, GpBrush *, GDIPCONST GpPointF *, INT, GpFillMode)
GpStatus WINGDIPAPI GdipFillPolygon2 (GpGraphics *, GpBrush *, GDIPCONST GpPointF *, INT)
GpStatus WINGDIPAPI GdipFillPolygon2I (GpGraphics *, GpBrush *, GDIPCONST GpPoint *, INT)
GpStatus WINGDIPAPI GdipFillPolygonI (GpGraphics *, GpBrush *, GDIPCONST GpPoint *, INT, GpFillMode)
GpStatus WINGDIPAPI GdipFillRectangle (GpGraphics *, GpBrush *, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipFillRectangleI (GpGraphics *, GpBrush *, INT, INT, INT, INT)
GpStatus WINGDIPAPI GdipFillRectangles (GpGraphics *, GpBrush *, GDIPCONST GpRectF *, INT)
GpStatus WINGDIPAPI GdipFillRectanglesI (GpGraphics *, GpBrush *, GDIPCONST GpRect *, INT)
GpStatus WINGDIPAPI GdipFillRegion (GpGraphics *, GpBrush *, GpRegion *)
GpStatus WINGDIPAPI GdipFindFirstImageItem (GpImage *, ImageItemData *)
GpStatus WINGDIPAPI GdipFindNextImageItem (GpImage *, ImageItemData *)
GpStatus WINGDIPAPI GdipFlattenPath (GpPath *, GpMatrix *, REAL)
GpStatus WINGDIPAPI GdipFlush (GpGraphics *, GpFlushIntention)
GpStatus WINGDIPAPI GdipFontCollectionEnumerable (GpFontCollection *, GpGraphics *, INT *)
GpStatus WINGDIPAPI GdipFontCollectionEnumerate (GpFontCollection *, INT, GpFontFamily **, INT *, GpGraphics *)
GpStatus WINGDIPAPI GdipGetAdjustableArrowCapFillState (GpAdjustableArrowCap *, BOOL *)
GpStatus WINGDIPAPI GdipGetAdjustableArrowCapHeight (GpAdjustableArrowCap *, REAL *)
GpStatus WINGDIPAPI GdipGetAdjustableArrowCapMiddleInset (GpAdjustableArrowCap *, REAL *)
GpStatus WINGDIPAPI GdipGetAdjustableArrowCapWidth (GpAdjustableArrowCap *, REAL *)
GpStatus WINGDIPAPI GdipGetAllPropertyItems (GpImage *, UINT, UINT, PropertyItem *)
GpStatus WINGDIPAPI GdipGetBrushType (GpBrush *, GpBrushType *)
GpStatus WINGDIPAPI GdipGetCellAscent (GDIPCONST GpFontFamily *, INT, UINT16 *)
GpStatus WINGDIPAPI GdipGetCellDescent (GDIPCONST GpFontFamily *, INT, UINT16 *)
GpStatus WINGDIPAPI GdipGetClip (GpGraphics *, GpRegion *)
GpStatus WINGDIPAPI GdipGetClipBounds (GpGraphics *, GpRectF *)
GpStatus WINGDIPAPI GdipGetClipBoundsI (GpGraphics *, GpRect *)
GpStatus WINGDIPAPI GdipGetCompositingMode (GpGraphics *, CompositingMode *)
GpStatus WINGDIPAPI GdipGetCompositingQuality (GpGraphics *, CompositingQuality *)
GpStatus WINGDIPAPI GdipGetCustomLineCapBaseCap (GpCustomLineCap *, GpLineCap *)
GpStatus WINGDIPAPI GdipGetCustomLineCapBaseInset (GpCustomLineCap *, REAL *)
GpStatus WINGDIPAPI GdipGetCustomLineCapStrokeCaps (GpCustomLineCap *, GpLineCap *, GpLineCap *)
GpStatus WINGDIPAPI GdipGetCustomLineCapStrokeJoin (GpCustomLineCap *, GpLineJoin *)
GpStatus WINGDIPAPI GdipGetCustomLineCapType (GpCustomLineCap *, CustomLineCapType *)
GpStatus WINGDIPAPI GdipGetCustomLineCapWidthScale (GpCustomLineCap *, REAL *)
GpStatus WINGDIPAPI GdipGetDC (GpGraphics *, HDC *)
GpStatus WINGDIPAPI GdipGetDpiX (GpGraphics *, REAL *)
GpStatus WINGDIPAPI GdipGetDpiY (GpGraphics *, REAL *)
GpStatus WINGDIPAPI GdipGetEffectParameters (CGpEffect *, UINT *, VOID *)
GpStatus WINGDIPAPI GdipGetEffectParameterSize (CGpEffect *, UINT *)
GpStatus WINGDIPAPI GdipGetEmHeight (GDIPCONST GpFontFamily *, INT, UINT16 *)
GpStatus WINGDIPAPI GdipGetEncoderParameterList (GpImage *, GDIPCONST CLSID *, UINT, EncoderParameters *)
GpStatus WINGDIPAPI GdipGetEncoderParameterListSize (GpImage *, GDIPCONST CLSID *, UINT *)
GpStatus WINGDIPAPI GdipGetFamily (GpFont *, GpFontFamily **)
GpStatus WINGDIPAPI GdipGetFamilyName (GDIPCONST GpFontFamily *, WCHAR[LF_FACESIZE], LANGID)
GpStatus WINGDIPAPI GdipGetFontCollectionFamilyCount (GpFontCollection *, INT *)
GpStatus WINGDIPAPI GdipGetFontCollectionFamilyList (GpFontCollection *, INT, GpFontFamily **, INT *)
GpStatus WINGDIPAPI GdipGetFontHeight (GDIPCONST GpFont *, GDIPCONST GpGraphics *, REAL *)
GpStatus WINGDIPAPI GdipGetFontHeightGivenDPI (GDIPCONST GpFont *, REAL, REAL *)
GpStatus WINGDIPAPI GdipGetFontSize (GpFont *, REAL *)
GpStatus WINGDIPAPI GdipGetFontStyle (GpFont *, INT *)
GpStatus WINGDIPAPI GdipGetFontUnit (GpFont *, Unit *)
GpStatus WINGDIPAPI GdipGetGenericFontFamilyMonospace (GpFontFamily **)
GpStatus WINGDIPAPI GdipGetGenericFontFamilySansSerif (GpFontFamily **)
GpStatus WINGDIPAPI GdipGetGenericFontFamilySerif (GpFontFamily **)
GpStatus WINGDIPAPI GdipGetHatchBackgroundColor (GpHatch *, ARGB *)
GpStatus WINGDIPAPI GdipGetHatchForegroundColor (GpHatch *, ARGB *)
GpStatus WINGDIPAPI GdipGetHatchStyle (GpHatch *, GpHatchStyle *)
GpStatus WINGDIPAPI GdipGetHemfFromMetafile (GpMetafile *, HENHMETAFILE *)
GpStatus WINGDIPAPI GdipGetImageAttributesAdjustedPalette (GpImageAttributes *, ColorPalette *, ColorAdjustType)
GpStatus WINGDIPAPI GdipGetImageBounds (GpImage *, GpRectF *, GpUnit *)
GpStatus WINGDIPAPI GdipGetImageDecoders (UINT, UINT, ImageCodecInfo *)
GpStatus WINGDIPAPI GdipGetImageDecodersSize (UINT *, UINT *)
GpStatus WINGDIPAPI GdipGetImageDimension (GpImage *, REAL *, REAL *)
GpStatus WINGDIPAPI GdipGetImageEncoders (UINT, UINT, ImageCodecInfo *)
GpStatus WINGDIPAPI GdipGetImageEncodersSize (UINT *, UINT *)
GpStatus WINGDIPAPI GdipGetImageFlags (GpImage *, UINT *)
GpStatus WINGDIPAPI GdipGetImageGraphicsContext (GpImage *, GpGraphics **)
GpStatus WINGDIPAPI GdipGetImageHeight (GpImage *, UINT *)
GpStatus WINGDIPAPI GdipGetImageHorizontalResolution (GpImage *, REAL *)
GpStatus WINGDIPAPI GdipGetImageItemData (GpImage *, ImageItemData *)
GpStatus WINGDIPAPI GdipGetImagePalette (GpImage *, ColorPalette *, INT)
GpStatus WINGDIPAPI GdipGetImagePaletteSize (GpImage *, INT *)
GpStatus WINGDIPAPI GdipGetImagePixelFormat (GpImage *, PixelFormat *)
GpStatus WINGDIPAPI GdipGetImageRawFormat (GpImage *, GUID *)
GpStatus WINGDIPAPI GdipGetImageThumbnail (GpImage *, UINT, UINT, GpImage **, GetThumbnailImageAbort, VOID *)
GpStatus WINGDIPAPI GdipGetImageType (GpImage *, ImageType *)
GpStatus WINGDIPAPI GdipGetImageVerticalResolution (GpImage *, REAL *)
GpStatus WINGDIPAPI GdipGetImageWidth (GpImage *, UINT *)
GpStatus WINGDIPAPI GdipGetInterpolationMode (GpGraphics *, InterpolationMode *)
GpStatus WINGDIPAPI GdipGetLineBlend (GpLineGradient *, REAL *, REAL *, INT)
GpStatus WINGDIPAPI GdipGetLineBlendCount (GpLineGradient *, INT *)
GpStatus WINGDIPAPI GdipGetLineColors (GpLineGradient *, ARGB *)
GpStatus WINGDIPAPI GdipGetLineGammaCorrection (GpLineGradient *, BOOL *)
GpStatus WINGDIPAPI GdipGetLinePresetBlend (GpLineGradient *, ARGB *, REAL *, INT)
GpStatus WINGDIPAPI GdipGetLinePresetBlendCount (GpLineGradient *, INT *)
GpStatus WINGDIPAPI GdipGetLineRect (GpLineGradient *, GpRectF *)
GpStatus WINGDIPAPI GdipGetLineRectI (GpLineGradient *, GpRect *)
GpStatus WINGDIPAPI GdipGetLineSpacing (GDIPCONST GpFontFamily *, INT, UINT16 *)
GpStatus WINGDIPAPI GdipGetLineTransform (GpLineGradient *, GpMatrix *)
GpStatus WINGDIPAPI GdipGetLineWrapMode (GpLineGradient *, GpWrapMode *)
GpStatus WINGDIPAPI GdipGetLogFontA (GpFont *, GpGraphics *, LOGFONTA *)
GpStatus WINGDIPAPI GdipGetLogFontW (GpFont *, GpGraphics *, LOGFONTW *)
GpStatus WINGDIPAPI GdipGetMatrixElements (GDIPCONST GpMatrix *, REAL *)
GpStatus WINGDIPAPI GdipGetMetafileDownLevelRasterizationLimit (GDIPCONST GpMetafile *, UINT *)
GpStatus WINGDIPAPI GdipGetMetafileHeaderFromEmf (HENHMETAFILE, MetafileHeader *)
GpStatus WINGDIPAPI GdipGetMetafileHeaderFromFile (GDIPCONST WCHAR *, MetafileHeader *)
GpStatus WINGDIPAPI GdipGetMetafileHeaderFromMetafile (GpMetafile *, MetafileHeader *)
GpStatus WINGDIPAPI GdipGetMetafileHeaderFromStream (IStream *, MetafileHeader *)
GpStatus WINGDIPAPI GdipGetNearestColor (GpGraphics *, ARGB *)
GpStatus WINGDIPAPI GdipGetPageScale (GpGraphics *, REAL *)
GpStatus WINGDIPAPI GdipGetPageUnit (GpGraphics *, GpUnit *)
GpStatus WINGDIPAPI GdipGetPathData (GpPath *, GpPathData *)
GpStatus WINGDIPAPI GdipGetPathFillMode (GpPath *, GpFillMode *)
GpStatus WINGDIPAPI GdipGetPathGradientBlend (GpPathGradient *, REAL *, REAL *, INT)
GpStatus WINGDIPAPI GdipGetPathGradientBlendCount (GpPathGradient *, INT *)
GpStatus WINGDIPAPI GdipGetPathGradientCenterColor (GpPathGradient *, ARGB *)
GpStatus WINGDIPAPI GdipGetPathGradientCenterPoint (GpPathGradient *, GpPointF *)
GpStatus WINGDIPAPI GdipGetPathGradientCenterPointI (GpPathGradient *, GpPoint *)
GpStatus WINGDIPAPI GdipGetPathGradientFocusScales (GpPathGradient *, REAL *, REAL *)
GpStatus WINGDIPAPI GdipGetPathGradientGammaCorrection (GpPathGradient *, BOOL *)
GpStatus WINGDIPAPI GdipGetPathGradientPath (GpPathGradient *, GpPath *)
GpStatus WINGDIPAPI GdipGetPathGradientPointCount (GpPathGradient *, INT *)
GpStatus WINGDIPAPI GdipGetPathGradientPresetBlend (GpPathGradient *, ARGB *, REAL *, INT)
GpStatus WINGDIPAPI GdipGetPathGradientPresetBlendCount (GpPathGradient *, INT *)
GpStatus WINGDIPAPI GdipGetPathGradientRect (GpPathGradient *, GpRectF *)
GpStatus WINGDIPAPI GdipGetPathGradientRectI (GpPathGradient *, GpRect *)
GpStatus WINGDIPAPI GdipGetPathGradientSurroundColorCount (GpPathGradient *, INT *)
GpStatus WINGDIPAPI GdipGetPathGradientSurroundColorsWithCount (GpPathGradient *, ARGB *, INT *)
GpStatus WINGDIPAPI GdipGetPathGradientTransform (GpPathGradient *, GpMatrix *)
GpStatus WINGDIPAPI GdipGetPathGradientWrapMode (GpPathGradient *, GpWrapMode *)
GpStatus WINGDIPAPI GdipGetPathLastPoint (GpPath *, GpPointF *)
GpStatus WINGDIPAPI GdipGetPathPoints (GpPath *, GpPointF *, INT)
GpStatus WINGDIPAPI GdipGetPathPointsI (GpPath *, GpPoint *, INT)
GpStatus WINGDIPAPI GdipGetPathTypes (GpPath *, BYTE *, INT)
GpStatus WINGDIPAPI GdipGetPathWorldBounds (GpPath *, GpRectF *, GDIPCONST GpMatrix *, GDIPCONST GpPen *)
GpStatus WINGDIPAPI GdipGetPathWorldBoundsI (GpPath *, GpRect *, GDIPCONST GpMatrix *, GDIPCONST GpPen *)
GpStatus WINGDIPAPI GdipGetPenBrushFill (GpPen *, GpBrush **)
GpStatus WINGDIPAPI GdipGetPenColor (GpPen *, ARGB *)
GpStatus WINGDIPAPI GdipGetPenCompoundArray (GpPen *, REAL *, INT)
GpStatus WINGDIPAPI GdipGetPenCompoundCount (GpPen *, INT *)
GpStatus WINGDIPAPI GdipGetPenCustomEndCap (GpPen *, GpCustomLineCap **)
GpStatus WINGDIPAPI GdipGetPenCustomStartCap (GpPen *, GpCustomLineCap **)
GpStatus WINGDIPAPI GdipGetPenDashArray (GpPen *, REAL *, INT)
GpStatus WINGDIPAPI GdipGetPenDashCap197819 (GpPen *, GpDashCap *)
GpStatus WINGDIPAPI GdipGetPenDashCount (GpPen *, INT *)
GpStatus WINGDIPAPI GdipGetPenDashOffset (GpPen *, REAL *)
GpStatus WINGDIPAPI GdipGetPenDashStyle (GpPen *, GpDashStyle *)
GpStatus WINGDIPAPI GdipGetPenEndCap (GpPen *, GpLineCap *)
GpStatus WINGDIPAPI GdipGetPenFillType (GpPen *, GpPenType *)
GpStatus WINGDIPAPI GdipGetPenLineJoin (GpPen *, GpLineJoin *)
GpStatus WINGDIPAPI GdipGetPenMiterLimit (GpPen *, REAL *)
GpStatus WINGDIPAPI GdipGetPenMode (GpPen *, GpPenAlignment *)
GpStatus WINGDIPAPI GdipGetPenStartCap (GpPen *, GpLineCap *)
GpStatus WINGDIPAPI GdipGetPenTransform (GpPen *, GpMatrix *)
GpStatus WINGDIPAPI GdipGetPenUnit (GpPen *, GpUnit *)
GpStatus WINGDIPAPI GdipGetPenWidth (GpPen *, REAL *)
GpStatus WINGDIPAPI GdipGetPixelOffsetMode (GpGraphics *, PixelOffsetMode *)
GpStatus WINGDIPAPI GdipGetPointCount (GpPath *, INT *)
GpStatus WINGDIPAPI GdipGetPropertyCount (GpImage *, UINT *)
GpStatus WINGDIPAPI GdipGetPropertyIdList (GpImage *, UINT, PROPID *)
GpStatus WINGDIPAPI GdipGetPropertyItem (GpImage *, PROPID, UINT, PropertyItem *)
GpStatus WINGDIPAPI GdipGetPropertyItemSize (GpImage *, PROPID, UINT *)
GpStatus WINGDIPAPI GdipGetPropertySize (GpImage *, UINT *, UINT *)
GpStatus WINGDIPAPI GdipGetRegionBounds (GpRegion *, GpGraphics *, GpRectF *)
GpStatus WINGDIPAPI GdipGetRegionBoundsI (GpRegion *, GpGraphics *, GpRect *)
GpStatus WINGDIPAPI GdipGetRegionData (GpRegion *, BYTE *, UINT, UINT *)
GpStatus WINGDIPAPI GdipGetRegionDataSize (GpRegion *, UINT *)
GpStatus WINGDIPAPI GdipGetRegionHRgn (GpRegion *, GpGraphics *, HRGN *)
GpStatus WINGDIPAPI GdipGetRegionScans (GpRegion *, GpRectF *, INT *, GpMatrix *)
GpStatus WINGDIPAPI GdipGetRegionScansCount (GpRegion *, UINT *, GpMatrix *)
GpStatus WINGDIPAPI GdipGetRegionScansI (GpRegion *, GpRect *, INT *, GpMatrix *)
GpStatus WINGDIPAPI GdipGetRenderingOrigin (GpGraphics *, INT *, INT *)
GpStatus WINGDIPAPI GdipGetSmoothingMode (GpGraphics *, SmoothingMode *)
GpStatus WINGDIPAPI GdipGetSolidFillColor (GpSolidFill *, ARGB *)
GpStatus WINGDIPAPI GdipGetStringFormatAlign (GDIPCONST GpStringFormat *, StringAlignment *)
GpStatus WINGDIPAPI GdipGetStringFormatDigitSubstitution (GDIPCONST GpStringFormat *, LANGID *, StringDigitSubstitute *)
GpStatus WINGDIPAPI GdipGetStringFormatFlags (GDIPCONST GpStringFormat *, INT *)
GpStatus WINGDIPAPI GdipGetStringFormatHotkeyPrefix (GDIPCONST GpStringFormat *, INT *)
GpStatus WINGDIPAPI GdipGetStringFormatLineAlign (GDIPCONST GpStringFormat *, StringAlignment *)
GpStatus WINGDIPAPI GdipGetStringFormatMeasurableCharacterRangeCount (GDIPCONST GpStringFormat *, INT *)
GpStatus WINGDIPAPI GdipGetStringFormatTabStopCount (GDIPCONST GpStringFormat *, INT *)
GpStatus WINGDIPAPI GdipGetStringFormatTabStops (GDIPCONST GpStringFormat *, INT, REAL *, REAL *)
GpStatus WINGDIPAPI GdipGetStringFormatTrimming (GDIPCONST GpStringFormat *, StringTrimming *)
GpStatus WINGDIPAPI GdipGetTextContrast (GpGraphics *, UINT *)
GpStatus WINGDIPAPI GdipGetTextRenderingHint (GpGraphics *, TextRenderingHint *)
GpStatus WINGDIPAPI GdipGetTextureImage (GpTexture *, GpImage **)
GpStatus WINGDIPAPI GdipGetTextureTransform (GpTexture *, GpMatrix *)
GpStatus WINGDIPAPI GdipGetTextureWrapMode (GpTexture *, GpWrapMode *)
GpStatus WINGDIPAPI GdipGetVisibleClipBounds (GpGraphics *, GpRectF *)
GpStatus WINGDIPAPI GdipGetVisibleClipBoundsI (GpGraphics *, GpRect *)
GpStatus WINGDIPAPI GdipGetWorldTransform (GpGraphics *, GpMatrix *)
GpStatus WINGDIPAPI GdipGraphicsClear (GpGraphics *, ARGB)
GpStatus WINGDIPAPI GdipGraphicsSetAbort (GpGraphics *, GdiplusAbort *)
GpStatus WINGDIPAPI GdipImageForceValidation (GpImage *)
GpStatus WINGDIPAPI GdipImageGetFrameCount (GpImage *, GDIPCONST GUID *, UINT *)
GpStatus WINGDIPAPI GdipImageGetFrameDimensionsCount (GpImage *, UINT *)
GpStatus WINGDIPAPI GdipImageGetFrameDimensionsList (GpImage *, GUID *, UINT)
GpStatus WINGDIPAPI GdipImageRotateFlip (GpImage *, RotateFlipType)
GpStatus WINGDIPAPI GdipImageSelectActiveFrame (GpImage *, GDIPCONST GUID *, UINT)
GpStatus WINGDIPAPI GdipImageSetAbort (GpImage *, GdiplusAbort *)
GpStatus WINGDIPAPI GdipInitializePalette (ColorPalette *, PaletteType, INT, BOOL, GpBitmap *)
GpStatus WINGDIPAPI GdipInvertMatrix (GpMatrix *)
GpStatus WINGDIPAPI GdipIsClipEmpty (GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsEmptyRegion (GpRegion *, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsEqualRegion (GpRegion *, GpRegion *, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsInfiniteRegion (GpRegion *, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsMatrixEqual (GDIPCONST GpMatrix *, GDIPCONST GpMatrix *, BOOL *)
GpStatus WINGDIPAPI GdipIsMatrixIdentity (GDIPCONST GpMatrix *, BOOL *)
GpStatus WINGDIPAPI GdipIsMatrixInvertible (GDIPCONST GpMatrix *, BOOL *)
GpStatus WINGDIPAPI GdipIsOutlineVisiblePathPoint (GpPath *, REAL, REAL, GpPen *, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsOutlineVisiblePathPointI (GpPath *, INT, INT, GpPen *, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsStyleAvailable (GDIPCONST GpFontFamily *, INT, BOOL *)
GpStatus WINGDIPAPI GdipIsVisibleClipEmpty (GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsVisiblePathPoint (GpPath *, REAL, REAL, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsVisiblePathPointI (GpPath *, INT, INT, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsVisiblePoint (GpGraphics *, REAL, REAL, BOOL *)
GpStatus WINGDIPAPI GdipIsVisiblePointI (GpGraphics *, INT, INT, BOOL *)
GpStatus WINGDIPAPI GdipIsVisibleRect (GpGraphics *, REAL, REAL, REAL, REAL, BOOL *)
GpStatus WINGDIPAPI GdipIsVisibleRectI (GpGraphics *, INT, INT, INT, INT, BOOL *)
GpStatus WINGDIPAPI GdipIsVisibleRegionPoint (GpRegion *, REAL, REAL, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsVisibleRegionPointI (GpRegion *, INT, INT, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsVisibleRegionRect (GpRegion *, REAL, REAL, REAL, REAL, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipIsVisibleRegionRectI (GpRegion *, INT, INT, INT, INT, GpGraphics *, BOOL *)
GpStatus WINGDIPAPI GdipLoadImageFromFile (GDIPCONST WCHAR *, GpImage **)
GpStatus WINGDIPAPI GdipLoadImageFromFileICM (GDIPCONST WCHAR *, GpImage **)
GpStatus WINGDIPAPI GdipLoadImageFromStream (IStream *, GpImage **)
GpStatus WINGDIPAPI GdipLoadImageFromStreamICM (IStream *, GpImage **)
GpStatus WINGDIPAPI GdipMeasureDriverString (GpGraphics *, GDIPCONST UINT16 *, INT, GDIPCONST GpFont *, GDIPCONST PointF *, INT, GDIPCONST GpMatrix *, RectF *)
GpStatus WINGDIPAPI GdipMeasureString (GpGraphics *, GDIPCONST WCHAR *, INT, GDIPCONST GpFont *, GDIPCONST RectF *, GDIPCONST GpStringFormat *, RectF *, INT *, INT *)
GpStatus WINGDIPAPI GdipMultiplyLineTransform (GpLineGradient *, GDIPCONST GpMatrix *, GpMatrixOrder)
GpStatus WINGDIPAPI GdipMultiplyMatrix (GpMatrix *, GpMatrix *, GpMatrixOrder)
GpStatus WINGDIPAPI GdipMultiplyPathGradientTransform (GpPathGradient *, GDIPCONST GpMatrix *, GpMatrixOrder)
GpStatus WINGDIPAPI GdipMultiplyPenTransform (GpPen *, GDIPCONST GpMatrix *, GpMatrixOrder)
GpStatus WINGDIPAPI GdipMultiplyTextureTransform (GpTexture *, GDIPCONST GpMatrix *, GpMatrixOrder)
GpStatus WINGDIPAPI GdipMultiplyWorldTransform (GpGraphics *, GDIPCONST GpMatrix *, GpMatrixOrder)
GpStatus WINGDIPAPI GdipNewInstalledFontCollection (GpFontCollection **)
GpStatus WINGDIPAPI GdipNewPrivateFontCollection (GpFontCollection **)
GpStatus WINGDIPAPI GdipPathIterCopyData (GpPathIterator *, INT *, GpPointF *, BYTE *, INT, INT)
GpStatus WINGDIPAPI GdipPathIterEnumerate (GpPathIterator *, INT *, GpPointF *, BYTE *, INT)
GpStatus WINGDIPAPI GdipPathIterGetCount (GpPathIterator *, INT *)
GpStatus WINGDIPAPI GdipPathIterGetSubpathCount (GpPathIterator *, INT *)
GpStatus WINGDIPAPI GdipPathIterHasCurve (GpPathIterator *, BOOL *)
GpStatus WINGDIPAPI GdipPathIterIsValid (GpPathIterator *, BOOL *)
GpStatus WINGDIPAPI GdipPathIterNextMarker (GpPathIterator *, INT *, INT *, INT *)
GpStatus WINGDIPAPI GdipPathIterNextMarkerPath (GpPathIterator *, INT *, GpPath *)
GpStatus WINGDIPAPI GdipPathIterNextPathType (GpPathIterator *, INT *, BYTE *, INT *, INT *)
GpStatus WINGDIPAPI GdipPathIterNextSubpath (GpPathIterator *, INT *, INT *, INT *, BOOL *)
GpStatus WINGDIPAPI GdipPathIterNextSubpathPath (GpPathIterator *, INT *, GpPath *, BOOL *)
GpStatus WINGDIPAPI GdipPathIterRewind (GpPathIterator *)
GpStatus WINGDIPAPI GdipPlayMetafileRecord (GDIPCONST GpMetafile *, EmfPlusRecordType, UINT, UINT, GDIPCONST BYTE *)
GpStatus WINGDIPAPI GdipPrivateAddFontFile (GpFontCollection *, GDIPCONST WCHAR *)
GpStatus WINGDIPAPI GdipPrivateAddMemoryFont (GpFontCollection *, GDIPCONST void *, INT)
GpStatus WINGDIPAPI GdipRecordMetafile (HDC, EmfType, GDIPCONST GpRectF *, MetafileFrameUnit, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipRecordMetafileFileName (GDIPCONST WCHAR *, HDC, EmfType, GDIPCONST GpRectF *, MetafileFrameUnit, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipRecordMetafileFileNameI (GDIPCONST WCHAR *, HDC, EmfType, GDIPCONST GpRect *, MetafileFrameUnit, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipRecordMetafileI (HDC, EmfType, GDIPCONST GpRect *, MetafileFrameUnit, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipRecordMetafileStream (IStream *, HDC, EmfType, GDIPCONST GpRectF *, MetafileFrameUnit, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipRecordMetafileStreamI (IStream *, HDC, EmfType, GDIPCONST GpRect *, MetafileFrameUnit, GDIPCONST WCHAR *, GpMetafile **)
GpStatus WINGDIPAPI GdipReleaseDC (GpGraphics *, HDC)
GpStatus WINGDIPAPI GdipRemovePropertyItem (GpImage *, PROPID)
GpStatus WINGDIPAPI GdipResetClip (GpGraphics *)
GpStatus WINGDIPAPI GdipResetImageAttributes (GpImageAttributes *, ColorAdjustType)
GpStatus WINGDIPAPI GdipResetLineTransform (GpLineGradient *)
GpStatus WINGDIPAPI GdipResetPageTransform (GpGraphics *)
GpStatus WINGDIPAPI GdipResetPath (GpPath *)
GpStatus WINGDIPAPI GdipResetPathGradientTransform (GpPathGradient *)
GpStatus WINGDIPAPI GdipResetPenTransform (GpPen *)
GpStatus WINGDIPAPI GdipResetTextureTransform (GpTexture *)
GpStatus WINGDIPAPI GdipResetWorldTransform (GpGraphics *)
GpStatus WINGDIPAPI GdipRestoreGraphics (GpGraphics *, GraphicsState)
GpStatus WINGDIPAPI GdipReversePath (GpPath *)
GpStatus WINGDIPAPI GdipRotateLineTransform (GpLineGradient *, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipRotateMatrix (GpMatrix *, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipRotatePathGradientTransform (GpPathGradient *, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipRotatePenTransform (GpPen *, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipRotateTextureTransform (GpTexture *, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipRotateWorldTransform (GpGraphics *, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipSaveAdd (GpImage *, GDIPCONST EncoderParameters *)
GpStatus WINGDIPAPI GdipSaveAddImage (GpImage *, GpImage *, GDIPCONST EncoderParameters *)
GpStatus WINGDIPAPI GdipSaveGraphics (GpGraphics *, GraphicsState *)
GpStatus WINGDIPAPI GdipSaveImageToFile (GpImage *, GDIPCONST WCHAR *, GDIPCONST CLSID *, GDIPCONST EncoderParameters *)
GpStatus WINGDIPAPI GdipSaveImageToStream (GpImage *, IStream *, GDIPCONST CLSID *, GDIPCONST EncoderParameters *)
GpStatus WINGDIPAPI GdipScaleLineTransform (GpLineGradient *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipScaleMatrix (GpMatrix *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipScalePathGradientTransform (GpPathGradient *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipScalePenTransform (GpPen *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipScaleTextureTransform (GpTexture *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipScaleWorldTransform (GpGraphics *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipSetAdjustableArrowCapFillState (GpAdjustableArrowCap *, BOOL)
GpStatus WINGDIPAPI GdipSetAdjustableArrowCapHeight (GpAdjustableArrowCap *, REAL)
GpStatus WINGDIPAPI GdipSetAdjustableArrowCapMiddleInset (GpAdjustableArrowCap *, REAL)
GpStatus WINGDIPAPI GdipSetAdjustableArrowCapWidth (GpAdjustableArrowCap *, REAL)
GpStatus WINGDIPAPI GdipSetClipGraphics (GpGraphics *, GpGraphics *, CombineMode)
GpStatus WINGDIPAPI GdipSetClipHrgn (GpGraphics *, HRGN, CombineMode)
GpStatus WINGDIPAPI GdipSetClipPath (GpGraphics *, GpPath *, CombineMode)
GpStatus WINGDIPAPI GdipSetClipRect (GpGraphics *, REAL, REAL, REAL, REAL, CombineMode)
GpStatus WINGDIPAPI GdipSetClipRectI (GpGraphics *, INT, INT, INT, INT, CombineMode)
GpStatus WINGDIPAPI GdipSetClipRegion (GpGraphics *, GpRegion *, CombineMode)
GpStatus WINGDIPAPI GdipSetCompositingMode (GpGraphics *, CompositingMode)
GpStatus WINGDIPAPI GdipSetCompositingQuality (GpGraphics *, CompositingQuality)
GpStatus WINGDIPAPI GdipSetCustomLineCapBaseCap (GpCustomLineCap *, GpLineCap)
GpStatus WINGDIPAPI GdipSetCustomLineCapBaseInset (GpCustomLineCap *, REAL)
GpStatus WINGDIPAPI GdipSetCustomLineCapStrokeCaps (GpCustomLineCap *, GpLineCap, GpLineCap)
GpStatus WINGDIPAPI GdipSetCustomLineCapStrokeJoin (GpCustomLineCap *, GpLineJoin)
GpStatus WINGDIPAPI GdipSetCustomLineCapWidthScale (GpCustomLineCap *, REAL)
GpStatus WINGDIPAPI GdipSetEffectParameters (CGpEffect *, GDIPCONST VOID *, UINT)
GpStatus WINGDIPAPI GdipSetEmpty (GpRegion *)
GpStatus WINGDIPAPI GdipSetImageAttributesCachedBackground (GpImageAttributes *, BOOL)
GpStatus WINGDIPAPI GdipSetImageAttributesColorKeys (GpImageAttributes *, ColorAdjustType, BOOL, ARGB, ARGB)
GpStatus WINGDIPAPI GdipSetImageAttributesColorMatrix (GpImageAttributes *, ColorAdjustType, BOOL, GDIPCONST ColorMatrix *, GDIPCONST ColorMatrix *, ColorMatrixFlags)
GpStatus WINGDIPAPI GdipSetImageAttributesGamma (GpImageAttributes *, ColorAdjustType, BOOL, REAL)
GpStatus WINGDIPAPI GdipSetImageAttributesICMMode (GpImageAttributes *, BOOL)
GpStatus WINGDIPAPI GdipSetImageAttributesNoOp (GpImageAttributes *, ColorAdjustType, BOOL)
GpStatus WINGDIPAPI GdipSetImageAttributesOutputChannel (GpImageAttributes *, ColorAdjustType, BOOL, ColorChannelFlags)
GpStatus WINGDIPAPI GdipSetImageAttributesOutputChannelColorProfile (GpImageAttributes *, ColorAdjustType, BOOL, GDIPCONST WCHAR *)
GpStatus WINGDIPAPI GdipSetImageAttributesRemapTable (GpImageAttributes *, ColorAdjustType, BOOL, UINT, GDIPCONST ColorMap *)
GpStatus WINGDIPAPI GdipSetImageAttributesThreshold (GpImageAttributes *, ColorAdjustType, BOOL, REAL)
GpStatus WINGDIPAPI GdipSetImageAttributesToIdentity (GpImageAttributes *, ColorAdjustType)
GpStatus WINGDIPAPI GdipSetImageAttributesWrapMode (GpImageAttributes *, WrapMode, ARGB, BOOL)
GpStatus WINGDIPAPI GdipSetImagePalette (GpImage *, GDIPCONST ColorPalette *)
GpStatus WINGDIPAPI GdipSetInfinite (GpRegion *)
GpStatus WINGDIPAPI GdipSetInterpolationMode (GpGraphics *, InterpolationMode)
GpStatus WINGDIPAPI GdipSetLineBlend (GpLineGradient *, GDIPCONST REAL *, GDIPCONST REAL *, INT)
GpStatus WINGDIPAPI GdipSetLineColors (GpLineGradient *, ARGB, ARGB)
GpStatus WINGDIPAPI GdipSetLineGammaCorrection (GpLineGradient *, BOOL)
GpStatus WINGDIPAPI GdipSetLineLinearBlend (GpLineGradient *, REAL, REAL)
GpStatus WINGDIPAPI GdipSetLinePresetBlend (GpLineGradient *, GDIPCONST ARGB *, GDIPCONST REAL *, INT)
GpStatus WINGDIPAPI GdipSetLineSigmaBlend (GpLineGradient *, REAL, REAL)
GpStatus WINGDIPAPI GdipSetLineTransform (GpLineGradient *, GDIPCONST GpMatrix *)
GpStatus WINGDIPAPI GdipSetLineWrapMode (GpLineGradient *, GpWrapMode)
GpStatus WINGDIPAPI GdipSetMatrixElements (GpMatrix *, REAL, REAL, REAL, REAL, REAL, REAL)
GpStatus WINGDIPAPI GdipSetMetafileDownLevelRasterizationLimit (GpMetafile *, UINT)
GpStatus WINGDIPAPI GdipSetPageScale (GpGraphics *, REAL)
GpStatus WINGDIPAPI GdipSetPageUnit (GpGraphics *, GpUnit)
GpStatus WINGDIPAPI GdipSetPathFillMode (GpPath *, GpFillMode)
GpStatus WINGDIPAPI GdipSetPathGradientBlend (GpPathGradient *, GDIPCONST REAL *, GDIPCONST REAL *, INT)
GpStatus WINGDIPAPI GdipSetPathGradientCenterColor (GpPathGradient *, ARGB)
GpStatus WINGDIPAPI GdipSetPathGradientCenterPoint (GpPathGradient *, GDIPCONST GpPointF *)
GpStatus WINGDIPAPI GdipSetPathGradientCenterPointI (GpPathGradient *, GDIPCONST GpPoint *)
GpStatus WINGDIPAPI GdipSetPathGradientFocusScales (GpPathGradient *, REAL, REAL)
GpStatus WINGDIPAPI GdipSetPathGradientGammaCorrection (GpPathGradient *, BOOL)
GpStatus WINGDIPAPI GdipSetPathGradientLinearBlend (GpPathGradient *, REAL, REAL)
GpStatus WINGDIPAPI GdipSetPathGradientPath (GpPathGradient *, GDIPCONST GpPath *)
GpStatus WINGDIPAPI GdipSetPathGradientPresetBlend (GpPathGradient *, GDIPCONST ARGB *, GDIPCONST REAL *, INT)
GpStatus WINGDIPAPI GdipSetPathGradientSigmaBlend (GpPathGradient *, REAL, REAL)
GpStatus WINGDIPAPI GdipSetPathGradientSurroundColorsWithCount (GpPathGradient *, GDIPCONST ARGB *, INT *)
GpStatus WINGDIPAPI GdipSetPathGradientTransform (GpPathGradient *, GpMatrix *)
GpStatus WINGDIPAPI GdipSetPathGradientWrapMode (GpPathGradient *, GpWrapMode)
GpStatus WINGDIPAPI GdipSetPathMarker (GpPath *)
GpStatus WINGDIPAPI GdipSetPenBrushFill (GpPen *, GpBrush *)
GpStatus WINGDIPAPI GdipSetPenColor (GpPen *, ARGB)
GpStatus WINGDIPAPI GdipSetPenCompoundArray (GpPen *, GDIPCONST REAL *, INT)
GpStatus WINGDIPAPI GdipSetPenCustomEndCap (GpPen *, GpCustomLineCap *)
GpStatus WINGDIPAPI GdipSetPenCustomStartCap (GpPen *, GpCustomLineCap *)
GpStatus WINGDIPAPI GdipSetPenDashArray (GpPen *, GDIPCONST REAL *, INT)
GpStatus WINGDIPAPI GdipSetPenDashCap197819 (GpPen *, GpDashCap)
GpStatus WINGDIPAPI GdipSetPenDashOffset (GpPen *, REAL)
GpStatus WINGDIPAPI GdipSetPenDashStyle (GpPen *, GpDashStyle)
GpStatus WINGDIPAPI GdipSetPenEndCap (GpPen *, GpLineCap)
GpStatus WINGDIPAPI GdipSetPenLineCap197819 (GpPen *, GpLineCap, GpLineCap, GpDashCap)
GpStatus WINGDIPAPI GdipSetPenLineJoin (GpPen *, GpLineJoin)
GpStatus WINGDIPAPI GdipSetPenMiterLimit (GpPen *, REAL)
GpStatus WINGDIPAPI GdipSetPenMode (GpPen *, GpPenAlignment)
GpStatus WINGDIPAPI GdipSetPenStartCap (GpPen *, GpLineCap)
GpStatus WINGDIPAPI GdipSetPenTransform (GpPen *, GpMatrix *)
GpStatus WINGDIPAPI GdipSetPenUnit (GpPen *, GpUnit)
GpStatus WINGDIPAPI GdipSetPenWidth (GpPen *, REAL)
GpStatus WINGDIPAPI GdipSetPixelOffsetMode (GpGraphics *, PixelOffsetMode)
GpStatus WINGDIPAPI GdipSetPropertyItem (GpImage *, GDIPCONST PropertyItem *)
GpStatus WINGDIPAPI GdipSetRenderingOrigin (GpGraphics *, INT, INT)
GpStatus WINGDIPAPI GdipSetSmoothingMode (GpGraphics *, SmoothingMode)
GpStatus WINGDIPAPI GdipSetSolidFillColor (GpSolidFill *, ARGB)
GpStatus WINGDIPAPI GdipSetStringFormatAlign (GpStringFormat *, StringAlignment)
GpStatus WINGDIPAPI GdipSetStringFormatDigitSubstitution (GpStringFormat *, LANGID, StringDigitSubstitute)
GpStatus WINGDIPAPI GdipSetStringFormatFlags (GpStringFormat *, INT)
GpStatus WINGDIPAPI GdipSetStringFormatHotkeyPrefix (GpStringFormat *, INT)
GpStatus WINGDIPAPI GdipSetStringFormatLineAlign (GpStringFormat *, StringAlignment)
GpStatus WINGDIPAPI GdipSetStringFormatMeasurableCharacterRanges (GpStringFormat *, INT, GDIPCONST CharacterRange *)
GpStatus WINGDIPAPI GdipSetStringFormatTabStops (GpStringFormat *, REAL, INT, GDIPCONST REAL *)
GpStatus WINGDIPAPI GdipSetStringFormatTrimming (GpStringFormat *, StringTrimming)
GpStatus WINGDIPAPI GdipSetTextContrast (GpGraphics *, UINT)
GpStatus WINGDIPAPI GdipSetTextRenderingHint (GpGraphics *, TextRenderingHint)
GpStatus WINGDIPAPI GdipSetTextureTransform (GpTexture *, GDIPCONST GpMatrix *)
GpStatus WINGDIPAPI GdipSetTextureWrapMode (GpTexture *, GpWrapMode)
GpStatus WINGDIPAPI GdipSetWorldTransform (GpGraphics *, GpMatrix *)
GpStatus WINGDIPAPI GdipShearMatrix (GpMatrix *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipStartPathFigure (GpPath *)
GpStatus WINGDIPAPI GdipStringFormatGetGenericDefault (GpStringFormat **)
GpStatus WINGDIPAPI GdipStringFormatGetGenericTypographic (GpStringFormat **)
GpStatus WINGDIPAPI GdipTestControl (GpTestControlEnum, void *)
GpStatus WINGDIPAPI GdipTransformMatrixPoints (GpMatrix *, GpPointF *, INT)
GpStatus WINGDIPAPI GdipTransformMatrixPointsI (GpMatrix *, GpPoint *, INT)
GpStatus WINGDIPAPI GdipTransformPath (GpPath *, GpMatrix *)
GpStatus WINGDIPAPI GdipTransformPoints (GpGraphics *, GpCoordinateSpace, GpCoordinateSpace, GpPointF *, INT)
GpStatus WINGDIPAPI GdipTransformPointsI (GpGraphics *, GpCoordinateSpace, GpCoordinateSpace, GpPoint *, INT)
GpStatus WINGDIPAPI GdipTransformRegion (GpRegion *, GpMatrix *)
GpStatus WINGDIPAPI GdipTranslateClip (GpGraphics *, REAL, REAL)
GpStatus WINGDIPAPI GdipTranslateClipI (GpGraphics *, INT, INT)
GpStatus WINGDIPAPI GdipTranslateLineTransform (GpLineGradient *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipTranslateMatrix (GpMatrix *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipTranslatePathGradientTransform (GpPathGradient *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipTranslatePenTransform (GpPen *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipTranslateRegion (GpRegion *, REAL, REAL)
GpStatus WINGDIPAPI GdipTranslateRegionI (GpRegion *, INT, INT)
GpStatus WINGDIPAPI GdipTranslateTextureTransform (GpTexture *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipTranslateWorldTransform (GpGraphics *, REAL, REAL, GpMatrixOrder)
GpStatus WINGDIPAPI GdipVectorTransformMatrixPoints (GpMatrix *, GpPointF *, INT)
GpStatus WINGDIPAPI GdipVectorTransformMatrixPointsI (GpMatrix *, GpPoint *, INT)
GpStatus WINGDIPAPI GdipWarpPath (GpPath *, GpMatrix *, GDIPCONST GpPointF *, INT, REAL, REAL, REAL, REAL, WarpMode, REAL)
GpStatus WINGDIPAPI GdipWidenPath (GpPath *, GpPen *, GpMatrix *, REAL)
GpStatus WINGDIPAPI GdipWindingModeOutline (GpPath *, GpMatrix *, REAL)
Function Documentation
GdipAddPathArc()
GpStatus WINGDIPAPI GdipAddPathArc (GpPath * , REAL , REAL , REAL , REAL , REAL , REAL)
Referenced by GraphicsPath::AddArc().
GdipAddPathArcI()
GpStatus WINGDIPAPI GdipAddPathArcI (GpPath * , INT , INT , INT , INT , REAL , REAL)
Referenced by GraphicsPath::AddArc().
GdipAddPathBezier()
GpStatus WINGDIPAPI GdipAddPathBezier (GpPath * , REAL , REAL , REAL , REAL , REAL , REAL , REAL , REAL)
Referenced by GraphicsPath::AddBezier().
GdipAddPathBezierI()
GpStatus WINGDIPAPI GdipAddPathBezierI (GpPath * , INT , INT , INT , INT , INT , INT , INT , INT)
Referenced by GraphicsPath::AddBezier().
GdipAddPathBeziers()
GpStatus WINGDIPAPI GdipAddPathBeziers (GpPath * , GDIPCONST GpPointF * , INT)
Referenced by GraphicsPath::AddBeziers().
GdipAddPathBeziersI()
GpStatus WINGDIPAPI GdipAddPathBeziersI (GpPath * , GDIPCONST GpPoint * , INT)
Referenced by GraphicsPath::AddBeziers().
GdipAddPathClosedCurve()
GpStatus WINGDIPAPI GdipAddPathClosedCurve (GpPath * , GDIPCONST GpPointF * , INT)
Referenced by GraphicsPath::AddClosedCurve().
GdipAddPathClosedCurve2()
GpStatus WINGDIPAPI GdipAddPathClosedCurve2 (GpPath * , GDIPCONST GpPointF * , INT , REAL)
Referenced by GraphicsPath::AddClosedCurve().
GdipAddPathClosedCurve2I()
GpStatus WINGDIPAPI GdipAddPathClosedCurve2I (GpPath * , GDIPCONST GpPoint * , INT , REAL)
Referenced by GraphicsPath::AddClosedCurve().
GdipAddPathClosedCurveI()
GpStatus WINGDIPAPI GdipAddPathClosedCurveI (GpPath * , GDIPCONST GpPoint * , INT)
Referenced by GraphicsPath::AddClosedCurve().
GdipAddPathCurve()
GpStatus WINGDIPAPI GdipAddPathCurve (GpPath * , GDIPCONST GpPointF * , INT)
Referenced by GraphicsPath::AddCurve().
GdipAddPathCurve2()
GpStatus WINGDIPAPI GdipAddPathCurve2 (GpPath * , GDIPCONST GpPointF * , INT , REAL)
Referenced by GraphicsPath::AddCurve().
GdipAddPathCurve2I()
GpStatus WINGDIPAPI GdipAddPathCurve2I (GpPath * , GDIPCONST GpPoint * , INT , REAL)
Referenced by GraphicsPath::AddCurve().
GdipAddPathCurve3()
GpStatus WINGDIPAPI GdipAddPathCurve3 (GpPath * , GDIPCONST GpPointF * , INT , INT , INT , REAL)
Referenced by GraphicsPath::AddCurve().
GdipAddPathCurve3I()
GpStatus WINGDIPAPI GdipAddPathCurve3I (GpPath * , GDIPCONST GpPoint * , INT , INT , INT , REAL)
Referenced by GraphicsPath::AddCurve().
GdipAddPathCurveI()
GpStatus WINGDIPAPI GdipAddPathCurveI (GpPath * , GDIPCONST GpPoint * , INT)
Referenced by GraphicsPath::AddCurve().
GdipAddPathEllipse()
GpStatus WINGDIPAPI GdipAddPathEllipse (GpPath * , REAL , REAL , REAL , REAL)
Referenced by GraphicsPath::AddEllipse().
GdipAddPathEllipseI()
GpStatus WINGDIPAPI GdipAddPathEllipseI (GpPath * , INT , INT , INT , INT)
Referenced by GraphicsPath::AddEllipse().
GdipAddPathLine()
GpStatus WINGDIPAPI GdipAddPathLine (GpPath * , REAL , REAL , REAL , REAL)
Referenced by GraphicsPath::AddLine().
GdipAddPathLine2()
GpStatus WINGDIPAPI GdipAddPathLine2 (GpPath * , GDIPCONST GpPointF * , INT)
Referenced by GraphicsPath::AddLines().
GdipAddPathLine2I()
GpStatus WINGDIPAPI GdipAddPathLine2I (GpPath * , GDIPCONST GpPoint * , INT)
Referenced by GraphicsPath::AddLines().
GdipAddPathLineI()
GpStatus WINGDIPAPI GdipAddPathLineI (GpPath * , INT , INT , INT , INT)
Referenced by GraphicsPath::AddLine().
GdipAddPathPath()
GpStatus WINGDIPAPI GdipAddPathPath (GpPath * , GDIPCONST GpPath * , BOOL)
Referenced by GraphicsPath::AddPath().
GdipAddPathPie()
GpStatus WINGDIPAPI GdipAddPathPie (GpPath * , REAL , REAL , REAL , REAL , REAL , REAL)
Referenced by GraphicsPath::AddPie().
GdipAddPathPieI()
GpStatus WINGDIPAPI GdipAddPathPieI (GpPath * , INT , INT , INT , INT , REAL , REAL)
Referenced by GraphicsPath::AddPie().
GdipAddPathPolygon()
GpStatus WINGDIPAPI GdipAddPathPolygon (GpPath * , GDIPCONST GpPointF * , INT)
Referenced by GraphicsPath::AddPolygon().
GdipAddPathPolygonI()
GpStatus WINGDIPAPI GdipAddPathPolygonI (GpPath * , GDIPCONST GpPoint * , INT)
Referenced by GraphicsPath::AddPolygon().
GdipAddPathRectangle()
GpStatus WINGDIPAPI GdipAddPathRectangle (GpPath * , REAL , REAL , REAL , REAL)
Referenced by GraphicsPath::AddRectangle().
GdipAddPathRectangleI()
GpStatus WINGDIPAPI GdipAddPathRectangleI (GpPath * , INT , INT , INT , INT)
Referenced by GraphicsPath::AddRectangle().
GdipAddPathRectangles()
GpStatus WINGDIPAPI GdipAddPathRectangles (GpPath * , GDIPCONST GpRectF * , INT)
Referenced by GraphicsPath::AddRectangles().
GdipAddPathRectanglesI()
GpStatus WINGDIPAPI GdipAddPathRectanglesI (GpPath * , GDIPCONST GpRect * , INT)
Referenced by GraphicsPath::AddRectangles().
GdipAddPathString()
GpStatus WINGDIPAPI GdipAddPathString (GpPath * , GDIPCONST WCHAR * , INT , GDIPCONST GpFontFamily * , INT , REAL , GDIPCONST RectF * , GDIPCONST GpStringFormat *)
Referenced by GraphicsPath::AddString().
GdipAddPathStringI()
GpStatus WINGDIPAPI GdipAddPathStringI (GpPath * , GDIPCONST WCHAR * , INT , GDIPCONST GpFontFamily * , INT , REAL , GDIPCONST Rect * , GDIPCONST GpStringFormat *)
Referenced by GraphicsPath::AddString().
GdipBeginContainer()
GpStatus WINGDIPAPI GdipBeginContainer (GpGraphics * , GDIPCONST GpRectF * , GDIPCONST GpRectF * , GpUnit , GraphicsContainer *)
Referenced by Graphics::BeginContainer().
GdipBeginContainer2()
GpStatus WINGDIPAPI GdipBeginContainer2 (GpGraphics * , GraphicsContainer *)
Referenced by Graphics::BeginContainer().
GdipBeginContainerI()
GpStatus WINGDIPAPI GdipBeginContainerI (GpGraphics * , GDIPCONST GpRect * , GDIPCONST GpRect * , GpUnit , GraphicsContainer *)
Referenced by Graphics::BeginContainer().
GdipBitmapApplyEffect()
GpStatus WINGDIPAPI GdipBitmapApplyEffect (GpBitmap * , CGpEffect * , RECT * , BOOL , VOID ** , INT *)
GdipBitmapConvertFormat()
GpStatus WINGDIPAPI GdipBitmapConvertFormat (GpBitmap * , PixelFormat , DitherType , PaletteType , ColorPalette * , REAL)
Referenced by Bitmap::ConvertFormat().
GdipBitmapCreateApplyEffect()
GpStatus WINGDIPAPI GdipBitmapCreateApplyEffect (GpBitmap ** , INT , CGpEffect * , RECT * , RECT * , GpBitmap ** , BOOL , VOID ** , INT *)
GdipBitmapGetHistogram()
GpStatus WINGDIPAPI GdipBitmapGetHistogram (GpBitmap * , HistogramFormat , UINT , UINT * , UINT * , UINT * , UINT *)
Referenced by Bitmap::GetHistogram().
GdipBitmapGetHistogramSize()
GpStatus WINGDIPAPI GdipBitmapGetHistogramSize (HistogramFormat , UINT *)
Referenced by Bitmap::GetHistogramSize().
GdipBitmapGetPixel()
GpStatus WINGDIPAPI GdipBitmapGetPixel (GpBitmap * , INT , INT , ARGB *)
Referenced by Bitmap::GetPixel().
GdipBitmapLockBits()
GpStatus WINGDIPAPI GdipBitmapLockBits (GpBitmap * , GDIPCONST GpRect * , UINT , PixelFormat , BitmapData *)
Referenced by Bitmap::LockBits().
GdipBitmapSetPixel()
GpStatus WINGDIPAPI GdipBitmapSetPixel (GpBitmap * , INT , INT , ARGB)
Referenced by Bitmap::SetPixel().
GdipBitmapSetResolution()
GpStatus WINGDIPAPI GdipBitmapSetResolution (GpBitmap * , REAL , REAL)
Referenced by Bitmap::SetResolution().
GdipBitmapUnlockBits()
GpStatus WINGDIPAPI GdipBitmapUnlockBits (GpBitmap * , BitmapData *)
Referenced by Bitmap::UnlockBits().
GdipClearPathMarkers()
GpStatus WINGDIPAPI GdipClearPathMarkers (GpPath *)
Referenced by GraphicsPath::ClearMarkers().
GdipCloneBitmapArea()
GpStatus WINGDIPAPI GdipCloneBitmapArea (REAL , REAL , REAL , REAL , PixelFormat , GpBitmap * , GpBitmap **)
Referenced by Bitmap::Clone().
GdipCloneBitmapAreaI()
GpStatus WINGDIPAPI GdipCloneBitmapAreaI (INT , INT , INT , INT , PixelFormat , GpBitmap * , GpBitmap **)
Referenced by Bitmap::Clone().
GdipCloneBrush()
GpStatus WINGDIPAPI GdipCloneBrush (GpBrush * , GpBrush **)
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), TextureBrush::Clone(), and PathGradientBrush::Clone().
GdipCloneCustomLineCap()
GpStatus WINGDIPAPI GdipCloneCustomLineCap (GpCustomLineCap * , GpCustomLineCap **)
Referenced by AdjustableArrowCap::Clone(), and CustomLineCap::Clone().
GdipCloneFont()
GpStatus WINGDIPAPI GdipCloneFont (GpFont * , GpFont **)
Referenced by Font::Clone().
GdipCloneFontFamily()
GpStatus WINGDIPAPI GdipCloneFontFamily (GpFontFamily * , GpFontFamily **)
Referenced by FontFamily::Clone(), and FontCollection::GetFamilies().
GdipCloneImage()
GpStatus WINGDIPAPI GdipCloneImage (GpImage * , GpImage **)
Referenced by Image::Clone(), Bitmap::Clone(), and Metafile::Clone().
GdipCloneImageAttributes()
GpStatus WINGDIPAPI GdipCloneImageAttributes (GDIPCONST GpImageAttributes * , GpImageAttributes **)
Referenced by ImageAttributes::Clone().
GdipCloneMatrix()
GpStatus WINGDIPAPI GdipCloneMatrix (GpMatrix * , GpMatrix **)
Referenced by Matrix::Clone().
GdipClonePath()
GpStatus WINGDIPAPI GdipClonePath (GpPath * , GpPath **)
Referenced by GraphicsPath::Clone().
GdipClonePen()
GpStatus WINGDIPAPI GdipClonePen (GpPen * , GpPen **)
Referenced by Pen::Clone().
GdipCloneRegion()
GpStatus WINGDIPAPI GdipCloneRegion (GpRegion * , GpRegion **)
Referenced by Region::Clone().
GdipCloneStringFormat()
GpStatus WINGDIPAPI GdipCloneStringFormat (GDIPCONST GpStringFormat * , GpStringFormat **)
Referenced by StringFormat::Clone(), and StringFormat::StringFormat().
GdipClosePathFigure()
GpStatus WINGDIPAPI GdipClosePathFigure (GpPath *)
Referenced by GraphicsPath::CloseFigure().
GdipClosePathFigures()
GpStatus WINGDIPAPI GdipClosePathFigures (GpPath *)
Referenced by GraphicsPath::CloseAllFigures().
GdipCombineRegionPath()
GpStatus WINGDIPAPI GdipCombineRegionPath (GpRegion * , GpPath * , CombineMode)
Referenced by Region::Complement(), Region::Exclude(), Region::Intersect(), Region::Union(), and Region::Xor().
GdipCombineRegionRect()
GpStatus WINGDIPAPI GdipCombineRegionRect (GpRegion * , GDIPCONST GpRectF * , CombineMode)
Referenced by Region::Complement(), Region::Exclude(), Region::Intersect(), Region::Union(), and Region::Xor().
GdipCombineRegionRectI()
GpStatus WINGDIPAPI GdipCombineRegionRectI (GpRegion * , GDIPCONST GpRect * , CombineMode)
Referenced by Region::Complement(), Region::Exclude(), Region::Intersect(), Region::Union(), and Region::Xor().
GdipCombineRegionRegion()
GpStatus WINGDIPAPI GdipCombineRegionRegion (GpRegion * , GpRegion * , CombineMode)
Referenced by Region::Complement(), Region::Exclude(), Region::Intersect(), Region::Union(), and Region::Xor().
GdipComment()
GpStatus WINGDIPAPI GdipComment (GpGraphics * , UINT , GDIPCONST BYTE *)
Referenced by Graphics::AddMetafileComment().
GdipConvertToEmfPlus()
GpStatus WINGDIPAPI GdipConvertToEmfPlus (GDIPCONST GpGraphics * , GpMetafile * , BOOL * , EmfType , GDIPCONST WCHAR * , GpMetafile **)
GdipConvertToEmfPlusToFile()
GpStatus WINGDIPAPI GdipConvertToEmfPlusToFile (GDIPCONST GpGraphics * , GpMetafile * , BOOL * , GDIPCONST WCHAR * , EmfType , GDIPCONST WCHAR * , GpMetafile **)
GdipConvertToEmfPlusToStream()
GpStatus WINGDIPAPI GdipConvertToEmfPlusToStream (GDIPCONST GpGraphics * , GpMetafile * , BOOL * , IStream * , EmfType , GDIPCONST WCHAR * , GpMetafile **)
GdipCreateAdjustableArrowCap()
GpStatus WINGDIPAPI GdipCreateAdjustableArrowCap (REAL , REAL , BOOL , GpAdjustableArrowCap **)
Referenced by AdjustableArrowCap::AdjustableArrowCap().
GdipCreateBitmapFromDirectDrawSurface()
GpStatus WINGDIPAPI GdipCreateBitmapFromDirectDrawSurface (IDirectDrawSurface7 * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromFile()
GpStatus WINGDIPAPI GdipCreateBitmapFromFile (GDIPCONST WCHAR * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromFileICM()
GpStatus WINGDIPAPI GdipCreateBitmapFromFileICM (GDIPCONST WCHAR * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromGdiDib()
GpStatus WINGDIPAPI GdipCreateBitmapFromGdiDib (GDIPCONST BITMAPINFO * , VOID * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromGraphics()
GpStatus WINGDIPAPI GdipCreateBitmapFromGraphics (INT , INT , GpGraphics * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromHBITMAP()
GpStatus WINGDIPAPI GdipCreateBitmapFromHBITMAP (HBITMAP , HPALETTE , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromHICON()
GpStatus WINGDIPAPI GdipCreateBitmapFromHICON (HICON , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromResource()
GpStatus WINGDIPAPI GdipCreateBitmapFromResource (HINSTANCE , GDIPCONST WCHAR * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromScan0()
GpStatus WINGDIPAPI GdipCreateBitmapFromScan0 (INT , INT , INT , PixelFormat , BYTE * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromStream()
GpStatus WINGDIPAPI GdipCreateBitmapFromStream (IStream * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateBitmapFromStreamICM()
GpStatus WINGDIPAPI GdipCreateBitmapFromStreamICM (IStream * , GpBitmap **)
Referenced by Bitmap::Bitmap().
GdipCreateCachedBitmap()
GpStatus WINGDIPAPI GdipCreateCachedBitmap (GpBitmap * , GpGraphics * , GpCachedBitmap **)
Referenced by CachedBitmap::CachedBitmap().
GdipCreateCustomLineCap()
GpStatus WINGDIPAPI GdipCreateCustomLineCap (GpPath * , GpPath * , GpLineCap , REAL , GpCustomLineCap **)
Referenced by CustomLineCap::CustomLineCap().
GdipCreateEffect()
GpStatus WINGDIPAPI GdipCreateEffect (GDIPCONST GUID, CGpEffect **)
GdipCreateFont()
GpStatus WINGDIPAPI GdipCreateFont (GDIPCONST GpFontFamily * , REAL , INT , Unit , GpFont **)
Referenced by Font::Font().
GdipCreateFontFamilyFromName()
GpStatus WINGDIPAPI GdipCreateFontFamilyFromName (GDIPCONST WCHAR * , GpFontCollection * , GpFontFamily **)
Referenced by Font::Font(), and FontFamily::FontFamily().
GdipCreateFontFromDC()
GpStatus WINGDIPAPI GdipCreateFontFromDC (HDC , GpFont **)
Referenced by Font::Font().
GdipCreateFontFromLogfontA()
GpStatus WINGDIPAPI GdipCreateFontFromLogfontA (HDC , GDIPCONST LOGFONTA * , GpFont **)
Referenced by Font::Font().
GdipCreateFontFromLogfontW()
GpStatus WINGDIPAPI GdipCreateFontFromLogfontW (HDC , GDIPCONST LOGFONTW * , GpFont **)
Referenced by Font::Font().
GdipCreateFromHDC()
GpStatus WINGDIPAPI GdipCreateFromHDC (HDC , GpGraphics **)
Referenced by Graphics::Graphics().
GdipCreateFromHDC2()
GpStatus WINGDIPAPI GdipCreateFromHDC2 (HDC , HANDLE , GpGraphics **)
Referenced by Graphics::Graphics().
GdipCreateFromHWND()
GpStatus WINGDIPAPI GdipCreateFromHWND (HWND , GpGraphics **)
Referenced by Graphics::Graphics().
GdipCreateFromHWNDICM()
GpStatus WINGDIPAPI GdipCreateFromHWNDICM (HWND , GpGraphics **)
Referenced by Graphics::Graphics().
GdipCreateHalftonePalette()
HPALETTE WINGDIPAPI GdipCreateHalftonePalette (void)
Referenced by Graphics::GetHalftonePalette().
GdipCreateHatchBrush()
GpStatus WINGDIPAPI GdipCreateHatchBrush (GpHatchStyle , ARGB , ARGB , GpHatch **)
Referenced by HatchBrush::HatchBrush().
GdipCreateHBITMAPFromBitmap()
GpStatus WINGDIPAPI GdipCreateHBITMAPFromBitmap (GpBitmap * , HBITMAP * , ARGB)
Referenced by Bitmap::GetHBITMAP().
GdipCreateHICONFromBitmap()
GpStatus WINGDIPAPI GdipCreateHICONFromBitmap (GpBitmap * , HICON *)
Referenced by Bitmap::GetHICON().
GdipCreateImageAttributes()
GpStatus WINGDIPAPI GdipCreateImageAttributes (GpImageAttributes **)
Referenced by ImageAttributes::ImageAttributes().
GdipCreateLineBrush()
GpStatus WINGDIPAPI GdipCreateLineBrush (GDIPCONST GpPointF * , GDIPCONST GpPointF * , ARGB , ARGB , GpWrapMode , GpLineGradient **)
Referenced by LinearGradientBrush::LinearGradientBrush().
GdipCreateLineBrushFromRect()
GpStatus WINGDIPAPI GdipCreateLineBrushFromRect (GDIPCONST GpRectF * , ARGB , ARGB , LinearGradientMode , GpWrapMode , GpLineGradient **)
Referenced by LinearGradientBrush::LinearGradientBrush().
GdipCreateLineBrushFromRectI()
GpStatus WINGDIPAPI GdipCreateLineBrushFromRectI (GDIPCONST GpRect * , ARGB , ARGB , LinearGradientMode , GpWrapMode , GpLineGradient **)
Referenced by LinearGradientBrush::LinearGradientBrush().
GdipCreateLineBrushFromRectWithAngle()
GpStatus WINGDIPAPI GdipCreateLineBrushFromRectWithAngle (GDIPCONST GpRectF * , ARGB , ARGB , REAL , BOOL , GpWrapMode , GpLineGradient **)
Referenced by LinearGradientBrush::LinearGradientBrush().
GdipCreateLineBrushFromRectWithAngleI()
GpStatus WINGDIPAPI GdipCreateLineBrushFromRectWithAngleI (GDIPCONST GpRect * , ARGB , ARGB , REAL , BOOL , GpWrapMode , GpLineGradient **)
Referenced by LinearGradientBrush::LinearGradientBrush().
GdipCreateLineBrushI()
GpStatus WINGDIPAPI GdipCreateLineBrushI (GDIPCONST GpPoint * , GDIPCONST GpPoint * , ARGB , ARGB , GpWrapMode , GpLineGradient **)
Referenced by LinearGradientBrush::LinearGradientBrush().
GdipCreateMatrix()
GpStatus WINGDIPAPI GdipCreateMatrix (GpMatrix **)
Referenced by Matrix::Matrix().
GdipCreateMatrix2()
GpStatus WINGDIPAPI GdipCreateMatrix2 (REAL , REAL , REAL , REAL , REAL , REAL , GpMatrix **)
Referenced by Matrix::Matrix().
GdipCreateMatrix3()
GpStatus WINGDIPAPI GdipCreateMatrix3 (GDIPCONST GpRectF * , GDIPCONST GpPointF * , GpMatrix **)
Referenced by Matrix::Matrix().
GdipCreateMatrix3I()
GpStatus WINGDIPAPI GdipCreateMatrix3I (GDIPCONST GpRect * , GDIPCONST GpPoint * , GpMatrix **)
Referenced by Matrix::Matrix().
GdipCreateMetafileFromEmf()
GpStatus WINGDIPAPI GdipCreateMetafileFromEmf (HENHMETAFILE , BOOL , GpMetafile **)
Referenced by Metafile::Metafile().
GdipCreateMetafileFromFile()
GpStatus WINGDIPAPI GdipCreateMetafileFromFile (GDIPCONST WCHAR * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipCreateMetafileFromStream()
GpStatus WINGDIPAPI GdipCreateMetafileFromStream (IStream * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipCreateMetafileFromWmf()
GpStatus WINGDIPAPI GdipCreateMetafileFromWmf (HMETAFILE , BOOL , GDIPCONST WmfPlaceableFileHeader * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipCreateMetafileFromWmfFile()
GpStatus WINGDIPAPI GdipCreateMetafileFromWmfFile (GDIPCONST WCHAR * , GDIPCONST WmfPlaceableFileHeader * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipCreatePath()
GpStatus WINGDIPAPI GdipCreatePath (GpFillMode , GpPath **)
Referenced by GraphicsPath::GraphicsPath().
GdipCreatePath2()
GpStatus WINGDIPAPI GdipCreatePath2 (GDIPCONST GpPointF * , GDIPCONST BYTE * , INT , GpFillMode , GpPath **)
Referenced by GraphicsPath::GraphicsPath().
GdipCreatePath2I()
GpStatus WINGDIPAPI GdipCreatePath2I (GDIPCONST GpPoint * , GDIPCONST BYTE * , INT , GpFillMode , GpPath **)
Referenced by GraphicsPath::GraphicsPath().
GdipCreatePathGradient()
GpStatus WINGDIPAPI GdipCreatePathGradient (GDIPCONST GpPointF * , INT , GpWrapMode , GpPathGradient **)
Referenced by PathGradientBrush::PathGradientBrush().
GdipCreatePathGradientFromPath()
GpStatus WINGDIPAPI GdipCreatePathGradientFromPath (GDIPCONST GpPath * , GpPathGradient **)
Referenced by PathGradientBrush::PathGradientBrush().
GdipCreatePathGradientI()
GpStatus WINGDIPAPI GdipCreatePathGradientI (GDIPCONST GpPoint * , INT , GpWrapMode , GpPathGradient **)
Referenced by PathGradientBrush::PathGradientBrush().
GdipCreatePathIter()
GpStatus WINGDIPAPI GdipCreatePathIter (GpPathIterator ** , GpPath *)
Referenced by GraphicsPathIterator::GraphicsPathIterator().
GdipCreatePen1()
GpStatus WINGDIPAPI GdipCreatePen1 (ARGB , REAL , GpUnit , GpPen **)
Referenced by Pen::Pen().
GdipCreatePen2()
GpStatus WINGDIPAPI GdipCreatePen2 (GpBrush * , REAL , GpUnit , GpPen **)
Referenced by Pen::Pen().
GdipCreateRegion()
GpStatus WINGDIPAPI GdipCreateRegion (GpRegion **)
Referenced by Region::Region().
GdipCreateRegionHrgn()
GpStatus WINGDIPAPI GdipCreateRegionHrgn (HRGN , GpRegion **)
Referenced by Region::Region().
GdipCreateRegionPath()
GpStatus WINGDIPAPI GdipCreateRegionPath (GpPath * , GpRegion **)
Referenced by Region::Region().
GdipCreateRegionRect()
GpStatus WINGDIPAPI GdipCreateRegionRect (GDIPCONST GpRectF * , GpRegion **)
Referenced by Region::Region().
GdipCreateRegionRectI()
GpStatus WINGDIPAPI GdipCreateRegionRectI (GDIPCONST GpRect * , GpRegion **)
Referenced by Region::Region().
GdipCreateRegionRgnData()
GpStatus WINGDIPAPI GdipCreateRegionRgnData (GDIPCONST BYTE * , INT , GpRegion **)
Referenced by Region::Region().
GdipCreateSolidFill()
GpStatus WINGDIPAPI GdipCreateSolidFill (ARGB , GpSolidFill **)
Referenced by SolidBrush::SolidBrush().
GdipCreateStreamOnFile()
GpStatus WINGDIPAPI GdipCreateStreamOnFile (GDIPCONST WCHAR * , UINT , IStream **)
GdipCreateStringFormat()
GpStatus WINGDIPAPI GdipCreateStringFormat (INT , LANGID , GpStringFormat **)
Referenced by StringFormat::StringFormat().
GdipCreateTexture()
GpStatus WINGDIPAPI GdipCreateTexture (GpImage * , GpWrapMode , GpTexture **)
Referenced by TextureBrush::TextureBrush().
GdipCreateTexture2()
GpStatus WINGDIPAPI GdipCreateTexture2 (GpImage * , GpWrapMode , REAL , REAL , REAL , REAL , GpTexture **)
Referenced by TextureBrush::TextureBrush().
GdipCreateTexture2I()
GpStatus WINGDIPAPI GdipCreateTexture2I (GpImage * , GpWrapMode , INT , INT , INT , INT , GpTexture **)
Referenced by TextureBrush::TextureBrush().
GdipCreateTextureIA()
GpStatus WINGDIPAPI GdipCreateTextureIA (GpImage * , GDIPCONST GpImageAttributes * , REAL , REAL , REAL , REAL , GpTexture **)
Referenced by TextureBrush::TextureBrush().
GdipCreateTextureIAI()
GpStatus WINGDIPAPI GdipCreateTextureIAI (GpImage * , GDIPCONST GpImageAttributes * , INT , INT , INT , INT , GpTexture **)
Referenced by TextureBrush::TextureBrush().
GdipDeleteBrush()
GpStatus WINGDIPAPI GdipDeleteBrush (GpBrush *)
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), and Brush::~Brush().
GdipDeleteCachedBitmap()
GpStatus WINGDIPAPI GdipDeleteCachedBitmap (GpCachedBitmap *)
Referenced by CachedBitmap::~CachedBitmap().
GdipDeleteCustomLineCap()
GpStatus WINGDIPAPI GdipDeleteCustomLineCap (GpCustomLineCap *)
Referenced by AdjustableArrowCap::Clone(), CustomLineCap::Clone(), and CustomLineCap::~CustomLineCap().
GdipDeleteEffect()
GpStatus WINGDIPAPI GdipDeleteEffect (CGpEffect *)
GdipDeleteFont()
GpStatus WINGDIPAPI GdipDeleteFont (GpFont *)
Referenced by Font::Clone(), and Font::~Font().
GdipDeleteFontFamily()
GpStatus WINGDIPAPI GdipDeleteFontFamily (GpFontFamily *)
Referenced by FontFamily::Clone(), Font::Font(), and FontFamily::~FontFamily().
GdipDeleteGraphics()
GpStatus WINGDIPAPI GdipDeleteGraphics (GpGraphics *)
Referenced by Graphics::~Graphics().
GdipDeleteMatrix()
GpStatus WINGDIPAPI GdipDeleteMatrix (GpMatrix *)
Referenced by Matrix::Clone(), and Matrix::~Matrix().
GdipDeletePath()
GpStatus WINGDIPAPI GdipDeletePath (GpPath *)
Referenced by GraphicsPath::Clone(), and GraphicsPath::~GraphicsPath().
GdipDeletePathIter()
GpStatus WINGDIPAPI GdipDeletePathIter (GpPathIterator *)
Referenced by GraphicsPathIterator::~GraphicsPathIterator().
GdipDeletePen()
GpStatus WINGDIPAPI GdipDeletePen (GpPen *)
Referenced by Pen::Clone(), and Pen::~Pen().
GdipDeletePrivateFontCollection()
GpStatus WINGDIPAPI GdipDeletePrivateFontCollection (GpFontCollection **)
Referenced by PrivateFontCollection::~PrivateFontCollection().
GdipDeleteRegion()
GpStatus WINGDIPAPI GdipDeleteRegion (GpRegion *)
Referenced by Region::Clone(), and Region::~Region().
GdipDeleteStringFormat()
GpStatus WINGDIPAPI GdipDeleteStringFormat (GpStringFormat *)
Referenced by StringFormat::Clone(), and StringFormat::~StringFormat().
GdipDisposeImage()
GpStatus WINGDIPAPI GdipDisposeImage (GpImage *)
Referenced by Image::Clone(), Bitmap::Clone(), Metafile::Clone(), Image::GetThumbnailImage(), and Image::~Image().
GdipDisposeImageAttributes()
GpStatus WINGDIPAPI GdipDisposeImageAttributes (GpImageAttributes *)
Referenced by ImageAttributes::Clone(), and ImageAttributes::~ImageAttributes().
GdipDrawArc()
GpStatus WINGDIPAPI GdipDrawArc (GpGraphics * , GpPen * , REAL , REAL , REAL , REAL , REAL , REAL)
Referenced by Graphics::DrawArc().
GdipDrawArcI()
GpStatus WINGDIPAPI GdipDrawArcI (GpGraphics * , GpPen * , INT , INT , INT , INT , REAL , REAL)
Referenced by Graphics::DrawArc().
GdipDrawBezier()
GpStatus WINGDIPAPI GdipDrawBezier (GpGraphics * , GpPen * , REAL , REAL , REAL , REAL , REAL , REAL , REAL , REAL)
Referenced by Graphics::DrawBezier().
GdipDrawBezierI()
GpStatus WINGDIPAPI GdipDrawBezierI (GpGraphics * , GpPen * , INT , INT , INT , INT , INT , INT , INT , INT)
Referenced by Graphics::DrawBezier().
GdipDrawBeziers()
GpStatus WINGDIPAPI GdipDrawBeziers (GpGraphics * , GpPen * , GDIPCONST GpPointF * , INT)
Referenced by Graphics::DrawBeziers().
GdipDrawBeziersI()
GpStatus WINGDIPAPI GdipDrawBeziersI (GpGraphics * , GpPen * , GDIPCONST GpPoint * , INT)
Referenced by Graphics::DrawBeziers().
GdipDrawCachedBitmap()
GpStatus WINGDIPAPI GdipDrawCachedBitmap (GpGraphics * , GpCachedBitmap * , INT , INT)
Referenced by Graphics::DrawCachedBitmap().
GdipDrawClosedCurve()
GpStatus WINGDIPAPI GdipDrawClosedCurve (GpGraphics * , GpPen * , GDIPCONST GpPointF * , INT)
Referenced by Graphics::DrawClosedCurve().
GdipDrawClosedCurve2()
GpStatus WINGDIPAPI GdipDrawClosedCurve2 (GpGraphics * , GpPen * , GDIPCONST GpPointF * , INT , REAL)
Referenced by Graphics::DrawClosedCurve().
GdipDrawClosedCurve2I()
GpStatus WINGDIPAPI GdipDrawClosedCurve2I (GpGraphics * , GpPen * , GDIPCONST GpPoint * , INT , REAL)
Referenced by Graphics::DrawClosedCurve().
GdipDrawClosedCurveI()
GpStatus WINGDIPAPI GdipDrawClosedCurveI (GpGraphics * , GpPen * , GDIPCONST GpPoint * , INT)
Referenced by Graphics::DrawClosedCurve().
GdipDrawCurve()
GpStatus WINGDIPAPI GdipDrawCurve (GpGraphics * , GpPen * , GDIPCONST GpPointF * , INT)
Referenced by Graphics::DrawCurve().
GdipDrawCurve2()
GpStatus WINGDIPAPI GdipDrawCurve2 (GpGraphics * , GpPen * , GDIPCONST GpPointF * , INT , REAL)
Referenced by Graphics::DrawCurve().
GdipDrawCurve2I()
GpStatus WINGDIPAPI GdipDrawCurve2I (GpGraphics * , GpPen * , GDIPCONST GpPoint * , INT , REAL)
Referenced by Graphics::DrawCurve().
GdipDrawCurve3()
GpStatus WINGDIPAPI GdipDrawCurve3 (GpGraphics * , GpPen * , GDIPCONST GpPointF * , INT , INT , INT , REAL)
Referenced by Graphics::DrawCurve().
GdipDrawCurve3I()
GpStatus WINGDIPAPI GdipDrawCurve3I (GpGraphics * , GpPen * , GDIPCONST GpPoint * , INT , INT , INT , REAL)
Referenced by Graphics::DrawCurve().
GdipDrawCurveI()
GpStatus WINGDIPAPI GdipDrawCurveI (GpGraphics * , GpPen * , GDIPCONST GpPoint * , INT)
Referenced by Graphics::DrawCurve().
GdipDrawDriverString()
GpStatus WINGDIPAPI GdipDrawDriverString (GpGraphics * , GDIPCONST UINT16 * , INT , GDIPCONST GpFont * , GDIPCONST GpBrush * , GDIPCONST PointF * , INT , GDIPCONST GpMatrix *)
Referenced by Graphics::DrawDriverString().
GdipDrawEllipse()
GpStatus WINGDIPAPI GdipDrawEllipse (GpGraphics * , GpPen * , REAL , REAL , REAL , REAL)
Referenced by Graphics::DrawEllipse().
GdipDrawEllipseI()
GpStatus WINGDIPAPI GdipDrawEllipseI (GpGraphics * , GpPen * , INT , INT , INT , INT)
Referenced by Graphics::DrawEllipse().
GdipDrawImage()
GpStatus WINGDIPAPI GdipDrawImage (GpGraphics * , GpImage * , REAL , REAL)
Referenced by Graphics::DrawImage().
GdipDrawImageFX()
GpStatus WINGDIPAPI GdipDrawImageFX (GpGraphics * , GpImage * , GpRectF * , GpMatrix * , CGpEffect * , GpImageAttributes * , GpUnit)
GdipDrawImageI()
GpStatus WINGDIPAPI GdipDrawImageI (GpGraphics * , GpImage * , INT , INT)
Referenced by Graphics::DrawImage().
GdipDrawImagePointRect()
GpStatus WINGDIPAPI GdipDrawImagePointRect (GpGraphics * , GpImage * , REAL , REAL , REAL , REAL , REAL , REAL , GpUnit)
Referenced by Graphics::DrawImage().
GdipDrawImagePointRectI()
GpStatus WINGDIPAPI GdipDrawImagePointRectI (GpGraphics * , GpImage * , INT , INT , INT , INT , INT , INT , GpUnit)
Referenced by Graphics::DrawImage().
GdipDrawImagePoints()
GpStatus WINGDIPAPI GdipDrawImagePoints (GpGraphics * , GpImage * , GDIPCONST GpPointF * , INT)
Referenced by Graphics::DrawImage().
GdipDrawImagePointsI()
GpStatus WINGDIPAPI GdipDrawImagePointsI (GpGraphics * , GpImage * , GDIPCONST GpPoint * , INT)
Referenced by Graphics::DrawImage().
GdipDrawImagePointsRect()
GpStatus WINGDIPAPI GdipDrawImagePointsRect (GpGraphics * , GpImage * , GDIPCONST GpPointF * , INT , REAL , REAL , REAL , REAL , GpUnit , GDIPCONST GpImageAttributes * , DrawImageAbort , VOID *)
Referenced by Graphics::DrawImage().
GdipDrawImagePointsRectI()
GpStatus WINGDIPAPI GdipDrawImagePointsRectI (GpGraphics * , GpImage * , GDIPCONST GpPoint * , INT , INT , INT , INT , INT , GpUnit , GDIPCONST GpImageAttributes * , DrawImageAbort , VOID *)
Referenced by Graphics::DrawImage().
GdipDrawImageRect()
GpStatus WINGDIPAPI GdipDrawImageRect (GpGraphics * , GpImage * , REAL , REAL , REAL , REAL)
Referenced by Graphics::DrawImage().
GdipDrawImageRectI()
GpStatus WINGDIPAPI GdipDrawImageRectI (GpGraphics * , GpImage * , INT , INT , INT , INT)
Referenced by Graphics::DrawImage().
GdipDrawImageRectRect()
GpStatus WINGDIPAPI GdipDrawImageRectRect (GpGraphics * , GpImage * , REAL , REAL , REAL , REAL , REAL , REAL , REAL , REAL , GpUnit , GDIPCONST GpImageAttributes * , DrawImageAbort , VOID *)
Referenced by Graphics::DrawImage().
GdipDrawImageRectRectI()
GpStatus WINGDIPAPI GdipDrawImageRectRectI (GpGraphics * , GpImage * , INT , INT , INT , INT , INT , INT , INT , INT , GpUnit , GDIPCONST GpImageAttributes * , DrawImageAbort , VOID *)
Referenced by Graphics::DrawImage().
GdipDrawLine()
GpStatus WINGDIPAPI GdipDrawLine (GpGraphics * , GpPen * , REAL , REAL , REAL , REAL)
Referenced by Graphics::DrawLine().
GdipDrawLineI()
GpStatus WINGDIPAPI GdipDrawLineI (GpGraphics * , GpPen * , INT , INT , INT , INT)
Referenced by Graphics::DrawLine().
GdipDrawLines()
GpStatus WINGDIPAPI GdipDrawLines (GpGraphics * , GpPen * , GDIPCONST GpPointF * , INT)
Referenced by Graphics::DrawLines().
GdipDrawLinesI()
GpStatus WINGDIPAPI GdipDrawLinesI (GpGraphics * , GpPen * , GDIPCONST GpPoint * , INT)
Referenced by Graphics::DrawLines().
GdipDrawPath()
GpStatus WINGDIPAPI GdipDrawPath (GpGraphics * , GpPen * , GpPath *)
Referenced by Graphics::DrawPath().
GdipDrawPie()
GpStatus WINGDIPAPI GdipDrawPie (GpGraphics * , GpPen * , REAL , REAL , REAL , REAL , REAL , REAL)
Referenced by Graphics::DrawPie().
GdipDrawPieI()
GpStatus WINGDIPAPI GdipDrawPieI (GpGraphics * , GpPen * , INT , INT , INT , INT , REAL , REAL)
Referenced by Graphics::DrawPie().
GdipDrawPolygon()
GpStatus WINGDIPAPI GdipDrawPolygon (GpGraphics * , GpPen * , GDIPCONST GpPointF * , INT)
Referenced by Graphics::DrawPolygon().
GdipDrawPolygonI()
GpStatus WINGDIPAPI GdipDrawPolygonI (GpGraphics * , GpPen * , GDIPCONST GpPoint * , INT)
Referenced by Graphics::DrawPolygon().
GdipDrawRectangle()
GpStatus WINGDIPAPI GdipDrawRectangle (GpGraphics * , GpPen * , REAL , REAL , REAL , REAL)
Referenced by Graphics::DrawRectangle().
GdipDrawRectangleI()
GpStatus WINGDIPAPI GdipDrawRectangleI (GpGraphics * , GpPen * , INT , INT , INT , INT)
Referenced by Graphics::DrawRectangle().
GdipDrawRectangles()
GpStatus WINGDIPAPI GdipDrawRectangles (GpGraphics * , GpPen * , GDIPCONST GpRectF * , INT)
Referenced by Graphics::DrawRectangles().
GdipDrawRectanglesI()
GpStatus WINGDIPAPI GdipDrawRectanglesI (GpGraphics * , GpPen * , GDIPCONST GpRect * , INT)
Referenced by Graphics::DrawRectangles().
GdipDrawString()
GpStatus WINGDIPAPI GdipDrawString (GpGraphics * , GDIPCONST WCHAR * , INT , GDIPCONST GpFont * , GDIPCONST RectF * , GDIPCONST GpStringFormat * , GDIPCONST GpBrush *)
Referenced by Graphics::DrawString().
GdipEmfToWmfBits()
UINT WINGDIPAPI GdipEmfToWmfBits (HENHMETAFILE , UINT , LPBYTE , INT , INT)
Referenced by Metafile::EmfToWmfBits().
GdipEndContainer()
GpStatus WINGDIPAPI GdipEndContainer (GpGraphics * , GraphicsContainer)
Referenced by Graphics::EndContainer().
GdipEnumerateMetafileDestPoints()
GpStatus WINGDIPAPI GdipEnumerateMetafileDestPoints (GpGraphics * , GDIPCONST GpMetafile * , GDIPCONST PointF * , INT , EnumerateMetafileProc , VOID * , GDIPCONST GpImageAttributes *)
Referenced by Graphics::EnumerateMetafile().
GdipEnumerateMetafileDestPointsI()
GpStatus WINGDIPAPI GdipEnumerateMetafileDestPointsI (GpGraphics * , GDIPCONST GpMetafile * , GDIPCONST Point * , INT , EnumerateMetafileProc , VOID * , GDIPCONST GpImageAttributes *)
Referenced by Graphics::EnumerateMetafile().
GdipFillClosedCurve()
GpStatus WINGDIPAPI GdipFillClosedCurve (GpGraphics * , GpBrush * , GDIPCONST GpPointF * , INT)
Referenced by Graphics::FillClosedCurve().
GdipFillClosedCurve2()
GpStatus WINGDIPAPI GdipFillClosedCurve2 (GpGraphics * , GpBrush * , GDIPCONST GpPointF * , INT , REAL , GpFillMode)
Referenced by Graphics::FillClosedCurve().
GdipFillClosedCurve2I()
GpStatus WINGDIPAPI GdipFillClosedCurve2I (GpGraphics * , GpBrush * , GDIPCONST GpPoint * , INT , REAL , GpFillMode)
Referenced by Graphics::FillClosedCurve().
GdipFillClosedCurveI()
GpStatus WINGDIPAPI GdipFillClosedCurveI (GpGraphics * , GpBrush * , GDIPCONST GpPoint * , INT)
Referenced by Graphics::FillClosedCurve().
GdipFillEllipse()
GpStatus WINGDIPAPI GdipFillEllipse (GpGraphics * , GpBrush * , REAL , REAL , REAL , REAL)
Referenced by Graphics::FillEllipse().
GdipFillEllipseI()
GpStatus WINGDIPAPI GdipFillEllipseI (GpGraphics * , GpBrush * , INT , INT , INT , INT)
Referenced by Graphics::FillEllipse().
GdipFillPath()
GpStatus WINGDIPAPI GdipFillPath (GpGraphics * , GpBrush * , GpPath *)
Referenced by Graphics::FillPath().
GdipFillPie()
GpStatus WINGDIPAPI GdipFillPie (GpGraphics * , GpBrush * , REAL , REAL , REAL , REAL , REAL , REAL)
Referenced by Graphics::FillPie().
GdipFillPieI()
GpStatus WINGDIPAPI GdipFillPieI (GpGraphics * , GpBrush * , INT , INT , INT , INT , REAL , REAL)
Referenced by Graphics::FillPie().
GdipFillPolygon()
GpStatus WINGDIPAPI GdipFillPolygon (GpGraphics * , GpBrush * , GDIPCONST GpPointF * , INT , GpFillMode)
Referenced by Graphics::FillPolygon().
GdipFillPolygon2()
GpStatus WINGDIPAPI GdipFillPolygon2 (GpGraphics * , GpBrush * , GDIPCONST GpPointF * , INT)
GdipFillPolygon2I()
GpStatus WINGDIPAPI GdipFillPolygon2I (GpGraphics * , GpBrush * , GDIPCONST GpPoint * , INT)
GdipFillPolygonI()
GpStatus WINGDIPAPI GdipFillPolygonI (GpGraphics * , GpBrush * , GDIPCONST GpPoint * , INT , GpFillMode)
Referenced by Graphics::FillPolygon().
GdipFillRectangle()
GpStatus WINGDIPAPI GdipFillRectangle (GpGraphics * , GpBrush * , REAL , REAL , REAL , REAL)
Referenced by Graphics::FillRectangle().
GdipFillRectangleI()
GpStatus WINGDIPAPI GdipFillRectangleI (GpGraphics * , GpBrush * , INT , INT , INT , INT)
Referenced by Graphics::FillRectangle().
GdipFillRectangles()
GpStatus WINGDIPAPI GdipFillRectangles (GpGraphics * , GpBrush * , GDIPCONST GpRectF * , INT)
Referenced by Graphics::FillRectangles().
GdipFillRectanglesI()
GpStatus WINGDIPAPI GdipFillRectanglesI (GpGraphics * , GpBrush * , GDIPCONST GpRect * , INT)
Referenced by Graphics::FillRectangles().
GdipFillRegion()
GpStatus WINGDIPAPI GdipFillRegion (GpGraphics * , GpBrush * , GpRegion *)
Referenced by Graphics::FillRegion().
GdipFindFirstImageItem()
GpStatus WINGDIPAPI GdipFindFirstImageItem (GpImage * , ImageItemData *)
Referenced by Image::FindFirstItem().
GdipFindNextImageItem()
GpStatus WINGDIPAPI GdipFindNextImageItem (GpImage * , ImageItemData *)
Referenced by Image::FindNextItem().
GdipFlattenPath()
GpStatus WINGDIPAPI GdipFlattenPath (GpPath * , GpMatrix * , REAL)
Referenced by GraphicsPath::Flatten().
GdipFlush()
GpStatus WINGDIPAPI GdipFlush (GpGraphics * , GpFlushIntention)
Referenced by Graphics::Flush().
GdipFontCollectionEnumerable()
GpStatus WINGDIPAPI GdipFontCollectionEnumerable (GpFontCollection * , GpGraphics * , INT *)
GdipFontCollectionEnumerate()
GpStatus WINGDIPAPI GdipFontCollectionEnumerate (GpFontCollection * , INT , GpFontFamily ** , INT * , GpGraphics *)
GdipGetAdjustableArrowCapFillState()
GpStatus WINGDIPAPI GdipGetAdjustableArrowCapFillState (GpAdjustableArrowCap * , BOOL *)
Referenced by AdjustableArrowCap::IsFilled().
GdipGetAdjustableArrowCapHeight()
GpStatus WINGDIPAPI GdipGetAdjustableArrowCapHeight (GpAdjustableArrowCap * , REAL *)
Referenced by AdjustableArrowCap::GetHeight().
GdipGetAdjustableArrowCapMiddleInset()
GpStatus WINGDIPAPI GdipGetAdjustableArrowCapMiddleInset (GpAdjustableArrowCap * , REAL *)
Referenced by AdjustableArrowCap::GetMiddleInset().
GdipGetAdjustableArrowCapWidth()
GpStatus WINGDIPAPI GdipGetAdjustableArrowCapWidth (GpAdjustableArrowCap * , REAL *)
Referenced by AdjustableArrowCap::GetWidth().
GdipGetAllPropertyItems()
GpStatus WINGDIPAPI GdipGetAllPropertyItems (GpImage * , UINT , UINT , PropertyItem *)
Referenced by Image::GetAllPropertyItems().
GdipGetBrushType()
GpStatus WINGDIPAPI GdipGetBrushType (GpBrush * , GpBrushType *)
Referenced by Brush::GetType().
GdipGetCellAscent()
GpStatus WINGDIPAPI GdipGetCellAscent (GDIPCONST GpFontFamily * , INT , UINT16 *)
Referenced by FontFamily::GetCellAscent().
GdipGetCellDescent()
GpStatus WINGDIPAPI GdipGetCellDescent (GDIPCONST GpFontFamily * , INT , UINT16 *)
Referenced by FontFamily::GetCellDescent().
GdipGetClip()
GpStatus WINGDIPAPI GdipGetClip (GpGraphics * , GpRegion *)
Referenced by Graphics::GetClip().
GdipGetClipBounds()
GpStatus WINGDIPAPI GdipGetClipBounds (GpGraphics * , GpRectF *)
Referenced by Graphics::GetClipBounds().
GdipGetClipBoundsI()
GpStatus WINGDIPAPI GdipGetClipBoundsI (GpGraphics * , GpRect *)
Referenced by Graphics::GetClipBounds().
GdipGetCompositingMode()
GpStatus WINGDIPAPI GdipGetCompositingMode (GpGraphics * , CompositingMode *)
Referenced by Graphics::GetCompositingMode().
GdipGetCompositingQuality()
GpStatus WINGDIPAPI GdipGetCompositingQuality (GpGraphics * , CompositingQuality *)
Referenced by Graphics::GetCompositingQuality().
GdipGetCustomLineCapBaseCap()
GpStatus WINGDIPAPI GdipGetCustomLineCapBaseCap (GpCustomLineCap * , GpLineCap *)
Referenced by CustomLineCap::GetBaseCap().
GdipGetCustomLineCapBaseInset()
GpStatus WINGDIPAPI GdipGetCustomLineCapBaseInset (GpCustomLineCap * , REAL *)
Referenced by CustomLineCap::GetBaseInset().
GdipGetCustomLineCapStrokeCaps()
GpStatus WINGDIPAPI GdipGetCustomLineCapStrokeCaps (GpCustomLineCap * , GpLineCap * , GpLineCap *)
Referenced by CustomLineCap::GetStrokeCaps().
GdipGetCustomLineCapStrokeJoin()
GpStatus WINGDIPAPI GdipGetCustomLineCapStrokeJoin (GpCustomLineCap * , GpLineJoin *)
Referenced by CustomLineCap::GetStrokeJoin().
GdipGetCustomLineCapType()
GpStatus WINGDIPAPI GdipGetCustomLineCapType (GpCustomLineCap * , CustomLineCapType *)
GdipGetCustomLineCapWidthScale()
GpStatus WINGDIPAPI GdipGetCustomLineCapWidthScale (GpCustomLineCap * , REAL *)
Referenced by CustomLineCap::GetWidthScale().
GdipGetDC()
GpStatus WINGDIPAPI GdipGetDC (GpGraphics * , HDC *)
Referenced by Graphics::GetHDC().
GdipGetDpiX()
GpStatus WINGDIPAPI GdipGetDpiX (GpGraphics * , REAL *)
Referenced by Graphics::GetDpiX().
GdipGetDpiY()
GpStatus WINGDIPAPI GdipGetDpiY (GpGraphics * , REAL *)
Referenced by Graphics::GetDpiY().
GdipGetEffectParameters()
GpStatus WINGDIPAPI GdipGetEffectParameters (CGpEffect * , UINT * , VOID *)
GdipGetEffectParameterSize()
GpStatus WINGDIPAPI GdipGetEffectParameterSize (CGpEffect * , UINT *)
GdipGetEmHeight()
GpStatus WINGDIPAPI GdipGetEmHeight (GDIPCONST GpFontFamily * , INT , UINT16 *)
Referenced by FontFamily::GetEmHeight().
GdipGetEncoderParameterList()
GpStatus WINGDIPAPI GdipGetEncoderParameterList (GpImage * , GDIPCONST CLSID * , UINT , EncoderParameters *)
Referenced by Image::GetEncoderParameterList().
GdipGetEncoderParameterListSize()
GpStatus WINGDIPAPI GdipGetEncoderParameterListSize (GpImage * , GDIPCONST CLSID * , UINT *)
Referenced by Image::GetEncoderParameterListSize().
GdipGetFamily()
GpStatus WINGDIPAPI GdipGetFamily (GpFont * , GpFontFamily **)
Referenced by Font::GetFamily().
GdipGetFamilyName()
GpStatus WINGDIPAPI GdipGetFamilyName (GDIPCONST GpFontFamily * , WCHAR [LF_FACESIZE], LANGID)
Referenced by FontFamily::GetFamilyName().
GdipGetFontCollectionFamilyCount()
GpStatus WINGDIPAPI GdipGetFontCollectionFamilyCount (GpFontCollection * , INT *)
Referenced by FontCollection::GetFamilyCount().
GdipGetFontCollectionFamilyList()
GpStatus WINGDIPAPI GdipGetFontCollectionFamilyList (GpFontCollection * , INT , GpFontFamily ** , INT *)
Referenced by FontCollection::GetFamilies().
GdipGetFontHeight()
GpStatus WINGDIPAPI GdipGetFontHeight (GDIPCONST GpFont * , GDIPCONST GpGraphics * , REAL *)
Referenced by Font::GetHeight().
GdipGetFontHeightGivenDPI()
GpStatus WINGDIPAPI GdipGetFontHeightGivenDPI (GDIPCONST GpFont * , REAL , REAL *)
Referenced by Font::GetHeight().
GdipGetFontSize()
GpStatus WINGDIPAPI GdipGetFontSize (GpFont * , REAL *)
Referenced by Font::GetSize().
GdipGetFontStyle()
GpStatus WINGDIPAPI GdipGetFontStyle (GpFont * , INT *)
Referenced by Font::GetStyle().
GdipGetFontUnit()
GpStatus WINGDIPAPI GdipGetFontUnit (GpFont * , Unit *)
Referenced by Font::GetUnit().
GdipGetGenericFontFamilyMonospace()
GpStatus WINGDIPAPI GdipGetGenericFontFamilyMonospace (GpFontFamily **)
Referenced by FontFamily::GenericMonospace().
GdipGetGenericFontFamilySansSerif()
GpStatus WINGDIPAPI GdipGetGenericFontFamilySansSerif (GpFontFamily **)
Referenced by FontFamily::GenericSansSerif().
GdipGetGenericFontFamilySerif()
GpStatus WINGDIPAPI GdipGetGenericFontFamilySerif (GpFontFamily **)
Referenced by FontFamily::GenericSerif().
GdipGetHatchBackgroundColor()
GpStatus WINGDIPAPI GdipGetHatchBackgroundColor (GpHatch * , ARGB *)
Referenced by HatchBrush::GetBackgroundColor().
GdipGetHatchForegroundColor()
GpStatus WINGDIPAPI GdipGetHatchForegroundColor (GpHatch * , ARGB *)
Referenced by HatchBrush::GetForegroundColor().
GdipGetHatchStyle()
GpStatus WINGDIPAPI GdipGetHatchStyle (GpHatch * , GpHatchStyle *)
Referenced by HatchBrush::GetHatchStyle().
GdipGetHemfFromMetafile()
GpStatus WINGDIPAPI GdipGetHemfFromMetafile (GpMetafile * , HENHMETAFILE *)
Referenced by Metafile::GetHENHMETAFILE().
GdipGetImageAttributesAdjustedPalette()
GpStatus WINGDIPAPI GdipGetImageAttributesAdjustedPalette (GpImageAttributes * , ColorPalette * , ColorAdjustType)
Referenced by ImageAttributes::GetAdjustedPalette().
GdipGetImageBounds()
GpStatus WINGDIPAPI GdipGetImageBounds (GpImage * , GpRectF * , GpUnit *)
Referenced by Image::GetBounds().
GdipGetImageDecoders()
GpStatus WINGDIPAPI GdipGetImageDecoders (UINT , UINT , ImageCodecInfo *)
Referenced by GetImageDecoders().
GdipGetImageDecodersSize()
GpStatus WINGDIPAPI GdipGetImageDecodersSize (UINT * , UINT *)
Referenced by GetImageDecodersSize().
GdipGetImageDimension()
GpStatus WINGDIPAPI GdipGetImageDimension (GpImage * , REAL * , REAL *)
Referenced by Image::GetPhysicalDimension().
GdipGetImageEncoders()
GpStatus WINGDIPAPI GdipGetImageEncoders (UINT , UINT , ImageCodecInfo *)
Referenced by GetImageEncoders().
GdipGetImageEncodersSize()
GpStatus WINGDIPAPI GdipGetImageEncodersSize (UINT * , UINT *)
Referenced by GetImageEncodersSize().
GdipGetImageFlags()
GpStatus WINGDIPAPI GdipGetImageFlags (GpImage * , UINT *)
Referenced by Image::GetFlags().
GdipGetImageGraphicsContext()
GpStatus WINGDIPAPI GdipGetImageGraphicsContext (GpImage * , GpGraphics **)
Referenced by Graphics::Graphics().
GdipGetImageHeight()
GpStatus WINGDIPAPI GdipGetImageHeight (GpImage * , UINT *)
Referenced by Image::GetHeight().
GdipGetImageHorizontalResolution()
GpStatus WINGDIPAPI GdipGetImageHorizontalResolution (GpImage * , REAL *)
Referenced by Image::GetHorizontalResolution().
GdipGetImageItemData()
GpStatus WINGDIPAPI GdipGetImageItemData (GpImage * , ImageItemData *)
Referenced by Image::GetItemData().
GdipGetImagePalette()
GpStatus WINGDIPAPI GdipGetImagePalette (GpImage * , ColorPalette * , INT)
Referenced by Image::GetPalette().
GdipGetImagePaletteSize()
GpStatus WINGDIPAPI GdipGetImagePaletteSize (GpImage * , INT *)
Referenced by Image::GetPaletteSize().
GdipGetImagePixelFormat()
GpStatus WINGDIPAPI GdipGetImagePixelFormat (GpImage * , PixelFormat *)
Referenced by Image::GetPixelFormat().
GdipGetImageRawFormat()
GpStatus WINGDIPAPI GdipGetImageRawFormat (GpImage * , GUID *)
Referenced by Image::GetRawFormat().
GdipGetImageThumbnail()
GpStatus WINGDIPAPI GdipGetImageThumbnail (GpImage * , UINT , UINT , GpImage ** , GetThumbnailImageAbort , VOID *)
Referenced by Image::GetThumbnailImage().
GdipGetImageType()
GpStatus WINGDIPAPI GdipGetImageType (GpImage * , ImageType *)
Referenced by Image::GetType().
GdipGetImageVerticalResolution()
GpStatus WINGDIPAPI GdipGetImageVerticalResolution (GpImage * , REAL *)
Referenced by Image::GetVerticalResolution().
GdipGetImageWidth()
GpStatus WINGDIPAPI GdipGetImageWidth (GpImage * , UINT *)
Referenced by Image::GetWidth().
GdipGetInterpolationMode()
GpStatus WINGDIPAPI GdipGetInterpolationMode (GpGraphics * , InterpolationMode *)
Referenced by Graphics::GetInterpolationMode().
GdipGetLineBlend()
GpStatus WINGDIPAPI GdipGetLineBlend (GpLineGradient * , REAL * , REAL * , INT)
Referenced by LinearGradientBrush::GetBlend().
GdipGetLineBlendCount()
GpStatus WINGDIPAPI GdipGetLineBlendCount (GpLineGradient * , INT *)
Referenced by LinearGradientBrush::GetBlendCount().
GdipGetLineColors()
GpStatus WINGDIPAPI GdipGetLineColors (GpLineGradient * , ARGB *)
Referenced by LinearGradientBrush::GetLinearColors().
GdipGetLineGammaCorrection()
GpStatus WINGDIPAPI GdipGetLineGammaCorrection (GpLineGradient * , BOOL *)
Referenced by LinearGradientBrush::GetGammaCorrection().
GdipGetLinePresetBlend()
GpStatus WINGDIPAPI GdipGetLinePresetBlend (GpLineGradient * , ARGB * , REAL * , INT)
Referenced by LinearGradientBrush::GetInterpolationColors().
GdipGetLinePresetBlendCount()
GpStatus WINGDIPAPI GdipGetLinePresetBlendCount (GpLineGradient * , INT *)
Referenced by LinearGradientBrush::GetInterpolationColorCount().
GdipGetLineRect()
GpStatus WINGDIPAPI GdipGetLineRect (GpLineGradient * , GpRectF *)
Referenced by LinearGradientBrush::GetRectangle().
GdipGetLineRectI()
GpStatus WINGDIPAPI GdipGetLineRectI (GpLineGradient * , GpRect *)
Referenced by LinearGradientBrush::GetRectangle().
GdipGetLineSpacing()
GpStatus WINGDIPAPI GdipGetLineSpacing (GDIPCONST GpFontFamily * , INT , UINT16 *)
Referenced by FontFamily::GetLineSpacing().
GdipGetLineTransform()
GpStatus WINGDIPAPI GdipGetLineTransform (GpLineGradient * , GpMatrix *)
Referenced by LinearGradientBrush::GetTransform().
GdipGetLineWrapMode()
GpStatus WINGDIPAPI GdipGetLineWrapMode (GpLineGradient * , GpWrapMode *)
Referenced by LinearGradientBrush::GetWrapMode().
GdipGetLogFontA()
GpStatus WINGDIPAPI GdipGetLogFontA (GpFont * , GpGraphics * , LOGFONTA *)
Referenced by Font::GetLogFontA().
GdipGetLogFontW()
GpStatus WINGDIPAPI GdipGetLogFontW (GpFont * , GpGraphics * , LOGFONTW *)
Referenced by Font::GetLogFontW().
GdipGetMatrixElements()
GpStatus WINGDIPAPI GdipGetMatrixElements (GDIPCONST GpMatrix * , REAL *)
Referenced by Matrix::GetElements(), Matrix::OffsetX(), and Matrix::OffsetY().
GdipGetMetafileDownLevelRasterizationLimit()
GpStatus WINGDIPAPI GdipGetMetafileDownLevelRasterizationLimit (GDIPCONST GpMetafile * , UINT *)
Referenced by Metafile::GetDownLevelRasterizationLimit().
GdipGetMetafileHeaderFromEmf()
GpStatus WINGDIPAPI GdipGetMetafileHeaderFromEmf (HENHMETAFILE , MetafileHeader *)
Referenced by Metafile::GetMetafileHeader().
GdipGetMetafileHeaderFromFile()
GpStatus WINGDIPAPI GdipGetMetafileHeaderFromFile (GDIPCONST WCHAR * , MetafileHeader *)
Referenced by Metafile::GetMetafileHeader().
GdipGetMetafileHeaderFromMetafile()
GpStatus WINGDIPAPI GdipGetMetafileHeaderFromMetafile (GpMetafile * , MetafileHeader *)
Referenced by Metafile::GetMetafileHeader().
GdipGetMetafileHeaderFromStream()
GpStatus WINGDIPAPI GdipGetMetafileHeaderFromStream (IStream * , MetafileHeader *)
Referenced by Metafile::GetMetafileHeader().
GdipGetNearestColor()
GpStatus WINGDIPAPI GdipGetNearestColor (GpGraphics * , ARGB *)
Referenced by Graphics::GetNearestColor().
GdipGetPageScale()
GpStatus WINGDIPAPI GdipGetPageScale (GpGraphics * , REAL *)
Referenced by Graphics::GetPageScale().
GdipGetPageUnit()
GpStatus WINGDIPAPI GdipGetPageUnit (GpGraphics * , GpUnit *)
Referenced by Graphics::GetPageUnit().
GdipGetPathData()
GpStatus WINGDIPAPI GdipGetPathData (GpPath * , GpPathData *)
Referenced by GraphicsPath::GetPathData().
GdipGetPathFillMode()
GpStatus WINGDIPAPI GdipGetPathFillMode (GpPath * , GpFillMode *)
Referenced by GraphicsPath::GetFillMode().
GdipGetPathGradientBlend()
GpStatus WINGDIPAPI GdipGetPathGradientBlend (GpPathGradient * , REAL * , REAL * , INT)
Referenced by PathGradientBrush::GetBlend().
GdipGetPathGradientBlendCount()
GpStatus WINGDIPAPI GdipGetPathGradientBlendCount (GpPathGradient * , INT *)
Referenced by PathGradientBrush::GetBlendCount().
GdipGetPathGradientCenterColor()
GpStatus WINGDIPAPI GdipGetPathGradientCenterColor (GpPathGradient * , ARGB *)
Referenced by PathGradientBrush::GetCenterColor().
GdipGetPathGradientCenterPoint()
GpStatus WINGDIPAPI GdipGetPathGradientCenterPoint (GpPathGradient * , GpPointF *)
Referenced by PathGradientBrush::GetCenterPoint().
GdipGetPathGradientCenterPointI()
GpStatus WINGDIPAPI GdipGetPathGradientCenterPointI (GpPathGradient * , GpPoint *)
Referenced by PathGradientBrush::GetCenterPoint().
GdipGetPathGradientFocusScales()
GpStatus WINGDIPAPI GdipGetPathGradientFocusScales (GpPathGradient * , REAL * , REAL *)
Referenced by PathGradientBrush::GetFocusScales().
GdipGetPathGradientGammaCorrection()
GpStatus WINGDIPAPI GdipGetPathGradientGammaCorrection (GpPathGradient * , BOOL *)
Referenced by PathGradientBrush::GetGammaCorrection().
GdipGetPathGradientPath()
GpStatus WINGDIPAPI GdipGetPathGradientPath (GpPathGradient * , GpPath *)
GdipGetPathGradientPointCount()
GpStatus WINGDIPAPI GdipGetPathGradientPointCount (GpPathGradient * , INT *)
Referenced by PathGradientBrush::GetPointCount().
GdipGetPathGradientPresetBlend()
GpStatus WINGDIPAPI GdipGetPathGradientPresetBlend (GpPathGradient * , ARGB * , REAL * , INT)
Referenced by PathGradientBrush::GetInterpolationColors().
GdipGetPathGradientPresetBlendCount()
GpStatus WINGDIPAPI GdipGetPathGradientPresetBlendCount (GpPathGradient * , INT *)
Referenced by PathGradientBrush::GetInterpolationColorCount().
GdipGetPathGradientRect()
GpStatus WINGDIPAPI GdipGetPathGradientRect (GpPathGradient * , GpRectF *)
Referenced by PathGradientBrush::GetRectangle().
GdipGetPathGradientRectI()
GpStatus WINGDIPAPI GdipGetPathGradientRectI (GpPathGradient * , GpRect *)
Referenced by PathGradientBrush::GetRectangle().
GdipGetPathGradientSurroundColorCount()
GpStatus WINGDIPAPI GdipGetPathGradientSurroundColorCount (GpPathGradient * , INT *)
Referenced by PathGradientBrush::GetSurroundColorCount().
GdipGetPathGradientSurroundColorsWithCount()
GpStatus WINGDIPAPI GdipGetPathGradientSurroundColorsWithCount (GpPathGradient * , ARGB * , INT *)
Referenced by PathGradientBrush::GetSurroundColors().
GdipGetPathGradientTransform()
GpStatus WINGDIPAPI GdipGetPathGradientTransform (GpPathGradient * , GpMatrix *)
Referenced by PathGradientBrush::GetTransform().
GdipGetPathGradientWrapMode()
GpStatus WINGDIPAPI GdipGetPathGradientWrapMode (GpPathGradient * , GpWrapMode *)
Referenced by PathGradientBrush::GetWrapMode().
GdipGetPathLastPoint()
GpStatus WINGDIPAPI GdipGetPathLastPoint (GpPath * , GpPointF *)
Referenced by GraphicsPath::GetLastPoint().
GdipGetPathPoints()
GpStatus WINGDIPAPI GdipGetPathPoints (GpPath * , GpPointF * , INT)
Referenced by GraphicsPath::GetPathPoints().
GdipGetPathPointsI()
GpStatus WINGDIPAPI GdipGetPathPointsI (GpPath * , GpPoint * , INT)
Referenced by GraphicsPath::GetPathPoints().
GdipGetPathTypes()
GpStatus WINGDIPAPI GdipGetPathTypes (GpPath * , BYTE * , INT)
Referenced by GraphicsPath::GetPathTypes().
GdipGetPathWorldBounds()
GpStatus WINGDIPAPI GdipGetPathWorldBounds (GpPath * , GpRectF * , GDIPCONST GpMatrix * , GDIPCONST GpPen *)
Referenced by GraphicsPath::GetBounds().
GdipGetPathWorldBoundsI()
GpStatus WINGDIPAPI GdipGetPathWorldBoundsI (GpPath * , GpRect * , GDIPCONST GpMatrix * , GDIPCONST GpPen *)
Referenced by GraphicsPath::GetBounds().
GdipGetPenBrushFill()
GpStatus WINGDIPAPI GdipGetPenBrushFill (GpPen * , GpBrush **)
GdipGetPenColor()
GpStatus WINGDIPAPI GdipGetPenColor (GpPen * , ARGB *)
Referenced by Pen::GetColor().
GdipGetPenCompoundArray()
GpStatus WINGDIPAPI GdipGetPenCompoundArray (GpPen * , REAL * , INT)
Referenced by Pen::GetCompoundArray().
GdipGetPenCompoundCount()
GpStatus WINGDIPAPI GdipGetPenCompoundCount (GpPen * , INT *)
Referenced by Pen::GetCompoundArrayCount().
GdipGetPenCustomEndCap()
GpStatus WINGDIPAPI GdipGetPenCustomEndCap (GpPen * , GpCustomLineCap **)
Referenced by Pen::GetCustomEndCap().
GdipGetPenCustomStartCap()
GpStatus WINGDIPAPI GdipGetPenCustomStartCap (GpPen * , GpCustomLineCap **)
Referenced by Pen::GetCustomStartCap().
GdipGetPenDashArray()
GpStatus WINGDIPAPI GdipGetPenDashArray (GpPen * , REAL * , INT)
Referenced by Pen::GetDashPattern().
GdipGetPenDashCap197819()
GpStatus WINGDIPAPI GdipGetPenDashCap197819 (GpPen * , GpDashCap *)
Referenced by Pen::GetDashCap().
GdipGetPenDashCount()
GpStatus WINGDIPAPI GdipGetPenDashCount (GpPen * , INT *)
Referenced by Pen::GetDashPatternCount().
GdipGetPenDashOffset()
GpStatus WINGDIPAPI GdipGetPenDashOffset (GpPen * , REAL *)
Referenced by Pen::GetDashOffset().
GdipGetPenDashStyle()
GpStatus WINGDIPAPI GdipGetPenDashStyle (GpPen * , GpDashStyle *)
Referenced by Pen::GetDashStyle().
GdipGetPenEndCap()
GpStatus WINGDIPAPI GdipGetPenEndCap (GpPen * , GpLineCap *)
Referenced by Pen::GetEndCap().
GdipGetPenFillType()
GpStatus WINGDIPAPI GdipGetPenFillType (GpPen * , GpPenType *)
Referenced by Pen::GetPenType().
GdipGetPenLineJoin()
GpStatus WINGDIPAPI GdipGetPenLineJoin (GpPen * , GpLineJoin *)
Referenced by Pen::GetLineJoin().
GdipGetPenMiterLimit()
GpStatus WINGDIPAPI GdipGetPenMiterLimit (GpPen * , REAL *)
Referenced by Pen::GetMiterLimit().
GdipGetPenMode()
GpStatus WINGDIPAPI GdipGetPenMode (GpPen * , GpPenAlignment *)
Referenced by Pen::GetAlignment().
GdipGetPenStartCap()
GpStatus WINGDIPAPI GdipGetPenStartCap (GpPen * , GpLineCap *)
Referenced by Pen::GetStartCap().
GdipGetPenTransform()
GpStatus WINGDIPAPI GdipGetPenTransform (GpPen * , GpMatrix *)
Referenced by Pen::GetTransform().
GdipGetPenUnit()
GpStatus WINGDIPAPI GdipGetPenUnit (GpPen * , GpUnit *)
GdipGetPenWidth()
GpStatus WINGDIPAPI GdipGetPenWidth (GpPen * , REAL *)
Referenced by Pen::GetWidth().
GdipGetPixelOffsetMode()
GpStatus WINGDIPAPI GdipGetPixelOffsetMode (GpGraphics * , PixelOffsetMode *)
Referenced by Graphics::GetPixelOffsetMode().
GdipGetPointCount()
GpStatus WINGDIPAPI GdipGetPointCount (GpPath * , INT *)
Referenced by GraphicsPath::GetPathData(), and GraphicsPath::GetPointCount().
GdipGetPropertyCount()
GpStatus WINGDIPAPI GdipGetPropertyCount (GpImage * , UINT *)
Referenced by Image::GetPropertyCount().
GdipGetPropertyIdList()
GpStatus WINGDIPAPI GdipGetPropertyIdList (GpImage * , UINT , PROPID *)
Referenced by Image::GetPropertyIdList().
GdipGetPropertyItem()
GpStatus WINGDIPAPI GdipGetPropertyItem (GpImage * , PROPID , UINT , PropertyItem *)
Referenced by Image::GetPropertyItem().
GdipGetPropertyItemSize()
GpStatus WINGDIPAPI GdipGetPropertyItemSize (GpImage * , PROPID , UINT *)
Referenced by Image::GetPropertyItemSize().
GdipGetPropertySize()
GpStatus WINGDIPAPI GdipGetPropertySize (GpImage * , UINT * , UINT *)
Referenced by Image::GetPropertySize().
GdipGetRegionBounds()
GpStatus WINGDIPAPI GdipGetRegionBounds (GpRegion * , GpGraphics * , GpRectF *)
Referenced by Region::GetBounds().
GdipGetRegionBoundsI()
GpStatus WINGDIPAPI GdipGetRegionBoundsI (GpRegion * , GpGraphics * , GpRect *)
Referenced by Region::GetBounds().
GdipGetRegionData()
GpStatus WINGDIPAPI GdipGetRegionData (GpRegion * , BYTE * , UINT , UINT *)
Referenced by Region::GetData().
GdipGetRegionDataSize()
GpStatus WINGDIPAPI GdipGetRegionDataSize (GpRegion * , UINT *)
Referenced by Region::GetDataSize().
GdipGetRegionHRgn()
GpStatus WINGDIPAPI GdipGetRegionHRgn (GpRegion * , GpGraphics * , HRGN *)
Referenced by Region::GetHRGN().
GdipGetRegionScans()
GpStatus WINGDIPAPI GdipGetRegionScans (GpRegion * , GpRectF * , INT * , GpMatrix *)
Referenced by Region::GetRegionScans().
GdipGetRegionScansCount()
GpStatus WINGDIPAPI GdipGetRegionScansCount (GpRegion * , UINT * , GpMatrix *)
Referenced by Region::GetRegionScansCount().
GdipGetRegionScansI()
GpStatus WINGDIPAPI GdipGetRegionScansI (GpRegion * , GpRect * , INT * , GpMatrix *)
Referenced by Region::GetRegionScans().
GdipGetRenderingOrigin()
GpStatus WINGDIPAPI GdipGetRenderingOrigin (GpGraphics * , INT * , INT *)
Referenced by Graphics::GetRenderingOrigin().
GdipGetSmoothingMode()
GpStatus WINGDIPAPI GdipGetSmoothingMode (GpGraphics * , SmoothingMode *)
Referenced by Graphics::GetSmoothingMode().
GdipGetSolidFillColor()
GpStatus WINGDIPAPI GdipGetSolidFillColor (GpSolidFill * , ARGB *)
Referenced by SolidBrush::GetColor().
GdipGetStringFormatAlign()
GpStatus WINGDIPAPI GdipGetStringFormatAlign (GDIPCONST GpStringFormat * , StringAlignment *)
Referenced by StringFormat::GetAlignment().
GdipGetStringFormatDigitSubstitution()
GpStatus WINGDIPAPI GdipGetStringFormatDigitSubstitution (GDIPCONST GpStringFormat * , LANGID * , StringDigitSubstitute *)
Referenced by StringFormat::GetDigitSubstitutionLanguage(), and StringFormat::GetDigitSubstitutionMethod().
GdipGetStringFormatFlags()
GpStatus WINGDIPAPI GdipGetStringFormatFlags (GDIPCONST GpStringFormat * , INT *)
Referenced by StringFormat::GetFormatFlags().
GdipGetStringFormatHotkeyPrefix()
GpStatus WINGDIPAPI GdipGetStringFormatHotkeyPrefix (GDIPCONST GpStringFormat * , INT *)
Referenced by StringFormat::GetHotkeyPrefix().
GdipGetStringFormatLineAlign()
GpStatus WINGDIPAPI GdipGetStringFormatLineAlign (GDIPCONST GpStringFormat * , StringAlignment *)
Referenced by StringFormat::GetLineAlignment().
GdipGetStringFormatMeasurableCharacterRangeCount()
GpStatus WINGDIPAPI GdipGetStringFormatMeasurableCharacterRangeCount (GDIPCONST GpStringFormat * , INT *)
Referenced by StringFormat::GetMeasurableCharacterRangeCount().
GdipGetStringFormatTabStopCount()
GpStatus WINGDIPAPI GdipGetStringFormatTabStopCount (GDIPCONST GpStringFormat * , INT *)
Referenced by StringFormat::GetTabStopCount().
GdipGetStringFormatTabStops()
GpStatus WINGDIPAPI GdipGetStringFormatTabStops (GDIPCONST GpStringFormat * , INT , REAL * , REAL *)
Referenced by StringFormat::GetTabStops().
GdipGetStringFormatTrimming()
GpStatus WINGDIPAPI GdipGetStringFormatTrimming (GDIPCONST GpStringFormat * , StringTrimming *)
Referenced by StringFormat::GetTrimming().
GdipGetTextContrast()
GpStatus WINGDIPAPI GdipGetTextContrast (GpGraphics * , UINT *)
Referenced by Graphics::GetTextContrast().
GdipGetTextRenderingHint()
GpStatus WINGDIPAPI GdipGetTextRenderingHint (GpGraphics * , TextRenderingHint *)
Referenced by Graphics::GetTextRenderingHint().
GdipGetTextureImage()
GpStatus WINGDIPAPI GdipGetTextureImage (GpTexture * , GpImage **)
GdipGetTextureTransform()
GpStatus WINGDIPAPI GdipGetTextureTransform (GpTexture * , GpMatrix *)
Referenced by TextureBrush::GetTransfrom().
GdipGetTextureWrapMode()
GpStatus WINGDIPAPI GdipGetTextureWrapMode (GpTexture * , GpWrapMode *)
Referenced by TextureBrush::GetWrapMode().
GdipGetVisibleClipBounds()
GpStatus WINGDIPAPI GdipGetVisibleClipBounds (GpGraphics * , GpRectF *)
Referenced by Graphics::GetVisibleClipBounds().
GdipGetVisibleClipBoundsI()
GpStatus WINGDIPAPI GdipGetVisibleClipBoundsI (GpGraphics * , GpRect *)
Referenced by Graphics::GetVisibleClipBounds().
GdipGetWorldTransform()
GpStatus WINGDIPAPI GdipGetWorldTransform (GpGraphics * , GpMatrix *)
Referenced by Graphics::GetTransform().
GdipGraphicsClear()
GpStatus WINGDIPAPI GdipGraphicsClear (GpGraphics * , ARGB)
Referenced by Graphics::Clear().
GdipGraphicsSetAbort()
GpStatus WINGDIPAPI GdipGraphicsSetAbort (GpGraphics * , GdiplusAbort *)
GdipImageForceValidation()
GpStatus WINGDIPAPI GdipImageForceValidation (GpImage *)
GdipImageGetFrameCount()
GpStatus WINGDIPAPI GdipImageGetFrameCount (GpImage * , GDIPCONST GUID * , UINT *)
Referenced by Image::GetFrameCount().
GdipImageGetFrameDimensionsCount()
GpStatus WINGDIPAPI GdipImageGetFrameDimensionsCount (GpImage * , UINT *)
Referenced by Image::GetFrameDimensionsCount().
GdipImageGetFrameDimensionsList()
GpStatus WINGDIPAPI GdipImageGetFrameDimensionsList (GpImage * , GUID * , UINT)
Referenced by Image::GetFrameDimensionsList().
GdipImageRotateFlip()
GpStatus WINGDIPAPI GdipImageRotateFlip (GpImage * , RotateFlipType)
Referenced by Image::RotateFlip().
GdipImageSelectActiveFrame()
GpStatus WINGDIPAPI GdipImageSelectActiveFrame (GpImage * , GDIPCONST GUID * , UINT)
Referenced by Image::SelectActiveFrame().
GdipImageSetAbort()
GpStatus WINGDIPAPI GdipImageSetAbort (GpImage * , GdiplusAbort *)
Referenced by Image::SetAbort().
GdipInitializePalette()
GpStatus WINGDIPAPI GdipInitializePalette (ColorPalette * , PaletteType , INT , BOOL , GpBitmap *)
Referenced by Bitmap::InitializePalette().
GdipInvertMatrix()
GpStatus WINGDIPAPI GdipInvertMatrix (GpMatrix *)
Referenced by Matrix::Invert().
GdipIsClipEmpty()
GpStatus WINGDIPAPI GdipIsClipEmpty (GpGraphics * , BOOL *)
Referenced by Graphics::IsClipEmpty().
GdipIsEmptyRegion()
GpStatus WINGDIPAPI GdipIsEmptyRegion (GpRegion * , GpGraphics * , BOOL *)
Referenced by Region::IsEmpty().
GdipIsEqualRegion()
GpStatus WINGDIPAPI GdipIsEqualRegion (GpRegion * , GpRegion * , GpGraphics * , BOOL *)
Referenced by Region::Equals().
GdipIsInfiniteRegion()
GpStatus WINGDIPAPI GdipIsInfiniteRegion (GpRegion * , GpGraphics * , BOOL *)
Referenced by Region::IsInfinite().
GdipIsMatrixEqual()
GpStatus WINGDIPAPI GdipIsMatrixEqual (GDIPCONST GpMatrix * , GDIPCONST GpMatrix * , BOOL *)
Referenced by Matrix::Equals().
GdipIsMatrixIdentity()
GpStatus WINGDIPAPI GdipIsMatrixIdentity (GDIPCONST GpMatrix * , BOOL *)
Referenced by Matrix::IsIdentity().
GdipIsMatrixInvertible()
GpStatus WINGDIPAPI GdipIsMatrixInvertible (GDIPCONST GpMatrix * , BOOL *)
Referenced by Matrix::IsInvertible().
GdipIsOutlineVisiblePathPoint()
GpStatus WINGDIPAPI GdipIsOutlineVisiblePathPoint (GpPath * , REAL , REAL , GpPen * , GpGraphics * , BOOL *)
Referenced by GraphicsPath::IsOutlineVisible().
GdipIsOutlineVisiblePathPointI()
GpStatus WINGDIPAPI GdipIsOutlineVisiblePathPointI (GpPath * , INT , INT , GpPen * , GpGraphics * , BOOL *)
Referenced by GraphicsPath::IsOutlineVisible().
GdipIsStyleAvailable()
GpStatus WINGDIPAPI GdipIsStyleAvailable (GDIPCONST GpFontFamily * , INT , BOOL *)
Referenced by FontFamily::IsStyleAvailable().
GdipIsVisibleClipEmpty()
GpStatus WINGDIPAPI GdipIsVisibleClipEmpty (GpGraphics * , BOOL *)
Referenced by Graphics::IsVisibleClipEmpty().
GdipIsVisiblePathPoint()
GpStatus WINGDIPAPI GdipIsVisiblePathPoint (GpPath * , REAL , REAL , GpGraphics * , BOOL *)
Referenced by GraphicsPath::IsVisible().
GdipIsVisiblePathPointI()
GpStatus WINGDIPAPI GdipIsVisiblePathPointI (GpPath * , INT , INT , GpGraphics * , BOOL *)
Referenced by GraphicsPath::IsVisible().
GdipIsVisiblePoint()
GpStatus WINGDIPAPI GdipIsVisiblePoint (GpGraphics * , REAL , REAL , BOOL *)
Referenced by Graphics::IsVisible().
GdipIsVisiblePointI()
GpStatus WINGDIPAPI GdipIsVisiblePointI (GpGraphics * , INT , INT , BOOL *)
Referenced by Graphics::IsVisible().
GdipIsVisibleRect()
GpStatus WINGDIPAPI GdipIsVisibleRect (GpGraphics * , REAL , REAL , REAL , REAL , BOOL *)
Referenced by Graphics::IsVisible().
GdipIsVisibleRectI()
GpStatus WINGDIPAPI GdipIsVisibleRectI (GpGraphics * , INT , INT , INT , INT , BOOL *)
Referenced by Graphics::IsVisible().
GdipIsVisibleRegionPoint()
GpStatus WINGDIPAPI GdipIsVisibleRegionPoint (GpRegion * , REAL , REAL , GpGraphics * , BOOL *)
Referenced by Region::IsVisible().
GdipIsVisibleRegionPointI()
GpStatus WINGDIPAPI GdipIsVisibleRegionPointI (GpRegion * , INT , INT , GpGraphics * , BOOL *)
Referenced by Region::IsVisible().
GdipIsVisibleRegionRect()
GpStatus WINGDIPAPI GdipIsVisibleRegionRect (GpRegion * , REAL , REAL , REAL , REAL , GpGraphics * , BOOL *)
Referenced by Region::IsVisible().
GdipIsVisibleRegionRectI()
GpStatus WINGDIPAPI GdipIsVisibleRegionRectI (GpRegion * , INT , INT , INT , INT , GpGraphics * , BOOL *)
Referenced by Region::IsVisible().
GdipLoadImageFromFile()
GpStatus WINGDIPAPI GdipLoadImageFromFile (GDIPCONST WCHAR * , GpImage **)
Referenced by Image::Image().
GdipLoadImageFromFileICM()
GpStatus WINGDIPAPI GdipLoadImageFromFileICM (GDIPCONST WCHAR * , GpImage **)
Referenced by Image::Image().
GdipLoadImageFromStream()
GpStatus WINGDIPAPI GdipLoadImageFromStream (IStream * , GpImage **)
Referenced by Image::Image().
GdipLoadImageFromStreamICM()
GpStatus WINGDIPAPI GdipLoadImageFromStreamICM (IStream * , GpImage **)
Referenced by Image::Image().
GdipMeasureDriverString()
GpStatus WINGDIPAPI GdipMeasureDriverString (GpGraphics * , GDIPCONST UINT16 * , INT , GDIPCONST GpFont * , GDIPCONST PointF * , INT , GDIPCONST GpMatrix * , RectF *)
Referenced by Graphics::MeasureDriverString().
GdipMeasureString()
GpStatus WINGDIPAPI GdipMeasureString (GpGraphics * , GDIPCONST WCHAR * , INT , GDIPCONST GpFont * , GDIPCONST RectF * , GDIPCONST GpStringFormat * , RectF * , INT * , INT *)
Referenced by Graphics::MeasureString().
GdipMultiplyLineTransform()
GpStatus WINGDIPAPI GdipMultiplyLineTransform (GpLineGradient * , GDIPCONST GpMatrix * , GpMatrixOrder)
Referenced by LinearGradientBrush::MultiplyTransform().
GdipMultiplyMatrix()
GpStatus WINGDIPAPI GdipMultiplyMatrix (GpMatrix * , GpMatrix * , GpMatrixOrder)
Referenced by Matrix::Multiply().
GdipMultiplyPathGradientTransform()
GpStatus WINGDIPAPI GdipMultiplyPathGradientTransform (GpPathGradient * , GDIPCONST GpMatrix * , GpMatrixOrder)
Referenced by PathGradientBrush::MultiplyTransform().
GdipMultiplyPenTransform()
GpStatus WINGDIPAPI GdipMultiplyPenTransform (GpPen * , GDIPCONST GpMatrix * , GpMatrixOrder)
Referenced by Pen::MultiplyTransform().
GdipMultiplyTextureTransform()
GpStatus WINGDIPAPI GdipMultiplyTextureTransform (GpTexture * , GDIPCONST GpMatrix * , GpMatrixOrder)
Referenced by TextureBrush::MultiplyTransform().
GdipMultiplyWorldTransform()
GpStatus WINGDIPAPI GdipMultiplyWorldTransform (GpGraphics * , GDIPCONST GpMatrix * , GpMatrixOrder)
Referenced by Graphics::MultiplyTransform().
GdipNewInstalledFontCollection()
GpStatus WINGDIPAPI GdipNewInstalledFontCollection (GpFontCollection **)
Referenced by InstalledFontCollection::InstalledFontCollection().
GdipNewPrivateFontCollection()
GpStatus WINGDIPAPI GdipNewPrivateFontCollection (GpFontCollection **)
Referenced by PrivateFontCollection::PrivateFontCollection().
GdipPathIterCopyData()
GpStatus WINGDIPAPI GdipPathIterCopyData (GpPathIterator * , INT * , GpPointF * , BYTE * , INT , INT)
Referenced by GraphicsPathIterator::CopyData().
GdipPathIterEnumerate()
GpStatus WINGDIPAPI GdipPathIterEnumerate (GpPathIterator * , INT * , GpPointF * , BYTE * , INT)
Referenced by GraphicsPathIterator::Enumerate().
GdipPathIterGetCount()
GpStatus WINGDIPAPI GdipPathIterGetCount (GpPathIterator * , INT *)
Referenced by GraphicsPathIterator::GetCount().
GdipPathIterGetSubpathCount()
GpStatus WINGDIPAPI GdipPathIterGetSubpathCount (GpPathIterator * , INT *)
Referenced by GraphicsPathIterator::GetSubpathCount().
GdipPathIterHasCurve()
GpStatus WINGDIPAPI GdipPathIterHasCurve (GpPathIterator * , BOOL *)
Referenced by GraphicsPathIterator::HasCurve().
GdipPathIterIsValid()
GpStatus WINGDIPAPI GdipPathIterIsValid (GpPathIterator * , BOOL *)
GdipPathIterNextMarker()
GpStatus WINGDIPAPI GdipPathIterNextMarker (GpPathIterator * , INT * , INT * , INT *)
Referenced by GraphicsPathIterator::NextMarker().
GdipPathIterNextMarkerPath()
GpStatus WINGDIPAPI GdipPathIterNextMarkerPath (GpPathIterator * , INT * , GpPath *)
Referenced by GraphicsPathIterator::NextMarker().
GdipPathIterNextPathType()
GpStatus WINGDIPAPI GdipPathIterNextPathType (GpPathIterator * , INT * , BYTE * , INT * , INT *)
Referenced by GraphicsPathIterator::NextPathType().
GdipPathIterNextSubpath()
GpStatus WINGDIPAPI GdipPathIterNextSubpath (GpPathIterator * , INT * , INT * , INT * , BOOL *)
Referenced by GraphicsPathIterator::NextSubpath().
GdipPathIterNextSubpathPath()
GpStatus WINGDIPAPI GdipPathIterNextSubpathPath (GpPathIterator * , INT * , GpPath * , BOOL *)
Referenced by GraphicsPathIterator::NextSubpath().
GdipPathIterRewind()
GpStatus WINGDIPAPI GdipPathIterRewind (GpPathIterator *)
Referenced by GraphicsPathIterator::Rewind().
GdipPlayMetafileRecord()
GpStatus WINGDIPAPI GdipPlayMetafileRecord (GDIPCONST GpMetafile * , EmfPlusRecordType , UINT , UINT , GDIPCONST BYTE *)
Referenced by Metafile::PlayRecord().
GdipPrivateAddFontFile()
GpStatus WINGDIPAPI GdipPrivateAddFontFile (GpFontCollection * , GDIPCONST WCHAR *)
Referenced by PrivateFontCollection::AddFontFile().
GdipPrivateAddMemoryFont()
GpStatus WINGDIPAPI GdipPrivateAddMemoryFont (GpFontCollection * , GDIPCONST void * , INT)
Referenced by PrivateFontCollection::AddMemoryFont().
GdipRecordMetafile()
GpStatus WINGDIPAPI GdipRecordMetafile (HDC , EmfType , GDIPCONST GpRectF * , MetafileFrameUnit , GDIPCONST WCHAR * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipRecordMetafileFileName()
GpStatus WINGDIPAPI GdipRecordMetafileFileName (GDIPCONST WCHAR * , HDC , EmfType , GDIPCONST GpRectF * , MetafileFrameUnit , GDIPCONST WCHAR * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipRecordMetafileFileNameI()
GpStatus WINGDIPAPI GdipRecordMetafileFileNameI (GDIPCONST WCHAR * , HDC , EmfType , GDIPCONST GpRect * , MetafileFrameUnit , GDIPCONST WCHAR * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipRecordMetafileI()
GpStatus WINGDIPAPI GdipRecordMetafileI (HDC , EmfType , GDIPCONST GpRect * , MetafileFrameUnit , GDIPCONST WCHAR * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipRecordMetafileStream()
GpStatus WINGDIPAPI GdipRecordMetafileStream (IStream * , HDC , EmfType , GDIPCONST GpRectF * , MetafileFrameUnit , GDIPCONST WCHAR * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipRecordMetafileStreamI()
GpStatus WINGDIPAPI GdipRecordMetafileStreamI (IStream * , HDC , EmfType , GDIPCONST GpRect * , MetafileFrameUnit , GDIPCONST WCHAR * , GpMetafile **)
Referenced by Metafile::Metafile().
GdipReleaseDC()
GpStatus WINGDIPAPI GdipReleaseDC (GpGraphics * , HDC)
Referenced by Graphics::ReleaseHDC().
GdipRemovePropertyItem()
GpStatus WINGDIPAPI GdipRemovePropertyItem (GpImage * , PROPID)
Referenced by Image::RemovePropertyItem().
GdipResetClip()
GpStatus WINGDIPAPI GdipResetClip (GpGraphics *)
Referenced by Graphics::ResetClip().
GdipResetImageAttributes()
GpStatus WINGDIPAPI GdipResetImageAttributes (GpImageAttributes * , ColorAdjustType)
Referenced by ImageAttributes::Reset().
GdipResetLineTransform()
GpStatus WINGDIPAPI GdipResetLineTransform (GpLineGradient *)
Referenced by LinearGradientBrush::ResetTransform().
GdipResetPageTransform()
GpStatus WINGDIPAPI GdipResetPageTransform (GpGraphics *)
GdipResetPath()
GpStatus WINGDIPAPI GdipResetPath (GpPath *)
Referenced by GraphicsPath::Reset().
GdipResetPathGradientTransform()
GpStatus WINGDIPAPI GdipResetPathGradientTransform (GpPathGradient *)
Referenced by PathGradientBrush::ResetTransform().
GdipResetPenTransform()
GpStatus WINGDIPAPI GdipResetPenTransform (GpPen *)
Referenced by Pen::ResetTransform().
GdipResetTextureTransform()
GpStatus WINGDIPAPI GdipResetTextureTransform (GpTexture *)
Referenced by TextureBrush::ResetTransform().
GdipResetWorldTransform()
GpStatus WINGDIPAPI GdipResetWorldTransform (GpGraphics *)
Referenced by Graphics::ResetTransform().
GdipRestoreGraphics()
GpStatus WINGDIPAPI GdipRestoreGraphics (GpGraphics * , GraphicsState)
Referenced by Graphics::Restore().
GdipReversePath()
GpStatus WINGDIPAPI GdipReversePath (GpPath *)
Referenced by GraphicsPath::Reverse().
GdipRotateLineTransform()
GpStatus WINGDIPAPI GdipRotateLineTransform (GpLineGradient * , REAL , GpMatrixOrder)
Referenced by LinearGradientBrush::RotateTranform().
GdipRotateMatrix()
GpStatus WINGDIPAPI GdipRotateMatrix (GpMatrix * , REAL , GpMatrixOrder)
Referenced by Matrix::Rotate().
GdipRotatePathGradientTransform()
GpStatus WINGDIPAPI GdipRotatePathGradientTransform (GpPathGradient * , REAL , GpMatrixOrder)
Referenced by PathGradientBrush::RotateTransform().
GdipRotatePenTransform()
GpStatus WINGDIPAPI GdipRotatePenTransform (GpPen * , REAL , GpMatrixOrder)
Referenced by Pen::RotateTransform().
GdipRotateTextureTransform()
GpStatus WINGDIPAPI GdipRotateTextureTransform (GpTexture * , REAL , GpMatrixOrder)
Referenced by TextureBrush::RotateTransform().
GdipRotateWorldTransform()
GpStatus WINGDIPAPI GdipRotateWorldTransform (GpGraphics * , REAL , GpMatrixOrder)
Referenced by Graphics::RotateTransform().
GdipSaveAdd()
GpStatus WINGDIPAPI GdipSaveAdd (GpImage * , GDIPCONST EncoderParameters *)
Referenced by Image::SaveAdd().
GdipSaveAddImage()
GpStatus WINGDIPAPI GdipSaveAddImage (GpImage * , GpImage * , GDIPCONST EncoderParameters *)
Referenced by Image::SaveAdd().
GdipSaveGraphics()
GpStatus WINGDIPAPI GdipSaveGraphics (GpGraphics * , GraphicsState *)
Referenced by Graphics::Save().
GdipSaveImageToFile()
GpStatus WINGDIPAPI GdipSaveImageToFile (GpImage * , GDIPCONST WCHAR * , GDIPCONST CLSID * , GDIPCONST EncoderParameters *)
Referenced by Image::Save().
GdipSaveImageToStream()
GpStatus WINGDIPAPI GdipSaveImageToStream (GpImage * , IStream * , GDIPCONST CLSID * , GDIPCONST EncoderParameters *)
Referenced by Image::Save().
GdipScaleLineTransform()
GpStatus WINGDIPAPI GdipScaleLineTransform (GpLineGradient * , REAL , REAL , GpMatrixOrder)
Referenced by LinearGradientBrush::ScaleTransform().
GdipScaleMatrix()
GpStatus WINGDIPAPI GdipScaleMatrix (GpMatrix * , REAL , REAL , GpMatrixOrder)
Referenced by Matrix::Scale().
GdipScalePathGradientTransform()
GpStatus WINGDIPAPI GdipScalePathGradientTransform (GpPathGradient * , REAL , REAL , GpMatrixOrder)
Referenced by PathGradientBrush::ScaleTransform().
GdipScalePenTransform()
GpStatus WINGDIPAPI GdipScalePenTransform (GpPen * , REAL , REAL , GpMatrixOrder)
Referenced by Pen::ScaleTransform().
GdipScaleTextureTransform()
GpStatus WINGDIPAPI GdipScaleTextureTransform (GpTexture * , REAL , REAL , GpMatrixOrder)
Referenced by TextureBrush::ScaleTransform().
GdipScaleWorldTransform()
GpStatus WINGDIPAPI GdipScaleWorldTransform (GpGraphics * , REAL , REAL , GpMatrixOrder)
Referenced by Graphics::ScaleTransform().
GdipSetAdjustableArrowCapFillState()
GpStatus WINGDIPAPI GdipSetAdjustableArrowCapFillState (GpAdjustableArrowCap * , BOOL)
Referenced by AdjustableArrowCap::SetFillState().
GdipSetAdjustableArrowCapHeight()
GpStatus WINGDIPAPI GdipSetAdjustableArrowCapHeight (GpAdjustableArrowCap * , REAL)
Referenced by AdjustableArrowCap::SetHeight().
GdipSetAdjustableArrowCapMiddleInset()
GpStatus WINGDIPAPI GdipSetAdjustableArrowCapMiddleInset (GpAdjustableArrowCap * , REAL)
Referenced by AdjustableArrowCap::SetMiddleInset().
GdipSetAdjustableArrowCapWidth()
GpStatus WINGDIPAPI GdipSetAdjustableArrowCapWidth (GpAdjustableArrowCap * , REAL)
Referenced by AdjustableArrowCap::SetWidth().
GdipSetClipGraphics()
GpStatus WINGDIPAPI GdipSetClipGraphics (GpGraphics * , GpGraphics * , CombineMode)
Referenced by Graphics::SetClip().
GdipSetClipHrgn()
GpStatus WINGDIPAPI GdipSetClipHrgn (GpGraphics * , HRGN , CombineMode)
Referenced by Graphics::SetClip().
GdipSetClipPath()
GpStatus WINGDIPAPI GdipSetClipPath (GpGraphics * , GpPath * , CombineMode)
Referenced by Graphics::SetClip().
GdipSetClipRect()
GpStatus WINGDIPAPI GdipSetClipRect (GpGraphics * , REAL , REAL , REAL , REAL , CombineMode)
Referenced by Graphics::ExcludeClip(), Graphics::IntersectClip(), and Graphics::SetClip().
GdipSetClipRectI()
GpStatus WINGDIPAPI GdipSetClipRectI (GpGraphics * , INT , INT , INT , INT , CombineMode)
Referenced by Graphics::ExcludeClip(), Graphics::IntersectClip(), and Graphics::SetClip().
GdipSetClipRegion()
GpStatus WINGDIPAPI GdipSetClipRegion (GpGraphics * , GpRegion * , CombineMode)
Referenced by Graphics::ExcludeClip(), Graphics::IntersectClip(), and Graphics::SetClip().
GdipSetCompositingMode()
GpStatus WINGDIPAPI GdipSetCompositingMode (GpGraphics * , CompositingMode)
Referenced by Graphics::SetCompositingMode().
GdipSetCompositingQuality()
GpStatus WINGDIPAPI GdipSetCompositingQuality (GpGraphics * , CompositingQuality)
Referenced by Graphics::SetCompositingQuality().
GdipSetCustomLineCapBaseCap()
GpStatus WINGDIPAPI GdipSetCustomLineCapBaseCap (GpCustomLineCap * , GpLineCap)
Referenced by CustomLineCap::SetBaseCap().
GdipSetCustomLineCapBaseInset()
GpStatus WINGDIPAPI GdipSetCustomLineCapBaseInset (GpCustomLineCap * , REAL)
Referenced by CustomLineCap::SetBaseInset().
GdipSetCustomLineCapStrokeCaps()
GpStatus WINGDIPAPI GdipSetCustomLineCapStrokeCaps (GpCustomLineCap * , GpLineCap , GpLineCap)
Referenced by CustomLineCap::SetStrokeCap(), and CustomLineCap::SetStrokeCaps().
GdipSetCustomLineCapStrokeJoin()
GpStatus WINGDIPAPI GdipSetCustomLineCapStrokeJoin (GpCustomLineCap * , GpLineJoin)
Referenced by CustomLineCap::SetStrokeJoin().
GdipSetCustomLineCapWidthScale()
GpStatus WINGDIPAPI GdipSetCustomLineCapWidthScale (GpCustomLineCap * , REAL)
Referenced by CustomLineCap::SetWidthScale().
GdipSetEffectParameters()
GpStatus WINGDIPAPI GdipSetEffectParameters (CGpEffect * , GDIPCONST VOID * , UINT)
GdipSetEmpty()
GpStatus WINGDIPAPI GdipSetEmpty (GpRegion *)
Referenced by Region::MakeEmpty().
GdipSetImageAttributesCachedBackground()
GpStatus WINGDIPAPI GdipSetImageAttributesCachedBackground (GpImageAttributes * , BOOL)
GdipSetImageAttributesColorKeys()
GpStatus WINGDIPAPI GdipSetImageAttributesColorKeys (GpImageAttributes * , ColorAdjustType , BOOL , ARGB , ARGB)
Referenced by ImageAttributes::ClearColorKey(), and ImageAttributes::SetColorKey().
GdipSetImageAttributesColorMatrix()
GpStatus WINGDIPAPI GdipSetImageAttributesColorMatrix (GpImageAttributes * , ColorAdjustType , BOOL , GDIPCONST ColorMatrix * , GDIPCONST ColorMatrix * , ColorMatrixFlags)
Referenced by ImageAttributes::ClearColorMatrices(), ImageAttributes::ClearColorMatrix(), ImageAttributes::SetColorMatrices(), and ImageAttributes::SetColorMatrix().
GdipSetImageAttributesGamma()
GpStatus WINGDIPAPI GdipSetImageAttributesGamma (GpImageAttributes * , ColorAdjustType , BOOL , REAL)
Referenced by ImageAttributes::ClearGamma(), and ImageAttributes::SetGamma().
GdipSetImageAttributesICMMode()
GpStatus WINGDIPAPI GdipSetImageAttributesICMMode (GpImageAttributes * , BOOL)
GdipSetImageAttributesNoOp()
GpStatus WINGDIPAPI GdipSetImageAttributesNoOp (GpImageAttributes * , ColorAdjustType , BOOL)
Referenced by ImageAttributes::ClearNoOp(), and ImageAttributes::SetNoOp().
GdipSetImageAttributesOutputChannel()
GpStatus WINGDIPAPI GdipSetImageAttributesOutputChannel (GpImageAttributes * , ColorAdjustType , BOOL , ColorChannelFlags)
Referenced by ImageAttributes::ClearOutputChannel(), and ImageAttributes::SetOutputChannel().
GdipSetImageAttributesOutputChannelColorProfile()
GpStatus WINGDIPAPI GdipSetImageAttributesOutputChannelColorProfile (GpImageAttributes * , ColorAdjustType , BOOL , GDIPCONST WCHAR *)
Referenced by ImageAttributes::ClearOutputChannelColorProfile(), and ImageAttributes::SetOutputChannelColorProfile().
GdipSetImageAttributesRemapTable()
GpStatus WINGDIPAPI GdipSetImageAttributesRemapTable (GpImageAttributes * , ColorAdjustType , BOOL , UINT , GDIPCONST ColorMap *)
Referenced by ImageAttributes::ClearBrushRemapTable(), ImageAttributes::ClearRemapTable(), ImageAttributes::SetBrushRemapTable(), and ImageAttributes::SetRemapTable().
GdipSetImageAttributesThreshold()
GpStatus WINGDIPAPI GdipSetImageAttributesThreshold (GpImageAttributes * , ColorAdjustType , BOOL , REAL)
Referenced by ImageAttributes::ClearThreshold(), and ImageAttributes::SetThreshold().
GdipSetImageAttributesToIdentity()
GpStatus WINGDIPAPI GdipSetImageAttributesToIdentity (GpImageAttributes * , ColorAdjustType)
Referenced by ImageAttributes::SetToIdentity().
GdipSetImageAttributesWrapMode()
GpStatus WINGDIPAPI GdipSetImageAttributesWrapMode (GpImageAttributes * , WrapMode , ARGB , BOOL)
Referenced by ImageAttributes::SetWrapMode().
GdipSetImagePalette()
GpStatus WINGDIPAPI GdipSetImagePalette (GpImage * , GDIPCONST ColorPalette *)
Referenced by Image::SetPalette().
GdipSetInfinite()
GpStatus WINGDIPAPI GdipSetInfinite (GpRegion *)
Referenced by Region::MakeInfinite().
GdipSetInterpolationMode()
GpStatus WINGDIPAPI GdipSetInterpolationMode (GpGraphics * , InterpolationMode)
Referenced by Graphics::SetInterpolationMode().
GdipSetLineBlend()
GpStatus WINGDIPAPI GdipSetLineBlend (GpLineGradient * , GDIPCONST REAL * , GDIPCONST REAL * , INT)
Referenced by LinearGradientBrush::SetBlend().
GdipSetLineColors()
GpStatus WINGDIPAPI GdipSetLineColors (GpLineGradient * , ARGB , ARGB)
Referenced by LinearGradientBrush::SetLinearColors().
GdipSetLineGammaCorrection()
GpStatus WINGDIPAPI GdipSetLineGammaCorrection (GpLineGradient * , BOOL)
Referenced by LinearGradientBrush::SetGammaCorrection().
GdipSetLineLinearBlend()
GpStatus WINGDIPAPI GdipSetLineLinearBlend (GpLineGradient * , REAL , REAL)
Referenced by LinearGradientBrush::SetBlendTriangularShape().
GdipSetLinePresetBlend()
GpStatus WINGDIPAPI GdipSetLinePresetBlend (GpLineGradient * , GDIPCONST ARGB * , GDIPCONST REAL * , INT)
Referenced by LinearGradientBrush::SetInterpolationColors().
GdipSetLineSigmaBlend()
GpStatus WINGDIPAPI GdipSetLineSigmaBlend (GpLineGradient * , REAL , REAL)
Referenced by LinearGradientBrush::SetBlendBellShape().
GdipSetLineTransform()
GpStatus WINGDIPAPI GdipSetLineTransform (GpLineGradient * , GDIPCONST GpMatrix *)
Referenced by LinearGradientBrush::SetTransform().
GdipSetLineWrapMode()
GpStatus WINGDIPAPI GdipSetLineWrapMode (GpLineGradient * , GpWrapMode)
Referenced by LinearGradientBrush::SetWrapMode().
GdipSetMatrixElements()
GpStatus WINGDIPAPI GdipSetMatrixElements (GpMatrix * , REAL , REAL , REAL , REAL , REAL , REAL)
Referenced by Matrix::Reset(), and Matrix::SetElements().
GdipSetMetafileDownLevelRasterizationLimit()
GpStatus WINGDIPAPI GdipSetMetafileDownLevelRasterizationLimit (GpMetafile * , UINT)
Referenced by Metafile::SetDownLevelRasterizationLimit().
GdipSetPageScale()
GpStatus WINGDIPAPI GdipSetPageScale (GpGraphics * , REAL)
Referenced by Graphics::SetPageScale().
GdipSetPageUnit()
GpStatus WINGDIPAPI GdipSetPageUnit (GpGraphics * , GpUnit)
Referenced by Graphics::SetPageUnit().
GdipSetPathFillMode()
GpStatus WINGDIPAPI GdipSetPathFillMode (GpPath * , GpFillMode)
Referenced by GraphicsPath::SetFillMode().
GdipSetPathGradientBlend()
GpStatus WINGDIPAPI GdipSetPathGradientBlend (GpPathGradient * , GDIPCONST REAL * , GDIPCONST REAL * , INT)
Referenced by PathGradientBrush::SetBlend().
GdipSetPathGradientCenterColor()
GpStatus WINGDIPAPI GdipSetPathGradientCenterColor (GpPathGradient * , ARGB)
Referenced by PathGradientBrush::SetCenterColor().
GdipSetPathGradientCenterPoint()
GpStatus WINGDIPAPI GdipSetPathGradientCenterPoint (GpPathGradient * , GDIPCONST GpPointF *)
Referenced by PathGradientBrush::SetCenterPoint().
GdipSetPathGradientCenterPointI()
GpStatus WINGDIPAPI GdipSetPathGradientCenterPointI (GpPathGradient * , GDIPCONST GpPoint *)
Referenced by PathGradientBrush::SetCenterPoint().
GdipSetPathGradientFocusScales()
GpStatus WINGDIPAPI GdipSetPathGradientFocusScales (GpPathGradient * , REAL , REAL)
Referenced by PathGradientBrush::SetFocusScales().
GdipSetPathGradientGammaCorrection()
GpStatus WINGDIPAPI GdipSetPathGradientGammaCorrection (GpPathGradient * , BOOL)
Referenced by PathGradientBrush::SetGammaCorrection().
GdipSetPathGradientLinearBlend()
GpStatus WINGDIPAPI GdipSetPathGradientLinearBlend (GpPathGradient * , REAL , REAL)
Referenced by PathGradientBrush::SetBlendTriangularShape().
GdipSetPathGradientPath()
GpStatus WINGDIPAPI GdipSetPathGradientPath (GpPathGradient * , GDIPCONST GpPath *)
GdipSetPathGradientPresetBlend()
GpStatus WINGDIPAPI GdipSetPathGradientPresetBlend (GpPathGradient * , GDIPCONST ARGB * , GDIPCONST REAL * , INT)
Referenced by PathGradientBrush::SetInterpolationColors().
GdipSetPathGradientSigmaBlend()
GpStatus WINGDIPAPI GdipSetPathGradientSigmaBlend (GpPathGradient * , REAL , REAL)
Referenced by PathGradientBrush::SetBlendBellShape().
GdipSetPathGradientSurroundColorsWithCount()
GpStatus WINGDIPAPI GdipSetPathGradientSurroundColorsWithCount (GpPathGradient * , GDIPCONST ARGB * , INT *)
Referenced by PathGradientBrush::SetSurroundColors().
GdipSetPathGradientTransform()
GpStatus WINGDIPAPI GdipSetPathGradientTransform (GpPathGradient * , GpMatrix *)
Referenced by PathGradientBrush::SetTransform().
GdipSetPathGradientWrapMode()
GpStatus WINGDIPAPI GdipSetPathGradientWrapMode (GpPathGradient * , GpWrapMode)
Referenced by PathGradientBrush::SetWrapMode().
GdipSetPathMarker()
GpStatus WINGDIPAPI GdipSetPathMarker (GpPath *)
Referenced by GraphicsPath::SetMarker().
GdipSetPenBrushFill()
GpStatus WINGDIPAPI GdipSetPenBrushFill (GpPen * , GpBrush *)
Referenced by Pen::SetBrush().
GdipSetPenColor()
GpStatus WINGDIPAPI GdipSetPenColor (GpPen * , ARGB)
Referenced by Pen::SetColor().
GdipSetPenCompoundArray()
GpStatus WINGDIPAPI GdipSetPenCompoundArray (GpPen * , GDIPCONST REAL * , INT)
Referenced by Pen::SetCompoundArray().
GdipSetPenCustomEndCap()
GpStatus WINGDIPAPI GdipSetPenCustomEndCap (GpPen * , GpCustomLineCap *)
Referenced by Pen::SetCustomEndCap().
GdipSetPenCustomStartCap()
GpStatus WINGDIPAPI GdipSetPenCustomStartCap (GpPen * , GpCustomLineCap *)
Referenced by Pen::SetCustomStartCap().
GdipSetPenDashArray()
GpStatus WINGDIPAPI GdipSetPenDashArray (GpPen * , GDIPCONST REAL * , INT)
Referenced by Pen::SetDashPattern().
GdipSetPenDashCap197819()
GpStatus WINGDIPAPI GdipSetPenDashCap197819 (GpPen * , GpDashCap)
Referenced by Pen::SetDashCap().
GdipSetPenDashOffset()
GpStatus WINGDIPAPI GdipSetPenDashOffset (GpPen * , REAL)
Referenced by Pen::SetDashOffset().
GdipSetPenDashStyle()
GpStatus WINGDIPAPI GdipSetPenDashStyle (GpPen * , GpDashStyle)
Referenced by Pen::SetDashStyle().
GdipSetPenEndCap()
GpStatus WINGDIPAPI GdipSetPenEndCap (GpPen * , GpLineCap)
Referenced by Pen::SetEndCap().
GdipSetPenLineCap197819()
GpStatus WINGDIPAPI GdipSetPenLineCap197819 (GpPen * , GpLineCap , GpLineCap , GpDashCap)
Referenced by Pen::SetLineCap().
GdipSetPenLineJoin()
GpStatus WINGDIPAPI GdipSetPenLineJoin (GpPen * , GpLineJoin)
Referenced by Pen::SetLineJoin().
GdipSetPenMiterLimit()
GpStatus WINGDIPAPI GdipSetPenMiterLimit (GpPen * , REAL)
Referenced by Pen::SetMiterLimit().
GdipSetPenMode()
GpStatus WINGDIPAPI GdipSetPenMode (GpPen * , GpPenAlignment)
Referenced by Pen::SetAlignment().
GdipSetPenStartCap()
GpStatus WINGDIPAPI GdipSetPenStartCap (GpPen * , GpLineCap)
Referenced by Pen::SetStartCap().
GdipSetPenTransform()
GpStatus WINGDIPAPI GdipSetPenTransform (GpPen * , GpMatrix *)
Referenced by Pen::SetTransform().
GdipSetPenUnit()
GpStatus WINGDIPAPI GdipSetPenUnit (GpPen * , GpUnit)
GdipSetPenWidth()
GpStatus WINGDIPAPI GdipSetPenWidth (GpPen * , REAL)
Referenced by Pen::SetWidth().
GdipSetPixelOffsetMode()
GpStatus WINGDIPAPI GdipSetPixelOffsetMode (GpGraphics * , PixelOffsetMode)
Referenced by Graphics::SetPixelOffsetMode().
GdipSetPropertyItem()
GpStatus WINGDIPAPI GdipSetPropertyItem (GpImage * , GDIPCONST PropertyItem *)
Referenced by Image::SetPropertyItem().
GdipSetRenderingOrigin()
GpStatus WINGDIPAPI GdipSetRenderingOrigin (GpGraphics * , INT , INT)
Referenced by Graphics::SetRenderingOrigin().
GdipSetSmoothingMode()
GpStatus WINGDIPAPI GdipSetSmoothingMode (GpGraphics * , SmoothingMode)
Referenced by Graphics::SetSmoothingMode().
GdipSetSolidFillColor()
GpStatus WINGDIPAPI GdipSetSolidFillColor (GpSolidFill * , ARGB)
Referenced by SolidBrush::SetColor().
GdipSetStringFormatAlign()
GpStatus WINGDIPAPI GdipSetStringFormatAlign (GpStringFormat * , StringAlignment)
Referenced by StringFormat::SetAlignment().
GdipSetStringFormatDigitSubstitution()
GpStatus WINGDIPAPI GdipSetStringFormatDigitSubstitution (GpStringFormat * , LANGID , StringDigitSubstitute)
Referenced by StringFormat::SetDigitSubstitution().
GdipSetStringFormatFlags()
GpStatus WINGDIPAPI GdipSetStringFormatFlags (GpStringFormat * , INT)
Referenced by StringFormat::SetFormatFlags().
GdipSetStringFormatHotkeyPrefix()
GpStatus WINGDIPAPI GdipSetStringFormatHotkeyPrefix (GpStringFormat * , INT)
Referenced by StringFormat::SetHotkeyPrefix().
GdipSetStringFormatLineAlign()
GpStatus WINGDIPAPI GdipSetStringFormatLineAlign (GpStringFormat * , StringAlignment)
Referenced by StringFormat::SetLineAlignment().
GdipSetStringFormatMeasurableCharacterRanges()
GpStatus WINGDIPAPI GdipSetStringFormatMeasurableCharacterRanges (GpStringFormat * , INT , GDIPCONST CharacterRange *)
Referenced by StringFormat::SetMeasurableCharacterRanges().
GdipSetStringFormatTabStops()
GpStatus WINGDIPAPI GdipSetStringFormatTabStops (GpStringFormat * , REAL , INT , GDIPCONST REAL *)
Referenced by StringFormat::SetTabStops().
GdipSetStringFormatTrimming()
GpStatus WINGDIPAPI GdipSetStringFormatTrimming (GpStringFormat * , StringTrimming)
Referenced by StringFormat::SetTrimming().
GdipSetTextContrast()
GpStatus WINGDIPAPI GdipSetTextContrast (GpGraphics * , UINT)
Referenced by Graphics::SetTextContrast().
GdipSetTextRenderingHint()
GpStatus WINGDIPAPI GdipSetTextRenderingHint (GpGraphics * , TextRenderingHint)
Referenced by Graphics::SetTextRenderingHint().
GdipSetTextureTransform()
GpStatus WINGDIPAPI GdipSetTextureTransform (GpTexture * , GDIPCONST GpMatrix *)
Referenced by TextureBrush::SetTransform().
GdipSetTextureWrapMode()
GpStatus WINGDIPAPI GdipSetTextureWrapMode (GpTexture * , GpWrapMode)
Referenced by TextureBrush::SetWrapMode().
GdipSetWorldTransform()
GpStatus WINGDIPAPI GdipSetWorldTransform (GpGraphics * , GpMatrix *)
Referenced by Graphics::SetTransform().
GdipShearMatrix()
GpStatus WINGDIPAPI GdipShearMatrix (GpMatrix * , REAL , REAL , GpMatrixOrder)
Referenced by Matrix::Shear().
GdipStartPathFigure()
GpStatus WINGDIPAPI GdipStartPathFigure (GpPath *)
Referenced by GraphicsPath::StartFigure().
GdipStringFormatGetGenericDefault()
GpStatus WINGDIPAPI GdipStringFormatGetGenericDefault (GpStringFormat **)
Referenced by StringFormat::GenericDefault().
GdipStringFormatGetGenericTypographic()
GpStatus WINGDIPAPI GdipStringFormatGetGenericTypographic (GpStringFormat **)
Referenced by StringFormat::GenericTypographic().
GdipTestControl()
GpStatus WINGDIPAPI GdipTestControl (GpTestControlEnum , void *)
GdipTransformMatrixPoints()
GpStatus WINGDIPAPI GdipTransformMatrixPoints (GpMatrix * , GpPointF * , INT)
Referenced by Matrix::TransformPoints().
GdipTransformMatrixPointsI()
GpStatus WINGDIPAPI GdipTransformMatrixPointsI (GpMatrix * , GpPoint * , INT)
Referenced by Matrix::TransformPoints().
GdipTransformPath()
GpStatus WINGDIPAPI GdipTransformPath (GpPath * , GpMatrix *)
Referenced by GraphicsPath::Transform().
GdipTransformPoints()
GpStatus WINGDIPAPI GdipTransformPoints (GpGraphics * , GpCoordinateSpace , GpCoordinateSpace , GpPointF * , INT)
Referenced by Graphics::TransformPoints().
GdipTransformPointsI()
GpStatus WINGDIPAPI GdipTransformPointsI (GpGraphics * , GpCoordinateSpace , GpCoordinateSpace , GpPoint * , INT)
Referenced by Graphics::TransformPoints().
GdipTransformRegion()
GpStatus WINGDIPAPI GdipTransformRegion (GpRegion * , GpMatrix *)
Referenced by Region::Transform().
GdipTranslateClip()
GpStatus WINGDIPAPI GdipTranslateClip (GpGraphics * , REAL , REAL)
Referenced by Graphics::TranslateClip().
GdipTranslateClipI()
GpStatus WINGDIPAPI GdipTranslateClipI (GpGraphics * , INT , INT)
Referenced by Graphics::TranslateClip().
GdipTranslateLineTransform()
GpStatus WINGDIPAPI GdipTranslateLineTransform (GpLineGradient * , REAL , REAL , GpMatrixOrder)
Referenced by LinearGradientBrush::TranslateTransform().
GdipTranslateMatrix()
GpStatus WINGDIPAPI GdipTranslateMatrix (GpMatrix * , REAL , REAL , GpMatrixOrder)
Referenced by Matrix::Translate().
GdipTranslatePathGradientTransform()
GpStatus WINGDIPAPI GdipTranslatePathGradientTransform (GpPathGradient * , REAL , REAL , GpMatrixOrder)
Referenced by PathGradientBrush::TranslateTransform().
GdipTranslatePenTransform()
GpStatus WINGDIPAPI GdipTranslatePenTransform (GpPen * , REAL , REAL , GpMatrixOrder)
Referenced by Pen::TranslateTransform().
GdipTranslateRegion()
GpStatus WINGDIPAPI GdipTranslateRegion (GpRegion * , REAL , REAL)
Referenced by Region::Translate().
GdipTranslateRegionI()
GpStatus WINGDIPAPI GdipTranslateRegionI (GpRegion * , INT , INT)
Referenced by Region::Translate().
GdipTranslateTextureTransform()
GpStatus WINGDIPAPI GdipTranslateTextureTransform (GpTexture * , REAL , REAL , GpMatrixOrder)
Referenced by TextureBrush::TranslateTransform().
GdipTranslateWorldTransform()
GpStatus WINGDIPAPI GdipTranslateWorldTransform (GpGraphics * , REAL , REAL , GpMatrixOrder)
Referenced by Graphics::TranslateTransform().
GdipVectorTransformMatrixPoints()
GpStatus WINGDIPAPI GdipVectorTransformMatrixPoints (GpMatrix * , GpPointF * , INT)
Referenced by Matrix::TransformVectors().
GdipVectorTransformMatrixPointsI()
GpStatus WINGDIPAPI GdipVectorTransformMatrixPointsI (GpMatrix * , GpPoint * , INT)
Referenced by Matrix::TransformVectors().
GdipWarpPath()
GpStatus WINGDIPAPI GdipWarpPath (GpPath * , GpMatrix * , GDIPCONST GpPointF * , INT , REAL , REAL , REAL , REAL , WarpMode , REAL)
Referenced by GraphicsPath::Warp().
GdipWidenPath()
GpStatus WINGDIPAPI GdipWidenPath (GpPath * , GpPen * , GpMatrix * , REAL)
Referenced by GraphicsPath::Widen().
GdipWindingModeOutline()
GpStatus WINGDIPAPI GdipWindingModeOutline (GpPath * , GpMatrix * , REAL)
Referenced by GraphicsPath::Outline().