ZEQ2-Lite: pcrecpp::StringPiece Class Reference
pcrecpp::StringPiece Class Reference
#include <pcre_stringpiece.h>
Public Member Functions
StringPiece ()
StringPiece (const char *offset, int len)
StringPiece (const char *str)
StringPiece (const string &str)
StringPiece (const unsigned char *str)
string as_string () const
void clear ()
int compare (const StringPiece &x) const
void CopyToString (string *target) const
const char * data () const
bool empty () const
bool operator!= (const StringPiece &x) const
bool operator== (const StringPiece &x) const
char operator[] (int i) const
void remove_prefix (int n)
void remove_suffix (int n)
void set (const char *buffer, int len)
void set (const char *str)
void set (const void *buffer, int len)
int size () const
bool starts_with (const StringPiece &x) const
STRINGPIECE_BINARY_PREDICATE (<,<)
STRINGPIECE_BINARY_PREDICATE (<=,<)
STRINGPIECE_BINARY_PREDICATE (>, >)
STRINGPIECE_BINARY_PREDICATE (>=, >)
Private Attributes
int length_
const char * ptr_
Detailed Description
Definition at line 61 of file pcre_stringpiece.h.
Constructor & Destructor Documentation
StringPiece() [1/5]
pcrecpp::StringPiece::StringPiece () inline
Definition at line 70 of file pcre_stringpiece.h.
     : ptr_(NULL), length_(0) { }
StringPiece() [2/5]
pcrecpp::StringPiece::StringPiece (const char * str) inline
Definition at line 72 of file pcre_stringpiece.h.
     : ptr_(str), length_(static_cast<int>(strlen(ptr_))) { }
StringPiece() [3/5]
pcrecpp::StringPiece::StringPiece (const unsigned char * str) inline
Definition at line 74 of file pcre_stringpiece.h.
     : ptr_(reinterpret_cast<const char*>(str)),
       length_(static_cast<int>(strlen(ptr_))) { }
StringPiece() [4/5]
pcrecpp::StringPiece::StringPiece (const string & str) inline
Definition at line 77 of file pcre_stringpiece.h.
     : ptr_(str.data()), length_(static_cast<int>(str.size())) { }
StringPiece() [5/5]
pcrecpp::StringPiece::StringPiece (const char * offset, int len) inline
Definition at line 79 of file pcre_stringpiece.h.
     : ptr_(offset), length_(len) { }
Member Function Documentation
as_string()
string pcrecpp::StringPiece::as_string () const inline
Definition at line 142 of file pcre_stringpiece.h.
{
     return string(data(), size());
   }
clear()
void pcrecpp::StringPiece::clear () inline
Definition at line 92 of file pcre_stringpiece.h.
 { ptr_ = NULL; length_ = 0; }
References NULL.
compare()
int pcrecpp::StringPiece::compare (const StringPiece & x) const inline
Definition at line 133 of file pcre_stringpiece.h.
{
     int r = memcmp(ptr_, x.ptr_, length_ < x.length_ ? length_ : x.length_);
     if (r == 0) {
       if (length_ < x.length_) r = -1;
       else if (length_ > x.length_) r = +1;
     }
     return r;
   }
References memcmp().
CopyToString()
void pcrecpp::StringPiece::CopyToString (string * target) const inline
Definition at line 146 of file pcre_stringpiece.h.
{
     target->assign(ptr_, length_);
   }
data()
const char* pcrecpp::StringPiece::data () const inline
Definition at line 88 of file pcre_stringpiece.h.
 { return ptr_; }
empty()
bool pcrecpp::StringPiece::empty () const inline
Definition at line 90 of file pcre_stringpiece.h.
 { return length_ == 0; }
operator!=()
bool pcrecpp::StringPiece::operator!= (const StringPiece & x) const inline
Definition at line 118 of file pcre_stringpiece.h.
{
     return !(*this == x);
   }
operator==()
bool pcrecpp::StringPiece::operator== (const StringPiece & x) const inline
Definition at line 114 of file pcre_stringpiece.h.
{
     return ((length_ == x.length_) &&
             (memcmp(ptr_, x.ptr_, length_) == 0));
   }
References memcmp().
operator[]()
char pcrecpp::StringPiece::operator[] (int i) const inline
Definition at line 103 of file pcre_stringpiece.h.
 { return ptr_[i]; }
remove_prefix()
void pcrecpp::StringPiece::remove_prefix (int n) inline
Definition at line 105 of file pcre_stringpiece.h.
{
     ptr_ += n;
     length_ -= n;
   }
remove_suffix()
void pcrecpp::StringPiece::remove_suffix (int n) inline
Definition at line 110 of file pcre_stringpiece.h.
{
     length_ -= n;
   }
set() [1/3]
void pcrecpp::StringPiece::set (const char * buffer, int len) inline
Definition at line 93 of file pcre_stringpiece.h.
 { ptr_ = buffer; length_ = len; }
set() [2/3]
void pcrecpp::StringPiece::set (const char * str) inline
Definition at line 94 of file pcre_stringpiece.h.
{
     ptr_ = str;
     length_ = static_cast<int>(strlen(str));
   }
References strlen().
set() [3/3]
void pcrecpp::StringPiece::set (const void * buffer, int len) inline
Definition at line 98 of file pcre_stringpiece.h.
{
     ptr_ = reinterpret_cast<const char*>(buffer);
     length_ = len;
   }
size()
int pcrecpp::StringPiece::size () const inline
Definition at line 89 of file pcre_stringpiece.h.
 { return length_; }
starts_with()
bool pcrecpp::StringPiece::starts_with (const StringPiece & x) const inline
Definition at line 151 of file pcre_stringpiece.h.
{
     return ((length_ >= x.length_) && (memcmp(ptr_, x.ptr_, x.length_) == 0));
   }
References memcmp().
STRINGPIECE_BINARY_PREDICATE() [1/4]
pcrecpp::StringPiece::STRINGPIECE_BINARY_PREDICATE ()
STRINGPIECE_BINARY_PREDICATE() [2/4]
pcrecpp::StringPiece::STRINGPIECE_BINARY_PREDICATE (<=)
STRINGPIECE_BINARY_PREDICATE() [3/4]
pcrecpp::StringPiece::STRINGPIECE_BINARY_PREDICATE ()
STRINGPIECE_BINARY_PREDICATE() [4/4]
pcrecpp::StringPiece::STRINGPIECE_BINARY_PREDICATE (>=)
Field Documentation
length_
int pcrecpp::StringPiece::length_ private
Definition at line 64 of file pcre_stringpiece.h.
ptr_
const char* pcrecpp::StringPiece::ptr_ private
Definition at line 63 of file pcre_stringpiece.h.
The documentation for this class was generated from the following file:
Tools/MinGW/include/pcre_stringpiece.h