ZEQ2-Lite: Engine/SDL12/include/SDL_events.h File Reference
SDL_events.h File Reference
#include "SDL_stdinc.h"
#include "SDL_error.h"
#include "SDL_active.h"
#include "SDL_keyboard.h"
#include "SDL_mouse.h"
#include "SDL_joystick.h"
#include "SDL_quit.h"
#include "begin_code.h"
#include "close_code.h"
Data Structures
struct SDL_ActiveEvent
Application visibility event structure.
union SDL_Event
General event structure.
struct SDL_ExposeEvent
The "screen redraw" event.
struct SDL_JoyAxisEvent
Joystick axis motion event structure.
struct SDL_JoyBallEvent
Joystick trackball motion event structure.
struct SDL_JoyButtonEvent
Joystick button event structure.
struct SDL_JoyHatEvent
Joystick hat position change event structure.
struct SDL_KeyboardEvent
Keyboard event structure.
struct SDL_MouseButtonEvent
Mouse button event structure.
struct SDL_MouseMotionEvent
Mouse motion event structure.
struct SDL_QuitEvent
The "quit requested" event.
struct SDL_ResizeEvent
The "window resized" event When you get this event, you are responsible for setting a new video mode with the new width and height.
struct SDL_SysWMEvent
struct SDL_UserEvent
A user-defined event type.
General keyboard/mouse state definitions
enum SDL_EventType {
SDL_NOEVENT = 0, SDL_ACTIVEEVENT, SDL_KEYDOWN, SDL_KEYUP,
SDL_MOUSEMOTION, SDL_MOUSEBUTTONDOWN, SDL_MOUSEBUTTONUP, SDL_JOYAXISMOTION,
SDL_JOYBALLMOTION, SDL_JOYHATMOTION, SDL_JOYBUTTONDOWN, SDL_JOYBUTTONUP,
SDL_QUIT, SDL_SYSWMEVENT, SDL_EVENT_RESERVEDA, SDL_EVENT_RESERVEDB,
SDL_VIDEORESIZE, SDL_VIDEOEXPOSE, SDL_EVENT_RESERVED2, SDL_EVENT_RESERVED3,
SDL_EVENT_RESERVED4, SDL_EVENT_RESERVED5, SDL_EVENT_RESERVED6, SDL_EVENT_RESERVED7,
SDL_USEREVENT = 24, SDL_NUMEVENTS = 32
}
Event enumerations.
#define SDL_PRESSED 1
#define SDL_RELEASED 0
Predefined event masks
#define SDL_ALLEVENTS 0xFFFFFFFF
enum SDL_eventaction { SDL_ADDEVENT, SDL_PEEKEVENT, SDL_GETEVENT }
#define SDL_EVENTMASK(X) (1<<(X))
enum SDL_EventMask {
SDL_ACTIVEEVENTMASK = SDL_EVENTMASK(SDL_ACTIVEEVENT), SDL_KEYDOWNMASK = SDL_EVENTMASK(SDL_KEYDOWN), SDL_KEYUPMASK = SDL_EVENTMASK(SDL_KEYUP), SDL_KEYEVENTMASK,
SDL_MOUSEMOTIONMASK = SDL_EVENTMASK(SDL_MOUSEMOTION), SDL_MOUSEBUTTONDOWNMASK = SDL_EVENTMASK(SDL_MOUSEBUTTONDOWN), SDL_MOUSEBUTTONUPMASK = SDL_EVENTMASK(SDL_MOUSEBUTTONUP), SDL_MOUSEEVENTMASK,
SDL_JOYAXISMOTIONMASK = SDL_EVENTMASK(SDL_JOYAXISMOTION), SDL_JOYBALLMOTIONMASK = SDL_EVENTMASK(SDL_JOYBALLMOTION), SDL_JOYHATMOTIONMASK = SDL_EVENTMASK(SDL_JOYHATMOTION), SDL_JOYBUTTONDOWNMASK = SDL_EVENTMASK(SDL_JOYBUTTONDOWN),
SDL_JOYBUTTONUPMASK = SDL_EVENTMASK(SDL_JOYBUTTONUP), SDL_JOYEVENTMASK, SDL_VIDEORESIZEMASK = SDL_EVENTMASK(SDL_VIDEORESIZE), SDL_VIDEOEXPOSEMASK = SDL_EVENTMASK(SDL_VIDEOEXPOSE),
SDL_QUITMASK = SDL_EVENTMASK(SDL_QUIT), SDL_SYSWMEVENTMASK = SDL_EVENTMASK(SDL_SYSWMEVENT)
}
DECLSPEC int SDLCALL SDL_PeepEvents (SDL_Event *events, int numevents, SDL_eventaction action, Uint32 mask)
Checks the event queue for messages and optionally returns them.
DECLSPEC int SDLCALL SDL_PollEvent (SDL_Event *event)
Polls for currently pending events, and returns 1 if there are any pending events, or 0 if there are none available.
DECLSPEC void SDLCALL SDL_PumpEvents (void)
Pumps the event loop, gathering events from the input devices.
DECLSPEC int SDLCALL SDL_PushEvent (SDL_Event *event)
Add an event to the event queue.
DECLSPEC int SDLCALL SDL_WaitEvent (SDL_Event *event)
Waits indefinitely for the next available event, returning 1, or 0 if there was an error while waiting for events.
Event Filtering
typedef int(SDLCALL * SDL_EventFilter) (const SDL_Event *event)
DECLSPEC SDL_EventFilter SDLCALL SDL_GetEventFilter (void)
Return the current event filter - can be used to "chain" filters.
DECLSPEC void SDLCALL SDL_SetEventFilter (SDL_EventFilter filter)
This function sets up a filter to process all events before they change internal state and are posted to the internal event queue.
Event State
#define SDL_DISABLE 0
#define SDL_ENABLE 1
DECLSPEC Uint8 SDLCALL SDL_EventState (Uint8 type, int state)
This function allows you to set the state of processing certain events.
#define SDL_IGNORE 0
#define SDL_QUERY -1
Detailed Description
Include file for SDL event handling
Definition in file SDL_events.h.
Macro Definition Documentation
SDL_ALLEVENTS
#define SDL_ALLEVENTS 0xFFFFFFFF
Definition at line 115 of file SDL_events.h.
SDL_DISABLE
#define SDL_DISABLE 0
Definition at line 336 of file SDL_events.h.
SDL_ENABLE
#define SDL_ENABLE 1
Definition at line 337 of file SDL_events.h.
SDL_EVENTMASK
#define SDL_EVENTMASK (X) (1<<(X))
Definition at line 87 of file SDL_events.h.
SDL_IGNORE
#define SDL_IGNORE 0
Definition at line 335 of file SDL_events.h.
SDL_PRESSED
#define SDL_PRESSED 1
Definition at line 48 of file SDL_events.h.
SDL_QUERY
#define SDL_QUERY -1
Definition at line 334 of file SDL_events.h.
SDL_RELEASED
#define SDL_RELEASED 0
Definition at line 47 of file SDL_events.h.
Typedef Documentation
SDL_EventFilter
typedef int(SDLCALL * SDL_EventFilter) (const SDL_Event *event)
Definition at line 300 of file SDL_events.h.
Enumeration Type Documentation
SDL_eventaction
enum SDL_eventaction
Enumerator
SDL_ADDEVENT
SDL_PEEKEVENT
SDL_GETEVENT
Definition at line 253 of file SDL_events.h.
              {
     SDL_ADDEVENT,
     SDL_PEEKEVENT,
     SDL_GETEVENT
 } SDL_eventaction;
SDL_EventMask
enum SDL_EventMask
Enumerator
SDL_ACTIVEEVENTMASK
SDL_KEYDOWNMASK
SDL_KEYUPMASK
SDL_KEYEVENTMASK
SDL_MOUSEMOTIONMASK
SDL_MOUSEBUTTONDOWNMASK
SDL_MOUSEBUTTONUPMASK
SDL_MOUSEEVENTMASK
SDL_JOYAXISMOTIONMASK
SDL_JOYBALLMOTIONMASK
SDL_JOYHATMOTIONMASK
SDL_JOYBUTTONDOWNMASK
SDL_JOYBUTTONUPMASK
SDL_JOYEVENTMASK
SDL_VIDEORESIZEMASK
SDL_VIDEOEXPOSEMASK
SDL_QUITMASK
SDL_SYSWMEVENTMASK
Definition at line 88 of file SDL_events.h.
              {
     SDL_ACTIVEEVENTMASK = SDL_EVENTMASK(SDL_ACTIVEEVENT),
     SDL_KEYDOWNMASK     = SDL_EVENTMASK(SDL_KEYDOWN),
     SDL_KEYUPMASK       = SDL_EVENTMASK(SDL_KEYUP),
     SDL_KEYEVENTMASK    = SDL_EVENTMASK(SDL_KEYDOWN)|
                               SDL_EVENTMASK(SDL_KEYUP),
     SDL_MOUSEMOTIONMASK = SDL_EVENTMASK(SDL_MOUSEMOTION),
     SDL_MOUSEBUTTONDOWNMASK = SDL_EVENTMASK(SDL_MOUSEBUTTONDOWN),
     SDL_MOUSEBUTTONUPMASK   = SDL_EVENTMASK(SDL_MOUSEBUTTONUP),
     SDL_MOUSEEVENTMASK  = SDL_EVENTMASK(SDL_MOUSEMOTION)|
                               SDL_EVENTMASK(SDL_MOUSEBUTTONDOWN)|
                               SDL_EVENTMASK(SDL_MOUSEBUTTONUP),
     SDL_JOYAXISMOTIONMASK   = SDL_EVENTMASK(SDL_JOYAXISMOTION),
     SDL_JOYBALLMOTIONMASK   = SDL_EVENTMASK(SDL_JOYBALLMOTION),
     SDL_JOYHATMOTIONMASK    = SDL_EVENTMASK(SDL_JOYHATMOTION),
     SDL_JOYBUTTONDOWNMASK   = SDL_EVENTMASK(SDL_JOYBUTTONDOWN),
     SDL_JOYBUTTONUPMASK = SDL_EVENTMASK(SDL_JOYBUTTONUP),
     SDL_JOYEVENTMASK    = SDL_EVENTMASK(SDL_JOYAXISMOTION)|
                               SDL_EVENTMASK(SDL_JOYBALLMOTION)|
                               SDL_EVENTMASK(SDL_JOYHATMOTION)|
                               SDL_EVENTMASK(SDL_JOYBUTTONDOWN)|
                               SDL_EVENTMASK(SDL_JOYBUTTONUP),
     SDL_VIDEORESIZEMASK = SDL_EVENTMASK(SDL_VIDEORESIZE),
     SDL_VIDEOEXPOSEMASK = SDL_EVENTMASK(SDL_VIDEOEXPOSE),
     SDL_QUITMASK        = SDL_EVENTMASK(SDL_QUIT),
     SDL_SYSWMEVENTMASK  = SDL_EVENTMASK(SDL_SYSWMEVENT)
 } SDL_EventMask ;
SDL_EventType
enum SDL_EventType
Event enumerations.
Enumerator
SDL_NOEVENT
Unused (do not remove)
SDL_ACTIVEEVENT
Application loses/gains visibility.
SDL_KEYDOWN
Keys pressed.
SDL_KEYUP
Keys released.
SDL_MOUSEMOTION
Mouse moved.
SDL_MOUSEBUTTONDOWN
Mouse button pressed.
SDL_MOUSEBUTTONUP
Mouse button released.
SDL_JOYAXISMOTION
Joystick axis motion.
SDL_JOYBALLMOTION
Joystick trackball motion.
SDL_JOYHATMOTION
Joystick hat position change.
SDL_JOYBUTTONDOWN
Joystick button pressed.
SDL_JOYBUTTONUP
Joystick button released.
SDL_QUIT
User-requested quit.
SDL_SYSWMEVENT
System specific event.
SDL_EVENT_RESERVEDA
Reserved for future use.
SDL_EVENT_RESERVEDB
Reserved for future use.
SDL_VIDEORESIZE
User resized video mode.
SDL_VIDEOEXPOSE
Screen needs to be redrawn.
SDL_EVENT_RESERVED2
Reserved for future use.
SDL_EVENT_RESERVED3
Reserved for future use.
SDL_EVENT_RESERVED4
Reserved for future use.
SDL_EVENT_RESERVED5
Reserved for future use.
SDL_EVENT_RESERVED6
Reserved for future use.
SDL_EVENT_RESERVED7
Reserved for future use.
SDL_USEREVENT
Events SDL_USEREVENT through SDL_MAXEVENTS-1 are for your use.
SDL_NUMEVENTS
This last event is only for bounding internal arrays It is the number of bits in the event mask datatype – Uint32.
Definition at line 52 of file SDL_events.h.
              {
        SDL_NOEVENT = 0,
        SDL_ACTIVEEVENT,
        SDL_KEYDOWN,
        SDL_KEYUP,
        SDL_MOUSEMOTION,
        SDL_MOUSEBUTTONDOWN,
        SDL_MOUSEBUTTONUP,
        SDL_JOYAXISMOTION,
        SDL_JOYBALLMOTION,
        SDL_JOYHATMOTION,
        SDL_JOYBUTTONDOWN,
        SDL_JOYBUTTONUP,
        SDL_QUIT,
        SDL_SYSWMEVENT,
        SDL_EVENT_RESERVEDA,
        SDL_EVENT_RESERVEDB,
        SDL_VIDEORESIZE,
        SDL_VIDEOEXPOSE,
        SDL_EVENT_RESERVED2,
        SDL_EVENT_RESERVED3,
        SDL_EVENT_RESERVED4,
        SDL_EVENT_RESERVED5,
        SDL_EVENT_RESERVED6,
        SDL_EVENT_RESERVED7,
        SDL_USEREVENT = 24,
        SDL_NUMEVENTS = 32
 } SDL_EventType;
Function Documentation
SDL_EventState()
DECLSPEC Uint8 SDLCALL SDL_EventState (Uint8 type, int state)
This function allows you to set the state of processing certain events.
If 'state' is set to SDL_IGNORE, that event will be automatically dropped from the event queue and will not event be filtered. If 'state' is set to SDL_ENABLE, that event will be processed normally. If 'state' is set to SDL_QUERY, SDL_EventState() will return the current processing state of the specified event.
SDL_GetEventFilter()
DECLSPEC SDL_EventFilter SDLCALL SDL_GetEventFilter (void)
Return the current event filter - can be used to "chain" filters.
If there is no event filter set, this function returns NULL.
SDL_PeepEvents()
DECLSPEC int SDLCALL SDL_PeepEvents (SDL_Event * events, int numevents, SDL_eventaction action, Uint32 mask)
Checks the event queue for messages and optionally returns them.
If 'action' is SDL_ADDEVENT, up to 'numevents' events will be added to the back of the event queue. If 'action' is SDL_PEEKEVENT, up to 'numevents' events at the front of the event queue, matching 'mask', will be returned and will not be removed from the queue. If 'action' is SDL_GETEVENT, up to 'numevents' events at the front of the event queue, matching 'mask', will be returned and will be removed from the queue.
Returns
This function returns the number of events actually stored, or -1 if there was an error.
This function is thread-safe.
Referenced by IN_GobbleMotionEvents().
SDL_PollEvent()
DECLSPEC int SDLCALL SDL_PollEvent (SDL_Event * event)
Polls for currently pending events, and returns 1 if there are any pending events, or 0 if there are none available.
If 'event' is not NULL, the next event is removed from the queue and stored in that area.
Referenced by IN_ProcessEvents().
SDL_PumpEvents()
DECLSPEC void SDLCALL SDL_PumpEvents (void)
Pumps the event loop, gathering events from the input devices.
This function updates the event queue and internal input device state. This should only be run in the thread that sets the video mode.
Referenced by IN_GobbleMotionEvents().
SDL_PushEvent()
DECLSPEC int SDLCALL SDL_PushEvent (SDL_Event * event)
Add an event to the event queue.
This function returns 0 on success, or -1 if the event queue was full or there was some other error.
SDL_SetEventFilter()
DECLSPEC void SDLCALL SDL_SetEventFilter (SDL_EventFilter filter)
This function sets up a filter to process all events before they change internal state and are posted to the internal event queue.
The filter is protypted as:
typedef int (SDLCALL *SDL_EventFilter)(const SDL_Event *event);
If the filter returns 1, then the event will be added to the internal queue. If it returns 0, then the event will be dropped from the queue, but the internal state will still be updated. This allows selective filtering of dynamically arriving events.
Warning
Be very careful of what you do in the event filter function, as it may run in a different thread!
There is one caveat when dealing with the SDL_QUITEVENT event type. The event filter is only called when the window manager desires to close the application window. If the event filter returns 1, then the window will be closed, otherwise the window will remain open if possible. If the quit event is generated by an interrupt signal, it will bypass the internal queue and be delivered to the application at the next event poll.
SDL_WaitEvent()
DECLSPEC int SDLCALL SDL_WaitEvent (SDL_Event * event)
Waits indefinitely for the next available event, returning 1, or 0 if there was an error while waiting for events.
If 'event' is not NULL, the next event is removed from the queue and stored in that area.