ZEQ2-Lite: Source/Game/CGame/cg_weapGfxScanner.c File Reference
cg_weapGfxScanner.c File Reference
#include "cg_weapGfxParser.h"
Functions
qboolean CG_weapGfx_CheckPrematureEOF (cg_weapGfxScanner_t *scanner, cg_weapGfxToken_t *token)
qboolean CG_weapGfx_ErrorHandle (cg_weapGfxError_t errorNr, cg_weapGfxScanner_t *scanner, char *string1, char *string2)
qboolean CG_weapGfx_LoadFile (cg_weapGfxScanner_t *scanner, char *filename)
qboolean CG_weapGfx_NextSym (cg_weapGfxScanner_t *scanner, cg_weapGfxToken_t *token)
Variables
char * cg_weapGfxCategories [] = {"Charge","Explosion","Struggle","Missile","Flash","Trail","Hud",""}
cg_weapGfxField_t cg_weapGfxFields []
Function Documentation
CG_weapGfx_CheckPrematureEOF()
qboolean CG_weapGfx_CheckPrematureEOF (cg_weapGfxScanner_t * scanner, cg_weapGfxToken_t * token)
Definition at line 292 of file cg_weapGfxScanner.c.
{
     if(CG_weapGfx_NextSym(scanner,token)){return qtrue;}
     return token->tokenSym == TOKEN_EOF ? CG_weapGfx_ErrorHandle(ERROR_PREMATURE_EOF,scanner,NULL,NULL) : qfalse;
 }
References CG_weapGfx_ErrorHandle(), CG_weapGfx_NextSym(), ERROR_PREMATURE_EOF, NULL, qfalse, qtrue, and TOKEN_EOF.
Referenced by CG_weapGfx_ParseAnimationRange(), CG_weapGfx_ParseCategories(), CG_weapGfx_ParseDefinition(), CG_weapGfx_ParseDisplayName(), CG_weapGfx_ParseDlight(), CG_weapGfx_ParseDuration(), CG_weapGfx_ParseFields(), CG_weapGfx_ParseIcon(), CG_weapGfx_ParseImports(), CG_weapGfx_ParseLinks(), CG_weapGfx_ParseLoopFx(), CG_weapGfx_ParseLoopParticles(), CG_weapGfx_ParseMarkShader(), CG_weapGfx_ParseMarkSize(), CG_weapGfx_ParseModel(), CG_weapGfx_ParseOnceFx(), CG_weapGfx_ParseParticles(), CG_weapGfx_ParseRockDebris(), CG_weapGfx_ParseShader(), CG_weapGfx_ParseShockwave(), CG_weapGfx_ParseSize(), CG_weapGfx_ParseSkin(), CG_weapGfx_ParseSmokeParticles(), CG_weapGfx_ParseSoundFx(), CG_weapGfx_ParseSpin(), CG_weapGfx_ParseSpiralOffset(), CG_weapGfx_ParseSpiralShader(), CG_weapGfx_ParseSpiralSize(), CG_weapGfx_ParseTagTo(), CG_weapGfx_ParseTimedFx(), CG_weapGfx_ParseVoiceFx(), and CG_weapGfx_PreParseDefinitions().
CG_weapGfx_ErrorHandle()
qboolean CG_weapGfx_ErrorHandle (cg_weapGfxError_t errorNr, cg_weapGfxScanner_t * scanner, char * string1, char * string2)
Definition at line 35 of file cg_weapGfxScanner.c.
{
     char* file = scanner->filename;
     // <-- Internally we start from 0, for the user we start from 1
     int line = scanner->line + 1;
     if(errorNr == ERROR_FILE_NOTFOUND){CG_Printf("%s: File not found.\n",file);}
     else if(errorNr == ERROR_FILE_TOOBIG){CG_Printf("%s: File exceeds maximum script length.\n",file);}
     else if(errorNr == ERROR_PREMATURE_EOF){CG_Printf("%s(%i): Premature end of file.\n",file,line);}
     else if(errorNr == ERROR_STRING_TOOBIG){CG_Printf("%s(%i): String exceeds limit of %i characters.\n",file,line,MAX_TOKENSTRING_LENGTH);}
     else if(errorNr == ERROR_TOKEN_TOOBIG){CG_Printf("%s(%i): Symbol exceeds limit of %i characters.\n",file,line,MAX_TOKENSTRING_LENGTH);}
     else if(errorNr == ERROR_UNKNOWN_SYMBOL){CG_Printf("%s(%i): Unknown symbol '%s' encountered.\n",file,line,string1);}
     else if(errorNr == ERROR_UNEXPECTED_SYMBOL){
         if(!string2){CG_Printf("%s(%i): Unexpected symbol '%s' found.\n",file,line,string1);}
         else{CG_Printf("%s(%i): Unexpected symbol '%s' found, expected '%s'.\n",file,line,string1,string2);}
     }
     else if(errorNr == ERROR_STRING_EXPECTED){CG_Printf("%s(%i): String expected. '%s' is not a string or is missing quotes.\n",file,line,string1);}
     else if(errorNr == ERROR_INTEGER_EXPECTED){CG_Printf("%s(%i): Integer expected, but '%s' found.\n",file,line,string1);}
     else if(errorNr == ERROR_FLOAT_EXPECTED){CG_Printf("%s(%i): Float or integer expected, but '%s' found.\n",file,line,string1);}
     else if(errorNr == ERROR_IMPORTS_EXCEEDED){CG_Printf("%s(%i): Trying to exceed maximum number of %i imports.\n",file,line,MAX_IMPORTS);}
     else if(errorNr == ERROR_IMPORT_REDEFINED){CG_Printf("%s(%i): Trying to redefine previously defined import definition '%s'.\n",file,line,string1);}
     else if(errorNr == ERROR_IMPORT_DOUBLED){CG_Printf("%s(%i): Trying to duplicate a previously imported definition under the new name '%s'.\n",file,line,string1);}
     else if(errorNr == ERROR_IMPORT_UNDEFINED){CG_Printf("%s(%i): Undefined import '%s' being referenced.\n",file,line,string1);}
     else if(errorNr == ERROR_DEFINITIONS_EXCEEDED){CG_Printf("%s(%i): Trying to exceed maximum number of %i weapon definitions.\n",file,line,MAX_DEFINES);}
     else if(errorNr == ERROR_DEFINITION_REDEFINED){CG_Printf("%s(%i): Trying to redefine previously defined weapon definition '%s'.\n",file,line,string1);}
     else if(errorNr == ERROR_DEFINITION_UNDEFINED){CG_Printf("%s(%i): Undefined weapon definition '%s' being referenced.\n",file,line,string1);}
     else if(errorNr == ERROR_REDEFINE_IMPORT_AS_DEFINITION){CG_Printf("%s(%i): Trying to redefine previously defined import definition '%s' as a local weapon definition.\n",file,line,string1);}
     else if(errorNr == ERROR_LINK_BOUNDS){CG_Printf("%s(%i): Weapon link out of bounds. Must be in range [1..6].\n",file,line);}
     else if(errorNr == ERROR_LINK_REDEFINED){CG_Printf("%s(%i): Trying to redefine a previously defined weapon link number.\n",file,line);}
     else if(errorNr == ERROR_FIELD_NOT_IN_CATEGORY){CG_Printf("%s(%i): Field '%s' is not supported by category '%s'.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_INVERTED_RANGE){CG_Printf("%s(%i): This range doesn't allow end value '%s' to be larger than start value '%s'.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_OVER_MAXBOUND){CG_Printf("%s(%i): Value '%s' is larger than maximum bound of %s.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_UNDER_MINBOUND){CG_Printf("%s(%i): Value '%s' is smaller than minimum bound of %s.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_OVER_MAXVECTORELEMS){CG_Printf("%s(%i): Element '%s' exceeds maximum storage capacity of %s elements in vector.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_MAX_RECURSION){CG_Printf("%s: Compiler is trying to read beyond maximum recursion depth %i for overriding.\n",file,MAX_RECURSION_DEPTH);}
     else if(errorNr == ERROR_INHERITING_PRIVATE){CG_Printf("%s: Private definition '%s' can not be inherited.\n",file,string1);}
     else if(errorNr == ERROR_IMPORTING_NON_PUBLIC){CG_Printf("%s: Non-public definition '%s' can not be imported for local use.\n",file,string1);}
     else if(errorNr == ERROR_OVERRIDING_WITH_HIGHER_ACCESS){CG_Printf("%s: Definition '%s' may not be declared with higher access than its superclass.\n",file,string1);}
     else{CG_Printf("WEAPONSCRIPT ERROR: Unknown error occured.\n");}
     return qfalse;
 }
References CG_Printf(), ERROR_DEFINITION_REDEFINED, ERROR_DEFINITION_UNDEFINED, ERROR_DEFINITIONS_EXCEEDED, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, ERROR_FLOAT_EXPECTED, ERROR_IMPORT_DOUBLED, ERROR_IMPORT_REDEFINED, ERROR_IMPORT_UNDEFINED, ERROR_IMPORTING_NON_PUBLIC, ERROR_IMPORTS_EXCEEDED, ERROR_INHERITING_PRIVATE, ERROR_INTEGER_EXPECTED, ERROR_INVERTED_RANGE, ERROR_LINK_BOUNDS, ERROR_LINK_REDEFINED, ERROR_MAX_RECURSION, ERROR_OVER_MAXBOUND, ERROR_OVER_MAXVECTORELEMS, ERROR_OVERRIDING_WITH_HIGHER_ACCESS, ERROR_PREMATURE_EOF, ERROR_REDEFINE_IMPORT_AS_DEFINITION, ERROR_STRING_EXPECTED, ERROR_STRING_TOOBIG, ERROR_TOKEN_TOOBIG, ERROR_UNDER_MINBOUND, ERROR_UNEXPECTED_SYMBOL, ERROR_UNKNOWN_SYMBOL, cg_weapGfxScanner_t::filename, cg_weapGfxScanner_t::line, line, MAX_DEFINES, MAX_IMPORTS, MAX_RECURSION_DEPTH, MAX_TOKENSTRING_LENGTH, and qfalse.
Referenced by CG_weapGfx_AddDefinitionRef(), CG_weapGfx_AddImportRef(), CG_weapGfx_AddLinkRef(), CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_FindDefinitionRef(), CG_weapGfx_LoadFile(), CG_weapGfx_NextSym(), CG_weapGfx_Parse(), CG_weapGfx_ParseAnimationRange(), CG_weapGfx_ParseCategories(), CG_weapGfx_ParseDefinition(), CG_weapGfx_ParseDisplayName(), CG_weapGfx_ParseDlight(), CG_weapGfx_ParseDuration(), CG_weapGfx_ParseFields(), CG_weapGfx_ParseIcon(), CG_weapGfx_ParseImports(), CG_weapGfx_ParseLinks(), CG_weapGfx_ParseLoopFx(), CG_weapGfx_ParseLoopParticles(), CG_weapGfx_ParseMarkShader(), CG_weapGfx_ParseMarkSize(), CG_weapGfx_ParseModel(), CG_weapGfx_ParseOnceFx(), CG_weapGfx_ParseParticles(), CG_weapGfx_ParseRemoteDefinition(), CG_weapGfx_ParseRockDebris(), CG_weapGfx_ParseShader(), CG_weapGfx_ParseShockwave(), CG_weapGfx_ParseSize(), CG_weapGfx_ParseSkin(), CG_weapGfx_ParseSmokeParticles(), CG_weapGfx_ParseSoundFx(), CG_weapGfx_ParseSpin(), CG_weapGfx_ParseSpiralOffset(), CG_weapGfx_ParseSpiralShader(), CG_weapGfx_ParseSpiralSize(), CG_weapGfx_ParseTagTo(), CG_weapGfx_ParseTimedFx(), CG_weapGfx_ParseVoiceFx(), and CG_weapGfx_PreParseDefinitions().
CG_weapGfx_LoadFile()
qboolean CG_weapGfx_LoadFile (cg_weapGfxScanner_t * scanner, char * filename)
Definition at line 296 of file cg_weapGfxScanner.c.
{
     int len;
     qhandle_t file;
     Q_strncpyz(scanner->filename,filename,sizeof(scanner->filename));
     len = trap_FS_FOpenFile( filename, &file, FS_READ );
     if(!file){
         return CG_weapGfx_ErrorHandle(ERROR_FILE_NOTFOUND,scanner,filename,NULL);
     }
     if(len >= sizeof(char) * MAX_SCRIPT_LENGTH - 1){
         trap_FS_FCloseFile(file);
         return CG_weapGfx_ErrorHandle(ERROR_FILE_TOOBIG,scanner,NULL,NULL);
     }
     trap_FS_Read(scanner->script,len,file);
     trap_FS_FCloseFile(file);
     scanner->script[len] = '\0';
     scanner->line = 0;
     scanner->pos = scanner->script;
     if(cg_verboseParse.integer){
         CG_Printf("Scriptfile '%s' has been read into memory.\n",filename);
     }
     return qtrue;
 }
References CG_Printf(), cg_verboseParse, CG_weapGfx_ErrorHandle(), ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, file, cg_weapGfxScanner_t::filename, FS_READ, vmCvar_t::integer, cg_weapGfxScanner_t::line, MAX_SCRIPT_LENGTH, NULL, cg_weapGfxScanner_t::pos, Q_strncpyz(), qtrue, cg_weapGfxScanner_t::script, trap_FS_FCloseFile(), trap_FS_FOpenFile(), and trap_FS_Read().
Referenced by CG_weapGfx_Parse(), and CG_weapGfx_ParseRemoteDefinition().
CG_weapGfx_NextSym()
qboolean CG_weapGfx_NextSym (cg_weapGfxScanner_t * scanner, cg_weapGfxToken_t * token)
Definition at line 74 of file cg_weapGfxScanner.c.
{
     // Skip non-relevant characters
     while(1){
         // Leading whitespace
         while(*scanner->pos <= ' '){
             if(!*scanner->pos){break;}
             if(*scanner->pos == '\n'){scanner->line++;}
             scanner->pos++;
         }
         if(scanner->pos[0] == '/' && scanner->pos[1] == '/' ) {
             scanner->pos += 2;
             while(*scanner->pos && *scanner->pos != '\n') {
                 scanner->pos++;
             }
         }
         else if(scanner->pos[0] == '/' && scanner->pos[1] == '*'){
             scanner->pos += 2;
             while(*scanner->pos && (scanner->pos[0] != '*' || scanner->pos[1] != '/')){
                 scanner->pos++;
             }
             if(*scanner->pos){scanner->pos += 2;}
         }
         else{break;}
     }
     if(*scanner->pos == '\"'){
         int len = 0;
         scanner->pos++;
         while(1){
             if(!(*scanner->pos)){
                 return CG_weapGfx_ErrorHandle(ERROR_PREMATURE_EOF,scanner,NULL,NULL);
             }
             if(*scanner->pos == '\n'){scanner->line++;}
             if(*scanner->pos == '\"') {
                 scanner->pos++;
                 break;
             }
             if(len < MAX_TOKENSTRING_LENGTH-1 && *scanner->pos >= ' '){
                 token->stringval[len] = *scanner->pos;
                 len++;
             }
             else{
                 return CG_weapGfx_ErrorHandle(ERROR_STRING_TOOBIG,scanner,NULL,NULL);
             }
             scanner->pos++;
         }
         token->stringval[len] = '\0';
         token->tokenSym = TOKEN_STRING;
         return qtrue;
     }
     if(*scanner->pos >= '0' && *scanner->pos <= '9'){
         int len = 0;
         qboolean dot = qfalse;
         do{
             if(len < (MAX_TOKENSTRING_LENGTH-1)){
                 token->stringval[len] = *scanner->pos;
                 len++;
             }
             else{
                 return CG_weapGfx_ErrorHandle(ERROR_TOKEN_TOOBIG,scanner,NULL,NULL);
             }
             scanner->pos++;
             if(*scanner->pos == '.' && !dot){
                 dot = qtrue;
                 if(len < MAX_TOKENSTRING_LENGTH-1){
                     token->stringval[len] = *scanner->pos;
                     len++;
                 }
                 else{
                     return CG_weapGfx_ErrorHandle(ERROR_TOKEN_TOOBIG,scanner,NULL,NULL);
                 }
                 scanner->pos++;
             }
         }
         while(*scanner->pos >= '0' && *scanner->pos <= '9');
         token->tokenSym = dot ? TOKEN_FLOAT : TOKEN_INTEGER;
         token->stringval[len] = '\0';
         token->floatval = atof(token->stringval);
         token->intval = ceil(token->floatval);
         return qtrue;
     }
     switch(*scanner->pos){
         case '=':
             scanner->pos++;
             token->stringval[0] = '=';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_EQUALS;
             return qtrue;
         break;
         case '+':
             scanner->pos++;
             token->stringval[0] = '+';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_PLUS;
             return qtrue;
         break;
         case '|':
             scanner->pos++;
             token->stringval[0] = '|';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_COLON;
             return qtrue;
         break;
         case '{':
             scanner->pos++;
             token->stringval[0] = '{';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_OPENBLOCK;
             return qtrue;
         break;
         case '}':
             scanner->pos++;
             token->stringval[0] = '}';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_CLOSEBLOCK;
             return qtrue;
         break;
         case '(':
             scanner->pos++;
             token->stringval[0] = '(';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_OPENVECTOR;
             return qtrue;
         break;
         case ')':
             scanner->pos++;
             token->stringval[0] = ')';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_CLOSEVECTOR;
             return qtrue;
         break;
         case '[':
             scanner->pos++;
             token->stringval[0] = '[';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_OPENRANGE;
             return qtrue;
         break;
         case ']':
             scanner->pos++;
             token->stringval[0] = ']';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_CLOSERANGE;
             return qtrue;
         break;
     }
     // Handle keywords
     {
         int len = 0;
         int i;
         while(*scanner->pos >= 'a' && *scanner->pos <= 'z' || *scanner->pos >= 'A' && *scanner->pos <= 'Z'){
             if(len > MAX_TOKENSTRING_LENGTH-1){
                 return CG_weapGfx_ErrorHandle(ERROR_TOKEN_TOOBIG,scanner,NULL,NULL);
             }
             token->stringval[len] = *scanner->pos;
             len++;
             scanner->pos++;
         }
         token->stringval[len] = '\0';
         // Check if the keyword is a category.
         for(i=0;strcmp(cg_weapGfxCategories[i],"");i++){
             if(!Q_stricmp(cg_weapGfxCategories[i],token->stringval)){
                 token->identifierIndex = i;
                 token->tokenSym = TOKEN_CATEGORY;
                 return qtrue;
             }
         }
         // Check if the keyword is a field.
         for(i=0;strcmp(cg_weapGfxFields[i].fieldname,"");i++){
             // NOTE:
             // Need to do this comparison case independantly. Q_stricmp is case
             // independant, so use this instead of standard library function strcmp.
             if(!Q_stricmp(cg_weapGfxFields[i].fieldname,token->stringval)){
                 token->identifierIndex = i;
                 token->tokenSym = TOKEN_FIELD;
                 return qtrue;
             }
         }
         // Check if the keyword is 'import', 'private', 'protected', 'public',
         // 'weapon', 'true', 'false', or 'null'.
         if(!Q_stricmp(token->stringval,"import")){
             token->tokenSym = TOKEN_IMPORT;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"private")){
             token->tokenSym = TOKEN_PRIVATE;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"protected")){
             token->tokenSym = TOKEN_PROTECTED;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"public")){
             token->tokenSym = TOKEN_PUBLIC;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"weapon")){
             token->tokenSym = TOKEN_WEAPON;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"true")){
             token->tokenSym = TOKEN_TRUE;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"false")){
             token->tokenSym = TOKEN_FALSE;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"null")){
             token->tokenSym = TOKEN_NULL;
             return qtrue;
         }
     }
     if(*scanner->pos == '\0'){
         token->tokenSym = TOKEN_EOF;
         return qfalse;
     }
     return CG_weapGfx_ErrorHandle(ERROR_UNKNOWN_SYMBOL,scanner,token->stringval,NULL);
 }
References CG_weapGfx_ErrorHandle(), cg_weapGfxCategories, cg_weapGfxFields, ERROR_PREMATURE_EOF, ERROR_STRING_TOOBIG, ERROR_TOKEN_TOOBIG, ERROR_UNKNOWN_SYMBOL, cg_weapGfxScanner_t::line, MAX_TOKENSTRING_LENGTH, NULL, cg_weapGfxScanner_t::pos, Q_stricmp(), qfalse, qtrue, TOKEN_CATEGORY, TOKEN_CLOSEBLOCK, TOKEN_CLOSERANGE, TOKEN_CLOSEVECTOR, TOKEN_COLON, TOKEN_EOF, TOKEN_EQUALS, TOKEN_FALSE, TOKEN_FIELD, TOKEN_FLOAT, TOKEN_IMPORT, TOKEN_INTEGER, TOKEN_NULL, TOKEN_OPENBLOCK, TOKEN_OPENRANGE, TOKEN_OPENVECTOR, TOKEN_PLUS, TOKEN_PRIVATE, TOKEN_PROTECTED, TOKEN_PUBLIC, TOKEN_STRING, TOKEN_TRUE, and TOKEN_WEAPON.
Referenced by CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_Parse(), CG_weapGfx_ParseImports(), CG_weapGfx_ParseLinks(), CG_weapGfx_ParseRemoteDefinition(), and CG_weapGfx_PreParseDefinitions().
Variable Documentation
cg_weapGfxCategories
char* cg_weapGfxCategories[] = {"Charge","Explosion","Struggle","Missile","Flash","Trail","Hud",""}
Definition at line 4 of file cg_weapGfxScanner.c.
Referenced by CG_weapGfx_NextSym(), CG_weapGfx_ParseAnimationRange(), CG_weapGfx_ParseDisplayName(), CG_weapGfx_ParseDlight(), CG_weapGfx_ParseDuration(), CG_weapGfx_ParseIcon(), CG_weapGfx_ParseLoopFx(), CG_weapGfx_ParseLoopParticles(), CG_weapGfx_ParseMarkShader(), CG_weapGfx_ParseMarkSize(), CG_weapGfx_ParseModel(), CG_weapGfx_ParseOnceFx(), CG_weapGfx_ParseParticles(), CG_weapGfx_ParseRockDebris(), CG_weapGfx_ParseShader(), CG_weapGfx_ParseShockwave(), CG_weapGfx_ParseSize(), CG_weapGfx_ParseSkin(), CG_weapGfx_ParseSmokeParticles(), CG_weapGfx_ParseSoundFx(), CG_weapGfx_ParseSpin(), CG_weapGfx_ParseSpiralOffset(), CG_weapGfx_ParseSpiralShader(), CG_weapGfx_ParseSpiralSize(), CG_weapGfx_ParseTagTo(), CG_weapGfx_ParseTimedFx(), and CG_weapGfx_ParseVoiceFx().
cg_weapGfxFields
cg_weapGfxField_t cg_weapGfxFields[]
Initial value:
= {
    {"model",         CG_weapGfx_ParseModel},
    {"skin",          CG_weapGfx_ParseSkin},
    {"shader",        CG_weapGfx_ParseShader},
    {"animationRange",CG_weapGfx_ParseAnimationRange},
    {"size",          CG_weapGfx_ParseSize},
    {"light",         CG_weapGfx_ParseDlight},
    {"spin",          CG_weapGfx_ParseSpin},
    {"tagTo",         CG_weapGfx_ParseTagTo},
    {"soundFx",       CG_weapGfx_ParseSoundFx},
    {"voiceFx",       CG_weapGfx_ParseVoiceFx},
    {"loopFx",        CG_weapGfx_ParseLoopFx},
    {"timedFx",       CG_weapGfx_ParseTimedFx},
    {"onceFx",        CG_weapGfx_ParseOnceFx},
    {"duration",      CG_weapGfx_ParseDuration},
    {"shockwave",     CG_weapGfx_ParseShockwave},
    {"markShader",    CG_weapGfx_ParseMarkShader},
    {"markSize",      CG_weapGfx_ParseMarkSize},
    {"noRockDebris",  CG_weapGfx_ParseRockDebris},
    {"particles",     CG_weapGfx_ParseParticles},
    {"loopParticles", CG_weapGfx_ParseLoopParticles},
    {"smokeParticles",CG_weapGfx_ParseSmokeParticles},
    {"spiralShader",  CG_weapGfx_ParseSpiralShader},
    {"spiralSize",    CG_weapGfx_ParseSpiralSize},
    {"spiralOffset",  CG_weapGfx_ParseSpiralOffset},
    {"icon",          CG_weapGfx_ParseIcon},
    {"displayName",   CG_weapGfx_ParseDisplayName},
    {"",              CG_weapGfx_ParseDummy}
}
Definition at line 5 of file cg_weapGfxScanner.c.
Referenced by CG_weapGfx_NextSym(), CG_weapGfx_ParseAnimationRange(), CG_weapGfx_ParseDisplayName(), CG_weapGfx_ParseDlight(), CG_weapGfx_ParseDuration(), CG_weapGfx_ParseFields(), CG_weapGfx_ParseIcon(), CG_weapGfx_ParseLoopFx(), CG_weapGfx_ParseLoopParticles(), CG_weapGfx_ParseMarkShader(), CG_weapGfx_ParseMarkSize(), CG_weapGfx_ParseModel(), CG_weapGfx_ParseOnceFx(), CG_weapGfx_ParseParticles(), CG_weapGfx_ParseRockDebris(), CG_weapGfx_ParseShader(), CG_weapGfx_ParseShockwave(), CG_weapGfx_ParseSize(), CG_weapGfx_ParseSkin(), CG_weapGfx_ParseSmokeParticles(), CG_weapGfx_ParseSoundFx(), CG_weapGfx_ParseSpin(), CG_weapGfx_ParseSpiralOffset(), CG_weapGfx_ParseSpiralShader(), CG_weapGfx_ParseSpiralSize(), CG_weapGfx_ParseTagTo(), CG_weapGfx_ParseTimedFx(), and CG_weapGfx_ParseVoiceFx().