ZEQ2-Lite: Source/Engine/libspeex/speex.c File Reference
speex.c File Reference
#include "modes.h"
#include <math.h>
#include "os_support.h"
Macros
#define MAX_IN_SAMPLES 640
#define NULL 0
Functions
int nb_mode_query (const void *mode, int request, void *ptr)
int speex_decode (void *state, SpeexBits *bits, float *out)
Uses an existing decoder state to decode one frame of speech from bit-stream bits.
int speex_decode_int (void *state, SpeexBits *bits, spx_int16_t *out)
Uses an existing decoder state to decode one frame of speech from bit-stream bits.
int speex_decode_native (void *state, SpeexBits *bits, spx_word16_t *out)
int speex_decoder_ctl (void *state, int request, void *ptr)
Used like the ioctl function to control the encoder parameters.
void speex_decoder_destroy (void *state)
Frees all resources associated to an existing decoder state.
void * speex_decoder_init (const SpeexMode *mode)
Returns a handle to a newly created decoder state structure.
int speex_encode (void *state, float *in, SpeexBits *bits)
Uses an existing encoder state to encode one frame of speech pointed to by "in".
int speex_encode_int (void *state, spx_int16_t *in, SpeexBits *bits)
Uses an existing encoder state to encode one frame of speech pointed to by "in".
int speex_encode_native (void *state, spx_word16_t *in, SpeexBits *bits)
int speex_encoder_ctl (void *state, int request, void *ptr)
Used like the ioctl function to control the encoder parameters.
void speex_encoder_destroy (void *state)
Frees all resources associated to an existing Speex encoder state.
void * speex_encoder_init (const SpeexMode *mode)
Returns a handle to a newly created Speex encoder state structure.
int speex_lib_ctl (int request, void *ptr)
Functions for controlling the behavior of libspeex.
Macro Definition Documentation
MAX_IN_SAMPLES
#define MAX_IN_SAMPLES 640
Definition at line 47 of file speex.c.
NULL
#define NULL 0
Definition at line 44 of file speex.c.
Function Documentation
nb_mode_query()
int nb_mode_query (const void * mode, int request, void * ptr)
Definition at line 192 of file speex.c.
 {
    const SpeexNBMode *m = (const SpeexNBMode*)mode;
    switch (request)
    {
    case SPEEX_MODE_FRAME_SIZE:
       *((int*)ptr)=m->frameSize;
       break;
    case SPEEX_SUBMODE_BITS_PER_FRAME:
       if (*((int*)ptr)==0)
          *((int*)ptr) = NB_SUBMODE_BITS+1;
       else if (m->submodes[*((int*)ptr)]==NULL)
          *((int*)ptr) = -1;
       else
          *((int*)ptr) = m->submodes[*((int*)ptr)]->bits_per_frame;
       break;
    default:
       speex_warning_int("Unknown nb_mode_query request: ", request);
       return -1;
    }
    return 0;
 }
References m, NB_SUBMODE_BITS, NULL, ptr(), SPEEX_MODE_FRAME_SIZE, SPEEX_SUBMODE_BITS_PER_FRAME, and speex_warning_int().
speex_decode_native()
int speex_decode_native (void * state, SpeexBits * bits, spx_word16_t * out)
Definition at line 78 of file speex.c.
 {
    return (*((SpeexMode**)state))->dec(state, bits, out);
 }
References bits(), and out.
Referenced by sb_decode().
speex_encode_native()
int speex_encode_native (void * state, spx_word16_t * in, SpeexBits * bits)
Definition at line 73 of file speex.c.
 {
    return (*((SpeexMode**)state))->enc(state, in, bits);
 }
References bits().
Referenced by sb_encode().