ZEQ2-Lite: Tools/zMesh Exporter/config.h File Reference
config.h File Reference
Data Structures
struct zSkel_Config_Anim_t
struct zSkel_Config_BoneSets_t
struct zSkel_Config_Mesh_t
struct zSkel_Config_t
Macros
#define ZSKEL_MAXANIMS 256
#define ZSKEL_MAXBONES 128
#define ZSKEL_MAXBONESETS 3
#define ZSKEL_MAXMESHES 32
#define ZSKEL_VERSION 1
Typedefs
typedef char zSkel_Config_BoneName_t[32]
Enumerations
enum zSkel_Config_Mode_t {
ZSC_GENERAL, ZSC_SKELETON, ZSC_BONESET, ZSC_MESH,
ZSC_ANIM
}
Functions
void LoadCFG (const char srcFileName[512])
void LoadCFG_Anim (void)
void LoadCFG_BoneSet (void)
void LoadCFG_General (void)
void LoadCFG_Mesh (void)
void LoadCFG_Print (void)
void LoadCFG_Skeleton (void)
Variables
zSkel_Config_t config
Macro Definition Documentation
ZSKEL_MAXANIMS
#define ZSKEL_MAXANIMS 256
Definition at line 16 of file config.h.
ZSKEL_MAXBONES
#define ZSKEL_MAXBONES 128
Definition at line 13 of file config.h.
ZSKEL_MAXBONESETS
#define ZSKEL_MAXBONESETS 3
Definition at line 14 of file config.h.
ZSKEL_MAXMESHES
#define ZSKEL_MAXMESHES 32
Definition at line 15 of file config.h.
ZSKEL_VERSION
#define ZSKEL_VERSION 1
Definition at line 12 of file config.h.
Typedef Documentation
zSkel_Config_BoneName_t
typedef char zSkel_Config_BoneName_t[32]
Definition at line 19 of file config.h.
Enumeration Type Documentation
zSkel_Config_Mode_t
enum zSkel_Config_Mode_t
Enumerator
ZSC_GENERAL
ZSC_SKELETON
ZSC_BONESET
ZSC_MESH
ZSC_ANIM
Definition at line 65 of file config.h.
              {
     ZSC_GENERAL,
     ZSC_SKELETON,
     ZSC_BONESET,
     ZSC_MESH,
     ZSC_ANIM
 } zSkel_Config_Mode_t;
Function Documentation
LoadCFG()
void LoadCFG (const char srcFileName[512])
Definition at line 563 of file zskeleton.c.
{
     int i,cfgVer,flag = 0;
     int animationIndex = 0;
     char cfgFileName[512];
     // Mode List
     // See config.h
     vec_t *moff = &modelOffset;
     LoadCFG_Defaults();
     strcpy(cfgFileName,srcFileName);
     StripExtension(cfgFileName);
     DefaultExtension(cfgFileName,".cfg");
     LoadScriptFile(cfgFileName);
     while(GetToken(qtrue)){
         //if(!strlen(token)){continue;}
         if(verbose && !debug) {
         }
         if(!stricmp(token,"General")){
             configMode = ZSC_GENERAL;
             continue;
         }
         if(!stricmp(token,"Skeleton")){
             configMode = ZSC_SKELETON;
             continue;
         }
         if(!stricmp(token,"Animations")){
             configMode = ZSC_ANIM;
             continue;
         }
         if(!stricmp(token,"Meshes")){
             configMode = ZSC_MESH;
             continue;
         }
         else{
             if(configMode == ZSC_GENERAL){
                 LoadCFG_General();
             }
             else if(configMode == ZSC_SKELETON){
                 LoadCFG_Skeleton();
             }
             else if(configMode == ZSC_MESH){
                 LoadCFG_Mesh();
             }
             else if(configMode == ZSC_ANIM){
                 LoadCFG_Anim();
             }
         }
     }
 }
References configMode, debug, DefaultExtension(), GetToken(), LoadCFG_Anim(), LoadCFG_Defaults(), LoadCFG_General(), LoadCFG_Mesh(), LoadCFG_Skeleton(), LoadScriptFile(), modelOffset, qtrue, strcpy(), stricmp(), StripExtension(), verbose, ZSC_ANIM, ZSC_GENERAL, ZSC_MESH, and ZSC_SKELETON.
Referenced by main().
LoadCFG_Anim()
void LoadCFG_Anim (void)
Definition at line 756 of file zskeleton.c.
 {
     // Blah blah blah, same comments as LoadCFG_Mesh until more functionallity is added/needed
     if(!stricmp(token,"Anim"))
     {
         GetToken(qfalse);
         if(config.numAnims < ZSKEL_MAXMESHES)
         {
             int animID = config.numAnims;
             strcpy(config.anims[animID].name, token);
             strcpy(config.anims[animID].input, token);
             strcpy(config.anims[animID].output, token);
             config.anims[animID].animOffset[0] = 0.0f;
             config.anims[animID].animOffset[1] = 0.0f;
             config.anims[animID].animOffset[2] = 0.0f;
             config.numAnims++;
             if(config.debug) printf("LoadCFG_Anim: Adding Anim %i: \"%s\"\n",config.numAnims,token);
         }
         else
         {
             printf(" LoadCFG_Anim: Can Not Add Anim \"%s\" - Max Anims Exceeded %i\n",token, config.numAnims);
         }
     }
     else if(!stricmp(token,"input"))
     {
         if(config.numAnims == 0) Error(" LoadCFG_Anim: Input for no anim: \"Output %s\"\n",token);
         else
         {
             GetToken(qfalse);
             strcpy(config.anims[config.numAnims - 1].input,token);
             if(config.debug) printf(" LoadCFG_Anim: Setting anim \"%s\" input to \"%s\"\n",config.anims[config.numAnims - 1].name,token);
         }
     }
     else if(!stricmp(token,"output"))
     {
         if(config.numAnims == 0) Error(" LoadCFG_Anim: Output for no anim: \"Output %s\"\n",token);
         else
         {
             GetToken(qfalse);
             strcpy(config.anims[config.numAnims - 1].output,token);
             if(config.debug) printf(" LoadCFG_Anim: Setting anim \"%s\" output to \"%s\"\n",config.anims[config.numAnims - 1].name,token);
         }
     }
     if(!stricmp(token,"offset")){ // Mesh has it's own offset! :o
         vec3_t *moff;                                           // Parse1DMatrix takes a pointer!
         moff = &config.anims[config.numAnims - 1].animOffset; // So Let's make one!
         Parse1DMatrix(3,moff);
         config.anims[config.numAnims - 1].animOffset[2] = -config.anims[config.numAnims - 1].animOffset[2]; // Invert the Z axis. 'cos otherwise it's wrong
         if(config.debug) printf(" LoadCFG_Anim: Setting anim \"%s\" offset to {%f, %f, %f}\n", config.anims[config.numAnims - 1].animOffset[0], config.anims[config.numAnims - 1].animOffset[1], config.anims[config.numAnims - 1].animOffset[2]);
     }
 }
References zSkel_Config_Anim_t::animOffset, zSkel_Config_t::anims, config, zSkel_Config_t::debug, Error, GetToken(), zSkel_Config_Anim_t::input, zSkel_Config_Anim_t::name, zSkel_Config_t::numAnims, zSkel_Config_Anim_t::output, Parse1DMatrix(), printf(), qfalse, strcpy(), stricmp(), and ZSKEL_MAXMESHES.
Referenced by LoadCFG().
LoadCFG_BoneSet()
void LoadCFG_BoneSet (void)
LoadCFG_General()
void LoadCFG_General (void)
Definition at line 617 of file zskeleton.c.
 {
     if(!stricmp(token,"offset")){
         vec3_t *moff;
         moff = &config.originOffset;
         Parse1DMatrix(3,moff);
         config.originOffset[2] = -config.originOffset[2];
     }
     else if(!stricmp(token,"silent") && !config.debug)
     {
         config.verbose = qfalse;
     }
     else if(!stricmp(token,"debug"))
     {
         config.debug = qtrue;
         config.verbose = qtrue;
         printf(" LoadCFG_General: Debug Enabled\n");
     }
     else if(!stricmp(token,"overwrite"))
     {
         config.forceCompile = qtrue;
     }
     else if(!stricmp(token,"DefaultExtension"))
     {
         GetToken(qfalse);
         if(!stricmp(token, "Anim"))
         {
             GetToken(qfalse);
             strcpy(config.animExtension,token);
         }
         else if(!stricmp(token, "Mesh"))
         {
             GetToken(qfalse);
             strcpy(config.meshExtension,token);
         }
     }
 }
References zSkel_Config_t::animExtension, config, zSkel_Config_t::debug, zSkel_Config_t::forceCompile, GetToken(), zSkel_Config_t::meshExtension, zSkel_Config_t::originOffset, Parse1DMatrix(), printf(), qfalse, qtrue, strcpy(), stricmp(), and zSkel_Config_t::verbose.
Referenced by LoadCFG().
LoadCFG_Mesh()
void LoadCFG_Mesh (void)
Definition at line 687 of file zskeleton.c.
 {
     if(!stricmp(token,"Mesh"))
     {
         // Grab Mesh Name
         GetToken(qfalse);
         //Check there's room for another mesh
         if(config.numMeshes < ZSKEL_MAXMESHES)
         {
             // Save Typing
             int meshID = config.numMeshes;
             // Set Mesh Name
             strcpy(config.meshes[meshID].name, token);
             // Default input and output to the mesh name
             strcpy(config.meshes[meshID].input,token);
             strcpy(config.meshes[meshID].output,token);
             // Zero Mesh Offset
             config.meshes[meshID].meshOffset[0] = 0.0f;
             config.meshes[meshID].meshOffset[1] = 0.0f;
             config.meshes[meshID].meshOffset[2] = 0.0f;
             // Increase Mesh Counter!
             config.numMeshes++;
             if(config.debug) printf("LoadCFG_Mesh: Adding Mesh %i: \"%s\"\n",config.numMeshes,token);
         }
         else
         {
             // Oh shit! Too Many Meshes! Do Something About it!
             Error(" LoadCFG_Mesh: Can Not Add Mesh \"%s\" - Max Meshes Exceeded %i\n",token, config.numMeshes);
         }
     }
     else if(!stricmp(token,"input"))
     {
         //Check we have a mesh to declare an input for!
         if(config.numMeshes == 0) Error(" LoadCFG_Mesh: Input for no mesh: \"Output %s\"\n",token); // Oh shit! There's no mesh!
         else
         {
             // Grab input file name!
             GetToken(qfalse);
             // Set the file name!
             strcpy(config.meshes[config.numMeshes - 1].input,token);
             if(config.debug) printf(" LoadCFG_Mesh: Setting mesh \"%s\" input to \"%s\"\n",config.meshes[config.numMeshes - 1].name,token);
         }
     }
     else if(!stricmp(token,"output"))
     {
         // See comments for "input" :)
         if(config.numMeshes == 0) Error(" LoadCFG_Mesh: Output for no mesh: \"Output %s\"\n",token);
         else
         {
             GetToken(qfalse);
             strcpy(config.meshes[config.numMeshes - 1].output,token);
             if(config.debug) printf(" LoadCFG_Mesh: Setting mesh \"%s\" output to \"%s\"\n",config.meshes[config.numMeshes - 1].name,token);
         }
     }
     if(!stricmp(token,"offset")){ // Mesh has it's own offset! :o
         vec3_t *moff;                                           // Parse1DMatrix takes a pointer!
         moff = &config.meshes[config.numMeshes - 1].meshOffset; // So Let's make one!
         Parse1DMatrix(3,moff);
         config.meshes[config.numMeshes - 1].meshOffset[2] = -config.meshes[config.numMeshes - 1].meshOffset[2]; // Invert the Z axis. 'cos otherwise it's wrong
     }
 }
References config, zSkel_Config_t::debug, Error, GetToken(), zSkel_Config_Mesh_t::input, zSkel_Config_t::meshes, zSkel_Config_Mesh_t::meshOffset, zSkel_Config_Mesh_t::name, zSkel_Config_t::numMeshes, zSkel_Config_Mesh_t::output, Parse1DMatrix(), printf(), qfalse, strcpy(), stricmp(), and ZSKEL_MAXMESHES.
Referenced by LoadCFG().
LoadCFG_Print()
void LoadCFG_Print (void)
Definition at line 503 of file zskeleton.c.
 {
     printf("Config:\n");
     printf("   config.debug        = %i\n", config.debug);
     printf("   config.verbose      = %i\n", config.verbose);
     printf("   config.forceCompile = %i\n", config.forceCompile);
     printf("   config.animExtension= \"%s\"\n", config.animExtension);
     printf("   config.meshExtension= \"%s\"\n", config.meshExtension);
     printf("   config.originOffset = {%f, %f, %f}\n", config.originOffset[0], config.originOffset[1], config.originOffset[2]);
     printf("   config.numAnims     = %i\n", config.numAnims);
     if(config.numAnims > 0)
     {
         int i;
         printf("   Animations:\n");
         for(i = 0; i < config.numAnims; i++)
         {
             printf("      Anim #%i\n",i+1);
             printf("         config.anims[%i].name = \"%s\"\n",i,config.anims[i].name);
             printf("         config.anims[%i].input = \"%s\"\n",i,config.anims[i].input);
             printf("         config.anims[%i].output = \"%s\"\n",i,config.anims[i].output);
             printf("         config.anims[%i].animOffset = {%f, %f, %f}\n",i,config.anims[i].animOffset[0], config.anims[i].animOffset[2], config.anims[i].animOffset[2]);
         }
     }
     printf("   config.numMeshes     = %i\n", config.numMeshes);
     if(config.numMeshes > 0)
     {
         int i;
         printf("   Meshes:\n");
         for(i = 0; i < config.numMeshes; i++)
         {
             printf("      Mesh #%i\n",i+1);
             printf("         config.meshes[%i].name = \"%s\"\n",i,config.meshes[i].name);
             printf("         config.meshes[%i].input = \"%s\"\n",i,config.meshes[i].input);
             printf("         config.meshes[%i].output = \"%s\"\n",i,config.meshes[i].output);
             printf("         config.meshes[%i].meshOffset = {%f, %f, %f}\n",i,config.meshes[i].meshOffset[0], config.meshes[i].meshOffset[2], config.meshes[i].meshOffset[2]);
         }
     }
     printf("   config.numBoneSets     = %i\n", config.numBoneSets);
     if(config.numBoneSets > 0)
     {
         int i;
         printf("   BoneSets:\n");
         for(i = 0; i < config.numBoneSets; i++)
         {
             printf("      BoneSet #%i\n",i+1);
             printf("         config.boneSets[%i].name = \"%s\"\n",i,config.boneSets[i].name);
             printf("         config.boneSets[%i].numBones = %i\n",i,config.boneSets[i].numBones);
             if(config.boneSets[i].numBones > 0)
             {
                 int j;
                 printf("         Bones:\n");
                 for(j = 0; j < config.boneSets[i].numBones; j++)
                 {
                     printf("            config.boneSets[%i].bones[%i] = \"%s\"\n",i, j, config.boneSets[i].bones[j]);
                 }
             }
         }
     }
 }
References zSkel_Config_t::animExtension, zSkel_Config_Anim_t::animOffset, zSkel_Config_t::anims, zSkel_Config_BoneSets_t::bones, zSkel_Config_t::boneSets, config, zSkel_Config_t::debug, zSkel_Config_t::forceCompile, zSkel_Config_Mesh_t::input, zSkel_Config_Anim_t::input, zSkel_Config_t::meshes, zSkel_Config_t::meshExtension, zSkel_Config_Mesh_t::meshOffset, zSkel_Config_Mesh_t::name, zSkel_Config_Anim_t::name, zSkel_Config_BoneSets_t::name, zSkel_Config_t::numAnims, zSkel_Config_BoneSets_t::numBones, zSkel_Config_t::numBoneSets, zSkel_Config_t::numMeshes, zSkel_Config_t::originOffset, zSkel_Config_Mesh_t::output, zSkel_Config_Anim_t::output, printf(), and zSkel_Config_t::verbose.
Referenced by main().
LoadCFG_Skeleton()
void LoadCFG_Skeleton (void)
Definition at line 664 of file zskeleton.c.
 {
     if(!stricmp(token,"BoneSet")){
         GetToken(qfalse);
         if(config.numBoneSets < ZSKEL_MAXBONESETS)
         {
             strcpy(config.boneSets[config.numBoneSets].name, token);
             currentBoneSet = config.numBoneSets;
             config.numBoneSets++;
         }
         else
         {
             printf(" LoadCFG_Skeleton: Can Not Add BoneSet \"%s\" - Max BoneSets Exceeded %i\n",token, config.numBoneSets);
         }
     }
     else if(!stricmp(token,"Bone"))
     {
         GetToken(qfalse);
         LoadCFG_AddBoneToSet(currentBoneSet,token);
         if(config.debug) printf("LoadCFG_Skeleton: Adding bone \"%s\" to boneset \"%s\"\n",token,config.boneSets[currentBoneSet].name);
     }
 }
References zSkel_Config_t::boneSets, config, currentBoneSet, zSkel_Config_t::debug, GetToken(), LoadCFG_AddBoneToSet(), zSkel_Config_BoneSets_t::name, zSkel_Config_t::numBoneSets, printf(), qfalse, strcpy(), stricmp(), and ZSKEL_MAXBONESETS.
Referenced by LoadCFG().
Variable Documentation
config
zSkel_Config_t config
Definition at line 14 of file zskeleton.c.
Referenced by CG_AddAuraToScene(), CG_Aura_AddDebris(), CG_Aura_AddDLight(), CG_Aura_AddParticleSystem(), CG_Aura_AddSounds(), CG_Aura_AddTrail(), CG_Aura_BuildConvexHull(), CG_Aura_BuildTailPoint(), CG_Aura_ConvexHullRender(), CG_Aura_DimLight(), CG_Aura_DrawInnerSpike(), CG_Aura_GetHullPoints(), CG_AuraSpike(), CG_AuraStart(), CG_LerpSpike(), CL_GetGlconfig(), DoAnims(), DoMeshes(), FixCoords(), GetFlagForBone(), LoadCFG_AddBoneToSet(), LoadCFG_Anim(), LoadCFG_Defaults(), LoadCFG_General(), LoadCFG_Mesh(), LoadCFG_Print(), LoadCFG_Skeleton(), LoadSMD(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), LoadSMD_ParseTriangles(), main(), SaveAnimation(), and SaveMesh().