ZEQ2-Lite: Engine/jpeg-8c/jcmainct.c File Reference
jcmainct.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_main_controller
Macros
#define JPEG_INTERNALS
Typedefs
typedef my_main_controller * my_main_ptr
Functions
jinit_c_main_controller (j_compress_ptr cinfo, boolean need_full_buffer)
METHODDEF (void)
process_data_simple_main (j_compress_ptr cinfo, JSAMPARRAY input_buf, JDIMENSION *in_row_ctr, JDIMENSION in_rows_avail)
Macro Definition Documentation
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 13 of file jcmainct.c.
Typedef Documentation
my_main_ptr
typedef my_main_controller* my_main_ptr
Definition at line 50 of file jcmainct.c.
Function Documentation
jinit_c_main_controller()
jinit_c_main_controller (j_compress_ptr cinfo, boolean need_full_buffer)
Definition at line 245 of file jcmainct.c.
 {
   my_main_ptr main_ptr;
   int ci;
   jpeg_component_info *compptr;
   main_ptr = (my_main_ptr)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 SIZEOF(my_main_controller));
   cinfo->main = (struct jpeg_c_main_controller *) main_ptr;
   main_ptr->pub.start_pass = start_pass_main;
   /* We don't need to create a buffer in raw-data mode. */
   if (cinfo->raw_data_in)
     return;
   /* Create the buffer.  It holds downsampled data, so each component
    * may be of a different size.
    */
   if (need_full_buffer) {
 #ifdef FULL_MAIN_BUFFER_SUPPORTED
     /* Allocate a full-image virtual array for each component */
     /* Note we pad the bottom to a multiple of the iMCU height */
     for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
      ci++, compptr++) {
       main_ptr->whole_image[ci] = (*cinfo->mem->request_virt_sarray)
     ((j_common_ptr) cinfo, JPOOL_IMAGE, FALSE,
      compptr->width_in_blocks * compptr->DCT_h_scaled_size,
      (JDIMENSION) jround_up((long) compptr->height_in_blocks,
                 (long) compptr->v_samp_factor) * DCTSIZE,
      (JDIMENSION) (compptr->v_samp_factor * compptr->DCT_v_scaled_size));
     }
 #else
     ERREXIT(cinfo, JERR_BAD_BUFFER_MODE);
 #endif
   } else {
 #ifdef FULL_MAIN_BUFFER_SUPPORTED
     main_ptr->whole_image[0] = NULL; /* flag for no virtual arrays */
 #endif
     /* Allocate a strip buffer for each component */
     for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
      ci++, compptr++) {
       main_ptr->buffer[ci] = (*cinfo->mem->alloc_sarray)
     ((j_common_ptr) cinfo, JPOOL_IMAGE,
      compptr->width_in_blocks * compptr->DCT_h_scaled_size,
      (JDIMENSION) (compptr->v_samp_factor * compptr->DCT_v_scaled_size));
     }
   }
 }
References my_main_controller::buffer, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, DCTSIZE, ERREXIT, FALSE, jpeg_component_info::height_in_blocks, JPOOL_IMAGE, jround_up(), long(), need_full_buffer, NULL, my_main_controller::pub, SIZEOF, start_pass_main(), jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
Referenced by jinit_compress_master().
METHODDEF()
METHODDEF (void)
Definition at line 54 of file jcmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   /* Do nothing in raw-data mode. */
   if (cinfo->raw_data_in)
     return;
   main_ptr->cur_iMCU_row = 0;   /* initialize counters */
   main_ptr->rowgroup_ctr = 0;
   main_ptr->suspended = FALSE;
   main_ptr->pass_mode = pass_mode;  /* save mode for use by process_data */
   switch (pass_mode) {
   case JBUF_PASS_THRU:
 #ifdef FULL_MAIN_BUFFER_SUPPORTED
     if (main_ptr->whole_image[0] != NULL)
       ERREXIT(cinfo, JERR_BAD_BUFFER_MODE);
 #endif
     main_ptr->pub.process_data = process_data_simple_main;
     break;
 #ifdef FULL_MAIN_BUFFER_SUPPORTED
   case JBUF_SAVE_SOURCE:
   case JBUF_CRANK_DEST:
   case JBUF_SAVE_AND_PASS:
     if (main_ptr->whole_image[0] == NULL)
       ERREXIT(cinfo, JERR_BAD_BUFFER_MODE);
     main_ptr->pub.process_data = process_data_buffer_main;
     break;
 #endif
   default:
     ERREXIT(cinfo, JERR_BAD_BUFFER_MODE);
     break;
   }
 }
process_data_simple_main()
process_data_simple_main (j_compress_ptr cinfo, JSAMPARRAY input_buf, JDIMENSION * in_row_ctr, JDIMENSION in_rows_avail)
Definition at line 113 of file jcmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   while (main_ptr->cur_iMCU_row < cinfo->total_iMCU_rows) {
     /* Read input data if we haven't filled the main buffer yet */
     if (main_ptr->rowgroup_ctr < (JDIMENSION) cinfo->min_DCT_v_scaled_size)
       (*cinfo->prep->pre_process_data) (cinfo,
                     input_buf, in_row_ctr, in_rows_avail,
                     main_ptr->buffer, &main_ptr->rowgroup_ctr,
                     (JDIMENSION) cinfo->min_DCT_v_scaled_size);
     /* If we don't have a full iMCU row buffered, return to application for
      * more data.  Note that preprocessor will always pad to fill the iMCU row
      * at the bottom of the image.
      */
     if (main_ptr->rowgroup_ctr != (JDIMENSION) cinfo->min_DCT_v_scaled_size)
       return;
     /* Send the completed row to the compressor */
     if (! (*cinfo->coef->compress_data) (cinfo, main_ptr->buffer)) {
       /* If compressor did not consume the whole row, then we must need to
        * suspend processing and return to the application.  In this situation
        * we pretend we didn't yet consume the last input row; otherwise, if
        * it happened to be the last row of the image, the application would
        * think we were done.
        */
       if (! main_ptr->suspended) {
     (*in_row_ctr)--;
     main_ptr->suspended = TRUE;
       }
       return;
     }
     /* We did finish the row.  Undo our little suspension hack if a previous
      * call suspended; then mark the main buffer empty.
      */
     if (main_ptr->suspended) {
       (*in_row_ctr)++;
       main_ptr->suspended = FALSE;
     }
     main_ptr->rowgroup_ctr = 0;
     main_ptr->cur_iMCU_row++;
   }
 }
References my_main_controller::buffer, my_main_controller::cur_iMCU_row, FALSE, my_main_controller::rowgroup_ctr, my_main_controller::suspended, and TRUE.