ZEQ2-Lite: Source/Engine/jpeg-8c/jdcoefct.c File Reference
jdcoefct.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_coef_controller
Macros
#define JPEG_INTERNALS
#define Q01_POS 1
#define Q02_POS 2
#define Q10_POS 8
#define Q11_POS 9
#define Q20_POS 16
#define SAVED_COEFS 6 /* we save coef_bits[0..5] */
Typedefs
typedef my_coef_controller * my_coef_ptr
Functions
consume_data (j_decompress_ptr cinfo)
decompress_data (j_decompress_ptr cinfo, JSAMPIMAGE output_buf)
decompress_onepass (j_decompress_ptr cinfo, JSAMPIMAGE output_buf)
decompress_smooth_data (j_decompress_ptr cinfo, JSAMPIMAGE output_buf)
dummy_consume_data (j_decompress_ptr cinfo)
jinit_d_coef_controller (j_decompress_ptr cinfo, boolean need_full_buffer)
METHODDEF (int)
smoothing_ok (j_decompress_ptr cinfo)
start_input_pass (j_decompress_ptr cinfo)
start_output_pass (j_decompress_ptr cinfo)
Macro Definition Documentation
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 17 of file jdcoefct.c.
Q01_POS
#define Q01_POS 1
Definition at line 390 of file jdcoefct.c.
Q02_POS
#define Q02_POS 2
Definition at line 394 of file jdcoefct.c.
Q10_POS
#define Q10_POS 8
Definition at line 391 of file jdcoefct.c.
Q11_POS
#define Q11_POS 9
Definition at line 393 of file jdcoefct.c.
Q20_POS
#define Q20_POS 16
Definition at line 392 of file jdcoefct.c.
SAVED_COEFS
#define SAVED_COEFS 6 /* we save coef_bits[0..5] */
Definition at line 58 of file jdcoefct.c.
Typedef Documentation
my_coef_ptr
typedef my_coef_controller* my_coef_ptr
Definition at line 62 of file jdcoefct.c.
Function Documentation
consume_data()
consume_data (j_decompress_ptr cinfo)
Definition at line 244 of file jdcoefct.c.
 {
   my_coef_ptr coef = (my_coef_ptr) cinfo->coef;
   JDIMENSION MCU_col_num;   /* index of current MCU within row */
   int blkn, ci, xindex, yindex, yoffset;
   JDIMENSION start_col;
   JBLOCKARRAY buffer[MAX_COMPS_IN_SCAN];
   JBLOCKROW buffer_ptr;
   jpeg_component_info *compptr;
   /* Align the virtual buffers for the components used in this scan. */
   for (ci = 0; ci < cinfo->comps_in_scan; ci++) {
     compptr = cinfo->cur_comp_info[ci];
     buffer[ci] = (*cinfo->mem->access_virt_barray)
       ((j_common_ptr) cinfo, coef->whole_image[compptr->component_index],
        cinfo->input_iMCU_row * compptr->v_samp_factor,
        (JDIMENSION) compptr->v_samp_factor, TRUE);
     /* Note: entropy decoder expects buffer to be zeroed,
      * but this is handled automatically by the memory manager
      * because we requested a pre-zeroed array.
      */
   }
   /* Loop to process one whole iMCU row */
   for (yoffset = coef->MCU_vert_offset; yoffset < coef->MCU_rows_per_iMCU_row;
        yoffset++) {
     for (MCU_col_num = coef->MCU_ctr; MCU_col_num < cinfo->MCUs_per_row;
      MCU_col_num++) {
       /* Construct list of pointers to DCT blocks belonging to this MCU */
       blkn = 0;         /* index of current DCT block within MCU */
       for (ci = 0; ci < cinfo->comps_in_scan; ci++) {
     compptr = cinfo->cur_comp_info[ci];
     start_col = MCU_col_num * compptr->MCU_width;
     for (yindex = 0; yindex < compptr->MCU_height; yindex++) {
       buffer_ptr = buffer[ci][yindex+yoffset] + start_col;
       for (xindex = 0; xindex < compptr->MCU_width; xindex++) {
         coef->MCU_buffer[blkn++] = buffer_ptr++;
       }
     }
       }
       /* Try to fetch the MCU. */
       if (! (*cinfo->entropy->decode_mcu) (cinfo, coef->MCU_buffer)) {
     /* Suspension forced; update state counters and exit */
     coef->MCU_vert_offset = yoffset;
     coef->MCU_ctr = MCU_col_num;
     return JPEG_SUSPENDED;
       }
     }
     /* Completed an MCU row, but perhaps not an iMCU row */
     coef->MCU_ctr = 0;
   }
   /* Completed the iMCU row, advance counters for next one */
   if (++(cinfo->input_iMCU_row) < cinfo->total_iMCU_rows) {
     start_iMCU_row(cinfo);
     return JPEG_ROW_COMPLETED;
   }
   /* Completed the scan */
   (*cinfo->inputctl->finish_input_pass) (cinfo);
   return JPEG_SCAN_COMPLETED;
 }
References jpeg_component_info::component_index, compptr, JPEG_ROW_COMPLETED, JPEG_SCAN_COMPLETED, JPEG_SUSPENDED, MAX_COMPS_IN_SCAN, my_coef_controller::MCU_buffer, my_coef_controller::MCU_ctr, jpeg_component_info::MCU_height, my_coef_controller::MCU_vert_offset, jpeg_component_info::MCU_width, start_col, start_iMCU_row(), TRUE, jpeg_component_info::v_samp_factor, and my_coef_controller::whole_image.
Referenced by jinit_d_coef_controller().
decompress_data()
decompress_data (j_decompress_ptr cinfo, JSAMPIMAGE output_buf)
Definition at line 315 of file jdcoefct.c.
 {
   my_coef_ptr coef = (my_coef_ptr) cinfo->coef;
   JDIMENSION last_iMCU_row = cinfo->total_iMCU_rows - 1;
   JDIMENSION block_num;
   int ci, block_row, block_rows;
   JBLOCKARRAY buffer;
   JBLOCKROW buffer_ptr;
   JSAMPARRAY output_ptr;
   JDIMENSION output_col;
   jpeg_component_info *compptr;
   inverse_DCT_method_ptr inverse_DCT;
   /* Force some input to be done if we are getting ahead of the input. */
   while (cinfo->input_scan_number < cinfo->output_scan_number ||
      (cinfo->input_scan_number == cinfo->output_scan_number &&
       cinfo->input_iMCU_row <= cinfo->output_iMCU_row)) {
     if ((*cinfo->inputctl->consume_input)(cinfo) == JPEG_SUSPENDED)
       return JPEG_SUSPENDED;
   }
   /* OK, output from the virtual arrays. */
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     /* Don't bother to IDCT an uninteresting component. */
     if (! compptr->component_needed)
       continue;
     /* Align the virtual buffer for this component. */
     buffer = (*cinfo->mem->access_virt_barray)
       ((j_common_ptr) cinfo, coef->whole_image[ci],
        cinfo->output_iMCU_row * compptr->v_samp_factor,
        (JDIMENSION) compptr->v_samp_factor, FALSE);
     /* Count non-dummy DCT block rows in this iMCU row. */
     if (cinfo->output_iMCU_row < last_iMCU_row)
       block_rows = compptr->v_samp_factor;
     else {
       /* NB: can't use last_row_height here; it is input-side-dependent! */
       block_rows = (int) (compptr->height_in_blocks % compptr->v_samp_factor);
       if (block_rows == 0) block_rows = compptr->v_samp_factor;
     }
     inverse_DCT = cinfo->idct->inverse_DCT[ci];
     output_ptr = output_buf[ci];
     /* Loop over all DCT blocks to be processed. */
     for (block_row = 0; block_row < block_rows; block_row++) {
       buffer_ptr = buffer[block_row];
       output_col = 0;
       for (block_num = 0; block_num < compptr->width_in_blocks; block_num++) {
     (*inverse_DCT) (cinfo, compptr, (JCOEFPTR) buffer_ptr,
             output_ptr, output_col);
     buffer_ptr++;
     output_col += compptr->DCT_h_scaled_size;
       }
       output_ptr += compptr->DCT_v_scaled_size;
     }
   }
   if (++(cinfo->output_iMCU_row) < cinfo->total_iMCU_rows)
     return JPEG_ROW_COMPLETED;
   return JPEG_SCAN_COMPLETED;
 }
References jpeg_component_info::component_needed, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, FALSE, jpeg_component_info::height_in_blocks, int(), JPEG_ROW_COMPLETED, JPEG_SCAN_COMPLETED, JPEG_SUSPENDED, output_buf, output_col, jpeg_component_info::v_samp_factor, my_coef_controller::whole_image, and jpeg_component_info::width_in_blocks.
Referenced by jinit_d_coef_controller(), and start_output_pass().
decompress_onepass()
decompress_onepass (j_decompress_ptr cinfo, JSAMPIMAGE output_buf)
Definition at line 147 of file jdcoefct.c.
 {
   my_coef_ptr coef = (my_coef_ptr) cinfo->coef;
   JDIMENSION MCU_col_num;   /* index of current MCU within row */
   JDIMENSION last_MCU_col = cinfo->MCUs_per_row - 1;
   JDIMENSION last_iMCU_row = cinfo->total_iMCU_rows - 1;
   int blkn, ci, xindex, yindex, yoffset, useful_width;
   JSAMPARRAY output_ptr;
   JDIMENSION start_col, output_col;
   jpeg_component_info *compptr;
   inverse_DCT_method_ptr inverse_DCT;
   /* Loop to process as much as one whole iMCU row */
   for (yoffset = coef->MCU_vert_offset; yoffset < coef->MCU_rows_per_iMCU_row;
        yoffset++) {
     for (MCU_col_num = coef->MCU_ctr; MCU_col_num <= last_MCU_col;
      MCU_col_num++) {
       /* Try to fetch an MCU.  Entropy decoder expects buffer to be zeroed. */
       jzero_far((void FAR *) coef->MCU_buffer[0],
         (size_t) (cinfo->blocks_in_MCU * SIZEOF(JBLOCK)));
       if (! (*cinfo->entropy->decode_mcu) (cinfo, coef->MCU_buffer)) {
     /* Suspension forced; update state counters and exit */
     coef->MCU_vert_offset = yoffset;
     coef->MCU_ctr = MCU_col_num;
     return JPEG_SUSPENDED;
       }
       /* Determine where data should go in output_buf and do the IDCT thing.
        * We skip dummy blocks at the right and bottom edges (but blkn gets
        * incremented past them!).  Note the inner loop relies on having
        * allocated the MCU_buffer[] blocks sequentially.
        */
       blkn = 0;         /* index of current DCT block within MCU */
       for (ci = 0; ci < cinfo->comps_in_scan; ci++) {
     compptr = cinfo->cur_comp_info[ci];
     /* Don't bother to IDCT an uninteresting component. */
     if (! compptr->component_needed) {
       blkn += compptr->MCU_blocks;
       continue;
     }
     inverse_DCT = cinfo->idct->inverse_DCT[compptr->component_index];
     useful_width = (MCU_col_num < last_MCU_col) ? compptr->MCU_width
                             : compptr->last_col_width;
     output_ptr = output_buf[compptr->component_index] +
       yoffset * compptr->DCT_v_scaled_size;
     start_col = MCU_col_num * compptr->MCU_sample_width;
     for (yindex = 0; yindex < compptr->MCU_height; yindex++) {
       if (cinfo->input_iMCU_row < last_iMCU_row ||
           yoffset+yindex < compptr->last_row_height) {
         output_col = start_col;
         for (xindex = 0; xindex < useful_width; xindex++) {
           (*inverse_DCT) (cinfo, compptr,
                   (JCOEFPTR) coef->MCU_buffer[blkn+xindex],
                   output_ptr, output_col);
           output_col += compptr->DCT_h_scaled_size;
         }
       }
       blkn += compptr->MCU_width;
       output_ptr += compptr->DCT_v_scaled_size;
     }
       }
     }
     /* Completed an MCU row, but perhaps not an iMCU row */
     coef->MCU_ctr = 0;
   }
   /* Completed the iMCU row, advance counters for next one */
   cinfo->output_iMCU_row++;
   if (++(cinfo->input_iMCU_row) < cinfo->total_iMCU_rows) {
     start_iMCU_row(cinfo);
     return JPEG_ROW_COMPLETED;
   }
   /* Completed the scan */
   (*cinfo->inputctl->finish_input_pass) (cinfo);
   return JPEG_SCAN_COMPLETED;
 }
References jpeg_component_info::component_index, jpeg_component_info::component_needed, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, FAR, JPEG_ROW_COMPLETED, JPEG_SCAN_COMPLETED, JPEG_SUSPENDED, jzero_far(), jpeg_component_info::last_col_width, jpeg_component_info::MCU_blocks, my_coef_controller::MCU_buffer, my_coef_controller::MCU_ctr, jpeg_component_info::MCU_height, jpeg_component_info::MCU_sample_width, my_coef_controller::MCU_vert_offset, jpeg_component_info::MCU_width, output_buf, output_col, SIZEOF, start_col, and start_iMCU_row().
Referenced by jinit_d_coef_controller().
decompress_smooth_data()
decompress_smooth_data (j_decompress_ptr cinfo, JSAMPIMAGE output_buf)
Definition at line 461 of file jdcoefct.c.
 {
   my_coef_ptr coef = (my_coef_ptr) cinfo->coef;
   JDIMENSION last_iMCU_row = cinfo->total_iMCU_rows - 1;
   JDIMENSION block_num, last_block_column;
   int ci, block_row, block_rows, access_rows;
   JBLOCKARRAY buffer;
   JBLOCKROW buffer_ptr, prev_block_row, next_block_row;
   JSAMPARRAY output_ptr;
   JDIMENSION output_col;
   jpeg_component_info *compptr;
   inverse_DCT_method_ptr inverse_DCT;
   boolean first_row, last_row;
   JBLOCK workspace;
   int *coef_bits;
   JQUANT_TBL *quanttbl;
   INT32 Q00,Q01,Q02,Q10,Q11,Q20, num;
   int DC1,DC2,DC3,DC4,DC5,DC6,DC7,DC8,DC9;
   int Al, pred;
   /* Force some input to be done if we are getting ahead of the input. */
   while (cinfo->input_scan_number <= cinfo->output_scan_number &&
      ! cinfo->inputctl->eoi_reached) {
     if (cinfo->input_scan_number == cinfo->output_scan_number) {
       /* If input is working on current scan, we ordinarily want it to
        * have completed the current row.  But if input scan is DC,
        * we want it to keep one row ahead so that next block row's DC
        * values are up to date.
        */
       JDIMENSION delta = (cinfo->Ss == 0) ? 1 : 0;
       if (cinfo->input_iMCU_row > cinfo->output_iMCU_row+delta)
     break;
     }
     if ((*cinfo->inputctl->consume_input)(cinfo) == JPEG_SUSPENDED)
       return JPEG_SUSPENDED;
   }
   /* OK, output from the virtual arrays. */
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     /* Don't bother to IDCT an uninteresting component. */
     if (! compptr->component_needed)
       continue;
     /* Count non-dummy DCT block rows in this iMCU row. */
     if (cinfo->output_iMCU_row < last_iMCU_row) {
       block_rows = compptr->v_samp_factor;
       access_rows = block_rows * 2; /* this and next iMCU row */
       last_row = FALSE;
     } else {
       /* NB: can't use last_row_height here; it is input-side-dependent! */
       block_rows = (int) (compptr->height_in_blocks % compptr->v_samp_factor);
       if (block_rows == 0) block_rows = compptr->v_samp_factor;
       access_rows = block_rows; /* this iMCU row only */
       last_row = TRUE;
     }
     /* Align the virtual buffer for this component. */
     if (cinfo->output_iMCU_row > 0) {
       access_rows += compptr->v_samp_factor; /* prior iMCU row too */
       buffer = (*cinfo->mem->access_virt_barray)
     ((j_common_ptr) cinfo, coef->whole_image[ci],
      (cinfo->output_iMCU_row - 1) * compptr->v_samp_factor,
      (JDIMENSION) access_rows, FALSE);
       buffer += compptr->v_samp_factor; /* point to current iMCU row */
       first_row = FALSE;
     } else {
       buffer = (*cinfo->mem->access_virt_barray)
     ((j_common_ptr) cinfo, coef->whole_image[ci],
      (JDIMENSION) 0, (JDIMENSION) access_rows, FALSE);
       first_row = TRUE;
     }
     /* Fetch component-dependent info */
     coef_bits = coef->coef_bits_latch + (ci * SAVED_COEFS);
     quanttbl = compptr->quant_table;
     Q00 = quanttbl->quantval[0];
     Q01 = quanttbl->quantval[Q01_POS];
     Q10 = quanttbl->quantval[Q10_POS];
     Q20 = quanttbl->quantval[Q20_POS];
     Q11 = quanttbl->quantval[Q11_POS];
     Q02 = quanttbl->quantval[Q02_POS];
     inverse_DCT = cinfo->idct->inverse_DCT[ci];
     output_ptr = output_buf[ci];
     /* Loop over all DCT blocks to be processed. */
     for (block_row = 0; block_row < block_rows; block_row++) {
       buffer_ptr = buffer[block_row];
       if (first_row && block_row == 0)
     prev_block_row = buffer_ptr;
       else
     prev_block_row = buffer[block_row-1];
       if (last_row && block_row == block_rows-1)
     next_block_row = buffer_ptr;
       else
     next_block_row = buffer[block_row+1];
       /* We fetch the surrounding DC values using a sliding-register approach.
        * Initialize all nine here so as to do the right thing on narrow pics.
        */
       DC1 = DC2 = DC3 = (int) prev_block_row[0][0];
       DC4 = DC5 = DC6 = (int) buffer_ptr[0][0];
       DC7 = DC8 = DC9 = (int) next_block_row[0][0];
       output_col = 0;
       last_block_column = compptr->width_in_blocks - 1;
       for (block_num = 0; block_num <= last_block_column; block_num++) {
     /* Fetch current DCT block into workspace so we can modify it. */
     jcopy_block_row(buffer_ptr, (JBLOCKROW) workspace, (JDIMENSION) 1);
     /* Update DC values */
     if (block_num < last_block_column) {
       DC3 = (int) prev_block_row[1][0];
       DC6 = (int) buffer_ptr[1][0];
       DC9 = (int) next_block_row[1][0];
     }
     /* Compute coefficient estimates per K.8.
      * An estimate is applied only if coefficient is still zero,
      * and is not known to be fully accurate.
      */
     /* AC01 */
     if ((Al=coef_bits[1]) != 0 && workspace[1] == 0) {
       num = 36 * Q00 * (DC4 - DC6);
       if (num >= 0) {
         pred = (int) (((Q01<<7) + num) / (Q01<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
       } else {
         pred = (int) (((Q01<<7) - num) / (Q01<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
         pred = -pred;
       }
       workspace[1] = (JCOEF) pred;
     }
     /* AC10 */
     if ((Al=coef_bits[2]) != 0 && workspace[8] == 0) {
       num = 36 * Q00 * (DC2 - DC8);
       if (num >= 0) {
         pred = (int) (((Q10<<7) + num) / (Q10<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
       } else {
         pred = (int) (((Q10<<7) - num) / (Q10<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
         pred = -pred;
       }
       workspace[8] = (JCOEF) pred;
     }
     /* AC20 */
     if ((Al=coef_bits[3]) != 0 && workspace[16] == 0) {
       num = 9 * Q00 * (DC2 + DC8 - 2*DC5);
       if (num >= 0) {
         pred = (int) (((Q20<<7) + num) / (Q20<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
       } else {
         pred = (int) (((Q20<<7) - num) / (Q20<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
         pred = -pred;
       }
       workspace[16] = (JCOEF) pred;
     }
     /* AC11 */
     if ((Al=coef_bits[4]) != 0 && workspace[9] == 0) {
       num = 5 * Q00 * (DC1 - DC3 - DC7 + DC9);
       if (num >= 0) {
         pred = (int) (((Q11<<7) + num) / (Q11<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
       } else {
         pred = (int) (((Q11<<7) - num) / (Q11<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
         pred = -pred;
       }
       workspace[9] = (JCOEF) pred;
     }
     /* AC02 */
     if ((Al=coef_bits[5]) != 0 && workspace[2] == 0) {
       num = 9 * Q00 * (DC4 + DC6 - 2*DC5);
       if (num >= 0) {
         pred = (int) (((Q02<<7) + num) / (Q02<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
       } else {
         pred = (int) (((Q02<<7) - num) / (Q02<<8));
         if (Al > 0 && pred >= (1<<Al))
           pred = (1<<Al)-1;
         pred = -pred;
       }
       workspace[2] = (JCOEF) pred;
     }
     /* OK, do the IDCT */
     (*inverse_DCT) (cinfo, compptr, (JCOEFPTR) workspace,
             output_ptr, output_col);
     /* Advance for next column */
     DC1 = DC2; DC2 = DC3;
     DC4 = DC5; DC5 = DC6;
     DC7 = DC8; DC8 = DC9;
     buffer_ptr++, prev_block_row++, next_block_row++;
     output_col += compptr->DCT_h_scaled_size;
       }
       output_ptr += compptr->DCT_v_scaled_size;
     }
   }
   if (++(cinfo->output_iMCU_row) < cinfo->total_iMCU_rows)
     return JPEG_ROW_COMPLETED;
   return JPEG_SCAN_COMPLETED;
 }
References my_coef_controller::coef_bits_latch, jpeg_component_info::component_needed, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, FALSE, jpeg_component_info::height_in_blocks, int(), jcopy_block_row(), JPEG_ROW_COMPLETED, JPEG_SCAN_COMPLETED, JPEG_SUSPENDED, output_buf, output_col, Q01_POS, Q02_POS, Q10_POS, Q11_POS, Q20_POS, jpeg_component_info::quant_table, JQUANT_TBL::quantval, SAVED_COEFS, TRUE, jpeg_component_info::v_samp_factor, my_coef_controller::whole_image, and jpeg_component_info::width_in_blocks.
Referenced by start_output_pass().
dummy_consume_data()
dummy_consume_data (j_decompress_ptr cinfo)
Definition at line 228 of file jdcoefct.c.
 {
   return JPEG_SUSPENDED;    /* Always indicate nothing was done */
 }
References JPEG_SUSPENDED.
Referenced by jinit_d_coef_controller().
jinit_d_coef_controller()
jinit_d_coef_controller (j_decompress_ptr cinfo, boolean need_full_buffer)
Definition at line 676 of file jdcoefct.c.
 {
   my_coef_ptr coef;
   coef = (my_coef_ptr)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 SIZEOF(my_coef_controller));
   cinfo->coef = (struct jpeg_d_coef_controller *) coef;
   coef->pub.start_input_pass = start_input_pass;
   coef->pub.start_output_pass = start_output_pass;
 #ifdef BLOCK_SMOOTHING_SUPPORTED
   coef->coef_bits_latch = NULL;
 #endif
   /* Create the coefficient buffer. */
   if (need_full_buffer) {
 #ifdef D_MULTISCAN_FILES_SUPPORTED
     /* Allocate a full-image virtual array for each component, */
     /* padded to a multiple of samp_factor DCT blocks in each direction. */
     /* Note we ask for a pre-zeroed array. */
     int ci, access_rows;
     jpeg_component_info *compptr;
     for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
      ci++, compptr++) {
       access_rows = compptr->v_samp_factor;
 #ifdef BLOCK_SMOOTHING_SUPPORTED
       /* If block smoothing could be used, need a bigger window */
       if (cinfo->progressive_mode)
     access_rows *= 3;
 #endif
       coef->whole_image[ci] = (*cinfo->mem->request_virt_barray)
     ((j_common_ptr) cinfo, JPOOL_IMAGE, TRUE,
      (JDIMENSION) jround_up((long) compptr->width_in_blocks,
                 (long) compptr->h_samp_factor),
      (JDIMENSION) jround_up((long) compptr->height_in_blocks,
                 (long) compptr->v_samp_factor),
      (JDIMENSION) access_rows);
     }
     coef->pub.consume_data = consume_data;
     coef->pub.decompress_data = decompress_data;
     coef->pub.coef_arrays = coef->whole_image; /* link to virtual arrays */
 #else
     ERREXIT(cinfo, JERR_NOT_COMPILED);
 #endif
   } else {
     /* We only need a single-MCU buffer. */
     JBLOCKROW buffer;
     int i;
     buffer = (JBLOCKROW)
       (*cinfo->mem->alloc_large) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                   D_MAX_BLOCKS_IN_MCU * SIZEOF(JBLOCK));
     for (i = 0; i < D_MAX_BLOCKS_IN_MCU; i++) {
       coef->MCU_buffer[i] = buffer + i;
     }
     coef->pub.consume_data = dummy_consume_data;
     coef->pub.decompress_data = decompress_onepass;
     coef->pub.coef_arrays = NULL; /* flag for no virtual arrays */
   }
 }
References my_coef_controller::coef_bits_latch, compptr, consume_data(), D_MAX_BLOCKS_IN_MCU, decompress_data(), decompress_onepass(), dummy_consume_data(), ERREXIT, jpeg_component_info::h_samp_factor, jpeg_component_info::height_in_blocks, JPOOL_IMAGE, jround_up(), long(), my_coef_controller::MCU_buffer, need_full_buffer, NULL, my_coef_controller::pub, SIZEOF, start_input_pass(), start_output_pass(), TRUE, jpeg_component_info::v_samp_factor, my_coef_controller::whole_image, and jpeg_component_info::width_in_blocks.
Referenced by master_selection(), and transdecode_master_selection().
METHODDEF()
METHODDEF (int)
Definition at line 65 of file jdcoefct.c.
 {
   my_coef_ptr coef = (my_coef_ptr) cinfo->coef;
   /* In an interleaved scan, an MCU row is the same as an iMCU row.
    * In a noninterleaved scan, an iMCU row has v_samp_factor MCU rows.
    * But at the bottom of the image, process only what's left.
    */
   if (cinfo->comps_in_scan > 1) {
     coef->MCU_rows_per_iMCU_row = 1;
   } else {
     if (cinfo->input_iMCU_row < (cinfo->total_iMCU_rows-1))
       coef->MCU_rows_per_iMCU_row = cinfo->cur_comp_info[0]->v_samp_factor;
     else
       coef->MCU_rows_per_iMCU_row = cinfo->cur_comp_info[0]->last_row_height;
   }
   coef->MCU_ctr = 0;
   coef->MCU_vert_offset = 0;
 }
smoothing_ok()
smoothing_ok (j_decompress_ptr cinfo)
Definition at line 405 of file jdcoefct.c.
 {
   my_coef_ptr coef = (my_coef_ptr) cinfo->coef;
   boolean smoothing_useful = FALSE;
   int ci, coefi;
   jpeg_component_info *compptr;
   JQUANT_TBL * qtable;
   int * coef_bits;
   int * coef_bits_latch;
   if (! cinfo->progressive_mode || cinfo->coef_bits == NULL)
     return FALSE;
   /* Allocate latch area if not already done */
   if (coef->coef_bits_latch == NULL)
     coef->coef_bits_latch = (int *)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                   cinfo->num_components *
                   (SAVED_COEFS * SIZEOF(int)));
   coef_bits_latch = coef->coef_bits_latch;
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     /* All components' quantization values must already be latched. */
     if ((qtable = compptr->quant_table) == NULL)
       return FALSE;
     /* Verify DC & first 5 AC quantizers are nonzero to avoid zero-divide. */
     if (qtable->quantval[0] == 0 ||
     qtable->quantval[Q01_POS] == 0 ||
     qtable->quantval[Q10_POS] == 0 ||
     qtable->quantval[Q20_POS] == 0 ||
     qtable->quantval[Q11_POS] == 0 ||
     qtable->quantval[Q02_POS] == 0)
       return FALSE;
     /* DC values must be at least partly known for all components. */
     coef_bits = cinfo->coef_bits[ci];
     if (coef_bits[0] < 0)
       return FALSE;
     /* Block smoothing is helpful if some AC coefficients remain inaccurate. */
     for (coefi = 1; coefi <= 5; coefi++) {
       coef_bits_latch[coefi] = coef_bits[coefi];
       if (coef_bits[coefi] != 0)
     smoothing_useful = TRUE;
     }
     coef_bits_latch += SAVED_COEFS;
   }
   return smoothing_useful;
 }
References my_coef_controller::coef_bits_latch, compptr, FALSE, JPOOL_IMAGE, NULL, Q01_POS, Q02_POS, Q10_POS, Q11_POS, Q20_POS, jpeg_component_info::quant_table, SAVED_COEFS, SIZEOF, and TRUE.
Referenced by start_output_pass().
start_input_pass()
start_input_pass (j_decompress_ptr cinfo)
Definition at line 107 of file jdcoefct.c.
 {
   cinfo->input_iMCU_row = 0;
   start_iMCU_row(cinfo);
 }
References start_iMCU_row().
Referenced by jinit_d_coef_controller().
start_output_pass()
start_output_pass (j_decompress_ptr cinfo)
Definition at line 119 of file jdcoefct.c.
 {
 #ifdef BLOCK_SMOOTHING_SUPPORTED
   my_coef_ptr coef = (my_coef_ptr) cinfo->coef;
   /* If multipass, check to see whether to use block smoothing on this pass */
   if (coef->pub.coef_arrays != NULL) {
     if (cinfo->do_block_smoothing && smoothing_ok(cinfo))
       coef->pub.decompress_data = decompress_smooth_data;
     else
       coef->pub.decompress_data = decompress_data;
   }
 #endif
   cinfo->output_iMCU_row = 0;
 }
References decompress_data(), decompress_smooth_data(), NULL, my_coef_controller::pub, and smoothing_ok().
Referenced by jinit_d_coef_controller().