ZEQ2-Lite: Source/Engine/null/null_glimp.c File Reference
null_glimp.c File Reference
#include "../renderer/tr_local.h"
Functions
void GLimp_EnableLogging (qboolean enable)
void GLimp_EndFrame (void)
int GLimp_Init (void)
void GLimp_LogComment (char *comment)
void GLimp_Shutdown (void)
qboolean QGL_Init (const char *dllname)
void QGL_Shutdown (void)
Variables
void(* qglActiveTextureARB)(GLenum texture)
void(* qglClientActiveTextureARB)(GLenum texture)
void(* qglLockArraysEXT)(int, int)
void(* qglMultiTexCoord2fARB)(GLenum texture, float s, float t)
void(* qglUnlockArraysEXT)(void)
qboolean(* qwglSwapIntervalEXT)(int interval)
Function Documentation
GLimp_EnableLogging()
void GLimp_EnableLogging (qboolean enable)
Definition at line 45 of file null_glimp.c.
{
 }
GLimp_EndFrame()
void GLimp_EndFrame (void)
Definition at line 35 of file null_glimp.c.
{
 }
Referenced by RB_SwapBuffers().
GLimp_Init()
int GLimp_Init (void)
Definition at line 38 of file null_glimp.c.
 {
 }
Referenced by InitOpenGL().
GLimp_LogComment()
void GLimp_LogComment (char * comment)
Definition at line 48 of file null_glimp.c.
{
 }
Referenced by DrawBBoxes(), DrawTris(), GL_SelectTexture(), RB_EndSurface(), RB_GLSL_StageIteratorGeneric(), RB_OutlinesPass(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), RB_StageIteratorVertexLitTexture(), RB_SwapBuffers(), and RE_RenderScene().
GLimp_Shutdown()
void GLimp_Shutdown (void)
Definition at line 42 of file null_glimp.c.
{
 }
Referenced by RE_Shutdown().
QGL_Init()
qboolean QGL_Init (const char * dllname)
Definition at line 51 of file null_glimp.c.
{
     return qtrue;
 }
References qtrue.
QGL_Shutdown()
void QGL_Shutdown (void)
Definition at line 55 of file null_glimp.c.
{
 }
Variable Documentation
qglActiveTextureARB
void(* qglActiveTextureARB) (GLenum texture)
Definition at line 27 of file null_glimp.c.
Referenced by CollapseMultitexture(), GfxInfo_f(), GL_SelectTexture(), GL_SetDefaultState(), GLimp_InitExtensions(), R_CreateImage(), and R_DeleteTextures().
qglClientActiveTextureARB
void(* qglClientActiveTextureARB) (GLenum texture)
Definition at line 28 of file null_glimp.c.
Referenced by GL_SelectTexture(), and GLimp_InitExtensions().
qglLockArraysEXT
void(* qglLockArraysEXT) (int, int)
Definition at line 31 of file null_glimp.c.
Referenced by DrawBBoxes(), DrawTris(), GfxInfo_f(), GLimp_InitExtensions(), R_DrawElements(), RB_GLSL_StageIteratorGeneric(), RB_OutlinesPass(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
qglMultiTexCoord2fARB
void(* qglMultiTexCoord2fARB) (GLenum texture, float s, float t)
Definition at line 26 of file null_glimp.c.
Referenced by GLimp_InitExtensions(), and R_ArrayElementDiscrete().
qglUnlockArraysEXT
void(* qglUnlockArraysEXT) (void)
Definition at line 32 of file null_glimp.c.
Referenced by DrawBBoxes(), DrawTris(), GLimp_InitExtensions(), RB_GLSL_StageIteratorGeneric(), RB_OutlinesPass(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
qwglSwapIntervalEXT
qboolean(* qwglSwapIntervalEXT) (int interval)
Definition at line 25 of file null_glimp.c.