ZEQ2-Lite: Source/Game/CGame/cg_userweapons.c File Reference
cg_userweapons.c File Reference
#include "cg_local.h"
Functions
void CG_CopyUserWeaponGraphics (int from, int to)
cg_userWeapon_t * CG_FindUserWeaponGraphics (int clientNum, int index)
Variables
static cg_userWeapon_t weaponGraphicsDatabase [MAX_CLIENTS][ALTSPAWN_OFFSET+MAX_PLAYERWEAPONS]
Function Documentation
CG_CopyUserWeaponGraphics()
void CG_CopyUserWeaponGraphics (int from, int to)
Definition at line 19 of file cg_userweapons.c.
{
     memcpy(&weaponGraphicsDatabase[to], &weaponGraphicsDatabase[from], sizeof(cg_userWeapon_t)*(ALTSPAWN_OFFSET+MAX_PLAYERWEAPONS));
 }
References ALTSPAWN_OFFSET, MAX_PLAYERWEAPONS, and weaponGraphicsDatabase.
CG_FindUserWeaponGraphics()
cg_userWeapon_t* CG_FindUserWeaponGraphics (int clientNum, int index)
Definition at line 15 of file cg_userweapons.c.
{
     return &weaponGraphicsDatabase[clientNum][index - 1];
 }
References weaponGraphicsDatabase.
Referenced by CG_AddPlayerWeapon(), CG_DrawHUD(), CG_DrawWeaponSelectHorCenterBar(), CG_FireWeapon(), CG_Missile(), CG_Torch(), CG_TrailFunc_BendyBeam(), CG_TrailFunc_FadeTail(), CG_TrailFunc_SpiralBeam(), CG_TrailFunc_SpiralBeam_Helper(), CG_TrailFunc_StraightBeam(), CG_UserMissileHitWall(), and CG_weapGfx_StoreBuffer().
Variable Documentation
weaponGraphicsDatabase
cg_userWeapon_t weaponGraphicsDatabase[MAX_CLIENTS][ALTSPAWN_OFFSET+MAX_PLAYERWEAPONS] static
Definition at line 11 of file cg_userweapons.c.
Referenced by CG_CopyUserWeaponGraphics(), and CG_FindUserWeaponGraphics().