ZEQ2-Lite: __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator > Class Template Reference
__gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator > Class Template Reference
#include <const_iterator.hpp>
Public Types
typedef base_type::const_pointer const_pointer
typedef base_type::const_reference const_reference
typedef Allocator::difference_type difference_type
typedef std::forward_iterator_tag iterator_category
typedef base_type::pointer pointer
typedef base_type::reference reference
typedef base_type::value_type value_type
Public Member Functions
binary_heap_const_iterator_ ()
binary_heap_const_iterator_ (const PB_DS_CLASS_C_DEC &other)
binary_heap_const_iterator_ (entry_pointer p_e)
bool operator!= (const PB_DS_CLASS_C_DEC &other) const
PB_DS_CLASS_C_DEC & operator++ ()
PB_DS_CLASS_C_DEC operator++ (int)
bool operator== (const PB_DS_CLASS_C_DEC &other) const
Private Types
typedef PB_DS_BASE_C_DEC base_type
typedef PB_DS_BASE_C_DEC::entry_pointer entry_pointer
Private Member Functions
void inc ()
Detailed Description
template<typename Value_Type, typename Entry, bool Simple, class Allocator>
class __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >
Definition at line 64 of file const_iterator.hpp.
Member Typedef Documentation
base_type
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef PB_DS_BASE_C_DEC __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::base_type private
Definition at line 70 of file const_iterator.hpp.
const_pointer
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef base_type::const_pointer __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::const_pointer
Definition at line 87 of file const_iterator.hpp.
const_reference
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef base_type::const_reference __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::const_reference
Definition at line 93 of file const_iterator.hpp.
difference_type
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::difference_type
Definition at line 78 of file const_iterator.hpp.
entry_pointer
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef PB_DS_BASE_C_DEC::entry_pointer __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::entry_pointer private
Definition at line 68 of file const_iterator.hpp.
iterator_category
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef std::forward_iterator_tag __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::iterator_category
Definition at line 75 of file const_iterator.hpp.
pointer
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef base_type::pointer __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::pointer
Definition at line 84 of file const_iterator.hpp.
reference
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef base_type::reference __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::reference
Definition at line 90 of file const_iterator.hpp.
value_type
template<typename Value_Type , typename Entry , bool Simple, class Allocator > typedef base_type::value_type __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::value_type
Definition at line 81 of file const_iterator.hpp.
Constructor & Destructor Documentation
binary_heap_const_iterator_() [1/3]
template<typename Value_Type , typename Entry , bool Simple, class Allocator > __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::binary_heap_const_iterator_ (entry_pointer p_e) inline
Definition at line 98 of file const_iterator.hpp.
                                                      : base_type(p_e)
       { }
binary_heap_const_iterator_() [2/3]
template<typename Value_Type , typename Entry , bool Simple, class Allocator > __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::binary_heap_const_iterator_ () inline
Definition at line 103 of file const_iterator.hpp.
       { }
binary_heap_const_iterator_() [3/3]
template<typename Value_Type , typename Entry , bool Simple, class Allocator > __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::binary_heap_const_iterator_ (const PB_DS_CLASS_C_DEC & other) inline
Definition at line 108 of file const_iterator.hpp.
                                                                   : base_type(other)
       { }
Member Function Documentation
inc()
template<typename Value_Type , typename Entry , bool Simple, class Allocator > void __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::inc () inline private
Definition at line 143 of file const_iterator.hpp.
       { ++base_type::m_p_e; }
Referenced by __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::operator++().
operator!=()
template<typename Value_Type , typename Entry , bool Simple, class Allocator > bool __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::operator!= (const PB_DS_CLASS_C_DEC & other) const inline
Definition at line 120 of file const_iterator.hpp.
       {
     return base_type::m_p_e != other.m_p_e;
       }
operator++() [1/2]
template<typename Value_Type , typename Entry , bool Simple, class Allocator > PB_DS_CLASS_C_DEC& __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::operator++ () inline
Definition at line 126 of file const_iterator.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(base_type::m_p_e != 0);
     inc();
     return *this;
       }
References _GLIBCXX_DEBUG_ASSERT, and __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::inc().
Referenced by __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::operator++().
operator++() [2/2]
template<typename Value_Type , typename Entry , bool Simple, class Allocator > PB_DS_CLASS_C_DEC __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::operator++ (int) inline
Definition at line 134 of file const_iterator.hpp.
       {
     PB_DS_CLASS_C_DEC ret_it(base_type::m_p_e);
     operator++();
     return ret_it;
       }
References __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::operator++(), and PB_DS_CLASS_C_DEC.
operator==()
template<typename Value_Type , typename Entry , bool Simple, class Allocator > bool __gnu_pbds::detail::binary_heap_const_iterator_< Value_Type, Entry, Simple, Allocator >::operator== (const PB_DS_CLASS_C_DEC & other) const inline
Definition at line 113 of file const_iterator.hpp.
       {
     return base_type::m_p_e == other.m_p_e;
       }
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/binary_heap_/const_iterator.hpp