ZEQ2-Lite: SolidBrush Class Reference
SolidBrush Class Reference
#include <gdiplusbrush.h>
Public Member Functions
SolidBrush (const Color &color)
virtual SolidBrush * Clone () const
Status GetColor (Color *color) const
Status GetLastStatus () const
BrushType GetType () const
Status SetColor (const Color &color)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
SolidBrush (const SolidBrush &)
SolidBrush (GpBrush *brush, Status status)
SolidBrush & operator= (const SolidBrush &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpBrush * nativeBrush
Detailed Description
Definition at line 402 of file gdiplusbrush.h.
Constructor & Destructor Documentation
SolidBrush() [1/3]
SolidBrush::SolidBrush (const Color & color) inline
Definition at line 405 of file gdiplusbrush.h.
     {
         GpSolidFill *nativeSolidFill = NULL;
         lastStatus = DllExports::GdipCreateSolidFill(
                 color.GetValue(), &nativeSolidFill);
         nativeBrush = nativeSolidFill;
     }
References GdipCreateSolidFill(), Brush::lastStatus, Brush::nativeBrush, and NULL.
SolidBrush() [2/3]
SolidBrush::SolidBrush (GpBrush * brush, Status status) inline private
Definition at line 443 of file gdiplusbrush.h.
 : Brush(brush, status) {}
SolidBrush() [3/3]
SolidBrush::SolidBrush (const SolidBrush &) private
Member Function Documentation
Clone()
virtual SolidBrush* SolidBrush::Clone () const inline virtual
Reimplemented from Brush.
Definition at line 412 of file gdiplusbrush.h.
     {
         GpBrush *cloneBrush = NULL;
         Status status = updateStatus(DllExports::GdipCloneBrush(
                 nativeBrush, &cloneBrush));
         if (status == Ok) {
             SolidBrush *result =
                 new SolidBrush(cloneBrush, lastStatus);
             if (!result) {
                 DllExports::GdipDeleteBrush(cloneBrush);
                 updateStatus(OutOfMemory);
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneBrush(), GdipDeleteBrush(), Brush::lastStatus, Brush::nativeBrush, NULL, Ok, OutOfMemory, Brush::SolidBrush, and Brush::updateStatus().
GetColor()
Status SolidBrush::GetColor (Color * color) const inline
Definition at line 430 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipGetSolidFillColor(
                 (GpSolidFill*) nativeBrush,
                 color ? &color->Value : NULL));
     }
References GdipGetSolidFillColor(), Brush::nativeBrush, NULL, Brush::updateStatus(), and Color::Value.
GetLastStatus()
Status Brush::GetLastStatus () const inline inherited
Definition at line 54 of file gdiplusbrush.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References Brush::lastStatus, and Ok.
GetType()
BrushType Brush::GetType () const inline inherited
Definition at line 60 of file gdiplusbrush.h.
     {
         BrushType result = BrushTypeSolidColor;
         updateStatus(DllExports::GdipGetBrushType(nativeBrush, &result));
         return result;
     }
References BrushTypeSolidColor, GdipGetBrushType(), Brush::nativeBrush, and Brush::updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
SolidBrush& SolidBrush::operator= (const SolidBrush &) private
SetColor()
Status SolidBrush::SetColor (const Color & color) inline
Definition at line 436 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetSolidFillColor(
                 (GpSolidFill*) nativeBrush, color.GetValue()));
     }
References GdipSetSolidFillColor(), Brush::nativeBrush, and Brush::updateStatus().
updateStatus()
Status Brush::updateStatus (Status newStatus) const inline private inherited
Definition at line 74 of file gdiplusbrush.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References Brush::lastStatus, and Ok.
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), HatchBrush::GetBackgroundColor(), LinearGradientBrush::GetBlend(), PathGradientBrush::GetBlend(), LinearGradientBrush::GetBlendCount(), PathGradientBrush::GetBlendCount(), PathGradientBrush::GetCenterColor(), PathGradientBrush::GetCenterPoint(), GetColor(), PathGradientBrush::GetFocusScales(), HatchBrush::GetForegroundColor(), LinearGradientBrush::GetGammaCorrection(), PathGradientBrush::GetGammaCorrection(), HatchBrush::GetHatchStyle(), LinearGradientBrush::GetInterpolationColorCount(), PathGradientBrush::GetInterpolationColorCount(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetPointCount(), LinearGradientBrush::GetRectangle(), PathGradientBrush::GetRectangle(), PathGradientBrush::GetSurroundColorCount(), PathGradientBrush::GetSurroundColors(), LinearGradientBrush::GetTransform(), PathGradientBrush::GetTransform(), TextureBrush::GetTransfrom(), Brush::GetType(), LinearGradientBrush::GetWrapMode(), TextureBrush::GetWrapMode(), PathGradientBrush::GetWrapMode(), LinearGradientBrush::MultiplyTransform(), TextureBrush::MultiplyTransform(), PathGradientBrush::MultiplyTransform(), LinearGradientBrush::ResetTransform(), TextureBrush::ResetTransform(), PathGradientBrush::ResetTransform(), LinearGradientBrush::RotateTranform(), TextureBrush::RotateTransform(), PathGradientBrush::RotateTransform(), LinearGradientBrush::ScaleTransform(), TextureBrush::ScaleTransform(), PathGradientBrush::ScaleTransform(), LinearGradientBrush::SetBlend(), PathGradientBrush::SetBlend(), LinearGradientBrush::SetBlendBellShape(), PathGradientBrush::SetBlendBellShape(), LinearGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetCenterColor(), PathGradientBrush::SetCenterPoint(), SetColor(), PathGradientBrush::SetFocusScales(), LinearGradientBrush::SetGammaCorrection(), PathGradientBrush::SetGammaCorrection(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), LinearGradientBrush::SetLinearColors(), PathGradientBrush::SetSurroundColors(), LinearGradientBrush::SetTransform(), TextureBrush::SetTransform(), PathGradientBrush::SetTransform(), LinearGradientBrush::SetWrapMode(), TextureBrush::SetWrapMode(), PathGradientBrush::SetWrapMode(), LinearGradientBrush::TranslateTransform(), TextureBrush::TranslateTransform(), and PathGradientBrush::TranslateTransform().
Field Documentation
lastStatus
Status Brush::lastStatus mutable private inherited
Definition at line 81 of file gdiplusbrush.h.
Referenced by Brush::Clone(), HatchBrush::Clone(), LinearGradientBrush::Clone(), Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), Brush::GetLastStatus(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetSurroundColors(), HatchBrush::HatchBrush(), LinearGradientBrush::LinearGradientBrush(), PathGradientBrush::PathGradientBrush(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), PathGradientBrush::SetSurroundColors(), SolidBrush(), TextureBrush::TextureBrush(), and Brush::updateStatus().
nativeBrush
GpBrush* Brush::nativeBrush private inherited
Definition at line 80 of file gdiplusbrush.h.
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), Graphics::DrawDriverString(), Graphics::DrawString(), Graphics::FillClosedCurve(), Graphics::FillEllipse(), Graphics::FillPath(), Graphics::FillPie(), Graphics::FillPolygon(), Graphics::FillRectangle(), Graphics::FillRectangles(), Graphics::FillRegion(), HatchBrush::GetBackgroundColor(), LinearGradientBrush::GetBlend(), PathGradientBrush::GetBlend(), LinearGradientBrush::GetBlendCount(), PathGradientBrush::GetBlendCount(), PathGradientBrush::GetCenterColor(), PathGradientBrush::GetCenterPoint(), GetColor(), PathGradientBrush::GetFocusScales(), HatchBrush::GetForegroundColor(), LinearGradientBrush::GetGammaCorrection(), PathGradientBrush::GetGammaCorrection(), HatchBrush::GetHatchStyle(), LinearGradientBrush::GetInterpolationColorCount(), PathGradientBrush::GetInterpolationColorCount(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetPointCount(), LinearGradientBrush::GetRectangle(), PathGradientBrush::GetRectangle(), PathGradientBrush::GetSurroundColorCount(), PathGradientBrush::GetSurroundColors(), LinearGradientBrush::GetTransform(), PathGradientBrush::GetTransform(), TextureBrush::GetTransfrom(), Brush::GetType(), LinearGradientBrush::GetWrapMode(), TextureBrush::GetWrapMode(), PathGradientBrush::GetWrapMode(), HatchBrush::HatchBrush(), LinearGradientBrush::LinearGradientBrush(), LinearGradientBrush::MultiplyTransform(), TextureBrush::MultiplyTransform(), PathGradientBrush::MultiplyTransform(), PathGradientBrush::PathGradientBrush(), Pen::Pen(), LinearGradientBrush::ResetTransform(), TextureBrush::ResetTransform(), PathGradientBrush::ResetTransform(), LinearGradientBrush::RotateTranform(), TextureBrush::RotateTransform(), PathGradientBrush::RotateTransform(), LinearGradientBrush::ScaleTransform(), TextureBrush::ScaleTransform(), PathGradientBrush::ScaleTransform(), LinearGradientBrush::SetBlend(), PathGradientBrush::SetBlend(), LinearGradientBrush::SetBlendBellShape(), PathGradientBrush::SetBlendBellShape(), LinearGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetBlendTriangularShape(), Pen::SetBrush(), PathGradientBrush::SetCenterColor(), PathGradientBrush::SetCenterPoint(), SetColor(), PathGradientBrush::SetFocusScales(), LinearGradientBrush::SetGammaCorrection(), PathGradientBrush::SetGammaCorrection(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), LinearGradientBrush::SetLinearColors(), PathGradientBrush::SetSurroundColors(), LinearGradientBrush::SetTransform(), TextureBrush::SetTransform(), PathGradientBrush::SetTransform(), LinearGradientBrush::SetWrapMode(), TextureBrush::SetWrapMode(), PathGradientBrush::SetWrapMode(), SolidBrush(), TextureBrush::TextureBrush(), LinearGradientBrush::TranslateTransform(), TextureBrush::TranslateTransform(), PathGradientBrush::TranslateTransform(), and Brush::~Brush().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusbrush.h