ZEQ2-Lite: __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator > Class Template Reference
__gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator > Class Template Reference
#include <point_iterators.hpp>
Public Types
typedef Type_Traits::const_pointer const_pointer
typedef Type_Traits::const_reference const_reference
typedef Type_Traits::pointer pointer
typedef Type_Traits::reference reference
typedef Type_Traits::value_type value_type
Public Member Functions
pat_trie_it_ (const PB_DS_ODIR_IT_C_DEC &other)
pat_trie_it_ (node_pointer p_nd=0)
reference operator* () const
PB_DS_IT_C_DEC & operator++ ()
PB_DS_IT_C_DEC operator++ (int)
PB_DS_IT_C_DEC & operator-- ()
PB_DS_IT_C_DEC operator-- (int)
pointer operator-> () const
PB_DS_IT_C_DEC & operator= (const PB_DS_IT_C_DEC &other)
PB_DS_IT_C_DEC & operator= (const PB_DS_ODIR_IT_C_DEC &other)
Protected Types
typedef PB_DS_CONST_IT_C_DEC base_it_type
Private Types
typedef Allocator::template rebind< Leaf >::other::const_pointer const_leaf_pointer
typedef Allocator::template rebind< Head >::other::pointer head_pointer
typedef Allocator::template rebind< Internal_Node >::other::pointer internal_node_pointer
typedef Allocator::template rebind< Leaf >::other::pointer leaf_pointer
typedef Allocator::template rebind< Node >::other::pointer node_pointer
Friends
class PB_DS_CLASS_C_DEC
Detailed Description
template<typename Type_Traits, class Node, class Leaf, class Head, class Internal_Node, bool Is_Forward_Iterator, class Allocator>
class __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >
Definition at line 358 of file point_iterators.hpp.
Member Typedef Documentation
base_it_type
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef PB_DS_CONST_IT_C_DEC __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::base_it_type protected
Definition at line 470 of file point_iterators.hpp.
const_leaf_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Leaf>::other::const_pointer __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::const_leaf_pointer private
Definition at line 371 of file point_iterators.hpp.
const_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::const_pointer __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::const_pointer
Definition at line 391 of file point_iterators.hpp.
const_reference
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::const_reference __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::const_reference
Definition at line 395 of file point_iterators.hpp.
head_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Head>::other::pointer __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::head_pointer private
Definition at line 381 of file point_iterators.hpp.
internal_node_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Internal_Node>::other::pointer __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::internal_node_pointer private
Definition at line 386 of file point_iterators.hpp.
leaf_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Leaf>::other::pointer __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::leaf_pointer private
Definition at line 376 of file point_iterators.hpp.
node_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Node>::other::pointer __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::node_pointer private
Definition at line 366 of file point_iterators.hpp.
pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::pointer __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::pointer
Definition at line 393 of file point_iterators.hpp.
reference
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::reference __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::reference
Definition at line 397 of file point_iterators.hpp.
value_type
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::value_type __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::value_type
Definition at line 389 of file point_iterators.hpp.
Constructor & Destructor Documentation
pat_trie_it_() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::pat_trie_it_ (node_pointer p_nd = 0) inline
Definition at line 400 of file point_iterators.hpp.
                                           : PB_DS_CONST_IT_C_DEC((node_pointer)p_nd)
       { }
pat_trie_it_() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::pat_trie_it_ (const PB_DS_ODIR_IT_C_DEC & other) inline
Definition at line 404 of file point_iterators.hpp.
                                                      : PB_DS_CONST_IT_C_DEC(other.m_p_nd)
       { }
Member Function Documentation
operator*()
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > reference __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator* () const inline
Definition at line 432 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(base_it_type::m_p_nd->m_type == pat_trie_leaf_node_type);
     return static_cast<leaf_pointer>(base_it_type::m_p_nd)->value();
       }
References _GLIBCXX_DEBUG_ASSERT, and __gnu_pbds::detail::pat_trie_leaf_node_type.
operator++() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_IT_C_DEC& __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++ () inline
Definition at line 439 of file point_iterators.hpp.
       {
     PB_DS_CONST_IT_C_DEC::
       operator++();
     return *this;
       }
Referenced by __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++().
operator++() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_IT_C_DEC __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++ (int) inline
Definition at line 447 of file point_iterators.hpp.
       {
     PB_DS_IT_C_DEC ret_it(base_it_type::m_p_nd);
     operator++();
     return ret_it;
       }
References __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++(), and PB_DS_IT_C_DEC.
operator--() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_IT_C_DEC& __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator-- () inline
Definition at line 455 of file point_iterators.hpp.
       {
     PB_DS_CONST_IT_C_DEC::operator--();
     return *this;
       }
Referenced by __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator--().
operator--() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_IT_C_DEC __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator-- (int) inline
Definition at line 462 of file point_iterators.hpp.
       {
     PB_DS_IT_C_DEC ret_it(base_it_type::m_p_nd);
     operator--();
     return ret_it;
       }
References __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator--(), and PB_DS_IT_C_DEC.
operator->()
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > pointer __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator-> () const inline
Definition at line 424 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(base_it_type::m_p_nd->m_type == pat_trie_leaf_node_type);
     return &static_cast<leaf_pointer>(base_it_type::m_p_nd)->value();
       }
References _GLIBCXX_DEBUG_ASSERT, and __gnu_pbds::detail::pat_trie_leaf_node_type.
operator=() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_IT_C_DEC& __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator= (const PB_DS_IT_C_DEC & other) inline
Definition at line 409 of file point_iterators.hpp.
       {
     base_it_type::m_p_nd = other.m_p_nd;
     return *this;
       }
operator=() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_IT_C_DEC& __gnu_pbds::detail::pat_trie_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator= (const PB_DS_ODIR_IT_C_DEC & other) inline
Definition at line 417 of file point_iterators.hpp.
       {
     base_it_type::m_p_nd = other.m_p_nd;
     return *this;
       }
Friends And Related Function Documentation
PB_DS_CLASS_C_DEC
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > friend class PB_DS_CLASS_C_DEC friend
Definition at line 472 of file point_iterators.hpp.
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/pat_trie_/point_iterators.hpp