ZEQ2-Lite: Source/Engine/tools/lcc/cpp/cpp.h File Reference
cpp.h File Reference
#include <unistd.h>
#include <fcntl.h>
Data Structures
struct includelist
struct nlist
struct source
struct token
struct tokenrow
Macros
#define EOB 0xFE /* sentinel for end of input buffer */
#define EOF (-1)
#define EOFC 0xFD /* sentinel for end of input file */
#define INS 32768 /* input buffer */
#define ISDEFINED 01 /* has #defined value */
#define ISKW 02 /* is PP keyword */
#define ISMAC 010 /* builtin macro, e.g. __LINE__ */
#define ISUNCHANGE 04 /* can't be #defined in PP */
#define NARG 32 /* Max number arguments to a macro */
#define new(t) (t *)domalloc(sizeof(t))
#define NIF 32 /* depth of nesting of #if */
#define NINCLUDE 32 /* Max number of include directories (-I) */
#define NULL 0
#define OBS 4096 /* outbut buffer */
#define quicklook(a, b) (namebit[(a)&077] & (1<<((b)&037)))
#define quickset(a, b) namebit[(a)&077] |= (1<<((b)&037))
#define rowlen(tokrow) ((tokrow)->lp - (tokrow)->bp)
#define XPWS 1 /* token flag: white space to assure token sep. */
Typedefs
typedef unsigned char uchar
Enumerations
enum errtype { WARNING, ERROR, FATAL }
enum kwtype {
KIF, KIFDEF, KIFNDEF, KELIF,
KELSE, KENDIF, KINCLUDE, KDEFINE,
KUNDEF, KLINE, KWARNING, KERROR,
KPRAGMA, KDEFINED, KLINENO, KFILE,
KDATE, KTIME, KSTDC, KEVAL
}
enum toktype {
END, UNCLASS, NAME, NUMBER,
STRING, CCON, NL, WS,
DSHARP, EQ, NEQ, LEQ,
GEQ, LSH, RSH, LAND,
LOR, PPLUS, MMINUS, ARROW,
SBRA, SKET, LP, RP,
DOT, AND, STAR, PLUS,
MINUS, TILDE, NOT, SLASH,
PCT, LT, GT, CIRC,
OR, QUEST, COLON, ASGN,
COMMA, SHARP, SEMIC, CBRA,
CKET, ASPLUS, ASMINUS, ASSTAR,
ASSLASH, ASPCT, ASCIRC, ASLSH,
ASRSH, ASOR, ASAND, ELLIPS,
DSHARP1, NAME1, DEFINED, UMINUS
}
Functions
void adjustrow (Tokenrow *, int)
void appendDirToIncludeList (char *dir)
char * basepath (char *fname)
void builtin (Tokenrow *, int)
int checkhideset (int, Nlist *)
int comparetokens (Tokenrow *, Tokenrow *)
void control (Tokenrow *)
Tokenrow * copytokenrow (Tokenrow *, Tokenrow *)
int digit (int)
void doadefine (Tokenrow *, int)
void doconcat (Tokenrow *)
void dodefine (Tokenrow *)
void dofree (void *)
void doif (Tokenrow *, enum kwtype)
void doinclude (Tokenrow *)
void * domalloc (int)
void error (enum errtype, char *,...)
long eval (Tokenrow *, int)
void expand (Tokenrow *, Nlist *)
void expandlex (void)
void expandrow (Tokenrow *, char *)
int fillbuf (Source *)
void fixlex (void)
void flushout (void)
int foldline (Source *)
int gatherargs (Tokenrow *, Tokenrow **, int *)
void genline (void)
int gettokens (Tokenrow *, int)
Token * growtokenrow (Tokenrow *)
void iniths (void)
void insertrow (Tokenrow *, int, Tokenrow *)
Nlist * lookup (Token *, int)
int lookuparg (Nlist *, Token *)
void makespace (Tokenrow *)
void maketokenrow (int, Tokenrow *)
void movetokenrow (Tokenrow *, Tokenrow *)
int newhideset (int, Nlist *)
uchar * newstring (uchar *, int, int)
Tokenrow * normtokenrow (Tokenrow *)
char * outnum (char *, int)
void peektokens (Tokenrow *, char *)
void prhideset (int)
void process (Tokenrow *)
void puttokens (Tokenrow *)
void setempty (Tokenrow *)
void setobjname (char *)
Source * setsource (char *, int, char *)
void setup (int, char **)
Tokenrow * stringify (Tokenrow *)
void substargs (Nlist *, Tokenrow *, Tokenrow **)
int trigraph (Source *)
int unionhideset (int, int)
void unsetsource (void)
Variables
int Cplusplus
Source * cursource
char * curtime
int ifdepth
int ifsatisfied [NIF]
int incdepth
Includelist includelist [NINCLUDE]
Nlist * kwdefined
int Mflag
unsigned long namebit [077+1]
Token nltoken
char * outp
int skipping
int verbose
char wd []
Macro Definition Documentation
EOB
#define EOB 0xFE /* sentinel for end of input buffer */
Definition at line 35 of file cpp.h.
EOF
#define EOF (-1)
Definition at line 7 of file cpp.h.
EOFC
#define EOFC 0xFD /* sentinel for end of input file */
Definition at line 36 of file cpp.h.
INS
#define INS 32768 /* input buffer */
Definition at line 1 of file cpp.h.
ISDEFINED
#define ISDEFINED 01 /* has #defined value */
Definition at line 30 of file cpp.h.
ISKW
#define ISKW 02 /* is PP keyword */
Definition at line 31 of file cpp.h.
ISMAC
#define ISMAC 010 /* builtin macro, e.g. __LINE__ */
Definition at line 33 of file cpp.h.
ISUNCHANGE
#define ISUNCHANGE 04 /* can't be #defined in PP */
Definition at line 32 of file cpp.h.
NARG
#define NARG 32 /* Max number arguments to a macro */
Definition at line 3 of file cpp.h.
new
#define new (t) (t *)domalloc(sizeof(t))
Definition at line 83 of file cpp.h.
NIF
#define NIF 32 /* depth of nesting of #if */
Definition at line 5 of file cpp.h.
NINCLUDE
#define NINCLUDE 32 /* Max number of include directories (-I) */
Definition at line 4 of file cpp.h.
NULL
#define NULL 0
Definition at line 10 of file cpp.h.
OBS
#define OBS 4096 /* outbut buffer */
Definition at line 2 of file cpp.h.
quicklook
#define quicklook (a, b) (namebit[(a)&077] & (1<<((b)&037)))
Definition at line 84 of file cpp.h.
quickset
#define quickset (a, b) namebit[(a)&077] |= (1<<((b)&037))
Definition at line 85 of file cpp.h.
rowlen
#define rowlen (tokrow) ((tokrow)->lp - (tokrow)->bp)
Definition at line 142 of file cpp.h.
XPWS
#define XPWS 1 /* token flag: white space to assure token sep. */
Definition at line 37 of file cpp.h.
Typedef Documentation
uchar
typedef unsigned char uchar
Definition at line 14 of file cpp.h.
Enumeration Type Documentation
errtype
enum errtype
Enumerator
WARNING
ERROR
FATAL
Definition at line 88 of file cpp.h.
 { WARNING, ERROR, FATAL };
kwtype
enum kwtype
Enumerator
KIF
KIFDEF
KIFNDEF
KELIF
KELSE
KENDIF
KINCLUDE
KDEFINE
KUNDEF
KLINE
KWARNING
KERROR
KPRAGMA
KDEFINED
KLINENO
KFILE
KDATE
KTIME
KSTDC
KEVAL
Definition at line 26 of file cpp.h.
             { KIF, KIFDEF, KIFNDEF, KELIF, KELSE, KENDIF, KINCLUDE, KDEFINE,
         KUNDEF, KLINE, KWARNING, KERROR, KPRAGMA, KDEFINED,
         KLINENO, KFILE, KDATE, KTIME, KSTDC, KEVAL };
toktype
enum toktype
Enumerator
END
UNCLASS
NAME
NUMBER
STRING
CCON
NL
WS
DSHARP
EQ
NEQ
LEQ
GEQ
LSH
RSH
LAND
LOR
PPLUS
MMINUS
ARROW
SBRA
SKET
LP
RP
DOT
AND
STAR
PLUS
MINUS
TILDE
NOT
SLASH
PCT
LT
GT
CIRC
OR
QUEST
COLON
ASGN
COMMA
SHARP
SEMIC
CBRA
CKET
ASPLUS
ASMINUS
ASSTAR
ASSLASH
ASPCT
ASCIRC
ASLSH
ASRSH
ASOR
ASAND
ELLIPS
DSHARP1
NAME1
DEFINED
UMINUS
Definition at line 17 of file cpp.h.
              { END, UNCLASS, NAME, NUMBER, STRING, CCON, NL, WS, DSHARP,
         EQ, NEQ, LEQ, GEQ, LSH, RSH, LAND, LOR, PPLUS, MMINUS,
         ARROW, SBRA, SKET, LP, RP, DOT, AND, STAR, PLUS, MINUS,
         TILDE, NOT, SLASH, PCT, LT, GT, CIRC, OR, QUEST,
         COLON, ASGN, COMMA, SHARP, SEMIC, CBRA, CKET,
         ASPLUS, ASMINUS, ASSTAR, ASSLASH, ASPCT, ASCIRC, ASLSH,
         ASRSH, ASOR, ASAND, ELLIPS,
         DSHARP1, NAME1, DEFINED, UMINUS };
Function Documentation
adjustrow()
void adjustrow (Tokenrow * , int)
Definition at line 195 of file tokens.c.
 {
     int nby, size;
     if (nt==0)
         return;
     size = (trp->lp - trp->bp) + nt;
     while (size > trp->max)
         growtokenrow(trp);
     /* nby = sizeof(Token) * (trp->lp - trp->tp); */
     nby = (char *)trp->lp - (char *)trp->tp;
     if (nby)
         memmove(trp->tp+nt, trp->tp, nby);
     trp->lp += nt;
 }
References growtokenrow(), and memmove().
Referenced by gatherargs(), and insertrow().
appendDirToIncludeList()
void appendDirToIncludeList (char * dir)
Definition at line 10 of file include.c.
 {
     int i;
     char *fqdir;
     fqdir = (char *)newstring( (uchar *)includelist[NINCLUDE-1].file, 256, 0 );
     strcat( fqdir, "/" );
     strcat( fqdir, dir );
     //avoid adding it more than once
     for (i=NINCLUDE-2; i>=0; i--) {
         if (includelist[i].file &&
                 !strcmp (includelist[i].file, fqdir)) {
             return;
         }
     }
     for (i=NINCLUDE-2; i>=0; i--) {
         if (includelist[i].file==NULL) {
             includelist[i].always = 1;
             includelist[i].file = fqdir;
             break;
         }
     }
     if (i<0)
         error(FATAL, "Too many -I directives");
 }
References includelist::always, dir, error(), FATAL, includelist::file, value::i, newstring(), NINCLUDE, and NULL.
Referenced by doinclude(), and setup().
basepath()
char* basepath (char * fname)
Definition at line 86 of file unix.c.
 {
     char *dp = ".";
     char *p;
     if ((p = strrchr(fname, '/')) != NULL) {
         int dlen = p - fname;
         dp = (char*)newstring((uchar*)fname, dlen+1, 0);
         dp[dlen] = '\0';
     }
     return dp;
 }
References newstring(), and NULL.
Referenced by DefaultPath(), doinclude(), setup(), and UpdatePaths().
builtin()
void builtin (Tokenrow * , int)
Definition at line 457 of file macro.c.
 {
     char *op;
     Token *tp;
     Source *s;
     tp = trp->tp;
     trp->tp++;
     /* need to find the real source */
     s = cursource;
     while (s && s->fd==-1)
         s = s->next;
     if (s==NULL)
         s = cursource;
     /* most are strings */
     tp->type = STRING;
     if (tp->wslen) {
         *outp++ = ' ';
         tp->wslen = 1;
     }
     op = outp;
     *op++ = '"';
     switch (biname) {
     case KLINENO:
         tp->type = NUMBER;
         op = outnum(op-1, s->line);
         break;
     case KFILE: {
         char *src = s->filename;
         while ((*op++ = *src++) != 0)
             if (src[-1] == '\\')
                 *op++ = '\\';
         op--;
         break;
         }
     case KDATE:
         strncpy(op, curtime+4, 7);
         strncpy(op+7, curtime+20, 4);
         op += 11;
         break;
     case KTIME:
         strncpy(op, curtime+11, 8);
         op += 8;
         break;
     default:
         error(ERROR, "cpp botch: unknown internal macro");
         return;
     }
     if (tp->type==STRING)
         *op++ = '"';
     tp->t = (uchar*)outp;
     tp->len = op - outp;
     outp = op;
 }
References cursource, curtime, ERROR, error(), KDATE, KFILE, KLINENO, KTIME, NULL, NUMBER, op, outnum(), outp, and STRING.
Referenced by expandrow().
checkhideset()
int checkhideset (int , Nlist *)
Definition at line 23 of file hideset.c.
 {
     Hideset hsp;
     if (hs>=nhidesets)
         abort();
     for (hsp = hidesets[hs]; *hsp; hsp++) {
         if (*hsp == np)
             return 1;
     }
     return 0;
 }
References hidesets, nhidesets, and np.
Referenced by expandrow().
comparetokens()
int comparetokens (Tokenrow * , Tokenrow *)
Definition at line 107 of file tokens.c.
 {
     Token *tp1, *tp2;
     tp1 = tr1->tp;
     tp2 = tr2->tp;
     if (tr1->lp-tp1 != tr2->lp-tp2)
         return 1;
     for (; tp1<tr1->lp ; tp1++, tp2++) {
         if (tp1->type != tp2->type
          || (tp1->wslen==0) != (tp2->wslen==0)
          || tp1->len != tp2->len
          || strncmp((char*)tp1->t, (char*)tp2->t, tp1->len)!=0)
             return 1;
     }
     return 0;
 }
Referenced by dodefine().
control()
void control (Tokenrow *)
Definition at line 90 of file cpp.c.
 {
     Nlist *np;
     Token *tp;
     tp = trp->tp;
     if (tp->type!=NAME) {
         if (tp->type==NUMBER)
             goto kline;
         if (tp->type != NL)
             error(ERROR, "Unidentifiable control line");
         return;         /* else empty line */
     }
     if ((np = lookup(tp, 0))==NULL || ((np->flag&ISKW)==0 && !skipping)) {
         error(WARNING, "Unknown preprocessor control %t", tp);
         return;
     }
     if (skipping) {
         switch (np->val) {
         case KENDIF:
             if (--ifdepth<skipping)
                 skipping = 0;
             --cursource->ifdepth;
             setempty(trp);
             return;
         case KIFDEF:
         case KIFNDEF:
         case KIF:
             if (++ifdepth >= NIF)
                 error(FATAL, "#if too deeply nested");
             ++cursource->ifdepth;
             return;
         case KELIF:
         case KELSE:
             if (ifdepth<=skipping)
                 break;
             return;
         default:
             return;
         }
     }
     switch (np->val) {
     case KDEFINE:
         dodefine(trp);
         break;
     case KUNDEF:
         tp += 1;
         if (tp->type!=NAME || trp->lp - trp->bp != 4) {
             error(ERROR, "Syntax error in #undef");
             break;
         }
         if ((np = lookup(tp, 0)) != NULL)
             np->flag &= ~ISDEFINED;
         break;
     case KPRAGMA:
         return;
     case KIFDEF:
     case KIFNDEF:
     case KIF:
         if (++ifdepth >= NIF)
             error(FATAL, "#if too deeply nested");
         ++cursource->ifdepth;
         ifsatisfied[ifdepth] = 0;
         if (eval(trp, np->val))
             ifsatisfied[ifdepth] = 1;
         else
             skipping = ifdepth;
         break;
     case KELIF:
         if (ifdepth==0) {
             error(ERROR, "#elif with no #if");
             return;
         }
         if (ifsatisfied[ifdepth]==2)
             error(ERROR, "#elif after #else");
         if (eval(trp, np->val)) {
             if (ifsatisfied[ifdepth])
                 skipping = ifdepth;
             else {
                 skipping = 0;
                 ifsatisfied[ifdepth] = 1;
             }
         } else
             skipping = ifdepth;
         break;
     case KELSE:
         if (ifdepth==0 || cursource->ifdepth==0) {
             error(ERROR, "#else with no #if");
             return;
         }
         if (ifsatisfied[ifdepth]==2)
             error(ERROR, "#else after #else");
         if (trp->lp - trp->bp != 3)
             error(ERROR, "Syntax error in #else");
         skipping = ifsatisfied[ifdepth]? ifdepth: 0;
         ifsatisfied[ifdepth] = 2;
         break;
     case KENDIF:
         if (ifdepth==0 || cursource->ifdepth==0) {
             error(ERROR, "#endif with no #if");
             return;
         }
         --ifdepth;
         --cursource->ifdepth;
         if (trp->lp - trp->bp != 3)
             error(WARNING, "Syntax error in #endif");
         break;
     case KWARNING:
         trp->tp = tp+1;
         error(WARNING, "#warning directive: %r", trp);
         break;
     case KERROR:
         trp->tp = tp+1;
         error(ERROR, "#error directive: %r", trp);
         break;
     case KLINE:
         trp->tp = tp+1;
         expandrow(trp, "<line>");
         tp = trp->bp+2;
     kline:
         if (tp+1>=trp->lp || tp->type!=NUMBER || tp+3<trp->lp
          || ((tp+3==trp->lp && ((tp+1)->type!=STRING))||*(tp+1)->t=='L')){
             error(ERROR, "Syntax error in #line");
             return;
         }
         cursource->line = atol((char*)tp->t)-1;
         if (cursource->line<0 || cursource->line>=32768)
             error(WARNING, "#line specifies number out of range");
         tp = tp+1;
         if (tp+1<trp->lp)
             cursource->filename=(char*)newstring(tp->t+1,tp->len-2,0);
         return;
     case KDEFINED:
         error(ERROR, "Bad syntax for control line");
         break;
     case KINCLUDE:
         doinclude(trp);
         trp->lp = trp->bp;
         return;
     case KEVAL:
         eval(trp, np->val);
         break;
     default:
         error(ERROR, "Preprocessor control `%t' not yet implemented", tp);
         break;
     }
     setempty(trp);
     return;
 }
References cursource, dodefine(), doinclude(), ERROR, error(), eval(), expandrow(), FATAL, ifdepth, ifsatisfied, ISDEFINED, ISKW, KDEFINE, KDEFINED, KELIF, KELSE, KENDIF, KERROR, KEVAL, KIF, KIFDEF, KIFNDEF, KINCLUDE, KLINE, KPRAGMA, KUNDEF, KWARNING, lookup(), NAME, newstring(), NIF, NL, np, NULL, NUMBER, setempty(), skipping, STRING, and WARNING.
Referenced by Controls_Update(), PM_Friction(), PM_NoclipMove(), and process().
copytokenrow()
Tokenrow* copytokenrow (Tokenrow * , Tokenrow *)
Definition at line 216 of file tokens.c.
 {
     int len = rowlen(str);
     maketokenrow(len, dtr);
     movetokenrow(dtr, str);
     dtr->lp += len;
     return dtr;
 }
References maketokenrow(), movetokenrow(), and rowlen.
Referenced by expand(), and substargs().
digit()
int digit (int)
Definition at line 513 of file eval.c.
 {
     if ('0'<=i && i<='9')
         i -= '0';
     else if ('a'<=i && i<='f')
         i -= 'a'-10;
     else if ('A'<=i && i<='F')
         i -= 'A'-10;
     else
         i = -1;
     return i;
 }
References value::i.
Referenced by Com_HexStrToInt(), and tokval().
doadefine()
void doadefine (Tokenrow * , int)
Definition at line 92 of file macro.c.
 {
     Nlist *np;
     static Token onetoken[1] = {{ NUMBER, 0, 0, 0, 1, (uchar*)"1" }};
     static Tokenrow onetr = { onetoken, onetoken, onetoken+1, 1 };
     trp->tp = trp->bp;
     if (type=='U') {
         if (trp->lp-trp->tp != 2 || trp->tp->type!=NAME)
             goto syntax;
         if ((np = lookup(trp->tp, 0)) == NULL)
             return;
         np->flag &= ~ISDEFINED;
         return;
     }
     if (trp->tp >= trp->lp || trp->tp->type!=NAME)
         goto syntax;
     np = lookup(trp->tp, 1);
     np->flag |= ISDEFINED;
     trp->tp += 1;
     if (trp->tp >= trp->lp || trp->tp->type==END) {
         np->vp = &onetr;
         return;
     }
     if (trp->tp->type!=ASGN)
         goto syntax;
     trp->tp += 1;
     if ((trp->lp-1)->type == END)
         trp->lp -= 1;
     np->vp = normtokenrow(trp);
     return;
 syntax:
     error(FATAL, "Illegal -D or -U argument %r", trp);
 }
References ASGN, END, error(), FATAL, ISDEFINED, lookup(), NAME, normtokenrow(), np, NULL, and NUMBER.
Referenced by setup().
doconcat()
void doconcat (Tokenrow *)
Definition at line 360 of file macro.c.
 {
     Token *ltp, *ntp;
     Tokenrow ntr;
     int len;
     for (trp->tp=trp->bp; trp->tp<trp->lp; trp->tp++) {
         if (trp->tp->type==DSHARP1)
             trp->tp->type = DSHARP;
         else if (trp->tp->type==DSHARP) {
             char tt[128];
             ltp = trp->tp-1;
             ntp = trp->tp+1;
             if (ltp<trp->bp || ntp>=trp->lp) {
                 error(ERROR, "## occurs at border of replacement");
                 continue;
             }
             len = ltp->len + ntp->len;
             strncpy((char*)tt, (char*)ltp->t, ltp->len);
             strncpy((char*)tt+ltp->len, (char*)ntp->t, ntp->len);
             tt[len] = '\0';
             setsource("<##>", -1, tt);
             maketokenrow(3, &ntr);
             gettokens(&ntr, 1);
             unsetsource();
             if (ntr.lp-ntr.bp!=2 || ntr.bp->type==UNCLASS)
                 error(WARNING, "Bad token %r produced by ##", &ntr);
             ntr.lp = ntr.bp+1;
             trp->tp = ltp;
             makespace(&ntr);
             insertrow(trp, (ntp-ltp)+1, &ntr);
             dofree(ntr.bp);
             trp->tp--;
         }
     }
 }
References bp, dofree(), DSHARP, DSHARP1, ERROR, error(), gettokens(), insertrow(), makespace(), maketokenrow(), setsource(), UNCLASS, unsetsource(), and WARNING.
Referenced by expand().
dodefine()
void dodefine (Tokenrow *)
Definition at line 10 of file macro.c.
 {
     Token *tp;
     Nlist *np;
     Tokenrow *def, *args;
     tp = trp->tp+1;
     if (tp>=trp->lp || tp->type!=NAME) {
         error(ERROR, "#defined token is not a name");
         return;
     }
     np = lookup(tp, 1);
     if (np->flag&ISUNCHANGE) {
         error(ERROR, "#defined token %t can't be redefined", tp);
         return;
     }
     /* collect arguments */
     tp += 1;
     args = NULL;
     if (tp<trp->lp && tp->type==LP && tp->wslen==0) {
         /* macro with args */
         int narg = 0;
         tp += 1;
         args = new(Tokenrow);
         maketokenrow(2, args);
         if (tp->type!=RP) {
             int err = 0;
             for (;;) {
                 Token *atp;
                 if (tp->type!=NAME) {
                     err++;
                     break;
                 }
                 if (narg>=args->max)
                     growtokenrow(args);
                 for (atp=args->bp; atp<args->lp; atp++)
                     if (atp->len==tp->len
                      && strncmp((char*)atp->t, (char*)tp->t, tp->len)==0)
                         error(ERROR, "Duplicate macro argument");
                 *args->lp++ = *tp;
                 narg++;
                 tp += 1;
                 if (tp->type==RP)
                     break;
                 if (tp->type!=COMMA) {
                     err++;
                     break;
                 }
                 tp += 1;
             }
             if (err) {
                 error(ERROR, "Syntax error in macro parameters");
                 return;
             }
         }
         tp += 1;
     }
     trp->tp = tp;
     if (((trp->lp)-1)->type==NL)
         trp->lp -= 1;
     def = normtokenrow(trp);
     if (np->flag&ISDEFINED) {
         if (comparetokens(def, np->vp)
          || (np->ap==NULL) != (args==NULL)
          || (np->ap && comparetokens(args, np->ap)))
             error(ERROR, "Macro redefinition of %t", trp->bp+2);
     }
     if (args) {
         Tokenrow *tap;
         tap = normtokenrow(args);
         dofree(args->bp);
         args = tap;
     }
     np->ap = args;
     np->vp = def;
     np->flag |= ISDEFINED;
 }
References args, COMMA, comparetokens(), dofree(), ERROR, error(), growtokenrow(), ISDEFINED, ISUNCHANGE, lookup(), LP, maketokenrow(), NAME, NL, normtokenrow(), np, NULL, and RP.
Referenced by control().
dofree()
void dofree (void *)
Definition at line 267 of file cpp.c.
 {
     free(p);
 }
Referenced by doconcat(), dodefine(), expand(), substargs(), and unsetsource().
doif()
void doif (Tokenrow * , enum kwtype)
doinclude()
void doinclude (Tokenrow *)
Definition at line 39 of file include.c.
 {
     char fname[256], iname[256];
     Includelist *ip;
     int angled, len, fd, i;
     trp->tp += 1;
     if (trp->tp>=trp->lp)
         goto syntax;
     if (trp->tp->type!=STRING && trp->tp->type!=LT) {
         len = trp->tp - trp->bp;
         expandrow(trp, "<include>");
         trp->tp = trp->bp+len;
     }
     if (trp->tp->type==STRING) {
         len = trp->tp->len-2;
         if (len > sizeof(fname) - 1)
             len = sizeof(fname) - 1;
         strncpy(fname, (char*)trp->tp->t+1, len);
         angled = 0;
     } else if (trp->tp->type==LT) {
         len = 0;
         trp->tp++;
         while (trp->tp->type!=GT) {
             if (trp->tp>trp->lp || len+trp->tp->len+2 >= sizeof(fname))
                 goto syntax;
             strncpy(fname+len, (char*)trp->tp->t, trp->tp->len);
             len += trp->tp->len;
             trp->tp++;
         }
         angled = 1;
     } else
         goto syntax;
     trp->tp += 2;
     if (trp->tp < trp->lp || len==0)
         goto syntax;
     fname[len] = '\0';
     appendDirToIncludeList( basepath( fname ) );
     if (fname[0]=='/') {
         fd = open(fname, 0);
         strcpy(iname, fname);
     } else for (fd = -1,i=NINCLUDE-1; i>=0; i--) {
         ip = &includelist[i];
         if (ip->file==NULL || ip->deleted || (angled && ip->always==0))
             continue;
         if (strlen(fname)+strlen(ip->file)+2 > sizeof(iname))
             continue;
         strcpy(iname, ip->file);
         strcat(iname, "/");
         strcat(iname, fname);
         if ((fd = open(iname, 0)) >= 0)
             break;
     }
     if ( Mflag>1 || (!angled&&Mflag==1) ) {
         write(1,objname,strlen(objname));
         write(1,iname,strlen(iname));
         write(1,"\n",1);
     }
     if (fd >= 0) {
         if (++incdepth > 10)
             error(FATAL, "#include too deeply nested");
         setsource((char*)newstring((uchar*)iname, strlen(iname), 0), fd, NULL);
         genline();
     } else {
         trp->tp = trp->bp+2;
         error(ERROR, "Could not find include file %r", trp);
     }
     return;
 syntax:
     error(ERROR, "Syntax error in #include");
     return;
 }
References appendDirToIncludeList(), basepath(), ERROR, error(), expandrow(), FATAL, genline(), GT, value::i, incdepth, LT, Mflag, newstring(), NINCLUDE, NULL, objname, setsource(), and STRING.
Referenced by control().
domalloc()
void* domalloc (int)
Definition at line 257 of file cpp.c.
 {
     void *p = malloc(size);
     if (p==NULL)
         error(FATAL, "Out of memory from malloc");
     return p;
 }
References error(), FATAL, and NULL.
Referenced by iniths(), maketokenrow(), newhideset(), newstring(), setobjname(), and setsource().
error()
void error (enum errtype, char * , ...)
Definition at line 273 of file cpp.c.
 {
     va_list ap;
     char *cp, *ep;
     Token *tp;
     Tokenrow *trp;
     Source *s;
     int i;
     fprintf(stderr, "cpp: ");
     for (s=cursource; s; s=s->next)
         if (*s->filename)
             fprintf(stderr, "%s:%d ", s->filename, s->line);
     va_start(ap, string);
     for (ep=string; *ep; ep++) {
         if (*ep=='%') {
             switch (*++ep) {
             case 's':
                 cp = va_arg(ap, char *);
                 fprintf(stderr, "%s", cp);
                 break;
             case 'd':
                 i = va_arg(ap, int);
                 fprintf(stderr, "%d", i);
                 break;
             case 't':
                 tp = va_arg(ap, Token *);
                 fprintf(stderr, "%.*s", tp->len, tp->t);
                 break;
             case 'r':
                 trp = va_arg(ap, Tokenrow *);
                 for (tp=trp->tp; tp<trp->lp&&tp->type!=NL; tp++) {
                     if (tp>trp->tp && tp->wslen)
                         fputc(' ', stderr);
                     fprintf(stderr, "%.*s", tp->len, tp->t);
                 }
                 break;
             default:
                 fputc(*ep, stderr);
                 break;
             }
         } else
             fputc(*ep, stderr);
     }
     va_end(ap);
     fputc('\n', stderr);
     if (type==FATAL)
         exit(1);
     if (type!=WARNING)
         nerrs = 1;
     fflush(stderr);
 }
References cp, cursource, FATAL, nerrs, NL, and WARNING.
Referenced by _spx_lpc(), addrof(), addtree(), allocate(), appendDirToIncludeList(), array(), asgntree(), atop(), backslash(), builtin(), call(), caselabel(), checklab(), checkref(), Com_Error(), control(), dclglobal(), dcllocal(), dclparam(), dclr1(), decl(), deref(), doadefine(), doconcat(), dodefine(), doglobal(), doinclude(), domalloc(), enumdcl(), Error(), eval(), evalop(), exitparams(), expand(), expandrow(), fcon(), field(), fields(), fillbuf(), freturn(), func(), funcdefn(), gatherargs(), genconst(), gettok(), gettokens(), growtokenrow(), initializer(), initvalue(), intexpr(), lvalue(), newfield(), newhideset(), newstruct(), oldparam(), parameters(), postfix(), ppnumber(), primary(), process(), program(), qual(), retcode(), scon(), setup(), specifier(), statement(), stmtlabel(), stringify(), structdcl(), substargs(), subtree(), swstmt(), Sys_Error(), Sys_ErrorDialog(), tokval(), typeerror(), and unary().
eval()
long eval (Tokenrow * , int)
Definition at line 102 of file eval.c.
 {
     Token *tp;
     Nlist *np;
     int ntok, rand;
     trp->tp++;
     if (kw==KIFDEF || kw==KIFNDEF) {
         if (trp->lp - trp->bp != 4 || trp->tp->type!=NAME) {
             error(ERROR, "Syntax error in #ifdef/#ifndef");
             return 0;
         }
         np = lookup(trp->tp, 0);
         return (kw==KIFDEF) == (np && np->flag&(ISDEFINED|ISMAC));
     }
     ntok = trp->tp - trp->bp;
     kwdefined->val = KDEFINED;  /* activate special meaning of defined */
     expandrow(trp, "<if>");
     kwdefined->val = NAME;
     vp = vals;
     op = ops;
     *op++ = END;
     for (rand=0, tp = trp->bp+ntok; tp < trp->lp; tp++) {
         switch(tp->type) {
         case WS:
         case NL:
             continue;
         /* nilary */
         case NAME:
         case NAME1:
         case NUMBER:
         case CCON:
         case STRING:
             if (rand)
                 goto syntax;
             *vp++ = tokval(tp);
             rand = 1;
             continue;
         /* unary */
         case DEFINED:
         case TILDE:
         case NOT:
             if (rand)
                 goto syntax;
             *op++ = tp->type;
             continue;
         /* unary-binary */
         case PLUS: case MINUS: case STAR: case AND:
             if (rand==0) {
                 if (tp->type==MINUS)
                     *op++ = UMINUS;
                 if (tp->type==STAR || tp->type==AND) {
                     error(ERROR, "Illegal operator * or & in #if/#elsif");
                     return 0;
                 }
                 continue;
             }
             /* flow through */
         /* plain binary */
         case EQ: case NEQ: case LEQ: case GEQ: case LSH: case RSH:
         case LAND: case LOR: case SLASH: case PCT:
         case LT: case GT: case CIRC: case OR: case QUEST:
         case COLON: case COMMA:
             if (rand==0)
                 goto syntax;
             if (evalop(priority[tp->type])!=0)
                 return 0;
             *op++ = tp->type;
             rand = 0;
             continue;
         case LP:
             if (rand)
                 goto syntax;
             *op++ = LP;
             continue;
         case RP:
             if (!rand)
                 goto syntax;
             if (evalop(priority[RP])!=0)
                 return 0;
             if (op<=ops || op[-1]!=LP) {
                 goto syntax;
             }
             op--;
             continue;
         default:
             error(ERROR,"Bad operator (%t) in #if/#elsif", tp);
             return 0;
         }
     }
     if (rand==0)
         goto syntax;
     if (evalop(priority[END])!=0)
         return 0;
     if (op!=&ops[1] || vp!=&vals[1]) {
         error(ERROR, "Botch in #if/#elsif");
         return 0;
     }
     if (vals[0].type==UND)
         error(ERROR, "Undefined expression value");
     return vals[0].val;
 syntax:
     error(ERROR, "Syntax error in #if/#elsif");
     return 0;
 }
References AND, CCON, CIRC, COLON, COMMA, DEFINED, END, EQ, ERROR, error(), evalop(), expandrow(), GEQ, GT, ISDEFINED, ISMAC, KDEFINED, KIFDEF, KIFNDEF, kwdefined, LAND, LEQ, lookup(), LOR, LP, LSH, LT, MINUS, NAME, NAME1, NEQ, NL, NOT, np, NUMBER, op, ops, OR, PCT, PLUS, priority, QUEST, RP, RSH, SLASH, STAR, STRING, TILDE, tokval(), UMINUS, UND, value::val, vals, vp, and WS.
Referenced by control().
expand()
void expand (Tokenrow * , Nlist *)
Definition at line 178 of file macro.c.
 {
     Tokenrow ntr;
     int ntokc, narg, i;
     Token *tp;
     Tokenrow *atr[NARG+1];
     int hs;
     copytokenrow(&ntr, np->vp);     /* copy macro value */
     if (np->ap==NULL)           /* parameterless */
         ntokc = 1;
     else {
         ntokc = gatherargs(trp, atr, &narg);
         if (narg<0) {           /* not actually a call (no '(') */
             trp->tp++;
             return;
         }
         if (narg != rowlen(np->ap)) {
             error(ERROR, "Disagreement in number of macro arguments");
             trp->tp->hideset = newhideset(trp->tp->hideset, np);
             trp->tp += ntokc;
             return;
         }
         substargs(np, &ntr, atr);   /* put args into replacement */
         for (i=0; i<narg; i++) {
             dofree(atr[i]->bp);
             dofree(atr[i]);
         }
     }
     doconcat(&ntr);             /* execute ## operators */
     hs = newhideset(trp->tp->hideset, np);
     for (tp=ntr.bp; tp<ntr.lp; tp++) {  /* distribute hidesets */
         if (tp->type==NAME) {
             if (tp->hideset==0)
                 tp->hideset = hs;
             else
                 tp->hideset = unionhideset(tp->hideset, hs);
         }
     }
     ntr.tp = ntr.bp;
     insertrow(trp, ntokc, &ntr);
     trp->tp -= rowlen(&ntr);
     dofree(ntr.bp);
     return;
 }
References bp, copytokenrow(), doconcat(), dofree(), ERROR, error(), gatherargs(), insertrow(), NAME, NARG, newhideset(), np, NULL, rowlen, substargs(), and unionhideset().
Referenced by expandrow().
expandlex()
void expandlex (void)
Definition at line 239 of file lex.c.
 {
     /*const*/ struct fsm *fp;
     int i, j, nstate;
     for (fp = fsm; fp->state>=0; fp++) {
         for (i=0; fp->ch[i]; i++) {
             nstate = fp->nextstate;
             if (nstate >= S_SELF)
                 nstate = ~nstate;
             switch (fp->ch[i]) {
             case C_XX:      /* random characters */
                 for (j=0; j<256; j++)
                     bigfsm[j][fp->state] = nstate;
                 continue;
             case C_ALPH:
                 for (j=0; j<=256; j++)
                     if (('a'<=j&&j<='z') || ('A'<=j&&j<='Z')
                       || j=='_')
                         bigfsm[j][fp->state] = nstate;
                 continue;
             case C_NUM:
                 for (j='0'; j<='9'; j++)
                     bigfsm[j][fp->state] = nstate;
                 continue;
             default:
                 bigfsm[fp->ch[i]][fp->state] = nstate;
             }
         }
     }
     /* install special cases for ? (trigraphs),  \ (splicing), runes, and EOB */
     for (i=0; i<MAXSTATE; i++) {
         for (j=0; j<0xFF; j++)
             if (j=='?' || j=='\\') {
                 if (bigfsm[j][i]>0)
                     bigfsm[j][i] = ~bigfsm[j][i];
                 bigfsm[j][i] &= ~QBSBIT;
             }
         bigfsm[EOB][i] = ~S_EOB;
         if (bigfsm[EOFC][i]>=0)
             bigfsm[EOFC][i] = ~S_EOF;
     }
 }
References bigfsm, C_ALPH, C_NUM, C_XX, EOB, EOFC, fp, MAXSTATE, QBSBIT, S_EOB, S_EOF, and S_SELF.
Referenced by main().
expandrow()
void expandrow (Tokenrow * , char *)
Definition at line 132 of file macro.c.
 {
     Token *tp;
     Nlist *np;
     if (flag)
         setsource(flag, -1, "");
     for (tp = trp->tp; tp<trp->lp; ) {
         if (tp->type!=NAME
          || quicklook(tp->t[0], tp->len>1?tp->t[1]:0)==0
          || (np = lookup(tp, 0))==NULL
          || (np->flag&(ISDEFINED|ISMAC))==0
          || (tp->hideset && checkhideset(tp->hideset, np))) {
             tp++;
             continue;
         }
         trp->tp = tp;
         if (np->val==KDEFINED) {
             tp->type = DEFINED;
             if ((tp+1)<trp->lp && (tp+1)->type==NAME)
                 (tp+1)->type = NAME1;
             else if ((tp+3)<trp->lp && (tp+1)->type==LP
              && (tp+2)->type==NAME && (tp+3)->type==RP)
                 (tp+2)->type = NAME1;
             else
                 error(ERROR, "Incorrect syntax for `defined'");
             tp++;
             continue;
         }
         if (np->flag&ISMAC)
             builtin(trp, np->val);
         else {
             expand(trp, np);
         }
         tp = trp->tp;
     }
     if (flag)
         unsetsource();
 }
References builtin(), checkhideset(), DEFINED, ERROR, error(), expand(), ISDEFINED, ISMAC, KDEFINED, lookup(), LP, NAME, NAME1, np, NULL, quicklook, RP, setsource(), and unsetsource().
Referenced by control(), doinclude(), eval(), process(), and substargs().
fillbuf()
int fillbuf (Source *)
Definition at line 515 of file lex.c.
 {
     int n, nr;
     nr = INS/8;
     if ((char *)s->inl+nr > (char *)s->inb+INS)
         error(FATAL, "Input buffer overflow");
     if (s->fd<0 || (n=read(s->fd, (char *)s->inl, INS/8)) <= 0)
         n = 0;
     if ((*s->inp&0xff) == EOB) /* sentinel character appears in input */
         *s->inp = EOFC;
     s->inl += n;
     s->inl[0] = s->inl[1]= s->inl[2]= s->inl[3] = EOB;
     if (n==0) {
         s->inl[0] = s->inl[1]= s->inl[2]= s->inl[3] = EOFC;
         return EOF;
     }
     return 0;
 }
References EOB, EOF, EOFC, error(), FATAL, and INS.
Referenced by foldline(), gettok(), gettokens(), scon(), and trigraph().
fixlex()
void fixlex (void)
Definition at line 285 of file lex.c.
 {
     /* do C++ comments? */
     if (Cplusplus==0)
         bigfsm['/'][COM1] = bigfsm['x'][COM1];
 }
References bigfsm, COM1, and Cplusplus.
Referenced by main().
flushout()
void flushout (void)
Definition at line 328 of file tokens.c.
 {
     if (wbp>wbuf) {
         write(1, wbuf, wbp-wbuf);
         wbp = wbuf;
     }
 }
References wbp, and wbuf.
Referenced by main(), peektokens(), and puttokens().
foldline()
int foldline (Source *)
Definition at line 502 of file lex.c.
 {
     while (s->inp+1 >= s->inl && fillbuf(s)!=EOF)
         ;
     if (s->inp[1] == '\n') {
         memmove(s->inp, s->inp+2, s->inl-s->inp+3);
         s->inl -= 2;
         return 1;
     }
     return 0;
 }
References EOF, fillbuf(), and memmove().
Referenced by gettokens().
gatherargs()
int gatherargs (Tokenrow * , Tokenrow ** , int *)
Definition at line 230 of file macro.c.
 {
     int parens = 1;
     int ntok = 0;
     Token *bp, *lp;
     Tokenrow ttr;
     int ntokp;
     int needspace;
     *narg = -1;         /* means that there is no macro call */
     /* look for the ( */
     for (;;) {
         trp->tp++;
         ntok++;
         if (trp->tp >= trp->lp) {
             gettokens(trp, 0);
             if ((trp->lp-1)->type==END) {
                 trp->lp -= 1;
                 trp->tp -= ntok;
                 return ntok;
             }
         }
         if (trp->tp->type==LP)
             break;
         if (trp->tp->type!=NL)
             return ntok;
     }
     *narg = 0;
     ntok++;
     ntokp = ntok;
     trp->tp++;
     /* search for the terminating ), possibly extending the row */
     needspace = 0;
     while (parens>0) {
         if (trp->tp >= trp->lp)
             gettokens(trp, 0);
         if (needspace) {
             needspace = 0;
             makespace(trp);
         }
         if (trp->tp->type==END) {
             trp->lp -= 1;
             trp->tp -= ntok;
             error(ERROR, "EOF in macro arglist");
             return ntok;
         }
         if (trp->tp->type==NL) {
             trp->tp += 1;
             adjustrow(trp, -1);
             trp->tp -= 1;
             makespace(trp);
             needspace = 1;
             continue;
         }
         if (trp->tp->type==LP)
             parens++;
         else if (trp->tp->type==RP)
             parens--;
         trp->tp++;
         ntok++;
     }
     trp->tp -= ntok;
     /* Now trp->tp won't move underneath us */
     lp = bp = trp->tp+ntokp;
     for (; parens>=0; lp++) {
         if (lp->type == LP) {
             parens++;
             continue;
         }
         if (lp->type==RP)
             parens--;
         if (lp->type==DSHARP)
             lp->type = DSHARP1; /* ## not special in arg */
         if ((lp->type==COMMA && parens==0) || (parens<0 && (lp-1)->type!=LP)) {
             if (*narg>=NARG-1)
                 error(FATAL, "Sorry, too many macro arguments");
             ttr.bp = ttr.tp = bp;
             ttr.lp = lp;
             atr[(*narg)++] = normtokenrow(&ttr);
             bp = lp+1;
         }
     }
     return ntok;
 }
References adjustrow(), bp, COMMA, DSHARP, DSHARP1, END, ERROR, error(), FATAL, gettokens(), LP, makespace(), NARG, NL, normtokenrow(), and RP.
Referenced by expand().
genline()
void genline (void)
Definition at line 118 of file include.c.
 {
     static Token ta = { UNCLASS };
     static Tokenrow tr = { &ta, &ta, &ta+1, 1 };
     uchar *p;
     ta.t = p = (uchar*)outp;
     strcpy((char*)p, "#line ");
     p += sizeof("#line ")-1;
     p = (uchar*)outnum((char*)p, cursource->line);
     *p++ = ' '; *p++ = '"';
     if (cursource->filename[0]!='/' && wd[0]) {
         strcpy((char*)p, wd);
         p += strlen(wd);
         *p++ = '/';
     }
     strcpy((char*)p, cursource->filename);
     p += strlen((char*)p);
     *p++ = '"'; *p++ = '\n';
     ta.len = (char*)p-outp;
     outp = (char*)p;
     tr.tp = tr.bp;
     puttokens(&tr);
 }
References cursource, outnum(), outp, puttokens(), tr, UNCLASS, and wd.
Referenced by doinclude(), main(), and process().
gettokens()
int gettokens (Tokenrow * , int)
Definition at line 300 of file lex.c.
 {
     register int c, state, oldstate;
     register uchar *ip;
     register Token *tp, *maxp;
     int runelen;
     Source *s = cursource;
     int nmac = 0;
     tp = trp->lp;
     ip = s->inp;
     if (reset) {
         s->lineinc = 0;
         if (ip>=s->inl) {       /* nothing in buffer */
             s->inl = s->inb;
             fillbuf(s);
             ip = s->inp = s->inb;
         } else if (ip >= s->inb+(3*INS/4)) {
             memmove(s->inb, ip, 4+s->inl-ip);
             s->inl = s->inb+(s->inl-ip);
             ip = s->inp = s->inb;
         }
     }
     maxp = &trp->bp[trp->max];
     runelen = 1;
     for (;;) {
        continue2:
         if (tp>=maxp) {
             trp->lp = tp;
             tp = growtokenrow(trp);
             maxp = &trp->bp[trp->max];
         }
         tp->type = UNCLASS;
         tp->hideset = 0;
         tp->t = ip;
         tp->wslen = 0;
         tp->flag = 0;
         state = START;
         for (;;) {
             oldstate = state;
             c = *ip;
             if ((state = bigfsm[c][state]) >= 0) {
                 ip += runelen;
                 runelen = 1;
                 continue;
             }
             state = ~state;
         reswitch:
             switch (state&0177) {
             case S_SELF:
                 ip += runelen;
                 runelen = 1;
             case S_SELFB:
                 tp->type = GETACT(state);
                 tp->len = ip - tp->t;
                 tp++;
                 goto continue2;
             case S_NAME:    /* like S_SELFB but with nmac check */
                 tp->type = NAME;
                 tp->len = ip - tp->t;
                 nmac |= quicklook(tp->t[0], tp->len>1?tp->t[1]:0);
                 tp++;
                 goto continue2;
             case S_WS:
                 tp->wslen = ip - tp->t;
                 tp->t = ip;
                 state = START;
                 continue;
             default:
                 if ((state&QBSBIT)==0) {
                     ip += runelen;
                     runelen = 1;
                     continue;
                 }
                 state &= ~QBSBIT;
                 s->inp = ip;
                 if (c=='?') {   /* check trigraph */
                     if (trigraph(s)) {
                         state = oldstate;
                         continue;
                     }
                     goto reswitch;
                 }
                 if (c=='\\') { /* line-folding */
                     if (foldline(s)) {
                         s->lineinc++;
                         state = oldstate;
                         continue;
                     }
                     goto reswitch;
                 }
                 error(WARNING, "Lexical botch in cpp");
                 ip += runelen;
                 runelen = 1;
                 continue;
             case S_EOB:
                 s->inp = ip;
                 fillbuf(cursource);
                 state = oldstate;
                 continue;
             case S_EOF:
                 tp->type = END;
                 tp->len = 0;
                 s->inp = ip;
                 if (tp!=trp->bp && (tp-1)->type!=NL && cursource->fd!=-1)
                     error(WARNING,"No newline at end of file");
                 trp->lp = tp+1;
                 return nmac;
             case S_STNL:
                 error(ERROR, "Unterminated string or char const");
             case S_NL:
                 tp->t = ip;
                 tp->type = NL;
                 tp->len = 1;
                 tp->wslen = 0;
                 s->lineinc++;
                 s->inp = ip+1;
                 trp->lp = tp+1;
                 return nmac;
             case S_EOFSTR:
                 error(FATAL, "EOF in string or char constant");
                 break;
             case S_COMNL:
                 s->lineinc++;
                 state = COM2;
                 ip += runelen;
                 runelen = 1;
                 if (ip >= s->inb+(7*INS/8)) { /* very long comment */
                     memmove(tp->t, ip, 4+s->inl-ip);
                     s->inl -= ip-tp->t;
                     ip = tp->t+1;
                 }
                 continue;
             case S_EOFCOM:
                 error(WARNING, "EOF inside comment");
                 --ip;
             case S_COMMENT:
                 ++ip;
                 tp->t = ip;
                 tp->t[-1] = ' ';
                 tp->wslen = 1;
                 state = START;
                 continue;
             }
             break;
         }
         ip += runelen;
         runelen = 1;
         tp->len = ip - tp->t;
         tp++;
     }
 }
References bigfsm, COM2, cursource, END, ERROR, error(), FATAL, fillbuf(), foldline(), GETACT, growtokenrow(), INS, memmove(), NAME, NL, QBSBIT, quicklook, S_COMMENT, S_COMNL, S_EOB, S_EOF, S_EOFCOM, S_EOFSTR, S_NAME, S_NL, S_SELF, S_SELFB, S_STNL, S_WS, START, trigraph(), UNCLASS, and WARNING.
Referenced by doconcat(), gatherargs(), process(), and setup().
growtokenrow()
Token* growtokenrow (Tokenrow *)
Definition at line 89 of file tokens.c.
 {
     int ncur = trp->tp - trp->bp;
     int nlast = trp->lp - trp->bp;
     trp->max = 3*trp->max/2 + 1;
     trp->bp = (Token *)realloc(trp->bp, trp->max*sizeof(Token));
     if (trp->bp == NULL)
         error(FATAL, "Out of memory from realloc");
     trp->lp = &trp->bp[nlast];
     trp->tp = &trp->bp[ncur];
     return trp->lp;
 }
References error(), FATAL, and NULL.
Referenced by adjustrow(), dodefine(), and gettokens().
iniths()
void iniths (void)
Definition at line 95 of file hideset.c.
 {
     hidesets = (Hideset *)domalloc(maxhidesets*sizeof(Hideset *));
     hidesets[0] = (Hideset)domalloc(sizeof(Hideset));
     *hidesets[0] = NULL;
     nhidesets++;
 }
References domalloc(), hidesets, maxhidesets, nhidesets, and NULL.
Referenced by main().
insertrow()
void insertrow (Tokenrow * , int , Tokenrow *)
Definition at line 131 of file tokens.c.
 {
     int nrtok = rowlen(str);
     dtr->tp += ntok;
     adjustrow(dtr, nrtok-ntok);
     dtr->tp -= ntok;
     movetokenrow(dtr, str);
     makespace(dtr);
     dtr->tp += nrtok;
     makespace(dtr);
 }
References adjustrow(), makespace(), movetokenrow(), and rowlen.
Referenced by doconcat(), expand(), and substargs().
lookup()
Nlist* lookup (Token * , int)
Definition at line 73 of file nlist.c.
 {
     unsigned int h;
     Nlist *np;
     uchar *cp, *cpe;
     h = 0;
     for (cp=tp->t, cpe=cp+tp->len; cp<cpe; )
         h += *cp++;
     h %= NLSIZE;
     np = nlist[h];
     while (np) {
         if (*tp->t==*np->name && tp->len==np->len
          && strncmp((char*)tp->t, (char*)np->name, tp->len)==0)
             return np;
         np = np->next;
     }
     if (install) {
         np = new(Nlist);
         np->vp = NULL;
         np->ap = NULL;
         np->flag = 0;
         np->val = 0;
         np->len = tp->len;
         np->name = newstring(tp->t, tp->len, 0);
         np->next = nlist[h];
         nlist[h] = np;
         quickset(tp->t[0], tp->len>1? tp->t[1]:0);
         return np;
     }
     return NULL;
 }
References cp, install(), newstring(), NLSIZE, np, NULL, and quickset.
Referenced by control(), dclglobal(), dcllocal(), dclparam(), decl(), doadefine(), dodefine(), enumdcl(), eval(), expandrow(), fieldref(), funcdefn(), gettok(), newstruct(), primary(), setup_kwtab(), statement(), stmtlabel(), structdcl(), and tokval().
lookuparg()
int lookuparg (Nlist * , Token *)
Definition at line 403 of file macro.c.
 {
     Token *ap;
     if (tp->type!=NAME || mac->ap==NULL)
         return -1;
     for (ap=mac->ap->bp; ap<mac->ap->lp; ap++) {
         if (ap->len==tp->len && strncmp((char*)ap->t,(char*)tp->t,ap->len)==0)
             return ap - mac->ap->bp;
     }
     return -1;
 }
References NAME, and NULL.
Referenced by substargs().
makespace()
void makespace (Tokenrow *)
Definition at line 148 of file tokens.c.
 {
     uchar *tt;
     Token *tp = trp->tp;
     if (tp >= trp->lp)
         return;
     if (tp->wslen) {
         if (tp->flag&XPWS
          && (wstab[tp->type] || (trp->tp>trp->bp && wstab[(tp-1)->type]))) {
             tp->wslen = 0;
             return;
         }
         tp->t[-1] = ' ';
         return;
     }
     if (wstab[tp->type] || (trp->tp>trp->bp && wstab[(tp-1)->type]))
         return;
     tt = newstring(tp->t, tp->len, 1);
     *tt++ = ' ';
     tp->t = tt;
     tp->wslen = 1;
     tp->flag |= XPWS;
 }
References newstring(), wstab, and XPWS.
Referenced by doconcat(), gatherargs(), and insertrow().
maketokenrow()
void maketokenrow (int , Tokenrow *)
Definition at line 77 of file tokens.c.
 {
     trp->max = size;
     if (size>0)
         trp->bp = (Token *)domalloc(size*sizeof(Token));
     else
         trp->bp = NULL;
     trp->tp = trp->bp;
     trp->lp = trp->bp;
 }
References domalloc(), and NULL.
Referenced by copytokenrow(), doconcat(), dodefine(), main(), normtokenrow(), and setup().
movetokenrow()
void movetokenrow (Tokenrow * , Tokenrow *)
Definition at line 179 of file tokens.c.
 {
     int nby;
     /* nby = sizeof(Token) * (str->lp - str->bp); */
     nby = (char *)str->lp - (char *)str->bp;
     memmove(dtr->tp, str->bp, nby);
 }
References memmove().
Referenced by copytokenrow(), and insertrow().
newhideset()
int newhideset (int , Nlist *)
Definition at line 40 of file hideset.c.
 {
     int i, len;
     Nlist *nhs[HSSIZ+3];
     Hideset hs1, hs2;
     len = inserths(nhs, hidesets[hs], np);
     for (i=0; i<nhidesets; i++) {
         for (hs1=nhs, hs2=hidesets[i]; *hs1==*hs2; hs1++, hs2++)
             if (*hs1 == NULL)
                 return i;
     }
     if (len>=HSSIZ)
         return hs;
     if (nhidesets >= maxhidesets) {
         maxhidesets = 3*maxhidesets/2+1;
         hidesets = (Hideset *)realloc(hidesets, (sizeof (Hideset *))*maxhidesets);
         if (hidesets == NULL)
             error(FATAL, "Out of memory from realloc");
     }
     hs1 = (Hideset)domalloc(len*sizeof(Hideset));
     memmove(hs1, nhs, len*sizeof(Hideset));
     hidesets[nhidesets] = hs1;
     return nhidesets++;
 }
References domalloc(), error(), FATAL, hidesets, HSSIZ, value::i, inserths(), maxhidesets, memmove(), nhidesets, np, and NULL.
Referenced by expand(), and unionhideset().
newstring()
uchar* newstring (uchar * , int , int)
Definition at line 364 of file tokens.c.
 {
     uchar *ns = (uchar *)domalloc(l+o+1);
     ns[l+o] = '\0';
     return (uchar*)strncpy((char*)ns+o, (char*)s, l) - o;
 }
References domalloc().
Referenced by appendDirToIncludeList(), basepath(), control(), doinclude(), lookup(), makespace(), normtokenrow(), setup(), and stringify().
normtokenrow()
Tokenrow* normtokenrow (Tokenrow *)
Definition at line 232 of file tokens.c.
 {
     Token *tp;
     Tokenrow *ntrp = new(Tokenrow);
     int len;
     len = trp->lp - trp->tp;
     if (len<=0)
         len = 1;
     maketokenrow(len, ntrp);
     for (tp=trp->tp; tp < trp->lp; tp++) {
         *ntrp->lp = *tp;
         if (tp->len) {
             ntrp->lp->t = newstring(tp->t, tp->len, 1);
             *ntrp->lp->t++ = ' ';
             if (tp->wslen)
                 ntrp->lp->wslen = 1;
         }
         ntrp->lp++;
     }
     if (ntrp->lp > ntrp->bp)
         ntrp->bp->wslen = 0;
     return ntrp;
 }
References maketokenrow(), and newstring().
Referenced by doadefine(), dodefine(), and gatherargs().
outnum()
char* outnum (char * , int)
Definition at line 351 of file tokens.c.
 {
     if (n>=10)
         p = outnum(p, n/10);
     *p++ = n%10 + '0';
     return p;
 }
Referenced by builtin(), and genline().
peektokens()
void peektokens (Tokenrow * , char *)
Definition at line 261 of file tokens.c.
 {
     Token *tp;
     tp = trp->tp;
     flushout();
     if (str)
         fprintf(stderr, "%s ", str);
     if (tp<trp->bp || tp>trp->lp)
         fprintf(stderr, "(tp offset %ld) ", (long int) (tp - trp->bp));
     for (tp=trp->bp; tp<trp->lp && tp<trp->bp+32; tp++) {
         if (tp->type!=NL) {
             int c = tp->t[tp->len];
             tp->t[tp->len] = 0;
             fprintf(stderr, "%s", tp->t);
             tp->t[tp->len] = c;
         }
         if (tp->type==NAME) {
             fprintf(stderr, tp==trp->tp?"{*":"{");
             prhideset(tp->hideset);
             fprintf(stderr, "} ");
         } else
             fprintf(stderr, tp==trp->tp?"{%x*} ":"{%x} ", tp->type);
     }
     fprintf(stderr, "\n");
     fflush(stderr);
 }
References bp, flushout(), NAME, NL, and prhideset().
Referenced by puttokens().
prhideset()
void prhideset (int)
Definition at line 104 of file hideset.c.
 {
     Hideset np;
     for (np = hidesets[hs]; *np; np++) {
         fprintf(stderr, (char*)(*np)->name, (*np)->len);
         fprintf(stderr, " ");
     }
 }
References hidesets, and np.
Referenced by peektokens().
process()
void process (Tokenrow *)
Definition at line 47 of file cpp.c.
 {
     int anymacros = 0;
     for (;;) {
         if (trp->tp >= trp->lp) {
             trp->tp = trp->lp = trp->bp;
             outp = outbuf;
             anymacros |= gettokens(trp, 1);
             trp->tp = trp->bp;
         }
         if (trp->tp->type == END) {
             if (--incdepth>=0) {
                 if (cursource->ifdepth)
                     error(ERROR,
                      "Unterminated conditional in #include");
                 unsetsource();
                 cursource->line += cursource->lineinc;
                 trp->tp = trp->lp;
                 genline();
                 continue;
             }
             if (ifdepth)
                 error(ERROR, "Unterminated #if/#ifdef/#ifndef");
             break;
         }
         if (trp->tp->type==SHARP) {
             trp->tp += 1;
             control(trp);
         } else if (!skipping && anymacros)
             expandrow(trp, NULL);
         if (skipping)
             setempty(trp);
         puttokens(trp);
         anymacros = 0;
         cursource->line += cursource->lineinc;
         if (cursource->lineinc>1) {
             genline();
         }
     }
 }
References control(), cursource, END, ERROR, error(), expandrow(), genline(), gettokens(), ifdepth, incdepth, NULL, outbuf, outp, puttokens(), setempty(), SHARP, skipping, and unsetsource().
Referenced by main(), and prof_init().
puttokens()
void puttokens (Tokenrow *)
Definition at line 290 of file tokens.c.
 {
     Token *tp;
     int len;
     uchar *p;
     if (verbose)
         peektokens(trp, "");
     tp = trp->bp;
     for (; tp<trp->lp; tp++) {
         len = tp->len+tp->wslen;
         p = tp->t-tp->wslen;
         while (tp<trp->lp-1 && p+len == (tp+1)->t - (tp+1)->wslen) {
             tp++;
             len += tp->wslen+tp->len;
         }
         if (len>OBS/2) {        /* handle giant token */
             if (wbp > wbuf)
                 write(1, wbuf, wbp-wbuf);
             write(1, (char *)p, len);
             wbp = wbuf;
         } else {
             memcpy(wbp, p, len);
             wbp += len;
         }
         if (wbp >= &wbuf[OBS]) {
             write(1, wbuf, OBS);
             if (wbp > &wbuf[OBS])
                 memcpy(wbuf, wbuf+OBS, wbp - &wbuf[OBS]);
             wbp -= OBS;
         }
     }
     trp->tp = tp;
     if (cursource->fd==0)
         flushout();
 }
References cursource, flushout(), OBS, peektokens(), verbose, wbp, and wbuf.
Referenced by genline(), and process().
setempty()
void setempty (Tokenrow *)
Definition at line 340 of file tokens.c.
 {
     trp->tp = trp->bp;
     trp->lp = trp->bp+1;
     *trp->bp = nltoken;
 }
References nltoken.
Referenced by control(), and process().
setobjname()
void setobjname (char *)
Definition at line 144 of file include.c.
 {
     int n = strlen(f);
     objname = (char*)domalloc(n+5);
     strcpy(objname,f);
     if(objname[n-2]=='.'){
         strcpy(objname+n-1,"$O: ");
     }else{
         strcpy(objname+n,"$O: ");
     }
 }
References domalloc(), and objname.
Referenced by setup().
setsource()
Source* setsource (char * , int , char *)
Definition at line 541 of file lex.c.
 {
     Source *s = new(Source);
     int len;
     s->line = 1;
     s->lineinc = 0;
     s->fd = fd;
     s->filename = name;
     s->next = cursource;
     s->ifdepth = 0;
     cursource = s;
     /* slop at right for EOB */
     if (str) {
         len = strlen(str);
         s->inb = domalloc(len+4);
         s->inp = s->inb;
         strncpy((char *)s->inp, str, len);
     } else {
         s->inb = domalloc(INS+4);
         s->inp = s->inb;
         len = 0;
     }
     s->inl = s->inp+len;
     s->inl[0] = s->inl[1] = EOB;
     return s;
 }
References cursource, domalloc(), EOB, and INS.
Referenced by doconcat(), doinclude(), expandrow(), and setup().
setup()
void setup (int , char **)
Definition at line 16 of file unix.c.
 {
     int c, fd, i;
     char *fp, *dp;
     Tokenrow tr;
     extern void setup_kwtab(void);
     uchar *includeDirs[ NINCLUDE ] = { 0 };
     int   numIncludeDirs = 0;
     setup_kwtab();
     while ((c = lcc_getopt(argc, argv, "MNOVv+I:D:U:F:lg")) != -1)
         switch (c) {
         case 'N':
             for (i=0; i<NINCLUDE; i++)
                 if (includelist[i].always==1)
                     includelist[i].deleted = 1;
             break;
         case 'I':
             includeDirs[ numIncludeDirs++ ] = newstring( (uchar *)optarg, strlen( optarg ), 0 );
             break;
         case 'D':
         case 'U':
             setsource("<cmdarg>", -1, optarg);
             maketokenrow(3, &tr);
             gettokens(&tr, 1);
             doadefine(&tr, c);
             unsetsource();
             break;
         case 'M':
             Mflag++;
             break;
         case 'v':
             fprintf(stderr, "%s %s\n", argv[0], rcsid);
             break;
         case 'V':
             verbose++;
             break;
         case '+':
             Cplusplus++;
             break;
         default:
             break;
         }
     dp = ".";
     fp = "<stdin>";
     fd = 0;
     if (optind<argc) {
         dp = basepath( argv[optind] );
         fp = (char*)newstring((uchar*)argv[optind], strlen(argv[optind]), 0);
         if ((fd = open(fp, 0)) <= 0)
             error(FATAL, "Can't open input file %s", fp);
     }
     if (optind+1<argc) {
         int fdo = creat(argv[optind+1], 0666);
         if (fdo<0)
             error(FATAL, "Can't open output file %s", argv[optind+1]);
         dup2(fdo, 1);
     }
     if(Mflag)
         setobjname(fp);
     includelist[NINCLUDE-1].always = 0;
     includelist[NINCLUDE-1].file = dp;
     for( i = 0; i < numIncludeDirs; i++ )
         appendDirToIncludeList( (char *)includeDirs[ i ] );
     setsource(fp, fd, NULL);
 }
References includelist::always, appendDirToIncludeList(), basepath(), Cplusplus, includelist::deleted, doadefine(), error(), FATAL, includelist::file, fp, gettokens(), lcc_getopt(), maketokenrow(), Mflag, newstring(), NINCLUDE, NULL, optarg, optind, rcsid, setobjname(), setsource(), setup_kwtab(), tr, unsetsource(), and verbose.
Referenced by main().
stringify()
Tokenrow* stringify (Tokenrow *)
Definition at line 421 of file macro.c.
 {
     static Token t = { STRING };
     static Tokenrow tr = { &t, &t, &t+1, 1 };
     Token *tp;
     uchar s[STRLEN];
     uchar *sp = s, *cp;
     int i, instring;
     *sp++ = '"';
     for (tp = vp->bp; tp < vp->lp; tp++) {
         instring = tp->type==STRING || tp->type==CCON;
         if (sp+2*tp->len >= &s[STRLEN-10]) {
             error(ERROR, "Stringified macro arg is too long");
             break;
         }
         if (tp->wslen && (tp->flag&XPWS)==0)
             *sp++ = ' ';
         for (i=0, cp=tp->t; i<tp->len; i++) {
             if (instring && (*cp=='"' || *cp=='\\'))
                 *sp++ = '\\';
             *sp++ = *cp++;
         }
     }
     *sp++ = '"';
     *sp = '\0';
     sp = s;
     t.len = strlen((char*)sp);
     t.t = newstring(sp, t.len, 0);
     return &tr;
 }
References CCON, cp, ERROR, error(), newstring(), sp, STRING, STRLEN, tr, vp, and XPWS.
Referenced by substargs().
substargs()
void substargs (Nlist * , Tokenrow * , Tokenrow **)
Definition at line 320 of file macro.c.
 {
     Tokenrow tatr;
     Token *tp;
     int ntok, argno;
     for (rtr->tp=rtr->bp; rtr->tp<rtr->lp; ) {
         if (rtr->tp->type==SHARP) { /* string operator */
             tp = rtr->tp;
             rtr->tp += 1;
             if ((argno = lookuparg(np, rtr->tp))<0) {
                 error(ERROR, "# not followed by macro parameter");
                 continue;
             }
             ntok = 1 + (rtr->tp - tp);
             rtr->tp = tp;
             insertrow(rtr, ntok, stringify(atr[argno]));
             continue;
         }
         if (rtr->tp->type==NAME
          && (argno = lookuparg(np, rtr->tp)) >= 0) {
             if ((rtr->tp+1)->type==DSHARP
              || (rtr->tp!=rtr->bp && (rtr->tp-1)->type==DSHARP))
                 insertrow(rtr, 1, atr[argno]);
             else {
                 copytokenrow(&tatr, atr[argno]);
                 expandrow(&tatr, "<macro>");
                 insertrow(rtr, 1, &tatr);
                 dofree(tatr.bp);
             }
             continue;
         }
         rtr->tp++;
     }
 }
References copytokenrow(), dofree(), DSHARP, ERROR, error(), expandrow(), insertrow(), lookuparg(), NAME, np, SHARP, and stringify().
Referenced by expand().
trigraph()
int trigraph (Source *)
Definition at line 464 of file lex.c.
 {
     int c;
     while (s->inp+2 >= s->inl && fillbuf(s)!=EOF)
         ;
     if (s->inp[1]!='?')
         return 0;
     c = 0;
     switch(s->inp[2]) {
     case '=':
         c = '#'; break;
     case '(':
         c = '['; break;
     case '/':
         c = '\\'; break;
     case ')':
         c = ']'; break;
     case '\'':
         c = '^'; break;
     case '<':
         c = '{'; break;
     case '!':
         c = '|'; break;
     case '>':
         c = '}'; break;
     case '-':
         c = '~'; break;
     }
     if (c) {
         *s->inp = c;
         memmove(s->inp+1, s->inp+3, s->inl-s->inp+2);
         s->inl -= 2;
     }
     return c;
 }
References EOF, fillbuf(), and memmove().
Referenced by gettokens().
unionhideset()
int unionhideset (int , int)
Definition at line 85 of file hideset.c.
 {
     Hideset hp;
     for (hp = hidesets[hs2]; *hp; hp++)
         hs1 = newhideset(hs1, *hp);
     return hs1;
 }
References hidesets, and newhideset().
Referenced by expand().
unsetsource()
void unsetsource (void)
Definition at line 570 of file lex.c.
 {
     Source *s = cursource;
     if (s->fd>=0) {
         close(s->fd);
         dofree(s->inb);
     }
     cursource = s->next;
     dofree(s);
 }
References cursource, and dofree().
Referenced by doconcat(), expandrow(), process(), and setup().
Variable Documentation
Cplusplus
int Cplusplus
Definition at line 13 of file unix.c.
Referenced by fixlex().
cursource
Source* cursource
Definition at line 13 of file cpp.c.
Referenced by builtin(), control(), error(), genline(), gettokens(), process(), puttokens(), setsource(), and unsetsource().
curtime
char* curtime
Definition at line 112 of file sys_unix.c.
Referenced by builtin(), main(), and Sys_Milliseconds().
ifdepth
int ifdepth
Definition at line 18 of file cpp.c.
Referenced by control(), and process().
ifsatisfied
int ifsatisfied[NIF]
Definition at line 19 of file cpp.c.
Referenced by control().
incdepth
int incdepth
Definition at line 17 of file cpp.c.
Referenced by doinclude(), and process().
includelist
Includelist includelist[NINCLUDE]
Definition at line 6 of file include.c.
kwdefined
Nlist* kwdefined
Definition at line 10 of file nlist.c.
Referenced by eval(), and setup_kwtab().
Mflag
int Mflag
Definition at line 11 of file unix.c.
Referenced by doinclude(), and setup().
namebit
unsigned long namebit[077+1]
Definition at line 45 of file nlist.c.
nltoken
Token nltoken
Definition at line 15 of file cpp.c.
Referenced by setempty().
outp
char* outp
Definition at line 12 of file cpp.c.
Referenced by builtin(), genline(), process(), S_AdpcmDecode(), and S_AdpcmEncode().
skipping
int skipping
Definition at line 20 of file cpp.c.
Referenced by control(), and process().
verbose
int verbose
Definition at line 159 of file cmdlib.c.
wd
char wd[]
Definition at line 11 of file nlist.c.
Referenced by genline().