ZEQ2-Lite: Source/Engine/tools/lcc/src/alloc.c File Reference
alloc.c File Reference
#include "c.h"
Data Structures
union align
struct block
union header
Functions
void * allocate (unsigned long n, unsigned a)
void deallocate (unsigned a)
void * newarray (unsigned long m, unsigned long n, unsigned a)
Variables
static struct block * arena [] = { &first[0], &first[1], &first[2] }
static struct block first [] = { { NULL }, { NULL }, { NULL } }
static struct block * freeblocks
Function Documentation
allocate()
void* allocate (unsigned long n, unsigned a)
Definition at line 53 of file alloc.c.
{
     struct block *ap;
     assert(a < NELEMS(arena));
     assert(n > 0);
     ap = arena[a];
     n = roundup(n, sizeof (union align));
     while (n > ap->limit - ap->avail) {
         if ((ap->next = freeblocks) != NULL) {
             freeblocks = freeblocks->next;
             ap = ap->next;
         } else
             {
                 unsigned m = sizeof (union header) + n + roundup(10*1024, sizeof (union align));
                 ap->next = malloc(m);
                 ap = ap->next;
                 if (ap == NULL) {
                     error("insufficient memory\n");
                     exit(1);
                 }
                 ap->limit = (char *)ap + m;
             }
         ap->avail = (char *)((union header *)ap + 1);
         ap->next = NULL;
         arena[a] = ap;
     }
     ap->avail += n;
     return ap->avail - n;
 }
References arena, block::avail, error(), freeblocks, block::limit, m, NELEMS, block::next, NULL, and roundup.
Referenced by appendstr(), newarray(), primary(), prof_init(), and stringn().
deallocate()
void deallocate (unsigned a)
Definition at line 87 of file alloc.c.
{
     assert(a < NELEMS(arena));
     arena[a]->next = freeblocks;
     freeblocks = first[a].next;
     first[a].next = NULL;
     arena[a] = &first[a];
 }
References arena, freeblocks, NELEMS, block::next, and NULL.
Referenced by initializer(), main(), program(), statement(), and walk().
newarray()
void* newarray (unsigned long m, unsigned long n, unsigned a)
Definition at line 84 of file alloc.c.
{
     return allocate(m*n, a);
 }
References allocate(), and m.
Referenced by apoint(), caselabel(), funcdefn(), ltov(), parameters(), swgen(), and swstmt().
Variable Documentation
arena
struct block * arena[] = { &first[0], &first[1], &first[2] } static
Definition at line 50 of file alloc.c.
Referenced by allocate(), deallocate(), install(), and ltov().
first
struct block first[] = { { NULL }, { NULL }, { NULL } } static
Definition at line 49 of file alloc.c.
freeblocks
struct block* freeblocks static
Definition at line 51 of file alloc.c.
Referenced by allocate(), and deallocate().