ZEQ2-Lite: SpeexStereoState: Handling Speex stereo files
SpeexStereoState: Handling Speex stereo files
This describes the Speex intensity stereo encoding/decoding.
Data Structures
struct SpeexStereoState
If you access any of these fields directly, I'll personally come and bite you.
Macros
#define SPEEX_STEREO_STATE_INIT {1,.5,1,1,0,0}
Deprecated.
Functions
void speex_decode_stereo (float *data, int frame_size, SpeexStereoState *stereo)
Transforms a mono frame into a stereo frame using intensity stereo info.
void speex_decode_stereo_int (spx_int16_t *data, int frame_size, SpeexStereoState *stereo)
Transforms a mono frame into a stereo frame using intensity stereo info.
void speex_encode_stereo (float *data, int frame_size, SpeexBits *bits)
Transforms a stereo frame into a mono frame and stores intensity stereo info in 'bits'.
void speex_encode_stereo_int (spx_int16_t *data, int frame_size, SpeexBits *bits)
Transforms a stereo frame into a mono frame and stores intensity stereo info in 'bits'.
int speex_std_stereo_request_handler (SpeexBits *bits, void *state, void *data)
Callback handler for intensity stereo info.
void speex_stereo_state_destroy (SpeexStereoState *stereo)
Destroy a stereo stereo state.
SpeexStereoState * speex_stereo_state_init (void)
Initialise/create a stereo stereo state.
void speex_stereo_state_reset (SpeexStereoState *stereo)
Reset/re-initialise an already allocated stereo state.
Detailed Description
This describes the Speex intensity stereo encoding/decoding.
Macro Definition Documentation
SPEEX_STEREO_STATE_INIT
#define SPEEX_STEREO_STATE_INIT {1,.5,1,1,0,0}
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Deprecated.
Use speex_stereo_state_init() instead.
Definition at line 60 of file speex_stereo.h.
Function Documentation
speex_decode_stereo()
void speex_decode_stereo (float * data, int frame_size, SpeexStereoState * stereo)
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Transforms a mono frame into a stereo frame using intensity stereo info.
Definition at line 221 of file stereo.c.
 {
    int i;
    spx_word32_t balance;
    spx_word16_t e_left, e_right, e_ratio;
    RealSpeexStereoState *stereo = (RealSpeexStereoState*)_stereo;
    COMPATIBILITY_HACK(stereo);
    balance=stereo->balance;
    e_ratio=stereo->e_ratio;
    /* These two are Q14, with max value just below 2. */
    e_right = DIV32(QCONST32(1., 22), spx_sqrt(MULT16_32_Q15(e_ratio, ADD32(QCONST32(1., 16), balance))));
    e_left = SHR32(MULT16_16(spx_sqrt(balance), e_right), 8);
    for (i=frame_size-1;i>=0;i--)
    {
       spx_word16_t tmp=data[i];
       stereo->smooth_left = EXTRACT16(PSHR32(MAC16_16(MULT16_16(stereo->smooth_left, QCONST16(0.98, 15)), e_left, QCONST16(0.02, 15)), 15));
       stereo->smooth_right = EXTRACT16(PSHR32(MAC16_16(MULT16_16(stereo->smooth_right, QCONST16(0.98, 15)), e_right, QCONST16(0.02, 15)), 15));
       data[2*i] = (float)MULT16_16_P14(stereo->smooth_left, tmp);
       data[2*i+1] = (float)MULT16_16_P14(stereo->smooth_right, tmp);
    }
 }
References ADD32, RealSpeexStereoState::balance, COMPATIBILITY_HACK, DIV32, RealSpeexStereoState::e_ratio, EXTRACT16, MAC16_16, MULT16_16, MULT16_16_P14, MULT16_32_Q15, PSHR32, QCONST16, QCONST32, SHR32, RealSpeexStereoState::smooth_left, RealSpeexStereoState::smooth_right, and spx_sqrt.
speex_decode_stereo_int()
void speex_decode_stereo_int (spx_int16_t * data, int frame_size, SpeexStereoState * stereo)
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Transforms a mono frame into a stereo frame using intensity stereo info.
Definition at line 248 of file stereo.c.
 {
    int i;
    spx_word32_t balance;
    spx_word16_t e_left, e_right, e_ratio;
    RealSpeexStereoState *stereo = (RealSpeexStereoState*)_stereo;
    COMPATIBILITY_HACK(stereo);
    balance=stereo->balance;
    e_ratio=stereo->e_ratio;
    /* These two are Q14, with max value just below 2. */
    e_right = DIV32(QCONST32(1., 22), spx_sqrt(MULT16_32_Q15(e_ratio, ADD32(QCONST32(1., 16), balance))));
    e_left = SHR32(MULT16_16(spx_sqrt(balance), e_right), 8);
    for (i=frame_size-1;i>=0;i--)
    {
       spx_int16_t tmp=data[i];
       stereo->smooth_left = EXTRACT16(PSHR32(MAC16_16(MULT16_16(stereo->smooth_left, QCONST16(0.98, 15)), e_left, QCONST16(0.02, 15)), 15));
       stereo->smooth_right = EXTRACT16(PSHR32(MAC16_16(MULT16_16(stereo->smooth_right, QCONST16(0.98, 15)), e_right, QCONST16(0.02, 15)), 15));
       data[2*i] = (spx_int16_t)MULT16_16_P14(stereo->smooth_left, tmp);
       data[2*i+1] = (spx_int16_t)MULT16_16_P14(stereo->smooth_right, tmp);
    }
 }
References ADD32, RealSpeexStereoState::balance, COMPATIBILITY_HACK, DIV32, RealSpeexStereoState::e_ratio, EXTRACT16, MAC16_16, MULT16_16, MULT16_16_P14, MULT16_32_Q15, PSHR32, QCONST16, QCONST32, SHR32, RealSpeexStereoState::smooth_left, RealSpeexStereoState::smooth_right, and spx_sqrt.
speex_encode_stereo()
void speex_encode_stereo (float * data, int frame_size, SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Transforms a stereo frame into a mono frame and stores intensity stereo info in 'bits'.
Definition at line 108 of file stereo.c.
 {
    int i, tmp;
    float e_left=0, e_right=0, e_tot=0;
    float balance, e_ratio;
    for (i=0;i<frame_size;i++)
    {
       e_left  += ((float)data[2*i])*data[2*i];
       e_right += ((float)data[2*i+1])*data[2*i+1];
       data[i] =  .5*(((float)data[2*i])+data[2*i+1]);
       e_tot   += ((float)data[i])*data[i];
    }
    balance=(e_left+1)/(e_right+1);
    e_ratio = e_tot/(1+e_left+e_right);
    /*Quantization*/
    speex_bits_pack(bits, 14, 5);
    speex_bits_pack(bits, SPEEX_INBAND_STEREO, 4);
    balance=4*log(balance);
    /*Pack sign*/
    if (balance>0)
       speex_bits_pack(bits, 0, 1);
    else
       speex_bits_pack(bits, 1, 1);
    balance=floor(.5+fabs(balance));
    if (balance>30)
       balance=31;
    speex_bits_pack(bits, (int)balance, 5);
    /* FIXME: this is a hack */
    tmp=scal_quant(e_ratio*Q15_ONE, e_ratio_quant_bounds, 4);
    speex_bits_pack(bits, tmp, 2);
 }
References bits(), e_ratio_quant_bounds, Q15_ONE, scal_quant(), speex_bits_pack(), and SPEEX_INBAND_STEREO.
speex_encode_stereo_int()
void speex_encode_stereo_int (spx_int16_t * data, int frame_size, SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Transforms a stereo frame into a mono frame and stores intensity stereo info in 'bits'.
Definition at line 146 of file stereo.c.
 {
    int i, tmp;
    spx_word32_t e_left=0, e_right=0, e_tot=0;
    spx_word32_t balance, e_ratio;
    spx_word32_t largest, smallest;
    int balance_id;
 #ifdef FIXED_POINT
    int shift;
 #endif
    /* In band marker */
    speex_bits_pack(bits, 14, 5);
    /* Stereo marker */
    speex_bits_pack(bits, SPEEX_INBAND_STEREO, 4);
    for (i=0;i<frame_size;i++)
    {
       e_left  += SHR32(MULT16_16(data[2*i],data[2*i]),8);
       e_right += SHR32(MULT16_16(data[2*i+1],data[2*i+1]),8);
 #ifdef FIXED_POINT
       /* I think this is actually unbiased */
       data[i] =  SHR16(data[2*i],1)+PSHR16(data[2*i+1],1);
 #else
       data[i] =  .5*(((float)data[2*i])+data[2*i+1]);
 #endif
       e_tot   += SHR32(MULT16_16(data[i],data[i]),8);
    }
    if (e_left > e_right)
    {
       speex_bits_pack(bits, 0, 1);
       largest = e_left;
       smallest = e_right;
    } else {
       speex_bits_pack(bits, 1, 1);
       largest = e_right;
       smallest = e_left;
    }
    /* Balance quantization */
 #ifdef FIXED_POINT
    shift = spx_ilog2(largest)-15;
    largest = VSHR32(largest, shift-4);
    smallest = VSHR32(smallest, shift);
    balance = DIV32(largest, ADD32(smallest, 1));
    if (balance > 32767)
       balance = 32767;
    balance_id = scal_quant(EXTRACT16(balance), balance_bounds, 32);
 #else
    balance=(largest+1.)/(smallest+1.);
    balance=4*log(balance);
    balance_id=floor(.5+fabs(balance));
    if (balance_id>30)
       balance_id=31;
 #endif
    speex_bits_pack(bits, balance_id, 5);
    /* "coherence" quantisation */
 #ifdef FIXED_POINT
    shift = spx_ilog2(e_tot);
    e_tot = VSHR32(e_tot, shift-25);
    e_left = VSHR32(e_left, shift-10);
    e_right = VSHR32(e_right, shift-10);
    e_ratio = DIV32(e_tot, e_left+e_right+1);
 #else
    e_ratio = e_tot/(1.+e_left+e_right);
 #endif
    tmp=scal_quant(EXTRACT16(e_ratio), e_ratio_quant_bounds, 4);
    /*fprintf (stderr, "%d %d %d %d\n", largest, smallest, balance_id, e_ratio);*/
    speex_bits_pack(bits, tmp, 2);
 }
References ADD32, bits(), DIV32, e_ratio_quant_bounds, EXTRACT16, MULT16_16, PSHR16, scal_quant(), SHR16, SHR32, speex_bits_pack(), SPEEX_INBAND_STEREO, spx_ilog2(), and VSHR32.
speex_std_stereo_request_handler()
int speex_std_stereo_request_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Callback handler for intensity stereo info.
Definition at line 274 of file stereo.c.
 {
    RealSpeexStereoState *stereo;
    spx_word16_t sign=1, dexp;
    int tmp;
    stereo = (RealSpeexStereoState*)data;
    COMPATIBILITY_HACK(stereo);
    if (speex_bits_unpack_unsigned(bits, 1))
       sign=-1;
    dexp = speex_bits_unpack_unsigned(bits, 5);
 #ifndef FIXED_POINT
    stereo->balance = exp(sign*.25*dexp);
 #else
    stereo->balance = spx_exp(MULT16_16(sign, SHL16(dexp, 9)));
 #endif
    tmp = speex_bits_unpack_unsigned(bits, 2);
    stereo->e_ratio = e_ratio_quant[tmp];
    return 0;
 }
References RealSpeexStereoState::balance, bits(), COMPATIBILITY_HACK, RealSpeexStereoState::e_ratio, e_ratio_quant, MULT16_16, SHL16, speex_bits_unpack_unsigned(), and spx_exp.
speex_stereo_state_destroy()
void speex_stereo_state_destroy (SpeexStereoState * stereo)
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Destroy a stereo stereo state.
Definition at line 102 of file stereo.c.
 {
    speex_free(stereo);
 }
References speex_free().
speex_stereo_state_init()
SpeexStereoState* speex_stereo_state_init (void)
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Initialise/create a stereo stereo state.
Definition at line 75 of file stereo.c.
 {
    SpeexStereoState *stereo = speex_alloc(sizeof(SpeexStereoState));
    speex_stereo_state_reset(stereo);
    return stereo;
 }
References speex_alloc(), and speex_stereo_state_reset().
speex_stereo_state_reset()
void speex_stereo_state_reset (SpeexStereoState * stereo)
#include <Source/Engine/libspeex/include/speex/speex_stereo.h>
Reset/re-initialise an already allocated stereo state.
Definition at line 82 of file stereo.c.
 {
    RealSpeexStereoState *stereo = (RealSpeexStereoState*)_stereo;
 #ifdef FIXED_POINT
    stereo->balance = 65536;
    stereo->e_ratio = 16384;
    stereo->smooth_left = 16384;
    stereo->smooth_right = 16384;
    stereo->reserved1 = 0xdeadbeef;
    stereo->reserved2 = 0;
 #else
    stereo->balance = 1.0f;
    stereo->e_ratio = .5f;
    stereo->smooth_left = 1.f;
    stereo->smooth_right = 1.f;
    stereo->reserved1 = 0;
    stereo->reserved2 = 0;
 #endif
 }
References RealSpeexStereoState::balance, RealSpeexStereoState::e_ratio, RealSpeexStereoState::reserved1, RealSpeexStereoState::reserved2, RealSpeexStereoState::smooth_left, and RealSpeexStereoState::smooth_right.
Referenced by speex_stereo_state_init().