ZEQ2-Lite: Source/Engine/tools/lcc/etc/bytecode.c File Reference
bytecode.c File Reference
#include <string.h>
#include <stdio.h>
#include "../../../../Shared/q_platform.h"
Macros
#define BINEXT ""
Functions
char * concat (char *, char *)
int option (char *arg)
void UpdatePaths (const char *lccBinary)
Variables
char * as [] = { 0 }
char * com [] = { "q3rcc" BINEXT, "-target=bytecode", "$1", "$2", "$3", 0 }
char * cpp []
char * include [] = { 0 }
char inputs [256] = ""
char * ld [] = { 0 }
char * suffixes [] = { ".c", ".i", ".asm", ".o", ".out", 0 }
Macro Definition Documentation
BINEXT
#define BINEXT ""
Definition at line 10 of file bytecode.c.
Function Documentation
concat()
char * concat (char * s1, char * s2)
Definition at line 365 of file lcc.c.
{
     int n = strlen(s1);
     char *s = alloc(n + strlen(s2) + 1);
     strcpy(s, s1);
     strcpy(s + n, s2);
     return s;
 }
References alloc().
Referenced by filename(), initinputs(), main(), opt(), option(), and UpdatePaths().
option()
int option (char * arg)
Definition at line 50 of file bytecode.c.
                       {
     if (strncmp(arg, "-lccdir=", 8) == 0) {
         cpp[0] = concat(&arg[8], "/q3cpp" BINEXT);
         include[0] = concat("-I", concat(&arg[8], "/include"));
         com[0] = concat(&arg[8], "/q3rcc" BINEXT);
     } else if (strcmp(arg, "-p") == 0 || strcmp(arg, "-pg") == 0) {
         fprintf( stderr, "no profiling supported, %s ignored.\n", arg);
     } else if (strcmp(arg, "-b") == 0)
         ;
     else if (strcmp(arg, "-g") == 0)
         fprintf( stderr, "no debugging supported, %s ignored.\n", arg);
     else if (strncmp(arg, "-ld=", 4) == 0 || strcmp(arg, "-static") == 0) {
         fprintf( stderr, "no linking supported, %s ignored.\n", arg);
     } else
         return 0;
     return 1;
 }
References BINEXT, com, concat(), cpp, and include.
Referenced by main(), opt(), and PM_Melee().
UpdatePaths()
void UpdatePaths (const char * lccBinary)
Definition at line 33 of file bytecode.c.
 {
     char basepath[ 1024 ];
     char *p;
     strncpy( basepath, lccBinary, 1024 );
     p = strrchr( basepath, PATH_SEP );
     if( p )
     {
         *( p + 1 ) = '\0';
         cpp[ 0 ] = concat( basepath, "q3cpp" BINEXT );
         com[ 0 ] = concat( basepath, "q3rcc" BINEXT );
     }
 }
References basepath(), BINEXT, com, concat(), and cpp.
Referenced by main().
Variable Documentation
as
char* as[] = { 0 }
Definition at line 21 of file bytecode.c.
com
char* com[] = { "q3rcc" BINEXT, "-target=bytecode", "$1", "$2", "$3", 0 }
Definition at line 19 of file bytecode.c.
Referenced by option(), and UpdatePaths().
cpp
char* cpp[]
Initial value:
= { "q3cpp" BINEXT,
    "-D__STDC__=1", "-D__STRICT_ANSI__", "-D__signed__=signed", "-DQ3_VM",
    "$1", "$2", "$3", 0 }
Definition at line 15 of file bytecode.c.
Referenced by filename(), opt(), option(), stabend(), and UpdatePaths().
include
char* include[] = { 0 }
Definition at line 18 of file bytecode.c.
Referenced by option().
inputs
char inputs[256] = ""
Definition at line 14 of file bytecode.c.
ld
char* ld[] = { 0 }
Definition at line 20 of file bytecode.c.
Referenced by drfti1().
suffixes
char* suffixes[] = { ".c", ".i", ".asm", ".o", ".out", 0 }
Definition at line 13 of file bytecode.c.
Referenced by opname().