ZEQ2-Lite: Tools/zMesh Exporter/zskeleton.h File Reference
zskeleton.h File Reference
#include "scriplib.h"
#include "md4file.h"
#include "config.h"
Data Structures
struct progMeshTri_t
struct progMeshVert_t
struct smdBoneFrame_t
struct smdBoneName_t
struct smdFrame_t
struct smdModel_t
struct smdSurface_t
struct smdTriangle_t
struct smdVertex_t
struct smdWeight_t
Macros
#define CFG_VERSION 3
#define MAX_BONES 128
#define MAX_FRAMES 2048
#define MAX_SURFS 32
#define MAX_TRIS 8192
#define MAX_VERTS 4096
#define MAX_WEIGHTS 16
#define SMD2MD4_VERSION 10
#define SMD_VERSION 1
#define ZSKELETON_VERSION 1
Functions
void DoAnims (void)
void DoMeshes (void)
void FixCoords (void)
void LoadSMD (smdModel_t *smd, char modelName[32], char fileName[32])
void LoadSMD_ParseNodes (smdModel_t *smd)
void LoadSMD_ParseSkeleton (smdModel_t *smd)
void LoadSMD_ParseTriangles (smdModel_t *smd)
void OrderMesh (int input[][3], int output[][3], int numTris)
void PrintUsage (void)
void ProgressiveMesh (smdSurface_t *surf)
void SaveAnimation (smdModel_t *smd, char fileName[32])
void SaveMD4 (void)
void SaveMesh (smdModel_t *smd, char fileName[32])
Variables
qboolean debug
char indicator []
int progress
qboolean verbose
Macro Definition Documentation
CFG_VERSION
#define CFG_VERSION 3
Definition at line 20 of file zskeleton.h.
MAX_BONES
#define MAX_BONES 128
Definition at line 22 of file zskeleton.h.
MAX_FRAMES
#define MAX_FRAMES 2048
Definition at line 23 of file zskeleton.h.
MAX_SURFS
#define MAX_SURFS 32
Definition at line 27 of file zskeleton.h.
MAX_TRIS
#define MAX_TRIS 8192
Definition at line 26 of file zskeleton.h.
MAX_VERTS
#define MAX_VERTS 4096
Definition at line 24 of file zskeleton.h.
MAX_WEIGHTS
#define MAX_WEIGHTS 16
Definition at line 25 of file zskeleton.h.
SMD2MD4_VERSION
#define SMD2MD4_VERSION 10
Definition at line 18 of file zskeleton.h.
SMD_VERSION
#define SMD_VERSION 1
Definition at line 19 of file zskeleton.h.
ZSKELETON_VERSION
#define ZSKELETON_VERSION 1
Definition at line 17 of file zskeleton.h.
Function Documentation
DoAnims()
void DoAnims (void)
Definition at line 74 of file zskeleton.c.
 {
     int i;
     if(config.verbose) printf(" Compiling %i Animations...\n", config.numAnims);
     for(i = 0; i < config.numAnims; i++)
     {
         char dstFileName[512];
         strcpy(dstFileName,config.anims[i].output);
         StripExtension(dstFileName);
         DefaultExtension(dstFileName,config.animExtension);
         if(!config.forceCompile && FileExists(dstFileName))
         {
             printf("  Can not compile animation \"%s\", file %s already exists.\nUse the \"Overwrite\" config attribute to force an overwrite.\n",config.anims[i].name,dstFileName);
             continue;
         }
         if(config.verbose) printf("   Loading \"%s.smd\"\n",config.anims[i].input);
         LoadSMD(&config.anims[i].smd,config.anims[i].name,config.anims[i].input);
         if(config.debug) printf("   SMD Loaded \"%s.smd\" with %i frames, %i bones and %i surfs\n",config.anims[i].input,config.anims[i].smd.numFrames,config.anims[i].smd.numBones,config.anims[i].smd.numSurfs);
         FixCoords(&config.anims[i].smd);
         if(config.debug) printf("   SMD \"%s.smd\" Processed with %i frames, %i bones and %i surfs\n",config.anims[i].input,config.anims[i].smd.numFrames,config.anims[i].smd.numBones,config.anims[i].smd.numSurfs);
         SaveAnimation(&config.anims[i].smd,config.anims[i].output);
     }
 }
References zSkel_Config_t::animExtension, zSkel_Config_t::anims, config, zSkel_Config_t::debug, DefaultExtension(), FileExists(), FixCoords(), zSkel_Config_t::forceCompile, zSkel_Config_Anim_t::input, LoadSMD(), zSkel_Config_Anim_t::name, zSkel_Config_t::numAnims, smdModel_t::numBones, smdModel_t::numFrames, smdModel_t::numSurfs, zSkel_Config_Anim_t::output, printf(), SaveAnimation(), zSkel_Config_Anim_t::smd, strcpy(), StripExtension(), and zSkel_Config_t::verbose.
Referenced by main().
DoMeshes()
void DoMeshes (void)
Definition at line 49 of file zskeleton.c.
 {
     int i;
     if(config.verbose) printf(" Compiling %i Meshes...\n", config.numMeshes);
     for(i = 0; i < config.numMeshes; i++)
     {
         char dstFileName[512];
         strcpy(dstFileName,config.meshes[i].output);
         StripExtension(dstFileName);
         DefaultExtension(dstFileName,config.meshExtension);
         if(!config.forceCompile && FileExists(dstFileName))
         {
             printf("  Can not compile mesh \"%s\", file %s already exists.\nUse the \"Overwrite\" config attribute to force an overwrite.\n",config.meshes[i].name,dstFileName);
             continue;
         }
         if(config.verbose) printf("   Loading \"%s.smd\"\n",config.meshes[i].input);
         LoadSMD(&config.meshes[i].smd,config.meshes[i].name,config.meshes[i].input);
         if(config.debug) printf("   SMD Loaded \"%s.smd\" with %i frames, %i bones and %i surfs\n",config.meshes[i].input,config.meshes[i].smd.numFrames,config.meshes[i].smd.numBones,config.meshes[i].smd.numSurfs);
         FixCoords(&config.meshes[i].smd);
         if(config.debug) printf("   SMD \"%s.smd\" Processed with %i frames, %i bones and %i surfs\n",config.meshes[i].input,config.meshes[i].smd.numFrames,config.meshes[i].smd.numBones,config.meshes[i].smd.numSurfs);
         SaveMesh(&config.meshes[i].smd,config.meshes[i].output);
     }
 }
References config, zSkel_Config_t::debug, DefaultExtension(), FileExists(), FixCoords(), zSkel_Config_t::forceCompile, zSkel_Config_Mesh_t::input, LoadSMD(), zSkel_Config_t::meshes, zSkel_Config_t::meshExtension, zSkel_Config_Mesh_t::name, smdModel_t::numBones, smdModel_t::numFrames, zSkel_Config_t::numMeshes, smdModel_t::numSurfs, zSkel_Config_Mesh_t::output, printf(), SaveMesh(), zSkel_Config_Mesh_t::smd, strcpy(), StripExtension(), and zSkel_Config_t::verbose.
Referenced by main().
FixCoords()
void FixCoords (void)
LoadSMD()
void LoadSMD (smdModel_t * smd, char modelName[32], char fileName[32])
Definition at line 113 of file zskeleton.c.
{
     int smdVer,i;
     char smdFileName[512];
     strcpy(smdFileName,fileName);
     // load file and check version
     StripExtension(smdFileName);
     DefaultExtension(smdFileName,".smd");
     LoadScriptFile(smdFileName);
     MatchToken("version");
     ParseInt(&smdVer);
     if(smdVer != SMD_VERSION) {
         Error("LoadSMD: expected version %i, found version %i in %s\n",SMD_VERSION,smdVer,smdFileName);
     }
     // set the model name
     strncpy(smd->name,modelName,sizeof(smd->name));
     // parse through the file
     while(GetToken(qtrue)) {
         // process the next section
         if(!strcmp(token,"nodes")) {
             // bone names and hierarchy
             LoadSMD_ParseNodes(smd);
         } else if(!strcmp(token,"skeleton")) {
             // animation data
             LoadSMD_ParseSkeleton(smd);
         } else if(!strcmp(token,"triangles")) {
             // mesh data (optional)
             LoadSMD_ParseTriangles(smd);
         } else if(!strcmp(token,"end")) {
             break;
         } else {
             if(config.debug) {
                 printf("LoadSMD: unknown section \"%s\" in %s, skipping\n",token,smdFileName);
             }
             break;
         }
     }
     // children inherit parent's bone flags
     for(i = 0; i < smd->numBones; i++) {
         if((smd->bones[i].flags == 0) && (smd->bones[i].parent >= 0) && (smd->bones[smd->bones[i].parent].flags != 0)) {
             smd->bones[i].flags = smd->bones[smd->bones[i].parent].flags;
         }
     }
 }
References smdModel_t::bones, config, zSkel_Config_t::debug, DefaultExtension(), Error, smdBoneName_t::flags, GetToken(), LoadScriptFile(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), LoadSMD_ParseTriangles(), MatchToken(), smdModel_t::name, smdModel_t::numBones, smdBoneName_t::parent, ParseInt(), printf(), qtrue, SMD_VERSION, strcmp(), strcpy(), StripExtension(), and strncpy().
Referenced by DoAnims(), and DoMeshes().
LoadSMD_ParseNodes()
void LoadSMD_ParseNodes (smdModel_t * smd)
Definition at line 173 of file zskeleton.c.
{
     int numBones = 0;
     smdBoneName_t *bones;
     if(config.verbose && !config.debug) {
         printf("   bones\r");
     }
     // allocate space and zero it out
     smd->bones = (smdBoneName_t *)calloc(MAX_BONES, sizeof(smdBoneName_t));
     bones = smd->bones;
     while(1) {
         int boneNum = -1;
         GetToken(qtrue);    // bone number
         if(!strcmp(token,"end")) {
             break;
         }
         if(numBones >= MAX_BONES) {
             Error("LoadSMD_ParseNodes: exceeded maximum of %i bones\n",MAX_BONES);
         }
         boneNum = atoi(token);
         if(boneNum < 0) {
             Error("LoadSMD_ParseNodes: invalid bone index %i\n",boneNum);
         }
         bones[boneNum].id = boneNum;
         GetToken(qfalse);   // bone name
         strncpy(bones[boneNum].name,token,sizeof(bones[boneNum].name));
         ParseInt(&bones[boneNum].parent);   // bone parent
         bones[boneNum].flags = GetFlagForBone(bones[boneNum].name);
         numBones++;
         if(config.debug) {
             printf("   found bone \"%s\"\n",smd->bones[boneNum].name);
         }
     }
     // update the counter and resize array to save heap space
     smd->numBones = numBones;
     smd->bones = (smdBoneName_t *)realloc(smd->bones,sizeof(smdBoneName_t) * smd->numBones);
     if(config.verbose && !config.debug) {
         printf("  \n");
     }
 }
References atoi(), bones, smdModel_t::bones, calloc(), config, zSkel_Config_t::debug, Error, GetFlagForBone(), GetToken(), MAX_BONES, smdBoneName_t::name, smdModel_t::numBones, ParseInt(), printf(), qfalse, qtrue, realloc(), strcmp(), strncpy(), and zSkel_Config_t::verbose.
Referenced by LoadSMD().
LoadSMD_ParseSkeleton()
void LoadSMD_ParseSkeleton (smdModel_t * smd)
Definition at line 223 of file zskeleton.c.
{
     int numFrames = 0;
     if(config.verbose && !config.debug) {
         printf("   frames\r");
     }
     // allocate space and zero it out
     smd->frames = (smdFrame_t *)calloc(MAX_FRAMES,sizeof(smdFrame_t) + (sizeof(smdBoneFrame_t) * smd->numBones));
     while(1) {
         int i,frameNum = -1;
         smdBoneFrame_t *bones;
         smdFrame_t *frame;
         GetToken(qtrue);    // "time"
         if(!strcmp(token,"end")) {
             break;
         }
         if(numFrames >= MAX_FRAMES) {
             Error("LoadSMD_ParseSkeleton: exceeded maximum of %i frames\n",MAX_FRAMES);
         }
         ParseInt(&frameNum);    // frame number
         if(frameNum < 0) {
             Error("LoadSMD_ParseSkeleton: invalid frame index %i\n",frameNum);
         }
         // make sure space for the bones is properly allocated
         frame = &smd->frames[frameNum];
         frame->bones = (smdBoneFrame_t *)realloc(frame->bones,sizeof(smdBoneFrame_t) * smd->numBones);
         bones = frame->bones;
         // clear bounding box for frame
         ClearBounds(frame->bounds[0],frame->bounds[1]);
         for(i = 0; i < smd->numBones; i++) {
             int boneNum,parent;
             float rotation[3];
             smdBoneFrame_t temp;
             GetToken(qtrue);    // bone number
             if(!strcmp(token,"time")) {
                 // FIXME: smd spec allows lerping of bones between unkeyed frames
                 Error("LoadSMD_ParseSkeleton: missing bone keys in frame %i\n",frameNum);
             }
             boneNum = atoi(token);
             if(boneNum < 0) {
                 Error("LoadSMD_ParseSkeleton: frame %i has reference to invalid bone index %i\n",frameNum,boneNum);
             }
             Parse1DMatrix(3,temp.origin);   // bone position
             Parse1DMatrix(3,rotation);      // bone rotation
             // calculate bone matrix
             parent = smd->bones[boneNum].parent;
             AnglesToMatrix(rotation,temp.matrix);
             if(parent >= 0) {
                 // FIXME: assumes bones listed in order, smd spec allows bones to be in any order
                 MatrixMultiply(bones[parent].matrix,temp.matrix,bones[boneNum].matrix);
                 VectorRotate(temp.origin,bones[parent].matrix,bones[boneNum].origin);
                 VectorAdd(bones[parent].origin,bones[boneNum].origin,bones[boneNum].origin);
             } else {
                 // this is a root bone, copy as-is, child of world
                 VectorCopy(temp.origin,bones[boneNum].origin);
                 VectorCopy(temp.matrix[0],bones[boneNum].matrix[0]);
                 VectorCopy(temp.matrix[1],bones[boneNum].matrix[1]);
                 VectorCopy(temp.matrix[2],bones[boneNum].matrix[2]);
             }
         }
         numFrames++;
     }
     // update the counter and resize array to save heap space
     smd->numFrames = numFrames;
     smd->frames = (smdFrame_t *)realloc(smd->frames,(sizeof(smdFrame_t) + (sizeof(smdBoneFrame_t) * smd->numBones)) * smd->numFrames);
     if(config.verbose && !config.debug) {
         printf("  \n");
     }
 }
References AnglesToMatrix(), atoi(), bones, smdModel_t::bones, mdxFrame_t::bounds, calloc(), ClearBounds(), config, zSkel_Config_t::debug, Error, frame, smdModel_t::frames, GetToken(), smdBoneFrame_t::matrix, mdxBoneFrame_t::matrix, MatrixMultiply(), MAX_FRAMES, smdModel_t::numBones, smdModel_t::numFrames, smdBoneFrame_t::origin, smdBoneName_t::parent, Parse1DMatrix(), ParseInt(), printf(), qtrue, realloc(), strcmp(), VectorAdd, VectorCopy, VectorRotate(), and zSkel_Config_t::verbose.
Referenced by LoadSMD().
LoadSMD_ParseTriangles()
void LoadSMD_ParseTriangles (smdModel_t * smd)
Definition at line 308 of file zskeleton.c.
{
     int i,j,k,numSurfs = 0;
     smdSurface_t *surfs;
     smdBoneFrame_t *bones;
     if(config.verbose && !config.debug) {
         printf("   meshes\r");
     }
     // allocate space and zero it out
     smd->surfs = (smdSurface_t *)calloc(1,sizeof(smdSurface_t) + (sizeof(smdTriangle_t) * MAX_TRIS) + (sizeof(smdVertex_t) * MAX_VERTS) + (sizeof(int) * MAX_VERTS));
     // reduce typing, my hands hurt...
     surfs = smd->surfs;
     bones = smd->frames[0].bones;
     while(1) {
         int found = -1;
         int curSurf = -1,vertIndex = -1;
         smdVertex_t *verts;
         smdTriangle_t *tris;
         smdVertex_t temp;
         GetToken(qtrue);    // surface name
         if(!strcmp(token,"end")) {
             break;
         }
         // look for surf name to see if it exists
         for(i = 0; i < numSurfs; i++) {
             if(!strcmp(token,surfs[i].name)) {
                 found = i;
                 break;
             }
         }
         // add surf if it wasn't found
         if(found < 0) {
             if(numSurfs >= MAX_SURFS) {
                 Error("LoadSMD_ParseTriangles: exceeded maximum of %i surfaces\n",MAX_SURFS);
             }
             curSurf = numSurfs;
             // expand surf data as we go
             smd->surfs = (smdSurface_t *)realloc(smd->surfs,(sizeof(smdSurface_t) + (sizeof(smdTriangle_t) * MAX_TRIS) + (sizeof(smdVertex_t) * MAX_VERTS) + (sizeof(int) * MAX_VERTS)) * (numSurfs + 1));
             surfs = smd->surfs;
             strncpy(surfs[curSurf].name,token,sizeof(surfs[curSurf].name));
             surfs[curSurf].id = ++numSurfs;
             surfs[curSurf].numTris = 0;
             surfs[curSurf].numVerts = 0;
             surfs[curSurf].minLod = 0;
             surfs[curSurf].tris = (smdTriangle_t *)realloc(surfs[curSurf].tris,sizeof(smdTriangle_t) * MAX_TRIS);
             surfs[curSurf].verts = (smdVertex_t *)realloc(surfs[curSurf].verts,sizeof(smdVertex_t) * MAX_VERTS);
             surfs[curSurf].map = (int *)realloc(surfs[curSurf].map,sizeof(int) * MAX_VERTS);
         } else {
             curSurf = found;
             if(surfs[curSurf].numTris >= MAX_TRIS) {
                 Error("LoadSMD_ParseTriangles: exceeded maximum of %i triangles per surface\n",MAX_TRIS);
             }
         }
         tris = surfs[curSurf].tris;
         verts = surfs[curSurf].verts;
         // parse tri with vert indexes
         for(i = 0; i < 3; i++) {
             GetToken(qtrue);    // reference bone
             temp.parent = atoi(token);
             if(temp.parent < 0) {
                 Error("LoadSMD_ParseTriangles: invalid reference bone %i for vertex\n",temp.parent);
             }
             Parse1DMatrix(3,temp.origin);       // vertex position
             Parse1DMatrix(3,temp.normal);       // vertex normal
             Parse1DMatrix(2,temp.texCoords);    // vertex texture coords
             // half-life 2 smd explicitly lists each influence per vertex
             if(GetToken(qfalse)) {
                 temp.numWeights = atoi(token);  // number of influences
                 if(temp.numWeights < 1) {
                     Error("LoadSMD_ParseTriangles: invalid number of influences (%i) for vertex\n",temp.numWeights);
                 } else if(temp.numWeights > MAX_WEIGHTS) {
                     Error("LoadSMD_ParseTriangles: exceeded maximum of %i influences per vertex\n",MAX_WEIGHTS);
                 }
                 for(j = 0; j < temp.numWeights; j++) {
                     ParseInt(&temp.weights[j].bone);    // bone index
                     if(temp.weights[j].bone < 0) {
                         Error("LoadSMD_ParseTriangles: invalid bone index %i for influence %i on vertex\n",temp.weights[j].bone,j);
                     }
                     Parse1DMatrix(1,&temp.weights[j].weight);   // influence weight
                     if(temp.weights[j].weight < 0) {
                         Error("LoadSMD_ParseTriangles: invalid weight %f for influence %i on vertex\n",temp.weights[j].weight,j);
                     }
                 }
             } else {
                 // half-life 1 smd implies only 1 influence (the reference bone)
                 temp.numWeights = 1;
                 temp.weights[0].bone = temp.parent;
                 temp.weights[0].weight = 1.0f;
             }
             // check for redundant vertices
             found = -1;
             for(j = 0; j < surfs[curSurf].numVerts; j++) {
                 if( (temp.parent != verts[j].parent) ||
                     (temp.numWeights != verts[j].numWeights) ||
                     !VectorCompare(temp.origin,verts[j].origin) ||
                     !VectorCompare(temp.normal,verts[j].normal) ||
                     (fabs(temp.texCoords[0] - verts[j].texCoords[0]) > 0.0001) ||
                     (fabs(temp.texCoords[1] - verts[j].texCoords[1]) > 0.0001) ) {
                         continue;
                 }
                 for(k = 0; k < temp.numWeights; k++) {
                     if( (temp.weights[k].bone != verts[j].weights[k].bone) ||
                         (fabs(temp.weights[k].weight - verts[j].weights[k].weight) > 0.0001) ) {
                         found = 0;
                         break;
                     } else {
                         found = 1;
                     }
                 }
                 if(!found) {
                     found = -1;
                     continue;
                 } else {
                     found = j;
                     break;
                 }
             }
             // add vertex if it wasn't found
             if(found < 0) {
                 if(surfs[curSurf].numVerts >= MAX_VERTS) {
                     Error("LoadSMD_ParseTriangles: exceeded maximum of %i vertices per surface\n",MAX_VERTS);
                 }
                 vertIndex = surfs[curSurf].numVerts;
                 VectorCopy(temp.origin,verts[vertIndex].origin);
                 VectorCopy(temp.normal,verts[vertIndex].normal);
                 verts[vertIndex].texCoords[0] = temp.texCoords[0];
                 verts[vertIndex].texCoords[1] = temp.texCoords[1];
                 verts[vertIndex].parent = temp.parent;
                 verts[vertIndex].numWeights = temp.numWeights;
                 // calculate influence offsets
                 for(j = 0; j < verts[vertIndex].numWeights; j++) {
                     int boneNum;
                     float tempOrg[3];
                     verts[vertIndex].weights[j].bone = temp.weights[j].bone;
                     verts[vertIndex].weights[j].weight = temp.weights[j].weight;
                     boneNum = verts[vertIndex].weights[j].bone;
                     VectorSubtract(verts[vertIndex].origin,bones[boneNum].origin,tempOrg);
                     VectorInverseRotate(tempOrg,bones[boneNum].matrix,verts[vertIndex].weights[j].offset);
                 }
                 surfs[curSurf].map[vertIndex] = vertIndex;
                 surfs[curSurf].numVerts++;
                 surfs[curSurf].minLod = surfs[curSurf].numVerts;
             } else {
                 vertIndex = found;
             }
             // update vertex index
             tris[surfs[curSurf].numTris].verts[i] = vertIndex;
         }
         // add triangle and update counter
         tris[surfs[curSurf].numTris].surf = surfs[curSurf].id;
         smd->surfs[curSurf].numTris++;
     }
     // update counter
     smd->numSurfs = numSurfs;
     if(verbose && !debug) {
         printf("  \n");
     }
 }
References atoi(), smdWeight_t::bone, bones, smdFrame_t::bones, calloc(), config, debug, zSkel_Config_t::debug, Error, fabs(), smdModel_t::frames, GetToken(), smdSurface_t::id, int, smdSurface_t::map, MAX_SURFS, MAX_TRIS, MAX_VERTS, MAX_WEIGHTS, smdSurface_t::minLod, smdVertex_t::normal, smdModel_t::numSurfs, smdSurface_t::numTris, numVerts, smdSurface_t::numVerts, smdVertex_t::numWeights, smdVertex_t::origin, smdVertex_t::parent, Parse1DMatrix(), ParseInt(), printf(), qfalse, qtrue, realloc(), strcmp(), strncpy(), smdTriangle_t::surf, smdModel_t::surfs, smdVertex_t::texCoords, smdSurface_t::tris, VectorCompare(), VectorCopy, VectorInverseRotate(), VectorSubtract, verbose, zSkel_Config_t::verbose, smdTriangle_t::verts, smdSurface_t::verts, smdWeight_t::weight, and smdVertex_t::weights.
Referenced by LoadSMD().
OrderMesh()
void OrderMesh (int input[][3], int output[][3], int numTris)
Definition at line 200 of file ordermesh.c.
{
     int i;
     int sumStrippedTriangles = 0;
     int strippedTriangles;
     int totalStrips = 0;
     int strip[MAX_TRIS][3];         // could dump directly into 'output', but
                                     // this helps with debugging
     memset( s_used, 0, sizeof( s_used ) );
     // while there are still triangles that are not part of a strip
     while ( sumStrippedTriangles < numTris ) {
         // build a strip
         strippedTriangles = BuildOptimizedList( input, strip, numTris );
         for ( i = 0; i < strippedTriangles; i++ ) {
             output[sumStrippedTriangles+i][0] = strip[i][0];
             output[sumStrippedTriangles+i][1] = strip[i][1];
             output[sumStrippedTriangles+i][2] = strip[i][2];
         }
         sumStrippedTriangles += strippedTriangles;
         totalStrips++;
         if(debug) {
             printf( " strips %4d stripped %5d/%5d last strip length %4d\r", totalStrips, sumStrippedTriangles, numTris, strippedTriangles );
         }
     }
     if(debug) {
         printf( "                                                            \r" );
         printf( "Triangles on surface:      %d\n", sumStrippedTriangles );
         printf( "Total strips from surface: %d\n", totalStrips );
         printf( "Average strip length:      %.1f\n", ( float ) sumStrippedTriangles / totalStrips );
     }
 }
References BuildOptimizedList(), debug, MAX_TRIS, memset(), output(), printf(), and s_used.
Referenced by FixCoords().
PrintUsage()
void PrintUsage (void)
Definition at line 100 of file zskeleton.c.
{
     printf( "zSkeleton v.%i by Alex Darby\n based on smd2md4 v.%i by Gongo\n"
             "usage: zSkeleton <configName.cfg> [options]\n"
             "options:\n"
             "  --help,-h,-?    this help message\n"
             //"  --md4           md4 output (default)\n"
             /*"  --md4a          md4anim output\n"
             "  --md4b          md4base output\n"*/
             //"  --force         overwrite if destination exists\n"
             //"  --silent        quiet program messages\n"
             /*"  --debug         enable debug output messages\n"*/, ZSKELETON_VERSION, SMD2MD4_VERSION);
 }
References printf(), SMD2MD4_VERSION, and ZSKELETON_VERSION.
Referenced by main().
ProgressiveMesh()
void ProgressiveMesh (smdSurface_t * surf)
Definition at line 406 of file progmesh.c.
{
     int i,num;
     int *permutation;
     progMeshVert_t *mn;
     smdVertex_t *verts;
     AddFaces(surf);
     AddVertices(surf);  // put input data into our data structures
     ComputeAllEdgeCollapseCosts(); // cache all edge collapse costs
     min_resolution = -1;
     permutation = (int *)calloc(surf->numVerts,sizeof(int));
     // reduce the object down to nothing:
     for( num = surf->numVerts; num > 0; num-- ) {
         // get the next vertex to collapse
         mn = MinimumCostEdge();
         // keep track of this vertex, i.e. the collapse ordering
         permutation[mn->id] = num - 1;
         // keep track of vertex to which we collapse to
         surf->map[num - 1] = mn->collapse;
         // Collapse this edge
         if(mn->collapse > -1) {
             Collapse(mn,vertices[mn->collapse]);
         } else {
             Collapse(mn,NULL);
         }
     }
     // reorder the map list based on the collapse ordering
     for(i = 0 ; i < surf->numVerts; i++) {
         surf->map[i] = (surf->map[i] == -1) ? 0 : permutation[surf->map[i]];
     }
     // reorder vertices according to permutation
     verts = (smdVertex_t *)calloc(surf->numVerts,sizeof(smdVertex_t));
     for(i = 0; i < surf->numVerts; i++) {
         verts[permutation[i]] = surf->verts[i];
     }
     for(i = 0; i < surf->numVerts; i++) {
         surf->verts[i] = verts[i];
     }
     // reorder vertex indices for triangles
     for(i = 0; i < surf->numTris; i++) {
         surf->tris[i].verts[0] = permutation[surf->tris[i].verts[0]];
         surf->tris[i].verts[1] = permutation[surf->tris[i].verts[1]];
         surf->tris[i].verts[2] = permutation[surf->tris[i].verts[2]];
     }
     if ( min_resolution == -1 ) {
         min_resolution = 0;
     }
     surf->minLod = min_resolution;
     if(debug) {
         printf("  surface %s has minimum resolution of %i vertices\r",surf->name,surf->minLod);
     }
     // clean up
     for(i = 0; i < surf->numVerts; i++) {
         free(vertices[i]->faces);
         free(vertices[i]->neighbors);
         free(vertices[i]);
     }
     numProgMeshVerts = 0;
     for(i = 0; i < surf->numTris; i++) {
         free(triangles[i]);
     }
     numProgMeshTris = 0;
 }
References AddFaces(), AddVertices(), calloc(), progMeshVert_t::collapse, Collapse(), ComputeAllEdgeCollapseCosts(), debug, free(), progMeshVert_t::id, smdSurface_t::map, min_resolution, MinimumCostEdge(), smdSurface_t::minLod, smdSurface_t::name, NULL, numProgMeshTris, numProgMeshVerts, smdSurface_t::numTris, smdSurface_t::numVerts, printf(), triangles, smdSurface_t::tris, vertices, smdTriangle_t::verts, and smdSurface_t::verts.
Referenced by FixCoords().
SaveAnimation()
void SaveAnimation (smdModel_t * smd, char fileName[32])
Definition at line 1049 of file zskeleton.c.
{
     int i,j,k;
     int surfSum = 0;
     FILE *dstFile;
     char dstFileName[512];
     md4aHeader_t dstHeader;
     md4aFrame_t dstFrame;
     md4aBoneFrame_t dstBoneFrame;
     md4aBoneName_t dstBoneName;
     int cmap[MAX_VERTS];
     smdSurface_t *surfs;
     smdTriangle_t *tris;
     smdVertex_t *verts;
     smdFrame_t *frames;
     smdBoneFrame_t *bones;
     strcpy(dstFileName,fileName);
     StripExtension(dstFileName);
     DefaultExtension(dstFileName,config.animExtension);
     if(config.verbose && !config.debug) {
         printf("   %s\r",dstFileName);
     }
     // open destination file for write
     CreatePath(dstFileName);
     dstFile = SafeOpenWrite(dstFileName);
     // prepare header information
     dstHeader.ident = LittleLong(MD4A_IDENT);
     dstHeader.version = LittleLong(MD4A_VERSION);
     strncpy(dstHeader.name,smd->name,sizeof(dstHeader.name));
     dstHeader.numFrames = LittleLong(smd->numFrames);
     dstHeader.numBones = LittleLong(smd->numBones);
     // calculate offsets
     dstHeader.ofsFrames = sizeof(md4aHeader_t);
     dstHeader.ofsBones = dstHeader.ofsFrames + ((sizeof(md4aFrame_t) + (sizeof(md4aBoneFrame_t) * (smd->numBones - 1))) * smd->numFrames);
     dstHeader.ofsEnd = dstHeader.ofsBones + (sizeof(md4aBoneName_t) * smd->numBones);
     dstHeader.ofsFrames = LittleLong(dstHeader.ofsFrames);
     dstHeader.ofsBones = LittleLong(dstHeader.ofsBones);
     dstHeader.ofsEnd = LittleLong(dstHeader.ofsEnd);
     // write out header
     SafeWrite(dstFile,&dstHeader,sizeof(md4aHeader_t));
     if(config.debug) {
         printf( "md4Header {\n"
                 "   ident       %i\n"
                 "   version     %i\n"
                 "   name        %s\n"
                 "   numFrames   %i\n"
                 "   numBones    %i\n"
                 "   ofsFrames   %i\n"
                 "   ofsBones    %i\n"
                 "   ofsEnd      %i\n"
                 "}\n",
                 dstHeader.ident,
                 dstHeader.version,
                 dstHeader.name,
                 dstHeader.numFrames,
                 dstHeader.numBones,
                 dstHeader.ofsFrames,
                 dstHeader.ofsBones,
                 dstHeader.ofsEnd );
     }
     // write out frames
     frames = smd->frames;
     for(i = 0; i < smd->numFrames; i++) {
         dstFrame.bounds[0][0] = LittleFloat(frames[i].bounds[0][0] - config.originOffset[0]);
         dstFrame.bounds[0][1] = LittleFloat(frames[i].bounds[0][1] - config.originOffset[1]);
         dstFrame.bounds[0][2] = LittleFloat(frames[i].bounds[0][2] - config.originOffset[2]);
         dstFrame.bounds[1][0] = LittleFloat(frames[i].bounds[1][0] - config.originOffset[0]);
         dstFrame.bounds[1][1] = LittleFloat(frames[i].bounds[1][1] - config.originOffset[1]);
         dstFrame.bounds[1][2] = LittleFloat(frames[i].bounds[1][2] - config.originOffset[2]);
         dstFrame.localOrigin[0] = LittleFloat(frames[i].origin[0] - config.originOffset[0]);
         dstFrame.localOrigin[1] = LittleFloat(frames[i].origin[1] - config.originOffset[1]);
         dstFrame.localOrigin[2] = LittleFloat(frames[i].origin[2] - config.originOffset[2]);
         dstFrame.radius = LittleFloat(frames[i].radius);
         SafeWrite(dstFile,&dstFrame,sizeof(md4aFrame_t) - sizeof(md4aBoneFrame_t));
         if(config.debug) {
             printf( "md4Frame %i {\n"
                     "   mins    (%f, %f, %f)\n"
                     "   maxs    (%f, %f, %f)\n"
                     "   org     (%f, %f, %f)\n"
                     "   radius  %f\n",
                     i,
                     dstFrame.bounds[0][0],
                     dstFrame.bounds[0][1],
                     dstFrame.bounds[0][2],
                     dstFrame.bounds[1][0],
                     dstFrame.bounds[1][1],
                     dstFrame.bounds[1][2],
                     dstFrame.localOrigin[0],
                     dstFrame.localOrigin[1],
                     dstFrame.localOrigin[2],
                     dstFrame.radius );
         }
         bones = frames[i].bones;
         for(j = 0; j < smd->numBones; j++) {
             dstBoneFrame.matrix[0][0] = LittleFloat(bones[j].matrix[0][0]);
             dstBoneFrame.matrix[1][0] = LittleFloat(bones[j].matrix[1][0]);
             dstBoneFrame.matrix[2][0] = LittleFloat(bones[j].matrix[2][0]);
             dstBoneFrame.matrix[0][1] = LittleFloat(bones[j].matrix[0][1]);
             dstBoneFrame.matrix[1][1] = LittleFloat(bones[j].matrix[1][1]);
             dstBoneFrame.matrix[2][1] = LittleFloat(bones[j].matrix[2][1]);
             dstBoneFrame.matrix[0][2] = LittleFloat(bones[j].matrix[0][2]);
             dstBoneFrame.matrix[1][2] = LittleFloat(bones[j].matrix[1][2]);
             dstBoneFrame.matrix[2][2] = LittleFloat(bones[j].matrix[2][2]);
             dstBoneFrame.matrix[0][3] = LittleFloat(bones[j].origin[0] - config.originOffset[0]);
             dstBoneFrame.matrix[1][3] = LittleFloat(bones[j].origin[1] - config.originOffset[1]);
             dstBoneFrame.matrix[2][3] = LittleFloat(bones[j].origin[2] - config.originOffset[2]);
             // write out bone frame
             SafeWrite(dstFile,&dstBoneFrame,sizeof(md4aBoneFrame_t));
             if(config.debug) {
                 printf( "   md4BoneFrame %i {\n"
                         "       matrix[0]   (%f, %f, %f)\n"
                         "       matrix[1]   (%f, %f, %f)\n"
                         "       matrix[2]   (%f, %f, %f)\n"
                         "       matrix[3]   (%f, %f, %f)\n"
                         "   }\n",
                         j,
                         dstBoneFrame.matrix[0][0],
                         dstBoneFrame.matrix[1][0],
                         dstBoneFrame.matrix[2][0],
                         dstBoneFrame.matrix[0][1],
                         dstBoneFrame.matrix[1][1],
                         dstBoneFrame.matrix[2][1],
                         dstBoneFrame.matrix[0][2],
                         dstBoneFrame.matrix[1][2],
                         dstBoneFrame.matrix[2][2],
                         dstBoneFrame.matrix[0][3],
                         dstBoneFrame.matrix[1][3],
                         dstBoneFrame.matrix[2][3] );
             }
         }
         if(debug) {
             printf("}\n");
         }
     }
     // write out bone names
     for(i = 0; i < smd->numBones; i++) {
         strcpy(dstBoneName.name,smd->bones[i].name);
         dstBoneName.parent = LittleLong(smd->bones[i].parent);
         dstBoneName.flags = LittleLong(smd->bones[i].flags);
         SafeWrite(dstFile,&dstBoneName,sizeof(md4aBoneName_t));
         if(config.debug) {
             printf( "md4BoneName %i {\n"
                     "   name    %s\n"
                     "   parent  %i\n"
                     "   flags   %i\n"
                     "}\n",
                     i,
                     dstBoneName.name,
                     dstBoneName.parent,
                     dstBoneName.flags );
         }
     }
     if(config.verbose && !config.debug) {
         printf( "  \n");
         // print out file summary
         printf( " stats\n"
                 "   size:   %.2f kb\n"
                 "   bones:  %i\n"
                 "   frames: %i\n",
                 ftell(dstFile)/1024.0f,
                 smd->numBones,
                 smd->numFrames );
     }
 }
References zSkel_Config_t::animExtension, bones, smdFrame_t::bones, smdModel_t::bones, md4aFrame_t::bounds, config, CreatePath(), debug, zSkel_Config_t::debug, DefaultExtension(), smdBoneName_t::flags, md4aBoneName_t::flags, smdModel_t::frames, ftell(), md4aHeader_t::ident, LittleFloat(), LittleLong(), md4aFrame_t::localOrigin, md4aBoneFrame_t::matrix, MAX_VERTS, MD4A_IDENT, MD4A_VERSION, smdBoneName_t::name, smdModel_t::name, md4aBoneName_t::name, md4aHeader_t::name, smdModel_t::numBones, md4aHeader_t::numBones, smdModel_t::numFrames, md4aHeader_t::numFrames, md4aHeader_t::ofsBones, md4aHeader_t::ofsEnd, md4aHeader_t::ofsFrames, zSkel_Config_t::originOffset, smdBoneName_t::parent, md4aBoneName_t::parent, printf(), md4aFrame_t::radius, SafeOpenWrite(), SafeWrite(), strcpy(), StripExtension(), strncpy(), zSkel_Config_t::verbose, and md4aHeader_t::version.
Referenced by DoAnims().
SaveMD4()
void SaveMD4 (void)
SaveMesh()
void SaveMesh (smdModel_t * smd, char fileName[32])
Definition at line 1249 of file zskeleton.c.
{
     int i,j,k;
     int surfSum = 0;
     FILE *dstFile;
     char dstFileName[512];
     md4bHeader_t dstHeader;
     md4bBoneName_t dstBoneName;
     md4bSurface_t dstSurface;
     md4bVertex_t dstVertex;
     md4bWeight_t dstWeight;
     md4bTriangle_t dstTriangle;
     int cmap[MAX_VERTS];
     smdSurface_t *surfs;
     smdTriangle_t *tris;
     smdVertex_t *verts;
     smdFrame_t *frames;
     smdBoneFrame_t *bones;
     strcpy(dstFileName,fileName);
     StripExtension(dstFileName);
     DefaultExtension(dstFileName,config.meshExtension);
     if(config.verbose && !config.debug) {
         printf("   %s\r",dstFileName);
     }
     // open destination file for write
     CreatePath(dstFileName);
     dstFile = SafeOpenWrite(dstFileName);
     // prepare header information
     dstHeader.ident = LittleLong(MD4B_IDENT);
     dstHeader.version = LittleLong(MD4B_VERSION);
     strncpy(dstHeader.name,dstFileName,sizeof(dstHeader.name));
     dstHeader.numBones = LittleLong(smd->numBones);
     dstHeader.numSurfs = LittleLong(smd->numSurfs);
     // calculate surface offset
     for(i = 0; i < smd->numSurfs; i++) {
         surfSum += sizeof(md4bSurface_t);
         for(j = 0; j < smd->surfs[i].numVerts; j++) {
             surfSum += sizeof(md4bVertex_t) + (sizeof(md4bWeight_t) * (smd->surfs[i].verts[j].numWeights - 1));
             // FIXME: sizeof(md4Vertex_t) is wrong, it's +4 larger than it should be...
             surfSum -= 4;
         }
         surfSum += sizeof(md4bTriangle_t) * smd->surfs[i].numTris;
         surfSum += sizeof(cmap[0]) * smd->surfs[i].numVerts;
     }
     // calculate offsets
     dstHeader.ofsBones = sizeof(md4bHeader_t);
     dstHeader.ofsSurfs = dstHeader.ofsBones + (sizeof(md4bBoneName_t) * smd->numBones);
     dstHeader.ofsEnd = dstHeader.ofsSurfs + surfSum;
     dstHeader.ofsBones = LittleLong(dstHeader.ofsBones);
     dstHeader.ofsSurfs = LittleLong(dstHeader.ofsSurfs);
     dstHeader.ofsEnd = LittleLong(dstHeader.ofsEnd);
     // write out header
     SafeWrite(dstFile,&dstHeader,sizeof(md4bHeader_t));
     if(config.debug) {
         printf( "md4Header {\n"
                 "   ident       %i\n"
                 "   version     %i\n"
                 "   name        %s\n"
                 "   numFrames   %i\n"
                 "   numBones    %i\n"
                 "   numSurfs    %i\n"
                 "   ofsFrames   %i\n"
                 "   ofsBones    %i\n"
                 "   ofsSurfs    %i\n"
                 "   ofsEnd      %i\n"
                 "}\n",
                 dstHeader.ident,
                 dstHeader.version,
                 dstHeader.name,
                 dstHeader.numBones,
                 dstHeader.numSurfs,
                 dstHeader.ofsBones,
                 dstHeader.ofsSurfs,
                 dstHeader.ofsEnd );
     }
     // write out frames
     frames = smd->frames;
     // write out bone names
     for(i = 0; i < smd->numBones; i++) {
         strcpy(dstBoneName.name,smd->bones[i].name);
         dstBoneName.parent = LittleLong(smd->bones[i].parent);
         dstBoneName.flags = LittleLong(smd->bones[i].flags);
         SafeWrite(dstFile,&dstBoneName,sizeof(md4bBoneName_t));
         if(config.debug) {
             printf( "md4BoneName %i {\n"
                     "   name    %s\n"
                     "   parent  %i\n"
                     "   flags   %i\n"
                     "}\n",
                     i,
                     dstBoneName.name,
                     dstBoneName.parent,
                     dstBoneName.flags );
         }
     }
     // write out surfaces
     surfs = smd->surfs;
     for(i = 0; i < smd->numSurfs; i++) {
         int vertSum = 0;
         // prepare surface header
         dstSurface.ident = LittleLong(MD4_IDENT);
         strcpy(dstSurface.name,surfs[i].name);
         strcpy(dstSurface.shader,"");
         dstSurface.shaderIndex = LittleLong(0);
         dstSurface.lodBias = LittleLong(0);
         dstSurface.minLod = LittleLong(surfs[i].minLod);
         dstSurface.numVerts = LittleLong(surfs[i].numVerts);
         dstSurface.numTris = LittleLong(surfs[i].numTris);
         // calculate vertex offset
         for(j = 0; j < surfs[i].numVerts; j++) {
             vertSum += sizeof(md4Vertex_t) + (sizeof(md4Weight_t) * (surfs[i].verts[j].numWeights - 1));
             // FIXME: sizeof(md4Vertex_t) is wrong, it's +4 larger than it should be...
             vertSum -= 4;
         }
         // calculate offsets
         dstSurface.ofsHeader = -ftell(dstFile);
         dstSurface.ofsVerts = sizeof(md4Surface_t);
         dstSurface.ofsTris = dstSurface.ofsVerts + vertSum;
         dstSurface.ofsCollapseMap = dstSurface.ofsTris + (sizeof(md4Triangle_t) * surfs[i].numTris);
         dstSurface.ofsEnd = dstSurface.ofsCollapseMap + (sizeof(cmap[0]) * surfs[i].numVerts);
         dstSurface.ofsHeader = LittleLong(dstSurface.ofsHeader);
         dstSurface.ofsVerts = LittleLong(dstSurface.ofsVerts);
         dstSurface.ofsTris = LittleLong(dstSurface.ofsTris);
         dstSurface.ofsCollapseMap = LittleLong(dstSurface.ofsCollapseMap);
         dstSurface.ofsEnd = LittleLong(dstSurface.ofsEnd);
         SafeWrite(dstFile,&dstSurface,sizeof(md4Surface_t));
         if(config.debug) {
             printf( "md4Surface %i {\n"
                     "   ident   %i\n"
                     "   name    %s\n"
                     "   shader  %s\n"
                     "   shaderIndex %i\n"
                     "   lodBias %i\n"
                     "   minLod  %i\n"
                     "   numVerts    %i\n"
                     "   numTris %i\n"
                     "   ofsHeader   %i\n"
                     "   ofsVerts    %i\n"
                     "   ofsTris %i\n"
                     "   ofsCollapseMap  %i\n"
                     "   ofsEnd  %i\n",
                     i,
                     dstSurface.ident,
                     dstSurface.name,
                     dstSurface.shader,
                     dstSurface.shaderIndex,
                     dstSurface.lodBias,
                     dstSurface.minLod,
                     dstSurface.numVerts,
                     dstSurface.numTris,
                     dstSurface.ofsHeader,
                     dstSurface.ofsVerts,
                     dstSurface.ofsTris,
                     dstSurface.ofsCollapseMap,
                     dstSurface.ofsEnd );
         }
         // write out vertices
         verts = surfs[i].verts;
         for(j = 0; j < surfs[i].numVerts; j++) {
             dstVertex.normal[0] = LittleFloat(verts[j].normal[0]);
             dstVertex.normal[1] = LittleFloat(verts[j].normal[1]);
             dstVertex.normal[2] = LittleFloat(verts[j].normal[2]);
             dstVertex.texCoords[0] = LittleFloat(verts[j].texCoords[0]);
             dstVertex.texCoords[1] = LittleFloat(verts[j].texCoords[1]);
             dstVertex.numWeights = LittleLong(verts[j].numWeights);
             // FIXME: sizeof(md4Vertex_t) is wrong, it's +4 larger than it should be...
             SafeWrite(dstFile,&dstVertex.normal[0],sizeof(dstVertex.normal[0]));
             SafeWrite(dstFile,&dstVertex.normal[1],sizeof(dstVertex.normal[1]));
             SafeWrite(dstFile,&dstVertex.normal[2],sizeof(dstVertex.normal[2]));
             SafeWrite(dstFile,&dstVertex.texCoords[0],sizeof(dstVertex.texCoords[0]));
             SafeWrite(dstFile,&dstVertex.texCoords[1],sizeof(dstVertex.texCoords[1]));
             SafeWrite(dstFile,&dstVertex.numWeights,sizeof(dstVertex.numWeights));
             if(config.debug) {
                 printf( "   md4Vertex %i {\n"
                         "       normal  (%f, %f, %f)\n"
                         "       texCoords   (%f, %f)\n"
                         "       numWeights  %i\n",
                         j,
                         dstVertex.normal[0],
                         dstVertex.normal[1],
                         dstVertex.normal[2],
                         dstVertex.texCoords[0],
                         dstVertex.texCoords[1],
                         dstVertex.numWeights );
             }
             // write out influences
             for(k = 0; k < verts[j].numWeights; k++) {
                 float normal[3];
                 dstWeight.boneIndex = LittleLong(verts[j].weights[k].bone);
                 dstWeight.boneWeight = LittleFloat(verts[j].weights[k].weight);
                 dstWeight.offset[0] = LittleFloat(verts[j].weights[k].offset[0]);
                 dstWeight.offset[1] = LittleFloat(verts[j].weights[k].offset[1]);
                 dstWeight.offset[2] = LittleFloat(verts[j].weights[k].offset[2]);
                 VectorInverseRotate(verts[j].normal,bones[verts[j].weights[k].bone].matrix ,normal);
                 VectorNormalize(normal,dstWeight.normalOffset);
                 dstWeight.normalOffset[0] = LittleFloat(verts[j].weights[k].normalOffset[0]);
                 dstWeight.normalOffset[1] = LittleFloat(verts[j].weights[k].normalOffset[1]);
                 dstWeight.normalOffset[2] = LittleFloat(verts[j].weights[k].normalOffset[2]);
                 SafeWrite(dstFile,&dstWeight,sizeof(md4Weight_t));
                 if(config.debug) {
                     printf( "       md4Weight %i {\n"
                             "           boneIndex   %i\n"
                             "           boneWeight  %f\n"
                             "           offset  (%f, %f, %f)\n"
                             "           normalOffset    (%f, %f, %f)\n"
                             "       }\n",
                             k,
                             dstWeight.boneIndex,
                             dstWeight.boneWeight,
                             dstWeight.offset[0],
                             dstWeight.offset[1],
                             dstWeight.offset[2],
                             dstWeight.normalOffset[0],
                             dstWeight.normalOffset[1],
                             dstWeight.normalOffset[2]);
                 }
             }
             if(config.debug) {
                 printf("    }\n");
             }
         }
         // write out triangles
         tris = surfs[i].tris;
         for(j = 0; j < surfs[i].numTris; j++) {
             dstTriangle.indexes[0] = LittleLong(tris[j].verts[0]);
             dstTriangle.indexes[1] = LittleLong(tris[j].verts[1]);
             dstTriangle.indexes[2] = LittleLong(tris[j].verts[2]);
             SafeWrite(dstFile,&dstTriangle,sizeof(md4Triangle_t));
             if(config.debug) {
                 printf( "   md4Triangle %i {\n"
                         "       indexes (%i, %i, %i)\n"
                         "   }\n",
                         j,
                         dstTriangle.indexes[0],
                         dstTriangle.indexes[1],
                         dstTriangle.indexes[2] );
             }
         }
         if(config.debug) {
             printf( "   md4CollapseMap %i {\n",
                     i );
         }
         // write out collapse map
         for(j = 0; j < surfs[i].numVerts; j++) {
             cmap[j] = LittleLong(surfs[i].map[j]);
             if(config.debug) {
                 printf( "       %i  %i\n",
                         j,
                         cmap[j] );
             }
         }
         SafeWrite(dstFile,cmap,sizeof(cmap[0]) * surfs[i].numVerts);
         if(config.debug) {
             printf("    }\n");
         }
         if(config.debug) {
             printf("}\n");
         }
     }
     if(config.verbose && !config.debug) {
         int totalTris = 0, totalVerts = 0;
         printf( "  \n");
         for(i = 0; i < smd->numSurfs; i++) {
             totalTris += surfs[i].numTris;
             totalVerts += surfs[i].numVerts;
         }
         // print out file summary
         printf( " stats\n"
                 "   size:   %.2f kb\n"
                 "   bones:  %i\n"
                 "   frames: %i\n"
                 "   surfaces:  %i\n"
                 "   triangles: %i\n"
                 "   vertices:  %i\n",
                 ftell(dstFile)/1024.0f,
                 smd->numBones,
                 smd->numFrames,
                 smd->numSurfs,
                 totalTris,
                 totalVerts );
     }
 }
References bone, md4bWeight_t::boneIndex, bones, smdModel_t::bones, md4bWeight_t::boneWeight, config, CreatePath(), zSkel_Config_t::debug, DefaultExtension(), smdBoneName_t::flags, md4bBoneName_t::flags, smdModel_t::frames, ftell(), md4bSurface_t::ident, md4bHeader_t::ident, md4bTriangle_t::indexes, LittleFloat(), LittleLong(), md4bSurface_t::lodBias, MAX_VERTS, MD4_IDENT, MD4B_IDENT, MD4B_VERSION, zSkel_Config_t::meshExtension, md4bSurface_t::minLod, smdBoneName_t::name, smdSurface_t::name, md4bBoneName_t::name, md4bSurface_t::name, md4bHeader_t::name, md4bVertex_t::normal, md4bWeight_t::normalOffset, smdModel_t::numBones, md4bHeader_t::numBones, smdModel_t::numFrames, smdModel_t::numSurfs, md4bHeader_t::numSurfs, smdSurface_t::numTris, md4bSurface_t::numTris, numVerts, smdSurface_t::numVerts, md4bSurface_t::numVerts, smdVertex_t::numWeights, md4bVertex_t::numWeights, md4bWeight_t::offset, md4bHeader_t::ofsBones, md4bSurface_t::ofsCollapseMap, md4bSurface_t::ofsEnd, md4bHeader_t::ofsEnd, md4bSurface_t::ofsHeader, md4bHeader_t::ofsSurfs, md4bSurface_t::ofsTris, md4bSurface_t::ofsVerts, smdBoneName_t::parent, md4bBoneName_t::parent, printf(), SafeOpenWrite(), SafeWrite(), md4bSurface_t::shader, md4bSurface_t::shaderIndex, strcpy(), StripExtension(), strncpy(), smdModel_t::surfs, md4bVertex_t::texCoords, smdSurface_t::tris, VectorInverseRotate(), VectorNormalize(), zSkel_Config_t::verbose, md4bHeader_t::version, and smdSurface_t::verts.
Referenced by DoMeshes().
Variable Documentation
debug
qboolean debug
Definition at line 109 of file zskeleton.h.
indicator
char indicator[]
progress
int progress
verbose
qboolean verbose
Definition at line 159 of file cmdlib.c.
Referenced by LoadCFG(), LoadSMD_ParseTriangles(), puttokens(), qprintf(), and setup().