ZEQ2-Lite: __gnu_debug::_Safe_iterator_base Class Reference
__gnu_debug::_Safe_iterator_base Class Reference
Basic functionality for a safe iterator.
#include <safe_base.h>
Public Member Functions
void _M_attach (_Safe_sequence_base *__seq, bool __constant)
Attaches this iterator to the given sequence, detaching it from whatever sequence it was attached to originally.
void _M_attach_single (_Safe_sequence_base *__seq, bool __constant) throw ()
Likewise, but not thread-safe.
bool _M_attached_to (const _Safe_sequence_base *__seq) const
Determines if we are attached to the given sequence.
_GLIBCXX_PURE bool _M_can_compare (const _Safe_iterator_base &__x) const throw ()
Can we compare this iterator to the given iterator __x? Returns true if both iterators are nonsingular and reference the same sequence.
void _M_detach ()
Detach the iterator for whatever sequence it is attached to, if any.
void _M_detach_single () throw ()
Likewise, but not thread-safe.
void _M_invalidate ()
Invalidate the iterator, making it singular.
void _M_reset () throw ()
Reset all member variables.
_GLIBCXX_PURE bool _M_singular () const throw ()
Is this iterator singular?
void _M_unlink () throw ()
Unlink itself.
Data Fields
_Safe_iterator_base * _M_next
Pointer to the next iterator in the sequence's list of iterators.
_Safe_iterator_base * _M_prior
Pointer to the previous iterator in the sequence's list of iterators.
_Safe_sequence_base * _M_sequence
The sequence this iterator references; may be NULL to indicate a singular iterator.
unsigned int _M_version
The version number of this iterator.
Protected Member Functions
_Safe_iterator_base ()
Initializes the iterator and makes it singular.
_Safe_iterator_base (const _Safe_iterator_base &)
_Safe_iterator_base (const _Safe_iterator_base &__x, bool __constant)
Initializes the iterator to reference the same sequence that __x does.
_Safe_iterator_base (const _Safe_sequence_base *__seq, bool __constant)
Initialize the iterator to reference the sequence pointed to by @p__seq.
~_Safe_iterator_base ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
For use in _Safe_iterator.
_Safe_iterator_base & operator= (const _Safe_iterator_base &)
Detailed Description
Basic functionality for a safe iterator.
The _Safe_iterator_base base class implements the functionality of a safe iterator that is not specific to a particular iterator type. It contains a pointer back to the sequence it references along with iterator version information and pointers to form a doubly-linked list of iterators referenced by the container.
This class must not perform any operations that can throw an exception, or the exception guarantees of derived iterators will be broken.
Definition at line 51 of file safe_base.h.
Constructor & Destructor Documentation
_Safe_iterator_base() [1/4]
__gnu_debug::_Safe_iterator_base::_Safe_iterator_base () inline protected
Initializes the iterator and makes it singular.
Definition at line 77 of file safe_base.h.
     : _M_sequence(0), _M_version(0), _M_prior(0), _M_next(0)
     { }
_Safe_iterator_base() [2/4]
__gnu_debug::_Safe_iterator_base::_Safe_iterator_base (const _Safe_sequence_base * __seq, bool __constant) inline protected
Initialize the iterator to reference the sequence pointed to by @p__seq.
__constant is true when we are initializing a constant iterator, and false if it is a mutable iterator. Note that __seq may be NULL, in which case the iterator will be singular. Otherwise, the iterator will reference __seq and be nonsingular.
Definition at line 88 of file safe_base.h.
     : _M_sequence(0), _M_version(0), _M_prior(0), _M_next(0)
     { this->_M_attach(const_cast<_Safe_sequence_base*>(__seq), __constant); }
References _M_attach().
_Safe_iterator_base() [3/4]
__gnu_debug::_Safe_iterator_base::_Safe_iterator_base (const _Safe_iterator_base & __x, bool __constant) inline protected
Initializes the iterator to reference the same sequence that __x does.
__constant is true if this is a constant iterator, and false if it is mutable.
Definition at line 95 of file safe_base.h.
     : _M_sequence(0), _M_version(0), _M_prior(0), _M_next(0)
     { this->_M_attach(__x._M_sequence, __constant); }
References _M_attach(), and _M_sequence.
_Safe_iterator_base() [4/4]
__gnu_debug::_Safe_iterator_base::_Safe_iterator_base (const _Safe_iterator_base &) explicit protected
~_Safe_iterator_base()
__gnu_debug::_Safe_iterator_base::~_Safe_iterator_base () inline protected
Definition at line 105 of file safe_base.h.
 { this->_M_detach(); }
References _M_detach().
Member Function Documentation
_M_attach()
void __gnu_debug::_Safe_iterator_base::_M_attach (_Safe_sequence_base * __seq, bool __constant)
Attaches this iterator to the given sequence, detaching it from whatever sequence it was attached to originally.
If the new sequence is the NULL pointer, the iterator is left unattached.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), and _Safe_iterator_base().
_M_attach_single()
void __gnu_debug::_Safe_iterator_base::_M_attach_single (_Safe_sequence_base * __seq, bool __constant) throw ()
Likewise, but not thread-safe.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach_single().
_M_attached_to()
bool __gnu_debug::_Safe_iterator_base::_M_attached_to (const _Safe_sequence_base * __seq) const inline
Determines if we are attached to the given sequence.
Definition at line 130 of file safe_base.h.
     { return _M_sequence == __seq; }
References _M_sequence.
_M_can_compare()
_GLIBCXX_PURE bool __gnu_debug::_Safe_iterator_base::_M_can_compare (const _Safe_iterator_base & __x) const throw ()
Can we compare this iterator to the given iterator __x? Returns true if both iterators are nonsingular and reference the same sequence.
_M_detach()
void __gnu_debug::_Safe_iterator_base::_M_detach ()
Detach the iterator for whatever sequence it is attached to, if any.
Referenced by ~_Safe_iterator_base().
_M_detach_single()
void __gnu_debug::_Safe_iterator_base::_M_detach_single () throw ()
Likewise, but not thread-safe.
_M_get_mutex()
__gnu_cxx::__mutex& __gnu_debug::_Safe_iterator_base::_M_get_mutex () throw () protected
For use in _Safe_iterator.
_M_invalidate()
void __gnu_debug::_Safe_iterator_base::_M_invalidate () inline
Invalidate the iterator, making it singular.
Definition at line 143 of file safe_base.h.
     { _M_version = 0; }
References _M_version.
_M_reset()
void __gnu_debug::_Safe_iterator_base::_M_reset () throw ()
Reset all member variables.
_M_singular()
_GLIBCXX_PURE bool __gnu_debug::_Safe_iterator_base::_M_singular () const throw ()
Is this iterator singular?
Referenced by __gnu_debug::__check_singular_aux().
_M_unlink()
void __gnu_debug::_Safe_iterator_base::_M_unlink () throw () inline
Unlink itself.
Definition at line 152 of file safe_base.h.
     {
       if (_M_prior)
     _M_prior->_M_next = _M_next;
       if (_M_next)
     _M_next->_M_prior = _M_prior;
     }
References _M_next, and _M_prior.
operator=()
_Safe_iterator_base& __gnu_debug::_Safe_iterator_base::operator= (const _Safe_iterator_base &) protected
Field Documentation
_M_next
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_next
Pointer to the next iterator in the sequence's list of iterators.
Only valid when _M_sequence != NULL.
Definition at line 73 of file safe_base.h.
Referenced by _M_unlink().
_M_prior
_Safe_iterator_base* __gnu_debug::_Safe_iterator_base::_M_prior
Pointer to the previous iterator in the sequence's list of iterators.
Only valid when _M_sequence != NULL.
Definition at line 69 of file safe_base.h.
Referenced by _M_unlink().
_M_sequence
_Safe_sequence_base* __gnu_debug::_Safe_iterator_base::_M_sequence
The sequence this iterator references; may be NULL to indicate a singular iterator.
Definition at line 56 of file safe_base.h.
Referenced by _M_attached_to(), and _Safe_iterator_base().
_M_version
unsigned int __gnu_debug::_Safe_iterator_base::_M_version
The version number of this iterator.
The sentinel value 0 is used to indicate an invalidated iterator (i.e., one that is singular because of an operation on the container). This version number must equal the version number in the sequence referenced by _M_sequence for the iterator to be non-singular.
Definition at line 65 of file safe_base.h.
Referenced by _M_invalidate().
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/debug/safe_base.h