ZEQ2-Lite: Brush Class Reference
Brush Class Reference
#include <gdiplusbrush.h>
Public Member Functions
virtual ~Brush ()
virtual Brush * Clone () const
Status GetLastStatus () const
BrushType GetType () const
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Brush ()
Brush (const Brush &brush)
Brush (GpBrush *brush, Status status)
Brush & operator= (const Brush &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpBrush * nativeBrush
Friends
class Graphics
class HatchBrush
class LinearGradientBrush
class PathGradientBrush
class Pen
class SolidBrush
class TextureBrush
Detailed Description
Definition at line 33 of file gdiplusbrush.h.
Constructor & Destructor Documentation
~Brush()
virtual Brush::~Brush () inline virtual
Definition at line 44 of file gdiplusbrush.h.
     {
         DllExports::GdipDeleteBrush(nativeBrush);
     }
References GdipDeleteBrush(), and nativeBrush.
Brush() [1/3]
Brush::Brush () inline private
Definition at line 68 of file gdiplusbrush.h.
 : nativeBrush(NULL), lastStatus(Ok) {}
Brush() [2/3]
Brush::Brush (GpBrush * brush, Status status) inline private
Definition at line 69 of file gdiplusbrush.h.
                                         :
         nativeBrush(brush), lastStatus(status) {}
Brush() [3/3]
Brush::Brush (const Brush & brush) private
Member Function Documentation
Clone()
virtual Brush* Brush::Clone () const inline virtual
Reimplemented in PathGradientBrush, TextureBrush, SolidBrush, LinearGradientBrush, and HatchBrush.
Definition at line 48 of file gdiplusbrush.h.
     {
         lastStatus = NotImplemented;
         return NULL;
     }
References lastStatus, NotImplemented, and NULL.
GetLastStatus()
Status Brush::GetLastStatus () const inline
Definition at line 54 of file gdiplusbrush.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetType()
BrushType Brush::GetType () const inline
Definition at line 60 of file gdiplusbrush.h.
     {
         BrushType result = BrushTypeSolidColor;
         updateStatus(DllExports::GdipGetBrushType(nativeBrush, &result));
         return result;
     }
References BrushTypeSolidColor, GdipGetBrushType(), nativeBrush, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Brush& Brush::operator= (const Brush &) private
updateStatus()
Status Brush::updateStatus (Status newStatus) const inline private
Definition at line 74 of file gdiplusbrush.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), HatchBrush::GetBackgroundColor(), LinearGradientBrush::GetBlend(), PathGradientBrush::GetBlend(), LinearGradientBrush::GetBlendCount(), PathGradientBrush::GetBlendCount(), PathGradientBrush::GetCenterColor(), PathGradientBrush::GetCenterPoint(), SolidBrush::GetColor(), PathGradientBrush::GetFocusScales(), HatchBrush::GetForegroundColor(), LinearGradientBrush::GetGammaCorrection(), PathGradientBrush::GetGammaCorrection(), HatchBrush::GetHatchStyle(), LinearGradientBrush::GetInterpolationColorCount(), PathGradientBrush::GetInterpolationColorCount(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetPointCount(), LinearGradientBrush::GetRectangle(), PathGradientBrush::GetRectangle(), PathGradientBrush::GetSurroundColorCount(), PathGradientBrush::GetSurroundColors(), LinearGradientBrush::GetTransform(), PathGradientBrush::GetTransform(), TextureBrush::GetTransfrom(), GetType(), LinearGradientBrush::GetWrapMode(), TextureBrush::GetWrapMode(), PathGradientBrush::GetWrapMode(), LinearGradientBrush::MultiplyTransform(), TextureBrush::MultiplyTransform(), PathGradientBrush::MultiplyTransform(), LinearGradientBrush::ResetTransform(), TextureBrush::ResetTransform(), PathGradientBrush::ResetTransform(), LinearGradientBrush::RotateTranform(), TextureBrush::RotateTransform(), PathGradientBrush::RotateTransform(), LinearGradientBrush::ScaleTransform(), TextureBrush::ScaleTransform(), PathGradientBrush::ScaleTransform(), LinearGradientBrush::SetBlend(), PathGradientBrush::SetBlend(), LinearGradientBrush::SetBlendBellShape(), PathGradientBrush::SetBlendBellShape(), LinearGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetCenterColor(), PathGradientBrush::SetCenterPoint(), SolidBrush::SetColor(), PathGradientBrush::SetFocusScales(), LinearGradientBrush::SetGammaCorrection(), PathGradientBrush::SetGammaCorrection(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), LinearGradientBrush::SetLinearColors(), PathGradientBrush::SetSurroundColors(), LinearGradientBrush::SetTransform(), TextureBrush::SetTransform(), PathGradientBrush::SetTransform(), LinearGradientBrush::SetWrapMode(), TextureBrush::SetWrapMode(), PathGradientBrush::SetWrapMode(), LinearGradientBrush::TranslateTransform(), TextureBrush::TranslateTransform(), and PathGradientBrush::TranslateTransform().
Friends And Related Function Documentation
Graphics
friend class Graphics friend
Definition at line 40 of file gdiplusbrush.h.
HatchBrush
friend class HatchBrush friend
Definition at line 35 of file gdiplusbrush.h.
Referenced by HatchBrush::Clone().
LinearGradientBrush
friend class LinearGradientBrush friend
Definition at line 36 of file gdiplusbrush.h.
Referenced by LinearGradientBrush::Clone().
PathGradientBrush
friend class PathGradientBrush friend
Definition at line 37 of file gdiplusbrush.h.
Referenced by PathGradientBrush::Clone().
Pen
friend class Pen friend
Definition at line 41 of file gdiplusbrush.h.
SolidBrush
friend class SolidBrush friend
Definition at line 38 of file gdiplusbrush.h.
Referenced by SolidBrush::Clone().
TextureBrush
friend class TextureBrush friend
Definition at line 39 of file gdiplusbrush.h.
Referenced by TextureBrush::Clone().
Field Documentation
lastStatus
Status Brush::lastStatus mutable private
Definition at line 81 of file gdiplusbrush.h.
Referenced by Clone(), HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), GetLastStatus(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetSurroundColors(), HatchBrush::HatchBrush(), LinearGradientBrush::LinearGradientBrush(), PathGradientBrush::PathGradientBrush(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), PathGradientBrush::SetSurroundColors(), SolidBrush::SolidBrush(), TextureBrush::TextureBrush(), and updateStatus().
nativeBrush
GpBrush* Brush::nativeBrush private
Definition at line 80 of file gdiplusbrush.h.
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), Graphics::DrawDriverString(), Graphics::DrawString(), Graphics::FillClosedCurve(), Graphics::FillEllipse(), Graphics::FillPath(), Graphics::FillPie(), Graphics::FillPolygon(), Graphics::FillRectangle(), Graphics::FillRectangles(), Graphics::FillRegion(), HatchBrush::GetBackgroundColor(), LinearGradientBrush::GetBlend(), PathGradientBrush::GetBlend(), LinearGradientBrush::GetBlendCount(), PathGradientBrush::GetBlendCount(), PathGradientBrush::GetCenterColor(), PathGradientBrush::GetCenterPoint(), SolidBrush::GetColor(), PathGradientBrush::GetFocusScales(), HatchBrush::GetForegroundColor(), LinearGradientBrush::GetGammaCorrection(), PathGradientBrush::GetGammaCorrection(), HatchBrush::GetHatchStyle(), LinearGradientBrush::GetInterpolationColorCount(), PathGradientBrush::GetInterpolationColorCount(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetPointCount(), LinearGradientBrush::GetRectangle(), PathGradientBrush::GetRectangle(), PathGradientBrush::GetSurroundColorCount(), PathGradientBrush::GetSurroundColors(), LinearGradientBrush::GetTransform(), PathGradientBrush::GetTransform(), TextureBrush::GetTransfrom(), GetType(), LinearGradientBrush::GetWrapMode(), TextureBrush::GetWrapMode(), PathGradientBrush::GetWrapMode(), HatchBrush::HatchBrush(), LinearGradientBrush::LinearGradientBrush(), LinearGradientBrush::MultiplyTransform(), TextureBrush::MultiplyTransform(), PathGradientBrush::MultiplyTransform(), PathGradientBrush::PathGradientBrush(), Pen::Pen(), LinearGradientBrush::ResetTransform(), TextureBrush::ResetTransform(), PathGradientBrush::ResetTransform(), LinearGradientBrush::RotateTranform(), TextureBrush::RotateTransform(), PathGradientBrush::RotateTransform(), LinearGradientBrush::ScaleTransform(), TextureBrush::ScaleTransform(), PathGradientBrush::ScaleTransform(), LinearGradientBrush::SetBlend(), PathGradientBrush::SetBlend(), LinearGradientBrush::SetBlendBellShape(), PathGradientBrush::SetBlendBellShape(), LinearGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetBlendTriangularShape(), Pen::SetBrush(), PathGradientBrush::SetCenterColor(), PathGradientBrush::SetCenterPoint(), SolidBrush::SetColor(), PathGradientBrush::SetFocusScales(), LinearGradientBrush::SetGammaCorrection(), PathGradientBrush::SetGammaCorrection(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), LinearGradientBrush::SetLinearColors(), PathGradientBrush::SetSurroundColors(), LinearGradientBrush::SetTransform(), TextureBrush::SetTransform(), PathGradientBrush::SetTransform(), LinearGradientBrush::SetWrapMode(), TextureBrush::SetWrapMode(), PathGradientBrush::SetWrapMode(), SolidBrush::SolidBrush(), TextureBrush::TextureBrush(), LinearGradientBrush::TranslateTransform(), TextureBrush::TranslateTransform(), PathGradientBrush::TranslateTransform(), and ~Brush().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusbrush.h