ZEQ2-Lite: Engine/libspeex/lpc.h File Reference
lpc.h File Reference
Functions for LPC (Linear Prediction Coefficients) analysis.
#include "arch.h"
Functions
void _spx_autocorr (const spx_word16_t *x, spx_word16_t *ac, int lag, int n)
spx_word32_t _spx_lpc (spx_coef_t *lpc, const spx_word16_t *ac, int p)
Detailed Description
Functions for LPC (Linear Prediction Coefficients) analysis.
Definition in file lpc.h.
Function Documentation
_spx_autocorr()
void _spx_autocorr (const spx_word16_t * x, spx_word16_t * ac, int lag, int n)
Definition at line 181 of file lpc.c.
 {
    float d;
    int i;
    while (lag--)
    {
       for (i = lag, d = 0; i < n; i++)
          d += x[i] * x[i-lag];
       ac[lag] = d;
    }
    ac[0] += 10;
 }
References ac, ADD32, MULT16_16, and SHR32.
Referenced by nb_encode(), and sb_encode().
_spx_lpc()
spx_word32_t _spx_lpc (spx_coef_t * lpc, const spx_word16_t * ac, int p)
Definition at line 73 of file lpc.c.
 {
    int i, j;
    spx_word16_t r;
    spx_word16_t error = ac[0];
    if (ac[0] == 0)
    {
       for (i = 0; i < p; i++)
          lpc[i] = 0;
       return 0;
    }
    for (i = 0; i < p; i++) {
       /* Sum up this iteration's reflection coefficient */
       spx_word32_t rr = NEG32(SHL32(EXTEND32(ac[i + 1]),13));
       for (j = 0; j < i; j++)
          rr = SUB32(rr,MULT16_16(lpc[j],ac[i - j]));
 #ifdef FIXED_POINT
       r = DIV32_16(rr+PSHR32(error,1),ADD16(error,8));
 #else
       r = rr/(error+.003*ac[0]);
 #endif
       /*  Update LPC coefficients and total error */
       lpc[i] = r;
       for (j = 0; j < i>>1; j++)
       {
          spx_word16_t tmp  = lpc[j];
          lpc[j]     = MAC16_16_P13(lpc[j],r,lpc[i-1-j]);
          lpc[i-1-j] = MAC16_16_P13(lpc[i-1-j],r,tmp);
       }
       if (i & 1)
          lpc[j] = MAC16_16_P13(lpc[j],lpc[j],r);
       error = SUB16(error,MULT16_16_Q13(r,MULT16_16_Q13(error,r)));
    }
    return error;
 }
References ac, ADD16, DIV32_16, error(), EXTEND32, MAC16_16_P13, MULT16_16, MULT16_16_Q13, NEG32, PSHR32, SHL32, SUB16, and SUB32.
Referenced by nb_encode(), and sb_encode().