ZEQ2-Lite: Game/UI/ui_atoms.c File Reference
ui_atoms.c File Reference
#include "ui_local.h"
Macros
#define PROPB_GAP_WIDTH 4
#define PROPB_HEIGHT 36
#define PROPB_SPACE_WIDTH 12
Functions
void QDECL Com_Error (int level, const char *error,...)
void QDECL Com_Printf (const char *msg,...)
void UI_AdjustFrom640 (float *x, float *y, float *w, float *h)
char * UI_Argv (int arg)
void UI_Cache_f (void)
float UI_ClampCvar (float min, float max, float value)
qboolean UI_ConsoleCommand (int realTime)
qboolean UI_CursorInRect (int x, int y, int width, int height)
char * UI_Cvar_VariableString (const char *var_name)
void UI_DrawBackPic (qboolean drawPic)
void UI_DrawBannerString (int x, int y, const char *str, int style, vec4_t color)
static void UI_DrawBannerString2 (int x, int y, const char *str, vec4_t color)
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
void UI_DrawNamedPic (float x, float y, float width, float height, const char *picname)
void UI_DrawProportionalString (int x, int y, const char *str, int style, vec4_t color)
static void UI_DrawProportionalString2 (int x, int y, const char *str, vec4_t color, float sizeScale, qhandle_t charset)
void UI_DrawRect (float x, float y, float width, float height, const float *color)
void UI_DrawString (int x, int y, const char *str, int style, vec4_t color)
static void UI_DrawString2 (int x, int y, const char *str, vec4_t color, int charw, int charh)
int UI_DrawStrlen (const char *str)
void UI_DrawTextBox (int x, int y, int width, int lines)
void UI_FillRect (float x, float y, float width, float height, const float *color)
void UI_ForceMenuOff (void)
void UI_Init (void)
qboolean UI_IsFullscreen (void)
void UI_KeyEvent (int key, int down)
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
void UI_MenuLogo (void)
void UI_MenuScene (void)
void UI_MouseEvent (int dx, int dy)
void UI_PopMenu (void)
float UI_ProportionalSizeScale (int style)
int UI_ProportionalStringWidth (const char *str)
void UI_PushMenu (menuframework_s *menu)
void UI_Refresh (int realtime)
void UI_SetActiveMenu (uiMenuCommand_t menu)
void UI_SetColor (const float *rgba)
void UI_Shutdown (void)
void UI_StartDemoLoop (void)
void UI_UpdateScreen (void)
Variables
qboolean m_entersound
static int propMap [128][3]
static int propMapB [26][3]
uiStatic_t uis
Macro Definition Documentation
PROPB_GAP_WIDTH
#define PROPB_GAP_WIDTH 4
Definition at line 328 of file ui_atoms.c.
PROPB_HEIGHT
#define PROPB_HEIGHT 36
Definition at line 330 of file ui_atoms.c.
PROPB_SPACE_WIDTH
#define PROPB_SPACE_WIDTH 12
Definition at line 329 of file ui_atoms.c.
Function Documentation
Com_Error()
void QDECL Com_Error (int level, const char * error, ...)
Definition at line 33 of file ui_atoms.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, error);
     Q_vsnprintf (text, sizeof(text), error, argptr);
     va_end (argptr);
     trap_Error( va("%s", text) );
 }
References error(), Q_vsnprintf, trap_Error(), and va().
Com_Printf()
void QDECL Com_Printf (const char * msg, ...)
Definition at line 44 of file ui_atoms.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, msg);
     Q_vsnprintf (text, sizeof(text), msg, argptr);
     va_end (argptr);
     trap_Print( va("%s", text) );
 }
References Q_vsnprintf, trap_Print(), and va().
Referenced by UI_SetActiveMenu().
UI_AdjustFrom640()
void UI_AdjustFrom640 (float * x, float * y, float * w, float * h)
Definition at line 984 of file ui_atoms.c.
{
     qboolean stretch = qtrue;
     *x *= uis.scaleX;
     *y *= uis.scaleY;
     *w *= stretch ? uis.scaleX : 1.6;
     *h *= stretch ? uis.scaleY : 1.6;
 }
References qtrue, uiStatic_t::scaleX, uiStatic_t::scaleY, and uis.
Referenced by UI_DrawBackPic(), UI_DrawConnectScreen(), UI_DrawHandlePic(), UI_DrawNamedPic(), UI_DrawPlayer(), UI_DrawRect(), UI_FillRect(), UI_MenuLogo(), and UI_MenuScene().
UI_Argv()
char* UI_Argv (int arg)
Definition at line 918 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Argv( arg, buffer, sizeof( buffer ) );
     return buffer;
 }
References MAX_STRING_CHARS, and trap_Argv().
UI_Cache_f()
void UI_Cache_f (void)
Definition at line 941 of file ui_atoms.c.
{
 }
UI_ClampCvar()
float UI_ClampCvar (float min, float max, float value)
Definition at line 60 of file ui_atoms.c.
 {
     if ( value < min ) return min;
     if ( value > max ) return max;
     return value;
 }
Referenced by Camera_GetConfig().
UI_ConsoleCommand()
qboolean UI_ConsoleCommand (int realTime)
Definition at line 950 of file ui_atoms.c.
{
     char    *cmd;
     //cmd = UI_Argv(0);
     //Menu_Cache();
     return qfalse;
 }
References qfalse.
Referenced by vmMain().
UI_CursorInRect()
qboolean UI_CursorInRect (int x, int y, int width, int height)
Definition at line 1287 of file ui_atoms.c.
 {
     if (uis.cursorx < x ||
         uis.cursory < y ||
         uis.cursorx > x+width ||
         uis.cursory > y+height)
         return qfalse;
     return qtrue;
 }
References uiStatic_t::cursorx, uiStatic_t::cursory, qfalse, qtrue, and uis.
Referenced by ScrollList_Key().
UI_Cvar_VariableString()
char* UI_Cvar_VariableString (const char * var_name)
Definition at line 927 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Cvar_VariableStringBuffer( var_name, buffer, sizeof( buffer ) );
     return buffer;
 }
References MAX_STRING_CHARS, and trap_Cvar_VariableStringBuffer().
Referenced by Controls_InitModel(), StartServer_SetMenuItems(), SystemSettings_GetResolutions(), SystemSettings_SetMenuItems(), and UI_MainMenu().
UI_DrawBackPic()
void UI_DrawBackPic (qboolean drawPic)
Definition at line 1231 of file ui_atoms.c.
{
     float x, y, w, h;
     if (!drawPic) {
         UI_FillRect(0, 0, 640, 480, colorBlack);
     }
     else {
         x = 0;
         y = 0;
         w = 640;
         h = 480;
         UI_AdjustFrom640(&x, &y, &w, &h);
         trap_R_DrawStretchPic(x, y, w, h, 0, 0, 1, 768.0/1024.0, uis.menuBackShader);
     }
 }
References colorBlack, uiStatic_t::menuBackShader, trap_R_DrawStretchPic(), UI_AdjustFrom640(), UI_FillRect(), and uis.
Referenced by UI_DrawConnectScreen().
UI_DrawBannerString()
void UI_DrawBannerString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 402 of file ui_atoms.c.
{
     const char *    s;
     int             ch;
     int             width;
     vec4_t          drawcolor;
     // find the width of the drawn text
     s = str;
     width = 0;
     while ( *s ) {
         ch = *s;
         if ( ch == ' ' ) {
             width += PROPB_SPACE_WIDTH;
         }
         else if ( ch >= 'A' && ch <= 'Z' ) {
             width += propMapB[ch - 'A'][2] + PROPB_GAP_WIDTH;
         }
         s++;
     }
     width -= PROPB_GAP_WIDTH;
     switch( style & UI_FORMATMASK ) {
         case UI_CENTER:
             x -= width / 2;
             break;
         case UI_RIGHT:
             x -= width;
             break;
         case UI_LEFT:
         default:
             break;
     }
     if ( style & UI_DROPSHADOW ) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = 0.7;
         UI_DrawBannerString2( x+1, y+1, str, drawcolor );
     }
     UI_DrawBannerString2( x, y, str, color );
 }
References PROPB_GAP_WIDTH, PROPB_SPACE_WIDTH, propMapB, UI_CENTER, UI_DrawBannerString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_LEFT, and UI_RIGHT.
UI_DrawBannerString2()
static void UI_DrawBannerString2 (int x, int y, const char * str, vec4_t color) static
Definition at line 337 of file ui_atoms.c.
 {
     const char* s;
     unsigned char   ch;
     float   ax;
     float   ay;
     float   aw;
     float   ah;
     float   frow;
     float   fcol;
     float   fwidth;
     float   fheight;
     // draw the colored text
     trap_R_SetColor( color );
     // MDave: apply the new scaling
 #if 0
     ax = x * uis.scale + uis.bias;
     ay = y * uis.scale;
 #else
     ax = x * uis.scaleX;
     ay = y * uis.scaleY;
 #endif
     s = str;
     while ( *s )
     {
         ch = *s & 127;
         if ( ch == ' ' ) {
             // MDave: apply the new scaling
 #if 0
             ax += ((float)PROPB_SPACE_WIDTH + (float)PROPB_GAP_WIDTH)* uis.scale;
 #else
             ax += ((float)PROPB_SPACE_WIDTH + (float)PROPB_GAP_WIDTH)* uis.scaleX;
 #endif
         }
         else if ( ch >= 'A' && ch <= 'Z' ) {
             ch -= 'A';
             fcol = (float)propMapB[ch][0] / 256.0f;
             frow = (float)propMapB[ch][1] / 256.0f;
             fwidth = (float)propMapB[ch][2] / 256.0f;
             fheight = (float)PROPB_HEIGHT / 256.0f;
             // MDave: apply the new scaling
 #if 0
             aw = (float)propMapB[ch][2] * uis.scale;
             ah = (float)PROPB_HEIGHT * uis.scale;
 #else
             aw = (float)propMapB[ch][2] * uis.scaleX;
             ah = (float)PROPB_HEIGHT * uis.scaleY;
 #endif
             trap_R_DrawStretchPic( ax, ay, aw, ah, fcol, frow, fcol+fwidth, frow+fheight, uis.charsetPropB );
             // MDave: apply the new scaling
 #if 0
             ax += (aw + (float)PROPB_GAP_WIDTH * uis.scale);
 #else
             ax += (aw + (float)PROPB_GAP_WIDTH * uis.scaleX);
 #endif
         }
         s++;
     }
     trap_R_SetColor( NULL );
 }
References uiStatic_t::charsetPropB, NULL, PROPB_GAP_WIDTH, PROPB_HEIGHT, PROPB_SPACE_WIDTH, propMapB, uiStatic_t::scaleX, uiStatic_t::scaleY, trap_R_DrawStretchPic(), trap_R_SetColor(), and uis.
Referenced by UI_DrawBannerString().
UI_DrawChar()
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
Definition at line 790 of file ui_atoms.c.
 {
     char    buff[2];
     buff[0] = ch;
     buff[1] = '\0';
     UI_DrawString( x, y, buff, style, color );
 }
References UI_DrawString().
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MainMenu_DrawName(), MenuField_Draw(), MField_Draw(), RadioButton_Draw(), and SpinControl_Draw().
UI_DrawHandlePic()
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
Definition at line 998 of file ui_atoms.c.
{
     float   s0;
     float   s1;
     float   t0;
     float   t1;
     if( w < 0 ) {   // flip about vertical
         w  = -w;
         s0 = 1;
         s1 = 0;
     }
     else {
         s0 = 0;
         s1 = 1;
     }
     if( h < 0 ) {   // flip about horizontal
         h  = -h;
         t0 = 1;
         t1 = 0;
     }
     else {
         t0 = 0;
         t1 = 1;
     }
     UI_AdjustFrom640( &x, &y, &w, &h );
     trap_R_DrawStretchPic( x, y, w, h, s0, t0, s1, t1, hShader );
 }
References trap_R_DrawStretchPic(), and UI_AdjustFrom640().
Referenced by Bitmap_Draw(), Crosshair_Draw(), Main_MenuDraw(), Menu_Common(), Menu_Frame(), RadioButton_Draw(), Slider_Draw(), StartServer_LevelshotDraw(), and UI_Refresh().
UI_DrawNamedPic()
void UI_DrawNamedPic (float x, float y, float width, float height, const char * picname)
Definition at line 992 of file ui_atoms.c.
{
     qhandle_t   hShader;
     hShader = trap_R_RegisterShaderNoMip( picname );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
References trap_R_DrawStretchPic(), trap_R_RegisterShaderNoMip(), and UI_AdjustFrom640().
Referenced by ConfirmMenu_Draw(), and MessageMenu_Draw().
UI_DrawProportionalString()
void UI_DrawProportionalString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 555 of file ui_atoms.c.
{
     vec4_t  drawcolor;
     int     width;
     float   sizeScale;
     sizeScale = UI_ProportionalSizeScale( style );
     switch( style & UI_FORMATMASK ) {
         case UI_CENTER:
             width = UI_ProportionalStringWidth( str ) * sizeScale;
             x -= width / 2;
             break;
         case UI_RIGHT:
             width = UI_ProportionalStringWidth( str ) * sizeScale;
             x -= width;
             break;
         case UI_LEFT:
         default:
             break;
     }
     if ( style & UI_DROPSHADOW ) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = 0.7;
         UI_DrawProportionalString2( x+1, y+1, str, drawcolor, sizeScale, uis.charsetProp );
     }
     if ( style & UI_INVERSE ) {
         drawcolor[0] = color[0] * 0.7;
         drawcolor[1] = color[1] * 0.7;
         drawcolor[2] = color[2] * 0.7;
         drawcolor[3] = 0.7;
         UI_DrawProportionalString2( x, y, str, drawcolor, sizeScale, uis.charsetProp );
         return;
     }
     if ( style & UI_PULSE ) {
         /*drawcolor[0] = color[0] * 0.7;
         drawcolor[1] = color[1] * 0.7;
         drawcolor[2] = color[2] * 0.7;
         drawcolor[3] = 0.7;
         UI_DrawProportionalString2( x, y, str, color, sizeScale, uis.charsetProp );
         drawcolor[0] = color[0];
         drawcolor[1] = color[1];
         drawcolor[2] = color[2];
         drawcolor[3] = 0.7;
         UI_DrawProportionalString2( x, y, str, drawcolor, sizeScale, uis.charsetPropGlow );
         return;*/
     }
     UI_DrawProportionalString2( x, y, str, color, sizeScale, uis.charsetProp );
 }
References cg, cgs, uiStatic_t::charsetProp, cgMedia_t::charsetProp, cgMedia_t::charsetPropGlow, cgs_t::media, PULSE_DIVISOR, cg_t::time, UI_CENTER, UI_DrawProportionalString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_INVERSE, UI_LEFT, UI_ProportionalSizeScale(), UI_ProportionalStringWidth(), UI_PULSE, UI_RIGHT, and uis.
UI_DrawProportionalString2()
static void UI_DrawProportionalString2 (int x, int y, const char * str, vec4_t color, float sizeScale, qhandle_t charset) static
Definition at line 469 of file ui_atoms.c.
 {
     const char* s;
     unsigned char   ch;
     float   ax;
     float   ay;
     float   aw = 0;
     float   ah;
     float   frow;
     float   fcol;
     float   fwidth;
     float   fheight;
     // draw the colored text
     trap_R_SetColor( color );
     // JUHOX: apply the new scaling
 #if 0
     ax = x * uis.scale + uis.bias;
     ay = y * uis.scale;
 #else
     ax = x * uis.scaleX;
     ay = y * uis.scaleY;
 #endif
     s = str;
     while ( *s )
     {
         ch = *s & 127;
         if ( ch == ' ' ) {
             // JUHOX: apply the new scaling
 #if 0
             aw = (float)PROP_SPACE_WIDTH * uis.scale * sizeScale;
 #else
             aw = (float)PROP_SPACE_WIDTH * uis.scaleX * sizeScale;
 #endif
         }
         else if ( propMap[ch][2] != -1 ) {
             fcol = (float)propMap[ch][0] / 256.0f;
             frow = (float)propMap[ch][1] / 256.0f;
             fwidth = (float)propMap[ch][2] / 256.0f;
             fheight = (float)PROP_HEIGHT / 256.0f;
             // JUHOX: apply the new scaling
 #if 0
             aw = (float)propMap[ch][2] * uis.scale * sizeScale;
             ah = (float)PROP_HEIGHT * uis.scale * sizeScale;
 #else
             aw = (float)propMap[ch][2] * uis.scaleX * sizeScale;
             ah = (float)PROP_HEIGHT * uis.scaleY * sizeScale;
 #endif
             trap_R_DrawStretchPic( ax, ay, aw, ah, fcol, frow, fcol+fwidth, frow+fheight, charset );
         }
         // JUHOX: apply the new scaling
 #if 0
         ax += (aw + (float)PROP_GAP_WIDTH * uis.scale * sizeScale);
 #else
         ax += (aw + (float)PROP_GAP_WIDTH * uis.scaleX * sizeScale);
 #endif
         s++;
     }
     trap_R_SetColor( NULL );
 }
References NULL, PROP_GAP_WIDTH, PROP_HEIGHT, PROP_SPACE_WIDTH, propMap, uiStatic_t::scaleX, uiStatic_t::scaleY, trap_R_DrawStretchPic(), trap_R_SetColor(), and uis.
Referenced by UI_DrawProportionalString().
UI_DrawRect()
void UI_DrawRect (float x, float y, float width, float height, const float * color)
Definition at line 1051 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, 1, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x, y, 1, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x, y + height - 1, width, 1, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x + width - 1, y, 1, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_SetColor( NULL );
 }
References NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), UI_AdjustFrom640(), uis, and uiStatic_t::whiteShader.
Referenced by Menu_Draw(), and UI_DrawTextBox().
UI_DrawString()
void UI_DrawString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 707 of file ui_atoms.c.
 {
     int     len;
     int     charw;
     int     charh;
     vec4_t  newcolor;
     vec4_t  lowlight;
     float   *drawcolor;
     vec4_t  dropcolor;
     if( !str ) {
         return;
     }
     if ((style & UI_BLINK) && ((uis.realtime/BLINK_DIVISOR) & 1))
         return;
     if (style & UI_SMALLFONT)
     {
         charw = SMALLCHAR_WIDTH;
         charh = SMALLCHAR_HEIGHT;
     }
     else if (style & UI_TINYFONT)
     {
         charw = 6;
         charh = 12;
     }
     else if (style & UI_GIANTFONT)
     {
         charw = GIANTCHAR_WIDTH;
         charh = GIANTCHAR_HEIGHT;
     }
     else
     {
         charw = BIGCHAR_WIDTH;
         charh = BIGCHAR_HEIGHT;
     }
     drawcolor = color;
     switch (style & UI_FORMATMASK)
     {
         case UI_CENTER:
             // center justify at x
             // JUHOX: use UI_DrawStrlen() instead of strlen
 #if 0
             len = strlen(str);
 #else
             len = UI_DrawStrlen(str);
 #endif
             x   = x - len*(charw*0.7)/2;
             break;
         case UI_RIGHT:
             // right justify at x
             // JUHOX: use UI_DrawStrlen() instead of strlen
 #if 0
             len = strlen(str);
 #else
             len = UI_DrawStrlen(str);
 #endif
             x   = x - len*(charw*0.7);
             break;
         default:
             // left justify at x
             break;
     }
     if ( style & UI_DROPSHADOW )
     {
         dropcolor[0] = dropcolor[1] = dropcolor[2] = 0;
         dropcolor[3] = 0.7;
         UI_DrawString2(x+1,y+1,str,dropcolor,charw,charh);
     }
     UI_DrawString2(x,y,str,drawcolor,charw,charh);
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, BLINK_DIVISOR, GIANTCHAR_HEIGHT, GIANTCHAR_WIDTH, uiStatic_t::realtime, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, UI_BLINK, UI_CENTER, UI_DrawString2(), UI_DrawStrlen(), UI_DROPSHADOW, UI_FORMATMASK, UI_GIANTFONT, UI_RIGHT, UI_SMALLFONT, UI_TINYFONT, and uis.
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), MField_Draw(), RadioButton_Draw(), ScrollList_Draw(), ServerInfo_MenuDraw(), Slider_Draw(), SpinControl_Draw(), StartServer_LevelshotDraw(), Text_Draw(), UI_DrawChar(), and UI_Refresh().
UI_DrawString2()
static void UI_DrawString2 (int x, int y, const char * str, vec4_t color, int charw, int charh) static
Definition at line 616 of file ui_atoms.c.
 {
     const char* s;
     char    ch;
     int forceColor = qfalse; //APSFIXME;
     vec4_t  tempcolor;
     float   ax;
     float   ay;
     float   aw;
     float   ah;
     float   frow;
     float   fcol;
     if (y < -charh)
         // offscreen
         return;
     // draw the colored text
     trap_R_SetColor( color );
     // JUHOX: apply the new scaling
 #if 0
     ax = x * uis.scale + uis.bias;
     ay = y * uis.scale;
     aw = charw * uis.scale;
     ah = charh * uis.scale;
 #else
     ax = x * uis.scaleX;
     ay = y * uis.scaleY;
     aw = charw * uis.scaleX;
     ah = charh * uis.scaleY;
 #endif
     s = str;
     while ( *s )
     {
         if ( Q_IsColorString( s ) )
         {
             if ( !forceColor )
             {
                 memcpy( tempcolor, g_color_table[ColorIndex(s[1])], sizeof( tempcolor ) );
                 tempcolor[3] = 0.7;
                 trap_R_SetColor( tempcolor );
             }
             s += 2;
             continue;
         }
         ch = *s & 255;
         if (ch != ' ')
         {
             frow = (ch>>4)*0.0625;
             fcol = (ch&15)*0.0625;
             trap_R_DrawStretchPic( ax, ay, aw, ah, fcol, frow, fcol + 0.0625, frow + 0.0625, uis.charset );
         }
         ax += (charw*0.7) * uis.scaleX;
         s++;
     }
     trap_R_SetColor( NULL );
 }
References uiStatic_t::charset, ColorIndex, g_color_table, NULL, Q_IsColorString, qfalse, uiStatic_t::scaleX, uiStatic_t::scaleY, trap_R_DrawStretchPic(), trap_R_SetColor(), and uis.
Referenced by UI_DrawString().
UI_DrawStrlen()
int UI_DrawStrlen (const char * str)
Definition at line 686 of file ui_atoms.c.
{
     const char *s = str;
     int count = 0;
     while (*s) {
         if (Q_IsColorString(s)) {
             s += 2;
         } else {
             count++;
             s++;
         }
     }
     return count;
 }
References Q_IsColorString.
Referenced by UI_DrawString().
UI_DrawTextBox()
void UI_DrawTextBox (int x, int y, int width, int lines)
Definition at line 1281 of file ui_atoms.c.
 {
     UI_FillRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorBlack );
     UI_DrawRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorWhite );
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, colorBlack, colorWhite, UI_DrawRect(), and UI_FillRect().
UI_FillRect()
void UI_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 1035 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_SetColor( NULL );
 }
References NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), UI_AdjustFrom640(), uis, and uiStatic_t::whiteShader.
Referenced by Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), ScrollList_Draw(), StartServer_LevelshotDraw(), UI_DrawBackPic(), and UI_DrawTextBox().
UI_ForceMenuOff()
void UI_ForceMenuOff (void)
Definition at line 151 of file ui_atoms.c.
 {
     uis.menusp     = 0;
     uis.activemenu = NULL;
     trap_Key_SetCatcher( trap_Key_GetCatcher() & ~KEYCATCH_UI );
     trap_Key_ClearStates();
     trap_Cvar_Set( "cl_paused", "0" );
 }
References uiStatic_t::activemenu, KEYCATCH_UI, uiStatic_t::menusp, NULL, trap_Cvar_Set(), trap_Key_ClearStates(), trap_Key_GetCatcher(), trap_Key_SetCatcher(), and uis.
Referenced by SystemSettings_Event(), TeamMain_MenuEvent(), UI_PopMenu(), and UI_SetActiveMenu().
UI_Init()
void UI_Init (void)
Definition at line 969 of file ui_atoms.c.
                      {
     UI_RegisterCvars();
     UI_InitGameinfo();
     trap_GetGlconfig( &uis.glconfig );
     uis.scaleX = uis.glconfig.vidWidth / 640.0;
     uis.scaleY = uis.glconfig.vidHeight / 480.0;
     Menu_Cache();
     uis.activemenu = NULL;
     uis.menusp = 0;
 }
References uiStatic_t::activemenu, uiStatic_t::glconfig, Menu_Cache(), uiStatic_t::menusp, NULL, uiStatic_t::scaleX, uiStatic_t::scaleY, trap_GetGlconfig(), UI_InitGameinfo(), UI_RegisterCvars(), uis, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by vmMain().
UI_IsFullscreen()
qboolean UI_IsFullscreen (void)
Definition at line 800 of file ui_atoms.c.
{
     if ( uis.activemenu && ( trap_Key_GetCatcher() & KEYCATCH_UI ) ) {
         return uis.activemenu->fullscreen;
     }
     return qfalse;
 }
References uiStatic_t::activemenu, KEYCATCH_UI, qfalse, trap_Key_GetCatcher(), and uis.
Referenced by vmMain().
UI_KeyEvent()
void UI_KeyEvent (int key, int down)
Definition at line 834 of file ui_atoms.c.
{
     sfxHandle_t     s;
     if (!uis.activemenu) {
         return;
     }
     if (!down) {
         return;
     }
     if (uis.activemenu->key)
         s = uis.activemenu->key( key );
     else
         s = Menu_DefaultKey( uis.activemenu, key );
     if ((s > 0) && (s != menu_null_sound))
         trap_S_StartLocalSound( s, CHAN_LOCAL_SOUND );
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, Menu_DefaultKey(), menu_null_sound, trap_S_StartLocalSound(), and uis.
Referenced by vmMain().
UI_LerpColor()
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
Definition at line 166 of file ui_atoms.c.
 {
     int i;
     // lerp and clamp each component
     for (i=0; i<4; i++)
     {
         c[i] = a[i] + t*(b[i]-a[i]);
         if (c[i] < 0)
             c[i] = 0;
         else if (c[i] > 1.0)
             c[i] = 1.0;
     }
 }
UI_MenuLogo()
void UI_MenuLogo (void)
Definition at line 1154 of file ui_atoms.c.
{
     refdef_t        refdef;
     refEntity_t     ent;
     vec3_t          origin;
     vec3_t          angles;
     float           adjust;
     float           x, y, w, h;
     float           xx;
     vec3_t          mins = {-128, -128, -128};
     vec3_t          maxs = {128, 128, 128};
     float           len;
     // setup the refdef
     memset( &refdef, 0, sizeof( refdef ) );
     refdef.rdflags = RDF_NOWORLDMODEL;
     AxisClear( refdef.viewaxis );
     x = -19;
     y = -28;
     w = 205;
     h = 153;
     UI_AdjustFrom640( &x, &y, &w, &h );
     refdef.x = x;
     refdef.y = y;
     refdef.width = w;
     refdef.height = h;
     //adjust = 1.0f * sin( (float)uis.realtime / 5000 );
     refdef.fov_x = (int)((float)refdef.width / 640.0f * 35.0f);
     xx = refdef.width / tan( refdef.fov_x / 360 * M_PI );
     refdef.fov_y = atan2( refdef.height, xx );
     refdef.fov_y *= ( 360 / M_PI );
     /*
     refdef.fov_x = 20 + adjust;
     refdef.fov_y = 15 + adjust;
     */
     refdef.time = uis.realtime;
     // calculate distance so the scene fills the box
     len = 0.5 * ( maxs[2] - mins[2] );
     origin[0] = len / tan( DEG2RAD(refdef.fov_x) * 0.5 );
     origin[1] = 0.5 * ( mins[1] + maxs[1] );
     origin[2] = -0.5 * ( mins[2] + maxs[2] );
 /*
     origin[0] = 640; //z depth
     origin[1] = 0; //x depth
     origin[2] = 0; //y depth
 */
     trap_R_ClearScene();
     // add the model
     memset( &ent, 0, sizeof(ent) );
     adjust = -2.5f * sin( (float)uis.realtime / 5000 );
     VectorSet( angles, 0, 180 + adjust, 0 );
     AnglesToAxis( angles, ent.axis );
     ent.hModel = uis.logoModel;
     VectorCopy( origin, ent.origin );
     VectorCopy( origin, ent.lightingOrigin );
     ent.renderfx = RF_LIGHTING_ORIGIN | RF_NOSHADOW;
     VectorCopy( ent.origin, ent.oldorigin );
     trap_R_AddRefEntityToScene( &ent );
     trap_R_RenderScene( &refdef );
 }
References angles, AnglesToAxis(), refEntity_t::axis, AxisClear(), DEG2RAD, refdef_t::fov_x, refdef_t::fov_y, refdef_t::height, refEntity_t::hModel, int(), refEntity_t::lightingOrigin, uiStatic_t::logoModel, M_PI, refEntity_t::oldorigin, refEntity_t::origin, RDF_NOWORLDMODEL, refdef_t::rdflags, uiStatic_t::realtime, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, RF_NOSHADOW, refdef_t::time, trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RenderScene(), UI_AdjustFrom640(), uis, VectorCopy, VectorSet, refdef_t::viewaxis, refdef_t::width, refdef_t::x, xx, and refdef_t::y.
Referenced by Menu_Common().
UI_MenuScene()
void UI_MenuScene (void)
Definition at line 1077 of file ui_atoms.c.
{
     refdef_t        refdef;
     refEntity_t     ent;
     vec3_t          origin;
     vec3_t          angles;
     float           adjust;
     float           x, y, w, h;
     float           xx;
     vec3_t          mins = {-128, -128, -128};
     vec3_t          maxs = {128, 128, 128};
     float           len;
     // setup the refdef
     memset( &refdef, 0, sizeof( refdef ) );
     refdef.rdflags = RDF_NOWORLDMODEL;
     AxisClear( refdef.viewaxis );
     x = 0;
     y = 0;
     w = 640;
     h = 480;
     UI_AdjustFrom640( &x, &y, &w, &h );
     refdef.x = x;
     refdef.y = y;
     refdef.width = w;
     refdef.height = h;
     //adjust = 1.0f * sin( (float)uis.realtime / 5000 );
     refdef.fov_x = (int)((float)refdef.width / 640.0f * 35.0f);
     xx = refdef.width / tan( refdef.fov_x / 360 * M_PI );
     refdef.fov_y = atan2( refdef.height, xx );
     refdef.fov_y *= ( 360 / M_PI );
     /*
     refdef.fov_x = 20 + adjust;
     refdef.fov_y = 15 + adjust;
     */
     refdef.time = uis.realtime;
     // calculate distance so the scene fills the box
     len = 0.5 * ( maxs[2] - mins[2] );
     origin[0] = len / tan( DEG2RAD(refdef.fov_x) * 0.5 );
     origin[1] = 0.5 * ( mins[1] + maxs[1] );
     origin[2] = -0.5 * ( mins[2] + maxs[2] );
 /*
     origin[0] = 640; //z depth
     origin[1] = 0; //x depth
     origin[2] = 0; //y depth
 */
     trap_R_ClearScene();
     // add the model
     memset( &ent, 0, sizeof(ent) );
     adjust = 2.5f * sin( (float)uis.realtime / 5000 );
     VectorSet( angles, 0, 180 + adjust, 0 );
     AnglesToAxis( angles, ent.axis );
     ent.hModel = uis.sceneModel;
     VectorCopy( origin, ent.origin );
     VectorCopy( origin, ent.lightingOrigin );
     ent.renderfx = RF_LIGHTING_ORIGIN | RF_NOSHADOW;
     VectorCopy( ent.origin, ent.oldorigin );
     trap_R_AddRefEntityToScene( &ent );
     trap_R_RenderScene( &refdef );
 }
References angles, AnglesToAxis(), refEntity_t::axis, AxisClear(), DEG2RAD, refdef_t::fov_x, refdef_t::fov_y, refdef_t::height, refEntity_t::hModel, int(), refEntity_t::lightingOrigin, M_PI, refEntity_t::oldorigin, refEntity_t::origin, RDF_NOWORLDMODEL, refdef_t::rdflags, uiStatic_t::realtime, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, RF_NOSHADOW, uiStatic_t::sceneModel, refdef_t::time, trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RenderScene(), UI_AdjustFrom640(), uis, VectorCopy, VectorSet, refdef_t::viewaxis, refdef_t::width, refdef_t::x, xx, and refdef_t::y.
Referenced by UI_DrawConnectScreen(), and UI_Refresh().
UI_MouseEvent()
void UI_MouseEvent (int dx, int dy)
Definition at line 859 of file ui_atoms.c.
 {
     int             i;
     menucommon_s*   m;
     if (!uis.activemenu)
         return;
     // update mouse screen position
     uis.cursorx += dx;
     if (uis.cursorx < 0)
         uis.cursorx = 0;
     else if (uis.cursorx > SCREEN_WIDTH)
         uis.cursorx = SCREEN_WIDTH;
     uis.cursory += dy;
     if (uis.cursory < 0)
         uis.cursory = 0;
     else if (uis.cursory > SCREEN_HEIGHT)
         uis.cursory = SCREEN_HEIGHT;
     // region test the active menu items
     for (i=0; i<uis.activemenu->nitems; i++)
     {
         m = (menucommon_s*)uis.activemenu->items[i];
         if (m->flags & (QMF_GRAYED|QMF_INACTIVE))
             continue;
         if ((uis.cursorx < m->left) ||
             (uis.cursorx > m->right) ||
             (uis.cursory < m->top) ||
             (uis.cursory > m->bottom))
         {
             // cursor out of item bounds
             continue;
         }
         // set focus to item at cursor
         if (uis.activemenu->cursor != i)
         {
             Menu_SetCursor( uis.activemenu, i );
             ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor_prev]))->flags &= ~QMF_HASMOUSEFOCUS;
             if ( !(((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags & QMF_SILENT ) ) {
                 trap_S_StartLocalSound( menu_move_sound, CHAN_LOCAL_SOUND );
             }
         }
         ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags |= QMF_HASMOUSEFOCUS;
         return;
     }
     if (uis.activemenu->nitems > 0) {
         // out of any region
         ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags &= ~QMF_HASMOUSEFOCUS;
     }
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, uiStatic_t::cursorx, uiStatic_t::cursory, m, menu_move_sound, Menu_SetCursor(), QMF_GRAYED, QMF_HASMOUSEFOCUS, QMF_INACTIVE, QMF_SILENT, SCREEN_HEIGHT, SCREEN_WIDTH, trap_S_StartLocalSound(), and uis.
Referenced by vmMain().
UI_PopMenu()
void UI_PopMenu (void)
Definition at line 133 of file ui_atoms.c.
 {
     trap_S_StartLocalSound( menu_out_sound, CHAN_LOCAL_SOUND );
     uis.menusp--;
     if (uis.menusp < 0)
         trap_Error ("UI_PopMenu: menu stack underflow");
     if (uis.menusp) {
         uis.activemenu = uis.stack[uis.menusp-1];
         uis.firstdraw = qtrue;
     }
     else {
         UI_ForceMenuOff ();
     }
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, uiStatic_t::firstdraw, menu_out_sound, uiStatic_t::menusp, qtrue, uiStatic_t::stack, trap_Error(), trap_S_StartLocalSound(), UI_ForceMenuOff(), and uis.
Referenced by ArenaServers_Event(), Camera_MenuEvent(), ConfirmMenu_Event(), Controls_MenuEvent(), InGame_QuitAction(), InGame_RestartAction(), Menu_DefaultKey(), Music_MenuEvent(), Options_Event(), PlayerModel_MenuEvent(), Preferences_Event(), ServerInfo_Event(), StartServer_MenuEvent(), and SystemSettings_Event().
UI_ProportionalSizeScale()
float UI_ProportionalSizeScale (int style)
Definition at line 538 of file ui_atoms.c.
{
     if(  style & UI_SMALLFONT ) {
         return PROP_SMALL_SIZE_SCALE;
     }
     if(  style & UI_TINYFONT ) {
         return 0.6;
     }
     return 1.00;
 }
References PROP_SMALL_SIZE_SCALE, UI_SMALLFONT, and UI_TINYFONT.
Referenced by UI_DrawProportionalString().
UI_ProportionalStringWidth()
int UI_ProportionalStringWidth (const char * str)
Definition at line 447 of file ui_atoms.c.
{
     const char *    s;
     int             ch;
     int             charWidth;
     int             width;
     s = str;
     width = 0;
     while ( *s ) {
         ch = *s & 127;
         charWidth = propMap[ch][2];
         if ( charWidth != -1 ) {
             width += charWidth;
             width += PROP_GAP_WIDTH;
         }
         s++;
     }
     width -= PROP_GAP_WIDTH;
     return width;
 }
References PROP_GAP_WIDTH, and propMap.
Referenced by UI_DrawProportionalString().
UI_PushMenu()
void UI_PushMenu (menuframework_s * menu)
Definition at line 81 of file ui_atoms.c.
 {
     int             i;
     menucommon_s*   item;
     // avoid stacking menus invoked by hotkeys
     for (i=0 ; i<uis.menusp ; i++)
     {
         if (uis.stack[i] == menu){
             uis.menusp = i;
             break;
         }
     }
     if (i == uis.menusp)
     {
         if (uis.menusp >= MAX_MENUDEPTH)
             trap_Error("UI_PushMenu: menu stack overflow");
         uis.stack[uis.menusp++] = menu;
     }
     uis.activemenu = menu;
     // default cursor position
     menu->cursor      = 0;
     menu->cursor_prev = 0;
     m_entersound = qtrue;
     trap_Key_SetCatcher( KEYCATCH_UI );
     // force first available item to have focus
     for (i=0; i<menu->nitems; i++)
     {
         item = (menucommon_s *)menu->items[i];
         if (!(item->flags & (QMF_GRAYED|QMF_MOUSEONLY|QMF_INACTIVE)))
         {
             menu->cursor_prev = -1;
             Menu_SetCursor( menu, i );
             break;
         }
     }
     uis.firstdraw = qtrue;
 }
References uiStatic_t::activemenu, uiStatic_t::firstdraw, menucommon_s::flags, KEYCATCH_UI, m_entersound, MAX_MENUDEPTH, Menu_SetCursor(), uiStatic_t::menusp, QMF_GRAYED, QMF_INACTIVE, QMF_MOUSEONLY, qtrue, uiStatic_t::stack, trap_Error(), trap_Key_SetCatcher(), and uis.
Referenced by UI_ArenaServersMenu(), UI_CameraMenu(), UI_ConfirmMenu_Style(), UI_ControlsMenu(), UI_CreditMenu(), UI_InGameMenu(), UI_MainMenu(), UI_Message(), UI_MusicMenu(), UI_PlayerModelMenu(), UI_PreferencesMenu(), UI_ServerInfoMenu(), UI_StartServerMenu(), UI_SystemConfigMenu(), UI_SystemSettingsMenu(), and UI_TeamMainMenu().
UI_Refresh()
void UI_Refresh (int realtime)
Definition at line 1251 of file ui_atoms.c.
{
     uis.frametime = realtime - uis.realtime;
     uis.realtime  = realtime;
     if(!( trap_Key_GetCatcher() & KEYCATCH_UI)){
         return;
     }
     UI_UpdateCvars();
     if(uis.activemenu){
         if (uis.activemenu->fullscreen){
             if(!uis.hideBack){UI_DrawHandlePic( 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, uis.menuBackShader);}
             if(!uis.hideEarth){UI_MenuScene();}
             if(uis.showFrame){Menu_Frame();}
             if(uis.showSide){Menu_Side();}
             Menu_Common(uis.menuamount);
         }
         if(uis.activemenu->draw){uis.activemenu->draw();}
         else{Menu_Draw(uis.activemenu);}
     }
     UI_SetColor(NULL);
     UI_DrawHandlePic( uis.cursorx-16, uis.cursory-16, 32, 32, uis.cursor);
     if (uis.debug){
         UI_DrawString( 0, 0, va("(%d,%d)",uis.cursorx,uis.cursory), UI_LEFT|UI_SMALLFONT|UI_DROPSHADOW, colorRed );
     }
     if (m_entersound){
         trap_S_StartLocalSound( menu_in_sound, CHAN_LOCAL_SOUND );
         m_entersound = qfalse;
     }
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, colorRed, uiStatic_t::cursor, uiStatic_t::cursorx, uiStatic_t::cursory, uiStatic_t::debug, uiStatic_t::frametime, uiStatic_t::hideBack, uiStatic_t::hideEarth, KEYCATCH_UI, m_entersound, Menu_Common(), Menu_Draw(), Menu_Frame(), menu_in_sound, Menu_Side(), uiStatic_t::menuamount, uiStatic_t::menuBackShader, NULL, qfalse, uiStatic_t::realtime, SCREEN_HEIGHT, SCREEN_WIDTH, uiStatic_t::showFrame, uiStatic_t::showSide, trap_Key_GetCatcher(), trap_S_StartLocalSound(), UI_DrawHandlePic(), UI_DrawString(), UI_DROPSHADOW, UI_LEFT, UI_MenuScene(), UI_SetColor(), UI_SMALLFONT, UI_UpdateCvars(), uis, and va().
Referenced by vmMain().
UI_SetActiveMenu()
void UI_SetActiveMenu (uiMenuCommand_t menu)
Definition at line 808 of file ui_atoms.c.
{
     //Menu_Cache();
     switch(menu){
         case UIMENU_NONE:
             UI_ForceMenuOff();
             return;
         case UIMENU_MAIN:
             UI_MainMenu();
             return;
         case UIMENU_INGAME:
             trap_Cvar_Set("cl_paused","1");
             UI_InGameMenu();
             return;
         case UIMENU_TEAM:
         case UIMENU_POSTGAME:
         default:
           Com_Printf("UI_SetActiveMenu: bad enum %d\n", menu );
           break;
     }
 }
References Com_Printf(), trap_Cvar_Set(), UI_ForceMenuOff(), UI_InGameMenu(), UI_MainMenu(), UIMENU_INGAME, UIMENU_MAIN, UIMENU_NONE, UIMENU_POSTGAME, and UIMENU_TEAM.
Referenced by vmMain().
UI_SetColor()
void UI_SetColor (const float * rgba)
Definition at line 1064 of file ui_atoms.c.
{
     trap_R_SetColor( rgba );
 }
References trap_R_SetColor().
Referenced by Slider_Draw(), UI_DrawConnectScreen(), and UI_Refresh().
UI_Shutdown()
void UI_Shutdown (void)
Definition at line 962 of file ui_atoms.c.
 {}
Referenced by vmMain().
UI_StartDemoLoop()
void UI_StartDemoLoop (void)
Definition at line 72 of file ui_atoms.c.
{
     trap_Cmd_ExecuteText( EXEC_APPEND, "d1\n" );
 }
References EXEC_APPEND, and trap_Cmd_ExecuteText().
UI_UpdateScreen()
void UI_UpdateScreen (void)
Definition at line 1068 of file ui_atoms.c.
{
     trap_UpdateScreen();
 }
References trap_UpdateScreen().
Variable Documentation
m_entersound
qboolean m_entersound
Definition at line 31 of file ui_atoms.c.
Referenced by UI_PushMenu(), and UI_Refresh().
propMap
int propMap[128][3] static
Definition at line 186 of file ui_atoms.c.
Referenced by UI_DrawProportionalString2(), and UI_ProportionalStringWidth().
propMapB
int propMapB[26][3] static
Definition at line 296 of file ui_atoms.c.
Referenced by UI_DrawBannerString(), and UI_DrawBannerString2().
uis
uiStatic_t uis
Definition at line 30 of file ui_atoms.c.
Referenced by ArenaServers_DoRefresh(), ArenaServers_MenuDraw(), ArenaServers_MenuInit(), ArenaServers_StartRefresh(), Bitmap_Draw(), ConfirmMenu_Draw(), Controls_DrawPlayer(), Main_MenuDraw(), MainMenu_DrawPlayer(), Menu_Cache(), Menu_Common(), Menu_DefaultKey(), Menu_Draw(), Menu_Frame(), PlayerModel_DrawPlayer(), RadioButton_Draw(), ScrollList_Key(), Slider_Key(), SystemSettings_MenuInit(), UI_AdjustFrom640(), UI_ConfirmMenu_Style(), UI_ControlsMenu(), UI_CreditMenu(), UI_CursorInRect(), UI_DisplayDownloadInfo(), UI_DrawBackPic(), UI_DrawBannerString2(), UI_DrawProportionalString(), UI_DrawProportionalString2(), UI_DrawRect(), UI_DrawString(), UI_DrawString2(), UI_FillRect(), UI_ForceMenuOff(), UI_InGameMenu(), UI_Init(), UI_InitGameinfo(), UI_IsFullscreen(), UI_KeyEvent(), UI_MainMenu(), UI_MenuLogo(), UI_MenuScene(), UI_MouseEvent(), UI_PlayerAnimation(), UI_PlayerModelMenu(), UI_PopMenu(), UI_PreferencesMenu(), UI_PushMenu(), UI_Refresh(), UI_ServerInfoMenu(), UI_StartServerMenu(), UI_SwingAngles(), UI_SystemConfigMenu(), and UI_SystemSettingsMenu().