ZEQ2-Lite: Bitmap Class Reference
Bitmap Class Reference
#include <gdiplusheaders.h>
Public Member Functions
Bitmap (const BITMAPINFO *gdiBitmapInfo, VOID *gdiBitmapData)
Bitmap (const WCHAR *filename, BOOL useEmbeddedColorManagement=FALSE)
Bitmap (HBITMAP hbm, HPALETTE hpal)
Bitmap (HICON hicon)
Bitmap (HINSTANCE hInstance, const WCHAR *bitmapName)
Bitmap (IDirectDrawSurface7 *surface)
Bitmap (INT width, INT height, Graphics *target)
Bitmap (INT width, INT height, INT stride, PixelFormat format, BYTE *scan0)
Bitmap (INT width, INT height, PixelFormat format=PixelFormat32bppARGB)
Bitmap (IStream *stream, BOOL useEmbeddedColorManagement=FALSE)
virtual ~Bitmap ()
Status ApplyEffect (Effect *effect, RECT *ROI)
virtual Bitmap * Clone () const
Bitmap * Clone (const Rect &rect, PixelFormat format) const
Bitmap * Clone (const RectF &rect, PixelFormat format) const
Bitmap * Clone (INT x, INT y, INT width, INT height, PixelFormat format) const
Bitmap * Clone (REAL x, REAL y, REAL width, REAL height, PixelFormat format) const
Status ConvertFormat (PixelFormat format, DitherType ditherType, PaletteType paletteType, ColorPalette *palette, REAL alphaThresholdPercent)
Status FindFirstItem (ImageItemData *item)
Status FindNextItem (ImageItemData *item)
Status GetAllPropertyItems (UINT totalBufferSize, UINT numProperties, PropertyItem *allItems)
Status GetBounds (RectF *srcRect, Unit *srcUnit)
Status GetEncoderParameterList (const CLSID *clsidEncoder, UINT size, EncoderParameters *buffer)
UINT GetEncoderParameterListSize (const CLSID *clsidEncoder)
UINT GetFlags ()
UINT GetFrameCount (const GUID *dimensionID)
UINT GetFrameDimensionsCount ()
Status GetFrameDimensionsList (GUID *dimensionIDs, UINT count)
Status GetHBITMAP (const Color &colorBackground, HBITMAP *hbmReturn) const
UINT GetHeight ()
Status GetHICON (HICON *icon) const
Status GetHistogram (HistogramFormat format, UINT numberOfEntries, UINT *channel0, UINT *channel1, UINT *channel2, UINT *channel3) const
Status GetHistogramSize (HistogramFormat format, UINT *numberOfEntries) const
REAL GetHorizontalResolution ()
Status GetItemData (ImageItemData *item)
Status GetLastStatus () const
Status GetPalette (ColorPalette *palette, INT size)
INT GetPaletteSize ()
Status GetPhysicalDimension (SizeF *size)
Status GetPixel (INT x, INT y, Color *color) const
PixelFormat GetPixelFormat ()
UINT GetPropertyCount ()
Status GetPropertyIdList (UINT numOfProperty, PROPID *list)
Status GetPropertyItem (PROPID propId, UINT propSize, PropertyItem *buffer)
UINT GetPropertyItemSize (PROPID propId)
Status GetPropertySize (UINT *totalBufferSize, UINT *numProperties)
Status GetRawFormat (GUID *format)
Image * GetThumbnailImage (UINT thumbWidth, UINT thumbHeight, GetThumbnailImageAbort callback, VOID *callbackData)
ImageType GetType () const
REAL GetVerticalResolution ()
UINT GetWidth ()
Status LockBits (const Rect *rect, UINT flags, PixelFormat format, BitmapData *lockedBitmapData)
Status RemovePropertyItem (PROPID propId)
Status RotateFlip (RotateFlipType rotateFlipType)
Status Save (const WCHAR *filename, const CLSID *clsidEncoder, const EncoderParameters *encoderParams)
Status Save (IStream *stream, const CLSID *clsidEncoder, const EncoderParameters *encoderParams)
Status SaveAdd (const EncoderParameters *encoderParams)
Status SaveAdd (Image *newImage, const EncoderParameters *encoderParams)
Status SelectActiveFrame (const GUID *dimensionID, UINT frameIndex)
Status SetAbort (GdiplusAbort *pIAbort)
Status SetPalette (const ColorPalette *palette)
Status SetPixel (INT x, INT y, const Color &color)
Status SetPropertyItem (const PropertyItem *item)
Status SetResolution (REAL xdpi, REAL ydpi)
Status UnlockBits (BitmapData *lcokedBitmapData)
Static Public Member Functions
static Status ApplyEffect (Bitmap **inputs, INT numInputs, Effect *effect, RECT *ROI, RECT *outputRect, Bitmap **output)
static Bitmap * FromBITMAPINFO (const BITMAPINFO *gdiBitmapInfo, VOID *gdiBitmapData)
static Bitmap * FromDirectDrawSurface7 (IDirectDrawSurface7 *surface)
static Bitmap * FromFile (const WCHAR *filename, BOOL useEmbeddedColorManagement=FALSE)
static Bitmap * FromHBITMAP (HBITMAP hbm, HPALETTE hpal)
static Bitmap * FromHICON (HICON icon)
static Bitmap * FromResource (HINSTANCE hInstance, const WCHAR *bitmapName)
static Bitmap * FromStream (IStream *stream, BOOL useEmbeddedColorManagement=FALSE)
static Status InitializePalette (ColorPalette *palette, PaletteType paletteType, INT optimalColors, BOOL useTransparentColor, Bitmap *bitmap)
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Bitmap (const Bitmap &)
Bitmap (GpImage *image, Status status)
Bitmap & operator= (const Bitmap &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpImage * nativeImage
Detailed Description
Definition at line 156 of file gdiplusheaders.h.
Constructor & Destructor Documentation
Bitmap() [1/12]
__inline__ Bitmap::Bitmap (const BITMAPINFO * gdiBitmapInfo, VOID * gdiBitmapData)
Definition at line 407 of file gdiplusimpl.h.
                                                                              :
     Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     lastStatus = DllExports::GdipCreateBitmapFromGdiDib(
             gdiBitmapInfo, gdiBitmapData, &nativeBitmap);
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromGdiDib(), Image::lastStatus, Image::nativeImage, and NULL.
Bitmap() [2/12]
__inline__ Bitmap::Bitmap (IDirectDrawSurface7 * surface)
Definition at line 416 of file gdiplusimpl.h.
                                                      : Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     lastStatus = DllExports::GdipCreateBitmapFromDirectDrawSurface(
             surface, &nativeBitmap);
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromDirectDrawSurface(), Image::lastStatus, Image::nativeImage, and NULL.
Bitmap() [3/12]
__inline__ Bitmap::Bitmap (const WCHAR * filename, BOOL useEmbeddedColorManagement = FALSE)
Definition at line 424 of file gdiplusimpl.h.
                                         : Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     if (useEmbeddedColorManagement) {
         lastStatus = DllExports::GdipCreateBitmapFromFileICM(
                 filename, &nativeBitmap);
     } else {
         lastStatus = DllExports::GdipCreateBitmapFromFile(
                 filename, &nativeBitmap);
     }
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromFile(), GdipCreateBitmapFromFileICM(), Image::lastStatus, Image::nativeImage, and NULL.
Bitmap() [4/12]
__inline__ Bitmap::Bitmap (HBITMAP hbm, HPALETTE hpal)
Definition at line 438 of file gdiplusimpl.h.
                                                    :
     Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     lastStatus = DllExports::GdipCreateBitmapFromHBITMAP(
             hbm, hpal, &nativeBitmap);
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromHBITMAP(), Image::lastStatus, Image::nativeImage, and NULL.
Bitmap() [5/12]
__inline__ Bitmap::Bitmap (HICON hicon)
Definition at line 447 of file gdiplusimpl.h.
                                     :
     Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     lastStatus = DllExports::GdipCreateBitmapFromHICON(hicon, &nativeBitmap);
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromHICON(), Image::lastStatus, Image::nativeImage, and NULL.
Bitmap() [6/12]
__inline__ Bitmap::Bitmap (HINSTANCE hInstance, const WCHAR * bitmapName)
Definition at line 455 of file gdiplusimpl.h.
                                                                      :
     Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     lastStatus = DllExports::GdipCreateBitmapFromResource(
             hInstance, bitmapName, &nativeBitmap);
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromResource(), Image::lastStatus, Image::nativeImage, and NULL.
Bitmap() [7/12]
__inline__ Bitmap::Bitmap (IStream * stream, BOOL useEmbeddedColorManagement = FALSE)
Definition at line 464 of file gdiplusimpl.h.
                                                                          :
     Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     if (useEmbeddedColorManagement) {
         lastStatus = DllExports::GdipCreateBitmapFromStreamICM(
                 stream, &nativeBitmap);
     } else {
         lastStatus = DllExports::GdipCreateBitmapFromStream(
                 stream, &nativeBitmap);
     }
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromStream(), GdipCreateBitmapFromStreamICM(), Image::lastStatus, Image::nativeImage, and NULL.
Bitmap() [8/12]
__inline__ Bitmap::Bitmap (INT width, INT height, Graphics * target)
Definition at line 478 of file gdiplusimpl.h.
                                                                 :
     Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     lastStatus = DllExports::GdipCreateBitmapFromGraphics(
             width, height, target ? target->nativeGraphics : NULL,
             &nativeBitmap);
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromGraphics(), Image::lastStatus, Graphics::nativeGraphics, Image::nativeImage, and NULL.
Bitmap() [9/12]
__inline__ Bitmap::Bitmap (INT width, INT height, PixelFormat format = PixelFormat32bppARGB)
Definition at line 488 of file gdiplusimpl.h.
                                                                   :
     Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     lastStatus = DllExports::GdipCreateBitmapFromScan0(
             width, height, 0, format, NULL, &nativeBitmap);
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromScan0(), Image::lastStatus, Image::nativeImage, and NULL.
Bitmap() [10/12]
__inline__ Bitmap::Bitmap (INT width, INT height, INT stride, PixelFormat format, BYTE * scan0)
Definition at line 497 of file gdiplusimpl.h.
                                         : Image(NULL, Ok)
 {
     GpBitmap *nativeBitmap = NULL;
     lastStatus = DllExports::GdipCreateBitmapFromScan0(
             width, height, stride, format, scan0, &nativeBitmap);
     nativeImage = nativeBitmap;
 }
References GdipCreateBitmapFromScan0(), Image::lastStatus, Image::nativeImage, and NULL.
~Bitmap()
virtual Bitmap::~Bitmap () inline virtual
Definition at line 188 of file gdiplusheaders.h.
     {
     }
Bitmap() [11/12]
Bitmap::Bitmap (GpImage * image, Status status) inline private
Definition at line 234 of file gdiplusheaders.h.
 : Image(image, status) {}
Bitmap() [12/12]
Bitmap::Bitmap (const Bitmap &) private
Member Function Documentation
ApplyEffect() [1/2]
static Status Bitmap::ApplyEffect (Bitmap ** inputs, INT numInputs, Effect * effect, RECT * ROI, RECT * outputRect, Bitmap ** output) static
ApplyEffect() [2/2]
Status Bitmap::ApplyEffect (Effect * effect, RECT * ROI)
Clone() [1/5]
virtual Bitmap* Bitmap::Clone () const inline virtual
Reimplemented from Image.
Definition at line 191 of file gdiplusheaders.h.
     {
         GpImage *cloneImage = NULL;
         Status status = updateStatus(DllExports::GdipCloneImage(
                 nativeImage, &cloneImage));
         if (status == Ok) {
             Bitmap *result = new Bitmap(cloneImage, lastStatus);
             if (!result) {
                 DllExports::GdipDisposeImage(cloneImage);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References Image::Bitmap, GdipCloneImage(), GdipDisposeImage(), Image::lastStatus, Image::nativeImage, NULL, Ok, OutOfMemory, and Image::updateStatus().
Referenced by Clone().
Clone() [2/5]
__inline__ Bitmap * Bitmap::Clone (const Rect & rect, PixelFormat format) const
Definition at line 511 of file gdiplusimpl.h.
 {
     return Clone(rect.X, rect.Y, rect.Width, rect.Height, format);
 }
References Clone(), Rect::Height, Rect::Width, Rect::X, and Rect::Y.
Clone() [3/5]
__inline__ Bitmap * Bitmap::Clone (const RectF & rect, PixelFormat format) const
Definition at line 506 of file gdiplusimpl.h.
 {
     return Clone(rect.X, rect.Y, rect.Width, rect.Height, format);
 }
References Clone(), RectF::Height, RectF::Width, RectF::X, and RectF::Y.
Clone() [4/5]
__inline__ Bitmap * Bitmap::Clone (INT x, INT y, INT width, INT height, PixelFormat format) const
Definition at line 535 of file gdiplusimpl.h.
 {
     GpBitmap *cloneBitmap = NULL;
     Status status = updateStatus(DllExports::GdipCloneBitmapAreaI(
             x, y, width, height, format,
             (GpBitmap*) nativeImage, &cloneBitmap));
     if (status == Ok) {
         Bitmap *result = new Bitmap(cloneBitmap, lastStatus);
         if (!result) {
             DllExports::GdipDisposeImage(cloneBitmap);
             lastStatus = OutOfMemory;
         }
         return result;
     } else {
         return NULL;
     }
 }
References Image::Bitmap, GdipCloneBitmapAreaI(), GdipDisposeImage(), Image::lastStatus, Image::nativeImage, NULL, Ok, OutOfMemory, and Image::updateStatus().
Clone() [5/5]
__inline__ Bitmap * Bitmap::Clone (REAL x, REAL y, REAL width, REAL height, PixelFormat format) const
Definition at line 516 of file gdiplusimpl.h.
 {
     GpBitmap *cloneBitmap = NULL;
     Status status = updateStatus(DllExports::GdipCloneBitmapArea(
             x, y, width, height, format,
             (GpBitmap*) nativeImage, &cloneBitmap));
     if (status == Ok) {
         Bitmap *result = new Bitmap(cloneBitmap, lastStatus);
         if (!result) {
             DllExports::GdipDisposeImage(cloneBitmap);
             lastStatus = OutOfMemory;
         }
         return result;
     } else {
         return NULL;
     }
 }
References Image::Bitmap, GdipCloneBitmapArea(), GdipDisposeImage(), Image::lastStatus, Image::nativeImage, NULL, Ok, OutOfMemory, and Image::updateStatus().
ConvertFormat()
__inline__ Status Bitmap::ConvertFormat (PixelFormat format, DitherType ditherType, PaletteType paletteType, ColorPalette * palette, REAL alphaThresholdPercent)
Definition at line 560 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipBitmapConvertFormat b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipBitmapConvertFormat(
             (GpBitmap*) nativeImage, format, ditherType,
             paletteType, palette, alphaThresholdPercent));
 }
References GdipBitmapConvertFormat(), Image::nativeImage, and Image::updateStatus().
FindFirstItem()
__inline__ Status Image::FindFirstItem (ImageItemData * item) inherited
Definition at line 79 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipFindFirstImageItem b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipFindFirstImageItem(
             nativeImage, item));
 }
References GdipFindFirstImageItem(), Image::nativeImage, and Image::updateStatus().
FindNextItem()
__inline__ Status Image::FindNextItem (ImageItemData * item) inherited
Definition at line 86 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipFindFirstImageItem b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipFindNextImageItem(
             nativeImage, item));
 }
References GdipFindNextImageItem(), Image::nativeImage, and Image::updateStatus().
FromBITMAPINFO()
__inline__ Bitmap * Bitmap::FromBITMAPINFO (const BITMAPINFO * gdiBitmapInfo, VOID * gdiBitmapData) static
Definition at line 351 of file gdiplusimpl.h.
 {
     return new Bitmap(gdiBitmapInfo, gdiBitmapData);
 }
References Image::Bitmap.
FromDirectDrawSurface7()
__inline__ Bitmap * Bitmap::FromDirectDrawSurface7 (IDirectDrawSurface7 * surface) static
Definition at line 357 of file gdiplusimpl.h.
 {
     return new Bitmap(surface);
 }
References Image::Bitmap.
FromFile()
__inline__ Bitmap * Bitmap::FromFile (const WCHAR * filename, BOOL useEmbeddedColorManagement = FALSE) static
Definition at line 362 of file gdiplusimpl.h.
 {
     return new Bitmap(filename, useEmbeddedColorManagement);
 }
References Image::Bitmap.
FromHBITMAP()
__inline__ Bitmap * Bitmap::FromHBITMAP (HBITMAP hbm, HPALETTE hpal) static
Definition at line 368 of file gdiplusimpl.h.
 {
     return new Bitmap(hbm, hpal);
 }
References Image::Bitmap.
FromHICON()
__inline__ Bitmap * Bitmap::FromHICON (HICON icon) static
Definition at line 373 of file gdiplusimpl.h.
 {
     return new Bitmap(icon);
 }
References Image::Bitmap, and icon().
FromResource()
__inline__ Bitmap * Bitmap::FromResource (HINSTANCE hInstance, const WCHAR * bitmapName) static
Definition at line 378 of file gdiplusimpl.h.
 {
     return new Bitmap(hInstance, bitmapName);
 }
References Image::Bitmap.
FromStream()
__inline__ Bitmap * Bitmap::FromStream (IStream * stream, BOOL useEmbeddedColorManagement = FALSE) static
Definition at line 384 of file gdiplusimpl.h.
 {
     return new Bitmap(stream, useEmbeddedColorManagement);
 }
References Image::Bitmap.
GetAllPropertyItems()
__inline__ Status Image::GetAllPropertyItems (UINT totalBufferSize, UINT numProperties, PropertyItem * allItems) inherited
Definition at line 93 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetAllPropertyItems(
             nativeImage, totalBufferSize, numProperties, allItems));
 }
References GdipGetAllPropertyItems(), Image::nativeImage, and Image::updateStatus().
GetBounds()
__inline__ Status Image::GetBounds (RectF * srcRect, Unit * srcUnit) inherited
Definition at line 100 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImageBounds(
             nativeImage, srcRect, srcUnit));
 }
References GdipGetImageBounds(), Image::nativeImage, and Image::updateStatus().
GetEncoderParameterList()
__inline__ Status Image::GetEncoderParameterList (const CLSID * clsidEncoder, UINT size, EncoderParameters * buffer) inherited
Definition at line 106 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetEncoderParameterList(
             nativeImage, clsidEncoder, size, buffer));
 }
References GdipGetEncoderParameterList(), Image::nativeImage, and Image::updateStatus().
GetEncoderParameterListSize()
__inline__ UINT Image::GetEncoderParameterListSize (const CLSID * clsidEncoder) inherited
Definition at line 113 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetEncoderParameterListSize(
             nativeImage, clsidEncoder, &result));
     return result;
 }
References GdipGetEncoderParameterListSize(), Image::nativeImage, and Image::updateStatus().
GetFlags()
__inline__ UINT Image::GetFlags () inherited
Definition at line 121 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageFlags(nativeImage, &result));
     return result;
 }
References GdipGetImageFlags(), Image::nativeImage, and Image::updateStatus().
GetFrameCount()
__inline__ UINT Image::GetFrameCount (const GUID * dimensionID) inherited
Definition at line 128 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipImageGetFrameCount(
             nativeImage, dimensionID, &result));
     return result;
 }
References GdipImageGetFrameCount(), Image::nativeImage, and Image::updateStatus().
GetFrameDimensionsCount()
__inline__ UINT Image::GetFrameDimensionsCount () inherited
Definition at line 136 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipImageGetFrameDimensionsCount(
             nativeImage, &result));
     return result;
 }
References GdipImageGetFrameDimensionsCount(), Image::nativeImage, and Image::updateStatus().
GetFrameDimensionsList()
__inline__ Status Image::GetFrameDimensionsList (GUID * dimensionIDs, UINT count) inherited
Definition at line 144 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageGetFrameDimensionsList(
             nativeImage, dimensionIDs, count));
 }
References GdipImageGetFrameDimensionsList(), Image::nativeImage, and Image::updateStatus().
GetHBITMAP()
__inline__ Status Bitmap::GetHBITMAP (const Color & colorBackground, HBITMAP * hbmReturn) const
Definition at line 570 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCreateHBITMAPFromBitmap(
             (GpBitmap*) nativeImage, hbmReturn,
             colorBackground.GetValue()));
 }
References GdipCreateHBITMAPFromBitmap(), Image::nativeImage, and Image::updateStatus().
GetHeight()
__inline__ UINT Image::GetHeight () inherited
Definition at line 150 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageHeight(nativeImage, &result));
     return result;
 }
References GdipGetImageHeight(), Image::nativeImage, and Image::updateStatus().
GetHICON()
__inline__ Status Bitmap::GetHICON (HICON * icon) const
Definition at line 578 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCreateHICONFromBitmap(
             (GpBitmap*) nativeImage, icon));
 }
References GdipCreateHICONFromBitmap(), icon(), Image::nativeImage, and Image::updateStatus().
GetHistogram()
__inline__ Status Bitmap::GetHistogram (HistogramFormat format, UINT numberOfEntries, UINT * channel0, UINT * channel1, UINT * channel2, UINT * channel3) const
Definition at line 584 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipBitmapGetHistogram(
             (GpBitmap*) nativeImage, format, numberOfEntries,
             channel0, channel1, channel2, channel3));
 }
References GdipBitmapGetHistogram(), Image::nativeImage, and Image::updateStatus().
GetHistogramSize()
__inline__ Status Bitmap::GetHistogramSize (HistogramFormat format, UINT * numberOfEntries) const
Definition at line 594 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipBitmapGetHistogramSize(
             format, numberOfEntries));
 }
References GdipBitmapGetHistogramSize(), and Image::updateStatus().
GetHorizontalResolution()
__inline__ REAL Image::GetHorizontalResolution () inherited
Definition at line 157 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetImageHorizontalResolution(
             nativeImage, &result));
     return result;
 }
References GdipGetImageHorizontalResolution(), Image::nativeImage, and Image::updateStatus().
GetItemData()
__inline__ Status Image::GetItemData (ImageItemData * item) inherited
Definition at line 165 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipGetImageItemData b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipGetImageItemData(
             nativeImage, item));
 }
References GdipGetImageItemData(), Image::nativeImage, and Image::updateStatus().
GetLastStatus()
Status Image::GetLastStatus () const inline inherited
Definition at line 133 of file gdiplusheaders.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References Image::lastStatus, and Ok.
GetPalette()
__inline__ Status Image::GetPalette (ColorPalette * palette, INT size) inherited
Definition at line 172 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImagePalette(
             nativeImage, palette, size));
 }
References GdipGetImagePalette(), Image::nativeImage, and Image::updateStatus().
GetPaletteSize()
__inline__ INT Image::GetPaletteSize () inherited
Definition at line 178 of file gdiplusimpl.h.
 {
     INT result = 0;
     updateStatus(DllExports::GdipGetImagePaletteSize(nativeImage, &result));
     return result;
 }
References GdipGetImagePaletteSize(), Image::nativeImage, and Image::updateStatus().
GetPhysicalDimension()
__inline__ Status Image::GetPhysicalDimension (SizeF * size) inherited
Definition at line 185 of file gdiplusimpl.h.
 {
     if (!size) return lastStatus = InvalidParameter;
     return updateStatus(DllExports::GdipGetImageDimension(
             nativeImage, &size->Width, &size->Height));
 }
References GdipGetImageDimension(), InvalidParameter, Image::lastStatus, Image::nativeImage, and Image::updateStatus().
GetPixel()
__inline__ Status Bitmap::GetPixel (INT x, INT y, Color * color) const
Definition at line 601 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipBitmapGetPixel(
             (GpBitmap*) nativeImage, x, y,
             color ? &color->Value : NULL));
 }
References GdipBitmapGetPixel(), Image::nativeImage, NULL, Image::updateStatus(), and Color::Value.
GetPixelFormat()
__inline__ PixelFormat Image::GetPixelFormat () inherited
Definition at line 192 of file gdiplusimpl.h.
 {
     PixelFormat result = (PixelFormat) 0;
     updateStatus(DllExports::GdipGetImagePixelFormat(nativeImage, &result));
     return result;
 }
References GdipGetImagePixelFormat(), Image::nativeImage, and Image::updateStatus().
GetPropertyCount()
__inline__ UINT Image::GetPropertyCount () inherited
Definition at line 199 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetPropertyCount(nativeImage, &result));
     return result;
 }
References GdipGetPropertyCount(), Image::nativeImage, and Image::updateStatus().
GetPropertyIdList()
__inline__ Status Image::GetPropertyIdList (UINT numOfProperty, PROPID * list) inherited
Definition at line 206 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertyIdList(
             nativeImage, numOfProperty, list));
 }
References GdipGetPropertyIdList(), Image::nativeImage, and Image::updateStatus().
GetPropertyItem()
__inline__ Status Image::GetPropertyItem (PROPID propId, UINT propSize, PropertyItem * buffer) inherited
Definition at line 212 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertyItem(
             nativeImage, propId, propSize, buffer));
 }
References GdipGetPropertyItem(), Image::nativeImage, and Image::updateStatus().
GetPropertyItemSize()
__inline__ UINT Image::GetPropertyItemSize (PROPID propId) inherited
Definition at line 219 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetPropertyItemSize(
             nativeImage, propId, &result));
     return result;
 }
References GdipGetPropertyItemSize(), Image::nativeImage, and Image::updateStatus().
GetPropertySize()
__inline__ Status Image::GetPropertySize (UINT * totalBufferSize, UINT * numProperties) inherited
Definition at line 227 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertySize(
             nativeImage, totalBufferSize, numProperties));
 }
References GdipGetPropertySize(), Image::nativeImage, and Image::updateStatus().
GetRawFormat()
__inline__ Status Image::GetRawFormat (GUID * format) inherited
Definition at line 234 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImageRawFormat(
             nativeImage, format));
 }
References GdipGetImageRawFormat(), Image::nativeImage, and Image::updateStatus().
GetThumbnailImage()
__inline__ Image * Image::GetThumbnailImage (UINT thumbWidth, UINT thumbHeight, GetThumbnailImageAbort callback, VOID * callbackData) inherited
Definition at line 240 of file gdiplusimpl.h.
 {
     GpImage *thumbImage = NULL;
     Status status = updateStatus(DllExports::GdipGetImageThumbnail(
             nativeImage, thumbWidth, thumbHeight, &thumbImage,
             callback, callbackData));
     if (status == Ok) {
         Image *result = new Image(thumbImage, Ok);
         if (!result) {
             DllExports::GdipDisposeImage(thumbImage);
             lastStatus = OutOfMemory;
         }
         return result;
     } else {
         return NULL;
     }
 }
References GdipDisposeImage(), GdipGetImageThumbnail(), Image::Image(), Image::lastStatus, Image::nativeImage, NULL, Ok, OutOfMemory, and Image::updateStatus().
GetType()
__inline__ ImageType Image::GetType () const inherited
Definition at line 260 of file gdiplusimpl.h.
 {
     ImageType result = ImageTypeUnknown;
     updateStatus(DllExports::GdipGetImageType(nativeImage, &result));
     return result;
 }
References GdipGetImageType(), ImageTypeUnknown, Image::nativeImage, and Image::updateStatus().
GetVerticalResolution()
__inline__ REAL Image::GetVerticalResolution () inherited
Definition at line 267 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetImageVerticalResolution(
             nativeImage, &result));
     return result;
 }
References GdipGetImageVerticalResolution(), Image::nativeImage, and Image::updateStatus().
GetWidth()
__inline__ UINT Image::GetWidth () inherited
Definition at line 275 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageWidth(nativeImage, &result));
     return result;
 }
References GdipGetImageWidth(), Image::nativeImage, and Image::updateStatus().
InitializePalette()
__inline__ Status Bitmap::InitializePalette (ColorPalette * palette, PaletteType paletteType, INT optimalColors, BOOL useTransparentColor, Bitmap * bitmap) static
Definition at line 397 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipInitializePalette b/c it isn't exported in 1.0
     return DllExports::GdipInitializePalette(palette, paletteType,
             optimalColors, useTransparentColor,
             bitmap ? (GpBitmap*) bitmap->nativeImage : NULL);
 }
References GdipInitializePalette(), Image::nativeImage, and NULL.
LockBits()
__inline__ Status Bitmap::LockBits (const Rect * rect, UINT flags, PixelFormat format, BitmapData * lockedBitmapData)
Definition at line 608 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipBitmapLockBits(
             (GpBitmap*) nativeImage, rect, flags, format,
             lockedBitmapData));
 }
References GdipBitmapLockBits(), Image::nativeImage, and Image::updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Bitmap& Bitmap::operator= (const Bitmap &) private
RemovePropertyItem()
__inline__ Status Image::RemovePropertyItem (PROPID propId) inherited
Definition at line 282 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipRemovePropertyItem(
             nativeImage, propId));
 }
References GdipRemovePropertyItem(), Image::nativeImage, and Image::updateStatus().
RotateFlip()
__inline__ Status Image::RotateFlip (RotateFlipType rotateFlipType) inherited
Definition at line 288 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageRotateFlip(
             nativeImage, rotateFlipType));
 }
References GdipImageRotateFlip(), Image::nativeImage, and Image::updateStatus().
Save() [1/2]
__inline__ Status Image::Save (const WCHAR * filename, const CLSID * clsidEncoder, const EncoderParameters * encoderParams) inherited
Definition at line 294 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveImageToFile(
             nativeImage, filename, clsidEncoder, encoderParams));
 }
References GdipSaveImageToFile(), Image::nativeImage, and Image::updateStatus().
Save() [2/2]
__inline__ Status Image::Save (IStream * stream, const CLSID * clsidEncoder, const EncoderParameters * encoderParams) inherited
Definition at line 301 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveImageToStream(
             nativeImage, stream, clsidEncoder, encoderParams));
 }
References GdipSaveImageToStream(), Image::nativeImage, and Image::updateStatus().
SaveAdd() [1/2]
__inline__ Status Image::SaveAdd (const EncoderParameters * encoderParams) inherited
Definition at line 308 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveAdd(
             nativeImage, encoderParams));
 }
References GdipSaveAdd(), Image::nativeImage, and Image::updateStatus().
SaveAdd() [2/2]
__inline__ Status Image::SaveAdd (Image * newImage, const EncoderParameters * encoderParams) inherited
Definition at line 314 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveAddImage(
             nativeImage,
             newImage ? newImage->nativeImage : NULL,
             encoderParams));
 }
References GdipSaveAddImage(), Image::nativeImage, NULL, and Image::updateStatus().
SelectActiveFrame()
__inline__ Status Image::SelectActiveFrame (const GUID * dimensionID, UINT frameIndex) inherited
Definition at line 323 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageSelectActiveFrame(
             nativeImage, dimensionID, frameIndex));
 }
References GdipImageSelectActiveFrame(), Image::nativeImage, and Image::updateStatus().
SetAbort()
__inline__ Status Image::SetAbort (GdiplusAbort * pIAbort) inherited
Definition at line 330 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipImageSetAbort because it isn't exported in 1.0
     return updateStatus(DllExports::GdipImageSetAbort(
             nativeImage, pIAbort));
 }
References GdipImageSetAbort(), Image::nativeImage, and Image::updateStatus().
SetPalette()
__inline__ Status Image::SetPalette (const ColorPalette * palette) inherited
Definition at line 337 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetImagePalette(
             nativeImage, palette));
 }
References GdipSetImagePalette(), Image::nativeImage, and Image::updateStatus().
SetPixel()
__inline__ Status Bitmap::SetPixel (INT x, INT y, const Color & color)
Definition at line 616 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipBitmapSetPixel(
             (GpBitmap*) nativeImage, x, y, color.GetValue()));
 }
References GdipBitmapSetPixel(), Image::nativeImage, and Image::updateStatus().
SetPropertyItem()
__inline__ Status Image::SetPropertyItem (const PropertyItem * item) inherited
Definition at line 343 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetPropertyItem(nativeImage, item));
 }
References GdipSetPropertyItem(), Image::nativeImage, and Image::updateStatus().
SetResolution()
__inline__ Status Bitmap::SetResolution (REAL xdpi, REAL ydpi)
Definition at line 622 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipBitmapSetResolution(
             (GpBitmap*) nativeImage, xdpi, ydpi));
 }
References GdipBitmapSetResolution(), Image::nativeImage, and Image::updateStatus().
UnlockBits()
__inline__ Status Bitmap::UnlockBits (BitmapData * lcokedBitmapData)
Definition at line 628 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipBitmapUnlockBits(
             (GpBitmap*) nativeImage, lockedBitmapData));
 }
References GdipBitmapUnlockBits(), Image::nativeImage, and Image::updateStatus().
updateStatus()
Status Image::updateStatus (Status newStatus) const inline private inherited
Definition at line 146 of file gdiplusheaders.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References Image::lastStatus, and Ok.
Referenced by Image::Clone(), Clone(), Metafile::Clone(), ConvertFormat(), Image::FindFirstItem(), Image::FindNextItem(), Image::GetAllPropertyItems(), Image::GetBounds(), Metafile::GetDownLevelRasterizationLimit(), Image::GetEncoderParameterList(), Image::GetEncoderParameterListSize(), Image::GetFlags(), Image::GetFrameCount(), Image::GetFrameDimensionsCount(), Image::GetFrameDimensionsList(), GetHBITMAP(), Image::GetHeight(), Metafile::GetHENHMETAFILE(), GetHICON(), GetHistogram(), GetHistogramSize(), Image::GetHorizontalResolution(), Image::GetItemData(), Metafile::GetMetafileHeader(), Image::GetPalette(), Image::GetPaletteSize(), Image::GetPhysicalDimension(), GetPixel(), Image::GetPixelFormat(), Image::GetPropertyCount(), Image::GetPropertyIdList(), Image::GetPropertyItem(), Image::GetPropertyItemSize(), Image::GetPropertySize(), Image::GetRawFormat(), Image::GetThumbnailImage(), Image::GetType(), Image::GetVerticalResolution(), Image::GetWidth(), LockBits(), Metafile::PlayRecord(), Image::RemovePropertyItem(), Image::RotateFlip(), Image::Save(), Image::SaveAdd(), Image::SelectActiveFrame(), Image::SetAbort(), Metafile::SetDownLevelRasterizationLimit(), Image::SetPalette(), SetPixel(), Image::SetPropertyItem(), SetResolution(), and UnlockBits().
Field Documentation
lastStatus
Status Image::lastStatus mutable private inherited
Definition at line 153 of file gdiplusheaders.h.
Referenced by Bitmap(), Image::Clone(), Clone(), Metafile::Clone(), Image::GetLastStatus(), Image::GetPhysicalDimension(), Image::GetThumbnailImage(), Image::Image(), Metafile::Metafile(), and Image::updateStatus().
nativeImage
GpImage* Image::nativeImage private inherited
Definition at line 152 of file gdiplusheaders.h.
Referenced by Bitmap(), CachedBitmap::CachedBitmap(), Image::Clone(), Clone(), Metafile::Clone(), ConvertFormat(), Graphics::EnumerateMetafile(), Image::FindFirstItem(), Image::FindNextItem(), Image::GetAllPropertyItems(), Image::GetBounds(), Metafile::GetDownLevelRasterizationLimit(), Image::GetEncoderParameterList(), Image::GetEncoderParameterListSize(), Image::GetFlags(), Image::GetFrameCount(), Image::GetFrameDimensionsCount(), Image::GetFrameDimensionsList(), GetHBITMAP(), Image::GetHeight(), Metafile::GetHENHMETAFILE(), GetHICON(), GetHistogram(), Image::GetHorizontalResolution(), Image::GetItemData(), Metafile::GetMetafileHeader(), Image::GetPalette(), Image::GetPaletteSize(), Image::GetPhysicalDimension(), GetPixel(), Image::GetPixelFormat(), Image::GetPropertyCount(), Image::GetPropertyIdList(), Image::GetPropertyItem(), Image::GetPropertyItemSize(), Image::GetPropertySize(), Image::GetRawFormat(), Image::GetThumbnailImage(), Image::GetType(), Image::GetVerticalResolution(), Image::GetWidth(), Image::Image(), InitializePalette(), LockBits(), Metafile::Metafile(), Metafile::PlayRecord(), Image::RemovePropertyItem(), Image::RotateFlip(), Image::Save(), Image::SaveAdd(), Image::SelectActiveFrame(), Image::SetAbort(), Metafile::SetDownLevelRasterizationLimit(), Image::SetPalette(), SetPixel(), Image::SetPropertyItem(), SetResolution(), UnlockBits(), and Image::~Image().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdiplusheaders.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h