ZEQ2-Lite: Source/Engine/libspeex/fftwrap.h File Reference
fftwrap.h File Reference
#include "arch.h"
Functions
void spx_fft (void *table, spx_word16_t *in, spx_word16_t *out)
Forward (real to half-complex) transform.
void spx_fft_destroy (void *table)
Destroy tables for an FFT.
void spx_fft_float (void *table, float *in, float *out)
Forward (real to half-complex) transform of float data.
void * spx_fft_init (int size)
Compute tables for an FFT.
void spx_ifft (void *table, spx_word16_t *in, spx_word16_t *out)
Backward (half-complex to real) transform.
void spx_ifft_float (void *table, float *in, float *out)
Backward (half-complex to real) transform of float data.
Function Documentation
spx_fft()
void spx_fft (void * table, spx_word16_t * in, spx_word16_t * out)
Forward (real to half-complex) transform.
Definition at line 176 of file fftwrap.c.
 {
    int i;
    float scale;
    struct kiss_config *t = (struct kiss_config *)table;
    scale = 1./t->N;
    kiss_fftr2(t->forward, in, out);
    for (i=0;i<t->N;i++)
       out[i] *= scale;
 }
References kiss_fftr2(), and out.
Referenced by preprocess_analysis(), speex_echo_cancellation(), speex_echo_get_residual(), and spx_fft_float().
spx_fft_destroy()
void spx_fft_destroy (void * table)
Destroy tables for an FFT.
Definition at line 154 of file fftwrap.c.
 {
    struct kiss_config *t = (struct kiss_config *)table;
    kiss_fftr_free(t->forward);
    kiss_fftr_free(t->backward);
    speex_free(table);
 }
References kiss_fftr_free, and speex_free().
Referenced by speex_echo_state_destroy(), and speex_preprocess_state_destroy().
spx_fft_float()
void spx_fft_float (void * table, float * in, float * out)
Forward (real to half-complex) transform of float data.
Definition at line 279 of file fftwrap.c.
 {
    spx_fft(table, in, out);
 }
References out, and spx_fft().
spx_fft_init()
void* spx_fft_init (int size)
Compute tables for an FFT.
Definition at line 144 of file fftwrap.c.
 {
    struct kiss_config *table;
    table = (struct kiss_config*)speex_alloc(sizeof(struct kiss_config));
    table->forward = kiss_fftr_alloc(size,0,NULL,NULL);
    table->backward = kiss_fftr_alloc(size,1,NULL,NULL);
    table->N = size;
    return table;
 }
References kiss_fftr_alloc(), NULL, and speex_alloc().
Referenced by speex_echo_state_init(), and speex_preprocess_state_init().
spx_ifft()
void spx_ifft (void * table, spx_word16_t * in, spx_word16_t * out)
Backward (half-complex to real) transform.
Definition at line 188 of file fftwrap.c.
 {
    struct kiss_config *t = (struct kiss_config *)table;
    kiss_fftri2(t->backward, in, out);
 }
References kiss_fftri2(), and out.
Referenced by speex_echo_cancellation(), speex_preprocess_run(), and spx_ifft_float().
spx_ifft_float()
void spx_ifft_float (void * table, float * in, float * out)
Backward (half-complex to real) transform of float data.
Definition at line 283 of file fftwrap.c.
 {
    spx_ifft(table, in, out);
 }
References out, and spx_ifft().