ZEQ2-Lite: Tools/MinGW/include/libgen.h File Reference
libgen.h File Reference
#include <_mingw.h>
Functions
__cdecl __MINGW_NOTHROW char * basename (char *)
__cdecl __MINGW_NOTHROW char * dirname (char *)
Function Documentation
basename()
__cdecl __MINGW_NOTHROW char* basename (char *)
Definition at line 203 of file lcc.c.
{
     char *s, *b, *t = 0;
     for (b = s = name; *s; s++)
         if (*s == '/' || *s == '\\') {
             b = s + 1;
             t = 0;
         } else if (*s == '.')
             t = s;
     s = strsave(b);
     if (t)
         s[t-b] = 0;
     return s;
 }
References strsave().
Referenced by filename(), FS_LoadZipFile(), opt(), and Sys_Basename().
dirname()
__cdecl __MINGW_NOTHROW char* dirname (char *)
Referenced by Sys_Dirname().