ZEQ2-Lite: Source/Game/CGame/cg_particlesystem.h File Reference
cg_particlesystem.h File Reference
Data Structures
struct PSys_Constraint_s
struct PSys_Emitter_s
struct PSys_FloatTimeLerp_s
struct PSys_Force_s
struct PSys_MemberTemplate_s
struct PSys_Orientation_s
struct PSys_Particle_s
struct PSys_ParticleTemplate_s
struct PSys_System_s
struct PSys_SystemTemplate_s
struct PSys_Vec4TimeLerp_s
Macros
#define MAX_CONSTRAINTS 256
#define MAX_EMITTERS 256
#define MAX_FORCES 256
#define MAX_PARTICLE_TEMPLATES 3
#define MAX_PARTICLES 1024
#define MAX_PARTICLESYSTEM_MEMBERS 8
#define MAX_PARTICLESYSTEMS 128
Enumerations
enum PSys_AOIType_t { AOI_INFINITE, AOI_SPHERE, AOI_CYLINDER }
enum PSys_ConstraintType_t { CTYPE_DISTANCE_MAX, CTYPE_DISTANCE_MIN, CTYPE_DISTANCE_EXACT, CTYPE_PLANE }
enum PSys_EmitterType_t {
ETYPE_POINT, ETYPE_RADIUS, ETYPE_SPHERE, ETYPE_POINT_SURFACE,
ETYPE_RADIUS_SURFACE
}
enum PSys_ForceType_t { FTYPE_DIRECTIONAL, FTYPE_SPHERICAL, FTYPE_DRAG, FTYPE_SWIRL }
enum PSys_MemberType_t { MEM_NONE, MEM_EMITTER, MEM_FORCE, MEM_CONSTRAINT }
enum PSys_RenderType_t { RTYPE_DEFAULT, RTYPE_SPARK, RTYPE_RAY }
Functions
static void PSys_AccumulateParticle (PSys_System_t *system, PSys_Particle_t *particle)
static void PSys_AccumulateSystem (PSys_System_t *system)
static qboolean PSys_ApplyConstraint (PSys_System_t *system, PSys_Constraint_t *constraint)
static qboolean PSys_ApplyDistanceConstraint (PSys_System_t *system, float value)
static qboolean PSys_ApplyDistanceMaxConstraint (PSys_System_t *system, float value)
static qboolean PSys_ApplyDistanceMinConstraint (PSys_System_t *system, float value)
static qboolean PSys_ApplyPlaneConstraint (PSys_System_t *system, float value)
static qboolean PSys_ConstrainSystem (PSys_System_t *system)
void PSys_InitCache (void)
static void PSys_IntegrateParticle (PSys_Particle_t *particle, float timeStepSquare, float timeStepCorrected)
static void PSys_IntegrateSystem (PSys_System_t *system, float timeStepSquare, float timeStepCorrected)
PSys_SystemTemplate_t * PSys_LoadSystemFromCache (char *systemName)
Macro Definition Documentation
MAX_CONSTRAINTS
#define MAX_CONSTRAINTS 256
Definition at line 10 of file cg_particlesystem.h.
MAX_EMITTERS
#define MAX_EMITTERS 256
Definition at line 8 of file cg_particlesystem.h.
MAX_FORCES
#define MAX_FORCES 256
Definition at line 9 of file cg_particlesystem.h.
MAX_PARTICLE_TEMPLATES
#define MAX_PARTICLE_TEMPLATES 3
Definition at line 11 of file cg_particlesystem.h.
MAX_PARTICLES
#define MAX_PARTICLES 1024
Definition at line 6 of file cg_particlesystem.h.
MAX_PARTICLESYSTEM_MEMBERS
#define MAX_PARTICLESYSTEM_MEMBERS 8
Definition at line 12 of file cg_particlesystem.h.
MAX_PARTICLESYSTEMS
#define MAX_PARTICLESYSTEMS 128
Definition at line 7 of file cg_particlesystem.h.
Enumeration Type Documentation
PSys_AOIType_t
enum PSys_AOIType_t
Enumerator
AOI_INFINITE
AOI_SPHERE
AOI_CYLINDER
Definition at line 28 of file cg_particlesystem.h.
              {
     AOI_INFINITE,
     AOI_SPHERE,
     AOI_CYLINDER
 } PSys_AOIType_t;
PSys_ConstraintType_t
enum PSys_ConstraintType_t
Enumerator
CTYPE_DISTANCE_MAX
CTYPE_DISTANCE_MIN
CTYPE_DISTANCE_EXACT
CTYPE_PLANE
Definition at line 14 of file cg_particlesystem.h.
              {
     CTYPE_DISTANCE_MAX,
     CTYPE_DISTANCE_MIN,
     CTYPE_DISTANCE_EXACT,
     CTYPE_PLANE
 } PSys_ConstraintType_t;
PSys_EmitterType_t
enum PSys_EmitterType_t
Enumerator
ETYPE_POINT
ETYPE_RADIUS
ETYPE_SPHERE
ETYPE_POINT_SURFACE
ETYPE_RADIUS_SURFACE
Definition at line 34 of file cg_particlesystem.h.
              {
     ETYPE_POINT,
     ETYPE_RADIUS,
     ETYPE_SPHERE,
     ETYPE_POINT_SURFACE, // NOTE: Must be first surface type!
     ETYPE_RADIUS_SURFACE,
 } PSys_EmitterType_t;
PSys_ForceType_t
enum PSys_ForceType_t
Enumerator
FTYPE_DIRECTIONAL
FTYPE_SPHERICAL
FTYPE_DRAG
FTYPE_SWIRL
Definition at line 21 of file cg_particlesystem.h.
              {
     FTYPE_DIRECTIONAL,
     FTYPE_SPHERICAL,
     FTYPE_DRAG,
     FTYPE_SWIRL
 } PSys_ForceType_t;
PSys_MemberType_t
enum PSys_MemberType_t
Enumerator
MEM_NONE
MEM_EMITTER
MEM_FORCE
MEM_CONSTRAINT
Definition at line 237 of file cg_particlesystem.h.
              {
     MEM_NONE, // Nonactive element
     MEM_EMITTER,
     MEM_FORCE,
     MEM_CONSTRAINT
 } PSys_MemberType_t;
PSys_RenderType_t
enum PSys_RenderType_t
Enumerator
RTYPE_DEFAULT
RTYPE_SPARK
RTYPE_RAY
Definition at line 43 of file cg_particlesystem.h.
              {
     RTYPE_DEFAULT,      // Model or sprite, based on whether or not the model field is filled in.
     RTYPE_SPARK,        // Only uses shader field. Stretches from current position back to old position.
     RTYPE_RAY           // Only uses shader field. Shoots a ray from particle's origin to its current position.
 } PSys_RenderType_t;
Function Documentation
PSys_AccumulateParticle()
static void PSys_AccumulateParticle (PSys_System_t * system, PSys_Particle_t * particle) static
PSys_AccumulateSystem()
static void PSys_AccumulateSystem (PSys_System_t * system) static
PSys_ApplyConstraint()
static qboolean PSys_ApplyConstraint (PSys_System_t * system, PSys_Constraint_t * constraint) static
PSys_ApplyDistanceConstraint()
static qboolean PSys_ApplyDistanceConstraint (PSys_System_t * system, float value) static
PSys_ApplyDistanceMaxConstraint()
static qboolean PSys_ApplyDistanceMaxConstraint (PSys_System_t * system, float value) static
PSys_ApplyDistanceMinConstraint()
static qboolean PSys_ApplyDistanceMinConstraint (PSys_System_t * system, float value) static
PSys_ApplyPlaneConstraint()
static qboolean PSys_ApplyPlaneConstraint (PSys_System_t * system, float value) static
PSys_ConstrainSystem()
static qboolean PSys_ConstrainSystem (PSys_System_t * system) static
PSys_InitCache()
void PSys_InitCache (void)
Definition at line 1157 of file cg_particlesystem_cache.c.
{
     int         numdirs;
     char        filename[128];
     char        dirlist[1024];
     char*       dirptr;
     int         i;
     int         dirlen;
     // Feedback start of loading particle systems
     CG_Printf( "\nInitializing Particle Systems\n" );
     // Clear the cache
     memset(PSys_Cache, 0, sizeof(PSys_Cache));
     PSys_CurCacheSize = 0;
     // Parse all files fitting the /effects/*.psys pattern
     numdirs = trap_FS_GetFileList("effects", ".psys", dirlist, 1024 );
     dirptr  = dirlist;
     for ( i = 0; i < numdirs; i++, dirptr += dirlen+1 ) {
         dirlen = strlen(dirptr);
         strcpy(filename, "effects/");
         strcat(filename, dirptr);
         PSys_ParseFile(filename, &PSys_CurCacheSize );
     }
     // Quicksort loaded systems to retrieve them more efficiently with a binary search
     // NOTE: Must not give a negative 2nd parameter, or will read out of bounds!
     if ( PSys_CurCacheSize > 1 ) {
         PSys_QSortCache( 0, PSys_CurCacheSize - 1 );
     }
     CG_Printf( "%i Particle Systems Initialized\n\n", PSys_CurCacheSize );
 }
References CG_Printf(), PSys_Cache, PSys_CurCacheSize, PSys_ParseFile(), PSys_QSortCache(), and trap_FS_GetFileList().
Referenced by CG_InitParticleSystems().
PSys_IntegrateParticle()
static void PSys_IntegrateParticle (PSys_Particle_t * particle, float timeStepSquare, float timeStepCorrected) static
PSys_IntegrateSystem()
static void PSys_IntegrateSystem (PSys_System_t * system, float timeStepSquare, float timeStepCorrected) static
PSys_LoadSystemFromCache()
PSys_SystemTemplate_t* PSys_LoadSystemFromCache (char * systemName)
Definition at line 1094 of file cg_particlesystem_cache.c.
{
     int low, high, mid;
     // No string
     if ( !systemName ) return NULL;
     // Empty string
     if ( !*systemName ) return NULL;
     // Zero systems cached
     if ( !PSys_CurCacheSize ) {
         return NULL;
     }
     // Binary search the cache
     low = 0;
     high = PSys_CurCacheSize;
     while ( low + 1 != high ) {
         mid = ( low + high ) / 2;
         if ( Q_stricmp( PSys_Cache[mid].name, systemName ) < 1  ) low  = mid;
         if ( Q_stricmp( PSys_Cache[mid].name, systemName ) == 1 ) high = mid;
         // if ( PSys_Cache[mid].name <= systemName ) low  = mid;
         // if ( PSys_Cache[mid].name >  systemName ) high = mid;
     }
     if ( Q_stricmp( PSys_Cache[low].name, systemName )) return NULL;
     // if ( PSys_Cache[low].name != systemName ) return NULL;
     // Found the system we were looking for
     return &PSys_Cache[low];
 }
References NULL, PSys_Cache, PSys_CurCacheSize, and Q_stricmp().
Referenced by PSys_SpawnCachedSystem().