ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/i686-pc-mingw32/bits/ctype_base.h File Reference
ctype_base.h File Reference
Functions
namespace std _GLIBCXX_VISIBILITY (default)
Function Documentation
_GLIBCXX_VISIBILITY()
namespace std _GLIBCXX_VISIBILITY (default)
Base class for ctype.
Definition at line 37 of file ctype_base.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
   struct ctype_base
   {
     // Non-standard typedefs.
     typedef const int*      __to_type;
     // NB: Offsets into ctype<char>::_M_table force a particular size
     // on the mask type. Because of this, we don't use an enum.
     typedef unsigned short  mask;
     static const mask upper = 1 << 0;
     static const mask lower = 1 << 1;
     static const mask alpha = 1 << 2;
     static const mask digit = 1 << 3;
     static const mask xdigit    = 1 << 4;
     static const mask space = 1 << 5;
     static const mask print = 1 << 6;
     static const mask graph = (1 << 2) | (1 << 3) | (1 << 9);  // alnum|punct
     static const mask cntrl = 1 << 8;
     static const mask punct     = 1 << 9;
     static const mask alnum = (1 << 2) | (1 << 3);  // alpha|digit
   };
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References digit(), print(), and space().