ZEQ2-Lite: Tools/zMesh Exporter/cmdlib.h File Reference
cmdlib.h File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <ctype.h>
#include <time.h>
#include <stdarg.h>
Macros
#define __BYTEBOOL__
#define MAX_OS_PATH 1024
#define MEM_BLOCKSIZE 4096
#define myoffsetof(type, identifier) ((size_t)&((type *)0)->identifier)
Typedefs
typedef unsigned char byte
Enumerations
enum qboolean {
qfalse, qtrue, qfalse, qtrue,
qfalse, qtrue
}
Functions
void _printf (const char *format,...)
float BigFloat (float l)
int BigLong (int l)
short BigShort (short l)
int CheckParm (const char *check)
void CreatePath (const char *path)
void DefaultExtension (char *path, const char *extension)
void DefaultPath (char *path, const char *basepath)
void Error (const char *error,...)
void ExtractFileBase (const char *path, char *dest)
void ExtractFileExtension (const char *path, char *dest)
void ExtractFilePath (const char *path, char *dest)
qboolean FileExists (const char *filename)
int FileTime (const char *path)
float LittleFloat (float l)
int LittleLong (int l)
short LittleShort (short l)
int LoadFile (const char *filename, void **bufferptr)
int LoadFileBlock (const char *filename, void **bufferptr)
int Q_filelength (FILE *f)
void Q_mkdir (const char *path)
FILE * SafeOpenRead (const char *filename)
FILE * SafeOpenWrite (const char *filename)
void SafeRead (FILE *f, void *buffer, int count)
void SafeWrite (FILE *f, const void *buffer, int count)
void SaveFile (const char *filename, const void *buffer, int count)
void StripExtension (char *path)
void StripFilename (char *path)
int TryLoadFile (const char *filename, void **bufferptr)
Variables
int myargc
char ** myargv
Macro Definition Documentation
__BYTEBOOL__
#define __BYTEBOOL__
Definition at line 54 of file cmdlib.h.
MAX_OS_PATH
#define MAX_OS_PATH 1024
Definition at line 59 of file cmdlib.h.
MEM_BLOCKSIZE
#define MEM_BLOCKSIZE 4096
Definition at line 60 of file cmdlib.h.
myoffsetof
#define myoffsetof (type, identifier) ((size_t)&((type *)0)->identifier)
Definition at line 63 of file cmdlib.h.
Typedef Documentation
byte
typedef unsigned char byte
Definition at line 56 of file cmdlib.h.
Enumeration Type Documentation
qboolean
enum qboolean
Enumerator
qfalse
qtrue
qfalse
qtrue
qfalse
qtrue
Definition at line 55 of file cmdlib.h.
 { qfalse, qtrue } qboolean;
Function Documentation
_printf()
void _printf (const char * format, ...)
Definition at line 178 of file cmdlib.c.
{
     va_list argptr;
   char text[4096];
 #ifdef WIN32
   ATOM a;
 #endif
     va_start (argptr,format);
     vsprintf (text, format, argptr);
     va_end (argptr);
   printf("%s", text);
 #ifdef WIN32
   if (!lookedForServer) {
     lookedForServer = qtrue;
     hwndOut = FindWindow(NULL, "Q3Map Process Server");
     if (hwndOut) {
       wm_BroadcastCommand = RegisterWindowMessage( "Q3MPS_BroadcastCommand" );
     }
   }
   if (hwndOut) {
     a = GlobalAddAtom(text);
     PostMessage(hwndOut, wm_BroadcastCommand, 0, (LPARAM)a);
   }
 #endif
 }
References FindWindow, GlobalAddAtom, NULL, PostMessage, printf(), qtrue, RegisterWindowMessage, va_end, va_start, and vsprintf().
Referenced by Error().
BigFloat()
float BigFloat (float l)
Definition at line 527 of file cmdlib.c.
{
     union {byte b[4]; float f;} in, out;
     in.f = l;
     out.b[0] = in.b[3];
     out.b[1] = in.b[2];
     out.b[2] = in.b[1];
     out.b[3] = in.b[0];
     return out.f;
 }
References in, and out.
BigLong()
int BigLong (int l)
Definition at line 512 of file cmdlib.c.
{
     byte    b1,b2,b3,b4;
     b1 = l&255;
     b2 = (l>>8)&255;
     b3 = (l>>16)&255;
     b4 = (l>>24)&255;
     return ((int)b1<<24) + ((int)b2<<16) + ((int)b3<<8) + b4;
 }
Referenced by DecodeImageInterlaced(), DecodeImageNonInterlaced(), DecompressIDATs(), FindChunk(), and R_LoadPNG().
BigShort()
short BigShort (short l)
Definition at line 498 of file cmdlib.c.
{
     byte    b1,b2;
     b1 = l&255;
     b2 = (l>>8)&255;
     return (b1<<8) + b2;
 }
Referenced by CL_Connect_f(), CL_GlobalServers_f(), CL_LocalServers_f(), CL_Rcon_f(), CL_RequestMotd(), CL_ServersResponsePacket(), NET_StringToAdr(), and SV_MasterHeartbeat().
CheckParm()
int CheckParm (const char * check)
Definition at line 604 of file cmdlib.c.
 {
     int             i;
     for (i = 1;i<myargc;i++)
     {
         if ( !Q_stricmp(check, myargv[i]) )
             return i;
     }
     return 0;
 }
References check(), myargc, myargv, Q_stricmp(), and strcmp().
Referenced by main().
CreatePath()
void CreatePath (const char * path)
Definition at line 1085 of file cmdlib.c.
 {
     const char  *ofs;
     char        c;
     char        dir[1024];
 #ifdef _WIN32
     int     olddrive = -1;
     if ( path[1] == ':' )
     {
         olddrive = _getdrive();
         _chdrive( toupper( path[0] ) - 'A' + 1 );
     }
 #endif
     if (path[1] == ':')
         path += 2;
     for (ofs = path+1 ; *ofs ; ofs++)
     {
         c = *ofs;
         if (c == '/' || c == '\\')
         {   // create the directory
             memcpy( dir, path, ofs - path );
             dir[ ofs - path ] = 0;
             Q_mkdir( dir );
         }
     }
 #ifdef _WIN32
     if ( olddrive != -1 )
     {
         _chdrive( olddrive );
     }
 #endif
 }
References _chdrive(), _getdrive(), dir, memcpy(), Q_mkdir(), and toupper().
Referenced by QCopyFile(), SaveAnimation(), SaveMesh(), and WriteVmFile().
DefaultExtension()
void DefaultExtension (char * path, const char * extension)
Definition at line 809 of file cmdlib.c.
 {
     char    *src;
 //
 // if path doesnt have a .EXT, append extension
 // (extension should include the .)
 //
     src = path + strlen(path) - 1;
     while (*src != '/' && *src != '\\' && src != path)
     {
         if (*src == '.')
             return;                 // it has an extension
         src--;
     }
     strcat (path, extension);
 }
References strcat(), and strlen().
Referenced by Assemble(), DoAnims(), DoMeshes(), LoadCFG(), LoadSMD(), ParseOptionFile(), SaveAnimation(), and SaveMesh().
DefaultPath()
void DefaultPath (char * path, const char * basepath)
Definition at line 829 of file cmdlib.c.
 {
     char    temp[128];
     if (path[0] == PATHSEPERATOR)
         return;                   // absolute path location
     strcpy (temp,path);
     strcpy (path,basepath);
     strcat (path,temp);
 }
References basepath(), PATHSEPERATOR, strcat(), and strcpy().
Error()
void Error (const char * error, ...)
Definition at line 143 of file cmdlib.c.
 {
     va_list argptr;
     _printf ("\n************ ERROR ************\n");
     va_start (argptr,error);
     vprintf (error,argptr);
     va_end (argptr);
     _printf ("\r\n");
     exit (1);
 }
References _printf(), error(), exit(), va_end, va_start, and vprintf().
Referenced by ExpandGamePath(), ExpandPath(), ParseHex(), Q_mkdir(), SafeOpenRead(), SafeOpenWrite(), SafeRead(), SafeWrite(), and SetQdirFromPath().
ExtractFileBase()
void ExtractFileBase (const char * path, char * dest)
Definition at line 890 of file cmdlib.c.
 {
     const char    *src;
     src = path + strlen(path) - 1;
 //
 // back up until a \ or the start
 //
     while (src != path && *(src-1) != PATHSEPERATOR)
         src--;
     while (*src && *src != '.')
     {
         *dest++ = *src++;
     }
     *dest = 0;
 }
References PATHSEPERATOR, and strlen().
ExtractFileExtension()
void ExtractFileExtension (const char * path, char * dest)
Definition at line 909 of file cmdlib.c.
 {
     const char    *src;
     src = path + strlen(path) - 1;
 //
 // back up until a . or the start
 //
     while (src != path && *(src-1) != '.')
         src--;
     if (src == path)
     {
         *dest = 0;  // no extension
         return;
     }
     strcpy (dest,src);
 }
References strcpy(), and strlen().
ExtractFilePath()
void ExtractFilePath (const char * path, char * dest)
Definition at line 874 of file cmdlib.c.
 {
     const char    *src;
     src = path + strlen(path) - 1;
 //
 // back up until a \ or the start
 //
     while (src != path && *(src-1) != '\\' && *(src-1) != '/')
         src--;
     memcpy (dest, path, src-path);
     dest[src-path] = 0;
 }
References memcpy(), and strlen().
FileExists()
qboolean FileExists (const char * filename)
Definition at line 699 of file cmdlib.c.
 {
     FILE    *f;
     f = myfopen (filename, "r");
     if (!f)
         return qfalse;
     fclose (f);
     return qtrue;
 }
References fclose(), fopen(), myfopen(), qfalse, and qtrue.
Referenced by DoAnims(), and DoMeshes().
FileTime()
int FileTime (const char * path)
Definition at line 437 of file cmdlib.c.
 {
     struct  stat    buf;
     if (stat (path,&buf) == -1)
         return -1;
     return buf.st_mtime;
 }
References stat::st_mtime.
LittleFloat()
float LittleFloat (float l)
Definition at line 539 of file cmdlib.c.
{
     return l;
 }
Referenced by CMod_LoadPatches(), CMod_LoadPlanes(), CMod_LoadSubmodels(), ParseFace(), ParseFlare(), ParseMesh(), ParseTriSurf(), R_LoadMD3(), R_LoadPlanes(), R_LoadSubmodels(), SaveAnimation(), and SaveMesh().
LittleLong()
int LittleLong (int l)
Definition at line 523 of file cmdlib.c.
{
     return l;
 }
Referenced by CL_PacketEvent(), CL_ReadDemoMessage(), CL_Record_f(), CL_WriteDemoMessage(), CM_Checksum(), CM_LoadMap(), CM_LumpChecksum(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadLeafSurfaces(), CMod_LoadNodes(), CMod_LoadPatches(), CMod_LoadShaders(), CMod_LoadSubmodels(), CMod_LoadVisibility(), FGetLittleLong(), FS_LoadZipFile(), loadWord(), Netchan_Process(), ParseFace(), ParseFlare(), ParseMesh(), ParseTriSurf(), R_LoadBMP(), R_LoadFogs(), R_LoadMarksurfaces(), R_LoadMD3(), R_LoadNodesAndLeafs(), R_LoadShaders(), R_LoadSubmodels(), R_LoadSurfaces(), R_LoadVisibility(), R_RegisterMD3(), RE_LoadWorldMap(), SaveAnimation(), SaveMesh(), ShaderForShaderNum(), VM_LoadQVM(), WriteVmFile(), and yuv_to_rgb24().
LittleShort()
short LittleShort (short l)
Definition at line 507 of file cmdlib.c.
{
     return l;
 }
Referenced by FGetLittleShort(), R_LoadBMP(), R_LoadMD3(), R_LoadPCX(), R_LoadTGA(), ResampleSfxRaw(), and S_ByteSwapRawSamples().
LoadFile()
int LoadFile (const char * filename, void ** bufferptr)
Definition at line 715 of file cmdlib.c.
 {
     FILE    *f;
     int    length;
     void    *buffer;
     f = SafeOpenRead (filename);
     length = Q_filelength (f);
     buffer = malloc (length+1);
     ((char *)buffer)[length] = 0;
     SafeRead (f, buffer, length);
     fclose (f);
     *bufferptr = buffer;
     return length;
 }
References fclose(), malloc(), Q_filelength(), SafeOpenRead(), and SafeRead().
Referenced by AddScriptToStack(), Assemble(), ParseOptionFile(), and QCopyFile().
LoadFileBlock()
int LoadFileBlock (const char * filename, void ** bufferptr)
Definition at line 741 of file cmdlib.c.
 {
     FILE    *f;
     int    length, nBlock, nAllocSize;
     void    *buffer;
     f = SafeOpenRead (filename);
     length = Q_filelength (f);
   nAllocSize = length;
   nBlock = nAllocSize % MEM_BLOCKSIZE;
   if ( nBlock > 0) {
     nAllocSize += MEM_BLOCKSIZE - nBlock;
   }
     buffer = malloc (nAllocSize+1);
   memset(buffer, 0, nAllocSize+1);
     SafeRead (f, buffer, length);
     fclose (f);
     *bufferptr = buffer;
     return length;
 }
References fclose(), malloc(), MEM_BLOCKSIZE, memset(), Q_filelength(), SafeOpenRead(), and SafeRead().
Q_filelength()
int Q_filelength (FILE * f)
Definition at line 624 of file cmdlib.c.
 {
     int     pos;
     int     end;
     pos = ftell (f);
     fseek (f, 0, SEEK_END);
     end = ftell (f);
     fseek (f, pos, SEEK_SET);
     return end;
 }
References fseek(), ftell(), SEEK_END, and SEEK_SET.
Referenced by LoadFile(), LoadFileBlock(), and TryLoadFile().
Q_mkdir()
void Q_mkdir (const char * path)
Definition at line 417 of file cmdlib.c.
 {
 #ifdef WIN32
     if (_mkdir (path) != -1)
         return;
 #else
     if (mkdir (path, 0777) != -1)
         return;
 #endif
     if (errno != EEXIST)
         Error ("mkdir %s: %s",path, strerror(errno));
 }
References _mkdir(), EEXIST, errno, Error(), mkdir(), and strerror().
Referenced by CreatePath().
SafeOpenRead()
FILE* SafeOpenRead (const char * filename)
Definition at line 667 of file cmdlib.c.
 {
     FILE    *f;
     f = myfopen(filename, "rb");
     if (!f)
         Error ("Error opening %s: %s",filename,strerror(errno));
     return f;
 }
References errno, Error(), fopen(), myfopen(), and strerror().
Referenced by LoadFile(), and LoadFileBlock().
SafeOpenWrite()
FILE* SafeOpenWrite (const char * filename)
Definition at line 655 of file cmdlib.c.
 {
     FILE    *f;
     f = myfopen(filename, "wb");
     if (!f)
         Error ("Error opening %s: %s",filename,strerror(errno));
     return f;
 }
References errno, Error(), fopen(), myfopen(), and strerror().
Referenced by SaveAnimation(), SaveFile(), SaveMesh(), WriteMapFile(), and WriteVmFile().
SafeRead()
void SafeRead (FILE * f, void * buffer, int count)
Definition at line 680 of file cmdlib.c.
 {
     if ( fread (buffer, 1, count, f) != (size_t)count)
         Error ("File read failure");
 }
References Error(), and fread().
Referenced by LoadFile(), LoadFileBlock(), and TryLoadFile().
SafeWrite()
void SafeWrite (FILE * f, const void * buffer, int count)
Definition at line 687 of file cmdlib.c.
 {
     if (fwrite (buffer, 1, count, f) != (size_t)count)
         Error ("File write failure");
 }
References Error(), and fwrite().
Referenced by SaveAnimation(), SaveFile(), SaveMesh(), and WriteVmFile().
SaveFile()
void SaveFile (const char * filename, const void * buffer, int count)
Definition at line 798 of file cmdlib.c.
 {
     FILE    *f;
     f = SafeOpenWrite (filename);
     SafeWrite (f, buffer, count);
     fclose (f);
 }
References fclose(), SafeOpenWrite(), and SafeWrite().
Referenced by QCopyFile().
StripExtension()
void StripExtension (char * path)
Definition at line 851 of file cmdlib.c.
 {
     int             length;
     length = strlen(path)-1;
     while (length > 0 && path[length] != '.')
     {
         length--;
         if (path[length] == '/')
             return;     // no extension
     }
     if (length)
         path[length] = 0;
 }
References int, and strlen().
Referenced by DoAnims(), DoMeshes(), LoadCFG(), LoadSMD(), SaveAnimation(), SaveMesh(), WriteMapFile(), and WriteVmFile().
StripFilename()
void StripFilename (char * path)
Definition at line 841 of file cmdlib.c.
 {
     int             length;
     length = strlen(path)-1;
     while (length > 0 && path[length] != PATHSEPERATOR)
         length--;
     path[length] = 0;
 }
References int, PATHSEPERATOR, and strlen().
TryLoadFile()
int TryLoadFile (const char * filename, void ** bufferptr)
Definition at line 771 of file cmdlib.c.
 {
     FILE    *f;
     int    length;
     void    *buffer;
     *bufferptr = NULL;
     f = myfopen (filename, "rb");
     if (!f)
         return -1;
     length = Q_filelength (f);
     buffer = malloc (length+1);
     ((char *)buffer)[length] = 0;
     SafeRead (f, buffer, length);
     fclose (f);
     *bufferptr = buffer;
     return length;
 }
References fclose(), fopen(), malloc(), myfopen(), NULL, Q_filelength(), and SafeRead().
Variable Documentation
myargc
int myargc
Definition at line 41 of file cmdlib.c.
Referenced by CheckParm(), and main().
myargv
char** myargv
Definition at line 42 of file cmdlib.c.
Referenced by CheckParm(), and main().