ZEQ2-Lite: Engine/tools/lcc/src/event.c File Reference
event.c File Reference
#include "c.h"
Data Structures
struct entry
Functions
void apply (List event, void *arg1, void *arg2)
void attach (Apply func, void *cl, List *list)
Variables
Events events
Function Documentation
apply()
void apply (List event, void * arg1, void * arg2)
Definition at line 18 of file event.c.
{
     if (event) {
         List lp = event;
         do {
             struct entry *p = lp->x;
             (*p->func)(p->cl, arg1, arg2);
             lp = lp->link;
         } while (lp != event);
     }
 }
References entry::link.
Referenced by call(), compound(), definept(), expr2(), expr3(), funcdefn(), main(), and retcode().
attach()
void attach (Apply func, void * cl, List * list)
Definition at line 10 of file event.c.
{
     struct entry *p;
     NEW(p, PERM);
     p->func = func;
     p->cl = cl;
     *list = append(p, *list);
 }
References append(), cl, func(), NEW, and PERM.
Referenced by prof_init(), and trace_init().
Variable Documentation
events
Events events
Definition at line 9 of file event.c.
Referenced by call(), compound(), CON_Input(), definept(), expr2(), expr3(), funcdefn(), main(), prof_init(), retcode(), and trace_init().