ZEQ2-Lite: CustomLineCap Class Reference
CustomLineCap Class Reference
#include <gdiplusheaders.h>
Public Member Functions
CustomLineCap (const GraphicsPath *fillPath, const GraphicsPath *strokePath, LineCap baseCap=LineCapFlat, REAL baseInset=0.0f)
virtual ~CustomLineCap ()
virtual CustomLineCap * Clone () const
LineCap GetBaseCap () const
REAL GetBaseInset () const
Status GetLastStatus () const
Status GetStrokeCaps (LineCap *startCap, LineCap *endCap) const
LineJoin GetStrokeJoin () const
REAL GetWidthScale () const
Status SetBaseCap (LineCap baseCap)
Status SetBaseInset (REAL inset)
Status SetStrokeCap (LineCap strokeCap)
Status SetStrokeCaps (LineCap startCap, LineCap endCap)
Status SetStrokeJoin (LineJoin lineJoin)
Status SetWidthScale (REAL widthScale)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
CustomLineCap (const CustomLineCap &)
CustomLineCap (GpCustomLineCap *customLineCap, Status status)
CustomLineCap & operator= (const CustomLineCap &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpCustomLineCap * nativeCustomLineCap
Friends
class AdjustableArrowCap
class Pen
Detailed Description
Definition at line 260 of file gdiplusheaders.h.
Constructor & Destructor Documentation
CustomLineCap() [1/3]
__inline__ CustomLineCap::CustomLineCap (const GraphicsPath * fillPath, const GraphicsPath * strokePath, LineCap baseCap = LineCapFlat, REAL baseInset = 0.0f)
Definition at line 654 of file gdiplusimpl.h.
                                         :
         nativeCustomLineCap(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateCustomLineCap(
             fillPath ? fillPath->nativePath : NULL,
             strokePath ? strokePath->nativePath : NULL,
             baseCap, baseInset, &nativeCustomLineCap);
 }
References GdipCreateCustomLineCap(), lastStatus, nativeCustomLineCap, GraphicsPath::nativePath, and NULL.
Referenced by Clone().
~CustomLineCap()
virtual CustomLineCap::~CustomLineCap () inline virtual
Definition at line 271 of file gdiplusheaders.h.
     {
         DllExports::GdipDeleteCustomLineCap(nativeCustomLineCap);
     }
References GdipDeleteCustomLineCap(), and nativeCustomLineCap.
CustomLineCap() [2/3]
CustomLineCap::CustomLineCap (GpCustomLineCap * customLineCap, Status status) inline private
Definition at line 313 of file gdiplusheaders.h.
                                                                 :
         nativeCustomLineCap(customLineCap), lastStatus(status) {}
CustomLineCap() [3/3]
CustomLineCap::CustomLineCap (const CustomLineCap &) private
Member Function Documentation
Clone()
virtual CustomLineCap* CustomLineCap::Clone () const inline virtual
Reimplemented in AdjustableArrowCap.
Definition at line 275 of file gdiplusheaders.h.
     {
         GpCustomLineCap *cloneCustomLineCap = NULL;
         Status status = updateStatus(DllExports::GdipCloneCustomLineCap(
                 nativeCustomLineCap, &cloneCustomLineCap));
         if (status == Ok) {
             CustomLineCap *result = new CustomLineCap(
                     cloneCustomLineCap, lastStatus);
             if (!result) {
                 DllExports::GdipDeleteCustomLineCap(cloneCustomLineCap);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References CustomLineCap(), GdipCloneCustomLineCap(), GdipDeleteCustomLineCap(), lastStatus, nativeCustomLineCap, NULL, Ok, OutOfMemory, and updateStatus().
GetBaseCap()
__inline__ LineCap CustomLineCap::GetBaseCap () const
Definition at line 666 of file gdiplusimpl.h.
 {
     LineCap result = LineCapFlat;
     updateStatus(DllExports::GdipGetCustomLineCapBaseCap(
             nativeCustomLineCap, &result));
     return result;
 }
References GdipGetCustomLineCapBaseCap(), LineCapFlat, nativeCustomLineCap, and updateStatus().
GetBaseInset()
__inline__ REAL CustomLineCap::GetBaseInset () const
Definition at line 674 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetCustomLineCapBaseInset(
             nativeCustomLineCap, &result));
     return result;
 }
References GdipGetCustomLineCapBaseInset(), nativeCustomLineCap, and updateStatus().
GetLastStatus()
Status CustomLineCap::GetLastStatus () const inline
Definition at line 305 of file gdiplusheaders.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetStrokeCaps()
__inline__ Status CustomLineCap::GetStrokeCaps (LineCap * startCap, LineCap * endCap) const
Definition at line 682 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetCustomLineCapStrokeCaps(
             nativeCustomLineCap, startCap, endCap));
 }
References GdipGetCustomLineCapStrokeCaps(), nativeCustomLineCap, and updateStatus().
GetStrokeJoin()
__inline__ LineJoin CustomLineCap::GetStrokeJoin () const
Definition at line 689 of file gdiplusimpl.h.
 {
     LineJoin result = LineJoinMiter;
     updateStatus(DllExports::GdipGetCustomLineCapStrokeJoin(
             nativeCustomLineCap, &result));
     return result;
 }
References GdipGetCustomLineCapStrokeJoin(), LineJoinMiter, nativeCustomLineCap, and updateStatus().
GetWidthScale()
__inline__ REAL CustomLineCap::GetWidthScale () const
Definition at line 697 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetCustomLineCapWidthScale(
             nativeCustomLineCap, &result));
     return result;
 }
References GdipGetCustomLineCapWidthScale(), nativeCustomLineCap, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
CustomLineCap& CustomLineCap::operator= (const CustomLineCap &) private
SetBaseCap()
__inline__ Status CustomLineCap::SetBaseCap (LineCap baseCap)
Definition at line 705 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapBaseCap(
             nativeCustomLineCap, baseCap));
 }
References GdipSetCustomLineCapBaseCap(), nativeCustomLineCap, and updateStatus().
SetBaseInset()
__inline__ Status CustomLineCap::SetBaseInset (REAL inset)
Definition at line 711 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapBaseInset(
             nativeCustomLineCap, inset));
 }
References GdipSetCustomLineCapBaseInset(), nativeCustomLineCap, and updateStatus().
SetStrokeCap()
__inline__ Status CustomLineCap::SetStrokeCap (LineCap strokeCap)
Definition at line 717 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapStrokeCaps(
             nativeCustomLineCap, strokeCap, strokeCap));
 }
References GdipSetCustomLineCapStrokeCaps(), nativeCustomLineCap, and updateStatus().
SetStrokeCaps()
__inline__ Status CustomLineCap::SetStrokeCaps (LineCap startCap, LineCap endCap)
Definition at line 723 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapStrokeCaps(
             nativeCustomLineCap, startCap, endCap));
 }
References GdipSetCustomLineCapStrokeCaps(), nativeCustomLineCap, and updateStatus().
SetStrokeJoin()
__inline__ Status CustomLineCap::SetStrokeJoin (LineJoin lineJoin)
Definition at line 729 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapStrokeJoin(
             nativeCustomLineCap, lineJoin));
 }
References GdipSetCustomLineCapStrokeJoin(), nativeCustomLineCap, and updateStatus().
SetWidthScale()
__inline__ Status CustomLineCap::SetWidthScale (REAL widthScale)
Definition at line 735 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapWidthScale(
             nativeCustomLineCap, widthScale));
 }
References GdipSetCustomLineCapWidthScale(), nativeCustomLineCap, and updateStatus().
updateStatus()
Status CustomLineCap::updateStatus (Status newStatus) const inline private
Definition at line 318 of file gdiplusheaders.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by AdjustableArrowCap::Clone(), Clone(), GetBaseCap(), GetBaseInset(), AdjustableArrowCap::GetHeight(), AdjustableArrowCap::GetMiddleInset(), GetStrokeCaps(), GetStrokeJoin(), AdjustableArrowCap::GetWidth(), GetWidthScale(), AdjustableArrowCap::IsFilled(), SetBaseCap(), SetBaseInset(), AdjustableArrowCap::SetFillState(), AdjustableArrowCap::SetHeight(), AdjustableArrowCap::SetMiddleInset(), SetStrokeCap(), SetStrokeCaps(), SetStrokeJoin(), AdjustableArrowCap::SetWidth(), and SetWidthScale().
Friends And Related Function Documentation
AdjustableArrowCap
friend class AdjustableArrowCap friend
Definition at line 262 of file gdiplusheaders.h.
Referenced by AdjustableArrowCap::Clone().
Pen
friend class Pen friend
Definition at line 263 of file gdiplusheaders.h.
Field Documentation
lastStatus
Status CustomLineCap::lastStatus mutable private
Definition at line 325 of file gdiplusheaders.h.
Referenced by AdjustableArrowCap::AdjustableArrowCap(), AdjustableArrowCap::Clone(), Clone(), CustomLineCap(), GetLastStatus(), and updateStatus().
nativeCustomLineCap
GpCustomLineCap* CustomLineCap::nativeCustomLineCap private
Definition at line 324 of file gdiplusheaders.h.
Referenced by AdjustableArrowCap::AdjustableArrowCap(), AdjustableArrowCap::Clone(), Clone(), CustomLineCap(), GetBaseCap(), GetBaseInset(), Pen::GetCustomEndCap(), Pen::GetCustomStartCap(), AdjustableArrowCap::GetHeight(), AdjustableArrowCap::GetMiddleInset(), GetStrokeCaps(), GetStrokeJoin(), AdjustableArrowCap::GetWidth(), GetWidthScale(), AdjustableArrowCap::IsFilled(), SetBaseCap(), SetBaseInset(), Pen::SetCustomEndCap(), Pen::SetCustomStartCap(), AdjustableArrowCap::SetFillState(), AdjustableArrowCap::SetHeight(), AdjustableArrowCap::SetMiddleInset(), SetStrokeCap(), SetStrokeCaps(), SetStrokeJoin(), AdjustableArrowCap::SetWidth(), SetWidthScale(), and ~CustomLineCap().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdiplusheaders.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h