ZEQ2-Lite: Game/CGame/cg_playerstate.c File Reference
cg_playerstate.c File Reference
#include "cg_local.h"
Functions
void CG_CheckChangedPredictableEvents (playerState_t *ps)
void CG_CheckLocalSounds (playerState_t *ps, playerState_t *ops)
void CG_CheckPlayerstateEvents (playerState_t *ps, playerState_t *ops)
void CG_DamageFeedback (int yawByte, int pitchByte, int damage)
void CG_Respawn (void)
void CG_TransitionPlayerState (playerState_t *ps, playerState_t *ops)
Variables
char * eventnames []
Function Documentation
CG_CheckChangedPredictableEvents()
void CG_CheckChangedPredictableEvents (playerState_t * ps)
Definition at line 197 of file cg_playerstate.c.
{
     int i;
     int event;
     centity_t   *cent;
     cent = &cg.predictedPlayerEntity;
     for ( i = ps->eventSequence - MAX_PS_EVENTS ; i < ps->eventSequence ; i++ ) {
         //
         if (i >= cg.eventSequence) {
             continue;
         }
         // if this event is not further back in than the maximum predictable events we remember
         if (i > cg.eventSequence - MAX_PREDICTED_EVENTS) {
             // if the new playerstate event is different from a previously predicted one
             if ( ps->events[i & (MAX_PS_EVENTS-1)] != cg.predictableEvents[i & (MAX_PREDICTED_EVENTS-1) ] ) {
                 event = ps->events[ i & (MAX_PS_EVENTS-1) ];
                 cent->currentState.event = event;
                 cent->currentState.eventParm = ps->eventParms[ i & (MAX_PS_EVENTS-1) ];
                 CG_EntityEvent( cent, cent->lerpOrigin );
                 cg.predictableEvents[ i & (MAX_PREDICTED_EVENTS-1) ] = event;
                 if ( cg_showmiss.integer ) {
                     CG_Printf("WARNING: changed predicted event\n");
                 }
             }
         }
     }
 }
References cg, CG_EntityEvent(), CG_Printf(), cg_showmiss, cg_t::eventSequence, vmCvar_t::integer, MAX_PREDICTED_EVENTS, MAX_PS_EVENTS, cg_t::predictableEvents, and cg_t::predictedPlayerEntity.
CG_CheckLocalSounds()
void CG_CheckLocalSounds (playerState_t * ps, playerState_t * ops)
Definition at line 234 of file cg_playerstate.c.
{
     int         highScore, powerLevel, armor;
     sfxHandle_t sfx;
     // don't play the sounds if the player just changed teams
     if ( ps->persistant[PERS_TEAM] != ops->persistant[PERS_TEAM] ) {
         return;
     }
     // powerLevel changes of more than -1 should make pain sounds
     if ( ps->powerLevel[plFatigue] < ops->powerLevel[plFatigue] - 1 ) {
         // but only if actual damage is there; not if deducting powerLevel for an attack!
         if (ps->damageCount) {
             if ( ps->powerLevel[plFatigue] > 0 ) {
                 CG_PainEvent( &cg.predictedPlayerEntity, ps->powerLevel[plFatigue] );
             }
         }
     }
     // if we are going into the intermission, don't start any voices
     if ( cg.intermissionStarted ) {
         return;
     }
 }
References cg, CG_PainEvent(), cg_t::intermissionStarted, ops, PERS_TEAM, plFatigue, and cg_t::predictedPlayerEntity.
Referenced by CG_TransitionPlayerState().
CG_CheckPlayerstateEvents()
void CG_CheckPlayerstateEvents (playerState_t * ps, playerState_t * ops)
Definition at line 159 of file cg_playerstate.c.
{
     int         i;
     int         event;
     centity_t   *cent;
     if ( ps->externalEvent && ps->externalEvent != ops->externalEvent ) {
         cent = &cg_entities[ ps->clientNum ];
         cent->currentState.event = ps->externalEvent;
         cent->currentState.eventParm = ps->externalEventParm;
         CG_EntityEvent( cent, cent->lerpOrigin );
     }
     cent = &cg.predictedPlayerEntity; // cg_entities[ ps->clientNum ];
     // go through the predictable events buffer
     for ( i = ps->eventSequence - MAX_PS_EVENTS ; i < ps->eventSequence ; i++ ) {
         // if we have a new predictable event
         if ( i >= ops->eventSequence
             // or the server told us to play another event instead of a predicted event we already issued
             // or something the server told us changed our prediction causing a different event
             || (i > ops->eventSequence - MAX_PS_EVENTS && ps->events[i & (MAX_PS_EVENTS-1)] != ops->events[i & (MAX_PS_EVENTS-1)]) ) {
             event = ps->events[ i & (MAX_PS_EVENTS-1) ];
             cent->currentState.event = event;
             cent->currentState.eventParm = ps->eventParms[ i & (MAX_PS_EVENTS-1) ];
             CG_EntityEvent( cent, cent->lerpOrigin );
             cg.predictableEvents[ i & (MAX_PREDICTED_EVENTS-1) ] = event;
             cg.eventSequence++;
         }
     }
 }
References cg, cg_entities, CG_EntityEvent(), cg_t::eventSequence, MAX_PREDICTED_EVENTS, MAX_PS_EVENTS, ops, cg_t::predictableEvents, and cg_t::predictedPlayerEntity.
Referenced by CG_TransitionPlayerState().
CG_DamageFeedback()
void CG_DamageFeedback (int yawByte, int pitchByte, int damage)
Definition at line 33 of file cg_playerstate.c.
{
     float       left, front, up;
     float       kick;
     int         powerLevel;
     float       scale;
     vec3_t      dir;
     vec3_t      angles;
     float       dist;
     float       yaw, pitch;
     // show the attacking player's head and name in corner
     cg.attackerTime = cg.time;
     // the lower on powerLevel you are, the greater the view kick will be
     powerLevel = cg.snap->ps.powerLevel[plFatigue];
     if ( powerLevel < 40 ) {
         scale = 1;
     } else {
         scale = 40.0 / powerLevel;
     }
     kick = damage * scale;
     if (kick < 5)
         kick = 5;
     if (kick > 10)
         kick = 10;
     // if yaw and pitch are both 255, make the damage always centered (falling, etc)
     if ( yawByte == 255 && pitchByte == 255 ) {
         cg.damageX = 0;
         cg.damageY = 0;
         cg.v_dmg_roll = 0;
         cg.v_dmg_pitch = -kick;
     } else {
         // positional
         pitch = pitchByte / 255.0 * 360;
         yaw = yawByte / 255.0 * 360;
         angles[PITCH] = pitch;
         angles[YAW] = yaw;
         angles[ROLL] = 0;
         AngleVectors( angles, dir, NULL, NULL );
         VectorSubtract( vec3_origin, dir, dir );
         front = DotProduct (dir, cg.refdef.viewaxis[0] );
         left = DotProduct (dir, cg.refdef.viewaxis[1] );
         up = DotProduct (dir, cg.refdef.viewaxis[2] );
         dir[0] = front;
         dir[1] = left;
         dir[2] = 0;
         dist = VectorLength( dir );
         if ( dist < 0.1 ) {
             dist = 0.1f;
         }
         cg.v_dmg_roll = kick * left;
         cg.v_dmg_pitch = -kick * front;
         if ( front <= 0.1 ) {
             front = 0.1f;
         }
         cg.damageX = -left / front;
         cg.damageY = up / dist;
     }
     // clamp the position
     if ( cg.damageX > 1.0 ) {
         cg.damageX = 1.0;
     }
     if ( cg.damageX < - 1.0 ) {
         cg.damageX = -1.0;
     }
     if ( cg.damageY > 1.0 ) {
         cg.damageY = 1.0;
     }
     if ( cg.damageY < - 1.0 ) {
         cg.damageY = -1.0;
     }
     // don't let the screen flashes vary as much
     if ( kick > 10 ) {
         kick = 10;
     }
     cg.damageValue = kick;
     cg.v_dmg_time = cg.time + DAMAGE_TIME;
     cg.damageTime = cg.snap->serverTime;
 }
References angles, AngleVectors(), cg_t::attackerTime, cg, DAMAGE_TIME, cg_t::damageTime, cg_t::damageValue, cg_t::damageX, cg_t::damageY, dir, DotProduct, NULL, PITCH, plFatigue, snapshot_t::ps, cg_t::refdef, ROLL, snapshot_t::serverTime, cg_t::snap, cg_t::time, up, cg_t::v_dmg_pitch, cg_t::v_dmg_roll, cg_t::v_dmg_time, vec3_origin, VectorLength(), VectorSubtract, refdef_t::viewaxis, and YAW.
CG_Respawn()
void CG_Respawn (void)
Definition at line 135 of file cg_playerstate.c.
{
     // no error decay on player movement
     cg.thisFrameTeleport = qtrue;
     cg.resetValues = qtrue;
     // display weapons available
     cg.weaponSelectTime = cg.time;
     // select the weapon the server says we are using
     cg.weaponSelect = cg.snap->ps.weapon;
     cg.tierCurrent = 0;
     cg.tierSelect = -1;
     cg.weaponDesired = 1;
     cg.weaponChanged = 0;
     cg.weaponSelectionMode = 0;
 }
References cg, snapshot_t::ps, qtrue, cg_t::resetValues, cg_t::snap, cg_t::thisFrameTeleport, cg_t::tierCurrent, cg_t::tierSelect, cg_t::time, cg_t::weaponChanged, cg_t::weaponDesired, cg_t::weaponSelect, cg_t::weaponSelectionMode, and cg_t::weaponSelectTime.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionPlayerState().
CG_TransitionPlayerState()
void CG_TransitionPlayerState (playerState_t * ps, playerState_t * ops)
Definition at line 263 of file cg_playerstate.c.
{
     if(ps->clientNum != ops->clientNum){
         cg.thisFrameTeleport = qtrue;
         *ops = *ps;
     }
     if(ps->persistant[PERS_SPAWN_COUNT] != ops->persistant[PERS_SPAWN_COUNT]){
         CG_Respawn();
     }
     if(cg.mapRestart){
         CG_Respawn();
         cg.mapRestart = qfalse;
     }
     if(cg.snap->ps.pm_type != PM_INTERMISSION && ps->persistant[PERS_TEAM] != TEAM_SPECTATOR){
         CG_CheckLocalSounds(ps,ops);
     }
     CG_CheckPlayerstateEvents(ps,ops);
     if(ps->viewheight != ops->viewheight){
         cg.duckChange = ps->viewheight - ops->viewheight;
         cg.duckTime = cg.time;
     }
     cg.tierSelectionMode = 0;
     cg.tierSelect = -1;
     if(ps->powerLevel[plTierChanged] == 1 && ops->powerLevel[plTierChanged] != 1) {
         cg.tierCurrent = ps->powerLevel[plTierCurrent];
         cg.weaponDesired = -1;
         cg.weaponSelectionMode = 0;
     }
     if(ps->currentSkill[WPSTAT_CHANGED] != 0){
         //If the server validated a weapon change, changes it
         cg.weaponSelectionMode = 0;
         cg.weaponDesired = -1;
         cg.weaponSelect = ps->weapon;
         if(ps->currentSkill[WPSTAT_CHANGED] != -1) {
             cg.drawWeaponBar = 1;
         }
     }
 }
References cg, CG_CheckLocalSounds(), CG_CheckPlayerstateEvents(), CG_Respawn(), cg_t::drawWeaponBar, cg_t::duckChange, cg_t::duckTime, cg_t::mapRestart, ops, PERS_SPAWN_COUNT, PERS_TEAM, plTierChanged, plTierCurrent, PM_INTERMISSION, snapshot_t::ps, qfalse, qtrue, cg_t::snap, TEAM_SPECTATOR, cg_t::thisFrameTeleport, cg_t::tierCurrent, cg_t::tierSelect, cg_t::tierSelectionMode, cg_t::time, cg_t::weaponDesired, cg_t::weaponSelect, cg_t::weaponSelectionMode, and WPSTAT_CHANGED.
Referenced by CG_PredictPlayerState(), and CG_TransitionSnapshot().
Variable Documentation
eventnames
char* eventnames[]
Definition at line 244 of file bg_misc.c.
Referenced by BG_AddPredictableEventToPlayerstate().