ZEQ2-Lite: Source/Engine/libspeex/vq.c File Reference
vq.c File Reference
#include "vq.h"
#include "stack_alloc.h"
#include "arch.h"
Functions
int scal_quant (spx_word16_t in, const spx_word16_t *boundary, int entries)
int scal_quant32 (spx_word32_t in, const spx_word32_t *boundary, int entries)
void vq_nbest (spx_word16_t *in, const spx_word16_t *codebook, int len, int entries, spx_word32_t *E, int N, int *nbest, spx_word32_t *best_dist, char *stack)
void vq_nbest_sign (spx_word16_t *in, const spx_word16_t *codebook, int len, int entries, spx_word32_t *E, int N, int *nbest, spx_word32_t *best_dist, char *stack)
Function Documentation
scal_quant()
int scal_quant (spx_word16_t in, const spx_word16_t * boundary, int entries)
Definition at line 51 of file vq.c.
 {
    int i=0;
    while (i<entries-1 && in>boundary[0])
    {
       boundary++;
       i++;
    }
    return i;
 }
Referenced by nb_encode(), sb_encode(), speex_encode_stereo(), and speex_encode_stereo_int().
scal_quant32()
int scal_quant32 (spx_word32_t in, const spx_word32_t * boundary, int entries)
Definition at line 62 of file vq.c.
 {
    int i=0;
    while (i<entries-1 && in>boundary[0])
    {
       boundary++;
       i++;
    }
    return i;
 }
Referenced by nb_encode().
vq_nbest()
void vq_nbest (spx_word16_t * in, const spx_word16_t * codebook, int len, int entries, spx_word32_t * E, int N, int * nbest, spx_word32_t * best_dist, char * stack)
Definition at line 76 of file vq.c.
 {
    int i,j,k,used;
    used = 0;
    for (i=0;i<entries;i++)
    {
       spx_word32_t dist=0;
       for (j=0;j<len;j++)
          dist = MAC16_16(dist,in[j],*codebook++);
 #ifdef FIXED_POINT
       dist=SUB32(SHR32(E[i],1),dist);
 #else
       dist=.5f*E[i]-dist;
 #endif
       if (i<N || dist<best_dist[N-1])
       {
          for (k=N-1; (k >= 1) && (k > used || dist < best_dist[k-1]); k--)
          {
             best_dist[k]=best_dist[k-1];
             nbest[k] = nbest[k-1];
          }
          best_dist[k]=dist;
          nbest[k]=i;
          used++;
       }
    }
 }
Referenced by split_cb_search_shape_sign(), and split_cb_search_shape_sign_N1().
vq_nbest_sign()
void vq_nbest_sign (spx_word16_t * in, const spx_word16_t * codebook, int len, int entries, spx_word32_t * E, int N, int * nbest, spx_word32_t * best_dist, char * stack)
Definition at line 110 of file vq.c.
 {
    int i,j,k, sign, used;
    used=0;
    for (i=0;i<entries;i++)
    {
       spx_word32_t dist=0;
       for (j=0;j<len;j++)
          dist = MAC16_16(dist,in[j],*codebook++);
       if (dist>0)
       {
          sign=0;
          dist=-dist;
       } else
       {
          sign=1;
       }
 #ifdef FIXED_POINT
       dist = ADD32(dist,SHR32(E[i],1));
 #else
       dist = ADD32(dist,.5f*E[i]);
 #endif
       if (i<N || dist<best_dist[N-1])
       {
          for (k=N-1; (k >= 1) && (k > used || dist < best_dist[k-1]); k--)
          {
             best_dist[k]=best_dist[k-1];
             nbest[k] = nbest[k-1];
          }
          best_dist[k]=dist;
          nbest[k]=i;
          used++;
          if (sign)
             nbest[k]+=entries;
       }
    }
 }
References ADD32, MAC16_16, and SHR32.
Referenced by split_cb_search_shape_sign(), and split_cb_search_shape_sign_N1().