ZEQ2-Lite: Source/Engine/tools/lcc/src/tree.c File Reference
tree.c File Reference
#include "c.h"
Data Structures
struct nodeid
Functions
int nodeid (Tree p)
char * opname (int op)
int * printed (int id)
void printtree (Tree p, int fd)
static void printtree1 (Tree, int, int)
Tree root (Tree p)
static Tree root1 (Tree p)
Tree texpr (Tree(*f)(int), int tok, int a)
Tree tree (int op, Type type, Tree left, Tree right)
Variables
static struct nodeid ids [500]
static int nid = 1
static int warn
int where = STMT
Function Documentation
nodeid()
int nodeid (Tree p)
Definition at line 172 of file tree.c.
                    {
     int i = 1;
     ids[nid].node = p;
     while (ids[i].node != p)
         i++;
     if (i == nid)
         ids[nid++].printed = 0;
     return i;
 }
References nid.
Referenced by printdag(), printdag1(), printnode(), and printtree1().
opname()
char* opname (int op)
Definition at line 113 of file tree.c.
                      {
     static char *opnames[] = {
     "",
     "CNST",
     "ARG",
     "ASGN",
     "INDIR",
     "CVC",
     "CVD",
     "CVF",
     "CVI",
     "CVP",
     "CVS",
     "CVU",
     "NEG",
     "CALL",
     "*LOAD*",
     "RET",
     "ADDRG",
     "ADDRF",
     "ADDRL",
     "ADD",
     "SUB",
     "LSH",
     "MOD",
     "RSH",
     "BAND",
     "BCOM",
     "BOR",
     "BXOR",
     "DIV",
     "MUL",
     "EQ",
     "GE",
     "GT",
     "LE",
     "LT",
     "NE",
     "JUMP",
     "LABEL",
     "AND",
     "NOT",
     "OR",
     "COND",
     "RIGHT",
     "FIELD"
     }, *suffixes[] = {
         "0", "F", "D", "C", "S", "I", "U", "P", "V", "B",
         "10","11","12","13","14","15"
     };
     if (generic(op) >= AND && generic(op) <= FIELD && opsize(op) == 0)
         return opnames[opindex(op)];
     return stringf("%s%s%s",
         opindex(op) > 0 && opindex(op) < NELEMS(opnames) ?
             opnames[opindex(op)] : stringd(opindex(op)),
         suffixes[optype(op)], opsize(op) > 0 ? stringd(opsize(op)) : "");
 }
References AND, FIELD, NELEMS, op, opindex, opnames, opsize, optype, stringd(), stringf(), and suffixes.
Referenced by dumptree(), emit(), getrule(), printnode(), and printtree1().
printed()
int* printed (int id)
Definition at line 184 of file tree.c.
                      {
     if (id)
         return &ids[id].printed;
     nid = 1;
     return 0;
 }
References nid.
Referenced by opt(), printdag(), printdag1(), printtree(), and printtree1().
printtree()
void printtree (Tree p, int fd)
Definition at line 192 of file tree.c.
{
     (void)printed(0);
     printtree1(p, fd, 1);
 }
References printed(), printtree1(), and void().
printtree1()
static void printtree1 (Tree p, int fd, int lev) static
Definition at line 198 of file tree.c.
{
     FILE *f = fd == 1 ? stdout : stderr;
     int i;
     static char blanks[] = "                                                   ";
     if (p == 0 || *printed(i = nodeid(p)))
         return;
     fprint(f, "#%d%S%S", i, blanks, i < 10 ? 2 : i < 100 ? 1 : 0, blanks, lev);
     fprint(f, "%s %t", opname(p->op), p->type);
     *printed(i) = 1;
     for (i = 0; i < NELEMS(p->kids); i++)
         if (p->kids[i])
             fprint(f, " #%d", nodeid(p->kids[i]));
     if (p->op == FIELD && p->u.field)
         fprint(f, " %s %d..%d", p->u.field->name,
             fieldsize(p->u.field) + fieldright(p->u.field), fieldright(p->u.field));
     else if (generic(p->op) == CNST)
         fprint(f, " %s", vtoa(p->type, p->u.v));
     else if (p->u.sym)
         fprint(f, " %s", p->u.sym->name);
     if (p->node)
         fprint(f, " node=%p", p->node);
     fprint(f, "\n");
     for (i = 0; i < NELEMS(p->kids); i++)
         printtree1(p->kids[i], fd, lev + 1);
 }
References FIELD, fieldright, fieldsize, fprint(), NELEMS, nodeid(), opname(), printed(), and vtoa().
Referenced by printtree().
root()
Tree root (Tree p)
Definition at line 108 of file tree.c.
                   {
     warn = 0;
     return root1(p);
 }
References root1(), and warn.
Referenced by addrof(), call(), condtree(), dcllocal(), emitrecalc(), expr(), expr0(), inflate_table(), PSys_UpdateEmitters(), and simplify().
root1()
static Tree root1 (Tree p) static
Definition at line 34 of file tree.c.
{
     if (p == NULL)
         return p;
     if (p->type == voidtype)
         warn++;
     switch (generic(p->op)) {
     case COND: {
         Tree q = p->kids[1];
         assert(q && q->op == RIGHT);
         if (p->u.sym && q->kids[0] && generic(q->kids[0]->op) == ASGN)
             q->kids[0] = root1(q->kids[0]->kids[1]);
         else
             q->kids[0] = root1(q->kids[0]);
         if (p->u.sym && q->kids[1] && generic(q->kids[1]->op) == ASGN)
             q->kids[1] = root1(q->kids[1]->kids[1]);
         else
             q->kids[1] = root1(q->kids[1]);
         p->u.sym = 0;
         if (q->kids[0] == 0 && q->kids[1] == 0)
             p = root1(p->kids[0]);
         }
         break;
     case AND: case OR:
         if ((p->kids[1] = root1(p->kids[1])) == 0)
             p = root1(p->kids[0]);
         break;
     case NOT:
         if (warn++ == 0)
             warning("expression with no effect elided\n");
         return root1(p->kids[0]);
     case RIGHT:
         if (p->kids[1] == 0)
             return root1(p->kids[0]);
         if (p->kids[0] && p->kids[0]->op == CALL+B
         &&  p->kids[1] && p->kids[1]->op == INDIR+B)
             /* avoid premature release of the CALL+B temporary */
             return p->kids[0];
         if (p->kids[0] && p->kids[0]->op == RIGHT
         &&  p->kids[1] == p->kids[0]->kids[0])
             /* de-construct e++ construction */
             return p->kids[0]->kids[1];
         p = tree(RIGHT, p->type, root1(p->kids[0]), root1(p->kids[1]));
         return p->kids[0] || p->kids[1] ? p : (Tree)0;
     case EQ:  case NE:  case GT:   case GE:  case LE:  case LT:
     case ADD: case SUB: case MUL:  case DIV: case MOD:
     case LSH: case RSH: case BAND: case BOR: case BXOR:
         if (warn++ == 0)
             warning("expression with no effect elided\n");
         p = tree(RIGHT, p->type, root1(p->kids[0]), root1(p->kids[1]));
         return p->kids[0] || p->kids[1] ? p : (Tree)0;
     case INDIR:
         if (p->type->size == 0 && unqual(p->type) != voidtype)
             warning("reference to `%t' elided\n", p->type);
         if (isptr(p->kids[0]->type) && isvolatile(p->kids[0]->type->type))
             warning("reference to `volatile %t' elided\n", p->type);
         /* fall thru */
     case CVI: case CVF: case CVU: case CVP:
     case NEG: case BCOM: case FIELD:
         if (warn++ == 0)
             warning("expression with no effect elided\n");
         return root1(p->kids[0]);
     case ADDRL: case ADDRG: case ADDRF: case CNST:
         if (needconst)
             return p;
         if (warn++ == 0)
             warning("expression with no effect elided\n");
         return NULL;
     case ARG: case ASGN: case CALL: case JUMP: case LABEL:
         break;
     default: assert(0);
     }
     return p;
 }
References ADD, AND, ASGN, B, CALL, COND, DIV, EQ, FIELD, GT, isptr, isvolatile, LSH, LT, MOD, needconst, NOT, NULL, OR, RIGHT, RSH, SUB, tree(), unqual, voidtype, warn, and warning().
Referenced by root().
texpr()
Tree texpr (Tree(*)(int) f, int tok, int a)
Definition at line 25 of file tree.c.
{
     int save = where;
     Tree p;
     where = a;
     p = (*f)(tok);
     where = save;
     return p;
 }
References where.
Referenced by forstmt(), and whilestmt().
tree()
Tree tree (int op, Type type, Tree left, Tree right)
Definition at line 14 of file tree.c.
{
     Tree p;
     NEW0(p, where);
     p->op = op;
     p->type = type;
     p->kids[0] = left;
     p->kids[1] = right;
     return p;
 }
References NEW0, op, right, and where.
Referenced by root1().
Variable Documentation
ids
struct nodeid ids[500] static
nid
int nid = 1 static
Definition at line 6 of file tree.c.
Referenced by nodeid(), and printed().
warn
int warn static
Definition at line 5 of file tree.c.
Referenced by Cvar_Validate(), root(), and root1().
where
int where = STMT
Definition at line 4 of file tree.c.
Referenced by texpr(), and tree().