ZEQ2-Lite: __gnu_pbds Namespace Reference
__gnu_pbds Namespace Reference
This implementation loosely borrows ideas from: 1) Fast Mergeable Integer Maps, Okasaki, Gill 1998 2) Ptset: Sets of integers implemented as Patricia trees, Jean-Christophe Filliatr, 2000.
Namespaces
detail
Data Structures
struct associative_container_tag
Basic associative-container.
class basic_hash_table
An abstract basic hash-based associative container.
struct basic_hash_tag
Basic hash.
struct basic_invalidation_guarantee
class basic_tree
An abstract basic tree-like (tree, trie) associative container.
struct basic_tree_tag
Basic tree.
struct binary_heap_tag
Binary-heap (array-based).
struct binomial_heap_tag
Binomial-heap.
class cc_hash_max_collision_check_resize_trigger
class cc_hash_table
A concrete collision-chaining hash-based associative container.
struct cc_hash_tag
Collision-chaining hash.
class container_base
An abstract basic associative container.
struct container_error
struct container_tag
Base data structure tag.
struct container_traits
container_traits
struct container_traits_base
Base traits type for containers.
struct container_traits_base< binary_heap_tag >
struct container_traits_base< binomial_heap_tag >
struct container_traits_base< cc_hash_tag >
struct container_traits_base< gp_hash_tag >
struct container_traits_base< list_update_tag >
struct container_traits_base< ov_tree_tag >
struct container_traits_base< pairing_heap_tag >
struct container_traits_base< pat_trie_tag >
struct container_traits_base< rb_tree_tag >
struct container_traits_base< rc_binomial_heap_tag >
struct container_traits_base< splay_tree_tag >
struct container_traits_base< thin_heap_tag >
class counter_lu_policy
class direct_mask_range_hashing
class direct_mod_range_hashing
class gp_hash_table
A concrete general-probing hash-based associative container.
struct gp_hash_tag
General-probing hash.
class hash_exponential_size_policy
class hash_load_check_resize_trigger
class hash_prime_size_policy
class hash_standard_resize_policy
struct insert_error
struct join_error
class linear_probe_fn
class list_update
A list-update based associative container.
struct list_update_tag
List-update.
class move_to_front_lu_policy
struct null_hash_fn
struct null_lu_metadata
struct null_mapped_type
A mapped-policy indicating that an associative container is a set.
struct null_probe_fn
struct null_tree_node_update
struct null_trie_node_update
struct ov_tree_tag
Ordered-vector tree.
struct pairing_heap_tag
Pairing-heap.
struct pat_trie_tag
PATRICIA trie.
struct point_invalidation_guarantee
class priority_queue
struct priority_queue_tag
Basic priority-queue.
class quadratic_probe_fn
struct range_invalidation_guarantee
struct rb_tree_tag
Red-black tree.
struct rc_binomial_heap_tag
Redundant-counter binomial-heap.
struct resize_error
struct sequence_tag
Basic sequence.
struct splay_tree_tag
Splay tree.
struct string_tag
Basic string container, inclusive of strings, ropes, etc.
struct string_trie_e_access_traits
struct thin_heap_tag
Thin heap.
class tree
A concrete basic tree-based associative container.
class tree_order_statistics_node_update
struct tree_tag
tree.
class trie
A concrete basic trie-based associative container.
class trie_order_statistics_node_update
class trie_prefix_search_node_update
struct trie_tag
trie.
struct trivial_iterator_tag
Typedefs
typedef void trivial_iterator_difference_type
Functions
void __throw_container_error (void)
void __throw_insert_error (void)
void __throw_join_error (void)
void __throw_resize_error (void)
Detailed Description
This implementation loosely borrows ideas from: 1) Fast Mergeable Integer Maps, Okasaki, Gill 1998 2) Ptset: Sets of integers implemented as Patricia trees, Jean-Christophe Filliatr, 2000.
GNU extensions for policy-based data structures for public use.
Typedef Documentation
trivial_iterator_difference_type
typedef void __gnu_pbds::trivial_iterator_difference_type
Definition at line 60 of file tag_and_trait.hpp.
Function Documentation
__throw_container_error()
void __gnu_pbds::__throw_container_error (void) inline
Definition at line 88 of file exception.hpp.
   { std::abort(); }
References abort().
__throw_insert_error()
void __gnu_pbds::__throw_insert_error (void) inline
Definition at line 92 of file exception.hpp.
   { std::abort(); }
References abort().
__throw_join_error()
void __gnu_pbds::__throw_join_error (void) inline
Definition at line 96 of file exception.hpp.
   { std::abort(); }
References abort().
__throw_resize_error()
void __gnu_pbds::__throw_resize_error (void) inline
Definition at line 100 of file exception.hpp.
   { std::abort(); }
References abort().