ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/i686-pc-mingw32/bits/gthr-posix.h File Reference
gthr-posix.h File Reference
#include <pthread.h>
#include <unistd.h>
Macros
#define __GTHREAD_COND_INIT PTHREAD_COND_INITIALIZER
#define __GTHREAD_HAS_COND 1
#define __GTHREAD_MUTEX_INIT PTHREAD_MUTEX_INITIALIZER
#define __GTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
#define __GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION __gthread_recursive_mutex_init_function
#define __GTHREAD_TIME_INIT {0,0}
#define __GTHREADS 1
#define __GTHREADS_CXX0X 1
#define __gthrw(name) __gthrw2(__gthrw_ ## name,name,name)
#define __gthrw2(name, name2, type)
#define __gthrw_(name) name
Typedefs
typedef pthread_cond_t __gthread_cond_t
typedef pthread_key_t __gthread_key_t
typedef pthread_mutex_t __gthread_mutex_t
typedef pthread_once_t __gthread_once_t
typedef pthread_mutex_t __gthread_recursive_mutex_t
typedef pthread_t __gthread_t
typedef struct timespec __gthread_time_t
Functions
static int __gthread_cond_broadcast (__gthread_cond_t *__cond)
static int __gthread_cond_destroy (__gthread_cond_t *__cond)
static int __gthread_cond_signal (__gthread_cond_t *__cond)
static int __gthread_cond_timedwait (__gthread_cond_t *__cond, __gthread_mutex_t *__mutex, const __gthread_time_t *__abs_timeout)
static int __gthread_cond_timedwait_recursive (__gthread_cond_t *__cond, __gthread_recursive_mutex_t *__mutex, const __gthread_time_t *__abs_timeout)
static int __gthread_cond_wait (__gthread_cond_t *__cond, __gthread_mutex_t *__mutex)
static int __gthread_cond_wait_recursive (__gthread_cond_t *__cond, __gthread_recursive_mutex_t *__mutex)
static int __gthread_create (__gthread_t *__threadid, void *(*__func)(void *), void *__args)
static int __gthread_detach (__gthread_t __threadid)
static int __gthread_equal (__gthread_t __t1, __gthread_t __t2)
static void * __gthread_getspecific (__gthread_key_t __key)
static int __gthread_join (__gthread_t __threadid, void **__value_ptr)
static int __gthread_key_create (__gthread_key_t *__key, void(*__dtor)(void *))
static int __gthread_key_delete (__gthread_key_t __key)
static int __gthread_mutex_destroy (__gthread_mutex_t *__mutex)
static int __gthread_mutex_lock (__gthread_mutex_t *__mutex)
static int __gthread_mutex_trylock (__gthread_mutex_t *__mutex)
static int __gthread_mutex_unlock (__gthread_mutex_t *__mutex)
static int __gthread_once (__gthread_once_t *__once, void(*__func)(void))
static int __gthread_recursive_mutex_init_function (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_lock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_trylock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_unlock (__gthread_recursive_mutex_t *__mutex)
static __gthread_t __gthread_self (void)
static int __gthread_setspecific (__gthread_key_t __key, const void *__ptr)
static int __gthread_yield (void)
__gthrw (pthread_once) __gthrw(pthread_getspecific) __gthrw(pthread_setspecific) __gthrw(pthread_create) __gthrw(pthread_join) __gthrw(pthread_equal) __gthrw(pthread_self) __gthrw(pthread_detach) __gthrw(pthread_cancel) __gthrw(sched_yield) __gthrw(pthread_mutex_lock) __gthrw(pthread_mutex_trylock) __gthrw(pthread_mutex_unlock) __gthrw(pthread_mutex_init) __gthrw(pthread_mutex_destroy) __gthrw(pthread_cond_broadcast) __gthrw(pthread_cond_signal) __gthrw(pthread_cond_wait) __gthrw(pthread_cond_timedwait) __gthrw(pthread_cond_destroy) __gthrw(pthread_key_create) __gthrw(pthread_key_delete) __gthrw(pthread_mutexattr_init) __gthrw(pthread_mutexattr_settype) __gthrw(pthread_mutexattr_destroy) static inline int __gthread_active_p(void)
Macro Definition Documentation
__GTHREAD_COND_INIT
#define __GTHREAD_COND_INIT PTHREAD_COND_INITIALIZER
Definition at line 65 of file gthr-posix.h.
__GTHREAD_HAS_COND
#define __GTHREAD_HAS_COND 1
Definition at line 54 of file gthr-posix.h.
__GTHREAD_MUTEX_INIT
#define __GTHREAD_MUTEX_INIT PTHREAD_MUTEX_INITIALIZER
Definition at line 56 of file gthr-posix.h.
__GTHREAD_ONCE_INIT
#define __GTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
Definition at line 57 of file gthr-posix.h.
__GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION
#define __GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION __gthread_recursive_mutex_init_function
Definition at line 63 of file gthr-posix.h.
__GTHREAD_TIME_INIT
#define __GTHREAD_TIME_INIT {0,0}
Definition at line 66 of file gthr-posix.h.
__GTHREADS
#define __GTHREADS 1
Definition at line 33 of file gthr-posix.h.
__GTHREADS_CXX0X
#define __GTHREADS_CXX0X 1
Definition at line 34 of file gthr-posix.h.
__gthrw
#define __gthrw (name) __gthrw2(__gthrw_ ## name,name,name)
Definition at line 82 of file gthr-posix.h.
__gthrw2
#define __gthrw2 (name, name2, type)
Definition at line 77 of file gthr-posix.h.
__gthrw_
#define __gthrw_ (name) name
Definition at line 78 of file gthr-posix.h.
Typedef Documentation
__gthread_cond_t
typedef pthread_cond_t __gthread_cond_t
Definition at line 49 of file gthr-posix.h.
__gthread_key_t
typedef pthread_key_t __gthread_key_t
Definition at line 45 of file gthr-posix.h.
__gthread_mutex_t
typedef pthread_mutex_t __gthread_mutex_t
Definition at line 47 of file gthr-posix.h.
__gthread_once_t
typedef pthread_once_t __gthread_once_t
Definition at line 46 of file gthr-posix.h.
__gthread_recursive_mutex_t
typedef pthread_mutex_t __gthread_recursive_mutex_t
Definition at line 48 of file gthr-posix.h.
__gthread_t
typedef pthread_t __gthread_t
Definition at line 44 of file gthr-posix.h.
__gthread_time_t
typedef struct timespec __gthread_time_t
Definition at line 50 of file gthr-posix.h.
Function Documentation
__gthread_cond_broadcast()
static int __gthread_cond_broadcast (__gthread_cond_t * __cond) inline static
Definition at line 832 of file gthr-posix.h.
 {
   return __gthrw_(pthread_cond_broadcast) (__cond);
 }
References __gthrw_.
Referenced by _GLIBCXX_VISIBILITY().
__gthread_cond_destroy()
static int __gthread_cond_destroy (__gthread_cond_t * __cond) inline static
Definition at line 872 of file gthr-posix.h.
 {
   return __gthrw_(pthread_cond_destroy) (__cond);
 }
References __gthrw_.
Referenced by _GLIBCXX_VISIBILITY().
__gthread_cond_signal()
static int __gthread_cond_signal (__gthread_cond_t * __cond) inline static
Definition at line 838 of file gthr-posix.h.
 {
   return __gthrw_(pthread_cond_signal) (__cond);
 }
References __gthrw_.
__gthread_cond_timedwait()
static int __gthread_cond_timedwait (__gthread_cond_t * __cond, __gthread_mutex_t * __mutex, const __gthread_time_t * __abs_timeout) inline static
Definition at line 850 of file gthr-posix.h.
 {
   return __gthrw_(pthread_cond_timedwait) (__cond, __mutex, __abs_timeout);
 }
References __gthrw_.
Referenced by __gthread_cond_timedwait_recursive().
__gthread_cond_timedwait_recursive()
static int __gthread_cond_timedwait_recursive (__gthread_cond_t * __cond, __gthread_recursive_mutex_t * __mutex, const __gthread_time_t * __abs_timeout) inline static
Definition at line 864 of file gthr-posix.h.
 {
   return __gthread_cond_timedwait (__cond, __mutex, __abs_timeout);
 }
References __gthread_cond_timedwait().
__gthread_cond_wait()
static int __gthread_cond_wait (__gthread_cond_t * __cond, __gthread_mutex_t * __mutex) inline static
Definition at line 844 of file gthr-posix.h.
 {
   return __gthrw_(pthread_cond_wait) (__cond, __mutex);
 }
References __gthrw_.
Referenced by __gthread_cond_wait_recursive(), and _GLIBCXX_VISIBILITY().
__gthread_cond_wait_recursive()
static int __gthread_cond_wait_recursive (__gthread_cond_t * __cond, __gthread_recursive_mutex_t * __mutex) inline static
Definition at line 857 of file gthr-posix.h.
 {
   return __gthread_cond_wait (__cond, __mutex);
 }
References __gthread_cond_wait().
Referenced by _GLIBCXX_VISIBILITY().
__gthread_create()
static int __gthread_create (__gthread_t * __threadid, void *(*)(void *) __func, void * __args) inline static
Definition at line 660 of file gthr-posix.h.
 {
   return __gthrw_(pthread_create) (__threadid, NULL, __func, __args);
 }
References __gthrw_, and NULL.
__gthread_detach()
static int __gthread_detach (__gthread_t __threadid) inline static
Definition at line 673 of file gthr-posix.h.
 {
   return __gthrw_(pthread_detach) (__threadid);
 }
References __gthrw_.
__gthread_equal()
static int __gthread_equal (__gthread_t __t1, __gthread_t __t2) inline static
Definition at line 679 of file gthr-posix.h.
 {
   return __gthrw_(pthread_equal) (__t1, __t2);
 }
References __gthrw_.
__gthread_getspecific()
static void* __gthread_getspecific (__gthread_key_t __key) inline static
Definition at line 718 of file gthr-posix.h.
 {
   return __gthrw_(pthread_getspecific) (__key);
 }
References __gthrw_.
__gthread_join()
static int __gthread_join (__gthread_t __threadid, void ** __value_ptr) inline static
Definition at line 667 of file gthr-posix.h.
 {
   return __gthrw_(pthread_join) (__threadid, __value_ptr);
 }
References __gthrw_.
__gthread_key_create()
static int __gthread_key_create (__gthread_key_t * __key, void(*)(void *) __dtor) inline static
Definition at line 706 of file gthr-posix.h.
 {
   return __gthrw_(pthread_key_create) (__key, __dtor);
 }
References __gthrw_.
__gthread_key_delete()
static int __gthread_key_delete (__gthread_key_t __key) inline static
Definition at line 712 of file gthr-posix.h.
 {
   return __gthrw_(pthread_key_delete) (__key);
 }
References __gthrw_.
__gthread_mutex_destroy()
static int __gthread_mutex_destroy (__gthread_mutex_t * __mutex) inline static
Definition at line 730 of file gthr-posix.h.
 {
   if (__gthread_active_p ())
     return __gthrw_(pthread_mutex_destroy) (__mutex);
   else
     return 0;
 }
References __gthread_active_p(), and __gthrw_.
__gthread_mutex_lock()
static int __gthread_mutex_lock (__gthread_mutex_t * __mutex) inline static
Definition at line 739 of file gthr-posix.h.
 {
   if (__gthread_active_p ())
     return __gthrw_(pthread_mutex_lock) (__mutex);
   else
     return 0;
 }
References __gthread_active_p(), and __gthrw_.
Referenced by __gthread_recursive_mutex_lock().
__gthread_mutex_trylock()
static int __gthread_mutex_trylock (__gthread_mutex_t * __mutex) inline static
Definition at line 748 of file gthr-posix.h.
 {
   if (__gthread_active_p ())
     return __gthrw_(pthread_mutex_trylock) (__mutex);
   else
     return 0;
 }
References __gthread_active_p(), and __gthrw_.
Referenced by __gthread_recursive_mutex_trylock().
__gthread_mutex_unlock()
static int __gthread_mutex_unlock (__gthread_mutex_t * __mutex) inline static
Definition at line 771 of file gthr-posix.h.
 {
   if (__gthread_active_p ())
     return __gthrw_(pthread_mutex_unlock) (__mutex);
   else
     return 0;
 }
References __gthread_active_p(), and __gthrw_.
Referenced by __gthread_recursive_mutex_unlock().
__gthread_once()
static int __gthread_once (__gthread_once_t * __once, void(*)(void) __func) inline static
Definition at line 697 of file gthr-posix.h.
 {
   if (__gthread_active_p ())
     return __gthrw_(pthread_once) (__once, __func);
   else
     return -1;
 }
References __gthread_active_p(), and __gthrw_.
__gthread_recursive_mutex_init_function()
static int __gthread_recursive_mutex_init_function (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 781 of file gthr-posix.h.
 {
   if (__gthread_active_p ())
     {
       pthread_mutexattr_t __attr;
       int __r;
       __r = __gthrw_(pthread_mutexattr_init) (&__attr);
       if (!__r)
     __r = __gthrw_(pthread_mutexattr_settype) (&__attr,
                            PTHREAD_MUTEX_RECURSIVE);
       if (!__r)
     __r = __gthrw_(pthread_mutex_init) (__mutex, &__attr);
       if (!__r)
     __r = __gthrw_(pthread_mutexattr_destroy) (&__attr);
       return __r;
     }
   return 0;
 }
References __gthread_active_p(), and __gthrw_.
__gthread_recursive_mutex_lock()
static int __gthread_recursive_mutex_lock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 803 of file gthr-posix.h.
 {
   return __gthread_mutex_lock (__mutex);
 }
References __gthread_mutex_lock().
__gthread_recursive_mutex_trylock()
static int __gthread_recursive_mutex_trylock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 809 of file gthr-posix.h.
 {
   return __gthread_mutex_trylock (__mutex);
 }
References __gthread_mutex_trylock().
__gthread_recursive_mutex_unlock()
static int __gthread_recursive_mutex_unlock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 826 of file gthr-posix.h.
 {
   return __gthread_mutex_unlock (__mutex);
 }
References __gthread_mutex_unlock().
__gthread_self()
static __gthread_t __gthread_self (void) inline static
Definition at line 685 of file gthr-posix.h.
 {
   return __gthrw_(pthread_self) ();
 }
References __gthrw_.
__gthread_setspecific()
static int __gthread_setspecific (__gthread_key_t __key, const void * __ptr) inline static
Definition at line 724 of file gthr-posix.h.
 {
   return __gthrw_(pthread_setspecific) (__key, __ptr);
 }
References __gthrw_.
__gthread_yield()
static int __gthread_yield (void) inline static
Definition at line 691 of file gthr-posix.h.
 {
   return __gthrw_(sched_yield) ();
 }
References __gthrw_.
__gthrw()
__gthrw (pthread_once)
Definition at line 118 of file gthr-posix.h.
 {
   __gthread_active = 1;
 }
 static inline int
 __gthread_active_p (void)
 {
   static pthread_mutex_t __gthread_active_mutex = PTHREAD_MUTEX_INITIALIZER;
   static pthread_once_t __gthread_active_once = PTHREAD_ONCE_INIT;
   /* Avoid reading __gthread_active twice on the main code path.  */
   int __gthread_active_latest_value = __gthread_active;
   /* This test is not protected to avoid taking a lock on the main code
      path so every update of __gthread_active in a threaded program must
      be atomic with regard to the result of the test.  */
   if (__builtin_expect (__gthread_active_latest_value < 0, 0))
     {
       if (__gthrw_(pthread_once))
     {
       /* If this really is a threaded program, then we must ensure that
          __gthread_active has been set to 1 before exiting this block.  */
       __gthrw_(pthread_mutex_lock) (&__gthread_active_mutex);
       __gthrw_(pthread_once) (&__gthread_active_once, __gthread_trigger);
       __gthrw_(pthread_mutex_unlock) (&__gthread_active_mutex);
     }
       /* Make sure we'll never enter this block again.  */
       if (__gthread_active < 0)
     __gthread_active = 0;
       __gthread_active_latest_value = __gthread_active;
     }
   return __gthread_active_latest_value != 0;
 }
 #else /* neither FreeBSD nor Solaris */
 static inline int
 __gthread_active_p (void)
 {
   static void *const __gthread_active_ptr
     = __extension__ (void *) &__gthrw_(
 /* Android's C library does not provide pthread_cancel, check for
    `pthread_create' instead.  */
 #ifndef __BIONIC__
                        pthread_cancel
 #else
                        pthread_create
 #endif
                        );
   return __gthread_active_ptr != 0;
 }
 #endif /* FreeBSD or Solaris */
 #else /* not __GXX_WEAK__ */
 /* Similar to Solaris, HP-UX 11 for PA-RISC provides stubs for pthread
    calls in shared flavors of the HP-UX C library.  Most of the stubs
    have no functionality.  The details are described in the "libc cumulative
    patch" for each subversion of HP-UX 11.  There are two special interfaces
    provided for checking whether an application is linked to a shared pthread
    library or not.  However, these interfaces aren't available in early
    libpthread libraries.  We also need a test that works for archive
    libraries.  We can't use pthread_once as some libc versions call the
    init function.  We also can't use pthread_create or pthread_attr_init
    as these create a thread and thereby prevent changing the default stack
    size.  The function pthread_default_stacksize_np is available in both
    the archive and shared versions of libpthread.   It can be used to
    determine the default pthread stack size.  There is a stub in some
    shared libc versions which returns a zero size if pthreads are not
    active.  We provide an equivalent stub to handle cases where libc
    doesn't provide one.  */
 #if defined(__hppa__) && defined(__hpux__)
 static volatile int __gthread_active = -1;
 static inline int
 __gthread_active_p (void)
 {
   /* Avoid reading __gthread_active twice on the main code path.  */
   int __gthread_active_latest_value = __gthread_active;
   size_t __s;
   if (__builtin_expect (__gthread_active_latest_value < 0, 0))
     {
       pthread_default_stacksize_np (0, &__s);
       __gthread_active = __s ? 1 : 0;
       __gthread_active_latest_value = __gthread_active;
     }
   return __gthread_active_latest_value != 0;
 }
 #else /* not hppa-hpux */
 static inline int
 __gthread_active_p (void)
 {
   return 1;
 }