ZEQ2-Lite: Shared/cm_local.h File Reference
cm_local.h File Reference
#include "q_shared.h"
#include "qcommon.h"
#include "cm_polylib.h"
Data Structures
struct cArea_t
struct cbrush_t
struct cbrushside_t
struct cLeaf_t
struct clipMap_t
struct cmodel_s
struct cNode_t
struct cPatch_t
struct leafList_s
struct sphere_t
struct traceWork_t
Macros
#define BOX_MODEL_HANDLE 255
#define CAPSULE_MODEL_HANDLE 254
#define MAX_SUBMODELS 256
#define SURFACE_CLIP_EPSILON (0.125)
Functions
qboolean CM_BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
qboolean CM_BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t point)
int CM_BoxBrushes (const vec3_t mins, const vec3_t maxs, cbrush_t **list, int listsize)
void CM_BoxLeafnums_r (leafList_t *ll, int nodenum)
void CM_ClearLevelPatches (void)
cmodel_t * CM_ClipHandleToModel (clipHandle_t handle)
struct patchCollide_s * CM_GeneratePatchCollide (int width, int height, vec3_t *points)
qboolean CM_PositionTestInPatchCollide (traceWork_t *tw, const struct patchCollide_s *pc)
void CM_StoreBrushes (leafList_t *ll, int nodenum)
void CM_StoreLeafs (leafList_t *ll, int nodenum)
void CM_TraceThroughPatchCollide (traceWork_t *tw, const struct patchCollide_s *pc)
Variables
int c_brush_traces
int c_patch_traces
int c_pointcontents
int c_traces
clipMap_t cm
cvar_t * cm_noAreas
cvar_t * cm_noCurves
cvar_t * cm_playerCurveClip
Macro Definition Documentation
BOX_MODEL_HANDLE
#define BOX_MODEL_HANDLE 255
Definition at line 28 of file cm_local.h.
CAPSULE_MODEL_HANDLE
#define CAPSULE_MODEL_HANDLE 254
Definition at line 29 of file cm_local.h.
MAX_SUBMODELS
#define MAX_SUBMODELS 256
Definition at line 27 of file cm_local.h.
SURFACE_CLIP_EPSILON
#define SURFACE_CLIP_EPSILON (0.125)
Definition at line 134 of file cm_local.h.
Function Documentation
CM_BoundsIntersect()
qboolean CM_BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
Definition at line 488 of file cm_test.c.
 {
     if (maxs[0] < mins2[0] - SURFACE_CLIP_EPSILON ||
         maxs[1] < mins2[1] - SURFACE_CLIP_EPSILON ||
         maxs[2] < mins2[2] - SURFACE_CLIP_EPSILON ||
         mins[0] > maxs2[0] + SURFACE_CLIP_EPSILON ||
         mins[1] > maxs2[1] + SURFACE_CLIP_EPSILON ||
         mins[2] > maxs2[2] + SURFACE_CLIP_EPSILON)
     {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, qtrue, and SURFACE_CLIP_EPSILON.
Referenced by CM_TraceThroughLeaf(), and CM_TraceThroughPatchCollide().
CM_BoundsIntersectPoint()
qboolean CM_BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t point)
Definition at line 508 of file cm_test.c.
 {
     if (maxs[0] < point[0] - SURFACE_CLIP_EPSILON ||
         maxs[1] < point[1] - SURFACE_CLIP_EPSILON ||
         maxs[2] < point[2] - SURFACE_CLIP_EPSILON ||
         mins[0] > point[0] + SURFACE_CLIP_EPSILON ||
         mins[1] > point[1] + SURFACE_CLIP_EPSILON ||
         mins[2] > point[2] + SURFACE_CLIP_EPSILON)
     {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, qtrue, and SURFACE_CLIP_EPSILON.
Referenced by CM_PointContents().
CM_BoxBrushes()
int CM_BoxBrushes (const vec3_t mins, const vec3_t maxs, cbrush_t ** list, int listsize)
Definition at line 197 of file cm_test.c.
{
     leafList_t  ll;
     cm.checkcount++;
     VectorCopy( mins, ll.bounds[0] );
     VectorCopy( maxs, ll.bounds[1] );
     ll.count = 0;
     ll.maxcount = listsize;
     ll.list = (void *)list;
     ll.storeLeafs = CM_StoreBrushes;
     ll.lastLeaf = 0;
     ll.overflowed = qfalse;
     CM_BoxLeafnums_r( &ll, 0 );
     return ll.count;
 }
References clipMap_t::checkcount, cm, CM_BoxLeafnums_r(), CM_StoreBrushes(), qfalse, and VectorCopy.
CM_BoxLeafnums_r()
void CM_BoxLeafnums_r (leafList_t * ll, int nodenum)
Definition at line 140 of file cm_test.c.
{
     cplane_t    *plane;
     cNode_t     *node;
     int         s;
     while (1) {
         if (nodenum < 0) {
             ll->storeLeafs( ll, nodenum );
             return;
         }
         node = &cm.nodes[nodenum];
         plane = node->plane;
         s = BoxOnPlaneSide( ll->bounds[0], ll->bounds[1], plane );
         if (s == 1) {
             nodenum = node->children[0];
         } else if (s == 2) {
             nodenum = node->children[1];
         } else {
             // go down both
             CM_BoxLeafnums_r( ll, node->children[0] );
             nodenum = node->children[1];
         }
     }
 }
References BoxOnPlaneSide(), cm, node(), and clipMap_t::nodes.
Referenced by CM_BoxBrushes(), CM_BoxLeafnums(), and CM_PositionTest().
CM_ClearLevelPatches()
void CM_ClearLevelPatches (void)
Definition at line 97 of file cm_patch.c.
{
     debugPatchCollide = NULL;
     debugFacet = NULL;
 }
References debugFacet, debugPatchCollide, and NULL.
Referenced by CM_ClearMap(), and CM_LoadMap().
CM_ClipHandleToModel()
cmodel_t* CM_ClipHandleToModel (clipHandle_t handle)
Definition at line 678 of file cm_load.c.
{
     if ( handle < 0 ) {
         Com_Error( ERR_DROP, "CM_ClipHandleToModel: bad handle %i", handle );
     }
     if ( handle < cm.numSubModels ) {
         return &cm.cmodels[handle];
     }
     if ( handle == BOX_MODEL_HANDLE ) {
         return &box_model;
     }
     if ( handle < MAX_SUBMODELS ) {
         Com_Error( ERR_DROP, "CM_ClipHandleToModel: bad handle %i < %i < %i",
             cm.numSubModels, handle, MAX_SUBMODELS );
     }
     Com_Error( ERR_DROP, "CM_ClipHandleToModel: bad handle %i", handle + MAX_SUBMODELS );
     return NULL;
 }
References box_model, BOX_MODEL_HANDLE, cm, clipMap_t::cmodels, Com_Error(), ERR_DROP, MAX_SUBMODELS, NULL, and clipMap_t::numSubModels.
Referenced by CM_ModelBounds(), CM_PointContents(), CM_TestBoundingBoxInCapsule(), CM_Trace(), and CM_TraceBoundingBoxThroughCapsule().
CM_GeneratePatchCollide()
struct patchCollide_s* CM_GeneratePatchCollide (int width, int height, vec3_t * points)
Definition at line 1149 of file cm_patch.c.
{
     patchCollide_t  *pf;
     cGrid_t         grid;
     int             i, j;
     if ( width <= 2 || height <= 2 || !points ) {
         Com_Error( ERR_DROP, "CM_GeneratePatchFacets: bad parameters: (%i, %i, %p)",
             width, height, (void *)points );
     }
     if ( !(width & 1) || !(height & 1) ) {
         Com_Error( ERR_DROP, "CM_GeneratePatchFacets: even sizes are invalid for quadratic meshes" );
     }
     if ( width > MAX_GRID_SIZE || height > MAX_GRID_SIZE ) {
         Com_Error( ERR_DROP, "CM_GeneratePatchFacets: source is > MAX_GRID_SIZE" );
     }
     // build a grid
     grid.width = width;
     grid.height = height;
     grid.wrapWidth = qfalse;
     grid.wrapHeight = qfalse;
     for ( i = 0 ; i < width ; i++ ) {
         for ( j = 0 ; j < height ; j++ ) {
             VectorCopy( points[j*width + i], grid.points[i][j] );
         }
     }
     // subdivide the grid
     CM_SetGridWrapWidth( &grid );
     CM_SubdivideGridColumns( &grid );
     CM_RemoveDegenerateColumns( &grid );
     CM_TransposeGrid( &grid );
     CM_SetGridWrapWidth( &grid );
     CM_SubdivideGridColumns( &grid );
     CM_RemoveDegenerateColumns( &grid );
     // we now have a grid of points exactly on the curve
     // the aproximate surface defined by these points will be
     // collided against
     pf = Hunk_Alloc( sizeof( *pf ), h_high );
     ClearBounds( pf->bounds[0], pf->bounds[1] );
     for ( i = 0 ; i < grid.width ; i++ ) {
         for ( j = 0 ; j < grid.height ; j++ ) {
             AddPointToBounds( grid.points[i][j], pf->bounds[0], pf->bounds[1] );
         }
     }
     c_totalPatchBlocks += ( grid.width - 1 ) * ( grid.height - 1 );
     // generate a bsp tree for the surface
     CM_PatchCollideFromGrid( &grid, pf );
     // expand by one unit for epsilon purposes
     pf->bounds[0][0] -= 1;
     pf->bounds[0][1] -= 1;
     pf->bounds[0][2] -= 1;
     pf->bounds[1][0] += 1;
     pf->bounds[1][1] += 1;
     pf->bounds[1][2] += 1;
     return pf;
 }
Referenced by CMod_LoadPatches().
CM_PositionTestInPatchCollide()
qboolean CM_PositionTestInPatchCollide (traceWork_t * tw, const struct patchCollide_s * pc)
Definition at line 1519 of file cm_patch.c.
{
     int i, j;
     float offset, t;
     patchPlane_t *planes;
     facet_t *facet;
     float plane[4];
     vec3_t startp;
     if (tw->isPoint) {
         return qfalse;
     }
     //
     facet = pc->facets;
     for ( i = 0 ; i < pc->numFacets ; i++, facet++ ) {
         planes = &pc->planes[ facet->surfacePlane ];
         VectorCopy(planes->plane, plane);
         plane[3] = planes->plane[3];
         if ( tw->sphere.use ) {
             // adjust the plane distance apropriately for radius
             plane[3] += tw->sphere.radius;
             // find the closest point on the capsule to the plane
             t = DotProduct( plane, tw->sphere.offset );
             if ( t > 0 ) {
                 VectorSubtract( tw->start, tw->sphere.offset, startp );
             }
             else {
                 VectorAdd( tw->start, tw->sphere.offset, startp );
             }
         }
         else {
             offset = DotProduct( tw->offsets[ planes->signbits ], plane);
             plane[3] -= offset;
             VectorCopy( tw->start, startp );
         }
         if ( DotProduct( plane, startp ) - plane[3] > 0.0f ) {
             continue;
         }
         for ( j = 0; j < facet->numBorders; j++ ) {
             planes = &pc->planes[ facet->borderPlanes[j] ];
             if (facet->borderInward[j]) {
                 VectorNegate(planes->plane, plane);
                 plane[3] = -planes->plane[3];
             }
             else {
                 VectorCopy(planes->plane, plane);
                 plane[3] = planes->plane[3];
             }
             if ( tw->sphere.use ) {
                 // adjust the plane distance apropriately for radius
                 plane[3] += tw->sphere.radius;
                 // find the closest point on the capsule to the plane
                 t = DotProduct( plane, tw->sphere.offset );
                 if ( t > 0.0f ) {
                     VectorSubtract( tw->start, tw->sphere.offset, startp );
                 }
                 else {
                     VectorAdd( tw->start, tw->sphere.offset, startp );
                 }
             }
             else {
                 // NOTE: this works even though the plane might be flipped because the bbox is centered
                 offset = DotProduct( tw->offsets[ planes->signbits ], plane);
                 plane[3] += fabs(offset);
                 VectorCopy( tw->start, startp );
             }
             if ( DotProduct( plane, startp ) - plane[3] > 0.0f ) {
                 break;
             }
         }
         if (j < facet->numBorders) {
             continue;
         }
         // inside this patch facet
         return qtrue;
     }
     return qfalse;
 }
References facet_t::borderInward, facet_t::borderPlanes, DotProduct, fabs(), traceWork_t::isPoint, facet_t::numBorders, sphere_t::offset, traceWork_t::offsets, pc, patchPlane_t::plane, planes, qfalse, qtrue, sphere_t::radius, patchPlane_t::signbits, traceWork_t::sphere, traceWork_t::start, facet_t::surfacePlane, sphere_t::use, VectorAdd, VectorCopy, VectorNegate, and VectorSubtract.
Referenced by CM_TestInLeaf().
CM_StoreBrushes()
void CM_StoreBrushes (leafList_t * ll, int nodenum)
Definition at line 90 of file cm_test.c.
{
     int         i, k;
     int         leafnum;
     int         brushnum;
     cLeaf_t     *leaf;
     cbrush_t    *b;
     leafnum = -1 - nodenum;
     leaf = &cm.leafs[leafnum];
     for ( k = 0 ; k < leaf->numLeafBrushes ; k++ ) {
         brushnum = cm.leafbrushes[leaf->firstLeafBrush+k];
         b = &cm.brushes[brushnum];
         if ( b->checkcount == cm.checkcount ) {
             continue;   // already checked this brush in another leaf
         }
         b->checkcount = cm.checkcount;
         for ( i = 0 ; i < 3 ; i++ ) {
             if ( b->bounds[0][i] >= ll->bounds[1][i] || b->bounds[1][i] <= ll->bounds[0][i] ) {
                 break;
             }
         }
         if ( i != 3 ) {
             continue;
         }
         if ( ll->count >= ll->maxcount) {
             ll->overflowed = qtrue;
             return;
         }
         ((cbrush_t **)ll->list)[ ll->count++ ] = b;
     }
 #if 0
     // store patches?
     for ( k = 0 ; k < leaf->numLeafSurfaces ; k++ ) {
         patch = cm.surfaces[ cm.leafsurfaces[ leaf->firstleafsurface + k ] ];
         if ( !patch ) {
             continue;
         }
     }
 #endif
 }
References clipMap_t::brushes, cbrush_t::checkcount, clipMap_t::checkcount, cm, leaf, clipMap_t::leafbrushes, clipMap_t::leafs, clipMap_t::leafsurfaces, qtrue, and clipMap_t::surfaces.
Referenced by CM_BoxBrushes().
CM_StoreLeafs()
void CM_StoreLeafs (leafList_t * ll, int nodenum)
Definition at line 73 of file cm_test.c.
{
     int     leafNum;
     leafNum = -1 - nodenum;
     // store the lastLeaf even if the list is overflowed
     if ( cm.leafs[ leafNum ].cluster != -1 ) {
         ll->lastLeaf = leafNum;
     }
     if ( ll->count >= ll->maxcount) {
         ll->overflowed = qtrue;
         return;
     }
     ll->list[ ll->count++ ] = leafNum;
 }
References cLeaf_t::cluster, cm, clipMap_t::leafs, and qtrue.
Referenced by CM_BoxLeafnums(), and CM_PositionTest().
CM_TraceThroughPatchCollide()
void CM_TraceThroughPatchCollide (traceWork_t * tw, const struct patchCollide_s * pc)
Definition at line 1378 of file cm_patch.c.
{
     int i, j, hit, hitnum;
     float offset, enterFrac, leaveFrac, t;
     patchPlane_t *planes;
     facet_t *facet;
     float plane[4] = {0, 0, 0, 0}, bestplane[4] = {0, 0, 0, 0};
     vec3_t startp, endp;
 #ifndef BSPC
     static cvar_t *cv;
 #endif //BSPC
     if ( !CM_BoundsIntersect( tw->bounds[0], tw->bounds[1],
                 pc->bounds[0], pc->bounds[1] ) ) {
         return;
     }
     if (tw->isPoint) {
         CM_TracePointThroughPatchCollide( tw, pc );
         return;
     }
     facet = pc->facets;
     for ( i = 0 ; i < pc->numFacets ; i++, facet++ ) {
         enterFrac = -1.0;
         leaveFrac = 1.0;
         hitnum = -1;
         //
         planes = &pc->planes[ facet->surfacePlane ];
         VectorCopy(planes->plane, plane);
         plane[3] = planes->plane[3];
         if ( tw->sphere.use ) {
             // adjust the plane distance apropriately for radius
             plane[3] += tw->sphere.radius;
             // find the closest point on the capsule to the plane
             t = DotProduct( plane, tw->sphere.offset );
             if ( t > 0.0f ) {
                 VectorSubtract( tw->start, tw->sphere.offset, startp );
                 VectorSubtract( tw->end, tw->sphere.offset, endp );
             }
             else {
                 VectorAdd( tw->start, tw->sphere.offset, startp );
                 VectorAdd( tw->end, tw->sphere.offset, endp );
             }
         }
         else {
             offset = DotProduct( tw->offsets[ planes->signbits ], plane);
             plane[3] -= offset;
             VectorCopy( tw->start, startp );
             VectorCopy( tw->end, endp );
         }
         if (!CM_CheckFacetPlane(plane, startp, endp, &enterFrac, &leaveFrac, &hit)) {
             continue;
         }
         if (hit) {
             Vector4Copy(plane, bestplane);
         }
         for ( j = 0; j < facet->numBorders; j++ ) {
             planes = &pc->planes[ facet->borderPlanes[j] ];
             if (facet->borderInward[j]) {
                 VectorNegate(planes->plane, plane);
                 plane[3] = -planes->plane[3];
             }
             else {
                 VectorCopy(planes->plane, plane);
                 plane[3] = planes->plane[3];
             }
             if ( tw->sphere.use ) {
                 // adjust the plane distance apropriately for radius
                 plane[3] += tw->sphere.radius;
                 // find the closest point on the capsule to the plane
                 t = DotProduct( plane, tw->sphere.offset );
                 if ( t > 0.0f ) {
                     VectorSubtract( tw->start, tw->sphere.offset, startp );
                     VectorSubtract( tw->end, tw->sphere.offset, endp );
                 }
                 else {
                     VectorAdd( tw->start, tw->sphere.offset, startp );
                     VectorAdd( tw->end, tw->sphere.offset, endp );
                 }
             }
             else {
                 // NOTE: this works even though the plane might be flipped because the bbox is centered
                 offset = DotProduct( tw->offsets[ planes->signbits ], plane);
                 plane[3] += fabs(offset);
                 VectorCopy( tw->start, startp );
                 VectorCopy( tw->end, endp );
             }
             if (!CM_CheckFacetPlane(plane, startp, endp, &enterFrac, &leaveFrac, &hit)) {
                 break;
             }
             if (hit) {
                 hitnum = j;
                 Vector4Copy(plane, bestplane);
             }
         }
         if (j < facet->numBorders) continue;
         //never clip against the back side
         if (hitnum == facet->numBorders - 1) continue;
         if (enterFrac < leaveFrac && enterFrac >= 0) {
             if (enterFrac < tw->trace.fraction) {
                 if (enterFrac < 0) {
                     enterFrac = 0;
                 }
 #ifndef BSPC
                 if (!cv) {
                     cv = Cvar_Get( "r_debugSurfaceUpdate", "1", 0 );
                 }
                 if (cv && cv->integer) {
                     debugPatchCollide = pc;
                     debugFacet = facet;
                 }
 #endif //BSPC
                 tw->trace.fraction = enterFrac;
                 VectorCopy( bestplane, tw->trace.plane.normal );
                 tw->trace.plane.dist = bestplane[3];
             }
         }
     }
 }
References facet_t::borderInward, facet_t::borderPlanes, traceWork_t::bounds, CM_BoundsIntersect(), CM_CheckFacetPlane(), CM_TracePointThroughPatchCollide(), Cvar_Get(), debugFacet, debugPatchCollide, DotProduct, traceWork_t::end, fabs(), trace_t::fraction, traceWork_t::isPoint, facet_t::numBorders, sphere_t::offset, traceWork_t::offsets, pc, patchPlane_t::plane, trace_t::plane, planes, sphere_t::radius, patchPlane_t::signbits, traceWork_t::sphere, traceWork_t::start, facet_t::surfacePlane, traceWork_t::trace, sphere_t::use, Vector4Copy, VectorAdd, VectorCopy, VectorNegate, and VectorSubtract.
Referenced by CM_TraceThroughPatch().
Variable Documentation
c_brush_traces
int c_brush_traces
Definition at line 138 of file cm_local.h.
c_patch_traces
int c_patch_traces
Definition at line 138 of file cm_local.h.
c_pointcontents
int c_pointcontents
Definition at line 55 of file cm_load.c.
Referenced by CM_PointLeafnum_r(), and Com_Frame().
c_traces
int c_traces
Definition at line 56 of file cm_load.c.
Referenced by CM_Trace(), and Com_Frame().
cm
clipMap_t cm
Definition at line 54 of file cm_load.c.
Referenced by CG_DrawHead(), CM_AdjustAreaPortalState(), CM_AreasConnected(), CM_BoxBrushes(), CM_BoxLeafnums(), CM_BoxLeafnums_r(), CM_ClearMap(), CM_ClipHandleToModel(), CM_ClusterPVS(), CM_EntityString(), CM_FloodArea_r(), CM_FloodAreaConnections(), CM_InitBoxHull(), CM_InlineModel(), CM_LeafArea(), CM_LeafCluster(), CM_LoadMap(), CM_NumClusters(), CM_NumInlineModels(), CM_PointContents(), CM_PointLeafnum(), CM_PointLeafnum_r(), CM_PositionTest(), CM_StoreBrushes(), CM_StoreLeafs(), CM_TestInLeaf(), CM_Trace(), CM_TraceThroughLeaf(), CM_TraceThroughTree(), CM_WriteAreaBits(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadEntityString(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadLeafSurfaces(), CMod_LoadNodes(), CMod_LoadPatches(), CMod_LoadPlanes(), CMod_LoadShaders(), CMod_LoadSubmodels(), and CMod_LoadVisibility().
cm_noAreas
cvar_t* cm_noAreas
Definition at line 62 of file cm_load.c.
Referenced by CM_AreasConnected(), CM_LoadMap(), and CM_WriteAreaBits().
cm_noCurves
cvar_t* cm_noCurves
Definition at line 63 of file cm_load.c.
Referenced by CM_LoadMap(), CM_TestInLeaf(), and CM_TraceThroughLeaf().
cm_playerCurveClip
cvar_t* cm_playerCurveClip
Definition at line 64 of file cm_load.c.
Referenced by CM_LoadMap(), and CM_TracePointThroughPatchCollide().