ZEQ2-Lite: __gnu_debug::_Safe_iterator< _Iterator, _Sequence > Class Template Reference
__gnu_debug::_Safe_iterator< _Iterator, _Sequence > Class Template Reference
Safe iterator wrapper.
#include <formatter.h>
Public Types
typedef _Traits::difference_type difference_type
typedef _Traits::iterator_category iterator_category
typedef _Iterator iterator_type
typedef _Traits::pointer pointer
typedef _Traits::reference reference
typedef _Traits::value_type value_type
Public Member Functions
_Safe_iterator ()
_Safe_iterator (const _Iterator &__i, const _Sequence *__seq)
Safe iterator construction from an unsafe iterator and its sequence.
_Safe_iterator (const _Safe_iterator &__x)
Copy construction.
template<typename _MutableIterator >
_Safe_iterator (const _Safe_iterator< _MutableIterator, typename __gnu_cxx::__enable_if<(std::__are_same< _MutableIterator, typename _Sequence::iterator::iterator_type >::__value), _Sequence >::__type > &__x)
Converting constructor from a mutable iterator to a constant iterator.
void _M_attach (_Safe_sequence_base *__seq)
Attach iterator to the given sequence.
void _M_attach_single (_Safe_sequence_base *__seq)
Likewise, but not thread-safe.
bool _M_before_dereferenceable () const
Is the iterator before a dereferenceable one?
bool _M_can_advance (const difference_type &__n) const
bool _M_decrementable () const
bool _M_dereferenceable () const
Is the iterator dereferenceable?
const _Sequence * _M_get_sequence () const
bool _M_incrementable () const
Is the iterator incrementable?
bool _M_is_before_begin () const
Is this iterator equal to the sequence's before_begin() iterator if any?
bool _M_is_begin () const
Is this iterator equal to the sequence's begin() iterator?
bool _M_is_end () const
Is this iterator equal to the sequence's end() iterator?
template<typename _Other >
bool _M_valid_range (const _Safe_iterator< _Other, _Sequence > &__rhs) const
_Iterator base () const
Return the underlying iterator.
operator _Iterator () const
Conversion to underlying non-debug iterator to allow better interaction with non-debug containers.
reference operator* () const
Iterator dereference.
_Safe_iterator operator+ (const difference_type &__n) const
_Safe_iterator & operator++ ()
Iterator preincrement.
_Safe_iterator operator++ (int)
Iterator postincrement.
_Safe_iterator & operator+= (const difference_type &__n)
_Safe_iterator operator- (const difference_type &__n) const
_Safe_iterator & operator-- ()
Iterator predecrement.
_Safe_iterator operator-- (int)
Iterator postdecrement.
_Safe_iterator & operator-= (const difference_type &__n)
pointer operator-> () const
Iterator dereference.
_Safe_iterator & operator= (const _Safe_iterator &__x)
Copy assignment.
reference operator[] (const difference_type &__n) const
Static Public Member Functions
template<typename _Iterator1 , typename _Iterator2 >
static std::pair< difference_type, _Distance_precision > _M_get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs)
Determine the distance between two iterators with some known precision.
template<typename _Iterator1 , typename _Iterator2 >
static std::pair< difference_type, _Distance_precision > _M_get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs, std::forward_iterator_tag)
template<typename _Iterator1 , typename _Iterator2 >
static std::pair< difference_type, _Distance_precision > _M_get_distance (const _Iterator1 &__lhs, const _Iterator2 &__rhs, std::random_access_iterator_tag)
Private Types
enum _Distance_precision { __dp_equality, __dp_sign, __dp_exact }
The precision to which we can calculate the distance between two iterators.
typedef _Safe_iterator _Self
typedef std::iterator_traits< _Iterator > _Traits
Private Member Functions
bool _M_constant () const
Determine if this is a constant iterator.
Private Attributes
_Iterator _M_current
The underlying iterator.
Detailed Description
template<typename _Iterator, typename _Sequence>
class __gnu_debug::_Safe_iterator< _Iterator, _Sequence >
Safe iterator wrapper.
The class template _Safe_iterator is a wrapper around an iterator that tracks the iterator's movement among sequences and checks that operations performed on the "safe" iterator are legal. In additional to the basic iterator operations (which are validated, and then passed to the underlying iterator), _Safe_iterator has member functions for iterator invalidation, attaching/detaching the iterator from sequences, and querying the iterator's state.
Definition at line 47 of file formatter.h.
Member Typedef Documentation
_Self
template<typename _Iterator , typename _Sequence > typedef _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Self private
Definition at line 79 of file safe_iterator.h.
_Traits
template<typename _Iterator , typename _Sequence > typedef std::iterator_traits<_Iterator> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Traits private
Definition at line 102 of file safe_iterator.h.
difference_type
template<typename _Iterator , typename _Sequence > typedef _Traits::difference_type __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::difference_type
Definition at line 108 of file safe_iterator.h.
iterator_category
template<typename _Iterator , typename _Sequence > typedef _Traits::iterator_category __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::iterator_category
Definition at line 106 of file safe_iterator.h.
iterator_type
template<typename _Iterator , typename _Sequence > typedef _Iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::iterator_type
Definition at line 105 of file safe_iterator.h.
pointer
template<typename _Iterator , typename _Sequence > typedef _Traits::pointer __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::pointer
Definition at line 110 of file safe_iterator.h.
reference
template<typename _Iterator , typename _Sequence > typedef _Traits::reference __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::reference
Definition at line 109 of file safe_iterator.h.
value_type
template<typename _Iterator , typename _Sequence > typedef _Traits::value_type __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::value_type
Definition at line 107 of file safe_iterator.h.
Member Enumeration Documentation
_Distance_precision
template<typename _Iterator , typename _Sequence > enum __gnu_debug::_Safe_iterator::_Distance_precision private
The precision to which we can calculate the distance between two iterators.
Enumerator
__dp_equality
__dp_sign
__dp_exact
Definition at line 84 of file safe_iterator.h.
     {
       __dp_equality, //< Can compare iterator equality, only
       __dp_sign,     //< Can determine equality and ordering
       __dp_exact     //< Can determine distance precisely
     };
Constructor & Destructor Documentation
_Safe_iterator() [1/4]
template<typename _Iterator , typename _Sequence > __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator () inline
Postcondition
the iterator is singular and unattached
Definition at line 113 of file safe_iterator.h.
 : _M_current() { }
_Safe_iterator() [2/4]
template<typename _Iterator , typename _Sequence > __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Iterator & __i, const _Sequence * __seq) inline
Safe iterator construction from an unsafe iterator and its sequence.
Precondition
seq is not NULL
Postcondition
this is not singular
Definition at line 122 of file safe_iterator.h.
       : _Safe_iterator_base(__seq, _M_constant()), _M_current(__i)
       {
     _GLIBCXX_DEBUG_VERIFY(! this->_M_singular(),
                   _M_message(__msg_init_singular)
                   ._M_iterator(*this, "this"));
       }
References __gnu_debug::__msg_init_singular, and _GLIBCXX_DEBUG_VERIFY.
_Safe_iterator() [3/4]
template<typename _Iterator , typename _Sequence > __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Safe_iterator< _Iterator, _Sequence > & __x) inline
Copy construction.
Definition at line 133 of file safe_iterator.h.
       : _Safe_iterator_base(__x, _M_constant()), _M_current(__x._M_current)
       {
     // _GLIBCXX_RESOLVE_LIB_DEFECTS
     // DR 408. Is vector<reverse_iterator<char*> > forbidden?
     _GLIBCXX_DEBUG_VERIFY(!__x._M_singular()
                   || __x._M_current == _Iterator(),
                   _M_message(__msg_init_copy_singular)
                   ._M_iterator(*this, "this")
                   ._M_iterator(__x, "other"));
       }
References __gnu_debug::__msg_init_copy_singular, and _GLIBCXX_DEBUG_VERIFY.
_Safe_iterator() [4/4]
template<typename _Iterator , typename _Sequence > template<typename _MutableIterator > __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_Safe_iterator (const _Safe_iterator< _MutableIterator, typename __gnu_cxx::__enable_if<(std::__are_same< _MutableIterator, typename _Sequence::iterator::iterator_type >::__value), _Sequence >::__type , & __x) inline
Converting constructor from a mutable iterator to a constant iterator.
Definition at line 150 of file safe_iterator.h.
     : _Safe_iterator_base(__x, _M_constant()), _M_current(__x.base())
         {
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // DR 408. Is vector<reverse_iterator<char*> > forbidden?
       _GLIBCXX_DEBUG_VERIFY(!__x._M_singular()
                 || __x.base() == _Iterator(),
                 _M_message(__msg_init_const_singular)
                 ._M_iterator(*this, "this")
                 ._M_iterator(__x, "other"));
     }
References __gnu_debug::__msg_init_const_singular, and _GLIBCXX_DEBUG_VERIFY.
Member Function Documentation
_M_attach()
template<typename _Iterator , typename _Sequence > void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach (_Safe_sequence_base * __seq) inline
Attach iterator to the given sequence.
Definition at line 335 of file safe_iterator.h.
       {
     _Safe_iterator_base::_M_attach(__seq, _M_constant());
       }
References __gnu_debug::_Safe_iterator_base::_M_attach(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_constant().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=().
_M_attach_single()
template<typename _Iterator , typename _Sequence > void __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach_single (_Safe_sequence_base * __seq) inline
Likewise, but not thread-safe.
Definition at line 342 of file safe_iterator.h.
       {
     _Safe_iterator_base::_M_attach_single(__seq, _M_constant());
       }
References __gnu_debug::_Safe_iterator_base::_M_attach_single(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_constant().
_M_before_dereferenceable()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable () const inline
Is the iterator before a dereferenceable one?
Definition at line 354 of file safe_iterator.h.
       {
     _Self __it = *this;
     return __it._M_incrementable() && (++__it)._M_dereferenceable();
       }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
_M_can_advance()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_can_advance (const difference_type & __n) const
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator+=(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-=(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator[]().
_M_constant()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_constant () const inline private
Determine if this is a constant iterator.
Definition at line 96 of file safe_iterator.h.
       {
     typedef typename _Sequence::const_iterator const_iterator;
     return std::__are_same<const_iterator, _Safe_iterator>::__value;
       }
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach_single().
_M_decrementable()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_decrementable () const inline
Definition at line 367 of file safe_iterator.h.
 { return !_M_singular() && !_M_is_begin(); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator--().
_M_dereferenceable()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable () const inline
Is the iterator dereferenceable?
Definition at line 349 of file safe_iterator.h.
       { return !this->_M_singular() && !_M_is_end() && !_M_is_before_begin(); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end().
Referenced by __gnu_debug::__check_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator*(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator->().
_M_get_distance() [1/3]
template<typename _Iterator , typename _Sequence > template<typename _Iterator1 , typename _Iterator2 > static std::pair<difference_type, _Distance_precision> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_distance (const _Iterator1 & __lhs, const _Iterator2 & __rhs) inline static
Determine the distance between two iterators with some known precision.
Definition at line 388 of file safe_iterator.h.
       {
         typedef typename std::iterator_traits<_Iterator1>::iterator_category
       _Category;
         return _M_get_distance(__lhs, __rhs, _Category());
       }
_M_get_distance() [2/3]
template<typename _Iterator , typename _Sequence > template<typename _Iterator1 , typename _Iterator2 > static std::pair<difference_type, _Distance_precision> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_distance (const _Iterator1 & __lhs, const _Iterator2 & __rhs, std::forward_iterator_tag) inline static
Definition at line 403 of file safe_iterator.h.
       { return std::make_pair(__lhs == __rhs? 0 : 1, __dp_equality); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::__dp_equality.
_M_get_distance() [3/3]
template<typename _Iterator , typename _Sequence > template<typename _Iterator1 , typename _Iterator2 > static std::pair<difference_type, _Distance_precision> __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_distance (const _Iterator1 & __lhs, const _Iterator2 & __rhs, std::random_access_iterator_tag) inline static
Definition at line 397 of file safe_iterator.h.
       { return std::make_pair(__rhs - __lhs, __dp_exact); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::__dp_exact.
_M_get_sequence()
template<typename _Iterator , typename _Sequence > const _Sequence* __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_sequence () const inline
Definition at line 380 of file safe_iterator.h.
       { return static_cast<const _Sequence*>(_M_sequence); }
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), and __gnu_debug::_Error_formatter::_Parameter::_Parameter().
_M_incrementable()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable () const inline
Is the iterator incrementable?
Definition at line 362 of file safe_iterator.h.
       { return !this->_M_singular() && !_M_is_end(); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_before_dereferenceable(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++().
_M_is_before_begin()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin () const inline
Is this iterator equal to the sequence's before_begin() iterator if any?
Definition at line 417 of file safe_iterator.h.
       { return _BeforeBeginHelper<_Sequence>::_M_Is(base(), _M_get_sequence()); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_sequence(), __gnu_debug::_BeforeBeginHelper< _Sequence >::_M_Is(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), and __gnu_debug::_Error_formatter::_Parameter::_Parameter().
_M_is_begin()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin () const inline
Is this iterator equal to the sequence's begin() iterator?
Definition at line 408 of file safe_iterator.h.
       { return base() == _M_get_sequence()->_M_base().begin(); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_sequence(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_decrementable(), and __gnu_debug::_Error_formatter::_Parameter::_Parameter().
_M_is_end()
template<typename _Iterator , typename _Sequence > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end () const inline
Is this iterator equal to the sequence's end() iterator?
Definition at line 412 of file safe_iterator.h.
       { return base() == _M_get_sequence()->_M_base().end(); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_sequence(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base().
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable(), and __gnu_debug::_Error_formatter::_Parameter::_Parameter().
_M_valid_range()
template<typename _Iterator , typename _Sequence > template<typename _Other > bool __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_valid_range (const _Safe_iterator< _Other, _Sequence > & __rhs) const
Referenced by __gnu_debug::__valid_range().
base()
template<typename _Iterator , typename _Sequence > _Iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base () const inline
Return the underlying iterator.
Definition at line 325 of file safe_iterator.h.
 { return _M_current; }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end().
operator _Iterator()
template<typename _Iterator , typename _Sequence > __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator _Iterator () const inline
Conversion to underlying non-debug iterator to allow better interaction with non-debug containers.
Definition at line 331 of file safe_iterator.h.
 { return _M_current; }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current.
operator*()
template<typename _Iterator , typename _Sequence > reference __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator* () const inline
Iterator dereference.
Precondition
iterator is dereferenceable
Definition at line 189 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_dereferenceable(),
                   _M_message(__msg_bad_deref)
                   ._M_iterator(*this, "this"));
     return *_M_current;
       }
References __gnu_debug::__msg_bad_deref, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
operator+()
template<typename _Iterator , typename _Sequence > _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator+ (const difference_type & __n) const inline
Definition at line 295 of file safe_iterator.h.
       {
     _Safe_iterator __tmp(*this);
     __tmp += __n;
     return __tmp;
       }
operator++() [1/2]
template<typename _Iterator , typename _Sequence > _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++ () inline
Iterator preincrement.
Precondition
iterator is incrementable
Definition at line 218 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_incrementable(),
                   _M_message(__msg_bad_inc)
                   ._M_iterator(*this, "this"));
     ++_M_current;
     return *this;
       }
References __gnu_debug::__msg_bad_inc, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
operator++() [2/2]
template<typename _Iterator , typename _Sequence > _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++ (int) inline
Iterator postincrement.
Precondition
iterator is incrementable
Definition at line 232 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_incrementable(),
                   _M_message(__msg_bad_inc)
                   ._M_iterator(*this, "this"));
     _Safe_iterator __tmp(*this);
     ++_M_current;
     return __tmp;
       }
References __gnu_debug::__msg_bad_inc, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_incrementable().
operator+=()
template<typename _Iterator , typename _Sequence > _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator+= (const difference_type & __n) inline
Definition at line 285 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_can_advance(__n),
                   _M_message(__msg_advance_oob)
                   ._M_iterator(*this)._M_integer(__n));
     _M_current += __n;
     return *this;
       }
References __gnu_debug::__msg_advance_oob, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_can_advance(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current.
operator-()
template<typename _Iterator , typename _Sequence > _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator- (const difference_type & __n) const inline
Definition at line 313 of file safe_iterator.h.
       {
     _Safe_iterator __tmp(*this);
     __tmp -= __n;
     return __tmp;
       }
operator--() [1/2]
template<typename _Iterator , typename _Sequence > _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-- () inline
Iterator predecrement.
Precondition
iterator is decrementable
Definition at line 248 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_decrementable(),
                   _M_message(__msg_bad_dec)
                   ._M_iterator(*this, "this"));
     --_M_current;
     return *this;
       }
References __gnu_debug::__msg_bad_dec, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_decrementable().
operator--() [2/2]
template<typename _Iterator , typename _Sequence > _Safe_iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-- (int) inline
Iterator postdecrement.
Precondition
iterator is decrementable
Definition at line 262 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_decrementable(),
                   _M_message(__msg_bad_dec)
                   ._M_iterator(*this, "this"));
     _Safe_iterator __tmp(*this);
     --_M_current;
     return __tmp;
       }
References __gnu_debug::__msg_bad_dec, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_decrementable().
operator-=()
template<typename _Iterator , typename _Sequence > _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-= (const difference_type & __n) inline
Definition at line 303 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_can_advance(-__n),
                   _M_message(__msg_retreat_oob)
                   ._M_iterator(*this)._M_integer(__n));
     _M_current += -__n;
     return *this;
       }
References __gnu_debug::__msg_retreat_oob, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_can_advance(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current.
operator->()
template<typename _Iterator , typename _Sequence > pointer __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-> () const inline
Iterator dereference.
Precondition
iterator is dereferenceable
Todo:
Make this correct w.r.t. iterators that return proxies
Use addressof() instead of & operator
Definition at line 204 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_dereferenceable(),
                   _M_message(__msg_bad_deref)
                   ._M_iterator(*this, "this"));
     return &*_M_current;
       }
References __gnu_debug::__msg_bad_deref, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current, and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
operator=()
template<typename _Iterator , typename _Sequence > _Safe_iterator& __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator= (const _Safe_iterator< _Iterator, _Sequence > & __x) inline
Copy assignment.
Definition at line 170 of file safe_iterator.h.
       {
     // _GLIBCXX_RESOLVE_LIB_DEFECTS
     // DR 408. Is vector<reverse_iterator<char*> > forbidden?
     _GLIBCXX_DEBUG_VERIFY(!__x._M_singular()
                   || __x._M_current == _Iterator(),
                   _M_message(__msg_copy_singular)
                   ._M_iterator(*this, "this")
                   ._M_iterator(__x, "other"));
     _M_current = __x._M_current;
     this->_M_attach(__x._M_sequence);
     return *this;
       }
References __gnu_debug::__msg_copy_singular, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_attach(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current.
operator[]()
template<typename _Iterator , typename _Sequence > reference __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator[] (const difference_type & __n) const inline
Definition at line 274 of file safe_iterator.h.
       {
     _GLIBCXX_DEBUG_VERIFY(this->_M_can_advance(__n)
                   && this->_M_can_advance(__n+1),
                   _M_message(__msg_iter_subscript_oob)
                   ._M_iterator(*this)._M_integer(__n));
     return _M_current[__n];
       }
References __gnu_debug::__msg_iter_subscript_oob, _GLIBCXX_DEBUG_VERIFY, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_can_advance(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current.
Field Documentation
_M_current
template<typename _Iterator , typename _Sequence > _Iterator __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_current private
The underlying iterator.
Definition at line 92 of file safe_iterator.h.
Referenced by __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::base(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator _Iterator(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator*(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator++(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator+=(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator--(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator-=(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator->(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator=(), and __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::operator[]().
The documentation for this class was generated from the following files:
Tools/MinGW/include/c++/4.6.1/debug/formatter.h
Tools/MinGW/include/c++/4.6.1/debug/safe_iterator.h