ZEQ2-Lite: Game/Game/g_main.c File Reference
g_main.c File Reference
#include "g_local.h"
Data Structures
struct cvarTable_t
Functions
void AddTournamentPlayer (void)
void AddTournamentQueue (gclient_t *client)
void AdjustTournamentScores (void)
void BeginIntermission (void)
void CalculateRanks (void)
void CheckCvars (void)
void CheckExitRules (void)
void CheckIntermissionExit (void)
void CheckTeamLeader (int team)
void CheckTeamVote (int team)
void CheckTournament (void)
void CheckVote (void)
void QDECL Com_Error (int level, const char *error,...)
void QDECL Com_Printf (const char *msg,...)
void ExitLevel (void)
void FindIntermissionPoint (void)
void QDECL G_Error (const char *fmt,...)
void G_FindTeams (void)
void G_InitGame (int levelTime, int randomSeed, int restart)
void QDECL G_LogPrintf (const char *fmt,...)
void QDECL G_Printf (const char *fmt,...)
void G_RegisterCvars (void)
void G_RemapTeamShaders ()
void G_RunFrame (int levelTime)
void G_RunThink (gentity_t *ent)
void G_ShutdownGame (int restart)
void G_UpdateCvars (void)
void LogExit (const char *string)
void MoveClientToIntermission (gentity_t *ent)
void PrintTeam (int team, char *message)
void RemoveTournamentLoser (void)
void RemoveTournamentWinner (void)
qboolean ScoreIsTied (void)
void SendScoreboardMessageToAllClients (void)
void SetLeader (int team, int client)
int QDECL SortRanks (const void *a, const void *b)
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
Variables
vmCvar_t g_allowAdvancedMelee
vmCvar_t g_allowBallFlip
vmCvar_t g_allowBlock
vmCvar_t g_allowBoost
vmCvar_t g_allowBreakLimit
vmCvar_t g_allowFly
vmCvar_t g_allowJump
vmCvar_t g_allowLockon
vmCvar_t g_allowMelee
vmCvar_t g_allowOverheal
vmCvar_t g_allowScoreboard
vmCvar_t g_allowSoar
vmCvar_t g_allowTiers
vmCvar_t g_allowVote
vmCvar_t g_allowZanzoken
vmCvar_t g_banIPs
vmCvar_t g_blood
vmCvar_t g_breakLimitRate
vmCvar_t g_capturelimit
vmCvar_t g_cheats
gclient_t g_clients [MAX_CLIENTS]
vmCvar_t g_debugAlloc
vmCvar_t g_debugDamage
vmCvar_t g_debugMove
vmCvar_t g_dedicated
vmCvar_t g_dmflags
vmCvar_t g_doWarmup
gentity_t g_entities [MAX_GENTITIES]
vmCvar_t g_filterBan
vmCvar_t g_forcerespawn
vmCvar_t g_fraglimit
vmCvar_t g_friendlyFire
vmCvar_t g_gametype
vmCvar_t g_inactivity
vmCvar_t g_knockback
vmCvar_t g_listEntity
vmCvar_t g_logfile
vmCvar_t g_logfileSync
vmCvar_t g_maxclients
vmCvar_t g_maxGameClients
vmCvar_t g_motd
vmCvar_t g_needpass
vmCvar_t g_password
vmCvar_t g_podiumDist
vmCvar_t g_podiumDrop
vmCvar_t g_pointGravity
vmCvar_t g_powerlevel
vmCvar_t g_powerlevelMaximum
vmCvar_t g_quadfactor
vmCvar_t g_quickTransformCost
vmCvar_t g_quickTransformCostPerTier
vmCvar_t g_quickZanzokenCost
vmCvar_t g_quickZanzokenDistance
vmCvar_t g_rankings
vmCvar_t g_restarted
vmCvar_t g_rolling
vmCvar_t g_running
vmCvar_t g_smoothClients
vmCvar_t g_synchronousClients
vmCvar_t g_teamAutoJoin
vmCvar_t g_teamForceBalance
vmCvar_t g_timelimit
vmCvar_t g_verboseParse
vmCvar_t g_warmup
vmCvar_t g_weaponRespawn
vmCvar_t g_weaponTeamRespawn
static cvarTable_t gameCvarTable []
static int gameCvarTableSize = ARRAY_LEN(gameCvarTable)
level_locals_t level
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
Function Documentation
AddTournamentPlayer()
void AddTournamentPlayer (void)
Definition at line 558 of file g_main.c.
{
     int         i;
     gclient_t   *client;
     gclient_t   *nextInLine;
     if ( level.numPlayingClients >= 2 ) {
         return;
     }
     // never change during intermission
     if ( level.intermissiontime ) {
         return;
     }
     nextInLine = NULL;
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         client = &level.clients[i];
         if ( client->pers.connected != CON_CONNECTED ) {
             continue;
         }
         if ( client->sess.sessionTeam != TEAM_SPECTATOR ) {
             continue;
         }
         // never select the dedicated follow or scoreboard clients
         if ( client->sess.spectatorState == SPECTATOR_SCOREBOARD ||
             client->sess.spectatorClient < 0  ) {
             continue;
         }
         if(!nextInLine || client->sess.spectatorNum > nextInLine->sess.spectatorNum)
             nextInLine = client;
     }
     if ( !nextInLine ) {
         return;
     }
     level.warmupTime = -1;
     // set them to free-for-all team
     SetTeam( &g_entities[ nextInLine - level.clients ], "f" );
 }
References CON_CONNECTED, g_entities, NULL, SetTeam(), SPECTATOR_SCOREBOARD, and TEAM_SPECTATOR.
Referenced by CheckTournament().
AddTournamentQueue()
void AddTournamentQueue (gclient_t * client)
Definition at line 610 of file g_main.c.
 {
     int index;
     gclient_t *curclient;
     for(index = 0; index < level.maxclients; index++)
     {
         curclient = &level.clients[index];
         if(curclient->pers.connected != CON_DISCONNECTED)
         {
             if(curclient == client)
                 curclient->sess.spectatorNum = 0;
             else if(curclient->sess.sessionTeam == TEAM_SPECTATOR)
                 curclient->sess.spectatorNum++;
         }
     }
 }
References CON_DISCONNECTED, and TEAM_SPECTATOR.
Referenced by G_InitSessionData(), and SetTeam().
AdjustTournamentScores()
void AdjustTournamentScores (void)
Definition at line 680 of file g_main.c.
{
     int         clientNum;
     clientNum = level.sortedClients[0];
     if ( level.clients[ clientNum ].pers.connected == CON_CONNECTED ) {
         level.clients[ clientNum ].sess.wins++;
         ClientUserinfoChanged( clientNum );
     }
     clientNum = level.sortedClients[1];
     if ( level.clients[ clientNum ].pers.connected == CON_CONNECTED ) {
         level.clients[ clientNum ].sess.losses++;
         ClientUserinfoChanged( clientNum );
     }
 }
References ClientUserinfoChanged(), and CON_CONNECTED.
Referenced by BeginIntermission().
BeginIntermission()
void BeginIntermission (void)
Definition at line 905 of file g_main.c.
{
     int         i;
     gentity_t   *client;
     if ( level.intermissiontime ) {
         return;     // already active
     }
     // if in tournement mode, change the wins / losses
     if ( g_gametype.integer == GT_TOURNAMENT ) {
         AdjustTournamentScores();
     }
     level.intermissiontime = level.time;
     // move all clients to the intermission point
     for (i=0 ; i< level.maxclients ; i++) {
         client = g_entities + i;
         if (!client->inuse)
             continue;
         // respawn if dead
         if (client->powerLevelTotal <= 0) {
             ClientRespawn(client);
         }
         MoveClientToIntermission( client );
     }
     // if single player game
     if ( g_gametype.integer == GT_SINGLE_PLAYER ) {
         UpdateTournamentInfo();
         SpawnModelsOnVictoryPads();
     }
     // send the current scoring to all clients
     SendScoreboardMessageToAllClients();
 }
References AdjustTournamentScores(), ClientRespawn(), g_entities, g_gametype, GT_SINGLE_PLAYER, GT_TOURNAMENT, vmCvar_t::integer, MoveClientToIntermission(), SendScoreboardMessageToAllClients(), SpawnModelsOnVictoryPads(), and UpdateTournamentInfo().
Referenced by Cmd_LevelShot_f().
CalculateRanks()
void CalculateRanks (void)
Definition at line 764 of file g_main.c.
{
     int     i;
     int     rank;
     int     score;
     int     newScore;
     gclient_t   *cl;
     level.follow1 = -1;
     level.follow2 = -1;
     level.numConnectedClients = 0;
     level.numNonSpectatorClients = 0;
     level.numPlayingClients = 0;
     level.numVotingClients = 0;     // don't count bots
     for (i = 0; i < ARRAY_LEN(level.numteamVotingClients); i++)
         level.numteamVotingClients[i] = 0;
     qsort( level.sortedClients, level.numConnectedClients,
         sizeof(level.sortedClients[0]), SortRanks );
     // set the CS_SCORES1/2 configstrings, which will be visible to everyone
     if ( g_gametype.integer >= GT_TEAM ) {
         trap_SetConfigstring( CS_SCORES1, va("%i", level.teamScores[TEAM_RED] ) );
         trap_SetConfigstring( CS_SCORES2, va("%i", level.teamScores[TEAM_BLUE] ) );
     } else {
         if ( level.numConnectedClients == 0 ) {
             trap_SetConfigstring( CS_SCORES1, va("%i", SCORE_NOT_PRESENT) );
             trap_SetConfigstring( CS_SCORES2, va("%i", SCORE_NOT_PRESENT) );
         } else if ( level.numConnectedClients == 1 ) {
             trap_SetConfigstring( CS_SCORES1, va("%i", level.clients[ level.sortedClients[0] ].ps.persistant[PERS_SCORE] ) );
             trap_SetConfigstring( CS_SCORES2, va("%i", SCORE_NOT_PRESENT) );
         } else {
             trap_SetConfigstring( CS_SCORES1, va("%i", level.clients[ level.sortedClients[0] ].ps.persistant[PERS_SCORE] ) );
             trap_SetConfigstring( CS_SCORES2, va("%i", level.clients[ level.sortedClients[1] ].ps.persistant[PERS_SCORE] ) );
         }
     }
     // see if it is time to end the level
     CheckExitRules();
     // if we are at the intermission, send the new info to everyone
     if ( level.intermissiontime ) {
         SendScoreboardMessageToAllClients();
     }
 }
References ARRAY_LEN, CheckExitRules(), cl, CS_SCORES1, CS_SCORES2, g_gametype, GT_TEAM, vmCvar_t::integer, PERS_SCORE, SCORE_NOT_PRESENT, SendScoreboardMessageToAllClients(), SortRanks(), TEAM_BLUE, TEAM_RED, trap_SetConfigstring(), and va().
Referenced by ClientBegin(), ClientConnect(), ClientDisconnect(), and UpdateTournamentInfo().
CheckCvars()
void CheckCvars (void)
Definition at line 1400 of file g_main.c.
{
     static int lastMod = -1;
     if ( g_password.modificationCount != lastMod ) {
         lastMod = g_password.modificationCount;
         if ( *g_password.string && Q_stricmp( g_password.string, "none" ) ) {
             trap_Cvar_Set( "g_needpass", "1" );
         } else {
             trap_Cvar_Set( "g_needpass", "0" );
         }
     }
 }
References g_password, vmCvar_t::modificationCount, Q_stricmp(), vmCvar_t::string, and trap_Cvar_Set().
Referenced by G_RunFrame().
CheckExitRules()
void CheckExitRules (void)
Definition at line 1134 of file g_main.c.
 {}
Referenced by CalculateRanks(), and G_RunFrame().
CheckIntermissionExit()
void CheckIntermissionExit (void)
Definition at line 1101 of file g_main.c.
 {ExitLevel();}
References ExitLevel().
CheckTeamLeader()
void CheckTeamLeader (int team)
Definition at line 1347 of file g_main.c.
 {}
Referenced by SetTeam().
CheckTeamVote()
void CheckTeamVote (int team)
Definition at line 1354 of file g_main.c.
{
     int cs_offset;
     if ( team == TEAM_RED )
         cs_offset = 0;
     else if ( team == TEAM_BLUE )
         cs_offset = 1;
     else
         return;
     if ( !level.teamVoteTime[cs_offset] ) {
         return;
     }
     if ( level.time - level.teamVoteTime[cs_offset] >= VOTE_TIME ) {
         trap_SendServerCommand( -1, "print \"Team vote failed.\n\"" );
     } else {
         if ( level.teamVoteYes[cs_offset] > level.numteamVotingClients[cs_offset]/2 ) {
             // execute the command, then remove the vote
             trap_SendServerCommand( -1, "print \"Team vote passed.\n\"" );
             //
             if ( !Q_strncmp( "leader", level.teamVoteString[cs_offset], 6) ) {
                 //set the team leader
                 SetLeader(team, atoi(level.teamVoteString[cs_offset] + 7));
             }
             else {
                 trap_SendConsoleCommand( EXEC_APPEND, va("%s\n", level.teamVoteString[cs_offset] ) );
             }
         } else if ( level.teamVoteNo[cs_offset] >= level.numteamVotingClients[cs_offset]/2 ) {
             // same behavior as a timeout
             trap_SendServerCommand( -1, "print \"Team vote failed.\n\"" );
         } else {
             // still waiting for a majority
             return;
         }
     }
     level.teamVoteTime[cs_offset] = 0;
     trap_SetConfigstring( CS_TEAMVOTE_TIME + cs_offset, "" );
 }
References CS_TEAMVOTE_TIME, EXEC_APPEND, Q_strncmp(), SetLeader(), TEAM_BLUE, TEAM_RED, trap_SendConsoleCommand(), trap_SendServerCommand(), trap_SetConfigstring(), va(), and VOTE_TIME.
Referenced by G_RunFrame().
CheckTournament()
void CheckTournament (void)
Definition at line 1154 of file g_main.c.
{
     // check because we run 3 game frames before calling Connect and/or ClientBegin
     // for clients on a map_restart
     if ( level.numPlayingClients == 0 ) {
         return;
     }
     if ( g_gametype.integer == GT_TOURNAMENT ) {
         // pull in a spectator if needed
         if ( level.numPlayingClients < 2 ) {
             AddTournamentPlayer();
         }
         // if we don't have two players, go back to "waiting for players"
         if ( level.numPlayingClients != 2 ) {
             if ( level.warmupTime != -1 ) {
                 level.warmupTime = -1;
                 trap_SetConfigstring( CS_WARMUP, va("%i", level.warmupTime) );
                 G_LogPrintf( "Warmup:\n" );
             }
             return;
         }
         if ( level.warmupTime == 0 ) {
             return;
         }
         // if the warmup is changed at the console, restart it
         if ( g_warmup.modificationCount != level.warmupModificationCount ) {
             level.warmupModificationCount = g_warmup.modificationCount;
             level.warmupTime = -1;
         }
         // if all players have arrived, start the countdown
         if ( level.warmupTime < 0 ) {
             if ( level.numPlayingClients == 2 ) {
                 // fudge by -1 to account for extra delays
                 if ( g_warmup.integer > 1 ) {
                     level.warmupTime = level.time + ( g_warmup.integer - 1 ) * 1000;
                 } else {
                     level.warmupTime = 0;
                 }
                 trap_SetConfigstring( CS_WARMUP, va("%i", level.warmupTime) );
             }
             return;
         }
         // if the warmup time has counted down, restart
         if ( level.time > level.warmupTime ) {
             level.warmupTime += 10000;
             trap_Cvar_Set( "g_restarted", "1" );
             trap_SendConsoleCommand( EXEC_APPEND, "map_restart 0\n" );
             level.restarted = qtrue;
             return;
         }
     } else if ( g_gametype.integer != GT_SINGLE_PLAYER && level.warmupTime != 0 ) {
         int     counts[TEAM_NUM_TEAMS];
         qboolean    notEnough = qfalse;
         if ( g_gametype.integer > GT_TEAM ) {
             counts[TEAM_BLUE] = TeamCount( -1, TEAM_BLUE );
             counts[TEAM_RED] = TeamCount( -1, TEAM_RED );
             if (counts[TEAM_RED] < 1 || counts[TEAM_BLUE] < 1) {
                 notEnough = qtrue;
             }
         } else if ( level.numPlayingClients < 2 ) {
             notEnough = qtrue;
         }
         if ( notEnough ) {
             if ( level.warmupTime != -1 ) {
                 level.warmupTime = -1;
                 trap_SetConfigstring( CS_WARMUP, va("%i", level.warmupTime) );
                 G_LogPrintf( "Warmup:\n" );
             }
             return; // still waiting for team members
         }
         if ( level.warmupTime == 0 ) {
             return;
         }
         // if the warmup is changed at the console, restart it
         if ( g_warmup.modificationCount != level.warmupModificationCount ) {
             level.warmupModificationCount = g_warmup.modificationCount;
             level.warmupTime = -1;
         }
         // if all players have arrived, start the countdown
         if ( level.warmupTime < 0 ) {
             // fudge by -1 to account for extra delays
             level.warmupTime = level.time + ( g_warmup.integer - 1 ) * 1000;
             trap_SetConfigstring( CS_WARMUP, va("%i", level.warmupTime) );
             return;
         }
         // if the warmup time has counted down, restart
         if ( level.time > level.warmupTime ) {
             level.warmupTime += 10000;
             trap_Cvar_Set( "g_restarted", "1" );
             trap_SendConsoleCommand( EXEC_APPEND, "map_restart 0\n" );
             level.restarted = qtrue;
             return;
         }
     }
 }
References AddTournamentPlayer(), CS_WARMUP, EXEC_APPEND, g_gametype, G_LogPrintf(), g_warmup, GT_SINGLE_PLAYER, GT_TEAM, GT_TOURNAMENT, vmCvar_t::integer, vmCvar_t::modificationCount, qfalse, qtrue, TEAM_BLUE, TEAM_NUM_TEAMS, TEAM_RED, TeamCount(), trap_Cvar_Set(), trap_SendConsoleCommand(), trap_SetConfigstring(), and va().
Referenced by G_RunFrame().
CheckVote()
void CheckVote (void)
Definition at line 1269 of file g_main.c.
{
     if ( level.voteExecuteTime && level.voteExecuteTime < level.time ) {
         level.voteExecuteTime = 0;
         trap_SendConsoleCommand( EXEC_APPEND, va("%s\n", level.voteString ) );
     }
     if ( !level.voteTime ) {
         return;
     }
     if ( level.time - level.voteTime >= VOTE_TIME ) {
         trap_SendServerCommand( -1, "print \"Vote failed.\n\"" );
     } else {
         // ATVI Q3 1.32 Patch #9, WNF
         if ( level.voteYes > level.numVotingClients/2 ) {
             // execute the command, then remove the vote
             trap_SendServerCommand( -1, "print \"Vote passed.\n\"" );
             level.voteExecuteTime = level.time + 3000;
         } else if ( level.voteNo >= level.numVotingClients/2 ) {
             // same behavior as a timeout
             trap_SendServerCommand( -1, "print \"Vote failed.\n\"" );
         } else {
             // still waiting for a majority
             return;
         }
     }
     level.voteTime = 0;
     trap_SetConfigstring( CS_VOTE_TIME, "" );
 }
References CS_VOTE_TIME, EXEC_APPEND, trap_SendConsoleCommand(), trap_SendServerCommand(), trap_SetConfigstring(), va(), and VOTE_TIME.
Referenced by G_RunFrame().
Com_Error()
void QDECL Com_Error (int level, const char * error, ...)
Definition at line 520 of file g_main.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, error);
     Q_vsnprintf (text, sizeof(text), error, argptr);
     va_end (argptr);
     G_Error( "%s", text);
 }
References error(), G_Error(), and Q_vsnprintf.
Com_Printf()
void QDECL Com_Printf (const char * msg, ...)
Definition at line 531 of file g_main.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, msg);
     Q_vsnprintf (text, sizeof(text), msg, argptr);
     va_end (argptr);
     G_Printf ("%s", text);
 }
References G_Printf(), and Q_vsnprintf.
ExitLevel()
void ExitLevel (void)
Definition at line 950 of file g_main.c.
                       {
     int     i;
     gclient_t *cl;
     char nextmap[MAX_STRING_CHARS];
     char d1[MAX_STRING_CHARS];
     // if we are running a tournement map, kick the loser to spectator status,
     // which will automatically grab the next spectator and restart
     if ( g_gametype.integer == GT_TOURNAMENT  ) {
         if ( !level.restarted ) {
             RemoveTournamentLoser();
             trap_SendConsoleCommand( EXEC_APPEND, "map_restart 0\n" );
             level.restarted = qtrue;
             level.changemap = NULL;
             level.intermissiontime = 0;
         }
         return;
     }
     trap_Cvar_VariableStringBuffer( "nextmap", nextmap, sizeof(nextmap) );
     trap_Cvar_VariableStringBuffer( "d1", d1, sizeof(d1) );
     if( !Q_stricmp( nextmap, "map_restart 0" ) && Q_stricmp( d1, "" ) ) {
         trap_Cvar_Set( "nextmap", "vstr d2" );
         trap_SendConsoleCommand( EXEC_APPEND, "vstr d1\n" );
     } else {
         trap_SendConsoleCommand( EXEC_APPEND, "vstr nextmap\n" );
     }
     level.changemap = NULL;
     level.intermissiontime = 0;
     // reset all the scores so we don't enter the intermission again
     level.teamScores[TEAM_RED] = 0;
     level.teamScores[TEAM_BLUE] = 0;
     for ( i=0 ; i< g_maxclients.integer ; i++ ) {
         cl = level.clients + i;
         if ( cl->pers.connected != CON_CONNECTED ) {
             continue;
         }
         cl->ps.persistant[PERS_SCORE] = 0;
     }
     // we need to do this here before chaning to CON_CONNECTING
     G_WriteSessionData();
     // change all client states to connecting, so the early players into the
     // next level will know the others aren't done reconnecting
     for (i=0 ; i< g_maxclients.integer ; i++) {
         if ( level.clients[i].pers.connected == CON_CONNECTED ) {
             level.clients[i].pers.connected = CON_CONNECTING;
         }
     }
 }
References cl, CON_CONNECTED, CON_CONNECTING, EXEC_APPEND, g_gametype, g_maxclients, G_WriteSessionData(), GT_TOURNAMENT, vmCvar_t::integer, MAX_STRING_CHARS, NULL, PERS_SCORE, Q_stricmp(), qtrue, RemoveTournamentLoser(), TEAM_BLUE, TEAM_RED, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and trap_SendConsoleCommand().
Referenced by CheckIntermissionExit().
FindIntermissionPoint()
void FindIntermissionPoint (void)
Definition at line 877 of file g_main.c.
{
     gentity_t   *ent, *target;
     vec3_t      dir;
     // find the intermission spot
     ent = G_Find (NULL, FOFS(classname), "info_player_intermission");
     if ( !ent ) {   // the map creator forgot to put in an intermission point...
         SelectSpawnPoint ( vec3_origin, level.intermission_origin, level.intermission_angle );
     } else {
         VectorCopy (ent->s.origin, level.intermission_origin);
         VectorCopy (ent->s.angles, level.intermission_angle);
         // if it has a target, look towards it
         if ( ent->target ) {
             target = G_PickTarget( ent->target );
             if ( target ) {
                 VectorSubtract( target->s.origin, level.intermission_origin, dir );
                 vectoangles( dir, level.intermission_angle );
             }
         }
     }
 }
References dir, FOFS, G_Find(), G_PickTarget(), NULL, SelectSpawnPoint(), vec3_origin, vectoangles(), VectorCopy, and VectorSubtract.
Referenced by MoveClientToIntermission(), and SelectSpectatorSpawnPoint().
G_Error()
void QDECL G_Error (const char * fmt, ...)
Definition at line 262 of file g_main.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, fmt);
     Q_vsnprintf (text, sizeof(text), fmt, argptr);
     va_end (argptr);
     trap_Error( text );
 }
References fmt, Q_vsnprintf, and trap_Error().
Referenced by Com_Error(), and G_RunThink().
G_FindTeams()
void G_FindTeams (void)
Definition at line 284 of file g_main.c.
{
     gentity_t   *e, *e2;
     int     i, j;
     int     c, c2;
     c = 0;
     c2 = 0;
     for ( i=1, e=g_entities+i ; i < level.num_entities ; i++,e++ ){
         if (!e->inuse)
             continue;
         if (!e->team)
             continue;
         if (e->flags & FL_TEAMSLAVE)
             continue;
         e->teammaster = e;
         c++;
         c2++;
         for (j=i+1, e2=e+1 ; j < level.num_entities ; j++,e2++)
         {
             if (!e2->inuse)
                 continue;
             if (!e2->team)
                 continue;
             if (e2->flags & FL_TEAMSLAVE)
                 continue;
             if (!strcmp(e->team, e2->team))
             {
                 c2++;
                 e2->teamchain = e->teamchain;
                 e->teamchain = e2;
                 e2->teammaster = e;
                 e2->flags |= FL_TEAMSLAVE;
                 // make sure that targets only point at the master
                 if ( e2->targetname ) {
                     e->targetname = e2->targetname;
                     e2->targetname = NULL;
                 }
             }
         }
     }
     G_Printf ("%i teams with %i entities\n", c, c2);
 }
References FL_TEAMSLAVE, g_entities, G_Printf(), and NULL.
Referenced by G_InitGame().
G_InitGame()
void G_InitGame (int levelTime, int randomSeed, int restart)
Definition at line 405 of file g_main.c.
{
     int                 i;
     G_Printf ("------- Game Initialization -------\n");
     G_Printf ("gamename: %s\n", GAMEVERSION);
     G_Printf ("gamedate: %s\n", __DATE__);
     srand( randomSeed );
     G_RegisterCvars();
     G_ProcessIPBans();
     G_InitMemory();
     // set some level globals
     memset( &level, 0, sizeof( level ) );
     level.time = levelTime;
     level.startTime = levelTime;
     if ( g_gametype.integer != GT_SINGLE_PLAYER && g_logfile.string[0] ) {
         if ( g_logfileSync.integer ) {
             trap_FS_FOpenFile( g_logfile.string, &level.logFile, FS_APPEND_SYNC );
         } else {
             trap_FS_FOpenFile( g_logfile.string, &level.logFile, FS_APPEND );
         }
         if ( !level.logFile ) {
             G_Printf( "WARNING: Couldn't open logfile: %s\n", g_logfile.string );
         } else {
             char    serverinfo[MAX_INFO_STRING];
             trap_GetServerinfo( serverinfo, sizeof( serverinfo ) );
             G_LogPrintf("------------------------------------------------------------\n" );
             G_LogPrintf("InitGame: %s\n", serverinfo );
         }
     } else {
         G_Printf( "Not logging to disk.\n" );
     }
     G_InitWorldSession();
     // initialize all entities for this game
     memset( g_entities, 0, MAX_GENTITIES * sizeof(g_entities[0]) );
     level.gentities = g_entities;
     // initialize all clients for this game
     level.maxclients = g_maxclients.integer;
     memset( g_clients, 0, MAX_CLIENTS * sizeof(g_clients[0]) );
     level.clients = g_clients;
     // set client fields on player ents
     for ( i=0 ; i<level.maxclients ; i++ ) {
         g_entities[i].client = level.clients + i;
     }
     // always leave room for the max number of clients,
     // even if they aren't all used, so numbers inside that
     // range are NEVER anything but clients
     level.num_entities = MAX_CLIENTS;
     for ( i=0 ; i<MAX_CLIENTS ; i++ ) {
         g_entities[i].classname = "clientslot";
     }
     // let the server system know where the entites are
     trap_LocateGameData( level.gentities, level.num_entities, sizeof( gentity_t ),
         &level.clients[0].ps, sizeof( level.clients[0] ) );
     // reserve some spots for dead player bodies
     InitBodyQue();
     // parse the key/value pairs and spawn gentities
     G_SpawnEntitiesFromString();
     // general initialization
     G_FindTeams();
     // make sure we have flags for CTF, etc
     // ADDING FOR ZEQ2
     // Parse the weapon lists.
     // FIXME: As soon as these become variable, move them
     // to the client spawning functions!
     if( g_gametype.integer == GT_SINGLE_PLAYER || trap_Cvar_VariableIntegerValue( "com_buildScript" ) ) {
         G_ModelIndex( SP_PODIUM_MODEL );
     }
     G_RemapTeamShaders();
 }
References FS_APPEND, FS_APPEND_SYNC, g_clients, g_entities, G_FindTeams(), g_gametype, G_InitMemory(), G_InitWorldSession(), g_logfile, g_logfileSync, G_LogPrintf(), g_maxclients, G_ModelIndex(), G_Printf(), G_ProcessIPBans(), G_RegisterCvars(), G_RemapTeamShaders(), G_SpawnEntitiesFromString(), GAMEVERSION, GT_SINGLE_PLAYER, InitBodyQue(), vmCvar_t::integer, MAX_CLIENTS, MAX_GENTITIES, MAX_INFO_STRING, SP_PODIUM_MODEL, vmCvar_t::string, trap_Cvar_VariableIntegerValue(), trap_FS_FOpenFile(), trap_GetServerinfo(), and trap_LocateGameData().
Referenced by vmMain().
G_LogPrintf()
void QDECL G_LogPrintf (const char * fmt, ...)
Definition at line 1013 of file g_main.c.
{
     va_list     argptr;
     char        string[1024];
     int         min, tens, sec;
     sec = ( level.time - level.startTime ) / 1000;
     min = sec / 60;
     sec -= min * 60;
     tens = sec / 10;
     sec -= tens * 10;
     Com_sprintf( string, sizeof(string), "%3i:%i%i ", min, tens, sec );
     va_start( argptr, fmt );
     Q_vsnprintf(string + 7, sizeof(string) - 7, fmt, argptr);
     va_end( argptr );
     if ( g_dedicated.integer ) {
         G_Printf( "%s", string + 7 );
     }
     if ( !level.logFile ) {
         return;
     }
     trap_FS_Write( string, strlen( string ), level.logFile );
 }
References Com_sprintf(), fmt, g_dedicated, G_Printf(), vmCvar_t::integer, Q_vsnprintf, and trap_FS_Write().
Referenced by CheckTournament(), G_InitGame(), G_ShutdownGame(), and LogExit().
G_Printf()
void QDECL G_Printf (const char * fmt, ...)
Definition at line 251 of file g_main.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, fmt);
     Q_vsnprintf (text, sizeof(text), fmt, argptr);
     va_end (argptr);
     trap_Printf( text );
 }
References fmt, Q_vsnprintf, and trap_Printf().
Referenced by Com_Printf(), G_FindTeams(), G_InitGame(), G_LogPrintf(), G_RegisterCvars(), G_RunFrame(), and G_ShutdownGame().
G_RegisterCvars()
void G_RegisterCvars (void)
Definition at line 337 of file g_main.c.
{
     int         i;
     cvarTable_t *cv;
     qboolean remapped = qfalse;
     for ( i = 0, cv = gameCvarTable ; i < gameCvarTableSize ; i++, cv++ ) {
         trap_Cvar_Register( cv->vmCvar, cv->cvarName,
             cv->defaultString, cv->cvarFlags );
         if ( cv->vmCvar )
             cv->modificationCount = cv->vmCvar->modificationCount;
         if (cv->teamShader) {
             remapped = qtrue;
         }
     }
     if (remapped) {
         G_RemapTeamShaders();
     }
     // check some things
     if ( g_gametype.integer < 0 || g_gametype.integer >= GT_MAX_GAME_TYPE ) {
         G_Printf( "g_gametype %i is out of range, defaulting to 0\n", g_gametype.integer );
         trap_Cvar_Set( "g_gametype", "0" );
     }
     level.warmupModificationCount = g_warmup.modificationCount;
 }
References cvarTable_t::cvarFlags, cvarTable_t::cvarName, cvarTable_t::defaultString, g_gametype, G_Printf(), G_RemapTeamShaders(), g_warmup, gameCvarTable, gameCvarTableSize, GT_MAX_GAME_TYPE, vmCvar_t::integer, cvarTable_t::modificationCount, vmCvar_t::modificationCount, qfalse, qtrue, cvarTable_t::teamShader, trap_Cvar_Register(), trap_Cvar_Set(), and cvarTable_t::vmCvar.
Referenced by G_InitGame().
G_RemapTeamShaders()
void G_RemapTeamShaders ()
Definition at line 329 of file g_main.c.
 {}
Referenced by G_InitGame(), G_RegisterCvars(), and G_UpdateCvars().
G_RunFrame()
void G_RunFrame (int levelTime)
Definition at line 1445 of file g_main.c.
{
     int         i;
     gentity_t   *ent;
     // if we are waiting for the level to restart, do nothing
     if ( level.restarted ) {
         return;
     }
     level.framenum++;
     level.previousTime = level.time;
     level.time = levelTime;
     // get any cvar changes
     G_UpdateCvars();
     //
     // go through all allocated objects
     //
     ent = &g_entities[0];
     for (i=0 ; i<level.num_entities ; i++, ent++) {
         if ( !ent->inuse ) {
             continue;
         }
         // clear events that are too old
         if ( level.time - ent->eventTime > EVENT_VALID_MSEC ) {
             if ( ent->s.event ) {
                 ent->s.event = 0;   // &= EV_EVENT_BITS;
                 if ( ent->client ) {
                     ent->client->ps.externalEvent = 0;
                     // predicted events should never be set to zero
                     //ent->client->ps.events[0] = 0;
                     //ent->client->ps.events[1] = 0;
                 }
             }
             if ( ent->freeAfterEvent ) {
                 G_FreeEntity( ent );
                 continue;
             } else if ( ent->unlinkAfterEvent ) {
                 ent->unlinkAfterEvent = qfalse;
                 trap_UnlinkEntity( ent );
             }
         }
         if ( ent->freeAfterEvent ) {
             continue;
         }
         if ( !ent->r.linked && ent->neverFree ) {
             continue;
         }
         if ( ent->s.eType == ET_MISSILE ) {
             G_RunUserMissile( ent );
             continue;
         }
         if ( ent->s.eType == ET_EXPLOSION ) {
             G_RunUserExplosion( ent );
             continue;
         }
         if ( ent->s.eType == ET_BEAMHEAD ) {
             G_RunUserMissile( ent );
         }
         if ( ent->s.eType == ET_MOVER ) {
             G_RunMover( ent );
             continue;
         }
         if ( i < MAX_CLIENTS ) {
             G_RunClient( ent );
             continue;
         }
         G_RunThink( ent );
     }
     // perform final fixups on the players
     ent = &g_entities[0];
     for (i=0 ; i < level.maxclients ; i++, ent++ ) {
         if ( ent->inuse ) {
             ClientEndFrame( ent );
         }
     }
     G_RadarUpdateCS();
     // see if it is time to do a tournement restart
     CheckTournament();
     // see if it is time to end the level
     CheckExitRules();
     // update to team status?
     CheckTeamStatus();
     // cancel vote if timed out
     CheckVote();
     // check team votes
     CheckTeamVote( TEAM_RED );
     CheckTeamVote( TEAM_BLUE );
     // for tracking changes
     CheckCvars();
     if (g_listEntity.integer) {
         for (i = 0; i < MAX_GENTITIES; i++) {
             G_Printf("%4i: %s\n", i, g_entities[i].classname);
         }
         trap_Cvar_Set("g_listEntity", "0");
     }
 }
References CheckCvars(), CheckExitRules(), CheckTeamStatus(), CheckTeamVote(), CheckTournament(), CheckVote(), ClientEndFrame(), ET_BEAMHEAD, ET_EXPLOSION, ET_MISSILE, ET_MOVER, EVENT_VALID_MSEC, g_entities, G_FreeEntity(), g_listEntity, G_Printf(), G_RadarUpdateCS(), G_RunClient(), G_RunMover(), G_RunThink(), G_RunUserExplosion(), G_RunUserMissile(), G_UpdateCvars(), vmCvar_t::integer, MAX_CLIENTS, MAX_GENTITIES, qfalse, TEAM_BLUE, TEAM_RED, trap_Cvar_Set(), and trap_UnlinkEntity().
Referenced by vmMain().
G_RunThink()
void G_RunThink (gentity_t * ent)
Definition at line 1420 of file g_main.c.
{
     float   thinktime;
     thinktime = ent->nextthink;
     if (thinktime <= 0) {
         return;
     }
     if (thinktime > level.time) {
         return;
     }
     ent->nextthink = 0;
     if (!ent->think) {
         G_Error ( "NULL ent->think");
     }
     ent->think (ent);
 }
References G_Error().
Referenced by G_RunFrame(), G_RunMover(), and G_RunUserMissile().
G_ShutdownGame()
void G_ShutdownGame (int restart)
Definition at line 502 of file g_main.c.
{
     G_Printf ("==== ShutdownGame ====\n");
     if ( level.logFile ) {
         G_LogPrintf("ShutdownGame:\n" );
         G_LogPrintf("------------------------------------------------------------\n" );
         trap_FS_FCloseFile( level.logFile );
         level.logFile = 0;
     }
     // write all the client session data so we can get it back
     G_WriteSessionData();
 }
References G_LogPrintf(), G_Printf(), G_WriteSessionData(), and trap_FS_FCloseFile().
Referenced by vmMain().
G_UpdateCvars()
void G_UpdateCvars (void)
Definition at line 371 of file g_main.c.
{
     int         i;
     cvarTable_t *cv;
     qboolean remapped = qfalse;
     for ( i = 0, cv = gameCvarTable ; i < gameCvarTableSize ; i++, cv++ ) {
         if ( cv->vmCvar ) {
             trap_Cvar_Update( cv->vmCvar );
             if ( cv->modificationCount != cv->vmCvar->modificationCount ) {
                 cv->modificationCount = cv->vmCvar->modificationCount;
                 if ( cv->trackChange ) {
                     //trap_SendServerCommand( -1, va("print \"Server: %s changed to %s\n\"",cv->cvarName, cv->vmCvar->string ) );
                 }
                 if (cv->teamShader) {
                     remapped = qtrue;
                 }
             }
         }
     }
     if (remapped) {
         G_RemapTeamShaders();
     }
 }
References G_RemapTeamShaders(), gameCvarTable, gameCvarTableSize, cvarTable_t::modificationCount, vmCvar_t::modificationCount, qfalse, qtrue, cvarTable_t::teamShader, cvarTable_t::trackChange, trap_Cvar_Update(), and cvarTable_t::vmCvar.
Referenced by G_RunFrame().
LogExit()
void LogExit (const char * string)
Definition at line 1049 of file g_main.c.
{
     int             i, numSorted;
     gclient_t       *cl;
     G_LogPrintf( "Exit: %s\n", string );
     level.intermissionQueued = level.time;
     // this will keep the clients from playing any voice sounds
     // that will get cut off when the queued intermission starts
     trap_SetConfigstring( CS_INTERMISSION, "1" );
     // don't send more than 32 scores (FIXME?)
     numSorted = level.numConnectedClients;
     if ( numSorted > 32 ) {
         numSorted = 32;
     }
     if ( g_gametype.integer >= GT_TEAM ) {
         G_LogPrintf( "red:%i  blue:%i\n",
             level.teamScores[TEAM_RED], level.teamScores[TEAM_BLUE] );
     }
     for (i=0 ; i < numSorted ; i++) {
         int     ping;
         cl = &level.clients[level.sortedClients[i]];
         if ( cl->sess.sessionTeam == TEAM_SPECTATOR ) {
             continue;
         }
         if ( cl->pers.connected == CON_CONNECTING ) {
             continue;
         }
         ping = cl->ps.ping < 999 ? cl->ps.ping : 999;
         G_LogPrintf( "score: %i  ping: %i  client: %i %s\n", cl->ps.persistant[PERS_SCORE], ping, level.sortedClients[i],   cl->pers.netname );
     }
 }
References cl, CON_CONNECTING, CS_INTERMISSION, g_gametype, G_LogPrintf(), GT_TEAM, vmCvar_t::integer, PERS_SCORE, TEAM_BLUE, TEAM_RED, TEAM_SPECTATOR, and trap_SetConfigstring().
MoveClientToIntermission()
void MoveClientToIntermission (gentity_t * ent)
Definition at line 845 of file g_main.c.
{
     // take out of follow mode if needed
     if ( ent->client->sess.spectatorState == SPECTATOR_FOLLOW ) {
         StopFollowing( ent );
     }
     FindIntermissionPoint();
     // move to the spot
     VectorCopy( level.intermission_origin, ent->s.origin );
     VectorCopy( level.intermission_origin, ent->client->ps.origin );
     VectorCopy (level.intermission_angle, ent->client->ps.viewangles);
     ent->client->ps.pm_type = PM_INTERMISSION;
     // clean up powerup info
     memset( ent->client->ps.powerups, 0, sizeof(ent->client->ps.powerups) );
     ent->client->ps.eFlags = 0;
     ent->s.eFlags = 0;
     ent->s.eType = ET_GENERAL;
     ent->s.modelindex = 0;
     ent->s.loopSound = 0;
     ent->s.event = 0;
     ent->r.contents = 0;
 }
References ET_GENERAL, FindIntermissionPoint(), PM_INTERMISSION, SPECTATOR_FOLLOW, StopFollowing(), and VectorCopy.
Referenced by BeginIntermission(), and ClientSpawn().
PrintTeam()
void PrintTeam (int team, char * message)
Definition at line 1303 of file g_main.c.
{
     int i;
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if (level.clients[i].sess.sessionTeam != team)
             continue;
         trap_SendServerCommand( i, message );
     }
 }
References trap_SendServerCommand().
Referenced by SetLeader().
RemoveTournamentLoser()
void RemoveTournamentLoser (void)
Definition at line 636 of file g_main.c.
{
     int         clientNum;
     if ( level.numPlayingClients != 2 ) {
         return;
     }
     clientNum = level.sortedClients[1];
     if ( level.clients[ clientNum ].pers.connected != CON_CONNECTED ) {
         return;
     }
     // make them a spectator
     SetTeam( &g_entities[ clientNum ], "s" );
 }
References CON_CONNECTED, g_entities, and SetTeam().
Referenced by ExitLevel().
RemoveTournamentWinner()
void RemoveTournamentWinner (void)
Definition at line 658 of file g_main.c.
{
     int         clientNum;
     if ( level.numPlayingClients != 2 ) {
         return;
     }
     clientNum = level.sortedClients[0];
     if ( level.clients[ clientNum ].pers.connected != CON_CONNECTED ) {
         return;
     }
     // make them a spectator
     SetTeam( &g_entities[ clientNum ], "s" );
 }
References CON_CONNECTED, g_entities, and SetTeam().
ScoreIsTied()
qboolean ScoreIsTied (void)
Definition at line 1108 of file g_main.c.
{
     int     a, b;
     if ( level.numPlayingClients < 2 ) {
         return qfalse;
     }
     if ( g_gametype.integer >= GT_TEAM ) {
         return level.teamScores[TEAM_RED] == level.teamScores[TEAM_BLUE];
     }
     a = level.clients[level.sortedClients[0]].ps.persistant[PERS_SCORE];
     b = level.clients[level.sortedClients[1]].ps.persistant[PERS_SCORE];
     return a == b;
 }
References g_gametype, GT_TEAM, vmCvar_t::integer, PERS_SCORE, qfalse, TEAM_BLUE, and TEAM_RED.
SendScoreboardMessageToAllClients()
void SendScoreboardMessageToAllClients (void)
Definition at line 827 of file g_main.c.
{
     int     i;
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if ( level.clients[ i ].pers.connected == CON_CONNECTED ) {
             DeathmatchScoreboardMessage( g_entities + i );
         }
     }
 }
References CON_CONNECTED, DeathmatchScoreboardMessage(), and g_entities.
Referenced by BeginIntermission(), and CalculateRanks().
SetLeader()
void SetLeader (int team, int client)
Definition at line 1318 of file g_main.c.
{
     int i;
     if ( level.clients[client].pers.connected == CON_DISCONNECTED ) {
         PrintTeam(team, va("print \"%s is not connected\n\"", level.clients[client].pers.netname) );
         return;
     }
     if (level.clients[client].sess.sessionTeam != team) {
         PrintTeam(team, va("print \"%s is not on the team anymore\n\"", level.clients[client].pers.netname) );
         return;
     }
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if (level.clients[i].sess.sessionTeam != team)
             continue;
         if (level.clients[i].sess.teamLeader) {
             level.clients[i].sess.teamLeader = qfalse;
             ClientUserinfoChanged(i);
         }
     }
     level.clients[client].sess.teamLeader = qtrue;
     ClientUserinfoChanged( client );
     PrintTeam(team, va("print \"%s is the new team leader\n\"", level.clients[client].pers.netname) );
 }
References ClientUserinfoChanged(), CON_DISCONNECTED, PrintTeam(), qfalse, qtrue, and va().
Referenced by CheckTeamVote(), and SetTeam().
SortRanks()
int QDECL SortRanks (const void * a, const void * b)
Definition at line 703 of file g_main.c.
{
     gclient_t   *ca, *cb;
     ca = &level.clients[*(int *)a];
     cb = &level.clients[*(int *)b];
     // sort special clients last
     if ( ca->sess.spectatorState == SPECTATOR_SCOREBOARD || ca->sess.spectatorClient < 0 ) {
         return 1;
     }
     if ( cb->sess.spectatorState == SPECTATOR_SCOREBOARD || cb->sess.spectatorClient < 0  ) {
         return -1;
     }
     // then connecting clients
     if ( ca->pers.connected == CON_CONNECTING ) {
         return 1;
     }
     if ( cb->pers.connected == CON_CONNECTING ) {
         return -1;
     }
     // then spectators
     if ( ca->sess.sessionTeam == TEAM_SPECTATOR && cb->sess.sessionTeam == TEAM_SPECTATOR ) {
         if ( ca->sess.spectatorNum > cb->sess.spectatorNum ) {
             return -1;
         }
         if ( ca->sess.spectatorNum < cb->sess.spectatorNum ) {
             return 1;
         }
         return 0;
     }
     if ( ca->sess.sessionTeam == TEAM_SPECTATOR ) {
         return 1;
     }
     if ( cb->sess.sessionTeam == TEAM_SPECTATOR ) {
         return -1;
     }
     // then sort by score
     if ( ca->ps.persistant[PERS_SCORE]
         > cb->ps.persistant[PERS_SCORE] ) {
         return -1;
     }
     if ( ca->ps.persistant[PERS_SCORE]
         < cb->ps.persistant[PERS_SCORE] ) {
         return 1;
     }
     return 0;
 }
References CON_CONNECTING, PERS_SCORE, SPECTATOR_SCOREBOARD, and TEAM_SPECTATOR.
Referenced by CalculateRanks().
vmMain()
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
Definition at line 215 of file g_main.c.
{
     switch ( command ) {
         case GAME_INIT:
             G_InitGame( arg0, arg1, arg2 );
             return 0;
         case GAME_SHUTDOWN:
             G_ShutdownGame( arg0 );
             return 0;
         case GAME_CLIENT_CONNECT:
         return (intptr_t)ClientConnect( arg0, arg1 );
         case GAME_CLIENT_THINK:
             ClientThink( arg0 );
             return 0;
         case GAME_CLIENT_USERINFO_CHANGED:
             ClientUserinfoChanged( arg0 );
             return 0;
         case GAME_CLIENT_DISCONNECT:
             ClientDisconnect( arg0 );
             return 0;
         case GAME_CLIENT_BEGIN:
             ClientBegin( arg0 );
             return 0;
         case GAME_CLIENT_COMMAND:
             ClientCommand( arg0 );
             return 0;
         case GAME_RUN_FRAME:
             G_RunFrame( arg0 );
             return 0;
         case GAME_CONSOLE_COMMAND:
             return ConsoleCommand();
     }
     return -1;
 }
References ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientThink(), ClientUserinfoChanged(), ConsoleCommand(), G_InitGame(), G_RunFrame(), G_ShutdownGame(), GAME_CLIENT_BEGIN, GAME_CLIENT_COMMAND, GAME_CLIENT_CONNECT, GAME_CLIENT_DISCONNECT, GAME_CLIENT_THINK, GAME_CLIENT_USERINFO_CHANGED, GAME_CONSOLE_COMMAND, GAME_INIT, GAME_RUN_FRAME, GAME_SHUTDOWN, and intptr_t().
Variable Documentation
g_allowAdvancedMelee
vmCvar_t g_allowAdvancedMelee
Definition at line 99 of file g_main.c.
g_allowBallFlip
vmCvar_t g_allowBallFlip
Definition at line 93 of file g_main.c.
g_allowBlock
vmCvar_t g_allowBlock
Definition at line 98 of file g_main.c.
g_allowBoost
vmCvar_t g_allowBoost
Definition at line 89 of file g_main.c.
g_allowBreakLimit
vmCvar_t g_allowBreakLimit
Definition at line 95 of file g_main.c.
g_allowFly
vmCvar_t g_allowFly
Definition at line 90 of file g_main.c.
g_allowJump
vmCvar_t g_allowJump
Definition at line 92 of file g_main.c.
g_allowLockon
vmCvar_t g_allowLockon
Definition at line 97 of file g_main.c.
g_allowMelee
vmCvar_t g_allowMelee
Definition at line 96 of file g_main.c.
g_allowOverheal
vmCvar_t g_allowOverheal
Definition at line 94 of file g_main.c.
g_allowScoreboard
vmCvar_t g_allowScoreboard
Definition at line 87 of file g_main.c.
g_allowSoar
vmCvar_t g_allowSoar
Definition at line 88 of file g_main.c.
g_allowTiers
vmCvar_t g_allowTiers
Definition at line 86 of file g_main.c.
g_allowVote
vmCvar_t g_allowVote
Definition at line 71 of file g_main.c.
Referenced by Cmd_CallTeamVote_f(), and Cmd_CallVote_f().
g_allowZanzoken
vmCvar_t g_allowZanzoken
Definition at line 91 of file g_main.c.
g_banIPs
vmCvar_t g_banIPs
Definition at line 74 of file g_main.c.
Referenced by G_ProcessIPBans().
g_blood
vmCvar_t g_blood
Definition at line 68 of file g_main.c.
g_breakLimitRate
vmCvar_t g_breakLimitRate
Definition at line 85 of file g_main.c.
Referenced by syncTier().
g_capturelimit
vmCvar_t g_capturelimit
Definition at line 44 of file g_main.c.
g_cheats
vmCvar_t g_cheats
Definition at line 51 of file g_main.c.
Referenced by CheatsOk(), and Cmd_SetViewpos_f().
g_clients
gclient_t g_clients[MAX_CLIENTS]
Definition at line 39 of file g_main.c.
Referenced by G_InitGame().
g_debugAlloc
vmCvar_t g_debugAlloc
Definition at line 58 of file g_main.c.
Referenced by G_Alloc().
g_debugDamage
vmCvar_t g_debugDamage
Definition at line 57 of file g_main.c.
g_debugMove
vmCvar_t g_debugMove
Definition at line 56 of file g_main.c.
Referenced by ClientThink_real().
g_dedicated
vmCvar_t g_dedicated
Definition at line 50 of file g_main.c.
Referenced by ConsoleCommand(), G_LogPrintf(), G_Say(), and G_Voice().
g_dmflags
vmCvar_t g_dmflags
Definition at line 41 of file g_main.c.
Referenced by ClientThink_real().
g_doWarmup
vmCvar_t g_doWarmup
Definition at line 64 of file g_main.c.
Referenced by SP_worldspawn().
g_entities
gentity_t g_entities[MAX_GENTITIES]
Definition at line 38 of file g_main.c.
Referenced by __attribute__(), AddTournamentPlayer(), BeginIntermission(), CheatsOk(), CheckTeamStatus(), ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientEvents(), ClientImpacts(), ClientNumberFromString(), ClientSpawn(), ClientThink(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_GameCommand_f(), Cmd_LevelShot_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_VoiceTell_f(), Cmd_Vote_f(), Cmd_Where_f(), Fire_UserWeapon(), G_DetachUserWeapon(), G_EntitiesFree(), G_ExplodeUserWeapon(), G_Find(), G_FindTeams(), G_ImpactUserWeapon(), G_InitGame(), G_InitGentity(), G_MoverPush(), G_RadarUpdateCS(), G_RankClientDisconnect(), G_RankDamage(), G_RankRunFrame(), G_RemoveUserWeapon(), G_RunFrame(), G_RunUserMissile(), G_Say(), G_SayTo(), G_Spawn(), G_TestEntityPosition(), G_TouchTriggers(), G_UserRadiusDamage(), G_UserWeaponDamage(), G_Voice(), G_VoiceTo(), LockonCheck(), RemoveTournamentLoser(), RemoveTournamentWinner(), SendScoreboardMessageToAllClients(), SP_worldspawn(), SpawnModelOnVictoryPad(), SpawnPodium(), SpotWouldTelefrag(), StopFollowing(), Svcmd_EntityList_f(), Svcmd_ForceTeam_f(), target_location_linkup(), Team_ForceGesture(), TeamplayInfoMessage(), Think_CylinderHoming(), Think_Homing(), Think_ProxDet(), UpdateTournamentInfo(), Use_Target_Print(), and UserHitscan_Fire().
g_filterBan
vmCvar_t g_filterBan
Definition at line 75 of file g_main.c.
Referenced by G_FilterPacket().
g_forcerespawn
vmCvar_t g_forcerespawn
Definition at line 54 of file g_main.c.
g_fraglimit
vmCvar_t g_fraglimit
Definition at line 42 of file g_main.c.
Referenced by G_RankRunFrame().
g_friendlyFire
vmCvar_t g_friendlyFire
Definition at line 45 of file g_main.c.
g_gametype
vmCvar_t g_gametype
Definition at line 40 of file g_main.c.
Referenced by BeginIntermission(), CalculateRanks(), CheckTournament(), ClientBegin(), ClientConnect(), ClientDisconnect(), ClientSpawn(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_LevelShot_f(), Cmd_Team_f(), ExitLevel(), G_InitGame(), G_InitSessionData(), G_InitWorldSession(), G_RankRunFrame(), G_RegisterCvars(), G_Say(), G_SayTo(), G_SpawnGEntityFromSpawnVars(), G_Voice(), G_VoiceTo(), G_WriteSessionData(), LogExit(), OnSameTeam(), ScoreIsTied(), SetTeam(), Svcmd_AbortPodium_f(), Team_InitGame(), and Team_SetFlagStatus().
g_inactivity
vmCvar_t g_inactivity
Definition at line 55 of file g_main.c.
Referenced by ClientInactivityTimer(), and ClientSpawn().
g_knockback
vmCvar_t g_knockback
Definition at line 52 of file g_main.c.
g_listEntity
vmCvar_t g_listEntity
Definition at line 80 of file g_main.c.
Referenced by G_RunFrame().
g_logfile
vmCvar_t g_logfile
Definition at line 66 of file g_main.c.
Referenced by G_InitGame().
g_logfileSync
vmCvar_t g_logfileSync
Definition at line 67 of file g_main.c.
Referenced by G_InitGame().
g_maxclients
vmCvar_t g_maxclients
Definition at line 48 of file g_main.c.
Referenced by CheckTeamStatus(), ExitLevel(), G_InitGame(), G_RadarUpdateCS(), and TeamplayInfoMessage().
g_maxGameClients
vmCvar_t g_maxGameClients
Definition at line 49 of file g_main.c.
Referenced by G_InitSessionData(), and SetTeam().
g_motd
vmCvar_t g_motd
Definition at line 61 of file g_main.c.
Referenced by SP_worldspawn().
g_needpass
vmCvar_t g_needpass
Definition at line 47 of file g_main.c.
g_password
vmCvar_t g_password
Definition at line 46 of file g_main.c.
Referenced by CheckCvars(), and ClientConnect().
g_podiumDist
vmCvar_t g_podiumDist
Definition at line 69 of file g_main.c.
g_podiumDrop
vmCvar_t g_podiumDrop
Definition at line 70 of file g_main.c.
g_pointGravity
vmCvar_t g_pointGravity
Definition at line 102 of file g_main.c.
Referenced by ClientSpawn(), and ClientUserinfoChanged().
g_powerlevel
vmCvar_t g_powerlevel
Definition at line 83 of file g_main.c.
Referenced by ClientBegin(), and ClientSpawn().
g_powerlevelMaximum
vmCvar_t g_powerlevelMaximum
Definition at line 84 of file g_main.c.
Referenced by ClientBegin(), and ClientSpawn().
g_quadfactor
vmCvar_t g_quadfactor
Definition at line 53 of file g_main.c.
g_quickTransformCost
vmCvar_t g_quickTransformCost
Definition at line 103 of file g_main.c.
Referenced by checkTierUpTransformation().
g_quickTransformCostPerTier
vmCvar_t g_quickTransformCostPerTier
Definition at line 104 of file g_main.c.
Referenced by checkTierUpTransformation().
g_quickZanzokenCost
vmCvar_t g_quickZanzokenCost
Definition at line 105 of file g_main.c.
Referenced by syncTier().
g_quickZanzokenDistance
vmCvar_t g_quickZanzokenDistance
Definition at line 106 of file g_main.c.
Referenced by syncTier().
g_rankings
vmCvar_t g_rankings
Definition at line 79 of file g_main.c.
g_restarted
vmCvar_t g_restarted
Definition at line 65 of file g_main.c.
Referenced by SP_worldspawn().
g_rolling
vmCvar_t g_rolling
Definition at line 100 of file g_main.c.
Referenced by ClientSpawn(), and ClientUserinfoChanged().
g_running
vmCvar_t g_running
Definition at line 101 of file g_main.c.
Referenced by ClientSpawn(), and ClientUserinfoChanged().
g_smoothClients
vmCvar_t g_smoothClients
Definition at line 76 of file g_main.c.
g_synchronousClients
vmCvar_t g_synchronousClients
Definition at line 62 of file g_main.c.
Referenced by ClientThink(), and G_RunClient().
g_teamAutoJoin
vmCvar_t g_teamAutoJoin
Definition at line 72 of file g_main.c.
Referenced by G_InitSessionData().
g_teamForceBalance
vmCvar_t g_teamForceBalance
Definition at line 73 of file g_main.c.
Referenced by SetTeam().
g_timelimit
vmCvar_t g_timelimit
Definition at line 43 of file g_main.c.
Referenced by G_RankRunFrame().
g_verboseParse
vmCvar_t g_verboseParse
Definition at line 82 of file g_main.c.
Referenced by G_weapPhys_AddDefinitionRef(), G_weapPhys_AddImportRef(), G_weapPhys_AddLinkRef(), G_weapPhys_LoadFile(), G_weapPhys_Parse(), G_weapPhys_ParseCategories(), and G_weapPhys_ParseDefinition().
g_warmup
vmCvar_t g_warmup
Definition at line 63 of file g_main.c.
Referenced by CheckTournament(), and G_RegisterCvars().
g_weaponRespawn
vmCvar_t g_weaponRespawn
Definition at line 59 of file g_main.c.
g_weaponTeamRespawn
vmCvar_t g_weaponTeamRespawn
Definition at line 60 of file g_main.c.
gameCvarTable
cvarTable_t gameCvarTable[] static
Definition at line 108 of file g_main.c.
Referenced by G_RegisterCvars(), and G_UpdateCvars().
gameCvarTableSize
int gameCvarTableSize = ARRAY_LEN(gameCvarTable) static
Definition at line 198 of file g_main.c.
Referenced by G_RegisterCvars(), and G_UpdateCvars().
level
level_locals_t level
Definition at line 26 of file g_main.c.
pmove_fixed
vmCvar_t pmove_fixed
Definition at line 77 of file g_main.c.
Referenced by CG_PredictPlayerState(), and ClientThink_real().
pmove_msec
vmCvar_t pmove_msec
Definition at line 78 of file g_main.c.
Referenced by CG_PredictPlayerState(), and ClientThink_real().