ZEQ2-Lite: Engine/libspeex/jitter.c File Reference
jitter.c File Reference
#include "arch.h"
#include <speex/speex.h>
#include <speex/speex_bits.h>
#include <speex/speex_jitter.h>
#include "os_support.h"
Data Structures
struct JitterBuffer
Jitter buffer structure.
struct TimingBuffer
Buffer that keeps the time of arrival of the latest packets.
Macros
#define GE32(a, b) (((spx_int32_t)((a)-(b)))>=0)
#define GT32(a, b) (((spx_int32_t)((a)-(b)))>0)
#define LE32(a, b) (((spx_int32_t)((a)-(b)))<=0)
#define LT32(a, b) (((spx_int32_t)((a)-(b)))<0)
#define MAX_BUFFERS 3
#define MAX_TIMINGS 20
#define NULL 0
#define ROUND_DOWN(x, step) ((x)<0 ? ((x)-(step)+1)/(step)*(step) : (x)/(step)*(step))
#define SPEEX_JITTER_MAX_BUFFER_SIZE 200
Maximum number of packets in jitter buffer.
#define TOP_DELAY 20
#define TSUB(a, b) ((spx_int32_t)((a)-(b)))
Functions
static int _jitter_buffer_update_delay (JitterBuffer *jitter, JitterBufferPacket *packet, spx_int32_t *start_offset)
static spx_int16_t compute_opt_delay (JitterBuffer *jitter)
Based on available data, this computes the optimal delay for the jitter buffer.
int jitter_buffer_ctl (JitterBuffer *jitter, int request, void *ptr)
Used like the ioctl function to control the jitter buffer parameters.
void jitter_buffer_destroy (JitterBuffer *jitter)
Destroy jitter buffer.
int jitter_buffer_get (JitterBuffer *jitter, JitterBufferPacket *packet, spx_int32_t desired_span, spx_int32_t *start_offset)
Get one packet from the jitter buffer.
int jitter_buffer_get_another (JitterBuffer *jitter, JitterBufferPacket *packet)
Used right after jitter_buffer_get() to obtain another packet that would have the same timestamp.
int jitter_buffer_get_pointer_timestamp (JitterBuffer *jitter)
Get pointer timestamp of jitter buffer.
JitterBuffer * jitter_buffer_init (int step_size)
Initialise jitter buffer.
void jitter_buffer_put (JitterBuffer *jitter, const JitterBufferPacket *packet)
Put one packet into the jitter buffer.
void jitter_buffer_remaining_span (JitterBuffer *jitter, spx_uint32_t rem)
Telling the jitter buffer about the remaining data in the application buffer.
void jitter_buffer_reset (JitterBuffer *jitter)
Reset jitter buffer.
void jitter_buffer_tick (JitterBuffer *jitter)
Advance by one tick.
int jitter_buffer_update_delay (JitterBuffer *jitter, JitterBufferPacket *packet, spx_int32_t *start_offset)
static void shift_timings (JitterBuffer *jitter, spx_int16_t amount)
Compensate all timings when we do an adjustment of the buffering.
static void tb_add (struct TimingBuffer *tb, spx_int16_t timing)
static void tb_init (struct TimingBuffer *tb)
static void update_timings (JitterBuffer *jitter, spx_int32_t timing)
Take the following timing into consideration for future calculations.
Macro Definition Documentation
GE32
#define GE32 (a, b) (((spx_int32_t)((a)-(b)))>=0)
Definition at line 72 of file jitter.c.
GT32
#define GT32 (a, b) (((spx_int32_t)((a)-(b)))>0)
Definition at line 71 of file jitter.c.
LE32
#define LE32 (a, b) (((spx_int32_t)((a)-(b)))<=0)
Definition at line 74 of file jitter.c.
LT32
#define LT32 (a, b) (((spx_int32_t)((a)-(b)))<0)
Definition at line 73 of file jitter.c.
MAX_BUFFERS
#define MAX_BUFFERS 3
Definition at line 79 of file jitter.c.
MAX_TIMINGS
#define MAX_TIMINGS 20
Definition at line 78 of file jitter.c.
NULL
#define NULL 0
Definition at line 64 of file jitter.c.
ROUND_DOWN
#define ROUND_DOWN (x, step) ((x)<0 ? ((x)-(step)+1)/(step)*(step) : (x)/(step)*(step))
Definition at line 76 of file jitter.c.
SPEEX_JITTER_MAX_BUFFER_SIZE
#define SPEEX_JITTER_MAX_BUFFER_SIZE 200
Maximum number of packets in jitter buffer.
Definition at line 67 of file jitter.c.
TOP_DELAY
#define TOP_DELAY 20
Definition at line 80 of file jitter.c.
TSUB
#define TSUB (a, b) ((spx_int32_t)((a)-(b)))
Definition at line 69 of file jitter.c.
Function Documentation
_jitter_buffer_update_delay()
static int _jitter_buffer_update_delay (JitterBuffer * jitter, JitterBufferPacket * packet, spx_int32_t * start_offset) static
Definition at line 713 of file jitter.c.
 {
    spx_int16_t opt = compute_opt_delay(jitter);
    /*fprintf(stderr, "opt adjustment is %d ", opt);*/
    if (opt < 0)
    {
       shift_timings(jitter, -opt);
       jitter->pointer_timestamp += opt;
       jitter->interp_requested = -opt;
       /*fprintf (stderr, "Decision to interpolate %d samples\n", -opt);*/
    } else if (opt > 0)
    {
       shift_timings(jitter, -opt);
       jitter->pointer_timestamp += opt;
       /*fprintf (stderr, "Decision to drop %d samples\n", opt);*/
    }
    return opt;
 }
References compute_opt_delay(), opt(), and shift_timings().
Referenced by jitter_buffer_remaining_span(), jitter_buffer_tick(), and jitter_buffer_update_delay().
compute_opt_delay()
static spx_int16_t compute_opt_delay (JitterBuffer * jitter) static
Based on available data, this computes the optimal delay for the jitter buffer.
The optimised function is in timestamp units and is: cost = delay + late_factor*[number of frames that would be late if we used that delay]
Parameters
tb Array of buffers
late_factor Equivalent cost of a late frame (in timestamp units)
Definition at line 175 of file jitter.c.
 {
    int i;
    spx_int16_t opt=0;
    spx_int32_t best_cost=0x7fffffff;
    int late = 0;
    int pos[MAX_BUFFERS];
    int tot_count;
    float late_factor;
    int penalty_taken = 0;
    int best = 0;
    int worst = 0;
    spx_int32_t deltaT;
    struct TimingBuffer *tb;
    tb = jitter->_tb;
    /* Number of packet timings we have received (including those we didn't keep) */
    tot_count = 0;
    for (i=0;i<MAX_BUFFERS;i++)
       tot_count += tb[i].curr_count;
    if (tot_count==0)
       return 0;
    /* Compute cost for one lost packet */
    if (jitter->latency_tradeoff != 0)
       late_factor = jitter->latency_tradeoff * 100.0f / tot_count;
    else
       late_factor = jitter->auto_tradeoff * jitter->window_size/tot_count;
    /*fprintf(stderr, "late_factor = %f\n", late_factor);*/
    for (i=0;i<MAX_BUFFERS;i++)
       pos[i] = 0;
    /* Pick the TOP_DELAY "latest" packets (doesn't need to actually be late
       for the current settings) */
    for (i=0;i<TOP_DELAY;i++)
    {
       int j;
       int next=-1;
       int latest = 32767;
       /* Pick latest amoung all sub-windows */
       for (j=0;j<MAX_BUFFERS;j++)
       {
          if (pos[j] < tb[j].filled && tb[j].timing[pos[j]] < latest)
          {
             next = j;
             latest = tb[j].timing[pos[j]];
          }
       }
       if (next != -1)
       {
          spx_int32_t cost;
          if (i==0)
             worst = latest;
          best = latest;
          latest = ROUND_DOWN(latest, jitter->delay_step);
          pos[next]++;
          /* Actual cost function that tells us how bad using this delay would be */
          cost = -latest + late_factor*late;
          /*fprintf(stderr, "cost %d = %d + %f * %d\n", cost, -latest, late_factor, late);*/
          if (cost < best_cost)
          {
             best_cost = cost;
             opt = latest;
          }
       } else {
          break;
       }
       /* For the next timing we will consider, there will be one more late packet to count */
       late++;
       /* Two-frame penalty if we're going to increase the amount of late frames (hysteresis) */
       if (latest >= 0 && !penalty_taken)
       {
          penalty_taken = 1;
          late+=2;
       }
    }
    deltaT = best-worst;
    /* This is a default "automatic latency tradeoff" when none is provided */
    jitter->auto_tradeoff = 1 + deltaT/TOP_DELAY;
    /*fprintf(stderr, "auto_tradeoff = %d (%d %d %d)\n", jitter->auto_tradeoff, best, worst, i);*/
    /* FIXME: Compute a short-term estimate too and combine with the long-term one */
    /* Prevents reducing the buffer size when we haven't really had much data */
    if (tot_count < TOP_DELAY && opt > 0)
       return 0;
    return opt;
 }
References TimingBuffer::curr_count, TimingBuffer::filled, MAX_BUFFERS, opt(), ROUND_DOWN, TimingBuffer::timing, and TOP_DELAY.
Referenced by _jitter_buffer_update_delay(), and jitter_buffer_get().
shift_timings()
static void shift_timings (JitterBuffer * jitter, spx_int16_t amount) static
Compensate all timings when we do an adjustment of the buffering.
Definition at line 356 of file jitter.c.
 {
    int i, j;
    for (i=0;i<MAX_BUFFERS;i++)
    {
       for (j=0;j<jitter->timeBuffers[i]->filled;j++)
          jitter->timeBuffers[i]->timing[j] += amount;
    }
 }
References MAX_BUFFERS.
Referenced by _jitter_buffer_update_delay(), and jitter_buffer_get().
tb_add()
static void tb_add (struct TimingBuffer * tb, spx_int16_t timing) static
Definition at line 97 of file jitter.c.
 {
    int pos;
    /* Discard packet that won't make it into the list because they're too early */
    if (tb->filled >= MAX_TIMINGS && timing >= tb->timing[tb->filled-1])
    {
       tb->curr_count++;
       return;
    }
    /* Find where the timing info goes in the sorted list */
    pos = 0;
    /* FIXME: Do bisection instead of linear search */
    while (pos<tb->filled && timing >= tb->timing[pos])
    {
       pos++;
    }
    speex_assert(pos <= tb->filled && pos < MAX_TIMINGS);
    /* Shift everything so we can perform the insertion */
    if (pos < tb->filled)
    {
       int move_size = tb->filled-pos;
       if (tb->filled == MAX_TIMINGS)
          move_size -= 1;
       SPEEX_MOVE(&tb->timing[pos+1], &tb->timing[pos], move_size);
       SPEEX_MOVE(&tb->counts[pos+1], &tb->counts[pos], move_size);
    }
    /* Insert */
    tb->timing[pos] = timing;
    tb->counts[pos] = tb->curr_count;
    tb->curr_count++;
    if (tb->filled<MAX_TIMINGS)
       tb->filled++;
 }
References TimingBuffer::counts, TimingBuffer::curr_count, TimingBuffer::filled, MAX_TIMINGS, speex_assert, SPEEX_MOVE, and TimingBuffer::timing.
Referenced by update_timings().
tb_init()
static void tb_init (struct TimingBuffer * tb) static
Definition at line 90 of file jitter.c.
 {
    tb->filled = 0;
    tb->curr_count = 0;
 }
References TimingBuffer::curr_count, and TimingBuffer::filled.
Referenced by jitter_buffer_reset(), and update_timings().
update_timings()
static void update_timings (JitterBuffer * jitter, spx_int32_t timing) static
Take the following timing into consideration for future calculations.
Definition at line 335 of file jitter.c.
 {
    if (timing < -32767)
       timing = -32767;
    if (timing > 32767)
       timing = 32767;
    /* If the current sub-window is full, perform a rotation and discard oldest sub-widow */
    if (jitter->timeBuffers[0]->curr_count >= jitter->subwindow_size)
    {
       int i;
       /*fprintf(stderr, "Rotate buffer\n");*/
       struct TimingBuffer *tmp = jitter->timeBuffers[MAX_BUFFERS-1];
       for (i=MAX_BUFFERS-1;i>=1;i--)
          jitter->timeBuffers[i] = jitter->timeBuffers[i-1];
       jitter->timeBuffers[0] = tmp;
       tb_init(jitter->timeBuffers[0]);
    }
    tb_add(jitter->timeBuffers[0], timing);
 }
References MAX_BUFFERS, tb_add(), tb_init(), and TimingBuffer::timing.
Referenced by jitter_buffer_get(), and jitter_buffer_put().