ZEQ2-Lite: Source/Engine/renderer/tr_light.c File Reference
tr_light.c File Reference
#include "tr_local.h"
Macros
#define DLIGHT_AT_RADIUS 16
#define DLIGHT_MINIMUM_RADIUS 16
Functions
static void LogLight (trRefEntity_t *ent)
void R_DlightBmodel (bmodel_t *bmodel)
int R_LightForPoint (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
void R_SetupEntityLighting (const trRefdef_t *refdef, trRefEntity_t *ent)
static void R_SetupEntityLightingGrid (trRefEntity_t *ent)
void R_TransformDlights (int count, dlight_t *dl, orientationr_t *or)
Variables
cvar_t * r_ambientScale
cvar_t * r_debugLight
cvar_t * r_directedScale
Macro Definition Documentation
DLIGHT_AT_RADIUS
#define DLIGHT_AT_RADIUS 16
Definition at line 26 of file tr_light.c.
DLIGHT_MINIMUM_RADIUS
#define DLIGHT_MINIMUM_RADIUS 16
Definition at line 29 of file tr_light.c.
Function Documentation
LogLight()
static void LogLight (trRefEntity_t * ent) static
Definition at line 251 of file tr_light.c.
{
     int max1, max2, max3;
     if ( !(ent->e.renderfx & RF_FIRST_PERSON ) ) {
         return;
     }
     max1 = ent->ambientLight[0];
     if ( ent->ambientLight[1] > max1 ) {
         max1 = ent->ambientLight[1];
     } else if ( ent->ambientLight[2] > max1 ) {
         max1 = ent->ambientLight[2];
     }
     max2 = ent->directedLight[0];
     if ( ent->directedLight[1] > max2 ) {
         max2 = ent->directedLight[1];
     } else if ( ent->directedLight[2] > max2 ) {
         max2 = ent->directedLight[2];
     }
     max3 = ent->dynamicLight[0];
     if ( ent->dynamicLight[1] > max3 ) {
         max3 = ent->dynamicLight[1];
     } else if ( ent->dynamicLight[2] > max3 ) {
         max3 = ent->dynamicLight[2];
     }
     ri.Printf( PRINT_ALL, "amb:%i  dir:%i  dyn:%i\n", max1, max2, max3 );
 }
References trRefEntity_t::ambientLight, trRefEntity_t::directedLight, trRefEntity_t::dynamicLight, trRefEntity_t::e, PRINT_ALL, refEntity_t::renderfx, RF_FIRST_PERSON, and ri.
Referenced by R_SetupEntityLighting().
R_DlightBmodel()
void R_DlightBmodel (bmodel_t * bmodel)
Definition at line 61 of file tr_light.c.
{
     int         i, j;
     dlight_t    *dl;
     int         mask;
     msurface_t  *surf;
     // transform all the lights
     R_TransformDlights( tr.refdef.num_dlights, tr.refdef.dlights, &tr.or );
     mask = 0;
     for ( i=0 ; i<tr.refdef.num_dlights ; i++ ) {
         dl = &tr.refdef.dlights[i];
         // see if the point is close enough to the bounds to matter
         for ( j = 0 ; j < 3 ; j++ ) {
             if ( dl->transformed[j] - bmodel->bounds[1][j] > dl->radius ) {
                 break;
             }
             if ( bmodel->bounds[0][j] - dl->transformed[j] > dl->radius ) {
                 break;
             }
         }
         if ( j < 3 ) {
             continue;
         }
         // we need to check this light
         mask |= 1 << i;
     }
     tr.currentEntity->needDlights = (mask != 0);
     // set the dlight bits in all the surfaces
     for ( i = 0 ; i < bmodel->numSurfaces ; i++ ) {
         surf = bmodel->firstSurface + i;
         if ( *surf->data == SF_FACE ) {
             ((srfSurfaceFace_t *)surf->data)->dlightBits[ tr.smpFrame ] = mask;
         } else if ( *surf->data == SF_GRID ) {
             ((srfGridMesh_t *)surf->data)->dlightBits[ tr.smpFrame ] = mask;
         } else if ( *surf->data == SF_TRIANGLES ) {
             ((srfTriangles_t *)surf->data)->dlightBits[ tr.smpFrame ] = mask;
         }
     }
 }
References bmodel_t::bounds, trGlobals_t::currentEntity, trRefdef_t::dlights, bmodel_t::firstSurface, trRefEntity_t::needDlights, trRefdef_t::num_dlights, bmodel_t::numSurfaces, trGlobals_t::or, R_TransformDlights(), trGlobals_t::refdef, SF_FACE, SF_GRID, SF_TRIANGLES, trGlobals_t::smpFrame, and tr.
Referenced by R_AddBrushModelSurfaces().
R_LightForPoint()
int R_LightForPoint (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
Definition at line 392 of file tr_light.c.
 {
     trRefEntity_t ent;
     if ( tr.world->lightGridData == NULL )
       return qfalse;
     Com_Memset(&ent, 0, sizeof(ent));
     VectorCopy( point, ent.e.origin );
     R_SetupEntityLightingGrid( &ent );
     VectorCopy(ent.ambientLight, ambientLight);
     VectorCopy(ent.directedLight, directedLight);
     VectorCopy(ent.lightDir, lightDir);
     return qtrue;
 }
References trRefEntity_t::ambientLight, Com_Memset, trRefEntity_t::directedLight, trRefEntity_t::e, trRefEntity_t::lightDir, world_t::lightGridData, NULL, refEntity_t::origin, qfalse, qtrue, R_SetupEntityLightingGrid(), tr, VectorCopy, and trGlobals_t::world.
Referenced by GetRefAPI().
R_SetupEntityLighting()
void R_SetupEntityLighting (const trRefdef_t * refdef, trRefEntity_t * ent)
Definition at line 290 of file tr_light.c.
{
     int             i;
     dlight_t        *dl;
     float           power;
     vec3_t          dir;
     float           d;
     vec3_t          lightDir;
     vec3_t          lightOrigin;
     // lighting calculations
     if ( ent->lightingCalculated ) {
         return;
     }
     ent->lightingCalculated = qtrue;
     //
     // trace a sample point down to find ambient light
     //
     if ( ent->e.renderfx & RF_LIGHTING_ORIGIN ) {
         // seperate lightOrigins are needed so an object that is
         // sinking into the ground can still be lit, and so
         // multi-part models can be lit identically
         VectorCopy( ent->e.lightingOrigin, lightOrigin );
     } else {
         VectorCopy( ent->e.origin, lightOrigin );
     }
     // if NOWORLDMODEL, only use dynamic lights (menu system, etc)
     if ( !(refdef->rdflags & RDF_NOWORLDMODEL )
         && tr.world->lightGridData ) {
         R_SetupEntityLightingGrid( ent );
     } else {
         ent->ambientLight[0] = ent->ambientLight[1] =
             ent->ambientLight[2] = tr.identityLight * 150;
         ent->directedLight[0] = ent->directedLight[1] =
             ent->directedLight[2] = tr.identityLight * 150;
         VectorCopy( tr.sunDirection, ent->lightDir );
     }
     // dynamic lights should have be set to 0.1 when there are no dynamic lights.
     VectorSet(ent->dynamicLight,0.1,0.1,0.1);
     // bonus items and view weapons have a fixed minimum add
     if ( 1 /* ent->e.renderfx & RF_MINLIGHT */ ) {
         // give everything a minimum light add
         ent->ambientLight[0] += tr.identityLight * 32;
         ent->ambientLight[1] += tr.identityLight * 32;
         ent->ambientLight[2] += tr.identityLight * 32;
     }
     //
     // modify the light by dynamic lights
     //
     d = VectorLength( ent->directedLight );
     VectorScale( ent->lightDir, d, lightDir );
     for ( i = 0 ; i < refdef->num_dlights ; i++ ) {
         dl = &refdef->dlights[i];
         VectorSubtract( dl->origin, lightOrigin, dir );
         d = VectorNormalize( dir );
         power = DLIGHT_AT_RADIUS * ( dl->radius * dl->radius );
         if ( d < DLIGHT_MINIMUM_RADIUS ) {
             d = DLIGHT_MINIMUM_RADIUS;
         }
         d = power / ( d * d );
         VectorMA( ent->directedLight, d, dl->color, ent->directedLight );
         VectorMA( ent->dynamicLight, d, dl->color, ent->dynamicLight );
         ent->lightDistance = d;
         VectorMA( lightDir, d, dir, lightDir );
     }
     // clamp ambient
     for ( i = 0 ; i < 3 ; i++ ) {
         if ( ent->ambientLight[i] > tr.identityLightByte ) {
             ent->ambientLight[i] = tr.identityLightByte;
         }
     }
     if ( r_debugLight->integer ) {
         LogLight( ent );
     }
     // save out the byte packet version
     ((byte *)&ent->ambientLightInt)[0] = ri.ftol(ent->ambientLight[0]);
     ((byte *)&ent->ambientLightInt)[1] = ri.ftol(ent->ambientLight[1]);
     ((byte *)&ent->ambientLightInt)[2] = ri.ftol(ent->ambientLight[2]);
     ((byte *)&ent->ambientLightInt)[3] = 0xff;
     // transform the direction to local space
     VectorNormalize( lightDir );
     ent->lightDir[0] = DotProduct( lightDir, ent->e.axis[0] );
     ent->lightDir[1] = DotProduct( lightDir, ent->e.axis[1] );
     ent->lightDir[2] = DotProduct( lightDir, ent->e.axis[2] );
 }
References trRefEntity_t::ambientLight, trRefEntity_t::ambientLightInt, refEntity_t::axis, dir, trRefEntity_t::directedLight, DLIGHT_AT_RADIUS, DLIGHT_MINIMUM_RADIUS, trRefdef_t::dlights, DotProduct, trRefEntity_t::dynamicLight, trRefEntity_t::e, refimport_t::ftol, trGlobals_t::identityLight, trGlobals_t::identityLightByte, trRefEntity_t::lightDir, trRefEntity_t::lightDistance, world_t::lightGridData, trRefEntity_t::lightingCalculated, refEntity_t::lightingOrigin, lightOrigin, LogLight(), trRefdef_t::num_dlights, refEntity_t::origin, qtrue, r_debugLight, R_SetupEntityLightingGrid(), RDF_NOWORLDMODEL, trRefdef_t::rdflags, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, ri, trGlobals_t::sunDirection, tr, VectorCopy, VectorLength(), VectorMA(), VectorNormalize(), VectorScale, VectorSet, VectorSubtract, and trGlobals_t::world.
Referenced by R_AddBrushModelSurfaces(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), and R_MDM_AddAnimSurfaces().
R_SetupEntityLightingGrid()
static void R_SetupEntityLightingGrid (trRefEntity_t * ent) static
Definition at line 126 of file tr_light.c.
{
     vec3_t  lightOrigin;
     int     pos[3];
     int     i, j;
     byte    *gridData;
     float   frac[3];
     int     gridStep[3];
     vec3_t  direction;
     float   totalFactor;
     if ( ent->e.renderfx & RF_LIGHTING_ORIGIN ) {
         // seperate lightOrigins are needed so an object that is
         // sinking into the ground can still be lit, and so
         // multi-part models can be lit identically
         VectorCopy( ent->e.lightingOrigin, lightOrigin );
     } else {
         VectorCopy( ent->e.origin, lightOrigin );
     }
     VectorSubtract( lightOrigin, tr.world->lightGridOrigin, lightOrigin );
     for ( i = 0 ; i < 3 ; i++ ) {
         float   v;
         v = lightOrigin[i]*tr.world->lightGridInverseSize[i];
         pos[i] = floor( v );
         frac[i] = v - pos[i];
         if ( pos[i] < 0 ) {
             pos[i] = 0;
         } else if ( pos[i] >= tr.world->lightGridBounds[i] - 1 ) {
             pos[i] = tr.world->lightGridBounds[i] - 1;
         }
     }
     VectorClear( ent->ambientLight );
     VectorClear( ent->directedLight );
     VectorClear( ent->dynamicLight );
     VectorClear( direction );
     assert( tr.world->lightGridData ); // NULL with -nolight maps
     // trilerp the light value
     gridStep[0] = 8;
     gridStep[1] = 8 * tr.world->lightGridBounds[0];
     gridStep[2] = 8 * tr.world->lightGridBounds[0] * tr.world->lightGridBounds[1];
     gridData = tr.world->lightGridData + pos[0] * gridStep[0]
         + pos[1] * gridStep[1] + pos[2] * gridStep[2];
     totalFactor = 0;
     for ( i = 0 ; i < 8 ; i++ ) {
         float   factor;
         byte    *data;
         int     lat, lng;
         vec3_t  normal;
         #if idppc
         float d0, d1, d2, d3, d4, d5;
         #endif
         factor = 1.0;
         data = gridData;
         for ( j = 0 ; j < 3 ; j++ ) {
             if ( i & (1<<j) ) {
                 factor *= frac[j];
                 data += gridStep[j];
             } else {
                 factor *= (1.0f - frac[j]);
             }
         }
         if ( !(data[0]+data[1]+data[2]) ) {
             continue;   // ignore samples in walls
         }
         totalFactor += factor;
         #if idppc
         d0 = data[0]; d1 = data[1]; d2 = data[2];
         d3 = data[3]; d4 = data[4]; d5 = data[5];
         ent->ambientLight[0] += factor * d0;
         ent->ambientLight[1] += factor * d1;
         ent->ambientLight[2] += factor * d2;
         ent->directedLight[0] += factor * d3;
         ent->directedLight[1] += factor * d4;
         ent->directedLight[2] += factor * d5;
         #else
         ent->ambientLight[0] += factor * data[0];
         ent->ambientLight[1] += factor * data[1];
         ent->ambientLight[2] += factor * data[2];
         ent->directedLight[0] += factor * data[3];
         ent->directedLight[1] += factor * data[4];
         ent->directedLight[2] += factor * data[5];
         #endif
         lat = data[7];
         lng = data[6];
         lat *= (FUNCTABLE_SIZE/256);
         lng *= (FUNCTABLE_SIZE/256);
         // decode X as cos( lat ) * sin( long )
         // decode Y as sin( lat ) * sin( long )
         // decode Z as cos( long )
         normal[0] = tr.sinTable[(lat+(FUNCTABLE_SIZE/4))&FUNCTABLE_MASK] * tr.sinTable[lng];
         normal[1] = tr.sinTable[lat] * tr.sinTable[lng];
         normal[2] = tr.sinTable[(lng+(FUNCTABLE_SIZE/4))&FUNCTABLE_MASK];
         VectorMA( direction, factor, normal, direction );
     }
     if ( totalFactor > 0 && totalFactor < 0.99 ) {
         totalFactor = 1.0f / totalFactor;
         VectorScale( ent->ambientLight, totalFactor, ent->ambientLight );
         VectorScale( ent->directedLight, totalFactor, ent->directedLight );
     }
     VectorScale( ent->ambientLight, r_ambientScale->value, ent->ambientLight );
     VectorScale( ent->directedLight, r_directedScale->value, ent->directedLight );
     VectorNormalize2( direction, ent->lightDir );
 }
References trRefEntity_t::ambientLight, trRefEntity_t::directedLight, trRefEntity_t::dynamicLight, trRefEntity_t::e, FUNCTABLE_MASK, FUNCTABLE_SIZE, trRefEntity_t::lightDir, world_t::lightGridBounds, world_t::lightGridData, world_t::lightGridInverseSize, world_t::lightGridOrigin, refEntity_t::lightingOrigin, lightOrigin, refEntity_t::origin, r_ambientScale, r_directedScale, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, trGlobals_t::sinTable, tr, VectorClear, VectorCopy, VectorMA(), VectorNormalize2(), VectorScale, VectorSubtract, and trGlobals_t::world.
Referenced by R_LightForPoint(), and R_SetupEntityLighting().
R_TransformDlights()
void R_TransformDlights (int count, dlight_t * dl, orientationr_t * or)
Definition at line 42 of file tr_light.c.
{
     int     i;
     vec3_t  temp;
     for ( i = 0 ; i < count ; i++, dl++ ) {
         VectorSubtract( dl->origin, or->origin, temp );
         dl->transformed[0] = DotProduct( temp, or->axis[0] );
         dl->transformed[1] = DotProduct( temp, or->axis[1] );
         dl->transformed[2] = DotProduct( temp, or->axis[2] );
     }
 }
References orientationr_t::axis, DotProduct, orientationr_t::origin, and VectorSubtract.
Referenced by R_DlightBmodel(), and RB_RenderDrawSurfList().
Variable Documentation
r_ambientScale
cvar_t* r_ambientScale
Definition at line 175 of file tr_init.c.
Referenced by R_Register(), and R_SetupEntityLightingGrid().
r_debugLight
cvar_t* r_debugLight
Definition at line 177 of file tr_init.c.
Referenced by R_Register(), and R_SetupEntityLighting().
r_directedScale
cvar_t* r_directedScale
Definition at line 176 of file tr_init.c.
Referenced by R_Register(), and R_SetupEntityLightingGrid().