ZEQ2-Lite: Source/Engine/renderer/tr_subs.c File Reference
tr_subs.c File Reference
#include "tr_local.h"
Functions
void QDECL Com_Error (int level, const char *error,...)
void QDECL Com_Printf (const char *msg,...)
Function Documentation
Com_Error()
void QDECL Com_Error (int level, const char * error, ...)
Definition at line 38 of file tr_subs.c.
 {
     va_list         argptr;
     char            text[1024];
     va_start(argptr, error);
     Q_vsnprintf(text, sizeof(text), error, argptr);
     va_end(argptr);
     ri.Error(level, "%s", text);
 }
References error(), Q_vsnprintf, and ri.
Referenced by __attribute__(), BaseWindingForPlane(), BG_EvaluateTrajectory(), BG_EvaluateTrajectoryDelta(), Cbuf_ExecuteText(), CheckWinding(), ChopWindingInPlace(), CIN_HandleForVideo(), CL_AddReliableCommand(), CL_CgameError(), CL_CgameSystemCalls(), CL_CheckForResend(), CL_ConfigstringModified(), CL_Disconnect_f(), CL_GetParseEntityState(), CL_GetServerCommand(), CL_GetSnapshot(), CL_GetUserCmd(), CL_InitCGame(), CL_InitRef(), CL_InitUI(), CL_JoystickEvent(), CL_NextDownload(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParsePacketEntities(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_PlayDemo_f(), CL_ReadDemoMessage(), CL_SetCGameTime(), CL_UISystemCalls(), ClipWindingEpsilon(), CM_AdjustAreaPortalState(), CM_AreasConnected(), CM_ClipHandleToModel(), CM_EdgePlaneNum(), CM_FindPlane(), CM_FindPlane2(), CM_FloodArea_r(), CM_GeneratePatchCollide(), CM_InlineModel(), CM_LeafArea(), CM_LeafCluster(), CM_LoadMap(), CM_PatchCollideFromGrid(), CM_SetBorderInward(), Cmd_RemoveCommandSafe(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadLeafSurfaces(), CMod_LoadNodes(), CMod_LoadPatches(), CMod_LoadPlanes(), CMod_LoadShaders(), CMod_LoadSubmodels(), COM_MatchToken(), Cvar_Get(), Cvar_SetSafe(), Cvar_Update(), DoSyscall(), END_CHUNK(), ErrJump(), Field_CustomDraw(), Field_VariableSizeDraw(), FreeWinding(), FS_CheckFilenameIsNotExecutable(), FS_CreatePath(), FS_FCloseFile(), FS_FCreateOpenPipeFile(), FS_FileForHandle(), FS_FileIsInPAK(), FS_FindVM(), FS_FOpenFileAppend(), FS_FOpenFileByMode(), FS_FOpenFileRead(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_FreeFile(), FS_FreeFileList(), FS_HandleForFile(), FS_InitFilesystem(), FS_ListFilteredFiles(), FS_Read(), FS_Read2(), FS_ReadFileDir(), FS_Rename(), FS_Restart(), FS_Seek(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), FS_Write(), FS_WriteFile(), Hex(), IN_Init(), Info_RemoveKey(), Info_RemoveKey_Big(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Info_ValueForKey(), MSG_Copy(), MSG_ReadBits(), MSG_ReadDeltaEntity(), MSG_WriteBits(), MSG_WriteByte(), MSG_WriteChar(), MSG_WriteDeltaEntity(), MSG_WriteShort(), Netchan_Transmit(), Q_strcat(), Q_strncpyz(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_StartSound(), S_Base_UpdateEntityPosition(), S_FindName(), S_Init(), SafeFS_Write(), SCR_DrawScreenField(), SCR_UpdateScreen(), START_CHUNK(), SV_AddEntitiesVisibleFromPoint(), SV_BuildClientSnapshot(), SV_DirectConnect(), SV_GameSystemCalls(), SV_GetConfigstring(), SV_GetServerinfo(), SV_GetUsercmd(), SV_GetUserinfo(), SV_InitGameProgs(), SV_QsortEntityNumbers(), SV_RestartGameProgs(), SV_SetBrushModel(), SV_SetConfigstring(), SV_SetUserinfo(), SV_Startup(), SV_SvEntityForGentity(), Sys_SendPacket(), VM_BlockCopy(), VM_Call(), VM_CallCompiled(), VM_CallInterpreted(), VM_Compile(), VM_Create(), VM_Free(), VM_PrepareInterpreter(), and VM_Restart().
Com_Printf()
void QDECL Com_Printf (const char * msg, ...)
Definition at line 26 of file tr_subs.c.
 {
     va_list         argptr;
     char            text[1024];
     va_start(argptr, msg);
     Q_vsnprintf(text, sizeof(text), msg, argptr);
     va_end(argptr);
     ri.Printf(PRINT_ALL, "%s", text);
 }
References PRINT_ALL, Q_vsnprintf, and ri.
Referenced by __attribute__(), BG_AddPredictableEventToPlayerstate(), Cbuf_AddText(), Cbuf_InsertText(), CG_CustomSound(), CG_ParseAnimationFile(), CL_AdjustTimeDelta(), CL_CgameSystemCalls(), CL_CheckTimeout(), CL_Clientinfo_f(), CL_CloseAVI(), CL_Configstrings_f(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_DemoCompleted(), CL_Disconnect(), CL_DisconnectPacket(), CL_FirstSnapshot(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_GenerateQKey(), CL_GlobalServers_f(), CL_Init(), CL_InitCGame(), CL_InitDownloads(), CL_InitRef(), CL_KeyState(), CL_LoadConsoleHistory(), CL_LocalServers_f(), CL_MouseMove(), CL_NextDownload(), CL_OpenAVIForWriting(), CL_OpenedPK3List_f(), CL_PacketEvent(), CL_ParseDownload(), CL_ParsePacketEntities(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_Ping_f(), CL_PlayDemo_f(), CL_Rcon_f(), CL_ReadDemoMessage(), CL_Reconnect_f(), CL_Record_f(), CL_ReferencedPK3List_f(), CL_RequestMotd(), CL_SaveConsoleHistory(), CL_SendCmd(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_ServerStatus_f(), CL_ServerStatusResponse(), CL_SetModel_f(), CL_Shutdown(), CL_StopRecord_f(), CL_SystemInfoChanged(), CL_UISystemCalls(), CL_Video_f(), CL_WalkDemoExt(), CL_WriteAVIAudioFrame(), CL_WritePacket(), ClientForString(), CM_AddFacetBevels(), CM_DrawDebugSurface(), CM_GridPlane(), Cmd_AddCommand(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_List_f(), Cmd_Vstr_f(), COM_ParseError(), COM_ParseWarning(), Com_sprintf(), compile_one_insn(), Con_Dump_f(), CON_Init(), CON_Input(), Console_Key(), Cvar_Get(), Cvar_List_f(), Cvar_Print(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Set2(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Cvar_Validate(), Cvar_WriteVariables(), FS_ComparePaks(), FS_CreatePath(), FS_Dir_f(), FS_FCreateOpenPipeFile(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_NewDir_f(), FS_Path_f(), FS_Rename(), FS_Startup(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), FS_TouchFile_f(), FS_Which(), FS_Which_f(), FS_Write(), FS_WriteFile(), IN_ActivateMouse(), IN_DeactivateMouse(), IN_KeyDown(), IN_PrintKey(), IN_TranslateSDLToQ3Key(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Key_Bind_f(), Key_Bindlist_f(), Key_Unbind_f(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_ReportChangeVectors_f(), MSG_WriteBigString(), MSG_WriteString(), NET_CompareBaseAdrMask(), NET_GetLocalAddress(), NET_GetPacket(), NET_Init(), NET_IP6Socket(), NET_IPSocket(), NET_JoinMulticast6(), NET_OpenIP(), NET_OpenSocks(), NET_SendPacket(), NET_SetMulticast6(), NET_Sleep(), Netchan_Process(), Netchan_Transmit(), Netchan_TransmitNextFragment(), PM_StepSlideMove(), PM_VerifyTrace(), R_Bloom_InitTextures(), RE_GLSL_RegisterProgram(), readQuadInfo(), S_AL_Init(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_RegisterSound(), S_Base_SoundInfo(), S_Base_SoundList(), S_Base_StartBackgroundTrack(), S_Base_StartLocalSound(), S_Base_StartSound(), S_Base_Update(), S_CodecGetSound(), S_DisplayFreeMemory(), S_Init(), S_Music_f(), S_ReadChunkInfo(), S_ReadRIFFHeader(), S_WAV_CodecLoad(), SHOWNET(), SND_setup(), SNDDMA_Init(), SNDDMA_PrintAudiospec(), SNDDMA_Shutdown(), sparc_compute_code(), SV_AddBanToList(), SV_AddServerCommand(), SV_AreaEntities_r(), SV_ClientCommand(), SV_ConSay_f(), SV_DelBanFromList(), SV_DirectConnect(), SV_DumpUser_f(), SV_ExecuteClientMessage(), SV_FlushBans_f(), SV_GameSystemCalls(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Kick_f(), SV_KickNum_f(), SV_ListBans_f(), SV_Map_f(), SV_MapRestart_f(), SV_MasterHeartbeat(), SV_NextDownload_f(), SV_PacketEvent(), SV_SectorList_f(), SV_SendClientSnapshot(), SV_SendServerCommand(), SV_Serverinfo_f(), SV_Shutdown(), SV_SpawnServer(), SV_Status_f(), SV_Systeminfo_f(), SV_UnlinkEntity(), SV_UserMove(), SV_WriteDownloadToClient(), SVC_RemoteCommand(), Sys_DefaultHomePath(), Sys_ErrorDialog(), Sys_LoadDll(), Sys_LoadGameDll(), Sys_PlatformInit(), Sys_SendPacket(), Sys_ShowIP(), Sys_StringToSockaddr(), Sys_UnloadDll(), Sys_WritePIDFile(), UI_ParseAnimationFile(), UI_ParseInfos(), UpdateIPBans(), vimm(), VM_Call(), VM_CallInterpreted(), VM_Compile(), VM_Create(), VM_Destroy_Compiled(), VM_Free(), VM_LoadQVM(), VM_LoadSymbols(), VM_Restart(), VM_StackTrace(), VM_VmInfo_f(), and VM_VmProfile_f().