ZEQ2-Lite: CachedBitmap Class Reference
CachedBitmap Class Reference
#include <gdiplusheaders.h>
Public Member Functions
CachedBitmap (Bitmap *bitmap, Graphics *graphics)
~CachedBitmap ()
Status GetLastStatus () const
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
CachedBitmap (const CachedBitmap &)
CachedBitmap & operator= (const CachedBitmap &)
Private Attributes
Status lastStatus
GpCachedBitmap * nativeCachedBitmap
Friends
class Graphics
Detailed Description
Definition at line 239 of file gdiplusheaders.h.
Constructor & Destructor Documentation
CachedBitmap() [1/2]
__inline__ CachedBitmap::CachedBitmap (Bitmap * bitmap, Graphics * graphics)
Definition at line 637 of file gdiplusimpl.h.
                                                                        :
     nativeCachedBitmap(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateCachedBitmap(
             bitmap ? ((GpBitmap*) bitmap->nativeImage) : NULL,
             graphics ? graphics->nativeGraphics : NULL,
             &nativeCachedBitmap);
 }
References GdipCreateCachedBitmap(), lastStatus, nativeCachedBitmap, Graphics::nativeGraphics, Image::nativeImage, and NULL.
~CachedBitmap()
__inline__ CachedBitmap::~CachedBitmap ()
Definition at line 646 of file gdiplusimpl.h.
 {
     DllExports::GdipDeleteCachedBitmap(nativeCachedBitmap);
 }
References GdipDeleteCachedBitmap(), and nativeCachedBitmap.
CachedBitmap() [2/2]
CachedBitmap::CachedBitmap (const CachedBitmap &) private
Member Function Documentation
GetLastStatus()
Status CachedBitmap::GetLastStatus () const inline
Definition at line 247 of file gdiplusheaders.h.
     {
         return lastStatus;
     }
References lastStatus.
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
CachedBitmap& CachedBitmap::operator= (const CachedBitmap &) private
Friends And Related Function Documentation
Graphics
friend class Graphics friend
Definition at line 241 of file gdiplusheaders.h.
Field Documentation
lastStatus
Status CachedBitmap::lastStatus private
Definition at line 257 of file gdiplusheaders.h.
Referenced by CachedBitmap(), and GetLastStatus().
nativeCachedBitmap
GpCachedBitmap* CachedBitmap::nativeCachedBitmap private
Definition at line 256 of file gdiplusheaders.h.
Referenced by CachedBitmap(), Graphics::DrawCachedBitmap(), and ~CachedBitmap().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdiplusheaders.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h