ZEQ2-Lite: Tools/MinGW/include/dirent.h File Reference
dirent.h File Reference
#include <_mingw.h>
#include <io.h>
Data Structures
struct _WDIR
struct _wdirent
struct DIR
struct dirent
Functions
int __cdecl __MINGW_NOTHROW _wclosedir (_WDIR *)
_WDIR *__cdecl __MINGW_NOTHROW _wopendir (const wchar_t *)
struct _wdirent *__cdecl __MINGW_NOTHROW _wreaddir (_WDIR *)
void __cdecl __MINGW_NOTHROW _wrewinddir (_WDIR *)
void __cdecl __MINGW_NOTHROW _wseekdir (_WDIR *, long)
long __cdecl __MINGW_NOTHROW _wtelldir (_WDIR *)
int __cdecl __MINGW_NOTHROW closedir (DIR *)
DIR *__cdecl __MINGW_NOTHROW opendir (const char *)
struct dirent *__cdecl __MINGW_NOTHROW readdir (DIR *)
void __cdecl __MINGW_NOTHROW rewinddir (DIR *)
void __cdecl __MINGW_NOTHROW seekdir (DIR *, long)
long __cdecl __MINGW_NOTHROW telldir (DIR *)
Function Documentation
_wclosedir()
int __cdecl __MINGW_NOTHROW _wclosedir (_WDIR *)
_wopendir()
_WDIR* __cdecl __MINGW_NOTHROW _wopendir (const wchar_t *)
_wreaddir()
struct _wdirent* __cdecl __MINGW_NOTHROW _wreaddir (_WDIR *)
_wrewinddir()
void __cdecl __MINGW_NOTHROW _wrewinddir (_WDIR *)
_wseekdir()
void __cdecl __MINGW_NOTHROW _wseekdir (_WDIR * , long)
_wtelldir()
long __cdecl __MINGW_NOTHROW _wtelldir (_WDIR *)
closedir()
int __cdecl __MINGW_NOTHROW closedir (DIR *)
Referenced by Sys_ListFiles(), and Sys_ListFilteredFiles().
opendir()
DIR* __cdecl __MINGW_NOTHROW opendir (const char *)
Referenced by Sys_ListFiles(), and Sys_ListFilteredFiles().
readdir()
struct dirent* __cdecl __MINGW_NOTHROW readdir (DIR *)
Referenced by Sys_ListFiles(), and Sys_ListFilteredFiles().
rewinddir()
void __cdecl __MINGW_NOTHROW rewinddir (DIR *)
seekdir()
void __cdecl __MINGW_NOTHROW seekdir (DIR * , long)
Referenced by _GLIBCXX_VISIBILITY().
telldir()
long __cdecl __MINGW_NOTHROW telldir (DIR *)