ZEQ2-Lite: Engine/jpeg-8c/jdsample.c File Reference
jdsample.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_upsampler
Macros
#define JPEG_INTERNALS
Typedefs
typedef my_upsampler * my_upsample_ptr
Functions
fullsize_upsample (j_decompress_ptr cinfo, jpeg_component_info *compptr, JSAMPARRAY input_data, JSAMPARRAY *output_data_ptr)
h2v1_upsample (j_decompress_ptr cinfo, jpeg_component_info *compptr, JSAMPARRAY input_data, JSAMPARRAY *output_data_ptr)
h2v2_upsample (j_decompress_ptr cinfo, jpeg_component_info *compptr, JSAMPARRAY input_data, JSAMPARRAY *output_data_ptr)
int_upsample (j_decompress_ptr cinfo, jpeg_component_info *compptr, JSAMPARRAY input_data, JSAMPARRAY *output_data_ptr)
jinit_upsampler (j_decompress_ptr cinfo)
typedef JMETHOD (void, upsample1_ptr,(j_decompress_ptr cinfo, jpeg_component_info *compptr, JSAMPARRAY input_data, JSAMPARRAY *output_data_ptr))
noop_upsample (j_decompress_ptr cinfo, jpeg_component_info *compptr, JSAMPARRAY input_data, JSAMPARRAY *output_data_ptr)
sep_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION *in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
start_pass_upsample (j_decompress_ptr cinfo)
Macro Definition Documentation
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 22 of file jdsample.c.
Typedef Documentation
my_upsample_ptr
typedef my_upsampler* my_upsample_ptr
Definition at line 62 of file jdsample.c.
Function Documentation
fullsize_upsample()
fullsize_upsample (j_decompress_ptr cinfo, jpeg_component_info * compptr, JSAMPARRAY input_data, JSAMPARRAY * output_data_ptr)
Definition at line 158 of file jdsample.c.
 {
   *output_data_ptr = input_data;
 }
Referenced by jinit_upsampler().
h2v1_upsample()
h2v1_upsample (j_decompress_ptr cinfo, jpeg_component_info * compptr, JSAMPARRAY input_data, JSAMPARRAY * output_data_ptr)
Definition at line 234 of file jdsample.c.
 {
   JSAMPARRAY output_data = *output_data_ptr;
   register JSAMPROW inptr, outptr;
   register JSAMPLE invalue;
   JSAMPROW outend;
   int outrow;
   for (outrow = 0; outrow < cinfo->max_v_samp_factor; outrow++) {
     inptr = input_data[outrow];
     outptr = output_data[outrow];
     outend = outptr + cinfo->output_width;
     while (outptr < outend) {
       invalue = *inptr++;   /* don't need GETJSAMPLE() here */
       *outptr++ = invalue;
       *outptr++ = invalue;
     }
   }
 }
Referenced by jinit_upsampler().
h2v2_upsample()
h2v2_upsample (j_decompress_ptr cinfo, jpeg_component_info * compptr, JSAMPARRAY input_data, JSAMPARRAY * output_data_ptr)
Definition at line 262 of file jdsample.c.
 {
   JSAMPARRAY output_data = *output_data_ptr;
   register JSAMPROW inptr, outptr;
   register JSAMPLE invalue;
   JSAMPROW outend;
   int inrow, outrow;
   inrow = outrow = 0;
   while (outrow < cinfo->max_v_samp_factor) {
     inptr = input_data[inrow];
     outptr = output_data[outrow];
     outend = outptr + cinfo->output_width;
     while (outptr < outend) {
       invalue = *inptr++;   /* don't need GETJSAMPLE() here */
       *outptr++ = invalue;
       *outptr++ = invalue;
     }
     jcopy_sample_rows(output_data, outrow, output_data, outrow+1,
               1, cinfo->output_width);
     inrow++;
     outrow += 2;
   }
 }
References jcopy_sample_rows().
Referenced by jinit_upsampler().
int_upsample()
int_upsample (j_decompress_ptr cinfo, jpeg_component_info * compptr, JSAMPARRAY input_data, JSAMPARRAY * output_data_ptr)
Definition at line 190 of file jdsample.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   JSAMPARRAY output_data = *output_data_ptr;
   register JSAMPROW inptr, outptr;
   register JSAMPLE invalue;
   register int h;
   JSAMPROW outend;
   int h_expand, v_expand;
   int inrow, outrow;
   h_expand = upsample->h_expand[compptr->component_index];
   v_expand = upsample->v_expand[compptr->component_index];
   inrow = outrow = 0;
   while (outrow < cinfo->max_v_samp_factor) {
     /* Generate one output row with proper horizontal expansion */
     inptr = input_data[inrow];
     outptr = output_data[outrow];
     outend = outptr + cinfo->output_width;
     while (outptr < outend) {
       invalue = *inptr++;   /* don't need GETJSAMPLE() here */
       for (h = h_expand; h > 0; h--) {
     *outptr++ = invalue;
       }
     }
     /* Generate any additional output rows by duplicating the first one */
     if (v_expand > 1) {
       jcopy_sample_rows(output_data, outrow, output_data, outrow+1,
             v_expand-1, cinfo->output_width);
     }
     inrow++;
     outrow += v_expand;
   }
 }
References jpeg_component_info::component_index, compptr, my_upsampler::h_expand, jcopy_sample_rows(), and my_upsampler::v_expand.
Referenced by jinit_upsampler().
jinit_upsampler()
jinit_upsampler (j_decompress_ptr cinfo)
Definition at line 294 of file jdsample.c.
 {
   my_upsample_ptr upsample;
   int ci;
   jpeg_component_info * compptr;
   boolean need_buffer;
   int h_in_group, v_in_group, h_out_group, v_out_group;
   upsample = (my_upsample_ptr)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 SIZEOF(my_upsampler));
   cinfo->upsample = (struct jpeg_upsampler *) upsample;
   upsample->pub.start_pass = start_pass_upsample;
   upsample->pub.upsample = sep_upsample;
   upsample->pub.need_context_rows = FALSE; /* until we find out differently */
   if (cinfo->CCIR601_sampling)  /* this isn't supported */
     ERREXIT(cinfo, JERR_CCIR601_NOTIMPL);
   /* Verify we can handle the sampling factors, select per-component methods,
    * and create storage as needed.
    */
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     /* Compute size of an "input group" after IDCT scaling.  This many samples
      * are to be converted to max_h_samp_factor * max_v_samp_factor pixels.
      */
     h_in_group = (compptr->h_samp_factor * compptr->DCT_h_scaled_size) /
          cinfo->min_DCT_h_scaled_size;
     v_in_group = (compptr->v_samp_factor * compptr->DCT_v_scaled_size) /
          cinfo->min_DCT_v_scaled_size;
     h_out_group = cinfo->max_h_samp_factor;
     v_out_group = cinfo->max_v_samp_factor;
     upsample->rowgroup_height[ci] = v_in_group; /* save for use later */
     need_buffer = TRUE;
     if (! compptr->component_needed) {
       /* Don't bother to upsample an uninteresting component. */
       upsample->methods[ci] = noop_upsample;
       need_buffer = FALSE;
     } else if (h_in_group == h_out_group && v_in_group == v_out_group) {
       /* Fullsize components can be processed without any work. */
       upsample->methods[ci] = fullsize_upsample;
       need_buffer = FALSE;
     } else if (h_in_group * 2 == h_out_group &&
            v_in_group == v_out_group) {
       /* Special case for 2h1v upsampling */
       upsample->methods[ci] = h2v1_upsample;
     } else if (h_in_group * 2 == h_out_group &&
            v_in_group * 2 == v_out_group) {
       /* Special case for 2h2v upsampling */
       upsample->methods[ci] = h2v2_upsample;
     } else if ((h_out_group % h_in_group) == 0 &&
            (v_out_group % v_in_group) == 0) {
       /* Generic integral-factors upsampling method */
       upsample->methods[ci] = int_upsample;
       upsample->h_expand[ci] = (UINT8) (h_out_group / h_in_group);
       upsample->v_expand[ci] = (UINT8) (v_out_group / v_in_group);
     } else
       ERREXIT(cinfo, JERR_FRACT_SAMPLE_NOTIMPL);
     if (need_buffer) {
       upsample->color_buf[ci] = (*cinfo->mem->alloc_sarray)
     ((j_common_ptr) cinfo, JPOOL_IMAGE,
      (JDIMENSION) jround_up((long) cinfo->output_width,
                 (long) cinfo->max_h_samp_factor),
      (JDIMENSION) cinfo->max_v_samp_factor);
     }
   }
 }
References my_upsampler::color_buf, jpeg_component_info::component_needed, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, ERREXIT, FALSE, fullsize_upsample(), h2v1_upsample(), h2v2_upsample(), my_upsampler::h_expand, jpeg_component_info::h_samp_factor, int_upsample(), JPOOL_IMAGE, jround_up(), long(), my_upsampler::methods, jpeg_upsampler::need_context_rows, noop_upsample(), my_upsampler::pub, my_upsampler::rowgroup_height, sep_upsample(), SIZEOF, start_pass_upsample(), TRUE, my_upsampler::v_expand, and jpeg_component_info::v_samp_factor.
Referenced by master_selection().
JMETHOD()
typedef JMETHOD (void , upsample1_ptr , (j_decompress_ptr cinfo, jpeg_component_info *compptr, JSAMPARRAY input_data, JSAMPARRAY *output_data_ptr))
noop_upsample()
noop_upsample (j_decompress_ptr cinfo, jpeg_component_info * compptr, JSAMPARRAY input_data, JSAMPARRAY * output_data_ptr)
Definition at line 171 of file jdsample.c.
 {
   *output_data_ptr = NULL;  /* safety check */
 }
References NULL.
Referenced by jinit_upsampler().
sep_upsample()
sep_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION * in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 90 of file jdsample.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   int ci;
   jpeg_component_info * compptr;
   JDIMENSION num_rows;
   /* Fill the conversion buffer, if it's empty */
   if (upsample->next_row_out >= cinfo->max_v_samp_factor) {
     for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
      ci++, compptr++) {
       /* Invoke per-component upsample method.  Notice we pass a POINTER
        * to color_buf[ci], so that fullsize_upsample can change it.
        */
       (*upsample->methods[ci]) (cinfo, compptr,
     input_buf[ci] + (*in_row_group_ctr * upsample->rowgroup_height[ci]),
     upsample->color_buf + ci);
     }
     upsample->next_row_out = 0;
   }
   /* Color-convert and emit rows */
   /* How many we have in the buffer: */
   num_rows = (JDIMENSION) (cinfo->max_v_samp_factor - upsample->next_row_out);
   /* Not more than the distance to the end of the image.  Need this test
    * in case the image height is not a multiple of max_v_samp_factor:
    */
   if (num_rows > upsample->rows_to_go)
     num_rows = upsample->rows_to_go;
   /* And not more than what the client can accept: */
   out_rows_avail -= *out_row_ctr;
   if (num_rows > out_rows_avail)
     num_rows = out_rows_avail;
   (*cinfo->cconvert->color_convert) (cinfo, upsample->color_buf,
                      (JDIMENSION) upsample->next_row_out,
                      output_buf + *out_row_ctr,
                      (int) num_rows);
   /* Adjust counts */
   *out_row_ctr += num_rows;
   upsample->rows_to_go -= num_rows;
   upsample->next_row_out += num_rows;
   /* When the buffer is emptied, declare this input row group consumed */
   if (upsample->next_row_out >= cinfo->max_v_samp_factor)
     (*in_row_group_ctr)++;
 }
References my_upsampler::color_buf, compptr, int(), my_upsampler::methods, my_upsampler::next_row_out, num_rows, output_buf, my_upsampler::rowgroup_height, and my_upsampler::rows_to_go.
Referenced by jinit_upsampler().
start_pass_upsample()
start_pass_upsample (j_decompress_ptr cinfo)
Definition at line 70 of file jdsample.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   /* Mark the conversion buffer empty */
   upsample->next_row_out = cinfo->max_v_samp_factor;
   /* Initialize total-height counter for detecting bottom of image */
   upsample->rows_to_go = cinfo->output_height;
 }
References my_upsampler::next_row_out, and my_upsampler::rows_to_go.
Referenced by jinit_upsampler().