ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/bits/char_traits.h File Reference
char_traits.h File Reference
#include <bits/stl_algobase.h>
#include <bits/postypes.h>
#include <cwchar>
Functions
namespace __gnu_cxx _GLIBCXX_VISIBILITY (default)
Detailed Description
This is an internal header file, included by other library headers. Do not attempt to use it directly. @headername{string}
Definition in file char_traits.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace __gnu_cxx _GLIBCXX_VISIBILITY (default)
Mapping from character type to associated types.
Note
This is an implementation class for the generic version of char_traits. It defines int_type, off_type, pos_type, and state_type. By default these are unsigned long, streamoff, streampos, and mbstate_t. Users who need a different set of types, but who don't need to change the definitions of any function defined in char_traits, can specialize __gnu_cxx::_Char_types while leaving __gnu_cxx::char_traits alone.
Base class used to implement std::char_traits.
Note
For any given actual character type, this definition is probably wrong. (Most of the member functions are likely to be right, but the int_type and state_type typedefs, and the eof() member function, are likely to be wrong.) The reason this class exists is so users can specialize it. Classes in namespace std may not be specialized for fundamental types, but classes in namespace __gnu_cxx may be.
See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt05ch13s03.html for advice on how to make use of this class for unusual character types. Also, check out include/ext/pod_char_traits.h.
Basis for explicit traits specializations.
Note
For any given actual character type, this definition is probably wrong. Since this is just a thin wrapper around __gnu_cxx::char_traits, it is possible to achieve a more appropriate definition by specializing __gnu_cxx::char_traits.
See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt05ch13s03.html for advice on how to make use of this class for unusual character types. Also, check out include/ext/pod_char_traits.h.
21.1.3.1 char_traits specializations
Definition at line 45 of file char_traits.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
   template<typename _CharT>
     struct _Char_types
     {
       typedef unsigned long   int_type;
       typedef std::streampos  pos_type;
       typedef std::streamoff  off_type;
       typedef std::mbstate_t  state_type;
     };
   template<typename _CharT>
     struct char_traits
     {
       typedef _CharT                                    char_type;
       typedef typename _Char_types<_CharT>::int_type    int_type;
       typedef typename _Char_types<_CharT>::pos_type    pos_type;
       typedef typename _Char_types<_CharT>::off_type    off_type;
       typedef typename _Char_types<_CharT>::state_type  state_type;
       static void
       assign(char_type& __c1, const char_type& __c2)
       { __c1 = __c2; }
       static _GLIBCXX_CONSTEXPR bool
       eq(const char_type& __c1, const char_type& __c2)
       { return __c1 == __c2; }
       static _GLIBCXX_CONSTEXPR bool
       lt(const char_type& __c1, const char_type& __c2)
       { return __c1 < __c2; }
       static int
       compare(const char_type* __s1, const char_type* __s2, std::size_t __n);
       static std::size_t
       length(const char_type* __s);
       static const char_type*
       find(const char_type* __s, std::size_t __n, const char_type& __a);
       static char_type*
       move(char_type* __s1, const char_type* __s2, std::size_t __n);
       static char_type*
       copy(char_type* __s1, const char_type* __s2, std::size_t __n);
       static char_type*
       assign(char_type* __s, std::size_t __n, char_type __a);
       static _GLIBCXX_CONSTEXPR char_type
       to_char_type(const int_type& __c)
       { return static_cast<char_type>(__c); }
       static _GLIBCXX_CONSTEXPR int_type
       to_int_type(const char_type& __c)
       { return static_cast<int_type>(__c); }
       static _GLIBCXX_CONSTEXPR bool
       eq_int_type(const int_type& __c1, const int_type& __c2)
       { return __c1 == __c2; }
       static _GLIBCXX_CONSTEXPR int_type
       eof()
       { return static_cast<int_type>(_GLIBCXX_STDIO_EOF); }
       static _GLIBCXX_CONSTEXPR int_type
       not_eof(const int_type& __c)
       { return !eq_int_type(__c, eof()) ? __c : to_int_type(char_type()); }
     };
   template<typename _CharT>
     int
     char_traits<_CharT>::
     compare(const char_type* __s1, const char_type* __s2, std::size_t __n)
     {
       for (std::size_t __i = 0; __i < __n; ++__i)
     if (lt(__s1[__i], __s2[__i]))
       return -1;
     else if (lt(__s2[__i], __s1[__i]))
       return 1;
       return 0;
     }
   template<typename _CharT>
     std::size_t
     char_traits<_CharT>::
     length(const char_type* __p)
     {
       std::size_t __i = 0;
       while (!eq(__p[__i], char_type()))
         ++__i;
       return __i;
     }
   template<typename _CharT>
     const typename char_traits<_CharT>::char_type*
     char_traits<_CharT>::
     find(const char_type* __s, std::size_t __n, const char_type& __a)
     {
       for (std::size_t __i = 0; __i < __n; ++__i)
         if (eq(__s[__i], __a))
           return __s + __i;
       return 0;
     }
   template<typename _CharT>
     typename char_traits<_CharT>::char_type*
     char_traits<_CharT>::
     move(char_type* __s1, const char_type* __s2, std::size_t __n)
     {
       return static_cast<_CharT*>(__builtin_memmove(__s1, __s2,
                             __n * sizeof(char_type)));
     }
   template<typename _CharT>
     typename char_traits<_CharT>::char_type*
     char_traits<_CharT>::
     copy(char_type* __s1, const char_type* __s2, std::size_t __n)
     {
       // NB: Inline std::copy so no recursive dependencies.
       std::copy(__s2, __s2 + __n, __s1);
       return __s1;
     }
   template<typename _CharT>
     typename char_traits<_CharT>::char_type*
     char_traits<_CharT>::
     assign(char_type* __s, std::size_t __n, char_type __a)
     {
       // NB: Inline std::fill_n so no recursive dependencies.
       std::fill_n(__s, __n, __a);
       return __s;
     }
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References _GLIBCXX_STDIO_EOF, assign(), compare(), eof(), eq, find(), lt, and move().