ZEQ2-Lite: __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator > Class Template Reference
__gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator > Class Template Reference
#include <const_iterator.hpp>
Public Types
typedef base_type::const_pointer const_pointer
typedef base_type::const_reference const_reference
typedef Allocator::difference_type difference_type
typedef std::forward_iterator_tag iterator_category
typedef base_type::pointer pointer
typedef base_type::reference reference
typedef base_type::value_type value_type
Public Member Functions
left_child_next_sibling_heap_const_iterator_ ()
left_child_next_sibling_heap_const_iterator_ (const PB_DS_CLASS_C_DEC &other)
left_child_next_sibling_heap_const_iterator_ (node_pointer p_nd)
bool operator!= (const PB_DS_CLASS_C_DEC &other) const
PB_DS_CLASS_C_DEC & operator++ ()
PB_DS_CLASS_C_DEC operator++ (int)
bool operator== (const PB_DS_CLASS_C_DEC &other) const
Private Types
typedef PB_DS_BASE_C_DEC base_type
typedef PB_DS_BASE_C_DEC::node_pointer node_pointer
Private Member Functions
void inc ()
Detailed Description
template<typename Node, class Allocator>
class __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >
Definition at line 61 of file const_iterator.hpp.
Member Typedef Documentation
base_type
template<typename Node , class Allocator > typedef PB_DS_BASE_C_DEC __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::base_type private
Definition at line 67 of file const_iterator.hpp.
const_pointer
template<typename Node , class Allocator > typedef base_type::const_pointer __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::const_pointer
Definition at line 84 of file const_iterator.hpp.
const_reference
template<typename Node , class Allocator > typedef base_type::const_reference __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::const_reference
Definition at line 90 of file const_iterator.hpp.
difference_type
template<typename Node , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::difference_type
Definition at line 75 of file const_iterator.hpp.
iterator_category
template<typename Node , class Allocator > typedef std::forward_iterator_tag __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::iterator_category
Definition at line 72 of file const_iterator.hpp.
node_pointer
template<typename Node , class Allocator > typedef PB_DS_BASE_C_DEC::node_pointer __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::node_pointer private
Definition at line 65 of file const_iterator.hpp.
pointer
template<typename Node , class Allocator > typedef base_type::pointer __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::pointer
Definition at line 81 of file const_iterator.hpp.
reference
template<typename Node , class Allocator > typedef base_type::reference __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::reference
Definition at line 87 of file const_iterator.hpp.
value_type
template<typename Node , class Allocator > typedef base_type::value_type __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::value_type
Definition at line 78 of file const_iterator.hpp.
Constructor & Destructor Documentation
left_child_next_sibling_heap_const_iterator_() [1/3]
template<typename Node , class Allocator > __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::left_child_next_sibling_heap_const_iterator_ (node_pointer p_nd) inline
Definition at line 95 of file const_iterator.hpp.
                                                                       : base_type(p_nd)
       { }
left_child_next_sibling_heap_const_iterator_() [2/3]
template<typename Node , class Allocator > __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::left_child_next_sibling_heap_const_iterator_ () inline
Definition at line 100 of file const_iterator.hpp.
       { }
left_child_next_sibling_heap_const_iterator_() [3/3]
template<typename Node , class Allocator > __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::left_child_next_sibling_heap_const_iterator_ (const PB_DS_CLASS_C_DEC & other) inline
Definition at line 105 of file const_iterator.hpp.
                                                                                    : base_type(other)
       { }
Member Function Documentation
inc()
template<typename Node , class Allocator > void __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::inc () inline private
Definition at line 136 of file const_iterator.hpp.
       {
     if (base_type::m_p_nd->m_p_next_sibling != 0)
       {
         base_type::m_p_nd = base_type::m_p_nd->m_p_next_sibling;
         while (base_type::m_p_nd->m_p_l_child != 0)
           base_type::m_p_nd = base_type::m_p_nd->m_p_l_child;
         return;
       }
     while (true)
       {
         node_pointer p_next = base_type::m_p_nd;
         base_type::m_p_nd = base_type::m_p_nd->m_p_prev_or_parent;
         if (base_type::m_p_nd == 0 || base_type::m_p_nd->m_p_l_child == p_next)
           return;
       }
       }
Referenced by __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::operator++().
operator!=()
template<typename Node , class Allocator > bool __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::operator!= (const PB_DS_CLASS_C_DEC & other) const inline
Definition at line 115 of file const_iterator.hpp.
       { return (base_type::m_p_nd != other.m_p_nd); }
operator++() [1/2]
template<typename Node , class Allocator > PB_DS_CLASS_C_DEC& __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::operator++ () inline
Definition at line 119 of file const_iterator.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(base_type::m_p_nd != 0);
     inc();
     return (*this);
       }
References _GLIBCXX_DEBUG_ASSERT, and __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::inc().
Referenced by __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::operator++().
operator++() [2/2]
template<typename Node , class Allocator > PB_DS_CLASS_C_DEC __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::operator++ (int) inline
Definition at line 127 of file const_iterator.hpp.
       {
     PB_DS_CLASS_C_DEC ret_it(base_type::m_p_nd);
     operator++();
     return (ret_it);
       }
References __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::operator++(), and PB_DS_CLASS_C_DEC.
operator==()
template<typename Node , class Allocator > bool __gnu_pbds::detail::left_child_next_sibling_heap_const_iterator_< Node, Allocator >::operator== (const PB_DS_CLASS_C_DEC & other) const inline
Definition at line 110 of file const_iterator.hpp.
       { return (base_type::m_p_nd == other.m_p_nd); }
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/left_child_next_sibling_heap_/const_iterator.hpp