ZEQ2-Lite: Source/Shared/vm_x86_64.c File Reference
vm_x86_64.c File Reference
#include "vm_local.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <time.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <stdarg.h>
#include <inttypes.h>
#include <sys/mman.h>
#include <sys/wait.h>
Macros
#define CHECK_INSTR(nr)
#define CHECK_INSTR_REG(reg)
#define CONST_OPTIMIZE
#define CROSSCALL
#define Dfprintf(args...)
#define FJ(x, y)
#define FSIMPLE(op)
#define IJ(op)
#define JMPIARG()
#define MAYBE_EMIT_CONST()
#define NOTIMPL(x) do { Com_Printf(S_COLOR_RED "instruction not implemented: %x\n", x); vm->compiled = qfalse; return; } while(0)
#define PREPARE_JMP(reg)
#define RANGECHECK(reg, bytes) emit("andl $0x%x, %%" #reg, vm->dataMask &~(bytes-1))
#define SHIFT(op)
#define SIMPLE(op)
#define STACK_POP(bytes) emit("subb $0x%x, %%bl", bytes >> 2); \
#define STACK_PUSH(bytes) emit("addb $0x%x, %%bl", bytes >> 2); \
#define VM_FREEBUFFERS(vm) do {assembler_init(0); VM_Destroy_Compiled(vm);} while(0)
#define VM_X86_64_MMAP
#define XJ(op)
#define XSIMPLE(op)
Functions
static __attribute__ ((format(printf, 1, 2)))
static __attribute__ ((noreturn))
void assemble_line (const char *input, size_t len)
size_t assembler_get_code_size (void)
void assembler_init (int pass)
void assembler_set_output (char *buf)
static intptr_t CROSSCALL callAsmCall (intptr_t callProgramStack, int64_t callSyscallNum)
static void * getentrypoint (vm_t *vm)
int VM_CallCompiled (vm_t *vm, int *args)
void VM_Compile (vm_t *vm, vmHeader_t *header)
static void VM_Destroy_Compiled (vm_t *self)
Variables
static unsigned char op_argsize [256]
Macro Definition Documentation
CHECK_INSTR
#define CHECK_INSTR (nr)
Value:
    do { if(nr < 0 || nr >= header->instructionCount) { \
        VM_FREEBUFFERS(vm); \
        Com_Error( ERR_DROP, \
            "%s: jump target 0x%x out of range at offset %d", __func__, nr, pc ); \
    } } while(0)
Definition at line 278 of file vm_x86_64.c.
CHECK_INSTR_REG
#define CHECK_INSTR_REG (reg)
Value:
    emit("cmpl $%u, %%"#reg, header->instructionCount); \
    emit("jb jmp_ok_i_%08x", instruction); \
    emit("movq $%"PRIu64", %%rax", (intptr_t)jmpviolation); \
    emit("callq *%%rax"); \
    emit("jmp_ok_i_%08x:", instruction)
Definition at line 265 of file vm_x86_64.c.
CONST_OPTIMIZE
#define CONST_OPTIMIZE
Definition at line 290 of file vm_x86_64.c.
CROSSCALL
#define CROSSCALL
Definition at line 45 of file vm_x86_64.c.
Dfprintf
#define Dfprintf (args...)
Definition at line 54 of file vm_x86_64.c.
FJ
#define FJ (x, y)
Definition at line 327 of file vm_x86_64.c.
FSIMPLE
#define FSIMPLE (op)
Definition at line 354 of file vm_x86_64.c.
IJ
#define IJ (op)
Value:
    MAYBE_EMIT_CONST(); \
    STACK_POP(8); \
    emit("movl 4(%%r9, %%rbx, 4), %%eax"); \
    emit("cmpl 8(%%r9, %%rbx, 4), %%eax"); \
    emit(op " i_%08x", instruction+1); \
    JMPIARG(); \
    neednilabel = 1
Definition at line 305 of file vm_x86_64.c.
JMPIARG
#define JMPIARG ()
Value:
    CHECK_INSTR(iarg); \
    emit("movq $%"PRIu64", %%rax", vm->codeBase+vm->instructionPointers[iarg]); \
    emit("jmpq *%%rax")
Definition at line 285 of file vm_x86_64.c.
MAYBE_EMIT_CONST
#define MAYBE_EMIT_CONST ()
Value:
    if (got_const) \
    { \
        got_const = 0; \
        vm->instructionPointers[instruction-1] = assembler_get_code_size(); \
        STACK_PUSH(4); \
        emit("movl $%d, (%%r9, %%rbx, 4)", const_value); \
    }
Definition at line 292 of file vm_x86_64.c.
NOTIMPL
#define NOTIMPL (x) do { Com_Printf(S_COLOR_RED "instruction not implemented: %x\n", x); vm->compiled = qfalse; return; } while(0)
Definition at line 375 of file vm_x86_64.c.
PREPARE_JMP
#define PREPARE_JMP (reg)
Value:
    CHECK_INSTR_REG(reg); \
    emit("movq $%"PRIu64", %%rsi", (intptr_t)vm->instructionPointers); \
    emit("movl (%%rsi, %%rax, 8), %%eax"); \
    emit("addq %%r10, %%rax")
Definition at line 272 of file vm_x86_64.c.
RANGECHECK
#define RANGECHECK (reg, bytes) emit("andl $0x%x, %%" #reg, vm->dataMask &~(bytes-1))
Definition at line 253 of file vm_x86_64.c.
SHIFT
#define SHIFT (op)
Value:
    MAYBE_EMIT_CONST(); \
    STACK_POP(4); \
    emit("movl 4(%%r9, %%rbx, 4), %%ecx"); \
    emit("movl (%%r9, %%rbx, 4), %%eax"); \
    emit(op " %%cl, %%eax"); \
    emit("movl %%eax, (%%r9, %%rbx, 4)")
Definition at line 363 of file vm_x86_64.c.
SIMPLE
#define SIMPLE (op)
Value:
    MAYBE_EMIT_CONST(); \
    emit("movl (%%r9, %%rbx, 4), %%eax"); \
    STACK_POP(4); \
    emit(op " %%eax, (%%r9, %%rbx, 4)")
Definition at line 339 of file vm_x86_64.c.
STACK_POP
#define STACK_POP (bytes) emit("subb $0x%x, %%bl", bytes >> 2); \
Definition at line 262 of file vm_x86_64.c.
STACK_PUSH
#define STACK_PUSH (bytes) emit("addb $0x%x, %%bl", bytes >> 2); \
Definition at line 259 of file vm_x86_64.c.
VM_FREEBUFFERS
#define VM_FREEBUFFERS (vm) do {assembler_init(0); VM_Destroy_Compiled(vm);} while(0)
Definition at line 57 of file vm_x86_64.c.
VM_X86_64_MMAP
#define VM_X86_64_MMAP
Definition at line 44 of file vm_x86_64.c.
XJ
#define XJ (op)
Value:
    MAYBE_EMIT_CONST(); \
    STACK_POP(8); \
    emit("movss 4(%%r9, %%rbx, 4), %%xmm0");\
    emit("ucomiss 8(%%r9, %%rbx, 4), %%xmm0");\
    emit("jp i_%08x", instruction+1);\
    emit(op " i_%08x", instruction+1);\
    JMPIARG(); \
    neednilabel = 1
Definition at line 328 of file vm_x86_64.c.
XSIMPLE
#define XSIMPLE (op)
Value:
    MAYBE_EMIT_CONST(); \
    STACK_POP(4); \
    emit("movss (%%r9, %%rbx, 4), %%xmm0"); \
    emit(op " 4(%%r9, %%rbx, 4), %%xmm0"); \
    emit("movss %%xmm0, (%%r9, %%rbx, 4)")
Definition at line 355 of file vm_x86_64.c.
Function Documentation
__attribute__() [1/2]
static __attribute__ ((format(printf, 1, 2))) static
Definition at line 232 of file vm_x86_64.c.
 {
     va_list ap;
     char line[4096];
     va_start(ap, fmt);
     Q_vsnprintf(line, sizeof(line), fmt, ap);
     va_end(ap);
     assemble_line(line, strlen(line));
 }
References assemble_line(), fmt, line, and Q_vsnprintf.
__attribute__() [2/2]
static __attribute__ ((noreturn)) static
Definition at line 384 of file vm_x86_64.c.
 {
     Com_Error(ERR_DROP, "End of program reached without return!");
     exit(1);
 }
References Com_Error(), and ERR_DROP.
assemble_line()
void assemble_line (const char * input, size_t len)
Definition at line 1339 of file vm_x86_64_assembler.c.
 {
     char line[4096];
     char* s;
     op_t* o;
     char* opn;
     arg_t arg1, arg2;
     arg1.type = T_NONE;
     arg2.type = T_NONE;
     opn = NULL;
     o = NULL;
     if(len < 1)
         return;
     if(len >= sizeof(line))
         crap("line too long");
     memcpy(line, input, sizeof(line));
     cur_line = input;
     if(line[len-1] == '\n') line[--len] = 0;
     if(line[len-1] == ':')
     {
         line[--len] = 0;
         if(assembler_pass)
             debug("%s: 0x%x\n", line, compiledOfs);
         else
             hash_add_label(line, compiledOfs);
     }
     else
     {
         opn = line;
         s = strchr(line, ' ');
         if(s)
         {
             *s++ = 0;
             arg1 = parsearg((const char**)&s);
             if(*s)
             {
                 if(*s != ',')
                     crap("expected ',', got '%c'", *s);
                 ++s;
                 arg2 = parsearg((const char**)&s);
             }
         }
         if(!opn)
         {
             crap("no operator in %s", line);
         }
         o = getop(opn);
         if(!o)
         {
             crap("cannot handle op %s", opn);
         }
         o->func(opn, arg1, arg2, o->data);
         if(assembler_pass)
             debug("   - %s%s", cur_line, cur_line[strlen(cur_line)-1]=='\n'?"":"\n");
     }
 }
References assembler_pass, compiledOfs, crap, cur_line, op_t::data, debug, op_t::func, getop(), hash_add_label(), line, NULL, parsearg(), and T_NONE.
Referenced by __attribute__().
assembler_get_code_size()
size_t assembler_get_code_size (void)
Definition at line 1329 of file vm_x86_64_assembler.c.
 {
     return compiledOfs;
 }
References compiledOfs.
Referenced by VM_Compile().
assembler_init()
void assembler_init (int pass)
Definition at line 1313 of file vm_x86_64_assembler.c.
 {
     compiledOfs = 0;
     assembler_pass = pass;
     if(!pass)
     {
         labelhash_free();
         cur_line = NULL;
     }
     if(!ops_sorted)
     {
         ops_sorted = 1;
         qsort(ops, ARRAY_LEN(ops)-1, sizeof(ops[0]), opsort);
     }
 }
References ARRAY_LEN, assembler_pass, compiledOfs, cur_line, labelhash_free(), NULL, ops, ops_sorted, opsort(), and pass.
Referenced by VM_Compile().
assembler_set_output()
void assembler_set_output (char * buf)
Definition at line 1334 of file vm_x86_64_assembler.c.
 {
     out = buf;
 }
References out.
Referenced by VM_Compile().
callAsmCall()
static intptr_t CROSSCALL callAsmCall (intptr_t callProgramStack, int64_t callSyscallNum) static
Definition at line 85 of file vm_x86_64.c.
 {
     vm_t *savedVM;
     intptr_t ret = 0x77;
     intptr_t args[16];
 //  int iargs[16];
     int i;
 //  Dfprintf(stderr, "callAsmCall(%ld, %ld)\n", callProgramStack, callSyscallNum);
 //  Com_Printf("-> callAsmCall %s, level %d, num %ld\n", currentVM->name, currentVM->callLevel, callSyscallNum);
     savedVM = currentVM;
     // save the stack to allow recursive VM entry
     currentVM->programStack = callProgramStack - 4;
     args[0] = callSyscallNum;
 //  iargs[0] = callSyscallNum;
     for(i = 0; i < ARRAY_LEN(args)-1; ++i)
     {
 //      iargs[i+1] = *(int *)((byte *)currentVM->dataBase + callProgramStack + 8 + 4*i);
         args[i+1] = *(int *)((byte *)currentVM->dataBase + callProgramStack + 8 + 4*i);
     }
     ret = currentVM->systemCall(args);
     currentVM = savedVM;
 //  Com_Printf("<- callAsmCall %s, level %d, num %ld\n", currentVM->name, currentVM->callLevel, callSyscallNum);
     return ret;
 }
References args, ARRAY_LEN, currentVM, and intptr_t().
Referenced by VM_Compile().
getentrypoint()
static void* getentrypoint (vm_t * vm) static
Definition at line 379 of file vm_x86_64.c.
 {
        return vm->codeBase;
 }
Referenced by VM_CallCompiled().
VM_CallCompiled()
int VM_CallCompiled (vm_t * vm, int * args)
Definition at line 1017 of file vm_x86_64.c.
 {
     int stack[OPSTACK_SIZE + 15];
     int     programCounter;
     int     programStack;
     int     stackOnEntry;
     long        opStackRet;
     byte    *image;
     void    *entryPoint;
     int *opStack;
     currentVM = vm;
 //  Com_Printf("entering %s level %d, call %d, arg1 = 0x%x\n", vm->name, vm->callLevel, args[0], args[1]);
     // interpret the code
     vm->currentlyInterpreting = qtrue;
 //  callMask = vm->dataMask;
     // we might be called recursively, so this might not be the very top
     programStack = vm->programStack;
     stackOnEntry = programStack;
     // set up the stack frame
     image = vm->dataBase;
 #ifdef DEBUG_VM
     memData = (char*)image;
 #endif
     programCounter = 0;
     programStack -= 48;
     *(int *)&image[ programStack + 44] = args[9];
     *(int *)&image[ programStack + 40] = args[8];
     *(int *)&image[ programStack + 36] = args[7];
     *(int *)&image[ programStack + 32] = args[6];
     *(int *)&image[ programStack + 28] = args[5];
     *(int *)&image[ programStack + 24] = args[4];
     *(int *)&image[ programStack + 20] = args[3];
     *(int *)&image[ programStack + 16] = args[2];
     *(int *)&image[ programStack + 12] = args[1];
     *(int *)&image[ programStack + 8 ] = args[0];
     *(int *)&image[ programStack + 4 ] = 0x77777777;    // return stack
     *(int *)&image[ programStack ] = -1;    // will terminate the loop on return
     // off we go into generated code...
     entryPoint = getentrypoint(vm);
     opStack = PADP(stack, 16);
     *opStack = 0xDEADBEEF;
     opStackRet = 0;
     __asm__ __volatile__ (
         "   movq %4,%%r8        \r\n" \
         "   movq %3,%%r9        \r\n" \
         "   movq %2,%%r10       \r\n" \
         "   push %%r15      \r\n" \
         "   push %%r14      \r\n" \
         "   push %%r13      \r\n" \
         "   push %%r12      \r\n" \
         "       subq $24, %%rsp # fix alignment as call pushes one value \r\n" \
         "   callq *%%r10        \r\n" \
         "       addq $24, %%rsp         \r\n" \
         "   pop %%r12       \r\n" \
         "   pop %%r13       \r\n" \
         "   pop %%r14       \r\n" \
         "   pop %%r15       \r\n"
         : "+D" (programStack), "+b" (opStackRet)
         : "g" (entryPoint), "g" (opStack), "g" (vm->dataBase), "g" (programStack)
         : "%rsi", "%rax", "%rcx", "%rdx", "%r8", "%r9", "%r10", "%r11", "%xmm0"
     );
     if(opStackRet != 1 || *opStack != 0xDEADBEEF)
         Com_Error(ERR_DROP, "opStack corrupted in compiled code (offset %ld)", opStackRet);
     if ( programStack != stackOnEntry - 48 ) {
         Com_Error( ERR_DROP, "programStack corrupted in compiled code" );
     }
 //  Com_Printf("exiting %s level %d\n", vm->name, vm->callLevel);
     vm->programStack = stackOnEntry;
     return stack[1];
 }
References args, Com_Error(), currentVM, ERR_DROP, getentrypoint(), OPSTACK_SIZE, PADP, and qtrue.
Referenced by VM_Call().
VM_Compile()
void VM_Compile (vm_t * vm, vmHeader_t * header)
Definition at line 415 of file vm_x86_64.c.
{
     unsigned char op;
     int pc;
     unsigned instruction;
     char* code;
     unsigned iarg = 0;
     unsigned char barg = 0;
     int neednilabel = 0;
     struct timeval tvstart =  {0, 0};
 #ifdef DEBUG_VM
     char fn_d[MAX_QPATH]; // disassembled
 #endif
     int pass;
     size_t compiledOfs = 0;
     // const optimization
     unsigned got_const = 0, const_value = 0;
     vm->codeBase = NULL;
     gettimeofday(&tvstart, NULL);
     for (pass = 0; pass < 2; ++pass) {
     if(pass)
     {
         compiledOfs = assembler_get_code_size();
         vm->codeLength = compiledOfs;
         #ifdef VM_X86_64_MMAP
             vm->codeBase = mmap(NULL, compiledOfs, PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0);
             if(vm->codeBase == MAP_FAILED)
                 Com_Error(ERR_FATAL, "VM_CompileX86_64: can't mmap memory");
         #elif __WIN64__
             // allocate memory with write permissions under windows.
             vm->codeBase = VirtualAlloc(NULL, compiledOfs, MEM_RESERVE|MEM_COMMIT, PAGE_READWRITE);
             if(!vm->codeBase)
                 Com_Error(ERR_FATAL, "VM_CompileX86_64: VirtualAlloc failed");
         #else
             vm->codeBase = malloc(compiledOfs);
             if(!vm_codeBase)
                 Com_Error(ERR_FATAL, "VM_CompileX86_64: Failed to allocate memory");
         #endif
         assembler_set_output((char*)vm->codeBase);
     }
     assembler_init(pass);
 #ifdef DEBUG_VM
     strcpy(fn_d,vm->name);
     strcat(fn_d, ".qdasm");
     qdasmout = fopen(fn_d, "w");
 #endif
     // translate all instructions
     pc = 0;
     code = (char *)header + header->codeOffset;
     for ( instruction = 0; instruction < header->instructionCount; ++instruction )
     {
         op = code[ pc ];
         ++pc;
         vm->instructionPointers[instruction] = assembler_get_code_size();
         /* store current instruction number in r15 for debugging */
 #if DEBUG_VM0
         emit("nop");
         emit("movq $%d, %%r15", instruction);
         emit("nop");
 #endif
         if(op_argsize[op] == 4)
         {
             iarg = *(int*)(code+pc);
             pc += 4;
             Dfprintf(qdasmout, "%s %8u\n", opnames[op], iarg);
         }
         else if(op_argsize[op] == 1)
         {
             barg = code[pc++];
             Dfprintf(qdasmout, "%s %8hu\n", opnames[op], barg);
         }
         else
         {
             Dfprintf(qdasmout, "%s\n", opnames[op]);
         }
         if(neednilabel)
         {
             emit("i_%08x:", instruction);
             neednilabel = 0;
         }
         switch ( op )
         {
             case OP_UNDEF:
                 NOTIMPL(op);
                 break;
             case OP_IGNORE:
                 MAYBE_EMIT_CONST();
                 emit("nop");
                 break;
             case OP_BREAK:
                 MAYBE_EMIT_CONST();
                 emit("int3");
                 break;
             case OP_ENTER:
                 MAYBE_EMIT_CONST();
                 emit("subl $%d, %%edi", iarg);
                 break;
             case OP_LEAVE:
                 MAYBE_EMIT_CONST();
                 emit("addl $%d, %%edi", iarg);          // get rid of stack frame
                 emit("ret");
                 break;
             case OP_CALL:
                 RANGECHECK(edi, 4);
                 emit("movl $%d, (%%r8, %%rdi, 1)", instruction+1);  // save next instruction
                 if(got_const)
                 {
                     if ((int) const_value >= 0)
                     {
                         CHECK_INSTR(const_value);
                         emit("movq $%"PRIu64", %%rax", vm->codeBase+vm->instructionPointers[const_value]);
                         emit("callq *%%rax");
                         got_const = 0;
                         break;
                     }
                 }
                 else
                 {
                     MAYBE_EMIT_CONST();
                     emit("movl (%%r9, %%rbx, 4), %%eax");  // get instr from stack
                     STACK_POP(4);
                     emit("orl %%eax, %%eax");
                     emit("jl callSyscall%d", instruction);
                     PREPARE_JMP(eax);
                     emit("callq *%%rax");
                     emit("jmp i_%08x", instruction+1);
                     emit("callSyscall%d:", instruction);
                 }
 //              emit("fnsave 4(%%r9, %%rsi, 1)");
                 emit("push %%rdi");
                 emit("push %%r8");
                 emit("push %%r9");
                 emit("push %%r10");
                 emit("movq %%rsp, %%rsi"); // we need to align the stack pointer
                 emit("subq $8, %%rsi");    //   |
                 emit("andq $127, %%rsi");  //   |
                 emit("subq %%rsi, %%rsp"); // <-+
                 emit("push %%rsi");
                 if(got_const) {
                     got_const = 0;
                     emit("movq $%u, %%rsi", -1-const_value); // second argument in rsi
                 } else {
                     emit("notl %%eax");        // convert to actual number
                     // first argument already in rdi
                     emit("movq %%rax, %%rsi"); // second argument in rsi
                 }
                 emit("movq $%"PRIu64", %%rax", (intptr_t) callAsmCall);
                 emit("callq *%%rax");
                 emit("pop %%rsi");
                 emit("addq %%rsi, %%rsp");
                 emit("pop %%r10");
                 emit("pop %%r9");
                 emit("pop %%r8");
                 emit("pop %%rdi");
 //              emit("frstor 4(%%r9, %%rsi, 1)");
                 STACK_PUSH(4);
                 emit("movl %%eax, (%%r9, %%rbx, 4)"); // store return value
                 neednilabel = 1;
                 break;
             case OP_PUSH:
                 MAYBE_EMIT_CONST();
                 STACK_PUSH(4);
                 break;
             case OP_POP:
                 MAYBE_EMIT_CONST();
                 STACK_POP(4);
                 break;
             case OP_CONST:
                 MAYBE_EMIT_CONST();
 #ifdef CONST_OPTIMIZE
                 got_const = 1;
                 const_value = iarg;
 #else
                 STACK_PUSH(4);
                 emit("movl $%d, (%%r9, %%rbx, 4)", iarg);
 #endif
                 break;
             case OP_LOCAL:
                 MAYBE_EMIT_CONST();
                 emit("movl %%edi, %%esi");
                 emit("addl $%d,%%esi", iarg);
                 STACK_PUSH(4);
                 emit("movl %%esi, (%%r9, %%rbx, 4)");
                 break;
             case OP_JUMP:
                 if(got_const) {
                     iarg = const_value;
                     got_const = 0;
                     JMPIARG();
                 } else {
                     emit("movl (%%r9, %%rbx, 4), %%eax"); // get instr from stack
                     STACK_POP(4);
                     PREPARE_JMP(eax);
                     emit("jmp *%%rax");
                 }
                 break;
             case OP_EQ:
                 IJ("jne");
                 break;
             case OP_NE:
                 IJ("je");
                 break;
             case OP_LTI:
                 IJ("jnl");
                 break;
             case OP_LEI:
                 IJ("jnle");
                 break;
             case OP_GTI:
                 IJ("jng");
                 break;
             case OP_GEI:
                 IJ("jnge");
                 break;
             case OP_LTU:
                 IJ("jnb");
                 break;
             case OP_LEU:
                 IJ("jnbe");
                 break;
             case OP_GTU:
                 IJ("jna");
                 break;
             case OP_GEU:
                 IJ("jnae");
                 break;
             case OP_EQF:
                 FJ(0x40, "jz");
                 XJ("jnz");
                 break;
             case OP_NEF:
                 FJ(0x40, "jnz");
 #ifndef USE_X87
                 MAYBE_EMIT_CONST();
                 STACK_POP(8);
                 emit("movss 4(%%r9, %%rbx, 4), %%xmm0");
                 emit("ucomiss 8(%%r9, %%rbx, 4), %%xmm0");
                 emit("jp dojump_i_%08x", instruction);
                 emit("jz i_%08x", instruction+1);
                 emit("dojump_i_%08x:", instruction);
                 JMPIARG();
                 neednilabel = 1;
 #endif
                 break;
             case OP_LTF:
                 FJ(0x01, "jz");
                 XJ("jnc");
                 break;
             case OP_LEF:
                 FJ(0x41, "jz");
                 XJ("ja");
                 break;
             case OP_GTF:
                 FJ(0x41, "jnz");
                 XJ("jbe");
                 break;
             case OP_GEF:
                 FJ(0x01, "jnz");
                 XJ("jb");
                 break;
             case OP_LOAD1:
                 MAYBE_EMIT_CONST();
                 emit("movl (%%r9, %%rbx, 4), %%eax"); // get value from stack
                 RANGECHECK(eax, 1);
                 emit("movb (%%r8, %%rax, 1), %%al"); // deref into eax
                 emit("andq $255, %%rax");
                 emit("movl %%eax, (%%r9, %%rbx, 4)"); // store on stack
                 break;
             case OP_LOAD2:
                 MAYBE_EMIT_CONST();
                 emit("movl (%%r9, %%rbx, 4), %%eax"); // get value from stack
                 RANGECHECK(eax, 2);
                 emit("movw (%%r8, %%rax, 1), %%ax"); // deref into eax
                 emit("movl %%eax, (%%r9, %%rbx, 4)"); // store on stack
                 break;
             case OP_LOAD4:
                 MAYBE_EMIT_CONST();
                 emit("movl (%%r9, %%rbx, 4), %%eax"); // get value from stack
                 RANGECHECK(eax, 4); // not a pointer!?
                 emit("movl (%%r8, %%rax, 1), %%eax"); // deref into eax
                 emit("movl %%eax, (%%r9, %%rbx, 4)"); // store on stack
                 break;
             case OP_STORE1:
                 MAYBE_EMIT_CONST();
                 emit("movl (%%r9, %%rbx, 4), %%eax"); // get value from stack
                 STACK_POP(8);
                 emit("andq $255, %%rax");
                 emit("movl 4(%%r9, %%rbx, 4), %%esi"); // get pointer from stack
                 RANGECHECK(esi, 1);
                 emit("movb %%al, (%%r8, %%rsi, 1)"); // store in memory
                 break;
             case OP_STORE2:
                 MAYBE_EMIT_CONST();
                 emit("movl (%%r9, %%rbx, 4), %%eax"); // get value from stack
                 STACK_POP(8);
                 emit("movl 4(%%r9, %%rbx, 4), %%esi"); // get pointer from stack
                 RANGECHECK(esi, 2);
                 emit("movw %%ax, (%%r8, %%rsi, 1)"); // store in memory
                 break;
             case OP_STORE4:
                 MAYBE_EMIT_CONST();
                 emit("movl (%%r9, %%rbx, 4), %%eax"); // get value from stack
                 STACK_POP(8);
                 emit("movl 4(%%r9, %%rbx, 4), %%esi"); // get pointer from stack
                 RANGECHECK(esi, 4);
                 emit("movl %%eax, (%%r8, %%rsi, 1)"); // store in memory
                 break;
             case OP_ARG:
                 MAYBE_EMIT_CONST();
                 emit("movl (%%r9, %%rbx, 4), %%eax"); // get value from stack
                 STACK_POP(4);
                 emit("movl $0x%hx, %%esi", barg);
                 emit("addl %%edi, %%esi");
                 RANGECHECK(esi, 4);
                 emit("movl %%eax, (%%r8,%%rsi, 1)"); // store in args space
                 break;
             case OP_BLOCK_COPY:
                 MAYBE_EMIT_CONST();
                 STACK_POP(8);
                 emit("push %%rdi");
                 emit("push %%r8");
                 emit("push %%r9");
                 emit("push %%r10");
                 emit("movq %%rsp, %%rsi"); // we need to align the stack pointer
                 emit("subq $8, %%rsi");    //   |
                 emit("andq $127, %%rsi");  //   |
                 emit("subq %%rsi, %%rsp"); // <-+
                 emit("push %%rsi");
                 emit("movl 4(%%r9, %%rbx, 4), %%edi");  // 1st argument dest
                 emit("movl 8(%%r9, %%rbx, 4), %%rsi");  // 2nd argument src
                 emit("movl $%d, %%edx", iarg); // 3rd argument count
                 emit("movq $%"PRIu64", %%rax", (intptr_t) VM_BlockCopy);
                 emit("callq *%%rax");
                 emit("pop %%rsi");
                 emit("addq %%rsi, %%rsp");
                 emit("pop %%r10");
                 emit("pop %%r9");
                 emit("pop %%r8");
                 emit("pop %%rdi");
                 break;
             case OP_SEX8:
                 MAYBE_EMIT_CONST();
                 emit("movw (%%r9, %%rbx, 4), %%ax");
                 emit("andq $255, %%rax");
                 emit("cbw");
                 emit("cwde");
                 emit("movl %%eax, (%%r9, %%rbx, 4)");
                 break;
             case OP_SEX16:
                 MAYBE_EMIT_CONST();
                 emit("movw (%%r9, %%rbx, 4), %%ax");
                 emit("cwde");
                 emit("movl %%eax, (%%r9, %%rbx, 4)");
                 break;
             case OP_NEGI:
                 MAYBE_EMIT_CONST();
                 emit("negl (%%r9, %%rbx, 4)");
                 break;
             case OP_ADD:
                 SIMPLE("addl");
                 break;
             case OP_SUB:
                 SIMPLE("subl");
                 break;
             case OP_DIVI:
                 MAYBE_EMIT_CONST();
                 STACK_POP(4);
                 emit("movl (%%r9, %%rbx, 4), %%eax");
                 emit("cdq");
                 emit("idivl 4(%%r9, %%rbx, 4)");
                 emit("movl %%eax, (%%r9, %%rbx, 4)");
                 break;
             case OP_DIVU:
                 MAYBE_EMIT_CONST();
                 STACK_POP(4);
                 emit("movl (%%r9, %%rbx, 4), %%eax");
                 emit("xorq %%rdx, %%rdx");
                 emit("divl 4(%%r9, %%rbx, 4)");
                 emit("movl %%eax, (%%r9, %%rbx, 4)");
                 break;
             case OP_MODI:
                 MAYBE_EMIT_CONST();
                 STACK_POP(4);
                 emit("movl (%%r9, %%rbx, 4), %%eax");
                 emit("xorl %%edx, %%edx");
                 emit("cdq");
                 emit("idivl 4(%%r9, %%rbx, 4)");
                 emit("movl %%edx, (%%r9, %%rbx, 4)");
                 break;
             case OP_MODU:
                 MAYBE_EMIT_CONST();
                 STACK_POP(4);
                 emit("movl (%%r9, %%rbx, 4), %%eax");
                 emit("xorl %%edx, %%edx");
                 emit("divl 4(%%r9, %%rbx, 4)");
                 emit("movl %%edx, (%%r9, %%rbx, 4)");
                 break;
             case OP_MULI:
                 MAYBE_EMIT_CONST();
                 STACK_POP(4);
                 emit("movl (%%r9, %%rbx, 4), %%eax");
                 emit("imull 4(%%r9, %%rbx, 4)");
                 emit("movl %%eax, (%%r9, %%rbx, 4)");
                 break;
             case OP_MULU:
                 MAYBE_EMIT_CONST();
                 STACK_POP(4);
                 emit("movl (%%r9, %%rbx, 4), %%eax");
                 emit("mull 4(%%r9, %%rbx, 4)");
                 emit("movl %%eax, (%%r9, %%rbx, 4)");
                 break;
             case OP_BAND:
                 SIMPLE("andl");
                 break;
             case OP_BOR:
                 SIMPLE("orl");
                 break;
             case OP_BXOR:
                 SIMPLE("xorl");
                 break;
             case OP_BCOM:
                 MAYBE_EMIT_CONST();
                 emit("notl (%%r9, %%rbx, 4)");
                 break;
             case OP_LSH:
                 SHIFT("shl");
                 break;
             case OP_RSHI:
                 SHIFT("sarl");
                 break;
             case OP_RSHU:
                 SHIFT("shrl");
                 break;
             case OP_NEGF:
                 MAYBE_EMIT_CONST();
 #ifdef USE_X87
                 emit("flds (%%r9, %%rbx, 4)");
                 emit("fchs");
                 emit("fstps (%%r9, %%rbx, 4)");
 #else
                 emit("movl $0x80000000, %%eax");
                 emit("xorl %%eax, (%%r9, %%rbx, 4)");
 #endif
                 break;
             case OP_ADDF:
                 FSIMPLE("fadds");
                 XSIMPLE("addss");
                 break;
             case OP_SUBF:
                 FSIMPLE("fsubs");
                 XSIMPLE("subss");
                 break;
             case OP_DIVF:
                 FSIMPLE("fdivs");
                 XSIMPLE("divss");
                 break;
             case OP_MULF:
                 FSIMPLE("fmuls");
                 XSIMPLE("mulss");
                 break;
             case OP_CVIF:
                 MAYBE_EMIT_CONST();
 #ifdef USE_X87
                 emit("filds (%%r9, %%rbx, 4)");
                 emit("fstps (%%r9, %%rbx, 4)");
 #else
                 emit("movl (%%r9, %%rbx, 4), %%eax");
                 emit("cvtsi2ss %%eax, %%xmm0");
                 emit("movss %%xmm0, (%%r9, %%rbx, 4)");
 #endif
                 break;
             case OP_CVFI:
                 MAYBE_EMIT_CONST();
 #ifdef USE_X87
                 emit("flds (%%r9, %%rbx, 4)");
                 emit("fnstcw 4(%%r9, %%rbx, 4)");
                 emit("movw $0x0F7F, 8(%%r9, %%rbx, 4)"); // round toward zero
                 emit("fldcw 8(%%r9, %%rbx, 4)");
                 emit("fistpl (%%r9, %%rbx, 4)");
                 emit("fldcw 4(%%r9, %%rbx, 4)");
 #else
                 emit("movss (%%r9, %%rbx, 4), %%xmm0");
                 emit("cvttss2si %%xmm0, %%eax");
                 emit("movl %%eax, (%%r9, %%rbx, 4)");
 #endif
                 break;
             default:
                 NOTIMPL(op);
                 break;
         }
     }
     if(got_const)
     {
         VM_FREEBUFFERS(vm);
         Com_Error(ERR_DROP, "leftover const");
     }
     emit("movq $%"PRIu64", %%rax", (intptr_t) eop);
     emit("callq *%%rax");
     } // pass loop
     assembler_init(0);
     #ifdef VM_X86_64_MMAP
         if(mprotect(vm->codeBase, compiledOfs, PROT_READ|PROT_EXEC))
             Com_Error(ERR_FATAL, "VM_CompileX86_64: mprotect failed");
     #elif __WIN64__
         {
             DWORD oldProtect = 0;
             // remove write permissions; give exec permision
             if(!VirtualProtect(vm->codeBase, compiledOfs, PAGE_EXECUTE_READ, &oldProtect))
                 Com_Error(ERR_FATAL, "VM_CompileX86_64: VirtualProtect failed");
         }
     #endif
     vm->destroy = VM_Destroy_Compiled;
 #ifdef DEBUG_VM
     fflush(qdasmout);
     fclose(qdasmout);
 #if 0
     strcpy(fn_d,vm->name);
     strcat(fn_d, ".bin");
     qdasmout = fopen(fn_d, "w");
     fwrite(vm->codeBase, compiledOfs, 1, qdasmout);
     fflush(qdasmout);
     fclose(qdasmout);
 #endif
 #endif
     #ifndef __WIN64__ //timersub and gettimeofday
         if(vm->compiled)
         {
             struct timeval tvdone =  {0, 0};
             struct timeval dur =  {0, 0};
             Com_Printf( "VM file %s compiled to %i bytes of code (%p - %p)\n", vm->name, vm->codeLength, vm->codeBase, vm->codeBase+vm->codeLength );
             gettimeofday(&tvdone, NULL);
             timersub(&tvdone, &tvstart, &dur);
             Com_Printf( "compilation took %"PRIu64".%06"PRIu64" seconds\n", dur.tv_sec, dur.tv_usec );
         }
     #endif
 }
References assembler_get_code_size(), assembler_init(), assembler_set_output(), callAsmCall(), CHECK_INSTR, code, Com_Error(), Com_Printf(), compiledOfs, Dfprintf, emit(), ERR_DROP, ERR_FATAL, FJ, FSIMPLE, fwrite(), IJ, instruction, intptr_t(), JMPIARG, MAP_ANONYMOUS, MAX_QPATH, MAYBE_EMIT_CONST, NOTIMPL, NULL, op, OP_ADD, OP_ADDF, OP_ARG, op_argsize, OP_BAND, OP_BCOM, OP_BLOCK_COPY, OP_BOR, OP_BREAK, OP_BXOR, OP_CALL, OP_CONST, OP_CVFI, OP_CVIF, OP_DIVF, OP_DIVI, OP_DIVU, OP_ENTER, OP_EQ, OP_EQF, OP_GEF, OP_GEI, OP_GEU, OP_GTF, OP_GTI, OP_GTU, OP_IGNORE, OP_JUMP, OP_LEAVE, OP_LEF, OP_LEI, OP_LEU, OP_LOAD1, OP_LOAD2, OP_LOAD4, OP_LOCAL, OP_LSH, OP_LTF, OP_LTI, OP_LTU, OP_MODI, OP_MODU, OP_MULF, OP_MULI, OP_MULU, OP_NE, OP_NEF, OP_NEGF, OP_NEGI, OP_POP, OP_PUSH, OP_RSHI, OP_RSHU, OP_SEX16, OP_SEX8, OP_STORE1, OP_STORE2, OP_STORE4, OP_SUB, OP_SUBF, OP_UNDEF, opnames, pass, pc, PREPARE_JMP, RANGECHECK, SHIFT, SIMPLE, STACK_POP, STACK_PUSH, VM_BlockCopy(), VM_Destroy_Compiled(), VM_FREEBUFFERS, XJ, and XSIMPLE.
Referenced by VM_Create().
VM_Destroy_Compiled()
void VM_Destroy_Compiled (vm_t * self) static
Definition at line 991 of file vm_x86_64.c.
 {
     if(self && self->codeBase)
     {
 #ifdef VM_X86_64_MMAP
         munmap(self->codeBase, self->codeLength);
 #elif __WIN64__
         VirtualFree(self->codeBase, 0, MEM_RELEASE);
 #else
         free(self->codeBase);
 #endif
     }
 }
Referenced by VM_Compile().
Variable Documentation
op_argsize
unsigned char op_argsize[256] static
Initial value:
=
{
    [OP_ENTER]      = 4,
    [OP_LEAVE]      = 4,
    [OP_CONST]      = 4,
    [OP_LOCAL]      = 4,
    [OP_EQ]         = 4,
    [OP_NE]         = 4,
    [OP_LTI]        = 4,
    [OP_LEI]        = 4,
    [OP_GTI]        = 4,
    [OP_GEI]        = 4,
    [OP_LTU]        = 4,
    [OP_LEU]        = 4,
    [OP_GTU]        = 4,
    [OP_GEU]        = 4,
    [OP_EQF]        = 4,
    [OP_NEF]        = 4,
    [OP_LTF]        = 4,
    [OP_LEF]        = 4,
    [OP_GTF]        = 4,
    [OP_GEF]        = 4,
    [OP_ARG]        = 1,
    [OP_BLOCK_COPY] = 4,
}
Definition at line 206 of file vm_x86_64.c.
Referenced by VM_Compile().