ZEQ2-Lite: Source/Game/UI/ui_main.c File Reference
ui_main.c File Reference
#include "ui_local.h"
Data Structures
struct cvarTable_t
Functions
void UI_RegisterCvars (void)
void UI_UpdateCvars (void)
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
Variables
static cvarTable_t cvarTable []
static int cvarTableSize = ARRAY_LEN(cvarTable)
vmCvar_t s_mastermusicvolume
vmCvar_t ui_arenasFile
vmCvar_t ui_brassTime
vmCvar_t ui_browserGameType
vmCvar_t ui_browserMaster
vmCvar_t ui_browserShowEmpty
vmCvar_t ui_browserShowFull
vmCvar_t ui_browserSortKey
vmCvar_t ui_drawCrosshair
vmCvar_t ui_drawCrosshairNames
vmCvar_t ui_ffa_breakLimitRate
vmCvar_t ui_ffa_fraglimit
vmCvar_t ui_ffa_powerlevel
vmCvar_t ui_ffa_powerlevelMaximum
vmCvar_t ui_ffa_timelimit
vmCvar_t ui_marks
vmCvar_t ui_server1
vmCvar_t ui_server10
vmCvar_t ui_server11
vmCvar_t ui_server12
vmCvar_t ui_server13
vmCvar_t ui_server14
vmCvar_t ui_server15
vmCvar_t ui_server16
vmCvar_t ui_server2
vmCvar_t ui_server3
vmCvar_t ui_server4
vmCvar_t ui_server5
vmCvar_t ui_server6
vmCvar_t ui_server7
vmCvar_t ui_server8
vmCvar_t ui_server9
Function Documentation
UI_RegisterCvars()
void UI_RegisterCvars (void)
Definition at line 185 of file ui_main.c.
{
     int         i;
     cvarTable_t *cv;
     for ( i = 0, cv = cvarTable ; i < cvarTableSize ; i++, cv++ ) {
         trap_Cvar_Register( cv->vmCvar, cv->cvarName, cv->defaultString, cv->cvarFlags );
     }
 }
References cvarTable_t::cvarFlags, cvarTable_t::cvarName, cvarTable, cvarTableSize, cvarTable_t::defaultString, trap_Cvar_Register(), and cvarTable_t::vmCvar.
Referenced by UI_Init().
UI_UpdateCvars()
void UI_UpdateCvars (void)
Definition at line 199 of file ui_main.c.
{
     int         i;
     cvarTable_t *cv;
     for ( i = 0, cv = cvarTable ; i < cvarTableSize ; i++, cv++ ) {
         trap_Cvar_Update( cv->vmCvar );
     }
 }
References cvarTable, cvarTableSize, trap_Cvar_Update(), and cvarTable_t::vmCvar.
Referenced by UI_Refresh().
vmMain()
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
Definition at line 43 of file ui_main.c.
{
     switch ( command ) {
     case UI_GETAPIVERSION:
         return UI_API_VERSION;
     case UI_INIT:
         UI_Init();
         return 0;
     case UI_SHUTDOWN:
         UI_Shutdown();
         return 0;
     case UI_KEY_EVENT:
         UI_KeyEvent( arg0, arg1 );
         return 0;
     case UI_MOUSE_EVENT:
         UI_MouseEvent( arg0, arg1 );
         return 0;
     case UI_REFRESH:
         UI_Refresh( arg0 );
         return 0;
     case UI_IS_FULLSCREEN:
         return UI_IsFullscreen();
     case UI_SET_ACTIVE_MENU:
         UI_SetActiveMenu( arg0 );
         return 0;
     case UI_CONSOLE_COMMAND:
         return UI_ConsoleCommand(arg0);
     case UI_DRAW_CONNECT_SCREEN:
         UI_DrawConnectScreen( arg0 );
         return 0;
     }
     return -1;
 }
References UI_API_VERSION, UI_CONSOLE_COMMAND, UI_ConsoleCommand(), UI_DRAW_CONNECT_SCREEN, UI_DrawConnectScreen(), UI_GETAPIVERSION, UI_INIT, UI_Init(), UI_IS_FULLSCREEN, UI_IsFullscreen(), UI_KEY_EVENT, UI_KeyEvent(), UI_MOUSE_EVENT, UI_MouseEvent(), UI_REFRESH, UI_Refresh(), UI_SET_ACTIVE_MENU, UI_SetActiveMenu(), UI_SHUTDOWN, and UI_Shutdown().
Variable Documentation
cvarTable
cvarTable_t cvarTable[] static
Definition at line 137 of file ui_main.c.
Referenced by UI_RegisterCvars(), and UI_UpdateCvars().
cvarTableSize
int cvarTableSize = ARRAY_LEN(cvarTable) static
Definition at line 177 of file ui_main.c.
Referenced by UI_RegisterCvars(), and UI_UpdateCvars().
s_mastermusicvolume
vmCvar_t s_mastermusicvolume
Definition at line 136 of file ui_main.c.
ui_arenasFile
vmCvar_t ui_arenasFile
Definition at line 106 of file ui_main.c.
ui_brassTime
vmCvar_t ui_brassTime
Definition at line 114 of file ui_main.c.
ui_browserGameType
vmCvar_t ui_browserGameType
Definition at line 109 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserMaster
vmCvar_t ui_browserMaster
Definition at line 108 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserShowEmpty
vmCvar_t ui_browserShowEmpty
Definition at line 112 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserShowFull
vmCvar_t ui_browserShowFull
Definition at line 111 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserSortKey
vmCvar_t ui_browserSortKey
Definition at line 110 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_drawCrosshair
vmCvar_t ui_drawCrosshair
Definition at line 115 of file ui_main.c.
ui_drawCrosshairNames
vmCvar_t ui_drawCrosshairNames
Definition at line 116 of file ui_main.c.
ui_ffa_breakLimitRate
vmCvar_t ui_ffa_breakLimitRate
Definition at line 104 of file ui_main.c.
ui_ffa_fraglimit
vmCvar_t ui_ffa_fraglimit
Definition at line 100 of file ui_main.c.
ui_ffa_powerlevel
vmCvar_t ui_ffa_powerlevel
Definition at line 102 of file ui_main.c.
ui_ffa_powerlevelMaximum
vmCvar_t ui_ffa_powerlevelMaximum
Definition at line 103 of file ui_main.c.
ui_ffa_timelimit
vmCvar_t ui_ffa_timelimit
Definition at line 101 of file ui_main.c.
ui_marks
vmCvar_t ui_marks
Definition at line 117 of file ui_main.c.
ui_server1
vmCvar_t ui_server1
Definition at line 119 of file ui_main.c.
ui_server10
vmCvar_t ui_server10
Definition at line 128 of file ui_main.c.
ui_server11
vmCvar_t ui_server11
Definition at line 129 of file ui_main.c.
ui_server12
vmCvar_t ui_server12
Definition at line 130 of file ui_main.c.
ui_server13
vmCvar_t ui_server13
Definition at line 131 of file ui_main.c.
ui_server14
vmCvar_t ui_server14
Definition at line 132 of file ui_main.c.
ui_server15
vmCvar_t ui_server15
Definition at line 133 of file ui_main.c.
ui_server16
vmCvar_t ui_server16
Definition at line 134 of file ui_main.c.
ui_server2
vmCvar_t ui_server2
Definition at line 120 of file ui_main.c.
ui_server3
vmCvar_t ui_server3
Definition at line 121 of file ui_main.c.
ui_server4
vmCvar_t ui_server4
Definition at line 122 of file ui_main.c.
ui_server5
vmCvar_t ui_server5
Definition at line 123 of file ui_main.c.
ui_server6
vmCvar_t ui_server6
Definition at line 124 of file ui_main.c.
ui_server7
vmCvar_t ui_server7
Definition at line 125 of file ui_main.c.
ui_server8
vmCvar_t ui_server8
Definition at line 126 of file ui_main.c.
ui_server9
vmCvar_t ui_server9
Definition at line 127 of file ui_main.c.