ZEQ2-Lite: Source/Engine/tools/lcc/src/profio.c File Reference
profio.c File Reference
#include "c.h"
Data Structures
struct file::func::caller
struct count
struct file
struct file::func
Macros
#define MAXTOKEN 64
Functions
static void acaller (char *caller, char *file, int x, int y, int count, struct func *callee)
static struct func * afunction (char *name, char *file, int x, int y, int count)
static void apoint (int i, char *file, int x, int y, int count)
static int compare (struct count *a, struct count *b)
int findcount (char *file, int x, int y)
static struct file * findfile (char *name)
int findfunc (char *name, char *file)
static int gather (void)
static int getd (void)
static char * getstr (void)
int process (char *file)
Variables
struct file * filelist
FILE * fp
Macro Definition Documentation
MAXTOKEN
#define MAXTOKEN 64
Definition at line 22 of file profio.c.
Function Documentation
acaller()
static void acaller (char * caller, char * file, int x, int y, int count, struct func * callee) static
Definition at line 46 of file profio.c.
{
     struct caller *q;
     assert(callee);
     for (q = callee->callers; q && (caller != q->name
         || file != q->file || x != q->x || y != q->y); q = q->link)
         ;
     if (!q) {
         struct caller **r;
         NEW(q, PERM);
         q->name = caller;
         q->file = file;
         q->x = x;
         q->y = y;
         q->count = 0;
         for (r = &callee->callers; *r && (strcmp(q->name, (*r)->name) > 0
             || strcmp(q->file, (*r)->file) > 0 || q->y > (*r)->y || q->y > (*r)->y); r = &(*r)->link)
             ;
         q->link = *r;
         *r = q;
     }
     q->count += count;
 }
References func::callers, file, NEW, and PERM.
Referenced by gather().
afunction()
static struct func* afunction (char * name, char * file, int x, int y, int count) static
Definition at line 88 of file profio.c.
{
     struct file *p = findfile(file);
     struct func *q;
     assert(p);
     for (q = p->funcs; q && name != q->name; q = q->link)
         ;
     if (!q) {
         struct func **r;
         NEW(q, PERM);
         q->name = name;
         q->count.x = x;
         q->count.y = y;
         q->count.count = 0;
         q->callers = 0;
         for (r = &p->funcs; *r && compare(&q->count, &(*r)->count) > 0; r = &(*r)->link)
             ;
         q->link = *r;
         *r = q;
     }
     q->count.count += count;
     return q;
 }
References compare(), findfile(), NEW, and PERM.
Referenced by gather().
apoint()
static void apoint (int i, char * file, int x, int y, int count) static
Definition at line 113 of file profio.c.
{
     struct file *p = findfile(file);
     assert(p);
     if (i >= p->size) {
         int j;
         if (p->size == 0) {
             p->size = i >= 200 ? 2*i : 200;
             p->counts = newarray(p->size, sizeof *p->counts, PERM);
         } else {
             struct count *new;
             p->size = 2*i;
             new = newarray(p->size, sizeof *new, PERM);
             for (j = 0; j < p->count; j++)
                 new[j] = p->counts[j];
             p->counts = new;
         }
         for (j = p->count; j < p->size; j++) {
             static struct count z;
             p->counts[j] = z;
         }
     }
     p->counts[i].x = x;
     p->counts[i].y = y;
     p->counts[i].count += count;
     if (i >= p->count)
         p->count = i + 1;
 }
References findfile(), newarray(), and PERM.
Referenced by gather().
compare()
static int compare (struct count * a, struct count * b) static
Definition at line 71 of file profio.c.
{
     if (a->y == b->y)
         return a->x - b->x;
     return a->y - b->y;
 }
Referenced by AddIP(), afunction(), process(), and UpdateIPBans().
findcount()
int findcount (char * file, int x, int y)
Definition at line 143 of file profio.c.
{
     static struct file *cursor;
     if (cursor == 0 || cursor->name != file)
         cursor = findfile(file);
     if (cursor) {
         int l, u;
         struct count *c = cursor->counts;
         for (l = 0, u = cursor->count - 1; l <= u; ) {
             int k = (l + u)/2;
             if (c[k].y > y || (c[k].y == y && c[k].x > x))
                 u = k - 1;
             else if (c[k].y < y || (c[k].y == y && c[k].x < x))
                 l = k + 1;
             else
                 return c[k].count;
         }
     }
     return -1;
 }
References count::count, file::count, file::counts, findfile(), and file::name.
Referenced by definept().
findfile()
static struct file* findfile (char * name) static
Definition at line 78 of file profio.c.
{
     struct file *p;
     for (p = filelist; p; p = p->link)
         if (p->name == name)
             return p;
     return 0;
 }
References filelist.
Referenced by afunction(), apoint(), findcount(), findfunc(), and gather().
findfunc()
int findfunc (char * name, char * file)
Definition at line 165 of file profio.c.
{
     static struct file *cursor;
     if (cursor == 0 || cursor->name != file)
         cursor = findfile(file);
     if (cursor) {
         struct func *p;
         for (p = cursor->funcs; p; p = p->link)
             if (p->name == name)
                 return p->count.count;
     }
     return -1;
 }
References findfile(), file::funcs, file::func::link, and file::name.
Referenced by funcdefn().
gather()
static int gather (void) static
Definition at line 207 of file profio.c.
{
     int i, nfiles, nfuncs, npoints;
     char *files[64];
     if ((nfiles = getd()) < 0)
         return 0;
     assert(nfiles < NELEMS(files));
     for (i = 0; i < nfiles; i++) {
         if ((files[i] = getstr()) == 0)
             return -1;
         if (!findfile(files[i])) {
             struct file *new;
             NEW(new, PERM);
             new->name = files[i];
             new->size = new->count = 0;
             new->counts = 0;
             new->funcs = 0;
             new->link = filelist;
             filelist = new;
         }
     }
     if ((nfuncs = getd()) < 0)
         return -1;
     for (i = 0; i < nfuncs; i++) {
         struct func *q;
         char *name, *file;
         int f, x, y, count;
         if ((name = getstr()) == 0 || (f = getd()) <= 0
         || (x = getd()) < 0 || (y = getd()) < 0 || (count = getd()) < 0)
             return -1;
         q = afunction(name, files[f-1], x, y, count);
         if ((name = getstr()) == 0 || (file = getstr()) == 0
         || (x = getd()) < 0 || (y = getd()) < 0)
             return -1;
         if (*name != '?')
             acaller(name, file, x, y, count, q);
     }
     if ((npoints = getd()) < 0)
         return -1;
     for (i = 0; i < npoints; i++) {
         int f, x, y, count;
         if ((f = getd()) < 0 || (x = getd()) < 0 || (y = getd()) < 0
         || (count = getd()) < 0)
             return -1;
         if (f)
             apoint(i, files[f-1], x, y, count);
     }
     return 1;
 }
References acaller(), afunction(), apoint(), file, filelist, findfile(), getd(), getstr(), NELEMS, NEW, npoints, and PERM.
Referenced by process().
getd()
static int getd (void) static
Definition at line 180 of file profio.c.
                       {
     int c, n = 0;
     while ((c = getc(fp)) != EOF && (c == ' ' || c == '\n' || c == '\t'))
         ;
     if (c >= '0' && c <= '9') {
         do
             n = 10*n + (c - '0');
         while ((c = getc(fp)) >= '0' && c <= '9');
         return n;
     }
     return -1;
 }
References EOF, and fp.
Referenced by gather().
getstr()
static char* getstr (void) static
Definition at line 195 of file profio.c.
{
     int c;
     char buf[MAXTOKEN], *s = buf;
     while ((c = getc(fp)) != EOF && c != ' ' && c != '\n' && c != '\t')
         if (s - buf < (int)sizeof buf - 2)
             *s++ = c;
     *s = 0;
     return s == buf ? (char *)0 : string(buf);
 }
References EOF, fp, and MAXTOKEN.
Referenced by gather().
process()
int process (char * file)
Definition at line 258 of file profio.c.
{
     int more;
     if ((fp = fopen(file, "r")) != NULL) {
         struct file *p;
         while ((more = gather()) > 0)
             ;
         fclose(fp);
         if (more < 0)
             return more;
         for (p = filelist; p; p = p->link)
             qsort(p->counts, p->count, sizeof *p->counts,
                 (int (*)(const void *, const void *))
                 compare);
         return 1;
     }
     return 0;
 }
References compare(), filelist, fp, gather(), int(), and NULL.
Variable Documentation
filelist
struct file * filelist
Referenced by findfile(), FS_SortFileList(), gather(), PlayerModel_BuildList(), and process().
fp
FILE* fp
Definition at line 43 of file profio.c.
Referenced by __do_emit_one(), analyze_function(), compile_function(), compile_one_insn(), do_emit_const(), dst_insn_append(), dst_insn_insert_tail(), dst_new(), emit_jump(), emit_vm_thunk(), end_emit(), expandlex(), free_source_insns(), FS_SV_FOpenFileRead(), getd(), getstr(), jump_insn_append(), jump_insn_insert_tail(), process(), setup(), sparc_compute_code(), sparc_push_data(), start_emit(), and Sys_RandomBytes().