ZEQ2-Lite: Engine/tools/lcc/src/prof.c File Reference
prof.c File Reference
#include "c.h"
Data Structures
struct callsite
union callsite::coordinate
struct func
struct map
Functions
static void bbcall (Symbol yycounts, Coordinate *cp, Tree *e)
static void bbentry (Symbol yylink, Symbol f)
static void bbexit (Symbol yylink, Symbol f, Tree e)
static int bbfile (char *file)
static void bbfunc (Symbol yylink, Symbol f)
static void bbincr (Symbol yycounts, Coordinate *cp, Tree *e)
static void bbvars (Symbol yylink)
void prof_init (int argc, char *argv[])
Variables
static Symbol afunc
static List filelist
static Symbol funclist
static List maplist
int ncalled = -1
int npoints
static Symbol YYcounts
static Symbol YYlink
Function Documentation
bbcall()
static void bbcall (Symbol yycounts, Coordinate * cp, Tree * e) static
Definition at line 33 of file prof.c.
{
     static Symbol caller;
     Value v;
     union coordinate u;
     Symbol p = genident(STATIC, array(voidptype, 0, 0), GLOBAL);
     Tree t = *e;
     defglobal(p, LIT);
     defpointer(cp->file ? mkstr(cp->file)->u.c.loc : (Symbol)0);
     defpointer(mkstr(cfunc->name)->u.c.loc);
     if (IR->little_endian) {
         u.le.x = cp->x;
         u.le.y = cp->y;
     } else {
         u.be.x = cp->x;
         u.be.y = cp->y;
     }
     (*IR->defconst)(U, unsignedtype->size, (v.u = u.coord, v));
     if (caller == 0) {
         caller = mksymbol(EXTERN, "_caller", ptr(voidptype));
         caller->defined = 0;
     }
     if (generic((*e)->op) != CALL)
         t = (*e)->kids[0];
     assert(generic(t->op) == CALL);
     t = tree(t->op, t->type,
         tree(RIGHT, t->kids[0]->type,
             t->kids[0],
             tree(RIGHT, t->kids[0]->type, asgn(caller, idtree(p)), t->kids[0])),
         t->kids[1]);
     if (generic((*e)->op) != CALL)
         t = tree((*e)->op, (*e)->type, t, (*e)->kids[1]);
     *e = t;
 }
References array(), asgn(), CALL, cfunc, cp, defglobal(), defpointer(), EXTERN, genident(), GLOBAL, idtree(), IR, Tree::kids, LIT, mkstr(), mksymbol(), ptr(), RIGHT, tree(), U, unsignedtype, and voidptype.
Referenced by prof_init().
bbentry()
static void bbentry (Symbol yylink, Symbol f) static
Definition at line 69 of file prof.c.
{
     static Symbol prologue;
     afunc = genident(STATIC, array(voidptype, 4, 0), GLOBAL);
     if (prologue == 0) {
         prologue = mksymbol(EXTERN, "_prologue", ftype(inttype, voidptype));
         prologue->defined = 0;
     }
     walk(vcall(prologue, voidtype, pointer(idtree(afunc)), pointer(idtree(yylink)), NULL), 0, 0);
 }
References afunc, array(), EXTERN, ftype(), genident(), GLOBAL, idtree(), inttype, mksymbol(), NULL, vcall(), voidptype, voidtype, and walk().
Referenced by prof_init().
bbexit()
static void bbexit (Symbol yylink, Symbol f, Tree e) static
Definition at line 82 of file prof.c.
{
     static Symbol epilogue;
     if (epilogue == 0) {
         epilogue = mksymbol(EXTERN, "_epilogue", ftype(inttype, voidptype));
         epilogue->defined = 0;
     }
     walk(vcall(epilogue, voidtype, pointer(idtree(afunc)), NULL), 0, 0);
 }
References afunc, EXTERN, ftype(), idtree(), inttype, mksymbol(), NULL, vcall(), voidptype, voidtype, and walk().
Referenced by prof_init().
bbfile()
static int bbfile (char * file) static
Definition at line 93 of file prof.c.
{
     if (file) {
         List lp;
         int i = 1;
         if ((lp = filelist) != NULL)
             do {
                 lp = lp->link;
                 if (((Symbol)lp->x)->u.c.v.p == file)
                     return i;
                 i++;
             } while (lp != filelist);
         filelist = append(mkstr(file), filelist);
         return i;
     }
     return 0;
 }
References append(), filelist, mkstr(), and NULL.
Referenced by bbfunc(), and bbincr().
bbfunc()
static void bbfunc (Symbol yylink, Symbol f) static
Definition at line 111 of file prof.c.
{
     Value v;
     union coordinate u;
     defglobal(afunc, DATA);
     defpointer(funclist);
     defpointer(NULL);
     defpointer(mkstr(f->name)->u.c.loc);
     if (IR->little_endian) {
         u.le.x = f->u.f.pt.x;
         u.le.y = f->u.f.pt.y;
         u.le.index = bbfile(f->u.f.pt.file);
     } else {
         u.be.x = f->u.f.pt.x;
         u.be.y = f->u.f.pt.y;
         u.be.index = bbfile(f->u.f.pt.file);
     }
     (*IR->defconst)(U, unsignedtype->size, (v.u = u.coord, v));
     funclist = afunc;
 }
References afunc, bbfile(), DATA, defglobal(), defpointer(), funclist, IR, mkstr(), NULL, U, and unsignedtype.
Referenced by prof_init().
bbincr()
static void bbincr (Symbol yycounts, Coordinate * cp, Tree * e) static
Definition at line 133 of file prof.c.
{
     struct map *mp = maplist->x;
     Tree t;
     /* append *cp to source map */
     if (mp->size >= NELEMS(mp->u)) {
         NEW(mp, PERM);
         mp->size = 0;
         maplist = append(mp, maplist);
     }
     if (IR->little_endian) {
         mp->u[mp->size].le.x = cp->x;
         mp->u[mp->size].le.y = cp->y;
         mp->u[mp->size++].le.index = bbfile(cp->file);
     } else {
         mp->u[mp->size].be.x = cp->x;
         mp->u[mp->size].be.y = cp->y;
         mp->u[mp->size++].be.index = bbfile(cp->file);
     }
     t = incr('+', rvalue((*optree['+'])(ADD, pointer(idtree(yycounts)),
         consttree(npoints++, inttype))), consttree(1, inttype));
     if (*e)
         *e = tree(RIGHT, (*e)->type, t, *e);
     else
         *e = t;
 }
References ADD, append(), bbfile(), consttree(), cp, idtree(), incr(), inttype, IR, maplist, NELEMS, NEW, npoints, optree, PERM, RIGHT, rvalue(), map::size, tree(), and map::u.
Referenced by prof_init().
bbvars()
static void bbvars (Symbol yylink) static
Definition at line 161 of file prof.c.
{
     int i, j, n = npoints;
     Value v;
     struct map **mp;
     Symbol coords, files, *p;
     if (!YYcounts && !yylink)
         return;
     if (YYcounts) {
         if (n <= 0)
             n = 1;
         YYcounts->type = array(unsignedtype, n, 0);
         defglobal(YYcounts, BSS);
     }
     files = genident(STATIC, array(charptype, 1, 0), GLOBAL);
     defglobal(files, LIT);
     for (p = ltov(&filelist, PERM); *p; p++)
         defpointer((*p)->u.c.loc);
     defpointer(NULL);
     coords = genident(STATIC, array(unsignedtype, n, 0), GLOBAL);
     defglobal(coords, LIT);
     for (i = n, mp = ltov(&maplist, PERM); *mp; i -= (*mp)->size, mp++)
         for (j = 0; j < (*mp)->size; j++)
             (*IR->defconst)(U, unsignedtype->size, (v.u = (*mp)->u[j].coord, v));
     if (i > 0)
         (*IR->space)(i*coords->type->type->size);
     defpointer(NULL);
     defglobal(yylink, DATA);
     defpointer(NULL);
     (*IR->defconst)(U, unsignedtype->size, (v.u = n, v));
     defpointer(YYcounts);
     defpointer(coords);
     defpointer(files);
     defpointer(funclist);
 }
References array(), BSS, charptype, DATA, defglobal(), defpointer(), filelist, funclist, genident(), GLOBAL, IR, LIT, ltov(), maplist, npoints, NULL, PERM, map::size, U, unsignedtype, and YYcounts.
Referenced by prof_init().
prof_init()
void prof_init (int argc, char * argv[])
Definition at line 198 of file prof.c.
{
     int i;
     static int inited;
     if (inited)
         return;
     inited = 1;
     type_init(argc, argv);
     if (IR) {
         for (i = 1; i < argc; i++)
             if (strncmp(argv[i], "-a", 2) == 0) {
                 if (ncalled == -1
                 && process(argv[i][2] ? &argv[i][2] : "prof.out") > 0)
                     ncalled = 0;
             } else if ((strcmp(argv[i], "-b") == 0
                      || strcmp(argv[i], "-C") == 0) && YYlink == 0) {
                 YYlink = genident(STATIC, array(unsignedtype, 0, 0), GLOBAL);
                 attach((Apply)bbentry, YYlink, &events.entry);
                 attach((Apply)bbexit,  YYlink, &events.returns);
                 attach((Apply)bbfunc,  YYlink, &events.exit);
                 attach((Apply)bbvars,  YYlink, &events.end);
                 if (strcmp(argv[i], "-b") == 0) {
                     YYcounts = genident(STATIC, array(unsignedtype, 0, 0), GLOBAL);
                     maplist = append(allocate(sizeof (struct map), PERM), maplist);
                     ((struct map *)maplist->x)->size = 0;
                     attach((Apply)bbcall, YYcounts, &events.calls);
                     attach((Apply)bbincr, YYcounts, &events.points);
                 }
             }
   }
 }
References allocate(), append(), array(), attach(), bbcall(), bbentry(), bbexit(), bbfunc(), bbincr(), bbvars(), Events::calls, Events::end, Events::entry, events, Events::exit, genident(), GLOBAL, IR, maplist, ncalled, PERM, Events::points, process(), Events::returns, type_init(), unsignedtype, YYcounts, and YYlink.
Referenced by init().
Variable Documentation
afunc
Symbol afunc static
Definition at line 30 of file prof.c.
Referenced by bbentry(), bbexit(), and bbfunc().
filelist
List filelist static
Definition at line 28 of file prof.c.
Referenced by bbfile(), and bbvars().
funclist
Symbol funclist static
Definition at line 29 of file prof.c.
Referenced by bbfunc(), and bbvars().
maplist
List maplist static
Definition at line 27 of file prof.c.
Referenced by bbincr(), bbvars(), and prof_init().
ncalled
int ncalled = -1
Definition at line 24 of file prof.c.
Referenced by definept(), funcdefn(), and prof_init().
npoints
int npoints
Definition at line 23 of file prof.c.
Referenced by bbincr(), bbvars(), definept(), and gather().
YYcounts
Symbol YYcounts static
Definition at line 26 of file prof.c.
Referenced by bbvars(), and prof_init().
YYlink
Symbol YYlink static
Definition at line 25 of file prof.c.
Referenced by prof_init().