ZEQ2-Lite: refexport_t Struct Reference
refexport_t Struct Reference
#include <tr_public.h>
Data Fields
void(* AddAdditiveLightToScene)(const vec3_t org, float intensity, float r, float g, float b)
void(* AddFogToScene)(float start, float end, float r, float g, float b, float opacity, float mode, float hint)
void(* AddLightToScene)(const vec3_t org, float intensity, float r, float g, float b)
void(* AddPolyToScene)(qhandle_t hShader, int numVerts, const polyVert_t *verts, int num)
void(* AddRefEntityToScene)(const refEntity_t *re)
void(* BeginFrame)(stereoFrame_t stereoFrame)
void(* BeginRegistration)(glconfig_t *config)
void(* ClearScene)(void)
void(* DrawStretchPic)(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void(* DrawStretchRaw)(int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
void(* EndFrame)(int *frontEndMsec, int *backEndMsec)
void(* EndRegistration)(void)
qboolean(* GetEntityToken)(char *buffer, int size)
qboolean(* inPVS)(const vec3_t p1, const vec3_t p2)
int(* LerpTag)(orientation_t *tag, qhandle_t model, int startFrame, int endFrame, float frac, const char *tagName)
int(* LightForPoint)(vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
void(* LoadWorld)(const char *name)
int(* MarkFragments)(int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
void(* ModelBounds)(qhandle_t model, vec3_t mins, vec3_t maxs)
void(* RegisterFont)(const char *fontName, int pointSize, fontInfo_t *font)
qhandle_t(* RegisterModel)(const char *name)
qhandle_t(* RegisterShader)(const char *name)
qhandle_t(* RegisterShaderNoMip)(const char *name)
qhandle_t(* RegisterSkin)(const char *name)
void(* RemapShader)(const char *oldShader, const char *newShader, const char *offsetTime)
void(* RenderScene)(const refdef_t *fd)
void(* SetColor)(const float *rgba)
void(* SetWorldVisData)(const byte *vis)
void(* Shutdown)(qboolean destroyWindow)
void(* TakeVideoFrame)(int h, int w, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
void(* UploadCinematic)(int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Detailed Description
Definition at line 32 of file tr_public.h.
Field Documentation
AddAdditiveLightToScene
void(* refexport_t::AddAdditiveLightToScene) (const vec3_t org, float intensity, float r, float g, float b)
Definition at line 70 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
AddFogToScene
void(* refexport_t::AddFogToScene) (float start, float end, float r, float g, float b, float opacity, float mode, float hint)
Definition at line 68 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
AddLightToScene
void(* refexport_t::AddLightToScene) (const vec3_t org, float intensity, float r, float g, float b)
Definition at line 69 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
AddPolyToScene
void(* refexport_t::AddPolyToScene) (qhandle_t hShader, int numVerts, const polyVert_t *verts, int num)
Definition at line 66 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
AddRefEntityToScene
void(* refexport_t::AddRefEntityToScene) (const refEntity_t *re)
Definition at line 65 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
BeginFrame
void(* refexport_t::BeginFrame) (stereoFrame_t stereoFrame)
Definition at line 81 of file tr_public.h.
Referenced by GetRefAPI(), and SCR_DrawScreenField().
BeginRegistration
void(* refexport_t::BeginRegistration) (glconfig_t *config)
Definition at line 47 of file tr_public.h.
Referenced by CL_InitRenderer(), and GetRefAPI().
ClearScene
void(* refexport_t::ClearScene) (void)
Definition at line 64 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
DrawStretchPic
void(* refexport_t::DrawStretchPic) (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Definition at line 74 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetRefAPI(), SCR_DrawChar(), SCR_DrawDebugGraph(), SCR_DrawNamedPic(), SCR_DrawPic(), SCR_DrawScreenField(), SCR_DrawSmallChar(), and SCR_FillRect().
DrawStretchRaw
void(* refexport_t::DrawStretchRaw) (int x, int y, int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Definition at line 78 of file tr_public.h.
Referenced by CIN_DrawCinematic(), and GetRefAPI().
EndFrame
void(* refexport_t::EndFrame) (int *frontEndMsec, int *backEndMsec)
Definition at line 84 of file tr_public.h.
Referenced by GetRefAPI(), and SCR_UpdateScreen().
EndRegistration
void(* refexport_t::EndRegistration) (void)
Definition at line 60 of file tr_public.h.
Referenced by CL_InitCGame(), and GetRefAPI().
GetEntityToken
qboolean(* refexport_t::GetEntityToken) (char *buffer, int size)
Definition at line 99 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
inPVS
qboolean(* refexport_t::inPVS) (const vec3_t p1, const vec3_t p2)
Definition at line 100 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
LerpTag
int(* refexport_t::LerpTag) (orientation_t *tag, qhandle_t model, int startFrame, int endFrame, float frac, const char *tagName)
Definition at line 90 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
LightForPoint
int(* refexport_t::LightForPoint) (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
Definition at line 67 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
LoadWorld
void(* refexport_t::LoadWorld) (const char *name)
Definition at line 52 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
MarkFragments
int(* refexport_t::MarkFragments) (int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
Definition at line 87 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), and GetRefAPI().
ModelBounds
void(* refexport_t::ModelBounds) (qhandle_t model, vec3_t mins, vec3_t maxs)
Definition at line 92 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
RegisterFont
void(* refexport_t::RegisterFont) (const char *fontName, int pointSize, fontInfo_t *font)
Definition at line 97 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
RegisterModel
qhandle_t(* refexport_t::RegisterModel) (const char *name)
Definition at line 48 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
RegisterShader
qhandle_t(* refexport_t::RegisterShader) (const char *name)
Definition at line 50 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_InitRenderer(), GetRefAPI(), and SCR_DrawNamedPic().
RegisterShaderNoMip
qhandle_t(* refexport_t::RegisterShaderNoMip) (const char *name)
Definition at line 51 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
RegisterSkin
qhandle_t(* refexport_t::RegisterSkin) (const char *name)
Definition at line 49 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
RemapShader
void(* refexport_t::RemapShader) (const char *oldShader, const char *newShader, const char *offsetTime)
Definition at line 98 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
RenderScene
void(* refexport_t::RenderScene) (const refdef_t *fd)
Definition at line 71 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and GetRefAPI().
SetColor
void(* refexport_t::SetColor) (const float *rgba)
Definition at line 73 of file tr_public.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), GetRefAPI(), SCR_DrawCustomString(), SCR_DrawDebugGraph(), SCR_DrawScreenField(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), and SCR_FillRect().
SetWorldVisData
void(* refexport_t::SetWorldVisData) (const byte *vis)
Definition at line 56 of file tr_public.h.
Referenced by GetRefAPI().
Shutdown
void(* refexport_t::Shutdown) (qboolean destroyWindow)
Definition at line 36 of file tr_public.h.
Referenced by CL_ShutdownAll(), CL_ShutdownRef(), and GetRefAPI().
TakeVideoFrame
void(* refexport_t::TakeVideoFrame) (int h, int w, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
Definition at line 102 of file tr_public.h.
Referenced by CL_TakeVideoFrame(), and GetRefAPI().
UploadCinematic
void(* refexport_t::UploadCinematic) (int w, int h, int cols, int rows, const byte *data, int client, qboolean dirty)
Definition at line 79 of file tr_public.h.
Referenced by CIN_UploadCinematic(), and GetRefAPI().
The documentation for this struct was generated from the following file:
Source/Engine/renderer/tr_public.h