ZEQ2-Lite: Engine/tools/lcc/src/c.h File Reference
c.h File Reference
#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <string.h>
#include "config.h"
#include "token.h"
Data Structures
struct binding
struct Code
struct coord
struct Events
struct Field
union floatint_t
struct interface
struct List
struct metrics
struct Node
struct Swtch
struct Symbol
struct Tree
struct Type
union value
struct Xtype
Macros
#define BUFSIZE 4096
#define extend(x, ty) ((x)&(1<<(8*(ty)->size-1)) ? (x)|((~0UL)<<(8*(ty)->size-1)) : (x)&ones(8*(ty)->size))
#define fieldleft(p)
#define fieldmask(p) (~(~(unsigned)0<<fieldsize(p)))
#define fieldright(p) ((p)->lsb - 1)
#define fieldsize(p) (p)->bitsize
#define generic(op) ((op)&0x3F0)
#define gop(name, value) name=value<<4,
#define isaddrop(op)
#define isarith(t) (unqual(t)->op <= UNSIGNED)
#define isarray(t) (unqual(t)->op == ARRAY)
#define ischar(t) ((t)->size == 1 && isint(t))
#define isconst(t)
#define isenum(t) (unqual(t)->op == ENUM)
#define isfloat(t) (unqual(t)->op == FLOAT)
#define isfunc(t) (unqual(t)->op == FUNCTION)
#define isint(t)
#define isptr(t) (unqual(t)->op == POINTER)
#define isqual(t) ((t)->op >= CONST)
#define isscalar(t)
#define isstruct(t)
#define istypename(t, tsym)
#define isunion(t) (unqual(t)->op == UNION)
#define isunsigned(t) (unqual(t)->op == UNSIGNED)
#define isvolatile(t)
#define MAXLINE 512
#define mkop(op, ty) (specific((op) + ttob(ty)))
#define NELEMS(a) ((int)(sizeof (a)/sizeof ((a)[0])))
#define NEW(p, a) ((p) = allocate(sizeof *(p), (a)))
#define NEW0(p, a) memset(NEW((p),(a)), 0, sizeof *(p))
#define ones(n) ((n)>=8*sizeof (unsigned long) ? ~0UL : ~((~0UL)<<(n)))
#define op(name, type, sizes)
#define opindex(op) (((op)>>4)&0x3F)
#define opkind(op) ((op)&~0x3F0)
#define opsize(op) ((op)>>10)
#define optype(op) ((op)&0xF)
#define roundup(x, n) (((x)+((n)-1))&(~((n)-1)))
#define sizeop(n) ((n)<<10)
#define specific(op) ((op)&0x3FF)
#define unqual(t) (isqual(t) ? (t)->type : (t))
#define xx(a, b, c, d, e, f, g) a=b,
#define yy(a, b, c, d, e, f, g)
Typedefs
typedef void(* Apply) (void *, void *, void *)
Enumerations
enum { LAST }
enum {
F =FLOAT, I =INT, U =UNSIGNED, P =POINTER,
V =VOID, B =STRUCT
}
enum { gop }
enum { CODE =1, BSS, DATA, LIT }
enum { PERM =0, FUNC, STMT }
enum {
CONSTANTS =1, LABELS, GLOBAL, PARAM,
LOCAL
}
enum {
AND =38<<4, NOT =39<<4, OR =40<<4, COND =41<<4,
RIGHT =42<<4, FIELD =43<<4
}
Functions
void addlocal (Symbol)
Tree addrof (Tree)
void * allocate (unsigned long n, unsigned a)
Symbol allsymbols (Table)
List append (void *x, List list)
void apply (List event, void *arg1, void *arg2)
Type array (Type, int, int)
Tree asgn (Symbol, Tree)
Tree asgntree (int, Tree, Tree)
Type assign (Type, Tree)
Type atop (Type)
void attach (Apply, void *, List *)
Type binary (Type, Type)
Tree bittree (int, Tree, Tree)
void branch (int)
Type btot (int, int)
Tree call (Tree, Type, Coordinate)
Tree calltree (Tree, Type, Tree, Symbol)
Tree cast (Tree, Type)
void check (Node)
void checklab (Symbol p, void *cl)
Tree cnsttree (Type,...)
Code code (int)
Type compose (Type, Type)
void compound (int, Swtch, int)
Tree cond (Tree)
Tree condtree (Tree, Tree, Tree)
Symbol constant (Type, Value)
Tree constexpr (int)
Tree consttree (unsigned int, Type)
Tree cvtconst (Tree)
void deallocate (unsigned a)
void defglobal (Symbol, int)
void definelab (int)
void definept (Coordinate *)
void defpointer (Symbol)
Type deref (Type)
void emitcode (void)
void enterscope (void)
Type enumdcl (void)
Tree eqtree (int, Tree, Tree)
int eqtype (Type, Type, int)
void equatelab (Symbol, Symbol)
void error (const char *,...)
void exitscope (void)
void expect (int tok)
Tree expr (int)
Tree expr0 (int)
Tree expr1 (int)
int fatal (const char *, const char *, int)
Tree field (Tree, const char *)
Field fieldlist (Type)
Field fieldref (const char *name, Type ty)
void fillbuf (void)
void finalize (void)
int findcount (char *, int, int)
int findfunc (char *, char *)
Symbol findlabel (int)
Symbol findtype (Type)
void foreach (Table, int, void(*)(Symbol, void *), void *)
void fprint (FILE *f, const char *fmt,...)
Type freturn (Type)
Type ftype (Type, Type)
Type func (Type, Type *, int)
char * funcname (Tree)
void gencode (Symbol[], Symbol[])
Symbol genident (int, Type, int)
int genlabel (int)
int getchr (void)
int gettok (void)
int hascall (Tree p)
int hasproto (Type)
Tree idtree (Symbol)
Tree incr (int, Tree, Tree)
void init (int, char *[])
Type initializer (Type, int)
void input_init (int, char *[])
Symbol install (const char *, Table *, int, int)
Symbol intconst (int)
int intexpr (int, int)
int iscallb (Tree)
int ispow2 (unsigned long u)
Node jump (int)
int length (List list)
Node listnodes (Tree e, int tlab, int flab)
void locus (Table tp, Coordinate *cp)
Symbol lookup (const char *, Table)
void * ltov (List *list, unsigned a)
Tree lvalue (Tree)
int main (int, char *[])
void main_init (int, char *[])
Symbol mkstr (char *)
Symbol mksymbol (int, const char *, Type)
void * newarray (unsigned long m, unsigned long n, unsigned a)
Field newfield (char *, Type, Type)
Node newnode (int op, Node left, Node right, Symbol p)
Type newstruct (int, char *)
Symbol newtemp (int, int, int)
void nextline (void)
int nodeid (Tree)
Tree nullcall (Type, Symbol, Tree, Tree)
char * opname (int)
void outtype (Type, FILE *)
Tree pointer (Tree)
void print (const char *,...)
void printdag (Node, int)
void printdecl (Symbol p, Type ty)
int * printed (int)
void printproto (Symbol p, Symbol args[])
void printtree (Tree, int)
void printtype (Type, int)
int process (char *)
void program (void)
Type promote (Type)
Type ptr (Type)
Type qual (int, Type)
int reachable (int)
Symbol relocate (const char *name, Table src, Table dst)
void retcode (Tree)
Tree retype (Tree p, Type ty)
Tree rightkid (Tree p)
void rmtypes (int)
Tree root (Tree)
Tree rvalue (Tree)
Tree shtree (int, Tree, Tree)
Type signedint (Type)
Tree simplify (int, Type, Tree, Tree)
void skipto (int tok, char set[])
void statement (int, Swtch, int)
char * string (const char *str)
char * stringd (long n)
char * stringf (const char *,...)
char * stringn (const char *str, int len)
void swcode (Swtch, int *, int, int)
void swgen (Swtch)
void swtoseg (int)
Table table (Table, int)
Symbol temporary (int, Type)
void test (int tok, char set[])
Tree texpr (Tree(*)(int), int, int)
Tree tree (int, Type, Tree, Tree)
int ttob (Type)
void type_init (int, char *[])
void typeerror (int, Tree, Tree)
Type typename (void)
char * typestring (Type ty, char *id)
void use (Symbol p, Coordinate src)
Tree value (Tree)
int variadic (Type)
Tree vcall (Symbol func, Type ty,...)
void vfprint (FILE *, char *, const char *, va_list)
char * vtoa (Type, Value)
void walk (Tree e, int tlab, int flab)
void warning (const char *,...)
Variables
int Aflag
int assignargs
Binding bindings []
Symbol cfunc
Type charptype
Type chartype
struct code codehead
Code codelist
Table constants
unsigned char * cp
float density
Type doubletype
int errcnt
int errlimit
Events events
int explicitCast
Table externals
char * file
char * firstfile
Type floattype
Type funcptype
int glevel
Table globals
Table identifiers
Type inttype
Interface * IR
char kind []
Table labels
int level
unsigned char * limit
char * line
Current line number.
int lineno
List loci
Type longdouble
Type longlong
Type longtype
int ncalled
int needconst
int nodecount
int npoints
Tree(* optree [])(int, Tree, Tree)
int Pflag
int prunetemps
float refinc
Symbol retv
Type shorttype
Type signedchar
Type signedptr
Coordinate src
Table stmtlabs
List symbols
int t
char * token
Symbol tsym
Table types
Type unsignedchar
Type unsignedlong
Type unsignedlonglong
Type unsignedptr
Type unsignedshort
Type unsignedtype
Type voidptype
Type voidtype
int wflag
int where
Type widechar
int xref
Symbol YYcheck
Symbol YYnull
Macro Definition Documentation
BUFSIZE
#define BUFSIZE 4096
Definition at line 14 of file c.h.
extend
#define extend (x, ty) ((x)&(1<<(8*(ty)->size-1)) ? (x)|((~0UL)<<(8*(ty)->size-1)) : (x)&ones(8*(ty)->size))
Definition at line 35 of file c.h.
fieldleft
#define fieldleft (p)
Value:
                        (8*(p)->type->size - \
                        fieldsize(p) - fieldright(p))
Definition at line 62 of file c.h.
fieldmask
#define fieldmask (p) (~(~(unsigned)0<<fieldsize(p)))
Definition at line 64 of file c.h.
fieldright
#define fieldright (p) ((p)->lsb - 1)
Definition at line 61 of file c.h.
fieldsize
#define fieldsize (p) (p)->bitsize
Definition at line 60 of file c.h.
generic
#define generic (op) ((op)&0x3F0)
Definition at line 19 of file c.h.
gop
#define gop (name, value) name=value<<4,
Definition at line 196 of file c.h.
isaddrop
#define isaddrop (op)
Value:
    (specific(op)==ADDRG+P || specific(op)==ADDRL+P \
    || specific(op)==ADDRF+P)
Definition at line 10 of file c.h.
isarith
#define isarith (t) (unqual(t)->op <= UNSIGNED)
Definition at line 55 of file c.h.
isarray
#define isarray (t) (unqual(t)->op == ARRAY)
Definition at line 45 of file c.h.
ischar
#define ischar (t) ((t)->size == 1 && isint(t))
Definition at line 51 of file c.h.
isconst
#define isconst (t)
Value:
                    ((t)->op == CONST \
                    || (t)->op == CONST+VOLATILE)
Definition at line 43 of file c.h.
isenum
#define isenum (t) (unqual(t)->op == ENUM)
Definition at line 59 of file c.h.
isfloat
#define isfloat (t) (unqual(t)->op == FLOAT)
Definition at line 54 of file c.h.
isfunc
#define isfunc (t) (unqual(t)->op == FUNCTION)
Definition at line 49 of file c.h.
isint
#define isint (t)
Value:
                    (unqual(t)->op == INT \
                    || unqual(t)->op == UNSIGNED)
Definition at line 52 of file c.h.
isptr
#define isptr (t) (unqual(t)->op == POINTER)
Definition at line 50 of file c.h.
isqual
#define isqual (t) ((t)->op >= CONST)
Definition at line 38 of file c.h.
isscalar
#define isscalar (t)
Value:
                    (unqual(t)->op <= POINTER \
                    || unqual(t)->op == ENUM)
Definition at line 57 of file c.h.
isstruct
#define isstruct (t)
Value:
                    (unqual(t)->op == STRUCT \
                    || unqual(t)->op == UNION)
Definition at line 46 of file c.h.
istypename
#define istypename (t, tsym)
Value:
    (kind[t] == CHAR \
    || (t == ID && tsym && tsym->sclass == TYPEDEF))
Definition at line 16 of file c.h.
isunion
#define isunion (t) (unqual(t)->op == UNION)
Definition at line 48 of file c.h.
isunsigned
#define isunsigned (t) (unqual(t)->op == UNSIGNED)
Definition at line 56 of file c.h.
isvolatile
#define isvolatile (t)
Value:
                    ((t)->op == VOLATILE \
                    || (t)->op == CONST+VOLATILE)
Definition at line 41 of file c.h.
MAXLINE
#define MAXLINE 512
Definition at line 13 of file c.h.
mkop
#define mkop (op, ty) (specific((op) + ttob(ty)))
Definition at line 33 of file c.h.
NELEMS
#define NELEMS (a) ((int)(sizeof (a)/sizeof ((a)[0])))
Definition at line 30 of file c.h.
NEW
#define NEW (p, a) ((p) = allocate(sizeof *(p), (a)))
Definition at line 8 of file c.h.
NEW0
#define NEW0 (p, a) memset(NEW((p),(a)), 0, sizeof *(p))
Definition at line 9 of file c.h.
ones
#define ones (n) ((n)>=8*sizeof (unsigned long) ? ~0UL : ~((~0UL)<<(n)))
Definition at line 36 of file c.h.
op
#define op (name, type, sizes)
Definition at line 197 of file c.h.
opindex
#define opindex (op) (((op)>>4)&0x3F)
Definition at line 21 of file c.h.
opkind
#define opkind (op) ((op)&~0x3F0)
Definition at line 22 of file c.h.
opsize
#define opsize (op) ((op)>>10)
Definition at line 23 of file c.h.
optype
#define optype (op) ((op)&0xF)
Definition at line 24 of file c.h.
roundup
#define roundup (x, n) (((x)+((n)-1))&(~((n)-1)))
Definition at line 32 of file c.h.
sizeop
#define sizeop (n) ((n)<<10)
Definition at line 18 of file c.h.
specific
#define specific (op) ((op)&0x3FF)
Definition at line 20 of file c.h.
unqual
#define unqual (t) (isqual(t) ? (t)->type : (t))
Definition at line 39 of file c.h.
xx
#define xx (a, b, c, d, e, f, g) a=b,
Definition at line 175 of file c.h.
yy
#define yy (a, b, c, d, e, f, g)
Definition at line 176 of file c.h.
Typedef Documentation
Apply
typedef void(* Apply) (void *, void *, void *)
Definition at line 590 of file c.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LAST
Definition at line 174 of file c.h.
      {
 #define xx(a,b,c,d,e,f,g) a=b,
 #define yy(a,b,c,d,e,f,g)
 #include "token.h"
     LAST
 };
anonymous enum
anonymous enum
Enumerator
F
I
U
P
V
B
Definition at line 188 of file c.h.
      {
     F=FLOAT,
     I=INT,
     U=UNSIGNED,
     P=POINTER,
     V=VOID,
     B=STRUCT
 };
anonymous enum
anonymous enum
Enumerator
gop
Definition at line 199 of file c.h.
      { gop(CNST,1)
         op(CNST,F,fdx)
         op(CNST,I,csilh)
         op(CNST,P,p)
         op(CNST,U,csilh)
        gop(ARG,2)
         op(ARG,B,-)
         op(ARG,F,fdx)
         op(ARG,I,ilh)
         op(ARG,P,p)
         op(ARG,U,ilh)
        gop(ASGN,3)
         op(ASGN,B,-)
         op(ASGN,F,fdx)
         op(ASGN,I,csilh)
         op(ASGN,P,p)
         op(ASGN,U,csilh)
        gop(INDIR,4)
         op(INDIR,B,-)
         op(INDIR,F,fdx)
         op(INDIR,I,csilh)
         op(INDIR,P,p)
         op(INDIR,U,csilh)
        gop(CVF,7)
         op(CVF,F,fdx)
         op(CVF,I,ilh)
        gop(CVI,8)
         op(CVI,F,fdx)
         op(CVI,I,csilh)
         op(CVI,U,csilhp)
        gop(CVP,9)
         op(CVP,U,p)
        gop(CVU,11)
         op(CVU,I,csilh)
         op(CVU,P,p)
         op(CVU,U,csilh)
        gop(NEG,12)
         op(NEG,F,fdx)
         op(NEG,I,ilh)
        gop(CALL,13)
         op(CALL,B,-)
         op(CALL,F,fdx)
         op(CALL,I,ilh)
         op(CALL,P,p)
         op(CALL,U,ilh)
         op(CALL,V,-)
        gop(RET,15)
         op(RET,F,fdx)
         op(RET,I,ilh)
         op(RET,P,p)
         op(RET,U,ilh)
         op(RET,V,-)
        gop(ADDRG,16)
         op(ADDRG,P,p)
        gop(ADDRF,17)
         op(ADDRF,P,p)
        gop(ADDRL,18)
         op(ADDRL,P,p)
        gop(ADD,19)
         op(ADD,F,fdx)
         op(ADD,I,ilh)
         op(ADD,P,p)
         op(ADD,U,ilhp)
        gop(SUB,20)
         op(SUB,F,fdx)
         op(SUB,I,ilh)
         op(SUB,P,p)
         op(SUB,U,ilhp)
        gop(LSH,21)
         op(LSH,I,ilh)
         op(LSH,U,ilh)
        gop(MOD,22)
         op(MOD,I,ilh)
         op(MOD,U,ilh)
        gop(RSH,23)
         op(RSH,I,ilh)
         op(RSH,U,ilh)
        gop(BAND,24)
         op(BAND,I,ilh)
         op(BAND,U,ilh)
        gop(BCOM,25)
         op(BCOM,I,ilh)
         op(BCOM,U,ilh)
        gop(BOR,26)
         op(BOR,I,ilh)
         op(BOR,U,ilh)
        gop(BXOR,27)
         op(BXOR,I,ilh)
         op(BXOR,U,ilh)
        gop(DIV,28)
         op(DIV,F,fdx)
         op(DIV,I,ilh)
         op(DIV,U,ilh)
        gop(MUL,29)
         op(MUL,F,fdx)
         op(MUL,I,ilh)
         op(MUL,U,ilh)
        gop(EQ,30)
         op(EQ,F,fdx)
         op(EQ,I,ilh)
         op(EQ,U,ilhp)
        gop(GE,31)
         op(GE,F,fdx)
         op(GE,I,ilh)
         op(GE,U,ilhp)
        gop(GT,32)
         op(GT,F,fdx)
         op(GT,I,ilh)
         op(GT,U,ilhp)
        gop(LE,33)
         op(LE,F,fdx)
         op(LE,I,ilh)
         op(LE,U,ilhp)
        gop(LT,34)
         op(LT,F,fdx)
         op(LT,I,ilh)
         op(LT,U,ilhp)
        gop(NE,35)
         op(NE,F,fdx)
         op(NE,I,ilh)
         op(NE,U,ilhp)
        gop(JUMP,36)
         op(JUMP,V,-)
        gop(LABEL,37)
         op(LABEL,V,-)
        gop(LOAD,14)
         op(LOAD,B,-)
         op(LOAD,F,fdx)
         op(LOAD,I,csilh)
         op(LOAD,P,p)
         op(LOAD,U,csilhp) LASTOP };
anonymous enum
anonymous enum
Enumerator
CODE
BSS
DATA
LIT
Definition at line 333 of file c.h.
 { CODE=1, BSS, DATA, LIT };
anonymous enum
anonymous enum
Enumerator
PERM
FUNC
STMT
Definition at line 334 of file c.h.
 { PERM=0, FUNC, STMT };
anonymous enum
anonymous enum
Enumerator
CONSTANTS
LABELS
GLOBAL
PARAM
LOCAL
Definition at line 437 of file c.h.
 { CONSTANTS=1, LABELS, GLOBAL, PARAM, LOCAL };
anonymous enum
anonymous enum
Enumerator
AND
NOT
OR
COND
RIGHT
FIELD
Definition at line 450 of file c.h.
      {
     AND=38<<4,
     NOT=39<<4,
     OR=40<<4,
     COND=41<<4,
     RIGHT=42<<4,
     FIELD=43<<4
 };
Function Documentation
addlocal()
void addlocal (Symbol)
Definition at line 50 of file stmt.c.
{
     if (!p->defined) {
         code(Local)->u.var = p;
         p->defined = 1;
         p->scope = level;
     }
 }
References code(), and Code::Local.
Referenced by addrtree(), listnodes(), primary(), retcode(), swstmt(), tracecall(), and undag().
addrof()
Tree addrof (Tree)
Definition at line 389 of file enode.c.
                     {
     Tree q = p;
     for (;;)
         switch (generic(q->op)) {
         case RIGHT:
             assert(q->kids[0] || q->kids[1]);
             q = q->kids[1] ? q->kids[1] : q->kids[0];
             continue;
         case ASGN:
             q = q->kids[1];
             continue;
         case COND: {
             Symbol t1 = q->u.sym;
             q->u.sym = 0;
             q = idtree(t1);
             /* fall thru */
             }
         case INDIR:
             if (p == q)
                 return q->kids[0];
             q = q->kids[0];
             return tree(RIGHT, q->type, root(p), q);
         default:
             error("addressable object required\n");
             return value(p);
         }
 }
References ASGN, assert, COND, error(), idtree(), RIGHT, root(), and tree().
Referenced by call(), calltree(), postfix(), and tracevalue().
allocate()
void* allocate (unsigned long n, unsigned a)
Definition at line 53 of file alloc.c.
{
     struct block *ap;
     assert(a < NELEMS(arena));
     assert(n > 0);
     ap = arena[a];
     n = roundup(n, sizeof (union align));
     while (n > ap->limit - ap->avail) {
         if ((ap->next = freeblocks) != NULL) {
             freeblocks = freeblocks->next;
             ap = ap->next;
         } else
             {
                 unsigned m = sizeof (union header) + n + roundup(10*1024, sizeof (union align));
                 ap->next = malloc(m);
                 ap = ap->next;
                 if (ap == NULL) {
                     error("insufficient memory\n");
                     exit(1);
                 }
                 ap->limit = (char *)ap + m;
             }
         ap->avail = (char *)((union header *)ap + 1);
         ap->next = NULL;
         arena[a] = ap;
     }
     ap->avail += n;
     return ap->avail - n;
 }
References arena, assert, block::avail, error(), exit(), freeblocks, block::limit, m, malloc(), NELEMS, block::next, NULL, and roundup.
Referenced by _GLIBCXX_VISIBILITY(), appendstr(), newarray(), primary(), prof_init(), and stringn().
allsymbols()
Symbol allsymbols (Table)
Definition at line 235 of file sym.c.
{
     return tp->all;
 }
Referenced by locus().
append()
List append (void * x, List list)
Definition at line 7 of file list.c.
{
     List new;
     if ((new = freenodes) != NULL)
         freenodes = freenodes->link;
     else
         NEW(new, PERM);
     if (list) {
         new->link = list->link;
         list->link = new;
     } else
         new->link = new;
     new->x = x;
     return new;
 }
References freenodes, List::link, NEW, NULL, and PERM.
apply()
void apply (List event, void * arg1, void * arg2)
Definition at line 18 of file event.c.
{
     if (event) {
         List lp = event;
         do {
             struct entry *p = lp->x;
             (*p->func)(p->cl, arg1, arg2);
             lp = lp->link;
         } while (lp != event);
     }
 }
References entry::link.
Referenced by _GLIBCXX_VISIBILITY(), call(), compound(), definept(), expr2(), expr3(), funcdefn(), main(), and retcode().
array()
Type array (Type , int , int)
Definition at line 202 of file types.c.
{
     assert(ty);
     if (isfunc(ty)) {
         error("illegal type `array of %t'\n", ty);
         return array(inttype, n, 0);
     }
     if (isarray(ty) && ty->size == 0)
         error("missing array size\n");
     if (ty->size == 0) {
         if (unqual(ty) == voidtype)
             error("illegal type `array of %t'\n", ty);
         else if (Aflag >= 2)
             warning("declaring type array of %t' is undefined\n", ty);
     } else if (n > INT_MAX/ty->size) {
         error("size of `array of %t' exceeds %d bytes\n",
             ty, INT_MAX);
         n = 1;
     }
     return type(ARRAY, ty, n*ty->size,
         a ? a : ty->align, NULL);
 }
References Aflag, assert, error(), INT_MAX, inttype, isarray, isfunc, NULL, type(), unqual, voidtype, and warning().
Referenced by bbcall(), bbentry(), bbvars(), compose(), dcllocal(), dclr(), doglobal(), field(), gettok(), initializer(), ltov(), mkstr(), prof_init(), and swcode().
asgn()
Tree asgn (Symbol , Tree)
Definition at line 426 of file enode.c.
{
     if (isarray(p->type))
         e = tree(ASGN+B, p->type, idtree(p),
             tree(INDIR+B, e->type, e, NULL));
     else {
         Type ty = p->type;
         p->type = unqual(p->type);
         if (isstruct(p->type) && p->type->u.sym->u.s.cfields) {
             p->type->u.sym->u.s.cfields = 0;
             e = asgntree(ASGN, idtree(p), e);
             p->type->u.sym->u.s.cfields = 1;
         } else
             e = asgntree(ASGN, idtree(p), e);
         p->type = ty;
     }
     return e;
 }
References ASGN, asgntree(), B, idtree(), isarray, isstruct, NULL, tree(), and unqual.
Referenced by bbcall(), call(), condtree(), dcllocal(), gencode(), nullcheck(), retcode(), swstmt(), and tracecall().
asgntree()
Tree asgntree (int , Tree , Tree)
Definition at line 287 of file enode.c.
{
     Type aty, ty;
     r = pointer(r);
     ty = assign(l->type, r);
     if (ty)
         r = cast(r, ty);
     else {
         typeerror(ASGN, l, r);
         if (r->type == voidtype)
             r = retype(r, inttype);
         ty = r->type;
     }
     if (l->op != FIELD)
         l = lvalue(l);
     aty = l->type;
     if (isptr(aty))
         aty = unqual(aty)->type;
     if ( isconst(aty)
     ||  (isstruct(aty) && unqual(aty)->u.sym->u.s.cfields)) {
         if (isaddrop(l->op)
         && !l->u.sym->computed && !l->u.sym->generated)
             error("assignment to const identifier `%s'\n",
                 l->u.sym->name);
         else
             error("assignment to const location\n");
     }
     if (l->op == FIELD) {
         long n = 8*l->u.field->type->size - fieldsize(l->u.field);
         if (n > 0 && isunsigned(l->u.field->type))
             r = bittree(BAND, r,
                 cnsttree(r->type, (unsigned long)fieldmask(l->u.field)));
         else if (n > 0) {
             if (r->op == CNST+I) {
                 n = r->u.v.i;
                 if (n&(1<<(fieldsize(l->u.field)-1)))
                     n |= ~0UL<<fieldsize(l->u.field);
                 r = cnsttree(r->type, n);
             } else
                 r = shtree(RSH,
                     shtree(LSH, r, cnsttree(inttype, n)),
                     cnsttree(inttype, n));
         }
     }
     if (isstruct(ty) && isaddrop(l->op) && iscallb(r))
         return tree(RIGHT, ty,
             tree(CALL+B, ty, r->kids[0]->kids[0], l),
             idtree(l->u.sym));
     return tree(mkop(op,ty), ty, l, r);
 }
References ASGN, assign(), B, bittree(), CALL, cast(), cnsttree(), error(), FIELD, fieldmask, fieldsize, I, idtree(), inttype, isaddrop, iscallb(), isconst, isptr, isstruct, isunsigned, Symbol::l, LSH, lvalue(), mkop, op, retype(), RIGHT, RSH, shtree(), tree(), typeerror(), Symbol::u, unqual, and voidtype.
Referenced by asgn().
assign()
Type assign (Type , Tree)
Definition at line 249 of file enode.c.
{
     Type yty = unqual(e->type);
     xty = unqual(xty);
     if (isenum(xty))
         xty = xty->type;
     if (xty->size == 0 || yty->size == 0)
         return NULL;
     if ( (isarith(xty) && isarith(yty))
     ||  (isstruct(xty) && xty == yty))
         return xty;
     if (isptr(xty) && isnullptr(e))
         return xty;
     if (((isvoidptr(xty) && isptr(yty))
       || (isptr(xty)     && isvoidptr(yty)))
     && (  (isconst(xty->type)    || !isconst(yty->type))
        && (isvolatile(xty->type) || !isvolatile(yty->type))))
         return xty;
     if ((isptr(xty) && isptr(yty)
         && eqtype(unqual(xty->type), unqual(yty->type), 1))
     &&  (  (isconst(xty->type)    || !isconst(yty->type))
         && (isvolatile(xty->type) || !isvolatile(yty->type))))
         return xty;
     if (isptr(xty) && isptr(yty)
     && (  (isconst(xty->type)    || !isconst(yty->type))
        && (isvolatile(xty->type) || !isvolatile(yty->type)))) {
         Type lty = unqual(xty->type), rty = unqual(yty->type);
         if ((isenum(lty) && rty == inttype)
         ||  (isenum(rty) && lty == inttype)) {
             if (Aflag >= 1)
                 warning("assignment between `%t' and `%t' is compiler-dependent\n",
                     xty, yty);
             return xty;
         }
     }
     return NULL;
 }
References Aflag, eqtype(), inttype, isarith, isconst, isenum, isnullptr(), isptr, isstruct, isvoidptr, isvolatile, NULL, unqual, and warning().
Referenced by _GLIBCXX_VISIBILITY(), asgntree(), call(), initializer(), initvalue(), and retcode().
atop()
Type atop (Type)
Definition at line 224 of file types.c.
                    {
     if (isarray(ty))
         return ptr(ty->type);
     error("type error: %s\n", "array expected");
     return ptr(ty);
 }
References error(), isarray, and ptr().
Referenced by consttree(), cvtconst(), dclparam(), nullcall(), and pointer().
attach()
void attach (Apply , void * , List *)
Definition at line 10 of file event.c.
{
     struct entry *p;
     NEW(p, PERM);
     p->func = func;
     p->cl = cl;
     *list = append(p, *list);
 }
References append(), cl, func(), NEW, and PERM.
Referenced by prof_init(), and trace_init().
binary()
Type binary (Type , Type)
Definition at line 493 of file expr.c.
{
 #define xx(t) if (xty == t || yty == t) return t
     xx(longdouble);
     xx(doubletype);
     xx(floattype);
     xx(unsignedlonglong);
     xx(longlong);
     xx(unsignedlong);
     if ((xty == longtype     && yty == unsignedtype)
     ||  (xty == unsignedtype && yty == longtype)) {
         if (longtype->size > unsignedtype->size)
             return longtype;
         else
             return unsignedlong;
     }
     xx(longtype);
     xx(unsignedtype);
     return inttype;
 #undef xx
 }
References doubletype, floattype, inttype, longdouble, longlong, longtype, unsignedlong, unsignedlonglong, unsignedtype, and xx.
Referenced by _GLIBCXX_VISIBILITY(), addtree(), bittree(), cmptree(), condtree(), multree(), and subtree().
bittree()
Tree bittree (int , Tree , Tree)
Definition at line 445 of file enode.c.
{
     Type ty = inttype;
     if (isint(l->type) && isint(r->type)) {
         ty = binary(l->type, r->type);
         l = cast(l, ty);
         r = cast(r, ty);
     } else
         typeerror(op, l, r);
     return simplify(op, ty, l, r);
 }
References binary(), cast(), inttype, isint, Symbol::l, op, simplify(), and typeerror().
Referenced by asgntree().
branch()
void branch (int)
Definition at line 564 of file stmt.c.
                      {
     Code cp;
     Symbol p = findlabel(lab);
     assert(lab);
     walk(NULL, 0, 0);
     code(Label)->u.forest = jump(lab);
     for (cp = codelist->prev; cp->kind < Label; )
         cp = cp->prev;
     while (   cp->kind == Label
            && cp->u.forest->op == LABEL+V
            && !equal(cp->u.forest->syms[0], p)) {
         equatelab(cp->u.forest->syms[0], p);
         assert(cp->next);
         assert(cp->prev);
         cp->prev->next = cp->next;
         cp->next->prev = cp->prev;
         cp = cp->prev;
         while (cp->kind < Label)
             cp = cp->prev;
     }
     if (cp->kind == Jump || cp->kind == Switch) {
         p->ref--;
         codelist->prev->next = NULL;
         codelist = codelist->prev;
     } else {
         codelist->kind = Jump;
         if (cp->kind == Label
         &&  cp->u.forest->op == LABEL+V
         &&  equal(cp->u.forest->syms[0], p))
             warning("source code specifies an infinite loop");
     }
 }
References assert, code(), codelist, cp, equal(), equatelab(), findlabel(), jump(), Swtch::lab, NULL, V, walk(), and warning().
Referenced by forstmt(), ifstmt(), statement(), swcode(), swstmt(), and whilestmt().
btot()
Type btot (int , int)
Definition at line 447 of file types.c.
{
 #define xx(ty) if (size == (ty)->size) return ty;
     switch (optype(op)) {
     case F:
         xx(floattype);
         xx(doubletype);
         xx(longdouble);
         assert(0); return 0;
     case I:
         if (chartype->op == INT)
             xx(chartype);
         xx(signedchar);
         xx(shorttype);
         xx(inttype);
         xx(longtype);
         xx(longlong);
         assert(0); return 0;
     case U:
         if (chartype->op == UNSIGNED)
             xx(chartype);
         xx(unsignedchar);
         xx(unsignedshort);
         xx(unsignedtype);
         xx(unsignedlong);
         xx(unsignedlonglong);
         assert(0); return 0;
     case P:
         xx(voidptype);
         xx(funcptype);
         assert(0); return 0;
     }
 #undef xx
     assert(0); return 0;
 }
References assert, chartype, doubletype, F, floattype, funcptype, I, inttype, longdouble, longlong, longtype, op, optype, P, shorttype, signedchar, U, unsignedchar, unsignedlong, unsignedlonglong, unsignedshort, unsignedtype, voidptype, and xx.
Referenced by newtemp(), and visit().
call()
Tree call (Tree , Type , Coordinate)
Definition at line 19 of file enode.c.
{
     int n = 0;
     Tree args = NULL, r = NULL, e;
     Type *proto, rty = unqual(freturn(fty));
     Symbol t3 = NULL;
     if (fty->u.f.oldstyle)
         proto = NULL;
     else
         proto = fty->u.f.proto;
     if (hascall(f))
         r = f;
     if (isstruct(rty))
         {
             t3 = temporary(AUTO, unqual(rty));
             if (rty->size == 0)
                 error("illegal use of incomplete type `%t'\n", rty);
         }
     if (t != ')')
         for (;;) {
             Tree q = pointer(expr1(0));
             if (proto && *proto && *proto != voidtype)
                 {
                     Type aty;
                     q = value(q);
                     aty = assign(*proto, q);
                     if (aty)
                         q = cast(q, aty);
                     else
                         error("type error in argument %d to %s; found `%t' expected `%t'\n", n + 1, funcname(f),
                             q->type, *proto);
                     if ((isint(q->type) || isenum(q->type))
                     && q->type->size != inttype->size)
                         q = cast(q, promote(q->type));
                     ++proto;
                 }
             else
                 {
                     if (!fty->u.f.oldstyle && *proto == NULL)
                         error("too many arguments to %s\n", funcname(f));
                     q = value(q);
                     if (isarray(q->type) || q->type->size == 0)
                         error("type error in argument %d to %s; `%t' is illegal\n", n + 1, funcname(f), q->type);
                     else
                         q = cast(q, promote(q->type));
                 }
             if (!IR->wants_argb && isstruct(q->type)) {
                 if (iscallb(q))
                     q = addrof(q);
                 else {
                     Symbol t1 = temporary(AUTO, unqual(q->type));
                     q = asgn(t1, q);
                     q = tree(RIGHT, ptr(t1->type),
                         root(q), lvalue(idtree(t1)));
                 }
             }
             if (q->type->size == 0)
                 q->type = inttype;
             if (hascall(q))
                 r = r ? tree(RIGHT, voidtype, r, q) : q;
             args = tree(mkop(ARG, q->type), q->type, q, args);
             n++;
             if (Aflag >= 2 && n == 32)
                 warning("more than 31 arguments in a call to %s\n",
                     funcname(f));
             if (t != ',')
                 break;
             t = gettok();
         }
     expect(')');
     if (proto && *proto && *proto != voidtype)
         error("insufficient number of arguments to %s\n",
             funcname(f));
     if (r)
         args = tree(RIGHT, voidtype, r, args);
     e = calltree(f, rty, args, t3);
     if (events.calls)
         apply(events.calls, &src, &e);
     return e;
 }
References addrof(), Aflag, apply(), args, asgn(), assign(), Events::calls, calltree(), cast(), error(), events, expect(), expr1(), Symbol::f, freturn(), funcname(), gettok(), hascall(), idtree(), inttype, IR, isarray, iscallb(), isenum, isint, isstruct, lvalue(), mkop, NULL, promote(), ptr(), RIGHT, root(), temporary(), tree(), unqual, voidtype, and warning().
Referenced by asmcall(), postfix(), and VM_CallCompiled().
calltree()
Tree calltree (Tree , Type , Tree , Symbol)
Definition at line 101 of file enode.c.
{
     Tree p;
     if (args)
         f = tree(RIGHT, f->type, args, f);
     if (isstruct(ty))
         assert(t3),
         p = tree(RIGHT, ty,
             tree(CALL+B, ty, f, addrof(idtree(t3))),
             idtree(t3));
     else {
         Type rty = ty;
         if (isenum(ty))
             rty = unqual(ty)->type;
         if (!isfloat(rty))
             rty = promote(rty);
         p = tree(mkop(CALL, rty), rty, f, NULL);
         if (isptr(ty) || p->type->size > ty->size)
             p = cast(p, ty);
     }
     return p;
 }
References addrof(), args, assert, B, CALL, cast(), Symbol::f, idtree(), isenum, isfloat, isptr, isstruct, mkop, NULL, promote(), RIGHT, tree(), and unqual.
Referenced by call(), tracefinis(), and vcall().
cast()
Tree cast (Tree , Type)
Definition at line 531 of file expr.c.
{
     Type src, dst;
     p = value(p);
     if (p->type == type)
         return p;
     dst = unqual(type);
     src = unqual(p->type);
     if (src->op != dst->op || src->size != dst->size) {
         switch (src->op) {
         case INT:
             if (src->size < inttype->size)
                 p = simplify(CVI, inttype, p, NULL);
             break;
         case UNSIGNED:
             if (src->size < inttype->size)
                 p = simplify(CVU, inttype, p, NULL);
             else if (src->size < unsignedtype->size)
                 p = simplify(CVU, unsignedtype, p, NULL);
             break;
         case ENUM:
             p = retype(p, inttype);
             break;
         case POINTER:
             if (isint(dst) && src->size > dst->size)
                 warning("conversion from `%t' to `%t' is undefined\n", p->type, type);
             p = simplify(CVP, super(src), p, NULL);
             break;
         case FLOAT:
             break;
         default: assert(0);
         }
         {
             src = unqual(p->type);
             dst = super(dst);
             if (src->op != dst->op)
                 switch (src->op) {
                 case INT:
                     p = simplify(CVI, dst, p, NULL);
                     break;
                 case UNSIGNED:
                     if (isfloat(dst)) {
                         Type ssrc = signedint(src);
                         Tree two = cnsttree(longdouble, (double)2.0);
                         p = (*optree['+'])(ADD,
                             (*optree['*'])(MUL,
                                 two,
                                 simplify(CVU, ssrc,
                                     simplify(RSH, src,
                                         p, consttree(1, inttype)), NULL)),
                             simplify(CVU, ssrc,
                                 simplify(BAND, src,
                                     p, consttree(1, unsignedtype)), NULL));
                     } else
                         p = simplify(CVU, dst, p, NULL);
                     break;
                 case FLOAT:
                     if (isunsigned(dst)) {
                         Type sdst = signedint(dst);
                         Tree c = cast(cnsttree(longdouble, (double)sdst->u.sym->u.limits.max.i + 1), src);
                         p = condtree(
                             simplify(GE, src, p, c),
                             (*optree['+'])(ADD,
                                 cast(cast(simplify(SUB, src, p, c), sdst), dst),
                                 cast(cnsttree(unsignedlong, (unsigned long)sdst->u.sym->u.limits.max.i + 1), dst)),
                             simplify(CVF, sdst, p, NULL));
                     } else
                         p = simplify(CVF, dst, p, NULL);
                     break;
                 default: assert(0);
                 }
             dst = unqual(type);
         }
     }
     src = unqual(p->type);
     switch (src->op) {
     case INT:
         if (src->op != dst->op || src->size != dst->size)
             p = simplify(CVI, dst, p, NULL);
         break;
     case UNSIGNED:
         if (src->op != dst->op || src->size != dst->size)
             p = simplify(CVU, dst, p, NULL);
         break;
     case FLOAT:
         if (src->op != dst->op || src->size != dst->size)
             p = simplify(CVF, dst, p, NULL);
         break;
     case POINTER:
         if (src->op != dst->op)
             p = simplify(CVP, dst, p, NULL);
         else {
             if ((isfunc(src->type) && !isfunc(dst->type))
             || (!isfunc(src->type) &&  isfunc(dst->type)))
                 warning("conversion from `%t' to `%t' is compiler dependent\n", p->type, type);
             if (src->size != dst->size)
                 p = simplify(CVP, dst, p, NULL);
         }
         break;
     default: assert(0);
     }
     return retype(p, type);
 }
References ADD, assert, cnsttree(), condtree(), consttree(), INT, inttype, isfloat, isfunc, isint, isunsigned, longdouble, NULL, optree, retype(), RSH, signedint(), simplify(), SUB, super(), unqual, unsignedlong, unsignedtype, value(), and warning().
Referenced by addtree(), asgntree(), bittree(), call(), calltree(), cmp(), cmptree(), condtree(), eqtree(), initializer(), initvalue(), intexpr(), listnodes(), multree(), nullcheck(), retcode(), shtree(), simplify(), statement(), subtree(), swcode(), swstmt(), tracevalue(), and unary().
check()
void check (Node)
Referenced by CheckParm(), G_CheckProxMinePosition(), G_MoverPush(), G_TryPushingEntity(), G_TryPushingProxMine(), gen(), PM_CheckPowerLevel(), SV_AreaEntities_r(), and Svcmd_EntityList_f().
checklab()
void checklab (Symbol p, void * cl)
Definition at line 1073 of file decl.c.
{
     if (!p->defined)
         error("undefined label `%s'\n", p->name);
     p->defined = 1;
 }
References error().
Referenced by funcdefn().
cnsttree()
Tree cnsttree (Type , ...)
Definition at line 179 of file enode.c.
{
     Tree p = tree(mkop(CNST,ty), ty, NULL, NULL);
     va_list ap;
     va_start(ap, ty);
     switch (ty->op) {
     case INT:     p->u.v.i = va_arg(ap, long); break;
     case UNSIGNED:p->u.v.u = va_arg(ap, unsigned long)&ones(8*ty->size); break;
     case FLOAT:   p->u.v.d = va_arg(ap, double); break;
     case POINTER: p->u.v.p = va_arg(ap, void *); break;
     default: assert(0);
     }
     va_end(ap);
     return p;
 }
References assert, INT, mkop, NULL, ones, tree(), va_arg, va_end, and va_start.
Referenced by addtree(), asgntree(), cast(), cmp(), consttree(), funcdefn(), listnodes(), nullcall(), nullcheck(), primary(), simplify(), subtree(), swcode(), and unary().
code()
Code code (int)
Definition at line 25 of file stmt.c.
                     {
     Code cp;
     if (!reachable(kind))
         warning("unreachable code\n");
     NEW(cp, FUNC);
     cp->kind = kind;
     cp->prev = codelist;
     cp->next = NULL;
     codelist->next = cp;
     codelist = cp;
     return cp;
 }
References codelist, cp, FUNC, kind, NEW, NULL, reachable(), and warning().
Referenced by addlocal(), branch(), definelab(), definept(), swcode(), and swstmt().
compose()
Type compose (Type , Type)
Definition at line 390 of file types.c.
{
     if (ty1 == ty2)
         return ty1;
     assert(ty1->op == ty2->op);
     switch (ty1->op) {
     case POINTER:
         return ptr(compose(ty1->type, ty2->type));
     case CONST+VOLATILE:
         return qual(CONST, qual(VOLATILE,
             compose(ty1->type, ty2->type)));
     case CONST: case VOLATILE:
         return qual(ty1->op, compose(ty1->type, ty2->type));
     case ARRAY:    { Type ty = compose(ty1->type, ty2->type);
              if (ty1->size && ((ty1->type->size && ty2->size == 0) || ty1->size == ty2->size))
                 return array(ty, ty1->size/ty1->type->size, ty1->align);
              if (ty2->size && ty2->type->size && ty1->size == 0)
                 return array(ty, ty2->size/ty2->type->size, ty2->align);
              return array(ty, 0, 0);    }
     case FUNCTION: { Type *p1  = ty1->u.f.proto, *p2 = ty2->u.f.proto;
              Type ty   = compose(ty1->type, ty2->type);
              List tlist = NULL;
              if (p1 == NULL && p2 == NULL)
                 return func(ty, NULL, 1);
              if (p1 && p2 == NULL)
                 return func(ty, p1, ty1->u.f.oldstyle);
              if (p2 && p1 == NULL)
                 return func(ty, p2, ty2->u.f.oldstyle);
              for ( ; *p1 && *p2; p1++, p2++) {
                 Type ty = compose(unqual(*p1), unqual(*p2));
                 if (isconst(*p1)    || isconst(*p2))
                     ty = qual(CONST, ty);
                 if (isvolatile(*p1) || isvolatile(*p2))
                     ty = qual(VOLATILE, ty);
                 tlist = append(ty, tlist);
              }
              assert(*p1 == NULL && *p2 == NULL);
              return func(ty, ltov(&tlist, PERM), 0); }
     }
     assert(0); return NULL;
 }
References append(), array(), assert, CONST, func(), isconst, isvolatile, ltov(), NULL, p1, p2, PERM, ptr(), qual(), unqual, and VOLATILE.
compound()
void compound (int , Swtch , int)
Referenced by statement().
cond()
Tree cond (Tree)
Definition at line 521 of file expr.c.
                   {
     int op = generic(rightkid(p)->op);
     if (op == AND || op == OR || op == NOT
     ||  op == EQ  || op == NE
     ||  op == LE  || op == LT || op == GE || op == GT)
         return p;
     p = pointer(p);
     return (*optree[NEQ])(NE, p, consttree(0, inttype));
 }
References AND, consttree(), EQ, GT, inttype, LT, NEQ, NOT, op, optree, OR, pointer(), and rightkid().
Referenced by addd(), addi(), andtree(), conditional(), condtree(), divd(), divi(), muld(), muli(), nullcheck(), simplify(), and unary().
condtree()
Tree condtree (Tree , Tree , Tree)
Definition at line 337 of file enode.c.
{
     Symbol t1;
     Type ty, xty = l->type, yty = r->type;
     Tree p;
     if (isarith(xty) && isarith(yty))
         ty = binary(xty, yty);
     else if (eqtype(xty, yty, 1))
         ty = unqual(xty);
     else if (isptr(xty)   && isnullptr(r))
         ty = xty;
     else if (isnullptr(l) && isptr(yty))
         ty = yty;
     else if ((isptr(xty) && !isfunc(xty->type) && isvoidptr(yty))
     ||       (isptr(yty) && !isfunc(yty->type) && isvoidptr(xty)))
         ty = voidptype;
     else if ((isptr(xty) && isptr(yty)
          && eqtype(unqual(xty->type), unqual(yty->type), 1)))
         ty = xty;
     else {
         typeerror(COND, l, r);
         return consttree(0, inttype);
     }
     if (isptr(ty)) {
         ty = unqual(unqual(ty)->type);
         if ((isptr(xty) && isconst(unqual(xty)->type))
         ||  (isptr(yty) && isconst(unqual(yty)->type)))
             ty = qual(CONST, ty);
         if ((isptr(xty) && isvolatile(unqual(xty)->type))
         ||  (isptr(yty) && isvolatile(unqual(yty)->type)))
             ty = qual(VOLATILE, ty);
         ty = ptr(ty);
     }
     switch (e->op) {
     case CNST+I: return cast(e->u.v.i != 0   ? l : r, ty);
     case CNST+U: return cast(e->u.v.u != 0   ? l : r, ty);
     case CNST+P: return cast(e->u.v.p != 0   ? l : r, ty);
     case CNST+F: return cast(e->u.v.d != 0.0 ? l : r, ty);
     }
     if (ty != voidtype && ty->size > 0) {
         t1 = genident(REGISTER, unqual(ty), level);
     /*  t1 = temporary(REGISTER, unqual(ty)); */
         l = asgn(t1, l);
         r = asgn(t1, r);
     } else
         t1 = NULL;
     p = tree(COND, ty, cond(e),
         tree(RIGHT, ty, root(l), root(r)));
     p->u.sym = t1;
     return p;
 }
References asgn(), binary(), cast(), COND, cond(), CONST, consttree(), eqtype(), F, genident(), I, inttype, isarith, isconst, isfunc, isnullptr(), isptr, isvoidptr, isvolatile, Symbol::l, NULL, P, ptr(), qual(), RIGHT, root(), tree(), typeerror(), U, unqual, voidptype, voidtype, and VOLATILE.
Referenced by cast(), expr2(), tracevalue(), and value().
constant()
Symbol constant (Type , Value)
Definition at line 164 of file sym.c.
{
     struct entry *p;
     unsigned h = v.u&(HASHSIZE-1);
     ty = unqual(ty);
     for (p = constants->buckets[h]; p; p = p->link)
         if (eqtype(ty, p->sym.type, 1))
             switch (ty->op) {
             case INT:      if (equalp(i)) return &p->sym; break;
             case UNSIGNED: if (equalp(u)) return &p->sym; break;
             case FLOAT:    if (equalp(d)) return &p->sym; break;
             case FUNCTION: if (equalp(g)) return &p->sym; break;
             case ARRAY:
             case POINTER:  if (equalp(p)) return &p->sym; break;
             default: assert(0);
             }
     NEW0(p, PERM);
     p->sym.name = vtoa(ty, v);
     p->sym.scope = CONSTANTS;
     p->sym.type = ty;
     p->sym.sclass = STATIC;
     p->sym.u.c.v = v;
     p->link = constants->buckets[h];
     p->sym.up = constants->all;
     constants->all = &p->sym;
     constants->buckets[h] = p;
     if (ty->u.sym && !ty->u.sym->addressed)
         (*IR->defsymbol)(&p->sym);
     p->sym.defined = 1;
     return &p->sym;
 }
References assert, constants, CONSTANTS, eqtype(), equalp, HASHSIZE, INT, IR, NEW0, PERM, STATIC, unqual, and vtoa().
Referenced by cvtconst(), intconst(), listnodes(), mkstr(), and primary().
constexpr()
Tree constexpr (int)
Definition at line 185 of file simp.c.
{
     Tree p;
     needconst++;
     p = expr1(tok);
     needconst--;
     return p;
 }
References expr1(), and needconst.
Referenced by _GLIBCXX_VISIBILITY(), intexpr(), and statement().
consttree()
Tree consttree (unsigned int , Type)
Referenced by bbincr(), cast(), cond(), field(), genconst(), initvalue(), postfix(), primary(), tracecall(), tracevalue(), unary(), and value().
cvtconst()
Tree cvtconst (Tree)
Definition at line 405 of file dag.c.
                       {
     Symbol q = constant(p->type, p->u.v);
     Tree e;
     if (q->u.c.loc == NULL)
         q->u.c.loc = genident(STATIC, p->type, GLOBAL);
     if (isarray(p->type)) {
         e = simplify(ADDRG, atop(p->type), NULL, NULL);
         e->u.sym = q->u.c.loc;
     } else
         e = idtree(q->u.c.loc);
     return e;
 }
References atop(), constant(), genident(), GLOBAL, idtree(), isarray, NULL, simplify(), and STATIC.
Referenced by genconst(), and listnodes().
deallocate()
void deallocate (unsigned a)
Definition at line 87 of file alloc.c.
{
     assert(a < NELEMS(arena));
     arena[a]->next = freeblocks;
     freeblocks = first[a].next;
     first[a].next = NULL;
     arena[a] = &first[a];
 }
References arena, assert, freeblocks, NELEMS, block::next, and NULL.
Referenced by _GLIBCXX_VISIBILITY(), initializer(), main(), program(), statement(), walk(), and bin_search_tree_cond_dtor_entry_dealtor_::~bin_search_tree_cond_dtor_entry_dealtor_().
defglobal()
void defglobal (Symbol , int)
Definition at line 284 of file decl.c.
{
     p->u.seg = seg;
     swtoseg(p->u.seg);
     if (p->sclass != STATIC)
         (*IR->export)(p);
     (*IR->global)(p);
     p->defined = 1;
 }
References IR, STATIC, and swtoseg().
Referenced by bbcall(), bbfunc(), bbvars(), dcllocal(), doconst(), doglobal(), emitcode(), initglobal(), and tracecall().
definelab()
void definelab (int)
Definition at line 533 of file stmt.c.
{
     Code cp;
     Symbol p = findlabel(lab);
     assert(lab);
     walk(NULL, 0, 0);
     code(Label)->u.forest = newnode(LABEL+V, NULL, NULL, p);
     for (cp = codelist->prev; cp->kind <= Label; )
         cp = cp->prev;
     while (   cp->kind == Jump
            && cp->u.forest->kids[0]
            && specific(cp->u.forest->kids[0]->op) == ADDRG+P
            && cp->u.forest->kids[0]->syms[0] == p) {
         assert(cp->u.forest->kids[0]->syms[0]->u.l.label == lab);
         p->ref--;
         assert(cp->next);
         assert(cp->prev);
         cp->prev->next = cp->next;
         cp->next->prev = cp->prev;
         cp = cp->prev;
         while (cp->kind <= Label)
             cp = cp->prev;
     }
 }
References assert, code(), codelist, cp, findlabel(), Swtch::lab, newnode(), NULL, P, specific, V, and walk().
Referenced by dostmt(), forstmt(), funcdefn(), ifstmt(), statement(), stmtlabel(), swcode(), swstmt(), and whilestmt().
definept()
void definept (Coordinate *)
Definition at line 57 of file stmt.c.
{
     Code cp = code(Defpoint);
     cp->u.point.src = p ? *p : src;
     cp->u.point.point = npoints;
     if (ncalled > 0) {
         int n = findcount(cp->u.point.src.file,
             cp->u.point.src.x, cp->u.point.src.y);
         if (n > 0)
             refinc = (float)n/ncalled;
     }
     if (glevel > 2) locus(identifiers, &cp->u.point.src);
     if (events.points && reachable(Gen))
         {
             Tree e = NULL;
             apply(events.points, &cp->u.point.src, &e);
             if (e)
                 listnodes(e, 0, 0);
         }
 }
References apply(), code(), cp, Code::Defpoint, events, findcount(), Code::Gen, glevel, identifiers, listnodes(), locus(), ncalled, npoints, NULL, Events::points, reachable(), and refinc.
Referenced by compound(), dcllocal(), dostmt(), forstmt(), ifstmt(), statement(), swstmt(), and whilestmt().
defpointer()
void defpointer (Symbol)
Definition at line 7 of file init.c.
{
     if (p) {
         (*IR->defaddress)(p);
         p->ref++;
     } else {
         static Value v;
         (*IR->defconst)(P, voidptype->size, v);
     }
 }
References IR, P, and voidptype.
Referenced by bbcall(), bbfunc(), and bbvars().
deref()
Type deref (Type)
Definition at line 195 of file types.c.
                     {
     if (isptr(ty))
         ty = ty->type;
     else
         error("type error: %s\n", "pointer expected");
     return isenum(ty) ? unqual(ty)->type : ty;
 }
References error(), isenum, isptr, and unqual.
Referenced by field(), and rvalue().
emitcode()
void emitcode (void)
Definition at line 495 of file dag.c.
                     {
     Code cp;
     Coordinate save;
     save = src;
     cp = codehead.next;
     for ( ; errcnt <= 0 && cp; cp = cp->next)
         switch (cp->kind) {
         case Address: break;
         case Blockbeg: if (glevel && IR->stabblock) {
                     (*IR->stabblock)('{',  cp->u.block.level - LOCAL, cp->u.block.locals);
                     swtoseg(CODE);
                    }
  break;
         case Blockend: if (glevel && IR->stabblock) {
                     Code bp = cp->u.begin;
                     foreach(bp->u.block.identifiers, bp->u.block.level, typestab, NULL);
                     foreach(bp->u.block.types,       bp->u.block.level, typestab, NULL);
                     (*IR->stabblock)('}', bp->u.block.level - LOCAL, bp->u.block.locals);
                     swtoseg(CODE);
                    }
  break;
         case Defpoint: src = cp->u.point.src;
                    if (glevel > 0 && IR->stabline) {
                     (*IR->stabline)(&cp->u.point.src); swtoseg(CODE); } break;
         case Gen: case Jump:
         case Label:    if (cp->u.forest)
                     (*IR->emit)(cp->u.forest); break;
         case Local:    if (glevel && IR->stabsym) {
                     (*IR->stabsym)(cp->u.var);
                     swtoseg(CODE);
                    } break;
         case Switch:   {    int i;
                     defglobal(cp->u.swtch.table, LIT);
                     (*IR->defaddress)(equated(cp->u.swtch.labels[0]));
                     for (i = 1; i < cp->u.swtch.size; i++) {
                         long k = cp->u.swtch.values[i-1];
                         while (++k < cp->u.swtch.values[i])
                             assert(k < LONG_MAX),
                             (*IR->defaddress)(equated(cp->u.swtch.deflab));
                         (*IR->defaddress)(equated(cp->u.swtch.labels[i]));
                     }
                     swtoseg(CODE);
                    } break;
         default: assert(0);
         }
     src = save;
 }
References assert, bp, CODE, codehead, cp, defglobal(), equated(), errcnt, glevel, IR, LIT, LOCAL, LONG_MAX, Code::next, NULL, swtoseg(), and typestab().
Referenced by function().
enterscope()
void enterscope (void)
Definition at line 57 of file sym.c.
                       {
     if (++level == LOCAL)
         tempid = 0;
 }
References LOCAL, and tempid.
Referenced by compound(), dclr1(), and funcdefn().
enumdcl()
Type enumdcl (void)
Definition at line 1079 of file decl.c.
                    {
     char *tag;
     Type ty;
     Symbol p = {0};
     Coordinate pos;
     t = gettok();
     pos = src;
     if (t == ID) {
         tag = token;
         t = gettok();
     } else
         tag = "";
     if (t == '{') {
         static char follow[] = { IF, 0 };
         int n = 0;
         long k = -1;
         List idlist = 0;
         ty = newstruct(ENUM, tag);
         t = gettok();
         if (t != ID)
             error("expecting an enumerator identifier\n");
         while (t == ID) {
             char *id = token;
             Coordinate s;
             if (tsym && tsym->scope == level)
                 error("redeclaration of `%s' previously declared at %w\n",
                     token, &tsym->src);
             s = src;
             t = gettok();
             if (t == '=') {
                 t = gettok();
                 k = intexpr(0, 0);
             } else {
                 if (k == inttype->u.sym->u.limits.max.i)
                     error("overflow in value for enumeration constant `%s'\n", id);
                 k++;
             }
             p = install(id, &identifiers, level,  level < LOCAL ? PERM : FUNC);
             p->src = s;
             p->type = ty;
             p->sclass = ENUM;
             p->u.value = k;
             idlist = append(p, idlist);
             n++;
             if (Aflag >= 2 && n == 128)
                 warning("more than 127 enumeration constants in `%t'\n", ty);
             if (t != ',')
                 break;
             t = gettok();
             if (Aflag >= 2 && t == '}')
                 warning("non-ANSI trailing comma in enumerator list\n");
         }
         test('}', follow);
         ty->type = inttype;
         ty->size = ty->type->size;
         ty->align = ty->type->align;
         ty->u.sym->u.idlist = ltov(&idlist, PERM);
         ty->u.sym->defined = 1;
     } else if ((p = lookup(tag, types)) != NULL && p->type->op == ENUM) {
         ty = p->type;
         if (t == ';')
             error("empty declaration\n");
     } else {
         error("unknown enumeration `%s'\n",  tag);
         ty = newstruct(ENUM, tag);
         ty->type = inttype;
     }
     if (*tag && xref)
         use(p, pos);
     return ty;
 }
References Aflag, append(), error(), FUNC, gettok(), ID, identifiers, Symbol::idlist, install(), intexpr(), inttype, LOCAL, lookup(), ltov(), newstruct(), NULL, PERM, test(), token, tsym, types, use(), warning(), and xref.
Referenced by specifier().
eqtree()
Tree eqtree (int , Tree , Tree)
Definition at line 231 of file enode.c.
{
     Type xty = l->type, yty = r->type;
     if ((isptr(xty) && isnullptr(r))
     ||  (isptr(xty) && !isfunc(xty->type) && isvoidptr(yty))
     ||  (isptr(xty) && isptr(yty)
         && eqtype(unqual(xty->type), unqual(yty->type), 1))) {
         Type ty = unsignedptr;
         l = cast(l, ty);
         r = cast(r, ty);
         return simplify(mkop(op,ty), inttype, l, r);
     }
     if ((isptr(yty) && isnullptr(l))
     ||  (isptr(yty) && !isfunc(yty->type) && isvoidptr(xty)))
         return eqtree(op, r, l);
     return cmptree(op, l, r);
 }
References cast(), cmptree(), eqtype(), inttype, isfunc, isnullptr(), isptr, isvoidptr, Symbol::l, mkop, op, simplify(), unqual, and unsignedptr.
eqtype()
int eqtype (Type , Type , int)
Definition at line 312 of file types.c.
{
     if (ty1 == ty2)
         return 1;
     if (ty1->op != ty2->op)
         return 0;
     switch (ty1->op) {
     case ENUM: case UNION: case STRUCT:
     case UNSIGNED: case INT: case FLOAT:
         return 0;
     case POINTER:  return eqtype(ty1->type, ty2->type, 1);
     case VOLATILE: case CONST+VOLATILE:
     case CONST:    return eqtype(ty1->type, ty2->type, 1);
     case ARRAY:    if (eqtype(ty1->type, ty2->type, 1)) {
                 if (ty1->size == ty2->size)
                     return 1;
                 if (ty1->size == 0 || ty2->size == 0)
                     return ret;
                }
                return 0;
     case FUNCTION: if (eqtype(ty1->type, ty2->type, 1)) {
                 Type *p1 = ty1->u.f.proto, *p2 = ty2->u.f.proto;
                 if (p1 == p2)
                     return 1;
                 if (p1 && p2) {
                     for ( ; *p1 && *p2; p1++, p2++)
                     if (eqtype(unqual(*p1), unqual(*p2), 1) == 0)
                         return 0;
                 if (*p1 == NULL && *p2 == NULL)
                     return 1;
                 } else {
                     if (variadic(p1 ? ty1 : ty2))
                     return 0;
                 if (p1 == NULL)
                     p1 = p2;
                 for ( ; *p1; p1++) {
                     Type ty = unqual(*p1);
                     if (promote(ty) != (isenum(ty) ? ty->type : ty))
                         return 0;
                 }
                 return 1;
                 }
                }
                return 0;
     }
     assert(0); return 0;
 }
References assert, CONST, INT, isenum, NULL, p1, p2, promote(), unqual, variadic(), and VOLATILE.
Referenced by assign(), compatible(), condtree(), constant(), dclglobal(), dcllocal(), eqtree(), funcdefn(), and primary().
equatelab()
void equatelab (Symbol , Symbol)
Definition at line 597 of file stmt.c.
{
     assert(old->u.l.equatedto == NULL);
     old->u.l.equatedto = new;
     new->ref++;
 }
References assert, and NULL.
Referenced by branch(), labelnode(), and listnodes().
error()
void error (const char * , ...)
Definition at line 33 of file error.c.
{
     va_list ap;
     if (errcnt++ >= errlimit) {
         errcnt = -1;
         error("too many errors\n");
         exit(1);
     }
     va_start(ap, fmt);
     if (firstfile != file && firstfile && *firstfile)
         fprint(stderr, "%s: ", firstfile);
     fprint(stderr, "%w: ", &src);
     vfprint(stderr, NULL, fmt, ap);
     va_end(ap);
 }
References errcnt, errlimit, exit(), firstfile, fmt, fprint(), NULL, stderr, va_end, va_start, and vfprint().
Referenced by expect(), fatal(), skipto(), and warning().
exitscope()
void exitscope (void)
Definition at line 61 of file sym.c.
                      {
     rmtypes(level);
     if (types->level == level)
         types = types->previous;
     if (identifiers->level == level) {
         if (Aflag >= 2) {
             int n = 0;
             Symbol p;
             for (p = identifiers->all; p && p->scope == level; p = p->up)
                 if (++n > 127) {
                     warning("more than 127 identifiers declared in a block\n");
                     break;
                 }
         }
         identifiers = identifiers->previous;
     }
     assert(level >= GLOBAL);
     --level;
 }
References Aflag, assert, GLOBAL, identifiers, level, rmtypes(), types, and warning().
Referenced by compound(), decl(), exitparams(), and funcdefn().
expect()
void expect (int tok)
Definition at line 24 of file error.c.
                      {
     if (t == tok)
         t = gettok();
     else {
         error("syntax error; found");
         printtoken();
         fprint(stderr, " expecting `%k'\n", tok);
     }
 }
References error(), fprint(), gettok(), printtoken(), and stderr.
Referenced by call(), compound(), dcllocal(), dclr1(), dostmt(), expr1(), forstmt(), funcdefn(), ifstmt(), parameters(), statement(), stmtlabel(), swstmt(), test(), unary(), and whilestmt().
expr()
Tree expr (int)
Definition at line 38 of file expr.c.
                    {
     static char stop[] = { IF, ID, '}', 0 };
     Tree p = expr1(0);
     while (t == ',') {
         Tree q;
         t = gettok();
         q = pointer(expr1(0));
         p = tree(RIGHT, q->type, root(value(p)), q);
     }
     if (tok)
         test(tok, stop);
     return p;
 }
References expr1(), gettok(), ID, pointer(), RIGHT, root(), test(), tree(), and value().
Referenced by conditional(), expr0(), expr2(), postfix(), statement(), swstmt(), and unary().
expr0()
Tree expr0 (int)
Definition at line 52 of file expr.c.
                     {
     return root(expr(tok));
 }
References expr(), and root().
Referenced by forstmt(), and statement().
expr1()
Tree expr1 (int)
Definition at line 55 of file expr.c.
                     {
     static char stop[] = { IF, ID, 0 };
     Tree p = expr2();
     if (t == '='
     || (prec[t] >=  6 && prec[t] <=  8)
     || (prec[t] >= 11 && prec[t] <= 13)) {
         int op = t;
         t = gettok();
         if (oper[op] == ASGN)
             p = asgntree(ASGN, p, value(expr1(0)));
         else
             {
                 expect('=');
                 p = incr(op, p, expr1(0));
             }
     }
     if (tok)
         test(tok, stop);
     return p;
 }
References ASGN, asgntree, expect(), expr2(), gettok(), ID, incr(), op, oper, prec, test(), and value().
Referenced by call(), constexpr(), dcllocal(), dclparam(), expr(), initializer(), and initvalue().
fatal()
int fatal (const char * , const char * , int)
Definition at line 74 of file error.c.
{
     print("\n");
     errcnt = -1;
     error("compiler error in %s--", name);
     fprint(stderr, fmt, n);
     exit(EXIT_FAILURE);
     return 0;
 }
References errcnt, error(), exit(), EXIT_FAILURE, fmt, fprint(), print(), and stderr.
field()
Tree field (Tree , const char *)
Definition at line 635 of file expr.c.
{
     Field q;
     Type ty1, ty = p->type;
     if (isptr(ty))
         ty = deref(ty);
     ty1 = ty;
     ty = unqual(ty);
     if ((q = fieldref(name, ty)) != NULL) {
         if (isarray(q->type)) {
             ty = q->type->type;
             if (isconst(ty1) && !isconst(ty))
                 ty = qual(CONST, ty);
             if (isvolatile(ty1) && !isvolatile(ty))
                 ty = qual(VOLATILE, ty);
             ty = array(ty, q->type->size/ty->size, q->type->align);
         } else {
             ty = q->type;
             if (isconst(ty1) && !isconst(ty))
                 ty = qual(CONST, ty);
             if (isvolatile(ty1) && !isvolatile(ty))
                 ty = qual(VOLATILE, ty);
             ty = ptr(ty);
         }
         if (YYcheck && !isaddrop(p->op) && q->offset > 0)   /* omit */
             p = nullcall(ty, YYcheck, p, consttree(q->offset, inttype));    /* omit */
         else                    /* omit */
         p = simplify(ADD+P, ty, p, consttree(q->offset, inttype));
         if (q->lsb) {
             p = tree(FIELD, ty->type, rvalue(p), NULL);
             p->u.field = q;
         } else if (!isarray(q->type))
             p = rvalue(p);
     } else {
         error("unknown field `%s' of `%t'\n", name, ty);
         p = rvalue(retype(p, ptr(inttype)));
     }
     return p;
 }
References ADD, array(), CONST, consttree(), deref(), error(), FIELD, fieldref(), inttype, isaddrop, isarray, isconst, isptr, isvolatile, NULL, nullcall(), P, ptr(), qual(), retype(), rvalue(), simplify(), tree(), unqual, VOLATILE, and YYcheck.
Referenced by Field_AutoComplete(), G_weapPhys_ParseFields(), Hist_Add(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), postfix(), and tracevalue().
fieldlist()
Field fieldlist (Type)
Definition at line 497 of file types.c.
{
     return ty->u.sym->u.s.flist;
 }
fieldref()
Field fieldref (const char * name, Type ty)
Definition at line 502 of file types.c.
{
     Field p = isfield(name, unqual(ty)->u.sym->u.s.flist);
     if (p && xref) {
         Symbol q;
         assert(unqual(ty)->u.sym->u.s.ftab);
         q = lookup(name, unqual(ty)->u.sym->u.s.ftab);
         assert(q);
         use(q, src);
     }
     return p;
 }
References assert, isfield(), lookup(), unqual, use(), and xref.
Referenced by field().
fillbuf()
void fillbuf (void)
Definition at line 35 of file input.c.
                    {
     if (bsize == 0)
         return;
     if (cp >= limit)
         cp = &buffer[MAXLINE+1];
     else
         {
             int n = limit - cp;
             unsigned char *s = &buffer[MAXLINE+1] - n;
             assert(s >= buffer);
             line = (char *)s - ((char *)cp - line);
             while (cp < limit)
                 *s++ = *cp++;
             cp = &buffer[MAXLINE+1] - n;
         }
     if (feof(stdin))
         bsize = 0;
     else
         bsize = fread(&buffer[MAXLINE+1], 1, BUFSIZE, stdin);
     if (bsize < 0) {
         error("read error\n");
         exit(EXIT_FAILURE);
     }
     limit = &buffer[MAXLINE+1+bsize];
     *limit = '\n';
 }
References assert, bsize, BUFSIZE, cp, error(), exit(), EXIT_FAILURE, feof(), fread(), limit, line, MAXLINE, and stdin.
Referenced by input_init(), nextline(), and resynch().
finalize()
void finalize (void)
Definition at line 1021 of file decl.c.
                     {
     foreach(externals,   GLOBAL,    doextern, NULL);
     foreach(identifiers, GLOBAL,    doglobal, NULL);
     foreach(identifiers, GLOBAL,    checkref, NULL);
     foreach(constants,   CONSTANTS, doconst,  NULL);
 }
References checkref(), CONSTANTS, constants, doconst(), doextern(), doglobal(), externals, GLOBAL, identifiers, and NULL.
Referenced by main().
findcount()
int findcount (char * , int , int)
Definition at line 143 of file profio.c.
{
     static struct file *cursor;
     if (cursor == 0 || cursor->name != file)
         cursor = findfile(file);
     if (cursor) {
         int l, u;
         struct count *c = cursor->counts;
         for (l = 0, u = cursor->count - 1; l <= u; ) {
             int k = (l + u)/2;
             if (c[k].y > y || (c[k].y == y && c[k].x > x))
                 u = k - 1;
             else if (c[k].y < y || (c[k].y == y && c[k].x < x))
                 l = k + 1;
             else
                 return c[k].count;
         }
     }
     return -1;
 }
References count::count, file::count, file::counts, findfile(), and file::name.
Referenced by definept().
findfunc()
int findfunc (char * , char *)
Definition at line 165 of file profio.c.
{
     static struct file *cursor;
     if (cursor == 0 || cursor->name != file)
         cursor = findfile(file);
     if (cursor) {
         struct func *p;
         for (p = cursor->funcs; p; p = p->link)
             if (p->name == name)
                 return p->count.count;
     }
     return -1;
 }
References findfile(), file::funcs, file::func::link, and file::name.
Referenced by funcdefn().
findlabel()
Symbol findlabel (int)
Definition at line 145 of file sym.c.
{
     struct entry *p;
     unsigned h = lab&(HASHSIZE-1);
     for (p = labels->buckets[h]; p; p = p->link)
         if (lab == p->sym.u.l.label)
             return &p->sym;
     NEW0(p, FUNC);
     p->sym.name = stringd(lab);
     p->sym.scope = LABELS;
     p->sym.up = labels->all;
     labels->all = &p->sym;
     p->link = labels->buckets[h];
     labels->buckets[h] = p;
     p->sym.generated = 1;
     p->sym.u.l.label = lab;
     (*IR->defsymbol)(&p->sym);
     return &p->sym;
 }
References FUNC, HASHSIZE, IR, labels, LABELS, NEW0, and stringd().
Referenced by branch(), caselabel(), definelab(), dostmt(), forstmt(), ifstmt(), jump(), labelnode(), listnodes(), statement(), swstmt(), and whilestmt().
findtype()
Symbol findtype (Type)
Definition at line 252 of file sym.c.
{
     Table tp = identifiers;
     int i;
     struct entry *p;
     assert(tp);
     do
         for (i = 0; i < HASHSIZE; i++)
             for (p = tp->buckets[i]; p; p = p->link)
                 if (p->sym.type == ty && p->sym.sclass == TYPEDEF)
                     return &p->sym;
     while ((tp = tp->previous) != NULL);
     return NULL;
 }
References assert, HASHSIZE, identifiers, and NULL.
Referenced by outtype(), and typestring().
foreach()
void foreach (Table , int , void(*)(Symbol, void *) , void *)
Definition at line 42 of file sym.c.
{
     assert(tp);
     while (tp && tp->level > lev)
         tp = tp->previous;
     if (tp && tp->level == lev) {
         Symbol p;
         Coordinate sav;
         sav = src;
         for (p = tp->all; p && p->scope == lev; p = p->up) {
             src = p->src;
             (*apply)(p, cl);
         }
         src = sav;
     }
 }
References assert, and cl.
fprint()
void fprint (FILE * f, const char * fmt, ...)
Definition at line 47 of file output.c.
{
     va_list ap;
     va_start(ap, fmt);
     vfprint(f, NULL, fmt, ap);
     va_end(ap);
 }
References fmt, NULL, va_end, va_start, and vfprint().
Referenced by dumpcover(), dumpregs(), dumprule(), dumptree(), error(), expect(), fatal(), genreload(), genspill(), getrule(), linearize(), main(), main_init(), outtype(), printdag(), printdecl(), printnode(), printtoken(), printtree1(), printtype(), prtype(), prune(), ralloc(), reduce(), reprune(), requate(), rewrite(), rtarget(), and skipto().
freturn()
Type freturn (Type)
Definition at line 256 of file types.c.
                       {
     if (isfunc(ty))
         return ty->type;
     error("type error: %s\n", "function expected");
     return inttype;
 }
References error(), inttype, and isfunc.
Referenced by call(), compound(), funcdefn(), printproto(), retcode(), statement(), tracefinis(), tracereturn(), and vcall().
ftype()
Type ftype (Type , Type)
Definition at line 516 of file types.c.
{
     List list = append(ty, NULL);
     list = append(voidtype, list);
     return func(rty, ltov(&list, PERM), 0);
 }
References append(), func(), ltov(), NULL, PERM, and voidtype.
Referenced by bbentry(), bbexit(), and trace_init().
func()
Type func (Type , Type * , int)
Definition at line 248 of file types.c.
{
     if (ty && (isarray(ty) || isfunc(ty)))
         error("illegal return type `%t'\n", ty);
     ty = type(FUNCTION, ty, 0, 0, NULL);
     ty->u.f.proto = proto;
     ty->u.f.oldstyle = style;
     return ty;
 }
References error(), isarray, isfunc, NULL, and type().
Referenced by attach(), compose(), dclr(), ftype(), funcdefn(), main_init(), postfix(), primary(), printproto(), and type_init().
funcname()
char* funcname (Tree)
Definition at line 677 of file expr.c.
{
     if (isaddrop(f->op))
         return stringf("`%s'", f->u.sym->name);
     return "a function";
 }
References isaddrop, and stringf().
Referenced by call(), conditional(), expr2(), NameToAFunc(), and NameToGenFunc().
gencode()
void gencode (Symbol [], Symbol [])
Definition at line 418 of file dag.c.
{
     Code cp;
     Coordinate save;
     if (prunetemps == -1)
         prunetemps = !IR->wants_dag;
     save = src;
     if (assignargs) {
         int i;
         Symbol p, q;
         cp = codehead.next->next;
         codelist = codehead.next;
         for (i = 0; (p = callee[i]) != NULL
                  && (q = caller[i]) != NULL; i++)
             if (p->sclass != q->sclass || p->type != q->type)
                 walk(asgn(p, idtree(q)), 0, 0);
         codelist->next = cp;
         cp->prev = codelist;
     }
     if (glevel && IR->stabsym) {
         int i;
         Symbol p, q;
         for (i = 0; (p = callee[i]) != NULL
                  && (q = caller[i]) != NULL; i++) {
             (*IR->stabsym)(p);
             if (p->sclass != q->sclass || p->type != q->type)
                 (*IR->stabsym)(q);
         }
         swtoseg(CODE);
     }
     cp = codehead.next;
     for ( ; errcnt <= 0 && cp; cp = cp->next)
         switch (cp->kind) {
         case Address:  (*IR->address)(cp->u.addr.sym, cp->u.addr.base,
                     cp->u.addr.offset); break;
         case Blockbeg: {
                     Symbol *p = cp->u.block.locals;
                     (*IR->blockbeg)(&cp->u.block.x);
                     for ( ; *p; p++)
                         if ((*p)->ref != 0.0)
                             (*IR->local)(*p);
                         else if (glevel) (*IR->local)(*p);
                    }
  break;
         case Blockend: (*IR->blockend)(&cp->u.begin->u.block.x); break;
         case Defpoint: src = cp->u.point.src; break;
         case Gen: case Jump:
         case Label:    if (prunetemps)
                     cp->u.forest = prune(cp->u.forest);
                    fixup(cp->u.forest);
                    cp->u.forest = (*IR->gen)(cp->u.forest); break;
         case Local:    (*IR->local)(cp->u.var); break;
         case Switch:   break;
         default: assert(0);
         }
     src = save;
 }
References asgn(), assert, assignargs, CODE, codehead, codelist, cp, errcnt, fixup(), glevel, idtree(), IR, Code::next, NULL, prune(), prunetemps, swtoseg(), and walk().
Referenced by function().
genident()
Symbol genident (int , Type , int)
Definition at line 201 of file sym.c.
{
     Symbol p;
     NEW0(p, lev >= LOCAL ? FUNC : PERM);
     p->name = stringd(genlabel(1));
     p->scope = lev;
     p->sclass = scls;
     p->type = ty;
     p->generated = 1;
     if (lev == GLOBAL)
         (*IR->defsymbol)(p);
     return p;
 }
References FUNC, genlabel(), GLOBAL, IR, LOCAL, NEW0, PERM, and stringd().
Referenced by bbcall(), bbentry(), bbvars(), compound(), condtree(), cvtconst(), dcllocal(), funcdefn(), mkstr(), primary(), prof_init(), retcode(), swcode(), swstmt(), and tracecall().
genlabel()
int genlabel (int)
Definition at line 139 of file sym.c.
                     {
     static int label = 1;
     label += n;
     return label - n;
 }
Referenced by addrtree(), defsymbol(), fields(), funcdefn(), genident(), listnodes(), newfield(), newstruct(), statement(), stmtlabel(), and swcode().
getchr()
int getchr (void)
Definition at line 860 of file lex.c.
                  {
     for (;;) {
         while (map[*cp]&BLANK)
             cp++;
         if (!(map[*cp]&NEWLINE))
             return *cp;
         cp++;
         nextline();
         if (cp == limit)
             return EOI;
     }
 }
References BLANK, cp, limit, NEWLINE, and nextline().
Referenced by compound(), primary(), scon(), and statement().
gettok()
int gettok (void)
Definition at line 155 of file lex.c.
                  {
     for (;;) {
         register unsigned char *rcp = cp;
         while (map[*rcp]&BLANK)
             rcp++;
         if (limit - rcp < MAXTOKEN) {
             cp = rcp;
             fillbuf();
             rcp = cp;
         }
         src.file = file;
         src.x = (char *)rcp - line;
         src.y = lineno;
         cp = rcp + 1;
         switch (*rcp++) {
         case '/': if (*rcp == '*') {
                 int c = 0;
                 for (rcp++; *rcp != '/' || c != '*'; )
                     if (map[*rcp]&NEWLINE) {
                         if (rcp < limit)
                             c = *rcp;
                         cp = rcp + 1;
                         nextline();
                         rcp = cp;
                         if (rcp == limit)
                             break;
                     } else
                         c = *rcp++;
                 if (rcp < limit)
                     rcp++;
                 else
                     error("unclosed comment\n");
                 cp = rcp;
                 continue;
               }
               return '/';
         case '<':
             if (*rcp == '=') return cp++, LEQ;
             if (*rcp == '<') return cp++, LSHIFT;
             return '<';
         case '>':
             if (*rcp == '=') return cp++, GEQ;
             if (*rcp == '>') return cp++, RSHIFT;
             return '>';
         case '-':
             if (*rcp == '>') return cp++, DEREF;
             if (*rcp == '-') return cp++, DECR;
             return '-';
         case '=': return *rcp == '=' ? cp++, EQL    : '=';
         case '!': return *rcp == '=' ? cp++, NEQ    : '!';
         case '|': return *rcp == '|' ? cp++, OROR   : '|';
         case '&': return *rcp == '&' ? cp++, ANDAND : '&';
         case '+': return *rcp == '+' ? cp++, INCR   : '+';
         case ';': case ',': case ':':
         case '*': case '~': case '%': case '^': case '?':
         case '[': case ']': case '{': case '}': case '(': case ')':
             return rcp[-1];
         case '\n': case '\v': case '\r': case '\f':
             nextline();
             if (cp == limit) {
                 tsym = NULL;
                 return EOI;
             }
             continue;
         case 'i':
             if (rcp[0] == 'f'
             && !(map[rcp[1]]&(DIGIT|LETTER))) {
                 cp = rcp + 1;
                 return IF;
             }
             if (rcp[0] == 'n'
             &&  rcp[1] == 't'
             && !(map[rcp[2]]&(DIGIT|LETTER))) {
                 cp = rcp + 2;
                 tsym = inttype->u.sym;
                 return INT;
             }
             goto id;
         case 'h': case 'j': case 'k': case 'm': case 'n': case 'o':
         case 'p': case 'q': case 'x': case 'y': case 'z':
         case 'A': case 'B': case 'C': case 'D': case 'E': case 'F':
         case 'G': case 'H': case 'I': case 'J': case 'K':
         case 'M': case 'N': case 'O': case 'P': case 'Q': case 'R':
         case 'S': case 'T': case 'U': case 'V': case 'W': case 'X':
         case 'Y': case 'Z':
         id:
             if (limit - rcp < MAXLINE) {
                 cp = rcp - 1;
                 fillbuf();
                 rcp = ++cp;
             }
             assert(cp == rcp);
             token = (char *)rcp - 1;
             while (map[*rcp]&(DIGIT|LETTER))
                 rcp++;
             token = stringn(token, (char *)rcp - token);
             tsym = lookup(token, identifiers);
             cp = rcp;
             return ID;
         case '0': case '1': case '2': case '3': case '4':
         case '5': case '6': case '7': case '8': case '9': {
             unsigned long n = 0;
             if (limit - rcp < MAXLINE) {
                 cp = rcp - 1;
                 fillbuf();
                 rcp = ++cp;
             }
             assert(cp == rcp);
             token = (char *)rcp - 1;
             if (*token == '0' && (*rcp == 'x' || *rcp == 'X')) {
                 int d, overflow = 0;
                 while (*++rcp) {
                     if (map[*rcp]&DIGIT)
                         d = *rcp - '0';
                     else if (*rcp >= 'a' && *rcp <= 'f')
                         d = *rcp - 'a' + 10;
                     else if (*rcp >= 'A' && *rcp <= 'F')
                         d = *rcp - 'A' + 10;
                     else
                         break;
                     if (n&~(~0UL >> 4))
                         overflow = 1;
                     else
                         n = (n<<4) + d;
                 }
                 if ((char *)rcp - token <= 2)
                     error("invalid hexadecimal constant `%S'\n", token, (char *)rcp-token);
                 cp = rcp;
                 tsym = icon(n, overflow, 16);
             } else if (*token == '0') {
                 int err = 0, overflow = 0;
                 for ( ; map[*rcp]&DIGIT; rcp++) {
                     if (*rcp == '8' || *rcp == '9')
                         err = 1;
                     if (n&~(~0UL >> 3))
                         overflow = 1;
                     else
                         n = (n<<3) + (*rcp - '0');
                 }
                 if (*rcp == '.' || *rcp == 'e' || *rcp == 'E') {
                     cp = rcp;
                     tsym = fcon();
                     return FCON;
                 }
                 cp = rcp;
                 tsym = icon(n, overflow, 8);
                 if (err)
                     error("invalid octal constant `%S'\n", token, (char*)cp-token);
             } else {
                 int overflow = 0;
                 for (n = *token - '0'; map[*rcp]&DIGIT; ) {
                     int d = *rcp++ - '0';
                     if (n > (ULONG_MAX - d)/10)
                         overflow = 1;
                     else
                         n = 10*n + d;
                 }
                 if (*rcp == '.' || *rcp == 'e' || *rcp == 'E') {
                     cp = rcp;
                     tsym = fcon();
                     return FCON;
                 }
                 cp = rcp;
                 tsym = icon(n, overflow, 10);
             }
             return ICON;
         }
         case '.':
             if (rcp[0] == '.' && rcp[1] == '.') {
                 cp += 2;
                 return ELLIPSIS;
             }
             if ((map[*rcp]&DIGIT) == 0)
                 return '.';
             if (limit - rcp < MAXLINE) {
                 cp = rcp - 1;
                 fillbuf();
                 rcp = ++cp;
             }
             assert(cp == rcp);
             cp = rcp - 1;
             token = (char *)cp;
             tsym = fcon();
             return FCON;
         case 'L':
             if (*rcp == '\'') {
                 unsigned int *s = scon(*cp, wcput, wcbuf);
                 if (s - wcbuf > 2)
                     warning("excess characters in wide-character literal ignored\n");
                 tval.type = widechar;
                 tval.u.c.v.u = wcbuf[0];
                 tsym = &tval;
                 return ICON;
             } else if (*rcp == '"') {
                 unsigned int *s = scon(*cp, wcput, wcbuf);
                 tval.type = array(widechar, s - wcbuf, 0);
                 tval.u.c.v.p = wcbuf;
                 tsym = &tval;
                 return SCON;
             } else
                 goto id;
         case '\'': {
             char *s = scon(*--cp, cput, cbuf);
             if (s - cbuf > 2)
                 warning("excess characters in multibyte character literal ignored\n");
             tval.type = inttype;
             if (chartype->op == INT)
                 tval.u.c.v.i = extend(cbuf[0], chartype);
             else
                 tval.u.c.v.i = cbuf[0]&0xFF;
             tsym = &tval;
             return ICON;
             }
         case '"': {
             char *s = scon(*--cp, cput, cbuf);
             tval.type = array(chartype, s - cbuf, 0);
             tval.u.c.v.p = cbuf;
             tsym = &tval;
             return SCON;
             }
         case 'a':
             if (rcp[0] == 'u'
             &&  rcp[1] == 't'
             &&  rcp[2] == 'o'
             && !(map[rcp[3]]&(DIGIT|LETTER))) {
                 cp = rcp + 3;
                 return AUTO;
             }
             goto id;
         case 'b':
             if (rcp[0] == 'r'
             &&  rcp[1] == 'e'
             &&  rcp[2] == 'a'
             &&  rcp[3] == 'k'
             && !(map[rcp[4]]&(DIGIT|LETTER))) {
                 cp = rcp + 4;
                 return BREAK;
             }
             goto id;
         case 'c':
             if (rcp[0] == 'a'
             &&  rcp[1] == 's'
             &&  rcp[2] == 'e'
             && !(map[rcp[3]]&(DIGIT|LETTER))) {
                 cp = rcp + 3;
                 return CASE;
             }
             if (rcp[0] == 'h'
             &&  rcp[1] == 'a'
             &&  rcp[2] == 'r'
             && !(map[rcp[3]]&(DIGIT|LETTER))) {
                 cp = rcp + 3;
                 tsym = chartype->u.sym;
                 return CHAR;
             }
             if (rcp[0] == 'o'
             &&  rcp[1] == 'n'
             &&  rcp[2] == 's'
             &&  rcp[3] == 't'
             && !(map[rcp[4]]&(DIGIT|LETTER))) {
                 cp = rcp + 4;
                 return CONST;
             }
             if (rcp[0] == 'o'
             &&  rcp[1] == 'n'
             &&  rcp[2] == 't'
             &&  rcp[3] == 'i'
             &&  rcp[4] == 'n'
             &&  rcp[5] == 'u'
             &&  rcp[6] == 'e'
             && !(map[rcp[7]]&(DIGIT|LETTER))) {
                 cp = rcp + 7;
                 return CONTINUE;
             }
             goto id;
         case 'd':
             if (rcp[0] == 'e'
             &&  rcp[1] == 'f'
             &&  rcp[2] == 'a'
             &&  rcp[3] == 'u'
             &&  rcp[4] == 'l'
             &&  rcp[5] == 't'
             && !(map[rcp[6]]&(DIGIT|LETTER))) {
                 cp = rcp + 6;
                 return DEFAULT;
             }
             if (rcp[0] == 'o'
             &&  rcp[1] == 'u'
             &&  rcp[2] == 'b'
             &&  rcp[3] == 'l'
             &&  rcp[4] == 'e'
             && !(map[rcp[5]]&(DIGIT|LETTER))) {
                 cp = rcp + 5;
                 tsym = doubletype->u.sym;
                 return DOUBLE;
             }
             if (rcp[0] == 'o'
             && !(map[rcp[1]]&(DIGIT|LETTER))) {
                 cp = rcp + 1;
                 return DO;
             }
             goto id;
         case 'e':
             if (rcp[0] == 'l'
             &&  rcp[1] == 's'
             &&  rcp[2] == 'e'
             && !(map[rcp[3]]&(DIGIT|LETTER))) {
                 cp = rcp + 3;
                 return ELSE;
             }
             if (rcp[0] == 'n'
             &&  rcp[1] == 'u'
             &&  rcp[2] == 'm'
             && !(map[rcp[3]]&(DIGIT|LETTER))) {
                 cp = rcp + 3;
                 return ENUM;
             }
             if (rcp[0] == 'x'
             &&  rcp[1] == 't'
             &&  rcp[2] == 'e'
             &&  rcp[3] == 'r'
             &&  rcp[4] == 'n'
             && !(map[rcp[5]]&(DIGIT|LETTER))) {
                 cp = rcp + 5;
                 return EXTERN;
             }
             goto id;
         case 'f':
             if (rcp[0] == 'l'
             &&  rcp[1] == 'o'
             &&  rcp[2] == 'a'
             &&  rcp[3] == 't'
             && !(map[rcp[4]]&(DIGIT|LETTER))) {
                 cp = rcp + 4;
                 tsym = floattype->u.sym;
                 return FLOAT;
             }
             if (rcp[0] == 'o'
             &&  rcp[1] == 'r'
             && !(map[rcp[2]]&(DIGIT|LETTER))) {
                 cp = rcp + 2;
                 return FOR;
             }
             goto id;
         case 'g':
             if (rcp[0] == 'o'
             &&  rcp[1] == 't'
             &&  rcp[2] == 'o'
             && !(map[rcp[3]]&(DIGIT|LETTER))) {
                 cp = rcp + 3;
                 return GOTO;
             }
             goto id;
         case 'l':
             if (rcp[0] == 'o'
             &&  rcp[1] == 'n'
             &&  rcp[2] == 'g'
             && !(map[rcp[3]]&(DIGIT|LETTER))) {
                 cp = rcp + 3;
                 return LONG;
             }
             goto id;
         case 'r':
             if (rcp[0] == 'e'
             &&  rcp[1] == 'g'
             &&  rcp[2] == 'i'
             &&  rcp[3] == 's'
             &&  rcp[4] == 't'
             &&  rcp[5] == 'e'
             &&  rcp[6] == 'r'
             && !(map[rcp[7]]&(DIGIT|LETTER))) {
                 cp = rcp + 7;
                 return REGISTER;
             }
             if (rcp[0] == 'e'
             &&  rcp[1] == 't'
             &&  rcp[2] == 'u'
             &&  rcp[3] == 'r'
             &&  rcp[4] == 'n'
             && !(map[rcp[5]]&(DIGIT|LETTER))) {
                 cp = rcp + 5;
                 return RETURN;
             }
             goto id;
         case 's':
             if (rcp[0] == 'h'
             &&  rcp[1] == 'o'
             &&  rcp[2] == 'r'
             &&  rcp[3] == 't'
             && !(map[rcp[4]]&(DIGIT|LETTER))) {
                 cp = rcp + 4;
                 return SHORT;
             }
             if (rcp[0] == 'i'
             &&  rcp[1] == 'g'
             &&  rcp[2] == 'n'
             &&  rcp[3] == 'e'
             &&  rcp[4] == 'd'
             && !(map[rcp[5]]&(DIGIT|LETTER))) {
                 cp = rcp + 5;
                 return SIGNED;
             }
             if (rcp[0] == 'i'
             &&  rcp[1] == 'z'
             &&  rcp[2] == 'e'
             &&  rcp[3] == 'o'
             &&  rcp[4] == 'f'
             && !(map[rcp[5]]&(DIGIT|LETTER))) {
                 cp = rcp + 5;
                 return SIZEOF;
             }
             if (rcp[0] == 't'
             &&  rcp[1] == 'a'
             &&  rcp[2] == 't'
             &&  rcp[3] == 'i'
             &&  rcp[4] == 'c'
             && !(map[rcp[5]]&(DIGIT|LETTER))) {
                 cp = rcp + 5;
                 return STATIC;
             }
             if (rcp[0] == 't'
             &&  rcp[1] == 'r'
             &&  rcp[2] == 'u'
             &&  rcp[3] == 'c'
             &&  rcp[4] == 't'
             && !(map[rcp[5]]&(DIGIT|LETTER))) {
                 cp = rcp + 5;
                 return STRUCT;
             }
             if (rcp[0] == 'w'
             &&  rcp[1] == 'i'
             &&  rcp[2] == 't'
             &&  rcp[3] == 'c'
             &&  rcp[4] == 'h'
             && !(map[rcp[5]]&(DIGIT|LETTER))) {
                 cp = rcp + 5;
                 return SWITCH;
             }
             goto id;
         case 't':
             if (rcp[0] == 'y'
             &&  rcp[1] == 'p'
             &&  rcp[2] == 'e'
             &&  rcp[3] == 'd'
             &&  rcp[4] == 'e'
             &&  rcp[5] == 'f'
             && !(map[rcp[6]]&(DIGIT|LETTER))) {
                 cp = rcp + 6;
                 return TYPEDEF;
             }
             goto id;
         case 'u':
             if (rcp[0] == 'n'
             &&  rcp[1] == 'i'
             &&  rcp[2] == 'o'
             &&  rcp[3] == 'n'
             && !(map[rcp[4]]&(DIGIT|LETTER))) {
                 cp = rcp + 4;
                 return UNION;
             }
             if (rcp[0] == 'n'
             &&  rcp[1] == 's'
             &&  rcp[2] == 'i'
             &&  rcp[3] == 'g'
             &&  rcp[4] == 'n'
             &&  rcp[5] == 'e'
             &&  rcp[6] == 'd'
             && !(map[rcp[7]]&(DIGIT|LETTER))) {
                 cp = rcp + 7;
                 return UNSIGNED;
             }
             goto id;
         case 'v':
             if (rcp[0] == 'o'
             &&  rcp[1] == 'i'
             &&  rcp[2] == 'd'
             && !(map[rcp[3]]&(DIGIT|LETTER))) {
                 cp = rcp + 3;
                 tsym = voidtype->u.sym;
                 return VOID;
             }
             if (rcp[0] == 'o'
             &&  rcp[1] == 'l'
             &&  rcp[2] == 'a'
             &&  rcp[3] == 't'
             &&  rcp[4] == 'i'
             &&  rcp[5] == 'l'
             &&  rcp[6] == 'e'
             && !(map[rcp[7]]&(DIGIT|LETTER))) {
                 cp = rcp + 7;
                 return VOLATILE;
             }
             goto id;
         case 'w':
             if (rcp[0] == 'h'
             &&  rcp[1] == 'i'
             &&  rcp[2] == 'l'
             &&  rcp[3] == 'e'
             && !(map[rcp[4]]&(DIGIT|LETTER))) {
                 cp = rcp + 4;
                 return WHILE;
             }
             goto id;
         case '_':
             if (rcp[0] == '_'
             &&  rcp[1] == 't'
             &&  rcp[2] == 'y'
             &&  rcp[3] == 'p'
             &&  rcp[4] == 'e'
             &&  rcp[5] == 'c'
             &&  rcp[6] == 'o'
             &&  rcp[7] == 'd'
             &&  rcp[8] == 'e'
             && !(map[rcp[9]]&(DIGIT|LETTER))) {
                 cp = rcp + 9;
                 return TYPECODE;
             }
             if (rcp[0] == '_'
             &&  rcp[1] == 'f'
             &&  rcp[2] == 'i'
             &&  rcp[3] == 'r'
             &&  rcp[4] == 's'
             &&  rcp[5] == 't'
             &&  rcp[6] == 'a'
             &&  rcp[7] == 'r'
             &&  rcp[8] == 'g'
             && !(map[rcp[9]]&(DIGIT|LETTER))) {
                 cp = rcp + 9;
                 return FIRSTARG;
             }
             goto id;
         default:
             if ((map[cp[-1]]&BLANK) == 0) {
                 if (cp[-1] < ' ' || cp[-1] >= 0177)
                     error("illegal character `\\0%o'\n", cp[-1]);
                 else
                     error("illegal character `%c'\n", cp[-1]);
             }
         }
     }
 }
References array(), assert, BLANK, Symbol::c, cbuf, chartype, CONST, cp, cput(), DEREF, DIGIT, doubletype, EQL, error(), extend, EXTERN, fcon(), file, fillbuf(), floattype, GEQ, icon(), ID, identifiers, INT, inttype, LEQ, LETTER, limit, line, lineno, LONG, lookup(), MAXLINE, MAXTOKEN, NEQ, NEWLINE, nextline(), NULL, OROR, scon(), SIGNED, SIZEOF, STATIC, stringn(), token, tsym, tval, Symbol::type, Symbol::u, ULONG_MAX, VOID(), voidtype, VOLATILE, warning(), wcbuf, wcput(), and widechar.
Referenced by call(), dclglobal(), dcllocal(), dclparam(), dclr1(), decl(), dostmt(), enumdcl(), expect(), expr(), expr1(), expr2(), expr3(), fields(), forstmt(), ifstmt(), initarray(), initchar(), initend(), initfields(), initglobal(), initializer(), initstruct(), main(), parameters(), postfix(), pragma(), primary(), program(), skipto(), specifier(), statement(), stmtlabel(), structdcl(), swstmt(), test(), unary(), and whilestmt().
hascall()
int hascall (Tree p)
Definition at line 484 of file expr.c.
                     {
     if (p == 0)
         return 0;
     if (generic(p->op) == CALL || (IR->mulops_calls &&
       (p->op == DIV+I || p->op == MOD+I || p->op == MUL+I
     || p->op == DIV+U || p->op == MOD+U || p->op == MUL+U)))
         return 1;
     return hascall(p->kids[0]) || hascall(p->kids[1]);
 }
References CALL, DIV, I, IR, MOD, and U.
Referenced by call(), and vcall().
hasproto()
int hasproto (Type)
Definition at line 481 of file types.c.
                       {
     if (ty == 0)
         return 1;
     switch (ty->op) {
     case CONST: case VOLATILE: case CONST+VOLATILE: case POINTER:
     case ARRAY:
         return hasproto(ty->type);
     case FUNCTION:
         return hasproto(ty->type) && ty->u.f.proto;
     case STRUCT: case UNION:
     case VOID:   case FLOAT: case ENUM:  case INT: case UNSIGNED:
         return 1;
     }
     assert(0); return 0;
 }
References assert, CONST, INT, VOID(), and VOLATILE.
Referenced by decl(), fields(), parameters(), and typename().
idtree()
Tree idtree (Symbol)
Definition at line 415 of file expr.c.
                       {
     int op;
     Tree e;
     Type ty = p->type ? unqual(p->type) : voidptype;
     if (p->scope == GLOBAL || p->sclass == STATIC)
         op = ADDRG;
     else if (p->scope == PARAM) {
         op = ADDRF;
         if (isstruct(p->type) && !IR->wants_argb)
             {
                 e = tree(mkop(op,voidptype), ptr(ptr(p->type)), NULL, NULL);
                 e->u.sym = p;
                 return rvalue(rvalue(e));
             }
     } else if (p->sclass == EXTERN) {
         assert(p->u.alias);
         p = p->u.alias;
         op = ADDRG;
     } else
         op = ADDRL;
     p->ref += refinc;
     if (isarray(ty))
         e = tree(mkop(op,voidptype), p->type,      NULL, NULL);
     else if (isfunc(ty))
         e = tree(mkop(op,funcptype), p->type,      NULL, NULL);
     else
         e = tree(mkop(op,voidptype), ptr(p->type), NULL, NULL);
     e->u.sym = p;
     if (isptr(e->type))
         e = rvalue(e);
     return e;
 }
References assert, EXTERN, funcptype, GLOBAL, IR, isarray, isfunc, isptr, isstruct, mkop, NULL, op, PARAM, ptr(), refinc, rvalue(), STATIC, tree(), unqual, and voidptype.
Referenced by addrof(), asgn(), asgntree(), bbcall(), bbentry(), bbexit(), bbincr(), call(), calltree(), cmp(), cvtconst(), dcllocal(), gencode(), listnodes(), nullcall(), nullcheck(), primary(), retcode(), swcode(), tracecall(), tracefinis(), tracereturn(), tracevalue(), and vcall().
incr()
Tree incr (int , Tree , Tree)
Definition at line 76 of file expr.c.
{
     return asgntree(ASGN, v, (*optree[op])(oper[op], v, e));
 }
References ASGN, asgntree, op, oper, and optree.
Referenced by bbincr(), expr1(), inflate_table(), postfix(), tracecall(), and unary().
init()
void init (int , char * [])
Definition at line 1 of file inits.c.
{
     {extern void input_init(int, char *[]); input_init(argc, argv);}
     {extern void main_init(int, char *[]); main_init(argc, argv);}
     {extern void prof_init(int, char *[]); prof_init(argc, argv);}
     {extern void trace_init(int, char *[]); trace_init(argc, argv);}
     {extern void type_init(int, char *[]); type_init(argc, argv);}
 }
References input_init(), main_init(), prof_init(), trace_init(), and type_init().
Referenced by _GLIBCXX_VISIBILITY(), and main().
initializer()
Type initializer (Type , int)
Definition at line 196 of file init.c.
{
     int n = 0;
     Tree e;
     Type aty = NULL;
     static char follow[] = { IF, CHAR, STATIC, 0 };
     ty = unqual(ty);
     if (isscalar(ty)) {
         needconst++;
         if (t == '{') {
             t = gettok();
             e = expr1(0);
             initend(lev, follow);
         } else
             e = expr1(0);
         e = pointer(e);
         if ((aty = assign(ty, e)) != NULL)
             e = cast(e, aty);
         else
             error("invalid initialization type; found `%t' expected `%t'\n",
                 e->type, ty);
         n = genconst(e, 1);
         deallocate(STMT);
         needconst--;
     }
     if ((isunion(ty) || isstruct(ty)) && ty->size == 0) {
         static char follow[] = { CHAR, STATIC, 0 };
         error("cannot initialize undefined `%t'\n", ty);
         skipto(';', follow);
         return ty;
     } else if (isunion(ty)) {
         if (t == '{') {
             t = gettok();
             n = initstruct(ty->u.sym->u.s.flist->type->size, ty, lev + 1);
             initend(lev, follow);
         } else {
             if (lev == 0)
                 error("missing { in initialization of `%t'\n", ty);
             n = initstruct(ty->u.sym->u.s.flist->type->size, ty, lev + 1);
         }
     } else if (isstruct(ty)) {
         if (t == '{') {
             t = gettok();
             n = initstruct(0, ty, lev + 1);
             test('}', follow);
         } else if (lev > 0)
             n = initstruct(ty->size, ty, lev + 1);
         else {
             error("missing { in initialization of `%t'\n", ty);
             n = initstruct(ty->u.sym->u.s.flist->type->size, ty, lev + 1);
         }
     }
     if (isarray(ty))
         aty = unqual(ty->type);
     if (isarray(ty) && ischar(aty)) {
         if (t == SCON) {
             if (ty->size > 0 && ty->size == tsym->type->size - 1)
                 tsym->type = array(chartype, ty->size, 0);
             n = tsym->type->size;
             (*IR->defstring)(tsym->type->size, tsym->u.c.v.p);
             t = gettok();
         } else if (t == '{') {
             t = gettok();
             if (t == SCON) {
                 ty = initializer(ty, lev + 1);
                 initend(lev, follow);
                 return ty;
             }
             n = initchar(0, aty);
             test('}', follow);
         } else if (lev > 0 && ty->size > 0)
             n = initchar(ty->size, aty);
         else {  /* eg, char c[] = 0; */
             error("missing { in initialization of `%t'\n", ty);
             n = initchar(1, aty);
         }
     } else if (isarray(ty)) {
         if (t == SCON && aty == widechar) {
             int i;
             unsigned int *s = tsym->u.c.v.p;
             if (ty->size > 0 && ty->size == tsym->type->size - widechar->size)
                 tsym->type = array(widechar, ty->size/widechar->size, 0);
             n = tsym->type->size;
             for (i = 0; i < n; i += widechar->size) {
                 Value v;
                 v.u = *s++;
                 (*IR->defconst)(widechar->op, widechar->size, v);
             }
             t = gettok();
         } else if (t == '{') {
             t = gettok();
             if (t == SCON && aty == widechar) {
                 ty = initializer(ty, lev + 1);
                 initend(lev, follow);
                 return ty;
             }
             n = initarray(0, aty, lev + 1);
             test('}', follow);
         } else if (lev > 0 && ty->size > 0)
             n = initarray(ty->size, aty, lev + 1);
         else {
             error("missing { in initialization of `%t'\n", ty);
             n = initarray(aty->size, aty, lev + 1);
         }
     }
     if (ty->size) {
         if (n > ty->size)
             error("too many initializers\n");
         else if (n < ty->size)
             (*IR->space)(ty->size - n);
     } else if (isarray(ty) && ty->type->size > 0)
         ty = array(ty->type, n/ty->type->size, 0);
     else
         ty->size = n;
     return ty;
 }
References array(), assign(), cast(), chartype, deallocate(), error(), expr1(), genconst(), gettok(), initarray(), initchar(), initend(), initstruct(), IR, isarray, ischar, isscalar, isstruct, isunion, needconst, NULL, skipto(), STATIC, STMT, test(), tsym, unqual, and widechar.
Referenced by dclglobal(), initarray(), initglobal(), and initstruct().
input_init()
void input_init (int , char * [])
Definition at line 61 of file input.c.
{
     static int inited;
     if (inited)
         return;
     inited = 1;
     main_init(argc, argv);
     limit = cp = &buffer[MAXLINE+1];
     bsize = -1;
     lineno = 0;
     file = NULL;
     fillbuf();
     if (cp >= limit)
         cp = limit;
     nextline();
 }
References bsize, cp, fillbuf(), limit, lineno, main_init(), MAXLINE, nextline(), and NULL.
Referenced by init().
install()
Symbol install (const char * , Table * , int , int)
Definition at line 80 of file sym.c.
{
     Table tp = *tpp;
     struct entry *p;
     unsigned h = (unsigned long)name&(HASHSIZE-1);
     assert(level == 0 || level >= tp->level);
     if (level > 0 && tp->level < level)
         tp = *tpp = table(tp, level);
     NEW0(p, arena);
     p->sym.name = (char *)name;
     p->sym.scope = level;
     p->sym.up = tp->all;
     tp->all = &p->sym;
     p->link = tp->buckets[h];
     tp->buckets[h] = p;
     return &p->sym;
 }
References arena, assert, HASHSIZE, level, long(), NEW0, and table().
Referenced by mksymbol().
intconst()
Symbol intconst (int)
Definition at line 195 of file sym.c.
{
     Value v;
     v.i = n;
     return constant(inttype, v);
 }
References constant(), and inttype.
Referenced by asgnnode(), docall(), and listnodes().
intexpr()
int intexpr (int , int)
Definition at line 194 of file simp.c.
{
     Tree p = constexpr(tok);
     needconst++;
     if (p->op == CNST+I || p->op == CNST+U)
         n = cast(p, inttype)->u.v.i;
     else
         error("integer expression must be constant\n");
     needconst--;
     return n;
 }
References cast(), constexpr(), error(), I, inttype, needconst, and U.
Referenced by dclr1(), enumdcl(), and fields().
iscallb()
int iscallb (Tree)
Definition at line 141 of file enode.c.
                     {
     return e->op == RIGHT && e->kids[0] && e->kids[1]
         && e->kids[0]->op == CALL+B
         && e->kids[1]->op == INDIR+B
         && isaddrop(e->kids[1]->kids[0]->op)
         && e->kids[1]->kids[0]->u.sym->temporary;
 }
References B, CALL, isaddrop, and RIGHT.
Referenced by asgntree(), call(), and retcode().
ispow2()
int ispow2 (unsigned long u)
Definition at line 578 of file simp.c.
{
     int n;
     if (u > 1 && (u&(u-1)) == 0)
         for (n = 0; u; u >>= 1, n++)
             if (u&1)
                 return n;
     return 0;
 }
Referenced by simplify().
jump()
Node jump (int)
Definition at line 557 of file stmt.c.
                    {
     Symbol p = findlabel(lab);
     p->ref++;
     return newnode(JUMP+V, newnode(ADDRG+ttob(voidptype), NULL, NULL, p),
         NULL, NULL);
 }
References findlabel(), Swtch::lab, newnode(), NULL, ttob(), V, and voidptype.
Referenced by branch(), and listnodes().
length()
int length (List list)
Definition at line 24 of file list.c.
                       {
     int n = 0;
     if (list) {
         List lp = list;
         do
             n++;
         while ((lp = lp->link) != list);
     }
     return n;
 }
References list().
Referenced by ltov().
listnodes()
Node listnodes (Tree e, int tlab, int flab)
Definition at line 101 of file dag.c.
{
     Node p = NULL, l, r;
     int op;
     assert(tlab || flab || (tlab == 0 && flab == 0));
     if (tp == NULL)
         return NULL;
     if (tp->node)
         return tp->node;
     op = tp->op + sizeop(tp->type->size);
     switch (generic(tp->op)) {
     case AND:   { if (depth++ == 0) reset();
               if (flab) {
                 listnodes(tp->kids[0], 0, flab);
                 listnodes(tp->kids[1], 0, flab);
               } else {
                 listnodes(tp->kids[0], 0, flab = genlabel(1));
                 listnodes(tp->kids[1], tlab, 0);
                 labelnode(flab);
               }
               depth--; } break;
     case OR:    { if (depth++ == 0)
                 reset();
               if (tlab) {
                 listnodes(tp->kids[0], tlab, 0);
                 listnodes(tp->kids[1], tlab, 0);
               } else {
                 tlab = genlabel(1);
                 listnodes(tp->kids[0], tlab, 0);
                 listnodes(tp->kids[1], 0, flab);
                 labelnode(tlab);
               }
               depth--;
  } break;
     case NOT:   { return listnodes(tp->kids[0], flab, tlab); }
     case COND:  { Tree q = tp->kids[1];
               assert(tlab == 0 && flab == 0);
               if (tp->u.sym)
                 addlocal(tp->u.sym);
               flab = genlabel(2);
               listnodes(tp->kids[0], 0, flab);
               assert(q && q->op == RIGHT);
               reset();
               listnodes(q->kids[0], 0, 0);
               if (forest->op == LABEL+V) {
                 equatelab(forest->syms[0], findlabel(flab + 1));
                 unlist();
               }
               list(jump(flab + 1));
               labelnode(flab);
               listnodes(q->kids[1], 0, 0);
               if (forest->op == LABEL+V) {
                 equatelab(forest->syms[0], findlabel(flab + 1));
                 unlist();
               }
               labelnode(flab + 1);
               if (tp->u.sym)
                 p = listnodes(idtree(tp->u.sym), 0, 0); } break;
     case CNST:  { Type ty = unqual(tp->type);
               assert(ty->u.sym);
               if (tlab || flab) {
                 assert(ty == inttype);
                 if (tlab && tp->u.v.i != 0)
                     list(jump(tlab));
                 else if (flab && tp->u.v.i == 0)
                     list(jump(flab));
               }
               else if (ty->u.sym->addressed)
                 p = listnodes(cvtconst(tp), 0, 0);
               else
                 p = node(op, NULL, NULL, constant(ty, tp->u.v)); } break;
     case RIGHT: { if (   tp->kids[0] && tp->kids[1]
               &&  generic(tp->kids[1]->op) == ASGN
               && ((generic(tp->kids[0]->op) == INDIR
               && tp->kids[0]->kids[0] == tp->kids[1]->kids[0])
               || (tp->kids[0]->op == FIELD
               &&  tp->kids[0] == tp->kids[1]->kids[0]))) {
                 assert(tlab == 0 && flab == 0);
             if (generic(tp->kids[0]->op) == INDIR) {
                 p = listnodes(tp->kids[0], 0, 0);
                 list(p);
                 listnodes(tp->kids[1], 0, 0);
             }
             else {
                 assert(generic(tp->kids[0]->kids[0]->op) == INDIR);
                 list(listnodes(tp->kids[0]->kids[0], 0, 0));
                 p = listnodes(tp->kids[0], 0, 0);
                 listnodes(tp->kids[1], 0, 0);
             }
               } else if (tp->kids[1]) {
                 listnodes(tp->kids[0], 0, 0);
                 p = listnodes(tp->kids[1], tlab, flab);
               } else
                 p = listnodes(tp->kids[0], tlab, flab); } break;
     case JUMP:  { assert(tlab == 0 && flab == 0);
               assert(tp->u.sym == 0);
               assert(tp->kids[0]);
               l = listnodes(tp->kids[0], 0, 0);
               list(newnode(JUMP+V, l, NULL, NULL));
               reset(); } break;
     case CALL:  { Tree save = firstarg;
               firstarg = NULL;
               assert(tlab == 0 && flab == 0);
               if (tp->op == CALL+B && !IR->wants_callb) {
                 Tree arg0 = tree(ARG+P, tp->kids[1]->type,
                 tp->kids[1], NULL);
             if (IR->left_to_right)
                 firstarg = arg0;
             l = listnodes(tp->kids[0], 0, 0);
             if (!IR->left_to_right || firstarg) {
                 firstarg = NULL;
                 listnodes(arg0, 0, 0);
             }
                 p = newnode(CALL+V, l, NULL, NULL);
               } else {
                 l = listnodes(tp->kids[0], 0, 0);
                 r = listnodes(tp->kids[1], 0, 0);
                 p = newnode(tp->op == CALL+B ? tp->op : op, l, r, NULL);
               }
               NEW0(p->syms[0], FUNC);
               assert(isptr(tp->kids[0]->type));
               assert(isfunc(tp->kids[0]->type->type));
               p->syms[0]->type = tp->kids[0]->type->type;
               list(p);
               reset();
               cfunc->u.f.ncalls++;
               firstarg = save;
  } break;
     case ARG:   { assert(tlab == 0 && flab == 0);
               if (IR->left_to_right)
                 listnodes(tp->kids[1], 0, 0);
               if (firstarg) {
                 Tree arg = firstarg;
                 firstarg = NULL;
                 listnodes(arg, 0, 0);
               }
               l = listnodes(tp->kids[0], 0, 0);
               list(newnode(tp->op == ARG+B ? tp->op : op, l, NULL, NULL));
               forest->syms[0] = intconst(tp->type->size);
               forest->syms[1] = intconst(tp->type->align);
               if (!IR->left_to_right)
                 listnodes(tp->kids[1], 0, 0); } break;
     case EQ:  case NE: case GT: case GE: case LE:
     case LT:    { assert(tp->u.sym == 0);
               assert(errcnt || tlab || flab);
               l = listnodes(tp->kids[0], 0, 0);
               r = listnodes(tp->kids[1], 0, 0);
               assert(errcnt || opkind(l->op) == opkind(r->op));
               assert(errcnt || optype(op) == optype(l->op));
               if (tlab)
                 assert(flab == 0),
                 list(newnode(generic(tp->op) + opkind(l->op), l, r, findlabel(tlab)));
               else if (flab) {
                 switch (generic(tp->op)) {
                 case EQ: op = NE; break;
                 case NE: op = EQ; break;
                 case GT: op = LE; break;
                 case LT: op = GE; break;
                 case GE: op = LT; break;
                 case LE: op = GT; break;
                 default: assert(0);
                 }
                 list(newnode(op + opkind(l->op), l, r, findlabel(flab)));
               }
               if (forest && forest->syms[0])
                 forest->syms[0]->ref++; } break;
     case ASGN:  { assert(tlab == 0 && flab == 0);
               if (tp->kids[0]->op == FIELD) {
                 Tree  x = tp->kids[0]->kids[0];
             Field f = tp->kids[0]->u.field;
             assert(generic(x->op) == INDIR);
             reset();
             l = listnodes(lvalue(x), 0, 0);
             if (fieldsize(f) < 8*f->type->size) {
                 unsigned int fmask = fieldmask(f);
                 unsigned int  mask = fmask<<fieldright(f);
                 Tree q = tp->kids[1];
                 if ((q->op == CNST+I && q->u.v.i == 0)
                 ||  (q->op == CNST+U && q->u.v.u == 0))
                     q = bittree(BAND, x, cnsttree(unsignedtype, (unsigned long)~mask));
                 else if ((q->op == CNST+I && (q->u.v.i&fmask) == fmask)
                 ||       (q->op == CNST+U && (q->u.v.u&fmask) == fmask))
                     q = bittree(BOR, x, cnsttree(unsignedtype, (unsigned long)mask));
                 else {
                     listnodes(q, 0, 0);
                     q = bittree(BOR,
                         bittree(BAND, rvalue(lvalue(x)),
                             cnsttree(unsignedtype, (unsigned long)~mask)),
                         bittree(BAND, shtree(LSH, cast(q, unsignedtype),
                             cnsttree(unsignedtype, (unsigned long)fieldright(f))),
                             cnsttree(unsignedtype, (unsigned long)mask)));
                 }
                 r = listnodes(q, 0, 0);
                 op = ASGN + ttob(q->type);
             } else {
                 r = listnodes(tp->kids[1], 0, 0);
                 op = ASGN + ttob(tp->kids[1]->type);
             }
               } else {
                 l = listnodes(tp->kids[0], 0, 0);
                 r = listnodes(tp->kids[1], 0, 0);
               }
               list(newnode(tp->op == ASGN+B ? tp->op : op, l, r, NULL));
               forest->syms[0] = intconst(tp->kids[1]->type->size);
               forest->syms[1] = intconst(tp->kids[1]->type->align);
               if (isaddrop(tp->kids[0]->op)
               && !tp->kids[0]->u.sym->computed)
                 kill(tp->kids[0]->u.sym);
               else
                 reset();
               p = listnodes(tp->kids[1], 0, 0); } break;
     case BOR: case BAND: case BXOR:
     case ADD: case SUB:  case RSH:
     case LSH:   { assert(tlab == 0 && flab == 0);
               l = listnodes(tp->kids[0], 0, 0);
               r = listnodes(tp->kids[1], 0, 0);
               p = node(op, l, r, NULL); } break;
     case DIV: case MUL:
     case MOD:   { assert(tlab == 0 && flab == 0);
               l = listnodes(tp->kids[0], 0, 0);
               r = listnodes(tp->kids[1], 0, 0);
               p = node(op, l, r, NULL);
               if (IR->mulops_calls && isint(tp->type)) {
                 list(p);
                 cfunc->u.f.ncalls++;
               } } break;
     case RET:   { assert(tlab == 0 && flab == 0);
               l = listnodes(tp->kids[0], 0, 0);
               list(newnode(op, l, NULL, NULL)); } break;
     case CVF: case CVI: case CVP:
     case CVU:   { assert(tlab == 0 && flab == 0);
               assert(optype(tp->kids[0]->op) != optype(tp->op) || tp->kids[0]->type->size != tp->type->size);
               l = listnodes(tp->kids[0], 0, 0);
               p = node(op, l, NULL, intconst(tp->kids[0]->type->size));
  } break;
     case BCOM:
     case NEG:   { assert(tlab == 0 && flab == 0);
               l = listnodes(tp->kids[0], 0, 0);
               p = node(op, l, NULL, NULL); } break;
     case INDIR: { Type ty = tp->kids[0]->type;
               assert(tlab == 0 && flab == 0);
               l = listnodes(tp->kids[0], 0, 0);
               if (isptr(ty))
                 ty = unqual(ty)->type;
               if (isvolatile(ty)
               || (isstruct(ty) && unqual(ty)->u.sym->u.s.vfields))
                 p = newnode(tp->op == INDIR+B ? tp->op : op, l, NULL, NULL);
               else
                 p = node(tp->op == INDIR+B ? tp->op : op, l, NULL, NULL); } break;
     case FIELD: { Tree q = tp->kids[0];
               if (tp->type == inttype) {
                 long n = fieldleft(tp->u.field);
                 q = shtree(RSH,
                     shtree(LSH, q, cnsttree(inttype, n)),
                     cnsttree(inttype, n + fieldright(tp->u.field)));
               } else if (fieldsize(tp->u.field) < 8*tp->u.field->type->size)
                 q = bittree(BAND,
                     shtree(RSH, q, cnsttree(inttype, (long)fieldright(tp->u.field))),
                     cnsttree(unsignedtype, (unsigned long)fieldmask(tp->u.field)));
               assert(tlab == 0 && flab == 0);
               p = listnodes(q, 0, 0); } break;
     case ADDRG:
     case ADDRF: { assert(tlab == 0 && flab == 0);
               p = node(tp->op + sizeop(voidptype->size), NULL, NULL, tp->u.sym);
  } break;
     case ADDRL: { assert(tlab == 0 && flab == 0);
               if (tp->u.sym->temporary)
                 addlocal(tp->u.sym);
               p = node(tp->op + sizeop(voidptype->size), NULL, NULL, tp->u.sym); } break;
     default:assert(0);
     }
     tp->node = p;
     return p;
 }
References ADD, addlocal(), AND, ASGN, assert, B, bittree, CALL, cast(), cfunc, cnsttree(), COND, constant(), cvtconst(), DIV, EQ, equatelab(), errcnt, FIELD, fieldleft, fieldmask, fieldright, fieldsize, findlabel(), firstarg, forest, FUNC, genlabel(), GT, I, idtree(), intconst(), inttype, IR, isaddrop, isfunc, isint, isptr, isstruct, isvolatile, jump(), kill(), labelnode(), list(), LSH, LT, lvalue(), MOD, NEW0, newnode(), node(), NOT, NULL, op, opkind, optype, OR, P, reset(), RIGHT, RSH, rvalue(), shtree(), sizeop, SUB, tree(), ttob(), U, unlist(), unqual, unsignedtype, V, and voidptype.
Referenced by cmp(), definept(), statement(), and walk().
locus()
void locus (Table tp, Coordinate * cp)
Definition at line 239 of file sym.c.
{
     loci    = append(cp, loci);
     symbols = append(allsymbols(tp), symbols);
 }
References allsymbols(), append(), cp, loci, and symbols.
Referenced by definept().
lookup()
Symbol lookup (const char * , Table)
Definition at line 127 of file sym.c.
{
     struct entry *p;
     unsigned h = (unsigned long)name&(HASHSIZE-1);
     assert(tp);
     do
         for (p = tp->buckets[h]; p; p = p->link)
             if (name == p->sym.name)
                 return &p->sym;
     while ((tp = tp->previous) != NULL);
     return NULL;
 }
References assert, HASHSIZE, long(), and NULL.
ltov()
void* ltov (List * list, unsigned a)
Definition at line 37 of file list.c.
{
     int i = 0;
     void **array = newarray(length(*list) + 1, sizeof array[0], arena);
     if (*list) {
         List lp = *list;
         do {
             lp = lp->link;
             array[i++] = lp->x;
         } while (lp != *list);
 #ifndef PURIFY
         lp = (*list)->link;
         (*list)->link = freenodes;
         freenodes = lp;
 #endif
     }
     *list = NULL;
     array[i] = NULL;
     return array;
 }
References arena, array(), freenodes, length(), list(), newarray(), and NULL.
Referenced by bbvars(), compose(), compound(), enumdcl(), ftype(), main(), parameters(), and printproto().
lvalue()
Tree lvalue (Tree)
Definition at line 455 of file expr.c.
                     {
     if (generic(p->op) != INDIR) {
         error("lvalue required\n");
         return value(p);
     } else if (unqual(p->type) == voidtype)
         warning("`%t' used as an lvalue\n", p->type);
     return p->kids[0];
 }
References error(), unqual, value(), voidtype, and warning().
Referenced by asgntree(), call(), listnodes(), and unary().
main()
int main (int , char * [])
Definition at line 78 of file lcc.c.
{
     int i, j, nf;
     progname = argv[0];
     UpdatePaths( progname );
     ac = argc + 50;
     av = alloc(ac*sizeof(char *));
     if (signal(SIGINT, SIG_IGN) != SIG_IGN)
         signal(SIGINT, interrupt);
     if (signal(SIGTERM, SIG_IGN) != SIG_IGN)
         signal(SIGTERM, interrupt);
 #ifdef SIGHUP
     if (signal(SIGHUP, SIG_IGN) != SIG_IGN)
         signal(SIGHUP, interrupt);
 #endif
     if (getenv("TMP"))
         tempdir = getenv("TMP");
     else if (getenv("TEMP"))
         tempdir = getenv("TEMP");
     else if (getenv("TMPDIR"))
         tempdir = getenv("TMPDIR");
     assert(tempdir);
     i = strlen(tempdir);
     for (; (i > 0 && tempdir[i-1] == '/') || tempdir[i-1] == '\\'; i--)
         tempdir[i-1] = '\0';
     if (argc <= 1) {
         help();
         exit(0);
     }
     plist = append("-D__LCC__", 0);
     initinputs();
     if (getenv("LCCDIR"))
         option(stringf("-lccdir=%s", getenv("LCCDIR")));
     for (nf = 0, i = j = 1; i < argc; i++) {
         if (strcmp(argv[i], "-o") == 0) {
             if (++i < argc) {
                 if (suffix(argv[i], suffixes, 2) >= 0) {
                     error("-o would overwrite %s", argv[i]);
                     exit(8);
                 }
                 outfile = argv[i];
                 continue;
             } else {
                 error("unrecognized option `%s'", argv[i-1]);
                 exit(8);
             }
         } else if (strcmp(argv[i], "-target") == 0) {
             if (argv[i+1] && *argv[i+1] != '-')
                 i++;
             continue;
         } else if (*argv[i] == '-' && argv[i][1] != 'l') {
             opt(argv[i]);
             continue;
         } else if (*argv[i] != '-' && suffix(argv[i], suffixes, 3) >= 0)
             nf++;
         argv[j++] = argv[i];
     }
     if ((cflag || Sflag) && outfile && nf != 1) {
         fprintf(stderr, "%s: -o %s ignored\n", progname, outfile);
         outfile = 0;
     }
     argv[j] = 0;
     for (i = 0; include[i]; i++)
         plist = append(include[i], plist);
     if (ilist) {
         List b = ilist;
         do {
             b = b->link;
             plist = append(b->str, plist);
         } while (b != ilist);
     }
     ilist = 0;
     for (i = 1; argv[i]; i++)
         if (*argv[i] == '-')
             opt(argv[i]);
         else {
             char *name = exists(argv[i]);
             if (name) {
                 if (strcmp(name, argv[i]) != 0
                 || (nf > 1 && suffix(name, suffixes, 3) >= 0))
                     fprintf(stderr, "%s:\n", name);
                 filename(name, 0);
             } else
                 error("can't find `%s'", argv[i]);
         }
     if (errcnt == 0 && !Eflag && !Sflag && !cflag && llist[1]) {
         compose(ld, llist[0], llist[1],
             append(outfile ? outfile : concat("a", first(suffixes[4])), 0));
         if (callsys(av))
             errcnt++;
     }
     rm(rmlist);
     return errcnt ? EXIT_FAILURE : EXIT_SUCCESS;
 }
References ac, alloc(), append(), apply(), assert, av, bindings, callsys(), cflag, CheckParm(), ckreach(), compose(), concat(), config, deallocate(), zSkel_Config_t::debug, DoAnims(), DoMeshes(), Eflag, emitclosure(), emitdefs(), emitheader(), emitkids(), emitlabel(), emitnts(), emitrule(), emitstring(), emitstruct(), Events::end, EOF, errcnt, error(), events, exists(), exit(), EXIT_FAILURE, EXIT_SUCCESS, feof(), filename(), finalize(), first(), firstfile, fopen(), fprint(), fprintf(), free(), getc(), getenv(), gettok(), glevel, GLOBAL, help(), identifiers, ilist, include, infp, init(), initinputs(), interrupt(), IR, ld, lineno, block::link, llist, LoadCFG(), LoadCFG_Print(), loci, ltov(), memlist, memset(), myargc, myargv, nrules, ntnumber, nts, NULL, zSkel_Config_t::numAnims, zSkel_Config_t::numMeshes, opt(), option(), outfile, outfp, PERM, plist, prefix, printf(), PrintUsage(), progname, putc(), rm(), rmlist, rules, Sflag, SIG_IGN, SIGINT, signal(), SIGTERM, SMD2MD4_VERSION, stderr, stdin, stdout, strchr(), strcmp(), stringf(), strlen(), strncmp(), suffix(), suffixes, symbols, tempdir, terms, Tflag, types, typestab(), UpdatePaths(), xref, yyerror, yyparse, and ZSKEL_VERSION.
main_init()
void main_init (int , char * [])
Definition at line 80 of file main.c.
{
     char *infile = NULL, *outfile = NULL;
     int i;
     static int inited;
     if (inited)
         return;
     inited = 1;
     type_init(argc, argv);
     for (i = 1; i < argc; i++)
         if (strcmp(argv[i], "-g") == 0 || strcmp(argv[i], "-g2") == 0)
             glevel = 2;
         else if (strncmp(argv[i], "-g", 2) == 0) {  /* -gn[,x] */
             char *p = strchr(argv[i], ',');
             glevel = atoi(argv[i]+2);
             if (p) {
                 comment = p + 1;
                 if (glevel == 0)
                     glevel = 1;
                 if (stabIR.stabline == NULL) {
                     stabIR.stabline = IR->stabline;
                     stabIR.stabend = IR->stabend;
                     IR->stabline = stabline;
                     IR->stabend = stabend;
                 }
             }
         } else if (strcmp(argv[i], "-x") == 0)
             xref++;
         else if (strcmp(argv[i], "-A") == 0) {
             ++Aflag;
         } else if (strcmp(argv[i], "-P") == 0)
             Pflag++;
         else if (strcmp(argv[i], "-w") == 0)
             wflag++;
         else if (strcmp(argv[i], "-n") == 0) {
             if (!YYnull) {
                 YYnull = install(string("_YYnull"), &globals, GLOBAL, PERM);
                 YYnull->type = func(voidptype, NULL, 1);
                 YYnull->sclass = EXTERN;
                 (*IR->defsymbol)(YYnull);
             }
         } else if (strncmp(argv[i], "-n", 2) == 0) {    /* -nvalid[,check] */
             char *p = strchr(argv[i], ',');
             if (p) {
                 YYcheck = install(string(p+1), &globals, GLOBAL, PERM);
                 YYcheck->type = func(voidptype, NULL, 1);
                 YYcheck->sclass = EXTERN;
                 (*IR->defsymbol)(YYcheck);
                 p = stringn(argv[i]+2, p - (argv[i]+2));
             } else
                 p = string(argv[i]+2);
             YYnull = install(p, &globals, GLOBAL, PERM);
             YYnull->type = func(voidptype, NULL, 1);
             YYnull->sclass = EXTERN;
             (*IR->defsymbol)(YYnull);
         } else if (strcmp(argv[i], "-v") == 0)
             fprint(stderr, "%s %s\n", argv[0], rcsid);
         else if (strncmp(argv[i], "-s", 2) == 0)
             density = strtod(&argv[i][2], NULL);
         else if (strncmp(argv[i], "-errout=", 8) == 0) {
             FILE *f = fopen(argv[i]+8, "w");
             if (f == NULL) {
                 fprint(stderr, "%s: can't write errors to `%s'\n", argv[0], argv[i]+8);
                 exit(EXIT_FAILURE);
             }
             fclose(f);
             f = freopen(argv[i]+8, "w", stderr);
             assert(f);
         } else if (strncmp(argv[i], "-e", 2) == 0) {
             int x;
             if ((x = strtol(&argv[i][2], NULL, 0)) > 0)
                 errlimit = x;
         } else if (strncmp(argv[i], "-little_endian=", 15) == 0)
             IR->little_endian = argv[i][15] - '0';
         else if (strncmp(argv[i], "-mulops_calls=", 18) == 0)
             IR->mulops_calls = argv[i][18] - '0';
         else if (strncmp(argv[i], "-wants_callb=", 13) == 0)
             IR->wants_callb = argv[i][13] - '0';
         else if (strncmp(argv[i], "-wants_argb=", 12) == 0)
             IR->wants_argb = argv[i][12] - '0';
         else if (strncmp(argv[i], "-left_to_right=", 15) == 0)
             IR->left_to_right = argv[i][15] - '0';
         else if (strncmp(argv[i], "-wants_dag=", 11) == 0)
             IR->wants_dag = argv[i][11] - '0';
         else if (*argv[i] != '-' || strcmp(argv[i], "-") == 0) {
             if (infile == NULL)
                 infile = argv[i];
             else if (outfile == NULL)
                 outfile = argv[i];
         }
     if (infile != NULL && strcmp(infile, "-") != 0
     && freopen(infile, "r", stdin) == NULL) {
         fprint(stderr, "%s: can't read `%s'\n", argv[0], infile);
         exit(EXIT_FAILURE);
     }
     if (outfile != NULL && strcmp(outfile, "-") != 0
     && freopen(outfile, "w", stdout) == NULL) {
         fprint(stderr, "%s: can't write `%s'\n", argv[0], outfile);
         exit(EXIT_FAILURE);
     }
 }
References Aflag, assert, atoi(), comment, density, errlimit, exit(), EXIT_FAILURE, EXTERN, fclose(), fopen(), fprint(), freopen(), func(), glevel, GLOBAL, globals, infile, install(), IR, NULL, outfile, PERM, Pflag, rcsid, stabend(), stabIR, stabline(), stderr, stdin, stdout, strchr(), strcmp(), stringn(), strncmp(), strtod(), strtol(), type_init(), voidptype, wflag, xref, YYcheck, and YYnull.
Referenced by init(), and input_init().
mkstr()
Symbol mkstr (char *)
Definition at line 268 of file sym.c.
{
     Value v;
     Symbol p;
     v.p = str;
     p = constant(array(chartype, strlen(v.p) + 1, 0), v);
     if (p->u.c.loc == NULL)
         p->u.c.loc = genident(STATIC, p->type, GLOBAL);
     return p;
 }
References array(), chartype, constant(), genident(), GLOBAL, NULL, STATIC, and strlen().
Referenced by bbcall(), bbfile(), bbfunc(), nullcall(), nullcheck(), tracefinis(), and tracevalue().
mksymbol()
Symbol mksymbol (int , const char * , Type)
Definition at line 280 of file sym.c.
{
     Symbol p;
     if (sclass == EXTERN)
         p = install(string(name), &globals, GLOBAL, PERM);
     else {
         NEW0(p, PERM);
         p->name = string(name);
         p->scope = GLOBAL;
     }
     p->sclass = sclass;
     p->type = ty;
     (*IR->defsymbol)(p);
     p->defined = 1;
     return p;
 }
References EXTERN, GLOBAL, globals, install(), IR, NEW0, and PERM.
Referenced by bbcall(), bbentry(), bbexit(), and trace_init().
newarray()
void* newarray (unsigned long m, unsigned long n, unsigned a)
Definition at line 84 of file alloc.c.
{
     return allocate(m*n, a);
 }
References allocate(), and m.
Referenced by apoint(), caselabel(), funcdefn(), ltov(), parameters(), swgen(), and swstmt().
newfield()
Field newfield (char * , Type , Type)
Definition at line 292 of file types.c.
{
     Field p, *q = &ty->u.sym->u.s.flist;
     if (name == NULL)
         name = stringd(genlabel(1));
     for (p = *q; p; q = &p->link, p = *q)
         if (p->name == name)
             error("duplicate field name `%s' in `%t'\n",
                 name, ty);
     NEW0(p, PERM);
     *q = p;
     p->name = name;
     p->type = fty;
     if (xref) {                         /* omit */
         if (ty->u.sym->u.s.ftab == NULL)            /* omit */
             ty->u.sym->u.s.ftab = table(NULL, level);   /* omit */
         install(name, &ty->u.sym->u.s.ftab, 0, PERM)->src = src;/* omit */
     }                               /* omit */
     return p;
 }
References error(), genlabel(), install(), NEW0, NULL, PERM, stringd(), and xref.
Referenced by fields().
newnode()
Node newnode (int op, Node left, Node right, Symbol p)
Definition at line 79 of file dag.c.
{
     return &dagnode(op, l, r, sym)->node;
 }
References dagnode(), dag::node, and op.
Referenced by asgnnode(), definelab(), genreload(), genspill(), jump(), labelnode(), listnodes(), replace(), rtarget(), tmpnode(), and visit().
newstruct()
Type newstruct (int , char *)
Definition at line 271 of file types.c.
{
     Symbol p;
     assert(tag);
     if (*tag == 0)
         tag = stringd(genlabel(1));
     else
         if ((p = lookup(tag, types)) != NULL && (p->scope == level
         || (p->scope == PARAM && level == PARAM+1))) {
             if (p->type->op == op && !p->defined)
                 return p->type;
             error("redefinition of `%s' previously defined at %w\n",
                 p->name, &p->src);
         }
     p = install(tag, &types, level, PERM);
     p->type = type(op, NULL, 0, 0, p);
     if (p->scope > maxlevel)
         maxlevel = p->scope;
     p->src = src;
     return p->type;
 }
References assert, error(), genlabel(), install(), lookup(), maxlevel, NULL, op, PARAM, PERM, stringd(), type(), and types.
Referenced by enumdcl(), and structdcl().
newtemp()
Symbol newtemp (int , int , int)
Definition at line 227 of file sym.c.
{
     Symbol p = temporary(sclass, btot(tc, size));
     (*IR->local)(p);
     p->defined = 1;
     return p;
 }
References btot(), IR, and temporary().
Referenced by spillr().
nextline()
void nextline (void)
Definition at line 16 of file input.c.
                     {
     do {
         if (cp >= limit) {
             fillbuf();
             if (cp >= limit)
                 cp = limit;
             if (cp == limit)
                 return;
         } else {
             lineno++;
             for (line = (char *)cp; *cp==' ' || *cp=='\t'; cp++)
                 ;
             if (*cp == '#') {
                 resynch();
                 nextline();
             }
         }
     } while (*cp == '\n' && cp == limit);
 }
References cp, fillbuf(), limit, line, lineno, and resynch().
Referenced by getchr(), gettok(), input_init(), resynch(), and scon().
nodeid()
int nodeid (Tree)
Definition at line 172 of file tree.c.
                    {
     int i = 1;
     ids[nid].node = p;
     while (ids[i].node != p)
         i++;
     if (i == nid)
         ids[nid++].printed = 0;
     return i;
 }
References nid.
Referenced by printdag(), printdag1(), printnode(), and printtree1().
nullcall()
Tree nullcall (Type , Symbol , Tree , Tree)
Definition at line 700 of file expr.c.
{
     Type ty;
     if (isarray(pty))
         return retype(nullcall(atop(pty), f, p, e), pty);
     ty = unqual(unqual(p->type)->type);
     return vcall(f, pty,
         p, e,
         cnsttree(inttype, (long)ty->size),
         cnsttree(inttype, (long)ty->align),
         (file && *file ? pointer(idtree(mkstr(file)->u.c.loc)) : cnsttree(voidptype, NULL)), cnsttree(inttype, (long)lineno)        , NULL);
 }
References atop(), cnsttree(), idtree(), inttype, isarray, lineno, mkstr(), NULL, retype(), unqual, vcall(), and voidptype.
Referenced by addtree(), field(), and nullcheck().
opname()
char* opname (int)
Definition at line 113 of file tree.c.
                      {
     static char *opnames[] = {
     "",
     "CNST",
     "ARG",
     "ASGN",
     "INDIR",
     "CVC",
     "CVD",
     "CVF",
     "CVI",
     "CVP",
     "CVS",
     "CVU",
     "NEG",
     "CALL",
     "*LOAD*",
     "RET",
     "ADDRG",
     "ADDRF",
     "ADDRL",
     "ADD",
     "SUB",
     "LSH",
     "MOD",
     "RSH",
     "BAND",
     "BCOM",
     "BOR",
     "BXOR",
     "DIV",
     "MUL",
     "EQ",
     "GE",
     "GT",
     "LE",
     "LT",
     "NE",
     "JUMP",
     "LABEL",
     "AND",
     "NOT",
     "OR",
     "COND",
     "RIGHT",
     "FIELD"
     }, *suffixes[] = {
         "0", "F", "D", "C", "S", "I", "U", "P", "V", "B",
         "10","11","12","13","14","15"
     };
     if (generic(op) >= AND && generic(op) <= FIELD && opsize(op) == 0)
         return opnames[opindex(op)];
     return stringf("%s%s%s",
         opindex(op) > 0 && opindex(op) < NELEMS(opnames) ?
             opnames[opindex(op)] : stringd(opindex(op)),
         suffixes[optype(op)], opsize(op) > 0 ? stringd(opsize(op)) : "");
 }
References AND, FIELD, NELEMS, op, opindex, opnames, opsize, optype, stringd(), stringf(), and suffixes.
Referenced by dumptree(), emit(), getrule(), printnode(), and printtree1().
outtype()
void outtype (Type , FILE *)
Definition at line 532 of file types.c.
{
     switch (ty->op) {
     case CONST+VOLATILE: case CONST: case VOLATILE:
         fprint(f, "%k %t", ty->op, ty->type);
         break;
     case STRUCT: case UNION: case ENUM:
         assert(ty->u.sym);
         if (ty->size == 0)
             fprint(f, "incomplete ");
         assert(ty->u.sym->name);
         if (*ty->u.sym->name >= '1' && *ty->u.sym->name <= '9') {
             Symbol p = findtype(ty);
             if (p == 0)
                 fprint(f, "%k defined at %w", ty->op, &ty->u.sym->src);
             else
                 fprint(f, p->name);
         } else {
             fprint(f, "%k %s", ty->op, ty->u.sym->name);
             if (ty->size == 0)
                 fprint(f, " defined at %w", &ty->u.sym->src);
         }
         break;
     case VOID: case FLOAT: case INT: case UNSIGNED:
         fprint(f, ty->u.sym->name);
         break;
     case POINTER:
         fprint(f, "pointer to %t", ty->type);
         break;
     case FUNCTION:
         fprint(f, "%t function", ty->type);
         if (ty->u.f.proto && ty->u.f.proto[0]) {
             int i;
             fprint(f, "(%t", ty->u.f.proto[0]);
             for (i = 1; ty->u.f.proto[i]; i++)
                 if (ty->u.f.proto[i] == voidtype)
                     fprint(f, ",...");
                 else
                     fprint(f, ",%t", ty->u.f.proto[i]);
             fprint(f, ")");
         } else if (ty->u.f.proto && ty->u.f.proto[0] == 0)
             fprint(f, "(void)");
         break;
     case ARRAY:
         if (ty->size > 0 && ty->type && ty->type->size > 0) {
             fprint(f, "array %d", ty->size/ty->type->size);
             while (ty->type && isarray(ty->type) && ty->type->type->size > 0) {
                 ty = ty->type;
                 fprint(f, ",%d", ty->size/ty->type->size);
             }
         } else
             fprint(f, "incomplete array");
         if (ty->type)
             fprint(f, " of %t", ty->type);
         break;
     default: assert(0);
     }
 }
References assert, CONST, findtype(), fprint(), INT, isarray, VOID(), voidtype, and VOLATILE.
Referenced by vfprint().
pointer()
Tree pointer (Tree)
Definition at line 513 of file expr.c.
                      {
     if (isarray(p->type))
         /* assert(p->op != RIGHT || p->u.sym == NULL), */
         p = retype(p, atop(p->type));
     else if (isfunc(p->type))
         p = retype(p, ptr(p->type));
     return p;
 }
References atop(), isarray, isfunc, ptr(), and retype().
Referenced by cond(), expr(), expr2(), expr3(), nullcheck(), postfix(), and unary().
print()
void print (const char * , ...)
Definition at line 39 of file output.c.
{
     va_list ap;
     va_start(ap, fmt);
     vfprint(stdout, NULL, fmt, ap);
     va_end(ap);
 }
References fmt, NULL, stdout, va_end, va_start, and vfprint().
printdag()
void printdag (Node , int)
Definition at line 679 of file dag.c.
{
     FILE *f = fd == 1 ? stdout : stderr;
     printed(0);
     if (p == 0) {
         if ((p = forest) != NULL)
             do {
                 p = p->link;
                 printdag1(p, fd, 0);
             } while (p != forest);
     } else if (*printed(nodeid((Tree)p)))
         fprint(f, "node'%d printed above\n", nodeid((Tree)p));
     else
         printdag1(p, fd, 0);
 }
References forest, fprint(), nodeid(), NULL, printdag1(), printed(), stderr, and stdout.
printdecl()
void printdecl (Symbol p, Type ty)
Definition at line 592 of file types.c.
{
     switch (p->sclass) {
     case AUTO:
         fprint(stderr, "%s;\n", typestring(ty, p->name));
         break;
     case STATIC: case EXTERN:
         fprint(stderr, "%k %s;\n", p->sclass, typestring(ty, p->name));
         break;
     case TYPEDEF: case ENUM:
         break;
     default: assert(0);
     }
 }
References assert, EXTERN, fprint(), STATIC, stderr, and typestring().
Referenced by doglobal(), and printproto().
printed()
int* printed (int)
Definition at line 184 of file tree.c.
                      {
     if (id)
         return &ids[id].printed;
     nid = 1;
     return 0;
 }
References nid.
Referenced by opt(), printdag(), printdag1(), printtree(), and printtree1().
printproto()
void printproto (Symbol p, Symbol args[])
Definition at line 607 of file types.c.
{
     if (p->type->u.f.proto)
         printdecl(p, p->type);
     else {
         int i;
         List list = 0;
         if (callee[0] == 0)
             list = append(voidtype, list);
         else
             for (i = 0; callee[i]; i++)
                 list = append(callee[i]->type, list);
         printdecl(p, func(freturn(p->type), ltov(&list, PERM), 0));
     }
 }
References append(), freturn(), func(), ltov(), PERM, printdecl(), and voidtype.
Referenced by funcdefn().
printtree()
void printtree (Tree , int)
Definition at line 192 of file tree.c.
{
     (void)printed(0);
     printtree1(p, fd, 1);
 }
References printed(), printtree1(), and void().
printtype()
void printtype (Type , int)
Definition at line 684 of file types.c.
{
     static unsigned mark;
     prtype(ty, fd == 1 ? stdout : stderr, 0, ++mark);
     fprint(fd == 1 ? stdout : stderr, "\n");
 }
References fprint(), prtype(), stderr, and stdout.
process()
int process (char *)
Definition at line 258 of file profio.c.
{
     int more;
     if ((fp = fopen(file, "r")) != NULL) {
         struct file *p;
         while ((more = gather()) > 0)
             ;
         fclose(fp);
         if (more < 0)
             return more;
         for (p = filelist; p; p = p->link)
             qsort(p->counts, p->count, sizeof *p->counts,
                 (int (*)(const void *, const void *))
                 compare);
         return 1;
     }
     return 0;
 }
References compare(), fclose(), filelist, fopen(), fp, gather(), int, NULL, and qsort().
program()
void program (void)
Definition at line 32 of file decl.c.
                    {
     int n;
     level = GLOBAL;
     for (n = 0; t != EOI; n++)
         if (kind[t] == CHAR || kind[t] == STATIC
         || t == ID || t == '*' || t == '(') {
             decl(dclglobal);
             deallocate(STMT);
             if (!(glevel >= 3 || xref))
             deallocate(FUNC);
         } else if (t == ';') {
             warning("empty declaration\n");
             t = gettok();
         } else {
             error("unrecognized declaration\n");
             t = gettok();
         }
     if (n == 0)
         warning("empty input file\n");
 }
References dclglobal(), deallocate(), decl(), error(), FUNC, gettok(), glevel, GLOBAL, ID, kind, STATIC, STMT, warning(), and xref.
promote()
Type promote (Type)
Definition at line 358 of file types.c.
                       {
     ty = unqual(ty);
     switch (ty->op) {
     case ENUM:
         return inttype;
     case INT:
         if (ty->size < inttype->size)
             return inttype;
         break;
     case UNSIGNED:
         if (ty->size < inttype->size)
             return inttype;
         if (ty->size < unsignedtype->size)
             return unsignedtype;
         break;
     case FLOAT:
         if (ty->size < doubletype->size)
             return doubletype;
     }
     return ty;
 }
References doubletype, INT, inttype, unqual, and unsignedtype.
Referenced by addtree(), call(), calltree(), eqtype(), funcdefn(), retcode(), shtree(), subtree(), swstmt(), tracevalue(), and unary().
ptr()
Type ptr (Type)
Definition at line 191 of file types.c.
                   {
     return type(POINTER, ty, IR->ptrmetric.size,
         IR->ptrmetric.align, pointersym);
 }
References IR, pointersym, and type().
Referenced by access_virt_barray(), access_virt_sarray(), ArenaServers_Event(), Assemble(), atop(), bbcall(), call(), Camera_MenuEvent(), CG_DrawField(), CG_HeadModelVoiceChats(), CG_ParseVoiceChats(), CG_ServerCommand(), Com_Filter(), Com_QueueEvent(), compose(), compound(), condtree(), ConfirmMenu_Event(), Controls_ActionEvent(), Controls_MenuEvent(), create_colormap(), dclparam(), dclr(), do_barray_io(), do_sarray_io(), DoSyscall(), EmitPtr(), expand_right_edge(), field(), funcdefn(), GLimp_HaveExtension(), idtree(), InGame_Event(), jitter_buffer_ctl(), jzero_far(), lsp_quant(), lsp_weight_quant(), Main_MenuEvent(), Menu_SetCursorToItem(), Music_MenuEvent(), nb_decoder_ctl(), nb_encoder_ctl(), nb_mode_query(), Options_Event(), pitch_gain_search_3tap_vq(), PlayerModel_MenuEvent(), PlayerModel_PicEvent(), pointer(), postfix(), Preferences_Event(), prescan_quantize(), R_Init(), RB_IQMSurfaceAnim(), resampler_basic_direct_double(), resampler_basic_direct_single(), resampler_basic_interpolate_double(), resampler_basic_interpolate_single(), sb_decoder_ctl(), sb_encoder_ctl(), ServerInfo_Event(), speex_decoder_ctl(), speex_echo_ctl(), speex_encoder_ctl(), speex_free(), speex_free_scratch(), speex_header_free(), speex_lib_ctl(), speex_mode_query(), speex_preprocess_ctl(), speex_realloc(), StartServer_MapEvent(), StartServer_MenuEvent(), SystemSettings_Event(), TeamMain_MenuEvent(), trace_init(), type_init(), unary(), VM_CallCompiled(), wb_mode_query(), Z_Free(), Z_LogZoneHeap(), and zcfree().
qual()
Type qual (int , Type)
Definition at line 230 of file types.c.
{
     if (isarray(ty))
         ty = type(ARRAY, qual(op, ty->type), ty->size,
             ty->align, NULL);
     else if (isfunc(ty))
         warning("qualified function type ignored\n");
     else if ((isconst(ty)    && op == CONST)
     ||       (isvolatile(ty) && op == VOLATILE))
         error("illegal type `%k %t'\n", op, ty);
     else {
         if (isqual(ty)) {
             op += ty->op;
             ty = ty->type;
         }
         ty = type(op, ty, ty->size, ty->align, NULL);
     }
     return ty;
 }
References CONST, error(), isarray, isconst, isfunc, isqual, isvolatile, NULL, op, type(), VOLATILE, and warning().
Referenced by compose(), condtree(), dcllocal(), dclr(), field(), sb_encoder_ctl(), specifier(), speex_std_vbr_quality_request_handler(), trace_init(), unary(), and vbr_analysis().
reachable()
int reachable (int)
Definition at line 39 of file stmt.c.
{
     if (kind > Start) {
         Code cp;
         for (cp = codelist; cp->kind < Label; )
             cp = cp->prev;
         if (cp->kind == Jump || cp->kind == Switch)
             return 0;
     }
     return 1;
 }
References codelist, cp, if(), Code::Jump, kind, Code::Label, Code::Start, and Code::Switch.
Referenced by code(), compound(), and definept().
relocate()
Symbol relocate (const char * name, Table src, Table dst)
Definition at line 97 of file sym.c.
{
     struct entry *p, **q;
     Symbol *r;
     unsigned h = (unsigned long)name&(HASHSIZE-1);
     for (q = &src->buckets[h]; *q; q = &(*q)->link)
         if (name == (*q)->sym.name)
             break;
     assert(*q);
     /*
      Remove the entry from src's hash chain
       and from its list of all symbols.
     */
     p = *q;
     *q = (*q)->link;
     for (r = &src->all; *r && *r != &p->sym; r = &(*r)->up)
         ;
     assert(*r == &p->sym);
     *r = p->sym.up;
     /*
      Insert the entry into dst's hash chain
       and into its list of all symbols.
       Return the symbol-table entry.
     */
     p->link = dst->buckets[h];
     dst->buckets[h] = p;
     p->sym.up = dst->all;
     dst->all = &p->sym;
     return &p->sym;
 }
References assert, HASHSIZE, and long().
Referenced by dclglobal().
retcode()
void retcode (Tree)
Definition at line 481 of file stmt.c.
                      {
     Type ty;
     if (p == NULL) {
         if (events.returns)
             apply(events.returns, cfunc, NULL);
         return;
     }
     p = pointer(p);
     ty = assign(freturn(cfunc->type), p);
     if (ty == NULL) {
         error("illegal return type; found `%t' expected `%t'\n",
             p->type, freturn(cfunc->type));
         return;
     }
     p = cast(p, ty);
     if (retv)
         {
             if (iscallb(p))
                 p = tree(RIGHT, p->type,
                     tree(CALL+B, p->type,
                         p->kids[0]->kids[0], idtree(retv)),
                     rvalue(idtree(retv)));
             else
                 p = asgntree(ASGN, rvalue(idtree(retv)), p);
             walk(p, 0, 0);
             if (events.returns)
                 apply(events.returns, cfunc, rvalue(idtree(retv)));
             return;
         }
     if (events.returns)
         {
             Symbol t1 = genident(AUTO, p->type, level);
             addlocal(t1);
             walk(asgn(t1, p), 0, 0);
             apply(events.returns, cfunc, idtree(t1));
             p = idtree(t1);
         }
     if (!isfloat(p->type))
         p = cast(p, promote(p->type));
     if (isptr(p->type))
         {
             Symbol q = localaddr(p);
             if (q && (q->computed || q->generated))
                 warning("pointer to a %s is an illegal return value\n",
                     q->scope == PARAM ? "parameter" : "local");
             else if (q)
                 warning("pointer to %s `%s' is an illegal return value\n",
                     q->scope == PARAM ? "parameter" : "local", q->name);
         }
     walk(tree(mkop(RET,p->type), p->type, p, NULL), 0, 0);
 }
References addlocal(), apply(), ASGN, asgn(), asgntree, assign(), B, CALL, cast(), cfunc, error(), events, freturn(), genident(), idtree(), iscallb(), isfloat, isptr, localaddr(), mkop, NULL, PARAM, promote(), Events::returns, retv, RIGHT, rvalue(), tree(), walk(), and warning().
Referenced by funcdefn(), jpeg_consume_input(), jpeg_read_header(), and statement().
retype()
Tree retype (Tree p, Type ty)
Definition at line 463 of file expr.c.
{
     Tree q;
     if (p->type == ty)
         return p;
     q = tree(p->op, ty, p->kids[0], p->kids[1]);
     q->node = p->node;
     q->u = p->u;
     return q;
 }
References tree().
Referenced by asgntree(), cast(), field(), initvalue(), nullcall(), pointer(), postfix(), simplify(), swstmt(), tracevalue(), and unary().
rightkid()
Tree rightkid (Tree p)
Definition at line 473 of file expr.c.
                       {
     while (p && p->op == RIGHT)
         if (p->kids[1])
             p = p->kids[1];
         else if (p->kids[0])
             p = p->kids[0];
         else
             assert(0);
     assert(p);
     return p;
 }
References assert, and RIGHT.
Referenced by cond(), postfix(), unary(), and value().
rmtypes()
void rmtypes (int)
Definition at line 171 of file types.c.
                       {
     if (maxlevel >= lev) {
         int i;
         maxlevel = 0;
         for (i = 0; i < NELEMS(typetable); i++) {
             struct entry *tn, **tq = &typetable[i];
             while ((tn = *tq) != NULL)
                 if (tn->type.op == FUNCTION)
                     tq = &tn->link;
                 else if (tn->type.u.sym && tn->type.u.sym->scope >= lev)
                     *tq = tn->link;
                 else {
                     if (tn->type.u.sym && tn->type.u.sym->scope > maxlevel)
                         maxlevel = tn->type.u.sym->scope;
                     tq = &tn->link;
                 }
         }
     }
 }
References entry::link, maxlevel, NELEMS, NULL, Type::op, Type::sym, entry::type, typetable, and Type::u.
Referenced by exitscope().
root()
Tree root (Tree)
Definition at line 108 of file tree.c.
                   {
     warn = 0;
     return root1(p);
 }
References root1(), and warn.
Referenced by _GLIBCXX_VISIBILITY(), addrof(), call(), condtree(), dcllocal(), emitrecalc(), expr(), expr0(), inflate_table(), PSys_UpdateEmitters(), and simplify().
rvalue()
Tree rvalue (Tree)
Definition at line 449 of file expr.c.
                     {
     Type ty = deref(p->type);
     ty = unqual(ty);
     return tree(mkop(INDIR,ty), ty, p, NULL);
 }
References deref(), mkop, NULL, tree(), and unqual.
Referenced by bbincr(), field(), idtree(), listnodes(), postfix(), retcode(), swcode(), tracevalue(), and unary().
shtree()
Tree shtree (int , Tree , Tree)
Definition at line 471 of file enode.c.
{
     Type ty = inttype;
     if (isint(l->type) && isint(r->type)) {
         ty = promote(l->type);
         l = cast(l, ty);
         r = cast(r, inttype);
     } else
         typeerror(op, l, r);
     return simplify(op, ty, l, r);
 }
References cast(), inttype, isint, Symbol::l, op, promote(), simplify(), and typeerror().
Referenced by asgntree(), and listnodes().
signedint()
Type signedint (Type)
Definition at line 379 of file types.c.
{
     if (ty->op == INT)
         return ty;
     assert(ty->op == UNSIGNED);
 #define xx(t) if (ty->size == t->size) return t
     xx(inttype);
     xx(longtype);
     xx(longlong);
 #undef xx
     assert(0); return NULL;
 }
References assert, inttype, longlong, longtype, NULL, and xx.
Referenced by cast(), cmp(), and swcode().
simplify()
Tree simplify (int , Type , Tree , Tree)
Definition at line 205 of file simp.c.
{
     int n;
     if (optype(op) == 0)
         op = mkop(op, ty);
     switch (op) {
         case ADD+U:
             foldcnst(U,u,+);
             commute(r,l);
             identity(r,l,U,u,0);
             break;
         case ADD+I:
             xfoldcnst(I,i,+,addi);
             commute(r,l);
             identity(r,l,I,i,0);
             break;
         case CVI+I:
             xcvtcnst(I,l->u.v.i,ty,i,(long)extend(l->u.v.i,ty));
             break;
         case CVU+I:
             if (l->op == CNST+U) {
                 if (!explicitCast && l->u.v.u > ty->u.sym->u.limits.max.i)
                     warning("overflow in converting constant expression from `%t' to `%t'\n", l->type, ty);
                 if (needconst || !(l->u.v.u > ty->u.sym->u.limits.max.i))
                     return cnsttree(ty, (long)extend(l->u.v.u,ty));
             }
             break;
         case CVP+U:
             xcvtcnst(P,(unsigned long)l->u.v.p,ty,u,(unsigned long)l->u.v.p);
             break;
         case CVU+P:
             xcvtcnst(U,(void*)l->u.v.u,ty,p,(void*)l->u.v.u);
             break;
         case CVP+P:
             xcvtcnst(P,l->u.v.p,ty,p,l->u.v.p);
             break;
         case CVI+U:
             xcvtcnst(I,l->u.v.i,ty,u,((unsigned long)l->u.v.i)&ones(8*ty->size));
             break;
         case CVU+U:
             xcvtcnst(U,l->u.v.u,ty,u,l->u.v.u&ones(8*ty->size));
             break;
         case CVI+F:
             xcvtcnst(I,l->u.v.i,ty,d,(double)l->u.v.i);
         case CVU+F:
             xcvtcnst(U,l->u.v.u,ty,d,(double)l->u.v.u);
             break;
         case CVF+I:
             xcvtcnst(F,l->u.v.d,ty,i,(long)l->u.v.d);
             break;
         case CVF+F: {
             float d = 0.0f;
             if (l->op == CNST+F) {
                 if (l->u.v.d < ty->u.sym->u.limits.min.d)
                     d = ty->u.sym->u.limits.min.d;
                 else if (l->u.v.d > ty->u.sym->u.limits.max.d)
                     d = ty->u.sym->u.limits.max.d;
                 else
                     d = l->u.v.d;
             }
             xcvtcnst(F,l->u.v.d,ty,d,(double)d);
             break;
             }
         case BAND+U:
             foldcnst(U,u,&);
             commute(r,l);
             identity(r,l,U,u,ones(8*ty->size));
             if (r->op == CNST+U && r->u.v.u == 0)
                 return tree(RIGHT, ty, root(l), cnsttree(ty, 0UL));
             break;
         case BAND+I:
             foldcnst(I,i,&);
             commute(r,l);
             identity(r,l,I,i,ones(8*ty->size));
             if (r->op == CNST+I && r->u.v.u == 0)
                 return tree(RIGHT, ty, root(l), cnsttree(ty, 0L));
             break;
         case MUL+U:
             commute(l,r);
             if (l->op == CNST+U && (n = ispow2(l->u.v.u)) != 0)
                 return simplify(LSH, ty, r, cnsttree(inttype, (long)n));
             foldcnst(U,u,*);
             identity(r,l,U,u,1);
             break;
         case NE+I:
             cfoldcnst(I,i,!=);
             commute(r,l);
             zerofield(NE,I,i);
             break;
         case EQ+I:
             cfoldcnst(I,i,==);
             commute(r,l);
             zerofield(EQ,I,i);
             break;
         case ADD+P:
             foldaddp(l,r,I,i);
             foldaddp(l,r,U,u);
             foldaddp(r,l,I,i);
             foldaddp(r,l,U,u);
             commute(r,l);
             identity(r,retype(l,ty),I,i,0);
             identity(r,retype(l,ty),U,u,0);
             if (isaddrop(l->op)
             && ((r->op == CNST+I && r->u.v.i <= longtype->u.sym->u.limits.max.i
                 && r->u.v.i >= longtype->u.sym->u.limits.min.i)
             || (r->op == CNST+U && r->u.v.u <= longtype->u.sym->u.limits.max.i)))
                 return addrtree(l, cast(r, longtype)->u.v.i, ty);
             if (l->op == ADD+P && isaddrop(l->kids[1]->op)
             && ((r->op == CNST+I && r->u.v.i <= longtype->u.sym->u.limits.max.i
                 && r->u.v.i >= longtype->u.sym->u.limits.min.i)
             ||  (r->op == CNST+U && r->u.v.u <= longtype->u.sym->u.limits.max.i)))
                 return simplify(ADD+P, ty, l->kids[0],
                     addrtree(l->kids[1], cast(r, longtype)->u.v.i, ty));
             if ((l->op == ADD+I || l->op == SUB+I)
             && l->kids[1]->op == CNST+I && isaddrop(r->op))
                 return simplify(ADD+P, ty, l->kids[0],
                     simplify(generic(l->op)+P, ty, r, l->kids[1]));
             if (l->op == ADD+P && generic(l->kids[1]->op) == CNST
             && generic(r->op) == CNST)
                 return simplify(ADD+P, ty, l->kids[0],
                     simplify(ADD, l->kids[1]->type, l->kids[1], r));
             if (l->op == ADD+I && generic(l->kids[1]->op) == CNST
             &&  r->op == ADD+P && generic(r->kids[1]->op) == CNST)
                 return simplify(ADD+P, ty, l->kids[0],
                     simplify(ADD+P, ty, r->kids[0],
                     simplify(ADD, r->kids[1]->type, l->kids[1], r->kids[1])));
             if (l->op == RIGHT && l->kids[1])
                 return tree(RIGHT, ty, l->kids[0],
                     simplify(ADD+P, ty, l->kids[1], r));
             else if (l->op == RIGHT && l->kids[0])
                 return tree(RIGHT, ty,
                     simplify(ADD+P, ty, l->kids[0], r), NULL);
             break;
         case ADD+F:
             xfoldcnst(F,d,+,addd);
             commute(r,l);
             break;
         case AND+I:
             op = AND;
             ufoldcnst(I,l->u.v.i ? cond(r) : l);    /* 0&&r => 0, 1&&r => r */
             break;
         case OR+I:
             op = OR;
             /* 0||r => r, 1||r => 1 */
             ufoldcnst(I,l->u.v.i ? cnsttree(ty, 1L) : cond(r));
             break;
         case BCOM+I:
             ufoldcnst(I,cnsttree(ty, (long)extend((~l->u.v.i)&ones(8*ty->size), ty)));
             idempotent(BCOM+U);
             break;
         case BCOM+U:
             ufoldcnst(U,cnsttree(ty, (unsigned long)((~l->u.v.u)&ones(8*ty->size))));
             idempotent(BCOM+U);
             break;
         case BOR+U:
             foldcnst(U,u,|);
             commute(r,l);
             identity(r,l,U,u,0);
             break;
         case BOR+I:
             foldcnst(I,i,|);
             commute(r,l);
             identity(r,l,I,i,0);
             break;
         case BXOR+U:
             foldcnst(U,u,^);
             commute(r,l);
             identity(r,l,U,u,0);
             break;
         case BXOR+I:
             foldcnst(I,i,^);
             commute(r,l);
             identity(r,l,I,i,0);
             break;
         case DIV+F:
             xfoldcnst(F,d,/,divd);
             break;
         case DIV+I:
             identity(r,l,I,i,1);
             if ((r->op == CNST+I && r->u.v.i == 0)
             ||  (l->op == CNST+I && l->u.v.i == ty->u.sym->u.limits.min.i
             &&  r->op == CNST+I && r->u.v.i == -1))
                 break;
             xfoldcnst(I,i,/,divi);
             break;
         case DIV+U:
             identity(r,l,U,u,1);
             if (r->op == CNST+U && r->u.v.u == 0)
                 break;
             if (r->op == CNST+U && (n = ispow2(r->u.v.u)) != 0)
                 return simplify(RSH, ty, l, cnsttree(inttype, (long)n));
             foldcnst(U,u,/);
             break;
         case EQ+F:
             cfoldcnst(F,d,==);
             commute(r,l);
             break;
         case EQ+U:
             cfoldcnst(U,u,==);
             commute(r,l);
             zerofield(EQ,U,u);
             break;
         case GE+F: cfoldcnst(F,d,>=); break;
         case GE+I: cfoldcnst(I,i,>=); break;
         case GE+U:
             geu(l,r,1); /* l >= 0 => (l,1) */
             cfoldcnst(U,u,>=);
             if (l->op == CNST+U && l->u.v.u == 0)   /* 0 >= r => r == 0 */
                 return eqtree(EQ, r, l);
             break;
         case GT+F: cfoldcnst(F,d, >); break;
         case GT+I: cfoldcnst(I,i, >); break;
         case GT+U:
             geu(r,l,0); /* 0 > r => (r,0) */
             cfoldcnst(U,u, >);
             if (r->op == CNST+U && r->u.v.u == 0)   /* l > 0 => l != 0 */
                 return eqtree(NE, l, r);
             break;
         case LE+F: cfoldcnst(F,d,<=); break;
         case LE+I: cfoldcnst(I,i,<=); break;
         case LE+U:
             geu(r,l,1); /* 0 <= r => (r,1) */
             cfoldcnst(U,u,<=);
             if (r->op == CNST+U && r->u.v.u == 0)   /* l <= 0 => l == 0 */
                 return eqtree(EQ, l, r);
             break;
         case LSH+I:
             identity(r,l,I,i,0);
             if (l->op == CNST+I && r->op == CNST+I
             && r->u.v.i >= 0 && r->u.v.i < 8*l->type->size
             && muli(l->u.v.i, 1<<r->u.v.i, ty->u.sym->u.limits.min.i, ty->u.sym->u.limits.max.i, needconst))
                 return cnsttree(ty, (long)(l->u.v.i<<r->u.v.i));
             if (r->op == CNST+I && (r->u.v.i >= 8*ty->size || r->u.v.i < 0)) {
                 warning("shifting an `%t' by %d bits is undefined\n", ty, r->u.v.i);
                 break;
             }
             break;
         case LSH+U:
             identity(r,l,I,i,0);
             sfoldcnst(<<);
             if (r->op == CNST+I && (r->u.v.i >= 8*ty->size || r->u.v.i < 0)) {
                 warning("shifting an `%t' by %d bits is undefined\n", ty, r->u.v.i);
                 break;
             }
             break;
         case LT+F: cfoldcnst(F,d, <); break;
         case LT+I: cfoldcnst(I,i, <); break;
         case LT+U:
             geu(l,r,0); /* l < 0 => (l,0) */
             cfoldcnst(U,u, <);
             if (l->op == CNST+U && l->u.v.u == 0)   /* 0 < r => r != 0 */
                 return eqtree(NE, r, l);
             break;
         case MOD+I:
             if (r->op == CNST+I && r->u.v.i == 1)   /* l%1 => (l,0) */
                 return tree(RIGHT, ty, root(l), cnsttree(ty, 0L));
             if ((r->op == CNST+I && r->u.v.i == 0)
             ||  (l->op == CNST+I && l->u.v.i == ty->u.sym->u.limits.min.i
             &&  r->op == CNST+I && r->u.v.i == -1))
                 break;
             xfoldcnst(I,i,%,divi);
             break;
         case MOD+U:
             if (r->op == CNST+U && ispow2(r->u.v.u)) /* l%2^n => l&(2^n-1) */
                 return bittree(BAND, l, cnsttree(ty, r->u.v.u - 1));
             if (r->op == CNST+U && r->u.v.u == 0)
                 break;
             foldcnst(U,u,%);
             break;
         case MUL+F:
             xfoldcnst(F,d,*,muld);
             commute(l,r);
             break;
         case MUL+I:
             commute(l,r);
             xfoldcnst(I,i,*,muli);
             if (l->op == CNST+I && r->op == ADD+I && r->kids[1]->op == CNST+I)
                 /* c1*(x + c2) => c1*x + c1*c2 */
                 return simplify(ADD, ty, simplify(MUL, ty, l, r->kids[0]),
                     simplify(MUL, ty, l, r->kids[1]));
             if (l->op == CNST+I && r->op == SUB+I && r->kids[1]->op == CNST+I)
                 /* c1*(x - c2) => c1*x - c1*c2 */
                 return simplify(SUB, ty, simplify(MUL, ty, l, r->kids[0]),
                     simplify(MUL, ty, l, r->kids[1]));
             if (l->op == CNST+I && l->u.v.i > 0 && (n = ispow2(l->u.v.i)) != 0)
                 /* 2^n * r => r<<n */
                 return simplify(LSH, ty, r, cnsttree(inttype, (long)n));
             identity(r,l,I,i,1);
             break;
         case NE+F:
             cfoldcnst(F,d,!=);
             commute(r,l);
             break;
         case NE+U:
             cfoldcnst(U,u,!=);
             commute(r,l);
             zerofield(NE,U,u);
             break;
         case NEG+F:
             ufoldcnst(F,cnsttree(ty, -l->u.v.d));
             idempotent(NEG+F);
             break;
         case NEG+I:
             if (l->op == CNST+I) {
                 if (needconst && l->u.v.i == ty->u.sym->u.limits.min.i)
                     warning("overflow in constant expression\n");
                 if (needconst || l->u.v.i != ty->u.sym->u.limits.min.i)
                     return cnsttree(ty, -l->u.v.i);
             }
             idempotent(NEG+I);
             break;
         case NOT+I:
             op = NOT;
             ufoldcnst(I,cnsttree(ty, !l->u.v.i));
             break;
         case RSH+I:
             identity(r,l,I,i,0);
             if (l->op == CNST+I && r->op == CNST+I
             && r->u.v.i >= 0 && r->u.v.i < 8*l->type->size) {
                 long n = l->u.v.i>>r->u.v.i;
                 if (l->u.v.i < 0)
                     n |= ~0UL<<(8*l->type->size - r->u.v.i);
                 return cnsttree(ty, n);
             }
             if (r->op == CNST+I && (r->u.v.i >= 8*ty->size || r->u.v.i < 0)) {
                 warning("shifting an `%t' by %d bits is undefined\n", ty, r->u.v.i);
                 break;
             }
             break;
         case RSH+U:
             identity(r,l,I,i,0);
             sfoldcnst(>>);
             if (r->op == CNST+I && (r->u.v.i >= 8*ty->size || r->u.v.i < 0)) {
                 warning("shifting an `%t' by %d bits is undefined\n", ty, r->u.v.i);
                 break;
             }
             break;
         case SUB+F:
             xfoldcnst(F,d,-,subd);
             break;
         case SUB+I:
             xfoldcnst(I,i,-,subi);
             identity(r,l,I,i,0);
             break;
         case SUB+U:
             foldcnst(U,u,-);
             identity(r,l,U,u,0);
             break;
         case SUB+P:
             if (l->op == CNST+P && r->op == CNST+P)
                 return cnsttree(ty, (long)((char *)l->u.v.p - (char *)r->u.v.p));
             if (r->op == CNST+I || r->op == CNST+U)
                 return simplify(ADD, ty, l,
                     cnsttree(inttype, r->op == CNST+I ? -r->u.v.i : -(long)r->u.v.u));
             if (isaddrop(l->op) && r->op == ADD+I && r->kids[1]->op == CNST+I)
                 /* l - (x + c) => l-c - x */
                 return simplify(SUB, ty,
                     simplify(SUB, ty, l, r->kids[1]), r->kids[0]);
             break;
         default:assert(0);
     }
     return tree(op, ty, l, r);
 }
References ADD, addd(), addi(), addrtree(), AND, assert, bittree, cast(), cfoldcnst, cnsttree(), commute, cond(), DIV, divd(), divi(), EQ, eqtree, explicitCast, extend, F, foldaddp, foldcnst, geu, GT, I, idempotent, identity, inttype, isaddrop, ispow2(), longtype, LSH, LT, mkop, MOD, muld(), muli(), needconst, NOT, NULL, ones, op, optype, OR, P, retype(), RIGHT, root(), RSH, sfoldcnst, SUB, subd(), subi(), tree(), U, ufoldcnst, warning(), xcvtcnst, xfoldcnst, and zerofield.
Referenced by addtree(), andtree(), bittree(), cast(), cmptree(), cvtconst(), eqtree(), field(), foldcond(), multree(), shtree(), subtree(), and unary().
skipto()
void skipto (int tok, char set[])
Definition at line 49 of file error.c.
{
     int n;
     char *s;
     assert(set);
     for (n = 0; t != EOI && t != tok; t = gettok()) {
         for (s = set; *s && kind[t] != *s; s++)
             ;
         if (kind[t] == *s)
             break;
         if (n++ == 0)
             error("skipping");
         if (n <= 8)
             printtoken();
         else if (n == 9)
             fprint(stderr, " ...");
     }
     if (n > 8) {
         fprint(stderr, " up to");
         printtoken();
     }
     if (n > 0)
         fprint(stderr, "\n");
 }
References assert, error(), fprint(), gettok(), kind, printtoken(), and stderr.
Referenced by initializer(), parameters(), statement(), and test().
statement()
void statement (int , Swtch , int)
Definition at line 77 of file stmt.c.
{
     float ref = refinc;
     if (Aflag >= 2 && lev == 15)
         warning("more than 15 levels of nested statements\n");
     switch (t) {
     case IF:       ifstmt(genlabel(2), loop, swp, lev + 1);
  break;
     case WHILE:    whilestmt(genlabel(3), swp, lev + 1); break;
     case DO:       dostmt(genlabel(3), swp, lev + 1); expect(';');
                     break;
     case FOR:      forstmt(genlabel(4), swp, lev + 1);
  break;
     case BREAK:    walk(NULL, 0, 0);
                definept(NULL);
                if (swp && swp->lab > loop)
                 branch(swp->lab + 1);
                else if (loop)
                 branch(loop + 2);
                else
                 error("illegal break statement\n");
                t = gettok(); expect(';');
                        break;
     case CONTINUE: walk(NULL, 0, 0);
                definept(NULL);
                if (loop)
                 branch(loop + 1);
                else
                 error("illegal continue statement\n");
                t = gettok(); expect(';');
                           break;
     case SWITCH:   swstmt(loop, genlabel(2), lev + 1);
  break;
     case CASE:     {
                 int lab = genlabel(1);
                 if (swp == NULL)
                     error("illegal case label\n");
                 definelab(lab);
                 while (t == CASE) {
                     static char stop[] = { IF, ID, 0 };
                     Tree p;
                     t = gettok();
                     p = constexpr(0);
                     if (generic(p->op) == CNST && isint(p->type)) {
                         if (swp) {
                             needconst++;
                             p = cast(p, swp->sym->type);
                             if (p->type->op == UNSIGNED)
                                 p->u.v.i = extend(p->u.v.u, p->type);
                             needconst--;
                             caselabel(swp, p->u.v.i, lab);
                         }
                     } else
                         error("case label must be a constant integer expression\n");
                     test(':', stop);
                 }
                 statement(loop, swp, lev);
                } break;
     case DEFAULT:  if (swp == NULL)
                 error("illegal default label\n");
                else if (swp->deflab)
                 error("extra default label\n");
                else {
                 swp->deflab = findlabel(swp->lab);
                 definelab(swp->deflab->u.l.label);
                }
                t = gettok();
                expect(':');
                statement(loop, swp, lev); break;
     case RETURN:   {
                 Type rty = freturn(cfunc->type);
                 t = gettok();
                 definept(NULL);
                 if (t != ';')
                     if (rty == voidtype) {
                         error("extraneous return value\n");
                         expr(0);
                         retcode(NULL);
                     } else
                         retcode(expr(0));
                 else {
                     if (rty != voidtype)
                         warning("missing return value\n");
                     retcode(NULL);
                 }
                 branch(cfunc->u.f.label);
                } expect(';');
                         break;
     case '{':      compound(loop, swp, lev + 1); break;
     case ';':      definept(NULL); t = gettok(); break;
     case GOTO:     walk(NULL, 0, 0);
                definept(NULL);
                t = gettok();
                if (t == ID) {
                 Symbol p = lookup(token, stmtlabs);
                 if (p == NULL) {
                 p = install(token, &stmtlabs, 0, FUNC);
                 p->scope = LABELS;
                 p->u.l.label = genlabel(1);
                 p->src = src;
             }
                 use(p, src);
                 branch(p->u.l.label);
                 t = gettok();
                } else
                 error("missing label in goto\n"); expect(';');
                       break;
     case ID:       if (getchr() == ':') {
                 stmtlabel();
                 statement(loop, swp, lev);
                 break;
                }
     default:       definept(NULL);
                if (kind[t] != ID) {
                 error("unrecognized statement\n");
                 t = gettok();
                } else {
                 Tree e = expr0(0);
                 listnodes(e, 0, 0);
                 if (nodecount == 0 || nodecount > 200)
                     walk(NULL, 0, 0);
                 else if (glevel) walk(NULL, 0, 0);
                 deallocate(STMT);
                } expect(';');
                         break;
     }
     if (kind[t] != IF && kind[t] != ID
     && t != '}' && t != EOI) {
         static char stop[] = { IF, ID, '}', 0 };
         error("illegal statement termination\n");
         skipto(0, stop);
     }
     refinc = ref;
 }
References Aflag, branch(), caselabel(), cast(), cfunc, compound(), constexpr(), deallocate(), definelab(), definept(), dostmt(), error(), expect(), expr(), expr0(), extend, findlabel(), forstmt(), freturn(), FUNC, genlabel(), getchr(), gettok(), glevel, ID, ifstmt(), install(), isint, kind, LABELS, listnodes(), lookup(), needconst, nodecount, NULL, refinc, retcode(), skipto(), STMT, stmtlabel(), stmtlabs, swstmt(), test(), use(), voidtype, walk(), warning(), and whilestmt().
Referenced by compound(), dostmt(), forstmt(), ifstmt(), swstmt(), and whilestmt().
string()
char* string (const char * str)
Definition at line 63 of file string.c.
{
     const char *s;
     for (s = str; *s; s++)
         ;
     return stringn(str, s - str);
 }
References string::str, and stringn().
stringd()
char* stringd (long n)
Definition at line 70 of file string.c.
                       {
     char str[25], *s = str + sizeof (str);
     unsigned long m;
     if (n == LONG_MIN)
         m = (unsigned long)LONG_MAX + 1;
     else if (n < 0)
         m = -n;
     else
         m = n;
     do
         *--s = m%10 + '0';
     while ((m /= 10) != 0);
     if (n < 0)
         *--s = '-';
     return stringn(s, str + sizeof (str) - s);
 }
References long(), LONG_MAX, LONG_MIN, m, string::str, and stringn().
Referenced by addrtree(), defsymbol(), fields(), findlabel(), genident(), mkauto(), newfield(), newstruct(), opname(), parameters(), temporary(), and vtoa().
stringf()
char* stringf (const char * , ...)
Definition at line 813 of file lcc.c.
{
     char buf[1024];
     va_list ap;
     va_start(ap, fmt);
     vsprintf(buf, fmt, ap);
     va_end(ap);
     return strsave(buf);
 }
References fmt, NULL, strsave(), va_end, va_start, vfprint(), and vsprintf().
Referenced by address(), callsys(), dclparam(), defsymbol(), funcname(), function(), local(), main(), mkreg(), opname(), tempname(), typestring(), and vtoa().
stringn()
char* stringn (const char * str, int len)
Definition at line 87 of file string.c.
{
     int i;
     unsigned int h;
     const char *end;
     struct string *p;
     assert(str);
     for (h = 0, i = len, end = str; i > 0; i--)
         h = (h<<1) + scatter[*(unsigned char *)end++];
     h &= NELEMS(buckets)-1;
     for (p = buckets[h]; p; p = p->link)
         if (len == p->len) {
             const char *s1 = str;
             char *s2 = p->str;
             do {
                 if (s1 == end)
                     return p->str;
             } while (*s1++ == *s2++);
         }
     {
         static char *next, *strlimit;
         if (len + 1 >= strlimit - next) {
             int n = len + 4*1024;
             next = allocate(n, PERM);
             strlimit = next + n;
         }
         NEW(p, PERM);
         p->len = len;
         for (p->str = next; str < end; )
             *next++ = *str++;
         *next++ = 0;
         p->link = buckets[h];
         buckets[h] = p;
         return p->str;
     }
 }
References allocate(), assert, buckets, NELEMS, NEW, PERM, scatter, and string::str.
Referenced by gettok(), main_init(), primary(), resynch(), string(), and stringd().
swcode()
void swcode (Swtch , int * , int , int)
swgen()
void swgen (Swtch)
Definition at line 390 of file stmt.c.
                       {
     int *buckets, k, n;
     long *v = swp->values;
     buckets = newarray(swp->ncases + 1,
         sizeof *buckets, FUNC);
     for (n = k = 0; k < swp->ncases; k++, n++) {
         buckets[n] = k;
         while (n > 0 && den(n-1, k) >= density)
             n--;
     }
     buckets[n] = swp->ncases;
     swcode(swp, buckets, 0, n - 1);
 }
References buckets, den, density, FUNC, newarray(), and swcode().
Referenced by swstmt().
swtoseg()
void swtoseg (int)
Definition at line 314 of file init.c.
                       {
     if (curseg != seg)
         (*IR->segment)(seg);
     curseg = seg;
 }
References curseg, and IR.
Referenced by dclglobal(), defglobal(), emitcode(), funcdefn(), and gencode().
table()
Table table (Table , int)
Definition at line 32 of file sym.c.
{
     Table new;
     NEW0(new, FUNC);
     new->previous = tp;
     new->level = level;
     if (tp)
         new->all = tp->all;
     return new;
 }
References FUNC, level, and NEW0.
Referenced by install().
temporary()
Symbol temporary (int , Type)
Definition at line 215 of file sym.c.
{
     Symbol p;
     NEW0(p, FUNC);
     p->name = stringd(++tempid);
     p->scope = level < LOCAL ? LOCAL : level;
     p->sclass = scls;
     p->type = ty;
     p->temporary = 1;
     p->generated = 1;
     return p;
 }
References FUNC, level, LOCAL, NEW0, stringd(), and tempid.
Referenced by call(), CG_ImpactMark(), newtemp(), nullcheck(), and visit().
test()
void test (int tok, char set[])
Definition at line 14 of file error.c.
{
     if (t == tok)
         t = gettok();
     else {
         expect(tok);
         skipto(tok, set);
         if (t == tok)
             t = gettok();
     }
 }
References expect(), gettok(), and skipto().
Referenced by CG_TargetCommand_f(), decl(), enumdcl(), expr(), expr1(), fields(), forstmt(), initend(), initializer(), statement(), and structdcl().
texpr()
Tree texpr (Tree(*)(int) , int , int)
Definition at line 25 of file tree.c.
{
     int save = where;
     Tree p;
     where = a;
     p = (*f)(tok);
     where = save;
     return p;
 }
References where.
Referenced by forstmt(), and whilestmt().
tree()
Tree tree (int , Type , Tree , Tree)
Definition at line 14 of file tree.c.
{
     Tree p;
     NEW0(p, where);
     p->op = op;
     p->type = type;
     p->kids[0] = left;
     p->kids[1] = right;
     return p;
 }
References NEW0, op, right, and where.
Referenced by root1().
ttob()
int ttob (Type)
Definition at line 430 of file types.c.
                   {
     switch (ty->op) {
     case CONST: case VOLATILE: case CONST+VOLATILE:
         return ttob(ty->type);
     case VOID: case INT: case UNSIGNED: case FLOAT:
         return ty->op + sizeop(ty->size);
     case POINTER:
         return POINTER + sizeop(voidptype->size);
     case FUNCTION:
         return POINTER + sizeop(funcptype->size);
     case ARRAY: case STRUCT: case UNION:
         return STRUCT;
     case ENUM:
         return INT + sizeop(inttype->size);
     }
     assert(0); return INT;
 }
References assert, CONST, funcptype, INT, inttype, sizeop, VOID(), voidptype, and VOLATILE.
Referenced by asgnnode(), defsymbol(), jump(), listnodes(), and tmpnode().
type_init()
void type_init (int , char * [])
Definition at line 88 of file types.c.
{
     static int inited;
     int i;
     if (inited)
         return;
     inited = 1;
     if (!IR)
         return;
     for (i = 1; i < argc; i++) {
         int size, align, outofline;
         if (strncmp(argv[i], "-unsigned_char=", 15) == 0)
             IR->unsigned_char = argv[i][15] - '0';
 #define xx(name) \
         else if (sscanf(argv[i], "-" #name "=%d,%d,%d", &size, &align, &outofline) == 3) { \
             IR->name.size = size; IR->name.align = align; \
             IR->name.outofline = outofline; }
     xx(charmetric)
     xx(shortmetric)
     xx(intmetric)
     xx(longmetric)
     xx(longlongmetric)
     xx(floatmetric)
     xx(doublemetric)
     xx(longdoublemetric)
     xx(ptrmetric)
     xx(structmetric)
 #undef xx
     }
 #define xx(v,name,op,metrics) v=xxinit(op,name,IR->metrics)
     xx(chartype,        "char",              IR->unsigned_char ? UNSIGNED : INT,charmetric);
     xx(doubletype,      "double",            FLOAT,   doublemetric);
     xx(floattype,       "float",             FLOAT,   floatmetric);
     xx(inttype,         "int",               INT,     intmetric);
     xx(longdouble,      "long double",       FLOAT,   longdoublemetric);
     xx(longtype,        "long int",          INT,     longmetric);
     xx(longlong,        "long long int",     INT,     longlongmetric);
     xx(shorttype,       "short",             INT,     shortmetric);
     xx(signedchar,      "signed char",       INT,     charmetric);
     xx(unsignedchar,    "unsigned char",     UNSIGNED,charmetric);
     xx(unsignedlong,    "unsigned long",     UNSIGNED,longmetric);
     xx(unsignedshort,   "unsigned short",    UNSIGNED,shortmetric);
     xx(unsignedtype,    "unsigned int",      UNSIGNED,intmetric);
     xx(unsignedlonglong,"unsigned long long",UNSIGNED,longlongmetric);
 #undef xx
     {
         Symbol p;
         p = install(string("void"), &types, GLOBAL, PERM);
         voidtype = type(VOID, NULL, 0, 0, p);
         p->type = voidtype;
     }
     pointersym = install(string("T*"), &types, GLOBAL, PERM);
     pointersym->addressed = IR->ptrmetric.outofline;
     pointersym->u.limits.max.p = (void*)ones(8*IR->ptrmetric.size);
     pointersym->u.limits.min.p = 0;
     voidptype = ptr(voidtype);
     funcptype = ptr(func(voidtype, NULL, 1));
     charptype = ptr(chartype);
 #define xx(v,t) if (v==NULL && t->size==voidptype->size && t->align==voidptype->align) v=t
     xx(unsignedptr,unsignedshort);
     xx(unsignedptr,unsignedtype);
     xx(unsignedptr,unsignedlong);
     xx(unsignedptr,unsignedlonglong);
     if (unsignedptr == NULL)
         unsignedptr = type(UNSIGNED, NULL, voidptype->size, voidptype->align, voidptype->u.sym);
     xx(signedptr,shorttype);
     xx(signedptr,inttype);
     xx(signedptr,longtype);
     xx(signedptr,longlong);
     if (signedptr == NULL)
         signedptr = type(INT, NULL, voidptype->size, voidptype->align, voidptype->u.sym);
 #undef xx
     widechar = unsignedshort;
     for (i = 0; i < argc; i++) {
 #define xx(name,type) \
         if (strcmp(argv[i], "-wchar_t=" #name) == 0) \
             widechar = type;
         xx(unsigned_char,unsignedchar)
         xx(unsigned_int,unsignedtype)
         xx(unsigned_short,unsignedshort)
     }
 #undef xx
 }
References charptype, chartype, doubletype, floattype, func(), funcptype, GLOBAL, install(), inttype, IR, longdouble, longlong, longtype, NULL, ones, PERM, pointersym, ptr(), shorttype, signedchar, signedptr, strncmp(), type(), types, unsignedchar, unsignedlong, unsignedlonglong, unsignedptr, unsignedshort, unsignedtype, VOID(), voidptype, voidtype, widechar, and xx.
Referenced by init(), main_init(), prof_init(), and trace_init().
typeerror()
void typeerror (int , Tree , Tree)
Definition at line 520 of file enode.c.
{
     int i;
     static struct { int op; char *name; } ops[] = {
         {ASGN, "="},    {INDIR, "*"},   {NEG,  "-"},
         {ADD,  "+"},    {SUB,   "-"},   {LSH,  "<<"},
         {MOD,  "%"},    {RSH,   ">>"},  {BAND, "&"},
         {BCOM, "~"},    {BOR,   "|"},   {BXOR, "^"},
         {DIV,  "/"},    {MUL,   "*"},   {EQ,   "=="},
         {GE,   ">="},   {GT,    ">"},   {LE,   "<="},
         {LT,   "<"},    {NE,    "!="},  {AND,  "&&"},
         {NOT,  "!"},    {OR,    "||"},  {COND, "?:"},
         {0, 0}
     };
     op = generic(op);
     for (i = 0; ops[i].op; i++)
         if (op == ops[i].op)
             break;
     assert(ops[i].name);
     if (r)
         error("operands of %s have illegal types `%t' and `%t'\n",
             ops[i].name, l->type, r->type);
     else
         error("operand of unary %s has illegal type `%t'\n", ops[i].name,
             l->type);
 }
References ADD, AND, ASGN, assert, COND, DIV, EQ, error(), GT, Symbol::l, LSH, LT, MOD, NOT, op, ops, OR, RSH, and SUB.
Referenced by addtree(), andtree(), asgntree(), bittree(), cmptree(), condtree(), multree(), shtree(), subtree(), and unary().
typename()
Type typename (void)
Definition at line 1152 of file decl.c.
                     {
     Type ty = specifier(NULL);
     if (t == '*' || t == '(' || t == '[') {
         ty = dclr(ty, NULL, NULL, 1);
         if (Aflag >= 1 && !hasproto(ty))
             warning("missing prototype\n");
     }
     return ty;
 }
References Aflag, dclr(), hasproto(), NULL, specifier(), and warning().
Referenced by _GLIBCXX_VISIBILITY().
typestring()
char* typestring (Type ty, char * id)
Definition at line 691 of file types.c.
{
     for ( ; ty; ty = ty->type) {
         Symbol p;
         switch (ty->op) {
         case CONST+VOLATILE: case CONST: case VOLATILE:
             if (isptr(ty->type))
                 str = stringf("%k %s", ty->op, str);
             else
                 return stringf("%k %s", ty->op, typestring(ty->type, str));
             break;
         case STRUCT: case UNION: case ENUM:
             assert(ty->u.sym);
             if ((p = findtype(ty)) != NULL)
                 return *str ? stringf("%s %s", p->name, str) : p->name;
             if (*ty->u.sym->name >= '1' && *ty->u.sym->name <= '9')
                 warning("unnamed %k in prototype\n", ty->op);
             if (*str)
                 return stringf("%k %s %s", ty->op, ty->u.sym->name, str);
             else
                 return stringf("%k %s", ty->op, ty->u.sym->name);
         case VOID: case FLOAT: case INT: case UNSIGNED:
             return *str ? stringf("%s %s", ty->u.sym->name, str) : ty->u.sym->name;
         case POINTER:
             if (!ischar(ty->type) && (p = findtype(ty)) != NULL)
                 return *str ? stringf("%s %s", p->name, str) : p->name;
             str = stringf(isarray(ty->type) || isfunc(ty->type) ? "(*%s)" : "*%s", str);
             break;
         case FUNCTION:
             if ((p = findtype(ty)) != NULL)
                 return *str ? stringf("%s %s", p->name, str) : p->name;
             if (ty->u.f.proto == 0)
                 str = stringf("%s()", str);
             else if (ty->u.f.proto[0]) {
                 int i;
                 str = stringf("%s(%s", str, typestring(ty->u.f.proto[0], ""));
                 for (i = 1; ty->u.f.proto[i]; i++)
                     if (ty->u.f.proto[i] == voidtype)
                         str = stringf("%s, ...", str);
                     else
                         str = stringf("%s, %s", str, typestring(ty->u.f.proto[i], ""));
                 str = stringf("%s)", str);
             } else
                 str = stringf("%s(void)", str);
             break;
         case ARRAY:
             if ((p = findtype(ty)) != NULL)
                 return *str ? stringf("%s %s", p->name, str) : p->name;
             if (ty->type && ty->type->size > 0)
                 str = stringf("%s[%d]", str, ty->size/ty->type->size);
             else
                 str = stringf("%s[]", str);
             break;
         default: assert(0);
         }
     }
     assert(0); return 0;
 }
References assert, CONST, findtype(), INT, isarray, ischar, isfunc, isptr, NULL, stringf(), VOID(), voidtype, VOLATILE, and warning().
Referenced by funcdefn(), printdecl(), and tracevalue().
use()
void use (Symbol p, Coordinate src)
Definition at line 244 of file sym.c.
{
     Coordinate *cp;
     NEW(cp, PERM);
     *cp = src;
     p->uses = append(cp, p->uses);
 }
References append(), cp, NEW, and PERM.
Referenced by enumdcl(), fieldref(), funcdefn(), pragma(), primary(), specifier(), statement(), and structdcl().
value()
Tree value (Tree)
Definition at line 103 of file expr.c.
                    {
     int op = generic(rightkid(p)->op);
     if (p->type != voidtype
     && (op==AND || op==OR || op==NOT || op==EQ || op==NE
     ||  op== LE || op==LT || op== GE || op==GT))
         p = condtree(p, consttree(1, inttype),
             consttree(0, inttype));
     return p;
 }
References AND, condtree(), consttree(), EQ, GT, inttype, LT, NOT, op, OR, rightkid(), and voidtype.
Referenced by cast(), expr(), expr1(), lvalue(), and nullcheck().
variadic()
int variadic (Type)
Definition at line 262 of file types.c.
                       {
     if (isfunc(ty) && ty->u.f.proto) {
         int i;
         for (i = 0; ty->u.f.proto[i]; i++)
             ;
         return i > 1 && ty->u.f.proto[i-1] == voidtype;
     }
     return 0;
 }
References isfunc, and voidtype.
Referenced by eqtype(), funcdefn(), and tracecall().
vcall()
Tree vcall (Symbol func, Type ty, ...)
Definition at line 123 of file enode.c.
{
     va_list ap;
     Tree args = NULL, e, f = pointer(idtree(func)), r = NULL;
     assert(isfunc(func->type));
     if (ty == NULL)
         ty = freturn(func->type);
     va_start(ap, ty);
     while ((e = va_arg(ap, Tree)) != NULL) {
         if (hascall(e))
             r = r == NULL ? e : tree(RIGHT, voidtype, r, e);
         args = tree(mkop(ARG, e->type), e->type, e, args);
     }
     va_end(ap);
     if (r != NULL)
         args = tree(RIGHT, voidtype, r, args);
     return calltree(f, ty, args, NULL);
 }
References args, assert, calltree(), Symbol::f, freturn(), hascall(), idtree(), isfunc, mkop, NULL, RIGHT, tree(), va_arg, va_end, va_start, and voidtype.
Referenced by bbentry(), bbexit(), nullcall(), and nullcheck().
vfprint()
void vfprint (FILE * , char * , const char * , va_list)
Definition at line 67 of file output.c.
{
     for (; *fmt; fmt++)
         if (*fmt == '%')
             switch (*++fmt) {
             case 'd': bp = outd(va_arg(ap, int), f, bp); break;
             case 'D': bp = outd(va_arg(ap, long), f, bp); break;
             case 'U': bp = outu(va_arg(ap, unsigned long), 10, f, bp); break;
             case 'u': bp = outu(va_arg(ap, unsigned), 10, f, bp); break;
             case 'o': bp = outu(va_arg(ap, unsigned), 8, f, bp); break;
             case 'X': bp = outu(va_arg(ap, unsigned long), 16, f, bp); break;
             case 'x': bp = outu(va_arg(ap, unsigned), 16, f, bp); break;
             case 'f': case 'e':
             case 'g': {
                     static char format[] = "%f";
                     char buf[128];
                     format[1] = *fmt;
                     sprintf(buf, format, va_arg(ap, double));
                     bp = outs(buf, f, bp);
                   }
 ; break;
             case 's': bp = outs(va_arg(ap, char *), f, bp); break;
             case 'p': {
                 void *p = va_arg(ap, void *);
                 if (p)
                     bp = outs("0x", f, bp);
                 bp = outu((unsigned long)p, 16, f, bp);
                 break;
                   }
             case 'c': if (f) fputc(va_arg(ap, int), f); else *bp++ = va_arg(ap, int); break;
             case 'S': { char *s = va_arg(ap, char *);
                     int n = va_arg(ap, int);
                     if (s) {
                         for ( ; n-- > 0; s++)
                             if (f) (void)putc(*s, f); else *bp++ = *s;
                     }
  } break;
             case 'k': { int t = va_arg(ap, int);
                     static char *tokens[] = {
 #define xx(a,b,c,d,e,f,g) g,
 #define yy(a,b,c,d,e,f,g) g,
 #include "token.h"
                     };
                     assert(tokens[t&0177]);
                     bp = outs(tokens[t&0177], f, bp);
  } break;
             case 't': { Type ty = va_arg(ap, Type);
                     assert(f);
                     outtype(ty ? ty : voidtype, f);
  } break;
             case 'w': { Coordinate *p = va_arg(ap, Coordinate *);
                     if (p->file && *p->file) {
                         bp = outs(p->file, f, bp);
                         bp = outs(":", f, bp);
                     }
                     bp = outd(p->y, f, bp);
  } break;
             case 'I': { int n = va_arg(ap, int);
                     while (--n >= 0)
                         if (f) (void)putc(' ', f); else *bp++ = ' ';
  } break;
             default:  if (f) (void)putc(*fmt, f); else *bp++ = *fmt; break;
             }
         else if (f)
             (void)putc(*fmt, f);
         else
             *bp++ = *fmt;
     if (!f)
         *bp = '\0';
 }
References assert, bp, fmt, fputc(), outd(), outs(), outtype(), outu(), putc(), sprintf(), va_arg, void(), and voidtype.
Referenced by error(), fprint(), print(), stringf(), and warning().
vtoa()
char* vtoa (Type , Value)
Definition at line 298 of file sym.c.
{
     ty = unqual(ty);
     switch (ty->op) {
     case INT:      return stringd(v.i);
     case UNSIGNED: return stringf((v.u&~0x7FFF) ? "0x%X" : "%U", v.u);
     case FLOAT:    return stringf("%g", (double)v.d);
     case ARRAY:
         if (ty->type == chartype || ty->type == signedchar
         ||  ty->type == unsignedchar)
             return v.p;
         return stringf("%p", v.p);
     case POINTER:  return stringf("%p", v.p);
     case FUNCTION: return stringf("%p", v.g);
     }
     assert(0); return NULL;
 }
References assert, chartype, INT, NULL, signedchar, stringd(), stringf(), unqual, and unsignedchar.
Referenced by constant(), printtoken(), and printtree1().
walk()
void walk (Tree e, int tlab, int flab)
Definition at line 38 of file dag.c.
{
     listnodes(tp, tlab, flab);
     if (forest) {
         Node list = forest->link;
         forest->link = NULL;
         if (!IR->wants_dag)
             list = undag(list);
         code(Gen)->u.forest = list;
         forest = NULL;
     }
     reset();
     deallocate(STMT);
 }
References code, deallocate(), forest, IR, list(), listnodes(), NULL, reset(), STMT, and undag().
Referenced by bbentry(), bbexit(), branch(), compound(), dcllocal(), definelab(), dostmt(), forstmt(), funcdefn(), gencode(), ifstmt(), retcode(), statement(), swcode(), swstmt(), tracefinis(), and whilestmt().
warning()
void warning (const char * , ...)
Definition at line 127 of file error.c.
{
     va_list ap;
     va_start(ap, fmt);
     if (wflag == 0) {
         errcnt--;
         error("warning: ");
         vfprint(stderr, NULL, fmt, ap);
     }
     va_end(ap);
 }
References errcnt, error(), fmt, NULL, stderr, va_end, va_start, vfprint(), and wflag.
Referenced by addd(), addi(), array(), assign(), backslash(), branch(), call(), caselabel(), cast(), CG_DrawRadarBlips(), checkref(), code(), conditional(), cput(), dclglobal(), dcllocal(), dclparam(), dclr(), decl(), divd(), divi(), enumdcl(), exitscope(), expr2(), fcon(), fields(), funcdefn(), gettok(), icon(), initfields(), lvalue(), muld(), muli(), parameters(), primary(), program(), qual(), resynch(), retcode(), root1(), scon(), simplify(), specifier(), statement(), swcode(), swstmt(), typename(), typestring(), and unary().
Variable Documentation
Aflag
int Aflag
Definition at line 11 of file main.c.
Referenced by array(), assign(), call(), caselabel(), checkref(), conditional(), dclglobal(), dclr(), decl(), enumdcl(), exitscope(), expr2(), fields(), funcdefn(), main_init(), parameters(), primary(), resynch(), scon(), specifier(), statement(), typename(), and unary().
assignargs
int assignargs
Definition at line 15 of file dag.c.
Referenced by gencode().
bindings
Binding bindings[]
Definition at line 4 of file bind.c.
Referenced by main().
cfunc
Symbol cfunc
Definition at line 10 of file decl.c.
Referenced by bbcall(), compound(), funcdefn(), listnodes(), primary(), retcode(), and statement().
charptype
Type charptype
Definition at line 31 of file types.c.
Referenced by bbvars(), funcdefn(), tracefinis(), and type_init().
chartype
Type chartype
Definition at line 16 of file types.c.
Referenced by btot(), gettok(), initializer(), mkstr(), trace_init(), tracevalue(), type_init(), and vtoa().
codehead
struct code codehead
Definition at line 8 of file stmt.c.
Referenced by emitcode(), funcdefn(), and gencode().
codelist
Code codelist
Definition at line 9 of file stmt.c.
Referenced by branch(), code(), definelab(), funcdefn(), gencode(), reachable(), swcode(), and swstmt().
constants
Table constants
Definition at line 22 of file sym.c.
Referenced by constant(), and finalize().
cp
unsigned char* cp
Definition at line 9 of file input.c.
Referenced by fillbuf(), input_init(), nextline(), pragma(), and resynch().
density
float density
Definition at line 10 of file stmt.c.
Referenced by main_init(), and swgen().
doubletype
Type doubletype
Definition at line 17 of file types.c.
Referenced by binary(), btot(), fcon(), gettok(), promote(), and type_init().
errcnt
int errcnt
Definition at line 1680 of file gram.c.
Referenced by error(), fatal(), warning(), and yyerror().
errlimit
int errlimit
Definition at line 6 of file error.c.
Referenced by error(), and main_init().
events
Events events
Definition at line 9 of file event.c.
Referenced by call(), compound(), CON_Input(), definept(), expr2(), expr3(), funcdefn(), main(), prof_init(), retcode(), and trace_init().
explicitCast
int explicitCast
Definition at line 53 of file simp.c.
Referenced by simplify(), and unary().
externals
Table externals
Definition at line 23 of file sym.c.
Referenced by dclglobal(), dcllocal(), finalize(), and primary().
file
char* file
Definition at line 10 of file input.c.
Referenced by _GLIBCXX_VISIBILITY(), _MULT16_16(), _MULT16_32_QX(), acaller(), CG_ParseAnimationFile(), CG_weapGfx_LoadFile(), fopen_file_func(), FS_FOpenFileReadDir(), FS_ForceFlush(), FS_GetModList(), FS_Seek(), G_weapPhys_ErrorHandle(), G_weapPhys_LoadFile(), gather(), gettok(), Hunk_AllocDebug(), PSys_ParseFile(), resynch(), S_WAV_CodecLoad(), and Z_TagMallocDebug().
firstfile
char* firstfile
Definition at line 11 of file input.c.
Referenced by error(), main(), progbeg(), and resynch().
floattype
Type floattype
Definition at line 18 of file types.c.
Referenced by binary(), btot(), fcon(), gettok(), and type_init().
funcptype
Type funcptype
Definition at line 30 of file types.c.
Referenced by btot(), idtree(), ttob(), and type_init().
glevel
int glevel
Definition at line 13 of file main.c.
Referenced by dclglobal(), definept(), doglobal(), emitcode(), funcdefn(), gencode(), main(), main_init(), program(), and statement().
globals
Table globals
Definition at line 25 of file sym.c.
Referenced by dclglobal(), dcllocal(), main_init(), and mksymbol().
identifiers
Table identifiers
Definition at line 24 of file sym.c.
Referenced by compound(), dclglobal(), dcllocal(), dclparam(), decl(), definept(), enumdcl(), exitscope(), finalize(), findtype(), funcdefn(), gettok(), main(), and primary().
inttype
Type inttype
Definition at line 19 of file types.c.
Referenced by addtree(), andtree(), array(), asgntree(), assign(), bbentry(), bbexit(), bbincr(), binary(), bittree(), btot(), call(), cast(), cmptree(), cond(), condtree(), enumdcl(), eqtree(), field(), fields(), freturn(), funcdefn(), genconst(), gettok(), icon(), initchar(), initfields(), initvalue(), intconst(), intexpr(), listnodes(), multree(), nullcall(), nullcheck(), parameters(), postfix(), primary(), promote(), shtree(), signedint(), simplify(), specifier(), subtree(), super(), swstmt(), trace_init(), tracecall(), tracevalue(), ttob(), type_init(), unary(), and value().
IR
Interface* IR
Definition at line 9 of file main.c.
Referenced by address(), addrtree(), bbcall(), bbfunc(), bbincr(), bbvars(), blkcopy(), blkunroll(), call(), compound(), constant(), dclglobal(), dcllocal(), defglobal(), defpointer(), doconst(), doextern(), doglobal(), dumpcover(), dumprule(), emitasm(), emitcode(), emitSymbol(), emitSymRef(), fields(), findlabel(), funcdefn(), function(), gen(), gencode(), genconst(), genident(), genreload(), genspill(), getrule(), hascall(), idtree(), initchar(), initfields(), initializer(), initstruct(), listnodes(), local(), main(), main_init(), mksymbol(), newtemp(), prelabel(), primary(), prof_init(), prune(), ptr(), ralloc(), reduce(), reprune(), rewrite(), swcode(), swtoseg(), trace_init(), tracecall(), type_init(), typestab(), and walk().
kind
char kind[]
Definition at line 7 of file error.c.
Referenced by code(), compound(), dclr1(), decl(), forstmt(), funcdefn(), parameters(), program(), reachable(), skipto(), and statement().
labels
Table labels
Definition at line 27 of file sym.c.
Referenced by findlabel(), and funcdefn().
level
int level
Definition at line 28 of file sym.c.
limit
unsigned char* limit
Definition at line 12 of file input.c.
Referenced by alloc(), fillbuf(), getchr(), gettok(), input_init(), nextline(), PM_BurnPowerLevel(), PM_CheckBoost(), PM_CheckPowerLevel(), PM_UsePowerLevel(), resynch(), save_marker(), scon(), pcrecpp::RE_Options::set_match_limit(), and pcrecpp::RE_Options::set_match_limit_recursion().
line
char* line
Current line number.
Definition at line 13 of file input.c.
Referenced by __attribute__(), _ADD16(), _ADD32(), _DIV32(), _DIV32_16(), _EXTEND32(), _EXTRACT16(), _MULT16_16(), _MULT16_32_QX(), _SHL16(), _SHR16(), _speex_fatal(), _SUB16(), assemble_line(), Cbuf_Execute(), CG_Aura_DrawInnerSpike(), CG_Aura_DrawSpike(), CG_Draw3DLine(), CG_DrawLine(), CG_DrawLineRGBA(), CG_Tracer(), CG_weapGfx_AddDefinitionRef(), CG_weapGfx_ErrorHandle(), Con_Dump_f(), CON_Show(), ConcatArgs(), DistancePointLine(), fillbuf(), G_weapPhys_AddDefinitionRef(), G_weapPhys_ErrorHandle(), gettok(), Hunk_AllocDebug(), lines(), nextline(), PrintToSourceLine(), resynch(), S_MallocDebug(), trap_PC_SourceFileAndLine(), Z_MallocDebug(), and Z_TagMallocDebug().
lineno
int lineno
Definition at line 14 of file input.c.
Referenced by funcdefn(), gettok(), input_init(), main(), nextline(), nullcall(), nullcheck(), and resynch().
loci
List loci
Definition at line 30 of file sym.c.
Referenced by locus(), and main().
longdouble
Type longdouble
Definition at line 20 of file types.c.
Referenced by binary(), btot(), cast(), fcon(), specifier(), tracevalue(), and type_init().
longlong
Type longlong
Definition at line 22 of file types.c.
Referenced by binary(), btot(), signedint(), specifier(), and type_init().
longtype
Type longtype
Definition at line 21 of file types.c.
Referenced by binary(), btot(), icon(), signedint(), simplify(), specifier(), subtree(), tracevalue(), and type_init().
ncalled
int ncalled
Definition at line 24 of file prof.c.
Referenced by definept(), funcdefn(), and prof_init().
needconst
int needconst
Definition at line 52 of file simp.c.
Referenced by addd(), addi(), constexpr(), divd(), divi(), initializer(), initvalue(), intexpr(), muld(), muli(), nullcheck(), root1(), simplify(), statement(), subd(), and subi().
nodecount
int nodecount
Definition at line 13 of file dag.c.
Referenced by kill(), node(), reset(), and statement().
npoints
int npoints
Definition at line 23 of file prof.c.
Referenced by bbincr(), bbvars(), definept(), and gather().
optree
Tree(* optree[])(int, Tree, Tree)
Definition at line 14 of file enode.c.
Referenced by bbincr(), cast(), cond(), expr3(), incr(), postfix(), swcode(), and tracevalue().
Pflag
int Pflag
Definition at line 12 of file main.c.
Referenced by doglobal(), funcdefn(), and main_init().
prunetemps
int prunetemps
Definition at line 16 of file dag.c.
Referenced by gencode().
refinc
float refinc
Definition at line 14 of file expr.c.
Referenced by definept(), dostmt(), forstmt(), funcdefn(), idtree(), ifstmt(), statement(), swstmt(), and whilestmt().
retv
Symbol retv
Definition at line 11 of file decl.c.
Referenced by compound(), funcdefn(), and retcode().
shorttype
Type shorttype
Definition at line 23 of file types.c.
Referenced by btot(), specifier(), and type_init().
signedchar
Type signedchar
Definition at line 24 of file types.c.
Referenced by btot(), specifier(), tracevalue(), type_init(), and vtoa().
signedptr
Type signedptr
Definition at line 35 of file types.c.
Referenced by addtree(), subtree(), and type_init().
src
Coordinate src
Definition at line 142 of file lex.c.
stmtlabs
Table stmtlabs
Definition at line 11 of file stmt.c.
Referenced by funcdefn(), statement(), and stmtlabel().
symbols
List symbols
Definition at line 528 of file c.h.
t
int t
Definition at line 37 of file qgl.h.
token
char* token
Definition at line 210 of file q3asm.c.
tsym
Symbol tsym
Definition at line 145 of file lex.c.
Referenced by compound(), dclr1(), decl(), enumdcl(), fields(), funcdefn(), gettok(), initializer(), parameters(), pragma(), primary(), printtoken(), specifier(), structdcl(), and unary().
types
Table types
Definition at line 26 of file sym.c.
Referenced by compound(), GraphicsPathIterator::CopyData(), enumdcl(), GraphicsPathIterator::Enumerate(), exitscope(), GraphicsPath::GetPathTypes(), GraphicsPath::GraphicsPath(), main(), newstruct(), structdcl(), type_init(), and xxinit().
unsignedchar
Type unsignedchar
Definition at line 25 of file types.c.
Referenced by btot(), initfields(), specifier(), tracevalue(), type_init(), and vtoa().
unsignedlong
Type unsignedlong
Definition at line 26 of file types.c.
Referenced by binary(), btot(), cast(), icon(), specifier(), swcode(), tracevalue(), type_init(), and unary().
unsignedlonglong
Type unsignedlonglong
Definition at line 27 of file types.c.
Referenced by binary(), btot(), specifier(), and type_init().
unsignedptr
Type unsignedptr
Definition at line 34 of file types.c.
Referenced by cmptree(), eqtree(), subtree(), super(), swcode(), and type_init().
unsignedshort
Type unsignedshort
Definition at line 28 of file types.c.
Referenced by btot(), specifier(), and type_init().
unsignedtype
Type unsignedtype
Definition at line 29 of file types.c.
Referenced by bbcall(), bbfunc(), bbvars(), binary(), btot(), cast(), cmptree(), fields(), icon(), initfields(), listnodes(), prof_init(), promote(), specifier(), super(), tracevalue(), and type_init().
voidptype
Type voidptype
Definition at line 32 of file types.c.
Referenced by asgnnode(), bbcall(), bbentry(), bbexit(), btot(), condtree(), defpointer(), idtree(), jump(), listnodes(), main_init(), nullcall(), nullcheck(), swcode(), tmpnode(), ttob(), and type_init().
voidtype
Type voidtype
Definition at line 33 of file types.c.
Referenced by array(), asgntree(), bbentry(), bbexit(), call(), condtree(), ftype(), funcdefn(), gettok(), lvalue(), nullcheck(), outtype(), parameters(), postfix(), printproto(), root1(), statement(), swcode(), tracereturn(), type_init(), typestring(), unary(), value(), variadic(), vcall(), and vfprint().
wflag
int wflag
Definition at line 12 of file error.c.
Referenced by main_init(), and warning().
where
int where
Definition at line 4 of file tree.c.
Referenced by texpr(), and tree().
widechar
Type widechar
Definition at line 36 of file types.c.
Referenced by backslash(), doconst(), gettok(), initializer(), printtoken(), and type_init().
xref
int xref
Definition at line 14 of file main.c.
Referenced by enumdcl(), fieldref(), funcdefn(), main(), main_init(), newfield(), primary(), program(), and structdcl().
YYcheck
Symbol YYcheck
Definition at line 16 of file main.c.
Referenced by addtree(), field(), and main_init().
YYnull
Symbol YYnull
Definition at line 15 of file main.c.
Referenced by main_init(), nullcheck(), postfix(), and unary().