ZEQ2-Lite: Pen Class Reference
Pen Class Reference
#include <gdipluspen.h>
Public Member Functions
Pen (const Brush *brush, REAL width=1.0f)
Pen (const Color &color, REAL width=1.0f)
~Pen ()
Pen * Clone () const
PenAlignment GetAlignment () const
Status GetColor (Color *color) const
Status GetCompoundArray (REAL *compoundArray, INT count) const
INT GetCompoundArrayCount () const
Status GetCustomEndCap (CustomLineCap *customCap) const
Status GetCustomStartCap (CustomLineCap *customCap) const
DashCap GetDashCap () const
REAL GetDashOffset () const
Status GetDashPattern (REAL *dashArray, INT count) const
INT GetDashPatternCount () const
DashStyle GetDashStyle () const
LineCap GetEndCap () const
Status GetLastStatus () const
LineJoin GetLineJoin () const
REAL GetMiterLimit () const
PenType GetPenType () const
LineCap GetStartCap () const
Status GetTransform (Matrix *matrix) const
REAL GetWidth () const
Status MultiplyTransform (const Matrix *matrix, MatrixOrder order=MatrixOrderPrepend)
Status ResetTransform ()
Status RotateTransform (REAL angle, MatrixOrder order=MatrixOrderPrepend)
Status ScaleTransform (REAL sx, REAL sy, MatrixOrder order=MatrixOrderPrepend)
Status SetAlignment (PenAlignment penAlignment)
Status SetBrush (const Brush *brush)
Status SetColor (const Color &color)
Status SetCompoundArray (const REAL *compoundArray, INT count)
Status SetCustomEndCap (const CustomLineCap *customCap)
Status SetCustomStartCap (const CustomLineCap *customCap)
Status SetDashCap (DashCap dashCap)
Status SetDashOffset (REAL dashOffset)
Status SetDashPattern (const REAL *dashArray, INT count)
Status SetDashStyle (DashStyle dashStyle)
Status SetEndCap (LineCap endCap)
Status SetLineCap (LineCap startCap, LineCap endCap, DashCap dashCap)
Status SetLineJoin (LineJoin lineJoin)
Status SetMiterLimit (REAL miterLimit)
Status SetStartCap (LineCap startCap)
Status SetTransform (const Matrix *matrix)
Status SetWidth (REAL width)
Status TranslateTransform (REAL dx, REAL dy, MatrixOrder order=MatrixOrderPrepend)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Pen (const Pen &pen)
Pen (GpPen *pen, Status status)
Pen & operator= (const Pen &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpPen * nativePen
Friends
class Graphics
class GraphicsPath
Detailed Description
Definition at line 33 of file gdipluspen.h.
Constructor & Destructor Documentation
Pen() [1/4]
Pen::Pen (const Color & color, REAL width = 1.0f) inline
Definition at line 39 of file gdipluspen.h.
                                               :
         nativePen(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreatePen1(
                 color.GetValue(), width, UnitWorld,
                 &nativePen);
     }
References GdipCreatePen1(), lastStatus, nativePen, and UnitWorld.
Referenced by Clone().
Pen() [2/4]
Pen::Pen (const Brush * brush, REAL width = 1.0f) inline
Definition at line 46 of file gdipluspen.h.
                                               :
         nativePen(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreatePen2(
                 brush ? brush->nativeBrush : NULL,
                 width, UnitWorld, &nativePen);
     }
References GdipCreatePen2(), lastStatus, Brush::nativeBrush, nativePen, NULL, and UnitWorld.
~Pen()
Pen::~Pen () inline
Definition at line 53 of file gdipluspen.h.
     {
         DllExports::GdipDeletePen(nativePen);
     }
References GdipDeletePen(), and nativePen.
Pen() [3/4]
Pen::Pen (GpPen * pen, Status status) inline private
Definition at line 324 of file gdipluspen.h.
 : nativePen(pen), lastStatus(status) {}
Pen() [4/4]
Pen::Pen (const Pen & pen) private
Member Function Documentation
Clone()
Pen* Pen::Clone () const inline
Definition at line 57 of file gdipluspen.h.
     {
         GpPen *clonePen = NULL;
         Status status = updateStatus(DllExports::GdipClonePen(
                 nativePen, &clonePen));
         if (status == Ok) {
             Pen *result = new Pen(clonePen, lastStatus);
             if (!result) {
                 DllExports::GdipDeletePen(clonePen);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipClonePen(), GdipDeletePen(), lastStatus, nativePen, NULL, Ok, OutOfMemory, Pen(), and updateStatus().
GetAlignment()
PenAlignment Pen::GetAlignment () const inline
Definition at line 74 of file gdipluspen.h.
     {
         PenAlignment result = PenAlignmentCenter;
         updateStatus(DllExports::GdipGetPenMode(nativePen, &result));
         return result;
     }
References GdipGetPenMode(), nativePen, PenAlignmentCenter, and updateStatus().
GetColor()
Status Pen::GetColor (Color * color) const inline
Definition at line 88 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipGetPenColor(
                 nativePen, color ? &color->Value : NULL));
     }
References GdipGetPenColor(), nativePen, NULL, updateStatus(), and Color::Value.
GetCompoundArray()
Status Pen::GetCompoundArray (REAL * compoundArray, INT count) const inline
Definition at line 93 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipGetPenCompoundArray(
                 nativePen, compoundArray, count));
     }
References GdipGetPenCompoundArray(), nativePen, and updateStatus().
GetCompoundArrayCount()
INT Pen::GetCompoundArrayCount () const inline
Definition at line 98 of file gdipluspen.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetPenCompoundCount(
                 nativePen, &result));
         return result;
     }
References GdipGetPenCompoundCount(), nativePen, and updateStatus().
GetCustomEndCap()
Status Pen::GetCustomEndCap (CustomLineCap * customCap) const inline
Definition at line 105 of file gdipluspen.h.
     {
         if (!customCap) return lastStatus = InvalidParameter;
         // FIXME: do we need to call GdipDeleteCustomLineCap first?
         return updateStatus(DllExports::GdipGetPenCustomEndCap(
                 nativePen, &customCap->nativeCustomLineCap));
     }
References GdipGetPenCustomEndCap(), InvalidParameter, lastStatus, CustomLineCap::nativeCustomLineCap, nativePen, and updateStatus().
GetCustomStartCap()
Status Pen::GetCustomStartCap (CustomLineCap * customCap) const inline
Definition at line 112 of file gdipluspen.h.
     {
         if (!customCap) return lastStatus = InvalidParameter;
         // FIXME: do we need to call GdipDeleteCustomLineCap first?
         return updateStatus(DllExports::GdipGetPenCustomStartCap(
                 nativePen, &customCap->nativeCustomLineCap));
     }
References GdipGetPenCustomStartCap(), InvalidParameter, lastStatus, CustomLineCap::nativeCustomLineCap, nativePen, and updateStatus().
GetDashCap()
DashCap Pen::GetDashCap () const inline
Definition at line 119 of file gdipluspen.h.
     {
         DashCap result = DashCapFlat;
         updateStatus(DllExports::GdipGetPenDashCap197819(
                 nativePen, &result));
         return result;
     }
References DashCapFlat, GdipGetPenDashCap197819(), nativePen, and updateStatus().
GetDashOffset()
REAL Pen::GetDashOffset () const inline
Definition at line 126 of file gdipluspen.h.
     {
         REAL result = 0.0f;
         updateStatus(DllExports::GdipGetPenDashOffset(
                 nativePen, &result));
         return result;
     }
References GdipGetPenDashOffset(), nativePen, and updateStatus().
GetDashPattern()
Status Pen::GetDashPattern (REAL * dashArray, INT count) const inline
Definition at line 133 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipGetPenDashArray(
                 nativePen, dashArray, count));
     }
References GdipGetPenDashArray(), nativePen, and updateStatus().
GetDashPatternCount()
INT Pen::GetDashPatternCount () const inline
Definition at line 138 of file gdipluspen.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetPenDashCount(
                 nativePen, &result));
         return result;
     }
References GdipGetPenDashCount(), nativePen, and updateStatus().
GetDashStyle()
DashStyle Pen::GetDashStyle () const inline
Definition at line 145 of file gdipluspen.h.
     {
         DashStyle result = DashStyleSolid;
         updateStatus(DllExports::GdipGetPenDashStyle(
                 nativePen, &result));
         return result;
     }
References DashStyleSolid, GdipGetPenDashStyle(), nativePen, and updateStatus().
GetEndCap()
LineCap Pen::GetEndCap () const inline
Definition at line 152 of file gdipluspen.h.
     {
         LineCap result = LineCapFlat;
         updateStatus(DllExports::GdipGetPenEndCap(nativePen, &result));
         return result;
     }
References GdipGetPenEndCap(), LineCapFlat, nativePen, and updateStatus().
GetLastStatus()
Status Pen::GetLastStatus () const inline
Definition at line 158 of file gdipluspen.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetLineJoin()
LineJoin Pen::GetLineJoin () const inline
Definition at line 164 of file gdipluspen.h.
     {
         LineJoin result = LineJoinMiter;
         updateStatus(DllExports::GdipGetPenLineJoin(
                 nativePen, &result));
         return result;
     }
References GdipGetPenLineJoin(), LineJoinMiter, nativePen, and updateStatus().
GetMiterLimit()
REAL Pen::GetMiterLimit () const inline
Definition at line 171 of file gdipluspen.h.
     {
         REAL result = 10.0f;
         updateStatus(DllExports::GdipGetPenMiterLimit(
                 nativePen, &result));
         return result;
     }
References GdipGetPenMiterLimit(), nativePen, and updateStatus().
GetPenType()
PenType Pen::GetPenType () const inline
Definition at line 178 of file gdipluspen.h.
     {
         PenType result = PenTypeUnknown;
         updateStatus(DllExports::GdipGetPenFillType(
                 nativePen, &result));
         return result;
     }
References GdipGetPenFillType(), nativePen, PenTypeUnknown, and updateStatus().
GetStartCap()
LineCap Pen::GetStartCap () const inline
Definition at line 185 of file gdipluspen.h.
     {
         LineCap result = LineCapFlat;
         updateStatus(DllExports::GdipGetPenStartCap(
                 nativePen, &result));
         return result;
     }
References GdipGetPenStartCap(), LineCapFlat, nativePen, and updateStatus().
GetTransform()
Status Pen::GetTransform (Matrix * matrix) const inline
Definition at line 192 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipGetPenTransform(
                 nativePen,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipGetPenTransform(), nativePen, NULL, and updateStatus().
GetWidth()
REAL Pen::GetWidth () const inline
Definition at line 198 of file gdipluspen.h.
     {
         REAL result = 1.0f;
         updateStatus(DllExports::GdipGetPenWidth(nativePen, &result));
         return result;
     }
References GdipGetPenWidth(), nativePen, and updateStatus().
MultiplyTransform()
Status Pen::MultiplyTransform (const Matrix * matrix, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 204 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipMultiplyPenTransform(
                 nativePen,
                 matrix ? matrix->nativeMatrix : NULL, order));
     }
References GdipMultiplyPenTransform(), nativePen, NULL, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Pen& Pen::operator= (const Pen &) private
ResetTransform()
Status Pen::ResetTransform () inline
Definition at line 211 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipResetPenTransform(
                 nativePen));
     }
References GdipResetPenTransform(), nativePen, and updateStatus().
RotateTransform()
Status Pen::RotateTransform (REAL angle, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 216 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipRotatePenTransform(
                 nativePen, angle, order));
     }
References GdipRotatePenTransform(), nativePen, and updateStatus().
ScaleTransform()
Status Pen::ScaleTransform (REAL sx, REAL sy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 222 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipScalePenTransform(
                 nativePen, sx, sy, order));
     }
References GdipScalePenTransform(), nativePen, sy, and updateStatus().
SetAlignment()
Status Pen::SetAlignment (PenAlignment penAlignment) inline
Definition at line 228 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenMode(
                 nativePen, penAlignment));
     }
References GdipSetPenMode(), nativePen, and updateStatus().
SetBrush()
Status Pen::SetBrush (const Brush * brush) inline
Definition at line 233 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenBrushFill(
                 nativePen, brush ? brush->nativeBrush : NULL));
     }
References GdipSetPenBrushFill(), Brush::nativeBrush, nativePen, NULL, and updateStatus().
SetColor()
Status Pen::SetColor (const Color & color) inline
Definition at line 238 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenColor(
                 nativePen, color.GetValue()));
     }
References GdipSetPenColor(), nativePen, and updateStatus().
SetCompoundArray()
Status Pen::SetCompoundArray (const REAL * compoundArray, INT count) inline
Definition at line 243 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenCompoundArray(
                 nativePen, compoundArray, count));
     }
References GdipSetPenCompoundArray(), nativePen, and updateStatus().
SetCustomEndCap()
Status Pen::SetCustomEndCap (const CustomLineCap * customCap) inline
Definition at line 248 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenCustomEndCap(
                 nativePen,
                 customCap ? customCap->nativeCustomLineCap : NULL));
     }
References GdipSetPenCustomEndCap(), CustomLineCap::nativeCustomLineCap, nativePen, NULL, and updateStatus().
SetCustomStartCap()
Status Pen::SetCustomStartCap (const CustomLineCap * customCap) inline
Definition at line 254 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenCustomStartCap(
                 nativePen,
                 customCap ? customCap->nativeCustomLineCap : NULL));
     }
References GdipSetPenCustomStartCap(), CustomLineCap::nativeCustomLineCap, nativePen, NULL, and updateStatus().
SetDashCap()
Status Pen::SetDashCap (DashCap dashCap) inline
Definition at line 260 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenDashCap197819(
                 nativePen, dashCap));
     }
References GdipSetPenDashCap197819(), nativePen, and updateStatus().
SetDashOffset()
Status Pen::SetDashOffset (REAL dashOffset) inline
Definition at line 265 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenDashOffset(
                 nativePen, dashOffset));
     }
References GdipSetPenDashOffset(), nativePen, and updateStatus().
SetDashPattern()
Status Pen::SetDashPattern (const REAL * dashArray, INT count) inline
Definition at line 270 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenDashArray(
                 nativePen, dashArray, count));
     }
References GdipSetPenDashArray(), nativePen, and updateStatus().
SetDashStyle()
Status Pen::SetDashStyle (DashStyle dashStyle) inline
Definition at line 275 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenDashStyle(
                 nativePen, dashStyle));
     }
References GdipSetPenDashStyle(), nativePen, and updateStatus().
SetEndCap()
Status Pen::SetEndCap (LineCap endCap) inline
Definition at line 280 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenEndCap(
                 nativePen, endCap));
     }
References GdipSetPenEndCap(), nativePen, and updateStatus().
SetLineCap()
Status Pen::SetLineCap (LineCap startCap, LineCap endCap, DashCap dashCap) inline
Definition at line 285 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenLineCap197819(
                 nativePen, startCap, endCap, dashCap));
     }
References GdipSetPenLineCap197819(), nativePen, and updateStatus().
SetLineJoin()
Status Pen::SetLineJoin (LineJoin lineJoin) inline
Definition at line 290 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenLineJoin(
                 nativePen, lineJoin));
     }
References GdipSetPenLineJoin(), nativePen, and updateStatus().
SetMiterLimit()
Status Pen::SetMiterLimit (REAL miterLimit) inline
Definition at line 295 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenMiterLimit(
                 nativePen, miterLimit));
     }
References GdipSetPenMiterLimit(), nativePen, and updateStatus().
SetStartCap()
Status Pen::SetStartCap (LineCap startCap) inline
Definition at line 300 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenStartCap(
                 nativePen, startCap));
     }
References GdipSetPenStartCap(), nativePen, and updateStatus().
SetTransform()
Status Pen::SetTransform (const Matrix * matrix) inline
Definition at line 305 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenTransform(
                 nativePen,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipSetPenTransform(), nativePen, NULL, and updateStatus().
SetWidth()
Status Pen::SetWidth (REAL width) inline
Definition at line 311 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipSetPenWidth(
                 nativePen, width));
     }
References GdipSetPenWidth(), nativePen, and updateStatus().
TranslateTransform()
Status Pen::TranslateTransform (REAL dx, REAL dy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 316 of file gdipluspen.h.
     {
         return updateStatus(DllExports::GdipTranslatePenTransform(
                 nativePen, dx, dy, order));
     }
References GdipTranslatePenTransform(), nativePen, and updateStatus().
updateStatus()
Status Pen::updateStatus (Status newStatus) const inline private
Definition at line 328 of file gdipluspen.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by Clone(), GetAlignment(), GetColor(), GetCompoundArray(), GetCompoundArrayCount(), GetCustomEndCap(), GetCustomStartCap(), GetDashCap(), GetDashOffset(), GetDashPattern(), GetDashPatternCount(), GetDashStyle(), GetEndCap(), GetLineJoin(), GetMiterLimit(), GetPenType(), GetStartCap(), GetTransform(), GetWidth(), MultiplyTransform(), ResetTransform(), RotateTransform(), ScaleTransform(), SetAlignment(), SetBrush(), SetColor(), SetCompoundArray(), SetCustomEndCap(), SetCustomStartCap(), SetDashCap(), SetDashOffset(), SetDashPattern(), SetDashStyle(), SetEndCap(), SetLineCap(), SetLineJoin(), SetMiterLimit(), SetStartCap(), SetTransform(), SetWidth(), and TranslateTransform().
Friends And Related Function Documentation
Graphics
friend class Graphics friend
Definition at line 35 of file gdipluspen.h.
GraphicsPath
friend class GraphicsPath friend
Definition at line 36 of file gdipluspen.h.
Field Documentation
lastStatus
Status Pen::lastStatus mutable private
Definition at line 335 of file gdipluspen.h.
Referenced by Clone(), GetCustomEndCap(), GetCustomStartCap(), GetLastStatus(), Pen(), and updateStatus().
nativePen
GpPen* Pen::nativePen private
Definition at line 334 of file gdipluspen.h.
Referenced by Clone(), Graphics::DrawArc(), Graphics::DrawBezier(), Graphics::DrawBeziers(), Graphics::DrawClosedCurve(), Graphics::DrawCurve(), Graphics::DrawEllipse(), Graphics::DrawLine(), Graphics::DrawLines(), Graphics::DrawPath(), Graphics::DrawPie(), Graphics::DrawPolygon(), Graphics::DrawRectangle(), Graphics::DrawRectangles(), GetAlignment(), GetColor(), GetCompoundArray(), GetCompoundArrayCount(), GetCustomEndCap(), GetCustomStartCap(), GetDashCap(), GetDashOffset(), GetDashPattern(), GetDashPatternCount(), GetDashStyle(), GetEndCap(), GetLineJoin(), GetMiterLimit(), GetPenType(), GetStartCap(), GetTransform(), GetWidth(), GraphicsPath::IsOutlineVisible(), MultiplyTransform(), Pen(), ResetTransform(), RotateTransform(), ScaleTransform(), SetAlignment(), SetBrush(), SetColor(), SetCompoundArray(), SetCustomEndCap(), SetCustomStartCap(), SetDashCap(), SetDashOffset(), SetDashPattern(), SetDashStyle(), SetEndCap(), SetLineCap(), SetLineJoin(), SetMiterLimit(), SetStartCap(), SetTransform(), SetWidth(), TranslateTransform(), GraphicsPath::Widen(), and ~Pen().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdipluspen.h