ZEQ2-Lite: Tools/MinGW/include/winbase.h File Reference
winbase.h File Reference
Data Structures
struct _BY_HANDLE_FILE_INFORMATION
struct _COMM_CONFIG
struct _COMMPROP
struct _COMMTIMEOUTS
struct _COMSTAT
struct _CREATE_PROCESS_DEBUG_INFO
struct _CREATE_THREAD_DEBUG_INFO
struct _CRITICAL_SECTION
struct _CRITICAL_SECTION_DEBUG
struct _DCB
struct _DEBUG_EVENT
struct _EXCEPTION_DEBUG_INFO
struct _EXIT_PROCESS_DEBUG_INFO
struct _EXIT_THREAD_DEBUG_INFO
struct _FILETIME
struct _LDT_ENTRY
struct _LOAD_DLL_DEBUG_INFO
struct _MEMORYSTATUS
struct _OFSTRUCT
struct _OUTPUT_DEBUG_STRING_INFO
struct LPWSAOVERLAPPED
struct _PROCESS_HEAP_ENTRY
struct _PROCESS_INFORMATION
struct _RIP_INFO
struct _STARTUPINFOA
struct _STARTUPINFOW
struct _SYSTEM_INFO
struct _SYSTEM_POWER_STATUS
struct _SYSTEMTIME
struct _TIME_ZONE_INFORMATION
struct _UNLOAD_DLL_DEBUG_INFO
struct _WIN32_FILE_ATTRIBUTE_DATA
struct _WIN32_FIND_DATAA
struct _WIN32_FIND_DATAW
struct _WIN32_STREAM_ID
struct _WIN_CERTIFICATE
struct tagHW_PROFILE_INFOA
struct tagHW_PROFILE_INFOW
Macros
#define __GNUC_EXTENSION
#define __INTERLOCKED_DECLARED
#define AbnormalTermination() FALSE
#define ABOVE_NORMAL_PRIORITY_CLASS 0x00008000
#define AC_LINE_BACKUP_POWER 2
#define AC_LINE_OFFLINE 0
#define AC_LINE_ONLINE 1
#define AC_LINE_UNKNOWN 255
#define AccessCheckAndAuditAlarm AccessCheckAndAuditAlarmA
#define AddAtom AddAtomA
#define BACKUP_ALTERNATE_DATA 4
#define BACKUP_DATA 1
#define BACKUP_EA_DATA 2
#define BACKUP_INVALID 0
#define BACKUP_LINK 5
#define BACKUP_OBJECT_ID 7
#define BACKUP_PROPERTY_DATA 6
#define BACKUP_REPARSE_DATA 8
#define BACKUP_SECURITY_DATA 3
#define BACKUP_SPARSE_BLOCK 9
#define BackupEventLog BackupEventLogA
#define BATTERY_FLAG_CHARGING 8
#define BATTERY_FLAG_CRITICAL 4
#define BATTERY_FLAG_HIGH 1
#define BATTERY_FLAG_LOW 2
#define BATTERY_FLAG_NO_BATTERY 128
#define BATTERY_FLAG_UNKNOWN 255
#define BATTERY_LIFE_UNKNOWN 0xFFFFFFFF
#define BATTERY_PERCENTAGE_UNKNOWN 255
#define BAUD_075 1
#define BAUD_110 2
#define BAUD_115200 131072
#define BAUD_1200 64
#define BAUD_128K 65536
#define BAUD_134_5 4
#define BAUD_14400 4096
#define BAUD_150 8
#define BAUD_1800 128
#define BAUD_19200 8192
#define BAUD_2400 256
#define BAUD_300 16
#define BAUD_38400 16384
#define BAUD_4800 512
#define BAUD_56K 32768
#define BAUD_57600 262144
#define BAUD_600 32
#define BAUD_7200 1024
#define BAUD_9600 2048
#define BAUD_USER 0x10000000
#define BeginUpdateResource BeginUpdateResourceA
#define BELOW_NORMAL_PRIORITY_CLASS 0x00004000
#define BuildCommDCB BuildCommDCBA
#define BuildCommDCBAndTimeouts BuildCommDCBAndTimeoutsA
#define CALLBACK_CHUNK_FINISHED 0
#define CALLBACK_STREAM_SWITCH 1
#define CallNamedPipe CallNamedPipeA
#define CBR_110 110
#define CBR_115200 115200
#define CBR_1200 1200
#define CBR_128000 128000
#define CBR_14400 14400
#define CBR_19200 19200
#define CBR_2400 2400
#define CBR_256000 256000
#define CBR_300 300
#define CBR_38400 38400
#define CBR_4800 4800
#define CBR_56000 56000
#define CBR_57600 57600
#define CBR_600 600
#define CBR_9600 9600
#define CE_BREAK 16
#define CE_DNS 2048
#define CE_FRAME 8
#define CE_IOE 1024
#define CE_MODE 32768
#define CE_OOP 4096
#define CE_OVERRUN 2
#define CE_PTO 512
#define CE_RXOVER 1
#define CE_RXPARITY 4
#define CE_TXFULL 256
#define ClearEventLog ClearEventLogA
#define CLRBREAK 9
#define CLRDTR 6
#define CLRRTS 4
#define CommConfigDialog CommConfigDialogA
#define CONSOLE_TEXTMODE_BUFFER 1
#define CONTROL_C_EXIT STATUS_CONTROL_C_EXIT
#define COPY_FILE_FAIL_IF_EXISTS 0x0001
#define COPY_FILE_OPEN_SOURCE_FOR_WRITE 0x0004
#define COPY_FILE_RESTARTABLE 0x0002
#define CopyFile CopyFileA
#define CopyFileEx CopyFileExA
#define CopyMemory RtlCopyMemory
#define CREATE_ALWAYS 2
#define CREATE_BREAKAWAY_FROM_JOB 0x01000000
#define CREATE_DEFAULT_ERROR_MODE 0x04000000
#define CREATE_FORCEDOS 0x00002000
#define CREATE_NEW 1
#define CREATE_NEW_CONSOLE 0x00000010
#define CREATE_NEW_PROCESS_GROUP 0x00000200
#define CREATE_NO_WINDOW 0x08000000
#define CREATE_PROCESS_DEBUG_EVENT 3
#define CREATE_SEPARATE_WOW_VDM 0x00000800
#define CREATE_SHARED_WOW_VDM 0x00001000
#define CREATE_SUSPENDED 0x00000004
#define CREATE_THREAD_DEBUG_EVENT 2
#define CREATE_UNICODE_ENVIRONMENT 0x00000400
#define CREATE_WITH_USERPROFILE 0x02000000
#define CreateDirectory CreateDirectoryA
#define CreateDirectoryEx CreateDirectoryExA
#define CreateEvent CreateEventA
#define CreateFile CreateFileA
#define CreateFileMapping CreateFileMappingA
#define CreateMailslot CreateMailslotA
#define CreateMutex CreateMutexA
#define CreateNamedPipe CreateNamedPipeA
#define CreateProcess CreateProcessA
#define CreateProcessAsUser CreateProcessAsUserA
#define CreateSemaphore CreateSemaphoreA
#define CreateWaitableTimer CreateWaitableTimerA
#define DATABITS_16 16
#define DATABITS_16X 32
#define DATABITS_5 1
#define DATABITS_6 2
#define DATABITS_7 4
#define DATABITS_8 8
#define DDD_EXACT_MATCH_ON_REMOVE 4
#define DDD_RAW_TARGET_PATH 1
#define DDD_REMOVE_DEFINITION 2
#define DEBUG_ONLY_THIS_PROCESS 0x00000002
#define DEBUG_PROCESS 0x00000001
#define DefineDosDevice DefineDosDeviceA
#define DefineHandleTable(w) ((w),TRUE)
#define DeleteFile DeleteFileA
#define DETACHED_PROCESS 0x00000008
#define DOCKINFO_DOCKED 2
#define DOCKINFO_UNDOCKED 1
#define DOCKINFO_USER_DOCKED (DOCKINFO_USER_SUPPLIED|DOCKINFO_DOCKED)
#define DOCKINFO_USER_SUPPLIED 4
#define DOCKINFO_USER_UNDOCKED (DOCKINFO_USER_SUPPLIED|DOCKINFO_UNDOCKED)
#define DONT_RESOLVE_DLL_REFERENCES 1
#define DRIVE_CDROM 5
#define DRIVE_FIXED 3
#define DRIVE_NO_ROOT_DIR 1
#define DRIVE_RAMDISK 6
#define DRIVE_REMOTE 4
#define DRIVE_REMOVABLE 2
#define DRIVE_UNKNOWN 0
#define DTR_CONTROL_DISABLE 0
#define DTR_CONTROL_ENABLE 1
#define DTR_CONTROL_HANDSHAKE 2
#define EncryptFile EncryptFileA
#define EndUpdateResource EndUpdateResourceA
#define ENUMRESLANGPROC ENUMRESLANGPROCA
#define ENUMRESNAMEPROC ENUMRESNAMEPROCA
#define EnumResourceLanguages EnumResourceLanguagesA
#define EnumResourceNames EnumResourceNamesA
#define EnumResourceTypes EnumResourceTypesA
#define ENUMRESTYPEPROC ENUMRESTYPEPROCA
#define EV_BREAK 64
#define EV_CTS 8
#define EV_DSR 16
#define EV_ERR 128
#define EV_EVENT1 2048
#define EV_EVENT2 4096
#define EV_PERR 512
#define EV_RING 256
#define EV_RLSD 32
#define EV_RX80FULL 1024
#define EV_RXCHAR 1
#define EV_RXFLAG 2
#define EV_TXEMPTY 4
#define EVENPARITY 2
#define EVENT_ALL_ACCESS 0x1f0003
#define EVENT_MODIFY_STATE 2
#define EVENTLOG_AUDIT_FAILURE 16
#define EVENTLOG_AUDIT_SUCCESS 8
#define EVENTLOG_BACKWARDS_READ 8
#define EVENTLOG_ERROR_TYPE 1
#define EVENTLOG_FORWARDS_READ 4
#define EVENTLOG_INFORMATION_TYPE 4
#define EVENTLOG_SEEK_READ 2
#define EVENTLOG_SEQUENTIAL_READ 1
#define EVENTLOG_SUCCESS 0
#define EVENTLOG_WARNING_TYPE 2
#define EXCEPTION_ACCESS_VIOLATION STATUS_ACCESS_VIOLATION
#define EXCEPTION_ARRAY_BOUNDS_EXCEEDED STATUS_ARRAY_BOUNDS_EXCEEDED
#define EXCEPTION_BREAKPOINT STATUS_BREAKPOINT
#define EXCEPTION_CONTINUE_EXECUTION (-1)
#define EXCEPTION_CONTINUE_SEARCH 0
#define EXCEPTION_DATATYPE_MISALIGNMENT STATUS_DATATYPE_MISALIGNMENT
#define EXCEPTION_DEBUG_EVENT 1
#define EXCEPTION_EXECUTE_HANDLER 1
#define EXCEPTION_FLT_DENORMAL_OPERAND STATUS_FLOAT_DENORMAL_OPERAND
#define EXCEPTION_FLT_DIVIDE_BY_ZERO STATUS_FLOAT_DIVIDE_BY_ZERO
#define EXCEPTION_FLT_INEXACT_RESULT STATUS_FLOAT_INEXACT_RESULT
#define EXCEPTION_FLT_INVALID_OPERATION STATUS_FLOAT_INVALID_OPERATION
#define EXCEPTION_FLT_OVERFLOW STATUS_FLOAT_OVERFLOW
#define EXCEPTION_FLT_STACK_CHECK STATUS_FLOAT_STACK_CHECK
#define EXCEPTION_FLT_UNDERFLOW STATUS_FLOAT_UNDERFLOW
#define EXCEPTION_GUARD_PAGE STATUS_GUARD_PAGE_VIOLATION
#define EXCEPTION_ILLEGAL_INSTRUCTION STATUS_ILLEGAL_INSTRUCTION
#define EXCEPTION_IN_PAGE_ERROR STATUS_IN_PAGE_ERROR
#define EXCEPTION_INT_DIVIDE_BY_ZERO STATUS_INTEGER_DIVIDE_BY_ZERO
#define EXCEPTION_INT_OVERFLOW STATUS_INTEGER_OVERFLOW
#define EXCEPTION_INVALID_DISPOSITION STATUS_INVALID_DISPOSITION
#define EXCEPTION_INVALID_HANDLE STATUS_INVALID_HANDLE
#define EXCEPTION_NONCONTINUABLE_EXCEPTION STATUS_NONCONTINUABLE_EXCEPTION
#define EXCEPTION_PRIV_INSTRUCTION STATUS_PRIVILEGED_INSTRUCTION
#define EXCEPTION_SINGLE_STEP STATUS_SINGLE_STEP
#define EXCEPTION_STACK_OVERFLOW STATUS_STACK_OVERFLOW
#define EXIT_PROCESS_DEBUG_EVENT 5
#define EXIT_THREAD_DEBUG_EVENT 4
#define ExpandEnvironmentStrings ExpandEnvironmentStringsA
#define FatalAppExit FatalAppExitA
#define FILE_BEGIN 0
#define FILE_CURRENT 1
#define FILE_ENCRYPTABLE 0
#define FILE_END 2
#define FILE_FLAG_BACKUP_SEMANTICS 33554432
#define FILE_FLAG_DELETE_ON_CLOSE 67108864
#define FILE_FLAG_NO_BUFFERING 536870912
#define FILE_FLAG_OPEN_NO_RECALL 1048576
#define FILE_FLAG_OPEN_REPARSE_POINT 2097152
#define FILE_FLAG_OVERLAPPED 1073741824
#define FILE_FLAG_POSIX_SEMANTICS 16777216
#define FILE_FLAG_RANDOM_ACCESS 268435456
#define FILE_FLAG_SEQUENTIAL_SCAN 134217728
#define FILE_FLAG_WRITE_THROUGH 0x80000000
#define FILE_IS_ENCRYPTED 1
#define FILE_MAP_ALL_ACCESS 0xf001f
#define FILE_MAP_COPY 1
#define FILE_MAP_READ 4
#define FILE_MAP_WRITE 2
#define FILE_READ_ONLY 8
#define FILE_ROOT_DIR 3
#define FILE_SYSTEM_ATTR 2
#define FILE_SYSTEM_DIR 4
#define FILE_SYSTEM_NOT_SUPPORT 6
#define FILE_TYPE_CHAR 2
#define FILE_TYPE_DISK 1
#define FILE_TYPE_PIPE 3
#define FILE_TYPE_REMOTE 0x8000
#define FILE_TYPE_UNKNOWN 0
#define FILE_UNKNOWN 5
#define FILE_USER_DISALLOWED 7
#define FileEncryptionStatus FileEncryptionStatusA
#define FillMemory RtlFillMemory
#define FIND_FIRST_EX_CASE_SENSITIVE 1
#define FindAtom FindAtomA
#define FindFirstChangeNotification FindFirstChangeNotificationA
#define FindFirstFile FindFirstFileA
#define FindFirstFileEx FindFirstFileExA
#define FindNextFile FindNextFileA
#define FindResource FindResourceA
#define FindResourceEx FindResourceExA
#define FORMAT_MESSAGE_ALLOCATE_BUFFER 256
#define FORMAT_MESSAGE_ARGUMENT_ARRAY 8192
#define FORMAT_MESSAGE_FROM_HMODULE 2048
#define FORMAT_MESSAGE_FROM_STRING 1024
#define FORMAT_MESSAGE_FROM_SYSTEM 4096
#define FORMAT_MESSAGE_IGNORE_INSERTS 512
#define FORMAT_MESSAGE_MAX_WIDTH_MASK 255
#define FormatMessage FormatMessageA
#define FreeEnvironmentStrings FreeEnvironmentStringsA
#define FreeModule(m) FreeLibrary(m)
#define FreeProcInstance(p) (void)(p)
#define FS_CASE_IS_PRESERVED 2
#define FS_CASE_SENSITIVE 1
#define FS_FILE_COMPRESSION 16
#define FS_PERSISTENT_ACLS 8
#define FS_UNICODE_STORED_ON_DISK 4
#define FS_VOL_IS_COMPRESSED 32768
#define GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS 0x00000004
#define GET_MODULE_HANDLE_EX_FLAG_PIN 0x00000001
#define GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT 0x00000002
#define GET_TAPE_DRIVE_INFORMATION 1
#define GET_TAPE_MEDIA_INFORMATION 0
#define GetAtomName GetAtomNameA
#define GetBinaryType GetBinaryTypeA
#define GetCommandLine GetCommandLineA
#define GetCompressedFileSize GetCompressedFileSizeA
#define GetComputerName GetComputerNameA
#define GetCurrentDirectory GetCurrentDirectoryA
#define GetCurrentTime GetTickCount
#define GetDefaultCommConfig GetDefaultCommConfigA
#define GetDiskFreeSpace GetDiskFreeSpaceA
#define GetDiskFreeSpaceEx GetDiskFreeSpaceExA
#define GetDriveType GetDriveTypeA
#define GetEnvironmentVariable GetEnvironmentVariableA
#define GetFileAttributes GetFileAttributesA
#define GetFileAttributesEx GetFileAttributesExA
#define GetFileSecurity GetFileSecurityA
#define GetFreeSpace(w) (0x100000L)
#define GetFullPathName GetFullPathNameA
#define GetLogicalDriveStrings GetLogicalDriveStringsA
#define GetModuleFileName GetModuleFileNameA
#define GetModuleHandle GetModuleHandleA
#define GetNamedPipeHandleState GetNamedPipeHandleStateA
#define GetPrivateProfileInt GetPrivateProfileIntA
#define GetPrivateProfileSection GetPrivateProfileSectionA
#define GetPrivateProfileSectionNames GetPrivateProfileSectionNamesA
#define GetPrivateProfileString GetPrivateProfileStringA
#define GetPrivateProfileStruct GetPrivateProfileStructA
#define GetProfileInt GetProfileIntA
#define GetProfileSection GetProfileSectionA
#define GetProfileString GetProfileStringA
#define GetShortPathName GetShortPathNameA
#define GetStartupInfo GetStartupInfoA
#define GetSystemDirectory GetSystemDirectoryA
#define GetTempFileName GetTempFileNameA
#define GetTempPath GetTempPathA
#define GetUserName GetUserNameA
#define GetVersionEx GetVersionExA
#define GetVolumeInformation GetVolumeInformationA
#define GetVolumeNameForVolumeMountPoint GetVolumeNameForVolumeMountPointA
#define GetVolumePathName GetVolumePathNameA
#define GetVolumePathNamesForVolumeName GetVolumePathNamesForVolumeNameA
#define GetWindowsDirectory GetWindowsDirectoryA
#define GHND 66
#define GlobalAddAtom GlobalAddAtomA
#define GlobalDiscard(hMem) GlobalReAlloc((hMem), 0, GMEM_MOVEABLE)
#define GlobalFindAtom GlobalFindAtomA
#define GlobalGetAtomName GlobalGetAtomNameA
#define GMEM_DDESHARE 8192
#define GMEM_DISCARDABLE 256
#define GMEM_DISCARDED 16384
#define GMEM_FIXED 0
#define GMEM_INVALID_HANDLE 32768
#define GMEM_LOCKCOUNT 255
#define GMEM_LOWER 4096
#define GMEM_MODIFY 128
#define GMEM_MOVEABLE 2
#define GMEM_NOCOMPACT 16
#define GMEM_NODISCARD 32
#define GMEM_NOT_BANKED 4096
#define GMEM_NOTIFY 16384
#define GMEM_SHARE 8192
#define GMEM_VALID_FLAGS 32626
#define GMEM_ZEROINIT 64
#define GPTR 64
#define HANDLE_FLAG_INHERIT 0x01
#define HANDLE_FLAG_PROTECT_FROM_CLOSE 0x02
#define HasOverlappedIoCompleted(lpOverlapped) ((lpOverlapped)->Internal != STATUS_PENDING)
#define HFILE_ERROR ((HFILE)-1)
#define HIGH_PRIORITY_CLASS 0x00000080
#define HINSTANCE_ERROR 32
#define HW_PROFILE_GUIDLEN 39
#define IDLE_PRIORITY_CLASS 0x00000040
#define IGNORE 0
#define INFINITE 0xFFFFFFFF
#define InterlockedCompareExchangePointer(d, e, c) (PVOID)InterlockedCompareExchange((LONG volatile *)(d),(LONG)(e),(LONG)(c))
#define InterlockedExchangePointer(t, v) (PVOID)InterlockedExchange((LONG volatile *)(t),(LONG)(v))
#define INVALID_ATOM ((ATOM)0)
#define INVALID_FILE_SIZE 0xFFFFFFFF
#define INVALID_HANDLE_VALUE (HANDLE)(-1)
#define INVALID_SET_FILE_POINTER ((DWORD)-1)
#define IsBadStringPtr IsBadStringPtrA
#define LHND 66
#define LimitEmsPages(n)
#define LMEM_DISCARDABLE 3840
#define LMEM_DISCARDED 16384
#define LMEM_FIXED 0
#define LMEM_INVALID_HANDLE 32768
#define LMEM_LOCKCOUNT 255
#define LMEM_MODIFY 128
#define LMEM_MOVEABLE 2
#define LMEM_NOCOMPACT 16
#define LMEM_NODISCARD 32
#define LMEM_NONZEROLHND 2
#define LMEM_NONZEROLPTR 0
#define LMEM_ZEROINIT 64
#define LOAD_DLL_DEBUG_EVENT 6
#define LOAD_LIBRARY_AS_DATAFILE 2
#define LOAD_WITH_ALTERED_SEARCH_PATH 8
#define LoadLibrary LoadLibraryA
#define LoadLibraryEx LoadLibraryExA
#define LOCKFILE_EXCLUSIVE_LOCK 2
#define LOCKFILE_FAIL_IMMEDIATELY 1
#define LockSegment(w) GlobalFix((HANDLE)(w)) /* Obsolete: Has no effect. */
#define LOGON32_LOGON_BATCH 4
#define LOGON32_LOGON_INTERACTIVE 2
#define LOGON32_LOGON_NETWORK 3
#define LOGON32_LOGON_SERVICE 5
#define LOGON32_LOGON_UNLOCK 7
#define LOGON32_PROVIDER_DEFAULT 0
#define LOGON32_PROVIDER_WINNT35 1
#define LogonUser LogonUserA
#define LookupAccountName LookupAccountNameA
#define LookupAccountSid LookupAccountSidA
#define LookupPrivilegeDisplayName LookupPrivilegeDisplayNameA
#define LookupPrivilegeName LookupPrivilegeNameA
#define LookupPrivilegeValue LookupPrivilegeValueA
#define LPTR 64
#define lstrcat lstrcatA
#define lstrcmp lstrcmpA
#define lstrcmpi lstrcmpiA
#define lstrcpy lstrcpyA
#define lstrcpyn lstrcpynA
#define lstrlen lstrlenA
#define MAKEINTATOM(i) (LPTSTR)((DWORD)((WORD)(i)))
#define MakeProcInstance(p, i) (p)
#define MARKPARITY 3
#define MAX_COMPUTERNAME_LENGTH 15
#define MAX_PROFILE_LEN 80
#define MAXIMUM_SUSPEND_COUNT 0x7F
#define MAXIMUM_WAIT_OBJECTS 64
#define MAXINTATOM 0xC000
#define MoveFile MoveFileA
#define MOVEFILE_COPY_ALLOWED 2
#define MOVEFILE_DELAY_UNTIL_REBOOT 4
#define MOVEFILE_REPLACE_EXISTING 1
#define MOVEFILE_WRITE_THROUGH 8
#define MoveFileEx MoveFileExA
#define MoveMemory RtlMoveMemory
#define MS_CTS_ON 16
#define MS_DSR_ON 32
#define MS_RING_ON 64
#define MS_RLSD_ON 128
#define MUTEX_ALL_ACCESS 0x1f0001
#define MUTEX_MODIFY_STATE 1
#define NMPWAIT_NOWAIT 1
#define NMPWAIT_USE_DEFAULT_WAIT 0
#define NMPWAIT_WAIT_FOREVER ((DWORD)-1)
#define NONZEROLHND 2
#define NONZEROLPTR 0
#define NOPARITY 0
#define NORMAL_PRIORITY_CLASS 0x00000020
#define ObjectCloseAuditAlarm ObjectCloseAuditAlarmA
#define ObjectDeleteAuditAlarm ObjectDeleteAuditAlarmA
#define ObjectOpenAuditAlarm ObjectOpenAuditAlarmA
#define ObjectPrivilegeAuditAlarm ObjectPrivilegeAuditAlarmA
#define ODDPARITY 1
#define OF_CANCEL 2048
#define OF_CREATE 4096
#define OF_DELETE 512
#define OF_EXIST 16384
#define OF_PARSE 256
#define OF_PROMPT 8192
#define OF_READ 0
#define OF_READWRITE 2
#define OF_REOPEN 32768
#define OF_SHARE_COMPAT 0
#define OF_SHARE_DENY_NONE 64
#define OF_SHARE_DENY_READ 48
#define OF_SHARE_DENY_WRITE 32
#define OF_SHARE_EXCLUSIVE 16
#define OF_VERIFY 1024
#define OF_WRITE 1
#define OFS_MAXPATHNAME 128
#define ONE5STOPBITS 1
#define ONESTOPBIT 0
#define OPEN_ALWAYS 4
#define OPEN_EXISTING 3
#define OpenBackupEventLog OpenBackupEventLogA
#define OpenEvent OpenEventA
#define OpenEventLog OpenEventLogA
#define OpenFileMapping OpenFileMappingA
#define OpenMutex OpenMutexA
#define OpenSemaphore OpenSemaphoreA
#define OUTPUT_DEBUG_STRING_EVENT 8
#define OutputDebugString OutputDebugStringA
#define PARITY_EVEN 1024
#define PARITY_MARK 2048
#define PARITY_NONE 256
#define PARITY_ODD 512
#define PARITY_SPACE 4096
#define PCF_16BITMODE 512
#define PCF_DTRDSR 1
#define PCF_INTTIMEOUTS 128
#define PCF_PARITY_CHECK 8
#define PCF_RLSD 4
#define PCF_RTSCTS 2
#define PCF_SETXCHAR 32
#define PCF_SPECIALCHARS 256
#define PCF_TOTALTIMEOUTS 64
#define PCF_XONXOFF 16
#define PIPE_ACCESS_DUPLEX 3
#define PIPE_ACCESS_INBOUND 1
#define PIPE_ACCESS_OUTBOUND 2
#define PIPE_CLIENT_END 0
#define PIPE_NOWAIT 1
#define PIPE_READMODE_BYTE 0
#define PIPE_READMODE_MESSAGE 2
#define PIPE_SERVER_END 1
#define PIPE_TYPE_BYTE 0
#define PIPE_TYPE_MESSAGE 4
#define PIPE_UNLIMITED_INSTANCES 255
#define PIPE_WAIT 0
#define PrivilegedServiceAuditAlarm PrivilegedServiceAuditAlarmA
#define PROCESS_HEAP_ENTRY_BUSY 4
#define PROCESS_HEAP_ENTRY_DDESHARE 32
#define PROCESS_HEAP_ENTRY_MOVEABLE 16
#define PROCESS_HEAP_REGION 1
#define PROCESS_HEAP_UNCOMMITTED_RANGE 2
#define PROFILE_KERNEL 0x20000000
#define PROFILE_SERVER 0x40000000
#define PROFILE_USER 0x10000000
#define PROGRESS_CANCEL 1
#define PROGRESS_CONTINUE 0
#define PROGRESS_QUIET 3
#define PROGRESS_STOP 2
#define PST_FAX 0x21
#define PST_LAT 0x101
#define PST_MODEM 6
#define PST_NETWORK_BRIDGE 0x100
#define PST_PARALLELPORT 2
#define PST_RS232 1
#define PST_RS422 3
#define PST_RS423 4
#define PST_RS449 5
#define PST_SCANNER 0x22
#define PST_TCPIP_TELNET 0x102
#define PST_UNSPECIFIED 0
#define PST_X25 0x103
#define PURGE_RXABORT 2
#define PURGE_RXCLEAR 8
#define PURGE_TXABORT 1
#define PURGE_TXCLEAR 4
#define QueryDosDevice QueryDosDeviceA
#define ReadEventLog ReadEventLogA
#define REALTIME_PRIORITY_CLASS 0x00000100
#define RegisterEventSource RegisterEventSourceA
#define RemoveDirectory RemoveDirectoryA
#define ReportEvent ReportEventA
#define RIP_EVENT 9
#define RtlCopyMemory memcpy
#define RtlFillMemory(d, l, f) memset((d), (f), (l))
#define RtlMoveMemory memmove
#define RtlZeroMemory(d, l) RtlFillMemory((d),(l),0)
#define RTS_CONTROL_DISABLE 0
#define RTS_CONTROL_ENABLE 1
#define RTS_CONTROL_HANDSHAKE 2
#define RTS_CONTROL_TOGGLE 3
#define SCS_32BIT_BINARY 0
#define SCS_64BIT_BINARY 6
#define SCS_DOS_BINARY 1
#define SCS_OS216_BINARY 5
#define SCS_PIF_BINARY 3
#define SCS_POSIX_BINARY 4
#define SCS_WOW_BINARY 2
#define SearchPath SearchPathA
#define SECURITY_ANONYMOUS (SecurityAnonymous<<16)
#define SECURITY_CONTEXT_TRACKING 0x40000
#define SECURITY_DELEGATION (SecurityDelegation<<16)
#define SECURITY_EFFECTIVE_ONLY 0x80000
#define SECURITY_IDENTIFICATION (SecurityIdentification<<16)
#define SECURITY_IMPERSONATION (SecurityImpersonation<<16)
#define SECURITY_SQOS_PRESENT 0x100000
#define SECURITY_VALID_SQOS_FLAGS 0x1F0000
#define SEM_FAILCRITICALERRORS 0x0001
#define SEM_NOALIGNMENTFAULTEXCEPT 0x0004
#define SEM_NOGPFAULTERRORBOX 0x0002
#define SEM_NOOPENFILEERRORBOX 0x8000
#define SEMAPHORE_ALL_ACCESS 0x1f0003
#define SEMAPHORE_MODIFY_STATE 2
#define SET_TAPE_DRIVE_INFORMATION 1
#define SET_TAPE_MEDIA_INFORMATION 0
#define SETBREAK 8
#define SetComputerName SetComputerNameA
#define SetCurrentDirectory SetCurrentDirectoryA
#define SetDefaultCommConfig SetDefaultCommConfigA
#define SETDTR 5
#define SetEnvironmentVariable SetEnvironmentVariableA
#define SetFileAttributes SetFileAttributesA
#define SetFileSecurity SetFileSecurityA
#define SETRTS 3
#define SetSwapAreaSize(w) (w)
#define SetVolumeLabel SetVolumeLabelA
#define SetVolumeMountPoint SetVolumeMountPointA
#define SETXOFF 1
#define SETXON 2
#define SHUTDOWN_NORETRY 1
#define SLE_ERROR 1
#define SLE_MINORERROR 2
#define SLE_WARNING 3
#define SP_BAUD 2
#define SP_DATABITS 4
#define SP_HANDSHAKING 16
#define SP_PARITY 1
#define SP_PARITY_CHECK 32
#define SP_RLSD 64
#define SP_SERIALCOMM 1
#define SP_STOPBITS 8
#define SPACEPARITY 4
#define STARTF_FORCEOFFFEEDBACK 128
#define STARTF_FORCEONFEEDBACK 64
#define STARTF_RUNFULLSCREEN 32
#define STARTF_USECOUNTCHARS 8
#define STARTF_USEFILLATTRIBUTE 16
#define STARTF_USEHOTKEY 512
#define STARTF_USEPOSITION 4
#define STARTF_USESHOWWINDOW 1
#define STARTF_USESIZE 2
#define STARTF_USESTDHANDLES 256
#define STATUS_ABANDONED_WAIT_0 0x80
#define STATUS_ACCESS_VIOLATION 0xC0000005
#define STATUS_ARRAY_BOUNDS_EXCEEDED 0xC000008C
#define STATUS_BREAKPOINT 0x80000003
#define STATUS_CONTROL_C_EXIT 0xC000013A
#define STATUS_DATATYPE_MISALIGNMENT 0x80000002
#define STATUS_DLL_INIT_FAILED 0xC0000142
#define STATUS_DLL_INIT_FAILED_LOGOFF 0xC000026B
#define STATUS_FLOAT_DENORMAL_OPERAND 0xC000008D
#define STATUS_FLOAT_DIVIDE_BY_ZERO 0xC000008E
#define STATUS_FLOAT_INEXACT_RESULT 0xC000008F
#define STATUS_FLOAT_INVALID_OPERATION 0xC0000090
#define STATUS_FLOAT_OVERFLOW 0xC0000091
#define STATUS_FLOAT_STACK_CHECK 0xC0000092
#define STATUS_FLOAT_UNDERFLOW 0xC0000093
#define STATUS_GUARD_PAGE_VIOLATION 0x80000001
#define STATUS_ILLEGAL_INSTRUCTION 0xC000001D
#define STATUS_IN_PAGE_ERROR 0xC0000006
#define STATUS_INTEGER_DIVIDE_BY_ZERO 0xC0000094
#define STATUS_INTEGER_OVERFLOW 0xC0000095
#define STATUS_INVALID_DISPOSITION 0xC0000026
#define STATUS_INVALID_HANDLE 0xC0000008L
#define STATUS_NO_MEMORY 0xC0000017
#define STATUS_NONCONTINUABLE_EXCEPTION 0xC0000025
#define STATUS_PENDING 0x103
#define STATUS_PRIVILEGED_INSTRUCTION 0xC0000096
#define STATUS_SEGMENT_NOTIFICATION 0x40000005
#define STATUS_SINGLE_STEP 0x80000004
#define STATUS_STACK_OVERFLOW 0xC00000FD
#define STATUS_TIMEOUT 0x102
#define STATUS_USER_APC 0xC0
#define STATUS_WAIT_0 0
#define STD_ERROR_HANDLE (DWORD)(0xfffffff4)
#define STD_INPUT_HANDLE (DWORD)(0xfffffff6)
#define STD_OUTPUT_HANDLE (DWORD)(0xfffffff5)
#define STILL_ACTIVE 0x103
#define STOPBITS_10 1
#define STOPBITS_15 2
#define STOPBITS_20 4
#define STREAM_CONTAINS_PROPERTIES 4
#define STREAM_CONTAINS_SECURITY 2
#define STREAM_MODIFIED_WHEN_READ 1
#define STREAM_NORMAL_ATTRIBUTE 0
#define SYMBOLIC_LINK_FLAG_DIRECTORY 0x1
#define TC_GP_TRAP 2
#define TC_HARDERR 1
#define TC_NORMAL 0
#define TC_SIGNAL 3
#define THREAD_PRIORITY_ABOVE_NORMAL 1
#define THREAD_PRIORITY_BELOW_NORMAL (-1)
#define THREAD_PRIORITY_ERROR_RETURN 2147483647
#define THREAD_PRIORITY_HIGHEST 2
#define THREAD_PRIORITY_IDLE (-15)
#define THREAD_PRIORITY_LOWEST (-2)
#define THREAD_PRIORITY_NORMAL 0
#define THREAD_PRIORITY_TIME_CRITICAL 15
#define TIME_ZONE_ID_DAYLIGHT 2
#define TIME_ZONE_ID_INVALID 0xFFFFFFFF
#define TIME_ZONE_ID_STANDARD 1
#define TIME_ZONE_ID_UNKNOWN 0
#define TLS_OUT_OF_INDEXES (DWORD)0xFFFFFFFF
#define TRUNCATE_EXISTING 5
#define TWOSTOPBITS 2
#define UNLOAD_DLL_DEBUG_EVENT 7
#define UnlockResource(h) (h)
#define UnlockSegment(w) GlobalUnfix((HANDLE)(w)) /* Obsolete: Has no effect. */
#define UpdateResource UpdateResourceA
#define VerifyVersionInfo VerifyVersionInfoA
#define WAIT_ABANDONED 128
#define WAIT_ABANDONED_0 128
#define WAIT_FAILED ((DWORD)0xFFFFFFFF)
#define WAIT_IO_COMPLETION 0xC0
#define WAIT_OBJECT_0 0
#define WAIT_TIMEOUT 258
#define WaitNamedPipe WaitNamedPipeA
#define WINADVAPI
#define WINBASEAPI
#define WRITE_WATCH_FLAG_RESET 1
#define WritePrivateProfileSection WritePrivateProfileSectionA
#define WritePrivateProfileString WritePrivateProfileStringA
#define WritePrivateProfileStruct WritePrivateProfileStructA
#define WriteProfileSection WriteProfileSectionA
#define WriteProfileString WriteProfileStringA
#define Yield()
#define ZeroMemory RtlZeroMemory
Typedefs
typedef BOOL(CALLBACK * ENUMRESLANGPROCA) (HMODULE, LPCSTR, LPCSTR, WORD, LONG)
typedef BOOL(CALLBACK * ENUMRESLANGPROCW) (HMODULE, LPCWSTR, LPCWSTR, WORD, LONG)
typedef BOOL(CALLBACK * ENUMRESNAMEPROCA) (HMODULE, LPCSTR, LPSTR, LONG)
typedef BOOL(CALLBACK * ENUMRESNAMEPROCW) (HMODULE, LPCWSTR, LPWSTR, LONG)
typedef BOOL(CALLBACK * ENUMRESTYPEPROCA) (HMODULE, LPSTR, LONG)
typedef BOOL(CALLBACK * ENUMRESTYPEPROCW) (HMODULE, LPWSTR, LONG)
typedef HW_PROFILE_INFOA HW_PROFILE_INFO
typedef struct BY_HANDLE_FILE_INFORMATION * LPBY_HANDLE_FILE_INFORMATION
typedef struct COMMCONFIG * LPCOMMCONFIG
typedef struct COMMPROP * LPCOMMPROP
typedef struct COMMTIMEOUTS * LPCOMMTIMEOUTS
typedef struct COMSTAT * LPCOMSTAT
typedef struct CREATE_PROCESS_DEBUG_INFO * LPCREATE_PROCESS_DEBUG_INFO
typedef struct CREATE_THREAD_DEBUG_INFO * LPCREATE_THREAD_DEBUG_INFO
typedef struct CRITICAL_SECTION * LPCRITICAL_SECTION
typedef struct DCB * LPDCB
typedef struct DEBUG_EVENT * LPDEBUG_EVENT
typedef struct EXCEPTION_DEBUG_INFO * LPEXCEPTION_DEBUG_INFO
typedef struct EXIT_PROCESS_DEBUG_INFO * LPEXIT_PROCESS_DEBUG_INFO
typedef struct EXIT_THREAD_DEBUG_INFO * LPEXIT_THREAD_DEBUG_INFO
typedef void(WINAPI * LPFIBER_START_ROUTINE) (PVOID)
typedef struct FILETIME * LPFILETIME
typedef HW_PROFILE_INFOA * LPHW_PROFILE_INFO
typedef struct HW_PROFILE_INFOA * LPHW_PROFILE_INFOA
typedef struct HW_PROFILE_INFOW * LPHW_PROFILE_INFOW
typedef struct LDT_ENTRY * LPLDT_ENTRY
typedef struct LOAD_DLL_DEBUG_INFO * LPLOAD_DLL_DEBUG_INFO
typedef struct MEMORYSTATUS * LPMEMORYSTATUS
typedef struct OFSTRUCT * LPOFSTRUCT
typedef struct OUTPUT_DEBUG_STRING_INFO * LPOUTPUT_DEBUG_STRING_INFO
typedef struct OVERLAPPED * LPOVERLAPPED
typedef void(CALLBACK * LPOVERLAPPED_COMPLETION_ROUTINE) (DWORD, DWORD, LPOVERLAPPED)
typedef struct PROCESS_HEAP_ENTRY * LPPROCESS_HEAP_ENTRY
typedef struct PROCESS_INFORMATION * LPPROCESS_INFORMATION
typedef DWORD(WINAPI * LPPROGRESS_ROUTINE) (LARGE_INTEGER, LARGE_INTEGER, LARGE_INTEGER, LARGE_INTEGER, DWORD, DWORD, HANDLE, HANDLE, LPVOID)
typedef struct RIP_INFO * LPRIP_INFO
typedef STARTUPINFOA * LPSTARTUPINFO
typedef struct STARTUPINFOA * LPSTARTUPINFOA
typedef struct STARTUPINFOW * LPSTARTUPINFOW
typedef struct SYSTEM_INFO * LPSYSTEM_INFO
typedef struct SYSTEM_POWER_STATUS * LPSYSTEM_POWER_STATUS
typedef struct SYSTEMTIME * LPSYSTEMTIME
typedef DWORD(WINAPI * LPTHREAD_START_ROUTINE) (LPVOID)
typedef struct TIME_ZONE_INFORMATION * LPTIME_ZONE_INFORMATION
typedef PTOP_LEVEL_EXCEPTION_FILTER LPTOP_LEVEL_EXCEPTION_FILTER
typedef struct UNLOAD_DLL_DEBUG_INFO * LPUNLOAD_DLL_DEBUG_INFO
typedef struct WIN32_FILE_ATTRIBUTE_DATA * LPWIN32_FILE_ATTRIBUTE_DATA
typedef WIN32_FIND_DATAA * LPWIN32_FIND_DATA
typedef struct WIN32_FIND_DATAA * LPWIN32_FIND_DATAA
typedef struct WIN32_FIND_DATAW * LPWIN32_FIND_DATAW
typedef struct WIN32_STREAM_ID * LPWIN32_STREAM_ID
typedef struct WIN_CERTIFICATE * LPWIN_CERTIFICATE
typedef void(APIENTRY * PAPCFUNC) (ULONG_PTR)
typedef struct CRITICAL_SECTION * PCRITICAL_SECTION
typedef struct CRITICAL_SECTION_DEBUG * PCRITICAL_SECTION_DEBUG
typedef struct FILETIME * PFILETIME
typedef struct LDT_ENTRY * PLDT_ENTRY
typedef struct OFSTRUCT * POFSTRUCT
typedef struct OVERLAPPED * POVERLAPPED
typedef struct PROCESS_INFORMATION * PPROCESS_INFORMATION
typedef void(CALLBACK * PTIMERAPCROUTINE) (PVOID, DWORD, DWORD)
typedef LONG(CALLBACK * PTOP_LEVEL_EXCEPTION_FILTER) (LPEXCEPTION_POINTERS)
typedef WIN32_FIND_DATAA * PWIN32_FIND_DATA
typedef struct WIN32_FIND_DATAA * PWIN32_FIND_DATAA
typedef struct WIN32_FIND_DATAW * PWIN32_FIND_DATAW
typedef STARTUPINFOA STARTUPINFO
typedef WIN32_FIND_DATAA WIN32_FIND_DATA
Enumerations
enum _ACL_INFORMATION_CLASS { AclRevisionInformation =1, AclSizeInformation }
enum _FINDEX_INFO_LEVELS { FindExInfoStandard, FindExInfoMaxInfoLevel }
enum _FINDEX_SEARCH_OPS { FindExSearchNameMatch, FindExSearchLimitToDirectories, FindExSearchLimitToDevices, FindExSearchMaxSearchOp }
enum _GET_FILEEX_INFO_LEVELS { GetFileExInfoStandard, GetFileExMaxInfoLevel }
Functions
WINBASEAPI long WINAPI _hread (HFILE, LPVOID, long)
WINBASEAPI long WINAPI _hwrite (HFILE, LPCSTR, long)
WINBASEAPI HFILE WINAPI _lclose (HFILE)
WINBASEAPI HFILE WINAPI _lcreat (LPCSTR, int)
WINBASEAPI LONG WINAPI _llseek (HFILE, LONG, int)
WINBASEAPI HFILE WINAPI _lopen (LPCSTR, int)
WINBASEAPI UINT WINAPI _lread (HFILE, LPVOID, UINT)
WINBASEAPI UINT WINAPI _lwrite (HFILE, LPCSTR, UINT)
WINBASEAPI BOOL WINAPI AccessCheck (PSECURITY_DESCRIPTOR, HANDLE, DWORD, PGENERIC_MAPPING, PPRIVILEGE_SET, PDWORD, PDWORD, PBOOL)
WINBASEAPI BOOL WINAPI AccessCheckAndAuditAlarmA (LPCSTR, LPVOID, LPSTR, LPSTR, PSECURITY_DESCRIPTOR, DWORD, PGENERIC_MAPPING, BOOL, PDWORD, PBOOL, PBOOL)
WINBASEAPI BOOL WINAPI AccessCheckAndAuditAlarmW (LPCWSTR, LPVOID, LPWSTR, LPWSTR, PSECURITY_DESCRIPTOR, DWORD, PGENERIC_MAPPING, BOOL, PDWORD, PBOOL, PBOOL)
WINBASEAPI BOOL WINAPI AddAccessAllowedAce (PACL, DWORD, DWORD, PSID)
WINBASEAPI BOOL WINAPI AddAccessDeniedAce (PACL, DWORD, DWORD, PSID)
WINBASEAPI BOOL WINAPI AddAce (PACL, DWORD, DWORD, PVOID, DWORD)
WINBASEAPI ATOM WINAPI AddAtomA (LPCSTR)
WINBASEAPI ATOM WINAPI AddAtomW (LPCWSTR)
WINBASEAPI BOOL WINAPI AddAuditAccessAce (PACL, DWORD, DWORD, PSID, BOOL, BOOL)
WINBASEAPI BOOL WINAPI AdjustTokenGroups (HANDLE, BOOL, PTOKEN_GROUPS, DWORD, PTOKEN_GROUPS, PDWORD)
WINBASEAPI BOOL WINAPI AdjustTokenPrivileges (HANDLE, BOOL, PTOKEN_PRIVILEGES, DWORD, PTOKEN_PRIVILEGES, PDWORD)
WINBASEAPI BOOL WINAPI AllocateAndInitializeSid (PSID_IDENTIFIER_AUTHORITY, BYTE, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, PSID *)
WINBASEAPI BOOL WINAPI AllocateLocallyUniqueId (PLUID)
WINBASEAPI BOOL WINAPI AreAllAccessesGranted (DWORD, DWORD)
WINBASEAPI BOOL WINAPI AreAnyAccessesGranted (DWORD, DWORD)
WINBASEAPI BOOL WINAPI AreFileApisANSI (void)
WINBASEAPI BOOL WINAPI BackupEventLogA (HANDLE, LPCSTR)
WINBASEAPI BOOL WINAPI BackupEventLogW (HANDLE, LPCWSTR)
WINBASEAPI BOOL WINAPI BackupRead (HANDLE, LPBYTE, DWORD, LPDWORD, BOOL, BOOL, LPVOID *)
WINBASEAPI BOOL WINAPI BackupSeek (HANDLE, DWORD, DWORD, LPDWORD, LPDWORD, LPVOID *)
WINBASEAPI BOOL WINAPI BackupWrite (HANDLE, LPBYTE, DWORD, LPDWORD, BOOL, BOOL, LPVOID *)
WINBASEAPI BOOL WINAPI Beep (DWORD, DWORD)
WINBASEAPI HANDLE WINAPI BeginUpdateResourceA (LPCSTR, BOOL)
WINBASEAPI HANDLE WINAPI BeginUpdateResourceW (LPCWSTR, BOOL)
WINBASEAPI BOOL WINAPI BuildCommDCBA (LPCSTR, LPDCB)
WINBASEAPI BOOL WINAPI BuildCommDCBAndTimeoutsA (LPCSTR, LPDCB, LPCOMMTIMEOUTS)
WINBASEAPI BOOL WINAPI BuildCommDCBAndTimeoutsW (LPCWSTR, LPDCB, LPCOMMTIMEOUTS)
WINBASEAPI BOOL WINAPI BuildCommDCBW (LPCWSTR, LPDCB)
WINBASEAPI BOOL WINAPI CallNamedPipeA (LPCSTR, PVOID, DWORD, PVOID, DWORD, PDWORD, DWORD)
WINBASEAPI BOOL WINAPI CallNamedPipeW (LPCWSTR, PVOID, DWORD, PVOID, DWORD, PDWORD, DWORD)
WINBASEAPI BOOL WINAPI CancelDeviceWakeupRequest (HANDLE)
WINBASEAPI BOOL WINAPI CancelIo (HANDLE)
WINBASEAPI BOOL WINAPI CancelWaitableTimer (HANDLE)
WINBASEAPI BOOL WINAPI ClearCommBreak (HANDLE)
WINBASEAPI BOOL WINAPI ClearCommError (HANDLE, PDWORD, LPCOMSTAT)
WINBASEAPI BOOL WINAPI ClearEventLogA (HANDLE, LPCSTR)
WINBASEAPI BOOL WINAPI ClearEventLogW (HANDLE, LPCWSTR)
WINBASEAPI BOOL WINAPI CloseEventLog (HANDLE)
WINBASEAPI BOOL WINAPI CloseHandle (HANDLE)
WINBASEAPI BOOL WINAPI CommConfigDialogA (LPCSTR, HWND, LPCOMMCONFIG)
WINBASEAPI BOOL WINAPI CommConfigDialogW (LPCWSTR, HWND, LPCOMMCONFIG)
WINBASEAPI LONG WINAPI CompareFileTime (CONST FILETIME *, CONST FILETIME *)
WINBASEAPI BOOL WINAPI ConnectNamedPipe (HANDLE, LPOVERLAPPED)
WINBASEAPI BOOL WINAPI ContinueDebugEvent (DWORD, DWORD, DWORD)
WINBASEAPI PVOID WINAPI ConvertThreadToFiber (PVOID)
WINBASEAPI BOOL WINAPI CopyFileA (LPCSTR, LPCSTR, BOOL)
WINBASEAPI BOOL WINAPI CopyFileExA (LPCSTR, LPCSTR, LPPROGRESS_ROUTINE, LPVOID, LPBOOL, DWORD)
WINBASEAPI BOOL WINAPI CopyFileExW (LPCWSTR, LPCWSTR, LPPROGRESS_ROUTINE, LPVOID, LPBOOL, DWORD)
WINBASEAPI BOOL WINAPI CopyFileW (LPCWSTR, LPCWSTR, BOOL)
WINBASEAPI BOOL WINAPI CopySid (DWORD, PSID, PSID)
WINBASEAPI BOOL WINAPI CreateDirectoryA (LPCSTR, LPSECURITY_ATTRIBUTES)
WINBASEAPI BOOL WINAPI CreateDirectoryExA (LPCSTR, LPCSTR, LPSECURITY_ATTRIBUTES)
WINBASEAPI BOOL WINAPI CreateDirectoryExW (LPCWSTR, LPCWSTR, LPSECURITY_ATTRIBUTES)
WINBASEAPI BOOL WINAPI CreateDirectoryW (LPCWSTR, LPSECURITY_ATTRIBUTES)
WINBASEAPI HANDLE WINAPI CreateEventA (LPSECURITY_ATTRIBUTES, BOOL, BOOL, LPCSTR)
WINBASEAPI HANDLE WINAPI CreateEventW (LPSECURITY_ATTRIBUTES, BOOL, BOOL, LPCWSTR)
WINBASEAPI LPVOID WINAPI CreateFiber (SIZE_T, LPFIBER_START_ROUTINE, LPVOID)
WINBASEAPI HANDLE WINAPI CreateFileA (LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE)
WINBASEAPI HANDLE WINAPI CreateFileMappingA (HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR)
WINBASEAPI HANDLE WINAPI CreateFileMappingW (HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCWSTR)
WINBASEAPI HANDLE WINAPI CreateFileW (LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE)
WINBASEAPI HANDLE WINAPI CreateIoCompletionPort (HANDLE, HANDLE, ULONG_PTR, DWORD)
WINBASEAPI HANDLE WINAPI CreateMailslotA (LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES)
WINBASEAPI HANDLE WINAPI CreateMailslotW (LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES)
WINBASEAPI HANDLE WINAPI CreateMutexA (LPSECURITY_ATTRIBUTES, BOOL, LPCSTR)
WINBASEAPI HANDLE WINAPI CreateMutexW (LPSECURITY_ATTRIBUTES, BOOL, LPCWSTR)
WINBASEAPI HANDLE WINAPI CreateNamedPipeA (LPCSTR, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, LPSECURITY_ATTRIBUTES)
WINBASEAPI HANDLE WINAPI CreateNamedPipeW (LPCWSTR, DWORD, DWORD, DWORD, DWORD, DWORD, DWORD, LPSECURITY_ATTRIBUTES)
WINBASEAPI BOOL WINAPI CreatePipe (PHANDLE, PHANDLE, LPSECURITY_ATTRIBUTES, DWORD)
WINBASEAPI BOOL WINAPI CreatePrivateObjectSecurity (PSECURITY_DESCRIPTOR, PSECURITY_DESCRIPTOR, PSECURITY_DESCRIPTOR *, BOOL, HANDLE, PGENERIC_MAPPING)
WINBASEAPI BOOL WINAPI CreateProcessA (LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, PVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION)
WINBASEAPI BOOL WINAPI CreateProcessAsUserA (HANDLE, LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, PVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION)
WINBASEAPI BOOL WINAPI CreateProcessAsUserW (HANDLE, LPCWSTR, LPWSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, PVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION)
WINBASEAPI BOOL WINAPI CreateProcessW (LPCWSTR, LPWSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, PVOID, LPCWSTR, LPSTARTUPINFOW, LPPROCESS_INFORMATION)
WINBASEAPI HANDLE WINAPI CreateRemoteThread (HANDLE, LPSECURITY_ATTRIBUTES, DWORD, LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD)
WINBASEAPI HANDLE WINAPI CreateSemaphoreA (LPSECURITY_ATTRIBUTES, LONG, LONG, LPCSTR)
WINBASEAPI HANDLE WINAPI CreateSemaphoreW (LPSECURITY_ATTRIBUTES, LONG, LONG, LPCWSTR)
WINBASEAPI DWORD WINAPI CreateTapePartition (HANDLE, DWORD, DWORD, DWORD)
WINBASEAPI HANDLE WINAPI CreateThread (LPSECURITY_ATTRIBUTES, DWORD, LPTHREAD_START_ROUTINE, PVOID, DWORD, PDWORD)
WINBASEAPI HANDLE WINAPI CreateWaitableTimerA (LPSECURITY_ATTRIBUTES, BOOL, LPCSTR)
WINBASEAPI HANDLE WINAPI CreateWaitableTimerW (LPSECURITY_ATTRIBUTES, BOOL, LPCWSTR)
WINBASEAPI BOOL WINAPI DebugActiveProcess (DWORD)
WINBASEAPI void WINAPI DebugBreak (void)
WINBASEAPI BOOL WINAPI DefineDosDeviceA (DWORD, LPCSTR, LPCSTR)
WINBASEAPI BOOL WINAPI DefineDosDeviceW (DWORD, LPCWSTR, LPCWSTR)
WINBASEAPI BOOL WINAPI DeleteAce (PACL, DWORD)
WINBASEAPI ATOM WINAPI DeleteAtom (ATOM)
WINBASEAPI void WINAPI DeleteCriticalSection (PCRITICAL_SECTION)
WINBASEAPI void WINAPI DeleteFiber (PVOID)
WINBASEAPI BOOL WINAPI DeleteFileA (LPCSTR)
WINBASEAPI BOOL WINAPI DeleteFileW (LPCWSTR)
WINBASEAPI BOOL WINAPI DeregisterEventSource (HANDLE)
WINBASEAPI BOOL WINAPI DestroyPrivateObjectSecurity (PSECURITY_DESCRIPTOR *)
WINBASEAPI BOOL WINAPI DeviceIoControl (HANDLE, DWORD, PVOID, DWORD, PVOID, DWORD, PDWORD, POVERLAPPED)
WINBASEAPI BOOL WINAPI DisableThreadLibraryCalls (HMODULE)
WINBASEAPI BOOL WINAPI DisconnectNamedPipe (HANDLE)
WINBASEAPI BOOL WINAPI DosDateTimeToFileTime (WORD, WORD, LPFILETIME)
WINBASEAPI BOOL WINAPI DuplicateHandle (HANDLE, HANDLE, HANDLE, PHANDLE, DWORD, BOOL, DWORD)
WINBASEAPI BOOL WINAPI DuplicateToken (HANDLE, SECURITY_IMPERSONATION_LEVEL, PHANDLE)
WINBASEAPI BOOL WINAPI DuplicateTokenEx (HANDLE, DWORD, LPSECURITY_ATTRIBUTES, SECURITY_IMPERSONATION_LEVEL, TOKEN_TYPE, PHANDLE)
WINBASEAPI BOOL WINAPI EncryptFileA (LPCSTR)
WINBASEAPI BOOL WINAPI EncryptFileW (LPCWSTR)
WINBASEAPI BOOL WINAPI EndUpdateResourceA (HANDLE, BOOL)
WINBASEAPI BOOL WINAPI EndUpdateResourceW (HANDLE, BOOL)
WINBASEAPI void WINAPI EnterCriticalSection (LPCRITICAL_SECTION)
WINBASEAPI BOOL WINAPI EnumResourceLanguagesA (HMODULE, LPCSTR, LPCSTR, ENUMRESLANGPROCA, LONG_PTR)
WINBASEAPI BOOL WINAPI EnumResourceLanguagesW (HMODULE, LPCWSTR, LPCWSTR, ENUMRESLANGPROCW, LONG_PTR)
WINBASEAPI BOOL WINAPI EnumResourceNamesA (HMODULE, LPCSTR, ENUMRESNAMEPROCA, LONG_PTR)
WINBASEAPI BOOL WINAPI EnumResourceNamesW (HMODULE, LPCWSTR, ENUMRESNAMEPROCW, LONG_PTR)
WINBASEAPI BOOL WINAPI EnumResourceTypesA (HMODULE, ENUMRESTYPEPROCA, LONG_PTR)
WINBASEAPI BOOL WINAPI EnumResourceTypesW (HMODULE, ENUMRESTYPEPROCW, LONG_PTR)
WINBASEAPI BOOL WINAPI EqualPrefixSid (PSID, PSID)
WINBASEAPI BOOL WINAPI EqualSid (PSID, PSID)
WINBASEAPI DWORD WINAPI EraseTape (HANDLE, DWORD, BOOL)
WINBASEAPI BOOL WINAPI EscapeCommFunction (HANDLE, DWORD)
DECLSPEC_NORETURN WINBASEAPI void WINAPI ExitProcess (UINT)
DECLSPEC_NORETURN WINBASEAPI void WINAPI ExitThread (DWORD)
WINBASEAPI DWORD WINAPI ExpandEnvironmentStringsA (LPCSTR, LPSTR, DWORD)
WINBASEAPI DWORD WINAPI ExpandEnvironmentStringsW (LPCWSTR, LPWSTR, DWORD)
WINBASEAPI void WINAPI FatalAppExitA (UINT, LPCSTR)
WINBASEAPI void WINAPI FatalAppExitW (UINT, LPCWSTR)
WINBASEAPI void WINAPI FatalExit (int)
WINBASEAPI BOOL WINAPI FileEncryptionStatusA (LPCSTR, LPDWORD)
WINBASEAPI BOOL WINAPI FileEncryptionStatusW (LPCWSTR, LPDWORD)
WINBASEAPI BOOL WINAPI FileTimeToDosDateTime (CONST FILETIME *, LPWORD, LPWORD)
WINBASEAPI BOOL WINAPI FileTimeToLocalFileTime (CONST FILETIME *, LPFILETIME)
WINBASEAPI BOOL WINAPI FileTimeToSystemTime (CONST FILETIME *, LPSYSTEMTIME)
WINBASEAPI ATOM WINAPI FindAtomA (LPCSTR)
WINBASEAPI ATOM WINAPI FindAtomW (LPCWSTR)
WINBASEAPI BOOL WINAPI FindClose (HANDLE)
WINBASEAPI BOOL WINAPI FindCloseChangeNotification (HANDLE)
WINBASEAPI HANDLE WINAPI FindFirstChangeNotificationA (LPCSTR, BOOL, DWORD)
WINBASEAPI HANDLE WINAPI FindFirstChangeNotificationW (LPCWSTR, BOOL, DWORD)
WINBASEAPI HANDLE WINAPI FindFirstFileA (LPCSTR, LPWIN32_FIND_DATAA)
WINBASEAPI HANDLE WINAPI FindFirstFileExA (LPCSTR, FINDEX_INFO_LEVELS, PVOID, FINDEX_SEARCH_OPS, PVOID, DWORD)
WINBASEAPI HANDLE WINAPI FindFirstFileExW (LPCWSTR, FINDEX_INFO_LEVELS, PVOID, FINDEX_SEARCH_OPS, PVOID, DWORD)
WINBASEAPI HANDLE WINAPI FindFirstFileW (LPCWSTR, LPWIN32_FIND_DATAW)
WINBASEAPI BOOL WINAPI FindFirstFreeAce (PACL, PVOID *)
WINBASEAPI BOOL WINAPI FindNextChangeNotification (HANDLE)
WINBASEAPI BOOL WINAPI FindNextFileA (HANDLE, LPWIN32_FIND_DATAA)
WINBASEAPI BOOL WINAPI FindNextFileW (HANDLE, LPWIN32_FIND_DATAW)
WINBASEAPI HRSRC WINAPI FindResourceA (HMODULE, LPCSTR, LPCSTR)
WINBASEAPI HRSRC WINAPI FindResourceExA (HINSTANCE, LPCSTR, LPCSTR, WORD)
WINBASEAPI HRSRC WINAPI FindResourceExW (HINSTANCE, LPCWSTR, LPCWSTR, WORD)
WINBASEAPI HRSRC WINAPI FindResourceW (HINSTANCE, LPCWSTR, LPCWSTR)
WINBASEAPI BOOL WINAPI FlushFileBuffers (HANDLE)
WINBASEAPI BOOL WINAPI FlushInstructionCache (HANDLE, PCVOID, DWORD)
WINBASEAPI BOOL WINAPI FlushViewOfFile (PCVOID, DWORD)
WINBASEAPI DWORD WINAPI FormatMessageA (DWORD, PCVOID, DWORD, DWORD, LPSTR, DWORD, va_list *)
WINBASEAPI DWORD WINAPI FormatMessageW (DWORD, PCVOID, DWORD, DWORD, LPWSTR, DWORD, va_list *)
WINBASEAPI BOOL WINAPI FreeEnvironmentStringsA (LPSTR)
WINBASEAPI BOOL WINAPI FreeEnvironmentStringsW (LPWSTR)
WINBASEAPI BOOL WINAPI FreeLibrary (HMODULE)
DECLSPEC_NORETURN WINBASEAPI void WINAPI FreeLibraryAndExitThread (HMODULE, DWORD)
WINBASEAPI BOOL WINAPI FreeResource (HGLOBAL)
WINBASEAPI PVOID WINAPI FreeSid (PSID)
WINBASEAPI BOOL WINAPI GetAce (PACL, DWORD, LPVOID *)
WINBASEAPI BOOL WINAPI GetAclInformation (PACL, PVOID, DWORD, ACL_INFORMATION_CLASS)
WINBASEAPI UINT WINAPI GetAtomNameA (ATOM, LPSTR, int)
WINBASEAPI UINT WINAPI GetAtomNameW (ATOM, LPWSTR, int)
WINBASEAPI BOOL WINAPI GetBinaryTypeA (LPCSTR, PDWORD)
WINBASEAPI BOOL WINAPI GetBinaryTypeW (LPCWSTR, PDWORD)
WINBASEAPI LPSTR WINAPI GetCommandLineA (VOID)
WINBASEAPI LPWSTR WINAPI GetCommandLineW (VOID)
WINBASEAPI BOOL WINAPI GetCommConfig (HANDLE, LPCOMMCONFIG, PDWORD)
WINBASEAPI BOOL WINAPI GetCommMask (HANDLE, PDWORD)
WINBASEAPI BOOL WINAPI GetCommModemStatus (HANDLE, PDWORD)
WINBASEAPI BOOL WINAPI GetCommProperties (HANDLE, LPCOMMPROP)
WINBASEAPI BOOL WINAPI GetCommState (HANDLE, LPDCB)
WINBASEAPI BOOL WINAPI GetCommTimeouts (HANDLE, LPCOMMTIMEOUTS)
WINBASEAPI DWORD WINAPI GetCompressedFileSizeA (LPCSTR, PDWORD)
WINBASEAPI DWORD WINAPI GetCompressedFileSizeW (LPCWSTR, PDWORD)
WINBASEAPI BOOL WINAPI GetComputerNameA (LPSTR, PDWORD)
WINBASEAPI BOOL WINAPI GetComputerNameW (LPWSTR, PDWORD)
WINBASEAPI DWORD WINAPI GetCurrentDirectoryA (DWORD, LPSTR)
WINBASEAPI DWORD WINAPI GetCurrentDirectoryW (DWORD, LPWSTR)
WINBASEAPI BOOL WINAPI GetCurrentHwProfileA (LPHW_PROFILE_INFOA)
WINBASEAPI BOOL WINAPI GetCurrentHwProfileW (LPHW_PROFILE_INFOW)
WINBASEAPI HANDLE WINAPI GetCurrentProcess (void)
WINBASEAPI DWORD WINAPI GetCurrentProcessId (void)
WINBASEAPI HANDLE WINAPI GetCurrentThread (void)
WINBASEAPI DWORD WINAPI GetCurrentThreadId (void)
WINBASEAPI BOOL WINAPI GetDefaultCommConfigA (LPCSTR, LPCOMMCONFIG, PDWORD)
WINBASEAPI BOOL WINAPI GetDefaultCommConfigW (LPCWSTR, LPCOMMCONFIG, PDWORD)
WINBASEAPI BOOL WINAPI GetDevicePowerState (HANDLE, BOOL *)
WINBASEAPI BOOL WINAPI GetDiskFreeSpaceA (LPCSTR, PDWORD, PDWORD, PDWORD, PDWORD)
WINBASEAPI BOOL WINAPI GetDiskFreeSpaceExA (LPCSTR, PULARGE_INTEGER, PULARGE_INTEGER, PULARGE_INTEGER)
WINBASEAPI BOOL WINAPI GetDiskFreeSpaceExW (LPCWSTR, PULARGE_INTEGER, PULARGE_INTEGER, PULARGE_INTEGER)
WINBASEAPI BOOL WINAPI GetDiskFreeSpaceW (LPCWSTR, PDWORD, PDWORD, PDWORD, PDWORD)
WINBASEAPI UINT WINAPI GetDriveTypeA (LPCSTR)
WINBASEAPI UINT WINAPI GetDriveTypeW (LPCWSTR)
WINBASEAPI LPCH WINAPI GetEnvironmentStrings (void)
WINBASEAPI LPCH WINAPI GetEnvironmentStringsA (void)
WINBASEAPI LPWCH WINAPI GetEnvironmentStringsW (void)
WINBASEAPI DWORD WINAPI GetEnvironmentVariableA (LPCSTR, LPSTR, DWORD)
WINBASEAPI DWORD WINAPI GetEnvironmentVariableW (LPCWSTR, LPWSTR, DWORD)
WINBASEAPI BOOL WINAPI GetExitCodeProcess (HANDLE, PDWORD)
WINBASEAPI BOOL WINAPI GetExitCodeThread (HANDLE, PDWORD)
WINBASEAPI DWORD WINAPI GetFileAttributesA (LPCSTR)
WINBASEAPI BOOL WINAPI GetFileAttributesExA (LPCSTR, GET_FILEEX_INFO_LEVELS, PVOID)
WINBASEAPI BOOL WINAPI GetFileAttributesExW (LPCWSTR, GET_FILEEX_INFO_LEVELS, PVOID)
WINBASEAPI DWORD WINAPI GetFileAttributesW (LPCWSTR)
WINBASEAPI BOOL WINAPI GetFileInformationByHandle (HANDLE, LPBY_HANDLE_FILE_INFORMATION)
WINBASEAPI BOOL WINAPI GetFileSecurityA (LPCSTR, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR, DWORD, PDWORD)
WINBASEAPI BOOL WINAPI GetFileSecurityW (LPCWSTR, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR, DWORD, PDWORD)
WINBASEAPI DWORD WINAPI GetFileSize (HANDLE, PDWORD)
WINBASEAPI BOOL WINAPI GetFileTime (HANDLE, LPFILETIME, LPFILETIME, LPFILETIME)
WINBASEAPI DWORD WINAPI GetFileType (HANDLE)
WINBASEAPI DWORD WINAPI GetFullPathNameA (LPCSTR, DWORD, LPSTR, LPSTR *)
WINBASEAPI DWORD WINAPI GetFullPathNameW (LPCWSTR, DWORD, LPWSTR, LPWSTR *)
WINBASEAPI BOOL WINAPI GetHandleInformation (HANDLE, PDWORD)
WINBASEAPI BOOL WINAPI GetKernelObjectSecurity (HANDLE, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR, DWORD, PDWORD)
WINBASEAPI DWORD WINAPI GetLastError (void)
WINBASEAPI DWORD WINAPI GetLengthSid (PSID)
WINBASEAPI void WINAPI GetLocalTime (LPSYSTEMTIME)
WINBASEAPI DWORD WINAPI GetLogicalDrives (void)
WINBASEAPI DWORD WINAPI GetLogicalDriveStringsA (DWORD, LPSTR)
WINBASEAPI DWORD WINAPI GetLogicalDriveStringsW (DWORD, LPWSTR)
WINBASEAPI BOOL WINAPI GetMailslotInfo (HANDLE, PDWORD, PDWORD, PDWORD, PDWORD)
WINBASEAPI DWORD WINAPI GetModuleFileNameA (HINSTANCE, LPSTR, DWORD)
WINBASEAPI DWORD WINAPI GetModuleFileNameW (HINSTANCE, LPWSTR, DWORD)
WINBASEAPI HMODULE WINAPI GetModuleHandleA (LPCSTR)
WINBASEAPI HMODULE WINAPI GetModuleHandleW (LPCWSTR)
WINBASEAPI BOOL WINAPI GetNamedPipeHandleStateA (HANDLE, PDWORD, PDWORD, PDWORD, PDWORD, LPSTR, DWORD)
WINBASEAPI BOOL WINAPI GetNamedPipeHandleStateW (HANDLE, PDWORD, PDWORD, PDWORD, PDWORD, LPWSTR, DWORD)
WINBASEAPI BOOL WINAPI GetNamedPipeInfo (HANDLE, PDWORD, PDWORD, PDWORD, PDWORD)
WINBASEAPI BOOL WINAPI GetNumberOfEventLogRecords (HANDLE, PDWORD)
WINBASEAPI BOOL WINAPI GetOldestEventLogRecord (HANDLE, PDWORD)
WINBASEAPI BOOL WINAPI GetOverlappedResult (HANDLE, LPOVERLAPPED, PDWORD, BOOL)
WINBASEAPI DWORD WINAPI GetPriorityClass (HANDLE)
WINBASEAPI BOOL WINAPI GetPrivateObjectSecurity (PSECURITY_DESCRIPTOR, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR, DWORD, PDWORD)
WINBASEAPI UINT WINAPI GetPrivateProfileIntA (LPCSTR, LPCSTR, INT, LPCSTR)
WINBASEAPI UINT WINAPI GetPrivateProfileIntW (LPCWSTR, LPCWSTR, INT, LPCWSTR)
WINBASEAPI DWORD WINAPI GetPrivateProfileSectionA (LPCSTR, LPSTR, DWORD, LPCSTR)
WINBASEAPI DWORD WINAPI GetPrivateProfileSectionNamesA (LPSTR, DWORD, LPCSTR)
WINBASEAPI DWORD WINAPI GetPrivateProfileSectionNamesW (LPWSTR, DWORD, LPCWSTR)
WINBASEAPI DWORD WINAPI GetPrivateProfileSectionW (LPCWSTR, LPWSTR, DWORD, LPCWSTR)
WINBASEAPI DWORD WINAPI GetPrivateProfileStringA (LPCSTR, LPCSTR, LPCSTR, LPSTR, DWORD, LPCSTR)
WINBASEAPI DWORD WINAPI GetPrivateProfileStringW (LPCWSTR, LPCWSTR, LPCWSTR, LPWSTR, DWORD, LPCWSTR)
WINBASEAPI BOOL WINAPI GetPrivateProfileStructA (LPCSTR, LPCSTR, LPVOID, UINT, LPCSTR)
WINBASEAPI BOOL WINAPI GetPrivateProfileStructW (LPCWSTR, LPCWSTR, LPVOID, UINT, LPCWSTR)
WINBASEAPI FARPROC WINAPI GetProcAddress (HINSTANCE, LPCSTR)
WINBASEAPI BOOL WINAPI GetProcessAffinityMask (HANDLE, PDWORD, PDWORD)
WINBASEAPI HANDLE WINAPI GetProcessHeap (VOID)
WINBASEAPI DWORD WINAPI GetProcessHeaps (DWORD, PHANDLE)
WINBASEAPI BOOL WINAPI GetProcessPriorityBoost (HANDLE, PBOOL)
WINBASEAPI BOOL WINAPI GetProcessShutdownParameters (PDWORD, PDWORD)
WINBASEAPI BOOL WINAPI GetProcessTimes (HANDLE, LPFILETIME, LPFILETIME, LPFILETIME, LPFILETIME)
WINBASEAPI DWORD WINAPI GetProcessVersion (DWORD)
WINBASEAPI HWINSTA WINAPI GetProcessWindowStation (void)
WINBASEAPI BOOL WINAPI GetProcessWorkingSetSize (HANDLE, PSIZE_T, PSIZE_T)
WINBASEAPI UINT WINAPI GetProfileIntA (LPCSTR, LPCSTR, INT)
WINBASEAPI UINT WINAPI GetProfileIntW (LPCWSTR, LPCWSTR, INT)
WINBASEAPI DWORD WINAPI GetProfileSectionA (LPCSTR, LPSTR, DWORD)
WINBASEAPI DWORD WINAPI GetProfileSectionW (LPCWSTR, LPWSTR, DWORD)
WINBASEAPI DWORD WINAPI GetProfileStringA (LPCSTR, LPCSTR, LPCSTR, LPSTR, DWORD)
WINBASEAPI DWORD WINAPI GetProfileStringW (LPCWSTR, LPCWSTR, LPCWSTR, LPWSTR, DWORD)
WINBASEAPI BOOL WINAPI GetQueuedCompletionStatus (HANDLE, PDWORD, PULONG_PTR, LPOVERLAPPED *, DWORD)
WINBASEAPI BOOL WINAPI GetSecurityDescriptorControl (PSECURITY_DESCRIPTOR, PSECURITY_DESCRIPTOR_CONTROL, PDWORD)
WINBASEAPI BOOL WINAPI GetSecurityDescriptorDacl (PSECURITY_DESCRIPTOR, LPBOOL, PACL *, LPBOOL)
WINBASEAPI BOOL WINAPI GetSecurityDescriptorGroup (PSECURITY_DESCRIPTOR, PSID *, LPBOOL)
WINBASEAPI DWORD WINAPI GetSecurityDescriptorLength (PSECURITY_DESCRIPTOR)
WINBASEAPI BOOL WINAPI GetSecurityDescriptorOwner (PSECURITY_DESCRIPTOR, PSID *, LPBOOL)
WINBASEAPI BOOL WINAPI GetSecurityDescriptorSacl (PSECURITY_DESCRIPTOR, LPBOOL, PACL *, LPBOOL)
WINBASEAPI DWORD WINAPI GetShortPathNameA (LPCSTR, LPSTR, DWORD)
WINBASEAPI DWORD WINAPI GetShortPathNameW (LPCWSTR, LPWSTR, DWORD)
WINBASEAPI PSID_IDENTIFIER_AUTHORITY WINAPI GetSidIdentifierAuthority (PSID)
WINBASEAPI DWORD WINAPI GetSidLengthRequired (UCHAR)
WINBASEAPI PDWORD WINAPI GetSidSubAuthority (PSID, DWORD)
WINBASEAPI PUCHAR WINAPI GetSidSubAuthorityCount (PSID)
WINBASEAPI VOID WINAPI GetStartupInfoA (LPSTARTUPINFOA)
WINBASEAPI VOID WINAPI GetStartupInfoW (LPSTARTUPINFOW)
WINBASEAPI HANDLE WINAPI GetStdHandle (DWORD)
WINBASEAPI UINT WINAPI GetSystemDirectoryA (LPSTR, UINT)
WINBASEAPI UINT WINAPI GetSystemDirectoryW (LPWSTR, UINT)
WINBASEAPI VOID WINAPI GetSystemInfo (LPSYSTEM_INFO)
WINBASEAPI BOOL WINAPI GetSystemPowerStatus (LPSYSTEM_POWER_STATUS)
WINBASEAPI VOID WINAPI GetSystemTime (LPSYSTEMTIME)
WINBASEAPI BOOL WINAPI GetSystemTimeAdjustment (PDWORD, PDWORD, PBOOL)
WINBASEAPI void WINAPI GetSystemTimeAsFileTime (LPFILETIME)
WINBASEAPI DWORD WINAPI GetTapeParameters (HANDLE, DWORD, PDWORD, PVOID)
WINBASEAPI DWORD WINAPI GetTapePosition (HANDLE, DWORD, PDWORD, PDWORD, PDWORD)
WINBASEAPI DWORD WINAPI GetTapeStatus (HANDLE)
WINBASEAPI UINT WINAPI GetTempFileNameA (LPCSTR, LPCSTR, UINT, LPSTR)
WINBASEAPI UINT WINAPI GetTempFileNameW (LPCWSTR, LPCWSTR, UINT, LPWSTR)
WINBASEAPI DWORD WINAPI GetTempPathA (DWORD, LPSTR)
WINBASEAPI DWORD WINAPI GetTempPathW (DWORD, LPWSTR)
WINBASEAPI BOOL WINAPI GetThreadContext (HANDLE, LPCONTEXT)
WINBASEAPI int WINAPI GetThreadPriority (HANDLE)
WINBASEAPI BOOL WINAPI GetThreadPriorityBoost (HANDLE, PBOOL)
WINBASEAPI BOOL WINAPI GetThreadSelectorEntry (HANDLE, DWORD, LPLDT_ENTRY)
WINBASEAPI BOOL WINAPI GetThreadTimes (HANDLE, LPFILETIME, LPFILETIME, LPFILETIME, LPFILETIME)
WINBASEAPI DWORD WINAPI GetTickCount (VOID)
WINBASEAPI DWORD WINAPI GetTimeZoneInformation (LPTIME_ZONE_INFORMATION)
WINBASEAPI BOOL WINAPI GetTokenInformation (HANDLE, TOKEN_INFORMATION_CLASS, PVOID, DWORD, PDWORD)
WINBASEAPI BOOL WINAPI GetUserNameA (LPSTR, PDWORD)
WINBASEAPI BOOL WINAPI GetUserNameW (LPWSTR, PDWORD)
WINBASEAPI DWORD WINAPI GetVersion (void)
WINBASEAPI BOOL WINAPI GetVersionExA (LPOSVERSIONINFOA)
WINBASEAPI BOOL WINAPI GetVersionExW (LPOSVERSIONINFOW)
WINBASEAPI BOOL WINAPI GetVolumeInformationA (LPCSTR, LPSTR, DWORD, PDWORD, PDWORD, PDWORD, LPSTR, DWORD)
WINBASEAPI BOOL WINAPI GetVolumeInformationW (LPCWSTR, LPWSTR, DWORD, PDWORD, PDWORD, PDWORD, LPWSTR, DWORD)
WINBASEAPI UINT WINAPI GetWindowsDirectoryA (LPSTR, UINT)
WINBASEAPI UINT WINAPI GetWindowsDirectoryW (LPWSTR, UINT)
WINBASEAPI DWORD WINAPI GetWindowThreadProcessId (HWND, PDWORD)
WINBASEAPI UINT WINAPI GetWriteWatch (DWORD, PVOID, SIZE_T, PVOID *, PULONG_PTR, PULONG)
WINBASEAPI ATOM WINAPI GlobalAddAtomA (LPCSTR)
WINBASEAPI ATOM WINAPI GlobalAddAtomW (LPCWSTR)
WINBASEAPI HGLOBAL WINAPI GlobalAlloc (UINT, DWORD)
WINBASEAPI SIZE_T WINAPI GlobalCompact (DWORD)
WINBASEAPI ATOM WINAPI GlobalDeleteAtom (ATOM)
WINBASEAPI ATOM WINAPI GlobalFindAtomA (LPCSTR)
WINBASEAPI ATOM WINAPI GlobalFindAtomW (LPCWSTR)
WINBASEAPI VOID WINAPI GlobalFix (HGLOBAL)
WINBASEAPI UINT WINAPI GlobalFlags (HGLOBAL)
WINBASEAPI HGLOBAL WINAPI GlobalFree (HGLOBAL)
WINBASEAPI UINT WINAPI GlobalGetAtomNameA (ATOM, LPSTR, int)
WINBASEAPI UINT WINAPI GlobalGetAtomNameW (ATOM, LPWSTR, int)
WINBASEAPI HGLOBAL WINAPI GlobalHandle (PCVOID)
WINBASEAPI LPVOID WINAPI GlobalLock (HGLOBAL)
WINBASEAPI VOID WINAPI GlobalMemoryStatus (LPMEMORYSTATUS)
WINBASEAPI HGLOBAL WINAPI GlobalReAlloc (HGLOBAL, DWORD, UINT)
WINBASEAPI DWORD WINAPI GlobalSize (HGLOBAL)
WINBASEAPI VOID WINAPI GlobalUnfix (HGLOBAL)
WINBASEAPI BOOL WINAPI GlobalUnlock (HGLOBAL)
WINBASEAPI BOOL WINAPI GlobalUnWire (HGLOBAL)
WINBASEAPI PVOID WINAPI GlobalWire (HGLOBAL)
WINBASEAPI PVOID WINAPI HeapAlloc (HANDLE, DWORD, DWORD)
SIZE_T WINAPI HeapCompact (HANDLE, DWORD)
WINBASEAPI HANDLE WINAPI HeapCreate (DWORD, DWORD, DWORD)
WINBASEAPI BOOL WINAPI HeapDestroy (HANDLE)
WINBASEAPI BOOL WINAPI HeapFree (HANDLE, DWORD, PVOID)
WINBASEAPI BOOL WINAPI HeapLock (HANDLE)
WINBASEAPI PVOID WINAPI HeapReAlloc (HANDLE, DWORD, PVOID, DWORD)
WINBASEAPI DWORD WINAPI HeapSize (HANDLE, DWORD, PCVOID)
WINBASEAPI BOOL WINAPI HeapUnlock (HANDLE)
WINBASEAPI BOOL WINAPI HeapValidate (HANDLE, DWORD, PCVOID)
WINBASEAPI BOOL WINAPI HeapWalk (HANDLE, LPPROCESS_HEAP_ENTRY)
WINBASEAPI BOOL WINAPI ImpersonateLoggedOnUser (HANDLE)
WINBASEAPI BOOL WINAPI ImpersonateNamedPipeClient (HANDLE)
WINBASEAPI BOOL WINAPI ImpersonateSelf (SECURITY_IMPERSONATION_LEVEL)
WINBASEAPI BOOL WINAPI InitAtomTable (DWORD)
WINBASEAPI BOOL WINAPI InitializeAcl (PACL, DWORD, DWORD)
WINBASEAPI VOID WINAPI InitializeCriticalSection (LPCRITICAL_SECTION)
WINBASEAPI BOOL WINAPI InitializeCriticalSectionAndSpinCount (LPCRITICAL_SECTION, DWORD)
WINBASEAPI BOOL WINAPI InitializeSecurityDescriptor (PSECURITY_DESCRIPTOR, DWORD)
WINBASEAPI BOOL WINAPI InitializeSid (PSID, PSID_IDENTIFIER_AUTHORITY, BYTE)
LONG WINAPI InterlockedCompareExchange (LONG volatile *, LONG, LONG)
LONG WINAPI InterlockedDecrement (LONG volatile *)
LONG WINAPI InterlockedExchange (LONG volatile *, LONG)
LONG WINAPI InterlockedExchangeAdd (LONG volatile *, LONG)
LONG WINAPI InterlockedIncrement (LONG volatile *)
WINBASEAPI BOOL WINAPI IsBadCodePtr (FARPROC)
WINBASEAPI BOOL WINAPI IsBadHugeReadPtr (PCVOID, UINT)
WINBASEAPI BOOL WINAPI IsBadHugeWritePtr (PVOID, UINT)
WINBASEAPI BOOL WINAPI IsBadReadPtr (PCVOID, UINT)
WINBASEAPI BOOL WINAPI IsBadStringPtrA (LPCSTR, UINT)
WINBASEAPI BOOL WINAPI IsBadStringPtrW (LPCWSTR, UINT)
WINBASEAPI BOOL WINAPI IsBadWritePtr (PVOID, UINT)
WINBASEAPI BOOL WINAPI IsDebuggerPresent (void)
WINBASEAPI BOOL WINAPI IsProcessorFeaturePresent (DWORD)
WINBASEAPI BOOL WINAPI IsSystemResumeAutomatic (void)
WINBASEAPI BOOL WINAPI IsTextUnicode (PCVOID, int, LPINT)
WINBASEAPI BOOL WINAPI IsValidAcl (PACL)
WINBASEAPI BOOL WINAPI IsValidSecurityDescriptor (PSECURITY_DESCRIPTOR)
WINBASEAPI BOOL WINAPI IsValidSid (PSID)
WINBASEAPI void WINAPI LeaveCriticalSection (LPCRITICAL_SECTION)
WINBASEAPI HINSTANCE WINAPI LoadLibraryA (LPCSTR)
WINBASEAPI HINSTANCE WINAPI LoadLibraryExA (LPCSTR, HANDLE, DWORD)
WINBASEAPI HINSTANCE WINAPI LoadLibraryExW (LPCWSTR, HANDLE, DWORD)
WINBASEAPI HINSTANCE WINAPI LoadLibraryW (LPCWSTR)
WINBASEAPI DWORD WINAPI LoadModule (LPCSTR, PVOID)
WINBASEAPI HGLOBAL WINAPI LoadResource (HINSTANCE, HRSRC)
WINBASEAPI HLOCAL WINAPI LocalAlloc (UINT, SIZE_T)
WINBASEAPI SIZE_T WINAPI LocalCompact (UINT)
WINBASEAPI HLOCAL LocalDiscard (HLOCAL)
WINBASEAPI BOOL WINAPI LocalFileTimeToFileTime (CONST FILETIME *, LPFILETIME)
WINBASEAPI UINT WINAPI LocalFlags (HLOCAL)
WINBASEAPI HLOCAL WINAPI LocalFree (HLOCAL)
WINBASEAPI HLOCAL WINAPI LocalHandle (LPCVOID)
WINBASEAPI PVOID WINAPI LocalLock (HLOCAL)
WINBASEAPI HLOCAL WINAPI LocalReAlloc (HLOCAL, SIZE_T, UINT)
WINBASEAPI SIZE_T WINAPI LocalShrink (HLOCAL, UINT)
WINBASEAPI UINT WINAPI LocalSize (HLOCAL)
WINBASEAPI BOOL WINAPI LocalUnlock (HLOCAL)
WINBASEAPI BOOL WINAPI LockFile (HANDLE, DWORD, DWORD, DWORD, DWORD)
WINBASEAPI BOOL WINAPI LockFileEx (HANDLE, DWORD, DWORD, DWORD, DWORD, LPOVERLAPPED)
WINBASEAPI PVOID WINAPI LockResource (HGLOBAL)
WINBASEAPI BOOL WINAPI LogonUserA (LPSTR, LPSTR, LPSTR, DWORD, DWORD, PHANDLE)
WINBASEAPI BOOL WINAPI LogonUserW (LPWSTR, LPWSTR, LPWSTR, DWORD, DWORD, PHANDLE)
WINBASEAPI BOOL WINAPI LookupAccountNameA (LPCSTR, LPCSTR, PSID, PDWORD, LPSTR, PDWORD, PSID_NAME_USE)
WINBASEAPI BOOL WINAPI LookupAccountNameW (LPCWSTR, LPCWSTR, PSID, PDWORD, LPWSTR, PDWORD, PSID_NAME_USE)
WINBASEAPI BOOL WINAPI LookupAccountSidA (LPCSTR, PSID, LPSTR, PDWORD, LPSTR, PDWORD, PSID_NAME_USE)
WINBASEAPI BOOL WINAPI LookupAccountSidW (LPCWSTR, PSID, LPWSTR, PDWORD, LPWSTR, PDWORD, PSID_NAME_USE)
WINBASEAPI BOOL WINAPI LookupPrivilegeDisplayNameA (LPCSTR, LPCSTR, LPSTR, PDWORD, PDWORD)
WINBASEAPI BOOL WINAPI LookupPrivilegeDisplayNameW (LPCWSTR, LPCWSTR, LPWSTR, PDWORD, PDWORD)
WINBASEAPI BOOL WINAPI LookupPrivilegeNameA (LPCSTR, PLUID, LPSTR, PDWORD)
WINBASEAPI BOOL WINAPI LookupPrivilegeNameW (LPCWSTR, PLUID, LPWSTR, PDWORD)
WINBASEAPI BOOL WINAPI LookupPrivilegeValueA (LPCSTR, LPCSTR, PLUID)
WINBASEAPI BOOL WINAPI LookupPrivilegeValueW (LPCWSTR, LPCWSTR, PLUID)
WINBASEAPI LPSTR WINAPI lstrcatA (LPSTR, LPCSTR)
WINBASEAPI LPWSTR WINAPI lstrcatW (LPWSTR, LPCWSTR)
WINBASEAPI int WINAPI lstrcmpA (LPCSTR, LPCSTR)
WINBASEAPI int WINAPI lstrcmpiA (LPCSTR, LPCSTR)
WINBASEAPI int WINAPI lstrcmpiW (LPCWSTR, LPCWSTR)
WINBASEAPI int WINAPI lstrcmpW (LPCWSTR, LPCWSTR)
WINBASEAPI LPSTR WINAPI lstrcpyA (LPSTR, LPCSTR)
WINBASEAPI LPSTR WINAPI lstrcpynA (LPSTR, LPCSTR, int)
WINBASEAPI LPWSTR WINAPI lstrcpynW (LPWSTR, LPCWSTR, int)
WINBASEAPI LPWSTR WINAPI lstrcpyW (LPWSTR, LPCWSTR)
WINBASEAPI int WINAPI lstrlenA (LPCSTR)
WINBASEAPI int WINAPI lstrlenW (LPCWSTR)
WINBASEAPI BOOL WINAPI MakeAbsoluteSD (PSECURITY_DESCRIPTOR, PSECURITY_DESCRIPTOR, PDWORD, PACL, PDWORD, PACL, PDWORD, PSID, PDWORD, PSID, PDWORD)
WINBASEAPI BOOL WINAPI MakeSelfRelativeSD (PSECURITY_DESCRIPTOR, PSECURITY_DESCRIPTOR, PDWORD)
WINBASEAPI VOID WINAPI MapGenericMask (PDWORD, PGENERIC_MAPPING)
WINBASEAPI PVOID WINAPI MapViewOfFile (HANDLE, DWORD, DWORD, DWORD, DWORD)
WINBASEAPI PVOID WINAPI MapViewOfFileEx (HANDLE, DWORD, DWORD, DWORD, DWORD, PVOID)
WINBASEAPI BOOL WINAPI MoveFileA (LPCSTR, LPCSTR)
WINBASEAPI BOOL WINAPI MoveFileExA (LPCSTR, LPCSTR, DWORD)
WINBASEAPI BOOL WINAPI MoveFileExW (LPCWSTR, LPCWSTR, DWORD)
WINBASEAPI BOOL WINAPI MoveFileW (LPCWSTR, LPCWSTR)
WINBASEAPI int WINAPI MulDiv (int, int, int)
WINBASEAPI BOOL WINAPI NotifyChangeEventLog (HANDLE, HANDLE)
WINBASEAPI BOOL WINAPI ObjectCloseAuditAlarmA (LPCSTR, PVOID, BOOL)
WINBASEAPI BOOL WINAPI ObjectCloseAuditAlarmW (LPCWSTR, PVOID, BOOL)
WINBASEAPI BOOL WINAPI ObjectDeleteAuditAlarmA (LPCSTR, PVOID, BOOL)
WINBASEAPI BOOL WINAPI ObjectDeleteAuditAlarmW (LPCWSTR, PVOID, BOOL)
WINBASEAPI BOOL WINAPI ObjectOpenAuditAlarmA (LPCSTR, PVOID, LPSTR, LPSTR, PSECURITY_DESCRIPTOR, HANDLE, DWORD, DWORD, PPRIVILEGE_SET, BOOL, BOOL, PBOOL)
WINBASEAPI BOOL WINAPI ObjectOpenAuditAlarmW (LPCWSTR, PVOID, LPWSTR, LPWSTR, PSECURITY_DESCRIPTOR, HANDLE, DWORD, DWORD, PPRIVILEGE_SET, BOOL, BOOL, PBOOL)
WINBASEAPI BOOL WINAPI ObjectPrivilegeAuditAlarmA (LPCSTR, PVOID, HANDLE, DWORD, PPRIVILEGE_SET, BOOL)
WINBASEAPI BOOL WINAPI ObjectPrivilegeAuditAlarmW (LPCWSTR, PVOID, HANDLE, DWORD, PPRIVILEGE_SET, BOOL)
WINBASEAPI HANDLE WINAPI OpenBackupEventLogA (LPCSTR, LPCSTR)
WINBASEAPI HANDLE WINAPI OpenBackupEventLogW (LPCWSTR, LPCWSTR)
WINBASEAPI HANDLE WINAPI OpenEventA (DWORD, BOOL, LPCSTR)
WINBASEAPI HANDLE WINAPI OpenEventLogA (LPCSTR, LPCSTR)
WINBASEAPI HANDLE WINAPI OpenEventLogW (LPCWSTR, LPCWSTR)
WINBASEAPI HANDLE WINAPI OpenEventW (DWORD, BOOL, LPCWSTR)
WINBASEAPI HFILE WINAPI OpenFile (LPCSTR, LPOFSTRUCT, UINT)
WINBASEAPI HANDLE WINAPI OpenFileMappingA (DWORD, BOOL, LPCSTR)
WINBASEAPI HANDLE WINAPI OpenFileMappingW (DWORD, BOOL, LPCWSTR)
WINBASEAPI HANDLE WINAPI OpenMutexA (DWORD, BOOL, LPCSTR)
WINBASEAPI HANDLE WINAPI OpenMutexW (DWORD, BOOL, LPCWSTR)
WINBASEAPI HANDLE WINAPI OpenProcess (DWORD, BOOL, DWORD)
WINBASEAPI BOOL WINAPI OpenProcessToken (HANDLE, DWORD, PHANDLE)
WINBASEAPI HANDLE WINAPI OpenSemaphoreA (DWORD, BOOL, LPCSTR)
WINBASEAPI HANDLE WINAPI OpenSemaphoreW (DWORD, BOOL, LPCWSTR)
WINBASEAPI BOOL WINAPI OpenThreadToken (HANDLE, DWORD, BOOL, PHANDLE)
WINBASEAPI HANDLE WINAPI OpenWaitableTimerA (DWORD, BOOL, LPCSTR)
WINBASEAPI HANDLE WINAPI OpenWaitableTimerW (DWORD, BOOL, LPCWSTR)
WINBASEAPI void WINAPI OutputDebugStringA (LPCSTR)
WINBASEAPI void WINAPI OutputDebugStringW (LPCWSTR)
WINBASEAPI BOOL WINAPI PeekNamedPipe (HANDLE, PVOID, DWORD, PDWORD, PDWORD, PDWORD)
WINBASEAPI BOOL WINAPI PostQueuedCompletionStatus (HANDLE, DWORD, ULONG_PTR, LPOVERLAPPED)
WINBASEAPI DWORD WINAPI PrepareTape (HANDLE, DWORD, BOOL)
WINBASEAPI BOOL WINAPI PrivilegeCheck (HANDLE, PPRIVILEGE_SET, PBOOL)
WINBASEAPI BOOL WINAPI PrivilegedServiceAuditAlarmA (LPCSTR, LPCSTR, HANDLE, PPRIVILEGE_SET, BOOL)
WINBASEAPI BOOL WINAPI PrivilegedServiceAuditAlarmW (LPCWSTR, LPCWSTR, HANDLE, PPRIVILEGE_SET, BOOL)
WINBASEAPI BOOL WINAPI PulseEvent (HANDLE)
WINBASEAPI BOOL WINAPI PurgeComm (HANDLE, DWORD)
WINBASEAPI DWORD WINAPI QueryDosDeviceA (LPCSTR, LPSTR, DWORD)
WINBASEAPI DWORD WINAPI QueryDosDeviceW (LPCWSTR, LPWSTR, DWORD)
WINBASEAPI BOOL WINAPI QueryPerformanceCounter (PLARGE_INTEGER)
WINBASEAPI BOOL WINAPI QueryPerformanceFrequency (PLARGE_INTEGER)
WINBASEAPI DWORD WINAPI QueueUserAPC (PAPCFUNC, HANDLE, ULONG_PTR)
WINBASEAPI void WINAPI RaiseException (DWORD, DWORD, DWORD, const DWORD *)
WINBASEAPI BOOL WINAPI ReadDirectoryChangesW (HANDLE, PVOID, DWORD, BOOL, DWORD, PDWORD, LPOVERLAPPED, LPOVERLAPPED_COMPLETION_ROUTINE)
WINBASEAPI BOOL WINAPI ReadEventLogA (HANDLE, DWORD, DWORD, PVOID, DWORD, DWORD *, DWORD *)
WINBASEAPI BOOL WINAPI ReadEventLogW (HANDLE, DWORD, DWORD, PVOID, DWORD, DWORD *, DWORD *)
WINBASEAPI BOOL WINAPI ReadFile (HANDLE, PVOID, DWORD, PDWORD, LPOVERLAPPED)
WINBASEAPI BOOL WINAPI ReadFileEx (HANDLE, PVOID, DWORD, LPOVERLAPPED, LPOVERLAPPED_COMPLETION_ROUTINE)
WINBASEAPI BOOL WINAPI ReadFileScatter (HANDLE, FILE_SEGMENT_ELEMENT *, DWORD, LPDWORD, LPOVERLAPPED)
WINBASEAPI BOOL WINAPI ReadProcessMemory (HANDLE, PCVOID, PVOID, DWORD, PDWORD)
WINBASEAPI HANDLE WINAPI RegisterEventSourceA (LPCSTR, LPCSTR)
WINBASEAPI HANDLE WINAPI RegisterEventSourceW (LPCWSTR, LPCWSTR)
WINBASEAPI BOOL WINAPI ReleaseMutex (HANDLE)
WINBASEAPI BOOL WINAPI ReleaseSemaphore (HANDLE, LONG, LPLONG)
WINBASEAPI BOOL WINAPI RemoveDirectoryA (LPCSTR)
WINBASEAPI BOOL WINAPI RemoveDirectoryW (LPCWSTR)
WINBASEAPI BOOL WINAPI ReportEventA (HANDLE, WORD, WORD, DWORD, PSID, WORD, DWORD, LPCSTR *, PVOID)
WINBASEAPI BOOL WINAPI ReportEventW (HANDLE, WORD, WORD, DWORD, PSID, WORD, DWORD, LPCWSTR *, PVOID)
WINBASEAPI BOOL WINAPI ResetEvent (HANDLE)
WINBASEAPI UINT WINAPI ResetWriteWatch (LPVOID, SIZE_T)
WINBASEAPI DWORD WINAPI ResumeThread (HANDLE)
WINBASEAPI BOOL WINAPI RevertToSelf (void)
WINBASEAPI DWORD WINAPI SearchPathA (LPCSTR, LPCSTR, LPCSTR, DWORD, LPSTR, LPSTR *)
WINBASEAPI DWORD WINAPI SearchPathW (LPCWSTR, LPCWSTR, LPCWSTR, DWORD, LPWSTR, LPWSTR *)
WINBASEAPI BOOL WINAPI SetAclInformation (PACL, PVOID, DWORD, ACL_INFORMATION_CLASS)
WINBASEAPI BOOL WINAPI SetCommBreak (HANDLE)
WINBASEAPI BOOL WINAPI SetCommConfig (HANDLE, LPCOMMCONFIG, DWORD)
WINBASEAPI BOOL WINAPI SetCommMask (HANDLE, DWORD)
WINBASEAPI BOOL WINAPI SetCommState (HANDLE, LPDCB)
WINBASEAPI BOOL WINAPI SetCommTimeouts (HANDLE, LPCOMMTIMEOUTS)
WINBASEAPI BOOL WINAPI SetComputerNameA (LPCSTR)
WINBASEAPI BOOL WINAPI SetComputerNameW (LPCWSTR)
WINBASEAPI DWORD WINAPI SetCriticalSectionSpinCount (LPCRITICAL_SECTION, DWORD)
WINBASEAPI BOOL WINAPI SetCurrentDirectoryA (LPCSTR)
WINBASEAPI BOOL WINAPI SetCurrentDirectoryW (LPCWSTR)
WINBASEAPI BOOL WINAPI SetDefaultCommConfigA (LPCSTR, LPCOMMCONFIG, DWORD)
WINBASEAPI BOOL WINAPI SetDefaultCommConfigW (LPCWSTR, LPCOMMCONFIG, DWORD)
WINBASEAPI BOOL WINAPI SetEndOfFile (HANDLE)
WINBASEAPI BOOL WINAPI SetEnvironmentVariableA (LPCSTR, LPCSTR)
WINBASEAPI BOOL WINAPI SetEnvironmentVariableW (LPCWSTR, LPCWSTR)
WINBASEAPI UINT WINAPI SetErrorMode (UINT)
WINBASEAPI BOOL WINAPI SetEvent (HANDLE)
WINBASEAPI VOID WINAPI SetFileApisToANSI (void)
WINBASEAPI VOID WINAPI SetFileApisToOEM (void)
WINBASEAPI BOOL WINAPI SetFileAttributesA (LPCSTR, DWORD)
WINBASEAPI BOOL WINAPI SetFileAttributesW (LPCWSTR, DWORD)
WINBASEAPI DWORD WINAPI SetFilePointer (HANDLE, LONG, PLONG, DWORD)
WINBASEAPI BOOL WINAPI SetFilePointerEx (HANDLE, LARGE_INTEGER, PLARGE_INTEGER, DWORD)
WINBASEAPI BOOL WINAPI SetFileSecurityA (LPCSTR, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR)
WINBASEAPI BOOL WINAPI SetFileSecurityW (LPCWSTR, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR)
WINBASEAPI BOOL WINAPI SetFileTime (HANDLE, const FILETIME *, const FILETIME *, const FILETIME *)
WINBASEAPI UINT WINAPI SetHandleCount (UINT)
WINBASEAPI BOOL WINAPI SetHandleInformation (HANDLE, DWORD, DWORD)
WINBASEAPI BOOL WINAPI SetKernelObjectSecurity (HANDLE, SECURITY_INFORMATION, PSECURITY_DESCRIPTOR)
WINBASEAPI void WINAPI SetLastError (DWORD)
WINBASEAPI void WINAPI SetLastErrorEx (DWORD, DWORD)
WINBASEAPI BOOL WINAPI SetLocalTime (const SYSTEMTIME *)
WINBASEAPI BOOL WINAPI SetMailslotInfo (HANDLE, DWORD)
WINBASEAPI BOOL WINAPI SetNamedPipeHandleState (HANDLE, PDWORD, PDWORD, PDWORD)
WINBASEAPI BOOL WINAPI SetPriorityClass (HANDLE, DWORD)
WINBASEAPI BOOL WINAPI SetPrivateObjectSecurity (SECURITY_INFORMATION, PSECURITY_DESCRIPTOR, PSECURITY_DESCRIPTOR *, PGENERIC_MAPPING, HANDLE)
WINBASEAPI BOOL WINAPI SetProcessAffinityMask (HANDLE, DWORD)
WINBASEAPI BOOL WINAPI SetProcessPriorityBoost (HANDLE, BOOL)
WINBASEAPI BOOL WINAPI SetProcessShutdownParameters (DWORD, DWORD)
WINBASEAPI BOOL WINAPI SetProcessWorkingSetSize (HANDLE, SIZE_T, SIZE_T)
WINBASEAPI BOOL WINAPI SetSecurityDescriptorControl (PSECURITY_DESCRIPTOR, SECURITY_DESCRIPTOR_CONTROL, SECURITY_DESCRIPTOR_CONTROL)
WINBASEAPI BOOL WINAPI SetSecurityDescriptorDacl (PSECURITY_DESCRIPTOR, BOOL, PACL, BOOL)
WINBASEAPI BOOL WINAPI SetSecurityDescriptorGroup (PSECURITY_DESCRIPTOR, PSID, BOOL)
WINBASEAPI BOOL WINAPI SetSecurityDescriptorOwner (PSECURITY_DESCRIPTOR, PSID, BOOL)
WINBASEAPI BOOL WINAPI SetSecurityDescriptorSacl (PSECURITY_DESCRIPTOR, BOOL, PACL, BOOL)
WINBASEAPI BOOL WINAPI SetStdHandle (DWORD, HANDLE)
WINBASEAPI BOOL WINAPI SetSystemPowerState (BOOL, BOOL)
WINBASEAPI BOOL WINAPI SetSystemTime (const SYSTEMTIME *)
WINBASEAPI BOOL WINAPI SetSystemTimeAdjustment (DWORD, BOOL)
WINBASEAPI DWORD WINAPI SetTapeParameters (HANDLE, DWORD, PVOID)
WINBASEAPI DWORD WINAPI SetTapePosition (HANDLE, DWORD, DWORD, DWORD, DWORD, BOOL)
WINBASEAPI DWORD WINAPI SetThreadAffinityMask (HANDLE, DWORD)
WINBASEAPI BOOL WINAPI SetThreadContext (HANDLE, const CONTEXT *)
WINBASEAPI DWORD WINAPI SetThreadIdealProcessor (HANDLE, DWORD)
WINBASEAPI BOOL WINAPI SetThreadPriority (HANDLE, int)
WINBASEAPI BOOL WINAPI SetThreadPriorityBoost (HANDLE, BOOL)
WINBASEAPI BOOL WINAPI SetThreadToken (PHANDLE, HANDLE)
WINBASEAPI BOOL WINAPI SetTimeZoneInformation (const TIME_ZONE_INFORMATION *)
WINBASEAPI BOOL WINAPI SetTokenInformation (HANDLE, TOKEN_INFORMATION_CLASS, PVOID, DWORD)
WINBASEAPI LPTOP_LEVEL_EXCEPTION_FILTER WINAPI SetUnhandledExceptionFilter (LPTOP_LEVEL_EXCEPTION_FILTER)
WINBASEAPI BOOL WINAPI SetupComm (HANDLE, DWORD, DWORD)
WINBASEAPI BOOL WINAPI SetVolumeLabelA (LPCSTR, LPCSTR)
WINBASEAPI BOOL WINAPI SetVolumeLabelW (LPCWSTR, LPCWSTR)
WINBASEAPI BOOL WINAPI SetWaitableTimer (HANDLE, const LARGE_INTEGER *, LONG, PTIMERAPCROUTINE, PVOID, BOOL)
WINBASEAPI DWORD WINAPI SignalObjectAndWait (HANDLE, HANDLE, DWORD, BOOL)
WINBASEAPI DWORD WINAPI SizeofResource (HINSTANCE, HRSRC)
WINBASEAPI void WINAPI Sleep (DWORD)
WINBASEAPI DWORD WINAPI SleepEx (DWORD, BOOL)
WINBASEAPI DWORD WINAPI SuspendThread (HANDLE)
WINBASEAPI void WINAPI SwitchToFiber (PVOID)
WINBASEAPI BOOL WINAPI SwitchToThread (void)
WINBASEAPI BOOL WINAPI SystemTimeToFileTime (const SYSTEMTIME *, LPFILETIME)
WINBASEAPI BOOL WINAPI SystemTimeToTzSpecificLocalTime (LPTIME_ZONE_INFORMATION, LPSYSTEMTIME, LPSYSTEMTIME)
WINBASEAPI BOOL WINAPI TerminateProcess (HANDLE, UINT)
WINBASEAPI BOOL WINAPI TerminateThread (HANDLE, DWORD)
WINBASEAPI DWORD WINAPI TlsAlloc (VOID)
WINBASEAPI BOOL WINAPI TlsFree (DWORD)
WINBASEAPI PVOID WINAPI TlsGetValue (DWORD)
WINBASEAPI BOOL WINAPI TlsSetValue (DWORD, PVOID)
WINBASEAPI BOOL WINAPI TransactNamedPipe (HANDLE, PVOID, DWORD, PVOID, DWORD, PDWORD, LPOVERLAPPED)
WINBASEAPI BOOL WINAPI TransmitCommChar (HANDLE, char)
WINBASEAPI BOOL WINAPI TryEnterCriticalSection (LPCRITICAL_SECTION)
WINBASEAPI LONG WINAPI UnhandledExceptionFilter (LPEXCEPTION_POINTERS)
WINBASEAPI BOOL WINAPI UnlockFile (HANDLE, DWORD, DWORD, DWORD, DWORD)
WINBASEAPI BOOL WINAPI UnlockFileEx (HANDLE, DWORD, DWORD, DWORD, LPOVERLAPPED)
WINBASEAPI BOOL WINAPI UnmapViewOfFile (LPCVOID)
WINBASEAPI BOOL WINAPI UpdateResourceA (HANDLE, LPCSTR, LPCSTR, WORD, PVOID, DWORD)
WINBASEAPI BOOL WINAPI UpdateResourceW (HANDLE, LPCWSTR, LPCWSTR, WORD, PVOID, DWORD)
WINBASEAPI BOOL WINAPI VerifyVersionInfoA (LPOSVERSIONINFOEXA, DWORD, DWORDLONG)
WINBASEAPI BOOL WINAPI VerifyVersionInfoW (LPOSVERSIONINFOEXW, DWORD, DWORDLONG)
WINBASEAPI PVOID WINAPI VirtualAlloc (PVOID, DWORD, DWORD, DWORD)
WINBASEAPI PVOID WINAPI VirtualAllocEx (HANDLE, PVOID, DWORD, DWORD, DWORD)
WINBASEAPI BOOL WINAPI VirtualFree (PVOID, DWORD, DWORD)
WINBASEAPI BOOL WINAPI VirtualFreeEx (HANDLE, PVOID, DWORD, DWORD)
WINBASEAPI BOOL WINAPI VirtualLock (PVOID, DWORD)
WINBASEAPI BOOL WINAPI VirtualProtect (PVOID, DWORD, DWORD, PDWORD)
WINBASEAPI BOOL WINAPI VirtualProtectEx (HANDLE, PVOID, DWORD, DWORD, PDWORD)
WINBASEAPI DWORD WINAPI VirtualQuery (LPCVOID, PMEMORY_BASIC_INFORMATION, DWORD)
WINBASEAPI DWORD WINAPI VirtualQueryEx (HANDLE, LPCVOID, PMEMORY_BASIC_INFORMATION, DWORD)
WINBASEAPI BOOL WINAPI VirtualUnlock (PVOID, DWORD)
WINBASEAPI BOOL WINAPI WaitCommEvent (HANDLE, PDWORD, LPOVERLAPPED)
WINBASEAPI BOOL WINAPI WaitForDebugEvent (LPDEBUG_EVENT, DWORD)
WINBASEAPI DWORD WINAPI WaitForMultipleObjects (DWORD, const HANDLE *, BOOL, DWORD)
WINBASEAPI DWORD WINAPI WaitForMultipleObjectsEx (DWORD, const HANDLE *, BOOL, DWORD, BOOL)
WINBASEAPI DWORD WINAPI WaitForSingleObject (HANDLE, DWORD)
WINBASEAPI DWORD WINAPI WaitForSingleObjectEx (HANDLE, DWORD, BOOL)
WINBASEAPI BOOL WINAPI WaitNamedPipeA (LPCSTR, DWORD)
WINBASEAPI BOOL WINAPI WaitNamedPipeW (LPCWSTR, DWORD)
WINBASEAPI BOOL WINAPI WinLoadTrustProvider (GUID *)
int APIENTRY WinMain (HINSTANCE, HINSTANCE, LPSTR, int)
WINBASEAPI BOOL WINAPI WriteFile (HANDLE, PCVOID, DWORD, PDWORD, LPOVERLAPPED)
WINBASEAPI BOOL WINAPI WriteFileEx (HANDLE, PCVOID, DWORD, LPOVERLAPPED, LPOVERLAPPED_COMPLETION_ROUTINE)
WINBASEAPI BOOL WINAPI WriteFileGather (HANDLE, FILE_SEGMENT_ELEMENT *, DWORD, LPDWORD, LPOVERLAPPED)
WINBASEAPI BOOL WINAPI WritePrivateProfileSectionA (LPCSTR, LPCSTR, LPCSTR)
WINBASEAPI BOOL WINAPI WritePrivateProfileSectionW (LPCWSTR, LPCWSTR, LPCWSTR)
WINBASEAPI BOOL WINAPI WritePrivateProfileStringA (LPCSTR, LPCSTR, LPCSTR, LPCSTR)
WINBASEAPI BOOL WINAPI WritePrivateProfileStringW (LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR)
WINBASEAPI BOOL WINAPI WritePrivateProfileStructA (LPCSTR, LPCSTR, LPVOID, UINT, LPCSTR)
WINBASEAPI BOOL WINAPI WritePrivateProfileStructW (LPCWSTR, LPCWSTR, LPVOID, UINT, LPCWSTR)
WINBASEAPI BOOL WINAPI WriteProcessMemory (HANDLE, LPVOID, LPCVOID, SIZE_T, SIZE_T *)
WINBASEAPI BOOL WINAPI WriteProfileSectionA (LPCSTR, LPCSTR)
WINBASEAPI BOOL WINAPI WriteProfileSectionW (LPCWSTR, LPCWSTR)
WINBASEAPI BOOL WINAPI WriteProfileStringA (LPCSTR, LPCSTR, LPCSTR)
WINBASEAPI BOOL WINAPI WriteProfileStringW (LPCWSTR, LPCWSTR, LPCWSTR)
WINBASEAPI DWORD WINAPI WriteTapemark (HANDLE, DWORD, DWORD, BOOL)
int APIENTRY wWinMain (HINSTANCE, HINSTANCE, LPWSTR, int)
Macro Definition Documentation
__GNUC_EXTENSION
#define __GNUC_EXTENSION
Definition at line 10 of file winbase.h.
__INTERLOCKED_DECLARED
#define __INTERLOCKED_DECLARED
Definition at line 1843 of file winbase.h.
AbnormalTermination
#define AbnormalTermination () FALSE
Definition at line 1264 of file winbase.h.
ABOVE_NORMAL_PRIORITY_CLASS
#define ABOVE_NORMAL_PRIORITY_CLASS 0x00008000
Definition at line 196 of file winbase.h.
AC_LINE_BACKUP_POWER
#define AC_LINE_BACKUP_POWER 2
Definition at line 539 of file winbase.h.
AC_LINE_OFFLINE
#define AC_LINE_OFFLINE 0
Definition at line 537 of file winbase.h.
AC_LINE_ONLINE
#define AC_LINE_ONLINE 1
Definition at line 538 of file winbase.h.
AC_LINE_UNKNOWN
#define AC_LINE_UNKNOWN 255
Definition at line 540 of file winbase.h.
AccessCheckAndAuditAlarm
#define AccessCheckAndAuditAlarm AccessCheckAndAuditAlarmA
Definition at line 2448 of file winbase.h.
AddAtom
#define AddAtom AddAtomA
Definition at line 2449 of file winbase.h.
BACKUP_ALTERNATE_DATA
#define BACKUP_ALTERNATE_DATA 4
Definition at line 513 of file winbase.h.
BACKUP_DATA
#define BACKUP_DATA 1
Definition at line 510 of file winbase.h.
BACKUP_EA_DATA
#define BACKUP_EA_DATA 2
Definition at line 511 of file winbase.h.
BACKUP_INVALID
#define BACKUP_INVALID 0
Definition at line 509 of file winbase.h.
BACKUP_LINK
#define BACKUP_LINK 5
Definition at line 514 of file winbase.h.
BACKUP_OBJECT_ID
#define BACKUP_OBJECT_ID 7
Definition at line 516 of file winbase.h.
BACKUP_PROPERTY_DATA
#define BACKUP_PROPERTY_DATA 6
Definition at line 515 of file winbase.h.
BACKUP_REPARSE_DATA
#define BACKUP_REPARSE_DATA 8
Definition at line 517 of file winbase.h.
BACKUP_SECURITY_DATA
#define BACKUP_SECURITY_DATA 3
Definition at line 512 of file winbase.h.
BACKUP_SPARSE_BLOCK
#define BACKUP_SPARSE_BLOCK 9
Definition at line 518 of file winbase.h.
BackupEventLog
#define BackupEventLog BackupEventLogA
Definition at line 2450 of file winbase.h.
BATTERY_FLAG_CHARGING
#define BATTERY_FLAG_CHARGING 8
Definition at line 544 of file winbase.h.
BATTERY_FLAG_CRITICAL
#define BATTERY_FLAG_CRITICAL 4
Definition at line 543 of file winbase.h.
BATTERY_FLAG_HIGH
#define BATTERY_FLAG_HIGH 1
Definition at line 541 of file winbase.h.
BATTERY_FLAG_LOW
#define BATTERY_FLAG_LOW 2
Definition at line 542 of file winbase.h.
BATTERY_FLAG_NO_BATTERY
#define BATTERY_FLAG_NO_BATTERY 128
Definition at line 545 of file winbase.h.
BATTERY_FLAG_UNKNOWN
#define BATTERY_FLAG_UNKNOWN 255
Definition at line 546 of file winbase.h.
BATTERY_LIFE_UNKNOWN
#define BATTERY_LIFE_UNKNOWN 0xFFFFFFFF
Definition at line 548 of file winbase.h.
BATTERY_PERCENTAGE_UNKNOWN
#define BATTERY_PERCENTAGE_UNKNOWN 255
Definition at line 547 of file winbase.h.
BAUD_075
#define BAUD_075 1
Definition at line 47 of file winbase.h.
BAUD_110
#define BAUD_110 2
Definition at line 48 of file winbase.h.
BAUD_115200
#define BAUD_115200 131072
Definition at line 64 of file winbase.h.
BAUD_1200
#define BAUD_1200 64
Definition at line 53 of file winbase.h.
BAUD_128K
#define BAUD_128K 65536
Definition at line 63 of file winbase.h.
BAUD_134_5
#define BAUD_134_5 4
Definition at line 49 of file winbase.h.
BAUD_14400
#define BAUD_14400 4096
Definition at line 59 of file winbase.h.
BAUD_150
#define BAUD_150 8
Definition at line 50 of file winbase.h.
BAUD_1800
#define BAUD_1800 128
Definition at line 54 of file winbase.h.
BAUD_19200
#define BAUD_19200 8192
Definition at line 60 of file winbase.h.
BAUD_2400
#define BAUD_2400 256
Definition at line 55 of file winbase.h.
BAUD_300
#define BAUD_300 16
Definition at line 51 of file winbase.h.
BAUD_38400
#define BAUD_38400 16384
Definition at line 61 of file winbase.h.
BAUD_4800
#define BAUD_4800 512
Definition at line 56 of file winbase.h.
BAUD_56K
#define BAUD_56K 32768
Definition at line 62 of file winbase.h.
BAUD_57600
#define BAUD_57600 262144
Definition at line 65 of file winbase.h.
BAUD_600
#define BAUD_600 32
Definition at line 52 of file winbase.h.
BAUD_7200
#define BAUD_7200 1024
Definition at line 57 of file winbase.h.
BAUD_9600
#define BAUD_9600 2048
Definition at line 58 of file winbase.h.
BAUD_USER
#define BAUD_USER 0x10000000
Definition at line 66 of file winbase.h.
BeginUpdateResource
#define BeginUpdateResource BeginUpdateResourceA
Definition at line 2451 of file winbase.h.
BELOW_NORMAL_PRIORITY_CLASS
#define BELOW_NORMAL_PRIORITY_CLASS 0x00004000
Definition at line 195 of file winbase.h.
BuildCommDCB
#define BuildCommDCB BuildCommDCBA
Definition at line 2452 of file winbase.h.
BuildCommDCBAndTimeouts
#define BuildCommDCBAndTimeouts BuildCommDCBAndTimeoutsA
Definition at line 2453 of file winbase.h.
CALLBACK_CHUNK_FINISHED
#define CALLBACK_CHUNK_FINISHED 0
Definition at line 146 of file winbase.h.
CALLBACK_STREAM_SWITCH
#define CALLBACK_STREAM_SWITCH 1
Definition at line 147 of file winbase.h.
CallNamedPipe
#define CallNamedPipe CallNamedPipeA
Definition at line 2454 of file winbase.h.
CBR_110
#define CBR_110 110
Definition at line 494 of file winbase.h.
CBR_115200
#define CBR_115200 115200
Definition at line 506 of file winbase.h.
CBR_1200
#define CBR_1200 1200
Definition at line 497 of file winbase.h.
CBR_128000
#define CBR_128000 128000
Definition at line 507 of file winbase.h.
CBR_14400
#define CBR_14400 14400
Definition at line 501 of file winbase.h.
CBR_19200
#define CBR_19200 19200
Definition at line 502 of file winbase.h.
CBR_2400
#define CBR_2400 2400
Definition at line 498 of file winbase.h.
CBR_256000
#define CBR_256000 256000
Definition at line 508 of file winbase.h.
CBR_300
#define CBR_300 300
Definition at line 495 of file winbase.h.
CBR_38400
#define CBR_38400 38400
Definition at line 503 of file winbase.h.
CBR_4800
#define CBR_4800 4800
Definition at line 499 of file winbase.h.
CBR_56000
#define CBR_56000 56000
Definition at line 504 of file winbase.h.
CBR_57600
#define CBR_57600 57600
Definition at line 505 of file winbase.h.
CBR_600
#define CBR_600 600
Definition at line 496 of file winbase.h.
CBR_9600
#define CBR_9600 9600
Definition at line 500 of file winbase.h.
CE_BREAK
#define CE_BREAK 16
Definition at line 131 of file winbase.h.
CE_DNS
#define CE_DNS 2048
Definition at line 132 of file winbase.h.
CE_FRAME
#define CE_FRAME 8
Definition at line 133 of file winbase.h.
CE_IOE
#define CE_IOE 1024
Definition at line 134 of file winbase.h.
CE_MODE
#define CE_MODE 32768
Definition at line 135 of file winbase.h.
CE_OOP
#define CE_OOP 4096
Definition at line 136 of file winbase.h.
CE_OVERRUN
#define CE_OVERRUN 2
Definition at line 137 of file winbase.h.
CE_PTO
#define CE_PTO 512
Definition at line 138 of file winbase.h.
CE_RXOVER
#define CE_RXOVER 1
Definition at line 139 of file winbase.h.
CE_RXPARITY
#define CE_RXPARITY 4
Definition at line 140 of file winbase.h.
CE_TXFULL
#define CE_TXFULL 256
Definition at line 141 of file winbase.h.
ClearEventLog
#define ClearEventLog ClearEventLogA
Definition at line 2458 of file winbase.h.
CLRBREAK
#define CLRBREAK 9
Definition at line 231 of file winbase.h.
CLRDTR
#define CLRDTR 6
Definition at line 224 of file winbase.h.
CLRRTS
#define CLRRTS 4
Definition at line 225 of file winbase.h.
CommConfigDialog
#define CommConfigDialog CommConfigDialogA
Definition at line 2459 of file winbase.h.
CONSOLE_TEXTMODE_BUFFER
#define CONSOLE_TEXTMODE_BUFFER 1
Definition at line 204 of file winbase.h.
CONTROL_C_EXIT
#define CONTROL_C_EXIT STATUS_CONTROL_C_EXIT
Definition at line 376 of file winbase.h.
COPY_FILE_FAIL_IF_EXISTS
#define COPY_FILE_FAIL_IF_EXISTS 0x0001
Definition at line 148 of file winbase.h.
COPY_FILE_OPEN_SOURCE_FOR_WRITE
#define COPY_FILE_OPEN_SOURCE_FOR_WRITE 0x0004
Definition at line 150 of file winbase.h.
COPY_FILE_RESTARTABLE
#define COPY_FILE_RESTARTABLE 0x0002
Definition at line 149 of file winbase.h.
CopyFile
#define CopyFile CopyFileA
Definition at line 2460 of file winbase.h.
CopyFileEx
#define CopyFileEx CopyFileExA
Definition at line 2461 of file winbase.h.
CopyMemory
#define CopyMemory RtlCopyMemory
Definition at line 1346 of file winbase.h.
CREATE_ALWAYS
#define CREATE_ALWAYS 2
Definition at line 206 of file winbase.h.
CREATE_BREAKAWAY_FROM_JOB
#define CREATE_BREAKAWAY_FROM_JOB 0x01000000
Definition at line 197 of file winbase.h.
CREATE_DEFAULT_ERROR_MODE
#define CREATE_DEFAULT_ERROR_MODE 0x04000000
Definition at line 199 of file winbase.h.
CREATE_FORCEDOS
#define CREATE_FORCEDOS 0x00002000
Definition at line 194 of file winbase.h.
CREATE_NEW
#define CREATE_NEW 1
Definition at line 205 of file winbase.h.
CREATE_NEW_CONSOLE
#define CREATE_NEW_CONSOLE 0x00000010
Definition at line 185 of file winbase.h.
CREATE_NEW_PROCESS_GROUP
#define CREATE_NEW_PROCESS_GROUP 0x00000200
Definition at line 190 of file winbase.h.
CREATE_NO_WINDOW
#define CREATE_NO_WINDOW 0x08000000
Definition at line 200 of file winbase.h.
CREATE_PROCESS_DEBUG_EVENT
#define CREATE_PROCESS_DEBUG_EVENT 3
Definition at line 100 of file winbase.h.
CREATE_SEPARATE_WOW_VDM
#define CREATE_SEPARATE_WOW_VDM 0x00000800
Definition at line 192 of file winbase.h.
CREATE_SHARED_WOW_VDM
#define CREATE_SHARED_WOW_VDM 0x00001000
Definition at line 193 of file winbase.h.
CREATE_SUSPENDED
#define CREATE_SUSPENDED 0x00000004
Definition at line 183 of file winbase.h.
CREATE_THREAD_DEBUG_EVENT
#define CREATE_THREAD_DEBUG_EVENT 2
Definition at line 99 of file winbase.h.
CREATE_UNICODE_ENVIRONMENT
#define CREATE_UNICODE_ENVIRONMENT 0x00000400
Definition at line 191 of file winbase.h.
CREATE_WITH_USERPROFILE
#define CREATE_WITH_USERPROFILE 0x02000000
Definition at line 198 of file winbase.h.
CreateDirectory
#define CreateDirectory CreateDirectoryA
Definition at line 2465 of file winbase.h.
CreateDirectoryEx
#define CreateDirectoryEx CreateDirectoryExA
Definition at line 2466 of file winbase.h.
CreateEvent
#define CreateEvent CreateEventA
Definition at line 2467 of file winbase.h.
CreateFile
#define CreateFile CreateFileA
Definition at line 2468 of file winbase.h.
CreateFileMapping
#define CreateFileMapping CreateFileMappingA
Definition at line 2469 of file winbase.h.
CreateMailslot
#define CreateMailslot CreateMailslotA
Definition at line 2474 of file winbase.h.
CreateMutex
#define CreateMutex CreateMutexA
Definition at line 2475 of file winbase.h.
CreateNamedPipe
#define CreateNamedPipe CreateNamedPipeA
Definition at line 2476 of file winbase.h.
CreateProcess
#define CreateProcess CreateProcessA
Definition at line 2477 of file winbase.h.
CreateProcessAsUser
#define CreateProcessAsUser CreateProcessAsUserA
Definition at line 2478 of file winbase.h.
CreateSemaphore
#define CreateSemaphore CreateSemaphoreA
Definition at line 2479 of file winbase.h.
CreateWaitableTimer
#define CreateWaitableTimer CreateWaitableTimerA
Definition at line 2483 of file winbase.h.
DATABITS_16
#define DATABITS_16 16
Definition at line 88 of file winbase.h.
DATABITS_16X
#define DATABITS_16X 32
Definition at line 89 of file winbase.h.
DATABITS_5
#define DATABITS_5 1
Definition at line 84 of file winbase.h.
DATABITS_6
#define DATABITS_6 2
Definition at line 85 of file winbase.h.
DATABITS_7
#define DATABITS_7 4
Definition at line 86 of file winbase.h.
DATABITS_8
#define DATABITS_8 8
Definition at line 87 of file winbase.h.
DDD_EXACT_MATCH_ON_REMOVE
#define DDD_EXACT_MATCH_ON_REMOVE 4
Definition at line 551 of file winbase.h.
DDD_RAW_TARGET_PATH
#define DDD_RAW_TARGET_PATH 1
Definition at line 549 of file winbase.h.
DDD_REMOVE_DEFINITION
#define DDD_REMOVE_DEFINITION 2
Definition at line 550 of file winbase.h.
DEBUG_ONLY_THIS_PROCESS
#define DEBUG_ONLY_THIS_PROCESS 0x00000002
Definition at line 182 of file winbase.h.
DEBUG_PROCESS
#define DEBUG_PROCESS 0x00000001
Definition at line 181 of file winbase.h.
DefineDosDevice
#define DefineDosDevice DefineDosDeviceA
Definition at line 2484 of file winbase.h.
DefineHandleTable
#define DefineHandleTable (w) ((w),TRUE)
Definition at line 1440 of file winbase.h.
DeleteFile
#define DeleteFile DeleteFileA
Definition at line 2485 of file winbase.h.
DETACHED_PROCESS
#define DETACHED_PROCESS 0x00000008
Definition at line 184 of file winbase.h.
DOCKINFO_DOCKED
#define DOCKINFO_DOCKED 2
Definition at line 245 of file winbase.h.
DOCKINFO_UNDOCKED
#define DOCKINFO_UNDOCKED 1
Definition at line 244 of file winbase.h.
DOCKINFO_USER_DOCKED
#define DOCKINFO_USER_DOCKED (DOCKINFO_USER_SUPPLIED|DOCKINFO_DOCKED)
Definition at line 248 of file winbase.h.
DOCKINFO_USER_SUPPLIED
#define DOCKINFO_USER_SUPPLIED 4
Definition at line 246 of file winbase.h.
DOCKINFO_USER_UNDOCKED
#define DOCKINFO_USER_UNDOCKED (DOCKINFO_USER_SUPPLIED|DOCKINFO_UNDOCKED)
Definition at line 247 of file winbase.h.
DONT_RESOLVE_DLL_REFERENCES
#define DONT_RESOLVE_DLL_REFERENCES 1
Definition at line 382 of file winbase.h.
DRIVE_CDROM
#define DRIVE_CDROM 5
Definition at line 252 of file winbase.h.
DRIVE_FIXED
#define DRIVE_FIXED 3
Definition at line 250 of file winbase.h.
DRIVE_NO_ROOT_DIR
#define DRIVE_NO_ROOT_DIR 1
Definition at line 255 of file winbase.h.
DRIVE_RAMDISK
#define DRIVE_RAMDISK 6
Definition at line 253 of file winbase.h.
DRIVE_REMOTE
#define DRIVE_REMOTE 4
Definition at line 251 of file winbase.h.
DRIVE_REMOVABLE
#define DRIVE_REMOVABLE 2
Definition at line 249 of file winbase.h.
DRIVE_UNKNOWN
#define DRIVE_UNKNOWN 0
Definition at line 254 of file winbase.h.
DTR_CONTROL_DISABLE
#define DTR_CONTROL_DISABLE 0
Definition at line 557 of file winbase.h.
DTR_CONTROL_ENABLE
#define DTR_CONTROL_ENABLE 1
Definition at line 558 of file winbase.h.
DTR_CONTROL_HANDSHAKE
#define DTR_CONTROL_HANDSHAKE 2
Definition at line 559 of file winbase.h.
EncryptFile
#define EncryptFile EncryptFileA
Definition at line 2490 of file winbase.h.
EndUpdateResource
#define EndUpdateResource EndUpdateResourceA
Definition at line 2491 of file winbase.h.
ENUMRESLANGPROC
#define ENUMRESLANGPROC ENUMRESLANGPROCA
Definition at line 1224 of file winbase.h.
ENUMRESNAMEPROC
#define ENUMRESNAMEPROC ENUMRESNAMEPROCA
Definition at line 1231 of file winbase.h.
EnumResourceLanguages
#define EnumResourceLanguages EnumResourceLanguagesA
Definition at line 2492 of file winbase.h.
EnumResourceNames
#define EnumResourceNames EnumResourceNamesA
Definition at line 2493 of file winbase.h.
EnumResourceTypes
#define EnumResourceTypes EnumResourceTypesA
Definition at line 2494 of file winbase.h.
ENUMRESTYPEPROC
#define ENUMRESTYPEPROC ENUMRESTYPEPROCA
Definition at line 1238 of file winbase.h.
EV_BREAK
#define EV_BREAK 64
Definition at line 455 of file winbase.h.
EV_CTS
#define EV_CTS 8
Definition at line 456 of file winbase.h.
EV_DSR
#define EV_DSR 16
Definition at line 457 of file winbase.h.
EV_ERR
#define EV_ERR 128
Definition at line 458 of file winbase.h.
EV_EVENT1
#define EV_EVENT1 2048
Definition at line 459 of file winbase.h.
EV_EVENT2
#define EV_EVENT2 4096
Definition at line 460 of file winbase.h.
EV_PERR
#define EV_PERR 512
Definition at line 461 of file winbase.h.
EV_RING
#define EV_RING 256
Definition at line 462 of file winbase.h.
EV_RLSD
#define EV_RLSD 32
Definition at line 463 of file winbase.h.
EV_RX80FULL
#define EV_RX80FULL 1024
Definition at line 464 of file winbase.h.
EV_RXCHAR
#define EV_RXCHAR 1
Definition at line 465 of file winbase.h.
EV_RXFLAG
#define EV_RXFLAG 2
Definition at line 466 of file winbase.h.
EV_TXEMPTY
#define EV_TXEMPTY 4
Definition at line 467 of file winbase.h.
EVENPARITY
#define EVENPARITY 2
Definition at line 488 of file winbase.h.
EVENT_ALL_ACCESS
#define EVENT_ALL_ACCESS 0x1f0003
Definition at line 167 of file winbase.h.
EVENT_MODIFY_STATE
#define EVENT_MODIFY_STATE 2
Definition at line 168 of file winbase.h.
EVENTLOG_AUDIT_FAILURE
#define EVENTLOG_AUDIT_FAILURE 16
Definition at line 447 of file winbase.h.
EVENTLOG_AUDIT_SUCCESS
#define EVENTLOG_AUDIT_SUCCESS 8
Definition at line 446 of file winbase.h.
EVENTLOG_BACKWARDS_READ
#define EVENTLOG_BACKWARDS_READ 8
Definition at line 440 of file winbase.h.
EVENTLOG_ERROR_TYPE
#define EVENTLOG_ERROR_TYPE 1
Definition at line 443 of file winbase.h.
EVENTLOG_FORWARDS_READ
#define EVENTLOG_FORWARDS_READ 4
Definition at line 439 of file winbase.h.
EVENTLOG_INFORMATION_TYPE
#define EVENTLOG_INFORMATION_TYPE 4
Definition at line 445 of file winbase.h.
EVENTLOG_SEEK_READ
#define EVENTLOG_SEEK_READ 2
Definition at line 441 of file winbase.h.
EVENTLOG_SEQUENTIAL_READ
#define EVENTLOG_SEQUENTIAL_READ 1
Definition at line 442 of file winbase.h.
EVENTLOG_SUCCESS
#define EVENTLOG_SUCCESS 0
Definition at line 438 of file winbase.h.
EVENTLOG_WARNING_TYPE
#define EVENTLOG_WARNING_TYPE 2
Definition at line 444 of file winbase.h.
EXCEPTION_ACCESS_VIOLATION
#define EXCEPTION_ACCESS_VIOLATION STATUS_ACCESS_VIOLATION
Definition at line 354 of file winbase.h.
EXCEPTION_ARRAY_BOUNDS_EXCEEDED
#define EXCEPTION_ARRAY_BOUNDS_EXCEEDED STATUS_ARRAY_BOUNDS_EXCEEDED
Definition at line 358 of file winbase.h.
EXCEPTION_BREAKPOINT
#define EXCEPTION_BREAKPOINT STATUS_BREAKPOINT
Definition at line 356 of file winbase.h.
EXCEPTION_CONTINUE_EXECUTION
#define EXCEPTION_CONTINUE_EXECUTION (-1)
Definition at line 480 of file winbase.h.
EXCEPTION_CONTINUE_SEARCH
#define EXCEPTION_CONTINUE_SEARCH 0
Definition at line 481 of file winbase.h.
EXCEPTION_DATATYPE_MISALIGNMENT
#define EXCEPTION_DATATYPE_MISALIGNMENT STATUS_DATATYPE_MISALIGNMENT
Definition at line 355 of file winbase.h.
EXCEPTION_DEBUG_EVENT
#define EXCEPTION_DEBUG_EVENT 1
Definition at line 98 of file winbase.h.
EXCEPTION_EXECUTE_HANDLER
#define EXCEPTION_EXECUTE_HANDLER 1
Definition at line 479 of file winbase.h.
EXCEPTION_FLT_DENORMAL_OPERAND
#define EXCEPTION_FLT_DENORMAL_OPERAND STATUS_FLOAT_DENORMAL_OPERAND
Definition at line 359 of file winbase.h.
EXCEPTION_FLT_DIVIDE_BY_ZERO
#define EXCEPTION_FLT_DIVIDE_BY_ZERO STATUS_FLOAT_DIVIDE_BY_ZERO
Definition at line 360 of file winbase.h.
EXCEPTION_FLT_INEXACT_RESULT
#define EXCEPTION_FLT_INEXACT_RESULT STATUS_FLOAT_INEXACT_RESULT
Definition at line 361 of file winbase.h.
EXCEPTION_FLT_INVALID_OPERATION
#define EXCEPTION_FLT_INVALID_OPERATION STATUS_FLOAT_INVALID_OPERATION
Definition at line 362 of file winbase.h.
EXCEPTION_FLT_OVERFLOW
#define EXCEPTION_FLT_OVERFLOW STATUS_FLOAT_OVERFLOW
Definition at line 363 of file winbase.h.
EXCEPTION_FLT_STACK_CHECK
#define EXCEPTION_FLT_STACK_CHECK STATUS_FLOAT_STACK_CHECK
Definition at line 364 of file winbase.h.
EXCEPTION_FLT_UNDERFLOW
#define EXCEPTION_FLT_UNDERFLOW STATUS_FLOAT_UNDERFLOW
Definition at line 365 of file winbase.h.
EXCEPTION_GUARD_PAGE
#define EXCEPTION_GUARD_PAGE STATUS_GUARD_PAGE_VIOLATION
Definition at line 374 of file winbase.h.
EXCEPTION_ILLEGAL_INSTRUCTION
#define EXCEPTION_ILLEGAL_INSTRUCTION STATUS_ILLEGAL_INSTRUCTION
Definition at line 370 of file winbase.h.
EXCEPTION_IN_PAGE_ERROR
#define EXCEPTION_IN_PAGE_ERROR STATUS_IN_PAGE_ERROR
Definition at line 369 of file winbase.h.
EXCEPTION_INT_DIVIDE_BY_ZERO
#define EXCEPTION_INT_DIVIDE_BY_ZERO STATUS_INTEGER_DIVIDE_BY_ZERO
Definition at line 366 of file winbase.h.
EXCEPTION_INT_OVERFLOW
#define EXCEPTION_INT_OVERFLOW STATUS_INTEGER_OVERFLOW
Definition at line 367 of file winbase.h.
EXCEPTION_INVALID_DISPOSITION
#define EXCEPTION_INVALID_DISPOSITION STATUS_INVALID_DISPOSITION
Definition at line 373 of file winbase.h.
EXCEPTION_INVALID_HANDLE
#define EXCEPTION_INVALID_HANDLE STATUS_INVALID_HANDLE
Definition at line 375 of file winbase.h.
EXCEPTION_NONCONTINUABLE_EXCEPTION
#define EXCEPTION_NONCONTINUABLE_EXCEPTION STATUS_NONCONTINUABLE_EXCEPTION
Definition at line 371 of file winbase.h.
EXCEPTION_PRIV_INSTRUCTION
#define EXCEPTION_PRIV_INSTRUCTION STATUS_PRIVILEGED_INSTRUCTION
Definition at line 368 of file winbase.h.
EXCEPTION_SINGLE_STEP
#define EXCEPTION_SINGLE_STEP STATUS_SINGLE_STEP
Definition at line 357 of file winbase.h.
EXCEPTION_STACK_OVERFLOW
#define EXCEPTION_STACK_OVERFLOW STATUS_STACK_OVERFLOW
Definition at line 372 of file winbase.h.
EXIT_PROCESS_DEBUG_EVENT
#define EXIT_PROCESS_DEBUG_EVENT 5
Definition at line 102 of file winbase.h.
EXIT_THREAD_DEBUG_EVENT
#define EXIT_THREAD_DEBUG_EVENT 4
Definition at line 101 of file winbase.h.
ExpandEnvironmentStrings
#define ExpandEnvironmentStrings ExpandEnvironmentStringsA
Definition at line 2495 of file winbase.h.
FatalAppExit
#define FatalAppExit FatalAppExitA
Definition at line 2496 of file winbase.h.
FILE_BEGIN
#define FILE_BEGIN 0
Definition at line 108 of file winbase.h.
FILE_CURRENT
#define FILE_CURRENT 1
Definition at line 109 of file winbase.h.
FILE_ENCRYPTABLE
#define FILE_ENCRYPTABLE 0
Definition at line 261 of file winbase.h.
FILE_END
#define FILE_END 2
Definition at line 110 of file winbase.h.
FILE_FLAG_BACKUP_SEMANTICS
#define FILE_FLAG_BACKUP_SEMANTICS 33554432
Definition at line 216 of file winbase.h.
FILE_FLAG_DELETE_ON_CLOSE
#define FILE_FLAG_DELETE_ON_CLOSE 67108864
Definition at line 215 of file winbase.h.
FILE_FLAG_NO_BUFFERING
#define FILE_FLAG_NO_BUFFERING 536870912
Definition at line 212 of file winbase.h.
FILE_FLAG_OPEN_NO_RECALL
#define FILE_FLAG_OPEN_NO_RECALL 1048576
Definition at line 219 of file winbase.h.
FILE_FLAG_OPEN_REPARSE_POINT
#define FILE_FLAG_OPEN_REPARSE_POINT 2097152
Definition at line 218 of file winbase.h.
FILE_FLAG_OVERLAPPED
#define FILE_FLAG_OVERLAPPED 1073741824
Definition at line 211 of file winbase.h.
FILE_FLAG_POSIX_SEMANTICS
#define FILE_FLAG_POSIX_SEMANTICS 16777216
Definition at line 217 of file winbase.h.
FILE_FLAG_RANDOM_ACCESS
#define FILE_FLAG_RANDOM_ACCESS 268435456
Definition at line 213 of file winbase.h.
FILE_FLAG_SEQUENTIAL_SCAN
#define FILE_FLAG_SEQUENTIAL_SCAN 134217728
Definition at line 214 of file winbase.h.
FILE_FLAG_WRITE_THROUGH
#define FILE_FLAG_WRITE_THROUGH 0x80000000
Definition at line 210 of file winbase.h.
FILE_IS_ENCRYPTED
#define FILE_IS_ENCRYPTED 1
Definition at line 262 of file winbase.h.
FILE_MAP_ALL_ACCESS
#define FILE_MAP_ALL_ACCESS 0xf001f
Definition at line 159 of file winbase.h.
FILE_MAP_COPY
#define FILE_MAP_COPY 1
Definition at line 162 of file winbase.h.
FILE_MAP_READ
#define FILE_MAP_READ 4
Definition at line 160 of file winbase.h.
FILE_MAP_WRITE
#define FILE_MAP_WRITE 2
Definition at line 161 of file winbase.h.
FILE_READ_ONLY
#define FILE_READ_ONLY 8
Definition at line 263 of file winbase.h.
FILE_ROOT_DIR
#define FILE_ROOT_DIR 3
Definition at line 264 of file winbase.h.
FILE_SYSTEM_ATTR
#define FILE_SYSTEM_ATTR 2
Definition at line 265 of file winbase.h.
FILE_SYSTEM_DIR
#define FILE_SYSTEM_DIR 4
Definition at line 266 of file winbase.h.
FILE_SYSTEM_NOT_SUPPORT
#define FILE_SYSTEM_NOT_SUPPORT 6
Definition at line 267 of file winbase.h.
FILE_TYPE_CHAR
#define FILE_TYPE_CHAR 2
Definition at line 258 of file winbase.h.
FILE_TYPE_DISK
#define FILE_TYPE_DISK 1
Definition at line 257 of file winbase.h.
FILE_TYPE_PIPE
#define FILE_TYPE_PIPE 3
Definition at line 259 of file winbase.h.
FILE_TYPE_REMOTE
#define FILE_TYPE_REMOTE 0x8000
Definition at line 260 of file winbase.h.
FILE_TYPE_UNKNOWN
#define FILE_TYPE_UNKNOWN 0
Definition at line 256 of file winbase.h.
FILE_UNKNOWN
#define FILE_UNKNOWN 5
Definition at line 268 of file winbase.h.
FILE_USER_DISALLOWED
#define FILE_USER_DISALLOWED 7
Definition at line 269 of file winbase.h.
FileEncryptionStatus
#define FileEncryptionStatus FileEncryptionStatusA
Definition at line 2497 of file winbase.h.
FillMemory
#define FillMemory RtlFillMemory
Definition at line 1347 of file winbase.h.
FIND_FIRST_EX_CASE_SENSITIVE
#define FIND_FIRST_EX_CASE_SENSITIVE 1
Definition at line 233 of file winbase.h.
FindAtom
#define FindAtom FindAtomA
Definition at line 2501 of file winbase.h.
FindFirstChangeNotification
#define FindFirstChangeNotification FindFirstChangeNotificationA
Definition at line 2502 of file winbase.h.
FindFirstFile
#define FindFirstFile FindFirstFileA
Definition at line 2503 of file winbase.h.
FindFirstFileEx
#define FindFirstFileEx FindFirstFileExA
Definition at line 2504 of file winbase.h.
FindNextFile
#define FindNextFile FindNextFileA
Definition at line 2509 of file winbase.h.
FindResource
#define FindResource FindResourceA
Definition at line 2514 of file winbase.h.
FindResourceEx
#define FindResourceEx FindResourceExA
Definition at line 2515 of file winbase.h.
FORMAT_MESSAGE_ALLOCATE_BUFFER
#define FORMAT_MESSAGE_ALLOCATE_BUFFER 256
Definition at line 448 of file winbase.h.
FORMAT_MESSAGE_ARGUMENT_ARRAY
#define FORMAT_MESSAGE_ARGUMENT_ARRAY 8192
Definition at line 453 of file winbase.h.
FORMAT_MESSAGE_FROM_HMODULE
#define FORMAT_MESSAGE_FROM_HMODULE 2048
Definition at line 451 of file winbase.h.
FORMAT_MESSAGE_FROM_STRING
#define FORMAT_MESSAGE_FROM_STRING 1024
Definition at line 450 of file winbase.h.
FORMAT_MESSAGE_FROM_SYSTEM
#define FORMAT_MESSAGE_FROM_SYSTEM 4096
Definition at line 452 of file winbase.h.
FORMAT_MESSAGE_IGNORE_INSERTS
#define FORMAT_MESSAGE_IGNORE_INSERTS 512
Definition at line 449 of file winbase.h.
FORMAT_MESSAGE_MAX_WIDTH_MASK
#define FORMAT_MESSAGE_MAX_WIDTH_MASK 255
Definition at line 454 of file winbase.h.
FormatMessage
#define FormatMessage FormatMessageA
Definition at line 2516 of file winbase.h.
FreeEnvironmentStrings
#define FreeEnvironmentStrings FreeEnvironmentStringsA
Definition at line 2517 of file winbase.h.
FreeModule
#define FreeModule (m) FreeLibrary(m)
Definition at line 1544 of file winbase.h.
FreeProcInstance
#define FreeProcInstance (p) (void)(p)
Definition at line 1545 of file winbase.h.
FS_CASE_IS_PRESERVED
#define FS_CASE_IS_PRESERVED 2
Definition at line 298 of file winbase.h.
FS_CASE_SENSITIVE
#define FS_CASE_SENSITIVE 1
Definition at line 299 of file winbase.h.
FS_FILE_COMPRESSION
#define FS_FILE_COMPRESSION 16
Definition at line 302 of file winbase.h.
FS_PERSISTENT_ACLS
#define FS_PERSISTENT_ACLS 8
Definition at line 301 of file winbase.h.
FS_UNICODE_STORED_ON_DISK
#define FS_UNICODE_STORED_ON_DISK 4
Definition at line 300 of file winbase.h.
FS_VOL_IS_COMPRESSED
#define FS_VOL_IS_COMPRESSED 32768
Definition at line 303 of file winbase.h.
GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS
#define GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS 0x00000004
Definition at line 574 of file winbase.h.
GET_MODULE_HANDLE_EX_FLAG_PIN
#define GET_MODULE_HANDLE_EX_FLAG_PIN 0x00000001
Definition at line 575 of file winbase.h.
GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT
#define GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT 0x00000002
Definition at line 576 of file winbase.h.
GET_TAPE_DRIVE_INFORMATION
#define GET_TAPE_DRIVE_INFORMATION 1
Definition at line 279 of file winbase.h.
GET_TAPE_MEDIA_INFORMATION
#define GET_TAPE_MEDIA_INFORMATION 0
Definition at line 278 of file winbase.h.
GetAtomName
#define GetAtomName GetAtomNameA
Definition at line 2518 of file winbase.h.
GetBinaryType
#define GetBinaryType GetBinaryTypeA
Definition at line 2519 of file winbase.h.
GetCommandLine
#define GetCommandLine GetCommandLineA
Definition at line 2520 of file winbase.h.
GetCompressedFileSize
#define GetCompressedFileSize GetCompressedFileSizeA
Definition at line 2525 of file winbase.h.
GetComputerName
#define GetComputerName GetComputerNameA
Definition at line 2521 of file winbase.h.
GetCurrentDirectory
#define GetCurrentDirectory GetCurrentDirectoryA
Definition at line 2526 of file winbase.h.
GetCurrentTime
#define GetCurrentTime GetTickCount
Definition at line 1587 of file winbase.h.
GetDefaultCommConfig
#define GetDefaultCommConfig GetDefaultCommConfigA
Definition at line 2527 of file winbase.h.
GetDiskFreeSpace
#define GetDiskFreeSpace GetDiskFreeSpaceA
Definition at line 2528 of file winbase.h.
GetDiskFreeSpaceEx
#define GetDiskFreeSpaceEx GetDiskFreeSpaceExA
Definition at line 2529 of file winbase.h.
GetDriveType
#define GetDriveType GetDriveTypeA
Definition at line 2533 of file winbase.h.
GetEnvironmentVariable
#define GetEnvironmentVariable GetEnvironmentVariableA
Definition at line 2534 of file winbase.h.
GetFileAttributes
#define GetFileAttributes GetFileAttributesA
Definition at line 2535 of file winbase.h.
GetFileAttributesEx
#define GetFileAttributesEx GetFileAttributesExA
Definition at line 2537 of file winbase.h.
GetFileSecurity
#define GetFileSecurity GetFileSecurityA
Definition at line 2536 of file winbase.h.
GetFreeSpace
#define GetFreeSpace (w) (0x100000L)
Definition at line 1630 of file winbase.h.
GetFullPathName
#define GetFullPathName GetFullPathNameA
Definition at line 2541 of file winbase.h.
GetLogicalDriveStrings
#define GetLogicalDriveStrings GetLogicalDriveStringsA
Definition at line 2542 of file winbase.h.
GetModuleFileName
#define GetModuleFileName GetModuleFileNameA
Definition at line 2551 of file winbase.h.
GetModuleHandle
#define GetModuleHandle GetModuleHandleA
Definition at line 2547 of file winbase.h.
GetNamedPipeHandleState
#define GetNamedPipeHandleState GetNamedPipeHandleStateA
Definition at line 2546 of file winbase.h.
GetPrivateProfileInt
#define GetPrivateProfileInt GetPrivateProfileIntA
Definition at line 2552 of file winbase.h.
GetPrivateProfileSection
#define GetPrivateProfileSection GetPrivateProfileSectionA
Definition at line 2553 of file winbase.h.
GetPrivateProfileSectionNames
#define GetPrivateProfileSectionNames GetPrivateProfileSectionNamesA
Definition at line 2554 of file winbase.h.
GetPrivateProfileString
#define GetPrivateProfileString GetPrivateProfileStringA
Definition at line 2555 of file winbase.h.
GetPrivateProfileStruct
#define GetPrivateProfileStruct GetPrivateProfileStructA
Definition at line 2556 of file winbase.h.
GetProfileInt
#define GetProfileInt GetProfileIntA
Definition at line 2557 of file winbase.h.
GetProfileSection
#define GetProfileSection GetProfileSectionA
Definition at line 2558 of file winbase.h.
GetProfileString
#define GetProfileString GetProfileStringA
Definition at line 2559 of file winbase.h.
GetShortPathName
#define GetShortPathName GetShortPathNameA
Definition at line 2560 of file winbase.h.
GetStartupInfo
#define GetStartupInfo GetStartupInfoA
Definition at line 2561 of file winbase.h.
GetSystemDirectory
#define GetSystemDirectory GetSystemDirectoryA
Definition at line 2562 of file winbase.h.
GetTempFileName
#define GetTempFileName GetTempFileNameA
Definition at line 2569 of file winbase.h.
GetTempPath
#define GetTempPath GetTempPathA
Definition at line 2570 of file winbase.h.
GetUserName
#define GetUserName GetUserNameA
Definition at line 2571 of file winbase.h.
GetVersionEx
#define GetVersionEx GetVersionExA
Definition at line 2572 of file winbase.h.
GetVolumeInformation
#define GetVolumeInformation GetVolumeInformationA
Definition at line 2573 of file winbase.h.
GetVolumeNameForVolumeMountPoint
#define GetVolumeNameForVolumeMountPoint GetVolumeNameForVolumeMountPointA
Definition at line 2574 of file winbase.h.
GetVolumePathName
#define GetVolumePathName GetVolumePathNameA
Definition at line 2575 of file winbase.h.
GetVolumePathNamesForVolumeName
#define GetVolumePathNamesForVolumeName GetVolumePathNamesForVolumeNameA
Definition at line 2576 of file winbase.h.
GetWindowsDirectory
#define GetWindowsDirectory GetWindowsDirectoryA
Definition at line 2577 of file winbase.h.
GHND
#define GHND 66
Definition at line 308 of file winbase.h.
GlobalAddAtom
#define GlobalAddAtom GlobalAddAtomA
Definition at line 2578 of file winbase.h.
GlobalDiscard
#define GlobalDiscard (hMem) GlobalReAlloc((hMem), 0, GMEM_MOVEABLE)
Definition at line 1787 of file winbase.h.
GlobalFindAtom
#define GlobalFindAtom GlobalFindAtomA
Definition at line 2579 of file winbase.h.
GlobalGetAtomName
#define GlobalGetAtomName GlobalGetAtomNameA
Definition at line 2580 of file winbase.h.
GMEM_DDESHARE
#define GMEM_DDESHARE 8192
Definition at line 309 of file winbase.h.
GMEM_DISCARDABLE
#define GMEM_DISCARDABLE 256
Definition at line 310 of file winbase.h.
GMEM_DISCARDED
#define GMEM_DISCARDED 16384
Definition at line 318 of file winbase.h.
GMEM_FIXED
#define GMEM_FIXED 0
Definition at line 304 of file winbase.h.
GMEM_INVALID_HANDLE
#define GMEM_INVALID_HANDLE 32768
Definition at line 319 of file winbase.h.
GMEM_LOCKCOUNT
#define GMEM_LOCKCOUNT 255
Definition at line 320 of file winbase.h.
GMEM_LOWER
#define GMEM_LOWER 4096
Definition at line 311 of file winbase.h.
GMEM_MODIFY
#define GMEM_MODIFY 128
Definition at line 306 of file winbase.h.
GMEM_MOVEABLE
#define GMEM_MOVEABLE 2
Definition at line 305 of file winbase.h.
GMEM_NOCOMPACT
#define GMEM_NOCOMPACT 16
Definition at line 312 of file winbase.h.
GMEM_NODISCARD
#define GMEM_NODISCARD 32
Definition at line 313 of file winbase.h.
GMEM_NOT_BANKED
#define GMEM_NOT_BANKED 4096
Definition at line 314 of file winbase.h.
GMEM_NOTIFY
#define GMEM_NOTIFY 16384
Definition at line 315 of file winbase.h.
GMEM_SHARE
#define GMEM_SHARE 8192
Definition at line 316 of file winbase.h.
GMEM_VALID_FLAGS
#define GMEM_VALID_FLAGS 32626
Definition at line 321 of file winbase.h.
GMEM_ZEROINIT
#define GMEM_ZEROINIT 64
Definition at line 317 of file winbase.h.
GPTR
#define GPTR 64
Definition at line 307 of file winbase.h.
HANDLE_FLAG_INHERIT
#define HANDLE_FLAG_INHERIT 0x01
Definition at line 271 of file winbase.h.
HANDLE_FLAG_PROTECT_FROM_CLOSE
#define HANDLE_FLAG_PROTECT_FROM_CLOSE 0x02
Definition at line 272 of file winbase.h.
HasOverlappedIoCompleted
#define HasOverlappedIoCompleted (lpOverlapped) ((lpOverlapped)->Internal != STATUS_PENDING)
Definition at line 1807 of file winbase.h.
HFILE_ERROR
#define HFILE_ERROR ((HFILE)-1)
Definition at line 107 of file winbase.h.
HIGH_PRIORITY_CLASS
#define HIGH_PRIORITY_CLASS 0x00000080
Definition at line 188 of file winbase.h.
HINSTANCE_ERROR
#define HINSTANCE_ERROR 32
Definition at line 552 of file winbase.h.
HW_PROFILE_GUIDLEN
#define HW_PROFILE_GUIDLEN 39
Definition at line 242 of file winbase.h.
IDLE_PRIORITY_CLASS
#define IDLE_PRIORITY_CLASS 0x00000040
Definition at line 187 of file winbase.h.
IGNORE
#define IGNORE 0
Definition at line 484 of file winbase.h.
INFINITE
#define INFINITE 0xFFFFFFFF
Definition at line 485 of file winbase.h.
InterlockedCompareExchangePointer
#define InterlockedCompareExchangePointer (d, e, c) (PVOID)InterlockedCompareExchange((LONG volatile *)(d),(LONG)(e),(LONG)(c))
Definition at line 1846 of file winbase.h.
InterlockedExchangePointer
#define InterlockedExchangePointer (t, v) (PVOID)InterlockedExchange((LONG volatile *)(t),(LONG)(v))
Definition at line 1851 of file winbase.h.
INVALID_ATOM
#define INVALID_ATOM ((ATOM)0)
Definition at line 483 of file winbase.h.
INVALID_FILE_SIZE
#define INVALID_FILE_SIZE 0xFFFFFFFF
Definition at line 572 of file winbase.h.
INVALID_HANDLE_VALUE
#define INVALID_HANDLE_VALUE (HANDLE)(-1)
Definition at line 277 of file winbase.h.
INVALID_SET_FILE_POINTER
#define INVALID_SET_FILE_POINTER ((DWORD)-1)
Definition at line 111 of file winbase.h.
IsBadStringPtr
#define IsBadStringPtr IsBadStringPtrA
Definition at line 2581 of file winbase.h.
LHND
#define LHND 66
Definition at line 398 of file winbase.h.
LimitEmsPages
#define LimitEmsPages (n)
Definition at line 1889 of file winbase.h.
LMEM_DISCARDABLE
#define LMEM_DISCARDABLE 3840
Definition at line 389 of file winbase.h.
LMEM_DISCARDED
#define LMEM_DISCARDED 16384
Definition at line 393 of file winbase.h.
LMEM_FIXED
#define LMEM_FIXED 0
Definition at line 385 of file winbase.h.
LMEM_INVALID_HANDLE
#define LMEM_INVALID_HANDLE 32768
Definition at line 395 of file winbase.h.
LMEM_LOCKCOUNT
#define LMEM_LOCKCOUNT 255
Definition at line 396 of file winbase.h.
LMEM_MODIFY
#define LMEM_MODIFY 128
Definition at line 394 of file winbase.h.
LMEM_MOVEABLE
#define LMEM_MOVEABLE 2
Definition at line 386 of file winbase.h.
LMEM_NOCOMPACT
#define LMEM_NOCOMPACT 16
Definition at line 390 of file winbase.h.
LMEM_NODISCARD
#define LMEM_NODISCARD 32
Definition at line 391 of file winbase.h.
LMEM_NONZEROLHND
#define LMEM_NONZEROLHND 2
Definition at line 387 of file winbase.h.
LMEM_NONZEROLPTR
#define LMEM_NONZEROLPTR 0
Definition at line 388 of file winbase.h.
LMEM_ZEROINIT
#define LMEM_ZEROINIT 64
Definition at line 392 of file winbase.h.
LOAD_DLL_DEBUG_EVENT
#define LOAD_DLL_DEBUG_EVENT 6
Definition at line 103 of file winbase.h.
LOAD_LIBRARY_AS_DATAFILE
#define LOAD_LIBRARY_AS_DATAFILE 2
Definition at line 383 of file winbase.h.
LOAD_WITH_ALTERED_SEARCH_PATH
#define LOAD_WITH_ALTERED_SEARCH_PATH 8
Definition at line 384 of file winbase.h.
LoadLibrary
#define LoadLibrary LoadLibraryA
Definition at line 2582 of file winbase.h.
LoadLibraryEx
#define LoadLibraryEx LoadLibraryExA
Definition at line 2583 of file winbase.h.
LOCKFILE_EXCLUSIVE_LOCK
#define LOCKFILE_EXCLUSIVE_LOCK 2
Definition at line 402 of file winbase.h.
LOCKFILE_FAIL_IMMEDIATELY
#define LOCKFILE_FAIL_IMMEDIATELY 1
Definition at line 401 of file winbase.h.
LockSegment
#define LockSegment (w) GlobalFix((HANDLE)(w)) /* Obsolete: Has no effect. */
Definition at line 1911 of file winbase.h.
LOGON32_LOGON_BATCH
#define LOGON32_LOGON_BATCH 4
Definition at line 413 of file winbase.h.
LOGON32_LOGON_INTERACTIVE
#define LOGON32_LOGON_INTERACTIVE 2
Definition at line 411 of file winbase.h.
LOGON32_LOGON_NETWORK
#define LOGON32_LOGON_NETWORK 3
Definition at line 412 of file winbase.h.
LOGON32_LOGON_SERVICE
#define LOGON32_LOGON_SERVICE 5
Definition at line 414 of file winbase.h.
LOGON32_LOGON_UNLOCK
#define LOGON32_LOGON_UNLOCK 7
Definition at line 415 of file winbase.h.
LOGON32_PROVIDER_DEFAULT
#define LOGON32_PROVIDER_DEFAULT 0
Definition at line 403 of file winbase.h.
LOGON32_PROVIDER_WINNT35
#define LOGON32_PROVIDER_WINNT35 1
Definition at line 404 of file winbase.h.
LogonUser
#define LogonUser LogonUserA
Definition at line 2584 of file winbase.h.
LookupAccountName
#define LookupAccountName LookupAccountNameA
Definition at line 2585 of file winbase.h.
LookupAccountSid
#define LookupAccountSid LookupAccountSidA
Definition at line 2586 of file winbase.h.
LookupPrivilegeDisplayName
#define LookupPrivilegeDisplayName LookupPrivilegeDisplayNameA
Definition at line 2587 of file winbase.h.
LookupPrivilegeName
#define LookupPrivilegeName LookupPrivilegeNameA
Definition at line 2588 of file winbase.h.
LookupPrivilegeValue
#define LookupPrivilegeValue LookupPrivilegeValueA
Definition at line 2589 of file winbase.h.
LPTR
#define LPTR 64
Definition at line 397 of file winbase.h.
lstrcat
#define lstrcat lstrcatA
Definition at line 2590 of file winbase.h.
lstrcmp
#define lstrcmp lstrcmpA
Definition at line 2591 of file winbase.h.
lstrcmpi
#define lstrcmpi lstrcmpiA
Definition at line 2592 of file winbase.h.
lstrcpy
#define lstrcpy lstrcpyA
Definition at line 2593 of file winbase.h.
lstrcpyn
#define lstrcpyn lstrcpynA
Definition at line 2594 of file winbase.h.
lstrlen
#define lstrlen lstrlenA
Definition at line 2595 of file winbase.h.
MAKEINTATOM
#define MAKEINTATOM (i) (LPTSTR)((DWORD)((WORD)(i)))
Definition at line 1248 of file winbase.h.
MakeProcInstance
#define MakeProcInstance (p, i) (p)
Definition at line 1937 of file winbase.h.
MARKPARITY
#define MARKPARITY 3
Definition at line 489 of file winbase.h.
MAX_COMPUTERNAME_LENGTH
#define MAX_COMPUTERNAME_LENGTH 15
Definition at line 241 of file winbase.h.
MAX_PROFILE_LEN
#define MAX_PROFILE_LEN 80
Definition at line 243 of file winbase.h.
MAXIMUM_SUSPEND_COUNT
#define MAXIMUM_SUSPEND_COUNT 0x7F
Definition at line 425 of file winbase.h.
MAXIMUM_WAIT_OBJECTS
#define MAXIMUM_WAIT_OBJECTS 64
Definition at line 424 of file winbase.h.
MAXINTATOM
#define MAXINTATOM 0xC000
Definition at line 482 of file winbase.h.
MoveFile
#define MoveFile MoveFileA
Definition at line 2596 of file winbase.h.
MOVEFILE_COPY_ALLOWED
#define MOVEFILE_COPY_ALLOWED 2
Definition at line 421 of file winbase.h.
MOVEFILE_DELAY_UNTIL_REBOOT
#define MOVEFILE_DELAY_UNTIL_REBOOT 4
Definition at line 422 of file winbase.h.
MOVEFILE_REPLACE_EXISTING
#define MOVEFILE_REPLACE_EXISTING 1
Definition at line 420 of file winbase.h.
MOVEFILE_WRITE_THROUGH
#define MOVEFILE_WRITE_THROUGH 8
Definition at line 423 of file winbase.h.
MoveFileEx
#define MoveFileEx MoveFileExA
Definition at line 2597 of file winbase.h.
MoveMemory
#define MoveMemory RtlMoveMemory
Definition at line 1345 of file winbase.h.
MS_CTS_ON
#define MS_CTS_ON 16
Definition at line 553 of file winbase.h.
MS_DSR_ON
#define MS_DSR_ON 32
Definition at line 554 of file winbase.h.
MS_RING_ON
#define MS_RING_ON 64
Definition at line 555 of file winbase.h.
MS_RLSD_ON
#define MS_RLSD_ON 128
Definition at line 556 of file winbase.h.
MUTEX_ALL_ACCESS
#define MUTEX_ALL_ACCESS 0x1f0001
Definition at line 163 of file winbase.h.
MUTEX_MODIFY_STATE
#define MUTEX_MODIFY_STATE 1
Definition at line 164 of file winbase.h.
NMPWAIT_NOWAIT
#define NMPWAIT_NOWAIT 1
Definition at line 128 of file winbase.h.
NMPWAIT_USE_DEFAULT_WAIT
#define NMPWAIT_USE_DEFAULT_WAIT 0
Definition at line 130 of file winbase.h.
NMPWAIT_WAIT_FOREVER
#define NMPWAIT_WAIT_FOREVER ((DWORD)-1)
Definition at line 129 of file winbase.h.
NONZEROLHND
#define NONZEROLHND 2
Definition at line 399 of file winbase.h.
NONZEROLPTR
#define NONZEROLPTR 0
Definition at line 400 of file winbase.h.
NOPARITY
#define NOPARITY 0
Definition at line 486 of file winbase.h.
NORMAL_PRIORITY_CLASS
#define NORMAL_PRIORITY_CLASS 0x00000020
Definition at line 186 of file winbase.h.
ObjectCloseAuditAlarm
#define ObjectCloseAuditAlarm ObjectCloseAuditAlarmA
Definition at line 2601 of file winbase.h.
ObjectDeleteAuditAlarm
#define ObjectDeleteAuditAlarm ObjectDeleteAuditAlarmA
Definition at line 2602 of file winbase.h.
ObjectOpenAuditAlarm
#define ObjectOpenAuditAlarm ObjectOpenAuditAlarmA
Definition at line 2603 of file winbase.h.
ObjectPrivilegeAuditAlarm
#define ObjectPrivilegeAuditAlarm ObjectPrivilegeAuditAlarmA
Definition at line 2604 of file winbase.h.
ODDPARITY
#define ODDPARITY 1
Definition at line 487 of file winbase.h.
OF_CANCEL
#define OF_CANCEL 2048
Definition at line 120 of file winbase.h.
OF_CREATE
#define OF_CREATE 4096
Definition at line 121 of file winbase.h.
OF_DELETE
#define OF_DELETE 512
Definition at line 122 of file winbase.h.
OF_EXIST
#define OF_EXIST 16384
Definition at line 123 of file winbase.h.
OF_PARSE
#define OF_PARSE 256
Definition at line 124 of file winbase.h.
OF_PROMPT
#define OF_PROMPT 8192
Definition at line 125 of file winbase.h.
OF_READ
#define OF_READ 0
Definition at line 112 of file winbase.h.
OF_READWRITE
#define OF_READWRITE 2
Definition at line 113 of file winbase.h.
OF_REOPEN
#define OF_REOPEN 32768
Definition at line 126 of file winbase.h.
OF_SHARE_COMPAT
#define OF_SHARE_COMPAT 0
Definition at line 115 of file winbase.h.
OF_SHARE_DENY_NONE
#define OF_SHARE_DENY_NONE 64
Definition at line 116 of file winbase.h.
OF_SHARE_DENY_READ
#define OF_SHARE_DENY_READ 48
Definition at line 117 of file winbase.h.
OF_SHARE_DENY_WRITE
#define OF_SHARE_DENY_WRITE 32
Definition at line 118 of file winbase.h.
OF_SHARE_EXCLUSIVE
#define OF_SHARE_EXCLUSIVE 16
Definition at line 119 of file winbase.h.
OF_VERIFY
#define OF_VERIFY 1024
Definition at line 127 of file winbase.h.
OF_WRITE
#define OF_WRITE 1
Definition at line 114 of file winbase.h.
OFS_MAXPATHNAME
#define OFS_MAXPATHNAME 128
Definition at line 158 of file winbase.h.
ONE5STOPBITS
#define ONE5STOPBITS 1
Definition at line 492 of file winbase.h.
ONESTOPBIT
#define ONESTOPBIT 0
Definition at line 491 of file winbase.h.
OPEN_ALWAYS
#define OPEN_ALWAYS 4
Definition at line 208 of file winbase.h.
OPEN_EXISTING
#define OPEN_EXISTING 3
Definition at line 207 of file winbase.h.
OpenBackupEventLog
#define OpenBackupEventLog OpenBackupEventLogA
Definition at line 2605 of file winbase.h.
OpenEvent
#define OpenEvent OpenEventA
Definition at line 2606 of file winbase.h.
OpenEventLog
#define OpenEventLog OpenEventLogA
Definition at line 2607 of file winbase.h.
OpenFileMapping
#define OpenFileMapping OpenFileMappingA
Definition at line 2608 of file winbase.h.
OpenMutex
#define OpenMutex OpenMutexA
Definition at line 2609 of file winbase.h.
OpenSemaphore
#define OpenSemaphore OpenSemaphoreA
Definition at line 2610 of file winbase.h.
OUTPUT_DEBUG_STRING_EVENT
#define OUTPUT_DEBUG_STRING_EVENT 8
Definition at line 105 of file winbase.h.
OutputDebugString
#define OutputDebugString OutputDebugStringA
Definition at line 2611 of file winbase.h.
PARITY_EVEN
#define PARITY_EVEN 1024
Definition at line 95 of file winbase.h.
PARITY_MARK
#define PARITY_MARK 2048
Definition at line 96 of file winbase.h.
PARITY_NONE
#define PARITY_NONE 256
Definition at line 93 of file winbase.h.
PARITY_ODD
#define PARITY_ODD 512
Definition at line 94 of file winbase.h.
PARITY_SPACE
#define PARITY_SPACE 4096
Definition at line 97 of file winbase.h.
PCF_16BITMODE
#define PCF_16BITMODE 512
Definition at line 76 of file winbase.h.
PCF_DTRDSR
#define PCF_DTRDSR 1
Definition at line 67 of file winbase.h.
PCF_INTTIMEOUTS
#define PCF_INTTIMEOUTS 128
Definition at line 74 of file winbase.h.
PCF_PARITY_CHECK
#define PCF_PARITY_CHECK 8
Definition at line 70 of file winbase.h.
PCF_RLSD
#define PCF_RLSD 4
Definition at line 69 of file winbase.h.
PCF_RTSCTS
#define PCF_RTSCTS 2
Definition at line 68 of file winbase.h.
PCF_SETXCHAR
#define PCF_SETXCHAR 32
Definition at line 72 of file winbase.h.
PCF_SPECIALCHARS
#define PCF_SPECIALCHARS 256
Definition at line 75 of file winbase.h.
PCF_TOTALTIMEOUTS
#define PCF_TOTALTIMEOUTS 64
Definition at line 73 of file winbase.h.
PCF_XONXOFF
#define PCF_XONXOFF 16
Definition at line 71 of file winbase.h.
PIPE_ACCESS_DUPLEX
#define PIPE_ACCESS_DUPLEX 3
Definition at line 169 of file winbase.h.
PIPE_ACCESS_INBOUND
#define PIPE_ACCESS_INBOUND 1
Definition at line 170 of file winbase.h.
PIPE_ACCESS_OUTBOUND
#define PIPE_ACCESS_OUTBOUND 2
Definition at line 171 of file winbase.h.
PIPE_CLIENT_END
#define PIPE_CLIENT_END 0
Definition at line 178 of file winbase.h.
PIPE_NOWAIT
#define PIPE_NOWAIT 1
Definition at line 177 of file winbase.h.
PIPE_READMODE_BYTE
#define PIPE_READMODE_BYTE 0
Definition at line 174 of file winbase.h.
PIPE_READMODE_MESSAGE
#define PIPE_READMODE_MESSAGE 2
Definition at line 175 of file winbase.h.
PIPE_SERVER_END
#define PIPE_SERVER_END 1
Definition at line 179 of file winbase.h.
PIPE_TYPE_BYTE
#define PIPE_TYPE_BYTE 0
Definition at line 172 of file winbase.h.
PIPE_TYPE_MESSAGE
#define PIPE_TYPE_MESSAGE 4
Definition at line 173 of file winbase.h.
PIPE_UNLIMITED_INSTANCES
#define PIPE_UNLIMITED_INSTANCES 255
Definition at line 180 of file winbase.h.
PIPE_WAIT
#define PIPE_WAIT 0
Definition at line 176 of file winbase.h.
PrivilegedServiceAuditAlarm
#define PrivilegedServiceAuditAlarm PrivilegedServiceAuditAlarmA
Definition at line 2612 of file winbase.h.
PROCESS_HEAP_ENTRY_BUSY
#define PROCESS_HEAP_ENTRY_BUSY 4
Definition at line 379 of file winbase.h.
PROCESS_HEAP_ENTRY_DDESHARE
#define PROCESS_HEAP_ENTRY_DDESHARE 32
Definition at line 381 of file winbase.h.
PROCESS_HEAP_ENTRY_MOVEABLE
#define PROCESS_HEAP_ENTRY_MOVEABLE 16
Definition at line 380 of file winbase.h.
PROCESS_HEAP_REGION
#define PROCESS_HEAP_REGION 1
Definition at line 377 of file winbase.h.
PROCESS_HEAP_UNCOMMITTED_RANGE
#define PROCESS_HEAP_UNCOMMITTED_RANGE 2
Definition at line 378 of file winbase.h.
PROFILE_KERNEL
#define PROFILE_KERNEL 0x20000000
Definition at line 202 of file winbase.h.
PROFILE_SERVER
#define PROFILE_SERVER 0x40000000
Definition at line 203 of file winbase.h.
PROFILE_USER
#define PROFILE_USER 0x10000000
Definition at line 201 of file winbase.h.
PROGRESS_CANCEL
#define PROGRESS_CANCEL 1
Definition at line 143 of file winbase.h.
PROGRESS_CONTINUE
#define PROGRESS_CONTINUE 0
Definition at line 142 of file winbase.h.
PROGRESS_QUIET
#define PROGRESS_QUIET 3
Definition at line 145 of file winbase.h.
PROGRESS_STOP
#define PROGRESS_STOP 2
Definition at line 144 of file winbase.h.
PST_FAX
#define PST_FAX 0x21
Definition at line 41 of file winbase.h.
PST_LAT
#define PST_LAT 0x101
Definition at line 44 of file winbase.h.
PST_MODEM
#define PST_MODEM 6
Definition at line 40 of file winbase.h.
PST_NETWORK_BRIDGE
#define PST_NETWORK_BRIDGE 0x100
Definition at line 43 of file winbase.h.
PST_PARALLELPORT
#define PST_PARALLELPORT 2
Definition at line 36 of file winbase.h.
PST_RS232
#define PST_RS232 1
Definition at line 35 of file winbase.h.
PST_RS422
#define PST_RS422 3
Definition at line 37 of file winbase.h.
PST_RS423
#define PST_RS423 4
Definition at line 38 of file winbase.h.
PST_RS449
#define PST_RS449 5
Definition at line 39 of file winbase.h.
PST_SCANNER
#define PST_SCANNER 0x22
Definition at line 42 of file winbase.h.
PST_TCPIP_TELNET
#define PST_TCPIP_TELNET 0x102
Definition at line 45 of file winbase.h.
PST_UNSPECIFIED
#define PST_UNSPECIFIED 0
Definition at line 34 of file winbase.h.
PST_X25
#define PST_X25 0x103
Definition at line 46 of file winbase.h.
PURGE_RXABORT
#define PURGE_RXABORT 2
Definition at line 435 of file winbase.h.
PURGE_RXCLEAR
#define PURGE_RXCLEAR 8
Definition at line 437 of file winbase.h.
PURGE_TXABORT
#define PURGE_TXABORT 1
Definition at line 434 of file winbase.h.
PURGE_TXCLEAR
#define PURGE_TXCLEAR 4
Definition at line 436 of file winbase.h.
QueryDosDevice
#define QueryDosDevice QueryDosDeviceA
Definition at line 2613 of file winbase.h.
ReadEventLog
#define ReadEventLog ReadEventLogA
Definition at line 2614 of file winbase.h.
REALTIME_PRIORITY_CLASS
#define REALTIME_PRIORITY_CLASS 0x00000100
Definition at line 189 of file winbase.h.
RegisterEventSource
#define RegisterEventSource RegisterEventSourceA
Definition at line 2615 of file winbase.h.
RemoveDirectory
#define RemoveDirectory RemoveDirectoryA
Definition at line 2616 of file winbase.h.
ReportEvent
#define ReportEvent ReportEventA
Definition at line 2620 of file winbase.h.
RIP_EVENT
#define RIP_EVENT 9
Definition at line 106 of file winbase.h.
RtlCopyMemory
#define RtlCopyMemory memcpy
Definition at line 1342 of file winbase.h.
RtlFillMemory
#define RtlFillMemory (d, l, f) memset((d), (f), (l))
Definition at line 1343 of file winbase.h.
RtlMoveMemory
#define RtlMoveMemory memmove
Definition at line 1341 of file winbase.h.
RtlZeroMemory
#define RtlZeroMemory (d, l) RtlFillMemory((d),(l),0)
Definition at line 1344 of file winbase.h.
RTS_CONTROL_DISABLE
#define RTS_CONTROL_DISABLE 0
Definition at line 560 of file winbase.h.
RTS_CONTROL_ENABLE
#define RTS_CONTROL_ENABLE 1
Definition at line 561 of file winbase.h.
RTS_CONTROL_HANDSHAKE
#define RTS_CONTROL_HANDSHAKE 2
Definition at line 562 of file winbase.h.
RTS_CONTROL_TOGGLE
#define RTS_CONTROL_TOGGLE 3
Definition at line 563 of file winbase.h.
SCS_32BIT_BINARY
#define SCS_32BIT_BINARY 0
Definition at line 234 of file winbase.h.
SCS_64BIT_BINARY
#define SCS_64BIT_BINARY 6
Definition at line 235 of file winbase.h.
SCS_DOS_BINARY
#define SCS_DOS_BINARY 1
Definition at line 236 of file winbase.h.
SCS_OS216_BINARY
#define SCS_OS216_BINARY 5
Definition at line 237 of file winbase.h.
SCS_PIF_BINARY
#define SCS_PIF_BINARY 3
Definition at line 238 of file winbase.h.
SCS_POSIX_BINARY
#define SCS_POSIX_BINARY 4
Definition at line 239 of file winbase.h.
SCS_WOW_BINARY
#define SCS_WOW_BINARY 2
Definition at line 240 of file winbase.h.
SearchPath
#define SearchPath SearchPathA
Definition at line 2621 of file winbase.h.
SECURITY_ANONYMOUS
#define SECURITY_ANONYMOUS (SecurityAnonymous<<16)
Definition at line 564 of file winbase.h.
SECURITY_CONTEXT_TRACKING
#define SECURITY_CONTEXT_TRACKING 0x40000
Definition at line 568 of file winbase.h.
SECURITY_DELEGATION
#define SECURITY_DELEGATION (SecurityDelegation<<16)
Definition at line 567 of file winbase.h.
SECURITY_EFFECTIVE_ONLY
#define SECURITY_EFFECTIVE_ONLY 0x80000
Definition at line 569 of file winbase.h.
SECURITY_IDENTIFICATION
#define SECURITY_IDENTIFICATION (SecurityIdentification<<16)
Definition at line 565 of file winbase.h.
SECURITY_IMPERSONATION
#define SECURITY_IMPERSONATION (SecurityImpersonation<<16)
Definition at line 566 of file winbase.h.
SECURITY_SQOS_PRESENT
#define SECURITY_SQOS_PRESENT 0x100000
Definition at line 570 of file winbase.h.
SECURITY_VALID_SQOS_FLAGS
#define SECURITY_VALID_SQOS_FLAGS 0x1F0000
Definition at line 571 of file winbase.h.
SEM_FAILCRITICALERRORS
#define SEM_FAILCRITICALERRORS 0x0001
Definition at line 470 of file winbase.h.
SEM_NOALIGNMENTFAULTEXCEPT
#define SEM_NOALIGNMENTFAULTEXCEPT 0x0004
Definition at line 472 of file winbase.h.
SEM_NOGPFAULTERRORBOX
#define SEM_NOGPFAULTERRORBOX 0x0002
Definition at line 471 of file winbase.h.
SEM_NOOPENFILEERRORBOX
#define SEM_NOOPENFILEERRORBOX 0x8000
Definition at line 473 of file winbase.h.
SEMAPHORE_ALL_ACCESS
#define SEMAPHORE_ALL_ACCESS 0x1f0003
Definition at line 165 of file winbase.h.
SEMAPHORE_MODIFY_STATE
#define SEMAPHORE_MODIFY_STATE 2
Definition at line 166 of file winbase.h.
SET_TAPE_DRIVE_INFORMATION
#define SET_TAPE_DRIVE_INFORMATION 1
Definition at line 281 of file winbase.h.
SET_TAPE_MEDIA_INFORMATION
#define SET_TAPE_MEDIA_INFORMATION 0
Definition at line 280 of file winbase.h.
SETBREAK
#define SETBREAK 8
Definition at line 230 of file winbase.h.
SetComputerName
#define SetComputerName SetComputerNameA
Definition at line 2622 of file winbase.h.
SetCurrentDirectory
#define SetCurrentDirectory SetCurrentDirectoryA
Definition at line 2623 of file winbase.h.
SetDefaultCommConfig
#define SetDefaultCommConfig SetDefaultCommConfigA
Definition at line 2624 of file winbase.h.
SETDTR
#define SETDTR 5
Definition at line 226 of file winbase.h.
SetEnvironmentVariable
#define SetEnvironmentVariable SetEnvironmentVariableA
Definition at line 2628 of file winbase.h.
SetFileAttributes
#define SetFileAttributes SetFileAttributesA
Definition at line 2629 of file winbase.h.
SetFileSecurity
#define SetFileSecurity SetFileSecurityA
Definition at line 2630 of file winbase.h.
SETRTS
#define SETRTS 3
Definition at line 227 of file winbase.h.
SetSwapAreaSize
#define SetSwapAreaSize (w) (w)
Definition at line 2126 of file winbase.h.
SetVolumeLabel
#define SetVolumeLabel SetVolumeLabelA
Definition at line 2637 of file winbase.h.
SetVolumeMountPoint
#define SetVolumeMountPoint SetVolumeMountPointA
Definition at line 2638 of file winbase.h.
SETXOFF
#define SETXOFF 1
Definition at line 228 of file winbase.h.
SETXON
#define SETXON 2
Definition at line 229 of file winbase.h.
SHUTDOWN_NORETRY
#define SHUTDOWN_NORETRY 1
Definition at line 478 of file winbase.h.
SLE_ERROR
#define SLE_ERROR 1
Definition at line 475 of file winbase.h.
SLE_MINORERROR
#define SLE_MINORERROR 2
Definition at line 476 of file winbase.h.
SLE_WARNING
#define SLE_WARNING 3
Definition at line 477 of file winbase.h.
SP_BAUD
#define SP_BAUD 2
Definition at line 78 of file winbase.h.
SP_DATABITS
#define SP_DATABITS 4
Definition at line 79 of file winbase.h.
SP_HANDSHAKING
#define SP_HANDSHAKING 16
Definition at line 81 of file winbase.h.
SP_PARITY
#define SP_PARITY 1
Definition at line 77 of file winbase.h.
SP_PARITY_CHECK
#define SP_PARITY_CHECK 32
Definition at line 82 of file winbase.h.
SP_RLSD
#define SP_RLSD 64
Definition at line 83 of file winbase.h.
SP_SERIALCOMM
#define SP_SERIALCOMM 1
Definition at line 33 of file winbase.h.
SP_STOPBITS
#define SP_STOPBITS 8
Definition at line 80 of file winbase.h.
SPACEPARITY
#define SPACEPARITY 4
Definition at line 490 of file winbase.h.
STARTF_FORCEOFFFEEDBACK
#define STARTF_FORCEOFFFEEDBACK 128
Definition at line 530 of file winbase.h.
STARTF_FORCEONFEEDBACK
#define STARTF_FORCEONFEEDBACK 64
Definition at line 529 of file winbase.h.
STARTF_RUNFULLSCREEN
#define STARTF_RUNFULLSCREEN 32
Definition at line 528 of file winbase.h.
STARTF_USECOUNTCHARS
#define STARTF_USECOUNTCHARS 8
Definition at line 526 of file winbase.h.
STARTF_USEFILLATTRIBUTE
#define STARTF_USEFILLATTRIBUTE 16
Definition at line 527 of file winbase.h.
STARTF_USEHOTKEY
#define STARTF_USEHOTKEY 512
Definition at line 532 of file winbase.h.
STARTF_USEPOSITION
#define STARTF_USEPOSITION 4
Definition at line 525 of file winbase.h.
STARTF_USESHOWWINDOW
#define STARTF_USESHOWWINDOW 1
Definition at line 523 of file winbase.h.
STARTF_USESIZE
#define STARTF_USESIZE 2
Definition at line 524 of file winbase.h.
STARTF_USESTDHANDLES
#define STARTF_USESTDHANDLES 256
Definition at line 531 of file winbase.h.
STATUS_ABANDONED_WAIT_0
#define STATUS_ABANDONED_WAIT_0 0x80
Definition at line 323 of file winbase.h.
STATUS_ACCESS_VIOLATION
#define STATUS_ACCESS_VIOLATION 0xC0000005
Definition at line 332 of file winbase.h.
STATUS_ARRAY_BOUNDS_EXCEEDED
#define STATUS_ARRAY_BOUNDS_EXCEEDED 0xC000008C
Definition at line 339 of file winbase.h.
STATUS_BREAKPOINT
#define STATUS_BREAKPOINT 0x80000003
Definition at line 330 of file winbase.h.
STATUS_CONTROL_C_EXIT
#define STATUS_CONTROL_C_EXIT 0xC000013A
Definition at line 351 of file winbase.h.
STATUS_DATATYPE_MISALIGNMENT
#define STATUS_DATATYPE_MISALIGNMENT 0x80000002
Definition at line 329 of file winbase.h.
STATUS_DLL_INIT_FAILED
#define STATUS_DLL_INIT_FAILED 0xC0000142
Definition at line 352 of file winbase.h.
STATUS_DLL_INIT_FAILED_LOGOFF
#define STATUS_DLL_INIT_FAILED_LOGOFF 0xC000026B
Definition at line 353 of file winbase.h.
STATUS_FLOAT_DENORMAL_OPERAND
#define STATUS_FLOAT_DENORMAL_OPERAND 0xC000008D
Definition at line 340 of file winbase.h.
STATUS_FLOAT_DIVIDE_BY_ZERO
#define STATUS_FLOAT_DIVIDE_BY_ZERO 0xC000008E
Definition at line 341 of file winbase.h.
STATUS_FLOAT_INEXACT_RESULT
#define STATUS_FLOAT_INEXACT_RESULT 0xC000008F
Definition at line 342 of file winbase.h.
STATUS_FLOAT_INVALID_OPERATION
#define STATUS_FLOAT_INVALID_OPERATION 0xC0000090
Definition at line 343 of file winbase.h.
STATUS_FLOAT_OVERFLOW
#define STATUS_FLOAT_OVERFLOW 0xC0000091
Definition at line 344 of file winbase.h.
STATUS_FLOAT_STACK_CHECK
#define STATUS_FLOAT_STACK_CHECK 0xC0000092
Definition at line 345 of file winbase.h.
STATUS_FLOAT_UNDERFLOW
#define STATUS_FLOAT_UNDERFLOW 0xC0000093
Definition at line 346 of file winbase.h.
STATUS_GUARD_PAGE_VIOLATION
#define STATUS_GUARD_PAGE_VIOLATION 0x80000001
Definition at line 328 of file winbase.h.
STATUS_ILLEGAL_INSTRUCTION
#define STATUS_ILLEGAL_INSTRUCTION 0xC000001D
Definition at line 336 of file winbase.h.
STATUS_IN_PAGE_ERROR
#define STATUS_IN_PAGE_ERROR 0xC0000006
Definition at line 333 of file winbase.h.
STATUS_INTEGER_DIVIDE_BY_ZERO
#define STATUS_INTEGER_DIVIDE_BY_ZERO 0xC0000094
Definition at line 347 of file winbase.h.
STATUS_INTEGER_OVERFLOW
#define STATUS_INTEGER_OVERFLOW 0xC0000095
Definition at line 348 of file winbase.h.
STATUS_INVALID_DISPOSITION
#define STATUS_INVALID_DISPOSITION 0xC0000026
Definition at line 338 of file winbase.h.
STATUS_INVALID_HANDLE
#define STATUS_INVALID_HANDLE 0xC0000008L
Definition at line 334 of file winbase.h.
STATUS_NO_MEMORY
#define STATUS_NO_MEMORY 0xC0000017
Definition at line 335 of file winbase.h.
STATUS_NONCONTINUABLE_EXCEPTION
#define STATUS_NONCONTINUABLE_EXCEPTION 0xC0000025
Definition at line 337 of file winbase.h.
STATUS_PENDING
#define STATUS_PENDING 0x103
Definition at line 326 of file winbase.h.
STATUS_PRIVILEGED_INSTRUCTION
#define STATUS_PRIVILEGED_INSTRUCTION 0xC0000096
Definition at line 349 of file winbase.h.
STATUS_SEGMENT_NOTIFICATION
#define STATUS_SEGMENT_NOTIFICATION 0x40000005
Definition at line 327 of file winbase.h.
STATUS_SINGLE_STEP
#define STATUS_SINGLE_STEP 0x80000004
Definition at line 331 of file winbase.h.
STATUS_STACK_OVERFLOW
#define STATUS_STACK_OVERFLOW 0xC00000FD
Definition at line 350 of file winbase.h.
STATUS_TIMEOUT
#define STATUS_TIMEOUT 0x102
Definition at line 325 of file winbase.h.
STATUS_USER_APC
#define STATUS_USER_APC 0xC0
Definition at line 324 of file winbase.h.
STATUS_WAIT_0
#define STATUS_WAIT_0 0
Definition at line 322 of file winbase.h.
STD_ERROR_HANDLE
#define STD_ERROR_HANDLE (DWORD)(0xfffffff4)
Definition at line 276 of file winbase.h.
STD_INPUT_HANDLE
#define STD_INPUT_HANDLE (DWORD)(0xfffffff6)
Definition at line 274 of file winbase.h.
STD_OUTPUT_HANDLE
#define STD_OUTPUT_HANDLE (DWORD)(0xfffffff5)
Definition at line 275 of file winbase.h.
STILL_ACTIVE
#define STILL_ACTIVE 0x103
Definition at line 232 of file winbase.h.
STOPBITS_10
#define STOPBITS_10 1
Definition at line 90 of file winbase.h.
STOPBITS_15
#define STOPBITS_15 2
Definition at line 91 of file winbase.h.
STOPBITS_20
#define STOPBITS_20 4
Definition at line 92 of file winbase.h.
STREAM_CONTAINS_PROPERTIES
#define STREAM_CONTAINS_PROPERTIES 4
Definition at line 522 of file winbase.h.
STREAM_CONTAINS_SECURITY
#define STREAM_CONTAINS_SECURITY 2
Definition at line 521 of file winbase.h.
STREAM_MODIFIED_WHEN_READ
#define STREAM_MODIFIED_WHEN_READ 1
Definition at line 520 of file winbase.h.
STREAM_NORMAL_ATTRIBUTE
#define STREAM_NORMAL_ATTRIBUTE 0
Definition at line 519 of file winbase.h.
SYMBOLIC_LINK_FLAG_DIRECTORY
#define SYMBOLIC_LINK_FLAG_DIRECTORY 0x1
Definition at line 223 of file winbase.h.
TC_GP_TRAP
#define TC_GP_TRAP 2
Definition at line 535 of file winbase.h.
TC_HARDERR
#define TC_HARDERR 1
Definition at line 534 of file winbase.h.
TC_NORMAL
#define TC_NORMAL 0
Definition at line 533 of file winbase.h.
TC_SIGNAL
#define TC_SIGNAL 3
Definition at line 536 of file winbase.h.
THREAD_PRIORITY_ABOVE_NORMAL
#define THREAD_PRIORITY_ABOVE_NORMAL 1
Definition at line 286 of file winbase.h.
THREAD_PRIORITY_BELOW_NORMAL
#define THREAD_PRIORITY_BELOW_NORMAL (-1)
Definition at line 287 of file winbase.h.
THREAD_PRIORITY_ERROR_RETURN
#define THREAD_PRIORITY_ERROR_RETURN 2147483647
Definition at line 293 of file winbase.h.
THREAD_PRIORITY_HIGHEST
#define THREAD_PRIORITY_HIGHEST 2
Definition at line 288 of file winbase.h.
THREAD_PRIORITY_IDLE
#define THREAD_PRIORITY_IDLE (-15)
Definition at line 289 of file winbase.h.
THREAD_PRIORITY_LOWEST
#define THREAD_PRIORITY_LOWEST (-2)
Definition at line 290 of file winbase.h.
THREAD_PRIORITY_NORMAL
#define THREAD_PRIORITY_NORMAL 0
Definition at line 291 of file winbase.h.
THREAD_PRIORITY_TIME_CRITICAL
#define THREAD_PRIORITY_TIME_CRITICAL 15
Definition at line 292 of file winbase.h.
TIME_ZONE_ID_DAYLIGHT
#define TIME_ZONE_ID_DAYLIGHT 2
Definition at line 296 of file winbase.h.
TIME_ZONE_ID_INVALID
#define TIME_ZONE_ID_INVALID 0xFFFFFFFF
Definition at line 297 of file winbase.h.
TIME_ZONE_ID_STANDARD
#define TIME_ZONE_ID_STANDARD 1
Definition at line 295 of file winbase.h.
TIME_ZONE_ID_UNKNOWN
#define TIME_ZONE_ID_UNKNOWN 0
Definition at line 294 of file winbase.h.
TLS_OUT_OF_INDEXES
#define TLS_OUT_OF_INDEXES (DWORD)0xFFFFFFFF
Definition at line 573 of file winbase.h.
TRUNCATE_EXISTING
#define TRUNCATE_EXISTING 5
Definition at line 209 of file winbase.h.
TWOSTOPBITS
#define TWOSTOPBITS 2
Definition at line 493 of file winbase.h.
UNLOAD_DLL_DEBUG_EVENT
#define UNLOAD_DLL_DEBUG_EVENT 7
Definition at line 104 of file winbase.h.
UnlockResource
#define UnlockResource (h) (h)
Definition at line 2176 of file winbase.h.
UnlockSegment
#define UnlockSegment (w) GlobalUnfix((HANDLE)(w)) /* Obsolete: Has no effect. */
Definition at line 2177 of file winbase.h.
UpdateResource
#define UpdateResource UpdateResourceA
Definition at line 2639 of file winbase.h.
VerifyVersionInfo
#define VerifyVersionInfo VerifyVersionInfoA
Definition at line 2640 of file winbase.h.
WAIT_ABANDONED
#define WAIT_ABANDONED 128
Definition at line 432 of file winbase.h.
WAIT_ABANDONED_0
#define WAIT_ABANDONED_0 128
Definition at line 427 of file winbase.h.
WAIT_FAILED
#define WAIT_FAILED ((DWORD)0xFFFFFFFF)
Definition at line 433 of file winbase.h.
WAIT_IO_COMPLETION
#define WAIT_IO_COMPLETION 0xC0
Definition at line 431 of file winbase.h.
WAIT_OBJECT_0
#define WAIT_OBJECT_0 0
Definition at line 426 of file winbase.h.
WAIT_TIMEOUT
#define WAIT_TIMEOUT 258
Definition at line 429 of file winbase.h.
WaitNamedPipe
#define WaitNamedPipe WaitNamedPipeA
Definition at line 2641 of file winbase.h.
WINADVAPI
#define WINADVAPI
Definition at line 25 of file winbase.h.
WINBASEAPI
#define WINBASEAPI
Definition at line 17 of file winbase.h.
WRITE_WATCH_FLAG_RESET
#define WRITE_WATCH_FLAG_RESET 1
Definition at line 595 of file winbase.h.
WritePrivateProfileSection
#define WritePrivateProfileSection WritePrivateProfileSectionA
Definition at line 2642 of file winbase.h.
WritePrivateProfileString
#define WritePrivateProfileString WritePrivateProfileStringA
Definition at line 2643 of file winbase.h.
WritePrivateProfileStruct
#define WritePrivateProfileStruct WritePrivateProfileStructA
Definition at line 2644 of file winbase.h.
WriteProfileSection
#define WriteProfileSection WriteProfileSectionA
Definition at line 2645 of file winbase.h.
WriteProfileString
#define WriteProfileString WriteProfileStringA
Definition at line 2646 of file winbase.h.
Yield
#define Yield ()
Definition at line 2221 of file winbase.h.
ZeroMemory
#define ZeroMemory RtlZeroMemory
Definition at line 1348 of file winbase.h.
Typedef Documentation
ENUMRESLANGPROCA
typedef BOOL(CALLBACK * ENUMRESLANGPROCA) (HMODULE, LPCSTR, LPCSTR, WORD, LONG)
Definition at line 1219 of file winbase.h.
ENUMRESLANGPROCW
typedef BOOL(CALLBACK * ENUMRESLANGPROCW) (HMODULE, LPCWSTR, LPCWSTR, WORD, LONG)
Definition at line 1220 of file winbase.h.
ENUMRESNAMEPROCA
typedef BOOL(CALLBACK * ENUMRESNAMEPROCA) (HMODULE, LPCSTR, LPSTR, LONG)
Definition at line 1226 of file winbase.h.
ENUMRESNAMEPROCW
typedef BOOL(CALLBACK * ENUMRESNAMEPROCW) (HMODULE, LPCWSTR, LPWSTR, LONG)
Definition at line 1227 of file winbase.h.
ENUMRESTYPEPROCA
typedef BOOL(CALLBACK * ENUMRESTYPEPROCA) (HMODULE, LPSTR, LONG)
Definition at line 1233 of file winbase.h.
ENUMRESTYPEPROCW
typedef BOOL(CALLBACK * ENUMRESTYPEPROCW) (HMODULE, LPWSTR, LONG)
Definition at line 1234 of file winbase.h.
HW_PROFILE_INFO
typedef HW_PROFILE_INFOA HW_PROFILE_INFO
Definition at line 2443 of file winbase.h.
LPBY_HANDLE_FILE_INFORMATION
typedef struct BY_HANDLE_FILE_INFORMATION* LPBY_HANDLE_FILE_INFORMATION
LPCOMMCONFIG
typedef struct COMMCONFIG* LPCOMMCONFIG
LPCOMMPROP
typedef struct COMMPROP* LPCOMMPROP
LPCOMMTIMEOUTS
typedef struct COMMTIMEOUTS* LPCOMMTIMEOUTS
LPCOMSTAT
typedef struct COMSTAT* LPCOMSTAT
LPCREATE_PROCESS_DEBUG_INFO
typedef struct CREATE_PROCESS_DEBUG_INFO* LPCREATE_PROCESS_DEBUG_INFO
LPCREATE_THREAD_DEBUG_INFO
typedef struct CREATE_THREAD_DEBUG_INFO* LPCREATE_THREAD_DEBUG_INFO
LPCRITICAL_SECTION
typedef struct CRITICAL_SECTION* LPCRITICAL_SECTION
LPDCB
typedef struct DCB* LPDCB
LPDEBUG_EVENT
typedef struct DEBUG_EVENT* LPDEBUG_EVENT
LPEXCEPTION_DEBUG_INFO
typedef struct EXCEPTION_DEBUG_INFO* LPEXCEPTION_DEBUG_INFO
LPEXIT_PROCESS_DEBUG_INFO
typedef struct EXIT_PROCESS_DEBUG_INFO* LPEXIT_PROCESS_DEBUG_INFO
LPEXIT_THREAD_DEBUG_INFO
typedef struct EXIT_THREAD_DEBUG_INFO* LPEXIT_THREAD_DEBUG_INFO
LPFIBER_START_ROUTINE
typedef void(WINAPI * LPFIBER_START_ROUTINE) (PVOID)
Definition at line 1218 of file winbase.h.
LPFILETIME
typedef struct FILETIME* LPFILETIME
LPHW_PROFILE_INFO
typedef HW_PROFILE_INFOA * LPHW_PROFILE_INFO
Definition at line 2443 of file winbase.h.
LPHW_PROFILE_INFOA
typedef struct HW_PROFILE_INFOA* LPHW_PROFILE_INFOA
LPHW_PROFILE_INFOW
typedef struct HW_PROFILE_INFOW* LPHW_PROFILE_INFOW
LPLDT_ENTRY
typedef struct LDT_ENTRY* LPLDT_ENTRY
LPLOAD_DLL_DEBUG_INFO
typedef struct LOAD_DLL_DEBUG_INFO* LPLOAD_DLL_DEBUG_INFO
LPMEMORYSTATUS
typedef struct MEMORYSTATUS* LPMEMORYSTATUS
LPOFSTRUCT
typedef struct OFSTRUCT* LPOFSTRUCT
LPOUTPUT_DEBUG_STRING_INFO
typedef struct OUTPUT_DEBUG_STRING_INFO* LPOUTPUT_DEBUG_STRING_INFO
LPOVERLAPPED
typedef struct OVERLAPPED* LPOVERLAPPED
LPOVERLAPPED_COMPLETION_ROUTINE
typedef void(CALLBACK * LPOVERLAPPED_COMPLETION_ROUTINE) (DWORD, DWORD, LPOVERLAPPED)
Definition at line 1240 of file winbase.h.
LPPROCESS_HEAP_ENTRY
typedef struct PROCESS_HEAP_ENTRY* LPPROCESS_HEAP_ENTRY
LPPROCESS_INFORMATION
typedef struct PROCESS_INFORMATION* LPPROCESS_INFORMATION
LPPROGRESS_ROUTINE
typedef DWORD(WINAPI * LPPROGRESS_ROUTINE) (LARGE_INTEGER, LARGE_INTEGER, LARGE_INTEGER, LARGE_INTEGER, DWORD, DWORD, HANDLE, HANDLE, LPVOID)
Definition at line 1217 of file winbase.h.
LPRIP_INFO
typedef struct RIP_INFO* LPRIP_INFO
LPSTARTUPINFO
typedef STARTUPINFOA * LPSTARTUPINFO
Definition at line 2441 of file winbase.h.
LPSTARTUPINFOA
typedef struct STARTUPINFOA* LPSTARTUPINFOA
LPSTARTUPINFOW
typedef struct STARTUPINFOW* LPSTARTUPINFOW
LPSYSTEM_INFO
typedef struct SYSTEM_INFO* LPSYSTEM_INFO
LPSYSTEM_POWER_STATUS
typedef struct SYSTEM_POWER_STATUS* LPSYSTEM_POWER_STATUS
LPSYSTEMTIME
typedef struct SYSTEMTIME* LPSYSTEMTIME
LPTHREAD_START_ROUTINE
typedef DWORD(WINAPI * LPTHREAD_START_ROUTINE) (LPVOID)
Definition at line 788 of file winbase.h.
LPTIME_ZONE_INFORMATION
typedef struct TIME_ZONE_INFORMATION* LPTIME_ZONE_INFORMATION
LPTOP_LEVEL_EXCEPTION_FILTER
typedef PTOP_LEVEL_EXCEPTION_FILTER LPTOP_LEVEL_EXCEPTION_FILTER
Definition at line 1242 of file winbase.h.
LPUNLOAD_DLL_DEBUG_INFO
typedef struct UNLOAD_DLL_DEBUG_INFO* LPUNLOAD_DLL_DEBUG_INFO
LPWIN32_FILE_ATTRIBUTE_DATA
typedef struct WIN32_FILE_ATTRIBUTE_DATA* LPWIN32_FILE_ATTRIBUTE_DATA
LPWIN32_FIND_DATA
typedef WIN32_FIND_DATAA * LPWIN32_FIND_DATA
Definition at line 2442 of file winbase.h.
LPWIN32_FIND_DATAA
typedef struct WIN32_FIND_DATAA* LPWIN32_FIND_DATAA
LPWIN32_FIND_DATAW
typedef struct WIN32_FIND_DATAW* LPWIN32_FIND_DATAW
LPWIN32_STREAM_ID
typedef struct WIN32_STREAM_ID * LPWIN32_STREAM_ID
LPWIN_CERTIFICATE
typedef struct WIN_CERTIFICATE * LPWIN_CERTIFICATE
PAPCFUNC
typedef void(APIENTRY * PAPCFUNC) (ULONG_PTR)
Definition at line 1243 of file winbase.h.
PCRITICAL_SECTION
typedef struct CRITICAL_SECTION* PCRITICAL_SECTION
PCRITICAL_SECTION_DEBUG
typedef struct CRITICAL_SECTION_DEBUG* PCRITICAL_SECTION_DEBUG
PFILETIME
typedef struct FILETIME* PFILETIME
PLDT_ENTRY
typedef struct LDT_ENTRY* PLDT_ENTRY
POFSTRUCT
typedef struct OFSTRUCT* POFSTRUCT
POVERLAPPED
typedef struct OVERLAPPED* POVERLAPPED
PPROCESS_INFORMATION
typedef struct PROCESS_INFORMATION* PPROCESS_INFORMATION
PTIMERAPCROUTINE
typedef void(CALLBACK * PTIMERAPCROUTINE) (PVOID, DWORD, DWORD)
Definition at line 1244 of file winbase.h.
PTOP_LEVEL_EXCEPTION_FILTER
typedef LONG(CALLBACK * PTOP_LEVEL_EXCEPTION_FILTER) (LPEXCEPTION_POINTERS)
Definition at line 1241 of file winbase.h.
PWIN32_FIND_DATA
typedef WIN32_FIND_DATAA * PWIN32_FIND_DATA
Definition at line 2442 of file winbase.h.
PWIN32_FIND_DATAA
typedef struct WIN32_FIND_DATAA* PWIN32_FIND_DATAA
PWIN32_FIND_DATAW
typedef struct WIN32_FIND_DATAW* PWIN32_FIND_DATAW
STARTUPINFO
typedef STARTUPINFOA STARTUPINFO
Definition at line 2441 of file winbase.h.
WIN32_FIND_DATA
typedef WIN32_FIND_DATAA WIN32_FIND_DATA
Definition at line 2442 of file winbase.h.
Enumeration Type Documentation
_ACL_INFORMATION_CLASS
enum _ACL_INFORMATION_CLASS
Enumerator
AclRevisionInformation
AclSizeInformation
Definition at line 998 of file winbase.h.
{
     AclRevisionInformation=1,
     AclSizeInformation
 } ACL_INFORMATION_CLASS;
_FINDEX_INFO_LEVELS
enum _FINDEX_INFO_LEVELS
Enumerator
FindExInfoStandard
FindExInfoMaxInfoLevel
Definition at line 988 of file winbase.h.
{
     FindExInfoStandard,
     FindExInfoMaxInfoLevel
 } FINDEX_INFO_LEVELS;
_FINDEX_SEARCH_OPS
enum _FINDEX_SEARCH_OPS
Enumerator
FindExSearchNameMatch
FindExSearchLimitToDirectories
FindExSearchLimitToDevices
FindExSearchMaxSearchOp
Definition at line 992 of file winbase.h.
{
     FindExSearchNameMatch,
     FindExSearchLimitToDirectories,
     FindExSearchLimitToDevices,
     FindExSearchMaxSearchOp
 } FINDEX_SEARCH_OPS;
_GET_FILEEX_INFO_LEVELS
enum _GET_FILEEX_INFO_LEVELS
Enumerator
GetFileExInfoStandard
GetFileExMaxInfoLevel
Definition at line 1012 of file winbase.h.
{
     GetFileExInfoStandard,
     GetFileExMaxInfoLevel
 } GET_FILEEX_INFO_LEVELS;
Function Documentation
_hread()
WINBASEAPI long WINAPI _hread (HFILE , LPVOID , long)
_hwrite()
WINBASEAPI long WINAPI _hwrite (HFILE , LPCSTR , long)
_lclose()
WINBASEAPI HFILE WINAPI _lclose (HFILE)
_lcreat()
WINBASEAPI HFILE WINAPI _lcreat (LPCSTR , int)
_llseek()
WINBASEAPI LONG WINAPI _llseek (HFILE , LONG , int)
_lopen()
WINBASEAPI HFILE WINAPI _lopen (LPCSTR , int)
_lread()
WINBASEAPI UINT WINAPI _lread (HFILE , LPVOID , UINT)
_lwrite()
WINBASEAPI UINT WINAPI _lwrite (HFILE , LPCSTR , UINT)
AccessCheck()
WINBASEAPI BOOL WINAPI AccessCheck (PSECURITY_DESCRIPTOR , HANDLE , DWORD , PGENERIC_MAPPING , PPRIVILEGE_SET , PDWORD , PDWORD , PBOOL)
AccessCheckAndAuditAlarmA()
WINBASEAPI BOOL WINAPI AccessCheckAndAuditAlarmA (LPCSTR , LPVOID , LPSTR , LPSTR , PSECURITY_DESCRIPTOR , DWORD , PGENERIC_MAPPING , BOOL , PDWORD , PBOOL , PBOOL)
AccessCheckAndAuditAlarmW()
WINBASEAPI BOOL WINAPI AccessCheckAndAuditAlarmW (LPCWSTR , LPVOID , LPWSTR , LPWSTR , PSECURITY_DESCRIPTOR , DWORD , PGENERIC_MAPPING , BOOL , PDWORD , PBOOL , PBOOL)
AddAccessAllowedAce()
WINBASEAPI BOOL WINAPI AddAccessAllowedAce (PACL , DWORD , DWORD , PSID)
AddAccessDeniedAce()
WINBASEAPI BOOL WINAPI AddAccessDeniedAce (PACL , DWORD , DWORD , PSID)
AddAce()
WINBASEAPI BOOL WINAPI AddAce (PACL , DWORD , DWORD , PVOID , DWORD)
AddAtomA()
WINBASEAPI ATOM WINAPI AddAtomA (LPCSTR)
AddAtomW()
WINBASEAPI ATOM WINAPI AddAtomW (LPCWSTR)
AddAuditAccessAce()
WINBASEAPI BOOL WINAPI AddAuditAccessAce (PACL , DWORD , DWORD , PSID , BOOL , BOOL)
AdjustTokenGroups()
WINBASEAPI BOOL WINAPI AdjustTokenGroups (HANDLE , BOOL , PTOKEN_GROUPS , DWORD , PTOKEN_GROUPS , PDWORD)
AdjustTokenPrivileges()
WINBASEAPI BOOL WINAPI AdjustTokenPrivileges (HANDLE , BOOL , PTOKEN_PRIVILEGES , DWORD , PTOKEN_PRIVILEGES , PDWORD)
AllocateAndInitializeSid()
WINBASEAPI BOOL WINAPI AllocateAndInitializeSid (PSID_IDENTIFIER_AUTHORITY , BYTE , DWORD , DWORD , DWORD , DWORD , DWORD , DWORD , DWORD , DWORD , PSID *)
AllocateLocallyUniqueId()
WINBASEAPI BOOL WINAPI AllocateLocallyUniqueId (PLUID)
AreAllAccessesGranted()
WINBASEAPI BOOL WINAPI AreAllAccessesGranted (DWORD , DWORD)
AreAnyAccessesGranted()
WINBASEAPI BOOL WINAPI AreAnyAccessesGranted (DWORD , DWORD)
AreFileApisANSI()
WINBASEAPI BOOL WINAPI AreFileApisANSI (void)
BackupEventLogA()
WINBASEAPI BOOL WINAPI BackupEventLogA (HANDLE , LPCSTR)
BackupEventLogW()
WINBASEAPI BOOL WINAPI BackupEventLogW (HANDLE , LPCWSTR)
BackupRead()
WINBASEAPI BOOL WINAPI BackupRead (HANDLE , LPBYTE , DWORD , LPDWORD , BOOL , BOOL , LPVOID *)
BackupSeek()
WINBASEAPI BOOL WINAPI BackupSeek (HANDLE , DWORD , DWORD , LPDWORD , LPDWORD , LPVOID *)
BackupWrite()
WINBASEAPI BOOL WINAPI BackupWrite (HANDLE , LPBYTE , DWORD , LPDWORD , BOOL , BOOL , LPVOID *)
Beep()
WINBASEAPI BOOL WINAPI Beep (DWORD , DWORD)
BeginUpdateResourceA()
WINBASEAPI HANDLE WINAPI BeginUpdateResourceA (LPCSTR , BOOL)
BeginUpdateResourceW()
WINBASEAPI HANDLE WINAPI BeginUpdateResourceW (LPCWSTR , BOOL)
BuildCommDCBA()
WINBASEAPI BOOL WINAPI BuildCommDCBA (LPCSTR , LPDCB)
BuildCommDCBAndTimeoutsA()
WINBASEAPI BOOL WINAPI BuildCommDCBAndTimeoutsA (LPCSTR , LPDCB , LPCOMMTIMEOUTS)
BuildCommDCBAndTimeoutsW()
WINBASEAPI BOOL WINAPI BuildCommDCBAndTimeoutsW (LPCWSTR , LPDCB , LPCOMMTIMEOUTS)
BuildCommDCBW()
WINBASEAPI BOOL WINAPI BuildCommDCBW (LPCWSTR , LPDCB)
CallNamedPipeA()
WINBASEAPI BOOL WINAPI CallNamedPipeA (LPCSTR , PVOID , DWORD , PVOID , DWORD , PDWORD , DWORD)
CallNamedPipeW()
WINBASEAPI BOOL WINAPI CallNamedPipeW (LPCWSTR , PVOID , DWORD , PVOID , DWORD , PDWORD , DWORD)
CancelDeviceWakeupRequest()
WINBASEAPI BOOL WINAPI CancelDeviceWakeupRequest (HANDLE)
CancelIo()
WINBASEAPI BOOL WINAPI CancelIo (HANDLE)
CancelWaitableTimer()
WINBASEAPI BOOL WINAPI CancelWaitableTimer (HANDLE)
ClearCommBreak()
WINBASEAPI BOOL WINAPI ClearCommBreak (HANDLE)
ClearCommError()
WINBASEAPI BOOL WINAPI ClearCommError (HANDLE , PDWORD , LPCOMSTAT)
ClearEventLogA()
WINBASEAPI BOOL WINAPI ClearEventLogA (HANDLE , LPCSTR)
ClearEventLogW()
WINBASEAPI BOOL WINAPI ClearEventLogW (HANDLE , LPCWSTR)
CloseEventLog()
WINBASEAPI BOOL WINAPI CloseEventLog (HANDLE)
CloseHandle()
WINBASEAPI BOOL WINAPI CloseHandle (HANDLE)
Referenced by __gthread_mutex_destroy(), CON_Shutdown(), mumble_link(), and mumble_unlink().
CommConfigDialogA()
WINBASEAPI BOOL WINAPI CommConfigDialogA (LPCSTR , HWND , LPCOMMCONFIG)
CommConfigDialogW()
WINBASEAPI BOOL WINAPI CommConfigDialogW (LPCWSTR , HWND , LPCOMMCONFIG)
CompareFileTime()
WINBASEAPI LONG WINAPI CompareFileTime (CONST FILETIME * , CONST FILETIME *)
ConnectNamedPipe()
WINBASEAPI BOOL WINAPI ConnectNamedPipe (HANDLE , LPOVERLAPPED)
ContinueDebugEvent()
WINBASEAPI BOOL WINAPI ContinueDebugEvent (DWORD , DWORD , DWORD)
ConvertThreadToFiber()
WINBASEAPI PVOID WINAPI ConvertThreadToFiber (PVOID)
CopyFileA()
WINBASEAPI BOOL WINAPI CopyFileA (LPCSTR , LPCSTR , BOOL)
CopyFileExA()
WINBASEAPI BOOL WINAPI CopyFileExA (LPCSTR , LPCSTR , LPPROGRESS_ROUTINE , LPVOID , LPBOOL , DWORD)
CopyFileExW()
WINBASEAPI BOOL WINAPI CopyFileExW (LPCWSTR , LPCWSTR , LPPROGRESS_ROUTINE , LPVOID , LPBOOL , DWORD)
CopyFileW()
WINBASEAPI BOOL WINAPI CopyFileW (LPCWSTR , LPCWSTR , BOOL)
CopySid()
WINBASEAPI BOOL WINAPI CopySid (DWORD , PSID , PSID)
CreateDirectoryA()
WINBASEAPI BOOL WINAPI CreateDirectoryA (LPCSTR , LPSECURITY_ATTRIBUTES)
CreateDirectoryExA()
WINBASEAPI BOOL WINAPI CreateDirectoryExA (LPCSTR , LPCSTR , LPSECURITY_ATTRIBUTES)
CreateDirectoryExW()
WINBASEAPI BOOL WINAPI CreateDirectoryExW (LPCWSTR , LPCWSTR , LPSECURITY_ATTRIBUTES)
CreateDirectoryW()
WINBASEAPI BOOL WINAPI CreateDirectoryW (LPCWSTR , LPSECURITY_ATTRIBUTES)
CreateEventA()
WINBASEAPI HANDLE WINAPI CreateEventA (LPSECURITY_ATTRIBUTES , BOOL , BOOL , LPCSTR)
CreateEventW()
WINBASEAPI HANDLE WINAPI CreateEventW (LPSECURITY_ATTRIBUTES , BOOL , BOOL , LPCWSTR)
CreateFiber()
WINBASEAPI LPVOID WINAPI CreateFiber (SIZE_T , LPFIBER_START_ROUTINE , LPVOID)
CreateFileA()
WINBASEAPI HANDLE WINAPI CreateFileA (LPCSTR , DWORD , DWORD , LPSECURITY_ATTRIBUTES , DWORD , DWORD , HANDLE)
CreateFileMappingA()
WINBASEAPI HANDLE WINAPI CreateFileMappingA (HANDLE , LPSECURITY_ATTRIBUTES , DWORD , DWORD , DWORD , LPCSTR)
CreateFileMappingW()
WINBASEAPI HANDLE WINAPI CreateFileMappingW (HANDLE , LPSECURITY_ATTRIBUTES , DWORD , DWORD , DWORD , LPCWSTR)
CreateFileW()
WINBASEAPI HANDLE WINAPI CreateFileW (LPCWSTR , DWORD , DWORD , LPSECURITY_ATTRIBUTES , DWORD , DWORD , HANDLE)
CreateIoCompletionPort()
WINBASEAPI HANDLE WINAPI CreateIoCompletionPort (HANDLE , HANDLE , ULONG_PTR , DWORD)
CreateMailslotA()
WINBASEAPI HANDLE WINAPI CreateMailslotA (LPCSTR , DWORD , DWORD , LPSECURITY_ATTRIBUTES)
CreateMailslotW()
WINBASEAPI HANDLE WINAPI CreateMailslotW (LPCWSTR , DWORD , DWORD , LPSECURITY_ATTRIBUTES)
CreateMutexA()
WINBASEAPI HANDLE WINAPI CreateMutexA (LPSECURITY_ATTRIBUTES , BOOL , LPCSTR)
CreateMutexW()
WINBASEAPI HANDLE WINAPI CreateMutexW (LPSECURITY_ATTRIBUTES , BOOL , LPCWSTR)
CreateNamedPipeA()
WINBASEAPI HANDLE WINAPI CreateNamedPipeA (LPCSTR , DWORD , DWORD , DWORD , DWORD , DWORD , DWORD , LPSECURITY_ATTRIBUTES)
CreateNamedPipeW()
WINBASEAPI HANDLE WINAPI CreateNamedPipeW (LPCWSTR , DWORD , DWORD , DWORD , DWORD , DWORD , DWORD , LPSECURITY_ATTRIBUTES)
CreatePipe()
WINBASEAPI BOOL WINAPI CreatePipe (PHANDLE , PHANDLE , LPSECURITY_ATTRIBUTES , DWORD)
CreatePrivateObjectSecurity()
WINBASEAPI BOOL WINAPI CreatePrivateObjectSecurity (PSECURITY_DESCRIPTOR , PSECURITY_DESCRIPTOR , PSECURITY_DESCRIPTOR * , BOOL , HANDLE , PGENERIC_MAPPING)
CreateProcessA()
WINBASEAPI BOOL WINAPI CreateProcessA (LPCSTR , LPSTR , LPSECURITY_ATTRIBUTES , LPSECURITY_ATTRIBUTES , BOOL , DWORD , PVOID , LPCSTR , LPSTARTUPINFOA , LPPROCESS_INFORMATION)
CreateProcessAsUserA()
WINBASEAPI BOOL WINAPI CreateProcessAsUserA (HANDLE , LPCSTR , LPSTR , LPSECURITY_ATTRIBUTES , LPSECURITY_ATTRIBUTES , BOOL , DWORD , PVOID , LPCSTR , LPSTARTUPINFOA , LPPROCESS_INFORMATION)
CreateProcessAsUserW()
WINBASEAPI BOOL WINAPI CreateProcessAsUserW (HANDLE , LPCWSTR , LPWSTR , LPSECURITY_ATTRIBUTES , LPSECURITY_ATTRIBUTES , BOOL , DWORD , PVOID , LPCWSTR , LPSTARTUPINFOW , LPPROCESS_INFORMATION)
CreateProcessW()
WINBASEAPI BOOL WINAPI CreateProcessW (LPCWSTR , LPWSTR , LPSECURITY_ATTRIBUTES , LPSECURITY_ATTRIBUTES , BOOL , DWORD , PVOID , LPCWSTR , LPSTARTUPINFOW , LPPROCESS_INFORMATION)
CreateRemoteThread()
WINBASEAPI HANDLE WINAPI CreateRemoteThread (HANDLE , LPSECURITY_ATTRIBUTES , DWORD , LPTHREAD_START_ROUTINE , LPVOID , DWORD , LPDWORD)
CreateSemaphoreA()
WINBASEAPI HANDLE WINAPI CreateSemaphoreA (LPSECURITY_ATTRIBUTES , LONG , LONG , LPCSTR)
CreateSemaphoreW()
WINBASEAPI HANDLE WINAPI CreateSemaphoreW (LPSECURITY_ATTRIBUTES , LONG , LONG , LPCWSTR)
CreateTapePartition()
WINBASEAPI DWORD WINAPI CreateTapePartition (HANDLE , DWORD , DWORD , DWORD)
CreateThread()
WINBASEAPI HANDLE WINAPI CreateThread (LPSECURITY_ATTRIBUTES , DWORD , LPTHREAD_START_ROUTINE , PVOID , DWORD , PDWORD)
CreateWaitableTimerA()
WINBASEAPI HANDLE WINAPI CreateWaitableTimerA (LPSECURITY_ATTRIBUTES , BOOL , LPCSTR)
CreateWaitableTimerW()
WINBASEAPI HANDLE WINAPI CreateWaitableTimerW (LPSECURITY_ATTRIBUTES , BOOL , LPCWSTR)
DebugActiveProcess()
WINBASEAPI BOOL WINAPI DebugActiveProcess (DWORD)
DebugBreak()
WINBASEAPI void WINAPI DebugBreak (void)
DefineDosDeviceA()
WINBASEAPI BOOL WINAPI DefineDosDeviceA (DWORD , LPCSTR , LPCSTR)
DefineDosDeviceW()
WINBASEAPI BOOL WINAPI DefineDosDeviceW (DWORD , LPCWSTR , LPCWSTR)
DeleteAce()
WINBASEAPI BOOL WINAPI DeleteAce (PACL , DWORD)
DeleteAtom()
WINBASEAPI ATOM WINAPI DeleteAtom (ATOM)
DeleteCriticalSection()
WINBASEAPI void WINAPI DeleteCriticalSection (PCRITICAL_SECTION)
DeleteFiber()
WINBASEAPI void WINAPI DeleteFiber (PVOID)
DeleteFileA()
WINBASEAPI BOOL WINAPI DeleteFileA (LPCSTR)
DeleteFileW()
WINBASEAPI BOOL WINAPI DeleteFileW (LPCWSTR)
DeregisterEventSource()
WINBASEAPI BOOL WINAPI DeregisterEventSource (HANDLE)
DestroyPrivateObjectSecurity()
WINBASEAPI BOOL WINAPI DestroyPrivateObjectSecurity (PSECURITY_DESCRIPTOR *)
DeviceIoControl()
WINBASEAPI BOOL WINAPI DeviceIoControl (HANDLE , DWORD , PVOID , DWORD , PVOID , DWORD , PDWORD , POVERLAPPED)
DisableThreadLibraryCalls()
WINBASEAPI BOOL WINAPI DisableThreadLibraryCalls (HMODULE)
DisconnectNamedPipe()
WINBASEAPI BOOL WINAPI DisconnectNamedPipe (HANDLE)
DosDateTimeToFileTime()
WINBASEAPI BOOL WINAPI DosDateTimeToFileTime (WORD , WORD , LPFILETIME)
DuplicateHandle()
WINBASEAPI BOOL WINAPI DuplicateHandle (HANDLE , HANDLE , HANDLE , PHANDLE , DWORD , BOOL , DWORD)
DuplicateToken()
WINBASEAPI BOOL WINAPI DuplicateToken (HANDLE , SECURITY_IMPERSONATION_LEVEL , PHANDLE)
DuplicateTokenEx()
WINBASEAPI BOOL WINAPI DuplicateTokenEx (HANDLE , DWORD , LPSECURITY_ATTRIBUTES , SECURITY_IMPERSONATION_LEVEL , TOKEN_TYPE , PHANDLE)
EncryptFileA()
WINBASEAPI BOOL WINAPI EncryptFileA (LPCSTR)
EncryptFileW()
WINBASEAPI BOOL WINAPI EncryptFileW (LPCWSTR)
EndUpdateResourceA()
WINBASEAPI BOOL WINAPI EndUpdateResourceA (HANDLE , BOOL)
EndUpdateResourceW()
WINBASEAPI BOOL WINAPI EndUpdateResourceW (HANDLE , BOOL)
EnterCriticalSection()
WINBASEAPI void WINAPI EnterCriticalSection (LPCRITICAL_SECTION)
EnumResourceLanguagesA()
WINBASEAPI BOOL WINAPI EnumResourceLanguagesA (HMODULE , LPCSTR , LPCSTR , ENUMRESLANGPROCA , LONG_PTR)
EnumResourceLanguagesW()
WINBASEAPI BOOL WINAPI EnumResourceLanguagesW (HMODULE , LPCWSTR , LPCWSTR , ENUMRESLANGPROCW , LONG_PTR)
EnumResourceNamesA()
WINBASEAPI BOOL WINAPI EnumResourceNamesA (HMODULE , LPCSTR , ENUMRESNAMEPROCA , LONG_PTR)
EnumResourceNamesW()
WINBASEAPI BOOL WINAPI EnumResourceNamesW (HMODULE , LPCWSTR , ENUMRESNAMEPROCW , LONG_PTR)
EnumResourceTypesA()
WINBASEAPI BOOL WINAPI EnumResourceTypesA (HMODULE , ENUMRESTYPEPROCA , LONG_PTR)
EnumResourceTypesW()
WINBASEAPI BOOL WINAPI EnumResourceTypesW (HMODULE , ENUMRESTYPEPROCW , LONG_PTR)
EqualPrefixSid()
WINBASEAPI BOOL WINAPI EqualPrefixSid (PSID , PSID)
EqualSid()
WINBASEAPI BOOL WINAPI EqualSid (PSID , PSID)
EraseTape()
WINBASEAPI DWORD WINAPI EraseTape (HANDLE , DWORD , BOOL)
EscapeCommFunction()
WINBASEAPI BOOL WINAPI EscapeCommFunction (HANDLE , DWORD)
ExitProcess()
DECLSPEC_NORETURN WINBASEAPI void WINAPI ExitProcess (UINT)
ExitThread()
DECLSPEC_NORETURN WINBASEAPI void WINAPI ExitThread (DWORD)
ExpandEnvironmentStringsA()
WINBASEAPI DWORD WINAPI ExpandEnvironmentStringsA (LPCSTR , LPSTR , DWORD)
ExpandEnvironmentStringsW()
WINBASEAPI DWORD WINAPI ExpandEnvironmentStringsW (LPCWSTR , LPWSTR , DWORD)
FatalAppExitA()
WINBASEAPI void WINAPI FatalAppExitA (UINT , LPCSTR)
FatalAppExitW()
WINBASEAPI void WINAPI FatalAppExitW (UINT , LPCWSTR)
FatalExit()
WINBASEAPI void WINAPI FatalExit (int)
FileEncryptionStatusA()
WINBASEAPI BOOL WINAPI FileEncryptionStatusA (LPCSTR , LPDWORD)
FileEncryptionStatusW()
WINBASEAPI BOOL WINAPI FileEncryptionStatusW (LPCWSTR , LPDWORD)
FileTimeToDosDateTime()
WINBASEAPI BOOL WINAPI FileTimeToDosDateTime (CONST FILETIME * , LPWORD , LPWORD)
FileTimeToLocalFileTime()
WINBASEAPI BOOL WINAPI FileTimeToLocalFileTime (CONST FILETIME * , LPFILETIME)
FileTimeToSystemTime()
WINBASEAPI BOOL WINAPI FileTimeToSystemTime (CONST FILETIME * , LPSYSTEMTIME)
FindAtomA()
WINBASEAPI ATOM WINAPI FindAtomA (LPCSTR)
FindAtomW()
WINBASEAPI ATOM WINAPI FindAtomW (LPCWSTR)
FindClose()
WINBASEAPI BOOL WINAPI FindClose (HANDLE)
FindCloseChangeNotification()
WINBASEAPI BOOL WINAPI FindCloseChangeNotification (HANDLE)
FindFirstChangeNotificationA()
WINBASEAPI HANDLE WINAPI FindFirstChangeNotificationA (LPCSTR , BOOL , DWORD)
FindFirstChangeNotificationW()
WINBASEAPI HANDLE WINAPI FindFirstChangeNotificationW (LPCWSTR , BOOL , DWORD)
FindFirstFileA()
WINBASEAPI HANDLE WINAPI FindFirstFileA (LPCSTR , LPWIN32_FIND_DATAA)
FindFirstFileExA()
WINBASEAPI HANDLE WINAPI FindFirstFileExA (LPCSTR , FINDEX_INFO_LEVELS , PVOID , FINDEX_SEARCH_OPS , PVOID , DWORD)
FindFirstFileExW()
WINBASEAPI HANDLE WINAPI FindFirstFileExW (LPCWSTR , FINDEX_INFO_LEVELS , PVOID , FINDEX_SEARCH_OPS , PVOID , DWORD)
FindFirstFileW()
WINBASEAPI HANDLE WINAPI FindFirstFileW (LPCWSTR , LPWIN32_FIND_DATAW)
FindFirstFreeAce()
WINBASEAPI BOOL WINAPI FindFirstFreeAce (PACL , PVOID *)
FindNextChangeNotification()
WINBASEAPI BOOL WINAPI FindNextChangeNotification (HANDLE)
FindNextFileA()
WINBASEAPI BOOL WINAPI FindNextFileA (HANDLE , LPWIN32_FIND_DATAA)
FindNextFileW()
WINBASEAPI BOOL WINAPI FindNextFileW (HANDLE , LPWIN32_FIND_DATAW)
FindResourceA()
WINBASEAPI HRSRC WINAPI FindResourceA (HMODULE , LPCSTR , LPCSTR)
FindResourceExA()
WINBASEAPI HRSRC WINAPI FindResourceExA (HINSTANCE , LPCSTR , LPCSTR , WORD)
FindResourceExW()
WINBASEAPI HRSRC WINAPI FindResourceExW (HINSTANCE , LPCWSTR , LPCWSTR , WORD)
FindResourceW()
WINBASEAPI HRSRC WINAPI FindResourceW (HINSTANCE , LPCWSTR , LPCWSTR)
FlushFileBuffers()
WINBASEAPI BOOL WINAPI FlushFileBuffers (HANDLE)
FlushInstructionCache()
WINBASEAPI BOOL WINAPI FlushInstructionCache (HANDLE , PCVOID , DWORD)
FlushViewOfFile()
WINBASEAPI BOOL WINAPI FlushViewOfFile (PCVOID , DWORD)
FormatMessageA()
WINBASEAPI DWORD WINAPI FormatMessageA (DWORD , PCVOID , DWORD , DWORD , LPSTR , DWORD , va_list *)
Referenced by gai_strerrorA().
FormatMessageW()
WINBASEAPI DWORD WINAPI FormatMessageW (DWORD , PCVOID , DWORD , DWORD , LPWSTR , DWORD , va_list *)
Referenced by gai_strerrorW().
FreeEnvironmentStringsA()
WINBASEAPI BOOL WINAPI FreeEnvironmentStringsA (LPSTR)
FreeEnvironmentStringsW()
WINBASEAPI BOOL WINAPI FreeEnvironmentStringsW (LPWSTR)
FreeLibrary()
WINBASEAPI BOOL WINAPI FreeLibrary (HMODULE)
Referenced by Sys_DefaultHomePath().
FreeLibraryAndExitThread()
DECLSPEC_NORETURN WINBASEAPI void WINAPI FreeLibraryAndExitThread (HMODULE , DWORD)
FreeResource()
WINBASEAPI BOOL WINAPI FreeResource (HGLOBAL)
FreeSid()
WINBASEAPI PVOID WINAPI FreeSid (PSID)
GetAce()
WINBASEAPI BOOL WINAPI GetAce (PACL , DWORD , LPVOID *)
GetAclInformation()
WINBASEAPI BOOL WINAPI GetAclInformation (PACL , PVOID , DWORD , ACL_INFORMATION_CLASS)
GetAtomNameA()
WINBASEAPI UINT WINAPI GetAtomNameA (ATOM , LPSTR , int)
GetAtomNameW()
WINBASEAPI UINT WINAPI GetAtomNameW (ATOM , LPWSTR , int)
GetBinaryTypeA()
WINBASEAPI BOOL WINAPI GetBinaryTypeA (LPCSTR , PDWORD)
GetBinaryTypeW()
WINBASEAPI BOOL WINAPI GetBinaryTypeW (LPCWSTR , PDWORD)
GetCommandLineA()
WINBASEAPI LPSTR WINAPI GetCommandLineA (VOID)
GetCommandLineW()
WINBASEAPI LPWSTR WINAPI GetCommandLineW (VOID)
GetCommConfig()
WINBASEAPI BOOL WINAPI GetCommConfig (HANDLE , LPCOMMCONFIG , PDWORD)
GetCommMask()
WINBASEAPI BOOL WINAPI GetCommMask (HANDLE , PDWORD)
GetCommModemStatus()
WINBASEAPI BOOL WINAPI GetCommModemStatus (HANDLE , PDWORD)
GetCommProperties()
WINBASEAPI BOOL WINAPI GetCommProperties (HANDLE , LPCOMMPROP)
GetCommState()
WINBASEAPI BOOL WINAPI GetCommState (HANDLE , LPDCB)
GetCommTimeouts()
WINBASEAPI BOOL WINAPI GetCommTimeouts (HANDLE , LPCOMMTIMEOUTS)
GetCompressedFileSizeA()
WINBASEAPI DWORD WINAPI GetCompressedFileSizeA (LPCSTR , PDWORD)
GetCompressedFileSizeW()
WINBASEAPI DWORD WINAPI GetCompressedFileSizeW (LPCWSTR , PDWORD)
GetComputerNameA()
WINBASEAPI BOOL WINAPI GetComputerNameA (LPSTR , PDWORD)
GetComputerNameW()
WINBASEAPI BOOL WINAPI GetComputerNameW (LPWSTR , PDWORD)
GetCurrentDirectoryA()
WINBASEAPI DWORD WINAPI GetCurrentDirectoryA (DWORD , LPSTR)
GetCurrentDirectoryW()
WINBASEAPI DWORD WINAPI GetCurrentDirectoryW (DWORD , LPWSTR)
GetCurrentHwProfileA()
WINBASEAPI BOOL WINAPI GetCurrentHwProfileA (LPHW_PROFILE_INFOA)
GetCurrentHwProfileW()
WINBASEAPI BOOL WINAPI GetCurrentHwProfileW (LPHW_PROFILE_INFOW)
GetCurrentProcess()
WINBASEAPI HANDLE WINAPI GetCurrentProcess (void)
GetCurrentProcessId()
WINBASEAPI DWORD WINAPI GetCurrentProcessId (void)
Referenced by Sys_PID().
GetCurrentThread()
WINBASEAPI HANDLE WINAPI GetCurrentThread (void)
GetCurrentThreadId()
WINBASEAPI DWORD WINAPI GetCurrentThreadId (void)
Referenced by __gthread_recursive_mutex_lock(), and __gthread_recursive_mutex_trylock().
GetDefaultCommConfigA()
WINBASEAPI BOOL WINAPI GetDefaultCommConfigA (LPCSTR , LPCOMMCONFIG , PDWORD)
GetDefaultCommConfigW()
WINBASEAPI BOOL WINAPI GetDefaultCommConfigW (LPCWSTR , LPCOMMCONFIG , PDWORD)
GetDevicePowerState()
WINBASEAPI BOOL WINAPI GetDevicePowerState (HANDLE , BOOL *)
GetDiskFreeSpaceA()
WINBASEAPI BOOL WINAPI GetDiskFreeSpaceA (LPCSTR , PDWORD , PDWORD , PDWORD , PDWORD)
GetDiskFreeSpaceExA()
WINBASEAPI BOOL WINAPI GetDiskFreeSpaceExA (LPCSTR , PULARGE_INTEGER , PULARGE_INTEGER , PULARGE_INTEGER)
GetDiskFreeSpaceExW()
WINBASEAPI BOOL WINAPI GetDiskFreeSpaceExW (LPCWSTR , PULARGE_INTEGER , PULARGE_INTEGER , PULARGE_INTEGER)
GetDiskFreeSpaceW()
WINBASEAPI BOOL WINAPI GetDiskFreeSpaceW (LPCWSTR , PDWORD , PDWORD , PDWORD , PDWORD)
GetDriveTypeA()
WINBASEAPI UINT WINAPI GetDriveTypeA (LPCSTR)
GetDriveTypeW()
WINBASEAPI UINT WINAPI GetDriveTypeW (LPCWSTR)
GetEnvironmentStrings()
WINBASEAPI LPCH WINAPI GetEnvironmentStrings (void)
GetEnvironmentStringsA()
WINBASEAPI LPCH WINAPI GetEnvironmentStringsA (void)
GetEnvironmentStringsW()
WINBASEAPI LPWCH WINAPI GetEnvironmentStringsW (void)
GetEnvironmentVariableA()
WINBASEAPI DWORD WINAPI GetEnvironmentVariableA (LPCSTR , LPSTR , DWORD)
GetEnvironmentVariableW()
WINBASEAPI DWORD WINAPI GetEnvironmentVariableW (LPCWSTR , LPWSTR , DWORD)
GetExitCodeProcess()
WINBASEAPI BOOL WINAPI GetExitCodeProcess (HANDLE , PDWORD)
GetExitCodeThread()
WINBASEAPI BOOL WINAPI GetExitCodeThread (HANDLE , PDWORD)
GetFileAttributesA()
WINBASEAPI DWORD WINAPI GetFileAttributesA (LPCSTR)
GetFileAttributesExA()
WINBASEAPI BOOL WINAPI GetFileAttributesExA (LPCSTR , GET_FILEEX_INFO_LEVELS , PVOID)
GetFileAttributesExW()
WINBASEAPI BOOL WINAPI GetFileAttributesExW (LPCWSTR , GET_FILEEX_INFO_LEVELS , PVOID)
GetFileAttributesW()
WINBASEAPI DWORD WINAPI GetFileAttributesW (LPCWSTR)
GetFileInformationByHandle()
WINBASEAPI BOOL WINAPI GetFileInformationByHandle (HANDLE , LPBY_HANDLE_FILE_INFORMATION)
GetFileSecurityA()
WINBASEAPI BOOL WINAPI GetFileSecurityA (LPCSTR , SECURITY_INFORMATION , PSECURITY_DESCRIPTOR , DWORD , PDWORD)
GetFileSecurityW()
WINBASEAPI BOOL WINAPI GetFileSecurityW (LPCWSTR , SECURITY_INFORMATION , PSECURITY_DESCRIPTOR , DWORD , PDWORD)
GetFileSize()
WINBASEAPI DWORD WINAPI GetFileSize (HANDLE , PDWORD)
GetFileTime()
WINBASEAPI BOOL WINAPI GetFileTime (HANDLE , LPFILETIME , LPFILETIME , LPFILETIME)
GetFileType()
WINBASEAPI DWORD WINAPI GetFileType (HANDLE)
GetFullPathNameA()
WINBASEAPI DWORD WINAPI GetFullPathNameA (LPCSTR , DWORD , LPSTR , LPSTR *)
GetFullPathNameW()
WINBASEAPI DWORD WINAPI GetFullPathNameW (LPCWSTR , DWORD , LPWSTR , LPWSTR *)
GetHandleInformation()
WINBASEAPI BOOL WINAPI GetHandleInformation (HANDLE , PDWORD)
GetKernelObjectSecurity()
WINBASEAPI BOOL WINAPI GetKernelObjectSecurity (HANDLE , SECURITY_INFORMATION , PSECURITY_DESCRIPTOR , DWORD , PDWORD)
GetLastError()
WINBASEAPI DWORD WINAPI GetLastError (void)
Referenced by __gthread_getspecific(), __gthread_key_create(), __gthread_key_delete(), __gthread_setspecific(), and Sys_Mkdir().
GetLengthSid()
WINBASEAPI DWORD WINAPI GetLengthSid (PSID)
GetLocalTime()
WINBASEAPI void WINAPI GetLocalTime (LPSYSTEMTIME)
GetLogicalDrives()
WINBASEAPI DWORD WINAPI GetLogicalDrives (void)
GetLogicalDriveStringsA()
WINBASEAPI DWORD WINAPI GetLogicalDriveStringsA (DWORD , LPSTR)
GetLogicalDriveStringsW()
WINBASEAPI DWORD WINAPI GetLogicalDriveStringsW (DWORD , LPWSTR)
GetMailslotInfo()
WINBASEAPI BOOL WINAPI GetMailslotInfo (HANDLE , PDWORD , PDWORD , PDWORD , PDWORD)
GetModuleFileNameA()
WINBASEAPI DWORD WINAPI GetModuleFileNameA (HINSTANCE , LPSTR , DWORD)
GetModuleFileNameW()
WINBASEAPI DWORD WINAPI GetModuleFileNameW (HINSTANCE , LPWSTR , DWORD)
GetModuleHandleA()
WINBASEAPI HMODULE WINAPI GetModuleHandleA (LPCSTR)
GetModuleHandleW()
WINBASEAPI HMODULE WINAPI GetModuleHandleW (LPCWSTR)
GetNamedPipeHandleStateA()
WINBASEAPI BOOL WINAPI GetNamedPipeHandleStateA (HANDLE , PDWORD , PDWORD , PDWORD , PDWORD , LPSTR , DWORD)
GetNamedPipeHandleStateW()
WINBASEAPI BOOL WINAPI GetNamedPipeHandleStateW (HANDLE , PDWORD , PDWORD , PDWORD , PDWORD , LPWSTR , DWORD)
GetNamedPipeInfo()
WINBASEAPI BOOL WINAPI GetNamedPipeInfo (HANDLE , PDWORD , PDWORD , PDWORD , PDWORD)
GetNumberOfEventLogRecords()
WINBASEAPI BOOL WINAPI GetNumberOfEventLogRecords (HANDLE , PDWORD)
GetOldestEventLogRecord()
WINBASEAPI BOOL WINAPI GetOldestEventLogRecord (HANDLE , PDWORD)
GetOverlappedResult()
WINBASEAPI BOOL WINAPI GetOverlappedResult (HANDLE , LPOVERLAPPED , PDWORD , BOOL)
GetPriorityClass()
WINBASEAPI DWORD WINAPI GetPriorityClass (HANDLE)
GetPrivateObjectSecurity()
WINBASEAPI BOOL WINAPI GetPrivateObjectSecurity (PSECURITY_DESCRIPTOR , SECURITY_INFORMATION , PSECURITY_DESCRIPTOR , DWORD , PDWORD)
GetPrivateProfileIntA()
WINBASEAPI UINT WINAPI GetPrivateProfileIntA (LPCSTR , LPCSTR , INT , LPCSTR)
GetPrivateProfileIntW()
WINBASEAPI UINT WINAPI GetPrivateProfileIntW (LPCWSTR , LPCWSTR , INT , LPCWSTR)
GetPrivateProfileSectionA()
WINBASEAPI DWORD WINAPI GetPrivateProfileSectionA (LPCSTR , LPSTR , DWORD , LPCSTR)
GetPrivateProfileSectionNamesA()
WINBASEAPI DWORD WINAPI GetPrivateProfileSectionNamesA (LPSTR , DWORD , LPCSTR)
GetPrivateProfileSectionNamesW()
WINBASEAPI DWORD WINAPI GetPrivateProfileSectionNamesW (LPWSTR , DWORD , LPCWSTR)
GetPrivateProfileSectionW()
WINBASEAPI DWORD WINAPI GetPrivateProfileSectionW (LPCWSTR , LPWSTR , DWORD , LPCWSTR)
GetPrivateProfileStringA()
WINBASEAPI DWORD WINAPI GetPrivateProfileStringA (LPCSTR , LPCSTR , LPCSTR , LPSTR , DWORD , LPCSTR)
GetPrivateProfileStringW()
WINBASEAPI DWORD WINAPI GetPrivateProfileStringW (LPCWSTR , LPCWSTR , LPCWSTR , LPWSTR , DWORD , LPCWSTR)
GetPrivateProfileStructA()
WINBASEAPI BOOL WINAPI GetPrivateProfileStructA (LPCSTR , LPCSTR , LPVOID , UINT , LPCSTR)
GetPrivateProfileStructW()
WINBASEAPI BOOL WINAPI GetPrivateProfileStructW (LPCWSTR , LPCWSTR , LPVOID , UINT , LPCWSTR)
GetProcAddress()
WINBASEAPI FARPROC WINAPI GetProcAddress (HINSTANCE , LPCSTR)
Referenced by Sys_DefaultHomePath().
GetProcessAffinityMask()
WINBASEAPI BOOL WINAPI GetProcessAffinityMask (HANDLE , PDWORD , PDWORD)
GetProcessHeap()
WINBASEAPI HANDLE WINAPI GetProcessHeap (VOID)
GetProcessHeaps()
WINBASEAPI DWORD WINAPI GetProcessHeaps (DWORD , PHANDLE)
GetProcessPriorityBoost()
WINBASEAPI BOOL WINAPI GetProcessPriorityBoost (HANDLE , PBOOL)
GetProcessShutdownParameters()
WINBASEAPI BOOL WINAPI GetProcessShutdownParameters (PDWORD , PDWORD)
GetProcessTimes()
WINBASEAPI BOOL WINAPI GetProcessTimes (HANDLE , LPFILETIME , LPFILETIME , LPFILETIME , LPFILETIME)
GetProcessVersion()
WINBASEAPI DWORD WINAPI GetProcessVersion (DWORD)
GetProcessWindowStation()
WINBASEAPI HWINSTA WINAPI GetProcessWindowStation (void)
GetProcessWorkingSetSize()
WINBASEAPI BOOL WINAPI GetProcessWorkingSetSize (HANDLE , PSIZE_T , PSIZE_T)
GetProfileIntA()
WINBASEAPI UINT WINAPI GetProfileIntA (LPCSTR , LPCSTR , INT)
GetProfileIntW()
WINBASEAPI UINT WINAPI GetProfileIntW (LPCWSTR , LPCWSTR , INT)
GetProfileSectionA()
WINBASEAPI DWORD WINAPI GetProfileSectionA (LPCSTR , LPSTR , DWORD)
GetProfileSectionW()
WINBASEAPI DWORD WINAPI GetProfileSectionW (LPCWSTR , LPWSTR , DWORD)
GetProfileStringA()
WINBASEAPI DWORD WINAPI GetProfileStringA (LPCSTR , LPCSTR , LPCSTR , LPSTR , DWORD)
GetProfileStringW()
WINBASEAPI DWORD WINAPI GetProfileStringW (LPCWSTR , LPCWSTR , LPCWSTR , LPWSTR , DWORD)
GetQueuedCompletionStatus()
WINBASEAPI BOOL WINAPI GetQueuedCompletionStatus (HANDLE , PDWORD , PULONG_PTR , LPOVERLAPPED * , DWORD)
GetSecurityDescriptorControl()
WINBASEAPI BOOL WINAPI GetSecurityDescriptorControl (PSECURITY_DESCRIPTOR , PSECURITY_DESCRIPTOR_CONTROL , PDWORD)
GetSecurityDescriptorDacl()
WINBASEAPI BOOL WINAPI GetSecurityDescriptorDacl (PSECURITY_DESCRIPTOR , LPBOOL , PACL * , LPBOOL)
GetSecurityDescriptorGroup()
WINBASEAPI BOOL WINAPI GetSecurityDescriptorGroup (PSECURITY_DESCRIPTOR , PSID * , LPBOOL)
GetSecurityDescriptorLength()
WINBASEAPI DWORD WINAPI GetSecurityDescriptorLength (PSECURITY_DESCRIPTOR)
GetSecurityDescriptorOwner()
WINBASEAPI BOOL WINAPI GetSecurityDescriptorOwner (PSECURITY_DESCRIPTOR , PSID * , LPBOOL)
GetSecurityDescriptorSacl()
WINBASEAPI BOOL WINAPI GetSecurityDescriptorSacl (PSECURITY_DESCRIPTOR , LPBOOL , PACL * , LPBOOL)
GetShortPathNameA()
WINBASEAPI DWORD WINAPI GetShortPathNameA (LPCSTR , LPSTR , DWORD)
GetShortPathNameW()
WINBASEAPI DWORD WINAPI GetShortPathNameW (LPCWSTR , LPWSTR , DWORD)
GetSidIdentifierAuthority()
WINBASEAPI PSID_IDENTIFIER_AUTHORITY WINAPI GetSidIdentifierAuthority (PSID)
GetSidLengthRequired()
WINBASEAPI DWORD WINAPI GetSidLengthRequired (UCHAR)
GetSidSubAuthority()
WINBASEAPI PDWORD WINAPI GetSidSubAuthority (PSID , DWORD)
GetSidSubAuthorityCount()
WINBASEAPI PUCHAR WINAPI GetSidSubAuthorityCount (PSID)
GetStartupInfoA()
WINBASEAPI VOID WINAPI GetStartupInfoA (LPSTARTUPINFOA)
GetStartupInfoW()
WINBASEAPI VOID WINAPI GetStartupInfoW (LPSTARTUPINFOW)
GetStdHandle()
WINBASEAPI HANDLE WINAPI GetStdHandle (DWORD)
Referenced by CON_Init(), and Sys_Sleep().
GetSystemDirectoryA()
WINBASEAPI UINT WINAPI GetSystemDirectoryA (LPSTR , UINT)
GetSystemDirectoryW()
WINBASEAPI UINT WINAPI GetSystemDirectoryW (LPWSTR , UINT)
GetSystemInfo()
WINBASEAPI VOID WINAPI GetSystemInfo (LPSYSTEM_INFO)
GetSystemPowerStatus()
WINBASEAPI BOOL WINAPI GetSystemPowerStatus (LPSYSTEM_POWER_STATUS)
GetSystemTime()
WINBASEAPI VOID WINAPI GetSystemTime (LPSYSTEMTIME)
GetSystemTimeAdjustment()
WINBASEAPI BOOL WINAPI GetSystemTimeAdjustment (PDWORD , PDWORD , PBOOL)
GetSystemTimeAsFileTime()
WINBASEAPI void WINAPI GetSystemTimeAsFileTime (LPFILETIME)
GetTapeParameters()
WINBASEAPI DWORD WINAPI GetTapeParameters (HANDLE , DWORD , PDWORD , PVOID)
GetTapePosition()
WINBASEAPI DWORD WINAPI GetTapePosition (HANDLE , DWORD , PDWORD , PDWORD , PDWORD)
GetTapeStatus()
WINBASEAPI DWORD WINAPI GetTapeStatus (HANDLE)
GetTempFileNameA()
WINBASEAPI UINT WINAPI GetTempFileNameA (LPCSTR , LPCSTR , UINT , LPSTR)
GetTempFileNameW()
WINBASEAPI UINT WINAPI GetTempFileNameW (LPCWSTR , LPCWSTR , UINT , LPWSTR)
GetTempPathA()
WINBASEAPI DWORD WINAPI GetTempPathA (DWORD , LPSTR)
GetTempPathW()
WINBASEAPI DWORD WINAPI GetTempPathW (DWORD , LPWSTR)
GetThreadContext()
WINBASEAPI BOOL WINAPI GetThreadContext (HANDLE , LPCONTEXT)
GetThreadPriority()
WINBASEAPI int WINAPI GetThreadPriority (HANDLE)
GetThreadPriorityBoost()
WINBASEAPI BOOL WINAPI GetThreadPriorityBoost (HANDLE , PBOOL)
GetThreadSelectorEntry()
WINBASEAPI BOOL WINAPI GetThreadSelectorEntry (HANDLE , DWORD , LPLDT_ENTRY)
GetThreadTimes()
WINBASEAPI BOOL WINAPI GetThreadTimes (HANDLE , LPFILETIME , LPFILETIME , LPFILETIME , LPFILETIME)
GetTickCount()
WINBASEAPI DWORD WINAPI GetTickCount (VOID)
GetTimeZoneInformation()
WINBASEAPI DWORD WINAPI GetTimeZoneInformation (LPTIME_ZONE_INFORMATION)
GetTokenInformation()
WINBASEAPI BOOL WINAPI GetTokenInformation (HANDLE , TOKEN_INFORMATION_CLASS , PVOID , DWORD , PDWORD)
GetUserNameA()
WINBASEAPI BOOL WINAPI GetUserNameA (LPSTR , PDWORD)
GetUserNameW()
WINBASEAPI BOOL WINAPI GetUserNameW (LPWSTR , PDWORD)
GetVersion()
WINBASEAPI DWORD WINAPI GetVersion (void)
GetVersionExA()
WINBASEAPI BOOL WINAPI GetVersionExA (LPOSVERSIONINFOA)
GetVersionExW()
WINBASEAPI BOOL WINAPI GetVersionExW (LPOSVERSIONINFOW)
GetVolumeInformationA()
WINBASEAPI BOOL WINAPI GetVolumeInformationA (LPCSTR , LPSTR , DWORD , PDWORD , PDWORD , PDWORD , LPSTR , DWORD)
GetVolumeInformationW()
WINBASEAPI BOOL WINAPI GetVolumeInformationW (LPCWSTR , LPWSTR , DWORD , PDWORD , PDWORD , PDWORD , LPWSTR , DWORD)
GetWindowsDirectoryA()
WINBASEAPI UINT WINAPI GetWindowsDirectoryA (LPSTR , UINT)
GetWindowsDirectoryW()
WINBASEAPI UINT WINAPI GetWindowsDirectoryW (LPWSTR , UINT)
GetWindowThreadProcessId()
WINBASEAPI DWORD WINAPI GetWindowThreadProcessId (HWND , PDWORD)
GetWriteWatch()
WINBASEAPI UINT WINAPI GetWriteWatch (DWORD , PVOID , SIZE_T , PVOID * , PULONG_PTR , PULONG)
GlobalAddAtomA()
WINBASEAPI ATOM WINAPI GlobalAddAtomA (LPCSTR)
GlobalAddAtomW()
WINBASEAPI ATOM WINAPI GlobalAddAtomW (LPCWSTR)
GlobalAlloc()
WINBASEAPI HGLOBAL WINAPI GlobalAlloc (UINT , DWORD)
Referenced by Sys_ErrorDialog().
GlobalCompact()
WINBASEAPI SIZE_T WINAPI GlobalCompact (DWORD)
GlobalDeleteAtom()
WINBASEAPI ATOM WINAPI GlobalDeleteAtom (ATOM)
GlobalFindAtomA()
WINBASEAPI ATOM WINAPI GlobalFindAtomA (LPCSTR)
GlobalFindAtomW()
WINBASEAPI ATOM WINAPI GlobalFindAtomW (LPCWSTR)
GlobalFix()
WINBASEAPI VOID WINAPI GlobalFix (HGLOBAL)
GlobalFlags()
WINBASEAPI UINT WINAPI GlobalFlags (HGLOBAL)
GlobalFree()
WINBASEAPI HGLOBAL WINAPI GlobalFree (HGLOBAL)
GlobalGetAtomNameA()
WINBASEAPI UINT WINAPI GlobalGetAtomNameA (ATOM , LPSTR , int)
GlobalGetAtomNameW()
WINBASEAPI UINT WINAPI GlobalGetAtomNameW (ATOM , LPWSTR , int)
GlobalHandle()
WINBASEAPI HGLOBAL WINAPI GlobalHandle (PCVOID)
GlobalLock()
WINBASEAPI LPVOID WINAPI GlobalLock (HGLOBAL)
Referenced by Sys_ErrorDialog(), and Sys_GetClipboardData().
GlobalMemoryStatus()
WINBASEAPI VOID WINAPI GlobalMemoryStatus (LPMEMORYSTATUS)
Referenced by Sys_LowPhysicalMemory().
GlobalReAlloc()
WINBASEAPI HGLOBAL WINAPI GlobalReAlloc (HGLOBAL , DWORD , UINT)
GlobalSize()
WINBASEAPI DWORD WINAPI GlobalSize (HGLOBAL)
Referenced by Sys_GetClipboardData().
GlobalUnfix()
WINBASEAPI VOID WINAPI GlobalUnfix (HGLOBAL)
GlobalUnlock()
WINBASEAPI BOOL WINAPI GlobalUnlock (HGLOBAL)
Referenced by Sys_ErrorDialog(), and Sys_GetClipboardData().
GlobalUnWire()
WINBASEAPI BOOL WINAPI GlobalUnWire (HGLOBAL)
GlobalWire()
WINBASEAPI PVOID WINAPI GlobalWire (HGLOBAL)
HeapAlloc()
WINBASEAPI PVOID WINAPI HeapAlloc (HANDLE , DWORD , DWORD)
HeapCompact()
SIZE_T WINAPI HeapCompact (HANDLE , DWORD)
HeapCreate()
WINBASEAPI HANDLE WINAPI HeapCreate (DWORD , DWORD , DWORD)
HeapDestroy()
WINBASEAPI BOOL WINAPI HeapDestroy (HANDLE)
HeapFree()
WINBASEAPI BOOL WINAPI HeapFree (HANDLE , DWORD , PVOID)
HeapLock()
WINBASEAPI BOOL WINAPI HeapLock (HANDLE)
HeapReAlloc()
WINBASEAPI PVOID WINAPI HeapReAlloc (HANDLE , DWORD , PVOID , DWORD)
HeapSize()
WINBASEAPI DWORD WINAPI HeapSize (HANDLE , DWORD , PCVOID)
HeapUnlock()
WINBASEAPI BOOL WINAPI HeapUnlock (HANDLE)
HeapValidate()
WINBASEAPI BOOL WINAPI HeapValidate (HANDLE , DWORD , PCVOID)
HeapWalk()
WINBASEAPI BOOL WINAPI HeapWalk (HANDLE , LPPROCESS_HEAP_ENTRY)
ImpersonateLoggedOnUser()
WINBASEAPI BOOL WINAPI ImpersonateLoggedOnUser (HANDLE)
ImpersonateNamedPipeClient()
WINBASEAPI BOOL WINAPI ImpersonateNamedPipeClient (HANDLE)
ImpersonateSelf()
WINBASEAPI BOOL WINAPI ImpersonateSelf (SECURITY_IMPERSONATION_LEVEL)
InitAtomTable()
WINBASEAPI BOOL WINAPI InitAtomTable (DWORD)
InitializeAcl()
WINBASEAPI BOOL WINAPI InitializeAcl (PACL , DWORD , DWORD)
InitializeCriticalSection()
WINBASEAPI VOID WINAPI InitializeCriticalSection (LPCRITICAL_SECTION)
InitializeCriticalSectionAndSpinCount()
WINBASEAPI BOOL WINAPI InitializeCriticalSectionAndSpinCount (LPCRITICAL_SECTION , DWORD)
InitializeSecurityDescriptor()
WINBASEAPI BOOL WINAPI InitializeSecurityDescriptor (PSECURITY_DESCRIPTOR , DWORD)
InitializeSid()
WINBASEAPI BOOL WINAPI InitializeSid (PSID , PSID_IDENTIFIER_AUTHORITY , BYTE)
InterlockedCompareExchange()
LONG WINAPI InterlockedCompareExchange (LONG volatile * , LONG , LONG)
InterlockedDecrement()
LONG WINAPI InterlockedDecrement (LONG volatile *)
Referenced by __gthread_mutex_lock(), __gthread_mutex_unlock(), __gthread_recursive_mutex_lock(), and __gthread_recursive_mutex_unlock().
InterlockedExchange()
LONG WINAPI InterlockedExchange (LONG volatile * , LONG)
InterlockedExchangeAdd()
LONG WINAPI InterlockedExchangeAdd (LONG volatile * , LONG)
InterlockedIncrement()
LONG WINAPI InterlockedIncrement (LONG volatile *)
Referenced by __gthread_mutex_lock(), __gthread_once(), and __gthread_recursive_mutex_lock().
IsBadCodePtr()
WINBASEAPI BOOL WINAPI IsBadCodePtr (FARPROC)
IsBadHugeReadPtr()
WINBASEAPI BOOL WINAPI IsBadHugeReadPtr (PCVOID , UINT)
IsBadHugeWritePtr()
WINBASEAPI BOOL WINAPI IsBadHugeWritePtr (PVOID , UINT)
IsBadReadPtr()
WINBASEAPI BOOL WINAPI IsBadReadPtr (PCVOID , UINT)
IsBadStringPtrA()
WINBASEAPI BOOL WINAPI IsBadStringPtrA (LPCSTR , UINT)
IsBadStringPtrW()
WINBASEAPI BOOL WINAPI IsBadStringPtrW (LPCWSTR , UINT)
IsBadWritePtr()
WINBASEAPI BOOL WINAPI IsBadWritePtr (PVOID , UINT)
IsDebuggerPresent()
WINBASEAPI BOOL WINAPI IsDebuggerPresent (void)
IsProcessorFeaturePresent()
WINBASEAPI BOOL WINAPI IsProcessorFeaturePresent (DWORD)
IsSystemResumeAutomatic()
WINBASEAPI BOOL WINAPI IsSystemResumeAutomatic (void)
IsTextUnicode()
WINBASEAPI BOOL WINAPI IsTextUnicode (PCVOID , int , LPINT)
IsValidAcl()
WINBASEAPI BOOL WINAPI IsValidAcl (PACL)
IsValidSecurityDescriptor()
WINBASEAPI BOOL WINAPI IsValidSecurityDescriptor (PSECURITY_DESCRIPTOR)
IsValidSid()
WINBASEAPI BOOL WINAPI IsValidSid (PSID)
LeaveCriticalSection()
WINBASEAPI void WINAPI LeaveCriticalSection (LPCRITICAL_SECTION)
LoadLibraryA()
WINBASEAPI HINSTANCE WINAPI LoadLibraryA (LPCSTR)
LoadLibraryExA()
WINBASEAPI HINSTANCE WINAPI LoadLibraryExA (LPCSTR , HANDLE , DWORD)
LoadLibraryExW()
WINBASEAPI HINSTANCE WINAPI LoadLibraryExW (LPCWSTR , HANDLE , DWORD)
LoadLibraryW()
WINBASEAPI HINSTANCE WINAPI LoadLibraryW (LPCWSTR)
LoadModule()
WINBASEAPI DWORD WINAPI LoadModule (LPCSTR , PVOID)
LoadResource()
WINBASEAPI HGLOBAL WINAPI LoadResource (HINSTANCE , HRSRC)
LocalAlloc()
WINBASEAPI HLOCAL WINAPI LocalAlloc (UINT , SIZE_T)
LocalCompact()
WINBASEAPI SIZE_T WINAPI LocalCompact (UINT)
LocalDiscard()
WINBASEAPI HLOCAL LocalDiscard (HLOCAL)
LocalFileTimeToFileTime()
WINBASEAPI BOOL WINAPI LocalFileTimeToFileTime (CONST FILETIME * , LPFILETIME)
LocalFlags()
WINBASEAPI UINT WINAPI LocalFlags (HLOCAL)
LocalFree()
WINBASEAPI HLOCAL WINAPI LocalFree (HLOCAL)
LocalHandle()
WINBASEAPI HLOCAL WINAPI LocalHandle (LPCVOID)
LocalLock()
WINBASEAPI PVOID WINAPI LocalLock (HLOCAL)
LocalReAlloc()
WINBASEAPI HLOCAL WINAPI LocalReAlloc (HLOCAL , SIZE_T , UINT)
LocalShrink()
WINBASEAPI SIZE_T WINAPI LocalShrink (HLOCAL , UINT)
LocalSize()
WINBASEAPI UINT WINAPI LocalSize (HLOCAL)
LocalUnlock()
WINBASEAPI BOOL WINAPI LocalUnlock (HLOCAL)
LockFile()
WINBASEAPI BOOL WINAPI LockFile (HANDLE , DWORD , DWORD , DWORD , DWORD)
LockFileEx()
WINBASEAPI BOOL WINAPI LockFileEx (HANDLE , DWORD , DWORD , DWORD , DWORD , LPOVERLAPPED)
LockResource()
WINBASEAPI PVOID WINAPI LockResource (HGLOBAL)
LogonUserA()
WINBASEAPI BOOL WINAPI LogonUserA (LPSTR , LPSTR , LPSTR , DWORD , DWORD , PHANDLE)
LogonUserW()
WINBASEAPI BOOL WINAPI LogonUserW (LPWSTR , LPWSTR , LPWSTR , DWORD , DWORD , PHANDLE)
LookupAccountNameA()
WINBASEAPI BOOL WINAPI LookupAccountNameA (LPCSTR , LPCSTR , PSID , PDWORD , LPSTR , PDWORD , PSID_NAME_USE)
LookupAccountNameW()
WINBASEAPI BOOL WINAPI LookupAccountNameW (LPCWSTR , LPCWSTR , PSID , PDWORD , LPWSTR , PDWORD , PSID_NAME_USE)
LookupAccountSidA()
WINBASEAPI BOOL WINAPI LookupAccountSidA (LPCSTR , PSID , LPSTR , PDWORD , LPSTR , PDWORD , PSID_NAME_USE)
LookupAccountSidW()
WINBASEAPI BOOL WINAPI LookupAccountSidW (LPCWSTR , PSID , LPWSTR , PDWORD , LPWSTR , PDWORD , PSID_NAME_USE)
LookupPrivilegeDisplayNameA()
WINBASEAPI BOOL WINAPI LookupPrivilegeDisplayNameA (LPCSTR , LPCSTR , LPSTR , PDWORD , PDWORD)
LookupPrivilegeDisplayNameW()
WINBASEAPI BOOL WINAPI LookupPrivilegeDisplayNameW (LPCWSTR , LPCWSTR , LPWSTR , PDWORD , PDWORD)
LookupPrivilegeNameA()
WINBASEAPI BOOL WINAPI LookupPrivilegeNameA (LPCSTR , PLUID , LPSTR , PDWORD)
LookupPrivilegeNameW()
WINBASEAPI BOOL WINAPI LookupPrivilegeNameW (LPCWSTR , PLUID , LPWSTR , PDWORD)
LookupPrivilegeValueA()
WINBASEAPI BOOL WINAPI LookupPrivilegeValueA (LPCSTR , LPCSTR , PLUID)
LookupPrivilegeValueW()
WINBASEAPI BOOL WINAPI LookupPrivilegeValueW (LPCWSTR , LPCWSTR , PLUID)
lstrcatA()
WINBASEAPI LPSTR WINAPI lstrcatA (LPSTR , LPCSTR)
lstrcatW()
WINBASEAPI LPWSTR WINAPI lstrcatW (LPWSTR , LPCWSTR)
lstrcmpA()
WINBASEAPI int WINAPI lstrcmpA (LPCSTR , LPCSTR)
lstrcmpiA()
WINBASEAPI int WINAPI lstrcmpiA (LPCSTR , LPCSTR)
lstrcmpiW()
WINBASEAPI int WINAPI lstrcmpiW (LPCWSTR , LPCWSTR)
lstrcmpW()
WINBASEAPI int WINAPI lstrcmpW (LPCWSTR , LPCWSTR)
lstrcpyA()
WINBASEAPI LPSTR WINAPI lstrcpyA (LPSTR , LPCSTR)
lstrcpynA()
WINBASEAPI LPSTR WINAPI lstrcpynA (LPSTR , LPCSTR , int)
lstrcpynW()
WINBASEAPI LPWSTR WINAPI lstrcpynW (LPWSTR , LPCWSTR , int)
lstrcpyW()
WINBASEAPI LPWSTR WINAPI lstrcpyW (LPWSTR , LPCWSTR)
lstrlenA()
WINBASEAPI int WINAPI lstrlenA (LPCSTR)
lstrlenW()
WINBASEAPI int WINAPI lstrlenW (LPCWSTR)
MakeAbsoluteSD()
WINBASEAPI BOOL WINAPI MakeAbsoluteSD (PSECURITY_DESCRIPTOR , PSECURITY_DESCRIPTOR , PDWORD , PACL , PDWORD , PACL , PDWORD , PSID , PDWORD , PSID , PDWORD)
MakeSelfRelativeSD()
WINBASEAPI BOOL WINAPI MakeSelfRelativeSD (PSECURITY_DESCRIPTOR , PSECURITY_DESCRIPTOR , PDWORD)
MapGenericMask()
WINBASEAPI VOID WINAPI MapGenericMask (PDWORD , PGENERIC_MAPPING)
MapViewOfFile()
WINBASEAPI PVOID WINAPI MapViewOfFile (HANDLE , DWORD , DWORD , DWORD , DWORD)
Referenced by mumble_link().
MapViewOfFileEx()
WINBASEAPI PVOID WINAPI MapViewOfFileEx (HANDLE , DWORD , DWORD , DWORD , DWORD , PVOID)
MoveFileA()
WINBASEAPI BOOL WINAPI MoveFileA (LPCSTR , LPCSTR)
MoveFileExA()
WINBASEAPI BOOL WINAPI MoveFileExA (LPCSTR , LPCSTR , DWORD)
MoveFileExW()
WINBASEAPI BOOL WINAPI MoveFileExW (LPCWSTR , LPCWSTR , DWORD)
MoveFileW()
WINBASEAPI BOOL WINAPI MoveFileW (LPCWSTR , LPCWSTR)
MulDiv()
WINBASEAPI int WINAPI MulDiv (int , int , int)
NotifyChangeEventLog()
WINBASEAPI BOOL WINAPI NotifyChangeEventLog (HANDLE , HANDLE)
ObjectCloseAuditAlarmA()
WINBASEAPI BOOL WINAPI ObjectCloseAuditAlarmA (LPCSTR , PVOID , BOOL)
ObjectCloseAuditAlarmW()
WINBASEAPI BOOL WINAPI ObjectCloseAuditAlarmW (LPCWSTR , PVOID , BOOL)
ObjectDeleteAuditAlarmA()
WINBASEAPI BOOL WINAPI ObjectDeleteAuditAlarmA (LPCSTR , PVOID , BOOL)
ObjectDeleteAuditAlarmW()
WINBASEAPI BOOL WINAPI ObjectDeleteAuditAlarmW (LPCWSTR , PVOID , BOOL)
ObjectOpenAuditAlarmA()
WINBASEAPI BOOL WINAPI ObjectOpenAuditAlarmA (LPCSTR , PVOID , LPSTR , LPSTR , PSECURITY_DESCRIPTOR , HANDLE , DWORD , DWORD , PPRIVILEGE_SET , BOOL , BOOL , PBOOL)
ObjectOpenAuditAlarmW()
WINBASEAPI BOOL WINAPI ObjectOpenAuditAlarmW (LPCWSTR , PVOID , LPWSTR , LPWSTR , PSECURITY_DESCRIPTOR , HANDLE , DWORD , DWORD , PPRIVILEGE_SET , BOOL , BOOL , PBOOL)
ObjectPrivilegeAuditAlarmA()
WINBASEAPI BOOL WINAPI ObjectPrivilegeAuditAlarmA (LPCSTR , PVOID , HANDLE , DWORD , PPRIVILEGE_SET , BOOL)
ObjectPrivilegeAuditAlarmW()
WINBASEAPI BOOL WINAPI ObjectPrivilegeAuditAlarmW (LPCWSTR , PVOID , HANDLE , DWORD , PPRIVILEGE_SET , BOOL)
OpenBackupEventLogA()
WINBASEAPI HANDLE WINAPI OpenBackupEventLogA (LPCSTR , LPCSTR)
OpenBackupEventLogW()
WINBASEAPI HANDLE WINAPI OpenBackupEventLogW (LPCWSTR , LPCWSTR)
OpenEventA()
WINBASEAPI HANDLE WINAPI OpenEventA (DWORD , BOOL , LPCSTR)
OpenEventLogA()
WINBASEAPI HANDLE WINAPI OpenEventLogA (LPCSTR , LPCSTR)
OpenEventLogW()
WINBASEAPI HANDLE WINAPI OpenEventLogW (LPCWSTR , LPCWSTR)
OpenEventW()
WINBASEAPI HANDLE WINAPI OpenEventW (DWORD , BOOL , LPCWSTR)
OpenFile()
WINBASEAPI HFILE WINAPI OpenFile (LPCSTR , LPOFSTRUCT , UINT)
OpenFileMappingA()
WINBASEAPI HANDLE WINAPI OpenFileMappingA (DWORD , BOOL , LPCSTR)
OpenFileMappingW()
WINBASEAPI HANDLE WINAPI OpenFileMappingW (DWORD , BOOL , LPCWSTR)
Referenced by mumble_link().
OpenMutexA()
WINBASEAPI HANDLE WINAPI OpenMutexA (DWORD , BOOL , LPCSTR)
OpenMutexW()
WINBASEAPI HANDLE WINAPI OpenMutexW (DWORD , BOOL , LPCWSTR)
OpenProcess()
WINBASEAPI HANDLE WINAPI OpenProcess (DWORD , BOOL , DWORD)
OpenProcessToken()
WINBASEAPI BOOL WINAPI OpenProcessToken (HANDLE , DWORD , PHANDLE)
OpenSemaphoreA()
WINBASEAPI HANDLE WINAPI OpenSemaphoreA (DWORD , BOOL , LPCSTR)
OpenSemaphoreW()
WINBASEAPI HANDLE WINAPI OpenSemaphoreW (DWORD , BOOL , LPCWSTR)
OpenThreadToken()
WINBASEAPI BOOL WINAPI OpenThreadToken (HANDLE , DWORD , BOOL , PHANDLE)
OpenWaitableTimerA()
WINBASEAPI HANDLE WINAPI OpenWaitableTimerA (DWORD , BOOL , LPCSTR)
OpenWaitableTimerW()
WINBASEAPI HANDLE WINAPI OpenWaitableTimerW (DWORD , BOOL , LPCWSTR)
OutputDebugStringA()
WINBASEAPI void WINAPI OutputDebugStringA (LPCSTR)
OutputDebugStringW()
WINBASEAPI void WINAPI OutputDebugStringW (LPCWSTR)
PeekNamedPipe()
WINBASEAPI BOOL WINAPI PeekNamedPipe (HANDLE , PVOID , DWORD , PDWORD , PDWORD , PDWORD)
PostQueuedCompletionStatus()
WINBASEAPI BOOL WINAPI PostQueuedCompletionStatus (HANDLE , DWORD , ULONG_PTR , LPOVERLAPPED)
PrepareTape()
WINBASEAPI DWORD WINAPI PrepareTape (HANDLE , DWORD , BOOL)
PrivilegeCheck()
WINBASEAPI BOOL WINAPI PrivilegeCheck (HANDLE , PPRIVILEGE_SET , PBOOL)
PrivilegedServiceAuditAlarmA()
WINBASEAPI BOOL WINAPI PrivilegedServiceAuditAlarmA (LPCSTR , LPCSTR , HANDLE , PPRIVILEGE_SET , BOOL)
PrivilegedServiceAuditAlarmW()
WINBASEAPI BOOL WINAPI PrivilegedServiceAuditAlarmW (LPCWSTR , LPCWSTR , HANDLE , PPRIVILEGE_SET , BOOL)
PulseEvent()
WINBASEAPI BOOL WINAPI PulseEvent (HANDLE)
PurgeComm()
WINBASEAPI BOOL WINAPI PurgeComm (HANDLE , DWORD)
QueryDosDeviceA()
WINBASEAPI DWORD WINAPI QueryDosDeviceA (LPCSTR , LPSTR , DWORD)
QueryDosDeviceW()
WINBASEAPI DWORD WINAPI QueryDosDeviceW (LPCWSTR , LPWSTR , DWORD)
QueryPerformanceCounter()
WINBASEAPI BOOL WINAPI QueryPerformanceCounter (PLARGE_INTEGER)
QueryPerformanceFrequency()
WINBASEAPI BOOL WINAPI QueryPerformanceFrequency (PLARGE_INTEGER)
QueueUserAPC()
WINBASEAPI DWORD WINAPI QueueUserAPC (PAPCFUNC , HANDLE , ULONG_PTR)
RaiseException()
WINBASEAPI void WINAPI RaiseException (DWORD , DWORD , DWORD , const DWORD *)
ReadDirectoryChangesW()
WINBASEAPI BOOL WINAPI ReadDirectoryChangesW (HANDLE , PVOID , DWORD , BOOL , DWORD , PDWORD , LPOVERLAPPED , LPOVERLAPPED_COMPLETION_ROUTINE)
ReadEventLogA()
WINBASEAPI BOOL WINAPI ReadEventLogA (HANDLE , DWORD , DWORD , PVOID , DWORD , DWORD * , DWORD *)
ReadEventLogW()
WINBASEAPI BOOL WINAPI ReadEventLogW (HANDLE , DWORD , DWORD , PVOID , DWORD , DWORD * , DWORD *)
ReadFile()
WINBASEAPI BOOL WINAPI ReadFile (HANDLE , PVOID , DWORD , PDWORD , LPOVERLAPPED)
ReadFileEx()
WINBASEAPI BOOL WINAPI ReadFileEx (HANDLE , PVOID , DWORD , LPOVERLAPPED , LPOVERLAPPED_COMPLETION_ROUTINE)
ReadFileScatter()
WINBASEAPI BOOL WINAPI ReadFileScatter (HANDLE , FILE_SEGMENT_ELEMENT * , DWORD , LPDWORD , LPOVERLAPPED)
ReadProcessMemory()
WINBASEAPI BOOL WINAPI ReadProcessMemory (HANDLE , PCVOID , PVOID , DWORD , PDWORD)
RegisterEventSourceA()
WINBASEAPI HANDLE WINAPI RegisterEventSourceA (LPCSTR , LPCSTR)
RegisterEventSourceW()
WINBASEAPI HANDLE WINAPI RegisterEventSourceW (LPCWSTR , LPCWSTR)
ReleaseMutex()
WINBASEAPI BOOL WINAPI ReleaseMutex (HANDLE)
ReleaseSemaphore()
WINBASEAPI BOOL WINAPI ReleaseSemaphore (HANDLE , LONG , LPLONG)
Referenced by __gthread_mutex_unlock(), and __gthread_recursive_mutex_unlock().
RemoveDirectoryA()
WINBASEAPI BOOL WINAPI RemoveDirectoryA (LPCSTR)
RemoveDirectoryW()
WINBASEAPI BOOL WINAPI RemoveDirectoryW (LPCWSTR)
ReportEventA()
WINBASEAPI BOOL WINAPI ReportEventA (HANDLE , WORD , WORD , DWORD , PSID , WORD , DWORD , LPCSTR * , PVOID)
ReportEventW()
WINBASEAPI BOOL WINAPI ReportEventW (HANDLE , WORD , WORD , DWORD , PSID , WORD , DWORD , LPCWSTR * , PVOID)
ResetEvent()
WINBASEAPI BOOL WINAPI ResetEvent (HANDLE)
ResetWriteWatch()
WINBASEAPI UINT WINAPI ResetWriteWatch (LPVOID , SIZE_T)
ResumeThread()
WINBASEAPI DWORD WINAPI ResumeThread (HANDLE)
RevertToSelf()
WINBASEAPI BOOL WINAPI RevertToSelf (void)
Referenced by DECLARE_INTERFACE_().
SearchPathA()
WINBASEAPI DWORD WINAPI SearchPathA (LPCSTR , LPCSTR , LPCSTR , DWORD , LPSTR , LPSTR *)
SearchPathW()
WINBASEAPI DWORD WINAPI SearchPathW (LPCWSTR , LPCWSTR , LPCWSTR , DWORD , LPWSTR , LPWSTR *)
SetAclInformation()
WINBASEAPI BOOL WINAPI SetAclInformation (PACL , PVOID , DWORD , ACL_INFORMATION_CLASS)
SetCommBreak()
WINBASEAPI BOOL WINAPI SetCommBreak (HANDLE)
SetCommConfig()
WINBASEAPI BOOL WINAPI SetCommConfig (HANDLE , LPCOMMCONFIG , DWORD)
SetCommMask()
WINBASEAPI BOOL WINAPI SetCommMask (HANDLE , DWORD)
SetCommState()
WINBASEAPI BOOL WINAPI SetCommState (HANDLE , LPDCB)
SetCommTimeouts()
WINBASEAPI BOOL WINAPI SetCommTimeouts (HANDLE , LPCOMMTIMEOUTS)
SetComputerNameA()
WINBASEAPI BOOL WINAPI SetComputerNameA (LPCSTR)
SetComputerNameW()
WINBASEAPI BOOL WINAPI SetComputerNameW (LPCWSTR)
SetCriticalSectionSpinCount()
WINBASEAPI DWORD WINAPI SetCriticalSectionSpinCount (LPCRITICAL_SECTION , DWORD)
SetCurrentDirectoryA()
WINBASEAPI BOOL WINAPI SetCurrentDirectoryA (LPCSTR)
SetCurrentDirectoryW()
WINBASEAPI BOOL WINAPI SetCurrentDirectoryW (LPCWSTR)
SetDefaultCommConfigA()
WINBASEAPI BOOL WINAPI SetDefaultCommConfigA (LPCSTR , LPCOMMCONFIG , DWORD)
SetDefaultCommConfigW()
WINBASEAPI BOOL WINAPI SetDefaultCommConfigW (LPCWSTR , LPCOMMCONFIG , DWORD)
SetEndOfFile()
WINBASEAPI BOOL WINAPI SetEndOfFile (HANDLE)
SetEnvironmentVariableA()
WINBASEAPI BOOL WINAPI SetEnvironmentVariableA (LPCSTR , LPCSTR)
SetEnvironmentVariableW()
WINBASEAPI BOOL WINAPI SetEnvironmentVariableW (LPCWSTR , LPCWSTR)
SetErrorMode()
WINBASEAPI UINT WINAPI SetErrorMode (UINT)
SetEvent()
WINBASEAPI BOOL WINAPI SetEvent (HANDLE)
SetFileApisToANSI()
WINBASEAPI VOID WINAPI SetFileApisToANSI (void)
SetFileApisToOEM()
WINBASEAPI VOID WINAPI SetFileApisToOEM (void)
SetFileAttributesA()
WINBASEAPI BOOL WINAPI SetFileAttributesA (LPCSTR , DWORD)
SetFileAttributesW()
WINBASEAPI BOOL WINAPI SetFileAttributesW (LPCWSTR , DWORD)
SetFilePointer()
WINBASEAPI DWORD WINAPI SetFilePointer (HANDLE , LONG , PLONG , DWORD)
SetFilePointerEx()
WINBASEAPI BOOL WINAPI SetFilePointerEx (HANDLE , LARGE_INTEGER , PLARGE_INTEGER , DWORD)
SetFileSecurityA()
WINBASEAPI BOOL WINAPI SetFileSecurityA (LPCSTR , SECURITY_INFORMATION , PSECURITY_DESCRIPTOR)
SetFileSecurityW()
WINBASEAPI BOOL WINAPI SetFileSecurityW (LPCWSTR , SECURITY_INFORMATION , PSECURITY_DESCRIPTOR)
SetFileTime()
WINBASEAPI BOOL WINAPI SetFileTime (HANDLE , const FILETIME * , const FILETIME * , const FILETIME *)
SetHandleCount()
WINBASEAPI UINT WINAPI SetHandleCount (UINT)
SetHandleInformation()
WINBASEAPI BOOL WINAPI SetHandleInformation (HANDLE , DWORD , DWORD)
SetKernelObjectSecurity()
WINBASEAPI BOOL WINAPI SetKernelObjectSecurity (HANDLE , SECURITY_INFORMATION , PSECURITY_DESCRIPTOR)
SetLastError()
WINBASEAPI void WINAPI SetLastError (DWORD)
Referenced by __gthread_getspecific().
SetLastErrorEx()
WINBASEAPI void WINAPI SetLastErrorEx (DWORD , DWORD)
SetLocalTime()
WINBASEAPI BOOL WINAPI SetLocalTime (const SYSTEMTIME *)
SetMailslotInfo()
WINBASEAPI BOOL WINAPI SetMailslotInfo (HANDLE , DWORD)
SetNamedPipeHandleState()
WINBASEAPI BOOL WINAPI SetNamedPipeHandleState (HANDLE , PDWORD , PDWORD , PDWORD)
SetPriorityClass()
WINBASEAPI BOOL WINAPI SetPriorityClass (HANDLE , DWORD)
SetPrivateObjectSecurity()
WINBASEAPI BOOL WINAPI SetPrivateObjectSecurity (SECURITY_INFORMATION , PSECURITY_DESCRIPTOR , PSECURITY_DESCRIPTOR * , PGENERIC_MAPPING , HANDLE)
SetProcessAffinityMask()
WINBASEAPI BOOL WINAPI SetProcessAffinityMask (HANDLE , DWORD)
SetProcessPriorityBoost()
WINBASEAPI BOOL WINAPI SetProcessPriorityBoost (HANDLE , BOOL)
SetProcessShutdownParameters()
WINBASEAPI BOOL WINAPI SetProcessShutdownParameters (DWORD , DWORD)
SetProcessWorkingSetSize()
WINBASEAPI BOOL WINAPI SetProcessWorkingSetSize (HANDLE , SIZE_T , SIZE_T)
SetSecurityDescriptorControl()
WINBASEAPI BOOL WINAPI SetSecurityDescriptorControl (PSECURITY_DESCRIPTOR , SECURITY_DESCRIPTOR_CONTROL , SECURITY_DESCRIPTOR_CONTROL)
SetSecurityDescriptorDacl()
WINBASEAPI BOOL WINAPI SetSecurityDescriptorDacl (PSECURITY_DESCRIPTOR , BOOL , PACL , BOOL)
SetSecurityDescriptorGroup()
WINBASEAPI BOOL WINAPI SetSecurityDescriptorGroup (PSECURITY_DESCRIPTOR , PSID , BOOL)
SetSecurityDescriptorOwner()
WINBASEAPI BOOL WINAPI SetSecurityDescriptorOwner (PSECURITY_DESCRIPTOR , PSID , BOOL)
SetSecurityDescriptorSacl()
WINBASEAPI BOOL WINAPI SetSecurityDescriptorSacl (PSECURITY_DESCRIPTOR , BOOL , PACL , BOOL)
SetStdHandle()
WINBASEAPI BOOL WINAPI SetStdHandle (DWORD , HANDLE)
SetSystemPowerState()
WINBASEAPI BOOL WINAPI SetSystemPowerState (BOOL , BOOL)
SetSystemTime()
WINBASEAPI BOOL WINAPI SetSystemTime (const SYSTEMTIME *)
SetSystemTimeAdjustment()
WINBASEAPI BOOL WINAPI SetSystemTimeAdjustment (DWORD , BOOL)
SetTapeParameters()
WINBASEAPI DWORD WINAPI SetTapeParameters (HANDLE , DWORD , PVOID)
SetTapePosition()
WINBASEAPI DWORD WINAPI SetTapePosition (HANDLE , DWORD , DWORD , DWORD , DWORD , BOOL)
SetThreadAffinityMask()
WINBASEAPI DWORD WINAPI SetThreadAffinityMask (HANDLE , DWORD)
SetThreadContext()
WINBASEAPI BOOL WINAPI SetThreadContext (HANDLE , const CONTEXT *)
SetThreadIdealProcessor()
WINBASEAPI DWORD WINAPI SetThreadIdealProcessor (HANDLE , DWORD)
SetThreadPriority()
WINBASEAPI BOOL WINAPI SetThreadPriority (HANDLE , int)
SetThreadPriorityBoost()
WINBASEAPI BOOL WINAPI SetThreadPriorityBoost (HANDLE , BOOL)
SetThreadToken()
WINBASEAPI BOOL WINAPI SetThreadToken (PHANDLE , HANDLE)
SetTimeZoneInformation()
WINBASEAPI BOOL WINAPI SetTimeZoneInformation (const TIME_ZONE_INFORMATION *)
SetTokenInformation()
WINBASEAPI BOOL WINAPI SetTokenInformation (HANDLE , TOKEN_INFORMATION_CLASS , PVOID , DWORD)
SetUnhandledExceptionFilter()
WINBASEAPI LPTOP_LEVEL_EXCEPTION_FILTER WINAPI SetUnhandledExceptionFilter (LPTOP_LEVEL_EXCEPTION_FILTER)
SetupComm()
WINBASEAPI BOOL WINAPI SetupComm (HANDLE , DWORD , DWORD)
SetVolumeLabelA()
WINBASEAPI BOOL WINAPI SetVolumeLabelA (LPCSTR , LPCSTR)
SetVolumeLabelW()
WINBASEAPI BOOL WINAPI SetVolumeLabelW (LPCWSTR , LPCWSTR)
SetWaitableTimer()
WINBASEAPI BOOL WINAPI SetWaitableTimer (HANDLE , const LARGE_INTEGER * , LONG , PTIMERAPCROUTINE , PVOID , BOOL)
SignalObjectAndWait()
WINBASEAPI DWORD WINAPI SignalObjectAndWait (HANDLE , HANDLE , DWORD , BOOL)
SizeofResource()
WINBASEAPI DWORD WINAPI SizeofResource (HINSTANCE , HRSRC)
Sleep()
WINBASEAPI void WINAPI Sleep (DWORD)
Referenced by __gthread_once(), and Sys_Sleep().
SleepEx()
WINBASEAPI DWORD WINAPI SleepEx (DWORD , BOOL)
Referenced by NET_Sleep().
SuspendThread()
WINBASEAPI DWORD WINAPI SuspendThread (HANDLE)
SwitchToFiber()
WINBASEAPI void WINAPI SwitchToFiber (PVOID)
SwitchToThread()
WINBASEAPI BOOL WINAPI SwitchToThread (void)
SystemTimeToFileTime()
WINBASEAPI BOOL WINAPI SystemTimeToFileTime (const SYSTEMTIME * , LPFILETIME)
SystemTimeToTzSpecificLocalTime()
WINBASEAPI BOOL WINAPI SystemTimeToTzSpecificLocalTime (LPTIME_ZONE_INFORMATION , LPSYSTEMTIME , LPSYSTEMTIME)
TerminateProcess()
WINBASEAPI BOOL WINAPI TerminateProcess (HANDLE , UINT)
TerminateThread()
WINBASEAPI BOOL WINAPI TerminateThread (HANDLE , DWORD)
TlsAlloc()
WINBASEAPI DWORD WINAPI TlsAlloc (VOID)
Referenced by __gthread_key_create().
TlsFree()
WINBASEAPI BOOL WINAPI TlsFree (DWORD)
Referenced by __gthread_key_delete().
TlsGetValue()
WINBASEAPI PVOID WINAPI TlsGetValue (DWORD)
Referenced by __gthread_getspecific().
TlsSetValue()
WINBASEAPI BOOL WINAPI TlsSetValue (DWORD , PVOID)
Referenced by __gthread_setspecific().
TransactNamedPipe()
WINBASEAPI BOOL WINAPI TransactNamedPipe (HANDLE , PVOID , DWORD , PVOID , DWORD , PDWORD , LPOVERLAPPED)
TransmitCommChar()
WINBASEAPI BOOL WINAPI TransmitCommChar (HANDLE , char)
TryEnterCriticalSection()
WINBASEAPI BOOL WINAPI TryEnterCriticalSection (LPCRITICAL_SECTION)
UnhandledExceptionFilter()
WINBASEAPI LONG WINAPI UnhandledExceptionFilter (LPEXCEPTION_POINTERS)
UnlockFile()
WINBASEAPI BOOL WINAPI UnlockFile (HANDLE , DWORD , DWORD , DWORD , DWORD)
UnlockFileEx()
WINBASEAPI BOOL WINAPI UnlockFileEx (HANDLE , DWORD , DWORD , DWORD , LPOVERLAPPED)
UnmapViewOfFile()
WINBASEAPI BOOL WINAPI UnmapViewOfFile (LPCVOID)
Referenced by mumble_unlink().
UpdateResourceA()
WINBASEAPI BOOL WINAPI UpdateResourceA (HANDLE , LPCSTR , LPCSTR , WORD , PVOID , DWORD)
UpdateResourceW()
WINBASEAPI BOOL WINAPI UpdateResourceW (HANDLE , LPCWSTR , LPCWSTR , WORD , PVOID , DWORD)
VerifyVersionInfoA()
WINBASEAPI BOOL WINAPI VerifyVersionInfoA (LPOSVERSIONINFOEXA , DWORD , DWORDLONG)
VerifyVersionInfoW()
WINBASEAPI BOOL WINAPI VerifyVersionInfoW (LPOSVERSIONINFOEXW , DWORD , DWORDLONG)
VirtualAlloc()
WINBASEAPI PVOID WINAPI VirtualAlloc (PVOID , DWORD , DWORD , DWORD)
Referenced by VM_Compile().
VirtualAllocEx()
WINBASEAPI PVOID WINAPI VirtualAllocEx (HANDLE , PVOID , DWORD , DWORD , DWORD)
VirtualFree()
WINBASEAPI BOOL WINAPI VirtualFree (PVOID , DWORD , DWORD)
Referenced by VM_Destroy_Compiled().
VirtualFreeEx()
WINBASEAPI BOOL WINAPI VirtualFreeEx (HANDLE , PVOID , DWORD , DWORD)
VirtualLock()
WINBASEAPI BOOL WINAPI VirtualLock (PVOID , DWORD)
VirtualProtect()
WINBASEAPI BOOL WINAPI VirtualProtect (PVOID , DWORD , DWORD , PDWORD)
Referenced by VM_Compile().
VirtualProtectEx()
WINBASEAPI BOOL WINAPI VirtualProtectEx (HANDLE , PVOID , DWORD , DWORD , PDWORD)
VirtualQuery()
WINBASEAPI DWORD WINAPI VirtualQuery (LPCVOID , PMEMORY_BASIC_INFORMATION , DWORD)
VirtualQueryEx()
WINBASEAPI DWORD WINAPI VirtualQueryEx (HANDLE , LPCVOID , PMEMORY_BASIC_INFORMATION , DWORD)
VirtualUnlock()
WINBASEAPI BOOL WINAPI VirtualUnlock (PVOID , DWORD)
WaitCommEvent()
WINBASEAPI BOOL WINAPI WaitCommEvent (HANDLE , PDWORD , LPOVERLAPPED)
WaitForDebugEvent()
WINBASEAPI BOOL WINAPI WaitForDebugEvent (LPDEBUG_EVENT , DWORD)
WaitForMultipleObjects()
WINBASEAPI DWORD WINAPI WaitForMultipleObjects (DWORD , const HANDLE * , BOOL , DWORD)
WaitForMultipleObjectsEx()
WINBASEAPI DWORD WINAPI WaitForMultipleObjectsEx (DWORD , const HANDLE * , BOOL , DWORD , BOOL)
WaitForSingleObject()
WINBASEAPI DWORD WINAPI WaitForSingleObject (HANDLE , DWORD)
Referenced by __gthread_mutex_lock(), __gthread_recursive_mutex_lock(), and Sys_Sleep().
WaitForSingleObjectEx()
WINBASEAPI DWORD WINAPI WaitForSingleObjectEx (HANDLE , DWORD , BOOL)
WaitNamedPipeA()
WINBASEAPI BOOL WINAPI WaitNamedPipeA (LPCSTR , DWORD)
WaitNamedPipeW()
WINBASEAPI BOOL WINAPI WaitNamedPipeW (LPCWSTR , DWORD)
WinLoadTrustProvider()
WINBASEAPI BOOL WINAPI WinLoadTrustProvider (GUID *)
WinMain()
int APIENTRY WinMain (HINSTANCE , HINSTANCE , LPSTR , int)
WriteFile()
WINBASEAPI BOOL WINAPI WriteFile (HANDLE , PCVOID , DWORD , PDWORD , LPOVERLAPPED)
WriteFileEx()
WINBASEAPI BOOL WINAPI WriteFileEx (HANDLE , PCVOID , DWORD , LPOVERLAPPED , LPOVERLAPPED_COMPLETION_ROUTINE)
WriteFileGather()
WINBASEAPI BOOL WINAPI WriteFileGather (HANDLE , FILE_SEGMENT_ELEMENT * , DWORD , LPDWORD , LPOVERLAPPED)
WritePrivateProfileSectionA()
WINBASEAPI BOOL WINAPI WritePrivateProfileSectionA (LPCSTR , LPCSTR , LPCSTR)
WritePrivateProfileSectionW()
WINBASEAPI BOOL WINAPI WritePrivateProfileSectionW (LPCWSTR , LPCWSTR , LPCWSTR)
WritePrivateProfileStringA()
WINBASEAPI BOOL WINAPI WritePrivateProfileStringA (LPCSTR , LPCSTR , LPCSTR , LPCSTR)
WritePrivateProfileStringW()
WINBASEAPI BOOL WINAPI WritePrivateProfileStringW (LPCWSTR , LPCWSTR , LPCWSTR , LPCWSTR)
WritePrivateProfileStructA()
WINBASEAPI BOOL WINAPI WritePrivateProfileStructA (LPCSTR , LPCSTR , LPVOID , UINT , LPCSTR)
WritePrivateProfileStructW()
WINBASEAPI BOOL WINAPI WritePrivateProfileStructW (LPCWSTR , LPCWSTR , LPVOID , UINT , LPCWSTR)
WriteProcessMemory()
WINBASEAPI BOOL WINAPI WriteProcessMemory (HANDLE , LPVOID , LPCVOID , SIZE_T , SIZE_T *)
WriteProfileSectionA()
WINBASEAPI BOOL WINAPI WriteProfileSectionA (LPCSTR , LPCSTR)
WriteProfileSectionW()
WINBASEAPI BOOL WINAPI WriteProfileSectionW (LPCWSTR , LPCWSTR)
WriteProfileStringA()
WINBASEAPI BOOL WINAPI WriteProfileStringA (LPCSTR , LPCSTR , LPCSTR)
WriteProfileStringW()
WINBASEAPI BOOL WINAPI WriteProfileStringW (LPCWSTR , LPCWSTR , LPCWSTR)
WriteTapemark()
WINBASEAPI DWORD WINAPI WriteTapemark (HANDLE , DWORD , DWORD , BOOL)
wWinMain()
int APIENTRY wWinMain (HINSTANCE , HINSTANCE , LPWSTR , int)