ZEQ2-Lite: Source/Game/CGame/cg_frameHist.c File Reference
cg_frameHist.c File Reference
#include "cg_local.h"
Data Structures
struct cg_frameHist_t
Functions
qboolean CG_FrameHist_HadAura (int num)
qboolean CG_FrameHist_HasAura (int num)
void CG_FrameHist_Init (void)
qboolean CG_FrameHist_IsInPVS (int num)
int CG_FrameHist_IsWeaponNr (int num)
int CG_FrameHist_IsWeaponState (int num)
void CG_FrameHist_NextFrame (void)
void CG_FrameHist_SetAura (int num)
void CG_FrameHist_SetPVS (int num)
qboolean CG_FrameHist_WasInPVS (int num)
int CG_FrameHist_WasWeaponNr (int num)
int CG_FrameHist_WasWeaponState (int num)
Variables
static cg_frameHist_t frHist_lastFrame [MAX_GENTITIES]
static cg_frameHist_t frHist_thisFrame [MAX_GENTITIES]
Function Documentation
CG_FrameHist_HadAura()
qboolean CG_FrameHist_HadAura (int num)
Definition at line 71 of file cg_frameHist.c.
{
     return frHist_lastFrame[num].hasAura;
 }
References frHist_lastFrame, and cg_frameHist_t::hasAura.
Referenced by CG_Aura_AddDebris(), and CG_Aura_AddParticleSystem().
CG_FrameHist_HasAura()
qboolean CG_FrameHist_HasAura (int num)
Definition at line 67 of file cg_frameHist.c.
{
     return frHist_thisFrame[num].hasAura;
 }
References frHist_thisFrame, and cg_frameHist_t::hasAura.
Referenced by PSys_UpdateOrientation().
CG_FrameHist_Init()
void CG_FrameHist_Init (void)
Definition at line 15 of file cg_frameHist.c.
{
     memset( frHist_thisFrame, 0, sizeof(frHist_thisFrame));
     memset( frHist_lastFrame, 0, sizeof(frHist_lastFrame));
 }
References frHist_lastFrame, and frHist_thisFrame.
Referenced by CG_Init(), and CG_MapRestart().
CG_FrameHist_IsInPVS()
qboolean CG_FrameHist_IsInPVS (int num)
Definition at line 53 of file cg_frameHist.c.
{
     return frHist_thisFrame[num].inPVS;
 }
References frHist_thisFrame, and cg_frameHist_t::inPVS.
Referenced by PSys_UpdateOrientation().
CG_FrameHist_IsWeaponNr()
int CG_FrameHist_IsWeaponNr (int num)
Definition at line 87 of file cg_frameHist.c.
{
     return frHist_thisFrame[num].weapNr;
 }
References frHist_thisFrame, and cg_frameHist_t::weapNr.
Referenced by CG_AddPlayerWeapon(), and PSys_UpdateOrientation().
CG_FrameHist_IsWeaponState()
int CG_FrameHist_IsWeaponState (int num)
Definition at line 77 of file cg_frameHist.c.
{
     return frHist_thisFrame[num].weaponState;
 }
References frHist_thisFrame, and cg_frameHist_t::weaponState.
Referenced by CG_AddPlayerWeapon(), and PSys_UpdateOrientation().
CG_FrameHist_NextFrame()
void CG_FrameHist_NextFrame (void)
Definition at line 20 of file cg_frameHist.c.
{
     int i;
     for( i = 0 ; i < MAX_GENTITIES ; i++) {
         frHist_lastFrame[i].inPVS = frHist_thisFrame[i].inPVS;
         frHist_thisFrame[i].inPVS = qfalse;
         frHist_lastFrame[i].hasAura = frHist_thisFrame[i].hasAura;
         frHist_thisFrame[i].hasAura = qfalse;
         // NOTE: Thes last ones update automatically, so there is no 'Set' function
         //       associated with them.
         frHist_lastFrame[i].weaponState = frHist_thisFrame[i].weaponState;
         if ( i < MAX_CLIENTS ) {
             frHist_thisFrame[i].weaponState = cg_entities[i].currentState.weaponstate;
         } else {
             frHist_thisFrame[i].weaponState = WEAPON_READY;
         }
         frHist_lastFrame[i].weapNr = frHist_thisFrame[i].weapNr;
         frHist_thisFrame[i].weapNr = cg_entities[i].currentState.weapon;
     }
 }
References cg_entities, frHist_lastFrame, frHist_thisFrame, cg_frameHist_t::hasAura, cg_frameHist_t::inPVS, MAX_CLIENTS, MAX_GENTITIES, qfalse, cg_frameHist_t::weapNr, WEAPON_READY, and cg_frameHist_t::weaponState.
Referenced by CG_DrawActiveFrame().
CG_FrameHist_SetAura()
void CG_FrameHist_SetAura (int num)
Definition at line 63 of file cg_frameHist.c.
{
     frHist_thisFrame[num].hasAura = qtrue;
 }
References frHist_thisFrame, cg_frameHist_t::hasAura, and qtrue.
Referenced by CG_Aura_AddParticleSystem().
CG_FrameHist_SetPVS()
void CG_FrameHist_SetPVS (int num)
Definition at line 49 of file cg_frameHist.c.
{
     frHist_thisFrame[num].inPVS = qtrue;
 }
References frHist_thisFrame, cg_frameHist_t::inPVS, and qtrue.
Referenced by CG_AddCEntity().
CG_FrameHist_WasInPVS()
qboolean CG_FrameHist_WasInPVS (int num)
Definition at line 57 of file cg_frameHist.c.
{
     return frHist_lastFrame[num].inPVS;
 }
References frHist_lastFrame, and cg_frameHist_t::inPVS.
Referenced by CG_AddPlayerWeapon(), and CG_Missile().
CG_FrameHist_WasWeaponNr()
int CG_FrameHist_WasWeaponNr (int num)
Definition at line 91 of file cg_frameHist.c.
{
     return frHist_lastFrame[num].weapNr;
 }
References frHist_lastFrame, and cg_frameHist_t::weapNr.
Referenced by CG_AddPlayerWeapon().
CG_FrameHist_WasWeaponState()
int CG_FrameHist_WasWeaponState (int num)
Definition at line 81 of file cg_frameHist.c.
{
     return frHist_lastFrame[num].weaponState;
 }
References frHist_lastFrame, and cg_frameHist_t::weaponState.
Referenced by CG_AddPlayerWeapon().
Variable Documentation
frHist_lastFrame
cg_frameHist_t frHist_lastFrame[MAX_GENTITIES] static
Definition at line 11 of file cg_frameHist.c.
Referenced by CG_FrameHist_HadAura(), CG_FrameHist_Init(), CG_FrameHist_NextFrame(), CG_FrameHist_WasInPVS(), CG_FrameHist_WasWeaponNr(), and CG_FrameHist_WasWeaponState().
frHist_thisFrame
cg_frameHist_t frHist_thisFrame[MAX_GENTITIES] static
Definition at line 10 of file cg_frameHist.c.
Referenced by CG_FrameHist_HasAura(), CG_FrameHist_Init(), CG_FrameHist_IsInPVS(), CG_FrameHist_IsWeaponNr(), CG_FrameHist_IsWeaponState(), CG_FrameHist_NextFrame(), CG_FrameHist_SetAura(), and CG_FrameHist_SetPVS().