ZEQ2-Lite: Source/Game/Game/g_active.c File Reference
g_active.c File Reference
#include "g_local.h"
#include "bg_local.h"
Functions
void ClientEndFrame (gentity_t *ent)
void ClientEvents (gentity_t *ent, int oldEventSequence)
void ClientImpacts (gentity_t *ent, pmove_t *pm)
qboolean ClientInactivityTimer (gclient_t *client)
void ClientIntermissionThink (gclient_t *client)
void ClientThink (int clientNum)
void ClientThink_real (gentity_t *ent)
void G_RunClient (gentity_t *ent)
void G_SetClientSound (gentity_t *ent)
void G_TouchTriggers (gentity_t *ent)
void LockonCheck (gclient_t *client)
void P_DamageFeedback (gentity_t *player)
void P_WorldEffects (gentity_t *ent)
void SendPendingPredictableEvents (playerState_t *ps)
void SpectatorClientEndFrame (gentity_t *ent)
void SpectatorThink (gentity_t *ent, usercmd_t *ucmd)
Function Documentation
ClientEndFrame()
void ClientEndFrame (gentity_t * ent)
Definition at line 670 of file g_active.c.
{
 //  int         i;
     if ( ent->client->sess.sessionTeam == TEAM_SPECTATOR ) {
         SpectatorClientEndFrame( ent );
         return;
     }
     //
     // If the end of unit layout is displayed, don't give
     // the player any normal movement attributes
     //
     if ( level.intermissiontime ) {
         return;
     }
     // burn from lava, etc
     P_WorldEffects( ent );
     // apply all the damage taken this frame
     P_DamageFeedback( ent );
     // add the EF_CONNECTION flag if we haven't gotten commands recently
     if ( level.time - ent->client->lastCmdTime > 1000 ) {
         ent->s.eFlags |= EF_CONNECTION;
     } else {
         ent->s.eFlags &= ~EF_CONNECTION;
     }
     G_SetClientSound (ent);
     // set the latest infor
     BG_PlayerStateToEntityState( &ent->client->ps, &ent->s, qtrue );
     SendPendingPredictableEvents( &ent->client->ps );
     // set the bit for the reachability area the client is currently in
 //  i = trap_AAS_PointReachabilityAreaIndex( ent->client->ps.origin );
 //  ent->client->areabits[i >> 3] |= 1 << (i & 7);
 }
References BG_PlayerStateToEntityState(), EF_CONNECTION, G_SetClientSound(), P_DamageFeedback(), P_WorldEffects(), qtrue, SendPendingPredictableEvents(), SpectatorClientEndFrame(), and TEAM_SPECTATOR.
Referenced by ClientSpawn(), and G_RunFrame().
ClientEvents()
void ClientEvents (gentity_t * ent, int oldEventSequence)
Definition at line 307 of file g_active.c.
{
     int         i, j;
     int         event;
     int         tier;
     int         distance;
     int         enemyMelee,playerMelee;
     gclient_t   *client;
     gentity_t   *enemy;
     int         damage;
     int         amount;
     vec3_t      dir;
     vec3_t      origin, angles;
 //  qboolean    fired;
     gentity_t   *drop;
     playerState_t *ps;
     playerState_t *enemyPS;
     // ADDING FOR ZEQ2
     gentity_t   *missile;
     // END ADDING
     client = ent->client;
     ps = &client->ps;
     if(ps->lockedTarget>0){enemyPS = &g_entities[ps->lockedTarget-1].client->ps;}
     tier = ps->powerLevel[plTierCurrent];
     if(oldEventSequence < client->ps.eventSequence - MAX_PS_EVENTS){
         oldEventSequence = client->ps.eventSequence - MAX_PS_EVENTS;
     }
     for ( i = oldEventSequence ; i < client->ps.eventSequence ; i++ ) {
         event = client->ps.events[ i & (MAX_PS_EVENTS-1) ];
         switch ( event ) {
         case EV_FALL_MEDIUM:
         case EV_FALL_FAR:
             break;
         case EV_FIRE_WEAPON:
             FireWeapon(ent,qfalse);
             break;
         case EV_CHANGE_WEAPON:
             break;
         case EV_ZANZOKEN_START:
             if(!ps->bitFlags & usingMelee){}
             break;
         case EV_ALTFIRE_WEAPON:
             FireWeapon(ent,qtrue);
             break;
         case EV_DETONATE_WEAPON:
             missile = client->guidetarget;
             G_DetachUserWeapon(missile);
             break;
         case EV_BALLFLIP:
             break;
         case EV_MELEE_SPEED:
             break;
         case EV_MELEE_MISS:
             break;
         case EV_MELEE_KNOCKBACK:
             break;
         case EV_MELEE_STUN:
             break;
         case EV_MELEE_KNOCKOUT:
             enemy = &g_entities[ps->lockedTarget-1];
             enemy->enemy = ent;
             break;
         case EV_TIERUP_FIRST:
         case EV_TIERUP:
         case EV_TIERDOWN:
             break;
         case EV_SYNCTIER:
             syncTier(client);
             break;
         case EV_ALTERUP_START:
             break;
         case EV_ALTERDOWN_START:
             break;
         case EV_POWERINGUP_START:
             break;
         case EV_BOOST_START:
             break;
         case EV_LOCKON_START:
             break;
         case EV_LOCKON_RESTART:
             break;
         case EV_LOCKON_END:
             break;
         case EV_DEATH:
             ent->r.contents &= ~CONTENTS_BODY;
             syncTier(client);
             client->respawnTime = level.time + 10000;
             break;
         case EV_UNCONCIOUS:
             syncTier(client);
             break;
         default:
             break;
         }
     }
 }
References angles, CONTENTS_BODY, dir, EV_ALTERDOWN_START, EV_ALTERUP_START, EV_ALTFIRE_WEAPON, EV_BALLFLIP, EV_BOOST_START, EV_CHANGE_WEAPON, EV_DEATH, EV_DETONATE_WEAPON, EV_FALL_FAR, EV_FALL_MEDIUM, EV_FIRE_WEAPON, EV_LOCKON_END, EV_LOCKON_RESTART, EV_LOCKON_START, EV_MELEE_KNOCKBACK, EV_MELEE_KNOCKOUT, EV_MELEE_MISS, EV_MELEE_SPEED, EV_MELEE_STUN, EV_POWERINGUP_START, EV_SYNCTIER, EV_TIERDOWN, EV_TIERUP, EV_TIERUP_FIRST, EV_UNCONCIOUS, EV_ZANZOKEN_START, FireWeapon(), G_DetachUserWeapon(), g_entities, MAX_PS_EVENTS, plTierCurrent, qfalse, qtrue, syncTier(), and usingMelee.
Referenced by ClientThink_real().
ClientImpacts()
void ClientImpacts (gentity_t * ent, pmove_t * pm)
Definition at line 112 of file g_active.c.
{
     int     i, j;
     trace_t trace;
     gentity_t   *other;
     memset( &trace, 0, sizeof( trace ) );
     for (i=0 ; i<pm->numtouch ; i++) {
         for (j=0 ; j<i ; j++) {
             if (pm->touchents[j] == pm->touchents[i] ) {
                 break;
             }
         }
         if (j != i) {
             continue;   // duplicated
         }
         other = &g_entities[ pm->touchents[i] ];
         if ( !other->touch ) {
             continue;
         }
         other->touch( other, ent, &trace );
     }
 }
References g_entities, pmove_t::numtouch, pm, and pmove_t::touchents.
Referenced by ClientThink_real().
ClientInactivityTimer()
qboolean ClientInactivityTimer (gclient_t * client)
Definition at line 253 of file g_active.c.
{
     if ( ! g_inactivity.integer ) {
         // give everyone some time, so if the operator sets g_inactivity during
         // gameplay, everyone isn't kicked
         client->inactivityTime = level.time + 60 * 1000;
         client->inactivityWarning = qfalse;
     } else if ( client->pers.cmd.forwardmove ||
         client->pers.cmd.rightmove ||
         client->pers.cmd.upmove ||
         (client->pers.cmd.buttons & BUTTON_ATTACK) ) {
         client->inactivityTime = level.time + g_inactivity.integer * 1000;
         client->inactivityWarning = qfalse;
     } else if ( !client->pers.localClient ) {
         if ( level.time > client->inactivityTime ) {
             trap_DropClient( client - level.clients, "Dropped due to inactivity" );
             return qfalse;
         }
         if ( level.time > client->inactivityTime - 10000 && !client->inactivityWarning ) {
             client->inactivityWarning = qtrue;
             trap_SendServerCommand( client - level.clients, "cp \"Ten seconds until inactivity drop!\n\"" );
         }
     }
     return qtrue;
 }
References BUTTON_ATTACK, g_inactivity, vmCvar_t::integer, qfalse, qtrue, trap_DropClient(), and trap_SendServerCommand().
ClientIntermissionThink()
void ClientIntermissionThink (gclient_t * client)
Definition at line 283 of file g_active.c.
{
     client->ps.eFlags &= ~EF_TALK;
     client->ps.eFlags &= ~EF_FIRING;
     // the level will exit when everyone wants to or after timeouts
     // swap and latch button actions
     client->oldbuttons = client->buttons;
     client->buttons = client->pers.cmd.buttons;
     if ( client->buttons & ( BUTTON_ATTACK | BUTTON_USE_HOLDABLE ) & ( client->oldbuttons ^ client->buttons ) ) {
         // this used to be an ^1 but once a player says ready, it should stick
         client->readyToExit = 1;
     }
 }
References BUTTON_ATTACK, BUTTON_USE_HOLDABLE, EF_FIRING, and EF_TALK.
Referenced by ClientThink_real().
ClientThink()
void ClientThink (int clientNum)
Definition at line 593 of file g_active.c.
{
     gentity_t *ent;
     ent = g_entities + clientNum;
     trap_GetUsercmd( clientNum, &ent->client->pers.cmd );
     // mark the time we got info, so we can display the
     // phone jack if they don't get any for a while
     ent->client->lastCmdTime = level.time;
     if ( !g_synchronousClients.integer && !ent->client->ps.lockedTarget) {
         ClientThink_real( ent );
     }
 }
References ClientThink_real(), g_entities, g_synchronousClients, vmCvar_t::integer, and trap_GetUsercmd().
Referenced by ClientSpawn(), and vmMain().
ClientThink_real()
void ClientThink_real (gentity_t * ent)
Definition at line 483 of file g_active.c.
{
     gclient_t   *client;
     pmove_t     pm;
     int         oldEventSequence;
     int         msec;
     usercmd_t   *ucmd;
     int         i;
     client = ent->client;
     if (client->pers.connected != CON_CONNECTED){return;}
     ucmd = &ent->client->pers.cmd;
     if ( ucmd->serverTime > level.time + 200 ) {ucmd->serverTime = level.time + 200;}
     if ( ucmd->serverTime < level.time - 1000 ) {ucmd->serverTime = level.time - 1000;}
     msec = ucmd->serverTime - client->ps.commandTime;
     if(msec < 1 && client->sess.spectatorState != SPECTATOR_FOLLOW){return;}
     if(msec > 200){msec = 200;}
     if(pmove_msec.integer < 8 ){trap_Cvar_Set("pmove_msec", "8");}
     else if(pmove_msec.integer > 33){trap_Cvar_Set("pmove_msec", "33");}
     if(pmove_fixed.integer || client->pers.pmoveFixed){
         ucmd->serverTime = ((ucmd->serverTime + pmove_msec.integer-1) / pmove_msec.integer) * pmove_msec.integer;
     }
     if(level.intermissiontime){
         ClientIntermissionThink( client );
         return;
     }
     if(client->sess.sessionTeam == TEAM_SPECTATOR){
         if ( client->sess.spectatorState == SPECTATOR_SCOREBOARD ) {
             return;
         }
         SpectatorThink( ent, ucmd );
         return;
     }
     if(client->noclip){
         client->ps.pm_type = PM_NOCLIP;
     }
     else{
         client->ps.pm_type = PM_NORMAL;
     }
     ent->s.playerBitFlags = client->ps.bitFlags;
     ent->s.attackPowerCurrent = client->ps.powerLevel[plHealth];
     ent->s.attackPowerTotal = client->ps.powerLevel[plMaximum];
     G_LinkUserWeaponData( &(client->ps) );
     G_CheckSkills(&(client->ps));
     // set up for pmove
     oldEventSequence = client->ps.eventSequence;
     memset(&pm,0,sizeof(pm));
     pm.ps = &client->ps;
     pm.cmd = *ucmd;
     pm.tracemask = MASK_PLAYERSOLID;
     pm.trace = trap_Trace;
     pm.pointcontents = trap_PointContents;
     pm.debugLevel = g_debugMove.integer;
     pm.noFootsteps = (g_dmflags.integer & DF_NO_FOOTSTEPS) > 0;
     pm.pmove_fixed = pmove_fixed.integer | client->pers.pmoveFixed;
     pm.pmove_msec = pmove_msec.integer;
     VectorCopy(client->ps.origin,client->oldOrigin);
     Pmove(&pm);
     checkTier(client);
     if(pm.ps->powerLevel[plTierChanged] == 1)
     {
         if(pm.ps->powerLevel[plTierChanged] == 1){
             if(!PM_WeaponSelectable(pm.ps->weapon)){
                 for(i = 6; i > 0; i--){
                     if(PM_WeaponSelectable(i)){
                         pm.ps->weapon = i;
                         break;
                     }
                 }
             }
         }
     }
     LockonCheck(client);
     if ( ent->client->ps.eventSequence != oldEventSequence ) {
         ent->eventTime = level.time;
     }
     BG_PlayerStateToEntityState( &ent->client->ps, &ent->s, qtrue );
     SendPendingPredictableEvents(&ent->client->ps);
     if ( !( ent->client->ps.eFlags & EF_FIRING ) ) {
         client->fireHeld = qfalse;
     }
     VectorCopy( ent->s.pos.trBase, ent->r.currentOrigin );
     VectorCopy (pm.mins, ent->r.mins);
     VectorCopy (pm.maxs, ent->r.maxs);
     ent->waterlevel = pm.waterlevel;
     ent->watertype = pm.watertype;
     ClientEvents(ent,oldEventSequence);
     trap_LinkEntity (ent);
     if(!ent->client->noclip){
         G_TouchTriggers(ent);
     }
     VectorCopy( ent->client->ps.origin, ent->r.currentOrigin );
     ClientImpacts(ent,&pm);
     if(ent->client->ps.eventSequence != oldEventSequence) {
         ent->eventTime = level.time;
     }
     client->oldbuttons = client->buttons;
     client->buttons = ucmd->buttons;
     client->latched_buttons |= client->buttons & ~client->oldbuttons;
     if (client->ps.bitFlags & isDead){
         if(level.time > client->respawnTime){ClientRespawn(ent);}
         return;
     }
 }
References BG_PlayerStateToEntityState(), checkTier(), ClientEvents(), ClientImpacts(), ClientIntermissionThink(), ClientRespawn(), pmove_t::cmd, CON_CONNECTED, pmove_t::debugLevel, DF_NO_FOOTSTEPS, EF_FIRING, G_CheckSkills(), g_debugMove, g_dmflags, G_LinkUserWeaponData(), G_TouchTriggers(), vmCvar_t::integer, isDead, LockonCheck(), MASK_PLAYERSOLID, pmove_t::maxs, pmove_t::mins, pmove_t::noFootsteps, plHealth, plMaximum, plTierChanged, pm, PM_NOCLIP, PM_NORMAL, PM_WeaponSelectable(), Pmove(), pmove_t::pmove_fixed, pmove_fixed, pmove_t::pmove_msec, pmove_msec, pmove_t::pointcontents, pmove_t::ps, qfalse, qtrue, SendPendingPredictableEvents(), SPECTATOR_FOLLOW, SPECTATOR_SCOREBOARD, SpectatorThink(), TEAM_SPECTATOR, pmove_t::trace, pmove_t::tracemask, trap_Cvar_Set(), trap_LinkEntity(), trap_PointContents(), trap_Trace(), VectorCopy, pmove_t::waterlevel, and pmove_t::watertype.
Referenced by ClientThink(), and G_RunClient().
G_RunClient()
void G_RunClient (gentity_t * ent)
Definition at line 609 of file g_active.c.
{
     if ( !g_synchronousClients.integer && !ent->client->ps.lockedTarget) {
         return;
     }
     ent->client->pers.cmd.serverTime = level.time;
     ClientThink_real( ent );
 }
References ClientThink_real(), g_synchronousClients, and vmCvar_t::integer.
Referenced by G_RunFrame().
G_SetClientSound()
void G_SetClientSound (gentity_t * ent)
Definition at line 99 of file g_active.c.
{
     ent->client->ps.loopSound = 0;
 }
Referenced by ClientEndFrame().
G_TouchTriggers()
void G_TouchTriggers (gentity_t * ent)
Definition at line 146 of file g_active.c.
{
     int         i, num;
     int         touch[MAX_GENTITIES];
     gentity_t   *hit;
     trace_t     trace;
     vec3_t      mins, maxs;
     static vec3_t   range = { 40, 40, 52 };
     if ( !ent->client ) {
         return;
     }
     VectorSubtract( ent->client->ps.origin, range, mins );
     VectorAdd( ent->client->ps.origin, range, maxs );
     num = trap_EntitiesInBox( mins, maxs, touch, MAX_GENTITIES );
     // can't use ent->absmin, because that has a one unit pad
     VectorAdd( ent->client->ps.origin, ent->r.mins, mins );
     VectorAdd( ent->client->ps.origin, ent->r.maxs, maxs );
     for ( i=0 ; i<num ; i++ ) {
         hit = &g_entities[touch[i]];
         if ( !hit->touch && !ent->touch ) {
             continue;
         }
         if ( !( hit->r.contents & CONTENTS_TRIGGER ) ) {
             continue;
         }
         // ignore most entities if a spectator
         if ( ent->client->sess.sessionTeam == TEAM_SPECTATOR ) {
             if ( hit->s.eType != ET_TELEPORT_TRIGGER &&
                 // this is ugly but adding a new ET_? type will
                 // most likely cause network incompatibilities
                 hit->touch != Touch_DoorTrigger) {
                 continue;
             }
         }
         if ( !trap_EntityContact( mins, maxs, hit ) ) {
                 continue;
         }
         memset( &trace, 0, sizeof(trace) );
         if ( hit->touch ) {
             hit->touch (hit, ent, &trace);
         }
     }
     // if we didn't touch a jump pad this pmove frame
     if ( ent->client->ps.jumppad_frame != ent->client->ps.pmove_framecount ) {
         ent->client->ps.jumppad_frame = 0;
         ent->client->ps.jumppad_ent = 0;
     }
 }
References CONTENTS_TRIGGER, ET_TELEPORT_TRIGGER, g_entities, MAX_GENTITIES, TEAM_SPECTATOR, Touch_DoorTrigger(), trap_EntitiesInBox(), trap_EntityContact(), VectorAdd, and VectorSubtract.
Referenced by ClientThink_real(), and SpectatorThink().
LockonCheck()
void LockonCheck (gclient_t * client)
Definition at line 438 of file g_active.c.
{
     int entityNum = -1;
     playerState_t *ps;
     ps = &client->ps;
     if(ps->lockedTarget>0){
         if(!&g_entities[ps->lockedTarget-1].client || &g_entities[ps->lockedTarget-1].client->pers.connected == CON_DISCONNECTED){
             ps->lockonData[lkLastLockedPlayer] = -1;
             ps->lockedPosition = 0;
             ps->lockedPlayer = 0;
             ps->lockedTarget = 0;
             return;
         }
         if(ps->lockedPlayer){
             ps->timers[tmLockon] += pml.msec;
             if(ps->lockedPlayer->bitFlags & isTransforming || ps->lockedPlayer->bitFlags & isStruggling || ps->lockedPlayer->bitFlags & isDead ||
                     ps->lockedPlayer->bitFlags & isUnconcious || ps->lockedPlayer->bitFlags & isCrashed){
                 ps->lockedPosition = 0;
                 ps->lockedPlayer = 0;
                 ps->lockedTarget = 0;
                 return;
             }
             entityNum = PM_VerifyTrace(250);
             if(!(ps->bitFlags & usingZanzoken) && ps->lockedPlayer && ((entityNum == -1) || ps->lockedPlayer->bitFlags & usingZanzoken)){
                     ps->lockonData[lkLastLockedPlayer] = ps->lockedPlayer->clientNum;
                     ps->lockedPosition = 0;
                     ps->lockedTarget = 0;
                     ps->timers[tmLockon] = 0;
                     return;
             }
         }
         ps->lockedPosition = &g_entities[ps->lockedTarget-1].r.currentOrigin;
         ps->lockedPlayer = &g_entities[ps->lockedTarget-1].client->ps;
     }
 }
References CON_DISCONNECTED, g_entities, isCrashed, isDead, isStruggling, isTransforming, isUnconcious, lkLastLockedPlayer, pml_t::msec, PM_VerifyTrace(), pml, tmLockon, and usingZanzoken.
Referenced by ClientThink_real().
P_DamageFeedback()
void P_DamageFeedback (gentity_t * player)
Definition at line 29 of file g_active.c.
{
     gclient_t   *client;
     float   count;
     vec3_t  angles;
     client = player->client;
     // total points of damage shot at the player this frame
     count = client->damage_blood; // + client->damage_armor;
     if ( count == 0 ) { // didn't take any damage
         // ADDING FOR ZEQ2
         // but we DO need to reset this to 0 for the deductHP to work!
         client->ps.damageCount = 0;
         return;
     }
     if ( count > 255 ) {
         count = 255;
     }
     // send the information to the client
     // world damage (falling, slime, etc) uses a special code
     // to make the blend blob centered instead of positional
     if ( client->damage_fromWorld ) {
         client->ps.damagePitch = 255;
         client->ps.damageYaw = 255;
         client->damage_fromWorld = qfalse;
     } else {
         vectoangles( client->damage_from, angles );
         client->ps.damagePitch = angles[PITCH]/360.0 * 256;
         client->ps.damageYaw = angles[YAW]/360.0 * 256;
     }
     // play an apropriate pain sound
     if ( (level.time > player->pain_debounce_time) ) {
         player->pain_debounce_time = level.time + 700;
         G_AddEvent( player, EV_PAIN, player->powerLevelTotal );
         client->ps.damageEvent++;
     }
     client->ps.damageCount = count;
     //
     // clear totals
     //
     client->damage_blood = 0;
     //client->damage_armor = 0;
     client->damage_knockback = 0;
 }
References angles, EV_PAIN, G_AddEvent(), PITCH, qfalse, vectoangles(), and YAW.
Referenced by ClientEndFrame().
P_WorldEffects()
void P_WorldEffects (gentity_t * ent)
Definition at line 90 of file g_active.c.
 {}
Referenced by ClientEndFrame().
SendPendingPredictableEvents()
void SendPendingPredictableEvents (playerState_t * ps)
Definition at line 409 of file g_active.c.
{
     gentity_t *t;
     int event, seq;
     int extEvent, number;
     // if there are still events pending
     if ( ps->entityEventSequence < ps->eventSequence ) {
         // create a temporary entity for this event which is sent to everyone
         // except the client who generated the event
         seq = ps->entityEventSequence & (MAX_PS_EVENTS-1);
         event = ps->events[ seq ] | ( ( ps->entityEventSequence & 3 ) << 8 );
         // set external event to zero before calling BG_PlayerStateToEntityState
         extEvent = ps->externalEvent;
         ps->externalEvent = 0;
         // create temporary entity for event
         t = G_TempEntity( ps->origin, event );
         number = t->s.number;
         BG_PlayerStateToEntityState( ps, &t->s,qtrue );
         t->s.number = number;
         t->s.eType = ET_EVENTS + event;
         t->s.eFlags |= EF_PLAYER_EVENT;
         t->s.otherEntityNum = ps->clientNum;
         // send to everyone except the client who generated the event
         t->r.svFlags |= SVF_NOTSINGLECLIENT;
         t->r.singleClient = ps->clientNum;
         // set back external event
         ps->externalEvent = extEvent;
     }
 }
References BG_PlayerStateToEntityState(), EF_PLAYER_EVENT, ET_EVENTS, G_TempEntity(), MAX_PS_EVENTS, qtrue, and SVF_NOTSINGLECLIENT.
Referenced by ClientEndFrame(), and ClientThink_real().
SpectatorClientEndFrame()
void SpectatorClientEndFrame (gentity_t * ent)
Definition at line 621 of file g_active.c.
{
     gclient_t   *cl;
     // if we are doing a chase cam or a remote view, grab the latest info
     if ( ent->client->sess.spectatorState == SPECTATOR_FOLLOW ) {
         int     clientNum, flags;
         clientNum = ent->client->sess.spectatorClient;
         // team follow1 and team follow2 go to whatever clients are playing
         if ( clientNum == -1 ) {
             clientNum = level.follow1;
         } else if ( clientNum == -2 ) {
             clientNum = level.follow2;
         }
         if ( clientNum >= 0 ) {
             cl = &level.clients[ clientNum ];
             if ( cl->pers.connected == CON_CONNECTED && cl->sess.sessionTeam != TEAM_SPECTATOR ) {
                 flags = (cl->ps.eFlags & ~(EF_VOTED | EF_TEAMVOTED)) | (ent->client->ps.eFlags & (EF_VOTED | EF_TEAMVOTED));
                 ent->client->ps = cl->ps;
                 ent->client->ps.pm_flags |= PMF_FOLLOW;
                 ent->client->ps.eFlags = flags;
                 return;
             } else {
                 // drop them to free spectators unless they are dedicated camera followers
                 if ( ent->client->sess.spectatorClient >= 0 ) {
                     ent->client->sess.spectatorState = SPECTATOR_FREE;
                     ClientBegin( ent->client - level.clients );
                 }
             }
         }
     }
     if ( ent->client->sess.spectatorState == SPECTATOR_SCOREBOARD ) {
         ent->client->ps.pm_flags |= PMF_SCOREBOARD;
     } else {
         ent->client->ps.pm_flags &= ~PMF_SCOREBOARD;
     }
 }
References cl, ClientBegin(), CON_CONNECTED, EF_TEAMVOTED, EF_VOTED, PMF_FOLLOW, PMF_SCOREBOARD, SPECTATOR_FOLLOW, SPECTATOR_FREE, SPECTATOR_SCOREBOARD, and TEAM_SPECTATOR.
Referenced by ClientEndFrame().
SpectatorThink()
void SpectatorThink (gentity_t * ent, usercmd_t * ucmd)
Definition at line 208 of file g_active.c.
{
     pmove_t pm;
     gclient_t   *client;
     client = ent->client;
     if ( client->sess.spectatorState != SPECTATOR_FOLLOW ) {
         client->ps.pm_type = PM_SPECTATOR;
         client->ps.baseStats[stSpeed] = 400;    // faster than normal
         // set up for pmove
         memset (&pm, 0, sizeof(pm));
         pm.ps = &client->ps;
         pm.cmd = *ucmd;
         pm.tracemask = MASK_PLAYERSOLID & ~CONTENTS_BODY;   // spectators can fly through bodies
         pm.trace = trap_Trace;
         pm.pointcontents = trap_PointContents;
         // perform a pmove
         Pmove (&pm);
         // save results of pmove
         VectorCopy( client->ps.origin, ent->s.origin );
         // END ADDING
         G_TouchTriggers( ent );
         trap_UnlinkEntity( ent );
     }
     client->oldbuttons = client->buttons;
     client->buttons = ucmd->buttons;
     // attack button cycles through spectators
     if ( ( client->buttons & BUTTON_ATTACK ) && ! ( client->oldbuttons & BUTTON_ATTACK ) ) {
         Cmd_FollowCycle_f( ent, 1 );
     }
 }
References BUTTON_ATTACK, pmove_t::cmd, Cmd_FollowCycle_f(), CONTENTS_BODY, G_TouchTriggers(), MASK_PLAYERSOLID, pm, PM_SPECTATOR, Pmove(), pmove_t::pointcontents, pmove_t::ps, SPECTATOR_FOLLOW, stSpeed, pmove_t::trace, pmove_t::tracemask, trap_PointContents(), trap_Trace(), trap_UnlinkEntity(), and VectorCopy.
Referenced by ClientThink_real().