ZEQ2-Lite: Source/Game/Game/g_userweapons.c File Reference
g_userweapons.c File Reference
#include "g_local.h"
Functions
void G_CheckSkills (playerState_t *ps)
g_userweapons.c
g_userWeapon_t * G_FindUserAltWeaponData (int clientNum, int weaponNum)
g_userWeapon_t * G_FindUserAltWeaponSpawnData (int clientNum, int weaponNum)
g_userWeapon_t * G_FindUserWeaponData (int clientNum, int weaponNum)
int * G_FindUserWeaponMask (int clientNum)
g_userWeapon_t * G_FindUserWeaponSpawnData (int clientNum, int weaponNum)
void G_LinkUserWeaponData (playerState_t *ps)
Variables
static g_userWeapon_t weaponPhysicsDatabase [MAX_CLIENTS][ALTSPAWN_OFFSET+MAX_PLAYERWEAPONS]
static int weaponPhysicsMasks [MAX_CLIENTS]
Function Documentation
G_CheckSkills()
void G_CheckSkills (playerState_t * ps)
g_userweapons.c
Definition at line 56 of file g_userweapons.c.
{
     int weapon;
     weapon = 1;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL1;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL2;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL3;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL4;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL5;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL6;
     while(weapon < 7){
         qboolean usable;
         g_userWeapon_t  *weaponSettings;
         usable = qtrue;
         weaponSettings = G_FindUserWeaponData(ps->clientNum,weapon);
         // =========================
         // REQUIREMENTS
         // =========================
         if(weaponSettings->require_maximum && ps->powerLevel[plMaximum] < weaponSettings->require_maximum){usable = qfalse;}
         if(weaponSettings->require_minPowerLevel && ps->powerLevel[plCurrent] < weaponSettings->require_minPowerLevel){usable = qfalse;}
         if(weaponSettings->require_maxPowerLevel && ps->powerLevel[plCurrent] > weaponSettings->require_maxPowerLevel){usable = qfalse;}
         if(weaponSettings->require_minFatigue && ps->powerLevel[plFatigue] < weaponSettings->require_minFatigue){usable = qfalse;}
         if(weaponSettings->require_maxFatigue && ps->powerLevel[plFatigue] > weaponSettings->require_maxFatigue){usable = qfalse;}
         if(weaponSettings->require_minHealth && ps->powerLevel[plHealth] < weaponSettings->require_minHealth){usable = qfalse;}
         if(weaponSettings->require_maxHealth && ps->powerLevel[plHealth] > weaponSettings->require_maxHealth){usable = qfalse;}
         if(weaponSettings->require_minTier && ps->powerLevel[plTierCurrent] < weaponSettings->require_minTier-1){usable = qfalse;}
         if(weaponSettings->require_maxTier && ps->powerLevel[plTierCurrent] > weaponSettings->require_maxTier-1){usable = qfalse;}
         if(weaponSettings->require_minTotalTier && ps->powerLevel[plTierTotal] < weaponSettings->require_minTotalTier-1){usable = qfalse;}
         if(weaponSettings->require_maxTotalTier && ps->powerLevel[plTierTotal] > weaponSettings->require_maxTotalTier-1){usable = qfalse;}
         if(weaponSettings->require_ground && !(ps->bitFlags & atopGround)){usable = qfalse;}
         if(weaponSettings->require_flight && !(ps->bitFlags & usingFlight)){usable = qfalse;}
         if(weaponSettings->require_water && !(ps->bitFlags & underWater)){usable = qfalse;}
         if(usable){
             if(weapon == 1){ps->powerups[PW_SKILLS] |= USABLE_SKILL1;}
             if(weapon == 2){ps->powerups[PW_SKILLS] |= USABLE_SKILL2;}
             if(weapon == 3){ps->powerups[PW_SKILLS] |= USABLE_SKILL3;}
             if(weapon == 4){ps->powerups[PW_SKILLS] |= USABLE_SKILL4;}
             if(weapon == 5){ps->powerups[PW_SKILLS] |= USABLE_SKILL5;}
             if(weapon == 6){ps->powerups[PW_SKILLS] |= USABLE_SKILL6;}
         }
         weapon += 1;
     }
 }
References atopGround, G_FindUserWeaponData(), plCurrent, plFatigue, plHealth, plMaximum, plTierCurrent, plTierTotal, PW_SKILLS, qfalse, qtrue, g_userWeapon_t::require_flight, g_userWeapon_t::require_ground, g_userWeapon_t::require_maxFatigue, g_userWeapon_t::require_maxHealth, g_userWeapon_t::require_maximum, g_userWeapon_t::require_maxPowerLevel, g_userWeapon_t::require_maxTier, g_userWeapon_t::require_maxTotalTier, g_userWeapon_t::require_minFatigue, g_userWeapon_t::require_minHealth, g_userWeapon_t::require_minPowerLevel, g_userWeapon_t::require_minTier, g_userWeapon_t::require_minTotalTier, g_userWeapon_t::require_water, underWater, USABLE_SKILL1, USABLE_SKILL2, USABLE_SKILL3, USABLE_SKILL4, USABLE_SKILL5, USABLE_SKILL6, and usingFlight.
Referenced by ClientThink_real().
G_FindUserAltWeaponData()
g_userWeapon_t* G_FindUserAltWeaponData (int clientNum, int weaponNum)
Definition at line 40 of file g_userweapons.c.
{
     return &weaponPhysicsDatabase[clientNum][weaponNum - 1 + ALTWEAPON_OFFSET];
 }
References ALTWEAPON_OFFSET, and weaponPhysicsDatabase.
Referenced by Fire_UserWeapon(), and G_LinkUserWeaponData().
G_FindUserAltWeaponSpawnData()
g_userWeapon_t* G_FindUserAltWeaponSpawnData (int clientNum, int weaponNum)
Definition at line 49 of file g_userweapons.c.
{
     return &weaponPhysicsDatabase[clientNum][weaponNum - 1 + ALTSPAWN_OFFSET];
 }
References ALTSPAWN_OFFSET, and weaponPhysicsDatabase.
G_FindUserWeaponData()
g_userWeapon_t* G_FindUserWeaponData (int clientNum, int weaponNum)
Definition at line 22 of file g_userweapons.c.
{
     return &weaponPhysicsDatabase[clientNum][weaponNum - 1];
 }
References weaponPhysicsDatabase.
Referenced by Fire_UserWeapon(), G_CheckSkills(), G_LinkUserWeaponData(), and G_weapPhys_StoreBuffer().
G_FindUserWeaponMask()
int* G_FindUserWeaponMask (int clientNum)
Definition at line 13 of file g_userweapons.c.
{
     return &weaponPhysicsMasks[clientNum];
 }
References weaponPhysicsMasks.
Referenced by ClientSpawn(), ClientUserinfoChanged(), and G_weapPhys_Parse().
G_FindUserWeaponSpawnData()
g_userWeapon_t* G_FindUserWeaponSpawnData (int clientNum, int weaponNum)
Definition at line 31 of file g_userweapons.c.
{
     return &weaponPhysicsDatabase[clientNum][weaponNum - 1 + SPAWN_OFFSET];
 }
References SPAWN_OFFSET, and weaponPhysicsDatabase.
G_LinkUserWeaponData()
void G_LinkUserWeaponData (playerState_t * ps)
Definition at line 106 of file g_userweapons.c.
{
     g_userWeapon_t  *weaponSettings;
     g_userWeapon_t  *alt_weaponSettings;
     // Prevent reading below bound of array pointed to by weaponSettings.
     if ( ps->weapon == WP_NONE ) {
         memset(ps->currentSkill, 0, sizeof(ps->currentSkill) );
         return;
     }
     // NOTE: This function will NEVER be able to be called with a weapon that
     //       was not defined, so the next statement is SAFE.
     weaponSettings = G_FindUserWeaponData( ps->clientNum, ps->weapon );
     ps->currentSkill[WPSTAT_NUMCHECK] = ps->weapon;
     ps->currentSkill[WPSTAT_POWER] = weaponSettings->damage_damage;
     ps->currentSkill[WPSTAT_POWERLEVELCOST] = weaponSettings->costs_powerLevel;
     ps->currentSkill[WPSTAT_MAXIMUMCOST] = weaponSettings->costs_maximum;
     ps->currentSkill[WPSTAT_HEALTHCOST] = weaponSettings->costs_health;
     ps->currentSkill[WPSTAT_FATIGUECOST] = weaponSettings->costs_fatigue;
     ps->currentSkill[WPSTAT_CHRGTIME] = weaponSettings->costs_chargeTime;
     ps->currentSkill[WPSTAT_CHRGREADY] = weaponSettings->costs_chargeReady;
     ps->currentSkill[WPSTAT_COOLTIME] = weaponSettings->costs_cooldownTime;
     ps->currentSkill[WPSTAT_RESTRICT_MOVEMENT] = weaponSettings->restrict_movement;
     ps->currentSkill[WPSTAT_BITFLAGS] = weaponSettings->general_bitflags;
     ps->currentSkill[WPSTAT_RESTRICT_MOVEMENT] = weaponSettings->restrict_movement;
     // Set the ready state of a charged weapon
     if ( ( ps->stats[stChargePercentPrimary] >= weaponSettings->costs_chargeReady ) && ( ps->currentSkill[WPSTAT_BITFLAGS] & WPF_NEEDSCHARGE ) ) {
         ps->currentSkill[WPSTAT_BITFLAGS] |= WPF_READY;
     } else {
         ps->currentSkill[WPSTAT_BITFLAGS] &= ~WPF_READY;
     }
     // Guided trajectories and beams should use WEAPON_GUIDING state
     if ( weaponSettings->homing_type == HOM_GUIDED || weaponSettings->general_type == skillTypeBEAM ) {
         ps->currentSkill[WPSTAT_BITFLAGS] |= WPF_GUIDED;
     }
     // Only attempt to link altfire weapon when it exists.
     if (ps->currentSkill[WPSTAT_BITFLAGS] & WPF_ALTWEAPONPRESENT) {
         alt_weaponSettings = G_FindUserAltWeaponData( ps->clientNum, ps->weapon );
         ps->currentSkill[WPSTAT_ALT_POWER] = alt_weaponSettings->damage_damage;
         ps->currentSkill[WPSTAT_ALT_POWERLEVELCOST] = alt_weaponSettings->costs_powerLevel;
         ps->currentSkill[WPSTAT_ALT_MAXIMUMCOST] = alt_weaponSettings->costs_maximum;
         ps->currentSkill[WPSTAT_ALT_HEALTHCOST] = alt_weaponSettings->costs_health;
         ps->currentSkill[WPSTAT_ALT_FATIGUECOST] = alt_weaponSettings->costs_fatigue;
         ps->currentSkill[WPSTAT_ALT_CHRGTIME] = alt_weaponSettings->costs_chargeTime;
         ps->currentSkill[WPSTAT_ALT_CHRGREADY] = alt_weaponSettings->costs_chargeReady;
         ps->currentSkill[WPSTAT_ALT_COOLTIME] = alt_weaponSettings->costs_cooldownTime;
         ps->currentSkill[WPSTAT_ALT_RESTRICT_MOVEMENT] = alt_weaponSettings->restrict_movement;
         ps->currentSkill[WPSTAT_ALT_BITFLAGS] = alt_weaponSettings->general_bitflags;
         ps->currentSkill[WPSTAT_ALT_RESTRICT_MOVEMENT] = alt_weaponSettings->restrict_movement;
         // Guided trajectories and beams should use WEAPON_GUIDING state
         if ( alt_weaponSettings->homing_type == HOM_GUIDED || alt_weaponSettings->general_type == skillTypeBEAM ) {
             ps->currentSkill[WPSTAT_ALT_BITFLAGS] |= WPF_GUIDED;
         }
         // Set the ready state of a charged altfire weapon
         if ( ( ps->stats[stChargePercentSecondary] >= alt_weaponSettings->costs_chargeReady ) && ( ps->currentSkill[WPSTAT_ALT_BITFLAGS] & WPF_NEEDSCHARGE ) ) {
             ps->currentSkill[WPSTAT_ALT_BITFLAGS] |= WPF_READY;
         } else {
             ps->currentSkill[WPSTAT_ALT_BITFLAGS] &= ~WPF_READY;
         }
     }
 }
References g_userWeapon_t::costs_chargeReady, g_userWeapon_t::costs_chargeTime, g_userWeapon_t::costs_cooldownTime, g_userWeapon_t::costs_fatigue, g_userWeapon_t::costs_health, g_userWeapon_t::costs_maximum, g_userWeapon_t::costs_powerLevel, g_userWeapon_t::damage_damage, G_FindUserAltWeaponData(), G_FindUserWeaponData(), g_userWeapon_t::general_bitflags, g_userWeapon_t::general_type, HOM_GUIDED, g_userWeapon_t::homing_type, g_userWeapon_t::restrict_movement, skillTypeBEAM, stChargePercentPrimary, stChargePercentSecondary, WP_NONE, WPF_ALTWEAPONPRESENT, WPF_GUIDED, WPF_NEEDSCHARGE, WPF_READY, WPSTAT_ALT_BITFLAGS, WPSTAT_ALT_CHRGREADY, WPSTAT_ALT_CHRGTIME, WPSTAT_ALT_COOLTIME, WPSTAT_ALT_FATIGUECOST, WPSTAT_ALT_HEALTHCOST, WPSTAT_ALT_MAXIMUMCOST, WPSTAT_ALT_POWER, WPSTAT_ALT_POWERLEVELCOST, WPSTAT_ALT_RESTRICT_MOVEMENT, WPSTAT_BITFLAGS, WPSTAT_CHRGREADY, WPSTAT_CHRGTIME, WPSTAT_COOLTIME, WPSTAT_FATIGUECOST, WPSTAT_HEALTHCOST, WPSTAT_MAXIMUMCOST, WPSTAT_NUMCHECK, WPSTAT_POWER, WPSTAT_POWERLEVELCOST, and WPSTAT_RESTRICT_MOVEMENT.
Referenced by ClientThink_real().
Variable Documentation
weaponPhysicsDatabase
g_userWeapon_t weaponPhysicsDatabase[MAX_CLIENTS][ALTSPAWN_OFFSET+MAX_PLAYERWEAPONS] static
Definition at line 4 of file g_userweapons.c.
Referenced by G_FindUserAltWeaponData(), G_FindUserAltWeaponSpawnData(), G_FindUserWeaponData(), and G_FindUserWeaponSpawnData().
weaponPhysicsMasks
int weaponPhysicsMasks[MAX_CLIENTS] static
Definition at line 3 of file g_userweapons.c.
Referenced by G_FindUserWeaponMask().