ZEQ2-Lite: Engine/tools/lcc/cpp/lex.c File Reference
lex.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cpp.h"
Data Structures
struct fsm
Macros
#define ACT(tok, act) ((tok<<7)+act)
#define C_ALPH 2
#define C_EOF 4
#define C_NUM 3
#define C_WS 1
#define C_XX 5
#define GETACT(st) (st>>7)&0x1ff
#define MAXSTATE 32
#define QBSBIT 0100
Enumerations
enum state {
START =0, NUM1, NUM2, NUM3,
ID1, ST1, ST2, ST3,
COM1, COM2, COM3, COM4,
CC1, CC2, WS1, PLUS1,
MINUS1, STAR1, SLASH1, PCT1,
SHARP1, CIRC1, GT1, GT2,
LT1, LT2, OR1, AND1,
ASG1, NOT1, DOTS1, S_SELF =MAXSTATE,
S_SELFB, S_EOF, S_NL, S_EOFSTR,
S_STNL, S_COMNL, S_EOFCOM, S_COMMENT,
S_EOB, S_WS, S_NAME
}
Functions
void expandlex (void)
int fillbuf (Source *s)
void fixlex (void)
int foldline (Source *s)
int gettokens (Tokenrow *trp, int reset)
Source * setsource (char *name, int fd, char *str)
int trigraph (Source *s)
void unsetsource (void)
Variables
short bigfsm [256][MAXSTATE]
struct fsm fsm []
int tokkind [256]
int tottok
Macro Definition Documentation
ACT
#define ACT (tok, act) ((tok<<7)+act)
Definition at line 26 of file lex.c.
C_ALPH
#define C_ALPH 2
Definition at line 32 of file lex.c.
C_EOF
#define C_EOF 4
Definition at line 34 of file lex.c.
C_NUM
#define C_NUM 3
Definition at line 33 of file lex.c.
C_WS
#define C_WS 1
Definition at line 31 of file lex.c.
C_XX
#define C_XX 5
Definition at line 35 of file lex.c.
GETACT
#define GETACT (st) (st>>7)&0x1ff
Definition at line 28 of file lex.c.
MAXSTATE
#define MAXSTATE 32
Definition at line 25 of file lex.c.
QBSBIT
#define QBSBIT 0100
Definition at line 27 of file lex.c.
Enumeration Type Documentation
state
enum state
Enumerator
START
NUM1
NUM2
NUM3
ID1
ST1
ST2
ST3
COM1
COM2
COM3
COM4
CC1
CC2
WS1
PLUS1
MINUS1
STAR1
SLASH1
PCT1
SHARP1
CIRC1
GT1
GT2
LT1
LT2
OR1
AND1
ASG1
NOT1
DOTS1
S_SELF
S_SELFB
S_EOF
S_NL
S_EOFSTR
S_STNL
S_COMNL
S_EOFCOM
S_COMMENT
S_EOB
S_WS
S_NAME
Definition at line 37 of file lex.c.
            {
     START=0, NUM1, NUM2, NUM3, ID1, ST1, ST2, ST3, COM1, COM2, COM3, COM4,
     CC1, CC2, WS1, PLUS1, MINUS1, STAR1, SLASH1, PCT1, SHARP1,
     CIRC1, GT1, GT2, LT1, LT2, OR1, AND1, ASG1, NOT1, DOTS1,
     S_SELF=MAXSTATE, S_SELFB, S_EOF, S_NL, S_EOFSTR,
     S_STNL, S_COMNL, S_EOFCOM, S_COMMENT, S_EOB, S_WS, S_NAME
 };
Function Documentation
expandlex()
void expandlex (void)
Definition at line 239 of file lex.c.
 {
     /*const*/ struct fsm *fp;
     int i, j, nstate;
     for (fp = fsm; fp->state>=0; fp++) {
         for (i=0; fp->ch[i]; i++) {
             nstate = fp->nextstate;
             if (nstate >= S_SELF)
                 nstate = ~nstate;
             switch (fp->ch[i]) {
             case C_XX:      /* random characters */
                 for (j=0; j<256; j++)
                     bigfsm[j][fp->state] = nstate;
                 continue;
             case C_ALPH:
                 for (j=0; j<=256; j++)
                     if (('a'<=j&&j<='z') || ('A'<=j&&j<='Z')
                       || j=='_')
                         bigfsm[j][fp->state] = nstate;
                 continue;
             case C_NUM:
                 for (j='0'; j<='9'; j++)
                     bigfsm[j][fp->state] = nstate;
                 continue;
             default:
                 bigfsm[fp->ch[i]][fp->state] = nstate;
             }
         }
     }
     /* install special cases for ? (trigraphs),  \ (splicing), runes, and EOB */
     for (i=0; i<MAXSTATE; i++) {
         for (j=0; j<0xFF; j++)
             if (j=='?' || j=='\\') {
                 if (bigfsm[j][i]>0)
                     bigfsm[j][i] = ~bigfsm[j][i];
                 bigfsm[j][i] &= ~QBSBIT;
             }
         bigfsm[EOB][i] = ~S_EOB;
         if (bigfsm[EOFC][i]>=0)
             bigfsm[EOFC][i] = ~S_EOF;
     }
 }
References bigfsm, C_ALPH, C_NUM, C_XX, EOB, EOFC, fp, MAXSTATE, QBSBIT, S_EOB, S_EOF, and S_SELF.
Referenced by main().
fillbuf()
int fillbuf (Source * s)
Definition at line 515 of file lex.c.
 {
     int n, nr;
     nr = INS/8;
     if ((char *)s->inl+nr > (char *)s->inb+INS)
         error(FATAL, "Input buffer overflow");
     if (s->fd<0 || (n=read(s->fd, (char *)s->inl, INS/8)) <= 0)
         n = 0;
     if ((*s->inp&0xff) == EOB) /* sentinel character appears in input */
         *s->inp = EOFC;
     s->inl += n;
     s->inl[0] = s->inl[1]= s->inl[2]= s->inl[3] = EOB;
     if (n==0) {
         s->inl[0] = s->inl[1]= s->inl[2]= s->inl[3] = EOFC;
         return EOF;
     }
     return 0;
 }
References EOB, EOF, EOFC, error(), FATAL, and INS.
Referenced by foldline(), gettok(), gettokens(), scon(), and trigraph().
fixlex()
void fixlex (void)
Definition at line 285 of file lex.c.
 {
     /* do C++ comments? */
     if (Cplusplus==0)
         bigfsm['/'][COM1] = bigfsm['x'][COM1];
 }
References bigfsm, COM1, and Cplusplus.
Referenced by main().
foldline()
int foldline (Source * s)
Definition at line 502 of file lex.c.
 {
     while (s->inp+1 >= s->inl && fillbuf(s)!=EOF)
         ;
     if (s->inp[1] == '\n') {
         memmove(s->inp, s->inp+2, s->inl-s->inp+3);
         s->inl -= 2;
         return 1;
     }
     return 0;
 }
References EOF, fillbuf(), and memmove().
Referenced by gettokens().
gettokens()
int gettokens (Tokenrow * trp, int reset)
Definition at line 300 of file lex.c.
 {
     register int c, state, oldstate;
     register uchar *ip;
     register Token *tp, *maxp;
     int runelen;
     Source *s = cursource;
     int nmac = 0;
     tp = trp->lp;
     ip = s->inp;
     if (reset) {
         s->lineinc = 0;
         if (ip>=s->inl) {       /* nothing in buffer */
             s->inl = s->inb;
             fillbuf(s);
             ip = s->inp = s->inb;
         } else if (ip >= s->inb+(3*INS/4)) {
             memmove(s->inb, ip, 4+s->inl-ip);
             s->inl = s->inb+(s->inl-ip);
             ip = s->inp = s->inb;
         }
     }
     maxp = &trp->bp[trp->max];
     runelen = 1;
     for (;;) {
        continue2:
         if (tp>=maxp) {
             trp->lp = tp;
             tp = growtokenrow(trp);
             maxp = &trp->bp[trp->max];
         }
         tp->type = UNCLASS;
         tp->hideset = 0;
         tp->t = ip;
         tp->wslen = 0;
         tp->flag = 0;
         state = START;
         for (;;) {
             oldstate = state;
             c = *ip;
             if ((state = bigfsm[c][state]) >= 0) {
                 ip += runelen;
                 runelen = 1;
                 continue;
             }
             state = ~state;
         reswitch:
             switch (state&0177) {
             case S_SELF:
                 ip += runelen;
                 runelen = 1;
             case S_SELFB:
                 tp->type = GETACT(state);
                 tp->len = ip - tp->t;
                 tp++;
                 goto continue2;
             case S_NAME:    /* like S_SELFB but with nmac check */
                 tp->type = NAME;
                 tp->len = ip - tp->t;
                 nmac |= quicklook(tp->t[0], tp->len>1?tp->t[1]:0);
                 tp++;
                 goto continue2;
             case S_WS:
                 tp->wslen = ip - tp->t;
                 tp->t = ip;
                 state = START;
                 continue;
             default:
                 if ((state&QBSBIT)==0) {
                     ip += runelen;
                     runelen = 1;
                     continue;
                 }
                 state &= ~QBSBIT;
                 s->inp = ip;
                 if (c=='?') {   /* check trigraph */
                     if (trigraph(s)) {
                         state = oldstate;
                         continue;
                     }
                     goto reswitch;
                 }
                 if (c=='\\') { /* line-folding */
                     if (foldline(s)) {
                         s->lineinc++;
                         state = oldstate;
                         continue;
                     }
                     goto reswitch;
                 }
                 error(WARNING, "Lexical botch in cpp");
                 ip += runelen;
                 runelen = 1;
                 continue;
             case S_EOB:
                 s->inp = ip;
                 fillbuf(cursource);
                 state = oldstate;
                 continue;
             case S_EOF:
                 tp->type = END;
                 tp->len = 0;
                 s->inp = ip;
                 if (tp!=trp->bp && (tp-1)->type!=NL && cursource->fd!=-1)
                     error(WARNING,"No newline at end of file");
                 trp->lp = tp+1;
                 return nmac;
             case S_STNL:
                 error(ERROR, "Unterminated string or char const");
             case S_NL:
                 tp->t = ip;
                 tp->type = NL;
                 tp->len = 1;
                 tp->wslen = 0;
                 s->lineinc++;
                 s->inp = ip+1;
                 trp->lp = tp+1;
                 return nmac;
             case S_EOFSTR:
                 error(FATAL, "EOF in string or char constant");
                 break;
             case S_COMNL:
                 s->lineinc++;
                 state = COM2;
                 ip += runelen;
                 runelen = 1;
                 if (ip >= s->inb+(7*INS/8)) { /* very long comment */
                     memmove(tp->t, ip, 4+s->inl-ip);
                     s->inl -= ip-tp->t;
                     ip = tp->t+1;
                 }
                 continue;
             case S_EOFCOM:
                 error(WARNING, "EOF inside comment");
                 --ip;
             case S_COMMENT:
                 ++ip;
                 tp->t = ip;
                 tp->t[-1] = ' ';
                 tp->wslen = 1;
                 state = START;
                 continue;
             }
             break;
         }
         ip += runelen;
         runelen = 1;
         tp->len = ip - tp->t;
         tp++;
     }
 }
References bigfsm, COM2, cursource, END, ERROR, error(), FATAL, fillbuf(), foldline(), GETACT, growtokenrow(), INS, memmove(), NAME, NL, QBSBIT, quicklook, S_COMMENT, S_COMNL, S_EOB, S_EOF, S_EOFCOM, S_EOFSTR, S_NAME, S_NL, S_SELF, S_SELFB, S_STNL, S_WS, START, trigraph(), UNCLASS, and WARNING.
Referenced by doconcat(), gatherargs(), process(), and setup().
setsource()
Source* setsource (char * name, int fd, char * str)
Definition at line 541 of file lex.c.
 {
     Source *s = new(Source);
     int len;
     s->line = 1;
     s->lineinc = 0;
     s->fd = fd;
     s->filename = name;
     s->next = cursource;
     s->ifdepth = 0;
     cursource = s;
     /* slop at right for EOB */
     if (str) {
         len = strlen(str);
         s->inb = domalloc(len+4);
         s->inp = s->inb;
         strncpy((char *)s->inp, str, len);
     } else {
         s->inb = domalloc(INS+4);
         s->inp = s->inb;
         len = 0;
     }
     s->inl = s->inp+len;
     s->inl[0] = s->inl[1] = EOB;
     return s;
 }
References cursource, domalloc(), EOB, and INS.
Referenced by doconcat(), doinclude(), expandrow(), and setup().
trigraph()
int trigraph (Source * s)
Definition at line 464 of file lex.c.
 {
     int c;
     while (s->inp+2 >= s->inl && fillbuf(s)!=EOF)
         ;
     if (s->inp[1]!='?')
         return 0;
     c = 0;
     switch(s->inp[2]) {
     case '=':
         c = '#'; break;
     case '(':
         c = '['; break;
     case '/':
         c = '\\'; break;
     case ')':
         c = ']'; break;
     case '\'':
         c = '^'; break;
     case '<':
         c = '{'; break;
     case '!':
         c = '|'; break;
     case '>':
         c = '}'; break;
     case '-':
         c = '~'; break;
     }
     if (c) {
         *s->inp = c;
         memmove(s->inp+1, s->inp+3, s->inl-s->inp+2);
         s->inl -= 2;
     }
     return c;
 }
References EOF, fillbuf(), and memmove().
Referenced by gettokens().
unsetsource()
void unsetsource (void)
Definition at line 570 of file lex.c.
 {
     Source *s = cursource;
     if (s->fd>=0) {
         close(s->fd);
         dofree(s->inb);
     }
     cursource = s->next;
     dofree(s);
 }
References cursource, and dofree().
Referenced by doconcat(), expandrow(), process(), and setup().
Variable Documentation
bigfsm
short bigfsm[256][MAXSTATE]
Definition at line 236 of file lex.c.
Referenced by expandlex(), fixlex(), and gettokens().
fsm
struct fsm fsm[]
Definition at line 53 of file lex.c.
tokkind
int tokkind[256]
Definition at line 46 of file lex.c.
tottok
int tottok
Definition at line 45 of file lex.c.