ZEQ2-Lite: Tools/MinGW/include/oleidl.h File Reference
oleidl.h File Reference
#include <objfwd.h>
Data Structures
struct tagOIFI
struct tagOleMenuGroupWidths
struct tagOLEVERB
Macros
#define INTERFACE IParseDisplayName
#define INTERFACE IOleContainer
#define INTERFACE IOleItemContainer
#define INTERFACE IOleClientSite
#define INTERFACE IOleObject
#define INTERFACE IOleWindow
#define INTERFACE IOleInPlaceUIWindow
#define INTERFACE IOleInPlaceObject
#define INTERFACE IOleInPlaceActiveObject
#define INTERFACE IOleInPlaceFrame
#define INTERFACE IOleInPlaceSite
#define INTERFACE IOleAdviseHolder
#define INTERFACE IDropSource
#define INTERFACE IDropTarget
#define INTERFACE IViewObject
#define INTERFACE IViewObject2
#define INTERFACE IOleCache
#define INTERFACE IOleCache2
#define INTERFACE IOleCacheControl
#define MK_ALT 32
Typedefs
typedef RECT BORDERWIDTHS
typedef HGLOBAL HOLEMENU
typedef IEnumOLEVERB IEnumOleVerb
typedef LPRECT LPBORDERWIDTHS
typedef LPCRECT LPCBORDERWIDTHS
typedef _COM_interface IDropSource * LPDROPSOURCE
typedef _COM_interface IDropTarget * LPDROPTARGET
typedef _COM_interface IEnumOleUndoUnits * LPENUMOLEUNDOUNITS
typedef _COM_interface IEnumOLEVERB * LPENUMOLEVERB
typedef _COM_interface IOleAdviseHolder * LPOLEADVISEHOLDER
typedef _COM_interface IOleCache * LPOLECACHE
typedef _COM_interface IOleCache2 * LPOLECACHE2
typedef _COM_interface IOleCacheControl * LPOLECACHECONTROL
typedef _COM_interface IOleClientSite * LPOLECLIENTSITE
typedef _COM_interface IOleContainer * LPOLECONTAINER
typedef _COM_interface IOleInPlaceActiveObject * LPOLEINPLACEACTIVEOBJECT
typedef _COM_interface IOleInPlaceFrame * LPOLEINPLACEFRAME
typedef struct OLEINPLACEFRAMEINFO * LPOLEINPLACEFRAMEINFO
typedef _COM_interface IOleInPlaceUIWindow * LPOLEINPLACEUIWINDOW
typedef struct OLEMENUGROUPWIDTHS * LPOLEMENUGROUPWIDTHS
typedef _COM_interface IOleObject * LPOLEOBJECT
typedef struct OLEVERB * LPOLEVERB
typedef _COM_interface IOleWindow * LPOLEWINDOW
typedef _COM_interface IParseDisplayName * LPPARSEDISPLAYNAME
typedef _COM_interface IViewObject * LPVIEWOBJECT
typedef _COM_interface IViewObject2 * LPVIEWOBJECT2
Enumerations
enum tagBINDSPEED { BINDSPEED_INDEFINITE =1, BINDSPEED_MODERATE, BINDSPEED_IMMEDIATE }
enum tagDROPEFFECT {
DROPEFFECT_NONE =0, DROPEFFECT_COPY =1, DROPEFFECT_MOVE =2, DROPEFFECT_LINK =4,
DROPEFFECT_SCROLL =0x80000000
}
enum tagOLECLOSE { OLECLOSE_SAVEIFDIRTY, OLECLOSE_NOSAVE, OLECLOSE_PROMPTSAVE }
enum tagOLEGETMONIKER { OLEGETMONIKER_ONLYIFTHERE =1, OLEGETMONIKER_FORCEASSIGN, OLEGETMONIKER_UNASSIGN, OLEGETMONIKER_TEMPFORUSER }
enum tagOLEWHICHMK { OLEWHICHMK_CONTAINER =1, OLEWHICHMK_OBJREL, OLEWHICHMK_OBJFULL }
enum tagUSERCLASSTYPE { USERCLASSTYPE_FULL =1, USERCLASSTYPE_SHORT, USERCLASSTYPE_APPNAME }
Functions
typedef BOOL (CALLBACK *__IView_pfncont)(DWORD)
DECLARE_ENUMERATOR (OLEVERB)
DECLARE_INTERFACE_ (IDropSource, IUnknown)
DECLARE_INTERFACE_ (IDropTarget, IUnknown)
DECLARE_INTERFACE_ (IOleAdviseHolder, IUnknown)
DECLARE_INTERFACE_ (IOleCache, IUnknown)
DECLARE_INTERFACE_ (IOleCache2, IOleCache)
DECLARE_INTERFACE_ (IOleCacheControl, IUnknown)
DECLARE_INTERFACE_ (IOleClientSite, IUnknown)
DECLARE_INTERFACE_ (IOleContainer, IParseDisplayName)
DECLARE_INTERFACE_ (IOleInPlaceActiveObject, IOleWindow)
DECLARE_INTERFACE_ (IOleInPlaceFrame, IOleInPlaceUIWindow)
DECLARE_INTERFACE_ (IOleInPlaceObject, IOleWindow)
DECLARE_INTERFACE_ (IOleInPlaceSite, IOleWindow)
DECLARE_INTERFACE_ (IOleInPlaceUIWindow, IOleWindow)
DECLARE_INTERFACE_ (IOleItemContainer, IOleContainer)
DECLARE_INTERFACE_ (IOleObject, IUnknown)
DECLARE_INTERFACE_ (IOleWindow, IUnknown)
DECLARE_INTERFACE_ (IParseDisplayName, IUnknown)
DECLARE_INTERFACE_ (IViewObject, IUnknown)
DECLARE_INTERFACE_ (IViewObject2, IViewObject)
Variables
const EXTERN_C IID IID_IDropSource
const EXTERN_C IID IID_IDropTarget
const EXTERN_C IID IID_IOleAdviseHolder
const EXTERN_C IID IID_IOleCache
const EXTERN_C IID IID_IOleCache2
const EXTERN_C IID IID_IOleCacheControl
const EXTERN_C IID IID_IOleClientSite
const EXTERN_C IID IID_IOleContainer
const EXTERN_C IID IID_IOleInPlaceActiveObject
const EXTERN_C IID IID_IOleInPlaceFrame
const EXTERN_C IID IID_IOleInPlaceObject
const EXTERN_C IID IID_IOleInPlaceSite
const EXTERN_C IID IID_IOleInPlaceUIWindow
const EXTERN_C IID IID_IOleItemContainer
const EXTERN_C IID IID_IOleObject
const EXTERN_C IID IID_IOleWindow
const EXTERN_C IID IID_IParseDisplayName
const EXTERN_C IID IID_IViewObject
const EXTERN_C IID IID_IViewObject2
Macro Definition Documentation
INTERFACE [1/19]
#define INTERFACE IParseDisplayName
Definition at line 560 of file oleidl.h.
INTERFACE [2/19]
#define INTERFACE IOleContainer
Definition at line 560 of file oleidl.h.
INTERFACE [3/19]
#define INTERFACE IOleItemContainer
Definition at line 560 of file oleidl.h.
INTERFACE [4/19]
#define INTERFACE IOleClientSite
Definition at line 560 of file oleidl.h.
INTERFACE [5/19]
#define INTERFACE IOleObject
Definition at line 560 of file oleidl.h.
INTERFACE [6/19]
#define INTERFACE IOleWindow
Definition at line 560 of file oleidl.h.
INTERFACE [7/19]
#define INTERFACE IOleInPlaceUIWindow
Definition at line 560 of file oleidl.h.
INTERFACE [8/19]
#define INTERFACE IOleInPlaceObject
Definition at line 560 of file oleidl.h.
INTERFACE [9/19]
#define INTERFACE IOleInPlaceActiveObject
Definition at line 560 of file oleidl.h.
INTERFACE [10/19]
#define INTERFACE IOleInPlaceFrame
Definition at line 560 of file oleidl.h.
INTERFACE [11/19]
#define INTERFACE IOleInPlaceSite
Definition at line 560 of file oleidl.h.
INTERFACE [12/19]
#define INTERFACE IOleAdviseHolder
Definition at line 560 of file oleidl.h.
INTERFACE [13/19]
#define INTERFACE IDropSource
Definition at line 560 of file oleidl.h.
INTERFACE [14/19]
#define INTERFACE IDropTarget
Definition at line 560 of file oleidl.h.
INTERFACE [15/19]
#define INTERFACE IViewObject
Definition at line 560 of file oleidl.h.
INTERFACE [16/19]
#define INTERFACE IViewObject2
Definition at line 560 of file oleidl.h.
INTERFACE [17/19]
#define INTERFACE IOleCache
Definition at line 560 of file oleidl.h.
INTERFACE [18/19]
#define INTERFACE IOleCache2
Definition at line 560 of file oleidl.h.
INTERFACE [19/19]
#define INTERFACE IOleCacheControl
Definition at line 560 of file oleidl.h.
MK_ALT
#define MK_ALT 32
Definition at line 13 of file oleidl.h.
Typedef Documentation
BORDERWIDTHS
typedef RECT BORDERWIDTHS
Definition at line 82 of file oleidl.h.
HOLEMENU
typedef HGLOBAL HOLEMENU
Definition at line 70 of file oleidl.h.
IEnumOleVerb
typedef IEnumOLEVERB IEnumOleVerb
Definition at line 94 of file oleidl.h.
LPBORDERWIDTHS
typedef LPRECT LPBORDERWIDTHS
Definition at line 83 of file oleidl.h.
LPCBORDERWIDTHS
typedef LPCRECT LPCBORDERWIDTHS
Definition at line 84 of file oleidl.h.
LPDROPSOURCE
typedef _COM_interface IDropSource* LPDROPSOURCE
Definition at line 20 of file oleidl.h.
LPDROPTARGET
typedef _COM_interface IDropTarget* LPDROPTARGET
Definition at line 19 of file oleidl.h.
LPENUMOLEUNDOUNITS
typedef _COM_interface IEnumOleUndoUnits* LPENUMOLEUNDOUNITS
Definition at line 21 of file oleidl.h.
LPENUMOLEVERB
typedef _COM_interface IEnumOLEVERB* LPENUMOLEVERB
Definition at line 22 of file oleidl.h.
LPOLEADVISEHOLDER
typedef _COM_interface IOleAdviseHolder* LPOLEADVISEHOLDER
Definition at line 27 of file oleidl.h.
LPOLECACHE
typedef _COM_interface IOleCache* LPOLECACHE
Definition at line 30 of file oleidl.h.
LPOLECACHE2
typedef _COM_interface IOleCache2* LPOLECACHE2
Definition at line 31 of file oleidl.h.
LPOLECACHECONTROL
typedef _COM_interface IOleCacheControl* LPOLECACHECONTROL
Definition at line 32 of file oleidl.h.
LPOLECLIENTSITE
typedef _COM_interface IOleClientSite* LPOLECLIENTSITE
Definition at line 17 of file oleidl.h.
LPOLECONTAINER
typedef _COM_interface IOleContainer* LPOLECONTAINER
Definition at line 16 of file oleidl.h.
LPOLEINPLACEACTIVEOBJECT
typedef _COM_interface IOleInPlaceActiveObject* LPOLEINPLACEACTIVEOBJECT
Definition at line 25 of file oleidl.h.
LPOLEINPLACEFRAME
typedef _COM_interface IOleInPlaceFrame* LPOLEINPLACEFRAME
Definition at line 26 of file oleidl.h.
LPOLEINPLACEFRAMEINFO
typedef struct OLEINPLACEFRAMEINFO* LPOLEINPLACEFRAMEINFO
LPOLEINPLACEUIWINDOW
typedef _COM_interface IOleInPlaceUIWindow* LPOLEINPLACEUIWINDOW
Definition at line 24 of file oleidl.h.
LPOLEMENUGROUPWIDTHS
typedef struct OLEMENUGROUPWIDTHS* LPOLEMENUGROUPWIDTHS
LPOLEOBJECT
typedef struct _OLEOBJECT * LPOLEOBJECT
Definition at line 18 of file oleidl.h.
LPOLEVERB
typedef struct OLEVERB* LPOLEVERB
LPOLEWINDOW
typedef _COM_interface IOleWindow* LPOLEWINDOW
Definition at line 23 of file oleidl.h.
LPPARSEDISPLAYNAME
typedef _COM_interface IParseDisplayName* LPPARSEDISPLAYNAME
Definition at line 15 of file oleidl.h.
LPVIEWOBJECT
typedef _COM_interface IViewObject* LPVIEWOBJECT
Definition at line 28 of file oleidl.h.
LPVIEWOBJECT2
typedef _COM_interface IViewObject2* LPVIEWOBJECT2
Definition at line 29 of file oleidl.h.
Enumeration Type Documentation
tagBINDSPEED
enum tagBINDSPEED
Enumerator
BINDSPEED_INDEFINITE
BINDSPEED_MODERATE
BINDSPEED_IMMEDIATE
Definition at line 34 of file oleidl.h.
 {
     BINDSPEED_INDEFINITE=1,
     BINDSPEED_MODERATE,
     BINDSPEED_IMMEDIATE
 } BINDSPEED;
tagDROPEFFECT
enum tagDROPEFFECT
Enumerator
DROPEFFECT_NONE
DROPEFFECT_COPY
DROPEFFECT_MOVE
DROPEFFECT_LINK
DROPEFFECT_SCROLL
Definition at line 60 of file oleidl.h.
{
     DROPEFFECT_NONE=0,
     DROPEFFECT_COPY=1,
     DROPEFFECT_MOVE=2,
     DROPEFFECT_LINK=4,
     DROPEFFECT_SCROLL=0x80000000
 } DROPEFFECT;
tagOLECLOSE
enum tagOLECLOSE
Enumerator
OLECLOSE_SAVEIFDIRTY
OLECLOSE_NOSAVE
OLECLOSE_PROMPTSAVE
Definition at line 71 of file oleidl.h.
{
     OLECLOSE_SAVEIFDIRTY,
     OLECLOSE_NOSAVE,
     OLECLOSE_PROMPTSAVE
 } OLECLOSE;
tagOLEGETMONIKER
enum tagOLEGETMONIKER
Enumerator
OLEGETMONIKER_ONLYIFTHERE
OLEGETMONIKER_FORCEASSIGN
OLEGETMONIKER_UNASSIGN
OLEGETMONIKER_TEMPFORUSER
Definition at line 45 of file oleidl.h.
{
     OLEGETMONIKER_ONLYIFTHERE=1,
     OLEGETMONIKER_FORCEASSIGN,
     OLEGETMONIKER_UNASSIGN,
     OLEGETMONIKER_TEMPFORUSER
 } OLEGETMONIKER;
tagOLEWHICHMK
enum tagOLEWHICHMK
Enumerator
OLEWHICHMK_CONTAINER
OLEWHICHMK_OBJREL
OLEWHICHMK_OBJFULL
Definition at line 40 of file oleidl.h.
{
     OLEWHICHMK_CONTAINER=1,
     OLEWHICHMK_OBJREL,
     OLEWHICHMK_OBJFULL
 } OLEWHICHMK;
tagUSERCLASSTYPE
enum tagUSERCLASSTYPE
Enumerator
USERCLASSTYPE_FULL
USERCLASSTYPE_SHORT
USERCLASSTYPE_APPNAME
Definition at line 51 of file oleidl.h.
{
     USERCLASSTYPE_FULL=1,
     USERCLASSTYPE_SHORT,
     USERCLASSTYPE_APPNAME
 } USERCLASSTYPE;
Function Documentation
BOOL()
typedef BOOL (CALLBACK * __IView_pfncont)
Referenced by DECLARE_INTERFACE_().
DECLARE_ENUMERATOR()
DECLARE_ENUMERATOR (OLEVERB)
DECLARE_INTERFACE_() [1/19]
DECLARE_INTERFACE_ (IDropSource , IUnknown)
Definition at line 402 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(QueryContinueDrag)(THIS_ BOOL,DWORD) PURE;
     STDMETHOD(GiveFeedback)(THIS_ DWORD) PURE;
 };
References BOOL(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [2/19]
DECLARE_INTERFACE_ (IDropTarget , IUnknown)
Definition at line 422 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(DragEnter)(THIS_ LPDATAOBJECT,DWORD,POINTL,PDWORD) PURE;
     STDMETHOD(DragOver)(THIS_ DWORD,POINTL,PDWORD) PURE;
     STDMETHOD(DragLeave)(THIS) PURE;
     STDMETHOD(Drop)(THIS_ LPDATAOBJECT,DWORD,POINTL,PDWORD) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [3/19]
DECLARE_INTERFACE_ (IOleAdviseHolder , IUnknown)
Definition at line 374 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Advise)(THIS_ LPADVISESINK,PDWORD) PURE;
     STDMETHOD(Unadvise)(THIS_ DWORD) PURE;
     STDMETHOD(EnumAdvise)(THIS_ LPENUMSTATDATA*) PURE;
     STDMETHOD(SendOnRename)(THIS_ LPMONIKER) PURE;
     STDMETHOD(SendOnSave)(THIS) PURE;
     STDMETHOD(SendOnClose)(THIS) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [4/19]
DECLARE_INTERFACE_ (IOleCache , IUnknown)
Definition at line 505 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Cache)(THIS_ FORMATETC*,DWORD,DWORD*) PURE;
     STDMETHOD(Uncache)(THIS_ DWORD) PURE;
     STDMETHOD(EnumCache)(THIS_ IEnumSTATDATA**);
     STDMETHOD(InitCache)(THIS_ LPDATAOBJECT);
     STDMETHOD(SetData)(THIS_ FORMATETC*,STGMEDIUM*,BOOL);
 };
References BOOL(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [5/19]
DECLARE_INTERFACE_ (IOleCache2 , IOleCache)
Definition at line 531 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Cache)(THIS_ FORMATETC*,DWORD,DWORD*) PURE;
     STDMETHOD(Uncache)(THIS_ DWORD) PURE;
     STDMETHOD(EnumCache)(THIS_ IEnumSTATDATA**) PURE;
     STDMETHOD(InitCache)(THIS_ LPDATAOBJECT) PURE;
     STDMETHOD(SetData)(THIS_ FORMATETC*,STGMEDIUM*,BOOL) PURE;
     STDMETHOD(UpdateCache)(THIS_ LPDATAOBJECT,DWORD,LPVOID) PURE;
     STDMETHOD(DiscardCache)(THIS_ DWORD) PURE;
 };
References BOOL(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [6/19]
DECLARE_INTERFACE_ (IOleCacheControl , IUnknown)
Definition at line 561 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(OnRun)(THIS_ LPDATAOBJECT) PURE;
     STDMETHOD(OnStop)(THIS) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [7/19]
DECLARE_INTERFACE_ (IOleClientSite , IUnknown)
Definition at line 157 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(SaveObject)(THIS) PURE;
     STDMETHOD(GetMoniker)(THIS_ DWORD,DWORD,LPMONIKER*) PURE;
     STDMETHOD(GetContainer)(THIS_ LPOLECONTAINER*) PURE;
     STDMETHOD(ShowObject)(THIS) PURE;
     STDMETHOD(OnShowWindow)(THIS_ BOOL) PURE;
     STDMETHOD(RequestNewObjectLayout)(THIS) PURE;
 };
References BOOL(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [8/19]
DECLARE_INTERFACE_ (IOleContainer , IParseDisplayName)
Definition at line 116 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(ParseDisplayName)(THIS_ IBindCtx*,LPOLESTR,ULONG*,IMoniker**) PURE;
     STDMETHOD(EnumObjects)(THIS_ DWORD,IEnumUnknown**) PURE;
     STDMETHOD(LockContainer)(THIS_ BOOL) PURE;
 };
References BOOL(), EnumObjects(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [9/19]
DECLARE_INTERFACE_ (IOleInPlaceActiveObject , IOleWindow)
Definition at line 295 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetWindow)(THIS_ HWND*) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
     STDMETHOD(TranslateAccelerator)(THIS_ LPMSG) PURE;
     STDMETHOD(OnFrameWindowActivate)(THIS_ BOOL) PURE;
     STDMETHOD(OnDocWindowActivate)(THIS_ BOOL) PURE;
     STDMETHOD(ResizeBorder)(THIS_ LPCRECT,LPOLEINPLACEUIWINDOW,BOOL) PURE;
     STDMETHOD(EnableModeless)(THIS_ BOOL) PURE;
 };
References BOOL(), GetWindow(), HWND, LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, THIS_, and TranslateAccelerator.
DECLARE_INTERFACE_() [10/19]
DECLARE_INTERFACE_ (IOleInPlaceFrame , IOleInPlaceUIWindow)
Definition at line 312 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetWindow)(THIS_ HWND*) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
     STDMETHOD(GetBorder)(THIS_ LPRECT) PURE;
     STDMETHOD(RequestBorderSpace)(THIS_ LPCBORDERWIDTHS) PURE;
     STDMETHOD(SetBorderSpace)(THIS_ LPCBORDERWIDTHS) PURE;
     STDMETHOD(SetActiveObject)(THIS_ LPOLEINPLACEACTIVEOBJECT,LPCOLESTR) PURE;
     STDMETHOD(InsertMenus)(THIS_ HMENU,LPOLEMENUGROUPWIDTHS) PURE;
     STDMETHOD(SetMenu)(THIS_ HMENU,HOLEMENU,HWND) PURE;
     STDMETHOD(RemoveMenus)(THIS_ HMENU) PURE;
     STDMETHOD(SetStatusText)(THIS_ LPCOLESTR) PURE;
     STDMETHOD(EnableModeless)(THIS_ BOOL) PURE;
     STDMETHOD(TranslateAccelerator)(THIS_ LPMSG,WORD) PURE;
 };
References BOOL(), GetWindow(), HMENU, HWND, PURE, SetMenu(), STDMETHOD, STDMETHOD_, THIS, THIS_, and TranslateAccelerator.
DECLARE_INTERFACE_() [11/19]
DECLARE_INTERFACE_ (IOleInPlaceObject , IOleWindow)
Definition at line 279 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetWindow)(THIS_ HWND*) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
     STDMETHOD(InPlaceDeactivate)(THIS) PURE;
     STDMETHOD(UIDeactivate)(THIS) PURE;
     STDMETHOD(SetObjectRects)(THIS_ LPCRECT,LPCRECT) PURE;
     STDMETHOD(ReactivateAndUndo)(THIS) PURE;
 };
References BOOL(), GetWindow(), HWND, LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [12/19]
DECLARE_INTERFACE_ (IOleInPlaceSite , IOleWindow)
Definition at line 352 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetWindow)(THIS_ HWND*) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
     STDMETHOD(CanInPlaceActivate)(THIS) PURE;
     STDMETHOD(OnInPlaceActivate)(THIS) PURE;
     STDMETHOD(OnUIActivate)(THIS) PURE;
     STDMETHOD(GetWindowContext)(THIS_ IOleInPlaceFrame**,IOleInPlaceUIWindow**,LPRECT,LPRECT,LPOLEINPLACEFRAMEINFO) PURE;
     STDMETHOD(Scroll)(THIS_ SIZE) PURE;
     STDMETHOD(OnUIDeactivate)(THIS_ BOOL) PURE;
     STDMETHOD(OnInPlaceDeactivate)(THIS) PURE;
     STDMETHOD(DiscardUndoState)(THIS) PURE;
     STDMETHOD(DeactivateAndUndo)(THIS) PURE;
     STDMETHOD(OnPosRectChange)(THIS_ LPCRECT) PURE;
 };
References BOOL(), GetWindow(), HWND, LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [13/19]
DECLARE_INTERFACE_ (IOleInPlaceUIWindow , IOleWindow)
Definition at line 263 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetWindow)(THIS_ HWND*) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
     STDMETHOD(GetBorder)(THIS_ LPRECT) PURE;
     STDMETHOD(RequestBorderSpace)(THIS_ LPCBORDERWIDTHS) PURE;
     STDMETHOD(SetBorderSpace)(THIS_ LPCBORDERWIDTHS) PURE;
     STDMETHOD(SetActiveObject)(THIS_ LPOLEINPLACEACTIVEOBJECT,LPCOLESTR) PURE;
 };
References BOOL(), GetWindow(), HWND, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [14/19]
DECLARE_INTERFACE_ (IOleItemContainer , IOleContainer)
Definition at line 129 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(ParseDisplayName)(THIS_ IBindCtx*,LPOLESTR,ULONG*,IMoniker**) PURE;
     STDMETHOD(EnumObjects)(THIS_ DWORD,IEnumUnknown**) PURE;
     STDMETHOD(LockContainer)(THIS_ BOOL) PURE;
     STDMETHOD(GetObject)(THIS_ LPOLESTR,DWORD,IBindCtx*,REFIID,void**) PURE;
     STDMETHOD(GetObjectStorage)(THIS_ LPOLESTR,IBindCtx*,REFIID,void**) PURE;
     STDMETHOD(IsRunning)(THIS_ LPOLESTR) PURE;
 };
References BOOL(), EnumObjects(), GetObject, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [15/19]
DECLARE_INTERFACE_ (IOleObject , IUnknown)
Definition at line 185 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(SetClientSite)(THIS_ LPOLECLIENTSITE) PURE;
     STDMETHOD(GetClientSite)(THIS_ LPOLECLIENTSITE*) PURE;
     STDMETHOD(SetHostNames)(THIS_ LPCOLESTR,LPCOLESTR) PURE;
     STDMETHOD(Close)(THIS_ DWORD) PURE;
     STDMETHOD(SetMoniker)(THIS_ DWORD,LPMONIKER) PURE;
     STDMETHOD(GetMoniker)(THIS_ DWORD,DWORD,LPMONIKER*) PURE;
     STDMETHOD(InitFromData)(THIS_ LPDATAOBJECT,BOOL,DWORD) PURE;
     STDMETHOD(GetClipboardData)(THIS_ DWORD,LPDATAOBJECT*) PURE;
     STDMETHOD(DoVerb)(THIS_ LONG,LPMSG,LPOLECLIENTSITE,LONG,HWND,LPCRECT) PURE;
     STDMETHOD(EnumVerbs)(THIS_ LPENUMOLEVERB*) PURE;
     STDMETHOD(Update)(THIS) PURE;
     STDMETHOD(IsUpToDate)(THIS) PURE;
     STDMETHOD(GetUserClassID)(THIS_ LPCLSID) PURE;
     STDMETHOD(GetUserType)(THIS_ DWORD,LPOLESTR*) PURE;
     STDMETHOD(SetExtent)(THIS_ DWORD,SIZEL*) PURE;
     STDMETHOD(GetExtent)(THIS_ DWORD,SIZEL*) PURE;
     STDMETHOD(Advise)(THIS_ LPADVISESINK,PDWORD) PURE;
     STDMETHOD(Unadvise)(THIS_ DWORD) PURE;
     STDMETHOD(EnumAdvise)(THIS_ LPENUMSTATDATA*) PURE;
     STDMETHOD(GetMiscStatus)(THIS_ DWORD,PDWORD) PURE;
     STDMETHOD(SetColorScheme)(THIS_ LPLOGPALETTE) PURE;
 };
References BOOL(), GetClipboardData(), HWND, LONG, LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [16/19]
DECLARE_INTERFACE_ (IOleWindow , IUnknown)
Definition at line 243 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetWindow)(THIS_ HWND*) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
 };
References BOOL(), GetWindow(), HWND, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [17/19]
DECLARE_INTERFACE_ (IParseDisplayName , IUnknown)
Definition at line 98 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(ParseDisplayName)(THIS_ IBindCtx*,LPOLESTR,ULONG*,IMoniker**) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [18/19]
DECLARE_INTERFACE_ (IViewObject , IUnknown)
Definition at line 447 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Draw)(THIS_ DWORD,LONG,PVOID,DVTARGETDEVICE*,HDC,HDC,LPCRECTL,LPCRECTL,__IView_pfncont pfnContinue,DWORD) PURE;
     STDMETHOD(GetColorSet)(THIS_ DWORD,LONG,PVOID,DVTARGETDEVICE*,HDC,LPLOGPALETTE*) PURE;
     STDMETHOD(Freeze)(THIS_ DWORD,LONG,PVOID,PDWORD) PURE;
     STDMETHOD(Unfreeze)(THIS_ DWORD) PURE;
     STDMETHOD(SetAdvise)(THIS_ DWORD,DWORD,IAdviseSink*) PURE;
     STDMETHOD(GetAdvise)(THIS_ PDWORD,PDWORD,IAdviseSink**) PURE;
 };
References LONG, LPCRECTL, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [19/19]
DECLARE_INTERFACE_ (IViewObject2 , IViewObject)
Definition at line 475 of file oleidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Draw)(THIS_ DWORD,LONG,PVOID,DVTARGETDEVICE*,HDC,HDC,LPCRECTL,LPCRECTL,__IView_pfncont pfnContinue,DWORD) PURE;
     STDMETHOD(GetColorSet)(THIS_ DWORD,LONG,PVOID,DVTARGETDEVICE*,HDC,LPLOGPALETTE*) PURE;
     STDMETHOD(Freeze)(THIS_ DWORD,LONG,PVOID,PDWORD) PURE;
     STDMETHOD(Unfreeze)(THIS_ DWORD) PURE;
     STDMETHOD(SetAdvise)(THIS_ DWORD,DWORD,IAdviseSink*) PURE;
     STDMETHOD(GetAdvise)(THIS_ PDWORD,PDWORD,IAdviseSink**) PURE;
     STDMETHOD(GetExtent)(THIS_ DWORD,LONG,DVTARGETDEVICE*,LPSIZEL) PURE;
 };
References LONG, LPCRECTL, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
Variable Documentation
IID_IDropSource
const EXTERN_C IID IID_IDropSource
Definition at line 385 of file oleidl.h.
IID_IDropTarget
const EXTERN_C IID IID_IDropTarget
Definition at line 409 of file oleidl.h.
IID_IOleAdviseHolder
const EXTERN_C IID IID_IOleAdviseHolder
Definition at line 369 of file oleidl.h.
IID_IOleCache
const EXTERN_C IID IID_IOleCache
Definition at line 487 of file oleidl.h.
IID_IOleCache2
const EXTERN_C IID IID_IOleCache2
Definition at line 515 of file oleidl.h.
IID_IOleCacheControl
const EXTERN_C IID IID_IOleCacheControl
Definition at line 543 of file oleidl.h.
IID_IOleClientSite
const EXTERN_C IID IID_IOleClientSite
Definition at line 140 of file oleidl.h.
IID_IOleContainer
const EXTERN_C IID IID_IOleContainer
Definition at line 104 of file oleidl.h.
IID_IOleInPlaceActiveObject
const EXTERN_C IID IID_IOleInPlaceActiveObject
Definition at line 290 of file oleidl.h.
IID_IOleInPlaceFrame
const EXTERN_C IID IID_IOleInPlaceFrame
Definition at line 307 of file oleidl.h.
IID_IOleInPlaceObject
const EXTERN_C IID IID_IOleInPlaceObject
Definition at line 274 of file oleidl.h.
IID_IOleInPlaceSite
const EXTERN_C IID IID_IOleInPlaceSite
Definition at line 329 of file oleidl.h.
IID_IOleInPlaceUIWindow
const EXTERN_C IID IID_IOleInPlaceUIWindow
Definition at line 250 of file oleidl.h.
IID_IOleItemContainer
const EXTERN_C IID IID_IOleItemContainer
Definition at line 124 of file oleidl.h.
IID_IOleObject
const EXTERN_C IID IID_IOleObject
Definition at line 168 of file oleidl.h.
IID_IOleWindow
const EXTERN_C IID IID_IOleWindow
Definition at line 211 of file oleidl.h.
IID_IParseDisplayName
const EXTERN_C IID IID_IParseDisplayName
Definition at line 96 of file oleidl.h.
IID_IViewObject
const EXTERN_C IID IID_IViewObject
Definition at line 445 of file oleidl.h.
IID_IViewObject2
const EXTERN_C IID IID_IViewObject2
Definition at line 458 of file oleidl.h.