ZEQ2-Lite: Source/Engine/tools/lcc/cpp/tokens.c File Reference
tokens.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cpp.h"
Functions
void adjustrow (Tokenrow *trp, int nt)
int comparetokens (Tokenrow *tr1, Tokenrow *tr2)
Tokenrow * copytokenrow (Tokenrow *dtr, Tokenrow *str)
void flushout (void)
Token * growtokenrow (Tokenrow *trp)
void insertrow (Tokenrow *dtr, int ntok, Tokenrow *str)
void makespace (Tokenrow *trp)
void maketokenrow (int size, Tokenrow *trp)
void movetokenrow (Tokenrow *dtr, Tokenrow *str)
uchar * newstring (uchar *s, int l, int o)
Tokenrow * normtokenrow (Tokenrow *trp)
char * outnum (char *p, int n)
void peektokens (Tokenrow *trp, char *str)
void puttokens (Tokenrow *trp)
void setempty (Tokenrow *trp)
Variables
static char * wbp = wbuf
static char wbuf [2 *OBS]
static const char wstab []
Function Documentation
adjustrow()
void adjustrow (Tokenrow * trp, int nt)
Definition at line 195 of file tokens.c.
 {
     int nby, size;
     if (nt==0)
         return;
     size = (trp->lp - trp->bp) + nt;
     while (size > trp->max)
         growtokenrow(trp);
     /* nby = sizeof(Token) * (trp->lp - trp->tp); */
     nby = (char *)trp->lp - (char *)trp->tp;
     if (nby)
         memmove(trp->tp+nt, trp->tp, nby);
     trp->lp += nt;
 }
References growtokenrow(), and memmove().
Referenced by gatherargs(), and insertrow().
comparetokens()
int comparetokens (Tokenrow * tr1, Tokenrow * tr2)
Definition at line 107 of file tokens.c.
 {
     Token *tp1, *tp2;
     tp1 = tr1->tp;
     tp2 = tr2->tp;
     if (tr1->lp-tp1 != tr2->lp-tp2)
         return 1;
     for (; tp1<tr1->lp ; tp1++, tp2++) {
         if (tp1->type != tp2->type
          || (tp1->wslen==0) != (tp2->wslen==0)
          || tp1->len != tp2->len
          || strncmp((char*)tp1->t, (char*)tp2->t, tp1->len)!=0)
             return 1;
     }
     return 0;
 }
Referenced by dodefine().
copytokenrow()
Tokenrow* copytokenrow (Tokenrow * dtr, Tokenrow * str)
Definition at line 216 of file tokens.c.
 {
     int len = rowlen(str);
     maketokenrow(len, dtr);
     movetokenrow(dtr, str);
     dtr->lp += len;
     return dtr;
 }
References maketokenrow(), movetokenrow(), and rowlen.
Referenced by expand(), and substargs().
flushout()
void flushout (void)
Definition at line 328 of file tokens.c.
 {
     if (wbp>wbuf) {
         write(1, wbuf, wbp-wbuf);
         wbp = wbuf;
     }
 }
References wbp, and wbuf.
Referenced by main(), peektokens(), and puttokens().
growtokenrow()
Token* growtokenrow (Tokenrow * trp)
Definition at line 89 of file tokens.c.
 {
     int ncur = trp->tp - trp->bp;
     int nlast = trp->lp - trp->bp;
     trp->max = 3*trp->max/2 + 1;
     trp->bp = (Token *)realloc(trp->bp, trp->max*sizeof(Token));
     if (trp->bp == NULL)
         error(FATAL, "Out of memory from realloc");
     trp->lp = &trp->bp[nlast];
     trp->tp = &trp->bp[ncur];
     return trp->lp;
 }
References error(), FATAL, and NULL.
Referenced by adjustrow(), dodefine(), and gettokens().
insertrow()
void insertrow (Tokenrow * dtr, int ntok, Tokenrow * str)
Definition at line 131 of file tokens.c.
 {
     int nrtok = rowlen(str);
     dtr->tp += ntok;
     adjustrow(dtr, nrtok-ntok);
     dtr->tp -= ntok;
     movetokenrow(dtr, str);
     makespace(dtr);
     dtr->tp += nrtok;
     makespace(dtr);
 }
References adjustrow(), makespace(), movetokenrow(), and rowlen.
Referenced by doconcat(), expand(), and substargs().
makespace()
void makespace (Tokenrow * trp)
Definition at line 148 of file tokens.c.
 {
     uchar *tt;
     Token *tp = trp->tp;
     if (tp >= trp->lp)
         return;
     if (tp->wslen) {
         if (tp->flag&XPWS
          && (wstab[tp->type] || (trp->tp>trp->bp && wstab[(tp-1)->type]))) {
             tp->wslen = 0;
             return;
         }
         tp->t[-1] = ' ';
         return;
     }
     if (wstab[tp->type] || (trp->tp>trp->bp && wstab[(tp-1)->type]))
         return;
     tt = newstring(tp->t, tp->len, 1);
     *tt++ = ' ';
     tp->t = tt;
     tp->wslen = 1;
     tp->flag |= XPWS;
 }
References newstring(), wstab, and XPWS.
Referenced by doconcat(), gatherargs(), and insertrow().
maketokenrow()
void maketokenrow (int size, Tokenrow * trp)
Definition at line 77 of file tokens.c.
 {
     trp->max = size;
     if (size>0)
         trp->bp = (Token *)domalloc(size*sizeof(Token));
     else
         trp->bp = NULL;
     trp->tp = trp->bp;
     trp->lp = trp->bp;
 }
References domalloc(), and NULL.
Referenced by copytokenrow(), doconcat(), dodefine(), main(), normtokenrow(), and setup().
movetokenrow()
void movetokenrow (Tokenrow * dtr, Tokenrow * str)
Definition at line 179 of file tokens.c.
 {
     int nby;
     /* nby = sizeof(Token) * (str->lp - str->bp); */
     nby = (char *)str->lp - (char *)str->bp;
     memmove(dtr->tp, str->bp, nby);
 }
References memmove().
Referenced by copytokenrow(), and insertrow().
newstring()
uchar* newstring (uchar * s, int l, int o)
Definition at line 364 of file tokens.c.
 {
     uchar *ns = (uchar *)domalloc(l+o+1);
     ns[l+o] = '\0';
     return (uchar*)strncpy((char*)ns+o, (char*)s, l) - o;
 }
References domalloc().
Referenced by appendDirToIncludeList(), basepath(), control(), doinclude(), lookup(), makespace(), normtokenrow(), setup(), and stringify().
normtokenrow()
Tokenrow* normtokenrow (Tokenrow * trp)
Definition at line 232 of file tokens.c.
 {
     Token *tp;
     Tokenrow *ntrp = new(Tokenrow);
     int len;
     len = trp->lp - trp->tp;
     if (len<=0)
         len = 1;
     maketokenrow(len, ntrp);
     for (tp=trp->tp; tp < trp->lp; tp++) {
         *ntrp->lp = *tp;
         if (tp->len) {
             ntrp->lp->t = newstring(tp->t, tp->len, 1);
             *ntrp->lp->t++ = ' ';
             if (tp->wslen)
                 ntrp->lp->wslen = 1;
         }
         ntrp->lp++;
     }
     if (ntrp->lp > ntrp->bp)
         ntrp->bp->wslen = 0;
     return ntrp;
 }
References maketokenrow(), and newstring().
Referenced by doadefine(), dodefine(), and gatherargs().
outnum()
char* outnum (char * p, int n)
Definition at line 351 of file tokens.c.
 {
     if (n>=10)
         p = outnum(p, n/10);
     *p++ = n%10 + '0';
     return p;
 }
Referenced by builtin(), and genline().
peektokens()
void peektokens (Tokenrow * trp, char * str)
Definition at line 261 of file tokens.c.
 {
     Token *tp;
     tp = trp->tp;
     flushout();
     if (str)
         fprintf(stderr, "%s ", str);
     if (tp<trp->bp || tp>trp->lp)
         fprintf(stderr, "(tp offset %ld) ", (long int) (tp - trp->bp));
     for (tp=trp->bp; tp<trp->lp && tp<trp->bp+32; tp++) {
         if (tp->type!=NL) {
             int c = tp->t[tp->len];
             tp->t[tp->len] = 0;
             fprintf(stderr, "%s", tp->t);
             tp->t[tp->len] = c;
         }
         if (tp->type==NAME) {
             fprintf(stderr, tp==trp->tp?"{*":"{");
             prhideset(tp->hideset);
             fprintf(stderr, "} ");
         } else
             fprintf(stderr, tp==trp->tp?"{%x*} ":"{%x} ", tp->type);
     }
     fprintf(stderr, "\n");
     fflush(stderr);
 }
References bp, flushout(), NAME, NL, and prhideset().
Referenced by puttokens().
puttokens()
void puttokens (Tokenrow * trp)
Definition at line 290 of file tokens.c.
 {
     Token *tp;
     int len;
     uchar *p;
     if (verbose)
         peektokens(trp, "");
     tp = trp->bp;
     for (; tp<trp->lp; tp++) {
         len = tp->len+tp->wslen;
         p = tp->t-tp->wslen;
         while (tp<trp->lp-1 && p+len == (tp+1)->t - (tp+1)->wslen) {
             tp++;
             len += tp->wslen+tp->len;
         }
         if (len>OBS/2) {        /* handle giant token */
             if (wbp > wbuf)
                 write(1, wbuf, wbp-wbuf);
             write(1, (char *)p, len);
             wbp = wbuf;
         } else {
             memcpy(wbp, p, len);
             wbp += len;
         }
         if (wbp >= &wbuf[OBS]) {
             write(1, wbuf, OBS);
             if (wbp > &wbuf[OBS])
                 memcpy(wbuf, wbuf+OBS, wbp - &wbuf[OBS]);
             wbp -= OBS;
         }
     }
     trp->tp = tp;
     if (cursource->fd==0)
         flushout();
 }
References cursource, flushout(), OBS, peektokens(), verbose, wbp, and wbuf.
Referenced by genline(), and process().
setempty()
void setempty (Tokenrow * trp)
Definition at line 340 of file tokens.c.
 {
     trp->tp = trp->bp;
     trp->lp = trp->bp+1;
     *trp->bp = nltoken;
 }
References nltoken.
Referenced by control(), and process().
Variable Documentation
wbp
char* wbp = wbuf static
Definition at line 7 of file tokens.c.
Referenced by flushout(), and puttokens().
wbuf
char wbuf[2 *OBS] static
Definition at line 6 of file tokens.c.
Referenced by flushout(), and puttokens().
wstab
const char wstab[] static
Definition at line 13 of file tokens.c.
Referenced by makespace().