ZEQ2-Lite: Source/Engine/libspeex/os_support.h File Reference
os_support.h File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
Macros
#define speex_assert(cond) {if (!(cond)) {speex_fatal("assertion failed: " #cond);}}
#define SPEEX_COPY(dst, src, n) (memcpy((dst), (src), (n)*sizeof(*(dst)) + 0*((dst)-(src))))
Copy n bytes of memory from src to dst.
#define speex_fatal(str) _speex_fatal(str, __FILE__, __LINE__);
#define SPEEX_MEMSET(dst, c, n) (memset((dst), (c), (n)*sizeof(*(dst))))
Set n bytes of memory to value of c, starting at address s.
#define SPEEX_MOVE(dst, src, n) (memmove((dst), (src), (n)*sizeof(*(dst)) + 0*((dst)-(src))))
Copy n bytes of memory from src to dst, allowing overlapping regions.
Functions
static void _speex_fatal (const char *str, const char *file, int line)
static void _speex_putc (int ch, void *file)
Speex wrapper for putc.
static void print_vec (float *vec, int len, char *name)
static void * speex_alloc (int size)
Speex wrapper for calloc.
static void * speex_alloc_scratch (int size)
Same as speex_alloc, except that the area is only needed inside a Speex call (might cause problem with wideband though)
static void speex_free (void *ptr)
Speex wrapper for calloc.
static void speex_free_scratch (void *ptr)
Same as speex_free, except that the area is only needed inside a Speex call (might cause problem with wideband though)
static void speex_notify (const char *str)
static void * speex_realloc (void *ptr, int size)
Speex wrapper for realloc.
static void speex_warning (const char *str)
static void speex_warning_int (const char *str, int val)
Macro Definition Documentation
speex_assert
#define speex_assert (cond) {if (!(cond)) {speex_fatal("assertion failed: " #cond);}}
Definition at line 155 of file os_support.h.
SPEEX_COPY
#define SPEEX_COPY (dst, src, n) (memcpy((dst), (src), (n)*sizeof(*(dst)) + 0*((dst)-(src))))
Copy n bytes of memory from src to dst.
The 0* term provides compile-time type checking
Definition at line 95 of file os_support.h.
speex_fatal
#define speex_fatal (str) _speex_fatal(str, __FILE__, __LINE__);
Definition at line 154 of file os_support.h.
SPEEX_MEMSET
#define SPEEX_MEMSET (dst, c, n) (memset((dst), (c), (n)*sizeof(*(dst))))
Set n bytes of memory to value of c, starting at address s.
Definition at line 106 of file os_support.h.
SPEEX_MOVE
#define SPEEX_MOVE (dst, src, n) (memmove((dst), (src), (n)*sizeof(*(dst)) + 0*((dst)-(src))))
Copy n bytes of memory from src to dst, allowing overlapping regions.
The 0* term provides compile-time type checking
Definition at line 101 of file os_support.h.
Function Documentation
_speex_fatal()
static void _speex_fatal (const char * str, const char * file, int line) inline static
Definition at line 111 of file os_support.h.
 {
    fprintf (stderr, "Fatal (internal) error in %s, line %d: %s\n", file, line, str);
    exit(1);
 }
References line.
_speex_putc()
static void _speex_putc (int ch, void * file) inline static
Speex wrapper for putc.
Definition at line 147 of file os_support.h.
 {
    FILE *f = (FILE *)file;
    fprintf(f, "%c", ch);
 }
Referenced by speex_std_char_handler().
print_vec()
static void print_vec (float * vec, int len, char * name) inline static
Definition at line 158 of file os_support.h.
 {
    int i;
    printf ("%s ", name);
    for (i=0;i<len;i++)
       printf (" %f", vec[i]);
    printf ("\n");
 }
References vec.
speex_alloc()
static void* speex_alloc (int size) inline static
Speex wrapper for calloc.
To do your own dynamic allocation, all you need to do is replace this function, speex_realloc and speex_free NOTE: speex_alloc needs to CLEAR THE MEMORY
Definition at line 51 of file os_support.h.
 {
    /* WARNING: this is not equivalent to malloc(). If you want to use malloc()
       or your own allocator, YOU NEED TO CLEAR THE MEMORY ALLOCATED. Otherwise
       you will experience strange bugs */
    return calloc(size,1);
 }
Referenced by filterbank_new(), jitter_buffer_init(), jitter_buffer_put(), nb_decoder_init(), nb_encoder_init(), sb_decoder_init(), sb_encoder_init(), speex_bits_init(), speex_buffer_init(), speex_echo_state_init(), speex_header_to_packet(), speex_packet_to_header(), speex_preprocess_state_init(), speex_resampler_init_frac(), speex_stereo_state_init(), spx_drft_init(), spx_fft_init(), and update_filter().
speex_alloc_scratch()
static void* speex_alloc_scratch (int size) inline static
Same as speex_alloc, except that the area is only needed inside a Speex call (might cause problem with wideband though)
Definition at line 62 of file os_support.h.
 {
    /* Scratch space doesn't need to be cleared */
    return calloc(size,1);
 }
Referenced by nb_decoder_init(), and nb_encoder_init().
speex_free()
static void speex_free (void * ptr) inline static
Speex wrapper for calloc.
To do your own dynamic allocation, all you need to do is replace this function, speex_realloc and speex_alloc
Definition at line 79 of file os_support.h.
 {
    free(ptr);
 }
References ptr().
Referenced by filterbank_destroy(), jitter_buffer_destroy(), jitter_buffer_get(), jitter_buffer_get_another(), jitter_buffer_put(), jitter_buffer_reset(), nb_decoder_destroy(), nb_encoder_destroy(), sb_decoder_destroy(), sb_encoder_destroy(), speex_bits_destroy(), speex_buffer_destroy(), speex_echo_state_destroy(), speex_header_free(), speex_preprocess_state_destroy(), speex_resampler_destroy(), speex_stereo_state_destroy(), spx_drft_clear(), and spx_fft_destroy().
speex_free_scratch()
static void speex_free_scratch (void * ptr) inline static
Same as speex_free, except that the area is only needed inside a Speex call (might cause problem with wideband though)
Definition at line 87 of file os_support.h.
 {
    free(ptr);
 }
References ptr().
Referenced by nb_decoder_destroy(), and nb_encoder_destroy().
speex_notify()
static void speex_notify (const char * str) inline static
Definition at line 137 of file os_support.h.
 {
 #ifndef DISABLE_NOTIFICATIONS
    fprintf (stderr, "notification: %s\n", str);
 #endif
 }
Referenced by nb_decode(), sb_decode(), speex_bits_pack(), speex_bits_read_from(), and speex_packet_to_header().
speex_realloc()
static void* speex_realloc (void * ptr, int size) inline static
Speex wrapper for realloc.
To do your own dynamic allocation, all you need to do is replace this function, speex_alloc and speex_free
Definition at line 71 of file os_support.h.
 {
    return realloc(ptr, size);
 }
References ptr().
Referenced by speex_bits_pack(), speex_bits_read_from(), speex_bits_read_whole_bytes(), speex_buffer_resize(), and update_filter().
speex_warning()
static void speex_warning (const char * str) inline static
Definition at line 119 of file os_support.h.
 {
 #ifndef DISABLE_WARNINGS
    fprintf (stderr, "warning: %s\n", str);
 #endif
 }
Referenced by kiss_fftr_alloc(), speex_bits_pack(), speex_bits_read_from(), speex_bits_read_whole_bytes(), speex_echo_cancellation(), speex_echo_capture(), speex_echo_playback(), speex_init_header(), and speex_preprocess_ctl().
speex_warning_int()
static void speex_warning_int (const char * str, int val) inline static
Definition at line 128 of file os_support.h.
 {
 #ifndef DISABLE_WARNINGS
    fprintf (stderr, "warning: %s %d\n", str, val);
 #endif
 }
References val.
Referenced by jitter_buffer_ctl(), jitter_buffer_get(), jitter_buffer_remaining_span(), jitter_buffer_tick(), nb_decoder_ctl(), nb_encoder_ctl(), nb_mode_query(), sb_decoder_ctl(), sb_encoder_ctl(), speex_echo_ctl(), speex_lib_ctl(), speex_preprocess_ctl(), and wb_mode_query().