ZEQ2-Lite: Source/Engine/renderer/tr_model.c File Reference
tr_model.c File Reference
#include "tr_local.h"
Data Structures
struct modelExtToLoaderMap_t
Macros
#define LL(x) x=LittleLong(x)
Functions
model_t * R_AllocModel (void)
model_t * R_GetModelByHandle (qhandle_t index)
static md3Tag_t * R_GetTag (md3Header_t *mod, int frame, const char *tagName)
int R_LerpTag (orientation_t *tag, qhandle_t handle, int startFrame, int endFrame, float frac, const char *tagName)
static qboolean R_LoadMD3 (model_t *mod, int lod, void *buffer, const char *name)
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
void R_ModelInit (void)
void R_Modellist_f (void)
qhandle_t R_RegisterIQM (const char *name, model_t *mod)
qhandle_t R_RegisterMD3 (const char *name, model_t *mod)
void RE_BeginRegistration (glconfig_t *glconfigOut)
qhandle_t RE_RegisterModel (const char *name)
Variables
static modelExtToLoaderMap_t modelLoaders []
static int numModelLoaders = ARRAY_LEN(modelLoaders)
Macro Definition Documentation
LL
#define LL (x) x=LittleLong(x)
Definition at line 26 of file tr_model.c.
Function Documentation
R_AllocModel()
model_t* R_AllocModel (void)
Definition at line 186 of file tr_model.c.
{
     model_t     *mod;
     if ( tr.numModels == MAX_MOD_KNOWN ) {
         return NULL;
     }
     mod = ri.Hunk_Alloc( sizeof( *tr.models[tr.numModels] ), h_low );
     mod->index = tr.numModels;
     tr.models[tr.numModels] = mod;
     tr.numModels++;
     return mod;
 }
References h_low, refimport_t::Hunk_Alloc, MAX_MOD_KNOWN, trGlobals_t::models, NULL, trGlobals_t::numModels, ri, and tr.
Referenced by R_LoadSubmodels(), R_ModelInit(), and RE_RegisterModel().
R_GetModelByHandle()
model_t* R_GetModelByHandle (qhandle_t index)
Definition at line 168 of file tr_model.c.
{
     model_t     *mod;
     // out of range gets the defualt model
     if ( index < 1 || index >= tr.numModels ) {
         return tr.models[0];
     }
     mod = tr.models[index];
     return mod;
 }
References trGlobals_t::models, trGlobals_t::numModels, and tr.
Referenced by R_AddBrushModelSurfaces(), R_AddEntitySurfaces(), R_CalcBones(), R_ComputeFogNum(), R_CullModel(), R_LerpTag(), and R_ModelBounds().
R_GetTag()
static md3Tag_t* R_GetTag (md3Header_t * mod, int frame, const char * tagName) static
Definition at line 571 of file tr_model.c.
{
     md3Tag_t        *tag;
     int             i;
     if ( frame >= mod->numFrames ) {
         // it is possible to have a bad frame while changing models, so don't error
         frame = mod->numFrames - 1;
     }
     tag = (md3Tag_t *)((byte *)mod + mod->ofsTags) + frame * mod->numTags;
     for ( i = 0 ; i < mod->numTags ; i++, tag++ ) {
         if ( !strcmp( tag->name, tagName ) ) {
             return tag; // found it
         }
     }
     return NULL;
 }
References frame, NULL, md3Header_t::numFrames, md3Header_t::numTags, and md3Header_t::ofsTags.
Referenced by R_LerpTag().
R_LerpTag()
int R_LerpTag (orientation_t * tag, qhandle_t handle, int startFrame, int endFrame, float frac, const char * tagName)
Definition at line 595 of file tr_model.c.
{
     md3Tag_t    *start, *end;
     int     i;
     float       frontLerp, backLerp;
     model_t     *model;
     model = R_GetModelByHandle( handle );
     if ( !model->md3[0] )
     {
         if( model->type == MOD_IQM ) {
             return R_IQMLerpTag( tag, model->modelData,
                     startFrame, endFrame,
                     frac, tagName );
         } else {
             AxisClear( tag->axis );
             VectorClear( tag->origin );
             return qfalse;
         }
     }
     else
     {
         start = R_GetTag( model->md3[0], startFrame, tagName );
         end = R_GetTag( model->md3[0], endFrame, tagName );
         if ( !start || !end ) {
             AxisClear( tag->axis );
             VectorClear( tag->origin );
             return qfalse;
         }
     }
     frontLerp = frac;
     backLerp = 1.0f - frac;
     for ( i = 0 ; i < 3 ; i++ ) {
         tag->origin[i] = start->origin[i] * backLerp +  end->origin[i] * frontLerp;
         tag->axis[0][i] = start->axis[0][i] * backLerp +  end->axis[0][i] * frontLerp;
         tag->axis[1][i] = start->axis[1][i] * backLerp +  end->axis[1][i] * frontLerp;
         tag->axis[2][i] = start->axis[2][i] * backLerp +  end->axis[2][i] * frontLerp;
     }
     VectorNormalize( tag->axis[0] );
     VectorNormalize( tag->axis[1] );
     VectorNormalize( tag->axis[2] );
     return qtrue;
 }
References orientation_t::axis, AxisClear(), MOD_IQM, orientation_t::origin, qfalse, qtrue, R_GetModelByHandle(), R_GetTag(), R_IQMLerpTag(), VectorClear, and VectorNormalize().
Referenced by GetRefAPI().
R_LoadMD3()
static qboolean R_LoadMD3 (model_t * mod, int lod, void * buffer, const char * name) static
Definition at line 334 of file tr_model.c.
{
     int                 i, j;
     md3Header_t         *pinmodel;
     md3Frame_t          *frame;
     md3Surface_t        *surf;
     md3Shader_t         *shader;
     md3Triangle_t       *tri;
     md3St_t             *st;
     md3XyzNormal_t      *xyz;
     md3Tag_t            *tag;
     int                 version;
     int                 size;
     pinmodel = (md3Header_t *)buffer;
     version = LittleLong (pinmodel->version);
     if (version != MD3_VERSION) {
         ri.Printf( PRINT_WARNING, "R_LoadMD3: %s has wrong version (%i should be %i)\n",
                  mod_name, version, MD3_VERSION);
         return qfalse;
     }
     mod->type = MOD_MESH;
     size = LittleLong(pinmodel->ofsEnd);
     mod->dataSize += size;
     mod->md3[lod] = ri.Hunk_Alloc( size, h_low );
     Com_Memcpy (mod->md3[lod], buffer, LittleLong(pinmodel->ofsEnd) );
     LL(mod->md3[lod]->ident);
     LL(mod->md3[lod]->version);
     LL(mod->md3[lod]->numFrames);
     LL(mod->md3[lod]->numTags);
     LL(mod->md3[lod]->numSurfaces);
     LL(mod->md3[lod]->ofsFrames);
     LL(mod->md3[lod]->ofsTags);
     LL(mod->md3[lod]->ofsSurfaces);
     LL(mod->md3[lod]->ofsEnd);
     if ( mod->md3[lod]->numFrames < 1 ) {
         ri.Printf( PRINT_WARNING, "R_LoadMD3: %s has no frames\n", mod_name );
         return qfalse;
     }
     // swap all the frames
     frame = (md3Frame_t *) ( (byte *)mod->md3[lod] + mod->md3[lod]->ofsFrames );
     for ( i = 0 ; i < mod->md3[lod]->numFrames ; i++, frame++) {
         frame->radius = LittleFloat( frame->radius );
         for ( j = 0 ; j < 3 ; j++ ) {
             frame->bounds[0][j] = LittleFloat( frame->bounds[0][j] );
             frame->bounds[1][j] = LittleFloat( frame->bounds[1][j] );
             frame->localOrigin[j] = LittleFloat( frame->localOrigin[j] );
         }
     }
     // swap all the tags
     tag = (md3Tag_t *) ( (byte *)mod->md3[lod] + mod->md3[lod]->ofsTags );
     for ( i = 0 ; i < mod->md3[lod]->numTags * mod->md3[lod]->numFrames ; i++, tag++) {
         for ( j = 0 ; j < 3 ; j++ ) {
             tag->origin[j] = LittleFloat( tag->origin[j] );
             tag->axis[0][j] = LittleFloat( tag->axis[0][j] );
             tag->axis[1][j] = LittleFloat( tag->axis[1][j] );
             tag->axis[2][j] = LittleFloat( tag->axis[2][j] );
         }
     }
     // swap all the surfaces
     surf = (md3Surface_t *) ( (byte *)mod->md3[lod] + mod->md3[lod]->ofsSurfaces );
     for ( i = 0 ; i < mod->md3[lod]->numSurfaces ; i++) {
         LL(surf->ident);
         LL(surf->flags);
         LL(surf->numFrames);
         LL(surf->numShaders);
         LL(surf->numTriangles);
         LL(surf->ofsTriangles);
         LL(surf->numVerts);
         LL(surf->ofsShaders);
         LL(surf->ofsSt);
         LL(surf->ofsXyzNormals);
         LL(surf->ofsEnd);
         if ( surf->numVerts > SHADER_MAX_VERTEXES ) {
             ri.Printf(PRINT_WARNING, "R_LoadMD3: %s has more than %i verts on a surface (%i).\n",
                 mod_name, SHADER_MAX_VERTEXES, surf->numVerts );
             return qfalse;
         }
         if ( surf->numTriangles*3 > SHADER_MAX_INDEXES ) {
             ri.Printf(PRINT_WARNING, "R_LoadMD3: %s has more than %i triangles on a surface (%i).\n",
                 mod_name, SHADER_MAX_INDEXES / 3, surf->numTriangles );
             return qfalse;
         }
         // change to surface identifier
         surf->ident = SF_MD3;
         // lowercase the surface name so skin compares are faster
         Q_strlwr( surf->name );
         // strip off a trailing _1 or _2
         // this is a crutch for q3data being a mess
         j = strlen( surf->name );
         if ( j > 2 && surf->name[j-2] == '_' ) {
             surf->name[j-2] = 0;
         }
         // register the shaders
         shader = (md3Shader_t *) ( (byte *)surf + surf->ofsShaders );
         for ( j = 0 ; j < surf->numShaders ; j++, shader++ ) {
             shader_t    *sh;
             sh = R_FindShader( shader->name, LIGHTMAP_NONE, qtrue );
             if ( sh->defaultShader ) {
                 shader->shaderIndex = 0;
             } else {
                 shader->shaderIndex = sh->index;
             }
         }
         // swap all the triangles
         tri = (md3Triangle_t *) ( (byte *)surf + surf->ofsTriangles );
         for ( j = 0 ; j < surf->numTriangles ; j++, tri++ ) {
             LL(tri->indexes[0]);
             LL(tri->indexes[1]);
             LL(tri->indexes[2]);
         }
         // swap all the ST
         st = (md3St_t *) ( (byte *)surf + surf->ofsSt );
         for ( j = 0 ; j < surf->numVerts ; j++, st++ ) {
             st->st[0] = LittleFloat( st->st[0] );
             st->st[1] = LittleFloat( st->st[1] );
         }
         // swap all the XyzNormals
         xyz = (md3XyzNormal_t *) ( (byte *)surf + surf->ofsXyzNormals );
         for ( j = 0 ; j < surf->numVerts * surf->numFrames ; j++, xyz++ )
         {
             xyz->xyz[0] = LittleShort( xyz->xyz[0] );
             xyz->xyz[1] = LittleShort( xyz->xyz[1] );
             xyz->xyz[2] = LittleShort( xyz->xyz[2] );
             xyz->normal = LittleShort( xyz->normal );
         }
         // find the next surface
         surf = (md3Surface_t *)( (byte *)surf + surf->ofsEnd );
     }
     return qtrue;
 }
References mdxFrame_t::bounds, Com_Memcpy, md3Surface_t::flags, frame, h_low, refimport_t::Hunk_Alloc, md3Surface_t::ident, md3Triangle_t::indexes, LIGHTMAP_NONE, LL, mdxFrame_t::localOrigin, MD3_VERSION, MOD_MESH, md3Surface_t::name, md3XyzNormal_t::normal, md3Surface_t::numFrames, md3Surface_t::numShaders, md3Surface_t::numTriangles, md3Surface_t::numVerts, md3Surface_t::ofsEnd, md3Header_t::ofsEnd, md3Surface_t::ofsShaders, md3Surface_t::ofsSt, md3Surface_t::ofsTriangles, md3Surface_t::ofsXyzNormals, PRINT_WARNING, Q_strlwr(), qfalse, qtrue, R_FindShader(), mdxFrame_t::radius, ri, SF_MD3, sh, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, md3St_t::st, md3Header_t::version, version, and md3XyzNormal_t::xyz.
Referenced by R_RegisterMD3().
R_ModelBounds()
void R_ModelBounds (qhandle_t handle, vec3_t mins, vec3_t maxs)
Definition at line 650 of file tr_model.c.
{
     model_t     *model;
     model = R_GetModelByHandle( handle );
     if(model->type == MOD_BRUSH) {
         VectorCopy( model->bmodel->bounds[0], mins );
         VectorCopy( model->bmodel->bounds[1], maxs );
         return;
     } else if (model->type == MOD_MESH) {
         md3Header_t *header;
         md3Frame_t  *frame;
         header = model->md3[0];
         frame = (md3Frame_t *) ((byte *)header + header->ofsFrames);
         VectorCopy( frame->bounds[0], mins );
         VectorCopy( frame->bounds[1], maxs );
         return;
     } else if(model->type == MOD_IQM) {
         iqmData_t *iqmData;
         iqmData = model->modelData;
         if(iqmData->bounds)
         {
             VectorCopy(iqmData->bounds, mins);
             VectorCopy(iqmData->bounds + 3, maxs);
             return;
         }
     }
     VectorClear( mins );
     VectorClear( maxs );
 }
References mdxFrame_t::bounds, iqmData_t::bounds, frame, MOD_BRUSH, MOD_IQM, MOD_MESH, R_GetModelByHandle(), VectorClear, and VectorCopy.
Referenced by GetRefAPI().
R_ModelInit()
void R_ModelInit (void)
Definition at line 520 of file tr_model.c.
{
     model_t     *mod;
     // leave a space for NULL model
     tr.numModels = 0;
     mod = R_AllocModel();
     mod->type = MOD_BAD;
 }
References MOD_BAD, trGlobals_t::numModels, R_AllocModel(), and tr.
Referenced by R_Init().
R_Modellist_f()
void R_Modellist_f (void)
Definition at line 535 of file tr_model.c.
{
     int     i, j;
     model_t *mod;
     int     total;
     int     lods;
     total = 0;
     for ( i = 1 ; i < tr.numModels; i++ ) {
         mod = tr.models[i];
         lods = 1;
         for ( j = 1 ; j < MD3_MAX_LODS ; j++ ) {
             if ( mod->md3[j] && mod->md3[j] != mod->md3[j-1] ) {
                 lods++;
             }
         }
         ri.Printf( PRINT_ALL, "%8i : (%i) %s\n",mod->dataSize, lods, mod->name );
         total += mod->dataSize;
     }
     ri.Printf( PRINT_ALL, "%8i : Total models\n", total );
 #if 0       // not working right with new hunk
     if ( tr.world ) {
         ri.Printf( PRINT_ALL, "\n%8i : %s\n", tr.world->dataSize, tr.world->name );
     }
 #endif
 }
References world_t::dataSize, MD3_MAX_LODS, trGlobals_t::models, world_t::name, trGlobals_t::numModels, PRINT_ALL, ri, tr, and trGlobals_t::world.
Referenced by R_Register().
R_RegisterIQM()
qhandle_t R_RegisterIQM (const char * name, model_t * mod)
Definition at line 116 of file tr_model.c.
 {
     union {
         unsigned *u;
         void *v;
     } buf;
     qboolean loaded = qfalse;
     int filesize;
     filesize = ri.FS_ReadFile(name, (void **) &buf.v);
     if(!buf.u)
     {
         mod->type = MOD_BAD;
         return 0;
     }
     loaded = R_LoadIQM(mod, buf.u, filesize, name);
     ri.FS_FreeFile (buf.v);
     if(!loaded)
     {
         ri.Printf(PRINT_WARNING,"R_RegisterIQM: couldn't load iqm file %s\n", name);
         mod->type = MOD_BAD;
         return 0;
     }
     return mod->index;
 }
References refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, MOD_BAD, PRINT_WARNING, qfalse, R_LoadIQM(), and ri.
R_RegisterMD3()
qhandle_t R_RegisterMD3 (const char * name, model_t * mod)
Definition at line 36 of file tr_model.c.
 {
     union {
         unsigned *u;
         void *v;
     } buf;
     int         lod;
     int         ident;
     qboolean    loaded = qfalse;
     int         numLoaded;
     char filename[MAX_QPATH], namebuf[MAX_QPATH+20];
     char *fext, defex[] = "md3";
     numLoaded = 0;
     strcpy(filename, name);
     fext = strchr(filename, '.');
     if(!fext)
         fext = defex;
     else
     {
         *fext = '\0';
         fext++;
     }
     for (lod = MD3_MAX_LODS - 1 ; lod >= 0 ; lod--)
     {
         if(lod)
             Com_sprintf(namebuf, sizeof(namebuf), "%s_%d.%s", filename, lod, fext);
         else
             Com_sprintf(namebuf, sizeof(namebuf), "%s.%s", filename, fext);
         ri.FS_ReadFile( namebuf, &buf.v );
         if(!buf.u)
             continue;
         ident = LittleLong(* (unsigned *) buf.u);
         if (ident == MD3_IDENT)
                 loaded = R_LoadMD3(mod, lod, buf.u, name);
         else
                 ri.Printf(PRINT_WARNING,"R_RegisterMD3: unknown fileid for %s\n", name);
         ri.FS_FreeFile(buf.v);
         if(loaded)
         {
             mod->numLods++;
             numLoaded++;
         }
         else
             break;
     }
     if(numLoaded)
     {
         // duplicate into higher lod spots that weren't
         // loaded, in case the user changes r_lodbias on the fly
         for(lod--; lod >= 0; lod--)
         {
             mod->numLods++;
             mod->md3[lod] = mod->md3[lod + 1];
         }
         return mod->index;
     }
 #ifdef _DEBUG
     ri.Printf(PRINT_WARNING,"R_RegisterMD3: couldn't load %s\n", name);
 #endif
     mod->type = MOD_BAD;
     return 0;
 }
References Com_sprintf(), refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, MAX_QPATH, MD3_IDENT, MD3_MAX_LODS, MOD_BAD, PRINT_WARNING, qfalse, R_LoadMD3(), and ri.
RE_BeginRegistration()
void RE_BeginRegistration (glconfig_t * glconfigOut)
Definition at line 493 of file tr_model.c.
{
     R_Init();
     *glconfigOut = glConfig;
     R_SyncRenderThread();
     tr.viewCluster = -1;        // force markleafs to regenerate
     R_ClearFlares();
     RE_ClearScene();
     tr.registered = qtrue;
     // NOTE: this sucks, for some reason the first stretch pic is never drawn
     // without this we'd see a white flash on a level load because the very
     // first time the level shot would not be drawn
 //  RE_StretchPic(0, 0, 0, 0, 0, 0, 1, 1, 0);
 }
References glConfig, qtrue, R_ClearFlares(), R_Init(), R_SyncRenderThread(), RE_ClearScene(), trGlobals_t::registered, tr, and trGlobals_t::viewCluster.
Referenced by GetRefAPI().
RE_RegisterModel()
qhandle_t RE_RegisterModel (const char * name)
Definition at line 213 of file tr_model.c.
{
     model_t     *mod;
     qhandle_t   hModel;
     qboolean    orgNameFailed = qfalse;
     int         orgLoader = -1;
     int         i;
     char        localName[ MAX_QPATH ];
     const char  *ext;
     char        altName[ MAX_QPATH ];
     if ( !name || !name[0] ) {
         ri.Printf( PRINT_ALL, "RE_RegisterModel: NULL name\n" );
         return 0;
     }
     if ( strlen( name ) >= MAX_QPATH ) {
         ri.Printf( PRINT_ALL, "Model name exceeds MAX_QPATH\n" );
         return 0;
     }
     //
     // search the currently loaded models
     //
     for ( hModel = 1 ; hModel < tr.numModels; hModel++ ) {
         mod = tr.models[hModel];
         if ( !strcmp( mod->name, name ) ) {
             if( mod->type == MOD_BAD ) {
                 return 0;
             }
             return hModel;
         }
     }
     // allocate a new model_t
     if ( ( mod = R_AllocModel() ) == NULL ) {
         ri.Printf( PRINT_WARNING, "RE_RegisterModel: R_AllocModel() failed for '%s'\n", name);
         return 0;
     }
     // only set the name after the model has been successfully loaded
     Q_strncpyz( mod->name, name, sizeof( mod->name ) );
     // make sure the render thread is stopped
     R_SyncRenderThread();
     mod->type = MOD_BAD;
     mod->numLods = 0;
     //
     // load the files
     //
     Q_strncpyz( localName, name, MAX_QPATH );
     ext = COM_GetExtension( localName );
     if( *ext )
     {
         // Look for the correct loader and use it
         for( i = 0; i < numModelLoaders; i++ )
         {
             if( !Q_stricmp( ext, modelLoaders[ i ].ext ) )
             {
                 // Load
                 hModel = modelLoaders[ i ].ModelLoader( localName, mod );
                 break;
             }
         }
         // A loader was found
         if( i < numModelLoaders )
         {
             if( !hModel )
             {
                 // Loader failed, most likely because the file isn't there;
                 // try again without the extension
                 orgNameFailed = qtrue;
                 orgLoader = i;
                 COM_StripExtension( name, localName, MAX_QPATH );
             }
             else
             {
                 // Something loaded
                 return mod->index;
             }
         }
     }
     // Try and find a suitable match using all
     // the model formats supported
     for( i = 0; i < numModelLoaders; i++ )
     {
         if (i == orgLoader)
             continue;
         Com_sprintf( altName, sizeof (altName), "%s.%s", localName, modelLoaders[ i ].ext );
         // Load
         hModel = modelLoaders[ i ].ModelLoader( altName, mod );
         if( hModel )
         {
             if( orgNameFailed )
             {
                 ri.Printf( PRINT_DEVELOPER, "WARNING: %s not present, using %s instead\n",
                         name, altName );
             }
             break;
         }
     }
     return hModel;
 }
References COM_GetExtension(), Com_sprintf(), COM_StripExtension(), ext, MAX_QPATH, MOD_BAD, modelExtToLoaderMap_t::ModelLoader, modelLoaders, trGlobals_t::models, NULL, numModelLoaders, trGlobals_t::numModels, PRINT_ALL, PRINT_DEVELOPER, PRINT_WARNING, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, R_AllocModel(), R_SyncRenderThread(), ri, and tr.
Referenced by GetRefAPI().
Variable Documentation
modelLoaders
modelExtToLoaderMap_t modelLoaders[] static
Initial value:
=
{
    { "iqm", R_RegisterIQM },
    { "md3", R_RegisterMD3 }
}
Definition at line 155 of file tr_model.c.
Referenced by RE_RegisterModel().
numModelLoaders
int numModelLoaders = ARRAY_LEN(modelLoaders) static
Definition at line 161 of file tr_model.c.
Referenced by RE_RegisterModel().