ZEQ2-Lite: SpeexBits: Bit-stream manipulations
SpeexBits: Bit-stream manipulations
This is the structure that holds the bit-stream when encoding or decoding with Speex. It allows some manipulations as well.
Data Structures
struct SpeexBits
Bit-packing data structure representing (part of) a bit-stream.
Functions
void speex_bits_advance (SpeexBits *bits, int n)
Advances the position of the "bit cursor" in the stream.
void speex_bits_destroy (SpeexBits *bits)
Frees all resources associated to a SpeexBits struct.
void speex_bits_init (SpeexBits *bits)
Initializes and allocates resources for a SpeexBits struct.
void speex_bits_init_buffer (SpeexBits *bits, void *buff, int buf_size)
Initializes SpeexBits struct using a pre-allocated buffer.
void speex_bits_insert_terminator (SpeexBits *bits)
Insert a terminator so that the data can be sent as a packet while auto-detecting the number of frames in each packet.
int speex_bits_nbytes (SpeexBits *bits)
Returns the number of bytes in the bit-stream, including the last one even if it is not "full".
void speex_bits_pack (SpeexBits *bits, int data, int nbBits)
Append bits to the bit-stream.
int speex_bits_peek (SpeexBits *bits)
Get the value of the next bit in the stream, without modifying the "cursor" position.
unsigned int speex_bits_peek_unsigned (SpeexBits *bits, int nbBits)
Same as speex_bits_unpack_unsigned, but without modifying the cursor position.
void speex_bits_read_from (SpeexBits *bits, char *bytes, int len)
Initializes the bit-stream from the data in an area of memory.
void speex_bits_read_whole_bytes (SpeexBits *bits, char *bytes, int len)
Append bytes to the bit-stream.
int speex_bits_remaining (SpeexBits *bits)
Returns the number of bits remaining to be read in a stream.
void speex_bits_reset (SpeexBits *bits)
Resets bits to initial value (just after initialization, erasing content)
void speex_bits_rewind (SpeexBits *bits)
Rewind the bit-stream to the beginning (ready for read) without erasing the content.
void speex_bits_set_bit_buffer (SpeexBits *bits, void *buff, int buf_size)
Sets the bits in a SpeexBits struct to use data from an existing buffer (for decoding without copying data)
int speex_bits_unpack_signed (SpeexBits *bits, int nbBits)
Interpret the next bits in the bit-stream as a signed integer.
unsigned int speex_bits_unpack_unsigned (SpeexBits *bits, int nbBits)
Interpret the next bits in the bit-stream as an unsigned integer.
int speex_bits_write (SpeexBits *bits, char *bytes, int max_len)
Write the content of a bit-stream to an area of memory.
int speex_bits_write_whole_bytes (SpeexBits *bits, char *bytes, int max_len)
Like speex_bits_write, but writes only the complete bytes in the stream.
Variables
int SpeexBits::bitPtr
Position of the bit "cursor" within the current char.
int SpeexBits::buf_size
Allocated size for buffer.
int SpeexBits::charPtr
Position of the byte "cursor".
char * SpeexBits::chars
"raw" data
int SpeexBits::nbBits
Total number of bits stored in the stream.
int SpeexBits::overflow
Set to one if we try to read past the valid data.
int SpeexBits::owner
Does the struct "own" the "raw" buffer (member "chars")
int SpeexBits::reserved1
Reserved for future use.
void * SpeexBits::reserved2
Reserved for future use.
Detailed Description
This is the structure that holds the bit-stream when encoding or decoding with Speex. It allows some manipulations as well.
Function Documentation
speex_bits_advance()
void speex_bits_advance (SpeexBits * bits, int n)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Advances the position of the "bit cursor" in the stream.
Parameters
bits Bit-stream to operate on
n Number of bits to advance
Definition at line 343 of file bits.c.
 {
     if (((bits->charPtr<<LOG2_BITS_PER_CHAR)+bits->bitPtr+n>bits->nbBits) || bits->overflow){
       bits->overflow=1;
       return;
     }
    bits->charPtr += (bits->bitPtr+n) >> LOG2_BITS_PER_CHAR; /* divide by BITS_PER_CHAR */
    bits->bitPtr = (bits->bitPtr+n) & (BITS_PER_CHAR-1);       /* modulo by BITS_PER_CHAR */
 }
References bits(), BITS_PER_CHAR, and LOG2_BITS_PER_CHAR.
Referenced by nb_decode(), speex_default_user_handler(), and speex_inband_handler().
speex_bits_destroy()
void speex_bits_destroy (SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Frees all resources associated to a SpeexBits struct.
Right now this does nothing since no resources are allocated, but this could change in the future.
Definition at line 85 of file bits.c.
 {
    if (bits->owner)
       speex_free(bits->chars);
    /* Will do something once the allocation is dynamic */
 }
References bits(), and speex_free().
Referenced by CL_Disconnect(), and main().
speex_bits_init()
void speex_bits_init (SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Initializes and allocates resources for a SpeexBits struct.
Definition at line 48 of file bits.c.
 {
    bits->chars = (char*)speex_alloc(MAX_CHARS_PER_FRAME);
    if (!bits->chars)
       return;
    bits->buf_size = MAX_CHARS_PER_FRAME;
    bits->owner=1;
    speex_bits_reset(bits);
 }
References bits(), MAX_CHARS_PER_FRAME, speex_alloc(), and speex_bits_reset().
Referenced by CL_FirstSnapshot(), and main().
speex_bits_init_buffer()
void speex_bits_init_buffer (SpeexBits * bits, void * buff, int buf_size)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Initializes SpeexBits struct using a pre-allocated buffer.
Definition at line 61 of file bits.c.
 {
    bits->chars = (char*)buff;
    bits->buf_size = buf_size;
    bits->owner=0;
    speex_bits_reset(bits);
 }
References bits(), and speex_bits_reset().
speex_bits_insert_terminator()
void speex_bits_insert_terminator (SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Insert a terminator so that the data can be sent as a packet while auto-detecting the number of frames in each packet.
Parameters
bits Bit-stream to operate on
Definition at line 366 of file bits.c.
 {
    if (bits->bitPtr)
       speex_bits_pack(bits, 0, 1);
    while (bits->bitPtr)
       speex_bits_pack(bits, 1, 1);
 }
References bits(), and speex_bits_pack().
Referenced by speex_bits_write().
speex_bits_nbytes()
int speex_bits_nbytes (SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Returns the number of bytes in the bit-stream, including the last one even if it is not "full".
Parameters
bits Bit-stream to operate on
Returns
Number of bytes in the stream
Definition at line 361 of file bits.c.
 {
    return ((bits->nbBits+BITS_PER_CHAR-1)>>LOG2_BITS_PER_CHAR);
 }
References bits(), BITS_PER_CHAR, and LOG2_BITS_PER_CHAR.
speex_bits_pack()
void speex_bits_pack (SpeexBits * bits, int data, int nbBits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Append bits to the bit-stream.
Parameters
bits Bit-stream to operate on
data Value to append as integer
nbBits number of bits to consider in "data"
Definition at line 229 of file bits.c.
 {
    unsigned int d=data;
    if (bits->charPtr+((nbBits+bits->bitPtr)>>LOG2_BITS_PER_CHAR) >= bits->buf_size)
    {
       speex_notify("Buffer too small to pack bits");
       if (bits->owner)
       {
          int new_nchars = ((bits->buf_size+5)*3)>>1;
          char *tmp = (char*)speex_realloc(bits->chars, new_nchars);
          if (tmp)
          {
             bits->buf_size=new_nchars;
             bits->chars=tmp;
          } else {
             speex_warning("Could not resize input buffer: not packing");
             return;
          }
       } else {
          speex_warning("Do not own input buffer: not packing");
          return;
       }
    }
    while(nbBits)
    {
       int bit;
       bit = (d>>(nbBits-1))&1;
       bits->chars[bits->charPtr] |= bit<<(BITS_PER_CHAR-1-bits->bitPtr);
       bits->bitPtr++;
       if (bits->bitPtr==BITS_PER_CHAR)
       {
          bits->bitPtr=0;
          bits->charPtr++;
          bits->chars[bits->charPtr] = 0;
       }
       bits->nbBits++;
       nbBits--;
    }
 }
References bits(), BITS_PER_CHAR, LOG2_BITS_PER_CHAR, speex_notify(), speex_realloc(), and speex_warning().
Referenced by lsp_quant_high(), lsp_quant_lbr(), lsp_quant_nb(), nb_encode(), pitch_search_3tap(), sb_encode(), speex_bits_insert_terminator(), speex_encode_stereo(), speex_encode_stereo_int(), split_cb_search_shape_sign(), and split_cb_search_shape_sign_N1().
speex_bits_peek()
int speex_bits_peek (SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Get the value of the next bit in the stream, without modifying the "cursor" position.
Parameters
bits Bit-stream to operate on
Returns
Value of the bit peeked (one bit only)
Definition at line 334 of file bits.c.
 {
    if ((bits->charPtr<<LOG2_BITS_PER_CHAR)+bits->bitPtr+1>bits->nbBits)
       bits->overflow=1;
    if (bits->overflow)
       return 0;
    return (bits->chars[bits->charPtr]>>(BITS_PER_CHAR-1 - bits->bitPtr))&1;
 }
References bits(), BITS_PER_CHAR, and LOG2_BITS_PER_CHAR.
Referenced by sb_decode().
speex_bits_peek_unsigned()
unsigned int speex_bits_peek_unsigned (SpeexBits * bits, int nbBits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Same as speex_bits_unpack_unsigned, but without modifying the cursor position.
Parameters
bits Bit-stream to operate on
nbBits Number of bits to look for
Returns
Value of the bits peeked, interpreted as unsigned
Definition at line 305 of file bits.c.
 {
    unsigned int d=0;
    int bitPtr, charPtr;
    char *chars;
    if ((bits->charPtr<<LOG2_BITS_PER_CHAR)+bits->bitPtr+nbBits>bits->nbBits)
      bits->overflow=1;
    if (bits->overflow)
       return 0;
    bitPtr=bits->bitPtr;
    charPtr=bits->charPtr;
    chars = bits->chars;
    while(nbBits)
    {
       d<<=1;
       d |= (chars[charPtr]>>(BITS_PER_CHAR-1 - bitPtr))&1;
       bitPtr++;
       if (bitPtr==BITS_PER_CHAR)
       {
          bitPtr=0;
          charPtr++;
       }
       nbBits--;
    }
    return d;
 }
References bits(), BITS_PER_CHAR, and LOG2_BITS_PER_CHAR.
speex_bits_read_from()
void speex_bits_read_from (SpeexBits * bits, char * bytes, int len)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Initializes the bit-stream from the data in an area of memory.
Definition at line 109 of file bits.c.
 {
    int i;
    int nchars = len / BYTES_PER_CHAR;
    if (nchars > bits->buf_size)
    {
       speex_notify("Packet is larger than allocated buffer");
       if (bits->owner)
       {
          char *tmp = (char*)speex_realloc(bits->chars, nchars);
          if (tmp)
          {
             bits->buf_size=nchars;
             bits->chars=tmp;
          } else {
             nchars=bits->buf_size;
             speex_warning("Could not resize input buffer: truncating input");
          }
       } else {
          speex_warning("Do not own input buffer: truncating oversize input");
          nchars=bits->buf_size;
       }
    }
 #if (BYTES_PER_CHAR==2)
 /* Swap bytes to proper endian order (could be done externally) */
 #define HTOLS(A) ((((A) >> 8)&0xff)|(((A) & 0xff)<<8))
 #else
 #define HTOLS(A) (A)
 #endif
    for (i=0;i<nchars;i++)
       bits->chars[i]=HTOLS(chars[i]);
    bits->nbBits=nchars<<LOG2_BITS_PER_CHAR;
    bits->charPtr=0;
    bits->bitPtr=0;
    bits->overflow=0;
 }
References bits(), BYTES_PER_CHAR, HTOLS, LOG2_BITS_PER_CHAR, speex_notify(), speex_realloc(), and speex_warning().
speex_bits_read_whole_bytes()
void speex_bits_read_whole_bytes (SpeexBits * bits, char * bytes, int len)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Append bytes to the bit-stream.
Parameters
bits Bit-stream to operate on
bytes pointer to the bytes what will be appended
len Number of bytes of append
Definition at line 156 of file bits.c.
 {
    int i,pos;
    int nchars = nbytes/BYTES_PER_CHAR;
    if (((bits->nbBits+BITS_PER_CHAR-1)>>LOG2_BITS_PER_CHAR)+nchars > bits->buf_size)
    {
       /* Packet is larger than allocated buffer */
       if (bits->owner)
       {
          char *tmp = (char*)speex_realloc(bits->chars, (bits->nbBits>>LOG2_BITS_PER_CHAR)+nchars+1);
          if (tmp)
          {
             bits->buf_size=(bits->nbBits>>LOG2_BITS_PER_CHAR)+nchars+1;
             bits->chars=tmp;
          } else {
             nchars=bits->buf_size-(bits->nbBits>>LOG2_BITS_PER_CHAR)-1;
             speex_warning("Could not resize input buffer: truncating oversize input");
          }
       } else {
          speex_warning("Do not own input buffer: truncating oversize input");
          nchars=bits->buf_size;
       }
    }
    speex_bits_flush(bits);
    pos=bits->nbBits>>LOG2_BITS_PER_CHAR;
    for (i=0;i<nchars;i++)
       bits->chars[pos+i]=HTOLS(chars[i]);
    bits->nbBits+=nchars<<LOG2_BITS_PER_CHAR;
 }
References bits(), BITS_PER_CHAR, BYTES_PER_CHAR, HTOLS, LOG2_BITS_PER_CHAR, speex_bits_flush(), speex_realloc(), and speex_warning().
speex_bits_remaining()
int speex_bits_remaining (SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Returns the number of bits remaining to be read in a stream.
Parameters
bits Bit-stream to operate on
Returns
Number of bits that can still be read from the stream
Definition at line 353 of file bits.c.
 {
    if (bits->overflow)
       return -1;
    else
       return bits->nbBits-((bits->charPtr<<LOG2_BITS_PER_CHAR)+bits->bitPtr);
 }
References bits(), and LOG2_BITS_PER_CHAR.
Referenced by nb_decode(), and sb_decode().
speex_bits_reset()
void speex_bits_reset (SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Resets bits to initial value (just after initialization, erasing content)
Definition at line 92 of file bits.c.
 {
    /* We only need to clear the first byte now */
    bits->chars[0]=0;
    bits->nbBits=0;
    bits->charPtr=0;
    bits->bitPtr=0;
    bits->overflow=0;
 }
References bits().
Referenced by CL_FirstSnapshot(), main(), speex_bits_init(), and speex_bits_init_buffer().
speex_bits_rewind()
void speex_bits_rewind (SpeexBits * bits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Rewind the bit-stream to the beginning (ready for read) without erasing the content.
Definition at line 102 of file bits.c.
 {
    bits->charPtr=0;
    bits->bitPtr=0;
    bits->overflow=0;
 }
References bits().
Referenced by main().
speex_bits_set_bit_buffer()
void speex_bits_set_bit_buffer (SpeexBits * bits, void * buff, int buf_size)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Sets the bits in a SpeexBits struct to use data from an existing buffer (for decoding without copying data)
Definition at line 71 of file bits.c.
 {
    bits->chars = (char*)buff;
    bits->buf_size = buf_size;
    bits->owner=0;
    bits->nbBits=buf_size<<LOG2_BITS_PER_CHAR;
    bits->charPtr=0;
    bits->bitPtr=0;
    bits->overflow=0;
 }
References bits(), and LOG2_BITS_PER_CHAR.
speex_bits_unpack_signed()
int speex_bits_unpack_signed (SpeexBits * bits, int nbBits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Interpret the next bits in the bit-stream as a signed integer.
Parameters
bits Bit-stream to operate on
nbBits Number of bits to interpret
Returns
A signed integer represented by the bits read
Definition at line 272 of file bits.c.
 {
    unsigned int d=speex_bits_unpack_unsigned(bits,nbBits);
    /* If number is negative */
    if (d>>(nbBits-1))
    {
       d |= (-1)<<nbBits;
    }
    return d;
 }
References bits(), and speex_bits_unpack_unsigned().
speex_bits_unpack_unsigned()
unsigned int speex_bits_unpack_unsigned (SpeexBits * bits, int nbBits)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Interpret the next bits in the bit-stream as an unsigned integer.
Parameters
bits Bit-stream to operate on
nbBits Number of bits to interpret
Returns
An unsigned integer represented by the bits read
Definition at line 283 of file bits.c.
 {
    unsigned int d=0;
    if ((bits->charPtr<<LOG2_BITS_PER_CHAR)+bits->bitPtr+nbBits>bits->nbBits)
       bits->overflow=1;
    if (bits->overflow)
       return 0;
    while(nbBits)
    {
       d<<=1;
       d |= (bits->chars[bits->charPtr]>>(BITS_PER_CHAR-1 - bits->bitPtr))&1;
       bits->bitPtr++;
       if (bits->bitPtr==BITS_PER_CHAR)
       {
          bits->bitPtr=0;
          bits->charPtr++;
       }
       nbBits--;
    }
    return d;
 }
References bits(), BITS_PER_CHAR, and LOG2_BITS_PER_CHAR.
Referenced by lsp_unquant_high(), lsp_unquant_lbr(), lsp_unquant_nb(), nb_decode(), pitch_unquant_3tap(), sb_decode(), speex_bits_unpack_signed(), speex_default_user_handler(), speex_inband_handler(), speex_std_char_handler(), speex_std_enh_request_handler(), speex_std_high_mode_request_handler(), speex_std_low_mode_request_handler(), speex_std_mode_request_handler(), speex_std_stereo_request_handler(), speex_std_vbr_quality_request_handler(), speex_std_vbr_request_handler(), and split_cb_shape_sign_unquant().
speex_bits_write()
int speex_bits_write (SpeexBits * bits, char * bytes, int max_len)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Write the content of a bit-stream to an area of memory.
Parameters
bits Bit-stream to operate on
bytes Memory location where to write the bits
max_len Maximum number of bytes to write (i.e. size of the "bytes" buffer)
Returns
Number of bytes written to the "bytes" buffer
Definition at line 188 of file bits.c.
 {
    int i;
    int max_nchars = max_nbytes/BYTES_PER_CHAR;
    int charPtr, bitPtr, nbBits;
    /* Insert terminator, but save the data so we can put it back after */
    bitPtr=bits->bitPtr;
    charPtr=bits->charPtr;
    nbBits=bits->nbBits;
    speex_bits_insert_terminator(bits);
    bits->bitPtr=bitPtr;
    bits->charPtr=charPtr;
    bits->nbBits=nbBits;
    if (max_nchars > ((bits->nbBits+BITS_PER_CHAR-1)>>LOG2_BITS_PER_CHAR))
       max_nchars = ((bits->nbBits+BITS_PER_CHAR-1)>>LOG2_BITS_PER_CHAR);
    for (i=0;i<max_nchars;i++)
       chars[i]=HTOLS(bits->chars[i]);
    return max_nchars*BYTES_PER_CHAR;
 }
References bits(), BITS_PER_CHAR, BYTES_PER_CHAR, HTOLS, LOG2_BITS_PER_CHAR, and speex_bits_insert_terminator().
Referenced by main().
speex_bits_write_whole_bytes()
int speex_bits_write_whole_bytes (SpeexBits * bits, char * bytes, int max_len)
#include <Source/Engine/libspeex/include/speex/speex_bits.h>
Like speex_bits_write, but writes only the complete bytes in the stream.
Also removes the written bytes from the stream
Definition at line 211 of file bits.c.
 {
    int max_nchars = max_nbytes/BYTES_PER_CHAR;
    int i;
    if (max_nchars > ((bits->nbBits)>>LOG2_BITS_PER_CHAR))
       max_nchars = ((bits->nbBits)>>LOG2_BITS_PER_CHAR);
    for (i=0;i<max_nchars;i++)
       chars[i]=HTOLS(bits->chars[i]);
    if (bits->bitPtr>0)
       bits->chars[0]=bits->chars[max_nchars];
    else
       bits->chars[0]=0;
    bits->charPtr=0;
    bits->nbBits &= (BITS_PER_CHAR-1);
    return max_nchars*BYTES_PER_CHAR;
 }
References bits(), BITS_PER_CHAR, BYTES_PER_CHAR, HTOLS, and LOG2_BITS_PER_CHAR.
Variable Documentation
bitPtr
int SpeexBits::bitPtr
Position of the bit "cursor" within the current char.
Definition at line 53 of file speex_bits.h.
buf_size
int SpeexBits::buf_size
Allocated size for buffer.
Definition at line 56 of file speex_bits.h.
charPtr
int SpeexBits::charPtr
Position of the byte "cursor".
Definition at line 52 of file speex_bits.h.
chars
char* SpeexBits::chars
"raw" data
Definition at line 50 of file speex_bits.h.
nbBits
int SpeexBits::nbBits
Total number of bits stored in the stream.
Definition at line 51 of file speex_bits.h.
overflow
int SpeexBits::overflow
Set to one if we try to read past the valid data.
Definition at line 55 of file speex_bits.h.
owner
int SpeexBits::owner
Does the struct "own" the "raw" buffer (member "chars")
Definition at line 54 of file speex_bits.h.
reserved1
int SpeexBits::reserved1
Reserved for future use.
Definition at line 57 of file speex_bits.h.
reserved2
void* SpeexBits::reserved2
Reserved for future use.
Definition at line 58 of file speex_bits.h.