ZEQ2-Lite: Source/Game/CGame/cg_info.c File Reference
cg_info.c File Reference
#include "cg_local.h"
Macros
#define MAX_LOADING_PLAYER_ICONS 16
Functions
void CG_DrawInformation (void)
static void CG_DrawLoadingIcons (void)
void CG_LoadingClient (int clientNum)
void CG_LoadingString (const char *s)
Variables
static int loadingPlayerIconCount
static qhandle_t loadingPlayerIcons [MAX_LOADING_PLAYER_ICONS]
static char loadingPlayerNames [MAX_LOADING_PLAYER_ICONS][32]
Macro Definition Documentation
MAX_LOADING_PLAYER_ICONS
#define MAX_LOADING_PLAYER_ICONS 16
Definition at line 27 of file cg_info.c.
Function Documentation
CG_DrawInformation()
void CG_DrawInformation (void)
Definition at line 118 of file cg_info.c.
{
     const char  *s;
     const char  *info;
     const char  *sysInfo;
     int         y;
     int         value;
     qhandle_t   levelshot,text,dots;
     char        buf[1024];
     info = CG_ConfigString( CS_SERVERINFO );
     sysInfo = CG_ConfigString( CS_SYSTEMINFO );
     s = Info_ValueForKey(info,"mapname");
     levelshot = trap_R_RegisterShaderNoMip(va("maps/%s.jpg",s));
     dots = trap_R_RegisterShaderNoMip("dots");
     if(!levelshot){levelshot = trap_R_RegisterShaderNoMip("menuback");}
     trap_R_SetColor(NULL);
     CG_DrawPic(qfalse,0,0,SCREEN_WIDTH,SCREEN_HEIGHT,levelshot);
     CG_DrawLoadingIcons();
     if(cg.infoScreenText[0]){
         text = trap_R_RegisterShaderNoMip("loading");
         CG_DrawPic(qfalse,0,18,127,64,text);
         CG_DrawPic(qfalse,64,52,8,4,dots);
     }
     else{
         text = trap_R_RegisterShaderNoMip("ready");
         CG_DrawPic(qfalse,0,18,127,64,text);
     }
     y = 180-32;
     // Remote Server only
 }
References cg, CG_ConfigString(), CG_DrawLoadingIcons(), CG_DrawPic(), CS_SERVERINFO, CS_SYSTEMINFO, info, Info_ValueForKey(), cg_t::infoScreenText, NULL, qfalse, SCREEN_HEIGHT, SCREEN_WIDTH, trap_R_RegisterShaderNoMip(), trap_R_SetColor(), and va().
Referenced by CG_DrawActive(), and CG_DrawActiveFrame().
CG_DrawLoadingIcons()
static void CG_DrawLoadingIcons (void) static
Definition at line 38 of file cg_info.c.
{
     int     n;
     int     x, y;
     cgs.media.chatBackgroundShader = trap_R_RegisterShaderNoMip("chatBox");
     for( n = 0; n < loadingPlayerIconCount; n++ ) {
         y = 80 + (40 * n);
         CG_DrawPic(qfalse,-25,y-22,369,75,cgs.media.chatBackgroundShader );
         CG_DrawPic(qfalse,5,y,32,32,loadingPlayerIcons[n] );
         CG_DrawSmallStringCustom(42,y+10,11,11,loadingPlayerNames[n],1.0,6);
         //cgs.clientinfo[clientNum].name
     }
 }
References CG_DrawPic(), CG_DrawSmallStringCustom(), cgs, cgMedia_t::chatBackgroundShader, loadingPlayerIconCount, loadingPlayerIcons, loadingPlayerNames, cgs_t::media, qfalse, and trap_R_RegisterShaderNoMip().
Referenced by CG_DrawInformation().
CG_LoadingClient()
void CG_LoadingClient (int clientNum)
Definition at line 69 of file cg_info.c.
{
     const char      *info;
     char            *skin;
     char            name[32];
     char            personality[MAX_QPATH];
     char            model[MAX_QPATH];
     char            iconName[MAX_QPATH];
     info = CG_ConfigString( CS_PLAYERS + clientNum );
     if ( loadingPlayerIconCount < MAX_LOADING_PLAYER_ICONS ) {
         Q_strncpyz( name, Info_ValueForKey( info, "n" ), sizeof(name) );
         Q_strncpyz( model, Info_ValueForKey( info, "model" ), sizeof( model ) );
         skin = strrchr( model, '/' );
         if ( skin ) {
             *skin++ = '\0';
         } else {
             skin = "default";
         }
         Com_sprintf( iconName, MAX_QPATH, "players//%s/icon_%s.tga", model, skin );
         strcpy(loadingPlayerNames[loadingPlayerIconCount],name);
         loadingPlayerIcons[loadingPlayerIconCount] = trap_R_RegisterShaderNoMip( iconName );
         if ( !loadingPlayerIcons[loadingPlayerIconCount] ) {
             Com_sprintf( iconName, MAX_QPATH, "players//characters/%s/icon_%s.tga", model, skin );
             loadingPlayerIcons[loadingPlayerIconCount] = trap_R_RegisterShaderNoMip( iconName );
         }
         if ( !loadingPlayerIcons[loadingPlayerIconCount] ) {
             Com_sprintf( iconName, MAX_QPATH, "players//%s/icon_%s.tga", DEFAULT_MODEL, "default" );
             loadingPlayerIcons[loadingPlayerIconCount] = trap_R_RegisterShaderNoMip( iconName );
         }
         if ( loadingPlayerIcons[loadingPlayerIconCount] ) {
             loadingPlayerIconCount++;
         }
     }
     Q_strncpyz( personality, Info_ValueForKey( info, "n" ), sizeof(personality) );
     Q_CleanStr( personality );
     CG_LoadingString( personality );
 }
References CG_ConfigString(), CG_LoadingString(), Com_sprintf(), CS_PLAYERS, DEFAULT_MODEL, info, Info_ValueForKey(), loadingPlayerIconCount, loadingPlayerIcons, loadingPlayerNames, MAX_LOADING_PLAYER_ICONS, MAX_QPATH, Q_CleanStr(), Q_strncpyz(), and trap_R_RegisterShaderNoMip().
Referenced by CG_RegisterClients().
CG_LoadingString()
void CG_LoadingString (const char * s)
Definition at line 58 of file cg_info.c.
{
     Q_strncpyz( cg.infoScreenText, s, sizeof( cg.infoScreenText ) );
     trap_UpdateScreen();
 }
References cg, cg_t::infoScreenText, Q_strncpyz(), and trap_UpdateScreen().
Referenced by CG_Init(), CG_LoadingClient(), and CG_RegisterGraphics().
Variable Documentation
loadingPlayerIconCount
int loadingPlayerIconCount static
Definition at line 29 of file cg_info.c.
Referenced by CG_DrawLoadingIcons(), and CG_LoadingClient().
loadingPlayerIcons
qhandle_t loadingPlayerIcons[MAX_LOADING_PLAYER_ICONS] static
Definition at line 31 of file cg_info.c.
Referenced by CG_DrawLoadingIcons(), and CG_LoadingClient().
loadingPlayerNames
char loadingPlayerNames[MAX_LOADING_PLAYER_ICONS][32] static
Definition at line 30 of file cg_info.c.
Referenced by CG_DrawLoadingIcons(), and CG_LoadingClient().