ZEQ2-Lite: __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator > Class Template Reference
__gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator > Class Template Reference
#include <const_point_iterator.hpp>
Public Types
typedef Allocator::template rebind< value_type >::other::const_pointer const_pointer
typedef Allocator::template rebind< value_type >::other::const_reference const_reference
typedef trivial_iterator_difference_type difference_type
typedef trivial_iterator_tag iterator_category
typedef Allocator::template rebind< value_type >::other::pointer pointer
typedef Allocator::template rebind< value_type >::other::reference reference
typedef Value_Type value_type
Public Member Functions
binary_heap_const_point_iterator_ ()
binary_heap_const_point_iterator_ (const binary_heap_const_point_iterator_ &other)
binary_heap_const_point_iterator_ (entry_pointer p_e)
bool operator!= (const binary_heap_const_point_iterator_ &other) const
const_reference operator* () const
const_pointer operator-> () const
bool operator== (const binary_heap_const_point_iterator_ &other) const
Data Fields
entry_pointer m_p_e
Protected Types
typedef Allocator::template rebind< Entry >::other::pointer entry_pointer
Private Member Functions
const_pointer to_ptr (false_type) const
const_pointer to_ptr (true_type) const
Detailed Description
template<typename Value_Type, typename Entry, bool Simple, typename Allocator>
class __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >
Definition at line 55 of file const_point_iterator.hpp.
Member Typedef Documentation
const_pointer
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > typedef Allocator::template rebind<value_type>::other::const_pointer __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::const_pointer
Definition at line 77 of file const_point_iterator.hpp.
const_reference
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > typedef Allocator::template rebind<value_type>::other::const_reference __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::const_reference
Definition at line 87 of file const_point_iterator.hpp.
difference_type
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > typedef trivial_iterator_difference_type __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::difference_type
Definition at line 65 of file const_point_iterator.hpp.
entry_pointer
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > typedef Allocator::template rebind<Entry>::other::pointer __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::entry_pointer protected
Definition at line 58 of file const_point_iterator.hpp.
iterator_category
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > typedef trivial_iterator_tag __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::iterator_category
Definition at line 62 of file const_point_iterator.hpp.
pointer
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > typedef Allocator::template rebind<value_type>::other::pointer __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::pointer
Definition at line 72 of file const_point_iterator.hpp.
reference
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > typedef Allocator::template rebind<value_type>::other::reference __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::reference
Definition at line 82 of file const_point_iterator.hpp.
value_type
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > typedef Value_Type __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::value_type
Definition at line 68 of file const_point_iterator.hpp.
Constructor & Destructor Documentation
binary_heap_const_point_iterator_() [1/3]
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::binary_heap_const_point_iterator_ (entry_pointer p_e) inline
Definition at line 90 of file const_point_iterator.hpp.
                                                            : m_p_e(p_e)
       { }
binary_heap_const_point_iterator_() [2/3]
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::binary_heap_const_point_iterator_ () inline
Definition at line 95 of file const_point_iterator.hpp.
 : m_p_e(0) { }
binary_heap_const_point_iterator_() [3/3]
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::binary_heap_const_point_iterator_ (const binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator > & other) inline
Definition at line 99 of file const_point_iterator.hpp.
       : m_p_e(other.m_p_e)
       { }
Member Function Documentation
operator!=()
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > bool __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator!= (const binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator > & other) const inline
Definition at line 126 of file const_point_iterator.hpp.
       { return m_p_e != other.m_p_e; }
References __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::m_p_e.
operator*()
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > const_reference __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator* () const inline
Definition at line 113 of file const_point_iterator.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_p_e != 0);
     return *to_ptr(integral_constant<int, Simple>());
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::m_p_e, and __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::to_ptr().
operator->()
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > const_pointer __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator-> () const inline
Definition at line 105 of file const_point_iterator.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_p_e != 0);
     return to_ptr(integral_constant<int, Simple>());
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::m_p_e, and __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::to_ptr().
operator==()
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > bool __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator== (const binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator > & other) const inline
Definition at line 121 of file const_point_iterator.hpp.
       { return m_p_e == other.m_p_e; }
References __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::m_p_e.
to_ptr() [1/2]
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > const_pointer __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::to_ptr (false_type) const inline private
Definition at line 135 of file const_point_iterator.hpp.
       { return *m_p_e; }
References __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::m_p_e.
to_ptr() [2/2]
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > const_pointer __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::to_ptr (true_type) const inline private
Definition at line 131 of file const_point_iterator.hpp.
       { return m_p_e; }
References __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::m_p_e.
Referenced by __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator*(), and __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator->().
Field Documentation
m_p_e
template<typename Value_Type , typename Entry , bool Simple, typename Allocator > entry_pointer __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::m_p_e
Definition at line 139 of file const_point_iterator.hpp.
Referenced by __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator!=(), __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator*(), __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator->(), __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::operator==(), and __gnu_pbds::detail::binary_heap_const_point_iterator_< Value_Type, Entry, Simple, Allocator >::to_ptr().
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/binary_heap_/const_point_iterator.hpp