ZEQ2-Lite: Tools/MinGW/include/stdlib.h File Reference
stdlib.h File Reference
#include <_mingw.h>
#include <stddef.h>
Data Structures
struct div_t
struct ldiv_t
struct lldiv_t
Macros
#define __argc __argc_dll
#define __argv __argv_dll
#define __need_NULL
#define __need_size_t
#define __need_wchar_t
#define _doserrno (*__doserrno())
#define _environ _environ_dll
#define _fmode _fmode_dll
#define _MAX_DIR 256
#define _MAX_DRIVE (3)
#define _MAX_EXT 256
#define _MAX_FNAME 256
#define _MAX_PATH MAX_PATH
#define _osver _osver_dll
#define _pgmptr _pgmptr_dll
#define _winmajor _winmajor_dll
#define _winminor _winminor_dll
#define _winver _winver_dll
#define _WSTDLIB_DEFINED
#define environ _environ
#define errno (*_errno())
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define MAX_PATH (260)
#define MB_CUR_MAX __mb_cur_max_dll
#define RAND_MAX 0x7FFF
#define sys_errlist _sys_errlist
#define sys_nerr _sys_nerr_dll
Typedefs
typedef int(* _onexit_t) (void)
Functions
_CRTIMP int *__cdecl __MINGW_NOTHROW __doserrno (void)
double __cdecl __MINGW_NOTHROW __strtod (const char *, char **)
_CRTIMP void __cdecl __MINGW_NOTHROW _beep (unsigned int, unsigned int) __MINGW_ATTRIB_DEPRECATED
_CRTIMP char *__cdecl __MINGW_NOTHROW _ecvt (double, int, int *, int *)
_CRTIMP int *__cdecl __MINGW_NOTHROW _errno (void)
_CRTIMP void __cdecl __MINGW_NOTHROW _exit (int) __MINGW_ATTRIB_NORETURN
void __cdecl __MINGW_NOTHROW _Exit (int) __MINGW_ATTRIB_NORETURN
_CRTIMP char *__cdecl __MINGW_NOTHROW _fcvt (double, int, int *, int *)
_CRTIMP char *__cdecl __MINGW_NOTHROW _fullpath (char *, const char *, size_t)
_CRTIMP char *__cdecl __MINGW_NOTHROW _gcvt (double, int, char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW _itoa (int, char *, int)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _itow (int, wchar_t *, int)
_CRTIMP char *__cdecl __MINGW_NOTHROW _ltoa (long, char *, int)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _ltow (long, wchar_t *, int)
_CRTIMP void __cdecl __MINGW_NOTHROW _makepath (char *, const char *, const char *, const char *, const char *)
_onexit_t __cdecl __MINGW_NOTHROW _onexit (_onexit_t)
_CRTIMP int __cdecl __MINGW_NOTHROW _putenv (const char *)
_CRTIMP void __cdecl __MINGW_NOTHROW _searchenv (const char *, const char *, char *)
_CRTIMP void __cdecl __MINGW_NOTHROW _seterrormode (int) __MINGW_ATTRIB_DEPRECATED
_CRTIMP void __cdecl __MINGW_NOTHROW _sleep (unsigned long) __MINGW_ATTRIB_DEPRECATED
_CRTIMP void __cdecl __MINGW_NOTHROW _splitpath (const char *, char *, char *, char *, char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW _ultoa (unsigned long, char *, int)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _ultow (unsigned long, wchar_t *, int)
_CRTIMP double __cdecl __MINGW_NOTHROW _wtof (const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW _wtoi (const wchar_t *)
_CRTIMP long __cdecl __MINGW_NOTHROW _wtol (const wchar_t *)
_CRTIMP void __cdecl __MINGW_NOTHROW abort (void) __MINGW_ATTRIB_NORETURN
_CRTIMP int __cdecl __MINGW_NOTHROW abs (int) __MINGW_ATTRIB_CONST
int __cdecl __MINGW_NOTHROW atexit (void(*)(void))
_CRTIMP double __cdecl __MINGW_NOTHROW atof (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW atoi (const char *)
_CRTIMP long __cdecl __MINGW_NOTHROW atol (const char *)
_CRTIMP void *__cdecl bsearch (const void *, const void *, size_t, size_t, int(*)(const void *, const void *))
_CRTIMP void *__cdecl __MINGW_NOTHROW calloc (size_t, size_t) __MINGW_ATTRIB_MALLOC
_CRTIMP div_t __cdecl __MINGW_NOTHROW div (int, int) __MINGW_ATTRIB_CONST
_CRTIMP char *__cdecl __MINGW_NOTHROW ecvt (double, int, int *, int *)
_CRTIMP void __cdecl __MINGW_NOTHROW exit (int) __MINGW_ATTRIB_NORETURN
_CRTIMP char *__cdecl __MINGW_NOTHROW fcvt (double, int, int *, int *)
_CRTIMP void __cdecl __MINGW_NOTHROW free (void *)
_CRTIMP char *__cdecl __MINGW_NOTHROW gcvt (double, int, char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW getenv (const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW itoa (int, char *, int)
_CRTIMP long __cdecl __MINGW_NOTHROW labs (long) __MINGW_ATTRIB_CONST
_CRTIMP ldiv_t __cdecl __MINGW_NOTHROW ldiv (long, long) __MINGW_ATTRIB_CONST
long long __cdecl __MINGW_NOTHROW llabs (long long)
lldiv_t __cdecl __MINGW_NOTHROW lldiv (long long, long long) __MINGW_ATTRIB_CONST
_CRTIMP char *__cdecl __MINGW_NOTHROW ltoa (long, char *, int)
_CRTIMP void *__cdecl __MINGW_NOTHROW malloc (size_t) __MINGW_ATTRIB_MALLOC
_CRTIMP int __cdecl __MINGW_NOTHROW mblen (const char *, size_t)
_CRTIMP size_t __cdecl __MINGW_NOTHROW mbstowcs (wchar_t *, const char *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW mbtowc (wchar_t *, const char *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW putenv (const char *)
_CRTIMP void __cdecl qsort (void *, size_t, size_t, int(*)(const void *, const void *))
_CRTIMP int __cdecl __MINGW_NOTHROW rand (void)
_CRTIMP void *__cdecl __MINGW_NOTHROW realloc (void *, size_t)
_CRTIMP void __cdecl __MINGW_NOTHROW searchenv (const char *, const char *, char *)
_CRTIMP void __cdecl __MINGW_NOTHROW srand (unsigned int)
static __inline__ double __cdecl __MINGW_NOTHROW strtod (const char *__restrict__ __nptr, char **__restrict__ __endptr)
float __cdecl __MINGW_NOTHROW strtof (const char *__restrict__, char **__restrict__)
_CRTIMP long __cdecl __MINGW_NOTHROW strtol (const char *, char **, int)
long double __cdecl __MINGW_NOTHROW strtold (const char *__restrict__, char **__restrict__)
long long __cdecl __MINGW_NOTHROW strtoll (const char *__restrict__, char **__restrict, int)
_CRTIMP unsigned long __cdecl __MINGW_NOTHROW strtoul (const char *, char **, int)
unsigned long long __cdecl __MINGW_NOTHROW strtoull (const char *__restrict__, char **__restrict__, int)
_CRTIMP int __cdecl __MINGW_NOTHROW system (const char *)
_CRTIMP double __cdecl __MINGW_NOTHROW wcstod (const wchar_t *, wchar_t **)
float __cdecl __MINGW_NOTHROW wcstof (const wchar_t *__restrict__, wchar_t **__restrict__)
_CRTIMP long __cdecl __MINGW_NOTHROW wcstol (const wchar_t *, wchar_t **, int)
long double __cdecl __MINGW_NOTHROW wcstold (const wchar_t *__restrict__, wchar_t **__restrict__)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcstombs (char *, const wchar_t *, size_t)
_CRTIMP unsigned long __cdecl __MINGW_NOTHROW wcstoul (const wchar_t *, wchar_t **, int)
_CRTIMP int __cdecl __MINGW_NOTHROW wctomb (char *, wchar_t)
Variables
__MINGW_IMPORT int __argc_dll
__MINGW_IMPORT char ** __argv_dll
__MINGW_IMPORT int __mb_cur_max_dll
int _argc
char ** _argv
__MINGW_IMPORT char ** _environ_dll
__MINGW_IMPORT int _fmode_dll
__MINGW_IMPORT unsigned int _osver_dll
__MINGW_IMPORT char * _pgmptr_dll
__MINGW_IMPORT char * _sys_errlist []
__MINGW_IMPORT int _sys_nerr_dll
__MINGW_IMPORT unsigned int _winmajor_dll
__MINGW_IMPORT unsigned int _winminor_dll
__MINGW_IMPORT unsigned int _winver_dll
Macro Definition Documentation
__argc
#define __argc __argc_dll
Definition at line 98 of file stdlib.h.
__argv
#define __argv __argv_dll
Definition at line 99 of file stdlib.h.
__need_NULL
#define __need_NULL
Definition at line 19 of file stdlib.h.
__need_size_t
#define __need_size_t
Definition at line 17 of file stdlib.h.
__need_wchar_t
#define __need_wchar_t
Definition at line 18 of file stdlib.h.
_doserrno
#define _doserrno (*__doserrno())
Definition at line 141 of file stdlib.h.
_environ
#define _environ _environ_dll
Definition at line 159 of file stdlib.h.
_fmode
#define _fmode _fmode_dll
Definition at line 296 of file stdlib.h.
_MAX_DIR
#define _MAX_DIR 256
Definition at line 50 of file stdlib.h.
_MAX_DRIVE
#define _MAX_DRIVE (3)
Definition at line 49 of file stdlib.h.
_MAX_EXT
#define _MAX_EXT 256
Definition at line 52 of file stdlib.h.
_MAX_FNAME
#define _MAX_FNAME 256
Definition at line 51 of file stdlib.h.
_MAX_PATH
#define _MAX_PATH MAX_PATH
Definition at line 48 of file stdlib.h.
_osver
#define _osver _osver_dll
Definition at line 248 of file stdlib.h.
_pgmptr
#define _pgmptr _pgmptr_dll
Definition at line 270 of file stdlib.h.
_winmajor
#define _winmajor _winmajor_dll
Definition at line 250 of file stdlib.h.
_winminor
#define _winminor _winminor_dll
Definition at line 251 of file stdlib.h.
_winver
#define _winver _winver_dll
Definition at line 249 of file stdlib.h.
_WSTDLIB_DEFINED
#define _WSTDLIB_DEFINED
Definition at line 350 of file stdlib.h.
environ
#define environ _environ
Definition at line 163 of file stdlib.h.
errno
#define errno (*_errno())
Definition at line 138 of file stdlib.h.
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 34 of file stdlib.h.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 33 of file stdlib.h.
MAX_PATH
#define MAX_PATH (260)
Definition at line 45 of file stdlib.h.
MB_CUR_MAX
#define MB_CUR_MAX __mb_cur_max_dll
Definition at line 114 of file stdlib.h.
RAND_MAX
#define RAND_MAX 0x7FFF
Definition at line 28 of file stdlib.h.
sys_errlist
#define sys_errlist _sys_errlist
Definition at line 198 of file stdlib.h.
sys_nerr
#define sys_nerr _sys_nerr_dll
Definition at line 187 of file stdlib.h.
Typedef Documentation
_onexit_t
typedef int(* _onexit_t) (void)
Definition at line 414 of file stdlib.h.
Function Documentation
__doserrno()
_CRTIMP int* __cdecl __MINGW_NOTHROW __doserrno (void)
__strtod()
double __cdecl __MINGW_NOTHROW __strtod (const char * , char **)
Referenced by strtod().
_beep()
_CRTIMP void __cdecl __MINGW_NOTHROW _beep (unsigned int , unsigned int)
_ecvt()
_CRTIMP char* __cdecl __MINGW_NOTHROW _ecvt (double , int , int * , int *)
_errno()
_CRTIMP int* __cdecl __MINGW_NOTHROW _errno (void)
_exit()
_CRTIMP void __cdecl __MINGW_NOTHROW _exit (int)
Referenced by _Exit().
_Exit()
__CRT_INLINE void __cdecl __MINGW_NOTHROW _Exit (int __status)
Definition at line 507 of file stdlib.h.
     {  _exit (__status); }
References _exit().
_fcvt()
_CRTIMP char* __cdecl __MINGW_NOTHROW _fcvt (double , int , int * , int *)
_fullpath()
_CRTIMP char* __cdecl __MINGW_NOTHROW _fullpath (char * , const char * , size_t)
_gcvt()
_CRTIMP char* __cdecl __MINGW_NOTHROW _gcvt (double , int , char *)
_itoa()
_CRTIMP char* __cdecl __MINGW_NOTHROW _itoa (int , char * , int)
_itow()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _itow (int , wchar_t * , int)
_ltoa()
_CRTIMP char* __cdecl __MINGW_NOTHROW _ltoa (long , char * , int)
_ltow()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _ltow (long , wchar_t * , int)
_makepath()
_CRTIMP void __cdecl __MINGW_NOTHROW _makepath (char * , const char * , const char * , const char * , const char *)
_onexit()
_onexit_t __cdecl __MINGW_NOTHROW _onexit (_onexit_t)
_putenv()
_CRTIMP int __cdecl __MINGW_NOTHROW _putenv (const char *)
Referenced by Sys_GLimpInit(), Sys_GLimpSafeInit(), and Sys_SetEnv().
_searchenv()
_CRTIMP void __cdecl __MINGW_NOTHROW _searchenv (const char * , const char * , char *)
_seterrormode()
_CRTIMP void __cdecl __MINGW_NOTHROW _seterrormode (int)
_sleep()
_CRTIMP void __cdecl __MINGW_NOTHROW _sleep (unsigned long)
_splitpath()
_CRTIMP void __cdecl __MINGW_NOTHROW _splitpath (const char * , char * , char * , char * , char *)
_ultoa()
_CRTIMP char* __cdecl __MINGW_NOTHROW _ultoa (unsigned long , char * , int)
_ultow()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _ultow (unsigned long , wchar_t * , int)
_wtof()
_CRTIMP double __cdecl __MINGW_NOTHROW _wtof (const wchar_t *)
_wtoi()
_CRTIMP int __cdecl __MINGW_NOTHROW _wtoi (const wchar_t *)
_wtol()
_CRTIMP long __cdecl __MINGW_NOTHROW _wtol (const wchar_t *)
abort()
_CRTIMP void __cdecl __MINGW_NOTHROW abort (void)
Referenced by __gnu_profile::__env_to_size_t(), __gnu_profile::__open_output_file(), __gnu_pbds::__throw_container_error(), __gnu_pbds::__throw_insert_error(), __gnu_pbds::__throw_join_error(), __gnu_pbds::__throw_resize_error(), and checkhideset().
abs()
_CRTIMP int __cdecl __MINGW_NOTHROW abs (int)
Referenced by _GLIBCXX_VISIBILITY(), CIN_RunCinematic(), CL_AdjustTimeDelta(), CL_CreateCmd(), emit_condjump(), G_LocationImpact(), HashString(), hashtable_add(), hashtable_get(), hashtable_symbol_exists(), IN_JoyMove(), PM_CmdScale(), PmoveSingle(), and PredictPaeth().
atexit()
int __cdecl __MINGW_NOTHROW atexit (void(*)(void))
Referenced by __gnu_profile::__profcxx_init_unconditional().
atof()
_CRTIMP double __cdecl __MINGW_NOTHROW atof (const char *)
Referenced by aspectRatioCorrectedY(), BG_AddPredictableEventToPlayerstate(), CG_NewParticleArea(), CG_ParseAnimationFile(), CG_ServerCommand(), CG_weapGfx_NextSym(), Cmd_SetViewpos_f(), Com_Freeze_f(), Cvar_Get(), Cvar_Set2(), Cvar_Validate(), G_ParseField(), G_SpawnFloat(), G_weapPhys_NextSym(), __gnu_profile::__cost_factor_setter::operator()(), Parse1DMatrix(), parseAura(), ParseDeform(), ParseShader(), ParseSkyParms(), ParseSort(), ParseStage(), ParseTexMod(), parseTier(), ParseVector(), ParseWaveForm(), PSys_ParseConstraint(), PSys_ParseEmitter(), PSys_ParseForce(), PSys_ParseParticleTemplate(), PSys_ParseSystem(), PSys_ParseVector(), R_RemapShader(), RB_RenderFlares(), and UI_ParseAnimationFile().
atoi()
_CRTIMP int __cdecl __MINGW_NOTHROW atoi (const char *)
Referenced by __gnu_profile::__set_max_warn_count(), ArenaServers_Insert(), aspectRatioCorrectedY(), CG_CheckMusic(), CG_ConfigStringModified(), CG_Draw2D_f(), CG_DrawActiveFrame(), CG_GetMilliseconds(), CG_Init(), CG_NewParticleArea(), CG_ParseAnimationFile(), CG_ParseScores(), CG_ParseServerinfo(), CG_ParseTeamInfo(), CG_ParseWarmup(), CG_RegisterCvars(), CG_SetConfigValues(), CG_StartOrbit_f(), CG_TargetCommand_f(), CG_Tier_f(), CG_Weapon_f(), CheckTeamVote(), CL_ConfigstringModified(), CL_ConnectionlessPacket(), CL_GlobalServers_f(), CL_LoadConsoleHistory(), CL_ParseServerInfo(), CL_PlayDemo_f(), CL_ServerInfoPacket(), CL_SetServerInfo(), CL_SystemInfoChanged(), ClientForString(), ClientNumberFromString(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_GameCommand_f(), Cmd_TeamTask_f(), Cmd_Tell_f(), Cmd_VoiceTell_f(), Cmd_Wait_f(), Cvar_Get(), Cvar_Set2(), FS_IsDemoExt(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), G_InitWorldSession(), G_ParseField(), G_SpawnInt(), IN_KeyDown(), IN_KeyUp(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), LoadSMD_ParseTriangles(), main_init(), NET_StringToAdr(), parseAura(), ParseInt(), ParseStage(), parseTier(), PSys_ParseEmitter(), PSys_ParseParticleTemplate(), StartServer_Start(), StringToFilter(), SV_AddBanToList(), SV_DelBanFromList(), SV_DirectConnect(), SV_GetChallenge(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_MapRestart_f(), SV_NextDownload_f(), SV_ParseCIDRNotation(), SV_RehashBans_f(), SV_SetBrushModel(), SV_UserinfoChanged(), SV_VerifyPaks_f(), Sys_WritePIDFile(), SystemSettings_backChanges(), SystemSettings_CheckConfig(), SystemSettings_GetAspectRatios(), SystemSettings_GetInitialVideo(), SystemSettings_UpdateMenuItems(), TeamMain_MenuInit(), UI_GetArenaInfoByNumber(), and UI_ParseAnimationFile().
atol()
_CRTIMP long __cdecl __MINGW_NOTHROW atol (const char *)
Referenced by control(), and ParseNum().
bsearch()
_CRTIMP void* __cdecl bsearch (const void * , const void * , size_t , size_t , int(*)(const void *, const void *))
calloc()
_CRTIMP void* __cdecl __MINGW_NOTHROW calloc (size_t , size_t)
Referenced by AddFaces(), AddVertices(), alloc(), Com_InitHunkMemory(), Com_InitSmallZoneMemory(), Com_InitZoneMemory(), ComputeEdgeCollapseCost(), hashtable_add(), hashtable_init(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), LoadSMD_ParseTriangles(), ProgressiveMesh(), RemoveTriangle(), RemoveVertex(), SNDDMA_Init(), speex_alloc(), speex_alloc_scratch(), and zcalloc().
div()
_CRTIMP div_t __cdecl __MINGW_NOTHROW div (int , int)
ecvt()
_CRTIMP char* __cdecl __MINGW_NOTHROW ecvt (double , int , int * , int *)
exit()
_CRTIMP void __cdecl __MINGW_NOTHROW exit (int)
Referenced by __attribute__(), _speex_fatal(), alloc(), allocate(), ErrJump(), Error(), error(), error_exit(), fatal(), fillbuf(), interrupt(), main(), main_init(), spawn(), Sys_Error(), Sys_Exec(), Sys_Quit(), trap_Error(), VM_CallCompiled(), and VM_Compile().
fcvt()
_CRTIMP char* __cdecl __MINGW_NOTHROW fcvt (double , int , int * , int *)
free()
_CRTIMP void __cdecl __MINGW_NOTHROW free (void *)
Referenced by _mm_free(), dofree(), empty_mem_output_buffer(), EndOfScript(), jpeg_free_large(), jpeg_free_small(), main(), ProgressiveMesh(), QCopyFile(), R_LoadTGA(), SND_shutdown(), SNDDMA_Shutdown(), sort_symbols(), speex_free(), speex_free_scratch(), stabline(), VM_Destroy_Compiled(), and zcfree().
gcvt()
_CRTIMP char* __cdecl __MINGW_NOTHROW gcvt (double , int , char *)
getenv()
_CRTIMP char* __cdecl __MINGW_NOTHROW getenv (const char *)
Referenced by __gnu_profile::__env_to_size_t(), __gnu_profile::__set_max_warn_count(), __gnu_profile::__set_trace_path(), Com_Setenv_f(), initinputs(), jinit_memory_mgr(), main(), __gnu_profile::__cost_factor_setter::operator()(), Sys_DefaultHomePath(), Sys_Dialog(), Sys_PlatformInit(), and Sys_TempPath().
itoa()
_CRTIMP char* __cdecl __MINGW_NOTHROW itoa (int , char * , int)
labs()
_CRTIMP long __cdecl __MINGW_NOTHROW labs (long)
Referenced by caselabel().
ldiv()
_CRTIMP ldiv_t __cdecl __MINGW_NOTHROW ldiv (long , long)
llabs()
__CRT_INLINE long long __cdecl __MINGW_NOTHROW llabs (long long _j)
Definition at line 517 of file stdlib.h.
   {return (_j >= 0 ? _j : -_j);}
lldiv()
lldiv_t __cdecl __MINGW_NOTHROW lldiv (long long , long long)
ltoa()
_CRTIMP char* __cdecl __MINGW_NOTHROW ltoa (long , char * , int)
malloc()
_CRTIMP void* __cdecl __MINGW_NOTHROW malloc (size_t)
Referenced by _mm_malloc(), alloc(), allocate(), callsys(), copystring(), DefineSymbol(), domalloc(), empty_mem_output_buffer(), hashtable_new(), jpeg_get_large(), jpeg_get_small(), jpeg_mem_dest(), LoadFile(), LoadFileBlock(), LoadSourceFile(), R_LoadTGA(), SND_setup(), sort_symbols(), TryLoadFile(), VM_Compile(), and zcalloc().
mblen()
_CRTIMP int __cdecl __MINGW_NOTHROW mblen (const char * , size_t)
mbstowcs()
_CRTIMP size_t __cdecl __MINGW_NOTHROW mbstowcs (wchar_t * , const char * , size_t)
Referenced by mumble_link(), mumble_set_description(), and mumble_set_identity().
mbtowc()
_CRTIMP int __cdecl __MINGW_NOTHROW mbtowc (wchar_t * , const char * , size_t)
putenv()
_CRTIMP int __cdecl __MINGW_NOTHROW putenv (const char *)
qsort()
_CRTIMP void __cdecl qsort (void * , size_t , size_t , int(*)(const void *, const void *))
rand()
_CRTIMP int __cdecl __MINGW_NOTHROW rand (void)
Referenced by _GLIBCXX_VISIBILITY(), CG_BloodPool(), CG_BubbleTrail(), CG_EntityEvent(), CG_FireWeapon(), CG_MakeExplosion(), CG_MakeUserExplosion(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleMisc(), CG_ParticleSnowFlurry(), CG_UserMissileHitWall(), CG_WaterSplash(), CL_Connect_f(), CL_RequestMotd(), Com_RandomBytes(), eval(), G_PickTarget(), NET_Event(), __gnu_pbds::detail::counter_lu_policy_base< std::allocator< char > ::size_type >::operator()(), PSys_UpdateEmitters(), R_NoiseInit(), SelectRandomDeathmatchSpawnPoint(), SelectRandomTeamSpawnPoint(), SV_GetChallenge(), and SV_SpawnServer().
realloc()
_CRTIMP void* __cdecl __MINGW_NOTHROW realloc (void * , size_t)
Referenced by AddVertices(), callsys(), ComputeEdgeCollapseCost(), growtokenrow(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), LoadSMD_ParseTriangles(), newhideset(), RebuildNeighbors(), ReplaceVertex(), speex_realloc(), and UpdateNeighbors().
searchenv()
_CRTIMP void __cdecl __MINGW_NOTHROW searchenv (const char * , const char * , char *)
srand()
_CRTIMP void __cdecl __MINGW_NOTHROW srand (unsigned int)
Referenced by Com_InitRand(), and G_InitGame().
strtod()
static __inline__ double __cdecl __MINGW_NOTHROW strtod (const char *__restrict__ __nptr, char **__restrict__ __endptr) static
Definition at line 319 of file stdlib.h.
 {
   return __strtod(__nptr, __endptr);
 }
References __strtod().
Referenced by fcon(), main_init(), and Q_isanumber().
strtof()
float __cdecl __MINGW_NOTHROW strtof (const char * __restrict__, char ** __restrict__)
strtol()
_CRTIMP long __cdecl __MINGW_NOTHROW strtol (const char * , char ** , int)
Referenced by __gnu_profile::__env_to_size_t(), main_init(), and rule().
strtold()
long double __cdecl __MINGW_NOTHROW strtold (const char * __restrict__, char ** __restrict__)
strtoll()
long long __cdecl __MINGW_NOTHROW strtoll (const char * __restrict__, char ** __restrict, int)
strtoul()
_CRTIMP unsigned long __cdecl __MINGW_NOTHROW strtoul (const char * , char ** , int)
strtoull()
unsigned long long __cdecl __MINGW_NOTHROW strtoull (const char * __restrict__, char ** __restrict__, int)
Referenced by nexttok().
system()
_CRTIMP int __cdecl __MINGW_NOTHROW system (const char *)
Referenced by PSys_AccumulateParticle(), PSys_AccumulateSystem(), PSys_ApplyConstraint(), PSys_ApplyDistanceConstraint(), PSys_ApplyDistanceMaxConstraint(), PSys_ApplyDistanceMinConstraint(), PSys_ApplyPlaneConstraint(), PSys_ConstrainSystem(), PSys_FreeEmitter(), PSys_FreeSystem(), PSys_IntegrateSystem(), PSys_RenderSystems(), PSys_SpawnCachedSystem(), PSys_SpawnConstraint(), PSys_SpawnEmitter(), PSys_SpawnForce(), PSys_SpawnParticle(), PSys_SpawnSystem(), PSys_UpdateEmitters(), PSys_UpdateForces(), PSys_UpdateOrientation(), and PSys_UpdateSystems().
wcstod()
_CRTIMP double __cdecl __MINGW_NOTHROW wcstod (const wchar_t * , wchar_t **)
wcstof()
float __cdecl __MINGW_NOTHROW wcstof (const wchar_t * __restrict__, wchar_t ** __restrict__)
wcstol()
_CRTIMP long __cdecl __MINGW_NOTHROW wcstol (const wchar_t * , wchar_t ** , int)
wcstold()
long double __cdecl __MINGW_NOTHROW wcstold (const wchar_t * __restrict__, wchar_t ** __restrict__)
wcstombs()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcstombs (char * , const wchar_t * , size_t)
wcstoul()
_CRTIMP unsigned long __cdecl __MINGW_NOTHROW wcstoul (const wchar_t * , wchar_t ** , int)
wctomb()
_CRTIMP int __cdecl __MINGW_NOTHROW wctomb (char * , wchar_t)
Variable Documentation
__argc_dll
__MINGW_IMPORT int __argc_dll
Definition at line 96 of file stdlib.h.
__argv_dll
__MINGW_IMPORT char** __argv_dll
Definition at line 97 of file stdlib.h.
__mb_cur_max_dll
__MINGW_IMPORT int __mb_cur_max_dll
Definition at line 115 of file stdlib.h.
_argc
int _argc
_argv
char** _argv
_environ_dll
__MINGW_IMPORT char** _environ_dll
Definition at line 158 of file stdlib.h.
_fmode_dll
__MINGW_IMPORT int _fmode_dll
Definition at line 295 of file stdlib.h.
_osver_dll
__MINGW_IMPORT unsigned int _osver_dll
Definition at line 243 of file stdlib.h.
_pgmptr_dll
__MINGW_IMPORT char* _pgmptr_dll
Definition at line 269 of file stdlib.h.
_sys_errlist
__MINGW_IMPORT char* _sys_errlist[]
Definition at line 196 of file stdlib.h.
_sys_nerr_dll
__MINGW_IMPORT int _sys_nerr_dll
Definition at line 186 of file stdlib.h.
_winmajor_dll
__MINGW_IMPORT unsigned int _winmajor_dll
Definition at line 245 of file stdlib.h.
_winminor_dll
__MINGW_IMPORT unsigned int _winminor_dll
Definition at line 246 of file stdlib.h.
_winver_dll
__MINGW_IMPORT unsigned int _winver_dll
Definition at line 244 of file stdlib.h.