ZEQ2-Lite: Shared/puff.c File Reference
puff.c File Reference
#include <setjmp.h>
#include "puff.h"
Data Structures
struct huffman
struct state
Macros
#define FIXLCODES 288 /* number of fixed literal/length codes */
#define local static /* for local function definitions */
#define MAXBITS 15 /* maximum bits in a code */
#define MAXCODES (MAXLCODES+MAXDCODES) /* maximum codes lengths to read */
#define MAXDCODES 30 /* maximum number of distance codes */
#define MAXLCODES 286 /* maximum number of literal/length codes */
Functions
int32_t bits (struct state *s, int32_t need)
int32_t codes (struct state *s, struct huffman *lencode, struct huffman *distcode)
int32_t construct (struct huffman *h, int16_t *length, int32_t n)
int32_t decode (struct state *s, struct huffman *h)
int32_t dynamic (struct state *s)
int32_t fixed (struct state *s)
int32_t puff (uint8_t *dest, uint32_t *destlen, uint8_t *source, uint32_t *sourcelen)
int32_t stored (struct state *s)
Macro Definition Documentation
FIXLCODES
#define FIXLCODES 288 /* number of fixed literal/length codes */
Definition at line 85 of file puff.c.
local
#define local static /* for local function definitions */
Definition at line 75 of file puff.c.
MAXBITS
#define MAXBITS 15 /* maximum bits in a code */
Definition at line 81 of file puff.c.
MAXCODES
#define MAXCODES (MAXLCODES+MAXDCODES) /* maximum codes lengths to read */
Definition at line 84 of file puff.c.
MAXDCODES
#define MAXDCODES 30 /* maximum number of distance codes */
Definition at line 83 of file puff.c.
MAXLCODES
#define MAXLCODES 286 /* maximum number of literal/length codes */
Definition at line 82 of file puff.c.
Function Documentation
bits()
int32_t bits (struct state * s, int32_t need)
Definition at line 116 of file puff.c.
 {
     int32_t val;           /* bit accumulator (can use up to 20 bits) */
     /* load at least need bits into val */
     val = s->bitbuf;
     while (s->bitcnt < need) {
         if (s->incnt == s->inlen) longjmp(s->env, 1);   /* out of input */
         val |= (int32_t)(s->in[s->incnt++]) << s->bitcnt;  /* load eight bits */
         s->bitcnt += 8;
     }
     /* drop need bits and update buffer, always zero to seven bits left */
     s->bitbuf = (int32_t)(val >> need);
     s->bitcnt -= need;
     /* return need bits, zeroing the bits above that */
     return (int32_t)(val & ((1L << need) - 1));
 }
References val.
Referenced by add_huff_table(), CG_DrawWeaponSelectHorCenterBar(), CG_DrawWeaponSelectQuarterFan(), CL_PlayCinematic_f(), CM_SignbitsForNormal(), CMod_LoadPlanes(), codes(), dynamic(), fields(), fixedtables(), G_AddEvent(), GametypeBits(), get_dht(), inflate(), inflate_fast(), inflate_table(), inflatePrime(), initfields(), jpeg_gen_optimal_table(), lsp_quant_high(), lsp_quant_lbr(), lsp_quant_nb(), lsp_unquant_high(), lsp_unquant_lbr(), lsp_unquant_nb(), main(), MSG_ReadBits(), MSG_ReadDelta(), MSG_ReadDeltaKey(), MSG_ReadDeltaPlayerstate(), MSG_WriteBits(), MSG_WriteDelta(), MSG_WriteDeltaKey(), nb_decode(), nb_encode(), pitch_search_3tap(), pitch_unquant_3tap(), puff(), R_LoadPlanes(), S_ReadRIFFHeader(), sb_decode(), sb_encode(), SetPlaneSignbits(), speex_bits_advance(), speex_bits_destroy(), speex_bits_flush(), speex_bits_init(), speex_bits_init_buffer(), speex_bits_insert_terminator(), speex_bits_nbytes(), speex_bits_pack(), speex_bits_peek(), speex_bits_peek_unsigned(), speex_bits_read_from(), speex_bits_read_whole_bytes(), speex_bits_remaining(), speex_bits_reset(), speex_bits_rewind(), speex_bits_set_bit_buffer(), speex_bits_unpack_signed(), speex_bits_unpack_unsigned(), speex_bits_write(), speex_bits_write_whole_bytes(), speex_decode(), speex_decode_int(), speex_decode_native(), speex_default_user_handler(), speex_encode(), speex_encode_int(), speex_encode_native(), speex_encode_stereo(), speex_encode_stereo_int(), speex_inband_handler(), speex_std_char_handler(), speex_std_enh_request_handler(), speex_std_high_mode_request_handler(), speex_std_low_mode_request_handler(), speex_std_mode_request_handler(), speex_std_stereo_request_handler(), speex_std_vbr_quality_request_handler(), speex_std_vbr_request_handler(), split_cb_search_shape_sign(), split_cb_search_shape_sign_N1(), split_cb_shape_sign_unquant(), trap_CIN_PlayCinematic(), and vimm().
codes()
int32_t codes (struct state * s, struct huffman * lencode, struct huffman * distcode)
Definition at line 389 of file puff.c.
 {
     int32_t symbol;         /* decoded symbol */
     int32_t len;            /* length for copy */
     uint32_t dist;          /* distance for copy */
     static const int16_t lens[29] = { /* Size base for length codes 257..285 */
         3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31,
         35, 43, 51, 59, 67, 83, 99, 115, 131, 163, 195, 227, 258};
     static const int16_t lext[29] = { /* Extra bits for length codes 257..285 */
         0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2,
         3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
     static const int16_t dists[30] = { /* Offset base for distance codes 0..29 */
         1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193,
         257, 385, 513, 769, 1025, 1537, 2049, 3073, 4097, 6145,
         8193, 12289, 16385, 24577};
     static const int16_t dext[30] = { /* Extra bits for distance codes 0..29 */
         0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6,
         7, 7, 8, 8, 9, 9, 10, 10, 11, 11,
         12, 12, 13, 13};
     /* decode literals and length/distance pairs */
     do {
         symbol = decode(s, lencode);
         if (symbol < 0) return symbol;  /* invalid symbol */
         if (symbol < 256) {             /* literal: symbol is the byte */
             /* write out the literal */
             if (s->out != NULL) {
                 if (s->outcnt == s->outlen) return 1;
                 s->out[s->outcnt] = symbol;
             }
             s->outcnt++;
         }
         else if (symbol > 256) {        /* length */
             /* get and compute length */
             symbol -= 257;
             if (symbol >= 29) return -9;        /* invalid fixed code */
             len = lens[symbol] + bits(s, lext[symbol]);
             /* get and check distance */
             symbol = decode(s, distcode);
             if (symbol < 0) return symbol;      /* invalid symbol */
             dist = dists[symbol] + bits(s, dext[symbol]);
             if (dist > s->outcnt)
                 return -10;     /* distance too far back */
             /* copy length bytes from distance bytes back */
             if (s->out != NULL) {
                 if (s->outcnt + len > s->outlen) return 1;
                 while (len--) {
                     s->out[s->outcnt] = s->out[s->outcnt - dist];
                     s->outcnt++;
                 }
             }
             else
                 s->outcnt += len;
         }
     } while (symbol != 256);            /* end of block symbol */
     /* done with a valid fixed or dynamic block */
     return 0;
 }
References bits(), decode(), and NULL.
Referenced by dynamic(), fixed(), and inflate_table().
construct()
int32_t construct (struct huffman * h, int16_t * length, int32_t n)
Definition at line 294 of file puff.c.
 {
     int32_t symbol;         /* current symbol when stepping through length[] */
     int32_t len;            /* current length when stepping through h->count[] */
     int32_t left;           /* number of possible codes left of current length */
     int16_t offs[MAXBITS+1];      /* offsets in symbol table for each length */
     /* count number of codes of each length */
     for (len = 0; len <= MAXBITS; len++)
         h->count[len] = 0;
     for (symbol = 0; symbol < n; symbol++)
         (h->count[length[symbol]])++;   /* assumes lengths are within bounds */
     if (h->count[0] == n)               /* no codes! */
         return 0;                       /* complete, but decode() will fail */
     /* check for an over-subscribed or incomplete set of lengths */
     left = 1;                           /* one possible code of zero length */
     for (len = 1; len <= MAXBITS; len++) {
         left <<= 1;                     /* one more bit, double codes left */
         left -= h->count[len];          /* deduct count from possible codes */
         if (left < 0) return left;      /* over-subscribed--return negative */
     }                                   /* left > 0 means incomplete */
     /* generate offsets into symbol table for each length for sorting */
     offs[1] = 0;
     for (len = 1; len < MAXBITS; len++)
         offs[len + 1] = offs[len] + h->count[len];
     /*
      * put symbols in table sorted by length, by symbol order within each
      * length
      */
     for (symbol = 0; symbol < n; symbol++)
         if (length[symbol] != 0)
             h->symbol[offs[length[symbol]]++] = symbol;
     /* return zero for complete set, positive for incomplete set */
     return left;
 }
References huffman::count, MAXBITS, and huffman::symbol.
Referenced by dynamic(), and fixed().
decode()
int32_t decode (struct state * s, struct huffman * h)
Definition at line 221 of file puff.c.
 {
     int32_t len;            /* current number of bits in code */
     int32_t code;           /* len bits being decoded */
     int32_t first;          /* first code of length len */
     int32_t count;          /* number of codes of length len */
     int32_t index;          /* index of first code of length len in symbol table */
     int32_t bitbuf;         /* bits from stream */
     int32_t left;           /* bits left in next or left to process */
     int16_t *next;        /* next number of codes */
     bitbuf = s->bitbuf;
     left = s->bitcnt;
     code = first = index = 0;
     len = 1;
     next = h->count + 1;
     while (1) {
         while (left--) {
             code |= bitbuf & 1;
             bitbuf >>= 1;
             count = *next++;
             if (code < first + count) { /* if length len, return symbol */
                 s->bitbuf = bitbuf;
                 s->bitcnt = (s->bitcnt - len) & 7;
                 return h->symbol[index + (code - first)];
             }
             index += count;             /* else update for next length */
             first += count;
             first <<= 1;
             code <<= 1;
             len++;
         }
         left = (MAXBITS+1) - len;
         if (left == 0) break;
         if (s->incnt == s->inlen) longjmp(s->env, 1);   /* out of input */
         bitbuf = s->in[s->incnt++];
         if (left > 8) left = 8;
     }
     return -9;                          /* ran out of codes */
 }
References code, huffman::count, MAXBITS, and huffman::symbol.
Referenced by codes(), and dynamic().
dynamic()
int32_t dynamic (struct state * s)
Definition at line 601 of file puff.c.
 {
     int32_t nlen, ndist, ncode;             /* number of lengths in descriptor */
     int32_t index;                          /* index of lengths[] */
     int32_t err;                            /* construct() return value */
     int16_t lengths[MAXCODES];            /* descriptor code lengths */
     int16_t lencnt[MAXBITS+1], lensym[MAXLCODES];         /* lencode memory */
     int16_t distcnt[MAXBITS+1], distsym[MAXDCODES];       /* distcode memory */
     struct huffman lencode = {lencnt, lensym};          /* length code */
     struct huffman distcode = {distcnt, distsym};       /* distance code */
     static const int16_t order[19] =      /* permutation of code length codes */
         {16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15};
     /* get number of lengths in each table, check lengths */
     nlen = bits(s, 5) + 257;
     ndist = bits(s, 5) + 1;
     ncode = bits(s, 4) + 4;
     if (nlen > MAXLCODES || ndist > MAXDCODES)
         return -3;                      /* bad counts */
     /* read code length code lengths (really), missing lengths are zero */
     for (index = 0; index < ncode; index++)
         lengths[order[index]] = bits(s, 3);
     for (; index < 19; index++)
         lengths[order[index]] = 0;
     /* build huffman table for code lengths codes (use lencode temporarily) */
     err = construct(&lencode, lengths, 19);
     if (err != 0) return -4;            /* require complete code set here */
     /* read length/literal and distance code length tables */
     index = 0;
     while (index < nlen + ndist) {
         int32_t symbol;             /* decoded value */
         int32_t len;                /* last length to repeat */
         symbol = decode(s, &lencode);
         if (symbol < 16)                /* length in 0..15 */
             lengths[index++] = symbol;
         else {                          /* repeat instruction */
             len = 0;                    /* assume repeating zeros */
             if (symbol == 16) {         /* repeat last length 3..6 times */
                 if (index == 0) return -5;      /* no last length! */
                 len = lengths[index - 1];       /* last length */
                 symbol = 3 + bits(s, 2);
             }
             else if (symbol == 17)      /* repeat zero 3..10 times */
                 symbol = 3 + bits(s, 3);
             else                        /* == 18, repeat zero 11..138 times */
                 symbol = 11 + bits(s, 7);
             if (index + symbol > nlen + ndist)
                 return -6;              /* too many lengths! */
             while (symbol--)            /* repeat last or zero symbol times */
                 lengths[index++] = len;
         }
     }
     /* build huffman table for literal/length codes */
     err = construct(&lencode, lengths, nlen);
     if (err < 0 || (err > 0 && nlen - lencode.count[0] != 1))
         return -7;      /* only allow incomplete codes if just one code */
     /* build huffman table for distance codes */
     err = construct(&distcode, lengths + nlen, ndist);
     if (err < 0 || (err > 0 && ndist - distcode.count[0] != 1))
         return -8;      /* only allow incomplete codes if just one code */
     /* decode data until end-of-block code */
     return codes(s, &lencode, &distcode);
 }
References bits(), codes(), construct(), huffman::count, decode(), MAXBITS, MAXCODES, MAXDCODES, MAXLCODES, and huffman::symbol.
Referenced by puff(), and RB_CalcDynamicColor().
fixed()
int32_t fixed (struct state * s)
Definition at line 477 of file puff.c.
 {
     static int32_t virgin = 1;
     static int16_t lencnt[MAXBITS+1], lensym[FIXLCODES];
     static int16_t distcnt[MAXBITS+1], distsym[MAXDCODES];
     static struct huffman lencode = {lencnt, lensym};
     static struct huffman distcode = {distcnt, distsym};
     /* build fixed huffman tables if first call (may not be thread safe) */
     if (virgin) {
         int32_t symbol;
         int16_t lengths[FIXLCODES];
         /* literal/length table */
         for (symbol = 0; symbol < 144; symbol++)
             lengths[symbol] = 8;
         for (; symbol < 256; symbol++)
             lengths[symbol] = 9;
         for (; symbol < 280; symbol++)
             lengths[symbol] = 7;
         for (; symbol < FIXLCODES; symbol++)
             lengths[symbol] = 8;
         construct(&lencode, lengths, FIXLCODES);
         /* distance table */
         for (symbol = 0; symbol < MAXDCODES; symbol++)
             lengths[symbol] = 5;
         construct(&distcode, lengths, MAXDCODES);
         /* do this just once */
         virgin = 0;
     }
     /* decode data until end-of-block code */
     return codes(s, &lencode, &distcode);
 }
References codes(), construct(), FIXLCODES, MAXBITS, MAXDCODES, and huffman::symbol.
Referenced by fixedtables(), and puff().
puff()
int32_t puff (uint8_t * dest, uint32_t * destlen, uint8_t * source, uint32_t * sourcelen)
Definition at line 715 of file puff.c.
 {
     struct state s;             /* input/output state */
     int32_t last, type;             /* block information */
     int32_t err;                    /* return value */
     /* initialize output state */
     s.out = dest;
     s.outlen = *destlen;                /* ignored if dest is NULL */
     s.outcnt = 0;
     /* initialize input state */
     s.in = source;
     s.inlen = *sourcelen;
     s.incnt = 0;
     s.bitbuf = 0;
     s.bitcnt = 0;
     /* return if bits() or decode() tries to read past available input */
     if (setjmp(s.env) != 0)             /* if came back here via longjmp() */
         err = 2;                        /* then skip do-loop, return error */
     else {
         /* process blocks until last block or error */
         do {
             last = bits(&s, 1);         /* one if last block */
             type = bits(&s, 2);         /* block type 0..3 */
             err = type == 0 ? stored(&s) :
                   (type == 1 ? fixed(&s) :
                    (type == 2 ? dynamic(&s) :
                     -1));               /* type == 3, invalid */
             if (err != 0) break;        /* return with error */
         } while (!last);
     }
     /* update the lengths and return */
     if (err <= 0) {
         *destlen = s.outcnt;
         *sourcelen = s.incnt;
     }
     return err;
 }
References bits(), dynamic(), fixed(), and stored().
Referenced by DecompressIDATs().
stored()
int32_t stored (struct state * s)
Definition at line 153 of file puff.c.
 {
     uint32_t len;       /* length of stored block */
     /* discard leftover bits from current byte (assumes s->bitcnt < 8) */
     s->bitbuf = 0;
     s->bitcnt = 0;
     /* get length and check against its one's complement */
     if (s->incnt + 4 > s->inlen) return 2;      /* not enough input */
     len = s->in[s->incnt++];
     len |= s->in[s->incnt++] << 8;
     if (s->in[s->incnt++] != (~len & 0xff) ||
         s->in[s->incnt++] != ((~len >> 8) & 0xff))
         return -2;                              /* didn't match complement! */
     /* copy len bytes from in to out */
     if (s->incnt + len > s->inlen) return 2;    /* not enough input */
     if (s->out != NULL) {
         if (s->outcnt + len > s->outlen)
             return 1;                           /* not enough output space */
         while (len--)
             s->out[s->outcnt++] = s->in[s->incnt++];
     }
     else {                                      /* just scanning */
         s->outcnt += len;
         s->incnt += len;
     }
     /* done with a valid stored block */
     return 0;
 }
References NULL.
Referenced by puff().