ZEQ2-Lite: __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator > Class Template Reference
__gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator > Class Template Reference
#include <point_iterators.hpp>
Public Member Functions
bin_search_tree_it_ (const Node_Pointer p_nd=0)
bin_search_tree_it_ (const PB_DS_TREE_ODIR_IT_C_DEC &other)
PB_DS_TREE_CONST_IT_C_DEC::reference operator* () const
PB_DS_TREE_IT_C_DEC & operator++ ()
PB_DS_TREE_IT_C_DEC operator++ (int)
PB_DS_TREE_IT_C_DEC & operator-- ()
PB_DS_TREE_IT_C_DEC operator-- (int)
PB_DS_TREE_CONST_IT_C_DEC::pointer operator-> () const
PB_DS_TREE_IT_C_DEC & operator= (const PB_DS_TREE_IT_C_DEC &other)
PB_DS_TREE_IT_C_DEC & operator= (const PB_DS_TREE_ODIR_IT_C_DEC &other)
Protected Types
typedef PB_DS_TREE_CONST_IT_C_DEC base_it_type
Detailed Description
template<typename Node_Pointer, typename Value_Type, typename Pointer, typename Const_Pointer, typename Reference, typename Const_Reference, bool Is_Forward_Iterator, class Allocator>
class __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >
Definition at line 292 of file point_iterators.hpp.
Member Typedef Documentation
base_it_type
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > typedef PB_DS_TREE_CONST_IT_C_DEC __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::base_it_type protected
Definition at line 370 of file point_iterators.hpp.
Constructor & Destructor Documentation
bin_search_tree_it_() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::bin_search_tree_it_ (const Node_Pointer p_nd = 0) inline
Definition at line 300 of file point_iterators.hpp.
       : PB_DS_TREE_CONST_IT_C_DEC((Node_Pointer)p_nd)
       { }
bin_search_tree_it_() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::bin_search_tree_it_ (const PB_DS_TREE_ODIR_IT_C_DEC & other) inline
Definition at line 305 of file point_iterators.hpp.
       : PB_DS_TREE_CONST_IT_C_DEC(other.m_p_nd)
       { }
Member Function Documentation
operator*()
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_CONST_IT_C_DEC::reference __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator* () const inline
Definition at line 333 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(base_it_type::m_p_nd != 0);
     return base_it_type::m_p_nd->m_value;
       }
References _GLIBCXX_DEBUG_ASSERT.
operator++() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_IT_C_DEC& __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++ () inline
Definition at line 340 of file point_iterators.hpp.
       {
     PB_DS_TREE_CONST_IT_C_DEC:: operator++();
     return *this;
       }
Referenced by __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++().
operator++() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_IT_C_DEC __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++ (int) inline
Definition at line 347 of file point_iterators.hpp.
       {
     PB_DS_TREE_IT_C_DEC ret_it(base_it_type::m_p_nd);
     operator++();
     return ret_it;
       }
References __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++(), and PB_DS_TREE_IT_C_DEC.
operator--() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_IT_C_DEC& __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator-- () inline
Definition at line 355 of file point_iterators.hpp.
       {
     PB_DS_TREE_CONST_IT_C_DEC:: operator--();
     return *this;
       }
Referenced by __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator--().
operator--() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_IT_C_DEC __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator-- (int) inline
Definition at line 362 of file point_iterators.hpp.
       {
     PB_DS_TREE_IT_C_DEC ret_it(base_it_type::m_p_nd);
     operator--();
     return ret_it;
       }
References __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator--(), and PB_DS_TREE_IT_C_DEC.
operator->()
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_CONST_IT_C_DEC::pointer __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator-> () const inline
Definition at line 326 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(base_it_type::m_p_nd != 0);
     return &base_it_type::m_p_nd->m_value;
       }
References _GLIBCXX_DEBUG_ASSERT.
operator=() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_IT_C_DEC& __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator= (const PB_DS_TREE_IT_C_DEC & other) inline
Definition at line 311 of file point_iterators.hpp.
       {
     base_it_type::m_p_nd = other.m_p_nd;
     return *this;
       }
operator=() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_IT_C_DEC& __gnu_pbds::detail::bin_search_tree_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator= (const PB_DS_TREE_ODIR_IT_C_DEC & other) inline
Definition at line 319 of file point_iterators.hpp.
       {
     base_it_type::m_p_nd = other.m_p_nd;
     return *this;
       }
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/bin_search_tree_/point_iterators.hpp