ZEQ2-Lite: Engine/tools/lcc/src/bytecode.c File Reference
bytecode.c File Reference
#include "c.h"
Macros
#define b_blockbeg blockbeg
#define b_blockend blockend
#define I(f) b_##f
Functions
static void I() address (Symbol q, Symbol p, long n)
static void I() defaddress (Symbol p)
static void I() defconst (int suffix, int size, Value v)
static void I() defstring (int len, char *str)
static void I() defsymbol (Symbol p)
static void dumptree (Node p)
static void I() emit (Node p)
static void I() export (Symbol p)
static int filelength (FILE *f)
static void I() function (Symbol f, Symbol caller[], Symbol callee[], int ncalls)
static Node I() gen (Node p)
static void gen01 (Node p)
static void gen02 (Node p)
static void I() global (Symbol p)
static void I() import (Symbol p)
static void LoadSourceFile (const char *filename)
static void I() local (Symbol p)
static void PrintToSourceLine (int line)
static void I() progbeg (int argc, char *argv[])
static void I() progend (void)
static void I() segment (int n)
static void I() space (int n)
static void I() stabline (Coordinate *cp)
Variables
Interface bytecodeIR
static char * sourceFile
static int sourceLine
static char * sourcePtr
Macro Definition Documentation
b_blockbeg
#define b_blockbeg blockbeg
Definition at line 320 of file bytecode.c.
b_blockend
#define b_blockend blockend
Definition at line 321 of file bytecode.c.
I
#define I (f) b_##f
Definition at line 2 of file bytecode.c.
Function Documentation
address()
static void I() address (Symbol q, Symbol p, long n) static
Definition at line 18 of file bytecode.c.
{
     q->x.name = stringf("%s%s%D", p->x.name, n > 0 ? "+" : "", n);
 }
References stringf().
defaddress()
static void I() defaddress (Symbol p) static
Definition at line 22 of file bytecode.c.
{
     print("address %s\n", p->x.name);
 }
References print().
defconst()
static void I() defconst (int suffix, int size, Value v) static
Definition at line 26 of file bytecode.c.
{
     switch (suffix) {
     case I:
         if (size > sizeof (int))
             print("byte %d %D\n", size, v.i);
         else
             print("byte %d %d\n", size, v.i);
         return;
     case U:
         if (size > sizeof (unsigned))
             print("byte %d %U\n", size, v.u);
         else
             print("byte %d %u\n", size, v.u);
         return;
     case P: print("byte %d %U\n", size, (unsigned long)v.p); return;
     case F:
         if (size == 4) {
             floatint_t fi;
             fi.f = v.d;
             print("byte 4 %u\n", fi.ui);
         } else {
             unsigned *p = (unsigned *)&v.d;
             print("byte 4 %u\n", p[swap]);
             print("byte 4 %u\n", p[1 - swap]);
         }
         return;
     }
     assert(0);
 }
References assert, floatint_t::f, F, I, P, print(), suffix(), swap, U, and floatint_t::ui.
defstring()
static void I() defstring (int len, char * str) static
Definition at line 56 of file bytecode.c.
{
     char *s;
     for (s = str; s < str + len; s++)
         print("byte 1 %d\n", (*s)&0377);
 }
References print().
defsymbol()
static void I() defsymbol (Symbol p) static
Definition at line 63 of file bytecode.c.
{
     if (p->scope == CONSTANTS)
         switch (optype(ttob(p->type))) {
         case I: p->x.name = stringf("%D", p->u.c.v.i); break;
         case U: p->x.name = stringf("%U", p->u.c.v.u); break;
         case P: p->x.name = stringf("%U", p->u.c.v.p); break;
         case F:
             {   // JDC: added this to get inline floats
                 floatint_t temp;
                 temp.f = p->u.c.v.d;
                 p->x.name = stringf("%U", temp.ui );
             }
             break;// JDC: added this
         default: assert(0);
         }
     else if (p->scope >= LOCAL && p->sclass == STATIC)
         p->x.name = stringf("$%d", genlabel(1));
     else if (p->scope == LABELS || p->generated)
         p->x.name = stringf("$%s", p->name);
     else
         p->x.name = p->name;
 }
References assert, CONSTANTS, floatint_t::f, F, genlabel(), I, LABELS, LOCAL, optype, P, STATIC, stringf(), ttob(), U, and floatint_t::ui.
dumptree()
static void dumptree (Node p) static
Definition at line 87 of file bytecode.c.
{
     switch (specific(p->op)) {
     case ASGN+B:
         assert(p->kids[0]);
         assert(p->kids[1]);
         assert(p->syms[0]);
         dumptree(p->kids[0]);
         dumptree(p->kids[1]);
         print("%s %d\n", opname(p->op), p->syms[0]->u.c.v.u);
         return;
     case RET+V:
         assert(!p->kids[0]);
         assert(!p->kids[1]);
         print("%s\n", opname(p->op));
         return;
     }
     switch (generic(p->op)) {
     case CNST: case ADDRG: case ADDRF: case ADDRL: case LABEL:
         assert(!p->kids[0]);
         assert(!p->kids[1]);
         assert(p->syms[0] && p->syms[0]->x.name);
         print("%s %s\n", opname(p->op), p->syms[0]->x.name);
         return;
     case CVF: case CVI: case CVP: case CVU:
         assert(p->kids[0]);
         assert(!p->kids[1]);
         assert(p->syms[0]);
         dumptree(p->kids[0]);
         print("%s %d\n", opname(p->op), p->syms[0]->u.c.v.i);
         return;
     case ARG: case BCOM: case NEG: case INDIR: case JUMP: case RET:
         assert(p->kids[0]);
         assert(!p->kids[1]);
         dumptree(p->kids[0]);
         print("%s\n", opname(p->op));
         return;
     case CALL:
         assert(p->kids[0]);
         assert(!p->kids[1]);
         assert(optype(p->op) != B);
         dumptree(p->kids[0]);
         print("%s\n", opname(p->op));
         if ( !p->count ) { printf("pop\n"); };  // JDC
         return;
     case ASGN: case BOR: case BAND: case BXOR: case RSH: case LSH:
     case ADD: case SUB: case DIV: case MUL: case MOD:
         assert(p->kids[0]);
         assert(p->kids[1]);
         dumptree(p->kids[0]);
         dumptree(p->kids[1]);
         print("%s\n", opname(p->op));
         return;
     case EQ: case NE: case GT: case GE: case LE: case LT:
         assert(p->kids[0]);
         assert(p->kids[1]);
         assert(p->syms[0]);
         assert(p->syms[0]->x.name);
         dumptree(p->kids[0]);
         dumptree(p->kids[1]);
         print("%s %s\n", opname(p->op), p->syms[0]->x.name);
         return;
     }
     assert(0);
 }
References ADD, ASGN, assert, B, CALL, DIV, EQ, GT, LSH, LT, MOD, opname(), optype, print(), printf(), RSH, specific, SUB, and V.
Referenced by emit().
emit()
static void I() emit (Node p) static
Definition at line 152 of file bytecode.c.
{
     for (; p; p = p->link)
         dumptree(p);
 }
References dumptree().
Referenced by VM_Compile().
export()
static void I() export (Symbol p) static
Definition at line 157 of file bytecode.c.
{
     print("export %s\n", p->x.name);
 }
References print().
filelength()
static int filelength (FILE * f) static
Definition at line 239 of file bytecode.c.
{
     int     pos;
     int     end;
     pos = ftell (f);
     fseek (f, 0, SEEK_END);
     end = ftell (f);
     fseek (f, pos, SEEK_SET);
     return end;
 }
References fseek(), ftell(), SEEK_END, and SEEK_SET.
Referenced by LoadSourceFile().
function()
static void I() function (Symbol f, Symbol caller[], Symbol callee[], int ncalls) static
Definition at line 161 of file bytecode.c.
{
     int i;
     (*IR->segment)(CODE);
     offset = 0;
     for (i = 0; caller[i] && callee[i]; i++) {
         offset = roundup(offset, caller[i]->type->align);
         caller[i]->x.name = callee[i]->x.name = stringf("%d", offset);
         caller[i]->x.offset = callee[i]->x.offset = offset;
         offset += caller[i]->type->size;
     }
     maxargoffset = maxoffset = argoffset = offset = 0;
     gencode(caller, callee);
     print("proc %s %d %d\n", f->x.name, maxoffset, maxargoffset);
     emitcode();
     print("endproc %s %d %d\n", f->x.name, maxoffset, maxargoffset);
 }
References Type::align, argoffset, CODE, emitcode(), gencode(), IR, maxargoffset, maxoffset, print(), roundup, and stringf().
Referenced by _GLIBCXX_VISIBILITY().
gen()
static Node I() gen (Node p) static
Definition at line 199 of file bytecode.c.
{
     Node q;
     assert(p);
     for (q = p; q; q = q->link)
         gen01(q);
     return p;
 }
References assert, and gen01().
gen01()
static void gen01 (Node p) static
Definition at line 191 of file bytecode.c.
{
     if (p) {
         gen01(p->kids[0]);
         gen01(p->kids[1]);
         gen02(p);
     }
 }
References gen02().
Referenced by gen().
gen02()
static void gen02 (Node p) static
Definition at line 180 of file bytecode.c.
{
     assert(p);
     if (generic(p->op) == ARG) {
         assert(p->syms[0]);
         argoffset += (p->syms[0]->u.c.v.i < 4 ? 4 : p->syms[0]->u.c.v.i);
     } else if (generic(p->op) == CALL) {
         maxargoffset = (argoffset > maxargoffset ? argoffset : maxargoffset);
         argoffset = 0;
     }
 }
References argoffset, assert, CALL, and maxargoffset.
Referenced by gen01().
global()
static void I() global (Symbol p) static
Definition at line 208 of file bytecode.c.
{
     print("align %d\n", p->type->align > 4 ? 4 : p->type->align);
     print("LABELV %s\n", p->x.name);
 }
References print().
import()
static void I() import (Symbol p) static
Definition at line 213 of file bytecode.c.
{
     print("import %s\n", p->x.name);
 }
References print().
LoadSourceFile()
static void LoadSourceFile (const char * filename) static
Definition at line 251 of file bytecode.c.
{
     FILE    *f;
     int     length;
     f = fopen( filename, "r" );
     if ( !f ) {
         print( ";couldn't open %s\n", filename );
         sourceFile = NULL;
         return;
     }
     length = filelength( f );
     sourceFile = malloc( length + 1 );
     if ( sourceFile ) {
         fread( sourceFile, length, 1, f );
         sourceFile[length] = 0;
     }
     fclose( f );
     sourceLine = 1;
     sourcePtr = sourceFile;
 }
References fclose(), filelength(), fopen(), fread(), malloc(), NULL, print(), sourceFile, sourceLine, and sourcePtr.
Referenced by stabline().
local()
static void I() local (Symbol p) static
Definition at line 217 of file bytecode.c.
{
     offset = roundup(offset, p->type->align);
     p->x.name = stringf("%d", offset);
     p->x.offset = offset;
     offset += p->type->size;
 }
References roundup, and stringf().
PrintToSourceLine()
static void PrintToSourceLine (int line) static
Definition at line 273 of file bytecode.c.
{
     int     c;
     if ( !sourceFile ) {
         return;
     }
     while ( sourceLine <= line ) {
         int     i;
         for ( i = 0 ; sourcePtr[i] && sourcePtr[i] != '\n' ; i++ ) {
         }
         c = sourcePtr[i];
         if ( c == '\n' ) {
             sourcePtr[i] = 0;
         }
         print( ";%d:%s\n", sourceLine, sourcePtr );
         if ( c == 0 ) {
             sourcePtr += i; // end of file
         } else {
             sourcePtr += i+1;
         }
         sourceLine++;
     }
 }
References line, print(), sourceFile, sourceLine, and sourcePtr.
Referenced by stabline().
progbeg()
static void I() progbeg (int argc, char * argv[]) static
Definition at line 224 of file bytecode.c.
 {}
progend()
static void I() progend (void) static
Definition at line 226 of file bytecode.c.
 {}
segment()
static void I() segment (int n) static
Definition at line 5 of file bytecode.c.
{
     static int cseg;
     if (cseg != n)
         switch (cseg = n) {
         case CODE: print("code\n"); return;
         case DATA: print("data\n"); return;
         case BSS:  print("bss\n");  return;
         case LIT:  print("lit\n");  return;
         default: assert(0);
         }
 }
References assert, BSS, CODE, DATA, LIT, and print().
space()
static void I() space (int n) static
Definition at line 228 of file bytecode.c.
{
     print("skip %d\n", n);
 }
References print().
Referenced by _GLIBCXX_VISIBILITY().
stabline()
static void I() stabline (Coordinate * cp) static
Definition at line 298 of file bytecode.c.
{
     static char *prevfile;
     static int prevline;
     if (cp->file && (prevfile == NULL || strcmp(prevfile, cp->file) != 0)) {
         print("file \"%s\"\n", prevfile = cp->file);
         prevline = 0;
         if ( sourceFile ) {
             free( sourceFile );
             sourceFile = NULL;
         }
         // load the new source file
         LoadSourceFile( cp->file );
     }
     if (cp->y != prevline) {
         print("line %d\n", prevline = cp->y);
         PrintToSourceLine( cp->y );
     }
 }
References cp, free(), LoadSourceFile(), NULL, print(), PrintToSourceLine(), sourceFile, and strcmp().
Variable Documentation
bytecodeIR
Interface bytecodeIR
Definition at line 323 of file bytecode.c.
sourceFile
char* sourceFile static
Definition at line 235 of file bytecode.c.
Referenced by LoadSourceFile(), PrintToSourceLine(), and stabline().
sourceLine
int sourceLine static
Definition at line 237 of file bytecode.c.
Referenced by LoadSourceFile(), and PrintToSourceLine().
sourcePtr
char* sourcePtr static
Definition at line 236 of file bytecode.c.
Referenced by LoadSourceFile(), and PrintToSourceLine().