ZEQ2-Lite: Source/Engine/tools/lcc/cpp/cpp.c File Reference
cpp.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stdarg.h>
#include "cpp.h"
Macros
#define OUTS 16384
Functions
void control (Tokenrow *trp)
void dofree (void *p)
void * domalloc (int size)
void error (enum errtype type, char *string,...)
int main (int argc, char **argv)
void process (Tokenrow *trp)
Variables
Source * cursource
char * curtime
int ifdepth
int ifsatisfied [NIF]
int incdepth
int nerrs
struct token nltoken = { NL, 0, 0, 0, 1, (uchar*)"\n" }
char outbuf [OUTS]
char * outp = outbuf
char rcsid [] = "cpp.c - faked rcsid"
int skipping
Macro Definition Documentation
OUTS
#define OUTS 16384
Definition at line 10 of file cpp.c.
Function Documentation
control()
void control (Tokenrow * trp)
Definition at line 90 of file cpp.c.
 {
     Nlist *np;
     Token *tp;
     tp = trp->tp;
     if (tp->type!=NAME) {
         if (tp->type==NUMBER)
             goto kline;
         if (tp->type != NL)
             error(ERROR, "Unidentifiable control line");
         return;         /* else empty line */
     }
     if ((np = lookup(tp, 0))==NULL || ((np->flag&ISKW)==0 && !skipping)) {
         error(WARNING, "Unknown preprocessor control %t", tp);
         return;
     }
     if (skipping) {
         switch (np->val) {
         case KENDIF:
             if (--ifdepth<skipping)
                 skipping = 0;
             --cursource->ifdepth;
             setempty(trp);
             return;
         case KIFDEF:
         case KIFNDEF:
         case KIF:
             if (++ifdepth >= NIF)
                 error(FATAL, "#if too deeply nested");
             ++cursource->ifdepth;
             return;
         case KELIF:
         case KELSE:
             if (ifdepth<=skipping)
                 break;
             return;
         default:
             return;
         }
     }
     switch (np->val) {
     case KDEFINE:
         dodefine(trp);
         break;
     case KUNDEF:
         tp += 1;
         if (tp->type!=NAME || trp->lp - trp->bp != 4) {
             error(ERROR, "Syntax error in #undef");
             break;
         }
         if ((np = lookup(tp, 0)) != NULL)
             np->flag &= ~ISDEFINED;
         break;
     case KPRAGMA:
         return;
     case KIFDEF:
     case KIFNDEF:
     case KIF:
         if (++ifdepth >= NIF)
             error(FATAL, "#if too deeply nested");
         ++cursource->ifdepth;
         ifsatisfied[ifdepth] = 0;
         if (eval(trp, np->val))
             ifsatisfied[ifdepth] = 1;
         else
             skipping = ifdepth;
         break;
     case KELIF:
         if (ifdepth==0) {
             error(ERROR, "#elif with no #if");
             return;
         }
         if (ifsatisfied[ifdepth]==2)
             error(ERROR, "#elif after #else");
         if (eval(trp, np->val)) {
             if (ifsatisfied[ifdepth])
                 skipping = ifdepth;
             else {
                 skipping = 0;
                 ifsatisfied[ifdepth] = 1;
             }
         } else
             skipping = ifdepth;
         break;
     case KELSE:
         if (ifdepth==0 || cursource->ifdepth==0) {
             error(ERROR, "#else with no #if");
             return;
         }
         if (ifsatisfied[ifdepth]==2)
             error(ERROR, "#else after #else");
         if (trp->lp - trp->bp != 3)
             error(ERROR, "Syntax error in #else");
         skipping = ifsatisfied[ifdepth]? ifdepth: 0;
         ifsatisfied[ifdepth] = 2;
         break;
     case KENDIF:
         if (ifdepth==0 || cursource->ifdepth==0) {
             error(ERROR, "#endif with no #if");
             return;
         }
         --ifdepth;
         --cursource->ifdepth;
         if (trp->lp - trp->bp != 3)
             error(WARNING, "Syntax error in #endif");
         break;
     case KWARNING:
         trp->tp = tp+1;
         error(WARNING, "#warning directive: %r", trp);
         break;
     case KERROR:
         trp->tp = tp+1;
         error(ERROR, "#error directive: %r", trp);
         break;
     case KLINE:
         trp->tp = tp+1;
         expandrow(trp, "<line>");
         tp = trp->bp+2;
     kline:
         if (tp+1>=trp->lp || tp->type!=NUMBER || tp+3<trp->lp
          || ((tp+3==trp->lp && ((tp+1)->type!=STRING))||*(tp+1)->t=='L')){
             error(ERROR, "Syntax error in #line");
             return;
         }
         cursource->line = atol((char*)tp->t)-1;
         if (cursource->line<0 || cursource->line>=32768)
             error(WARNING, "#line specifies number out of range");
         tp = tp+1;
         if (tp+1<trp->lp)
             cursource->filename=(char*)newstring(tp->t+1,tp->len-2,0);
         return;
     case KDEFINED:
         error(ERROR, "Bad syntax for control line");
         break;
     case KINCLUDE:
         doinclude(trp);
         trp->lp = trp->bp;
         return;
     case KEVAL:
         eval(trp, np->val);
         break;
     default:
         error(ERROR, "Preprocessor control `%t' not yet implemented", tp);
         break;
     }
     setempty(trp);
     return;
 }
References cursource, dodefine(), doinclude(), ERROR, error(), eval(), expandrow(), FATAL, ifdepth, ifsatisfied, ISDEFINED, ISKW, KDEFINE, KDEFINED, KELIF, KELSE, KENDIF, KERROR, KEVAL, KIF, KIFDEF, KIFNDEF, KINCLUDE, KLINE, KPRAGMA, KUNDEF, KWARNING, lookup(), NAME, newstring(), NIF, NL, np, NULL, NUMBER, setempty(), skipping, STRING, and WARNING.
Referenced by Controls_Update(), PM_Friction(), PM_NoclipMove(), and process().
dofree()
void dofree (void * p)
Definition at line 267 of file cpp.c.
 {
     free(p);
 }
Referenced by doconcat(), dodefine(), expand(), substargs(), and unsetsource().
domalloc()
void* domalloc (int size)
Definition at line 257 of file cpp.c.
 {
     void *p = malloc(size);
     if (p==NULL)
         error(FATAL, "Out of memory from malloc");
     return p;
 }
References error(), FATAL, and NULL.
Referenced by iniths(), maketokenrow(), newhideset(), newstring(), setobjname(), and setsource().
error()
void error (enum errtype type, char * string, ...)
Definition at line 273 of file cpp.c.
 {
     va_list ap;
     char *cp, *ep;
     Token *tp;
     Tokenrow *trp;
     Source *s;
     int i;
     fprintf(stderr, "cpp: ");
     for (s=cursource; s; s=s->next)
         if (*s->filename)
             fprintf(stderr, "%s:%d ", s->filename, s->line);
     va_start(ap, string);
     for (ep=string; *ep; ep++) {
         if (*ep=='%') {
             switch (*++ep) {
             case 's':
                 cp = va_arg(ap, char *);
                 fprintf(stderr, "%s", cp);
                 break;
             case 'd':
                 i = va_arg(ap, int);
                 fprintf(stderr, "%d", i);
                 break;
             case 't':
                 tp = va_arg(ap, Token *);
                 fprintf(stderr, "%.*s", tp->len, tp->t);
                 break;
             case 'r':
                 trp = va_arg(ap, Tokenrow *);
                 for (tp=trp->tp; tp<trp->lp&&tp->type!=NL; tp++) {
                     if (tp>trp->tp && tp->wslen)
                         fputc(' ', stderr);
                     fprintf(stderr, "%.*s", tp->len, tp->t);
                 }
                 break;
             default:
                 fputc(*ep, stderr);
                 break;
             }
         } else
             fputc(*ep, stderr);
     }
     va_end(ap);
     fputc('\n', stderr);
     if (type==FATAL)
         exit(1);
     if (type!=WARNING)
         nerrs = 1;
     fflush(stderr);
 }
References cp, cursource, FATAL, nerrs, NL, and WARNING.
Referenced by _spx_lpc(), addrof(), addtree(), allocate(), appendDirToIncludeList(), array(), asgntree(), atop(), backslash(), builtin(), call(), caselabel(), checklab(), checkref(), Com_Error(), control(), dclglobal(), dcllocal(), dclparam(), dclr1(), decl(), deref(), doadefine(), doconcat(), dodefine(), doglobal(), doinclude(), domalloc(), enumdcl(), Error(), eval(), evalop(), exitparams(), expand(), expandrow(), fcon(), field(), fields(), fillbuf(), freturn(), func(), funcdefn(), gatherargs(), genconst(), gettok(), gettokens(), growtokenrow(), initializer(), initvalue(), intexpr(), lvalue(), newfield(), newhideset(), newstruct(), oldparam(), parameters(), postfix(), ppnumber(), primary(), process(), program(), qual(), retcode(), scon(), setup(), specifier(), statement(), stmtlabel(), stringify(), structdcl(), substargs(), subtree(), swstmt(), Sys_Error(), Sys_ErrorDialog(), tokval(), typeerror(), and unary().
main()
int main (int argc, char ** argv)
Definition at line 24 of file cpp.c.
 {
     Tokenrow tr;
     time_t t;
     char ebuf[BUFSIZ];
     setbuf(stderr, ebuf);
     t = time(NULL);
     curtime = ctime(&t);
     maketokenrow(3, &tr);
     expandlex();
     setup(argc, argv);
     fixlex();
     iniths();
     genline();
     process(&tr);
     flushout();
     fflush(stderr);
     exit(nerrs > 0);
     return 0;
 }
References curtime, expandlex(), fixlex(), flushout(), genline(), iniths(), maketokenrow(), nerrs, NULL, process(), setup(), and tr.
process()
void process (Tokenrow * trp)
Definition at line 47 of file cpp.c.
 {
     int anymacros = 0;
     for (;;) {
         if (trp->tp >= trp->lp) {
             trp->tp = trp->lp = trp->bp;
             outp = outbuf;
             anymacros |= gettokens(trp, 1);
             trp->tp = trp->bp;
         }
         if (trp->tp->type == END) {
             if (--incdepth>=0) {
                 if (cursource->ifdepth)
                     error(ERROR,
                      "Unterminated conditional in #include");
                 unsetsource();
                 cursource->line += cursource->lineinc;
                 trp->tp = trp->lp;
                 genline();
                 continue;
             }
             if (ifdepth)
                 error(ERROR, "Unterminated #if/#ifdef/#ifndef");
             break;
         }
         if (trp->tp->type==SHARP) {
             trp->tp += 1;
             control(trp);
         } else if (!skipping && anymacros)
             expandrow(trp, NULL);
         if (skipping)
             setempty(trp);
         puttokens(trp);
         anymacros = 0;
         cursource->line += cursource->lineinc;
         if (cursource->lineinc>1) {
             genline();
         }
     }
 }
References control(), cursource, END, ERROR, error(), expandrow(), genline(), gettokens(), ifdepth, incdepth, NULL, outbuf, outp, puttokens(), setempty(), SHARP, skipping, and unsetsource().
Referenced by main(), and prof_init().
Variable Documentation
cursource
Source* cursource
Definition at line 13 of file cpp.c.
Referenced by builtin(), control(), error(), genline(), gettokens(), process(), puttokens(), setsource(), and unsetsource().
curtime
char* curtime
Definition at line 16 of file cpp.c.
Referenced by main().
ifdepth
int ifdepth
Definition at line 18 of file cpp.c.
Referenced by control(), and process().
ifsatisfied
int ifsatisfied[NIF]
Definition at line 19 of file cpp.c.
Referenced by control().
incdepth
int incdepth
Definition at line 17 of file cpp.c.
Referenced by doinclude(), and process().
nerrs
int nerrs
Definition at line 14 of file cpp.c.
Referenced by error(), and main().
nltoken
struct token nltoken = { NL, 0, 0, 0, 1, (uchar*)"\n" }
Definition at line 15 of file cpp.c.
Referenced by setempty().
outbuf
char outbuf[OUTS]
Definition at line 11 of file cpp.c.
Referenced by process().
outp
char* outp = outbuf
Definition at line 12 of file cpp.c.
Referenced by builtin(), genline(), process(), S_AdpcmDecode(), and S_AdpcmEncode().
rcsid
char rcsid[] = "cpp.c - faked rcsid"
Definition at line 8 of file cpp.c.
skipping
int skipping
Definition at line 20 of file cpp.c.
Referenced by control(), and process().