ZEQ2-Lite: __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator > Class Template Reference
__gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator > Class Template Reference
#include <ov_tree_map_.hpp>
Public Types
typedef Allocator allocator_type
typedef Cmp_Fn cmp_fn
typedef const_point_iterator const_iterator
typedef traits_base::const_key_pointer const_key_pointer
typedef traits_base::const_key_reference const_key_reference
typedef traits_base::const_mapped_pointer const_mapped_pointer
typedef traits_base::const_mapped_reference const_mapped_reference
typedef Node_And_It_Traits::const_node_iterator const_node_iterator
typedef const_pointer const_point_iterator
typedef traits_base::const_pointer const_pointer
typedef traits_base::const_reference const_reference
typedef Allocator::difference_type difference_type
typedef point_iterator iterator
typedef traits_base::key_pointer key_pointer
typedef traits_base::key_reference key_reference
typedef traits_base::key_type key_type
typedef traits_base::mapped_pointer mapped_pointer
typedef traits_base::mapped_reference mapped_reference
typedef traits_base::mapped_type mapped_type
typedef Node_And_It_Traits::node_iterator node_iterator
typedef Node_And_It_Traits::node_update node_update
typedef const_point_iterator point_iterator
typedef traits_base::pointer pointer
typedef traits_base::reference reference
typedef Allocator::size_type size_type
typedef traits_base::value_type value_type
Public Member Functions
PB_DS_OV_TREE_CLASS_NAME ()
PB_DS_OV_TREE_CLASS_NAME (const Cmp_Fn &)
PB_DS_OV_TREE_CLASS_NAME (const Cmp_Fn &, const node_update &)
PB_DS_OV_TREE_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
~PB_DS_OV_TREE_CLASS_NAME ()
iterator begin ()
const_iterator begin () const
void clear ()
template<typename It >
void copy_from_range (It, It)
bool empty () const
iterator end ()
const_iterator end () const
bool erase (const_key_reference)
iterator erase (iterator it)
template<typename Pred >
size_type erase_if (Pred)
point_iterator find (const_key_reference r_key)
const_point_iterator find (const_key_reference r_key) const
Cmp_Fn & get_cmp_fn ()
const Cmp_Fn & get_cmp_fn () const
std::pair< point_iterator, bool > insert (const_reference r_value)
void join (PB_DS_CLASS_C_DEC &)
point_iterator lower_bound (const_key_reference r_key)
const_point_iterator lower_bound (const_key_reference r_key) const
size_type max_size () const
node_iterator node_begin ()
const_node_iterator node_begin () const
node_iterator node_end ()
const_node_iterator node_end () const
mapped_reference operator[] (const_key_reference r_key)
size_type size () const
void split (const_key_reference, PB_DS_CLASS_C_DEC &)
void swap (PB_DS_CLASS_C_DEC &)
point_iterator upper_bound (const_key_reference r_key)
const_point_iterator upper_bound (const_key_reference r_key) const
Private Types
typedef Cmp_Fn cmp_fn_base
typedef traits_base::const_pointer const_mapped_pointer_
typedef metadata_allocator::const_reference const_metadata_reference
typedef traits_base::pointer mapped_pointer_
typedef Allocator::template rebind< metadata_type >::other metadata_allocator
typedef metadata_allocator::pointer metadata_pointer
typedef metadata_allocator::reference metadata_reference
typedef Node_And_It_Traits::metadata_type metadata_type
typedef remove_const< typename traits_base::value_type >::type non_const_value_type
typedef Node_And_It_Traits::null_node_update_pointer null_node_update_pointer
typedef PB_DS_TYPES_TRAITS_C_DEC traits_base
typedef Allocator::template rebind< non_const_value_type >::other value_allocator
typedef value_allocator::pointer value_vector
Private Member Functions
template<typename It >
void copy_from_ordered_range (It, It)
template<typename It >
void copy_from_ordered_range (It, It, It, It)
template<typename It >
It erase_imp (It it)
iterator insert_new_val (iterator it, const_reference r_value)
node_iterator PB_DS_node_begin_imp ()
const_node_iterator PB_DS_node_begin_imp () const
node_iterator PB_DS_node_end_imp ()
const_node_iterator PB_DS_node_end_imp () const
template<typename Node_Update_ >
void reallocate_metadata (Node_Update_ *, size_type)
void reallocate_metadata (null_node_update_pointer, size_type)
template<typename Node_Update >
void update (node_iterator, Node_Update *)
void update (node_iterator, null_node_update_pointer)
void value_swap (PB_DS_CLASS_C_DEC &)
Static Private Member Functions
template<typename Ptr >
static Ptr mid_pointer (Ptr p_begin, Ptr p_end)
Private Attributes
metadata_pointer m_a_metadata
value_vector m_a_values
iterator m_end_it
size_type m_size
Static Private Attributes
static metadata_allocator s_metadata_alloc
static value_allocator s_value_alloc
Detailed Description
template<typename Key, typename Mapped, class Cmp_Fn, class Node_And_It_Traits, class Allocator>
class __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >
Definition at line 113 of file ov_tree_map_.hpp.
Member Typedef Documentation
allocator_type
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocator_type
Definition at line 155 of file ov_tree_map_.hpp.
cmp_fn
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Cmp_Fn __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::cmp_fn
Definition at line 159 of file ov_tree_map_.hpp.
cmp_fn_base
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Cmp_Fn __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::cmp_fn_base private
Definition at line 133 of file ov_tree_map_.hpp.
const_iterator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_iterator
Definition at line 187 of file ov_tree_map_.hpp.
const_key_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_pointer
Definition at line 165 of file ov_tree_map_.hpp.
const_key_reference
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_reference
Definition at line 167 of file ov_tree_map_.hpp.
const_mapped_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_pointer
Definition at line 170 of file ov_tree_map_.hpp.
const_mapped_pointer_
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_pointer_ private
Definition at line 140 of file ov_tree_map_.hpp.
const_mapped_reference
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_reference
Definition at line 172 of file ov_tree_map_.hpp.
const_metadata_reference
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef metadata_allocator::const_reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_metadata_reference private
Definition at line 146 of file ov_tree_map_.hpp.
const_node_iterator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::const_node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_node_iterator
Definition at line 195 of file ov_tree_map_.hpp.
const_point_iterator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_point_iterator
Definition at line 179 of file ov_tree_map_.hpp.
const_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer
Definition at line 175 of file ov_tree_map_.hpp.
const_reference
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference
Definition at line 177 of file ov_tree_map_.hpp.
difference_type
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::difference_type
Definition at line 157 of file ov_tree_map_.hpp.
iterator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::iterator
Definition at line 189 of file ov_tree_map_.hpp.
key_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_pointer
Definition at line 164 of file ov_tree_map_.hpp.
key_reference
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_reference
Definition at line 166 of file ov_tree_map_.hpp.
key_type
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_type
Definition at line 163 of file ov_tree_map_.hpp.
mapped_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_pointer
Definition at line 169 of file ov_tree_map_.hpp.
mapped_pointer_
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_pointer_ private
Definition at line 139 of file ov_tree_map_.hpp.
mapped_reference
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_reference
Definition at line 171 of file ov_tree_map_.hpp.
mapped_type
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_type
Definition at line 168 of file ov_tree_map_.hpp.
metadata_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<metadata_type>::other __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::metadata_allocator private
Definition at line 144 of file ov_tree_map_.hpp.
metadata_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef metadata_allocator::pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::metadata_pointer private
Definition at line 145 of file ov_tree_map_.hpp.
metadata_reference
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef metadata_allocator::reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::metadata_reference private
Definition at line 147 of file ov_tree_map_.hpp.
metadata_type
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::metadata_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::metadata_type private
Definition at line 142 of file ov_tree_map_.hpp.
node_iterator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_iterator
Definition at line 197 of file ov_tree_map_.hpp.
node_update
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::node_update __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_update
Definition at line 161 of file ov_tree_map_.hpp.
non_const_value_type
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef remove_const<typename traits_base::value_type>::type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::non_const_value_type private
Definition at line 127 of file ov_tree_map_.hpp.
null_node_update_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::null_node_update_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::null_node_update_pointer private
Definition at line 151 of file ov_tree_map_.hpp.
point_iterator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::point_iterator
Definition at line 184 of file ov_tree_map_.hpp.
pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer
Definition at line 174 of file ov_tree_map_.hpp.
reference
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference
Definition at line 176 of file ov_tree_map_.hpp.
size_type
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size_type
Definition at line 156 of file ov_tree_map_.hpp.
traits_base
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::traits_base private
Definition at line 125 of file ov_tree_map_.hpp.
value_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<non_const_value_type>::other __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_allocator private
Definition at line 129 of file ov_tree_map_.hpp.
value_type
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::value_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type
Definition at line 173 of file ov_tree_map_.hpp.
value_vector
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef value_allocator::pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_vector private
Definition at line 130 of file ov_tree_map_.hpp.
Constructor & Destructor Documentation
PB_DS_OV_TREE_CLASS_NAME() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_OV_TREE_CLASS_NAME ()
PB_DS_OV_TREE_CLASS_NAME() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_OV_TREE_CLASS_NAME (const Cmp_Fn &)
PB_DS_OV_TREE_CLASS_NAME() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_OV_TREE_CLASS_NAME (const Cmp_Fn & , const node_update &)
PB_DS_OV_TREE_CLASS_NAME() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_OV_TREE_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
~PB_DS_OV_TREE_CLASS_NAME()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::~PB_DS_OV_TREE_CLASS_NAME ()
Member Function Documentation
begin() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () inline
Definition at line 350 of file ov_tree_map_.hpp.
       { return m_a_values; }
References __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_a_values.
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val().
begin() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () const inline
Definition at line 354 of file ov_tree_map_.hpp.
       { return m_a_values; }
References __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_a_values.
clear()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::clear ()
copy_from_ordered_range() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_ordered_range (It , It) private
copy_from_ordered_range() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_ordered_range (It , It , It , It) private
copy_from_range()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_range (It , It)
empty()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::empty () const inline
end() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () inline
Definition at line 358 of file ov_tree_map_.hpp.
       { return m_end_it; }
References __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_end_it.
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[](), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound().
end() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () const inline
Definition at line 362 of file ov_tree_map_.hpp.
       { return m_end_it; }
References __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_end_it.
erase() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_key_reference)
erase() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (iterator it) inline
Definition at line 337 of file ov_tree_map_.hpp.
       { return erase_imp<iterator>(it); }
erase_if()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Pred > size_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_if (Pred) inline
erase_imp()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > It __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_imp (It it) private
find() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference r_key) inline
Definition at line 311 of file ov_tree_map_.hpp.
       {
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     iterator pot_it = lower_bound(r_key);
     if (pot_it != end() && !Cmp_Fn::operator()(r_key, PB_DS_V2F(*pot_it)))
       {
         _GLIBCXX_DEBUG_ONLY(debug_base::check_key_exists(r_key));
         return pot_it;
       }
     _GLIBCXX_DEBUG_ONLY(debug_base::check_key_does_not_exist(r_key));
     return end();
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound().
find() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference r_key) const inline
Definition at line 326 of file ov_tree_map_.hpp.
       { return (const_cast<PB_DS_CLASS_C_DEC& >(*this).find(r_key)); }
References PB_DS_CLASS_C_DEC.
get_cmp_fn() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Cmp_Fn& __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_cmp_fn ()
get_cmp_fn() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Cmp_Fn& __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_cmp_fn () const
insert()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert (const_reference r_value) inline
Definition at line 255 of file ov_tree_map_.hpp.
       {
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     const_key_reference r_key = PB_DS_V2F(r_value);
     point_iterator it = lower_bound(r_key);
     if (it != end()&&  !Cmp_Fn::operator()(r_key, PB_DS_V2F(*it)))
       {
         _GLIBCXX_DEBUG_ONLY(assert_valid();)
         _GLIBCXX_DEBUG_ONLY(debug_base::check_key_exists(r_key));
         return std::make_pair(it, false);
       }
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     return std::make_pair(insert_new_val(it, r_value), true);
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound().
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[]().
insert_new_val()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val (iterator it, const_reference r_value) inline private
Definition at line 413 of file ov_tree_map_.hpp.
       {
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
 #ifdef PB_DS_REGRESSION
       typename Allocator::group_adjustor adjust(m_size);
 #endif
     _GLIBCXX_DEBUG_ONLY(debug_base::check_key_does_not_exist(PB_DS_V2F(r_value)));
     value_vector a_values = s_value_alloc.allocate(m_size + 1);
     iterator source_it = begin();
     iterator source_end_it = end();
     iterator target_it = a_values;
     iterator ret_it;
     cond_dtor<size_type> cd(a_values, target_it, m_size + 1);
     while (source_it != it)
       {
         new (const_cast<void* >(static_cast<const void* >(target_it)))
           value_type(*source_it++);
         ++target_it;
       }
     new (const_cast<void* >(static_cast<const void* >(ret_it = target_it)))
       value_type(r_value);
     ++target_it;
     while (source_it != source_end_it)
       {
         new (const_cast<void* >(static_cast<const void* >(target_it)))
           value_type(*source_it++);
         ++target_it;
       }
     reallocate_metadata((node_update* )this, m_size + 1);
     cd.set_no_action();
     if (m_size != 0)
       {
         cond_dtor<size_type> cd1(m_a_values, m_end_it, m_size);
       }
     ++m_size;
     m_a_values = a_values;
     m_end_it = m_a_values + m_size;
     _GLIBCXX_DEBUG_ONLY(debug_base::insert_new(PB_DS_V2F(r_value)));
     update(node_begin(), (node_update* )this);
     _GLIBCXX_DEBUG_ONLY(PB_DS_CLASS_C_DEC::assert_valid();)
     return ret_it;
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_a_values, __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_end_it, __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_size, __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_begin(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reallocate_metadata(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_value_alloc, cond_dtor< Size_Type >::set_no_action(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update().
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[]().
join()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::join (PB_DS_CLASS_C_DEC &)
lower_bound() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound (const_key_reference r_key) inline
Definition at line 273 of file ov_tree_map_.hpp.
       {
     pointer it = m_a_values;
     pointer e_it = m_a_values + m_size;
     while (it != e_it)
       {
         pointer mid_it = it + ((e_it - it) >> 1);
         if (cmp_fn_base::operator()(PB_DS_V2F(*mid_it), r_key))
           it = ++mid_it;
         else
           e_it = mid_it;
       }
     return it;
       }
References __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_a_values, and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_size.
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[](), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound().
lower_bound() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound (const_key_reference r_key) const inline
Definition at line 289 of file ov_tree_map_.hpp.
       { return const_cast<PB_DS_CLASS_C_DEC& >(*this).lower_bound(r_key); }
References PB_DS_CLASS_C_DEC.
max_size()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::max_size () const inline
mid_pointer()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Ptr > static Ptr __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mid_pointer (Ptr p_begin, Ptr p_end) inline static private
Definition at line 406 of file ov_tree_map_.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(p_end >= p_begin);
     return (p_begin + (p_end - p_begin) / 2);
       }
References _GLIBCXX_DEBUG_ASSERT.
node_begin() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_begin () inline
node_begin() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_begin () const inline
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val().
node_end() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_end () inline
node_end() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_end () const inline
operator[]()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > mapped_reference __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[] (const_key_reference r_key) inline
Definition at line 234 of file ov_tree_map_.hpp.
       {
 #ifdef PB_DS_DATA_TRUE_INDICATOR
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     point_iterator it = lower_bound(r_key);
     if (it != end() && !Cmp_Fn::operator()(r_key, PB_DS_V2F(*it)))
       {
         _GLIBCXX_DEBUG_ONLY(debug_base::check_key_exists(r_key));
         _GLIBCXX_DEBUG_ONLY(assert_valid();)
          return it->second;
       }
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     return (insert_new_val(it, std::make_pair(r_key, mapped_type()))->second);
 #else
     insert(r_key);
     return traits_base::s_null_mapped;
 #endif
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound().
PB_DS_node_begin_imp() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_node_begin_imp () inline private
PB_DS_node_begin_imp() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_node_begin_imp () const inline private
PB_DS_node_end_imp() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_node_end_imp () inline private
PB_DS_node_end_imp() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_node_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_node_end_imp () const inline private
reallocate_metadata() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Node_Update_ > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reallocate_metadata (Node_Update_ * , size_type) private
reallocate_metadata() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reallocate_metadata (null_node_update_pointer , size_type) private
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val().
size()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size () const inline
split()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split (const_key_reference , PB_DS_CLASS_C_DEC &)
swap()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::swap (PB_DS_CLASS_C_DEC &)
update() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Node_Update > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update (node_iterator , Node_Update *) private
update() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update (node_iterator , null_node_update_pointer) inline private
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val().
upper_bound() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound (const_key_reference r_key) inline
Definition at line 293 of file ov_tree_map_.hpp.
       {
     iterator pot_it = lower_bound(r_key);
     if (pot_it != end()&&  !Cmp_Fn::operator()(r_key, PB_DS_V2F(*pot_it)))
       {
         _GLIBCXX_DEBUG_ONLY(debug_base::check_key_exists(r_key));
         return ++pot_it;
       }
     _GLIBCXX_DEBUG_ONLY(debug_base::check_key_does_not_exist(r_key));
     return pot_it;
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound().
upper_bound() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound (const_key_reference r_key) const inline
Definition at line 307 of file ov_tree_map_.hpp.
       { return const_cast<PB_DS_CLASS_C_DEC&>(*this).upper_bound(r_key); }
References PB_DS_CLASS_C_DEC.
value_swap()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_swap (PB_DS_CLASS_C_DEC &) private
Field Documentation
m_a_metadata
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > metadata_pointer __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_a_metadata private
Definition at line 493 of file ov_tree_map_.hpp.
m_a_values
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > value_vector __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_a_values private
Definition at line 492 of file ov_tree_map_.hpp.
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin(), __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound().
m_end_it
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_end_it private
Definition at line 494 of file ov_tree_map_.hpp.
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val().
m_size
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_size private
Definition at line 495 of file ov_tree_map_.hpp.
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val(), and __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound().
s_metadata_alloc
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > metadata_allocator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_metadata_alloc static private
Definition at line 490 of file ov_tree_map_.hpp.
s_value_alloc
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > value_allocator __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_value_alloc static private
Definition at line 489 of file ov_tree_map_.hpp.
Referenced by __gnu_pbds::detail::PB_DS_OV_TREE_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_val().
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/ov_tree_map_/ov_tree_map_.hpp