ZEQ2-Lite: Source/Game/Game/bg_public.h File Reference
bg_public.h File Reference
Data Structures
struct animation_s
struct pmove_t
struct radar_t
Macros
#define advancedFlight 0x00000002
#define advancedMelee 0x00000001
#define ANIM_TOGGLEBIT 32768
#define ARENAS_PER_TIER 4
#define ARMOR_PROTECTION 0.66
#define atopGround 0x02000000
#define canAlter 0x00000004
#define canBallFlip 0x00020000
#define canBlock 0x00000008
#define canBoost 0x00001000
#define canBreakLimit 0x00080000
#define canClench 0x00000200
#define canDischarge 0x00000800
#define canExpulse 0x00000400
#define canFly 0x00004000
#define canGrab 0x00000080
#define canHandspring 0x00000040
#define canJump 0x00008000
#define canLockon 0x00000020
#define canMelee 0x00000010
#define canOverheal 0x00040000
#define canSlam 0x00000100
#define canSoar 0x00200000
#define canSwim 0x00002000
#define canTransform 0x00100000
#define canZanzoken 0x00010000
#define causedDamage 0x00000400
#define CROUCH_VIEWHEIGHT 12
#define CS_CLIENTSREADY 29
#define CS_FLAGSTATUS 23
#define CS_GAME_VERSION 20
#define CS_INTERMISSION 22
#define CS_ITEMS 27
#define CS_LEVEL_START_TIME 21
#define CS_LOCATIONS (CS_PLAYERS+MAX_CLIENTS)
#define CS_MAX (CS_PARTICLES+MAX_LOCATIONS)
#define CS_MESSAGE 3
#define CS_MODELS 32
#define CS_MOTD 4
#define CS_MUSIC 2
#define CS_PARTICLES (CS_LOCATIONS+MAX_LOCATIONS)
#define CS_PLAYERS (CS_SOUNDS+MAX_SOUNDS)
#define CS_SCORES1 6
#define CS_SCORES2 7
#define CS_SHADERSTATE 24
#define CS_SOUNDS (CS_MODELS+MAX_MODELS)
#define CS_TEAMVOTE_NO 18
#define CS_TEAMVOTE_STRING 14
#define CS_TEAMVOTE_TIME 12
#define CS_TEAMVOTE_YES 16
#define CS_VOTE_NO 11
#define CS_VOTE_STRING 9
#define CS_VOTE_TIME 8
#define CS_VOTE_YES 10
#define CS_WARMUP 5
#define DEAD_VIEWHEIGHT -16
#define DEFAULT_GRAVITY 3000
#define DEFAULT_SHOTGUN_COUNT 11
#define DEFAULT_SHOTGUN_SPREAD 700
#define DEFAULT_VIEWHEIGHT 26
#define DF_FIXED_FOV 16
#define DF_NO_FALLING 8
#define DF_NO_FOOTSTEPS 32
#define EARTHQUAKE_SYSTEM 1
#define EF_AURA 0x00000010
#define EF_BOUNCE 0x00000010
#define EF_BOUNCE_HALF 0x00000020
#define EF_CONNECTION 0x00002000
#define EF_DEAD 0x00000001
#define EF_FIRING 0x00000100
#define EF_GUIDED 0x00004000
#define EF_MOVER_STOP 0x00000400
#define EF_NODRAW 0x00000080
#define EF_PLAYER_EVENT 0x00000010
#define EF_TALK 0x00001000
#define EF_TEAMVOTED 0x00080000
#define EF_TELEPORT_BIT 0x00000004
#define EF_VOTED 0x00004000
#define EV_EVENT_BIT1 0x00000100
#define EV_EVENT_BIT2 0x00000200
#define EV_EVENT_BITS (EV_EVENT_BIT1|EV_EVENT_BIT2)
#define EVENT_VALID_MSEC 300
#define GAME_VERSION "ZEQ2"
#define GIB_HEALTH -40
#define hasFlipOffset 0x00000001
#define isBlinking 0x01000000
#define isBreakingLimit 0x00020000
#define isBurning 0x00000040
#define isCharging 0x00100000
#define isCrashed 0x00040000
#define isDashing 0x00000100
#define isDead 0x00010000
#define isGuiding 0x00080000
#define isHovering 0x00000080
#define isPreparing 0x00400000
#define isRiding 0x00000020
#define isStruggling 0x00004000
#define isTargetable 0x00000200
#define isTargeted 0x00200000
#define isTransforming 0x00002000
#define isUnconcious 0x00008000
#define isUnsafe 0x00800000
#define ITEM_RADIUS 15
#define keyTierDown 0x00001000
#define keyTierUp 0x00000800
#define LIGHTNING_RANGE 768
#define LOCATION_BACK 0x00000800
#define LOCATION_FRONT 0x00000400
#define LOCATION_LEFT 0x00000100
#define LOCATION_NONE 0x00000000
#define LOCATION_RIGHT 0x00000200
#define locked360 0x00000008
#define lockedPitch 0x00000001
#define lockedRoll 0x00000004
#define lockedSpin 0x00000010
#define lockedYaw 0x00000002
#define MASK_ALL (-1)
#define MASK_DEADSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP)
#define MASK_OPAQUE (CONTENTS_SOLID|CONTENTS_SLIME|CONTENTS_LAVA)
#define MASK_PLAYERSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_BODY)
#define MASK_SHOT (CONTENTS_SOLID|CONTENTS_BODY|CONTENTS_CORPSE)
#define MASK_SOLID (CONTENTS_SOLID)
#define MASK_WATER (CONTENTS_WATER|CONTENTS_LAVA|CONTENTS_SLIME)
#define MAX_ARENAS 1024
#define MAX_ARENAS_TEXT 8192
#define MAX_ITEMS 256
#define MAXTOUCH 32
#define MINS_Z -24
#define nearGround 0x04000000
#define PMF_ATTACK1_HELD 1
#define PMF_ATTACK2_HELD 2
#define PMF_BACKWARDS_JUMP 8
#define PMF_BACKWARDS_RUN 16
#define PMF_BLOCK_HELD 32768
#define PMF_BOOST_HELD 1024
#define PMF_CAN_MOVE 512
#define PMF_FOLLOW 4096
#define PMF_FORWARDS_JUMP 32
#define PMF_GRAPPLE_PULL 2048
#define PMF_LOCK_HELD 16384
#define PMF_SCOREBOARD 8192
#define PMF_TIME_KNOCKBACK 64
#define PMF_TIME_WATERJUMP 256
#define PMF_ZANZOKEN 2048
#define pointGravity 0x00400000
#define RADAR_BURST 2
#define RADAR_WARN 1
#define RANK_TIED_FLAG 0x4000
#define SCORE_NOT_PRESENT -9999
#define TEAM_LOCATION_UPDATE_TIME 1000
#define TEAM_MAXOVERLAY 32
#define underWater 0x08000000
#define usingAlter 0x00000008
#define usingBallFlip 0x00000400
#define usingBlock 0x00000004
#define usingBoost 0x00000002
#define usingFlight 0x00000080
#define usingJump 0x00000010
#define usingMelee 0x00000200
#define usingQuickZanzoken 0x10000000
#define usingSoar 0x00000100
#define usingWeapon 0x00000040
#define usingZanzoken 0x00000020
#define VOTE_TIME 30000
Enumerations
enum animNumber_t {
ANIM_DEATH_GROUND, ANIM_DEATH_AIR, ANIM_DEATH_AIR_LAND, ANIM_STUN,
ANIM_FLOOR_RECOVER, ANIM_IDLE, ANIM_IDLE_LOCKED, ANIM_TURN,
ANIM_WALK, ANIM_RUN, ANIM_SWIM_IDLE, ANIM_SWIM,
ANIM_JUMP_UP, ANIM_LAND_UP, ANIM_JUMP_FORWARD, ANIM_LAND_FORWARD,
ANIM_JUMP_BACK, ANIM_LAND_BACK, ANIM_DASH_RIGHT, ANIM_DASH_LEFT,
ANIM_DASH_FORWARD, ANIM_DASH_BACKWARD, ANIM_FLY_IDLE, ANIM_FLY_START,
ANIM_FLY_FORWARD, ANIM_FLY_BACKWARD, ANIM_FLY_UP, ANIM_FLY_DOWN,
ANIM_KI_CHARGE, ANIM_PL_UP, ANIM_PL_DOWN, ANIM_TRANS_UP,
ANIM_TRANS_BACK, ANIM_STUNNED, ANIM_PUSH, ANIM_DEFLECT,
ANIM_BLOCK, ANIM_SPEED_MELEE_ATTACK, ANIM_SPEED_MELEE_DODGE, ANIM_SPEED_MELEE_BLOCK,
ANIM_SPEED_MELEE_HIT, ANIM_BREAKER_MELEE_ATTACK1, ANIM_BREAKER_MELEE_ATTACK2, ANIM_BREAKER_MELEE_ATTACK3,
ANIM_BREAKER_MELEE_ATTACK4, ANIM_BREAKER_MELEE_ATTACK5, ANIM_BREAKER_MELEE_ATTACK6, ANIM_BREAKER_MELEE_HIT1,
ANIM_BREAKER_MELEE_HIT2, ANIM_BREAKER_MELEE_HIT3, ANIM_BREAKER_MELEE_HIT4, ANIM_BREAKER_MELEE_HIT5,
ANIM_BREAKER_MELEE_HIT6, ANIM_POWER_MELEE_1_CHARGE, ANIM_POWER_MELEE_2_CHARGE, ANIM_POWER_MELEE_3_CHARGE,
ANIM_POWER_MELEE_4_CHARGE, ANIM_POWER_MELEE_5_CHARGE, ANIM_POWER_MELEE_6_CHARGE, ANIM_POWER_MELEE_1_HIT,
ANIM_POWER_MELEE_2_HIT, ANIM_POWER_MELEE_3_HIT, ANIM_POWER_MELEE_4_HIT, ANIM_POWER_MELEE_5_HIT,
ANIM_POWER_MELEE_6_HIT, ANIM_STUNNED_MELEE, ANIM_KNOCKBACK, ANIM_KNOCKBACK_RECOVER_1,
ANIM_KNOCKBACK_RECOVER_2, ANIM_KNOCKBACK_HIT_WALL, ANIM_KI_ATTACK1_PREPARE, ANIM_KI_ATTACK1_FIRE,
ANIM_KI_ATTACK2_PREPARE, ANIM_KI_ATTACK2_FIRE, ANIM_KI_ATTACK3_PREPARE, ANIM_KI_ATTACK3_FIRE,
ANIM_KI_ATTACK4_PREPARE, ANIM_KI_ATTACK4_FIRE, ANIM_KI_ATTACK5_PREPARE, ANIM_KI_ATTACK5_FIRE,
ANIM_KI_ATTACK6_PREPARE, ANIM_KI_ATTACK6_FIRE, ANIM_KI_ATTACK1_ALT_PREPARE, ANIM_KI_ATTACK1_ALT_FIRE,
ANIM_KI_ATTACK2_ALT_PREPARE, ANIM_KI_ATTACK2_ALT_FIRE, ANIM_KI_ATTACK3_ALT_PREPARE, ANIM_KI_ATTACK3_ALT_FIRE,
ANIM_KI_ATTACK4_ALT_PREPARE, ANIM_KI_ATTACK4_ALT_FIRE, ANIM_KI_ATTACK5_ALT_PREPARE, ANIM_KI_ATTACK5_ALT_FIRE,
ANIM_KI_ATTACK6_ALT_PREPARE, ANIM_KI_ATTACK6_ALT_FIRE, MAX_ANIMATIONS, ANIM_BACKWALK,
ANIM_BACKRUN, MAX_TOTALANIMATIONS
}
enum baseStats_t {
stJumpTimedPower, stSpeed, stAirBrakeCost, stMeleeAttack,
stEnergyAttack, stKnockbackPower, stKnockbackIntensity, stZanzokenSpeed,
stZanzokenDistance, stZanzokenCost, stZanzokenQuickDistance, stZanzokenQuickCost,
stEnergyAttackCost, stBoostCost, stFatigueRecovery, stDefenseEnergy,
stDefenseMelee, stDefenseCapacity, stDefenseRecovery, stDefenseRecoveryDelay,
stTransformSubsequentDuration, stTransformSubsequentFatigueScale, stTransformSubsequentHealthScale, stTransformSubsequentMaximumScale
}
enum buffers_t { bfZanzokenCost }
enum cooldownTimers_t { cdLockon }
enum entity_event_t {
EV_NONE, EV_FOOTSTEP, EV_FOOTSTEP_METAL, EV_FOOTSPLASH,
EV_FOOTWADE, EV_SWIM, EV_STEP_4, EV_STEP_8,
EV_STEP_12, EV_STEP_16, EV_FALL_SHORT, EV_FALL_MEDIUM,
EV_FALL_FAR, EV_JUMP_PAD, EV_HIGHJUMP, EV_JUMP,
EV_WATER_TOUCH, EV_WATER_LEAVE, EV_WATER_UNDER, EV_WATER_CLEAR,
EV_WATER_SPLASH, EV_CHANGE_WEAPON, EV_FIRE_WEAPON, EV_CRASH,
EV_NULL, EV_DETONATE_WEAPON, EV_ALTFIRE_WEAPON, EV_TIERUP_FIRST,
EV_TIERUP, EV_TIERDOWN, EV_SYNCTIER, EV_ALTERUP_START,
EV_ALTERDOWN_START, EV_POWERINGUP_START, EV_BOOST_START, EV_BALLFLIP,
EV_MELEE_SPEED, EV_MELEE_MISS, EV_MELEE_KNOCKBACK, EV_MELEE_BREAKER,
EV_MELEE_STUN, EV_MELEE_CHECK, EV_MELEE_KNOCKOUT, EV_ZANZOKEN_END,
EV_ZANZOKEN_START, EV_POWER_STRUGGLE_START, EV_PLAYER_TELEPORT_IN, EV_PLAYER_TELEPORT_OUT,
EV_GENERAL_SOUND, EV_GLOBAL_SOUND, EV_GLOBAL_TEAM_SOUND, EV_BULLET_HIT_FLESH,
EV_BULLET_HIT_WALL, EV_MISSILE_HIT, EV_MISSILE_MISS, EV_MISSILE_MISS_METAL,
EV_MISSILE_MISS_AIR, EV_SHOTGUN, EV_BULLET, EV_AIRBRAKE,
EV_PAIN, EV_PAIN1, EV_PAIN2, EV_PAIN3,
EV_PAIN4, EV_PAIN5, EV_DEATH, EV_DEATH1,
EV_DEATH2, EV_DEATH3, EV_UNCONCIOUS, EV_OBITUARY,
EV_DEBUG_LINE, EV_STOPLOOPINGSOUND, EV_LOCKON_START, EV_LOCKON_RESTART,
EV_LOCKON_END, EV_STUNNED, EV_BLOCK, EV_PUSH,
EV_SWAT, EV_HOVER, EV_HOVER_FAST, EV_HOVER_LONG,
EV_BEAM_FADE, EV_EARTHQUAKE
}
enum entityType_t {
ET_GENERAL, ET_PLAYER, ET_ITEM, ET_MISSILE,
ET_MOVER, ET_BEAM, ET_PORTAL, ET_SPEAKER,
ET_PUSH_TRIGGER, ET_TELEPORT_TRIGGER, ET_INVISIBLE, ET_GRAPPLE,
ET_TEAM, ET_BEAMHEAD, ET_EXPLOSION, ET_EVENTS
}
enum gametype_t {
GT_FFA, GT_TOURNAMENT, GT_SINGLE_PLAYER, GT_STRUGGLE,
GT_TEAM, GT_CTF, GT_1FCTF, GT_OBELISK,
GT_HARVESTER, GT_MAX_GAME_TYPE
}
enum lockedStat_t {
lkPowerCurrent, lkPowerHealth, lkPowerMaximum, lkAttackPower,
lkLastLockedPlayer
}
enum measureTimers_t { mtBoost, mtZanzoken, mtZanzokenDistance, mtDrifting }
enum melee_t {
stMeleeInactive, stMeleeAggressing, stMeleeDegressing, stMeleeIdle,
stMeleeStartPower, stMeleeStartAttack, stMeleeStartDodge, stMeleeStartHit,
stMeleeUsingSpeed, stMeleeUsingPower, stMeleeUsingStun, stMeleeUsingBlock,
stMeleeUsingEvade, stMeleeUsingSpeedBreaker, stMeleeUsingChargeBreaker, stMeleeUsingZanzoken,
stMeleeChargingPower, stMeleeChargingStun
}
enum persEnum_t {
PERS_SCORE, PERS_TEAM, PERS_SPAWN_COUNT, PERS_PLAYEREVENTS,
PERS_ATTACKER, PERS_KILLED
}
enum pmtype_t {
PM_NORMAL, PM_NOCLIP, PM_SPECTATOR, PM_DEAD,
PM_FREEZE, PM_INTERMISSION, PM_SPINTERMISSION
}
enum powerLevel_t {
plCurrent, plFatigue, plHealth, plHealthPool,
plMaximum, plMaximumPool, plLimit, plUseCurrent,
plUseFatigue, plUseHealth, plUseMaximum, plDrainCurrent,
plDrainMaximum, plDrainFatigue, plDrainHealth, plTierCurrent,
plTierTotal, plDamageFromEnergy, plDamageFromMelee, plDamageGeneric,
plBuffer, plTierDesired, plTierChanged, plTierSelectionMode
}
enum powerup_t {
PW_NONE, PW_STATE, PW_SKILLS, PW_DRIFTING,
PW_INVULNERABILITY, PW_KNOCKBACK_SPEED, PW_NUM_POWERUPS
}
enum sequenceTimers_t {
sqAttack, sqAltAttack, sqPowerLevel, sqBlock,
sqWalk, sqBoost, sqLockon, sqJump,
sqZanzoken, sqForward, sqLeft, sqRight,
sqBack, sqUp, sqDown, sqRollRight,
sqRollLeft
}
enum statIndex_t {
stJumpTimed, stChargePercentPrimary, stChargePercentSecondary, stTransformState,
stMeleeState, stAnimState, stSkills, stTransformFirstDuration,
stTransformFirstEffectMaximum, stTransformFirstHealth, stTransformFirstFatigue, stTransformDuration,
stTransformFatigue, stTransformHealth, stTransformEffectMaximum
}
enum team_t {
TEAM_FREE, TEAM_RED, TEAM_BLUE, TEAM_SPECTATOR,
TEAM_NUM_TEAMS
}
enum teamtask_t {
TEAMTASK_NONE, TEAMTASK_OFFENSE, TEAMTASK_DEFENSE, TEAMTASK_PATROL,
TEAMTASK_FOLLOW, TEAMTASK_RETRIEVE, TEAMTASK_ESCORT, TEAMTASK_CAMP
}
enum timers_t {
tmUpdateTier, tmUpdateMelee, tmTransform, tmKnockback,
tmZanzoken, tmBoost, tmJump, tmBlink,
tmAttackLife, tmAttack1, tmAttack2, tmMeleeBreaker,
tmMeleeBreakerWait, tmMeleeCharge, tmMeleeSpeed, tmMeleeIdle,
tmStruggleEnergy, tmStruggleBlock, tmPowerRaise, tmPowerAuto,
tmBurning, tmRiding, tmImpede, tmCrash,
tmFreeze, tmRecover, tmBlind, tmSoar,
tmFall, tmSafe, tmOnGround, tmLockon
}
enum weapon_t {
WP_NONE, WP_GAUNTLET, WP_MACHINEGUN, WP_SHOTGUN,
WP_GRENADE_LAUNCHER, WP_ROCKET_LAUNCHER, WP_LIGHTNING, WP_RAILGUN,
WP_PLASMAGUN, WP_BFG, WP_GRAPPLING_HOOK, WP_NUM_WEAPONS
}
enum weaponstate_t {
WEAPON_READY, WEAPON_FIRING, WEAPON_GUIDING, WEAPON_CHARGING,
WEAPON_ALTFIRING, WEAPON_ALTGUIDING, WEAPON_ALTCHARGING, WEAPON_COOLING,
WEAPON_RAISING, WEAPON_DROPPING
}
Functions
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t *ps)
void BG_EvaluateTrajectory (entityState_t *es, const trajectory_t *tr, int atTime, vec3_t result)
void BG_EvaluateTrajectoryDelta (entityState_t *es, const trajectory_t *tr, int atTime, vec3_t result)
float BG_EvaluateWeaponChargeLevel (charge_t *ch, int atTime)
int BG_IntHiBits (const int i)
int BG_IntLoBits (const int i)
int BG_IntMergeBits (const int hi, const int lo)
void BG_PlayerStateToEntityState (playerState_t *ps, entityState_t *s, qboolean snap)
void BG_TouchJumpPad (playerState_t *ps, entityState_t *jumppad)
void PM_UpdateViewAngles (playerState_t *ps, const usercmd_t *cmd)
void Pmove (pmove_t *pmove)
Macro Definition Documentation
advancedFlight
#define advancedFlight 0x00000002
Definition at line 415 of file bg_public.h.
advancedMelee
#define advancedMelee 0x00000001
Definition at line 414 of file bg_public.h.
ANIM_TOGGLEBIT
#define ANIM_TOGGLEBIT 32768
Definition at line 749 of file bg_public.h.
ARENAS_PER_TIER
#define ARENAS_PER_TIER 4
Definition at line 839 of file bg_public.h.
ARMOR_PROTECTION
#define ARMOR_PROTECTION 0.66
Definition at line 34 of file bg_public.h.
atopGround
#define atopGround 0x02000000
Definition at line 395 of file bg_public.h.
canAlter
#define canAlter 0x00000004
Definition at line 416 of file bg_public.h.
canBallFlip
#define canBallFlip 0x00020000
Definition at line 431 of file bg_public.h.
canBlock
#define canBlock 0x00000008
Definition at line 417 of file bg_public.h.
canBoost
#define canBoost 0x00001000
Definition at line 426 of file bg_public.h.
canBreakLimit
#define canBreakLimit 0x00080000
Definition at line 433 of file bg_public.h.
canClench
#define canClench 0x00000200
Definition at line 423 of file bg_public.h.
canDischarge
#define canDischarge 0x00000800
Definition at line 425 of file bg_public.h.
canExpulse
#define canExpulse 0x00000400
Definition at line 424 of file bg_public.h.
canFly
#define canFly 0x00004000
Definition at line 428 of file bg_public.h.
canGrab
#define canGrab 0x00000080
Definition at line 421 of file bg_public.h.
canHandspring
#define canHandspring 0x00000040
Definition at line 420 of file bg_public.h.
canJump
#define canJump 0x00008000
Definition at line 429 of file bg_public.h.
canLockon
#define canLockon 0x00000020
Definition at line 419 of file bg_public.h.
canMelee
#define canMelee 0x00000010
Definition at line 418 of file bg_public.h.
canOverheal
#define canOverheal 0x00040000
Definition at line 432 of file bg_public.h.
canSlam
#define canSlam 0x00000100
Definition at line 422 of file bg_public.h.
canSoar
#define canSoar 0x00200000
Definition at line 435 of file bg_public.h.
canSwim
#define canSwim 0x00002000
Definition at line 427 of file bg_public.h.
canTransform
#define canTransform 0x00100000
Definition at line 434 of file bg_public.h.
canZanzoken
#define canZanzoken 0x00010000
Definition at line 430 of file bg_public.h.
causedDamage
#define causedDamage 0x00000400
Definition at line 411 of file bg_public.h.
CROUCH_VIEWHEIGHT
#define CROUCH_VIEWHEIGHT 12
Definition at line 53 of file bg_public.h.
CS_CLIENTSREADY
#define CS_CLIENTSREADY 29
Definition at line 98 of file bg_public.h.
CS_FLAGSTATUS
#define CS_FLAGSTATUS 23
Definition at line 94 of file bg_public.h.
CS_GAME_VERSION
#define CS_GAME_VERSION 20
Definition at line 91 of file bg_public.h.
CS_INTERMISSION
#define CS_INTERMISSION 22
Definition at line 93 of file bg_public.h.
CS_ITEMS
#define CS_ITEMS 27
Definition at line 97 of file bg_public.h.
CS_LEVEL_START_TIME
#define CS_LEVEL_START_TIME 21
Definition at line 92 of file bg_public.h.
CS_LOCATIONS
#define CS_LOCATIONS (CS_PLAYERS+MAX_CLIENTS)
Definition at line 103 of file bg_public.h.
CS_MAX
#define CS_MAX (CS_PARTICLES+MAX_LOCATIONS)
Definition at line 106 of file bg_public.h.
CS_MESSAGE
#define CS_MESSAGE 3
Definition at line 76 of file bg_public.h.
CS_MODELS
#define CS_MODELS 32
Definition at line 100 of file bg_public.h.
CS_MOTD
#define CS_MOTD 4
Definition at line 77 of file bg_public.h.
CS_MUSIC
#define CS_MUSIC 2
Definition at line 75 of file bg_public.h.
CS_PARTICLES
#define CS_PARTICLES (CS_LOCATIONS+MAX_LOCATIONS)
Definition at line 104 of file bg_public.h.
CS_PLAYERS
#define CS_PLAYERS (CS_SOUNDS+MAX_SOUNDS)
Definition at line 102 of file bg_public.h.
CS_SCORES1
#define CS_SCORES1 6
Definition at line 79 of file bg_public.h.
CS_SCORES2
#define CS_SCORES2 7
Definition at line 80 of file bg_public.h.
CS_SHADERSTATE
#define CS_SHADERSTATE 24
Definition at line 95 of file bg_public.h.
CS_SOUNDS
#define CS_SOUNDS (CS_MODELS+MAX_MODELS)
Definition at line 101 of file bg_public.h.
CS_TEAMVOTE_NO
#define CS_TEAMVOTE_NO 18
Definition at line 89 of file bg_public.h.
CS_TEAMVOTE_STRING
#define CS_TEAMVOTE_STRING 14
Definition at line 87 of file bg_public.h.
CS_TEAMVOTE_TIME
#define CS_TEAMVOTE_TIME 12
Definition at line 86 of file bg_public.h.
CS_TEAMVOTE_YES
#define CS_TEAMVOTE_YES 16
Definition at line 88 of file bg_public.h.
CS_VOTE_NO
#define CS_VOTE_NO 11
Definition at line 84 of file bg_public.h.
CS_VOTE_STRING
#define CS_VOTE_STRING 9
Definition at line 82 of file bg_public.h.
CS_VOTE_TIME
#define CS_VOTE_TIME 8
Definition at line 81 of file bg_public.h.
CS_VOTE_YES
#define CS_VOTE_YES 10
Definition at line 83 of file bg_public.h.
CS_WARMUP
#define CS_WARMUP 5
Definition at line 78 of file bg_public.h.
DEAD_VIEWHEIGHT
#define DEAD_VIEWHEIGHT -16
Definition at line 54 of file bg_public.h.
DEFAULT_GRAVITY
#define DEFAULT_GRAVITY 3000
Definition at line 32 of file bg_public.h.
DEFAULT_SHOTGUN_COUNT
#define DEFAULT_SHOTGUN_COUNT 11
Definition at line 41 of file bg_public.h.
DEFAULT_SHOTGUN_SPREAD
#define DEFAULT_SHOTGUN_SPREAD 700
Definition at line 40 of file bg_public.h.
DEFAULT_VIEWHEIGHT
#define DEFAULT_VIEWHEIGHT 26
Definition at line 52 of file bg_public.h.
DF_FIXED_FOV
#define DF_FIXED_FOV 16
Definition at line 786 of file bg_public.h.
DF_NO_FALLING
#define DF_NO_FALLING 8
Definition at line 785 of file bg_public.h.
DF_NO_FOOTSTEPS
#define DF_NO_FOOTSTEPS 32
Definition at line 787 of file bg_public.h.
EARTHQUAKE_SYSTEM
#define EARTHQUAKE_SYSTEM 1
Definition at line 30 of file bg_public.h.
EF_AURA
#define EF_AURA 0x00000010
Definition at line 487 of file bg_public.h.
EF_BOUNCE
#define EF_BOUNCE 0x00000010
Definition at line 477 of file bg_public.h.
EF_BOUNCE_HALF
#define EF_BOUNCE_HALF 0x00000020
Definition at line 478 of file bg_public.h.
EF_CONNECTION
#define EF_CONNECTION 0x00002000
Definition at line 483 of file bg_public.h.
EF_DEAD
#define EF_DEAD 0x00000001
Definition at line 474 of file bg_public.h.
EF_FIRING
#define EF_FIRING 0x00000100
Definition at line 480 of file bg_public.h.
EF_GUIDED
#define EF_GUIDED 0x00004000
Definition at line 486 of file bg_public.h.
EF_MOVER_STOP
#define EF_MOVER_STOP 0x00000400
Definition at line 481 of file bg_public.h.
EF_NODRAW
#define EF_NODRAW 0x00000080
Definition at line 479 of file bg_public.h.
EF_PLAYER_EVENT
#define EF_PLAYER_EVENT 0x00000010
Definition at line 476 of file bg_public.h.
EF_TALK
#define EF_TALK 0x00001000
Definition at line 482 of file bg_public.h.
EF_TEAMVOTED
#define EF_TEAMVOTED 0x00080000
Definition at line 485 of file bg_public.h.
EF_TELEPORT_BIT
#define EF_TELEPORT_BIT 0x00000004
Definition at line 475 of file bg_public.h.
EF_VOTED
#define EF_VOTED 0x00004000
Definition at line 484 of file bg_public.h.
EV_EVENT_BIT1
#define EV_EVENT_BIT1 0x00000100
Definition at line 514 of file bg_public.h.
EV_EVENT_BIT2
#define EV_EVENT_BIT2 0x00000200
Definition at line 515 of file bg_public.h.
EV_EVENT_BITS
#define EV_EVENT_BITS (EV_EVENT_BIT1|EV_EVENT_BIT2)
Definition at line 516 of file bg_public.h.
EVENT_VALID_MSEC
#define EVENT_VALID_MSEC 300
Definition at line 518 of file bg_public.h.
GAME_VERSION
#define GAME_VERSION "ZEQ2"
Definition at line 28 of file bg_public.h.
GIB_HEALTH
#define GIB_HEALTH -40
Definition at line 33 of file bg_public.h.
hasFlipOffset
#define hasFlipOffset 0x00000001
Definition at line 370 of file bg_public.h.
isBlinking
#define isBlinking 0x01000000
Definition at line 394 of file bg_public.h.
isBreakingLimit
#define isBreakingLimit 0x00020000
Definition at line 387 of file bg_public.h.
isBurning
#define isBurning 0x00000040
Definition at line 407 of file bg_public.h.
isCharging
#define isCharging 0x00100000
Definition at line 390 of file bg_public.h.
isCrashed
#define isCrashed 0x00040000
Definition at line 388 of file bg_public.h.
isDashing
#define isDashing 0x00000100
Definition at line 409 of file bg_public.h.
isDead
#define isDead 0x00010000
Definition at line 386 of file bg_public.h.
isGuiding
#define isGuiding 0x00080000
Definition at line 389 of file bg_public.h.
isHovering
#define isHovering 0x00000080
Definition at line 408 of file bg_public.h.
isPreparing
#define isPreparing 0x00400000
Definition at line 392 of file bg_public.h.
isRiding
#define isRiding 0x00000020
Definition at line 406 of file bg_public.h.
isStruggling
#define isStruggling 0x00004000
Definition at line 384 of file bg_public.h.
isTargetable
#define isTargetable 0x00000200
Definition at line 410 of file bg_public.h.
isTargeted
#define isTargeted 0x00200000
Definition at line 391 of file bg_public.h.
isTransforming
#define isTransforming 0x00002000
Definition at line 383 of file bg_public.h.
isUnconcious
#define isUnconcious 0x00008000
Definition at line 385 of file bg_public.h.
isUnsafe
#define isUnsafe 0x00800000
Definition at line 393 of file bg_public.h.
ITEM_RADIUS
#define ITEM_RADIUS 15
Definition at line 43 of file bg_public.h.
keyTierDown
#define keyTierDown 0x00001000
Definition at line 382 of file bg_public.h.
keyTierUp
#define keyTierUp 0x00000800
Definition at line 381 of file bg_public.h.
LIGHTNING_RANGE
#define LIGHTNING_RANGE 768
Definition at line 45 of file bg_public.h.
LOCATION_BACK
#define LOCATION_BACK 0x00000800
Definition at line 756 of file bg_public.h.
LOCATION_FRONT
#define LOCATION_FRONT 0x00000400
Definition at line 755 of file bg_public.h.
LOCATION_LEFT
#define LOCATION_LEFT 0x00000100
Definition at line 753 of file bg_public.h.
LOCATION_NONE
#define LOCATION_NONE 0x00000000
Definition at line 752 of file bg_public.h.
LOCATION_RIGHT
#define LOCATION_RIGHT 0x00000200
Definition at line 754 of file bg_public.h.
locked360
#define locked360 0x00000008
Definition at line 404 of file bg_public.h.
lockedPitch
#define lockedPitch 0x00000001
Definition at line 401 of file bg_public.h.
lockedRoll
#define lockedRoll 0x00000004
Definition at line 403 of file bg_public.h.
lockedSpin
#define lockedSpin 0x00000010
Definition at line 405 of file bg_public.h.
lockedYaw
#define lockedYaw 0x00000002
Definition at line 402 of file bg_public.h.
MASK_ALL
#define MASK_ALL (-1)
Definition at line 790 of file bg_public.h.
MASK_DEADSOLID
#define MASK_DEADSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP)
Definition at line 793 of file bg_public.h.
MASK_OPAQUE
#define MASK_OPAQUE (CONTENTS_SOLID|CONTENTS_SLIME|CONTENTS_LAVA)
Definition at line 795 of file bg_public.h.
MASK_PLAYERSOLID
#define MASK_PLAYERSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_BODY)
Definition at line 792 of file bg_public.h.
MASK_SHOT
#define MASK_SHOT (CONTENTS_SOLID|CONTENTS_BODY|CONTENTS_CORPSE)
Definition at line 796 of file bg_public.h.
MASK_SOLID
#define MASK_SOLID (CONTENTS_SOLID)
Definition at line 791 of file bg_public.h.
MASK_WATER
#define MASK_WATER (CONTENTS_WATER|CONTENTS_LAVA|CONTENTS_SLIME)
Definition at line 794 of file bg_public.h.
MAX_ARENAS
#define MAX_ARENAS 1024
Definition at line 840 of file bg_public.h.
MAX_ARENAS_TEXT
#define MAX_ARENAS_TEXT 8192
Definition at line 841 of file bg_public.h.
MAX_ITEMS
#define MAX_ITEMS 256
Definition at line 36 of file bg_public.h.
MAXTOUCH
#define MAXTOUCH 32
Definition at line 182 of file bg_public.h.
MINS_Z
#define MINS_Z -24
Definition at line 51 of file bg_public.h.
nearGround
#define nearGround 0x04000000
Definition at line 396 of file bg_public.h.
PMF_ATTACK1_HELD
#define PMF_ATTACK1_HELD 1
Definition at line 166 of file bg_public.h.
PMF_ATTACK2_HELD
#define PMF_ATTACK2_HELD 2
Definition at line 167 of file bg_public.h.
PMF_BACKWARDS_JUMP
#define PMF_BACKWARDS_JUMP 8
Definition at line 168 of file bg_public.h.
PMF_BACKWARDS_RUN
#define PMF_BACKWARDS_RUN 16
Definition at line 169 of file bg_public.h.
PMF_BLOCK_HELD
#define PMF_BLOCK_HELD 32768
Definition at line 180 of file bg_public.h.
PMF_BOOST_HELD
#define PMF_BOOST_HELD 1024
Definition at line 174 of file bg_public.h.
PMF_CAN_MOVE
#define PMF_CAN_MOVE 512
Definition at line 173 of file bg_public.h.
PMF_FOLLOW
#define PMF_FOLLOW 4096
Definition at line 177 of file bg_public.h.
PMF_FORWARDS_JUMP
#define PMF_FORWARDS_JUMP 32
Definition at line 170 of file bg_public.h.
PMF_GRAPPLE_PULL
#define PMF_GRAPPLE_PULL 2048
Definition at line 176 of file bg_public.h.
PMF_LOCK_HELD
#define PMF_LOCK_HELD 16384
Definition at line 179 of file bg_public.h.
PMF_SCOREBOARD
#define PMF_SCOREBOARD 8192
Definition at line 178 of file bg_public.h.
PMF_TIME_KNOCKBACK
#define PMF_TIME_KNOCKBACK 64
Definition at line 171 of file bg_public.h.
PMF_TIME_WATERJUMP
#define PMF_TIME_WATERJUMP 256
Definition at line 172 of file bg_public.h.
PMF_ZANZOKEN
#define PMF_ZANZOKEN 2048
Definition at line 175 of file bg_public.h.
pointGravity
#define pointGravity 0x00400000
Definition at line 436 of file bg_public.h.
RADAR_BURST
#define RADAR_BURST 2
Definition at line 57 of file bg_public.h.
RADAR_WARN
#define RADAR_WARN 1
Definition at line 56 of file bg_public.h.
RANK_TIED_FLAG
#define RANK_TIED_FLAG 0x4000
Definition at line 38 of file bg_public.h.
SCORE_NOT_PRESENT
#define SCORE_NOT_PRESENT -9999
Definition at line 47 of file bg_public.h.
TEAM_LOCATION_UPDATE_TIME
#define TEAM_LOCATION_UPDATE_TIME 1000
Definition at line 766 of file bg_public.h.
TEAM_MAXOVERLAY
#define TEAM_MAXOVERLAY 32
Definition at line 769 of file bg_public.h.
underWater
#define underWater 0x08000000
Definition at line 397 of file bg_public.h.
usingAlter
#define usingAlter 0x00000008
Definition at line 373 of file bg_public.h.
usingBallFlip
#define usingBallFlip 0x00000400
Definition at line 380 of file bg_public.h.
usingBlock
#define usingBlock 0x00000004
Definition at line 372 of file bg_public.h.
usingBoost
#define usingBoost 0x00000002
Definition at line 371 of file bg_public.h.
usingFlight
#define usingFlight 0x00000080
Definition at line 377 of file bg_public.h.
usingJump
#define usingJump 0x00000010
Definition at line 374 of file bg_public.h.
usingMelee
#define usingMelee 0x00000200
Definition at line 379 of file bg_public.h.
usingQuickZanzoken
#define usingQuickZanzoken 0x10000000
Definition at line 398 of file bg_public.h.
usingSoar
#define usingSoar 0x00000100
Definition at line 378 of file bg_public.h.
usingWeapon
#define usingWeapon 0x00000040
Definition at line 376 of file bg_public.h.
usingZanzoken
#define usingZanzoken 0x00000020
Definition at line 375 of file bg_public.h.
VOTE_TIME
#define VOTE_TIME 30000
Definition at line 49 of file bg_public.h.
Enumeration Type Documentation
animNumber_t
enum animNumber_t
Enumerator
ANIM_DEATH_GROUND
ANIM_DEATH_AIR
ANIM_DEATH_AIR_LAND
ANIM_STUN
ANIM_FLOOR_RECOVER
ANIM_IDLE
ANIM_IDLE_LOCKED
ANIM_TURN
ANIM_WALK
ANIM_RUN
ANIM_SWIM_IDLE
ANIM_SWIM
ANIM_JUMP_UP
ANIM_LAND_UP
ANIM_JUMP_FORWARD
ANIM_LAND_FORWARD
ANIM_JUMP_BACK
ANIM_LAND_BACK
ANIM_DASH_RIGHT
ANIM_DASH_LEFT
ANIM_DASH_FORWARD
ANIM_DASH_BACKWARD
ANIM_FLY_IDLE
ANIM_FLY_START
ANIM_FLY_FORWARD
ANIM_FLY_BACKWARD
ANIM_FLY_UP
ANIM_FLY_DOWN
ANIM_KI_CHARGE
ANIM_PL_UP
ANIM_PL_DOWN
ANIM_TRANS_UP
ANIM_TRANS_BACK
ANIM_STUNNED
ANIM_PUSH
ANIM_DEFLECT
ANIM_BLOCK
ANIM_SPEED_MELEE_ATTACK
ANIM_SPEED_MELEE_DODGE
ANIM_SPEED_MELEE_BLOCK
ANIM_SPEED_MELEE_HIT
ANIM_BREAKER_MELEE_ATTACK1
ANIM_BREAKER_MELEE_ATTACK2
ANIM_BREAKER_MELEE_ATTACK3
ANIM_BREAKER_MELEE_ATTACK4
ANIM_BREAKER_MELEE_ATTACK5
ANIM_BREAKER_MELEE_ATTACK6
ANIM_BREAKER_MELEE_HIT1
ANIM_BREAKER_MELEE_HIT2
ANIM_BREAKER_MELEE_HIT3
ANIM_BREAKER_MELEE_HIT4
ANIM_BREAKER_MELEE_HIT5
ANIM_BREAKER_MELEE_HIT6
ANIM_POWER_MELEE_1_CHARGE
ANIM_POWER_MELEE_2_CHARGE
ANIM_POWER_MELEE_3_CHARGE
ANIM_POWER_MELEE_4_CHARGE
ANIM_POWER_MELEE_5_CHARGE
ANIM_POWER_MELEE_6_CHARGE
ANIM_POWER_MELEE_1_HIT
ANIM_POWER_MELEE_2_HIT
ANIM_POWER_MELEE_3_HIT
ANIM_POWER_MELEE_4_HIT
ANIM_POWER_MELEE_5_HIT
ANIM_POWER_MELEE_6_HIT
ANIM_STUNNED_MELEE
ANIM_KNOCKBACK
ANIM_KNOCKBACK_RECOVER_1
ANIM_KNOCKBACK_RECOVER_2
ANIM_KNOCKBACK_HIT_WALL
ANIM_KI_ATTACK1_PREPARE
ANIM_KI_ATTACK1_FIRE
ANIM_KI_ATTACK2_PREPARE
ANIM_KI_ATTACK2_FIRE
ANIM_KI_ATTACK3_PREPARE
ANIM_KI_ATTACK3_FIRE
ANIM_KI_ATTACK4_PREPARE
ANIM_KI_ATTACK4_FIRE
ANIM_KI_ATTACK5_PREPARE
ANIM_KI_ATTACK5_FIRE
ANIM_KI_ATTACK6_PREPARE
ANIM_KI_ATTACK6_FIRE
ANIM_KI_ATTACK1_ALT_PREPARE
ANIM_KI_ATTACK1_ALT_FIRE
ANIM_KI_ATTACK2_ALT_PREPARE
ANIM_KI_ATTACK2_ALT_FIRE
ANIM_KI_ATTACK3_ALT_PREPARE
ANIM_KI_ATTACK3_ALT_FIRE
ANIM_KI_ATTACK4_ALT_PREPARE
ANIM_KI_ATTACK4_ALT_FIRE
ANIM_KI_ATTACK5_ALT_PREPARE
ANIM_KI_ATTACK5_ALT_FIRE
ANIM_KI_ATTACK6_ALT_PREPARE
ANIM_KI_ATTACK6_ALT_FIRE
MAX_ANIMATIONS
ANIM_BACKWALK
ANIM_BACKRUN
MAX_TOTALANIMATIONS
Definition at line 611 of file bg_public.h.
              {
     // DEATH
     ANIM_DEATH_GROUND,
     ANIM_DEATH_AIR,
     ANIM_DEATH_AIR_LAND,
     // STUN
     ANIM_STUN,
     // RECOVER
     ANIM_FLOOR_RECOVER,
     // IDLE
     ANIM_IDLE,
     ANIM_IDLE_LOCKED,
     ANIM_TURN,
     // WALK
     ANIM_WALK,
     // RUN
     ANIM_RUN,
     // SWIM
     ANIM_SWIM_IDLE,
     ANIM_SWIM,
     // JUMP
     ANIM_JUMP_UP,
     ANIM_LAND_UP,
     ANIM_JUMP_FORWARD,
     ANIM_LAND_FORWARD,
     ANIM_JUMP_BACK,
     ANIM_LAND_BACK,
     // DASH
     ANIM_DASH_RIGHT,
     ANIM_DASH_LEFT,
     ANIM_DASH_FORWARD,
     ANIM_DASH_BACKWARD,
     // FLY
     ANIM_FLY_IDLE,
     ANIM_FLY_START,
     ANIM_FLY_FORWARD,
     ANIM_FLY_BACKWARD,
     ANIM_FLY_UP,
     ANIM_FLY_DOWN,
     // KI
     ANIM_KI_CHARGE,
     ANIM_PL_UP,
     ANIM_PL_DOWN,
     // TRANSFORM
     ANIM_TRANS_UP,
     ANIM_TRANS_BACK,
     // DEFENSE
     ANIM_STUNNED,
     ANIM_PUSH,
     ANIM_DEFLECT,
     ANIM_BLOCK,
     // SPEED MELEE ATTACKS
     ANIM_SPEED_MELEE_ATTACK,
     ANIM_SPEED_MELEE_DODGE,
     ANIM_SPEED_MELEE_BLOCK,
     ANIM_SPEED_MELEE_HIT,
     // BREAKER MELEE ATTACK
     ANIM_BREAKER_MELEE_ATTACK1,
     ANIM_BREAKER_MELEE_ATTACK2,
     ANIM_BREAKER_MELEE_ATTACK3,
     ANIM_BREAKER_MELEE_ATTACK4,
     ANIM_BREAKER_MELEE_ATTACK5,
     ANIM_BREAKER_MELEE_ATTACK6,
     ANIM_BREAKER_MELEE_HIT1,
     ANIM_BREAKER_MELEE_HIT2,
     ANIM_BREAKER_MELEE_HIT3,
     ANIM_BREAKER_MELEE_HIT4,
     ANIM_BREAKER_MELEE_HIT5,
     ANIM_BREAKER_MELEE_HIT6,
     // POWER MELEE ATTACKS
     ANIM_POWER_MELEE_1_CHARGE,
     ANIM_POWER_MELEE_2_CHARGE,
     ANIM_POWER_MELEE_3_CHARGE,
     ANIM_POWER_MELEE_4_CHARGE,
     ANIM_POWER_MELEE_5_CHARGE,
     ANIM_POWER_MELEE_6_CHARGE,
     ANIM_POWER_MELEE_1_HIT,
     ANIM_POWER_MELEE_2_HIT,
     ANIM_POWER_MELEE_3_HIT,
     ANIM_POWER_MELEE_4_HIT,
     ANIM_POWER_MELEE_5_HIT,
     ANIM_POWER_MELEE_6_HIT,
     // STUN MELEE
     ANIM_STUNNED_MELEE,
     // KNOCKBACK
     ANIM_KNOCKBACK,
     ANIM_KNOCKBACK_RECOVER_1,
     ANIM_KNOCKBACK_RECOVER_2,
     ANIM_KNOCKBACK_HIT_WALL,
 // KI ATTACKS
     ANIM_KI_ATTACK1_PREPARE,
     ANIM_KI_ATTACK1_FIRE,
     ANIM_KI_ATTACK2_PREPARE,
     ANIM_KI_ATTACK2_FIRE,
     ANIM_KI_ATTACK3_PREPARE,
     ANIM_KI_ATTACK3_FIRE,
     ANIM_KI_ATTACK4_PREPARE,
     ANIM_KI_ATTACK4_FIRE,
     ANIM_KI_ATTACK5_PREPARE,
     ANIM_KI_ATTACK5_FIRE,
     ANIM_KI_ATTACK6_PREPARE,
     ANIM_KI_ATTACK6_FIRE,
     ANIM_KI_ATTACK1_ALT_PREPARE,
     ANIM_KI_ATTACK1_ALT_FIRE,
     ANIM_KI_ATTACK2_ALT_PREPARE,
     ANIM_KI_ATTACK2_ALT_FIRE,
     ANIM_KI_ATTACK3_ALT_PREPARE,
     ANIM_KI_ATTACK3_ALT_FIRE,
     ANIM_KI_ATTACK4_ALT_PREPARE,
     ANIM_KI_ATTACK4_ALT_FIRE,
     ANIM_KI_ATTACK5_ALT_PREPARE,
     ANIM_KI_ATTACK5_ALT_FIRE,
     ANIM_KI_ATTACK6_ALT_PREPARE,
     ANIM_KI_ATTACK6_ALT_FIRE,
     // END ADDING
     MAX_ANIMATIONS,
     ANIM_BACKWALK,
     ANIM_BACKRUN,
     MAX_TOTALANIMATIONS
 } animNumber_t;
baseStats_t
enum baseStats_t
Enumerator
stJumpTimedPower
stSpeed
stAirBrakeCost
stMeleeAttack
stEnergyAttack
stKnockbackPower
stKnockbackIntensity
stZanzokenSpeed
stZanzokenDistance
stZanzokenCost
stZanzokenQuickDistance
stZanzokenQuickCost
stEnergyAttackCost
stBoostCost
stFatigueRecovery
stDefenseEnergy
stDefenseMelee
stDefenseCapacity
stDefenseRecovery
stDefenseRecoveryDelay
stTransformSubsequentDuration
stTransformSubsequentFatigueScale
stTransformSubsequentHealthScale
stTransformSubsequentMaximumScale
Definition at line 234 of file bg_public.h.
             {
     stJumpTimedPower,
     stSpeed,
     stAirBrakeCost,
     stMeleeAttack,
     stEnergyAttack,
     stKnockbackPower,
     stKnockbackIntensity,
     stZanzokenSpeed,
     stZanzokenDistance,
     stZanzokenCost,
     stZanzokenQuickDistance,
     stZanzokenQuickCost,
     stEnergyAttackCost,
     stBoostCost,
     stFatigueRecovery,
     stDefenseEnergy,
     stDefenseMelee,
     stDefenseCapacity,
     stDefenseRecovery,
     stDefenseRecoveryDelay,
     stTransformSubsequentDuration,
     stTransformSubsequentFatigueScale,
     stTransformSubsequentHealthScale,
     stTransformSubsequentMaximumScale,
 }baseStats_t;
buffers_t
enum buffers_t
Enumerator
bfZanzokenCost
Definition at line 365 of file bg_public.h.
              {
     bfZanzokenCost
 }buffers_t;
cooldownTimers_t
enum cooldownTimers_t
Enumerator
cdLockon
Definition at line 327 of file bg_public.h.
             {
     cdLockon
 }cooldownTimers_t;
entity_event_t
enum entity_event_t
Enumerator
EV_NONE
EV_FOOTSTEP
EV_FOOTSTEP_METAL
EV_FOOTSPLASH
EV_FOOTWADE
EV_SWIM
EV_STEP_4
EV_STEP_8
EV_STEP_12
EV_STEP_16
EV_FALL_SHORT
EV_FALL_MEDIUM
EV_FALL_FAR
EV_JUMP_PAD
EV_HIGHJUMP
EV_JUMP
EV_WATER_TOUCH
EV_WATER_LEAVE
EV_WATER_UNDER
EV_WATER_CLEAR
EV_WATER_SPLASH
EV_CHANGE_WEAPON
EV_FIRE_WEAPON
EV_CRASH
EV_NULL
EV_DETONATE_WEAPON
EV_ALTFIRE_WEAPON
EV_TIERUP_FIRST
EV_TIERUP
EV_TIERDOWN
EV_SYNCTIER
EV_ALTERUP_START
EV_ALTERDOWN_START
EV_POWERINGUP_START
EV_BOOST_START
EV_BALLFLIP
EV_MELEE_SPEED
EV_MELEE_MISS
EV_MELEE_KNOCKBACK
EV_MELEE_BREAKER
EV_MELEE_STUN
EV_MELEE_CHECK
EV_MELEE_KNOCKOUT
EV_ZANZOKEN_END
EV_ZANZOKEN_START
EV_POWER_STRUGGLE_START
EV_PLAYER_TELEPORT_IN
EV_PLAYER_TELEPORT_OUT
EV_GENERAL_SOUND
EV_GLOBAL_SOUND
EV_GLOBAL_TEAM_SOUND
EV_BULLET_HIT_FLESH
EV_BULLET_HIT_WALL
EV_MISSILE_HIT
EV_MISSILE_MISS
EV_MISSILE_MISS_METAL
EV_MISSILE_MISS_AIR
EV_SHOTGUN
EV_BULLET
EV_AIRBRAKE
EV_PAIN
EV_PAIN1
EV_PAIN2
EV_PAIN3
EV_PAIN4
EV_PAIN5
EV_DEATH
EV_DEATH1
EV_DEATH2
EV_DEATH3
EV_UNCONCIOUS
EV_OBITUARY
EV_DEBUG_LINE
EV_STOPLOOPINGSOUND
EV_LOCKON_START
EV_LOCKON_RESTART
EV_LOCKON_END
EV_STUNNED
EV_BLOCK
EV_PUSH
EV_SWAT
EV_HOVER
EV_HOVER_FAST
EV_HOVER_LONG
EV_BEAM_FADE
EV_EARTHQUAKE
Definition at line 520 of file bg_public.h.
              {
     EV_NONE,
     EV_FOOTSTEP,
     EV_FOOTSTEP_METAL,
     EV_FOOTSPLASH,
     EV_FOOTWADE,
     EV_SWIM,
     EV_STEP_4,
     EV_STEP_8,
     EV_STEP_12,
     EV_STEP_16,
     EV_FALL_SHORT,
     EV_FALL_MEDIUM,
     EV_FALL_FAR,
     EV_JUMP_PAD,            // boing sound at origin, jump sound on player
     EV_HIGHJUMP,
     EV_JUMP,
     EV_WATER_TOUCH, // foot touches
     EV_WATER_LEAVE, // foot leaves
     EV_WATER_UNDER, // head touches
     EV_WATER_CLEAR, // head leaves
     EV_WATER_SPLASH,    // something hits water fast
     EV_CHANGE_WEAPON,
     EV_FIRE_WEAPON,
     // ADDING FOR ZEQ2
     EV_CRASH,
     EV_NULL,
     EV_DETONATE_WEAPON,
     EV_ALTFIRE_WEAPON,
     EV_TIERUP_FIRST,
     EV_TIERUP,
     EV_TIERDOWN,
     EV_SYNCTIER,
     EV_ALTERUP_START,
     EV_ALTERDOWN_START,
     EV_POWERINGUP_START,
     EV_BOOST_START,
     EV_BALLFLIP,
     EV_MELEE_SPEED,
     EV_MELEE_MISS,
     EV_MELEE_KNOCKBACK,
     EV_MELEE_BREAKER,
     EV_MELEE_STUN,
     EV_MELEE_CHECK,
     EV_MELEE_KNOCKOUT,
     EV_ZANZOKEN_END,
     EV_ZANZOKEN_START,
     EV_POWER_STRUGGLE_START,
     EV_PLAYER_TELEPORT_IN,
     EV_PLAYER_TELEPORT_OUT,
     EV_GENERAL_SOUND,
     EV_GLOBAL_SOUND,        // no attenuation
     EV_GLOBAL_TEAM_SOUND,
     EV_BULLET_HIT_FLESH,
     EV_BULLET_HIT_WALL,
     EV_MISSILE_HIT,
     EV_MISSILE_MISS,
     EV_MISSILE_MISS_METAL,
     EV_MISSILE_MISS_AIR,
     EV_SHOTGUN,
     EV_BULLET,              // otherEntity is the shooter
     EV_AIRBRAKE,
     EV_PAIN,
     EV_PAIN1,
     EV_PAIN2,
     EV_PAIN3,
     EV_PAIN4,
     EV_PAIN5,
     EV_DEATH,
     EV_DEATH1,
     EV_DEATH2,
     EV_DEATH3,
     EV_UNCONCIOUS,
     EV_OBITUARY,
     EV_DEBUG_LINE,
     EV_STOPLOOPINGSOUND,
     EV_LOCKON_START,
     EV_LOCKON_RESTART,
     EV_LOCKON_END,
     EV_STUNNED,
     EV_BLOCK,
     EV_PUSH,
     EV_SWAT,
     EV_HOVER,
     EV_HOVER_FAST,
     EV_HOVER_LONG,
     // ADDING FOR ZEQ2
     EV_BEAM_FADE,
     EV_EARTHQUAKE
     // END ADDING
 } entity_event_t;
entityType_t
enum entityType_t
Enumerator
ET_GENERAL
ET_PLAYER
ET_ITEM
ET_MISSILE
ET_MOVER
ET_BEAM
ET_PORTAL
ET_SPEAKER
ET_PUSH_TRIGGER
ET_TELEPORT_TRIGGER
ET_INVISIBLE
ET_GRAPPLE
ET_TEAM
ET_BEAMHEAD
ET_EXPLOSION
ET_EVENTS
Definition at line 801 of file bg_public.h.
              {
     ET_GENERAL,
     ET_PLAYER,
     ET_ITEM,
     ET_MISSILE,
     ET_MOVER,
     ET_BEAM,
     ET_PORTAL,
     ET_SPEAKER,
     ET_PUSH_TRIGGER,
     ET_TELEPORT_TRIGGER,
     ET_INVISIBLE,
     ET_GRAPPLE,             // grapple hooked on wall
     ET_TEAM,
     // <-- RiO: New entity types for ZEQ2
     ET_BEAMHEAD,            // a beam's beamhead
     ET_EXPLOSION,
     // -->
     ET_EVENTS               // any of the EV_* events can be added freestanding
                             // by setting eType to ET_EVENTS + eventNum
                             // this avoids having to set eFlags and eventNum
 } entityType_t;
gametype_t
enum gametype_t
Enumerator
GT_FFA
GT_TOURNAMENT
GT_SINGLE_PLAYER
GT_STRUGGLE
GT_TEAM
GT_CTF
GT_1FCTF
GT_OBELISK
GT_HARVESTER
GT_MAX_GAME_TYPE
Definition at line 112 of file bg_public.h.
              {
     GT_FFA,             // free for all
     GT_TOURNAMENT,      // one on one tournament
     GT_SINGLE_PLAYER,   // single player ffa
     GT_STRUGGLE,
     //-- team games go after this --
     GT_TEAM,            // team deathmatch
     GT_CTF,             // capture the flag
     GT_1FCTF,
     GT_OBELISK,
     GT_HARVESTER,
     GT_MAX_GAME_TYPE
 } gametype_t;
lockedStat_t
enum lockedStat_t
Enumerator
lkPowerCurrent
lkPowerHealth
lkPowerMaximum
lkAttackPower
lkLastLockedPlayer
Definition at line 286 of file bg_public.h.
             {
     lkPowerCurrent,
     lkPowerHealth,
     lkPowerMaximum,
     lkAttackPower,
     lkLastLockedPlayer
 }lockedStat_t;
measureTimers_t
enum measureTimers_t
Enumerator
mtBoost
mtZanzoken
mtZanzokenDistance
mtDrifting
Definition at line 358 of file bg_public.h.
              {
     mtBoost,
     mtZanzoken,
     mtZanzokenDistance,
     mtDrifting,
 }measureTimers_t;
melee_t
enum melee_t
Enumerator
stMeleeInactive
stMeleeAggressing
stMeleeDegressing
stMeleeIdle
stMeleeStartPower
stMeleeStartAttack
stMeleeStartDodge
stMeleeStartHit
stMeleeUsingSpeed
stMeleeUsingPower
stMeleeUsingStun
stMeleeUsingBlock
stMeleeUsingEvade
stMeleeUsingSpeedBreaker
stMeleeUsingChargeBreaker
stMeleeUsingZanzoken
stMeleeChargingPower
stMeleeChargingStun
Definition at line 439 of file bg_public.h.
              {
     stMeleeInactive,
     stMeleeAggressing,
     stMeleeDegressing,
     stMeleeIdle,
     stMeleeStartPower,
     stMeleeStartAttack,
     stMeleeStartDodge,
     stMeleeStartHit,
     stMeleeUsingSpeed,
     stMeleeUsingPower,
     stMeleeUsingStun,
     stMeleeUsingBlock,
     stMeleeUsingEvade,
     stMeleeUsingSpeedBreaker,
     stMeleeUsingChargeBreaker,
     stMeleeUsingZanzoken,
     stMeleeChargingPower,
     stMeleeChargingStun
 } melee_t;
persEnum_t
enum persEnum_t
Enumerator
PERS_SCORE
PERS_TEAM
PERS_SPAWN_COUNT
PERS_PLAYEREVENTS
PERS_ATTACKER
PERS_KILLED
Definition at line 463 of file bg_public.h.
              {
     PERS_SCORE,                     // !!! MUST NOT CHANGE, SERVER AND GAME BOTH REFERENCE !!!
     PERS_TEAM,                      // player team
     PERS_SPAWN_COUNT,               // incremented every respawn
     PERS_PLAYEREVENTS,              // 16 bits that can be flipped for events
     PERS_ATTACKER,                  // clientnum of last damage inflicter
     PERS_KILLED                 // count of the number of times you died
 } persEnum_t;
pmtype_t
enum pmtype_t
Enumerator
PM_NORMAL
PM_NOCLIP
PM_SPECTATOR
PM_DEAD
PM_FREEZE
PM_INTERMISSION
PM_SPINTERMISSION
Definition at line 137 of file bg_public.h.
              {
     PM_NORMAL,      // can accelerate and turn
     PM_NOCLIP,      // noclip movement
     PM_SPECTATOR,   // still run into walls
     PM_DEAD,        // no acceleration or turning, but free falling
     PM_FREEZE,      // stuck in place with no control
     PM_INTERMISSION,    // no movement or status bar
     PM_SPINTERMISSION   // no movement or status bar
 } pmtype_t;
powerLevel_t
enum powerLevel_t
Enumerator
plCurrent
plFatigue
plHealth
plHealthPool
plMaximum
plMaximumPool
plLimit
plUseCurrent
plUseFatigue
plUseHealth
plUseMaximum
plDrainCurrent
plDrainMaximum
plDrainFatigue
plDrainHealth
plTierCurrent
plTierTotal
plDamageFromEnergy
plDamageFromMelee
plDamageGeneric
plBuffer
plTierDesired
plTierChanged
plTierSelectionMode
Definition at line 260 of file bg_public.h.
             {
     plCurrent,
     plFatigue,
     plHealth,
     plHealthPool,
     plMaximum,
     plMaximumPool,
     plLimit,
     plUseCurrent,
     plUseFatigue,
     plUseHealth,
     plUseMaximum,
     plDrainCurrent,
     plDrainMaximum,
     plDrainFatigue,
     plDrainHealth,
     plTierCurrent,
     plTierTotal,
     plDamageFromEnergy,
     plDamageFromMelee,
     plDamageGeneric,
     plBuffer,
     plTierDesired,
     plTierChanged,
     plTierSelectionMode //0 means tier select, 1 means previous tier, 2 means next tier
 }powerLevel_t;
powerup_t
enum powerup_t
Enumerator
PW_NONE
PW_STATE
PW_SKILLS
PW_DRIFTING
PW_INVULNERABILITY
PW_KNOCKBACK_SPEED
PW_NUM_POWERUPS
Definition at line 349 of file bg_public.h.
              {
     PW_NONE,
     PW_STATE,
     PW_SKILLS,
     PW_DRIFTING,
     PW_INVULNERABILITY,
     PW_KNOCKBACK_SPEED,
     PW_NUM_POWERUPS,
 }powerup_t;
sequenceTimers_t
enum sequenceTimers_t
Enumerator
sqAttack
sqAltAttack
sqPowerLevel
sqBlock
sqWalk
sqBoost
sqLockon
sqJump
sqZanzoken
sqForward
sqLeft
sqRight
sqBack
sqUp
sqDown
sqRollRight
sqRollLeft
Definition at line 330 of file bg_public.h.
             {
     sqAttack,
     sqAltAttack,
     sqPowerLevel,
     sqBlock,
     sqWalk,
     sqBoost,
     sqLockon,
     sqJump,
     sqZanzoken,
     sqForward,
     sqLeft,
     sqRight,
     sqBack,
     sqUp,
     sqDown,
     sqRollRight,
     sqRollLeft
 }sequenceTimers_t;
statIndex_t
enum statIndex_t
Enumerator
stJumpTimed
stChargePercentPrimary
stChargePercentSecondary
stTransformState
stMeleeState
stAnimState
stSkills
stTransformFirstDuration
stTransformFirstEffectMaximum
stTransformFirstHealth
stTransformFirstFatigue
stTransformDuration
stTransformFatigue
stTransformHealth
stTransformEffectMaximum
Definition at line 217 of file bg_public.h.
              {
     stJumpTimed,
     stChargePercentPrimary,
     stChargePercentSecondary,
     stTransformState,
     stMeleeState,
     stAnimState,
     stSkills,
     stTransformFirstDuration,
     stTransformFirstEffectMaximum,
     stTransformFirstHealth,
     stTransformFirstFatigue,
     stTransformDuration,
     stTransformFatigue,
     stTransformHealth,
     stTransformEffectMaximum
 }statIndex_t;
team_t
enum team_t
Enumerator
TEAM_FREE
TEAM_RED
TEAM_BLUE
TEAM_SPECTATOR
TEAM_NUM_TEAMS
Definition at line 758 of file bg_public.h.
              {
     TEAM_FREE,
     TEAM_RED,
     TEAM_BLUE,
     TEAM_SPECTATOR,
     TEAM_NUM_TEAMS
 } team_t;
teamtask_t
enum teamtask_t
Enumerator
TEAMTASK_NONE
TEAMTASK_OFFENSE
TEAMTASK_DEFENSE
TEAMTASK_PATROL
TEAMTASK_FOLLOW
TEAMTASK_RETRIEVE
TEAMTASK_ESCORT
TEAMTASK_CAMP
Definition at line 772 of file bg_public.h.
              {
     TEAMTASK_NONE,
     TEAMTASK_OFFENSE,
     TEAMTASK_DEFENSE,
     TEAMTASK_PATROL,
     TEAMTASK_FOLLOW,
     TEAMTASK_RETRIEVE,
     TEAMTASK_ESCORT,
     TEAMTASK_CAMP
 } teamtask_t;
timers_t
enum timers_t
Enumerator
tmUpdateTier
tmUpdateMelee
tmTransform
tmKnockback
tmZanzoken
tmBoost
tmJump
tmBlink
tmAttackLife
tmAttack1
tmAttack2
tmMeleeBreaker
tmMeleeBreakerWait
tmMeleeCharge
tmMeleeSpeed
tmMeleeIdle
tmStruggleEnergy
tmStruggleBlock
tmPowerRaise
tmPowerAuto
tmBurning
tmRiding
tmImpede
tmCrash
tmFreeze
tmRecover
tmBlind
tmSoar
tmFall
tmSafe
tmOnGround
tmLockon
Definition at line 293 of file bg_public.h.
             {
     tmUpdateTier,
     tmUpdateMelee,
     tmTransform,
     tmKnockback,
     tmZanzoken,
     tmBoost,
     tmJump,
     tmBlink,
     tmAttackLife,
     tmAttack1,
     tmAttack2,
     tmMeleeBreaker,
     tmMeleeBreakerWait,
     tmMeleeCharge,
     tmMeleeSpeed,
     tmMeleeIdle,
     tmStruggleEnergy,
     tmStruggleBlock,
     tmPowerRaise,
     tmPowerAuto,
     tmBurning,
     tmRiding,
     tmImpede,
     tmCrash,
     tmFreeze,
     tmRecover,
     tmBlind,
     tmSoar,
     tmFall,
     tmSafe,
     tmOnGround,
     tmLockon
 }timers_t;
weapon_t
enum weapon_t
Enumerator
WP_NONE
WP_GAUNTLET
WP_MACHINEGUN
WP_SHOTGUN
WP_GRENADE_LAUNCHER
WP_ROCKET_LAUNCHER
WP_LIGHTNING
WP_RAILGUN
WP_PLASMAGUN
WP_BFG
WP_GRAPPLING_HOOK
WP_NUM_WEAPONS
Definition at line 489 of file bg_public.h.
              {
     WP_NONE,
     WP_GAUNTLET,
     WP_MACHINEGUN,
     WP_SHOTGUN,
     WP_GRENADE_LAUNCHER,
     WP_ROCKET_LAUNCHER,
     WP_LIGHTNING,
     WP_RAILGUN,
     WP_PLASMAGUN,
     WP_BFG,
     WP_GRAPPLING_HOOK,
     WP_NUM_WEAPONS
 } weapon_t;
weaponstate_t
enum weaponstate_t
Enumerator
WEAPON_READY
WEAPON_FIRING
WEAPON_GUIDING
WEAPON_CHARGING
WEAPON_ALTFIRING
WEAPON_ALTGUIDING
WEAPON_ALTCHARGING
WEAPON_COOLING
WEAPON_RAISING
WEAPON_DROPPING
Definition at line 147 of file bg_public.h.
              {
     WEAPON_READY,
     WEAPON_FIRING, // ZEQ2: Will be used for continuous fire, regular firing goes immediately to WEAPON_COOLING.
     WEAPON_GUIDING,
     WEAPON_CHARGING,
     WEAPON_ALTFIRING,
     WEAPON_ALTGUIDING,
     WEAPON_ALTCHARGING,
     // NOTE: Must make these last to preserve enumeration in client entityState;
     //       These are remapped onto WEAPON_READY for entityState.
     WEAPON_COOLING,
     WEAPON_RAISING,
     WEAPON_DROPPING
 } weaponstate_t;
Function Documentation
BG_AddPredictableEventToPlayerstate()
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t * ps)
Definition at line 320 of file bg_misc.c.
{
 #ifdef _DEBUG
     {
         char buf[256];
         trap_Cvar_VariableStringBuffer("showevents", buf, sizeof(buf));
         if ( atof(buf) != 0 ) {
 #ifdef GAME
             Com_Printf(" game event svt %5d -> %5d: num = %20s parm %d\n", ps->pmove_framecount/*ps->commandTime*/, ps->eventSequence, eventnames[newEvent], eventParm);
 #else
             Com_Printf("Cgame event svt %5d -> %5d: num = %20s parm %d\n", ps->pmove_framecount/*ps->commandTime*/, ps->eventSequence, eventnames[newEvent], eventParm);
 #endif
         }
     }
 #endif
     ps->events[ps->eventSequence & (MAX_PS_EVENTS-1)] = newEvent;
     ps->eventParms[ps->eventSequence & (MAX_PS_EVENTS-1)] = eventParm;
     ps->eventSequence++;
 }
References Com_Printf(), eventnames, MAX_PS_EVENTS, and trap_Cvar_VariableStringBuffer().
Referenced by BG_TouchJumpPad(), G_AddPredictableEvent(), and PM_AddEvent().
BG_EvaluateTrajectory()
void BG_EvaluateTrajectory (entityState_t * es, const trajectory_t * tr, int atTime, vec3_t result)
Definition at line 66 of file bg_misc.c.
{
     float           deltaTime;
     float           phase;
     float           v0;
     vec3_t          dir;
     switch( tr->trType ) {
     case TR_STATIONARY:
     case TR_INTERPOLATE:
         VectorCopy( tr->trBase, result );
         break;
     case TR_LINEAR:
     case TR_DRUNKEN:
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         VectorMA( tr->trBase, deltaTime, tr->trDelta, result );
         if ( tr->trType == TR_DRUNKEN ) { // trDuration is how much the missile will wobble
             vec3_t  axis[3];
             float   ph1, ph2;
             if ( VectorNormalize2( tr->trDelta, axis[0] ) == 0.0f ) {
                 VectorSet( axis[0], 0, 0, 1 );
             }
             MakeNormalVectors( tr->trDelta, axis[1], axis[2] );
             RotateAroundDirection( axis, deltaTime );
             ph1 = sin( deltaTime * M_PI * 2 );
             ph2 = (cos( deltaTime * M_PI * 2 ) - ph1) + cos( deltaTime * M_PI * 4 );
             VectorMA( result, tr->trDuration * ph1, axis[1], result );
             VectorMA( result, tr->trDuration * ph2, axis[2], result );
         }
         break;
     case TR_SINE:
         deltaTime = ( atTime - tr->trTime ) / (float) tr->trDuration;
         phase = sin( deltaTime * M_PI * 2 );
         VectorMA( tr->trBase, phase, tr->trDelta, result );
         break;
     case TR_LINEAR_STOP:
         if ( atTime > tr->trTime + tr->trDuration ) {
             atTime = tr->trTime + tr->trDuration;
         }
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         if ( deltaTime < 0 ) {
             deltaTime = 0;
         }
         VectorMA( tr->trBase, deltaTime, tr->trDelta, result );
         break;
     case TR_GRAVITY:
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         VectorMA( tr->trBase, deltaTime, tr->trDelta, result );
         result[2] -= 0.5 * DEFAULT_GRAVITY * deltaTime * deltaTime;     // FIXME: local gravity...
         break;
     case TR_ACCEL:
         deltaTime = ( atTime - tr->trTime ) * 0.001f;   // milliseconds to seconds
         /*
             NOTE:
             There's a problem with accelerated missiles being able to
             get a negative acceleration and thus 'boomeranging' backwards.
             We want to set a minimum velocity of 0 to prevent this.
             NOTE:
             trDuration = acceleration,
         */
         VectorCopy( tr->trDelta, dir );
         v0 = VectorNormalize( dir );
         phase = v0 + tr->trDuration * deltaTime;
         if ( phase < 0 ) {
             // We have to find the point in time at which the velocity
             // becomes zero. We solve 0 = v0 + a * t for t.
             deltaTime = -v0 / tr->trDuration;
             // Now we can use this time to get the missile's position
         }
             // the 0.5*a*t^2 part.
             phase = (tr->trDuration / 2.0f) * (deltaTime * deltaTime);
             VectorMA (tr->trBase, phase, dir, result);
             // The u*t part.
             VectorMA (result, deltaTime, tr->trDelta, result);
         break;
     case TR_ARCH:
         if (!es) {
             Com_Error( ERR_DROP, "BG_EvaluateTrajectory: NULL entityState: %i", tr->trTime );
         } else {
             deltaTime = 1.0f - ( ( atTime - tr->trTime ) / (float) tr->trDuration );
             BG_LerpQuadraticSpline( tr->trBase, es->angles2, tr->trDelta, deltaTime, result );
         }
         break;
     default:
         Com_Error( ERR_DROP, "BG_EvaluateTrajectory: unknown trType: %i", tr->trTime );
         break;
     }
 }
References BG_LerpQuadraticSpline(), Com_Error(), DEFAULT_GRAVITY, dir, ERR_DROP, M_PI, MakeNormalVectors(), RotateAroundDirection(), tr, TR_ACCEL, TR_ARCH, TR_DRUNKEN, TR_GRAVITY, TR_INTERPOLATE, TR_LINEAR, TR_LINEAR_STOP, TR_SINE, TR_STATIONARY, VectorCopy, VectorMA(), VectorNormalize(), VectorNormalize2(), and VectorSet.
Referenced by CG_AddFragment(), CG_AddMoveScaleFade(), CG_AdjustPositionForMover(), CG_CalcEntityLerpPositions(), CG_CheckEvents(), CG_ClipMoveToEntities(), CG_InterpolateEntityPosition(), CG_PlayerSplash(), CG_ResetPlayerEntity(), CG_TrailFunc_SpiralBeam_Helper(), Fire_UserWeapon(), G_ExplodeUserWeapon(), G_MoverTeam(), G_RunUserMissile(), and SetMoverState().
BG_EvaluateTrajectoryDelta()
void BG_EvaluateTrajectoryDelta (entityState_t * es, const trajectory_t * tr, int atTime, vec3_t result)
Definition at line 178 of file bg_misc.c.
{
     float   deltaTime;
     float   phase;
     vec3_t  dir;
     switch( tr->trType ) {
     case TR_STATIONARY:
     case TR_INTERPOLATE:
         VectorClear( result );
         break;
     case TR_LINEAR:
     case TR_DRUNKEN:
         VectorCopy( tr->trDelta, result );
         break;
     case TR_SINE:
         deltaTime = ( atTime - tr->trTime ) / (float) tr->trDuration;
         phase = cos( deltaTime * M_PI * 2 );    // derivative of sin = cos
         phase *= 0.5;
         VectorScale( tr->trDelta, phase, result );
         break;
     case TR_LINEAR_STOP:
         if ( atTime > tr->trTime + tr->trDuration ) {
             VectorClear( result );
             return;
         }
         VectorCopy( tr->trDelta, result );
         break;
     case TR_GRAVITY:
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         VectorCopy( tr->trDelta, result );
         result[2] -= DEFAULT_GRAVITY * deltaTime;       // FIXME: local gravity...
         break;
     case TR_ACCEL:
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         // Turn magnitude of acceleration into a vector
         VectorCopy(tr->trDelta, dir);
         phase = VectorNormalize (dir);
         phase = phase + tr->trDuration * deltaTime;
         if ( phase < 0 ) { // prevent 'negative' velocity, clamp it at zero.
             VectorSet( dir, 0, 0, 0);
         } else {
             VectorScale (dir, tr->trDuration, dir);
         }
         // u + t * a = v
         VectorMA (tr->trDelta, deltaTime, dir, result);
         break;
     case TR_ARCH:
         if (!es) {
             Com_Error( ERR_DROP, "BG_EvaluateTrajectory: NULL entityState: %i", tr->trTime );
         } else {
             deltaTime = 1.0f - ( ( atTime - tr->trTime ) / (float) tr->trDuration );
             BG_LerpQuadraticSplineDelta( tr->trBase, es->angles2, tr->trDelta, deltaTime, result );
             VectorNormalize( result );
             // Reverse the speed calculation we did in user_missile.c under HOM_ARCH
             VectorScale( result, 1000.0f * Distance( tr->trBase, tr->trDelta ) / (float) tr->trDuration, result );
         }
         break;
     default:
         Com_Error( ERR_DROP, "BG_EvaluateTrajectoryDelta: unknown trType: %i", tr->trTime );
         break;
     }
 }
References BG_LerpQuadraticSplineDelta(), Com_Error(), DEFAULT_GRAVITY, dir, Distance(), ERR_DROP, M_PI, tr, TR_ACCEL, TR_ARCH, TR_DRUNKEN, TR_GRAVITY, TR_INTERPOLATE, TR_LINEAR, TR_LINEAR_STOP, TR_SINE, TR_STATIONARY, VectorClear, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, and VectorSet.
Referenced by CG_BeamTableUpdate(), CG_Missile(), CG_ReflectVelocity(), CG_TrailFunc_FadeTail(), G_BounceUserMissile(), G_HoldUserMissile(), and G_ImpactUserWeapon().
BG_EvaluateWeaponChargeLevel()
float BG_EvaluateWeaponChargeLevel (charge_t * ch, int atTime)
BG_IntHiBits()
int BG_IntHiBits (const int i)
BG_IntLoBits()
int BG_IntLoBits (const int i)
BG_IntMergeBits()
int BG_IntMergeBits (const int hi, const int lo)
BG_PlayerStateToEntityState()
void BG_PlayerStateToEntityState (playerState_t * ps, entityState_t * s, qboolean snap)
Definition at line 383 of file bg_misc.c.
{
     int i;
     int time;
     time = ps->commandTime;
     if(ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPECTATOR){s->eType = ET_INVISIBLE;}
     else{s->eType = ET_PLAYER;}
     s->number = ps->clientNum;
     s->pos.trType = TR_INTERPOLATE;
     VectorCopy( ps->origin, s->pos.trBase );
     if(snap){
         SnapVector(s->pos.trBase);
     }
     VectorCopy(ps->velocity,s->pos.trDelta);
     s->pos.trTime = time;
     s->pos.trDuration = 50;
     s->apos.trType = TR_INTERPOLATE;
     if(ps->weaponstate != WEAPON_GUIDING && ps->weaponstate != WEAPON_ALTGUIDING && !(ps->bitFlags & isDead) && !(ps->bitFlags & isUnconcious) && !(ps->bitFlags & isCrashed) && !(ps->bitFlags & usingAlter)){
         VectorCopy(ps->viewangles,s->apos.trBase);
         if(snap){SnapVector(s->apos.trBase);}
     }
     s->angles2[YAW] = ps->movementDir;
     s->legsAnim = ps->legsAnim;
     s->torsoAnim = ps->torsoAnim;
     s->clientNum = ps->clientNum;
     s->eFlags = ps->eFlags;
     if(ps->externalEvent){
         s->event = ps->externalEvent;
         s->eventParm = ps->externalEventParm;
     }
     else if(ps->entityEventSequence < ps->eventSequence){
         int seq;
         if(ps->entityEventSequence < ps->eventSequence - MAX_PS_EVENTS){
             ps->entityEventSequence = ps->eventSequence - MAX_PS_EVENTS;
         }
         seq = ps->entityEventSequence & (MAX_PS_EVENTS-1);
         s->event = ps->events[seq] | ((ps->entityEventSequence & 3 ) << 8);
         s->eventParm = ps->eventParms[ seq ];
         ps->entityEventSequence++;
     }
     s->weapon = ps->weapon;
     s->weaponstate = ps->weaponstate;
     s->playerBitFlags = ps->bitFlags;
     s->attackPowerCurrent = ps->powerLevel[plHealth];
     s->attackPowerTotal = ps->powerLevel[plMaximum];
     s->charge1.chBase = ps->stats[stChargePercentPrimary];
     s->charge2.chBase = ps->stats[stChargePercentSecondary];
     s->groundEntityNum = ps->groundEntityNum;
     s->tier = ps->powerLevel[plTierCurrent];
     s->powerups = 0;
     for(i = 0;i < MAX_POWERUPS;i++){
         if ( ps->powerups[ i ] ) {
             s->powerups |= 1 << i;
         }
     }
     s->loopSound = ps->loopSound;
     s->generic1 = ps->generic1;
 }
References ET_INVISIBLE, ET_PLAYER, isCrashed, isDead, isUnconcious, MAX_POWERUPS, MAX_PS_EVENTS, plHealth, plMaximum, plTierCurrent, PM_INTERMISSION, PM_SPECTATOR, SnapVector, stChargePercentPrimary, stChargePercentSecondary, TR_INTERPOLATE, usingAlter, VectorCopy, WEAPON_ALTGUIDING, WEAPON_GUIDING, and YAW.
Referenced by CG_AddPacketEntities(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_TransitionSnapshot(), ClientEndFrame(), ClientSpawn(), ClientThink_real(), SendPendingPredictableEvents(), and TeleportPlayer().
BG_TouchJumpPad()
void BG_TouchJumpPad (playerState_t * ps, entityState_t * jumppad)
Definition at line 345 of file bg_misc.c.
{
     vec3_t  angles;
     float p;
     int effectNum;
     // spectators don't use jump pads
     if ( ps->pm_type != PM_NORMAL ) {
         return;
     }
     // if we didn't hit this same jumppad the previous frame
     // then don't play the event sound again if we are in a fat trigger
     if ( ps->jumppad_ent != jumppad->number ) {
         vectoangles( jumppad->origin2, angles);
         p = fabs( AngleNormalize180( angles[PITCH] ) );
         if( p < 45 ) {
             effectNum = 0;
         } else {
             effectNum = 1;
         }
         BG_AddPredictableEventToPlayerstate( EV_JUMP_PAD, effectNum, ps );
     }
     // remember hitting this jumppad this frame
     ps->jumppad_ent = jumppad->number;
     ps->jumppad_frame = ps->pmove_framecount;
     // give the player the velocity from the jumppad
     VectorCopy( jumppad->origin2, ps->velocity );
 }
References AngleNormalize180(), angles, BG_AddPredictableEventToPlayerstate(), EV_JUMP_PAD, PITCH, PM_NORMAL, vectoangles(), and VectorCopy.
Referenced by CG_TouchTriggerPrediction(), and trigger_push_touch().
PM_UpdateViewAngles()
void PM_UpdateViewAngles (playerState_t * ps, const usercmd_t * cmd)
Definition at line 3270 of file bg_pmove.c.
{
     short       temp;
     int         i;
     int         roll = 0;
     float       oldCmdAngle;
     vec3_t      offset_angles;
     vec4_t      quatOrient;
     vec4_t      quatRot;
     vec4_t      quatResult;
     vec3_t      new_angles;
     float       pitchNorm;
     if(ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPINTERMISSION) {
         return;
     }
     //Com_Printf("Testing : %f, %f, %f\n",SHORT2ANGLE(ps->delta_angles[0]),SHORT2ANGLE(ps->delta_angles[1]),SHORT2ANGLE(ps->delta_angles[2]));
     //VectorCopy(pml.gravityNormal,pml.up);
     //VectorSubtract(pm->ps->delta_angles,pml.gravityNormal,pm->ps->delta_angles);
     //VectorNormalize2(pm->ps->delta_angles,pml.gravityNormal);
     if(pm->ps->bitFlags & usingZanzoken || pm->ps->lockedTarget > 0){
         AngleVectors(pm->ps->viewangles,pml.forward,NULL,NULL);
     }
     /*AnglesToAxis( const vec3_t angles, vec3_t axis[3] );
     Com_Printf("View Angles : %f, %f, %f\n",pm->ps->viewangles[0],pm->ps->viewangles[1],pm->ps->viewangles[2]);
     for (i = 0; i < 3; i++) {
         ps->delta_angles[i] = ANGLE2SHORT(fixedAngles[i]) - cmd->angles[i];
     }*/
     if(pm->ps->options & pointGravity){
         VectorSubtract(pm->ps->origin,pml.gravityPoint,pml.gravityDirection);
         VectorNormalize2(pml.gravityDirection,pml.gravityNormal);
     }
     else{
         pml.gravityNormal[0] = 0;
         pml.gravityNormal[1] = 0;
         pml.gravityNormal[2] = 1;
     }
     VectorScale(pml.gravityNormal,pm->ps->gravity[2],pml.gravityDirection);
     if((pm->ps->lockedTarget > 0) && !(pm->ps->bitFlags & usingAlter) && *ps->lockedPosition){
         vec3_t dir;
         vec3_t angles;
         VectorSubtract(*(ps->lockedPosition),ps->origin,dir);
         vectoangles(dir,angles);
         for (i = 0; i < 3; i++) {
             ps->delta_angles[i] = ANGLE2SHORT(angles[i]) - cmd->angles[i];
         }
     }
     else if(pm->ps->bitFlags & usingFlight && (pm->ps->options & advancedFlight || pm->ps->bitFlags & usingSoar)){
         int base = pm->ps->bitFlags & usingSoar ? 50 : 28;
         if(cmd->buttons & BUTTON_ROLL_LEFT){
             roll -= base * (pml.msec / 200.0f);
         }
         if(cmd->buttons & BUTTON_ROLL_RIGHT) {
             roll += base * (pml.msec / 200.0f);
         }
         for (i=0; i<3; i++) {
             // Get the offsets for the angles
             oldCmdAngle = ps->viewangles[i] - SHORT2ANGLE(ps->delta_angles[i]);
             offset_angles[i] = AngleNormalize180(SHORT2ANGLE(cmd->angles[i]) - oldCmdAngle);
         }
         // Don't forget to add our customized roll function if
         // we're not guiding a weapon!
         if(!(pm->ps->bitFlags & isGuiding)){
             offset_angles[ROLL] = AngleNormalize180(offset_angles[ROLL] + roll);
         }
         // There's a drifting problem with the quaternions' rounding, so when we DON'T change
         // our viewangles at all, we don't run through the quaternions to prevent drifting.
         // (As a bonus; this also means we won't be doing needless matrix manipulations.)
         if(((offset_angles[0] == 0) && (offset_angles[1] == 0)) && (offset_angles[2] == 0)) {
             return;
         }
         AnglesToQuat(ps->viewangles, quatOrient);
         AnglesToQuat(offset_angles, quatRot);
         QuatMul(quatOrient, quatRot, quatResult);
         QuatToAngles(quatResult, new_angles);
         // Try and compensate for the drifting problem.
         new_angles[PITCH] += 0.05f;
         // HACK: Because an exact pitch of -90 degrees STILL causes trouble troughout the
         //       code due to 'bad mathematics', we give a slight nudge ifthis threatens
         //       to happen. 2 degrees is not really noticeable, and is big enough to
         //       compensate for round off errors leading to -90 degrees of pitch.
         // NOTE: For some reason the program 'auto-magically' prevents angles of 90 degree
         //       pitch, by forcing you into a bit more yaw. Strange...
         AngleNormalize180(new_angles[PITCH]);
         if((new_angles[PITCH] < -89.0f)&& (new_angles[PITCH] > -91.0f)) {
             if(ps->viewangles[PITCH] < new_angles[PITCH]){
                 new_angles[PITCH] += 2;
             } else{
                 new_angles[PITCH] -= 2;
             }
         }
         // Correct the 3 delta_angles;
         if(i == ROLL && ps->viewangles[i] != 0) {
             ps->viewangles[i] = 0;
             ps->delta_angles[i] = 0 - cmd->angles[i];
         }
         for (i=0; i<3; i++) {
             ps->viewangles[i] = AngleNormalize180(new_angles[i]);
             ps->delta_angles[i] = ANGLE2SHORT(ps->viewangles[i]) - cmd->angles[i];
         }
         return;
     }
     else{
         ps->viewangles[ROLL] = 0;
         ps->delta_angles[ROLL] = 0;
         offset_angles[ROLL]= 0;
     }
     // We've been flying and we've inverted our pitch to a good amount upside down.
     // Cheat the view, by adjusting the yaw to 'swing around' and adjusting the pitch to match.
     pitchNorm = AngleNormalize180(ps->viewangles[PITCH]);
     if(pitchNorm > 100){
         ps->delta_angles[YAW] += ANGLE2SHORT(180);
         ps->delta_angles[PITCH] -= ANGLE2SHORT(pitchNorm);
         ps->delta_angles[PITCH] += ANGLE2SHORT(180 - pitchNorm);
     }
     if(pitchNorm < -100){
         ps->delta_angles[YAW] += ANGLE2SHORT(180);
         ps->delta_angles[PITCH] -= ANGLE2SHORT(pitchNorm);
         ps->delta_angles[PITCH] += ANGLE2SHORT(-180 - pitchNorm);
     }
     for (i=0 ; i<3 ; i++) {
         temp = cmd->angles[i] + ps->delta_angles[i];
         if(i == PITCH){
             if(pm->ps->lockedTarget <= 0){
                 if(temp > 16000){
                     ps->delta_angles[i] = 16000 - cmd->angles[i];
                     temp = 16000;
                 } else if(temp < -16000){
                     ps->delta_angles[i] = -16000 - cmd->angles[i];
                     temp = -16000;
                 }
             }
         }
         ps->viewangles[i] = SHORT2ANGLE(temp);
     }
 }
References advancedFlight, ANGLE2SHORT, AngleNormalize180(), angles, AnglesToQuat(), AngleVectors(), BUTTON_ROLL_LEFT, BUTTON_ROLL_RIGHT, dir, pml_t::forward, pml_t::gravityDirection, pml_t::gravityNormal, pml_t::gravityPoint, isGuiding, pml_t::msec, NULL, PITCH, pm, PM_INTERMISSION, PM_SPINTERMISSION, pml, pointGravity, pmove_t::ps, QuatMul(), QuatToAngles(), ROLL, SHORT2ANGLE, usingAlter, usingFlight, usingSoar, usingZanzoken, vectoangles(), VectorNormalize2(), VectorScale, VectorSubtract, and YAW.
Referenced by CG_InterpolatePlayerState(), CG_PredictPlayerState(), and PmoveSingle().
Pmove()
void Pmove (pmove_t * pmove)
Definition at line 3524 of file bg_pmove.c.
{
     int finalTime;
     finalTime = pmove->cmd.serverTime;
     if(finalTime < pmove->ps->commandTime){return;}
     if(finalTime > pmove->ps->commandTime + 1000){
         pmove->ps->commandTime = finalTime - 1000;
     }
     pmove->ps->pmove_framecount = (pmove->ps->pmove_framecount+1) & ((1<<PS_PMOVEFRAMECOUNTBITS)-1);
     while(pmove->ps->commandTime != finalTime){
         int msec;
         msec = finalTime - pmove->ps->commandTime;
         if(pmove->pmove_fixed){
             if(msec > pmove->pmove_msec){
                 msec = pmove->pmove_msec;
             }
         }
         else if(msec > 66){
             msec = 66;
         }
         pmove->cmd.serverTime = pmove->ps->commandTime + msec;
         PmoveSingle(pmove);
     }
 }
References pmove_t::cmd, pmove_t::pmove_fixed, pmove_t::pmove_msec, PmoveSingle(), pmove_t::ps, and PS_PMOVEFRAMECOUNTBITS.
Referenced by CG_PredictPlayerState(), ClientThink_real(), and SpectatorThink().