ZEQ2-Lite: Source/Game/Game/g_syscalls.c File Reference
g_syscalls.c File Reference
#include "g_local.h"
Functions
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
static intptr_t (QDECL *syscall)(intptr_t arg
int PASSFLOAT (float x)
void trap_AdjustAreaPortalState (gentity_t *ent, qboolean open)
qboolean trap_AreasConnected (int area1, int area2)
int trap_Argc (void)
void trap_Argv (int n, char *buffer, int bufferLength)
void trap_Cvar_Register (vmCvar_t *cvar, const char *var_name, const char *value, int flags)
void trap_Cvar_Set (const char *var_name, const char *value)
void trap_Cvar_Update (vmCvar_t *cvar)
int trap_Cvar_VariableIntegerValue (const char *var_name)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
void trap_DebugPolygonDelete (int id)
void trap_DropClient (int clientNum, const char *reason)
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int *list, int maxcount)
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
qboolean trap_EntityContactCapsule (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
void trap_Error (const char *fmt)
void trap_FS_FCloseFile (fileHandle_t f)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
void trap_GetConfigstring (int num, char *buffer, int bufferSize)
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
void trap_GetServerinfo (char *buffer, int bufferSize)
void trap_GetUsercmd (int clientNum, usercmd_t *cmd)
void trap_GetUserinfo (int num, char *buffer, int bufferSize)
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
void trap_LinkEntity (gentity_t *ent)
void trap_LocateGameData (gentity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *clients, int sizeofGClient)
int trap_Milliseconds (void)
int trap_PointContents (const vec3_t point, int passEntityNum)
void trap_Printf (const char *fmt)
int trap_RealTime (qtime_t *qtime)
void trap_SendConsoleCommand (int exec_when, const char *text)
void trap_SendServerCommand (int clientNum, const char *text)
void trap_SetBrushModel (gentity_t *ent, const char *name)
void trap_SetConfigstring (int num, const char *string)
void trap_SetUserinfo (int num, const char *buffer)
void trap_SnapVector (float *v)
void trap_Trace (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
void trap_TraceCapsule (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
void trap_UnlinkEntity (gentity_t *ent)
Function Documentation
dllEntry()
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
Definition at line 33 of file g_syscalls.c.
{
     syscall = syscallptr;
 }
intptr_t()
static intptr_t (QDECL * syscall) static
PASSFLOAT()
int PASSFLOAT (float x)
Definition at line 37 of file g_syscalls.c.
{
     floatint_t fi;
     fi.f = x;
     return fi.i;
 }
References floatint_t::f, and floatint_t::i.
trap_AdjustAreaPortalState()
void trap_AdjustAreaPortalState (gentity_t * ent, qboolean open)
Definition at line 167 of file g_syscalls.c.
{
     syscall( G_ADJUST_AREA_PORTAL_STATE, ent, open );
 }
References G_ADJUST_AREA_PORTAL_STATE.
Referenced by Reached_BinaryMover(), and Use_BinaryMover().
trap_AreasConnected()
qboolean trap_AreasConnected (int area1, int area2)
Definition at line 171 of file g_syscalls.c.
{
     return syscall( G_AREAS_CONNECTED, area1, area2 );
 }
References G_AREAS_CONNECTED.
trap_Argc()
int trap_Argc (void)
Definition at line 56 of file g_syscalls.c.
{
     return syscall( G_ARGC );
 }
References G_ARGC.
trap_Argv()
void trap_Argv (int n, char * buffer, int bufferLength)
Definition at line 60 of file g_syscalls.c.
{
     syscall( G_ARGV, n, buffer, bufferLength );
 }
References G_ARGV.
trap_Cvar_Register()
void trap_Cvar_Register (vmCvar_t * cvar, const char * var_name, const char * value, int flags)
Definition at line 88 of file g_syscalls.c.
{
     syscall( G_CVAR_REGISTER, cvar, var_name, value, flags );
 }
References G_CVAR_REGISTER.
trap_Cvar_Set()
void trap_Cvar_Set (const char * var_name, const char * value)
Definition at line 96 of file g_syscalls.c.
{
     syscall( G_CVAR_SET, var_name, value );
 }
References G_CVAR_SET.
trap_Cvar_Update()
void trap_Cvar_Update (vmCvar_t * cvar)
Definition at line 92 of file g_syscalls.c.
{
     syscall( G_CVAR_UPDATE, cvar );
 }
References G_CVAR_UPDATE.
trap_Cvar_VariableIntegerValue()
int trap_Cvar_VariableIntegerValue (const char * var_name)
Definition at line 100 of file g_syscalls.c.
{
     return syscall( G_CVAR_VARIABLE_INTEGER_VALUE, var_name );
 }
References G_CVAR_VARIABLE_INTEGER_VALUE.
Referenced by G_InitGame(), G_RankGameOver(), PodiumPlacementThink(), and SpawnPodium().
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
Definition at line 104 of file g_syscalls.c.
{
     syscall( G_CVAR_VARIABLE_STRING_BUFFER, var_name, buffer, bufsize );
 }
References G_CVAR_VARIABLE_STRING_BUFFER.
trap_DebugPolygonCreate()
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
Definition at line 202 of file g_syscalls.c.
{
     return syscall( G_DEBUG_POLYGON_CREATE, color, numPoints, points );
 }
References G_DEBUG_POLYGON_CREATE.
Referenced by DebugLine().
trap_DebugPolygonDelete()
void trap_DebugPolygonDelete (int id)
Definition at line 206 of file g_syscalls.c.
{
     syscall( G_DEBUG_POLYGON_DELETE, id );
 }
References G_DEBUG_POLYGON_DELETE.
trap_DropClient()
void trap_DropClient (int clientNum, const char * reason)
Definition at line 114 of file g_syscalls.c.
{
     syscall( G_DROP_CLIENT, clientNum, reason );
 }
References G_DROP_CLIENT.
Referenced by ClientInactivityTimer().
trap_EntitiesInBox()
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int * list, int maxcount)
Definition at line 183 of file g_syscalls.c.
{
     return syscall( G_ENTITIES_IN_BOX, mins, maxs, list, maxcount );
 }
References G_ENTITIES_IN_BOX.
Referenced by G_MoverPush(), G_TouchTriggers(), G_UserRadiusDamage(), Missile_Smooth(), and SpotWouldTelefrag().
trap_EntityContact()
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
Definition at line 187 of file g_syscalls.c.
{
     return syscall( G_ENTITY_CONTACT, mins, maxs, ent );
 }
References G_ENTITY_CONTACT.
Referenced by G_TouchTriggers().
trap_EntityContactCapsule()
qboolean trap_EntityContactCapsule (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
Definition at line 191 of file g_syscalls.c.
{
     return syscall( G_ENTITY_CONTACTCAPSULE, mins, maxs, ent );
 }
References G_ENTITY_CONTACTCAPSULE.
trap_Error()
void trap_Error (const char * fmt)
Definition at line 47 of file g_syscalls.c.
 {
     syscall(G_ERROR, fmt);
     exit(1);
 }
References fmt, and G_ERROR.
trap_FS_FCloseFile()
void trap_FS_FCloseFile (fileHandle_t f)
Definition at line 76 of file g_syscalls.c.
{
     syscall( G_FS_FCLOSE_FILE, f );
 }
References G_FS_FCLOSE_FILE.
trap_FS_FOpenFile()
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
Definition at line 64 of file g_syscalls.c.
{
     return syscall( G_FS_FOPEN_FILE, qpath, f, mode );
 }
References G_FS_FOPEN_FILE.
trap_FS_GetFileList()
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
Definition at line 80 of file g_syscalls.c.
{
     return syscall( G_FS_GETFILELIST, path, extension, listbuf, bufsize );
 }
References G_FS_GETFILELIST.
trap_FS_Read()
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
Definition at line 68 of file g_syscalls.c.
{
     syscall( G_FS_READ, buffer, len, f );
 }
References G_FS_READ.
trap_FS_Write()
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
Definition at line 72 of file g_syscalls.c.
{
     syscall( G_FS_WRITE, buffer, len, f );
 }
References G_FS_WRITE.
trap_GetConfigstring()
void trap_GetConfigstring (int num, char * buffer, int bufferSize)
Definition at line 126 of file g_syscalls.c.
{
     syscall( G_GET_CONFIGSTRING, num, buffer, bufferSize );
 }
References G_GET_CONFIGSTRING.
Referenced by G_FindConfigstringIndex().
trap_GetEntityToken()
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
Definition at line 198 of file g_syscalls.c.
{
     return syscall( G_GET_ENTITY_TOKEN, buffer, bufferSize );
 }
References CG_GET_ENTITY_TOKEN, and G_GET_ENTITY_TOKEN.
Referenced by G_ParseSpawnVars().
trap_GetServerinfo()
void trap_GetServerinfo (char * buffer, int bufferSize)
Definition at line 138 of file g_syscalls.c.
{
     syscall( G_GET_SERVERINFO, buffer, bufferSize );
 }
References G_GET_SERVERINFO.
Referenced by G_InitGame().
trap_GetUsercmd()
void trap_GetUsercmd (int clientNum, usercmd_t * cmd)
Definition at line 194 of file g_syscalls.c.
{
     syscall( G_GET_USERCMD, clientNum, cmd );
 }
References G_GET_USERCMD.
Referenced by ClientSpawn(), and ClientThink().
trap_GetUserinfo()
void trap_GetUserinfo (int num, char * buffer, int bufferSize)
Definition at line 130 of file g_syscalls.c.
{
     syscall( G_GET_USERINFO, num, buffer, bufferSize );
 }
References G_GET_USERINFO.
Referenced by ClientConnect(), ClientSpawn(), ClientUserinfoChanged(), and Cmd_TeamTask_f().
trap_InPVS()
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
Definition at line 159 of file g_syscalls.c.
{
     return syscall( G_IN_PVS, p1, p2 );
 }
References G_IN_PVS, p1, and p2.
Referenced by Team_GetLocation().
trap_InPVSIgnorePortals()
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Definition at line 163 of file g_syscalls.c.
{
     return syscall( G_IN_PVS_IGNORE_PORTALS, p1, p2 );
 }
References G_IN_PVS_IGNORE_PORTALS, p1, and p2.
trap_LinkEntity()
void trap_LinkEntity (gentity_t * ent)
Definition at line 175 of file g_syscalls.c.
{
     syscall( G_LINKENTITY, ent );
 }
References G_LINKENTITY.
Referenced by ClientSpawn(), ClientThink_real(), G_ExplodeUserWeapon(), G_ImpactUserWeapon(), G_MoverPush(), G_MoverTeam(), G_RunUserMissile(), G_TempEntity(), G_TryPushingEntity(), G_TryPushingProxMine(), hurt_touch(), hurt_use(), InitMover(), SetMoverState(), SP_func_rotating(), SP_misc_model(), SP_misc_portal_camera(), SP_misc_portal_surface(), SP_target_speaker(), SP_trigger_multiple(), SP_trigger_push(), SP_trigger_teleport(), SpawnModelOnVictoryPad(), SpawnPlatTrigger(), SpawnPodium(), TeleportPlayer(), Think_SpawnNewDoorTrigger(), and UserHitscan_Fire().
trap_LocateGameData()
void trap_LocateGameData (gentity_t * gEnts, int numGEntities, int sizeofGEntity_t, playerState_t * clients, int sizeofGClient)
Definition at line 109 of file g_syscalls.c.
{
     syscall( G_LOCATE_GAME_DATA, gEnts, numGEntities, sizeofGEntity_t, clients, sizeofGClient );
 }
References G_LOCATE_GAME_DATA.
Referenced by G_InitGame(), and G_Spawn().
trap_Milliseconds()
int trap_Milliseconds (void)
Definition at line 53 of file g_syscalls.c.
{
     return syscall( G_MILLISECONDS );
 }
References G_MILLISECONDS.
trap_PointContents()
int trap_PointContents (const vec3_t point, int passEntityNum)
Definition at line 154 of file g_syscalls.c.
{
     return syscall( G_POINT_CONTENTS, point, passEntityNum );
 }
References G_POINT_CONTENTS.
Referenced by ClientThink_real(), and SpectatorThink().
trap_Printf()
void trap_Printf (const char * fmt)
Definition at line 43 of file g_syscalls.c.
{
     syscall( G_PRINT, fmt );
 }
References fmt, and G_PRINT.
Referenced by G_Printf().
trap_RealTime()
int trap_RealTime (qtime_t * qtime)
Definition at line 210 of file g_syscalls.c.
{
     return syscall( G_REAL_TIME, qtime );
 }
References G_REAL_TIME.
trap_SendConsoleCommand()
void trap_SendConsoleCommand (int exec_when, const char * text)
Definition at line 84 of file g_syscalls.c.
{
     syscall( G_SEND_CONSOLE_COMMAND, exec_when, text );
 }
References G_SEND_CONSOLE_COMMAND.
trap_SendServerCommand()
void trap_SendServerCommand (int clientNum, const char * text)
Definition at line 118 of file g_syscalls.c.
{
     syscall( G_SEND_SERVER_COMMAND, clientNum, text );
 }
References G_SEND_SERVER_COMMAND.
Referenced by __attribute__(), BroadcastTeamChange(), CheatsOk(), CheckTeamVote(), CheckVote(), ClientBegin(), ClientCommand(), ClientConnect(), ClientInactivityTimer(), ClientNumberFromString(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_LevelShot_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamVote_f(), Cmd_Vote_f(), Cmd_Where_f(), ConsoleCommand(), G_RadarUpdateCS(), G_RankRunFrame(), G_SayTo(), G_TeamCommand(), G_VoiceTo(), hurt_touch(), PrintTeam(), SetTeam(), TeamplayInfoMessage(), and Use_Target_Print().
trap_SetBrushModel()
void trap_SetBrushModel (gentity_t * ent, const char * name)
Definition at line 142 of file g_syscalls.c.
{
     syscall( G_SET_BRUSH_MODEL, ent, name );
 }
References G_SET_BRUSH_MODEL.
Referenced by InitTrigger(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_rotating(), SP_func_static(), and SP_func_train().
trap_SetConfigstring()
void trap_SetConfigstring (int num, const char * string)
Definition at line 122 of file g_syscalls.c.
{
     syscall( G_SET_CONFIGSTRING, num, string );
 }
References G_SET_CONFIGSTRING.
Referenced by CalculateRanks(), CheckTeamVote(), CheckTournament(), CheckVote(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_TeamVote_f(), Cmd_Vote_f(), G_FindConfigstringIndex(), G_UseTargets(), LogExit(), SP_worldspawn(), target_location_linkup(), and Team_SetFlagStatus().
trap_SetUserinfo()
void trap_SetUserinfo (int num, const char * buffer)
Definition at line 134 of file g_syscalls.c.
{
     syscall( G_SET_USERINFO, num, buffer );
 }
References G_SET_USERINFO.
Referenced by Cmd_TeamTask_f().
trap_SnapVector()
void trap_SnapVector (float * v)
Definition at line 214 of file g_syscalls.c.
{
     syscall( G_SNAPVECTOR, v );
     return;
 }
References CG_SNAPVECTOR, and G_SNAPVECTOR.
Referenced by PmoveSingle().
trap_Trace()
void trap_Trace (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
Definition at line 146 of file g_syscalls.c.
{
     syscall( G_TRACE, results, start, mins, maxs, end, passEntityNum, contentmask );
 }
References G_TRACE.
Referenced by CanDamage(), ClientThink_real(), Fire_UserWeapon(), G_CheckProxMinePosition(), G_RunUserMissile(), G_TestEntityPosition(), SpectatorThink(), Think_CylinderHoming(), Think_Homing(), and UserHitscan_Fire().
trap_TraceCapsule()
void trap_TraceCapsule (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
Definition at line 150 of file g_syscalls.c.
{
     syscall( G_TRACECAPSULE, results, start, mins, maxs, end, passEntityNum, contentmask );
 }
References G_TRACECAPSULE.
trap_UnlinkEntity()
void trap_UnlinkEntity (gentity_t * ent)
Definition at line 179 of file g_syscalls.c.
{
     syscall( G_UNLINKENTITY, ent );
 }
References G_UNLINKENTITY.
Referenced by BodySink(), ClientBegin(), ClientDisconnect(), G_FreeEntity(), G_MoverPush(), G_RunFrame(), hurt_use(), SpectatorThink(), target_laser_off(), and TeleportPlayer().