ZEQ2-Lite: Tools/MinGW/include/time.h File Reference
time.h File Reference
#include <_mingw.h>
#include <stddef.h>
Data Structures
struct tm
Macros
#define __need_NULL
#define __need_size_t
#define __need_wchar_t
#define _CLOCK_T_DEFINED
#define _daylight _daylight_dll
#define _TIME32_T_DEFINED
#define _TIME64_T_DEFINED
#define _TIME_T_DEFINED
#define _timezone _timezone_dll
#define _TM_DEFINED
#define _WTIME_DEFINED
#define CLK_TCK CLOCKS_PER_SEC
#define CLOCKS_PER_SEC ((clock_t)1000)
#define daylight _daylight
Typedefs
typedef __int32 __time32_t
typedef __int64 __time64_t
typedef long clock_t
typedef __time32_t time_t
Functions
_CRTIMP char *__cdecl __MINGW_NOTHROW _strdate (char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW _strtime (char *)
_CRTIMP void __cdecl __MINGW_NOTHROW _tzset (void)
_CRTIMP char *__cdecl __MINGW_NOTHROW asctime (const struct tm *)
_CRTIMP clock_t __cdecl __MINGW_NOTHROW clock (void)
_CRTIMP char *__cdecl __MINGW_NOTHROW ctime (const time_t *)
_CRTIMP double __cdecl __MINGW_NOTHROW difftime (time_t, time_t)
_CRTIMP struct tm *__cdecl __MINGW_NOTHROW gmtime (const time_t *)
_CRTIMP struct tm *__cdecl __MINGW_NOTHROW localtime (const time_t *)
_CRTIMP time_t __cdecl __MINGW_NOTHROW mktime (struct tm *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW strftime (char *, size_t, const char *, const struct tm *)
_CRTIMP time_t __cdecl __MINGW_NOTHROW time (time_t *)
_CRTIMP void __cdecl __MINGW_NOTHROW tzset (void)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsftime (wchar_t *, size_t, const wchar_t *, const struct tm *)
Variables
__MINGW_IMPORT int _daylight_dll
__MINGW_IMPORT long _timezone_dll
__MINGW_IMPORT char * _tzname [2]
__MINGW_IMPORT char * tzname [2]
Macro Definition Documentation
__need_NULL
#define __need_NULL
Definition at line 19 of file time.h.
__need_size_t
#define __need_size_t
Definition at line 18 of file time.h.
__need_wchar_t
#define __need_wchar_t
Definition at line 17 of file time.h.
_CLOCK_T_DEFINED
#define _CLOCK_T_DEFINED
Definition at line 72 of file time.h.
_daylight
#define _daylight _daylight_dll
Definition at line 212 of file time.h.
_TIME32_T_DEFINED
#define _TIME32_T_DEFINED
Definition at line 41 of file time.h.
_TIME64_T_DEFINED
#define _TIME64_T_DEFINED
Definition at line 48 of file time.h.
_TIME_T_DEFINED
#define _TIME_T_DEFINED
Definition at line 63 of file time.h.
_timezone
#define _timezone _timezone_dll
Definition at line 213 of file time.h.
_TM_DEFINED
#define _TM_DEFINED
Definition at line 93 of file time.h.
_WTIME_DEFINED
#define _WTIME_DEFINED
Definition at line 269 of file time.h.
CLK_TCK
#define CLK_TCK CLOCKS_PER_SEC
Definition at line 29 of file time.h.
CLOCKS_PER_SEC
#define CLOCKS_PER_SEC ((clock_t)1000)
Definition at line 28 of file time.h.
daylight
#define daylight _daylight
Definition at line 234 of file time.h.
Typedef Documentation
__time32_t
typedef __int32 __time32_t
Definition at line 40 of file time.h.
__time64_t
typedef __int64 __time64_t
Definition at line 47 of file time.h.
clock_t
typedef long clock_t
Definition at line 71 of file time.h.
time_t
typedef __time32_t time_t
Definition at line 61 of file time.h.
Function Documentation
_strdate()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strdate (char *)
_strtime()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strtime (char *)
_tzset()
_CRTIMP void __cdecl __MINGW_NOTHROW _tzset (void)
asctime()
_CRTIMP char* __cdecl __MINGW_NOTHROW asctime (const struct tm *)
Referenced by Com_Printf().
clock()
_CRTIMP clock_t __cdecl __MINGW_NOTHROW clock (void)
ctime()
_CRTIMP char* __cdecl __MINGW_NOTHROW ctime (const time_t *)
Referenced by emitheader(), main(), and progend().
difftime()
_CRTIMP double __cdecl __MINGW_NOTHROW difftime (time_t , time_t)
gmtime()
_CRTIMP struct tm* __cdecl __MINGW_NOTHROW gmtime (const time_t *)
localtime()
_CRTIMP struct tm* __cdecl __MINGW_NOTHROW localtime (const time_t *)
Referenced by Com_Printf(), and Com_RealTime().
mktime()
_CRTIMP time_t __cdecl __MINGW_NOTHROW mktime (struct tm *)
strftime()
_CRTIMP size_t __cdecl __MINGW_NOTHROW strftime (char * , size_t , const char * , const struct tm *)
time()
_CRTIMP time_t __cdecl __MINGW_NOTHROW time (time_t *)
Referenced by AddEarthquakeTremble(), AimAtTarget(), ArenaServers_DoRefresh(), BG_PlayerStateToEntityState(), CG_AddParticles(), CG_AddParticleToScene(), CG_AllocMark(), CG_GetMilliseconds(), CG_Particle_OilParticle(), CG_TrailFunc_SpiralBeam_Helper(), CL_DemoCompleted(), CL_GetFreePing(), CL_GetPing(), CL_KeyDownEvent(), CL_KeyEvent(), CL_KeyUpEvent(), CL_ParseBinding(), CL_ServerInfoPacket(), Com_InitRand(), Com_Printf(), Com_QueueEvent(), Com_RealTime(), Con_DrawNotify(), emitheader(), G_RankClientDisconnect(), G_RankRunFrame(), I_FloatTime(), main(), MatchTeam(), PM_CheckSequences(), PM_CheckSpecificSequences(), progend(), S_AddLoopSounds(), S_Base_StartSound(), SetMoverState(), UI_DrawPlayer(), and UI_PrintTime().
tzset()
_CRTIMP void __cdecl __MINGW_NOTHROW tzset (void)
wcsftime()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsftime (wchar_t * , size_t , const wchar_t * , const struct tm *)
Variable Documentation
_daylight_dll
__MINGW_IMPORT int _daylight_dll
Definition at line 208 of file time.h.
_timezone_dll
__MINGW_IMPORT long _timezone_dll
Definition at line 209 of file time.h.
_tzname
__MINGW_IMPORT char* _tzname[2]
Definition at line 210 of file time.h.
tzname
__MINGW_IMPORT char* tzname[2]
Definition at line 238 of file time.h.