ZEQ2-Lite: Source/Engine/jpeg-8c/jdatasrc.c File Reference
jdatasrc.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jerror.h"
Data Structures
struct my_source_mgr
Macros
#define INPUT_BUF_SIZE 4096 /* choose an efficiently fread'able size */
Typedefs
typedef my_source_mgr * my_src_ptr
Functions
fill_input_buffer (j_decompress_ptr cinfo)
fill_mem_input_buffer (j_decompress_ptr cinfo)
init_mem_source (j_decompress_ptr cinfo)
init_source (j_decompress_ptr cinfo)
jpeg_mem_src (j_decompress_ptr cinfo, unsigned char *inbuffer, unsigned long insize)
jpeg_stdio_src (j_decompress_ptr cinfo, FILE *infile)
skip_input_data (j_decompress_ptr cinfo, long num_bytes)
term_source (j_decompress_ptr cinfo)
Macro Definition Documentation
INPUT_BUF_SIZE
#define INPUT_BUF_SIZE 4096 /* choose an efficiently fread'able size */
Definition at line 36 of file jdatasrc.c.
Typedef Documentation
my_src_ptr
typedef my_source_mgr* my_src_ptr
Definition at line 34 of file jdatasrc.c.
Function Documentation
fill_input_buffer()
fill_input_buffer (j_decompress_ptr cinfo)
Definition at line 97 of file jdatasrc.c.
 {
   my_src_ptr src = (my_src_ptr) cinfo->src;
   size_t nbytes;
   nbytes = JFREAD(src->infile, src->buffer, INPUT_BUF_SIZE);
   if (nbytes <= 0) {
     if (src->start_of_file) /* Treat empty input file as fatal error */
       ERREXIT(cinfo, JERR_INPUT_EMPTY);
     WARNMS(cinfo, JWRN_JPEG_EOF);
     /* Insert a fake EOI marker */
     src->buffer[0] = (JOCTET) 0xFF;
     src->buffer[1] = (JOCTET) JPEG_EOI;
     nbytes = 2;
   }
   src->pub.next_input_byte = src->buffer;
   src->pub.bytes_in_buffer = nbytes;
   src->start_of_file = FALSE;
   return TRUE;
 }
References ERREXIT, FALSE, INPUT_BUF_SIZE, JFREAD, JPEG_EOI, TRUE, and WARNMS.
Referenced by jpeg_stdio_src().
fill_mem_input_buffer()
fill_mem_input_buffer (j_decompress_ptr cinfo)
Definition at line 122 of file jdatasrc.c.
 {
   static JOCTET mybuffer[4];
   /* The whole JPEG data is expected to reside in the supplied memory
    * buffer, so any request for more data beyond the given buffer size
    * is treated as an error.
    */
   WARNMS(cinfo, JWRN_JPEG_EOF);
   /* Insert a fake EOI marker */
   mybuffer[0] = (JOCTET) 0xFF;
   mybuffer[1] = (JOCTET) JPEG_EOI;
   cinfo->src->next_input_byte = mybuffer;
   cinfo->src->bytes_in_buffer = 2;
   return TRUE;
 }
References JPEG_EOI, TRUE, and WARNMS.
Referenced by jpeg_mem_src().
init_mem_source()
init_mem_source (j_decompress_ptr cinfo)
Definition at line 57 of file jdatasrc.c.
 {
   /* no work necessary here */
 }
Referenced by jpeg_mem_src().
init_source()
init_source (j_decompress_ptr cinfo)
Definition at line 45 of file jdatasrc.c.
 {
   my_src_ptr src = (my_src_ptr) cinfo->src;
   /* We reset the empty-input-file flag for each image,
    * but we don't clear the input buffer.
    * This is correct behavior for reading a series of images from one source.
    */
   src->start_of_file = TRUE;
 }
References my_source_mgr::start_of_file, and TRUE.
Referenced by jpeg_stdio_src().
jpeg_mem_src()
jpeg_mem_src (j_decompress_ptr cinfo, unsigned char * inbuffer, unsigned long insize)
Definition at line 248 of file jdatasrc.c.
 {
   struct jpeg_source_mgr * src;
   if (inbuffer == NULL || insize == 0)  /* Treat empty input as fatal error */
     ERREXIT(cinfo, JERR_INPUT_EMPTY);
   /* The source object is made permanent so that a series of JPEG images
    * can be read from the same buffer by calling jpeg_mem_src only before
    * the first one.
    */
   if (cinfo->src == NULL) { /* first time for this JPEG object? */
     cinfo->src = (struct jpeg_source_mgr *)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_PERMANENT,
                   SIZEOF(struct jpeg_source_mgr));
   }
   src = cinfo->src;
   src->init_source = init_mem_source;
   src->fill_input_buffer = fill_mem_input_buffer;
   src->skip_input_data = skip_input_data;
   src->resync_to_restart = jpeg_resync_to_restart; /* use default method */
   src->term_source = term_source;
   src->bytes_in_buffer = (size_t) insize;
   src->next_input_byte = (JOCTET *) inbuffer;
 }
References ERREXIT, fill_mem_input_buffer(), inbuffer, init_mem_source(), insize, jpeg_resync_to_restart(), JPOOL_PERMANENT, NULL, SIZEOF, skip_input_data(), and term_source().
Referenced by R_LoadJPG().
jpeg_stdio_src()
jpeg_stdio_src (j_decompress_ptr cinfo, FILE * infile)
Definition at line 209 of file jdatasrc.c.
 {
   my_src_ptr src;
   /* The source object and input buffer are made permanent so that a series
    * of JPEG images can be read from the same file by calling jpeg_stdio_src
    * only before the first one.  (If we discarded the buffer at the end of
    * one image, we'd likely lose the start of the next one.)
    * This makes it unsafe to use this manager and a different source
    * manager serially with the same JPEG object.  Caveat programmer.
    */
   if (cinfo->src == NULL) { /* first time for this JPEG object? */
     cinfo->src = (struct jpeg_source_mgr *)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_PERMANENT,
                   SIZEOF(my_source_mgr));
     src = (my_src_ptr) cinfo->src;
     src->buffer = (JOCTET *)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_PERMANENT,
                   INPUT_BUF_SIZE * SIZEOF(JOCTET));
   }
   src = (my_src_ptr) cinfo->src;
   src->pub.init_source = init_source;
   src->pub.fill_input_buffer = fill_input_buffer;
   src->pub.skip_input_data = skip_input_data;
   src->pub.resync_to_restart = jpeg_resync_to_restart; /* use default method */
   src->pub.term_source = term_source;
   src->infile = infile;
   src->pub.bytes_in_buffer = 0; /* forces fill_input_buffer on first read */
   src->pub.next_input_byte = NULL; /* until buffer loaded */
 }
References fill_input_buffer(), infile, init_source(), INPUT_BUF_SIZE, jpeg_resync_to_restart(), JPOOL_PERMANENT, NULL, SIZEOF, skip_input_data(), and term_source().
skip_input_data()
skip_input_data (j_decompress_ptr cinfo, long num_bytes)
Definition at line 155 of file jdatasrc.c.
 {
   struct jpeg_source_mgr * src = cinfo->src;
   /* Just a dumb implementation for now.  Could use fseek() except
    * it doesn't work on pipes.  Not clear that being smart is worth
    * any trouble anyway --- large skips are infrequent.
    */
   if (num_bytes > 0) {
     while (num_bytes > (long) src->bytes_in_buffer) {
       num_bytes -= (long) src->bytes_in_buffer;
       (void) (*src->fill_input_buffer) (cinfo);
       /* note we assume that fill_input_buffer will never return FALSE,
        * so suspension need not be handled.
        */
     }
     src->next_input_byte += (size_t) num_bytes;
     src->bytes_in_buffer -= (size_t) num_bytes;
   }
 }
References jpeg_source_mgr::bytes_in_buffer, and long().
Referenced by jpeg_mem_src(), and jpeg_stdio_src().
term_source()
term_source (j_decompress_ptr cinfo)
Definition at line 196 of file jdatasrc.c.
 {
   /* no work necessary here */
 }
Referenced by jpeg_mem_src(), and jpeg_stdio_src().