ZEQ2-Lite: GraphicsPath Class Reference
GraphicsPath Class Reference
#include <gdipluspath.h>
Public Member Functions
GraphicsPath (const Point *points, const BYTE *types, INT count, FillMode fillMode=FillModeAlternate)
GraphicsPath (const PointF *points, const BYTE *types, INT count, FillMode fillMode=FillModeAlternate)
GraphicsPath (FillMode fillMode=FillModeAlternate)
~GraphicsPath ()
Status AddArc (const Rect &rect, REAL startAngle, REAL sweepAngle)
Status AddArc (const RectF &rect, REAL startAngle, REAL sweepAngle)
Status AddArc (INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle)
Status AddArc (REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle)
Status AddBezier (const Point &pt1, const Point &pt2, const Point &pt3, const Point &pt4)
Status AddBezier (const PointF &pt1, const PointF &pt2, const PointF &pt3, const PointF &pt4)
Status AddBezier (INT x1, INT y1, INT x2, INT y2, INT x3, INT y3, INT x4, INT y4)
Status AddBezier (REAL x1, REAL y1, REAL x2, REAL y2, REAL x3, REAL y3, REAL x4, REAL y4)
Status AddBeziers (const Point *points, INT count)
Status AddBeziers (const PointF *points, INT count)
Status AddClosedCurve (const Point *points, INT count)
Status AddClosedCurve (const Point *points, INT count, REAL tension)
Status AddClosedCurve (const PointF *points, INT count)
Status AddClosedCurve (const PointF *points, INT count, REAL tension)
Status AddCurve (const Point *points, INT count)
Status AddCurve (const Point *points, INT count, INT offset, INT numberOfSegments, REAL tension)
Status AddCurve (const Point *points, INT count, REAL tension)
Status AddCurve (const PointF *points, INT count)
Status AddCurve (const PointF *points, INT count, INT offset, INT numberOfSegments, REAL tension)
Status AddCurve (const PointF *points, INT count, REAL tension)
Status AddEllipse (const Rect &rect)
Status AddEllipse (const RectF &rect)
Status AddEllipse (INT x, INT y, INT width, INT height)
Status AddEllipse (REAL x, REAL y, REAL width, REAL height)
Status AddLine (const Point &pt1, const Point &pt2)
Status AddLine (const PointF &pt1, const PointF &pt2)
Status AddLine (INT x1, INT y1, INT x2, INT y2)
Status AddLine (REAL x1, REAL y1, REAL x2, REAL y2)
Status AddLines (const Point *points, INT count)
Status AddLines (const PointF *points, INT count)
Status AddPath (const GraphicsPath *addingPath, BOOL connect)
Status AddPie (const Rect &rect, REAL startAngle, REAL sweepAngle)
Status AddPie (const RectF &rect, REAL startAngle, REAL sweepAngle)
Status AddPie (INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle)
Status AddPie (REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle)
Status AddPolygon (const Point *points, INT count)
Status AddPolygon (const PointF *points, INT count)
Status AddRectangle (const Rect &rect)
Status AddRectangle (const RectF &rect)
Status AddRectangles (const Rect *rects, INT count)
Status AddRectangles (const RectF *rects, INT count)
Status AddString (const WCHAR *string, INT length, const FontFamily *family, INT style, REAL emSize, const Point &origin, const StringFormat *format)
Status AddString (const WCHAR *string, INT length, const FontFamily *family, INT style, REAL emSize, const PointF &origin, const StringFormat *format)
Status AddString (const WCHAR *string, INT length, const FontFamily *family, INT style, REAL emSize, const Rect &layoutRect, const StringFormat *format)
Status AddString (const WCHAR *string, INT length, const FontFamily *family, INT style, REAL emSize, const RectF &layoutRect, const StringFormat *format)
Status ClearMarkers ()
GraphicsPath * Clone () const
Status CloseAllFigures ()
Status CloseFigure ()
Status Flatten (const Matrix *matrix=NULL, REAL flatness=FlatnessDefault)
Status GetBounds (Rect *bounds, const Matrix *matrix=NULL, const Pen *pen=NULL) const
Status GetBounds (RectF *bounds, const Matrix *matrix=NULL, const Pen *pen=NULL) const
FillMode GetFillMode () const
Status GetLastPoint (PointF *lastPoint) const
Status GetLastStatus () const
Status GetPathData (PathData *pathData) const
Status GetPathPoints (Point *points, INT count) const
Status GetPathPoints (PointF *points, INT count) const
Status GetPathTypes (BYTE *types, INT count) const
INT GetPointCount () const
BOOL IsOutlineVisible (const Point &point, const Pen *pen, const Graphics *g=NULL) const
BOOL IsOutlineVisible (const PointF &point, const Pen *pen, const Graphics *g=NULL) const
BOOL IsOutlineVisible (INT x, INT y, const Pen *pen, const Graphics *g=NULL) const
BOOL IsOutlineVisible (REAL x, REAL y, const Pen *pen, const Graphics *g=NULL) const
BOOL IsVisible (const Point &point, const Graphics *g=NULL) const
BOOL IsVisible (const PointF &point, const Graphics *g=NULL) const
BOOL IsVisible (INT x, INT y, const Graphics *g=NULL) const
BOOL IsVisible (REAL x, REAL y, const Graphics *g=NULL) const
Status Outline (const Matrix *matrix=NULL, REAL flatness=FlatnessDefault)
Status Reset ()
Status Reverse ()
Status SetFillMode (FillMode fillMode)
Status SetMarker ()
Status StartFigure ()
Status Transform (const Matrix *matrix)
Status Warp (const PointF *destPoints, INT count, const RectF &srcRect, const Matrix *matrix=NULL, WarpMode warpMode=WarpModePerspective, REAL flatness=FlatnessDefault)
Status Widen (const Pen *pen, const Matrix *matrix=NULL, REAL flatness=FlatnessDefault)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
GraphicsPath (const GraphicsPath &)
GraphicsPath (GpPath *path, Status status)
GraphicsPath & operator= (const GraphicsPath &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpPath * nativePath
Friends
class CustomLineCap
class Graphics
class GraphicsPathIterator
class PathGradientBrush
class Region
Detailed Description
Definition at line 36 of file gdipluspath.h.
Constructor & Destructor Documentation
GraphicsPath() [1/5]
GraphicsPath::GraphicsPath (FillMode fillMode = FillModeAlternate) inline
Definition at line 45 of file gdipluspath.h.
                                                        :
             nativePath(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreatePath(fillMode, &nativePath);
     }
References GdipCreatePath(), lastStatus, and nativePath.
Referenced by Clone().
GraphicsPath() [2/5]
GraphicsPath::GraphicsPath (const PointF * points, const BYTE * types, INT count, FillMode fillMode = FillModeAlternate) inline
Definition at line 50 of file gdipluspath.h.
                                                   :
             nativePath(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreatePath2(
                 points, types, count, fillMode, &nativePath);
     }
References GdipCreatePath2(), lastStatus, nativePath, and types.
GraphicsPath() [3/5]
GraphicsPath::GraphicsPath (const Point * points, const BYTE * types, INT count, FillMode fillMode = FillModeAlternate) inline
Definition at line 57 of file gdipluspath.h.
                                                   :
             nativePath(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreatePath2I(
                 points, types, count, fillMode, &nativePath);
     }
References GdipCreatePath2I(), lastStatus, nativePath, and types.
~GraphicsPath()
GraphicsPath::~GraphicsPath () inline
Definition at line 64 of file gdipluspath.h.
     {
         DllExports::GdipDeletePath(nativePath);
     }
References GdipDeletePath(), and nativePath.
GraphicsPath() [4/5]
GraphicsPath::GraphicsPath (GpPath * path, Status status) inline private
Definition at line 517 of file gdipluspath.h.
                                              :
         nativePath(path), lastStatus(status) {}
GraphicsPath() [5/5]
GraphicsPath::GraphicsPath (const GraphicsPath &) private
Member Function Documentation
AddArc() [1/4]
Status GraphicsPath::AddArc (const Rect & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 103 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathArcI(nativePath,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipAddPathArcI(), Rect::Height, nativePath, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
AddArc() [2/4]
Status GraphicsPath::AddArc (const RectF & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 97 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathArc(nativePath,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipAddPathArc(), RectF::Height, nativePath, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
AddArc() [3/4]
Status GraphicsPath::AddArc (INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle) inline
Definition at line 91 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathArcI(nativePath,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipAddPathArcI(), nativePath, and updateStatus().
AddArc() [4/4]
Status GraphicsPath::AddArc (REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle) inline
Definition at line 85 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathArc(nativePath,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipAddPathArc(), nativePath, and updateStatus().
AddBezier() [1/4]
Status GraphicsPath::AddBezier (const Point & pt1, const Point & pt2, const Point & pt3, const Point & pt4) inline
Definition at line 128 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathBezierI(nativePath,
                 pt1.X, pt1.Y, pt2.X, pt2.Y,
                 pt3.X, pt3.Y, pt4.X, pt4.Y));
     }
References GdipAddPathBezierI(), nativePath, updateStatus(), Point::X, and Point::Y.
AddBezier() [2/4]
Status GraphicsPath::AddBezier (const PointF & pt1, const PointF & pt2, const PointF & pt3, const PointF & pt4) inline
Definition at line 121 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathBezier(nativePath,
                 pt1.X, pt1.Y, pt2.X, pt2.Y,
                 pt3.X, pt3.Y, pt4.X, pt4.Y));
     }
References GdipAddPathBezier(), nativePath, updateStatus(), PointF::X, and PointF::Y.
AddBezier() [3/4]
Status GraphicsPath::AddBezier (INT x1, INT y1, INT x2, INT y2, INT x3, INT y3, INT x4, INT y4) inline
Definition at line 115 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathBezierI(nativePath,
                 x1, y1, x2, y2, x3, y3, x4, y4));
     }
References GdipAddPathBezierI(), nativePath, updateStatus(), and y1().
AddBezier() [4/4]
Status GraphicsPath::AddBezier (REAL x1, REAL y1, REAL x2, REAL y2, REAL x3, REAL y3, REAL x4, REAL y4) inline
Definition at line 109 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathBezier(nativePath,
                 x1, y1, x2, y2, x3, y3, x4, y4));
     }
References GdipAddPathBezier(), nativePath, updateStatus(), and y1().
AddBeziers() [1/2]
Status GraphicsPath::AddBeziers (const Point * points, INT count) inline
Definition at line 140 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathBeziersI(
                 nativePath, points, count));
     }
References GdipAddPathBeziersI(), nativePath, and updateStatus().
AddBeziers() [2/2]
Status GraphicsPath::AddBeziers (const PointF * points, INT count) inline
Definition at line 135 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathBeziers(
                 nativePath, points, count));
     }
References GdipAddPathBeziers(), nativePath, and updateStatus().
AddClosedCurve() [1/4]
Status GraphicsPath::AddClosedCurve (const Point * points, INT count) inline
Definition at line 150 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathClosedCurveI(
                 nativePath, points, count));
     }
References GdipAddPathClosedCurveI(), nativePath, and updateStatus().
AddClosedCurve() [2/4]
Status GraphicsPath::AddClosedCurve (const Point * points, INT count, REAL tension) inline
Definition at line 160 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathClosedCurve2I(
                 nativePath, points, count, tension));
     }
References GdipAddPathClosedCurve2I(), nativePath, and updateStatus().
AddClosedCurve() [3/4]
Status GraphicsPath::AddClosedCurve (const PointF * points, INT count) inline
Definition at line 145 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathClosedCurve(
                 nativePath, points, count));
     }
References GdipAddPathClosedCurve(), nativePath, and updateStatus().
AddClosedCurve() [4/4]
Status GraphicsPath::AddClosedCurve (const PointF * points, INT count, REAL tension) inline
Definition at line 155 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathClosedCurve2(
                 nativePath, points, count, tension));
     }
References GdipAddPathClosedCurve2(), nativePath, and updateStatus().
AddCurve() [1/6]
Status GraphicsPath::AddCurve (const Point * points, INT count) inline
Definition at line 170 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathCurveI(
                 nativePath, points, count));
     }
References GdipAddPathCurveI(), nativePath, and updateStatus().
AddCurve() [2/6]
Status GraphicsPath::AddCurve (const Point * points, INT count, INT offset, INT numberOfSegments, REAL tension) inline
Definition at line 192 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathCurve3I(
                 nativePath, points, count,
                 offset, numberOfSegments, tension));
     }
References GdipAddPathCurve3I(), nativePath, and updateStatus().
AddCurve() [3/6]
Status GraphicsPath::AddCurve (const Point * points, INT count, REAL tension) inline
Definition at line 180 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathCurve2I(
                 nativePath, points, count, tension));
     }
References GdipAddPathCurve2I(), nativePath, and updateStatus().
AddCurve() [4/6]
Status GraphicsPath::AddCurve (const PointF * points, INT count) inline
Definition at line 165 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathCurve(
                 nativePath, points, count));
     }
References GdipAddPathCurve(), nativePath, and updateStatus().
AddCurve() [5/6]
Status GraphicsPath::AddCurve (const PointF * points, INT count, INT offset, INT numberOfSegments, REAL tension) inline
Definition at line 185 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathCurve3(
                 nativePath, points, count,
                 offset, numberOfSegments, tension));
     }
References GdipAddPathCurve3(), nativePath, and updateStatus().
AddCurve() [6/6]
Status GraphicsPath::AddCurve (const PointF * points, INT count, REAL tension) inline
Definition at line 175 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathCurve2(
                 nativePath, points, count, tension));
     }
References GdipAddPathCurve2(), nativePath, and updateStatus().
AddEllipse() [1/4]
Status GraphicsPath::AddEllipse (const Rect & rect) inline
Definition at line 214 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathEllipseI(nativePath,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipAddPathEllipseI(), Rect::Height, nativePath, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
AddEllipse() [2/4]
Status GraphicsPath::AddEllipse (const RectF & rect) inline
Definition at line 209 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathEllipse(nativePath,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipAddPathEllipse(), RectF::Height, nativePath, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
AddEllipse() [3/4]
Status GraphicsPath::AddEllipse (INT x, INT y, INT width, INT height) inline
Definition at line 204 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathEllipseI(nativePath,
                 x, y, width, height));
     }
References GdipAddPathEllipseI(), nativePath, and updateStatus().
AddEllipse() [4/4]
Status GraphicsPath::AddEllipse (REAL x, REAL y, REAL width, REAL height) inline
Definition at line 199 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathEllipse(nativePath,
                 x, y, width, height));
     }
References GdipAddPathEllipse(), nativePath, and updateStatus().
AddLine() [1/4]
Status GraphicsPath::AddLine (const Point & pt1, const Point & pt2) inline
Definition at line 234 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathLineI(nativePath,
                 pt1.X, pt1.Y, pt2.X, pt2.Y));
     }
References GdipAddPathLineI(), nativePath, updateStatus(), Point::X, and Point::Y.
AddLine() [2/4]
Status GraphicsPath::AddLine (const PointF & pt1, const PointF & pt2) inline
Definition at line 229 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathLine(nativePath,
                 pt1.X, pt1.Y, pt2.X, pt2.Y));
     }
References GdipAddPathLine(), nativePath, updateStatus(), PointF::X, and PointF::Y.
AddLine() [3/4]
Status GraphicsPath::AddLine (INT x1, INT y1, INT x2, INT y2) inline
Definition at line 224 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathLineI(nativePath,
                 x1, y1, x2, y2));
     }
References GdipAddPathLineI(), nativePath, updateStatus(), and y1().
AddLine() [4/4]
Status GraphicsPath::AddLine (REAL x1, REAL y1, REAL x2, REAL y2) inline
Definition at line 219 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathLine(nativePath,
                 x1, y1, x2, y2));
     }
References GdipAddPathLine(), nativePath, updateStatus(), and y1().
AddLines() [1/2]
Status GraphicsPath::AddLines (const Point * points, INT count) inline
Definition at line 244 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathLine2I(nativePath,
                 points, count));
     }
References GdipAddPathLine2I(), nativePath, and updateStatus().
AddLines() [2/2]
Status GraphicsPath::AddLines (const PointF * points, INT count) inline
Definition at line 239 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathLine2(nativePath,
                 points, count));
     }
References GdipAddPathLine2(), nativePath, and updateStatus().
AddPath()
Status GraphicsPath::AddPath (const GraphicsPath * addingPath, BOOL connect) inline
Definition at line 249 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathPath(nativePath,
                 addingPath ? addingPath->nativePath : NULL,
                 connect));
     }
References connect(), GdipAddPathPath(), nativePath, NULL, and updateStatus().
AddPie() [1/4]
Status GraphicsPath::AddPie (const Rect & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 273 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathPieI(nativePath,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipAddPathPieI(), Rect::Height, nativePath, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
AddPie() [2/4]
Status GraphicsPath::AddPie (const RectF & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 267 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathPie(nativePath,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipAddPathPie(), RectF::Height, nativePath, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
AddPie() [3/4]
Status GraphicsPath::AddPie (INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle) inline
Definition at line 261 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathPieI(nativePath,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipAddPathPieI(), nativePath, and updateStatus().
AddPie() [4/4]
Status GraphicsPath::AddPie (REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle) inline
Definition at line 255 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathPie(nativePath,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipAddPathPie(), nativePath, and updateStatus().
AddPolygon() [1/2]
Status GraphicsPath::AddPolygon (const Point * points, INT count) inline
Definition at line 284 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathPolygonI(nativePath,
                 points, count));
     }
References GdipAddPathPolygonI(), nativePath, and updateStatus().
AddPolygon() [2/2]
Status GraphicsPath::AddPolygon (const PointF * points, INT count) inline
Definition at line 279 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathPolygon(nativePath,
                 points, count));
     }
References GdipAddPathPolygon(), nativePath, and updateStatus().
AddRectangle() [1/2]
Status GraphicsPath::AddRectangle (const Rect & rect) inline
Definition at line 294 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathRectangleI(
                 nativePath,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipAddPathRectangleI(), Rect::Height, nativePath, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
AddRectangle() [2/2]
Status GraphicsPath::AddRectangle (const RectF & rect) inline
Definition at line 289 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathRectangle(nativePath,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipAddPathRectangle(), RectF::Height, nativePath, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
AddRectangles() [1/2]
Status GraphicsPath::AddRectangles (const Rect * rects, INT count) inline
Definition at line 305 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathRectanglesI(
                 nativePath, rects, count));
     }
References GdipAddPathRectanglesI(), nativePath, and updateStatus().
AddRectangles() [2/2]
Status GraphicsPath::AddRectangles (const RectF * rects, INT count) inline
Definition at line 300 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathRectangles(
                 nativePath, rects, count));
     }
References GdipAddPathRectangles(), nativePath, and updateStatus().
AddString() [1/4]
Status GraphicsPath::AddString (const WCHAR * string, INT length, const FontFamily * family, INT style, REAL emSize, const Point & origin, const StringFormat * format) inline
Definition at line 321 of file gdipluspath.h.
     {
         Rect layoutRect(origin, Size(0, 0));
         return updateStatus(DllExports::GdipAddPathStringI(nativePath,
                 string, length,
                 family ? family->nativeFontFamily : NULL,
                 style, emSize, &layoutRect,
                 format ? format->nativeStringFormat : NULL));
     }
References GdipAddPathStringI(), FontFamily::nativeFontFamily, nativePath, NULL, and updateStatus().
AddString() [2/4]
Status GraphicsPath::AddString (const WCHAR * string, INT length, const FontFamily * family, INT style, REAL emSize, const PointF & origin, const StringFormat * format) inline
Definition at line 310 of file gdipluspath.h.
     {
         RectF layoutRect(origin, SizeF(0.0f, 0.0f));
         return updateStatus(DllExports::GdipAddPathString(nativePath,
                 string, length,
                 family ? family->nativeFontFamily : NULL,
                 style, emSize, &layoutRect,
                 format ? format->nativeStringFormat : NULL));
     }
References GdipAddPathString(), FontFamily::nativeFontFamily, nativePath, NULL, and updateStatus().
AddString() [3/4]
Status GraphicsPath::AddString (const WCHAR * string, INT length, const FontFamily * family, INT style, REAL emSize, const Rect & layoutRect, const StringFormat * format) inline
Definition at line 342 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathStringI(nativePath,
                 string, length,
                 family ? family->nativeFontFamily : NULL,
                 style, emSize, &layoutRect,
                 format ? format->nativeStringFormat : NULL));
     }
References GdipAddPathStringI(), FontFamily::nativeFontFamily, nativePath, NULL, and updateStatus().
AddString() [4/4]
Status GraphicsPath::AddString (const WCHAR * string, INT length, const FontFamily * family, INT style, REAL emSize, const RectF & layoutRect, const StringFormat * format) inline
Definition at line 332 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipAddPathString(nativePath,
                 string, length,
                 family ? family->nativeFontFamily : NULL,
                 style, emSize, &layoutRect,
                 format ? format->nativeStringFormat : NULL));
     }
References GdipAddPathString(), FontFamily::nativeFontFamily, nativePath, NULL, and updateStatus().
ClearMarkers()
Status GraphicsPath::ClearMarkers () inline
Definition at line 352 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipClearPathMarkers(
                 nativePath));
     }
References GdipClearPathMarkers(), nativePath, and updateStatus().
Clone()
GraphicsPath* GraphicsPath::Clone () const inline
Definition at line 68 of file gdipluspath.h.
     {
         GpPath *clonePath = NULL;
         Status status = updateStatus(DllExports::GdipClonePath(
                 nativePath, &clonePath));
         if (status == Ok) {
             GraphicsPath *result = new GraphicsPath(clonePath, lastStatus);
             if (!result) {
                 DllExports::GdipDeletePath(clonePath);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipClonePath(), GdipDeletePath(), GraphicsPath(), lastStatus, nativePath, NULL, Ok, OutOfMemory, and updateStatus().
CloseAllFigures()
Status GraphicsPath::CloseAllFigures () inline
Definition at line 357 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipClosePathFigures(
                 nativePath));
     }
References GdipClosePathFigures(), nativePath, and updateStatus().
CloseFigure()
Status GraphicsPath::CloseFigure () inline
Definition at line 362 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipClosePathFigure(
                 nativePath));
     }
References GdipClosePathFigure(), nativePath, and updateStatus().
Flatten()
Status GraphicsPath::Flatten (const Matrix * matrix = NULL, REAL flatness = FlatnessDefault) inline
Definition at line 367 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipFlattenPath(nativePath,
                 matrix ? matrix->nativeMatrix : NULL,
                 flatness));
     }
References GdipFlattenPath(), nativePath, NULL, and updateStatus().
GetBounds() [1/2]
Status GraphicsPath::GetBounds (Rect * bounds, const Matrix * matrix = NULL, const Pen * pen = NULL) const inline
Definition at line 382 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathWorldBoundsI(
                 nativePath, bounds,
                 matrix ? matrix->nativeMatrix : NULL,
                 pen ? pen->nativePen : NULL));
     }
References GdipGetPathWorldBoundsI(), nativePath, NULL, and updateStatus().
GetBounds() [2/2]
Status GraphicsPath::GetBounds (RectF * bounds, const Matrix * matrix = NULL, const Pen * pen = NULL) const inline
Definition at line 374 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathWorldBounds(
                 nativePath, bounds,
                 matrix ? matrix->nativeMatrix : NULL,
                 pen ? pen->nativePen : NULL));
     }
References GdipGetPathWorldBounds(), nativePath, NULL, and updateStatus().
GetFillMode()
FillMode GraphicsPath::GetFillMode () const inline
Definition at line 390 of file gdipluspath.h.
     {
         FillMode result = FillModeAlternate;
         updateStatus(DllExports::GdipGetPathFillMode(nativePath,
                 &result));
         return result;
     }
References FillModeAlternate, GdipGetPathFillMode(), nativePath, and updateStatus().
GetLastPoint()
Status GraphicsPath::GetLastPoint (PointF * lastPoint) const inline
Definition at line 397 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathLastPoint(
                 nativePath, lastPoint));
     }
References GdipGetPathLastPoint(), nativePath, and updateStatus().
GetLastStatus()
Status GraphicsPath::GetLastStatus () const inline
Definition at line 402 of file gdipluspath.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetPathData()
Status GraphicsPath::GetPathData (PathData * pathData) const inline
Definition at line 408 of file gdipluspath.h.
     {
         if (!pathData) return lastStatus = InvalidParameter;
         Status status;
         INT count;
         status = updateStatus(DllExports::GdipGetPointCount(
                 nativePath, &count));
         if (status != Ok) return status;
         status = updateStatus(pathData->AllocateArrays(count));
         if (status != Ok) return status;
         return updateStatus(DllExports::GdipGetPathData(
                 nativePath, (GpPathData*) pathData));
     }
References GdipGetPathData(), GdipGetPointCount(), InvalidParameter, lastStatus, nativePath, Ok, and updateStatus().
GetPathPoints() [1/2]
Status GraphicsPath::GetPathPoints (Point * points, INT count) const inline
Definition at line 430 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathPointsI(nativePath,
                 points, count));
     }
References GdipGetPathPointsI(), nativePath, and updateStatus().
GetPathPoints() [2/2]
Status GraphicsPath::GetPathPoints (PointF * points, INT count) const inline
Definition at line 425 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathPoints(nativePath,
                 points, count));
     }
References GdipGetPathPoints(), nativePath, and updateStatus().
GetPathTypes()
Status GraphicsPath::GetPathTypes (BYTE * types, INT count) const inline
Definition at line 435 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathTypes(nativePath,
                 types, count));
     }
References GdipGetPathTypes(), nativePath, types, and updateStatus().
GetPointCount()
INT GraphicsPath::GetPointCount () const inline
Definition at line 440 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetPointCount(nativePath,
                 &result));
         return result;
     }
References GdipGetPointCount(), nativePath, and updateStatus().
IsOutlineVisible() [1/4]
__inline__ BOOL GraphicsPath::IsOutlineVisible (const Point & point, const Pen * pen, const Graphics * g = NULL) const
Definition at line 1528 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsOutlineVisiblePathPointI(
             nativePath, point.X, point.Y,
             pen ? pen->nativePen : NULL,
             g ? g->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsOutlineVisiblePathPointI(), nativePath, Pen::nativePen, NULL, updateStatus(), Point::X, and Point::Y.
IsOutlineVisible() [2/4]
__inline__ BOOL GraphicsPath::IsOutlineVisible (const PointF & point, const Pen * pen, const Graphics * g = NULL) const
Definition at line 1517 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsOutlineVisiblePathPoint(
             nativePath, point.X, point.Y,
             pen ? pen->nativePen : NULL,
             g ? g->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsOutlineVisiblePathPoint(), nativePath, Pen::nativePen, NULL, updateStatus(), PointF::X, and PointF::Y.
IsOutlineVisible() [3/4]
__inline__ BOOL GraphicsPath::IsOutlineVisible (INT x, INT y, const Pen * pen, const Graphics * g = NULL) const
Definition at line 1507 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsOutlineVisiblePathPointI(
             nativePath, x, y, pen ? pen->nativePen : NULL,
             g ? g->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsOutlineVisiblePathPointI(), nativePath, Pen::nativePen, NULL, and updateStatus().
IsOutlineVisible() [4/4]
__inline__ BOOL GraphicsPath::IsOutlineVisible (REAL x, REAL y, const Pen * pen, const Graphics * g = NULL) const
Definition at line 1497 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsOutlineVisiblePathPoint(
             nativePath, x, y, pen ? pen->nativePen : NULL,
             g ? g->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsOutlineVisiblePathPoint(), nativePath, Pen::nativePen, NULL, and updateStatus().
IsVisible() [1/4]
__inline__ BOOL GraphicsPath::IsVisible (const Point & point, const Graphics * g = NULL) const
Definition at line 1566 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisiblePathPointI(
             nativePath, point.X, point.Y,
             g ? g->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisiblePathPointI(), nativePath, NULL, updateStatus(), Point::X, and Point::Y.
IsVisible() [2/4]
__inline__ BOOL GraphicsPath::IsVisible (const PointF & point, const Graphics * g = NULL) const
Definition at line 1556 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisiblePathPoint(
             nativePath, point.X, point.Y,
             g ? g->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisiblePathPoint(), nativePath, NULL, updateStatus(), PointF::X, and PointF::Y.
IsVisible() [3/4]
__inline__ BOOL GraphicsPath::IsVisible (INT x, INT y, const Graphics * g = NULL) const
Definition at line 1547 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisiblePathPointI(
             nativePath, x, y,
             g ? g->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisiblePathPointI(), nativePath, NULL, and updateStatus().
IsVisible() [4/4]
__inline__ BOOL GraphicsPath::IsVisible (REAL x, REAL y, const Graphics * g = NULL) const
Definition at line 1539 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisiblePathPoint(
             nativePath, x, y,
             g ? g->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisiblePathPoint(), nativePath, NULL, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
GraphicsPath& GraphicsPath::operator= (const GraphicsPath &) private
Outline()
Status GraphicsPath::Outline (const Matrix * matrix = NULL, REAL flatness = FlatnessDefault) inline
Definition at line 459 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipWindingModeOutline(
                 nativePath,
                 matrix ? matrix->nativeMatrix : NULL,
                 flatness));
     }
References GdipWindingModeOutline(), nativePath, NULL, and updateStatus().
Reset()
Status GraphicsPath::Reset () inline
Definition at line 467 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipResetPath(nativePath));
     }
References GdipResetPath(), nativePath, and updateStatus().
Reverse()
Status GraphicsPath::Reverse () inline
Definition at line 471 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipReversePath(nativePath));
     }
References GdipReversePath(), nativePath, and updateStatus().
SetFillMode()
Status GraphicsPath::SetFillMode (FillMode fillMode) inline
Definition at line 475 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathFillMode(
                 nativePath, fillMode));
     }
References GdipSetPathFillMode(), nativePath, and updateStatus().
SetMarker()
Status GraphicsPath::SetMarker () inline
Definition at line 480 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathMarker(nativePath));
     }
References GdipSetPathMarker(), nativePath, and updateStatus().
StartFigure()
Status GraphicsPath::StartFigure () inline
Definition at line 484 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipStartPathFigure(
                 nativePath));
     }
References GdipStartPathFigure(), nativePath, and updateStatus().
Transform()
Status GraphicsPath::Transform (const Matrix * matrix) inline
Definition at line 489 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipTransformPath(
                 nativePath,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipTransformPath(), nativePath, NULL, and updateStatus().
updateStatus()
Status GraphicsPath::updateStatus (Status newStatus) const inline private
Definition at line 522 of file gdipluspath.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by AddArc(), AddBezier(), AddBeziers(), AddClosedCurve(), AddCurve(), AddEllipse(), AddLine(), AddLines(), AddPath(), AddPie(), AddPolygon(), AddRectangle(), AddRectangles(), AddString(), ClearMarkers(), Clone(), CloseAllFigures(), CloseFigure(), Flatten(), GetBounds(), GetFillMode(), GetLastPoint(), GetPathData(), GetPathPoints(), GetPathTypes(), GetPointCount(), IsOutlineVisible(), IsVisible(), Outline(), Reset(), Reverse(), SetFillMode(), SetMarker(), StartFigure(), Transform(), Warp(), and Widen().
Warp()
Status GraphicsPath::Warp (const PointF * destPoints, INT count, const RectF & srcRect, const Matrix * matrix = NULL, WarpMode warpMode = WarpModePerspective, REAL flatness = FlatnessDefault) inline
Definition at line 495 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipWarpPath(nativePath,
                 matrix ? matrix->nativeMatrix : NULL,
                 destPoints, count,
                 srcRect.X, srcRect.Y,
                 srcRect.Width, srcRect.Height,
                 warpMode, flatness));
     }
References GdipWarpPath(), RectF::Height, nativePath, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
Widen()
Status GraphicsPath::Widen (const Pen * pen, const Matrix * matrix = NULL, REAL flatness = FlatnessDefault) inline
Definition at line 507 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipWidenPath(nativePath,
                 pen ? pen->nativePen : NULL,
                 matrix ? matrix->nativeMatrix : NULL,
                 flatness));
     }
References GdipWidenPath(), nativePath, Pen::nativePen, NULL, and updateStatus().
Friends And Related Function Documentation
CustomLineCap
friend class CustomLineCap friend
Definition at line 38 of file gdipluspath.h.
Graphics
friend class Graphics friend
Definition at line 39 of file gdipluspath.h.
GraphicsPathIterator
friend class GraphicsPathIterator friend
Definition at line 40 of file gdipluspath.h.
PathGradientBrush
friend class PathGradientBrush friend
Definition at line 41 of file gdipluspath.h.
Region
friend class Region friend
Definition at line 42 of file gdipluspath.h.
Field Documentation
lastStatus
Status GraphicsPath::lastStatus mutable private
Definition at line 529 of file gdipluspath.h.
Referenced by Clone(), GetLastStatus(), GetPathData(), GraphicsPath(), and updateStatus().
nativePath
GpPath* GraphicsPath::nativePath private
Definition at line 528 of file gdipluspath.h.
Referenced by AddArc(), AddBezier(), AddBeziers(), AddClosedCurve(), AddCurve(), AddEllipse(), AddLine(), AddLines(), AddPath(), AddPie(), AddPolygon(), AddRectangle(), AddRectangles(), AddString(), ClearMarkers(), Clone(), CloseAllFigures(), CloseFigure(), Region::Complement(), CustomLineCap::CustomLineCap(), Graphics::DrawPath(), Region::Exclude(), Graphics::FillPath(), Flatten(), GetBounds(), GetFillMode(), GetLastPoint(), GetPathData(), GetPathPoints(), GetPathTypes(), GetPointCount(), GraphicsPath(), GraphicsPathIterator::GraphicsPathIterator(), Region::Intersect(), IsOutlineVisible(), IsVisible(), GraphicsPathIterator::NextMarker(), GraphicsPathIterator::NextSubpath(), Outline(), PathGradientBrush::PathGradientBrush(), Region::Region(), Reset(), Reverse(), Graphics::SetClip(), SetFillMode(), SetMarker(), StartFigure(), Transform(), Region::Union(), Warp(), Widen(), Region::Xor(), and ~GraphicsPath().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdipluspath.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h