ZEQ2-Lite: Tools/MinGW/include/mlang.h File Reference
mlang.h File Reference
#include <windows.h>
Data Structures
struct tagDetectEncodingInfo
struct tagMIMECPINFO
struct tagMIMECSETINFO
struct tagRFC1766INFO
struct tagSCRIPTINFO
struct tagUNICODERANGE
Macros
#define INTERFACE IEnumCodePage
#define INTERFACE IEnumRfc1766
#define INTERFACE IEnumScript
#define INTERFACE IMLangCodePages
#define INTERFACE IMLangConvertCharset
#define INTERFACE IMLangFontLink
#define INTERFACE IMLangFontLink2
#define INTERFACE IMLangLineBreakConsole
#define INTERFACE IMultiLanguage
#define INTERFACE IMultiLanguage2
#define MAX_LOCALE_NAME 32
#define MAX_MIMECP_NAME 64
#define MAX_MIMECSET_NAME 50
#define MAX_MIMEFACE_NAME 32
#define MAX_RFC1766_NAME 6
#define MAX_SCRIPT_NAME 48
Typedefs
typedef struct DetectEncodingInfo * pDetectEncodingInfo
typedef struct MIMECPINFO * PMIMECPINFO
typedef struct MIMECSETINFO * PMIMECSETINFO
typedef struct RFC1766INFO * PRFC1766INFO
typedef struct SCRIPTINFO * PSCRIPTINFO
typedef BYTE SCRIPT_ID
typedef struct tagSCRIPTFONTINFO SCRIPTFONTINFO
Enumerations
enum tagMIMECONTF {
MIMECONTF_MAILNEWS = 0x00000001, MIMECONTF_BROWSER = 0x00000002, MIMECONTF_MINIMAL = 0x00000004, MIMECONTF_IMPORT = 0x00000008,
MIMECONTF_SAVABLE_MAILNEWS = 0x00000100, MIMECONTF_SAVABLE_BROWSER = 0x00000200, MIMECONTF_EXPORT = 0x00000400, MIMECONTF_PRIVCONVERTER = 0x00010000,
MIMECONTF_VALID = 0x00020000, MIMECONTF_VALID_NLS = 0x00040000, MIMECONTF_MIME_IE4 = 0x10000000, MIMECONTF_MIME_LATEST = 0x20000000,
MIMECONTF_MIME_REGISTRY = 0x40000000
}
enum tagMLCONVCHARF {
MLCONVCHARF_NONE = 0, MLCONVCHARF_AUTODETECT = 1, MLCONVCHARF_NCR_ENTITIZE = 2, MLCONVCHARF_NAME_ENTITIZE = 4,
MLCONVCHARF_USEDEFCHAR = 8, MLCONVCHARF_NOBESTFITCHARS = 16
}
enum tagMLCPF {
MLDETECTF_MAILNEWS = 0x0001, MLDETECTF_BROWSER = 0x0002, MLDETECTF_VALID = 0x0004, MLDETECTF_VALID_NLS = 0x0008,
MLDETECTF_PRESERVE_ORDER = 0x0010, MLDETECTF_PREFERRED_ONLY = 0x0020, MLDETECTF_FILTER_SPECIALCHAR = 0x0040
}
enum tagMLDETECTCP {
MLDETECTCP_NONE = 0, MLDETECTCP_7BIT = 1, MLDETECTCP_8BIT = 2, MLDETECTCP_DBCS = 4,
MLDETECTCP_HTML = 8
}
enum tagSCRIPTCONTF {
sidDefault, sidMerge, sidAsciiSym, sidAsciiLatin,
sidLatin, sidGreek, sidCyrillic, sidArmenian,
sidHebrew, sidArabic, sidDevanagari, sidBengali,
sidGurmukhi, sidGujarati, sidOriya, sidTamil,
sidTelugu, sidKannada, sidMalayalam, sidThai,
sidLao, sidTibetan, sidGeorgian, sidHangul,
sidKana, sidBopomofo, sidHan, sidEthiopic,
sidCanSyllabic, sidCherokee, sidYi, sidBraille,
sidRunic, sidOgham, sidSinhala, sidSyriac,
sidBurmese, sidKhmer, sidThaana, sidMongolian,
sidLim, sidFEFirst = sidHangul, sidFELast = sidHan
}
enum tagSCRIPTFONTCONTF {
SCRIPTCONTF_FIXED_FONT = 0x00000001, SCRIPTCONTF_PROPORTIONAL_FONT = 0x00000002, SCRIPTCONTF_SCRIPT_USER = 0x00010000, SCRIPTCONTF_SCRIPT_HIDE = 0x00020000,
SCRIPTCONTF_SCRIPT_SYSTEM = 0x00040000
}
Functions
DECLARE_INTERFACE_ (IEnumCodePage, IUnknown)
DECLARE_INTERFACE_ (IEnumRfc1766, IUnknown)
DECLARE_INTERFACE_ (IEnumScript, IUnknown)
DECLARE_INTERFACE_ (IMLangCodePages, IUnknown)
DECLARE_INTERFACE_ (IMLangConvertCharset, IUnknown)
DECLARE_INTERFACE_ (IMLangFontLink, IMLangCodePages)
DECLARE_INTERFACE_ (IMLangFontLink2, IMLangCodePages)
DECLARE_INTERFACE_ (IMLangLineBreakConsole, IMLangCodePages)
DECLARE_INTERFACE_ (IMultiLanguage, IUnknown)
DECLARE_INTERFACE_ (IMultiLanguage2, IUnknown)
Variables
const EXTERN_C CLSID CLSID_CMLangConvertCharset
const EXTERN_C CLSID CLSID_CMultiLanguage
const EXTERN_C IID IID_IEnumCodePage
const EXTERN_C IID IID_IEnumRfc1766
const EXTERN_C IID IID_IEnumScript
const EXTERN_C IID IID_IMLangCodePages
const EXTERN_C IID IID_IMLangConvertCharset
const EXTERN_C IID IID_IMLangFontLink
const EXTERN_C IID IID_IMLangFontLink2
const EXTERN_C IID IID_IMLangLineBreakConsole
const EXTERN_C IID IID_IMultiLanguage
const EXTERN_C IID IID_IMultiLanguage2
Macro Definition Documentation
INTERFACE [1/10]
#define INTERFACE IEnumCodePage
Definition at line 309 of file mlang.h.
INTERFACE [2/10]
#define INTERFACE IEnumRfc1766
Definition at line 309 of file mlang.h.
INTERFACE [3/10]
#define INTERFACE IEnumScript
Definition at line 309 of file mlang.h.
INTERFACE [4/10]
#define INTERFACE IMLangCodePages
Definition at line 309 of file mlang.h.
INTERFACE [5/10]
#define INTERFACE IMLangConvertCharset
Definition at line 309 of file mlang.h.
INTERFACE [6/10]
#define INTERFACE IMLangFontLink
Definition at line 309 of file mlang.h.
INTERFACE [7/10]
#define INTERFACE IMLangFontLink2
Definition at line 309 of file mlang.h.
INTERFACE [8/10]
#define INTERFACE IMLangLineBreakConsole
Definition at line 309 of file mlang.h.
INTERFACE [9/10]
#define INTERFACE IMultiLanguage
Definition at line 309 of file mlang.h.
INTERFACE [10/10]
#define INTERFACE IMultiLanguage2
Definition at line 309 of file mlang.h.
MAX_LOCALE_NAME
#define MAX_LOCALE_NAME 32
Definition at line 19 of file mlang.h.
MAX_MIMECP_NAME
#define MAX_MIMECP_NAME 64
Definition at line 14 of file mlang.h.
MAX_MIMECSET_NAME
#define MAX_MIMECSET_NAME 50
Definition at line 15 of file mlang.h.
MAX_MIMEFACE_NAME
#define MAX_MIMEFACE_NAME 32
Definition at line 17 of file mlang.h.
MAX_RFC1766_NAME
#define MAX_RFC1766_NAME 6
Definition at line 18 of file mlang.h.
MAX_SCRIPT_NAME
#define MAX_SCRIPT_NAME 48
Definition at line 16 of file mlang.h.
Typedef Documentation
pDetectEncodingInfo
typedef struct DetectEncodingInfo * pDetectEncodingInfo
PMIMECPINFO
typedef struct MIMECPINFO * PMIMECPINFO
PMIMECSETINFO
typedef struct MIMECSETINFO * PMIMECSETINFO
PRFC1766INFO
typedef struct RFC1766INFO * PRFC1766INFO
PSCRIPTINFO
typedef struct SCRIPTINFO * PSCRIPTINFO
SCRIPT_ID
typedef BYTE SCRIPT_ID
Definition at line 141 of file mlang.h.
SCRIPTFONTINFO
typedef struct tagSCRIPTFONTINFO SCRIPTFONTINFO
Definition at line 154 of file mlang.h.
Enumeration Type Documentation
tagMIMECONTF
enum tagMIMECONTF
Enumerator
MIMECONTF_MAILNEWS
MIMECONTF_BROWSER
MIMECONTF_MINIMAL
MIMECONTF_IMPORT
MIMECONTF_SAVABLE_MAILNEWS
MIMECONTF_SAVABLE_BROWSER
MIMECONTF_EXPORT
MIMECONTF_PRIVCONVERTER
MIMECONTF_VALID
MIMECONTF_VALID_NLS
MIMECONTF_MIME_IE4
MIMECONTF_MIME_LATEST
MIMECONTF_MIME_REGISTRY
Definition at line 21 of file mlang.h.
{
     MIMECONTF_MAILNEWS = 0x00000001,
     MIMECONTF_BROWSER = 0x00000002,
     MIMECONTF_MINIMAL = 0x00000004,
     MIMECONTF_IMPORT = 0x00000008,
     MIMECONTF_SAVABLE_MAILNEWS = 0x00000100,
     MIMECONTF_SAVABLE_BROWSER = 0x00000200,
     MIMECONTF_EXPORT = 0x00000400,
     MIMECONTF_PRIVCONVERTER = 0x00010000,
     MIMECONTF_VALID = 0x00020000,
     MIMECONTF_VALID_NLS = 0x00040000,
     MIMECONTF_MIME_IE4 = 0x10000000,
     MIMECONTF_MIME_LATEST = 0x20000000,
     MIMECONTF_MIME_REGISTRY = 0x40000000
 } MIMECONTF;
tagMLCONVCHARF
enum tagMLCONVCHARF
Enumerator
MLCONVCHARF_NONE
MLCONVCHARF_AUTODETECT
MLCONVCHARF_NCR_ENTITIZE
MLCONVCHARF_NAME_ENTITIZE
MLCONVCHARF_USEDEFCHAR
MLCONVCHARF_NOBESTFITCHARS
Definition at line 36 of file mlang.h.
{
     MLCONVCHARF_NONE = 0,
     MLCONVCHARF_AUTODETECT = 1,
     MLCONVCHARF_NCR_ENTITIZE = 2,
     MLCONVCHARF_NAME_ENTITIZE = 4,
     MLCONVCHARF_USEDEFCHAR = 8,
     MLCONVCHARF_NOBESTFITCHARS = 16
 } MLCONVCHAR;
tagMLCPF
enum tagMLCPF
Enumerator
MLDETECTF_MAILNEWS
MLDETECTF_BROWSER
MLDETECTF_VALID
MLDETECTF_VALID_NLS
MLDETECTF_PRESERVE_ORDER
MLDETECTF_PREFERRED_ONLY
MLDETECTF_FILTER_SPECIALCHAR
Definition at line 44 of file mlang.h.
                       {
     MLDETECTF_MAILNEWS = 0x0001,
     MLDETECTF_BROWSER = 0x0002,
     MLDETECTF_VALID = 0x0004,
     MLDETECTF_VALID_NLS = 0x0008,
     MLDETECTF_PRESERVE_ORDER = 0x0010,
     MLDETECTF_PREFERRED_ONLY = 0x0020,
     MLDETECTF_FILTER_SPECIALCHAR = 0x0040
 } MLCP;
tagMLDETECTCP
enum tagMLDETECTCP
Enumerator
MLDETECTCP_NONE
MLDETECTCP_7BIT
MLDETECTCP_8BIT
MLDETECTCP_DBCS
MLDETECTCP_HTML
Definition at line 53 of file mlang.h.
{
     MLDETECTCP_NONE = 0,
     MLDETECTCP_7BIT = 1,
     MLDETECTCP_8BIT = 2,
     MLDETECTCP_DBCS = 4,
     MLDETECTCP_HTML = 8
 } MLDETECTCP;
tagSCRIPTCONTF
enum tagSCRIPTCONTF
Enumerator
sidDefault
sidMerge
sidAsciiSym
sidAsciiLatin
sidLatin
sidGreek
sidCyrillic
sidArmenian
sidHebrew
sidArabic
sidDevanagari
sidBengali
sidGurmukhi
sidGujarati
sidOriya
sidTamil
sidTelugu
sidKannada
sidMalayalam
sidThai
sidLao
sidTibetan
sidGeorgian
sidHangul
sidKana
sidBopomofo
sidHan
sidEthiopic
sidCanSyllabic
sidCherokee
sidYi
sidBraille
sidRunic
sidOgham
sidSinhala
sidSyriac
sidBurmese
sidKhmer
sidThaana
sidMongolian
sidLim
sidFEFirst
sidFELast
Definition at line 67 of file mlang.h.
{
     sidDefault,
     sidMerge,
     sidAsciiSym,
     sidAsciiLatin,
     sidLatin,
     sidGreek,
     sidCyrillic,
     sidArmenian,
     sidHebrew,
     sidArabic,
     sidDevanagari,
     sidBengali,
     sidGurmukhi,
     sidGujarati,
     sidOriya,
     sidTamil,
     sidTelugu,
     sidKannada,
     sidMalayalam,
     sidThai,
     sidLao,
     sidTibetan,
     sidGeorgian,
     sidHangul,
     sidKana,
     sidBopomofo,
     sidHan,
     sidEthiopic,
     sidCanSyllabic,
     sidCherokee,
     sidYi,
     sidBraille,
     sidRunic,
     sidOgham,
     sidSinhala,
     sidSyriac,
     sidBurmese,
     sidKhmer,
     sidThaana,
     sidMongolian,
     sidLim,
     sidFEFirst = sidHangul,
     sidFELast = sidHan
 } SCRIPTCONTF;
tagSCRIPTFONTCONTF
enum tagSCRIPTFONTCONTF
Enumerator
SCRIPTCONTF_FIXED_FONT
SCRIPTCONTF_PROPORTIONAL_FONT
SCRIPTCONTF_SCRIPT_USER
SCRIPTCONTF_SCRIPT_HIDE
SCRIPTCONTF_SCRIPT_SYSTEM
Definition at line 60 of file mlang.h.
{
     SCRIPTCONTF_FIXED_FONT = 0x00000001,
     SCRIPTCONTF_PROPORTIONAL_FONT = 0x00000002,
     SCRIPTCONTF_SCRIPT_USER = 0x00010000,
     SCRIPTCONTF_SCRIPT_HIDE = 0x00020000,
     SCRIPTCONTF_SCRIPT_SYSTEM = 0x00040000
 } SCRIPTFONTCONTF;
Function Documentation
DECLARE_INTERFACE_() [1/10]
DECLARE_INTERFACE_ (IEnumCodePage , IUnknown)
Definition at line 158 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(Clone)(THIS_ IEnumCodePage**) PURE;
         STDMETHOD(Next)(THIS_ ULONG,PMIMECPINFO,ULONG*) PURE;
         STDMETHOD(Reset)(THIS) PURE;
         STDMETHOD(Skip)(THIS_ ULONG) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [2/10]
DECLARE_INTERFACE_ (IEnumRfc1766 , IUnknown)
Definition at line 172 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(Clone)(THIS_ IEnumRfc1766**) PURE;
         STDMETHOD(Next)(THIS_ ULONG,PRFC1766INFO,ULONG*) PURE;
         STDMETHOD(Reset)(THIS) PURE;
         STDMETHOD(Skip)(THIS_ ULONG) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [3/10]
DECLARE_INTERFACE_ (IEnumScript , IUnknown)
Definition at line 186 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(Clone)(THIS_ IEnumScript**) PURE;
         STDMETHOD(Next)(THIS_ ULONG,PSCRIPTINFO,ULONG*) PURE;
         STDMETHOD(Reset)(THIS) PURE;
         STDMETHOD(Skip)(THIS_ ULONG) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [4/10]
DECLARE_INTERFACE_ (IMLangCodePages , IUnknown)
Definition at line 200 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(GetCharCodePages)(THIS_ WCHAR,DWORD*) PURE;
         STDMETHOD(GetStrCodePages)(THIS_ const WCHAR *,long,DWORD,DWORD*,long*) PURE;
         STDMETHOD(CodePageToCodePages)(THIS_ UINT,DWORD*) PURE;
         STDMETHOD(CodePagesToCodePage)(THIS_ DWORD,UINT,UINT*) PURE;
 };
References long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [5/10]
DECLARE_INTERFACE_ (IMLangConvertCharset , IUnknown)
Definition at line 214 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(Initialize)(THIS_ UINT,UINT,DWORD) PURE;
         STDMETHOD(GetSourceCodePage)(THIS_ UINT*) PURE;
         STDMETHOD(GetDestinationCodePage)(THIS_ UINT*) PURE;
         STDMETHOD(GetProperty)(THIS_ DWORD*) PURE;
         STDMETHOD(DoConversion)(THIS_ BYTE*,UINT*,BYTE*,UINT*) PURE;
         STDMETHOD(DoConversionToUnicode)(THIS_ CHAR*,UINT*,WCHAR*,UINT*) PURE;
         STDMETHOD(DoConversionFromUnicode)(THIS_ WCHAR*,UINT*,CHAR*,UINT*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [6/10]
DECLARE_INTERFACE_ (IMLangFontLink , IMLangCodePages)
Definition at line 232 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(GetCharCodePages)(THIS_ WCHAR,DWORD*) PURE;
         STDMETHOD(GetStrCodePages)(THIS_ const WCHAR *,long,DWORD,DWORD*,long*) PURE;
         STDMETHOD(CodePageToCodePages)(THIS_ UINT,DWORD*) PURE;
         STDMETHOD(CodePagesToCodePage)(THIS_ DWORD,UINT,UINT*) PURE;
         STDMETHOD(GetFontCodePages)(THIS_ HDC,HFONT,DWORD*) PURE;
         STDMETHOD(MapFont)(THIS_ HDC,DWORD,HFONT,HFONT*) PURE;
         STDMETHOD(ReleaseFont)(THIS_ HFONT) PURE;
         STDMETHOD(ResetFontMapping)(THIS) PURE;
 };
References long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [7/10]
DECLARE_INTERFACE_ (IMLangFontLink2 , IMLangCodePages)
Definition at line 250 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(GetCharCodePages)(THIS_ WCHAR,DWORD*) PURE;
         STDMETHOD(GetStrCodePages)(THIS_ const WCHAR *,long,DWORD,DWORD*,long*) PURE;
         STDMETHOD(CodePageToCodePages)(THIS_ UINT,DWORD*) PURE;
         STDMETHOD(CodePagesToCodePage)(THIS_ DWORD,UINT,UINT*) PURE;
         STDMETHOD(GetFontCodePages)(THIS_ HDC,HFONT,DWORD*) PURE;
         STDMETHOD(ReleaseFont)(THIS_ HFONT) PURE;
         STDMETHOD(ResetFontMapping)(THIS) PURE;
         STDMETHOD(MapFont)(THIS_ HDC,DWORD,WCHAR,HFONT*) PURE;
         STDMETHOD(GetFontUnicodeRange)(THIS_ HDC,UINT*,UNICODERANGE*) PURE;
         STDMETHOD(GetScriptFontInfo)(THIS_ SCRIPT_ID,DWORD,UINT*,SCRIPTFONTINFO*) PURE;
         STDMETHOD(CodePageToScriptID)(THIS) PURE;
 };
References long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [8/10]
DECLARE_INTERFACE_ (IMLangLineBreakConsole , IMLangCodePages)
Definition at line 271 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(BreakLineML)(THIS) PURE;
         STDMETHOD(BreakLineW)(THIS_ LCID,const WCHAR*,long,long,long*,long*) PURE;
         STDMETHOD(BreakLineA)(THIS_ LCID,UINT,const CHAR*,long,long,long*,long*) PURE;
 };
References long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [9/10]
DECLARE_INTERFACE_ (IMultiLanguage , IUnknown)
Definition at line 284 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(GetNumberOfCodePageInfo)(THIS_ UINT*) PURE;
         STDMETHOD(GetCodePageInfo)(THIS_ UINT,PMIMECPINFO) PURE;
         STDMETHOD(GetFamilyCodePage)(THIS_ UINT,UINT*) PURE;
         STDMETHOD(EnumCodePages)(THIS_ DWORD,IEnumCodePage**) PURE;
         STDMETHOD(GetCharsetInfo)(THIS_ BSTR,PMIMECSETINFO) PURE;
         STDMETHOD(IsConvertible)(THIS_ DWORD,DWORD) PURE;
         STDMETHOD(ConvertString)(THIS_ DWORD*,DWORD,DWORD,BYTE*,UINT*,BYTE*,UINT*) PURE;
         STDMETHOD(ConvertStringToUnicode)(THIS_ DWORD*,DWORD,CHAR*,UINT*,WCHAR*,UINT*) PURE;
         STDMETHOD(ConvertStringFromUnicode)(THIS_ DWORD*,DWORD,WCHAR*,UINT*,CHAR*,UINT*) PURE;
         STDMETHOD(ConvertStringReset)(THIS) PURE;
         STDMETHOD(GetRfc1766FromLcid)(THIS_ LCID,BSTR*) PURE;
         STDMETHOD(GetLcidFromRfc1766)(THIS_ LCID*,BSTR) PURE;
         STDMETHOD(EnumRfc1766)(THIS_ IEnumRfc1766**) PURE;
         STDMETHOD(GetRfc1766Info)(THIS_ LCID,PRFC1766INFO) PURE;
         STDMETHOD(CreateConvertCharset)(THIS_ UINT,UINT,DWORD,IMLangConvertCharset**) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [10/10]
DECLARE_INTERFACE_ (IMultiLanguage2 , IUnknown)
Definition at line 310 of file mlang.h.
 {
         STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
         STDMETHOD_(ULONG,AddRef)(THIS) PURE;
         STDMETHOD_(ULONG,Release)(THIS) PURE;
         STDMETHOD(GetNumberOfCodePageInfo)(THIS_ UINT*) PURE;
         STDMETHOD(GetCodePageInfo)(THIS_ UINT,PMIMECPINFO) PURE;
         STDMETHOD(GetFamilyCodePage)(THIS_ UINT,UINT*) PURE;
         STDMETHOD(EnumCodePages)(THIS_ DWORD,IEnumCodePage**) PURE;
         STDMETHOD(GetCharsetInfo)(THIS_ BSTR,PMIMECSETINFO) PURE;
         STDMETHOD(IsConvertible)(THIS_ DWORD,DWORD) PURE;
         STDMETHOD(ConvertString)(THIS_ DWORD*,DWORD,DWORD,BYTE*,UINT*,BYTE*,UINT*) PURE;
         STDMETHOD(ConvertStringToUnicode)(THIS_ DWORD*,DWORD,CHAR*,UINT*,WCHAR*,UINT*) PURE;
         STDMETHOD(ConvertStringFromUnicode)(THIS_ DWORD*,DWORD,WCHAR*,UINT*,CHAR*,UINT*) PURE;
         STDMETHOD(ConvertStringReset)(THIS) PURE;
         STDMETHOD(GetRfc1766FromLcid)(THIS_ LCID,BSTR*) PURE;
         STDMETHOD(GetLcidFromRfc1766)(THIS_ LCID*,BSTR) PURE;
         STDMETHOD(EnumRfc1766)(THIS_ IEnumRfc1766**) PURE;
         STDMETHOD(GetRfc1766Info)(THIS_ LCID,PRFC1766INFO) PURE;
         STDMETHOD(CreateConvertCharset)(THIS_ UINT,UINT,DWORD,IMLangConvertCharset**) PURE;
         STDMETHOD(ConvertStringInIStream)(THIS_ DWORD*,DWORD,WCHAR*,DWORD,DWORD,IStream*,IStream*) PURE;
         STDMETHOD(ConvertStringToUnicodeEx)(THIS_ DWORD*,DWORD,CHAR*,UINT*,WCHAR*,UINT*,DWORD,WCHAR*) PURE;
         STDMETHOD(ConvertStringFromUnicodeEx)(THIS_ DWORD*,DWORD,WCHAR*,UINT*,CHAR*,UINT*,DWORD,WCHAR*) PURE;
         STDMETHOD(DetectCodepageInIStream)(THIS_ DWORD,DWORD,IStream*,DetectEncodingInfo*,INT*) PURE;
         STDMETHOD(DetectInputCodepage)(THIS_ DWORD,DWORD,CHAR*,INT*,DetectEncodingInfo*,INT*) PURE;
         STDMETHOD(ValidateCodePage)(THIS) PURE;
         STDMETHOD(GetCodePageDescription)(THIS_ UINT,LCID,LPWSTR,int) PURE;
         STDMETHOD(IsCodePageInstallable)(THIS) PURE;
         STDMETHOD(SetMimeDBSource)(THIS_ MIMECONTF) PURE;
         STDMETHOD(GetNumberOfScripts)(THIS_ UINT*) PURE;
         STDMETHOD(EnumScripts)(THIS_ DWORD,LANGID,IEnumScript**) PURE;
 };
References int, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
Variable Documentation
CLSID_CMLangConvertCharset
const EXTERN_C CLSID CLSID_CMLangConvertCharset
Definition at line 226 of file mlang.h.
CLSID_CMultiLanguage
const EXTERN_C CLSID CLSID_CMultiLanguage
Definition at line 304 of file mlang.h.
IID_IEnumCodePage
const EXTERN_C IID IID_IEnumCodePage
Definition at line 156 of file mlang.h.
IID_IEnumRfc1766
const EXTERN_C IID IID_IEnumRfc1766
Definition at line 167 of file mlang.h.
IID_IEnumScript
const EXTERN_C IID IID_IEnumScript
Definition at line 181 of file mlang.h.
IID_IMLangCodePages
const EXTERN_C IID IID_IMLangCodePages
Definition at line 195 of file mlang.h.
IID_IMLangConvertCharset
const EXTERN_C IID IID_IMLangConvertCharset
Definition at line 209 of file mlang.h.
IID_IMLangFontLink
const EXTERN_C IID IID_IMLangFontLink
Definition at line 230 of file mlang.h.
IID_IMLangFontLink2
const EXTERN_C IID IID_IMLangFontLink2
Definition at line 245 of file mlang.h.
IID_IMLangLineBreakConsole
const EXTERN_C IID IID_IMLangLineBreakConsole
Definition at line 266 of file mlang.h.
IID_IMultiLanguage
const EXTERN_C IID IID_IMultiLanguage
Definition at line 279 of file mlang.h.
IID_IMultiLanguage2
const EXTERN_C IID IID_IMultiLanguage2
Definition at line 308 of file mlang.h.