ZEQ2-Lite: Source/Game/Game/g_combat.c File Reference
g_combat.c File Reference
#include "g_local.h"
Functions
qboolean CanDamage (gentity_t *targ, vec3_t origin)
int RaySphereIntersections (vec3_t origin, float radius, vec3_t point, vec3_t dir, vec3_t intersections[2])
Function Documentation
CanDamage()
qboolean CanDamage (gentity_t * targ, vec3_t origin)
Definition at line 50 of file g_combat.c.
{
     vec3_t  dest;
     trace_t tr;
     vec3_t  midpoint;
     VectorAdd (targ->r.absmin, targ->r.absmax, midpoint);
     VectorScale (midpoint, 0.5, midpoint);
     VectorCopy (midpoint, dest);
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0 || tr.entityNum == targ->s.number)
         return qtrue;
     VectorCopy (midpoint, dest);
     dest[0] += 15.0;
     dest[1] += 15.0;
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy (midpoint, dest);
     dest[0] += 15.0;
     dest[1] -= 15.0;
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy (midpoint, dest);
     dest[0] -= 15.0;
     dest[1] += 15.0;
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy (midpoint, dest);
     dest[0] -= 15.0;
     dest[1] -= 15.0;
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     return qfalse;
 }
References ENTITYNUM_NONE, MASK_SOLID, qfalse, qtrue, tr, trap_Trace(), vec3_origin, VectorAdd, VectorCopy, and VectorScale.
Referenced by G_UserRadiusDamage().
RaySphereIntersections()
int RaySphereIntersections (vec3_t origin, float radius, vec3_t point, vec3_t dir, vec3_t intersections[2])
Definition at line 26 of file g_combat.c.
{
     float b, c, d, t;
     VectorNormalize(dir);
     b = 2 * (dir[0] * (point[0] - origin[0]) + dir[1] * (point[1] - origin[1]) + dir[2] * (point[2] - origin[2]));
     c = (point[0] - origin[0]) * (point[0] - origin[0]) +
         (point[1] - origin[1]) * (point[1] - origin[1]) +
         (point[2] - origin[2]) * (point[2] - origin[2]) -
         radius * radius;
     d = b * b - 4 * c;
     if (d > 0) {
         t = (- b + sqrt(d)) / 2;
         VectorMA(point, t, dir, intersections[0]);
         t = (- b - sqrt(d)) / 2;
         VectorMA(point, t, dir, intersections[1]);
         return 2;
     }
     else if (d == 0) {
         t = (- b ) / 2;
         VectorMA(point, t, dir, intersections[0]);
         return 1;
     }
     return 0;
 }
References dir, VectorMA(), and VectorNormalize().