ZEQ2-Lite: Source/Engine/jpeg-8c/jmemmgr.c File Reference
jmemmgr.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jmemsys.h"
Data Structures
struct jvirt_barray_ptr
struct jvirt_sarray_ptr
union large_pool_ptr
struct my_memory_mgr
union small_pool_ptr
Macros
#define ALIGN_TYPE double
#define AM_MEMORY_MANAGER /* we define jvirt_Xarray_control structs */
#define JPEG_INTERNALS
#define MIN_SLOP 50 /* greater than 0 to avoid futile looping */
Typedefs
typedef my_memory_mgr * my_mem_ptr
Functions
access_virt_barray (j_common_ptr cinfo, jvirt_barray_ptr ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable)
access_virt_sarray (j_common_ptr cinfo, jvirt_sarray_ptr ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable)
alloc_barray (j_common_ptr cinfo, int pool_id, JDIMENSION blocksperrow, JDIMENSION numrows)
alloc_large (j_common_ptr cinfo, int pool_id, size_t sizeofobject)
alloc_sarray (j_common_ptr cinfo, int pool_id, JDIMENSION samplesperrow, JDIMENSION numrows)
alloc_small (j_common_ptr cinfo, int pool_id, size_t sizeofobject)
do_barray_io (j_common_ptr cinfo, jvirt_barray_ptr ptr, boolean writing)
do_sarray_io (j_common_ptr cinfo, jvirt_sarray_ptr ptr, boolean writing)
free_pool (j_common_ptr cinfo, int pool_id)
jinit_memory_mgr (j_common_ptr cinfo)
out_of_memory (j_common_ptr cinfo, int which)
realize_virt_arrays (j_common_ptr cinfo)
request_virt_barray (j_common_ptr cinfo, int pool_id, boolean pre_zero, JDIMENSION blocksperrow, JDIMENSION numrows, JDIMENSION maxaccess)
request_virt_sarray (j_common_ptr cinfo, int pool_id, boolean pre_zero, JDIMENSION samplesperrow, JDIMENSION numrows, JDIMENSION maxaccess)
self_destruct (j_common_ptr cinfo)
Variables
static const size_t extra_pool_slop [JPOOL_NUMPOOLS]
static const size_t first_pool_slop [JPOOL_NUMPOOLS]
Macro Definition Documentation
ALIGN_TYPE
#define ALIGN_TYPE double
Definition at line 73 of file jmemmgr.c.
AM_MEMORY_MANAGER
#define AM_MEMORY_MANAGER /* we define jvirt_Xarray_control structs */
Definition at line 28 of file jmemmgr.c.
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 27 of file jmemmgr.c.
MIN_SLOP
#define MIN_SLOP 50 /* greater than 0 to avoid futile looping */
Definition at line 253 of file jmemmgr.c.
Typedef Documentation
my_mem_ptr
typedef my_memory_mgr* my_mem_ptr
Definition at line 140 of file jmemmgr.c.
Function Documentation
access_virt_barray()
access_virt_barray (j_common_ptr cinfo, jvirt_barray_ptr ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable)
Definition at line 841 of file jmemmgr.c.
 {
   JDIMENSION end_row = start_row + num_rows;
   JDIMENSION undef_row;
   /* debugging check */
   if (end_row > ptr->rows_in_array || num_rows > ptr->maxaccess ||
       ptr->mem_buffer == NULL)
     ERREXIT(cinfo, JERR_BAD_VIRTUAL_ACCESS);
   /* Make the desired part of the virtual array accessible */
   if (start_row < ptr->cur_start_row ||
       end_row > ptr->cur_start_row+ptr->rows_in_mem) {
     if (! ptr->b_s_open)
       ERREXIT(cinfo, JERR_VIRTUAL_BUG);
     /* Flush old buffer contents if necessary */
     if (ptr->dirty) {
       do_barray_io(cinfo, ptr, TRUE);
       ptr->dirty = FALSE;
     }
     /* Decide what part of virtual array to access.
      * Algorithm: if target address > current window, assume forward scan,
      * load starting at target address.  If target address < current window,
      * assume backward scan, load so that target area is top of window.
      * Note that when switching from forward write to forward read, will have
      * start_row = 0, so the limiting case applies and we load from 0 anyway.
      */
     if (start_row > ptr->cur_start_row) {
       ptr->cur_start_row = start_row;
     } else {
       /* use long arithmetic here to avoid overflow & unsigned problems */
       long ltemp;
       ltemp = (long) end_row - (long) ptr->rows_in_mem;
       if (ltemp < 0)
     ltemp = 0;      /* don't fall off front end of file */
       ptr->cur_start_row = (JDIMENSION) ltemp;
     }
     /* Read in the selected part of the array.
      * During the initial write pass, we will do no actual read
      * because the selected part is all undefined.
      */
     do_barray_io(cinfo, ptr, FALSE);
   }
   /* Ensure the accessed part of the array is defined; prezero if needed.
    * To improve locality of access, we only prezero the part of the array
    * that the caller is about to access, not the entire in-memory array.
    */
   if (ptr->first_undef_row < end_row) {
     if (ptr->first_undef_row < start_row) {
       if (writable)     /* writer skipped over a section of array */
     ERREXIT(cinfo, JERR_BAD_VIRTUAL_ACCESS);
       undef_row = start_row;    /* but reader is allowed to read ahead */
     } else {
       undef_row = ptr->first_undef_row;
     }
     if (writable)
       ptr->first_undef_row = end_row;
     if (ptr->pre_zero) {
       size_t bytesperrow = (size_t) ptr->blocksperrow * SIZEOF(JBLOCK);
       undef_row -= ptr->cur_start_row; /* make indexes relative to buffer */
       end_row -= ptr->cur_start_row;
       while (undef_row < end_row) {
     jzero_far((void FAR *) ptr->mem_buffer[undef_row], bytesperrow);
     undef_row++;
       }
     } else {
       if (! writable)       /* reader looking at undefined data */
     ERREXIT(cinfo, JERR_BAD_VIRTUAL_ACCESS);
     }
   }
   /* Flag the buffer dirty if caller will write in it */
   if (writable)
     ptr->dirty = TRUE;
   /* Return address of proper part of the buffer */
   return ptr->mem_buffer + (start_row - ptr->cur_start_row);
 }
References do_barray_io(), ERREXIT, FALSE, FAR, jzero_far(), long(), NULL, num_rows, ptr(), SIZEOF, and TRUE.
Referenced by jinit_memory_mgr().
access_virt_sarray()
access_virt_sarray (j_common_ptr cinfo, jvirt_sarray_ptr ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable)
Definition at line 756 of file jmemmgr.c.
 {
   JDIMENSION end_row = start_row + num_rows;
   JDIMENSION undef_row;
   /* debugging check */
   if (end_row > ptr->rows_in_array || num_rows > ptr->maxaccess ||
       ptr->mem_buffer == NULL)
     ERREXIT(cinfo, JERR_BAD_VIRTUAL_ACCESS);
   /* Make the desired part of the virtual array accessible */
   if (start_row < ptr->cur_start_row ||
       end_row > ptr->cur_start_row+ptr->rows_in_mem) {
     if (! ptr->b_s_open)
       ERREXIT(cinfo, JERR_VIRTUAL_BUG);
     /* Flush old buffer contents if necessary */
     if (ptr->dirty) {
       do_sarray_io(cinfo, ptr, TRUE);
       ptr->dirty = FALSE;
     }
     /* Decide what part of virtual array to access.
      * Algorithm: if target address > current window, assume forward scan,
      * load starting at target address.  If target address < current window,
      * assume backward scan, load so that target area is top of window.
      * Note that when switching from forward write to forward read, will have
      * start_row = 0, so the limiting case applies and we load from 0 anyway.
      */
     if (start_row > ptr->cur_start_row) {
       ptr->cur_start_row = start_row;
     } else {
       /* use long arithmetic here to avoid overflow & unsigned problems */
       long ltemp;
       ltemp = (long) end_row - (long) ptr->rows_in_mem;
       if (ltemp < 0)
     ltemp = 0;      /* don't fall off front end of file */
       ptr->cur_start_row = (JDIMENSION) ltemp;
     }
     /* Read in the selected part of the array.
      * During the initial write pass, we will do no actual read
      * because the selected part is all undefined.
      */
     do_sarray_io(cinfo, ptr, FALSE);
   }
   /* Ensure the accessed part of the array is defined; prezero if needed.
    * To improve locality of access, we only prezero the part of the array
    * that the caller is about to access, not the entire in-memory array.
    */
   if (ptr->first_undef_row < end_row) {
     if (ptr->first_undef_row < start_row) {
       if (writable)     /* writer skipped over a section of array */
     ERREXIT(cinfo, JERR_BAD_VIRTUAL_ACCESS);
       undef_row = start_row;    /* but reader is allowed to read ahead */
     } else {
       undef_row = ptr->first_undef_row;
     }
     if (writable)
       ptr->first_undef_row = end_row;
     if (ptr->pre_zero) {
       size_t bytesperrow = (size_t) ptr->samplesperrow * SIZEOF(JSAMPLE);
       undef_row -= ptr->cur_start_row; /* make indexes relative to buffer */
       end_row -= ptr->cur_start_row;
       while (undef_row < end_row) {
     jzero_far((void FAR *) ptr->mem_buffer[undef_row], bytesperrow);
     undef_row++;
       }
     } else {
       if (! writable)       /* reader looking at undefined data */
     ERREXIT(cinfo, JERR_BAD_VIRTUAL_ACCESS);
     }
   }
   /* Flag the buffer dirty if caller will write in it */
   if (writable)
     ptr->dirty = TRUE;
   /* Return address of proper part of the buffer */
   return ptr->mem_buffer + (start_row - ptr->cur_start_row);
 }
References do_sarray_io(), ERREXIT, FALSE, FAR, jzero_far(), long(), NULL, num_rows, ptr(), SIZEOF, and TRUE.
Referenced by jinit_memory_mgr().
alloc_barray()
alloc_barray (j_common_ptr cinfo, int pool_id, JDIMENSION blocksperrow, JDIMENSION numrows)
Definition at line 443 of file jmemmgr.c.
 {
   my_mem_ptr mem = (my_mem_ptr) cinfo->mem;
   JBLOCKARRAY result;
   JBLOCKROW workspace;
   JDIMENSION rowsperchunk, currow, i;
   long ltemp;
   /* Calculate max # of rows allowed in one allocation chunk */
   ltemp = (MAX_ALLOC_CHUNK-SIZEOF(large_pool_hdr)) /
       ((long) blocksperrow * SIZEOF(JBLOCK));
   if (ltemp <= 0)
     ERREXIT(cinfo, JERR_WIDTH_OVERFLOW);
   if (ltemp < (long) numrows)
     rowsperchunk = (JDIMENSION) ltemp;
   else
     rowsperchunk = numrows;
   mem->last_rowsperchunk = rowsperchunk;
   /* Get space for row pointers (small object) */
   result = (JBLOCKARRAY) alloc_small(cinfo, pool_id,
                      (size_t) (numrows * SIZEOF(JBLOCKROW)));
   /* Get the rows themselves (large objects) */
   currow = 0;
   while (currow < numrows) {
     rowsperchunk = MIN(rowsperchunk, numrows - currow);
     workspace = (JBLOCKROW) alloc_large(cinfo, pool_id,
     (size_t) ((size_t) rowsperchunk * (size_t) blocksperrow
           * SIZEOF(JBLOCK)));
     for (i = rowsperchunk; i > 0; i--) {
       result[currow++] = workspace;
       workspace += blocksperrow;
     }
   }
   return result;
 }
References alloc_large(), alloc_small(), ERREXIT, my_memory_mgr::last_rowsperchunk, MAX_ALLOC_CHUNK, MIN, and SIZEOF.
Referenced by jinit_memory_mgr(), and realize_virt_arrays().
alloc_large()
alloc_large (j_common_ptr cinfo, int pool_id, size_t sizeofobject)
Definition at line 342 of file jmemmgr.c.
 {
   my_mem_ptr mem = (my_mem_ptr) cinfo->mem;
   large_pool_ptr hdr_ptr;
   size_t odd_bytes;
   /* Check for unsatisfiable request (do now to ensure no overflow below) */
   if (sizeofobject > (size_t) (MAX_ALLOC_CHUNK-SIZEOF(large_pool_hdr)))
     out_of_memory(cinfo, 3);    /* request exceeds malloc's ability */
   /* Round up the requested size to a multiple of SIZEOF(ALIGN_TYPE) */
   odd_bytes = sizeofobject % SIZEOF(ALIGN_TYPE);
   if (odd_bytes > 0)
     sizeofobject += SIZEOF(ALIGN_TYPE) - odd_bytes;
   /* Always make a new pool */
   if (pool_id < 0 || pool_id >= JPOOL_NUMPOOLS)
     ERREXIT1(cinfo, JERR_BAD_POOL_ID, pool_id); /* safety check */
   hdr_ptr = (large_pool_ptr) jpeg_get_large(cinfo, sizeofobject +
                         SIZEOF(large_pool_hdr));
   if (hdr_ptr == NULL)
     out_of_memory(cinfo, 4);    /* jpeg_get_large failed */
   mem->total_space_allocated += sizeofobject + SIZEOF(large_pool_hdr);
   /* Success, initialize the new pool header and add to list */
   hdr_ptr->hdr.next = mem->large_list[pool_id];
   /* We maintain space counts in each pool header for statistical purposes,
    * even though they are not needed for allocation.
    */
   hdr_ptr->hdr.bytes_used = sizeofobject;
   hdr_ptr->hdr.bytes_left = 0;
   mem->large_list[pool_id] = hdr_ptr;
   return (void FAR *) (hdr_ptr + 1); /* point to first data byte in pool */
 }
References ALIGN_TYPE, ERREXIT1, FAR, jpeg_get_large(), JPOOL_NUMPOOLS, my_memory_mgr::large_list, MAX_ALLOC_CHUNK, NULL, out_of_memory(), SIZEOF, sizeofobject, and my_memory_mgr::total_space_allocated.
Referenced by alloc_barray(), alloc_sarray(), and jinit_memory_mgr().
alloc_sarray()
alloc_sarray (j_common_ptr cinfo, int pool_id, JDIMENSION samplesperrow, JDIMENSION numrows)
Definition at line 395 of file jmemmgr.c.
 {
   my_mem_ptr mem = (my_mem_ptr) cinfo->mem;
   JSAMPARRAY result;
   JSAMPROW workspace;
   JDIMENSION rowsperchunk, currow, i;
   long ltemp;
   /* Calculate max # of rows allowed in one allocation chunk */
   ltemp = (MAX_ALLOC_CHUNK-SIZEOF(large_pool_hdr)) /
       ((long) samplesperrow * SIZEOF(JSAMPLE));
   if (ltemp <= 0)
     ERREXIT(cinfo, JERR_WIDTH_OVERFLOW);
   if (ltemp < (long) numrows)
     rowsperchunk = (JDIMENSION) ltemp;
   else
     rowsperchunk = numrows;
   mem->last_rowsperchunk = rowsperchunk;
   /* Get space for row pointers (small object) */
   result = (JSAMPARRAY) alloc_small(cinfo, pool_id,
                     (size_t) (numrows * SIZEOF(JSAMPROW)));
   /* Get the rows themselves (large objects) */
   currow = 0;
   while (currow < numrows) {
     rowsperchunk = MIN(rowsperchunk, numrows - currow);
     workspace = (JSAMPROW) alloc_large(cinfo, pool_id,
     (size_t) ((size_t) rowsperchunk * (size_t) samplesperrow
           * SIZEOF(JSAMPLE)));
     for (i = rowsperchunk; i > 0; i--) {
       result[currow++] = workspace;
       workspace += samplesperrow;
     }
   }
   return result;
 }
References alloc_large(), alloc_small(), ERREXIT, my_memory_mgr::last_rowsperchunk, MAX_ALLOC_CHUNK, MIN, and SIZEOF.
Referenced by jinit_memory_mgr(), and realize_virt_arrays().
alloc_small()
alloc_small (j_common_ptr cinfo, int pool_id, size_t sizeofobject)
Definition at line 257 of file jmemmgr.c.
 {
   my_mem_ptr mem = (my_mem_ptr) cinfo->mem;
   small_pool_ptr hdr_ptr, prev_hdr_ptr;
   char * data_ptr;
   size_t odd_bytes, min_request, slop;
   /* Check for unsatisfiable request (do now to ensure no overflow below) */
   if (sizeofobject > (size_t) (MAX_ALLOC_CHUNK-SIZEOF(small_pool_hdr)))
     out_of_memory(cinfo, 1);    /* request exceeds malloc's ability */
   /* Round up the requested size to a multiple of SIZEOF(ALIGN_TYPE) */
   odd_bytes = sizeofobject % SIZEOF(ALIGN_TYPE);
   if (odd_bytes > 0)
     sizeofobject += SIZEOF(ALIGN_TYPE) - odd_bytes;
   /* See if space is available in any existing pool */
   if (pool_id < 0 || pool_id >= JPOOL_NUMPOOLS)
     ERREXIT1(cinfo, JERR_BAD_POOL_ID, pool_id); /* safety check */
   prev_hdr_ptr = NULL;
   hdr_ptr = mem->small_list[pool_id];
   while (hdr_ptr != NULL) {
     if (hdr_ptr->hdr.bytes_left >= sizeofobject)
       break;            /* found pool with enough space */
     prev_hdr_ptr = hdr_ptr;
     hdr_ptr = hdr_ptr->hdr.next;
   }
   /* Time to make a new pool? */
   if (hdr_ptr == NULL) {
     /* min_request is what we need now, slop is what will be leftover */
     min_request = sizeofobject + SIZEOF(small_pool_hdr);
     if (prev_hdr_ptr == NULL)   /* first pool in class? */
       slop = first_pool_slop[pool_id];
     else
       slop = extra_pool_slop[pool_id];
     /* Don't ask for more than MAX_ALLOC_CHUNK */
     if (slop > (size_t) (MAX_ALLOC_CHUNK-min_request))
       slop = (size_t) (MAX_ALLOC_CHUNK-min_request);
     /* Try to get space, if fail reduce slop and try again */
     for (;;) {
       hdr_ptr = (small_pool_ptr) jpeg_get_small(cinfo, min_request + slop);
       if (hdr_ptr != NULL)
     break;
       slop /= 2;
       if (slop < MIN_SLOP)  /* give up when it gets real small */
     out_of_memory(cinfo, 2); /* jpeg_get_small failed */
     }
     mem->total_space_allocated += min_request + slop;
     /* Success, initialize the new pool header and add to end of list */
     hdr_ptr->hdr.next = NULL;
     hdr_ptr->hdr.bytes_used = 0;
     hdr_ptr->hdr.bytes_left = sizeofobject + slop;
     if (prev_hdr_ptr == NULL)   /* first pool in class? */
       mem->small_list[pool_id] = hdr_ptr;
     else
       prev_hdr_ptr->hdr.next = hdr_ptr;
   }
   /* OK, allocate the object from the current pool */
   data_ptr = (char *) (hdr_ptr + 1); /* point to first data byte in pool */
   data_ptr += hdr_ptr->hdr.bytes_used; /* point to place for object */
   hdr_ptr->hdr.bytes_used += sizeofobject;
   hdr_ptr->hdr.bytes_left -= sizeofobject;
   return (void *) data_ptr;
 }
References ALIGN_TYPE, ERREXIT1, extra_pool_slop, first_pool_slop, jpeg_get_small(), JPOOL_NUMPOOLS, MAX_ALLOC_CHUNK, MIN_SLOP, NULL, out_of_memory(), SIZEOF, sizeofobject, my_memory_mgr::small_list, and my_memory_mgr::total_space_allocated.
Referenced by alloc_barray(), alloc_sarray(), jinit_memory_mgr(), request_virt_barray(), and request_virt_sarray().
do_barray_io()
do_barray_io (j_common_ptr cinfo, jvirt_barray_ptr ptr, boolean writing)
Definition at line 723 of file jmemmgr.c.
 {
   long bytesperrow, file_offset, byte_count, rows, thisrow, i;
   bytesperrow = (long) ptr->blocksperrow * SIZEOF(JBLOCK);
   file_offset = ptr->cur_start_row * bytesperrow;
   /* Loop to read or write each allocation chunk in mem_buffer */
   for (i = 0; i < (long) ptr->rows_in_mem; i += ptr->rowsperchunk) {
     /* One chunk, but check for short chunk at end of buffer */
     rows = MIN((long) ptr->rowsperchunk, (long) ptr->rows_in_mem - i);
     /* Transfer no more than is currently defined */
     thisrow = (long) ptr->cur_start_row + i;
     rows = MIN(rows, (long) ptr->first_undef_row - thisrow);
     /* Transfer no more than fits in file */
     rows = MIN(rows, (long) ptr->rows_in_array - thisrow);
     if (rows <= 0)      /* this chunk might be past end of file! */
       break;
     byte_count = rows * bytesperrow;
     if (writing)
       (*ptr->b_s_info.write_backing_store) (cinfo, & ptr->b_s_info,
                         (void FAR *) ptr->mem_buffer[i],
                         file_offset, byte_count);
     else
       (*ptr->b_s_info.read_backing_store) (cinfo, & ptr->b_s_info,
                        (void FAR *) ptr->mem_buffer[i],
                        file_offset, byte_count);
     file_offset += byte_count;
   }
 }
References FAR, long(), MIN, ptr(), and SIZEOF.
Referenced by access_virt_barray().
do_sarray_io()
do_sarray_io (j_common_ptr cinfo, jvirt_sarray_ptr ptr, boolean writing)
Definition at line 690 of file jmemmgr.c.
 {
   long bytesperrow, file_offset, byte_count, rows, thisrow, i;
   bytesperrow = (long) ptr->samplesperrow * SIZEOF(JSAMPLE);
   file_offset = ptr->cur_start_row * bytesperrow;
   /* Loop to read or write each allocation chunk in mem_buffer */
   for (i = 0; i < (long) ptr->rows_in_mem; i += ptr->rowsperchunk) {
     /* One chunk, but check for short chunk at end of buffer */
     rows = MIN((long) ptr->rowsperchunk, (long) ptr->rows_in_mem - i);
     /* Transfer no more than is currently defined */
     thisrow = (long) ptr->cur_start_row + i;
     rows = MIN(rows, (long) ptr->first_undef_row - thisrow);
     /* Transfer no more than fits in file */
     rows = MIN(rows, (long) ptr->rows_in_array - thisrow);
     if (rows <= 0)      /* this chunk might be past end of file! */
       break;
     byte_count = rows * bytesperrow;
     if (writing)
       (*ptr->b_s_info.write_backing_store) (cinfo, & ptr->b_s_info,
                         (void FAR *) ptr->mem_buffer[i],
                         file_offset, byte_count);
     else
       (*ptr->b_s_info.read_backing_store) (cinfo, & ptr->b_s_info,
                        (void FAR *) ptr->mem_buffer[i],
                        file_offset, byte_count);
     file_offset += byte_count;
   }
 }
References FAR, long(), MIN, ptr(), and SIZEOF.
Referenced by access_virt_sarray().
free_pool()
free_pool (j_common_ptr cinfo, int pool_id)
Definition at line 930 of file jmemmgr.c.
 {
   my_mem_ptr mem = (my_mem_ptr) cinfo->mem;
   small_pool_ptr shdr_ptr;
   large_pool_ptr lhdr_ptr;
   size_t space_freed;
   if (pool_id < 0 || pool_id >= JPOOL_NUMPOOLS)
     ERREXIT1(cinfo, JERR_BAD_POOL_ID, pool_id); /* safety check */
 #ifdef MEM_STATS
   if (cinfo->err->trace_level > 1)
     print_mem_stats(cinfo, pool_id); /* print pool's memory usage statistics */
 #endif
   /* If freeing IMAGE pool, close any virtual arrays first */
   if (pool_id == JPOOL_IMAGE) {
     jvirt_sarray_ptr sptr;
     jvirt_barray_ptr bptr;
     for (sptr = mem->virt_sarray_list; sptr != NULL; sptr = sptr->next) {
       if (sptr->b_s_open) { /* there may be no backing store */
     sptr->b_s_open = FALSE; /* prevent recursive close if error */
     (*sptr->b_s_info.close_backing_store) (cinfo, & sptr->b_s_info);
       }
     }
     mem->virt_sarray_list = NULL;
     for (bptr = mem->virt_barray_list; bptr != NULL; bptr = bptr->next) {
       if (bptr->b_s_open) { /* there may be no backing store */
     bptr->b_s_open = FALSE; /* prevent recursive close if error */
     (*bptr->b_s_info.close_backing_store) (cinfo, & bptr->b_s_info);
       }
     }
     mem->virt_barray_list = NULL;
   }
   /* Release large objects */
   lhdr_ptr = mem->large_list[pool_id];
   mem->large_list[pool_id] = NULL;
   while (lhdr_ptr != NULL) {
     large_pool_ptr next_lhdr_ptr = lhdr_ptr->hdr.next;
     space_freed = lhdr_ptr->hdr.bytes_used +
           lhdr_ptr->hdr.bytes_left +
           SIZEOF(large_pool_hdr);
     jpeg_free_large(cinfo, (void FAR *) lhdr_ptr, space_freed);
     mem->total_space_allocated -= space_freed;
     lhdr_ptr = next_lhdr_ptr;
   }
   /* Release small objects */
   shdr_ptr = mem->small_list[pool_id];
   mem->small_list[pool_id] = NULL;
   while (shdr_ptr != NULL) {
     small_pool_ptr next_shdr_ptr = shdr_ptr->hdr.next;
     space_freed = shdr_ptr->hdr.bytes_used +
           shdr_ptr->hdr.bytes_left +
           SIZEOF(small_pool_hdr);
     jpeg_free_small(cinfo, (void *) shdr_ptr, space_freed);
     mem->total_space_allocated -= space_freed;
     shdr_ptr = next_shdr_ptr;
   }
 }
References ERREXIT1, FALSE, FAR, small_pool_ptr::hdr, large_pool_ptr::hdr, jpeg_free_large(), jpeg_free_small(), JPOOL_IMAGE, JPOOL_NUMPOOLS, my_memory_mgr::large_list, small_pool_ptr::next, large_pool_ptr::next, NULL, SIZEOF, my_memory_mgr::small_list, my_memory_mgr::total_space_allocated, my_memory_mgr::virt_barray_list, and my_memory_mgr::virt_sarray_list.
Referenced by jinit_memory_mgr(), and self_destruct().
jinit_memory_mgr()
jinit_memory_mgr (j_common_ptr cinfo)
Definition at line 1028 of file jmemmgr.c.
 {
   my_mem_ptr mem;
   long max_to_use;
   int pool;
   size_t test_mac;
   cinfo->mem = NULL;        /* for safety if init fails */
   /* Check for configuration errors.
    * SIZEOF(ALIGN_TYPE) should be a power of 2; otherwise, it probably
    * doesn't reflect any real hardware alignment requirement.
    * The test is a little tricky: for X>0, X and X-1 have no one-bits
    * in common if and only if X is a power of 2, ie has only one one-bit.
    * Some compilers may give an "unreachable code" warning here; ignore it.
    */
   if ((SIZEOF(ALIGN_TYPE) & (SIZEOF(ALIGN_TYPE)-1)) != 0)
     ERREXIT(cinfo, JERR_BAD_ALIGN_TYPE);
   /* MAX_ALLOC_CHUNK must be representable as type size_t, and must be
    * a multiple of SIZEOF(ALIGN_TYPE).
    * Again, an "unreachable code" warning may be ignored here.
    * But a "constant too large" warning means you need to fix MAX_ALLOC_CHUNK.
    */
   test_mac = (size_t) MAX_ALLOC_CHUNK;
   if ((long) test_mac != MAX_ALLOC_CHUNK ||
       (MAX_ALLOC_CHUNK % SIZEOF(ALIGN_TYPE)) != 0)
     ERREXIT(cinfo, JERR_BAD_ALLOC_CHUNK);
   max_to_use = jpeg_mem_init(cinfo); /* system-dependent initialization */
   /* Attempt to allocate memory manager's control block */
   mem = (my_mem_ptr) jpeg_get_small(cinfo, SIZEOF(my_memory_mgr));
   if (mem == NULL) {
     jpeg_mem_term(cinfo);   /* system-dependent cleanup */
     ERREXIT1(cinfo, JERR_OUT_OF_MEMORY, 0);
   }
   /* OK, fill in the method pointers */
   mem->pub.alloc_small = alloc_small;
   mem->pub.alloc_large = alloc_large;
   mem->pub.alloc_sarray = alloc_sarray;
   mem->pub.alloc_barray = alloc_barray;
   mem->pub.request_virt_sarray = request_virt_sarray;
   mem->pub.request_virt_barray = request_virt_barray;
   mem->pub.realize_virt_arrays = realize_virt_arrays;
   mem->pub.access_virt_sarray = access_virt_sarray;
   mem->pub.access_virt_barray = access_virt_barray;
   mem->pub.free_pool = free_pool;
   mem->pub.self_destruct = self_destruct;
   /* Make MAX_ALLOC_CHUNK accessible to other modules */
   mem->pub.max_alloc_chunk = MAX_ALLOC_CHUNK;
   /* Initialize working state */
   mem->pub.max_memory_to_use = max_to_use;
   for (pool = JPOOL_NUMPOOLS-1; pool >= JPOOL_PERMANENT; pool--) {
     mem->small_list[pool] = NULL;
     mem->large_list[pool] = NULL;
   }
   mem->virt_sarray_list = NULL;
   mem->virt_barray_list = NULL;
   mem->total_space_allocated = SIZEOF(my_memory_mgr);
   /* Declare ourselves open for business */
   cinfo->mem = & mem->pub;
   /* Check for an environment variable JPEGMEM; if found, override the
    * default max_memory setting from jpeg_mem_init.  Note that the
    * surrounding application may again override this value.
    * If your system doesn't support getenv(), define NO_GETENV to disable
    * this feature.
    */
 #ifndef NO_GETENV
   { char * memenv;
     if ((memenv = getenv("JPEGMEM")) != NULL) {
       char ch = 'x';
       if (sscanf(memenv, "%ld%c", &max_to_use, &ch) > 0) {
     if (ch == 'm' || ch == 'M')
       max_to_use *= 1000L;
     mem->pub.max_memory_to_use = max_to_use * 1000L;
       }
     }
   }
 #endif
 }
References access_virt_barray(), access_virt_sarray(), ALIGN_TYPE, alloc_barray(), alloc_large(), alloc_sarray(), alloc_small(), ERREXIT, ERREXIT1, free_pool(), jpeg_get_small(), jpeg_mem_init(), jpeg_mem_term(), JPOOL_NUMPOOLS, JPOOL_PERMANENT, my_memory_mgr::large_list, MAX_ALLOC_CHUNK, jpeg_memory_mgr::max_alloc_chunk, jpeg_memory_mgr::max_memory_to_use, NULL, my_memory_mgr::pub, realize_virt_arrays(), request_virt_barray(), request_virt_sarray(), self_destruct(), SIZEOF, my_memory_mgr::small_list, my_memory_mgr::total_space_allocated, my_memory_mgr::virt_barray_list, and my_memory_mgr::virt_sarray_list.
Referenced by jpeg_CreateCompress(), and jpeg_CreateDecompress().
out_of_memory()
out_of_memory (j_common_ptr cinfo, int which)
Definition at line 217 of file jmemmgr.c.
 {
 #ifdef MEM_STATS
   cinfo->err->trace_level = 2;  /* force self_destruct to report stats */
 #endif
   ERREXIT1(cinfo, JERR_OUT_OF_MEMORY, which);
 }
References ERREXIT1.
Referenced by alloc_large(), and alloc_small().
realize_virt_arrays()
realize_virt_arrays (j_common_ptr cinfo)
Definition at line 583 of file jmemmgr.c.
 {
   my_mem_ptr mem = (my_mem_ptr) cinfo->mem;
   long space_per_minheight, maximum_space, avail_mem;
   long minheights, max_minheights;
   jvirt_sarray_ptr sptr;
   jvirt_barray_ptr bptr;
   /* Compute the minimum space needed (maxaccess rows in each buffer)
    * and the maximum space needed (full image height in each buffer).
    * These may be of use to the system-dependent jpeg_mem_available routine.
    */
   space_per_minheight = 0;
   maximum_space = 0;
   for (sptr = mem->virt_sarray_list; sptr != NULL; sptr = sptr->next) {
     if (sptr->mem_buffer == NULL) { /* if not realized yet */
       space_per_minheight += (long) sptr->maxaccess *
                  (long) sptr->samplesperrow * SIZEOF(JSAMPLE);
       maximum_space += (long) sptr->rows_in_array *
                (long) sptr->samplesperrow * SIZEOF(JSAMPLE);
     }
   }
   for (bptr = mem->virt_barray_list; bptr != NULL; bptr = bptr->next) {
     if (bptr->mem_buffer == NULL) { /* if not realized yet */
       space_per_minheight += (long) bptr->maxaccess *
                  (long) bptr->blocksperrow * SIZEOF(JBLOCK);
       maximum_space += (long) bptr->rows_in_array *
                (long) bptr->blocksperrow * SIZEOF(JBLOCK);
     }
   }
   if (space_per_minheight <= 0)
     return;         /* no unrealized arrays, no work */
   /* Determine amount of memory to actually use; this is system-dependent. */
   avail_mem = jpeg_mem_available(cinfo, space_per_minheight, maximum_space,
                  mem->total_space_allocated);
   /* If the maximum space needed is available, make all the buffers full
    * height; otherwise parcel it out with the same number of minheights
    * in each buffer.
    */
   if (avail_mem >= maximum_space)
     max_minheights = 1000000000L;
   else {
     max_minheights = avail_mem / space_per_minheight;
     /* If there doesn't seem to be enough space, try to get the minimum
      * anyway.  This allows a "stub" implementation of jpeg_mem_available().
      */
     if (max_minheights <= 0)
       max_minheights = 1;
   }
   /* Allocate the in-memory buffers and initialize backing store as needed. */
   for (sptr = mem->virt_sarray_list; sptr != NULL; sptr = sptr->next) {
     if (sptr->mem_buffer == NULL) { /* if not realized yet */
       minheights = ((long) sptr->rows_in_array - 1L) / sptr->maxaccess + 1L;
       if (minheights <= max_minheights) {
     /* This buffer fits in memory */
     sptr->rows_in_mem = sptr->rows_in_array;
       } else {
     /* It doesn't fit in memory, create backing store. */
     sptr->rows_in_mem = (JDIMENSION) (max_minheights * sptr->maxaccess);
     jpeg_open_backing_store(cinfo, & sptr->b_s_info,
                 (long) sptr->rows_in_array *
                 (long) sptr->samplesperrow *
                 (long) SIZEOF(JSAMPLE));
     sptr->b_s_open = TRUE;
       }
       sptr->mem_buffer = alloc_sarray(cinfo, JPOOL_IMAGE,
                       sptr->samplesperrow, sptr->rows_in_mem);
       sptr->rowsperchunk = mem->last_rowsperchunk;
       sptr->cur_start_row = 0;
       sptr->first_undef_row = 0;
       sptr->dirty = FALSE;
     }
   }
   for (bptr = mem->virt_barray_list; bptr != NULL; bptr = bptr->next) {
     if (bptr->mem_buffer == NULL) { /* if not realized yet */
       minheights = ((long) bptr->rows_in_array - 1L) / bptr->maxaccess + 1L;
       if (minheights <= max_minheights) {
     /* This buffer fits in memory */
     bptr->rows_in_mem = bptr->rows_in_array;
       } else {
     /* It doesn't fit in memory, create backing store. */
     bptr->rows_in_mem = (JDIMENSION) (max_minheights * bptr->maxaccess);
     jpeg_open_backing_store(cinfo, & bptr->b_s_info,
                 (long) bptr->rows_in_array *
                 (long) bptr->blocksperrow *
                 (long) SIZEOF(JBLOCK));
     bptr->b_s_open = TRUE;
       }
       bptr->mem_buffer = alloc_barray(cinfo, JPOOL_IMAGE,
                       bptr->blocksperrow, bptr->rows_in_mem);
       bptr->rowsperchunk = mem->last_rowsperchunk;
       bptr->cur_start_row = 0;
       bptr->first_undef_row = 0;
       bptr->dirty = FALSE;
     }
   }
 }
References alloc_barray(), alloc_sarray(), FALSE, jpeg_mem_available(), jpeg_open_backing_store(), JPOOL_IMAGE, my_memory_mgr::last_rowsperchunk, long(), NULL, SIZEOF, my_memory_mgr::total_space_allocated, TRUE, my_memory_mgr::virt_barray_list, and my_memory_mgr::virt_sarray_list.
Referenced by jinit_memory_mgr().
request_virt_barray()
request_virt_barray (j_common_ptr cinfo, int pool_id, boolean pre_zero, JDIMENSION blocksperrow, JDIMENSION numrows, JDIMENSION maxaccess)
Definition at line 553 of file jmemmgr.c.
 {
   my_mem_ptr mem = (my_mem_ptr) cinfo->mem;
   jvirt_barray_ptr result;
   /* Only IMAGE-lifetime virtual arrays are currently supported */
   if (pool_id != JPOOL_IMAGE)
     ERREXIT1(cinfo, JERR_BAD_POOL_ID, pool_id); /* safety check */
   /* get control block */
   result = (jvirt_barray_ptr) alloc_small(cinfo, pool_id,
                       SIZEOF(struct jvirt_barray_control));
   result->mem_buffer = NULL;    /* marks array not yet realized */
   result->rows_in_array = numrows;
   result->blocksperrow = blocksperrow;
   result->maxaccess = maxaccess;
   result->pre_zero = pre_zero;
   result->b_s_open = FALSE; /* no associated backing-store object */
   result->next = mem->virt_barray_list; /* add to list of virtual arrays */
   mem->virt_barray_list = result;
   return result;
 }
References alloc_small(), ERREXIT1, FALSE, JPOOL_IMAGE, NULL, SIZEOF, and my_memory_mgr::virt_barray_list.
Referenced by jinit_memory_mgr().
request_virt_sarray()
request_virt_sarray (j_common_ptr cinfo, int pool_id, boolean pre_zero, JDIMENSION samplesperrow, JDIMENSION numrows, JDIMENSION maxaccess)
Definition at line 523 of file jmemmgr.c.
 {
   my_mem_ptr mem = (my_mem_ptr) cinfo->mem;
   jvirt_sarray_ptr result;
   /* Only IMAGE-lifetime virtual arrays are currently supported */
   if (pool_id != JPOOL_IMAGE)
     ERREXIT1(cinfo, JERR_BAD_POOL_ID, pool_id); /* safety check */
   /* get control block */
   result = (jvirt_sarray_ptr) alloc_small(cinfo, pool_id,
                       SIZEOF(struct jvirt_sarray_control));
   result->mem_buffer = NULL;    /* marks array not yet realized */
   result->rows_in_array = numrows;
   result->samplesperrow = samplesperrow;
   result->maxaccess = maxaccess;
   result->pre_zero = pre_zero;
   result->b_s_open = FALSE; /* no associated backing-store object */
   result->next = mem->virt_sarray_list; /* add to list of virtual arrays */
   mem->virt_sarray_list = result;
   return result;
 }
References alloc_small(), ERREXIT1, FALSE, JPOOL_IMAGE, NULL, SIZEOF, and my_memory_mgr::virt_sarray_list.
Referenced by jinit_memory_mgr().
self_destruct()
self_destruct (j_common_ptr cinfo)
Definition at line 1002 of file jmemmgr.c.
 {
   int pool;
   /* Close all backing store, release all memory.
    * Releasing pools in reverse order might help avoid fragmentation
    * with some (brain-damaged) malloc libraries.
    */
   for (pool = JPOOL_NUMPOOLS-1; pool >= JPOOL_PERMANENT; pool--) {
     free_pool(cinfo, pool);
   }
   /* Release the memory manager control block too. */
   jpeg_free_small(cinfo, (void *) cinfo->mem, SIZEOF(my_memory_mgr));
   cinfo->mem = NULL;        /* ensures I will be called only once */
   jpeg_mem_term(cinfo);     /* system-dependent cleanup */
 }
References free_pool(), jpeg_free_small(), jpeg_mem_term(), JPOOL_NUMPOOLS, JPOOL_PERMANENT, NULL, and SIZEOF.
Referenced by jinit_memory_mgr().
Variable Documentation
extra_pool_slop
const size_t extra_pool_slop[JPOOL_NUMPOOLS] static
Initial value:
=
{
    0,
    5000
}
Definition at line 247 of file jmemmgr.c.
Referenced by alloc_small().
first_pool_slop
const size_t first_pool_slop[JPOOL_NUMPOOLS] static
Initial value:
=
{
    1600,
    16000
}
Definition at line 241 of file jmemmgr.c.
Referenced by alloc_small().