ZEQ2-Lite: Game/UI/ui_camera.c File Reference
ui_camera.c File Reference
#include "ui_local.h"
Data Structures
struct camera_t
struct cameraconfigcvar_t
Macros
#define ART_BACK0 "interface/art/back_0"
#define ART_BACK1 "interface/art/back_1"
#define ID_ANGLE 12
#define ID_BACK 13
#define ID_HEIGHT 11
#define ID_RANGE 10
#define ID_SLIDE 14
Functions
void Camera_Cache (void)
static void Camera_GetConfig (void)
static float Camera_GetCvarDefault (char *name)
static float Camera_GetCvarValue (char *name)
static void Camera_InitCvars (void)
static void Camera_MenuEvent (void *ptr, int event)
static void Camera_MenuInit (void)
static void Camera_SetConfig (void)
void UI_CameraMenu (void)
Variables
static cameraconfigcvar_t g_cameraconfigcvars []
static camera_t s_camera
Macro Definition Documentation
ART_BACK0
#define ART_BACK0 "interface/art/back_0"
Definition at line 14 of file ui_camera.c.
ART_BACK1
#define ART_BACK1 "interface/art/back_1"
Definition at line 15 of file ui_camera.c.
ID_ANGLE
#define ID_ANGLE 12
Definition at line 19 of file ui_camera.c.
ID_BACK
#define ID_BACK 13
Definition at line 20 of file ui_camera.c.
ID_HEIGHT
#define ID_HEIGHT 11
Definition at line 18 of file ui_camera.c.
ID_RANGE
#define ID_RANGE 10
Definition at line 17 of file ui_camera.c.
ID_SLIDE
#define ID_SLIDE 14
Definition at line 21 of file ui_camera.c.
Function Documentation
Camera_Cache()
void Camera_Cache (void)
Definition at line 286 of file ui_camera.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
 }
References ART_BACK0, ART_BACK1, and trap_R_RegisterShaderNoMip().
Referenced by Camera_MenuInit().
Camera_GetConfig()
static void Camera_GetConfig (void) static
Definition at line 139 of file ui_camera.c.
 {
     s_camera.rangeSlider.curvalue  = UI_ClampCvar( 15, 150, Camera_GetCvarValue( "cg_thirdPersonRange" ) );
     s_camera.heightSlider.curvalue  = UI_ClampCvar( -80, 80, Camera_GetCvarValue( "cg_thirdPersonHeight" ) );
     s_camera.slideSlider.curvalue  = UI_ClampCvar( -150, 150, Camera_GetCvarValue( "cg_thirdPersonSlide" ) );
     s_camera.angleSlider.curvalue  = UI_ClampCvar( 0, 359, Camera_GetCvarValue( "cg_thirdPersonAngle" ) );
 }
References camera_t::angleSlider, Camera_GetCvarValue(), menuslider_s::curvalue, camera_t::heightSlider, camera_t::rangeSlider, s_camera, camera_t::slideSlider, and UI_ClampCvar().
Referenced by Camera_MenuInit().
Camera_GetCvarDefault()
static float Camera_GetCvarDefault (char * name) static
Definition at line 93 of file ui_camera.c.
 {
     cameraconfigcvar_t* cvarptr;
     int             i;
     cvarptr = g_cameraconfigcvars;
     for (i=0; ;i++,cvarptr++)
     {
         if (!cvarptr->name)
             return (0);
         if (!strcmp(cvarptr->name,name))
             break;
     }
     return (cvarptr->defaultvalue);
 }
References cameraconfigcvar_t::defaultvalue, g_cameraconfigcvars, and cameraconfigcvar_t::name.
Camera_GetCvarValue()
static float Camera_GetCvarValue (char * name) static
Definition at line 116 of file ui_camera.c.
 {
     cameraconfigcvar_t* cvarptr;
     int             i;
     cvarptr = g_cameraconfigcvars;
     for (i=0; ;i++,cvarptr++)
     {
         if (!cvarptr->name)
             return (0);
         if (!strcmp(cvarptr->name,name))
             break;
     }
     return (cvarptr->value);
 }
References g_cameraconfigcvars, cameraconfigcvar_t::name, and cameraconfigcvar_t::value.
Referenced by Camera_GetConfig().
Camera_InitCvars()
static void Camera_InitCvars (void) static
Definition at line 65 of file ui_camera.c.
 {
     int             i;
     cameraconfigcvar_t* cvarptr;
     cvarptr = g_cameraconfigcvars;
     for (i=0; ;i++,cvarptr++)
     {
         if (!cvarptr->name)
             break;
         // get current value
         cvarptr->value = trap_Cvar_VariableValue( cvarptr->name );
         // get default value
         trap_Cvar_Reset( cvarptr->name );
         cvarptr->defaultvalue = trap_Cvar_VariableValue( cvarptr->name );
         // restore current value
         trap_Cvar_SetValue( cvarptr->name, cvarptr->value );
     }
 }
References cameraconfigcvar_t::defaultvalue, g_cameraconfigcvars, cameraconfigcvar_t::name, trap_Cvar_Reset(), trap_Cvar_SetValue(), trap_Cvar_VariableValue(), and cameraconfigcvar_t::value.
Referenced by Camera_MenuInit().
Camera_MenuEvent()
static void Camera_MenuEvent (void * ptr, int event) static
Definition at line 165 of file ui_camera.c.
{
     switch( ((menucommon_s*)ptr)->id ) {
     {
         case ID_BACK:
             if (event == QM_ACTIVATED)
             {
                 if (s_camera.changesMade)
                     Camera_SetConfig();
                 UI_PopMenu();
             }
             break;
         case ID_RANGE:
         case ID_HEIGHT:
         case ID_SLIDE:
         case ID_ANGLE:
             if (event == QM_ACTIVATED)
             {
                 s_camera.changesMade = qtrue;
                 Camera_SetConfig();
             }
             break;
         }
     }
 }
References Camera_SetConfig(), camera_t::changesMade, ID_ANGLE, ID_BACK, ID_HEIGHT, ID_RANGE, ID_SLIDE, ptr(), QM_ACTIVATED, qtrue, s_camera, and UI_PopMenu().
Referenced by Camera_MenuInit().
Camera_MenuInit()
static void Camera_MenuInit (void) static
Definition at line 196 of file ui_camera.c.
 {
     // zero set all our globals
     memset( &s_camera, 0 ,sizeof(camera_t) );
     Camera_Cache();
     s_camera.menu.wrapAround        = qtrue;
     s_camera.menu.fullscreen        = qfalse;
     s_camera.banner.generic.type    = MTYPE_BTEXT;
     s_camera.banner.generic.flags   = QMF_CENTER_JUSTIFY;
     s_camera.banner.generic.x       = 320;
     s_camera.banner.generic.y       = 16;
     s_camera.banner.string          = "CAMERA";
     s_camera.banner.color           = color_white;
     s_camera.banner.style           = UI_CENTER|UI_DROPSHADOW;
     s_camera.rangeSlider.generic.type       = MTYPE_SLIDER;
     s_camera.rangeSlider.generic.name       = "Range:";
     s_camera.rangeSlider.generic.flags      = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     s_camera.rangeSlider.generic.callback   = Camera_MenuEvent;
     s_camera.rangeSlider.generic.id         = ID_RANGE;
     s_camera.rangeSlider.generic.x          = 70;
     s_camera.rangeSlider.generic.y          = 40;
     s_camera.rangeSlider.minvalue           = 15;
     s_camera.rangeSlider.maxvalue           = 150;
     s_camera.heightSlider.generic.type      = MTYPE_SLIDER;
     s_camera.heightSlider.generic.name      = "Height:";
     s_camera.heightSlider.generic.flags     = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     s_camera.heightSlider.generic.callback  = Camera_MenuEvent;
     s_camera.heightSlider.generic.id        = ID_HEIGHT;
     s_camera.heightSlider.generic.x         = 70;
     s_camera.heightSlider.generic.y         = 60;
     s_camera.heightSlider.minvalue          = -80;
     s_camera.heightSlider.maxvalue          = 80;
     s_camera.slideSlider.generic.type       = MTYPE_SLIDER;
     s_camera.slideSlider.generic.name       = "Slide:";
     s_camera.slideSlider.generic.flags      = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     s_camera.slideSlider.generic.callback   = Camera_MenuEvent;
     s_camera.slideSlider.generic.id         = ID_SLIDE;
     s_camera.slideSlider.generic.x          = 70;
     s_camera.slideSlider.generic.y          = 80;
     s_camera.slideSlider.minvalue           = -150;
     s_camera.slideSlider.maxvalue           = 150;
     s_camera.angleSlider.generic.type       = MTYPE_SLIDER;
     s_camera.angleSlider.generic.name       = "Angle:";
     s_camera.angleSlider.generic.flags      = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     s_camera.angleSlider.generic.callback   = Camera_MenuEvent;
     s_camera.angleSlider.generic.id         = ID_ANGLE;
     s_camera.angleSlider.generic.x          = 70;
     s_camera.angleSlider.generic.y          = 100;
     s_camera.angleSlider.minvalue           = 0;
     s_camera.angleSlider.maxvalue           = 359;
     s_camera.back.generic.type          = MTYPE_BITMAP;
     s_camera.back.generic.name          = ART_BACK0;
     s_camera.back.generic.flags         = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_camera.back.generic.x             = 640-128;
     s_camera.back.generic.y             = 480-64;
     s_camera.back.generic.id            = ID_BACK;
     s_camera.back.generic.callback      = Camera_MenuEvent;
     s_camera.back.width                 = 128;
     s_camera.back.height                = 64;
     s_camera.back.focuspic              = ART_BACK1;
     Menu_AddItem( &s_camera.menu, &s_camera.banner );
     Menu_AddItem( &s_camera.menu, &s_camera.rangeSlider );
     Menu_AddItem( &s_camera.menu, &s_camera.heightSlider );
     Menu_AddItem( &s_camera.menu, &s_camera.slideSlider );
     Menu_AddItem( &s_camera.menu, &s_camera.angleSlider );
     Menu_AddItem( &s_camera.menu, &s_camera.back );
     // initialize the configurable cvars
     Camera_InitCvars();
     // initialize the current config
     Camera_GetConfig();
 }
References camera_t::angleSlider, ART_BACK0, ART_BACK1, camera_t::back, camera_t::banner, menucommon_s::callback, Camera_Cache(), Camera_GetConfig(), Camera_InitCvars(), Camera_MenuEvent(), menutext_s::color, color_white, menucommon_s::flags, menubitmap_s::focuspic, menuslider_s::generic, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, camera_t::heightSlider, menucommon_s::id, ID_ANGLE, ID_BACK, ID_HEIGHT, ID_RANGE, ID_SLIDE, menuslider_s::maxvalue, camera_t::menu, Menu_AddItem(), menuslider_s::minvalue, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_SLIDER, menucommon_s::name, qfalse, QMF_CENTER_JUSTIFY, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, QMF_SMALLFONT, qtrue, camera_t::rangeSlider, s_camera, camera_t::slideSlider, menutext_s::string, menutext_s::style, menucommon_s::type, UI_CENTER, UI_DROPSHADOW, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by UI_CameraMenu().
Camera_SetConfig()
static void Camera_SetConfig (void) static
Definition at line 152 of file ui_camera.c.
 {
     trap_Cvar_SetValue( "cg_thirdPersonRange", s_camera.rangeSlider.curvalue );
     trap_Cvar_SetValue( "cg_thirdPersonHeight", s_camera.heightSlider.curvalue );
     trap_Cvar_SetValue( "cg_thirdPersonSlide", s_camera.slideSlider.curvalue );
     trap_Cvar_SetValue( "cg_thirdPersonAngle", s_camera.angleSlider.curvalue );
 }
References camera_t::angleSlider, menuslider_s::curvalue, camera_t::heightSlider, camera_t::rangeSlider, s_camera, camera_t::slideSlider, and trap_Cvar_SetValue().
Referenced by Camera_MenuEvent().
UI_CameraMenu()
void UI_CameraMenu (void)
Definition at line 297 of file ui_camera.c.
{
     Camera_MenuInit();
     UI_PushMenu( &s_camera.menu );
 }
References Camera_MenuInit(), camera_t::menu, s_camera, and UI_PushMenu().
Referenced by InGame_Event().
Variable Documentation
g_cameraconfigcvars
cameraconfigcvar_t g_cameraconfigcvars[] static
Initial value:
=
{
    {"cg_thirdPersonRange", 0,  0},
    {"cg_thirdPersonHeight",0,  0},
    {"cg_thirdPersonSlide",0,   0},
    {"cg_thirdPersonAngle", 0,  0},
    {NULL,                  0,  0}
}
Definition at line 51 of file ui_camera.c.
Referenced by Camera_GetCvarDefault(), Camera_GetCvarValue(), and Camera_InitCvars().
s_camera
camera_t s_camera static
Definition at line 49 of file ui_camera.c.
Referenced by Camera_GetConfig(), Camera_MenuEvent(), Camera_MenuInit(), Camera_SetConfig(), and UI_CameraMenu().