ZEQ2-Lite: Source/Game/CGame/cg_servercmds.c File Reference
cg_servercmds.c File Reference
#include "cg_local.h"
#include "../UI/menudef/menudef.h"
Data Structures
struct bufferedVoiceChat_s
struct headModelVoiceChat_s
struct orderTask_t
struct voiceChat_s
struct voiceChatList_s
Macros
#define MAX_CHATSIZE 64
#define MAX_HEADMODELS 64
#define MAX_VOICECHATBUFFER 32
#define MAX_VOICECHATS 64
#define MAX_VOICEFILES 8
#define MAX_VOICEFILESIZE 16384
#define MAX_VOICESOUNDS 64
Functions
void CG_AddBufferedVoiceChat (bufferedVoiceChat_t *vchat)
static void CG_AddToTeamChat (const char *str)
static void CG_ConfigStringModified (void)
void CG_ExecuteNewServerCommands (int latestSequence)
int CG_GetVoiceChat (voiceChatList_t *voiceChatList, const char *id, sfxHandle_t *snd, char **chat)
int CG_HeadModelVoiceChats (char *filename)
void CG_LoadVoiceChats (void)
static void CG_MapRestart (void)
static void CG_ParseScores (void)
void CG_ParseServerinfo (void)
static void CG_ParseTeamInfo (void)
int CG_ParseVoiceChats (const char *filename, voiceChatList_t *voiceChatList, int maxVoiceChats)
static void CG_ParseWarmup (void)
void CG_PlayBufferedVoiceChats (void)
void CG_PlayVoiceChat (bufferedVoiceChat_t *vchat)
static void CG_RemoveChatEscapeChar (char *text)
static void CG_ServerCommand (void)
void CG_SetConfigValues (void)
void CG_ShaderStateChanged (void)
void CG_VoiceChat (int mode)
voiceChatList_t * CG_VoiceChatListForClient (int clientNum)
void CG_VoiceChatLocal (int mode, qboolean voiceOnly, int clientNum, int color, const char *cmd)
Variables
headModelVoiceChat_t headModelVoiceChat [MAX_HEADMODELS]
static const int numValidOrders = ARRAY_LEN(validOrders)
static const orderTask_t validOrders []
bufferedVoiceChat_t voiceChatBuffer [MAX_VOICECHATBUFFER]
voiceChatList_t voiceChatLists [MAX_VOICEFILES]
Macro Definition Documentation
MAX_CHATSIZE
#define MAX_CHATSIZE 64
Definition at line 438 of file cg_servercmds.c.
MAX_HEADMODELS
#define MAX_HEADMODELS 64
Definition at line 439 of file cg_servercmds.c.
MAX_VOICECHATBUFFER
#define MAX_VOICECHATBUFFER 32
Definition at line 707 of file cg_servercmds.c.
MAX_VOICECHATS
#define MAX_VOICECHATS 64
Definition at line 436 of file cg_servercmds.c.
MAX_VOICEFILES
#define MAX_VOICEFILES 8
Definition at line 435 of file cg_servercmds.c.
MAX_VOICEFILESIZE
#define MAX_VOICEFILESIZE 16384
Definition at line 434 of file cg_servercmds.c.
MAX_VOICESOUNDS
#define MAX_VOICESOUNDS 64
Definition at line 437 of file cg_servercmds.c.
Function Documentation
CG_AddBufferedVoiceChat()
void CG_AddBufferedVoiceChat (bufferedVoiceChat_t * vchat)
Definition at line 741 of file cg_servercmds.c.
{
 }
CG_AddToTeamChat()
static void CG_AddToTeamChat (const char * str) static
Definition at line 317 of file cg_servercmds.c.
{
     int len;
     char *p, *ls;
     int lastcolor;
     int chatHeight;
     if (cg_teamChatHeight.integer < TEAMCHAT_HEIGHT) {
         chatHeight = cg_teamChatHeight.integer;
     } else {
         chatHeight = TEAMCHAT_HEIGHT;
     }
     if (chatHeight <= 0 || cg_teamChatTime.integer <= 0) {
         // team chat disabled, dump into normal chat
         cgs.teamChatPos = cgs.teamLastChatPos = 0;
         return;
     }
     len = 0;
     p = cgs.teamChatMsgs[cgs.teamChatPos % chatHeight];
     *p = 0;
     lastcolor = '7';
     ls = NULL;
     while (*str) {
         if (len > TEAMCHAT_WIDTH - 1) {
             if (ls) {
                 str -= (p - ls);
                 str++;
                 p -= (p - ls);
             }
             *p = 0;
             cgs.teamChatMsgTimes[cgs.teamChatPos % chatHeight] = cg.time;
             cgs.teamChatPos++;
             p = cgs.teamChatMsgs[cgs.teamChatPos % chatHeight];
             *p = 0;
             *p++ = Q_COLOR_ESCAPE;
             *p++ = lastcolor;
             len = 0;
             ls = NULL;
         }
         if ( Q_IsColorString( str ) ) {
             *p++ = *str++;
             lastcolor = *str;
             *p++ = *str++;
             continue;
         }
         if (*str == ' ') {
             ls = p;
         }
         *p++ = *str++;
         len++;
     }
     *p = 0;
     cgs.teamChatMsgTimes[cgs.teamChatPos % chatHeight] = cg.time;
     cgs.teamChatPos++;
     if (cgs.teamChatPos - cgs.teamLastChatPos > chatHeight)
         cgs.teamLastChatPos = cgs.teamChatPos - chatHeight;
 }
References cg, cg_teamChatHeight, cg_teamChatTime, cgs, vmCvar_t::integer, NULL, Q_COLOR_ESCAPE, Q_IsColorString, TEAMCHAT_HEIGHT, TEAMCHAT_WIDTH, cgs_t::teamChatMsgs, cgs_t::teamChatMsgTimes, cgs_t::teamChatPos, cgs_t::teamLastChatPos, and cg_t::time.
Referenced by CG_ServerCommand().
CG_ConfigStringModified()
static void CG_ConfigStringModified (void) static
Definition at line 240 of file cg_servercmds.c.
{
     const char  *str;
     int     num;
     num = atoi( CG_Argv( 1 ) );
     // get the gamestate from the client system, which will have the
     // new configstring already integrated
     trap_GetGameState( &cgs.gameState );
     // look up the individual string that was modified
     str = CG_ConfigString( num );
     // do something with it if necessary
     if ( num == CS_SERVERINFO ) {
         CG_ParseServerinfo();
     } else if ( num == CS_WARMUP ) {
         CG_ParseWarmup();
     } else if ( num == CS_SCORES1 ) {
         cgs.scores1 = atoi( str );
     } else if ( num == CS_SCORES2 ) {
         cgs.scores2 = atoi( str );
     } else if ( num == CS_LEVEL_START_TIME ) {
         cgs.levelStartTime = atoi( str );
     } else if ( num == CS_VOTE_TIME ) {
         cgs.voteTime = atoi( str );
         cgs.voteModified = qtrue;
     } else if ( num == CS_VOTE_YES ) {
         cgs.voteYes = atoi( str );
         cgs.voteModified = qtrue;
     } else if ( num == CS_VOTE_NO ) {
         cgs.voteNo = atoi( str );
         cgs.voteModified = qtrue;
     } else if ( num == CS_VOTE_STRING ) {
         Q_strncpyz( cgs.voteString, str, sizeof( cgs.voteString ) );
     } else if ( num >= CS_TEAMVOTE_TIME && num <= CS_TEAMVOTE_TIME + 1) {
         cgs.teamVoteTime[num-CS_TEAMVOTE_TIME] = atoi( str );
         cgs.teamVoteModified[num-CS_TEAMVOTE_TIME] = qtrue;
     } else if ( num >= CS_TEAMVOTE_YES && num <= CS_TEAMVOTE_YES + 1) {
         cgs.teamVoteYes[num-CS_TEAMVOTE_YES] = atoi( str );
         cgs.teamVoteModified[num-CS_TEAMVOTE_YES] = qtrue;
     } else if ( num >= CS_TEAMVOTE_NO && num <= CS_TEAMVOTE_NO + 1) {
         cgs.teamVoteNo[num-CS_TEAMVOTE_NO] = atoi( str );
         cgs.teamVoteModified[num-CS_TEAMVOTE_NO] = qtrue;
     } else if ( num >= CS_TEAMVOTE_STRING && num <= CS_TEAMVOTE_STRING + 1) {
         Q_strncpyz( cgs.teamVoteString[num-CS_TEAMVOTE_STRING], str, sizeof( cgs.teamVoteString ) );
     } else if ( num == CS_INTERMISSION ) {
         cg.intermissionStarted = atoi( str );
     } else if ( num >= CS_MODELS && num < CS_MODELS+MAX_MODELS ) {
         cgs.gameModels[ num-CS_MODELS ] = trap_R_RegisterModel( str );
     } else if ( num >= CS_SOUNDS && num < CS_SOUNDS+MAX_SOUNDS ) {
         if ( str[0] != '*' ) {  // player specific sounds don't register here
             cgs.gameSounds[ num-CS_SOUNDS] = trap_S_RegisterSound( str, qfalse );
         }
     } else if ( num >= CS_PLAYERS && num < CS_PLAYERS+MAX_CLIENTS ) {
         CG_NewClientInfo( num - CS_PLAYERS );
         CG_BuildSpectatorString();
     } else if ( num == CS_FLAGSTATUS ) {
         if( cgs.gametype == GT_CTF ) {
             // format is rb where its red/blue, 0 is at base, 1 is taken, 2 is dropped
             cgs.redflag = str[0] - '0';
             cgs.blueflag = str[1] - '0';
         }
     }
     else if ( num == CS_SHADERSTATE ) {
         CG_ShaderStateChanged();
     }
 }
References cgs_t::blueflag, cg, CG_Argv(), CG_BuildSpectatorString(), CG_ConfigString(), CG_NewClientInfo(), CG_ParseServerinfo(), CG_ParseWarmup(), CG_ShaderStateChanged(), cgs, CS_FLAGSTATUS, CS_INTERMISSION, CS_LEVEL_START_TIME, CS_MODELS, CS_PLAYERS, CS_SCORES1, CS_SCORES2, CS_SERVERINFO, CS_SHADERSTATE, CS_SOUNDS, CS_TEAMVOTE_NO, CS_TEAMVOTE_STRING, CS_TEAMVOTE_TIME, CS_TEAMVOTE_YES, CS_VOTE_NO, CS_VOTE_STRING, CS_VOTE_TIME, CS_VOTE_YES, CS_WARMUP, cgs_t::gameModels, cgs_t::gameSounds, cgs_t::gameState, cgs_t::gametype, GT_CTF, cg_t::intermissionStarted, cgs_t::levelStartTime, MAX_CLIENTS, MAX_MODELS, MAX_SOUNDS, Q_strncpyz(), qfalse, qtrue, cgs_t::redflag, cgs_t::scores1, cgs_t::scores2, cgs_t::teamVoteModified, cgs_t::teamVoteNo, cgs_t::teamVoteString, cgs_t::teamVoteTime, cgs_t::teamVoteYes, trap_GetGameState(), trap_R_RegisterModel(), trap_S_RegisterSound(), cgs_t::voteModified, cgs_t::voteNo, cgs_t::voteString, cgs_t::voteTime, and cgs_t::voteYes.
Referenced by CG_ServerCommand().
CG_ExecuteNewServerCommands()
void CG_ExecuteNewServerCommands (int latestSequence)
Definition at line 997 of file cg_servercmds.c.
{
     while ( cgs.serverCommandSequence < latestSequence ) {
         if ( trap_GetServerCommand( ++cgs.serverCommandSequence ) ) {
             CG_ServerCommand();
         }
     }
 }
References CG_ServerCommand(), cgs, cgs_t::serverCommandSequence, and trap_GetServerCommand().
Referenced by CG_SetInitialSnapshot(), and CG_TransitionSnapshot().
CG_GetVoiceChat()
int CG_GetVoiceChat (voiceChatList_t * voiceChatList, const char * id, sfxHandle_t * snd, char ** chat)
Definition at line 625 of file cg_servercmds.c.
{
     int i, rnd;
     for ( i = 0; i < voiceChatList->numVoiceChats; i++ ) {
         if ( !Q_stricmp( id, voiceChatList->voiceChats[i].id ) ) {
             rnd = random() * voiceChatList->voiceChats[i].numSounds;
             *snd = voiceChatList->voiceChats[i].sounds[rnd];
             *chat = voiceChatList->voiceChats[i].chats[rnd];
             return qtrue;
         }
     }
     return qfalse;
 }
References Q_stricmp(), qfalse, qtrue, and random.
CG_HeadModelVoiceChats()
int CG_HeadModelVoiceChats (char * filename)
Definition at line 578 of file cg_servercmds.c.
{
     int len, i;
     fileHandle_t f;
     char buf[MAX_VOICEFILESIZE];
     char **p, *ptr;
     char *token;
     len = trap_FS_FOpenFile( filename, &f, FS_READ );
     if ( !f ) {
         //trap_Print( va( "voice chat file not found: %s\n", filename ) );
         return -1;
     }
     if ( len >= MAX_VOICEFILESIZE ) {
         trap_Print( va( S_COLOR_RED "voice chat file too large: %s is %i, max allowed is %i\n", filename, len, MAX_VOICEFILESIZE ) );
         trap_FS_FCloseFile( f );
         return -1;
     }
     trap_FS_Read( buf, len, f );
     buf[len] = 0;
     trap_FS_FCloseFile( f );
     ptr = buf;
     p = &ptr;
     token = COM_ParseExt(p, qtrue);
     if (!token || token[0] == 0) {
         return -1;
     }
     for ( i = 0; i < MAX_VOICEFILES; i++ ) {
         if ( !Q_stricmp(token, voiceChatLists[i].name) ) {
             return i;
         }
     }
     //FIXME: maybe try to load the .voice file which name is stored in token?
     return -1;
 }
References COM_ParseExt(), FS_READ, MAX_VOICEFILES, MAX_VOICEFILESIZE, ptr(), Q_stricmp(), qtrue, S_COLOR_RED, token, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_Print(), va(), and voiceChatLists.
Referenced by CG_VoiceChatListForClient().
CG_LoadVoiceChats()
void CG_LoadVoiceChats (void)
Definition at line 558 of file cg_servercmds.c.
{
     int size;
     size = trap_MemoryRemaining();
     CG_ParseVoiceChats( "scripts/female1.voice", &voiceChatLists[0], MAX_VOICECHATS );
     CG_ParseVoiceChats( "scripts/female2.voice", &voiceChatLists[1], MAX_VOICECHATS );
     CG_ParseVoiceChats( "scripts/female3.voice", &voiceChatLists[2], MAX_VOICECHATS );
     CG_ParseVoiceChats( "scripts/male1.voice", &voiceChatLists[3], MAX_VOICECHATS );
     CG_ParseVoiceChats( "scripts/male2.voice", &voiceChatLists[4], MAX_VOICECHATS );
     CG_ParseVoiceChats( "scripts/male3.voice", &voiceChatLists[5], MAX_VOICECHATS );
     CG_ParseVoiceChats( "scripts/male4.voice", &voiceChatLists[6], MAX_VOICECHATS );
     CG_ParseVoiceChats( "scripts/male5.voice", &voiceChatLists[7], MAX_VOICECHATS );
     CG_Printf("voice chat memory size = %d\n", size - trap_MemoryRemaining());
 }
References CG_ParseVoiceChats(), CG_Printf(), MAX_VOICECHATS, trap_MemoryRemaining(), and voiceChatLists.
CG_MapRestart()
static void CG_MapRestart (void) static
Definition at line 395 of file cg_servercmds.c.
{
     if ( cg_showmiss.integer ) {
         CG_Printf( "CG_MapRestart\n" );
     }
     CG_InitLocalEntities();
     CG_InitMarkPolys();
     // ADDING FOR ZEQ2
     CG_FrameHist_Init();
     CG_InitTrails();
     CG_InitParticleSystems();
     CG_InitBeamTables();
     CG_InitRadarBlips();
     // make sure the "3 frags left" warnings play again
     cg.fraglimitWarnings = 0;
     cg.timelimitWarnings = 0;
     cg.intermissionStarted = qfalse;
     cg.levelShot = qfalse;
     cgs.voteTime = 0;
     cg.mapRestart = qtrue;
     trap_S_ClearLoopingSounds(qtrue);
     // we really should clear more parts of cg here and stop sounds
     // play the "fight" sound if this is a restart without warmup
     if ( cg.warmup == 0 /* && cgs.gametype == GT_TOURNAMENT */) {
         //trap_S_StartLocalSound( cgs.media.countFightSound, CHAN_ANNOUNCER );
         CG_CenterPrint( "FIGHT!", 120, BIGCHAR_WIDTH*2 );
     }
     trap_Cvar_Set("cg_thirdPerson", "1"); // ZEQ2 Stays in third person
 }
References BIGCHAR_WIDTH, cg, CG_CenterPrint(), CG_FrameHist_Init(), CG_InitBeamTables(), CG_InitLocalEntities(), CG_InitMarkPolys(), CG_InitParticleSystems(), CG_InitRadarBlips(), CG_InitTrails(), CG_Printf(), cg_showmiss, cgs, cg_t::fraglimitWarnings, vmCvar_t::integer, cg_t::intermissionStarted, cg_t::levelShot, cg_t::mapRestart, qfalse, qtrue, cg_t::timelimitWarnings, trap_Cvar_Set(), trap_S_ClearLoopingSounds(), cgs_t::voteTime, and cg_t::warmup.
Referenced by CG_ServerCommand().
CG_ParseScores()
static void CG_ParseScores (void) static
Definition at line 55 of file cg_servercmds.c.
{
     int     i, powerups;
     cg.numScores = atoi( CG_Argv( 1 ) );
     if ( cg.numScores > MAX_CLIENTS ) {
         cg.numScores = MAX_CLIENTS;
     }
     cg.teamScores[0] = atoi( CG_Argv( 2 ) );
     cg.teamScores[1] = atoi( CG_Argv( 3 ) );
     memset( cg.scores, 0, sizeof( cg.scores ) );
     for ( i = 0 ; i < cg.numScores ; i++ ) {
         //
         cg.scores[i].client = atoi( CG_Argv( i * 14 + 4 ) );
         cg.scores[i].score = atoi( CG_Argv( i * 14 + 5 ) );
         cg.scores[i].ping = atoi( CG_Argv( i * 14 + 6 ) );
         cg.scores[i].time = atoi( CG_Argv( i * 14 + 7 ) );
         cg.scores[i].scoreFlags = atoi( CG_Argv( i * 14 + 8 ) );
         powerups = atoi( CG_Argv( i * 14 + 9 ) );
         cg.scores[i].accuracy = atoi(CG_Argv(i * 14 + 10));
         cg.scores[i].impressiveCount = atoi(CG_Argv(i * 14 + 11));
         cg.scores[i].excellentCount = atoi(CG_Argv(i * 14 + 12));
         cg.scores[i].guantletCount = atoi(CG_Argv(i * 14 + 13));
         cg.scores[i].defendCount = atoi(CG_Argv(i * 14 + 14));
         cg.scores[i].assistCount = atoi(CG_Argv(i * 14 + 15));
         cg.scores[i].perfect = atoi(CG_Argv(i * 14 + 16));
         cg.scores[i].captures = atoi(CG_Argv(i * 14 + 17));
         if ( cg.scores[i].client < 0 || cg.scores[i].client >= MAX_CLIENTS ) {
             cg.scores[i].client = 0;
         }
         cgs.clientinfo[ cg.scores[i].client ].score = cg.scores[i].score;
         cgs.clientinfo[ cg.scores[i].client ].powerups = powerups;
         cg.scores[i].team = cgs.clientinfo[cg.scores[i].client].team;
     }
 }
References score_t::accuracy, score_t::assistCount, score_t::captures, cg, CG_Argv(), cgs, score_t::client, cgs_t::clientinfo, score_t::defendCount, score_t::excellentCount, score_t::guantletCount, score_t::impressiveCount, MAX_CLIENTS, cg_t::numScores, score_t::perfect, score_t::ping, clientInfo_t::powerups, score_t::score, clientInfo_t::score, score_t::scoreFlags, cg_t::scores, score_t::team, clientInfo_t::team, cg_t::teamScores, and score_t::time.
Referenced by CG_ServerCommand().
CG_ParseServerinfo()
void CG_ParseServerinfo (void)
Definition at line 138 of file cg_servercmds.c.
{
     const char  *info;
     char    *mapname;
     info = CG_ConfigString( CS_SERVERINFO );
     cgs.gametype = atoi( Info_ValueForKey( info, "g_gametype" ) );
     trap_Cvar_Set("g_gametype", va("%i", cgs.gametype));
     cgs.dmflags = atoi( Info_ValueForKey( info, "dmflags" ) );
     cgs.teamflags = atoi( Info_ValueForKey( info, "teamflags" ) );
     cgs.fraglimit = atoi( Info_ValueForKey( info, "fraglimit" ) );
     cgs.capturelimit = atoi( Info_ValueForKey( info, "capturelimit" ) );
     cgs.timelimit = atoi( Info_ValueForKey( info, "timelimit" ) );
     cgs.maxclients = atoi( Info_ValueForKey( info, "sv_maxclients" ) );
     mapname = Info_ValueForKey( info, "mapname" );
     Com_sprintf( cgs.mapname, sizeof( cgs.mapname ), "maps/%s.bsp", mapname );
     Q_strncpyz( cgs.redTeam, Info_ValueForKey( info, "g_redTeam" ), sizeof(cgs.redTeam) );
     trap_Cvar_Set("g_redTeam", cgs.redTeam);
     Q_strncpyz( cgs.blueTeam, Info_ValueForKey( info, "g_blueTeam" ), sizeof(cgs.blueTeam) );
     trap_Cvar_Set("g_blueTeam", cgs.blueTeam);
 }
References cgs_t::blueTeam, cgs_t::capturelimit, CG_ConfigString(), cgs, Com_sprintf(), CS_SERVERINFO, cgs_t::dmflags, cgs_t::fraglimit, cgs_t::gametype, info, Info_ValueForKey(), cgs_t::mapname, cgs_t::maxclients, Q_strncpyz(), cgs_t::redTeam, cgs_t::teamflags, cgs_t::timelimit, trap_Cvar_Set(), and va().
Referenced by CG_ConfigStringModified(), and CG_Init().
CG_ParseTeamInfo()
static void CG_ParseTeamInfo (void) static
Definition at line 100 of file cg_servercmds.c.
{
     int     i;
     int     client;
     numSortedTeamPlayers = atoi( CG_Argv( 1 ) );
     if( numSortedTeamPlayers < 0 || numSortedTeamPlayers > TEAM_MAXOVERLAY )
     {
         CG_Error( "CG_ParseTeamInfo: numSortedTeamPlayers out of range (%d)",
                 numSortedTeamPlayers );
         return;
     }
     for ( i = 0 ; i < numSortedTeamPlayers ; i++ ) {
         client = atoi( CG_Argv( i * 6 + 2 ) );
         if( client < 0 || client >= MAX_CLIENTS )
         {
           CG_Error( "CG_ParseTeamInfo: bad client number: %d", client );
           return;
         }
         sortedTeamPlayers[i] = client;
         cgs.clientinfo[ client ].location = atoi( CG_Argv( i * 6 + 3 ) );
         cgs.clientinfo[ client ].armor = atoi( CG_Argv( i * 6 + 5 ) );
         cgs.clientinfo[ client ].curWeapon = atoi( CG_Argv( i * 6 + 6 ) );
         cgs.clientinfo[ client ].powerups = atoi( CG_Argv( i * 6 + 7 ) );
     }
 }
References clientInfo_t::armor, CG_Argv(), CG_Error(), cgs, cgs_t::clientinfo, clientInfo_t::curWeapon, clientInfo_t::location, MAX_CLIENTS, numSortedTeamPlayers, clientInfo_t::powerups, sortedTeamPlayers, and TEAM_MAXOVERLAY.
Referenced by CG_ServerCommand().
CG_ParseVoiceChats()
int CG_ParseVoiceChats (const char * filename, voiceChatList_t * voiceChatList, int maxVoiceChats)
Definition at line 470 of file cg_servercmds.c.
{
     int len, i;
     fileHandle_t f;
     char buf[MAX_VOICEFILESIZE];
     char **p, *ptr;
     char *token;
     voiceChat_t *voiceChats;
     qboolean compress;
     sfxHandle_t sound;
     compress = qtrue;
     if (cg_buildScript.integer) {
         compress = qfalse;
     }
     len = trap_FS_FOpenFile( filename, &f, FS_READ );
     if ( !f ) {
         trap_Print( va( S_COLOR_RED "voice chat file not found: %s\n", filename ) );
         return qfalse;
     }
     if ( len >= MAX_VOICEFILESIZE ) {
         trap_Print( va( S_COLOR_RED "voice chat file too large: %s is %i, max allowed is %i\n", filename, len, MAX_VOICEFILESIZE ) );
         trap_FS_FCloseFile( f );
         return qfalse;
     }
     trap_FS_Read( buf, len, f );
     buf[len] = 0;
     trap_FS_FCloseFile( f );
     ptr = buf;
     p = &ptr;
     Com_sprintf(voiceChatList->name, sizeof(voiceChatList->name), "%s", filename);
     voiceChats = voiceChatList->voiceChats;
     for ( i = 0; i < maxVoiceChats; i++ ) {
         voiceChats[i].id[0] = 0;
     }
     token = COM_ParseExt(p, qtrue);
     if (!token || token[0] == 0) {
         return qtrue;
     }
     voiceChatList->numVoiceChats = 0;
     while ( 1 ) {
         token = COM_ParseExt(p, qtrue);
         if (!token || token[0] == 0) {
             return qtrue;
         }
         Com_sprintf(voiceChats[voiceChatList->numVoiceChats].id, sizeof( voiceChats[voiceChatList->numVoiceChats].id ), "%s", token);
         token = COM_ParseExt(p, qtrue);
         if (Q_stricmp(token, "{")) {
             trap_Print( va( S_COLOR_RED "expected { found %s in voice chat file: %s\n", token, filename ) );
             return qfalse;
         }
         voiceChats[voiceChatList->numVoiceChats].numSounds = 0;
         while(1) {
             token = COM_ParseExt(p, qtrue);
             if (!token || token[0] == 0) {
                 return qtrue;
             }
             if (!Q_stricmp(token, "}"))
                 break;
             sound = trap_S_RegisterSound( token, compress );
             voiceChats[voiceChatList->numVoiceChats].sounds[voiceChats[voiceChatList->numVoiceChats].numSounds] = sound;
             token = COM_ParseExt(p, qtrue);
             if (!token || token[0] == 0) {
                 return qtrue;
             }
             Com_sprintf(voiceChats[voiceChatList->numVoiceChats].chats[
                             voiceChats[voiceChatList->numVoiceChats].numSounds], MAX_CHATSIZE, "%s", token);
             if (sound)
                 voiceChats[voiceChatList->numVoiceChats].numSounds++;
             if (voiceChats[voiceChatList->numVoiceChats].numSounds >= MAX_VOICESOUNDS)
                 break;
         }
         voiceChatList->numVoiceChats++;
         if (voiceChatList->numVoiceChats >= maxVoiceChats)
             return qtrue;
     }
     return qtrue;
 }
References cg_buildScript, COM_ParseExt(), Com_sprintf(), FS_READ, vmCvar_t::integer, MAX_CHATSIZE, MAX_VOICEFILESIZE, MAX_VOICESOUNDS, ptr(), Q_stricmp(), qfalse, qtrue, S_COLOR_RED, token, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_Print(), trap_S_RegisterSound(), and va().
Referenced by CG_LoadVoiceChats().
CG_ParseWarmup()
static void CG_ParseWarmup (void) static
Definition at line 164 of file cg_servercmds.c.
{
     const char  *info;
     int         warmup;
     info = CG_ConfigString( CS_WARMUP );
     warmup = atoi( info );
     cg.warmupCount = -1;
     cg.warmup = warmup;
 }
References cg, CG_ConfigString(), CS_WARMUP, info, cg_t::warmup, and cg_t::warmupCount.
Referenced by CG_ConfigStringModified().
CG_PlayBufferedVoiceChats()
void CG_PlayBufferedVoiceChats (void)
Definition at line 733 of file cg_servercmds.c.
{
 }
Referenced by CG_DrawActiveFrame().
CG_PlayVoiceChat()
void CG_PlayVoiceChat (bufferedVoiceChat_t * vchat)
Definition at line 725 of file cg_servercmds.c.
{
 }
CG_RemoveChatEscapeChar()
static void CG_RemoveChatEscapeChar (char * text) static
Definition at line 765 of file cg_servercmds.c.
{
     int i, l;
     l = 0;
     for ( i = 0; text[i]; i++ ) {
         if (text[i] == '\x19')
             continue;
         text[l++] = text[i];
     }
     text[l] = '\0';
 }
Referenced by CG_ServerCommand().
CG_ServerCommand()
static void CG_ServerCommand (void) static
Definition at line 785 of file cg_servercmds.c.
{
     const char  *cmd;
     char        text[MAX_SAY_TEXT];
     cmd = CG_Argv(0);
     if ( !cmd[0] ) {
         // server claimed the command
         return;
     }
     if ( !strcmp( cmd, "cp" ) ) {
         CG_CenterPrint( CG_Argv(1), SCREEN_HEIGHT * 0.30, BIGCHAR_WIDTH );
         return;
     }
     if ( !strcmp( cmd, "cs" ) ) {
         CG_ConfigStringModified();
         return;
     }
     if ( !strcmp( cmd, "print" ) ) {
         CG_Printf( "%s", CG_Argv(1) );
         return;
     }
     if ( !strcmp( cmd, "chat" ) ) {
         if ( !cg_teamChatsOnly.integer ) {
             trap_S_StartLocalSound( cgs.media.talkSound, CHAN_LOCAL_SOUND );
             Q_strncpyz( text, CG_Argv(1), MAX_SAY_TEXT );
             CG_RemoveChatEscapeChar( text );
             CG_Printf( "%s\n", text );
             CG_DrawChat(text);
         }
         return;
     }
     if ( !strcmp( cmd, "tchat" ) ) {
         trap_S_StartLocalSound( cgs.media.talkSound, CHAN_LOCAL_SOUND );
         Q_strncpyz( text, CG_Argv(1), MAX_SAY_TEXT );
         CG_RemoveChatEscapeChar( text );
         CG_AddToTeamChat( text );
         CG_Printf( "%s\n", text );
         return;
     }
     if ( !strcmp( cmd, "vchat" ) ) {
         CG_VoiceChat( SAY_ALL );
         return;
     }
     if ( !strcmp( cmd, "vtchat" ) ) {
         CG_VoiceChat( SAY_TEAM );
         return;
     }
     if ( !strcmp( cmd, "vtell" ) ) {
         CG_VoiceChat( SAY_TELL );
         return;
     }
     if ( !strcmp( cmd, "scores" ) ) {
         CG_ParseScores();
         return;
     }
     if ( !strcmp( cmd, "tinfo" ) ) {
         CG_ParseTeamInfo();
         return;
     }
     if ( !strcmp( cmd, "map_restart" ) ) {
         CG_MapRestart();
         return;
     }
     if ( Q_stricmp (cmd, "remapShader") == 0 )
     {
         if (trap_Argc() == 4)
         {
             char shader1[MAX_QPATH];
             char shader2[MAX_QPATH];
             char shader3[MAX_QPATH];
             Q_strncpyz(shader1, CG_Argv(1), sizeof(shader1));
             Q_strncpyz(shader2, CG_Argv(2), sizeof(shader2));
             Q_strncpyz(shader3, CG_Argv(3), sizeof(shader3));
             trap_R_RemapShader(shader1, shader2, shader3);
         }
         return;
     }
     // loaddeferred can be both a servercmd and a consolecmd
     if ( !strcmp( cmd, "loaddefered" ) ) {  // FIXME: spelled wrong, but not changing for demo
         CG_LoadDeferredPlayers();
         return;
     }
     // clientLevelShot is sent before taking a special screenshot for
     // the menu system during development
     if ( !strcmp( cmd, "clientLevelShot" ) ) {
         cg.levelShot = qtrue;
         return;
     }
     if ( !strcmp( cmd, "radar" ) ) {
         int count;
         int i;
         const char *ptr;
         // expand the string into our settings
         // clear out old list
         memset( cg_playerOrigins, 0, sizeof(cg_playerOrigins) );
         // get amount in current list
         count = atof( CG_Argv( 1 ) );
         for( i = 0; i < count ; i++ ) {
             // set the string pointer to the correct set of parameters
             ptr = CG_Argv(i + 2);
             //read in the clientNum
             cg_playerOrigins[i].clientNum = atof(ptr);
             //move the ptr on until we come to a comma
             ptr = strchr(ptr, ',');
             //skip over the comma
             ptr++;
             //read in the PL
             cg_playerOrigins[i].pl = atof(ptr);
             //move the ptr on until we come to a comma
             ptr = strchr(ptr, ',');
             //skip over the comma
             ptr++;
             //read in the PLMax
             cg_playerOrigins[i].plMax = atof(ptr);
             //move the ptr on until we come to a comma
             ptr = strchr(ptr, ',');
             //skip over the comma
             ptr++;
             //read in the team
             cg_playerOrigins[i].team = atof(ptr);
             //move the ptr on until we come to a comma
             ptr = strchr(ptr, ',');
             //skip over the comma
             ptr++;
             //read in the properties
             cg_playerOrigins[i].properties = atof(ptr);
             //move the ptr on until we come to a comma
             ptr = strchr(ptr, ',');
             //skip over the comma
             ptr++;
             //read in the first position number
             cg_playerOrigins[i].pos[0] = atof(ptr);
             //move the ptr on until we come to a comma
             ptr = strchr(ptr, ',');
             //skip over the comma
             ptr++;
             //read in the next position number
             cg_playerOrigins[i].pos[1] = atof(ptr);
             //move the ptr on until we come to a comma
             ptr = strchr(ptr, ',');
             //skip over the comma
             ptr++;
             //read in the final position number
             cg_playerOrigins[i].pos[2] = atof(ptr);
             // Do a probability check on whether we're going to display the dot
             // or not.
             if ( qtrue ) {
                 //mark the entry as valid
                 cg_playerOrigins[i].valid = qtrue;
             } else {
                 cg_playerOrigins[i].valid = qfalse;
             }
         }
         return;
     }
     CG_Printf( "Unknown client game command: %s\n", cmd );
 }
References BIGCHAR_WIDTH, cg, CG_AddToTeamChat(), CG_Argv(), CG_CenterPrint(), CG_ConfigStringModified(), CG_DrawChat(), CG_LoadDeferredPlayers(), CG_MapRestart(), CG_ParseScores(), CG_ParseTeamInfo(), cg_playerOrigins, CG_Printf(), CG_RemoveChatEscapeChar(), cg_teamChatsOnly, CG_VoiceChat(), cgs, CHAN_LOCAL_SOUND, radar_t::clientNum, vmCvar_t::integer, cg_t::levelShot, MAX_QPATH, MAX_SAY_TEXT, cgs_t::media, radar_t::pl, radar_t::plMax, radar_t::pos, radar_t::properties, ptr(), Q_stricmp(), Q_strncpyz(), qfalse, qtrue, SAY_ALL, SAY_TEAM, SAY_TELL, SCREEN_HEIGHT, cgMedia_t::talkSound, radar_t::team, trap_Argc(), trap_R_RemapShader(), trap_S_StartLocalSound(), and radar_t::valid.
Referenced by CG_ExecuteNewServerCommands().
CG_SetConfigValues()
void CG_SetConfigValues (void)
Definition at line 180 of file cg_servercmds.c.
{
     const char *s;
     cgs.scores1 = atoi( CG_ConfigString( CS_SCORES1 ) );
     cgs.scores2 = atoi( CG_ConfigString( CS_SCORES2 ) );
     cgs.levelStartTime = atoi( CG_ConfigString( CS_LEVEL_START_TIME ) );
     if( cgs.gametype == GT_CTF ) {
         s = CG_ConfigString( CS_FLAGSTATUS );
         cgs.redflag = s[0] - '0';
         cgs.blueflag = s[1] - '0';
     }
     cg.warmup = atoi( CG_ConfigString( CS_WARMUP ) );
 }
References cgs_t::blueflag, cg, CG_ConfigString(), cgs, CS_FLAGSTATUS, CS_LEVEL_START_TIME, CS_SCORES1, CS_SCORES2, CS_WARMUP, cgs_t::gametype, GT_CTF, cgs_t::levelStartTime, cgs_t::redflag, cgs_t::scores1, cgs_t::scores2, and cg_t::warmup.
Referenced by CG_Init().
CG_ShaderStateChanged()
void CG_ShaderStateChanged (void)
Definition at line 199 of file cg_servercmds.c.
{
     char originalShader[MAX_QPATH];
     char newShader[MAX_QPATH];
     char timeOffset[16];
     const char *o;
     char *n,*t;
     o = CG_ConfigString( CS_SHADERSTATE );
     while (o && *o) {
         n = strstr(o, "=");
         if (n && *n) {
             strncpy(originalShader, o, n-o);
             originalShader[n-o] = 0;
             n++;
             t = strstr(n, ":");
             if (t && *t) {
                 strncpy(newShader, n, t-n);
                 newShader[t-n] = 0;
             } else {
                 break;
             }
             t++;
             o = strstr(t, "@");
             if (o) {
                 strncpy(timeOffset, t, o-t);
                 timeOffset[o-t] = 0;
                 o++;
                 trap_R_RemapShader( originalShader, newShader, timeOffset );
             }
         } else {
             break;
         }
     }
 }
References CG_ConfigString(), CS_SHADERSTATE, MAX_QPATH, and trap_R_RemapShader().
Referenced by CG_ConfigStringModified(), and CG_Init().
CG_VoiceChat()
void CG_VoiceChat (int mode)
Definition at line 757 of file cg_servercmds.c.
{
 }
Referenced by CG_ServerCommand().
CG_VoiceChatListForClient()
voiceChatList_t* CG_VoiceChatListForClient (int clientNum)
Definition at line 644 of file cg_servercmds.c.
{
     clientInfo_t *ci;
     int voiceChatNum, i, j, k;
     char filename[MAX_QPATH], headModelName[MAX_QPATH];
     if ( clientNum < 0 || clientNum >= MAX_CLIENTS ) {
         clientNum = 0;
     }
     ci = &cgs.clientinfo[ clientNum ];
     for ( k = 0; k < 2; k++ ) {
         if ( k == 0 ) {
             if (ci->headModelName[0] == '*') {
                 Com_sprintf( headModelName, sizeof(headModelName), "%s/%s", ci->headModelName+1, ci->headSkinName );
             }
             else {
                 Com_sprintf( headModelName, sizeof(headModelName), "%s/%s", ci->headModelName, ci->headSkinName );
             }
         }
         else {
             if (ci->headModelName[0] == '*') {
                 Com_sprintf( headModelName, sizeof(headModelName), "%s", ci->headModelName+1 );
             }
             else {
                 Com_sprintf( headModelName, sizeof(headModelName), "%s", ci->headModelName );
             }
         }
         // find the voice file for the head model the client uses
         for ( i = 0; i < MAX_HEADMODELS; i++ ) {
             if (!Q_stricmp(headModelVoiceChat[i].headmodel, headModelName)) {
                 break;
             }
         }
         if (i < MAX_HEADMODELS) {
             return &voiceChatLists[headModelVoiceChat[i].voiceChatNum];
         }
         // find a <headmodelname>.vc file
         for ( i = 0; i < MAX_HEADMODELS; i++ ) {
             if (!strlen(headModelVoiceChat[i].headmodel)) {
                 Com_sprintf(filename, sizeof(filename), "scripts/%s.vc", headModelName);
                 voiceChatNum = CG_HeadModelVoiceChats(filename);
                 if (voiceChatNum == -1)
                     break;
                 Com_sprintf(headModelVoiceChat[i].headmodel, sizeof ( headModelVoiceChat[i].headmodel ),
                             "%s", headModelName);
                 headModelVoiceChat[i].voiceChatNum = voiceChatNum;
                 return &voiceChatLists[headModelVoiceChat[i].voiceChatNum];
             }
         }
     }
     // store this head model with voice chat for future reference
     for ( j = 0; j < MAX_HEADMODELS; j++ ) {
         if (!strlen(headModelVoiceChat[j].headmodel)) {
             Com_sprintf(headModelVoiceChat[j].headmodel, sizeof ( headModelVoiceChat[j].headmodel ),
                     "%s", headModelName);
             headModelVoiceChat[j].voiceChatNum = 0;
             break;
         }
     }
     // just return the first voice chat list
     return &voiceChatLists[0];
 }
References CG_HeadModelVoiceChats(), cgs, cgs_t::clientinfo, Com_sprintf(), clientInfo_t::headModelName, headModelVoiceChat, clientInfo_t::headSkinName, MAX_CLIENTS, MAX_HEADMODELS, MAX_QPATH, Q_stricmp(), and voiceChatLists.
CG_VoiceChatLocal()
void CG_VoiceChatLocal (int mode, qboolean voiceOnly, int clientNum, int color, const char * cmd)
Definition at line 749 of file cg_servercmds.c.
{
 }
Variable Documentation
headModelVoiceChat
headModelVoiceChat_t headModelVoiceChat[MAX_HEADMODELS]
Definition at line 463 of file cg_servercmds.c.
Referenced by CG_VoiceChatListForClient().
numValidOrders
const int numValidOrders = ARRAY_LEN(validOrders) static
Definition at line 47 of file cg_servercmds.c.
validOrders
const orderTask_t validOrders[] static
Initial value:
= {
    { VOICECHAT_GETFLAG,            TEAMTASK_OFFENSE    },
    { VOICECHAT_OFFENSE,            TEAMTASK_OFFENSE    },
    { VOICECHAT_DEFEND,             TEAMTASK_DEFENSE    },
    { VOICECHAT_DEFENDFLAG,         TEAMTASK_DEFENSE    },
    { VOICECHAT_PATROL,             TEAMTASK_PATROL     },
    { VOICECHAT_CAMP,               TEAMTASK_CAMP       },
    { VOICECHAT_FOLLOWME,           TEAMTASK_FOLLOW     },
    { VOICECHAT_RETURNFLAG,         TEAMTASK_RETRIEVE   },
    { VOICECHAT_FOLLOWFLAGCARRIER,  TEAMTASK_ESCORT     }
}
Definition at line 35 of file cg_servercmds.c.
voiceChatBuffer
bufferedVoiceChat_t voiceChatBuffer[MAX_VOICECHATBUFFER]
Definition at line 718 of file cg_servercmds.c.
voiceChatLists
voiceChatList_t voiceChatLists[MAX_VOICEFILES]
Definition at line 462 of file cg_servercmds.c.
Referenced by CG_HeadModelVoiceChats(), CG_LoadVoiceChats(), and CG_VoiceChatListForClient().