ZEQ2-Lite: __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator > Class Template Reference
__gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator > Class Template Reference
class description = "8i|\|4ree $34rc|-| 7r33 74813.">
#include <bin_search_tree_.hpp>
Data Structures
struct entry
Public Types
enum { store_hash = Store_Hash }
enum { store_hash = Store_Hash }
typedef Allocator allocator_type
typedef Allocator allocator_type
typedef Allocator allocator_type
typedef Allocator allocator_type
typedef Allocator allocator_type
typedef Allocator allocator_type
typedef Allocator allocator_type
typedef Cmp_Fn cmp_fn
typedef Cmp_Fn cmp_fn
typedef Cmp_Fn cmp_fn
typedef Comb_Hash_Fn comb_hash_fn
typedef Comb_Probe_Fn comb_probe_fn
typedef base_type::const_iterator const_iterator
typedef base_type::const_iterator const_iterator
typedef const_point_iterator const_iterator
typedef const_iterator_ const_iterator
typedef const_iterator_ const_iterator
typedef const_iterator_ const_iterator
typedef const_point_iterator const_iterator
typedef base_type::const_key_pointer const_key_pointer
typedef base_type::const_key_pointer const_key_pointer
typedef traits_base::const_key_pointer const_key_pointer
typedef traits_base::const_key_pointer const_key_pointer
typedef PB_DS_TYPES_TRAITS_C_DEC::const_key_pointer const_key_pointer
typedef traits_base::const_key_pointer const_key_pointer
typedef traits_base::const_key_pointer const_key_pointer
typedef base_type::const_key_reference const_key_reference
typedef base_type::const_key_reference const_key_reference
typedef traits_base::const_key_reference const_key_reference
typedef traits_base::const_key_reference const_key_reference
typedef PB_DS_TYPES_TRAITS_C_DEC::const_key_reference const_key_reference
typedef traits_base::const_key_reference const_key_reference
typedef traits_base::const_key_reference const_key_reference
typedef base_type::const_mapped_pointer const_mapped_pointer
typedef base_type::const_mapped_pointer const_mapped_pointer
typedef traits_base::const_mapped_pointer const_mapped_pointer
typedef traits_base::const_mapped_pointer const_mapped_pointer
typedef traits_base::const_mapped_pointer const_mapped_pointer
typedef traits_base::const_mapped_pointer const_mapped_pointer
typedef base_type::const_mapped_reference const_mapped_reference
typedef base_type::const_mapped_reference const_mapped_reference
typedef traits_base::const_mapped_reference const_mapped_reference
typedef traits_base::const_mapped_reference const_mapped_reference
typedef traits_base::const_mapped_reference const_mapped_reference
typedef traits_base::const_mapped_reference const_mapped_reference
typedef Node_And_It_Traits::const_node_iterator const_node_iterator
typedef Node_And_It_Traits::const_node_iterator const_node_iterator
typedef base_type::const_iterator const_point_iterator
typedef base_type::const_iterator const_point_iterator
typedef const_point_iterator_ const_point_iterator
typedef Node_And_It_Traits::const_iterator const_point_iterator
typedef const_point_iterator_ const_point_iterator
typedef const_point_iterator_ const_point_iterator
typedef Node_And_It_Traits::const_point_iterator const_point_iterator
typedef base_type::const_pointer const_pointer
typedef base_type::const_pointer const_pointer
typedef traits_base::const_pointer const_pointer
typedef traits_base::const_pointer const_pointer
typedef traits_base::const_pointer const_pointer
typedef traits_base::const_pointer const_pointer
typedef PB_DS_TYPES_TRAITS_C_DEC::const_pointer const_pointer
typedef base_type::const_reference const_reference
typedef base_type::const_reference const_reference
typedef traits_base::const_reference const_reference
typedef traits_base::const_reference const_reference
typedef traits_base::const_reference const_reference
typedef traits_base::const_reference const_reference
typedef PB_DS_TYPES_TRAITS_C_DEC::const_reference const_reference
typedef base_type::const_reverse_iterator const_reverse_iterator
typedef base_type::const_reverse_iterator const_reverse_iterator
typedef Node_And_It_Traits::const_reverse_iterator const_reverse_iterator
typedef Node_And_It_Traits::const_reverse_iterator const_reverse_iterator
typedef pat_trie_tag container_category
typedef Allocator::difference_type difference_type
typedef Allocator::difference_type difference_type
typedef Allocator::difference_type difference_type
typedef Allocator::difference_type difference_type
typedef Allocator::difference_type difference_type
typedef Allocator::difference_type difference_type
typedef Allocator::difference_type difference_type
typedef Node_And_It_Traits::e_access_traits e_access_traits
typedef Eq_Fn eq_fn
typedef Eq_Fn eq_fn
typedef Eq_Fn eq_fn
typedef Hash_Fn hash_fn
typedef Hash_Fn hash_fn
typedef base_type::iterator iterator
typedef base_type::iterator iterator
typedef point_iterator iterator
typedef point_iterator iterator
typedef base_type::key_pointer key_pointer
typedef base_type::key_pointer key_pointer
typedef traits_base::key_pointer key_pointer
typedef traits_base::key_pointer key_pointer
typedef PB_DS_TYPES_TRAITS_C_DEC::key_pointer key_pointer
typedef traits_base::key_pointer key_pointer
typedef traits_base::key_pointer key_pointer
typedef base_type::key_reference key_reference
typedef base_type::key_reference key_reference
typedef traits_base::key_reference key_reference
typedef traits_base::key_reference key_reference
typedef PB_DS_TYPES_TRAITS_C_DEC::key_reference key_reference
typedef traits_base::key_reference key_reference
typedef traits_base::key_reference key_reference
typedef base_type::key_type key_type
typedef base_type::key_type key_type
typedef traits_base::key_type key_type
typedef traits_base::key_type key_type
typedef PB_DS_TYPES_TRAITS_C_DEC::key_type key_type
typedef traits_base::key_type key_type
typedef traits_base::key_type key_type
typedef base_type::mapped_pointer mapped_pointer
typedef base_type::mapped_pointer mapped_pointer
typedef traits_base::mapped_pointer mapped_pointer
typedef traits_base::mapped_pointer mapped_pointer
typedef traits_base::mapped_pointer mapped_pointer
typedef traits_base::mapped_pointer mapped_pointer
typedef base_type::mapped_reference mapped_reference
typedef base_type::mapped_reference mapped_reference
typedef traits_base::mapped_reference mapped_reference
typedef traits_base::mapped_reference mapped_reference
typedef traits_base::mapped_reference mapped_reference
typedef traits_base::mapped_reference mapped_reference
typedef base_type::mapped_type mapped_type
typedef base_type::mapped_type mapped_type
typedef traits_base::mapped_type mapped_type
typedef traits_base::mapped_type mapped_type
typedef traits_base::mapped_type mapped_type
typedef traits_base::mapped_type mapped_type
typedef Node_And_It_Traits::node_iterator node_iterator
typedef Node_And_It_Traits::node_iterator node_iterator
typedef base_type::node_update node_update
typedef base_type::node_update node_update
typedef Node_And_It_Traits::node_update node_update
typedef Node_And_It_Traits::node_update node_update
typedef base_type::point_iterator point_iterator
typedef base_type::point_iterator point_iterator
typedef Node_And_It_Traits::iterator point_iterator
typedef Node_And_It_Traits::point_iterator point_iterator
typedef base_type::pointer pointer
typedef base_type::pointer pointer
typedef traits_base::pointer pointer
typedef traits_base::pointer pointer
typedef traits_base::pointer pointer
typedef traits_base::pointer pointer
typedef PB_DS_TYPES_TRAITS_C_DEC::pointer pointer
typedef Probe_Fn probe_fn
typedef base_type::reference reference
typedef base_type::reference reference
typedef traits_base::reference reference
typedef traits_base::reference reference
typedef traits_base::reference reference
typedef traits_base::reference reference
typedef PB_DS_TYPES_TRAITS_C_DEC::reference reference
typedef Resize_Policy resize_policy
typedef Resize_Policy resize_policy
typedef base_type::reverse_iterator reverse_iterator
typedef base_type::reverse_iterator reverse_iterator
typedef Node_And_It_Traits::reverse_iterator reverse_iterator
typedef Node_And_It_Traits::reverse_iterator reverse_iterator
typedef Allocator::size_type size_type
typedef Allocator::size_type size_type
typedef Allocator::size_type size_type
typedef Allocator::size_type size_type
typedef Allocator::size_type size_type
typedef Allocator::size_type size_type
typedef Allocator::size_type size_type
typedef Update_Policy::metadata_type update_metadata
typedef Update_Policy update_policy
typedef base_type::value_type value_type
typedef base_type::value_type value_type
typedef traits_base::value_type value_type
typedef traits_base::value_type value_type
typedef traits_base::value_type value_type
typedef traits_base::value_type value_type
typedef PB_DS_TYPES_TRAITS_C_DEC::value_type value_type
Public Member Functions
PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME (const Cmp_Fn &)
PB_DS_CLASS_NAME (const Cmp_Fn &)
PB_DS_CLASS_NAME (const Cmp_Fn &, const node_update &)
PB_DS_CLASS_NAME (const Cmp_Fn &, const node_update &)
PB_DS_CLASS_NAME (const Cmp_Fn &r_cmp_fn)
PB_DS_CLASS_NAME (const Cmp_Fn &r_cmp_fn, const node_update &r_update)
PB_DS_CLASS_NAME (const e_access_traits &)
PB_DS_CLASS_NAME (const Hash_Fn &)
PB_DS_CLASS_NAME (const Hash_Fn &)
PB_DS_CLASS_NAME (const Hash_Fn &, const Eq_Fn &)
PB_DS_CLASS_NAME (const Hash_Fn &, const Eq_Fn &)
PB_DS_CLASS_NAME (const Hash_Fn &, const Eq_Fn &, const Comb_Hash_Fn &)
PB_DS_CLASS_NAME (const Hash_Fn &, const Eq_Fn &, const Comb_Hash_Fn &, const Resize_Policy &)
PB_DS_CLASS_NAME (const Hash_Fn &, const Eq_Fn &, const Comb_Probe_Fn &)
PB_DS_CLASS_NAME (const Hash_Fn &, const Eq_Fn &, const Comb_Probe_Fn &, const Probe_Fn &)
PB_DS_CLASS_NAME (const Hash_Fn &, const Eq_Fn &, const Comb_Probe_Fn &, const Probe_Fn &, const Resize_Policy &)
PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &other)
template<typename It >
PB_DS_CLASS_NAME (It first_it, It last_it)
virtual ~PB_DS_CLASS_NAME ()
~PB_DS_CLASS_NAME ()
virtual ~PB_DS_CLASS_NAME ()
virtual ~PB_DS_CLASS_NAME ()
~PB_DS_CLASS_NAME ()
iterator begin ()
iterator begin ()
iterator begin ()
iterator begin ()
iterator begin ()
const_iterator begin () const
const_iterator begin () const
const_iterator begin () const
const_iterator begin () const
const_iterator begin () const
void clear ()
void clear ()
void clear ()
void clear ()
void clear ()
template<typename It >
void copy_from_range (It first_it, It last_it)
template<typename It >
void copy_from_range (It, It)
template<typename It >
void copy_from_range (It, It)
template<typename It >
void copy_from_range (It, It)
bool empty () const
bool empty () const
bool empty () const
bool empty () const
bool empty () const
iterator end ()
iterator end ()
iterator end ()
iterator end ()
iterator end ()
const_iterator end () const
const_iterator end () const
const_iterator end () const
const_iterator end () const
const_iterator end () const
const_iterator erase (const_iterator)
bool erase (const_key_reference r_key)
bool erase (const_key_reference)
bool erase (const_key_reference)
bool erase (const_key_reference)
bool erase (const_key_reference)
bool erase (const_key_reference)
const_reverse_iterator erase (const_reverse_iterator)
iterator erase (iterator it)
iterator erase (iterator)
reverse_iterator erase (reverse_iterator)
reverse_iterator erase (reverse_iterator)
template<typename Pred >
size_type erase_if (Pred prd)
template<typename Pred >
size_type erase_if (Pred)
template<typename Pred >
size_type erase_if (Pred)
template<typename Pred >
size_type erase_if (Pred)
template<typename Pred >
size_type erase_if (Pred)
template<typename Pred >
size_type erase_if (Pred)
point_iterator find (const_key_reference r_key)
point_iterator find (const_key_reference r_key)
point_iterator find (const_key_reference r_key)
const_point_iterator find (const_key_reference r_key) const
const_point_iterator find (const_key_reference r_key) const
const_point_iterator find (const_key_reference r_key) const
point_iterator find (const_key_reference)
point_iterator find (const_key_reference)
point_iterator find (const_key_reference)
const_point_iterator find (const_key_reference) const
const_point_iterator find (const_key_reference) const
const_point_iterator find (const_key_reference) const
point_iterator find_end ()
point_iterator find_end ()
const_point_iterator find_end () const
const_point_iterator find_end () const
Cmp_Fn & get_cmp_fn ()
const Cmp_Fn & get_cmp_fn () const
Comb_Hash_Fn & get_comb_hash_fn ()
const Comb_Hash_Fn & get_comb_hash_fn () const
Comb_Probe_Fn & get_comb_probe_fn ()
const Comb_Probe_Fn & get_comb_probe_fn () const
e_access_traits & get_e_access_traits ()
const e_access_traits & get_e_access_traits () const
Eq_Fn & get_eq_fn ()
Eq_Fn & get_eq_fn ()
const Eq_Fn & get_eq_fn () const
const Eq_Fn & get_eq_fn () const
Hash_Fn & get_hash_fn ()
Hash_Fn & get_hash_fn ()
const Hash_Fn & get_hash_fn () const
const Hash_Fn & get_hash_fn () const
node_update & get_node_update ()
const node_update & get_node_update () const
Probe_Fn & get_probe_fn ()
const Probe_Fn & get_probe_fn () const
Resize_Policy & get_resize_policy ()
Resize_Policy & get_resize_policy ()
const Resize_Policy & get_resize_policy () const
const Resize_Policy & get_resize_policy () const
void initialize ()
void initialize ()
std::pair< point_iterator, bool > insert (const_reference r_val)
std::pair< point_iterator, bool > insert (const_reference r_val)
std::pair< point_iterator, bool > insert (const_reference r_value)
std::pair< point_iterator, bool > insert (const_reference)
std::pair< point_iterator, bool > insert (const_reference)
std::pair< point_iterator, bool > insert (const_reference)
void join (PB_DS_CLASS_C_DEC &)
void join (PB_DS_CLASS_C_DEC &)
void join (PB_DS_CLASS_C_DEC &)
point_iterator lower_bound (const_key_reference r_key)
const_point_iterator lower_bound (const_key_reference r_key) const
point_iterator lower_bound (const_key_reference)
const_point_iterator lower_bound (const_key_reference) const
size_type max_size () const
size_type max_size () const
size_type max_size () const
size_type max_size () const
size_type max_size () const
node_iterator node_begin ()
node_iterator node_begin ()
const_node_iterator node_begin () const
const_node_iterator node_begin () const
node_iterator node_end ()
node_iterator node_end ()
const_node_iterator node_end () const
const_node_iterator node_end () const
mapped_reference operator[] (const_key_reference r_key)
mapped_reference operator[] (const_key_reference r_key)
mapped_reference operator[] (const_key_reference r_key)
mapped_reference operator[] (const_key_reference r_key)
mapped_reference operator[] (const_key_reference r_key)
mapped_reference operator[] (const_key_reference r_key)
reverse_iterator rbegin ()
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator rbegin () const
reverse_iterator rend ()
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator rend () const
size_type size () const
size_type size () const
size_type size () const
size_type size () const
size_type size () const
void split (const_key_reference, PB_DS_CLASS_C_DEC &)
void split (const_key_reference, PB_DS_CLASS_C_DEC &)
void split (const_key_reference, PB_DS_CLASS_C_DEC &)
void swap (PB_DS_CLASS_C_DEC &)
void swap (PB_DS_CLASS_C_DEC &)
void swap (PB_DS_CLASS_C_DEC &)
void swap (PB_DS_CLASS_C_DEC &)
void swap (PB_DS_CLASS_C_DEC &)
void swap (PB_DS_CLASS_C_DEC &other)
void swap (PB_DS_CLASS_C_DEC &other)
point_iterator upper_bound (const_key_reference r_key)
const_point_iterator upper_bound (const_key_reference r_key) const
point_iterator upper_bound (const_key_reference)
const_point_iterator upper_bound (const_key_reference) const
Protected Types
typedef node_allocator::value_type node
typedef Allocator::template rebind< typename Node_And_It_Traits::node >::other node_allocator
typedef node_allocator::pointer node_pointer
typedef Node_And_It_Traits::null_node_update_pointer null_node_update_pointer
typedef PB_DS_TYPES_TRAITS_C_DEC traits_base
Protected Member Functions
void actual_erase_node (node_pointer p_nd)
template<typename Node_Update_ >
void apply_update (node_pointer p_nd, Node_Update_ *p_update)
void apply_update (node_pointer p_nd, null_node_update_pointer)
template<typename It >
void copy_from_range (It, It)
template<typename It >
void copy_from_range (It, It)
std::pair< node_pointer, bool > erase (node_pointer p_nd)
node_pointer get_new_node_for_leaf_insert (const_reference r_val, false_type)
node_pointer get_new_node_for_leaf_insert (const_reference r_val, true_type)
void initialize_min_max ()
iterator insert_imp_empty (const_reference r_value)
std::pair< point_iterator, bool > insert_leaf (const_reference r_value)
iterator insert_leaf_new (const_reference r_value, node_pointer p_nd, bool left_nd)
void join_finish (PB_DS_CLASS_C_DEC &other)
bool join_prep (PB_DS_CLASS_C_DEC &other)
node_pointer recursive_copy_node (const_node_pointer)
size_type recursive_count (node_pointer p_nd) const
void rotate_left (node_pointer p_x)
void rotate_parent (node_pointer p_nd)
void rotate_right (node_pointer p_y)
void split_finish (PB_DS_CLASS_C_DEC &other)
bool split_prep (const_key_reference r_key, PB_DS_CLASS_C_DEC &other)
void update_min_max_for_erased_node (node_pointer p_nd)
template<typename Node_Update_ >
void update_to_top (node_pointer p_nd, Node_Update_ *p_update)
void update_to_top (node_pointer p_nd, null_node_update_pointer)
void value_swap (PB_DS_CLASS_C_DEC &)
void value_swap (PB_DS_CLASS_C_DEC &other)
Static Protected Member Functions
static void clear_imp (node_pointer p_nd)
Protected Attributes
node_pointer m_p_head
size_type m_size
Static Protected Attributes
static node_allocator s_node_allocator
Private Types
enum { store_hash_ok }
enum { store_hash_ok }
typedef PB_DS_BASE_C_DEC base_type
typedef PB_DS_BASE_C_DEC base_type
typedef traits_base::comp_hash comp_hash
typedef traits_base::comp_hash comp_hash
typedef cond_dealtor< entry, Allocator > cond_dealtor_t
typedef cond_dealtor< entry, Allocator > cond_dealtor_t
typedef cond_dealtor< node, Allocator > cond_dealtor_t
typedef Allocator::template rebind< synth_e_access_traits >::other::const_pointer const_e_access_traits_pointer
typedef synth_e_access_traits::const_iterator const_e_iterator
typedef entry_allocator::const_pointer const_entry_pointer
typedef entry_allocator::const_pointer const_entry_pointer
typedef entry_allocator::const_pointer const_entry_pointer
typedef entry_allocator::const_reference const_entry_reference
typedef entry_allocator::const_reference const_entry_reference
typedef entry_allocator::const_reference const_entry_reference
typedef internal_node_allocator::const_pointer const_internal_node_pointer
typedef leaf_allocator::const_pointer const_leaf_pointer
typedef Allocator::template rebind< node >::other::const_pointer const_node_pointer
typedef traits_base::const_pointer const_pointer_
typedef traits_base::const_pointer const_pointer_
typedef traits_base::const_pointer const_pointer_
typedef traits_base::const_reference const_reference_
typedef traits_base::const_reference const_reference_
typedef traits_base::const_reference const_reference_
typedef Allocator::template rebind< entry >::other entry_allocator
typedef Allocator::template rebind< entry >::other entry_allocator
typedef Allocator::template rebind< entry >::other entry_allocator
typedef entry_allocator::pointer entry_array
typedef entry_allocator::pointer entry_pointer
typedef entry_allocator::pointer entry_pointer
typedef entry_allocator::pointer entry_pointer
typedef Allocator::template rebind< entry_pointer >::other entry_pointer_allocator
typedef Allocator::template rebind< entry_pointer >::other entry_pointer_allocator
typedef entry_pointer_allocator::pointer entry_pointer_array
typedef entry_pointer_allocator::pointer entry_pointer_array
typedef entry_allocator::reference entry_reference
typedef entry_allocator::reference entry_reference
typedef entry_allocator::reference entry_reference
enum entry_status { empty_entry_status, valid_entry_status, erased_entry_status }
typedef PB_DS_HASH_EQ_FN_C_DEC hash_eq_fn_base
typedef PB_DS_HASH_EQ_FN_C_DEC hash_eq_fn_base
typedef Node_And_It_Traits::head head
typedef Allocator::template rebind< head >::other head_allocator
typedef head_allocator::pointer head_pointer
typedef Node_And_It_Traits::internal_node internal_node
typedef Allocator::template rebind< internal_node >::other internal_node_allocator
typedef internal_node_allocator::pointer internal_node_pointer
typedef Node_And_It_Traits::leaf leaf
typedef Allocator::template rebind< leaf >::other leaf_allocator
typedef leaf_allocator::pointer leaf_pointer
typedef Node_And_It_Traits::node node
typedef base_type::node_pointer node_pointer
typedef Allocator::template rebind< node >::other::pointer node_pointer
typedef base_type::node_pointer node_pointer
typedef Node_And_It_Traits::null_node_update_pointer null_node_update_pointer
typedef traits_base::pointer pointer_
typedef traits_base::pointer pointer_
typedef traits_base::pointer pointer_
typedef PB_DS_RANGED_HASH_FN_C_DEC ranged_hash_fn_base
typedef PB_DS_RANGED_PROBE_FN_C_DEC ranged_probe_fn_base
typedef traits_base::reference reference_
typedef traits_base::reference reference_
typedef traits_base::reference reference_
typedef Resize_Policy resize_base
typedef Resize_Policy resize_base
typedef Node_And_It_Traits::synth_e_access_traits synth_e_access_traits
typedef PB_DS_TYPES_TRAITS_C_DEC traits_base
typedef PB_DS_TYPES_TRAITS_C_DEC traits_base
typedef PB_DS_TYPES_TRAITS_C_DEC traits_base
typedef PB_DS_TYPES_TRAITS_C_DEC traits_base
typedef traits_base::value_type value_type_
typedef traits_base::value_type value_type_
typedef traits_base::value_type value_type_
Private Member Functions
template<typename Key , typename Mapped , typename Hash_Fn , typename Eq_Fn , typename Allocator , bool Store_Hash, typename Comb_Probe_Fn , typename Probe_Fn , typename Resize_Policy >
enum __gnu_pbds::detail::PB_DS_CLASS_NAME::entry_status __attribute__ ((packed))
void actual_erase_entry (entry_pointer)
void actual_erase_leaf (leaf_pointer)
entry_pointer allocate_new_entry (const_reference, false_type)
entry_pointer allocate_new_entry (const_reference, true_type)
template<typename Node_Update_ >
void apply_update (node_pointer, Node_Update_ *)
void apply_update (node_pointer, null_node_update_pointer)
size_type black_height (node_pointer)
void clear_imp (node_pointer)
void deallocate_all ()
void deallocate_all ()
void deallocate_all ()
void deallocate_links_in_list (entry_pointer)
void do_resize (size_type new_size)
virtual void do_resize (size_type)
bool do_resize_if_needed ()
bool do_resize_if_needed ()
void do_resize_if_needed_no_throw ()
void do_resize_if_needed_no_throw ()
void erase_all_valid_entries (entry_array, size_type)
void erase_entry (entry_pointer p_e)
void erase_entry_pointer (entry_pointer &)
void erase_fixup (internal_node_pointer)
bool erase_imp (const_key_reference, false_type)
bool erase_imp (const_key_reference, true_type)
bool erase_in_pos_imp (const_key_reference, const comp_hash &)
bool erase_in_pos_imp (const_key_reference, size_type)
void erase_leaf (leaf_pointer)
void erase_next (entry_pointer)
void erase_node (node_pointer)
void erase_node (node_pointer)
node_pointer find_imp (const_key_reference)
node_pointer find_imp (const_key_reference)
const node_pointer find_imp (const_key_reference) const
entry_pointer find_imp (const_key_reference) const
size_type find_ins_pos (const_key_reference, false_type)
comp_hash find_ins_pos (const_key_reference, true_type)
std::pair< node_pointer, node_pointer > find_join_pos_left (node_pointer, size_type, size_type)
std::pair< node_pointer, node_pointer > find_join_pos_right (node_pointer, size_type, size_type)
pointer find_key_pointer (const_key_reference key, false_type)
pointer find_key_pointer (const_key_reference key, true_type)
pointer find_key_pointer (const_key_reference r_key, false_type)
pointer find_key_pointer (const_key_reference r_key, true_type)
entry_pointer get_entry (const_reference, false_type)
entry_pointer get_entry (const_reference, true_type)
void get_start_it_state (const_pointer &r_p_value, size_type &r_pos) const
void get_start_it_state (pointer &r_p_value, size_type &r_pos)
void get_start_it_state (pointer &r_p_value, std::pair< entry_pointer, size_type > &r_pos) const
void inc_it_state (const_pointer &r_p_value, entry_pointer &r_pos) const
void inc_it_state (const_pointer &r_p_value, size_type &r_pos) const
void inc_it_state (const_pointer &r_p_value, std::pair< entry_pointer, size_type > &r_pos) const
void initialize ()
void initialize ()
void initialize ()
void initialize ()
internal_node_pointer insert_branch (node_pointer, node_pointer, split_join_branch_bag &)
void insert_fixup (node_pointer)
std::pair< point_iterator, bool > insert_imp (const_reference, false_type)
std::pair< point_iterator, bool > insert_imp (const_reference, false_type)
std::pair< point_iterator, bool > insert_imp (const_reference, true_type)
std::pair< point_iterator, bool > insert_imp (const_reference, true_type)
std::pair< point_iterator, bool > insert_leaf_imp (const_reference)
pointer insert_new_imp (const_reference r_val, comp_hash &r_pos_hash_pair)
pointer insert_new_imp (const_reference r_val, comp_hash &r_pos_hash_pair)
pointer insert_new_imp (const_reference r_val, size_type pos)
pointer insert_new_imp (const_reference r_val, size_type pos)
void join_imp (node_pointer, node_pointer)
bool join_prep (PB_DS_CLASS_C_DEC &, split_join_branch_bag &)
size_type keys_diff_ind (typename e_access_traits::const_iterator, typename e_access_traits::const_iterator, typename e_access_traits::const_iterator, typename e_access_traits::const_iterator)
node_pointer leftmost (node_pointer)
node_pointer lower_bound_imp (const_key_reference)
PB_DS_STATIC_ASSERT (sth, store_hash_ok)
PB_DS_STATIC_ASSERT (sth, store_hash_ok)
node_pointer rec_join (internal_node_pointer, internal_node_pointer, split_join_branch_bag &)
node_pointer rec_join (internal_node_pointer, leaf_pointer, size_type, split_join_branch_bag &)
node_pointer rec_join (leaf_pointer, internal_node_pointer, size_type, split_join_branch_bag &)
node_pointer rec_join (leaf_pointer, leaf_pointer, split_join_branch_bag &)
node_pointer rec_join (node_pointer, node_pointer, size_type, split_join_branch_bag &)
void rec_join_prep (const_internal_node_pointer, const_internal_node_pointer, split_join_branch_bag &)
void rec_join_prep (const_internal_node_pointer, const_leaf_pointer, split_join_branch_bag &)
void rec_join_prep (const_leaf_pointer, const_internal_node_pointer, split_join_branch_bag &)
void rec_join_prep (const_leaf_pointer, const_leaf_pointer, split_join_branch_bag &)
void rec_join_prep (const_node_pointer, const_node_pointer, split_join_branch_bag &)
node_pointer rec_split (node_pointer, const_e_iterator, const_e_iterator, PB_DS_CLASS_C_DEC &, split_join_branch_bag &)
node_pointer recursive_copy_node (const node_pointer p_nd)
void rels_entry (entry_pointer)
void remove_fixup (node_pointer, node_pointer)
void remove_node (node_pointer)
void resize_imp (entry_array, size_type)
void resize_imp (size_type new_size)
void resize_imp (size_type)
void resize_imp_no_exceptions (size_type, entry_pointer_array, size_type)
entry_pointer resize_imp_no_exceptions_reassign_pointer (entry_pointer, entry_pointer_array, false_type)
entry_pointer resize_imp_no_exceptions_reassign_pointer (entry_pointer, entry_pointer_array, true_type)
void resize_imp_reassign (entry_pointer, entry_array, false_type)
void resize_imp_reassign (entry_pointer, entry_array, true_type)
void splay (node_pointer)
void splay_zig_zag_left (node_pointer, node_pointer, node_pointer)
void splay_zig_zag_right (node_pointer, node_pointer, node_pointer)
void splay_zig_zig_left (node_pointer, node_pointer, node_pointer)
void splay_zig_zig_right (node_pointer, node_pointer, node_pointer)
void splay_zz_end (node_pointer, node_pointer, node_pointer)
void splay_zz_start (node_pointer, node_pointer, node_pointer)
void split_at_node (node_pointer, PB_DS_CLASS_C_DEC &)
void split_imp (node_pointer, PB_DS_CLASS_C_DEC &)
void split_insert_branch (size_type, const_e_iterator, typename internal_node::iterator, size_type, split_join_branch_bag &)
node_pointer split_min ()
std::pair< node_pointer, node_pointer > split_min_imp ()
leaf_pointer split_prep (const_key_reference, PB_DS_CLASS_C_DEC &, split_join_branch_bag &)
void update_min_max_for_erased_leaf (leaf_pointer)
void update_min_max_for_inserted_leaf (leaf_pointer)
node_pointer upper_bound_imp (const_key_reference)
Static Private Member Functions
template<typename Metadata >
static bool apply_update (entry_pointer, type_to_type< Metadata >)
static bool apply_update (entry_pointer, type_to_type< null_lu_metadata >)
template<typename Metadata >
static void init_entry_metadata (entry_pointer, type_to_type< Metadata >)
static void init_entry_metadata (entry_pointer, type_to_type< null_lu_metadata >)
static bool is_effectively_black (const node_pointer)
static const_leaf_pointer leftmost_descendant (const_node_pointer)
static leaf_pointer leftmost_descendant (node_pointer)
static const_e_iterator pref_begin (const_node_pointer)
static const_e_iterator pref_end (const_node_pointer)
static const_leaf_pointer rightmost_descendant (const_node_pointer)
static leaf_pointer rightmost_descendant (node_pointer)
Private Attributes
__gnu_pbds::detail::PB_DS_CLASS_NAME::entry __attribute__
entry_pointer_array m_entries
entry_pointer m_entries
size_type m_num_e
size_type m_num_used_e
head_pointer m_p_head
entry_pointer m_p_l
Static Private Attributes
static const_iterator s_const_end_it
static const_point_iterator s_const_find_end_it
static iterator s_end_it
static entry_allocator s_entry_allocator
static entry_pointer_allocator s_entry_pointer_allocator
static Eq_Fn s_eq_fn
static point_iterator s_find_end_it
static head_allocator s_head_allocator
static internal_node_allocator s_internal_node_allocator
static leaf_allocator s_leaf_allocator
static type_to_type< update_metadata > s_metadata_type_indicator
static null_lu_metadata s_null_lu_metadata
static Update_Policy s_update_policy
Friends
class const_iterator_
Detailed Description
template<typename Key, typename Mapped, class Cmp_Fn, class Node_And_It_Traits, class Allocator>
class __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >
class description = "8i|\|4ree $34rc|-| 7r33 74813.">
class description = PATRICIA trie implementation.
">
Definition at line 127 of file bin_search_tree_.hpp.
Member Typedef Documentation
allocator_type [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocator_type
Definition at line 121 of file rb_tree_.hpp.
allocator_type [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocator_type
Definition at line 142 of file splay_tree_.hpp.
allocator_type [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocator_type
Definition at line 151 of file lu_map_.hpp.
allocator_type [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocator_type
Definition at line 161 of file pat_trie_.hpp.
allocator_type [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocator_type
Definition at line 164 of file cc_ht_map_.hpp.
allocator_type [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocator_type
Definition at line 165 of file gp_ht_map_.hpp.
allocator_type [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocator_type
Definition at line 238 of file bin_search_tree_.hpp.
base_type [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_BASE_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::base_type private
Definition at line 116 of file rb_tree_.hpp.
base_type [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_BASE_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::base_type private
Definition at line 138 of file splay_tree_.hpp.
cmp_fn [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Cmp_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::cmp_fn
Definition at line 120 of file rb_tree_.hpp.
cmp_fn [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Cmp_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::cmp_fn
Definition at line 145 of file splay_tree_.hpp.
cmp_fn [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Cmp_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::cmp_fn
Definition at line 236 of file bin_search_tree_.hpp.
comb_hash_fn
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Comb_Hash_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::comb_hash_fn
Definition at line 169 of file cc_ht_map_.hpp.
comb_probe_fn
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Comb_Probe_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::comb_probe_fn
Definition at line 171 of file gp_ht_map_.hpp.
comp_hash [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::comp_hash __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::comp_hash private
Definition at line 123 of file cc_ht_map_.hpp.
comp_hash [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::comp_hash __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::comp_hash private
Definition at line 125 of file gp_ht_map_.hpp.
cond_dealtor_t [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef cond_dealtor<entry, Allocator> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::cond_dealtor_t private
Definition at line 135 of file cc_ht_map_.hpp.
cond_dealtor_t [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef cond_dealtor<entry, Allocator> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::cond_dealtor_t private
Definition at line 148 of file lu_map_.hpp.
cond_dealtor_t [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef cond_dealtor< node, Allocator> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::cond_dealtor_t private
Definition at line 156 of file bin_search_tree_.hpp.
const_e_access_traits_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<synth_e_access_traits>::other::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_e_access_traits_pointer private
Definition at line 127 of file pat_trie_.hpp.
const_e_iterator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef synth_e_access_traits::const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_e_iterator private
Definition at line 128 of file pat_trie_.hpp.
const_entry_pointer [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_entry_pointer private
Definition at line 121 of file lu_map_.hpp.
const_entry_pointer [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_entry_pointer private
Definition at line 139 of file cc_ht_map_.hpp.
const_entry_pointer [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_entry_pointer private
Definition at line 141 of file gp_ht_map_.hpp.
const_entry_reference [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_entry_reference private
Definition at line 123 of file lu_map_.hpp.
const_entry_reference [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_entry_reference private
Definition at line 141 of file cc_ht_map_.hpp.
const_entry_reference [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_entry_reference private
Definition at line 143 of file gp_ht_map_.hpp.
const_internal_node_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef internal_node_allocator::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_internal_node_pointer private
Definition at line 146 of file pat_trie_.hpp.
const_iterator [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_iterator
Definition at line 142 of file rb_tree_.hpp.
const_iterator [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_iterator
Definition at line 164 of file splay_tree_.hpp.
const_iterator [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_iterator
Definition at line 183 of file pat_trie_.hpp.
const_iterator [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_iterator_ __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_iterator
Definition at line 191 of file lu_map_.hpp.
const_iterator [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_iterator_ __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_iterator
Definition at line 211 of file cc_ht_map_.hpp.
const_iterator [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_iterator_ __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_iterator
Definition at line 213 of file gp_ht_map_.hpp.
const_iterator [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_iterator
Definition at line 218 of file bin_search_tree_.hpp.
const_key_pointer [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_pointer
Definition at line 126 of file rb_tree_.hpp.
const_key_pointer [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_pointer
Definition at line 148 of file splay_tree_.hpp.
const_key_pointer [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_pointer
Definition at line 159 of file lu_map_.hpp.
const_key_pointer [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_pointer
Definition at line 167 of file pat_trie_.hpp.
const_key_pointer [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::const_key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_pointer
Definition at line 174 of file bin_search_tree_.hpp.
const_key_pointer [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_pointer
Definition at line 179 of file cc_ht_map_.hpp.
const_key_pointer [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_pointer
Definition at line 181 of file gp_ht_map_.hpp.
const_key_reference [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_reference
Definition at line 128 of file rb_tree_.hpp.
const_key_reference [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_reference
Definition at line 150 of file splay_tree_.hpp.
const_key_reference [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_reference
Definition at line 161 of file lu_map_.hpp.
const_key_reference [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_reference
Definition at line 169 of file pat_trie_.hpp.
const_key_reference [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::const_key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_reference
Definition at line 180 of file bin_search_tree_.hpp.
const_key_reference [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_reference
Definition at line 181 of file cc_ht_map_.hpp.
const_key_reference [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_key_reference
Definition at line 183 of file gp_ht_map_.hpp.
const_leaf_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef leaf_allocator::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_leaf_pointer private
Definition at line 141 of file pat_trie_.hpp.
const_mapped_pointer [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_pointer
Definition at line 131 of file rb_tree_.hpp.
const_mapped_pointer [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_pointer
Definition at line 153 of file splay_tree_.hpp.
const_mapped_pointer [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_pointer
Definition at line 164 of file lu_map_.hpp.
const_mapped_pointer [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_pointer
Definition at line 172 of file pat_trie_.hpp.
const_mapped_pointer [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_pointer
Definition at line 184 of file cc_ht_map_.hpp.
const_mapped_pointer [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_pointer
Definition at line 186 of file gp_ht_map_.hpp.
const_mapped_reference [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_reference
Definition at line 133 of file rb_tree_.hpp.
const_mapped_reference [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_reference
Definition at line 155 of file splay_tree_.hpp.
const_mapped_reference [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_reference
Definition at line 166 of file lu_map_.hpp.
const_mapped_reference [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_reference
Definition at line 174 of file pat_trie_.hpp.
const_mapped_reference [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_reference
Definition at line 186 of file cc_ht_map_.hpp.
const_mapped_reference [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_mapped_reference
Definition at line 188 of file gp_ht_map_.hpp.
const_node_iterator [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::const_node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_node_iterator
Definition at line 188 of file pat_trie_.hpp.
const_node_iterator [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::const_node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_node_iterator
Definition at line 232 of file bin_search_tree_.hpp.
const_node_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<node>::other::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_node_pointer private
Definition at line 131 of file pat_trie_.hpp.
const_point_iterator [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_point_iterator
Definition at line 140 of file rb_tree_.hpp.
const_point_iterator [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_point_iterator
Definition at line 162 of file splay_tree_.hpp.
const_point_iterator [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_point_iterator_ __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_point_iterator
Definition at line 181 of file lu_map_.hpp.
const_point_iterator [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_point_iterator
Definition at line 181 of file pat_trie_.hpp.
const_point_iterator [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_point_iterator_ __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_point_iterator
Definition at line 201 of file cc_ht_map_.hpp.
const_point_iterator [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef const_point_iterator_ __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_point_iterator
Definition at line 203 of file gp_ht_map_.hpp.
const_point_iterator [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_point_iterator
Definition at line 216 of file bin_search_tree_.hpp.
const_pointer [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer
Definition at line 136 of file rb_tree_.hpp.
const_pointer [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer
Definition at line 158 of file splay_tree_.hpp.
const_pointer [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer
Definition at line 169 of file lu_map_.hpp.
const_pointer [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer
Definition at line 177 of file pat_trie_.hpp.
const_pointer [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer
Definition at line 189 of file cc_ht_map_.hpp.
const_pointer [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer
Definition at line 191 of file gp_ht_map_.hpp.
const_pointer [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer
Definition at line 206 of file bin_search_tree_.hpp.
const_pointer_ [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer_ private
Definition at line 122 of file gp_ht_map_.hpp.
const_pointer_ [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer_ private
Definition at line 126 of file cc_ht_map_.hpp.
const_pointer_ [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_pointer_ private
Definition at line 130 of file lu_map_.hpp.
const_reference [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference
Definition at line 138 of file rb_tree_.hpp.
const_reference [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference
Definition at line 160 of file splay_tree_.hpp.
const_reference [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference
Definition at line 171 of file lu_map_.hpp.
const_reference [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference
Definition at line 179 of file pat_trie_.hpp.
const_reference [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference
Definition at line 191 of file cc_ht_map_.hpp.
const_reference [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference
Definition at line 193 of file gp_ht_map_.hpp.
const_reference [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference
Definition at line 212 of file bin_search_tree_.hpp.
const_reference_ [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference_ private
Definition at line 124 of file gp_ht_map_.hpp.
const_reference_ [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference_ private
Definition at line 128 of file cc_ht_map_.hpp.
const_reference_ [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::const_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reference_ private
Definition at line 132 of file lu_map_.hpp.
const_reverse_iterator [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reverse_iterator
Definition at line 144 of file rb_tree_.hpp.
const_reverse_iterator [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reverse_iterator
Definition at line 166 of file splay_tree_.hpp.
const_reverse_iterator [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reverse_iterator
Definition at line 186 of file pat_trie_.hpp.
const_reverse_iterator [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::const_reverse_iterator
Definition at line 226 of file bin_search_tree_.hpp.
container_category
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef pat_trie_tag __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::container_category
Definition at line 160 of file pat_trie_.hpp.
difference_type [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::difference_type
Definition at line 123 of file rb_tree_.hpp.
difference_type [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::difference_type
Definition at line 144 of file splay_tree_.hpp.
difference_type [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::difference_type
Definition at line 153 of file lu_map_.hpp.
difference_type [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::difference_type
Definition at line 163 of file pat_trie_.hpp.
difference_type [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::difference_type
Definition at line 166 of file bin_search_tree_.hpp.
difference_type [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::difference_type
Definition at line 166 of file cc_ht_map_.hpp.
difference_type [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::difference_type
Definition at line 167 of file gp_ht_map_.hpp.
e_access_traits
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::e_access_traits __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::e_access_traits
Definition at line 190 of file pat_trie_.hpp.
entry_allocator [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<entry>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_allocator private
Definition at line 119 of file lu_map_.hpp.
entry_allocator [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<entry>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_allocator private
Definition at line 137 of file cc_ht_map_.hpp.
entry_allocator [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<entry>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_allocator private
Definition at line 139 of file gp_ht_map_.hpp.
entry_array
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_array private
Definition at line 144 of file gp_ht_map_.hpp.
entry_pointer [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_pointer private
Definition at line 120 of file lu_map_.hpp.
entry_pointer [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_pointer private
Definition at line 138 of file cc_ht_map_.hpp.
entry_pointer [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_pointer private
Definition at line 140 of file gp_ht_map_.hpp.
entry_pointer_allocator [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<entry_pointer>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_pointer_allocator private
Definition at line 125 of file lu_map_.hpp.
entry_pointer_allocator [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<entry_pointer>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_pointer_allocator private
Definition at line 143 of file cc_ht_map_.hpp.
entry_pointer_array [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_pointer_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_pointer_array private
Definition at line 126 of file lu_map_.hpp.
entry_pointer_array [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_pointer_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_pointer_array private
Definition at line 144 of file cc_ht_map_.hpp.
entry_reference [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_reference private
Definition at line 122 of file lu_map_.hpp.
entry_reference [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_reference private
Definition at line 140 of file cc_ht_map_.hpp.
entry_reference [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef entry_allocator::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry_reference private
Definition at line 142 of file gp_ht_map_.hpp.
eq_fn [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Eq_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::eq_fn
Definition at line 154 of file lu_map_.hpp.
eq_fn [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Eq_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::eq_fn
Definition at line 168 of file cc_ht_map_.hpp.
eq_fn [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Eq_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::eq_fn
Definition at line 169 of file gp_ht_map_.hpp.
hash_eq_fn_base [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_HASH_EQ_FN_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::hash_eq_fn_base private
Definition at line 147 of file cc_ht_map_.hpp.
hash_eq_fn_base [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_HASH_EQ_FN_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::hash_eq_fn_base private
Definition at line 152 of file gp_ht_map_.hpp.
hash_fn [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Hash_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::hash_fn
Definition at line 167 of file cc_ht_map_.hpp.
hash_fn [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Hash_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::hash_fn
Definition at line 168 of file gp_ht_map_.hpp.
head
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::head __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::head private
Definition at line 135 of file pat_trie_.hpp.
head_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<head>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::head_allocator private
Definition at line 136 of file pat_trie_.hpp.
head_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef head_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::head_pointer private
Definition at line 137 of file pat_trie_.hpp.
internal_node
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::internal_node __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::internal_node private
Definition at line 144 of file pat_trie_.hpp.
internal_node_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<internal_node>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::internal_node_allocator private
Definition at line 145 of file pat_trie_.hpp.
internal_node_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef internal_node_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::internal_node_pointer private
Definition at line 147 of file pat_trie_.hpp.
iterator [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::iterator
Definition at line 141 of file rb_tree_.hpp.
iterator [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::iterator
Definition at line 163 of file splay_tree_.hpp.
iterator [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::iterator
Definition at line 184 of file pat_trie_.hpp.
iterator [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::iterator
Definition at line 222 of file bin_search_tree_.hpp.
key_pointer [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_pointer
Definition at line 125 of file rb_tree_.hpp.
key_pointer [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_pointer
Definition at line 147 of file splay_tree_.hpp.
key_pointer [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_pointer
Definition at line 158 of file lu_map_.hpp.
key_pointer [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_pointer
Definition at line 166 of file pat_trie_.hpp.
key_pointer [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_pointer
Definition at line 170 of file bin_search_tree_.hpp.
key_pointer [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_pointer
Definition at line 178 of file cc_ht_map_.hpp.
key_pointer [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_pointer
Definition at line 180 of file gp_ht_map_.hpp.
key_reference [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_reference
Definition at line 127 of file rb_tree_.hpp.
key_reference [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_reference
Definition at line 149 of file splay_tree_.hpp.
key_reference [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_reference
Definition at line 160 of file lu_map_.hpp.
key_reference [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_reference
Definition at line 168 of file pat_trie_.hpp.
key_reference [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_reference
Definition at line 176 of file bin_search_tree_.hpp.
key_reference [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_reference
Definition at line 180 of file cc_ht_map_.hpp.
key_reference [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_reference
Definition at line 182 of file gp_ht_map_.hpp.
key_type [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::key_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_type
Definition at line 124 of file rb_tree_.hpp.
key_type [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::key_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_type
Definition at line 146 of file splay_tree_.hpp.
key_type [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_type
Definition at line 157 of file lu_map_.hpp.
key_type [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_type
Definition at line 165 of file pat_trie_.hpp.
key_type [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::key_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_type
Definition at line 168 of file bin_search_tree_.hpp.
key_type [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_type
Definition at line 177 of file cc_ht_map_.hpp.
key_type [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::key_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::key_type
Definition at line 179 of file gp_ht_map_.hpp.
leaf
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::leaf __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::leaf private
Definition at line 139 of file pat_trie_.hpp.
leaf_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<leaf>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::leaf_allocator private
Definition at line 140 of file pat_trie_.hpp.
leaf_pointer
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef leaf_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::leaf_pointer private
Definition at line 142 of file pat_trie_.hpp.
mapped_pointer [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_pointer
Definition at line 130 of file rb_tree_.hpp.
mapped_pointer [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_pointer
Definition at line 152 of file splay_tree_.hpp.
mapped_pointer [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_pointer
Definition at line 163 of file lu_map_.hpp.
mapped_pointer [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_pointer
Definition at line 171 of file pat_trie_.hpp.
mapped_pointer [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_pointer
Definition at line 183 of file cc_ht_map_.hpp.
mapped_pointer [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_pointer
Definition at line 185 of file gp_ht_map_.hpp.
mapped_reference [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_reference
Definition at line 132 of file rb_tree_.hpp.
mapped_reference [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_reference
Definition at line 154 of file splay_tree_.hpp.
mapped_reference [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_reference
Definition at line 165 of file lu_map_.hpp.
mapped_reference [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_reference
Definition at line 173 of file pat_trie_.hpp.
mapped_reference [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_reference
Definition at line 185 of file cc_ht_map_.hpp.
mapped_reference [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_reference
Definition at line 187 of file gp_ht_map_.hpp.
mapped_type [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::mapped_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_type
Definition at line 129 of file rb_tree_.hpp.
mapped_type [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::mapped_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_type
Definition at line 151 of file splay_tree_.hpp.
mapped_type [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_type
Definition at line 162 of file lu_map_.hpp.
mapped_type [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_type
Definition at line 170 of file pat_trie_.hpp.
mapped_type [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_type
Definition at line 182 of file cc_ht_map_.hpp.
mapped_type [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::mapped_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::mapped_type
Definition at line 184 of file gp_ht_map_.hpp.
node [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::node __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node private
Definition at line 130 of file pat_trie_.hpp.
node [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef node_allocator::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node protected
Definition at line 145 of file bin_search_tree_.hpp.
node_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind< typename Node_And_It_Traits::node>::other __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_allocator protected
Definition at line 143 of file bin_search_tree_.hpp.
node_iterator [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_iterator
Definition at line 189 of file pat_trie_.hpp.
node_iterator [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_iterator
Definition at line 234 of file bin_search_tree_.hpp.
node_pointer [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_pointer private
Definition at line 117 of file rb_tree_.hpp.
node_pointer [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::template rebind<node>::other::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_pointer private
Definition at line 133 of file pat_trie_.hpp.
node_pointer [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_pointer private
Definition at line 139 of file splay_tree_.hpp.
node_pointer [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef node_allocator::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_pointer protected
Definition at line 147 of file bin_search_tree_.hpp.
node_update [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::node_update __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_update
Definition at line 145 of file rb_tree_.hpp.
node_update [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::node_update __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_update
Definition at line 167 of file splay_tree_.hpp.
node_update [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::node_update __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_update
Definition at line 191 of file pat_trie_.hpp.
node_update [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::node_update __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_update
Definition at line 240 of file bin_search_tree_.hpp.
null_node_update_pointer [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::null_node_update_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::null_node_update_pointer protected
Definition at line 153 of file bin_search_tree_.hpp.
null_node_update_pointer [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::null_node_update_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::null_node_update_pointer private
Definition at line 157 of file pat_trie_.hpp.
point_iterator [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::point_iterator
Definition at line 139 of file rb_tree_.hpp.
point_iterator [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::point_iterator
Definition at line 161 of file splay_tree_.hpp.
point_iterator [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::point_iterator
Definition at line 182 of file pat_trie_.hpp.
point_iterator [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::point_iterator
Definition at line 220 of file bin_search_tree_.hpp.
pointer [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer
Definition at line 135 of file rb_tree_.hpp.
pointer [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer
Definition at line 157 of file splay_tree_.hpp.
pointer [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer
Definition at line 168 of file lu_map_.hpp.
pointer [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer
Definition at line 176 of file pat_trie_.hpp.
pointer [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer
Definition at line 188 of file cc_ht_map_.hpp.
pointer [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer
Definition at line 190 of file gp_ht_map_.hpp.
pointer [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer
Definition at line 204 of file bin_search_tree_.hpp.
pointer_ [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer_ private
Definition at line 121 of file gp_ht_map_.hpp.
pointer_ [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer_ private
Definition at line 125 of file cc_ht_map_.hpp.
pointer_ [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pointer_ private
Definition at line 129 of file lu_map_.hpp.
probe_fn
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Probe_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::probe_fn
Definition at line 170 of file gp_ht_map_.hpp.
ranged_hash_fn_base
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_RANGED_HASH_FN_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::ranged_hash_fn_base private
Definition at line 146 of file cc_ht_map_.hpp.
ranged_probe_fn_base
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_RANGED_PROBE_FN_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::ranged_probe_fn_base private
Definition at line 146 of file gp_ht_map_.hpp.
reference [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference
Definition at line 137 of file rb_tree_.hpp.
reference [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference
Definition at line 159 of file splay_tree_.hpp.
reference [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference
Definition at line 170 of file lu_map_.hpp.
reference [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference
Definition at line 178 of file pat_trie_.hpp.
reference [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference
Definition at line 190 of file cc_ht_map_.hpp.
reference [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference
Definition at line 192 of file gp_ht_map_.hpp.
reference [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference
Definition at line 208 of file bin_search_tree_.hpp.
reference_ [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference_ private
Definition at line 123 of file gp_ht_map_.hpp.
reference_ [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference_ private
Definition at line 127 of file cc_ht_map_.hpp.
reference_ [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reference_ private
Definition at line 131 of file lu_map_.hpp.
resize_base [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Resize_Policy __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_base private
Definition at line 148 of file cc_ht_map_.hpp.
resize_base [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Resize_Policy __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_base private
Definition at line 153 of file gp_ht_map_.hpp.
resize_policy [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Resize_Policy __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_policy
Definition at line 170 of file cc_ht_map_.hpp.
resize_policy [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Resize_Policy __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_policy
Definition at line 172 of file gp_ht_map_.hpp.
reverse_iterator [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reverse_iterator
Definition at line 143 of file rb_tree_.hpp.
reverse_iterator [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reverse_iterator
Definition at line 165 of file splay_tree_.hpp.
reverse_iterator [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reverse_iterator
Definition at line 187 of file pat_trie_.hpp.
reverse_iterator [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::reverse_iterator
Definition at line 228 of file bin_search_tree_.hpp.
size_type [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size_type
Definition at line 122 of file rb_tree_.hpp.
size_type [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size_type
Definition at line 143 of file splay_tree_.hpp.
size_type [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size_type
Definition at line 152 of file lu_map_.hpp.
size_type [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size_type
Definition at line 162 of file pat_trie_.hpp.
size_type [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size_type
Definition at line 164 of file bin_search_tree_.hpp.
size_type [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size_type
Definition at line 165 of file cc_ht_map_.hpp.
size_type [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size_type
Definition at line 166 of file gp_ht_map_.hpp.
synth_e_access_traits
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Node_And_It_Traits::synth_e_access_traits __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::synth_e_access_traits private
Definition at line 126 of file pat_trie_.hpp.
traits_base [1/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::traits_base private
Definition at line 110 of file lu_map_.hpp.
traits_base [2/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::traits_base private
Definition at line 119 of file gp_ht_map_.hpp.
traits_base [3/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::traits_base private
Definition at line 122 of file cc_ht_map_.hpp.
traits_base [4/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::traits_base private
Definition at line 124 of file pat_trie_.hpp.
traits_base [5/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::traits_base protected
Definition at line 149 of file bin_search_tree_.hpp.
update_metadata
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Update_Policy::metadata_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update_metadata
Definition at line 156 of file lu_map_.hpp.
update_policy
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef Update_Policy __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update_policy
Definition at line 155 of file lu_map_.hpp.
value_type [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type
Definition at line 134 of file rb_tree_.hpp.
value_type [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef base_type::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type
Definition at line 156 of file splay_tree_.hpp.
value_type [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type
Definition at line 167 of file lu_map_.hpp.
value_type [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type
Definition at line 175 of file pat_trie_.hpp.
value_type [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type
Definition at line 187 of file cc_ht_map_.hpp.
value_type [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type
Definition at line 189 of file gp_ht_map_.hpp.
value_type [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef PB_DS_TYPES_TRAITS_C_DEC::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type
Definition at line 202 of file bin_search_tree_.hpp.
value_type_ [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type_ private
Definition at line 120 of file gp_ht_map_.hpp.
value_type_ [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type_ private
Definition at line 124 of file cc_ht_map_.hpp.
value_type_ [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > typedef traits_base::value_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_type_ private
Definition at line 128 of file lu_map_.hpp.
Member Enumeration Documentation
anonymous enum
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > anonymous enum
Enumerator
store_hash
Definition at line 172 of file cc_ht_map_.hpp.
     {
       store_hash = Store_Hash
     };
anonymous enum
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > anonymous enum private
Enumerator
store_hash_ok
Definition at line 603 of file cc_ht_map_.hpp.
     {
       store_hash_ok = !Store_Hash
                       || !is_same<Hash_Fn, __gnu_pbds::null_hash_fn>::value
     };
anonymous enum
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > anonymous enum
Enumerator
store_hash
Definition at line 174 of file gp_ht_map_.hpp.
     {
       store_hash = Store_Hash
     };
anonymous enum
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > anonymous enum private
Enumerator
store_hash_ok
Definition at line 645 of file gp_ht_map_.hpp.
     {
       store_hash_ok = !Store_Hash
                       || !is_same<Hash_Fn, __gnu_pbds::null_hash_fn>::value
     };
entry_status
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > enum __gnu_pbds::detail::PB_DS_CLASS_NAME::entry_status private
Enumerator
empty_entry_status
valid_entry_status
erased_entry_status
Definition at line 127 of file gp_ht_map_.hpp.
     {
       empty_entry_status,
       valid_entry_status,
       erased_entry_status
     } __attribute__ ((packed));
Constructor & Destructor Documentation
PB_DS_CLASS_NAME() [1/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [2/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Cmp_Fn & r_cmp_fn)
PB_DS_CLASS_NAME() [3/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Cmp_Fn & r_cmp_fn, const node_update & r_update)
PB_DS_CLASS_NAME() [4/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC & other)
~PB_DS_CLASS_NAME() [1/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::~PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [5/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [6/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn &)
PB_DS_CLASS_NAME() [7/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn & , const Eq_Fn &)
PB_DS_CLASS_NAME() [8/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn & , const Eq_Fn & , const Comb_Hash_Fn &)
PB_DS_CLASS_NAME() [9/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn & , const Eq_Fn & , const Comb_Hash_Fn & , const Resize_Policy &)
PB_DS_CLASS_NAME() [10/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
~PB_DS_CLASS_NAME() [2/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > virtual __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::~PB_DS_CLASS_NAME () virtual
PB_DS_CLASS_NAME() [11/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [12/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
PB_DS_CLASS_NAME() [13/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn &)
PB_DS_CLASS_NAME() [14/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn & , const Eq_Fn &)
PB_DS_CLASS_NAME() [15/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn & , const Eq_Fn & , const Comb_Probe_Fn &)
PB_DS_CLASS_NAME() [16/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn & , const Eq_Fn & , const Comb_Probe_Fn & , const Probe_Fn &)
PB_DS_CLASS_NAME() [17/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Hash_Fn & , const Eq_Fn & , const Comb_Probe_Fn & , const Probe_Fn & , const Resize_Policy &)
~PB_DS_CLASS_NAME() [3/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > virtual __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::~PB_DS_CLASS_NAME () virtual
PB_DS_CLASS_NAME() [18/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [19/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
~PB_DS_CLASS_NAME() [4/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > virtual __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::~PB_DS_CLASS_NAME () virtual
PB_DS_CLASS_NAME() [20/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (It first_it, It last_it)
PB_DS_CLASS_NAME() [21/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [22/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const e_access_traits &)
PB_DS_CLASS_NAME() [23/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
~PB_DS_CLASS_NAME() [5/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::~PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [24/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [25/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Cmp_Fn &)
PB_DS_CLASS_NAME() [26/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Cmp_Fn & , const node_update &)
PB_DS_CLASS_NAME() [27/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
PB_DS_CLASS_NAME() [28/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME ()
PB_DS_CLASS_NAME() [29/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Cmp_Fn &)
PB_DS_CLASS_NAME() [30/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const Cmp_Fn & , const node_update &)
PB_DS_CLASS_NAME() [31/31]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_CLASS_NAME (const PB_DS_CLASS_C_DEC &)
Member Function Documentation
__attribute__()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Key , typename Mapped , typename Hash_Fn , typename Eq_Fn , typename Allocator , bool Store_Hash, typename Comb_Probe_Fn , typename Probe_Fn , typename Resize_Policy > enum __gnu_pbds::detail::PB_DS_CLASS_NAME::entry_status __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::__attribute__ ((packed)) private
actual_erase_entry()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::actual_erase_entry (entry_pointer) private
actual_erase_leaf()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::actual_erase_leaf (leaf_pointer) inline private
actual_erase_node()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::actual_erase_node (node_pointer p_nd) inline protected
allocate_new_entry() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocate_new_entry (const_reference , false_type) inline private
allocate_new_entry() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::allocate_new_entry (const_reference , true_type) inline private
apply_update() [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Metadata > static bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::apply_update (entry_pointer , type_to_type< Metadata >) inline static private
apply_update() [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::apply_update (entry_pointer , type_to_type< null_lu_metadata >) inline static private
apply_update() [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Node_Update_ > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::apply_update (node_pointer p_nd, Node_Update_ * p_update) inline protected
apply_update() [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::apply_update (node_pointer p_nd, null_node_update_pointer) inline protected
apply_update() [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Node_Update_ > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::apply_update (node_pointer , Node_Update_ *) inline private
apply_update() [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::apply_update (node_pointer , null_node_update_pointer) inline private
begin() [1/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () inline
begin() [2/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () inline
begin() [3/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () inline
begin() [4/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () inline
begin() [5/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () inline
begin() [6/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () const inline
begin() [7/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () const inline
begin() [8/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () const inline
begin() [9/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () const inline
begin() [10/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::begin () const inline
black_height()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::black_height (node_pointer) inline private
clear() [1/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::clear ()
clear() [2/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::clear ()
clear() [3/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::clear ()
clear() [4/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::clear ()
clear() [5/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::clear ()
clear_imp() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::clear_imp (node_pointer p_nd) static protected
clear_imp() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::clear_imp (node_pointer) private
copy_from_range() [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_range (It first_it, It last_it)
copy_from_range() [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_range (It , It)
copy_from_range() [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_range (It , It)
copy_from_range() [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_range (It , It)
copy_from_range() [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_range (It , It) protected
copy_from_range() [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename It > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::copy_from_range (It , It) protected
deallocate_all() [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::deallocate_all () private
deallocate_all() [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::deallocate_all () private
deallocate_all() [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::deallocate_all () private
deallocate_links_in_list()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::deallocate_links_in_list (entry_pointer) private
do_resize() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize (size_type new_size) private
do_resize() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > virtual void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize (size_type) private virtual
do_resize_if_needed() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize_if_needed () inline private
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp().
do_resize_if_needed() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize_if_needed () inline private
do_resize_if_needed_no_throw() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize_if_needed_no_throw () inline private
do_resize_if_needed_no_throw() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize_if_needed_no_throw () inline private
empty() [1/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::empty () const inline
empty() [2/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::empty () const inline
empty() [3/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::empty () const inline
empty() [4/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::empty () const inline
empty() [5/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::empty () const inline
end() [1/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () inline
end() [2/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () inline
end() [3/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () inline
end() [4/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () inline
end() [5/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () inline
end() [6/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () const inline
end() [7/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () const inline
end() [8/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () const inline
end() [9/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () const inline
end() [10/10]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::end () const inline
erase() [1/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_iterator) inline
erase() [2/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_key_reference r_key) inline
erase() [3/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_key_reference) inline
erase() [4/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_key_reference) inline
erase() [5/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_key_reference) inline
erase() [6/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_key_reference) inline
erase() [7/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_key_reference) inline
erase() [8/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (const_reverse_iterator) inline
erase() [9/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (iterator it) inline
erase() [10/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (iterator) inline
erase() [11/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<node_pointer, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (node_pointer p_nd) inline protected
erase() [12/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (reverse_iterator) inline
erase() [13/13]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase (reverse_iterator) inline
erase_all_valid_entries()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_all_valid_entries (entry_array , size_type) private
erase_entry()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_entry (entry_pointer p_e) inline private
erase_entry_pointer()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_entry_pointer (entry_pointer &) inline private
erase_fixup()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_fixup (internal_node_pointer) private
erase_if() [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Pred > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_if (Pred prd) inline
erase_if() [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Pred > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_if (Pred) inline
erase_if() [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Pred > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_if (Pred) inline
erase_if() [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Pred > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_if (Pred) inline
erase_if() [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Pred > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_if (Pred) inline
erase_if() [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Pred > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_if (Pred) inline
erase_imp() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_imp (const_key_reference , false_type) inline private
erase_imp() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_imp (const_key_reference , true_type) inline private
erase_in_pos_imp() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_in_pos_imp (const_key_reference , const comp_hash &) inline private
erase_in_pos_imp() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_in_pos_imp (const_key_reference , size_type) inline private
erase_leaf()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_leaf (leaf_pointer) private
erase_next()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_next (entry_pointer) private
erase_node() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_node (node_pointer) private
erase_node() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erase_node (node_pointer) private
find() [1/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference r_key) inline
Definition at line 232 of file lu_map_.hpp.
       {
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     entry_pointer p_e = find_imp(r_key);
     return point_iterator(p_e == 0 ? 0: &p_e->m_value);
       }
References _GLIBCXX_DEBUG_ONLY, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_imp().
find() [2/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference r_key) inline
find() [3/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference r_key) inline
find() [4/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference r_key) const inline
Definition at line 240 of file lu_map_.hpp.
       {
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     entry_pointer p_e = find_imp(r_key);
     return const_point_iterator(p_e == 0 ? 0: &p_e->m_value);
       }
References _GLIBCXX_DEBUG_ONLY, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_imp().
find() [5/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference r_key) const inline
find() [6/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference r_key) const inline
find() [7/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference) inline
find() [8/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference) inline
find() [9/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference) inline
find() [10/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference) const inline
find() [11/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference) const inline
find() [12/12]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find (const_key_reference) const inline
find_end() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_end () inline
find_end() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_end () inline
find_end() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_end () const inline
find_end() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_end () const inline
find_imp() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_imp (const_key_reference) inline private
find_imp() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_imp (const_key_reference) inline private
find_imp() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_imp (const_key_reference) const inline private
find_imp() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_imp (const_key_reference) const inline private
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find().
find_ins_pos() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_ins_pos (const_key_reference , false_type) inline private
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp().
find_ins_pos() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > comp_hash __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_ins_pos (const_key_reference , true_type) inline private
find_join_pos_left()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<node_pointer, node_pointer> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_join_pos_left (node_pointer , size_type , size_type) private
find_join_pos_right()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<node_pointer, node_pointer> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_join_pos_right (node_pointer , size_type , size_type) private
find_key_pointer() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_key_pointer (const_key_reference key, false_type) inline private
Definition at line 474 of file gp_ht_map_.hpp.
       {
     const size_type hash = ranged_probe_fn_base::operator()(key);
     size_type i;
     resize_base::notify_find_search_start();
     // Loop until entry is found or until all possible entries accessed.
     for (i = 0; i < m_num_e; ++i)
       {
         const size_type pos = ranged_probe_fn_base::operator()(key, hash, i);
         entry* const p_e = m_entries + pos;
         switch (p_e->m_stat)
           {
           case empty_entry_status:
         {
           resize_base::notify_find_search_end();
           _GLIBCXX_DEBUG_ONLY(debug_base::check_key_does_not_exist(key);)
             return 0;
         }
         break;
           case valid_entry_status:
         if (hash_eq_fn_base::operator()(PB_DS_V2F(p_e->m_value), key))
           {
             resize_base::notify_find_search_end();
             _GLIBCXX_DEBUG_ONLY(debug_base::check_key_exists(key);)
             return pointer(&p_e->m_value);
           }
         break;
           case erased_entry_status:
         break;
           default:
         _GLIBCXX_DEBUG_ASSERT(0);
           };
         resize_base::notify_find_search_collision();
       }
     _GLIBCXX_DEBUG_ONLY(debug_base::check_key_does_not_exist(key);)
     resize_base::notify_find_search_end();
     return 0;
       }
References _GLIBCXX_DEBUG_ASSERT, _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::empty_entry_status, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erased_entry_status, hash(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_e, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry::m_stat, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry::m_value, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::valid_entry_status.
find_key_pointer() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_key_pointer (const_key_reference key, true_type) inline private
Definition at line 520 of file gp_ht_map_.hpp.
       {
     comp_hash pos_hash_pair = ranged_probe_fn_base::operator()(key);
     size_type i;
     resize_base::notify_find_search_start();
     // Loop until entry is found or until all possible entries accessed.
     for (i = 0; i < m_num_e; ++i)
       {
         const size_type pos =
           ranged_probe_fn_base::operator()(key, pos_hash_pair.second, i);
         entry* const p_e = m_entries + pos;
         switch(p_e->m_stat)
           {
           case empty_entry_status:
         {
           resize_base::notify_find_search_end();
           _GLIBCXX_DEBUG_ONLY(debug_base::check_key_does_not_exist(key);)
           return 0;
         }
         break;
           case valid_entry_status:
         if (hash_eq_fn_base::operator()(PB_DS_V2F(p_e->m_value),
                         p_e->m_hash,
                         key, pos_hash_pair.second))
           {
             resize_base::notify_find_search_end();
             _GLIBCXX_DEBUG_ONLY(debug_base::check_key_exists(key);)
             return pointer(&p_e->m_value);
           }
         break;
           case erased_entry_status:
         break;
           default:
         _GLIBCXX_DEBUG_ASSERT(0);
           };
         resize_base::notify_find_search_collision();
       }
     _GLIBCXX_DEBUG_ONLY(debug_base::check_key_does_not_exist(key);)
     resize_base::notify_find_search_end();
     return 0;
       }
References _GLIBCXX_DEBUG_ASSERT, _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::empty_entry_status, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::erased_entry_status, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_e, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry::m_stat, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry::m_value, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::valid_entry_status.
find_key_pointer() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_key_pointer (const_key_reference r_key, false_type) inline private
Definition at line 467 of file cc_ht_map_.hpp.
       {
     entry_pointer p_e = m_entries[ranged_hash_fn_base::operator()(r_key)];
     resize_base::notify_find_search_start();
     while (p_e != 0 &&
            !hash_eq_fn_base::operator()(PB_DS_V2F(p_e->m_value), r_key))
       {
         resize_base::notify_find_search_collision();
         p_e = p_e->m_p_next;
       }
     resize_base::notify_find_search_end();
 #ifdef _GLIBCXX_DEBUG
     if (p_e == 0)
       debug_base::check_key_does_not_exist(r_key);
     else
       debug_base::check_key_exists(r_key);
 #endif
     return &p_e->m_value;
       }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries.
find_key_pointer() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_key_pointer (const_key_reference r_key, true_type) inline private
Definition at line 490 of file cc_ht_map_.hpp.
       {
     comp_hash pos_hash_pair = ranged_hash_fn_base::operator()(r_key);
     entry_pointer p_e = m_entries[pos_hash_pair.first];
     resize_base::notify_find_search_start();
     while (p_e != 0 &&
            !hash_eq_fn_base::operator()(PB_DS_V2F(p_e->m_value),
                         p_e->m_hash,
                         r_key, pos_hash_pair.second))
       {
         resize_base::notify_find_search_collision();
         p_e = p_e->m_p_next;
       }
     resize_base::notify_find_search_end();
 #ifdef _GLIBCXX_DEBUG
     if (p_e == 0)
       debug_base::check_key_does_not_exist(r_key);
     else
       debug_base::check_key_exists(r_key);
 #endif
     return &p_e->m_value;
       }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries.
get_cmp_fn() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Cmp_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_cmp_fn ()
get_cmp_fn() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Cmp_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_cmp_fn () const
get_comb_hash_fn() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Comb_Hash_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_comb_hash_fn ()
get_comb_hash_fn() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Comb_Hash_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_comb_hash_fn () const
get_comb_probe_fn() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Comb_Probe_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_comb_probe_fn ()
get_comb_probe_fn() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Comb_Probe_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_comb_probe_fn () const
get_e_access_traits() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > e_access_traits& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_e_access_traits ()
get_e_access_traits() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const e_access_traits& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_e_access_traits () const
get_entry() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_entry (const_reference , false_type) inline private
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp().
get_entry() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_entry (const_reference , true_type) inline private
get_eq_fn() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Eq_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_eq_fn ()
get_eq_fn() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Eq_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_eq_fn ()
get_eq_fn() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Eq_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_eq_fn () const
get_eq_fn() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Eq_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_eq_fn () const
get_hash_fn() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Hash_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_hash_fn ()
get_hash_fn() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Hash_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_hash_fn ()
get_hash_fn() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Hash_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_hash_fn () const
get_hash_fn() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Hash_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_hash_fn () const
get_new_node_for_leaf_insert() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_new_node_for_leaf_insert (const_reference r_val, false_type) inline protected
get_new_node_for_leaf_insert() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_new_node_for_leaf_insert (const_reference r_val, true_type) inline protected
get_node_update() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_update& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_node_update ()
get_node_update() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const node_update& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_node_update () const
get_probe_fn() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Probe_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_probe_fn ()
get_probe_fn() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Probe_Fn& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_probe_fn () const
get_resize_policy() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Resize_Policy& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_resize_policy ()
get_resize_policy() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Resize_Policy& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_resize_policy ()
get_resize_policy() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Resize_Policy& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_resize_policy () const
get_resize_policy() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const Resize_Policy& __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_resize_policy () const
get_start_it_state() [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_start_it_state (const_pointer & r_p_value, size_type & r_pos) const inline private
Definition at line 600 of file gp_ht_map_.hpp.
       {
     for (r_pos = 0; r_pos < m_num_e; ++r_pos)
       {
         const_entry_pointer p_e = &m_entries[r_pos];
         if (p_e->m_stat == valid_entry_status)
           {
         r_p_value = &p_e->m_value;
         return;
           }
       }
     r_p_value = 0;
       }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_e, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::valid_entry_status.
get_start_it_state() [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_start_it_state (pointer & r_p_value, size_type & r_pos) inline private
Definition at line 615 of file gp_ht_map_.hpp.
       {
     for (r_pos = 0; r_pos < m_num_e; ++r_pos)
       {
         entry_pointer p_e = &m_entries[r_pos];
         if (p_e->m_stat == valid_entry_status)
           {
         r_p_value = &p_e->m_value;
         return;
           }
       }
     r_p_value = 0;
       }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_e, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::valid_entry_status.
get_start_it_state() [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_start_it_state (pointer & r_p_value, std::pair< entry_pointer, size_type > & r_pos) const inline private
Definition at line 556 of file cc_ht_map_.hpp.
       {
     for (r_pos.second = 0; r_pos.second < m_num_e; ++r_pos.second)
       if (m_entries[r_pos.second] != 0)
         {
           r_pos.first = m_entries[r_pos.second];
           r_p_value = &r_pos.first->m_value;
           return;
         }
     r_p_value = 0;
       }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_e.
inc_it_state() [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::inc_it_state (const_pointer & r_p_value, entry_pointer & r_pos) const inline private
Definition at line 315 of file lu_map_.hpp.
       {
     r_pos = r_pos->m_p_next;
     r_p_value = (r_pos == 0) ? 0 : &r_pos->m_value;
       }
inc_it_state() [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::inc_it_state (const_pointer & r_p_value, size_type & r_pos) const inline private
Definition at line 584 of file gp_ht_map_.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(r_p_value != 0);
     for (++r_pos; r_pos < m_num_e; ++r_pos)
       {
         const_entry_pointer p_e =& m_entries[r_pos];
         if (p_e->m_stat == valid_entry_status)
           {
         r_p_value =& p_e->m_value;
         return;
           }
       }
     r_p_value = 0;
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_e, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::valid_entry_status.
inc_it_state() [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::inc_it_state (const_pointer & r_p_value, std::pair< entry_pointer, size_type > & r_pos) const inline private
Definition at line 534 of file cc_ht_map_.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(r_p_value != 0);
     r_pos.first = r_pos.first->m_p_next;
     if (r_pos.first != 0)
       {
         r_p_value = &r_pos.first->m_value;
         return;
       }
     for (++r_pos.second; r_pos.second < m_num_e; ++r_pos.second)
       if (m_entries[r_pos.second] != 0)
         {
           r_pos.first = m_entries[r_pos.second];
           r_p_value = &r_pos.first->m_value;
           return;
         }
     r_p_value = 0;
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_e.
init_entry_metadata() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Metadata > static void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::init_entry_metadata (entry_pointer , type_to_type< Metadata >) inline static private
init_entry_metadata() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::init_entry_metadata (entry_pointer , type_to_type< null_lu_metadata >) inline static private
initialize() [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::initialize ()
initialize() [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::initialize () private
initialize() [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::initialize ()
initialize() [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::initialize () private
initialize() [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::initialize () private
initialize() [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::initialize () private
initialize_min_max()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::initialize_min_max () protected
insert() [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert (const_reference r_val) inline
Definition at line 273 of file cc_ht_map_.hpp.
       { return insert_imp(r_val, traits_base::m_store_extra_indicator); }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_imp().
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[]().
insert() [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert (const_reference r_val) inline
Definition at line 281 of file gp_ht_map_.hpp.
       {
     _GLIBCXX_DEBUG_ONLY(PB_DS_CLASS_C_DEC::assert_valid();)
         return insert_imp(r_val, traits_base::m_store_extra_indicator);
       }
References _GLIBCXX_DEBUG_ONLY, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_imp().
insert() [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert (const_reference r_value) inline
insert() [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert (const_reference) inline
insert() [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert (const_reference) inline
insert() [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert (const_reference) inline
insert_branch()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > internal_node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_branch (node_pointer , node_pointer , split_join_branch_bag &) private
insert_fixup()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_fixup (node_pointer) private
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[]().
insert_imp() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_imp (const_reference , false_type) inline private
insert_imp() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_imp (const_reference , false_type) inline private
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert().
insert_imp() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_imp (const_reference , true_type) inline private
insert_imp() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_imp (const_reference , true_type) inline private
insert_imp_empty()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_imp_empty (const_reference r_value) inline protected
insert_leaf()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair< point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_leaf (const_reference r_value) inline protected
insert_leaf_imp()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<point_iterator, bool> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_leaf_imp (const_reference) inline private
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[]().
insert_leaf_new()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_leaf_new (const_reference r_value, node_pointer p_nd, bool left_nd) inline protected
insert_new_imp() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp (const_reference r_val, comp_hash & r_pos_hash_pair) inline private
Definition at line 414 of file gp_ht_map_.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_entries[r_pos_hash_pair.first].m_stat !=
              valid_entry_status);
     if (do_resize_if_needed())
       r_pos_hash_pair = find_ins_pos(PB_DS_V2F(r_val),
                      traits_base::m_store_extra_indicator);
     _GLIBCXX_DEBUG_ASSERT(m_entries[r_pos_hash_pair.first].m_stat !=
                   valid_entry_status);
     entry* const p_e = m_entries + r_pos_hash_pair.first;
     new (&p_e->m_value) value_type(r_val);
     p_e->m_hash = r_pos_hash_pair.second;
     p_e->m_stat = valid_entry_status;
     resize_base::notify_inserted(++m_num_used_e);
     _GLIBCXX_DEBUG_ONLY(debug_base::insert_new(PB_DS_V2F(p_e->m_value));)
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     return &p_e->m_value;
       }
References _GLIBCXX_DEBUG_ASSERT, _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize_if_needed(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_ins_pos(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_used_e, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry::m_stat, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry::m_value, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::valid_entry_status.
insert_new_imp() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp (const_reference r_val, comp_hash & r_pos_hash_pair) inline private
Definition at line 448 of file cc_ht_map_.hpp.
       {
     // Following lines might throw an exception.
     if (do_resize_if_needed())
       r_pos_hash_pair = ranged_hash_fn_base::operator()(PB_DS_V2F(r_val));
     entry_pointer p_e = get_entry(r_val, traits_base::m_no_throw_copies_indicator);
     // At this point no exceptions can be thrown.
     p_e->m_hash = r_pos_hash_pair.second;
     p_e->m_p_next = m_entries[r_pos_hash_pair.first];
     m_entries[r_pos_hash_pair.first] = p_e;
     resize_base::notify_inserted(++m_num_used_e);
     _GLIBCXX_DEBUG_ONLY(debug_base::insert_new(PB_DS_V2F(r_val));)
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     return &p_e->m_value;
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize_if_needed(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_entry(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_used_e.
insert_new_imp() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp (const_reference r_val, size_type pos) inline private
Definition at line 392 of file gp_ht_map_.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_entries[pos].m_stat != valid_entry_status);
     if (do_resize_if_needed())
       pos = find_ins_pos(PB_DS_V2F(r_val),
                  traits_base::m_store_extra_indicator);
     _GLIBCXX_DEBUG_ASSERT(m_entries[pos].m_stat != valid_entry_status);
     entry* const p_e = m_entries + pos;
     new (&p_e->m_value) value_type(r_val);
     p_e->m_stat = valid_entry_status;
     resize_base::notify_inserted(++m_num_used_e);
     _GLIBCXX_DEBUG_ONLY(debug_base::insert_new(PB_DS_V2F(p_e->m_value));)
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     return &p_e->m_value;
       }
References _GLIBCXX_DEBUG_ASSERT, _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize_if_needed(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_ins_pos(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_used_e, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry::m_stat, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::entry::m_value, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::valid_entry_status.
insert_new_imp() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp (const_reference r_val, size_type pos) inline private
Definition at line 429 of file cc_ht_map_.hpp.
       {
     if (do_resize_if_needed())
       pos = ranged_hash_fn_base::operator()(PB_DS_V2F(r_val));
     // Following lines might throw an exception.
     entry_pointer p_e = get_entry(r_val, traits_base::m_no_throw_copies_indicator);
     // At this point no exceptions can be thrown.
     p_e->m_p_next = m_entries[pos];
     m_entries[pos] = p_e;
     resize_base::notify_inserted(++m_num_used_e);
     _GLIBCXX_DEBUG_ONLY(debug_base::insert_new(PB_DS_V2F(r_val));)
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     return &p_e->m_value;
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::do_resize_if_needed(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_entry(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_used_e.
is_effectively_black()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::is_effectively_black (const node_pointer) inline static private
join() [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::join (PB_DS_CLASS_C_DEC &)
join() [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::join (PB_DS_CLASS_C_DEC &)
join() [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::join (PB_DS_CLASS_C_DEC &)
join_finish()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::join_finish (PB_DS_CLASS_C_DEC & other) protected
join_imp()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::join_imp (node_pointer , node_pointer) private
join_prep() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::join_prep (PB_DS_CLASS_C_DEC & , split_join_branch_bag &) private
join_prep() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::join_prep (PB_DS_CLASS_C_DEC & other) protected
keys_diff_ind()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::keys_diff_ind (typename e_access_traits::const_iterator , typename e_access_traits::const_iterator , typename e_access_traits::const_iterator , typename e_access_traits::const_iterator) private
leftmost()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::leftmost (node_pointer) inline private
leftmost_descendant() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static const_leaf_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::leftmost_descendant (const_node_pointer) inline static private
leftmost_descendant() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static leaf_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::leftmost_descendant (node_pointer) inline static private
lower_bound() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound (const_key_reference r_key) inline
lower_bound() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound (const_key_reference r_key) const inline
lower_bound() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound (const_key_reference) inline
lower_bound() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound (const_key_reference) const inline
lower_bound_imp()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::lower_bound_imp (const_key_reference) inline private
max_size() [1/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::max_size () const inline
max_size() [2/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::max_size () const inline
max_size() [3/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::max_size () const inline
max_size() [4/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::max_size () const inline
max_size() [5/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::max_size () const inline
node_begin() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_begin () inline
node_begin() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_begin () inline
node_begin() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_begin () const inline
node_begin() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_begin () const inline
node_end() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_end () inline
node_end() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_end () inline
node_end() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_end () const inline
node_end() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_node_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::node_end () const inline
operator[]() [1/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[] (const_key_reference r_key) inline
Definition at line 167 of file rb_tree_.hpp.
       {
 #ifdef PB_DS_DATA_TRUE_INDICATOR
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     std::pair<point_iterator, bool> ins_pair =
     base_type::insert_leaf(value_type(r_key, mapped_type()));
     if (ins_pair.second == true)
       {
         ins_pair.first.m_p_nd->m_red = true;
         _GLIBCXX_DEBUG_ONLY(this->structure_only_assert_valid();)
         insert_fixup(ins_pair.first.m_p_nd);
       }
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     return ins_pair.first.m_p_nd->m_value.second;
 #else
     insert(r_key);
     return base_type::s_null_mapped;
 #endif
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert(), and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_fixup().
operator[]() [2/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[] (const_key_reference r_key) inline
Definition at line 191 of file splay_tree_.hpp.
       {
 #ifdef PB_DS_DATA_TRUE_INDICATOR
     _GLIBCXX_DEBUG_ONLY(PB_DS_CLASS_C_DEC::assert_valid();)
     std::pair<point_iterator, bool> ins_pair =
       insert_leaf_imp(value_type(r_key, mapped_type()));
     ins_pair.first.m_p_nd->m_special = false;
     _GLIBCXX_DEBUG_ONLY(base_type::assert_valid());
     splay(ins_pair.first.m_p_nd);
     _GLIBCXX_DEBUG_ONLY(PB_DS_CLASS_C_DEC::assert_valid();)
     return ins_pair.first.m_p_nd->m_value.second;
 #else
     insert(r_key);
     return base_type::s_null_mapped;
 #endif
       }
References _GLIBCXX_DEBUG_ONLY, __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_leaf_imp(), and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::splay().
operator[]() [3/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[] (const_key_reference r_key) inline
Definition at line 217 of file lu_map_.hpp.
       {
 #ifdef PB_DS_DATA_TRUE_INDICATOR
     _GLIBCXX_DEBUG_ONLY(assert_valid();)
     return insert(std::make_pair(r_key, mapped_type())).first->second;
 #else
     insert(r_key);
     return traits_base::s_null_mapped;
 #endif
       }
References _GLIBCXX_DEBUG_ONLY, and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert().
operator[]() [4/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[] (const_key_reference r_key) inline
Definition at line 229 of file pat_trie_.hpp.
       {
 #ifdef PB_DS_DATA_TRUE_INDICATOR
     return insert(std::make_pair(r_key, mapped_type())).first->second;
 #else
     insert(r_key);
     return traits_base::s_null_mapped;
 #endif
       }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert().
operator[]() [5/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[] (const_key_reference r_key) inline
Definition at line 277 of file cc_ht_map_.hpp.
       {
 #ifdef PB_DS_DATA_TRUE_INDICATOR
     return (subscript_imp(r_key, traits_base::m_store_extra_indicator));
 #else
     insert(r_key);
     return traits_base::s_null_mapped;
 #endif
       }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert().
operator[]() [6/6]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > mapped_reference __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[] (const_key_reference r_key) inline
Definition at line 288 of file gp_ht_map_.hpp.
       {
 #ifdef PB_DS_DATA_TRUE_INDICATOR
     return subscript_imp(r_key, traits_base::m_store_extra_indicator);
 #else
     insert(r_key);
         return traits_base::s_null_mapped;
 #endif
       }
References __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert().
PB_DS_STATIC_ASSERT() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_STATIC_ASSERT (sth , store_hash_ok) private
PB_DS_STATIC_ASSERT() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::PB_DS_STATIC_ASSERT (sth , store_hash_ok) private
pref_begin()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static const_e_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pref_begin (const_node_pointer) inline static private
pref_end()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static const_e_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::pref_end (const_node_pointer) inline static private
rbegin() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rbegin () inline
rbegin() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rbegin () inline
rbegin() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rbegin () const inline
rbegin() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rbegin () const inline
rec_join() [1/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join (internal_node_pointer , internal_node_pointer , split_join_branch_bag &) private
rec_join() [2/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join (internal_node_pointer , leaf_pointer , size_type , split_join_branch_bag &) private
rec_join() [3/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join (leaf_pointer , internal_node_pointer , size_type , split_join_branch_bag &) private
rec_join() [4/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join (leaf_pointer , leaf_pointer , split_join_branch_bag &) private
rec_join() [5/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join (node_pointer , node_pointer , size_type , split_join_branch_bag &) private
rec_join_prep() [1/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join_prep (const_internal_node_pointer , const_internal_node_pointer , split_join_branch_bag &) private
rec_join_prep() [2/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join_prep (const_internal_node_pointer , const_leaf_pointer , split_join_branch_bag &) private
rec_join_prep() [3/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join_prep (const_leaf_pointer , const_internal_node_pointer , split_join_branch_bag &) private
rec_join_prep() [4/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join_prep (const_leaf_pointer , const_leaf_pointer , split_join_branch_bag &) private
rec_join_prep() [5/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_join_prep (const_node_pointer , const_node_pointer , split_join_branch_bag &) private
rec_split()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rec_split (node_pointer , const_e_iterator , const_e_iterator , PB_DS_CLASS_C_DEC & , split_join_branch_bag &) private
recursive_copy_node() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::recursive_copy_node (const node_pointer p_nd) private
recursive_copy_node() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::recursive_copy_node (const_node_pointer) protected
recursive_count()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::recursive_count (node_pointer p_nd) const protected
rels_entry()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rels_entry (entry_pointer) inline private
remove_fixup()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::remove_fixup (node_pointer , node_pointer) private
remove_node()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::remove_node (node_pointer) private
rend() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rend () inline
rend() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rend () inline
rend() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rend () const inline
rend() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_reverse_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rend () const inline
resize_imp() [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_imp (entry_array , size_type) private
resize_imp() [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_imp (size_type new_size) private
resize_imp() [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_imp (size_type) private
resize_imp_no_exceptions()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_imp_no_exceptions (size_type , entry_pointer_array , size_type) private
resize_imp_no_exceptions_reassign_pointer() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_imp_no_exceptions_reassign_pointer (entry_pointer , entry_pointer_array , false_type) inline private
resize_imp_no_exceptions_reassign_pointer() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_imp_no_exceptions_reassign_pointer (entry_pointer , entry_pointer_array , true_type) inline private
resize_imp_reassign() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_imp_reassign (entry_pointer , entry_array , false_type) inline private
resize_imp_reassign() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::resize_imp_reassign (entry_pointer , entry_array , true_type) inline private
rightmost_descendant() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static const_leaf_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rightmost_descendant (const_node_pointer) inline static private
rightmost_descendant() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static leaf_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rightmost_descendant (node_pointer) inline static private
rotate_left()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rotate_left (node_pointer p_x) inline protected
rotate_parent()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rotate_parent (node_pointer p_nd) inline protected
rotate_right()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::rotate_right (node_pointer p_y) inline protected
size() [1/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size () const inline
size() [2/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size () const inline
size() [3/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size () const inline
size() [4/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size () const inline
size() [5/5]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::size () const inline
splay()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::splay (node_pointer) private
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::operator[]().
splay_zig_zag_left()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::splay_zig_zag_left (node_pointer , node_pointer , node_pointer) inline private
splay_zig_zag_right()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::splay_zig_zag_right (node_pointer , node_pointer , node_pointer) inline private
splay_zig_zig_left()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::splay_zig_zig_left (node_pointer , node_pointer , node_pointer) inline private
splay_zig_zig_right()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::splay_zig_zig_right (node_pointer , node_pointer , node_pointer) inline private
splay_zz_end()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::splay_zz_end (node_pointer , node_pointer , node_pointer) inline private
splay_zz_start()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::splay_zz_start (node_pointer , node_pointer , node_pointer) inline private
split() [1/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split (const_key_reference , PB_DS_CLASS_C_DEC &)
split() [2/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split (const_key_reference , PB_DS_CLASS_C_DEC &)
split() [3/3]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split (const_key_reference , PB_DS_CLASS_C_DEC &)
split_at_node()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split_at_node (node_pointer , PB_DS_CLASS_C_DEC &) private
split_finish()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split_finish (PB_DS_CLASS_C_DEC & other) protected
split_imp()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split_imp (node_pointer , PB_DS_CLASS_C_DEC &) private
split_insert_branch()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split_insert_branch (size_type , const_e_iterator , typename internal_node::iterator , size_type , split_join_branch_bag &) private
split_min()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split_min () inline private
split_min_imp()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > std::pair<node_pointer, node_pointer> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split_min_imp () private
split_prep() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > bool __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split_prep (const_key_reference r_key, PB_DS_CLASS_C_DEC & other) protected
split_prep() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > leaf_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::split_prep (const_key_reference , PB_DS_CLASS_C_DEC & , split_join_branch_bag &) private
swap() [1/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::swap (PB_DS_CLASS_C_DEC &)
swap() [2/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::swap (PB_DS_CLASS_C_DEC &)
swap() [3/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::swap (PB_DS_CLASS_C_DEC &)
swap() [4/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::swap (PB_DS_CLASS_C_DEC &)
swap() [5/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::swap (PB_DS_CLASS_C_DEC &)
swap() [6/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::swap (PB_DS_CLASS_C_DEC & other)
swap() [7/7]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::swap (PB_DS_CLASS_C_DEC & other)
update_min_max_for_erased_leaf()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update_min_max_for_erased_leaf (leaf_pointer) private
update_min_max_for_erased_node()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update_min_max_for_erased_node (node_pointer p_nd) inline protected
update_min_max_for_inserted_leaf()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update_min_max_for_inserted_leaf (leaf_pointer) private
update_to_top() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > template<typename Node_Update_ > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update_to_top (node_pointer p_nd, Node_Update_ * p_update) inline protected
update_to_top() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::update_to_top (node_pointer p_nd, null_node_update_pointer) inline protected
upper_bound() [1/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound (const_key_reference r_key) inline
upper_bound() [2/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound (const_key_reference r_key) const inline
upper_bound() [3/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound (const_key_reference) inline
upper_bound() [4/4]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound (const_key_reference) const inline
upper_bound_imp()
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::upper_bound_imp (const_key_reference) inline private
value_swap() [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_swap (PB_DS_CLASS_C_DEC &) protected
value_swap() [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > void __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::value_swap (PB_DS_CLASS_C_DEC & other) protected
Friends And Related Function Documentation
const_iterator_
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_iterator_ friend
Definition at line 590 of file cc_ht_map_.hpp.
Field Documentation
__attribute__
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > __gnu_pbds::detail::PB_DS_CLASS_NAME::entry __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::__attribute__ private
m_entries [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer_array __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries private
Definition at line 601 of file cc_ht_map_.hpp.
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_key_pointer(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_start_it_state(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::inc_it_state(), and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp().
m_entries [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_entries private
Definition at line 643 of file gp_ht_map_.hpp.
m_num_e
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_e private
Definition at line 599 of file cc_ht_map_.hpp.
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::find_key_pointer(), __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::get_start_it_state(), and __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::inc_it_state().
m_num_used_e
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_num_used_e private
Definition at line 600 of file cc_ht_map_.hpp.
Referenced by __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::insert_new_imp().
m_p_head [1/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_p_head protected
Definition at line 460 of file bin_search_tree_.hpp.
m_p_head [2/2]
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > head_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_p_head private
Definition at line 489 of file pat_trie_.hpp.
m_p_l
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_p_l mutable private
Definition at line 337 of file lu_map_.hpp.
m_size
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > size_type __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::m_size protected
Definition at line 462 of file bin_search_tree_.hpp.
s_const_end_it
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static const_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_const_end_it static private
Definition at line 595 of file cc_ht_map_.hpp.
s_const_find_end_it
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > const_point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_const_find_end_it static private
Definition at line 597 of file cc_ht_map_.hpp.
s_end_it
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_end_it static private
Definition at line 594 of file cc_ht_map_.hpp.
s_entry_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > static entry_allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_entry_allocator static private
Definition at line 592 of file cc_ht_map_.hpp.
s_entry_pointer_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > entry_pointer_allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_entry_pointer_allocator static private
Definition at line 593 of file cc_ht_map_.hpp.
s_eq_fn
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Eq_Fn __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_eq_fn static private
Definition at line 332 of file lu_map_.hpp.
s_find_end_it
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > point_iterator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_find_end_it static private
Definition at line 596 of file cc_ht_map_.hpp.
s_head_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > head_allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_head_allocator static private
Definition at line 485 of file pat_trie_.hpp.
s_internal_node_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > internal_node_allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_internal_node_allocator static private
Definition at line 486 of file pat_trie_.hpp.
s_leaf_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > leaf_allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_leaf_allocator static private
Definition at line 487 of file pat_trie_.hpp.
s_metadata_type_indicator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > type_to_type<update_metadata> __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_metadata_type_indicator static private
Definition at line 334 of file lu_map_.hpp.
s_node_allocator
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > node_allocator __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_node_allocator static protected
Definition at line 464 of file bin_search_tree_.hpp.
s_null_lu_metadata
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > null_lu_metadata __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_null_lu_metadata static private
Definition at line 335 of file lu_map_.hpp.
s_update_policy
template<typename Key , typename Mapped , class Cmp_Fn , class Node_And_It_Traits , class Allocator > Update_Policy __gnu_pbds::detail::PB_DS_CLASS_NAME< Key, Mapped, Cmp_Fn, Node_And_It_Traits, Allocator >::s_update_policy static private
Definition at line 333 of file lu_map_.hpp.
The documentation for this class was generated from the following files:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/bin_search_tree_/bin_search_tree_.hpp
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/cc_hash_table_map_/cc_ht_map_.hpp
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/gp_hash_table_map_/gp_ht_map_.hpp
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/list_update_map_/lu_map_.hpp
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/pat_trie_/pat_trie_.hpp
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/rb_tree_map_/rb_tree_.hpp
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/splay_tree_/splay_tree_.hpp