ZEQ2-Lite: Source/Engine/tools/asm/cmdlib.h File Reference
cmdlib.h File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <ctype.h>
#include <time.h>
#include <stdarg.h>
Data Structures
struct cblock_t
Macros
#define __BYTEBOOL__
#define MAX_OS_PATH 1024
#define MEM_BLOCKSIZE 4096
#define myoffsetof(type, identifier) ((size_t)&((type *)0)->identifier)
Typedefs
typedef unsigned char byte
Enumerations
enum qboolean { qfalse, qtrue, qfalse, qtrue }
Functions
void _printf (const char *format,...)
int CheckParm (const char *check)
char * COM_Parse (char *data)
char * copystring (const char *s)
void CRC_Init (unsigned short *crcvalue)
void CRC_ProcessByte (unsigned short *crcvalue, byte data)
unsigned short CRC_Value (unsigned short crcvalue)
void CreatePath (const char *path)
void DefaultExtension (char *path, const char *extension)
void DefaultPath (char *path, const char *basepath)
void Error (const char *error,...)
char * ExpandArg (const char *path)
char * ExpandGamePath (const char *path)
char * ExpandPath (const char *path)
char * ExpandPathAndArchive (const char *path)
void ExpandWildcards (int *argc, char ***argv)
void ExtractFileBase (const char *path, char *dest)
void ExtractFileExtension (const char *path, char *dest)
void ExtractFilePath (const char *path, char *dest)
qboolean FileExists (const char *filename)
int FileTime (const char *path)
double I_FloatTime (void)
int LoadFile (const char *filename, void **bufferptr)
int LoadFileBlock (const char *filename, void **bufferptr)
int ParseNum (const char *str)
int Q_filelength (FILE *f)
void Q_getwd (char *out)
void Q_mkdir (const char *path)
int Q_stricmp (const char *s1, const char *s2)
int Q_strncasecmp (const char *s1, const char *s2, int n)
void QCopyFile (const char *from, const char *to)
void qprintf (const char *format,...)
FILE * SafeOpenRead (const char *filename)
FILE * SafeOpenWrite (const char *filename)
void SafeRead (FILE *f, void *buffer, int count)
void SafeWrite (FILE *f, const void *buffer, int count)
void SaveFile (const char *filename, const void *buffer, int count)
void SetQdirFromPath (const char *path)
void StripExtension (char *path)
void StripFilename (char *path)
char * strlower (char *in)
char * strupr (char *in)
int TryLoadFile (const char *filename, void **bufferptr)
Variables
qboolean archive
char archivedir [1024]
qboolean com_eof
char com_token [1024]
char gamedir [1024]
int myargc
char ** myargv
char qdir [1024]
qboolean verbose
char writedir [1024]
Macro Definition Documentation
__BYTEBOOL__
#define __BYTEBOOL__
Definition at line 54 of file cmdlib.h.
MAX_OS_PATH
#define MAX_OS_PATH 1024
Definition at line 59 of file cmdlib.h.
MEM_BLOCKSIZE
#define MEM_BLOCKSIZE 4096
Definition at line 60 of file cmdlib.h.
myoffsetof
#define myoffsetof (type, identifier) ((size_t)&((type *)0)->identifier)
Definition at line 63 of file cmdlib.h.
Typedef Documentation
byte
typedef unsigned char byte
Definition at line 56 of file cmdlib.h.
Enumeration Type Documentation
qboolean
enum qboolean
Enumerator
qfalse
qtrue
qfalse
qtrue
Definition at line 55 of file cmdlib.h.
 { qfalse, qtrue } qboolean;
Function Documentation
_printf()
void _printf (const char * format, ...)
Definition at line 178 of file cmdlib.c.
{
     va_list argptr;
   char text[4096];
 #ifdef WIN32
   ATOM a;
 #endif
     va_start (argptr,format);
     vsprintf (text, format, argptr);
     va_end (argptr);
   printf("%s", text);
 #ifdef WIN32
   if (!lookedForServer) {
     lookedForServer = qtrue;
     hwndOut = FindWindow(NULL, "Q3Map Process Server");
     if (hwndOut) {
       wm_BroadcastCommand = RegisterWindowMessage( "Q3MPS_BroadcastCommand" );
     }
   }
   if (hwndOut) {
     a = GlobalAddAtom(text);
     PostMessage(hwndOut, wm_BroadcastCommand, 0, (LPARAM)a);
   }
 #endif
 }
References NULL, and qtrue.
Referenced by Error().
CheckParm()
int CheckParm (const char * check)
Definition at line 604 of file cmdlib.c.
 {
     int             i;
     for (i = 1;i<myargc;i++)
     {
         if ( !Q_stricmp(check, myargv[i]) )
             return i;
     }
     return 0;
 }
References check(), myargc, myargv, and Q_stricmp().
COM_Parse()
char* COM_Parse (char * data)
Definition at line 456 of file cmdlib.c.
 {
     int     c;
     int     len;
     len = 0;
     com_token[0] = 0;
     if (!data)
         return NULL;
 // skip whitespace
 skipwhite:
     while ( (c = *data) <= ' ')
     {
         if (c == 0)
         {
             com_eof = qtrue;
             return NULL;            // end of file;
         }
         data++;
     }
 // skip // comments
     if (c=='/' && data[1] == '/')
     {
         while (*data && *data != '\n')
             data++;
         goto skipwhite;
     }
 // handle quoted strings specially
     if (c == '\"')
     {
         data++;
         do
         {
             c = *data++;
             if (c=='\"')
             {
                 com_token[len] = 0;
                 return data;
             }
             com_token[len] = c;
             len++;
         } while (1);
     }
 // parse single characters
     if (c=='{' || c=='}'|| c==')'|| c=='(' || c=='\'' || c==':')
     {
         com_token[len] = c;
         len++;
         com_token[len] = 0;
         return data+1;
     }
 // parse a regular word
     do
     {
         com_token[len] = c;
         data++;
         len++;
         c = *data;
     if (c=='{' || c=='}'|| c==')'|| c=='(' || c=='\'' || c==':')
             break;
     } while (c>32);
     com_token[len] = 0;
     return data;
 }
References com_eof, com_token, NULL, and qtrue.
Referenced by ArenaServers_MenuDraw(), CG_DrawChat(), CG_Music_ParsePlaylist(), CG_ParseAnimationFile(), CL_LoadConsoleHistory(), IN_IsConsoleKey(), parseAura(), ParseOptionFile(), parseTier(), PSys_ParseConstraint(), PSys_ParseEmitter(), PSys_ParseFile(), PSys_ParseForce(), PSys_ParseParticleTemplate(), PSys_ParseSystem(), PSys_ParseVector(), R_GetEntityToken(), SV_GameSystemCalls(), UI_ParseAnimationFile(), UI_ParseInfos(), and VM_LoadSymbols().
copystring()
char* copystring (const char * s)
Definition at line 354 of file cmdlib.c.
 {
     char    *b;
     b = malloc(strlen(s)+1);
     strcpy (b, s);
     return b;
 }
Referenced by DefineSymbol(), main(), and ParseOptionFile().
CRC_Init()
void CRC_Init (unsigned short * crcvalue)
Definition at line 1064 of file cmdlib.c.
 {
     *crcvalue = CRC_INIT_VALUE;
 }
References CRC_INIT_VALUE.
CRC_ProcessByte()
void CRC_ProcessByte (unsigned short * crcvalue, byte data)
Definition at line 1069 of file cmdlib.c.
 {
     *crcvalue = (*crcvalue << 8) ^ crctable[(*crcvalue >> 8) ^ data];
 }
References crctable.
CRC_Value()
unsigned short CRC_Value (unsigned short crcvalue)
Definition at line 1074 of file cmdlib.c.
 {
     return crcvalue ^ CRC_XOR_VALUE;
 }
References CRC_XOR_VALUE.
CreatePath()
void CreatePath (const char * path)
Definition at line 1085 of file cmdlib.c.
 {
     const char  *ofs;
     char        c;
     char        dir[1024];
 #ifdef _WIN32
     int     olddrive = -1;
     if ( path[1] == ':' )
     {
         olddrive = _getdrive();
         _chdrive( toupper( path[0] ) - 'A' + 1 );
     }
 #endif
     if (path[1] == ':')
         path += 2;
     for (ofs = path+1 ; *ofs ; ofs++)
     {
         c = *ofs;
         if (c == '/' || c == '\\')
         {   // create the directory
             memcpy( dir, path, ofs - path );
             dir[ ofs - path ] = 0;
             Q_mkdir( dir );
         }
     }
 #ifdef _WIN32
     if ( olddrive != -1 )
     {
         _chdrive( olddrive );
     }
 #endif
 }
References dir, and Q_mkdir().
Referenced by QCopyFile(), and WriteVmFile().
DefaultExtension()
void DefaultExtension (char * path, const char * extension)
Definition at line 809 of file cmdlib.c.
 {
     char    *src;
 //
 // if path doesnt have a .EXT, append extension
 // (extension should include the .)
 //
     src = path + strlen(path) - 1;
     while (*src != '/' && *src != '\\' && src != path)
     {
         if (*src == '.')
             return;                 // it has an extension
         src--;
     }
     strcat (path, extension);
 }
Referenced by Assemble(), and ParseOptionFile().
DefaultPath()
void DefaultPath (char * path, const char * basepath)
Definition at line 829 of file cmdlib.c.
 {
     char    temp[128];
     if (path[0] == PATHSEPERATOR)
         return;                   // absolute path location
     strcpy (temp,path);
     strcpy (path,basepath);
     strcat (path,temp);
 }
References basepath(), and PATHSEPERATOR.
Error()
void Error (const char * error, ...)
Definition at line 143 of file cmdlib.c.
 {
     va_list argptr;
     _printf ("\n************ ERROR ************\n");
     va_start (argptr,error);
     vprintf (error,argptr);
     va_end (argptr);
     _printf ("\r\n");
     exit (1);
 }
References _printf(), and error().
Referenced by EmitByte(), EmitInt(), ExpandGamePath(), ExpandPath(), main(), ParseHex(), Q_mkdir(), SafeOpenRead(), SafeOpenWrite(), SafeRead(), SafeWrite(), SetQdirFromPath(), and ShowHelp().
ExpandArg()
char* ExpandArg (const char * path)
Definition at line 298 of file cmdlib.c.
 {
     static char full[1024];
     if (path[0] != '/' && path[0] != '\\' && path[1] != ':')
     {
         Q_getwd (full);
         strcat (full, path);
     }
     else
         strcpy (full, path);
     return full;
 }
References Q_getwd().
ExpandGamePath()
char* ExpandGamePath (const char * path)
Definition at line 325 of file cmdlib.c.
 {
     static char full[1024];
     if (!qdir[0])
         Error ("ExpandGamePath called without qdir set");
     if (path[0] == '/' || path[0] == '\\' || path[1] == ':') {
         strcpy( full, path );
         return full;
     }
     sprintf (full, "%s%s", gamedir, path);
     return full;
 }
References Error(), gamedir, and qdir.
ExpandPath()
char* ExpandPath (const char * path)
Definition at line 312 of file cmdlib.c.
 {
     static char full[1024];
     if (!qdir[0])
         Error ("ExpandPath called without qdir set");
     if (path[0] == '/' || path[0] == '\\' || path[1] == ':') {
         strcpy( full, path );
         return full;
     }
     sprintf (full, "%s%s", qdir, path);
     return full;
 }
References Error(), and qdir.
Referenced by ExpandPathAndArchive().
ExpandPathAndArchive()
char* ExpandPathAndArchive (const char * path)
Definition at line 338 of file cmdlib.c.
 {
     char    *expanded;
     char    archivename[1024];
     expanded = ExpandPath (path);
     if (archive)
     {
         sprintf (archivename, "%s/%s", archivedir, path);
         QCopyFile (expanded, archivename);
     }
     return expanded;
 }
References archive, archivedir, ExpandPath(), and QCopyFile().
ExpandWildcards()
void ExpandWildcards (int * argc, char *** argv)
Definition at line 102 of file cmdlib.c.
 {
 }
ExtractFileBase()
void ExtractFileBase (const char * path, char * dest)
Definition at line 890 of file cmdlib.c.
 {
     const char    *src;
     src = path + strlen(path) - 1;
 //
 // back up until a \ or the start
 //
     while (src != path && *(src-1) != PATHSEPERATOR)
         src--;
     while (*src && *src != '.')
     {
         *dest++ = *src++;
     }
     *dest = 0;
 }
References PATHSEPERATOR.
ExtractFileExtension()
void ExtractFileExtension (const char * path, char * dest)
Definition at line 909 of file cmdlib.c.
 {
     const char    *src;
     src = path + strlen(path) - 1;
 //
 // back up until a . or the start
 //
     while (src != path && *(src-1) != '.')
         src--;
     if (src == path)
     {
         *dest = 0;  // no extension
         return;
     }
     strcpy (dest,src);
 }
ExtractFilePath()
void ExtractFilePath (const char * path, char * dest)
Definition at line 874 of file cmdlib.c.
 {
     const char    *src;
     src = path + strlen(path) - 1;
 //
 // back up until a \ or the start
 //
     while (src != path && *(src-1) != '\\' && *(src-1) != '/')
         src--;
     memcpy (dest, path, src-path);
     dest[src-path] = 0;
 }
FileExists()
qboolean FileExists (const char * filename)
Definition at line 699 of file cmdlib.c.
 {
     FILE    *f;
     f = myfopen (filename, "r");
     if (!f)
         return qfalse;
     fclose (f);
     return qtrue;
 }
References myfopen(), qfalse, and qtrue.
FileTime()
int FileTime (const char * path)
Definition at line 437 of file cmdlib.c.
 {
     struct  stat    buf;
     if (stat (path,&buf) == -1)
         return -1;
     return buf.st_mtime;
 }
I_FloatTime()
double I_FloatTime (void)
Definition at line 369 of file cmdlib.c.
 {
     time_t  t;
     time (&t);
     return t;
 #if 0
 // more precise, less portable
     struct timeval tp;
     struct timezone tzp;
     static int      secbase;
     gettimeofday(&tp, &tzp);
     if (!secbase)
     {
         secbase = tp.tv_sec;
         return tp.tv_usec/1000000.0;
     }
     return (tp.tv_sec - secbase) + tp.tv_usec/1000000.0;
 #endif
 }
Referenced by main().
LoadFile()
int LoadFile (const char * filename, void ** bufferptr)
Definition at line 715 of file cmdlib.c.
 {
     FILE    *f;
     int    length;
     void    *buffer;
     f = SafeOpenRead (filename);
     length = Q_filelength (f);
     buffer = malloc (length+1);
     ((char *)buffer)[length] = 0;
     SafeRead (f, buffer, length);
     fclose (f);
     *bufferptr = buffer;
     return length;
 }
References Q_filelength(), SafeOpenRead(), and SafeRead().
Referenced by Assemble(), ParseOptionFile(), and QCopyFile().
LoadFileBlock()
int LoadFileBlock (const char * filename, void ** bufferptr)
Definition at line 741 of file cmdlib.c.
 {
     FILE    *f;
     int    length, nBlock, nAllocSize;
     void    *buffer;
     f = SafeOpenRead (filename);
     length = Q_filelength (f);
   nAllocSize = length;
   nBlock = nAllocSize % MEM_BLOCKSIZE;
   if ( nBlock > 0) {
     nAllocSize += MEM_BLOCKSIZE - nBlock;
   }
     buffer = malloc (nAllocSize+1);
   memset(buffer, 0, nAllocSize+1);
     SafeRead (f, buffer, length);
     fclose (f);
     *bufferptr = buffer;
     return length;
 }
References MEM_BLOCKSIZE, Q_filelength(), SafeOpenRead(), and SafeRead().
ParseNum()
int ParseNum (const char * str)
Definition at line 961 of file cmdlib.c.
 {
     if (str[0] == '$')
         return ParseHex (str+1);
     if (str[0] == '0' && str[1] == 'x')
         return ParseHex (str+2);
     return atol (str);
 }
References ParseHex().
Q_filelength()
int Q_filelength (FILE * f)
Definition at line 624 of file cmdlib.c.
 {
     int     pos;
     int     end;
     pos = ftell (f);
     fseek (f, 0, SEEK_END);
     end = ftell (f);
     fseek (f, pos, SEEK_SET);
     return end;
 }
References SEEK_END, and SEEK_SET.
Referenced by LoadFile(), LoadFileBlock(), and TryLoadFile().
Q_getwd()
void Q_getwd (char * out)
Definition at line 394 of file cmdlib.c.
 {
     int i = 0;
 #ifdef WIN32
    if (_getcwd (out, 256) == NULL)
      strcpy(out, ".");  /* shrug */
    strcat (out, "\\");
 #else
    if (getcwd (out, 256) == NULL)
      strcpy(out, ".");  /* shrug */
    strcat (out, "/");
 #endif
    while ( out[i] != 0 )
    {
        if ( out[i] == '\\' )
            out[i] = '/';
        i++;
    }
 }
References NULL, and out.
Referenced by ExpandArg(), and SetQdirFromPath().
Q_mkdir()
void Q_mkdir (const char * path)
Definition at line 417 of file cmdlib.c.
 {
 #ifdef WIN32
     if (_mkdir (path) != -1)
         return;
 #else
     if (mkdir (path, 0777) != -1)
         return;
 #endif
     if (errno != EEXIST)
         Error ("mkdir %s: %s",path, strerror(errno));
 }
References Error().
Referenced by CreatePath().
Q_stricmp()
int Q_stricmp (const char * s1, const char * s2)
Definition at line 556 of file cmdlib.c.
 {
     return Q_strncasecmp (s1, s2, 99999);
 }
Q_strncasecmp()
int Q_strncasecmp (const char * s1, const char * s2, int n)
Definition at line 530 of file cmdlib.c.
 {
     int     c1, c2;
     do
     {
         c1 = *s1++;
         c2 = *s2++;
         if (!n--)
             return 0;       // strings are equal until end point
         if (c1 != c2)
         {
             if (c1 >= 'a' && c1 <= 'z')
                 c1 -= ('a' - 'A');
             if (c2 >= 'a' && c2 <= 'z')
                 c2 -= ('a' - 'A');
             if (c1 != c2)
                 return -1;      // strings not equal
         }
     } while (c1);
     return 0;       // strings are equal
 }
Referenced by Q_stricmp(), and SetQdirFromPath().
QCopyFile()
void QCopyFile (const char * from, const char * to)
Definition at line 1131 of file cmdlib.c.
 {
     void    *buffer;
     int     length;
     length = LoadFile (from, &buffer);
     CreatePath (to);
     SaveFile (to, buffer, length);
     free (buffer);
 }
References CreatePath(), LoadFile(), and SaveFile().
Referenced by ExpandPathAndArchive().
qprintf()
void qprintf (const char * format, ...)
Definition at line 160 of file cmdlib.c.
{
     va_list argptr;
     if (!verbose)
         return;
     va_start (argptr,format);
     vprintf (format,argptr);
     va_end (argptr);
 }
References verbose.
Referenced by SetQdirFromPath().
SafeOpenRead()
FILE* SafeOpenRead (const char * filename)
Definition at line 667 of file cmdlib.c.
 {
     FILE    *f;
     f = myfopen(filename, "rb");
     if (!f)
         Error ("Error opening %s: %s",filename,strerror(errno));
     return f;
 }
References Error(), and myfopen().
Referenced by LoadFile(), and LoadFileBlock().
SafeOpenWrite()
FILE* SafeOpenWrite (const char * filename)
Definition at line 655 of file cmdlib.c.
 {
     FILE    *f;
     f = myfopen(filename, "wb");
     if (!f)
         Error ("Error opening %s: %s",filename,strerror(errno));
     return f;
 }
References Error(), and myfopen().
Referenced by SaveFile(), WriteMapFile(), and WriteVmFile().
SafeRead()
void SafeRead (FILE * f, void * buffer, int count)
Definition at line 680 of file cmdlib.c.
 {
     if ( fread (buffer, 1, count, f) != (size_t)count)
         Error ("File read failure");
 }
References Error(), and fread().
Referenced by LoadFile(), LoadFileBlock(), and TryLoadFile().
SafeWrite()
void SafeWrite (FILE * f, const void * buffer, int count)
Definition at line 687 of file cmdlib.c.
 {
     if (fwrite (buffer, 1, count, f) != (size_t)count)
         Error ("File write failure");
 }
References Error(), and fwrite().
Referenced by SaveFile(), and WriteVmFile().
SaveFile()
void SaveFile (const char * filename, const void * buffer, int count)
Definition at line 798 of file cmdlib.c.
 {
     FILE    *f;
     f = SafeOpenWrite (filename);
     SafeWrite (f, buffer, count);
     fclose (f);
 }
References SafeOpenWrite(), and SafeWrite().
Referenced by QCopyFile().
SetQdirFromPath()
void SetQdirFromPath (const char * path)
Definition at line 221 of file cmdlib.c.
 {
     char    temp[1024];
     const char  *c;
   const char *sep;
     int     len, count;
     if (!(path[0] == '/' || path[0] == '\\' || path[1] == ':'))
     {   // path is partial
         Q_getwd (temp);
         strcat (temp, path);
         path = temp;
     }
     // search for "quake2" in path
     len = strlen(BASEDIRNAME);
     for (c=path+strlen(path)-1 ; c != path ; c--)
     {
         int i;
         if (!Q_strncasecmp (c, BASEDIRNAME, len))
         {
       //
             //strncpy (qdir, path, c+len+2-path);
       // the +2 assumes a 2 or 3 following quake which is not the
       // case with a retail install
       // so we need to add up how much to the next separator
       sep = c + len;
       count = 1;
       while (*sep && *sep != '/' && *sep != '\\')
       {
         sep++;
         count++;
       }
             strncpy (qdir, path, c+len+count-path);
             qprintf ("qdir: %s\n", qdir);
             for ( i = 0; i < strlen( qdir ); i++ )
             {
                 if ( qdir[i] == '\\' )
                     qdir[i] = '/';
             }
             c += len+count;
             while (*c)
             {
                 if (*c == '/' || *c == '\\')
                 {
                     strncpy (gamedir, path, c+1-path);
                     for ( i = 0; i < strlen( gamedir ); i++ )
                     {
                         if ( gamedir[i] == '\\' )
                             gamedir[i] = '/';
                     }
                     qprintf ("gamedir: %s\n", gamedir);
                     if ( !writedir[0] )
                         strcpy( writedir, gamedir );
                     else if ( writedir[strlen( writedir )-1] != '/' )
                     {
                         writedir[strlen( writedir )] = '/';
                         writedir[strlen( writedir )+1] = 0;
                     }
                     return;
                 }
                 c++;
             }
             Error ("No gamedir in %s", path);
             return;
         }
     }
     Error ("SetQdirFromPath: no '%s' in %s", BASEDIRNAME, path);
 }
References BASEDIRNAME, Error(), gamedir, Q_getwd(), Q_strncasecmp(), qdir, qprintf(), and writedir.
StripExtension()
void StripExtension (char * path)
Definition at line 851 of file cmdlib.c.
 {
     int             length;
     length = strlen(path)-1;
     while (length > 0 && path[length] != '.')
     {
         length--;
         if (path[length] == '/')
             return;     // no extension
     }
     if (length)
         path[length] = 0;
 }
Referenced by WriteMapFile(), and WriteVmFile().
StripFilename()
void StripFilename (char * path)
Definition at line 841 of file cmdlib.c.
 {
     int             length;
     length = strlen(path)-1;
     while (length > 0 && path[length] != PATHSEPERATOR)
         length--;
     path[length] = 0;
 }
References PATHSEPERATOR.
strlower()
char* strlower (char * in)
Definition at line 574 of file cmdlib.c.
 {
     char    *in;
     in = start;
     while (*in)
     {
         *in = tolower(*in);
         in++;
     }
     return start;
 }
strupr()
char* strupr (char * in)
Definition at line 562 of file cmdlib.c.
 {
     char    *in;
     in = start;
     while (*in)
     {
         *in = toupper(*in);
         in++;
     }
     return start;
 }
TryLoadFile()
int TryLoadFile (const char * filename, void ** bufferptr)
Definition at line 771 of file cmdlib.c.
 {
     FILE    *f;
     int    length;
     void    *buffer;
     *bufferptr = NULL;
     f = myfopen (filename, "rb");
     if (!f)
         return -1;
     length = Q_filelength (f);
     buffer = malloc (length+1);
     ((char *)buffer)[length] = 0;
     SafeRead (f, buffer, length);
     fclose (f);
     *bufferptr = buffer;
     return length;
 }
References myfopen(), NULL, Q_filelength(), and SafeRead().
Variable Documentation
archive
qboolean archive
Definition at line 47 of file cmdlib.c.
Referenced by ExpandPathAndArchive().
archivedir
char archivedir[1024]
Definition at line 48 of file cmdlib.c.
Referenced by ExpandPathAndArchive().
com_eof
qboolean com_eof
Definition at line 45 of file cmdlib.c.
Referenced by COM_Parse().
com_token
char com_token[1024]
Definition at line 44 of file cmdlib.c.
Referenced by COM_Parse(), CommaParse(), G_ParseSpawnVars(), and ParseOptionFile().
gamedir
char gamedir[1024]
Definition at line 218 of file cmdlib.c.
Referenced by ExpandGamePath(), SetQdirFromPath(), SVC_Info(), and Sys_ErrorDialog().
myargc
int myargc
Definition at line 41 of file cmdlib.c.
Referenced by CheckParm().
myargv
char** myargv
Definition at line 42 of file cmdlib.c.
Referenced by CheckParm().
qdir
char qdir[1024]
Definition at line 217 of file cmdlib.c.
Referenced by ExpandGamePath(), ExpandPath(), and SetQdirFromPath().
verbose
qboolean verbose
Definition at line 159 of file cmdlib.c.
writedir
char writedir[1024]
Definition at line 219 of file cmdlib.c.
Referenced by SetQdirFromPath().