ZEQ2-Lite: __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator > Class Template Reference
__gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator > Class Template Reference
#include <point_iterators.hpp>
Public Types
typedef Type_Traits::const_pointer const_pointer
typedef Type_Traits::const_reference const_reference
typedef Allocator::difference_type difference_type
typedef std::bidirectional_iterator_tag iterator_category
typedef Type_Traits::pointer pointer
typedef Type_Traits::reference reference
typedef Type_Traits::value_type value_type
Public Member Functions
pat_trie_const_it_ (const PB_DS_CONST_ODIR_IT_C_DEC &other)
pat_trie_const_it_ (node_pointer p_nd=0)
bool operator!= (const PB_DS_CONST_IT_C_DEC &other) const
bool operator!= (const PB_DS_CONST_ODIR_IT_C_DEC &other) const
const_reference operator* () const
PB_DS_CONST_IT_C_DEC & operator++ ()
PB_DS_CONST_IT_C_DEC operator++ (int)
PB_DS_CONST_IT_C_DEC & operator-- ()
PB_DS_CONST_IT_C_DEC operator-- (int)
const_pointer operator-> () const
PB_DS_CONST_IT_C_DEC & operator= (const PB_DS_CONST_IT_C_DEC &other)
PB_DS_CONST_IT_C_DEC & operator= (const PB_DS_CONST_ODIR_IT_C_DEC &other)
bool operator== (const PB_DS_CONST_IT_C_DEC &other) const
bool operator== (const PB_DS_CONST_ODIR_IT_C_DEC &other) const
Data Fields
node_pointer m_p_nd
Protected Member Functions
void dec (false_type)
void dec (true_type)
void inc (false_type)
void inc (true_type)
Static Protected Member Functions
static node_pointer get_larger_sibling (node_pointer p_nd)
static node_pointer get_smaller_sibling (node_pointer p_nd)
static leaf_pointer leftmost_descendant (node_pointer p_nd)
static leaf_pointer rightmost_descendant (node_pointer p_nd)
Private Types
typedef Allocator::template rebind< Leaf >::other::const_pointer const_leaf_pointer
typedef Allocator::template rebind< Head >::other::pointer head_pointer
typedef Allocator::template rebind< Internal_Node >::other::pointer internal_node_pointer
typedef Allocator::template rebind< Leaf >::other::pointer leaf_pointer
typedef Allocator::template rebind< Node >::other::pointer node_pointer
Detailed Description
template<typename Type_Traits, class Node, class Leaf, class Head, class Internal_Node, bool Is_Forward_Iterator, class Allocator>
class __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >
Definition at line 100 of file point_iterators.hpp.
Member Typedef Documentation
const_leaf_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Leaf>::other::const_pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::const_leaf_pointer private
Definition at line 112 of file point_iterators.hpp.
const_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::const_pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::const_pointer
Definition at line 139 of file point_iterators.hpp.
const_reference
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::const_reference __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::const_reference
Definition at line 143 of file point_iterators.hpp.
difference_type
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::difference_type
Definition at line 133 of file point_iterators.hpp.
head_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Head>::other::pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::head_pointer private
Definition at line 122 of file point_iterators.hpp.
internal_node_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Internal_Node>::other::pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::internal_node_pointer private
Definition at line 127 of file point_iterators.hpp.
iterator_category
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef std::bidirectional_iterator_tag __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::iterator_category
Definition at line 131 of file point_iterators.hpp.
leaf_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Leaf>::other::pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::leaf_pointer private
Definition at line 117 of file point_iterators.hpp.
node_pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Allocator::template rebind< Node>::other::pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::node_pointer private
Definition at line 107 of file point_iterators.hpp.
pointer
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::pointer
Definition at line 137 of file point_iterators.hpp.
reference
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::reference __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::reference
Definition at line 141 of file point_iterators.hpp.
value_type
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > typedef Type_Traits::value_type __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::value_type
Definition at line 135 of file point_iterators.hpp.
Constructor & Destructor Documentation
pat_trie_const_it_() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::pat_trie_const_it_ (node_pointer p_nd = 0) inline
Definition at line 148 of file point_iterators.hpp.
                                                 : m_p_nd(p_nd)
       { }
pat_trie_const_it_() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::pat_trie_const_it_ (const PB_DS_CONST_ODIR_IT_C_DEC & other) inline
Definition at line 152 of file point_iterators.hpp.
       : m_p_nd(other.m_p_nd)
       { }
Member Function Documentation
dec() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > void __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::dec (false_type) inline protected
Definition at line 263 of file point_iterators.hpp.
       { inc(true_type()); }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::inc().
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::inc(), and __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator--().
dec() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > void __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::dec (true_type) inline protected
Definition at line 267 of file point_iterators.hpp.
       {
     if (m_p_nd->m_type == pat_trie_head_node_type)
       {
         m_p_nd = static_cast<head_pointer>(m_p_nd)->m_p_max;
         return;
       }
     node_pointer p_y = m_p_nd->m_p_parent;
     while (p_y->m_type != pat_trie_head_node_type &&
            get_smaller_sibling(m_p_nd) == 0)
       {
         m_p_nd = p_y;
         p_y = p_y->m_p_parent;
       }
     if (p_y->m_type == pat_trie_head_node_type)
       {
         m_p_nd = p_y;
         return;
       }
     m_p_nd = rightmost_descendant(get_smaller_sibling(m_p_nd));
       }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::get_smaller_sibling(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd, __gnu_pbds::detail::pat_trie_head_node_type, and __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::rightmost_descendant().
get_larger_sibling()
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > static node_pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::get_larger_sibling (node_pointer p_nd) inline static protected
Definition at line 292 of file point_iterators.hpp.
       {
     internal_node_pointer p_parent =
       static_cast<internal_node_pointer>(p_nd->m_p_parent);
     typename Internal_Node::iterator it = p_parent->begin();
     while (*it != p_nd)
       ++it;
     typename Internal_Node::iterator next_it = it;
     ++next_it;
     return ((next_it == p_parent->end())? 0 :* next_it);
       }
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::inc().
get_smaller_sibling()
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > static node_pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::get_smaller_sibling (node_pointer p_nd) inline static protected
Definition at line 307 of file point_iterators.hpp.
       {
     internal_node_pointer p_parent =
       static_cast<internal_node_pointer>(p_nd->m_p_parent);
     typename Internal_Node::iterator it = p_parent->begin();
     if (*it == p_nd)
       return (0);
     typename Internal_Node::iterator prev_it;
     do
       {
         prev_it = it;
         ++it;
         if (*it == p_nd)
           return (*prev_it);
       }
     while (true);
     _GLIBCXX_DEBUG_ASSERT(false);
     return (0);
       }
References _GLIBCXX_DEBUG_ASSERT.
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::dec().
inc() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > void __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::inc (false_type) inline protected
Definition at line 234 of file point_iterators.hpp.
       { dec(true_type()); }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::dec().
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::dec(), and __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++().
inc() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > void __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::inc (true_type) inline protected
Definition at line 238 of file point_iterators.hpp.
       {
     if (m_p_nd->m_type == pat_trie_head_node_type)
       {
         m_p_nd = static_cast<head_pointer>(m_p_nd)->m_p_min;
         return;
       }
     node_pointer p_y = m_p_nd->m_p_parent;
     while (p_y->m_type != pat_trie_head_node_type &&
            get_larger_sibling(m_p_nd) == 0)
       {
         m_p_nd = p_y;
         p_y = p_y->m_p_parent;
       }
     if (p_y->m_type == pat_trie_head_node_type)
       {
         m_p_nd = p_y;
         return;
       }
     m_p_nd = leftmost_descendant(get_larger_sibling(m_p_nd));
       }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::get_larger_sibling(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::leftmost_descendant(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd, and __gnu_pbds::detail::pat_trie_head_node_type.
leftmost_descendant()
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > static leaf_pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::leftmost_descendant (node_pointer p_nd) inline static protected
Definition at line 331 of file point_iterators.hpp.
       {
     if (p_nd->m_type == pat_trie_leaf_node_type)
       return static_cast<leaf_pointer>(p_nd);
     return static_cast<internal_node_pointer>(p_nd)->leftmost_descendant();
       }
References __gnu_pbds::detail::pat_trie_leaf_node_type.
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::inc().
operator!=() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > bool __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator!= (const PB_DS_CONST_IT_C_DEC & other) const inline
Definition at line 195 of file point_iterators.hpp.
       { return (m_p_nd != other.m_p_nd); }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd.
operator!=() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > bool __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator!= (const PB_DS_CONST_ODIR_IT_C_DEC & other) const inline
Definition at line 199 of file point_iterators.hpp.
       { return (m_p_nd != other.m_p_nd); }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd.
operator*()
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > const_reference __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator* () const inline
Definition at line 180 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_p_nd->m_type == pat_trie_leaf_node_type);
     return static_cast<leaf_pointer>(m_p_nd)->value();
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd, and __gnu_pbds::detail::pat_trie_leaf_node_type.
operator++() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_CONST_IT_C_DEC& __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++ () inline
Definition at line 203 of file point_iterators.hpp.
       {
     inc(integral_constant<int,Is_Forward_Iterator>());
     return *this;
       }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::inc().
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++().
operator++() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_CONST_IT_C_DEC __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++ (int) inline
Definition at line 210 of file point_iterators.hpp.
       {
     PB_DS_CONST_IT_C_DEC ret_it(m_p_nd);
     operator++();
     return ret_it;
       }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd, and __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++().
operator--() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_CONST_IT_C_DEC& __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator-- () inline
Definition at line 218 of file point_iterators.hpp.
       {
     dec(integral_constant<int,Is_Forward_Iterator>());
     return *this;
       }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::dec().
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator--().
operator--() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_CONST_IT_C_DEC __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator-- (int) inline
Definition at line 225 of file point_iterators.hpp.
       {
     PB_DS_CONST_IT_C_DEC ret_it(m_p_nd);
     operator--();
     return ret_it;
       }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd, and __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator--().
operator->()
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > const_pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator-> () const inline
Definition at line 173 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_p_nd->m_type == pat_trie_leaf_node_type);
     return &static_cast<leaf_pointer>(m_p_nd)->value();
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd, and __gnu_pbds::detail::pat_trie_leaf_node_type.
operator=() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_CONST_IT_C_DEC& __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator= (const PB_DS_CONST_IT_C_DEC & other) inline
Definition at line 158 of file point_iterators.hpp.
       {
     m_p_nd = other.m_p_nd;
     return *this;
       }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd.
operator=() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > PB_DS_CONST_IT_C_DEC& __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator= (const PB_DS_CONST_ODIR_IT_C_DEC & other) inline
Definition at line 166 of file point_iterators.hpp.
       {
     m_p_nd = other.m_p_nd;
     return *this;
       }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd.
operator==() [1/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > bool __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator== (const PB_DS_CONST_IT_C_DEC & other) const inline
Definition at line 187 of file point_iterators.hpp.
       { return (m_p_nd == other.m_p_nd); }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd.
operator==() [2/2]
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > bool __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator== (const PB_DS_CONST_ODIR_IT_C_DEC & other) const inline
Definition at line 191 of file point_iterators.hpp.
       { return (m_p_nd == other.m_p_nd); }
References __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd.
rightmost_descendant()
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > static leaf_pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::rightmost_descendant (node_pointer p_nd) inline static protected
Definition at line 339 of file point_iterators.hpp.
       {
     if (p_nd->m_type == pat_trie_leaf_node_type)
       return static_cast<leaf_pointer>(p_nd);
     return static_cast<internal_node_pointer>(p_nd)->rightmost_descendant();
       }
References __gnu_pbds::detail::pat_trie_leaf_node_type.
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::dec().
Field Documentation
m_p_nd
template<typename Type_Traits , class Node , class Leaf , class Head , class Internal_Node , bool Is_Forward_Iterator, class Allocator > node_pointer __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::m_p_nd
Definition at line 347 of file point_iterators.hpp.
Referenced by __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::dec(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::inc(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator!=(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator*(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator++(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator--(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator->(), __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator=(), and __gnu_pbds::detail::pat_trie_const_it_< Type_Traits, Node, Leaf, Head, Internal_Node, Is_Forward_Iterator, Allocator >::operator==().
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/pat_trie_/point_iterators.hpp