ZEQ2-Lite: __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator > Class Template Reference
__gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator > Class Template Reference
#include <node_iterators.hpp>
Public Types
typedef Allocator::template rebind< metadata_type >::other::const_reference const_metadata_reference
typedef Allocator::template rebind< typename remove_const< Value_Type >::type >::other::const_pointer const_reference
typedef trivial_iterator_difference_type difference_type
typedef trivial_iterator_tag iterator_category
typedef Metadata_Type metadata_type
typedef Allocator::template rebind< typename remove_const< Value_Type >::type >::other::const_pointer reference
typedef Allocator::template rebind< Value_Type >::other::const_pointer value_type
Public Member Functions
ov_tree_node_const_it_ (const_pointer p_nd=0, const_pointer p_begin_nd=0, const_pointer p_end_nd=0, const_metadata_pointer p_metadata=0)
this_type get_l_child () const
const_metadata_reference get_metadata () const
this_type get_r_child () const
bool operator!= (const this_type &other) const
const_reference operator* () const
bool operator== (const this_type &other) const
Data Fields
pointer m_p_begin_value
pointer m_p_end_value
const_metadata_pointer m_p_metadata
pointer m_p_value
Protected Types
typedef Allocator::template rebind< Metadata_Type >::other::const_pointer const_metadata_pointer
typedef Allocator::template rebind< Value_Type >::other::const_pointer const_pointer
typedef Allocator::template rebind< Value_Type >::other::pointer pointer
typedef PB_DS_OV_TREE_CONST_NODE_ITERATOR_C_DEC this_type
Static Protected Member Functions
template<typename Ptr >
static Ptr mid_pointer (Ptr p_begin, Ptr p_end)
Detailed Description
template<typename Value_Type, typename Metadata_Type, class Allocator>
class __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >
Definition at line 58 of file node_iterators.hpp.
Member Typedef Documentation
const_metadata_pointer
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef Allocator::template rebind< Metadata_Type>::other::const_pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::const_metadata_pointer protected
Definition at line 75 of file node_iterators.hpp.
const_metadata_reference
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef Allocator::template rebind< metadata_type>::other::const_reference __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::const_metadata_reference
Definition at line 117 of file node_iterators.hpp.
const_pointer
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef Allocator::template rebind< Value_Type>::other::const_pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::const_pointer protected
Definition at line 70 of file node_iterators.hpp.
const_reference
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef Allocator::template rebind< typename remove_const< Value_Type>::type>::other::const_pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::const_reference
Definition at line 110 of file node_iterators.hpp.
difference_type
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef trivial_iterator_difference_type __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::difference_type
Definition at line 93 of file node_iterators.hpp.
iterator_category
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef trivial_iterator_tag __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::iterator_category
Definition at line 91 of file node_iterators.hpp.
metadata_type
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef Metadata_Type __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::metadata_type
Definition at line 112 of file node_iterators.hpp.
pointer
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef Allocator::template rebind< Value_Type>::other::pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::pointer protected
Definition at line 65 of file node_iterators.hpp.
reference
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef Allocator::template rebind< typename remove_const< Value_Type>::type>::other::const_pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::reference
Definition at line 104 of file node_iterators.hpp.
this_type
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef PB_DS_OV_TREE_CONST_NODE_ITERATOR_C_DEC __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::this_type protected
Definition at line 77 of file node_iterators.hpp.
value_type
template<typename Value_Type , typename Metadata_Type , class Allocator > typedef Allocator::template rebind< Value_Type>::other::const_pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::value_type
Definition at line 98 of file node_iterators.hpp.
Constructor & Destructor Documentation
ov_tree_node_const_it_()
template<typename Value_Type , typename Metadata_Type , class Allocator > __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::ov_tree_node_const_it_ (const_pointer p_nd = 0, const_pointer p_begin_nd = 0, const_pointer p_end_nd = 0, const_metadata_pointer p_metadata = 0) inline
Definition at line 121 of file node_iterators.hpp.
                                                                                                                                                          : m_p_value(const_cast<pointer>(p_nd)), m_p_begin_value(const_cast<pointer>(p_begin_nd)), m_p_end_value(const_cast<pointer>(p_end_nd)), m_p_metadata(p_metadata)
       { }
Member Function Documentation
get_l_child()
template<typename Value_Type , typename Metadata_Type , class Allocator > this_type __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_l_child () const inline
Definition at line 142 of file node_iterators.hpp.
       {
     if (m_p_begin_value == m_p_value)
       return (this_type(m_p_begin_value, m_p_begin_value, m_p_begin_value));
     const_metadata_pointer p_begin_metadata =
       m_p_metadata - (m_p_value - m_p_begin_value);
     return (this_type(mid_pointer(m_p_begin_value, m_p_value),
               m_p_begin_value,
               m_p_value,
               mid_pointer(p_begin_metadata, m_p_metadata)));
       }
References __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_begin_value, __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_metadata, __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_value, and __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::mid_pointer().
get_metadata()
template<typename Value_Type , typename Metadata_Type , class Allocator > const_metadata_reference __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_metadata () const inline
Definition at line 129 of file node_iterators.hpp.
       {
     enum
       {
         has_metadata = !is_same<Metadata_Type, null_node_metadata>::value
       };
     PB_DS_STATIC_ASSERT(should_have_metadata, has_metadata);
     _GLIBCXX_DEBUG_ASSERT(m_p_metadata != 0);
     return *m_p_metadata;
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_metadata, and PB_DS_STATIC_ASSERT.
get_r_child()
template<typename Value_Type , typename Metadata_Type , class Allocator > this_type __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_r_child () const inline
Definition at line 157 of file node_iterators.hpp.
       {
     if (m_p_value == m_p_end_value)
       return (this_type(m_p_end_value,  m_p_end_value,  m_p_end_value));
     const_metadata_pointer p_end_metadata =
       m_p_metadata + (m_p_end_value - m_p_value);
     return (this_type(mid_pointer(m_p_value + 1, m_p_end_value),
               m_p_value + 1,
               m_p_end_value,(m_p_metadata == 0) ?
               0 : mid_pointer(m_p_metadata + 1, p_end_metadata)));
       }
References __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_end_value, __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_metadata, __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_value, and __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::mid_pointer().
mid_pointer()
template<typename Value_Type , typename Metadata_Type , class Allocator > template<typename Ptr > static Ptr __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::mid_pointer (Ptr p_begin, Ptr p_end) inline static protected
Definition at line 83 of file node_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(p_end >= p_begin);
     return (p_begin + (p_end - p_begin) / 2);
       }
References _GLIBCXX_DEBUG_ASSERT.
Referenced by __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_l_child(), and __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_r_child().
operator!=()
template<typename Value_Type , typename Metadata_Type , class Allocator > bool __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator!= (const this_type & other) const inline
Definition at line 187 of file node_iterators.hpp.
       { return !operator==(other); }
References __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator==().
operator*()
template<typename Value_Type , typename Metadata_Type , class Allocator > const_reference __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator* () const inline
Definition at line 125 of file node_iterators.hpp.
       { return m_p_value; }
References __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_value.
operator==()
template<typename Value_Type , typename Metadata_Type , class Allocator > bool __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator== (const this_type & other) const inline
Definition at line 172 of file node_iterators.hpp.
       {
     const bool is_end = m_p_begin_value == m_p_end_value;
     const bool is_other_end = other.m_p_begin_value == other.m_p_end_value;
     if (is_end)
       return (is_other_end);
     if (is_other_end)
       return (is_end);
     return m_p_value == other.m_p_value;
       }
References __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_begin_value, __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_end_value, and __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_value.
Referenced by __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator!=().
Field Documentation
m_p_begin_value
template<typename Value_Type , typename Metadata_Type , class Allocator > pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_begin_value
Definition at line 192 of file node_iterators.hpp.
Referenced by __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_l_child(), and __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator==().
m_p_end_value
template<typename Value_Type , typename Metadata_Type , class Allocator > pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_end_value
Definition at line 193 of file node_iterators.hpp.
Referenced by __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_r_child(), and __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator==().
m_p_metadata
template<typename Value_Type , typename Metadata_Type , class Allocator > const_metadata_pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_metadata
Definition at line 195 of file node_iterators.hpp.
Referenced by __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_l_child(), __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_metadata(), and __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_r_child().
m_p_value
template<typename Value_Type , typename Metadata_Type , class Allocator > pointer __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::m_p_value
Definition at line 191 of file node_iterators.hpp.
Referenced by __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_l_child(), __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::get_r_child(), __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator*(), and __gnu_pbds::detail::ov_tree_node_const_it_< Value_Type, Metadata_Type, Allocator >::operator==().
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/ov_tree_map_/node_iterators.hpp