ZEQ2-Lite: Tools/MinGW/include/signal.h File Reference
signal.h File Reference
#include <_mingw.h>
Macros
#define _SIG_ATOMIC_T_DEFINED
#define NSIG 23 /* maximum signal number + 1 */
#define SIG_ACK ((__p_sig_fn_t) 4)
#define SIG_DFL ((__p_sig_fn_t) 0)
#define SIG_ERR ((__p_sig_fn_t) -1)
#define SIG_IGN ((__p_sig_fn_t) 1)
#define SIG_SGE ((__p_sig_fn_t) 3)
#define SIGABRT 22 /* Abnormal termination (abort) */
#define SIGBREAK 21 /* Control-break */
#define SIGFPE 8 /* Floating point error */
#define SIGILL 4 /* Illegal instruction */
#define SIGINT 2 /* Interactive attention */
#define SIGSEGV 11 /* Segmentation violation */
#define SIGTERM 15 /* Termination request */
Typedefs
typedef void(* __p_sig_fn_t) (int)
typedef int sig_atomic_t
Functions
_CRTIMP int __cdecl __MINGW_NOTHROW raise (int)
_CRTIMP __p_sig_fn_t __cdecl __MINGW_NOTHROW signal (int, __p_sig_fn_t)
Macro Definition Documentation
_SIG_ATOMIC_T_DEFINED
#define _SIG_ATOMIC_T_DEFINED
Definition at line 47 of file signal.h.
NSIG
#define NSIG 23 /* maximum signal number + 1 */
Definition at line 41 of file signal.h.
SIG_ACK
#define SIG_ACK ((__p_sig_fn_t) 4)
Definition at line 72 of file signal.h.
SIG_DFL
#define SIG_DFL ((__p_sig_fn_t) 0)
Definition at line 68 of file signal.h.
SIG_ERR
#define SIG_ERR ((__p_sig_fn_t) -1)
Definition at line 70 of file signal.h.
SIG_IGN
#define SIG_IGN ((__p_sig_fn_t) 1)
Definition at line 69 of file signal.h.
SIG_SGE
#define SIG_SGE ((__p_sig_fn_t) 3)
Definition at line 71 of file signal.h.
SIGABRT
#define SIGABRT 22 /* Abnormal termination (abort) */
Definition at line 39 of file signal.h.
SIGBREAK
#define SIGBREAK 21 /* Control-break */
Definition at line 38 of file signal.h.
SIGFPE
#define SIGFPE 8 /* Floating point error */
Definition at line 35 of file signal.h.
SIGILL
#define SIGILL 4 /* Illegal instruction */
Definition at line 34 of file signal.h.
SIGINT
#define SIGINT 2 /* Interactive attention */
Definition at line 33 of file signal.h.
SIGSEGV
#define SIGSEGV 11 /* Segmentation violation */
Definition at line 36 of file signal.h.
SIGTERM
#define SIGTERM 15 /* Termination request */
Definition at line 37 of file signal.h.
Typedef Documentation
__p_sig_fn_t
typedef void(* __p_sig_fn_t) (int)
Definition at line 60 of file signal.h.
sig_atomic_t
typedef int sig_atomic_t
Definition at line 46 of file signal.h.
Function Documentation
raise()
_CRTIMP int __cdecl __MINGW_NOTHROW raise (int)
signal()
_CRTIMP __p_sig_fn_t __cdecl __MINGW_NOTHROW signal (int , __p_sig_fn_t)
Referenced by CON_Init(), main(), Sys_PlatformInit(), and Sys_SigHandler().