ZEQ2-Lite: Tools/MinGW/include/setjmp.h File Reference
setjmp.h File Reference
#include <_mingw.h>
Macros
#define _JBLEN 16
#define _JBTYPE int
#define setjmp(x) _setjmp(x)
Typedefs
typedef _JBTYPE jmp_buf[_JBLEN]
Functions
_CRTIMP int __cdecl __MINGW_NOTHROW _setjmp (jmp_buf)
_CRTIMP void __cdecl __MINGW_NOTHROW longjmp (jmp_buf, int) __MINGW_ATTRIB_NORETURN
Macro Definition Documentation
_JBLEN
#define _JBLEN 16
Definition at line 31 of file setjmp.h.
_JBTYPE
#define _JBTYPE int
Definition at line 32 of file setjmp.h.
setjmp
#define setjmp (x) _setjmp(x)
Definition at line 41 of file setjmp.h.
Typedef Documentation
jmp_buf
typedef _JBTYPE jmp_buf[_JBLEN]
Definition at line 33 of file setjmp.h.
Function Documentation
_setjmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _setjmp (jmp_buf)
longjmp()
_CRTIMP void __cdecl __MINGW_NOTHROW longjmp (jmp_buf , int)
Referenced by bits(), Com_Error(), and decode().