ZEQ2-Lite: Engine/sys/con_win32.c File Reference
con_win32.c File Reference
#include "../../Shared/q_shared.h"
#include "../../Shared/qcommon.h"
#include "sys_local.h"
#include "windows.h"
Macros
#define QCONSOLE_HISTORY 32
Functions
static BOOL WINAPI CON_CtrlHandler (DWORD sig)
static void CON_HistAdd (void)
static void CON_HistNext (void)
static void CON_HistPrev (void)
void CON_Init (void)
char * CON_Input (void)
void CON_Print (const char *msg)
static void CON_Show (void)
void CON_Shutdown (void)
Variables
static WORD qconsole_attrib
static HANDLE qconsole_hin
static char qconsole_history [QCONSOLE_HISTORY][MAX_EDIT_LINE]
static int qconsole_history_oldest = 0
static int qconsole_history_pos = -1
static HANDLE qconsole_hout
static char qconsole_line [MAX_EDIT_LINE]
static int qconsole_linelen = 0
static CONSOLE_CURSOR_INFO qconsole_orig_cursorinfo
static DWORD qconsole_orig_mode
Macro Definition Documentation
QCONSOLE_HISTORY
#define QCONSOLE_HISTORY 32
Definition at line 28 of file con_win32.c.
Function Documentation
CON_CtrlHandler()
static BOOL WINAPI CON_CtrlHandler (DWORD sig) static
Definition at line 60 of file con_win32.c.
 {
     Sys_SigHandler( sig );
     return TRUE;
 }
References Sys_SigHandler(), and TRUE.
Referenced by CON_Init().
CON_HistAdd()
static void CON_HistAdd (void) static
Definition at line 71 of file con_win32.c.
 {
     Q_strncpyz( qconsole_history[ qconsole_history_oldest ], qconsole_line,
         sizeof( qconsole_history[ qconsole_history_oldest ] ) );
     if( qconsole_history_oldest >= QCONSOLE_HISTORY - 1 )
         qconsole_history_oldest = 0;
     else
         qconsole_history_oldest++;
     qconsole_history_pos = qconsole_history_oldest;
 }
References Q_strncpyz(), QCONSOLE_HISTORY, qconsole_history, qconsole_history_oldest, qconsole_history_pos, and qconsole_line.
Referenced by CON_Input().
CON_HistNext()
static void CON_HistNext (void) static
Definition at line 111 of file con_win32.c.
 {
     int pos;
     pos = ( qconsole_history_pos >= QCONSOLE_HISTORY - 1 ) ?
         0 : ( qconsole_history_pos + 1 );
     // clear the edit buffer if they try to advance to a future command
     if( pos == qconsole_history_oldest )
     {
         qconsole_line[ 0 ] = '\0';
         qconsole_linelen = 0;
         return;
     }
     qconsole_history_pos = pos;
     Q_strncpyz( qconsole_line, qconsole_history[ qconsole_history_pos ],
         sizeof( qconsole_line ) );
     qconsole_linelen = strlen( qconsole_line );
 }
References Q_strncpyz(), QCONSOLE_HISTORY, qconsole_history, qconsole_history_oldest, qconsole_history_pos, qconsole_line, and qconsole_linelen.
Referenced by CON_Input().
CON_HistPrev()
static void CON_HistPrev (void) static
Definition at line 89 of file con_win32.c.
 {
     int pos;
     pos = ( qconsole_history_pos < 1 ) ?
         ( QCONSOLE_HISTORY - 1 ) : ( qconsole_history_pos - 1 );
     // don' t allow looping through history
     if( pos == qconsole_history_oldest )
         return;
     qconsole_history_pos = pos;
     Q_strncpyz( qconsole_line, qconsole_history[ qconsole_history_pos ],
         sizeof( qconsole_line ) );
     qconsole_linelen = strlen( qconsole_line );
 }
References Q_strncpyz(), QCONSOLE_HISTORY, qconsole_history, qconsole_history_oldest, qconsole_history_pos, qconsole_line, and qconsole_linelen.
Referenced by CON_Input().
CON_Init()
void CON_Init (void)
Definition at line 200 of file con_win32.c.
 {
     CONSOLE_CURSOR_INFO curs;
     CONSOLE_SCREEN_BUFFER_INFO info;
     int i;
     // handle Ctrl-C or other console termination
     SetConsoleCtrlHandler( CON_CtrlHandler, TRUE );
     qconsole_hin = GetStdHandle( STD_INPUT_HANDLE );
     if( qconsole_hin == INVALID_HANDLE_VALUE )
         return;
     qconsole_hout = GetStdHandle( STD_OUTPUT_HANDLE );
     if( qconsole_hout == INVALID_HANDLE_VALUE )
         return;
     GetConsoleMode( qconsole_hin, &qconsole_orig_mode );
     // allow mouse wheel scrolling
     SetConsoleMode( qconsole_hin,
         qconsole_orig_mode & ~ENABLE_MOUSE_INPUT );
     FlushConsoleInputBuffer( qconsole_hin );
     GetConsoleScreenBufferInfo( qconsole_hout, &info );
     qconsole_attrib = info.wAttributes;
     SetConsoleTitle(CLIENT_WINDOW_TITLE " Dedicated Server Console");
     // make cursor invisible
     GetConsoleCursorInfo( qconsole_hout, &qconsole_orig_cursorinfo );
     curs.dwSize = 1;
     curs.bVisible = FALSE;
     SetConsoleCursorInfo( qconsole_hout, &curs );
     // initialize history
     for( i = 0; i < QCONSOLE_HISTORY; i++ )
         qconsole_history[ i ][ 0 ] = '\0';
 }
References CLIENT_WINDOW_TITLE, CON_CtrlHandler(), FALSE, info, qconsole_attrib, qconsole_hin, QCONSOLE_HISTORY, qconsole_history, qconsole_hout, qconsole_orig_cursorinfo, qconsole_orig_mode, and TRUE.
CON_Input()
char* CON_Input (void)
Definition at line 246 of file con_win32.c.
 {
     INPUT_RECORD buff[ MAX_EDIT_LINE ];
     DWORD count = 0, events = 0;
     WORD key = 0;
     int i;
     int newlinepos = -1;
     if( !GetNumberOfConsoleInputEvents( qconsole_hin, &events ) )
         return NULL;
     if( events < 1 )
         return NULL;
     // if we have overflowed, start dropping oldest input events
     if( events >= MAX_EDIT_LINE )
     {
         ReadConsoleInput( qconsole_hin, buff, 1, &events );
         return NULL;
     }
     if( !ReadConsoleInput( qconsole_hin, buff, events, &count ) )
         return NULL;
     FlushConsoleInputBuffer( qconsole_hin );
     for( i = 0; i < count; i++ )
     {
         if( buff[ i ].EventType != KEY_EVENT )
             continue;
         if( !buff[ i ].Event.KeyEvent.bKeyDown )
             continue;
         key = buff[ i ].Event.KeyEvent.wVirtualKeyCode;
         if( key == VK_RETURN )
         {
             newlinepos = i;
             break;
         }
         else if( key == VK_UP )
         {
             CON_HistPrev();
             break;
         }
         else if( key == VK_DOWN )
         {
             CON_HistNext();
             break;
         }
         else if( key == VK_TAB )
         {
             field_t f;
             Q_strncpyz( f.buffer, qconsole_line,
                 sizeof( f.buffer ) );
             Field_AutoComplete( &f );
             Q_strncpyz( qconsole_line, f.buffer,
                 sizeof( qconsole_line ) );
             qconsole_linelen = strlen( qconsole_line );
             break;
         }
         if( qconsole_linelen < sizeof( qconsole_line ) - 1 )
         {
             char c = buff[ i ].Event.KeyEvent.uChar.AsciiChar;
             if( key == VK_BACK )
             {
                 int pos = ( qconsole_linelen > 0 ) ?
                     qconsole_linelen - 1 : 0;
                 qconsole_line[ pos ] = '\0';
                 qconsole_linelen = pos;
             }
             else if( c )
             {
                 qconsole_line[ qconsole_linelen++ ] = c;
                 qconsole_line[ qconsole_linelen ] = '\0';
             }
         }
     }
     if( newlinepos < 0) {
         CON_Show();
         return NULL;
     }
     if( !qconsole_linelen )
     {
         CON_Show();
         Com_Printf( "\n" );
         return NULL;
     }
     CON_HistAdd();
     Com_Printf( "%s\n", qconsole_line );
     qconsole_linelen = 0;
     CON_Show();
     return qconsole_line;
 }
References field_t::buffer, Com_Printf(), CON_HistAdd(), CON_HistNext(), CON_HistPrev(), CON_Show(), events, Field_AutoComplete(), MAX_EDIT_LINE, NULL, Q_strncpyz(), qconsole_hin, qconsole_line, and qconsole_linelen.
CON_Print()
void CON_Print (const char * msg)
Definition at line 355 of file con_win32.c.
 {
     fputs( msg, stderr );
     CON_Show( );
 }
References com_ansiColor, CON_Show(), and Sys_AnsiColorPrint().
CON_Show()
static void CON_Show (void) static
Definition at line 138 of file con_win32.c.
 {
     CONSOLE_SCREEN_BUFFER_INFO binfo;
     COORD writeSize = { MAX_EDIT_LINE, 1 };
     COORD writePos = { 0, 0 };
     SMALL_RECT writeArea = { 0, 0, 0, 0 };
     int i;
     CHAR_INFO line[ MAX_EDIT_LINE ];
     GetConsoleScreenBufferInfo( qconsole_hout, &binfo );
     // if we're in the middle of printf, don't bother writing the buffer
     if( binfo.dwCursorPosition.X != 0 )
         return;
     writeArea.Left = 0;
     writeArea.Top = binfo.dwCursorPosition.Y;
     writeArea.Bottom = binfo.dwCursorPosition.Y;
     writeArea.Right = MAX_EDIT_LINE;
     // build a space-padded CHAR_INFO array
     for( i = 0; i < MAX_EDIT_LINE; i++ )
     {
         if( i < qconsole_linelen )
             line[ i ].Char.AsciiChar = qconsole_line[ i ];
         else
             line[ i ].Char.AsciiChar = ' ';
         line[ i ].Attributes =  qconsole_attrib;
     }
     if( qconsole_linelen > binfo.srWindow.Right )
     {
         WriteConsoleOutput( qconsole_hout,
             line + (qconsole_linelen - binfo.srWindow.Right ),
             writeSize, writePos, &writeArea );
     }
     else
     {
         WriteConsoleOutput( qconsole_hout, line, writeSize,
             writePos, &writeArea );
     }
 }
References line, MAX_EDIT_LINE, qconsole_attrib, qconsole_hout, qconsole_line, qconsole_linelen, and writePos.
Referenced by CON_Input(), and CON_Print().
CON_Shutdown()
void CON_Shutdown (void)
Definition at line 187 of file con_win32.c.
 {
     SetConsoleMode( qconsole_hin, qconsole_orig_mode );
     SetConsoleCursorInfo( qconsole_hout, &qconsole_orig_cursorinfo );
     CloseHandle( qconsole_hout );
     CloseHandle( qconsole_hin );
 }
References qconsole_hin, qconsole_hout, qconsole_orig_cursorinfo, and qconsole_orig_mode.
Variable Documentation
qconsole_attrib
WORD qconsole_attrib static
Definition at line 30 of file con_win32.c.
Referenced by CON_Init(), and CON_Show().
qconsole_hin
HANDLE qconsole_hin static
Definition at line 46 of file con_win32.c.
Referenced by CON_Init(), CON_Input(), and CON_Shutdown().
qconsole_history
char qconsole_history[QCONSOLE_HISTORY][MAX_EDIT_LINE] static
Definition at line 37 of file con_win32.c.
Referenced by CON_HistAdd(), CON_HistNext(), CON_HistPrev(), and CON_Init().
qconsole_history_oldest
int qconsole_history_oldest = 0 static
Definition at line 39 of file con_win32.c.
Referenced by CON_HistAdd(), CON_HistNext(), and CON_HistPrev().
qconsole_history_pos
int qconsole_history_pos = -1 static
Definition at line 38 of file con_win32.c.
Referenced by CON_HistAdd(), CON_HistNext(), and CON_HistPrev().
qconsole_hout
HANDLE qconsole_hout static
Definition at line 45 of file con_win32.c.
Referenced by CON_Init(), CON_Show(), and CON_Shutdown().
qconsole_line
char qconsole_line[MAX_EDIT_LINE] static
Definition at line 42 of file con_win32.c.
Referenced by CON_HistAdd(), CON_HistNext(), CON_HistPrev(), CON_Input(), and CON_Show().
qconsole_linelen
int qconsole_linelen = 0 static
Definition at line 43 of file con_win32.c.
Referenced by CON_HistNext(), CON_HistPrev(), CON_Input(), and CON_Show().
qconsole_orig_cursorinfo
CONSOLE_CURSOR_INFO qconsole_orig_cursorinfo static
Definition at line 34 of file con_win32.c.
Referenced by CON_Init(), and CON_Shutdown().
qconsole_orig_mode
DWORD qconsole_orig_mode static
Definition at line 33 of file con_win32.c.
Referenced by CON_Init(), and CON_Shutdown().