ZEQ2-Lite: Source/Shared/vm.c File Reference
vm.c File Reference
#include "vm_local.h"
Macros
#define MAX_VM 3
Functions
int ParseHex (const char *text)
void * VM_ArgPtr (intptr_t intValue)
void VM_BlockCopy (unsigned int dest, unsigned int src, size_t n)
intptr_t QDECL VM_Call (vm_t *vm, int callnum,...)
void VM_Clear (void)
vm_t * VM_Create (const char *module, intptr_t(*systemCalls)(intptr_t *), vmInterpret_t interpret)
void VM_Debug (int level)
intptr_t QDECL VM_DllSyscall (intptr_t arg,...)
void * VM_ExplicitArgPtr (vm_t *vm, intptr_t intValue)
void VM_Forced_Unload_Done (void)
void VM_Forced_Unload_Start (void)
void VM_Free (vm_t *vm)
void VM_Init (void)
vmHeader_t * VM_LoadQVM (vm_t *vm, qboolean alloc, qboolean unpure)
void VM_LoadSymbols (vm_t *vm)
void VM_LogSyscalls (int *args)
static int QDECL VM_ProfileSort (const void *a, const void *b)
vm_t * VM_Restart (vm_t *vm, qboolean unpure)
int VM_SymbolToValue (vm_t *vm, const char *symbol)
vmSymbol_t * VM_ValueToFunctionSymbol (vm_t *vm, int value)
const char * VM_ValueToSymbol (vm_t *vm, int value)
void VM_VmInfo_f (void)
void VM_VmProfile_f (void)
Variables
vm_t * currentVM = NULL
static int forced_unload
vm_t * lastVM = NULL
int vm_debugLevel
vm_t vmTable [MAX_VM]
Macro Definition Documentation
MAX_VM
#define MAX_VM 3
Definition at line 46 of file vm.c.
Function Documentation
ParseHex()
int ParseHex (const char * text)
Definition at line 191 of file vm.c.
{
     int     value;
     int     c;
     value = 0;
     while ( ( c = *text++ ) != 0 ) {
         if ( c >= '0' && c <= '9' ) {
             value = value * 16 + c - '0';
             continue;
         }
         if ( c >= 'a' && c <= 'f' ) {
             value = value * 16 + 10 + c - 'a';
             continue;
         }
         if ( c >= 'A' && c <= 'F' ) {
             value = value * 16 + 10 + c - 'A';
             continue;
         }
     }
     return value;
 }
Referenced by VM_LoadSymbols().
VM_ArgPtr()
void* VM_ArgPtr (intptr_t intValue)
Definition at line 746 of file vm.c.
{
     if ( !intValue ) {
         return NULL;
     }
     // currentVM is missing on reconnect
     if ( currentVM==NULL )
       return NULL;
     if ( currentVM->entryPoint ) {
         return (void *)(currentVM->dataBase + intValue);
     }
     else {
         return (void *)(currentVM->dataBase + (intValue & currentVM->dataMask));
     }
 }
References currentVM, and NULL.
VM_BlockCopy()
void VM_BlockCopy (unsigned int dest, unsigned int src, size_t n)
Definition at line 995 of file vm.c.
 {
     unsigned int dataMask = currentVM->dataMask;
     if ((dest & dataMask) != dest
     || (src & dataMask) != src
     || ((dest + n) & dataMask) != dest + n
     || ((src + n) & dataMask) != src + n)
     {
         Com_Error(ERR_DROP, "OP_BLOCK_COPY out of range!");
     }
     Com_Memcpy(currentVM->dataBase + dest, currentVM->dataBase + src, n);
 }
References Com_Error(), Com_Memcpy, currentVM, and ERR_DROP.
Referenced by DoSyscall(), PPC_ComputeCode(), VM_CallInterpreted(), and VM_Compile().
VM_Call()
intptr_t QDECL VM_Call (vm_t * vm, int callnum, ...)
Definition at line 805 of file vm.c.
 {
     vm_t    *oldVM;
     intptr_t r;
     int i;
     if(!vm || !vm->name[0])
         Com_Error(ERR_FATAL, "VM_Call with NULL vm");
     oldVM = currentVM;
     currentVM = vm;
     lastVM = vm;
     if ( vm_debugLevel ) {
       Com_Printf( "VM_Call( %d )\n", callnum );
     }
     ++vm->callLevel;
     // if we have a dll loaded, call it directly
     if ( vm->entryPoint ) {
         //rcg010207 -  see dissertation at top of VM_DllSyscall() in this file.
         int args[10];
         va_list ap;
         va_start(ap, callnum);
         for (i = 0; i < ARRAY_LEN(args); i++) {
             args[i] = va_arg(ap, int);
         }
         va_end(ap);
         r = vm->entryPoint( callnum,  args[0],  args[1],  args[2], args[3],
                             args[4],  args[5],  args[6], args[7],
                             args[8],  args[9]);
     } else {
 #if id386 || idsparc // i386/sparc calling convention doesn't need conversion
 #ifndef NO_VM_COMPILED
         if ( vm->compiled )
             r = VM_CallCompiled( vm, (int*)&callnum );
         else
 #endif
             r = VM_CallInterpreted( vm, (int*)&callnum );
 #else
         struct {
             int callnum;
             int args[10];
         } a;
         va_list ap;
         a.callnum = callnum;
         va_start(ap, callnum);
         for (i = 0; i < ARRAY_LEN(a.args); i++) {
             a.args[i] = va_arg(ap, int);
         }
         va_end(ap);
 #ifndef NO_VM_COMPILED
         if ( vm->compiled )
             r = VM_CallCompiled( vm, &a.callnum );
         else
 #endif
             r = VM_CallInterpreted( vm, &a.callnum );
 #endif
     }
     --vm->callLevel;
     if ( oldVM != NULL )
       currentVM = oldVM;
     return r;
 }
References args, ARRAY_LEN, Com_Error(), Com_Printf(), currentVM, ERR_FATAL, intptr_t(), lastVM, NULL, VM_CallCompiled(), VM_CallInterpreted(), and vm_debugLevel.
Referenced by CIN_PlayCinematic(), CL_CGameRendering(), CL_CharEvent(), CL_Disconnect(), CL_Frame(), CL_GameCommand(), CL_InitCGame(), CL_InitUI(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MouseEvent(), CL_ShutdownCGame(), CL_ShutdownUI(), Con_MessageMode3_f(), Con_MessageMode4_f(), SCR_DrawScreenField(), SV_ClientEnterWorld(), SV_ClientThink(), SV_DirectConnect(), SV_DropClient(), SV_ExecuteClientCommand(), SV_Frame(), SV_GameCommand(), SV_InitGameVM(), SV_MapRestart_f(), SV_RestartGameProgs(), SV_ShutdownGameProgs(), SV_SpawnServer(), SV_UpdateUserinfo_f(), and UI_GameCommand().
VM_Clear()
void VM_Clear (void)
Definition at line 731 of file vm.c.
                     {
     int i;
     for (i=0;i<MAX_VM; i++) {
         VM_Free(&vmTable[i]);
     }
 }
References MAX_VM, VM_Free(), and vmTable.
Referenced by Hunk_Clear().
VM_Create()
vm_t* VM_Create (const char * module, intptr_t(*)(intptr_t *) systemCalls, vmInterpret_t interpret)
Definition at line 574 of file vm.c.
{
     vm_t        *vm;
     vmHeader_t  *header;
     int         i, remaining, retval;
     char filename[MAX_OSPATH];
     void *startSearch = NULL;
     if ( !module || !module[0] || !systemCalls ) {
         Com_Error( ERR_FATAL, "VM_Create: bad parms" );
     }
     remaining = Hunk_MemoryRemaining();
     // see if we already have the VM
     for ( i = 0 ; i < MAX_VM ; i++ ) {
         if (!Q_stricmp(vmTable[i].name, module)) {
             vm = &vmTable[i];
             return vm;
         }
     }
     // find a free vm
     for ( i = 0 ; i < MAX_VM ; i++ ) {
         if ( !vmTable[i].name[0] ) {
             break;
         }
     }
     if ( i == MAX_VM ) {
         Com_Error( ERR_FATAL, "VM_Create: no free vm_t" );
     }
     vm = &vmTable[i];
     Q_strncpyz(vm->name, module, sizeof(vm->name));
     do
     {
         retval = FS_FindVM(&startSearch, filename, sizeof(filename), module, (interpret == VMI_NATIVE));
         if(retval == VMI_NATIVE)
         {
             Com_Printf("Try loading dll file %s\n", filename);
             vm->dllHandle = Sys_LoadGameDll(filename, &vm->entryPoint, VM_DllSyscall);
             if(vm->dllHandle)
             {
                 vm->systemCall = systemCalls;
                 return vm;
             }
             Com_Printf("Failed loading dll, trying next\n");
         }
         else if(retval == VMI_COMPILED)
         {
             vm->searchPath = startSearch;
             if((header = VM_LoadQVM(vm, qtrue, qfalse)))
                 break;
             // VM_Free overwrites the name on failed load
             Q_strncpyz(vm->name, module, sizeof(vm->name));
         }
     } while(retval >= 0);
     if(retval < 0)
         return NULL;
     vm->systemCall = systemCalls;
     // allocate space for the jump targets, which will be filled in by the compile/prep functions
     vm->instructionCount = header->instructionCount;
     vm->instructionPointers = Hunk_Alloc(vm->instructionCount * sizeof(*vm->instructionPointers), h_high);
     // copy or compile the instructions
     vm->codeLength = header->codeLength;
     vm->compiled = qfalse;
 #ifdef NO_VM_COMPILED
     if(interpret >= VMI_COMPILED) {
         Com_Printf("Architecture doesn't have a bytecode compiler, using interpreter\n");
         interpret = VMI_BYTECODE;
     }
 #else
     if(interpret != VMI_BYTECODE)
     {
         vm->compiled = qtrue;
         VM_Compile( vm, header );
     }
 #endif
     // VM_Compile may have reset vm->compiled if compilation failed
     if (!vm->compiled)
     {
         VM_PrepareInterpreter( vm, header );
     }
     // free the original file
     FS_FreeFile( header );
     // load the map file
     VM_LoadSymbols( vm );
     // the stack is implicitly at the end of the image
     vm->programStack = vm->dataMask + 1;
     vm->stackBottom = vm->programStack - PROGRAM_STACK_SIZE;
     Com_Printf("%s loaded in %d bytes on the hunk\n", module, remaining - Hunk_MemoryRemaining());
     return vm;
 }
References Com_Error(), Com_Printf(), ERR_FATAL, FS_FindVM(), FS_FreeFile(), h_high, Hunk_Alloc, Hunk_MemoryRemaining(), MAX_OSPATH, MAX_VM, NULL, PROGRAM_STACK_SIZE, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, Sys_LoadGameDll(), VM_Compile(), VM_DllSyscall(), VM_LoadQVM(), VM_LoadSymbols(), VM_PrepareInterpreter(), VMI_BYTECODE, VMI_COMPILED, VMI_NATIVE, and vmTable.
Referenced by CL_InitCGame(), CL_InitUI(), SV_InitGameProgs(), and VM_Restart().
VM_Debug()
void VM_Debug (int level)
Definition at line 63 of file vm.c.
{
     vm_debugLevel = level;
 }
References vm_debugLevel.
Referenced by CL_CGameRendering(), and VM_CallInterpreted().
VM_DllSyscall()
intptr_t QDECL VM_DllSyscall (intptr_t arg, ...)
Definition at line 338 of file vm.c.
{
 #if !id386
   // rcg010206 - see commentary above
   intptr_t args[16];
   int i;
   va_list ap;
   args[0] = arg;
   va_start(ap, arg);
   for (i = 1; i < ARRAY_LEN (args); i++)
     args[i] = va_arg(ap, intptr_t);
   va_end(ap);
   return currentVM->systemCall( args );
 #else // original id code
     return currentVM->systemCall( &arg );
 #endif
 }
References args, ARRAY_LEN, currentVM, and intptr_t().
Referenced by VM_Create().
VM_ExplicitArgPtr()
void* VM_ExplicitArgPtr (vm_t * vm, intptr_t intValue)
Definition at line 762 of file vm.c.
{
     if ( !intValue ) {
         return NULL;
     }
     // currentVM is missing on reconnect here as well?
     if ( currentVM==NULL )
       return NULL;
     //
     if ( vm->entryPoint ) {
         return (void *)(vm->dataBase + intValue);
     }
     else {
         return (void *)(vm->dataBase + (intValue & vm->dataMask));
     }
 }
References currentVM, and NULL.
Referenced by SV_DirectConnect(), SV_MapRestart_f(), and SV_SpawnServer().
VM_Forced_Unload_Done()
void VM_Forced_Unload_Done (void)
Definition at line 742 of file vm.c.
{
     forced_unload = 0;
 }
References forced_unload.
Referenced by Com_Error(), Com_Quit_f(), and Sys_SigHandler().
VM_Forced_Unload_Start()
void VM_Forced_Unload_Start (void)
Definition at line 738 of file vm.c.
{
     forced_unload = 1;
 }
References forced_unload.
Referenced by Com_Error(), Com_Quit_f(), and Sys_SigHandler().
VM_Free()
void VM_Free (vm_t * vm)
Definition at line 692 of file vm.c.
{
     if(!vm) {
         return;
     }
     if(vm->callLevel) {
         if(!forced_unload) {
             Com_Error( ERR_FATAL, "VM_Free(%s) on running vm", vm->name );
             return;
         } else {
             Com_Printf( "forcefully unloading %s vm\n", vm->name );
         }
     }
     if(vm->destroy)
         vm->destroy(vm);
     if ( vm->dllHandle ) {
         Sys_UnloadDll( vm->dllHandle );
         Com_Memset( vm, 0, sizeof( *vm ) );
     }
 #if 0   // now automatically freed by hunk
     if ( vm->codeBase ) {
         Z_Free( vm->codeBase );
     }
     if ( vm->dataBase ) {
         Z_Free( vm->dataBase );
     }
     if ( vm->instructionPointers ) {
         Z_Free( vm->instructionPointers );
     }
 #endif
     Com_Memset( vm, 0, sizeof( *vm ) );
     currentVM = NULL;
     lastVM = NULL;
 }
References Com_Error(), Com_Memset, Com_Printf(), currentVM, ERR_FATAL, forced_unload, lastVM, NULL, Sys_UnloadDll(), and Z_Free().
Referenced by CL_ShutdownCGame(), CL_ShutdownUI(), SV_ShutdownGameProgs(), VM_Clear(), VM_LoadQVM(), and VM_Restart().
VM_Init()
void VM_Init (void)
Definition at line 72 of file vm.c.
                      {
     Cvar_Get( "vm_cgame", "2", CVAR_ARCHIVE );  // !@# SHIP WITH SET TO 2
     Cvar_Get( "vm_game", "2", CVAR_ARCHIVE );   // !@# SHIP WITH SET TO 2
     Cvar_Get( "vm_ui", "2", CVAR_ARCHIVE );     // !@# SHIP WITH SET TO 2
     Cmd_AddCommand ("vmprofile", VM_VmProfile_f );
     Cmd_AddCommand ("vminfo", VM_VmInfo_f );
     Com_Memset( vmTable, 0, sizeof( vmTable ) );
 }
References Cmd_AddCommand(), Com_Memset, CVAR_ARCHIVE, Cvar_Get(), VM_VmInfo_f(), VM_VmProfile_f(), and vmTable.
Referenced by Com_Init().
VM_LoadQVM()
vmHeader_t* VM_LoadQVM (vm_t * vm, qboolean alloc, qboolean unpure)
Definition at line 366 of file vm.c.
 {
     int                 dataLength;
     int                 i;
     char                filename[MAX_QPATH];
     union {
         vmHeader_t  *h;
         void                *v;
     } header;
     // load the image
     Com_sprintf( filename, sizeof(filename), "vm/%s.qvm", vm->name );
     Com_Printf( "Loading vm file %s...\n", filename );
     FS_ReadFileDir(filename, vm->searchPath, unpure, &header.v);
     if ( !header.h ) {
         Com_Printf( "Failed.\n" );
         VM_Free( vm );
         Com_Printf(S_COLOR_YELLOW "Warning: Couldn't open VM file %s\n", filename);
         return NULL;
     }
     // show where the qvm was loaded from
     FS_Which(filename, vm->searchPath);
     if( LittleLong( header.h->vmMagic ) == VM_MAGIC_VER2 ) {
         Com_Printf( "...which has vmMagic VM_MAGIC_VER2\n" );
         // byte swap the header
         for ( i = 0 ; i < sizeof( vmHeader_t ) / 4 ; i++ ) {
             ((int *)header.h)[i] = LittleLong( ((int *)header.h)[i] );
         }
         // validate
         if ( header.h->jtrgLength < 0
             || header.h->bssLength < 0
             || header.h->dataLength < 0
             || header.h->litLength < 0
             || header.h->codeLength <= 0 )
         {
             VM_Free(vm);
             FS_FreeFile(header.v);
             Com_Printf(S_COLOR_YELLOW "Warning: %s has bad header\n", filename);
             return NULL;
         }
     } else if( LittleLong( header.h->vmMagic ) == VM_MAGIC ) {
         // byte swap the header
         // sizeof( vmHeader_t ) - sizeof( int ) is the 1.32b vm header size
         for ( i = 0 ; i < ( sizeof( vmHeader_t ) - sizeof( int ) ) / 4 ; i++ ) {
             ((int *)header.h)[i] = LittleLong( ((int *)header.h)[i] );
         }
         // validate
         if ( header.h->bssLength < 0
             || header.h->dataLength < 0
             || header.h->litLength < 0
             || header.h->codeLength <= 0 )
         {
             VM_Free(vm);
             FS_FreeFile(header.v);
             Com_Printf(S_COLOR_YELLOW "Warning: %s has bad header\n", filename);
             return NULL;
         }
     } else {
         VM_Free( vm );
         FS_FreeFile(header.v);
         Com_Printf(S_COLOR_YELLOW "Warning: %s does not have a recognisable "
                 "magic number in its header\n", filename);
         return NULL;
     }
     // round up to next power of 2 so all data operations can
     // be mask protected
     dataLength = header.h->dataLength + header.h->litLength +
         header.h->bssLength;
     for ( i = 0 ; dataLength > ( 1 << i ) ; i++ ) {
     }
     dataLength = 1 << i;
     if(alloc)
     {
         // allocate zero filled space for initialized and uninitialized data
         vm->dataBase = Hunk_Alloc(dataLength, h_high);
         vm->dataMask = dataLength - 1;
     }
     else
     {
         // clear the data, but make sure we're not clearing more than allocated
         if(vm->dataMask + 1 != dataLength)
         {
             VM_Free(vm);
             FS_FreeFile(header.v);
             Com_Printf(S_COLOR_YELLOW "Warning: Data region size of %s not matching after "
                     "VM_Restart()\n", filename);
             return NULL;
         }
         Com_Memset(vm->dataBase, 0, dataLength);
     }
     // copy the intialized data
     Com_Memcpy( vm->dataBase, (byte *)header.h + header.h->dataOffset,
         header.h->dataLength + header.h->litLength );
     // byte swap the longs
     for ( i = 0 ; i < header.h->dataLength ; i += 4 ) {
         *(int *)(vm->dataBase + i) = LittleLong( *(int *)(vm->dataBase + i ) );
     }
     if(header.h->vmMagic == VM_MAGIC_VER2)
     {
         int previousNumJumpTableTargets = vm->numJumpTableTargets;
         header.h->jtrgLength &= ~0x03;
         vm->numJumpTableTargets = header.h->jtrgLength >> 2;
         Com_Printf("Loading %d jump table targets\n", vm->numJumpTableTargets);
         if(alloc)
         {
             vm->jumpTableTargets = Hunk_Alloc(header.h->jtrgLength, h_high);
         }
         else
         {
             if(vm->numJumpTableTargets != previousNumJumpTableTargets)
             {
                 VM_Free(vm);
                 FS_FreeFile(header.v);
                 Com_Printf(S_COLOR_YELLOW "Warning: Jump table size of %s not matching after "
                         "VM_Restart()\n", filename);
                 return NULL;
             }
             Com_Memset(vm->jumpTableTargets, 0, header.h->jtrgLength);
         }
         Com_Memcpy(vm->jumpTableTargets, (byte *) header.h + header.h->dataOffset +
                 header.h->dataLength + header.h->litLength, header.h->jtrgLength);
         // byte swap the longs
         for ( i = 0 ; i < header.h->jtrgLength ; i += 4 ) {
             *(int *)(vm->jumpTableTargets + i) = LittleLong( *(int *)(vm->jumpTableTargets + i ) );
         }
     }
     return header.h;
 }
References alloc(), Com_Memcpy, Com_Memset, Com_Printf(), Com_sprintf(), FS_FreeFile(), FS_ReadFileDir(), FS_Which(), h_high, Hunk_Alloc, MAX_QPATH, NULL, S_COLOR_YELLOW, VM_Free(), VM_MAGIC, and VM_MAGIC_VER2.
Referenced by VM_Create(), and VM_Restart().
VM_LoadSymbols()
void VM_LoadSymbols (vm_t * vm)
Definition at line 219 of file vm.c.
{
     union {
         char    *c;
         void    *v;
     } mapfile;
     char *text_p, *token;
     char    name[MAX_QPATH];
     char    symbols[MAX_QPATH];
     vmSymbol_t  **prev, *sym;
     int     count;
     int     value;
     int     chars;
     int     segment;
     int     numInstructions;
     // don't load symbols if not developer
     if ( !com_developer->integer ) {
         return;
     }
     COM_StripExtension(vm->name, name, sizeof(name));
     Com_sprintf( symbols, sizeof( symbols ), "vm/%s.map", name );
     FS_ReadFile( symbols, &mapfile.v );
     if ( !mapfile.c ) {
         Com_Printf( "Couldn't load symbol file: %s\n", symbols );
         return;
     }
     numInstructions = vm->instructionCount;
     // parse the symbols
     text_p = mapfile.c;
     prev = &vm->symbols;
     count = 0;
     while ( 1 ) {
         token = COM_Parse( &text_p );
         if ( !token[0] ) {
             break;
         }
         segment = ParseHex( token );
         if ( segment ) {
             COM_Parse( &text_p );
             COM_Parse( &text_p );
             continue;       // only load code segment values
         }
         token = COM_Parse( &text_p );
         if ( !token[0] ) {
             Com_Printf( "WARNING: incomplete line at end of file\n" );
             break;
         }
         value = ParseHex( token );
         token = COM_Parse( &text_p );
         if ( !token[0] ) {
             Com_Printf( "WARNING: incomplete line at end of file\n" );
             break;
         }
         chars = strlen( token );
         sym = Hunk_Alloc( sizeof( *sym ) + chars, h_high );
         *prev = sym;
         prev = &sym->next;
         sym->next = NULL;
         // convert value from an instruction number to a code offset
         if ( value >= 0 && value < numInstructions ) {
             value = vm->instructionPointers[value];
         }
         sym->symValue = value;
         Q_strncpyz( sym->symName, token, chars + 1 );
         count++;
     }
     vm->numSymbols = count;
     Com_Printf( "%i symbols parsed from %s\n", count, symbols );
     FS_FreeFile( mapfile.v );
 }
References com_developer, COM_Parse(), Com_Printf(), Com_sprintf(), COM_StripExtension(), FS_FreeFile(), FS_ReadFile(), h_high, Hunk_Alloc, MAX_QPATH, NULL, ParseHex(), Q_strncpyz(), segment, symbols, and token.
Referenced by VM_Create().
VM_LogSyscalls()
void VM_LogSyscalls (int * args)
Definition at line 976 of file vm.c.
{
     static  int     callnum;
     static  FILE    *f;
     if ( !f ) {
         f = fopen("syscalls.log", "w" );
     }
     callnum++;
     fprintf(f, "%i: %p (%i) = %i %i %i %i\n", callnum, (void*)(args - (int *)currentVM->dataBase),
         args[0], args[1], args[2], args[3], args[4] );
 }
References args, and currentVM.
VM_ProfileSort()
static int QDECL VM_ProfileSort (const void * a, const void * b) static
Definition at line 875 of file vm.c.
{
     vmSymbol_t  *sa, *sb;
     sa = *(vmSymbol_t **)a;
     sb = *(vmSymbol_t **)b;
     if ( sa->profileCount < sb->profileCount ) {
         return -1;
     }
     if ( sa->profileCount > sb->profileCount ) {
         return 1;
     }
     return 0;
 }
Referenced by VM_VmProfile_f().
VM_Restart()
vm_t* VM_Restart (vm_t * vm, qboolean unpure)
Definition at line 533 of file vm.c.
 {
     vmHeader_t  *header;
     // DLL's can't be restarted in place
     if ( vm->dllHandle ) {
         char    name[MAX_QPATH];
         intptr_t    (*systemCall)( intptr_t *parms );
         systemCall = vm->systemCall;
         Q_strncpyz( name, vm->name, sizeof( name ) );
         VM_Free( vm );
         vm = VM_Create( name, systemCall, VMI_NATIVE );
         return vm;
     }
     // load the image
     Com_Printf("VM_Restart()\n");
     if(!(header = VM_LoadQVM(vm, qfalse, unpure)))
     {
         Com_Error(ERR_DROP, "VM_Restart failed");
         return NULL;
     }
     // free the original file
     FS_FreeFile(header);
     return vm;
 }
References Com_Error(), Com_Printf(), ERR_DROP, FS_FreeFile(), intptr_t(), MAX_QPATH, NULL, Q_strncpyz(), qfalse, VM_Create(), VM_Free(), VM_LoadQVM(), and VMI_NATIVE.
Referenced by SV_RestartGameProgs().
VM_SymbolToValue()
int VM_SymbolToValue (vm_t * vm, const char * symbol)
Definition at line 143 of file vm.c.
{
     vmSymbol_t  *sym;
     for ( sym = vm->symbols ; sym ; sym = sym->next ) {
         if ( !strcmp( symbol, sym->symName ) ) {
             return sym->symValue;
         }
     }
     return 0;
 }
VM_ValueToFunctionSymbol()
vmSymbol_t* VM_ValueToFunctionSymbol (vm_t * vm, int value)
Definition at line 121 of file vm.c.
{
     vmSymbol_t  *sym;
     static vmSymbol_t   nullSym;
     sym = vm->symbols;
     if ( !sym ) {
         return &nullSym;
     }
     while ( sym->next && sym->next->symValue <= value ) {
         sym = sym->next;
     }
     return sym;
 }
Referenced by VM_CallInterpreted().
VM_ValueToSymbol()
const char* VM_ValueToSymbol (vm_t * vm, int value)
Definition at line 91 of file vm.c.
{
     vmSymbol_t  *sym;
     static char     text[MAX_TOKEN_CHARS];
     sym = vm->symbols;
     if ( !sym ) {
         return "NO SYMBOLS";
     }
     // find the symbol
     while ( sym->next && sym->next->symValue <= value ) {
         sym = sym->next;
     }
     if ( value == sym->symValue ) {
         return sym->symName;
     }
     Com_sprintf( text, sizeof( text ), "%s+%i", sym->symName, value - sym->symValue );
     return text;
 }
References Com_sprintf(), and MAX_TOKEN_CHARS.
Referenced by VM_CallInterpreted(), and VM_StackTrace().
VM_VmInfo_f()
void VM_VmInfo_f (void)
Definition at line 943 of file vm.c.
{
     vm_t    *vm;
     int     i;
     Com_Printf( "Registered virtual machines:\n" );
     for ( i = 0 ; i < MAX_VM ; i++ ) {
         vm = &vmTable[i];
         if ( !vm->name[0] ) {
             break;
         }
         Com_Printf( "%s : ", vm->name );
         if ( vm->dllHandle ) {
             Com_Printf( "native\n" );
             continue;
         }
         if ( vm->compiled ) {
             Com_Printf( "compiled on load\n" );
         } else {
             Com_Printf( "interpreted\n" );
         }
         Com_Printf( "    code length : %7i\n", vm->codeLength );
         Com_Printf( "    table length: %7i\n", vm->instructionCount*4 );
         Com_Printf( "    data length : %7i\n", vm->dataMask + 1 );
     }
 }
References Com_Printf(), MAX_VM, and vmTable.
Referenced by VM_Init().
VM_VmProfile_f()
void VM_VmProfile_f (void)
Definition at line 896 of file vm.c.
{
     vm_t        *vm;
     vmSymbol_t  **sorted, *sym;
     int         i;
     double      total;
     if ( !lastVM ) {
         return;
     }
     vm = lastVM;
     if ( !vm->numSymbols ) {
         return;
     }
     sorted = Z_Malloc( vm->numSymbols * sizeof( *sorted ) );
     sorted[0] = vm->symbols;
     total = sorted[0]->profileCount;
     for ( i = 1 ; i < vm->numSymbols ; i++ ) {
         sorted[i] = sorted[i-1]->next;
         total += sorted[i]->profileCount;
     }
     qsort( sorted, vm->numSymbols, sizeof( *sorted ), VM_ProfileSort );
     for ( i = 0 ; i < vm->numSymbols ; i++ ) {
         int     perc;
         sym = sorted[i];
         perc = 100 * (float) sym->profileCount / total;
         Com_Printf( "%2i%% %9i %s\n", perc, sym->profileCount, sym->symName );
         sym->profileCount = 0;
     }
     Com_Printf("    %9.0f total\n", total );
     Z_Free( sorted );
 }
References Com_Printf(), lastVM, VM_ProfileSort(), Z_Free(), and Z_Malloc.
Referenced by VM_Init().
Variable Documentation
currentVM
vm_t* currentVM = NULL
Definition at line 39 of file vm.c.
Referenced by asmcall(), blockcopy(), callAsmCall(), DoSyscall(), VM_ArgPtr(), VM_AsmCall(), VM_BlockCopy(), VM_Call(), VM_CallCompiled(), VM_DllSyscall(), VM_ExplicitArgPtr(), VM_Free(), and VM_LogSyscalls().
forced_unload
int forced_unload static
Definition at line 44 of file vm.c.
Referenced by VM_Forced_Unload_Done(), VM_Forced_Unload_Start(), and VM_Free().
lastVM
vm_t* lastVM = NULL
Definition at line 40 of file vm.c.
Referenced by VM_Call(), VM_Free(), and VM_VmProfile_f().
vm_debugLevel
int vm_debugLevel
Definition at line 41 of file vm.c.
Referenced by VM_Call(), VM_CallInterpreted(), and VM_Debug().
vmTable
vm_t vmTable[MAX_VM]
Definition at line 47 of file vm.c.
Referenced by VM_Clear(), VM_Create(), VM_Init(), and VM_VmInfo_f().