ZEQ2-Lite: Source/Engine/libspeex/modes.h File Reference
modes.h File Reference
Describes the different modes of the codec.
#include <speex/speex.h>
#include <speex/speex_bits.h>
#include "arch.h"
Data Structures
struct SpeexNBMode
Struct defining the encoding/decoding mode.
struct SpeexSBMode
Struct defining the encoding/decoding mode for SB-CELP (wideband)
struct SpeexSubmode
Description of a Speex sub-mode (wither narrowband or wideband.
Macros
#define NB_SUBMODE_BITS 4
#define NB_SUBMODES 16
#define SB_SUBMODE_BITS 3
#define SB_SUBMODES 8
#define SPEEX_GET_DTX_STATUS 103
Used internally.
#define SPEEX_GET_EXC 101
Used internally.
#define SPEEX_GET_INNOV 102
Used internally.
#define SPEEX_GET_PI_GAIN 100
Used internally.
#define SPEEX_GET_STACK 106
Used internally.
#define SPEEX_SET_INNOVATION_SAVE 104
Used internally.
#define SPEEX_SET_WIDEBAND 105
Used internally.
Typedefs
typedef void(* innovation_quant_func) (spx_word16_t *, spx_coef_t *, spx_coef_t *, spx_coef_t *, const void *, int, int, spx_sig_t *, spx_word16_t *, SpeexBits *, char *, int, int)
Innovation quantization function.
typedef void(* innovation_unquant_func) (spx_sig_t *, const void *, int, SpeexBits *, char *, spx_int32_t *)
Innovation unquantization function.
typedef void(* lsp_quant_func) (spx_lsp_t *, spx_lsp_t *, int, SpeexBits *)
Quantizes LSPs.
typedef void(* lsp_unquant_func) (spx_lsp_t *, int, SpeexBits *)
Decodes quantized LSPs.
typedef int(* ltp_quant_func) (spx_word16_t *, spx_word16_t *, spx_coef_t *, spx_coef_t *, spx_coef_t *, spx_sig_t *, const void *, int, int, spx_word16_t, int, int, SpeexBits *, char *, spx_word16_t *, spx_word16_t *, int, int, int, spx_word32_t *)
Long-term predictor quantization.
typedef void(* ltp_unquant_func) (spx_word16_t *, spx_word32_t *, int, int, spx_word16_t, const void *, int, int *, spx_word16_t *, SpeexBits *, char *, int, int, spx_word16_t, int)
Long-term un-quantize.
Functions
int nb_mode_query (const void *mode, int request, void *ptr)
int speex_decode_native (void *state, SpeexBits *bits, spx_word16_t *out)
int speex_encode_native (void *state, spx_word16_t *in, SpeexBits *bits)
int wb_mode_query (const void *mode, int request, void *ptr)
Detailed Description
Describes the different modes of the codec.
Definition in file modes.h.
Macro Definition Documentation
NB_SUBMODE_BITS
#define NB_SUBMODE_BITS 4
Definition at line 44 of file modes.h.
NB_SUBMODES
#define NB_SUBMODES 16
Definition at line 43 of file modes.h.
SB_SUBMODE_BITS
#define SB_SUBMODE_BITS 3
Definition at line 47 of file modes.h.
SB_SUBMODES
#define SB_SUBMODES 8
Definition at line 46 of file modes.h.
SPEEX_GET_DTX_STATUS
#define SPEEX_GET_DTX_STATUS 103
Used internally.
Definition at line 57 of file modes.h.
SPEEX_GET_EXC
#define SPEEX_GET_EXC 101
Used internally.
Definition at line 53 of file modes.h.
SPEEX_GET_INNOV
#define SPEEX_GET_INNOV 102
Used internally.
Definition at line 55 of file modes.h.
SPEEX_GET_PI_GAIN
#define SPEEX_GET_PI_GAIN 100
Used internally.
Definition at line 51 of file modes.h.
SPEEX_GET_STACK
#define SPEEX_GET_STACK 106
Used internally.
Definition at line 64 of file modes.h.
SPEEX_SET_INNOVATION_SAVE
#define SPEEX_SET_INNOVATION_SAVE 104
Used internally.
Definition at line 59 of file modes.h.
SPEEX_SET_WIDEBAND
#define SPEEX_SET_WIDEBAND 105
Used internally.
Definition at line 61 of file modes.h.
Typedef Documentation
innovation_quant_func
typedef void(* innovation_quant_func) (spx_word16_t *, spx_coef_t *, spx_coef_t *, spx_coef_t *, const void *, int, int, spx_sig_t *, spx_word16_t *, SpeexBits *, char *, int, int)
Innovation quantization function.
Definition at line 85 of file modes.h.
innovation_unquant_func
typedef void(* innovation_unquant_func) (spx_sig_t *, const void *, int, SpeexBits *, char *, spx_int32_t *)
Innovation unquantization function.
Definition at line 89 of file modes.h.
lsp_quant_func
typedef void(* lsp_quant_func) (spx_lsp_t *, spx_lsp_t *, int, SpeexBits *)
Quantizes LSPs.
Definition at line 68 of file modes.h.
lsp_unquant_func
typedef void(* lsp_unquant_func) (spx_lsp_t *, int, SpeexBits *)
Decodes quantized LSPs.
Definition at line 71 of file modes.h.
ltp_quant_func
typedef int(* ltp_quant_func) (spx_word16_t *, spx_word16_t *, spx_coef_t *, spx_coef_t *, spx_coef_t *, spx_sig_t *, const void *, int, int, spx_word16_t, int, int, SpeexBits *, char *, spx_word16_t *, spx_word16_t *, int, int, int, spx_word32_t *)
Long-term predictor quantization.
Definition at line 75 of file modes.h.
ltp_unquant_func
typedef void(* ltp_unquant_func) (spx_word16_t *, spx_word32_t *, int, int, spx_word16_t, const void *, int, int *, spx_word16_t *, SpeexBits *, char *, int, int, spx_word16_t, int)
Long-term un-quantize.
Definition at line 80 of file modes.h.
Function Documentation
nb_mode_query()
int nb_mode_query (const void * mode, int request, void * ptr)
Definition at line 192 of file speex.c.
 {
    const SpeexNBMode *m = (const SpeexNBMode*)mode;
    switch (request)
    {
    case SPEEX_MODE_FRAME_SIZE:
       *((int*)ptr)=m->frameSize;
       break;
    case SPEEX_SUBMODE_BITS_PER_FRAME:
       if (*((int*)ptr)==0)
          *((int*)ptr) = NB_SUBMODE_BITS+1;
       else if (m->submodes[*((int*)ptr)]==NULL)
          *((int*)ptr) = -1;
       else
          *((int*)ptr) = m->submodes[*((int*)ptr)]->bits_per_frame;
       break;
    default:
       speex_warning_int("Unknown nb_mode_query request: ", request);
       return -1;
    }
    return 0;
 }
References m, NB_SUBMODE_BITS, NULL, ptr(), SPEEX_MODE_FRAME_SIZE, SPEEX_SUBMODE_BITS_PER_FRAME, and speex_warning_int().
speex_decode_native()
int speex_decode_native (void * state, SpeexBits * bits, spx_word16_t * out)
Definition at line 78 of file speex.c.
 {
    return (*((SpeexMode**)state))->dec(state, bits, out);
 }
References bits(), and out.
Referenced by sb_decode().
speex_encode_native()
int speex_encode_native (void * state, spx_word16_t * in, SpeexBits * bits)
Definition at line 73 of file speex.c.
 {
    return (*((SpeexMode**)state))->enc(state, in, bits);
 }
References bits().
Referenced by sb_encode().
wb_mode_query()
int wb_mode_query (const void * mode, int request, void * ptr)
Definition at line 248 of file modes_wb.c.
 {
    const SpeexSBMode *m = (const SpeexSBMode*)mode;
    switch (request)
    {
       case SPEEX_MODE_FRAME_SIZE:
          *((int*)ptr)=2*m->frameSize;
          break;
       case SPEEX_SUBMODE_BITS_PER_FRAME:
          if (*((int*)ptr)==0)
             *((int*)ptr) = SB_SUBMODE_BITS+1;
          else if (m->submodes[*((int*)ptr)]==NULL)
             *((int*)ptr) = -1;
          else
             *((int*)ptr) = m->submodes[*((int*)ptr)]->bits_per_frame;
          break;
       default:
          speex_warning_int("Unknown wb_mode_query request: ", request);
          return -1;
    }
    return 0;
 }
References m, NULL, ptr(), SB_SUBMODE_BITS, SPEEX_MODE_FRAME_SIZE, SPEEX_SUBMODE_BITS_PER_FRAME, and speex_warning_int().