ZEQ2-Lite: Source/Engine/tools/lcc/lburg/lburg.c File Reference
lburg.c File Reference
#include <assert.h>
#include <ctype.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "lburg.h"
Data Structures
struct block
struct entry
Macros
#define HASHSIZE (sizeof table/sizeof table[0])
Functions
void * alloc (int nbytes)
static void ckreach (Nonterm p)
static char * computekids (Tree t, char *v, char *bp, int *ip)
static char * computents (Tree t, char *bp)
static void emitcase (Term p, int ntnumber)
static void emitclosure (Nonterm nts)
static void emitcost (Tree t, char *v)
static void emitdefs (Nonterm nts, int ntnumber)
static void emitheader (void)
static void emitkids (Rule rules, int nrules)
static void emitlabel (Term terms, Nonterm start, int ntnumber)
static void emitnts (Rule rules, int nrules)
static void emitrecalc (char *pre, Term root, Term kid)
static void emitrecord (char *pre, Rule r, char *c, int cost)
static void emitrule (Nonterm nts)
static void emitstring (Rule rules)
static void emitstruct (Nonterm nts, int ntnumber)
static void emittest (Tree t, char *v, char *suffix)
static unsigned hash (char *str)
static void * install (char *name)
static void * lookup (char *name)
int main (int argc, char *argv[])
Nonterm nonterm (char *id)
static void print (char *fmt,...)
static void reach (Tree t)
Rule rule (char *id, Tree pattern, char *template, char *code)
static char * stringf (char *fmt,...)
Term term (char *id, int esn)
Tree tree (char *id, Tree left, Tree right)
Variables
static struct block * memlist
static int nrules
static int ntnumber = 0
static Nonterm nts
static char * prefix = ""
static char rcsid [] = "lburg.c - faked rcsid"
static Rule rules
static Nonterm start = 0
struct entry * table [211]
static Term terms
static int Tflag = 0
Macro Definition Documentation
HASHSIZE
#define HASHSIZE (sizeof table/sizeof table[0])
Definition at line 137 of file lburg.c.
Function Documentation
alloc()
void* alloc (int nbytes)
Definition at line 106 of file lburg.c.
{
     struct block *p = calloc(1, sizeof *p + nbytes);
     if (p == NULL) {
         yyerror("out of memory\n");
         exit(1);
     }
     p->link = memlist;
     memlist = p;
     return p + 1;
 }
References memlist, NULL, and yyerror().
Referenced by emitkids(), emitnts(), install(), rule(), stringf(), and tree().
ckreach()
static void ckreach (Nonterm p) static
Definition at line 334 of file lburg.c.
{
     Rule r;
         p->reached = 1;
     for (r = p->rules; r; r = r->decode)
         reach(r->pattern);
 }
References reach().
Referenced by main(), and reach().
computekids()
static char* computekids (Tree t, char * v, char * bp, int * ip) static
Definition at line 468 of file lburg.c.
{
     Term p = t->op;
     if (p->kind == NONTERM) {
         sprintf(bp, "\t\tkids[%d] = %s;\n", (*ip)++, v);
         bp += strlen(bp);
     } else if (p->arity > 0) {
         bp = computekids(t->left, stringf("LEFT_CHILD(%s)", v), bp, ip);
         if (p->arity == 2)
             bp = computekids(t->right, stringf("RIGHT_CHILD(%s)", v), bp, ip);
     }
     return bp;
 }
References bp, NONTERM, and stringf().
Referenced by emitkids().
computents()
static char* computents (Tree t, char * bp) static
Definition at line 531 of file lburg.c.
{
     if (t) {
         Nonterm p = t->op;
         if (p->kind == NONTERM) {
             sprintf(bp, "%s_%s_NT, ", prefix, p->name);
             bp += strlen(bp);
         } else
             bp = computents(t->right, computents(t->left,  bp));
     }
     return bp;
 }
References bp, NONTERM, and prefix.
Referenced by emitnts().
emitcase()
static void emitcase (Term p, int ntnumber) static
Definition at line 343 of file lburg.c.
{
     Rule r;
     print("%1case %d: /* %S */\n", p->esn, p);
     switch (p->arity) {
     case 0: case -1:
         break;
     case 1:
         print("%2%Plabel(LEFT_CHILD(a));\n");
         break;
     case 2:
         print("%2%Plabel(LEFT_CHILD(a));\n");
         print("%2%Plabel(RIGHT_CHILD(a));\n");
         break;
     default: assert(0);
     }
     for (r = p->rules; r; r = r->next) {
         char *indent = "\t\t\0";
         switch (p->arity) {
         case 0: case -1:
             print("%2/* %R */\n", r);
             if (r->cost == -1) {
                 print("%2c = %s;\n", r->code);
                 emitrecord("\t\t", r, "c", 0);
             } else
                 emitrecord("\t\t", r, r->code, 0);
             break;
         case 1:
             if (r->pattern->nterms > 1) {
                 print("%2if (%1/* %R */\n", r);
                 emittest(r->pattern->left, "LEFT_CHILD(a)", " ");
                 print("%2) {\n");
                 indent = "\t\t\t";
             } else
                 print("%2/* %R */\n", r);
             if (r->pattern->nterms == 2 && r->pattern->left
             &&  r->pattern->right == NULL)
                 emitrecalc(indent, r->pattern->op, r->pattern->left->op);
             print("%sc = ", indent);
             emitcost(r->pattern->left, "LEFT_CHILD(a)");
             print("%s;\n", r->code);
             emitrecord(indent, r, "c", 0);
             if (indent[2])
                 print("%2}\n");
             break;
         case 2:
             if (r->pattern->nterms > 1) {
                 print("%2if (%1/* %R */\n", r);
                 emittest(r->pattern->left,  "LEFT_CHILD(a)",
                     r->pattern->right->nterms ? " && " : " ");
                 emittest(r->pattern->right, "RIGHT_CHILD(a)", " ");
                 print("%2) {\n");
                 indent = "\t\t\t";
             } else
                 print("%2/* %R */\n", r);
             print("%sc = ", indent);
             emitcost(r->pattern->left,  "LEFT_CHILD(a)");
             emitcost(r->pattern->right, "RIGHT_CHILD(a)");
             print("%s;\n", r->code);
             emitrecord(indent, r, "c", 0);
             if (indent[2])
                 print("%2}\n");
             break;
         default: assert(0);
         }
     }
     print("%2break;\n");
 }
References emitcost(), emitrecalc(), emitrecord(), emittest(), NULL, and print().
Referenced by emitlabel().
emitclosure()
static void emitclosure (Nonterm nts) static
Definition at line 413 of file lburg.c.
{
     Nonterm p;
     for (p = nts; p; p = p->link)
         if (p->chain)
             print("static void %Pclosure_%S(NODEPTR_TYPE, int);\n", p);
     print("\n");
     for (p = nts; p; p = p->link)
         if (p->chain) {
             Rule r;
             print("static void %Pclosure_%S(NODEPTR_TYPE a, int c) {\n"
 "%1struct %Pstate *p = STATE_LABEL(a);\n", p);
             for (r = p->chain; r; r = r->chain)
                 emitrecord("\t", r, "c", r->cost);
             print("}\n\n");
         }
 }
References emitrecord(), nts, and print().
Referenced by main().
emitcost()
static void emitcost (Tree t, char * v) static
Definition at line 432 of file lburg.c.
{
     Nonterm p = t->op;
     if (p->kind == TERM) {
         if (t->left)
             emitcost(t->left,  stringf("LEFT_CHILD(%s)",  v));
         if (t->right)
             emitcost(t->right, stringf("RIGHT_CHILD(%s)", v));
     } else
         print("((struct %Pstate *)(%s->x.state))->cost[%P%S_NT] + ", v, p);
 }
References print(), stringf(), and TERM.
Referenced by emitcase().
emitdefs()
static void emitdefs (Nonterm nts, int ntnumber) static
Definition at line 445 of file lburg.c.
{
     Nonterm p;
     for (p = nts; p; p = p->link)
         print("#define %P%S_NT %d\n", p, p->number);
     print("\n");
     print("static char *%Pntname[] = {\n%10,\n");
     for (p = nts; p; p = p->link)
         print("%1\"%S\",\n", p);
     print("%10\n};\n\n");
 }
References nts, and print().
Referenced by main().
emitheader()
static void emitheader (void) static
Definition at line 458 of file lburg.c.
{
     time_t timer = time(NULL);
     print("/*\ngenerated at %sby %s\n*/\n", ctime(&timer), rcsid);
     print("static void %Pkids(NODEPTR_TYPE, int, NODEPTR_TYPE[]);\n");
     print("static void %Plabel(NODEPTR_TYPE);\n");
     print("static int %Prule(void*, int);\n\n");
 }
References NULL, print(), and rcsid.
Referenced by main().
emitkids()
static void emitkids (Rule rules, int nrules) static
Definition at line 483 of file lburg.c.
{
     int i;
     Rule r, *rc = alloc((nrules + 1 + 1)*sizeof *rc);
     char **str  = alloc((nrules + 1 + 1)*sizeof *str);
     for (i = 0, r = rules; r; r = r->link) {
         int j = 0;
         char buf[1024], *bp = buf;
         *computekids(r->pattern, "p", bp, &j) = 0;
         for (j = 0; str[j] && strcmp(str[j], buf); j++)
             ;
         if (str[j] == NULL)
             str[j] = strcpy(alloc(strlen(buf) + 1), buf);
         r->kids = rc[j];
         rc[j] = r;
     }
     print("static void %Pkids(NODEPTR_TYPE p, int eruleno, NODEPTR_TYPE kids[]) {\n"
 "%1if (!p)\n%2fatal(\"%Pkids\", \"Null tree\\n\", 0);\n"
 "%1if (!kids)\n%2fatal(\"%Pkids\", \"Null kids\\n\", 0);\n"
 "%1switch (eruleno) {\n");
     for (i = 0; (r = rc[i]) != NULL; i++) {
         for ( ; r; r = r->kids)
             print("%1case %d: /* %R */\n", r->ern, r);
         print("%s%2break;\n", str[i]);
     }
     print("%1default:\n%2fatal(\"%Pkids\", \"Bad rule number %%d\\n\", eruleno);\n%1}\n}\n\n");
 }
References alloc(), bp, computekids(), nrules, NULL, print(), and rules.
Referenced by main().
emitlabel()
static void emitlabel (Term terms, Nonterm start, int ntnumber) static
Definition at line 512 of file lburg.c.
{
     int i;
     Term p;
     print("static void %Plabel(NODEPTR_TYPE a) {\n%1int c;\n"
 "%1struct %Pstate *p;\n\n"
 "%1if (!a)\n%2fatal(\"%Plabel\", \"Null tree\\n\", 0);\n");
     print("%1STATE_LABEL(a) = p = allocate(sizeof *p, FUNC);\n"
 "%1p->rule._stmt = 0;\n");
     for (i = 1; i <= ntnumber; i++)
         print("%1p->cost[%d] =\n", i);
     print("%20x7fff;\n%1switch (OP_LABEL(a)) {\n");
     for (p = terms; p; p = p->link)
         emitcase(p, ntnumber);
     print("%1default:\n"
 "%2fatal(\"%Plabel\", \"Bad terminal %%d\\n\", OP_LABEL(a));\n%1}\n}\n\n");
 }
References emitcase(), ntnumber, print(), and terms.
Referenced by main().
emitnts()
static void emitnts (Rule rules, int nrules) static
Definition at line 544 of file lburg.c.
{
     Rule r;
     int i, j, *nts = alloc((nrules + 1)*sizeof *nts);
     char **str = alloc((nrules + 1)*sizeof *str);
     for (i = 0, r = rules; r; r = r->link) {
         char buf[1024];
         *computents(r->pattern, buf) = 0;
         for (j = 0; str[j] && strcmp(str[j], buf); j++)
             ;
         if (str[j] == NULL) {
             print("static short %Pnts_%d[] = { %s0 };\n", j, buf);
             str[j] = strcpy(alloc(strlen(buf) + 1), buf);
         }
         nts[i++] = j;
     }
     print("\nstatic short *%Pnts[] = {\n");
     for (i = j = 0, r = rules; r; r = r->link) {
         for ( ; j < r->ern; j++)
             print("%10,%1/* %d */\n", j);
         print("%1%Pnts_%d,%1/* %d */\n", nts[i++], j++);
     }
     print("};\n\n");
 }
References alloc(), computents(), nrules, nts, NULL, print(), and rules.
Referenced by main().
emitrecalc()
static void emitrecalc (char * pre, Term root, Term kid) static
Definition at line 570 of file lburg.c.
{
     if (root->kind == TERM && strncmp(root->name, "INDIR", 5) == 0
     &&   kid->kind == TERM &&  strcmp(kid->name,  "VREGP"   ) == 0) {
         Nonterm p;
         print("%sif (mayrecalc(a)) {\n", pre);
         print("%s%1struct %Pstate *q = a->syms[RX]->u.t.cse->x.state;\n", pre);
         for (p = nts; p; p = p->link) {
             print("%s%1if (q->cost[%P%S_NT] == 0) {\n", pre, p);
             print("%s%2p->cost[%P%S_NT] = 0;\n", pre, p);
             print("%s%2p->rule.%P%S = q->rule.%P%S;\n", pre, p, p);
             print("%s%1}\n", pre);
         }
         print("%s}\n", pre);
     }
 }
References nts, print(), root(), and TERM.
Referenced by emitcase().
emitrecord()
static void emitrecord (char * pre, Rule r, char * c, int cost) static
Definition at line 587 of file lburg.c.
{
     if (Tflag)
         print("%s%Ptrace(a, %d, %s + %d, p->cost[%P%S_NT]);\n",
             pre, r->ern, c, cost, r->lhs);
     print("%sif (", pre);
     print("%s + %d < p->cost[%P%S_NT]) {\n"
 "%s%1p->cost[%P%S_NT] = %s + %d;\n%s%1p->rule.%P%S = %d;\n",
         c, cost, r->lhs, pre, r->lhs, c, cost, pre, r->lhs,
         r->packed);
     if (r->lhs->chain)
         print("%s%1%Pclosure_%S(a, %s + %d);\n", pre, r->lhs, c, cost);
     print("%s}\n", pre);
 }
References print(), and Tflag.
Referenced by emitcase(), and emitclosure().
emitrule()
static void emitrule (Nonterm nts) static
Definition at line 602 of file lburg.c.
{
     Nonterm p;
     for (p = nts; p; p = p->link) {
         Rule r;
         print("static short %Pdecode_%S[] = {\n%10,\n", p);
         for (r = p->rules; r; r = r->decode)
             print("%1%d,\n", r->ern);
         print("};\n\n");
     }
     print("static int %Prule(void *state, int goalnt) {\n"
 "%1if (goalnt < 1 || goalnt > %d)\n%2fatal(\"%Prule\", \"Bad goal nonterminal %%d\\n\", goalnt);\n"
 "%1if (!state)\n%2return 0;\n%1switch (goalnt) {\n", ntnumber);
     for (p = nts; p; p = p->link)
         print("%1case %P%S_NT:"
 "%1return %Pdecode_%S[((struct %Pstate *)state)->rule.%P%S];\n", p, p, p);
     print("%1default:\n%2fatal(\"%Prule\", \"Bad goal nonterminal %%d\\n\", goalnt);\n%2return 0;\n%1}\n}\n\n");
 }
References ntnumber, nts, and print().
Referenced by main().
emitstring()
static void emitstring (Rule rules) static
Definition at line 622 of file lburg.c.
{
     Rule r;
     print("static char *%Ptemplates[] = {\n");
     print("/* 0 */%10,\n");
     for (r = rules; r; r = r->link)
         print("/* %d */%1\"%s\",%1/* %R */\n", r->ern, r->template, r);
     print("};\n");
     print("\nstatic char %Pisinstruction[] = {\n");
     print("/* 0 */%10,\n");
     for (r = rules; r; r = r->link) {
         int len = strlen(r->template);
         print("/* %d */%1%d,%1/* %s */\n", r->ern,
             len >= 2 && r->template[len-2] == '\\' && r->template[len-1] == 'n',
             r->template);
     }
     print("};\n");
     print("\nstatic char *%Pstring[] = {\n");
     print("/* 0 */%10,\n");
     for (r = rules; r; r = r->link)
         print("/* %d */%1\"%R\",\n", r->ern, r);
     print("};\n\n");
 }
References print(), and rules.
Referenced by main().
emitstruct()
static void emitstruct (Nonterm nts, int ntnumber) static
Definition at line 647 of file lburg.c.
{
     print("struct %Pstate {\n%1short cost[%d];\n%1struct {\n", ntnumber + 1);
     for ( ; nts; nts = nts->link) {
         int n = 1, m = nts->lhscount;
         while ((m >>= 1) != 0)
             n++;
         print("%2unsigned int %P%S:%d;\n", nts, n);
     }
     print("%1} rule;\n};\n\n");
 }
References m, ntnumber, nts, and print().
Referenced by main().
emittest()
static void emittest (Tree t, char * v, char * suffix) static
Definition at line 659 of file lburg.c.
{
     Term p = t->op;
     if (p->kind == TERM) {
         print("%3%s->op == %d%s/* %S */\n", v, p->esn,
             t->nterms > 1 ? " && " : suffix, p);
         if (t->left)
             emittest(t->left, stringf("LEFT_CHILD(%s)",  v),
                 t->right && t->right->nterms ? " && " : suffix);
         if (t->right)
             emittest(t->right, stringf("RIGHT_CHILD(%s)", v), suffix);
     }
 }
References print(), stringf(), suffix(), and TERM.
Referenced by emitcase().
hash()
static unsigned hash (char * str) static
Definition at line 140 of file lburg.c.
{
     unsigned h = 0;
     while (*str)
         h = (h<<1) + *str++;
     return h;
 }
Referenced by AssembleLine(), Com_HashKey(), Cvar_FindVar(), Cvar_Get(), DefineSymbol(), FindShaderInShaderText(), FS_FileIsInPAK(), FS_FOpenFileReadDir(), FS_HashFileName(), FS_LoadZipFile(), generateHashValue(), GeneratePermanentShader(), hashkey(), hashtable_symbol_exists(), install(), lookup(), LookupSymbol(), MSG_HashKey(), R_CreateImage(), R_FindImageFile(), R_FindShader(), R_FindShaderByName(), R_MDM_AddAnimSurfaces(), R_RemapShader(), RE_RegisterShaderFromImage(), S_FindName(), S_HashSFXName(), ScanAndLoadShaderFiles(), SVC_BucketForAddress(), and SVC_HashForAddress().
install()
static void* install (char * name) static
Definition at line 159 of file lburg.c.
{
     struct entry *p = alloc(sizeof *p);
     int i = hash(name)%HASHSIZE;
     p->sym.name = name;
     p->link = table[i];
     table[i] = p;
     return &p->sym;
 }
References alloc(), hash(), and HASHSIZE.
Referenced by dclglobal(), dcllocal(), dclparam(), decl(), enumdcl(), lookup(), main_init(), newfield(), newstruct(), nonterm(), primary(), statement(), stmtlabel(), term(), type_init(), and xxinit().
lookup()
static void* lookup (char * name) static
Definition at line 149 of file lburg.c.
{
     struct entry *p = table[hash(name)%HASHSIZE];
     for ( ; p; p = p->link)
         if (strcmp(name, p->sym.name) == 0)
             return &p->sym;
     return 0;
 }
References hash(), and HASHSIZE.
Referenced by nonterm(), term(), and tree().
main()
int main (int argc, char * argv[])
Definition at line 41 of file lburg.c.
{
     int c, i;
     Nonterm p;
     for (i = 1; i < argc; i++)
         if (strcmp(argv[i], "-T") == 0)
             Tflag = 1;
         else if (strncmp(argv[i], "-p", 2) == 0 && argv[i][2])
             prefix = &argv[i][2];
         else if (strncmp(argv[i], "-p", 2) == 0 && i + 1 < argc)
             prefix = argv[++i];
         else if (*argv[i] == '-' && argv[i][1]) {
             yyerror("usage: %s [-T | -p prefix]... [ [ input ] output ] \n",
                 argv[0]);
             exit(1);
         } else if (infp == NULL) {
             if (strcmp(argv[i], "-") == 0)
                 infp = stdin;
             else if ((infp = fopen(argv[i], "r")) == NULL) {
                 yyerror("%s: can't read `%s'\n", argv[0], argv[i]);
                 exit(1);
             }
         } else if (outfp == NULL) {
             if (strcmp(argv[i], "-") == 0)
                 outfp = stdout;
             if ((outfp = fopen(argv[i], "w")) == NULL) {
                 yyerror("%s: can't write `%s'\n", argv[0], argv[i]);
                 exit(1);
             }
         }
     if (infp == NULL)
         infp = stdin;
     if (outfp == NULL)
         outfp = stdout;
     yyparse();
     if (start)
         ckreach(start);
     for (p = nts; p; p = p->link) {
         if (p->rules == NULL)
             yyerror("undefined nonterminal `%s'\n", p->name);
         if (!p->reached)
             yyerror("can't reach nonterminal `%s'\n", p->name);
     }
     emitheader();
     emitdefs(nts, ntnumber);
     emitstruct(nts, ntnumber);
     emitnts(rules, nrules);
     emitstring(rules);
     emitrule(nts);
     emitclosure(nts);
     if (start)
         emitlabel(terms, start, ntnumber);
     emitkids(rules, nrules);
     if (!feof(infp))
         while ((c = getc(infp)) != EOF)
             putc(c, outfp);
     while (memlist) {   /* for purify */
         struct block *q = memlist->link;
         free(memlist);
         memlist = q;
     }
     return errcnt > 0;
 }
References ckreach(), emitclosure(), emitdefs(), emitheader(), emitkids(), emitlabel(), emitnts(), emitrule(), emitstring(), emitstruct(), EOF, errcnt, infp, block::link, memlist, nrules, ntnumber, nts, NULL, outfp, prefix, rules, terms, Tflag, yyerror(), and yyparse().
nonterm()
Nonterm nonterm (char * id)
Definition at line 170 of file lburg.c.
{
     Nonterm p = lookup(id), *q = &nts;
     if (p && p->kind == NONTERM)
         return p;
     if (p && p->kind == TERM)
         yyerror("`%s' is a terminal\n", id);
     p = install(id);
     p->kind = NONTERM;
     p->number = ++ntnumber;
     if (p->number == 1)
         start = p;
     while (*q && (*q)->number < p->number)
         q = &(*q)->link;
     assert(*q == 0 || (*q)->number != p->number);
     p->link = *q;
     *q = p;
     return p;
 }
References install(), lookup(), NONTERM, ntnumber, nts, TERM, and yyerror().
Referenced by rule(), tree(), and yyparse().
print()
static void print (char * fmt, ...) static
Definition at line 282 of file lburg.c.
{
     va_list ap;
     va_start(ap, fmt);
     for ( ; *fmt; fmt++)
         if (*fmt == '%')
             switch (*++fmt) {
             case 'd': fprintf(outfp, "%d", va_arg(ap, int)); break;
             case 's': fputs(va_arg(ap, char *), outfp); break;
             case 'P': fprintf(outfp, "%s_", prefix); break;
             case 'T': {
                 Tree t = va_arg(ap, Tree);
                 print("%S", t->op);
                 if (t->left && t->right)
                     print("(%T,%T)", t->left, t->right);
                 else if (t->left)
                     print("(%T)", t->left);
                 break;
                 }
             case 'R': {
                 Rule r = va_arg(ap, Rule);
                 print("%S: %T", r->lhs, r->pattern);
                 break;
                 }
             case 'S': fputs(va_arg(ap, Term)->name, outfp); break;
             case '1': case '2': case '3': case '4': case '5': {
                 int n = *fmt - '0';
                 while (n-- > 0)
                     putc('\t', outfp);
                 break;
                 }
             default: putc(*fmt, outfp); break;
             }
         else
             putc(*fmt, outfp);
     va_end(ap);
 }
References fmt, outfp, and prefix.
Referenced by address(), blockbeg(), blockend(), defaddress(), defconst(), defstring(), dumptree(), emit(), emitasm(), emitcase(), emitclosure(), emitCoord(), emitcost(), emitdefs(), emitheader(), emitkids(), emitlabel(), emitnts(), emitrecalc(), emitrecord(), emitrule(), emitString(), emitstring(), emitstruct(), emitSymbol(), emitSymRef(), emittest(), export(), fatal(), function(), global(), import(), LoadSourceFile(), local(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), PrintToSourceLine(), progbeg(), progend(), segment(), space(), stabend(), stabline(), yyBEGIN(), and yyEND().
reach()
static void reach (Tree t) static
Definition at line 321 of file lburg.c.
{
     Nonterm p = t->op;
     if (p->kind == NONTERM)
         if (!p->reached)
             ckreach(p);
     if (t->left)
         reach(t->left);
     if (t->right)
         reach(t->right);
 }
References ckreach(), and NONTERM.
Referenced by ckreach().
rule()
Rule rule (char * id, Tree pattern, char * template, char * code)
Definition at line 244 of file lburg.c.
{
     Rule r = alloc(sizeof *r), *q;
     Term p = pattern->op;
     char *end;
     r->lhs = nonterm(id);
     r->packed = ++r->lhs->lhscount;
     for (q = &r->lhs->rules; *q; q = &(*q)->decode)
         ;
     *q = r;
     r->pattern = pattern;
     r->ern = ++nrules;
     r->template = template;
     r->code = code;
     r->cost = strtol(code, &end, 10);
     if (*end) {
         r->cost = -1;
         r->code = stringf("(%s)", code);
     }
     if (p->kind == TERM) {
         for (q = &p->rules; *q; q = &(*q)->next)
             ;
         *q = r;
     } else if (pattern->left == NULL && pattern->right == NULL) {
         Nonterm p = pattern->op;
         r->chain = p->chain;
             p->chain = r;
         if (r->cost == -1)
             yyerror("illegal nonconstant cost `%s'\n", code);
     }
     for (q = &rules; *q; q = &(*q)->link)
         ;
     r->link = *q;
     *q = r;
     return r;
 }
References alloc(), code, nonterm(), nrules, NULL, rules, stringf(), TERM, and yyerror().
Referenced by yyparse().
stringf()
static char * stringf (char * fmt, ...) static
Definition at line 119 of file lburg.c.
{
     va_list ap;
     char buf[512];
     va_start(ap, fmt);
     vsprintf(buf, fmt, ap);
     va_end(ap);
     return strcpy(alloc(strlen(buf) + 1), buf);
 }
References alloc(), and fmt.
Referenced by computekids(), emitcost(), emittest(), and rule().
term()
Term term (char * id, int esn)
Definition at line 191 of file lburg.c.
{
     Term p = lookup(id), *q = &terms;
     if (p)
         yyerror("redefinition of terminal `%s'\n", id);
     else
         p = install(id);
     p->kind = TERM;
     p->esn = esn;
     p->arity = -1;
     while (*q && (*q)->esn < p->esn)
         q = &(*q)->link;
     if (*q && (*q)->esn == p->esn)
         yyerror("duplicate external symbol number `%s=%d'\n",
             p->name, p->esn);
     p->link = *q;
     *q = p;
     return p;
 }
References install(), lookup(), TERM, terms, and yyerror().
Referenced by tree(), and yyparse().
tree()
Tree tree (char * id, Tree left, Tree right)
Definition at line 212 of file lburg.c.
{
     Tree t = alloc(sizeof *t);
     Term p = lookup(id);
     int arity = 0;
     if (left && right)
         arity = 2;
     else if (left)
         arity = 1;
     if (p == NULL && arity > 0) {
         yyerror("undefined terminal `%s'\n", id);
         p = term(id, -1);
     } else if (p == NULL && arity == 0)
         p = (Term)nonterm(id);
     else if (p && p->kind == NONTERM && arity > 0) {
         yyerror("`%s' is a nonterminal\n", id);
         p = term(id, -1);
     }
     if (p->kind == TERM && p->arity == -1)
         p->arity = arity;
     if (p->kind == TERM && arity != p->arity)
         yyerror("inconsistent arity for terminal `%s'\n", id);
     t->op = p;
     t->nterms = p->kind == TERM;
     if ((t->left = left) != NULL)
         t->nterms += left->nterms;
     if ((t->right = right) != NULL)
         t->nterms += right->nterms;
     return t;
 }
References alloc(), lookup(), NONTERM, nonterm(), NULL, right, TERM, term(), and yyerror().
Referenced by addrof(), addrtree(), asgn(), asgntree(), bbcall(), bbincr(), call(), calltree(), cnsttree(), condtree(), expr(), field(), idtree(), listnodes(), nullcheck(), postfix(), primary(), retcode(), retype(), rvalue(), simplify(), swcode(), tracefinis(), tracevalue(), unary(), vcall(), and yyparse().
Variable Documentation
memlist
struct block * memlist static
Referenced by alloc(), and main().
nrules
int nrules static
Definition at line 19 of file lburg.c.
Referenced by emitkids(), emitnts(), main(), and rule().
ntnumber
int ntnumber = 0 static
Definition at line 14 of file lburg.c.
Referenced by emitlabel(), emitrule(), emitstruct(), main(), and nonterm().
nts
Nonterm nts static
Definition at line 17 of file lburg.c.
Referenced by dumpcover(), emitasm(), emitclosure(), emitdefs(), emitnts(), emitrecalc(), emitrule(), emitstruct(), main(), nonterm(), and reduce().
prefix
char* prefix = "" static
Definition at line 12 of file lburg.c.
Referenced by CL_UpdateGUID(), Com_MD5File(), computents(), main(), and print().
rcsid
char rcsid[] = "lburg.c - faked rcsid" static
Definition at line 10 of file lburg.c.
Referenced by emitheader().
rules
Rule rules static
Definition at line 18 of file lburg.c.
Referenced by emitkids(), emitnts(), emitstring(), main(), and rule().
start
Nonterm start = 0 static
Definition at line 15 of file lburg.c.
table
struct entry * table[211]
terms
Term terms static
Definition at line 16 of file lburg.c.
Referenced by emitlabel(), main(), and term().
Tflag
int Tflag = 0 static
Definition at line 13 of file lburg.c.
Referenced by emitrecord(), and main().