ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/i686-pc-mingw32/bits/gthr-single.h File Reference
gthr-single.h File Reference
Macros
#define __GTHREAD_MUTEX_INIT 0
#define __GTHREAD_ONCE_INIT 0
#define __GTHREAD_RECURSIVE_MUTEX_INIT 0
#define _GLIBCXX_UNUSED __attribute__((unused))
Typedefs
typedef int __gthread_key_t
typedef int __gthread_mutex_t
typedef int __gthread_once_t
typedef int __gthread_recursive_mutex_t
Functions
static int __gthread_active_p (void)
static void * __gthread_getspecific (__gthread_key_t __key _GLIBCXX_UNUSED)
static int _GLIBCXX_UNUSED __gthread_key_create (__gthread_key_t *__key _GLIBCXX_UNUSED, void(*__func)(void *) _GLIBCXX_UNUSED)
static int _GLIBCXX_UNUSED __gthread_key_delete (__gthread_key_t __key _GLIBCXX_UNUSED)
static int __gthread_mutex_destroy (__gthread_mutex_t *__mutex _GLIBCXX_UNUSED)
static int __gthread_mutex_lock (__gthread_mutex_t *__mutex _GLIBCXX_UNUSED)
static int __gthread_mutex_trylock (__gthread_mutex_t *__mutex _GLIBCXX_UNUSED)
static int __gthread_mutex_unlock (__gthread_mutex_t *__mutex _GLIBCXX_UNUSED)
static int __gthread_once (__gthread_once_t *__once _GLIBCXX_UNUSED, void(*__func)(void) _GLIBCXX_UNUSED)
static int __gthread_recursive_mutex_lock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_trylock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_unlock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_setspecific (__gthread_key_t __key _GLIBCXX_UNUSED, const void *__v _GLIBCXX_UNUSED)
Macro Definition Documentation
__GTHREAD_MUTEX_INIT
#define __GTHREAD_MUTEX_INIT 0
Definition at line 38 of file gthr-single.h.
__GTHREAD_ONCE_INIT
#define __GTHREAD_ONCE_INIT 0
Definition at line 37 of file gthr-single.h.
__GTHREAD_RECURSIVE_MUTEX_INIT
#define __GTHREAD_RECURSIVE_MUTEX_INIT 0
Definition at line 39 of file gthr-single.h.
_GLIBCXX_UNUSED
#define _GLIBCXX_UNUSED __attribute__((unused))
Definition at line 41 of file gthr-single.h.
Typedef Documentation
__gthread_key_t
typedef int __gthread_key_t
Definition at line 32 of file gthr-single.h.
__gthread_mutex_t
typedef int __gthread_mutex_t
Definition at line 34 of file gthr-single.h.
__gthread_once_t
typedef int __gthread_once_t
Definition at line 33 of file gthr-single.h.
__gthread_recursive_mutex_t
typedef int __gthread_recursive_mutex_t
Definition at line 35 of file gthr-single.h.
Function Documentation
__gthread_active_p()
static int __gthread_active_p (void) inline static
Definition at line 211 of file gthr-single.h.
 {
   return 0;
 }
__gthread_getspecific()
static void* __gthread_getspecific (__gthread_key_t __key _GLIBCXX_UNUSED) inline static
Definition at line 235 of file gthr-single.h.
 {
   return 0;
 }
__gthread_key_create()
static int _GLIBCXX_UNUSED __gthread_key_create (__gthread_key_t *__key _GLIBCXX_UNUSED, void(*)(void *) _GLIBCXX_UNUSED __func) inline static
Definition at line 223 of file gthr-single.h.
 {
   return 0;
 }
__gthread_key_delete()
static int _GLIBCXX_UNUSED __gthread_key_delete (__gthread_key_t __key _GLIBCXX_UNUSED) static
Definition at line 229 of file gthr-single.h.
 {
   return 0;
 }
__gthread_mutex_destroy()
static int __gthread_mutex_destroy (__gthread_mutex_t *__mutex _GLIBCXX_UNUSED) inline static
Definition at line 247 of file gthr-single.h.
 {
   return 0;
 }
__gthread_mutex_lock()
static int __gthread_mutex_lock (__gthread_mutex_t *__mutex _GLIBCXX_UNUSED) inline static
Definition at line 253 of file gthr-single.h.
 {
   return 0;
 }
Referenced by __gthread_recursive_mutex_lock().
__gthread_mutex_trylock()
static int __gthread_mutex_trylock (__gthread_mutex_t *__mutex _GLIBCXX_UNUSED) inline static
Definition at line 259 of file gthr-single.h.
 {
   return 0;
 }
Referenced by __gthread_recursive_mutex_trylock().
__gthread_mutex_unlock()
static int __gthread_mutex_unlock (__gthread_mutex_t *__mutex _GLIBCXX_UNUSED) inline static
Definition at line 265 of file gthr-single.h.
 {
   return 0;
 }
Referenced by __gthread_recursive_mutex_unlock().
__gthread_once()
static int __gthread_once (__gthread_once_t *__once _GLIBCXX_UNUSED, void(*)(void) _GLIBCXX_UNUSED __func) inline static
Definition at line 217 of file gthr-single.h.
 {
   return 0;
 }
__gthread_recursive_mutex_lock()
static int __gthread_recursive_mutex_lock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 271 of file gthr-single.h.
 {
   return __gthread_mutex_lock (__mutex);
 }
References __gthread_mutex_lock().
__gthread_recursive_mutex_trylock()
static int __gthread_recursive_mutex_trylock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 277 of file gthr-single.h.
 {
   return __gthread_mutex_trylock (__mutex);
 }
References __gthread_mutex_trylock().
__gthread_recursive_mutex_unlock()
static int __gthread_recursive_mutex_unlock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 283 of file gthr-single.h.
 {
   return __gthread_mutex_unlock (__mutex);
 }
References __gthread_mutex_unlock().
__gthread_setspecific()
static int __gthread_setspecific (__gthread_key_t __key _GLIBCXX_UNUSED, const void *__v _GLIBCXX_UNUSED) inline static
Definition at line 241 of file gthr-single.h.
 {
   return 0;
 }