ZEQ2-Lite: Source/Engine/SDL12/include/SDL_joystick.h File Reference
SDL_joystick.h File Reference
#include "SDL_stdinc.h"
#include "SDL_error.h"
#include "begin_code.h"
#include "close_code.h"
Typedefs
typedef struct _SDL_Joystick SDL_Joystick
Functions
DECLSPEC int SDLCALL SDL_JoystickEventState (int state)
Enable/disable joystick event polling.
DECLSPEC Sint16 SDLCALL SDL_JoystickGetAxis (SDL_Joystick *joystick, int axis)
Get the current state of an axis control on a joystick.
DECLSPEC int SDLCALL SDL_JoystickIndex (SDL_Joystick *joystick)
Get the device index of an opened joystick.
const DECLSPEC char *SDLCALL SDL_JoystickName (int device_index)
Get the implementation dependent name of a joystick.
DECLSPEC int SDLCALL SDL_JoystickNumAxes (SDL_Joystick *joystick)
Get the number of general axis controls on a joystick.
DECLSPEC int SDLCALL SDL_JoystickNumBalls (SDL_Joystick *joystick)
Get the number of trackballs on a joystick.
DECLSPEC int SDLCALL SDL_JoystickNumButtons (SDL_Joystick *joystick)
Get the number of buttons on a joystick.
DECLSPEC int SDLCALL SDL_JoystickNumHats (SDL_Joystick *joystick)
Get the number of POV hats on a joystick.
DECLSPEC SDL_Joystick *SDLCALL SDL_JoystickOpen (int device_index)
Open a joystick for use.
DECLSPEC int SDLCALL SDL_JoystickOpened (int device_index)
Returns 1 if the joystick has been opened, or 0 if it has not.
DECLSPEC void SDLCALL SDL_JoystickUpdate (void)
Update the current state of the open joysticks.
DECLSPEC int SDLCALL SDL_NumJoysticks (void)
Count the number of joysticks attached to the system.
Hat Positions
The return value of SDL_JoystickGetHat() is one of the following positions:
#define SDL_HAT_CENTERED 0x00
#define SDL_HAT_DOWN 0x04
#define SDL_HAT_LEFT 0x08
#define SDL_HAT_LEFTDOWN (SDL_HAT_LEFT|SDL_HAT_DOWN)
#define SDL_HAT_LEFTUP (SDL_HAT_LEFT|SDL_HAT_UP)
#define SDL_HAT_RIGHT 0x02
#define SDL_HAT_RIGHTDOWN (SDL_HAT_RIGHT|SDL_HAT_DOWN)
#define SDL_HAT_RIGHTUP (SDL_HAT_RIGHT|SDL_HAT_UP)
#define SDL_HAT_UP 0x01
DECLSPEC void SDLCALL SDL_JoystickClose (SDL_Joystick *joystick)
Close a joystick previously opened with SDL_JoystickOpen()
DECLSPEC int SDLCALL SDL_JoystickGetBall (SDL_Joystick *joystick, int ball, int *dx, int *dy)
Get the ball axis change since the last poll.
DECLSPEC Uint8 SDLCALL SDL_JoystickGetButton (SDL_Joystick *joystick, int button)
Get the current state of a button on a joystick.
DECLSPEC Uint8 SDLCALL SDL_JoystickGetHat (SDL_Joystick *joystick, int hat)
Get the current state of a POV hat on a joystick.
Detailed Description
Include file for SDL joystick event handling
Note
In order to use these functions, SDL_Init() must have been called with the SDL_INIT_JOYSTICK flag. This causes SDL to scan the system for joysticks, and load appropriate drivers.
Definition in file SDL_joystick.h.
Macro Definition Documentation
SDL_HAT_CENTERED
#define SDL_HAT_CENTERED 0x00
Definition at line 141 of file SDL_joystick.h.
SDL_HAT_DOWN
#define SDL_HAT_DOWN 0x04
Definition at line 144 of file SDL_joystick.h.
SDL_HAT_LEFT
#define SDL_HAT_LEFT 0x08
Definition at line 145 of file SDL_joystick.h.
SDL_HAT_LEFTDOWN
#define SDL_HAT_LEFTDOWN (SDL_HAT_LEFT|SDL_HAT_DOWN)
Definition at line 149 of file SDL_joystick.h.
SDL_HAT_LEFTUP
#define SDL_HAT_LEFTUP (SDL_HAT_LEFT|SDL_HAT_UP)
Definition at line 148 of file SDL_joystick.h.
SDL_HAT_RIGHT
#define SDL_HAT_RIGHT 0x02
Definition at line 143 of file SDL_joystick.h.
SDL_HAT_RIGHTDOWN
#define SDL_HAT_RIGHTDOWN (SDL_HAT_RIGHT|SDL_HAT_DOWN)
Definition at line 147 of file SDL_joystick.h.
SDL_HAT_RIGHTUP
#define SDL_HAT_RIGHTUP (SDL_HAT_RIGHT|SDL_HAT_UP)
Definition at line 146 of file SDL_joystick.h.
SDL_HAT_UP
#define SDL_HAT_UP 0x01
Definition at line 142 of file SDL_joystick.h.
Typedef Documentation
SDL_Joystick
typedef struct _SDL_Joystick SDL_Joystick
Definition at line 47 of file SDL_joystick.h.
Function Documentation
SDL_JoystickClose()
DECLSPEC void SDLCALL SDL_JoystickClose (SDL_Joystick * joystick)
Close a joystick previously opened with SDL_JoystickOpen()
Referenced by IN_InitJoystick(), and IN_ShutdownJoystick().
SDL_JoystickEventState()
DECLSPEC int SDLCALL SDL_JoystickEventState (int state)
Enable/disable joystick event polling.
If joystick events are disabled, you must call SDL_JoystickUpdate() yourself and check the state of the joystick when you want joystick information.
Parameters
[in] state The state can be one of SDL_QUERY, SDL_ENABLE or SDL_IGNORE.
Referenced by IN_InitJoystick().
SDL_JoystickGetAxis()
DECLSPEC Sint16 SDLCALL SDL_JoystickGetAxis (SDL_Joystick * joystick, int axis)
Get the current state of an axis control on a joystick.
Parameters
[in] axis The axis indices start at index 0.
Returns
The state is a value ranging from -32768 to 32767.
Referenced by IN_JoyMove().
SDL_JoystickGetBall()
DECLSPEC int SDLCALL SDL_JoystickGetBall (SDL_Joystick * joystick, int ball, int * dx, int * dy)
Get the ball axis change since the last poll.
Parameters
[in] ball The ball indices start at index 0.
Returns
This returns 0, or -1 if you passed it invalid parameters.
Referenced by IN_JoyMove().
SDL_JoystickGetButton()
DECLSPEC Uint8 SDLCALL SDL_JoystickGetButton (SDL_Joystick * joystick, int button)
Get the current state of a button on a joystick.
Parameters
[in] button The button indices start at index 0.
Referenced by IN_JoyMove().
SDL_JoystickGetHat()
DECLSPEC Uint8 SDLCALL SDL_JoystickGetHat (SDL_Joystick * joystick, int hat)
Get the current state of a POV hat on a joystick.
Parameters
[in] hat The hat indices start at index 0.
Referenced by IN_JoyMove().
SDL_JoystickIndex()
DECLSPEC int SDLCALL SDL_JoystickIndex (SDL_Joystick * joystick)
Get the device index of an opened joystick.
SDL_JoystickName()
const DECLSPEC char* SDLCALL SDL_JoystickName (int device_index)
Get the implementation dependent name of a joystick.
This can be called before any joysticks are opened. If no name can be found, this function returns NULL.
Referenced by IN_InitJoystick().
SDL_JoystickNumAxes()
DECLSPEC int SDLCALL SDL_JoystickNumAxes (SDL_Joystick * joystick)
Get the number of general axis controls on a joystick.
Referenced by IN_InitJoystick(), and IN_JoyMove().
SDL_JoystickNumBalls()
DECLSPEC int SDLCALL SDL_JoystickNumBalls (SDL_Joystick * joystick)
Get the number of trackballs on a joystick.
Joystick trackballs have only relative motion events associated with them and their state cannot be polled.
Referenced by IN_InitJoystick(), and IN_JoyMove().
SDL_JoystickNumButtons()
DECLSPEC int SDLCALL SDL_JoystickNumButtons (SDL_Joystick * joystick)
Get the number of buttons on a joystick.
Referenced by IN_InitJoystick(), and IN_JoyMove().
SDL_JoystickNumHats()
DECLSPEC int SDLCALL SDL_JoystickNumHats (SDL_Joystick * joystick)
Get the number of POV hats on a joystick.
Referenced by IN_InitJoystick(), and IN_JoyMove().
SDL_JoystickOpen()
DECLSPEC SDL_Joystick* SDLCALL SDL_JoystickOpen (int device_index)
Open a joystick for use.
Parameters
[in] device_index The index passed as an argument refers to the N'th joystick on the system. This index is the value which will identify this joystick in future joystick events.
Returns
This function returns a joystick identifier, or NULL if an error occurred.
Referenced by IN_InitJoystick().
SDL_JoystickOpened()
DECLSPEC int SDLCALL SDL_JoystickOpened (int device_index)
Returns 1 if the joystick has been opened, or 0 if it has not.
SDL_JoystickUpdate()
DECLSPEC void SDLCALL SDL_JoystickUpdate (void)
Update the current state of the open joysticks.
This is called automatically by the event loop if any joystick events are enabled.
Referenced by IN_JoyMove().
SDL_NumJoysticks()
DECLSPEC int SDLCALL SDL_NumJoysticks (void)
Count the number of joysticks attached to the system.
Referenced by IN_InitJoystick().