ZEQ2-Lite: Tools/MinGW/include/wincon.h File Reference
wincon.h File Reference
Data Structures
struct _CHAR_INFO
struct _CONSOLE_CURSOR_INFO
struct _CONSOLE_FONT_INFO
struct _CONSOLE_SCREEN_BUFFER_INFO
struct _COORD
struct _FOCUS_EVENT_RECORD
struct _INPUT_RECORD
struct _KEY_EVENT_RECORD
struct _MENU_EVENT_RECORD
struct _MOUSE_EVENT_RECORD
struct _SMALL_RECT
struct _WINDOW_BUFFER_SIZE_RECORD
Macros
#define BACKGROUND_BLUE 16
#define BACKGROUND_GREEN 32
#define BACKGROUND_INTENSITY 128
#define BACKGROUND_RED 64
#define CAPSLOCK_ON 128
#define CTRL_BREAK_EVENT 1
#define CTRL_C_EVENT 0
#define CTRL_CLOSE_EVENT 2
#define CTRL_LOGOFF_EVENT 5
#define CTRL_SHUTDOWN_EVENT 6
#define DOUBLE_CLICK 2
#define ENABLE_AUTO_POSITION 256
#define ENABLE_ECHO_INPUT 4
#define ENABLE_EXTENDED_FLAGS 128
#define ENABLE_INSERT_MODE 32
#define ENABLE_LINE_INPUT 2
#define ENABLE_MOUSE_INPUT 16
#define ENABLE_PROCESSED_INPUT 1
#define ENABLE_PROCESSED_OUTPUT 1
#define ENABLE_QUICK_EDIT_MODE 64
#define ENABLE_WINDOW_INPUT 8
#define ENABLE_WRAP_AT_EOL_OUTPUT 2
#define ENHANCED_KEY 256
#define FillConsoleOutputCharacter FillConsoleOutputCharacterA
#define FOCUS_EVENT 16
#define FOREGROUND_BLUE 1
#define FOREGROUND_GREEN 2
#define FOREGROUND_INTENSITY 8
#define FOREGROUND_RED 4
#define FROM_LEFT_1ST_BUTTON_PRESSED 1
#define FROM_LEFT_2ND_BUTTON_PRESSED 4
#define FROM_LEFT_3RD_BUTTON_PRESSED 8
#define FROM_LEFT_4TH_BUTTON_PRESSED 16
#define GetConsoleTitle GetConsoleTitleA
#define KEY_EVENT 1
#define LEFT_ALT_PRESSED 2
#define LEFT_CTRL_PRESSED 8
#define MENU_EVENT 8
#define MOUSE_EVENT 2
#define MOUSE_MOVED 1
#define MOUSE_WHEELED 4
#define NUMLOCK_ON 32
#define PeekConsoleInput PeekConsoleInputA
#define ReadConsole ReadConsoleA
#define ReadConsoleInput ReadConsoleInputA
#define ReadConsoleOutput ReadConsoleOutputA
#define ReadConsoleOutputCharacter ReadConsoleOutputCharacterA
#define RIGHT_ALT_PRESSED 1
#define RIGHT_CTRL_PRESSED 4
#define RIGHTMOST_BUTTON_PRESSED 2
#define ScrollConsoleScreenBuffer ScrollConsoleScreenBufferA
#define SCROLLLOCK_ON 64
#define SetConsoleTitle SetConsoleTitleA
#define SHIFT_PRESSED 16
#define WINDOW_BUFFER_SIZE_EVENT 4
#define WriteConsole WriteConsoleA
#define WriteConsoleInput WriteConsoleInputA
#define WriteConsoleOutput WriteConsoleOutputA
#define WriteConsoleOutputCharacter WriteConsoleOutputCharacterA
Typedefs
typedef struct CHAR_INFO * PCHAR_INFO
typedef struct CONSOLE_CURSOR_INFO * PCONSOLE_CURSOR_INFO
typedef struct CONSOLE_FONT_INFO * PCONSOLE_FONT_INFO
typedef struct CONSOLE_SCREEN_BUFFER_INFO * PCONSOLE_SCREEN_BUFFER_INFO
typedef struct COORD * PCOORD
typedef BOOL(CALLBACK * PHANDLER_ROUTINE) (DWORD)
typedef struct INPUT_RECORD * PINPUT_RECORD
typedef struct MENU_EVENT_RECORD * PMENU_EVENT_RECORD
typedef struct SMALL_RECT * PSMALL_RECT
Functions
BOOL WINAPI AllocConsole (void)
HANDLE WINAPI CreateConsoleScreenBuffer (DWORD, DWORD, CONST SECURITY_ATTRIBUTES *, DWORD, LPVOID)
BOOL WINAPI FillConsoleOutputAttribute (HANDLE, WORD, DWORD, COORD, PDWORD)
BOOL WINAPI FillConsoleOutputCharacterA (HANDLE, CHAR, DWORD, COORD, PDWORD)
BOOL WINAPI FillConsoleOutputCharacterW (HANDLE, WCHAR, DWORD, COORD, PDWORD)
BOOL WINAPI FlushConsoleInputBuffer (HANDLE)
BOOL WINAPI FreeConsole (void)
BOOL WINAPI GenerateConsoleCtrlEvent (DWORD, DWORD)
UINT WINAPI GetConsoleCP (void)
BOOL WINAPI GetConsoleCursorInfo (HANDLE, PCONSOLE_CURSOR_INFO)
BOOL WINAPI GetConsoleMode (HANDLE, PDWORD)
UINT WINAPI GetConsoleOutputCP (void)
BOOL WINAPI GetConsoleScreenBufferInfo (HANDLE, PCONSOLE_SCREEN_BUFFER_INFO)
DWORD WINAPI GetConsoleTitleA (LPSTR, DWORD)
DWORD WINAPI GetConsoleTitleW (LPWSTR, DWORD)
COORD WINAPI GetLargestConsoleWindowSize (HANDLE)
BOOL WINAPI GetNumberOfConsoleInputEvents (HANDLE, PDWORD)
BOOL WINAPI GetNumberOfConsoleMouseButtons (PDWORD)
BOOL WINAPI PeekConsoleInputA (HANDLE, PINPUT_RECORD, DWORD, PDWORD)
BOOL WINAPI PeekConsoleInputW (HANDLE, PINPUT_RECORD, DWORD, PDWORD)
BOOL WINAPI ReadConsoleA (HANDLE, PVOID, DWORD, PDWORD, PVOID)
BOOL WINAPI ReadConsoleInputA (HANDLE, PINPUT_RECORD, DWORD, PDWORD)
BOOL WINAPI ReadConsoleInputW (HANDLE, PINPUT_RECORD, DWORD, PDWORD)
BOOL WINAPI ReadConsoleOutputA (HANDLE, PCHAR_INFO, COORD, COORD, PSMALL_RECT)
BOOL WINAPI ReadConsoleOutputAttribute (HANDLE, LPWORD, DWORD, COORD, LPDWORD)
BOOL WINAPI ReadConsoleOutputCharacterA (HANDLE, LPSTR, DWORD, COORD, PDWORD)
BOOL WINAPI ReadConsoleOutputCharacterW (HANDLE, LPWSTR, DWORD, COORD, PDWORD)
BOOL WINAPI ReadConsoleOutputW (HANDLE, PCHAR_INFO, COORD, COORD, PSMALL_RECT)
BOOL WINAPI ReadConsoleW (HANDLE, PVOID, DWORD, PDWORD, PVOID)
BOOL WINAPI ScrollConsoleScreenBufferA (HANDLE, const SMALL_RECT *, const SMALL_RECT *, COORD, const CHAR_INFO *)
BOOL WINAPI ScrollConsoleScreenBufferW (HANDLE, const SMALL_RECT *, const SMALL_RECT *, COORD, const CHAR_INFO *)
BOOL WINAPI SetConsoleActiveScreenBuffer (HANDLE)
BOOL WINAPI SetConsoleCP (UINT)
BOOL WINAPI SetConsoleCtrlHandler (PHANDLER_ROUTINE, BOOL)
BOOL WINAPI SetConsoleCursorInfo (HANDLE, const CONSOLE_CURSOR_INFO *)
BOOL WINAPI SetConsoleCursorPosition (HANDLE, COORD)
BOOL WINAPI SetConsoleMode (HANDLE, DWORD)
BOOL WINAPI SetConsoleOutputCP (UINT)
BOOL WINAPI SetConsoleScreenBufferSize (HANDLE, COORD)
BOOL WINAPI SetConsoleTextAttribute (HANDLE, WORD)
BOOL WINAPI SetConsoleTitleA (LPCSTR)
BOOL WINAPI SetConsoleTitleW (LPCWSTR)
BOOL WINAPI SetConsoleWindowInfo (HANDLE, BOOL, const SMALL_RECT *)
BOOL WINAPI WriteConsoleA (HANDLE, PCVOID, DWORD, PDWORD, PVOID)
BOOL WINAPI WriteConsoleInputA (HANDLE, const INPUT_RECORD *, DWORD, PDWORD)
BOOL WINAPI WriteConsoleInputW (HANDLE, const INPUT_RECORD *, DWORD, PDWORD)
BOOL WINAPI WriteConsoleOutputA (HANDLE, const CHAR_INFO *, COORD, COORD, PSMALL_RECT)
BOOL WINAPI WriteConsoleOutputAttribute (HANDLE, const WORD *, DWORD, COORD, PDWORD)
BOOL WINAPI WriteConsoleOutputCharacterA (HANDLE, LPCSTR, DWORD, COORD, PDWORD)
BOOL WINAPI WriteConsoleOutputCharacterW (HANDLE, LPCWSTR, DWORD, COORD, PDWORD)
BOOL WINAPI WriteConsoleOutputW (HANDLE, const CHAR_INFO *, COORD, COORD, PSMALL_RECT)
BOOL WINAPI WriteConsoleW (HANDLE, PCVOID, DWORD, PDWORD, PVOID)
Macro Definition Documentation
BACKGROUND_BLUE
#define BACKGROUND_BLUE 16
Definition at line 15 of file wincon.h.
BACKGROUND_GREEN
#define BACKGROUND_GREEN 32
Definition at line 16 of file wincon.h.
BACKGROUND_INTENSITY
#define BACKGROUND_INTENSITY 128
Definition at line 18 of file wincon.h.
BACKGROUND_RED
#define BACKGROUND_RED 64
Definition at line 17 of file wincon.h.
CAPSLOCK_ON
#define CAPSLOCK_ON 128
Definition at line 44 of file wincon.h.
CTRL_BREAK_EVENT
#define CTRL_BREAK_EVENT 1
Definition at line 24 of file wincon.h.
CTRL_C_EVENT
#define CTRL_C_EVENT 0
Definition at line 23 of file wincon.h.
CTRL_CLOSE_EVENT
#define CTRL_CLOSE_EVENT 2
Definition at line 25 of file wincon.h.
CTRL_LOGOFF_EVENT
#define CTRL_LOGOFF_EVENT 5
Definition at line 26 of file wincon.h.
CTRL_SHUTDOWN_EVENT
#define CTRL_SHUTDOWN_EVENT 6
Definition at line 27 of file wincon.h.
DOUBLE_CLICK
#define DOUBLE_CLICK 2
Definition at line 59 of file wincon.h.
ENABLE_AUTO_POSITION
#define ENABLE_AUTO_POSITION 256
Definition at line 36 of file wincon.h.
ENABLE_ECHO_INPUT
#define ENABLE_ECHO_INPUT 4
Definition at line 29 of file wincon.h.
ENABLE_EXTENDED_FLAGS
#define ENABLE_EXTENDED_FLAGS 128
Definition at line 35 of file wincon.h.
ENABLE_INSERT_MODE
#define ENABLE_INSERT_MODE 32
Definition at line 33 of file wincon.h.
ENABLE_LINE_INPUT
#define ENABLE_LINE_INPUT 2
Definition at line 28 of file wincon.h.
ENABLE_MOUSE_INPUT
#define ENABLE_MOUSE_INPUT 16
Definition at line 32 of file wincon.h.
ENABLE_PROCESSED_INPUT
#define ENABLE_PROCESSED_INPUT 1
Definition at line 30 of file wincon.h.
ENABLE_PROCESSED_OUTPUT
#define ENABLE_PROCESSED_OUTPUT 1
Definition at line 37 of file wincon.h.
ENABLE_QUICK_EDIT_MODE
#define ENABLE_QUICK_EDIT_MODE 64
Definition at line 34 of file wincon.h.
ENABLE_WINDOW_INPUT
#define ENABLE_WINDOW_INPUT 8
Definition at line 31 of file wincon.h.
ENABLE_WRAP_AT_EOL_OUTPUT
#define ENABLE_WRAP_AT_EOL_OUTPUT 2
Definition at line 38 of file wincon.h.
ENHANCED_KEY
#define ENHANCED_KEY 256
Definition at line 45 of file wincon.h.
FillConsoleOutputCharacter
#define FillConsoleOutputCharacter FillConsoleOutputCharacterA
Definition at line 214 of file wincon.h.
FOCUS_EVENT
#define FOCUS_EVENT 16
Definition at line 43 of file wincon.h.
FOREGROUND_BLUE
#define FOREGROUND_BLUE 1
Definition at line 11 of file wincon.h.
FOREGROUND_GREEN
#define FOREGROUND_GREEN 2
Definition at line 12 of file wincon.h.
FOREGROUND_INTENSITY
#define FOREGROUND_INTENSITY 8
Definition at line 14 of file wincon.h.
FOREGROUND_RED
#define FOREGROUND_RED 4
Definition at line 13 of file wincon.h.
FROM_LEFT_1ST_BUTTON_PRESSED
#define FROM_LEFT_1ST_BUTTON_PRESSED 1
Definition at line 53 of file wincon.h.
FROM_LEFT_2ND_BUTTON_PRESSED
#define FROM_LEFT_2ND_BUTTON_PRESSED 4
Definition at line 55 of file wincon.h.
FROM_LEFT_3RD_BUTTON_PRESSED
#define FROM_LEFT_3RD_BUTTON_PRESSED 8
Definition at line 56 of file wincon.h.
FROM_LEFT_4TH_BUTTON_PRESSED
#define FROM_LEFT_4TH_BUTTON_PRESSED 16
Definition at line 57 of file wincon.h.
GetConsoleTitle
#define GetConsoleTitle GetConsoleTitleA
Definition at line 215 of file wincon.h.
KEY_EVENT
#define KEY_EVENT 1
Definition at line 39 of file wincon.h.
LEFT_ALT_PRESSED
#define LEFT_ALT_PRESSED 2
Definition at line 47 of file wincon.h.
LEFT_CTRL_PRESSED
#define LEFT_CTRL_PRESSED 8
Definition at line 49 of file wincon.h.
MENU_EVENT
#define MENU_EVENT 8
Definition at line 42 of file wincon.h.
MOUSE_EVENT
#define MOUSE_EVENT 2
Definition at line 40 of file wincon.h.
MOUSE_MOVED
#define MOUSE_MOVED 1
Definition at line 58 of file wincon.h.
MOUSE_WHEELED
#define MOUSE_WHEELED 4
Definition at line 60 of file wincon.h.
NUMLOCK_ON
#define NUMLOCK_ON 32
Definition at line 51 of file wincon.h.
PeekConsoleInput
#define PeekConsoleInput PeekConsoleInputA
Definition at line 216 of file wincon.h.
ReadConsole
#define ReadConsole ReadConsoleA
Definition at line 217 of file wincon.h.
ReadConsoleInput
#define ReadConsoleInput ReadConsoleInputA
Definition at line 218 of file wincon.h.
ReadConsoleOutput
#define ReadConsoleOutput ReadConsoleOutputA
Definition at line 219 of file wincon.h.
ReadConsoleOutputCharacter
#define ReadConsoleOutputCharacter ReadConsoleOutputCharacterA
Definition at line 220 of file wincon.h.
RIGHT_ALT_PRESSED
#define RIGHT_ALT_PRESSED 1
Definition at line 46 of file wincon.h.
RIGHT_CTRL_PRESSED
#define RIGHT_CTRL_PRESSED 4
Definition at line 48 of file wincon.h.
RIGHTMOST_BUTTON_PRESSED
#define RIGHTMOST_BUTTON_PRESSED 2
Definition at line 54 of file wincon.h.
ScrollConsoleScreenBuffer
#define ScrollConsoleScreenBuffer ScrollConsoleScreenBufferA
Definition at line 221 of file wincon.h.
SCROLLLOCK_ON
#define SCROLLLOCK_ON 64
Definition at line 52 of file wincon.h.
SetConsoleTitle
#define SetConsoleTitle SetConsoleTitleA
Definition at line 222 of file wincon.h.
SHIFT_PRESSED
#define SHIFT_PRESSED 16
Definition at line 50 of file wincon.h.
WINDOW_BUFFER_SIZE_EVENT
#define WINDOW_BUFFER_SIZE_EVENT 4
Definition at line 41 of file wincon.h.
WriteConsole
#define WriteConsole WriteConsoleA
Definition at line 223 of file wincon.h.
WriteConsoleInput
#define WriteConsoleInput WriteConsoleInputA
Definition at line 224 of file wincon.h.
WriteConsoleOutput
#define WriteConsoleOutput WriteConsoleOutputA
Definition at line 225 of file wincon.h.
WriteConsoleOutputCharacter
#define WriteConsoleOutputCharacter WriteConsoleOutputCharacterA
Definition at line 226 of file wincon.h.
Typedef Documentation
PCHAR_INFO
typedef struct CHAR_INFO * PCHAR_INFO
PCONSOLE_CURSOR_INFO
typedef struct CONSOLE_CURSOR_INFO* PCONSOLE_CURSOR_INFO
PCONSOLE_FONT_INFO
typedef struct CONSOLE_FONT_INFO * PCONSOLE_FONT_INFO
PCONSOLE_SCREEN_BUFFER_INFO
typedef struct CONSOLE_SCREEN_BUFFER_INFO* PCONSOLE_SCREEN_BUFFER_INFO
PCOORD
typedef struct COORD * PCOORD
PHANDLER_ROUTINE
typedef BOOL(CALLBACK * PHANDLER_ROUTINE) (DWORD)
Definition at line 94 of file wincon.h.
PINPUT_RECORD
typedef struct INPUT_RECORD* PINPUT_RECORD
PMENU_EVENT_RECORD
typedef struct MENU_EVENT_RECORD* PMENU_EVENT_RECORD
PSMALL_RECT
typedef struct SMALL_RECT * PSMALL_RECT
Function Documentation
AllocConsole()
BOOL WINAPI AllocConsole (void)
CreateConsoleScreenBuffer()
HANDLE WINAPI CreateConsoleScreenBuffer (DWORD , DWORD , CONST SECURITY_ATTRIBUTES * , DWORD , LPVOID)
FillConsoleOutputAttribute()
BOOL WINAPI FillConsoleOutputAttribute (HANDLE , WORD , DWORD , COORD , PDWORD)
FillConsoleOutputCharacterA()
BOOL WINAPI FillConsoleOutputCharacterA (HANDLE , CHAR , DWORD , COORD , PDWORD)
FillConsoleOutputCharacterW()
BOOL WINAPI FillConsoleOutputCharacterW (HANDLE , WCHAR , DWORD , COORD , PDWORD)
FlushConsoleInputBuffer()
BOOL WINAPI FlushConsoleInputBuffer (HANDLE)
Referenced by CON_Init(), and CON_Input().
FreeConsole()
BOOL WINAPI FreeConsole (void)
GenerateConsoleCtrlEvent()
BOOL WINAPI GenerateConsoleCtrlEvent (DWORD , DWORD)
GetConsoleCP()
UINT WINAPI GetConsoleCP (void)
GetConsoleCursorInfo()
BOOL WINAPI GetConsoleCursorInfo (HANDLE , PCONSOLE_CURSOR_INFO)
Referenced by CON_Init().
GetConsoleMode()
BOOL WINAPI GetConsoleMode (HANDLE , PDWORD)
Referenced by CON_Init().
GetConsoleOutputCP()
UINT WINAPI GetConsoleOutputCP (void)
GetConsoleScreenBufferInfo()
BOOL WINAPI GetConsoleScreenBufferInfo (HANDLE , PCONSOLE_SCREEN_BUFFER_INFO)
Referenced by CON_Init(), and CON_Show().
GetConsoleTitleA()
DWORD WINAPI GetConsoleTitleA (LPSTR , DWORD)
GetConsoleTitleW()
DWORD WINAPI GetConsoleTitleW (LPWSTR , DWORD)
GetLargestConsoleWindowSize()
COORD WINAPI GetLargestConsoleWindowSize (HANDLE)
GetNumberOfConsoleInputEvents()
BOOL WINAPI GetNumberOfConsoleInputEvents (HANDLE , PDWORD)
Referenced by CON_Input().
GetNumberOfConsoleMouseButtons()
BOOL WINAPI GetNumberOfConsoleMouseButtons (PDWORD)
PeekConsoleInputA()
BOOL WINAPI PeekConsoleInputA (HANDLE , PINPUT_RECORD , DWORD , PDWORD)
PeekConsoleInputW()
BOOL WINAPI PeekConsoleInputW (HANDLE , PINPUT_RECORD , DWORD , PDWORD)
ReadConsoleA()
BOOL WINAPI ReadConsoleA (HANDLE , PVOID , DWORD , PDWORD , PVOID)
ReadConsoleInputA()
BOOL WINAPI ReadConsoleInputA (HANDLE , PINPUT_RECORD , DWORD , PDWORD)
ReadConsoleInputW()
BOOL WINAPI ReadConsoleInputW (HANDLE , PINPUT_RECORD , DWORD , PDWORD)
ReadConsoleOutputA()
BOOL WINAPI ReadConsoleOutputA (HANDLE , PCHAR_INFO , COORD , COORD , PSMALL_RECT)
ReadConsoleOutputAttribute()
BOOL WINAPI ReadConsoleOutputAttribute (HANDLE , LPWORD , DWORD , COORD , LPDWORD)
ReadConsoleOutputCharacterA()
BOOL WINAPI ReadConsoleOutputCharacterA (HANDLE , LPSTR , DWORD , COORD , PDWORD)
ReadConsoleOutputCharacterW()
BOOL WINAPI ReadConsoleOutputCharacterW (HANDLE , LPWSTR , DWORD , COORD , PDWORD)
ReadConsoleOutputW()
BOOL WINAPI ReadConsoleOutputW (HANDLE , PCHAR_INFO , COORD , COORD , PSMALL_RECT)
ReadConsoleW()
BOOL WINAPI ReadConsoleW (HANDLE , PVOID , DWORD , PDWORD , PVOID)
ScrollConsoleScreenBufferA()
BOOL WINAPI ScrollConsoleScreenBufferA (HANDLE , const SMALL_RECT * , const SMALL_RECT * , COORD , const CHAR_INFO *)
ScrollConsoleScreenBufferW()
BOOL WINAPI ScrollConsoleScreenBufferW (HANDLE , const SMALL_RECT * , const SMALL_RECT * , COORD , const CHAR_INFO *)
SetConsoleActiveScreenBuffer()
BOOL WINAPI SetConsoleActiveScreenBuffer (HANDLE)
SetConsoleCP()
BOOL WINAPI SetConsoleCP (UINT)
SetConsoleCtrlHandler()
BOOL WINAPI SetConsoleCtrlHandler (PHANDLER_ROUTINE , BOOL)
Referenced by CON_Init().
SetConsoleCursorInfo()
BOOL WINAPI SetConsoleCursorInfo (HANDLE , const CONSOLE_CURSOR_INFO *)
Referenced by CON_Init(), and CON_Shutdown().
SetConsoleCursorPosition()
BOOL WINAPI SetConsoleCursorPosition (HANDLE , COORD)
SetConsoleMode()
BOOL WINAPI SetConsoleMode (HANDLE , DWORD)
Referenced by CON_Init(), and CON_Shutdown().
SetConsoleOutputCP()
BOOL WINAPI SetConsoleOutputCP (UINT)
SetConsoleScreenBufferSize()
BOOL WINAPI SetConsoleScreenBufferSize (HANDLE , COORD)
SetConsoleTextAttribute()
BOOL WINAPI SetConsoleTextAttribute (HANDLE , WORD)
SetConsoleTitleA()
BOOL WINAPI SetConsoleTitleA (LPCSTR)
SetConsoleTitleW()
BOOL WINAPI SetConsoleTitleW (LPCWSTR)
SetConsoleWindowInfo()
BOOL WINAPI SetConsoleWindowInfo (HANDLE , BOOL , const SMALL_RECT *)
WriteConsoleA()
BOOL WINAPI WriteConsoleA (HANDLE , PCVOID , DWORD , PDWORD , PVOID)
WriteConsoleInputA()
BOOL WINAPI WriteConsoleInputA (HANDLE , const INPUT_RECORD * , DWORD , PDWORD)
WriteConsoleInputW()
BOOL WINAPI WriteConsoleInputW (HANDLE , const INPUT_RECORD * , DWORD , PDWORD)
WriteConsoleOutputA()
BOOL WINAPI WriteConsoleOutputA (HANDLE , const CHAR_INFO * , COORD , COORD , PSMALL_RECT)
WriteConsoleOutputAttribute()
BOOL WINAPI WriteConsoleOutputAttribute (HANDLE , const WORD * , DWORD , COORD , PDWORD)
WriteConsoleOutputCharacterA()
BOOL WINAPI WriteConsoleOutputCharacterA (HANDLE , LPCSTR , DWORD , COORD , PDWORD)
WriteConsoleOutputCharacterW()
BOOL WINAPI WriteConsoleOutputCharacterW (HANDLE , LPCWSTR , DWORD , COORD , PDWORD)
WriteConsoleOutputW()
BOOL WINAPI WriteConsoleOutputW (HANDLE , const CHAR_INFO * , COORD , COORD , PSMALL_RECT)
WriteConsoleW()
BOOL WINAPI WriteConsoleW (HANDLE , PCVOID , DWORD , PDWORD , PVOID)