ZEQ2-Lite: Tools/MinGW/include/sys/stat.h File Reference
stat.h File Reference
#include <_mingw.h>
#include <stddef.h>
#include <sys/types.h>
Data Structures
struct _stat
struct stat
Macros
#define __need_size_t
#define __need_wchar_t
#define _S_IEXEC 0x0040
#define _S_IFBLK 0x3000 /* Block: Is this ever set under w32? */
#define _S_IFCHR 0x2000 /* Character */
#define _S_IFDIR 0x4000 /* Directory */
#define _S_IFIFO 0x1000 /* FIFO */
#define _S_IFMT 0xF000 /* File type mask */
#define _S_IFREG 0x8000 /* Regular */
#define _S_IREAD 0x0100
#define _S_IRUSR _S_IREAD
#define _S_IRWXU (_S_IREAD | _S_IWRITE | _S_IEXEC)
#define _S_ISBLK(m) (((m) & _S_IFMT) == _S_IFBLK)
#define _S_ISCHR(m) (((m) & _S_IFMT) == _S_IFCHR)
#define _S_ISDIR(m) (((m) & _S_IFMT) == _S_IFDIR)
#define _S_ISFIFO(m) (((m) & _S_IFMT) == _S_IFIFO)
#define _S_ISREG(m) (((m) & _S_IFMT) == _S_IFREG)
#define _S_IWRITE 0x0080
#define _S_IWUSR _S_IWRITE
#define _S_IXUSR _S_IEXEC
#define _STAT_DEFINED
#define S_IEXEC _S_IEXEC
#define S_IFBLK _S_IFBLK
#define S_IFCHR _S_IFCHR
#define S_IFDIR _S_IFDIR
#define S_IFIFO _S_IFIFO
#define S_IFMT _S_IFMT
#define S_IFREG _S_IFREG
#define S_IREAD _S_IREAD
#define S_IRUSR _S_IRUSR
#define S_IRWXU _S_IRWXU
#define S_ISBLK(m) (((m) & S_IFMT) == S_IFBLK)
#define S_ISCHR(m) (((m) & S_IFMT) == S_IFCHR)
#define S_ISDIR(m) (((m) & S_IFMT) == S_IFDIR)
#define S_ISFIFO(m) (((m) & S_IFMT) == S_IFIFO)
#define S_ISREG(m) (((m) & S_IFMT) == S_IFREG)
#define S_IWRITE _S_IWRITE
#define S_IWUSR _S_IWUSR
#define S_IXUSR _S_IXUSR
Functions
_CRTIMP int __cdecl __MINGW_NOTHROW _chmod (const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _fstat (int, struct _stat *)
_CRTIMP int __cdecl __MINGW_NOTHROW _stat (const char *, struct _stat *)
_CRTIMP int __cdecl __MINGW_NOTHROW chmod (const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW fstat (int, struct stat *)
_CRTIMP int __cdecl __MINGW_NOTHROW stat (const char *, struct stat *)
Macro Definition Documentation
__need_size_t
#define __need_size_t
Definition at line 18 of file stat.h.
__need_wchar_t
#define __need_wchar_t
Definition at line 19 of file stat.h.
_S_IEXEC
#define _S_IEXEC 0x0040
Definition at line 37 of file stat.h.
_S_IFBLK
#define _S_IFBLK 0x3000 /* Block: Is this ever set under w32? */
Definition at line 31 of file stat.h.
_S_IFCHR
#define _S_IFCHR 0x2000 /* Character */
Definition at line 30 of file stat.h.
_S_IFDIR
#define _S_IFDIR 0x4000 /* Directory */
Definition at line 32 of file stat.h.
_S_IFIFO
#define _S_IFIFO 0x1000 /* FIFO */
Definition at line 29 of file stat.h.
_S_IFMT
#define _S_IFMT 0xF000 /* File type mask */
Definition at line 35 of file stat.h.
_S_IFREG
#define _S_IFREG 0x8000 /* Regular */
Definition at line 33 of file stat.h.
_S_IREAD
#define _S_IREAD 0x0100
Definition at line 39 of file stat.h.
_S_IRUSR
#define _S_IRUSR _S_IREAD
Definition at line 44 of file stat.h.
_S_IRWXU
#define _S_IRWXU (_S_IREAD | _S_IWRITE | _S_IEXEC)
Definition at line 41 of file stat.h.
_S_ISBLK
#define _S_ISBLK (m) (((m) & _S_IFMT) == _S_IFBLK)
Definition at line 49 of file stat.h.
_S_ISCHR
#define _S_ISCHR (m) (((m) & _S_IFMT) == _S_IFCHR)
Definition at line 48 of file stat.h.
_S_ISDIR
#define _S_ISDIR (m) (((m) & _S_IFMT) == _S_IFDIR)
Definition at line 46 of file stat.h.
_S_ISFIFO
#define _S_ISFIFO (m) (((m) & _S_IFMT) == _S_IFIFO)
Definition at line 47 of file stat.h.
_S_ISREG
#define _S_ISREG (m) (((m) & _S_IFMT) == _S_IFREG)
Definition at line 50 of file stat.h.
_S_IWRITE
#define _S_IWRITE 0x0080
Definition at line 38 of file stat.h.
_S_IWUSR
#define _S_IWUSR _S_IWRITE
Definition at line 43 of file stat.h.
_S_IXUSR
#define _S_IXUSR _S_IEXEC
Definition at line 42 of file stat.h.
_STAT_DEFINED
#define _STAT_DEFINED
Definition at line 194 of file stat.h.
S_IEXEC
#define S_IEXEC _S_IEXEC
Definition at line 60 of file stat.h.
S_IFBLK
#define S_IFBLK _S_IFBLK
Definition at line 56 of file stat.h.
S_IFCHR
#define S_IFCHR _S_IFCHR
Definition at line 55 of file stat.h.
S_IFDIR
#define S_IFDIR _S_IFDIR
Definition at line 57 of file stat.h.
S_IFIFO
#define S_IFIFO _S_IFIFO
Definition at line 54 of file stat.h.
S_IFMT
#define S_IFMT _S_IFMT
Definition at line 59 of file stat.h.
S_IFREG
#define S_IFREG _S_IFREG
Definition at line 58 of file stat.h.
S_IREAD
#define S_IREAD _S_IREAD
Definition at line 62 of file stat.h.
S_IRUSR
#define S_IRUSR _S_IRUSR
Definition at line 66 of file stat.h.
S_IRWXU
#define S_IRWXU _S_IRWXU
Definition at line 63 of file stat.h.
S_ISBLK
#define S_ISBLK (m) (((m) & S_IFMT) == S_IFBLK)
Definition at line 71 of file stat.h.
S_ISCHR
#define S_ISCHR (m) (((m) & S_IFMT) == S_IFCHR)
Definition at line 70 of file stat.h.
S_ISDIR
#define S_ISDIR (m) (((m) & S_IFMT) == S_IFDIR)
Definition at line 68 of file stat.h.
S_ISFIFO
#define S_ISFIFO (m) (((m) & S_IFMT) == S_IFIFO)
Definition at line 69 of file stat.h.
S_ISREG
#define S_ISREG (m) (((m) & S_IFMT) == S_IFREG)
Definition at line 72 of file stat.h.
S_IWRITE
#define S_IWRITE _S_IWRITE
Definition at line 61 of file stat.h.
S_IWUSR
#define S_IWUSR _S_IWUSR
Definition at line 65 of file stat.h.
S_IXUSR
#define S_IXUSR _S_IXUSR
Definition at line 64 of file stat.h.
Function Documentation
_chmod()
_CRTIMP int __cdecl __MINGW_NOTHROW _chmod (const char * , int)
_fstat()
_CRTIMP int __cdecl __MINGW_NOTHROW _fstat (int , struct _stat *)
_stat()
_CRTIMP int __cdecl __MINGW_NOTHROW _stat (const char * , struct _stat *)
chmod()
_CRTIMP int __cdecl __MINGW_NOTHROW chmod (const char * , int)
fstat()
_CRTIMP int __cdecl __MINGW_NOTHROW fstat (int , struct stat *)
stat()
_CRTIMP int __cdecl __MINGW_NOTHROW stat (const char * , struct stat *)
Referenced by PM_UsePowerLevel(), Sys_ListFiles(), Sys_ListFilteredFiles(), Sys_LowPhysicalMemory(), and Sys_Mkfifo().