ZEQ2-Lite: __gnu_profile::__trace_container_size Class Reference
__gnu_profile::__trace_container_size Class Reference
Container size instrumentation trace producer.
#include <profiler_container_size.h>
Public Member Functions
__trace_container_size ()
~__trace_container_size ()
void __add_object (__object_t object, __container_size_info __info)
void __collect_warnings (__warning_vector_t &__warnings)
void __construct (const void *__obj, std::size_t __inum)
void __destruct (const void *__obj, std::size_t __num, std::size_t __inum)
__container_size_info * __get_object_info (__object_t __object)
void __insert (const __object_t __obj, __stack_t __stack, std::size_t __num)
void __resize (const void *__obj, int __from, int __to)
void __retire_object (__object_t __object)
void __write (FILE *__f)
Protected Attributes
const char * __id
Private Types
typedef _GLIBCXX_IMPL_UNORDERED_MAP< __object_t, __container_size_info > __object_table_t
typedef _GLIBCXX_IMPL_UNORDERED_MAP< __stack_t, __container_size_stack_info, __stack_hash, __stack_hash > __stack_table_t
Private Attributes
__object_table_t __object_table
__gnu_cxx::__mutex __object_table_lock
__stack_table_t __stack_table
std::size_t __stack_table_byte_size
__gnu_cxx::__mutex __stack_table_lock
Detailed Description
Container size instrumentation trace producer.
Definition at line 171 of file profiler_container_size.h.
Member Typedef Documentation
__object_table_t
typedef _GLIBCXX_IMPL_UNORDERED_MAP<__object_t, __container_size_info > __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__object_table_t private inherited
Definition at line 211 of file profiler_trace.h.
__stack_table_t
typedef _GLIBCXX_IMPL_UNORDERED_MAP<__stack_t, __container_size_stack_info , __stack_hash, __stack_hash> __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__stack_table_t private inherited
Definition at line 214 of file profiler_trace.h.
Constructor & Destructor Documentation
~__trace_container_size()
__gnu_profile::__trace_container_size::~__trace_container_size () inline
Definition at line 175 of file profiler_container_size.h.
 { }
__trace_container_size()
__gnu_profile::__trace_container_size::__trace_container_size () inline
Definition at line 177 of file profiler_container_size.h.
     : __trace_base<__container_size_info, __container_size_stack_info>() { };
Member Function Documentation
__add_object()
void __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__add_object (__object_t object, __container_size_info __info) inherited
Definition at line 238 of file profiler_trace.h.
     {
       if (__max_mem() == 0
       || __object_table.size() * sizeof(__object_info) <= __max_mem())
     {
       this->__object_table_lock.lock();
       __object_table.insert(typename __object_table_t::
                 value_type(__object, __info));
       this->__object_table_lock.unlock();
     }
     }
__collect_warnings()
void __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__collect_warnings (__warning_vector_t & __warnings) inherited
Definition at line 226 of file profiler_trace.h.
     {
       for (typename __stack_table_t::iterator __it
          = __stack_table.begin(); __it != __stack_table.end(); ++__it)
     __warnings.push_back(__warning_data((*__it).second.__magnitude(),
                         (*__it).first, __id,
                         (*__it).second.__advice()));
     }
__construct()
void __gnu_profile::__trace_container_size::__construct (const void * __obj, std::size_t __inum)
__destruct()
void __gnu_profile::__trace_container_size::__destruct (const void * __obj, std::size_t __num, std::size_t __inum) inline
Definition at line 191 of file profiler_container_size.h.
     {
       if (!__is_on())
     return;
       __object_t __obj_handle = static_cast<__object_t>(__obj);
       __container_size_info* __object_info = __get_object_info(__obj_handle);
       if (!__object_info)
     return;
       __object_info->__destruct(__num, __inum);
       __retire_object(__obj_handle);
     }
References __gnu_profile::__container_size_info::__destruct(), __gnu_profile::__trace_base< __container_size_info, __container_size_stack_info >::__get_object_info(), __gnu_profile::__is_on(), __gnu_profile::__object_t, and __gnu_profile::__trace_base< __container_size_info, __container_size_stack_info >::__retire_object().
__get_object_info()
__container_size_info * __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__get_object_info (__object_t __object) inherited
Definition at line 253 of file profiler_trace.h.
     {
       // XXX: Revisit this to see if we can decrease mutex spans.
       // Without this mutex, the object table could be rehashed during an
       // insertion on another thread, which could result in a segfault.
       this->__object_table_lock.lock();
       typename __object_table_t::iterator __object_it
     =  __object_table.find(__object);
       if (__object_it == __object_table.end())
     {
       this->__object_table_lock.unlock();
       return 0;
     }
       else
     {
       this->__object_table_lock.unlock();
       return &__object_it->second;
     }
     }
__insert()
void __gnu_profile::__trace_container_size::__insert (const __object_t __obj, __stack_t __stack, std::size_t __num) inline
Definition at line 182 of file profiler_container_size.h.
     { __add_object(__obj, __container_size_info(__stack, __num)); }
References __gnu_profile::__trace_base< __container_size_info, __container_size_stack_info >::__add_object().
__resize()
void __gnu_profile::__trace_container_size::__resize (const void * __obj, int __from, int __to) inline
Definition at line 208 of file profiler_container_size.h.
     {
       if (!__is_on())
     return;
       __container_size_info* __object_info = __get_object_info(__obj);
       if (!__object_info)
     return;
       __object_info->__resize(__from, __to);
     }
References __gnu_profile::__trace_base< __container_size_info, __container_size_stack_info >::__get_object_info(), __gnu_profile::__is_on(), and __gnu_profile::__container_size_info::__resize().
__retire_object()
void __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__retire_object (__object_t __object) inherited
Definition at line 277 of file profiler_trace.h.
     {
       this->__object_table_lock.lock();
       this->__stack_table_lock.lock();
       typename __object_table_t::iterator __object_it
     = __object_table.find(__object);
       if (__object_it != __object_table.end())
     {
       const __object_info& __info = __object_it->second;
       const __stack_t& __stack = __info.__stack();
       typename __stack_table_t::iterator __stack_it
         = __stack_table.find(__stack);
       if (__stack_it == __stack_table.end())
         {
           // First occurence of this call context.
           if (__max_mem() == 0 || __stack_table_byte_size < __max_mem())
         {
           __stack_table_byte_size
             += (sizeof(__instruction_address_t) * __size(__stack)
             + sizeof(__stack) + sizeof(__stack_info));
           __stack_table.insert(make_pair(__stack,
                          __stack_info(__info)));
         }
         }
       else
         {
           // Merge object info into info summary for this call context.
           __stack_it->second.__merge(__info);
           delete __stack;
         }
       __object_table.erase(__object);
     }
       this->__object_table_lock.unlock();
       this->__stack_table_lock.unlock();
     }
__write()
void __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__write (FILE * __f) inherited
Definition at line 319 of file profiler_trace.h.
     {
       for (typename __stack_table_t::iterator __it
          = __stack_table.begin(); __it != __stack_table.end(); ++__it)
     if (__it->second.__is_valid())
       {
         std::fprintf(__f, __id);
         std::fprintf(__f, "|");
         __gnu_profile::__write(__f, __it->first);
         std::fprintf(__f, "|");
         __it->second.__write(__f);
       }
     }
Field Documentation
__id
const char* __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__id protected inherited
Definition at line 220 of file profiler_trace.h.
__object_table
__object_table_t __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__object_table private inherited
Definition at line 215 of file profiler_trace.h.
__object_table_lock
__gnu_cxx::__mutex __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__object_table_lock private inherited
Definition at line 208 of file profiler_trace.h.
__stack_table
__stack_table_t __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__stack_table private inherited
Definition at line 216 of file profiler_trace.h.
__stack_table_byte_size
std::size_t __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__stack_table_byte_size private inherited
Definition at line 217 of file profiler_trace.h.
__stack_table_lock
__gnu_cxx::__mutex __gnu_profile::__trace_base< __container_size_info , __container_size_stack_info >::__stack_table_lock private inherited
Definition at line 209 of file profiler_trace.h.
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/profile/impl/profiler_container_size.h