ZEQ2-Lite: Source/Game/CGame/cg_consolecmds.c File Reference
cg_consolecmds.c File Reference
#include "cg_local.h"
#include "../UI/ui_shared.h"
Data Structures
struct consoleCommand_t
Functions
qboolean CG_ConsoleCommand (void)
static void CG_Draw2D_f (void)
void CG_InitConsoleCommands (void)
static void CG_ScoresDown_f (void)
static void CG_ScoresUp_f (void)
static void CG_SizeDown_f (void)
static void CG_SizeUp_f (void)
static void CG_StartOrbit_f (void)
void CG_TargetCommand_f (void)
static void CG_TellAttacker_f (void)
static void CG_TellTarget_f (void)
static void CG_Viewpos_f (void)
static void CG_VoiceTellAttacker_f (void)
static void CG_VoiceTellTarget_f (void)
Variables
static consoleCommand_t commands []
Function Documentation
CG_ConsoleCommand()
qboolean CG_ConsoleCommand (void)
Definition at line 274 of file cg_consolecmds.c.
{
     const char  *cmd;
     int     i;
     cmd = CG_Argv(0);
     for ( i = 0 ; i < ARRAY_LEN( commands ) ; i++ ) {
         if ( !Q_stricmp( cmd, commands[i].cmd ) ) {
             commands[i].function();
             return qtrue;
         }
     }
     return qfalse;
 }
References ARRAY_LEN, CG_Argv(), commands, consoleCommand_t::function, Q_stricmp(), qfalse, and qtrue.
Referenced by vmMain().
CG_Draw2D_f()
static void CG_Draw2D_f (void) static
Definition at line 175 of file cg_consolecmds.c.
{
     char shaderName[256];
     overlay2D *current;
     int index;
     if(trap_Argc()<2){
         CG_Printf("^3Usage : ^7draw2D <^5shaderName^7> <^5x^7> <^5y^7> <^5width^7> <^5height^7> <^5duration^7>\n");
         return;
     }
     Q_strncpyz(shaderName,CG_Argv(1),256);
     for(index=0;index<16;++index){
         if(!cg.scripted2D[index].active){break;}
         if(index == 15){
             CG_Printf("^3Warning : ^7Cannot add overlay.  Maximum overlay surfaces of [^3%i^7] active.\n",16);
             return;
         }
     }
     current = &cg.scripted2D[index];
     current->shader = trap_R_RegisterShader(shaderName);
     if(!current->shader){
         CG_Printf("^1Error : ^7Shader by the name [^1%s^7] could not be found.\n",shaderName);
         return;
     }
     current->active = qtrue;
     current->x = atoi(CG_Argv(2));
     current->y = atoi(CG_Argv(3));
     current->width = atoi(CG_Argv(4)) ? atoi(CG_Argv(4)) : 640;
     current->height = atoi(CG_Argv(5)) ? atoi(CG_Argv(5)) : 480;
     current->endTime = atoi(CG_Argv(6)) ? atoi(CG_Argv(6)) : -1;
     if(current->endTime != -1){
         current->endTime += cg.time;
     }
 }
References overlay2D::active, cg, CG_Argv(), CG_Printf(), current, Q_strncpyz(), qtrue, cg_t::scripted2D, cg_t::time, trap_Argc(), and trap_R_RegisterShader().
CG_InitConsoleCommands()
void CG_InitConsoleCommands (void)
Definition at line 299 of file cg_consolecmds.c.
{
     int     i;
     for ( i = 0 ; i < ARRAY_LEN( commands ) ; i++ ) {
         trap_AddCommand( commands[i].cmd );
     }
     //
     // the game server will interpret these commands, which will be automatically
     // forwarded to the server after they are not recognized locally
     //
     trap_AddCommand ("say");
     trap_AddCommand ("say_team");
     trap_AddCommand ("tell");
     trap_AddCommand ("vsay");
     trap_AddCommand ("vsay_team");
     trap_AddCommand ("vtell");
     trap_AddCommand ("vtaunt");
     trap_AddCommand ("vosay");
     trap_AddCommand ("vosay_team");
     trap_AddCommand ("votell");
     trap_AddCommand ("team");
     trap_AddCommand ("follow");
     trap_AddCommand ("levelshot");
     trap_AddCommand ("setviewpos");
     trap_AddCommand ("callvote");
     trap_AddCommand ("vote");
     trap_AddCommand ("callteamvote");
     trap_AddCommand ("teamvote");
     trap_AddCommand ("stats");
     trap_AddCommand ("teamtask");
     trap_AddCommand ("loaddefered");    // spelled wrong, but not changing for demo
 }
References ARRAY_LEN, commands, and trap_AddCommand().
Referenced by CG_Init().
CG_ScoresDown_f()
static void CG_ScoresDown_f (void) static
Definition at line 82 of file cg_consolecmds.c.
{
     if ( cg.scoresRequestTime + 2000 < cg.time ) {
         // the scores are more than two seconds out of data,
         // so request new ones
         cg.scoresRequestTime = cg.time;
         trap_SendClientCommand( "score" );
         // leave the current scores up if they were already
         // displayed, but if this is the first hit, clear them out
         if ( !cg.showScores ) {
             cg.showScores = qtrue;
             cg.numScores = 0;
         }
     } else {
         // show the cached contents even if they just pressed if it
         // is within two seconds
         cg.showScores = qtrue;
     }
 }
References cg, cg_t::numScores, qtrue, cg_t::scoresRequestTime, cg_t::showScores, cg_t::time, and trap_SendClientCommand().
CG_ScoresUp_f()
static void CG_ScoresUp_f (void) static
Definition at line 102 of file cg_consolecmds.c.
{
     if ( cg.showScores ) {
         cg.showScores = qfalse;
         cg.scoreFadeTime = cg.time;
     }
 }
References cg, qfalse, cg_t::scoreFadeTime, cg_t::showScores, and cg_t::time.
CG_SizeDown_f()
static void CG_SizeDown_f (void) static
Definition at line 63 of file cg_consolecmds.c.
{
     trap_Cvar_Set("cg_viewsize", va("%i",(int)(cg_viewsize.integer-10)));
 }
References cg_viewsize, vmCvar_t::integer, trap_Cvar_Set(), and va().
CG_SizeUp_f()
static void CG_SizeUp_f (void) static
Definition at line 51 of file cg_consolecmds.c.
{
     trap_Cvar_Set("cg_viewsize", va("%i",(int)(cg_viewsize.integer+10)));
 }
References cg_viewsize, vmCvar_t::integer, trap_Cvar_Set(), and va().
CG_StartOrbit_f()
static void CG_StartOrbit_f (void) static
Definition at line 214 of file cg_consolecmds.c.
{
     char var[MAX_TOKEN_CHARS];
     trap_Cvar_VariableStringBuffer( "developer", var, sizeof( var ) );
     if ( !atoi(var) ) {
         return;
     }
     if (cg_cameraOrbit.value != 0) {
         trap_Cvar_Set ("cg_cameraOrbit", "0");
         trap_Cvar_Set("cg_thirdPerson", "0");
     } else {
         trap_Cvar_Set("cg_cameraOrbit", "5");
         trap_Cvar_Set("cg_thirdPerson", "1");
         trap_Cvar_Set("cg_thirdPersonAngle", "0");
         trap_Cvar_Set("cg_thirdPersonRange", "100");
     }
 }
References cg_cameraOrbit, MAX_TOKEN_CHARS, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and vmCvar_t::value.
CG_TargetCommand_f()
void CG_TargetCommand_f (void)
Definition at line 29 of file cg_consolecmds.c.
{
     int     targetNum;
     char    test[4];
     targetNum = CG_CrosshairPlayer();
     if (!targetNum ) {
         return;
     }
     trap_Argv( 1, test, 4 );
     trap_SendConsoleCommand( va( "gc %i %i", targetNum, atoi( test ) ) );
 }
References CG_CrosshairPlayer(), test(), trap_Argv(), trap_SendConsoleCommand(), and va().
CG_TellAttacker_f()
static void CG_TellAttacker_f (void) static
Definition at line 124 of file cg_consolecmds.c.
{
     int     clientNum;
     char    command[128];
     char    message[128];
     clientNum = CG_LastAttacker();
     if ( clientNum == -1 ) {
         return;
     }
     trap_Args( message, 128 );
     Com_sprintf( command, 128, "tell %i %s", clientNum, message );
     trap_SendClientCommand( command );
 }
References CG_LastAttacker(), Com_sprintf(), trap_Args(), and trap_SendClientCommand().
CG_TellTarget_f()
static void CG_TellTarget_f (void) static
Definition at line 109 of file cg_consolecmds.c.
{
     int     clientNum;
     char    command[128];
     char    message[128];
     clientNum = CG_CrosshairPlayer();
     if ( clientNum == -1 ) {
         return;
     }
     trap_Args( message, 128 );
     Com_sprintf( command, 128, "tell %i %s", clientNum, message );
     trap_SendClientCommand( command );
 }
References CG_CrosshairPlayer(), Com_sprintf(), trap_Args(), and trap_SendClientCommand().
CG_Viewpos_f()
static void CG_Viewpos_f (void) static
Definition at line 75 of file cg_consolecmds.c.
{
     CG_Printf ("(%i %i %i) : %i\n", (int)cg.refdef.vieworg[0],
         (int)cg.refdef.vieworg[1], (int)cg.refdef.vieworg[2],
         (int)cg.refdefViewAngles[YAW]);
 }
References cg, CG_Printf(), cg_t::refdef, cg_t::refdefViewAngles, refdef_t::vieworg, and YAW.
CG_VoiceTellAttacker_f()
static void CG_VoiceTellAttacker_f (void) static
Definition at line 154 of file cg_consolecmds.c.
{
     int     clientNum;
     char    command[128];
     char    message[128];
     clientNum = CG_LastAttacker();
     if ( clientNum == -1 ) {
         return;
     }
     trap_Args( message, 128 );
     Com_sprintf( command, 128, "vtell %i %s", clientNum, message );
     trap_SendClientCommand( command );
 }
References CG_LastAttacker(), Com_sprintf(), trap_Args(), and trap_SendClientCommand().
CG_VoiceTellTarget_f()
static void CG_VoiceTellTarget_f (void) static
Definition at line 139 of file cg_consolecmds.c.
{
     int     clientNum;
     char    command[128];
     char    message[128];
     clientNum = CG_CrosshairPlayer();
     if ( clientNum == -1 ) {
         return;
     }
     trap_Args( message, 128 );
     Com_sprintf( command, 128, "vtell %i %s", clientNum, message );
     trap_SendClientCommand( command );
 }
References CG_CrosshairPlayer(), Com_sprintf(), trap_Args(), and trap_SendClientCommand().
Variable Documentation
commands
consoleCommand_t commands[] static
Initial value:
= {
    { "viewpos", CG_Viewpos_f },
    { "+scores", CG_ScoresDown_f },
    { "-scores", CG_ScoresUp_f },
    { "+zoom", CG_ZoomDown_f },
    { "-zoom", CG_ZoomUp_f },
    { "sizeup", CG_SizeUp_f },
    { "sizedown", CG_SizeDown_f },
    { "weapnext", CG_NextWeapon_f },
    { "weapprev", CG_PrevWeapon_f },
    { "weapon", CG_Weapon_f },
    { "tiernext", CG_NextTier_f },
    { "tierprev", CG_PrevTier_f },
    { "tier", CG_Tier_f },
    { "tell_target", CG_TellTarget_f },
    { "tell_attacker", CG_TellAttacker_f },
    { "vtell_target", CG_VoiceTellTarget_f },
    { "vtell_attacker", CG_VoiceTellAttacker_f },
    { "tcmd", CG_TargetCommand_f },
    { "startOrbit", CG_StartOrbit_f },
    { "draw2D", CG_Draw2D_f },
    { "draw2d", CG_Draw2D_f },
    { "loaddeferred", CG_LoadDeferredPlayers }
}
Definition at line 236 of file cg_consolecmds.c.
Referenced by CG_ConsoleCommand(), CG_InitConsoleCommands(), and Sys_Dialog().