ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/bits/stl_pair.h File Reference
stl_pair.h File Reference
#include <bits/move.h>
Functions
namespace std _GLIBCXX_VISIBILITY (default)
Detailed Description
This is an internal header file, included by other library headers. Do not attempt to use it directly. @headername{utility}
Definition in file stl_pair.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace std _GLIBCXX_VISIBILITY (default)
Struct holding two objects of arbitrary type.
first_type is the first bound type
second_type is the second bound type
first is a copy of the first object
second is a copy of the second object
The default constructor creates first and second using their respective default constructors.
Two objects may be passed to a pair constructor to be copied.
There is also a templated copy ctor for the pair class itself.
Two pairs of the same type are equal iff their members are equal.
http://gcc.gnu.org/onlinedocs/libstdc++/manual/utilities.html
Uses operator== to find the result.
Uses operator< to find the result.
Uses operator< to find the result.
Uses operator< to find the result.
A convenience wrapper for creating a pair from two objects.
Parameters
x The first object.
y The second object.
Returns
A newly-constructed pair<> object of the appropriate type.
The standard requires that the objects be passed by reference-to-const, but LWG issue #181 says they should be passed by const value. We follow the LWG by default.
Definition at line 66 of file stl_pair.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
   struct piecewise_construct_t { };
   constexpr piecewise_construct_t piecewise_construct = piecewise_construct_t();
   // Forward declarations.
   template<typename...>
     class tuple;
   template<int...>
     struct _Index_tuple;
 #endif
   template<class _T1, class _T2>
     struct pair
     {
       typedef _T1 first_type;
       typedef _T2 second_type;
       _T1 first;
       _T2 second;
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // 265.  std::pair::pair() effects overly restrictive
       _GLIBCXX_CONSTEXPR pair()
       : first(), second() { }
       _GLIBCXX_CONSTEXPR pair(const _T1& __a, const _T2& __b)
       : first(__a), second(__b) { }
       template<class _U1, class _U2>
     _GLIBCXX_CONSTEXPR pair(const pair<_U1, _U2>& __p)
     : first(__p.first), second(__p.second) { }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       constexpr pair(const pair&) = default;
       // Implicit.
       // pair(pair&&) = default;
       // DR 811.
       template<class _U1, class = typename
            std::enable_if<std::is_convertible<_U1, _T1>::value>::type>
     pair(_U1&& __x, const _T2& __y)
     : first(std::forward<_U1>(__x)), second(__y) { }
       template<class _U2, class = typename
            std::enable_if<std::is_convertible<_U2, _T2>::value>::type>
     pair(const _T1& __x, _U2&& __y)
     : first(__x), second(std::forward<_U2>(__y)) { }
       template<class _U1, class _U2, class = typename
            std::enable_if<std::is_convertible<_U1, _T1>::value
                   && std::is_convertible<_U2, _T2>::value>::type>
     pair(_U1&& __x, _U2&& __y)
     : first(std::forward<_U1>(__x)), second(std::forward<_U2>(__y)) { }
       template<class _U1, class _U2>
     pair(pair<_U1, _U2>&& __p)
     : first(std::forward<_U1>(__p.first)),
       second(std::forward<_U2>(__p.second)) { }
       template<class... _Args1, class... _Args2>
     pair(piecewise_construct_t,
          tuple<_Args1...> __first, tuple<_Args2...> __second)
     : first(__cons<first_type>(std::move(__first))),
       second(__cons<second_type>(std::move(__second))) { }
       pair&
       operator=(const pair& __p)
       {
     first = __p.first;
     second = __p.second;
     return *this;
       }
       pair&
       operator=(pair&& __p)
       {
     first = std::move(__p.first);
     second = std::move(__p.second);
     return *this;
       }
       template<class _U1, class _U2>
     pair&
     operator=(const pair<_U1, _U2>& __p)
     {
       first = __p.first;
       second = __p.second;
       return *this;
     }
       template<class _U1, class _U2>
     pair&
     operator=(pair<_U1, _U2>&& __p)
     {
       first = std::move(__p.first);
       second = std::move(__p.second);
       return *this;
     }
       void
       swap(pair& __p)
       {
     using std::swap;
     swap(first, __p.first);
     swap(second, __p.second);
       }
     private:
       template<typename _Tp, typename... _Args>
     static _Tp
     __cons(tuple<_Args...>&&);
       template<typename _Tp, typename... _Args, int... _Indexes>
     static _Tp
     __do_cons(tuple<_Args...>&&, const _Index_tuple<_Indexes...>&);
 #endif
     };
   template<class _T1, class _T2>
     inline _GLIBCXX_CONSTEXPR bool
     operator==(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
     { return __x.first == __y.first && __x.second == __y.second; }
   template<class _T1, class _T2>
     inline _GLIBCXX_CONSTEXPR bool
     operator<(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
     { return __x.first < __y.first
          || (!(__y.first < __x.first) && __x.second < __y.second); }
   template<class _T1, class _T2>
     inline _GLIBCXX_CONSTEXPR bool
     operator!=(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
     { return !(__x == __y); }
   template<class _T1, class _T2>
     inline _GLIBCXX_CONSTEXPR bool
     operator>(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
     { return __y < __x; }
   template<class _T1, class _T2>
     inline _GLIBCXX_CONSTEXPR bool
     operator<=(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
     { return !(__y < __x); }
   template<class _T1, class _T2>
     inline _GLIBCXX_CONSTEXPR bool
     operator>=(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
     { return !(__x < __y); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
   // Note:  no std::swap overloads in C++03 mode, this has performance
   //        implications, see, eg, libstdc++/38466.
   template<class _T1, class _T2>
     inline void
     swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
     { __x.swap(__y); }
 #endif
   // _GLIBCXX_RESOLVE_LIB_DEFECTS
   // 181.  make_pair() unintended behavior
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
   // NB: DR 706.
   template<class _T1, class _T2>
     inline pair<typename __decay_and_strip<_T1>::__type,
         typename __decay_and_strip<_T2>::__type>
     make_pair(_T1&& __x, _T2&& __y)
     {
       typedef typename __decay_and_strip<_T1>::__type __ds_type1;
       typedef typename __decay_and_strip<_T2>::__type __ds_type2;
       typedef pair<__ds_type1, __ds_type2>        __pair_type;
       return __pair_type(std::forward<_T1>(__x), std::forward<_T2>(__y));
     }
 #else
   template<class _T1, class _T2>
     inline pair<_T1, _T2>
     make_pair(_T1 __x, _T2 __y)
     { return pair<_T1, _T2>(__x, __y); }
 #endif
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References constexpr(), move(), std::__exception_ptr::operator!=(), __gnu_debug::operator<(), __gnu_debug::operator<=(), std::__exception_ptr::operator==(), __gnu_debug::operator>(), __gnu_debug::operator>=(), and swap.