ZEQ2-Lite: Various definitions for Speex callbacks supported by the decoder.
Various definitions for Speex callbacks supported by the decoder.
Data Structures
struct SpeexCallback
Callback information.
Macros
#define SPEEX_INBAND_ACKNOWLEDGE 12
Acknowledge packet reception.
#define SPEEX_INBAND_ACKNOWLEDGE_REQUEST 6
Request to be sent acknowledge.
#define SPEEX_INBAND_CHAR 8
Send a character in-band.
#define SPEEX_INBAND_ENH_REQUEST 0
Request for perceptual enhancement (1 for on, 0 for off)
#define SPEEX_INBAND_HIGH_MODE_REQUEST 4
Request for a high mode change.
#define SPEEX_INBAND_LOW_MODE_REQUEST 3
Request for a low mode change.
#define SPEEX_INBAND_MAX_BITRATE 10
Transmit max bit-rate allowed.
#define SPEEX_INBAND_MODE_REQUEST 2
Request for a mode change.
#define SPEEX_INBAND_RESERVED1 1
Reserved.
#define SPEEX_INBAND_STEREO 9
Intensity stereo information.
#define SPEEX_INBAND_VBR_QUALITY_REQUEST 5
Request for VBR (1 on, 0 off)
#define SPEEX_INBAND_VBR_REQUEST 7
Request for VBR (1 for on, 0 for off)
#define SPEEX_MAX_CALLBACKS 16
Total number of callbacks.
Typedefs
typedef int(* speex_callback_func) (SpeexBits *bits, void *state, void *data)
Callback function type.
Functions
int speex_default_user_handler (SpeexBits *bits, void *state, void *data)
Default handler for user-defined requests: in this case, just ignore.
int speex_inband_handler (SpeexBits *bits, SpeexCallback *callback_list, void *state)
Handle in-band request.
int speex_std_char_handler (SpeexBits *bits, void *state, void *data)
Standard handler for in-band characters (write to stderr)
int speex_std_enh_request_handler (SpeexBits *bits, void *state, void *data)
Standard handler for enhancer request (Turn enhancer on/off, no questions asked)
int speex_std_high_mode_request_handler (SpeexBits *bits, void *state, void *data)
Standard handler for high mode request (change high mode, no questions asked)
int speex_std_low_mode_request_handler (SpeexBits *bits, void *state, void *data)
Standard handler for low mode request (change low mode, no questions asked)
int speex_std_mode_request_handler (SpeexBits *bits, void *state, void *data)
Standard handler for mode request (change mode, no questions asked)
int speex_std_vbr_quality_request_handler (SpeexBits *bits, void *state, void *data)
Standard handler for VBR quality request (Set VBR quality, no questions asked)
int speex_std_vbr_request_handler (SpeexBits *bits, void *state, void *data)
Standard handler for VBR request (Set VBR, no questions asked)
Detailed Description
Macro Definition Documentation
SPEEX_INBAND_ACKNOWLEDGE
#define SPEEX_INBAND_ACKNOWLEDGE 12
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Acknowledge packet reception.
Definition at line 85 of file speex_callbacks.h.
SPEEX_INBAND_ACKNOWLEDGE_REQUEST
#define SPEEX_INBAND_ACKNOWLEDGE_REQUEST 6
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Request to be sent acknowledge.
Definition at line 69 of file speex_callbacks.h.
SPEEX_INBAND_CHAR
#define SPEEX_INBAND_CHAR 8
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Send a character in-band.
Definition at line 75 of file speex_callbacks.h.
SPEEX_INBAND_ENH_REQUEST
#define SPEEX_INBAND_ENH_REQUEST 0
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Request for perceptual enhancement (1 for on, 0 for off)
Definition at line 55 of file speex_callbacks.h.
SPEEX_INBAND_HIGH_MODE_REQUEST
#define SPEEX_INBAND_HIGH_MODE_REQUEST 4
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Request for a high mode change.
Definition at line 65 of file speex_callbacks.h.
SPEEX_INBAND_LOW_MODE_REQUEST
#define SPEEX_INBAND_LOW_MODE_REQUEST 3
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Request for a low mode change.
Definition at line 63 of file speex_callbacks.h.
SPEEX_INBAND_MAX_BITRATE
#define SPEEX_INBAND_MAX_BITRATE 10
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Transmit max bit-rate allowed.
Definition at line 81 of file speex_callbacks.h.
SPEEX_INBAND_MODE_REQUEST
#define SPEEX_INBAND_MODE_REQUEST 2
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Request for a mode change.
Definition at line 61 of file speex_callbacks.h.
SPEEX_INBAND_RESERVED1
#define SPEEX_INBAND_RESERVED1 1
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Reserved.
Definition at line 57 of file speex_callbacks.h.
SPEEX_INBAND_STEREO
#define SPEEX_INBAND_STEREO 9
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Intensity stereo information.
Definition at line 77 of file speex_callbacks.h.
SPEEX_INBAND_VBR_QUALITY_REQUEST
#define SPEEX_INBAND_VBR_QUALITY_REQUEST 5
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Request for VBR (1 on, 0 off)
Definition at line 67 of file speex_callbacks.h.
SPEEX_INBAND_VBR_REQUEST
#define SPEEX_INBAND_VBR_REQUEST 7
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Request for VBR (1 for on, 0 for off)
Definition at line 71 of file speex_callbacks.h.
SPEEX_MAX_CALLBACKS
#define SPEEX_MAX_CALLBACKS 16
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Total number of callbacks.
Definition at line 49 of file speex_callbacks.h.
Typedef Documentation
speex_callback_func
typedef int(* speex_callback_func) (SpeexBits *bits, void *state, void *data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Callback function type.
Definition at line 88 of file speex_callbacks.h.
Function Documentation
speex_default_user_handler()
int speex_default_user_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Default handler for user-defined requests: in this case, just ignore.
Definition at line 139 of file speex_callbacks.c.
 {
    int req_size = speex_bits_unpack_unsigned(bits, 4);
    speex_bits_advance(bits, 5+8*req_size);
    return 0;
 }
References bits(), speex_bits_advance(), and speex_bits_unpack_unsigned().
Referenced by nb_decoder_init().
speex_inband_handler()
int speex_inband_handler (SpeexBits * bits, SpeexCallback * callback_list, void * state)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Handle in-band request.
Definition at line 43 of file speex_callbacks.c.
 {
    int id;
    SpeexCallback *callback;
    /*speex_bits_advance(bits, 5);*/
    id=speex_bits_unpack_unsigned(bits, 4);
    callback = callback_list+id;
    if (callback->func)
    {
       return callback->func(bits, state, callback->data);
    } else
       /*If callback is not registered, skip the right number of bits*/
    {
       int adv;
       if (id<2)
          adv = 1;
       else if (id<8)
          adv = 4;
       else if (id<10)
          adv = 8;
       else if (id<12)
          adv = 16;
       else if (id<14)
          adv = 32;
       else
          adv = 64;
       speex_bits_advance(bits, adv);
    }
    return 0;
 }
References bits(), SpeexCallback::data, SpeexCallback::func, speex_bits_advance(), and speex_bits_unpack_unsigned().
Referenced by nb_decode().
speex_std_char_handler()
int speex_std_char_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Standard handler for in-band characters (write to stderr)
Definition at line 127 of file speex_callbacks.c.
 {
    unsigned char ch;
    ch = speex_bits_unpack_unsigned(bits, 8);
    _speex_putc(ch, data);
    /*printf("speex_std_char_handler ch=%x\n", ch);*/
    return 0;
 }
References _speex_putc(), bits(), and speex_bits_unpack_unsigned().
Referenced by main().
speex_std_enh_request_handler()
int speex_std_enh_request_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Standard handler for enhancer request (Turn enhancer on/off, no questions asked)
Definition at line 109 of file speex_callbacks.c.
 {
    spx_int32_t enh;
    enh = speex_bits_unpack_unsigned(bits, 1);
    speex_decoder_ctl(data, SPEEX_SET_ENH, &enh);
    return 0;
 }
References bits(), speex_bits_unpack_unsigned(), speex_decoder_ctl(), and SPEEX_SET_ENH.
speex_std_high_mode_request_handler()
int speex_std_high_mode_request_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Standard handler for high mode request (change high mode, no questions asked)
Definition at line 91 of file speex_callbacks.c.
 {
    spx_int32_t m;
    m = speex_bits_unpack_unsigned(bits, 4);
    speex_encoder_ctl(data, SPEEX_SET_HIGH_MODE, &m);
    return 0;
 }
References bits(), m, speex_bits_unpack_unsigned(), speex_encoder_ctl(), and SPEEX_SET_HIGH_MODE.
speex_std_low_mode_request_handler()
int speex_std_low_mode_request_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Standard handler for low mode request (change low mode, no questions asked)
Definition at line 83 of file speex_callbacks.c.
 {
    spx_int32_t m;
    m = speex_bits_unpack_unsigned(bits, 4);
    speex_encoder_ctl(data, SPEEX_SET_LOW_MODE, &m);
    return 0;
 }
References bits(), m, speex_bits_unpack_unsigned(), speex_encoder_ctl(), and SPEEX_SET_LOW_MODE.
speex_std_mode_request_handler()
int speex_std_mode_request_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Standard handler for mode request (change mode, no questions asked)
Definition at line 75 of file speex_callbacks.c.
 {
    spx_int32_t m;
    m = speex_bits_unpack_unsigned(bits, 4);
    speex_encoder_ctl(data, SPEEX_SET_MODE, &m);
    return 0;
 }
References bits(), m, speex_bits_unpack_unsigned(), speex_encoder_ctl(), and SPEEX_SET_MODE.
Referenced by main().
speex_std_vbr_quality_request_handler()
int speex_std_vbr_quality_request_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Standard handler for VBR quality request (Set VBR quality, no questions asked)
Definition at line 118 of file speex_callbacks.c.
 {
    float qual;
    qual = speex_bits_unpack_unsigned(bits, 4);
    speex_encoder_ctl(data, SPEEX_SET_VBR_QUALITY, &qual);
    return 0;
 }
References bits(), qual(), speex_bits_unpack_unsigned(), speex_encoder_ctl(), and SPEEX_SET_VBR_QUALITY.
speex_std_vbr_request_handler()
int speex_std_vbr_request_handler (SpeexBits * bits, void * state, void * data)
#include <Source/Engine/libspeex/include/speex/speex_callbacks.h>
Standard handler for VBR request (Set VBR, no questions asked)
Definition at line 100 of file speex_callbacks.c.
 {
    spx_int32_t vbr;
    vbr = speex_bits_unpack_unsigned(bits, 1);
    speex_encoder_ctl(data, SPEEX_SET_VBR, &vbr);
    return 0;
 }
References bits(), speex_bits_unpack_unsigned(), speex_encoder_ctl(), and SPEEX_SET_VBR.