ZEQ2-Lite: Source/Game/UI/ui_options.c File Reference
ui_options.c File Reference
#include "ui_local.h"
Data Structures
struct optionsmenu_t
Macros
#define ART_BACK0 "interface/art/back_0"
#define ART_BACK1 "interface/art/back_1"
#define ART_FRAMEL "interface/art/frame2_l"
#define ART_FRAMER "interface/art/frame1_r"
#define ID_BACK 14
#define ID_DISPLAY 11
#define ID_GRAPHICS 10
#define ID_NETWORK 13
#define ID_SOUND 12
#define VERTICAL_SPACING 34
Functions
static void Options_Event (void *ptr, int event)
void Options_MenuInit (void)
void SystemConfig_Cache (void)
void UI_SystemConfigMenu (void)
Variables
static optionsmenu_t s_options
Macro Definition Documentation
ART_BACK0
#define ART_BACK0 "interface/art/back_0"
Definition at line 35 of file ui_options.c.
ART_BACK1
#define ART_BACK1 "interface/art/back_1"
Definition at line 36 of file ui_options.c.
ART_FRAMEL
#define ART_FRAMEL "interface/art/frame2_l"
Definition at line 33 of file ui_options.c.
ART_FRAMER
#define ART_FRAMER "interface/art/frame1_r"
Definition at line 34 of file ui_options.c.
ID_BACK
#define ID_BACK 14
Definition at line 42 of file ui_options.c.
ID_DISPLAY
#define ID_DISPLAY 11
Definition at line 39 of file ui_options.c.
ID_GRAPHICS
#define ID_GRAPHICS 10
Definition at line 38 of file ui_options.c.
ID_NETWORK
#define ID_NETWORK 13
Definition at line 41 of file ui_options.c.
ID_SOUND
#define ID_SOUND 12
Definition at line 40 of file ui_options.c.
VERTICAL_SPACING
#define VERTICAL_SPACING 34
Definition at line 44 of file ui_options.c.
Function Documentation
Options_Event()
static void Options_Event (void * ptr, int event) static
Definition at line 68 of file ui_options.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch( ((menucommon_s*)ptr)->id ) {
     case ID_BACK:
         UI_PopMenu();
         break;
     }
 }
References ID_BACK, ptr(), QM_ACTIVATED, and UI_PopMenu().
Referenced by Options_MenuInit().
Options_MenuInit()
void Options_MenuInit (void)
Definition at line 98 of file ui_options.c.
{
     int             y;
     uiClientState_t cstate;
     memset( &s_options, 0, sizeof(optionsmenu_t) );
     SystemConfig_Cache();
     s_options.menu.wrapAround = qtrue;
     trap_GetClientState( &cstate );
     if ( cstate.connState >= CA_CONNECTED ) {
         s_options.menu.fullscreen = qfalse;
     }
     else {
         s_options.menu.fullscreen = qtrue;
     }
     s_options.banner.generic.type   = MTYPE_BTEXT;
     s_options.banner.generic.flags  = QMF_CENTER_JUSTIFY;
     s_options.banner.generic.x      = 320;
     s_options.banner.generic.y      = 16;
     s_options.banner.string         = "SYSTEM SETUP";
     s_options.banner.color          = color_white;
     s_options.banner.style          = UI_CENTER|UI_DROPSHADOW;
     s_options.framel.generic.type  = MTYPE_BITMAP;
     s_options.framel.generic.name  = ART_FRAMEL;
     s_options.framel.generic.flags = QMF_INACTIVE;
     s_options.framel.generic.x     = 8;
     s_options.framel.generic.y     = 76;
     s_options.framel.width         = 256;
     s_options.framel.height        = 334;
     s_options.framer.generic.type  = MTYPE_BITMAP;
     s_options.framer.generic.name  = ART_FRAMER;
     s_options.framer.generic.flags = QMF_INACTIVE;
     s_options.framer.generic.x     = 376;
     s_options.framer.generic.y     = 76;
     s_options.framer.width         = 256;
     s_options.framer.height        = 334;
     y = 168;
     s_options.graphics.generic.type     = MTYPE_PTEXT;
     s_options.graphics.generic.flags    = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_options.graphics.generic.callback = Options_Event;
     s_options.graphics.generic.id       = ID_GRAPHICS;
     s_options.graphics.generic.x        = 320;
     s_options.graphics.generic.y        = y;
     s_options.graphics.string           = "GRAPHICS";
     s_options.graphics.color            = color_white;
     s_options.graphics.style            = UI_CENTER|UI_DROPSHADOW;
     y += VERTICAL_SPACING;
     s_options.display.generic.type      = MTYPE_PTEXT;
     s_options.display.generic.flags     = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_options.display.generic.callback  = Options_Event;
     s_options.display.generic.id        = ID_DISPLAY;
     s_options.display.generic.x         = 320;
     s_options.display.generic.y         = y;
     s_options.display.string            = "DISPLAY";
     s_options.display.color             = color_white;
     s_options.display.style             = UI_CENTER|UI_DROPSHADOW;
     y += VERTICAL_SPACING;
     s_options.sound.generic.type        = MTYPE_PTEXT;
     s_options.sound.generic.flags       = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_options.sound.generic.callback    = Options_Event;
     s_options.sound.generic.id          = ID_SOUND;
     s_options.sound.generic.x           = 320;
     s_options.sound.generic.y           = y;
     s_options.sound.string              = "SOUND";
     s_options.sound.color               = color_white;
     s_options.sound.style               = UI_CENTER|UI_DROPSHADOW;
     y += VERTICAL_SPACING;
     s_options.network.generic.type      = MTYPE_PTEXT;
     s_options.network.generic.flags     = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_options.network.generic.callback  = Options_Event;
     s_options.network.generic.id        = ID_NETWORK;
     s_options.network.generic.x         = 320;
     s_options.network.generic.y         = y;
     s_options.network.string            = "NETWORK";
     s_options.network.color             = color_white;
     s_options.network.style             = UI_CENTER|UI_DROPSHADOW;
     s_options.back.generic.type     = MTYPE_BITMAP;
     s_options.back.generic.name     = ART_BACK0;
     s_options.back.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_options.back.generic.callback = Options_Event;
     s_options.back.generic.id       = ID_BACK;
     s_options.back.generic.x        = 0;
     s_options.back.generic.y        = 480-64;
     s_options.back.width            = 128;
     s_options.back.height           = 64;
     s_options.back.focuspic         = ART_BACK1;
     Menu_AddItem( &s_options.menu, ( void * ) &s_options.graphics );
     Menu_AddItem( &s_options.menu, ( void * ) &s_options.display );
     Menu_AddItem( &s_options.menu, ( void * ) &s_options.sound );
     Menu_AddItem( &s_options.menu, ( void * ) &s_options.network );
     Menu_AddItem( &s_options.menu, ( void * ) &s_options.back );
 }
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, optionsmenu_t::back, optionsmenu_t::banner, CA_CONNECTED, menucommon_s::callback, menutext_s::color, color_white, uiClientState_t::connState, optionsmenu_t::display, menucommon_s::flags, menubitmap_s::focuspic, optionsmenu_t::framel, optionsmenu_t::framer, menubitmap_s::generic, menutext_s::generic, optionsmenu_t::graphics, menubitmap_s::height, menucommon_s::id, ID_BACK, ID_DISPLAY, ID_GRAPHICS, ID_NETWORK, ID_SOUND, optionsmenu_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, menucommon_s::name, optionsmenu_t::network, Options_Event(), qfalse, QMF_CENTER_JUSTIFY, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s_options, optionsmenu_t::sound, menutext_s::string, menutext_s::style, SystemConfig_Cache(), trap_GetClientState(), menucommon_s::type, UI_CENTER, UI_DROPSHADOW, VERTICAL_SPACING, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by UI_SystemConfigMenu().
SystemConfig_Cache()
void SystemConfig_Cache (void)
Definition at line 86 of file ui_options.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
 }
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by Options_MenuInit().
UI_SystemConfigMenu()
void UI_SystemConfigMenu (void)
Definition at line 207 of file ui_options.c.
{
     uis.menuamount = 0;
     Options_MenuInit();
     UI_PushMenu ( &s_options.menu );
 }
References optionsmenu_t::menu, uiStatic_t::menuamount, Options_MenuInit(), s_options, UI_PushMenu(), and uis.
Variable Documentation
s_options
optionsmenu_t s_options static
Definition at line 60 of file ui_options.c.
Referenced by Options_MenuInit(), and UI_SystemConfigMenu().