ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/i686-pc-mingw32/bits/gthr-tpf.h File Reference
gthr-tpf.h File Reference
#include <pthread.h>
#include <unistd.h>
Macros
#define __GTHREAD_MUTEX_INIT PTHREAD_MUTEX_INITIALIZER
#define __GTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
#define __GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION __gthread_recursive_mutex_init_function
#define __GTHREADS 1
#define __gthrw(name)
#define __gthrw_(name) name
#define __tpf_pthread_active() (CE2THRCPTR != NOTATHREAD)
#define _REENTRANT 1
#define CE2THRCPTR *((unsigned char *)(ECBPG2PTR + 16))
#define ECBBASEPTR (unsigned long int) *(unsigned int *)0x00000514u
#define ECBPG2PTR ECBBASEPTR + 0x1000
#define NOTATHREAD 00
Typedefs
typedef pthread_key_t __gthread_key_t
typedef pthread_mutex_t __gthread_mutex_t
typedef pthread_once_t __gthread_once_t
typedef pthread_mutex_t __gthread_recursive_mutex_t
Functions
static void * __gthread_getspecific (__gthread_key_t __key)
static int __gthread_key_create (__gthread_key_t *__key, void(*__dtor)(void *))
static int __gthread_key_delete (__gthread_key_t __key)
static int __gthread_mutex_destroy (__gthread_mutex_t *__mutex)
static int __gthread_mutex_lock (__gthread_mutex_t *__mutex)
static int __gthread_mutex_trylock (__gthread_mutex_t *__mutex)
static int __gthread_mutex_unlock (__gthread_mutex_t *__mutex)
static int __gthread_once (__gthread_once_t *__once, void(*__func)(void))
static int __gthread_recursive_mutex_init_function (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_lock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_trylock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_unlock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_setspecific (__gthread_key_t __key, const void *__ptr)
__gthrw (pthread_once) __gthrw(pthread_key_create) __gthrw(pthread_key_delete) __gthrw(pthread_getspecific) __gthrw(pthread_setspecific) __gthrw(pthread_create) __gthrw(pthread_mutex_lock) __gthrw(pthread_mutex_trylock) __gthrw(pthread_mutex_unlock) __gthrw(pthread_mutexattr_init) __gthrw(pthread_mutexattr_settype) __gthrw(pthread_mutexattr_destroy) __gthrw(pthread_mutex_init) __gthrw(pthread_mutex_destroy) static inline int __gthread_active_p(void)
Macro Definition Documentation
__GTHREAD_MUTEX_INIT
#define __GTHREAD_MUTEX_INIT PTHREAD_MUTEX_INITIALIZER
Definition at line 58 of file gthr-tpf.h.
__GTHREAD_ONCE_INIT
#define __GTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
Definition at line 59 of file gthr-tpf.h.
__GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION
#define __GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION __gthread_recursive_mutex_init_function
Definition at line 60 of file gthr-tpf.h.
__GTHREADS
#define __GTHREADS 1
Definition at line 37 of file gthr-tpf.h.
__gthrw
#define __gthrw (name)
Definition at line 73 of file gthr-tpf.h.
__gthrw_
#define __gthrw_ (name) name
Definition at line 74 of file gthr-tpf.h.
__tpf_pthread_active
#define __tpf_pthread_active () (CE2THRCPTR != NOTATHREAD)
Definition at line 66 of file gthr-tpf.h.
_REENTRANT
#define _REENTRANT 1
Definition at line 41 of file gthr-tpf.h.
CE2THRCPTR
#define CE2THRCPTR *((unsigned char *)(ECBPG2PTR + 16))
Definition at line 65 of file gthr-tpf.h.
ECBBASEPTR
#define ECBBASEPTR (unsigned long int) *(unsigned int *)0x00000514u
Definition at line 63 of file gthr-tpf.h.
ECBPG2PTR
#define ECBPG2PTR ECBBASEPTR + 0x1000
Definition at line 64 of file gthr-tpf.h.
NOTATHREAD
#define NOTATHREAD 00
Definition at line 62 of file gthr-tpf.h.
Typedef Documentation
__gthread_key_t
typedef pthread_key_t __gthread_key_t
Definition at line 47 of file gthr-tpf.h.
__gthread_mutex_t
typedef pthread_mutex_t __gthread_mutex_t
Definition at line 49 of file gthr-tpf.h.
__gthread_once_t
typedef pthread_once_t __gthread_once_t
Definition at line 48 of file gthr-tpf.h.
__gthread_recursive_mutex_t
typedef pthread_mutex_t __gthread_recursive_mutex_t
Definition at line 50 of file gthr-tpf.h.
Function Documentation
__gthread_getspecific()
static void* __gthread_getspecific (__gthread_key_t __key) inline static
Definition at line 127 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_getspecific) (__key);
   else
     return NULL;
 }
References __gthrw_, __tpf_pthread_active, and NULL.
__gthread_key_create()
static int __gthread_key_create (__gthread_key_t * __key, void(*)(void *) __dtor) inline static
Definition at line 109 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_key_create) (__key, __dtor);
   else
     return -1;
 }
References __gthrw_, and __tpf_pthread_active.
__gthread_key_delete()
static int __gthread_key_delete (__gthread_key_t __key) inline static
Definition at line 118 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_key_delete) (__key);
   else
     return -1;
 }
References __gthrw_, and __tpf_pthread_active.
__gthread_mutex_destroy()
static int __gthread_mutex_destroy (__gthread_mutex_t * __mutex) inline static
Definition at line 145 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_mutex_destroy) (__mutex);
   else
     return 0;
 }
References __gthrw_, and __tpf_pthread_active.
__gthread_mutex_lock()
static int __gthread_mutex_lock (__gthread_mutex_t * __mutex) inline static
Definition at line 154 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_mutex_lock) (__mutex);
   else
     return 0;
 }
References __gthrw_, and __tpf_pthread_active.
Referenced by __gthread_recursive_mutex_lock().
__gthread_mutex_trylock()
static int __gthread_mutex_trylock (__gthread_mutex_t * __mutex) inline static
Definition at line 163 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_mutex_trylock) (__mutex);
   else
     return 0;
 }
References __gthrw_, and __tpf_pthread_active.
Referenced by __gthread_recursive_mutex_trylock().
__gthread_mutex_unlock()
static int __gthread_mutex_unlock (__gthread_mutex_t * __mutex) inline static
Definition at line 172 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_mutex_unlock) (__mutex);
   else
     return 0;
 }
References __gthrw_, and __tpf_pthread_active.
Referenced by __gthread_recursive_mutex_unlock().
__gthread_once()
static int __gthread_once (__gthread_once_t * __once, void(*)(void) __func) inline static
Definition at line 100 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_once) (__once, __func);
   else
     return -1;
 }
References __gthrw_, and __tpf_pthread_active.
__gthread_recursive_mutex_init_function()
static int __gthread_recursive_mutex_init_function (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 208 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     {
       pthread_mutexattr_t __attr;
       int __r;
       __r = __gthrw_(pthread_mutexattr_init) (&__attr);
       if (!__r)
     __r = __gthrw_(pthread_mutexattr_settype) (&__attr,
                            PTHREAD_MUTEX_RECURSIVE);
       if (!__r)
     __r = __gthrw_(pthread_mutex_init) (__mutex, &__attr);
       if (!__r)
     __r = __gthrw_(pthread_mutexattr_destroy) (&__attr);
       return __r;
     }
   return 0;
 }
References __gthrw_, and __tpf_pthread_active.
__gthread_recursive_mutex_lock()
static int __gthread_recursive_mutex_lock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 181 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthread_mutex_lock (__mutex);
   else
     return 0;
 }
References __gthread_mutex_lock(), and __tpf_pthread_active.
__gthread_recursive_mutex_trylock()
static int __gthread_recursive_mutex_trylock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 190 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthread_mutex_trylock (__mutex);
   else
     return 0;
 }
References __gthread_mutex_trylock(), and __tpf_pthread_active.
__gthread_recursive_mutex_unlock()
static int __gthread_recursive_mutex_unlock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 199 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthread_mutex_unlock (__mutex);
   else
     return 0;
 }
References __gthread_mutex_unlock(), and __tpf_pthread_active.
__gthread_setspecific()
static int __gthread_setspecific (__gthread_key_t __key, const void * __ptr) inline static
Definition at line 136 of file gthr-tpf.h.
 {
   if (__tpf_pthread_active ())
     return __gthrw_(pthread_setspecific) (__key, __ptr);
   else
     return -1;
 }
References __gthrw_, and __tpf_pthread_active.
__gthrw()
__gthrw (pthread_once)
Definition at line 77 of file gthr-tpf.h.
 {
   return 1;
 }