ZEQ2-Lite: Game/Game/g_trigger.c File Reference
g_trigger.c File Reference
#include "g_local.h"
Functions
void AimAtTarget (gentity_t *self)
void func_timer_think (gentity_t *self)
void func_timer_use (gentity_t *self, gentity_t *other, gentity_t *activator)
void hurt_touch (gentity_t *self, gentity_t *other, trace_t *trace)
void hurt_use (gentity_t *self, gentity_t *other, gentity_t *activator)
void InitTrigger (gentity_t *self)
void multi_trigger (gentity_t *ent, gentity_t *activator)
void multi_wait (gentity_t *ent)
void SP_func_timer (gentity_t *self)
void SP_target_push (gentity_t *self)
void SP_trigger_always (gentity_t *ent)
void SP_trigger_hurt (gentity_t *self)
void SP_trigger_multiple (gentity_t *ent)
void SP_trigger_push (gentity_t *self)
void SP_trigger_teleport (gentity_t *self)
void Touch_Multi (gentity_t *self, gentity_t *other, trace_t *trace)
void trigger_always_think (gentity_t *ent)
void trigger_push_touch (gentity_t *self, gentity_t *other, trace_t *trace)
void trigger_teleporter_touch (gentity_t *self, gentity_t *other, trace_t *trace)
void Use_Multi (gentity_t *ent, gentity_t *other, gentity_t *activator)
void Use_target_push (gentity_t *self, gentity_t *other, gentity_t *activator)
Function Documentation
AimAtTarget()
void AimAtTarget (gentity_t * self)
Definition at line 160 of file g_trigger.c.
{
     gentity_t   *ent;
     vec3_t      origin;
     float       height, gravity, time, forward;
     float       dist;
     VectorAdd( self->r.absmin, self->r.absmax, origin );
     VectorScale ( origin, 0.5, origin );
     ent = G_PickTarget( self->target );
     if ( !ent ) {
         G_FreeEntity( self );
         return;
     }
     height = ent->s.origin[2] - origin[2];
     gravity = 1000;
     time = sqrt( height / ( .5 * gravity ) );
     if ( !time ) {
         G_FreeEntity( self );
         return;
     }
     // set s.origin2 to the push velocity
     VectorSubtract ( ent->s.origin, origin, self->s.origin2 );
     self->s.origin2[2] = 0;
     dist = VectorNormalize( self->s.origin2);
     forward = dist / time;
     VectorScale( self->s.origin2, forward, self->s.origin2 );
     self->s.origin2[2] = time * gravity;
 }
References forward, G_FreeEntity(), G_PickTarget(), sqrt(), time(), VectorAdd, VectorNormalize(), VectorScale, and VectorSubtract.
Referenced by SP_target_push(), and SP_trigger_push().
func_timer_think()
void func_timer_think (gentity_t * self)
Definition at line 380 of file g_trigger.c.
{
     G_UseTargets (self, self->activator);
     // set time before next firing
     self->nextthink = level.time + 1000 * ( self->wait + crandom() * self->random );
 }
References crandom, and G_UseTargets().
Referenced by func_timer_use(), and SP_func_timer().
func_timer_use()
void func_timer_use (gentity_t * self, gentity_t * other, gentity_t * activator)
Definition at line 386 of file g_trigger.c.
{
     self->activator = activator;
     // if on, turn it off
     if ( self->nextthink ) {
         self->nextthink = 0;
         return;
     }
     // turn it on
     func_timer_think (self);
 }
References func_timer_think().
Referenced by SP_func_timer().
hurt_touch()
void hurt_touch (gentity_t * self, gentity_t * other, trace_t * trace)
Definition at line 340 of file g_trigger.c.
{
     // is the activator a client ?
     if(other->client){
         other->client->ps.powerLevel[plDamageGeneric] += 8000000;
         trap_SendServerCommand(-1, va("cp \"%s^7 Was Put Knock Out\n\"", other->client->pers.netname));
         trap_SendConsoleCommand( EXEC_APPEND,"map_restart 5\n");
         if(other->pain){other->pain(other,other,8000000);}
     }
     // link in to the world if starting active
     if ( ! (self->spawnflags & 1) ) {
         trap_LinkEntity (self);
     }
 }
References EXEC_APPEND, plDamageGeneric, trap_LinkEntity(), trap_SendConsoleCommand(), trap_SendServerCommand(), and va().
Referenced by SP_trigger_hurt().
hurt_use()
void hurt_use (gentity_t * self, gentity_t * other, gentity_t * activator)
Definition at line 332 of file g_trigger.c.
{
     if ( self->r.linked ) {
         trap_UnlinkEntity( self );
     } else {
         trap_LinkEntity( self );
     }
 }
References trap_LinkEntity(), and trap_UnlinkEntity().
InitTrigger()
void InitTrigger (gentity_t * self)
Definition at line 26 of file g_trigger.c.
{
     if (!VectorCompare (self->s.angles, vec3_origin))
         G_SetMovedir (self->s.angles, self->movedir);
     trap_SetBrushModel( self, self->model );
     self->r.contents = CONTENTS_TRIGGER;        // replaces the -1 from trap_SetBrushModel
     self->r.svFlags = SVF_NOCLIENT;
 }
References CONTENTS_TRIGGER, G_SetMovedir(), SVF_NOCLIENT, trap_SetBrushModel(), vec3_origin, and VectorCompare().
Referenced by SP_trigger_hurt(), SP_trigger_multiple(), SP_trigger_push(), and SP_trigger_teleport().
multi_trigger()
void multi_trigger (gentity_t * ent, gentity_t * activator)
Definition at line 45 of file g_trigger.c.
{
     ent->activator = activator;
     if ( ent->nextthink ) {
         return;     // can't retrigger until the wait is over
     }
     if ( activator->client ) {
         if ( ( ent->spawnflags & 1 ) &&
             activator->client->sess.sessionTeam != TEAM_RED ) {
             return;
         }
         if ( ( ent->spawnflags & 2 ) &&
             activator->client->sess.sessionTeam != TEAM_BLUE ) {
             return;
         }
     }
     G_UseTargets (ent, ent->activator);
     if ( ent->wait > 0 ) {
         ent->think = multi_wait;
         ent->nextthink = level.time + ( ent->wait + ent->random * crandom() ) * 1000;
     } else {
         // we can't just remove (self) here, because this is a touch function
         // called while looping through area links...
         ent->touch = 0;
         ent->nextthink = level.time + FRAMETIME;
         ent->think = G_FreeEntity;
     }
 }
References crandom, FRAMETIME, G_FreeEntity(), G_UseTargets(), multi_wait(), TEAM_BLUE, and TEAM_RED.
Referenced by Touch_Multi(), and Use_Multi().
multi_wait()
void multi_wait (gentity_t * ent)
Definition at line 37 of file g_trigger.c.
{
     ent->nextthink = 0;
 }
Referenced by multi_trigger().
SP_func_timer()
void SP_func_timer (gentity_t * self)
Definition at line 399 of file g_trigger.c.
{
     G_SpawnFloat( "random", "1", &self->random);
     G_SpawnFloat( "wait", "1", &self->wait );
     self->use = func_timer_use;
     self->think = func_timer_think;
     if ( self->random >= self->wait ) {
         self->random = self->wait - FRAMETIME;
         G_Printf( "func_timer at %s has random >= wait\n", vtos( self->s.origin ) );
     }
     if ( self->spawnflags & 1 ) {
         self->nextthink = level.time + FRAMETIME;
         self->activator = self;
     }
     self->r.svFlags = SVF_NOCLIENT;
 }
References FRAMETIME, func_timer_think(), func_timer_use(), G_Printf(), G_SpawnFloat(), SVF_NOCLIENT, and vtos().
SP_target_push()
void SP_target_push (gentity_t * self)
Definition at line 238 of file g_trigger.c.
{
     if (!self->speed) {
         self->speed = 1000;
     }
     G_SetMovedir (self->s.angles, self->s.origin2);
     VectorScale (self->s.origin2, self->speed, self->s.origin2);
     if ( self->spawnflags & 1 ) {
         self->noise_index = G_SoundIndex("sound/world/jumppad.ogg");
     } else {
         self->noise_index = G_SoundIndex("sound/misc/windfly.ogg");
     }
     if ( self->target ) {
         VectorCopy( self->s.origin, self->r.absmin );
         VectorCopy( self->s.origin, self->r.absmax );
         self->think = AimAtTarget;
         self->nextthink = level.time + FRAMETIME;
     }
     self->use = Use_target_push;
 }
References AimAtTarget(), FRAMETIME, G_SetMovedir(), G_SoundIndex(), Use_target_push(), VectorCopy, and VectorScale.
SP_trigger_always()
void SP_trigger_always (gentity_t * ent)
Definition at line 128 of file g_trigger.c.
{
     // we must have some delay to make sure our use targets are present
     ent->nextthink = level.time + 300;
     ent->think = trigger_always_think;
 }
References trigger_always_think().
SP_trigger_hurt()
void SP_trigger_hurt (gentity_t * self)
Definition at line 355 of file g_trigger.c.
{
     InitTrigger (self);
     self->touch = hurt_touch;
 }
References hurt_touch(), and InitTrigger().
SP_trigger_multiple()
void SP_trigger_multiple (gentity_t * ent)
Definition at line 94 of file g_trigger.c.
{
     G_SpawnFloat( "wait", "0.5", &ent->wait );
     G_SpawnFloat( "random", "0", &ent->random );
     if ( ent->random >= ent->wait && ent->wait >= 0 ) {
         ent->random = ent->wait - FRAMETIME;
         G_Printf( "trigger_multiple has random >= wait\n" );
     }
     ent->touch = Touch_Multi;
     ent->use = Use_Multi;
     InitTrigger( ent );
     trap_LinkEntity (ent);
 }
References FRAMETIME, G_Printf(), G_SpawnFloat(), InitTrigger(), Touch_Multi(), trap_LinkEntity(), and Use_Multi().
SP_trigger_push()
void SP_trigger_push (gentity_t * self)
Definition at line 199 of file g_trigger.c.
{
     InitTrigger (self);
     // unlike other triggers, we need to send this one to the client
     self->r.svFlags &= ~SVF_NOCLIENT;
     // make sure the client precaches this sound
     G_SoundIndex("sound/world/jumppad.ogg");
     self->s.eType = ET_PUSH_TRIGGER;
     self->touch = trigger_push_touch;
     self->think = AimAtTarget;
     self->nextthink = level.time + FRAMETIME;
     trap_LinkEntity (self);
 }
References AimAtTarget(), ET_PUSH_TRIGGER, FRAMETIME, G_SoundIndex(), InitTrigger(), SVF_NOCLIENT, trap_LinkEntity(), and trigger_push_touch().
SP_trigger_teleport()
void SP_trigger_teleport (gentity_t * self)
Definition at line 301 of file g_trigger.c.
{
     InitTrigger (self);
     // unlike other triggers, we need to send this one to the client
     // unless is a spectator trigger
     if ( self->spawnflags & 1 ) {
         self->r.svFlags |= SVF_NOCLIENT;
     } else {
         self->r.svFlags &= ~SVF_NOCLIENT;
     }
     // make sure the client precaches this sound
     G_SoundIndex("sound/world/jumppad.ogg");
     self->s.eType = ET_TELEPORT_TRIGGER;
     self->touch = trigger_teleporter_touch;
     trap_LinkEntity (self);
 }
References ET_TELEPORT_TRIGGER, G_SoundIndex(), InitTrigger(), SVF_NOCLIENT, trap_LinkEntity(), and trigger_teleporter_touch().
Touch_Multi()
void Touch_Multi (gentity_t * self, gentity_t * other, trace_t * trace)
Definition at line 80 of file g_trigger.c.
{
     if( !other->client ) {
         return;
     }
     multi_trigger( self, other );
 }
References multi_trigger().
Referenced by SP_trigger_multiple().
trigger_always_think()
void trigger_always_think (gentity_t * ent)
Definition at line 120 of file g_trigger.c.
{
     G_UseTargets(ent, ent);
     G_FreeEntity( ent );
 }
References G_FreeEntity(), and G_UseTargets().
Referenced by SP_trigger_always().
trigger_push_touch()
void trigger_push_touch (gentity_t * self, gentity_t * other, trace_t * trace)
Definition at line 143 of file g_trigger.c.
{
     if ( !other->client ) {
         return;
     }
     BG_TouchJumpPad( &other->client->ps, &self->s );
 }
References BG_TouchJumpPad().
Referenced by SP_trigger_push().
trigger_teleporter_touch()
void trigger_teleporter_touch (gentity_t * self, gentity_t * other, trace_t * trace)
Definition at line 267 of file g_trigger.c.
{
     gentity_t   *dest;
     if ( !other->client ) {
         return;
     }
     if ( other->client->ps.pm_type == PM_DEAD ) {
         return;
     }
     // Spectators only?
     if ( ( self->spawnflags & 1 ) &&
         other->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         return;
     }
     dest =  G_PickTarget( self->target );
     if (!dest) {
         G_Printf ("Couldn't find teleporter destination\n");
         return;
     }
     TeleportPlayer( other, dest->s.origin, dest->s.angles );
 }
References G_PickTarget(), G_Printf(), PM_DEAD, TEAM_SPECTATOR, and TeleportPlayer().
Referenced by SP_trigger_teleport().
Use_Multi()
void Use_Multi (gentity_t * ent, gentity_t * other, gentity_t * activator)
Definition at line 76 of file g_trigger.c.
{
     multi_trigger( ent, activator );
 }
References multi_trigger().
Referenced by SP_trigger_multiple().
Use_target_push()
void Use_target_push (gentity_t * self, gentity_t * other, gentity_t * activator)
Definition at line 216 of file g_trigger.c.
{
     if ( !activator->client ) {
         return;
     }
     if ( activator->client->ps.pm_type != PM_NORMAL ) {
         return;
     }
     VectorCopy (self->s.origin2, activator->client->ps.velocity);
     // play fly sound every 1.5 seconds
     if ( activator->fly_sound_debounce_time < level.time ) {
         activator->fly_sound_debounce_time = level.time + 1500;
         G_Sound( activator, CHAN_AUTO, self->noise_index );
     }
 }
References CHAN_AUTO, G_Sound(), PM_NORMAL, and VectorCopy.
Referenced by SP_target_push().