ZEQ2-Lite: Iterators
Iterators
Macros
#define _GLIBCXX_MAKE_MOVE_ITERATOR(_Iter) (_Iter)
Functions
namespace __gnu_cxx _GLIBCXX_VISIBILITY (default)
Detailed Description
Abstractions for uniform iterating through various underlying types.
Macro Definition Documentation
_GLIBCXX_MAKE_MOVE_ITERATOR
#define _GLIBCXX_MAKE_MOVE_ITERATOR (_Iter) (_Iter)
#include <Tools/MinGW/include/c++/4.6.1/bits/stl_iterator.h>
Definition at line 1128 of file stl_iterator.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace __gnu_cxx _GLIBCXX_VISIBILITY (default)
#include <Tools/MinGW/include/c++/4.6.1/bits/stl_iterator.h>
Definition at line 688 of file stl_iterator.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
   // This iterator adapter is @a normal in the sense that it does not
   // change the semantics of any of the operators of its iterator
   // parameter.  Its primary purpose is to convert an iterator that is
   // not a class, e.g. a pointer, into an iterator that is a class.
   // The _Container parameter exists solely so that different containers
   // using this template can instantiate different types, even if the
   // _Iterator parameter is the same.
   using std::iterator_traits;
   using std::iterator;
   template<typename _Iterator, typename _Container>
     class __normal_iterator
     {
     protected:
       _Iterator _M_current;
       typedef iterator_traits<_Iterator>        __traits_type;
     public:
       typedef _Iterator                 iterator_type;
       typedef typename __traits_type::iterator_category iterator_category;
       typedef typename __traits_type::value_type    value_type;
       typedef typename __traits_type::difference_type   difference_type;
       typedef typename __traits_type::reference     reference;
       typedef typename __traits_type::pointer       pointer;
       _GLIBCXX_CONSTEXPR __normal_iterator() : _M_current(_Iterator()) { }
       explicit
       __normal_iterator(const _Iterator& __i) : _M_current(__i) { }
       // Allow iterator to const_iterator conversion
       template<typename _Iter>
         __normal_iterator(const __normal_iterator<_Iter,
               typename __enable_if<
                (std::__are_same<_Iter, typename _Container::pointer>::__value),
               _Container>::__type>& __i)
         : _M_current(__i.base()) { }
       // Forward iterator requirements
       reference
       operator*() const
       { return *_M_current; }
       pointer
       operator->() const
       { return _M_current; }
       __normal_iterator&
       operator++()
       {
     ++_M_current;
     return *this;
       }
       __normal_iterator
       operator++(int)
       { return __normal_iterator(_M_current++); }
       // Bidirectional iterator requirements
       __normal_iterator&
       operator--()
       {
     --_M_current;
     return *this;
       }
       __normal_iterator
       operator--(int)
       { return __normal_iterator(_M_current--); }
       // Random access iterator requirements
       reference
       operator[](const difference_type& __n) const
       { return _M_current[__n]; }
       __normal_iterator&
       operator+=(const difference_type& __n)
       { _M_current += __n; return *this; }
       __normal_iterator
       operator+(const difference_type& __n) const
       { return __normal_iterator(_M_current + __n); }
       __normal_iterator&
       operator-=(const difference_type& __n)
       { _M_current -= __n; return *this; }
       __normal_iterator
       operator-(const difference_type& __n) const
       { return __normal_iterator(_M_current - __n); }
       const _Iterator&
       base() const
       { return _M_current; }
     };
   // Note: In what follows, the left- and right-hand-side iterators are
   // allowed to vary in types (conceptually in cv-qualification) so that
   // comparison between cv-qualified and non-cv-qualified iterators be
   // valid.  However, the greedy and unfriendly operators in std::rel_ops
   // will make overload resolution ambiguous (when in scope) if we don't
   // provide overloads whose operands are of the same type.  Can someone
   // remind me what generic programming is about? -- Gaby
   // Forward iterator requirements
   template<typename _IteratorL, typename _IteratorR, typename _Container>
     inline bool
     operator==(const __normal_iterator<_IteratorL, _Container>& __lhs,
            const __normal_iterator<_IteratorR, _Container>& __rhs)
     { return __lhs.base() == __rhs.base(); }
   template<typename _Iterator, typename _Container>
     inline bool
     operator==(const __normal_iterator<_Iterator, _Container>& __lhs,
            const __normal_iterator<_Iterator, _Container>& __rhs)
     { return __lhs.base() == __rhs.base(); }
   template<typename _IteratorL, typename _IteratorR, typename _Container>
     inline bool
     operator!=(const __normal_iterator<_IteratorL, _Container>& __lhs,
            const __normal_iterator<_IteratorR, _Container>& __rhs)
     { return __lhs.base() != __rhs.base(); }
   template<typename _Iterator, typename _Container>
     inline bool
     operator!=(const __normal_iterator<_Iterator, _Container>& __lhs,
            const __normal_iterator<_Iterator, _Container>& __rhs)
     { return __lhs.base() != __rhs.base(); }
   // Random access iterator requirements
   template<typename _IteratorL, typename _IteratorR, typename _Container>
     inline bool
     operator<(const __normal_iterator<_IteratorL, _Container>& __lhs,
           const __normal_iterator<_IteratorR, _Container>& __rhs)
     { return __lhs.base() < __rhs.base(); }
   template<typename _Iterator, typename _Container>
     inline bool
     operator<(const __normal_iterator<_Iterator, _Container>& __lhs,
           const __normal_iterator<_Iterator, _Container>& __rhs)
     { return __lhs.base() < __rhs.base(); }
   template<typename _IteratorL, typename _IteratorR, typename _Container>
     inline bool
     operator>(const __normal_iterator<_IteratorL, _Container>& __lhs,
           const __normal_iterator<_IteratorR, _Container>& __rhs)
     { return __lhs.base() > __rhs.base(); }
   template<typename _Iterator, typename _Container>
     inline bool
     operator>(const __normal_iterator<_Iterator, _Container>& __lhs,
           const __normal_iterator<_Iterator, _Container>& __rhs)
     { return __lhs.base() > __rhs.base(); }
   template<typename _IteratorL, typename _IteratorR, typename _Container>
     inline bool
     operator<=(const __normal_iterator<_IteratorL, _Container>& __lhs,
            const __normal_iterator<_IteratorR, _Container>& __rhs)
     { return __lhs.base() <= __rhs.base(); }
   template<typename _Iterator, typename _Container>
     inline bool
     operator<=(const __normal_iterator<_Iterator, _Container>& __lhs,
            const __normal_iterator<_Iterator, _Container>& __rhs)
     { return __lhs.base() <= __rhs.base(); }
   template<typename _IteratorL, typename _IteratorR, typename _Container>
     inline bool
     operator>=(const __normal_iterator<_IteratorL, _Container>& __lhs,
            const __normal_iterator<_IteratorR, _Container>& __rhs)
     { return __lhs.base() >= __rhs.base(); }
   template<typename _Iterator, typename _Container>
     inline bool
     operator>=(const __normal_iterator<_Iterator, _Container>& __lhs,
            const __normal_iterator<_Iterator, _Container>& __rhs)
     { return __lhs.base() >= __rhs.base(); }
   // _GLIBCXX_RESOLVE_LIB_DEFECTS
   // According to the resolution of DR179 not only the various comparison
   // operators but also operator- must accept mixed iterator/const_iterator
   // parameters.
   template<typename _IteratorL, typename _IteratorR, typename _Container>
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
     // DR 685.
     inline auto
     operator-(const __normal_iterator<_IteratorL, _Container>& __lhs,
           const __normal_iterator<_IteratorR, _Container>& __rhs)
     -> decltype(__lhs.base() - __rhs.base())
 #else
     inline typename __normal_iterator<_IteratorL, _Container>::difference_type
     operator-(const __normal_iterator<_IteratorL, _Container>& __lhs,
           const __normal_iterator<_IteratorR, _Container>& __rhs)
 #endif
     { return __lhs.base() - __rhs.base(); }
   template<typename _Iterator, typename _Container>
     inline typename __normal_iterator<_Iterator, _Container>::difference_type
     operator-(const __normal_iterator<_Iterator, _Container>& __lhs,
           const __normal_iterator<_Iterator, _Container>& __rhs)
     { return __lhs.base() - __rhs.base(); }
   template<typename _Iterator, typename _Container>
     inline __normal_iterator<_Iterator, _Container>
     operator+(typename __normal_iterator<_Iterator, _Container>::difference_type
           __n, const __normal_iterator<_Iterator, _Container>& __i)
     { return __normal_iterator<_Iterator, _Container>(__i.base() + __n); }
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References std::__exception_ptr::operator!=(), operator+(), operator+=(), operator-(), operator-=(), __gnu_debug::operator<(), __gnu_debug::operator<=(), std::__exception_ptr::operator==(), __gnu_debug::operator>(), and __gnu_debug::operator>=().