ZEQ2-Lite: Engine/jpeg-8c/jquant1.c File Reference
jquant1.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_cquantizer
Macros
#define JPEG_INTERNALS
#define MAX_Q_COMPS 4 /* max components I can handle */
#define ODITHER_CELLS (ODITHER_SIZE*ODITHER_SIZE) /* # cells in matrix */
#define ODITHER_MASK (ODITHER_SIZE-1) /* mask for wrapping around counters */
#define ODITHER_SIZE 16 /* dimension of dither matrix */
Typedefs
typedef INT16 FSERROR
typedef FSERROR FAR * FSERRPTR
typedef int LOCFSERROR
typedef my_cquantizer * my_cquantize_ptr
typedef int ODITHER_MATRIX[ODITHER_SIZE][ODITHER_SIZE]
typedef int(* ODITHER_MATRIX_PTR)[ODITHER_SIZE]
Functions
alloc_fs_workspace (j_decompress_ptr cinfo)
color_quantize (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
color_quantize3 (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
create_colorindex (j_decompress_ptr cinfo)
create_colormap (j_decompress_ptr cinfo)
create_odither_tables (j_decompress_ptr cinfo)
finish_pass_1_quant (j_decompress_ptr cinfo)
jinit_1pass_quantizer (j_decompress_ptr cinfo)
largest_input_value (j_decompress_ptr cinfo, int ci, int j, int maxj)
make_odither_array (j_decompress_ptr cinfo, int ncolors)
new_color_map_1_quant (j_decompress_ptr cinfo)
output_value (j_decompress_ptr cinfo, int ci, int j, int maxj)
quantize3_ord_dither (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
quantize_fs_dither (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
quantize_ord_dither (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
select_ncolors (j_decompress_ptr cinfo, int Ncolors[])
start_pass_1_quant (j_decompress_ptr cinfo, boolean is_pre_scan)
Variables
static const UINT8 base_dither_matrix [ODITHER_SIZE][ODITHER_SIZE]
Macro Definition Documentation
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 13 of file jquant1.c.
MAX_Q_COMPS
#define MAX_Q_COMPS 4 /* max components I can handle */
Definition at line 140 of file jquant1.c.
ODITHER_CELLS
#define ODITHER_CELLS (ODITHER_SIZE*ODITHER_SIZE) /* # cells in matrix */
Definition at line 73 of file jquant1.c.
ODITHER_MASK
#define ODITHER_MASK (ODITHER_SIZE-1) /* mask for wrapping around counters */
Definition at line 74 of file jquant1.c.
ODITHER_SIZE
#define ODITHER_SIZE 16 /* dimension of dither matrix */
Definition at line 71 of file jquant1.c.
Typedef Documentation
FSERROR
typedef INT16 FSERROR
Definition at line 128 of file jquant1.c.
FSERRPTR
typedef FSERROR FAR* FSERRPTR
Definition at line 135 of file jquant1.c.
LOCFSERROR
typedef int LOCFSERROR
Definition at line 129 of file jquant1.c.
my_cquantize_ptr
typedef my_cquantizer* my_cquantize_ptr
Definition at line 167 of file jquant1.c.
ODITHER_MATRIX
typedef int ODITHER_MATRIX[ODITHER_SIZE][ODITHER_SIZE]
Definition at line 76 of file jquant1.c.
ODITHER_MATRIX_PTR
typedef int(* ODITHER_MATRIX_PTR)[ODITHER_SIZE]
Definition at line 77 of file jquant1.c.
Function Documentation
alloc_fs_workspace()
alloc_fs_workspace (j_decompress_ptr cinfo)
Definition at line 722 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   size_t arraysize;
   int i;
   arraysize = (size_t) ((cinfo->output_width + 2) * SIZEOF(FSERROR));
   for (i = 0; i < cinfo->out_color_components; i++) {
     cquantize->fserrors[i] = (FSERRPTR)
       (*cinfo->mem->alloc_large)((j_common_ptr) cinfo, JPOOL_IMAGE, arraysize);
   }
 }
References my_cquantizer::fserrors, JPOOL_IMAGE, and SIZEOF.
Referenced by jinit_1pass_quantizer(), and start_pass_1_quant().
color_quantize()
color_quantize (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
Definition at line 459 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   JSAMPARRAY colorindex = cquantize->colorindex;
   register int pixcode, ci;
   register JSAMPROW ptrin, ptrout;
   int row;
   JDIMENSION col;
   JDIMENSION width = cinfo->output_width;
   register int nc = cinfo->out_color_components;
   for (row = 0; row < num_rows; row++) {
     ptrin = input_buf[row];
     ptrout = output_buf[row];
     for (col = width; col > 0; col--) {
       pixcode = 0;
       for (ci = 0; ci < nc; ci++) {
     pixcode += GETJSAMPLE(colorindex[ci][GETJSAMPLE(*ptrin++)]);
       }
       *ptrout++ = (JSAMPLE) pixcode;
     }
   }
 }
References my_cquantizer::colorindex, for(), GETJSAMPLE, num_rows, and output_buf.
Referenced by start_pass_1_quant().
color_quantize3()
color_quantize3 (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
Definition at line 487 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   register int pixcode;
   register JSAMPROW ptrin, ptrout;
   JSAMPROW colorindex0 = cquantize->colorindex[0];
   JSAMPROW colorindex1 = cquantize->colorindex[1];
   JSAMPROW colorindex2 = cquantize->colorindex[2];
   int row;
   JDIMENSION col;
   JDIMENSION width = cinfo->output_width;
   for (row = 0; row < num_rows; row++) {
     ptrin = input_buf[row];
     ptrout = output_buf[row];
     for (col = width; col > 0; col--) {
       pixcode  = GETJSAMPLE(colorindex0[GETJSAMPLE(*ptrin++)]);
       pixcode += GETJSAMPLE(colorindex1[GETJSAMPLE(*ptrin++)]);
       pixcode += GETJSAMPLE(colorindex2[GETJSAMPLE(*ptrin++)]);
       *ptrout++ = (JSAMPLE) pixcode;
     }
   }
 }
References my_cquantizer::colorindex, for(), GETJSAMPLE, num_rows, and output_buf.
Referenced by start_pass_1_quant().
create_colorindex()
create_colorindex (j_decompress_ptr cinfo)
Definition at line 333 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   JSAMPROW indexptr;
   int i,j,k, nci, blksize, val, pad;
   /* For ordered dither, we pad the color index tables by MAXJSAMPLE in
    * each direction (input index values can be -MAXJSAMPLE .. 2*MAXJSAMPLE).
    * This is not necessary in the other dithering modes.  However, we
    * flag whether it was done in case user changes dithering mode.
    */
   if (cinfo->dither_mode == JDITHER_ORDERED) {
     pad = MAXJSAMPLE*2;
     cquantize->is_padded = TRUE;
   } else {
     pad = 0;
     cquantize->is_padded = FALSE;
   }
   cquantize->colorindex = (*cinfo->mem->alloc_sarray)
     ((j_common_ptr) cinfo, JPOOL_IMAGE,
      (JDIMENSION) (MAXJSAMPLE+1 + pad),
      (JDIMENSION) cinfo->out_color_components);
   /* blksize is number of adjacent repeated entries for a component */
   blksize = cquantize->sv_actual;
   for (i = 0; i < cinfo->out_color_components; i++) {
     /* fill in colorindex entries for i'th color component */
     nci = cquantize->Ncolors[i]; /* # of distinct values for this color */
     blksize = blksize / nci;
     /* adjust colorindex pointers to provide padding at negative indexes. */
     if (pad)
       cquantize->colorindex[i] += MAXJSAMPLE;
     /* in loop, val = index of current output value, */
     /* and k = largest j that maps to current val */
     indexptr = cquantize->colorindex[i];
     val = 0;
     k = largest_input_value(cinfo, i, 0, nci-1);
     for (j = 0; j <= MAXJSAMPLE; j++) {
       while (j > k)     /* advance val if past boundary */
     k = largest_input_value(cinfo, i, ++val, nci-1);
       /* premultiply so that no multiplication needed in main processing */
       indexptr[j] = (JSAMPLE) (val * blksize);
     }
     /* Pad at both ends if necessary */
     if (pad)
       for (j = 1; j <= MAXJSAMPLE; j++) {
     indexptr[-j] = indexptr[0];
     indexptr[MAXJSAMPLE+j] = indexptr[MAXJSAMPLE];
       }
   }
 }
References my_cquantizer::colorindex, FALSE, if(), my_cquantizer::is_padded, JDITHER_ORDERED, JPOOL_IMAGE, largest_input_value(), MAXJSAMPLE, my_cquantizer::Ncolors, my_cquantizer::sv_actual, TRUE, and val.
Referenced by jinit_1pass_quantizer(), and start_pass_1_quant().
create_colormap()
create_colormap (j_decompress_ptr cinfo)
Definition at line 273 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   JSAMPARRAY colormap;      /* Created colormap */
   int total_colors;     /* Number of distinct output colors */
   int i,j,k, nci, blksize, blkdist, ptr, val;
   /* Select number of colors for each component */
   total_colors = select_ncolors(cinfo, cquantize->Ncolors);
   /* Report selected color counts */
   if (cinfo->out_color_components == 3)
     TRACEMS4(cinfo, 1, JTRC_QUANT_3_NCOLORS,
          total_colors, cquantize->Ncolors[0],
          cquantize->Ncolors[1], cquantize->Ncolors[2]);
   else
     TRACEMS1(cinfo, 1, JTRC_QUANT_NCOLORS, total_colors);
   /* Allocate and fill in the colormap. */
   /* The colors are ordered in the map in standard row-major order, */
   /* i.e. rightmost (highest-indexed) color changes most rapidly. */
   colormap = (*cinfo->mem->alloc_sarray)
     ((j_common_ptr) cinfo, JPOOL_IMAGE,
      (JDIMENSION) total_colors, (JDIMENSION) cinfo->out_color_components);
   /* blksize is number of adjacent repeated entries for a component */
   /* blkdist is distance between groups of identical entries for a component */
   blkdist = total_colors;
   for (i = 0; i < cinfo->out_color_components; i++) {
     /* fill in colormap entries for i'th color component */
     nci = cquantize->Ncolors[i]; /* # of distinct values for this color */
     blksize = blkdist / nci;
     for (j = 0; j < nci; j++) {
       /* Compute j'th output value (out of nci) for component */
       val = output_value(cinfo, i, j, nci-1);
       /* Fill in all colormap entries that have this value of this component */
       for (ptr = j * blksize; ptr < total_colors; ptr += blkdist) {
     /* fill in blksize entries beginning at ptr */
     for (k = 0; k < blksize; k++)
       colormap[i][ptr+k] = (JSAMPLE) val;
       }
     }
     blkdist = blksize;      /* blksize of this color is blkdist of next */
   }
   /* Save the colormap in private storage,
    * where it will survive color quantization mode changes.
    */
   cquantize->sv_colormap = colormap;
   cquantize->sv_actual = total_colors;
 }
References JPOOL_IMAGE, my_cquantizer::Ncolors, output_value(), ptr(), select_ncolors(), my_cquantizer::sv_actual, my_cquantizer::sv_colormap, TRACEMS1, TRACEMS4, and val.
Referenced by jinit_1pass_quantizer().
create_odither_tables()
create_odither_tables (j_decompress_ptr cinfo)
Definition at line 432 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   ODITHER_MATRIX_PTR odither;
   int i, j, nci;
   for (i = 0; i < cinfo->out_color_components; i++) {
     nci = cquantize->Ncolors[i]; /* # of distinct values for this color */
     odither = NULL;     /* search for matching prior component */
     for (j = 0; j < i; j++) {
       if (nci == cquantize->Ncolors[j]) {
     odither = cquantize->odither[j];
     break;
       }
     }
     if (odither == NULL)    /* need a new table? */
       odither = make_odither_array(cinfo, nci);
     cquantize->odither[i] = odither;
   }
 }
References for(), make_odither_array(), my_cquantizer::Ncolors, NULL, and my_cquantizer::odither.
Referenced by start_pass_1_quant().
finish_pass_1_quant()
finish_pass_1_quant (j_decompress_ptr cinfo)
Definition at line 798 of file jquant1.c.
 {
   /* no work in 1-pass case */
 }
Referenced by jinit_1pass_quantizer().
jinit_1pass_quantizer()
jinit_1pass_quantizer (j_decompress_ptr cinfo)
Definition at line 821 of file jquant1.c.
 {
   my_cquantize_ptr cquantize;
   cquantize = (my_cquantize_ptr)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 SIZEOF(my_cquantizer));
   cinfo->cquantize = (struct jpeg_color_quantizer *) cquantize;
   cquantize->pub.start_pass = start_pass_1_quant;
   cquantize->pub.finish_pass = finish_pass_1_quant;
   cquantize->pub.new_color_map = new_color_map_1_quant;
   cquantize->fserrors[0] = NULL; /* Flag FS workspace not allocated */
   cquantize->odither[0] = NULL; /* Also flag odither arrays not allocated */
   /* Make sure my internal arrays won't overflow */
   if (cinfo->out_color_components > MAX_Q_COMPS)
     ERREXIT1(cinfo, JERR_QUANT_COMPONENTS, MAX_Q_COMPS);
   /* Make sure colormap indexes can be represented by JSAMPLEs */
   if (cinfo->desired_number_of_colors > (MAXJSAMPLE+1))
     ERREXIT1(cinfo, JERR_QUANT_MANY_COLORS, MAXJSAMPLE+1);
   /* Create the colormap and color index table. */
   create_colormap(cinfo);
   create_colorindex(cinfo);
   /* Allocate Floyd-Steinberg workspace now if requested.
    * We do this now since it is FAR storage and may affect the memory
    * manager's space calculations.  If the user changes to FS dither
    * mode in a later pass, we will allocate the space then, and will
    * possibly overrun the max_memory_to_use setting.
    */
   if (cinfo->dither_mode == JDITHER_FS)
     alloc_fs_workspace(cinfo);
 }
References alloc_fs_workspace(), create_colorindex(), create_colormap(), ERREXIT1, finish_pass_1_quant(), my_cquantizer::fserrors, JDITHER_FS, JPOOL_IMAGE, MAX_Q_COMPS, MAXJSAMPLE, new_color_map_1_quant(), NULL, my_cquantizer::odither, my_cquantizer::pub, SIZEOF, and start_pass_1_quant().
Referenced by master_selection().
largest_input_value()
largest_input_value (j_decompress_ptr cinfo, int ci, int j, int maxj)
Definition at line 259 of file jquant1.c.
 {
   /* Breakpoints are halfway between values returned by output_value */
   return (int) (((INT32) (2*j + 1) * MAXJSAMPLE + maxj) / (2*maxj));
 }
References MAXJSAMPLE.
Referenced by create_colorindex().
make_odither_array()
make_odither_array (j_decompress_ptr cinfo, int ncolors)
Definition at line 396 of file jquant1.c.
 {
   ODITHER_MATRIX_PTR odither;
   int j,k;
   INT32 num,den;
   odither = (ODITHER_MATRIX_PTR)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 SIZEOF(ODITHER_MATRIX));
   /* The inter-value distance for this color is MAXJSAMPLE/(ncolors-1).
    * Hence the dither value for the matrix cell with fill order f
    * (f=0..N-1) should be (N-1-2*f)/(2*N) * MAXJSAMPLE/(ncolors-1).
    * On 16-bit-int machine, be careful to avoid overflow.
    */
   den = 2 * ODITHER_CELLS * ((INT32) (ncolors - 1));
   for (j = 0; j < ODITHER_SIZE; j++) {
     for (k = 0; k < ODITHER_SIZE; k++) {
       num = ((INT32) (ODITHER_CELLS-1 - 2*((int)base_dither_matrix[j][k])))
         * MAXJSAMPLE;
       /* Ensure round towards zero despite C's lack of consistency
        * about rounding negative values in integer division...
        */
       odither[j][k] = (int) (num<0 ? -((-num)/den) : num/den);
     }
   }
   return odither;
 }
References base_dither_matrix, den, int, JPOOL_IMAGE, MAXJSAMPLE, ODITHER_CELLS, ODITHER_SIZE, and SIZEOF.
Referenced by create_odither_tables().
new_color_map_1_quant()
new_color_map_1_quant (j_decompress_ptr cinfo)
Definition at line 810 of file jquant1.c.
 {
   ERREXIT(cinfo, JERR_MODE_CHANGE);
 }
References ERREXIT.
Referenced by jinit_1pass_quantizer().
output_value()
output_value (j_decompress_ptr cinfo, int ci, int j, int maxj)
Definition at line 245 of file jquant1.c.
 {
   /* We always provide values 0 and MAXJSAMPLE for each component;
    * any additional values are equally spaced between these limits.
    * (Forcing the upper and lower values to the limits ensures that
    * dithering can't produce a color outside the selected gamut.)
    */
   return (int) (((INT32) j * MAXJSAMPLE + maxj/2) / maxj);
 }
References MAXJSAMPLE.
Referenced by create_colormap().
quantize3_ord_dither()
quantize3_ord_dither (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
Definition at line 565 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   register int pixcode;
   register JSAMPROW input_ptr;
   register JSAMPROW output_ptr;
   JSAMPROW colorindex0 = cquantize->colorindex[0];
   JSAMPROW colorindex1 = cquantize->colorindex[1];
   JSAMPROW colorindex2 = cquantize->colorindex[2];
   int * dither0;        /* points to active row of dither matrix */
   int * dither1;
   int * dither2;
   int row_index, col_index; /* current indexes into dither matrix */
   int row;
   JDIMENSION col;
   JDIMENSION width = cinfo->output_width;
   for (row = 0; row < num_rows; row++) {
     row_index = cquantize->row_index;
     input_ptr = input_buf[row];
     output_ptr = output_buf[row];
     dither0 = cquantize->odither[0][row_index];
     dither1 = cquantize->odither[1][row_index];
     dither2 = cquantize->odither[2][row_index];
     col_index = 0;
     for (col = width; col > 0; col--) {
       pixcode  = GETJSAMPLE(colorindex0[GETJSAMPLE(*input_ptr++) +
                     dither0[col_index]]);
       pixcode += GETJSAMPLE(colorindex1[GETJSAMPLE(*input_ptr++) +
                     dither1[col_index]]);
       pixcode += GETJSAMPLE(colorindex2[GETJSAMPLE(*input_ptr++) +
                     dither2[col_index]]);
       *output_ptr++ = (JSAMPLE) pixcode;
       col_index = (col_index + 1) & ODITHER_MASK;
     }
     row_index = (row_index + 1) & ODITHER_MASK;
     cquantize->row_index = row_index;
   }
 }
References my_cquantizer::colorindex, for(), GETJSAMPLE, num_rows, my_cquantizer::odither, ODITHER_MASK, output_buf, and my_cquantizer::row_index.
Referenced by start_pass_1_quant().
quantize_fs_dither()
quantize_fs_dither (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
Definition at line 610 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   register LOCFSERROR cur;  /* current error or pixel value */
   LOCFSERROR belowerr;      /* error for pixel below cur */
   LOCFSERROR bpreverr;      /* error for below/prev col */
   LOCFSERROR bnexterr;      /* error for below/next col */
   LOCFSERROR delta;
   register FSERRPTR errorptr;   /* => fserrors[] at column before current */
   register JSAMPROW input_ptr;
   register JSAMPROW output_ptr;
   JSAMPROW colorindex_ci;
   JSAMPROW colormap_ci;
   int pixcode;
   int nc = cinfo->out_color_components;
   int dir;          /* 1 for left-to-right, -1 for right-to-left */
   int dirnc;            /* dir * nc */
   int ci;
   int row;
   JDIMENSION col;
   JDIMENSION width = cinfo->output_width;
   JSAMPLE *range_limit = cinfo->sample_range_limit;
   SHIFT_TEMPS
   for (row = 0; row < num_rows; row++) {
     /* Initialize output values to 0 so can process components separately */
     jzero_far((void FAR *) output_buf[row],
           (size_t) (width * SIZEOF(JSAMPLE)));
     for (ci = 0; ci < nc; ci++) {
       input_ptr = input_buf[row] + ci;
       output_ptr = output_buf[row];
       if (cquantize->on_odd_row) {
     /* work right to left in this row */
     input_ptr += (width-1) * nc; /* so point to rightmost pixel */
     output_ptr += width-1;
     dir = -1;
     dirnc = -nc;
     errorptr = cquantize->fserrors[ci] + (width+1); /* => entry after last column */
       } else {
     /* work left to right in this row */
     dir = 1;
     dirnc = nc;
     errorptr = cquantize->fserrors[ci]; /* => entry before first column */
       }
       colorindex_ci = cquantize->colorindex[ci];
       colormap_ci = cquantize->sv_colormap[ci];
       /* Preset error values: no error propagated to first pixel from left */
       cur = 0;
       /* and no error propagated to row below yet */
       belowerr = bpreverr = 0;
       for (col = width; col > 0; col--) {
     /* cur holds the error propagated from the previous pixel on the
      * current line.  Add the error propagated from the previous line
      * to form the complete error correction term for this pixel, and
      * round the error term (which is expressed * 16) to an integer.
      * RIGHT_SHIFT rounds towards minus infinity, so adding 8 is correct
      * for either sign of the error value.
      * Note: errorptr points to *previous* column's array entry.
      */
     cur = RIGHT_SHIFT(cur + errorptr[dir] + 8, 4);
     /* Form pixel value + error, and range-limit to 0..MAXJSAMPLE.
      * The maximum error is +- MAXJSAMPLE; this sets the required size
      * of the range_limit array.
      */
     cur += GETJSAMPLE(*input_ptr);
     cur = GETJSAMPLE(range_limit[cur]);
     /* Select output value, accumulate into output code for this pixel */
     pixcode = GETJSAMPLE(colorindex_ci[cur]);
     *output_ptr += (JSAMPLE) pixcode;
     /* Compute actual representation error at this pixel */
     /* Note: we can do this even though we don't have the final */
     /* pixel code, because the colormap is orthogonal. */
     cur -= GETJSAMPLE(colormap_ci[pixcode]);
     /* Compute error fractions to be propagated to adjacent pixels.
      * Add these into the running sums, and simultaneously shift the
      * next-line error sums left by 1 column.
      */
     bnexterr = cur;
     delta = cur * 2;
     cur += delta;       /* form error * 3 */
     errorptr[0] = (FSERROR) (bpreverr + cur);
     cur += delta;       /* form error * 5 */
     bpreverr = belowerr + cur;
     belowerr = bnexterr;
     cur += delta;       /* form error * 7 */
     /* At this point cur contains the 7/16 error value to be propagated
      * to the next pixel on the current line, and all the errors for the
      * next line have been shifted over. We are therefore ready to move on.
      */
     input_ptr += dirnc; /* advance input ptr to next column */
     output_ptr += dir;  /* advance output ptr to next column */
     errorptr += dir;    /* advance errorptr to current column */
       }
       /* Post-loop cleanup: we must unload the final error value into the
        * final fserrors[] entry.  Note we need not unload belowerr because
        * it is for the dummy column before or after the actual array.
        */
       errorptr[0] = (FSERROR) bpreverr; /* unload prev err into array */
     }
     cquantize->on_odd_row = (cquantize->on_odd_row ? FALSE : TRUE);
   }
 }
References my_cquantizer::colorindex, dir, FALSE, FAR, for(), my_cquantizer::fserrors, GETJSAMPLE, jzero_far(), num_rows, my_cquantizer::on_odd_row, output_buf, RIGHT_SHIFT, SHIFT_TEMPS, SIZEOF, my_cquantizer::sv_colormap, and TRUE.
Referenced by start_pass_1_quant().
quantize_ord_dither()
quantize_ord_dither (j_decompress_ptr cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows)
Definition at line 515 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   register JSAMPROW input_ptr;
   register JSAMPROW output_ptr;
   JSAMPROW colorindex_ci;
   int * dither;         /* points to active row of dither matrix */
   int row_index, col_index; /* current indexes into dither matrix */
   int nc = cinfo->out_color_components;
   int ci;
   int row;
   JDIMENSION col;
   JDIMENSION width = cinfo->output_width;
   for (row = 0; row < num_rows; row++) {
     /* Initialize output values to 0 so can process components separately */
     jzero_far((void FAR *) output_buf[row],
           (size_t) (width * SIZEOF(JSAMPLE)));
     row_index = cquantize->row_index;
     for (ci = 0; ci < nc; ci++) {
       input_ptr = input_buf[row] + ci;
       output_ptr = output_buf[row];
       colorindex_ci = cquantize->colorindex[ci];
       dither = cquantize->odither[ci][row_index];
       col_index = 0;
       for (col = width; col > 0; col--) {
     /* Form pixel value + dither, range-limit to 0..MAXJSAMPLE,
      * select output value, accumulate into output code for this pixel.
      * Range-limiting need not be done explicitly, as we have extended
      * the colorindex table to produce the right answers for out-of-range
      * inputs.  The maximum dither is +- MAXJSAMPLE; this sets the
      * required amount of padding.
      */
     *output_ptr += colorindex_ci[GETJSAMPLE(*input_ptr)+dither[col_index]];
     input_ptr += nc;
     output_ptr++;
     col_index = (col_index + 1) & ODITHER_MASK;
       }
     }
     /* Advance row index for next row */
     row_index = (row_index + 1) & ODITHER_MASK;
     cquantize->row_index = row_index;
   }
 }
References my_cquantizer::colorindex, FAR, for(), GETJSAMPLE, jzero_far(), num_rows, my_cquantizer::odither, ODITHER_MASK, output_buf, my_cquantizer::row_index, and SIZEOF.
Referenced by start_pass_1_quant().
select_ncolors()
select_ncolors (j_decompress_ptr cinfo, int Ncolors[])
Definition at line 186 of file jquant1.c.
 {
   int nc = cinfo->out_color_components; /* number of color components */
   int max_colors = cinfo->desired_number_of_colors;
   int total_colors, iroot, i, j;
   boolean changed;
   long temp;
   static const int RGB_order[3] = { RGB_GREEN, RGB_RED, RGB_BLUE };
   /* We can allocate at least the nc'th root of max_colors per component. */
   /* Compute floor(nc'th root of max_colors). */
   iroot = 1;
   do {
     iroot++;
     temp = iroot;       /* set temp = iroot ** nc */
     for (i = 1; i < nc; i++)
       temp *= iroot;
   } while (temp <= (long) max_colors); /* repeat till iroot exceeds root */
   iroot--;          /* now iroot = floor(root) */
   /* Must have at least 2 color values per component */
   if (iroot < 2)
     ERREXIT1(cinfo, JERR_QUANT_FEW_COLORS, (int) temp);
   /* Initialize to iroot color values for each component */
   total_colors = 1;
   for (i = 0; i < nc; i++) {
     Ncolors[i] = iroot;
     total_colors *= iroot;
   }
   /* We may be able to increment the count for one or more components without
    * exceeding max_colors, though we know not all can be incremented.
    * Sometimes, the first component can be incremented more than once!
    * (Example: for 16 colors, we start at 2*2*2, go to 3*2*2, then 4*2*2.)
    * In RGB colorspace, try to increment G first, then R, then B.
    */
   do {
     changed = FALSE;
     for (i = 0; i < nc; i++) {
       j = (cinfo->out_color_space == JCS_RGB ? RGB_order[i] : i);
       /* calculate new total_colors if Ncolors[j] is incremented */
       temp = total_colors / Ncolors[j];
       temp *= Ncolors[j]+1; /* done in long arith to avoid oflo */
       if (temp > (long) max_colors)
     break;          /* won't fit, done with this pass */
       Ncolors[j]++;     /* OK, apply the increment */
       total_colors = (int) temp;
       changed = TRUE;
     }
   } while (changed);
   return total_colors;
 }
References ERREXIT1, FALSE, int, JCS_RGB, and TRUE.
Referenced by create_colormap().
start_pass_1_quant()
start_pass_1_quant (j_decompress_ptr cinfo, boolean is_pre_scan)
Definition at line 741 of file jquant1.c.
 {
   my_cquantize_ptr cquantize = (my_cquantize_ptr) cinfo->cquantize;
   size_t arraysize;
   int i;
   /* Install my colormap. */
   cinfo->colormap = cquantize->sv_colormap;
   cinfo->actual_number_of_colors = cquantize->sv_actual;
   /* Initialize for desired dithering mode. */
   switch (cinfo->dither_mode) {
   case JDITHER_NONE:
     if (cinfo->out_color_components == 3)
       cquantize->pub.color_quantize = color_quantize3;
     else
       cquantize->pub.color_quantize = color_quantize;
     break;
   case JDITHER_ORDERED:
     if (cinfo->out_color_components == 3)
       cquantize->pub.color_quantize = quantize3_ord_dither;
     else
       cquantize->pub.color_quantize = quantize_ord_dither;
     cquantize->row_index = 0;   /* initialize state for ordered dither */
     /* If user changed to ordered dither from another mode,
      * we must recreate the color index table with padding.
      * This will cost extra space, but probably isn't very likely.
      */
     if (! cquantize->is_padded)
       create_colorindex(cinfo);
     /* Create ordered-dither tables if we didn't already. */
     if (cquantize->odither[0] == NULL)
       create_odither_tables(cinfo);
     break;
   case JDITHER_FS:
     cquantize->pub.color_quantize = quantize_fs_dither;
     cquantize->on_odd_row = FALSE; /* initialize state for F-S dither */
     /* Allocate Floyd-Steinberg workspace if didn't already. */
     if (cquantize->fserrors[0] == NULL)
       alloc_fs_workspace(cinfo);
     /* Initialize the propagated errors to zero. */
     arraysize = (size_t) ((cinfo->output_width + 2) * SIZEOF(FSERROR));
     for (i = 0; i < cinfo->out_color_components; i++)
       jzero_far((void FAR *) cquantize->fserrors[i], arraysize);
     break;
   default:
     ERREXIT(cinfo, JERR_NOT_COMPILED);
     break;
   }
 }
References alloc_fs_workspace(), color_quantize(), color_quantize3(), create_colorindex(), create_odither_tables(), ERREXIT, FALSE, FAR, my_cquantizer::fserrors, my_cquantizer::is_padded, JDITHER_FS, JDITHER_NONE, JDITHER_ORDERED, jzero_far(), NULL, my_cquantizer::odither, my_cquantizer::on_odd_row, my_cquantizer::pub, quantize3_ord_dither(), quantize_fs_dither(), quantize_ord_dither(), my_cquantizer::row_index, SIZEOF, my_cquantizer::sv_actual, my_cquantizer::sv_colormap, and switch().
Referenced by jinit_1pass_quantizer().
Variable Documentation
base_dither_matrix
const UINT8 base_dither_matrix[ODITHER_SIZE][ODITHER_SIZE] static
Initial value:
= {
  {   0,192, 48,240, 12,204, 60,252,  3,195, 51,243, 15,207, 63,255 },
  { 128, 64,176,112,140, 76,188,124,131, 67,179,115,143, 79,191,127 },
  {  32,224, 16,208, 44,236, 28,220, 35,227, 19,211, 47,239, 31,223 },
  { 160, 96,144, 80,172,108,156, 92,163, 99,147, 83,175,111,159, 95 },
  {   8,200, 56,248,  4,196, 52,244, 11,203, 59,251,  7,199, 55,247 },
  { 136, 72,184,120,132, 68,180,116,139, 75,187,123,135, 71,183,119 },
  {  40,232, 24,216, 36,228, 20,212, 43,235, 27,219, 39,231, 23,215 },
  { 168,104,152, 88,164,100,148, 84,171,107,155, 91,167,103,151, 87 },
  {   2,194, 50,242, 14,206, 62,254,  1,193, 49,241, 13,205, 61,253 },
  { 130, 66,178,114,142, 78,190,126,129, 65,177,113,141, 77,189,125 },
  {  34,226, 18,210, 46,238, 30,222, 33,225, 17,209, 45,237, 29,221 },
  { 162, 98,146, 82,174,110,158, 94,161, 97,145, 81,173,109,157, 93 },
  {  10,202, 58,250,  6,198, 54,246,  9,201, 57,249,  5,197, 53,245 },
  { 138, 74,186,122,134, 70,182,118,137, 73,185,121,133, 69,181,117 },
  {  42,234, 26,218, 38,230, 22,214, 41,233, 25,217, 37,229, 21,213 },
  { 170,106,154, 90,166,102,150, 86,169,105,153, 89,165,101,149, 85 }
}
Definition at line 79 of file jquant1.c.
Referenced by make_odither_array().