ZEQ2-Lite: Source/Shared/cmd.c File Reference
cmd.c File Reference
#include "q_shared.h"
#include "qcommon.h"
Data Structures
struct cmd_function_s
struct cmd_t
Macros
#define MAX_CMD_BUFFER 16384
#define MAX_CMD_LINE 1024
Functions
void Cbuf_AddText (const char *text)
void Cbuf_Execute (void)
void Cbuf_ExecuteText (int exec_when, const char *text)
void Cbuf_Init (void)
void Cbuf_InsertText (const char *text)
void Cmd_AddCommand (const char *cmd_name, xcommand_t function)
int Cmd_Argc (void)
char * Cmd_Args (void)
void Cmd_Args_Sanitize (void)
void Cmd_ArgsBuffer (char *buffer, int bufferLength)
char * Cmd_ArgsFrom (int arg)
char * Cmd_Argv (int arg)
void Cmd_ArgvBuffer (int arg, char *buffer, int bufferLength)
char * Cmd_Cmd (void)
void Cmd_CommandCompletion (void(*callback)(const char *s))
void Cmd_CompleteArgument (const char *command, char *args, int argNum)
void Cmd_CompleteCfgName (char *args, int argNum)
void Cmd_Echo_f (void)
void Cmd_Exec_f (void)
void Cmd_ExecuteString (const char *text)
cmd_function_t * Cmd_FindCommand (const char *cmd_name)
void Cmd_Init (void)
void Cmd_List_f (void)
void Cmd_RemoveCommand (const char *cmd_name)
void Cmd_RemoveCommandSafe (const char *cmd_name)
void Cmd_SetCommandCompletionFunc (const char *command, completionFunc_t complete)
void Cmd_TokenizeString (const char *text_in)
static void Cmd_TokenizeString2 (const char *text_in, qboolean ignoreQuotes)
void Cmd_TokenizeStringIgnoreQuotes (const char *text_in)
void Cmd_Vstr_f (void)
void Cmd_Wait_f (void)
Variables
static int cmd_argc
static char * cmd_argv [MAX_STRING_TOKENS]
static char cmd_cmd [BIG_INFO_STRING]
static cmd_function_t * cmd_functions
cmd_t cmd_text
byte cmd_text_buf [MAX_CMD_BUFFER]
static char cmd_tokenized [BIG_INFO_STRING+MAX_STRING_TOKENS]
int cmd_wait
Macro Definition Documentation
MAX_CMD_BUFFER
#define MAX_CMD_BUFFER 16384
Definition at line 27 of file cmd.c.
MAX_CMD_LINE
#define MAX_CMD_LINE 1024
Definition at line 28 of file cmd.c.
Function Documentation
Cbuf_AddText()
void Cbuf_AddText (const char * text)
Definition at line 90 of file cmd.c.
{
     int     l;
     l = strlen (text);
     if (cmd_text.cursize + l >= cmd_text.maxsize)
     {
         Com_Printf ("Cbuf_AddText: overflow\n");
         return;
     }
     Com_Memcpy(&cmd_text.data[cmd_text.cursize], text, l);
     cmd_text.cursize += l;
 }
References cmd_text, Com_Memcpy, Com_Printf(), cmd_t::cursize, cmd_t::data, and cmd_t::maxsize.
Referenced by Cbuf_ExecuteText(), CL_CgameSystemCalls(), CL_FirstSnapshot(), CL_GetServerCommand(), CL_NextDemo(), CL_ParseBinding(), CL_Reconnect_f(), CL_StartDemoLoop(), Com_AddStartupCommands(), Com_EventLoop(), Com_Init(), Console_Key(), FS_Restart(), IN_Frame(), SV_Frame(), and SV_Init().
Cbuf_Execute()
void Cbuf_Execute (void)
Definition at line 172 of file cmd.c.
 {
     int     i;
     char    *text;
     char    line[MAX_CMD_LINE];
     int     quotes;
     // This will keep // style comments all on one line by not breaking on
     // a semicolon.  It will keep /* ... */ style comments all on one line by not
     // breaking it for semicolon or newline.
     qboolean in_star_comment = qfalse;
     qboolean in_slash_comment = qfalse;
     while (cmd_text.cursize)
     {
         if ( cmd_wait > 0 ) {
             // skip out while text still remains in buffer, leaving it
             // for next frame
             cmd_wait--;
             break;
         }
         // find a \n or ; line break or comment: // or /* */
         text = (char *)cmd_text.data;
         quotes = 0;
         for (i=0 ; i< cmd_text.cursize ; i++)
         {
             if (text[i] == '"')
                 quotes++;
             if ( !(quotes&1)) {
                 if (i < cmd_text.cursize - 1) {
                     if (! in_star_comment && text[i] == '/' && text[i+1] == '/')
                         in_slash_comment = qtrue;
                     else if (! in_slash_comment && text[i] == '/' && text[i+1] == '*')
                         in_star_comment = qtrue;
                     else if (in_star_comment && text[i] == '*' && text[i+1] == '/') {
                         in_star_comment = qfalse;
                         // If we are in a star comment, then the part after it is valid
                         // Note: This will cause it to NUL out the terminating '/'
                         // but ExecuteString doesn't require it anyway.
                         i++;
                         break;
                     }
                 }
                 if (! in_slash_comment && ! in_star_comment && text[i] == ';')
                     break;
             }
             if (! in_star_comment && (text[i] == '\n' || text[i] == '\r')) {
                 in_slash_comment = qfalse;
                 break;
             }
         }
         if( i >= (MAX_CMD_LINE - 1)) {
             i = MAX_CMD_LINE - 1;
         }
         Com_Memcpy (line, text, i);
         line[i] = 0;
 // delete the text from the command buffer and move remaining commands down
 // this is necessary because commands (exec) can insert data at the
 // beginning of the text buffer
         if (i == cmd_text.cursize)
             cmd_text.cursize = 0;
         else
         {
             i++;
             cmd_text.cursize -= i;
             memmove (text, text+i, cmd_text.cursize);
         }
 // execute the command line
         Cmd_ExecuteString (line);
     }
 }
References Cmd_ExecuteString(), cmd_text, cmd_wait, Com_Memcpy, cmd_t::cursize, cmd_t::data, line, MAX_CMD_LINE, memmove(), qfalse, and qtrue.
Referenced by Cbuf_ExecuteText(), CL_NextDemo(), Com_ExecuteCfg(), and Com_Frame().
Cbuf_ExecuteText()
void Cbuf_ExecuteText (int exec_when, const char * text)
Definition at line 143 of file cmd.c.
 {
     switch (exec_when)
     {
     case EXEC_NOW:
         if (text && strlen(text) > 0) {
             Com_DPrintf(S_COLOR_YELLOW "EXEC_NOW %s\n", text);
             Cmd_ExecuteString (text);
         } else {
             Cbuf_Execute();
             Com_DPrintf(S_COLOR_YELLOW "EXEC_NOW %s\n", cmd_text.data);
         }
         break;
     case EXEC_INSERT:
         Cbuf_InsertText (text);
         break;
     case EXEC_APPEND:
         Cbuf_AddText (text);
         break;
     default:
         Com_Error (ERR_FATAL, "Cbuf_ExecuteText: bad exec_when");
     }
 }
References Cbuf_AddText(), Cbuf_Execute(), Cbuf_InsertText(), Cmd_ExecuteString(), cmd_text, Com_DPrintf(), Com_Error(), cmd_t::data, ERR_FATAL, EXEC_APPEND, EXEC_INSERT, EXEC_NOW, and S_COLOR_YELLOW.
Referenced by CL_Frame(), CL_InitRef(), CL_UISystemCalls(), Com_ExecuteCfg(), Com_ReadFromPipe(), IN_ProcessEvents(), RoQShutdown(), and SV_GameSystemCalls().
Cbuf_Init()
void Cbuf_Init (void)
Definition at line 76 of file cmd.c.
 {
     cmd_text.data = cmd_text_buf;
     cmd_text.maxsize = MAX_CMD_BUFFER;
     cmd_text.cursize = 0;
 }
References cmd_text, cmd_text_buf, cmd_t::cursize, cmd_t::data, MAX_CMD_BUFFER, and cmd_t::maxsize.
Referenced by Com_Init().
Cbuf_InsertText()
void Cbuf_InsertText (const char * text)
Definition at line 113 of file cmd.c.
{
     int     len;
     int     i;
     len = strlen( text ) + 1;
     if ( len + cmd_text.cursize > cmd_text.maxsize ) {
         Com_Printf( "Cbuf_InsertText overflowed\n" );
         return;
     }
     // move the existing command text
     for ( i = cmd_text.cursize - 1 ; i >= 0 ; i-- ) {
         cmd_text.data[ i + len ] = cmd_text.data[ i ];
     }
     // copy the new text in
     Com_Memcpy( cmd_text.data, text, len - 1 );
     // add a \n
     cmd_text.data[ len - 1 ] = '\n';
     cmd_text.cursize += len;
 }
References cmd_text, Com_Memcpy, Com_Printf(), cmd_t::cursize, cmd_t::data, and cmd_t::maxsize.
Referenced by Cbuf_ExecuteText(), Cmd_Exec_f(), and Cmd_Vstr_f().
Cmd_AddCommand()
void Cmd_AddCommand (const char * cmd_name, xcommand_t function)
Definition at line 633 of file cmd.c.
{
     cmd_function_t  *cmd;
     // fail if the command already exists
     if( Cmd_FindCommand( cmd_name ) )
     {
         // allow completion-only commands to be silently doubled
         if( function != NULL )
             Com_Printf( "Cmd_AddCommand: %s already defined\n", cmd_name );
         return;
     }
     // use a small malloc to avoid zone fragmentation
     cmd = S_Malloc (sizeof(cmd_function_t));
     cmd->name = CopyString( cmd_name );
     cmd->function = function;
     cmd->complete = NULL;
     cmd->next = cmd_functions;
     cmd_functions = cmd;
 }
References Cmd_FindCommand(), cmd_functions, Com_Printf(), CopyString(), NULL, and S_Malloc.
Referenced by CL_AddCgameCommand(), CL_FirstSnapshot(), CL_Init(), CL_InitInput(), CL_InitKeyCommands(), CL_InitRef(), Cmd_Init(), Com_Init(), Com_InitHunkMemory(), Con_Init(), Cvar_Init(), FS_Startup(), NET_Init(), S_Init(), SV_AddOperatorCommands(), Sys_Init(), and VM_Init().
Cmd_Argc()
int Cmd_Argc (void)
Definition at line 356 of file cmd.c.
{
     return cmd_argc;
 }
References cmd_argc.
Referenced by CL_CgameSystemCalls(), CL_Connect_f(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_InitRef(), CL_Ping_f(), CL_PlayDemo_f(), CL_Record_f(), CL_ServerStatus_f(), CL_UISystemCalls(), CL_Video_f(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_List_f(), Cmd_Vstr_f(), Cmd_Wait_f(), Com_Error_f(), Com_Freeze_f(), Com_Meminfo_f(), Com_Setenv_f(), Com_WriteConfig_f(), Con_Dump_f(), Cvar_Command(), Cvar_List_f(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Field_CompleteCommand(), FS_Dir_f(), FS_NewDir_f(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), FS_TouchFile_f(), Key_Bind_f(), Key_Unbind_f(), S_Music_f(), S_Play_f(), SV_AddBanToList(), SV_ConSay_f(), SV_DelBanFromList(), SV_DumpUser_f(), SV_GameSystemCalls(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Kick_f(), SV_KickNum_f(), SV_MapRestart_f(), SV_VerifyPaks_f(), and SV_WriteDownloadToClient().
Cmd_Args()
char* Cmd_Args (void)
Definition at line 392 of file cmd.c.
{
     static  char        cmd_args[MAX_STRING_CHARS];
     int     i;
     cmd_args[0] = 0;
     for ( i = 1 ; i < cmd_argc ; i++ ) {
         strcat( cmd_args, cmd_argv[i] );
         if ( i != cmd_argc-1 ) {
             strcat( cmd_args, " " );
         }
     }
     return cmd_args;
 }
References cmd_argc, cmd_argv, and MAX_STRING_CHARS.
Referenced by CL_ForwardToServer_f(), Cmd_ArgsBuffer(), Cmd_Echo_f(), Com_Quit_f(), Cvar_Command(), and SV_ConSay_f().
Cmd_Args_Sanitize()
void Cmd_Args_Sanitize (void)
Definition at line 464 of file cmd.c.
 {
     int i;
     for(i = 1; i < cmd_argc; i++)
     {
         char *c = cmd_argv[i];
         if(strlen(c) > MAX_CVAR_VALUE_STRING - 1)
             c[MAX_CVAR_VALUE_STRING - 1] = '\0';
         while ((c = strpbrk(c, "\n\r;"))) {
             *c = ' ';
             ++c;
         }
     }
 }
References cmd_argc, cmd_argv, and MAX_CVAR_VALUE_STRING.
Referenced by SV_ExecuteClientCommand().
Cmd_ArgsBuffer()
void Cmd_ArgsBuffer (char * buffer, int bufferLength)
Definition at line 439 of file cmd.c.
{
     Q_strncpyz( buffer, Cmd_Args(), bufferLength );
 }
References Cmd_Args(), and Q_strncpyz().
Referenced by CL_CgameSystemCalls().
Cmd_ArgsFrom()
char* Cmd_ArgsFrom (int arg)
Definition at line 414 of file cmd.c.
{
     static  char        cmd_args[BIG_INFO_STRING];
     int     i;
     cmd_args[0] = 0;
     if (arg < 0)
         arg = 0;
     for ( i = arg ; i < cmd_argc ; i++ ) {
         strcat( cmd_args, cmd_argv[i] );
         if ( i != cmd_argc-1 ) {
             strcat( cmd_args, " " );
         }
     }
     return cmd_args;
 }
References BIG_INFO_STRING, cmd_argc, and cmd_argv.
Referenced by CL_ConfigstringModified(), Com_Setenv_f(), Cvar_Set_f(), and SVC_RemoteCommand().
Cmd_Argv()
char* Cmd_Argv (int arg)
Definition at line 365 of file cmd.c.
{
     if ( (unsigned)arg >= cmd_argc ) {
         return "";
     }
     return cmd_argv[arg];
 }
References cmd_argc, and cmd_argv.
Referenced by CL_ConfigstringModified(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_ForwardCommandToServer(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_InitRef(), CL_MotdPacket(), CL_Ping_f(), CL_PlayCinematic_f(), CL_PlayDemo_f(), CL_Record_f(), CL_ServerStatus_f(), CL_SetModel_f(), CL_Video_f(), Cmd_ArgvBuffer(), Cmd_Exec_f(), Cmd_List_f(), Cmd_Vstr_f(), Cmd_Wait_f(), Com_Freeze_f(), Com_GameRestart_f(), Com_SafeMode(), Com_Setenv_f(), Com_StartupVariable(), Com_WriteConfig_f(), Con_Dump_f(), Cvar_Command(), Cvar_List_f(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Field_CompleteCommand(), FS_Dir_f(), FS_NewDir_f(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), FS_TouchFile_f(), FS_Which_f(), IN_KeyDown(), IN_KeyUp(), Key_Bind_f(), Key_Unbind_f(), S_Music_f(), S_Play_f(), SV_AddBanToList(), SV_BeginDownload_f(), SV_ConnectionlessPacket(), SV_DelBanFromList(), SV_DirectConnect(), SV_ExecuteClientCommand(), SV_GetChallenge(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Map_f(), SV_MapRestart_f(), SV_NextDownload_f(), SV_UpdateUserinfo_f(), SV_VerifyPaks_f(), SV_WriteDownloadToClient(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
Cmd_ArgvBuffer()
void Cmd_ArgvBuffer (int arg, char * buffer, int bufferLength)
Definition at line 380 of file cmd.c.
{
     Q_strncpyz( buffer, Cmd_Argv( arg ), bufferLength );
 }
References Cmd_Argv(), and Q_strncpyz().
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
Cmd_Cmd()
char* Cmd_Cmd (void)
Definition at line 452 of file cmd.c.
 {
     return cmd_cmd;
 }
References cmd_cmd.
Referenced by CL_Rcon_f(), and SVC_RemoteCommand().
Cmd_CommandCompletion()
void Cmd_CommandCompletion (void(*)(const char *s) callback)
Definition at line 724 of file cmd.c.
{
     cmd_function_t  *cmd;
     for (cmd=cmd_functions ; cmd ; cmd=cmd->next) {
         callback( cmd->name );
     }
 }
References cmd_functions.
Referenced by Field_CompleteCommand().
Cmd_CompleteArgument()
void Cmd_CompleteArgument (const char * command, char * args, int argNum)
Definition at line 737 of file cmd.c.
{
     cmd_function_t  *cmd;
     for( cmd = cmd_functions; cmd; cmd = cmd->next ) {
         if( !Q_stricmp( command, cmd->name ) && cmd->complete ) {
             cmd->complete( args, argNum );
         }
     }
 }
References args, cmd_functions, and Q_stricmp().
Referenced by Field_CompleteCommand().
Cmd_CompleteCfgName()
void Cmd_CompleteCfgName (char * args, int argNum)
Definition at line 842 of file cmd.c.
{
     if( argNum == 2 ) {
         Field_CompleteFilename( "", "cfg", qfalse, qtrue );
     }
 }
References Field_CompleteFilename(), qfalse, and qtrue.
Referenced by Cmd_Init(), and Com_Init().
Cmd_Echo_f()
void Cmd_Echo_f (void)
Definition at line 321 of file cmd.c.
 {
     Com_Printf ("%s\n", Cmd_Args());
 }
References Cmd_Args(), and Com_Printf().
Referenced by Cmd_Init().
Cmd_Exec_f()
void Cmd_Exec_f (void)
Definition at line 267 of file cmd.c.
{
     union {
         char    *c;
         void    *v;
     } f;
     char    filename[MAX_QPATH];
     if (Cmd_Argc () != 2) {
         Com_Printf ("exec <filename> : execute a script file\n");
         return;
     }
     Q_strncpyz( filename, Cmd_Argv(1), sizeof( filename ) );
     COM_DefaultExtension( filename, sizeof( filename ), ".cfg" );
     FS_ReadFile( filename, &f.v);
     if (!f.c) {
         Com_Printf ("couldn't exec %s\n",Cmd_Argv(1));
         return;
     }
     Com_Printf ("execing %s\n",Cmd_Argv(1));
     Cbuf_InsertText (f.c);
     FS_FreeFile (f.v);
 }
References Cbuf_InsertText(), Cmd_Argc(), Cmd_Argv(), COM_DefaultExtension(), Com_Printf(), FS_FreeFile(), FS_ReadFile(), MAX_QPATH, and Q_strncpyz().
Referenced by Cmd_Init().
Cmd_ExecuteString()
void Cmd_ExecuteString (const char * text)
Definition at line 755 of file cmd.c.
{
     cmd_function_t  *cmd, **prev;
     // execute the command line
     Cmd_TokenizeString( text );
     if ( !Cmd_Argc() ) {
         return;     // no tokens
     }
     // check registered command functions
     for ( prev = &cmd_functions ; *prev ; prev = &cmd->next ) {
         cmd = *prev;
         if ( !Q_stricmp( cmd_argv[0],cmd->name ) ) {
             // rearrange the links so that the command will be
             // near the head of the list next time it is used
             *prev = cmd->next;
             cmd->next = cmd_functions;
             cmd_functions = cmd;
             // perform the action
             if ( !cmd->function ) {
                 // let the cgame or game handle it
                 break;
             } else {
                 cmd->function ();
             }
             return;
         }
     }
     // check cvars
     if ( Cvar_Command() ) {
         return;
     }
     // check client game commands
     if ( com_cl_running && com_cl_running->integer && CL_GameCommand() ) {
         return;
     }
     // check server game commands
     if ( com_sv_running && com_sv_running->integer && SV_GameCommand() ) {
         return;
     }
     // check ui commands
     if ( com_cl_running && com_cl_running->integer && UI_GameCommand() ) {
         return;
     }
     // send it as a server command if we are connected
     // this will usually result in a chat message
     CL_ForwardCommandToServer ( text );
 }
References CL_ForwardCommandToServer(), CL_GameCommand(), Cmd_Argc(), cmd_argv, cmd_functions, Cmd_TokenizeString(), com_cl_running, com_sv_running, Cvar_Command(), Q_stricmp(), SV_GameCommand(), and UI_GameCommand().
Referenced by Cbuf_Execute(), Cbuf_ExecuteText(), and SVC_RemoteCommand().
Cmd_FindCommand()
cmd_function_t* Cmd_FindCommand (const char * cmd_name)
Definition at line 619 of file cmd.c.
 {
     cmd_function_t *cmd;
     for( cmd = cmd_functions; cmd; cmd = cmd->next )
         if( !Q_stricmp( cmd_name, cmd->name ) )
             return cmd;
     return NULL;
 }
References cmd_functions, NULL, and Q_stricmp().
Referenced by Cmd_AddCommand(), and Cmd_RemoveCommandSafe().
Cmd_Init()
void Cmd_Init (void)
Definition at line 853 of file cmd.c.
                      {
     Cmd_AddCommand ("cmdlist",Cmd_List_f);
     Cmd_AddCommand ("exec",Cmd_Exec_f);
     Cmd_SetCommandCompletionFunc( "exec", Cmd_CompleteCfgName );
     Cmd_AddCommand ("vstr",Cmd_Vstr_f);
     Cmd_SetCommandCompletionFunc( "vstr", Cvar_CompleteCvarName );
     Cmd_AddCommand ("echo",Cmd_Echo_f);
     Cmd_AddCommand ("wait", Cmd_Wait_f);
 }
References Cmd_AddCommand(), Cmd_CompleteCfgName(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_List_f(), Cmd_SetCommandCompletionFunc(), Cmd_Vstr_f(), Cmd_Wait_f(), and Cvar_CompleteCvarName().
Referenced by Com_Init().
Cmd_List_f()
void Cmd_List_f (void)
Definition at line 815 of file cmd.c.
 {
     cmd_function_t  *cmd;
     int             i;
     char            *match;
     if ( Cmd_Argc() > 1 ) {
         match = Cmd_Argv( 1 );
     } else {
         match = NULL;
     }
     i = 0;
     for (cmd=cmd_functions ; cmd ; cmd=cmd->next) {
         if (match && !Com_Filter(match, cmd->name, qfalse)) continue;
         Com_Printf ("%s\n", cmd->name);
         i++;
     }
     Com_Printf ("%i commands\n", i);
 }
References Cmd_Argc(), Cmd_Argv(), cmd_functions, Com_Filter(), Com_Printf(), NULL, and qfalse.
Referenced by Cmd_Init().
Cmd_RemoveCommand()
void Cmd_RemoveCommand (const char * cmd_name)
Definition at line 674 of file cmd.c.
{
     cmd_function_t  *cmd, **back;
     back = &cmd_functions;
     while( 1 ) {
         cmd = *back;
         if ( !cmd ) {
             // command wasn't active
             return;
         }
         if ( !strcmp( cmd_name, cmd->name ) ) {
             *back = cmd->next;
             if (cmd->name) {
                 Z_Free(cmd->name);
             }
             Z_Free (cmd);
             return;
         }
         back = &cmd->next;
     }
 }
References cmd_functions, and Z_Free().
Referenced by CL_Disconnect(), CL_InitRef(), CL_Shutdown(), CL_ShutdownInput(), Cmd_RemoveCommandSafe(), Con_Shutdown(), FS_Shutdown(), S_Base_Shutdown(), S_Shutdown(), and SV_RemoveOperatorCommands().
Cmd_RemoveCommandSafe()
void Cmd_RemoveCommandSafe (const char * cmd_name)
Definition at line 703 of file cmd.c.
 {
     cmd_function_t *cmd = Cmd_FindCommand( cmd_name );
     if( !cmd )
         return;
     if( cmd->function )
     {
         Com_Error( ERR_DROP, "Restricted source tried to remove "
             "system command \"%s\"", cmd_name );
         return;
     }
     Cmd_RemoveCommand( cmd_name );
 }
References Cmd_FindCommand(), Cmd_RemoveCommand(), Com_Error(), and ERR_DROP.
Referenced by CL_CgameSystemCalls().
Cmd_SetCommandCompletionFunc()
void Cmd_SetCommandCompletionFunc (const char * command, completionFunc_t complete)
Definition at line 659 of file cmd.c.
{
     cmd_function_t  *cmd;
     for( cmd = cmd_functions; cmd; cmd = cmd->next ) {
         if( !Q_stricmp( command, cmd->name ) ) {
             cmd->complete = complete;
         }
     }
 }
References cmd_functions, cmd_function_s::complete, and Q_stricmp().
Referenced by CL_Init(), CL_InitKeyCommands(), Cmd_Init(), Com_Init(), Con_Init(), Cvar_Init(), and SV_AddOperatorCommands().
Cmd_TokenizeString()
void Cmd_TokenizeString (const char * text_in)
Definition at line 601 of file cmd.c.
{
     Cmd_TokenizeString2( text_in, qfalse );
 }
References Cmd_TokenizeString2(), and qfalse.
Referenced by CL_ConnectionlessPacket(), CL_GetServerCommand(), Cmd_ExecuteString(), Com_SafeMode(), Com_StartupVariable(), FS_PureServerSetLoadedPaks(), FS_PureServerSetReferencedPaks(), SV_ConnectionlessPacket(), SV_ExecuteClientCommand(), and SV_VerifyPaks_f().
Cmd_TokenizeString2()
static void Cmd_TokenizeString2 (const char * text_in, qboolean ignoreQuotes) static
Definition at line 494 of file cmd.c.
{
     const char  *text;
     char    *textOut;
 #ifdef TKN_DBG
   // FIXME TTimo blunt hook to try to find the tokenization of userinfo
   Com_DPrintf("Cmd_TokenizeString: %s\n", text_in);
 #endif
     // clear previous args
     cmd_argc = 0;
     if ( !text_in ) {
         return;
     }
     Q_strncpyz( cmd_cmd, text_in, sizeof(cmd_cmd) );
     text = text_in;
     textOut = cmd_tokenized;
     while ( 1 ) {
         if ( cmd_argc == MAX_STRING_TOKENS ) {
             return;         // this is usually something malicious
         }
         while ( 1 ) {
             // skip whitespace
             while ( *text && *text <= ' ' ) {
                 text++;
             }
             if ( !*text ) {
                 return;         // all tokens parsed
             }
             // skip // comments
             if ( text[0] == '/' && text[1] == '/' ) {
                 return;         // all tokens parsed
             }
             // skip /* */ comments
             if ( text[0] == '/' && text[1] =='*' ) {
                 while ( *text && ( text[0] != '*' || text[1] != '/' ) ) {
                     text++;
                 }
                 if ( !*text ) {
                     return;     // all tokens parsed
                 }
                 text += 2;
             } else {
                 break;          // we are ready to parse a token
             }
         }
         // handle quoted strings
     // NOTE TTimo this doesn't handle \" escaping
         if ( !ignoreQuotes && *text == '"' ) {
             cmd_argv[cmd_argc] = textOut;
             cmd_argc++;
             text++;
             while ( *text && *text != '"' ) {
                 *textOut++ = *text++;
             }
             *textOut++ = 0;
             if ( !*text ) {
                 return;     // all tokens parsed
             }
             text++;
             continue;
         }
         // regular token
         cmd_argv[cmd_argc] = textOut;
         cmd_argc++;
         // skip until whitespace, quote, or command
         while ( *text > ' ' ) {
             if ( !ignoreQuotes && text[0] == '"' ) {
                 break;
             }
             if ( text[0] == '/' && text[1] == '/' ) {
                 break;
             }
             // skip /* */ comments
             if ( text[0] == '/' && text[1] =='*' ) {
                 break;
             }
             *textOut++ = *text++;
         }
         *textOut++ = 0;
         if ( !*text ) {
             return;     // all tokens parsed
         }
     }
 }
References cmd_argc, cmd_argv, cmd_cmd, cmd_tokenized, Com_DPrintf(), MAX_STRING_TOKENS, and Q_strncpyz().
Referenced by Cmd_TokenizeString(), and Cmd_TokenizeStringIgnoreQuotes().
Cmd_TokenizeStringIgnoreQuotes()
void Cmd_TokenizeStringIgnoreQuotes (const char * text_in)
Definition at line 610 of file cmd.c.
{
     Cmd_TokenizeString2( text_in, qtrue );
 }
References Cmd_TokenizeString2(), and qtrue.
Referenced by Field_CompleteCommand(), and SV_WriteDownloadToClient().
Cmd_Vstr_f()
void Cmd_Vstr_f (void)
Definition at line 301 of file cmd.c.
{
     char    *v;
     if (Cmd_Argc () != 2) {
         Com_Printf ("vstr <variablename> : execute a variable command\n");
         return;
     }
     v = Cvar_VariableString( Cmd_Argv( 1 ) );
     Cbuf_InsertText( va("%s\n", v ) );
 }
References Cbuf_InsertText(), Cmd_Argc(), Cmd_Argv(), Com_Printf(), Cvar_VariableString(), and va().
Referenced by Cmd_Init().
Cmd_Wait_f()
void Cmd_Wait_f (void)
Definition at line 52 of file cmd.c.
{
     if ( Cmd_Argc() == 2 ) {
         cmd_wait = atoi( Cmd_Argv( 1 ) );
         if ( cmd_wait < 0 )
             cmd_wait = 1; // ignore the argument
     } else {
         cmd_wait = 1;
     }
 }
References Cmd_Argc(), Cmd_Argv(), and cmd_wait.
Referenced by Cmd_Init().
Variable Documentation
cmd_argc
int cmd_argc static
Definition at line 344 of file cmd.c.
Referenced by Cmd_Argc(), Cmd_Args(), Cmd_Args_Sanitize(), Cmd_ArgsFrom(), Cmd_Argv(), and Cmd_TokenizeString2().
cmd_argv
char* cmd_argv[MAX_STRING_TOKENS] static
Definition at line 345 of file cmd.c.
Referenced by Cmd_Args(), Cmd_Args_Sanitize(), Cmd_ArgsFrom(), Cmd_Argv(), Cmd_ExecuteString(), and Cmd_TokenizeString2().
cmd_cmd
char cmd_cmd[BIG_INFO_STRING] static
Definition at line 347 of file cmd.c.
Referenced by Cmd_Cmd(), and Cmd_TokenizeString2().
cmd_functions
cmd_function_t* cmd_functions static
Definition at line 349 of file cmd.c.
Referenced by Cmd_AddCommand(), Cmd_CommandCompletion(), Cmd_CompleteArgument(), Cmd_ExecuteString(), Cmd_FindCommand(), Cmd_List_f(), Cmd_RemoveCommand(), and Cmd_SetCommandCompletionFunc().
cmd_text
cmd_t cmd_text
Definition at line 37 of file cmd.c.
Referenced by Cbuf_AddText(), Cbuf_Execute(), Cbuf_ExecuteText(), Cbuf_Init(), and Cbuf_InsertText().
cmd_text_buf
byte cmd_text_buf[MAX_CMD_BUFFER]
Definition at line 38 of file cmd.c.
Referenced by Cbuf_Init().
cmd_tokenized
char cmd_tokenized[BIG_INFO_STRING+MAX_STRING_TOKENS] static
Definition at line 346 of file cmd.c.
Referenced by Cmd_TokenizeString2().
cmd_wait
int cmd_wait
Definition at line 36 of file cmd.c.
Referenced by Cbuf_Execute(), and Cmd_Wait_f().