ZEQ2-Lite: Source/Engine/SDL12/include/SDL_mouse.h File Reference
SDL_mouse.h File Reference
#include "SDL_stdinc.h"
#include "SDL_error.h"
#include "SDL_video.h"
#include "begin_code.h"
#include "close_code.h"
Data Structures
struct SDL_Cursor
Macros
#define SDL_BUTTON(X) (1 << ((X)-1))
Used as a mask when testing buttons in buttonstate Button 1: Left mouse button Button 2: Middle mouse button Button 3: Right mouse button Button 4: Mouse wheel up (may also be a real button) Button 5: Mouse wheel down (may also be a real button)
#define SDL_BUTTON_LEFT 1
#define SDL_BUTTON_LMASK SDL_BUTTON(SDL_BUTTON_LEFT)
#define SDL_BUTTON_MIDDLE 2
#define SDL_BUTTON_MMASK SDL_BUTTON(SDL_BUTTON_MIDDLE)
#define SDL_BUTTON_RIGHT 3
#define SDL_BUTTON_RMASK SDL_BUTTON(SDL_BUTTON_RIGHT)
#define SDL_BUTTON_WHEELDOWN 5
#define SDL_BUTTON_WHEELUP 4
#define SDL_BUTTON_X1 6
#define SDL_BUTTON_X1MASK SDL_BUTTON(SDL_BUTTON_X1)
#define SDL_BUTTON_X2 7
#define SDL_BUTTON_X2MASK SDL_BUTTON(SDL_BUTTON_X2)
Typedefs
typedef struct WMcursor WMcursor
Implementation dependent.
Functions
DECLSPEC SDL_Cursor *SDLCALL SDL_CreateCursor (Uint8 *data, Uint8 *mask, int w, int h, int hot_x, int hot_y)
Create a cursor using the specified data and mask (in MSB format).
DECLSPEC void SDLCALL SDL_FreeCursor (SDL_Cursor *cursor)
Deallocates a cursor created with SDL_CreateCursor().
DECLSPEC SDL_Cursor *SDLCALL SDL_GetCursor (void)
Returns the currently active cursor.
DECLSPEC Uint8 SDLCALL SDL_GetMouseState (int *x, int *y)
Retrieve the current state of the mouse.
DECLSPEC Uint8 SDLCALL SDL_GetRelativeMouseState (int *x, int *y)
Retrieve the current state of the mouse.
DECLSPEC void SDLCALL SDL_SetCursor (SDL_Cursor *cursor)
Set the currently active cursor to the specified one.
DECLSPEC int SDLCALL SDL_ShowCursor (int toggle)
Toggle whether or not the cursor is shown on the screen.
DECLSPEC void SDLCALL SDL_WarpMouse (Uint16 x, Uint16 y)
Set the position of the mouse cursor (generates a mouse motion event)
Detailed Description
Include file for SDL mouse event handling
Definition in file SDL_mouse.h.
Macro Definition Documentation
SDL_BUTTON
#define SDL_BUTTON (X) (1 << ((X)-1))
Used as a mask when testing buttons in buttonstate Button 1: Left mouse button Button 2: Middle mouse button Button 3: Right mouse button Button 4: Mouse wheel up (may also be a real button) Button 5: Mouse wheel down (may also be a real button)
Definition at line 122 of file SDL_mouse.h.
SDL_BUTTON_LEFT
#define SDL_BUTTON_LEFT 1
Definition at line 123 of file SDL_mouse.h.
SDL_BUTTON_LMASK
#define SDL_BUTTON_LMASK SDL_BUTTON(SDL_BUTTON_LEFT)
Definition at line 130 of file SDL_mouse.h.
SDL_BUTTON_MIDDLE
#define SDL_BUTTON_MIDDLE 2
Definition at line 124 of file SDL_mouse.h.
SDL_BUTTON_MMASK
#define SDL_BUTTON_MMASK SDL_BUTTON(SDL_BUTTON_MIDDLE)
Definition at line 131 of file SDL_mouse.h.
SDL_BUTTON_RIGHT
#define SDL_BUTTON_RIGHT 3
Definition at line 125 of file SDL_mouse.h.
SDL_BUTTON_RMASK
#define SDL_BUTTON_RMASK SDL_BUTTON(SDL_BUTTON_RIGHT)
Definition at line 132 of file SDL_mouse.h.
SDL_BUTTON_WHEELDOWN
#define SDL_BUTTON_WHEELDOWN 5
Definition at line 127 of file SDL_mouse.h.
SDL_BUTTON_WHEELUP
#define SDL_BUTTON_WHEELUP 4
Definition at line 126 of file SDL_mouse.h.
SDL_BUTTON_X1
#define SDL_BUTTON_X1 6
Definition at line 128 of file SDL_mouse.h.
SDL_BUTTON_X1MASK
#define SDL_BUTTON_X1MASK SDL_BUTTON(SDL_BUTTON_X1)
Definition at line 133 of file SDL_mouse.h.
SDL_BUTTON_X2
#define SDL_BUTTON_X2 7
Definition at line 129 of file SDL_mouse.h.
SDL_BUTTON_X2MASK
#define SDL_BUTTON_X2MASK SDL_BUTTON(SDL_BUTTON_X2)
Definition at line 134 of file SDL_mouse.h.
Typedef Documentation
WMcursor
typedef struct WMcursor WMcursor
Implementation dependent.
Definition at line 40 of file SDL_mouse.h.
Function Documentation
SDL_CreateCursor()
DECLSPEC SDL_Cursor* SDLCALL SDL_CreateCursor (Uint8 * data, Uint8 * mask, int w, int h, int hot_x, int hot_y)
Create a cursor using the specified data and mask (in MSB format).
The cursor width must be a multiple of 8 bits.
The cursor is created in black and white according to the following: data mask resulting pixel on screen 0 1 White 1 1 Black 0 0 Transparent 1 0 Inverted color if possible, black if not.
Cursors created with this function must be freed with SDL_FreeCursor().
SDL_FreeCursor()
DECLSPEC void SDLCALL SDL_FreeCursor (SDL_Cursor * cursor)
Deallocates a cursor created with SDL_CreateCursor().
SDL_GetCursor()
DECLSPEC SDL_Cursor* SDLCALL SDL_GetCursor (void)
Returns the currently active cursor.
SDL_GetMouseState()
DECLSPEC Uint8 SDLCALL SDL_GetMouseState (int * x, int * y)
Retrieve the current state of the mouse.
The current button state is returned as a button bitmask, which can be tested using the SDL_BUTTON(X) macros, and x and y are set to the current mouse cursor position. You can pass NULL for either x or y.
SDL_GetRelativeMouseState()
DECLSPEC Uint8 SDLCALL SDL_GetRelativeMouseState (int * x, int * y)
Retrieve the current state of the mouse.
The current button state is returned as a button bitmask, which can be tested using the SDL_BUTTON(X) macros, and x and y are set to the mouse deltas since the last call to SDL_GetRelativeMouseState().
SDL_SetCursor()
DECLSPEC void SDLCALL SDL_SetCursor (SDL_Cursor * cursor)
Set the currently active cursor to the specified one.
If the cursor is currently visible, the change will be immediately represented on the display.
SDL_ShowCursor()
DECLSPEC int SDLCALL SDL_ShowCursor (int toggle)
Toggle whether or not the cursor is shown on the screen.
The cursor start off displayed, but can be turned off. SDL_ShowCursor() returns 1 if the cursor was being displayed before the call, or 0 if it was not. You can query the current state by passing a 'toggle' value of -1.
Referenced by GLimp_SetMode(), IN_ActivateMouse(), and IN_DeactivateMouse().
SDL_WarpMouse()
DECLSPEC void SDLCALL SDL_WarpMouse (Uint16 x, Uint16 y)
Set the position of the mouse cursor (generates a mouse motion event)
Referenced by IN_DeactivateMouse().