ZEQ2-Lite: ImageAttributes Class Reference
ImageAttributes Class Reference
#include <gdiplusimageattributes.h>
Public Member Functions
ImageAttributes ()
~ImageAttributes ()
Status ClearBrushRemapTable ()
Status ClearColorKey (ColorAdjustType type=ColorAdjustTypeDefault)
Status ClearColorMatrices (ColorAdjustType type=ColorAdjustTypeDefault)
Status ClearColorMatrix (ColorAdjustType type=ColorAdjustTypeDefault)
Status ClearGamma (ColorAdjustType type=ColorAdjustTypeDefault)
Status ClearNoOp (ColorAdjustType type=ColorAdjustTypeDefault)
Status ClearOutputChannel (ColorAdjustType type=ColorAdjustTypeDefault)
Status ClearOutputChannelColorProfile (ColorAdjustType type=ColorAdjustTypeDefault)
Status ClearRemapTable (ColorAdjustType type=ColorAdjustTypeDefault)
Status ClearThreshold (ColorAdjustType type=ColorAdjustTypeDefault)
ImageAttributes * Clone () const
Status GetAdjustedPalette (ColorPalette *colorPalette, ColorAdjustType type) const
Status GetLastStatus () const
Status Reset (ColorAdjustType type=ColorAdjustTypeDefault)
Status SetBrushRemapTable (UINT mapSize, ColorMap *map)
Status SetColorKey (const Color &colorLow, const Color &colorHigh, ColorAdjustType type=ColorAdjustTypeDefault)
Status SetColorMatrices (const ColorMatrix *colorMatrix, const ColorMatrix *grayMatrix, ColorMatrixFlags mode=ColorMatrixFlagsDefault, ColorAdjustType type=ColorAdjustTypeDefault)
Status SetColorMatrix (const ColorMatrix *colorMatrix, ColorMatrixFlags mode=ColorMatrixFlagsDefault, ColorAdjustType type=ColorAdjustTypeDefault)
Status SetGamma (REAL gamma, ColorAdjustType type=ColorAdjustTypeDefault)
Status SetNoOp (ColorAdjustType type=ColorAdjustTypeDefault)
Status SetOutputChannel (ColorChannelFlags channelFlags, ColorAdjustType type=ColorAdjustTypeDefault)
Status SetOutputChannelColorProfile (const WCHAR *colorProfileFilename, ColorAdjustType type=ColorAdjustTypeDefault)
Status SetRemapTable (UINT mapSize, const ColorMap *map, ColorAdjustType type=ColorAdjustTypeDefault)
Status SetThreshold (REAL threshold, ColorAdjustType type=ColorAdjustTypeDefault)
Status SetToIdentity (ColorAdjustType type=ColorAdjustTypeDefault)
Status SetWrapMode (WrapMode wrap, const Color &color=Color(), BOOL clamp=FALSE)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
ImageAttributes (const ImageAttributes &)
ImageAttributes (GpImageAttributes *imageAttributes, Status status)
ImageAttributes & operator= (const ImageAttributes &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpImageAttributes * nativeImageAttributes
Friends
class Graphics
class TextureBrush
Detailed Description
Definition at line 33 of file gdiplusimageattributes.h.
Constructor & Destructor Documentation
ImageAttributes() [1/3]
ImageAttributes::ImageAttributes () inline
Definition at line 39 of file gdiplusimageattributes.h.
                      : nativeImageAttributes(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreateImageAttributes(
                 &nativeImageAttributes);
     }
References GdipCreateImageAttributes(), lastStatus, and nativeImageAttributes.
Referenced by Clone().
~ImageAttributes()
ImageAttributes::~ImageAttributes () inline
Definition at line 44 of file gdiplusimageattributes.h.
     {
         DllExports::GdipDisposeImageAttributes(nativeImageAttributes);
     }
References GdipDisposeImageAttributes(), and nativeImageAttributes.
ImageAttributes() [2/3]
ImageAttributes::ImageAttributes (GpImageAttributes * imageAttributes, Status status) inline private
Definition at line 220 of file gdiplusimageattributes.h.
                                                                       :
         nativeImageAttributes(imageAttributes), lastStatus(status) {}
ImageAttributes() [3/3]
ImageAttributes::ImageAttributes (const ImageAttributes &) private
Member Function Documentation
ClearBrushRemapTable()
Status ImageAttributes::ClearBrushRemapTable () inline
Definition at line 66 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesRemapTable(
                 nativeImageAttributes, ColorAdjustTypeBrush,
                 FALSE, 0, NULL));
     }
References ColorAdjustTypeBrush, FALSE, GdipSetImageAttributesRemapTable(), nativeImageAttributes, NULL, and updateStatus().
ClearColorKey()
Status ImageAttributes::ClearColorKey (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 72 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesColorKeys(
                 nativeImageAttributes, type, FALSE, 0, 0));
     }
References FALSE, GdipSetImageAttributesColorKeys(), nativeImageAttributes, and updateStatus().
ClearColorMatrices()
Status ImageAttributes::ClearColorMatrices (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 77 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesColorMatrix(
                 nativeImageAttributes, type, FALSE,
                 NULL, NULL, ColorMatrixFlagsDefault));
     }
References ColorMatrixFlagsDefault, FALSE, GdipSetImageAttributesColorMatrix(), nativeImageAttributes, NULL, and updateStatus().
ClearColorMatrix()
Status ImageAttributes::ClearColorMatrix (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 83 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesColorMatrix(
                 nativeImageAttributes, type, FALSE,
                 NULL, NULL, ColorMatrixFlagsDefault));
     }
References ColorMatrixFlagsDefault, FALSE, GdipSetImageAttributesColorMatrix(), nativeImageAttributes, NULL, and updateStatus().
ClearGamma()
Status ImageAttributes::ClearGamma (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 89 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesGamma(
                 nativeImageAttributes, type, FALSE, 1.0f));
     }
References FALSE, GdipSetImageAttributesGamma(), nativeImageAttributes, and updateStatus().
ClearNoOp()
Status ImageAttributes::ClearNoOp (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 94 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesNoOp(
                 nativeImageAttributes, type, FALSE));
     }
References FALSE, GdipSetImageAttributesNoOp(), nativeImageAttributes, and updateStatus().
ClearOutputChannel()
Status ImageAttributes::ClearOutputChannel (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 99 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesOutputChannel(
                 nativeImageAttributes, type, FALSE,
                 ColorChannelFlagsC));
     }
References ColorChannelFlagsC, FALSE, GdipSetImageAttributesOutputChannel(), nativeImageAttributes, and updateStatus().
ClearOutputChannelColorProfile()
Status ImageAttributes::ClearOutputChannelColorProfile (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 105 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesOutputChannelColorProfile(
                 nativeImageAttributes, type, FALSE, NULL));
     }
References FALSE, GdipSetImageAttributesOutputChannelColorProfile(), nativeImageAttributes, NULL, and updateStatus().
ClearRemapTable()
Status ImageAttributes::ClearRemapTable (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 111 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesRemapTable(
                 nativeImageAttributes, type, FALSE, 0, NULL));
     }
References FALSE, GdipSetImageAttributesRemapTable(), nativeImageAttributes, NULL, and updateStatus().
ClearThreshold()
Status ImageAttributes::ClearThreshold (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 116 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesThreshold(
                 nativeImageAttributes, type, FALSE, 0.0));
     }
References FALSE, GdipSetImageAttributesThreshold(), nativeImageAttributes, and updateStatus().
Clone()
ImageAttributes* ImageAttributes::Clone () const inline
Definition at line 48 of file gdiplusimageattributes.h.
     {
         GpImageAttributes *cloneImageAttributes = NULL;
         Status status = updateStatus(DllExports::GdipCloneImageAttributes(
                 nativeImageAttributes, &cloneImageAttributes));
         if (status == Ok) {
             ImageAttributes *result = new ImageAttributes(
                     cloneImageAttributes, lastStatus);
             if (!result) {
                 DllExports::GdipDisposeImageAttributes(cloneImageAttributes);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneImageAttributes(), GdipDisposeImageAttributes(), ImageAttributes(), lastStatus, nativeImageAttributes, NULL, Ok, OutOfMemory, and updateStatus().
GetAdjustedPalette()
Status ImageAttributes::GetAdjustedPalette (ColorPalette * colorPalette, ColorAdjustType type) const inline
Definition at line 121 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipGetImageAttributesAdjustedPalette(
                 nativeImageAttributes, colorPalette, type));
     }
References GdipGetImageAttributesAdjustedPalette(), nativeImageAttributes, and updateStatus().
GetLastStatus()
Status ImageAttributes::GetLastStatus () const inline
Definition at line 127 of file gdiplusimageattributes.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
ImageAttributes& ImageAttributes::operator= (const ImageAttributes &) private
Reset()
Status ImageAttributes::Reset (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 133 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipResetImageAttributes(
                 nativeImageAttributes, type));
     }
References GdipResetImageAttributes(), nativeImageAttributes, and updateStatus().
SetBrushRemapTable()
Status ImageAttributes::SetBrushRemapTable (UINT mapSize, ColorMap * map) inline
Definition at line 138 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesRemapTable(
                 nativeImageAttributes, ColorAdjustTypeBrush,
                 TRUE, mapSize, map));
     }
References ColorAdjustTypeBrush, GdipSetImageAttributesRemapTable(), nativeImageAttributes, TRUE, and updateStatus().
SetColorKey()
Status ImageAttributes::SetColorKey (const Color & colorLow, const Color & colorHigh, ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 144 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesColorKeys(
                 nativeImageAttributes, type, TRUE,
                 colorLow.GetValue(), colorHigh.GetValue()));
     }
References GdipSetImageAttributesColorKeys(), nativeImageAttributes, TRUE, and updateStatus().
SetColorMatrices()
Status ImageAttributes::SetColorMatrices (const ColorMatrix * colorMatrix, const ColorMatrix * grayMatrix, ColorMatrixFlags mode = ColorMatrixFlagsDefault, ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 151 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesColorMatrix(
                 nativeImageAttributes, type, TRUE,
                 colorMatrix, grayMatrix, mode));
     }
References GdipSetImageAttributesColorMatrix(), nativeImageAttributes, TRUE, and updateStatus().
SetColorMatrix()
Status ImageAttributes::SetColorMatrix (const ColorMatrix * colorMatrix, ColorMatrixFlags mode = ColorMatrixFlagsDefault, ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 160 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesColorMatrix(
                 nativeImageAttributes, type, TRUE,
                 colorMatrix, NULL, mode));
     }
References GdipSetImageAttributesColorMatrix(), nativeImageAttributes, NULL, TRUE, and updateStatus().
SetGamma()
Status ImageAttributes::SetGamma (REAL gamma, ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 168 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesGamma(
                 nativeImageAttributes, type, TRUE, gamma));
     }
References GdipSetImageAttributesGamma(), nativeImageAttributes, TRUE, and updateStatus().
SetNoOp()
Status ImageAttributes::SetNoOp (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 174 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesNoOp(
                 nativeImageAttributes, type, TRUE));
     }
References GdipSetImageAttributesNoOp(), nativeImageAttributes, TRUE, and updateStatus().
SetOutputChannel()
Status ImageAttributes::SetOutputChannel (ColorChannelFlags channelFlags, ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 179 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesOutputChannel(
                 nativeImageAttributes, type, TRUE,
                 channelFlags));
     }
References GdipSetImageAttributesOutputChannel(), nativeImageAttributes, TRUE, and updateStatus().
SetOutputChannelColorProfile()
Status ImageAttributes::SetOutputChannelColorProfile (const WCHAR * colorProfileFilename, ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 186 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesOutputChannelColorProfile(
                 nativeImageAttributes, type, TRUE,
                 colorProfileFilename));
     }
References GdipSetImageAttributesOutputChannelColorProfile(), nativeImageAttributes, TRUE, and updateStatus().
SetRemapTable()
Status ImageAttributes::SetRemapTable (UINT mapSize, const ColorMap * map, ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 193 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesRemapTable(
                 nativeImageAttributes, type, TRUE,
                 mapSize, map));
     }
References GdipSetImageAttributesRemapTable(), nativeImageAttributes, TRUE, and updateStatus().
SetThreshold()
Status ImageAttributes::SetThreshold (REAL threshold, ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 200 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesThreshold(
                 nativeImageAttributes, type, TRUE, threshold));
     }
References GdipSetImageAttributesThreshold(), nativeImageAttributes, TRUE, and updateStatus().
SetToIdentity()
Status ImageAttributes::SetToIdentity (ColorAdjustType type = ColorAdjustTypeDefault) inline
Definition at line 206 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesToIdentity(
                 nativeImageAttributes, type));
     }
References GdipSetImageAttributesToIdentity(), nativeImageAttributes, and updateStatus().
SetWrapMode()
Status ImageAttributes::SetWrapMode (WrapMode wrap, const Color & color = Color(), BOOL clamp = FALSE) inline
Definition at line 211 of file gdiplusimageattributes.h.
     {
         return updateStatus(DllExports::GdipSetImageAttributesWrapMode(
                 nativeImageAttributes, wrap,
                 color.GetValue(), clamp));
     }
References GdipSetImageAttributesWrapMode(), nativeImageAttributes, and updateStatus().
updateStatus()
Status ImageAttributes::updateStatus (Status newStatus) const inline private
Definition at line 225 of file gdiplusimageattributes.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by ClearBrushRemapTable(), ClearColorKey(), ClearColorMatrices(), ClearColorMatrix(), ClearGamma(), ClearNoOp(), ClearOutputChannel(), ClearOutputChannelColorProfile(), ClearRemapTable(), ClearThreshold(), Clone(), GetAdjustedPalette(), Reset(), SetBrushRemapTable(), SetColorKey(), SetColorMatrices(), SetColorMatrix(), SetGamma(), SetNoOp(), SetOutputChannel(), SetOutputChannelColorProfile(), SetRemapTable(), SetThreshold(), SetToIdentity(), and SetWrapMode().
Friends And Related Function Documentation
Graphics
friend class Graphics friend
Definition at line 35 of file gdiplusimageattributes.h.
TextureBrush
friend class TextureBrush friend
Definition at line 36 of file gdiplusimageattributes.h.
Field Documentation
lastStatus
Status ImageAttributes::lastStatus mutable private
Definition at line 232 of file gdiplusimageattributes.h.
Referenced by Clone(), GetLastStatus(), ImageAttributes(), and updateStatus().
nativeImageAttributes
GpImageAttributes* ImageAttributes::nativeImageAttributes private
Definition at line 231 of file gdiplusimageattributes.h.
Referenced by ClearBrushRemapTable(), ClearColorKey(), ClearColorMatrices(), ClearColorMatrix(), ClearGamma(), ClearNoOp(), ClearOutputChannel(), ClearOutputChannelColorProfile(), ClearRemapTable(), ClearThreshold(), Clone(), GetAdjustedPalette(), ImageAttributes(), Reset(), SetBrushRemapTable(), SetColorKey(), SetColorMatrices(), SetColorMatrix(), SetGamma(), SetNoOp(), SetOutputChannel(), SetOutputChannelColorProfile(), SetRemapTable(), SetThreshold(), SetToIdentity(), SetWrapMode(), and ~ImageAttributes().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusimageattributes.h