ZEQ2-Lite: FontFamily Class Reference
FontFamily Class Reference
#include <gdiplusheaders.h>
Public Member Functions
FontFamily ()
FontFamily (const WCHAR *name, const FontCollection *fontCollection=NULL)
~FontFamily ()
FontFamily * Clone () const
UINT16 GetCellAscent (INT style) const
UINT16 GetCellDescent (INT style) const
UINT16 GetEmHeight (INT style) const
Status GetFamilyName (WCHAR name[LF_FACESIZE], LANGID language=LANG_NEUTRAL) const
Status GetLastStatus () const
UINT16 GetLineSpacing (INT style) const
BOOL IsAvailable () const
BOOL IsStyleAvailable (INT style) const
Static Public Member Functions
static const FontFamily * GenericMonospace ()
static const FontFamily * GenericSansSerif ()
static const FontFamily * GenericSerif ()
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
FontFamily (const FontFamily &)
FontFamily (GpFontFamily *fontFamily, Status status)
FontFamily & operator= (const FontFamily &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpFontFamily * nativeFontFamily
Friends
class Font
class FontCollection
class GraphicsPath
Detailed Description
Definition at line 414 of file gdiplusheaders.h.
Constructor & Destructor Documentation
FontFamily() [1/4]
__inline__ FontFamily::FontFamily ()
Definition at line 993 of file gdiplusimpl.h.
                                  :
     nativeFontFamily(NULL), lastStatus(Ok)
 {
 }
Referenced by Clone(), GenericMonospace(), GenericSansSerif(), and GenericSerif().
FontFamily() [2/4]
__inline__ FontFamily::FontFamily (const WCHAR * name, const FontCollection * fontCollection = NULL)
Definition at line 998 of file gdiplusimpl.h.
                                              :
         nativeFontFamily(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateFontFamilyFromName(name,
             fontCollection ? fontCollection->nativeFontCollection : NULL,
             &nativeFontFamily);
 }
References GdipCreateFontFamilyFromName(), lastStatus, FontCollection::nativeFontCollection, nativeFontFamily, and NULL.
~FontFamily()
__inline__ FontFamily::~FontFamily ()
Definition at line 1007 of file gdiplusimpl.h.
 {
     DllExports::GdipDeleteFontFamily(nativeFontFamily);
 }
References GdipDeleteFontFamily(), and nativeFontFamily.
FontFamily() [3/4]
FontFamily::FontFamily (GpFontFamily * fontFamily, Status status) inline private
Definition at line 451 of file gdiplusheaders.h.
                                                        :
         nativeFontFamily(fontFamily), lastStatus(status) {}
FontFamily() [4/4]
FontFamily::FontFamily (const FontFamily &) private
Member Function Documentation
Clone()
__inline__ FontFamily * FontFamily::Clone () const
Definition at line 1012 of file gdiplusimpl.h.
 {
     GpFontFamily *cloneFontFamily = NULL;
     Status status = updateStatus(DllExports::GdipCloneFontFamily(
             nativeFontFamily, &cloneFontFamily));
     if (status == Ok) {
         FontFamily *result = new FontFamily(cloneFontFamily, lastStatus);
         if (!result) {
             DllExports::GdipDeleteFontFamily(cloneFontFamily);
             lastStatus = OutOfMemory;
         }
         return result;
     } else {
         return NULL;
     }
 }
References FontFamily(), GdipCloneFontFamily(), GdipDeleteFontFamily(), lastStatus, nativeFontFamily, NULL, Ok, OutOfMemory, and updateStatus().
GenericMonospace()
const __inline__ FontFamily * FontFamily::GenericMonospace () static
Definition at line 951 of file gdiplusimpl.h.
 {
     if (!_GdipFontFamilyCachedGenericMonospace) {
         GpFontFamily *nativeFontFamily = 0;
         Status status = DllExports::GdipGetGenericFontFamilyMonospace(
                 &nativeFontFamily);
         if (status == Ok && nativeFontFamily) {
             _GdipFontFamilyCachedGenericMonospace = (void*)
                 new FontFamily(nativeFontFamily, Ok);
         }
     }
     return (FontFamily*) _GdipFontFamilyCachedGenericMonospace;
 }
References _GdipFontFamilyCachedGenericMonospace, FontFamily(), GdipGetGenericFontFamilyMonospace(), nativeFontFamily, and Ok.
GenericSansSerif()
const __inline__ FontFamily * FontFamily::GenericSansSerif () static
Definition at line 965 of file gdiplusimpl.h.
 {
     if (!_GdipFontFamilyCachedGenericSansSerif) {
         GpFontFamily *nativeFontFamily = 0;
         Status status = DllExports::GdipGetGenericFontFamilySansSerif(
                 &nativeFontFamily);
         if (status == Ok && nativeFontFamily) {
             _GdipFontFamilyCachedGenericSansSerif = (void*)
                 new FontFamily(nativeFontFamily, Ok);
         }
     }
     return (FontFamily*) _GdipFontFamilyCachedGenericSansSerif;
 }
References _GdipFontFamilyCachedGenericSansSerif, FontFamily(), GdipGetGenericFontFamilySansSerif(), nativeFontFamily, and Ok.
GenericSerif()
const __inline__ FontFamily * FontFamily::GenericSerif () static
Definition at line 979 of file gdiplusimpl.h.
 {
     if (!_GdipFontFamilyCachedGenericSerif) {
         GpFontFamily *nativeFontFamily = 0;
         Status status = DllExports::GdipGetGenericFontFamilySerif(
                 &nativeFontFamily);
         if (status == Ok && nativeFontFamily) {
             _GdipFontFamilyCachedGenericSerif = (void*)
                 new FontFamily(nativeFontFamily, Ok);
         }
     }
     return (FontFamily*) _GdipFontFamilyCachedGenericSerif;
 }
References _GdipFontFamilyCachedGenericSerif, FontFamily(), GdipGetGenericFontFamilySerif(), nativeFontFamily, and Ok.
GetCellAscent()
__inline__ UINT16 FontFamily::GetCellAscent (INT style) const
Definition at line 1029 of file gdiplusimpl.h.
 {
     UINT16 result = 0;
     updateStatus(DllExports::GdipGetCellAscent(
             nativeFontFamily, style, &result));
     return result;
 }
References GdipGetCellAscent(), nativeFontFamily, and updateStatus().
GetCellDescent()
__inline__ UINT16 FontFamily::GetCellDescent (INT style) const
Definition at line 1037 of file gdiplusimpl.h.
 {
     UINT16 result = 0;
     updateStatus(DllExports::GdipGetCellDescent(
             nativeFontFamily, style, &result));
     return result;
 }
References GdipGetCellDescent(), nativeFontFamily, and updateStatus().
GetEmHeight()
__inline__ UINT16 FontFamily::GetEmHeight (INT style) const
Definition at line 1045 of file gdiplusimpl.h.
 {
     UINT16 result = 0;
     updateStatus(DllExports::GdipGetEmHeight(
             nativeFontFamily, style, &result));
     return result;
 }
References GdipGetEmHeight(), nativeFontFamily, and updateStatus().
GetFamilyName()
__inline__ Status FontFamily::GetFamilyName (WCHAR name[LF_FACESIZE], LANGID language = LANG_NEUTRAL) const
Definition at line 1053 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetFamilyName(
             nativeFontFamily, name, language));
 }
References GdipGetFamilyName(), nativeFontFamily, and updateStatus().
GetLastStatus()
Status FontFamily::GetLastStatus () const inline
Definition at line 439 of file gdiplusheaders.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetLineSpacing()
__inline__ UINT16 FontFamily::GetLineSpacing (INT style) const
Definition at line 1060 of file gdiplusimpl.h.
 {
     UINT16 result = 0;
     updateStatus(DllExports::GdipGetLineSpacing(
             nativeFontFamily, style, &result));
     return result;
 }
References GdipGetLineSpacing(), nativeFontFamily, and updateStatus().
IsAvailable()
BOOL FontFamily::IsAvailable () const inline
Definition at line 445 of file gdiplusheaders.h.
     {
         return nativeFontFamily != NULL;
     }
References nativeFontFamily, and NULL.
IsStyleAvailable()
__inline__ BOOL FontFamily::IsStyleAvailable (INT style) const
Definition at line 1068 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsStyleAvailable(
             nativeFontFamily, style, &result));
     return result;
 }
References FALSE, GdipIsStyleAvailable(), nativeFontFamily, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
FontFamily& FontFamily::operator= (const FontFamily &) private
updateStatus()
Status FontFamily::updateStatus (Status newStatus) const inline private
Definition at line 456 of file gdiplusheaders.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by Clone(), GetCellAscent(), GetCellDescent(), GetEmHeight(), GetFamilyName(), GetLineSpacing(), and IsStyleAvailable().
Friends And Related Function Documentation
Font
friend class Font friend
Definition at line 416 of file gdiplusheaders.h.
FontCollection
friend class FontCollection friend
Definition at line 417 of file gdiplusheaders.h.
GraphicsPath
friend class GraphicsPath friend
Definition at line 418 of file gdiplusheaders.h.
Field Documentation
lastStatus
Status FontFamily::lastStatus mutable private
Definition at line 463 of file gdiplusheaders.h.
Referenced by Clone(), FontFamily(), FontCollection::GetFamilies(), Font::GetFamily(), GetLastStatus(), and updateStatus().
nativeFontFamily
GpFontFamily* FontFamily::nativeFontFamily private
Definition at line 462 of file gdiplusheaders.h.
Referenced by GraphicsPath::AddString(), Clone(), Font::Font(), FontFamily(), GenericMonospace(), GenericSansSerif(), GenericSerif(), GetCellAscent(), GetCellDescent(), GetEmHeight(), FontCollection::GetFamilies(), Font::GetFamily(), GetFamilyName(), GetLineSpacing(), IsAvailable(), IsStyleAvailable(), and ~FontFamily().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdiplusheaders.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h