ZEQ2-Lite: Source/Game/Game/bg_misc.c File Reference
bg_misc.c File Reference
#include "../../Shared/q_shared.h"
#include "bg_public.h"
Macros
#define QUADB1(t) (t*t)
#define QUADB1dt(t) (2*t)
#define QUADB2(t) (2*t*(1-t))
#define QUADB2dt(t) (2-4*t)
#define QUADB3(t) ((1-t)*(1-t))
#define QUADB3dt(t) (2*t-2)
Functions
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t *ps)
void BG_EvaluateTrajectory (entityState_t *es, const trajectory_t *tr, int atTime, vec3_t result)
void BG_EvaluateTrajectoryDelta (entityState_t *es, const trajectory_t *tr, int atTime, vec3_t result)
void BG_LerpQuadraticSpline (const vec3_t cp1, const vec3_t cp2, const vec3_t cp3, float t, vec3_t lerpBase)
void BG_LerpQuadraticSplineDelta (const vec3_t cp1, const vec3_t cp2, const vec3_t cp3, float t, vec3_t lerpDelta)
void BG_PlayerStateToEntityState (playerState_t *ps, entityState_t *s, qboolean snap)
void BG_TouchJumpPad (playerState_t *ps, entityState_t *jumppad)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
Variables
char * eventnames []
Macro Definition Documentation
QUADB1
#define QUADB1 (t) (t*t)
Definition at line 30 of file bg_misc.c.
QUADB1dt
#define QUADB1dt (t) (2*t)
Definition at line 34 of file bg_misc.c.
QUADB2
#define QUADB2 (t) (2*t*(1-t))
Definition at line 31 of file bg_misc.c.
QUADB2dt
#define QUADB2dt (t) (2-4*t)
Definition at line 35 of file bg_misc.c.
QUADB3
#define QUADB3 (t) ((1-t)*(1-t))
Definition at line 32 of file bg_misc.c.
QUADB3dt
#define QUADB3dt (t) (2*t-2)
Definition at line 36 of file bg_misc.c.
Function Documentation
BG_AddPredictableEventToPlayerstate()
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t * ps)
Definition at line 320 of file bg_misc.c.
{
 #ifdef _DEBUG
     {
         char buf[256];
         trap_Cvar_VariableStringBuffer("showevents", buf, sizeof(buf));
         if ( atof(buf) != 0 ) {
 #ifdef GAME
             Com_Printf(" game event svt %5d -> %5d: num = %20s parm %d\n", ps->pmove_framecount/*ps->commandTime*/, ps->eventSequence, eventnames[newEvent], eventParm);
 #else
             Com_Printf("Cgame event svt %5d -> %5d: num = %20s parm %d\n", ps->pmove_framecount/*ps->commandTime*/, ps->eventSequence, eventnames[newEvent], eventParm);
 #endif
         }
     }
 #endif
     ps->events[ps->eventSequence & (MAX_PS_EVENTS-1)] = newEvent;
     ps->eventParms[ps->eventSequence & (MAX_PS_EVENTS-1)] = eventParm;
     ps->eventSequence++;
 }
References Com_Printf(), eventnames, MAX_PS_EVENTS, and trap_Cvar_VariableStringBuffer().
Referenced by BG_TouchJumpPad(), G_AddPredictableEvent(), and PM_AddEvent().
BG_EvaluateTrajectory()
void BG_EvaluateTrajectory (entityState_t * es, const trajectory_t * tr, int atTime, vec3_t result)
Definition at line 66 of file bg_misc.c.
{
     float           deltaTime;
     float           phase;
     float           v0;
     vec3_t          dir;
     switch( tr->trType ) {
     case TR_STATIONARY:
     case TR_INTERPOLATE:
         VectorCopy( tr->trBase, result );
         break;
     case TR_LINEAR:
     case TR_DRUNKEN:
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         VectorMA( tr->trBase, deltaTime, tr->trDelta, result );
         if ( tr->trType == TR_DRUNKEN ) { // trDuration is how much the missile will wobble
             vec3_t  axis[3];
             float   ph1, ph2;
             if ( VectorNormalize2( tr->trDelta, axis[0] ) == 0.0f ) {
                 VectorSet( axis[0], 0, 0, 1 );
             }
             MakeNormalVectors( tr->trDelta, axis[1], axis[2] );
             RotateAroundDirection( axis, deltaTime );
             ph1 = sin( deltaTime * M_PI * 2 );
             ph2 = (cos( deltaTime * M_PI * 2 ) - ph1) + cos( deltaTime * M_PI * 4 );
             VectorMA( result, tr->trDuration * ph1, axis[1], result );
             VectorMA( result, tr->trDuration * ph2, axis[2], result );
         }
         break;
     case TR_SINE:
         deltaTime = ( atTime - tr->trTime ) / (float) tr->trDuration;
         phase = sin( deltaTime * M_PI * 2 );
         VectorMA( tr->trBase, phase, tr->trDelta, result );
         break;
     case TR_LINEAR_STOP:
         if ( atTime > tr->trTime + tr->trDuration ) {
             atTime = tr->trTime + tr->trDuration;
         }
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         if ( deltaTime < 0 ) {
             deltaTime = 0;
         }
         VectorMA( tr->trBase, deltaTime, tr->trDelta, result );
         break;
     case TR_GRAVITY:
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         VectorMA( tr->trBase, deltaTime, tr->trDelta, result );
         result[2] -= 0.5 * DEFAULT_GRAVITY * deltaTime * deltaTime;     // FIXME: local gravity...
         break;
     case TR_ACCEL:
         deltaTime = ( atTime - tr->trTime ) * 0.001f;   // milliseconds to seconds
         /*
             NOTE:
             There's a problem with accelerated missiles being able to
             get a negative acceleration and thus 'boomeranging' backwards.
             We want to set a minimum velocity of 0 to prevent this.
             NOTE:
             trDuration = acceleration,
         */
         VectorCopy( tr->trDelta, dir );
         v0 = VectorNormalize( dir );
         phase = v0 + tr->trDuration * deltaTime;
         if ( phase < 0 ) {
             // We have to find the point in time at which the velocity
             // becomes zero. We solve 0 = v0 + a * t for t.
             deltaTime = -v0 / tr->trDuration;
             // Now we can use this time to get the missile's position
         }
             // the 0.5*a*t^2 part.
             phase = (tr->trDuration / 2.0f) * (deltaTime * deltaTime);
             VectorMA (tr->trBase, phase, dir, result);
             // The u*t part.
             VectorMA (result, deltaTime, tr->trDelta, result);
         break;
     case TR_ARCH:
         if (!es) {
             Com_Error( ERR_DROP, "BG_EvaluateTrajectory: NULL entityState: %i", tr->trTime );
         } else {
             deltaTime = 1.0f - ( ( atTime - tr->trTime ) / (float) tr->trDuration );
             BG_LerpQuadraticSpline( tr->trBase, es->angles2, tr->trDelta, deltaTime, result );
         }
         break;
     default:
         Com_Error( ERR_DROP, "BG_EvaluateTrajectory: unknown trType: %i", tr->trTime );
         break;
     }
 }
References BG_LerpQuadraticSpline(), Com_Error(), DEFAULT_GRAVITY, dir, ERR_DROP, M_PI, MakeNormalVectors(), RotateAroundDirection(), tr, TR_ACCEL, TR_ARCH, TR_DRUNKEN, TR_GRAVITY, TR_INTERPOLATE, TR_LINEAR, TR_LINEAR_STOP, TR_SINE, TR_STATIONARY, VectorCopy, VectorMA(), VectorNormalize(), VectorNormalize2(), and VectorSet.
Referenced by CG_AddFragment(), CG_AddMoveScaleFade(), CG_AdjustPositionForMover(), CG_CalcEntityLerpPositions(), CG_CheckEvents(), CG_ClipMoveToEntities(), CG_InterpolateEntityPosition(), CG_PlayerSplash(), CG_ResetPlayerEntity(), CG_TrailFunc_SpiralBeam_Helper(), Fire_UserWeapon(), G_ExplodeUserWeapon(), G_MoverTeam(), G_RunUserMissile(), and SetMoverState().
BG_EvaluateTrajectoryDelta()
void BG_EvaluateTrajectoryDelta (entityState_t * es, const trajectory_t * tr, int atTime, vec3_t result)
Definition at line 178 of file bg_misc.c.
{
     float   deltaTime;
     float   phase;
     vec3_t  dir;
     switch( tr->trType ) {
     case TR_STATIONARY:
     case TR_INTERPOLATE:
         VectorClear( result );
         break;
     case TR_LINEAR:
     case TR_DRUNKEN:
         VectorCopy( tr->trDelta, result );
         break;
     case TR_SINE:
         deltaTime = ( atTime - tr->trTime ) / (float) tr->trDuration;
         phase = cos( deltaTime * M_PI * 2 );    // derivative of sin = cos
         phase *= 0.5;
         VectorScale( tr->trDelta, phase, result );
         break;
     case TR_LINEAR_STOP:
         if ( atTime > tr->trTime + tr->trDuration ) {
             VectorClear( result );
             return;
         }
         VectorCopy( tr->trDelta, result );
         break;
     case TR_GRAVITY:
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         VectorCopy( tr->trDelta, result );
         result[2] -= DEFAULT_GRAVITY * deltaTime;       // FIXME: local gravity...
         break;
     case TR_ACCEL:
         deltaTime = ( atTime - tr->trTime ) * 0.001;    // milliseconds to seconds
         // Turn magnitude of acceleration into a vector
         VectorCopy(tr->trDelta, dir);
         phase = VectorNormalize (dir);
         phase = phase + tr->trDuration * deltaTime;
         if ( phase < 0 ) { // prevent 'negative' velocity, clamp it at zero.
             VectorSet( dir, 0, 0, 0);
         } else {
             VectorScale (dir, tr->trDuration, dir);
         }
         // u + t * a = v
         VectorMA (tr->trDelta, deltaTime, dir, result);
         break;
     case TR_ARCH:
         if (!es) {
             Com_Error( ERR_DROP, "BG_EvaluateTrajectory: NULL entityState: %i", tr->trTime );
         } else {
             deltaTime = 1.0f - ( ( atTime - tr->trTime ) / (float) tr->trDuration );
             BG_LerpQuadraticSplineDelta( tr->trBase, es->angles2, tr->trDelta, deltaTime, result );
             VectorNormalize( result );
             // Reverse the speed calculation we did in user_missile.c under HOM_ARCH
             VectorScale( result, 1000.0f * Distance( tr->trBase, tr->trDelta ) / (float) tr->trDuration, result );
         }
         break;
     default:
         Com_Error( ERR_DROP, "BG_EvaluateTrajectoryDelta: unknown trType: %i", tr->trTime );
         break;
     }
 }
References BG_LerpQuadraticSplineDelta(), Com_Error(), DEFAULT_GRAVITY, dir, Distance(), ERR_DROP, M_PI, tr, TR_ACCEL, TR_ARCH, TR_DRUNKEN, TR_GRAVITY, TR_INTERPOLATE, TR_LINEAR, TR_LINEAR_STOP, TR_SINE, TR_STATIONARY, VectorClear, VectorCopy, VectorMA(), VectorNormalize(), VectorScale, and VectorSet.
Referenced by CG_BeamTableUpdate(), CG_Missile(), CG_ReflectVelocity(), CG_TrailFunc_FadeTail(), G_BounceUserMissile(), G_HoldUserMissile(), and G_ImpactUserWeapon().
BG_LerpQuadraticSpline()
void BG_LerpQuadraticSpline (const vec3_t cp1, const vec3_t cp2, const vec3_t cp3, float t, vec3_t lerpBase)
Definition at line 38 of file bg_misc.c.
 {
     // CP1: Start point
     // CP2: Mid point
     // CP3: End point
     lerpBase[0] = cp1[0]*QUADB1(t) + cp2[0]*QUADB2(t) + cp3[0]*QUADB3(t);
     lerpBase[1] = cp1[1]*QUADB1(t) + cp2[1]*QUADB2(t) + cp3[1]*QUADB3(t);
     lerpBase[2] = cp1[2]*QUADB1(t) + cp2[2]*QUADB2(t) + cp3[2]*QUADB3(t);
 }
References QUADB1, QUADB2, and QUADB3.
Referenced by BG_EvaluateTrajectory().
BG_LerpQuadraticSplineDelta()
void BG_LerpQuadraticSplineDelta (const vec3_t cp1, const vec3_t cp2, const vec3_t cp3, float t, vec3_t lerpDelta)
Definition at line 48 of file bg_misc.c.
 {
     // CP1: Start point
     // CP2: Mid point
     // CP3: End point
     lerpDelta[0] = cp1[0]*QUADB1(t) + cp2[0]*QUADB2(t) + cp3[0]*QUADB3(t);
     lerpDelta[1] = cp1[1]*QUADB1(t) + cp2[1]*QUADB2(t) + cp3[1]*QUADB3(t);
     lerpDelta[2] = cp1[2]*QUADB1(t) + cp2[2]*QUADB2(t) + cp3[2]*QUADB3(t);
     VectorInverse( lerpDelta );
 }
References QUADB1, QUADB2, QUADB3, and VectorInverse().
Referenced by BG_EvaluateTrajectoryDelta().
BG_PlayerStateToEntityState()
void BG_PlayerStateToEntityState (playerState_t * ps, entityState_t * s, qboolean snap)
Definition at line 383 of file bg_misc.c.
{
     int i;
     int time;
     time = ps->commandTime;
     if(ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPECTATOR){s->eType = ET_INVISIBLE;}
     else{s->eType = ET_PLAYER;}
     s->number = ps->clientNum;
     s->pos.trType = TR_INTERPOLATE;
     VectorCopy( ps->origin, s->pos.trBase );
     if(snap){
         SnapVector(s->pos.trBase);
     }
     VectorCopy(ps->velocity,s->pos.trDelta);
     s->pos.trTime = time;
     s->pos.trDuration = 50;
     s->apos.trType = TR_INTERPOLATE;
     if(ps->weaponstate != WEAPON_GUIDING && ps->weaponstate != WEAPON_ALTGUIDING && !(ps->bitFlags & isDead) && !(ps->bitFlags & isUnconcious) && !(ps->bitFlags & isCrashed) && !(ps->bitFlags & usingAlter)){
         VectorCopy(ps->viewangles,s->apos.trBase);
         if(snap){SnapVector(s->apos.trBase);}
     }
     s->angles2[YAW] = ps->movementDir;
     s->legsAnim = ps->legsAnim;
     s->torsoAnim = ps->torsoAnim;
     s->clientNum = ps->clientNum;
     s->eFlags = ps->eFlags;
     if(ps->externalEvent){
         s->event = ps->externalEvent;
         s->eventParm = ps->externalEventParm;
     }
     else if(ps->entityEventSequence < ps->eventSequence){
         int seq;
         if(ps->entityEventSequence < ps->eventSequence - MAX_PS_EVENTS){
             ps->entityEventSequence = ps->eventSequence - MAX_PS_EVENTS;
         }
         seq = ps->entityEventSequence & (MAX_PS_EVENTS-1);
         s->event = ps->events[seq] | ((ps->entityEventSequence & 3 ) << 8);
         s->eventParm = ps->eventParms[ seq ];
         ps->entityEventSequence++;
     }
     s->weapon = ps->weapon;
     s->weaponstate = ps->weaponstate;
     s->playerBitFlags = ps->bitFlags;
     s->attackPowerCurrent = ps->powerLevel[plHealth];
     s->attackPowerTotal = ps->powerLevel[plMaximum];
     s->charge1.chBase = ps->stats[stChargePercentPrimary];
     s->charge2.chBase = ps->stats[stChargePercentSecondary];
     s->groundEntityNum = ps->groundEntityNum;
     s->tier = ps->powerLevel[plTierCurrent];
     s->powerups = 0;
     for(i = 0;i < MAX_POWERUPS;i++){
         if ( ps->powerups[ i ] ) {
             s->powerups |= 1 << i;
         }
     }
     s->loopSound = ps->loopSound;
     s->generic1 = ps->generic1;
 }
References ET_INVISIBLE, ET_PLAYER, isCrashed, isDead, isUnconcious, MAX_POWERUPS, MAX_PS_EVENTS, plHealth, plMaximum, plTierCurrent, PM_INTERMISSION, PM_SPECTATOR, SnapVector, stChargePercentPrimary, stChargePercentSecondary, TR_INTERPOLATE, usingAlter, VectorCopy, WEAPON_ALTGUIDING, WEAPON_GUIDING, and YAW.
Referenced by CG_AddPacketEntities(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_TransitionSnapshot(), ClientEndFrame(), ClientSpawn(), ClientThink_real(), SendPendingPredictableEvents(), and TeleportPlayer().
BG_TouchJumpPad()
void BG_TouchJumpPad (playerState_t * ps, entityState_t * jumppad)
Definition at line 345 of file bg_misc.c.
{
     vec3_t  angles;
     float p;
     int effectNum;
     // spectators don't use jump pads
     if ( ps->pm_type != PM_NORMAL ) {
         return;
     }
     // if we didn't hit this same jumppad the previous frame
     // then don't play the event sound again if we are in a fat trigger
     if ( ps->jumppad_ent != jumppad->number ) {
         vectoangles( jumppad->origin2, angles);
         p = fabs( AngleNormalize180( angles[PITCH] ) );
         if( p < 45 ) {
             effectNum = 0;
         } else {
             effectNum = 1;
         }
         BG_AddPredictableEventToPlayerstate( EV_JUMP_PAD, effectNum, ps );
     }
     // remember hitting this jumppad this frame
     ps->jumppad_ent = jumppad->number;
     ps->jumppad_frame = ps->pmove_framecount;
     // give the player the velocity from the jumppad
     VectorCopy( jumppad->origin2, ps->velocity );
 }
References AngleNormalize180(), angles, BG_AddPredictableEventToPlayerstate(), EV_JUMP_PAD, PITCH, PM_NORMAL, vectoangles(), and VectorCopy.
Referenced by CG_TouchTriggerPrediction(), and trigger_push_touch().
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
Definition at line 72 of file cg_syscalls.c.
{
     syscall( CG_CVAR_VARIABLESTRINGBUFFER, var_name, buffer, bufsize );
 }
Referenced by BG_AddPredictableEventToPlayerstate().
Variable Documentation
eventnames
char* eventnames[]
Definition at line 244 of file bg_misc.c.
Referenced by BG_AddPredictableEventToPlayerstate().