ZEQ2-Lite: Source/Engine/jpeg-8c/jdmerge.c File Reference
jdmerge.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_upsampler
Macros
#define FIX(x) ((INT32) ((x) * (1L<<SCALEBITS) + 0.5))
#define JPEG_INTERNALS
#define ONE_HALF ((INT32) 1 << (SCALEBITS-1))
#define SCALEBITS 16 /* speediest right-shift on some machines */
Typedefs
typedef my_upsampler * my_upsample_ptr
Functions
build_ycc_rgb_table (j_decompress_ptr cinfo)
h2v1_merged_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION in_row_group_ctr, JSAMPARRAY output_buf)
h2v2_merged_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION in_row_group_ctr, JSAMPARRAY output_buf)
jinit_merged_upsampler (j_decompress_ptr cinfo)
merged_1v_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION *in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
merged_2v_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION *in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
start_pass_merged_upsample (j_decompress_ptr cinfo)
Macro Definition Documentation
FIX
#define FIX (x) ((INT32) ((x) * (1L<<SCALEBITS) + 0.5))
Definition at line 74 of file jdmerge.c.
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 35 of file jdmerge.c.
ONE_HALF
#define ONE_HALF ((INT32) 1 << (SCALEBITS-1))
Definition at line 73 of file jdmerge.c.
SCALEBITS
#define SCALEBITS 16 /* speediest right-shift on some machines */
Definition at line 72 of file jdmerge.c.
Typedef Documentation
my_upsample_ptr
typedef my_upsampler* my_upsample_ptr
Definition at line 70 of file jdmerge.c.
Function Documentation
build_ycc_rgb_table()
build_ycc_rgb_table (j_decompress_ptr cinfo)
Definition at line 83 of file jdmerge.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   int i;
   INT32 x;
   SHIFT_TEMPS
   upsample->Cr_r_tab = (int *)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 (MAXJSAMPLE+1) * SIZEOF(int));
   upsample->Cb_b_tab = (int *)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 (MAXJSAMPLE+1) * SIZEOF(int));
   upsample->Cr_g_tab = (INT32 *)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 (MAXJSAMPLE+1) * SIZEOF(INT32));
   upsample->Cb_g_tab = (INT32 *)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 (MAXJSAMPLE+1) * SIZEOF(INT32));
   for (i = 0, x = -CENTERJSAMPLE; i <= MAXJSAMPLE; i++, x++) {
     /* i is the actual input pixel value, in the range 0..MAXJSAMPLE */
     /* The Cb or Cr value we are thinking of is x = i - CENTERJSAMPLE */
     /* Cr=>R value is nearest int to 1.40200 * x */
     upsample->Cr_r_tab[i] = (int)
             RIGHT_SHIFT(FIX(1.40200) * x + ONE_HALF, SCALEBITS);
     /* Cb=>B value is nearest int to 1.77200 * x */
     upsample->Cb_b_tab[i] = (int)
             RIGHT_SHIFT(FIX(1.77200) * x + ONE_HALF, SCALEBITS);
     /* Cr=>G value is scaled-up -0.71414 * x */
     upsample->Cr_g_tab[i] = (- FIX(0.71414)) * x;
     /* Cb=>G value is scaled-up -0.34414 * x */
     /* We also add in ONE_HALF so that need not do it in inner loop */
     upsample->Cb_g_tab[i] = (- FIX(0.34414)) * x + ONE_HALF;
   }
 }
References my_upsampler::Cb_b_tab, my_upsampler::Cb_g_tab, CENTERJSAMPLE, my_upsampler::Cr_g_tab, my_upsampler::Cr_r_tab, FIX, int(), JPOOL_IMAGE, MAXJSAMPLE, ONE_HALF, RIGHT_SHIFT, SCALEBITS, SHIFT_TEMPS, and SIZEOF.
Referenced by jinit_merged_upsampler().
h2v1_merged_upsample()
h2v1_merged_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION in_row_group_ctr, JSAMPARRAY output_buf)
Definition at line 226 of file jdmerge.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   register int y, cred, cgreen, cblue;
   int cb, cr;
   register JSAMPROW outptr;
   JSAMPROW inptr0, inptr1, inptr2;
   JDIMENSION col;
   /* copy these pointers into registers if possible */
   register JSAMPLE * range_limit = cinfo->sample_range_limit;
   int * Crrtab = upsample->Cr_r_tab;
   int * Cbbtab = upsample->Cb_b_tab;
   INT32 * Crgtab = upsample->Cr_g_tab;
   INT32 * Cbgtab = upsample->Cb_g_tab;
   SHIFT_TEMPS
   inptr0 = input_buf[0][in_row_group_ctr];
   inptr1 = input_buf[1][in_row_group_ctr];
   inptr2 = input_buf[2][in_row_group_ctr];
   outptr = output_buf[0];
   /* Loop for each pair of output pixels */
   for (col = cinfo->output_width >> 1; col > 0; col--) {
     /* Do the chroma part of the calculation */
     cb = GETJSAMPLE(*inptr1++);
     cr = GETJSAMPLE(*inptr2++);
     cred = Crrtab[cr];
     cgreen = (int) RIGHT_SHIFT(Cbgtab[cb] + Crgtab[cr], SCALEBITS);
     cblue = Cbbtab[cb];
     /* Fetch 2 Y values and emit 2 pixels */
     y  = GETJSAMPLE(*inptr0++);
     outptr[RGB_RED] =   range_limit[y + cred];
     outptr[RGB_GREEN] = range_limit[y + cgreen];
     outptr[RGB_BLUE] =  range_limit[y + cblue];
     outptr += RGB_PIXELSIZE;
     y  = GETJSAMPLE(*inptr0++);
     outptr[RGB_RED] =   range_limit[y + cred];
     outptr[RGB_GREEN] = range_limit[y + cgreen];
     outptr[RGB_BLUE] =  range_limit[y + cblue];
     outptr += RGB_PIXELSIZE;
   }
   /* If image width is odd, do the last output column separately */
   if (cinfo->output_width & 1) {
     cb = GETJSAMPLE(*inptr1);
     cr = GETJSAMPLE(*inptr2);
     cred = Crrtab[cr];
     cgreen = (int) RIGHT_SHIFT(Cbgtab[cb] + Crgtab[cr], SCALEBITS);
     cblue = Cbbtab[cb];
     y  = GETJSAMPLE(*inptr0);
     outptr[RGB_RED] =   range_limit[y + cred];
     outptr[RGB_GREEN] = range_limit[y + cgreen];
     outptr[RGB_BLUE] =  range_limit[y + cblue];
   }
 }
References my_upsampler::Cb_b_tab, my_upsampler::Cb_g_tab, cr, my_upsampler::Cr_g_tab, my_upsampler::Cr_r_tab, GETJSAMPLE, int(), output_buf, RIGHT_SHIFT, SCALEBITS, and SHIFT_TEMPS.
Referenced by jinit_merged_upsampler().
h2v2_merged_upsample()
h2v2_merged_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION in_row_group_ctr, JSAMPARRAY output_buf)
Definition at line 288 of file jdmerge.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   register int y, cred, cgreen, cblue;
   int cb, cr;
   register JSAMPROW outptr0, outptr1;
   JSAMPROW inptr00, inptr01, inptr1, inptr2;
   JDIMENSION col;
   /* copy these pointers into registers if possible */
   register JSAMPLE * range_limit = cinfo->sample_range_limit;
   int * Crrtab = upsample->Cr_r_tab;
   int * Cbbtab = upsample->Cb_b_tab;
   INT32 * Crgtab = upsample->Cr_g_tab;
   INT32 * Cbgtab = upsample->Cb_g_tab;
   SHIFT_TEMPS
   inptr00 = input_buf[0][in_row_group_ctr*2];
   inptr01 = input_buf[0][in_row_group_ctr*2 + 1];
   inptr1 = input_buf[1][in_row_group_ctr];
   inptr2 = input_buf[2][in_row_group_ctr];
   outptr0 = output_buf[0];
   outptr1 = output_buf[1];
   /* Loop for each group of output pixels */
   for (col = cinfo->output_width >> 1; col > 0; col--) {
     /* Do the chroma part of the calculation */
     cb = GETJSAMPLE(*inptr1++);
     cr = GETJSAMPLE(*inptr2++);
     cred = Crrtab[cr];
     cgreen = (int) RIGHT_SHIFT(Cbgtab[cb] + Crgtab[cr], SCALEBITS);
     cblue = Cbbtab[cb];
     /* Fetch 4 Y values and emit 4 pixels */
     y  = GETJSAMPLE(*inptr00++);
     outptr0[RGB_RED] =   range_limit[y + cred];
     outptr0[RGB_GREEN] = range_limit[y + cgreen];
     outptr0[RGB_BLUE] =  range_limit[y + cblue];
     outptr0 += RGB_PIXELSIZE;
     y  = GETJSAMPLE(*inptr00++);
     outptr0[RGB_RED] =   range_limit[y + cred];
     outptr0[RGB_GREEN] = range_limit[y + cgreen];
     outptr0[RGB_BLUE] =  range_limit[y + cblue];
     outptr0 += RGB_PIXELSIZE;
     y  = GETJSAMPLE(*inptr01++);
     outptr1[RGB_RED] =   range_limit[y + cred];
     outptr1[RGB_GREEN] = range_limit[y + cgreen];
     outptr1[RGB_BLUE] =  range_limit[y + cblue];
     outptr1 += RGB_PIXELSIZE;
     y  = GETJSAMPLE(*inptr01++);
     outptr1[RGB_RED] =   range_limit[y + cred];
     outptr1[RGB_GREEN] = range_limit[y + cgreen];
     outptr1[RGB_BLUE] =  range_limit[y + cblue];
     outptr1 += RGB_PIXELSIZE;
   }
   /* If image width is odd, do the last output column separately */
   if (cinfo->output_width & 1) {
     cb = GETJSAMPLE(*inptr1);
     cr = GETJSAMPLE(*inptr2);
     cred = Crrtab[cr];
     cgreen = (int) RIGHT_SHIFT(Cbgtab[cb] + Crgtab[cr], SCALEBITS);
     cblue = Cbbtab[cb];
     y  = GETJSAMPLE(*inptr00);
     outptr0[RGB_RED] =   range_limit[y + cred];
     outptr0[RGB_GREEN] = range_limit[y + cgreen];
     outptr0[RGB_BLUE] =  range_limit[y + cblue];
     y  = GETJSAMPLE(*inptr01);
     outptr1[RGB_RED] =   range_limit[y + cred];
     outptr1[RGB_GREEN] = range_limit[y + cgreen];
     outptr1[RGB_BLUE] =  range_limit[y + cblue];
   }
 }
References my_upsampler::Cb_b_tab, my_upsampler::Cb_g_tab, cr, my_upsampler::Cr_g_tab, my_upsampler::Cr_r_tab, GETJSAMPLE, int(), output_buf, RIGHT_SHIFT, SCALEBITS, and SHIFT_TEMPS.
Referenced by jinit_merged_upsampler().
jinit_merged_upsampler()
jinit_merged_upsampler (j_decompress_ptr cinfo)
Definition at line 370 of file jdmerge.c.
 {
   my_upsample_ptr upsample;
   upsample = (my_upsample_ptr)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 SIZEOF(my_upsampler));
   cinfo->upsample = (struct jpeg_upsampler *) upsample;
   upsample->pub.start_pass = start_pass_merged_upsample;
   upsample->pub.need_context_rows = FALSE;
   upsample->out_row_width = cinfo->output_width * cinfo->out_color_components;
   if (cinfo->max_v_samp_factor == 2) {
     upsample->pub.upsample = merged_2v_upsample;
     upsample->upmethod = h2v2_merged_upsample;
     /* Allocate a spare row buffer */
     upsample->spare_row = (JSAMPROW)
       (*cinfo->mem->alloc_large) ((j_common_ptr) cinfo, JPOOL_IMAGE,
         (size_t) (upsample->out_row_width * SIZEOF(JSAMPLE)));
   } else {
     upsample->pub.upsample = merged_1v_upsample;
     upsample->upmethod = h2v1_merged_upsample;
     /* No spare row needed */
     upsample->spare_row = NULL;
   }
   build_ycc_rgb_table(cinfo);
 }
References build_ycc_rgb_table(), FALSE, h2v1_merged_upsample(), h2v2_merged_upsample(), JPOOL_IMAGE, merged_1v_upsample(), merged_2v_upsample(), jpeg_upsampler::need_context_rows, NULL, my_upsampler::out_row_width, my_upsampler::pub, SIZEOF, my_upsampler::spare_row, and start_pass_merged_upsample().
Referenced by master_selection().
merged_1v_upsample()
merged_1v_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION * in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 193 of file jdmerge.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   /* Just do the upsampling. */
   (*upsample->upmethod) (cinfo, input_buf, *in_row_group_ctr,
              output_buf + *out_row_ctr);
   /* Adjust counts */
   (*out_row_ctr)++;
   (*in_row_group_ctr)++;
 }
References output_buf.
Referenced by jinit_merged_upsampler().
merged_2v_upsample()
merged_2v_upsample (j_decompress_ptr cinfo, JSAMPIMAGE input_buf, JDIMENSION * in_row_group_ctr, JDIMENSION in_row_groups_avail, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 144 of file jdmerge.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   JSAMPROW work_ptrs[2];
   JDIMENSION num_rows;      /* number of rows returned to caller */
   if (upsample->spare_full) {
     /* If we have a spare row saved from a previous cycle, just return it. */
     jcopy_sample_rows(& upsample->spare_row, 0, output_buf + *out_row_ctr, 0,
               1, upsample->out_row_width);
     num_rows = 1;
     upsample->spare_full = FALSE;
   } else {
     /* Figure number of rows to return to caller. */
     num_rows = 2;
     /* Not more than the distance to the end of the image. */
     if (num_rows > upsample->rows_to_go)
       num_rows = upsample->rows_to_go;
     /* And not more than what the client can accept: */
     out_rows_avail -= *out_row_ctr;
     if (num_rows > out_rows_avail)
       num_rows = out_rows_avail;
     /* Create output pointer array for upsampler. */
     work_ptrs[0] = output_buf[*out_row_ctr];
     if (num_rows > 1) {
       work_ptrs[1] = output_buf[*out_row_ctr + 1];
     } else {
       work_ptrs[1] = upsample->spare_row;
       upsample->spare_full = TRUE;
     }
     /* Now do the upsampling. */
     (*upsample->upmethod) (cinfo, input_buf, *in_row_group_ctr, work_ptrs);
   }
   /* Adjust counts */
   *out_row_ctr += num_rows;
   upsample->rows_to_go -= num_rows;
   /* When the buffer is emptied, declare this input row group consumed */
   if (! upsample->spare_full)
     (*in_row_group_ctr)++;
 }
References FALSE, jcopy_sample_rows(), num_rows, my_upsampler::out_row_width, output_buf, my_upsampler::rows_to_go, my_upsampler::spare_full, my_upsampler::spare_row, and TRUE.
Referenced by jinit_merged_upsampler().
start_pass_merged_upsample()
start_pass_merged_upsample (j_decompress_ptr cinfo)
Definition at line 126 of file jdmerge.c.
 {
   my_upsample_ptr upsample = (my_upsample_ptr) cinfo->upsample;
   /* Mark the spare buffer empty */
   upsample->spare_full = FALSE;
   /* Initialize total-height counter for detecting bottom of image */
   upsample->rows_to_go = cinfo->output_height;
 }
References FALSE, my_upsampler::rows_to_go, and my_upsampler::spare_full.
Referenced by jinit_merged_upsampler().