ZEQ2-Lite: Source/Game/Game/g_weapPhysParser.h File Reference
g_weapPhysParser.h File Reference
#include "g_local.h"
Data Structures
struct g_weapPhysDefinitionRef_t
struct g_weapPhysField_t
struct g_weapPhysImportRef_t
struct g_weapPhysLinkRef_t
struct g_weapPhysParser_t
struct g_weapPhysScanner_t
struct g_weapPhysToken_t
Macros
#define MAX_DEFINES 64
#define MAX_IMPORTS 16
#define MAX_LINKS 6
#define MAX_RECURSION_DEPTH 5
#define MAX_SCRIPT_LENGTH 8192
#define MAX_TOKENSTRING_LENGTH MAX_QPATH
#define TOKEN_CATEGORY 21
#define TOKEN_CLOSEBLOCK 2
#define TOKEN_CLOSERANGE 6
#define TOKEN_CLOSEVECTOR 4
#define TOKEN_COLON 13
#define TOKEN_EOF 0
#define TOKEN_EQUALS 11
#define TOKEN_FALSE 15
#define TOKEN_FIELD 20
#define TOKEN_FLOAT 18
#define TOKEN_IMPORT 7
#define TOKEN_INTEGER 17
#define TOKEN_NULL 16
#define TOKEN_OPENBLOCK 1
#define TOKEN_OPENRANGE 5
#define TOKEN_OPENVECTOR 3
#define TOKEN_PLUS 12
#define TOKEN_PRIVATE 10
#define TOKEN_PROTECTED 9
#define TOKEN_PUBLIC 8
#define TOKEN_STRING 19
#define TOKEN_TRUE 14
#define TOKEN_WEAPON 22
Enumerations
enum g_weapPhysAccessLvls_t { LVL_PUBLIC, LVL_PROTECTED, LVL_PRIVATE }
enum g_weapPhysCategoryIndex_t {
CAT_PHYSICS, CAT_COSTS, CAT_DETONATION, CAT_MUZZLE,
CAT_TRAJECTORY, CAT_REQUIREMENT, CAT_RESTRICT
}
enum g_weapPhysError_t {
ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, ERROR_PREMATURE_EOF, ERROR_STRING_TOOBIG,
ERROR_TOKEN_TOOBIG, ERROR_UNKNOWN_SYMBOL, ERROR_UNEXPECTED_SYMBOL, ERROR_STRING_EXPECTED,
ERROR_INTEGER_EXPECTED, ERROR_FLOAT_EXPECTED, ERROR_BOOLEAN_EXPECTED, ERROR_IMPORTS_EXCEEDED,
ERROR_IMPORT_REDEFINED, ERROR_IMPORT_DOUBLED, ERROR_IMPORT_UNDEFINED, ERROR_REDEFINE_IMPORT_AS_DEFINITION,
ERROR_DEFINITIONS_EXCEEDED, ERROR_DEFINITION_REDEFINED, ERROR_DEFINITION_UNDEFINED, ERROR_LINK_BOUNDS,
ERROR_LINK_REDEFINED, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INVERTED_RANGE, ERROR_OVER_MAXBOUND,
ERROR_UNDER_MINBOUND, ERROR_OVER_MAXVECTORELEMS, ERROR_UNKNOWN_ENUMTYPE, ERROR_MAX_RECURSION,
ERROR_INHERITING_PRIVATE, ERROR_IMPORTING_NON_PUBLIC, ERROR_OVERRIDING_WITH_HIGHER_ACCESS
}
Functions
qboolean G_weapPhys_AddDefinitionRef (g_weapPhysParser_t *parser, char *refname, char *pos, int line, g_weapPhysAccessLvls_t accessLvl, qboolean hasSuper, char *supername)
qboolean G_weapPhys_AddImportRef (g_weapPhysParser_t *parser, char *refname, char *filename, char *defname)
qboolean G_weapPhys_AddLinkRef (g_weapPhysParser_t *parser, int index, char *pri_refname, char *sec_refname)
void G_weapPhys_ErrorHandle (g_weapPhysError_t errorNr, g_weapPhysScanner_t *scanner, char *string1, char *string2)
int G_weapPhys_FindDefinitionRef (g_weapPhysParser_t *parser, char *refname)
int G_weapPhys_FindImportRef (g_weapPhysParser_t *parser, char *refname)
qboolean G_weapPhys_LoadFile (g_weapPhysScanner_t *scanner, char *filename)
qboolean G_weapPhys_NextSym (g_weapPhysScanner_t *scanner, g_weapPhysToken_t *token)
qboolean G_weapPhys_ParseAcceleration (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseAngleHeight (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseAngleWidth (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseBlind (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseChargeReadyPct (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseChargeTime (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseCooldownTime (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseDamage (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseDrain (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseDummy (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseDuration (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseFatigue (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseFlight (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseFlipInHeight (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseFlipInWidth (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseFOV (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseGround (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseHealth (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseImpede (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseKnockBack (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseLifetime (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMaxFatigue (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMaxHealth (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMaximum (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMaxPowerLevel (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMaxTier (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMaxTotalTier (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMinFatigue (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMinHealth (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMinPowerLevel (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMinTier (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMinTotalTier (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseMovement (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseNrShots (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseOffsetHeight (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseOffsetWidth (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParsePowerLevel (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseRadius (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseRange (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseReaction (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseRequire (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseSpeed (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseSwat (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseType (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
qboolean G_weapPhys_ParseWater (g_weapPhysParser_t *parser, g_weapPhysCategoryIndex_t category, int field)
Variables
char * g_weapPhysCategories []
g_weapPhysField_t g_weapPhysFields []
Macro Definition Documentation
MAX_DEFINES
#define MAX_DEFINES 64
Definition at line 11 of file g_weapPhysParser.h.
MAX_IMPORTS
#define MAX_IMPORTS 16
Definition at line 10 of file g_weapPhysParser.h.
MAX_LINKS
#define MAX_LINKS 6
Definition at line 12 of file g_weapPhysParser.h.
MAX_RECURSION_DEPTH
#define MAX_RECURSION_DEPTH 5
Definition at line 14 of file g_weapPhysParser.h.
MAX_SCRIPT_LENGTH
#define MAX_SCRIPT_LENGTH 8192
Definition at line 15 of file g_weapPhysParser.h.
MAX_TOKENSTRING_LENGTH
#define MAX_TOKENSTRING_LENGTH MAX_QPATH
Definition at line 16 of file g_weapPhysParser.h.
TOKEN_CATEGORY
#define TOKEN_CATEGORY 21
Definition at line 48 of file g_weapPhysParser.h.
TOKEN_CLOSEBLOCK
#define TOKEN_CLOSEBLOCK 2
Definition at line 24 of file g_weapPhysParser.h.
TOKEN_CLOSERANGE
#define TOKEN_CLOSERANGE 6
Definition at line 28 of file g_weapPhysParser.h.
TOKEN_CLOSEVECTOR
#define TOKEN_CLOSEVECTOR 4
Definition at line 26 of file g_weapPhysParser.h.
TOKEN_COLON
#define TOKEN_COLON 13
Definition at line 37 of file g_weapPhysParser.h.
TOKEN_EOF
#define TOKEN_EOF 0
Definition at line 21 of file g_weapPhysParser.h.
TOKEN_EQUALS
#define TOKEN_EQUALS 11
Definition at line 35 of file g_weapPhysParser.h.
TOKEN_FALSE
#define TOKEN_FALSE 15
Definition at line 40 of file g_weapPhysParser.h.
TOKEN_FIELD
#define TOKEN_FIELD 20
Definition at line 47 of file g_weapPhysParser.h.
TOKEN_FLOAT
#define TOKEN_FLOAT 18
Definition at line 44 of file g_weapPhysParser.h.
TOKEN_IMPORT
#define TOKEN_IMPORT 7
Definition at line 30 of file g_weapPhysParser.h.
TOKEN_INTEGER
#define TOKEN_INTEGER 17
Definition at line 43 of file g_weapPhysParser.h.
TOKEN_NULL
#define TOKEN_NULL 16
Definition at line 41 of file g_weapPhysParser.h.
TOKEN_OPENBLOCK
#define TOKEN_OPENBLOCK 1
Definition at line 23 of file g_weapPhysParser.h.
TOKEN_OPENRANGE
#define TOKEN_OPENRANGE 5
Definition at line 27 of file g_weapPhysParser.h.
TOKEN_OPENVECTOR
#define TOKEN_OPENVECTOR 3
Definition at line 25 of file g_weapPhysParser.h.
TOKEN_PLUS
#define TOKEN_PLUS 12
Definition at line 36 of file g_weapPhysParser.h.
TOKEN_PRIVATE
#define TOKEN_PRIVATE 10
Definition at line 33 of file g_weapPhysParser.h.
TOKEN_PROTECTED
#define TOKEN_PROTECTED 9
Definition at line 32 of file g_weapPhysParser.h.
TOKEN_PUBLIC
#define TOKEN_PUBLIC 8
Definition at line 31 of file g_weapPhysParser.h.
TOKEN_STRING
#define TOKEN_STRING 19
Definition at line 45 of file g_weapPhysParser.h.
TOKEN_TRUE
#define TOKEN_TRUE 14
Definition at line 39 of file g_weapPhysParser.h.
TOKEN_WEAPON
#define TOKEN_WEAPON 22
Definition at line 50 of file g_weapPhysParser.h.
Enumeration Type Documentation
g_weapPhysAccessLvls_t
enum g_weapPhysAccessLvls_t
Enumerator
LVL_PUBLIC
LVL_PROTECTED
LVL_PRIVATE
Definition at line 121 of file g_weapPhysParser.h.
              {
     LVL_PUBLIC,
     LVL_PROTECTED,
     LVL_PRIVATE
 } g_weapPhysAccessLvls_t;
g_weapPhysCategoryIndex_t
enum g_weapPhysCategoryIndex_t
Enumerator
CAT_PHYSICS
CAT_COSTS
CAT_DETONATION
CAT_MUZZLE
CAT_TRAJECTORY
CAT_REQUIREMENT
CAT_RESTRICT
Definition at line 151 of file g_weapPhysParser.h.
              {
     CAT_PHYSICS,
     CAT_COSTS,
     CAT_DETONATION,
     CAT_MUZZLE,
     CAT_TRAJECTORY,
     CAT_REQUIREMENT,
     CAT_RESTRICT
 } g_weapPhysCategoryIndex_t;
g_weapPhysError_t
enum g_weapPhysError_t
Enumerator
ERROR_FILE_NOTFOUND
ERROR_FILE_TOOBIG
ERROR_PREMATURE_EOF
ERROR_STRING_TOOBIG
ERROR_TOKEN_TOOBIG
ERROR_UNKNOWN_SYMBOL
ERROR_UNEXPECTED_SYMBOL
ERROR_STRING_EXPECTED
ERROR_INTEGER_EXPECTED
ERROR_FLOAT_EXPECTED
ERROR_BOOLEAN_EXPECTED
ERROR_IMPORTS_EXCEEDED
ERROR_IMPORT_REDEFINED
ERROR_IMPORT_DOUBLED
ERROR_IMPORT_UNDEFINED
ERROR_REDEFINE_IMPORT_AS_DEFINITION
ERROR_DEFINITIONS_EXCEEDED
ERROR_DEFINITION_REDEFINED
ERROR_DEFINITION_UNDEFINED
ERROR_LINK_BOUNDS
ERROR_LINK_REDEFINED
ERROR_FIELD_NOT_IN_CATEGORY
ERROR_INVERTED_RANGE
ERROR_OVER_MAXBOUND
ERROR_UNDER_MINBOUND
ERROR_OVER_MAXVECTORELEMS
ERROR_UNKNOWN_ENUMTYPE
ERROR_MAX_RECURSION
ERROR_INHERITING_PRIVATE
ERROR_IMPORTING_NON_PUBLIC
ERROR_OVERRIDING_WITH_HIGHER_ACCESS
Definition at line 54 of file g_weapPhysParser.h.
              {
     ERROR_FILE_NOTFOUND,
     ERROR_FILE_TOOBIG,
     ERROR_PREMATURE_EOF,
     ERROR_STRING_TOOBIG,
     ERROR_TOKEN_TOOBIG,
     ERROR_UNKNOWN_SYMBOL,
     ERROR_UNEXPECTED_SYMBOL,
     ERROR_STRING_EXPECTED,
     ERROR_INTEGER_EXPECTED,
     ERROR_FLOAT_EXPECTED,
     ERROR_BOOLEAN_EXPECTED,
     ERROR_IMPORTS_EXCEEDED,
     ERROR_IMPORT_REDEFINED,
     ERROR_IMPORT_DOUBLED,
     ERROR_IMPORT_UNDEFINED,
     ERROR_REDEFINE_IMPORT_AS_DEFINITION,
     ERROR_DEFINITIONS_EXCEEDED,
     ERROR_DEFINITION_REDEFINED,
     ERROR_DEFINITION_UNDEFINED,
     ERROR_LINK_BOUNDS,
     ERROR_LINK_REDEFINED,
     ERROR_FIELD_NOT_IN_CATEGORY,
     ERROR_INVERTED_RANGE,
     ERROR_OVER_MAXBOUND,
     ERROR_UNDER_MINBOUND,
     ERROR_OVER_MAXVECTORELEMS,
     ERROR_UNKNOWN_ENUMTYPE,
     ERROR_MAX_RECURSION,
     ERROR_INHERITING_PRIVATE,
     ERROR_IMPORTING_NON_PUBLIC,
     ERROR_OVERRIDING_WITH_HIGHER_ACCESS
 } g_weapPhysError_t;
Function Documentation
G_weapPhys_AddDefinitionRef()
qboolean G_weapPhys_AddDefinitionRef (g_weapPhysParser_t * parser, char * refname, char * pos, int line, g_weapPhysAccessLvls_t accessLvl, qboolean hasSuper, char * supername)
Definition at line 141 of file g_weapPhysAttributes.c.
{
     g_weapPhysDefinitionRef_t   *defList;
     g_weapPhysScanner_t         *scanner;
     int i;
     defList = parser->definitionRef;
     scanner = &parser->scanner;
     if ( G_weapPhys_FindImportRef( parser, refname ) ) {
         G_weapPhys_ErrorHandle( ERROR_REDEFINE_IMPORT_AS_DEFINITION, scanner, refname, NULL );
         return qfalse;
     }
     i = 0;
     while ( i < MAX_DEFINES ) {
         if ( defList[i].active ) {
             if ( !Q_stricmp( refname, defList[i].refname ) ) {
                 G_weapPhys_ErrorHandle( ERROR_DEFINITION_REDEFINED, scanner, refname, NULL );
                 return qfalse;
             }
             i++;
         } else {
             break;
         }
     }
     if ( i == MAX_DEFINES ) {
         G_weapPhys_ErrorHandle( ERROR_DEFINITIONS_EXCEEDED, scanner, NULL, NULL );
         return qfalse;
     }
     Q_strncpyz( defList[i].refname,   refname,   sizeof(defList[i].refname  ) );
     Q_strncpyz( defList[i].supername, supername, sizeof(defList[i].supername) );
     defList[i].accessLvl = accessLvl;
     defList[i].hasSuper = hasSuper;
     defList[i].active = qtrue;
     defList[i].scannerPos = pos;
     defList[i].scannerLine = line;
     // Handle some verbose output
     if ( g_verboseParse.integer ) {
         G_Printf("Added definition '%s' to attribute list.\n", defList[i].refname );
     }
     return qtrue;
 }
References g_weapPhysDefinitionRef_t::accessLvl, g_weapPhysDefinitionRef_t::active, g_weapPhysParser_t::definitionRef, ERROR_DEFINITION_REDEFINED, ERROR_DEFINITIONS_EXCEEDED, ERROR_REDEFINE_IMPORT_AS_DEFINITION, G_Printf(), g_verboseParse, G_weapPhys_ErrorHandle(), G_weapPhys_FindImportRef(), g_weapPhysDefinitionRef_t::hasSuper, vmCvar_t::integer, line, MAX_DEFINES, NULL, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysDefinitionRef_t::scannerLine, and g_weapPhysDefinitionRef_t::scannerPos.
Referenced by G_weapPhys_PreParseDefinitions().
G_weapPhys_AddImportRef()
qboolean G_weapPhys_AddImportRef (g_weapPhysParser_t * parser, char * refname, char * filename, char * defname)
Definition at line 46 of file g_weapPhysAttributes.c.
{
     g_weapPhysImportRef_t   *importList;
     g_weapPhysScanner_t     *scanner;
     int i;
     importList = parser->importRef;
     scanner = &parser->scanner;
     i = 0;
     while ( i < MAX_IMPORTS ) {
         if ( importList[i].active ) {
             if ( !Q_stricmp( refname, importList[i].refname ) ) {
                 G_weapPhys_ErrorHandle( ERROR_IMPORT_REDEFINED, scanner, refname, NULL );
                 return qfalse;
             }
             if ( !Q_stricmp( filename, importList[i].filename ) && !Q_stricmp( defname, importList[i].defname ) ) {
                 G_weapPhys_ErrorHandle( ERROR_IMPORT_DOUBLED, scanner, refname, NULL );
                 return qfalse;
             }
             i++;
         } else {
             break;
         }
     }
     if ( i == MAX_IMPORTS ) {
         G_weapPhys_ErrorHandle( ERROR_IMPORTS_EXCEEDED, scanner, NULL, NULL );
         return qfalse;
     }
     Q_strncpyz( importList[i].refname,  refname,  sizeof(importList[i].refname ) );
     Q_strncpyz( importList[i].filename, filename, sizeof(importList[i].filename) );
     Q_strncpyz( importList[i].defname,  defname,  sizeof(importList[i].defname ) );
     importList[i].active = qtrue;
     // Handle some verbose output
     if ( g_verboseParse.integer ) {
         G_Printf("Added import '%s' to attribute list.\n", importList[i].refname );
     }
     return qtrue;
 }
References g_weapPhysImportRef_t::active, ERROR_IMPORT_DOUBLED, ERROR_IMPORT_REDEFINED, ERROR_IMPORTS_EXCEEDED, G_Printf(), g_verboseParse, G_weapPhys_ErrorHandle(), g_weapPhysParser_t::importRef, vmCvar_t::integer, MAX_IMPORTS, NULL, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, and g_weapPhysParser_t::scanner.
Referenced by G_weapPhys_ParseImports().
G_weapPhys_AddLinkRef()
qboolean G_weapPhys_AddLinkRef (g_weapPhysParser_t * parser, int index, char * pri_refname, char * sec_refname)
Definition at line 200 of file g_weapPhysAttributes.c.
{
     g_weapPhysLinkRef_t *linkList;
     g_weapPhysScanner_t *scanner;
     int true_index;
     linkList = parser->linkRef;
     scanner = &parser->scanner;
     true_index = index - 1; // The script parses 1 as the first weapon, but arrays start at 0.
     if ( ( true_index < 0 ) || ( true_index > MAX_LINKS ) ) {
         G_weapPhys_ErrorHandle( ERROR_LINK_BOUNDS, scanner, NULL, NULL );
         return qfalse;
     }
     if ( linkList[true_index].active ) {
         G_weapPhys_ErrorHandle( ERROR_LINK_REDEFINED, scanner, NULL, NULL );
         return qfalse;
     }
     Q_strncpyz( linkList[true_index].pri_refname,  pri_refname,  sizeof(linkList[true_index].pri_refname ) );
     Q_strncpyz( linkList[true_index].sec_refname,  sec_refname,  sizeof(linkList[true_index].sec_refname ) );
     linkList[true_index].active = qtrue;
         // Handle some verbose output
     if ( g_verboseParse.integer ) {
         if ( !strcmp( linkList[true_index].sec_refname, "" ) ) {
             G_Printf("Added link '%s' to attribute list.\n", linkList[true_index].pri_refname );
         } else {
             G_Printf("Added link '%s | %s' to attribute list.\n", linkList[true_index].pri_refname, linkList[true_index].sec_refname );
         }
     }
     return qtrue;
 }
References g_weapPhysLinkRef_t::active, ERROR_LINK_BOUNDS, ERROR_LINK_REDEFINED, G_Printf(), g_verboseParse, G_weapPhys_ErrorHandle(), vmCvar_t::integer, g_weapPhysParser_t::linkRef, MAX_LINKS, NULL, Q_strncpyz(), qfalse, qtrue, and g_weapPhysParser_t::scanner.
Referenced by G_weapPhys_ParseLinks().
G_weapPhys_ErrorHandle()
void G_weapPhys_ErrorHandle (g_weapPhysError_t errorNr, g_weapPhysScanner_t * scanner, char * string1, char * string2)
Definition at line 66 of file g_weapPhysScanner.c.
{
     char    *file;
     int     line;
     file = scanner->filename;
     line = scanner->line + 1; // <-- Internally we start from 0, for the user we start from 1
     switch ( errorNr ) {
     case ERROR_FILE_NOTFOUND:
         G_Printf( "%s: File not found.\n", file );
         break;
     case ERROR_FILE_TOOBIG:
         G_Printf( "%s: File exceeds maximum script length.\n", file );
         break;
     case ERROR_PREMATURE_EOF:
         G_Printf( "%s(%i): Premature end of file.\n", file, line );
         break;
     case ERROR_STRING_TOOBIG:
         G_Printf( "%s(%i): String exceeds limit of %i characters.\n", file, line, MAX_TOKENSTRING_LENGTH );
         break;
     case ERROR_TOKEN_TOOBIG:
         G_Printf( "%s(%i): Symbol exceeds limit of %i characters.\n", file, line, MAX_TOKENSTRING_LENGTH );
         break;
     case ERROR_UNKNOWN_SYMBOL:
         G_Printf( "%s(%i): Unknown symbol '%s' encountered.\n", file, line, string1 );
         break;
     case ERROR_UNEXPECTED_SYMBOL:
         if ( !string2 ) {
             G_Printf( "%s(%i): Unexpected symbol '%s' found.\n", file, line, string1 );
         } else {
             G_Printf( "%s(%i): Unexpected symbol '%s' found, expected '%s'.\n", file, line, string1, string2 );
         }
         break;
     case ERROR_STRING_EXPECTED:
         G_Printf( "%s(%i): String expected. '%s' is not a string or is missing quotes.\n", file, line, string1 );
         break;
     case ERROR_INTEGER_EXPECTED:
         G_Printf( "%s(%i): Integer expected, but '%s' found.\n", file, line, string1 );
         break;
     case ERROR_FLOAT_EXPECTED:
         G_Printf( "%s(%i): Float or integer expected, but '%s' found.\n", file, line, string1 );
         break;
     case ERROR_BOOLEAN_EXPECTED:
         G_Printf( "%s(%i): Boolean expected, but '%s' found.\n", file, line, string1 );
         break;
     case ERROR_IMPORTS_EXCEEDED:
         G_Printf( "%s(%i): Trying to exceed maximum number of %i imports.\n", file, line, MAX_IMPORTS );
         break;
     case ERROR_IMPORT_REDEFINED:
         G_Printf( "%s(%i): Trying to redefine previously defined import definition '%s'.\n", file, line, string1 );
         break;
     case ERROR_IMPORT_DOUBLED:
         G_Printf( "%s(%i): Trying to duplicate a previously imported definition under the new name '%s'.\n", file, line, string1 );
         break;
     case ERROR_IMPORT_UNDEFINED:
         G_Printf( "%s(%i): Undefined import '%s' being referenced.\n", file, line, string1 );
         break;
     case ERROR_DEFINITIONS_EXCEEDED:
         G_Printf( "%s(%i): Trying to exceed maximum number of %i weapon definitions.\n", file, line, MAX_DEFINES );
         break;
     case ERROR_DEFINITION_REDEFINED:
         G_Printf( "%s(%i): Trying to redefine previously defined weapon definition '%s'.\n", file, line, string1 );
         break;
     case ERROR_DEFINITION_UNDEFINED:
         G_Printf( "%s(%i): Undefined weapon definition '%s' being referenced.\n", file, line, string1 );
         break;
     case ERROR_REDEFINE_IMPORT_AS_DEFINITION:
         G_Printf( "%s(%i): Trying to redefine previously defined import definition '%s' as a local weapon definition.\n", file, line, string1 );
         break;
     case ERROR_LINK_BOUNDS:
         G_Printf( "%s(%i): Weapon link out of bounds. Must be in range [1..6].\n", file, line );
         break;
     case ERROR_LINK_REDEFINED:
         G_Printf( "%s(%i): Trying to redefine a previously defined weapon link number.\n", file, line );
         break;
     case ERROR_FIELD_NOT_IN_CATEGORY:
         G_Printf( "%s(%i): Field '%s' is not supported by category '%s'.\n", file, line, string1, string2 );
         break;
     case ERROR_INVERTED_RANGE:
         G_Printf( "%s(%i): This range doesn't allow end value '%s' to be larger than start value '%s'.\n", file, line, string1, string2 );
         break;
     case ERROR_OVER_MAXBOUND:
         G_Printf( "%s(%i): Value '%s' is larger than maximum bound of %s.\n", file, line, string1, string2 );
         break;
     case ERROR_UNDER_MINBOUND:
         G_Printf( "%s(%i): Value '%s' is smaller than minimum bound of %s.\n", file, line, string1, string2 );
         break;
     case ERROR_OVER_MAXVECTORELEMS:
         G_Printf( "%s(%i): Element '%s' exceeds maximum storage capacity of %s elements in vector.\n", file, line, string1, string2 );
         break;
     case ERROR_UNKNOWN_ENUMTYPE:
         G_Printf( "%s(%i): Identifier '%s' is not a valid option in this enumeration type.", file, line, string1 );
         break;
     case ERROR_MAX_RECURSION:
         G_Printf( "%s: Compiler is trying to read beyond maximum recursion depth %i for overriding.\n", file, MAX_RECURSION_DEPTH );
         break;
     case ERROR_INHERITING_PRIVATE:
         G_Printf( "%s: Private definition '%s' can not be inherited.\n", file, string1 );
         break;
     case ERROR_IMPORTING_NON_PUBLIC:
         G_Printf( "%s: Non-public definition '%s' can not be imported for local use.\n", file, string1 );
         break;
     case ERROR_OVERRIDING_WITH_HIGHER_ACCESS:
         G_Printf( "%s: Definition '%s' may not be declared with higher access than its superclass.\n", file, string1 );
         break;
     default:
         G_Printf( "WEAPONSCRIPT ERROR: Unknown error occured.\n" );
         break;
     }
 }
References ERROR_BOOLEAN_EXPECTED, ERROR_DEFINITION_REDEFINED, ERROR_DEFINITION_UNDEFINED, ERROR_DEFINITIONS_EXCEEDED, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, ERROR_FLOAT_EXPECTED, ERROR_IMPORT_DOUBLED, ERROR_IMPORT_REDEFINED, ERROR_IMPORT_UNDEFINED, ERROR_IMPORTING_NON_PUBLIC, ERROR_IMPORTS_EXCEEDED, ERROR_INHERITING_PRIVATE, ERROR_INTEGER_EXPECTED, ERROR_INVERTED_RANGE, ERROR_LINK_BOUNDS, ERROR_LINK_REDEFINED, ERROR_MAX_RECURSION, ERROR_OVER_MAXBOUND, ERROR_OVER_MAXVECTORELEMS, ERROR_OVERRIDING_WITH_HIGHER_ACCESS, ERROR_PREMATURE_EOF, ERROR_REDEFINE_IMPORT_AS_DEFINITION, ERROR_STRING_EXPECTED, ERROR_STRING_TOOBIG, ERROR_TOKEN_TOOBIG, ERROR_UNDER_MINBOUND, ERROR_UNEXPECTED_SYMBOL, ERROR_UNKNOWN_ENUMTYPE, ERROR_UNKNOWN_SYMBOL, file, g_weapPhysScanner_t::filename, G_Printf(), g_weapPhysScanner_t::line, line, MAX_DEFINES, MAX_IMPORTS, MAX_RECURSION_DEPTH, and MAX_TOKENSTRING_LENGTH.
Referenced by G_weapPhys_AddDefinitionRef(), G_weapPhys_AddImportRef(), G_weapPhys_AddLinkRef(), G_weapPhys_FindDefinitionRef(), G_weapPhys_LoadFile(), G_weapPhys_NextSym(), G_weapPhys_Parse(), G_weapPhys_ParseAcceleration(), G_weapPhys_ParseAngleHeight(), G_weapPhys_ParseAngleWidth(), G_weapPhys_ParseBlind(), G_weapPhys_ParseCategories(), G_weapPhys_ParseChargeReadyPct(), G_weapPhys_ParseChargeTime(), G_weapPhys_ParseCooldownTime(), G_weapPhys_ParseDamage(), G_weapPhys_ParseDefinition(), G_weapPhys_ParseDrain(), G_weapPhys_ParseDuration(), G_weapPhys_ParseFatigue(), G_weapPhys_ParseFields(), G_weapPhys_ParseFlight(), G_weapPhys_ParseFlipInHeight(), G_weapPhys_ParseFlipInWidth(), G_weapPhys_ParseFOV(), G_weapPhys_ParseGround(), G_weapPhys_ParseHealth(), G_weapPhys_ParseImpede(), G_weapPhys_ParseImports(), G_weapPhys_ParseKnockBack(), G_weapPhys_ParseLifetime(), G_weapPhys_ParseLinks(), G_weapPhys_ParseMaxFatigue(), G_weapPhys_ParseMaxHealth(), G_weapPhys_ParseMaximum(), G_weapPhys_ParseMaxPowerLevel(), G_weapPhys_ParseMaxTier(), G_weapPhys_ParseMaxTotalTier(), G_weapPhys_ParseMinFatigue(), G_weapPhys_ParseMinHealth(), G_weapPhys_ParseMinPowerLevel(), G_weapPhys_ParseMinTier(), G_weapPhys_ParseMinTotalTier(), G_weapPhys_ParseMovement(), G_weapPhys_ParseNrShots(), G_weapPhys_ParseOffsetHeight(), G_weapPhys_ParseOffsetWidth(), G_weapPhys_ParsePowerLevel(), G_weapPhys_ParseRadius(), G_weapPhys_ParseRange(), G_weapPhys_ParseRemoteDefinition(), G_weapPhys_ParseSpeed(), G_weapPhys_ParseSwat(), G_weapPhys_ParseType(), G_weapPhys_ParseWater(), and G_weapPhys_PreParseDefinitions().
G_weapPhys_FindDefinitionRef()
int G_weapPhys_FindDefinitionRef (g_weapPhysParser_t * parser, char * refname)
Definition at line 104 of file g_weapPhysAttributes.c.
{
     g_weapPhysDefinitionRef_t   *defList;
     g_weapPhysScanner_t         *scanner;
     int i;
     int retval;
     defList = parser->definitionRef;
     scanner = &parser->scanner;
     for ( i = 0; i < MAX_DEFINES; i++ ) {
         if ( !defList[i].active ) {
             break;
         }
         if ( !Q_stricmp( refname, defList[i].refname ) ) {
             return i + 1;
         }
     }
     retval = G_weapPhys_FindImportRef( parser, refname );
     if ( !retval ) {
         G_weapPhys_ErrorHandle( ERROR_DEFINITION_UNDEFINED, scanner, refname, NULL );
         return qfalse;
     } else {
         return retval + MAX_DEFINES; // So we can seperate a local ref from an import
     }
 }
References g_weapPhysParser_t::definitionRef, ERROR_DEFINITION_UNDEFINED, G_weapPhys_ErrorHandle(), G_weapPhys_FindImportRef(), MAX_DEFINES, NULL, Q_stricmp(), qfalse, and g_weapPhysParser_t::scanner.
Referenced by G_weapPhys_ParseDefinition(), G_weapPhys_ParseLinks(), G_weapPhys_ParseRemoteDefinition(), and G_weapPhys_PreParseDefinitions().
G_weapPhys_FindImportRef()
int G_weapPhys_FindImportRef (g_weapPhysParser_t * parser, char * refname)
Definition at line 16 of file g_weapPhysAttributes.c.
{
     g_weapPhysImportRef_t   *importList;
     g_weapPhysScanner_t     *scanner;
     int i;
     importList = parser->importRef;
     scanner = &parser->scanner;
     for ( i = 0; i < MAX_IMPORTS; i++ ) {
         if ( !importList[i].active ) {
             return qfalse;
         }
         if ( !Q_stricmp( refname, importList[i].refname ) ) {
             return i + 1;
         }
     }
     return qfalse;
 }
References g_weapPhysParser_t::importRef, MAX_IMPORTS, Q_stricmp(), qfalse, and g_weapPhysParser_t::scanner.
Referenced by G_weapPhys_AddDefinitionRef(), and G_weapPhys_FindDefinitionRef().
G_weapPhys_LoadFile()
qboolean G_weapPhys_LoadFile (g_weapPhysScanner_t * scanner, char * filename)
Definition at line 533 of file g_weapPhysScanner.c.
{
     int         len;
     qhandle_t   file;
     Q_strncpyz( scanner->filename, filename, sizeof(scanner->filename) );
     // Grab filehandle
     len = trap_FS_FOpenFile( filename, &file, FS_READ );
     // File must exist, else report error
     if ( !file ) {
         G_weapPhys_ErrorHandle( ERROR_FILE_NOTFOUND, scanner, filename, NULL );
         return qfalse;
     }
     // File must not be too big, else report error
     if ( len >= ( sizeof(char) * MAX_SCRIPT_LENGTH - 1 ) ) {
         G_weapPhys_ErrorHandle( ERROR_FILE_TOOBIG, scanner, NULL, NULL );
         trap_FS_FCloseFile( file );
         return qfalse;
     }
     // Read file
     trap_FS_Read( scanner->script, len, file );
     trap_FS_FCloseFile( file );
     // Ensure null termination
     scanner->script[len] = '\0';
     // Set starting position
     scanner->line = 0;
     scanner->pos = scanner->script;
     // Handle some verbose output
     if ( g_verboseParse.integer ) {
         G_Printf( "Scriptfile '%s' has been read into memory.\n", filename );
     }
     return qtrue;
 }
References ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, file, g_weapPhysScanner_t::filename, FS_READ, G_Printf(), g_verboseParse, G_weapPhys_ErrorHandle(), vmCvar_t::integer, g_weapPhysScanner_t::line, MAX_SCRIPT_LENGTH, NULL, g_weapPhysScanner_t::pos, Q_strncpyz(), qfalse, qtrue, g_weapPhysScanner_t::script, trap_FS_FCloseFile(), trap_FS_FOpenFile(), and trap_FS_Read().
Referenced by G_weapPhys_Parse(), and G_weapPhys_ParseRemoteDefinition().
G_weapPhys_NextSym()
qboolean G_weapPhys_NextSym (g_weapPhysScanner_t * scanner, g_weapPhysToken_t * token)
Definition at line 216 of file g_weapPhysScanner.c.
{
     // Skip non-relevant characters
     while (1) {
         // Skip leading whitespace
         while( (*scanner->pos) <= ' ') {
             if( !*scanner->pos ) {
                 break;
             }
             if( *scanner->pos == '\n' ) {
                 scanner->line++;
             }
             scanner->pos++;
         }
         // Skip double slash comments
         if ( scanner->pos[0] == '/' && scanner->pos[1] == '/' ) {
             scanner->pos += 2;
             while (*scanner->pos && *scanner->pos != '\n') {
                 scanner->pos++;
             }
         }
         // Skip /* */ comments
         else if ( scanner->pos[0] == '/' && scanner->pos[1] == '*' ) {
             scanner->pos += 2;
             while ( *scanner->pos && ( scanner->pos[0] != '*' || scanner->pos[1] != '/' ) ) {
                 scanner->pos++;
             }
             if ( *scanner->pos ) {
                 scanner->pos += 2;
             }
         } else {
             break;
         }
     }
     // Handle quoted strings
     if ( *scanner->pos == '\"') {
         int len;
         len = 0;
         scanner->pos++;
         while (1) {
             if ( !(*scanner->pos) ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
                 return qfalse;
             }
             if ( *scanner->pos == '\n' ) {
                 scanner->line++;
             }
             if ( *scanner->pos == '\"' ) {
                 scanner->pos++;
                 break;
             }
             if ( (len < (MAX_TOKENSTRING_LENGTH-1)) && ( *scanner->pos >= ' ' ) ) {
                 token->stringval[len] = *scanner->pos;
                 len++;
             } else {
                 G_weapPhys_ErrorHandle( ERROR_STRING_TOOBIG, scanner, NULL, NULL );
                 return qfalse;
             }
             scanner->pos++;
         }
         token->stringval[len] = '\0';
         token->tokenSym = TOKEN_STRING;
         return qtrue;
     }
     // Handle numbers (including support for negative ones)
     if ( (( *scanner->pos >= '0' ) && ( *scanner->pos <= '9' )) || (*scanner->pos == '-') ) {
         int len;
         qboolean dot;
         len = 0;
         dot = qfalse;
         do {
             if (len < (MAX_TOKENSTRING_LENGTH-1)) {
                 token->stringval[len] = *scanner->pos;
                 len++;
             } else {
                 G_weapPhys_ErrorHandle( ERROR_TOKEN_TOOBIG, scanner, NULL, NULL );
                 return qfalse;
             }
             scanner->pos++;
             if ( ( *scanner->pos == '.' ) && !dot ) {
                 dot = qtrue;
                 if ( len < (MAX_TOKENSTRING_LENGTH-1)) {
                     token->stringval[len] = *scanner->pos;
                     len++;
                 } else {
                     G_weapPhys_ErrorHandle( ERROR_TOKEN_TOOBIG, scanner, NULL, NULL );
                     return qfalse;
                 }
                 scanner->pos++;
             }
         } while ( ( *scanner->pos >= '0' ) && ( *scanner->pos <= '9' ) );
         if ( dot ) {
             token->tokenSym = TOKEN_FLOAT;
         } else {
             token->tokenSym = TOKEN_INTEGER;
         }
         token->stringval[len] = '\0';
         token->floatval = atof( token->stringval );
         token->intval = ceil( token->floatval );
         return qtrue;
     }
     // Handle operators
     switch ( *scanner->pos ) {
     case '=':
         scanner->pos++;
         token->stringval[0] = '=';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_EQUALS;
         return qtrue;
         break;
     case '+':
         scanner->pos++;
         token->stringval[0] = '+';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_PLUS;
         return qtrue;
         break;
     case '|':
         scanner->pos++;
         token->stringval[0] = '|';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_COLON;
         return qtrue;
         break;
     case '{':
         scanner->pos++;
         token->stringval[0] = '{';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_OPENBLOCK;
         return qtrue;
         break;
     case '}':
         scanner->pos++;
         token->stringval[0] = '}';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_CLOSEBLOCK;
         return qtrue;
         break;
     case '(':
         scanner->pos++;
         token->stringval[0] = '(';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_OPENVECTOR;
         return qtrue;
         break;
     case ')':
         scanner->pos++;
         token->stringval[0] = ')';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_CLOSEVECTOR;
         return qtrue;
         break;
     case '[':
         scanner->pos++;
         token->stringval[0] = '[';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_OPENRANGE;
         return qtrue;
         break;
     case ']':
         scanner->pos++;
         token->stringval[0] = ']';
         token->stringval[1] = '\0';
         token->tokenSym = TOKEN_CLOSERANGE;
         return qtrue;
         break;
     default:
         break;
     }
     // Handle keywords
     {
         int len;
         int i;
         len = 0;
         while ( ((*scanner->pos >= 'a') && (*scanner->pos <= 'z')) ||
                 ((*scanner->pos >= 'A') && (*scanner->pos <= 'Z')) ) { // <-- Make sure we only have words
             if ( len < MAX_TOKENSTRING_LENGTH ) {
                 token->stringval[len] = *scanner->pos;
                 len++;
             } else {
                 G_weapPhys_ErrorHandle( ERROR_TOKEN_TOOBIG, scanner, NULL, NULL );
                 return qfalse;
             }
             scanner->pos++;
         }
         token->stringval[len] = '\0';
         // Check if the keyword is a category.
         for ( i = 0; strcmp( g_weapPhysCategories[i], "" ); i++ ) {
             if ( !Q_stricmp( g_weapPhysCategories[i], token->stringval ) ) {
                 token->identifierIndex = i;
                 token->tokenSym = TOKEN_CATEGORY;
                 return qtrue;
             }
         }
         // Check if the keyword is a field.
         for ( i = 0; strcmp( g_weapPhysFields[i].fieldname, "" ); i++ ) {
             // NOTE:
             // Need to do this comparison case independantly. Q_stricmp is case
             // independant, so use this instead of standard library function strcmp.
             if ( !Q_stricmp( g_weapPhysFields[i].fieldname, token->stringval ) ) {
                 token->identifierIndex = i;
                 token->tokenSym = TOKEN_FIELD;
                 return qtrue;
             }
         }
         // Check if the keyword is 'import', 'private', 'protected', 'public',
         // 'weapon', 'true', 'false', or 'null'.
         if ( !Q_stricmp( token->stringval, "import" ) ) {
             token->tokenSym = TOKEN_IMPORT;
             return qtrue;
         }
         if ( !Q_stricmp( token->stringval, "private" ) ) {
             token->tokenSym = TOKEN_PRIVATE;
             return qtrue;
         }
         if ( !Q_stricmp( token->stringval, "protected" ) ) {
             token->tokenSym = TOKEN_PROTECTED;
             return qtrue;
         }
         if ( !Q_stricmp( token->stringval, "public" ) ) {
             token->tokenSym = TOKEN_PUBLIC;
             return qtrue;
         }
         if ( !Q_stricmp( token->stringval, "weapon" ) ) {
             token->tokenSym = TOKEN_WEAPON;
             return qtrue;
         }
         if ( !Q_stricmp( token->stringval, "true" ) ) {
             token->tokenSym = TOKEN_TRUE;
             return qtrue;
         }
         if ( !Q_stricmp( token->stringval, "false" ) ) {
             token->tokenSym = TOKEN_FALSE;
             return qtrue;
         }
         if ( !Q_stricmp( token->stringval, "null" ) ) {
             token->tokenSym = TOKEN_NULL;
             return qtrue;
         }
     }
     // Handle end of file
     if ( *scanner->pos == '\0' ) {
         token->tokenSym = TOKEN_EOF;
         return qfalse;
     }
     // Return an error, because the scanned symbol is invalid
     G_weapPhys_ErrorHandle( ERROR_UNKNOWN_SYMBOL, scanner, token->stringval, NULL );
     return qfalse;
 }
References ERROR_PREMATURE_EOF, ERROR_STRING_TOOBIG, ERROR_TOKEN_TOOBIG, ERROR_UNKNOWN_SYMBOL, G_weapPhys_ErrorHandle(), g_weapPhysCategories, g_weapPhysFields, g_weapPhysScanner_t::line, MAX_TOKENSTRING_LENGTH, NULL, g_weapPhysScanner_t::pos, Q_stricmp(), qfalse, qtrue, TOKEN_CATEGORY, TOKEN_CLOSEBLOCK, TOKEN_CLOSERANGE, TOKEN_CLOSEVECTOR, TOKEN_COLON, TOKEN_EOF, TOKEN_EQUALS, TOKEN_FALSE, TOKEN_FIELD, TOKEN_FLOAT, TOKEN_IMPORT, TOKEN_INTEGER, TOKEN_NULL, TOKEN_OPENBLOCK, TOKEN_OPENRANGE, TOKEN_OPENVECTOR, TOKEN_PLUS, TOKEN_PRIVATE, TOKEN_PROTECTED, TOKEN_PUBLIC, TOKEN_STRING, TOKEN_TRUE, and TOKEN_WEAPON.
Referenced by G_weapPhys_Parse(), G_weapPhys_ParseAcceleration(), G_weapPhys_ParseAngleHeight(), G_weapPhys_ParseAngleWidth(), G_weapPhys_ParseBlind(), G_weapPhys_ParseCategories(), G_weapPhys_ParseChargeReadyPct(), G_weapPhys_ParseChargeTime(), G_weapPhys_ParseCooldownTime(), G_weapPhys_ParseDamage(), G_weapPhys_ParseDefinition(), G_weapPhys_ParseDrain(), G_weapPhys_ParseDuration(), G_weapPhys_ParseFatigue(), G_weapPhys_ParseFields(), G_weapPhys_ParseFlight(), G_weapPhys_ParseFlipInHeight(), G_weapPhys_ParseFlipInWidth(), G_weapPhys_ParseFOV(), G_weapPhys_ParseGround(), G_weapPhys_ParseHealth(), G_weapPhys_ParseImpede(), G_weapPhys_ParseImports(), G_weapPhys_ParseKnockBack(), G_weapPhys_ParseLifetime(), G_weapPhys_ParseLinks(), G_weapPhys_ParseMaxFatigue(), G_weapPhys_ParseMaxHealth(), G_weapPhys_ParseMaximum(), G_weapPhys_ParseMaxPowerLevel(), G_weapPhys_ParseMaxTier(), G_weapPhys_ParseMaxTotalTier(), G_weapPhys_ParseMinFatigue(), G_weapPhys_ParseMinHealth(), G_weapPhys_ParseMinPowerLevel(), G_weapPhys_ParseMinTier(), G_weapPhys_ParseMinTotalTier(), G_weapPhys_ParseMovement(), G_weapPhys_ParseNrShots(), G_weapPhys_ParseOffsetHeight(), G_weapPhys_ParseOffsetWidth(), G_weapPhys_ParsePowerLevel(), G_weapPhys_ParseRadius(), G_weapPhys_ParseRange(), G_weapPhys_ParseRemoteDefinition(), G_weapPhys_ParseSpeed(), G_weapPhys_ParseSwat(), G_weapPhys_ParseType(), G_weapPhys_ParseWater(), and G_weapPhys_PreParseDefinitions().
G_weapPhys_ParseAcceleration()
qboolean G_weapPhys_ParseAcceleration (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 172 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_PHYSICS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( (token->tokenSym != TOKEN_INTEGER) && (token->tokenSym != TOKEN_FLOAT) ) {
         G_weapPhys_ErrorHandle( ERROR_FLOAT_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.physics_acceleration = token->floatval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_PHYSICS, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FLOAT_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, g_userWeapon_t::physics_acceleration, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, TOKEN_FLOAT, and TOKEN_INTEGER.
G_weapPhys_ParseAngleHeight()
qboolean G_weapPhys_ParseAngleHeight (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1433 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     int rng_start, rng_end;
     if ( category != CAT_MUZZLE ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     switch ( token->tokenSym ) {
     case TOKEN_INTEGER:
         rng_start = rng_end = token->intval;
         break;
         case TOKEN_OPENRANGE:
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
         } else {
             rng_start = token->intval;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
         } else {
             rng_end = token->intval;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_CLOSERANGE ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, "]" );
             return qfalse;
         }
         break;
     default:
         G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
         return qfalse;
         break;
     }
     g_weapPhysBuffer.firing_angleH_min = rng_start;
     g_weapPhysBuffer.firing_angleH_max = rng_end;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_MUZZLE, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_PREMATURE_EOF, ERROR_UNEXPECTED_SYMBOL, g_userWeapon_t::firing_angleH_max, g_userWeapon_t::firing_angleH_min, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_CLOSERANGE, TOKEN_EOF, TOKEN_INTEGER, and TOKEN_OPENRANGE.
G_weapPhys_ParseAngleWidth()
qboolean G_weapPhys_ParseAngleWidth (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1346 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     int rng_start, rng_end;
     if ( category != CAT_MUZZLE ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     switch ( token->tokenSym ) {
     case TOKEN_INTEGER:
         rng_start = rng_end = token->intval;
         break;
     case TOKEN_OPENRANGE:
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
         } else {
             rng_start = token->intval;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
         } else {
             rng_end = token->intval;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_CLOSERANGE ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, "]" );
             return qfalse;
         }
         break;
     default:
         G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
         return qfalse;
         break;
     }
     g_weapPhysBuffer.firing_angleW_min = rng_start;
     g_weapPhysBuffer.firing_angleW_max = rng_end;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_MUZZLE, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_PREMATURE_EOF, ERROR_UNEXPECTED_SYMBOL, g_userWeapon_t::firing_angleW_max, g_userWeapon_t::firing_angleW_min, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_CLOSERANGE, TOKEN_EOF, TOKEN_INTEGER, and TOKEN_OPENRANGE.
G_weapPhys_ParseBlind()
qboolean G_weapPhys_ParseBlind (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 579 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_PHYSICS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.physics_blind = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_PHYSICS, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, g_userWeapon_t::physics_blind, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseChargeReadyPct()
qboolean G_weapPhys_ParseChargeReadyPct (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1008 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_COSTS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.costs_chargeReady = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_COSTS, g_userWeapon_t::costs_chargeReady, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseChargeTime()
qboolean G_weapPhys_ParseChargeTime (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 973 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_COSTS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.costs_chargeTime = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_COSTS, g_userWeapon_t::costs_chargeTime, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseCooldownTime()
qboolean G_weapPhys_ParseCooldownTime (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 938 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_COSTS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.costs_cooldownTime = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_COSTS, g_userWeapon_t::costs_cooldownTime, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseDamage()
qboolean G_weapPhys_ParseDamage (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1042 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_DETONATION ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.damage_damage = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     if ( token->tokenSym == TOKEN_PLUS ) {
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
             return qfalse;
         }
         g_weapPhysBuffer.damage_multiplier = token->intval;
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
     } else {
         // No + multiplier means we reset any old multiplier, to keep it from remaining
         // as a ghost.
         g_weapPhysBuffer.damage_multiplier = 0;
     }
     return qtrue;
 }
References CAT_DETONATION, g_userWeapon_t::damage_damage, g_userWeapon_t::damage_multiplier, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, TOKEN_INTEGER, and TOKEN_PLUS.
G_weapPhys_ParseDrain()
qboolean G_weapPhys_ParseDrain (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 545 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_PHYSICS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.physics_drain = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_PHYSICS, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, g_userWeapon_t::physics_drain, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseDummy()
qboolean G_weapPhys_ParseDummy (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1636 of file g_weapPhysParser.c.
{
     return qfalse;
 }
References qfalse.
G_weapPhys_ParseDuration()
qboolean G_weapPhys_ParseDuration (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 423 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_DETONATION ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.damage_radiusDuration = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_DETONATION, g_userWeapon_t::damage_radiusDuration, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseFatigue()
qboolean G_weapPhys_ParseFatigue (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 874 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_COSTS){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.costs_fatigue = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_COSTS, g_userWeapon_t::costs_fatigue, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseFlight()
qboolean G_weapPhys_ParseFlight (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 805 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_flight = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_flight, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseFlipInHeight()
qboolean G_weapPhys_ParseFlipInHeight (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1560 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_MUZZLE ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     switch ( token->tokenSym ) {
     case TOKEN_TRUE:
         g_weapPhysBuffer.firing_offsetHFlip = qtrue;
         break;
     case TOKEN_FALSE:
         g_weapPhysBuffer.firing_offsetHFlip = qfalse;
         break;
     default:
         G_weapPhys_ErrorHandle( ERROR_BOOLEAN_EXPECTED, scanner, token->stringval, NULL );
         break;
     }
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_MUZZLE, ERROR_BOOLEAN_EXPECTED, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_PREMATURE_EOF, g_userWeapon_t::firing_offsetHFlip, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, TOKEN_FALSE, and TOKEN_TRUE.
G_weapPhys_ParseFlipInWidth()
qboolean G_weapPhys_ParseFlipInWidth (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1520 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_MUZZLE ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     switch ( token->tokenSym ) {
     case TOKEN_TRUE:
         g_weapPhysBuffer.firing_offsetWFlip = qtrue;
         break;
     case TOKEN_FALSE:
         g_weapPhysBuffer.firing_offsetWFlip = qfalse;
         break;
     default:
         G_weapPhys_ErrorHandle( ERROR_BOOLEAN_EXPECTED, scanner, token->stringval, NULL );
         break;
     }
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_MUZZLE, ERROR_BOOLEAN_EXPECTED, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_PREMATURE_EOF, g_userWeapon_t::firing_offsetWFlip, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, TOKEN_FALSE, and TOKEN_TRUE.
G_weapPhys_ParseFOV()
qboolean G_weapPhys_ParseFOV (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1600 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_MUZZLE ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.homing_FOV = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_MUZZLE, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, g_userWeapon_t::homing_FOV, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseGround()
qboolean G_weapPhys_ParseGround (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 787 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_ground = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_ground, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseHealth()
qboolean G_weapPhys_ParseHealth (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 892 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_COSTS){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.costs_health = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_COSTS, g_userWeapon_t::costs_health, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseImpede()
qboolean G_weapPhys_ParseImpede (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 197 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_DETONATION){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.damage_impede = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_DETONATION, g_userWeapon_t::damage_impede, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseKnockBack()
qboolean G_weapPhys_ParseKnockBack (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1106 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_DETONATION ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.damage_extraKnockback = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_DETONATION, g_userWeapon_t::damage_extraKnockback, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseLifetime()
qboolean G_weapPhys_ParseLifetime (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 453 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_PHYSICS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.physics_lifetime = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_PHYSICS, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, g_userWeapon_t::physics_lifetime, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMaxFatigue()
qboolean G_weapPhys_ParseMaxFatigue (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 697 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_maxFatigue = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_maxFatigue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMaxHealth()
qboolean G_weapPhys_ParseMaxHealth (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 661 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_maxHealth = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_maxHealth, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMaximum()
qboolean G_weapPhys_ParseMaximum (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 910 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_COSTS && category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     if(category==CAT_COSTS){g_weapPhysBuffer.costs_maximum = token->intval;}
     if(category==CAT_REQUIREMENT){g_weapPhysBuffer.require_maximum = token->intval;}
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_COSTS, CAT_REQUIREMENT, g_userWeapon_t::costs_maximum, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_maximum, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMaxPowerLevel()
qboolean G_weapPhys_ParseMaxPowerLevel (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 625 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_maxPowerLevel = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_maxPowerLevel, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMaxTier()
qboolean G_weapPhys_ParseMaxTier (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 733 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_maxTier = token->intval+1;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_maxTier, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMaxTotalTier()
qboolean G_weapPhys_ParseMaxTotalTier (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 769 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_maxTotalTier = token->intval+1;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_maxTotalTier, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMinFatigue()
qboolean G_weapPhys_ParseMinFatigue (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 679 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_minFatigue = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_minFatigue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMinHealth()
qboolean G_weapPhys_ParseMinHealth (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 643 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_minHealth = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_minHealth, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMinPowerLevel()
qboolean G_weapPhys_ParseMinPowerLevel (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 607 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_minPowerLevel = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_minPowerLevel, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMinTier()
qboolean G_weapPhys_ParseMinTier (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 715 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_minTier = token->intval+1;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_minTier, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMinTotalTier()
qboolean G_weapPhys_ParseMinTotalTier (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 751 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_minTotalTier = token->intval+1;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_minTotalTier, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseMovement()
qboolean G_weapPhys_ParseMovement (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 516 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category != CAT_RESTRICT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym != TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.restrict_movement = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){
             G_weapPhys_ErrorHandle(ERROR_PREMATURE_EOF,scanner,NULL,NULL);
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_RESTRICT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::restrict_movement, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseNrShots()
qboolean G_weapPhys_ParseNrShots (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1141 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_MUZZLE ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.firing_nrShots = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_MUZZLE, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, g_userWeapon_t::firing_nrShots, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseOffsetHeight()
qboolean G_weapPhys_ParseOffsetHeight (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1261 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     int rng_start, rng_end;
     if ( category != CAT_MUZZLE ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     switch ( token->tokenSym ) {
     case TOKEN_INTEGER:
         rng_start = rng_end = token->intval;
         break;
     case TOKEN_OPENRANGE:
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
         } else {
             rng_start = token->intval;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
         } else {
             rng_end = token->intval;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_CLOSERANGE ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, "]" );
             return qfalse;
         }
         break;
     default:
         G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.firing_offsetH_min = rng_start;
     g_weapPhysBuffer.firing_offsetH_max = rng_end;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_MUZZLE, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_PREMATURE_EOF, ERROR_UNEXPECTED_SYMBOL, g_userWeapon_t::firing_offsetH_max, g_userWeapon_t::firing_offsetH_min, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_CLOSERANGE, TOKEN_EOF, TOKEN_INTEGER, and TOKEN_OPENRANGE.
G_weapPhys_ParseOffsetWidth()
qboolean G_weapPhys_ParseOffsetWidth (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 1176 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     int rng_start, rng_end;
     if ( category != CAT_MUZZLE ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     switch ( token->tokenSym ) {
     case TOKEN_INTEGER:
         rng_start = rng_end = token->intval;
         break;
     case TOKEN_OPENRANGE:
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
         } else {
             rng_start = token->intval;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
         } else {
             rng_end = token->intval;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_CLOSERANGE ) {
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, "]" );
             return qfalse;
         }
         break;
     default:
         G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.firing_offsetW_min = rng_start;
     g_weapPhysBuffer.firing_offsetW_max = rng_end;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_MUZZLE, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_PREMATURE_EOF, ERROR_UNEXPECTED_SYMBOL, g_userWeapon_t::firing_offsetW_max, g_userWeapon_t::firing_offsetW_min, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_CLOSERANGE, TOKEN_EOF, TOKEN_INTEGER, and TOKEN_OPENRANGE.
G_weapPhys_ParsePowerLevel()
qboolean G_weapPhys_ParsePowerLevel (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 849 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_COSTS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.costs_powerLevel = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_COSTS, g_userWeapon_t::costs_powerLevel, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseRadius()
qboolean G_weapPhys_ParseRadius (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 223 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( (category != CAT_PHYSICS) && (category != CAT_DETONATION) ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     switch ( category ) {
     case CAT_PHYSICS:
         g_weapPhysBuffer.physics_radius = token->intval;
         break;
     case CAT_DETONATION:
         g_weapPhysBuffer.damage_radius = token->intval;
         break;
     default:
         // shouldn't be able to happen
         break;
     }
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     if ( token->tokenSym == TOKEN_PLUS ) {
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
             return qfalse;
         }
         switch ( category ) {
         case CAT_PHYSICS:
             g_weapPhysBuffer.physics_radiusMultiplier = token->intval;
             break;
         case CAT_DETONATION:
             g_weapPhysBuffer.damage_radiusMultiplier = token->intval;
             break;
         default:
             // shouldn't be able to happen
             break;
         }
         if ( !G_weapPhys_NextSym( scanner, token ) ) {
             if ( token->tokenSym == TOKEN_EOF ) {
                 G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
             }
             return qfalse;
         }
     } else {
         // No + multiplier means we reset any old multiplier, to keep it from remaining
         // as a ghost.
         switch ( category ) {
         case CAT_PHYSICS:
             g_weapPhysBuffer.physics_radiusMultiplier = 0;
             break;
         case CAT_DETONATION:
             g_weapPhysBuffer.damage_radiusMultiplier = 0;
             break;
         default:
             // shouldn't be able to happen
             break;
         }
     }
     return qtrue;
 }
References CAT_DETONATION, CAT_PHYSICS, g_userWeapon_t::damage_radius, g_userWeapon_t::damage_radiusMultiplier, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, g_userWeapon_t::physics_radius, g_userWeapon_t::physics_radiusMultiplier, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, TOKEN_INTEGER, and TOKEN_PLUS.
G_weapPhys_ParseRange()
qboolean G_weapPhys_ParseRange (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 319 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     int rng_start, rng_end;
     if ( (category != CAT_PHYSICS) && (category != CAT_TRAJECTORY) ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     switch ( category ) {
     case CAT_PHYSICS:
         switch ( token->tokenSym ) {
         case TOKEN_INTEGER:
             rng_start = rng_end = token->intval;
             break;
         case TOKEN_OPENRANGE:
             if ( !G_weapPhys_NextSym( scanner, token ) ) {
                 if ( token->tokenSym == TOKEN_EOF ) {
                     G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
                 }
                 return qfalse;
             }
             if ( token->tokenSym != TOKEN_INTEGER ) {
                 G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
                 return qfalse;
             } else {
                 rng_start = token->intval;
             }
             if ( !G_weapPhys_NextSym( scanner, token ) ) {
                 if ( token->tokenSym == TOKEN_EOF ) {
                     G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
                 }
                 return qfalse;
             }
             if ( token->tokenSym != TOKEN_INTEGER ) {
                 G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
                 return qfalse;
             } else {
                 rng_end = token->intval;
             }
             if ( !G_weapPhys_NextSym( scanner, token ) ) {
                 if ( token->tokenSym == TOKEN_EOF ) {
                     G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
                 }
                 return qfalse;
             }
             if ( token->tokenSym != TOKEN_CLOSERANGE ) {
                 G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, "]" );
                 return qfalse;
             }
             break;
         default:
             G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
             return qfalse;
             break;
         }
         g_weapPhysBuffer.physics_range_min = rng_start;
         g_weapPhysBuffer.physics_range_max = rng_end;
         break;
     case CAT_TRAJECTORY:
         if ( token->tokenSym != TOKEN_INTEGER ) {
             G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
             return qfalse;
         }
         g_weapPhysBuffer.homing_range = token->intval;
         break;
     default:
         // shouldn't be able to happen
         break;
     }
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_PHYSICS, CAT_TRAJECTORY, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, ERROR_UNEXPECTED_SYMBOL, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, g_userWeapon_t::homing_range, NULL, g_userWeapon_t::physics_range_max, g_userWeapon_t::physics_range_min, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_CLOSERANGE, TOKEN_EOF, TOKEN_INTEGER, and TOKEN_OPENRANGE.
G_weapPhys_ParseReaction()
qboolean G_weapPhys_ParseReaction (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
G_weapPhys_ParseRequire()
qboolean G_weapPhys_ParseRequire (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
G_weapPhys_ParseSpeed()
qboolean G_weapPhys_ParseSpeed (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 137 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_PHYSICS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( (token->tokenSym != TOKEN_INTEGER) && (token->tokenSym != TOKEN_FLOAT) ) {
         G_weapPhys_ErrorHandle( ERROR_FLOAT_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.physics_speed = token->floatval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_PHYSICS, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FLOAT_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, g_userWeapon_t::physics_speed, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, TOKEN_FLOAT, and TOKEN_INTEGER.
G_weapPhys_ParseSwat()
qboolean G_weapPhys_ParseSwat (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 487 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if ( category != CAT_PHYSICS ) {
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
     }
     if ( token->tokenSym != TOKEN_INTEGER ) {
         G_weapPhys_ErrorHandle( ERROR_INTEGER_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     g_weapPhysBuffer.physics_swat = token->intval;
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_PHYSICS, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, g_userWeapon_t::physics_swat, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
G_weapPhys_ParseType()
qboolean G_weapPhys_ParseType (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 64 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t   *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     // NOTE: The sequences of the strings in these stringtables are dependant on the
     //       sequences of enumeration types in g_userweapons.h !!!
     char *Physics_strings[] = { "Missile", "Beam", "Hitscan", "Trigger", "None", "" };
     char *Detonation_strings[] = { "Ki", "" };
     char *Trajectory_strings[] = { "LineOfSight", "ProxBomb", "Guided", "Homing", "Arch", "Drunken", "Cylinder", "" };
     int i;
     if ( token->tokenSym != TOKEN_STRING ) {
         G_weapPhys_ErrorHandle( ERROR_STRING_EXPECTED, scanner, token->stringval, NULL );
         return qfalse;
     }
     switch ( category ) {
     case CAT_PHYSICS:
         for ( i = 0; Q_stricmp( Physics_strings[i], token->stringval ); i++ ) {
             if ( !strcmp( Physics_strings[i], "" )) {
                 G_weapPhys_ErrorHandle( ERROR_UNKNOWN_ENUMTYPE, scanner, token->stringval, NULL );
                 return qfalse;
             }
         }
         g_weapPhysBuffer.general_type = i;
         break;
     case CAT_DETONATION:
         for ( i = 0; Q_stricmp( Detonation_strings[i], token->stringval ); i++ ) {
             if ( !strcmp( Detonation_strings[i], "" )) {
                 G_weapPhys_ErrorHandle( ERROR_UNKNOWN_ENUMTYPE, scanner, token->stringval, NULL );
                 return qfalse;
             }
         }
         break;
     case CAT_TRAJECTORY:
         for ( i = 0; Q_stricmp( Trajectory_strings[i], token->stringval ); i++ ) {
             if ( !strcmp( Trajectory_strings[i], "" )) {
                 G_weapPhys_ErrorHandle( ERROR_UNKNOWN_ENUMTYPE, scanner, token->stringval, NULL );
                 return qfalse;
             }
         }
         g_weapPhysBuffer.homing_type = i;
         break;
     default:
         G_weapPhys_ErrorHandle( ERROR_FIELD_NOT_IN_CATEGORY, scanner, g_weapPhysFields[field].fieldname, g_weapPhysCategories[category] );
         return qfalse;
         break;
     }
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym == TOKEN_EOF ) {
             G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );
         }
         return qfalse;
     }
     return qtrue;
 }
References CAT_DETONATION, CAT_PHYSICS, CAT_TRAJECTORY, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_PREMATURE_EOF, ERROR_STRING_EXPECTED, ERROR_UNKNOWN_ENUMTYPE, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, g_userWeapon_t::general_type, g_userWeapon_t::homing_type, NULL, Q_stricmp(), qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_STRING.
G_weapPhys_ParseWater()
qboolean G_weapPhys_ParseWater (g_weapPhysParser_t * parser, g_weapPhysCategoryIndex_t category, int field)
Definition at line 823 of file g_weapPhysParser.c.
{
     g_weapPhysToken_t *token = &parser->token;
     g_weapPhysScanner_t *scanner = &parser->scanner;
     if(category!=CAT_REQUIREMENT){
         G_weapPhys_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,g_weapPhysFields[field].fieldname,g_weapPhysCategories[category]);
         return qfalse;
     }
     if(token->tokenSym!=TOKEN_INTEGER){
         G_weapPhys_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         return qfalse;
     }
     g_weapPhysBuffer.require_water = token->intval;
     if(!G_weapPhys_NextSym(scanner,token)){
         if(token->tokenSym == TOKEN_EOF){G_weapPhys_ErrorHandle( ERROR_PREMATURE_EOF, scanner, NULL, NULL );}
         return qfalse;
     }
     return qtrue;
 }
References CAT_REQUIREMENT, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_PREMATURE_EOF, G_weapPhys_ErrorHandle(), G_weapPhys_NextSym(), g_weapPhysBuffer, g_weapPhysCategories, g_weapPhysFields, NULL, qfalse, qtrue, g_userWeapon_t::require_water, g_weapPhysParser_t::scanner, g_weapPhysParser_t::token, TOKEN_EOF, and TOKEN_INTEGER.
Variable Documentation
g_weapPhysCategories
char* g_weapPhysCategories[]
Definition at line 7 of file g_weapPhysScanner.c.
Referenced by G_weapPhys_NextSym(), G_weapPhys_ParseAcceleration(), G_weapPhys_ParseAngleHeight(), G_weapPhys_ParseAngleWidth(), G_weapPhys_ParseBlind(), G_weapPhys_ParseChargeReadyPct(), G_weapPhys_ParseChargeTime(), G_weapPhys_ParseCooldownTime(), G_weapPhys_ParseDamage(), G_weapPhys_ParseDrain(), G_weapPhys_ParseDuration(), G_weapPhys_ParseFatigue(), G_weapPhys_ParseFlight(), G_weapPhys_ParseFlipInHeight(), G_weapPhys_ParseFlipInWidth(), G_weapPhys_ParseFOV(), G_weapPhys_ParseGround(), G_weapPhys_ParseHealth(), G_weapPhys_ParseImpede(), G_weapPhys_ParseKnockBack(), G_weapPhys_ParseLifetime(), G_weapPhys_ParseMaxFatigue(), G_weapPhys_ParseMaxHealth(), G_weapPhys_ParseMaximum(), G_weapPhys_ParseMaxPowerLevel(), G_weapPhys_ParseMaxTier(), G_weapPhys_ParseMaxTotalTier(), G_weapPhys_ParseMinFatigue(), G_weapPhys_ParseMinHealth(), G_weapPhys_ParseMinPowerLevel(), G_weapPhys_ParseMinTier(), G_weapPhys_ParseMinTotalTier(), G_weapPhys_ParseMovement(), G_weapPhys_ParseNrShots(), G_weapPhys_ParseOffsetHeight(), G_weapPhys_ParseOffsetWidth(), G_weapPhys_ParsePowerLevel(), G_weapPhys_ParseRadius(), G_weapPhys_ParseRange(), G_weapPhys_ParseSpeed(), G_weapPhys_ParseSwat(), G_weapPhys_ParseType(), and G_weapPhys_ParseWater().
g_weapPhysFields
g_weapPhysField_t g_weapPhysFields[]
Definition at line 11 of file g_weapPhysScanner.c.
Referenced by G_weapPhys_NextSym(), G_weapPhys_ParseAcceleration(), G_weapPhys_ParseAngleHeight(), G_weapPhys_ParseAngleWidth(), G_weapPhys_ParseBlind(), G_weapPhys_ParseChargeReadyPct(), G_weapPhys_ParseChargeTime(), G_weapPhys_ParseCooldownTime(), G_weapPhys_ParseDamage(), G_weapPhys_ParseDrain(), G_weapPhys_ParseDuration(), G_weapPhys_ParseFatigue(), G_weapPhys_ParseFields(), G_weapPhys_ParseFlight(), G_weapPhys_ParseFlipInHeight(), G_weapPhys_ParseFlipInWidth(), G_weapPhys_ParseFOV(), G_weapPhys_ParseGround(), G_weapPhys_ParseHealth(), G_weapPhys_ParseImpede(), G_weapPhys_ParseKnockBack(), G_weapPhys_ParseLifetime(), G_weapPhys_ParseMaxFatigue(), G_weapPhys_ParseMaxHealth(), G_weapPhys_ParseMaximum(), G_weapPhys_ParseMaxPowerLevel(), G_weapPhys_ParseMaxTier(), G_weapPhys_ParseMaxTotalTier(), G_weapPhys_ParseMinFatigue(), G_weapPhys_ParseMinHealth(), G_weapPhys_ParseMinPowerLevel(), G_weapPhys_ParseMinTier(), G_weapPhys_ParseMinTotalTier(), G_weapPhys_ParseMovement(), G_weapPhys_ParseNrShots(), G_weapPhys_ParseOffsetHeight(), G_weapPhys_ParseOffsetWidth(), G_weapPhys_ParsePowerLevel(), G_weapPhys_ParseRadius(), G_weapPhys_ParseRange(), G_weapPhys_ParseSpeed(), G_weapPhys_ParseSwat(), G_weapPhys_ParseType(), and G_weapPhys_ParseWater().