ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/bits/stl_map.h File Reference
stl_map.h File Reference
#include <bits/functexcept.h>
#include <bits/concept_check.h>
#include <initializer_list>
Functions
namespace std _GLIBCXX_VISIBILITY (default)
Detailed Description
This is an internal header file, included by other library headers. Do not attempt to use it directly. @headername{map}
Definition in file stl_map.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace std _GLIBCXX_VISIBILITY (default)
A standard container made up of (key,value) pairs, which can be retrieved based on a key, in logarithmic time.
Meets the requirements of a container, a reversible container, and an associative container (using unique keys). For a map<Key,T> the key_type is Key, the mapped_type is T, and the value_type is std::pair<const Key,T>.
Maps support bidirectional iterators.
The private tree data is declared exactly the same way for map and multimap; the distinction is made entirely in how the tree functions are called (*_unique versus *_equal, same as the standard).
This turns a red-black tree into a [multi]map.
The actual tree structure.
Default constructor creates no elements.
Creates a map with no elements.
Parameters
comp A comparison object.
a An allocator object.
Map copy constructor.
Parameters
x A map of identical element and allocator types.
The newly-created map uses a copy of the allocation object used by x.
Builds a map from a range.
Parameters
first An input iterator.
last An input iterator.
Create a map consisting of copies of the elements from [first,last). This is linear in N if the range is already sorted, and NlogN otherwise (where N is distance(first,last)).
Builds a map from a range.
Parameters
first An input iterator.
last An input iterator.
comp A comparison functor.
a An allocator object.
Create a map consisting of copies of the elements from [first,last). This is linear in N if the range is already sorted, and NlogN otherwise (where N is distance(first,last)).
The dtor only erases the elements, and note that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Map assignment operator.
Parameters
x A map of identical element and allocator types.
All the elements of x are copied, but unlike the copy constructor, the allocator object is not copied.
Get a copy of the memory allocation object.
Returns a read/write iterator that points to the first pair in the map. Iteration is done in ascending order according to the keys.
Returns a read-only (constant) iterator that points to the first pair in the map. Iteration is done in ascending order according to the keys.
Returns a read/write iterator that points one past the last pair in the map. Iteration is done in ascending order according to the keys.
Returns a read-only (constant) iterator that points one past the last pair in the map. Iteration is done in ascending order according to the keys.
Returns a read/write reverse iterator that points to the last pair in the map. Iteration is done in descending order according to the keys.
Returns a read-only (constant) reverse iterator that points to the last pair in the map. Iteration is done in descending order according to the keys.
Returns a read/write reverse iterator that points to one before the first pair in the map. Iteration is done in descending order according to the keys.
Returns a read-only (constant) reverse iterator that points to one before the first pair in the map. Iteration is done in descending order according to the keys.
Returns true if the map is empty. (Thus begin() would equal end().)
Returns the size of the map.
Returns the maximum size of the map.
Subscript ([]) access to map data.
Parameters
k The key for which data should be retrieved.
Returns
A reference to the data of the (key,data) pair.
Allows for easy lookup with the subscript ([]) operator. Returns data associated with the key specified in subscript. If the key does not exist, a pair with that key is created using default values, which is then returned.
Lookup requires logarithmic time.
Access to map data.
Parameters
k The key for which data should be retrieved.
Returns
A reference to the data whose key is equivalent to k, if such a data is present in the map.
Exceptions
std::out_of_range If no such data is present.
Attempts to insert a std::pair into the map.
Parameters
x Pair to be inserted (see std::make_pair for easy creation of pairs).
Returns
A pair, of which the first element is an iterator that points to the possibly inserted pair, and the second is a bool that is true if the pair was actually inserted.
This function attempts to insert a (key, value) pair into the map. A map relies on unique keys and thus a pair is only inserted if its first element (the key) is not already present in the map.
Insertion requires logarithmic time.
Attempts to insert a std::pair into the map.
Parameters
position An iterator that serves as a hint as to where the pair should be inserted.
x Pair to be inserted (see std::make_pair for easy creation of pairs).
Returns
An iterator that points to the element with key of x (may or may not be the pair passed in).
This function is not concerned about whether the insertion took place, and thus does not return a boolean like the single-argument insert() does. Note that the first parameter is only a hint and can potentially improve the performance of the insertion process. A bad hint would cause no gains in efficiency.
See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html for more on hinting.
Insertion requires logarithmic time (if the hint is not taken).
Template function that attempts to insert a range of elements.
Parameters
first Iterator pointing to the start of the range to be inserted.
last Iterator pointing to the end of the range.
Complexity similar to that of the range constructor.
Erases an element from a map.
Parameters
position An iterator pointing to the element to be erased.
This function erases an element, pointed to by the given iterator, from a map. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Erases elements according to the provided key.
Parameters
x Key of element to be erased.
Returns
The number of elements erased.
This function erases all the elements located by the given key from a map. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Erases a [first,last) range of elements from a map.
Parameters
first Iterator pointing to the start of the range to be erased.
last Iterator pointing to the end of the range to be erased.
This function erases a sequence of elements from a map. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Swaps data with another map.
Parameters
x A map of the same element and allocator types.
This exchanges the elements between two maps in constant time. (It is only swapping a pointer, an integer, and an instance of the Compare type (which itself is often stateless and empty), so it should be quite fast.) Note that the global std::swap() function is specialized such that std::swap(m1,m2) will feed to this function.
Erases all elements in a map. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Returns the key comparison object out of which the map was constructed.
Returns a value comparison object, built from the key comparison object out of which the map was constructed.
Tries to locate an element in a map.
Parameters
x Key of (key, value) pair to be located.
Returns
Iterator pointing to sought-after element, or end() if not found.
This function takes a key and tries to locate the element with which the key matches. If successful the function returns an iterator pointing to the sought after pair. If unsuccessful it returns the past-the-end (end()) iterator.
Tries to locate an element in a map.
Parameters
x Key of (key, value) pair to be located.
Returns
Read-only (constant) iterator pointing to sought-after element, or end() if not found.
This function takes a key and tries to locate the element with which the key matches. If successful the function returns a constant iterator pointing to the sought after pair. If unsuccessful it returns the past-the-end (end()) iterator.
Finds the number of elements with given key.
Parameters
x Key of (key, value) pairs to be located.
Returns
Number of elements with specified key.
This function only makes sense for multimaps; for map the result will either be 0 (not present) or 1 (present).
Finds the beginning of a subsequence matching given key.
Parameters
x Key of (key, value) pair to be located.
Returns
Iterator pointing to first element equal to or greater than key, or end().
This function returns the first element of a subsequence of elements that matches the given key. If unsuccessful it returns an iterator pointing to the first element that has a greater value than given key or end() if no such element exists.
Finds the beginning of a subsequence matching given key.
Parameters
x Key of (key, value) pair to be located.
Returns
Read-only (constant) iterator pointing to first element equal to or greater than key, or end().
This function returns the first element of a subsequence of elements that matches the given key. If unsuccessful it returns an iterator pointing to the first element that has a greater value than given key or end() if no such element exists.
Finds the end of a subsequence matching given key.
Parameters
x Key of (key, value) pair to be located.
Returns
Iterator pointing to the first element greater than key, or end().
Finds the end of a subsequence matching given key.
Parameters
x Key of (key, value) pair to be located.
Returns
Read-only (constant) iterator pointing to first iterator greater than key, or end().
Finds a subsequence matching given key.
Parameters
x Key of (key, value) pairs to be located.
Returns
Pair of iterators that possibly points to the subsequence matching given key.
This function is equivalent to
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
(but is faster than making the calls separately).
This function probably only makes sense for multimaps.
Finds a subsequence matching given key.
Parameters
x Key of (key, value) pairs to be located.
Returns
Pair of read-only (constant) iterators that possibly points to the subsequence matching given key.
This function is equivalent to
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
(but is faster than making the calls separately).
This function probably only makes sense for multimaps.
Map equality comparison.
Parameters
x A map.
y A map of the same type as x.
Returns
True iff the size and elements of the maps are equal.
This is an equivalence relation. It is linear in the size of the maps. Maps are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Map ordering relation.
Parameters
x A map.
y A map of the same type as x.
Returns
True iff x is lexicographically less than y.
This is a total ordering relation. It is linear in the size of the maps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Based on operator==
Based on operator<
Based on operator<
Based on operator<
See std::map::swap().
Definition at line 64 of file stl_map.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_CONTAINER
   template <typename _Key, typename _Tp, typename _Compare = std::less<_Key>,
             typename _Alloc = std::allocator<std::pair<const _Key, _Tp> > >
     class map
     {
     public:
       typedef _Key                                          key_type;
       typedef _Tp                                           mapped_type;
       typedef std::pair<const _Key, _Tp>                    value_type;
       typedef _Compare                                      key_compare;
       typedef _Alloc                                        allocator_type;
     private:
       // concept requirements
       typedef typename _Alloc::value_type                   _Alloc_value_type;
       __glibcxx_class_requires(_Tp, _SGIAssignableConcept)
       __glibcxx_class_requires4(_Compare, bool, _Key, _Key,
                 _BinaryFunctionConcept)
       __glibcxx_class_requires2(value_type, _Alloc_value_type, _SameTypeConcept)
     public:
       class value_compare
       : public std::binary_function<value_type, value_type, bool>
       {
     friend class map<_Key, _Tp, _Compare, _Alloc>;
       protected:
     _Compare comp;
     value_compare(_Compare __c)
     : comp(__c) { }
       public:
     bool operator()(const value_type& __x, const value_type& __y) const
     { return comp(__x.first, __y.first); }
       };
     private:
       typedef typename _Alloc::template rebind<value_type>::other
         _Pair_alloc_type;
       typedef _Rb_tree<key_type, value_type, _Select1st<value_type>,
                key_compare, _Pair_alloc_type> _Rep_type;
       _Rep_type _M_t;
     public:
       // many of these are specified differently in ISO, but the following are
       // "functionally equivalent"
       typedef typename _Pair_alloc_type::pointer         pointer;
       typedef typename _Pair_alloc_type::const_pointer   const_pointer;
       typedef typename _Pair_alloc_type::reference       reference;
       typedef typename _Pair_alloc_type::const_reference const_reference;
       typedef typename _Rep_type::iterator               iterator;
       typedef typename _Rep_type::const_iterator         const_iterator;
       typedef typename _Rep_type::size_type              size_type;
       typedef typename _Rep_type::difference_type        difference_type;
       typedef typename _Rep_type::reverse_iterator       reverse_iterator;
       typedef typename _Rep_type::const_reverse_iterator const_reverse_iterator;
       // [23.3.1.1] construct/copy/destroy
       // (get_allocator() is normally listed in this section, but seems to have
       // been accidentally omitted in the printed standard)
       map()
       : _M_t() { }
       explicit
       map(const _Compare& __comp,
       const allocator_type& __a = allocator_type())
       : _M_t(__comp, __a) { }
       map(const map& __x)
       : _M_t(__x._M_t) { }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       map(map&& __x)
       : _M_t(std::move(__x._M_t)) { }
       map(initializer_list<value_type> __l,
       const _Compare& __c = _Compare(),
       const allocator_type& __a = allocator_type())
       : _M_t(__c, __a)
       { _M_t._M_insert_unique(__l.begin(), __l.end()); }
 #endif
       template<typename _InputIterator>
         map(_InputIterator __first, _InputIterator __last)
     : _M_t()
         { _M_t._M_insert_unique(__first, __last); }
       template<typename _InputIterator>
         map(_InputIterator __first, _InputIterator __last,
         const _Compare& __comp,
         const allocator_type& __a = allocator_type())
     : _M_t(__comp, __a)
         { _M_t._M_insert_unique(__first, __last); }
       // FIXME There is no dtor declared, but we should have something
       // generated by Doxygen.  I don't know what tags to add to this
       // paragraph to make that happen:
       map&
       operator=(const map& __x)
       {
     _M_t = __x._M_t;
     return *this;
       }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       map&
       operator=(map&& __x)
       {
     // NB: DR 1204.
     // NB: DR 675.
     this->clear();
     this->swap(__x);
     return *this;
       }
       map&
       operator=(initializer_list<value_type> __l)
       {
     this->clear();
     this->insert(__l.begin(), __l.end());
     return *this;
       }
 #endif
       allocator_type
       get_allocator() const
       { return _M_t.get_allocator(); }
       // iterators
       iterator
       begin()
       { return _M_t.begin(); }
       const_iterator
       begin() const
       { return _M_t.begin(); }
       iterator
       end()
       { return _M_t.end(); }
       const_iterator
       end() const
       { return _M_t.end(); }
       reverse_iterator
       rbegin()
       { return _M_t.rbegin(); }
       const_reverse_iterator
       rbegin() const
       { return _M_t.rbegin(); }
       reverse_iterator
       rend()
       { return _M_t.rend(); }
       const_reverse_iterator
       rend() const
       { return _M_t.rend(); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       const_iterator
       cbegin() const
       { return _M_t.begin(); }
       const_iterator
       cend() const
       { return _M_t.end(); }
       const_reverse_iterator
       crbegin() const
       { return _M_t.rbegin(); }
       const_reverse_iterator
       crend() const
       { return _M_t.rend(); }
 #endif
       // capacity
       bool
       empty() const
       { return _M_t.empty(); }
       size_type
       size() const
       { return _M_t.size(); }
       size_type
       max_size() const
       { return _M_t.max_size(); }
       // [23.3.1.2] element access
       mapped_type&
       operator[](const key_type& __k)
       {
     // concept requirements
     __glibcxx_function_requires(_DefaultConstructibleConcept<mapped_type>)
     iterator __i = lower_bound(__k);
     // __i->first is greater than or equivalent to __k.
     if (__i == end() || key_comp()(__k, (*__i).first))
           __i = insert(__i, value_type(__k, mapped_type()));
     return (*__i).second;
       }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       mapped_type&
       operator[](key_type&& __k)
       {
     // concept requirements
     __glibcxx_function_requires(_DefaultConstructibleConcept<mapped_type>)
     iterator __i = lower_bound(__k);
     // __i->first is greater than or equivalent to __k.
     if (__i == end() || key_comp()(__k, (*__i).first))
           __i = insert(__i, std::make_pair(std::move(__k), mapped_type()));
     return (*__i).second;
       }
 #endif
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // DR 464. Suggestion for new member functions in standard containers.
       mapped_type&
       at(const key_type& __k)
       {
     iterator __i = lower_bound(__k);
     if (__i == end() || key_comp()(__k, (*__i).first))
       __throw_out_of_range(__N("map::at"));
     return (*__i).second;
       }
       const mapped_type&
       at(const key_type& __k) const
       {
     const_iterator __i = lower_bound(__k);
     if (__i == end() || key_comp()(__k, (*__i).first))
       __throw_out_of_range(__N("map::at"));
     return (*__i).second;
       }
       // modifiers
       std::pair<iterator, bool>
       insert(const value_type& __x)
       { return _M_t._M_insert_unique(__x); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       template<typename _Pair, typename = typename
            std::enable_if<std::is_convertible<_Pair,
                           value_type>::value>::type>
         std::pair<iterator, bool>
         insert(_Pair&& __x)
         { return _M_t._M_insert_unique(std::forward<_Pair>(__x)); }
 #endif
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       void
       insert(std::initializer_list<value_type> __list)
       { insert(__list.begin(), __list.end()); }
 #endif
       iterator
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       insert(const_iterator __position, const value_type& __x)
 #else
       insert(iterator __position, const value_type& __x)
 #endif
       { return _M_t._M_insert_unique_(__position, __x); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       template<typename _Pair, typename = typename
            std::enable_if<std::is_convertible<_Pair,
                           value_type>::value>::type>
         iterator
         insert(const_iterator __position, _Pair&& __x)
         { return _M_t._M_insert_unique_(__position,
                     std::forward<_Pair>(__x)); }
 #endif
       template<typename _InputIterator>
         void
         insert(_InputIterator __first, _InputIterator __last)
         { _M_t._M_insert_unique(__first, __last); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // DR 130. Associative erase should return an iterator.
       iterator
       erase(const_iterator __position)
       { return _M_t.erase(__position); }
 #else
       void
       erase(iterator __position)
       { _M_t.erase(__position); }
 #endif
       size_type
       erase(const key_type& __x)
       { return _M_t.erase(__x); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // DR 130. Associative erase should return an iterator.
       iterator
       erase(const_iterator __first, const_iterator __last)
       { return _M_t.erase(__first, __last); }
 #else
       void
       erase(iterator __first, iterator __last)
       { _M_t.erase(__first, __last); }
 #endif
       void
       swap(map& __x)
       { _M_t.swap(__x._M_t); }
       void
       clear()
       { _M_t.clear(); }
       // observers
       key_compare
       key_comp() const
       { return _M_t.key_comp(); }
       value_compare
       value_comp() const
       { return value_compare(_M_t.key_comp()); }
       // [23.3.1.3] map operations
       iterator
       find(const key_type& __x)
       { return _M_t.find(__x); }
       const_iterator
       find(const key_type& __x) const
       { return _M_t.find(__x); }
       size_type
       count(const key_type& __x) const
       { return _M_t.find(__x) == _M_t.end() ? 0 : 1; }
       iterator
       lower_bound(const key_type& __x)
       { return _M_t.lower_bound(__x); }
       const_iterator
       lower_bound(const key_type& __x) const
       { return _M_t.lower_bound(__x); }
       iterator
       upper_bound(const key_type& __x)
       { return _M_t.upper_bound(__x); }
       const_iterator
       upper_bound(const key_type& __x) const
       { return _M_t.upper_bound(__x); }
       std::pair<iterator, iterator>
       equal_range(const key_type& __x)
       { return _M_t.equal_range(__x); }
       std::pair<const_iterator, const_iterator>
       equal_range(const key_type& __x) const
       { return _M_t.equal_range(__x); }
       template<typename _K1, typename _T1, typename _C1, typename _A1>
         friend bool
         operator==(const map<_K1, _T1, _C1, _A1>&,
            const map<_K1, _T1, _C1, _A1>&);
       template<typename _K1, typename _T1, typename _C1, typename _A1>
         friend bool
         operator<(const map<_K1, _T1, _C1, _A1>&,
           const map<_K1, _T1, _C1, _A1>&);
     };
   template<typename _Key, typename _Tp, typename _Compare, typename _Alloc>
     inline bool
     operator==(const map<_Key, _Tp, _Compare, _Alloc>& __x,
                const map<_Key, _Tp, _Compare, _Alloc>& __y)
     { return __x._M_t == __y._M_t; }
   template<typename _Key, typename _Tp, typename _Compare, typename _Alloc>
     inline bool
     operator<(const map<_Key, _Tp, _Compare, _Alloc>& __x,
               const map<_Key, _Tp, _Compare, _Alloc>& __y)
     { return __x._M_t < __y._M_t; }
   template<typename _Key, typename _Tp, typename _Compare, typename _Alloc>
     inline bool
     operator!=(const map<_Key, _Tp, _Compare, _Alloc>& __x,
                const map<_Key, _Tp, _Compare, _Alloc>& __y)
     { return !(__x == __y); }
   template<typename _Key, typename _Tp, typename _Compare, typename _Alloc>
     inline bool
     operator>(const map<_Key, _Tp, _Compare, _Alloc>& __x,
               const map<_Key, _Tp, _Compare, _Alloc>& __y)
     { return __y < __x; }
   template<typename _Key, typename _Tp, typename _Compare, typename _Alloc>
     inline bool
     operator<=(const map<_Key, _Tp, _Compare, _Alloc>& __x,
                const map<_Key, _Tp, _Compare, _Alloc>& __y)
     { return !(__y < __x); }
   template<typename _Key, typename _Tp, typename _Compare, typename _Alloc>
     inline bool
     operator>=(const map<_Key, _Tp, _Compare, _Alloc>& __x,
                const map<_Key, _Tp, _Compare, _Alloc>& __y)
     { return !(__x < __y); }
   template<typename _Key, typename _Tp, typename _Compare, typename _Alloc>
     inline void
     swap(map<_Key, _Tp, _Compare, _Alloc>& __x,
      map<_Key, _Tp, _Compare, _Alloc>& __y)
     { __x.swap(__y); }
 _GLIBCXX_END_NAMESPACE_CONTAINER
 } // namespace std
References __glibcxx_class_requires, __glibcxx_class_requires2, __glibcxx_class_requires4, __glibcxx_function_requires, __N, find(), map, move(), std::__exception_ptr::operator!=(), __gnu_debug::operator<(), __gnu_debug::operator<=(), std::__exception_ptr::operator==(), __gnu_debug::operator>(), __gnu_debug::operator>=(), and swap.