ZEQ2-Lite: SpeexHeader: Makes it easy to write/parse an Ogg/Speex header
SpeexHeader: Makes it easy to write/parse an Ogg/Speex header
This is the Speex header for the Ogg encapsulation. You don't need that if you just use RTP.
Data Structures
struct SpeexHeader
Speex header info for file-based formats.
Macros
#define SPEEX_HEADER_STRING_LENGTH 8
Length of the Speex header identifier.
#define SPEEX_HEADER_VERSION_LENGTH 20
Maximum number of characters for encoding the Speex version number in the header.
Functions
void speex_header_free (void *ptr)
Frees the memory allocated by either speex_header_to_packet() or speex_packet_to_header()
char * speex_header_to_packet (SpeexHeader *header, int *size)
Creates the header packet from the header itself (mostly involves endianness conversion)
void speex_init_header (SpeexHeader *header, int rate, int nb_channels, const struct SpeexMode *m)
Initializes a SpeexHeader using basic information.
SpeexHeader * speex_packet_to_header (char *packet, int size)
Creates a SpeexHeader from a packet.
Detailed Description
This is the Speex header for the Ogg encapsulation. You don't need that if you just use RTP.
Macro Definition Documentation
SPEEX_HEADER_STRING_LENGTH
#define SPEEX_HEADER_STRING_LENGTH 8
#include <Source/Engine/libspeex/include/speex/speex_header.h>
Length of the Speex header identifier.
Definition at line 53 of file speex_header.h.
SPEEX_HEADER_VERSION_LENGTH
#define SPEEX_HEADER_VERSION_LENGTH 20
#include <Source/Engine/libspeex/include/speex/speex_header.h>
Maximum number of characters for encoding the Speex version number in the header.
Definition at line 56 of file speex_header.h.
Function Documentation
speex_header_free()
void speex_header_free (void * ptr)
#include <Source/Engine/libspeex/include/speex/speex_header.h>
Frees the memory allocated by either speex_header_to_packet() or speex_packet_to_header()
Definition at line 185 of file speex_header.c.
 {
    speex_free(ptr);
 }
References ptr(), and speex_free().
speex_header_to_packet()
char* speex_header_to_packet (SpeexHeader * header, int * size)
#include <Source/Engine/libspeex/include/speex/speex_header.h>
Creates the header packet from the header itself (mostly involves endianness conversion)
Definition at line 121 of file speex_header.c.
 {
    SpeexHeader *le_header;
    le_header = (SpeexHeader*)speex_alloc(sizeof(SpeexHeader));
    SPEEX_COPY(le_header, header, 1);
    /*Make sure everything is now little-endian*/
    ENDIAN_SWITCH(le_header->speex_version_id);
    ENDIAN_SWITCH(le_header->header_size);
    ENDIAN_SWITCH(le_header->rate);
    ENDIAN_SWITCH(le_header->mode);
    ENDIAN_SWITCH(le_header->mode_bitstream_version);
    ENDIAN_SWITCH(le_header->nb_channels);
    ENDIAN_SWITCH(le_header->bitrate);
    ENDIAN_SWITCH(le_header->frame_size);
    ENDIAN_SWITCH(le_header->vbr);
    ENDIAN_SWITCH(le_header->frames_per_packet);
    ENDIAN_SWITCH(le_header->extra_headers);
    *size = sizeof(SpeexHeader);
    return (char *)le_header;
 }
References bitrate, ENDIAN_SWITCH, extra_headers, frame_size, frames_per_packet, header_size, mode, mode_bitstream_version, nb_channels, rate, speex_alloc(), SPEEX_COPY, speex_version_id, and vbr.
speex_init_header()
void speex_init_header (SpeexHeader * header, int rate, int nb_channels, const struct SpeexMode * m)
#include <Source/Engine/libspeex/include/speex/speex_header.h>
Initializes a SpeexHeader using basic information.
speex_packet_to_header()
SpeexHeader* speex_packet_to_header (char * packet, int size)
#include <Source/Engine/libspeex/include/speex/speex_header.h>
Creates a SpeexHeader from a packet.
Definition at line 145 of file speex_header.c.
 {
    int i;
    SpeexHeader *le_header;
    const char *h = "Speex   ";
    for (i=0;i<8;i++)
       if (packet[i]!=h[i])
       {
          speex_notify("This doesn't look like a Speex file");
          return NULL;
       }
    /*FIXME: Do we allow larger headers?*/
    if (size < (int)sizeof(SpeexHeader))
    {
       speex_notify("Speex header too small");
       return NULL;
    }
    le_header = (SpeexHeader*)speex_alloc(sizeof(SpeexHeader));
    SPEEX_COPY(le_header, (SpeexHeader*)packet, 1);
    /*Make sure everything is converted correctly from little-endian*/
    ENDIAN_SWITCH(le_header->speex_version_id);
    ENDIAN_SWITCH(le_header->header_size);
    ENDIAN_SWITCH(le_header->rate);
    ENDIAN_SWITCH(le_header->mode);
    ENDIAN_SWITCH(le_header->mode_bitstream_version);
    ENDIAN_SWITCH(le_header->nb_channels);
    ENDIAN_SWITCH(le_header->bitrate);
    ENDIAN_SWITCH(le_header->frame_size);
    ENDIAN_SWITCH(le_header->vbr);
    ENDIAN_SWITCH(le_header->frames_per_packet);
    ENDIAN_SWITCH(le_header->extra_headers);
    return le_header;
 }
References bitrate, ENDIAN_SWITCH, extra_headers, frame_size, frames_per_packet, header_size, mode, mode_bitstream_version, nb_channels, NULL, rate, speex_alloc(), SPEEX_COPY, speex_notify(), speex_version_id, and vbr.