ZEQ2-Lite: Engine/tools/lcc/cpp/hideset.c File Reference
hideset.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cpp.h"
Macros
#define HSSIZ 32
Typedefs
typedef Nlist ** Hideset
Functions
int checkhideset (int hs, Nlist *np)
void iniths (void)
int inserths (Hideset, Hideset, Nlist *)
int newhideset (int hs, Nlist *np)
void prhideset (int hs)
int unionhideset (int hs1, int hs2)
Variables
Hideset * hidesets
int maxhidesets = 3
int nhidesets = 0
Macro Definition Documentation
HSSIZ
#define HSSIZ 32
Definition at line 12 of file hideset.c.
Typedef Documentation
Hideset
typedef Nlist** Hideset
Definition at line 13 of file hideset.c.
Function Documentation
checkhideset()
int checkhideset (int hs, Nlist * np)
Definition at line 23 of file hideset.c.
 {
     Hideset hsp;
     if (hs>=nhidesets)
         abort();
     for (hsp = hidesets[hs]; *hsp; hsp++) {
         if (*hsp == np)
             return 1;
     }
     return 0;
 }
References abort(), hidesets, nhidesets, and np.
Referenced by expandrow().
iniths()
void iniths (void)
Definition at line 95 of file hideset.c.
 {
     hidesets = (Hideset *)domalloc(maxhidesets*sizeof(Hideset *));
     hidesets[0] = (Hideset)domalloc(sizeof(Hideset));
     *hidesets[0] = NULL;
     nhidesets++;
 }
References domalloc(), hidesets, maxhidesets, nhidesets, and NULL.
Referenced by main().
inserths()
int inserths (Hideset dhs, Hideset shs, Nlist * np)
Definition at line 67 of file hideset.c.
 {
     Hideset odhs = dhs;
     while (*shs && *shs < np)
         *dhs++ = *shs++;
     if (*shs != np)
         *dhs++ = np;
     do {
         *dhs++ = *shs;
     } while (*shs++);
     return dhs - odhs;
 }
References np.
Referenced by newhideset().
newhideset()
int newhideset (int hs, Nlist * np)
Definition at line 40 of file hideset.c.
 {
     int i, len;
     Nlist *nhs[HSSIZ+3];
     Hideset hs1, hs2;
     len = inserths(nhs, hidesets[hs], np);
     for (i=0; i<nhidesets; i++) {
         for (hs1=nhs, hs2=hidesets[i]; *hs1==*hs2; hs1++, hs2++)
             if (*hs1 == NULL)
                 return i;
     }
     if (len>=HSSIZ)
         return hs;
     if (nhidesets >= maxhidesets) {
         maxhidesets = 3*maxhidesets/2+1;
         hidesets = (Hideset *)realloc(hidesets, (sizeof (Hideset *))*maxhidesets);
         if (hidesets == NULL)
             error(FATAL, "Out of memory from realloc");
     }
     hs1 = (Hideset)domalloc(len*sizeof(Hideset));
     memmove(hs1, nhs, len*sizeof(Hideset));
     hidesets[nhidesets] = hs1;
     return nhidesets++;
 }
References domalloc(), error(), FATAL, hidesets, HSSIZ, value::i, inserths(), maxhidesets, memmove(), nhidesets, np, NULL, and realloc().
Referenced by expand(), and unionhideset().
prhideset()
void prhideset (int hs)
Definition at line 104 of file hideset.c.
 {
     Hideset np;
     for (np = hidesets[hs]; *np; np++) {
         fprintf(stderr, (char*)(*np)->name, (*np)->len);
         fprintf(stderr, " ");
     }
 }
References fprintf(), hidesets, np, and stderr.
Referenced by peektokens().
unionhideset()
int unionhideset (int hs1, int hs2)
Definition at line 85 of file hideset.c.
 {
     Hideset hp;
     for (hp = hidesets[hs2]; *hp; hp++)
         hs1 = newhideset(hs1, *hp);
     return hs1;
 }
References hidesets, and newhideset().
Referenced by expand().
Variable Documentation
hidesets
Hideset* hidesets
Definition at line 14 of file hideset.c.
Referenced by checkhideset(), iniths(), newhideset(), prhideset(), and unionhideset().
maxhidesets
int maxhidesets = 3
Definition at line 16 of file hideset.c.
Referenced by iniths(), and newhideset().
nhidesets
int nhidesets = 0
Definition at line 15 of file hideset.c.
Referenced by checkhideset(), iniths(), and newhideset().