ZEQ2-Lite: __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator > Struct Template Reference
__gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator > Struct Template Reference abstract
#include <basic_tree_policy_base.hpp>
Protected Types
typedef Allocator::template rebind< typename remove_const< key_type >::type >::other::const_reference const_key_reference
typedef Allocator::template rebind< typename remove_const< value_type >::type >::other::const_pointer const_pointer
typedef Allocator::template rebind< typename remove_const< value_type >::type >::other::const_reference const_reference
typedef Node_Iterator::value_type it_type
typedef value_type::first_type key_type
typedef Allocator::template rebind< typename remove_const< value_type >::type >::other::reference reference
typedef std::iterator_traits< it_type >::value_type value_type
Protected Member Functions
virtual ~basic_tree_policy_base ()
virtual it_type end ()=0
it_type end_iterator () const
Static Protected Member Functions
static const_key_reference extract_key (const_reference r_val)
Detailed Description
template<typename Const_Node_Iterator, typename Node_Iterator, typename Allocator>
struct __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >
Definition at line 58 of file basic_tree_policy_base.hpp.
Member Typedef Documentation
const_key_reference
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > typedef Allocator::template rebind< typename remove_const< key_type>::type>::other::const_reference __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::const_key_reference protected
Definition at line 71 of file basic_tree_policy_base.hpp.
const_pointer
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > typedef Allocator::template rebind< typename remove_const< value_type>::type>::other::const_pointer __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::const_pointer protected
Definition at line 89 of file basic_tree_policy_base.hpp.
const_reference
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > typedef Allocator::template rebind< typename remove_const< value_type>::type>::other::const_reference __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::const_reference protected
Definition at line 77 of file basic_tree_policy_base.hpp.
it_type
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > typedef Node_Iterator::value_type __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::it_type protected
Definition at line 61 of file basic_tree_policy_base.hpp.
key_type
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > typedef value_type::first_type __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::key_type protected
Definition at line 65 of file basic_tree_policy_base.hpp.
reference
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > typedef Allocator::template rebind< typename remove_const< value_type>::type>::other::reference __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::reference protected
Definition at line 83 of file basic_tree_policy_base.hpp.
value_type
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > typedef std::iterator_traits< it_type>::value_type __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::value_type protected
Definition at line 63 of file basic_tree_policy_base.hpp.
Constructor & Destructor Documentation
~basic_tree_policy_base()
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > virtual __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::~basic_tree_policy_base () inline protected virtual
Definition at line 107 of file basic_tree_policy_base.hpp.
       { }
Member Function Documentation
end()
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > virtual it_type __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::end () protected pure virtual
Referenced by __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::end_iterator(), and __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Const_Node_Iterator, Allocator >::end_iterator().
end_iterator()
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > it_type __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::end_iterator () const inline protected
Definition at line 101 of file basic_tree_policy_base.hpp.
       {
     return (const_cast<PB_DS_CLASS_C_DEC* >(this)->end());
       }
References __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::end(), and PB_DS_CLASS_C_DEC.
extract_key()
template<typename Const_Node_Iterator , typename Node_Iterator , typename Allocator > static const_key_reference __gnu_pbds::detail::basic_tree_policy_base< Const_Node_Iterator, Node_Iterator, Allocator >::extract_key (const_reference r_val) inline static protected
Definition at line 92 of file basic_tree_policy_base.hpp.
       {
     return (r_val.first);
       }
The documentation for this struct was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/basic_tree_policy/basic_tree_policy_base.hpp