ZEQ2-Lite: pcrecpp Namespace Reference
pcrecpp Namespace Reference
Data Structures
class _RE_MatchObject
class Arg
class RE
class RE_Options
class Scanner
class StringPiece
Functions
static RE_Options CASELESS ()
static RE_Options DOTALL ()
static RE_Options EXTENDED ()
ushort MAKE_INTEGER_PARSER (int, int) MAKE_INTEGER_PARSER(unsigned int
ushort uint ulong MAKE_INTEGER_PARSER (long long, longlong) MAKE_INTEGER_PARSER(unsigned long long
ushort uint MAKE_INTEGER_PARSER (long, long) MAKE_INTEGER_PARSER(unsigned long
MAKE_INTEGER_PARSER (short, short) MAKE_INTEGER_PARSER(unsigned short
static RE_Options MULTILINE ()
static RE_Options UTF8 ()
Function Documentation
CASELESS()
static RE_Options pcrecpp::CASELESS () inline static
Definition at line 469 of file pcrecpp.h.
{
   return RE_Options().set_caseless(true);
 }
References pcrecpp::RE_Options::set_caseless().
DOTALL()
static RE_Options pcrecpp::DOTALL () inline static
Definition at line 476 of file pcrecpp.h.
{
   return RE_Options().set_dotall(true);
 }
References pcrecpp::RE_Options::set_dotall().
EXTENDED()
static RE_Options pcrecpp::EXTENDED () inline static
Definition at line 480 of file pcrecpp.h.
{
   return RE_Options().set_extended(true);
 }
References pcrecpp::RE_Options::set_extended().
MAKE_INTEGER_PARSER() [1/4]
ushort pcrecpp::MAKE_INTEGER_PARSER (int , int)
MAKE_INTEGER_PARSER() [2/4]
ushort uint ulong pcrecpp::MAKE_INTEGER_PARSER (long long , longlong)
MAKE_INTEGER_PARSER() [3/4]
ushort uint pcrecpp::MAKE_INTEGER_PARSER (long , long)
MAKE_INTEGER_PARSER() [4/4]
pcrecpp::MAKE_INTEGER_PARSER (short , short)
MULTILINE()
static RE_Options pcrecpp::MULTILINE () inline static
Definition at line 472 of file pcrecpp.h.
{
   return RE_Options().set_multiline(true);
 }
References pcrecpp::RE_Options::set_multiline().
UTF8()
static RE_Options pcrecpp::UTF8 () inline static
Definition at line 465 of file pcrecpp.h.
{
   return RE_Options().set_utf8(true);
 }
References pcrecpp::RE_Options::set_utf8().