ZEQ2-Lite: Tools/MinGW/include/ws2spi.h File Reference
ws2spi.h File Reference
#include <winsock2.h>
Data Structures
struct _NSP_ROUTINE
struct _WSATHREADID
struct _WSPPROC_TABLE
struct _WSPUPCALLTABLE
struct WSPData
Macros
#define WSPAPI WSAAPI
#define WSPDESCRIPTION_LEN 255
Typedefs
typedef struct NSP_ROUTINE * LPNSP_ROUTINE
typedef INT(WSPAPI * LPNSPCLEANUP) (LPGUID)
typedef INT(WSPAPI * LPNSPGETSERVICECLASSINFO) (LPGUID, LPDWORD, LPWSASERVICECLASSINFOW)
typedef INT(WSPAPI * LPNSPINSTALLSERVICECLASS) (LPGUID, LPWSASERVICECLASSINFOW)
typedef INT(WSPAPI * LPNSPLOOKUPSERVICEBEGIN) (LPGUID, LPWSAQUERYSETW, LPWSASERVICECLASSINFOW, DWORD, LPHANDLE)
typedef INT(WSPAPI * LPNSPLOOKUPSERVICEEND) (HANDLE)
typedef INT(WSPAPI * LPNSPLOOKUPSERVICENEXT) (HANDLE, DWORD, LPDWORD, LPWSAQUERYSET)
typedef INT(WSPAPI * LPNSPREMOVESERVICECLASS) (LPGUID, LPGUID)
typedef INT(WSPAPI * LPNSPSETSERVICE) (LPGUID, LPWSASERVICECLASSINFOW, LPWSAQUERYSETW, WSAESETSERVICEOP, DWORD)
typedef BOOL(WSPAPI * LPWPUCLOSEEVENT) (WSAEVENT, LPINT)
typedef INT(WSPAPI * LPWPUCLOSESOCKETHANDLE) (SOCKET, LPINT)
typedef INT(WSPAPI * LPWPUCLOSETHREAD) (LPWSATHREADID, LPINT)
typedef INT(WSPAPI * LPWPUCOMPLETEOVERLAPPEDREQUEST) (SOCKET, LPWSAOVERLAPPED, DWORD, DWORD, LPINT)
typedef WSAEVENT(WSPAPI * LPWPUCREATEEVENT) (LPINT)
typedef SOCKET(WSPAPI * LPWPUCREATESOCKETHANDLE) (DWORD, DWORD, LPINT)
typedef SOCKET(WSPAPI * LPWPUFDISSET) (SOCKET, LPFD_SET)
typedef INT(WSPAPI * LPWPUGETPROVIDERPATH) (LPGUID, LPWSTR, LPINT, LPINT)
typedef SOCKET(WSPAPI * LPWPUMODIFYIFSHANDLE) (DWORD, SOCKET, LPINT)
typedef INT(WSPAPI * LPWPUOPENCURRENTTHREAD) (LPWSATHREADID, LPINT)
typedef BOOL(WSPAPI * LPWPUPOSTMESSAGE) (HWND, UINT, WPARAM, LPARAM)
typedef INT(WSPAPI * LPWPUQUERYBLOCKINGCALLBACK) (DWORD, LPBLOCKINGCALLBACK FAR *, LPDWORD, LPINT)
typedef INT(WSPAPI * LPWPUQUERYSOCKETHANDLECONTEXT) (SOCKET, LPDWORD, LPINT)
typedef INT(WSPAPI * LPWPUQUEUEAPC) (LPWSATHREADID, LPWSAUSERAPC, DWORD, LPINT)
typedef BOOL(WSPAPI * LPWPURESETEVENT) (WSAEVENT, LPINT)
typedef BOOL(WSPAPI * LPWPUSETEVENT) (WSAEVENT, LPINT)
typedef struct WSATHREADID * LPWSATHREADID
typedef SOCKET(WSPAPI * LPWSPACCEPT) (SOCKET, LPSOCKADDR, LPINT, LPCONDITIONPROC, DWORD, LPINT)
typedef INT(WSPAPI * LPWSPADDRESSTOSTRING) (LPSOCKADDR, DWORD, LPWSAPROTOCOL_INFOW, LPWSTR, LPDWORD, LPINT)
typedef INT(WSPAPI * LPWSPASYNCSELECT) (SOCKET, HWND, UINT, LONG, LPINT)
typedef INT(WSPAPI * LPWSPBIND) (SOCKET, const struct sockaddr *, INT, LPINT)
typedef INT(WSPAPI * LPWSPCANCELBLOCKINGCALL) (LPINT)
typedef INT(WSPAPI * LPWSPCLEANUP) (LPINT)
typedef INT(WSPAPI * LPWSPCLOSESOCKET) (SOCKET, LPINT)
typedef INT(WSPAPI * LPWSPCONNECT) (SOCKET, const struct sockaddr *, INT, LPWSABUF, LPWSABUF, LPQOS, LPQOS, LPINT)
typedef struct WSPDATA * LPWSPDATA
typedef INT(WSPAPI * LPWSPDUPLICATESOCKET) (SOCKET, DWORD, LPWSAPROTOCOL_INFOW, LPINT)
typedef INT(WSPAPI * LPWSPENUMNETWORKEVENTS) (SOCKET, WSAEVENT, LPWSANETWORKEVENTS, LPINT)
typedef INT(WSPAPI * LPWSPEVENTSELECT) (SOCKET, WSAEVENT, LONG, LPINT)
typedef BOOL(WSPAPI * LPWSPGETOVERLAPPEDRESULT) (SOCKET, LPWSAOVERLAPPED, LPDWORD, BOOL, LPDWORD, LPINT)
typedef INT(WSPAPI * LPWSPGETPEERNAME) (SOCKET, LPSOCKADDR, LPINT, LPINT)
typedef BOOL(WSPAPI * LPWSPGETQOSBYNAME) (SOCKET, LPWSABUF, LPQOS, LPINT)
typedef INT(WSPAPI * LPWSPGETSOCKNAME) (SOCKET, LPSOCKADDR, LPINT, LPINT)
typedef INT(WSPAPI * LPWSPGETSOCKOPT) (SOCKET, INT, INT, CHAR FAR *, LPINT, LPINT)
typedef INT(WSPAPI * LPWSPIOCTL) (SOCKET, DWORD, LPVOID, DWORD, LPVOID, DWORD, LPDWORD, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
typedef SOCKET(WSPAPI * LPWSPJOINLEAF) (SOCKET, const struct sockaddr *, INT, LPWSABUF, LPWSABUF, LPQOS, LPQOS, DWORD, LPINT)
typedef INT(WSPAPI * LPWSPLISTEN) (SOCKET, INT, LPINT)
typedef struct WSPPROC_TABLE * LPWSPPROC_TABLE
typedef INT(WSPAPI * LPWSPRECV) (SOCKET, LPWSABUF, DWORD, LPDWORD, LPDWORD, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
typedef INT(WSPAPI * LPWSPRECVDISCONNECT) (SOCKET, LPWSABUF, LPINT)
typedef INT(WSPAPI * LPWSPRECVFROM) (SOCKET, LPWSABUF, DWORD, LPDWORD, LPDWORD, LPSOCKADDR, LPINT, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
typedef INT(WSPAPI * LPWSPSELECT) (INT, LPFD_SET, LPFD_SET, LPFD_SET, CONST TIMEVAL *, LPINT)
typedef INT(WSPAPI * LPWSPSEND) (SOCKET, LPWSABUF, DWORD, LPDWORD, DWORD, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
typedef INT(WSPAPI * LPWSPSENDDISCONNECT) (SOCKET, LPWSABUF, LPINT)
typedef INT(WSPAPI * LPWSPSENDTO) (SOCKET, LPWSABUF, DWORD, LPDWORD, DWORD, const struct sockaddr *, INT, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
typedef INT(WSPAPI * LPWSPSETSOCKOPT) (SOCKET, INT, INT, CONST CHAR FAR *, INT, LPINT)
typedef INT(WSPAPI * LPWSPSHUTDOWN) (SOCKET, INT, LPINT)
typedef SOCKET(WSPAPI * LPWSPSOCKET) (INT, INT, INT, LPWSAPROTOCOL_INFOW, GROUP, DWORD, LPINT)
typedef INT(WSPAPI * LPWSPSTARTUP) (WORD, LPWSPDATA, LPWSAPROTOCOL_INFOW, WSPUPCALLTABLE, LPWSPPROC_TABLE)
typedef INT(WSPAPI * LPWSPSTRINGTOADDRESS) (LPWSTR, INT, LPWSAPROTOCOL_INFOW, LPSOCKADDR, LPINT, LPINT)
typedef struct WSPUPCALLTABLE * LPWSPUPCALLTABLE
typedef struct NSP_ROUTINE * PNSP_ROUTINE
Functions
typedef BOOL (CALLBACK FAR *LPBLOCKINGCALLBACK)(DWORD)
INT WSPAPI NSPStartup (LPGUID, LPNSP_ROUTINE)
typedef VOID (CALLBACK FAR *LPWSAUSERAPC)(DWORD)
INT WSPAPI WPUCompleteOverlappedRequest (SOCKET, LPWSAOVERLAPPED, DWORD, DWORD, LPINT)
INT WSPAPI WSCDeinstallProvider (LPGUID, LPINT)
INT WSPAPI WSCEnableNSProvider (LPGUID, BOOL)
INT WSPAPI WSCEnumProtocols (LPINT, LPWSAPROTOCOL_INFOW, LPDWORD, LPINT)
INT WSPAPI WSCGetProviderPath (LPGUID, LPWSTR, LPINT, LPINT)
INT WSPAPI WSCInstallNameSpace (LPWSTR, LPWSTR, DWORD, DWORD, LPGUID)
INT WSPAPI WSCInstallProvider (CONST LPGUID, CONST LPWSTR, CONST LPWSAPROTOCOL_INFOW, DWORD, LPINT)
INT WSPAPI WSCUnInstallNameSpace (LPGUID)
INT WSPAPI WSCWriteProviderOrder (LPDWORD, DWORD)
INT WSPAPI WSPStartup (WORD, LPWSPDATA, LPWSAPROTOCOL_INFOW, WSPUPCALLTABLE, LPWSPPROC_TABLE)
Macro Definition Documentation
WSPAPI
#define WSPAPI WSAAPI
Definition at line 30 of file ws2spi.h.
WSPDESCRIPTION_LEN
#define WSPDESCRIPTION_LEN 255
Definition at line 31 of file ws2spi.h.
Typedef Documentation
LPNSP_ROUTINE
typedef struct NSP_ROUTINE * LPNSP_ROUTINE
LPNSPCLEANUP
typedef INT(WSPAPI * LPNSPCLEANUP) (LPGUID)
Definition at line 160 of file ws2spi.h.
LPNSPGETSERVICECLASSINFO
typedef INT(WSPAPI * LPNSPGETSERVICECLASSINFO) (LPGUID, LPDWORD, LPWSASERVICECLASSINFOW)
Definition at line 161 of file ws2spi.h.
LPNSPINSTALLSERVICECLASS
typedef INT(WSPAPI * LPNSPINSTALLSERVICECLASS) (LPGUID, LPWSASERVICECLASSINFOW)
Definition at line 162 of file ws2spi.h.
LPNSPLOOKUPSERVICEBEGIN
typedef INT(WSPAPI * LPNSPLOOKUPSERVICEBEGIN) (LPGUID, LPWSAQUERYSETW, LPWSASERVICECLASSINFOW, DWORD, LPHANDLE)
Definition at line 163 of file ws2spi.h.
LPNSPLOOKUPSERVICEEND
typedef INT(WSPAPI * LPNSPLOOKUPSERVICEEND) (HANDLE)
Definition at line 164 of file ws2spi.h.
LPNSPLOOKUPSERVICENEXT
typedef INT(WSPAPI * LPNSPLOOKUPSERVICENEXT) (HANDLE, DWORD, LPDWORD, LPWSAQUERYSET)
Definition at line 165 of file ws2spi.h.
LPNSPREMOVESERVICECLASS
typedef INT(WSPAPI * LPNSPREMOVESERVICECLASS) (LPGUID, LPGUID)
Definition at line 166 of file ws2spi.h.
LPNSPSETSERVICE
typedef INT(WSPAPI * LPNSPSETSERVICE) (LPGUID, LPWSASERVICECLASSINFOW, LPWSAQUERYSETW, WSAESETSERVICEOP, DWORD)
Definition at line 167 of file ws2spi.h.
LPWPUCLOSEEVENT
typedef BOOL(WSPAPI * LPWPUCLOSEEVENT) (WSAEVENT, LPINT)
Definition at line 120 of file ws2spi.h.
LPWPUCLOSESOCKETHANDLE
typedef INT(WSPAPI * LPWPUCLOSESOCKETHANDLE) (SOCKET, LPINT)
Definition at line 121 of file ws2spi.h.
LPWPUCLOSETHREAD
typedef INT(WSPAPI * LPWPUCLOSETHREAD) (LPWSATHREADID, LPINT)
Definition at line 122 of file ws2spi.h.
LPWPUCOMPLETEOVERLAPPEDREQUEST
typedef INT(WSPAPI * LPWPUCOMPLETEOVERLAPPEDREQUEST) (SOCKET, LPWSAOVERLAPPED, DWORD, DWORD, LPINT)
Definition at line 136 of file ws2spi.h.
LPWPUCREATEEVENT
typedef WSAEVENT(WSPAPI * LPWPUCREATEEVENT) (LPINT)
Definition at line 123 of file ws2spi.h.
LPWPUCREATESOCKETHANDLE
typedef SOCKET(WSPAPI * LPWPUCREATESOCKETHANDLE) (DWORD, DWORD, LPINT)
Definition at line 124 of file ws2spi.h.
LPWPUFDISSET
typedef SOCKET(WSPAPI * LPWPUFDISSET) (SOCKET, LPFD_SET)
Definition at line 125 of file ws2spi.h.
LPWPUGETPROVIDERPATH
typedef INT(WSPAPI * LPWPUGETPROVIDERPATH) (LPGUID, LPWSTR, LPINT, LPINT)
Definition at line 126 of file ws2spi.h.
LPWPUMODIFYIFSHANDLE
typedef SOCKET(WSPAPI * LPWPUMODIFYIFSHANDLE) (DWORD, SOCKET, LPINT)
Definition at line 127 of file ws2spi.h.
LPWPUOPENCURRENTTHREAD
typedef INT(WSPAPI * LPWPUOPENCURRENTTHREAD) (LPWSATHREADID, LPINT)
Definition at line 128 of file ws2spi.h.
LPWPUPOSTMESSAGE
typedef BOOL(WSPAPI * LPWPUPOSTMESSAGE) (HWND, UINT, WPARAM, LPARAM)
Definition at line 129 of file ws2spi.h.
LPWPUQUERYBLOCKINGCALLBACK
typedef INT(WSPAPI * LPWPUQUERYBLOCKINGCALLBACK) (DWORD, LPBLOCKINGCALLBACK FAR *, LPDWORD, LPINT)
Definition at line 130 of file ws2spi.h.
LPWPUQUERYSOCKETHANDLECONTEXT
typedef INT(WSPAPI * LPWPUQUERYSOCKETHANDLECONTEXT) (SOCKET, LPDWORD, LPINT)
Definition at line 131 of file ws2spi.h.
LPWPUQUEUEAPC
typedef INT(WSPAPI * LPWPUQUEUEAPC) (LPWSATHREADID, LPWSAUSERAPC, DWORD, LPINT)
Definition at line 132 of file ws2spi.h.
LPWPURESETEVENT
typedef BOOL(WSPAPI * LPWPURESETEVENT) (WSAEVENT, LPINT)
Definition at line 133 of file ws2spi.h.
LPWPUSETEVENT
typedef BOOL(WSPAPI * LPWPUSETEVENT) (WSAEVENT, LPINT)
Definition at line 134 of file ws2spi.h.
LPWSATHREADID
typedef struct WSATHREADID* LPWSATHREADID
LPWSPACCEPT
typedef SOCKET(WSPAPI * LPWSPACCEPT) (SOCKET, LPSOCKADDR, LPINT, LPCONDITIONPROC, DWORD, LPINT)
Definition at line 49 of file ws2spi.h.
LPWSPADDRESSTOSTRING
typedef INT(WSPAPI * LPWSPADDRESSTOSTRING) (LPSOCKADDR, DWORD, LPWSAPROTOCOL_INFOW, LPWSTR, LPDWORD, LPINT)
Definition at line 50 of file ws2spi.h.
LPWSPASYNCSELECT
typedef INT(WSPAPI * LPWSPASYNCSELECT) (SOCKET, HWND, UINT, LONG, LPINT)
Definition at line 51 of file ws2spi.h.
LPWSPBIND
typedef INT(WSPAPI * LPWSPBIND) (SOCKET, const struct sockaddr *, INT, LPINT)
Definition at line 52 of file ws2spi.h.
LPWSPCANCELBLOCKINGCALL
typedef INT(WSPAPI * LPWSPCANCELBLOCKINGCALL) (LPINT)
Definition at line 53 of file ws2spi.h.
LPWSPCLEANUP
typedef INT(WSPAPI * LPWSPCLEANUP) (LPINT)
Definition at line 54 of file ws2spi.h.
LPWSPCLOSESOCKET
typedef INT(WSPAPI * LPWSPCLOSESOCKET) (SOCKET, LPINT)
Definition at line 55 of file ws2spi.h.
LPWSPCONNECT
typedef INT(WSPAPI * LPWSPCONNECT) (SOCKET, const struct sockaddr *, INT, LPWSABUF, LPWSABUF, LPQOS, LPQOS, LPINT)
Definition at line 56 of file ws2spi.h.
LPWSPDATA
typedef struct WSPDATA* LPWSPDATA
LPWSPDUPLICATESOCKET
typedef INT(WSPAPI * LPWSPDUPLICATESOCKET) (SOCKET, DWORD, LPWSAPROTOCOL_INFOW, LPINT)
Definition at line 57 of file ws2spi.h.
LPWSPENUMNETWORKEVENTS
typedef INT(WSPAPI * LPWSPENUMNETWORKEVENTS) (SOCKET, WSAEVENT, LPWSANETWORKEVENTS, LPINT)
Definition at line 58 of file ws2spi.h.
LPWSPEVENTSELECT
typedef INT(WSPAPI * LPWSPEVENTSELECT) (SOCKET, WSAEVENT, LONG, LPINT)
Definition at line 59 of file ws2spi.h.
LPWSPGETOVERLAPPEDRESULT
typedef BOOL(WSPAPI * LPWSPGETOVERLAPPEDRESULT) (SOCKET, LPWSAOVERLAPPED, LPDWORD, BOOL, LPDWORD, LPINT)
Definition at line 60 of file ws2spi.h.
LPWSPGETPEERNAME
typedef INT(WSPAPI * LPWSPGETPEERNAME) (SOCKET, LPSOCKADDR, LPINT, LPINT)
Definition at line 61 of file ws2spi.h.
LPWSPGETQOSBYNAME
typedef BOOL(WSPAPI * LPWSPGETQOSBYNAME) (SOCKET, LPWSABUF, LPQOS, LPINT)
Definition at line 62 of file ws2spi.h.
LPWSPGETSOCKNAME
typedef INT(WSPAPI * LPWSPGETSOCKNAME) (SOCKET, LPSOCKADDR, LPINT, LPINT)
Definition at line 63 of file ws2spi.h.
LPWSPGETSOCKOPT
typedef INT(WSPAPI * LPWSPGETSOCKOPT) (SOCKET, INT, INT, CHAR FAR *, LPINT, LPINT)
Definition at line 64 of file ws2spi.h.
LPWSPIOCTL
typedef INT(WSPAPI * LPWSPIOCTL) (SOCKET, DWORD, LPVOID, DWORD, LPVOID, DWORD, LPDWORD, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
Definition at line 65 of file ws2spi.h.
LPWSPJOINLEAF
typedef SOCKET(WSPAPI * LPWSPJOINLEAF) (SOCKET, const struct sockaddr *, INT, LPWSABUF, LPWSABUF, LPQOS, LPQOS, DWORD, LPINT)
Definition at line 67 of file ws2spi.h.
LPWSPLISTEN
typedef INT(WSPAPI * LPWSPLISTEN) (SOCKET, INT, LPINT)
Definition at line 68 of file ws2spi.h.
LPWSPPROC_TABLE
typedef struct WSPPROC_TABLE* LPWSPPROC_TABLE
LPWSPRECV
typedef INT(WSPAPI * LPWSPRECV) (SOCKET, LPWSABUF, DWORD, LPDWORD, LPDWORD, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
Definition at line 69 of file ws2spi.h.
LPWSPRECVDISCONNECT
typedef INT(WSPAPI * LPWSPRECVDISCONNECT) (SOCKET, LPWSABUF, LPINT)
Definition at line 71 of file ws2spi.h.
LPWSPRECVFROM
typedef INT(WSPAPI * LPWSPRECVFROM) (SOCKET, LPWSABUF, DWORD, LPDWORD, LPDWORD, LPSOCKADDR, LPINT, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
Definition at line 72 of file ws2spi.h.
LPWSPSELECT
typedef INT(WSPAPI * LPWSPSELECT) (INT, LPFD_SET, LPFD_SET, LPFD_SET, CONST TIMEVAL *, LPINT)
Definition at line 74 of file ws2spi.h.
LPWSPSEND
typedef INT(WSPAPI * LPWSPSEND) (SOCKET, LPWSABUF, DWORD, LPDWORD, DWORD, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
Definition at line 75 of file ws2spi.h.
LPWSPSENDDISCONNECT
typedef INT(WSPAPI * LPWSPSENDDISCONNECT) (SOCKET, LPWSABUF, LPINT)
Definition at line 77 of file ws2spi.h.
LPWSPSENDTO
typedef INT(WSPAPI * LPWSPSENDTO) (SOCKET, LPWSABUF, DWORD, LPDWORD, DWORD, const struct sockaddr *, INT, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE, LPWSATHREADID, LPINT)
Definition at line 78 of file ws2spi.h.
LPWSPSETSOCKOPT
typedef INT(WSPAPI * LPWSPSETSOCKOPT) (SOCKET, INT, INT, CONST CHAR FAR *, INT, LPINT)
Definition at line 80 of file ws2spi.h.
LPWSPSHUTDOWN
typedef INT(WSPAPI * LPWSPSHUTDOWN) (SOCKET, INT, LPINT)
Definition at line 81 of file ws2spi.h.
LPWSPSOCKET
typedef SOCKET(WSPAPI * LPWSPSOCKET) (INT, INT, INT, LPWSAPROTOCOL_INFOW, GROUP, DWORD, LPINT)
Definition at line 82 of file ws2spi.h.
LPWSPSTARTUP
typedef INT(WSPAPI * LPWSPSTARTUP) (WORD, LPWSPDATA, LPWSAPROTOCOL_INFOW, WSPUPCALLTABLE, LPWSPPROC_TABLE)
Definition at line 157 of file ws2spi.h.
LPWSPSTRINGTOADDRESS
typedef INT(WSPAPI * LPWSPSTRINGTOADDRESS) (LPWSTR, INT, LPWSAPROTOCOL_INFOW, LPSOCKADDR, LPINT, LPINT)
Definition at line 83 of file ws2spi.h.
LPWSPUPCALLTABLE
typedef struct WSPUPCALLTABLE* LPWSPUPCALLTABLE
PNSP_ROUTINE
typedef struct NSP_ROUTINE * PNSP_ROUTINE
Function Documentation
BOOL()
typedef BOOL (CALLBACK FAR * LPBLOCKINGCALLBACK)
NSPStartup()
INT WSPAPI NSPStartup (LPGUID , LPNSP_ROUTINE)
VOID()
typedef VOID (CALLBACK FAR * LPWSAUSERAPC)
Referenced by gettok(), hasproto(), outtype(), prtype(), specifier(), ttob(), type_init(), and typestring().
WPUCompleteOverlappedRequest()
INT WSPAPI WPUCompleteOverlappedRequest (SOCKET , LPWSAOVERLAPPED , DWORD , DWORD , LPINT)
WSCDeinstallProvider()
INT WSPAPI WSCDeinstallProvider (LPGUID , LPINT)
WSCEnableNSProvider()
INT WSPAPI WSCEnableNSProvider (LPGUID , BOOL)
WSCEnumProtocols()
INT WSPAPI WSCEnumProtocols (LPINT , LPWSAPROTOCOL_INFOW , LPDWORD , LPINT)
WSCGetProviderPath()
INT WSPAPI WSCGetProviderPath (LPGUID , LPWSTR , LPINT , LPINT)
WSCInstallNameSpace()
INT WSPAPI WSCInstallNameSpace (LPWSTR , LPWSTR , DWORD , DWORD , LPGUID)
WSCInstallProvider()
INT WSPAPI WSCInstallProvider (CONST LPGUID, CONST LPWSTR, CONST LPWSAPROTOCOL_INFOW, DWORD , LPINT)
WSCUnInstallNameSpace()
INT WSPAPI WSCUnInstallNameSpace (LPGUID)
WSCWriteProviderOrder()
INT WSPAPI WSCWriteProviderOrder (LPDWORD , DWORD)
WSPStartup()
INT WSPAPI WSPStartup (WORD , LPWSPDATA , LPWSAPROTOCOL_INFOW , WSPUPCALLTABLE , LPWSPPROC_TABLE)