ZEQ2-Lite: Source/Engine/sys/sys_local.h File Reference
sys_local.h File Reference
#include "../../Shared/q_shared.h"
#include "../../Shared/qcommon.h"
Macros
#define MINSDL_MAJOR 1
#define MINSDL_MINOR 2
#define MINSDL_PATCH 10
Functions
void CON_Init (void)
char * CON_Input (void)
unsigned int CON_LogRead (char *out, unsigned int outSize)
unsigned int CON_LogSize (void)
unsigned int CON_LogWrite (const char *in)
void CON_Print (const char *message)
void CON_Shutdown (void)
void IN_Frame (void)
void IN_Init (void)
void IN_Restart (void)
void IN_Shutdown (void)
void Sys_AnsiColorPrint (const char *msg)
void Sys_ErrorDialog (const char *error)
void Sys_GLimpInit (void)
void Sys_GLimpSafeInit (void)
int Sys_PID (void)
qboolean Sys_PIDIsRunning (int pid)
void Sys_PlatformExit (void)
void Sys_PlatformInit (void)
void Sys_SigHandler (int signal) __attribute__((noreturn))
Macro Definition Documentation
MINSDL_MAJOR
#define MINSDL_MAJOR 1
Definition at line 27 of file sys_local.h.
MINSDL_MINOR
#define MINSDL_MINOR 2
Definition at line 28 of file sys_local.h.
MINSDL_PATCH
#define MINSDL_PATCH 10
Definition at line 29 of file sys_local.h.
Function Documentation
CON_Init()
void CON_Init (void)
Definition at line 43 of file con_passive.c.
 {
 }
References CLIENT_WINDOW_TITLE, Com_Printf(), CON_CtrlHandler(), CON_Show(), CON_SigCont(), FALSE, Field_Clear(), info, qconsole_attrib, qconsole_hin, QCONSOLE_HISTORY, qconsole_history, qconsole_hout, qconsole_orig_cursorinfo, qconsole_orig_mode, qfalse, qtrue, stdin_active, stdinIsATTY, TRUE, TTY_con, TTY_eof, TTY_erase, TTY_tc, ttycon_hide, and ttycon_on.
Referenced by CON_SigCont(), and main().
CON_Input()
char* CON_Input (void)
Definition at line 52 of file con_passive.c.
 {
     return NULL;
 }
References field_t::buffer, CA_ACTIVE, clc, Com_DPrintf(), Com_Printf(), Com_sprintf(), CON_Back(), CON_FlushIn(), CON_Hide(), CON_HistAdd(), CON_HistNext(), CON_HistPrev(), CON_Show(), field_t::cursor, events, Field_AutoComplete(), Field_Clear(), Hist_Add(), Hist_Next(), Hist_Prev(), MAX_EDIT_LINE, memmove(), NULL, Q_strncpyz(), qconsole_hin, qconsole_line, qconsole_linelen, qfalse, clientConnection_t::state, stdin_active, TTY_con, TTY_CONSOLE_PROMPT, TTY_erase, ttycon_on, and UNUSED_VAR.
Referenced by Sys_ConsoleInput().
CON_LogRead()
unsigned int CON_LogRead (char * out, unsigned int outSize)
Definition at line 104 of file con_log.c.
 {
     unsigned int firstChunk;
     unsigned int secondChunk;
     if( CON_LogSize( ) < outSize )
         outSize = CON_LogSize( );
     if( readPos + outSize > MAX_LOG )
     {
         firstChunk  = MAX_LOG - readPos;
         secondChunk = outSize - firstChunk;
     }
     else
     {
         firstChunk  = outSize;
         secondChunk = 0;
     }
     Com_Memcpy( out, consoleLog + readPos, firstChunk );
     Com_Memcpy( out + firstChunk, out, secondChunk );
     readPos = ( readPos + outSize ) % MAX_LOG;
     return outSize;
 }
References Com_Memcpy, CON_LogSize(), consoleLog, MAX_LOG, out, and readPos.
Referenced by Sys_ErrorDialog().
CON_LogSize()
unsigned int CON_LogSize (void)
Definition at line 38 of file con_log.c.
 {
     if( readPos <= writePos )
         return writePos - readPos;
     else
         return writePos + MAX_LOG - readPos;
 }
References MAX_LOG, readPos, and writePos.
Referenced by CON_LogFree(), CON_LogRead(), CON_LogWrite(), and Sys_ErrorDialog().
CON_LogWrite()
unsigned int CON_LogWrite (const char * in)
Definition at line 61 of file con_log.c.
 {
     unsigned int length = strlen( in );
     unsigned int firstChunk;
     unsigned int secondChunk;
     while( CON_LogFree( ) < length && CON_LogSize( ) > 0 )
     {
         // Free enough space
         while( consoleLog[ readPos ] != '\n' && CON_LogSize( ) > 1 )
             readPos = ( readPos + 1 ) % MAX_LOG;
         // Skip past the '\n'
         readPos = ( readPos + 1 ) % MAX_LOG;
     }
     if( CON_LogFree( ) < length )
         return 0;
     if( writePos + length > MAX_LOG )
     {
         firstChunk  = MAX_LOG - writePos;
         secondChunk = length - firstChunk;
     }
     else
     {
         firstChunk  = length;
         secondChunk = 0;
     }
     Com_Memcpy( consoleLog + writePos, in, firstChunk );
     Com_Memcpy( consoleLog, in + firstChunk, secondChunk );
     writePos = ( writePos + length ) % MAX_LOG;
     return length;
 }
References Com_Memcpy, CON_LogFree(), CON_LogSize(), consoleLog, MAX_LOG, readPos, and writePos.
Referenced by Sys_Print().
CON_Print()
void CON_Print (const char * message)
Definition at line 62 of file con_passive.c.
 {
     if( com_ansiColor && com_ansiColor->integer )
         Sys_AnsiColorPrint( msg );
     else
         fputs( msg, stderr );
 }
References com_ansiColor, CON_Hide(), CON_Show(), Sys_AnsiColorPrint(), ttycon_on, and ttycon_show_overdue.
Referenced by Sys_Print().
CON_Shutdown()
void CON_Shutdown (void)
Definition at line 34 of file con_passive.c.
 {
 }
References CON_Hide(), qconsole_hin, qconsole_hout, qconsole_orig_cursorinfo, qconsole_orig_mode, TTY_tc, and ttycon_on.
Referenced by __attribute__().
IN_Frame()
void IN_Frame (void)
Definition at line 26 of file null_input.c.
                      {
 }
References CA_ACTIVE, CA_DISCONNECTED, Cbuf_AddText(), clc, Cvar_VariableIntegerValue(), IN_ActivateMouse(), IN_DeactivateMouse(), IN_JoyMove(), IN_ProcessEvents(), Key_GetCatcher(), KEYCATCH_CONSOLE, SDL_APPINPUTFOCUS, SDL_GetAppState(), clientConnection_t::state, Sys_Milliseconds(), and vidRestartTime.
Referenced by main().
IN_Init()
void IN_Init (void)
Definition at line 23 of file null_input.c.
                      {
 }
References Com_DPrintf(), Com_Error(), CVAR_ARCHIVE, Cvar_Get(), CVAR_LATCH, Cvar_SetValue(), CVAR_TEMP, ERR_FATAL, IN_DeactivateMouse(), IN_InitJoystick(), IN_InitKeyLockStates(), in_joystick, in_joystickDebug, in_joystickThreshold, in_keyboardDebug, in_mouse, in_nograb, keyRepeatEnabled, mouseAvailable, qtrue, SDL_APPACTIVE, SDL_APPINPUTFOCUS, SDL_DEFAULT_REPEAT_DELAY, SDL_DEFAULT_REPEAT_INTERVAL, SDL_EnableKeyRepeat(), SDL_EnableUNICODE(), SDL_GetAppState(), SDL_INIT_VIDEO, and SDL_WasInit().
Referenced by CL_InitRef(), and IN_Restart().
IN_Restart()
void IN_Restart (void)
Definition at line 32 of file null_input.c.
{
 }
References IN_Init(), and IN_ShutdownJoystick().
Referenced by CL_InitRef(), and Sys_In_Restart_f().
IN_Shutdown()
void IN_Shutdown (void)
Definition at line 29 of file null_input.c.
{
 }
References IN_DeactivateMouse(), IN_ShutdownJoystick(), mouseAvailable, and qfalse.
Referenced by CL_InitRef().
Sys_AnsiColorPrint()
void Sys_AnsiColorPrint (const char * msg)
Definition at line 267 of file sys_main.c.
 {
     static char buffer[ MAXPRINTMSG ];
     int         length = 0;
     static int  q3ToAnsi[ 8 ] =
     {
         30, // COLOR_BLACK
         31, // COLOR_RED
         32, // COLOR_GREEN
         33, // COLOR_YELLOW
         34, // COLOR_BLUE
         36, // COLOR_CYAN
         35, // COLOR_MAGENTA
         0   // COLOR_WHITE
     };
     while( *msg )
     {
         if( Q_IsColorString( msg ) || *msg == '\n' )
         {
             // First empty the buffer
             if( length > 0 )
             {
                 buffer[ length ] = '\0';
                 fputs( buffer, stderr );
                 length = 0;
             }
             if( *msg == '\n' )
             {
                 // Issue a reset and then the newline
                 fputs( "\033[0m\n", stderr );
                 msg++;
             }
             else
             {
                 // Print the color code
                 Com_sprintf( buffer, sizeof( buffer ), "\033[%dm",
                         q3ToAnsi[ ColorIndex( *( msg + 1 ) ) ] );
                 fputs( buffer, stderr );
                 msg += 2;
             }
         }
         else
         {
             if( length >= MAXPRINTMSG - 1 )
                 break;
             buffer[ length ] = *msg;
             length++;
             msg++;
         }
     }
     // Empty anything still left in the buffer
     if( length > 0 )
     {
         buffer[ length ] = '\0';
         fputs( buffer, stderr );
     }
 }
References ColorIndex, Com_sprintf(), MAXPRINTMSG, and Q_IsColorString.
Referenced by CON_Print().
Sys_ErrorDialog()
void Sys_ErrorDialog (const char * error)
Definition at line 510 of file sys_unix.c.
 {
     char buffer[ 1024 ];
     unsigned int size;
     int f = -1;
     const char *homepath = Cvar_VariableString( "fs_homepath" );
     const char *gamedir = Cvar_VariableString( "fs_game" );
     const char *fileName = "crashlog.txt";
     char *ospath = FS_BuildOSPath( homepath, gamedir, fileName );
     Sys_Print( va( "%s\n", error ) );
 #ifndef DEDICATED
     Sys_Dialog( DT_ERROR, va( "%s. See \"%s\" for details.", error, ospath ), "Error" );
 #endif
     // Make sure the write path for the crashlog exists...
     if( FS_CreatePath( ospath ) ) {
         Com_Printf( "ERROR: couldn't create path '%s' for crash log.\n", ospath );
         return;
     }
     // We might be crashing because we maxed out the Quake MAX_FILE_HANDLES,
     // which will come through here, so we don't want to recurse forever by
     // calling FS_FOpenFileWrite()...use the Unix system APIs instead.
     f = open( ospath, O_CREAT | O_TRUNC | O_WRONLY, 0640 );
     if( f == -1 )
     {
         Com_Printf( "ERROR: couldn't open %s\n", fileName );
         return;
     }
     // We're crashing, so we don't care much if write() or close() fails.
     while( ( size = CON_LogRead( buffer, sizeof( buffer ) ) ) > 0 ) {
         if( write( f, buffer, size ) != size ) {
             Com_Printf( "ERROR: couldn't fully write to %s\n", fileName );
             break;
         }
     }
     close( f );
 }
References Com_Memcpy, Com_Printf(), CON_LogRead(), CON_LogSize(), Cvar_VariableString(), DR_YES, DT_ERROR, DT_YES_NO, error(), FS_BuildOSPath(), FS_CreatePath(), gamedir, NULL, Sys_Dialog(), Sys_Print(), and va().
Referenced by Sys_Error().
Sys_GLimpInit()
void Sys_GLimpInit (void)
Definition at line 806 of file sys_unix.c.
 {
     // NOP
 }
References Cvar_VariableIntegerValue(), and SDL_VIDEODRIVER_externallySet.
Referenced by CL_InitRef().
Sys_GLimpSafeInit()
void Sys_GLimpSafeInit (void)
Definition at line 794 of file sys_unix.c.
 {
     // NOP
 }
References SDL_VIDEODRIVER_externallySet.
Referenced by CL_InitRef().
Sys_PID()
int Sys_PID (void)
Definition at line 870 of file sys_unix.c.
 {
     return getpid( );
 }
References getpid().
Referenced by Sys_WritePIDFile().
Sys_PIDIsRunning()
qboolean Sys_PIDIsRunning (int pid)
Definition at line 880 of file sys_unix.c.
 {
     return kill( pid, 0 ) == 0;
 }
References kill(), qfalse, and qtrue.
Referenced by Sys_WritePIDFile().
Sys_PlatformExit()
void Sys_PlatformExit (void)
Definition at line 845 of file sys_unix.c.
 {
 }
References timerResolution.
Referenced by __attribute__().
Sys_PlatformInit()
void Sys_PlatformInit (void)
Definition at line 824 of file sys_unix.c.
 {
     const char* term = getenv( "TERM" );
     signal( SIGHUP, Sys_SigHandler );
     signal( SIGQUIT, Sys_SigHandler );
     signal( SIGTRAP, Sys_SigHandler );
     signal( SIGIOT, Sys_SigHandler );
     signal( SIGBUS, Sys_SigHandler );
     stdinIsATTY = isatty( STDIN_FILENO ) &&
         !( term && ( !strcmp( term, "raw" ) || !strcmp( term, "dumb" ) ) );
 }
References Com_Printf(), qfalse, qtrue, SDL_VIDEODRIVER_externallySet, stdinIsATTY, Sys_SetFloatEnv(), Sys_SigHandler(), and timerResolution.
Referenced by main().
Sys_SigHandler()
void Sys_SigHandler (int signal)
Definition at line 540 of file sys_main.c.
 {
     static qboolean signalcaught = qfalse;
     if( signalcaught )
     {
         fprintf( stderr, "DOUBLE SIGNAL FAULT: Received signal %d, exiting...\n",
             signal );
     }
     else
     {
         signalcaught = qtrue;
         VM_Forced_Unload_Start();
 #ifndef DEDICATED
         CL_Shutdown(va("Received signal %d", signal), qtrue, qtrue);
 #endif
         SV_Shutdown(va("Received signal %d", signal) );
         VM_Forced_Unload_Done();
     }
     if( signal == SIGTERM || signal == SIGINT )
         Sys_Exit( 1 );
     else
         Sys_Exit( 2 );
 }
References CL_Shutdown(), qfalse, qtrue, SV_Shutdown(), va(), VM_Forced_Unload_Done(), and VM_Forced_Unload_Start().
Referenced by CON_CtrlHandler(), main(), and Sys_PlatformInit().