ZEQ2-Lite: Source/Engine/client/cl_net_chan.c File Reference
cl_net_chan.c File Reference
#include "../../Shared/q_shared.h"
#include "../../Shared/qcommon.h"
#include "client.h"
Functions
qboolean CL_Netchan_Process (netchan_t *chan, msg_t *msg)
void CL_Netchan_Transmit (netchan_t *chan, msg_t *msg)
qboolean CL_Netchan_TransmitNextFragment (netchan_t *chan)
Function Documentation
CL_Netchan_Process()
qboolean CL_Netchan_Process (netchan_t * chan, msg_t * msg)
Definition at line 174 of file cl_net_chan.c.
{
     int ret;
     ret = Netchan_Process( chan, msg );
     if (!ret)
         return qfalse;
 #ifdef LEGACY_PROTOCOL
     if(chan->compat)
         CL_Netchan_Decode(msg);
 #endif
     return qtrue;
 }
References Netchan_Process(), qfalse, and qtrue.
Referenced by CL_PacketEvent().
CL_Netchan_Transmit()
void CL_Netchan_Transmit (netchan_t * chan, msg_t * msg)
Definition at line 152 of file cl_net_chan.c.
{
     MSG_WriteByte( msg, clc_EOF );
 #ifdef LEGACY_PROTOCOL
     if(chan->compat)
         CL_Netchan_Encode(msg);
 #endif
     Netchan_Transmit(chan, msg->cursize, msg->data);
     // Transmit all fragments without delay
     while(CL_Netchan_TransmitNextFragment(chan))
     {
         Com_DPrintf("WARNING: #462 unsent fragments (not supposed to happen!)\n");
     }
 }
References CL_Netchan_TransmitNextFragment(), clc_EOF, Com_DPrintf(), msg_t::cursize, msg_t::data, MSG_WriteByte(), and Netchan_Transmit().
Referenced by CL_WritePacket().
CL_Netchan_TransmitNextFragment()
qboolean CL_Netchan_TransmitNextFragment (netchan_t * chan)
Definition at line 136 of file cl_net_chan.c.
 {
     if(chan->unsentFragments)
     {
         Netchan_TransmitNextFragment(chan);
         return qtrue;
     }
     return qfalse;
 }
References Netchan_TransmitNextFragment(), qfalse, qtrue, and netchan_t::unsentFragments.
Referenced by CL_Netchan_Transmit().