ZEQ2-Lite: Region Class Reference
Region Class Reference
#include <gdiplusheaders.h>
Public Member Functions
Region ()
Region (const BYTE *regionData, INT size)
Region (const GraphicsPath *path)
Region (const Rect &rect)
Region (const RectF &rect)
Region (HRGN hrgn)
~Region ()
Region * Clone () const
Status Complement (const GraphicsPath *path)
Status Complement (const Rect &rect)
Status Complement (const RectF &rect)
Status Complement (const Region *region)
BOOL Equals (const Region *region, const Graphics *graphics) const
Status Exclude (const GraphicsPath *path)
Status Exclude (const Rect &rect)
Status Exclude (const RectF &rect)
Status Exclude (const Region *region)
Status GetBounds (Rect *rect, const Graphics *graphics) const
Status GetBounds (RectF *rect, const Graphics *graphics) const
Status GetData (BYTE *buffer, UINT bufferSize, UINT *sizeFilled) const
UINT GetDataSize () const
HRGN GetHRGN (const Graphics *graphics) const
Status GetLastStatus () const
Status GetRegionScans (const Matrix *matrix, Rect *rects, INT *count) const
Status GetRegionScans (const Matrix *matrix, RectF *rects, INT *count) const
UINT GetRegionScansCount (const Matrix *matrix) const
Status Intersect (const GraphicsPath *path)
Status Intersect (const Rect &rect)
Status Intersect (const RectF &rect)
Status Intersect (const Region *region)
BOOL IsEmpty (const Graphics *graphics) const
BOOL IsInfinite (const Graphics *graphics) const
BOOL IsVisible (const Point &point, const Graphics *graphics=NULL) const
BOOL IsVisible (const PointF &point, const Graphics *graphics=NULL) const
BOOL IsVisible (const Rect &rect, const Graphics *graphics=NULL) const
BOOL IsVisible (const RectF &rect, const Graphics *graphics=NULL) const
BOOL IsVisible (INT x, INT y, const Graphics *graphics=NULL) const
BOOL IsVisible (INT x, INT y, INT width, INT height, const Graphics *graphics=NULL) const
BOOL IsVisible (REAL x, REAL y, const Graphics *graphics=NULL) const
BOOL IsVisible (REAL x, REAL y, REAL width, REAL height, const Graphics *graphics=NULL) const
Status MakeEmpty ()
Status MakeInfinite ()
Status Transform (const Matrix *matrix)
Status Translate (INT dx, INT dy)
Status Translate (REAL dx, REAL dy)
Status Union (const GraphicsPath *path)
Status Union (const Rect &rect)
Status Union (const RectF &rect)
Status Union (const Region *region)
Status Xor (const GraphicsPath *path)
Status Xor (const Rect &rect)
Status Xor (const RectF &rect)
Status Xor (const Region *region)
Static Public Member Functions
static Region * FromHRGN (HRGN hrgn)
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Region (const Region &)
Region (GpRegion *region, Status status)
Region & operator= (const Region &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpRegion * nativeRegion
Friends
class Graphics
Detailed Description
Definition at line 487 of file gdiplusheaders.h.
Constructor & Destructor Documentation
Region() [1/8]
__inline__ Region::Region ()
Definition at line 1115 of file gdiplusimpl.h.
                          : nativeRegion(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateRegion(&nativeRegion);
 }
References GdipCreateRegion(), lastStatus, and nativeRegion.
Referenced by Clone(), and FromHRGN().
Region() [2/8]
__inline__ Region::Region (const RectF & rect)
Definition at line 1120 of file gdiplusimpl.h.
                                           : nativeRegion(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateRegionRect(&rect, &nativeRegion);
 }
References GdipCreateRegionRect(), lastStatus, and nativeRegion.
Region() [3/8]
__inline__ Region::Region (const Rect & rect)
Definition at line 1125 of file gdiplusimpl.h.
                                          : nativeRegion(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateRegionRectI(&rect, &nativeRegion);
 }
References GdipCreateRegionRectI(), lastStatus, and nativeRegion.
Region() [4/8]
__inline__ Region::Region (const GraphicsPath * path)
Definition at line 1130 of file gdiplusimpl.h.
                                                  :
     nativeRegion(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateRegionPath(
             path ? path->nativePath : NULL, &nativeRegion);
 }
References GdipCreateRegionPath(), lastStatus, GraphicsPath::nativePath, nativeRegion, and NULL.
Region() [5/8]
__inline__ Region::Region (const BYTE * regionData, INT size)
Definition at line 1137 of file gdiplusimpl.h.
                                                          :
     nativeRegion(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateRegionRgnData(
             regionData, size, &nativeRegion);
 }
References GdipCreateRegionRgnData(), lastStatus, and nativeRegion.
Region() [6/8]
__inline__ Region::Region (HRGN hrgn)
Definition at line 1144 of file gdiplusimpl.h.
                                   : nativeRegion(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateRegionHrgn(hrgn, &nativeRegion);
 }
References GdipCreateRegionHrgn(), lastStatus, and nativeRegion.
~Region()
__inline__ Region::~Region ()
Definition at line 1149 of file gdiplusimpl.h.
 {
     DllExports::GdipDeleteRegion(nativeRegion);
 }
References GdipDeleteRegion(), and nativeRegion.
Region() [7/8]
Region::Region (GpRegion * region, Status status) inline private
Definition at line 566 of file gdiplusheaders.h.
                                            :
         nativeRegion(region), lastStatus(status) {}
Region() [8/8]
Region::Region (const Region &) private
Member Function Documentation
Clone()
__inline__ Region * Region::Clone () const
Definition at line 1154 of file gdiplusimpl.h.
 {
     GpRegion *cloneRegion = NULL;
     Status status = updateStatus(DllExports::GdipCloneRegion(
             nativeRegion, &cloneRegion));
     if (status == Ok) {
         Region *result = new Region(cloneRegion, lastStatus);
         if (!result) {
             DllExports::GdipDeleteRegion(cloneRegion);
             lastStatus = OutOfMemory;
         }
         return result;
     } else {
         return NULL;
     }
 }
References GdipCloneRegion(), GdipDeleteRegion(), lastStatus, nativeRegion, NULL, Ok, OutOfMemory, Region(), and updateStatus().
Complement() [1/4]
__inline__ Status Region::Complement (const GraphicsPath * path)
Definition at line 1190 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionPath(
             nativeRegion, path ? path->nativePath : NULL,
             CombineModeComplement));
 }
References CombineModeComplement, GdipCombineRegionPath(), GraphicsPath::nativePath, nativeRegion, NULL, and updateStatus().
Complement() [2/4]
__inline__ Status Region::Complement (const Rect & rect)
Definition at line 1177 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRectI(
             nativeRegion, &rect, CombineModeComplement));
 }
References CombineModeComplement, GdipCombineRegionRectI(), nativeRegion, and updateStatus().
Complement() [3/4]
__inline__ Status Region::Complement (const RectF & rect)
Definition at line 1171 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRect(
             nativeRegion, &rect, CombineModeComplement));
 }
References CombineModeComplement, GdipCombineRegionRect(), nativeRegion, and updateStatus().
Complement() [4/4]
__inline__ Status Region::Complement (const Region * region)
Definition at line 1183 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRegion(
             nativeRegion, region ? region->nativeRegion : NULL,
             CombineModeComplement));
 }
References CombineModeComplement, GdipCombineRegionRegion(), nativeRegion, NULL, and updateStatus().
Equals()
__inline__ BOOL Region::Equals (const Region * region, const Graphics * graphics) const
Definition at line 1197 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsEqualRegion(
             nativeRegion, region ? region->nativeRegion : NULL,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsEqualRegion(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
Exclude() [1/4]
__inline__ Status Region::Exclude (const GraphicsPath * path)
Definition at line 1226 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionPath(
             nativeRegion, path ? path->nativePath : NULL,
             CombineModeExclude));
 }
References CombineModeExclude, GdipCombineRegionPath(), GraphicsPath::nativePath, nativeRegion, NULL, and updateStatus().
Exclude() [2/4]
__inline__ Status Region::Exclude (const Rect & rect)
Definition at line 1213 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRectI(
             nativeRegion, &rect, CombineModeExclude));
 }
References CombineModeExclude, GdipCombineRegionRectI(), nativeRegion, and updateStatus().
Exclude() [3/4]
__inline__ Status Region::Exclude (const RectF & rect)
Definition at line 1207 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRect(
             nativeRegion, &rect, CombineModeExclude));
 }
References CombineModeExclude, GdipCombineRegionRect(), nativeRegion, and updateStatus().
Exclude() [4/4]
__inline__ Status Region::Exclude (const Region * region)
Definition at line 1219 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRegion(
             nativeRegion, region ? region->nativeRegion : NULL,
             CombineModeExclude));
 }
References CombineModeExclude, GdipCombineRegionRegion(), nativeRegion, NULL, and updateStatus().
FromHRGN()
__inline__ Region * Region::FromHRGN (HRGN hrgn) static
Definition at line 1110 of file gdiplusimpl.h.
 {
     return new Region(hrgn);
 }
References Region().
GetBounds() [1/2]
__inline__ Status Region::GetBounds (Rect * rect, const Graphics * graphics) const
Definition at line 1239 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetRegionBoundsI(nativeRegion,
             graphics ? graphics->nativeGraphics : NULL, rect));
 }
References GdipGetRegionBoundsI(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
GetBounds() [2/2]
__inline__ Status Region::GetBounds (RectF * rect, const Graphics * graphics) const
Definition at line 1233 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetRegionBounds(nativeRegion,
             graphics ? graphics->nativeGraphics : NULL, rect));
 }
References GdipGetRegionBounds(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
GetData()
__inline__ Status Region::GetData (BYTE * buffer, UINT bufferSize, UINT * sizeFilled) const
Definition at line 1245 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetRegionData(
             nativeRegion, buffer, bufferSize, sizeFilled));
 }
References GdipGetRegionData(), nativeRegion, and updateStatus().
GetDataSize()
__inline__ UINT Region::GetDataSize () const
Definition at line 1252 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetRegionDataSize(nativeRegion, &result));
     return result;
 }
References GdipGetRegionDataSize(), nativeRegion, and updateStatus().
GetHRGN()
__inline__ HRGN Region::GetHRGN (const Graphics * graphics) const
Definition at line 1259 of file gdiplusimpl.h.
 {
     HRGN result = NULL;
     updateStatus(DllExports::GdipGetRegionHRgn(nativeRegion,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References GdipGetRegionHRgn(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
GetLastStatus()
Status Region::GetLastStatus () const inline
Definition at line 558 of file gdiplusheaders.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetRegionScans() [1/2]
__inline__ Status Region::GetRegionScans (const Matrix * matrix, Rect * rects, INT * count) const
Definition at line 1275 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetRegionScansI(
             nativeRegion, rects, count,
             matrix ? matrix->nativeMatrix : NULL));
 }
References GdipGetRegionScansI(), nativeRegion, NULL, and updateStatus().
GetRegionScans() [2/2]
__inline__ Status Region::GetRegionScans (const Matrix * matrix, RectF * rects, INT * count) const
Definition at line 1267 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetRegionScans(
             nativeRegion, rects, count,
             matrix ? matrix->nativeMatrix : NULL));
 }
References GdipGetRegionScans(), nativeRegion, NULL, and updateStatus().
GetRegionScansCount()
__inline__ UINT Region::GetRegionScansCount (const Matrix * matrix) const
Definition at line 1283 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetRegionScansCount(
             nativeRegion, &result,
             matrix ? matrix->nativeMatrix : NULL));
     return result;
 }
References GdipGetRegionScansCount(), nativeRegion, NULL, and updateStatus().
Intersect() [1/4]
__inline__ Status Region::Intersect (const GraphicsPath * path)
Definition at line 1311 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionPath(
             nativeRegion, path ? path->nativePath : NULL,
             CombineModeIntersect));
 }
References CombineModeIntersect, GdipCombineRegionPath(), GraphicsPath::nativePath, nativeRegion, NULL, and updateStatus().
Intersect() [2/4]
__inline__ Status Region::Intersect (const Rect & rect)
Definition at line 1298 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRectI(
             nativeRegion, &rect, CombineModeIntersect));
 }
References CombineModeIntersect, GdipCombineRegionRectI(), nativeRegion, and updateStatus().
Intersect() [3/4]
__inline__ Status Region::Intersect (const RectF & rect)
Definition at line 1292 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRect(
             nativeRegion, &rect, CombineModeIntersect));
 }
References CombineModeIntersect, GdipCombineRegionRect(), nativeRegion, and updateStatus().
Intersect() [4/4]
__inline__ Status Region::Intersect (const Region * region)
Definition at line 1304 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRegion(
             nativeRegion, region ? region->nativeRegion : NULL,
             CombineModeIntersect));
 }
References CombineModeIntersect, GdipCombineRegionRegion(), nativeRegion, NULL, and updateStatus().
IsEmpty()
__inline__ BOOL Region::IsEmpty (const Graphics * graphics) const
Definition at line 1318 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsEmptyRegion(nativeRegion,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsEmptyRegion(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
IsInfinite()
__inline__ BOOL Region::IsInfinite (const Graphics * graphics) const
Definition at line 1326 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsInfiniteRegion(nativeRegion,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsInfiniteRegion(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
IsVisible() [1/8]
__inline__ BOOL Region::IsVisible (const Point & point, const Graphics * graphics = NULL) const
Definition at line 1364 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisibleRegionPointI(
             nativeRegion, point.X, point.Y,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisibleRegionPointI(), Graphics::nativeGraphics, nativeRegion, NULL, updateStatus(), Point::X, and Point::Y.
IsVisible() [2/8]
__inline__ BOOL Region::IsVisible (const PointF & point, const Graphics * graphics = NULL) const
Definition at line 1354 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisibleRegionPoint(
             nativeRegion, point.X, point.Y,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisibleRegionPoint(), Graphics::nativeGraphics, nativeRegion, NULL, updateStatus(), PointF::X, and PointF::Y.
IsVisible() [3/8]
__inline__ BOOL Region::IsVisible (const Rect & rect, const Graphics * graphics = NULL) const
Definition at line 1404 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisibleRegionRectI(
             nativeRegion, rect.X, rect.Y, rect.Width, rect.Height,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisibleRegionRectI(), Rect::Height, Graphics::nativeGraphics, nativeRegion, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
IsVisible() [4/8]
__inline__ BOOL Region::IsVisible (const RectF & rect, const Graphics * graphics = NULL) const
Definition at line 1394 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisibleRegionRect(
             nativeRegion, rect.X, rect.Y, rect.Width, rect.Height,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisibleRegionRect(), RectF::Height, Graphics::nativeGraphics, nativeRegion, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
IsVisible() [5/8]
__inline__ BOOL Region::IsVisible (INT x, INT y, const Graphics * graphics = NULL) const
Definition at line 1344 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisibleRegionPointI(
             nativeRegion, x, y,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisibleRegionPointI(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
IsVisible() [6/8]
__inline__ BOOL Region::IsVisible (INT x, INT y, INT width, INT height, const Graphics * graphics = NULL) const
Definition at line 1384 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisibleRegionRectI(
             nativeRegion, x, y, width, height,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisibleRegionRectI(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
IsVisible() [7/8]
__inline__ BOOL Region::IsVisible (REAL x, REAL y, const Graphics * graphics = NULL) const
Definition at line 1334 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisibleRegionPoint(
             nativeRegion, x, y,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisibleRegionPoint(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
IsVisible() [8/8]
__inline__ BOOL Region::IsVisible (REAL x, REAL y, REAL width, REAL height, const Graphics * graphics = NULL) const
Definition at line 1374 of file gdiplusimpl.h.
 {
     BOOL result = FALSE;
     updateStatus(DllExports::GdipIsVisibleRegionRect(
             nativeRegion, x, y, width, height,
             graphics ? graphics->nativeGraphics : NULL, &result));
     return result;
 }
References FALSE, GdipIsVisibleRegionRect(), Graphics::nativeGraphics, nativeRegion, NULL, and updateStatus().
MakeEmpty()
__inline__ Status Region::MakeEmpty ()
Definition at line 1414 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetEmpty(nativeRegion));
 }
References GdipSetEmpty(), nativeRegion, and updateStatus().
MakeInfinite()
__inline__ Status Region::MakeInfinite ()
Definition at line 1419 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetInfinite(nativeRegion));
 }
References GdipSetInfinite(), nativeRegion, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Region& Region::operator= (const Region &) private
Transform()
__inline__ Status Region::Transform (const Matrix * matrix)
Definition at line 1424 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipTransformRegion(
             nativeRegion, matrix ? matrix->nativeMatrix : NULL));
 }
References GdipTransformRegion(), nativeRegion, NULL, and updateStatus().
Translate() [1/2]
__inline__ Status Region::Translate (INT dx, INT dy)
Definition at line 1436 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipTranslateRegionI(
             nativeRegion, dx, dy));
 }
References GdipTranslateRegionI(), nativeRegion, and updateStatus().
Translate() [2/2]
__inline__ Status Region::Translate (REAL dx, REAL dy)
Definition at line 1430 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipTranslateRegion(
             nativeRegion, dx, dy));
 }
References GdipTranslateRegion(), nativeRegion, and updateStatus().
Union() [1/4]
__inline__ Status Region::Union (const GraphicsPath * path)
Definition at line 1461 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionPath(
             nativeRegion, path ? path->nativePath : NULL,
             CombineModeUnion));
 }
References CombineModeUnion, GdipCombineRegionPath(), GraphicsPath::nativePath, nativeRegion, NULL, and updateStatus().
Union() [2/4]
__inline__ Status Region::Union (const Rect & rect)
Definition at line 1448 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRectI(
             nativeRegion, &rect, CombineModeUnion));
 }
References CombineModeUnion, GdipCombineRegionRectI(), nativeRegion, and updateStatus().
Union() [3/4]
__inline__ Status Region::Union (const RectF & rect)
Definition at line 1442 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRect(
             nativeRegion, &rect, CombineModeUnion));
 }
References CombineModeUnion, GdipCombineRegionRect(), nativeRegion, and updateStatus().
Union() [4/4]
__inline__ Status Region::Union (const Region * region)
Definition at line 1454 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRegion(
             nativeRegion, region ? region->nativeRegion : NULL,
             CombineModeUnion));
 }
References CombineModeUnion, GdipCombineRegionRegion(), nativeRegion, NULL, and updateStatus().
updateStatus()
Status Region::updateStatus (Status newStatus) const inline private
Definition at line 571 of file gdiplusheaders.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by Clone(), Complement(), Equals(), Exclude(), GetBounds(), GetData(), GetDataSize(), GetHRGN(), GetRegionScans(), GetRegionScansCount(), Intersect(), IsEmpty(), IsInfinite(), IsVisible(), MakeEmpty(), MakeInfinite(), Transform(), Translate(), Union(), and Xor().
Xor() [1/4]
__inline__ Status Region::Xor (const GraphicsPath * path)
Definition at line 1487 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionPath(
             nativeRegion, path ? path->nativePath : NULL,
             CombineModeXor));
 }
References CombineModeXor, GdipCombineRegionPath(), GraphicsPath::nativePath, nativeRegion, NULL, and updateStatus().
Xor() [2/4]
__inline__ Status Region::Xor (const Rect & rect)
Definition at line 1474 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRectI(
             nativeRegion, &rect, CombineModeXor));
 }
References CombineModeXor, GdipCombineRegionRectI(), nativeRegion, and updateStatus().
Xor() [3/4]
__inline__ Status Region::Xor (const RectF & rect)
Definition at line 1468 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRect(
             nativeRegion, &rect, CombineModeXor));
 }
References CombineModeXor, GdipCombineRegionRect(), nativeRegion, and updateStatus().
Xor() [4/4]
__inline__ Status Region::Xor (const Region * region)
Definition at line 1480 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipCombineRegionRegion(
             nativeRegion, region ? region->nativeRegion : NULL,
             CombineModeXor));
 }
References CombineModeXor, GdipCombineRegionRegion(), nativeRegion, NULL, and updateStatus().
Friends And Related Function Documentation
Graphics
friend class Graphics friend
Definition at line 489 of file gdiplusheaders.h.
Field Documentation
lastStatus
Status Region::lastStatus mutable private
Definition at line 578 of file gdiplusheaders.h.
Referenced by Clone(), GetLastStatus(), Region(), and updateStatus().
nativeRegion
GpRegion* Region::nativeRegion private
Definition at line 577 of file gdiplusheaders.h.
Referenced by Clone(), Complement(), Equals(), Exclude(), Graphics::ExcludeClip(), Graphics::FillRegion(), GetBounds(), Graphics::GetClip(), GetData(), GetDataSize(), GetHRGN(), GetRegionScans(), GetRegionScansCount(), Intersect(), Graphics::IntersectClip(), IsEmpty(), IsInfinite(), IsVisible(), MakeEmpty(), MakeInfinite(), Graphics::MeasureCharacterRanges(), Region(), Graphics::SetClip(), Transform(), Translate(), Union(), Xor(), and ~Region().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdiplusheaders.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h