ZEQ2-Lite: Source/Engine/libspeex/ltp.h File Reference
ltp.h File Reference
Long-Term Prediction functions.
#include <speex/speex_bits.h>
#include "arch.h"
Data Structures
struct ltp_params
LTP parameters.
Macros
#define gain_3tap_to_1tap(g) (ABS(g[1]) + (g[0]>0 ? g[0] : -.5*g[0]) + (g[2]>0 ? g[2] : -.5*g[2]))
Functions
int forced_pitch_quant (spx_word16_t target[], spx_word16_t *sw, spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], spx_sig_t exc[], const void *par, int start, int end, spx_word16_t pitch_coef, int p, int nsf, SpeexBits *bits, char *stack, spx_word16_t *exc2, spx_word16_t *r, int complexity, int cdbk_offset, int plc_tuning, spx_word32_t *cumul_gain)
Forced pitch delay and gain.
void forced_pitch_unquant (spx_word16_t exc[], spx_word32_t exc_out[], int start, int end, spx_word16_t pitch_coef, const void *par, int nsf, int *pitch_val, spx_word16_t *gain_val, SpeexBits *bits, char *stack, int lost, int subframe_offset, spx_word16_t last_pitch_gain, int cdbk_offset)
Unquantize forced pitch delay and gain.
spx_word32_t inner_prod (const spx_word16_t *x, const spx_word16_t *y, int len)
void open_loop_nbest_pitch (spx_word16_t *sw, int start, int end, int len, int *pitch, spx_word16_t *gain, int N, char *stack)
int pitch_search_3tap (spx_word16_t target[], spx_word16_t *sw, spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], spx_sig_t exc[], const void *par, int start, int end, spx_word16_t pitch_coef, int p, int nsf, SpeexBits *bits, char *stack, spx_word16_t *exc2, spx_word16_t *r, int complexity, int cdbk_offset, int plc_tuning, spx_word32_t *cumul_gain)
Finds the best quantized 3-tap pitch predictor by analysis by synthesis.
void pitch_unquant_3tap (spx_word16_t exc[], spx_word32_t exc_out[], int start, int end, spx_word16_t pitch_coef, const void *par, int nsf, int *pitch_val, spx_word16_t *gain_val, SpeexBits *bits, char *stack, int lost, int subframe_offset, spx_word16_t last_pitch_gain, int cdbk_offset)
void pitch_xcorr (const spx_word16_t *_x, const spx_word16_t *_y, spx_word32_t *corr, int len, int nb_pitch, char *stack)
Detailed Description
Long-Term Prediction functions.
Definition in file ltp.h.
Macro Definition Documentation
gain_3tap_to_1tap
#define gain_3tap_to_1tap (g) (ABS(g[1]) + (g[0]>0 ? g[0] : -.5*g[0]) + (g[2]>0 ? g[2] : -.5*g[2]))
Definition at line 48 of file ltp.h.
Function Documentation
forced_pitch_quant()
int forced_pitch_quant (spx_word16_t target[], spx_word16_t * sw, spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], spx_sig_t exc[], const void * par, int start, int end, spx_word16_t pitch_coef, int p, int nsf, SpeexBits * bits, char * stack, spx_word16_t * exc2, spx_word16_t * r, int complexity, int cdbk_offset, int plc_tuning, spx_word32_t * cumul_gain)
Forced pitch delay and gain.
Definition at line 755 of file ltp.c.
 {
    int i;
    VARDECL(spx_word16_t *res);
    ALLOC(res, nsf, spx_word16_t);
 #ifdef FIXED_POINT
    if (pitch_coef>63)
       pitch_coef=63;
 #else
    if (pitch_coef>.99)
       pitch_coef=.99;
 #endif
    for (i=0;i<nsf&&i<start;i++)
    {
       exc[i]=MULT16_16(SHL16(pitch_coef, 7),exc2[i-start]);
    }
    for (;i<nsf;i++)
    {
       exc[i]=MULT16_32_Q15(SHL16(pitch_coef, 9),exc[i-start]);
    }
    for (i=0;i<nsf;i++)
       res[i] = EXTRACT16(PSHR32(exc[i], SIG_SHIFT-1));
    syn_percep_zero16(res, ak, awk1, awk2, res, nsf, p, stack);
    for (i=0;i<nsf;i++)
       target[i]=EXTRACT16(SATURATE(SUB32(EXTEND32(target[i]),EXTEND32(res[i])),32700));
    return start;
 }
References ALLOC, EXTEND32, EXTRACT16, MULT16_16, MULT16_32_Q15, PSHR32, SATURATE, SHL16, SUB32, syn_percep_zero16(), and VARDECL.
forced_pitch_unquant()
void forced_pitch_unquant (spx_word16_t exc[], spx_word32_t exc_out[], int start, int end, spx_word16_t pitch_coef, const void * par, int nsf, int * pitch_val, spx_word16_t * gain_val, SpeexBits * bits, char * stack, int lost, int subframe_offset, spx_word16_t last_pitch_gain, int cdbk_offset)
Unquantize forced pitch delay and gain.
Definition at line 805 of file ltp.c.
 {
    int i;
 #ifdef FIXED_POINT
    if (pitch_coef>63)
       pitch_coef=63;
 #else
    if (pitch_coef>.99)
       pitch_coef=.99;
 #endif
    for (i=0;i<nsf;i++)
    {
       exc_out[i]=MULT16_16(exc[i-start],SHL16(pitch_coef,7));
       exc[i] = EXTRACT16(PSHR32(exc_out[i],13));
    }
    *pitch_val = start;
    gain_val[0]=gain_val[2]=0;
    gain_val[1] = pitch_coef;
 }
References EXTRACT16, MULT16_16, PSHR32, and SHL16.
inner_prod()
spx_word32_t inner_prod (const spx_word16_t * x, const spx_word16_t * y, int len)
Definition at line 59 of file ltp.c.
 {
    spx_word32_t sum=0;
    len >>= 2;
    while(len--)
    {
       spx_word32_t part=0;
       part = MAC16_16(part,*x++,*y++);
       part = MAC16_16(part,*x++,*y++);
       part = MAC16_16(part,*x++,*y++);
       part = MAC16_16(part,*x++,*y++);
       /* HINT: If you had a 40-bit accumulator, you could shift only at the end */
       sum = ADD32(sum,SHR32(part,6));
    }
    return sum;
 }
References ADD32, MAC16_16, and SHR32.
Referenced by interp_pitch(), multicomb(), open_loop_nbest_pitch(), pitch_gain_search_3tap(), and pitch_xcorr().
open_loop_nbest_pitch()
void open_loop_nbest_pitch (spx_word16_t * sw, int start, int end, int len, int * pitch, spx_word16_t * gain, int N, char * stack)
Definition at line 173 of file ltp.c.
 {
    int i,j,k;
    VARDECL(spx_word32_t *best_score);
    VARDECL(spx_word32_t *best_ener);
    spx_word32_t e0;
    VARDECL(spx_word32_t *corr);
 #ifdef FIXED_POINT
    /* In fixed-point, we need only one (temporary) array of 32-bit values and two (corr16, ener16)
       arrays for (normalized) 16-bit values */
    VARDECL(spx_word16_t *corr16);
    VARDECL(spx_word16_t *ener16);
    spx_word32_t *energy;
    int cshift=0, eshift=0;
    int scaledown = 0;
    ALLOC(corr16, end-start+1, spx_word16_t);
    ALLOC(ener16, end-start+1, spx_word16_t);
    ALLOC(corr, end-start+1, spx_word32_t);
    energy = corr;
 #else
    /* In floating-point, we need to float arrays and no normalized copies */
    VARDECL(spx_word32_t *energy);
    spx_word16_t *corr16;
    spx_word16_t *ener16;
    ALLOC(energy, end-start+2, spx_word32_t);
    ALLOC(corr, end-start+1, spx_word32_t);
    corr16 = corr;
    ener16 = energy;
 #endif
    ALLOC(best_score, N, spx_word32_t);
    ALLOC(best_ener, N, spx_word32_t);
    for (i=0;i<N;i++)
    {
         best_score[i]=-1;
         best_ener[i]=0;
         pitch[i]=start;
    }
 #ifdef FIXED_POINT
    for (i=-end;i<len;i++)
    {
       if (ABS16(sw[i])>16383)
       {
          scaledown=1;
          break;
       }
    }
    /* If the weighted input is close to saturation, then we scale it down */
    if (scaledown)
    {
       for (i=-end;i<len;i++)
       {
          sw[i]=SHR16(sw[i],1);
       }
    }
 #endif
    energy[0]=inner_prod(sw-start, sw-start, len);
    e0=inner_prod(sw, sw, len);
    for (i=start;i<end;i++)
    {
       /* Update energy for next pitch*/
       energy[i-start+1] = SUB32(ADD32(energy[i-start],SHR32(MULT16_16(sw[-i-1],sw[-i-1]),6)), SHR32(MULT16_16(sw[-i+len-1],sw[-i+len-1]),6));
       if (energy[i-start+1] < 0)
          energy[i-start+1] = 0;
    }
 #ifdef FIXED_POINT
    eshift = normalize16(energy, ener16, 32766, end-start+1);
 #endif
    /* In fixed-point, this actually overrites the energy array (aliased to corr) */
    pitch_xcorr(sw, sw-end, corr, len, end-start+1, stack);
 #ifdef FIXED_POINT
    /* Normalize to 180 so we can square it and it still fits in 16 bits */
    cshift = normalize16(corr, corr16, 180, end-start+1);
    /* If we scaled weighted input down, we need to scale it up again (OK, so we've just lost the LSB, who cares?) */
    if (scaledown)
    {
       for (i=-end;i<len;i++)
       {
          sw[i]=SHL16(sw[i],1);
       }
    }
 #endif
    /* Search for the best pitch prediction gain */
    for (i=start;i<=end;i++)
    {
       spx_word16_t tmp = MULT16_16_16(corr16[i-start],corr16[i-start]);
       /* Instead of dividing the tmp by the energy, we multiply on the other side */
       if (MULT16_16(tmp,best_ener[N-1])>MULT16_16(best_score[N-1],ADD16(1,ener16[i-start])))
       {
          /* We can safely put it last and then check */
          best_score[N-1]=tmp;
          best_ener[N-1]=ener16[i-start]+1;
          pitch[N-1]=i;
          /* Check if it comes in front of others */
          for (j=0;j<N-1;j++)
          {
             if (MULT16_16(tmp,best_ener[j])>MULT16_16(best_score[j],ADD16(1,ener16[i-start])))
             {
                for (k=N-1;k>j;k--)
                {
                   best_score[k]=best_score[k-1];
                   best_ener[k]=best_ener[k-1];
                   pitch[k]=pitch[k-1];
                }
                best_score[j]=tmp;
                best_ener[j]=ener16[i-start]+1;
                pitch[j]=i;
                break;
             }
          }
       }
    }
    /* Compute open-loop gain if necessary */
    if (gain)
    {
       for (j=0;j<N;j++)
       {
          spx_word16_t g;
          i=pitch[j];
          g = DIV32(SHL32(EXTEND32(corr16[i-start]),cshift), 10+SHR32(MULT16_16(spx_sqrt(e0),spx_sqrt(SHL32(EXTEND32(ener16[i-start]),eshift))),6));
          /* FIXME: g = max(g,corr/energy) */
          if (g<0)
             g = 0;
          gain[j]=g;
       }
    }
 }
References ABS16, ADD16, ADD32, ALLOC, DIV32, EXTEND32, inner_prod(), MULT16_16, MULT16_16_16, normalize16(), pitch_xcorr(), SHL16, SHL32, SHR16, SHR32, spx_sqrt, SUB32, and VARDECL.
Referenced by multicomb(), nb_encode(), and pitch_search_3tap().
pitch_search_3tap()
int pitch_search_3tap (spx_word16_t target[], spx_word16_t * sw, spx_coef_t ak[], spx_coef_t awk1[], spx_coef_t awk2[], spx_sig_t exc[], const void * par, int start, int end, spx_word16_t pitch_coef, int p, int nsf, SpeexBits * bits, char * stack, spx_word16_t * exc2, spx_word16_t * r, int complexity, int cdbk_offset, int plc_tuning, spx_word32_t * cumul_gain)
Finds the best quantized 3-tap pitch predictor by analysis by synthesis.
Definition at line 528 of file ltp.c.
 {
    int i;
    int cdbk_index, pitch=0, best_gain_index=0;
    VARDECL(spx_sig_t *best_exc);
    VARDECL(spx_word16_t *new_target);
    VARDECL(spx_word16_t *best_target);
    int best_pitch=0;
    spx_word32_t err, best_err=-1;
    int N;
    const ltp_params *params;
    const signed char *gain_cdbk;
    int   gain_cdbk_size;
    int scaledown=0;
    VARDECL(int *nbest);
    params = (const ltp_params*) par;
    gain_cdbk_size = 1<<params->gain_bits;
    gain_cdbk = params->gain_cdbk + 4*gain_cdbk_size*cdbk_offset;
    N=complexity;
    if (N>10)
       N=10;
    if (N<1)
       N=1;
    ALLOC(nbest, N, int);
    params = (const ltp_params*) par;
    if (end<start)
    {
       speex_bits_pack(bits, 0, params->pitch_bits);
       speex_bits_pack(bits, 0, params->gain_bits);
       SPEEX_MEMSET(exc, 0, nsf);
       return start;
    }
 #ifdef FIXED_POINT
    /* Check if we need to scale everything down in the pitch search to avoid overflows */
    for (i=0;i<nsf;i++)
    {
       if (ABS16(target[i])>16383)
       {
          scaledown=1;
          break;
       }
    }
    for (i=-end;i<nsf;i++)
    {
       if (ABS16(exc2[i])>16383)
       {
          scaledown=1;
          break;
       }
    }
 #endif
    if (N>end-start+1)
       N=end-start+1;
    if (end != start)
       open_loop_nbest_pitch(sw, start, end, nsf, nbest, NULL, N, stack);
    else
       nbest[0] = start;
    ALLOC(best_exc, nsf, spx_sig_t);
    ALLOC(new_target, nsf, spx_word16_t);
    ALLOC(best_target, nsf, spx_word16_t);
    for (i=0;i<N;i++)
    {
       pitch=nbest[i];
       SPEEX_MEMSET(exc, 0, nsf);
       err=pitch_gain_search_3tap(target, ak, awk1, awk2, exc, gain_cdbk, gain_cdbk_size, pitch, p, nsf,
                                  bits, stack, exc2, r, new_target, &cdbk_index, plc_tuning, *cumul_gain, scaledown);
       if (err<best_err || best_err<0)
       {
          SPEEX_COPY(best_exc, exc, nsf);
          SPEEX_COPY(best_target, new_target, nsf);
          best_err=err;
          best_pitch=pitch;
          best_gain_index=cdbk_index;
       }
    }
    /*printf ("pitch: %d %d\n", best_pitch, best_gain_index);*/
    speex_bits_pack(bits, best_pitch-start, params->pitch_bits);
    speex_bits_pack(bits, best_gain_index, params->gain_bits);
 #ifdef FIXED_POINT
    *cumul_gain = MULT16_32_Q13(SHL16(params->gain_cdbk[4*best_gain_index+3],8), MAX32(1024,*cumul_gain));
 #else
    *cumul_gain = 0.03125*MAX32(1024,*cumul_gain)*params->gain_cdbk[4*best_gain_index+3];
 #endif
    /*printf ("%f\n", cumul_gain);*/
    /*printf ("encode pitch: %d %d\n", best_pitch, best_gain_index);*/
    SPEEX_COPY(exc, best_exc, nsf);
    SPEEX_COPY(target, best_target, nsf);
 #ifdef FIXED_POINT
    /* Scale target back up if needed */
    if (scaledown)
    {
       for (i=0;i<nsf;i++)
          target[i]=SHL16(target[i],1);
    }
 #endif
    return pitch;
 }
References ABS16, ALLOC, bits(), MAX32, MULT16_32_Q13, NULL, open_loop_nbest_pitch(), pitch_gain_search_3tap(), SHL16, speex_bits_pack(), SPEEX_COPY, SPEEX_MEMSET, and VARDECL.
pitch_unquant_3tap()
void pitch_unquant_3tap (spx_word16_t exc[], spx_word32_t exc_out[], int start, int end, spx_word16_t pitch_coef, const void * par, int nsf, int * pitch_val, spx_word16_t * gain_val, SpeexBits * bits, char * stack, int lost, int subframe_offset, spx_word16_t last_pitch_gain, int cdbk_offset)
Definition at line 655 of file ltp.c.
 {
    int i;
    int pitch;
    int gain_index;
    spx_word16_t gain[3];
    const signed char *gain_cdbk;
    int gain_cdbk_size;
    const ltp_params *params;
    params = (const ltp_params*) par;
    gain_cdbk_size = 1<<params->gain_bits;
    gain_cdbk = params->gain_cdbk + 4*gain_cdbk_size*cdbk_offset;
    pitch = speex_bits_unpack_unsigned(bits, params->pitch_bits);
    pitch += start;
    gain_index = speex_bits_unpack_unsigned(bits, params->gain_bits);
    /*printf ("decode pitch: %d %d\n", pitch, gain_index);*/
 #ifdef FIXED_POINT
    gain[0] = ADD16(32,(spx_word16_t)gain_cdbk[gain_index*4]);
    gain[1] = ADD16(32,(spx_word16_t)gain_cdbk[gain_index*4+1]);
    gain[2] = ADD16(32,(spx_word16_t)gain_cdbk[gain_index*4+2]);
 #else
    gain[0] = 0.015625*gain_cdbk[gain_index*4]+.5;
    gain[1] = 0.015625*gain_cdbk[gain_index*4+1]+.5;
    gain[2] = 0.015625*gain_cdbk[gain_index*4+2]+.5;
 #endif
    if (count_lost && pitch > subframe_offset)
    {
       spx_word16_t gain_sum;
       if (1) {
 #ifdef FIXED_POINT
          spx_word16_t tmp = count_lost < 4 ? last_pitch_gain : SHR16(last_pitch_gain,1);
          if (tmp>62)
             tmp=62;
 #else
          spx_word16_t tmp = count_lost < 4 ? last_pitch_gain : 0.5 * last_pitch_gain;
          if (tmp>.95)
             tmp=.95;
 #endif
          gain_sum = gain_3tap_to_1tap(gain);
          if (gain_sum > tmp)
          {
             spx_word16_t fact = DIV32_16(SHL32(EXTEND32(tmp),14),gain_sum);
             for (i=0;i<3;i++)
                gain[i]=MULT16_16_Q14(fact,gain[i]);
          }
       }
    }
    *pitch_val = pitch;
    gain_val[0]=gain[0];
    gain_val[1]=gain[1];
    gain_val[2]=gain[2];
    gain[0] = SHL16(gain[0],7);
    gain[1] = SHL16(gain[1],7);
    gain[2] = SHL16(gain[2],7);
    SPEEX_MEMSET(exc_out, 0, nsf);
    for (i=0;i<3;i++)
    {
       int j;
       int tmp1, tmp3;
       int pp=pitch+1-i;
       tmp1=nsf;
       if (tmp1>pp)
          tmp1=pp;
       for (j=0;j<tmp1;j++)
          exc_out[j]=MAC16_16(exc_out[j],gain[2-i],exc[j-pp]);
       tmp3=nsf;
       if (tmp3>pp+pitch)
          tmp3=pp+pitch;
       for (j=tmp1;j<tmp3;j++)
          exc_out[j]=MAC16_16(exc_out[j],gain[2-i],exc[j-pp-pitch]);
    }
    /*for (i=0;i<nsf;i++)
    exc[i]=PSHR32(exc32[i],13);*/
 }
References ADD16, bits(), DIV32_16, EXTEND32, gain_3tap_to_1tap, MAC16_16, MULT16_16_Q14, SHL16, SHL32, SHR16, speex_bits_unpack_unsigned(), and SPEEX_MEMSET.
pitch_xcorr()
void pitch_xcorr (const spx_word16_t * _x, const spx_word16_t * _y, spx_word32_t * corr, int len, int nb_pitch, char * stack)
Definition at line 142 of file ltp.c.
 {
    int i;
    for (i=0;i<nb_pitch;i++)
    {
       /* Compute correlation*/
       corr[nb_pitch-1-i]=inner_prod(_x, _y+i, len);
    }
 }
References ALLOC, inner_prod(), VARDECL, xx, and yy.
Referenced by open_loop_nbest_pitch().