ZEQ2-Lite: AdjustableArrowCap Class Reference
AdjustableArrowCap Class Reference
#include <gdipluslinecaps.h>
Public Member Functions
AdjustableArrowCap (REAL height, REAL width, BOOL isFilled)
virtual ~AdjustableArrowCap ()
virtual AdjustableArrowCap * Clone () const
LineCap GetBaseCap () const
REAL GetBaseInset () const
REAL GetHeight () const
Status GetLastStatus () const
REAL GetMiddleInset () const
Status GetStrokeCaps (LineCap *startCap, LineCap *endCap) const
LineJoin GetStrokeJoin () const
REAL GetWidth () const
REAL GetWidthScale () const
BOOL IsFilled () const
Status SetBaseCap (LineCap baseCap)
Status SetBaseInset (REAL inset)
Status SetFillState (BOOL isFilled)
Status SetHeight (REAL height)
Status SetMiddleInset (REAL middleInset)
Status SetStrokeCap (LineCap strokeCap)
Status SetStrokeCaps (LineCap startCap, LineCap endCap)
Status SetStrokeJoin (LineJoin lineJoin)
Status SetWidth (REAL width)
Status SetWidthScale (REAL widthScale)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
AdjustableArrowCap (const AdjustableArrowCap &)
AdjustableArrowCap (GpCustomLineCap *customLineCap, Status status)
AdjustableArrowCap & operator= (const AdjustableArrowCap &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpCustomLineCap * nativeCustomLineCap
Detailed Description
Definition at line 33 of file gdipluslinecaps.h.
Constructor & Destructor Documentation
AdjustableArrowCap() [1/3]
AdjustableArrowCap::AdjustableArrowCap (REAL height, REAL width, BOOL isFilled) inline
Definition at line 36 of file gdipluslinecaps.h.
                                                               :
         CustomLineCap(NULL, Ok)
     {
         GpAdjustableArrowCap *nativeAdjustableArrowCap = NULL;
         lastStatus = DllExports::GdipCreateAdjustableArrowCap(
                 height, width, isFilled,
                 &nativeAdjustableArrowCap);
         nativeCustomLineCap = nativeAdjustableArrowCap;
     }
References GdipCreateAdjustableArrowCap(), CustomLineCap::lastStatus, CustomLineCap::nativeCustomLineCap, and NULL.
~AdjustableArrowCap()
virtual AdjustableArrowCap::~AdjustableArrowCap () inline virtual
Definition at line 45 of file gdipluslinecaps.h.
     {
     }
AdjustableArrowCap() [2/3]
AdjustableArrowCap::AdjustableArrowCap (GpCustomLineCap * customLineCap, Status status) inline private
Definition at line 125 of file gdipluslinecaps.h.
                                                                      :
         CustomLineCap(customLineCap, status) {}
AdjustableArrowCap() [3/3]
AdjustableArrowCap::AdjustableArrowCap (const AdjustableArrowCap &) private
Member Function Documentation
Clone()
virtual AdjustableArrowCap* AdjustableArrowCap::Clone () const inline virtual
Reimplemented from CustomLineCap.
Definition at line 48 of file gdipluslinecaps.h.
     {
         GpCustomLineCap *cloneCustomLineCap = NULL;
         Status status = updateStatus(DllExports::GdipCloneCustomLineCap(
                 nativeCustomLineCap, &cloneCustomLineCap));
         if (status == Ok) {
             AdjustableArrowCap *result = new AdjustableArrowCap(
                     cloneCustomLineCap, lastStatus);
             if (!result) {
                 DllExports::GdipDeleteCustomLineCap(
                         cloneCustomLineCap);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References CustomLineCap::AdjustableArrowCap, GdipCloneCustomLineCap(), GdipDeleteCustomLineCap(), CustomLineCap::lastStatus, CustomLineCap::nativeCustomLineCap, NULL, Ok, OutOfMemory, and CustomLineCap::updateStatus().
GetBaseCap()
__inline__ LineCap CustomLineCap::GetBaseCap () const inherited
Definition at line 666 of file gdiplusimpl.h.
 {
     LineCap result = LineCapFlat;
     updateStatus(DllExports::GdipGetCustomLineCapBaseCap(
             nativeCustomLineCap, &result));
     return result;
 }
References GdipGetCustomLineCapBaseCap(), LineCapFlat, CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
GetBaseInset()
__inline__ REAL CustomLineCap::GetBaseInset () const inherited
Definition at line 674 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetCustomLineCapBaseInset(
             nativeCustomLineCap, &result));
     return result;
 }
References GdipGetCustomLineCapBaseInset(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
GetHeight()
REAL AdjustableArrowCap::GetHeight () const inline
Definition at line 67 of file gdipluslinecaps.h.
     {
         REAL result = 0.0f;
         updateStatus(DllExports::GdipGetAdjustableArrowCapHeight(
                 (GpAdjustableArrowCap*) nativeCustomLineCap,
                 &result));
         return result;
     }
References GdipGetAdjustableArrowCapHeight(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
GetLastStatus()
Status CustomLineCap::GetLastStatus () const inline inherited
Definition at line 305 of file gdiplusheaders.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References CustomLineCap::lastStatus, and Ok.
GetMiddleInset()
REAL AdjustableArrowCap::GetMiddleInset () const inline
Definition at line 75 of file gdipluslinecaps.h.
     {
         REAL result = 0.0f;
         updateStatus(DllExports::GdipGetAdjustableArrowCapMiddleInset(
                 (GpAdjustableArrowCap*) nativeCustomLineCap,
                 &result));
         return result;
     }
References GdipGetAdjustableArrowCapMiddleInset(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
GetStrokeCaps()
__inline__ Status CustomLineCap::GetStrokeCaps (LineCap * startCap, LineCap * endCap) const inherited
Definition at line 682 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetCustomLineCapStrokeCaps(
             nativeCustomLineCap, startCap, endCap));
 }
References GdipGetCustomLineCapStrokeCaps(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
GetStrokeJoin()
__inline__ LineJoin CustomLineCap::GetStrokeJoin () const inherited
Definition at line 689 of file gdiplusimpl.h.
 {
     LineJoin result = LineJoinMiter;
     updateStatus(DllExports::GdipGetCustomLineCapStrokeJoin(
             nativeCustomLineCap, &result));
     return result;
 }
References GdipGetCustomLineCapStrokeJoin(), LineJoinMiter, CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
GetWidth()
REAL AdjustableArrowCap::GetWidth () const inline
Definition at line 83 of file gdipluslinecaps.h.
     {
         REAL result = 0.0f;
         updateStatus(DllExports::GdipGetAdjustableArrowCapWidth(
                 (GpAdjustableArrowCap*) nativeCustomLineCap,
                 &result));
         return result;
     }
References GdipGetAdjustableArrowCapWidth(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
GetWidthScale()
__inline__ REAL CustomLineCap::GetWidthScale () const inherited
Definition at line 697 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetCustomLineCapWidthScale(
             nativeCustomLineCap, &result));
     return result;
 }
References GdipGetCustomLineCapWidthScale(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
IsFilled()
BOOL AdjustableArrowCap::IsFilled () const inline
Definition at line 91 of file gdipluslinecaps.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipGetAdjustableArrowCapFillState(
                 (GpAdjustableArrowCap*) nativeCustomLineCap,
                 &result));
         return result;
     }
References FALSE, GdipGetAdjustableArrowCapFillState(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
AdjustableArrowCap& AdjustableArrowCap::operator= (const AdjustableArrowCap &) private
SetBaseCap()
__inline__ Status CustomLineCap::SetBaseCap (LineCap baseCap) inherited
Definition at line 705 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapBaseCap(
             nativeCustomLineCap, baseCap));
 }
References GdipSetCustomLineCapBaseCap(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetBaseInset()
__inline__ Status CustomLineCap::SetBaseInset (REAL inset) inherited
Definition at line 711 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapBaseInset(
             nativeCustomLineCap, inset));
 }
References GdipSetCustomLineCapBaseInset(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetFillState()
Status AdjustableArrowCap::SetFillState (BOOL isFilled) inline
Definition at line 99 of file gdipluslinecaps.h.
     {
         return updateStatus(DllExports::GdipSetAdjustableArrowCapFillState(
                 (GpAdjustableArrowCap*) nativeCustomLineCap,
                 isFilled));
     }
References GdipSetAdjustableArrowCapFillState(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetHeight()
Status AdjustableArrowCap::SetHeight (REAL height) inline
Definition at line 105 of file gdipluslinecaps.h.
     {
         return updateStatus(DllExports::GdipSetAdjustableArrowCapHeight(
                 (GpAdjustableArrowCap*) nativeCustomLineCap,
                 height));
     }
References GdipSetAdjustableArrowCapHeight(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetMiddleInset()
Status AdjustableArrowCap::SetMiddleInset (REAL middleInset) inline
Definition at line 111 of file gdipluslinecaps.h.
     {
         return updateStatus(DllExports::GdipSetAdjustableArrowCapMiddleInset(
                 (GpAdjustableArrowCap*) nativeCustomLineCap,
                 middleInset));
     }
References GdipSetAdjustableArrowCapMiddleInset(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetStrokeCap()
__inline__ Status CustomLineCap::SetStrokeCap (LineCap strokeCap) inherited
Definition at line 717 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapStrokeCaps(
             nativeCustomLineCap, strokeCap, strokeCap));
 }
References GdipSetCustomLineCapStrokeCaps(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetStrokeCaps()
__inline__ Status CustomLineCap::SetStrokeCaps (LineCap startCap, LineCap endCap) inherited
Definition at line 723 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapStrokeCaps(
             nativeCustomLineCap, startCap, endCap));
 }
References GdipSetCustomLineCapStrokeCaps(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetStrokeJoin()
__inline__ Status CustomLineCap::SetStrokeJoin (LineJoin lineJoin) inherited
Definition at line 729 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapStrokeJoin(
             nativeCustomLineCap, lineJoin));
 }
References GdipSetCustomLineCapStrokeJoin(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetWidth()
Status AdjustableArrowCap::SetWidth (REAL width) inline
Definition at line 117 of file gdipluslinecaps.h.
     {
         return updateStatus(DllExports::GdipSetAdjustableArrowCapWidth(
                 (GpAdjustableArrowCap*) nativeCustomLineCap,
                 width));
     }
References GdipSetAdjustableArrowCapWidth(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
SetWidthScale()
__inline__ Status CustomLineCap::SetWidthScale (REAL widthScale) inherited
Definition at line 735 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetCustomLineCapWidthScale(
             nativeCustomLineCap, widthScale));
 }
References GdipSetCustomLineCapWidthScale(), CustomLineCap::nativeCustomLineCap, and CustomLineCap::updateStatus().
updateStatus()
Status CustomLineCap::updateStatus (Status newStatus) const inline private inherited
Definition at line 318 of file gdiplusheaders.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References CustomLineCap::lastStatus, and Ok.
Referenced by Clone(), CustomLineCap::Clone(), CustomLineCap::GetBaseCap(), CustomLineCap::GetBaseInset(), GetHeight(), GetMiddleInset(), CustomLineCap::GetStrokeCaps(), CustomLineCap::GetStrokeJoin(), GetWidth(), CustomLineCap::GetWidthScale(), IsFilled(), CustomLineCap::SetBaseCap(), CustomLineCap::SetBaseInset(), SetFillState(), SetHeight(), SetMiddleInset(), CustomLineCap::SetStrokeCap(), CustomLineCap::SetStrokeCaps(), CustomLineCap::SetStrokeJoin(), SetWidth(), and CustomLineCap::SetWidthScale().
Field Documentation
lastStatus
Status CustomLineCap::lastStatus mutable private inherited
Definition at line 325 of file gdiplusheaders.h.
Referenced by AdjustableArrowCap(), Clone(), CustomLineCap::Clone(), CustomLineCap::CustomLineCap(), CustomLineCap::GetLastStatus(), and CustomLineCap::updateStatus().
nativeCustomLineCap
GpCustomLineCap* CustomLineCap::nativeCustomLineCap private inherited
Definition at line 324 of file gdiplusheaders.h.
Referenced by AdjustableArrowCap(), Clone(), CustomLineCap::Clone(), CustomLineCap::CustomLineCap(), CustomLineCap::GetBaseCap(), CustomLineCap::GetBaseInset(), Pen::GetCustomEndCap(), Pen::GetCustomStartCap(), GetHeight(), GetMiddleInset(), CustomLineCap::GetStrokeCaps(), CustomLineCap::GetStrokeJoin(), GetWidth(), CustomLineCap::GetWidthScale(), IsFilled(), CustomLineCap::SetBaseCap(), CustomLineCap::SetBaseInset(), Pen::SetCustomEndCap(), Pen::SetCustomStartCap(), SetFillState(), SetHeight(), SetMiddleInset(), CustomLineCap::SetStrokeCap(), CustomLineCap::SetStrokeCaps(), CustomLineCap::SetStrokeJoin(), SetWidth(), CustomLineCap::SetWidthScale(), and CustomLineCap::~CustomLineCap().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdipluslinecaps.h