ZEQ2-Lite: Tools/MinGW/include/vfw.h File Reference
vfw.h File Reference
#include <windows.h>
#include <mmsystem.h>
#include <ole2.h>
#include <pshpack8.h>
#include <poppack.h>
Data Structures
struct _AVICOMPRESSOPTIONS
struct _AVIFILEINFOA
struct _AVIFILEINFOW
struct _AVIINDEXENTRY
struct _AVIPALCHANGE
struct _AVISTREAMINFOA
struct _AVISTREAMINFOW
struct _CAPDRIVERCAPS
struct _CAPINFOCHUNK
struct _CAPSTATUS
struct _CAPTUREPARMS
struct _MainAVIHeader
struct AVIStreamHeader
struct COMPVARS
struct ICCOMPRESS
struct ICCOMPRESSFRAMES
struct ICDECOMPRESS
struct ICDECOMPRESSEX
struct ICDRAW
struct ICDRAWBEGIN
struct ICDRAWSUGGEST
struct ICINFO
struct ICOPEN
struct ICPALETTE
struct ICSETSTATUSPROC
struct videohdr_tag
Macros
#define __capSendMessage(hwnd, m, w, l) (IsWindow(hwnd)?SendMessage(hwnd,m,w,l):0)
#define AVI_HEADERSIZE 2048
#define AVIBuildFilter AVIBuildFilterA
#define AVICOMPRESSF_DATARATE 0x02
#define AVICOMPRESSF_INTERLEAVE 0x01
#define AVICOMPRESSF_KEYFRAMES 0x04
#define AVICOMPRESSF_VALID 0x08
#define AVIERR_BADFLAGS MAKE_AVIERR(105)
#define AVIERR_BADFORMAT MAKE_AVIERR(102)
#define AVIERR_BADHANDLE MAKE_AVIERR(108)
#define AVIERR_BADPARAM MAKE_AVIERR(106)
#define AVIERR_BADSIZE MAKE_AVIERR(107)
#define AVIERR_BUFFERTOOSMALL MAKE_AVIERR(116)
#define AVIERR_CANTCOMPRESS MAKE_AVIERR(117)
#define AVIERR_COMPRESSOR MAKE_AVIERR(112)
#define AVIERR_ERROR MAKE_AVIERR(199)
#define AVIERR_FILEOPEN MAKE_AVIERR(111)
#define AVIERR_FILEREAD MAKE_AVIERR(109)
#define AVIERR_FILEWRITE MAKE_AVIERR(110)
#define AVIERR_INTERNAL MAKE_AVIERR(104)
#define AVIERR_MEMORY MAKE_AVIERR(103)
#define AVIERR_NOCOMPRESSOR MAKE_AVIERR(113)
#define AVIERR_NODATA MAKE_AVIERR(115)
#define AVIERR_OK 0
#define AVIERR_READONLY MAKE_AVIERR(114)
#define AVIERR_UNSUPPORTED MAKE_AVIERR(101)
#define AVIERR_USERABORT MAKE_AVIERR(198)
#define AVIF_COPYRIGHTED 0x20000
#define AVIF_HASINDEX 0x10
#define AVIF_ISINTERLEAVED 0x100
#define AVIF_MUSTUSEINDEX 0x20
#define AVIF_TRUSTCKTYPE 0x800
#define AVIF_WASCAPTUREFILE 0x10000
#define AVIFILECAPS_ALLKEYFRAMES 0x10
#define AVIFILECAPS_CANREAD 0x01
#define AVIFILECAPS_CANWRITE 0x02
#define AVIFILECAPS_NOCOMPRESSION 0x20
#define AVIFileClose(pavi) AVIFileRelease(pavi)
#define AVIFileCreateStream AVIFileCreateStreamA
#define AVIFILEINFO AVIFILEINFOA
#define AVIFileInfo AVIFileInfoA
#define AVIFILEINFO_COPYRIGHTED 0x20000
#define AVIFILEINFO_HASINDEX 0x10
#define AVIFILEINFO_ISINTERLEAVED 0x100
#define AVIFILEINFO_MUSTUSEINDEX 0x20
#define AVIFILEINFO_TRUSTCKTYPE 0x800
#define AVIFILEINFO_WASCAPTUREFILE 0x10000
#define AVIFileOpen AVIFileOpenA
#define AVIGETFRAMEF_BESTDISPLAYFMT 1
#define AVIIF_COMPUSE 0xfff0000
#define AVIIF_KEYFRAME 0x10
#define AVIIF_KEYFRAME 0x10
#define AVIIF_LIST 0x01
#define AVIIF_NOTIME 0x100
#define AVIIF_TWOCC 0x02
#define AVISaveV AVISaveVA
#define AVISF_DISABLED 0x01
#define AVISF_VIDEO_PALCHANGES 0x10000
#define AVIStreamClose(pavi) AVIStreamRelease(pavi);
#define AVIStreamEnd(pavi) (AVIStreamStart(pavi)+AVIStreamLength(pavi))
#define AVIStreamEndTime(pavi) AVIStreamSampleToTime(pavi,AVIStreamEnd(pavi))
#define AVIStreamFormatSize(pavi, lPos, plSize) AVIStreamReadFormat(pavi,lPos,NULL,plSize)
#define AVISTREAMINFO AVISTREAMINFOA
#define AVIStreamInfo AVIStreamInfoA
#define AVISTREAMINFO_DISABLED 0x01
#define AVISTREAMINFO_FORMATCHANGES 0x10000
#define AVIStreamIsKeyFrame(pavi, pos) (AVIStreamNearestKeyFrame(pavi,pos) == pos)
#define AVIStreamLengthTime(pavi) AVIStreamSampleToTime(pavi,AVIStreamLength(pavi))
#define AVIStreamNearestKeyFrame(pavi, pos) AVIStreamFindSample(pavi,pos,FIND_PREV|FIND_KEY)
#define AVIStreamNearestSample(pavi, pos) AVIStreamFindSample(pavi,pos,FIND_PREV|FIND_ANY)
#define AVIStreamNextSample(pavi, pos) AVIStreamFindSample(pavi,pos+1,FIND_NEXT|FIND_ANY)
#define AVIStreamOpenFromFile AVIStreamOpenFromFileA
#define AVIStreamPrevSample(pavi, pos) AVIStreamFindSample(pavi,pos-1,FIND_PREV|FIND_ANY)
#define AVIStreamSampleSize(pavi, pos, psize) AVIStreamRead(pavi,pos,1,NULL,0,psize,NULL)
#define AVIStreamSampleToSample(pavi1, pavi2, samp2) AVIStreamTimeToSample(pavi1,AVIStreamSampleToTime(pavi2,samp2))
#define AVIStreamStartTime(pavi) AVIStreamSampleToTime(pavi,AVIStreamStart(pavi))
#define aviTWOCC(ch0, ch1) ((WORD)(BYTE)(ch0)|((WORD)(BYTE)(ch1)<<8))
#define AVStreamNextKeyFrame(pavi, pos) AVIStreamFindSample(pavi,pos+1,FIND_NEXT|FIND_KEY)
#define AVStreamPrevKeyFrame(pavi, pos) AVIStreamFindSample(pavi,pos-1,FIND_NEXT|FIND_KEY)
#define capCaptureAbort(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_ABORT,0,0))
#define capCaptureGetSetup(hwnd, s, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_GET_SEQUENCE_SETUP,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPCAPTUREPARMS)(s)))
#define capCaptureSequence(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SEQUENCE,0,0))
#define capCaptureSequenceNoFile(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SEQUENCE_NOFILE,0,0))
#define capCaptureSetSetup(hwnd, s, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_SEQUENCE_SETUP,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPCAPTUREPARMS)(s)))
#define capCaptureSingleFrame(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SINGLE_FRAME,0,0))
#define capCaptureSingleFrameClose(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SINGLE_FRAME_CLOSE,0,0))
#define capCaptureSingleFrameOpen(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SINGLE_FRAME_OPEN,0,0))
#define capCaptureStop(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_STOP,0,0))
#define capCreateCaptureWindow capCreateCaptureWindowA
#define capDlgVideoCompression(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DLG_VIDEOCOMPRESSION,0,0))
#define capDlgVideoDisplay(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DLG_VIDEODISPLAY,0,0))
#define capDlgVideoFormat(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DLG_VIDEOFORMAT,0,0))
#define capDlgVideoSource(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DLG_VIDEOSOURCE,0,0))
#define capDriverConnect(hwnd, i) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_CONNECT,(WPARAM)(i),0))
#define capDriverDisconnect(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_DISCONNECT,0,0))
#define capDriverGetCaps(hwnd, psCaps, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_GET_CAPS,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPCAPDRIVERCAPS)(psCaps)))
#define capDriverGetName(hwnd, szName, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_GET_NAME,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capDriverGetVersion(hwnd, szVer, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_GET_VERSION,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPTSTR)(szVer)))
#define capEditCopy(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_EDIT_COPY,0,0))
#define capFileAlloc(hwnd, dwSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_ALLOCATE,0,(LPARAM)(DWORD)(dwSize)))
#define capFileGetCaptureFile(hwnd, szName, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_GET_CAPTURE_FILE,(WPARAM)(wSize), (LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capFileSaveAs(hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_SAVEAS,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capFileSaveDIB(hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_SAVEDIB,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capFileSetCaptureFile(hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_SET_CAPTURE_FILE,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capFileSetInfoChunk(hwnd, lpInfoChunk) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_SET_INFOCHUNK,0,(LPARAM)(LPCAPINFOCHUNK)(lpInfoChunk)))
#define capGetAudioFormat(hwnd, psAudioFormat, wSize) ((DWORD)__capSendMessage(hwnd,WM_CAP_GET_AUDIOFORMAT,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPWAVEFORMATEX)(psAudioFormat)))
#define capGetAudioFormatSize(hwnd) ((DWORD)__capSendMessage(hwnd,WM_CAP_GET_AUDIOFORMAT,0,0))
#define capGetDriverDescription capGetDriverDescriptionA
#define capGetMCIDeviceName(hwnd, szName, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_GET_MCI_DEVICE,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capGetStatus(hwnd, s, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_GET_STATUS,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPCAPSTATUS)(s)))
#define capGetUserData(hwnd) ((LONG) __capSendMessage(hwnd,WM_CAP_GET_USER_DATA,0,0))
#define capGetVideoFormat(hwnd, psVideoFormat, wSize) ((DWORD)__capSendMessage(hwnd,WM_CAP_GET_VIDEOFORMAT,(WPARAM)(wSize),(LPARAM)(LPVOID)(psVideoFormat)))
#define capGetVideoFormatSize(hwnd) ((DWORD)__capSendMessage(hwnd,WM_CAP_GET_VIDEOFORMAT,0,0))
#define capGrabFrame(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_GRAB_FRAME,0,0))
#define capGrabFrameNoStop(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_GRAB_FRAME_NOSTOP,0,0))
#define capOverlay(hwnd, f) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_OVERLAY,(WPARAM)(BOOL)(f),0))
#define capPaletteAuto(hwnd, iFrames, iColors) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_AUTOCREATE,(WPARAM)(iFrames),(LPARAM)(DWORD)(iColors)))
#define capPaletteManual(hwnd, fGrab, iColors) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_MANUALCREATE,(WPARAM)(fGrab),(LPARAM)(DWORD)(iColors)))
#define capPaletteOpen(hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_OPEN,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capPalettePaste(hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_PASTE,0,0))
#define capPaletteSave(hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_SAVE,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capPreview(hwnd, f) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_PREVIEW,(WPARAM)(BOOL)(f),0))
#define capPreviewRate(hwnd, wMS) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_PREVIEWRATE,(WPARAM)(wMS),0))
#define capPreviewScale(hwnd, f) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_SCALE,(WPARAM)(BOOL)f,0))
#define capSetAudioFormat(hwnd, psAudioFormat, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_AUDIOFORMAT,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPWAVEFORMATEX)(psAudioFormat)))
#define capSetCallbackOnCapControl(hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_CAPCONTROL,0,(LPARAM)(LPVOID)(fpProc)))
#define capSetCallbackOnError(hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_ERROR,0,(LPARAM)(LPVOID)(fpProc)))
#define capSetCallbackOnFrame(hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_FRAME,0,(LPARAM)(LPVOID)(fpProc)))
#define capSetCallbackOnStatus(hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_STATUS,0,(LPARAM)(LPVOID)(fpProc)))
#define capSetCallbackOnVideoStream(hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_VIDEOSTREAM,0,(LPARAM)(LPVOID)(fpProc)))
#define capSetCallbackOnWaveStream(hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_WAVESTREAM,0,(LPARAM)(LPVOID)(fpProc)))
#define capSetCallbackOnYield(hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_YIELD,0,(LPARAM)(LPVOID)(fpProc)))
#define capSetMCIDeviceName(hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_MCI_DEVICE,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
#define capSetScrollPos(hwnd, lpP) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_SCROLL,0,(LPARAM)(LPPOINT)(lpP)))
#define capSetUserData(hwnd, lUser) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_USER_DATA,0,(LPARAM)lUser))
#define capSetVideoFormat(hwnd, psVideoFormat, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_VIDEOFORMAT,(WPARAM)(wSize),(LPARAM)(LPVOID)(psVideoFormat)))
#define ckidAVIMAINHDR mmioFOURCC('a','v','i','h')
#define ckidAVINEWINDEX mmioFOURCC('i', 'd', 'x', '1')
#define ckidAVIPADDING mmioFOURCC('J','U','N','K')
#define ckidSTREAMFORMAT mmioFOURCC('s','t','r','f')
#define ckidSTREAMHANDLERDATA mmioFOURCC('s','t','r','d')
#define ckidSTREAMHEADER mmioFOURCC('s','t','r','h')
#define ckidSTREAMNAME mmioFOURCC('s','t','r','n')
#define cktypeDIBbits aviTWOCC('d','b')
#define cktypeDIBcompressed aviTWOCC('d','c')
#define cktypePALchange aviTWOCC('p','c')
#define cktypeWAVEbytes aviTWOCC('w','b')
#define DDF_ANIMATE 0x20
#define DDF_BACKGROUNDPAL 0x200
#define DDF_BUFFER 0x40
#define DDF_DONTDRAW 0x10
#define DDF_FULLSCREEN 0x100
#define DDF_HALFTONE 0x1000
#define DDF_HURRYUP 0x800
#define DDF_JUSTDRAWIT 0x80
#define DDF_NOTKEYFRAME 0x400
#define DDF_PREROLL DDF_DONTDRAW
#define DDF_SAME_DIB DDF_SAME_DRAW
#define DDF_SAME_DRAW 0x08
#define DDF_SAME_HDC 0x04
#define DDF_SAME_SIZE DDF_SAME_DRAW
#define DDF_UPDATE 0x02
#define DEFINE_AVIGUID(name, l, w1, w2) DEFINE_GUID(name,l,w1,w2,0xC0,0,0,0,0,0,0,0x46)
#define DrawDibUpdate(hdd, hdc, x, y) DrawDibDraw(hdd,hdc,x,y,0,0,NULL,NULL,0,0,0,0,DDF_UPDATE)
#define EditStreamSetInfo EditStreamSetInfoA
#define EditStreamSetName EditStreamSetNameA
#define FIND_ANY 0x00000020L
#define FIND_DIR 0x0000000fL
#define FIND_FORMAT 0x00000040L
#define FIND_FROM_START 0x00000008L
#define FIND_INDEX 0x00004000L
#define FIND_KEY 0x00000010L
#define FIND_LENGTH 0x00001000L
#define FIND_NEXT 0x00000001L
#define FIND_OFFSET 0x00002000L
#define FIND_POS 0x00000000L
#define FIND_PREV 0x00000004L
#define FIND_RET 0x0000f000L
#define FIND_SIZE 0x00003000L
#define FIND_TYPE 0x000000f0L
#define formtypeAVI mmioFOURCC('A','V','I',' ')
#define FromHex(n) (((n)>='A')?((n)+10-'A'):((n)-'0'))
#define GetOpenFileNamePreview GetOpenFileNamePreviewA
#define GetSaveFileNamePreview GetSaveFileNamePreviewA
#define ICAbout(hic, hwnd) ICSendMessage(hic,ICM_ABOUT,(DWORD)(hwnd),0)
#define ICCOMPRESS_KEYFRAME 0x01
#define ICCompressBegin(hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_COMPRESS_BEGIN,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
#define ICCompressEnd(hic) ICSendMessage(hic,ICM_COMPRESS_END,0,0)
#define ICCOMPRESSFRAMES_PADDING 0x01
#define ICCompressGetFormat(hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_COMPRESS_GET_FORMAT,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
#define ICCompressGetFormatSize(hic, lpbi) ICCompressGetFormat(hic,lpbi,NULL)
#define ICCompressGetSize(hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_COMPRESS_GET_SIZE,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
#define ICCompressQuery(hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_COMPRESS_QUERY,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
#define ICConfigure(hic, hwnd) ICSendMessage(hic,ICM_CONFIGURE,(DWORD)(hwnd),0)
#define ICDECOMPRESS_HURRYUP 0x80000000
#define ICDECOMPRESS_NOTKEYFRAME 0x8000000
#define ICDECOMPRESS_NULLFRAME 0x10000000
#define ICDECOMPRESS_PREROLL 0x20000000
#define ICDECOMPRESS_UPDATE 0x40000000
#define ICDecompressBegin(hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_DECOMPRESS_BEGIN,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
#define ICDecompressEnd(hic) ICSendMessage(hic,ICM_DECOMPRESS_END,0,0)
#define ICDecompressExEnd(hic) ICSendMessage(hic,ICM_DECOMPRESSEX_END,0,0)
#define ICDecompressGetFormat(hic, lpbiInput, lpbiOutput) (LONG)ICSendMessage(hic,ICM_DECOMPRESS_GET_FORMAT,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
#define ICDecompressGetFormatSize(hic, lpbi) ICDecompressGetFormat(hic, lpbi, NULL)
#define ICDecompressGetPalette(hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_DECOMPRESS_GET_PALETTE,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
#define ICDecompressOpen(fccType, fccHandler, lpbiIn, lpbiOut) ICLocate(fccType,fccHandler,lpbiIn,lpbiOut,ICMODE_DECOMPRESS)
#define ICDecompressQuery(hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_DECOMPRESS_QUERY,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
#define ICDecompressSetPalette(hic, lpbiPalette) ICSendMessage(hic,ICM_DECOMPRESS_SET_PALETTE,(DWORD)(lpbiPalette),0)
#define ICDRAW_ANIMATE 0x08L
#define ICDRAW_BUFFER 0x100L
#define ICDRAW_CONTINUE 0x10L
#define ICDRAW_FULLSCREEN 0x02L
#define ICDRAW_HDC 0x04L
#define ICDRAW_HURRYUP 0x80000000L
#define ICDRAW_MEMORYDC 0x20L
#define ICDRAW_NOTKEYFRAME 0x8000000L
#define ICDRAW_NULLFRAME 0x10000000L
#define ICDRAW_PREROLL 0x20000000L
#define ICDRAW_QUERY 0x01L
#define ICDRAW_RENDER 0x80L
#define ICDRAW_UPDATE 0x40000000L
#define ICDRAW_UPDATING 0x40L
#define ICDrawChangePalette(hic, lpbiInput) ICSendMessage(hic,ICM_DRAW_CHANGEPALETTE,(DWORD)(lpbiInput),0)
#define ICDrawEnd(hic) ICSendMessage(hic,ICM_DRAW_END,0,0)
#define ICDrawFlush(hic) ICSendMessage(hic,ICM_DRAW_FLUSH,0,0)
#define ICDrawGetTime(hic, lplTime) ICSendMessage(hic,ICM_DRAW_GETTIME,(DWORD)(lplTime),0)
#define ICDrawOpen(fccType, fccHandler, lpbiIn) ICLocate(fccType,fccHandler,lpbiIn,NULL,ICMODE_DRAW)
#define ICDrawQuery(hic, lpbiInput) ICSendMessage(hic,ICM_DRAW_QUERY,(DWORD)(lpbiInput),0)
#define ICDrawRealize(hic, hdc, fBackground) ICSendMessage(hic,ICM_DRAW_REALIZE,(DWORD)(hdc),(DWORD)(fBackground))
#define ICDrawRenderBuffer(hic) ICSendMessage(hic,ICM_DRAW_RENDERBUFFER,0,0)
#define ICDrawSetTime(hic, lTime) ICSendMessage(hic,ICM_DRAW_SETTIME,(DWORD)lTime,0)
#define ICDrawStart(hic) ICSendMessage(hic,ICM_DRAW_START,0,0)
#define ICDrawStartPlay(hic, lFrom, lTo) ICSendMessage(hic,ICM_DRAW_START_PLAY,(DWORD)(lFrom),(DWORD)(lTo))
#define ICDrawStop(hic) ICSendMessage(hic,ICM_DRAW_STOP,0,0)
#define ICDrawStopPlay(hic) ICSendMessage(hic,ICM_DRAW_STOP_PLAY,0,0)
#define ICDrawWindow(hic, prc) ICSendMessage(hic,ICM_DRAW_WINDOW,(DWORD)(prc),sizeof(RECT))
#define ICERR_ABORT -10
#define ICERR_BADBITDEPTH -200
#define ICERR_BADFLAGS -5
#define ICERR_BADFORMAT -2
#define ICERR_BADHANDLE -8
#define ICERR_BADIMAGESIZE -201
#define ICERR_BADPARAM -6
#define ICERR_BADSIZE -7
#define ICERR_CANTUPDATE -9
#define ICERR_CUSTOM -400
#define ICERR_DONTDRAW 1
#define ICERR_ERROR -100
#define ICERR_GOTOKEYFRAME 3
#define ICERR_INTERNAL -4
#define ICERR_MEMORY -3
#define ICERR_NEWPALETTE 2
#define ICERR_OK 0
#define ICERR_STOPDRAWING 4
#define ICERR_UNSUPPORTED -1
#define ICGetBuffersWanted(hic, lpdwBuffers) ICSendMessage(hic,ICM_GETBUFFERSWANTED,(DWORD)(lpdwBuffers),0)
#define ICGetState(hic, pv, cb) ICSendMessage(hic,ICM_GETSTATE,(DWORD)(pv),(DWORD)(cb))
#define ICGetStateSize(hic) ICGetState(hic,NULL,0)
#define ICINSTALL_DRIVER 0x02
#define ICINSTALL_DRIVERW 0x8002
#define ICINSTALL_FUNCTION 0x01
#define ICINSTALL_HDRV 0x04
#define ICINSTALL_UNICODE 0x8000
#define ICM_ABOUT (ICM_RESERVED+11)
#define ICM_COMPRESS (ICM_USER+8)
#define ICM_COMPRESS_BEGIN (ICM_USER+7)
#define ICM_COMPRESS_END (ICM_USER+9)
#define ICM_COMPRESS_FRAMES_INFO (ICM_USER+70)
#define ICM_COMPRESS_GET_FORMAT (ICM_USER+4)
#define ICM_COMPRESS_GET_SIZE (ICM_USER+5)
#define ICM_COMPRESS_QUERY (ICM_USER+6)
#define ICM_CONFIGURE (ICM_RESERVED+10)
#define ICM_DECOMPRESS (ICM_USER+13)
#define ICM_DECOMPRESS_BEGIN (ICM_USER+12)
#define ICM_DECOMPRESS_END (ICM_USER+14)
#define ICM_DECOMPRESS_GET_FORMAT (ICM_USER+10)
#define ICM_DECOMPRESS_GET_PALETTE (ICM_USER+30)
#define ICM_DECOMPRESS_QUERY (ICM_USER+11)
#define ICM_DECOMPRESS_SET_PALETTE (ICM_USER+29)
#define ICM_DECOMPRESSEX (ICM_USER+62)
#define ICM_DECOMPRESSEX_BEGIN (ICM_USER+60)
#define ICM_DECOMPRESSEX_END (ICM_USER+63)
#define ICM_DECOMPRESSEX_QUERY (ICM_USER+61)
#define ICM_DRAW (ICM_USER+33)
#define ICM_DRAW_BEGIN (ICM_USER+15)
#define ICM_DRAW_CHANGEPALETTE (ICM_USER+51)
#define ICM_DRAW_END (ICM_USER+21)
#define ICM_DRAW_FLUSH (ICM_USER+37)
#define ICM_DRAW_GET_PALETTE (ICM_USER+16)
#define ICM_DRAW_GETTIME (ICM_USER+32)
#define ICM_DRAW_QUERY (ICM_USER+31)
#define ICM_DRAW_REALIZE (ICM_USER+36)
#define ICM_DRAW_RENDERBUFFER (ICM_USER+38)
#define ICM_DRAW_SETTIME (ICM_USER+35)
#define ICM_DRAW_START (ICM_USER+18)
#define ICM_DRAW_START_PLAY (ICM_USER+39)
#define ICM_DRAW_STOP (ICM_USER+19)
#define ICM_DRAW_STOP_PLAY (ICM_USER+40)
#define ICM_DRAW_SUGGESTFORMAT (ICM_USER+50)
#define ICM_DRAW_WINDOW (ICM_USER+34)
#define ICM_FRAMERATE mmioFOURCC('F','r','m','R')
#define ICM_GET (ICM_RESERVED+41)
#define ICM_GETBUFFERSWANTED (ICM_USER+41)
#define ICM_GETDEFAULTKEYFRAMERATE (ICM_USER+42)
#define ICM_GETDEFAULTQUALITY (ICM_RESERVED+30)
#define ICM_GETINFO (ICM_RESERVED+2)
#define ICM_GETQUALITY (ICM_RESERVED+31)
#define ICM_GETSTATE (ICM_RESERVED+0)
#define ICM_KEYFRAMERATE mmioFOURCC('K','e','y','R')
#define ICM_RESERVED ICM_RESERVED_LOW
#define ICM_RESERVED_HIGH (DRV_USER+0x2000)
#define ICM_RESERVED_LOW (DRV_USER+0x1000)
#define ICM_SET (ICM_RESERVED+40)
#define ICM_SET_STATUS_PROC (ICM_USER+72)
#define ICM_SETQUALITY (ICM_RESERVED+32)
#define ICM_SETSTATE (ICM_RESERVED+1)
#define ICM_USER (DRV_USER+0x0000)
#define ICMF_ABOUT_QUERY 0x01
#define ICMF_CHOOSE_ALLCOMPRESSORS 0x08
#define ICMF_CHOOSE_DATARATE 0x02
#define ICMF_CHOOSE_KEYFRAME 0x01
#define ICMF_CHOOSE_PREVIEW 0x04
#define ICMF_COMPVARS_VALID 0x01
#define ICMF_CONFIGURE_QUERY 0x01
#define ICMODE_COMPRESS 1
#define ICMODE_DECOMPRESS 2
#define ICMODE_DRAW 8
#define ICMODE_FASTCOMPRESS 5
#define ICMODE_FASTDECOMPRESS 3
#define ICMODE_QUERY 4
#define ICQUALITY_DEFAULT -1
#define ICQUALITY_HIGH 10000
#define ICQUALITY_LOW 0
#define ICQueryAbout(hic) (ICSendMessage(hic,ICM_ABOUT,(DWORD)-1,ICMF_ABOUT_QUERY)==ICERR_OK)
#define ICQueryConfigure(hic) (ICSendMessage(hic,ICM_CONFIGURE,(DWORD)-1,ICMF_CONFIGURE_QUERY)==ICERR_OK)
#define ICSetState(hic, pv, cb) ICSendMessage(hic,ICM_SETSTATE,(DWORD)(pv),(DWORD)(cb))
#define ICSTATUS_END 2
#define ICSTATUS_ERROR 3
#define ICSTATUS_START 0
#define ICSTATUS_STATUS 1
#define ICSTATUS_YIELD 4
#define ICTYPE_AUDIO mmioFOURCC('a','u','d','c')
#define ICTYPE_VIDEO mmioFOURCC('v','i','d','c')
#define INTERFACE IAVIStream
#define INTERFACE IAVIStreaming
#define INTERFACE IAVIEditStream
#define INTERFACE IAVIFile
#define INTERFACE IGetFrame
#define listtypeAVIHEADER mmioFOURCC('h','d','r','l')
#define listtypeAVIMOVIE mmioFOURCC('m','o','v','i')
#define listtypeAVIRECORD mmioFOURCC('r','e','c',' ')
#define listtypeSTREAMHEADER mmioFOURCC('s','t','r','l')
#define LPAVIFILEINFO LPAVIFILEINFOA
#define LPAVISTREAMINFO LPAVISTREAMINFOA
#define MAKE_AVIERR(e) MAKE_SCODE(SEVERITY_ERROR,FACILITY_ITF,0x4000+e)
#define MAKEAVICKID(tcc, stream) MAKELONG((ToHex((stream)&0x0f)<<8)|(ToHex(((stream)&0xf0)>>4)),tcc)
#define MCIWND_END -2
#define MCIWND_START -1
#define MCIWndCanConfig(hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_CONFIG,0,0)
#define MCIWndCanEject(hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_EJECT,0,0)
#define MCIWndCanPlay(hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_PLAY,0,0)
#define MCIWndCanRecord(hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_RECORD,0,0)
#define MCIWndCanSave(hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_SAVE,0,0)
#define MCIWndCanWindow(hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_WINDOW,0,0)
#define MCIWndChangeStyles(hWnd, mask, value) (LONG)MCIWndSM(hWnd,MCIWNDM_CHANGESTYLES,(WPARAM)(UINT)(mask),(LPARAM)(LONG)(value))
#define MCIWndClose(hWnd) (LONG)MCIWndSM(hWnd,MCI_CLOSE,0,0)
#define MCIWndCreate MCIWndCreateA
#define MCIWndDestroy(hWnd) (VOID)MCIWndSM(hWnd,WM_CLOSE,0,0)
#define MCIWndEject(hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_EJECT,0,0)
#define MCIWndEnd(hWnd) MCIWndSeek(hWnd,MCIWND_END)
#define MCIWNDF_NOAUTOSIZEMOVIE 0x0004
#define MCIWNDF_NOAUTOSIZEWINDOW 0x0001
#define MCIWNDF_NOERRORDLG 0x4000
#define MCIWNDF_NOMENU 0x0008
#define MCIWNDF_NOOPEN 0x8000
#define MCIWNDF_NOPLAYBAR 0x0002
#define MCIWNDF_NOTIFYALL 0x1F00
#define MCIWNDF_NOTIFYANSI 0x0080
#define MCIWNDF_NOTIFYERROR 0x1000
#define MCIWNDF_NOTIFYMEDIA MCIWNDF_NOTIFYMEDIAA
#define MCIWNDF_NOTIFYMEDIAA 0x0880
#define MCIWNDF_NOTIFYMEDIAW 0x0800
#define MCIWNDF_NOTIFYMODE 0x0100
#define MCIWNDF_NOTIFYPOS 0x0200
#define MCIWNDF_NOTIFYSIZE 0x0400
#define MCIWNDF_RECORD 0x2000
#define MCIWNDF_SHOWALL 0x0070
#define MCIWNDF_SHOWMODE 0x0040
#define MCIWNDF_SHOWNAME 0x0010
#define MCIWNDF_SHOWPOS 0x0020
#define MCIWndGetActiveTimer(hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETACTIVETIMER,0,0L);
#define MCIWndGetAlias(hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETALIAS,0,0)
#define MCIWndGetDest(hWnd, prc) (LONG)MCIWndSM(hWnd,MCIWNDM_GET_DEST,0,(LPARAM)(LPRECT)(prc))
#define MCIWndGetDevice(hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETDEVICE,(WPARAM)(UINT)(len),(LPARAM)(LPVOID)(lp))
#define MCIWndGetDeviceID(hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETDEVICEID,0,0)
#define MCIWndGetEnd(hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETEND,0,0)
#define MCIWndGetError(hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETERROR,(WPARAM)(UINT)(len),(LPARAM)(LPVOID)(lp))
#define MCIWndGetFileName(hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETFILENAME,(WPARAM)(UINT)(len),(LPARAM)(LPVOID)(lp))
#define MCIWndGetInactiveTimer(hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETINACTIVETIMER,0,0L);
#define MCIWndGetLength(hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETLENGTH,0,0)
#define MCIWndGetMode(hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETMODE,(WPARAM)(UINT)(len),(LPARAM)(LPTSTR)(lp))
#define MCIWndGetPalette(hWnd) (HPALETTE)MCIWndSM(hWnd,MCIWNDM_GETPALETTE,0,0)
#define MCIWndGetPosition(hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETPOSITION,0,0)
#define MCIWndGetPositionString(hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETPOSITION,(WPARAM)(UINT)(len),(LPARAM)(LPTSTR)(lp))
#define MCIWndGetRepeat(hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_GETREPEAT,0,0)
#define MCIWndGetSource(hWnd, prc) (LONG)MCIWndSM(hWnd,MCIWNDM_GET_SOURCE,0,(LPARAM)(LPRECT)(prc))
#define MCIWndGetSpeed(hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETSPEED,0,0)
#define MCIWndGetStart(hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETSTART,0,0)
#define MCIWndGetStyles(hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETSTYLES,0,0L)
#define MCIWndGetTimeFormat(hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETTIMEFORMAT,(WPARAM)(UINT)(len),(LPARAM)(LPTSTR)(lp))
#define MCIWndGetVolume(hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETVOLUME,0,0)
#define MCIWndGetZoom(hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETZOOM,0,0)
#define MCIWndHome(hWnd) MCIWndSeek(hWnd,MCIWND_START)
#define MCIWNDM_CAN_CONFIG (WM_USER + 149)
#define MCIWNDM_CAN_EJECT (WM_USER + 148)
#define MCIWNDM_CAN_PLAY (WM_USER + 144)
#define MCIWNDM_CAN_RECORD (WM_USER + 146)
#define MCIWNDM_CAN_SAVE (WM_USER + 147)
#define MCIWNDM_CAN_WINDOW (WM_USER + 145)
#define MCIWNDM_CHANGESTYLES (WM_USER + 135)
#define MCIWNDM_EJECT (WM_USER + 107)
#define MCIWNDM_GET_DEST (WM_USER + 142)
#define MCIWNDM_GET_SOURCE (WM_USER + 140)
#define MCIWNDM_GETACTIVETIMER (WM_USER + 132)
#define MCIWNDM_GETALIAS (WM_USER + 137)
#define MCIWNDM_GETDEVICE MCIWNDM_GETDEVICEA
#define MCIWNDM_GETDEVICEA (WM_USER + 125)
#define MCIWNDM_GETDEVICEID (WM_USER + 100)
#define MCIWNDM_GETDEVICEW (WM_USER + 225)
#define MCIWNDM_GETEND (WM_USER + 105)
#define MCIWNDM_GETERROR MCIWNDM_GETERRORA
#define MCIWNDM_GETERRORA (WM_USER + 128)
#define MCIWNDM_GETERRORW (WM_USER + 228)
#define MCIWNDM_GETFILENAME MCIWNDM_GETFILENAMEA
#define MCIWNDM_GETFILENAMEA (WM_USER + 124)
#define MCIWNDM_GETFILENAMEW (WM_USER + 224)
#define MCIWNDM_GETINACTIVETIMER (WM_USER + 133)
#define MCIWNDM_GETLENGTH (WM_USER + 104)
#define MCIWNDM_GETMODE MCIWNDM_GETMODEA
#define MCIWNDM_GETMODEA (WM_USER + 106)
#define MCIWNDM_GETMODEW (WM_USER + 206)
#define MCIWNDM_GETPALETTE (WM_USER + 126)
#define MCIWNDM_GETPOSITION MCIWNDM_GETPOSITIONA
#define MCIWNDM_GETPOSITIONA (WM_USER + 102)
#define MCIWNDM_GETPOSITIONW (WM_USER + 202)
#define MCIWNDM_GETREPEAT (WM_USER + 115)
#define MCIWNDM_GETSPEED (WM_USER + 113)
#define MCIWNDM_GETSTART (WM_USER + 103)
#define MCIWNDM_GETSTYLES (WM_USER + 136)
#define MCIWNDM_GETTIMEFORMAT MCIWNDM_GETTIMEFORMATA
#define MCIWNDM_GETTIMEFORMATA (WM_USER + 120)
#define MCIWNDM_GETTIMEFORMATW (WM_USER + 220)
#define MCIWNDM_GETVOLUME (WM_USER + 111)
#define MCIWNDM_GETZOOM (WM_USER + 109)
#define MCIWNDM_NEW MCIWNDM_NEWA
#define MCIWNDM_NEWA (WM_USER + 134)
#define MCIWNDM_NEWW (WM_USER + 234)
#define MCIWNDM_NOTIFYERROR (WM_USER + 205)
#define MCIWNDM_NOTIFYMEDIA (WM_USER + 203)
#define MCIWNDM_NOTIFYMODE (WM_USER + 200)
#define MCIWNDM_NOTIFYPOS (WM_USER + 201)
#define MCIWNDM_NOTIFYSIZE (WM_USER + 202)
#define MCIWNDM_OPEN MCIWNDM_OPENA
#define MCIWNDM_OPENA (WM_USER + 153)
#define MCIWNDM_OPENINTERFACE (WM_USER + 151)
#define MCIWNDM_OPENW (WM_USER + 252)
#define MCIWNDM_PALETTEKICK (WM_USER + 150)
#define MCIWNDM_PLAYFROM (WM_USER + 122)
#define MCIWNDM_PLAYREVERSE (WM_USER + 139)
#define MCIWNDM_PLAYTO (WM_USER + 123)
#define MCIWNDM_PUT_DEST (WM_USER + 143)
#define MCIWNDM_PUT_SOURCE (WM_USER + 141)
#define MCIWNDM_REALIZE (WM_USER + 118)
#define MCIWNDM_RETURNSTRING MCIWNDM_RETURNSTRINGA
#define MCIWNDM_RETURNSTRINGA (WM_USER + 138)
#define MCIWNDM_RETURNSTRINGW (WM_USER + 238)
#define MCIWNDM_SENDSTRING MCIWNDM_SENDSTRINGA
#define MCIWNDM_SENDSTRINGA (WM_USER + 101)
#define MCIWNDM_SENDSTRINGW (WM_USER + 201)
#define MCIWNDM_SETACTIVETIMER (WM_USER + 130)
#define MCIWNDM_SETINACTIVETIMER (WM_USER + 131)
#define MCIWNDM_SETOWNER (WM_USER + 152)
#define MCIWNDM_SETPALETTE (WM_USER + 127)
#define MCIWNDM_SETREPEAT (WM_USER + 114)
#define MCIWNDM_SETSPEED (WM_USER + 112)
#define MCIWNDM_SETTIMEFORMAT MCIWNDM_SETTIMEFORMATA
#define MCIWNDM_SETTIMEFORMATA (WM_USER + 119)
#define MCIWNDM_SETTIMEFORMATW (WM_USER + 219)
#define MCIWNDM_SETTIMERS (WM_USER + 129)
#define MCIWNDM_SETVOLUME (WM_USER + 110)
#define MCIWNDM_SETZOOM (WM_USER + 108)
#define MCIWNDM_VALIDATEMEDIA (WM_USER + 121)
#define MCIWndNew(hWnd, lp) (LONG)MCIWndSM(hWnd,MCIWNDM_NEW,0,(LPARAM)(LPVOID)(lp))
#define MCIWndOpen(hWnd, sz, f) (LONG)MCIWndSM(hWnd,MCIWNDM_OPEN,(WPARAM)(UINT)(f),(LPARAM)(LPVOID)(sz))
#define MCIWndOpenDialog(hWnd) MCIWndOpen(hWnd,-1,0)
#define MCIWNDOPENF_NEW 0x0001
#define MCIWndOpenInterface(hWnd, pUnk) (LONG)MCIWndSM(hWnd,MCIWNDM_OPENINTERFACE,0,(LPARAM)(LPUNKNOWN)(pUnk))
#define MCIWndPaletteKick(hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_PALETTEKICK,0,0)
#define MCIWndPause(hWnd) (LONG)MCIWndSM(hWnd,MCI_PAUSE,0,0)
#define MCIWndPlay(hWnd) (LONG)MCIWndSM(hWnd,MCI_PLAY,0,0)
#define MCIWndPlayFrom(hWnd, lPos) (LONG)MCIWndSM(hWnd,MCIWNDM_PLAYFROM,0,(LPARAM)(LONG)(lPos))
#define MCIWndPlayFromTo(hWnd, lStart, lEnd) (MCIWndSeek(hWnd,lStart),MCIWndPlayTo(hWnd,lEnd))
#define MCIWndPlayReverse(hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_PLAYREVERSE,0,0)
#define MCIWndPlayTo(hWnd, lPos) (LONG)MCIWndSM(hWnd,MCIWNDM_PLAYTO, 0,(LPARAM)(LONG)(lPos))
#define MCIWndPutDest(hWnd, prc) (LONG)MCIWndSM(hWnd,MCIWNDM_PUT_DEST,0,(LPARAM)(LPRECT)(prc))
#define MCIWndPutSource(hWnd, prc) (LONG)MCIWndSM(hWnd,MCIWNDM_PUT_SOURCE,0,(LPARAM)(LPRECT)(prc))
#define MCIWndRealize(hWnd, fBkgnd) (LONG)MCIWndSM(hWnd,MCIWNDM_REALIZE,(WPARAM)(BOOL)(fBkgnd),0)
#define MCIWndRecord(hWnd) (LONG)MCIWndSM(hWnd,MCI_RECORD,0,0)
#define MCIWndResume(hWnd) (LONG)MCIWndSM(hWnd,MCI_RESUME,0,0)
#define MCIWndReturnString(hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_RETURNSTRING,(WPARAM)(UINT)(len),(LPARAM)(LPVOID)(lp))
#define MCIWndSave(hWnd, szFile) (LONG)MCIWndSM(hWnd,MCI_SAVE,0,(LPARAM)(LPVOID)(szFile))
#define MCIWndSaveDialog(hWnd) MCIWndSave(hWnd,-1)
#define MCIWndSeek(hWnd, lPos) (LONG)MCIWndSM(hWnd,MCI_SEEK,0,(LPARAM)(LONG)(lPos))
#define MCIWndSendString(hWnd, sz) (LONG)MCIWndSM(hWnd,MCIWNDM_SENDSTRING,0,(LPARAM)(LPTSTR)(sz))
#define MCIWndSetActiveTimer(hWnd, active) (VOID)MCIWndSM(hWnd,MCIWNDM_SETACTIVETIMER,(WPARAM)(UINT)(active),0L)
#define MCIWndSetInactiveTimer(hWnd, inactive) (VOID)MCIWndSM(hWnd,MCIWNDM_SETINACTIVETIMER,(WPARAM)(UINT)(inactive),0L)
#define MCIWndSetOwner(hWnd, hWndP) (LONG)MCIWndSM(hWnd,MCIWNDM_SETOWNER,(WPARAM)(hWndP),0)
#define MCIWndSetPalette(hWnd, hpal) (LONG)MCIWndSM(hWnd,MCIWNDM_SETPALETTE,(WPARAM)(HPALETTE)(hpal),0)
#define MCIWndSetRepeat(hWnd, f) (void)MCIWndSM(hWnd,MCIWNDM_SETREPEAT,0,(LPARAM)(BOOL)(f))
#define MCIWndSetSpeed(hWnd, iSpeed) (LONG)MCIWndSM(hWnd,MCIWNDM_SETSPEED,0,(LPARAM)(UINT)(iSpeed))
#define MCIWndSetTimeFormat(hWnd, lp) (LONG)MCIWndSM(hWnd,MCIWNDM_SETTIMEFORMAT,0,(LPARAM)(LPTSTR)(lp))
#define MCIWndSetTimers(hWnd, active, inactive) (VOID)MCIWndSM(hWnd,MCIWNDM_SETTIMERS,(WPARAM)(UINT)(active),(LPARAM)(UINT)(inactive))
#define MCIWndSetVolume(hWnd, iVol) (LONG)MCIWndSM(hWnd,MCIWNDM_SETVOLUME,0,(LPARAM)(UINT)(iVol))
#define MCIWndSetZoom(hWnd, iZoom) (VOID)MCIWndSM(hWnd,MCIWNDM_SETZOOM,0,(LPARAM)(UINT)(iZoom))
#define MCIWndSM SendMessage
#define MCIWndStep(hWnd, n) (LONG)MCIWndSM(hWnd,MCI_STEP,0,(LPARAM)(long)(n))
#define MCIWndStop(hWnd) (LONG)MCIWndSM(hWnd,MCI_STOP,0,0)
#define MCIWndUseFrames(hWnd) MCIWndSetTimeFormat(hWnd,TEXT("frames"))
#define MCIWndUseTime(hWnd) MCIWndSetTimeFormat(hWnd,TEXT("ms"))
#define MCIWndValidateMedia(hWnd) (VOID)MCIWndSM(hWnd,MCIWNDM_VALIDATEMEDIA,0,0)
#define PAVIFILEINFO PAVIFILEINFOA
#define PAVISTREAMINFO PAVISTREAMINFOA
#define PD_CAN_DRAW_DIB 0x01
#define PD_CAN_STRETCHDIB 0x02
#define PD_STRETCHDIB_1_1_OK 0x04
#define PD_STRETCHDIB_1_2_OK 0x08
#define PD_STRETCHDIB_1_N_OK 0x10
#define StreamFromFOURCC(fcc) ((WORD)((FromHex(LOBYTE(LOWORD(fcc)))<<4)+(FromHex(HIBYTE(LOWORD(fcc))))))
#define streamtypeANY 0UL
#define streamtypeAUDIO mmioFOURCC('a','u','d','s')
#define streamtypeMIDI mmioFOURCC('m','i','d','s')
#define streamtypeTEXT mmioFOURCC('t','x','t','s')
#define streamtypeVIDEO mmioFOURCC('v','i','d','s')
#define ToHex(n) ((BYTE)(((n)>9)?((n)-10+'A'):((n)+'0')))
#define TWOCCFromFOURCC(fcc) HIWORD(fcc)
#define VFWAPI WINAPI
#define VFWAPIV WINAPIV
#define VIDCF_COMPRESSFRAMES 0x08
#define VIDCF_CRUNCH 0x02
#define VIDCF_DRAW 0x10
#define VIDCF_FASTTEMPORAL (VIDCF_FASTTEMPORALC|VIDCF_FASTTEMPORALD)
#define VIDCF_FASTTEMPORALC 0x20
#define VIDCF_FASTTEMPORALD 0x80
#define VIDCF_QUALITY 0x01
#define VIDCF_QUALITYTIME 0x40
#define VIDCF_TEMPORAL 0x04
#define WM_CAP_ABORT (WM_USER + 69)
#define WM_CAP_DLG_VIDEOCOMPRESSION (WM_USER + 46)
#define WM_CAP_DLG_VIDEODISPLAY (WM_USER + 43)
#define WM_CAP_DLG_VIDEOFORMAT (WM_USER + 41)
#define WM_CAP_DLG_VIDEOSOURCE (WM_USER + 42)
#define WM_CAP_DRIVER_CONNECT (WM_USER + 10)
#define WM_CAP_DRIVER_DISCONNECT (WM_USER + 11)
#define WM_CAP_DRIVER_GET_CAPS (WM_USER + 14)
#define WM_CAP_DRIVER_GET_NAME WM_CAP_DRIVER_GET_NAMEA
#define WM_CAP_DRIVER_GET_NAMEA (WM_USER + 12)
#define WM_CAP_DRIVER_GET_NAMEW (WM_CAP_DRIVER_GET_NAMEA + 100)
#define WM_CAP_DRIVER_GET_VERSION WM_CAP_DRIVER_GET_VERSIONA
#define WM_CAP_DRIVER_GET_VERSIONA (WM_USER + 13)
#define WM_CAP_DRIVER_GET_VERSIONW (WM_CAP_DRIVER_GET_VERSIONA + 100)
#define WM_CAP_EDIT_COPY (WM_USER + 30)
#define WM_CAP_FILE_ALLOCATE (WM_USER + 22)
#define WM_CAP_FILE_GET_CAPTURE_FILE WM_CAP_FILE_GET_CAPTURE_FILEA
#define WM_CAP_FILE_GET_CAPTURE_FILEA (WM_USER + 21)
#define WM_CAP_FILE_GET_CAPTURE_FILEW (WM_CAP_FILE_GET_CAPTURE_FILEA + 100)
#define WM_CAP_FILE_SAVEAS WM_CAP_FILE_SAVEASA
#define WM_CAP_FILE_SAVEASA (WM_USER + 23)
#define WM_CAP_FILE_SAVEASW (WM_CAP_FILE_SAVEASA + 100)
#define WM_CAP_FILE_SAVEDIB WM_CAP_FILE_SAVEDIBA
#define WM_CAP_FILE_SAVEDIBA (WM_USER + 25)
#define WM_CAP_FILE_SAVEDIBW (WM_CAP_FILE_SAVEDIBA + 100)
#define WM_CAP_FILE_SET_CAPTURE_FILE WM_CAP_FILE_SET_CAPTURE_FILEA
#define WM_CAP_FILE_SET_CAPTURE_FILEA (WM_USER + 20)
#define WM_CAP_FILE_SET_CAPTURE_FILEW (WM_CAP_FILE_SET_CAPTURE_FILEA + 100)
#define WM_CAP_FILE_SET_INFOCHUNK (WM_USER + 24)
#define WM_CAP_GET_AUDIOFORMAT (WM_USER + 36)
#define WM_CAP_GET_MCI_DEVICE WM_CAP_GET_MCI_DEVICEA
#define WM_CAP_GET_MCI_DEVICEA (WM_USER + 67)
#define WM_CAP_GET_MCI_DEVICEW (WM_CAP_GET_MCI_DEVICEA + 100)
#define WM_CAP_GET_SEQUENCE_SETUP (WM_USER + 65)
#define WM_CAP_GET_STATUS (WM_USER + 54)
#define WM_CAP_GET_USER_DATA (WM_USER + 8)
#define WM_CAP_GET_VIDEOFORMAT (WM_USER + 44)
#define WM_CAP_GRAB_FRAME (WM_USER + 60)
#define WM_CAP_GRAB_FRAME_NOSTOP (WM_USER + 61)
#define WM_CAP_PAL_AUTOCREATE (WM_USER + 83)
#define WM_CAP_PAL_MANUALCREATE (WM_USER + 84)
#define WM_CAP_PAL_OPEN WM_CAP_PAL_OPENA
#define WM_CAP_PAL_OPENA (WM_USER + 80)
#define WM_CAP_PAL_OPENW (WM_CAP_PAL_OPENA + 100)
#define WM_CAP_PAL_PASTE (WM_USER + 82)
#define WM_CAP_PAL_SAVE WM_CAP_PAL_SAVEA
#define WM_CAP_PAL_SAVEA (WM_USER + 81)
#define WM_CAP_PAL_SAVEW (WM_CAP_PAL_SAVEA + 100)
#define WM_CAP_SEQUENCE (WM_USER + 62)
#define WM_CAP_SEQUENCE_NOFILE (WM_USER + 63)
#define WM_CAP_SET_AUDIOFORMAT (WM_USER + 35)
#define WM_CAP_SET_CALLBACK_CAPCONTROL (WM_USER + 85)
#define WM_CAP_SET_CALLBACK_ERROR WM_CAP_SET_CALLBACK_ERRORA
#define WM_CAP_SET_CALLBACK_ERRORA (WM_USER + 2)
#define WM_CAP_SET_CALLBACK_ERRORW (WM_CAP_SET_CALLBACK_ERRORA + 100)
#define WM_CAP_SET_CALLBACK_FRAME WM_CAP_SET_CALLBACK_FRAMEA
#define WM_CAP_SET_CALLBACK_FRAMEA (WM_USER + 5)
#define WM_CAP_SET_CALLBACK_FRAMEW (WM_CAP_SET_CALLBACK_FRAMEA + 100)
#define WM_CAP_SET_CALLBACK_STATUS (WM_USER + 3)
#define WM_CAP_SET_CALLBACK_VIDEOSTREAM (WM_USER + 6)
#define WM_CAP_SET_CALLBACK_WAVESTREAM (WM_USER + 7)
#define WM_CAP_SET_CALLBACK_YIELD (WM_USER + 4)
#define WM_CAP_SET_MCI_DEVICE WM_CAP_SET_MCI_DEVICEA
#define WM_CAP_SET_MCI_DEVICEA (WM_USER + 66)
#define WM_CAP_SET_MCI_DEVICEW (WM_CAP_SET_MCI_DEVICEA + 100)
#define WM_CAP_SET_OVERLAY (WM_USER + 51)
#define WM_CAP_SET_PREVIEW (WM_USER + 50)
#define WM_CAP_SET_PREVIEWRATE (WM_USER + 52)
#define WM_CAP_SET_SCALE (WM_USER + 53)
#define WM_CAP_SET_SCROLL (WM_USER + 55)
#define WM_CAP_SET_SEQUENCE_SETUP (WM_USER + 64)
#define WM_CAP_SET_USER_DATA (WM_USER + 9)
#define WM_CAP_SET_VIDEOFORMAT (WM_USER + 45)
#define WM_CAP_SINGLE_FRAME (WM_USER + 72)
#define WM_CAP_SINGLE_FRAME_CLOSE (WM_USER + 71)
#define WM_CAP_SINGLE_FRAME_OPEN (WM_USER + 70)
#define WM_CAP_STOP (WM_USER + 68)
Typedefs
typedef BOOL(CALLBACK * AVISAVECALLBACK) (INT)
typedef struct AVICOMPRESSOPTIONS * LPAVICOMPRESSOPTIONS
typedef struct AVIFILEINFOA * LPAVIFILEINFOA
typedef struct AVIFILEINFOW * LPAVIFILEINFOW
typedef struct AVISTREAMINFOA * LPAVISTREAMINFOA
typedef struct AVISTREAMINFOW * LPAVISTREAMINFOW
typedef struct CAPDRIVERCAPS * LPCAPDRIVERCAPS
typedef struct CAPINFOCHUNK * LPCAPINFOCHUNK
typedef struct CAPSTATUS * LPCAPSTATUS
typedef struct CAPTUREPARMS * LPCAPTUREPARMS
typedef struct ICOPEN * LPICOPEN
typedef struct VIDEOHDR * LPVIDEOHDR
typedef struct AVICOMPRESSOPTIONS * PAVICOMPRESSOPTIONS
typedef IAVIEditStream * PAVIEDITSTREAM
typedef IAVIFile * PAVIFILE
typedef struct AVIFILEINFOA * PAVIFILEINFOA
typedef struct AVIFILEINFOW * PAVIFILEINFOW
typedef IAVIStream * PAVISTREAM
typedef struct AVISTREAMINFOA * PAVISTREAMINFOA
typedef struct AVISTREAMINFOW * PAVISTREAMINFOW
typedef IAVIStreaming * PAVISTREAMING
typedef struct COMPVARS * PCOMPVARS
typedef IGetFrame * PGETFRAME
typedef WORD TWOCC
Functions
HRESULT WINAPI AVIBuildFilterA (LPSTR, LONG, BOOL)
HRESULT WINAPI AVIBuildFilterW (LPWSTR, LONG, BOOL)
HRESULT WINAPI AVIClearClipboard (VOID)
ULONG WINAPI AVIFileAddRef (PAVIFILE)
HRESULT WINAPI AVIFileCreateStreamA (PAVIFILE, PAVISTREAM *, AVISTREAMINFOA *)
HRESULT WINAPI AVIFileCreateStreamW (PAVIFILE, PAVISTREAM *, AVISTREAMINFOW *)
HRESULT WINAPI AVIFileEndRecord (PAVIFILE)
VOID WINAPI AVIFileExit (void)
HRESULT WINAPI AVIFileGetStream (PAVIFILE, PAVISTREAM *, DWORD, LONG)
HRESULT WINAPI AVIFileInfoA (PAVIFILE, PAVIFILEINFOA, LONG)
HRESULT WINAPI AVIFileInfoW (PAVIFILE, PAVIFILEINFOW, LONG)
VOID WINAPI AVIFileInit (void)
HRESULT WINAPI AVIFileOpenA (PAVIFILE *, LPCSTR, UINT, LPCLSID)
HRESULT WINAPI AVIFileOpenW (PAVIFILE *, LPCWSTR, UINT, LPCLSID)
HRESULT WINAPI AVIFileReadData (PAVIFILE, DWORD, LPVOID, LPLONG)
ULONG WINAPI AVIFileRelease (PAVIFILE)
HRESULT WINAPI AVIFileWriteData (PAVIFILE, DWORD, LPVOID, LONG)
HRESULT WINAPI AVIGetFromClipboard (PAVIFILE *)
HRESULT WINAPI AVIMakeCompressedStream (PAVISTREAM *, PAVISTREAM, AVICOMPRESSOPTIONS *, CLSID *)
HRESULT WINAPI AVIMakeFileFromStreams (PAVIFILE *, INT, PAVISTREAM *)
HRESULT WINAPI AVIPutFileOnClipboard (PAVIFILE)
BOOL WINAPI AVISaveOptions (HWND, UINT, INT, PAVISTREAM *, LPAVICOMPRESSOPTIONS *)
HRESULT WINAPI AVISaveOptionsFree (INT, LPAVICOMPRESSOPTIONS *)
HRESULT WINAPI AVISaveVA (LPCSTR, CLSID *, AVISAVECALLBACK, INT, PAVISTREAM *, LPAVICOMPRESSOPTIONS *)
HRESULT WINAPI AVISaveVW (LPCWSTR, CLSID *, AVISAVECALLBACK, INT, PAVISTREAM *, LPAVICOMPRESSOPTIONS *)
ULONG WINAPI AVIStreamAddRef (PAVISTREAM)
HRESULT WINAPI AVIStreamCreate (PAVISTREAM *, LONG, LONG, CLSID *)
HRESULT WINAPI AVIStreamFindSample (PAVISTREAM, LONG, DWORD)
LPVOID WINAPI AVIStreamGetFrame (PGETFRAME, LONG)
HRESULT WINAPI AVIStreamGetFrameClose (PGETFRAME)
PGETFRAME WINAPI AVIStreamGetFrameOpen (PAVISTREAM, LPBITMAPINFOHEADER)
HRESULT WINAPI AVIStreamInfoA (PAVISTREAM, AVISTREAMINFOA *, LONG)
HRESULT WINAPI AVIStreamInfoW (PAVISTREAM, AVISTREAMINFOW *, LONG)
LONG WINAPI AVIStreamLength (PAVISTREAM)
HRESULT WINAPI AVIStreamOpenFromFileA (PAVISTREAM *, LPCSTR, DWORD, LONG, UINT, CLSID *)
HRESULT WINAPI AVIStreamOpenFromFileW (PAVISTREAM *, LPCWSTR, DWORD, LONG, UINT, CLSID *)
HRESULT WINAPI AVIStreamRead (PAVISTREAM, LONG, LONG, LPVOID, LONG, LONG *, LONG *)
HRESULT WINAPI AVIStreamReadData (PAVISTREAM, DWORD, LPVOID, LONG *)
HRESULT WINAPI AVIStreamReadFormat (PAVISTREAM, LONG, LPVOID, LONG *)
ULONG WINAPI AVIStreamRelease (PAVISTREAM)
LONG WINAPI AVIStreamSampleToTime (PAVISTREAM, LONG)
HRESULT WINAPI AVIStreamSetFormat (PAVISTREAM, LONG, LPVOID, LONG)
LONG WINAPI AVIStreamStart (PAVISTREAM)
LONG WINAPI AVIStreamTimeToSample (PAVISTREAM, LONG)
HRESULT WINAPI AVIStreamWrite (PAVISTREAM, LONG, LONG, LPVOID, LONG, DWORD, LONG *, LONG *)
HRESULT WINAPI AVIStreamWriteData (PAVISTREAM, DWORD, LPVOID, LONG)
HWND VFWAPI capCreateCaptureWindowA (LPCSTR, DWORD, int, int, int, int, HWND, int)
HWND VFWAPI capCreateCaptureWindowW (LPCWSTR, DWORD, int, int, int, int, HWND, int)
BOOL VFWAPI capGetDriverDescriptionA (UINT, LPSTR, int, LPSTR, int)
BOOL VFWAPI capGetDriverDescriptionW (UINT, LPWSTR, int, LPWSTR, int)
HRESULT WINAPI CreateEditableStream (PAVISTREAM *, PAVISTREAM)
DECLARE_HANDLE (HDRAWDIB)
DECLARE_HANDLE (HIC)
DECLARE_INTERFACE_ (IAVIEditStream, IUnknown)
DECLARE_INTERFACE_ (IAVIFile, IUnknown)
DECLARE_INTERFACE_ (IAVIStream, IUnknown)
DECLARE_INTERFACE_ (IAVIStreaming, IUnknown)
DECLARE_INTERFACE_ (IGetFrame, IUnknown)
DEFINE_AVIGUID (CLSID_AVIFile, 0x00020000, 0, 0)
DEFINE_AVIGUID (IID_IAVIEditStream, 0x00020024, 0, 0)
DEFINE_AVIGUID (IID_IAVIFile, 0x00020020, 0, 0)
DEFINE_AVIGUID (IID_IAVIStream, 0x00020021, 0, 0)
DEFINE_AVIGUID (IID_IAVIStreaming, 0x00020022, 0, 0)
DEFINE_AVIGUID (IID_IGetFrame, 0x00020023, 0, 0)
BOOL VFWAPI DrawDibBegin (HDRAWDIB, HDC, INT, INT, LPBITMAPINFOHEADER, INT, INT, UINT)
BOOL VFWAPI DrawDibChangePalette (HDRAWDIB, int, int, LPPALETTEENTRY)
BOOL VFWAPI DrawDibClose (HDRAWDIB)
BOOL VFWAPI DrawDibDraw (HDRAWDIB, HDC, INT, INT, INT, INT, LPBITMAPINFOHEADER, LPVOID, INT, INT, INT, INT, UINT)
BOOL VFWAPI DrawDibEnd (HDRAWDIB)
LPVOID VFWAPI DrawDibGetBuffer (HDRAWDIB, LPBITMAPINFOHEADER, DWORD, DWORD)
HPALETTE VFWAPI DrawDibGetPalette (HDRAWDIB)
HDRAWDIB VFWAPI DrawDibOpen (VOID)
DWORD VFWAPI DrawDibProfileDisplay (LPBITMAPINFOHEADER)
UINT VFWAPI DrawDibRealize (HDRAWDIB, HDC, BOOL)
BOOL VFWAPI DrawDibSetPalette (HDRAWDIB, HPALETTE)
BOOL VFWAPI DrawDibStart (HDRAWDIB, DWORD)
BOOL VFWAPI DrawDibStop (HDRAWDIB)
HRESULT WINAPI EditStreamClone (PAVISTREAM, PAVISTREAM *)
HRESULT WINAPI EditStreamCopy (PAVISTREAM, LONG *, LONG *, PAVISTREAM *)
HRESULT WINAPI EditStreamCut (PAVISTREAM, LONG *, LONG *, PAVISTREAM *)
HRESULT WINAPI EditStreamPaste (PAVISTREAM, LONG *, LONG *, PAVISTREAM, LONG, LONG)
HRESULT WINAPI EditStreamSetInfoA (PAVISTREAM, LPAVISTREAMINFOA, LONG)
HRESULT WINAPI EditStreamSetInfoW (PAVISTREAM, LPAVISTREAMINFOW, LONG)
HRESULT WINAPI EditStreamSetNameA (PAVISTREAM, LPCSTR)
HRESULT WINAPI EditStreamSetNameW (PAVISTREAM, LPCWSTR)
LRESULT VFWAPI ICClose (HIC hic)
DWORD VFWAPIV ICCompress (HIC, DWORD, LPBITMAPINFOHEADER, LPVOID, LPBITMAPINFOHEADER, LPVOID, LPDWORD, LPDWORD, LONG, DWORD, DWORD, LPBITMAPINFOHEADER, LPVOID)
BOOL VFWAPI ICCompressorChoose (HWND, UINT, LPVOID, LPVOID, PCOMPVARS, LPSTR)
void VFWAPI ICCompressorFree (PCOMPVARS)
DWORD VFWAPIV ICDecompress (HIC, DWORD, LPBITMAPINFOHEADER, LPVOID, LPBITMAPINFOHEADER, LPVOID)
static __inline LRESULT ICDecompressEx (HIC hic, DWORD dwFlags, LPBITMAPINFOHEADER lpbiSrc, LPVOID lpSrc, INT xSrc, INT ySrc, INT dxSrc, INT dySrc, LPBITMAPINFOHEADER lpbiDst, LPVOID lpDst, INT xDst, INT yDst, INT dxDst, INT dyDst)
static __inline LRESULT ICDecompressExBegin (HIC hic, DWORD dwFlags, LPBITMAPINFOHEADER lpbiSrc, LPVOID lpSrc, INT xSrc, INT ySrc, INT dxSrc, INT dySrc, LPBITMAPINFOHEADER lpbiDst, LPVOID lpDst, INT xDst, INT yDst, INT dxDst, INT dyDst)
static __inline LRESULT ICDecompressExQuery (HIC hic, DWORD dwFlags, LPBITMAPINFOHEADER lpbiSrc, LPVOID lpSrc, INT xSrc, INT ySrc, INT dxSrc, INT dySrc, LPBITMAPINFOHEADER lpbiDst, LPVOID lpDst, INT xDst, INT yDst, INT dxDst, INT dyDst)
DWORD VFWAPIV ICDraw (HIC, DWORD, LPVOID, LPVOID, DWORD, LONG)
DWORD VFWAPIV ICDrawBegin (HIC, DWORD, HPALETTE, HWND, HDC, INT, INT, INT, INT, LPBITMAPINFOHEADER, INT, INT, INT, INT, DWORD, DWORD)
static __inline LRESULT ICDrawSuggestFormat (HIC hic, LPBITMAPINFOHEADER lpbiIn, LPBITMAPINFOHEADER lpbiOut, INT dxSrc, INT dySrc, INT dxDst, INT dyDst, HIC hicDecomp)
static __inline DWORD ICGetDefaultKeyFrameRate (HIC hic)
static __inline DWORD ICGetDefaultQuality (HIC hic)
HIC VFWAPI ICGetDisplayFormat (HIC, LPBITMAPINFOHEADER, LPBITMAPINFOHEADER, INT, INT, INT)
LRESULT VFWAPI ICGetInfo (HIC, ICINFO *, DWORD)
HANDLE VFWAPI ICImageCompress (HIC, UINT, LPBITMAPINFO, LPVOID, LPBITMAPINFO, LONG, LONG *)
HANDLE VFWAPI ICImageDecompress (HIC, UINT, LPBITMAPINFO, LPVOID, LPBITMAPINFO)
BOOL VFWAPI ICInfo (DWORD, DWORD, ICINFO *)
BOOL VFWAPI ICInstall (DWORD, DWORD, LPARAM, LPSTR, UINT)
HIC VFWAPI ICLocate (DWORD, DWORD, LPBITMAPINFOHEADER, LPBITMAPINFOHEADER, WORD)
HIC VFWAPI ICOpen (DWORD, DWORD, UINT)
HIC VFWAPI ICOpenFunction (DWORD, DWORD, UINT, FARPROC)
BOOL VFWAPI ICRemove (DWORD, DWORD, UINT)
LRESULT VFWAPI ICSendMessage (HIC, UINT, DWORD, DWORD)
LPVOID VFWAPI ICSeqCompressFrame (PCOMPVARS, UINT, LPVOID, BOOL *, LONG *)
void VFWAPI ICSeqCompressFrameEnd (PCOMPVARS)
BOOL VFWAPI ICSeqCompressFrameStart (PCOMPVARS, LPBITMAPINFO)
static __inline LRESULT ICSetStatusProc (HIC hic, DWORD dwFlags, LRESULT lParam, LONG(CALLBACK *fpfnStatus)(LPARAM, UINT, LONG))
LONG VFWAPI InitVFW (VOID)
HWND VFWAPIV MCIWndCreateA (HWND, HINSTANCE, DWORD, LPCSTR)
HWND VFWAPIV MCIWndCreateW (HWND, HINSTANCE, DWORD, LPCWSTR)
LONG VFWAPI TermVFW (VOID)
DWORD VFWAPI VideoForWindowsVersion (VOID)
Macro Definition Documentation
__capSendMessage
#define __capSendMessage (hwnd, m, w, l) (IsWindow(hwnd)?SendMessage(hwnd,m,w,l):0)
Definition at line 1228 of file vfw.h.
AVI_HEADERSIZE
#define AVI_HEADERSIZE 2048
Definition at line 189 of file vfw.h.
AVIBuildFilter
#define AVIBuildFilter AVIBuildFilterA
Definition at line 1336 of file vfw.h.
AVICOMPRESSF_DATARATE
#define AVICOMPRESSF_DATARATE 0x02
Definition at line 212 of file vfw.h.
AVICOMPRESSF_INTERLEAVE
#define AVICOMPRESSF_INTERLEAVE 0x01
Definition at line 211 of file vfw.h.
AVICOMPRESSF_KEYFRAMES
#define AVICOMPRESSF_KEYFRAMES 0x04
Definition at line 213 of file vfw.h.
AVICOMPRESSF_VALID
#define AVICOMPRESSF_VALID 0x08
Definition at line 214 of file vfw.h.
AVIERR_BADFLAGS
#define AVIERR_BADFLAGS MAKE_AVIERR(105)
Definition at line 235 of file vfw.h.
AVIERR_BADFORMAT
#define AVIERR_BADFORMAT MAKE_AVIERR(102)
Definition at line 232 of file vfw.h.
AVIERR_BADHANDLE
#define AVIERR_BADHANDLE MAKE_AVIERR(108)
Definition at line 238 of file vfw.h.
AVIERR_BADPARAM
#define AVIERR_BADPARAM MAKE_AVIERR(106)
Definition at line 236 of file vfw.h.
AVIERR_BADSIZE
#define AVIERR_BADSIZE MAKE_AVIERR(107)
Definition at line 237 of file vfw.h.
AVIERR_BUFFERTOOSMALL
#define AVIERR_BUFFERTOOSMALL MAKE_AVIERR(116)
Definition at line 246 of file vfw.h.
AVIERR_CANTCOMPRESS
#define AVIERR_CANTCOMPRESS MAKE_AVIERR(117)
Definition at line 247 of file vfw.h.
AVIERR_COMPRESSOR
#define AVIERR_COMPRESSOR MAKE_AVIERR(112)
Definition at line 242 of file vfw.h.
AVIERR_ERROR
#define AVIERR_ERROR MAKE_AVIERR(199)
Definition at line 249 of file vfw.h.
AVIERR_FILEOPEN
#define AVIERR_FILEOPEN MAKE_AVIERR(111)
Definition at line 241 of file vfw.h.
AVIERR_FILEREAD
#define AVIERR_FILEREAD MAKE_AVIERR(109)
Definition at line 239 of file vfw.h.
AVIERR_FILEWRITE
#define AVIERR_FILEWRITE MAKE_AVIERR(110)
Definition at line 240 of file vfw.h.
AVIERR_INTERNAL
#define AVIERR_INTERNAL MAKE_AVIERR(104)
Definition at line 234 of file vfw.h.
AVIERR_MEMORY
#define AVIERR_MEMORY MAKE_AVIERR(103)
Definition at line 233 of file vfw.h.
AVIERR_NOCOMPRESSOR
#define AVIERR_NOCOMPRESSOR MAKE_AVIERR(113)
Definition at line 243 of file vfw.h.
AVIERR_NODATA
#define AVIERR_NODATA MAKE_AVIERR(115)
Definition at line 245 of file vfw.h.
AVIERR_OK
#define AVIERR_OK 0
Definition at line 229 of file vfw.h.
AVIERR_READONLY
#define AVIERR_READONLY MAKE_AVIERR(114)
Definition at line 244 of file vfw.h.
AVIERR_UNSUPPORTED
#define AVIERR_UNSUPPORTED MAKE_AVIERR(101)
Definition at line 231 of file vfw.h.
AVIERR_USERABORT
#define AVIERR_USERABORT MAKE_AVIERR(198)
Definition at line 248 of file vfw.h.
AVIF_COPYRIGHTED
#define AVIF_COPYRIGHTED 0x20000
Definition at line 188 of file vfw.h.
AVIF_HASINDEX
#define AVIF_HASINDEX 0x10
Definition at line 183 of file vfw.h.
AVIF_ISINTERLEAVED
#define AVIF_ISINTERLEAVED 0x100
Definition at line 185 of file vfw.h.
AVIF_MUSTUSEINDEX
#define AVIF_MUSTUSEINDEX 0x20
Definition at line 184 of file vfw.h.
AVIF_TRUSTCKTYPE
#define AVIF_TRUSTCKTYPE 0x800
Definition at line 186 of file vfw.h.
AVIF_WASCAPTUREFILE
#define AVIF_WASCAPTUREFILE 0x10000
Definition at line 187 of file vfw.h.
AVIFILECAPS_ALLKEYFRAMES
#define AVIFILECAPS_ALLKEYFRAMES 0x10
Definition at line 209 of file vfw.h.
AVIFILECAPS_CANREAD
#define AVIFILECAPS_CANREAD 0x01
Definition at line 207 of file vfw.h.
AVIFILECAPS_CANWRITE
#define AVIFILECAPS_CANWRITE 0x02
Definition at line 208 of file vfw.h.
AVIFILECAPS_NOCOMPRESSION
#define AVIFILECAPS_NOCOMPRESSION 0x20
Definition at line 210 of file vfw.h.
AVIFileClose
#define AVIFileClose (pavi) AVIFileRelease(pavi)
Definition at line 948 of file vfw.h.
AVIFileCreateStream
#define AVIFileCreateStream AVIFileCreateStreamA
Definition at line 1342 of file vfw.h.
AVIFILEINFO
#define AVIFILEINFO AVIFILEINFOA
Definition at line 1331 of file vfw.h.
AVIFileInfo
#define AVIFileInfo AVIFileInfoA
Definition at line 1341 of file vfw.h.
AVIFILEINFO_COPYRIGHTED
#define AVIFILEINFO_COPYRIGHTED 0x20000
Definition at line 206 of file vfw.h.
AVIFILEINFO_HASINDEX
#define AVIFILEINFO_HASINDEX 0x10
Definition at line 201 of file vfw.h.
AVIFILEINFO_ISINTERLEAVED
#define AVIFILEINFO_ISINTERLEAVED 0x100
Definition at line 203 of file vfw.h.
AVIFILEINFO_MUSTUSEINDEX
#define AVIFILEINFO_MUSTUSEINDEX 0x20
Definition at line 202 of file vfw.h.
AVIFILEINFO_TRUSTCKTYPE
#define AVIFILEINFO_TRUSTCKTYPE 0x800
Definition at line 204 of file vfw.h.
AVIFILEINFO_WASCAPTUREFILE
#define AVIFILEINFO_WASCAPTUREFILE 0x10000
Definition at line 205 of file vfw.h.
AVIFileOpen
#define AVIFileOpen AVIFileOpenA
Definition at line 1340 of file vfw.h.
AVIGETFRAMEF_BESTDISPLAYFMT
#define AVIGETFRAMEF_BESTDISPLAYFMT 1
Definition at line 198 of file vfw.h.
AVIIF_COMPUSE
#define AVIIF_COMPUSE 0xfff0000
Definition at line 196 of file vfw.h.
AVIIF_KEYFRAME [1/2]
#define AVIIF_KEYFRAME 0x10
Definition at line 197 of file vfw.h.
AVIIF_KEYFRAME [2/2]
#define AVIIF_KEYFRAME 0x10
Definition at line 197 of file vfw.h.
AVIIF_LIST
#define AVIIF_LIST 0x01
Definition at line 192 of file vfw.h.
AVIIF_NOTIME
#define AVIIF_NOTIME 0x100
Definition at line 195 of file vfw.h.
AVIIF_TWOCC
#define AVIIF_TWOCC 0x02
Definition at line 193 of file vfw.h.
AVISaveV
#define AVISaveV AVISaveVA
Definition at line 1337 of file vfw.h.
AVISF_DISABLED
#define AVISF_DISABLED 0x01
Definition at line 190 of file vfw.h.
AVISF_VIDEO_PALCHANGES
#define AVISF_VIDEO_PALCHANGES 0x10000
Definition at line 191 of file vfw.h.
AVIStreamClose
#define AVIStreamClose (pavi) AVIStreamRelease(pavi);
Definition at line 949 of file vfw.h.
AVIStreamEnd
#define AVIStreamEnd (pavi) (AVIStreamStart(pavi)+AVIStreamLength(pavi))
Definition at line 950 of file vfw.h.
AVIStreamEndTime
#define AVIStreamEndTime (pavi) AVIStreamSampleToTime(pavi,AVIStreamEnd(pavi))
Definition at line 951 of file vfw.h.
AVIStreamFormatSize
#define AVIStreamFormatSize (pavi, lPos, plSize) AVIStreamReadFormat(pavi,lPos,NULL,plSize)
Definition at line 952 of file vfw.h.
AVISTREAMINFO
#define AVISTREAMINFO AVISTREAMINFOA
Definition at line 1328 of file vfw.h.
AVIStreamInfo
#define AVIStreamInfo AVIStreamInfoA
Definition at line 1334 of file vfw.h.
AVISTREAMINFO_DISABLED
#define AVISTREAMINFO_DISABLED 0x01
Definition at line 199 of file vfw.h.
AVISTREAMINFO_FORMATCHANGES
#define AVISTREAMINFO_FORMATCHANGES 0x10000
Definition at line 200 of file vfw.h.
AVIStreamIsKeyFrame
#define AVIStreamIsKeyFrame (pavi, pos) (AVIStreamNearestKeyFrame(pavi,pos) == pos)
Definition at line 963 of file vfw.h.
AVIStreamLengthTime
#define AVIStreamLengthTime (pavi) AVIStreamSampleToTime(pavi,AVIStreamLength(pavi))
Definition at line 953 of file vfw.h.
AVIStreamNearestKeyFrame
#define AVIStreamNearestKeyFrame (pavi, pos) AVIStreamFindSample(pavi,pos,FIND_PREV|FIND_KEY)
Definition at line 962 of file vfw.h.
AVIStreamNearestSample
#define AVIStreamNearestSample (pavi, pos) AVIStreamFindSample(pavi,pos,FIND_PREV|FIND_ANY)
Definition at line 959 of file vfw.h.
AVIStreamNextSample
#define AVIStreamNextSample (pavi, pos) AVIStreamFindSample(pavi,pos+1,FIND_NEXT|FIND_ANY)
Definition at line 957 of file vfw.h.
AVIStreamOpenFromFile
#define AVIStreamOpenFromFile AVIStreamOpenFromFileA
Definition at line 1335 of file vfw.h.
AVIStreamPrevSample
#define AVIStreamPrevSample (pavi, pos) AVIStreamFindSample(pavi,pos-1,FIND_PREV|FIND_ANY)
Definition at line 958 of file vfw.h.
AVIStreamSampleSize
#define AVIStreamSampleSize (pavi, pos, psize) AVIStreamRead(pavi,pos,1,NULL,0,psize,NULL)
Definition at line 954 of file vfw.h.
AVIStreamSampleToSample
#define AVIStreamSampleToSample (pavi1, pavi2, samp2) AVIStreamTimeToSample(pavi1,AVIStreamSampleToTime(pavi2,samp2))
Definition at line 955 of file vfw.h.
AVIStreamStartTime
#define AVIStreamStartTime (pavi) AVIStreamSampleToTime(pavi,AVIStreamStart(pavi))
Definition at line 956 of file vfw.h.
aviTWOCC
#define aviTWOCC (ch0, ch1) ((WORD)(BYTE)(ch0)|((WORD)(BYTE)(ch1)<<8))
Definition at line 364 of file vfw.h.
AVStreamNextKeyFrame
#define AVStreamNextKeyFrame (pavi, pos) AVIStreamFindSample(pavi,pos+1,FIND_NEXT|FIND_KEY)
Definition at line 960 of file vfw.h.
AVStreamPrevKeyFrame
#define AVStreamPrevKeyFrame (pavi, pos) AVIStreamFindSample(pavi,pos-1,FIND_NEXT|FIND_KEY)
Definition at line 961 of file vfw.h.
capCaptureAbort
#define capCaptureAbort (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_ABORT,0,0))
Definition at line 1275 of file vfw.h.
capCaptureGetSetup
#define capCaptureGetSetup (hwnd, s, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_GET_SEQUENCE_SETUP,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPCAPTUREPARMS)(s)))
Definition at line 1271 of file vfw.h.
capCaptureSequence
#define capCaptureSequence (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SEQUENCE,0,0))
Definition at line 1268 of file vfw.h.
capCaptureSequenceNoFile
#define capCaptureSequenceNoFile (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SEQUENCE_NOFILE,0,0))
Definition at line 1269 of file vfw.h.
capCaptureSetSetup
#define capCaptureSetSetup (hwnd, s, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_SEQUENCE_SETUP,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPCAPTUREPARMS)(s)))
Definition at line 1270 of file vfw.h.
capCaptureSingleFrame
#define capCaptureSingleFrame (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SINGLE_FRAME,0,0))
Definition at line 1278 of file vfw.h.
capCaptureSingleFrameClose
#define capCaptureSingleFrameClose (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SINGLE_FRAME_CLOSE,0,0))
Definition at line 1277 of file vfw.h.
capCaptureSingleFrameOpen
#define capCaptureSingleFrameOpen (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_SINGLE_FRAME_OPEN,0,0))
Definition at line 1276 of file vfw.h.
capCaptureStop
#define capCaptureStop (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_STOP,0,0))
Definition at line 1274 of file vfw.h.
capCreateCaptureWindow
#define capCreateCaptureWindow capCreateCaptureWindowA
Definition at line 1359 of file vfw.h.
capDlgVideoCompression
#define capDlgVideoCompression (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DLG_VIDEOCOMPRESSION,0,0))
Definition at line 1259 of file vfw.h.
capDlgVideoDisplay
#define capDlgVideoDisplay (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DLG_VIDEODISPLAY,0,0))
Definition at line 1255 of file vfw.h.
capDlgVideoFormat
#define capDlgVideoFormat (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DLG_VIDEOFORMAT,0,0))
Definition at line 1253 of file vfw.h.
capDlgVideoSource
#define capDlgVideoSource (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DLG_VIDEOSOURCE,0,0))
Definition at line 1254 of file vfw.h.
capDriverConnect
#define capDriverConnect (hwnd, i) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_CONNECT,(WPARAM)(i),0))
Definition at line 1238 of file vfw.h.
capDriverDisconnect
#define capDriverDisconnect (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_DISCONNECT,0,0))
Definition at line 1239 of file vfw.h.
capDriverGetCaps
#define capDriverGetCaps (hwnd, psCaps, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_GET_CAPS,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPCAPDRIVERCAPS)(psCaps)))
Definition at line 1242 of file vfw.h.
capDriverGetName
#define capDriverGetName (hwnd, szName, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_GET_NAME,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1240 of file vfw.h.
capDriverGetVersion
#define capDriverGetVersion (hwnd, szVer, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_DRIVER_GET_VERSION,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPTSTR)(szVer)))
Definition at line 1241 of file vfw.h.
capEditCopy
#define capEditCopy (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_EDIT_COPY,0,0))
Definition at line 1249 of file vfw.h.
capFileAlloc
#define capFileAlloc (hwnd, dwSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_ALLOCATE,0,(LPARAM)(DWORD)(dwSize)))
Definition at line 1245 of file vfw.h.
capFileGetCaptureFile
#define capFileGetCaptureFile (hwnd, szName, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_GET_CAPTURE_FILE,(WPARAM)(wSize), (LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1244 of file vfw.h.
capFileSaveAs
#define capFileSaveAs (hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_SAVEAS,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1246 of file vfw.h.
capFileSaveDIB
#define capFileSaveDIB (hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_SAVEDIB,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1248 of file vfw.h.
capFileSetCaptureFile
#define capFileSetCaptureFile (hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_SET_CAPTURE_FILE,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1243 of file vfw.h.
capFileSetInfoChunk
#define capFileSetInfoChunk (hwnd, lpInfoChunk) ((BOOL) __capSendMessage(hwnd,WM_CAP_FILE_SET_INFOCHUNK,0,(LPARAM)(LPCAPINFOCHUNK)(lpInfoChunk)))
Definition at line 1247 of file vfw.h.
capGetAudioFormat
#define capGetAudioFormat (hwnd, psAudioFormat, wSize) ((DWORD)__capSendMessage(hwnd,WM_CAP_GET_AUDIOFORMAT,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPWAVEFORMATEX)(psAudioFormat)))
Definition at line 1251 of file vfw.h.
capGetAudioFormatSize
#define capGetAudioFormatSize (hwnd) ((DWORD)__capSendMessage(hwnd,WM_CAP_GET_AUDIOFORMAT,0,0))
Definition at line 1252 of file vfw.h.
capGetDriverDescription
#define capGetDriverDescription capGetDriverDescriptionA
Definition at line 1360 of file vfw.h.
capGetMCIDeviceName
#define capGetMCIDeviceName (hwnd, szName, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_GET_MCI_DEVICE,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1273 of file vfw.h.
capGetStatus
#define capGetStatus (hwnd, s, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_GET_STATUS,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPCAPSTATUS)(s)))
Definition at line 1264 of file vfw.h.
capGetUserData
#define capGetUserData (hwnd) ((LONG) __capSendMessage(hwnd,WM_CAP_GET_USER_DATA,0,0))
Definition at line 1236 of file vfw.h.
capGetVideoFormat
#define capGetVideoFormat (hwnd, psVideoFormat, wSize) ((DWORD)__capSendMessage(hwnd,WM_CAP_GET_VIDEOFORMAT,(WPARAM)(wSize),(LPARAM)(LPVOID)(psVideoFormat)))
Definition at line 1256 of file vfw.h.
capGetVideoFormatSize
#define capGetVideoFormatSize (hwnd) ((DWORD)__capSendMessage(hwnd,WM_CAP_GET_VIDEOFORMAT,0,0))
Definition at line 1257 of file vfw.h.
capGrabFrame
#define capGrabFrame (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_GRAB_FRAME,0,0))
Definition at line 1266 of file vfw.h.
capGrabFrameNoStop
#define capGrabFrameNoStop (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_GRAB_FRAME_NOSTOP,0,0))
Definition at line 1267 of file vfw.h.
capOverlay
#define capOverlay (hwnd, f) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_OVERLAY,(WPARAM)(BOOL)(f),0))
Definition at line 1261 of file vfw.h.
capPaletteAuto
#define capPaletteAuto (hwnd, iFrames, iColors) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_AUTOCREATE,(WPARAM)(iFrames),(LPARAM)(DWORD)(iColors)))
Definition at line 1282 of file vfw.h.
capPaletteManual
#define capPaletteManual (hwnd, fGrab, iColors) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_MANUALCREATE,(WPARAM)(fGrab),(LPARAM)(DWORD)(iColors)))
Definition at line 1283 of file vfw.h.
capPaletteOpen
#define capPaletteOpen (hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_OPEN,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1279 of file vfw.h.
capPalettePaste
#define capPalettePaste (hwnd) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_PASTE,0,0))
Definition at line 1281 of file vfw.h.
capPaletteSave
#define capPaletteSave (hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_PAL_SAVE,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1280 of file vfw.h.
capPreview
#define capPreview (hwnd, f) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_PREVIEW,(WPARAM)(BOOL)(f),0))
Definition at line 1260 of file vfw.h.
capPreviewRate
#define capPreviewRate (hwnd, wMS) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_PREVIEWRATE,(WPARAM)(wMS),0))
Definition at line 1262 of file vfw.h.
capPreviewScale
#define capPreviewScale (hwnd, f) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_SCALE,(WPARAM)(BOOL)f,0))
Definition at line 1263 of file vfw.h.
capSetAudioFormat
#define capSetAudioFormat (hwnd, psAudioFormat, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_AUDIOFORMAT,(WPARAM)(wSize),(LPARAM)(LPVOID)(LPWAVEFORMATEX)(psAudioFormat)))
Definition at line 1250 of file vfw.h.
capSetCallbackOnCapControl
#define capSetCallbackOnCapControl (hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_CAPCONTROL,0,(LPARAM)(LPVOID)(fpProc)))
Definition at line 1284 of file vfw.h.
capSetCallbackOnError
#define capSetCallbackOnError (hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_ERROR,0,(LPARAM)(LPVOID)(fpProc)))
Definition at line 1230 of file vfw.h.
capSetCallbackOnFrame
#define capSetCallbackOnFrame (hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_FRAME,0,(LPARAM)(LPVOID)(fpProc)))
Definition at line 1233 of file vfw.h.
capSetCallbackOnStatus
#define capSetCallbackOnStatus (hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_STATUS,0,(LPARAM)(LPVOID)(fpProc)))
Definition at line 1231 of file vfw.h.
capSetCallbackOnVideoStream
#define capSetCallbackOnVideoStream (hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_VIDEOSTREAM,0,(LPARAM)(LPVOID)(fpProc)))
Definition at line 1234 of file vfw.h.
capSetCallbackOnWaveStream
#define capSetCallbackOnWaveStream (hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_WAVESTREAM,0,(LPARAM)(LPVOID)(fpProc)))
Definition at line 1235 of file vfw.h.
capSetCallbackOnYield
#define capSetCallbackOnYield (hwnd, fpProc) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_CALLBACK_YIELD,0,(LPARAM)(LPVOID)(fpProc)))
Definition at line 1232 of file vfw.h.
capSetMCIDeviceName
#define capSetMCIDeviceName (hwnd, szName) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_MCI_DEVICE,0,(LPARAM)(LPVOID)(LPTSTR)(szName)))
Definition at line 1272 of file vfw.h.
capSetScrollPos
#define capSetScrollPos (hwnd, lpP) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_SCROLL,0,(LPARAM)(LPPOINT)(lpP)))
Definition at line 1265 of file vfw.h.
capSetUserData
#define capSetUserData (hwnd, lUser) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_USER_DATA,0,(LPARAM)lUser))
Definition at line 1237 of file vfw.h.
capSetVideoFormat
#define capSetVideoFormat (hwnd, psVideoFormat, wSize) ((BOOL) __capSendMessage(hwnd,WM_CAP_SET_VIDEOFORMAT,(WPARAM)(wSize),(LPARAM)(LPVOID)(psVideoFormat)))
Definition at line 1258 of file vfw.h.
ckidAVIMAINHDR
#define ckidAVIMAINHDR mmioFOURCC('a','v','i','h')
Definition at line 159 of file vfw.h.
ckidAVINEWINDEX
#define ckidAVINEWINDEX mmioFOURCC('i', 'd', 'x', '1')
Definition at line 167 of file vfw.h.
ckidAVIPADDING
#define ckidAVIPADDING mmioFOURCC('J','U','N','K')
Definition at line 177 of file vfw.h.
ckidSTREAMFORMAT
#define ckidSTREAMFORMAT mmioFOURCC('s','t','r','f')
Definition at line 162 of file vfw.h.
ckidSTREAMHANDLERDATA
#define ckidSTREAMHANDLERDATA mmioFOURCC('s','t','r','d')
Definition at line 163 of file vfw.h.
ckidSTREAMHEADER
#define ckidSTREAMHEADER mmioFOURCC('s','t','r','h')
Definition at line 161 of file vfw.h.
ckidSTREAMNAME
#define ckidSTREAMNAME mmioFOURCC('s','t','r','n')
Definition at line 164 of file vfw.h.
cktypeDIBbits
#define cktypeDIBbits aviTWOCC('d','b')
Definition at line 173 of file vfw.h.
cktypeDIBcompressed
#define cktypeDIBcompressed aviTWOCC('d','c')
Definition at line 174 of file vfw.h.
cktypePALchange
#define cktypePALchange aviTWOCC('p','c')
Definition at line 175 of file vfw.h.
cktypeWAVEbytes
#define cktypeWAVEbytes aviTWOCC('w','b')
Definition at line 176 of file vfw.h.
DDF_ANIMATE
#define DDF_ANIMATE 0x20
Definition at line 344 of file vfw.h.
DDF_BACKGROUNDPAL
#define DDF_BACKGROUNDPAL 0x200
Definition at line 348 of file vfw.h.
DDF_BUFFER
#define DDF_BUFFER 0x40
Definition at line 345 of file vfw.h.
DDF_DONTDRAW
#define DDF_DONTDRAW 0x10
Definition at line 343 of file vfw.h.
DDF_FULLSCREEN
#define DDF_FULLSCREEN 0x100
Definition at line 347 of file vfw.h.
DDF_HALFTONE
#define DDF_HALFTONE 0x1000
Definition at line 351 of file vfw.h.
DDF_HURRYUP
#define DDF_HURRYUP 0x800
Definition at line 350 of file vfw.h.
DDF_JUSTDRAWIT
#define DDF_JUSTDRAWIT 0x80
Definition at line 346 of file vfw.h.
DDF_NOTKEYFRAME
#define DDF_NOTKEYFRAME 0x400
Definition at line 349 of file vfw.h.
DDF_PREROLL
#define DDF_PREROLL DDF_DONTDRAW
Definition at line 352 of file vfw.h.
DDF_SAME_DIB
#define DDF_SAME_DIB DDF_SAME_DRAW
Definition at line 353 of file vfw.h.
DDF_SAME_DRAW
#define DDF_SAME_DRAW 0x08
Definition at line 342 of file vfw.h.
DDF_SAME_HDC
#define DDF_SAME_HDC 0x04
Definition at line 341 of file vfw.h.
DDF_SAME_SIZE
#define DDF_SAME_SIZE DDF_SAME_DRAW
Definition at line 354 of file vfw.h.
DDF_UPDATE
#define DDF_UPDATE 0x02
Definition at line 340 of file vfw.h.
DEFINE_AVIGUID
#define DEFINE_AVIGUID (name, l, w1, w2) DEFINE_GUID(name,l,w1,w2,0xC0,0,0,0,0,0,0,0x46)
Definition at line 711 of file vfw.h.
DrawDibUpdate
#define DrawDibUpdate (hdd, hdc, x, y) DrawDibDraw(hdd,hdc,x,y,0,0,NULL,NULL,0,0,0,0,DDF_UPDATE)
Definition at line 1039 of file vfw.h.
EditStreamSetInfo
#define EditStreamSetInfo EditStreamSetInfoA
Definition at line 1338 of file vfw.h.
EditStreamSetName
#define EditStreamSetName EditStreamSetNameA
Definition at line 1339 of file vfw.h.
FIND_ANY
#define FIND_ANY 0x00000020L
Definition at line 221 of file vfw.h.
FIND_DIR
#define FIND_DIR 0x0000000fL
Definition at line 215 of file vfw.h.
FIND_FORMAT
#define FIND_FORMAT 0x00000040L
Definition at line 222 of file vfw.h.
FIND_FROM_START
#define FIND_FROM_START 0x00000008L
Definition at line 218 of file vfw.h.
FIND_INDEX
#define FIND_INDEX 0x00004000L
Definition at line 228 of file vfw.h.
FIND_KEY
#define FIND_KEY 0x00000010L
Definition at line 220 of file vfw.h.
FIND_LENGTH
#define FIND_LENGTH 0x00001000L
Definition at line 225 of file vfw.h.
FIND_NEXT
#define FIND_NEXT 0x00000001L
Definition at line 216 of file vfw.h.
FIND_OFFSET
#define FIND_OFFSET 0x00002000L
Definition at line 226 of file vfw.h.
FIND_POS
#define FIND_POS 0x00000000L
Definition at line 224 of file vfw.h.
FIND_PREV
#define FIND_PREV 0x00000004L
Definition at line 217 of file vfw.h.
FIND_RET
#define FIND_RET 0x0000f000L
Definition at line 223 of file vfw.h.
FIND_SIZE
#define FIND_SIZE 0x00003000L
Definition at line 227 of file vfw.h.
FIND_TYPE
#define FIND_TYPE 0x000000f0L
Definition at line 219 of file vfw.h.
formtypeAVI
#define formtypeAVI mmioFOURCC('A','V','I',' ')
Definition at line 157 of file vfw.h.
FromHex
#define FromHex (n) (((n)>='A')?((n)+10-'A'):((n)-'0'))
Definition at line 178 of file vfw.h.
GetOpenFileNamePreview
#define GetOpenFileNamePreview GetOpenFileNamePreviewA
Definition at line 1343 of file vfw.h.
GetSaveFileNamePreview
#define GetSaveFileNamePreview GetSaveFileNamePreviewA
Definition at line 1344 of file vfw.h.
ICAbout
#define ICAbout (hic, hwnd) ICSendMessage(hic,ICM_ABOUT,(DWORD)(hwnd),0)
Definition at line 918 of file vfw.h.
ICCOMPRESS_KEYFRAME
#define ICCOMPRESS_KEYFRAME 0x01
Definition at line 101 of file vfw.h.
ICCompressBegin
#define ICCompressBegin (hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_COMPRESS_BEGIN,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
Definition at line 913 of file vfw.h.
ICCompressEnd
#define ICCompressEnd (hic) ICSendMessage(hic,ICM_COMPRESS_END,0,0)
Definition at line 916 of file vfw.h.
ICCOMPRESSFRAMES_PADDING
#define ICCOMPRESSFRAMES_PADDING 0x01
Definition at line 45 of file vfw.h.
ICCompressGetFormat
#define ICCompressGetFormat (hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_COMPRESS_GET_FORMAT,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
Definition at line 911 of file vfw.h.
ICCompressGetFormatSize
#define ICCompressGetFormatSize (hic, lpbi) ICCompressGetFormat(hic,lpbi,NULL)
Definition at line 912 of file vfw.h.
ICCompressGetSize
#define ICCompressGetSize (hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_COMPRESS_GET_SIZE,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
Definition at line 914 of file vfw.h.
ICCompressQuery
#define ICCompressQuery (hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_COMPRESS_QUERY,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
Definition at line 915 of file vfw.h.
ICConfigure
#define ICConfigure (hic, hwnd) ICSendMessage(hic,ICM_CONFIGURE,(DWORD)(hwnd),0)
Definition at line 920 of file vfw.h.
ICDECOMPRESS_HURRYUP
#define ICDECOMPRESS_HURRYUP 0x80000000
Definition at line 126 of file vfw.h.
ICDECOMPRESS_NOTKEYFRAME
#define ICDECOMPRESS_NOTKEYFRAME 0x8000000
Definition at line 130 of file vfw.h.
ICDECOMPRESS_NULLFRAME
#define ICDECOMPRESS_NULLFRAME 0x10000000
Definition at line 129 of file vfw.h.
ICDECOMPRESS_PREROLL
#define ICDECOMPRESS_PREROLL 0x20000000
Definition at line 128 of file vfw.h.
ICDECOMPRESS_UPDATE
#define ICDECOMPRESS_UPDATE 0x40000000
Definition at line 127 of file vfw.h.
ICDecompressBegin
#define ICDecompressBegin (hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_DECOMPRESS_BEGIN,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
Definition at line 921 of file vfw.h.
ICDecompressEnd
#define ICDecompressEnd (hic) ICSendMessage(hic,ICM_DECOMPRESS_END,0,0)
Definition at line 927 of file vfw.h.
ICDecompressExEnd
#define ICDecompressExEnd (hic) ICSendMessage(hic,ICM_DECOMPRESSEX_END,0,0)
Definition at line 928 of file vfw.h.
ICDecompressGetFormat
#define ICDecompressGetFormat (hic, lpbiInput, lpbiOutput) (LONG)ICSendMessage(hic,ICM_DECOMPRESS_GET_FORMAT,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
Definition at line 923 of file vfw.h.
ICDecompressGetFormatSize
#define ICDecompressGetFormatSize (hic, lpbi) ICDecompressGetFormat(hic, lpbi, NULL)
Definition at line 924 of file vfw.h.
ICDecompressGetPalette
#define ICDecompressGetPalette (hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_DECOMPRESS_GET_PALETTE,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
Definition at line 925 of file vfw.h.
ICDecompressOpen
#define ICDecompressOpen (fccType, fccHandler, lpbiIn, lpbiOut) ICLocate(fccType,fccHandler,lpbiIn,lpbiOut,ICMODE_DECOMPRESS)
Definition at line 929 of file vfw.h.
ICDecompressQuery
#define ICDecompressQuery (hic, lpbiInput, lpbiOutput) ICSendMessage(hic,ICM_DECOMPRESS_QUERY,(DWORD)(lpbiInput),(DWORD)(lpbiOutput))
Definition at line 922 of file vfw.h.
ICDecompressSetPalette
#define ICDecompressSetPalette (hic, lpbiPalette) ICSendMessage(hic,ICM_DECOMPRESS_SET_PALETTE,(DWORD)(lpbiPalette),0)
Definition at line 926 of file vfw.h.
ICDRAW_ANIMATE
#define ICDRAW_ANIMATE 0x08L
Definition at line 134 of file vfw.h.
ICDRAW_BUFFER
#define ICDRAW_BUFFER 0x100L
Definition at line 139 of file vfw.h.
ICDRAW_CONTINUE
#define ICDRAW_CONTINUE 0x10L
Definition at line 135 of file vfw.h.
ICDRAW_FULLSCREEN
#define ICDRAW_FULLSCREEN 0x02L
Definition at line 132 of file vfw.h.
ICDRAW_HDC
#define ICDRAW_HDC 0x04L
Definition at line 133 of file vfw.h.
ICDRAW_HURRYUP
#define ICDRAW_HURRYUP 0x80000000L
Definition at line 145 of file vfw.h.
ICDRAW_MEMORYDC
#define ICDRAW_MEMORYDC 0x20L
Definition at line 136 of file vfw.h.
ICDRAW_NOTKEYFRAME
#define ICDRAW_NOTKEYFRAME 0x8000000L
Definition at line 149 of file vfw.h.
ICDRAW_NULLFRAME
#define ICDRAW_NULLFRAME 0x10000000L
Definition at line 148 of file vfw.h.
ICDRAW_PREROLL
#define ICDRAW_PREROLL 0x20000000L
Definition at line 147 of file vfw.h.
ICDRAW_QUERY
#define ICDRAW_QUERY 0x01L
Definition at line 131 of file vfw.h.
ICDRAW_RENDER
#define ICDRAW_RENDER 0x80L
Definition at line 138 of file vfw.h.
ICDRAW_UPDATE
#define ICDRAW_UPDATE 0x40000000L
Definition at line 146 of file vfw.h.
ICDRAW_UPDATING
#define ICDRAW_UPDATING 0x40L
Definition at line 137 of file vfw.h.
ICDrawChangePalette
#define ICDrawChangePalette (hic, lpbiInput) ICSendMessage(hic,ICM_DRAW_CHANGEPALETTE,(DWORD)(lpbiInput),0)
Definition at line 936 of file vfw.h.
ICDrawEnd
#define ICDrawEnd (hic) ICSendMessage(hic,ICM_DRAW_END,0,0)
Definition at line 938 of file vfw.h.
ICDrawFlush
#define ICDrawFlush (hic) ICSendMessage(hic,ICM_DRAW_FLUSH,0,0)
Definition at line 946 of file vfw.h.
ICDrawGetTime
#define ICDrawGetTime (hic, lplTime) ICSendMessage(hic,ICM_DRAW_GETTIME,(DWORD)(lplTime),0)
Definition at line 943 of file vfw.h.
ICDrawOpen
#define ICDrawOpen (fccType, fccHandler, lpbiIn) ICLocate(fccType,fccHandler,lpbiIn,NULL,ICMODE_DRAW)
Definition at line 930 of file vfw.h.
ICDrawQuery
#define ICDrawQuery (hic, lpbiInput) ICSendMessage(hic,ICM_DRAW_QUERY,(DWORD)(lpbiInput),0)
Definition at line 935 of file vfw.h.
ICDrawRealize
#define ICDrawRealize (hic, hdc, fBackground) ICSendMessage(hic,ICM_DRAW_REALIZE,(DWORD)(hdc),(DWORD)(fBackground))
Definition at line 945 of file vfw.h.
ICDrawRenderBuffer
#define ICDrawRenderBuffer (hic) ICSendMessage(hic,ICM_DRAW_RENDERBUFFER,0,0)
Definition at line 947 of file vfw.h.
ICDrawSetTime
#define ICDrawSetTime (hic, lTime) ICSendMessage(hic,ICM_DRAW_SETTIME,(DWORD)lTime,0)
Definition at line 944 of file vfw.h.
ICDrawStart
#define ICDrawStart (hic) ICSendMessage(hic,ICM_DRAW_START,0,0)
Definition at line 939 of file vfw.h.
ICDrawStartPlay
#define ICDrawStartPlay (hic, lFrom, lTo) ICSendMessage(hic,ICM_DRAW_START_PLAY,(DWORD)(lFrom),(DWORD)(lTo))
Definition at line 940 of file vfw.h.
ICDrawStop
#define ICDrawStop (hic) ICSendMessage(hic,ICM_DRAW_STOP,0,0)
Definition at line 941 of file vfw.h.
ICDrawStopPlay
#define ICDrawStopPlay (hic) ICSendMessage(hic,ICM_DRAW_STOP_PLAY,0,0)
Definition at line 942 of file vfw.h.
ICDrawWindow
#define ICDrawWindow (hic, prc) ICSendMessage(hic,ICM_DRAW_WINDOW,(DWORD)(prc),sizeof(RECT))
Definition at line 934 of file vfw.h.
ICERR_ABORT
#define ICERR_ABORT -10
Definition at line 40 of file vfw.h.
ICERR_BADBITDEPTH
#define ICERR_BADBITDEPTH -200
Definition at line 42 of file vfw.h.
ICERR_BADFLAGS
#define ICERR_BADFLAGS -5
Definition at line 35 of file vfw.h.
ICERR_BADFORMAT
#define ICERR_BADFORMAT -2
Definition at line 32 of file vfw.h.
ICERR_BADHANDLE
#define ICERR_BADHANDLE -8
Definition at line 38 of file vfw.h.
ICERR_BADIMAGESIZE
#define ICERR_BADIMAGESIZE -201
Definition at line 43 of file vfw.h.
ICERR_BADPARAM
#define ICERR_BADPARAM -6
Definition at line 36 of file vfw.h.
ICERR_BADSIZE
#define ICERR_BADSIZE -7
Definition at line 37 of file vfw.h.
ICERR_CANTUPDATE
#define ICERR_CANTUPDATE -9
Definition at line 39 of file vfw.h.
ICERR_CUSTOM
#define ICERR_CUSTOM -400
Definition at line 44 of file vfw.h.
ICERR_DONTDRAW
#define ICERR_DONTDRAW 1
Definition at line 27 of file vfw.h.
ICERR_ERROR
#define ICERR_ERROR -100
Definition at line 41 of file vfw.h.
ICERR_GOTOKEYFRAME
#define ICERR_GOTOKEYFRAME 3
Definition at line 29 of file vfw.h.
ICERR_INTERNAL
#define ICERR_INTERNAL -4
Definition at line 34 of file vfw.h.
ICERR_MEMORY
#define ICERR_MEMORY -3
Definition at line 33 of file vfw.h.
ICERR_NEWPALETTE
#define ICERR_NEWPALETTE 2
Definition at line 28 of file vfw.h.
ICERR_OK
#define ICERR_OK 0
Definition at line 26 of file vfw.h.
ICERR_STOPDRAWING
#define ICERR_STOPDRAWING 4
Definition at line 30 of file vfw.h.
ICERR_UNSUPPORTED
#define ICERR_UNSUPPORTED -1
Definition at line 31 of file vfw.h.
ICGetBuffersWanted
#define ICGetBuffersWanted (hic, lpdwBuffers) ICSendMessage(hic,ICM_GETBUFFERSWANTED,(DWORD)(lpdwBuffers),0)
Definition at line 937 of file vfw.h.
ICGetState
#define ICGetState (hic, pv, cb) ICSendMessage(hic,ICM_GETSTATE,(DWORD)(pv),(DWORD)(cb))
Definition at line 931 of file vfw.h.
ICGetStateSize
#define ICGetStateSize (hic) ICGetState(hic,NULL,0)
Definition at line 933 of file vfw.h.
ICINSTALL_DRIVER
#define ICINSTALL_DRIVER 0x02
Definition at line 142 of file vfw.h.
ICINSTALL_DRIVERW
#define ICINSTALL_DRIVERW 0x8002
Definition at line 144 of file vfw.h.
ICINSTALL_FUNCTION
#define ICINSTALL_FUNCTION 0x01
Definition at line 141 of file vfw.h.
ICINSTALL_HDRV
#define ICINSTALL_HDRV 0x04
Definition at line 143 of file vfw.h.
ICINSTALL_UNICODE
#define ICINSTALL_UNICODE 0x8000
Definition at line 140 of file vfw.h.
ICM_ABOUT
#define ICM_ABOUT (ICM_RESERVED+11)
Definition at line 54 of file vfw.h.
ICM_COMPRESS
#define ICM_COMPRESS (ICM_USER+8)
Definition at line 66 of file vfw.h.
ICM_COMPRESS_BEGIN
#define ICM_COMPRESS_BEGIN (ICM_USER+7)
Definition at line 65 of file vfw.h.
ICM_COMPRESS_END
#define ICM_COMPRESS_END (ICM_USER+9)
Definition at line 67 of file vfw.h.
ICM_COMPRESS_FRAMES_INFO
#define ICM_COMPRESS_FRAMES_INFO (ICM_USER+70)
Definition at line 98 of file vfw.h.
ICM_COMPRESS_GET_FORMAT
#define ICM_COMPRESS_GET_FORMAT (ICM_USER+4)
Definition at line 62 of file vfw.h.
ICM_COMPRESS_GET_SIZE
#define ICM_COMPRESS_GET_SIZE (ICM_USER+5)
Definition at line 63 of file vfw.h.
ICM_COMPRESS_QUERY
#define ICM_COMPRESS_QUERY (ICM_USER+6)
Definition at line 64 of file vfw.h.
ICM_CONFIGURE
#define ICM_CONFIGURE (ICM_RESERVED+10)
Definition at line 53 of file vfw.h.
ICM_DECOMPRESS
#define ICM_DECOMPRESS (ICM_USER+13)
Definition at line 71 of file vfw.h.
ICM_DECOMPRESS_BEGIN
#define ICM_DECOMPRESS_BEGIN (ICM_USER+12)
Definition at line 70 of file vfw.h.
ICM_DECOMPRESS_END
#define ICM_DECOMPRESS_END (ICM_USER+14)
Definition at line 72 of file vfw.h.
ICM_DECOMPRESS_GET_FORMAT
#define ICM_DECOMPRESS_GET_FORMAT (ICM_USER+10)
Definition at line 68 of file vfw.h.
ICM_DECOMPRESS_GET_PALETTE
#define ICM_DECOMPRESS_GET_PALETTE (ICM_USER+30)
Definition at line 74 of file vfw.h.
ICM_DECOMPRESS_QUERY
#define ICM_DECOMPRESS_QUERY (ICM_USER+11)
Definition at line 69 of file vfw.h.
ICM_DECOMPRESS_SET_PALETTE
#define ICM_DECOMPRESS_SET_PALETTE (ICM_USER+29)
Definition at line 73 of file vfw.h.
ICM_DECOMPRESSEX
#define ICM_DECOMPRESSEX (ICM_USER+62)
Definition at line 96 of file vfw.h.
ICM_DECOMPRESSEX_BEGIN
#define ICM_DECOMPRESSEX_BEGIN (ICM_USER+60)
Definition at line 94 of file vfw.h.
ICM_DECOMPRESSEX_END
#define ICM_DECOMPRESSEX_END (ICM_USER+63)
Definition at line 97 of file vfw.h.
ICM_DECOMPRESSEX_QUERY
#define ICM_DECOMPRESSEX_QUERY (ICM_USER+61)
Definition at line 95 of file vfw.h.
ICM_DRAW
#define ICM_DRAW (ICM_USER+33)
Definition at line 82 of file vfw.h.
ICM_DRAW_BEGIN
#define ICM_DRAW_BEGIN (ICM_USER+15)
Definition at line 76 of file vfw.h.
ICM_DRAW_CHANGEPALETTE
#define ICM_DRAW_CHANGEPALETTE (ICM_USER+51)
Definition at line 91 of file vfw.h.
ICM_DRAW_END
#define ICM_DRAW_END (ICM_USER+21)
Definition at line 80 of file vfw.h.
ICM_DRAW_FLUSH
#define ICM_DRAW_FLUSH (ICM_USER+37)
Definition at line 86 of file vfw.h.
ICM_DRAW_GET_PALETTE
#define ICM_DRAW_GET_PALETTE (ICM_USER+16)
Definition at line 77 of file vfw.h.
ICM_DRAW_GETTIME
#define ICM_DRAW_GETTIME (ICM_USER+32)
Definition at line 81 of file vfw.h.
ICM_DRAW_QUERY
#define ICM_DRAW_QUERY (ICM_USER+31)
Definition at line 75 of file vfw.h.
ICM_DRAW_REALIZE
#define ICM_DRAW_REALIZE (ICM_USER+36)
Definition at line 85 of file vfw.h.
ICM_DRAW_RENDERBUFFER
#define ICM_DRAW_RENDERBUFFER (ICM_USER+38)
Definition at line 87 of file vfw.h.
ICM_DRAW_SETTIME
#define ICM_DRAW_SETTIME (ICM_USER+35)
Definition at line 84 of file vfw.h.
ICM_DRAW_START
#define ICM_DRAW_START (ICM_USER+18)
Definition at line 78 of file vfw.h.
ICM_DRAW_START_PLAY
#define ICM_DRAW_START_PLAY (ICM_USER+39)
Definition at line 88 of file vfw.h.
ICM_DRAW_STOP
#define ICM_DRAW_STOP (ICM_USER+19)
Definition at line 79 of file vfw.h.
ICM_DRAW_STOP_PLAY
#define ICM_DRAW_STOP_PLAY (ICM_USER+40)
Definition at line 89 of file vfw.h.
ICM_DRAW_SUGGESTFORMAT
#define ICM_DRAW_SUGGESTFORMAT (ICM_USER+50)
Definition at line 90 of file vfw.h.
ICM_DRAW_WINDOW
#define ICM_DRAW_WINDOW (ICM_USER+34)
Definition at line 83 of file vfw.h.
ICM_FRAMERATE
#define ICM_FRAMERATE mmioFOURCC('F','r','m','R')
Definition at line 60 of file vfw.h.
ICM_GET
#define ICM_GET (ICM_RESERVED+41)
Definition at line 59 of file vfw.h.
ICM_GETBUFFERSWANTED
#define ICM_GETBUFFERSWANTED (ICM_USER+41)
Definition at line 92 of file vfw.h.
ICM_GETDEFAULTKEYFRAMERATE
#define ICM_GETDEFAULTKEYFRAMERATE (ICM_USER+42)
Definition at line 93 of file vfw.h.
ICM_GETDEFAULTQUALITY
#define ICM_GETDEFAULTQUALITY (ICM_RESERVED+30)
Definition at line 55 of file vfw.h.
ICM_GETINFO
#define ICM_GETINFO (ICM_RESERVED+2)
Definition at line 52 of file vfw.h.
ICM_GETQUALITY
#define ICM_GETQUALITY (ICM_RESERVED+31)
Definition at line 56 of file vfw.h.
ICM_GETSTATE
#define ICM_GETSTATE (ICM_RESERVED+0)
Definition at line 50 of file vfw.h.
ICM_KEYFRAMERATE
#define ICM_KEYFRAMERATE mmioFOURCC('K','e','y','R')
Definition at line 61 of file vfw.h.
ICM_RESERVED
#define ICM_RESERVED ICM_RESERVED_LOW
Definition at line 49 of file vfw.h.
ICM_RESERVED_HIGH
#define ICM_RESERVED_HIGH (DRV_USER+0x2000)
Definition at line 48 of file vfw.h.
ICM_RESERVED_LOW
#define ICM_RESERVED_LOW (DRV_USER+0x1000)
Definition at line 47 of file vfw.h.
ICM_SET
#define ICM_SET (ICM_RESERVED+40)
Definition at line 58 of file vfw.h.
ICM_SET_STATUS_PROC
#define ICM_SET_STATUS_PROC (ICM_USER+72)
Definition at line 99 of file vfw.h.
ICM_SETQUALITY
#define ICM_SETQUALITY (ICM_RESERVED+32)
Definition at line 57 of file vfw.h.
ICM_SETSTATE
#define ICM_SETSTATE (ICM_RESERVED+1)
Definition at line 51 of file vfw.h.
ICM_USER
#define ICM_USER (DRV_USER+0x0000)
Definition at line 46 of file vfw.h.
ICMF_ABOUT_QUERY
#define ICMF_ABOUT_QUERY 0x01
Definition at line 125 of file vfw.h.
ICMF_CHOOSE_ALLCOMPRESSORS
#define ICMF_CHOOSE_ALLCOMPRESSORS 0x08
Definition at line 154 of file vfw.h.
ICMF_CHOOSE_DATARATE
#define ICMF_CHOOSE_DATARATE 0x02
Definition at line 152 of file vfw.h.
ICMF_CHOOSE_KEYFRAME
#define ICMF_CHOOSE_KEYFRAME 0x01
Definition at line 151 of file vfw.h.
ICMF_CHOOSE_PREVIEW
#define ICMF_CHOOSE_PREVIEW 0x04
Definition at line 153 of file vfw.h.
ICMF_COMPVARS_VALID
#define ICMF_COMPVARS_VALID 0x01
Definition at line 150 of file vfw.h.
ICMF_CONFIGURE_QUERY
#define ICMF_CONFIGURE_QUERY 0x01
Definition at line 100 of file vfw.h.
ICMODE_COMPRESS
#define ICMODE_COMPRESS 1
Definition at line 107 of file vfw.h.
ICMODE_DECOMPRESS
#define ICMODE_DECOMPRESS 2
Definition at line 108 of file vfw.h.
ICMODE_DRAW
#define ICMODE_DRAW 8
Definition at line 112 of file vfw.h.
ICMODE_FASTCOMPRESS
#define ICMODE_FASTCOMPRESS 5
Definition at line 111 of file vfw.h.
ICMODE_FASTDECOMPRESS
#define ICMODE_FASTDECOMPRESS 3
Definition at line 109 of file vfw.h.
ICMODE_QUERY
#define ICMODE_QUERY 4
Definition at line 110 of file vfw.h.
ICQUALITY_DEFAULT
#define ICQUALITY_DEFAULT -1
Definition at line 115 of file vfw.h.
ICQUALITY_HIGH
#define ICQUALITY_HIGH 10000
Definition at line 114 of file vfw.h.
ICQUALITY_LOW
#define ICQUALITY_LOW 0
Definition at line 113 of file vfw.h.
ICQueryAbout
#define ICQueryAbout (hic) (ICSendMessage(hic,ICM_ABOUT,(DWORD)-1,ICMF_ABOUT_QUERY)==ICERR_OK)
Definition at line 917 of file vfw.h.
ICQueryConfigure
#define ICQueryConfigure (hic) (ICSendMessage(hic,ICM_CONFIGURE,(DWORD)-1,ICMF_CONFIGURE_QUERY)==ICERR_OK)
Definition at line 919 of file vfw.h.
ICSetState
#define ICSetState (hic, pv, cb) ICSendMessage(hic,ICM_SETSTATE,(DWORD)(pv),(DWORD)(cb))
Definition at line 932 of file vfw.h.
ICSTATUS_END
#define ICSTATUS_END 2
Definition at line 104 of file vfw.h.
ICSTATUS_ERROR
#define ICSTATUS_ERROR 3
Definition at line 105 of file vfw.h.
ICSTATUS_START
#define ICSTATUS_START 0
Definition at line 102 of file vfw.h.
ICSTATUS_STATUS
#define ICSTATUS_STATUS 1
Definition at line 103 of file vfw.h.
ICSTATUS_YIELD
#define ICSTATUS_YIELD 4
Definition at line 106 of file vfw.h.
ICTYPE_AUDIO
#define ICTYPE_AUDIO mmioFOURCC('a','u','d','c')
Definition at line 156 of file vfw.h.
ICTYPE_VIDEO
#define ICTYPE_VIDEO mmioFOURCC('v','i','d','c')
Definition at line 155 of file vfw.h.
INTERFACE [1/5]
#define INTERFACE IAVIStream
Definition at line 784 of file vfw.h.
INTERFACE [2/5]
#define INTERFACE IAVIStreaming
Definition at line 784 of file vfw.h.
INTERFACE [3/5]
#define INTERFACE IAVIEditStream
Definition at line 784 of file vfw.h.
INTERFACE [4/5]
#define INTERFACE IAVIFile
Definition at line 784 of file vfw.h.
INTERFACE [5/5]
#define INTERFACE IGetFrame
Definition at line 784 of file vfw.h.
listtypeAVIHEADER
#define listtypeAVIHEADER mmioFOURCC('h','d','r','l')
Definition at line 158 of file vfw.h.
listtypeAVIMOVIE
#define listtypeAVIMOVIE mmioFOURCC('m','o','v','i')
Definition at line 165 of file vfw.h.
listtypeAVIRECORD
#define listtypeAVIRECORD mmioFOURCC('r','e','c',' ')
Definition at line 166 of file vfw.h.
listtypeSTREAMHEADER
#define listtypeSTREAMHEADER mmioFOURCC('s','t','r','l')
Definition at line 160 of file vfw.h.
LPAVIFILEINFO
#define LPAVIFILEINFO LPAVIFILEINFOA
Definition at line 1333 of file vfw.h.
LPAVISTREAMINFO
#define LPAVISTREAMINFO LPAVISTREAMINFOA
Definition at line 1329 of file vfw.h.
MAKE_AVIERR
#define MAKE_AVIERR (e) MAKE_SCODE(SEVERITY_ERROR,FACILITY_ITF,0x4000+e)
Definition at line 230 of file vfw.h.
MAKEAVICKID
#define MAKEAVICKID (tcc, stream) MAKELONG((ToHex((stream)&0x0f)<<8)|(ToHex(((stream)&0xf0)>>4)),tcc)
Definition at line 182 of file vfw.h.
MCIWND_END
#define MCIWND_END -2
Definition at line 339 of file vfw.h.
MCIWND_START
#define MCIWND_START -1
Definition at line 338 of file vfw.h.
MCIWndCanConfig
#define MCIWndCanConfig (hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_CONFIG,0,0)
Definition at line 974 of file vfw.h.
MCIWndCanEject
#define MCIWndCanEject (hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_EJECT,0,0)
Definition at line 973 of file vfw.h.
MCIWndCanPlay
#define MCIWndCanPlay (hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_PLAY,0,0)
Definition at line 969 of file vfw.h.
MCIWndCanRecord
#define MCIWndCanRecord (hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_RECORD,0,0)
Definition at line 970 of file vfw.h.
MCIWndCanSave
#define MCIWndCanSave (hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_SAVE,0,0)
Definition at line 971 of file vfw.h.
MCIWndCanWindow
#define MCIWndCanWindow (hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_CAN_WINDOW,0,0)
Definition at line 972 of file vfw.h.
MCIWndChangeStyles
#define MCIWndChangeStyles (hWnd, mask, value) (LONG)MCIWndSM(hWnd,MCIWNDM_CHANGESTYLES,(WPARAM)(UINT)(mask),(LPARAM)(LONG)(value))
Definition at line 1036 of file vfw.h.
MCIWndClose
#define MCIWndClose (hWnd) (LONG)MCIWndSM(hWnd,MCI_CLOSE,0,0)
Definition at line 982 of file vfw.h.
MCIWndCreate
#define MCIWndCreate MCIWndCreateA
Definition at line 1345 of file vfw.h.
MCIWndDestroy
#define MCIWndDestroy (hWnd) (VOID)MCIWndSM(hWnd,WM_CLOSE,0,0)
Definition at line 1008 of file vfw.h.
MCIWndEject
#define MCIWndEject (hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_EJECT,0,0)
Definition at line 988 of file vfw.h.
MCIWndEnd
#define MCIWndEnd (hWnd) MCIWndSeek(hWnd,MCIWND_END)
Definition at line 990 of file vfw.h.
MCIWNDF_NOAUTOSIZEMOVIE
#define MCIWNDF_NOAUTOSIZEMOVIE 0x0004
Definition at line 253 of file vfw.h.
MCIWNDF_NOAUTOSIZEWINDOW
#define MCIWNDF_NOAUTOSIZEWINDOW 0x0001
Definition at line 251 of file vfw.h.
MCIWNDF_NOERRORDLG
#define MCIWNDF_NOERRORDLG 0x4000
Definition at line 268 of file vfw.h.
MCIWNDF_NOMENU
#define MCIWNDF_NOMENU 0x0008
Definition at line 254 of file vfw.h.
MCIWNDF_NOOPEN
#define MCIWNDF_NOOPEN 0x8000
Definition at line 269 of file vfw.h.
MCIWNDF_NOPLAYBAR
#define MCIWNDF_NOPLAYBAR 0x0002
Definition at line 252 of file vfw.h.
MCIWNDF_NOTIFYALL
#define MCIWNDF_NOTIFYALL 0x1F00
Definition at line 263 of file vfw.h.
MCIWNDF_NOTIFYANSI
#define MCIWNDF_NOTIFYANSI 0x0080
Definition at line 264 of file vfw.h.
MCIWNDF_NOTIFYERROR
#define MCIWNDF_NOTIFYERROR 0x1000
Definition at line 262 of file vfw.h.
MCIWNDF_NOTIFYMEDIA
#define MCIWNDF_NOTIFYMEDIA MCIWNDF_NOTIFYMEDIAA
Definition at line 1346 of file vfw.h.
MCIWNDF_NOTIFYMEDIAA
#define MCIWNDF_NOTIFYMEDIAA 0x0880
Definition at line 265 of file vfw.h.
MCIWNDF_NOTIFYMEDIAW
#define MCIWNDF_NOTIFYMEDIAW 0x0800
Definition at line 266 of file vfw.h.
MCIWNDF_NOTIFYMODE
#define MCIWNDF_NOTIFYMODE 0x0100
Definition at line 259 of file vfw.h.
MCIWNDF_NOTIFYPOS
#define MCIWNDF_NOTIFYPOS 0x0200
Definition at line 260 of file vfw.h.
MCIWNDF_NOTIFYSIZE
#define MCIWNDF_NOTIFYSIZE 0x0400
Definition at line 261 of file vfw.h.
MCIWNDF_RECORD
#define MCIWNDF_RECORD 0x2000
Definition at line 267 of file vfw.h.
MCIWNDF_SHOWALL
#define MCIWNDF_SHOWALL 0x0070
Definition at line 258 of file vfw.h.
MCIWNDF_SHOWMODE
#define MCIWNDF_SHOWMODE 0x0040
Definition at line 257 of file vfw.h.
MCIWNDF_SHOWNAME
#define MCIWNDF_SHOWNAME 0x0010
Definition at line 255 of file vfw.h.
MCIWNDF_SHOWPOS
#define MCIWNDF_SHOWPOS 0x0020
Definition at line 256 of file vfw.h.
MCIWndGetActiveTimer
#define MCIWndGetActiveTimer (hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETACTIVETIMER,0,0L);
Definition at line 1025 of file vfw.h.
MCIWndGetAlias
#define MCIWndGetAlias (hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETALIAS,0,0)
Definition at line 1000 of file vfw.h.
MCIWndGetDest
#define MCIWndGetDest (hWnd, prc) (LONG)MCIWndSM(hWnd,MCIWNDM_GET_DEST,0,(LPARAM)(LPRECT)(prc))
Definition at line 993 of file vfw.h.
MCIWndGetDevice
#define MCIWndGetDevice (hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETDEVICE,(WPARAM)(UINT)(len),(LPARAM)(LPVOID)(lp))
Definition at line 1034 of file vfw.h.
MCIWndGetDeviceID
#define MCIWndGetDeviceID (hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETDEVICEID,0,0)
Definition at line 999 of file vfw.h.
MCIWndGetEnd
#define MCIWndGetEnd (hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETEND,0,0)
Definition at line 1006 of file vfw.h.
MCIWndGetError
#define MCIWndGetError (hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETERROR,(WPARAM)(UINT)(len),(LPARAM)(LPVOID)(lp))
Definition at line 1030 of file vfw.h.
MCIWndGetFileName
#define MCIWndGetFileName (hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETFILENAME,(WPARAM)(UINT)(len),(LPARAM)(LPVOID)(lp))
Definition at line 1033 of file vfw.h.
MCIWndGetInactiveTimer
#define MCIWndGetInactiveTimer (hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETINACTIVETIMER,0,0L);
Definition at line 1026 of file vfw.h.
MCIWndGetLength
#define MCIWndGetLength (hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETLENGTH,0,0)
Definition at line 1005 of file vfw.h.
MCIWndGetMode
#define MCIWndGetMode (hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETMODE,(WPARAM)(UINT)(len),(LPARAM)(LPTSTR)(lp))
Definition at line 1001 of file vfw.h.
MCIWndGetPalette
#define MCIWndGetPalette (hWnd) (HPALETTE)MCIWndSM(hWnd,MCIWNDM_GETPALETTE,0,0)
Definition at line 1031 of file vfw.h.
MCIWndGetPosition
#define MCIWndGetPosition (hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETPOSITION,0,0)
Definition at line 1002 of file vfw.h.
MCIWndGetPositionString
#define MCIWndGetPositionString (hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETPOSITION,(WPARAM)(UINT)(len),(LPARAM)(LPTSTR)(lp))
Definition at line 1003 of file vfw.h.
MCIWndGetRepeat
#define MCIWndGetRepeat (hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_GETREPEAT,0,0)
Definition at line 1019 of file vfw.h.
MCIWndGetSource
#define MCIWndGetSource (hWnd, prc) (LONG)MCIWndSM(hWnd,MCIWNDM_GET_SOURCE,0,(LPARAM)(LPRECT)(prc))
Definition at line 991 of file vfw.h.
MCIWndGetSpeed
#define MCIWndGetSpeed (hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETSPEED,0,0)
Definition at line 1014 of file vfw.h.
MCIWndGetStart
#define MCIWndGetStart (hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETSTART,0,0)
Definition at line 1004 of file vfw.h.
MCIWndGetStyles
#define MCIWndGetStyles (hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETSTYLES,0,0L)
Definition at line 1035 of file vfw.h.
MCIWndGetTimeFormat
#define MCIWndGetTimeFormat (hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_GETTIMEFORMAT,(WPARAM)(UINT)(len),(LPARAM)(LPTSTR)(lp))
Definition at line 1016 of file vfw.h.
MCIWndGetVolume
#define MCIWndGetVolume (hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_GETVOLUME,0,0)
Definition at line 1012 of file vfw.h.
MCIWndGetZoom
#define MCIWndGetZoom (hWnd) (UINT)MCIWndSM(hWnd,MCIWNDM_GETZOOM,0,0)
Definition at line 1010 of file vfw.h.
MCIWndHome
#define MCIWndHome (hWnd) MCIWndSeek(hWnd,MCIWND_START)
Definition at line 989 of file vfw.h.
MCIWNDM_CAN_CONFIG
#define MCIWNDM_CAN_CONFIG (WM_USER + 149)
Definition at line 307 of file vfw.h.
MCIWNDM_CAN_EJECT
#define MCIWNDM_CAN_EJECT (WM_USER + 148)
Definition at line 306 of file vfw.h.
MCIWNDM_CAN_PLAY
#define MCIWNDM_CAN_PLAY (WM_USER + 144)
Definition at line 302 of file vfw.h.
MCIWNDM_CAN_RECORD
#define MCIWNDM_CAN_RECORD (WM_USER + 146)
Definition at line 304 of file vfw.h.
MCIWNDM_CAN_SAVE
#define MCIWNDM_CAN_SAVE (WM_USER + 147)
Definition at line 305 of file vfw.h.
MCIWNDM_CAN_WINDOW
#define MCIWNDM_CAN_WINDOW (WM_USER + 145)
Definition at line 303 of file vfw.h.
MCIWNDM_CHANGESTYLES
#define MCIWNDM_CHANGESTYLES (WM_USER + 135)
Definition at line 294 of file vfw.h.
MCIWNDM_EJECT
#define MCIWNDM_EJECT (WM_USER + 107)
Definition at line 274 of file vfw.h.
MCIWNDM_GET_DEST
#define MCIWNDM_GET_DEST (WM_USER + 142)
Definition at line 300 of file vfw.h.
MCIWNDM_GET_SOURCE
#define MCIWNDM_GET_SOURCE (WM_USER + 140)
Definition at line 298 of file vfw.h.
MCIWNDM_GETACTIVETIMER
#define MCIWNDM_GETACTIVETIMER (WM_USER + 132)
Definition at line 292 of file vfw.h.
MCIWNDM_GETALIAS
#define MCIWNDM_GETALIAS (WM_USER + 137)
Definition at line 296 of file vfw.h.
MCIWNDM_GETDEVICE
#define MCIWNDM_GETDEVICE MCIWNDM_GETDEVICEA
Definition at line 1353 of file vfw.h.
MCIWNDM_GETDEVICEA
#define MCIWNDM_GETDEVICEA (WM_USER + 125)
Definition at line 317 of file vfw.h.
MCIWNDM_GETDEVICEID
#define MCIWNDM_GETDEVICEID (WM_USER + 100)
Definition at line 270 of file vfw.h.
MCIWNDM_GETDEVICEW
#define MCIWNDM_GETDEVICEW (WM_USER + 225)
Definition at line 328 of file vfw.h.
MCIWNDM_GETEND
#define MCIWNDM_GETEND (WM_USER + 105)
Definition at line 273 of file vfw.h.
MCIWNDM_GETERROR
#define MCIWNDM_GETERROR MCIWNDM_GETERRORA
Definition at line 1354 of file vfw.h.
MCIWNDM_GETERRORA
#define MCIWNDM_GETERRORA (WM_USER + 128)
Definition at line 318 of file vfw.h.
MCIWNDM_GETERRORW
#define MCIWNDM_GETERRORW (WM_USER + 228)
Definition at line 329 of file vfw.h.
MCIWNDM_GETFILENAME
#define MCIWNDM_GETFILENAME MCIWNDM_GETFILENAMEA
Definition at line 1352 of file vfw.h.
MCIWNDM_GETFILENAMEA
#define MCIWNDM_GETFILENAMEA (WM_USER + 124)
Definition at line 316 of file vfw.h.
MCIWNDM_GETFILENAMEW
#define MCIWNDM_GETFILENAMEW (WM_USER + 224)
Definition at line 327 of file vfw.h.
MCIWNDM_GETINACTIVETIMER
#define MCIWNDM_GETINACTIVETIMER (WM_USER + 133)
Definition at line 293 of file vfw.h.
MCIWNDM_GETLENGTH
#define MCIWNDM_GETLENGTH (WM_USER + 104)
Definition at line 272 of file vfw.h.
MCIWNDM_GETMODE
#define MCIWNDM_GETMODE MCIWNDM_GETMODEA
Definition at line 1349 of file vfw.h.
MCIWNDM_GETMODEA
#define MCIWNDM_GETMODEA (WM_USER + 106)
Definition at line 313 of file vfw.h.
MCIWNDM_GETMODEW
#define MCIWNDM_GETMODEW (WM_USER + 206)
Definition at line 324 of file vfw.h.
MCIWNDM_GETPALETTE
#define MCIWNDM_GETPALETTE (WM_USER + 126)
Definition at line 287 of file vfw.h.
MCIWNDM_GETPOSITION
#define MCIWNDM_GETPOSITION MCIWNDM_GETPOSITIONA
Definition at line 1348 of file vfw.h.
MCIWNDM_GETPOSITIONA
#define MCIWNDM_GETPOSITIONA (WM_USER + 102)
Definition at line 312 of file vfw.h.
MCIWNDM_GETPOSITIONW
#define MCIWNDM_GETPOSITIONW (WM_USER + 202)
Definition at line 323 of file vfw.h.
MCIWNDM_GETREPEAT
#define MCIWNDM_GETREPEAT (WM_USER + 115)
Definition at line 282 of file vfw.h.
MCIWNDM_GETSPEED
#define MCIWNDM_GETSPEED (WM_USER + 113)
Definition at line 280 of file vfw.h.
MCIWNDM_GETSTART
#define MCIWNDM_GETSTART (WM_USER + 103)
Definition at line 271 of file vfw.h.
MCIWNDM_GETSTYLES
#define MCIWNDM_GETSTYLES (WM_USER + 136)
Definition at line 295 of file vfw.h.
MCIWNDM_GETTIMEFORMAT
#define MCIWNDM_GETTIMEFORMAT MCIWNDM_GETTIMEFORMATA
Definition at line 1351 of file vfw.h.
MCIWNDM_GETTIMEFORMATA
#define MCIWNDM_GETTIMEFORMATA (WM_USER + 120)
Definition at line 315 of file vfw.h.
MCIWNDM_GETTIMEFORMATW
#define MCIWNDM_GETTIMEFORMATW (WM_USER + 220)
Definition at line 326 of file vfw.h.
MCIWNDM_GETVOLUME
#define MCIWNDM_GETVOLUME (WM_USER + 111)
Definition at line 278 of file vfw.h.
MCIWNDM_GETZOOM
#define MCIWNDM_GETZOOM (WM_USER + 109)
Definition at line 276 of file vfw.h.
MCIWNDM_NEW
#define MCIWNDM_NEW MCIWNDM_NEWA
Definition at line 1355 of file vfw.h.
MCIWNDM_NEWA
#define MCIWNDM_NEWA (WM_USER + 134)
Definition at line 319 of file vfw.h.
MCIWNDM_NEWW
#define MCIWNDM_NEWW (WM_USER + 234)
Definition at line 330 of file vfw.h.
MCIWNDM_NOTIFYERROR
#define MCIWNDM_NOTIFYERROR (WM_USER + 205)
Definition at line 337 of file vfw.h.
MCIWNDM_NOTIFYMEDIA
#define MCIWNDM_NOTIFYMEDIA (WM_USER + 203)
Definition at line 336 of file vfw.h.
MCIWNDM_NOTIFYMODE
#define MCIWNDM_NOTIFYMODE (WM_USER + 200)
Definition at line 333 of file vfw.h.
MCIWNDM_NOTIFYPOS
#define MCIWNDM_NOTIFYPOS (WM_USER + 201)
Definition at line 334 of file vfw.h.
MCIWNDM_NOTIFYSIZE
#define MCIWNDM_NOTIFYSIZE (WM_USER + 202)
Definition at line 335 of file vfw.h.
MCIWNDM_OPEN
#define MCIWNDM_OPEN MCIWNDM_OPENA
Definition at line 1357 of file vfw.h.
MCIWNDM_OPENA
#define MCIWNDM_OPENA (WM_USER + 153)
Definition at line 321 of file vfw.h.
MCIWNDM_OPENINTERFACE
#define MCIWNDM_OPENINTERFACE (WM_USER + 151)
Definition at line 309 of file vfw.h.
MCIWNDM_OPENW
#define MCIWNDM_OPENW (WM_USER + 252)
Definition at line 332 of file vfw.h.
MCIWNDM_PALETTEKICK
#define MCIWNDM_PALETTEKICK (WM_USER + 150)
Definition at line 308 of file vfw.h.
MCIWNDM_PLAYFROM
#define MCIWNDM_PLAYFROM (WM_USER + 122)
Definition at line 285 of file vfw.h.
MCIWNDM_PLAYREVERSE
#define MCIWNDM_PLAYREVERSE (WM_USER + 139)
Definition at line 297 of file vfw.h.
MCIWNDM_PLAYTO
#define MCIWNDM_PLAYTO (WM_USER + 123)
Definition at line 286 of file vfw.h.
MCIWNDM_PUT_DEST
#define MCIWNDM_PUT_DEST (WM_USER + 143)
Definition at line 301 of file vfw.h.
MCIWNDM_PUT_SOURCE
#define MCIWNDM_PUT_SOURCE (WM_USER + 141)
Definition at line 299 of file vfw.h.
MCIWNDM_REALIZE
#define MCIWNDM_REALIZE (WM_USER + 118)
Definition at line 283 of file vfw.h.
MCIWNDM_RETURNSTRING
#define MCIWNDM_RETURNSTRING MCIWNDM_RETURNSTRINGA
Definition at line 1356 of file vfw.h.
MCIWNDM_RETURNSTRINGA
#define MCIWNDM_RETURNSTRINGA (WM_USER + 138)
Definition at line 320 of file vfw.h.
MCIWNDM_RETURNSTRINGW
#define MCIWNDM_RETURNSTRINGW (WM_USER + 238)
Definition at line 331 of file vfw.h.
MCIWNDM_SENDSTRING
#define MCIWNDM_SENDSTRING MCIWNDM_SENDSTRINGA
Definition at line 1347 of file vfw.h.
MCIWNDM_SENDSTRINGA
#define MCIWNDM_SENDSTRINGA (WM_USER + 101)
Definition at line 311 of file vfw.h.
MCIWNDM_SENDSTRINGW
#define MCIWNDM_SENDSTRINGW (WM_USER + 201)
Definition at line 322 of file vfw.h.
MCIWNDM_SETACTIVETIMER
#define MCIWNDM_SETACTIVETIMER (WM_USER + 130)
Definition at line 290 of file vfw.h.
MCIWNDM_SETINACTIVETIMER
#define MCIWNDM_SETINACTIVETIMER (WM_USER + 131)
Definition at line 291 of file vfw.h.
MCIWNDM_SETOWNER
#define MCIWNDM_SETOWNER (WM_USER + 152)
Definition at line 310 of file vfw.h.
MCIWNDM_SETPALETTE
#define MCIWNDM_SETPALETTE (WM_USER + 127)
Definition at line 288 of file vfw.h.
MCIWNDM_SETREPEAT
#define MCIWNDM_SETREPEAT (WM_USER + 114)
Definition at line 281 of file vfw.h.
MCIWNDM_SETSPEED
#define MCIWNDM_SETSPEED (WM_USER + 112)
Definition at line 279 of file vfw.h.
MCIWNDM_SETTIMEFORMAT
#define MCIWNDM_SETTIMEFORMAT MCIWNDM_SETTIMEFORMATA
Definition at line 1350 of file vfw.h.
MCIWNDM_SETTIMEFORMATA
#define MCIWNDM_SETTIMEFORMATA (WM_USER + 119)
Definition at line 314 of file vfw.h.
MCIWNDM_SETTIMEFORMATW
#define MCIWNDM_SETTIMEFORMATW (WM_USER + 219)
Definition at line 325 of file vfw.h.
MCIWNDM_SETTIMERS
#define MCIWNDM_SETTIMERS (WM_USER + 129)
Definition at line 289 of file vfw.h.
MCIWNDM_SETVOLUME
#define MCIWNDM_SETVOLUME (WM_USER + 110)
Definition at line 277 of file vfw.h.
MCIWNDM_SETZOOM
#define MCIWNDM_SETZOOM (WM_USER + 108)
Definition at line 275 of file vfw.h.
MCIWNDM_VALIDATEMEDIA
#define MCIWNDM_VALIDATEMEDIA (WM_USER + 121)
Definition at line 284 of file vfw.h.
MCIWndNew
#define MCIWndNew (hWnd, lp) (LONG)MCIWndSM(hWnd,MCIWNDM_NEW,0,(LPARAM)(LPVOID)(lp))
Definition at line 978 of file vfw.h.
MCIWndOpen
#define MCIWndOpen (hWnd, sz, f) (LONG)MCIWndSM(hWnd,MCIWNDM_OPEN,(WPARAM)(UINT)(f),(LPARAM)(LPVOID)(sz))
Definition at line 980 of file vfw.h.
MCIWndOpenDialog
#define MCIWndOpenDialog (hWnd) MCIWndOpen(hWnd,-1,0)
Definition at line 981 of file vfw.h.
MCIWNDOPENF_NEW
#define MCIWNDOPENF_NEW 0x0001
Definition at line 250 of file vfw.h.
MCIWndOpenInterface
#define MCIWndOpenInterface (hWnd, pUnk) (LONG)MCIWndSM(hWnd,MCIWNDM_OPENINTERFACE,0,(LPARAM)(LPUNKNOWN)(pUnk))
Definition at line 1037 of file vfw.h.
MCIWndPaletteKick
#define MCIWndPaletteKick (hWnd) (BOOL)MCIWndSM(hWnd,MCIWNDM_PALETTEKICK,0,0)
Definition at line 975 of file vfw.h.
MCIWndPause
#define MCIWndPause (hWnd) (LONG)MCIWndSM(hWnd,MCI_PAUSE,0,0)
Definition at line 985 of file vfw.h.
MCIWndPlay
#define MCIWndPlay (hWnd) (LONG)MCIWndSM(hWnd,MCI_PLAY,0,0)
Definition at line 983 of file vfw.h.
MCIWndPlayFrom
#define MCIWndPlayFrom (hWnd, lPos) (LONG)MCIWndSM(hWnd,MCIWNDM_PLAYFROM,0,(LPARAM)(LONG)(lPos))
Definition at line 996 of file vfw.h.
MCIWndPlayFromTo
#define MCIWndPlayFromTo (hWnd, lStart, lEnd) (MCIWndSeek(hWnd,lStart),MCIWndPlayTo(hWnd,lEnd))
Definition at line 998 of file vfw.h.
MCIWndPlayReverse
#define MCIWndPlayReverse (hWnd) (LONG)MCIWndSM(hWnd,MCIWNDM_PLAYREVERSE,0,0)
Definition at line 995 of file vfw.h.
MCIWndPlayTo
#define MCIWndPlayTo (hWnd, lPos) (LONG)MCIWndSM(hWnd,MCIWNDM_PLAYTO, 0,(LPARAM)(LONG)(lPos))
Definition at line 997 of file vfw.h.
MCIWndPutDest
#define MCIWndPutDest (hWnd, prc) (LONG)MCIWndSM(hWnd,MCIWNDM_PUT_DEST,0,(LPARAM)(LPRECT)(prc))
Definition at line 994 of file vfw.h.
MCIWndPutSource
#define MCIWndPutSource (hWnd, prc) (LONG)MCIWndSM(hWnd,MCIWNDM_PUT_SOURCE,0,(LPARAM)(LPRECT)(prc))
Definition at line 992 of file vfw.h.
MCIWndRealize
#define MCIWndRealize (hWnd, fBkgnd) (LONG)MCIWndSM(hWnd,MCIWNDM_REALIZE,(WPARAM)(BOOL)(fBkgnd),0)
Definition at line 1027 of file vfw.h.
MCIWndRecord
#define MCIWndRecord (hWnd) (LONG)MCIWndSM(hWnd,MCI_RECORD,0,0)
Definition at line 979 of file vfw.h.
MCIWndResume
#define MCIWndResume (hWnd) (LONG)MCIWndSM(hWnd,MCI_RESUME,0,0)
Definition at line 986 of file vfw.h.
MCIWndReturnString
#define MCIWndReturnString (hWnd, lp, len) (LONG)MCIWndSM(hWnd,MCIWNDM_RETURNSTRING,(WPARAM)(UINT)(len),(LPARAM)(LPVOID)(lp))
Definition at line 1029 of file vfw.h.
MCIWndSave
#define MCIWndSave (hWnd, szFile) (LONG)MCIWndSM(hWnd,MCI_SAVE,0,(LPARAM)(LPVOID)(szFile))
Definition at line 976 of file vfw.h.
MCIWndSaveDialog
#define MCIWndSaveDialog (hWnd) MCIWndSave(hWnd,-1)
Definition at line 977 of file vfw.h.
MCIWndSeek
#define MCIWndSeek (hWnd, lPos) (LONG)MCIWndSM(hWnd,MCI_SEEK,0,(LPARAM)(LONG)(lPos))
Definition at line 987 of file vfw.h.
MCIWndSendString
#define MCIWndSendString (hWnd, sz) (LONG)MCIWndSM(hWnd,MCIWNDM_SENDSTRING,0,(LPARAM)(LPTSTR)(sz))
Definition at line 1028 of file vfw.h.
MCIWndSetActiveTimer
#define MCIWndSetActiveTimer (hWnd, active) (VOID)MCIWndSM(hWnd,MCIWNDM_SETACTIVETIMER,(WPARAM)(UINT)(active),0L)
Definition at line 1022 of file vfw.h.
MCIWndSetInactiveTimer
#define MCIWndSetInactiveTimer (hWnd, inactive) (VOID)MCIWndSM(hWnd,MCIWNDM_SETINACTIVETIMER,(WPARAM)(UINT)(inactive),0L)
Definition at line 1023 of file vfw.h.
MCIWndSetOwner
#define MCIWndSetOwner (hWnd, hWndP) (LONG)MCIWndSM(hWnd,MCIWNDM_SETOWNER,(WPARAM)(hWndP),0)
Definition at line 1038 of file vfw.h.
MCIWndSetPalette
#define MCIWndSetPalette (hWnd, hpal) (LONG)MCIWndSM(hWnd,MCIWNDM_SETPALETTE,(WPARAM)(HPALETTE)(hpal),0)
Definition at line 1032 of file vfw.h.
MCIWndSetRepeat
#define MCIWndSetRepeat (hWnd, f) (void)MCIWndSM(hWnd,MCIWNDM_SETREPEAT,0,(LPARAM)(BOOL)(f))
Definition at line 1018 of file vfw.h.
MCIWndSetSpeed
#define MCIWndSetSpeed (hWnd, iSpeed) (LONG)MCIWndSM(hWnd,MCIWNDM_SETSPEED,0,(LPARAM)(UINT)(iSpeed))
Definition at line 1013 of file vfw.h.
MCIWndSetTimeFormat
#define MCIWndSetTimeFormat (hWnd, lp) (LONG)MCIWndSM(hWnd,MCIWNDM_SETTIMEFORMAT,0,(LPARAM)(LPTSTR)(lp))
Definition at line 1015 of file vfw.h.
MCIWndSetTimers
#define MCIWndSetTimers (hWnd, active, inactive) (VOID)MCIWndSM(hWnd,MCIWNDM_SETTIMERS,(WPARAM)(UINT)(active),(LPARAM)(UINT)(inactive))
Definition at line 1024 of file vfw.h.
MCIWndSetVolume
#define MCIWndSetVolume (hWnd, iVol) (LONG)MCIWndSM(hWnd,MCIWNDM_SETVOLUME,0,(LPARAM)(UINT)(iVol))
Definition at line 1011 of file vfw.h.
MCIWndSetZoom
#define MCIWndSetZoom (hWnd, iZoom) (VOID)MCIWndSM(hWnd,MCIWNDM_SETZOOM,0,(LPARAM)(UINT)(iZoom))
Definition at line 1009 of file vfw.h.
MCIWndSM
#define MCIWndSM SendMessage
Definition at line 967 of file vfw.h.
MCIWndStep
#define MCIWndStep (hWnd, n) (LONG)MCIWndSM(hWnd,MCI_STEP,0,(LPARAM)(long)(n))
Definition at line 1007 of file vfw.h.
MCIWndStop
#define MCIWndStop (hWnd) (LONG)MCIWndSM(hWnd,MCI_STOP,0,0)
Definition at line 984 of file vfw.h.
MCIWndUseFrames
#define MCIWndUseFrames (hWnd) MCIWndSetTimeFormat(hWnd,TEXT("frames"))
Definition at line 1020 of file vfw.h.
MCIWndUseTime
#define MCIWndUseTime (hWnd) MCIWndSetTimeFormat(hWnd,TEXT("ms"))
Definition at line 1021 of file vfw.h.
MCIWndValidateMedia
#define MCIWndValidateMedia (hWnd) (VOID)MCIWndSM(hWnd,MCIWNDM_VALIDATEMEDIA,0,0)
Definition at line 1017 of file vfw.h.
PAVIFILEINFO
#define PAVIFILEINFO PAVIFILEINFOA
Definition at line 1332 of file vfw.h.
PAVISTREAMINFO
#define PAVISTREAMINFO PAVISTREAMINFOA
Definition at line 1330 of file vfw.h.
PD_CAN_DRAW_DIB
#define PD_CAN_DRAW_DIB 0x01
Definition at line 355 of file vfw.h.
PD_CAN_STRETCHDIB
#define PD_CAN_STRETCHDIB 0x02
Definition at line 356 of file vfw.h.
PD_STRETCHDIB_1_1_OK
#define PD_STRETCHDIB_1_1_OK 0x04
Definition at line 357 of file vfw.h.
PD_STRETCHDIB_1_2_OK
#define PD_STRETCHDIB_1_2_OK 0x08
Definition at line 358 of file vfw.h.
PD_STRETCHDIB_1_N_OK
#define PD_STRETCHDIB_1_N_OK 0x10
Definition at line 359 of file vfw.h.
StreamFromFOURCC
#define StreamFromFOURCC (fcc) ((WORD)((FromHex(LOBYTE(LOWORD(fcc)))<<4)+(FromHex(HIBYTE(LOWORD(fcc))))))
Definition at line 179 of file vfw.h.
streamtypeANY
#define streamtypeANY 0UL
Definition at line 168 of file vfw.h.
streamtypeAUDIO
#define streamtypeAUDIO mmioFOURCC('a','u','d','s')
Definition at line 170 of file vfw.h.
streamtypeMIDI
#define streamtypeMIDI mmioFOURCC('m','i','d','s')
Definition at line 171 of file vfw.h.
streamtypeTEXT
#define streamtypeTEXT mmioFOURCC('t','x','t','s')
Definition at line 172 of file vfw.h.
streamtypeVIDEO
#define streamtypeVIDEO mmioFOURCC('v','i','d','s')
Definition at line 169 of file vfw.h.
ToHex
#define ToHex (n) ((BYTE)(((n)>9)?((n)-10+'A'):((n)+'0')))
Definition at line 181 of file vfw.h.
TWOCCFromFOURCC
#define TWOCCFromFOURCC (fcc) HIWORD(fcc)
Definition at line 180 of file vfw.h.
VFWAPI
#define VFWAPI WINAPI
Definition at line 17 of file vfw.h.
VFWAPIV
#define VFWAPIV WINAPIV
Definition at line 18 of file vfw.h.
VIDCF_COMPRESSFRAMES
#define VIDCF_COMPRESSFRAMES 0x08
Definition at line 119 of file vfw.h.
VIDCF_CRUNCH
#define VIDCF_CRUNCH 0x02
Definition at line 117 of file vfw.h.
VIDCF_DRAW
#define VIDCF_DRAW 0x10
Definition at line 120 of file vfw.h.
VIDCF_FASTTEMPORAL
#define VIDCF_FASTTEMPORAL (VIDCF_FASTTEMPORALC|VIDCF_FASTTEMPORALD)
Definition at line 124 of file vfw.h.
VIDCF_FASTTEMPORALC
#define VIDCF_FASTTEMPORALC 0x20
Definition at line 121 of file vfw.h.
VIDCF_FASTTEMPORALD
#define VIDCF_FASTTEMPORALD 0x80
Definition at line 122 of file vfw.h.
VIDCF_QUALITY
#define VIDCF_QUALITY 0x01
Definition at line 116 of file vfw.h.
VIDCF_QUALITYTIME
#define VIDCF_QUALITYTIME 0x40
Definition at line 123 of file vfw.h.
VIDCF_TEMPORAL
#define VIDCF_TEMPORAL 0x04
Definition at line 118 of file vfw.h.
WM_CAP_ABORT
#define WM_CAP_ABORT (WM_USER + 69)
Definition at line 1187 of file vfw.h.
WM_CAP_DLG_VIDEOCOMPRESSION
#define WM_CAP_DLG_VIDEOCOMPRESSION (WM_USER + 46)
Definition at line 1169 of file vfw.h.
WM_CAP_DLG_VIDEODISPLAY
#define WM_CAP_DLG_VIDEODISPLAY (WM_USER + 43)
Definition at line 1166 of file vfw.h.
WM_CAP_DLG_VIDEOFORMAT
#define WM_CAP_DLG_VIDEOFORMAT (WM_USER + 41)
Definition at line 1164 of file vfw.h.
WM_CAP_DLG_VIDEOSOURCE
#define WM_CAP_DLG_VIDEOSOURCE (WM_USER + 42)
Definition at line 1165 of file vfw.h.
WM_CAP_DRIVER_CONNECT
#define WM_CAP_DRIVER_CONNECT (WM_USER + 10)
Definition at line 1144 of file vfw.h.
WM_CAP_DRIVER_DISCONNECT
#define WM_CAP_DRIVER_DISCONNECT (WM_USER + 11)
Definition at line 1145 of file vfw.h.
WM_CAP_DRIVER_GET_CAPS
#define WM_CAP_DRIVER_GET_CAPS (WM_USER + 14)
Definition at line 1150 of file vfw.h.
WM_CAP_DRIVER_GET_NAME
#define WM_CAP_DRIVER_GET_NAME WM_CAP_DRIVER_GET_NAMEA
Definition at line 1216 of file vfw.h.
WM_CAP_DRIVER_GET_NAMEA
#define WM_CAP_DRIVER_GET_NAMEA (WM_USER + 12)
Definition at line 1146 of file vfw.h.
WM_CAP_DRIVER_GET_NAMEW
#define WM_CAP_DRIVER_GET_NAMEW (WM_CAP_DRIVER_GET_NAMEA + 100)
Definition at line 1147 of file vfw.h.
WM_CAP_DRIVER_GET_VERSION
#define WM_CAP_DRIVER_GET_VERSION WM_CAP_DRIVER_GET_VERSIONA
Definition at line 1217 of file vfw.h.
WM_CAP_DRIVER_GET_VERSIONA
#define WM_CAP_DRIVER_GET_VERSIONA (WM_USER + 13)
Definition at line 1148 of file vfw.h.
WM_CAP_DRIVER_GET_VERSIONW
#define WM_CAP_DRIVER_GET_VERSIONW (WM_CAP_DRIVER_GET_VERSIONA + 100)
Definition at line 1149 of file vfw.h.
WM_CAP_EDIT_COPY
#define WM_CAP_EDIT_COPY (WM_USER + 30)
Definition at line 1161 of file vfw.h.
WM_CAP_FILE_ALLOCATE
#define WM_CAP_FILE_ALLOCATE (WM_USER + 22)
Definition at line 1155 of file vfw.h.
WM_CAP_FILE_GET_CAPTURE_FILE
#define WM_CAP_FILE_GET_CAPTURE_FILE WM_CAP_FILE_GET_CAPTURE_FILEA
Definition at line 1219 of file vfw.h.
WM_CAP_FILE_GET_CAPTURE_FILEA
#define WM_CAP_FILE_GET_CAPTURE_FILEA (WM_USER + 21)
Definition at line 1153 of file vfw.h.
WM_CAP_FILE_GET_CAPTURE_FILEW
#define WM_CAP_FILE_GET_CAPTURE_FILEW (WM_CAP_FILE_GET_CAPTURE_FILEA + 100)
Definition at line 1154 of file vfw.h.
WM_CAP_FILE_SAVEAS
#define WM_CAP_FILE_SAVEAS WM_CAP_FILE_SAVEASA
Definition at line 1220 of file vfw.h.
WM_CAP_FILE_SAVEASA
#define WM_CAP_FILE_SAVEASA (WM_USER + 23)
Definition at line 1156 of file vfw.h.
WM_CAP_FILE_SAVEASW
#define WM_CAP_FILE_SAVEASW (WM_CAP_FILE_SAVEASA + 100)
Definition at line 1157 of file vfw.h.
WM_CAP_FILE_SAVEDIB
#define WM_CAP_FILE_SAVEDIB WM_CAP_FILE_SAVEDIBA
Definition at line 1221 of file vfw.h.
WM_CAP_FILE_SAVEDIBA
#define WM_CAP_FILE_SAVEDIBA (WM_USER + 25)
Definition at line 1159 of file vfw.h.
WM_CAP_FILE_SAVEDIBW
#define WM_CAP_FILE_SAVEDIBW (WM_CAP_FILE_SAVEDIBA + 100)
Definition at line 1160 of file vfw.h.
WM_CAP_FILE_SET_CAPTURE_FILE
#define WM_CAP_FILE_SET_CAPTURE_FILE WM_CAP_FILE_SET_CAPTURE_FILEA
Definition at line 1218 of file vfw.h.
WM_CAP_FILE_SET_CAPTURE_FILEA
#define WM_CAP_FILE_SET_CAPTURE_FILEA (WM_USER + 20)
Definition at line 1151 of file vfw.h.
WM_CAP_FILE_SET_CAPTURE_FILEW
#define WM_CAP_FILE_SET_CAPTURE_FILEW (WM_CAP_FILE_SET_CAPTURE_FILEA + 100)
Definition at line 1152 of file vfw.h.
WM_CAP_FILE_SET_INFOCHUNK
#define WM_CAP_FILE_SET_INFOCHUNK (WM_USER + 24)
Definition at line 1158 of file vfw.h.
WM_CAP_GET_AUDIOFORMAT
#define WM_CAP_GET_AUDIOFORMAT (WM_USER + 36)
Definition at line 1163 of file vfw.h.
WM_CAP_GET_MCI_DEVICE
#define WM_CAP_GET_MCI_DEVICE WM_CAP_GET_MCI_DEVICEA
Definition at line 1223 of file vfw.h.
WM_CAP_GET_MCI_DEVICEA
#define WM_CAP_GET_MCI_DEVICEA (WM_USER + 67)
Definition at line 1184 of file vfw.h.
WM_CAP_GET_MCI_DEVICEW
#define WM_CAP_GET_MCI_DEVICEW (WM_CAP_GET_MCI_DEVICEA + 100)
Definition at line 1185 of file vfw.h.
WM_CAP_GET_SEQUENCE_SETUP
#define WM_CAP_GET_SEQUENCE_SETUP (WM_USER + 65)
Definition at line 1181 of file vfw.h.
WM_CAP_GET_STATUS
#define WM_CAP_GET_STATUS (WM_USER + 54)
Definition at line 1174 of file vfw.h.
WM_CAP_GET_USER_DATA
#define WM_CAP_GET_USER_DATA (WM_USER + 8)
Definition at line 1142 of file vfw.h.
WM_CAP_GET_VIDEOFORMAT
#define WM_CAP_GET_VIDEOFORMAT (WM_USER + 44)
Definition at line 1167 of file vfw.h.
WM_CAP_GRAB_FRAME
#define WM_CAP_GRAB_FRAME (WM_USER + 60)
Definition at line 1176 of file vfw.h.
WM_CAP_GRAB_FRAME_NOSTOP
#define WM_CAP_GRAB_FRAME_NOSTOP (WM_USER + 61)
Definition at line 1177 of file vfw.h.
WM_CAP_PAL_AUTOCREATE
#define WM_CAP_PAL_AUTOCREATE (WM_USER + 83)
Definition at line 1196 of file vfw.h.
WM_CAP_PAL_MANUALCREATE
#define WM_CAP_PAL_MANUALCREATE (WM_USER + 84)
Definition at line 1197 of file vfw.h.
WM_CAP_PAL_OPEN
#define WM_CAP_PAL_OPEN WM_CAP_PAL_OPENA
Definition at line 1224 of file vfw.h.
WM_CAP_PAL_OPENA
#define WM_CAP_PAL_OPENA (WM_USER + 80)
Definition at line 1191 of file vfw.h.
WM_CAP_PAL_OPENW
#define WM_CAP_PAL_OPENW (WM_CAP_PAL_OPENA + 100)
Definition at line 1192 of file vfw.h.
WM_CAP_PAL_PASTE
#define WM_CAP_PAL_PASTE (WM_USER + 82)
Definition at line 1195 of file vfw.h.
WM_CAP_PAL_SAVE
#define WM_CAP_PAL_SAVE WM_CAP_PAL_SAVEA
Definition at line 1225 of file vfw.h.
WM_CAP_PAL_SAVEA
#define WM_CAP_PAL_SAVEA (WM_USER + 81)
Definition at line 1193 of file vfw.h.
WM_CAP_PAL_SAVEW
#define WM_CAP_PAL_SAVEW (WM_CAP_PAL_SAVEA + 100)
Definition at line 1194 of file vfw.h.
WM_CAP_SEQUENCE
#define WM_CAP_SEQUENCE (WM_USER + 62)
Definition at line 1178 of file vfw.h.
WM_CAP_SEQUENCE_NOFILE
#define WM_CAP_SEQUENCE_NOFILE (WM_USER + 63)
Definition at line 1179 of file vfw.h.
WM_CAP_SET_AUDIOFORMAT
#define WM_CAP_SET_AUDIOFORMAT (WM_USER + 35)
Definition at line 1162 of file vfw.h.
WM_CAP_SET_CALLBACK_CAPCONTROL
#define WM_CAP_SET_CALLBACK_CAPCONTROL (WM_USER + 85)
Definition at line 1198 of file vfw.h.
WM_CAP_SET_CALLBACK_ERROR
#define WM_CAP_SET_CALLBACK_ERROR WM_CAP_SET_CALLBACK_ERRORA
Definition at line 1214 of file vfw.h.
WM_CAP_SET_CALLBACK_ERRORA
#define WM_CAP_SET_CALLBACK_ERRORA (WM_USER + 2)
Definition at line 1134 of file vfw.h.
WM_CAP_SET_CALLBACK_ERRORW
#define WM_CAP_SET_CALLBACK_ERRORW (WM_CAP_SET_CALLBACK_ERRORA + 100)
Definition at line 1135 of file vfw.h.
WM_CAP_SET_CALLBACK_FRAME
#define WM_CAP_SET_CALLBACK_FRAME WM_CAP_SET_CALLBACK_FRAMEA
Definition at line 1215 of file vfw.h.
WM_CAP_SET_CALLBACK_FRAMEA
#define WM_CAP_SET_CALLBACK_FRAMEA (WM_USER + 5)
Definition at line 1138 of file vfw.h.
WM_CAP_SET_CALLBACK_FRAMEW
#define WM_CAP_SET_CALLBACK_FRAMEW (WM_CAP_SET_CALLBACK_FRAMEA + 100)
Definition at line 1139 of file vfw.h.
WM_CAP_SET_CALLBACK_STATUS
#define WM_CAP_SET_CALLBACK_STATUS (WM_USER + 3)
Definition at line 1136 of file vfw.h.
WM_CAP_SET_CALLBACK_VIDEOSTREAM
#define WM_CAP_SET_CALLBACK_VIDEOSTREAM (WM_USER + 6)
Definition at line 1140 of file vfw.h.
WM_CAP_SET_CALLBACK_WAVESTREAM
#define WM_CAP_SET_CALLBACK_WAVESTREAM (WM_USER + 7)
Definition at line 1141 of file vfw.h.
WM_CAP_SET_CALLBACK_YIELD
#define WM_CAP_SET_CALLBACK_YIELD (WM_USER + 4)
Definition at line 1137 of file vfw.h.
WM_CAP_SET_MCI_DEVICE
#define WM_CAP_SET_MCI_DEVICE WM_CAP_SET_MCI_DEVICEA
Definition at line 1222 of file vfw.h.
WM_CAP_SET_MCI_DEVICEA
#define WM_CAP_SET_MCI_DEVICEA (WM_USER + 66)
Definition at line 1182 of file vfw.h.
WM_CAP_SET_MCI_DEVICEW
#define WM_CAP_SET_MCI_DEVICEW (WM_CAP_SET_MCI_DEVICEA + 100)
Definition at line 1183 of file vfw.h.
WM_CAP_SET_OVERLAY
#define WM_CAP_SET_OVERLAY (WM_USER + 51)
Definition at line 1171 of file vfw.h.
WM_CAP_SET_PREVIEW
#define WM_CAP_SET_PREVIEW (WM_USER + 50)
Definition at line 1170 of file vfw.h.
WM_CAP_SET_PREVIEWRATE
#define WM_CAP_SET_PREVIEWRATE (WM_USER + 52)
Definition at line 1172 of file vfw.h.
WM_CAP_SET_SCALE
#define WM_CAP_SET_SCALE (WM_USER + 53)
Definition at line 1173 of file vfw.h.
WM_CAP_SET_SCROLL
#define WM_CAP_SET_SCROLL (WM_USER + 55)
Definition at line 1175 of file vfw.h.
WM_CAP_SET_SEQUENCE_SETUP
#define WM_CAP_SET_SEQUENCE_SETUP (WM_USER + 64)
Definition at line 1180 of file vfw.h.
WM_CAP_SET_USER_DATA
#define WM_CAP_SET_USER_DATA (WM_USER + 9)
Definition at line 1143 of file vfw.h.
WM_CAP_SET_VIDEOFORMAT
#define WM_CAP_SET_VIDEOFORMAT (WM_USER + 45)
Definition at line 1168 of file vfw.h.
WM_CAP_SINGLE_FRAME
#define WM_CAP_SINGLE_FRAME (WM_USER + 72)
Definition at line 1190 of file vfw.h.
WM_CAP_SINGLE_FRAME_CLOSE
#define WM_CAP_SINGLE_FRAME_CLOSE (WM_USER + 71)
Definition at line 1189 of file vfw.h.
WM_CAP_SINGLE_FRAME_OPEN
#define WM_CAP_SINGLE_FRAME_OPEN (WM_USER + 70)
Definition at line 1188 of file vfw.h.
WM_CAP_STOP
#define WM_CAP_STOP (WM_USER + 68)
Definition at line 1186 of file vfw.h.
Typedef Documentation
AVISAVECALLBACK
typedef BOOL(CALLBACK * AVISAVECALLBACK) (INT)
Definition at line 371 of file vfw.h.
LPAVICOMPRESSOPTIONS
typedef struct AVICOMPRESSOPTIONS * LPAVICOMPRESSOPTIONS
LPAVIFILEINFOA
typedef struct AVIFILEINFOA * LPAVIFILEINFOA
LPAVIFILEINFOW
typedef struct AVIFILEINFOW * LPAVIFILEINFOW
LPAVISTREAMINFOA
typedef struct AVISTREAMINFOA * LPAVISTREAMINFOA
LPAVISTREAMINFOW
typedef struct AVISTREAMINFOW * LPAVISTREAMINFOW
LPCAPDRIVERCAPS
typedef struct CAPDRIVERCAPS * LPCAPDRIVERCAPS
LPCAPINFOCHUNK
typedef struct CAPINFOCHUNK * LPCAPINFOCHUNK
LPCAPSTATUS
typedef struct CAPSTATUS * LPCAPSTATUS
LPCAPTUREPARMS
typedef struct CAPTUREPARMS * LPCAPTUREPARMS
LPICOPEN
typedef struct ICOPEN* LPICOPEN
LPVIDEOHDR
typedef struct VIDEOHDR * LPVIDEOHDR
PAVICOMPRESSOPTIONS
typedef struct AVICOMPRESSOPTIONS* PAVICOMPRESSOPTIONS
PAVIEDITSTREAM
typedef IAVIEditStream* PAVIEDITSTREAM
Definition at line 763 of file vfw.h.
PAVIFILE
typedef IAVIFile* PAVIFILE
Definition at line 780 of file vfw.h.
PAVIFILEINFOA
typedef struct AVIFILEINFOA * PAVIFILEINFOA
PAVIFILEINFOW
typedef struct AVIFILEINFOW * PAVIFILEINFOW
PAVISTREAM
typedef IAVIStream* PAVISTREAM
Definition at line 736 of file vfw.h.
PAVISTREAMINFOA
typedef struct AVISTREAMINFOA * PAVISTREAMINFOA
PAVISTREAMINFOW
typedef struct AVISTREAMINFOW * PAVISTREAMINFOW
PAVISTREAMING
typedef IAVIStreaming* PAVISTREAMING
Definition at line 748 of file vfw.h.
PCOMPVARS
typedef struct COMPVARS * PCOMPVARS
PGETFRAME
typedef IGetFrame* PGETFRAME
Definition at line 794 of file vfw.h.
TWOCC
typedef WORD TWOCC
Definition at line 370 of file vfw.h.
Function Documentation
AVIBuildFilterA()
HRESULT WINAPI AVIBuildFilterA (LPSTR , LONG , BOOL)
AVIBuildFilterW()
HRESULT WINAPI AVIBuildFilterW (LPWSTR , LONG , BOOL)
AVIClearClipboard()
HRESULT WINAPI AVIClearClipboard (VOID)
AVIFileAddRef()
ULONG WINAPI AVIFileAddRef (PAVIFILE)
AVIFileCreateStreamA()
HRESULT WINAPI AVIFileCreateStreamA (PAVIFILE , PAVISTREAM * , AVISTREAMINFOA *)
AVIFileCreateStreamW()
HRESULT WINAPI AVIFileCreateStreamW (PAVIFILE , PAVISTREAM * , AVISTREAMINFOW *)
AVIFileEndRecord()
HRESULT WINAPI AVIFileEndRecord (PAVIFILE)
AVIFileExit()
VOID WINAPI AVIFileExit (void)
AVIFileGetStream()
HRESULT WINAPI AVIFileGetStream (PAVIFILE , PAVISTREAM * , DWORD , LONG)
AVIFileInfoA()
HRESULT WINAPI AVIFileInfoA (PAVIFILE , PAVIFILEINFOA , LONG)
AVIFileInfoW()
HRESULT WINAPI AVIFileInfoW (PAVIFILE , PAVIFILEINFOW , LONG)
AVIFileInit()
VOID WINAPI AVIFileInit (void)
AVIFileOpenA()
HRESULT WINAPI AVIFileOpenA (PAVIFILE * , LPCSTR , UINT , LPCLSID)
AVIFileOpenW()
HRESULT WINAPI AVIFileOpenW (PAVIFILE * , LPCWSTR , UINT , LPCLSID)
AVIFileReadData()
HRESULT WINAPI AVIFileReadData (PAVIFILE , DWORD , LPVOID , LPLONG)
AVIFileRelease()
ULONG WINAPI AVIFileRelease (PAVIFILE)
AVIFileWriteData()
HRESULT WINAPI AVIFileWriteData (PAVIFILE , DWORD , LPVOID , LONG)
AVIGetFromClipboard()
HRESULT WINAPI AVIGetFromClipboard (PAVIFILE *)
AVIMakeCompressedStream()
HRESULT WINAPI AVIMakeCompressedStream (PAVISTREAM * , PAVISTREAM , AVICOMPRESSOPTIONS * , CLSID *)
AVIMakeFileFromStreams()
HRESULT WINAPI AVIMakeFileFromStreams (PAVIFILE * , INT , PAVISTREAM *)
AVIPutFileOnClipboard()
HRESULT WINAPI AVIPutFileOnClipboard (PAVIFILE)
AVISaveOptions()
BOOL WINAPI AVISaveOptions (HWND , UINT , INT , PAVISTREAM * , LPAVICOMPRESSOPTIONS *)
AVISaveOptionsFree()
HRESULT WINAPI AVISaveOptionsFree (INT , LPAVICOMPRESSOPTIONS *)
AVISaveVA()
HRESULT WINAPI AVISaveVA (LPCSTR , CLSID * , AVISAVECALLBACK , INT , PAVISTREAM * , LPAVICOMPRESSOPTIONS *)
AVISaveVW()
HRESULT WINAPI AVISaveVW (LPCWSTR , CLSID * , AVISAVECALLBACK , INT , PAVISTREAM * , LPAVICOMPRESSOPTIONS *)
AVIStreamAddRef()
ULONG WINAPI AVIStreamAddRef (PAVISTREAM)
AVIStreamCreate()
HRESULT WINAPI AVIStreamCreate (PAVISTREAM * , LONG , LONG , CLSID *)
AVIStreamFindSample()
HRESULT WINAPI AVIStreamFindSample (PAVISTREAM , LONG , DWORD)
AVIStreamGetFrame()
LPVOID WINAPI AVIStreamGetFrame (PGETFRAME , LONG)
AVIStreamGetFrameClose()
HRESULT WINAPI AVIStreamGetFrameClose (PGETFRAME)
AVIStreamGetFrameOpen()
PGETFRAME WINAPI AVIStreamGetFrameOpen (PAVISTREAM , LPBITMAPINFOHEADER)
AVIStreamInfoA()
HRESULT WINAPI AVIStreamInfoA (PAVISTREAM , AVISTREAMINFOA * , LONG)
AVIStreamInfoW()
HRESULT WINAPI AVIStreamInfoW (PAVISTREAM , AVISTREAMINFOW * , LONG)
AVIStreamLength()
LONG WINAPI AVIStreamLength (PAVISTREAM)
AVIStreamOpenFromFileA()
HRESULT WINAPI AVIStreamOpenFromFileA (PAVISTREAM * , LPCSTR , DWORD , LONG , UINT , CLSID *)
AVIStreamOpenFromFileW()
HRESULT WINAPI AVIStreamOpenFromFileW (PAVISTREAM * , LPCWSTR , DWORD , LONG , UINT , CLSID *)
AVIStreamRead()
HRESULT WINAPI AVIStreamRead (PAVISTREAM , LONG , LONG , LPVOID , LONG , LONG * , LONG *)
AVIStreamReadData()
HRESULT WINAPI AVIStreamReadData (PAVISTREAM , DWORD , LPVOID , LONG *)
AVIStreamReadFormat()
HRESULT WINAPI AVIStreamReadFormat (PAVISTREAM , LONG , LPVOID , LONG *)
AVIStreamRelease()
ULONG WINAPI AVIStreamRelease (PAVISTREAM)
AVIStreamSampleToTime()
LONG WINAPI AVIStreamSampleToTime (PAVISTREAM , LONG)
AVIStreamSetFormat()
HRESULT WINAPI AVIStreamSetFormat (PAVISTREAM , LONG , LPVOID , LONG)
AVIStreamStart()
LONG WINAPI AVIStreamStart (PAVISTREAM)
AVIStreamTimeToSample()
LONG WINAPI AVIStreamTimeToSample (PAVISTREAM , LONG)
AVIStreamWrite()
HRESULT WINAPI AVIStreamWrite (PAVISTREAM , LONG , LONG , LPVOID , LONG , DWORD , LONG * , LONG *)
AVIStreamWriteData()
HRESULT WINAPI AVIStreamWriteData (PAVISTREAM , DWORD , LPVOID , LONG)
capCreateCaptureWindowA()
HWND VFWAPI capCreateCaptureWindowA (LPCSTR , DWORD , int , int , int , int , HWND , int)
capCreateCaptureWindowW()
HWND VFWAPI capCreateCaptureWindowW (LPCWSTR , DWORD , int , int , int , int , HWND , int)
capGetDriverDescriptionA()
BOOL VFWAPI capGetDriverDescriptionA (UINT , LPSTR , int , LPSTR , int)
capGetDriverDescriptionW()
BOOL VFWAPI capGetDriverDescriptionW (UINT , LPWSTR , int , LPWSTR , int)
CreateEditableStream()
HRESULT WINAPI CreateEditableStream (PAVISTREAM * , PAVISTREAM)
DECLARE_HANDLE() [1/2]
DECLARE_HANDLE (HDRAWDIB)
DECLARE_HANDLE() [2/2]
DECLARE_HANDLE (HIC)
DECLARE_INTERFACE_() [1/5]
DECLARE_INTERFACE_ (IAVIEditStream , IUnknown)
Definition at line 753 of file vfw.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Cut)(THIS_ LONG*,LONG*,PAVISTREAM*) PURE;
     STDMETHOD(Copy)(THIS_ LONG*,LONG*,PAVISTREAM*) PURE;
     STDMETHOD(Paste)(THIS_ LONG*,LONG*,PAVISTREAM,LONG,LONG) PURE;
     STDMETHOD(Clone)(THIS_ PAVISTREAM*) PURE;
     STDMETHOD(SetInfo)(THIS_ LPAVISTREAMINFOW,LONG) PURE;
 };
References LONG, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [2/5]
DECLARE_INTERFACE_ (IAVIFile , IUnknown)
Definition at line 768 of file vfw.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Info)(THIS_ AVIFILEINFOW*,LONG) PURE;
     STDMETHOD(GetStream)(THIS_ PAVISTREAM*,DWORD,LONG) PURE;
     STDMETHOD(CreateStream)(THIS_ PAVISTREAM*,AVISTREAMINFOW*) PURE;
     STDMETHOD(WriteData)(THIS_ DWORD,LPVOID,LONG) PURE;
     STDMETHOD(ReadData)(THIS_ DWORD,LPVOID,LONG*) PURE;
     STDMETHOD(EndRecord)(THIS) PURE;
     STDMETHOD(DeleteStream)(THIS_ DWORD,LONG) PURE;
 };
References Info, LONG, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [3/5]
DECLARE_INTERFACE_ (IAVIStream , IUnknown)
Definition at line 720 of file vfw.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Create)(THIS_ LPARAM,LPARAM) PURE;
     STDMETHOD(Info)(THIS_ AVISTREAMINFOW*,LONG) PURE;
     STDMETHOD_(LONG,FindSample)(THIS_ LONG,LONG) PURE;
     STDMETHOD(ReadFormat)(THIS_ LONG,LPVOID,LONG*) PURE;
     STDMETHOD(SetFormat)(THIS_ LONG,LPVOID,LONG) PURE;
     STDMETHOD(Read)(THIS_ LONG,LONG,LPVOID,LONG,LONG*,LONG*) PURE;
     STDMETHOD(Write)(THIS_ LONG,LONG,LPVOID,LONG,DWORD,LONG*,LONG*) PURE;
     STDMETHOD(Delete)(THIS_ LONG,LONG) PURE;
     STDMETHOD(ReadData)(THIS_ DWORD,LPVOID,LONG*) PURE;
     STDMETHOD(WriteData)(THIS_ DWORD,LPVOID,LONG) PURE;
     STDMETHOD(SetInfo)(THIS_ AVISTREAMINFOW*,LONG) PURE;
 };
References Info, LONG, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [4/5]
DECLARE_INTERFACE_ (IAVIStreaming , IUnknown)
Definition at line 741 of file vfw.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Begin)(THIS_ LONG,LONG,LONG) PURE;
     STDMETHOD(End)(THIS) PURE;
 };
References LONG, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [5/5]
DECLARE_INTERFACE_ (IGetFrame , IUnknown)
Definition at line 785 of file vfw.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD_(LPVOID,GetFrame)(THIS_ LONG) PURE;
     STDMETHOD(Begin)(THIS_ LONG,LONG,LONG) PURE;
     STDMETHOD(End)(THIS) PURE;
     STDMETHOD(SetFormat)(THIS_ LPBITMAPINFOHEADER,LPVOID,INT,INT,INT,INT) PURE;
 };
References INT, LONG, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DEFINE_AVIGUID() [1/6]
DEFINE_AVIGUID (CLSID_AVIFile , 0x00020000 , 0 , 0)
DEFINE_AVIGUID() [2/6]
DEFINE_AVIGUID (IID_IAVIEditStream , 0x00020024 , 0 , 0)
DEFINE_AVIGUID() [3/6]
DEFINE_AVIGUID (IID_IAVIFile , 0x00020020 , 0 , 0)
DEFINE_AVIGUID() [4/6]
DEFINE_AVIGUID (IID_IAVIStream , 0x00020021 , 0 , 0)
DEFINE_AVIGUID() [5/6]
DEFINE_AVIGUID (IID_IAVIStreaming , 0x00020022 , 0 , 0)
DEFINE_AVIGUID() [6/6]
DEFINE_AVIGUID (IID_IGetFrame , 0x00020023 , 0 , 0)
DrawDibBegin()
BOOL VFWAPI DrawDibBegin (HDRAWDIB , HDC , INT , INT , LPBITMAPINFOHEADER , INT , INT , UINT)
DrawDibChangePalette()
BOOL VFWAPI DrawDibChangePalette (HDRAWDIB , int , int , LPPALETTEENTRY)
DrawDibClose()
BOOL VFWAPI DrawDibClose (HDRAWDIB)
DrawDibDraw()
BOOL VFWAPI DrawDibDraw (HDRAWDIB , HDC , INT , INT , INT , INT , LPBITMAPINFOHEADER , LPVOID , INT , INT , INT , INT , UINT)
DrawDibEnd()
BOOL VFWAPI DrawDibEnd (HDRAWDIB)
DrawDibGetBuffer()
LPVOID VFWAPI DrawDibGetBuffer (HDRAWDIB , LPBITMAPINFOHEADER , DWORD , DWORD)
DrawDibGetPalette()
HPALETTE VFWAPI DrawDibGetPalette (HDRAWDIB)
DrawDibOpen()
HDRAWDIB VFWAPI DrawDibOpen (VOID)
DrawDibProfileDisplay()
DWORD VFWAPI DrawDibProfileDisplay (LPBITMAPINFOHEADER)
DrawDibRealize()
UINT VFWAPI DrawDibRealize (HDRAWDIB , HDC , BOOL)
DrawDibSetPalette()
BOOL VFWAPI DrawDibSetPalette (HDRAWDIB , HPALETTE)
DrawDibStart()
BOOL VFWAPI DrawDibStart (HDRAWDIB , DWORD)
DrawDibStop()
BOOL VFWAPI DrawDibStop (HDRAWDIB)
EditStreamClone()
HRESULT WINAPI EditStreamClone (PAVISTREAM , PAVISTREAM *)
EditStreamCopy()
HRESULT WINAPI EditStreamCopy (PAVISTREAM , LONG * , LONG * , PAVISTREAM *)
EditStreamCut()
HRESULT WINAPI EditStreamCut (PAVISTREAM , LONG * , LONG * , PAVISTREAM *)
EditStreamPaste()
HRESULT WINAPI EditStreamPaste (PAVISTREAM , LONG * , LONG * , PAVISTREAM , LONG , LONG)
EditStreamSetInfoA()
HRESULT WINAPI EditStreamSetInfoA (PAVISTREAM , LPAVISTREAMINFOA , LONG)
EditStreamSetInfoW()
HRESULT WINAPI EditStreamSetInfoW (PAVISTREAM , LPAVISTREAMINFOW , LONG)
EditStreamSetNameA()
HRESULT WINAPI EditStreamSetNameA (PAVISTREAM , LPCSTR)
EditStreamSetNameW()
HRESULT WINAPI EditStreamSetNameW (PAVISTREAM , LPCWSTR)
ICClose()
LRESULT VFWAPI ICClose (HIC hic)
ICCompress()
DWORD VFWAPIV ICCompress (HIC , DWORD , LPBITMAPINFOHEADER , LPVOID , LPBITMAPINFOHEADER , LPVOID , LPDWORD , LPDWORD , LONG , DWORD , DWORD , LPBITMAPINFOHEADER , LPVOID)
ICCompressorChoose()
BOOL VFWAPI ICCompressorChoose (HWND , UINT , LPVOID , LPVOID , PCOMPVARS , LPSTR)
ICCompressorFree()
void VFWAPI ICCompressorFree (PCOMPVARS)
ICDecompress()
DWORD VFWAPIV ICDecompress (HIC , DWORD , LPBITMAPINFOHEADER , LPVOID , LPBITMAPINFOHEADER , LPVOID)
ICDecompressEx()
static __inline LRESULT ICDecompressEx (HIC hic, DWORD dwFlags, LPBITMAPINFOHEADER lpbiSrc, LPVOID lpSrc, INT xSrc, INT ySrc, INT dxSrc, INT dySrc, LPBITMAPINFOHEADER lpbiDst, LPVOID lpDst, INT xDst, INT yDst, INT dxDst, INT dyDst) static
Definition at line 1077 of file vfw.h.
 {
     ICDECOMPRESSEX ic;
     ic.dwFlags = dwFlags;
     ic.lpbiSrc = lpbiSrc;
     ic.lpSrc = lpSrc;
     ic.xSrc = xSrc;
     ic.ySrc = ySrc;
     ic.dxSrc = dxSrc;
     ic.dySrc = dySrc;
     ic.lpbiDst = lpbiDst;
     ic.lpDst = lpDst;
     ic.xDst = xDst;
     ic.yDst = yDst;
     ic.dxDst = dxDst;
     ic.dyDst = dyDst;
     return ICSendMessage(hic,ICM_DECOMPRESSEX,(DWORD)&ic,sizeof(ic));
 }
References ICDECOMPRESSEX::dwFlags, ICDECOMPRESSEX::dxDst, ICDECOMPRESSEX::dxSrc, ICDECOMPRESSEX::dyDst, ICDECOMPRESSEX::dySrc, ICM_DECOMPRESSEX, ICSendMessage(), ICDECOMPRESSEX::lpbiDst, ICDECOMPRESSEX::lpbiSrc, ICDECOMPRESSEX::lpDst, ICDECOMPRESSEX::lpSrc, ICDECOMPRESSEX::xDst, ICDECOMPRESSEX::xSrc, ICDECOMPRESSEX::yDst, and ICDECOMPRESSEX::ySrc.
ICDecompressExBegin()
static __inline LRESULT ICDecompressExBegin (HIC hic, DWORD dwFlags, LPBITMAPINFOHEADER lpbiSrc, LPVOID lpSrc, INT xSrc, INT ySrc, INT dxSrc, INT dySrc, LPBITMAPINFOHEADER lpbiDst, LPVOID lpDst, INT xDst, INT yDst, INT dxDst, INT dyDst) static
Definition at line 1096 of file vfw.h.
 {
     ICDECOMPRESSEX ic;
     ic.dwFlags = dwFlags;
     ic.lpbiSrc = lpbiSrc;
     ic.lpSrc = lpSrc;
     ic.xSrc = xSrc;
     ic.ySrc = ySrc;
     ic.dxSrc = dxSrc;
     ic.dySrc = dySrc;
     ic.lpbiDst = lpbiDst;
     ic.lpDst = lpDst;
     ic.xDst = xDst;
     ic.yDst = yDst;
     ic.dxDst = dxDst;
     ic.dyDst = dyDst;
     return ICSendMessage(hic,ICM_DECOMPRESSEX_BEGIN,(DWORD)&ic,sizeof(ic));
 }
References ICDECOMPRESSEX::dwFlags, ICDECOMPRESSEX::dxDst, ICDECOMPRESSEX::dxSrc, ICDECOMPRESSEX::dyDst, ICDECOMPRESSEX::dySrc, ICM_DECOMPRESSEX_BEGIN, ICSendMessage(), ICDECOMPRESSEX::lpbiDst, ICDECOMPRESSEX::lpbiSrc, ICDECOMPRESSEX::lpDst, ICDECOMPRESSEX::lpSrc, ICDECOMPRESSEX::xDst, ICDECOMPRESSEX::xSrc, ICDECOMPRESSEX::yDst, and ICDECOMPRESSEX::ySrc.
ICDecompressExQuery()
static __inline LRESULT ICDecompressExQuery (HIC hic, DWORD dwFlags, LPBITMAPINFOHEADER lpbiSrc, LPVOID lpSrc, INT xSrc, INT ySrc, INT dxSrc, INT dySrc, LPBITMAPINFOHEADER lpbiDst, LPVOID lpDst, INT xDst, INT yDst, INT dxDst, INT dyDst) static
Definition at line 1115 of file vfw.h.
 {
     ICDECOMPRESSEX ic;
     ic.dwFlags = dwFlags;
     ic.lpbiSrc = lpbiSrc;
     ic.lpSrc = lpSrc;
     ic.xSrc = xSrc;
     ic.ySrc = ySrc;
     ic.dxSrc = dxSrc;
     ic.dySrc = dySrc;
     ic.lpbiDst = lpbiDst;
     ic.lpDst = lpDst;
     ic.xDst = xDst;
     ic.yDst = yDst;
     ic.dxDst = dxDst;
     ic.dyDst = dyDst;
     return ICSendMessage(hic,ICM_DECOMPRESSEX_QUERY,(DWORD)&ic,sizeof(ic));
 }
References ICDECOMPRESSEX::dwFlags, ICDECOMPRESSEX::dxDst, ICDECOMPRESSEX::dxSrc, ICDECOMPRESSEX::dyDst, ICDECOMPRESSEX::dySrc, ICM_DECOMPRESSEX_QUERY, ICSendMessage(), ICDECOMPRESSEX::lpbiDst, ICDECOMPRESSEX::lpbiSrc, ICDECOMPRESSEX::lpDst, ICDECOMPRESSEX::lpSrc, ICDECOMPRESSEX::xDst, ICDECOMPRESSEX::xSrc, ICDECOMPRESSEX::yDst, and ICDECOMPRESSEX::ySrc.
ICDraw()
DWORD VFWAPIV ICDraw (HIC , DWORD , LPVOID , LPVOID , DWORD , LONG)
ICDrawBegin()
DWORD VFWAPIV ICDrawBegin (HIC , DWORD , HPALETTE , HWND , HDC , INT , INT , INT , INT , LPBITMAPINFOHEADER , INT , INT , INT , INT , DWORD , DWORD)
ICDrawSuggestFormat()
static __inline LRESULT ICDrawSuggestFormat (HIC hic, LPBITMAPINFOHEADER lpbiIn, LPBITMAPINFOHEADER lpbiOut, INT dxSrc, INT dySrc, INT dxDst, INT dyDst, HIC hicDecomp) static
Definition at line 1055 of file vfw.h.
 {
     ICDRAWSUGGEST ic;
     ic.lpbiIn = lpbiIn;
     ic.lpbiSuggest = lpbiOut;
     ic.dxSrc = dxSrc;
     ic.dySrc = dySrc;
     ic.dxDst = dxDst;
     ic.dyDst = dyDst;
     ic.hicDecompressor = hicDecomp;
     return ICSendMessage(hic,ICM_DRAW_SUGGESTFORMAT,(DWORD)&ic,sizeof(ic));
 }
References ICDRAWSUGGEST::dxDst, ICDRAWSUGGEST::dxSrc, ICDRAWSUGGEST::dyDst, ICDRAWSUGGEST::dySrc, ICDRAWSUGGEST::hicDecompressor, ICM_DRAW_SUGGESTFORMAT, ICSendMessage(), ICDRAWSUGGEST::lpbiIn, and ICDRAWSUGGEST::lpbiSuggest.
ICGetDefaultKeyFrameRate()
static __inline DWORD ICGetDefaultKeyFrameRate (HIC hic) static
Definition at line 1048 of file vfw.h.
 {
    DWORD dwICValue;
    ICSendMessage(hic, ICM_GETDEFAULTKEYFRAMERATE, (DWORD)(LPVOID)&dwICValue, sizeof(DWORD));
    return dwICValue;
 }
References ICM_GETDEFAULTKEYFRAMERATE, and ICSendMessage().
ICGetDefaultQuality()
static __inline DWORD ICGetDefaultQuality (HIC hic) static
Definition at line 1041 of file vfw.h.
 {
    DWORD dwICValue;
    ICSendMessage(hic, ICM_GETDEFAULTQUALITY, (DWORD)(LPVOID)&dwICValue, sizeof(DWORD));
    return dwICValue;
 }
References ICM_GETDEFAULTQUALITY, and ICSendMessage().
ICGetDisplayFormat()
HIC VFWAPI ICGetDisplayFormat (HIC , LPBITMAPINFOHEADER , LPBITMAPINFOHEADER , INT , INT , INT)
ICGetInfo()
LRESULT VFWAPI ICGetInfo (HIC , ICINFO * , DWORD)
ICImageCompress()
HANDLE VFWAPI ICImageCompress (HIC , UINT , LPBITMAPINFO , LPVOID , LPBITMAPINFO , LONG , LONG *)
ICImageDecompress()
HANDLE VFWAPI ICImageDecompress (HIC , UINT , LPBITMAPINFO , LPVOID , LPBITMAPINFO)
ICInfo()
BOOL VFWAPI ICInfo (DWORD , DWORD , ICINFO *)
ICInstall()
BOOL VFWAPI ICInstall (DWORD , DWORD , LPARAM , LPSTR , UINT)
ICLocate()
HIC VFWAPI ICLocate (DWORD , DWORD , LPBITMAPINFOHEADER , LPBITMAPINFOHEADER , WORD)
ICOpen()
HIC VFWAPI ICOpen (DWORD , DWORD , UINT)
ICOpenFunction()
HIC VFWAPI ICOpenFunction (DWORD , DWORD , UINT , FARPROC)
ICRemove()
BOOL VFWAPI ICRemove (DWORD , DWORD , UINT)
ICSendMessage()
LRESULT VFWAPI ICSendMessage (HIC , UINT , DWORD , DWORD)
Referenced by ICDecompressEx(), ICDecompressExBegin(), ICDecompressExQuery(), ICDrawSuggestFormat(), ICGetDefaultKeyFrameRate(), ICGetDefaultQuality(), and ICSetStatusProc().
ICSeqCompressFrame()
LPVOID VFWAPI ICSeqCompressFrame (PCOMPVARS , UINT , LPVOID , BOOL * , LONG *)
ICSeqCompressFrameEnd()
void VFWAPI ICSeqCompressFrameEnd (PCOMPVARS)
ICSeqCompressFrameStart()
BOOL VFWAPI ICSeqCompressFrameStart (PCOMPVARS , LPBITMAPINFO)
ICSetStatusProc()
static __inline LRESULT ICSetStatusProc (HIC hic, DWORD dwFlags, LRESULT lParam, LONG(CALLBACK *fpfnStatus)(LPARAM, UINT, LONG)) static
Definition at line 1068 of file vfw.h.
 {
     ICSETSTATUSPROC ic;
     ic.dwFlags = dwFlags;
     ic.lParam = lParam;
     ic.Status = fpfnStatus;
     return ICSendMessage(hic,ICM_SET_STATUS_PROC,(DWORD)&ic,sizeof(ic));
 }
References ICSETSTATUSPROC::dwFlags, ICM_SET_STATUS_PROC, ICSendMessage(), and ICSETSTATUSPROC::lParam.
InitVFW()
LONG VFWAPI InitVFW (VOID)
MCIWndCreateA()
HWND VFWAPIV MCIWndCreateA (HWND , HINSTANCE , DWORD , LPCSTR)
MCIWndCreateW()
HWND VFWAPIV MCIWndCreateW (HWND , HINSTANCE , DWORD , LPCWSTR)
TermVFW()
LONG VFWAPI TermVFW (VOID)
VideoForWindowsVersion()
DWORD VFWAPI VideoForWindowsVersion (VOID)