ZEQ2-Lite: Source/Shared/common.c File Reference
common.c File Reference
#include "q_shared.h"
#include "qcommon.h"
#include <setjmp.h>
#include <netinet/in.h>
#include <sys/stat.h>
Data Structures
struct hunkblock_s
struct hunkHeader_t
struct hunkUsed_t
struct memblock_s
struct memstatic_s
struct memzone_t
struct zonedebug_s
Macros
#define Com_DetectSSE()
#define DEF_COMHUNKMEGS 512
#define DEF_COMHUNKMEGS_S XSTRING(DEF_COMHUNKMEGS)
#define DEF_COMZONEMEGS 48
#define DEF_COMZONEMEGS_S XSTRING(DEF_COMZONEMEGS)
#define HUNK_FREE_MAGIC 0x89537893
#define HUNK_MAGIC 0x89537892
#define MASK_QUEUED_EVENTS (MAX_QUEUED_EVENTS - 1)
#define MAX_CONSOLE_LINES 32
#define MAX_NUM_ARGVS 50
#define MAX_PUSHED_EVENTS 1024
#define MAX_QUEUED_EVENTS 256
#define MIN_COMHUNKMEGS 256
#define MIN_DEDICATED_COMHUNKMEGS 1
#define MINFRAGMENT 64
#define ZONEID 0x1d4a11
Functions
void CIN_CloseAllVideos (void)
void CL_ShutdownCGame (void)
void CL_ShutdownUI (void)
qboolean Com_AddStartupCommands (void)
void Com_BeginRedirect (char *buffer, int buffersize, void(*flush)(char *))
static void Com_Crash_f (void)
static void Com_DetectAltivec (void)
void QDECL Com_DPrintf (const char *fmt,...)
void Com_EndRedirect (void)
void QDECL Com_Error (int code, const char *fmt,...)
static void Com_Error_f (void)
int Com_EventLoop (void)
void Com_ExecuteCfg (void)
int Com_Filter (char *filter, char *name, int casesensitive)
int Com_FilterPath (char *filter, char *name, int casesensitive)
void Com_Frame (void)
static void Com_Freeze_f (void)
void Com_GameRestart (int checksumFeed, qboolean disconnect)
void Com_GameRestart_f (void)
sysEvent_t Com_GetEvent (void)
sysEvent_t Com_GetRealEvent (void)
sysEvent_t Com_GetSystemEvent (void)
int Com_HashKey (char *string, int maxlen)
void Com_Init (char *commandLine)
void Com_InitHunkMemory (void)
void Com_InitJournaling (void)
void Com_InitPushEvent (void)
static void Com_InitRand (void)
void Com_InitSmallZoneMemory (void)
void Com_InitZoneMemory (void)
qboolean Com_IsVoipTarget (uint8_t *voipTargets, int voipTargetsSize, int clientNum)
void Com_Meminfo_f (void)
int Com_Milliseconds (void)
int Com_ModifyMsec (int msec)
void Com_ParseCommandLine (char *commandLine)
void QDECL Com_Printf (const char *fmt,...)
void Com_PushEvent (sysEvent_t *event)
void Com_QueueEvent (int time, sysEventType_t type, int value, int value2, int ptrLength, void *ptr)
void Com_Quit_f (void)
void Com_RandomBytes (byte *string, int len)
void Com_ReadFromPipe (void)
int Com_RealTime (qtime_t *qtime)
void Com_RunAndTimeServerPacket (netadr_t *evFrom, msg_t *buf)
qboolean Com_SafeMode (void)
void Com_Setenv_f (void)
void Com_Shutdown (void)
void Com_StartupVariable (const char *match)
char * Com_StringContains (char *str1, char *str2, int casesensitive)
int Com_TimeVal (int minMsec)
void Com_TouchMemory (void)
void Com_WriteConfig_f (void)
void Com_WriteConfigToFile (const char *filename)
void Com_WriteConfiguration (void)
char * CopyString (const char *in)
void Field_AutoComplete (field_t *field)
void Field_Clear (field_t *edit)
static qboolean Field_Complete (void)
void Field_CompleteCommand (char *cmd, qboolean doCommands, qboolean doCvars)
void Field_CompleteFilename (const char *dir, const char *ext, qboolean stripExt, qboolean allowNonPureFilesOnDisk)
void Field_CompleteKeyname (void)
static char * Field_FindFirstSeparator (char *s)
static void FindMatches (const char *s)
void * Hunk_AllocateTempMemory (int size)
void * Hunk_AllocDebug (int size, ha_pref preference, char *label, char *file, int line)
qboolean Hunk_CheckMark (void)
void Hunk_Clear (void)
void Hunk_ClearTempMemory (void)
void Hunk_ClearToMark (void)
void Hunk_FreeTempMemory (void *buf)
void Hunk_Log (void)
int Hunk_MemoryRemaining (void)
void Hunk_SetMark (void)
void Hunk_SmallLog (void)
static void Hunk_SwapBanks (void)
void Info_Print (const char *s)
static void PrintCvarMatches (const char *s)
static void PrintMatches (const char *s)
void * S_MallocDebug (int size, char *label, char *file, int line)
void SV_ShutdownGameProgs (void)
int Z_AvailableMemory (void)
int Z_AvailableZoneMemory (memzone_t *zone)
void Z_CheckHeap (void)
void Z_ClearZone (memzone_t *zone, int size)
void Z_Free (void *ptr)
void Z_FreeTags (int tag)
void Z_LogHeap (void)
void Z_LogZoneHeap (memzone_t *zone, char *name)
void * Z_MallocDebug (int size, char *label, char *file, int line)
void * Z_TagMallocDebug (int size, int tag, char *label, char *file, int line)
Variables
jmp_buf abortframe
cvar_t * cl_packetdelay
cvar_t * cl_paused
cvar_t * com_abnormalExit
cvar_t * com_altivec
cvar_t * com_ansiColor
int com_argc
char * com_argv [MAX_NUM_ARGVS+1]
cvar_t * com_basegame
cvar_t * com_blood
cvar_t * com_buildScript
cvar_t * com_busyWait
cvar_t * com_cameraMode
cvar_t * com_cl_running
char * com_consoleLines [MAX_CONSOLE_LINES]
cvar_t * com_dedicated
cvar_t * com_developer
qboolean com_errorEntered = qfalse
char com_errorMessage [MAXPRINTMSG]
cvar_t * com_fixedtime
int com_frameNumber
int com_frameTime
qboolean com_fullyInitialized = qfalse
cvar_t * com_gamename
qboolean com_gameRestarting = qfalse
cvar_t * com_homepath
cvar_t * com_introPlayed
cvar_t * com_journal
fileHandle_t com_journalDataFile
fileHandle_t com_journalFile
cvar_t * com_logfile
cvar_t * com_maxfps
cvar_t * com_maxfpsMinimized
cvar_t * com_maxfpsUnfocused
cvar_t * com_minimized
int com_numConsoleLines
cvar_t * com_pipefile
cvar_t * com_protocol
static sysEvent_t com_pushedEvents [MAX_PUSHED_EVENTS]
static int com_pushedEventsHead = 0
static int com_pushedEventsTail = 0
cvar_t * com_showtrace
cvar_t * com_speeds
cvar_t * com_sv_running
cvar_t * com_timedemo
cvar_t * com_timescale
cvar_t * com_unfocused
cvar_t * com_version
static field_t * completionField
static const char * completionString
FILE * debuglogfile
int demo_protocols []
memstatic_t emptystring
static int eventHead = 0
static sysEvent_t eventQueue [MAX_QUEUED_EVENTS]
static int eventTail = 0
static hunkUsed_t hunk_high
static hunkUsed_t hunk_low
static hunkUsed_t * hunk_permanent
static hunkUsed_t * hunk_temp
static hunkblock_t * hunkblocks
static fileHandle_t logfile
memzone_t * mainzone
static int matchCount
memstatic_t numberstring []
static fileHandle_t pipefile
static char * rd_buffer
static int rd_buffersize
static void(* rd_flush)(char *buffer)
static byte * s_hunkData = NULL
static int s_hunkTotal
static int s_smallZoneTotal
static int s_zoneTotal
static char shortestMatch [MAX_TOKEN_CHARS]
memzone_t * smallzone
cvar_t * sv_packetdelay
cvar_t * sv_paused
int time_backend
int time_frontend
int time_game
Macro Definition Documentation
Com_DetectSSE
#define Com_DetectSSE ()
Definition at line 2484 of file common.c.
DEF_COMHUNKMEGS
#define DEF_COMHUNKMEGS 512
Definition at line 41 of file common.c.
DEF_COMHUNKMEGS_S
#define DEF_COMHUNKMEGS_S XSTRING(DEF_COMHUNKMEGS)
Definition at line 43 of file common.c.
DEF_COMZONEMEGS
#define DEF_COMZONEMEGS 48
Definition at line 42 of file common.c.
DEF_COMZONEMEGS_S
#define DEF_COMZONEMEGS_S XSTRING(DEF_COMZONEMEGS)
Definition at line 44 of file common.c.
HUNK_FREE_MAGIC
#define HUNK_FREE_MAGIC 0x89537893
Definition at line 1227 of file common.c.
HUNK_MAGIC
#define HUNK_MAGIC 0x89537892
Definition at line 1226 of file common.c.
MASK_QUEUED_EVENTS
#define MASK_QUEUED_EVENTS (MAX_QUEUED_EVENTS - 1)
Definition at line 1925 of file common.c.
MAX_CONSOLE_LINES
#define MAX_CONSOLE_LINES 32
Definition at line 374 of file common.c.
MAX_NUM_ARGVS
#define MAX_NUM_ARGVS 50
Definition at line 37 of file common.c.
MAX_PUSHED_EVENTS
#define MAX_PUSHED_EVENTS 1024
Definition at line 1881 of file common.c.
MAX_QUEUED_EVENTS
#define MAX_QUEUED_EVENTS 256
Definition at line 1924 of file common.c.
MIN_COMHUNKMEGS
#define MIN_COMHUNKMEGS 256
Definition at line 40 of file common.c.
MIN_DEDICATED_COMHUNKMEGS
#define MIN_DEDICATED_COMHUNKMEGS 1
Definition at line 39 of file common.c.
MINFRAGMENT
#define MINFRAGMENT 64
Definition at line 747 of file common.c.
ZONEID
#define ZONEID 0x1d4a11
Definition at line 746 of file common.c.
Function Documentation
CIN_CloseAllVideos()
void CIN_CloseAllVideos (void)
Definition at line 138 of file cl_cin.c.
{
     int     i;
     for ( i = 0 ; i < MAX_VIDEO_HANDLES ; i++ ) {
         if (cinTable[i].fileName[0] != 0 ) {
             CIN_StopCinematic(i);
         }
     }
 }
References CIN_StopCinematic(), cinTable, and MAX_VIDEO_HANDLES.
CL_ShutdownCGame()
void CL_ShutdownCGame (void)
Definition at line 395 of file cl_cgame.c.
{
     Key_SetCatcher( Key_GetCatcher( ) & ~KEYCATCH_CGAME );
     cls.cgameStarted = qfalse;
     if ( !cgvm ) {
         return;
     }
     VM_Call( cgvm, CG_SHUTDOWN );
     VM_Free( cgvm );
     cgvm = NULL;
 }
References CG_SHUTDOWN, clientStatic_t::cgameStarted, cgvm, cls, Key_GetCatcher(), Key_SetCatcher(), KEYCATCH_CGAME, NULL, qfalse, VM_Call(), and VM_Free().
Referenced by CL_ShutdownAll(), and CL_Vid_Restart_f().
CL_ShutdownUI()
void CL_ShutdownUI (void)
Definition at line 999 of file cl_ui.c.
{
     Key_SetCatcher( Key_GetCatcher( ) & ~KEYCATCH_UI );
     cls.uiStarted = qfalse;
     if ( !uivm ) {
         return;
     }
     VM_Call( uivm, UI_SHUTDOWN );
     VM_Free( uivm );
     uivm = NULL;
 }
References cls, Key_GetCatcher(), Key_SetCatcher(), KEYCATCH_UI, NULL, qfalse, UI_SHUTDOWN, clientStatic_t::uiStarted, uivm, VM_Call(), and VM_Free().
Referenced by CL_ShutdownAll(), and CL_Vid_Restart_f().
Com_AddStartupCommands()
qboolean Com_AddStartupCommands (void)
Definition at line 477 of file common.c.
{
     int     i;
     qboolean    added;
     added = qfalse;
     // quote every token, so args with semicolons can work
     for (i=0 ; i < com_numConsoleLines ; i++) {
         if ( !com_consoleLines[i] || !com_consoleLines[i][0] ) {
             continue;
         }
         // set commands already added with Com_StartupVariable
         if ( !Q_stricmpn( com_consoleLines[i], "set", 3 ) ) {
             continue;
         }
         added = qtrue;
         Cbuf_AddText( com_consoleLines[i] );
         Cbuf_AddText( "\n" );
     }
     return added;
 }
References Cbuf_AddText(), com_consoleLines, com_numConsoleLines, Q_stricmpn(), qfalse, and qtrue.
Com_BeginRedirect()
void Com_BeginRedirect (char * buffer, int buffersize, void(*)(char *) flush)
Definition at line 127 of file common.c.
 {
     if (!buffer || !buffersize || !flush)
         return;
     rd_buffer = buffer;
     rd_buffersize = buffersize;
     rd_flush = flush;
     *rd_buffer = 0;
 }
References rd_buffer, rd_buffersize, and rd_flush.
Com_Crash_f()
static void Com_Crash_f (void) static
Definition at line 2290 of file common.c.
{
     * ( volatile int * ) 0 = 0x12345678;
 }
Referenced by Com_Init().
Com_DetectAltivec()
static void Com_DetectAltivec (void) static
Definition at line 2424 of file common.c.
 {
     // Only detect if user hasn't forcibly disabled it.
     if (com_altivec->integer) {
         static qboolean altivec = qfalse;
         static qboolean detected = qfalse;
         if (!detected) {
             altivec = ( Sys_GetProcessorFeatures( ) & CF_ALTIVEC );
             detected = qtrue;
         }
         if (!altivec) {
             Cvar_Set( "com_altivec", "0" );  // we don't have it! Disable support!
         }
     }
 }
References CF_ALTIVEC, com_altivec, Cvar_Set(), qfalse, qtrue, and Sys_GetProcessorFeatures().
Referenced by Com_Frame(), and Com_Init().
Com_DPrintf()
void QDECL Com_DPrintf (const char * fmt, ...)
Definition at line 236 of file common.c.
{
     va_list     argptr;
     char        msg[MAXPRINTMSG];
     if ( !com_developer || !com_developer->integer ) {
         return;         // don't confuse non-developers with techie stuff...
     }
     va_start (argptr,fmt);
     Q_vsnprintf (msg, sizeof(msg), fmt, argptr);
     va_end (argptr);
     Com_Printf ("%s", msg);
 }
References com_developer, Com_Printf(), fmt, MAXPRINTMSG, and Q_vsnprintf.
Com_EndRedirect()
void Com_EndRedirect (void)
Definition at line 138 of file common.c.
 {
     if ( rd_flush ) {
         rd_flush(rd_buffer);
     }
     rd_buffer = NULL;
     rd_buffersize = 0;
     rd_flush = NULL;
 }
References NULL, rd_buffer, rd_buffersize, and rd_flush.
Com_Error()
void QDECL Com_Error (int code, const char * fmt, ...)
Definition at line 259 of file common.c.
{
     va_list     argptr;
     static int  lastErrorTime;
     static int  errorCount;
     int         currentTime;
     if(com_errorEntered)
         Sys_Error("recursive error after: %s", com_errorMessage);
     com_errorEntered = qtrue;
     Cvar_Set("com_errorCode", va("%i", code));
     // when we are running automated scripts, make sure we
     // know if anything failed
     if ( com_buildScript && com_buildScript->integer ) {
         code = ERR_FATAL;
     }
     // if we are getting a solid stream of ERR_DROP, do an ERR_FATAL
     currentTime = Sys_Milliseconds();
     if ( currentTime - lastErrorTime < 100 ) {
         if ( ++errorCount > 3 ) {
             code = ERR_FATAL;
         }
     } else {
         errorCount = 0;
     }
     lastErrorTime = currentTime;
     va_start (argptr,fmt);
     Q_vsnprintf (com_errorMessage, sizeof(com_errorMessage),fmt,argptr);
     va_end (argptr);
     if (code != ERR_DISCONNECT)
         Cvar_Set("com_errorMessage", com_errorMessage);
     if (code == ERR_DISCONNECT || code == ERR_SERVERDISCONNECT) {
         VM_Forced_Unload_Start();
         SV_Shutdown( "Server disconnected" );
         CL_Disconnect( qtrue );
         CL_FlushMemory( );
         VM_Forced_Unload_Done();
         // make sure we can get at our local stuff
         FS_PureServerSetLoadedPaks("", "");
         com_errorEntered = qfalse;
         longjmp (abortframe, -1);
     } else if (code == ERR_DROP) {
         Com_Printf ("********************\nERROR: %s\n********************\n", com_errorMessage);
         VM_Forced_Unload_Start();
         SV_Shutdown (va("Server crashed: %s",  com_errorMessage));
         CL_Disconnect( qtrue );
         CL_FlushMemory( );
         VM_Forced_Unload_Done();
         FS_PureServerSetLoadedPaks("", "");
         com_errorEntered = qfalse;
         longjmp (abortframe, -1);
     } else {
         VM_Forced_Unload_Start();
         CL_Shutdown(va("Client fatal crashed: %s", com_errorMessage), qtrue, qtrue);
         SV_Shutdown(va("Server fatal crashed: %s", com_errorMessage));
         VM_Forced_Unload_Done();
     }
     Com_Shutdown ();
     Sys_Error ("%s", com_errorMessage);
 }
References abortframe, CL_Disconnect(), CL_FlushMemory(), CL_Shutdown(), com_buildScript, com_errorEntered, com_errorMessage, Com_Printf(), Com_Shutdown(), Cvar_Set(), ERR_DISCONNECT, ERR_DROP, ERR_FATAL, ERR_SERVERDISCONNECT, errorCount, fmt, FS_PureServerSetLoadedPaks(), Q_vsnprintf, qfalse, qtrue, SV_Shutdown(), Sys_Error(), Sys_Milliseconds(), va(), VM_Forced_Unload_Done(), and VM_Forced_Unload_Start().
Com_Error_f()
static void Com_Error_f (void) static
Definition at line 2246 of file common.c.
{
     if ( Cmd_Argc() > 1 ) {
         Com_Error( ERR_DROP, "Testing drop error" );
     } else {
         Com_Error( ERR_FATAL, "Testing fatal error" );
     }
 }
References Cmd_Argc(), Com_Error(), ERR_DROP, and ERR_FATAL.
Referenced by Com_Init().
Com_EventLoop()
int Com_EventLoop (void)
Definition at line 2153 of file common.c.
{
     sysEvent_t  ev;
     netadr_t    evFrom;
     byte        bufData[MAX_MSGLEN];
     msg_t       buf;
     MSG_Init( &buf, bufData, sizeof( bufData ) );
     while ( 1 ) {
         ev = Com_GetEvent();
         // if no more events are available
         if ( ev.evType == SE_NONE ) {
             // manually send packet events for the loopback channel
             while ( NET_GetLoopPacket( NS_CLIENT, &evFrom, &buf ) ) {
                 CL_PacketEvent( evFrom, &buf );
             }
             while ( NET_GetLoopPacket( NS_SERVER, &evFrom, &buf ) ) {
                 // if the server just shut down, flush the events
                 if ( com_sv_running->integer ) {
                     Com_RunAndTimeServerPacket( &evFrom, &buf );
                 }
             }
             return ev.evTime;
         }
         switch(ev.evType)
         {
             case SE_KEY:
                 CL_KeyEvent( ev.evValue, ev.evValue2, ev.evTime );
             break;
             case SE_CHAR:
                 CL_CharEvent( ev.evValue );
             break;
             case SE_MOUSE:
                 CL_MouseEvent( ev.evValue, ev.evValue2, ev.evTime );
             break;
             case SE_JOYSTICK_AXIS:
                 CL_JoystickEvent( ev.evValue, ev.evValue2, ev.evTime );
             break;
             case SE_CONSOLE:
                 Cbuf_AddText( (char *)ev.evPtr );
                 Cbuf_AddText( "\n" );
             break;
             default:
                 Com_Error( ERR_FATAL, "Com_EventLoop: bad event type %i", ev.evType );
             break;
         }
         // free any block data
         if ( ev.evPtr ) {
             Z_Free( ev.evPtr );
         }
     }
     return 0;   // never reached
 }
References Cbuf_AddText(), CL_CharEvent(), CL_JoystickEvent(), CL_KeyEvent(), CL_MouseEvent(), CL_PacketEvent(), Com_Error(), Com_GetEvent(), Com_RunAndTimeServerPacket(), com_sv_running, ERR_FATAL, sysEvent_t::evPtr, sysEvent_t::evTime, sysEvent_t::evType, sysEvent_t::evValue, sysEvent_t::evValue2, MAX_MSGLEN, MSG_Init(), NET_GetLoopPacket(), NS_CLIENT, NS_SERVER, SE_CHAR, SE_CONSOLE, SE_JOYSTICK_AXIS, SE_KEY, SE_MOUSE, SE_NONE, and Z_Free().
Com_ExecuteCfg()
void Com_ExecuteCfg (void)
Definition at line 2331 of file common.c.
 {
     Cbuf_ExecuteText(EXEC_NOW, "exec default.cfg\n");
     Cbuf_Execute(); // Always execute after exec to prevent text buffer overflowing
     if(!Com_SafeMode())
     {
         // skip the q3config.cfg and autoexec.cfg if "safe" is on the command line
         Cbuf_ExecuteText(EXEC_NOW, "exec " Q3CONFIG_CFG "\n");
         Cbuf_Execute();
         Cbuf_ExecuteText(EXEC_NOW, "exec autoexec.cfg\n");
         Cbuf_Execute();
     }
 }
References Cbuf_Execute(), Cbuf_ExecuteText(), Com_SafeMode(), EXEC_NOW, and Q3CONFIG_CFG.
Com_Filter()
int Com_Filter (char * filter, char * name, int casesensitive)
Definition at line 580 of file common.c.
 {
     char buf[MAX_TOKEN_CHARS];
     char *ptr;
     int i, found;
     while(*filter) {
         if (*filter == '*') {
             filter++;
             for (i = 0; *filter; i++) {
                 if (*filter == '*' || *filter == '?') break;
                 buf[i] = *filter;
                 filter++;
             }
             buf[i] = '\0';
             if (strlen(buf)) {
                 ptr = Com_StringContains(name, buf, casesensitive);
                 if (!ptr) return qfalse;
                 name = ptr + strlen(buf);
             }
         }
         else if (*filter == '?') {
             filter++;
             name++;
         }
         else if (*filter == '[' && *(filter+1) == '[') {
             filter++;
         }
         else if (*filter == '[') {
             filter++;
             found = qfalse;
             while(*filter && !found) {
                 if (*filter == ']' && *(filter+1) != ']') break;
                 if (*(filter+1) == '-' && *(filter+2) && (*(filter+2) != ']' || *(filter+3) == ']')) {
                     if (casesensitive) {
                         if (*name >= *filter && *name <= *(filter+2)) found = qtrue;
                     }
                     else {
                         if (toupper(*name) >= toupper(*filter) &&
                             toupper(*name) <= toupper(*(filter+2))) found = qtrue;
                     }
                     filter += 3;
                 }
                 else {
                     if (casesensitive) {
                         if (*filter == *name) found = qtrue;
                     }
                     else {
                         if (toupper(*filter) == toupper(*name)) found = qtrue;
                     }
                     filter++;
                 }
             }
             if (!found) return qfalse;
             while(*filter) {
                 if (*filter == ']' && *(filter+1) != ']') break;
                 filter++;
             }
             filter++;
             name++;
         }
         else {
             if (casesensitive) {
                 if (*filter != *name) return qfalse;
             }
             else {
                 if (toupper(*filter) != toupper(*name)) return qfalse;
             }
             filter++;
             name++;
         }
     }
     return qtrue;
 }
References Com_StringContains(), MAX_TOKEN_CHARS, ptr(), qfalse, and qtrue.
Com_FilterPath()
int Com_FilterPath (char * filter, char * name, int casesensitive)
Definition at line 660 of file common.c.
 {
     int i;
     char new_filter[MAX_QPATH];
     char new_name[MAX_QPATH];
     for (i = 0; i < MAX_QPATH-1 && filter[i]; i++) {
         if ( filter[i] == '\\' || filter[i] == ':' ) {
             new_filter[i] = '/';
         }
         else {
             new_filter[i] = filter[i];
         }
     }
     new_filter[i] = '\0';
     for (i = 0; i < MAX_QPATH-1 && name[i]; i++) {
         if ( name[i] == '\\' || name[i] == ':' ) {
             new_name[i] = '/';
         }
         else {
             new_name[i] = name[i];
         }
     }
     new_name[i] = '\0';
     return Com_Filter(new_filter, new_name, casesensitive);
 }
References Com_Filter(), and MAX_QPATH.
Com_Frame()
void Com_Frame (void)
Definition at line 2901 of file common.c.
{
     int     msec, minMsec;
     int     timeVal, timeValSV;
     static int  lastTime = 0, bias = 0;
     int     timeBeforeFirstEvents;
     int     timeBeforeServer;
     int     timeBeforeEvents;
     int     timeBeforeClient;
     int     timeAfter;
     if ( setjmp (abortframe) ) {
         return;         // an ERR_DROP was thrown
     }
     timeBeforeFirstEvents =0;
     timeBeforeServer =0;
     timeBeforeEvents =0;
     timeBeforeClient = 0;
     timeAfter = 0;
     // write config file if anything changed
     Com_WriteConfiguration();
     //
     // main event loop
     //
     if ( com_speeds->integer ) {
         timeBeforeFirstEvents = Sys_Milliseconds ();
     }
     // Figure out how much time we have
     if(!com_timedemo->integer)
     {
         if(com_dedicated->integer)
             minMsec = SV_FrameMsec();
         else
         {
             if(com_minimized->integer && com_maxfpsMinimized->integer > 0)
                 minMsec = 1000 / com_maxfpsMinimized->integer;
             else if(com_unfocused->integer && com_maxfpsUnfocused->integer > 0)
                 minMsec = 1000 / com_maxfpsUnfocused->integer;
             else if(com_maxfps->integer > 0)
                 minMsec = 1000 / com_maxfps->integer;
             else
                 minMsec = 1;
             timeVal = com_frameTime - lastTime;
             bias += timeVal - minMsec;
             if(bias > minMsec)
                 bias = minMsec;
             // Adjust minMsec if previous frame took too long to render so
             // that framerate is stable at the requested value.
             minMsec -= bias;
         }
     }
     else
         minMsec = 1;
     do
     {
         if(com_sv_running->integer)
         {
             timeValSV = SV_SendQueuedPackets();
             timeVal = Com_TimeVal(minMsec);
             if(timeValSV < timeVal)
                 timeVal = timeValSV;
         }
         else
             timeVal = Com_TimeVal(minMsec);
         if(com_busyWait->integer || timeVal < 1)
             NET_Sleep(0);
         else
             NET_Sleep(timeVal - 1);
     } while(Com_TimeVal(minMsec));
     lastTime = com_frameTime;
     com_frameTime = Com_EventLoop();
     msec = com_frameTime - lastTime;
     Cbuf_Execute ();
     if (com_altivec->modified)
     {
         Com_DetectAltivec();
         com_altivec->modified = qfalse;
     }
     // mess with msec if needed
     msec = Com_ModifyMsec(msec);
     //
     // server side
     //
     if ( com_speeds->integer ) {
         timeBeforeServer = Sys_Milliseconds ();
     }
     SV_Frame( msec );
     // if "dedicated" has been modified, start up
     // or shut down the client system.
     // Do this after the server may have started,
     // but before the client tries to auto-connect
     if ( com_dedicated->modified ) {
         // get the latched value
         Cvar_Get( "dedicated", "0", 0 );
         com_dedicated->modified = qfalse;
         if ( !com_dedicated->integer ) {
             SV_Shutdown( "dedicated set to 0" );
             CL_FlushMemory();
         }
     }
 #ifndef DEDICATED
     //
     // client system
     //
     //
     // run event loop a second time to get server to client packets
     // without a frame of latency
     //
     if ( com_speeds->integer ) {
         timeBeforeEvents = Sys_Milliseconds ();
     }
     Com_EventLoop();
     Cbuf_Execute ();
     //
     // client side
     //
     if ( com_speeds->integer ) {
         timeBeforeClient = Sys_Milliseconds ();
     }
     CL_Frame( msec );
     if ( com_speeds->integer ) {
         timeAfter = Sys_Milliseconds ();
     }
 #else
     if ( com_speeds->integer ) {
         timeAfter = Sys_Milliseconds ();
         timeBeforeEvents = timeAfter;
         timeBeforeClient = timeAfter;
     }
 #endif
     NET_FlushPacketQueue();
     //
     // report timing information
     //
     if ( com_speeds->integer ) {
         int         all, sv, ev, cl;
         all = timeAfter - timeBeforeServer;
         sv = timeBeforeEvents - timeBeforeServer;
         ev = timeBeforeServer - timeBeforeFirstEvents + timeBeforeClient - timeBeforeEvents;
         cl = timeAfter - timeBeforeClient;
         sv -= time_game;
         cl -= time_frontend + time_backend;
         Com_Printf ("frame:%i all:%3i sv:%3i ev:%3i cl:%3i gm:%3i rf:%3i bk:%3i\n",
                      com_frameNumber, all, sv, ev, cl, time_game, time_frontend, time_backend );
     }
     //
     // trace optimization tracking
     //
     if ( com_showtrace->integer ) {
         extern  int c_traces, c_brush_traces, c_patch_traces;
         extern  int c_pointcontents;
         Com_Printf ("%4i traces  (%ib %ip) %4i points\n", c_traces,
             c_brush_traces, c_patch_traces, c_pointcontents);
         c_traces = 0;
         c_brush_traces = 0;
         c_patch_traces = 0;
         c_pointcontents = 0;
     }
     Com_ReadFromPipe( );
     com_frameNumber++;
 }
References abortframe, c_brush_traces, c_patch_traces, c_pointcontents, c_traces, Cbuf_Execute(), cl, CL_FlushMemory(), CL_Frame(), com_altivec, com_busyWait, com_dedicated, Com_DetectAltivec(), Com_EventLoop(), com_frameNumber, com_frameTime, com_maxfps, com_maxfpsMinimized, com_maxfpsUnfocused, com_minimized, Com_ModifyMsec(), Com_Printf(), Com_ReadFromPipe(), com_showtrace, com_speeds, com_sv_running, com_timedemo, Com_TimeVal(), com_unfocused, Com_WriteConfiguration(), Cvar_Get(), NET_FlushPacketQueue(), NET_Sleep(), qfalse, sv, SV_Frame(), SV_FrameMsec(), SV_SendQueuedPackets(), SV_Shutdown(), Sys_Milliseconds(), time_backend, time_frontend, and time_game.
Com_Freeze_f()
static void Com_Freeze_f (void) static
Definition at line 2263 of file common.c.
{
     float   s;
     int     start, now;
     if ( Cmd_Argc() != 2 ) {
         Com_Printf( "freeze <seconds>\n" );
         return;
     }
     s = atof( Cmd_Argv(1) );
     start = Com_Milliseconds();
     while ( 1 ) {
         now = Com_Milliseconds();
         if ( ( now - start ) * 0.001 > s ) {
             break;
         }
     }
 }
References Cmd_Argc(), Cmd_Argv(), Com_Milliseconds(), and Com_Printf().
Referenced by Com_Init().
Com_GameRestart()
void Com_GameRestart (int checksumFeed, qboolean disconnect)
Definition at line 2354 of file common.c.
 {
     // make sure no recursion can be triggered
     if(!com_gameRestarting && com_fullyInitialized)
     {
         int clWasRunning;
         com_gameRestarting = qtrue;
         clWasRunning = com_cl_running->integer;
         // Kill server if we have one
         if(com_sv_running->integer)
             SV_Shutdown("Game directory changed");
         if(clWasRunning)
         {
             if(disconnect)
                 CL_Disconnect(qfalse);
             CL_Shutdown("Game directory changed", disconnect, qfalse);
         }
         FS_Restart(checksumFeed);
         // Clean out any user and VM created cvars
         Cvar_Restart(qtrue);
         Com_ExecuteCfg();
         if(disconnect)
         {
             // We don't want to change any network settings if gamedir
             // change was triggered by a connect to server because the
             // new network settings might make the connection fail.
             NET_Restart_f();
         }
         if(clWasRunning)
         {
             CL_Init();
             CL_StartHunkUsers(qfalse);
         }
         com_gameRestarting = qfalse;
     }
 }
References CL_Disconnect(), CL_Init(), CL_Shutdown(), CL_StartHunkUsers(), com_cl_running, Com_ExecuteCfg(), com_fullyInitialized, com_gameRestarting, com_sv_running, Cvar_Restart(), FS_Restart(), NET_Restart_f(), qfalse, qtrue, and SV_Shutdown().
Com_GameRestart_f()
void Com_GameRestart_f (void)
Definition at line 2408 of file common.c.
 {
     if(!FS_FilenameCompare(Cmd_Argv(1), com_basegame->string))
     {
         // This is the standard base game. Servers and clients should
         // use "" and not the standard basegame name because this messes
         // up pak file negotiation and lots of other stuff
         Cvar_Set("fs_game", "");
     }
     else
         Cvar_Set("fs_game", Cmd_Argv(1));
     Com_GameRestart(0, qtrue);
 }
References Cmd_Argv(), com_basegame, Com_GameRestart(), Cvar_Set(), FS_FilenameCompare(), and qtrue.
Com_GetEvent()
sysEvent_t Com_GetEvent (void)
Definition at line 2113 of file common.c.
{
     if ( com_pushedEventsHead > com_pushedEventsTail ) {
         com_pushedEventsTail++;
         return com_pushedEvents[ (com_pushedEventsTail-1) & (MAX_PUSHED_EVENTS-1) ];
     }
     return Com_GetRealEvent();
 }
References Com_GetRealEvent(), com_pushedEvents, com_pushedEventsHead, com_pushedEventsTail, and MAX_PUSHED_EVENTS.
Com_GetRealEvent()
sysEvent_t Com_GetRealEvent (void)
Definition at line 2022 of file common.c.
{
     int         r;
     sysEvent_t  ev;
     // either get an event from the system or the journal file
     if ( com_journal->integer == 2 ) {
         r = FS_Read( &ev, sizeof(ev), com_journalFile );
         if ( r != sizeof(ev) ) {
             Com_Error( ERR_FATAL, "Error reading from journal file" );
         }
         if ( ev.evPtrLength ) {
             ev.evPtr = Z_Malloc( ev.evPtrLength );
             r = FS_Read( ev.evPtr, ev.evPtrLength, com_journalFile );
             if ( r != ev.evPtrLength ) {
                 Com_Error( ERR_FATAL, "Error reading from journal file" );
             }
         }
     } else {
         ev = Com_GetSystemEvent();
         // write the journal value out if needed
         if ( com_journal->integer == 1 ) {
             r = FS_Write( &ev, sizeof(ev), com_journalFile );
             if ( r != sizeof(ev) ) {
                 Com_Error( ERR_FATAL, "Error writing to journal file" );
             }
             if ( ev.evPtrLength ) {
                 r = FS_Write( ev.evPtr, ev.evPtrLength, com_journalFile );
                 if ( r != ev.evPtrLength ) {
                     Com_Error( ERR_FATAL, "Error writing to journal file" );
                 }
             }
         }
     }
     return ev;
 }
References Com_Error(), Com_GetSystemEvent(), com_journal, com_journalFile, ERR_FATAL, sysEvent_t::evPtr, sysEvent_t::evPtrLength, FS_Read(), FS_Write(), and Z_Malloc.
Com_GetSystemEvent()
sysEvent_t Com_GetSystemEvent (void)
Definition at line 1978 of file common.c.
 {
     sysEvent_t  ev;
     char        *s;
     // return if we have data
     if ( eventHead > eventTail )
     {
         eventTail++;
         return eventQueue[ ( eventTail - 1 ) & MASK_QUEUED_EVENTS ];
     }
     // check for console commands
     s = Sys_ConsoleInput();
     if ( s )
     {
         char  *b;
         int   len;
         len = strlen( s ) + 1;
         b = Z_Malloc( len );
         strcpy( b, s );
         Com_QueueEvent( 0, SE_CONSOLE, 0, 0, len, b );
     }
     // return if we have data
     if ( eventHead > eventTail )
     {
         eventTail++;
         return eventQueue[ ( eventTail - 1 ) & MASK_QUEUED_EVENTS ];
     }
     // create an empty event to return
     memset( &ev, 0, sizeof( ev ) );
     ev.evTime = Sys_Milliseconds();
     return ev;
 }
References Com_QueueEvent(), eventHead, eventQueue, eventTail, sysEvent_t::evTime, MASK_QUEUED_EVENTS, SE_CONSOLE, Sys_ConsoleInput(), Sys_Milliseconds(), and Z_Malloc.
Com_HashKey()
int Com_HashKey (char * string, int maxlen)
Definition at line 692 of file common.c.
{
     int register hash, i;
     hash = 0;
     for ( i = 0; i < maxlen && string[i] != '\0'; i++ ) {
         hash += string[i] * ( 119 + i );
     }
     hash = ( hash ^ ( hash >> 10 ) ^ ( hash >> 20 ) );
     return hash;
 }
References hash().
Com_Init()
void Com_Init (char * commandLine)
Definition at line 2509 of file common.c.
{
     char    *s;
     int qport;
     Com_Printf( "%s %s %s\n", Q3_VERSION, PLATFORM_STRING, __DATE__ );
     if ( setjmp (abortframe) ) {
         Sys_Error ("Error during initialization");
     }
     // Clear queues
     Com_Memset( &eventQueue[ 0 ], 0, MAX_QUEUED_EVENTS * sizeof( sysEvent_t ) );
     // initialize the weak pseudo-random number generator for use later.
     Com_InitRand();
     // do this before anything else decides to push events
     Com_InitPushEvent();
     Com_InitSmallZoneMemory();
     Cvar_Init ();
     // prepare enough of the subsystems to handle
     // cvar and command buffer management
     Com_ParseCommandLine( commandLine );
 //  Swap_Init ();
     Cbuf_Init ();
     Com_DetectSSE();
     // override anything from the config files with command line args
     Com_StartupVariable( NULL );
     Com_InitZoneMemory();
     Cmd_Init ();
     // get the developer cvar set as early as possible
     com_developer = Cvar_Get("developer", "0", CVAR_TEMP);
     // done early so bind command exists
     CL_InitKeyCommands();
     com_basegame = Cvar_Get("com_basegame", BASEGAME, CVAR_INIT);
     com_homepath = Cvar_Get("com_homepath", "", CVAR_INIT);
     if(!com_basegame->string[0])
         Cvar_ForceReset("com_basegame");
     FS_InitFilesystem ();
     Com_InitJournaling();
     // Add some commands here already so users can use them from config files
     Cmd_AddCommand ("setenv", Com_Setenv_f);
     if (com_developer && com_developer->integer)
     {
         Cmd_AddCommand ("error", Com_Error_f);
         Cmd_AddCommand ("crash", Com_Crash_f);
         Cmd_AddCommand ("freeze", Com_Freeze_f);
     }
     Cmd_AddCommand ("quit", Com_Quit_f);
     Cmd_AddCommand ("changeVectors", MSG_ReportChangeVectors_f );
     Cmd_AddCommand ("writeconfig", Com_WriteConfig_f );
     Cmd_SetCommandCompletionFunc( "writeconfig", Cmd_CompleteCfgName );
     Cmd_AddCommand("game_restart", Com_GameRestart_f);
     Com_ExecuteCfg();
     // override anything from the config files with command line args
     Com_StartupVariable( NULL );
   // get dedicated here for proper hunk megs initialization
 #ifdef DEDICATED
     com_dedicated = Cvar_Get ("dedicated", "1", CVAR_INIT);
     Cvar_CheckRange( com_dedicated, 1, 2, qtrue );
 #else
     com_dedicated = Cvar_Get ("dedicated", "0", CVAR_LATCH);
     Cvar_CheckRange( com_dedicated, 0, 2, qtrue );
 #endif
     // allocate the stack based hunk allocator
     Com_InitHunkMemory();
     // if any archived cvars are modified after this, we will trigger a writing
     // of the config file
     cvar_modifiedFlags &= ~CVAR_ARCHIVE;
     //
     // init commands and vars
     //
     com_altivec = Cvar_Get ("com_altivec", "1", CVAR_ARCHIVE);
     com_maxfps = Cvar_Get ("com_maxfps", "85", CVAR_ARCHIVE);
     com_blood = Cvar_Get ("com_blood", "1", CVAR_ARCHIVE);
     com_logfile = Cvar_Get ("logfile", "0", CVAR_TEMP );
     com_timescale = Cvar_Get ("timescale", "1", CVAR_CHEAT | CVAR_SYSTEMINFO );
     com_fixedtime = Cvar_Get ("fixedtime", "0", CVAR_CHEAT);
     com_showtrace = Cvar_Get ("com_showtrace", "0", CVAR_CHEAT);
     com_speeds = Cvar_Get ("com_speeds", "0", 0);
     com_timedemo = Cvar_Get ("timedemo", "0", CVAR_CHEAT);
     com_cameraMode = Cvar_Get ("com_cameraMode", "0", CVAR_CHEAT);
     cl_paused = Cvar_Get ("cl_paused", "0", CVAR_ROM);
     sv_paused = Cvar_Get ("sv_paused", "0", CVAR_ROM);
     cl_packetdelay = Cvar_Get ("cl_packetdelay", "0", CVAR_CHEAT);
     sv_packetdelay = Cvar_Get ("sv_packetdelay", "0", CVAR_CHEAT);
     com_sv_running = Cvar_Get ("sv_running", "0", CVAR_ROM);
     com_cl_running = Cvar_Get ("cl_running", "0", CVAR_ROM);
     com_buildScript = Cvar_Get( "com_buildScript", "0", 0 );
     com_ansiColor = Cvar_Get( "com_ansiColor", "0", CVAR_ARCHIVE );
     com_unfocused = Cvar_Get( "com_unfocused", "0", CVAR_ROM );
     com_maxfpsUnfocused = Cvar_Get( "com_maxfpsUnfocused", "0", CVAR_ARCHIVE );
     com_minimized = Cvar_Get( "com_minimized", "0", CVAR_ROM );
     com_maxfpsMinimized = Cvar_Get( "com_maxfpsMinimized", "0", CVAR_ARCHIVE );
     com_abnormalExit = Cvar_Get( "com_abnormalExit", "0", CVAR_ROM );
     com_busyWait = Cvar_Get("com_busyWait", "0", CVAR_ARCHIVE);
     Cvar_Get("com_errorMessage", "", CVAR_ROM | CVAR_NORESTART);
     com_introPlayed = Cvar_Get( "com_introplayed", "0", CVAR_ARCHIVE);
     s = va("%s %s %s", Q3_VERSION, PLATFORM_STRING, __DATE__ );
     com_version = Cvar_Get ("version", s, CVAR_ROM | CVAR_SERVERINFO );
     com_gamename = Cvar_Get("com_gamename", GAMENAME_FOR_MASTER, CVAR_SERVERINFO | CVAR_INIT);
     com_protocol = Cvar_Get("com_protocol", va("%i", PROTOCOL_VERSION), CVAR_SERVERINFO | CVAR_INIT);
 #ifdef LEGACY_PROTOCOL
     com_legacyprotocol = Cvar_Get("com_legacyprotocol", va("%i", PROTOCOL_LEGACY_VERSION), CVAR_INIT);
     // Keep for compatibility with old mods / mods that haven't updated yet.
     if(com_legacyprotocol->integer > 0)
         Cvar_Get("protocol", com_legacyprotocol->string, CVAR_ROM);
     else
 #endif
         Cvar_Get("protocol", com_protocol->string, CVAR_ROM);
     Sys_Init();
     if( Sys_WritePIDFile( ) ) {
 #ifndef DEDICATED
         const char *message = "The last time " CLIENT_WINDOW_TITLE " ran, "
             "it didn't exit properly. This may be due to inappropriate video "
             "settings. Would you like to start with \"safe\" video settings?";
         if( Sys_Dialog( DT_YES_NO, message, "Abnormal Exit" ) == DR_YES ) {
             Cvar_Set( "com_abnormalExit", "1" );
         }
 #endif
     }
     // Pick a random port value
     Com_RandomBytes( (byte*)&qport, sizeof(int) );
     Netchan_Init( qport & 0xffff );
     VM_Init();
     SV_Init();
     com_dedicated->modified = qfalse;
 #ifndef DEDICATED
     CL_Init();
 #endif
     // set com_frameTime so that if a map is started on the
     // command line it will still be able to count on com_frameTime
     // being random enough for a serverid
     com_frameTime = Com_Milliseconds();
     // add + commands from command line
     if ( !Com_AddStartupCommands() ) {
         // if the user didn't give any commands, run default action
         if ( !com_dedicated->integer ) {
             Cbuf_AddText("cinematic zeq2logo.roq\n");
             if( !com_introPlayed->integer ) {
                 Cvar_Set(com_introPlayed->name,"1");
                 Cvar_Set("nextmap","cinematic zeq2intro.roq" );
             }
         }
     }
     // start in full screen ui mode
     Cvar_Set("r_uiFullScreen", "1");
     CL_StartHunkUsers( qfalse );
     // make sure single player is off by default
     Cvar_Set("ui_singlePlayerActive", "0");
     com_fullyInitialized = qtrue;
     // always set the cvar, but only print the info if it makes sense.
     Com_DetectAltivec();
 #if idppc
     Com_Printf ("Altivec support is %s\n", com_altivec->integer ? "enabled" : "disabled");
 #endif
     com_pipefile = Cvar_Get( "com_pipefile", "", CVAR_ARCHIVE|CVAR_LATCH );
     if( com_pipefile->string[0] )
     {
         pipefile = FS_FCreateOpenPipeFile( com_pipefile->string );
     }
     Com_Printf ("--- Common Initialization Complete ---\n");
 }
References abortframe, BASEGAME, Cbuf_AddText(), Cbuf_Init(), CL_Init(), CL_InitKeyCommands(), cl_packetdelay, cl_paused, CL_StartHunkUsers(), CLIENT_WINDOW_TITLE, Cmd_AddCommand(), Cmd_CompleteCfgName(), Cmd_Init(), Cmd_SetCommandCompletionFunc(), com_abnormalExit, Com_AddStartupCommands(), com_altivec, com_ansiColor, com_basegame, com_blood, com_buildScript, com_busyWait, com_cameraMode, com_cl_running, Com_Crash_f(), com_dedicated, Com_DetectAltivec(), Com_DetectSSE, com_developer, Com_Error_f(), Com_ExecuteCfg(), com_fixedtime, com_frameTime, Com_Freeze_f(), com_fullyInitialized, com_gamename, Com_GameRestart_f(), com_homepath, Com_InitHunkMemory(), Com_InitJournaling(), Com_InitPushEvent(), Com_InitRand(), Com_InitSmallZoneMemory(), Com_InitZoneMemory(), com_introPlayed, com_logfile, com_maxfps, com_maxfpsMinimized, com_maxfpsUnfocused, Com_Memset, Com_Milliseconds(), com_minimized, Com_ParseCommandLine(), com_pipefile, Com_Printf(), com_protocol, Com_Quit_f(), Com_RandomBytes(), Com_Setenv_f(), com_showtrace, com_speeds, Com_StartupVariable(), com_sv_running, com_timedemo, com_timescale, com_unfocused, com_version, Com_WriteConfig_f(), CVAR_ARCHIVE, CVAR_CHEAT, Cvar_CheckRange(), Cvar_ForceReset(), Cvar_Get(), CVAR_INIT, Cvar_Init(), CVAR_LATCH, cvar_modifiedFlags, CVAR_NORESTART, CVAR_ROM, CVAR_SERVERINFO, Cvar_Set(), CVAR_SYSTEMINFO, CVAR_TEMP, DR_YES, DT_YES_NO, eventQueue, FS_FCreateOpenPipeFile(), FS_InitFilesystem(), GAMENAME_FOR_MASTER, MAX_QUEUED_EVENTS, MSG_ReportChangeVectors_f(), Netchan_Init(), NULL, pipefile, PLATFORM_STRING, PROTOCOL_LEGACY_VERSION, PROTOCOL_VERSION, Q3_VERSION, qfalse, qport, qtrue, SV_Init(), sv_packetdelay, sv_paused, Sys_Dialog(), Sys_Error(), Sys_Init(), Sys_WritePIDFile(), va(), and VM_Init().
Com_InitHunkMemory()
void Com_InitHunkMemory (void)
Definition at line 1522 of file common.c.
{
     cvar_t  *cv;
     int nMinAlloc;
     char *pMsg = NULL;
     // make sure the file system has allocated and "not" freed any temp blocks
     // this allows the config and product id files ( journal files too ) to be loaded
     // by the file system without redunant routines in the file system utilizing different
     // memory systems
     if (FS_LoadStack() != 0) {
         Com_Error( ERR_FATAL, "Hunk initialization failed. File system load stack not zero");
     }
     // allocate the stack based hunk allocator
     cv = Cvar_Get( "com_hunkMegs", DEF_COMHUNKMEGS_S, CVAR_LATCH | CVAR_ARCHIVE );
     // if we are not dedicated min allocation is 56, otherwise min is 1
     if (com_dedicated && com_dedicated->integer) {
         nMinAlloc = MIN_DEDICATED_COMHUNKMEGS;
         pMsg = "Minimum com_hunkMegs for a dedicated server is %i, allocating %i megs.\n";
     }
     else {
         nMinAlloc = MIN_COMHUNKMEGS;
         pMsg = "Minimum com_hunkMegs is %i, allocating %i megs.\n";
     }
     if ( cv->integer < nMinAlloc ) {
         s_hunkTotal = 1024 * 1024 * nMinAlloc;
         Com_Printf(pMsg, nMinAlloc, s_hunkTotal / (1024 * 1024));
     } else {
         s_hunkTotal = cv->integer * 1024 * 1024;
     }
     s_hunkData = calloc( s_hunkTotal + 31, 1 );
     if ( !s_hunkData ) {
         Com_Error( ERR_FATAL, "Hunk data failed to allocate %i megs", s_hunkTotal / (1024*1024) );
     }
     // cacheline align
     s_hunkData = (byte *) ( ( (intptr_t)s_hunkData + 31 ) & ~31 );
     Hunk_Clear();
     Cmd_AddCommand( "meminfo", Com_Meminfo_f );
 #ifdef ZONE_DEBUG
     Cmd_AddCommand( "zonelog", Z_LogHeap );
 #endif
 #ifdef HUNK_DEBUG
     Cmd_AddCommand( "hunklog", Hunk_Log );
     Cmd_AddCommand( "hunksmalllog", Hunk_SmallLog );
 #endif
 }
References Cmd_AddCommand(), com_dedicated, Com_Error(), Com_Meminfo_f(), Com_Printf(), CVAR_ARCHIVE, Cvar_Get(), CVAR_LATCH, DEF_COMHUNKMEGS_S, ERR_FATAL, FS_LoadStack(), Hunk_Clear(), Hunk_Log(), Hunk_SmallLog(), intptr_t(), MIN_COMHUNKMEGS, MIN_DEDICATED_COMHUNKMEGS, NULL, s_hunkData, s_hunkTotal, and Z_LogHeap().
Com_InitJournaling()
void Com_InitJournaling (void)
Definition at line 1891 of file common.c.
{
     Com_StartupVariable( "journal" );
     com_journal = Cvar_Get ("journal", "0", CVAR_INIT);
     if ( !com_journal->integer ) {
         return;
     }
     if ( com_journal->integer == 1 ) {
         Com_Printf( "Journaling events\n");
         com_journalFile = FS_FOpenFileWrite( "journal.dat" );
         com_journalDataFile = FS_FOpenFileWrite( "journaldata.dat" );
     } else if ( com_journal->integer == 2 ) {
         Com_Printf( "Replaying journaled events\n");
         FS_FOpenFileRead( "journal.dat", &com_journalFile, qtrue );
         FS_FOpenFileRead( "journaldata.dat", &com_journalDataFile, qtrue );
     }
     if ( !com_journalFile || !com_journalDataFile ) {
         Cvar_Set( "com_journal", "0" );
         com_journalFile = 0;
         com_journalDataFile = 0;
         Com_Printf( "Couldn't open journal files\n" );
     }
 }
References com_journal, com_journalDataFile, com_journalFile, Com_Printf(), Com_StartupVariable(), Cvar_Get(), CVAR_INIT, Cvar_Set(), FS_FOpenFileRead(), FS_FOpenFileWrite(), and qtrue.
Com_InitPushEvent()
void Com_InitPushEvent (void)
Definition at line 2066 of file common.c.
{
   // clear the static buffer array
   // this requires SE_NONE to be accepted as a valid but NOP event
   memset( com_pushedEvents, 0, sizeof(com_pushedEvents) );
   // reset counters while we are at it
   // beware: GetEvent might still return an SE_NONE from the buffer
   com_pushedEventsHead = 0;
   com_pushedEventsTail = 0;
 }
References com_pushedEvents, com_pushedEventsHead, and com_pushedEventsTail.
Com_InitRand()
static void Com_InitRand (void) static
Definition at line 2494 of file common.c.
 {
     unsigned int seed;
     if(Sys_RandomBytes((byte *) &seed, sizeof(seed)))
         srand(seed);
     else
         srand(time(NULL));
 }
References NULL, and Sys_RandomBytes().
Referenced by Com_Init().
Com_InitSmallZoneMemory()
void Com_InitSmallZoneMemory (void)
Definition at line 1402 of file common.c.
{
     s_smallZoneTotal = 512 * 1024;
     smallzone = calloc( s_smallZoneTotal, 1 );
     if ( !smallzone ) {
         Com_Error( ERR_FATAL, "Small zone data failed to allocate %1.1f megs", (float)s_smallZoneTotal / (1024*1024) );
     }
     Z_ClearZone( smallzone, s_smallZoneTotal );
     return;
 }
References Com_Error(), ERR_FATAL, s_smallZoneTotal, smallzone, and Z_ClearZone().
Com_InitZoneMemory()
void Com_InitZoneMemory (void)
Definition at line 1413 of file common.c.
{
     cvar_t  *cv;
     // Please note: com_zoneMegs can only be set on the command line, and
     // not in q3config.cfg or Com_StartupVariable, as they haven't been
     // executed by this point. It's a chicken and egg problem. We need the
     // memory manager configured to handle those places where you would
     // configure the memory manager.
     // allocate the random block zone
     cv = Cvar_Get( "com_zoneMegs", DEF_COMZONEMEGS_S, CVAR_LATCH | CVAR_ARCHIVE );
     if ( cv->integer < DEF_COMZONEMEGS ) {
         s_zoneTotal = 1024 * 1024 * DEF_COMZONEMEGS;
     } else {
         s_zoneTotal = cv->integer * 1024 * 1024;
     }
     mainzone = calloc( s_zoneTotal, 1 );
     if ( !mainzone ) {
         Com_Error( ERR_FATAL, "Zone data failed to allocate %i megs", s_zoneTotal / (1024*1024) );
     }
     Z_ClearZone( mainzone, s_zoneTotal );
 }
References Com_Error(), CVAR_ARCHIVE, Cvar_Get(), CVAR_LATCH, DEF_COMZONEMEGS, DEF_COMZONEMEGS_S, ERR_FATAL, mainzone, s_zoneTotal, and Z_ClearZone().
Com_IsVoipTarget()
qboolean Com_IsVoipTarget (uint8_t * voipTargets, int voipTargetsSize, int clientNum)
Definition at line 3421 of file common.c.
 {
     int index;
     if(clientNum < 0)
     {
         for(index = 0; index < voipTargetsSize; index++)
         {
             if(voipTargets[index])
                 return qtrue;
         }
         return qfalse;
     }
     index = clientNum >> 3;
     if(index < voipTargetsSize)
         return (voipTargets[index] & (1 << (clientNum & 0x07)));
     return qfalse;
 }
References qfalse, and qtrue.
Com_Meminfo_f()
void Com_Meminfo_f (void)
Definition at line 1267 of file common.c.
{
     memblock_t  *block;
     int         zoneBytes, zoneBlocks;
     int         smallZoneBytes, smallZoneBlocks;
     int         rendererBytes;
     int         unused;
     zoneBytes = 0;
     rendererBytes = 0;
     zoneBlocks = 0;
     for (block = mainzone->blocklist.next ; ; block = block->next) {
         if ( Cmd_Argc() != 1 ) {
             Com_Printf ("block:%p    size:%7i    tag:%3i\n",
                 (void *)block, block->size, block->tag);
         }
         if ( block->tag ) {
             zoneBytes += block->size;
             zoneBlocks++;
             rendererBytes += block->size;
         }
         if (block->next == &mainzone->blocklist) {
             break;          // all blocks have been hit
         }
         if ( (byte *)block + block->size != (byte *)block->next) {
             Com_Printf ("ERROR: block size does not touch the next block\n");
         }
         if ( block->next->prev != block) {
             Com_Printf ("ERROR: next block doesn't have proper back link\n");
         }
         if ( !block->tag && !block->next->tag ) {
             Com_Printf ("ERROR: two consecutive free blocks\n");
         }
     }
     smallZoneBytes = 0;
     smallZoneBlocks = 0;
     for (block = smallzone->blocklist.next ; ; block = block->next) {
         if ( block->tag ) {
             smallZoneBytes += block->size;
             smallZoneBlocks++;
         }
         if (block->next == &smallzone->blocklist) {
             break;          // all blocks have been hit
         }
     }
     Com_Printf( "%8i bytes total hunk\n", s_hunkTotal );
     Com_Printf( "%8i bytes total zone\n", s_zoneTotal );
     Com_Printf( "\n" );
     Com_Printf( "%8i low mark\n", hunk_low.mark );
     Com_Printf( "%8i low permanent\n", hunk_low.permanent );
     if ( hunk_low.temp != hunk_low.permanent ) {
         Com_Printf( "%8i low temp\n", hunk_low.temp );
     }
     Com_Printf( "%8i low tempHighwater\n", hunk_low.tempHighwater );
     Com_Printf( "\n" );
     Com_Printf( "%8i high mark\n", hunk_high.mark );
     Com_Printf( "%8i high permanent\n", hunk_high.permanent );
     if ( hunk_high.temp != hunk_high.permanent ) {
         Com_Printf( "%8i high temp\n", hunk_high.temp );
     }
     Com_Printf( "%8i high tempHighwater\n", hunk_high.tempHighwater );
     Com_Printf( "\n" );
     Com_Printf( "%8i total hunk in use\n", hunk_low.permanent + hunk_high.permanent );
     unused = 0;
     if ( hunk_low.tempHighwater > hunk_low.permanent ) {
         unused += hunk_low.tempHighwater - hunk_low.permanent;
     }
     if ( hunk_high.tempHighwater > hunk_high.permanent ) {
         unused += hunk_high.tempHighwater - hunk_high.permanent;
     }
     Com_Printf( "%8i unused highwater\n", unused );
     Com_Printf( "\n" );
     Com_Printf( "%8i bytes in %i zone blocks\n", zoneBytes, zoneBlocks  );
     Com_Printf( "        %8i bytes in dynamic renderer\n", rendererBytes );
     Com_Printf( "        %8i bytes in dynamic other\n", zoneBytes - rendererBytes );
     Com_Printf( "        %8i bytes in small Zone memory\n", smallZoneBytes );
 }
References memzone_t::blocklist, Cmd_Argc(), Com_Printf(), hunk_high, hunk_low, mainzone, hunkUsed_t::mark, block::next, hunkUsed_t::permanent, s_hunkTotal, s_zoneTotal, smallzone, hunkUsed_t::temp, and hunkUsed_t::tempHighwater.
Com_Milliseconds()
int Com_Milliseconds (void)
Definition at line 2221 of file common.c.
{
     sysEvent_t  ev;
     // get events and push them until we get a null event with the current time
     do {
         ev = Com_GetRealEvent();
         if ( ev.evType != SE_NONE ) {
             Com_PushEvent( &ev );
         }
     } while ( ev.evType != SE_NONE );
     return ev.evTime;
 }
References Com_GetRealEvent(), Com_PushEvent(), sysEvent_t::evTime, sysEvent_t::evType, and SE_NONE.
Com_ModifyMsec()
int Com_ModifyMsec (int msec)
Definition at line 2830 of file common.c.
{
     int     clampTime;
     //
     // modify time for debugging values
     //
     if ( com_fixedtime->integer ) {
         msec = com_fixedtime->integer;
     } else if ( com_timescale->value ) {
         msec *= com_timescale->value;
     } else if (com_cameraMode->integer) {
         msec *= com_timescale->value;
     }
     // don't let it scale below 1 msec
     if ( msec < 1 && com_timescale->value) {
         msec = 1;
     }
     if ( com_dedicated->integer ) {
         // dedicated servers don't want to clamp for a much longer
         // period, because it would mess up all the client's views
         // of time.
         if (com_sv_running->integer && msec > 500)
             Com_Printf( "Hitch warning: %i msec frame time\n", msec );
         clampTime = 5000;
     } else
     if ( !com_sv_running->integer ) {
         // clients of remote servers do not want to clamp time, because
         // it would skew their view of the server's time temporarily
         clampTime = 5000;
     } else {
         // for local single player gaming
         // we may want to clamp the time to prevent players from
         // flying off edges when something hitches.
         clampTime = 200;
     }
     if ( msec > clampTime ) {
         msec = clampTime;
     }
     return msec;
 }
References com_cameraMode, com_dedicated, com_fixedtime, Com_Printf(), com_sv_running, and com_timescale.
Com_ParseCommandLine()
void Com_ParseCommandLine (char * commandLine)
Definition at line 385 of file common.c.
{
     int inq = 0;
     com_consoleLines[0] = commandLine;
     com_numConsoleLines = 1;
     while ( *commandLine ) {
         if (*commandLine == '"') {
             inq = !inq;
         }
         // look for a + seperating character
         // if commandLine came from a file, we might have real line seperators
         if ( (*commandLine == '+' && !inq) || *commandLine == '\n'  || *commandLine == '\r' ) {
             if ( com_numConsoleLines == MAX_CONSOLE_LINES ) {
                 return;
             }
             com_consoleLines[com_numConsoleLines] = commandLine + 1;
             com_numConsoleLines++;
             *commandLine = 0;
         }
         commandLine++;
     }
 }
References com_consoleLines, com_numConsoleLines, and MAX_CONSOLE_LINES.
Com_Printf()
void QDECL Com_Printf (const char * fmt, ...)
Definition at line 159 of file common.c.
{
     va_list     argptr;
     char        msg[MAXPRINTMSG];
   static qboolean opening_qconsole = qfalse;
     va_start (argptr,fmt);
     Q_vsnprintf (msg, sizeof(msg), fmt, argptr);
     va_end (argptr);
     if ( rd_buffer ) {
         if ((strlen (msg) + strlen(rd_buffer)) > (rd_buffersize - 1)) {
             rd_flush(rd_buffer);
             *rd_buffer = 0;
         }
         Q_strcat(rd_buffer, rd_buffersize, msg);
     // TTimo nooo .. that would defeat the purpose
         //rd_flush(rd_buffer);
         //*rd_buffer = 0;
         return;
     }
 #ifndef DEDICATED
     CL_ConsolePrint( msg );
 #endif
     // echo to dedicated console and early console
     Sys_Print( msg );
     // logfile
     if ( com_logfile && com_logfile->integer ) {
     // TTimo: only open the qconsole.log if the filesystem is in an initialized state
     //   also, avoid recursing in the qconsole.log opening (i.e. if fs_debug is on)
         if ( !logfile && FS_Initialized() && !opening_qconsole) {
             struct tm *newtime;
             time_t aclock;
       opening_qconsole = qtrue;
             time( &aclock );
             newtime = localtime( &aclock );
             logfile = FS_FOpenFileWrite( "console.log" );
             if(logfile)
             {
                 Com_Printf( "logfile opened on %s\n", asctime( newtime ) );
                 if ( com_logfile->integer > 1 )
                 {
                     // force it to not buffer so we get valid
                     // data even if we are crashing
                     FS_ForceFlush(logfile);
                 }
             }
             else
             {
                 Com_Printf("Opening console.log failed!\n");
                 Cvar_SetValue("logfile", 0);
             }
       opening_qconsole = qfalse;
         }
         if ( logfile && FS_Initialized()) {
             FS_Write(msg, strlen(msg), logfile);
         }
     }
 }
References CL_ConsolePrint(), com_logfile, Com_Printf(), Cvar_SetValue(), fmt, FS_FOpenFileWrite(), FS_ForceFlush(), FS_Initialized(), FS_Write(), logfile, MAXPRINTMSG, Q_strcat(), Q_vsnprintf, qfalse, qtrue, rd_buffer, rd_buffersize, rd_flush, and Sys_Print().
Com_PushEvent()
void Com_PushEvent (sysEvent_t * event)
Definition at line 2082 of file common.c.
{
     sysEvent_t      *ev;
     static int printedWarning = 0;
     ev = &com_pushedEvents[ com_pushedEventsHead & (MAX_PUSHED_EVENTS-1) ];
     if ( com_pushedEventsHead - com_pushedEventsTail >= MAX_PUSHED_EVENTS ) {
         // don't print the warning constantly, or it can give time for more...
         if ( !printedWarning ) {
             printedWarning = qtrue;
             Com_Printf( "WARNING: Com_PushEvent overflow\n" );
         }
         if ( ev->evPtr ) {
             Z_Free( ev->evPtr );
         }
         com_pushedEventsTail++;
     } else {
         printedWarning = qfalse;
     }
     *ev = *event;
     com_pushedEventsHead++;
 }
References Com_Printf(), com_pushedEvents, com_pushedEventsHead, com_pushedEventsTail, sysEvent_t::evPtr, MAX_PUSHED_EVENTS, qfalse, qtrue, and Z_Free().
Com_QueueEvent()
void Com_QueueEvent (int time, sysEventType_t type, int value, int value2, int ptrLength, void * ptr)
Definition at line 1940 of file common.c.
 {
     sysEvent_t  *ev;
     ev = &eventQueue[ eventHead & MASK_QUEUED_EVENTS ];
     if ( eventHead - eventTail >= MAX_QUEUED_EVENTS )
     {
         Com_Printf("Com_QueueEvent: overflow\n");
         // we are discarding an event, but don't leak memory
         if ( ev->evPtr )
         {
             Z_Free( ev->evPtr );
         }
         eventTail++;
     }
     eventHead++;
     if ( time == 0 )
     {
         time = Sys_Milliseconds();
     }
     ev->evTime = time;
     ev->evType = type;
     ev->evValue = value;
     ev->evValue2 = value2;
     ev->evPtrLength = ptrLength;
     ev->evPtr = ptr;
 }
References Com_Printf(), eventHead, eventQueue, eventTail, sysEvent_t::evPtr, sysEvent_t::evPtrLength, sysEvent_t::evTime, sysEvent_t::evType, sysEvent_t::evValue, sysEvent_t::evValue2, MASK_QUEUED_EVENTS, MAX_QUEUED_EVENTS, ptr(), Sys_Milliseconds(), and Z_Free().
Com_Quit_f()
void Com_Quit_f (void)
Definition at line 337 of file common.c.
{
     // don't try to shutdown if we are in a recursive error
     char *p = Cmd_Args( );
     if ( !com_errorEntered ) {
         // Some VMs might execute "quit" command directly,
         // which would trigger an unload of active VM error.
         // Sys_Quit will kill this process anyways, so
         // a corrupt call stack makes no difference
         VM_Forced_Unload_Start();
         SV_Shutdown(p[0] ? p : "Server quit");
         CL_Shutdown(p[0] ? p : "Client quit", qtrue, qtrue);
         VM_Forced_Unload_Done();
         Com_Shutdown ();
         FS_Shutdown(qtrue);
     }
     Sys_Quit ();
 }
References CL_Shutdown(), Cmd_Args(), com_errorEntered, Com_Shutdown(), FS_Shutdown(), qtrue, SV_Shutdown(), Sys_Quit(), VM_Forced_Unload_Done(), and VM_Forced_Unload_Start().
Com_RandomBytes()
void Com_RandomBytes (byte * string, int len)
Definition at line 3400 of file common.c.
 {
     int i;
     if( Sys_RandomBytes( string, len ) )
         return;
     Com_Printf( "Com_RandomBytes: using weak randomization\n" );
     for( i = 0; i < len; i++ )
         string[i] = (unsigned char)( rand() % 255 );
 }
References Com_Printf(), and Sys_RandomBytes().
Com_ReadFromPipe()
void Com_ReadFromPipe (void)
Definition at line 2720 of file common.c.
 {
     static char buf[MAX_STRING_CHARS];
     static int accu = 0;
     int read;
     if( !pipefile )
         return;
     while( ( read = FS_Read( buf + accu, sizeof( buf ) - accu - 1, pipefile ) ) > 0 )
     {
         char *brk = NULL;
         int i;
         for( i = accu; i < accu + read; ++i )
         {
             if( buf[ i ] == '\0' )
                 buf[ i ] = '\n';
             if( buf[ i ] == '\n' || buf[ i ] == '\r' )
                 brk = &buf[ i + 1 ];
         }
         buf[ accu + read ] = '\0';
         accu += read;
         if( brk )
         {
             char tmp = *brk;
             *brk = '\0';
             Cbuf_ExecuteText( EXEC_APPEND, buf );
             *brk = tmp;
             accu -= brk - buf;
             memmove( buf, brk, accu + 1 );
         }
         else if( accu >= sizeof( buf ) - 1 ) // full
         {
             Cbuf_ExecuteText( EXEC_APPEND, buf );
             accu = 0;
         }
     }
 }
References Cbuf_ExecuteText(), EXEC_APPEND, FS_Read(), MAX_STRING_CHARS, memmove(), NULL, and pipefile.
Com_RealTime()
int Com_RealTime (qtime_t * qtime)
Definition at line 708 of file common.c.
{
     time_t t;
     struct tm *tms;
     t = time(NULL);
     if (!qtime)
         return t;
     tms = localtime(&t);
     if (tms) {
         qtime->tm_sec = tms->tm_sec;
         qtime->tm_min = tms->tm_min;
         qtime->tm_hour = tms->tm_hour;
         qtime->tm_mday = tms->tm_mday;
         qtime->tm_mon = tms->tm_mon;
         qtime->tm_year = tms->tm_year;
         qtime->tm_wday = tms->tm_wday;
         qtime->tm_yday = tms->tm_yday;
         qtime->tm_isdst = tms->tm_isdst;
     }
     return t;
 }
References NULL.
Com_RunAndTimeServerPacket()
void Com_RunAndTimeServerPacket (netadr_t * evFrom, msg_t * buf)
Definition at line 2126 of file common.c.
{
     int     t1, t2, msec;
     t1 = 0;
     if ( com_speeds->integer ) {
         t1 = Sys_Milliseconds ();
     }
     SV_PacketEvent( *evFrom, buf );
     if ( com_speeds->integer ) {
         t2 = Sys_Milliseconds ();
         msec = t2 - t1;
         if ( com_speeds->integer == 3 ) {
             Com_Printf( "SV_PacketEvent time: %i\n", msec );
         }
     }
 }
References Com_Printf(), com_speeds, SV_PacketEvent(), and Sys_Milliseconds().
Com_SafeMode()
qboolean Com_SafeMode (void)
Definition at line 417 of file common.c.
{
     int     i;
     for ( i = 0 ; i < com_numConsoleLines ; i++ ) {
         Cmd_TokenizeString( com_consoleLines[i] );
         if ( !Q_stricmp( Cmd_Argv(0), "safe" )
             || !Q_stricmp( Cmd_Argv(0), "cvar_restart" ) ) {
             com_consoleLines[i][0] = 0;
             return qtrue;
         }
     }
     return qfalse;
 }
References Cmd_Argv(), Cmd_TokenizeString(), com_consoleLines, com_numConsoleLines, Q_stricmp(), qfalse, and qtrue.
Com_Setenv_f()
void Com_Setenv_f (void)
Definition at line 2301 of file common.c.
 {
     int argc = Cmd_Argc();
     char *arg1 = Cmd_Argv(1);
     if(argc > 2)
     {
         char *arg2 = Cmd_ArgsFrom(2);
         Sys_SetEnv(arg1, arg2);
     }
     else if(argc == 2)
     {
         char *env = getenv(arg1);
         if(env)
             Com_Printf("%s=%s\n", arg1, env);
         else
             Com_Printf("%s undefined\n", arg1);
         }
 }
References Cmd_Argc(), Cmd_ArgsFrom(), Cmd_Argv(), Com_Printf(), and Sys_SetEnv().
Com_Shutdown()
void Com_Shutdown (void)
Definition at line 3104 of file common.c.
{
     if (logfile) {
         FS_FCloseFile (logfile);
         logfile = 0;
     }
     if ( com_journalFile ) {
         FS_FCloseFile( com_journalFile );
         com_journalFile = 0;
     }
     if( pipefile ) {
         FS_FCloseFile( pipefile );
         FS_HomeRemove( com_pipefile->string );
     }
 }
References com_journalFile, com_pipefile, FS_FCloseFile(), FS_HomeRemove(), logfile, and pipefile.
Com_StartupVariable()
void Com_StartupVariable (const char * match)
Definition at line 443 of file common.c.
{
     int     i;
     char    *s;
     for (i=0 ; i < com_numConsoleLines ; i++) {
         Cmd_TokenizeString( com_consoleLines[i] );
         if ( strcmp( Cmd_Argv(0), "set" ) ) {
             continue;
         }
         s = Cmd_Argv(1);
         if(!match || !strcmp(s, match))
         {
             if(Cvar_Flags(s) == CVAR_NONEXISTENT)
                 Cvar_Get(s, Cmd_Argv(2), CVAR_USER_CREATED);
             else
                 Cvar_Set2(s, Cmd_Argv(2), qfalse);
         }
     }
 }
References Cmd_Argv(), Cmd_TokenizeString(), com_consoleLines, com_numConsoleLines, Cvar_Flags(), Cvar_Get(), CVAR_NONEXISTENT, Cvar_Set2(), CVAR_USER_CREATED, and qfalse.
Com_StringContains()
char* Com_StringContains (char * str1, char * str2, int casesensitive)
Definition at line 551 of file common.c.
{
     int len, i, j;
     len = strlen(str1) - strlen(str2);
     for (i = 0; i <= len; i++, str1++) {
         for (j = 0; str2[j]; j++) {
             if (casesensitive) {
                 if (str1[j] != str2[j]) {
                     break;
                 }
             }
             else {
                 if (toupper(str1[j]) != toupper(str2[j])) {
                     break;
                 }
             }
         }
         if (!str2[j]) {
             return str1;
         }
     }
     return NULL;
 }
References NULL.
Com_TimeVal()
int Com_TimeVal (int minMsec)
Definition at line 2882 of file common.c.
 {
     int timeVal;
     timeVal = Sys_Milliseconds() - com_frameTime;
     if(timeVal >= minMsec)
         timeVal = 0;
     else
         timeVal = minMsec - timeVal;
     return timeVal;
 }
References com_frameTime, and Sys_Milliseconds().
Com_TouchMemory()
void Com_TouchMemory (void)
Definition at line 1355 of file common.c.
{
     int     start, end;
     int     i, j;
     int     sum;
     memblock_t  *block;
     Z_CheckHeap();
     start = Sys_Milliseconds();
     sum = 0;
     j = hunk_low.permanent >> 2;
     for ( i = 0 ; i < j ; i+=64 ) {         // only need to touch each page
         sum += ((int *)s_hunkData)[i];
     }
     i = ( s_hunkTotal - hunk_high.permanent ) >> 2;
     j = hunk_high.permanent >> 2;
     for (  ; i < j ; i+=64 ) {          // only need to touch each page
         sum += ((int *)s_hunkData)[i];
     }
     for (block = mainzone->blocklist.next ; ; block = block->next) {
         if ( block->tag ) {
             j = block->size >> 2;
             for ( i = 0 ; i < j ; i+=64 ) {             // only need to touch each page
                 sum += ((int *)block)[i];
             }
         }
         if ( block->next == &mainzone->blocklist ) {
             break;          // all blocks have been hit
         }
     }
     end = Sys_Milliseconds();
     Com_Printf( "Com_TouchMemory: %i msec\n", end - start );
 }
References memzone_t::blocklist, Com_Printf(), hunk_high, hunk_low, mainzone, block::next, hunkUsed_t::permanent, s_hunkData, s_hunkTotal, Sys_Milliseconds(), and Z_CheckHeap().
Com_WriteConfig_f()
void Com_WriteConfig_f (void)
Definition at line 2811 of file common.c.
{
     char    filename[MAX_QPATH];
     if ( Cmd_Argc() != 2 ) {
         Com_Printf( "Usage: writeconfig <filename>\n" );
         return;
     }
     Q_strncpyz( filename, Cmd_Argv(1), sizeof( filename ) );
     COM_DefaultExtension( filename, sizeof( filename ), ".cfg" );
     Com_Printf( "Writing %s.\n", filename );
     Com_WriteConfigToFile( filename );
 }
References Cmd_Argc(), Cmd_Argv(), COM_DefaultExtension(), Com_Printf(), Com_WriteConfigToFile(), MAX_QPATH, and Q_strncpyz().
Com_WriteConfigToFile()
void Com_WriteConfigToFile (const char * filename)
Definition at line 2766 of file common.c.
{
     fileHandle_t    f;
     f = FS_FOpenFileWrite( filename );
     if ( !f ) {
         Com_Printf ("Couldn't write %s.\n", filename );
         return;
     }
     Key_WriteBindings (f);
     Cvar_WriteVariables (f);
     FS_FCloseFile( f );
 }
References Com_Printf(), Cvar_WriteVariables(), FS_FCloseFile(), FS_FOpenFileWrite(), and Key_WriteBindings().
Com_WriteConfiguration()
void Com_WriteConfiguration (void)
Definition at line 2788 of file common.c.
{
     // if we are quiting without fully initializing, make sure
     // we don't write out anything
     if ( !com_fullyInitialized ) {
         return;
     }
     if ( !(cvar_modifiedFlags & CVAR_ARCHIVE ) ) {
         return;
     }
     cvar_modifiedFlags &= ~CVAR_ARCHIVE;
     Com_WriteConfigToFile( Q3CONFIG_CFG );
 }
References com_fullyInitialized, Com_WriteConfigToFile(), CVAR_ARCHIVE, cvar_modifiedFlags, and Q3CONFIG_CFG.
CopyString()
char* CopyString (const char * in)
Definition at line 1175 of file common.c.
{
     char    *out;
     if (!in[0]) {
         return ((char *)&emptystring) + sizeof(memblock_t);
     }
     else if (!in[1]) {
         if (in[0] >= '0' && in[0] <= '9') {
             return ((char *)&numberstring[in[0]-'0']) + sizeof(memblock_t);
         }
     }
     out = S_Malloc (strlen(in)+1);
     strcpy (out, in);
     return out;
 }
References emptystring, numberstring, out, and S_Malloc.
Field_AutoComplete()
void Field_AutoComplete (field_t * field)
Definition at line 3386 of file common.c.
 {
     completionField = field;
     Field_CompleteCommand( completionField->buffer, qtrue, qtrue );
 }
References field_t::buffer, completionField, field(), Field_CompleteCommand(), and qtrue.
Field_Clear()
void Field_Clear (field_t * edit)
Definition at line 3133 of file common.c.
{
   memset(edit->buffer, 0, MAX_EDIT_LINE);
     edit->cursor = 0;
     edit->scroll = 0;
 }
References field_t::buffer, field_t::cursor, MAX_EDIT_LINE, and field_t::scroll.
Field_Complete()
static qboolean Field_Complete (void) static
Definition at line 3226 of file common.c.
 {
     int completionOffset;
     if( matchCount == 0 )
         return qtrue;
     completionOffset = strlen( completionField->buffer ) - strlen( completionString );
     Q_strncpyz( &completionField->buffer[ completionOffset ], shortestMatch,
         sizeof( completionField->buffer ) - completionOffset );
     completionField->cursor = strlen( completionField->buffer );
     if( matchCount == 1 )
     {
         Q_strcat( completionField->buffer, sizeof( completionField->buffer ), " " );
         completionField->cursor++;
         return qtrue;
     }
     Com_Printf( "]%s\n", completionField->buffer );
     return qfalse;
 }
References field_t::buffer, Com_Printf(), completionField, completionString, field_t::cursor, matchCount, Q_strcat(), Q_strncpyz(), qfalse, qtrue, and shortestMatch.
Referenced by Field_CompleteCommand(), Field_CompleteFilename(), and Field_CompleteKeyname().
Field_CompleteCommand()
void Field_CompleteCommand (char * cmd, qboolean doCommands, qboolean doCvars)
Definition at line 3292 of file common.c.
 {
     int     completionArgument = 0;
     // Skip leading whitespace and quotes
     cmd = Com_SkipCharset( cmd, " \"" );
     Cmd_TokenizeStringIgnoreQuotes( cmd );
     completionArgument = Cmd_Argc( );
     // If there is trailing whitespace on the cmd
     if( *( cmd + strlen( cmd ) - 1 ) == ' ' )
     {
         completionString = "";
         completionArgument++;
     }
     else
         completionString = Cmd_Argv( completionArgument - 1 );
 #ifndef DEDICATED
     // Unconditionally add a '\' to the start of the buffer
     if( completionField->buffer[ 0 ] &&
             completionField->buffer[ 0 ] != '\\' )
     {
         if( completionField->buffer[ 0 ] != '/' )
         {
             // Buffer is full, refuse to complete
             if( strlen( completionField->buffer ) + 1 >=
                 sizeof( completionField->buffer ) )
                 return;
             memmove( &completionField->buffer[ 1 ],
                 &completionField->buffer[ 0 ],
                 strlen( completionField->buffer ) + 1 );
             completionField->cursor++;
         }
         completionField->buffer[ 0 ] = '\\';
     }
 #endif
     if( completionArgument > 1 )
     {
         const char *baseCmd = Cmd_Argv( 0 );
         char *p;
 #ifndef DEDICATED
         // This should always be true
         if( baseCmd[ 0 ] == '\\' || baseCmd[ 0 ] == '/' )
             baseCmd++;
 #endif
         if( ( p = Field_FindFirstSeparator( cmd ) ) )
             Field_CompleteCommand( p + 1, qtrue, qtrue ); // Compound command
         else
             Cmd_CompleteArgument( baseCmd, cmd, completionArgument );
     }
     else
     {
         if( completionString[0] == '\\' || completionString[0] == '/' )
             completionString++;
         matchCount = 0;
         shortestMatch[ 0 ] = 0;
         if( strlen( completionString ) == 0 )
             return;
         if( doCommands )
             Cmd_CommandCompletion( FindMatches );
         if( doCvars )
             Cvar_CommandCompletion( FindMatches );
         if( !Field_Complete( ) )
         {
             // run through again, printing matches
             if( doCommands )
                 Cmd_CommandCompletion( PrintMatches );
             if( doCvars )
                 Cvar_CommandCompletion( PrintCvarMatches );
         }
     }
 }
References field_t::buffer, Cmd_Argc(), Cmd_Argv(), Cmd_CommandCompletion(), Cmd_CompleteArgument(), Cmd_TokenizeStringIgnoreQuotes(), Com_SkipCharset(), completionField, completionString, field_t::cursor, Cvar_CommandCompletion(), Field_Complete(), Field_CompleteCommand(), Field_FindFirstSeparator(), FindMatches(), matchCount, memmove(), PrintCvarMatches(), PrintMatches(), qtrue, and shortestMatch.
Field_CompleteFilename()
void Field_CompleteFilename (const char * dir, const char * ext, qboolean stripExt, qboolean allowNonPureFilesOnDisk)
Definition at line 3275 of file common.c.
 {
     matchCount = 0;
     shortestMatch[ 0 ] = 0;
     FS_FilenameCompletion( dir, ext, stripExt, FindMatches, allowNonPureFilesOnDisk );
     if( !Field_Complete( ) )
         FS_FilenameCompletion( dir, ext, stripExt, PrintMatches, allowNonPureFilesOnDisk );
 }
References dir, ext, Field_Complete(), FindMatches(), FS_FilenameCompletion(), matchCount, PrintMatches(), and shortestMatch.
Field_CompleteKeyname()
void Field_CompleteKeyname (void)
Definition at line 3258 of file common.c.
 {
     matchCount = 0;
     shortestMatch[ 0 ] = 0;
     Key_KeynameCompletion( FindMatches );
     if( !Field_Complete( ) )
         Key_KeynameCompletion( PrintMatches );
 }
References Field_Complete(), FindMatches(), Key_KeynameCompletion(), matchCount, PrintMatches(), and shortestMatch.
Field_FindFirstSeparator()
static char* Field_FindFirstSeparator (char * s) static
Definition at line 3208 of file common.c.
 {
     int i;
     for( i = 0; i < strlen( s ); i++ )
     {
         if( s[ i ] == ';' )
             return &s[ i ];
     }
     return NULL;
 }
References NULL.
Referenced by Field_CompleteCommand().
FindMatches()
static void FindMatches (const char * s) static
Definition at line 3151 of file common.c.
{
     int     i;
     if ( Q_stricmpn( s, completionString, strlen( completionString ) ) ) {
         return;
     }
     matchCount++;
     if ( matchCount == 1 ) {
         Q_strncpyz( shortestMatch, s, sizeof( shortestMatch ) );
         return;
     }
     // cut shortestMatch to the amount common with s
     for ( i = 0 ; shortestMatch[i] ; i++ ) {
         if ( i >= strlen( s ) ) {
             shortestMatch[i] = 0;
             break;
         }
         if ( tolower(shortestMatch[i]) != tolower(s[i]) ) {
             shortestMatch[i] = 0;
         }
     }
 }
References completionString, matchCount, Q_stricmpn(), Q_strncpyz(), and shortestMatch.
Referenced by Field_CompleteCommand(), Field_CompleteFilename(), and Field_CompleteKeyname().
Hunk_AllocateTempMemory()
void* Hunk_AllocateTempMemory (int size)
Definition at line 1768 of file common.c.
{
     void        *buf;
     hunkHeader_t    *hdr;
     // return a Z_Malloc'd block if the hunk has not been initialized
     // this allows the config and product id files ( journal files too ) to be loaded
     // by the file system without redunant routines in the file system utilizing different
     // memory systems
     if ( s_hunkData == NULL )
     {
         return Z_Malloc(size);
     }
     Hunk_SwapBanks();
     size = PAD(size, sizeof(intptr_t)) + sizeof( hunkHeader_t );
     if ( hunk_temp->temp + hunk_permanent->permanent + size > s_hunkTotal ) {
         Com_Error( ERR_DROP, "Hunk_AllocateTempMemory: failed on %i", size );
     }
     if ( hunk_temp == &hunk_low ) {
         buf = (void *)(s_hunkData + hunk_temp->temp);
         hunk_temp->temp += size;
     } else {
         hunk_temp->temp += size;
         buf = (void *)(s_hunkData + s_hunkTotal - hunk_temp->temp );
     }
     if ( hunk_temp->temp > hunk_temp->tempHighwater ) {
         hunk_temp->tempHighwater = hunk_temp->temp;
     }
     hdr = (hunkHeader_t *)buf;
     buf = (void *)(hdr+1);
     hdr->magic = HUNK_MAGIC;
     hdr->size = size;
     // don't bother clearing, because we are going to load a file over it
     return buf;
 }
References Com_Error(), ERR_DROP, hunk_low, HUNK_MAGIC, hunk_permanent, Hunk_SwapBanks(), hunk_temp, intptr_t(), hunkHeader_t::magic, NULL, PAD, hunkUsed_t::permanent, s_hunkData, s_hunkTotal, hunkHeader_t::size, hunkUsed_t::temp, hunkUsed_t::tempHighwater, and Z_Malloc.
Hunk_AllocDebug()
void* Hunk_AllocDebug (int size, ha_pref preference, char * label, char * file, int line)
Definition at line 1690 of file common.c.
{
 #else
 void *Hunk_Alloc( int size, ha_pref preference ) {
 #endif
     void    *buf;
     if ( s_hunkData == NULL)
     {
         Com_Error( ERR_FATAL, "Hunk_Alloc: Hunk memory system not initialized" );
     }
     // can't do preference if there is any temp allocated
     if (preference == h_dontcare || hunk_temp->temp != hunk_temp->permanent) {
         Hunk_SwapBanks();
     } else {
         if (preference == h_low && hunk_permanent != &hunk_low) {
             Hunk_SwapBanks();
         } else if (preference == h_high && hunk_permanent != &hunk_high) {
             Hunk_SwapBanks();
         }
     }
 #ifdef HUNK_DEBUG
     size += sizeof(hunkblock_t);
 #endif
     // round to cacheline
     size = (size+31)&~31;
     if ( hunk_low.temp + hunk_high.temp + size > s_hunkTotal ) {
 #ifdef HUNK_DEBUG
         Hunk_Log();
         Hunk_SmallLog();
         Com_Error(ERR_DROP, "Hunk_Alloc failed on %i: %s, line: %d (%s)", size, file, line, label);
 #else
         Com_Error(ERR_DROP, "Hunk_Alloc failed on %i", size);
 #endif
     }
     if ( hunk_permanent == &hunk_low ) {
         buf = (void *)(s_hunkData + hunk_permanent->permanent);
         hunk_permanent->permanent += size;
     } else {
         hunk_permanent->permanent += size;
         buf = (void *)(s_hunkData + s_hunkTotal - hunk_permanent->permanent );
     }
     hunk_permanent->temp = hunk_permanent->permanent;
     Com_Memset( buf, 0, size );
 #ifdef HUNK_DEBUG
     {
         hunkblock_t *block;
         block = (hunkblock_t *) buf;
         block->size = size - sizeof(hunkblock_t);
         block->file = file;
         block->label = label;
         block->line = line;
         block->next = hunkblocks;
         hunkblocks = block;
         buf = ((byte *) buf) + sizeof(hunkblock_t);
     }
 #endif
     return buf;
 }
References Com_Error(), Com_Memset, ERR_DROP, ERR_FATAL, file, h_dontcare, h_high, h_low, Hunk_Alloc, hunk_high, Hunk_Log(), hunk_low, hunk_permanent, Hunk_SmallLog(), Hunk_SwapBanks(), hunk_temp, hunkblocks, hunkblock_s::label, line, block::next, NULL, hunkUsed_t::permanent, s_hunkData, s_hunkTotal, and hunkUsed_t::temp.
Hunk_CheckMark()
qboolean Hunk_CheckMark (void)
Definition at line 1616 of file common.c.
{
     if( hunk_low.mark || hunk_high.mark ) {
         return qtrue;
     }
     return qfalse;
 }
References hunk_high, hunk_low, hunkUsed_t::mark, qfalse, and qtrue.
Hunk_Clear()
void Hunk_Clear (void)
Definition at line 1634 of file common.c.
{
 #ifndef DEDICATED
     CL_ShutdownCGame();
     CL_ShutdownUI();
 #endif
     SV_ShutdownGameProgs();
 #ifndef DEDICATED
     CIN_CloseAllVideos();
 #endif
     hunk_low.mark = 0;
     hunk_low.permanent = 0;
     hunk_low.temp = 0;
     hunk_low.tempHighwater = 0;
     hunk_high.mark = 0;
     hunk_high.permanent = 0;
     hunk_high.temp = 0;
     hunk_high.tempHighwater = 0;
     hunk_permanent = &hunk_low;
     hunk_temp = &hunk_high;
     Com_Printf( "Hunk_Clear: reset the hunk ok\n" );
     VM_Clear();
 #ifdef HUNK_DEBUG
     hunkblocks = NULL;
 #endif
 }
References CIN_CloseAllVideos(), CL_ShutdownCGame(), CL_ShutdownUI(), Com_Printf(), hunk_high, hunk_low, hunk_permanent, hunk_temp, hunkblocks, hunkUsed_t::mark, NULL, hunkUsed_t::permanent, SV_ShutdownGameProgs(), hunkUsed_t::temp, hunkUsed_t::tempHighwater, and VM_Clear().
Hunk_ClearTempMemory()
void Hunk_ClearTempMemory (void)
Definition at line 1865 of file common.c.
{
     if ( s_hunkData != NULL ) {
         hunk_temp->temp = hunk_temp->permanent;
     }
 }
References hunk_temp, NULL, hunkUsed_t::permanent, s_hunkData, and hunkUsed_t::temp.
Hunk_ClearToMark()
void Hunk_ClearToMark (void)
Definition at line 1606 of file common.c.
{
     hunk_low.permanent = hunk_low.temp = hunk_low.mark;
     hunk_high.permanent = hunk_high.temp = hunk_high.mark;
 }
References hunk_high, hunk_low, hunkUsed_t::mark, hunkUsed_t::permanent, and hunkUsed_t::temp.
Hunk_FreeTempMemory()
void Hunk_FreeTempMemory (void * buf)
Definition at line 1817 of file common.c.
{
     hunkHeader_t    *hdr;
       // free with Z_Free if the hunk has not been initialized
       // this allows the config and product id files ( journal files too ) to be loaded
       // by the file system without redunant routines in the file system utilizing different
       // memory systems
     if ( s_hunkData == NULL )
     {
         Z_Free(buf);
         return;
     }
     hdr = ( (hunkHeader_t *)buf ) - 1;
     if ( hdr->magic != HUNK_MAGIC ) {
         Com_Error( ERR_FATAL, "Hunk_FreeTempMemory: bad magic" );
     }
     hdr->magic = HUNK_FREE_MAGIC;
     // this only works if the files are freed in stack order,
     // otherwise the memory will stay around until Hunk_ClearTempMemory
     if ( hunk_temp == &hunk_low ) {
         if ( hdr == (void *)(s_hunkData + hunk_temp->temp - hdr->size ) ) {
             hunk_temp->temp -= hdr->size;
         } else {
             Com_Printf( "Hunk_FreeTempMemory: not the final block\n" );
         }
     } else {
         if ( hdr == (void *)(s_hunkData + s_hunkTotal - hunk_temp->temp ) ) {
             hunk_temp->temp -= hdr->size;
         } else {
             Com_Printf( "Hunk_FreeTempMemory: not the final block\n" );
         }
     }
 }
References Com_Error(), Com_Printf(), ERR_FATAL, HUNK_FREE_MAGIC, hunk_low, HUNK_MAGIC, hunk_temp, hunkHeader_t::magic, NULL, s_hunkData, s_hunkTotal, hunkHeader_t::size, hunkUsed_t::temp, and Z_Free().
Hunk_Log()
void Hunk_Log (void)
Definition at line 1444 of file common.c.
                      {
     hunkblock_t *block;
     char        buf[4096];
     int size, numBlocks;
     if (!logfile || !FS_Initialized())
         return;
     size = 0;
     numBlocks = 0;
     Com_sprintf(buf, sizeof(buf), "\r\n================\r\nHunk log\r\n================\r\n");
     FS_Write(buf, strlen(buf), logfile);
     for (block = hunkblocks ; block; block = block->next) {
 #ifdef HUNK_DEBUG
         Com_sprintf(buf, sizeof(buf), "size = %8d: %s, line: %d (%s)\r\n", block->size, block->file, block->line, block->label);
         FS_Write(buf, strlen(buf), logfile);
 #endif
         size += block->size;
         numBlocks++;
     }
     Com_sprintf(buf, sizeof(buf), "%d Hunk memory\r\n", size);
     FS_Write(buf, strlen(buf), logfile);
     Com_sprintf(buf, sizeof(buf), "%d hunk blocks\r\n", numBlocks);
     FS_Write(buf, strlen(buf), logfile);
 }
References Com_sprintf(), FS_Initialized(), FS_Write(), hunkblocks, logfile, and block::next.
Hunk_MemoryRemaining()
int Hunk_MemoryRemaining (void)
Definition at line 1578 of file common.c.
{
     int     low, high;
     low = hunk_low.permanent > hunk_low.temp ? hunk_low.permanent : hunk_low.temp;
     high = hunk_high.permanent > hunk_high.temp ? hunk_high.permanent : hunk_high.temp;
     return s_hunkTotal - ( low + high );
 }
References hunk_high, hunk_low, hunkUsed_t::permanent, s_hunkTotal, and hunkUsed_t::temp.
Hunk_SetMark()
void Hunk_SetMark (void)
Definition at line 1594 of file common.c.
{
     hunk_low.mark = hunk_low.permanent;
     hunk_high.mark = hunk_high.permanent;
 }
References hunk_high, hunk_low, hunkUsed_t::mark, and hunkUsed_t::permanent.
Hunk_SmallLog()
void Hunk_SmallLog (void)
Definition at line 1474 of file common.c.
{
     hunkblock_t *block, *block2;
     char        buf[4096];
     int size, locsize, numBlocks;
     if (!logfile || !FS_Initialized())
         return;
     for (block = hunkblocks ; block; block = block->next) {
         block->printed = qfalse;
     }
     size = 0;
     numBlocks = 0;
     Com_sprintf(buf, sizeof(buf), "\r\n================\r\nHunk Small log\r\n================\r\n");
     FS_Write(buf, strlen(buf), logfile);
     for (block = hunkblocks; block; block = block->next) {
         if (block->printed) {
             continue;
         }
         locsize = block->size;
         for (block2 = block->next; block2; block2 = block2->next) {
             if (block->line != block2->line) {
                 continue;
             }
             if (Q_stricmp(block->file, block2->file)) {
                 continue;
             }
             size += block2->size;
             locsize += block2->size;
             block2->printed = qtrue;
         }
 #ifdef HUNK_DEBUG
         Com_sprintf(buf, sizeof(buf), "size = %8d: %s, line: %d (%s)\r\n", locsize, block->file, block->line, block->label);
         FS_Write(buf, strlen(buf), logfile);
 #endif
         size += block->size;
         numBlocks++;
     }
     Com_sprintf(buf, sizeof(buf), "%d Hunk memory\r\n", size);
     FS_Write(buf, strlen(buf), logfile);
     Com_sprintf(buf, sizeof(buf), "%d hunk blocks\r\n", numBlocks);
     FS_Write(buf, strlen(buf), logfile);
 }
References Com_sprintf(), FS_Initialized(), FS_Write(), hunkblocks, logfile, block::next, Q_stricmp(), qfalse, and qtrue.
Hunk_SwapBanks()
static void Hunk_SwapBanks (void) static
Definition at line 1664 of file common.c.
{
     hunkUsed_t  *swap;
     // can't swap banks if there is any temp already allocated
     if ( hunk_temp->temp != hunk_temp->permanent ) {
         return;
     }
     // if we have a larger highwater mark on this side, start making
     // our permanent allocations here and use the other side for temp
     if ( hunk_temp->tempHighwater - hunk_temp->permanent >
         hunk_permanent->tempHighwater - hunk_permanent->permanent ) {
         swap = hunk_temp;
         hunk_temp = hunk_permanent;
         hunk_permanent = swap;
     }
 }
References hunk_permanent, hunk_temp, hunkUsed_t::permanent, swap, hunkUsed_t::temp, and hunkUsed_t::tempHighwater.
Referenced by Hunk_AllocateTempMemory(), and Hunk_AllocDebug().
Info_Print()
void Info_Print (const char * s)
Definition at line 504 of file common.c.
{
     char    key[BIG_INFO_KEY];
     char    value[BIG_INFO_VALUE];
     char    *o;
     int     l;
     if (*s == '\\')
         s++;
     while (*s)
     {
         o = key;
         while (*s && *s != '\\')
             *o++ = *s++;
         l = o - key;
         if (l < 20)
         {
             Com_Memset (o, ' ', 20-l);
             key[20] = 0;
         }
         else
             *o = 0;
         Com_Printf ("%s ", key);
         if (!*s)
         {
             Com_Printf ("MISSING VALUE\n");
             return;
         }
         o = value;
         s++;
         while (*s && *s != '\\')
             *o++ = *s++;
         *o = 0;
         if (*s)
             s++;
         Com_Printf ("%s\n", value);
     }
 }
References BIG_INFO_KEY, BIG_INFO_VALUE, Com_Memset, and Com_Printf().
PrintCvarMatches()
static void PrintCvarMatches (const char * s) static
Definition at line 3194 of file common.c.
{
     char value[ TRUNCATE_LENGTH ];
     if ( !Q_stricmpn( s, shortestMatch, strlen( shortestMatch ) ) ) {
         Com_TruncateLongString( value, Cvar_VariableString( s ) );
         Com_Printf( "    %s = \"%s\"\n", s, value );
     }
 }
References Com_Printf(), Com_TruncateLongString(), Cvar_VariableString(), Q_stricmpn(), shortestMatch, and TRUNCATE_LENGTH.
Referenced by Field_CompleteCommand().
PrintMatches()
static void PrintMatches (const char * s) static
Definition at line 3182 of file common.c.
{
     if ( !Q_stricmpn( s, shortestMatch, strlen( shortestMatch ) ) ) {
         Com_Printf( "    %s\n", s );
     }
 }
References Com_Printf(), Q_stricmpn(), and shortestMatch.
Referenced by Field_CompleteCommand(), Field_CompleteFilename(), and Field_CompleteKeyname().
S_MallocDebug()
void* S_MallocDebug (int size, char * label, char * file, int line)
Definition at line 1048 of file common.c.
{
     return Z_TagMallocDebug( size, TAG_SMALL, label, file, line );
 }
References line, TAG_SMALL, and Z_TagMallocDebug().
SV_ShutdownGameProgs()
void SV_ShutdownGameProgs (void)
Definition at line 473 of file sv_game.c.
{
     if ( !gvm ) {
         return;
     }
     VM_Call( gvm, GAME_SHUTDOWN, qfalse );
     VM_Free( gvm );
     gvm = NULL;
 }
References GAME_SHUTDOWN, gvm, NULL, qfalse, VM_Call(), and VM_Free().
Z_AvailableMemory()
int Z_AvailableMemory (void)
Definition at line 820 of file common.c.
{
     return Z_AvailableZoneMemory( mainzone );
 }
References mainzone, and Z_AvailableZoneMemory().
Z_AvailableZoneMemory()
int Z_AvailableZoneMemory (memzone_t * zone)
Definition at line 811 of file common.c.
{
     return zone->size - zone->used;
 }
References memzone_t::size, and memzone_t::used.
Z_CheckHeap()
void Z_CheckHeap (void)
Definition at line 1062 of file common.c.
{
     memblock_t  *block;
     for (block = mainzone->blocklist.next ; ; block = block->next) {
         if (block->next == &mainzone->blocklist) {
             break;          // all blocks have been hit
         }
         if ( (byte *)block + block->size != (byte *)block->next)
             Com_Error( ERR_FATAL, "Z_CheckHeap: block size does not touch the next block" );
         if ( block->next->prev != block) {
             Com_Error( ERR_FATAL, "Z_CheckHeap: next block doesn't have proper back link" );
         }
         if ( !block->tag && !block->next->tag ) {
             Com_Error( ERR_FATAL, "Z_CheckHeap: two consecutive free blocks" );
         }
     }
 }
References memzone_t::blocklist, Com_Error(), ERR_FATAL, mainzone, and block::next.
Z_ClearZone()
void Z_ClearZone (memzone_t * zone, int size)
Definition at line 786 of file common.c.
{
     memblock_t  *block;
     // set the entire zone to one free block
     zone->blocklist.next = zone->blocklist.prev = block =
         (memblock_t *)( (byte *)zone + sizeof(memzone_t) );
     zone->blocklist.tag = 1;    // in use block
     zone->blocklist.id = 0;
     zone->blocklist.size = 0;
     zone->rover = block;
     zone->size = size;
     zone->used = 0;
     block->prev = block->next = &zone->blocklist;
     block->tag = 0;         // free block
     block->id = ZONEID;
     block->size = size - sizeof(memzone_t);
 }
References memzone_t::blocklist, block::next, memzone_t::rover, memzone_t::size, memzone_t::used, and ZONEID.
Z_Free()
void Z_Free (void * ptr)
Definition at line 829 of file common.c.
{
     memblock_t  *block, *other;
     memzone_t *zone;
     if (!ptr) {
         Com_Error( ERR_DROP, "Z_Free: NULL pointer" );
     }
     block = (memblock_t *) ( (byte *)ptr - sizeof(memblock_t));
     if (block->id != ZONEID) {
         Com_Error( ERR_FATAL, "Z_Free: freed a pointer without ZONEID" );
     }
     if (block->tag == 0) {
         Com_Error( ERR_FATAL, "Z_Free: freed a freed pointer" );
     }
     // if static memory
     if (block->tag == TAG_STATIC) {
         return;
     }
     // check the memory trash tester
     if ( *(int *)((byte *)block + block->size - 4 ) != ZONEID ) {
         Com_Error( ERR_FATAL, "Z_Free: memory block wrote past end" );
     }
     if (block->tag == TAG_SMALL) {
         zone = smallzone;
     }
     else {
         zone = mainzone;
     }
     zone->used -= block->size;
     // set the block to something that should cause problems
     // if it is referenced...
     Com_Memset( ptr, 0xaa, block->size - sizeof( *block ) );
     block->tag = 0;     // mark as free
     other = block->prev;
     if (!other->tag) {
         // merge with previous free block
         other->size += block->size;
         other->next = block->next;
         other->next->prev = other;
         if (block == zone->rover) {
             zone->rover = other;
         }
         block = other;
     }
     zone->rover = block;
     other = block->next;
     if ( !other->tag ) {
         // merge the next free block onto the end
         block->size += other->size;
         block->next = other->next;
         block->next->prev = block;
         if (other == zone->rover) {
             zone->rover = block;
         }
     }
 }
References Com_Error(), Com_Memset, ERR_DROP, ERR_FATAL, mainzone, block::next, ptr(), memzone_t::rover, smallzone, TAG_SMALL, TAG_STATIC, memzone_t::used, and ZONEID.
Z_FreeTags()
void Z_FreeTags (int tag)
Definition at line 900 of file common.c.
{
     int         count;
     memzone_t   *zone;
     if ( tag == TAG_SMALL ) {
         zone = smallzone;
     }
     else {
         zone = mainzone;
     }
     count = 0;
     // use the rover as our pointer, because
     // Z_Free automatically adjusts it
     zone->rover = zone->blocklist.next;
     do {
         if ( zone->rover->tag == tag ) {
             count++;
             Z_Free( (void *)(zone->rover + 1) );
             continue;
         }
         zone->rover = zone->rover->next;
     } while ( zone->rover != &zone->blocklist );
 }
References memzone_t::blocklist, mainzone, memzone_t::rover, smallzone, TAG_SMALL, and Z_Free().
Z_LogHeap()
void Z_LogHeap (void)
Definition at line 1141 of file common.c.
{
     Z_LogZoneHeap( mainzone, "MAIN" );
     Z_LogZoneHeap( smallzone, "SMALL" );
 }
References mainzone, smallzone, and Z_LogZoneHeap().
Z_LogZoneHeap()
void Z_LogZoneHeap (memzone_t * zone, char * name)
Definition at line 1085 of file common.c.
{
 #ifdef ZONE_DEBUG
     char dump[32], *ptr;
     int  i, j;
 #endif
     memblock_t  *block;
     char        buf[4096];
     int size, allocSize, numBlocks;
     if (!logfile || !FS_Initialized())
         return;
     size = numBlocks = 0;
 #ifdef ZONE_DEBUG
     allocSize = 0;
 #endif
     Com_sprintf(buf, sizeof(buf), "\r\n================\r\n%s log\r\n================\r\n", name);
     FS_Write(buf, strlen(buf), logfile);
     for (block = zone->blocklist.next ; block->next != &zone->blocklist; block = block->next) {
         if (block->tag) {
 #ifdef ZONE_DEBUG
             ptr = ((char *) block) + sizeof(memblock_t);
             j = 0;
             for (i = 0; i < 20 && i < block->d.allocSize; i++) {
                 if (ptr[i] >= 32 && ptr[i] < 127) {
                     dump[j++] = ptr[i];
                 }
                 else {
                     dump[j++] = '_';
                 }
             }
             dump[j] = '\0';
             Com_sprintf(buf, sizeof(buf), "size = %8d: %s, line: %d (%s) [%s]\r\n", block->d.allocSize, block->d.file, block->d.line, block->d.label, dump);
             FS_Write(buf, strlen(buf), logfile);
             allocSize += block->d.allocSize;
 #endif
             size += block->size;
             numBlocks++;
         }
     }
 #ifdef ZONE_DEBUG
     // subtract debug memory
     size -= numBlocks * sizeof(zonedebug_t);
 #else
     allocSize = numBlocks * sizeof(memblock_t); // + 32 bit alignment
 #endif
     Com_sprintf(buf, sizeof(buf), "%d %s memory in %d blocks\r\n", size, name, numBlocks);
     FS_Write(buf, strlen(buf), logfile);
     Com_sprintf(buf, sizeof(buf), "%d %s memory overhead\r\n", size - allocSize, name);
     FS_Write(buf, strlen(buf), logfile);
 }
References memzone_t::blocklist, Com_sprintf(), FS_Initialized(), FS_Write(), logfile, block::next, and ptr().
Z_MallocDebug()
void* Z_MallocDebug (int size, char * label, char * file, int line)
Definition at line 1029 of file common.c.
{
 #else
 void *Z_Malloc( int size ) {
 #endif
     void    *buf;
   //Z_CheckHeap (); // DEBUG
 #ifdef ZONE_DEBUG
     buf = Z_TagMallocDebug( size, TAG_GENERAL, label, file, line );
 #else
     buf = Z_TagMalloc( size, TAG_GENERAL );
 #endif
     Com_Memset( buf, 0, size );
     return buf;
 }
References Com_Memset, line, TAG_GENERAL, Z_Malloc, Z_TagMalloc, and Z_TagMallocDebug().
Z_TagMallocDebug()
void* Z_TagMallocDebug (int size, int tag, char * label, char * file, int line)
Definition at line 931 of file common.c.
{
     int     allocSize;
 #else
 void *Z_TagMalloc( int size, int tag ) {
 #endif
     int     extra;
     memblock_t  *start, *rover, *new, *base;
     memzone_t *zone;
     if (!tag) {
         Com_Error( ERR_FATAL, "Z_TagMalloc: tried to use a 0 tag" );
     }
     if ( tag == TAG_SMALL ) {
         zone = smallzone;
     }
     else {
         zone = mainzone;
     }
 #ifdef ZONE_DEBUG
     allocSize = size;
 #endif
     //
     // scan through the block list looking for the first free block
     // of sufficient size
     //
     size += sizeof(memblock_t); // account for size of block header
     size += 4;                  // space for memory trash tester
     size = PAD(size, sizeof(intptr_t));     // align to 32/64 bit boundary
     base = rover = zone->rover;
     start = base->prev;
     do {
         if (rover == start) {
             // scaned all the way around the list
 #ifdef ZONE_DEBUG
             Z_LogHeap();
             Com_Error(ERR_FATAL, "Z_Malloc: failed on allocation of %i bytes from the %s zone: %s, line: %d (%s)",
                                 size, zone == smallzone ? "small" : "main", file, line, label);
 #else
             Com_Error(ERR_FATAL, "Z_Malloc: failed on allocation of %i bytes from the %s zone",
                                 size, zone == smallzone ? "small" : "main");
 #endif
             return NULL;
         }
         if (rover->tag) {
             base = rover = rover->next;
         } else {
             rover = rover->next;
         }
     } while (base->tag || base->size < size);
     //
     // found a block big enough
     //
     extra = base->size - size;
     if (extra > MINFRAGMENT) {
         // there will be a free fragment after the allocated block
         new = (memblock_t *) ((byte *)base + size );
         new->size = extra;
         new->tag = 0;           // free block
         new->prev = base;
         new->id = ZONEID;
         new->next = base->next;
         new->next->prev = new;
         base->next = new;
         base->size = size;
     }
     base->tag = tag;            // no longer a free block
     zone->rover = base->next;   // next allocation will start looking here
     zone->used += base->size;   //
     base->id = ZONEID;
 #ifdef ZONE_DEBUG
     base->d.label = label;
     base->d.file = file;
     base->d.line = line;
     base->d.allocSize = allocSize;
 #endif
     // marker for memory trash testing
     *(int *)((byte *)base + base->size - 4) = ZONEID;
     return (void *) ((byte *)base + sizeof(memblock_t));
 }
References Com_Error(), ERR_FATAL, file, intptr_t(), line, mainzone, MINFRAGMENT, NULL, PAD, memzone_t::rover, smallzone, TAG_SMALL, memzone_t::used, Z_LogHeap(), Z_TagMalloc, and ZONEID.
Variable Documentation
abortframe
jmp_buf abortframe
Definition at line 49 of file common.c.
cl_packetdelay
cvar_t* cl_packetdelay
Definition at line 78 of file common.c.
cl_paused
cvar_t* cl_paused
Definition at line 76 of file common.c.
com_abnormalExit
cvar_t* com_abnormalExit
Definition at line 86 of file common.c.
com_altivec
cvar_t* com_altivec
Definition at line 65 of file common.c.
com_ansiColor
cvar_t* com_ansiColor
Definition at line 81 of file common.c.
com_argc
int com_argc
Definition at line 46 of file common.c.
com_argv
char* com_argv[MAX_NUM_ARGVS+1]
Definition at line 47 of file common.c.
com_basegame
cvar_t* com_basegame
Definition at line 92 of file common.c.
com_blood
cvar_t* com_blood
Definition at line 73 of file common.c.
com_buildScript
cvar_t* com_buildScript
Definition at line 74 of file common.c.
com_busyWait
cvar_t* com_busyWait
Definition at line 94 of file common.c.
com_cameraMode
cvar_t* com_cameraMode
Definition at line 80 of file common.c.
com_cl_running
cvar_t* com_cl_running
Definition at line 68 of file common.c.
com_consoleLines
char* com_consoleLines[MAX_CONSOLE_LINES]
Definition at line 376 of file common.c.
com_dedicated
cvar_t* com_dedicated
Definition at line 60 of file common.c.
com_developer
cvar_t* com_developer
Definition at line 59 of file common.c.
com_errorEntered
qboolean com_errorEntered = qfalse
Definition at line 112 of file common.c.
com_errorMessage
char com_errorMessage[MAXPRINTMSG]
Definition at line 116 of file common.c.
com_fixedtime
cvar_t* com_fixedtime
Definition at line 62 of file common.c.
com_frameNumber
int com_frameNumber
Definition at line 110 of file common.c.
com_frameTime
int com_frameTime
Definition at line 109 of file common.c.
com_fullyInitialized
qboolean com_fullyInitialized = qfalse
Definition at line 113 of file common.c.
Referenced by FS_FOpenFileReadDir().
com_gamename
cvar_t* com_gamename
Definition at line 87 of file common.c.
com_gameRestarting
qboolean com_gameRestarting = qfalse
Definition at line 114 of file common.c.
com_homepath
cvar_t* com_homepath
Definition at line 93 of file common.c.
com_introPlayed
cvar_t* com_introPlayed
Definition at line 75 of file common.c.
com_journal
cvar_t* com_journal
Definition at line 63 of file common.c.
com_journalDataFile
fileHandle_t com_journalDataFile
Definition at line 56 of file common.c.
com_journalFile
fileHandle_t com_journalFile
Definition at line 55 of file common.c.
com_logfile
cvar_t* com_logfile
Definition at line 69 of file common.c.
com_maxfps
cvar_t* com_maxfps
Definition at line 64 of file common.c.
com_maxfpsMinimized
cvar_t* com_maxfpsMinimized
Definition at line 85 of file common.c.
com_maxfpsUnfocused
cvar_t* com_maxfpsUnfocused
Definition at line 83 of file common.c.
com_minimized
cvar_t* com_minimized
Definition at line 84 of file common.c.
com_numConsoleLines
int com_numConsoleLines
Definition at line 375 of file common.c.
com_pipefile
cvar_t* com_pipefile
Definition at line 70 of file common.c.
com_protocol
cvar_t* com_protocol
Definition at line 88 of file common.c.
com_pushedEvents
sysEvent_t com_pushedEvents[MAX_PUSHED_EVENTS] static
Definition at line 1884 of file common.c.
Referenced by Com_GetEvent(), Com_InitPushEvent(), and Com_PushEvent().
com_pushedEventsHead
int com_pushedEventsHead = 0 static
Definition at line 1882 of file common.c.
Referenced by Com_GetEvent(), Com_InitPushEvent(), and Com_PushEvent().
com_pushedEventsTail
int com_pushedEventsTail = 0 static
Definition at line 1883 of file common.c.
Referenced by Com_GetEvent(), Com_InitPushEvent(), and Com_PushEvent().
com_showtrace
cvar_t* com_showtrace
Definition at line 71 of file common.c.
com_speeds
cvar_t* com_speeds
Definition at line 58 of file common.c.
com_sv_running
cvar_t* com_sv_running
Definition at line 67 of file common.c.
com_timedemo
cvar_t* com_timedemo
Definition at line 66 of file common.c.
com_timescale
cvar_t* com_timescale
Definition at line 61 of file common.c.
com_unfocused
cvar_t* com_unfocused
Definition at line 82 of file common.c.
com_version
cvar_t* com_version
Definition at line 72 of file common.c.
completionField
field_t* completionField static
Definition at line 3143 of file common.c.
Referenced by Field_AutoComplete(), Field_Complete(), and Field_CompleteCommand().
completionString
const char* completionString static
Definition at line 3139 of file common.c.
Referenced by Field_Complete(), Field_CompleteCommand(), and FindMatches().
debuglogfile
FILE* debuglogfile
Definition at line 52 of file common.c.
demo_protocols
int demo_protocols[]
Initial value:
=
{ 67, 66, 0 }
Definition at line 34 of file common.c.
emptystring
memstatic_t emptystring
Initial value:
=
    { {(sizeof(memblock_t)+2 + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'\0', '\0'} }
Definition at line 1152 of file common.c.
eventHead
int eventHead = 0 static
Definition at line 1928 of file common.c.
Referenced by Com_GetSystemEvent(), and Com_QueueEvent().
eventQueue
sysEvent_t eventQueue[MAX_QUEUED_EVENTS] static
Definition at line 1927 of file common.c.
Referenced by Com_GetSystemEvent(), Com_Init(), and Com_QueueEvent().
eventTail
int eventTail = 0 static
Definition at line 1929 of file common.c.
Referenced by Com_GetSystemEvent(), and Com_QueueEvent().
hunk_high
hunkUsed_t hunk_high static
Definition at line 1252 of file common.c.
Referenced by Com_Meminfo_f(), Com_TouchMemory(), Hunk_AllocDebug(), Hunk_CheckMark(), Hunk_Clear(), Hunk_ClearToMark(), Hunk_MemoryRemaining(), and Hunk_SetMark().
hunk_low
hunkUsed_t hunk_low static
Definition at line 1252 of file common.c.
Referenced by Com_Meminfo_f(), Com_TouchMemory(), Hunk_AllocateTempMemory(), Hunk_AllocDebug(), Hunk_CheckMark(), Hunk_Clear(), Hunk_ClearToMark(), Hunk_FreeTempMemory(), Hunk_MemoryRemaining(), and Hunk_SetMark().
hunk_permanent
hunkUsed_t* hunk_permanent static
Definition at line 1253 of file common.c.
Referenced by Hunk_AllocateTempMemory(), Hunk_AllocDebug(), Hunk_Clear(), and Hunk_SwapBanks().
hunk_temp
hunkUsed_t * hunk_temp static
Definition at line 1253 of file common.c.
Referenced by Hunk_AllocateTempMemory(), Hunk_AllocDebug(), Hunk_Clear(), Hunk_ClearTempMemory(), Hunk_FreeTempMemory(), and Hunk_SwapBanks().
hunkblocks
hunkblock_t* hunkblocks static
Definition at line 1250 of file common.c.
Referenced by Hunk_AllocDebug(), Hunk_Clear(), Hunk_Log(), and Hunk_SmallLog().
logfile
fileHandle_t logfile static
Definition at line 54 of file common.c.
Referenced by Com_Printf(), Com_Shutdown(), Hunk_Log(), Hunk_SmallLog(), and Z_LogZoneHeap().
mainzone
memzone_t* mainzone
Definition at line 774 of file common.c.
matchCount
int matchCount static
Definition at line 3141 of file common.c.
Referenced by Field_Complete(), Field_CompleteCommand(), Field_CompleteFilename(), Field_CompleteKeyname(), and FindMatches().
numberstring
memstatic_t numberstring[]
Initial value:
= {
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'0', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'1', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'2', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'3', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'4', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'5', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'6', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'7', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'8', '\0'} },
    { {(sizeof(memstatic_t) + 3) & ~3, TAG_STATIC, NULL, NULL, ZONEID}, {'9', '\0'} }
}
Definition at line 1154 of file common.c.
pipefile
fileHandle_t pipefile static
Definition at line 53 of file common.c.
Referenced by Com_Init(), Com_ReadFromPipe(), and Com_Shutdown().
rd_buffer
char* rd_buffer static
Definition at line 123 of file common.c.
Referenced by Com_BeginRedirect(), Com_EndRedirect(), and Com_Printf().
rd_buffersize
int rd_buffersize static
Definition at line 124 of file common.c.
Referenced by Com_BeginRedirect(), Com_EndRedirect(), and Com_Printf().
rd_flush
void(* rd_flush) (char *buffer) static
Definition at line 125 of file common.c.
Referenced by Com_BeginRedirect(), Com_EndRedirect(), and Com_Printf().
s_hunkData
byte* s_hunkData = NULL static
Definition at line 1255 of file common.c.
Referenced by Com_InitHunkMemory(), Com_TouchMemory(), Hunk_AllocateTempMemory(), Hunk_AllocDebug(), Hunk_ClearTempMemory(), and Hunk_FreeTempMemory().
s_hunkTotal
int s_hunkTotal static
Definition at line 1256 of file common.c.
Referenced by Com_InitHunkMemory(), Com_Meminfo_f(), Com_TouchMemory(), Hunk_AllocateTempMemory(), Hunk_AllocDebug(), Hunk_FreeTempMemory(), and Hunk_MemoryRemaining().
s_smallZoneTotal
int s_smallZoneTotal static
Definition at line 1259 of file common.c.
Referenced by Com_InitSmallZoneMemory().
s_zoneTotal
int s_zoneTotal static
Definition at line 1258 of file common.c.
Referenced by Com_InitZoneMemory(), and Com_Meminfo_f().
shortestMatch
char shortestMatch[MAX_TOKEN_CHARS] static
Definition at line 3140 of file common.c.
Referenced by Field_Complete(), Field_CompleteCommand(), Field_CompleteFilename(), Field_CompleteKeyname(), FindMatches(), PrintCvarMatches(), and PrintMatches().
smallzone
memzone_t* smallzone
Definition at line 777 of file common.c.
sv_packetdelay
cvar_t* sv_packetdelay
Definition at line 79 of file common.c.
sv_paused
cvar_t* sv_paused
Definition at line 77 of file common.c.
time_backend
int time_backend
Definition at line 107 of file common.c.
time_frontend
int time_frontend
Definition at line 106 of file common.c.
time_game
int time_game
Definition at line 105 of file common.c.