ZEQ2-Lite: Source/Engine/libspeex/kiss_fft.h File Reference
kiss_fft.h File Reference
#include <stdlib.h>
#include <math.h>
#include "arch.h"
Data Structures
struct kiss_fft_cpx
Macros
#define kiss_fft_free speex_free
#define KISS_FFT_MALLOC speex_alloc
#define kiss_fft_scalar float
Functions
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout)
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void *mem, size_t *lenmem)
void kiss_fft_cleanup (void)
void kiss_fft_stride (kiss_fft_cfg cfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout, int fin_stride)
Macro Definition Documentation
kiss_fft_free
#define kiss_fft_free speex_free
Definition at line 95 of file kiss_fft.h.
KISS_FFT_MALLOC
#define KISS_FFT_MALLOC speex_alloc
Definition at line 30 of file kiss_fft.h.
kiss_fft_scalar
#define kiss_fft_scalar float
Definition at line 40 of file kiss_fft.h.
Function Documentation
kiss_fft()
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx * fin, kiss_fft_cpx * fout)
Definition at line 519 of file kiss_fft.c.
 {
     kiss_fft_stride(cfg,fin,fout,1);
 }
References fout, and kiss_fft_stride().
Referenced by kiss_fftr(), kiss_fftr2(), kiss_fftri(), and kiss_fftri2().
kiss_fft_alloc()
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void * mem, size_t * lenmem)
Definition at line 464 of file kiss_fft.c.
 {
     kiss_fft_cfg st=NULL;
     size_t memneeded = sizeof(struct kiss_fft_state)
         + sizeof(kiss_fft_cpx)*(nfft-1); /* twiddle factors*/
     if ( lenmem==NULL ) {
         st = ( kiss_fft_cfg)KISS_FFT_MALLOC( memneeded );
     }else{
         if (mem != NULL && *lenmem >= memneeded)
             st = (kiss_fft_cfg)mem;
         *lenmem = memneeded;
     }
     if (st) {
         int i;
         st->nfft=nfft;
         st->inverse = inverse_fft;
 #ifdef FIXED_POINT
         for (i=0;i<nfft;++i) {
             spx_word32_t phase = i;
             if (!st->inverse)
                 phase = -phase;
             kf_cexp2(st->twiddles+i, DIV32(SHL32(phase,17),nfft));
         }
 #else
         for (i=0;i<nfft;++i) {
            const double pi=3.14159265358979323846264338327;
            double phase = ( -2*pi /nfft ) * i;
            if (st->inverse)
               phase *= -1;
            kf_cexp(st->twiddles+i, phase );
         }
 #endif
         kf_factor(nfft,st->factors);
     }
     return st;
 }
References DIV32, kf_cexp, kf_cexp2, kf_factor(), KISS_FFT_MALLOC, kiss_fft_cfg::nfft, NULL, and SHL32.
Referenced by kiss_fftr_alloc().
kiss_fft_cleanup()
void kiss_fft_cleanup (void)
kiss_fft_stride()
void kiss_fft_stride (kiss_fft_cfg cfg, const kiss_fft_cpx * fin, kiss_fft_cpx * fout, int fin_stride)
Definition at line 505 of file kiss_fft.c.
 {
     if (fin == fout)
     {
        speex_fatal("In-place FFT not supported");
        /*CHECKBUF(tmpbuf,ntmpbuf,st->nfft);
        kf_work(tmpbuf,fin,1,in_stride, st->factors,st);
        SPEEX_MOVE(fout,tmpbuf,st->nfft);*/
     } else {
        kf_shuffle( fout, fin, 1,in_stride, st->factors,st);
        kf_work( fout, fin, 1,in_stride, st->factors,st, 1, in_stride, 1);
     }
 }
References fout, kf_shuffle(), kf_work(), and speex_fatal.
Referenced by kiss_fft().