ZEQ2-Lite: Source/Game/UI/ui_serverinfo.c File Reference
ui_serverinfo.c File Reference
#include "ui_local.h"
Data Structures
struct serverinfo_t
Macros
#define ID_ADD 100
#define ID_BACK 101
#define SERVERINFO_BACK0 "interface/art/back_0"
#define SERVERINFO_BACK1 "interface/art/back_1"
#define SERVERINFO_FRAMEL "interface/art/frame2_l"
#define SERVERINFO_FRAMER "interface/art/frame1_r"
Functions
void Favorites_Add (void)
void ServerInfo_Cache (void)
static void ServerInfo_Event (void *ptr, int event)
static void ServerInfo_MenuDraw (void)
static sfxHandle_t ServerInfo_MenuKey (int key)
void UI_ServerInfoMenu (void)
Variables
static serverinfo_t s_serverinfo
static char * serverinfo_artlist []
Macro Definition Documentation
ID_ADD
#define ID_ADD 100
Definition at line 39 of file ui_serverinfo.c.
ID_BACK
#define ID_BACK 101
Definition at line 40 of file ui_serverinfo.c.
SERVERINFO_BACK0
#define SERVERINFO_BACK0 "interface/art/back_0"
Definition at line 27 of file ui_serverinfo.c.
SERVERINFO_BACK1
#define SERVERINFO_BACK1 "interface/art/back_1"
Definition at line 28 of file ui_serverinfo.c.
SERVERINFO_FRAMEL
#define SERVERINFO_FRAMEL "interface/art/frame2_l"
Definition at line 25 of file ui_serverinfo.c.
SERVERINFO_FRAMER
#define SERVERINFO_FRAMER "interface/art/frame1_r"
Definition at line 26 of file ui_serverinfo.c.
Function Documentation
Favorites_Add()
void Favorites_Add (void)
Definition at line 64 of file ui_serverinfo.c.
 {
     char    adrstr[128];
     char    serverbuff[128];
     int     i;
     int     best;
     trap_Cvar_VariableStringBuffer( "cl_currentServerAddress", serverbuff, sizeof(serverbuff) );
     if (!serverbuff[0])
         return;
     best = 0;
     for (i=0; i<MAX_FAVORITESERVERS; i++)
     {
         trap_Cvar_VariableStringBuffer( va("server%d",i+1), adrstr, sizeof(adrstr) );
         if (!Q_stricmp(serverbuff,adrstr))
         {
             // already in list
             return;
         }
         // use first empty or non-numeric available slot
         if ((adrstr[0]  < '0' || adrstr[0] > '9' ) && !best)
             best = i+1;
     }
     if (best)
         trap_Cvar_Set( va("server%d",best), serverbuff);
 }
References MAX_FAVORITESERVERS, Q_stricmp(), trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and va().
ServerInfo_Cache()
void ServerInfo_Cache (void)
Definition at line 168 of file ui_serverinfo.c.
 {
     int i;
     // touch all our pics
     for (i=0; ;i++)
     {
         if (!serverinfo_artlist[i])
             break;
         trap_R_RegisterShaderNoMip(serverinfo_artlist[i]);
     }
 }
References serverinfo_artlist, and trap_R_RegisterShaderNoMip().
ServerInfo_Event()
static void ServerInfo_Event (void * ptr, int event) static
Definition at line 100 of file ui_serverinfo.c.
 {
     switch (((menucommon_s*)ptr)->id)
     {
         case ID_ADD:
             if (event != QM_ACTIVATED)
                 break;
             Favorites_Add();
             UI_PopMenu();
             break;
         case ID_BACK:
             if (event != QM_ACTIVATED)
                 break;
             UI_PopMenu();
             break;
     }
 }
References Favorites_Add(), ID_ADD, ID_BACK, ptr(), QM_ACTIVATED, and UI_PopMenu().
Referenced by UI_ServerInfoMenu().
ServerInfo_MenuDraw()
static void ServerInfo_MenuDraw (void) static
Definition at line 126 of file ui_serverinfo.c.
 {
     const char      *s;
     char            key[MAX_INFO_KEY];
     char            value[MAX_INFO_VALUE];
     int             i = 0, y;
     y = SCREEN_HEIGHT/2 - s_serverinfo.numlines*(SMALLCHAR_HEIGHT)/2 - 20;
     s = s_serverinfo.info;
     while ( s && i < s_serverinfo.numlines ) {
         Info_NextPair( &s, key, value );
         if ( !key[0] ) {
             break;
         }
         Q_strcat( key, MAX_INFO_KEY, ":" );
         UI_DrawString(SCREEN_WIDTH*0.50 - 8,y,key,UI_RIGHT|UI_SMALLFONT|UI_DROPSHADOW,color_white);
         UI_DrawString(SCREEN_WIDTH*0.50 + 8,y,value,UI_LEFT|UI_SMALLFONT|UI_DROPSHADOW,text_color_normal);
         y += SMALLCHAR_HEIGHT;
         i++;
     }
     Menu_Draw( &s_serverinfo.menu );
 }
References color_white, serverinfo_t::info, Info_NextPair(), MAX_INFO_KEY, MAX_INFO_VALUE, serverinfo_t::menu, Menu_Draw(), serverinfo_t::numlines, Q_strcat(), s_serverinfo, SCREEN_HEIGHT, SCREEN_WIDTH, SMALLCHAR_HEIGHT, text_color_normal, UI_DrawString(), UI_DROPSHADOW, UI_LEFT, UI_RIGHT, and UI_SMALLFONT.
Referenced by UI_ServerInfoMenu().
ServerInfo_MenuKey()
static sfxHandle_t ServerInfo_MenuKey (int key) static
Definition at line 158 of file ui_serverinfo.c.
 {
     return ( Menu_DefaultKey( &s_serverinfo.menu, key ) );
 }
References serverinfo_t::menu, Menu_DefaultKey(), and s_serverinfo.
Referenced by UI_ServerInfoMenu().
UI_ServerInfoMenu()
void UI_ServerInfoMenu (void)
Definition at line 186 of file ui_serverinfo.c.
 {
     const char      *s;
     char            key[MAX_INFO_KEY];
     char            value[MAX_INFO_VALUE];
     // zero set all our globals
     memset( &s_serverinfo, 0 ,sizeof(serverinfo_t) );
     ServerInfo_Cache();
     uis.menuamount = 0;
     s_serverinfo.menu.draw       = ServerInfo_MenuDraw;
     s_serverinfo.menu.key        = ServerInfo_MenuKey;
     s_serverinfo.menu.wrapAround = qtrue;
     s_serverinfo.menu.fullscreen = qtrue;
     s_serverinfo.banner.generic.type  = MTYPE_BTEXT;
     s_serverinfo.banner.generic.x     = 320;
     s_serverinfo.banner.generic.y     = 16;
     s_serverinfo.banner.string        = "SERVER INFO";
     s_serverinfo.banner.color         = color_white;
     s_serverinfo.banner.style         = UI_CENTER|UI_DROPSHADOW;
     s_serverinfo.framel.generic.type  = MTYPE_BITMAP;
     s_serverinfo.framel.generic.name  = SERVERINFO_FRAMEL;
     s_serverinfo.framel.generic.flags = QMF_INACTIVE;
     s_serverinfo.framel.generic.x     = 0;
     s_serverinfo.framel.generic.y     = 78;
     s_serverinfo.framel.width         = 256;
     s_serverinfo.framel.height        = 329;
     s_serverinfo.framer.generic.type  = MTYPE_BITMAP;
     s_serverinfo.framer.generic.name  = SERVERINFO_FRAMER;
     s_serverinfo.framer.generic.flags = QMF_INACTIVE;
     s_serverinfo.framer.generic.x     = 376;
     s_serverinfo.framer.generic.y     = 76;
     s_serverinfo.framer.width         = 256;
     s_serverinfo.framer.height        = 334;
     s_serverinfo.add.generic.type     = MTYPE_PTEXT;
     s_serverinfo.add.generic.flags    = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_serverinfo.add.generic.callback = ServerInfo_Event;
     s_serverinfo.add.generic.id       = ID_ADD;
     s_serverinfo.add.generic.x        = 320;
     s_serverinfo.add.generic.y        = 371;
     s_serverinfo.add.string           = "ADD TO FAVORITES";
     s_serverinfo.add.style            = UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW;
     s_serverinfo.add.color            = color_white;
     if( trap_Cvar_VariableValue( "sv_running" ) ) {
         s_serverinfo.add.generic.flags |= QMF_GRAYED;
     }
     s_serverinfo.back.generic.type     = MTYPE_BITMAP;
     s_serverinfo.back.generic.name     = SERVERINFO_BACK0;
     s_serverinfo.back.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_serverinfo.back.generic.callback = ServerInfo_Event;
     s_serverinfo.back.generic.id       = ID_BACK;
     s_serverinfo.back.generic.x        = 0;
     s_serverinfo.back.generic.y        = 480-64;
     s_serverinfo.back.width            = 128;
     s_serverinfo.back.height           = 64;
     s_serverinfo.back.focuspic         = SERVERINFO_BACK1;
     trap_GetConfigString( CS_SERVERINFO, s_serverinfo.info, MAX_INFO_STRING );
     s_serverinfo.numlines = 0;
     s = s_serverinfo.info;
     while ( s ) {
         Info_NextPair( &s, key, value );
         if ( !key[0] ) {
             break;
         }
         s_serverinfo.numlines++;
     }
     if (s_serverinfo.numlines > 16)
         s_serverinfo.numlines = 16;
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.add );
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.back );
     UI_PushMenu( &s_serverinfo.menu );
 }
References serverinfo_t::add, serverinfo_t::back, serverinfo_t::banner, menucommon_s::callback, menutext_s::color, color_white, CS_SERVERINFO, menucommon_s::flags, menubitmap_s::focuspic, serverinfo_t::framel, serverinfo_t::framer, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_ADD, ID_BACK, serverinfo_t::info, Info_NextPair(), MAX_INFO_KEY, MAX_INFO_STRING, MAX_INFO_VALUE, serverinfo_t::menu, Menu_AddItem(), uiStatic_t::menuamount, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, menucommon_s::name, serverinfo_t::numlines, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s_serverinfo, SERVERINFO_BACK0, SERVERINFO_BACK1, ServerInfo_Cache(), ServerInfo_Event(), SERVERINFO_FRAMEL, SERVERINFO_FRAMER, ServerInfo_MenuDraw(), ServerInfo_MenuKey(), menutext_s::string, menutext_s::style, trap_Cvar_VariableValue(), trap_GetConfigString(), menucommon_s::type, UI_CENTER, UI_DROPSHADOW, UI_PushMenu(), UI_SMALLFONT, uis, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Variable Documentation
s_serverinfo
serverinfo_t s_serverinfo static
Definition at line 54 of file ui_serverinfo.c.
Referenced by ServerInfo_MenuDraw(), ServerInfo_MenuKey(), and UI_ServerInfoMenu().
serverinfo_artlist
char* serverinfo_artlist[] static
Initial value:
=
{
    SERVERINFO_FRAMEL,
    SERVERINFO_FRAMER,
    SERVERINFO_BACK0,
    SERVERINFO_BACK1,
    NULL
}
Definition at line 30 of file ui_serverinfo.c.
Referenced by ServerInfo_Cache().