ZEQ2-Lite: Source/Game/Game/g_local.h File Reference
g_local.h File Reference
#include "../../Shared/q_shared.h"
#include "bg_public.h"
#include "bg_userweapons.h"
#include "g_userweapons.h"
#include "g_tiers.h"
#include "g_public.h"
#include "g_team.h"
Data Structures
struct clientPersistant_t
struct clientSession_t
struct gclient_t
struct gentity_t
struct level_locals_t
struct playerTeamState_t
Macros
#define BODY_QUEUE_SIZE 8
#define CARNAGE_REWARD_TIME 3000
#define DAMAGE_RADIUS 0x00000001
#define FL_FORCE_GESTURE 0x00000400
#define FL_NO_KNOCKBACK 0x00000020
#define FL_TEAMSLAVE 0x00000010
#define FOFS(x) ((size_t)&(((gentity_t *)0)->x))
#define FOLLOW_ACTIVE1 -1
#define FOLLOW_ACTIVE2 -2
#define FRAMETIME 100
#define GAMEVERSION BASEGAME
#define INFINITE 1000000
#define INTERMISSION_DELAY_TIME 1000
#define MAX_NETNAME 36
#define MAX_SPAWN_VARS 64
#define MAX_SPAWN_VARS_CHARS 4096
#define MAX_VOTE_COUNT 3
#define MISSILE_PRESTEP_TIME 50
#define REWARD_SPRITE_TIME 2000
#define SP_INTERMISSION_DELAY_TIME 5000
#define SP_PODIUM_MODEL "models/mapobjects/podium/podium4.md3"
Enumerations
enum clientConnected_t { CON_DISCONNECTED, CON_CONNECTING, CON_CONNECTED }
enum moverState_t { MOVER_POS1, MOVER_POS2, MOVER_1TO2, MOVER_2TO1 }
enum playerTeamStateState_t { TEAM_BEGIN, TEAM_ACTIVE }
enum spectatorState_t { SPECTATOR_NOT, SPECTATOR_FREE, SPECTATOR_FOLLOW, SPECTATOR_SCOREBOARD }
Functions
void AddRemap (const char *oldShader, const char *newShader, float timeOffset)
void AddTournamentQueue (gclient_t *client)
void BeginIntermission (void)
void body_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage)
void BroadcastTeamChange (gclient_t *client, int oldTeam)
const char * BuildShaderStateConfig (void)
void CalcMuzzlePoint (gentity_t *ent, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
void CalculateRanks (void)
qboolean CanDamage (gentity_t *targ, vec3_t origin)
qboolean CheckGauntletAttack (gentity_t *ent)
qboolean CheckObeliskAttack (gentity_t *obelisk, gentity_t *attacker)
void CheckTeamLeader (int team)
void checkTier (gclient_t *client)
g_tiers.c
void ClientBegin (int clientNum)
void ClientCommand (int clientNum)
char * ClientConnect (int clientNum, qboolean firstTime)
void ClientDisconnect (int clientNum)
void ClientEndFrame (gentity_t *ent)
void ClientRespawn (gentity_t *ent)
void ClientSpawn (gentity_t *ent)
void ClientThink (int clientNum)
void ClientUserinfoChanged (int clientNum)
void Cmd_FollowCycle_f (gentity_t *ent, int dir)
void Cmd_Score_f (gentity_t *ent)
qboolean ConsoleCommand (void)
void CopyToBodyQue (gentity_t *ent)
void DeathmatchScoreboardMessage (gentity_t *client)
void FindIntermissionPoint (void)
gentity_t * fire_bfg (gentity_t *self, vec3_t start, vec3_t dir)
gentity_t * fire_grapple (gentity_t *self, vec3_t start, vec3_t dir)
gentity_t * fire_grenade (gentity_t *self, vec3_t start, vec3_t aimdir)
gentity_t * fire_plasma (gentity_t *self, vec3_t start, vec3_t aimdir)
gentity_t * fire_rocket (gentity_t *self, vec3_t start, vec3_t dir)
void Fire_UserWeapon (gentity_t *self, vec3_t start, vec3_t dir, qboolean altfire)
void FireWeapon (gentity_t *ent, qboolean altfire)
void QDECL void QDECL format (printf, 1, 2)))
void G_AddEvent (gentity_t *ent, int event, int eventParm)
void G_AddPredictableEvent (gentity_t *ent, int event, int eventParm)
void * G_Alloc (int size)
void G_CheckSkills (playerState_t *ps)
g_userweapons.c
void G_Damage (gentity_t *targ, gentity_t *inflictor, gentity_t *attacker, vec3_t dir, vec3_t point, int damage, int dflags, int mod)
void G_DetachUserWeapon (gentity_t *self)
void G_DieUserWeapon (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, int mod)
qboolean G_EntitiesFree (void)
void QDECL void QDECL G_Error (const char *fmt,...) __attribute__((noreturn
void G_ExplodeMissile (gentity_t *ent)
void G_ExplodeUserWeapon (gentity_t *self)
qboolean G_FilterPacket (char *from)
gentity_t * G_Find (gentity_t *from, int fieldofs, const char *match)
void G_FreeEntity (gentity_t *e)
void G_GetMuzzleSettings (vec3_t muzzle_g, vec3_t forward_g, vec3_t right_g, vec3_t up_g)
void G_InitGentity (gentity_t *e)
void G_InitMemory (void)
void G_InitSessionData (gclient_t *client, char *userinfo)
void G_InitWorldSession (void)
int G_InvulnerabilityEffect (gentity_t *targ, vec3_t dir, vec3_t point, vec3_t impactpoint, vec3_t bouncedir)
void G_KillBox (gentity_t *ent)
void QDECL G_LogPrintf (const char *fmt,...) __attribute__((format(printf
int G_ModelIndex (char *name)
char * G_NewString (const char *string)
gentity_t * G_PickTarget (char *targetname)
void QDECL G_Printf (const char *fmt,...) __attribute__((format(printf
void G_ProcessIPBans (void)
void G_RadarUpdateCS (void)
qboolean G_RadiusDamage (vec3_t origin, gentity_t *attacker, float damage, float radius, gentity_t *ignore, int mod)
void G_ReadSessionData (gclient_t *client)
void G_RemoveUserWeapon (gentity_t *self)
void G_RunClient (gentity_t *ent)
void G_RunMissile (gentity_t *ent)
void G_RunMover (gentity_t *ent)
void G_RunRiftWeaponClass (gentity_t *ent)
void G_RunThink (gentity_t *ent)
void G_RunUserExplosion (gentity_t *ent)
void G_RunUserMissile (gentity_t *ent)
void G_SetMovedir (vec3_t angles, vec3_t movedir)
void G_SetOrigin (gentity_t *ent, vec3_t origin)
void G_SetStats (gentity_t *ent)
void G_Sound (gentity_t *ent, int channel, int soundIndex)
int G_SoundIndex (char *name)
gentity_t * G_Spawn (void)
void G_SpawnEntitiesFromString (void)
qboolean G_SpawnFloat (const char *key, const char *defaultString, float *out)
qboolean G_SpawnInt (const char *key, const char *defaultString, int *out)
qboolean G_SpawnString (const char *key, const char *defaultString, char **out)
qboolean G_SpawnVector (const char *key, const char *defaultString, float *out)
void G_TeamCommand (team_t team, char *cmd)
gentity_t * G_TempEntity (vec3_t origin, int event)
void G_TouchSolids (gentity_t *ent)
void G_TouchTriggers (gentity_t *ent)
void G_UseTargets (gentity_t *ent, gentity_t *activator)
qboolean G_weapPhys_Parse (char *filename, int clientNum)
qboolean G_weapPhysParser_MainParse (char *filename, int clientNum, int *weaponMask)
void G_WriteSessionData (void)
void InitBodyQue (void)
void InitClientPersistant (gclient_t *client)
void InitClientResp (gclient_t *client)
void MoveClientToIntermission (gentity_t *client)
qboolean OnSameTeam (gentity_t *ent1, gentity_t *ent2)
team_t PickTeam (int ignoreClientNum)
void Release_UserWeapon (gentity_t *self, qboolean altfire)
gentity_t * SelectSpawnPoint (vec3_t avoidPoint, vec3_t origin, vec3_t angles)
void QDECL void SendScoreboardMessageToAllClients (void)
void SetClientViewAngle (gentity_t *ent, vec3_t angle)
void SetLeader (int team, int client)
void SetTargetPos (gentity_t *ent)
void SetTeam (gentity_t *ent, char *s)
void setupTiers (gclient_t *client)
void SnapVectorTowards (vec3_t v, vec3_t to)
void SpawnModelsOnVictoryPads (void)
qboolean SpotWouldTelefrag (gentity_t *spot)
void StopFollowing (gentity_t *ent)
void Svcmd_AbortPodium_f (void)
void Svcmd_GameMem_f (void)
void syncTier (gclient_t *client)
void Team_CheckDroppedItem (gentity_t *dropped)
team_t TeamCount (int ignoreClientNum, int team)
int TeamLeader (int team)
void TeleportPlayer (gentity_t *player, vec3_t origin, vec3_t angles)
void Touch_DoorTrigger (gentity_t *ent, gentity_t *other, trace_t *trace)
void trap_AdjustAreaPortalState (gentity_t *ent, qboolean open)
qboolean trap_AreasConnected (int area1, int area2)
int trap_Argc (void)
void trap_Args (char *buffer, int bufferLength)
void trap_Argv (int n, char *buffer, int bufferLength)
void trap_Cvar_Register (vmCvar_t *cvar, const char *var_name, const char *value, int flags)
void trap_Cvar_Set (const char *var_name, const char *value)
void trap_Cvar_Update (vmCvar_t *cvar)
int trap_Cvar_VariableIntegerValue (const char *var_name)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
float trap_Cvar_VariableValue (const char *var_name)
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
void trap_DebugPolygonDelete (int id)
void trap_DropClient (int clientNum, const char *reason)
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int *entityList, int maxcount)
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
void trap_Error (const char *fmt) __attribute__((noreturn))
void trap_FS_FCloseFile (fileHandle_t f)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
void trap_GetConfigstring (int num, char *buffer, int bufferSize)
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
void trap_GetServerinfo (char *buffer, int bufferSize)
void trap_GetUsercmd (int clientNum, usercmd_t *cmd)
void trap_GetUserinfo (int num, char *buffer, int bufferSize)
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
void trap_LinkEntity (gentity_t *ent)
void trap_LocateGameData (gentity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *gameClients, int sizeofGameClient)
int trap_Milliseconds (void)
int trap_PointContents (const vec3_t point, int passEntityNum)
void trap_Printf (const char *fmt)
int trap_RealTime (qtime_t *qtime)
void trap_SendConsoleCommand (int exec_when, const char *text)
void trap_SendServerCommand (int clientNum, const char *text)
void trap_SetBrushModel (gentity_t *ent, const char *name)
void trap_SetConfigstring (int num, const char *string)
void trap_SetUserinfo (int num, const char *buffer)
void trap_SnapVector (float *v)
void trap_Trace (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
void trap_UnlinkEntity (gentity_t *ent)
void trigger_teleporter_touch (gentity_t *self, gentity_t *other, trace_t *trace)
float * tv (float x, float y, float z)
void UpdateTournamentInfo (void)
float vectoyaw (const vec3_t vec)
char * vtos (const vec3_t v)
void Weapon_HookFree (gentity_t *ent)
void Weapon_HookThink (gentity_t *ent)
Variables
vmCvar_t g_allowAdvancedMelee
vmCvar_t g_allowBallFlip
vmCvar_t g_allowBlock
vmCvar_t g_allowBoost
vmCvar_t g_allowBreakLimit
vmCvar_t g_allowFly
vmCvar_t g_allowJump
vmCvar_t g_allowLockon
vmCvar_t g_allowMelee
vmCvar_t g_allowOverheal
vmCvar_t g_allowScoreboard
vmCvar_t g_allowSoar
vmCvar_t g_allowTiers
vmCvar_t g_allowVote
vmCvar_t g_allowZanzoken
vmCvar_t g_banIPs
vmCvar_t g_breakLimitRate
vmCvar_t g_cheats
vmCvar_t g_debugAlloc
vmCvar_t g_debugDamage
vmCvar_t g_debugMove
vmCvar_t g_dedicated
vmCvar_t g_dmflags
vmCvar_t g_doWarmup
vmCvar_t g_enableBreath
vmCvar_t g_enableDust
gentity_t g_entities [MAX_GENTITIES]
vmCvar_t g_filterBan
vmCvar_t g_forcerespawn
vmCvar_t g_fraglimit
vmCvar_t g_friendlyFire
vmCvar_t g_gametype
vmCvar_t g_inactivity
vmCvar_t g_knockback
vmCvar_t g_maxclients
vmCvar_t g_maxGameClients
vmCvar_t g_motd
vmCvar_t g_needpass
vmCvar_t g_password
vmCvar_t g_pointGravity
vmCvar_t g_powerlevel
vmCvar_t g_powerlevelMaximum
vmCvar_t g_proxMineTimeout
vmCvar_t g_quickTransformCost
vmCvar_t g_quickTransformCostPerTier
vmCvar_t g_quickZanzokenCost
vmCvar_t g_quickZanzokenDistance
vmCvar_t g_rankings
vmCvar_t g_restarted
vmCvar_t g_rolling
vmCvar_t g_running
vmCvar_t g_singlePlayer
vmCvar_t g_smoothClients
vmCvar_t g_synchronousClients
vmCvar_t g_teamAutoJoin
vmCvar_t g_teamForceBalance
vmCvar_t g_timelimit
vmCvar_t g_verboseParse
vmCvar_t g_warmup
level_locals_t level
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
Macro Definition Documentation
BODY_QUEUE_SIZE
#define BODY_QUEUE_SIZE 8
Definition at line 38 of file g_local.h.
CARNAGE_REWARD_TIME
#define CARNAGE_REWARD_TIME 3000
Definition at line 43 of file g_local.h.
DAMAGE_RADIUS
#define DAMAGE_RADIUS 0x00000001
Definition at line 489 of file g_local.h.
FL_FORCE_GESTURE
#define FL_FORCE_GESTURE 0x00000400
Definition at line 53 of file g_local.h.
FL_NO_KNOCKBACK
#define FL_NO_KNOCKBACK 0x00000020
Definition at line 52 of file g_local.h.
FL_TEAMSLAVE
#define FL_TEAMSLAVE 0x00000010
Definition at line 51 of file g_local.h.
FOFS
#define FOFS (x) ((size_t)&(((gentity_t *)0)->x))
Definition at line 687 of file g_local.h.
FOLLOW_ACTIVE1
#define FOLLOW_ACTIVE1 -1
Definition at line 247 of file g_local.h.
FOLLOW_ACTIVE2
#define FOLLOW_ACTIVE2 -2
Definition at line 248 of file g_local.h.
FRAMETIME
#define FRAMETIME 100
Definition at line 42 of file g_local.h.
GAMEVERSION
#define GAMEVERSION BASEGAME
Definition at line 36 of file g_local.h.
INFINITE
#define INFINITE 1000000
Definition at line 40 of file g_local.h.
INTERMISSION_DELAY_TIME
#define INTERMISSION_DELAY_TIME 1000
Definition at line 46 of file g_local.h.
MAX_NETNAME
#define MAX_NETNAME 36
Definition at line 264 of file g_local.h.
MAX_SPAWN_VARS
#define MAX_SPAWN_VARS 64
Definition at line 346 of file g_local.h.
MAX_SPAWN_VARS_CHARS
#define MAX_SPAWN_VARS_CHARS 4096
Definition at line 347 of file g_local.h.
MAX_VOTE_COUNT
#define MAX_VOTE_COUNT 3
Definition at line 265 of file g_local.h.
MISSILE_PRESTEP_TIME
#define MISSILE_PRESTEP_TIME 50
Definition at line 48 of file g_local.h.
REWARD_SPRITE_TIME
#define REWARD_SPRITE_TIME 2000
Definition at line 44 of file g_local.h.
SP_INTERMISSION_DELAY_TIME
#define SP_INTERMISSION_DELAY_TIME 5000
Definition at line 47 of file g_local.h.
SP_PODIUM_MODEL
#define SP_PODIUM_MODEL "models/mapobjects/podium/podium4.md3"
Definition at line 63 of file g_local.h.
Enumeration Type Documentation
clientConnected_t
enum clientConnected_t
Enumerator
CON_DISCONNECTED
CON_CONNECTING
CON_CONNECTED
Definition at line 210 of file g_local.h.
              {
     CON_DISCONNECTED,
     CON_CONNECTING,
     CON_CONNECTED
 } clientConnected_t;
moverState_t
enum moverState_t
Enumerator
MOVER_POS1
MOVER_POS2
MOVER_1TO2
MOVER_2TO1
Definition at line 56 of file g_local.h.
              {
     MOVER_POS1,
     MOVER_POS2,
     MOVER_1TO2,
     MOVER_2TO1
 } moverState_t;
playerTeamStateState_t
enum playerTeamStateState_t
Enumerator
TEAM_BEGIN
TEAM_ACTIVE
Definition at line 223 of file g_local.h.
              {
     TEAM_BEGIN,     // Beginning a team game, spawn at base
     TEAM_ACTIVE     // Now actively playing
 } playerTeamStateState_t;
spectatorState_t
enum spectatorState_t
Enumerator
SPECTATOR_NOT
SPECTATOR_FREE
SPECTATOR_FOLLOW
SPECTATOR_SCOREBOARD
Definition at line 216 of file g_local.h.
              {
     SPECTATOR_NOT,
     SPECTATOR_FREE,
     SPECTATOR_FOLLOW,
     SPECTATOR_SCOREBOARD
 } spectatorState_t;
Function Documentation
AddRemap()
void AddRemap (const char * oldShader, const char * newShader, float timeOffset)
Definition at line 38 of file g_utils.c.
{
     int i;
     for (i = 0; i < remapCount; i++) {
         if (Q_stricmp(oldShader, remappedShaders[i].oldShader) == 0) {
             // found it, just update this one
             strcpy(remappedShaders[i].newShader,newShader);
             remappedShaders[i].timeOffset = timeOffset;
             return;
         }
     }
     if (remapCount < MAX_SHADER_REMAPS) {
         strcpy(remappedShaders[remapCount].newShader,newShader);
         strcpy(remappedShaders[remapCount].oldShader,oldShader);
         remappedShaders[remapCount].timeOffset = timeOffset;
         remapCount++;
     }
 }
References MAX_SHADER_REMAPS, Q_stricmp(), remapCount, remappedShaders, and shaderRemap_t::timeOffset.
Referenced by G_UseTargets().
AddTournamentQueue()
void AddTournamentQueue (gclient_t * client)
Definition at line 610 of file g_main.c.
 {
     int index;
     gclient_t *curclient;
     for(index = 0; index < level.maxclients; index++)
     {
         curclient = &level.clients[index];
         if(curclient->pers.connected != CON_DISCONNECTED)
         {
             if(curclient == client)
                 curclient->sess.spectatorNum = 0;
             else if(curclient->sess.sessionTeam == TEAM_SPECTATOR)
                 curclient->sess.spectatorNum++;
         }
     }
 }
References CON_DISCONNECTED, and TEAM_SPECTATOR.
Referenced by G_InitSessionData(), and SetTeam().
BeginIntermission()
void BeginIntermission (void)
Definition at line 905 of file g_main.c.
{
     int         i;
     gentity_t   *client;
     if ( level.intermissiontime ) {
         return;     // already active
     }
     // if in tournement mode, change the wins / losses
     if ( g_gametype.integer == GT_TOURNAMENT ) {
         AdjustTournamentScores();
     }
     level.intermissiontime = level.time;
     // move all clients to the intermission point
     for (i=0 ; i< level.maxclients ; i++) {
         client = g_entities + i;
         if (!client->inuse)
             continue;
         // respawn if dead
         if (client->powerLevelTotal <= 0) {
             ClientRespawn(client);
         }
         MoveClientToIntermission( client );
     }
     // if single player game
     if ( g_gametype.integer == GT_SINGLE_PLAYER ) {
         UpdateTournamentInfo();
         SpawnModelsOnVictoryPads();
     }
     // send the current scoring to all clients
     SendScoreboardMessageToAllClients();
 }
References AdjustTournamentScores(), ClientRespawn(), g_entities, g_gametype, GT_SINGLE_PLAYER, GT_TOURNAMENT, vmCvar_t::integer, MoveClientToIntermission(), SendScoreboardMessageToAllClients(), SpawnModelsOnVictoryPads(), and UpdateTournamentInfo().
Referenced by Cmd_LevelShot_f().
body_die()
void body_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage)
BroadcastTeamChange()
void BroadcastTeamChange (gclient_t * client, int oldTeam)
Definition at line 217 of file g_cmds.c.
 {
     if ( client->sess.sessionTeam == TEAM_RED ) {
         trap_SendServerCommand( -1, va("cp \"%s" S_COLOR_WHITE " joined the red team.\n\"",
             client->pers.netname) );
     } else if ( client->sess.sessionTeam == TEAM_BLUE ) {
         trap_SendServerCommand( -1, va("cp \"%s" S_COLOR_WHITE " joined the blue team.\n\"",
         client->pers.netname));
     } else if ( client->sess.sessionTeam == TEAM_SPECTATOR && oldTeam != TEAM_SPECTATOR ) {
         trap_SendServerCommand( -1, va("cp \"%s" S_COLOR_WHITE " joined the spectators.\n\"",
         client->pers.netname));
     } else if ( client->sess.sessionTeam == TEAM_FREE ) {
         trap_SendServerCommand( -1, va("cp \"%s" S_COLOR_WHITE " joined the battle.\n\"",
         client->pers.netname));
     }
 }
References S_COLOR_WHITE, TEAM_BLUE, TEAM_FREE, TEAM_RED, TEAM_SPECTATOR, trap_SendServerCommand(), and va().
Referenced by ClientConnect(), G_InitSessionData(), and SetTeam().
BuildShaderStateConfig()
const char* BuildShaderStateConfig (void)
Definition at line 57 of file g_utils.c.
{
     static char buff[MAX_STRING_CHARS*4];
     char out[(MAX_QPATH * 2) + 5];
     int i;
     memset(buff, 0, MAX_STRING_CHARS);
     for (i = 0; i < remapCount; i++) {
         Com_sprintf(out, (MAX_QPATH * 2) + 5, "%s=%s:%5.2f@", remappedShaders[i].oldShader, remappedShaders[i].newShader, remappedShaders[i].timeOffset);
         Q_strcat( buff, sizeof( buff ), out);
     }
     return buff;
 }
References Com_sprintf(), MAX_QPATH, MAX_STRING_CHARS, out, Q_strcat(), remapCount, and remappedShaders.
Referenced by G_UseTargets().
CalcMuzzlePoint()
void CalcMuzzlePoint (gentity_t * ent, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
Definition at line 70 of file g_weapon.c.
{
     VectorCopy(ent->s.pos.trBase,muzzlePoint);
     //FIXME: Old Q3A style adding to the vertical component will no longer work because of
     //       the barrel rolling,switched to a vectorMA function.
     //muzzlePoint[2] += ent->client->ps.viewheight;
     VectorMA(muzzlePoint,ent->client->ps.viewheight,up,muzzlePoint);
     VectorMA(muzzlePoint,14,forward,muzzlePoint);
     // snap to integer coordinates for more efficient network bandwidth usage
     SnapVector(muzzlePoint);
 }
References forward, SnapVector, up, VectorCopy, and VectorMA().
Referenced by G_PushUserMissile(), G_RunUserMissile(), and Think_Guided().
CalculateRanks()
void CalculateRanks (void)
Definition at line 764 of file g_main.c.
{
     int     i;
     int     rank;
     int     score;
     int     newScore;
     gclient_t   *cl;
     level.follow1 = -1;
     level.follow2 = -1;
     level.numConnectedClients = 0;
     level.numNonSpectatorClients = 0;
     level.numPlayingClients = 0;
     level.numVotingClients = 0;     // don't count bots
     for (i = 0; i < ARRAY_LEN(level.numteamVotingClients); i++)
         level.numteamVotingClients[i] = 0;
     qsort( level.sortedClients, level.numConnectedClients,
         sizeof(level.sortedClients[0]), SortRanks );
     // set the CS_SCORES1/2 configstrings, which will be visible to everyone
     if ( g_gametype.integer >= GT_TEAM ) {
         trap_SetConfigstring( CS_SCORES1, va("%i", level.teamScores[TEAM_RED] ) );
         trap_SetConfigstring( CS_SCORES2, va("%i", level.teamScores[TEAM_BLUE] ) );
     } else {
         if ( level.numConnectedClients == 0 ) {
             trap_SetConfigstring( CS_SCORES1, va("%i", SCORE_NOT_PRESENT) );
             trap_SetConfigstring( CS_SCORES2, va("%i", SCORE_NOT_PRESENT) );
         } else if ( level.numConnectedClients == 1 ) {
             trap_SetConfigstring( CS_SCORES1, va("%i", level.clients[ level.sortedClients[0] ].ps.persistant[PERS_SCORE] ) );
             trap_SetConfigstring( CS_SCORES2, va("%i", SCORE_NOT_PRESENT) );
         } else {
             trap_SetConfigstring( CS_SCORES1, va("%i", level.clients[ level.sortedClients[0] ].ps.persistant[PERS_SCORE] ) );
             trap_SetConfigstring( CS_SCORES2, va("%i", level.clients[ level.sortedClients[1] ].ps.persistant[PERS_SCORE] ) );
         }
     }
     // see if it is time to end the level
     CheckExitRules();
     // if we are at the intermission, send the new info to everyone
     if ( level.intermissiontime ) {
         SendScoreboardMessageToAllClients();
     }
 }
References ARRAY_LEN, CheckExitRules(), cl, CS_SCORES1, CS_SCORES2, g_gametype, GT_TEAM, vmCvar_t::integer, PERS_SCORE, SCORE_NOT_PRESENT, SendScoreboardMessageToAllClients(), SortRanks(), TEAM_BLUE, TEAM_RED, trap_SetConfigstring(), and va().
Referenced by ClientBegin(), ClientConnect(), ClientDisconnect(), and UpdateTournamentInfo().
CanDamage()
qboolean CanDamage (gentity_t * targ, vec3_t origin)
Definition at line 50 of file g_combat.c.
{
     vec3_t  dest;
     trace_t tr;
     vec3_t  midpoint;
     VectorAdd (targ->r.absmin, targ->r.absmax, midpoint);
     VectorScale (midpoint, 0.5, midpoint);
     VectorCopy (midpoint, dest);
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0 || tr.entityNum == targ->s.number)
         return qtrue;
     VectorCopy (midpoint, dest);
     dest[0] += 15.0;
     dest[1] += 15.0;
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy (midpoint, dest);
     dest[0] += 15.0;
     dest[1] -= 15.0;
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy (midpoint, dest);
     dest[0] -= 15.0;
     dest[1] += 15.0;
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy (midpoint, dest);
     dest[0] -= 15.0;
     dest[1] -= 15.0;
     trap_Trace ( &tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     return qfalse;
 }
References ENTITYNUM_NONE, MASK_SOLID, qfalse, qtrue, tr, trap_Trace(), vec3_origin, VectorAdd, VectorCopy, and VectorScale.
Referenced by G_UserRadiusDamage().
CheckGauntletAttack()
qboolean CheckGauntletAttack (gentity_t * ent)
CheckObeliskAttack()
qboolean CheckObeliskAttack (gentity_t * obelisk, gentity_t * attacker)
CheckTeamLeader()
void CheckTeamLeader (int team)
Definition at line 1347 of file g_main.c.
 {}
Referenced by SetTeam().
checkTier()
void checkTier (gclient_t * client)
g_tiers.c
Definition at line 163 of file g_tiers.c.
{
     int trigger;
     int tier = 1;
     int tierUp = -1;
     int tierDown = -1;
     int desiredTier = -1;
     int tierChangeMode = 0;
     playerState_t *ps;
     ps = &client->ps;
     if(ps->timers[tmTransform]){return;}
     while(client->tiers[tier].exists){
         if(client->tiers[tier].requirementUseSkill && (ps->weapon == client->tiers[tier].requirementUseSkill)){
             trigger = tier;
             break;
         }
         ++tier;
     }
     desiredTier = ps->powerLevel[plTierDesired];
     tier = ps->powerLevel[plTierCurrent];
     if(checkDefaultTierConfiguration(ps)) { return; }
     ps->powerLevel[plTierChanged] = 0;
     if(ps->stats[stTransformState] != 0) {
         ps->powerLevel[plTierChanged] = 1;
     }
     else if(desiredTier == tier || ps->powerLevel[plTierSelectionMode] < 3) {
         tierChangeMode = ps->powerLevel[plTierSelectionMode];
         if(tierChangeMode == 3) { tierChangeMode = 0; }
         if(ps->bitFlags & keyTierUp) { tierChangeMode = 2; }
         if(ps->bitFlags & keyTierDown) { tierChangeMode = 1; }
         tierUp = tier + 1;
         tierDown = tier - 1;
     }
     else if(!client->tiers[desiredTier].exists) {
          ps->powerLevel[plTierDesired] = -1;
          ps->powerLevel[plTierSelectionMode]=0;
          ps->powerLevel[plTierChanged] = 1;
         return;
     }
     else if(ps->powerLevel[plTierSelectionMode] == 3) {
         ps->powerLevel[plTierSelectionMode] = 0;
         if( desiredTier > tier ) {
             if(desiredTier > ps->powerLevel[plTierTotal]+1) {
                 ps->powerLevel[plTierDesired] = tier;
                 return;
             }
             tierUp = desiredTier;
         }
         else if (desiredTier < tier) { tierDown = desiredTier; }
         tierChangeMode = 3;
     }
     if(!checkTierUpTransformation(client,tierUp,tier,tierChangeMode)) { checkTierDownTransformation(client,tierDown,tier,tierChangeMode); }
     ps->powerLevel[plTierSelectionMode]=0;
 }
References checkDefaultTierConfiguration(), checkTierDownTransformation(), checkTierUpTransformation(), keyTierDown, keyTierUp, plTierChanged, plTierCurrent, plTierDesired, plTierSelectionMode, plTierTotal, stTransformState, and tmTransform.
Referenced by ClientThink_real().
ClientBegin()
void ClientBegin (int clientNum)
Definition at line 820 of file g_client.c.
{
     gentity_t   *ent;
     gclient_t   *client;
     gentity_t   *tent;
     int         flags;
     ent = g_entities + clientNum;
     client = level.clients + clientNum;
     if ( ent->r.linked ) {
         trap_UnlinkEntity( ent );
     }
     G_InitGentity( ent );
     ent->touch = 0;
     ent->pain = 0;
     ent->client = client;
     client->pers.connected = CON_CONNECTED;
     client->pers.enterTime = level.time;
     client->pers.teamState.state = TEAM_BEGIN;
     // save eflags around this, because changing teams will
     // cause this to happen with a valid entity, and we
     // want to make sure the teleport bit is set right
     // so the viewpoint doesn't interpolate through the
     // world to the new position
     flags = client->ps.eFlags;
     memset( &client->ps, 0, sizeof( client->ps ) );
     client->ps.eFlags = flags;
     // ADDING FOR ZEQ2
     // Set the starting cap
     ClientUserinfoChanged(clientNum);
     client->ps.powerLevel[plMaximum] = g_powerlevel.value;
     client->ps.powerLevel[plHealthPool] = client->ps.powerLevel[plMaximumPool] = client->ps.powerLevel[plMaximum] / 3;
     client->ps.powerLevel[plLimit] = g_powerlevelMaximum.value;
     client->ps.bitFlags |= isUnsafe;
     // END ADDING
     // locate ent at a spawn point
     ClientSpawn( ent );
     if ( client->sess.sessionTeam != TEAM_SPECTATOR ) {
         // send event
         tent = G_TempEntity( ent->client->ps.origin, EV_PLAYER_TELEPORT_IN );
         tent->s.clientNum = ent->s.clientNum;
         if ( g_gametype.integer != GT_TOURNAMENT  ) {
             trap_SendServerCommand( -1, va("print \"%s" S_COLOR_WHITE " entered the game\n\"", client->pers.netname) );
         }
     }
     G_LogPrintf( "ClientBegin: %i\n", clientNum );
     // count current clients and rank for scoreboard
     CalculateRanks();
 }
References CalculateRanks(), ClientSpawn(), ClientUserinfoChanged(), CON_CONNECTED, EV_PLAYER_TELEPORT_IN, g_entities, g_gametype, G_InitGentity(), G_LogPrintf(), g_powerlevel, g_powerlevelMaximum, G_TempEntity(), GT_TOURNAMENT, vmCvar_t::integer, isUnsafe, plHealthPool, plLimit, plMaximum, plMaximumPool, S_COLOR_WHITE, TEAM_BEGIN, TEAM_SPECTATOR, trap_SendServerCommand(), trap_UnlinkEntity(), va(), and vmCvar_t::value.
Referenced by SetTeam(), SpectatorClientEndFrame(), and vmMain().
ClientCommand()
void ClientCommand (int clientNum)
Definition at line 1267 of file g_cmds.c.
{
     gentity_t *ent;
     char    cmd[MAX_TOKEN_CHARS];
     ent = g_entities + clientNum;
     if ( !ent->client ) {
         return;     // not fully in game yet
     }
     trap_Argv( 0, cmd, sizeof( cmd ) );
     if (Q_stricmp (cmd, "say") == 0) {
         Cmd_Say_f (ent, SAY_ALL, qfalse);
         return;
     }
     if (Q_stricmp (cmd, "say_team") == 0) {
         Cmd_Say_f (ent, SAY_TEAM, qfalse);
         return;
     }
     if (Q_stricmp (cmd, "tell") == 0) {
         Cmd_Tell_f ( ent );
         return;
     }
     if (Q_stricmp (cmd, "vsay") == 0) {
         Cmd_Voice_f (ent, SAY_ALL, qfalse, qfalse);
         return;
     }
     if (Q_stricmp (cmd, "vsay_team") == 0) {
         Cmd_Voice_f (ent, SAY_TEAM, qfalse, qfalse);
         return;
     }
     if (Q_stricmp (cmd, "vtell") == 0) {
         Cmd_VoiceTell_f ( ent, qfalse );
         return;
     }
     if (Q_stricmp (cmd, "vosay") == 0) {
         Cmd_Voice_f (ent, SAY_ALL, qfalse, qtrue);
         return;
     }
     if (Q_stricmp (cmd, "vosay_team") == 0) {
         Cmd_Voice_f (ent, SAY_TEAM, qfalse, qtrue);
         return;
     }
     if (Q_stricmp (cmd, "votell") == 0) {
         Cmd_VoiceTell_f ( ent, qtrue );
         return;
     }
     if (Q_stricmp (cmd, "vtaunt") == 0) {
         Cmd_VoiceTaunt_f ( ent );
         return;
     }
     if (Q_stricmp (cmd, "score") == 0) {
         Cmd_Score_f (ent);
         return;
     }
     // ignore all other commands when at intermission
     if (level.intermissiontime) {
         Cmd_Say_f (ent, qfalse, qtrue);
         return;
     }
     else if (Q_stricmp (cmd, "teamtask") == 0)
         Cmd_TeamTask_f (ent);
     else if (Q_stricmp (cmd, "levelshot") == 0)
         Cmd_LevelShot_f (ent);
     else if (Q_stricmp (cmd, "follow") == 0)
         Cmd_Follow_f (ent);
     else if (Q_stricmp (cmd, "follownext") == 0)
         Cmd_FollowCycle_f (ent, 1);
     else if (Q_stricmp (cmd, "followprev") == 0)
         Cmd_FollowCycle_f (ent, -1);
     else if (Q_stricmp (cmd, "team") == 0)
         Cmd_Team_f (ent);
     else if (Q_stricmp (cmd, "where") == 0)
         Cmd_Where_f (ent);
     else if (Q_stricmp (cmd, "callvote") == 0)
         Cmd_CallVote_f (ent);
     else if (Q_stricmp (cmd, "vote") == 0)
         Cmd_Vote_f (ent);
     else if (Q_stricmp (cmd, "callteamvote") == 0)
         Cmd_CallTeamVote_f (ent);
     else if (Q_stricmp (cmd, "teamvote") == 0)
         Cmd_TeamVote_f (ent);
     else if (Q_stricmp (cmd, "gc") == 0)
         Cmd_GameCommand_f( ent );
     else if (Q_stricmp (cmd, "setviewpos") == 0)
         Cmd_SetViewpos_f( ent );
     else if (Q_stricmp (cmd, "stats") == 0)
         Cmd_Stats_f( ent );
     else
         trap_SendServerCommand( clientNum, va("print \"unknown cmd %s\n\"", cmd ) );
 }
References Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_GameCommand_f(), Cmd_LevelShot_f(), Cmd_Say_f(), Cmd_Score_f(), Cmd_SetViewpos_f(), Cmd_Stats_f(), Cmd_Team_f(), Cmd_TeamTask_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_Voice_f(), Cmd_VoiceTaunt_f(), Cmd_VoiceTell_f(), Cmd_Vote_f(), Cmd_Where_f(), g_entities, MAX_TOKEN_CHARS, Q_stricmp(), qfalse, qtrue, SAY_ALL, SAY_TEAM, trap_Argv(), trap_SendServerCommand(), and va().
Referenced by vmMain().
ClientConnect()
char* ClientConnect (int clientNum, qboolean firstTime)
Definition at line 739 of file g_client.c.
{
     char        *value;
 //  char        *areabits;
     gclient_t   *client;
     char        userinfo[MAX_INFO_STRING];
     gentity_t   *ent;
     ent = &g_entities[ clientNum ];
     trap_GetUserinfo( clientNum, userinfo, sizeof( userinfo ) );
     // IP filtering
     // https://zerowing.idsoftware.com/bugzilla/show_bug.cgi?id=500
     // recommanding PB based IP / GUID banning, the builtin system is pretty limited
     // check to see if they are on the banned IP list
     value = Info_ValueForKey (userinfo, "ip");
     if ( G_FilterPacket( value ) ) {
         return "You are banned from this server.";
     }
   // we don't check password for local client
   // NOTE: local client <-> "ip" "localhost"
   //   this means this client is not running in our current process
     if ((strcmp(value, "localhost") != 0)) {
         // check for a password
         value = Info_ValueForKey (userinfo, "password");
         if ( g_password.string[0] && Q_stricmp( g_password.string, "none" ) &&
             strcmp( g_password.string, value) != 0) {
             return "Invalid password";
         }
     }
     // they can connect
     ent->client = level.clients + clientNum;
     client = ent->client;
 //  areabits = client->areabits;
     memset( client, 0, sizeof(*client) );
     client->pers.connected = CON_CONNECTING;
     // read or initialize the session data
     if ( firstTime || level.newSession ) {
         G_InitSessionData( client, userinfo );
     }
     G_ReadSessionData( client );
     // get and distribute relevent paramters
     G_LogPrintf( "ClientConnect: %i\n", clientNum );
     ClientUserinfoChanged( clientNum );
     // don't do the "xxx connected" messages if they were caried over from previous level
     if ( firstTime ) {
         trap_SendServerCommand( -1, va("print \"%s" S_COLOR_WHITE " connected\n\"", client->pers.netname) );
     }
     if ( g_gametype.integer >= GT_TEAM &&
         client->sess.sessionTeam != TEAM_SPECTATOR ) {
         BroadcastTeamChange( client, -1 );
     }
     // count current clients and rank for scoreboard
     CalculateRanks();
     // for statistics
 //  client->areabits = areabits;
 //  if ( !client->areabits )
 //      client->areabits = G_Alloc( (trap_AAS_PointReachabilityAreaIndex( NULL ) + 7) / 8 );
     return NULL;
 }
References BroadcastTeamChange(), CalculateRanks(), ClientUserinfoChanged(), CON_CONNECTING, g_entities, G_FilterPacket(), g_gametype, G_InitSessionData(), G_LogPrintf(), g_password, G_ReadSessionData(), GT_TEAM, Info_ValueForKey(), vmCvar_t::integer, MAX_INFO_STRING, NULL, Q_stricmp(), S_COLOR_WHITE, vmCvar_t::string, TEAM_SPECTATOR, trap_GetUserinfo(), trap_SendServerCommand(), and va().
Referenced by vmMain().
ClientDisconnect()
void ClientDisconnect (int clientNum)
Definition at line 1075 of file g_client.c.
{
     gentity_t   *ent;
     gentity_t   *tent;
     int         i;
     ent = g_entities + clientNum;
     if ( !ent->client ) {
         return;
     }
     // stop any following clients
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if ( level.clients[i].sess.sessionTeam == TEAM_SPECTATOR
             && level.clients[i].sess.spectatorState == SPECTATOR_FOLLOW
             && level.clients[i].sess.spectatorClient == clientNum ) {
             StopFollowing( &g_entities[i] );
         }
     }
     // send effect if they were completely connected
     if ( ent->client->pers.connected == CON_CONNECTED
         && ent->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         tent = G_TempEntity( ent->client->ps.origin, EV_PLAYER_TELEPORT_OUT );
         tent->s.clientNum = ent->s.clientNum;
         // They don't get to take powerups with them!
         // Especially important for stuff like CTF flags
 }
     G_LogPrintf( "ClientDisconnect: %i\n", clientNum );
     // if we are playing in tourney mode and losing, give a win to the other player
     if ( (g_gametype.integer == GT_TOURNAMENT )
         && !level.intermissiontime
         && !level.warmupTime && level.sortedClients[1] == clientNum ) {
         level.clients[ level.sortedClients[0] ].sess.wins++;
         ClientUserinfoChanged( level.sortedClients[0] );
     }
     if( g_gametype.integer == GT_TOURNAMENT &&
         ent->client->sess.sessionTeam == TEAM_FREE &&
         level.intermissiontime ) {
         trap_SendConsoleCommand( EXEC_APPEND, "map_restart 0\n" );
         level.restarted = qtrue;
         level.changemap = NULL;
         level.intermissiontime = 0;
     }
     trap_UnlinkEntity (ent);
     ent->client->ps.powerLevel[plHealth] = 0;
     ent->s.modelindex = 0;
     ent->r.contents &= ~CONTENTS_BODY;
     ent->inuse = qfalse;
     ent->classname = "disconnected";
     ent->client->pers.connected = CON_DISCONNECTED;
     ent->client->ps.persistant[PERS_TEAM] = TEAM_FREE;
     ent->client->sess.sessionTeam = TEAM_FREE;
     trap_SetConfigstring( CS_PLAYERS + clientNum, "");
     CalculateRanks();
 }
References CalculateRanks(), ClientUserinfoChanged(), CON_CONNECTED, CON_DISCONNECTED, CONTENTS_BODY, CS_PLAYERS, EV_PLAYER_TELEPORT_OUT, EXEC_APPEND, g_entities, g_gametype, G_LogPrintf(), G_TempEntity(), GT_TOURNAMENT, vmCvar_t::integer, NULL, PERS_TEAM, plHealth, qfalse, qtrue, SPECTATOR_FOLLOW, StopFollowing(), TEAM_FREE, TEAM_SPECTATOR, trap_SendConsoleCommand(), trap_SetConfigstring(), and trap_UnlinkEntity().
Referenced by vmMain().
ClientEndFrame()
void ClientEndFrame (gentity_t * ent)
Definition at line 670 of file g_active.c.
{
 //  int         i;
     if ( ent->client->sess.sessionTeam == TEAM_SPECTATOR ) {
         SpectatorClientEndFrame( ent );
         return;
     }
     //
     // If the end of unit layout is displayed, don't give
     // the player any normal movement attributes
     //
     if ( level.intermissiontime ) {
         return;
     }
     // burn from lava, etc
     P_WorldEffects( ent );
     // apply all the damage taken this frame
     P_DamageFeedback( ent );
     // add the EF_CONNECTION flag if we haven't gotten commands recently
     if ( level.time - ent->client->lastCmdTime > 1000 ) {
         ent->s.eFlags |= EF_CONNECTION;
     } else {
         ent->s.eFlags &= ~EF_CONNECTION;
     }
     G_SetClientSound (ent);
     // set the latest infor
     BG_PlayerStateToEntityState( &ent->client->ps, &ent->s, qtrue );
     SendPendingPredictableEvents( &ent->client->ps );
     // set the bit for the reachability area the client is currently in
 //  i = trap_AAS_PointReachabilityAreaIndex( ent->client->ps.origin );
 //  ent->client->areabits[i >> 3] |= 1 << (i & 7);
 }
References BG_PlayerStateToEntityState(), EF_CONNECTION, G_SetClientSound(), P_DamageFeedback(), P_WorldEffects(), qtrue, SendPendingPredictableEvents(), SpectatorClientEndFrame(), and TEAM_SPECTATOR.
Referenced by ClientSpawn(), and G_RunFrame().
ClientRespawn()
void ClientRespawn (gentity_t * ent)
Definition at line 403 of file g_client.c.
{
     gentity_t   *tent;
     CopyToBodyQue (ent);
     ClientSpawn(ent);
     ent->client->ps.powerLevel[plTierCurrent] = 0;
     ent->client->ps.powerLevel[plTierDesired] = 0;
     ent->client->ps.powerLevel[plTierChanged] = 2;
     ent->client->ps.lockonData[lkLastLockedPlayer] = -1;
     // add a teleportation effect
     tent = G_TempEntity( ent->client->ps.origin, EV_PLAYER_TELEPORT_IN );
     tent->s.clientNum = ent->s.clientNum;
 }
References ClientSpawn(), CopyToBodyQue(), EV_PLAYER_TELEPORT_IN, G_TempEntity(), lkLastLockedPlayer, plTierChanged, plTierCurrent, and plTierDesired.
Referenced by BeginIntermission(), ClientThink_real(), and ClientUserinfoChanged().
ClientSpawn()
void ClientSpawn (gentity_t * ent)
Definition at line 885 of file g_client.c.
{
     int     index;
     vec3_t  spawn_origin, spawn_angles;
     gclient_t   *client;
     int     i;
     clientPersistant_t  saved;
     clientSession_t     savedSess;
     int     persistant[MAX_PERSISTANT];
     gentity_t   *spawnPoint;
     gentity_t *tent;
     int     flags;
     int     savedPing;
     int     eventSequence;
     char    model[MAX_QPATH];
     char    userinfo[MAX_INFO_STRING];
     index = ent - g_entities;
     client = ent->client;
     // find a spawn point
     // do it before setting powerLevel back up, so farthest
     // ranging doesn't count this client
     if(client->sess.sessionTeam == TEAM_SPECTATOR){
         spawnPoint = SelectSpectatorSpawnPoint(spawn_origin, spawn_angles);
     }
     else if (g_gametype.integer >= GT_CTF ){
         // all base oriented team games use the CTF spawn points
         spawnPoint = SelectCTFSpawnPoint(client->sess.sessionTeam,client->pers.teamState.state,spawn_origin, spawn_angles);
     }
     else
     {
         // the first spawn should be at a good looking spot
         if ( !client->pers.initialSpawn && client->pers.localClient )
         {
             client->pers.initialSpawn = qtrue;
             spawnPoint = SelectInitialSpawnPoint(spawn_origin, spawn_angles );
         }
         else
         {
             // don't spawn near existing origin if possible
             spawnPoint = SelectSpawnPoint (
                 client->ps.origin,
                 spawn_origin, spawn_angles );
         }
     }
     client->pers.teamState.state = TEAM_ACTIVE;
     // toggle the teleport bit so the client knows to not lerp
     // and never clear the voted flag
     flags = ent->client->ps.eFlags & (EF_TELEPORT_BIT | EF_VOTED | EF_TEAMVOTED);
     flags ^= EF_TELEPORT_BIT;
     // clear everything but the persistant data
     saved = client->pers;
     savedSess = client->sess;
     savedPing = client->ps.ping;
     for ( i = 0 ; i < MAX_PERSISTANT ; i++ ) {
         persistant[i] = client->ps.persistant[i];
     }
     eventSequence = client->ps.eventSequence;
     //memset (client, 0, sizeof(*client)); // bk FIXME: Com_Memset?
     client->pers = saved;
     client->sess = savedSess;
     client->ps.ping = savedPing;
     client->lastkilled_client = -1;
     for ( i = 0 ; i < MAX_PERSISTANT ; i++ ) {
         client->ps.persistant[i] = persistant[i];
     }
     client->ps.eventSequence = eventSequence;
     client->ps.persistant[PERS_SPAWN_COUNT]++;
     client->ps.persistant[PERS_TEAM] = client->sess.sessionTeam;
     client->airOutTime = level.time + 12000;
     trap_GetUserinfo( index, userinfo, sizeof(userinfo) );;
     Q_strncpyz( model, Info_ValueForKey (userinfo, "model"), sizeof( model ) );
     // clear entity values
     client->ps.eFlags = flags;
     ent->s.groundEntityNum = ENTITYNUM_NONE;
     ent->client = &level.clients[index];
     ent->takedamage = qtrue;
     ent->inuse = qtrue;
     ent->classname = "player";
     ent->r.contents = CONTENTS_BODY;
     ent->clipmask = MASK_PLAYERSOLID;
     ent->waterlevel = 0;
     ent->watertype = 0;
     ent->flags = 0;
     VectorCopy (playerMins, ent->r.mins);
     VectorCopy (playerMaxs, ent->r.maxs);
     client->ps.clientNum = index;
     client->ps.stats[stSkills] = *G_FindUserWeaponMask( index );
     client->ps.stats[stChargePercentPrimary] = 0;
     client->ps.stats[stChargePercentSecondary] = 0;
     client->ps.rolling = g_rolling.value;
     client->ps.running = g_running.value;
     if(g_pointGravity.value){client->ps.options |= pointGravity;}
     client->ps.powerLevel[plTierCurrent] = 0;
     client->ps.powerLevel[plTierTotal] = 0;
     client->ps.powerLevel[plTierDesired] = 0;
     client->ps.powerLevel[plTierChanged] = 2;
     client->ps.lockonData[lkLastLockedPlayer] = -1;
     if(g_powerlevel.value > 32767){
         g_powerlevel.value = 32767;
     }
     if(g_powerlevelMaximum.value > 32767){
         g_powerlevelMaximum.value = 32767;
     }
     // make sure all bitFlags are OFF, and explicitly turn off the aura
     client->ps.bitFlags = 0;
     client->ps.eFlags &= ~EF_AURA;
     // END ADDING
     client->ps.powerLevel[plMaximum] = client->ps.powerLevel[plMaximum] > g_powerlevel.value ? client->ps.powerLevel[plMaximum] * 0.75 : g_powerlevel.value;
     client->ps.powerLevel[plHealthPool] = client->ps.powerLevel[plMaximumPool] = client->ps.powerLevel[plMaximum] / 4;
     client->ps.powerLevel[plLimit] = g_powerlevelMaximum.value;
     client->ps.powerLevel[plCurrent] = client->ps.powerLevel[plHealth] = client->ps.powerLevel[plFatigue] = client->ps.powerLevel[plMaximum];
     G_SetOrigin( ent, spawn_origin );
     VectorCopy( spawn_origin, client->ps.origin );
     trap_GetUsercmd( client - level.clients, &ent->client->pers.cmd );
     SetClientViewAngle( ent, spawn_angles );
     if ( ent->client->sess.sessionTeam == TEAM_SPECTATOR ) {
     } else {
         int i;
         G_KillBox( ent );
         trap_LinkEntity (ent);
         // force the best weapon up
         for ( i = MAX_PLAYERWEAPONS; i > 0; i-- ) {
             // We found a valid weapon
             if ( client->ps.stats[stSkills] & (1 << i) ) {
                 break;
             }
         }
         // Either we assign a valid weapon, or we assign 0, which means
         client->ps.weapon = i;
         client->ps.weaponstate = WEAPON_READY;
     }
     // don't allow full run speed for a bit
     client->ps.pm_time = 100;
     client->respawnTime = level.time;
     client->inactivityTime = level.time + g_inactivity.integer * 1000;
     client->latched_buttons = 0;
     // set default animations
     client->ps.torsoAnim = ANIM_IDLE;
     client->ps.legsAnim = ANIM_IDLE;
     if ( level.intermissiontime ) {
         MoveClientToIntermission( ent );
     }
     // run a client frame to drop exactly to the floor,
     // initialize animations and other things
     client->ps.commandTime = level.time - 100;
     ent->client->pers.cmd.serverTime = level.time;
     ClientThink( ent-g_entities );
     // run the presend to set anything else
     ClientEndFrame( ent );
     // clear entity state values
     BG_PlayerStateToEntityState(&client->ps,&ent->s,qtrue);
 }
References ANIM_IDLE, BG_PlayerStateToEntityState(), ClientEndFrame(), ClientThink(), CONTENTS_BODY, EF_AURA, EF_TEAMVOTED, EF_TELEPORT_BIT, EF_VOTED, ENTITYNUM_NONE, g_entities, G_FindUserWeaponMask(), g_gametype, g_inactivity, G_KillBox(), g_pointGravity, g_powerlevel, g_powerlevelMaximum, g_rolling, g_running, G_SetOrigin(), GT_CTF, Info_ValueForKey(), vmCvar_t::integer, lkLastLockedPlayer, MASK_PLAYERSOLID, MAX_INFO_STRING, MAX_PERSISTANT, MAX_PLAYERWEAPONS, MAX_QPATH, MoveClientToIntermission(), PERS_SPAWN_COUNT, PERS_TEAM, playerMaxs, playerMins, plCurrent, plFatigue, plHealth, plHealthPool, plLimit, plMaximum, plMaximumPool, plTierChanged, plTierCurrent, plTierDesired, plTierTotal, pointGravity, Q_strncpyz(), qtrue, SelectCTFSpawnPoint(), SelectInitialSpawnPoint(), SelectSpawnPoint(), SelectSpectatorSpawnPoint(), clientSession_t::sessionTeam, SetClientViewAngle(), stChargePercentPrimary, stChargePercentSecondary, stSkills, TEAM_ACTIVE, TEAM_SPECTATOR, trap_GetUsercmd(), trap_GetUserinfo(), trap_LinkEntity(), vmCvar_t::value, VectorCopy, and WEAPON_READY.
Referenced by ClientBegin(), ClientRespawn(), and G_RankRunFrame().
ClientThink()
void ClientThink (int clientNum)
Definition at line 593 of file g_active.c.
{
     gentity_t *ent;
     ent = g_entities + clientNum;
     trap_GetUsercmd( clientNum, &ent->client->pers.cmd );
     // mark the time we got info, so we can display the
     // phone jack if they don't get any for a while
     ent->client->lastCmdTime = level.time;
     if ( !g_synchronousClients.integer && !ent->client->ps.lockedTarget) {
         ClientThink_real( ent );
     }
 }
References ClientThink_real(), g_entities, g_synchronousClients, vmCvar_t::integer, and trap_GetUsercmd().
Referenced by ClientSpawn(), and vmMain().
ClientUserinfoChanged()
void ClientUserinfoChanged (int clientNum)
Definition at line 586 of file g_client.c.
{
     gentity_t *ent;
     int     teamTask, teamLeader, team, shouldRespawn;
     char    *s;
     char    model[MAX_QPATH];
     char    headModel[MAX_QPATH];
     char    legsModel[MAX_QPATH];
     char    oldname[MAX_STRING_CHARS];
     gclient_t   *client;
     char    userinfo[MAX_INFO_STRING];
     shouldRespawn = 0;
     ent = g_entities + clientNum;
     client = ent->client;
     trap_GetUserinfo( clientNum, userinfo, sizeof( userinfo ) );
     // check for malformed or illegal info strings
     if ( !Info_Validate(userinfo) ) {
         strcpy (userinfo, "\\name\\badinfo");
     }
     // check for local client
     s = Info_ValueForKey( userinfo, "ip" );
     if ( !strcmp( s, "localhost" ) ) {
         client->pers.localClient = qtrue;
     }
     s = Info_ValueForKey(userinfo,"cg_advancedFlight");
     client->ps.options &= ~advancedFlight;
     if(!Q_stricmp(s,"1")){client->ps.options |= advancedFlight;}
     s = Info_ValueForKey(userinfo,"cg_predictItems");
     // set name
     Q_strncpyz ( oldname, client->pers.netname, sizeof( oldname ) );
     s = Info_ValueForKey (userinfo, "name");
     ClientCleanName( s, client->pers.netname, sizeof(client->pers.netname) );
     if ( client->sess.sessionTeam == TEAM_SPECTATOR ) {
         if ( client->sess.spectatorState == SPECTATOR_SCOREBOARD ) {
             Q_strncpyz( client->pers.netname, "scoreboard", sizeof(client->pers.netname) );
         }
     }
     if ( client->pers.connected == CON_CONNECTED ) {
         if ( strcmp( oldname, client->pers.netname ) ) {
             trap_SendServerCommand( -1, va("print \"%s" S_COLOR_WHITE " renamed to %s\n\"", oldname,
                 client->pers.netname) );
         }
     }
     // set model
     Q_strncpyz( model, Info_ValueForKey (userinfo, "model"), sizeof( model ) );
     Q_strncpyz( headModel, Info_ValueForKey (userinfo, "headmodel"), sizeof( headModel ) );
     Q_strncpyz( legsModel, Info_ValueForKey (userinfo, "legsmodel"), sizeof( legsModel ) );
     if(strcmp(model,ent->modelName)){
         if(client->ps.powerLevel[plHealth]>0){shouldRespawn = 1;}
         if(((float)client->ps.powerLevel[plHealth]/(float)client->ps.powerLevel[plMaximum])<0.75){shouldRespawn = 2;}
     }
     Q_strncpyz(ent->modelName,model,sizeof(ent->modelName));
     // set max powerLevel
     client->playerEntity = ent;
     // setup tier information
     client->ps.rolling = g_rolling.value;
     client->ps.running = g_running.value;
     if(g_pointGravity.value){client->ps.options |= pointGravity;}
     // ADDING FOR ZEQ2
     // REFPOINT: Loading the serverside weaponscripts here.
     {
         char    filename[MAX_QPATH];
         char    modelName[MAX_QPATH];
         char    skinName[MAX_QPATH];
         char    modelStr[MAX_QPATH];
         char    *skin;
         int     i;
         Q_strncpyz( modelStr, model, sizeof(modelStr));
         if ( ( skin = strchr( modelStr, '/' ) ) == NULL) {
                 skin = "default";
             } else {
                 *skin++ = 0;
         }
         Q_strncpyz( skinName, skin, sizeof( skinName ) );
         Q_strncpyz( modelName, modelStr, sizeof( modelName ) );
         client->modelName = modelName;
         setupTiers(client);
         Com_sprintf( filename, sizeof( filename ), "players/%s/%s.phys", modelName, skinName );
         if(trap_FS_FOpenFile(filename,0,FS_READ)<=0){
             Com_sprintf( filename, sizeof( filename ), "players/%s/%s.phys", "goku", "default" );
         }
         G_weapPhys_Parse( filename, clientNum );
         // Set the weapon mask here, incase we changed models on the fly.
         // FIXME: Can be removed eventually, when we will disallow on the fly
         //        switching.
         client->ps.stats[stSkills] = *G_FindUserWeaponMask( clientNum );
         // force a new weapon up if the current one is unavailable now.
         // Search downward
         for ( i = MAX_PLAYERWEAPONS; i > 0; i-- ) {
             // We found a valid weapon
             if ( client->ps.stats[stSkills] & (1 << i) ) {
                 break;
             }
         }
         client->ps.weapon = i;
     }
     // END ADDING
     team = client->sess.sessionTeam;
     // team task (0 = none, 1 = offence, 2 = defence)
     teamTask = atoi(Info_ValueForKey(userinfo, "teamtask"));
     // team Leader (1 = leader, 0 is normal player)
     teamLeader = client->sess.teamLeader;
     // send over a subset of the userinfo keys so other clients can
     // print scoreboards, display models, and play custom sounds
     s = va("n\\%s\\t\\%i\\model\\%s\\hmodel\\%s\\lmodel\\%s\\w\\%i\\l\\%i\\tt\\%d\\tl\\%d",
         client->pers.netname, client->sess.sessionTeam, model, headModel, legsModel,
         client->sess.wins, client->sess.losses, teamTask, teamLeader);
     client->ps.powerLevel[plTierCurrent] = 0;
     client->ps.powerLevel[plTierDesired] = 0;
     client->ps.powerLevel[plTierChanged] = 2;
     client->ps.lockonData[lkLastLockedPlayer] = -1;
     trap_SetConfigstring( CS_PLAYERS+clientNum, s );
     if(shouldRespawn==1){ClientRespawn(ent);}
     if(shouldRespawn==2){client->ps.powerLevel[plUseHealth] = 32767;}
     G_LogPrintf( "ClientUserinfoChanged: %i %s\n", clientNum, s );
 }
References advancedFlight, ClientCleanName(), ClientRespawn(), Com_sprintf(), CON_CONNECTED, CS_PLAYERS, FS_READ, g_entities, G_FindUserWeaponMask(), G_LogPrintf(), g_pointGravity, g_rolling, g_running, G_weapPhys_Parse(), Info_Validate(), Info_ValueForKey(), lkLastLockedPlayer, MAX_INFO_STRING, MAX_PLAYERWEAPONS, MAX_QPATH, MAX_STRING_CHARS, NULL, plHealth, plMaximum, plTierChanged, plTierCurrent, plTierDesired, plUseHealth, pointGravity, Q_stricmp(), Q_strncpyz(), qtrue, S_COLOR_WHITE, setupTiers(), SPECTATOR_SCOREBOARD, stSkills, TEAM_SPECTATOR, trap_FS_FOpenFile(), trap_GetUserinfo(), trap_SendServerCommand(), trap_SetConfigstring(), va(), and vmCvar_t::value.
Referenced by AdjustTournamentScores(), ClientBegin(), ClientConnect(), ClientDisconnect(), Cmd_TeamTask_f(), SetLeader(), SetTeam(), and vmMain().
Cmd_FollowCycle_f()
void Cmd_FollowCycle_f (gentity_t * ent, int dir)
Definition at line 474 of file g_cmds.c.
{
     int     clientnum;
     int     original;
     // if they are playing a tournement game, count as a loss
     if ( (g_gametype.integer == GT_TOURNAMENT )
         && ent->client->sess.sessionTeam == TEAM_FREE ) {
         ent->client->sess.losses++;
     }
     // first set them to spectator
     if ( ent->client->sess.spectatorState == SPECTATOR_NOT ) {
         SetTeam( ent, "spectator" );
     }
     if ( dir != 1 && dir != -1 ) {
         G_Error( "Cmd_FollowCycle_f: bad dir %i", dir );
     }
     clientnum = ent->client->sess.spectatorClient;
     original = clientnum;
     do {
         clientnum += dir;
         if ( clientnum >= level.maxclients ) {
             clientnum = 0;
         }
         if ( clientnum < 0 ) {
             clientnum = level.maxclients - 1;
         }
         // can only follow connected clients
         if ( level.clients[ clientnum ].pers.connected != CON_CONNECTED ) {
             continue;
         }
         // can't follow another spectator
         if ( level.clients[ clientnum ].sess.sessionTeam == TEAM_SPECTATOR ) {
             continue;
         }
         // this is good, we can use it
         ent->client->sess.spectatorClient = clientnum;
         ent->client->sess.spectatorState = SPECTATOR_FOLLOW;
         return;
     } while ( clientnum != original );
     // leave it where it was
 }
References CON_CONNECTED, dir, G_Error(), g_gametype, GT_TOURNAMENT, vmCvar_t::integer, SetTeam(), SPECTATOR_FOLLOW, SPECTATOR_NOT, TEAM_FREE, and TEAM_SPECTATOR.
Referenced by ClientCommand(), and SpectatorThink().
Cmd_Score_f()
void Cmd_Score_f (gentity_t * ent)
Definition at line 43 of file g_cmds.c.
{
     DeathmatchScoreboardMessage( ent );
 }
References DeathmatchScoreboardMessage().
Referenced by ClientCommand().
ConsoleCommand()
qboolean ConsoleCommand (void)
Definition at line 461 of file g_svcmds.c.
{
     char    cmd[MAX_TOKEN_CHARS];
     trap_Argv( 0, cmd, sizeof( cmd ) );
     if ( Q_stricmp (cmd, "entitylist") == 0 ) {
         Svcmd_EntityList_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "forceteam") == 0 ) {
         Svcmd_ForceTeam_f();
         return qtrue;
     }
     if (Q_stricmp (cmd, "game_memory") == 0) {
         Svcmd_GameMem_f();
         return qtrue;
     }
     if (Q_stricmp (cmd, "abort_podium") == 0) {
         Svcmd_AbortPodium_f();
         return qtrue;
     }
     if (Q_stricmp (cmd, "addip") == 0) {
         Svcmd_AddIP_f();
         return qtrue;
     }
     if (Q_stricmp (cmd, "addParticle") == 0) {
         Svcmd_AddParticle_f();
         return qtrue;
     }
     if (Q_stricmp (cmd, "removeip") == 0) {
         Svcmd_RemoveIP_f();
         return qtrue;
     }
     if (Q_stricmp (cmd, "listip") == 0) {
         trap_SendConsoleCommand( EXEC_NOW, "g_banIPs\n" );
         return qtrue;
     }
     if (g_dedicated.integer) {
         if (Q_stricmp (cmd, "say") == 0) {
             trap_SendServerCommand( -1, va("print \"server: %s\"", ConcatArgs(1) ) );
             return qtrue;
         }
         // everything else will also be printed as a say command
         trap_SendServerCommand( -1, va("print \"server: %s\"", ConcatArgs(0) ) );
         return qtrue;
     }
     return qfalse;
 }
References ConcatArgs(), EXEC_NOW, g_dedicated, vmCvar_t::integer, MAX_TOKEN_CHARS, Q_stricmp(), qfalse, qtrue, Svcmd_AbortPodium_f(), Svcmd_AddIP_f(), Svcmd_AddParticle_f(), Svcmd_EntityList_f(), Svcmd_ForceTeam_f(), Svcmd_GameMem_f(), Svcmd_RemoveIP_f(), trap_Argv(), trap_SendConsoleCommand(), trap_SendServerCommand(), and va().
Referenced by vmMain().
CopyToBodyQue()
void CopyToBodyQue (gentity_t * ent)
Definition at line 373 of file g_client.c.
 {}
Referenced by ClientRespawn().
DeathmatchScoreboardMessage()
void DeathmatchScoreboardMessage (gentity_t * client)
Definition at line 33 of file g_cmds.c.
 {}
Referenced by Cmd_Score_f(), G_RankRunFrame(), and SendScoreboardMessageToAllClients().
FindIntermissionPoint()
void FindIntermissionPoint (void)
Definition at line 877 of file g_main.c.
{
     gentity_t   *ent, *target;
     vec3_t      dir;
     // find the intermission spot
     ent = G_Find (NULL, FOFS(classname), "info_player_intermission");
     if ( !ent ) {   // the map creator forgot to put in an intermission point...
         SelectSpawnPoint ( vec3_origin, level.intermission_origin, level.intermission_angle );
     } else {
         VectorCopy (ent->s.origin, level.intermission_origin);
         VectorCopy (ent->s.angles, level.intermission_angle);
         // if it has a target, look towards it
         if ( ent->target ) {
             target = G_PickTarget( ent->target );
             if ( target ) {
                 VectorSubtract( target->s.origin, level.intermission_origin, dir );
                 vectoangles( dir, level.intermission_angle );
             }
         }
     }
 }
References dir, FOFS, G_Find(), G_PickTarget(), NULL, SelectSpawnPoint(), vec3_origin, vectoangles(), VectorCopy, and VectorSubtract.
Referenced by MoveClientToIntermission(), and SelectSpectatorSpawnPoint().
fire_bfg()
gentity_t* fire_bfg (gentity_t * self, vec3_t start, vec3_t dir)
fire_grapple()
gentity_t* fire_grapple (gentity_t * self, vec3_t start, vec3_t dir)
fire_grenade()
gentity_t* fire_grenade (gentity_t * self, vec3_t start, vec3_t aimdir)
fire_plasma()
gentity_t* fire_plasma (gentity_t * self, vec3_t start, vec3_t aimdir)
fire_rocket()
gentity_t* fire_rocket (gentity_t * self, vec3_t start, vec3_t dir)
Fire_UserWeapon()
void Fire_UserWeapon (gentity_t * self, vec3_t start, vec3_t dir, qboolean altfire)
Definition at line 671 of file g_usermissile.c.
{
     gentity_t       *bolt;
     g_userWeapon_t  *weaponInfo;
     float powerScale;
     int homingType;
     vec3_t          muzzle, forward, right, up;
     vec3_t          firingDir, firingStart; // <-- Contain the altered aiming and origin vectors.
     powerScale = ((float)self->client->ps.powerLevel[plCurrent] / 1000.0) * self->client->ps.baseStats[stEnergyAttack];
     // Get a hold of the weapon we're firing.
     // If altfire is used and it exists, use altfire, else use regular fire
     // Due to the nature of altfire presence detection, the regular fire must
     // always be loaded first. Since this is only one pointer dereference it is
     // negligable.
     weaponInfo = G_FindUserWeaponData( self->s.clientNum, self->s.weapon );
     if ( ( weaponInfo->general_bitflags & WPF_ALTWEAPONPRESENT ) && altfire ) {
         weaponInfo = G_FindUserAltWeaponData( self->s.clientNum, self->s.weapon );
     }
     // Retrieve the muzzle that was set in g_weapons.c
     G_GetMuzzleSettings(muzzle, forward, right, up);
     // Determine the corrected firing angle and firing origin
     VectorCopy( dir, firingDir);
     if ( weaponInfo->firing_angleW_min || weaponInfo->firing_angleW_max ) {
         vec3_t  temp;
         float   rnd;
         float   firing_angleW;
         rnd = crandom(); // <-- between 0.0f and 1.0f
         firing_angleW = ( 1.0f - rnd ) * weaponInfo->firing_angleW_min + rnd * weaponInfo->firing_angleW_max;
         if ( ( self->client->ps.bitFlags & hasFlipOffset ) && weaponInfo->firing_offsetWFlip ) {
             RotatePointAroundVector( temp, up, firingDir, firing_angleW );
         } else {
             RotatePointAroundVector( temp, up, firingDir, -firing_angleW );
         }
         VectorCopy( temp, firingDir );
     }
     if ( weaponInfo->firing_angleH_min || weaponInfo->firing_angleH_max ) {
         vec3_t temp;
         float   rnd;
         float   firing_angleH;
         rnd = crandom(); // <-- between 0.0f and 1.0f
         firing_angleH = ( 1.0f - rnd ) * weaponInfo->firing_angleH_min + rnd * weaponInfo->firing_angleH_max;
         if ( ( self->client->ps.bitFlags & hasFlipOffset ) && weaponInfo->firing_offsetHFlip ) {
             RotatePointAroundVector( temp, right, firingDir, firing_angleH );
         } else {
             RotatePointAroundVector( temp, right, firingDir, -firing_angleH );
         }
         VectorCopy( temp, firingDir );
     }
     VectorNormalize( firingDir );
     VectorCopy( start, firingStart );
     if ( weaponInfo->firing_offsetW_min || weaponInfo->firing_offsetW_max ) {
         float rnd;
         float firing_offsetW;
         rnd = crandom(); // <-- between 0.0f and 1.0f
         firing_offsetW = ( 1.0f - rnd ) * weaponInfo->firing_offsetW_min + rnd * weaponInfo->firing_offsetW_max;
         if ( ( self->client->ps.bitFlags & hasFlipOffset ) && weaponInfo->firing_offsetWFlip ) {
             VectorMA( firingStart, -firing_offsetW, right, firingStart );
         } else {
             VectorMA( firingStart, firing_offsetW, right, firingStart );
         }
     }
     if ( weaponInfo->firing_offsetH_min || weaponInfo->firing_offsetH_max ) {
         float rnd;
         float firing_offsetH;
         rnd = crandom(); // <-- between 0.0f and 1.0f
         firing_offsetH = ( 1.0f - rnd ) * weaponInfo->firing_offsetH_min + rnd * weaponInfo->firing_offsetH_max;
         if ( ( self->client->ps.bitFlags & hasFlipOffset ) && weaponInfo->firing_offsetHFlip ) {
             VectorMA( firingStart, -firing_offsetH, up, firingStart );
         } else {
             VectorMA( firingStart, firing_offsetH, up, firingStart );
         }
     }
     // Take the necessary steps to configure and fire the weapon.
     switch ( weaponInfo->general_type ) {
     /* MISSILES */
     case skillTypeMISSILE:
         bolt = G_Spawn();
         bolt->classname = "rocket";
         bolt->s.eType = ET_MISSILE;
         bolt->startTimer = level.time + 800;
         bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
         // Set the weapon number correct, depending on altfire status.
         if ( !altfire ) {
             bolt->s.weapon = self->s.weapon;
         } else {
             bolt->s.weapon = self->s.weapon + ALTWEAPON_OFFSET;
         }
         bolt->r.ownerNum = self->s.number;
         bolt->s.clientNum = self->s.number; // <-- clientNum is free on all but ET_PLAYER so
         bolt->parent = self;                //     use it to store the owner for clientside.
         bolt->damage = weaponInfo->damage_damage;
         bolt->splashRadius = weaponInfo->damage_radius;
         bolt->splashDuration = weaponInfo->damage_radiusDuration;
         bolt->extraKnockback = weaponInfo->damage_extraKnockback;
         bolt->impede = weaponInfo->damage_impede;
         bolt->isSwattable = weaponInfo->physics_swat;
         bolt->isDrainable = weaponInfo->physics_drain;
         bolt->isBlindable = weaponInfo->physics_blind;
         if (altfire) {
             bolt->chargelvl = self->client->ps.stats[stChargePercentSecondary];
             self->client->ps.stats[stChargePercentSecondary] = 0; // Only reset it here!
         } else {
             bolt->chargelvl = self->client->ps.stats[stChargePercentPrimary];
             self->client->ps.stats[stChargePercentPrimary] = 0; // Only reset it here!
         }
         bolt->s.powerups = bolt->chargelvl; // Use this free field to transfer chargelvl
         bolt->powerLevelCurrent = bolt->powerLevelTotal = bolt->damage * ((float)bolt->chargelvl / 100.0f) * powerScale;
         bolt->s.dashDir[0] = bolt->powerLevelTotal; // Use this free field to transfer total power level
         bolt->clipmask = MASK_SHOT;
         bolt->target_ent = NULL;
         bolt->takedamage = qtrue;
         self->s.dashDir[2] = 0.0f;
         bolt->count = 0;
         {
             float radius;
             radius = weaponInfo->physics_radius + weaponInfo->physics_radiusMultiplier * (bolt->chargelvl / 100.0f);
             radius = sqrt((radius * radius) / 3); // inverse of Pythagoras
             bolt->radius = radius;
             radius = 1;
             VectorSet( bolt->r.mins, -radius, -radius, -radius );
             VectorSet( bolt->r.maxs, radius, radius, radius );
             VectorCopy( bolt->r.mins, bolt->r.absmin );
             VectorCopy( bolt->r.maxs, bolt->r.absmax );
             bolt->r.contents = CONTENTS_CORPSE; // So we can pass through a missile, but can still fire at it.
             bolt->die = G_DieUserWeapon;
         }
         bolt->speed = weaponInfo->physics_speed;
         bolt->accel = weaponInfo->physics_acceleration;
         bolt->bounceFrac = weaponInfo->physics_bounceFrac;
         bolt->bouncesLeft = weaponInfo->physics_maxBounces;
         bolt->timesTriggered = 0;
         // Configure the type correctly if we're using gravity or acceleration
         // Gravity affection takes precedence over acceleration.
         // FIXME: Can we get both simultaneously?
         if (weaponInfo->physics_gravity > 0) {
             bolt->gravity = (weaponInfo->physics_gravity / 100) * 1000;
             bolt->s.pos.trType = TR_MAPGRAVITY;
             bolt->s.pos.trDuration = bolt->gravity;
         } else {
             if (bolt->accel != 0.0f) {
                 bolt->s.pos.trType = TR_ACCEL;
                 bolt->s.pos.trDuration = bolt->accel;
             } else {
                 bolt->s.pos.trType = TR_LINEAR;
             }
         }
         // move a bit on the very first frame
         bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;
         VectorCopy( firingStart, bolt->s.pos.trBase );
         VectorCopy( firingStart, bolt->r.currentOrigin );
         VectorCopy( self->client->ps.viewangles, self->s.angles );
         VectorCopy( self->client->ps.viewangles, bolt->s.angles2 );
         VectorScale( firingDir, bolt->speed, bolt->s.pos.trDelta );
         VectorCopy(firingDir,bolt->movedir);
         // This saves network bandwidth.
         SnapVector( bolt->s.pos.trDelta );
         // Set the correct think based on homing properties.
         switch (weaponInfo->homing_type) {
             case HOM_PROX:
                 bolt->think = Think_ProxDet;
                 bolt->nextthink = level.time + FRAMETIME;
                 bolt->homRange = weaponInfo->homing_range;
                 break;
             case HOM_GUIDED:
                 bolt->think = Think_Guided;
                 bolt->nextthink = level.time + FRAMETIME;
                 // Kill off previously set accel, bounce and gravity. Guided missiles
                 // do not accelerate, bounce or experience gravity.
                 bolt->accel = 0;
                 bolt->bounceFrac = 0;
                 bolt->bouncesLeft = 0;
                 bolt->gravity = 0;
                 // Set guidetarget.
                 bolt->s.eFlags |= EF_GUIDED;
                 self->client->guidetarget = bolt;
                 bolt->guided = qtrue;
                 break;
             case HOM_REGULAR:
                 bolt->think = Think_Homing;
                 bolt->nextthink = level.time + FRAMETIME;
                 bolt->homRange = weaponInfo->homing_range;
                 //bolt->homAccel = weaponInfo->homing_accel;
                 break;
             case HOM_CYLINDER:
                 bolt->think = Think_CylinderHoming;
                 bolt->nextthink = level.time + FRAMETIME;
                 bolt->homRange = weaponInfo->homing_range;
                 //bolt->homAccel = weaponInfo->homing_accel;
                 break;
             case HOM_ARCH:
                 bolt->think = Think_NormalMissile;
                 bolt->nextthink = level.time + FRAMETIME;
                 bolt->bounceFrac = 0;
                 bolt->bouncesLeft = 0;
                 bolt->accel = 0;
                 bolt->gravity = 0;
                 {
                     trace_t trace;
                     vec3_t  begin, mid, end;
                     float   length;
                     VectorCopy( bolt->s.pos.trBase, begin );
                     VectorMA( begin, weaponInfo->homing_range, dir, end );
                     trap_Trace( &trace, begin, NULL, NULL, end, self->s.number, MASK_SHOT );
                     VectorCopy( trace.endpos, end );
                     length = Distance( begin, end );
                     VectorMA( begin, length / 2.0f, firingDir, mid );
                     bolt->s.pos.trType = TR_ARCH;
                     bolt->s.pos.trDuration = 1000.0f * length / weaponInfo->physics_speed;
                     VectorCopy( begin, bolt->s.pos.trBase );
                     VectorCopy( mid, bolt->s.angles2 );
                     VectorCopy( end, bolt->s.pos.trDelta );
                 }
                 break;
             case HOM_DRUNKEN:
                 bolt->think = Think_NormalMissile;
                 bolt->nextthink = level.time + FRAMETIME;
                 bolt->s.pos.trType = TR_DRUNKEN;
                 bolt->s.pos.trDuration = weaponInfo->homing_range;
                 break;
             case HOM_NONE:
                 bolt->think = Think_NormalMissile;
                 bolt->nextthink = level.time + FRAMETIME;
                 break;
             default:
                 // This should never happen!
                 break;
         }
         bolt->missileSpawnTime = level.time;
         bolt->maxMissileTime = weaponInfo->physics_lifetime;
         break;
     /* BEAMS */
     case skillTypeBEAM:
         homingType = weaponInfo->homing_type;
         bolt = G_Spawn();
         bolt->classname = "user_beam";
         bolt->s.eType = ET_BEAMHEAD;
         bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
         bolt->startTimer = level.time + 800;
         // Set the weapon number correct, depending on altfire status.
         if ( !altfire ) {
             bolt->s.weapon = self->s.weapon;
         }
         else{
             bolt->s.weapon = self->s.weapon + ALTWEAPON_OFFSET;
         }
         bolt->r.ownerNum = self->s.number;
         bolt->s.clientNum = self->s.number; // <-- clientNum is free on all but ET_PLAYER so
         bolt->parent = self;                //     use it to store the owner for clientside.
         VectorCopy( self->client->ps.viewangles, bolt->s.angles ); // store the correct angles
         bolt->damage = weaponInfo->damage_damage;
         bolt->splashRadius = weaponInfo->damage_radius;
         bolt->splashDuration = weaponInfo->damage_radiusDuration;
         bolt->extraKnockback = weaponInfo->damage_extraKnockback;
         bolt->isSwattable = weaponInfo->physics_swat;
         bolt->isDrainable = weaponInfo->physics_drain;
         bolt->isBlindable = weaponInfo->physics_blind;
         if (altfire) {
             bolt->chargelvl = self->client->ps.stats[stChargePercentSecondary];
             self->client->ps.stats[stChargePercentSecondary] = 0;
         }
         else{
             bolt->chargelvl = self->client->ps.stats[stChargePercentPrimary];
             self->client->ps.stats[stChargePercentPrimary] = 0;
         }
         bolt->s.powerups = bolt->chargelvl;
         bolt->powerLevelCurrent = bolt->powerLevelTotal = bolt->damage * (1.0f+(float)bolt->chargelvl / 100.0f) * powerScale;
         bolt->s.dashDir[0] = bolt->powerLevelTotal; // Use this free field to transfer total power level
         // FIXME: Hack into the old mod style, since it's still needed for now
         bolt->takedamage = qtrue;
         bolt->clipmask = MASK_SHOT;
         bolt->target_ent = NULL;
         self->s.dashDir[2] = 0.0f;
         bolt->count = 0;
         {
             float radius;
             radius = weaponInfo->physics_radius + weaponInfo->physics_radiusMultiplier * (bolt->chargelvl / 100.0f);
             radius = sqrt((radius * radius) / 3); // inverse of Pythagoras
             bolt->radius = radius;
             radius = 1;
             VectorSet( bolt->r.mins, -radius, -radius, -radius );
             VectorSet( bolt->r.maxs, radius, radius, radius );
             VectorCopy( bolt->r.mins, bolt->r.absmin );
             VectorCopy( bolt->r.maxs, bolt->r.absmax );
             bolt->r.contents = CONTENTS_CORPSE; // So we can pass through a missile, but can still fire at it.
             bolt->die = G_DieUserWeapon;
         }
         bolt->speed = weaponInfo->physics_speed;
         bolt->accel = 0;
         bolt->bounceFrac = 0;
         bolt->bouncesLeft = 0;
         bolt->gravity = 0;
         bolt->s.pos.trType = TR_LINEAR;
         VectorScale( dir, bolt->speed, bolt->s.pos.trDelta );
         SnapVector( bolt->s.pos.trDelta );
         bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;
         VectorCopy( start, bolt->s.pos.trBase );
         VectorCopy( start, bolt->r.currentOrigin );
         VectorCopy( firingDir, bolt->movedir );
         VectorCopy( self->client->ps.viewangles, self->s.angles );
         VectorCopy( self->client->ps.viewangles, bolt->s.angles2 );
         if(self->client->ps.lockedTarget > 0){homingType = HOM_GUIDED;}
         switch (homingType) {
         case HOM_GUIDED:
             bolt->think = Think_Guided;
             bolt->nextthink = level.time + FRAMETIME;
             bolt->s.eFlags |= EF_GUIDED;
             self->client->guidetarget = bolt;
             bolt->guided = qtrue;
             break;
         case HOM_ARCH:
         case HOM_PROX:
         case HOM_REGULAR:
         case HOM_CYLINDER:
         case HOM_NONE:
             bolt->think = Think_NormalMissile;
             bolt->nextthink = level.time + FRAMETIME;
             self->client->guidetarget = bolt;
             bolt->guided = qtrue;
             break;
         default:
             break;
         }
         bolt->missileSpawnTime = level.time;
         bolt->maxMissileTime = weaponInfo->physics_lifetime;
         break;
     case skillTypeHITSCAN:
         if ( !altfire ) {
             UserHitscan_Fire( self, weaponInfo, self->s.weapon, firingStart, firingDir );
             self->client->ps.stats[stChargePercentPrimary] = 0;
         } else {
             UserHitscan_Fire( self, weaponInfo, self->s.weapon + ALTWEAPON_OFFSET, firingStart, firingDir );
             self->client->ps.stats[stChargePercentSecondary] = 0;
         }
         break;
     case skillTypeTRIGGER:
         {
             gentity_t       *trigTarget;
             trace_t         trace;
             vec3_t          newBase, newDir, traceEnd;
             int             pass_ent, i;
             float           traceDist;
             for ( i = 0; i < MAX_GENTITIES; i++ ) {
                 // Select the entity
                 trigTarget = &g_entities[i];
                 // See if it is affected by the trigger
                 if ( !trigTarget->inuse ) {
                     continue;
                 } else if ( trigTarget->s.eType != ET_MISSILE ) {
                     continue;
                 } else if ( !altfire && ( trigTarget->s.weapon != self->s.weapon + ALTWEAPON_OFFSET )) {
                     continue;
                 } else if ( altfire && ( trigTarget->s.weapon != self->s.weapon )) {
                     continue;
                 } else if (trigTarget->s.clientNum != self->s.number){
                     continue;
                 }
                 // Get the target's current position
                 BG_EvaluateTrajectory( &trigTarget->s, &trigTarget->s.pos, level.time, newBase );
                 // Don't process any missiles beyond the maximum range of control
                 if ( Distance(newBase, start) > weaponInfo->physics_range_max ) {
                     continue;
                 }
                 // Set the target's new starting position and increase its trigger count
                 VectorCopy( newBase, trigTarget->s.pos.trBase );
                 trigTarget->timesTriggered++;
                 // Setup the new directional vector for the triggered weapon.
                 VectorSubtract( start, newBase, newDir );
                 traceDist = VectorLength( newDir ) + 100000;
                 VectorScale( dir, traceDist, traceEnd );
                 VectorAdd( traceEnd, start, traceEnd );
                 pass_ent = self->s.number;
                 trap_Trace( &trace, start, NULL, NULL, traceEnd, pass_ent, MASK_PLAYERSOLID );
                 VectorSubtract( trace.endpos, start, traceEnd );
                 VectorAdd( traceEnd, newDir, newDir );
                 VectorNormalize( newDir );
                 // Set the triggered weapon's new direction and speed
                 VectorScale( newDir, weaponInfo->physics_speed, trigTarget->s.pos.trDelta );
                 vectoangles( newDir, trigTarget->s.angles );
                 trigTarget->s.pos.trTime = level.time;
                 // Configure the type correctly if we're using gravity or acceleration
                 // Gravity affection takes precedence over acceleration.
                 // FIXME: Can we get both simultaneously?
                 if (weaponInfo->physics_gravity > 0) {
                     trigTarget->accel = 0;
                     trigTarget->gravity = (weaponInfo->physics_gravity / 100) * 1000;
                     trigTarget->s.pos.trType = TR_MAPGRAVITY;
                     trigTarget->s.pos.trDuration = trigTarget->gravity;
                 } else if (weaponInfo->physics_acceleration != 0.0f) {
                     trigTarget->gravity = 0;
                     trigTarget->accel = weaponInfo->physics_acceleration;
                     trigTarget->s.pos.trType = TR_ACCEL;
                     trigTarget->s.pos.trDuration = trigTarget->accel;
                 } else {
                     trigTarget->accel = 0;
                     trigTarget->gravity = 0;
                     trigTarget->s.pos.trType = TR_LINEAR;
                 }
             }
         }
         break;
     case skillTypeNONE:
         break;
     default:
         break;
     }
 }
References ALTWEAPON_OFFSET, BG_EvaluateTrajectory(), CONTENTS_CORPSE, crandom, g_userWeapon_t::damage_damage, g_userWeapon_t::damage_extraKnockback, g_userWeapon_t::damage_impede, g_userWeapon_t::damage_radius, g_userWeapon_t::damage_radiusDuration, dir, Distance(), EF_GUIDED, trace_t::endpos, ET_BEAMHEAD, ET_MISSILE, g_userWeapon_t::firing_angleH_max, g_userWeapon_t::firing_angleH_min, g_userWeapon_t::firing_angleW_max, g_userWeapon_t::firing_angleW_min, g_userWeapon_t::firing_offsetH_max, g_userWeapon_t::firing_offsetH_min, g_userWeapon_t::firing_offsetHFlip, g_userWeapon_t::firing_offsetW_max, g_userWeapon_t::firing_offsetW_min, g_userWeapon_t::firing_offsetWFlip, forward, FRAMETIME, G_DieUserWeapon(), g_entities, G_FindUserAltWeaponData(), G_FindUserWeaponData(), G_GetMuzzleSettings(), G_Spawn(), g_userWeapon_t::general_bitflags, g_userWeapon_t::general_type, hasFlipOffset, HOM_ARCH, HOM_CYLINDER, HOM_DRUNKEN, HOM_GUIDED, HOM_NONE, HOM_PROX, HOM_REGULAR, g_userWeapon_t::homing_range, g_userWeapon_t::homing_type, MASK_PLAYERSOLID, MASK_SHOT, MAX_GENTITIES, MISSILE_PRESTEP_TIME, muzzle, NULL, g_userWeapon_t::physics_acceleration, g_userWeapon_t::physics_blind, g_userWeapon_t::physics_bounceFrac, g_userWeapon_t::physics_drain, g_userWeapon_t::physics_gravity, g_userWeapon_t::physics_lifetime, g_userWeapon_t::physics_maxBounces, g_userWeapon_t::physics_radius, g_userWeapon_t::physics_radiusMultiplier, g_userWeapon_t::physics_range_max, g_userWeapon_t::physics_speed, g_userWeapon_t::physics_swat, plCurrent, qtrue, right, RotatePointAroundVector(), skillTypeBEAM, skillTypeHITSCAN, skillTypeMISSILE, skillTypeNONE, skillTypeTRIGGER, SnapVector, stChargePercentPrimary, stChargePercentSecondary, stEnergyAttack, SVF_USE_CURRENT_ORIGIN, Think_CylinderHoming(), Think_Guided(), Think_Homing(), Think_NormalMissile(), Think_ProxDet(), TR_ACCEL, TR_ARCH, TR_DRUNKEN, TR_LINEAR, TR_MAPGRAVITY, trap_Trace(), up, UserHitscan_Fire(), vectoangles(), VectorAdd, VectorCopy, VectorLength(), VectorMA(), VectorNormalize(), VectorScale, VectorSet, VectorSubtract, and WPF_ALTWEAPONPRESENT.
Referenced by FireWeapon().
FireWeapon()
void FireWeapon (gentity_t * ent, qboolean altfire)
Definition at line 104 of file g_weapon.c.
{
     AngleVectors(ent->client->ps.viewangles,forward,right,up);
     CalcMuzzlePointOrigin(ent,ent->client->oldOrigin,forward,right,up,muzzle);
     Fire_UserWeapon(ent,muzzle,forward,altfire);
     ent->client->ps.bitFlags ^= hasFlipOffset;
 }
References AngleVectors(), CalcMuzzlePointOrigin(), Fire_UserWeapon(), forward, hasFlipOffset, muzzle, right, and up.
Referenced by ClientEvents().
format()
void QDECL void QDECL format (printf , 1 , 2)
G_AddEvent()
void G_AddEvent (gentity_t * ent, int event, int eventParm)
Definition at line 553 of file g_utils.c.
{
     int     bits;
     if ( !event ) {
         G_Printf( "G_AddEvent: zero event added for entity %i\n", ent->s.number );
         return;
     }
     // clients need to add the event in playerState_t instead of entityState_t
     if ( ent->client ) {
         bits = ent->client->ps.externalEvent & EV_EVENT_BITS;
         bits = ( bits + EV_EVENT_BIT1 ) & EV_EVENT_BITS;
         ent->client->ps.externalEvent = event | bits;
         ent->client->ps.externalEventParm = eventParm;
         ent->client->ps.externalEventTime = level.time;
     } else {
         bits = ent->s.event & EV_EVENT_BITS;
         bits = ( bits + EV_EVENT_BIT1 ) & EV_EVENT_BITS;
         ent->s.event = event | bits;
         ent->s.eventParm = eventParm;
     }
     ent->eventTime = level.time;
 }
References bits(), EV_EVENT_BIT1, EV_EVENT_BITS, and G_Printf().
Referenced by G_ExplodeUserWeapon(), G_ImpactUserWeapon(), P_DamageFeedback(), Reached_BinaryMover(), ReturnToPos1(), Use_BinaryMover(), Use_Target_Speaker(), and UserHitscan_Fire().
G_AddPredictableEvent()
void G_AddPredictableEvent (gentity_t * ent, int event, int eventParm)
Definition at line 538 of file g_utils.c.
{
     if ( !ent->client ) {
         return;
     }
     BG_AddPredictableEventToPlayerstate( event, eventParm, &ent->client->ps );
 }
References BG_AddPredictableEventToPlayerstate().
G_Alloc()
void* G_Alloc (int size)
Definition at line 36 of file g_mem.c.
{
     char    *p;
     if ( g_debugAlloc.integer ) {
         G_Printf( "G_Alloc of %i bytes (%i left)\n", size, POOLSIZE - allocPoint - ( ( size + 31 ) & ~31 ) );
     }
     if ( allocPoint + size > POOLSIZE ) {
       G_Error( "G_Alloc: failed on allocation of %i bytes\n", size );
         return NULL;
     }
     p = &memoryPool[allocPoint];
     allocPoint += ( size + 31 ) & ~31;
     return p;
 }
References allocPoint, g_debugAlloc, G_Error(), G_Printf(), vmCvar_t::integer, memoryPool, NULL, and POOLSIZE.
Referenced by G_NewString().
G_CheckSkills()
void G_CheckSkills (playerState_t * ps)
g_userweapons.c
Definition at line 56 of file g_userweapons.c.
{
     int weapon;
     weapon = 1;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL1;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL2;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL3;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL4;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL5;
     ps->powerups[PW_SKILLS] &= ~ USABLE_SKILL6;
     while(weapon < 7){
         qboolean usable;
         g_userWeapon_t  *weaponSettings;
         usable = qtrue;
         weaponSettings = G_FindUserWeaponData(ps->clientNum,weapon);
         // =========================
         // REQUIREMENTS
         // =========================
         if(weaponSettings->require_maximum && ps->powerLevel[plMaximum] < weaponSettings->require_maximum){usable = qfalse;}
         if(weaponSettings->require_minPowerLevel && ps->powerLevel[plCurrent] < weaponSettings->require_minPowerLevel){usable = qfalse;}
         if(weaponSettings->require_maxPowerLevel && ps->powerLevel[plCurrent] > weaponSettings->require_maxPowerLevel){usable = qfalse;}
         if(weaponSettings->require_minFatigue && ps->powerLevel[plFatigue] < weaponSettings->require_minFatigue){usable = qfalse;}
         if(weaponSettings->require_maxFatigue && ps->powerLevel[plFatigue] > weaponSettings->require_maxFatigue){usable = qfalse;}
         if(weaponSettings->require_minHealth && ps->powerLevel[plHealth] < weaponSettings->require_minHealth){usable = qfalse;}
         if(weaponSettings->require_maxHealth && ps->powerLevel[plHealth] > weaponSettings->require_maxHealth){usable = qfalse;}
         if(weaponSettings->require_minTier && ps->powerLevel[plTierCurrent] < weaponSettings->require_minTier-1){usable = qfalse;}
         if(weaponSettings->require_maxTier && ps->powerLevel[plTierCurrent] > weaponSettings->require_maxTier-1){usable = qfalse;}
         if(weaponSettings->require_minTotalTier && ps->powerLevel[plTierTotal] < weaponSettings->require_minTotalTier-1){usable = qfalse;}
         if(weaponSettings->require_maxTotalTier && ps->powerLevel[plTierTotal] > weaponSettings->require_maxTotalTier-1){usable = qfalse;}
         if(weaponSettings->require_ground && !(ps->bitFlags & atopGround)){usable = qfalse;}
         if(weaponSettings->require_flight && !(ps->bitFlags & usingFlight)){usable = qfalse;}
         if(weaponSettings->require_water && !(ps->bitFlags & underWater)){usable = qfalse;}
         if(usable){
             if(weapon == 1){ps->powerups[PW_SKILLS] |= USABLE_SKILL1;}
             if(weapon == 2){ps->powerups[PW_SKILLS] |= USABLE_SKILL2;}
             if(weapon == 3){ps->powerups[PW_SKILLS] |= USABLE_SKILL3;}
             if(weapon == 4){ps->powerups[PW_SKILLS] |= USABLE_SKILL4;}
             if(weapon == 5){ps->powerups[PW_SKILLS] |= USABLE_SKILL5;}
             if(weapon == 6){ps->powerups[PW_SKILLS] |= USABLE_SKILL6;}
         }
         weapon += 1;
     }
 }
References atopGround, G_FindUserWeaponData(), plCurrent, plFatigue, plHealth, plMaximum, plTierCurrent, plTierTotal, PW_SKILLS, qfalse, qtrue, g_userWeapon_t::require_flight, g_userWeapon_t::require_ground, g_userWeapon_t::require_maxFatigue, g_userWeapon_t::require_maxHealth, g_userWeapon_t::require_maximum, g_userWeapon_t::require_maxPowerLevel, g_userWeapon_t::require_maxTier, g_userWeapon_t::require_maxTotalTier, g_userWeapon_t::require_minFatigue, g_userWeapon_t::require_minHealth, g_userWeapon_t::require_minPowerLevel, g_userWeapon_t::require_minTier, g_userWeapon_t::require_minTotalTier, g_userWeapon_t::require_water, underWater, USABLE_SKILL1, USABLE_SKILL2, USABLE_SKILL3, USABLE_SKILL4, USABLE_SKILL5, USABLE_SKILL6, and usingFlight.
Referenced by ClientThink_real().
G_Damage()
void G_Damage (gentity_t * targ, gentity_t * inflictor, gentity_t * attacker, vec3_t dir, vec3_t point, int damage, int dflags, int mod)
G_DetachUserWeapon()
void G_DetachUserWeapon (gentity_t * self)
Definition at line 1469 of file g_usermissile.c.
{
     if(self->s.eType == ET_BEAMHEAD && self->powerLevelCurrent > 0){
         g_entities[self->s.clientNum].client->ps.weaponstate = WEAPON_READY;
         self->s.eType = ET_MISSILE;
         self->think = Think_NormalMissile;
     }
 }
References ET_BEAMHEAD, ET_MISSILE, g_entities, Think_NormalMissile(), and WEAPON_READY.
Referenced by ClientEvents().
G_DieUserWeapon()
void G_DieUserWeapon (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, int mod)
Definition at line 1121 of file g_usermissile.c.
{
     if (inflictor == self)
         return;
     self->takedamage = qfalse;
     self->think = G_ExplodeUserWeapon;
     self->nextthink = level.time;
 }
References G_ExplodeUserWeapon(), and qfalse.
Referenced by Fire_UserWeapon().
G_EntitiesFree()
qboolean G_EntitiesFree (void)
Definition at line 441 of file g_utils.c.
{
     int         i;
     gentity_t   *e;
     e = &g_entities[MAX_CLIENTS];
     for ( i = MAX_CLIENTS; i < level.num_entities; i++, e++) {
         if ( e->inuse ) {
             continue;
         }
         // slot available
         return qtrue;
     }
     return qfalse;
 }
References g_entities, MAX_CLIENTS, qfalse, and qtrue.
G_Error()
void QDECL void QDECL G_Error (const char * fmt, ...)
Referenced by __attribute__(), Cmd_FollowCycle_f(), G_AddSpawnVarToken(), G_Alloc(), G_FindConfigstringIndex(), G_ParseSpawnVars(), G_Spawn(), G_SpawnEntitiesFromString(), G_TryPushingEntity(), Reached_BinaryMover(), SelectRandomFurthestSpawnPoint(), SP_target_speaker(), and SP_worldspawn().
G_ExplodeMissile()
void G_ExplodeMissile (gentity_t * ent)
G_ExplodeUserWeapon()
void G_ExplodeUserWeapon (gentity_t * self)
Definition at line 1128 of file g_usermissile.c.
{
     // Handles actual detonation of the weapon in question.
     vec3_t dir = { 0, 0, 1};
     vec3_t origin;
     self->takedamage = qfalse;
     // Terminate guidance
     if ( self->guided ) {
         g_entities[ self->s.clientNum ].client->ps.weaponstate = WEAPON_READY;
     }
     // Calculate current position
     BG_EvaluateTrajectory(&self->s,&self->s.pos,level.time,origin);
     SnapVector( origin ); // save net bandwith
     SnapVectorTowards( origin, self->s.pos.trBase ); // save net bandwidth
     G_SetOrigin( self, origin );
     self->s.eType = ET_EXPLOSION;
     self->splashEnd = level.time + self->splashDuration;
     self->splashTimer = level.time;
     G_AddEvent( self, EV_MISSILE_MISS_AIR, DirToByte( dir ) );
     trap_LinkEntity( self );
 }
References BG_EvaluateTrajectory(), dir, DirToByte(), ET_EXPLOSION, EV_MISSILE_MISS_AIR, G_AddEvent(), g_entities, G_SetOrigin(), qfalse, SnapVector, SnapVectorTowards(), trap_LinkEntity(), and WEAPON_READY.
Referenced by G_BounceUserMissile(), G_DieUserWeapon(), G_RemoveUserWeapon(), Think_CylinderHoming(), Think_Homing(), Think_NormalMissile(), Think_NormalMissileStrugglePlayer(), and Think_ProxDet().
G_FilterPacket()
qboolean G_FilterPacket (char * from)
Definition at line 177 of file g_svcmds.c.
 {
     int     i;
     unsigned    in;
     byte m[4];
     char *p;
     i = 0;
     p = from;
     while (*p && i < 4) {
         m[i] = 0;
         while (*p >= '0' && *p <= '9') {
             m[i] = m[i]*10 + (*p - '0');
             p++;
         }
         if (!*p || *p == ':')
             break;
         i++, p++;
     }
     in = *(unsigned *)m;
     for (i=0 ; i<numIPFilters ; i++)
         if ( (in & ipFilters[i].mask) == ipFilters[i].compare)
             return g_filterBan.integer != 0;
     return g_filterBan.integer == 0;
 }
References g_filterBan, vmCvar_t::integer, ipFilters, m, and numIPFilters.
Referenced by ClientConnect().
G_Find()
gentity_t* G_Find (gentity_t * from, int fieldofs, const char * match)
Definition at line 159 of file g_utils.c.
 {
     char    *s;
     if (!from)
         from = g_entities;
     else
         from++;
     for ( ; from < &g_entities[level.num_entities] ; from++)
     {
         if (!from->inuse)
             continue;
         s = *(char **) ((byte *)from + fieldofs);
         if (!s)
             continue;
         if (!Q_stricmp (s, match))
             return from;
     }
     return NULL;
 }
References g_entities, NULL, and Q_stricmp().
Referenced by FindIntermissionPoint(), G_PickTarget(), G_UseTargets(), SelectInitialSpawnPoint(), SelectNearestDeathmatchSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectRandomFurthestSpawnPoint(), SelectRandomTeamSpawnPoint(), target_laser_start(), and Think_SetupTrainTargets().
G_FreeEntity()
void G_FreeEntity (gentity_t * e)
Definition at line 464 of file g_utils.c.
{
     trap_UnlinkEntity (ed);     // unlink from world
     if ( ed->neverFree ) {
         return;
     }
     memset (ed, 0, sizeof(*ed));
     ed->classname = "freed";
     ed->freetime = level.time;
     ed->inuse = qfalse;
 }
References qfalse, and trap_UnlinkEntity().
Referenced by AimAtTarget(), G_RemoveUserWeapon(), G_RunFrame(), G_SpawnGEntityFromSpawnVars(), locateCamera(), multi_trigger(), Release_UserWeapon(), SP_func_train(), SP_info_null(), SP_light(), SP_misc_model(), SP_path_corner(), and trigger_always_think().
G_GetMuzzleSettings()
void G_GetMuzzleSettings (vec3_t muzzle_g, vec3_t forward_g, vec3_t right_g, vec3_t up_g)
Definition at line 40 of file g_weapon.c.
{
     VectorCopy(muzzle,muzzle_g);
     VectorCopy(forward,forward_g);
     VectorCopy(right,right_g);
     VectorCopy(up,up_g);
 }
References forward, muzzle, right, up, and VectorCopy.
Referenced by Fire_UserWeapon().
G_InitGentity()
void G_InitGentity (gentity_t * e)
Definition at line 367 of file g_utils.c.
{
     e->inuse = qtrue;
     e->classname = "noclass";
     e->s.number = e - g_entities;
     e->r.ownerNum = ENTITYNUM_NONE;
 }
References ENTITYNUM_NONE, g_entities, and qtrue.
Referenced by ClientBegin(), and G_Spawn().
G_InitMemory()
void G_InitMemory (void)
Definition at line 55 of file g_mem.c.
{
     allocPoint = 0;
 }
References allocPoint.
Referenced by G_InitGame().
G_InitSessionData()
void G_InitSessionData (gclient_t * client, char * userinfo)
Definition at line 102 of file g_session.c.
{
     clientSession_t *sess;
     const char      *value;
     sess = &client->sess;
     // initial team determination
     if ( g_gametype.integer >= GT_TEAM ) {
         if ( g_teamAutoJoin.integer ) {
             sess->sessionTeam = PickTeam( -1 );
             BroadcastTeamChange( client, -1 );
         } else {
             // always spawn as spectator in team games
             sess->sessionTeam = TEAM_SPECTATOR;
         }
     } else {
         value = Info_ValueForKey( userinfo, "team" );
         if ( value[0] == 's' ) {
             // a willing spectator, not a waiting-in-line
             sess->sessionTeam = TEAM_SPECTATOR;
         } else {
             switch ( g_gametype.integer ) {
             default:
             case GT_FFA:
             case GT_STRUGGLE:
             case GT_SINGLE_PLAYER:
                 if ( g_maxGameClients.integer > 0 &&
                     level.numNonSpectatorClients >= g_maxGameClients.integer ) {
                     sess->sessionTeam = TEAM_SPECTATOR;
                 } else {
                     sess->sessionTeam = TEAM_FREE;
                 }
                 break;
             case GT_TOURNAMENT:
                 // if the game is full, go into a waiting mode
                 if ( level.numNonSpectatorClients >= 2 ) {
                     sess->sessionTeam = TEAM_SPECTATOR;
                 } else {
                     sess->sessionTeam = TEAM_FREE;
                 }
                 break;
             }
         }
     }
     sess->spectatorState = SPECTATOR_FREE;
     AddTournamentQueue(client);
     G_WriteClientSessionData( client );
 }
References AddTournamentQueue(), BroadcastTeamChange(), g_gametype, g_maxGameClients, g_teamAutoJoin, G_WriteClientSessionData(), GT_FFA, GT_SINGLE_PLAYER, GT_STRUGGLE, GT_TEAM, GT_TOURNAMENT, Info_ValueForKey(), vmCvar_t::integer, PickTeam(), clientSession_t::sessionTeam, SPECTATOR_FREE, clientSession_t::spectatorState, TEAM_FREE, and TEAM_SPECTATOR.
Referenced by ClientConnect().
G_InitWorldSession()
void G_InitWorldSession (void)
Definition at line 159 of file g_session.c.
{
     char    s[MAX_STRING_CHARS];
     int         gt;
     trap_Cvar_VariableStringBuffer( "session", s, sizeof(s) );
     gt = atoi( s );
     // if the gametype changed since the last session, don't use any
     // client sessions
     if ( g_gametype.integer != gt ) {
         level.newSession = qtrue;
         G_Printf( "Gametype changed, clearing session data.\n" );
     }
 }
References g_gametype, G_Printf(), gt, vmCvar_t::integer, MAX_STRING_CHARS, qtrue, and trap_Cvar_VariableStringBuffer().
Referenced by G_InitGame().
G_InvulnerabilityEffect()
int G_InvulnerabilityEffect (gentity_t * targ, vec3_t dir, vec3_t point, vec3_t impactpoint, vec3_t bouncedir)
G_KillBox()
void G_KillBox (gentity_t * ent)
Definition at line 525 of file g_utils.c.
 {}
Referenced by ClientSpawn(), and TeleportPlayer().
G_LogPrintf()
void QDECL G_LogPrintf (const char * fmt, ...)
Referenced by ClientBegin(), ClientConnect(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_Tell_f(), Cmd_VoiceTell_f(), G_Say(), and SP_worldspawn().
G_ModelIndex()
int G_ModelIndex (char * name)
Definition at line 116 of file g_utils.c.
{
     return G_FindConfigstringIndex (name, CS_MODELS, MAX_MODELS, qtrue);
 }
References CS_MODELS, G_FindConfigstringIndex(), MAX_MODELS, and qtrue.
Referenced by G_InitGame(), InitMover(), SP_misc_model(), and SpawnPodium().
G_NewString()
char* G_NewString (const char * string)
Definition at line 259 of file g_spawn.c.
{
     char    *newb, *new_p;
     int     i,l;
     l = strlen(string) + 1;
     newb = G_Alloc( l );
     new_p = newb;
     // turn \n into a real linefeed
     for ( i=0 ; i< l ; i++ ) {
         if (string[i] == '\\' && i < l-1) {
             i++;
             if (string[i] == 'n') {
                 *new_p++ = '\n';
             } else {
                 *new_p++ = '\\';
             }
         } else {
             *new_p++ = string[i];
         }
     }
     return newb;
 }
References G_Alloc().
Referenced by G_ParseField().
G_PickTarget()
gentity_t* G_PickTarget (char * targetname)
Definition at line 192 of file g_utils.c.
 {
     gentity_t   *ent = NULL;
     int     num_choices = 0;
     gentity_t   *choice[MAXCHOICES];
     if (!targetname)
     {
         G_Printf("G_PickTarget called with NULL targetname\n");
         return NULL;
     }
     while(1)
     {
         ent = G_Find (ent, FOFS(targetname), targetname);
         if (!ent)
             break;
         choice[num_choices++] = ent;
         if (num_choices == MAXCHOICES)
             break;
     }
     if (!num_choices)
     {
         G_Printf("G_PickTarget: target %s not found\n", targetname);
         return NULL;
     }
     return choice[rand() % num_choices];
 }
References FOFS, G_Find(), G_Printf(), MAXCHOICES, and NULL.
Referenced by AimAtTarget(), FindIntermissionPoint(), locateCamera(), target_relay_use(), target_teleporter_use(), and trigger_teleporter_touch().
G_Printf()
void QDECL G_Printf (const char * fmt, ...)
Referenced by AddIP(), ClientForString(), G_AddEvent(), G_Alloc(), G_CallSpawn(), G_InitWorldSession(), G_PickTarget(), G_Say(), G_Spawn(), G_UseTargets(), G_Voice(), G_weapPhys_AddDefinitionRef(), G_weapPhys_AddImportRef(), G_weapPhys_AddLinkRef(), G_weapPhys_ErrorHandle(), G_weapPhys_LoadFile(), G_weapPhys_Parse(), G_weapPhys_ParseCategories(), G_weapPhys_ParseDefinition(), locateCamera(), SP_func_timer(), SP_func_train(), SP_path_corner(), SP_target_teleporter(), SP_trigger_multiple(), SpawnModelOnVictoryPad(), StringToFilter(), Svcmd_AddIP_f(), Svcmd_EntityList_f(), Svcmd_GameMem_f(), Svcmd_RemoveIP_f(), target_laser_start(), target_teleporter_use(), Think_Guided(), Think_SetupTrainTargets(), and trigger_teleporter_touch().
G_ProcessIPBans()
void G_ProcessIPBans (void)
Definition at line 239 of file g_svcmds.c.
 {
     char *s, *t;
     char        str[MAX_CVAR_VALUE_STRING];
     Q_strncpyz( str, g_banIPs.string, sizeof(str) );
     for (t = s = g_banIPs.string; *t; /* */ ) {
         s = strchr(s, ' ');
         if (!s)
             break;
         while (*s == ' ')
             *s++ = 0;
         if (*t)
             AddIP( t );
         t = s;
     }
 }
References AddIP(), g_banIPs, MAX_CVAR_VALUE_STRING, Q_strncpyz(), and vmCvar_t::string.
Referenced by G_InitGame().
G_RadarUpdateCS()
void G_RadarUpdateCS (void)
Definition at line 8 of file g_radar.c.
{
     int i, valid_count;
     gentity_t *ent;
     playerState_t *ps;
     char cmd[MAX_TOKEN_CHARS];  // make sure our command string is
                                 // large enough for all the data
     // do we need to update the positions yet?
     if (level.time - level.lastRadarUpdateTime > RADAR_UPDATE_TIME) {
         //store the current time so we know when to update next
         level.lastRadarUpdateTime = level.time;
         //for each possible client
         valid_count = 0;
         for (i = 0; i < g_maxclients.integer; i++) {
             //get a pointer to the entity
             ent = g_entities + i;
             //see if we have a valid entry
             if ( ent->client->pers.connected != CON_CONNECTED ) {
                 g_playerOrigins[i].valid = qfalse;
             } else if ( !(ent->inuse) ) {
                 g_playerOrigins[i].valid = qfalse;
             } else if( ent->client->ps.powerLevel[plCurrent] <= 0 ) {
                 g_playerOrigins[i].valid = qfalse;
             } else {
                 // get the client's player info
                 ps = &ent->client->ps;
                 //get and store the client position and information
                 VectorCopy( ps->origin, g_playerOrigins[i].pos );
                 g_playerOrigins[i].pl = ps->powerLevel[plCurrent];
                 g_playerOrigins[i].plMax = ps->powerLevel[plMaximum];
                 g_playerOrigins[i].clientNum = ps->clientNum;
                 g_playerOrigins[i].properties = 0;
                 if ( ( ps->stats[stChargePercentPrimary] >= 50 ) || ( ps->stats[stChargePercentSecondary] >= 50 ) ) {
                     g_playerOrigins[i].properties |= RADAR_WARN;
                 }
                 if ( ( ps->eFlags & EF_AURA ) || ps->bitFlags & usingBoost ) {
                     g_playerOrigins[i].properties |= RADAR_BURST;
                 }
                 g_playerOrigins[i].team = ps->persistant[ PERS_TEAM ];
                 if ( g_playerOrigins[i].team >= TEAM_SPECTATOR ) {
                     // mark as invalid entry for a spectator
                     g_playerOrigins[i].valid = qfalse;
                 } else {
                     //mark as valid entry
                     g_playerOrigins[i].valid = qtrue;
                     //increase the valid counter
                     valid_count++;
                 }
             }
         }
         //build the command string to send
         Com_sprintf( cmd, sizeof(cmd), "radar %i", valid_count );
         for( i = 0; i < g_maxclients.integer; i++ ) {
             //if weve got a valid entry then add the position to the command string
             if( g_playerOrigins[i].valid ) {
                 strcat(cmd, va(" %i,", g_playerOrigins[i].clientNum));
                 strcat(cmd, va("%i,",  g_playerOrigins[i].pl));
                 strcat(cmd, va("%i,",  g_playerOrigins[i].plMax));
                 strcat(cmd, va("%i,",  g_playerOrigins[i].team));
                 strcat(cmd, va("%i,",  g_playerOrigins[i].properties));
                 strcat(cmd, va("%i,",  (int)ceil(g_playerOrigins[i].pos[0])));
                 strcat(cmd, va("%i,",  (int)ceil(g_playerOrigins[i].pos[1])));
                 strcat(cmd, va("%i",   (int)ceil(g_playerOrigins[i].pos[2])));
             }
         }
         // broadcast the command seperately to only connected clients.
         // FIXME: Does this prevent overflows that otherwise have to
         //        wait for a time-out message from unconnected clients?
         // NOTE:  Yep, seems to fix it.
         for ( i = 0; i < g_maxclients.integer; i++ ) {
             ent = g_entities + i;
             if ( ent->client->pers.connected != CON_CONNECTED ) {
                 continue;
             }
             if ( ent->inuse ) {
                 trap_SendServerCommand( ent-g_entities, cmd );
             }
         }
         /*
         //finally broadcast the command
         trap_SendServerCommand( -1, cmd );
         */
     }
 }
References radar_t::clientNum, Com_sprintf(), CON_CONNECTED, EF_AURA, g_entities, g_maxclients, g_playerOrigins, vmCvar_t::integer, MAX_TOKEN_CHARS, PERS_TEAM, radar_t::pl, plCurrent, radar_t::plMax, plMaximum, radar_t::pos, radar_t::properties, qfalse, qtrue, RADAR_BURST, RADAR_UPDATE_TIME, RADAR_WARN, stChargePercentPrimary, stChargePercentSecondary, radar_t::team, TEAM_SPECTATOR, trap_SendServerCommand(), usingBoost, va(), radar_t::valid, and VectorCopy.
Referenced by G_RunFrame().
G_RadiusDamage()
qboolean G_RadiusDamage (vec3_t origin, gentity_t * attacker, float damage, float radius, gentity_t * ignore, int mod)
G_ReadSessionData()
void G_ReadSessionData (gclient_t * client)
Definition at line 69 of file g_session.c.
{
     char    s[MAX_STRING_CHARS];
     const char  *var;
     int teamLeader;
     int spectatorState;
     int sessionTeam;
     var = va( "session%i", (int)(client - level.clients) );
     trap_Cvar_VariableStringBuffer( var, s, sizeof(s) );
     sscanf( s, "%i %i %i %i %i %i %i",
         &sessionTeam,
         &client->sess.spectatorNum,
         &spectatorState,
         &client->sess.spectatorClient,
         &client->sess.wins,
         &client->sess.losses,
         &teamLeader
         );
     client->sess.sessionTeam = (team_t)sessionTeam;
     client->sess.spectatorState = (spectatorState_t)spectatorState;
     client->sess.teamLeader = (qboolean)teamLeader;
 }
References MAX_STRING_CHARS, trap_Cvar_VariableStringBuffer(), and va().
Referenced by ClientConnect().
G_RemoveUserWeapon()
void G_RemoveUserWeapon (gentity_t * self)
Definition at line 1476 of file g_usermissile.c.
{
     gentity_t *other = self->enemy;
     if(self->client){
         self->client->ps.bitFlags &= ~isStruggling;
     }
     if(other){
         other->client->ps.bitFlags &= ~isStruggling;
         if(other->client->ps.lockedTarget >= MAX_CLIENTS){
             other->client->ps.lockedPosition = NULL;
             other->client->ps.lockedTarget = 0;
         }
     }
     if(self->guided){
         g_entities[self->s.clientNum].client->ps.weaponstate = WEAPON_READY;
     }
     if(self->s.eType == ET_BEAMHEAD && self->powerLevelCurrent > 0){
         G_ExplodeUserWeapon(self);
         return;
     }
     G_FreeEntity(self);
 }
References ET_BEAMHEAD, g_entities, G_ExplodeUserWeapon(), G_FreeEntity(), isStruggling, MAX_CLIENTS, NULL, and WEAPON_READY.
Referenced by G_RunUserMissile(), Think_CylinderHoming(), Think_Guided(), Think_Homing(), Think_NormalMissile(), and Think_NormalMissileStruggle().
G_RunClient()
void G_RunClient (gentity_t * ent)
Definition at line 609 of file g_active.c.
{
     if ( !g_synchronousClients.integer && !ent->client->ps.lockedTarget) {
         return;
     }
     ent->client->pers.cmd.serverTime = level.time;
     ClientThink_real( ent );
 }
References ClientThink_real(), g_synchronousClients, and vmCvar_t::integer.
Referenced by G_RunFrame().
G_RunMissile()
void G_RunMissile (gentity_t * ent)
G_RunMover()
void G_RunMover (gentity_t * ent)
Definition at line 441 of file g_mover.c.
{
     // if not a team captain, don't do anything, because
     // the captain will handle everything
     if ( ent->flags & FL_TEAMSLAVE ) {
         return;
     }
     // if stationary at one of the positions, don't move anything
     if ( ent->s.pos.trType != TR_STATIONARY || ent->s.apos.trType != TR_STATIONARY ) {
         G_MoverTeam( ent );
     }
     // check think function
     G_RunThink( ent );
 }
References FL_TEAMSLAVE, G_MoverTeam(), G_RunThink(), and TR_STATIONARY.
Referenced by G_RunFrame().
G_RunRiftWeaponClass()
void G_RunRiftWeaponClass (gentity_t * ent)
G_RunThink()
void G_RunThink (gentity_t * ent)
Definition at line 1420 of file g_main.c.
{
     float   thinktime;
     thinktime = ent->nextthink;
     if (thinktime <= 0) {
         return;
     }
     if (thinktime > level.time) {
         return;
     }
     ent->nextthink = 0;
     if (!ent->think) {
         G_Error ( "NULL ent->think");
     }
     ent->think (ent);
 }
References G_Error().
Referenced by G_RunFrame(), G_RunMover(), and G_RunUserMissile().
G_RunUserExplosion()
void G_RunUserExplosion (gentity_t * ent)
Definition at line 1515 of file g_usermissile.c.
{
     int radius,power;
     float step;
     if(level.time > ent->splashTimer && ent->powerLevelCurrent > 0){
         ent->splashTimer = level.time + 100;
         step = (1.0 - ((float)ent->splashEnd - (float)level.time) / (float)ent->splashDuration);
         radius = step * ent->splashRadius;
         power = (ent->powerLevelCurrent * (100.0/(float)ent->splashDuration));
         //G_Printf("Explosion power : %i\n",power);
         G_UserRadiusDamage(ent->r.currentOrigin,GetMissileOwnerEntity(ent),ent,power,radius,ent->extraKnockback);
     }
     if(level.time >= ent->splashEnd || ent->powerLevelCurrent <= 0){
         ent->freeAfterEvent = qtrue;
     }
 }
References G_UserRadiusDamage(), GetMissileOwnerEntity(), and qtrue.
Referenced by G_RunFrame().
G_RunUserMissile()
void G_RunUserMissile (gentity_t * ent)
Definition at line 1530 of file g_usermissile.c.
{
     vec3_t      origin;
     trace_t     trace;
     int         pass_ent;
     int         beamKnockBack;
     gentity_t   *traceEnt;
     vec3_t      muzzle, forward, right, up;
     vec3_t      start,end;
     trace_t     trace2;
     gentity_t   *traceEnt2;
     gentity_t   *missileOwner = GetMissileOwnerEntity(ent);
     BG_EvaluateTrajectory( &ent->s, &ent->s.pos, level.time, origin );
     if (ent->count) {
         pass_ent = ent->s.number;
     }
     else{
         pass_ent = ent->r.ownerNum;
     }
     // trace a line from the previous position to the current position
     trap_Trace( &trace, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, origin, pass_ent, ent->clipmask );
     if ( trace.startsolid || trace.allsolid ) {
         // make sure the trace.entityNum is set to the entity we're stuck in
         trap_Trace(&trace, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, ent->r.currentOrigin, pass_ent, ent->clipmask );
         trace.fraction = 0;
     }
     else {
         VectorCopy( trace.endpos, ent->r.currentOrigin );
     }
     //Missile_Smooth(ent,origin,&trace);
     trap_LinkEntity(ent);
     //G_Printf("%i\n",ent->r.currentOrigin);
     if(trace.fraction != 1){
         // never explode or bounce on sky
         if ( trace.surfaceFlags & SURF_NOIMPACT ) {
             G_RemoveUserWeapon( ent );
             return;
         }
         G_ImpactUserWeapon(ent, &trace);
         if ((ent->s.eType != ET_MISSILE) && (ent->s.eType != ET_BEAMHEAD)){return;}
     }
     // if the attack wasn't yet outside the player body
     if (!ent->count) {
         // check if the attack is outside the owner bbox
         trap_Trace( &trace, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, ent->r.currentOrigin, ENTITYNUM_NONE, ent->clipmask );
         if (!trace.startsolid || trace.entityNum != ent->r.ownerNum) {
             ent->count = 1;
         }
     }
     // Here we test if something entered a beam
     if(ent->s.eType == ET_BEAMHEAD && !(ent->s.eFlags & EF_GUIDED)){
         // Get player direction
         AngleVectors( missileOwner->client->ps.viewangles, forward, right, up );
         CalcMuzzlePoint( missileOwner, forward, right, up, muzzle );
         // Get player position and beam head position
         BG_EvaluateTrajectory( &missileOwner->s, &missileOwner->s.pos, level.time, start );
         BG_EvaluateTrajectory( &ent->s, &ent->s.pos, level.time, end );
         // Trace between the two positions
         trap_Trace (&trace2, start, ent->r.mins, ent->r.maxs, end, ent->s.number, MASK_SHOT);
         traceEnt2 = &g_entities[ trace2.entityNum ];
         // Snap the endpos to integers, but nudged towards the line
         SnapVectorTowards( trace2.endpos, muzzle );
         // If a player is holding block when he entered the beam, inititate push struggle.
         if (traceEnt2->client && traceEnt2->takedamage && trace2.fraction != 1 && (traceEnt2->client->ps.bitFlags & usingBlock)) {
             G_SetOrigin(ent,trace2.endpos);
             G_ImpactUserWeapon(ent,&trace2);
         // Else if a player that entered the beam isn't blocking, burn them and/or push them.
         }else if (traceEnt2->client && traceEnt2->takedamage && trace2.fraction != 1 && !(traceEnt2->client->ps.bitFlags & usingBlock)) {
         }
         if ((ent->s.eType != ET_MISSILE) && (ent->s.eType != ET_BEAMHEAD)) {
             return;
         }
     }
     // check think function after bouncing
     G_RunThink( ent );
 }
References trace_t::allsolid, AngleVectors(), BG_EvaluateTrajectory(), CalcMuzzlePoint(), EF_GUIDED, trace_t::endpos, trace_t::entityNum, ENTITYNUM_NONE, ET_BEAMHEAD, ET_MISSILE, forward, trace_t::fraction, g_entities, G_ImpactUserWeapon(), G_RemoveUserWeapon(), G_RunThink(), G_SetOrigin(), GetMissileOwnerEntity(), MASK_SHOT, muzzle, right, SnapVectorTowards(), trace_t::startsolid, SURF_NOIMPACT, trace_t::surfaceFlags, trap_LinkEntity(), trap_Trace(), up, usingBlock, and VectorCopy.
Referenced by G_RunFrame().
G_SetMovedir()
void G_SetMovedir (vec3_t angles, vec3_t movedir)
Definition at line 328 of file g_utils.c.
{
     static vec3_t VEC_UP        = {0, -1, 0};
     static vec3_t MOVEDIR_UP    = {0, 0, 1};
     static vec3_t VEC_DOWN      = {0, -2, 0};
     static vec3_t MOVEDIR_DOWN  = {0, 0, -1};
     if ( VectorCompare (angles, VEC_UP) ) {
         VectorCopy (MOVEDIR_UP, movedir);
     } else if ( VectorCompare (angles, VEC_DOWN) ) {
         VectorCopy (MOVEDIR_DOWN, movedir);
     } else {
         AngleVectors (angles, movedir, NULL, NULL);
     }
     VectorClear( angles );
 }
References angles, AngleVectors(), NULL, VectorClear, VectorCompare(), and VectorCopy.
Referenced by InitTrigger(), locateCamera(), SP_func_button(), SP_func_door(), SP_target_push(), and target_laser_start().
G_SetOrigin()
void G_SetOrigin (gentity_t * ent, vec3_t origin)
Definition at line 601 of file g_utils.c.
{
     VectorCopy( origin, ent->s.pos.trBase );
     ent->s.pos.trType = TR_STATIONARY;
     ent->s.pos.trTime = 0;
     ent->s.pos.trDuration = 0;
     VectorClear( ent->s.pos.trDelta );
     VectorCopy( origin, ent->r.currentOrigin );
 }
References TR_STATIONARY, VectorClear, and VectorCopy.
Referenced by ClientSpawn(), G_ExplodeUserWeapon(), G_ImpactUserWeapon(), G_RunUserMissile(), G_TempEntity(), PodiumPlacementThink(), SP_info_camp(), SP_info_notnull(), SP_misc_model(), SP_target_location(), SP_target_position(), SpawnModelOnVictoryPad(), SpawnPodium(), and UserHitscan_Fire().
G_SetStats()
void G_SetStats (gentity_t * ent)
G_Sound()
void G_Sound (gentity_t * ent, int channel, int soundIndex)
Definition at line 583 of file g_utils.c.
{
     gentity_t   *te;
     te = G_TempEntity( ent->r.currentOrigin, EV_GENERAL_SOUND );
     te->s.eventParm = soundIndex;
 }
References EV_GENERAL_SOUND, and G_TempEntity().
Referenced by Use_target_push().
G_SoundIndex()
int G_SoundIndex (char * name)
Definition at line 120 of file g_utils.c.
{
     return G_FindConfigstringIndex (name, CS_SOUNDS, MAX_SOUNDS, qtrue);
 }
References CS_SOUNDS, G_FindConfigstringIndex(), MAX_SOUNDS, and qtrue.
Referenced by InitMover(), SP_func_button(), SP_func_door(), SP_func_plat(), SP_target_push(), SP_target_speaker(), SP_trigger_push(), and SP_trigger_teleport().
G_Spawn()
gentity_t* G_Spawn (void)
Definition at line 389 of file g_utils.c.
{
     int         i, force;
     gentity_t   *e;
     e = NULL;   // shut up warning
     i = 0;      // shut up warning
     for ( force = 0 ; force < 2 ; force++ ) {
         // if we go through all entities and can't find one to free,
         // override the normal minimum times before use
         e = &g_entities[MAX_CLIENTS];
         for ( i = MAX_CLIENTS ; i<level.num_entities ; i++, e++) {
             if ( e->inuse ) {
                 continue;
             }
             // the first couple seconds of server time can involve a lot of
             // freeing and allocating, so relax the replacement policy
             if ( !force && e->freetime > level.startTime + 2000 && level.time - e->freetime < 1000 ) {
                 continue;
             }
             // reuse this slot
             G_InitGentity( e );
             return e;
         }
         if ( i != MAX_GENTITIES ) {
             break;
         }
     }
     if ( i == ENTITYNUM_MAX_NORMAL ) {
         for (i = 0; i < MAX_GENTITIES; i++) {
             G_Printf("%4i: %s\n", i, g_entities[i].classname);
         }
         G_Error( "G_Spawn: no free entities" );
     }
     // open up a new slot
     level.num_entities++;
     // let the server system know that there are more entities
     trap_LocateGameData( level.gentities, level.num_entities, sizeof( gentity_t ),
         &level.clients[0].ps, sizeof( level.clients[0] ) );
     G_InitGentity( e );
     return e;
 }
References ENTITYNUM_MAX_NORMAL, g_entities, G_Error(), G_InitGentity(), G_Printf(), MAX_CLIENTS, MAX_GENTITIES, NULL, and trap_LocateGameData().
Referenced by Fire_UserWeapon(), G_SpawnGEntityFromSpawnVars(), G_TempEntity(), InitBodyQue(), SpawnModelOnVictoryPad(), SpawnPlatTrigger(), SpawnPodium(), Think_SpawnNewDoorTrigger(), and UserHitscan_Fire().
G_SpawnEntitiesFromString()
void G_SpawnEntitiesFromString (void)
Definition at line 563 of file g_spawn.c.
{
     // allow calls to G_Spawn*()
     level.spawning = qtrue;
     level.numSpawnVars = 0;
     // the worldspawn is not an actual entity, but it still
     // has a "spawn" function to perform any global setup
     // needed by a level (setting configstrings or cvars, etc)
     if ( !G_ParseSpawnVars() ) {
         G_Error( "SpawnEntities: no entities" );
     }
     SP_worldspawn();
     // parse ents
     while( G_ParseSpawnVars() ) {
         G_SpawnGEntityFromSpawnVars();
     }
     level.spawning = qfalse;            // any future calls to G_Spawn*() will be errors
 }
References G_Error(), G_ParseSpawnVars(), G_SpawnGEntityFromSpawnVars(), qfalse, qtrue, and SP_worldspawn().
Referenced by G_InitGame().
G_SpawnFloat()
qboolean G_SpawnFloat (const char * key, const char * defaultString, float * out)
Definition at line 45 of file g_spawn.c.
{
     char        *s;
     qboolean    present;
     present = G_SpawnString( key, defaultString, &s );
     *out = atof( s );
     return present;
 }
References G_SpawnString(), and out.
Referenced by InitMover(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_timer(), SP_misc_portal_camera(), SP_target_delay(), SP_target_speaker(), and SP_trigger_multiple().
G_SpawnInt()
qboolean G_SpawnInt (const char * key, const char * defaultString, int * out)
Definition at line 54 of file g_spawn.c.
{
     char        *s;
     qboolean    present;
     present = G_SpawnString( key, defaultString, &s );
     *out = atoi( s );
     return present;
 }
References G_SpawnString(), and out.
Referenced by G_SpawnGEntityFromSpawnVars(), SP_func_bobbing(), SP_func_door(), SP_func_pendulum(), and SP_func_plat().
G_SpawnString()
qboolean G_SpawnString (const char * key, const char * defaultString, char ** out)
Definition at line 26 of file g_spawn.c.
{
     int     i;
     if ( !level.spawning ) {
         *out = (char *)defaultString;
 //      G_Error( "G_SpawnString() called while not spawning" );
     }
     for ( i = 0 ; i < level.numSpawnVars ; i++ ) {
         if ( !Q_stricmp( key, level.spawnVars[i][0] ) ) {
             *out = level.spawnVars[i][1];
             return qtrue;
         }
     }
     *out = (char *)defaultString;
     return qfalse;
 }
References out, Q_stricmp(), qfalse, and qtrue.
Referenced by G_SpawnFloat(), G_SpawnGEntityFromSpawnVars(), G_SpawnInt(), G_SpawnVector(), InitMover(), SP_target_speaker(), and SP_worldspawn().
G_SpawnVector()
qboolean G_SpawnVector (const char * key, const char * defaultString, float * out)
Definition at line 63 of file g_spawn.c.
{
     char        *s;
     qboolean    present;
     present = G_SpawnString( key, defaultString, &s );
     sscanf( s, "%f %f %f", &out[0], &out[1], &out[2] );
     return present;
 }
References G_SpawnString(), and out.
Referenced by InitMover().
G_TeamCommand()
void G_TeamCommand (team_t team, char * cmd)
Definition at line 134 of file g_utils.c.
{
     int     i;
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if ( level.clients[i].pers.connected == CON_CONNECTED ) {
             if ( level.clients[i].sess.sessionTeam == team ) {
                 trap_SendServerCommand( i, va("%s", cmd ));
             }
         }
     }
 }
References CON_CONNECTED, trap_SendServerCommand(), and va().
Referenced by Use_Target_Print().
G_TempEntity()
gentity_t* G_TempEntity (vec3_t origin, int event)
Definition at line 486 of file g_utils.c.
{
     gentity_t       *e;
     vec3_t      snapped;
     e = G_Spawn();
     e->s.eType = ET_EVENTS + event;
     e->classname = "tempEntity";
     e->eventTime = level.time;
     e->freeAfterEvent = qtrue;
     VectorCopy( origin, snapped );
     SnapVector( snapped );      // save network bandwidth
     G_SetOrigin( e, snapped );
     // find cluster for PVS
     trap_LinkEntity( e );
     return e;
 }
References ET_EVENTS, G_SetOrigin(), G_Spawn(), qtrue, SnapVector, trap_LinkEntity(), and VectorCopy.
Referenced by AddTeamScore(), ClientBegin(), ClientDisconnect(), ClientRespawn(), G_Sound(), SendPendingPredictableEvents(), TeleportPlayer(), and UserHitscan_Fire().
G_TouchSolids()
void G_TouchSolids (gentity_t * ent)
G_TouchTriggers()
void G_TouchTriggers (gentity_t * ent)
Definition at line 146 of file g_active.c.
{
     int         i, num;
     int         touch[MAX_GENTITIES];
     gentity_t   *hit;
     trace_t     trace;
     vec3_t      mins, maxs;
     static vec3_t   range = { 40, 40, 52 };
     if ( !ent->client ) {
         return;
     }
     VectorSubtract( ent->client->ps.origin, range, mins );
     VectorAdd( ent->client->ps.origin, range, maxs );
     num = trap_EntitiesInBox( mins, maxs, touch, MAX_GENTITIES );
     // can't use ent->absmin, because that has a one unit pad
     VectorAdd( ent->client->ps.origin, ent->r.mins, mins );
     VectorAdd( ent->client->ps.origin, ent->r.maxs, maxs );
     for ( i=0 ; i<num ; i++ ) {
         hit = &g_entities[touch[i]];
         if ( !hit->touch && !ent->touch ) {
             continue;
         }
         if ( !( hit->r.contents & CONTENTS_TRIGGER ) ) {
             continue;
         }
         // ignore most entities if a spectator
         if ( ent->client->sess.sessionTeam == TEAM_SPECTATOR ) {
             if ( hit->s.eType != ET_TELEPORT_TRIGGER &&
                 // this is ugly but adding a new ET_? type will
                 // most likely cause network incompatibilities
                 hit->touch != Touch_DoorTrigger) {
                 continue;
             }
         }
         if ( !trap_EntityContact( mins, maxs, hit ) ) {
                 continue;
         }
         memset( &trace, 0, sizeof(trace) );
         if ( hit->touch ) {
             hit->touch (hit, ent, &trace);
         }
     }
     // if we didn't touch a jump pad this pmove frame
     if ( ent->client->ps.jumppad_frame != ent->client->ps.pmove_framecount ) {
         ent->client->ps.jumppad_frame = 0;
         ent->client->ps.jumppad_ent = 0;
     }
 }
References CONTENTS_TRIGGER, ET_TELEPORT_TRIGGER, g_entities, MAX_GENTITIES, TEAM_SPECTATOR, Touch_DoorTrigger(), trap_EntitiesInBox(), trap_EntityContact(), VectorAdd, and VectorSubtract.
Referenced by ClientThink_real(), and SpectatorThink().
G_UseTargets()
void G_UseTargets (gentity_t * ent, gentity_t * activator)
Definition at line 235 of file g_utils.c.
{
     gentity_t       *t;
     if ( !ent ) {
         return;
     }
     if (ent->targetShaderName && ent->targetShaderNewName) {
         float f = level.time * 0.001;
         AddRemap(ent->targetShaderName, ent->targetShaderNewName, f);
         trap_SetConfigstring(CS_SHADERSTATE, BuildShaderStateConfig());
     }
     if ( !ent->target ) {
         return;
     }
     t = NULL;
     while ( (t = G_Find (t, FOFS(targetname), ent->target)) != NULL ) {
         if ( t == ent ) {
             G_Printf ("WARNING: Entity used itself.\n");
         } else {
             if ( t->use ) {
                 t->use (t, ent, activator);
             }
         }
         if ( !ent->inuse ) {
             G_Printf("entity was removed while using targets\n");
             return;
         }
     }
 }
References AddRemap(), BuildShaderStateConfig(), CS_SHADERSTATE, FOFS, G_Find(), G_Printf(), NULL, and trap_SetConfigstring().
Referenced by func_timer_think(), multi_trigger(), Reached_BinaryMover(), Reached_Train(), target_relay_use(), Think_Target_Delay(), and trigger_always_think().
G_weapPhys_Parse()
qboolean G_weapPhys_Parse (char * filename, int clientNum)
Definition at line 2324 of file g_weapPhysParser.c.
{
     g_weapPhysParser_t      parser;
     g_weapPhysScanner_t     *scanner;
     g_weapPhysToken_t       *token;
     int                     i;
     int                     *weaponMask;
     // Initialize the parser
     memset( &parser, 0, sizeof(parser) );
     scanner = &parser.scanner;
     token = &parser.token;
     g_weapPhysRecursionDepth = 0;
     // Clear the weapons here, so we are never stuck with 'ghost' weapons
     // if an error occurs in the parse.
     weaponMask = G_FindUserWeaponMask( clientNum );
     *weaponMask = 0;
     // Initialize the scanner by loading the file
     G_weapPhys_LoadFile( scanner, filename );
     // Get the very first token initialized. If
     // it is an end of file token, we will not parse
     // the empty file but will instead exit with true.
     if ( !G_weapPhys_NextSym( scanner, token ) ) {
         if ( token->tokenSym != TOKEN_EOF ) {
             return qfalse;
         } else {
             return qtrue;
         }
     }
     // Parse the imports
     if ( !G_weapPhys_ParseImports( &parser ) ) {
         return qfalse;
     }
     // Pre-Parse the definitions
     if ( !G_weapPhys_PreParseDefinitions( &parser ) ) {
         return qfalse;
     }
     // Parse the link to the weapons
     if ( !G_weapPhys_ParseLinks( &parser ) ) {
         return qfalse;
     }
     // Respond with an error if something is trailing the
     // link definitions.
     if ( token->tokenSym != TOKEN_EOF ) {
         G_weapPhys_ErrorHandle( ERROR_UNEXPECTED_SYMBOL, scanner, token->stringval, NULL );
         return qfalse;
     }
     // Work through the link table, parsing and assigning the definitions
     // as we go.
     for ( i = 0; i < MAX_LINKS; i++ ) {
         if ( !parser.linkRef[i].active ) {
             continue;
         }
         // Empty the buffer.
         memset( &g_weapPhysBuffer, 0, sizeof(g_weapPhysBuffer) );
         if ( g_verboseParse.integer ) {
             G_Printf( "Processing weapon nr %i, primary '%s'.\n", i+1, parser.linkRef[i].pri_refname );
         }
         if ( !G_weapPhys_ParseDefinition( &parser, parser.linkRef[i].pri_refname, NULL ) ) {
             return qfalse;
         }
         G_weapPhys_StoreBuffer( clientNum, i );
         // Empty the buffer.
         memset( &g_weapPhysBuffer, 0, sizeof(g_weapPhysBuffer) );
         if ( strcmp( parser.linkRef[i].sec_refname, "" ) ) {
             if ( g_verboseParse.integer ) {
                 G_Printf("Processing weapon nr %i, secondary '%s'.\n", i+1, parser.linkRef[i].sec_refname );
             }
             if ( !G_weapPhys_ParseDefinition( &parser, parser.linkRef[i].sec_refname, NULL ) ) {
                 return qfalse;
             }
             // Piggyback the alternate fire present flag in the buffer of the alternate fire
             // to let G_weapPhys_StoreBuffer enable this flag on the primary fire.
             g_weapPhysBuffer.general_bitflags |= WPF_ALTWEAPONPRESENT;
         }
         G_weapPhys_StoreBuffer( clientNum, i + ALTWEAPON_OFFSET );
         // If everything went okay, we add the weapon to the availability mask
         *weaponMask |= ( 1 << (i+1) );
         if ( g_verboseParse.integer ) {
             G_Printf("Added weapon nr %i to availabilty mask. New mask reads: %i\n", i+1, *weaponMask );
         }
     }
     if ( g_verboseParse.integer ) {
         G_Printf("Parse completed succesfully.\n");
     }
     return qtrue;
 }
References g_weapPhysLinkRef_t::active, ALTWEAPON_OFFSET, ERROR_UNEXPECTED_SYMBOL, G_FindUserWeaponMask(), G_Printf(), g_verboseParse, G_weapPhys_ErrorHandle(), G_weapPhys_LoadFile(), G_weapPhys_NextSym(), G_weapPhys_ParseDefinition(), G_weapPhys_ParseImports(), G_weapPhys_ParseLinks(), G_weapPhys_PreParseDefinitions(), G_weapPhys_StoreBuffer(), g_weapPhysBuffer, g_weapPhysRecursionDepth, g_userWeapon_t::general_bitflags, vmCvar_t::integer, g_weapPhysParser_t::linkRef, MAX_LINKS, NULL, g_weapPhysLinkRef_t::pri_refname, qfalse, qtrue, g_weapPhysParser_t::scanner, g_weapPhysLinkRef_t::sec_refname, g_weapPhysParser_t::token, token, TOKEN_EOF, and WPF_ALTWEAPONPRESENT.
Referenced by ClientUserinfoChanged().
G_weapPhysParser_MainParse()
qboolean G_weapPhysParser_MainParse (char * filename, int clientNum, int * weaponMask)
G_WriteSessionData()
void G_WriteSessionData (void)
Definition at line 180 of file g_session.c.
{
     int     i;
     trap_Cvar_Set( "session", va("%i", g_gametype.integer) );
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if ( level.clients[i].pers.connected == CON_CONNECTED ) {
             G_WriteClientSessionData( &level.clients[i] );
         }
     }
 }
References CON_CONNECTED, g_gametype, G_WriteClientSessionData(), vmCvar_t::integer, trap_Cvar_Set(), and va().
Referenced by ExitLevel(), and G_ShutdownGame().
InitBodyQue()
void InitBodyQue (void)
Definition at line 334 of file g_client.c.
{
     int     i;
     gentity_t   *ent;
     level.bodyQueIndex = 0;
     for (i=0; i<BODY_QUEUE_SIZE ; i++) {
         ent = G_Spawn();
         ent->classname = "bodyque";
         ent->neverFree = qtrue;
         level.bodyQue[i] = ent;
     }
 }
References BODY_QUEUE_SIZE, G_Spawn(), and qtrue.
Referenced by G_InitGame().
InitClientPersistant()
void InitClientPersistant (gclient_t * client)
InitClientResp()
void InitClientResp (gclient_t * client)
MoveClientToIntermission()
void MoveClientToIntermission (gentity_t * client)
Definition at line 845 of file g_main.c.
{
     // take out of follow mode if needed
     if ( ent->client->sess.spectatorState == SPECTATOR_FOLLOW ) {
         StopFollowing( ent );
     }
     FindIntermissionPoint();
     // move to the spot
     VectorCopy( level.intermission_origin, ent->s.origin );
     VectorCopy( level.intermission_origin, ent->client->ps.origin );
     VectorCopy (level.intermission_angle, ent->client->ps.viewangles);
     ent->client->ps.pm_type = PM_INTERMISSION;
     // clean up powerup info
     memset( ent->client->ps.powerups, 0, sizeof(ent->client->ps.powerups) );
     ent->client->ps.eFlags = 0;
     ent->s.eFlags = 0;
     ent->s.eType = ET_GENERAL;
     ent->s.modelindex = 0;
     ent->s.loopSound = 0;
     ent->s.event = 0;
     ent->r.contents = 0;
 }
References ET_GENERAL, FindIntermissionPoint(), PM_INTERMISSION, SPECTATOR_FOLLOW, StopFollowing(), and VectorCopy.
Referenced by BeginIntermission(), and ClientSpawn().
OnSameTeam()
qboolean OnSameTeam (gentity_t * ent1, gentity_t * ent2)
Definition at line 153 of file g_team.c.
{
     if ( !ent1->client || !ent2->client ) {
         return qfalse;
     }
     if ( g_gametype.integer < GT_TEAM ) {
         return qfalse;
     }
     if ( ent1->client->sess.sessionTeam == ent2->client->sess.sessionTeam ) {
         return qtrue;
     }
     return qfalse;
 }
References g_gametype, GT_TEAM, vmCvar_t::integer, qfalse, and qtrue.
Referenced by G_RankDamage(), G_SayTo(), G_VoiceTo(), Think_CylinderHoming(), Think_Homing(), and Think_ProxDet().
PickTeam()
team_t PickTeam (int ignoreClientNum)
Definition at line 475 of file g_client.c.
{
     int     counts[TEAM_NUM_TEAMS];
     counts[TEAM_BLUE] = TeamCount( ignoreClientNum, TEAM_BLUE );
     counts[TEAM_RED] = TeamCount( ignoreClientNum, TEAM_RED );
     if ( counts[TEAM_BLUE] > counts[TEAM_RED] ) {
         return TEAM_RED;
     }
     if ( counts[TEAM_RED] > counts[TEAM_BLUE] ) {
         return TEAM_BLUE;
     }
     // equal team count, so join the team with the lowest score
     if ( level.teamScores[TEAM_BLUE] > level.teamScores[TEAM_RED] ) {
         return TEAM_RED;
     }
     return TEAM_BLUE;
 }
References TEAM_BLUE, TEAM_NUM_TEAMS, TEAM_RED, and TeamCount().
Referenced by G_InitSessionData(), and SetTeam().
Release_UserWeapon()
void Release_UserWeapon (gentity_t * self, qboolean altfire)
Definition at line 648 of file g_usermissile.c.
{
     // Work on primary or alternate fire.
     if ( altfire ) {
         // If the altfired entity exists, then destroy it and null the pointer (just incase).
         if ( self->contAltfire_ent ) {
             G_FreeEntity( self->contAltfire_ent );
             self->contAltfire_ent = NULL;
         }
     } else {
         // If the fired entity exists, then destroy it and null the pointer (just incase).
         if ( self->contFire_ent ) {
             G_FreeEntity( self->contAltfire_ent );
             self->contAltfire_ent = NULL;
         }
     }
 }
References G_FreeEntity(), and NULL.
SelectSpawnPoint()
gentity_t* SelectSpawnPoint (vec3_t avoidPoint, vec3_t origin, vec3_t angles)
Definition at line 244 of file g_client.c.
{
     return SelectRandomFurthestSpawnPoint( avoidPoint, origin, angles );
     /*
     gentity_t   *spot;
     gentity_t   *nearestSpot;
     nearestSpot = SelectNearestDeathmatchSpawnPoint( avoidPoint );
     spot = SelectRandomDeathmatchSpawnPoint ( );
     if ( spot == nearestSpot ) {
         // roll again if it would be real close to point of death
         spot = SelectRandomDeathmatchSpawnPoint ( );
         if ( spot == nearestSpot ) {
             // last try
             spot = SelectRandomDeathmatchSpawnPoint ( );
         }
     }
     // find a single player start spot
     if (!spot) {
         G_Error( "Couldn't find a spawn point" );
     }
     VectorCopy (spot->s.origin, origin);
     origin[2] += 9;
     VectorCopy (spot->s.angles, angles);
     return spot;
     */
 }
References angles, and SelectRandomFurthestSpawnPoint().
Referenced by ClientSpawn(), FindIntermissionPoint(), SelectCTFSpawnPoint(), and SelectInitialSpawnPoint().
SendScoreboardMessageToAllClients()
void QDECL void SendScoreboardMessageToAllClients (void)
Definition at line 827 of file g_main.c.
{
     int     i;
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if ( level.clients[ i ].pers.connected == CON_CONNECTED ) {
             DeathmatchScoreboardMessage( g_entities + i );
         }
     }
 }
References CON_CONNECTED, DeathmatchScoreboardMessage(), and g_entities.
Referenced by BeginIntermission(), and CalculateRanks().
SetClientViewAngle()
void SetClientViewAngle (gentity_t * ent, vec3_t angle)
Definition at line 384 of file g_client.c.
{
     int         i;
     // set the delta angle
     for (i=0 ; i<3 ; i++) {
         int     cmdAngle;
         cmdAngle = ANGLE2SHORT(angle[i]);
         ent->client->ps.delta_angles[i] = cmdAngle - ent->client->pers.cmd.angles[i];
     }
     VectorCopy( angle, ent->s.angles );
     VectorCopy (ent->s.angles, ent->client->ps.viewangles);
 }
References ANGLE2SHORT, and VectorCopy.
Referenced by ClientSpawn(), and TeleportPlayer().
SetLeader()
void SetLeader (int team, int client)
Definition at line 1318 of file g_main.c.
{
     int i;
     if ( level.clients[client].pers.connected == CON_DISCONNECTED ) {
         PrintTeam(team, va("print \"%s is not connected\n\"", level.clients[client].pers.netname) );
         return;
     }
     if (level.clients[client].sess.sessionTeam != team) {
         PrintTeam(team, va("print \"%s is not on the team anymore\n\"", level.clients[client].pers.netname) );
         return;
     }
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if (level.clients[i].sess.sessionTeam != team)
             continue;
         if (level.clients[i].sess.teamLeader) {
             level.clients[i].sess.teamLeader = qfalse;
             ClientUserinfoChanged(i);
         }
     }
     level.clients[client].sess.teamLeader = qtrue;
     ClientUserinfoChanged( client );
     PrintTeam(team, va("print \"%s is the new team leader\n\"", level.clients[client].pers.netname) );
 }
References ClientUserinfoChanged(), CON_DISCONNECTED, PrintTeam(), qfalse, qtrue, and va().
Referenced by CheckTeamVote(), and SetTeam().
SetTargetPos()
void SetTargetPos (gentity_t * ent)
SetTeam()
void SetTeam (gentity_t * ent, char * s)
Definition at line 239 of file g_cmds.c.
{
     int                 team, oldTeam;
     gclient_t           *client;
     int                 clientNum;
     spectatorState_t    specState;
     int                 specClient;
     int                 teamLeader;
     //
     // see what change is requested
     //
     client = ent->client;
     clientNum = client - level.clients;
     specClient = 0;
     specState = SPECTATOR_NOT;
     if ( !Q_stricmp( s, "scoreboard" ) || !Q_stricmp( s, "score" )  ) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_SCOREBOARD;
     } else if ( !Q_stricmp( s, "follow1" ) ) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FOLLOW;
         specClient = -1;
     } else if ( !Q_stricmp( s, "follow2" ) ) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FOLLOW;
         specClient = -2;
     } else if ( !Q_stricmp( s, "spectator" ) || !Q_stricmp( s, "s" ) ) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FREE;
     } else if ( g_gametype.integer >= GT_TEAM ) {
         // if running a team game, assign player to one of the teams
         specState = SPECTATOR_NOT;
         if ( !Q_stricmp( s, "red" ) || !Q_stricmp( s, "r" ) ) {
             team = TEAM_RED;
         } else if ( !Q_stricmp( s, "blue" ) || !Q_stricmp( s, "b" ) ) {
             team = TEAM_BLUE;
         } else {
             // pick the team with the least number of players
             team = PickTeam( clientNum );
         }
         if ( g_teamForceBalance.integer  ) {
             int     counts[TEAM_NUM_TEAMS];
             counts[TEAM_BLUE] = TeamCount( clientNum, TEAM_BLUE );
             counts[TEAM_RED] = TeamCount( clientNum, TEAM_RED );
             // We allow a spread of two
             if ( team == TEAM_RED && counts[TEAM_RED] - counts[TEAM_BLUE] > 1 ) {
                 trap_SendServerCommand( clientNum,
                     "cp \"Red team has too many players.\n\"" );
                 return; // ignore the request
             }
             if ( team == TEAM_BLUE && counts[TEAM_BLUE] - counts[TEAM_RED] > 1 ) {
                 trap_SendServerCommand( clientNum,
                     "cp \"Blue team has too many players.\n\"" );
                 return; // ignore the request
             }
             // It's ok, the team we are switching to has less or same number of players
         }
     } else {
         // force them to spectators if there aren't any spots free
         team = TEAM_FREE;
     }
     // override decision if limiting the players
     if ( (g_gametype.integer == GT_TOURNAMENT)
         && level.numNonSpectatorClients >= 2 ) {
         team = TEAM_SPECTATOR;
     } else if ( g_maxGameClients.integer > 0 &&
         level.numNonSpectatorClients >= g_maxGameClients.integer ) {
         team = TEAM_SPECTATOR;
     }
     //
     // decide if we will allow the change
     //
     oldTeam = client->sess.sessionTeam;
     if ( team == oldTeam && team != TEAM_SPECTATOR ) {
         return;
     }
     // he starts at 'base'
     client->pers.teamState.state = TEAM_BEGIN;
     if ( oldTeam != TEAM_SPECTATOR ) {
         // Kill him (makes sure he loses flags, etc)
         ent->client->ps.powerLevel[plCurrent] = ent->powerLevelTotal = 0;
     }
     // they go to the end of the line for tournements
     if(team == TEAM_SPECTATOR && oldTeam != team)
         AddTournamentQueue(client);
     client->sess.sessionTeam = team;
     client->sess.spectatorState = specState;
     client->sess.spectatorClient = specClient;
     client->sess.teamLeader = qfalse;
     if ( team == TEAM_RED || team == TEAM_BLUE ) {
         teamLeader = TeamLeader( team );
         // if there is no team leader
         if ( teamLeader == -1 ) {
             SetLeader( team, clientNum );
         }
     }
     // make sure there is a team leader on the team the player came from
     if ( oldTeam == TEAM_RED || oldTeam == TEAM_BLUE ) {
         CheckTeamLeader( oldTeam );
     }
     BroadcastTeamChange( client, oldTeam );
     // get and distribute relevent paramters
     ClientUserinfoChanged( clientNum );
     ClientBegin( clientNum );
 }
References AddTournamentQueue(), BroadcastTeamChange(), CheckTeamLeader(), ClientBegin(), ClientUserinfoChanged(), g_gametype, g_maxGameClients, g_teamForceBalance, GT_TEAM, GT_TOURNAMENT, vmCvar_t::integer, PickTeam(), plCurrent, Q_stricmp(), qfalse, SetLeader(), SPECTATOR_FOLLOW, SPECTATOR_FREE, SPECTATOR_NOT, SPECTATOR_SCOREBOARD, TEAM_BEGIN, TEAM_BLUE, TEAM_FREE, TEAM_NUM_TEAMS, TEAM_RED, TEAM_SPECTATOR, TeamCount(), TeamLeader(), and trap_SendServerCommand().
Referenced by AddTournamentPlayer(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_Team_f(), G_RankRunFrame(), RemoveTournamentLoser(), RemoveTournamentWinner(), and Svcmd_ForceTeam_f().
setupTiers()
void setupTiers (gclient_t * client)
Definition at line 218 of file g_tiers.c.
{
     int i;
     tierConfig_g *tier;
     char *modelName;
     char *skinName;
     char *tierPath;
     char tempPath[MAX_QPATH];
     modelName = client->modelName;
     skinName = strchr(modelName,'/');
     if(!skinName){skinName = "default";}
     for(i=0;i<8;i++){
         tier = &client->tiers[i];
         memset(tier,0,sizeof(tierConfig_g));
         tierPath = va("players/%s/Tier%i/%s/",modelName,i+1,skinName);
         parseTier("players/TierDefault.config",tier);
         parseTier(strcat(tierPath,"Tier.config"),tier);
     }
     syncTier(client);
 }
References MAX_QPATH, parseTier(), syncTier(), and va().
Referenced by ClientUserinfoChanged().
SnapVectorTowards()
void SnapVectorTowards (vec3_t v, vec3_t to)
Definition at line 55 of file g_weapon.c.
{
     int index = 0;
     int length = sizeof(from)/sizeof(from[0]);
     for(;index<length;++index){
         from[index] = to[index]<=from[index] ? (int)from[index] : (int)from[index]+1;
     }
 }
References int().
Referenced by G_ExplodeUserWeapon(), G_ImpactUserWeapon(), G_RunUserMissile(), and UserHitscan_Fire().
SpawnModelsOnVictoryPads()
void SpawnModelsOnVictoryPads (void)
Definition at line 249 of file g_arenas.c.
 {}
Referenced by BeginIntermission().
SpotWouldTelefrag()
qboolean SpotWouldTelefrag (gentity_t * spot)
Definition at line 72 of file g_client.c.
{
     int         i, num;
     int         touch[MAX_GENTITIES];
     gentity_t   *hit;
     vec3_t      mins, maxs;
     VectorAdd( spot->s.origin, playerMins, mins );
     VectorAdd( spot->s.origin, playerMaxs, maxs );
     num = trap_EntitiesInBox( mins, maxs, touch, MAX_GENTITIES );
     for (i=0 ; i<num ; i++) {
         hit = &g_entities[touch[i]];
         if ( hit->client) {
             return qtrue;
         }
     }
     return qfalse;
 }
References g_entities, MAX_GENTITIES, playerMaxs, playerMins, qfalse, qtrue, trap_EntitiesInBox(), and VectorAdd.
Referenced by SelectInitialSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectRandomFurthestSpawnPoint(), and SelectRandomTeamSpawnPoint().
StopFollowing()
void StopFollowing (gentity_t * ent)
Definition at line 367 of file g_cmds.c.
{
     ent->client->ps.persistant[ PERS_TEAM ] = TEAM_SPECTATOR;
     ent->client->sess.sessionTeam = TEAM_SPECTATOR;
     ent->client->sess.spectatorState = SPECTATOR_FREE;
     ent->client->ps.pm_flags &= ~PMF_FOLLOW;
     ent->client->ps.clientNum = ent - g_entities;
 }
References g_entities, PERS_TEAM, PMF_FOLLOW, SPECTATOR_FREE, and TEAM_SPECTATOR.
Referenced by ClientDisconnect(), Cmd_Follow_f(), and MoveClientToIntermission().
Svcmd_AbortPodium_f()
void Svcmd_AbortPodium_f (void)
Definition at line 257 of file g_arenas.c.
{
     if( g_gametype.integer != GT_SINGLE_PLAYER ) {
         return;
     }
     if( podium1 ) {
         podium1->nextthink = level.time;
         podium1->think = CelebrateStop;
     }
 }
References CelebrateStop(), g_gametype, GT_SINGLE_PLAYER, vmCvar_t::integer, and podium1.
Referenced by ConsoleCommand().
Svcmd_GameMem_f()
void Svcmd_GameMem_f (void)
Definition at line 59 of file g_mem.c.
{
     G_Printf( "Game memory status: %i out of %i bytes allocated\n", allocPoint, POOLSIZE );
 }
References allocPoint, G_Printf(), and POOLSIZE.
Referenced by ConsoleCommand().
syncTier()
void syncTier (gclient_t * client)
Definition at line 3 of file g_tiers.c.
{
     tierConfig_g *tier;
     playerState_t *ps;
     ps = &client->ps;
     tier = &client->tiers[ps->powerLevel[plTierCurrent]];
     ps->breakLimitRate = (float)tier->breakLimitRate * g_breakLimitRate.value;
     ps->options = tier->capabilities | (ps->options & advancedMelee) | (ps->options & advancedFlight) | (ps->options & pointGravity);
     ps->stats[stTransformFirstDuration] = tier->transformFirstDuration;
     ps->stats[stTransformFirstEffectMaximum] = tier->transformFirstEffectMaximum;
     ps->stats[stTransformFirstHealth] = tier->transformFirstHealth;
     ps->stats[stTransformFirstFatigue] = tier->transformFirstFatigue;
     ps->stats[stTransformDuration] = tier->transformDuration;
     ps->stats[stTransformFatigue] = tier->transformFatigue;
     ps->stats[stTransformHealth] = tier->transformHealth;
     ps->stats[stTransformEffectMaximum] = tier->transformEffectMaximum;
     ps->baseStats[stKnockbackPower] = tier->knockbackPower;
     ps->baseStats[stSpeed] = tier->speed;
     ps->baseStats[stZanzokenDistance] = tier->zanzokenDistance;
     ps->baseStats[stZanzokenQuickDistance] = g_quickZanzokenDistance.value != -1.0 ? g_quickZanzokenDistance.value : tier->zanzokenQuickDistance;
     ps->baseStats[stZanzokenSpeed] = tier->zanzokenSpeed;
     ps->baseStats[stZanzokenCost] = tier->zanzokenCost;
     ps->baseStats[stZanzokenQuickCost] = g_quickZanzokenCost.value != -1.0 ? g_quickZanzokenCost.value : tier->zanzokenQuickCost;
     ps->baseStats[stBoostCost] = tier->boostCost;
     ps->baseStats[stFatigueRecovery] = tier->fatigueRecovery;
     ps->baseStats[stTransformSubsequentDuration] = tier->transformSubsequentDuration;
     ps->baseStats[stTransformSubsequentFatigueScale] = tier->transformSubsequentFatigueScale;
     ps->baseStats[stTransformSubsequentHealthScale] = tier->transformSubsequentHealthScale;
     ps->baseStats[stTransformSubsequentMaximumScale] = tier->transformSubsequentMaximumScale;
     ps->baseStats[stAirBrakeCost] = tier->airBrakeCost;
     ps->baseStats[stMeleeAttack] = tier->meleeAttack;
     ps->baseStats[stEnergyAttack] = tier->energyAttackDamage;
     ps->baseStats[stDefenseMelee] = tier->defenseMelee;
     ps->baseStats[stDefenseEnergy] = tier->defenseEnergy;
     ps->baseStats[stEnergyAttackCost] = tier->energyAttackCost;
     ps->powerLevel[plDrainCurrent] = tier->effectCurrent;
     ps->powerLevel[plDrainFatigue] = tier->effectFatigue;
     ps->powerLevel[plDrainHealth] = tier->effectHealth;
     ps->powerLevel[plDrainMaximum] = tier->effectMaximum;
 }
References advancedFlight, advancedMelee, tierConfig_g::airBrakeCost, tierConfig_g::boostCost, tierConfig_g::breakLimitRate, tierConfig_g::capabilities, tierConfig_g::defenseEnergy, tierConfig_g::defenseMelee, tierConfig_g::effectCurrent, tierConfig_g::effectFatigue, tierConfig_g::effectHealth, tierConfig_g::effectMaximum, tierConfig_g::energyAttackCost, tierConfig_g::energyAttackDamage, tierConfig_g::fatigueRecovery, g_breakLimitRate, g_quickZanzokenCost, g_quickZanzokenDistance, tierConfig_g::knockbackPower, tierConfig_g::meleeAttack, plDrainCurrent, plDrainFatigue, plDrainHealth, plDrainMaximum, plTierCurrent, pointGravity, tierConfig_g::speed, stAirBrakeCost, stBoostCost, stDefenseEnergy, stDefenseMelee, stEnergyAttack, stEnergyAttackCost, stFatigueRecovery, stKnockbackPower, stMeleeAttack, stSpeed, stTransformDuration, stTransformEffectMaximum, stTransformFatigue, stTransformFirstDuration, stTransformFirstEffectMaximum, stTransformFirstFatigue, stTransformFirstHealth, stTransformHealth, stTransformSubsequentDuration, stTransformSubsequentFatigueScale, stTransformSubsequentHealthScale, stTransformSubsequentMaximumScale, stZanzokenCost, stZanzokenDistance, stZanzokenQuickCost, stZanzokenQuickDistance, stZanzokenSpeed, tierConfig_g::transformDuration, tierConfig_g::transformEffectMaximum, tierConfig_g::transformFatigue, tierConfig_g::transformFirstDuration, tierConfig_g::transformFirstEffectMaximum, tierConfig_g::transformFirstFatigue, tierConfig_g::transformFirstHealth, tierConfig_g::transformHealth, tierConfig_g::transformSubsequentDuration, tierConfig_g::transformSubsequentFatigueScale, tierConfig_g::transformSubsequentHealthScale, tierConfig_g::transformSubsequentMaximumScale, vmCvar_t::value, tierConfig_g::zanzokenCost, tierConfig_g::zanzokenDistance, tierConfig_g::zanzokenQuickCost, tierConfig_g::zanzokenQuickDistance, and tierConfig_g::zanzokenSpeed.
Referenced by ClientEvents(), and setupTiers().
Team_CheckDroppedItem()
void Team_CheckDroppedItem (gentity_t * dropped)
Definition at line 216 of file g_team.c.
{
 }
TeamCount()
team_t TeamCount (int ignoreClientNum, int team)
Definition at line 426 of file g_client.c.
{
     int     i;
     int     count = 0;
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if ( i == ignoreClientNum ) {
             continue;
         }
         if ( level.clients[i].pers.connected == CON_DISCONNECTED ) {
             continue;
         }
         if ( level.clients[i].sess.sessionTeam == team ) {
             count++;
         }
     }
     return count;
 }
References CON_DISCONNECTED.
Referenced by CheckTournament(), PickTeam(), and SetTeam().
TeamLeader()
int TeamLeader (int team)
Definition at line 452 of file g_client.c.
{
     int     i;
     for ( i = 0 ; i < level.maxclients ; i++ ) {
         if ( level.clients[i].pers.connected == CON_DISCONNECTED ) {
             continue;
         }
         if ( level.clients[i].sess.sessionTeam == team ) {
             if ( level.clients[i].sess.teamLeader )
                 return i;
         }
     }
     return -1;
 }
References CON_DISCONNECTED.
Referenced by SetTeam().
TeleportPlayer()
void TeleportPlayer (gentity_t * player, vec3_t origin, vec3_t angles)
Definition at line 79 of file g_misc.c.
{
     gentity_t   *tent;
     qboolean noAngles;
     noAngles = (angles[0] > 999999.0);
     // use temp events at source and destination to prevent the effect
     // from getting dropped by a second player event
     if ( player->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         tent = G_TempEntity( player->client->ps.origin, EV_PLAYER_TELEPORT_OUT );
         tent->s.clientNum = player->s.clientNum;
         tent = G_TempEntity( origin, EV_PLAYER_TELEPORT_IN );
         tent->s.clientNum = player->s.clientNum;
     }
     // unlink to make sure it can't possibly interfere with G_KillBox
     trap_UnlinkEntity (player);
     VectorCopy ( origin, player->client->ps.origin );
     player->client->ps.origin[2] += 1;
     if (!noAngles) {
     // spit the player out
     AngleVectors( angles, player->client->ps.velocity, NULL, NULL );
     VectorScale( player->client->ps.velocity, 400, player->client->ps.velocity );
     player->client->ps.pm_time = 160;       // hold time
     player->client->ps.pm_flags |= PMF_TIME_KNOCKBACK;
     // set angles
     SetClientViewAngle(player, angles);
     }
     // toggle the teleport bit so the client knows to not lerp
     player->client->ps.eFlags ^= EF_TELEPORT_BIT;
     // kill anything at the destination
     if ( player->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         G_KillBox (player);
     }
     // save results of pmove
     BG_PlayerStateToEntityState( &player->client->ps, &player->s,qtrue );
     // use the precise origin for linking
     VectorCopy( player->client->ps.origin, player->r.currentOrigin );
     if ( player->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         trap_LinkEntity (player);
     }
 }
References angles, AngleVectors(), BG_PlayerStateToEntityState(), EF_TELEPORT_BIT, EV_PLAYER_TELEPORT_IN, EV_PLAYER_TELEPORT_OUT, G_KillBox(), G_TempEntity(), NULL, PMF_TIME_KNOCKBACK, qtrue, SetClientViewAngle(), TEAM_SPECTATOR, trap_LinkEntity(), trap_UnlinkEntity(), VectorCopy, and VectorScale.
Referenced by Cmd_SetViewpos_f(), target_teleporter_use(), Touch_DoorTriggerSpectator(), and trigger_teleporter_touch().
Touch_DoorTrigger()
void Touch_DoorTrigger (gentity_t * ent, gentity_t * other, trace_t * trace)
Definition at line 798 of file g_mover.c.
{
     if ( other->client && other->client->sess.sessionTeam == TEAM_SPECTATOR ) {
         // if the door is not open and not opening
         if ( ent->parent->moverState != MOVER_1TO2 &&
             ent->parent->moverState != MOVER_POS2) {
             Touch_DoorTriggerSpectator( ent, other, trace );
         }
     }
     else if ( ent->parent->moverState != MOVER_1TO2 ) {
         Use_BinaryMover( ent->parent, ent, other );
     }
 }
References MOVER_1TO2, MOVER_POS2, TEAM_SPECTATOR, Touch_DoorTriggerSpectator(), and Use_BinaryMover().
Referenced by G_TouchTriggers(), and Think_SpawnNewDoorTrigger().
trap_AdjustAreaPortalState()
void trap_AdjustAreaPortalState (gentity_t * ent, qboolean open)
Definition at line 167 of file g_syscalls.c.
{
     syscall( G_ADJUST_AREA_PORTAL_STATE, ent, open );
 }
References G_ADJUST_AREA_PORTAL_STATE.
Referenced by Reached_BinaryMover(), and Use_BinaryMover().
trap_AreasConnected()
qboolean trap_AreasConnected (int area1, int area2)
Definition at line 171 of file g_syscalls.c.
{
     return syscall( G_AREAS_CONNECTED, area1, area2 );
 }
References G_AREAS_CONNECTED.
trap_Argc()
int trap_Argc (void)
Definition at line 76 of file cg_syscalls.c.
{
     return syscall( CG_ARGC );
 }
trap_Args()
void trap_Args (char * buffer, int bufferLength)
Definition at line 84 of file cg_syscalls.c.
{
     syscall( CG_ARGS, buffer, bufferLength );
 }
References CG_ARGS.
trap_Argv()
void trap_Argv (int n, char * buffer, int bufferLength)
Definition at line 80 of file cg_syscalls.c.
{
     syscall( CG_ARGV, n, buffer, bufferLength );
 }
trap_Cvar_Register()
void trap_Cvar_Register (vmCvar_t * cvar, const char * var_name, const char * value, int flags)
Definition at line 60 of file cg_syscalls.c.
{
     syscall( CG_CVAR_REGISTER, vmCvar, varName, defaultValue, flags );
 }
trap_Cvar_Set()
void trap_Cvar_Set (const char * var_name, const char * value)
Definition at line 68 of file cg_syscalls.c.
{
     syscall( CG_CVAR_SET, var_name, value );
 }
trap_Cvar_Update()
void trap_Cvar_Update (vmCvar_t * cvar)
Definition at line 64 of file cg_syscalls.c.
{
     syscall( CG_CVAR_UPDATE, vmCvar );
 }
trap_Cvar_VariableIntegerValue()
int trap_Cvar_VariableIntegerValue (const char * var_name)
Definition at line 100 of file g_syscalls.c.
{
     return syscall( G_CVAR_VARIABLE_INTEGER_VALUE, var_name );
 }
References G_CVAR_VARIABLE_INTEGER_VALUE.
Referenced by G_InitGame(), G_RankGameOver(), PodiumPlacementThink(), and SpawnPodium().
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
Definition at line 72 of file cg_syscalls.c.
{
     syscall( CG_CVAR_VARIABLESTRINGBUFFER, var_name, buffer, bufsize );
 }
trap_Cvar_VariableValue()
float trap_Cvar_VariableValue (const char * var_name)
Definition at line 67 of file ui_syscalls.c.
{
     floatint_t fi;
     fi.i = syscall( UI_CVAR_VARIABLEVALUE, var_name );
     return fi.f;
 }
trap_DebugPolygonCreate()
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
Definition at line 202 of file g_syscalls.c.
{
     return syscall( G_DEBUG_POLYGON_CREATE, color, numPoints, points );
 }
References G_DEBUG_POLYGON_CREATE.
Referenced by DebugLine().
trap_DebugPolygonDelete()
void trap_DebugPolygonDelete (int id)
Definition at line 206 of file g_syscalls.c.
{
     syscall( G_DEBUG_POLYGON_DELETE, id );
 }
References G_DEBUG_POLYGON_DELETE.
trap_DropClient()
void trap_DropClient (int clientNum, const char * reason)
Definition at line 114 of file g_syscalls.c.
{
     syscall( G_DROP_CLIENT, clientNum, reason );
 }
References G_DROP_CLIENT.
Referenced by ClientInactivityTimer().
trap_EntitiesInBox()
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int * entityList, int maxcount)
Definition at line 183 of file g_syscalls.c.
{
     return syscall( G_ENTITIES_IN_BOX, mins, maxs, list, maxcount );
 }
References G_ENTITIES_IN_BOX.
Referenced by G_MoverPush(), G_TouchTriggers(), G_UserRadiusDamage(), Missile_Smooth(), and SpotWouldTelefrag().
trap_EntityContact()
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
Definition at line 187 of file g_syscalls.c.
{
     return syscall( G_ENTITY_CONTACT, mins, maxs, ent );
 }
References G_ENTITY_CONTACT.
Referenced by G_TouchTriggers().
trap_Error()
void trap_Error (const char * fmt)
Definition at line 49 of file cg_syscalls.c.
 {
     syscall(CG_ERROR, fmt);
     // shut up GCC warning about returning functions, because we know better
     exit(1);
 }
trap_FS_FCloseFile()
void trap_FS_FCloseFile (fileHandle_t f)
Definition at line 100 of file cg_syscalls.c.
{
     syscall( CG_FS_FCLOSEFILE, f );
 }
trap_FS_FOpenFile()
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
Definition at line 88 of file cg_syscalls.c.
{
     return syscall( CG_FS_FOPENFILE, qpath, f, mode );
 }
trap_FS_GetFileList()
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
Definition at line 104 of file cg_syscalls.c.
{
     return syscall( CG_FS_GETFILELIST, path, extension, listbuf, bufsize );
 }
trap_FS_Read()
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
Definition at line 92 of file cg_syscalls.c.
{
     syscall( CG_FS_READ, buffer, len, f );
 }
trap_FS_Write()
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
Definition at line 96 of file cg_syscalls.c.
{
     syscall( CG_FS_WRITE, buffer, len, f );
 }
trap_GetConfigstring()
void trap_GetConfigstring (int num, char * buffer, int bufferSize)
Definition at line 126 of file g_syscalls.c.
{
     syscall( G_GET_CONFIGSTRING, num, buffer, bufferSize );
 }
References G_GET_CONFIGSTRING.
Referenced by G_FindConfigstringIndex().
trap_GetEntityToken()
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
Definition at line 446 of file cg_syscalls.c.
{
     return syscall( CG_GET_ENTITY_TOKEN, buffer, bufferSize );
 }
References CG_GET_ENTITY_TOKEN, and G_GET_ENTITY_TOKEN.
trap_GetServerinfo()
void trap_GetServerinfo (char * buffer, int bufferSize)
Definition at line 138 of file g_syscalls.c.
{
     syscall( G_GET_SERVERINFO, buffer, bufferSize );
 }
References G_GET_SERVERINFO.
Referenced by G_InitGame().
trap_GetUsercmd()
void trap_GetUsercmd (int clientNum, usercmd_t * cmd)
Definition at line 194 of file g_syscalls.c.
{
     syscall( G_GET_USERCMD, clientNum, cmd );
 }
References G_GET_USERCMD.
Referenced by ClientSpawn(), and ClientThink().
trap_GetUserinfo()
void trap_GetUserinfo (int num, char * buffer, int bufferSize)
Definition at line 130 of file g_syscalls.c.
{
     syscall( G_GET_USERINFO, num, buffer, bufferSize );
 }
References G_GET_USERINFO.
Referenced by ClientConnect(), ClientSpawn(), ClientUserinfoChanged(), and Cmd_TeamTask_f().
trap_InPVS()
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
Definition at line 159 of file g_syscalls.c.
{
     return syscall( G_IN_PVS, p1, p2 );
 }
References G_IN_PVS, p1, and p2.
Referenced by Team_GetLocation().
trap_InPVSIgnorePortals()
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Definition at line 163 of file g_syscalls.c.
{
     return syscall( G_IN_PVS_IGNORE_PORTALS, p1, p2 );
 }
References G_IN_PVS_IGNORE_PORTALS, p1, and p2.
trap_LinkEntity()
void trap_LinkEntity (gentity_t * ent)
Definition at line 175 of file g_syscalls.c.
{
     syscall( G_LINKENTITY, ent );
 }
References G_LINKENTITY.
Referenced by ClientSpawn(), ClientThink_real(), G_ExplodeUserWeapon(), G_ImpactUserWeapon(), G_MoverPush(), G_MoverTeam(), G_RunUserMissile(), G_TempEntity(), G_TryPushingEntity(), G_TryPushingProxMine(), hurt_touch(), hurt_use(), InitMover(), SetMoverState(), SP_func_rotating(), SP_misc_model(), SP_misc_portal_camera(), SP_misc_portal_surface(), SP_target_speaker(), SP_trigger_multiple(), SP_trigger_push(), SP_trigger_teleport(), SpawnModelOnVictoryPad(), SpawnPlatTrigger(), SpawnPodium(), TeleportPlayer(), Think_SpawnNewDoorTrigger(), and UserHitscan_Fire().
trap_LocateGameData()
void trap_LocateGameData (gentity_t * gEnts, int numGEntities, int sizeofGEntity_t, playerState_t * gameClients, int sizeofGameClient)
Definition at line 109 of file g_syscalls.c.
{
     syscall( G_LOCATE_GAME_DATA, gEnts, numGEntities, sizeofGEntity_t, clients, sizeofGClient );
 }
References G_LOCATE_GAME_DATA.
Referenced by G_InitGame(), and G_Spawn().
trap_Milliseconds()
int trap_Milliseconds (void)
Definition at line 56 of file cg_syscalls.c.
{
     return syscall( CG_MILLISECONDS );
 }
trap_PointContents()
int trap_PointContents (const vec3_t point, int passEntityNum)
Definition at line 154 of file g_syscalls.c.
{
     return syscall( G_POINT_CONTENTS, point, passEntityNum );
 }
References G_POINT_CONTENTS.
Referenced by ClientThink_real(), and SpectatorThink().
trap_Printf()
void trap_Printf (const char * fmt)
Definition at line 43 of file g_syscalls.c.
{
     syscall( G_PRINT, fmt );
 }
References fmt, and G_PRINT.
Referenced by G_Printf().
trap_RealTime()
int trap_RealTime (qtime_t * qtime)
Definition at line 395 of file cg_syscalls.c.
{
     return syscall( CG_REAL_TIME, qtime );
 }
References CG_REAL_TIME, G_REAL_TIME, and UI_REAL_TIME.
trap_SendConsoleCommand()
void trap_SendConsoleCommand (int exec_when, const char * text)
Definition at line 84 of file g_syscalls.c.
{
     syscall( G_SEND_CONSOLE_COMMAND, exec_when, text );
 }
References G_SEND_CONSOLE_COMMAND.
trap_SendServerCommand()
void trap_SendServerCommand (int clientNum, const char * text)
Definition at line 118 of file g_syscalls.c.
{
     syscall( G_SEND_SERVER_COMMAND, clientNum, text );
 }
References G_SEND_SERVER_COMMAND.
Referenced by __attribute__(), BroadcastTeamChange(), CheatsOk(), CheckTeamVote(), CheckVote(), ClientBegin(), ClientCommand(), ClientConnect(), ClientInactivityTimer(), ClientNumberFromString(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_LevelShot_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamVote_f(), Cmd_Vote_f(), Cmd_Where_f(), ConsoleCommand(), G_RadarUpdateCS(), G_RankRunFrame(), G_SayTo(), G_TeamCommand(), G_VoiceTo(), hurt_touch(), PrintTeam(), SetTeam(), TeamplayInfoMessage(), and Use_Target_Print().
trap_SetBrushModel()
void trap_SetBrushModel (gentity_t * ent, const char * name)
Definition at line 142 of file g_syscalls.c.
{
     syscall( G_SET_BRUSH_MODEL, ent, name );
 }
References G_SET_BRUSH_MODEL.
Referenced by InitTrigger(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_rotating(), SP_func_static(), and SP_func_train().
trap_SetConfigstring()
void trap_SetConfigstring (int num, const char * string)
Definition at line 122 of file g_syscalls.c.
{
     syscall( G_SET_CONFIGSTRING, num, string );
 }
References G_SET_CONFIGSTRING.
Referenced by CalculateRanks(), CheckTeamVote(), CheckTournament(), CheckVote(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_TeamVote_f(), Cmd_Vote_f(), G_FindConfigstringIndex(), G_UseTargets(), LogExit(), SP_worldspawn(), target_location_linkup(), and Team_SetFlagStatus().
trap_SetUserinfo()
void trap_SetUserinfo (int num, const char * buffer)
Definition at line 134 of file g_syscalls.c.
{
     syscall( G_SET_USERINFO, num, buffer );
 }
References G_SET_USERINFO.
Referenced by Cmd_TeamTask_f().
trap_SnapVector()
void trap_SnapVector (float * v)
Definition at line 399 of file cg_syscalls.c.
{
     syscall( CG_SNAPVECTOR, v );
 }
References CG_SNAPVECTOR, and G_SNAPVECTOR.
trap_Trace()
void trap_Trace (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
Definition at line 146 of file g_syscalls.c.
{
     syscall( G_TRACE, results, start, mins, maxs, end, passEntityNum, contentmask );
 }
References G_TRACE.
Referenced by CanDamage(), ClientThink_real(), Fire_UserWeapon(), G_CheckProxMinePosition(), G_RunUserMissile(), G_TestEntityPosition(), SpectatorThink(), Think_CylinderHoming(), Think_Homing(), and UserHitscan_Fire().
trap_UnlinkEntity()
void trap_UnlinkEntity (gentity_t * ent)
Definition at line 179 of file g_syscalls.c.
{
     syscall( G_UNLINKENTITY, ent );
 }
References G_UNLINKENTITY.
Referenced by BodySink(), ClientBegin(), ClientDisconnect(), G_FreeEntity(), G_MoverPush(), G_RunFrame(), hurt_use(), SpectatorThink(), target_laser_off(), and TeleportPlayer().
trigger_teleporter_touch()
void trigger_teleporter_touch (gentity_t * self, gentity_t * other, trace_t * trace)
Definition at line 267 of file g_trigger.c.
{
     gentity_t   *dest;
     if ( !other->client ) {
         return;
     }
     if ( other->client->ps.pm_type == PM_DEAD ) {
         return;
     }
     // Spectators only?
     if ( ( self->spawnflags & 1 ) &&
         other->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         return;
     }
     dest =  G_PickTarget( self->target );
     if (!dest) {
         G_Printf ("Couldn't find teleporter destination\n");
         return;
     }
     TeleportPlayer( other, dest->s.origin, dest->s.angles );
 }
References G_PickTarget(), G_Printf(), PM_DEAD, TEAM_SPECTATOR, and TeleportPlayer().
Referenced by SP_trigger_teleport().
tv()
float* tv (float x, float y, float z)
Definition at line 277 of file g_utils.c.
{
     static  int     index;
     static  vec3_t  vecs[8];
     float   *v;
     // use an array so that multiple tempvectors won't collide
     // for a while
     v = vecs[index];
     index = (index + 1)&7;
     v[0] = x;
     v[1] = y;
     v[2] = z;
     return v;
 }
Referenced by GetTickCount(), and Touch_DoorTriggerSpectator().
UpdateTournamentInfo()
void UpdateTournamentInfo (void)
Definition at line 40 of file g_arenas.c.
{
     int         i;
     gentity_t   *player;
     int         playerClientNum;
     int         n, accuracy, perfect,   msglen;
     char        buf[32];
     char        msg[MAX_STRING_CHARS];
     // find the real player
     player = NULL;
     for (i = 0; i < level.maxclients; i++ ) {
         player = &g_entities[i];
         if ( !player->inuse ) {
             continue;
         }
     }
     // this should never happen!
     if ( !player || i == level.maxclients ) {
         return;
     }
     playerClientNum = i;
     CalculateRanks();
     if ( level.clients[playerClientNum].sess.sessionTeam == TEAM_SPECTATOR ) {
         Com_sprintf( msg, sizeof(msg), "postgame %i %i 0 0 0 0 0 0", level.numNonSpectatorClients, playerClientNum );
     }
     msglen = strlen( msg );
     trap_SendConsoleCommand( EXEC_APPEND, msg );
 }
References CalculateRanks(), Com_sprintf(), EXEC_APPEND, g_entities, MAX_STRING_CHARS, NULL, TEAM_SPECTATOR, and trap_SendConsoleCommand().
Referenced by BeginIntermission().
vectoyaw()
float vectoyaw (const vec3_t vec)
Definition at line 345 of file g_utils.c.
{
     float   yaw;
     if (vec[YAW] == 0 && vec[PITCH] == 0) {
         yaw = 0;
     } else {
         if (vec[PITCH]) {
             yaw = ( atan2( vec[YAW], vec[PITCH]) * 180 / M_PI );
         } else if (vec[YAW] > 0) {
             yaw = 90;
         } else {
             yaw = 270;
         }
         if (yaw < 0) {
             yaw += 360;
         }
     }
     return yaw;
 }
References M_PI, PITCH, vec, and YAW.
Referenced by SpawnPodium().
vtos()
char* vtos (const vec3_t v)
Definition at line 303 of file g_utils.c.
{
     static  int     index;
     static  char    str[8][32];
     char    *s;
     // use an array so that multiple vtos won't collide
     s = str[index];
     index = (index + 1)&7;
     Com_sprintf (s, 32, "(%i %i %i)", (int)v[0], (int)v[1], (int)v[2]);
     return s;
 }
References Com_sprintf().
Referenced by Cmd_Where_f(), SP_func_timer(), SP_func_train(), SP_path_corner(), SP_target_speaker(), SP_target_teleporter(), target_laser_start(), and Think_SetupTrainTargets().
Weapon_HookFree()
void Weapon_HookFree (gentity_t * ent)
Weapon_HookThink()
void Weapon_HookThink (gentity_t * ent)
Variable Documentation
g_allowAdvancedMelee
vmCvar_t g_allowAdvancedMelee
Definition at line 99 of file g_main.c.
g_allowBallFlip
vmCvar_t g_allowBallFlip
Definition at line 93 of file g_main.c.
g_allowBlock
vmCvar_t g_allowBlock
Definition at line 98 of file g_main.c.
g_allowBoost
vmCvar_t g_allowBoost
Definition at line 89 of file g_main.c.
g_allowBreakLimit
vmCvar_t g_allowBreakLimit
Definition at line 95 of file g_main.c.
g_allowFly
vmCvar_t g_allowFly
Definition at line 90 of file g_main.c.
g_allowJump
vmCvar_t g_allowJump
Definition at line 92 of file g_main.c.
g_allowLockon
vmCvar_t g_allowLockon
Definition at line 97 of file g_main.c.
g_allowMelee
vmCvar_t g_allowMelee
Definition at line 96 of file g_main.c.
g_allowOverheal
vmCvar_t g_allowOverheal
Definition at line 94 of file g_main.c.
g_allowScoreboard
vmCvar_t g_allowScoreboard
Definition at line 87 of file g_main.c.
g_allowSoar
vmCvar_t g_allowSoar
Definition at line 88 of file g_main.c.
g_allowTiers
vmCvar_t g_allowTiers
Definition at line 86 of file g_main.c.
g_allowVote
vmCvar_t g_allowVote
Definition at line 71 of file g_main.c.
Referenced by Cmd_CallTeamVote_f(), and Cmd_CallVote_f().
g_allowZanzoken
vmCvar_t g_allowZanzoken
Definition at line 91 of file g_main.c.
g_banIPs
vmCvar_t g_banIPs
Definition at line 74 of file g_main.c.
Referenced by G_ProcessIPBans().
g_breakLimitRate
vmCvar_t g_breakLimitRate
Definition at line 85 of file g_main.c.
Referenced by syncTier().
g_cheats
vmCvar_t g_cheats
Definition at line 51 of file g_main.c.
Referenced by CheatsOk(), and Cmd_SetViewpos_f().
g_debugAlloc
vmCvar_t g_debugAlloc
Definition at line 58 of file g_main.c.
Referenced by G_Alloc().
g_debugDamage
vmCvar_t g_debugDamage
Definition at line 57 of file g_main.c.
g_debugMove
vmCvar_t g_debugMove
Definition at line 56 of file g_main.c.
Referenced by ClientThink_real().
g_dedicated
vmCvar_t g_dedicated
Definition at line 50 of file g_main.c.
Referenced by ConsoleCommand(), G_LogPrintf(), G_Say(), and G_Voice().
g_dmflags
vmCvar_t g_dmflags
Definition at line 41 of file g_main.c.
Referenced by ClientThink_real().
g_doWarmup
vmCvar_t g_doWarmup
Definition at line 64 of file g_main.c.
Referenced by SP_worldspawn().
g_enableBreath
vmCvar_t g_enableBreath
g_enableDust
vmCvar_t g_enableDust
g_entities
gentity_t g_entities[MAX_GENTITIES]
Definition at line 38 of file g_main.c.
Referenced by __attribute__(), AddTournamentPlayer(), BeginIntermission(), CheatsOk(), CheckTeamStatus(), ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientEvents(), ClientImpacts(), ClientNumberFromString(), ClientSpawn(), ClientThink(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_GameCommand_f(), Cmd_LevelShot_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_VoiceTell_f(), Cmd_Vote_f(), Cmd_Where_f(), Fire_UserWeapon(), G_DetachUserWeapon(), G_EntitiesFree(), G_ExplodeUserWeapon(), G_Find(), G_FindTeams(), G_ImpactUserWeapon(), G_InitGame(), G_InitGentity(), G_MoverPush(), G_RadarUpdateCS(), G_RankClientDisconnect(), G_RankDamage(), G_RankRunFrame(), G_RemoveUserWeapon(), G_RunFrame(), G_RunUserMissile(), G_Say(), G_SayTo(), G_Spawn(), G_TestEntityPosition(), G_TouchTriggers(), G_UserRadiusDamage(), G_UserWeaponDamage(), G_Voice(), G_VoiceTo(), LockonCheck(), RemoveTournamentLoser(), RemoveTournamentWinner(), SendScoreboardMessageToAllClients(), SP_worldspawn(), SpawnModelOnVictoryPad(), SpawnPodium(), SpotWouldTelefrag(), StopFollowing(), Svcmd_EntityList_f(), Svcmd_ForceTeam_f(), target_location_linkup(), Team_ForceGesture(), TeamplayInfoMessage(), Think_CylinderHoming(), Think_Homing(), Think_ProxDet(), UpdateTournamentInfo(), Use_Target_Print(), and UserHitscan_Fire().
g_filterBan
vmCvar_t g_filterBan
Definition at line 75 of file g_main.c.
Referenced by G_FilterPacket().
g_forcerespawn
vmCvar_t g_forcerespawn
Definition at line 54 of file g_main.c.
g_fraglimit
vmCvar_t g_fraglimit
Definition at line 42 of file g_main.c.
Referenced by G_RankRunFrame().
g_friendlyFire
vmCvar_t g_friendlyFire
Definition at line 45 of file g_main.c.
g_gametype
vmCvar_t g_gametype
Definition at line 40 of file g_main.c.
Referenced by BeginIntermission(), CalculateRanks(), CheckTournament(), ClientBegin(), ClientConnect(), ClientDisconnect(), ClientSpawn(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_LevelShot_f(), Cmd_Team_f(), ExitLevel(), G_InitGame(), G_InitSessionData(), G_InitWorldSession(), G_RankRunFrame(), G_RegisterCvars(), G_Say(), G_SayTo(), G_SpawnGEntityFromSpawnVars(), G_Voice(), G_VoiceTo(), G_WriteSessionData(), LogExit(), OnSameTeam(), ScoreIsTied(), SetTeam(), Svcmd_AbortPodium_f(), Team_InitGame(), and Team_SetFlagStatus().
g_inactivity
vmCvar_t g_inactivity
Definition at line 55 of file g_main.c.
Referenced by ClientInactivityTimer(), and ClientSpawn().
g_knockback
vmCvar_t g_knockback
Definition at line 52 of file g_main.c.
g_maxclients
vmCvar_t g_maxclients
Definition at line 48 of file g_main.c.
Referenced by CheckTeamStatus(), ExitLevel(), G_InitGame(), G_RadarUpdateCS(), and TeamplayInfoMessage().
g_maxGameClients
vmCvar_t g_maxGameClients
Definition at line 49 of file g_main.c.
Referenced by G_InitSessionData(), and SetTeam().
g_motd
vmCvar_t g_motd
Definition at line 61 of file g_main.c.
Referenced by SP_worldspawn().
g_needpass
vmCvar_t g_needpass
Definition at line 47 of file g_main.c.
g_password
vmCvar_t g_password
Definition at line 46 of file g_main.c.
Referenced by CheckCvars(), and ClientConnect().
g_pointGravity
vmCvar_t g_pointGravity
Definition at line 102 of file g_main.c.
Referenced by ClientSpawn(), and ClientUserinfoChanged().
g_powerlevel
vmCvar_t g_powerlevel
Definition at line 83 of file g_main.c.
Referenced by ClientBegin(), and ClientSpawn().
g_powerlevelMaximum
vmCvar_t g_powerlevelMaximum
Definition at line 84 of file g_main.c.
Referenced by ClientBegin(), and ClientSpawn().
g_proxMineTimeout
vmCvar_t g_proxMineTimeout
g_quickTransformCost
vmCvar_t g_quickTransformCost
Definition at line 103 of file g_main.c.
Referenced by checkTierUpTransformation().
g_quickTransformCostPerTier
vmCvar_t g_quickTransformCostPerTier
Definition at line 104 of file g_main.c.
Referenced by checkTierUpTransformation().
g_quickZanzokenCost
vmCvar_t g_quickZanzokenCost
Definition at line 105 of file g_main.c.
Referenced by syncTier().
g_quickZanzokenDistance
vmCvar_t g_quickZanzokenDistance
Definition at line 106 of file g_main.c.
Referenced by syncTier().
g_rankings
vmCvar_t g_rankings
Definition at line 79 of file g_main.c.
g_restarted
vmCvar_t g_restarted
Definition at line 65 of file g_main.c.
Referenced by SP_worldspawn().
g_rolling
vmCvar_t g_rolling
Definition at line 100 of file g_main.c.
Referenced by ClientSpawn(), and ClientUserinfoChanged().
g_running
vmCvar_t g_running
Definition at line 101 of file g_main.c.
Referenced by ClientSpawn(), and ClientUserinfoChanged().
g_singlePlayer
vmCvar_t g_singlePlayer
g_smoothClients
vmCvar_t g_smoothClients
Definition at line 76 of file g_main.c.
g_synchronousClients
vmCvar_t g_synchronousClients
Definition at line 62 of file g_main.c.
Referenced by ClientThink(), and G_RunClient().
g_teamAutoJoin
vmCvar_t g_teamAutoJoin
Definition at line 72 of file g_main.c.
Referenced by G_InitSessionData().
g_teamForceBalance
vmCvar_t g_teamForceBalance
Definition at line 73 of file g_main.c.
Referenced by SetTeam().
g_timelimit
vmCvar_t g_timelimit
Definition at line 43 of file g_main.c.
Referenced by G_RankRunFrame().
g_verboseParse
vmCvar_t g_verboseParse
Definition at line 82 of file g_main.c.
Referenced by G_weapPhys_AddDefinitionRef(), G_weapPhys_AddImportRef(), G_weapPhys_AddLinkRef(), G_weapPhys_LoadFile(), G_weapPhys_Parse(), G_weapPhys_ParseCategories(), and G_weapPhys_ParseDefinition().
g_warmup
vmCvar_t g_warmup
Definition at line 63 of file g_main.c.
Referenced by CheckTournament(), and G_RegisterCvars().
level
level_locals_t level
Definition at line 28 of file sym.c.
Referenced by exitscope(), install(), table(), and temporary().
pmove_fixed
vmCvar_t pmove_fixed
Definition at line 158 of file cg_main.c.
pmove_msec
vmCvar_t pmove_msec
Definition at line 160 of file cg_main.c.