ZEQ2-Lite: Tools/MinGW/include/exdisp.h File Reference
exdisp.h File Reference
#include <oaidl.h>
#include <ocidl.h>
#include <docobj.h>
Macros
#define INTERFACE IWebBrowser
#define INTERFACE IWebBrowserApp
#define INTERFACE IWebBrowser2
#define INTERFACE DWebBrowserEvents2
Enumerations
enum BrowserNavConstants {
navOpenInNewWindow = 0x1, navNoHistory = 0x2, navNoReadFromCache = 0x4, navNoWriteTocache = 0x8,
navAllowAutosearch = 0x10, navBrowserBar = 0x20, navHyperLink = 0x40
}
Functions
DECLARE_INTERFACE_ (DWebBrowserEvents2, IDispatch)
DECLARE_INTERFACE_ (IWebBrowser, IDispatch)
DECLARE_INTERFACE_ (IWebBrowser2, IWebBrowserApp)
DECLARE_INTERFACE_ (IWebBrowserApp, IWebBrowser)
Variables
const EXTERN_C CLSID CLSID_WebBrowser
const EXTERN_C IID DIID_DWebBrowserEvents
const EXTERN_C IID DIID_DWebBrowserEvents2
const EXTERN_C IID IID_IWebBrowser
const EXTERN_C IID IID_IWebBrowser2
const EXTERN_C IID IID_IWebBrowserApp
Macro Definition Documentation
INTERFACE [1/4]
#define INTERFACE IWebBrowser
Definition at line 209 of file exdisp.h.
INTERFACE [2/4]
#define INTERFACE IWebBrowserApp
Definition at line 209 of file exdisp.h.
INTERFACE [3/4]
#define INTERFACE IWebBrowser2
Definition at line 209 of file exdisp.h.
INTERFACE [4/4]
#define INTERFACE DWebBrowserEvents2
Definition at line 209 of file exdisp.h.
Enumeration Type Documentation
BrowserNavConstants
enum BrowserNavConstants
Enumerator
navOpenInNewWindow
navNoHistory
navNoReadFromCache
navNoWriteTocache
navAllowAutosearch
navBrowserBar
navHyperLink
Definition at line 16 of file exdisp.h.
              {
     navOpenInNewWindow = 0x1,
     navNoHistory = 0x2,
     navNoReadFromCache = 0x4,
     navNoWriteTocache = 0x8,
     navAllowAutosearch = 0x10,
     navBrowserBar = 0x20,
     navHyperLink = 0x40
 } BrowserNavConstants;
Function Documentation
DECLARE_INTERFACE_() [1/4]
DECLARE_INTERFACE_ (DWebBrowserEvents2 , IDispatch)
Definition at line 210 of file exdisp.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetTypeInfoCount)(THIS_ UINT*) PURE;
     STDMETHOD(GetTypeInfo)(THIS_ UINT,LCID,LPTYPEINFO*) PURE;
     STDMETHOD(GetIDsOfNames)(THIS_ REFIID,LPOLESTR*,UINT,LCID,DISPID*) PURE;
     STDMETHOD(Invoke)(THIS_ DISPID,REFIID,LCID,WORD,DISPPARAMS*,VARIANT*,EXCEPINFO*,UINT*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [2/4]
DECLARE_INTERFACE_ (IWebBrowser , IDispatch)
Definition at line 28 of file exdisp.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetTypeInfoCount)(THIS_ UINT*) PURE;
     STDMETHOD(GetTypeInfo)(THIS_ UINT,LCID,LPTYPEINFO*) PURE;
     STDMETHOD(GetIDsOfNames)(THIS_ REFIID,LPOLESTR*,UINT,LCID,DISPID*) PURE;
     STDMETHOD(Invoke)(THIS_ DISPID,REFIID,LCID,WORD,DISPPARAMS*,VARIANT*,EXCEPINFO*,UINT*) PURE;
     STDMETHOD(GoBack)(THIS) PURE;
     STDMETHOD(GoForward)(THIS) PURE;
     STDMETHOD(GoHome)(THIS) PURE;
     STDMETHOD(GoSearch)(THIS) PURE;
     STDMETHOD(Navigate)(THIS_ BSTR,VARIANT*,VARIANT*,VARIANT*,VARIANT*) PURE;
     STDMETHOD(Refresh)(THIS) PURE;
     STDMETHOD(Refresh2)(THIS_ VARIANT*) PURE;
     STDMETHOD(Stop)(THIS) PURE;
     STDMETHOD(get_Application)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Parent)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Container)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Document)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_TopLevelContainer)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(get_Type)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Left)(THIS_ long*) PURE;
     STDMETHOD(put_Left)(THIS_ long) PURE;
     STDMETHOD(get_Top)(THIS_ long*) PURE;
     STDMETHOD(put_Top)(THIS_ long) PURE;
     STDMETHOD(get_Width)(THIS_ long*) PURE;
     STDMETHOD(put_Width)(THIS_ long) PURE;
     STDMETHOD(get_Height)(THIS_ long*) PURE;
     STDMETHOD(put_Height)(THIS_ long) PURE;
     STDMETHOD(get_LocationName)(THIS_ BSTR*) PURE;
     STDMETHOD(get_LocationURL)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Busy)(THIS_ VARIANT_BOOL*) PURE;
 };
References long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [3/4]
DECLARE_INTERFACE_ (IWebBrowser2 , IWebBrowserApp)
Definition at line 129 of file exdisp.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetTypeInfoCount)(THIS_ UINT*) PURE;
     STDMETHOD(GetTypeInfo)(THIS_ UINT,LCID,LPTYPEINFO*) PURE;
     STDMETHOD(GetIDsOfNames)(THIS_ REFIID,LPOLESTR*,UINT,LCID,DISPID*) PURE;
     STDMETHOD(Invoke)(THIS_ DISPID,REFIID,LCID,WORD,DISPPARAMS*,VARIANT*,EXCEPINFO*,UINT*) PURE;
     STDMETHOD(GoBack)(THIS) PURE;
     STDMETHOD(GoForward)(THIS) PURE;
     STDMETHOD(GoHome)(THIS) PURE;
     STDMETHOD(GoSearch)(THIS) PURE;
     STDMETHOD(Navigate)(THIS_ BSTR,VARIANT*,VARIANT*,VARIANT*,VARIANT*) PURE;
     STDMETHOD(Refresh)(THIS) PURE;
     STDMETHOD(Refresh2)(THIS_ VARIANT*) PURE;
     STDMETHOD(Stop)(THIS) PURE;
     STDMETHOD(get_Application)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Parent)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Container)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Document)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_TopLevelContainer)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(get_Type)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Left)(THIS_ long*) PURE;
     STDMETHOD(put_Left)(THIS_ long) PURE;
     STDMETHOD(get_Top)(THIS_ long*) PURE;
     STDMETHOD(put_Top)(THIS_ long) PURE;
     STDMETHOD(get_Width)(THIS_ long*) PURE;
     STDMETHOD(put_Width)(THIS_ long) PURE;
     STDMETHOD(get_Height)(THIS_ long*) PURE;
     STDMETHOD(put_Height)(THIS_ long) PURE;
     STDMETHOD(get_LocationName)(THIS_ BSTR*) PURE;
     STDMETHOD(get_LocationURL)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Busy)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(Quit)(THIS) PURE;
     STDMETHOD(ClientToWindow)(THIS_ int*,int*) PURE;
     STDMETHOD(PutProperty)(THIS_ BSTR,VARIANT) PURE;
     STDMETHOD(GetProperty)(THIS_ BSTR,VARIANT*) PURE;
     STDMETHOD(get_Name)(THIS_ BSTR*) PURE;
     STDMETHOD(get_HWND)(THIS_ long*) PURE;
     STDMETHOD(get_FullName)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Path)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Visible)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_Visible)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_StatusBar)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_StatusBar)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_StatusText)(THIS_ BSTR*) PURE;
     STDMETHOD(put_StatusText)(THIS_ BSTR) PURE;
     STDMETHOD(get_ToolBar)(THIS_ int*) PURE;
     STDMETHOD(put_ToolBar)(THIS_ int) PURE;
     STDMETHOD(get_MenuBar)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_MenuBar)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_FullScreen)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_FullScreen)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(Navigate2)(THIS_ VARIANT*,VARIANT*,VARIANT*,VARIANT*,VARIANT*) PURE;
     STDMETHOD(QueryStatusWB)(THIS_ OLECMDID,OLECMDF*) PURE;
     STDMETHOD(ExecWB)(THIS_ OLECMDID,OLECMDEXECOPT,VARIANT*,VARIANT*) PURE;
     STDMETHOD(ShowBrowserBar)(THIS_ VARIANT*,VARIANT*,VARIANT*) PURE;
     STDMETHOD(get_ReadyState)(THIS_ READYSTATE*) PURE;
     STDMETHOD(get_Offline)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_Offline)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_Silent)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_Silent)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_RegisterAsBrowser)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_RegisterAsBrowser)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_RegistaerAsDropTarget)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_RegisterAsDropTarget)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_TheaterMode)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_TheaterMode)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_AddressBar)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_AddressBar)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_Resizable)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_Resizable)(THIS_ VARIANT_BOOL) PURE;
 };
References int, long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [4/4]
DECLARE_INTERFACE_ (IWebBrowserApp , IWebBrowser)
Definition at line 68 of file exdisp.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetTypeInfoCount)(THIS_ UINT*) PURE;
     STDMETHOD(GetTypeInfo)(THIS_ UINT,LCID,LPTYPEINFO*) PURE;
     STDMETHOD(GetIDsOfNames)(THIS_ REFIID,LPOLESTR*,UINT,LCID,DISPID*) PURE;
     STDMETHOD(Invoke)(THIS_ DISPID,REFIID,LCID,WORD,DISPPARAMS*,VARIANT*,EXCEPINFO*,UINT*) PURE;
     STDMETHOD(GoBack)(THIS) PURE;
     STDMETHOD(GoForward)(THIS) PURE;
     STDMETHOD(GoHome)(THIS) PURE;
     STDMETHOD(GoSearch)(THIS) PURE;
     STDMETHOD(Navigate)(THIS_ BSTR,VARIANT*,VARIANT*,VARIANT*,VARIANT*) PURE;
     STDMETHOD(Refresh)(THIS) PURE;
     STDMETHOD(Refresh2)(THIS_ VARIANT*) PURE;
     STDMETHOD(Stop)(THIS) PURE;
     STDMETHOD(get_Application)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Parent)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Container)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_Document)(THIS_ IDispatch**) PURE;
     STDMETHOD(get_TopLevelContainer)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(get_Type)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Left)(THIS_ long*) PURE;
     STDMETHOD(put_Left)(THIS_ long) PURE;
     STDMETHOD(get_Top)(THIS_ long*) PURE;
     STDMETHOD(put_Top)(THIS_ long) PURE;
     STDMETHOD(get_Width)(THIS_ long*) PURE;
     STDMETHOD(put_Width)(THIS_ long) PURE;
     STDMETHOD(get_Height)(THIS_ long*) PURE;
     STDMETHOD(put_Height)(THIS_ long) PURE;
     STDMETHOD(get_LocationName)(THIS_ BSTR*) PURE;
     STDMETHOD(get_LocationURL)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Busy)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(Quit)(THIS) PURE;
     STDMETHOD(ClientToWindow)(THIS_ int*,int*) PURE;
     STDMETHOD(PutProperty)(THIS_ BSTR,VARIANT) PURE;
     STDMETHOD(GetProperty)(THIS_ BSTR,VARIANT*) PURE;
     STDMETHOD(get_Name)(THIS_ BSTR*) PURE;
     STDMETHOD(get_HWND)(THIS_ long*) PURE;
     STDMETHOD(get_FullName)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Path)(THIS_ BSTR*) PURE;
     STDMETHOD(get_Visible)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_Visible)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_StatusBar)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_StatusBar)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_StatusText)(THIS_ BSTR*) PURE;
     STDMETHOD(put_StatusText)(THIS_ BSTR) PURE;
     STDMETHOD(get_ToolBar)(THIS_ int*) PURE;
     STDMETHOD(put_ToolBar)(THIS_ int) PURE;
     STDMETHOD(get_MenuBar)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_MenuBar)(THIS_ VARIANT_BOOL) PURE;
     STDMETHOD(get_FullScreen)(THIS_ VARIANT_BOOL*) PURE;
     STDMETHOD(put_FullScreen)(THIS_ VARIANT_BOOL) PURE;
 };
References int, long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
Variable Documentation
CLSID_WebBrowser
const EXTERN_C CLSID CLSID_WebBrowser
Definition at line 13 of file exdisp.h.
DIID_DWebBrowserEvents
const EXTERN_C IID DIID_DWebBrowserEvents
Definition at line 14 of file exdisp.h.
DIID_DWebBrowserEvents2
const EXTERN_C IID DIID_DWebBrowserEvents2
Definition at line 205 of file exdisp.h.
IID_IWebBrowser
const EXTERN_C IID IID_IWebBrowser
Definition at line 26 of file exdisp.h.
IID_IWebBrowser2
const EXTERN_C IID IID_IWebBrowser2
Definition at line 124 of file exdisp.h.
IID_IWebBrowserApp
const EXTERN_C IID IID_IWebBrowserApp
Definition at line 63 of file exdisp.h.