ZEQ2-Lite: __gnu_debug::_Error_formatter::_Parameter Struct Reference
__gnu_debug::_Error_formatter::_Parameter Struct Reference
Public Types
enum {
__unused_param, __iterator, __sequence, __integer,
__string
}
Public Member Functions
_Parameter ()
template<typename _Type >
_Parameter (_Type *&__it, const char *__name, _Is_iterator)
template<typename _Iterator >
_Parameter (const _Iterator &__it, const char *__name, _Is_iterator)
template<typename _Iterator , typename _Sequence >
_Parameter (const _Safe_iterator< _Iterator, _Sequence > &__it, const char *__name, _Is_iterator)
template<typename _Sequence >
_Parameter (const _Safe_sequence< _Sequence > &__seq, const char *__name, _Is_sequence)
template<typename _Sequence >
_Parameter (const _Sequence &__seq, const char *__name, _Is_sequence)
template<typename _Type >
_Parameter (const _Type *&__it, const char *__name, _Is_iterator)
_Parameter (const char *__value, const char *__name)
_Parameter (long __value, const char *__name)
void _M_print_description (const _Error_formatter *__formatter) const
void _M_print_field (const _Error_formatter *__formatter, const char *__name) const
Data Fields
enum __gnu_debug::_Error_formatter::_Parameter:: { ... } _M_kind
union {
struct {
const char * _M_name
long _M_value
} _M_integer
struct {
const void * _M_address
_Constness _M_constness
const char * _M_name
const type_info * _M_seq_type
const void * _M_sequence
_Iterator_state _M_state
const type_info * _M_type
} _M_iterator
struct {
const void * _M_address
const char * _M_name
const type_info * _M_type
} _M_sequence
struct {
const char * _M_name
const char * _M_value
} _M_string
} _M_variant
Detailed Description
Definition at line 137 of file formatter.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
__unused_param
__iterator
__sequence
__integer
__string
Definition at line 139 of file formatter.h.
       {
     __unused_param,
     __iterator,
     __sequence,
     __integer,
     __string
       } _M_kind;
Constructor & Destructor Documentation
_Parameter() [1/9]
__gnu_debug::_Error_formatter::_Parameter::_Parameter () inline
Definition at line 185 of file formatter.h.
 : _M_kind(__unused_param), _M_variant() { }
_Parameter() [2/9]
__gnu_debug::_Error_formatter::_Parameter::_Parameter (long __value, const char * __name) inline
Definition at line 187 of file formatter.h.
       : _M_kind(__integer), _M_variant()
       {
     _M_variant._M_integer._M_name = __name;
     _M_variant._M_integer._M_value = __value;
       }
References _M_variant.
_Parameter() [3/9]
__gnu_debug::_Error_formatter::_Parameter::_Parameter (const char * __value, const char * __name) inline
Definition at line 194 of file formatter.h.
       : _M_kind(__string), _M_variant()
       {
     _M_variant._M_string._M_name = __name;
     _M_variant._M_string._M_value = __value;
       }
References _M_variant.
_Parameter() [4/9]
template<typename _Iterator , typename _Sequence > __gnu_debug::_Error_formatter::_Parameter::_Parameter (const _Safe_iterator< _Iterator, _Sequence > & __it, const char * __name, _Is_iterator) inline
Definition at line 202 of file formatter.h.
     : _M_kind(__iterator),  _M_variant()
         {
       _M_variant._M_iterator._M_name = __name;
       _M_variant._M_iterator._M_address = &__it;
 #ifdef __GXX_RTTI
       _M_variant._M_iterator._M_type = &typeid(__it);
 #else
       _M_variant._M_iterator._M_type = 0;
 #endif
       _M_variant._M_iterator._M_constness =
         std::__are_same<_Safe_iterator<_Iterator, _Sequence>,
                         typename _Sequence::iterator>::
           __value ? __mutable_iterator : __const_iterator;
       _M_variant._M_iterator._M_sequence = __it._M_get_sequence();
 #ifdef __GXX_RTTI
       _M_variant._M_iterator._M_seq_type = &typeid(_Sequence);
 #else
       _M_variant._M_iterator._M_seq_type = 0;
 #endif
       if (__it._M_singular())
         _M_variant._M_iterator._M_state = __singular;
       else
         {
           if (__it._M_is_before_begin())
         _M_variant._M_iterator._M_state = __before_begin;
           else if (__it._M_is_end())
         _M_variant._M_iterator._M_state = __end;
           else if (__it._M_is_begin())
         _M_variant._M_iterator._M_state = __begin;
           else
         _M_variant._M_iterator._M_state = __middle;
         }
     }
References __gnu_debug::_Error_formatter::__before_begin, __gnu_debug::_Error_formatter::__begin, __gnu_debug::_Error_formatter::__const_iterator, __gnu_debug::_Error_formatter::__end, __gnu_debug::_Error_formatter::__middle, __gnu_debug::_Error_formatter::__mutable_iterator, __gnu_debug::_Error_formatter::__singular, __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_get_sequence(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_before_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_begin(), __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_is_end(), _M_variant, and if().
_Parameter() [5/9]
template<typename _Type > __gnu_debug::_Error_formatter::_Parameter::_Parameter (const _Type *& __it, const char * __name, _Is_iterator) inline
Definition at line 240 of file formatter.h.
         : _M_kind(__iterator), _M_variant()
         {
       _M_variant._M_iterator._M_name = __name;
       _M_variant._M_iterator._M_address = &__it;
 #ifdef __GXX_RTTI
       _M_variant._M_iterator._M_type = &typeid(__it);
 #else
       _M_variant._M_iterator._M_type = 0;
 #endif
       _M_variant._M_iterator._M_constness = __mutable_iterator;
       _M_variant._M_iterator._M_state = __it? __unknown_state : __singular;
       _M_variant._M_iterator._M_sequence = 0;
       _M_variant._M_iterator._M_seq_type = 0;
     }
References __gnu_debug::_Error_formatter::__mutable_iterator, __gnu_debug::_Error_formatter::__singular, and __gnu_debug::_Error_formatter::__unknown_state.
_Parameter() [6/9]
template<typename _Type > __gnu_debug::_Error_formatter::_Parameter::_Parameter (_Type *& __it, const char * __name, _Is_iterator) inline
Definition at line 257 of file formatter.h.
         : _M_kind(__iterator), _M_variant()
         {
       _M_variant._M_iterator._M_name = __name;
       _M_variant._M_iterator._M_address = &__it;
 #ifdef __GXX_RTTI
       _M_variant._M_iterator._M_type = &typeid(__it);
 #else
       _M_variant._M_iterator._M_type = 0;
 #endif
       _M_variant._M_iterator._M_constness = __const_iterator;
       _M_variant._M_iterator._M_state = __it? __unknown_state : __singular;
       _M_variant._M_iterator._M_sequence = 0;
       _M_variant._M_iterator._M_seq_type = 0;
     }
References __gnu_debug::_Error_formatter::__const_iterator, __gnu_debug::_Error_formatter::__singular, and __gnu_debug::_Error_formatter::__unknown_state.
_Parameter() [7/9]
template<typename _Iterator > __gnu_debug::_Error_formatter::_Parameter::_Parameter (const _Iterator & __it, const char * __name, _Is_iterator) inline
Definition at line 274 of file formatter.h.
         : _M_kind(__iterator), _M_variant()
         {
       _M_variant._M_iterator._M_name = __name;
       _M_variant._M_iterator._M_address = &__it;
 #ifdef __GXX_RTTI
       _M_variant._M_iterator._M_type = &typeid(__it);
 #else
       _M_variant._M_iterator._M_type = 0;
 #endif
       _M_variant._M_iterator._M_constness = __unknown_constness;
       _M_variant._M_iterator._M_state =
         __gnu_debug::__check_singular(__it)? __singular : __unknown_state;
       _M_variant._M_iterator._M_sequence = 0;
       _M_variant._M_iterator._M_seq_type = 0;
     }
References __gnu_debug::__check_singular(), __gnu_debug::_Error_formatter::__singular, __gnu_debug::_Error_formatter::__unknown_constness, and __gnu_debug::_Error_formatter::__unknown_state.
_Parameter() [8/9]
template<typename _Sequence > __gnu_debug::_Error_formatter::_Parameter::_Parameter (const _Safe_sequence< _Sequence > & __seq, const char * __name, _Is_sequence) inline
Definition at line 292 of file formatter.h.
         : _M_kind(__sequence), _M_variant()
         {
       _M_variant._M_sequence._M_name = __name;
       _M_variant._M_sequence._M_address =
         static_cast<const _Sequence*>(&__seq);
 #ifdef __GXX_RTTI
       _M_variant._M_sequence._M_type = &typeid(_Sequence);
 #else
       _M_variant._M_sequence._M_type = 0;
 #endif
     }
_Parameter() [9/9]
template<typename _Sequence > __gnu_debug::_Error_formatter::_Parameter::_Parameter (const _Sequence & __seq, const char * __name, _Is_sequence) inline
Definition at line 307 of file formatter.h.
         : _M_kind(__sequence), _M_variant()
         {
       _M_variant._M_sequence._M_name = __name;
       _M_variant._M_sequence._M_address = &__seq;
 #ifdef __GXX_RTTI
       _M_variant._M_sequence._M_type = &typeid(_Sequence);
 #else
       _M_variant._M_sequence._M_type = 0;
 #endif
     }
Member Function Documentation
_M_print_description()
void __gnu_debug::_Error_formatter::_Parameter::_M_print_description (const _Error_formatter * __formatter) const
_M_print_field()
void __gnu_debug::_Error_formatter::_Parameter::_M_print_field (const _Error_formatter * __formatter, const char * __name) const
Field Documentation
_M_address
const void* __gnu_debug::_Error_formatter::_Parameter::_M_address
Definition at line 154 of file formatter.h.
_M_constness
_Constness __gnu_debug::_Error_formatter::_Parameter::_M_constness
Definition at line 156 of file formatter.h.
_M_integer
struct { ... } __gnu_debug::_Error_formatter::_Parameter::_M_integer
_M_iterator
struct { ... } __gnu_debug::_Error_formatter::_Parameter::_M_iterator
_M_kind
enum { ... } __gnu_debug::_Error_formatter::_Parameter::_M_kind
_M_name
const char* __gnu_debug::_Error_formatter::_Parameter::_M_name
Definition at line 153 of file formatter.h.
_M_seq_type
const type_info* __gnu_debug::_Error_formatter::_Parameter::_M_seq_type
Definition at line 159 of file formatter.h.
_M_sequence [1/2]
const void* __gnu_debug::_Error_formatter::_Parameter::_M_sequence
Definition at line 158 of file formatter.h.
_M_sequence [2/2]
struct { ... } __gnu_debug::_Error_formatter::_Parameter::_M_sequence
_M_state
_Iterator_state __gnu_debug::_Error_formatter::_Parameter::_M_state
Definition at line 157 of file formatter.h.
_M_string
struct { ... } __gnu_debug::_Error_formatter::_Parameter::_M_string
_M_type
const type_info* __gnu_debug::_Error_formatter::_Parameter::_M_type
Definition at line 155 of file formatter.h.
_M_value [1/2]
long __gnu_debug::_Error_formatter::_Parameter::_M_value
Definition at line 174 of file formatter.h.
_M_value [2/2]
const char* __gnu_debug::_Error_formatter::_Parameter::_M_value
Definition at line 181 of file formatter.h.
_M_variant
union { ... } __gnu_debug::_Error_formatter::_Parameter::_M_variant
Referenced by _Parameter().
The documentation for this struct was generated from the following file:
Tools/MinGW/include/c++/4.6.1/debug/formatter.h