ZEQ2-Lite: Source/Shared/puff.h File Reference
puff.h File Reference
#include "q_shared.h"
Functions
int32_t puff (uint8_t *dest, uint32_t *destlen, uint8_t *source, uint32_t *sourcelen)
Function Documentation
puff()
int32_t puff (uint8_t * dest, uint32_t * destlen, uint8_t * source, uint32_t * sourcelen)
Definition at line 715 of file puff.c.
 {
     struct state s;             /* input/output state */
     int32_t last, type;             /* block information */
     int32_t err;                    /* return value */
     /* initialize output state */
     s.out = dest;
     s.outlen = *destlen;                /* ignored if dest is NULL */
     s.outcnt = 0;
     /* initialize input state */
     s.in = source;
     s.inlen = *sourcelen;
     s.incnt = 0;
     s.bitbuf = 0;
     s.bitcnt = 0;
     /* return if bits() or decode() tries to read past available input */
     if (setjmp(s.env) != 0)             /* if came back here via longjmp() */
         err = 2;                        /* then skip do-loop, return error */
     else {
         /* process blocks until last block or error */
         do {
             last = bits(&s, 1);         /* one if last block */
             type = bits(&s, 2);         /* block type 0..3 */
             err = type == 0 ? stored(&s) :
                   (type == 1 ? fixed(&s) :
                    (type == 2 ? dynamic(&s) :
                     -1));               /* type == 3, invalid */
             if (err != 0) break;        /* return with error */
         } while (!last);
     }
     /* update the lengths and return */
     if (err <= 0) {
         *destlen = s.outcnt;
         *sourcelen = s.incnt;
     }
     return err;
 }
References bits(), dynamic(), fixed(), and stored().
Referenced by DecompressIDATs().