ZEQ2-Lite: Engine/libcurl/curl/stdcheaders.h File Reference
stdcheaders.h File Reference
#include <sys/types.h>
Functions
size_t fread (void *, size_t, size_t, FILE *)
size_t fwrite (const void *, size_t, size_t, FILE *)
int strcasecmp (const char *, const char *)
int strncasecmp (const char *, const char *, size_t)
Function Documentation
fread()
size_t fread (void * , size_t , size_t , FILE *)
Referenced by _GLIBCXX_VISIBILITY(), fillbuf(), fread_file_func(), FS_GetModList(), FS_Read(), LoadSourceFile(), main(), SafeRead(), Sys_RandomBytes(), Sys_StreamedRead(), and Sys_WritePIDFile().
fwrite()
size_t fwrite (const void * , size_t , size_t , FILE *)
Referenced by _GLIBCXX_VISIBILITY(), emit1(), FS_Write(), fwrite_file_func(), main(), SafeWrite(), and VM_Compile().
strcasecmp()
__CRT_INLINE int __cdecl __MINGW_NOTHROW strcasecmp (const char * __sz1, const char * __sz2)
Definition at line 98 of file string.h.
   {return _stricmp (__sz1, __sz2);}
References _stricmp().
strncasecmp()
__CRT_INLINE int __cdecl __MINGW_NOTHROW strncasecmp (const char * __sz1, const char * __sz2, size_t __sizeMaxCompare)
Definition at line 107 of file string.h.
   {return _strnicmp (__sz1, __sz2, __sizeMaxCompare);}
References _strnicmp().