ZEQ2-Lite: Source/Engine/jpeg-8c/jcapimin.c File Reference
jcapimin.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define JPEG_INTERNALS
Functions
jpeg_abort_compress (j_compress_ptr cinfo)
jpeg_CreateCompress (j_compress_ptr cinfo, int version, size_t structsize)
jpeg_destroy_compress (j_compress_ptr cinfo)
jpeg_finish_compress (j_compress_ptr cinfo)
jpeg_suppress_tables (j_compress_ptr cinfo, boolean suppress)
jpeg_write_m_byte (j_compress_ptr cinfo, int val)
jpeg_write_m_header (j_compress_ptr cinfo, int marker, unsigned int datalen)
jpeg_write_marker (j_compress_ptr cinfo, int marker, const JOCTET *dataptr, unsigned int datalen)
jpeg_write_tables (j_compress_ptr cinfo)
Macro Definition Documentation
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 20 of file jcapimin.c.
Function Documentation
jpeg_abort_compress()
jpeg_abort_compress (j_compress_ptr cinfo)
Definition at line 108 of file jcapimin.c.
 {
   jpeg_abort((j_common_ptr) cinfo); /* use common routine */
 }
References jpeg_abort().
jpeg_CreateCompress()
jpeg_CreateCompress (j_compress_ptr cinfo, int version, size_t structsize)
Definition at line 31 of file jcapimin.c.
 {
   int i;
   /* Guard against version mismatches between library and caller. */
   cinfo->mem = NULL;        /* so jpeg_destroy knows mem mgr not called */
   if (version != JPEG_LIB_VERSION)
     ERREXIT2(cinfo, JERR_BAD_LIB_VERSION, JPEG_LIB_VERSION, version);
   if (structsize != SIZEOF(struct jpeg_compress_struct))
     ERREXIT2(cinfo, JERR_BAD_STRUCT_SIZE,
          (int) SIZEOF(struct jpeg_compress_struct), (int) structsize);
   /* For debugging purposes, we zero the whole master structure.
    * But the application has already set the err pointer, and may have set
    * client_data, so we have to save and restore those fields.
    * Note: if application hasn't set client_data, tools like Purify may
    * complain here.
    */
   {
     struct jpeg_error_mgr * err = cinfo->err;
     void * client_data = cinfo->client_data; /* ignore Purify complaint here */
     MEMZERO(cinfo, SIZEOF(struct jpeg_compress_struct));
     cinfo->err = err;
     cinfo->client_data = client_data;
   }
   cinfo->is_decompressor = FALSE;
   /* Initialize a memory manager instance for this object */
   jinit_memory_mgr((j_common_ptr) cinfo);
   /* Zero out pointers to permanent structures. */
   cinfo->progress = NULL;
   cinfo->dest = NULL;
   cinfo->comp_info = NULL;
   for (i = 0; i < NUM_QUANT_TBLS; i++) {
     cinfo->quant_tbl_ptrs[i] = NULL;
     cinfo->q_scale_factor[i] = 100;
   }
   for (i = 0; i < NUM_HUFF_TBLS; i++) {
     cinfo->dc_huff_tbl_ptrs[i] = NULL;
     cinfo->ac_huff_tbl_ptrs[i] = NULL;
   }
   /* Must do it here for emit_dqt in case jpeg_write_tables is used */
   cinfo->block_size = DCTSIZE;
   cinfo->natural_order = jpeg_natural_order;
   cinfo->lim_Se = DCTSIZE2-1;
   cinfo->script_space = NULL;
   cinfo->input_gamma = 1.0; /* in case application forgets */
   /* OK, I'm ready */
   cinfo->global_state = CSTATE_START;
 }
References CSTATE_START, DCTSIZE, DCTSIZE2, ERREXIT2, FALSE, jpeg_error_mgr::i, jinit_memory_mgr(), JPEG_LIB_VERSION, jpeg_natural_order, MEMZERO, NULL, NUM_HUFF_TBLS, NUM_QUANT_TBLS, SIZEOF, structsize, and version.
jpeg_destroy_compress()
jpeg_destroy_compress (j_compress_ptr cinfo)
Definition at line 96 of file jcapimin.c.
 {
   jpeg_destroy((j_common_ptr) cinfo); /* use common routine */
 }
References jpeg_destroy().
Referenced by empty_output_buffer(), and RE_SaveJPGToBuffer().
jpeg_finish_compress()
jpeg_finish_compress (j_compress_ptr cinfo)
Definition at line 155 of file jcapimin.c.
 {
   JDIMENSION iMCU_row;
   if (cinfo->global_state == CSTATE_SCANNING ||
       cinfo->global_state == CSTATE_RAW_OK) {
     /* Terminate first pass */
     if (cinfo->next_scanline < cinfo->image_height)
       ERREXIT(cinfo, JERR_TOO_LITTLE_DATA);
     (*cinfo->master->finish_pass) (cinfo);
   } else if (cinfo->global_state != CSTATE_WRCOEFS)
     ERREXIT1(cinfo, JERR_BAD_STATE, cinfo->global_state);
   /* Perform any remaining passes */
   while (! cinfo->master->is_last_pass) {
     (*cinfo->master->prepare_for_pass) (cinfo);
     for (iMCU_row = 0; iMCU_row < cinfo->total_iMCU_rows; iMCU_row++) {
       if (cinfo->progress != NULL) {
     cinfo->progress->pass_counter = (long) iMCU_row;
     cinfo->progress->pass_limit = (long) cinfo->total_iMCU_rows;
     (*cinfo->progress->progress_monitor) ((j_common_ptr) cinfo);
       }
       /* We bypass the main controller and invoke coef controller directly;
        * all work is being done from the coefficient buffer.
        */
       if (! (*cinfo->coef->compress_data) (cinfo, (JSAMPIMAGE) NULL))
     ERREXIT(cinfo, JERR_CANT_SUSPEND);
     }
     (*cinfo->master->finish_pass) (cinfo);
   }
   /* Write EOI, do final cleanup */
   (*cinfo->marker->write_file_trailer) (cinfo);
   (*cinfo->dest->term_destination) (cinfo);
   /* We can use jpeg_abort to release memory and reset global_state */
   jpeg_abort((j_common_ptr) cinfo);
 }
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, ERREXIT, ERREXIT1, jpeg_abort(), long(), and NULL.
Referenced by RE_SaveJPGToBuffer().
jpeg_suppress_tables()
jpeg_suppress_tables (j_compress_ptr cinfo, boolean suppress)
Definition at line 127 of file jcapimin.c.
 {
   int i;
   JQUANT_TBL * qtbl;
   JHUFF_TBL * htbl;
   for (i = 0; i < NUM_QUANT_TBLS; i++) {
     if ((qtbl = cinfo->quant_tbl_ptrs[i]) != NULL)
       qtbl->sent_table = suppress;
   }
   for (i = 0; i < NUM_HUFF_TBLS; i++) {
     if ((htbl = cinfo->dc_huff_tbl_ptrs[i]) != NULL)
       htbl->sent_table = suppress;
     if ((htbl = cinfo->ac_huff_tbl_ptrs[i]) != NULL)
       htbl->sent_table = suppress;
   }
 }
References jpeg_error_mgr::i, NULL, NUM_HUFF_TBLS, NUM_QUANT_TBLS, JQUANT_TBL::sent_table, JHUFF_TBL::sent_table, and suppress.
Referenced by jpeg_start_compress().
jpeg_write_m_byte()
jpeg_write_m_byte (j_compress_ptr cinfo, int val)
Definition at line 234 of file jcapimin.c.
 {
   (*cinfo->marker->write_marker_byte) (cinfo, val);
 }
References val.
jpeg_write_m_header()
jpeg_write_m_header (j_compress_ptr cinfo, int marker, unsigned int datalen)
Definition at line 222 of file jcapimin.c.
 {
   if (cinfo->next_scanline != 0 ||
       (cinfo->global_state != CSTATE_SCANNING &&
        cinfo->global_state != CSTATE_RAW_OK &&
        cinfo->global_state != CSTATE_WRCOEFS))
     ERREXIT1(cinfo, JERR_BAD_STATE, cinfo->global_state);
   (*cinfo->marker->write_marker_header) (cinfo, marker, datalen);
 }
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, datalen, ERREXIT1, and marker.
jpeg_write_marker()
jpeg_write_marker (j_compress_ptr cinfo, int marker, const JOCTET * dataptr, unsigned int datalen)
Definition at line 200 of file jcapimin.c.
 {
   JMETHOD(void, write_marker_byte, (j_compress_ptr info, int val));
   if (cinfo->next_scanline != 0 ||
       (cinfo->global_state != CSTATE_SCANNING &&
        cinfo->global_state != CSTATE_RAW_OK &&
        cinfo->global_state != CSTATE_WRCOEFS))
     ERREXIT1(cinfo, JERR_BAD_STATE, cinfo->global_state);
   (*cinfo->marker->write_marker_header) (cinfo, marker, datalen);
   write_marker_byte = cinfo->marker->write_marker_byte; /* copy for speed */
   while (datalen--) {
     (*write_marker_byte) (cinfo, *dataptr);
     dataptr++;
   }
 }
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, datalen, dataptr, ERREXIT1, info, JMETHOD, marker, val, and write_marker_byte().
jpeg_write_tables()
jpeg_write_tables (j_compress_ptr cinfo)
Definition at line 262 of file jcapimin.c.
 {
   if (cinfo->global_state != CSTATE_START)
     ERREXIT1(cinfo, JERR_BAD_STATE, cinfo->global_state);
   /* (Re)initialize error mgr and destination modules */
   (*cinfo->err->reset_error_mgr) ((j_common_ptr) cinfo);
   (*cinfo->dest->init_destination) (cinfo);
   /* Initialize the marker writer ... bit of a crock to do it here. */
   jinit_marker_writer(cinfo);
   /* Write them tables! */
   (*cinfo->marker->write_tables_only) (cinfo);
   /* And clean up. */
   (*cinfo->dest->term_destination) (cinfo);
   /*
    * In library releases up through v6a, we called jpeg_abort() here to free
    * any working memory allocated by the destination manager and marker
    * writer.  Some applications had a problem with that: they allocated space
    * of their own from the library memory manager, and didn't want it to go
    * away during write_tables.  So now we do nothing.  This will cause a
    * memory leak if an app calls write_tables repeatedly without doing a full
    * compression cycle or otherwise resetting the JPEG object.  However, that
    * seems less bad than unexpectedly freeing memory in the normal case.
    * An app that prefers the old behavior can call jpeg_abort for itself after
    * each call to jpeg_write_tables().
    */
 }
References CSTATE_START, ERREXIT1, and jinit_marker_writer().