ZEQ2-Lite: Tools/MinGW/msys/share/bison/lalr1.cc File Reference
lalr1.cc File Reference
#include <string>
#include <iostream>
#include "stack.hh"
#include "location.hh"
#include "@basename(]b4_spec_defines_file[@)"
#include <deque>
Data Structures
struct token
Tokens.
Macros
#define BISON_STACK_HH
#define PARSER_HEADER_H
#define YY_(msgid) msgid
#define YY_REDUCE_PRINT(Rule)
#define YY_STACK_PRINT()
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YYABORT goto yyabortlab
#define YYACCEPT goto yyacceptlab
#define YYCDEBUG if (false) std::cerr
#define yyclearin (yychar = yyempty_)
#define YYDEBUG ]b4_debug_flag[
#define yyerrok (yyerrstatus_ = 0)
#define YYERROR goto yyerrorlab
#define YYERROR_VERBOSE ]b4_error_verbose_flag[
#define yylex b4_prefix[]lex])[
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define YYRECOVERING() (!!yyerrstatus_)
#define YYSTYPE b4_namespace_ref::b4_parser_class_name::semantic_type
#define YYTOKEN_TABLE ]b4_token_table[
#define YYUSE(e) ((void) (e))
Typedefs
typedef stack< location_type > location_stack_type
location stack type.
typedef stack< semantic_type > semantic_stack_type
Semantic value stack type.
typedef stack< state_type > state_stack_type
State stack type.
typedef int state_type
State numbers.
typedef token::yytokentype token_type
Token type.
Functions
b4_defines_if ([[]])[]b4_user_post_prologue b4_percent_code_get[]dnl[]b4_namespace_open[]b4_parser_class_name
Build a parser object.
static const b4_int_type (b4_pact_ninf, b4_pact_ninf)[yypact_ninf_
static const b4_int_type (b4_table_ninf, b4_table_ninf)[yytable_ninf_
typedef b4_int_type_for ([b4_translate])[token_number_type
Internal symbol numbers.
dnl we want computed header guards[#define PARSER_HEADER_H] b4_percent_code_get ([[requires]])[]b4_namespace_open[class position
b4_parse_param_vars[};] b4_namespace_close[] b4_percent_define_flag_if ([[global_tokens_and_yystype]], [b4_token_defines(b4_tokens) #define YYSTYPE]) b4_percent_code_get()[]dnl[]) dnl @output(b4_parser_file_name@)@ b4_copyright([Skeleton implementation for Bison LALR(1) parsers in C++]
error (yylloc, yysyntax_error_(yystate]dnl b4_error_verbose_if([, yytoken])[))
for (;;)
if (0<=yystate &&yystate<=yylast_ &&yycheck_[yystate]==yystate_stack_[0]) yystate
if (yyerrstatus_==3)
b4_namespace_close[#define YYDEBUG#define YYERROR_VERBOSE#define YYTOKEN_TABLE#define YYLLOC_DEFAULT(Current, Rhs, N)] b4_namespace_open[class] b4_parser_class_name[{ public:] m4_ifdef ([b4_stype], [union semantic_type { b4_user_stype };], [m4_if(b4_tag_seen_flag, 0, [[typedef int semantic_type;]], [[typedef YYSTYPE semantic_type;]])])[typedef]b4_percent_define_get()[location_type
Symbol locations.
m4_include (b4_pkgdatadir/[c++.m4]) m4_define([b4_parser_class_name]
b4_parser_class_name[::token_number_type] b4_parser_class_name[::yytranslate_(int t) { static const token_number_type translate_table[]={] b4_translate[};if((unsigned int) t<=yyuser_token_number_max_) return translate_table[t];else return yyundef_token_;} const int] b4_parser_class_name[::yyeof_=0;const int] b4_parser_class_name[::yylast_=] b4_last[;const int] b4_parser_class_name[::yynnts_=] b4_nterms_number[;const int] b4_parser_class_name[::yyempty_=-2;const int] b4_parser_class_name[::yyfinal_=] b4_final_state_number[;const int] b4_parser_class_name[::yyterror_=1;const int] b4_parser_class_name[::yyerrcode_=256;const int] b4_parser_class_name[::yyntokens_=] b4_tokens_number[;const unsigned int] b4_parser_class_name[::yyuser_token_number_max_=] b4_user_token_number_max[;const] b4_parser_class_name[::token_number_type] b4_parser_class_name[::yyundef_token_=] b4_undef_token_number[;] b4_namespace_close[] b4_epilogue dnl output (b4_dir_prefix[]stack.hh@)@ b4_copyright([Stack handling for Bison parsers in C++]
yylocation_stack_ push (yylloc)
yylocation_stack_ push (yyloc)
yysemantic_stack_ push (yylval)
yysemantic_stack_ push (yyval)
switch (yyn)
while (yystate_stack_.height() !=1)
YY_REDUCE_PRINT (yyn)
YY_SYMBOL_PRINT ("-> $$ =", yyr1_[yyn], &yyval, &yyloc)
YY_SYMBOL_PRINT ("Shifting", yystos_[yyn], &yysemantic_stack_[0], &yylocation_stack_[0])
void yydestruct_ (const char *yymsg, int yytype, semantic_type *yyvaluep, location_type *yylocationp)
Reclaim the memory associated to a symbol.
YYLLOC_DEFAULT (yyloc, slice, yylen)
YYLLOC_DEFAULT (yyloc,(yyerror_range - 1), 2)
void yypop_ (unsigned int n=1)
Pop n symbols the three stacks.
yypop_ (yylen)
token_number_type yytranslate_ (int t)
Convert a scanner token number t to a symbol number.
Variables
yynewstate __pad0__
yyerrlab __pad1__
yyerrorlab __pad2__
yyerrlab1 __pad3__
yyacceptlab __pad4__
yyabortlab __pad5__
yyreturn __pad6__
b4_parser_class_name[(] b4_parse_param_decl[);virtual ~] b4_parser_class_name[();virtual int parse();private:virtual void error(const location_type &loc, const std::string &msg);virtual std::string yysyntax_error_(int yystate] dnl b4_error_verbose_if ([, int tok])[)
Build a parser object.
dnl FIXME
b4_parser_class_name::~b4_parser_class_name[() { } void] b4_parser_class_name[::yydestruct_(const char *yymsg, int yytype, semantic_type *yyvaluep, location_type *yylocationp) { YYUSE(yylocationp);YYUSE(yymsg);YYUSE(yyvaluep);YY_SYMBOL_PRINT(yymsg, yytype, yyvaluep, yylocationp);switch(yytype) {] m4_map(m4_ifdef [b4_symbol_actions], m4_defn([b4_symbol_destructors]))[default void b4_parser_class_name[::yypop_(unsigned int n) { yystate_stack_.pop(n);yysemantic_stack_.pop(n);yylocation_stack_.pop(n);} int] b4_parser_class_name[::parse() { int yychar=yyempty_;int yytoken=0;int yyn;int yylen=0;int yystate=0;int yynerrs_=0;int yyerrstatus_=0;semantic_type yylval;location_type yylloc;location_type yyerror_range[2];semantic_type yyval;location_type yyloc;int yyresult;YYCDEBUG<< "Starting parse"<< std::endl;]([b4_initial_action], [m4_pushdef([b4_at_dollar], [yylloc]) dnl m4_pushdef([b4_dollar_dollar], [yylval]) dnl b4_user_initial_action m4_popdef([b4_dollar_dollar]) dnl m4_popdef([b4_at_dollar])]) dnl[yystate_stack_ = state_stack_type (0)
YYCDEBUG<< "Entering state "<< yystate<< std::endl;if(yystate==yyfinal_) goto yyacceptlab;goto yybackup;yybackup:yyn=yypact_[yystate];if(yyn==yypact_ninf_) goto yydefault;if(yychar==yyempty_) { YYCDEBUG<< "Reading a token: ";yychar=]b4_c_function_call([yylex],[int],[]dnlb4_locations_if([,]) dnlm4_ifdef([b4_lex_param],[,]b4_lex_param))[;} if(yychar<=yyeof_) { yychar=yytoken=yyeof_;YYCDEBUG<< "Now at end of input."<< std::endl;} else { yytoken=yytranslate_(yychar);YY_SYMBOL_PRINT("Next token is", yytoken, &yylval, &yylloc);} yyn+=yytoken;if(yyn< 0||yylast_< yyn||yycheck_[yyn] !=yytoken) goto yydefault;yyn=yytable_[yyn];if(yyn<=0) { if(yyn==0||yyn==yytable_ninf_) goto yyerrlab;yyn=-yyn;goto yyreduce;} YY_SYMBOL_PRINT("Shifting", yytoken, &yylval, &yylloc);yychar=yyempty_;yysemantic_stack_.push(yylval);yylocation_stack_.push(yylloc);if(yyerrstatus_) --yyerrstatus_;yystate=yyn;goto yynewstate;yydefault:yyn=yydefact_[yystate];if(yyn==0) goto yyerrlab;goto yyreduce;yyreduce:yylen=yyr2_[yyn];if(yylen) yyval=yysemantic_stack_[yylen - 1];else yyval=yysemantic_stack_[0];{ slice< location_type, location_stack_type > slice (yylocation_stack_, yylen)
static const int yyempty_
static const int yyeof_
static const int yyerrcode_
goto yyerrlab1
yyerror_range [0] = yylloc
static const int yyfinal_
static const int yylast_
yylen = 0
yyreturn & yylloc
location_stack_type yylocation_stack_ = location_stack_type (0)
The location stack.
yyreturn & yylval
yyn = yyr1_[yyn]
goto yynewstate
static const int yynnts_
static const int yyntokens_
return yyresult
goto yyreturn
semantic_stack_type yysemantic_stack_ = semantic_stack_type (0)
The semantic value stack.
yystate = yypgoto_[yyn - yyntokens_] + yystate_stack_[0]
state_stack_type yystate_stack_
The state stack.
static const int yyterror_
yyreturn yytoken
static const token_number_type yyundef_token_
static const unsigned int yyuser_token_number_max_
Macro Definition Documentation
BISON_STACK_HH
#define BISON_STACK_HH
PARSER_HEADER_H
#define PARSER_HEADER_H
YY_
#define YY_ (msgid) msgid
YY_REDUCE_PRINT
#define YY_REDUCE_PRINT (Rule)
YY_STACK_PRINT
YY_STACK_PRINT ()
Referenced by for().
YY_SYMBOL_PRINT
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
YYABORT
#define YYABORT goto yyabortlab
YYACCEPT
#define YYACCEPT goto yyacceptlab
YYCDEBUG
#define YYCDEBUG if (false) std::cerr
yyclearin
#define yyclearin (yychar = yyempty_)
YYDEBUG
#define YYDEBUG ]b4_debug_flag[
yyerrok
#define yyerrok (yyerrstatus_ = 0)
YYERROR
#define YYERROR goto yyerrorlab
YYERROR_VERBOSE
#define YYERROR_VERBOSE ]b4_error_verbose_flag[
yylex
#define yylex b4_prefix[]lex])[
YYLLOC_DEFAULT
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
do {                            \
  if (N)                        \
    {                           \
      (Current).begin = (Rhs)[1].begin;         \
      (Current).end   = (Rhs)[N].end;           \
    }                           \
  else                          \
    {                           \
      (Current).begin = (Current).end = (Rhs)[0].end;   \
    }                           \
} while (false)
YYRECOVERING
#define YYRECOVERING () (!!yyerrstatus_)
YYSTYPE
#define YYSTYPE b4_namespace_ref::b4_parser_class_name::semantic_type
YYTOKEN_TABLE
#define YYTOKEN_TABLE ]b4_token_table[
YYUSE
#define YYUSE (e) ((void) (e))
Typedef Documentation
location_stack_type
typedef stack<location_type> location_stack_type
location stack type.
Definition at line 183 of file lalr1.cc.
semantic_stack_type
typedef stack<semantic_type> semantic_stack_type
Semantic value stack type.
Definition at line 181 of file lalr1.cc.
state_stack_type
typedef stack<state_type> state_stack_type
State stack type.
Definition at line 179 of file lalr1.cc.
state_type
typedef int state_type
State numbers.
Definition at line 177 of file lalr1.cc.
token_type
typedef token::yytokentype token_type
Token type.
Definition at line 122 of file lalr1.cc.
Function Documentation
b4_defines_if()
b4_defines_if ([b4_fatal([b4_skeleton[: using %%defines is mandatory] ])
Build a parser object.
Definition at line 312 of file lalr1.cc.
    {                            \
   if (yydebug_)                     \
     {                           \
       *yycdebug_ << Title << ' ';           \
       yy_symbol_print_ ((Type), (Value), (Location));   \
       *yycdebug_ << std::endl;              \
     }                           \
 } while (false)
 # define YY_REDUCE_PRINT(Rule)      \
 do {                    \
   if (yydebug_)             \
     yy_reduce_print_ (Rule);        \
 } while (false)
 # define YY_STACK_PRINT()       \
 do {                    \
   if (yydebug_)             \
     yystack_print_ ();          \
 } while (false)
 #else /* !YYDEBUG */
 # define YYCDEBUG if (false) std::cerr
 # define YY_SYMBOL_PRINT(Title, Type, Value, Location)
 # define YY_REDUCE_PRINT(Rule)
 # define YY_STACK_PRINT()
 #endif /* !YYDEBUG */
 #define yyerrok     (yyerrstatus_ = 0)
 #define yyclearin   (yychar = yyempty_)
 #define YYACCEPT    goto yyacceptlab
 #define YYABORT     goto yyabortlab
 #define YYERROR     goto yyerrorlab
 #define YYRECOVERING()  (!!yyerrstatus_)
 ]b4_namespace_open[
 #if YYERROR_VERBOSE
   /* Return YYSTR after stripping away unnecessary quotes and
      backslashes, so that it's suitable for yyerror.  The heuristic is
      that double-quoting is unnecessary unless the string contains an
      apostrophe, a comma, or backslash (other than backslash-backslash).
      YYSTR is taken from yytname.  */
   std::string
   ]b4_parser_class_name[::yytnamerr_ (const char *yystr)
   {
     if (*yystr == '"')
       {
         std::string yyr = "";
         char const *yyp = yystr;
         for (;;)
           switch (*++yyp)
             {
             case '\'':
             case ',':
               goto do_not_strip_quotes;
             case '\\':
               if (*++yyp != '\\')
                 goto do_not_strip_quotes;
               /* Fall through.  */
             default:
               yyr += *yyp;
               break;
             case '"':
               return yyr;
             }
       do_not_strip_quotes: ;
       }
     return yystr;
   }
 #endif
   ]b4_parser_class_name::b4_parser_class_name[ (]b4_parse_param_decl[)]m4_ifset([b4_parse_param], [
     :])[
 #if YYDEBUG
     ]m4_ifset([b4_parse_param], [  ], [ :])[yydebug_ (false),
       yycdebug_ (&std::cerr)]m4_ifset([b4_parse_param], [,])[
 #endif]b4_parse_param_cons[
   {
   }
b4_int_type() [1/2]
static const b4_int_type (b4_pact_ninf , b4_pact_ninf) static
b4_int_type() [2/2]
static const b4_int_type (b4_table_ninf , b4_table_ninf) static
b4_int_type_for()
const b4_int_type_for ()
Internal symbol numbers.
For a rule, its RHS length.
For a rule, its LHS.
For a state, its accessing symbol.
What to do in a state.
For a state, default rule to reduce.
For a state, the index in yytable_ of its portion.
Unlessyytable_ specifies something else to do. Zero means the default is an error.
yytable_[yypact_[s]]: what to do in state s.
if positive, shift that token.
if negative, reduce the rule which number is the opposite.
if zero, do what YYDEFACT says.
Definition at line 885 of file lalr1.cc.
   {
     ]b4_pact[
   };
b4_percent_code_get()
dnl we want computed header guards [#define PARSER_HEADER_H] b4_percent_code_get ([[requires] ])
b4_percent_define_flag_if()
b4_parse_param_vars [ };] b4_namespace_close [] b4_percent_define_flag_if ([[global_tokens_and_yystype] ]))[]
error()
error (yylloc , yysyntax_error_(yystate]dnl b4_error_verbose_if([, yytoken])[))
for()
for (;;)
Definition at line 761 of file lalr1.cc.
       {
     yyn = yypact_[yystate];
     if (yyn != yypact_ninf_)
     {
       yyn += yyterror_;
       if (0 <= yyn && yyn <= yylast_ && yycheck_[yyn] == yyterror_)
         {
           yyn = yytable_[yyn];
           if (0 < yyn)
         break;
         }
     }
     /* Pop the current state because it cannot handle the error token.  */
     if (yystate_stack_.height () == 1)
     YYABORT;
     yyerror_range[0] = yylocation_stack_[0];
     yydestruct_ ("Error: popping",
              yystos_[yystate],
              &yysemantic_stack_[0], &yylocation_stack_[0]);
     yypop_ ();
     yystate = yystate_stack_[0];
     YY_STACK_PRINT ();
       }
References YY_STACK_PRINT, YYABORT, yydestruct_(), yyerror_range, yylast_, yylocation_stack_, yyn, yypop_(), yysemantic_stack_, yystate, yystate_stack_, and yyterror_.
Referenced by Cbuf_Execute(), CM_LoadMap(), color_quantize(), color_quantize3(), compress_data(), compress_first_pass(), compress_output(), compute_color(), Con_DrawSolidConsole(), Con_Dump_f(), construct(), consume_data(), create_odither_tables(), decode_mcu(), decode_mcu_AC_refine(), decompress_onepass(), expandlex(), filterbank_new(), forward_DCT(), forward_DCT_float(), h2v1_merged_upsample(), h2v2_merged_upsample(), jitter_buffer_ctl(), jpeg_CreateDecompress(), jpeg_idct_10x10(), jpeg_idct_10x5(), jpeg_idct_11x11(), jpeg_idct_12x12(), jpeg_idct_12x6(), jpeg_idct_13x13(), jpeg_idct_14x14(), jpeg_idct_14x7(), jpeg_idct_15x15(), jpeg_idct_16x16(), jpeg_idct_16x8(), jpeg_idct_2x4(), jpeg_idct_3x3(), jpeg_idct_3x6(), jpeg_idct_4x2(), jpeg_idct_4x4(), jpeg_idct_4x8(), jpeg_idct_5x10(), jpeg_idct_5x5(), jpeg_idct_6x12(), jpeg_idct_6x3(), jpeg_idct_6x6(), jpeg_idct_7x14(), jpeg_idct_7x7(), jpeg_idct_8x16(), jpeg_idct_8x4(), jpeg_idct_9x9(), jpeg_idct_float(), jpeg_idct_ifast(), jpeg_idct_islow(), make_funny_pointers(), nb_decoder_ctl(), nb_encode(), nb_encoder_ctl(), pass2_fs_dither(), pass2_no_dither(), preprocess_analysis(), prescan_quantize(), quantize3_ord_dither(), quantize_fs_dither(), quantize_ord_dither(), R_GetTag(), R_StitchPatches(), R_TryStitchingPatch(), RB_CalcBulgeVertexes(), RB_CalcColorFromEntity(), RB_CalcMoveVertexes(), RB_SurfaceGrid(), realize_virt_arrays(), reduce_script(), ResampleSfx(), ResampleSfxRaw(), S_PaintChannelFromMuLaw(), sb_decoder_ctl(), sb_encode(), sb_encoder_ctl(), select_scan_parameters(), sep_downsample(), set_bottom_pointers(), set_wraparound_pointers(), speex_echo_cancellation(), speex_echo_state_init(), speex_echo_state_reset(), speex_init_header(), speex_preprocess_estimate_update(), speex_preprocess_run(), speex_preprocess_state_init(), start_pass(), start_pass_fdctmgr(), and VM_Compile().
if() [1/2]
if (0<=yystate &&yystate<=yylast_ && yycheck_[yystate] = =yystate_stack_[0])
Referenced by __gnu_debug::_Error_formatter::_Parameter::_Parameter(), alloc_large(), alloc_small(), arith_encode(), CG_AddScorePlum(), CG_PredictPlayerState(), Con_DrawNotify(), consume_markers(), create_colorindex(), decode_mcu(), decode_mcu_AC_first(), decode_mcu_AC_refine(), decode_mcu_DC_first(), decode_mcu_DC_refine(), decode_mcu_sub(), empty_output_buffer(), encode_mcu(), encode_mcu_AC_first(), encode_mcu_AC_refine(), encode_mcu_DC_first(), encode_mcu_DC_refine(), encode_mcu_gather(), finish_output_pass(), finish_pass(), finish_pass_gather(), finish_pass_huff(), Fire_UserWeapon(), free_pool(), hashtable_symbol_exists(), inflate(), inflateEnd(), inflateGetHeader(), inflatePrime(), inflateSetDictionary(), inflateSync(), jinit_d_post_controller(), jpeg_make_c_derived_tbl(), jpeg_make_d_derived_tbl(), jpeg_mem_dest(), jpeg_new_colormap(), jpeg_set_marker_processor(), LookupSymbol(), MD5Update(), Menu_AdjustCursor(), Menu_Draw(), merged_2v_upsample(), Music_MenuInit(), post_process_1pass(), post_process_2pass(), post_process_prepass(), prepare_for_output_pass(), process_data_context_main(), process_data_simple_main(), process_restart(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_FixSharedVertexLodError(), R_FixSharedVertexLodError_r(), R_MovePatchSurfacesToHunk(), R_StitchAllPatches(), R_StitchPatches(), R_TryStitchingPatch(), RB_BeginSurface(), RB_MDM_SurfaceAnim(), RB_SurfaceRailRings(), reachable(), request_virt_barray(), request_virt_sarray(), S_Base_RawSamples(), S_TransferPaintBuffer(), ScrollList_Key(), sep_upsample(), smoothing_ok(), SNDDMA_Init(), speex_compute_agc(), speex_echo_playback(), speex_preprocess_run(), speex_preprocess_state_init(), start_iMCU_row(), start_output_pass(), start_pass(), start_pass_2_quant(), start_pass_coef(), start_pass_huff(), start_pass_huff_decoder(), start_pass_prep(), SV_ClipMoveToEntities(), term_destination(), UI_MouseEvent(), UI_PushMenu(), UI_RunLerpFrame(), unzOpenCurrentFile3(), unzReadCurrentFile(), update_box(), updatewindow(), VM_Compile(), and write_scan_header().
if() [2/2]
if (yyerrstatus_ = = 3)
Definition at line 713 of file lalr1.cc.
       {
     /* If just tried and failed to reuse lookahead token after an
      error, discard it.  */
     if (yychar <= yyeof_)
       {
       /* Return failure if at end of input.  */
       if (yychar == yyeof_)
         YYABORT;
       }
     else
       {
         yydestruct_ ("Error: discarding", yytoken, &yylval, &yylloc);
         yychar = yyempty_;
       }
       }
References YYABORT, yychar, yydestruct_(), yyempty_, yyeof_, yylloc, yylval, and yytoken.
m4_ifdef()
b4_namespace_close [#define YYDEBUG#define YYERROR_VERBOSE#define YYTOKEN_TABLE#define YYLLOC_DEFAULT(Current, Rhs, N) ] b4_namespace_open [ class ] b4_parser_class_name [ { public: ] m4_ifdef ([m4_if(b4_tag_seen_flag, 0, [[typedef int semantic_type;] ] , [[typedef YYSTYPE semantic_type;] ]))[typedef]
Symbol locations.
m4_include()
m4_include (b4_pkgdatadir/ [c++.m4])
output()
b4_parser_class_name [::token_number_type ] b4_parser_class_name [::yytranslate_ (int t) { static const token_number_type translate_table[] = { ] b4_translate [ }; if ((unsigned int) t <= yyuser_token_number_max_) return translate_table[t]; else return yyundef_token_; } const int ] b4_parser_class_name [::yyeof_ = 0; const int ] b4_parser_class_name [::yylast_ = ] b4_last [; const int ] b4_parser_class_name [::yynnts_ = ] b4_nterms_number [; const int ] b4_parser_class_name [::yyempty_ = -2; const int ] b4_parser_class_name [::yyfinal_ = ] b4_final_state_number [; const int ] b4_parser_class_name [::yyterror_ = 1; const int ] b4_parser_class_name [::yyerrcode_ = 256; const int ] b4_parser_class_name [::yyntokens_ = ] b4_tokens_number [; const unsigned int ] b4_parser_class_name [::yyuser_token_number_max_ = ] b4_user_token_number_max [; const ] b4_parser_class_name [::token_number_type ] b4_parser_class_name [::yyundef_token_ = ] b4_undef_token_number [;] b4_namespace_close [] b4_epilogue dnl output (b4_dir_prefix[]stack.hh@)
Referenced by OrderMesh().
push() [1/4]
yylocation_stack_ push (yylloc)
push() [2/4]
yylocation_stack_ push (yyloc)
push() [3/4]
yysemantic_stack_ push (yylval)
Referenced by _GLIBCXX_VISIBILITY().
push() [4/4]
yysemantic_stack_ push (yyval)
switch()
switch (yyn)
Definition at line 675 of file lalr1.cc.
       {
     ]b4_user_actions[
     default:
           break;
       }
Referenced by prepare_for_pass(), start_pass_1_quant(), and start_pass_main().
while()
while (yystate_stack_.height() ! = 1)
Definition at line 819 of file lalr1.cc.
       {
     yydestruct_ ("Cleanup: popping",
            yystos_[yystate_stack_[0]],
            &yysemantic_stack_[0],
            &yylocation_stack_[0]);
     yypop_ ();
       }
References yydestruct_(), yylocation_stack_, yypop_(), yysemantic_stack_, and yystate_stack_.
Referenced by arith_decode(), cmyk_ycck_convert(), decompress_data(), decompress_smooth_data(), int_upsample(), pre_process_context(), pre_process_data(), process_data_simple_main(), rgb_gray_convert(), rgb_ycc_convert(), unzReadCurrentFile(), ycc_rgb_convert(), and ycck_cmyk_convert().
YY_REDUCE_PRINT()
YY_REDUCE_PRINT (yyn)
YY_SYMBOL_PRINT() [1/2]
YY_SYMBOL_PRINT ()
YY_SYMBOL_PRINT() [2/2]
YY_SYMBOL_PRINT ("Shifting" , yystos_ [yyn], & yysemantic_stack_[0], & yylocation_stack_[0])
yydestruct_()
void yydestruct_ (const char * yymsg, int yytype, semantic_type * yyvaluep, location_type * yylocationp) inline
Reclaim the memory associated to a symbol.
Parameters
yymsg Why this token is reclaimed.
yytype The symbol type.
yyvaluep Its semantic value.
yylocationp Its location.
Referenced by for(), if(), and while().
YYLLOC_DEFAULT() [1/2]
YYLLOC_DEFAULT (yyloc , slice , yylen)
YYLLOC_DEFAULT() [2/2]
YYLLOC_DEFAULT (yyloc , (yyerror_range - 1) , 2)
yypop_() [1/2]
void yypop_ (unsigned int n = 1) inline
Pop n symbols the three stacks.
Referenced by for(), and while().
yypop_() [2/2]
yypop_ (yylen)
yytranslate_()
token_number_type yytranslate_ (int t)
Convert a scanner token number t to a symbol number.
Variable Documentation
__pad0__
yynewstate __pad0__
Definition at line 572 of file lalr1.cc.
__pad1__
yyerrlab __pad1__
Definition at line 707 of file lalr1.cc.
__pad2__
yyerrorlab __pad2__
Definition at line 745 of file lalr1.cc.
__pad3__
yyerrlab1 __pad3__
Definition at line 759 of file lalr1.cc.
__pad4__
yyacceptlab __pad4__
Definition at line 804 of file lalr1.cc.
__pad5__
yyabortlab __pad5__
Definition at line 809 of file lalr1.cc.
__pad6__
yyreturn __pad6__
Definition at line 814 of file lalr1.cc.
b4_error_verbose_if
b4_parser_class_name [ (] b4_parse_param_decl [); virtual ~] b4_parser_class_name [ (); virtual int parse (); private: virtual void error (const location_type& loc, const std::string& msg); virtual std::string yysyntax_error_ (int yystate] dnl b4_error_verbose_if([, int tok])[)
Build a parser object.
Definition at line 156 of file lalr1.cc.
FIXME
dnl FIXME
Definition at line 38 of file lalr1.cc.
m4_ifdef
b4_parser_class_name::~b4_parser_class_name [ () { } void ] b4_parser_class_name [::yydestruct_ (const char* yymsg, int yytype, semantic_type* yyvaluep, location_type* yylocationp) { YYUSE (yylocationp); YYUSE (yymsg); YYUSE (yyvaluep); YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp); switch (yytype) { ] m4_map (m4_ifdef[b4_symbol_actions], m4_defn([b4_symbol_destructors]))[ default void b4_parser_class_name [::yypop_ (unsigned int n) { yystate_stack_.pop (n); yysemantic_stack_.pop (n); yylocation_stack_.pop (n); } int ] b4_parser_class_name [::parse () { int yychar = yyempty_; int yytoken = 0; int yyn; int yylen = 0; int yystate = 0; int yynerrs_ = 0; int yyerrstatus_ = 0; semantic_type yylval; location_type yylloc; location_type yyerror_range[2]; semantic_type yyval; location_type yyloc; int yyresult; YYCDEBUG << "Starting parse" << std::endl;]([b4_initial_action],[m4_pushdef([b4_at_dollar],[yylloc]) dnl m4_pushdef([b4_dollar_dollar],[yylval]) dnl b4_user_initial_action m4_popdef([b4_dollar_dollar]) dnl m4_popdef([b4_at_dollar])]) dnl[ yystate_stack_ = state_stack_type (0)
Definition at line 552 of file lalr1.cc.
slice
YYCDEBUG<< "Entering state " << yystate << std::endl; if (yystate == yyfinal_) goto yyacceptlab; goto yybackup; yybackup: yyn = yypact_[yystate]; if (yyn == yypact_ninf_) goto yydefault; if (yychar == yyempty_) { YYCDEBUG << "Reading a token: "; yychar = ]b4_c_function_call([yylex], [int], []dnlb4_locations_if([, ])dnlm4_ifdef([b4_lex_param], [, ]b4_lex_param))[; } if (yychar <= yyeof_) { yychar = yytoken = yyeof_; YYCDEBUG << "Now at end of input." << std::endl; } else { yytoken = yytranslate_ (yychar); YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc); } yyn += yytoken; if (yyn < 0 || yylast_ < yyn || yycheck_[yyn] != yytoken) goto yydefault; yyn = yytable_[yyn]; if (yyn <= 0) { if (yyn == 0 || yyn == yytable_ninf_) goto yyerrlab; yyn = -yyn; goto yyreduce; } YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc); yychar = yyempty_; yysemantic_stack_.push (yylval); yylocation_stack_.push (yylloc); if (yyerrstatus_) --yyerrstatus_; yystate = yyn; goto yynewstate; yydefault: yyn = yydefact_[yystate]; if (yyn == 0) goto yyerrlab; goto yyreduce; yyreduce: yylen = yyr2_[yyn]; if (yylen) yyval = yysemantic_stack_[yylen - 1]; else yyval = yysemantic_stack_[0]; { slice<location_type, location_stack_type> slice(yylocation_stack_, yylen)
Definition at line 671 of file lalr1.cc.
Referenced by _GLIBCXX_VISIBILITY().
yyempty_
const int yyempty_ static
Definition at line 277 of file lalr1.cc.
Referenced by if().
yyeof_
const int yyeof_ static
Definition at line 273 of file lalr1.cc.
Referenced by if().
yyerrcode_
const int yyerrcode_ static
Definition at line 280 of file lalr1.cc.
yyerrlab1
goto yyerrlab1
Definition at line 733 of file lalr1.cc.
Referenced by yyparse().
yyerror_range
yyerror_range[1] = yylloc
Definition at line 712 of file lalr1.cc.
Referenced by for().
yyfinal_
const int yyfinal_ static
Definition at line 278 of file lalr1.cc.
yylast_
const int yylast_ static
Definition at line 275 of file lalr1.cc.
Referenced by for().
yylen
yylen = 0
Definition at line 684 of file lalr1.cc.
Referenced by yyparse().
yylloc
yyreturn & yylloc
Definition at line 814 of file lalr1.cc.
Referenced by if(), and yyparse().
yylocation_stack_
yylocation_stack_ = location_stack_type (0)
The location stack.
Definition at line 190 of file lalr1.cc.
Referenced by for(), and while().
yylval
yyreturn & yylval
Definition at line 814 of file lalr1.cc.
Referenced by if().
yyn
yyn = yyr1_[yyn]
Definition at line 691 of file lalr1.cc.
Referenced by for(), and yyparse().
yynewstate
goto yynewstate
Definition at line 698 of file lalr1.cc.
Referenced by yyparse().
yynnts_
const int yynnts_ static
Definition at line 276 of file lalr1.cc.
yyntokens_
const int yyntokens_ static
Definition at line 281 of file lalr1.cc.
yyresult
return yyresult
Definition at line 828 of file lalr1.cc.
Referenced by yyparse().
yyreturn
goto yyreturn
Definition at line 805 of file lalr1.cc.
Referenced by yyparse().
yysemantic_stack_
yysemantic_stack_ = semantic_stack_type (0)
The semantic value stack.
Definition at line 188 of file lalr1.cc.
Referenced by for(), and while().
yystate
else yystate = yypgoto_[yyn - yyntokens_] + yystate_stack_[0]
Definition at line 692 of file lalr1.cc.
Referenced by for(), and yyparse().
yystate_stack_
state_stack_type yystate_stack_
The state stack.
Definition at line 186 of file lalr1.cc.
Referenced by for(), and while().
yyterror_
const int yyterror_ static
Definition at line 279 of file lalr1.cc.
Referenced by for().
yytoken
yyreturn yytoken
Definition at line 814 of file lalr1.cc.
Referenced by if(), and yyparse().
yyundef_token_
const token_number_type yyundef_token_ static
Definition at line 283 of file lalr1.cc.
yyuser_token_number_max_
const unsigned int yyuser_token_number_max_ static
Definition at line 282 of file lalr1.cc.