ZEQ2-Lite: __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator > Class Template Reference
__gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator > Class Template Reference
#include <point_iterators.hpp>
Public Types
typedef Const_Pointer const_pointer
typedef Const_Reference const_reference
typedef Allocator::difference_type difference_type
typedef std::bidirectional_iterator_tag iterator_category
typedef Pointer pointer
typedef Reference reference
typedef Value_Type value_type
Public Member Functions
bin_search_tree_const_it_ (const Node_Pointer p_nd=0)
bin_search_tree_const_it_ (const PB_DS_TREE_CONST_ODIR_IT_C_DEC &other)
bool operator!= (const PB_DS_TREE_CONST_IT_C_DEC &other) const
bool operator!= (const PB_DS_TREE_CONST_ODIR_IT_C_DEC &other) const
const_reference operator* () const
PB_DS_TREE_CONST_IT_C_DEC & operator++ ()
PB_DS_TREE_CONST_IT_C_DEC operator++ (int)
PB_DS_TREE_CONST_IT_C_DEC & operator-- ()
PB_DS_TREE_CONST_IT_C_DEC operator-- (int)
const_pointer operator-> () const
PB_DS_TREE_CONST_IT_C_DEC & operator= (const PB_DS_TREE_CONST_IT_C_DEC &other)
PB_DS_TREE_CONST_IT_C_DEC & operator= (const PB_DS_TREE_CONST_ODIR_IT_C_DEC &other)
bool operator== (const PB_DS_TREE_CONST_IT_C_DEC &other) const
bool operator== (const PB_DS_TREE_CONST_ODIR_IT_C_DEC &other) const
Data Fields
Node_Pointer m_p_nd
Protected Member Functions
void dec (false_type)
void dec (true_type)
void inc (false_type)
void inc (true_type)
Detailed Description
template<typename Node_Pointer, typename Value_Type, typename Pointer, typename Const_Pointer, typename Reference, typename Const_Reference, bool Is_Forward_Iterator, class Allocator>
class __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >
Definition at line 105 of file point_iterators.hpp.
Member Typedef Documentation
const_pointer
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > typedef Const_Pointer __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::const_pointer
Definition at line 118 of file point_iterators.hpp.
const_reference
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > typedef Const_Reference __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::const_reference
Definition at line 122 of file point_iterators.hpp.
difference_type
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > typedef Allocator::difference_type __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::difference_type
Definition at line 112 of file point_iterators.hpp.
iterator_category
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > typedef std::bidirectional_iterator_tag __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::iterator_category
Definition at line 110 of file point_iterators.hpp.
pointer
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > typedef Pointer __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::pointer
Definition at line 116 of file point_iterators.hpp.
reference
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > typedef Reference __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::reference
Definition at line 120 of file point_iterators.hpp.
value_type
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > typedef Value_Type __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::value_type
Definition at line 114 of file point_iterators.hpp.
Constructor & Destructor Documentation
bin_search_tree_const_it_() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::bin_search_tree_const_it_ (const Node_Pointer p_nd = 0) inline
Definition at line 127 of file point_iterators.hpp.
       : m_p_nd(const_cast<Node_Pointer>(p_nd))
       { }
bin_search_tree_const_it_() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::bin_search_tree_const_it_ (const PB_DS_TREE_CONST_ODIR_IT_C_DEC & other) inline
Definition at line 132 of file point_iterators.hpp.
       : m_p_nd(other.m_p_nd)
       { }
Member Function Documentation
dec() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > void __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::dec (false_type) inline protected
Definition at line 248 of file point_iterators.hpp.
       { inc(true_type()); }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::inc().
Referenced by __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::inc(), and __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator--().
dec() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > void __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::dec (true_type) inline protected
Definition at line 252 of file point_iterators.hpp.
       {
     if (m_p_nd->special() && m_p_nd->m_p_parent->m_p_parent == m_p_nd)
       {
         m_p_nd = m_p_nd->m_p_right;
         return;
       }
     if (m_p_nd->m_p_left != 0)
       {
         Node_Pointer p_y = m_p_nd->m_p_left;
         while (p_y->m_p_right != 0)
           p_y = p_y->m_p_right;
         m_p_nd = p_y;
         return;
       }
     Node_Pointer p_y = m_p_nd->m_p_parent;
     while (m_p_nd == p_y->m_p_left)
       {
         m_p_nd = p_y;
         p_y = p_y->m_p_parent;
       }
     if (m_p_nd->m_p_left != p_y)
       m_p_nd = p_y;
       }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
inc() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > void __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::inc (false_type) inline protected
Definition at line 215 of file point_iterators.hpp.
       { dec(true_type()); }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::dec().
Referenced by __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::dec(), and __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++().
inc() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > void __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::inc (true_type) inline protected
Definition at line 219 of file point_iterators.hpp.
       {
     if (m_p_nd->special()&&
         m_p_nd->m_p_parent->m_p_parent == m_p_nd)
       {
         m_p_nd = m_p_nd->m_p_left;
         return;
       }
     if (m_p_nd->m_p_right != 0)
       {
         m_p_nd = m_p_nd->m_p_right;
         while (m_p_nd->m_p_left != 0)
           m_p_nd = m_p_nd->m_p_left;
         return;
       }
     Node_Pointer p_y = m_p_nd->m_p_parent;
     while (m_p_nd == p_y->m_p_right)
       {
         m_p_nd = p_y;
         p_y = p_y->m_p_parent;
       }
     if (m_p_nd->m_p_right != p_y)
       m_p_nd = p_y;
       }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
operator!=() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > bool __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator!= (const PB_DS_TREE_CONST_IT_C_DEC & other) const inline
Definition at line 175 of file point_iterators.hpp.
       { return m_p_nd != other.m_p_nd; }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
operator!=() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > bool __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator!= (const PB_DS_TREE_CONST_ODIR_IT_C_DEC & other) const inline
Definition at line 179 of file point_iterators.hpp.
       { return m_p_nd != other.m_p_nd; }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
operator*()
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > const_reference __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator* () const inline
Definition at line 160 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_p_nd != 0);
     return m_p_nd->m_value;
       }
References _GLIBCXX_DEBUG_ASSERT, and __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
operator++() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_CONST_IT_C_DEC& __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++ () inline
Definition at line 183 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_p_nd != 0);
     inc(integral_constant<int,Is_Forward_Iterator>());
     return *this;
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::inc(), and __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
Referenced by __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++().
operator++() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_CONST_IT_C_DEC __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++ (int) inline
Definition at line 191 of file point_iterators.hpp.
       {
     PB_DS_TREE_CONST_IT_C_DEC ret_it(m_p_nd);
     operator++();
     return ret_it;
       }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd, and __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++().
operator--() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_CONST_IT_C_DEC& __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator-- () inline
Definition at line 199 of file point_iterators.hpp.
       {
     dec(integral_constant<int,Is_Forward_Iterator>());
     return *this;
       }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::dec().
Referenced by __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator--().
operator--() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_CONST_IT_C_DEC __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator-- (int) inline
Definition at line 206 of file point_iterators.hpp.
       {
     PB_DS_TREE_CONST_IT_C_DEC ret_it(m_p_nd);
     operator--();
     return ret_it;
       }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd, and __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator--().
operator->()
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > const_pointer __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator-> () const inline
Definition at line 153 of file point_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_p_nd != 0);
     return &m_p_nd->m_value;
       }
References _GLIBCXX_DEBUG_ASSERT, and __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
operator=() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_CONST_IT_C_DEC& __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator= (const PB_DS_TREE_CONST_IT_C_DEC & other) inline
Definition at line 138 of file point_iterators.hpp.
       {
     m_p_nd = other.m_p_nd;
     return *this;
       }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
operator=() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > PB_DS_TREE_CONST_IT_C_DEC& __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator= (const PB_DS_TREE_CONST_ODIR_IT_C_DEC & other) inline
Definition at line 146 of file point_iterators.hpp.
       {
     m_p_nd = other.m_p_nd;
     return *this;
       }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
operator==() [1/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > bool __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator== (const PB_DS_TREE_CONST_IT_C_DEC & other) const inline
Definition at line 167 of file point_iterators.hpp.
       { return m_p_nd == other.m_p_nd; }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
operator==() [2/2]
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > bool __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator== (const PB_DS_TREE_CONST_ODIR_IT_C_DEC & other) const inline
Definition at line 171 of file point_iterators.hpp.
       { return m_p_nd == other.m_p_nd; }
References __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd.
Field Documentation
m_p_nd
template<typename Node_Pointer , typename Value_Type , typename Pointer , typename Const_Pointer , typename Reference , typename Const_Reference , bool Is_Forward_Iterator, class Allocator > Node_Pointer __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::m_p_nd
Definition at line 280 of file point_iterators.hpp.
Referenced by __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::dec(), __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::inc(), __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator!=(), __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator*(), __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator++(), __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator--(), __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator->(), __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator=(), and __gnu_pbds::detail::bin_search_tree_const_it_< Node_Pointer, Value_Type, Pointer, Const_Pointer, Reference, Const_Reference, Is_Forward_Iterator, Allocator >::operator==().
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/bin_search_tree_/point_iterators.hpp