ZEQ2-Lite: Source/Engine/libspeex/math_approx.h File Reference
math_approx.h File Reference
Various math approximation functions for Speex.
#include "arch.h"
Macros
#define C1 0.9999932946f
#define C2 -0.4999124376f
#define C3 0.0414877472f
#define C4 -0.0012712095f
#define M_PI 3.14159265358979323846 /* pi */
#define spx_acos acos
#define spx_atan atan
#define spx_cos_norm(x) (cos((.5f*M_PI)*(x)))
#define spx_exp exp
#define SPX_PI_2 1.5707963268
#define spx_sqrt sqrt
Functions
static spx_word16_t speex_rand (spx_word16_t std, spx_int32_t *seed)
Generate a pseudo-random number.
static spx_word16_t spx_cos (spx_word16_t x)
static spx_int16_t spx_ilog2 (spx_uint32_t x)
static spx_int16_t spx_ilog4 (spx_uint32_t x)
Detailed Description
Various math approximation functions for Speex.
Definition in file math_approx.h.
Macro Definition Documentation
C1
#define C1 0.9999932946f
Definition at line 309 of file math_approx.h.
C2
#define C2 -0.4999124376f
Definition at line 310 of file math_approx.h.
C3
#define C3 0.0414877472f
Definition at line 311 of file math_approx.h.
C4
#define C4 -0.0012712095f
Definition at line 312 of file math_approx.h.
M_PI
#define M_PI 3.14159265358979323846 /* pi */
Definition at line 306 of file math_approx.h.
spx_acos
#define spx_acos acos
Definition at line 43 of file math_approx.h.
spx_atan
#define spx_atan atan
Definition at line 46 of file math_approx.h.
spx_cos_norm
#define spx_cos_norm (x) (cos((.5f*M_PI)*(x)))
Definition at line 45 of file math_approx.h.
spx_exp
#define spx_exp exp
Definition at line 44 of file math_approx.h.
SPX_PI_2
#define SPX_PI_2 1.5707963268
Definition at line 315 of file math_approx.h.
spx_sqrt
#define spx_sqrt sqrt
Definition at line 42 of file math_approx.h.
Function Documentation
speex_rand()
static spx_word16_t speex_rand (spx_word16_t std, spx_int32_t * seed) inline static
Generate a pseudo-random number.
Definition at line 49 of file math_approx.h.
 {
    const unsigned int jflone = 0x3f800000;
    const unsigned int jflmsk = 0x007fffff;
    union {int i; float f;} ran;
    *seed = 1664525 * *seed + 1013904223;
    ran.i = jflone | (jflmsk & *seed);
    ran.f -= 1.5;
    return 3.4642*std*ran.f;
 }
Referenced by nb_decode(), nb_decode_lost(), noise_codebook_unquant(), and sb_decode_lost().
spx_cos()
static spx_word16_t spx_cos (spx_word16_t x) inline static
Definition at line 316 of file math_approx.h.
 {
    if (x<SPX_PI_2)
    {
       x *= x;
       return C1 + x*(C2+x*(C3+C4*x));
    } else {
       x = M_PI-x;
       x *= x;
       return NEG16(C1 + x*(C2+x*(C3+C4*x)));
    }
 }
References C1, C2, C3, C4, M_PI, NEG16, and SPX_PI_2.
Referenced by speex_echo_state_init().
spx_ilog2()
static spx_int16_t spx_ilog2 (spx_uint32_t x) inline static
Definition at line 64 of file math_approx.h.
 {
    int r=0;
    if (x>=(spx_int32_t)65536)
    {
       x >>= 16;
       r += 16;
    }
    if (x>=256)
    {
       x >>= 8;
       r += 8;
    }
    if (x>=16)
    {
       x >>= 4;
       r += 4;
    }
    if (x>=4)
    {
       x >>= 2;
       r += 2;
    }
    if (x>=2)
    {
       r += 1;
    }
    return r;
 }
Referenced by preprocess_analysis(), and speex_encode_stereo_int().
spx_ilog4()
static spx_int16_t spx_ilog4 (spx_uint32_t x) inline static
Definition at line 94 of file math_approx.h.
 {
    int r=0;
    if (x>=(spx_int32_t)65536)
    {
       x >>= 16;
       r += 8;
    }
    if (x>=256)
    {
       x >>= 8;
       r += 4;
    }
    if (x>=16)
    {
       x >>= 4;
       r += 2;
    }
    if (x>=4)
    {
       r += 1;
    }
    return r;
 }