ZEQ2-Lite: Engine/libspeex/smallft.h File Reference
smallft.h File Reference
Discrete Rotational Fourier Transform (DRFT)
Data Structures
struct drft_lookup
Discrete Rotational Fourier Transform lookup.
Functions
void spx_drft_backward (struct drft_lookup *l, float *data)
void spx_drft_clear (struct drft_lookup *l)
void spx_drft_forward (struct drft_lookup *l, float *data)
void spx_drft_init (struct drft_lookup *l, int n)
Detailed Description
Discrete Rotational Fourier Transform (DRFT)
Definition in file smallft.h.
Function Documentation
spx_drft_backward()
void spx_drft_backward (struct drft_lookup * l, float * data)
Definition at line 1239 of file smallft.c.
{
   if (l->n==1)return;
   drftb1(l->n,data,l->trigcache,l->trigcache+l->n,l->splitcache);
 }
References drftb1(), drft_lookup::n, drft_lookup::splitcache, and drft_lookup::trigcache.
spx_drft_clear()
void spx_drft_clear (struct drft_lookup * l)
Definition at line 1252 of file smallft.c.
 {
   if(l)
   {
     if(l->trigcache)
       speex_free(l->trigcache);
     if(l->splitcache)
       speex_free(l->splitcache);
   }
 }
References speex_free(), drft_lookup::splitcache, and drft_lookup::trigcache.
spx_drft_forward()
void spx_drft_forward (struct drft_lookup * l, float * data)
Definition at line 1234 of file smallft.c.
{
   if(l->n==1)return;
   drftf1(l->n,data,l->trigcache,l->trigcache+l->n,l->splitcache);
 }
References drftf1(), drft_lookup::n, drft_lookup::splitcache, and drft_lookup::trigcache.
spx_drft_init()
void spx_drft_init (struct drft_lookup * l, int n)
Definition at line 1244 of file smallft.c.
 {
   l->n=n;
   l->trigcache=(float*)speex_alloc(3*n*sizeof(*l->trigcache));
   l->splitcache=(int*)speex_alloc(32*sizeof(*l->splitcache));
   fdrffti(n, l->trigcache, l->splitcache);
 }
References fdrffti(), drft_lookup::n, speex_alloc(), drft_lookup::splitcache, and drft_lookup::trigcache.