ZEQ2-Lite: Tools/MinGW/include/winsock.h File Reference
winsock.h File Reference
#include <windows.h>
#include <mswsock.h>
Data Structures
struct LPFD_SET
struct LPHOSTENT
struct LPIN_ADDR
struct ip_mreq
struct LPLINGER
struct netent
struct LPPROTOENT
struct LPSERVENT
struct LPSOCKADDR
struct LPSOCKADDR_IN
struct sockproto
struct LPTIMEVAL
struct WSAData
Macros
#define _BSDTYPES_DEFINED
#define _GNU_H_WINDOWS32_SOCKETS
#define _IO(x, y) (IOC_VOID|((x)<<8)|(y))
#define _IOR(x, y, t) (IOC_OUT|(((long)sizeof(t)&IOCPARM_MASK)<<16)|((x)<<8)|(y))
#define _IOW(x, y, t) (IOC_IN|(((long)sizeof(t)&IOCPARM_MASK)<<16)|((x)<<8)|(y))
#define _TIMEVAL_DEFINED
#define AF_APPLETALK 16
#define AF_ATM 22
#define AF_BAN 21
#define AF_CCITT 10
#define AF_CHAOS 5
#define AF_DATAKIT 9
#define AF_DECnet 12
#define AF_DLI 13
#define AF_ECMA 8
#define AF_FIREFOX 19
#define AF_HYLINK 15
#define AF_IMPLINK 3
#define AF_INET 2
#define AF_INET6 23
#define AF_IPX 6
#define AF_ISO 7
#define AF_LAT 14
#define AF_MAX 24
#define AF_NETBIOS 17
#define AF_NS 6
#define AF_OSI AF_ISO
#define AF_PUP 4
#define AF_SNA 11
#define AF_UNIX 1
#define AF_UNKNOWN1 20
#define AF_UNSPEC 0
#define AF_VOICEVIEW 18
#define FD_ACCEPT 8
#define FD_CLOSE 32
#define FD_CLR(fd, set)
#define FD_CONNECT 16
#define FD_ISSET(fd, set) __WSAFDIsSet((SOCKET)(fd), (fd_set *)(set))
#define FD_OOB 4
#define FD_READ 1
#define FD_SET(fd, set)
#define FD_SETSIZE 64
#define FD_WRITE 2
#define FD_ZERO(set) (((fd_set *)(set))->fd_count=0)
#define FIOASYNC _IOW('f', 125, u_long)
#define FIONBIO _IOW('f', 126, u_long)
#define FIONREAD _IOR('f', 127, u_long)
#define h_addr h_addr_list[0]
#define h_errno WSAGetLastError()
#define HOST_NOT_FOUND WSAHOST_NOT_FOUND
#define IMPLINK_HIGHEXPER 158
#define IMPLINK_IP 155
#define IMPLINK_LOWEXPER 156
#define IN_CLASSA(i) (((long)(i)&0x80000000) == 0)
#define IN_CLASSA_HOST 0x00ffffff
#define IN_CLASSA_MAX 128
#define IN_CLASSA_NET 0xff000000
#define IN_CLASSA_NSHIFT 24
#define IN_CLASSB(i) (((long)(i)&0xc0000000)==0x80000000)
#define IN_CLASSB_HOST 0x0000ffff
#define IN_CLASSB_MAX 65536
#define IN_CLASSB_NET 0xffff0000
#define IN_CLASSB_NSHIFT 16
#define IN_CLASSC(i) (((long)(i)&0xe0000000)==0xc0000000)
#define IN_CLASSC_HOST 0xff
#define IN_CLASSC_NET 0xffffff00
#define IN_CLASSC_NSHIFT 8
#define INADDR_ANY (u_long)0
#define INADDR_BROADCAST (u_long)0xffffffff
#define INADDR_LOOPBACK 0x7f000001
#define INADDR_NONE 0xffffffff
#define INVALID_SOCKET (SOCKET)(~0)
#define IOC_IN 0x80000000
#define IOC_INOUT (IOC_IN|IOC_OUT)
#define IOC_OUT 0x40000000
#define IOC_VOID 0x20000000
#define IOCPARM_MASK 0x7f
#define IP_ADD_MEMBERSHIP 5
#define IP_DEFAULT_MULTICAST_LOOP 1
#define IP_DEFAULT_MULTICAST_TTL 1
#define IP_DROP_MEMBERSHIP 6
#define IP_MAX_MEMBERSHIPS 20
#define IP_MULTICAST_IF 2
#define IP_MULTICAST_LOOP 4
#define IP_MULTICAST_TTL 3
#define IP_OPTIONS 1
#define IPPORT_BIFFUDP 512
#define IPPORT_CMDSERVER 514
#define IPPORT_DAYTIME 13
#define IPPORT_DISCARD 9
#define IPPORT_ECHO 7
#define IPPORT_EFSSERVER 520
#define IPPORT_EXECSERVER 512
#define IPPORT_FINGER 79
#define IPPORT_FTP 21
#define IPPORT_LOGINSERVER 513
#define IPPORT_MTP 57
#define IPPORT_NAMESERVER 42
#define IPPORT_NETSTAT 15
#define IPPORT_RESERVED 1024
#define IPPORT_RJE 77
#define IPPORT_ROUTESERVER 520
#define IPPORT_SMTP 25
#define IPPORT_SUPDUP 95
#define IPPORT_SYSTAT 11
#define IPPORT_TELNET 23
#define IPPORT_TFTP 69
#define IPPORT_TIMESERVER 37
#define IPPORT_TTYLINK 87
#define IPPORT_WHOIS 43
#define IPPORT_WHOSERVER 513
#define IPPROTO_GGP 3
#define IPPROTO_ICMP 1
#define IPPROTO_IDP 22
#define IPPROTO_IGMP 2
#define IPPROTO_IP 0
#define IPPROTO_MAX 256
#define IPPROTO_ND 77
#define IPPROTO_PUP 12
#define IPPROTO_RAW 255
#define IPPROTO_TCP 6
#define IPPROTO_UDP 17
#define MAXGETHOSTSTRUCT 1024
#define MSG_DONTROUTE 4
#define MSG_MAXIOVLEN 16
#define MSG_OOB 1
#define MSG_PARTIAL 0x8000
#define MSG_PEEK 2
#define NO_ADDRESS WSANO_ADDRESS
#define NO_DATA WSANO_DATA
#define NO_RECOVERY WSANO_RECOVERY
#define PF_APPLETALK AF_APPLETALK
#define PF_ATM AF_ATM
#define PF_BAN AF_BAN
#define PF_CCITT AF_CCITT
#define PF_CHAOS AF_CHAOS
#define PF_DATAKIT AF_DATAKIT
#define PF_DECnet AF_DECnet
#define PF_DLI AF_DLI
#define PF_ECMA AF_ECMA
#define PF_FIREFOX AF_FIREFOX
#define PF_HYLINK AF_HYLINK
#define PF_IMPLINK AF_IMPLINK
#define PF_INET AF_INET
#define PF_INET6 AF_INET6
#define PF_IPX AF_IPX
#define PF_ISO AF_ISO
#define PF_LAT AF_LAT
#define PF_MAX AF_MAX
#define PF_NS AF_NS
#define PF_OSI AF_OSI
#define PF_PUP AF_PUP
#define PF_SNA AF_SNA
#define PF_UNIX AF_UNIX
#define PF_UNKNOWN1 AF_UNKNOWN1
#define PF_UNSPEC AF_UNSPEC
#define PF_VOICEVIEW AF_VOICEVIEW
#define s_addr S_un.S_addr
#define s_host S_un.S_un_b.s_b2
#define s_imp S_un.S_un_w.s_w2
#define s_impno S_un.S_un_b.s_b4
#define s_lh S_un.S_un_b.s_b3
#define s_net S_un.S_un_b.s_b1
#define SD_BOTH 0x02
#define SD_RECEIVE 0x00
#define SD_SEND 0x01
#define SIOCATMARK _IOR('s', 7, u_long)
#define SIOCGHIWAT _IOR('s', 1, u_long)
#define SIOCGLOWAT _IOR('s', 3, u_long)
#define SIOCSHIWAT _IOW('s', 0, u_long)
#define SIOCSLOWAT _IOW('s', 2, u_long)
#define SO_ACCEPTCONN 2
#define SO_BROADCAST 32
#define SO_DEBUG 1
#define SO_DONTLINGER (u_int)(~SO_LINGER)
#define SO_DONTROUTE 16
#define SO_ERROR 0x1007
#define SO_KEEPALIVE 8
#define SO_LINGER 128
#define SO_OOBINLINE 256
#define SO_RCVBUF 0x1002
#define SO_RCVLOWAT 0x1004
#define SO_RCVTIMEO 0x1006
#define SO_REUSEADDR 4
#define SO_SNDBUF 0x1001
#define SO_SNDLOWAT 0x1003
#define SO_SNDTIMEO 0x1005
#define SO_TYPE 0x1008
#define SO_USELOOPBACK 64
#define SOCK_DGRAM 2
#define SOCK_RAW 3
#define SOCK_RDM 4
#define SOCK_SEQPACKET 5
#define SOCK_STREAM 1
#define SOCKET_ERROR (-1)
#define SOL_SOCKET 0xffff
#define SOMAXCONN 5
#define TCP_NODELAY 0x0001
#define timerclear(tvp) (tvp)->tv_sec = (tvp)->tv_usec = 0
#define timercmp(tvp, uvp, cmp)
#define timerisset(tvp) ((tvp)->tv_sec || (tvp)->tv_usec)
#define TRY_AGAIN WSATRY_AGAIN
#define WSADESCRIPTION_LEN 256
#define WSAGETASYNCBUFLEN(l) LOWORD(l)
#define WSAGETASYNCERROR(l) HIWORD(l)
#define WSAGETSELECTERROR(l) HIWORD(l)
#define WSAGETSELECTEVENT(l) LOWORD(l)
#define WSAMAKEASYNCREPLY(b, e) MAKELONG(b,e)
#define WSAMAKESELECTREPLY(e, error) MAKELONG(e,error)
#define WSANO_ADDRESS WSANO_DATA
#define WSASYS_STATUS_LEN 128
Typedefs
typedef WSADATA * LPWSADATA
typedef u_int SOCKET
typedef unsigned char u_char
typedef unsigned int u_int
typedef unsigned long u_long
typedef unsigned short u_short
Functions
int PASCAL __WSAFDIsSet (SOCKET, fd_set *)
SOCKET PASCAL accept (SOCKET, struct sockaddr *, int *)
int PASCAL bind (SOCKET, const struct sockaddr *, int)
int PASCAL closesocket (SOCKET)
int PASCAL connect (SOCKET, const struct sockaddr *, int)
DECLARE_STDCALL_P (char *) inet_ntoa(struct in_addr)
DECLARE_STDCALL_P (struct hostent *) gethostbyaddr(const char *
const char const char * DECLARE_STDCALL_P (struct protoent *) getprotobynumber(int)
DECLARE_STDCALL_P (struct servent *) getservbyport(int
int PASCAL gethostname (char *, int)
int PASCAL getpeername (SOCKET, struct sockaddr *, int *)
int PASCAL getsockname (SOCKET, struct sockaddr *, int *)
int PASCAL getsockopt (SOCKET, int, int, char *, int *)
u_long PASCAL htonl (u_long)
u_short PASCAL htons (u_short)
unsigned long PASCAL inet_addr (const char *)
int PASCAL ioctlsocket (SOCKET, long, u_long *)
int PASCAL listen (SOCKET, int)
u_long PASCAL ntohl (u_long)
u_short PASCAL ntohs (u_short)
int PASCAL recv (SOCKET, char *, int, int)
int PASCAL recvfrom (SOCKET, char *, int, int, struct sockaddr *, int *)
int PASCAL select (int nfds, fd_set *, fd_set *, fd_set *, const struct timeval *)
int PASCAL send (SOCKET, const char *, int, int)
int PASCAL sendto (SOCKET, const char *, int, int, const struct sockaddr *, int)
int PASCAL setsockopt (SOCKET, int, int, const char *, int)
int PASCAL shutdown (SOCKET, int)
SOCKET PASCAL socket (int, int, int)
HANDLE PASCAL WSAAsyncGetHostByAddr (HWND, u_int, const char *, int, int, char *, int)
HANDLE PASCAL WSAAsyncGetHostByName (HWND, u_int, const char *, char *, int)
HANDLE PASCAL WSAAsyncGetProtoByName (HWND, u_int, const char *, char *, int)
HANDLE PASCAL WSAAsyncGetProtoByNumber (HWND, u_int, int, char *, int)
HANDLE PASCAL WSAAsyncGetServByName (HWND, u_int, const char *, const char *, char *, int)
HANDLE PASCAL WSAAsyncGetServByPort (HWND, u_int, int, const char *, char *, int)
int PASCAL WSAAsyncSelect (SOCKET, HWND, u_int, long)
int PASCAL WSACancelAsyncRequest (HANDLE)
int PASCAL WSACancelBlockingCall (void)
int PASCAL WSACleanup (void)
int PASCAL WSAGetLastError (void)
BOOL PASCAL WSAIsBlocking (void)
FARPROC PASCAL WSASetBlockingHook (FARPROC)
void PASCAL WSASetLastError (int)
int PASCAL WSAStartup (WORD, LPWSADATA)
int PASCAL WSAUnhookBlockingHook (void)
Variables
int
Macro Definition Documentation
_BSDTYPES_DEFINED
#define _BSDTYPES_DEFINED
Definition at line 31 of file winsock.h.
_GNU_H_WINDOWS32_SOCKETS
#define _GNU_H_WINDOWS32_SOCKETS
Definition at line 17 of file winsock.h.
_IO
#define _IO (x, y) (IOC_VOID|((x)<<8)|(y))
Definition at line 120 of file winsock.h.
_IOR
#define _IOR (x, y, t) (IOC_OUT|(((long)sizeof(t)&IOCPARM_MASK)<<16)|((x)<<8)|(y))
Definition at line 121 of file winsock.h.
_IOW
#define _IOW (x, y, t) (IOC_IN|(((long)sizeof(t)&IOCPARM_MASK)<<16)|((x)<<8)|(y))
Definition at line 122 of file winsock.h.
_TIMEVAL_DEFINED
#define _TIMEVAL_DEFINED
Definition at line 88 of file winsock.h.
AF_APPLETALK
#define AF_APPLETALK 16
Definition at line 308 of file winsock.h.
AF_ATM
#define AF_ATM 22
Definition at line 314 of file winsock.h.
AF_BAN
#define AF_BAN 21
Definition at line 313 of file winsock.h.
AF_CCITT
#define AF_CCITT 10
Definition at line 302 of file winsock.h.
AF_CHAOS
#define AF_CHAOS 5
Definition at line 295 of file winsock.h.
AF_DATAKIT
#define AF_DATAKIT 9
Definition at line 301 of file winsock.h.
AF_DECnet
#define AF_DECnet 12
Definition at line 304 of file winsock.h.
AF_DLI
#define AF_DLI 13
Definition at line 305 of file winsock.h.
AF_ECMA
#define AF_ECMA 8
Definition at line 300 of file winsock.h.
AF_FIREFOX
#define AF_FIREFOX 19
Definition at line 311 of file winsock.h.
AF_HYLINK
#define AF_HYLINK 15
Definition at line 307 of file winsock.h.
AF_IMPLINK
#define AF_IMPLINK 3
Definition at line 293 of file winsock.h.
AF_INET
#define AF_INET 2
Definition at line 292 of file winsock.h.
AF_INET6
#define AF_INET6 23
Definition at line 315 of file winsock.h.
AF_IPX
#define AF_IPX 6
Definition at line 296 of file winsock.h.
AF_ISO
#define AF_ISO 7
Definition at line 298 of file winsock.h.
AF_LAT
#define AF_LAT 14
Definition at line 306 of file winsock.h.
AF_MAX
#define AF_MAX 24
Definition at line 317 of file winsock.h.
AF_NETBIOS
#define AF_NETBIOS 17
Definition at line 309 of file winsock.h.
AF_NS
#define AF_NS 6
Definition at line 297 of file winsock.h.
AF_OSI
#define AF_OSI AF_ISO
Definition at line 299 of file winsock.h.
AF_PUP
#define AF_PUP 4
Definition at line 294 of file winsock.h.
AF_SNA
#define AF_SNA 11
Definition at line 303 of file winsock.h.
AF_UNIX
#define AF_UNIX 1
Definition at line 291 of file winsock.h.
AF_UNKNOWN1
#define AF_UNKNOWN1 20
Definition at line 312 of file winsock.h.
AF_UNSPEC
#define AF_UNSPEC 0
Definition at line 290 of file winsock.h.
AF_VOICEVIEW
#define AF_VOICEVIEW 18
Definition at line 310 of file winsock.h.
FD_ACCEPT
#define FD_ACCEPT 8
Definition at line 367 of file winsock.h.
FD_CLOSE
#define FD_CLOSE 32
Definition at line 369 of file winsock.h.
FD_CLR
#define FD_CLR (fd, set)
Value:
do { u_int __i;\
for (__i = 0; __i < ((fd_set *)(set))->fd_count ; __i++) {\
    if (((fd_set *)(set))->fd_array[__i] == (fd)) {\
    while (__i < ((fd_set *)(set))->fd_count-1) {\
        ((fd_set*)(set))->fd_array[__i] = ((fd_set*)(set))->fd_array[__i+1];\
        __i++;\
    }\
    ((fd_set*)(set))->fd_count--;\
    break;\
    }\
}\
} while (0)
Definition at line 56 of file winsock.h.
FD_CONNECT
#define FD_CONNECT 16
Definition at line 368 of file winsock.h.
FD_ISSET
#define FD_ISSET (fd, set) __WSAFDIsSet((SOCKET)(fd), (fd_set *)(set))
Definition at line 79 of file winsock.h.
FD_OOB
#define FD_OOB 4
Definition at line 366 of file winsock.h.
FD_READ
#define FD_READ 1
Definition at line 364 of file winsock.h.
FD_SET
#define FD_SET (fd, set)
Value:
    do { \
    if (((fd_set *)(set))->fd_count < FD_SETSIZE) \
    ((fd_set *)(set))->fd_array[((fd_set *)(set))->fd_count++]=(fd);\
}while (0)
Definition at line 70 of file winsock.h.
FD_SETSIZE
#define FD_SETSIZE 64
Definition at line 35 of file winsock.h.
FD_WRITE
#define FD_WRITE 2
Definition at line 365 of file winsock.h.
FD_ZERO
#define FD_ZERO (set) (((fd_set *)(set))->fd_count=0)
Definition at line 76 of file winsock.h.
FIOASYNC
#define FIOASYNC _IOW('f', 125, u_long)
Definition at line 127 of file winsock.h.
FIONBIO
#define FIONBIO _IOW('f', 126, u_long)
Definition at line 123 of file winsock.h.
FIONREAD
#define FIONREAD _IOR('f', 127, u_long)
Definition at line 126 of file winsock.h.
h_addr
#define h_addr h_addr_list[0]
Definition at line 106 of file winsock.h.
h_errno
#define h_errno WSAGetLastError()
Definition at line 427 of file winsock.h.
HOST_NOT_FOUND
#define HOST_NOT_FOUND WSAHOST_NOT_FOUND
Definition at line 428 of file winsock.h.
IMPLINK_HIGHEXPER
#define IMPLINK_HIGHEXPER 158
Definition at line 192 of file winsock.h.
IMPLINK_IP
#define IMPLINK_IP 155
Definition at line 190 of file winsock.h.
IMPLINK_LOWEXPER
#define IMPLINK_LOWEXPER 156
Definition at line 191 of file winsock.h.
IN_CLASSA
#define IN_CLASSA (i) (((long)(i)&0x80000000) == 0)
Definition at line 206 of file winsock.h.
IN_CLASSA_HOST
#define IN_CLASSA_HOST 0x00ffffff
Definition at line 209 of file winsock.h.
IN_CLASSA_MAX
#define IN_CLASSA_MAX 128
Definition at line 210 of file winsock.h.
IN_CLASSA_NET
#define IN_CLASSA_NET 0xff000000
Definition at line 207 of file winsock.h.
IN_CLASSA_NSHIFT
#define IN_CLASSA_NSHIFT 24
Definition at line 208 of file winsock.h.
IN_CLASSB
#define IN_CLASSB (i) (((long)(i)&0xc0000000)==0x80000000)
Definition at line 211 of file winsock.h.
IN_CLASSB_HOST
#define IN_CLASSB_HOST 0x0000ffff
Definition at line 214 of file winsock.h.
IN_CLASSB_MAX
#define IN_CLASSB_MAX 65536
Definition at line 215 of file winsock.h.
IN_CLASSB_NET
#define IN_CLASSB_NET 0xffff0000
Definition at line 212 of file winsock.h.
IN_CLASSB_NSHIFT
#define IN_CLASSB_NSHIFT 16
Definition at line 213 of file winsock.h.
IN_CLASSC
#define IN_CLASSC (i) (((long)(i)&0xe0000000)==0xc0000000)
Definition at line 216 of file winsock.h.
IN_CLASSC_HOST
#define IN_CLASSC_HOST 0xff
Definition at line 219 of file winsock.h.
IN_CLASSC_NET
#define IN_CLASSC_NET 0xffffff00
Definition at line 217 of file winsock.h.
IN_CLASSC_NSHIFT
#define IN_CLASSC_NSHIFT 8
Definition at line 218 of file winsock.h.
INADDR_ANY
#define INADDR_ANY (u_long)0
Definition at line 220 of file winsock.h.
INADDR_BROADCAST
#define INADDR_BROADCAST (u_long)0xffffffff
Definition at line 222 of file winsock.h.
INADDR_LOOPBACK
#define INADDR_LOOPBACK 0x7f000001
Definition at line 221 of file winsock.h.
INADDR_NONE
#define INADDR_NONE 0xffffffff
Definition at line 223 of file winsock.h.
INVALID_SOCKET
#define INVALID_SOCKET (SOCKET)(~0)
Definition at line 282 of file winsock.h.
IOC_IN
#define IOC_IN 0x80000000
Definition at line 116 of file winsock.h.
IOC_INOUT
#define IOC_INOUT (IOC_IN|IOC_OUT)
Definition at line 117 of file winsock.h.
IOC_OUT
#define IOC_OUT 0x40000000
Definition at line 115 of file winsock.h.
IOC_VOID
#define IOC_VOID 0x20000000
Definition at line 114 of file winsock.h.
IOCPARM_MASK
#define IOCPARM_MASK 0x7f
Definition at line 113 of file winsock.h.
IP_ADD_MEMBERSHIP
#define IP_ADD_MEMBERSHIP 5
Definition at line 272 of file winsock.h.
IP_DEFAULT_MULTICAST_LOOP
#define IP_DEFAULT_MULTICAST_LOOP 1
Definition at line 276 of file winsock.h.
IP_DEFAULT_MULTICAST_TTL
#define IP_DEFAULT_MULTICAST_TTL 1
Definition at line 275 of file winsock.h.
IP_DROP_MEMBERSHIP
#define IP_DROP_MEMBERSHIP 6
Definition at line 273 of file winsock.h.
IP_MAX_MEMBERSHIPS
#define IP_MAX_MEMBERSHIPS 20
Definition at line 277 of file winsock.h.
IP_MULTICAST_IF
#define IP_MULTICAST_IF 2
Definition at line 269 of file winsock.h.
IP_MULTICAST_LOOP
#define IP_MULTICAST_LOOP 4
Definition at line 271 of file winsock.h.
IP_MULTICAST_TTL
#define IP_MULTICAST_TTL 3
Definition at line 270 of file winsock.h.
IP_OPTIONS
#define IP_OPTIONS 1
Definition at line 244 of file winsock.h.
IPPORT_BIFFUDP
#define IPPORT_BIFFUDP 512
Definition at line 186 of file winsock.h.
IPPORT_CMDSERVER
#define IPPORT_CMDSERVER 514
Definition at line 184 of file winsock.h.
IPPORT_DAYTIME
#define IPPORT_DAYTIME 13
Definition at line 168 of file winsock.h.
IPPORT_DISCARD
#define IPPORT_DISCARD 9
Definition at line 166 of file winsock.h.
IPPORT_ECHO
#define IPPORT_ECHO 7
Definition at line 165 of file winsock.h.
IPPORT_EFSSERVER
#define IPPORT_EFSSERVER 520
Definition at line 185 of file winsock.h.
IPPORT_EXECSERVER
#define IPPORT_EXECSERVER 512
Definition at line 182 of file winsock.h.
IPPORT_FINGER
#define IPPORT_FINGER 79
Definition at line 179 of file winsock.h.
IPPORT_FTP
#define IPPORT_FTP 21
Definition at line 170 of file winsock.h.
IPPORT_LOGINSERVER
#define IPPORT_LOGINSERVER 513
Definition at line 183 of file winsock.h.
IPPORT_MTP
#define IPPORT_MTP 57
Definition at line 176 of file winsock.h.
IPPORT_NAMESERVER
#define IPPORT_NAMESERVER 42
Definition at line 174 of file winsock.h.
IPPORT_NETSTAT
#define IPPORT_NETSTAT 15
Definition at line 169 of file winsock.h.
IPPORT_RESERVED
#define IPPORT_RESERVED 1024
Definition at line 189 of file winsock.h.
IPPORT_RJE
#define IPPORT_RJE 77
Definition at line 178 of file winsock.h.
IPPORT_ROUTESERVER
#define IPPORT_ROUTESERVER 520
Definition at line 188 of file winsock.h.
IPPORT_SMTP
#define IPPORT_SMTP 25
Definition at line 172 of file winsock.h.
IPPORT_SUPDUP
#define IPPORT_SUPDUP 95
Definition at line 181 of file winsock.h.
IPPORT_SYSTAT
#define IPPORT_SYSTAT 11
Definition at line 167 of file winsock.h.
IPPORT_TELNET
#define IPPORT_TELNET 23
Definition at line 171 of file winsock.h.
IPPORT_TFTP
#define IPPORT_TFTP 69
Definition at line 177 of file winsock.h.
IPPORT_TIMESERVER
#define IPPORT_TIMESERVER 37
Definition at line 173 of file winsock.h.
IPPORT_TTYLINK
#define IPPORT_TTYLINK 87
Definition at line 180 of file winsock.h.
IPPORT_WHOIS
#define IPPORT_WHOIS 43
Definition at line 175 of file winsock.h.
IPPORT_WHOSERVER
#define IPPORT_WHOSERVER 513
Definition at line 187 of file winsock.h.
IPPROTO_GGP
#define IPPROTO_GGP 3
Definition at line 157 of file winsock.h.
IPPROTO_ICMP
#define IPPROTO_ICMP 1
Definition at line 155 of file winsock.h.
IPPROTO_IDP
#define IPPROTO_IDP 22
Definition at line 161 of file winsock.h.
IPPROTO_IGMP
#define IPPROTO_IGMP 2
Definition at line 156 of file winsock.h.
IPPROTO_IP
#define IPPROTO_IP 0
Definition at line 154 of file winsock.h.
IPPROTO_MAX
#define IPPROTO_MAX 256
Definition at line 164 of file winsock.h.
IPPROTO_ND
#define IPPROTO_ND 77
Definition at line 162 of file winsock.h.
IPPROTO_PUP
#define IPPROTO_PUP 12
Definition at line 159 of file winsock.h.
IPPROTO_RAW
#define IPPROTO_RAW 255
Definition at line 163 of file winsock.h.
IPPROTO_TCP
#define IPPROTO_TCP 6
Definition at line 158 of file winsock.h.
IPPROTO_UDP
#define IPPROTO_UDP 17
Definition at line 160 of file winsock.h.
MAXGETHOSTSTRUCT
#define MAXGETHOSTSTRUCT 1024
Definition at line 363 of file winsock.h.
MSG_DONTROUTE
#define MSG_DONTROUTE 4
Definition at line 359 of file winsock.h.
MSG_MAXIOVLEN
#define MSG_MAXIOVLEN 16
Definition at line 361 of file winsock.h.
MSG_OOB
#define MSG_OOB 1
Definition at line 357 of file winsock.h.
MSG_PARTIAL
#define MSG_PARTIAL 0x8000
Definition at line 362 of file winsock.h.
MSG_PEEK
#define MSG_PEEK 2
Definition at line 358 of file winsock.h.
NO_ADDRESS
#define NO_ADDRESS WSANO_ADDRESS
Definition at line 432 of file winsock.h.
NO_DATA
#define NO_DATA WSANO_DATA
Definition at line 431 of file winsock.h.
NO_RECOVERY
#define NO_RECOVERY WSANO_RECOVERY
Definition at line 430 of file winsock.h.
PF_APPLETALK
#define PF_APPLETALK AF_APPLETALK
Definition at line 346 of file winsock.h.
PF_ATM
#define PF_ATM AF_ATM
Definition at line 351 of file winsock.h.
PF_BAN
#define PF_BAN AF_BAN
Definition at line 350 of file winsock.h.
PF_CCITT
#define PF_CCITT AF_CCITT
Definition at line 340 of file winsock.h.
PF_CHAOS
#define PF_CHAOS AF_CHAOS
Definition at line 333 of file winsock.h.
PF_DATAKIT
#define PF_DATAKIT AF_DATAKIT
Definition at line 339 of file winsock.h.
PF_DECnet
#define PF_DECnet AF_DECnet
Definition at line 342 of file winsock.h.
PF_DLI
#define PF_DLI AF_DLI
Definition at line 343 of file winsock.h.
PF_ECMA
#define PF_ECMA AF_ECMA
Definition at line 338 of file winsock.h.
PF_FIREFOX
#define PF_FIREFOX AF_FIREFOX
Definition at line 348 of file winsock.h.
PF_HYLINK
#define PF_HYLINK AF_HYLINK
Definition at line 345 of file winsock.h.
PF_IMPLINK
#define PF_IMPLINK AF_IMPLINK
Definition at line 331 of file winsock.h.
PF_INET
#define PF_INET AF_INET
Definition at line 330 of file winsock.h.
PF_INET6
#define PF_INET6 AF_INET6
Definition at line 352 of file winsock.h.
PF_IPX
#define PF_IPX AF_IPX
Definition at line 335 of file winsock.h.
PF_ISO
#define PF_ISO AF_ISO
Definition at line 336 of file winsock.h.
PF_LAT
#define PF_LAT AF_LAT
Definition at line 344 of file winsock.h.
PF_MAX
#define PF_MAX AF_MAX
Definition at line 353 of file winsock.h.
PF_NS
#define PF_NS AF_NS
Definition at line 334 of file winsock.h.
PF_OSI
#define PF_OSI AF_OSI
Definition at line 337 of file winsock.h.
PF_PUP
#define PF_PUP AF_PUP
Definition at line 332 of file winsock.h.
PF_SNA
#define PF_SNA AF_SNA
Definition at line 341 of file winsock.h.
PF_UNIX
#define PF_UNIX AF_UNIX
Definition at line 329 of file winsock.h.
PF_UNKNOWN1
#define PF_UNKNOWN1 AF_UNKNOWN1
Definition at line 349 of file winsock.h.
PF_UNSPEC
#define PF_UNSPEC AF_UNSPEC
Definition at line 328 of file winsock.h.
PF_VOICEVIEW
#define PF_VOICEVIEW AF_VOICEVIEW
Definition at line 347 of file winsock.h.
s_addr
#define s_addr S_un.S_addr
Definition at line 199 of file winsock.h.
s_host
#define s_host S_un.S_un_b.s_b2
Definition at line 200 of file winsock.h.
s_imp
#define s_imp S_un.S_un_w.s_w2
Definition at line 202 of file winsock.h.
s_impno
#define s_impno S_un.S_un_b.s_b4
Definition at line 203 of file winsock.h.
s_lh
#define s_lh S_un.S_un_b.s_b3
Definition at line 204 of file winsock.h.
s_net
#define s_net S_un.S_un_b.s_b1
Definition at line 201 of file winsock.h.
SD_BOTH
#define SD_BOTH 0x02
Definition at line 41 of file winsock.h.
SD_RECEIVE
#define SD_RECEIVE 0x00
Definition at line 39 of file winsock.h.
SD_SEND
#define SD_SEND 0x01
Definition at line 40 of file winsock.h.
SIOCATMARK
#define SIOCATMARK _IOR('s', 7, u_long)
Definition at line 132 of file winsock.h.
SIOCGHIWAT
#define SIOCGHIWAT _IOR('s', 1, u_long)
Definition at line 129 of file winsock.h.
SIOCGLOWAT
#define SIOCGLOWAT _IOR('s', 3, u_long)
Definition at line 131 of file winsock.h.
SIOCSHIWAT
#define SIOCSHIWAT _IOW('s', 0, u_long)
Definition at line 128 of file winsock.h.
SIOCSLOWAT
#define SIOCSLOWAT _IOW('s', 2, u_long)
Definition at line 130 of file winsock.h.
SO_ACCEPTCONN
#define SO_ACCEPTCONN 2
Definition at line 246 of file winsock.h.
SO_BROADCAST
#define SO_BROADCAST 32
Definition at line 250 of file winsock.h.
SO_DEBUG
#define SO_DEBUG 1
Definition at line 245 of file winsock.h.
SO_DONTLINGER
#define SO_DONTLINGER (u_int)(~SO_LINGER)
Definition at line 254 of file winsock.h.
SO_DONTROUTE
#define SO_DONTROUTE 16
Definition at line 249 of file winsock.h.
SO_ERROR
#define SO_ERROR 0x1007
Definition at line 261 of file winsock.h.
SO_KEEPALIVE
#define SO_KEEPALIVE 8
Definition at line 248 of file winsock.h.
SO_LINGER
#define SO_LINGER 128
Definition at line 252 of file winsock.h.
SO_OOBINLINE
#define SO_OOBINLINE 256
Definition at line 253 of file winsock.h.
SO_RCVBUF
#define SO_RCVBUF 0x1002
Definition at line 256 of file winsock.h.
SO_RCVLOWAT
#define SO_RCVLOWAT 0x1004
Definition at line 258 of file winsock.h.
SO_RCVTIMEO
#define SO_RCVTIMEO 0x1006
Definition at line 260 of file winsock.h.
SO_REUSEADDR
#define SO_REUSEADDR 4
Definition at line 247 of file winsock.h.
SO_SNDBUF
#define SO_SNDBUF 0x1001
Definition at line 255 of file winsock.h.
SO_SNDLOWAT
#define SO_SNDLOWAT 0x1003
Definition at line 257 of file winsock.h.
SO_SNDTIMEO
#define SO_SNDTIMEO 0x1005
Definition at line 259 of file winsock.h.
SO_TYPE
#define SO_TYPE 0x1008
Definition at line 262 of file winsock.h.
SO_USELOOPBACK
#define SO_USELOOPBACK 64
Definition at line 251 of file winsock.h.
SOCK_DGRAM
#define SOCK_DGRAM 2
Definition at line 285 of file winsock.h.
SOCK_RAW
#define SOCK_RAW 3
Definition at line 286 of file winsock.h.
SOCK_RDM
#define SOCK_RDM 4
Definition at line 287 of file winsock.h.
SOCK_SEQPACKET
#define SOCK_SEQPACKET 5
Definition at line 288 of file winsock.h.
SOCK_STREAM
#define SOCK_STREAM 1
Definition at line 284 of file winsock.h.
SOCKET_ERROR
#define SOCKET_ERROR (-1)
Definition at line 283 of file winsock.h.
SOL_SOCKET
#define SOL_SOCKET 0xffff
Definition at line 354 of file winsock.h.
SOMAXCONN
#define SOMAXCONN 5
Definition at line 355 of file winsock.h.
TCP_NODELAY
#define TCP_NODELAY 0x0001
Definition at line 289 of file winsock.h.
timerclear
#define timerclear (tvp) (tvp)->tv_sec = (tvp)->tv_usec = 0
Definition at line 98 of file winsock.h.
timercmp
#define timercmp (tvp, uvp, cmp)
Value:
    (((tvp)->tv_sec != (uvp)->tv_sec) ? \
    ((tvp)->tv_sec cmp (uvp)->tv_sec) : \
    ((tvp)->tv_usec cmp (uvp)->tv_usec))
Definition at line 94 of file winsock.h.
timerisset
#define timerisset (tvp) ((tvp)->tv_sec || (tvp)->tv_usec)
Definition at line 93 of file winsock.h.
TRY_AGAIN
#define TRY_AGAIN WSATRY_AGAIN
Definition at line 429 of file winsock.h.
WSADESCRIPTION_LEN
#define WSADESCRIPTION_LEN 256
Definition at line 230 of file winsock.h.
WSAGETASYNCBUFLEN
#define WSAGETASYNCBUFLEN (l) LOWORD(l)
Definition at line 485 of file winsock.h.
WSAGETASYNCERROR
#define WSAGETASYNCERROR (l) HIWORD(l)
Definition at line 486 of file winsock.h.
WSAGETSELECTERROR
#define WSAGETSELECTERROR (l) HIWORD(l)
Definition at line 488 of file winsock.h.
WSAGETSELECTEVENT
#define WSAGETSELECTEVENT (l) LOWORD(l)
Definition at line 487 of file winsock.h.
WSAMAKEASYNCREPLY
#define WSAMAKEASYNCREPLY (b, e) MAKELONG(b,e)
Definition at line 483 of file winsock.h.
WSAMAKESELECTREPLY
#define WSAMAKESELECTREPLY (e, error) MAKELONG(e,error)
Definition at line 484 of file winsock.h.
WSANO_ADDRESS
#define WSANO_ADDRESS WSANO_DATA
Definition at line 425 of file winsock.h.
WSASYS_STATUS_LEN
#define WSASYS_STATUS_LEN 128
Definition at line 231 of file winsock.h.
Typedef Documentation
LPWSADATA
WINSOCK_API_LINKAGE typedef LPWSADATA
Definition at line 241 of file winsock.h.
SOCKET
typedef u_int SOCKET
Definition at line 33 of file winsock.h.
u_char
typedef unsigned char u_char
Definition at line 27 of file winsock.h.
u_int
typedef unsigned int u_int
Definition at line 29 of file winsock.h.
u_long
typedef unsigned long u_long
Definition at line 30 of file winsock.h.
u_short
typedef unsigned short u_short
Definition at line 28 of file winsock.h.
Function Documentation
__WSAFDIsSet()
int PASCAL __WSAFDIsSet (SOCKET , fd_set *)
accept()
SOCKET PASCAL accept (SOCKET , struct sockaddr * , int *)
bind()
int PASCAL bind (SOCKET , const struct sockaddr * , int)
Referenced by _GLIBCXX_VISIBILITY(), NET_IP6Socket(), and NET_IPSocket().
closesocket()
int PASCAL closesocket (SOCKET)
connect()
int PASCAL connect (SOCKET , const struct sockaddr * , int)
Referenced by GraphicsPath::AddPath(), and NET_OpenSocks().
DECLARE_STDCALL_P() [1/4]
DECLARE_STDCALL_P (char *)
DECLARE_STDCALL_P() [2/4]
WINSOCK_API_LINKAGE DECLARE_STDCALL_P (struct hostent *) const
DECLARE_STDCALL_P() [3/4]
WINSOCK_API_LINKAGE DECLARE_STDCALL_P (struct protoent *)
DECLARE_STDCALL_P() [4/4]
WINSOCK_API_LINKAGE const char *WINSOCK_API_LINKAGE DECLARE_STDCALL_P (struct servent *)
gethostname()
int PASCAL gethostname (char * , int)
Referenced by NET_GetLocalAddress().
getpeername()
int PASCAL getpeername (SOCKET , struct sockaddr * , int *)
getsockname()
int PASCAL getsockname (SOCKET , struct sockaddr * , int *)
getsockopt()
int PASCAL getsockopt (SOCKET , int , int , char * , int *)
htonl()
u_long PASCAL htonl (u_long)
htons()
u_short PASCAL htons (u_short)
Referenced by NET_IP6Socket(), NET_IPSocket(), and NET_OpenSocks().
inet_addr()
unsigned long PASCAL inet_addr (const char *)
ioctlsocket()
int PASCAL ioctlsocket (SOCKET , long , u_long *)
listen()
int PASCAL listen (SOCKET , int)
ntohl()
u_long PASCAL ntohl (u_long)
ntohs()
u_short PASCAL ntohs (u_short)
Referenced by NET_AdrToStringwPort(), and NET_JoinMulticast6().
recv()
int PASCAL recv (SOCKET , char * , int , int)
Referenced by NET_OpenSocks().
recvfrom()
int PASCAL recvfrom (SOCKET , char * , int , int , struct sockaddr * , int *)
Referenced by NET_GetPacket().
select()
int PASCAL select (int nfds, fd_set * , fd_set * , fd_set * , const struct timeval *)
Referenced by CON_Input(), DECLARE_INTERFACE_(), NET_Sleep(), and Sys_Sleep().
send()
int PASCAL send (SOCKET , const char * , int , int)
sendto()
int PASCAL sendto (SOCKET , const char * , int , int , const struct sockaddr * , int)
Referenced by Sys_SendPacket().
setsockopt()
int PASCAL setsockopt (SOCKET , int , int , const char * , int)
Referenced by NET_IP6Socket(), NET_IPSocket(), NET_JoinMulticast6(), and NET_LeaveMulticast6().
shutdown()
int PASCAL shutdown (SOCKET , int)
socket()
SOCKET PASCAL socket (int , int , int)
Referenced by NET_IP6Socket(), NET_IPSocket(), and NET_OpenSocks().
WSAAsyncGetHostByAddr()
HANDLE PASCAL WSAAsyncGetHostByAddr (HWND , u_int , const char * , int , int , char * , int)
WSAAsyncGetHostByName()
HANDLE PASCAL WSAAsyncGetHostByName (HWND , u_int , const char * , char * , int)
WSAAsyncGetProtoByName()
HANDLE PASCAL WSAAsyncGetProtoByName (HWND , u_int , const char * , char * , int)
WSAAsyncGetProtoByNumber()
HANDLE PASCAL WSAAsyncGetProtoByNumber (HWND , u_int , int , char * , int)
WSAAsyncGetServByName()
HANDLE PASCAL WSAAsyncGetServByName (HWND , u_int , const char * , const char * , char * , int)
WSAAsyncGetServByPort()
HANDLE PASCAL WSAAsyncGetServByPort (HWND , u_int , int , const char * , char * , int)
WSAAsyncSelect()
int PASCAL WSAAsyncSelect (SOCKET , HWND , u_int , long)
WSACancelAsyncRequest()
int PASCAL WSACancelAsyncRequest (HANDLE)
WSACancelBlockingCall()
int PASCAL WSACancelBlockingCall (void)
WSACleanup()
int PASCAL WSACleanup (void)
Referenced by NET_Shutdown().
WSAGetLastError()
int PASCAL WSAGetLastError (void)
WSAIsBlocking()
BOOL PASCAL WSAIsBlocking (void)
WSASetBlockingHook()
FARPROC PASCAL WSASetBlockingHook (FARPROC)
WSASetLastError()
void PASCAL WSASetLastError (int)
WSAStartup()
int PASCAL WSAStartup (WORD , LPWSADATA)
Referenced by NET_Init().
WSAUnhookBlockingHook()
int PASCAL WSAUnhookBlockingHook (void)
Variable Documentation
int
int
Definition at line 452 of file winsock.h.