ZEQ2-Lite: Source/Game/UI/ui_shared.c File Reference
ui_shared.c File Reference
#include "ui_local.h"
Functions
void Menu_Common (int amount)
void Menu_Frame (void)
void Menu_Side (void)
Function Documentation
Menu_Common()
void Menu_Common (int amount)
Definition at line 2 of file ui_shared.c.
{
     int current;
     int x = 16;
     int y = 112;
     current = 1;
     UI_MenuLogo();
     while(current < amount+1){
         if(current == 1){UI_DrawHandlePic(x,y,124,34,uis.menuButton1);}
         if(current == 2){UI_DrawHandlePic(x,y,109,34,uis.menuButton2);}
         if(current == 3){UI_DrawHandlePic(x,y,102,34,uis.menuButton3);}
         if(current == 4){UI_DrawHandlePic(x,y,102,34,uis.menuButton4);}
         if(current == 5){UI_DrawHandlePic(x,y,109,34,uis.menuButton5);}
         if(current == 6){UI_DrawHandlePic(x,y,124,34,uis.menuButton6);}
         y += 38;
         current += 1;
     }
 }
References current, uiStatic_t::menuButton1, uiStatic_t::menuButton2, uiStatic_t::menuButton3, uiStatic_t::menuButton4, uiStatic_t::menuButton5, uiStatic_t::menuButton6, UI_DrawHandlePic(), UI_MenuLogo(), and uis.
Referenced by UI_Refresh().
Menu_Frame()
void Menu_Frame (void)
Definition at line 19 of file ui_shared.c.
                      {
     UI_DrawHandlePic(147,113,367,310,uis.menuFrame);
 }
References uiStatic_t::menuFrame, UI_DrawHandlePic(), and uis.
Referenced by UI_Refresh().
Menu_Side()
void Menu_Side (void)
Definition at line 22 of file ui_shared.c.
 {}
Referenced by UI_Refresh().