ZEQ2-Lite: Source/Engine/tools/lcc/cpp/unix.c File Reference
unix.c File Reference
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "cpp.h"
Functions
char * basepath (char *fname)
int lcc_getopt (int, char *const *, const char *)
void * memmove (void *dp, const void *sp, size_t n)
void setup (int argc, char **argv)
Variables
int Cplusplus = 1
int Mflag
char * objname
char * optarg
int optind
char rcsid []
int verbose
Function Documentation
basepath()
char* basepath (char * fname)
Definition at line 86 of file unix.c.
 {
     char *dp = ".";
     char *p;
     if ((p = strrchr(fname, '/')) != NULL) {
         int dlen = p - fname;
         dp = (char*)newstring((uchar*)fname, dlen+1, 0);
         dp[dlen] = '\0';
     }
     return dp;
 }
References newstring(), and NULL.
Referenced by DefaultPath(), doinclude(), setup(), and UpdatePaths().
lcc_getopt()
int lcc_getopt (int , char *const * , const char *)
Referenced by setup().
memmove()
void* memmove (void * dp, const void * sp, size_t n)
Definition at line 107 of file unix.c.
 {
     unsigned char *cdp, *csp;
     if (n<=0)
         return 0;
     cdp = dp;
     csp = (unsigned char *)sp;
     if (cdp < csp) {
         do {
             *cdp++ = *csp++;
         } while (--n);
     } else {
         cdp += n;
         csp += n;
         do {
             *--cdp = *--csp;
         } while (--n);
     }
     return 0;
 }
References sp.
Referenced by adjustrow(), blit4_32(), Cbuf_Execute(), CL_LoadConsoleHistory(), CL_NextDownload(), CollapseMultitexture(), Com_ReadFromPipe(), CON_Input(), Field_CharEvent(), Field_CompleteCommand(), Field_KeyDownEvent(), FinishShader(), foldline(), FS_ReplaceSeparators(), gettokens(), Info_RemoveKey(), MField_CharEvent(), MField_KeyDownEvent(), movetokenrow(), newhideset(), SV_DelBanEntryFromList(), and trigraph().
setup()
void setup (int argc, char ** argv)
Definition at line 16 of file unix.c.
 {
     int c, fd, i;
     char *fp, *dp;
     Tokenrow tr;
     extern void setup_kwtab(void);
     uchar *includeDirs[ NINCLUDE ] = { 0 };
     int   numIncludeDirs = 0;
     setup_kwtab();
     while ((c = lcc_getopt(argc, argv, "MNOVv+I:D:U:F:lg")) != -1)
         switch (c) {
         case 'N':
             for (i=0; i<NINCLUDE; i++)
                 if (includelist[i].always==1)
                     includelist[i].deleted = 1;
             break;
         case 'I':
             includeDirs[ numIncludeDirs++ ] = newstring( (uchar *)optarg, strlen( optarg ), 0 );
             break;
         case 'D':
         case 'U':
             setsource("<cmdarg>", -1, optarg);
             maketokenrow(3, &tr);
             gettokens(&tr, 1);
             doadefine(&tr, c);
             unsetsource();
             break;
         case 'M':
             Mflag++;
             break;
         case 'v':
             fprintf(stderr, "%s %s\n", argv[0], rcsid);
             break;
         case 'V':
             verbose++;
             break;
         case '+':
             Cplusplus++;
             break;
         default:
             break;
         }
     dp = ".";
     fp = "<stdin>";
     fd = 0;
     if (optind<argc) {
         dp = basepath( argv[optind] );
         fp = (char*)newstring((uchar*)argv[optind], strlen(argv[optind]), 0);
         if ((fd = open(fp, 0)) <= 0)
             error(FATAL, "Can't open input file %s", fp);
     }
     if (optind+1<argc) {
         int fdo = creat(argv[optind+1], 0666);
         if (fdo<0)
             error(FATAL, "Can't open output file %s", argv[optind+1]);
         dup2(fdo, 1);
     }
     if(Mflag)
         setobjname(fp);
     includelist[NINCLUDE-1].always = 0;
     includelist[NINCLUDE-1].file = dp;
     for( i = 0; i < numIncludeDirs; i++ )
         appendDirToIncludeList( (char *)includeDirs[ i ] );
     setsource(fp, fd, NULL);
 }
References includelist::always, appendDirToIncludeList(), basepath(), Cplusplus, includelist::deleted, doadefine(), error(), FATAL, includelist::file, fp, gettokens(), lcc_getopt(), maketokenrow(), Mflag, newstring(), NINCLUDE, NULL, optarg, optind, rcsid, setobjname(), setsource(), setup_kwtab(), tr, unsetsource(), and verbose.
Referenced by main().
Variable Documentation
Cplusplus
int Cplusplus = 1
Definition at line 13 of file unix.c.
Referenced by fixlex(), and setup().
Mflag
int Mflag
Definition at line 11 of file unix.c.
Referenced by doinclude(), and setup().
objname
char* objname
Definition at line 12 of file unix.c.
Referenced by doinclude(), and setobjname().
optarg
char* optarg
Definition at line 8 of file getopt.c.
Referenced by lcc_getopt(), and setup().
optind
int optind
Definition at line 6 of file getopt.c.
Referenced by lcc_getopt(), and setup().
rcsid
char rcsid[]
Definition at line 8 of file unix.c.
Referenced by setup().
verbose
int verbose
Definition at line 10 of file unix.c.
Referenced by setup().