ZEQ2-Lite: Tools/MinGW/include/richole.h File Reference
richole.h File Reference
Data Structures
struct _reobject
Macros
#define INTERFACE IRichEditOle
#define INTERFACE IRichEditOleCallback
#define RECO_COPY 2
#define RECO_CUT 3
#define RECO_DRAG 4
#define RECO_DROP 1
#define RECO_PASTE 0
#define REO_BELOWBASELINE 2
#define REO_BLANK 16
#define REO_CP_SELECTION ((ULONG)-1)
#define REO_DONTNEEDPALETTE 32
#define REO_DYNAMICSIZE 8
#define REO_GETMETAFILE 0x400000
#define REO_GETOBJ_ALL_INTERFACES 7
#define REO_GETOBJ_NO_INTERFACES 0
#define REO_GETOBJ_POLEOBJ 1
#define REO_GETOBJ_POLESITE 4
#define REO_GETOBJ_PSTG 2
#define REO_HILITED 0x1000000
#define REO_INPLACEACTIVE 0x2000000
#define REO_INVERTEDSELECT 4
#define REO_IOB_SELECTION ((ULONG)-1)
#define REO_IOB_USE_CP ((ULONG)-2)
#define REO_LINK 0x80000000
#define REO_LINKAVAILABLE 0x800000
#define REO_NULL 0
#define REO_OPEN 0x4000000
#define REO_READWRITEMASK 0x3FL
#define REO_RESIZABLE 1
#define REO_SELECTED 0x08000000
#define REO_STATIC 0x40000000
Typedefs
typedef IRichEditOle * LPRICHEDITOLE
typedef IRichEditOleCallback FAR * LPRICHEDITOLECALLBACK
Functions
DECLARE_INTERFACE_ (IRichEditOle, IUnknown)
DECLARE_INTERFACE_ (IRichEditOleCallback, IUnknown)
Variables
const GUID IID_IRichEditOle
const GUID IID_IRichEditOleCallback
Macro Definition Documentation
INTERFACE [1/2]
#define INTERFACE IRichEditOle
Definition at line 83 of file richole.h.
INTERFACE [2/2]
#define INTERFACE IRichEditOleCallback
Definition at line 83 of file richole.h.
RECO_COPY
#define RECO_COPY 2
Definition at line 37 of file richole.h.
RECO_CUT
#define RECO_CUT 3
Definition at line 38 of file richole.h.
RECO_DRAG
#define RECO_DRAG 4
Definition at line 39 of file richole.h.
RECO_DROP
#define RECO_DROP 1
Definition at line 36 of file richole.h.
RECO_PASTE
#define RECO_PASTE 0
Definition at line 35 of file richole.h.
REO_BELOWBASELINE
#define REO_BELOWBASELINE 2
Definition at line 25 of file richole.h.
REO_BLANK
#define REO_BLANK 16
Definition at line 22 of file richole.h.
REO_CP_SELECTION
#define REO_CP_SELECTION ((ULONG)-1)
Definition at line 16 of file richole.h.
REO_DONTNEEDPALETTE
#define REO_DONTNEEDPALETTE 32
Definition at line 21 of file richole.h.
REO_DYNAMICSIZE
#define REO_DYNAMICSIZE 8
Definition at line 23 of file richole.h.
REO_GETMETAFILE
#define REO_GETMETAFILE 0x400000
Definition at line 34 of file richole.h.
REO_GETOBJ_ALL_INTERFACES
#define REO_GETOBJ_ALL_INTERFACES 7
Definition at line 15 of file richole.h.
REO_GETOBJ_NO_INTERFACES
#define REO_GETOBJ_NO_INTERFACES 0
Definition at line 11 of file richole.h.
REO_GETOBJ_POLEOBJ
#define REO_GETOBJ_POLEOBJ 1
Definition at line 12 of file richole.h.
REO_GETOBJ_POLESITE
#define REO_GETOBJ_POLESITE 4
Definition at line 14 of file richole.h.
REO_GETOBJ_PSTG
#define REO_GETOBJ_PSTG 2
Definition at line 13 of file richole.h.
REO_HILITED
#define REO_HILITED 0x1000000
Definition at line 32 of file richole.h.
REO_INPLACEACTIVE
#define REO_INPLACEACTIVE 0x2000000
Definition at line 31 of file richole.h.
REO_INVERTEDSELECT
#define REO_INVERTEDSELECT 4
Definition at line 24 of file richole.h.
REO_IOB_SELECTION
#define REO_IOB_SELECTION ((ULONG)-1)
Definition at line 17 of file richole.h.
REO_IOB_USE_CP
#define REO_IOB_USE_CP ((ULONG)-2)
Definition at line 18 of file richole.h.
REO_LINK
#define REO_LINK 0x80000000
Definition at line 27 of file richole.h.
REO_LINKAVAILABLE
#define REO_LINKAVAILABLE 0x800000
Definition at line 33 of file richole.h.
REO_NULL
#define REO_NULL 0
Definition at line 19 of file richole.h.
REO_OPEN
#define REO_OPEN 0x4000000
Definition at line 30 of file richole.h.
REO_READWRITEMASK
#define REO_READWRITEMASK 0x3FL
Definition at line 20 of file richole.h.
REO_RESIZABLE
#define REO_RESIZABLE 1
Definition at line 26 of file richole.h.
REO_SELECTED
#define REO_SELECTED 0x08000000
Definition at line 29 of file richole.h.
REO_STATIC
#define REO_STATIC 0x40000000
Definition at line 28 of file richole.h.
Typedef Documentation
LPRICHEDITOLE
typedef IRichEditOle* LPRICHEDITOLE
Definition at line 79 of file richole.h.
LPRICHEDITOLECALLBACK
typedef IRichEditOleCallback FAR* LPRICHEDITOLECALLBACK
Definition at line 99 of file richole.h.
Function Documentation
DECLARE_INTERFACE_() [1/2]
DECLARE_INTERFACE_ (IRichEditOle , IUnknown)
Definition at line 58 of file richole.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetClientSite)(THIS_ LPOLECLIENTSITE*) PURE;
     STDMETHOD_(LONG,GetObjectCount)(THIS) PURE;
     STDMETHOD_(LONG,GetLinkCount)(THIS) PURE;
     STDMETHOD(GetObject)(THIS_ LONG, REOBJECT*,DWORD) PURE;
     STDMETHOD(InsertObject)(THIS_ REOBJECT*) PURE;
     STDMETHOD(ConvertObject)(THIS_ LONG,REFCLSID,LPCSTR) PURE;
     STDMETHOD(ActivateAs)(THIS_ REFCLSID,REFCLSID) PURE;
     STDMETHOD(SetHostNames)(THIS_ LPCSTR,LPCSTR) PURE;
     STDMETHOD(SetLinkAvailable)(THIS_ LONG,BOOL) PURE;
     STDMETHOD(SetDvaspect)(THIS_ LONG,DWORD) PURE;
     STDMETHOD(HandsOffStorage)(THIS_ LONG) PURE;
     STDMETHOD(SaveCompleted)(THIS_ LONG,LPSTORAGE) PURE;
     STDMETHOD(InPlaceDeactivate)(THIS) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
     STDMETHOD(GetClipboardData)(THIS_ CHARRANGE*,DWORD,LPDATAOBJECT*) PURE;
     STDMETHOD(ImportDataObject)(THIS_ LPDATAOBJECT,CLIPFORMAT,HGLOBAL) PURE;
 };
References GetClipboardData(), GetObject, LONG, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [2/2]
DECLARE_INTERFACE_ (IRichEditOleCallback , IUnknown)
Definition at line 84 of file richole.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetNewStorage)(THIS_ LPSTORAGE*) PURE;
     STDMETHOD(GetInPlaceContext)(THIS_ LPOLEINPLACEFRAME*,LPOLEINPLACEUIWINDOW*,LPOLEINPLACEFRAMEINFO) PURE;
     STDMETHOD(ShowContainerUI)(THIS_ BOOL) PURE;
     STDMETHOD(QueryInsertObject)(THIS_ LPCLSID,LPSTORAGE,LONG) PURE;
     STDMETHOD(DeleteObject)(THIS_ LPOLEOBJECT) PURE;
     STDMETHOD(QueryAcceptData) (THIS_ LPDATAOBJECT,CLIPFORMAT*,DWORD,BOOL,HGLOBAL) PURE;
     STDMETHOD(ContextSensitiveHelp) (THIS_ BOOL) PURE;
     STDMETHOD(GetClipboardData) (THIS_ CHARRANGE*,DWORD,LPDATAOBJECT*) PURE;
     STDMETHOD(GetDragDropEffect) (THIS_ BOOL,DWORD,PDWORD) PURE;
     STDMETHOD(GetContextMenu) (THIS_ WORD,LPOLEOBJECT,CHARRANGE*,HMENU*) PURE;
 };
References DeleteObject(), GetClipboardData(), HMENU, LONG, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
Variable Documentation
IID_IRichEditOle
const GUID IID_IRichEditOle
IID_IRichEditOleCallback
const GUID IID_IRichEditOleCallback