ZEQ2-Lite: GraphicsPathIterator Class Reference
GraphicsPathIterator Class Reference
#include <gdipluspath.h>
Public Member Functions
GraphicsPathIterator (GraphicsPath *path)
~GraphicsPathIterator ()
INT CopyData (PointF *points, BYTE *types, INT startIndex, INT endIndex)
INT Enumerate (PointF *points, BYTE *types, INT count)
INT GetCount () const
Status GetLastStatus () const
INT GetSubpathCount () const
BOOL HasCurve () const
INT NextMarker (GraphicsPath *path)
INT NextMarker (INT *startIndex, INT *endIndex)
INT NextPathType (BYTE *pathType, INT *startIndex, INT *endIndex)
INT NextSubpath (GraphicsPath *path, BOOL *isClosed)
INT NextSubpath (INT *startIndex, INT *endIndex, BOOL *isClosed)
VOID Rewind ()
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
GraphicsPathIterator (const GraphicsPathIterator &)
GraphicsPathIterator (GpPathIterator *pathIterator, Status status)
GraphicsPathIterator & operator= (const GraphicsPathIterator &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpPathIterator * nativePathIterator
Detailed Description
Definition at line 532 of file gdipluspath.h.
Constructor & Destructor Documentation
GraphicsPathIterator() [1/3]
GraphicsPathIterator::GraphicsPathIterator (GraphicsPath * path) inline
Definition at line 535 of file gdipluspath.h.
                                             :
         nativePathIterator(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreatePathIter(
                 &nativePathIterator,
                 path ? path->nativePath : NULL);
     }
References GdipCreatePathIter(), lastStatus, GraphicsPath::nativePath, nativePathIterator, and NULL.
~GraphicsPathIterator()
GraphicsPathIterator::~GraphicsPathIterator () inline
Definition at line 542 of file gdipluspath.h.
     {
         DllExports::GdipDeletePathIter(nativePathIterator);
     }
References GdipDeletePathIter(), and nativePathIterator.
GraphicsPathIterator() [2/3]
GraphicsPathIterator::GraphicsPathIterator (GpPathIterator * pathIterator, Status status) inline private
Definition at line 637 of file gdipluspath.h.
                                                                      :
         nativePathIterator(pathIterator), lastStatus(status) {}
GraphicsPathIterator() [3/3]
GraphicsPathIterator::GraphicsPathIterator (const GraphicsPathIterator &) private
Member Function Documentation
CopyData()
INT GraphicsPathIterator::CopyData (PointF * points, BYTE * types, INT startIndex, INT endIndex) inline
Definition at line 547 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterCopyData(
                 nativePathIterator, &result,
                 points, types, startIndex, endIndex));
         return result;
     }
References GdipPathIterCopyData(), nativePathIterator, types, and updateStatus().
Enumerate()
INT GraphicsPathIterator::Enumerate (PointF * points, BYTE * types, INT count) inline
Definition at line 555 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterEnumerate(
                 nativePathIterator, &result,
                 points, types, count));
         return result;
     }
References GdipPathIterEnumerate(), nativePathIterator, types, and updateStatus().
GetCount()
INT GraphicsPathIterator::GetCount () const inline
Definition at line 563 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterGetCount(
                 nativePathIterator, &result));
         return result;
     }
References GdipPathIterGetCount(), nativePathIterator, and updateStatus().
GetLastStatus()
Status GraphicsPathIterator::GetLastStatus () const inline
Definition at line 570 of file gdipluspath.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetSubpathCount()
INT GraphicsPathIterator::GetSubpathCount () const inline
Definition at line 576 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterGetSubpathCount(
                 nativePathIterator, &result));
         return result;
     }
References GdipPathIterGetSubpathCount(), nativePathIterator, and updateStatus().
HasCurve()
BOOL GraphicsPathIterator::HasCurve () const inline
Definition at line 583 of file gdipluspath.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipPathIterHasCurve(
                 nativePathIterator, &result));
         return result;
     }
References FALSE, GdipPathIterHasCurve(), nativePathIterator, and updateStatus().
NextMarker() [1/2]
INT GraphicsPathIterator::NextMarker (GraphicsPath * path) inline
Definition at line 598 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterNextMarkerPath(
                 nativePathIterator, &result,
                 path ? path->nativePath : NULL));
         return result;
     }
References GdipPathIterNextMarkerPath(), GraphicsPath::nativePath, nativePathIterator, NULL, and updateStatus().
NextMarker() [2/2]
INT GraphicsPathIterator::NextMarker (INT * startIndex, INT * endIndex) inline
Definition at line 590 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterNextMarker(
                 nativePathIterator, &result,
                 startIndex, endIndex));
         return result;
     }
References GdipPathIterNextMarker(), nativePathIterator, and updateStatus().
NextPathType()
INT GraphicsPathIterator::NextPathType (BYTE * pathType, INT * startIndex, INT * endIndex) inline
Definition at line 606 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterNextPathType(
                 nativePathIterator, &result,
                 pathType, startIndex, endIndex));
         return result;
     }
References GdipPathIterNextPathType(), nativePathIterator, and updateStatus().
NextSubpath() [1/2]
INT GraphicsPathIterator::NextSubpath (GraphicsPath * path, BOOL * isClosed) inline
Definition at line 622 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterNextSubpathPath(
                 nativePathIterator, &result,
                 path ? path->nativePath : NULL, isClosed));
         return result;
     }
References GdipPathIterNextSubpathPath(), GraphicsPath::nativePath, nativePathIterator, NULL, and updateStatus().
NextSubpath() [2/2]
INT GraphicsPathIterator::NextSubpath (INT * startIndex, INT * endIndex, BOOL * isClosed) inline
Definition at line 614 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipPathIterNextSubpath(
                 nativePathIterator, &result,
                 startIndex, endIndex, isClosed));
         return result;
     }
References GdipPathIterNextSubpath(), nativePathIterator, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
GraphicsPathIterator& GraphicsPathIterator::operator= (const GraphicsPathIterator &) private
Rewind()
VOID GraphicsPathIterator::Rewind () inline
Definition at line 630 of file gdipluspath.h.
     {
         updateStatus(DllExports::GdipPathIterRewind(
                 nativePathIterator));
     }
References GdipPathIterRewind(), nativePathIterator, and updateStatus().
updateStatus()
Status GraphicsPathIterator::updateStatus (Status newStatus) const inline private
Definition at line 642 of file gdipluspath.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by CopyData(), Enumerate(), GetCount(), GetSubpathCount(), HasCurve(), NextMarker(), NextPathType(), NextSubpath(), and Rewind().
Field Documentation
lastStatus
Status GraphicsPathIterator::lastStatus mutable private
Definition at line 649 of file gdipluspath.h.
Referenced by GetLastStatus(), GraphicsPathIterator(), and updateStatus().
nativePathIterator
GpPathIterator* GraphicsPathIterator::nativePathIterator private
Definition at line 648 of file gdipluspath.h.
Referenced by CopyData(), Enumerate(), GetCount(), GetSubpathCount(), GraphicsPathIterator(), HasCurve(), NextMarker(), NextPathType(), NextSubpath(), Rewind(), and ~GraphicsPathIterator().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdipluspath.h