ZEQ2-Lite: Engine/tools/lcc/lburg/lburg.h File Reference
lburg.h File Reference
Data Structures
struct Nonterm
struct Rule
struct Term
struct Tree
Enumerations
enum Kind { TERM =1, NONTERM }
Functions
void * alloc (int nbytes)
Nonterm nonterm (char *id)
Rule rule (char *id, Tree pattern, char *template, char *code)
Term term (char *id, int esn)
Tree tree (char *op, Tree left, Tree right)
void yyerror (char *fmt,...)
int yyparse (void)
void yywarn (char *fmt,...)
Variables
int errcnt
FILE * infp
FILE * outfp
Enumeration Type Documentation
Kind
enum Kind
Enumerator
TERM
NONTERM
Definition at line 7 of file lburg.h.
 { TERM=1, NONTERM } Kind;
Function Documentation
alloc()
void* alloc (int nbytes)
Definition at line 106 of file lburg.c.
{
     struct block *p = calloc(1, sizeof *p + nbytes);
     if (p == NULL) {
         yyerror("out of memory\n");
         exit(1);
     }
     p->link = memlist;
     memlist = p;
     return p + 1;
 }
References calloc(), exit(), memlist, NULL, and yyerror.
Referenced by emitkids(), emitnts(), install(), rule(), stringf(), and tree().
nonterm()
Nonterm nonterm (char * id)
Definition at line 170 of file lburg.c.
{
     Nonterm p = lookup(id), *q = &nts;
     if (p && p->kind == NONTERM)
         return p;
     if (p && p->kind == TERM)
         yyerror("`%s' is a terminal\n", id);
     p = install(id);
     p->kind = NONTERM;
     p->number = ++ntnumber;
     if (p->number == 1)
         start = p;
     while (*q && (*q)->number < p->number)
         q = &(*q)->link;
     assert(*q == 0 || (*q)->number != p->number);
     p->link = *q;
     *q = p;
     return p;
 }
References assert, install(), lookup(), NONTERM, ntnumber, nts, TERM, and yyerror.
Referenced by rule(), tree(), and yyparse().
rule()
Rule rule (char * id, Tree pattern, char * template, char * code)
Definition at line 244 of file lburg.c.
{
     Rule r = alloc(sizeof *r), *q;
     Term p = pattern->op;
     char *end;
     r->lhs = nonterm(id);
     r->packed = ++r->lhs->lhscount;
     for (q = &r->lhs->rules; *q; q = &(*q)->decode)
         ;
     *q = r;
     r->pattern = pattern;
     r->ern = ++nrules;
     r->template = template;
     r->code = code;
     r->cost = strtol(code, &end, 10);
     if (*end) {
         r->cost = -1;
         r->code = stringf("(%s)", code);
     }
     if (p->kind == TERM) {
         for (q = &p->rules; *q; q = &(*q)->next)
             ;
         *q = r;
     } else if (pattern->left == NULL && pattern->right == NULL) {
         Nonterm p = pattern->op;
         r->chain = p->chain;
             p->chain = r;
         if (r->cost == -1)
             yyerror("illegal nonconstant cost `%s'\n", code);
     }
     for (q = &rules; *q; q = &(*q)->link)
         ;
     r->link = *q;
     *q = r;
     return r;
 }
References alloc(), code, nonterm(), nrules, NULL, rules, stringf(), strtol(), TERM, and yyerror.
Referenced by yyparse().
term()
Term term (char * id, int esn)
Definition at line 191 of file lburg.c.
{
     Term p = lookup(id), *q = &terms;
     if (p)
         yyerror("redefinition of terminal `%s'\n", id);
     else
         p = install(id);
     p->kind = TERM;
     p->esn = esn;
     p->arity = -1;
     while (*q && (*q)->esn < p->esn)
         q = &(*q)->link;
     if (*q && (*q)->esn == p->esn)
         yyerror("duplicate external symbol number `%s=%d'\n",
             p->name, p->esn);
     p->link = *q;
     *q = p;
     return p;
 }
References install(), lookup(), TERM, terms, and yyerror.
Referenced by tree(), and yyparse().
tree()
Tree tree (char * op, Tree left, Tree right)
Definition at line 212 of file lburg.c.
{
     Tree t = alloc(sizeof *t);
     Term p = lookup(id);
     int arity = 0;
     if (left && right)
         arity = 2;
     else if (left)
         arity = 1;
     if (p == NULL && arity > 0) {
         yyerror("undefined terminal `%s'\n", id);
         p = term(id, -1);
     } else if (p == NULL && arity == 0)
         p = (Term)nonterm(id);
     else if (p && p->kind == NONTERM && arity > 0) {
         yyerror("`%s' is a nonterminal\n", id);
         p = term(id, -1);
     }
     if (p->kind == TERM && p->arity == -1)
         p->arity = arity;
     if (p->kind == TERM && arity != p->arity)
         yyerror("inconsistent arity for terminal `%s'\n", id);
     t->op = p;
     t->nterms = p->kind == TERM;
     if ((t->left = left) != NULL)
         t->nterms += left->nterms;
     if ((t->right = right) != NULL)
         t->nterms += right->nterms;
     return t;
 }
References alloc(), lookup(), NONTERM, nonterm(), NULL, right, TERM, term(), and yyerror.
Referenced by addrof(), addrtree(), asgn(), asgntree(), bbcall(), bbincr(), call(), calltree(), cnsttree(), condtree(), expr(), field(), idtree(), listnodes(), nullcheck(), postfix(), primary(), retcode(), retype(), rvalue(), simplify(), swcode(), tracefinis(), tracevalue(), unary(), vcall(), and yyparse().
yyerror()
void yyerror (char * fmt, ...)
Definition at line 1713 of file gram.c.
{
     va_list ap;
     va_start(ap, fmt);
     if (yylineno > 0)
         fprintf(stderr, "line %d: ", yylineno);
     vfprintf(stderr, fmt, ap);
     if (fmt[strlen(fmt)-1] != '\n')
          fprintf(stderr, "\n");
     errcnt++;
     va_end(ap);
 }
References errcnt, fmt, fprintf(), stderr, strlen(), va_end, va_start, vfprintf(), and yylineno.
Referenced by yylex(), and yyparse().
yyparse()
int yyparse (void)
Definition at line 1124 of file gram.c.
 {
     int yystate;
     /* Number of tokens to shift before error messages enabled.  */
     int yyerrstatus;
     /* The stacks and their tools:
        `yyss': related to states.
        `yyvs': related to semantic values.
        Refer to the stacks thru separate pointers, to allow yyoverflow
        to reallocate them elsewhere.  */
     /* The state stack.  */
     yytype_int16 yyssa[YYINITDEPTH];
     yytype_int16 *yyss;
     yytype_int16 *yyssp;
     /* The semantic value stack.  */
     YYSTYPE yyvsa[YYINITDEPTH];
     YYSTYPE *yyvs;
     YYSTYPE *yyvsp;
     YYSIZE_T yystacksize;
   int yyn;
   int yyresult;
   /* Lookahead token as an internal (translated) token number.  */
   int yytoken;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
 #if YYERROR_VERBOSE
   /* Buffer for error messages, and its allocated size.  */
   char yymsgbuf[128];
   char *yymsg = yymsgbuf;
   YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
 #endif
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   yytoken = 0;
   yyss = yyssa;
   yyvs = yyvsa;
   yystacksize = YYINITDEPTH;
   YYDPRINTF ((stderr, "Starting parse\n"));
   yystate = 0;
   yyerrstatus = 0;
   yynerrs = 0;
   yychar = YYEMPTY; /* Cause a token to be read.  */
   /* Initialize stack pointers.
      Waste one element of value and location stack
      so that they stay on the same level as the state stack.
      The wasted elements are never initialized.  */
   yyssp = yyss;
   yyvsp = yyvs;
   goto yysetstate;
 /*------------------------------------------------------------.
 | yynewstate -- Push a new state, which is found in yystate.  |
 `------------------------------------------------------------*/
  yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
  yysetstate:
   *yyssp = yystate;
   if (yyss + yystacksize - 1 <= yyssp)
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYSIZE_T yysize = yyssp - yyss + 1;
 #ifdef yyoverflow
       {
     /* Give user a chance to reallocate the stack.  Use copies of
        these so that the &'s don't force the real ones into
        memory.  */
     YYSTYPE *yyvs1 = yyvs;
     yytype_int16 *yyss1 = yyss;
     /* Each stack pointer address is followed by the size of the
        data in use in that stack, in bytes.  This used to be a
        conditional around just the two extra args, but that might
        be undefined if yyoverflow is a macro.  */
     yyoverflow (YY_("memory exhausted"),
             &yyss1, yysize * sizeof (*yyssp),
             &yyvs1, yysize * sizeof (*yyvsp),
             &yystacksize);
     yyss = yyss1;
     yyvs = yyvs1;
       }
 #else /* no yyoverflow */
 # ifndef YYSTACK_RELOCATE
       goto yyexhaustedlab;
 # else
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
     goto yyexhaustedlab;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
     yystacksize = YYMAXDEPTH;
       {
     yytype_int16 *yyss1 = yyss;
     union yyalloc *yyptr =
       (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
     if (! yyptr)
       goto yyexhaustedlab;
     YYSTACK_RELOCATE (yyss_alloc, yyss);
     YYSTACK_RELOCATE (yyvs_alloc, yyvs);
 #  undef YYSTACK_RELOCATE
     if (yyss1 != yyssa)
       YYSTACK_FREE (yyss1);
       }
 # endif
 #endif /* no yyoverflow */
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YYDPRINTF ((stderr, "Stack size increased to %lu\n",
           (unsigned long int) yystacksize));
       if (yyss + yystacksize - 1 <= yyssp)
     YYABORT;
     }
   YYDPRINTF ((stderr, "Entering state %d\n", yystate));
   if (yystate == YYFINAL)
     YYACCEPT;
   goto yybackup;
 /*-----------.
 | yybackup.  |
 `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      lookahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to lookahead token.  */
   yyn = yypact[yystate];
   if (yyn == YYPACT_NINF)
     goto yydefault;
   /* Not known => get a lookahead token if don't already have one.  */
   /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF ((stderr, "Reading a token: "));
       yychar = YYLEX;
     }
   if (yychar <= YYEOF)
     {
       yychar = yytoken = YYEOF;
       YYDPRINTF ((stderr, "Now at end of input.\n"));
     }
   else
     {
       yytoken = YYTRANSLATE (yychar);
       YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yyn == 0 || yyn == YYTABLE_NINF)
     goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the lookahead token.  */
   YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
   /* Discard the shifted token.  */
   yychar = YYEMPTY;
   yystate = yyn;
   *++yyvsp = yylval;
   goto yynewstate;
 /*-----------------------------------------------------------.
 | yydefault -- do the default action for the current state.  |
 `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
 /*-----------------------------.
 | yyreduce -- Do a reduction.  |
 `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      `$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   YY_REDUCE_PRINT (yyn);
   switch (yyn)
     {
         case 2:
 /* Line 1464 of yacc.c  */
 #line 22 "Engine/tools/lcc/lburg/gram.y"
     { yylineno = 0; }
     break;
   case 3:
 /* Line 1464 of yacc.c  */
 #line 23 "Engine/tools/lcc/lburg/gram.y"
     { yylineno = 0; }
     break;
   case 7:
 /* Line 1464 of yacc.c  */
 #line 31 "Engine/tools/lcc/lburg/gram.y"
     {
         if (nonterm((yyvsp[(2) - (3)].string))->number != 1)
             yyerror("redeclaration of the start symbol\n");
         }
     break;
   case 9:
 /* Line 1464 of yacc.c  */
 #line 36 "Engine/tools/lcc/lburg/gram.y"
     { yyerrok; }
     break;
   case 11:
 /* Line 1464 of yacc.c  */
 #line 40 "Engine/tools/lcc/lburg/gram.y"
     { term((yyvsp[(2) - (4)].string), (yyvsp[(4) - (4)].n)); }
     break;
   case 13:
 /* Line 1464 of yacc.c  */
 #line 44 "Engine/tools/lcc/lburg/gram.y"
     { rule((yyvsp[(2) - (7)].string), (yyvsp[(4) - (7)].tree), (yyvsp[(5) - (7)].string), (yyvsp[(6) - (7)].string)); }
     break;
   case 15:
 /* Line 1464 of yacc.c  */
 #line 46 "Engine/tools/lcc/lburg/gram.y"
     { yyerrok; }
     break;
   case 16:
 /* Line 1464 of yacc.c  */
 #line 49 "Engine/tools/lcc/lburg/gram.y"
     { nonterm((yyval.string) = (yyvsp[(1) - (1)].string)); }
     break;
   case 17:
 /* Line 1464 of yacc.c  */
 #line 52 "Engine/tools/lcc/lburg/gram.y"
     { (yyval.tree) = tree((yyvsp[(1) - (1)].string),  0,  0); }
     break;
   case 18:
 /* Line 1464 of yacc.c  */
 #line 53 "Engine/tools/lcc/lburg/gram.y"
     { (yyval.tree) = tree((yyvsp[(1) - (4)].string), (yyvsp[(3) - (4)].tree),  0); }
     break;
   case 19:
 /* Line 1464 of yacc.c  */
 #line 54 "Engine/tools/lcc/lburg/gram.y"
     { (yyval.tree) = tree((yyvsp[(1) - (6)].string), (yyvsp[(3) - (6)].tree), (yyvsp[(5) - (6)].tree)); }
     break;
   case 20:
 /* Line 1464 of yacc.c  */
 #line 57 "Engine/tools/lcc/lburg/gram.y"
     { if (*(yyvsp[(1) - (1)].string) == 0) (yyval.string) = "0"; }
     break;
 /* Line 1464 of yacc.c  */
 #line 1461 "y.tab.c"
       default: break;
     }
   YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   *++yyvsp = yyval;
   /* Now `shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   yyn = yyr1[yyn];
   yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
   if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
     yystate = yytable[yystate];
   else
     yystate = yydefgoto[yyn - YYNTOKENS];
   goto yynewstate;
 /*------------------------------------.
 | yyerrlab -- here on detecting error |
 `------------------------------------*/
 yyerrlab:
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
 #if ! YYERROR_VERBOSE
       yyerror (YY_("syntax error"));
 #else
       {
     YYSIZE_T yysize = yysyntax_error (0, yystate, yychar);
     if (yymsg_alloc < yysize && yymsg_alloc < YYSTACK_ALLOC_MAXIMUM)
       {
         YYSIZE_T yyalloc = 2 * yysize;
         if (! (yysize <= yyalloc && yyalloc <= YYSTACK_ALLOC_MAXIMUM))
           yyalloc = YYSTACK_ALLOC_MAXIMUM;
         if (yymsg != yymsgbuf)
           YYSTACK_FREE (yymsg);
         yymsg = (char *) YYSTACK_ALLOC (yyalloc);
         if (yymsg)
           yymsg_alloc = yyalloc;
         else
           {
         yymsg = yymsgbuf;
         yymsg_alloc = sizeof yymsgbuf;
           }
       }
     if (0 < yysize && yysize <= yymsg_alloc)
       {
         (void) yysyntax_error (yymsg, yystate, yychar);
         yyerror (yymsg);
       }
     else
       {
         yyerror (YY_("syntax error"));
         if (yysize != 0)
           goto yyexhaustedlab;
       }
       }
 #endif
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse lookahead token after an
      error, discard it.  */
       if (yychar <= YYEOF)
     {
       /* Return failure if at end of input.  */
       if (yychar == YYEOF)
         YYABORT;
     }
       else
     {
       yydestruct ("Error: discarding",
               yytoken, &yylval);
       yychar = YYEMPTY;
     }
     }
   /* Else will try to reuse lookahead token after shifting the error
      token.  */
   goto yyerrlab1;
 /*---------------------------------------------------.
 | yyerrorlab -- error raised explicitly by YYERROR.  |
 `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers like GCC when the user code never invokes
      YYERROR and the label yyerrorlab therefore never appears in user
      code.  */
   if (/*CONSTCOND*/ 0)
      goto yyerrorlab;
   /* Do not reclaim the symbols of the rule which action triggered
      this YYERROR.  */
   YYPOPSTACK (yylen);
   yylen = 0;
   YY_STACK_PRINT (yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
 /*-------------------------------------------------------------.
 | yyerrlab1 -- common code for both syntax error and YYERROR.  |
 `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;  /* Each real token shifted decrements this.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (yyn != YYPACT_NINF)
     {
       yyn += YYTERROR;
       if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
         {
           yyn = yytable[yyn];
           if (0 < yyn)
         break;
         }
     }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
     YYABORT;
       yydestruct ("Error: popping",
           yystos[yystate], yyvsp);
       YYPOPSTACK (1);
       yystate = *yyssp;
       YY_STACK_PRINT (yyss, yyssp);
     }
   *++yyvsp = yylval;
   /* Shift the error token.  */
   YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
 /*-------------------------------------.
 | yyacceptlab -- YYACCEPT comes here.  |
 `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturn;
 /*-----------------------------------.
 | yyabortlab -- YYABORT comes here.  |
 `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturn;
 #if !defined(yyoverflow) || YYERROR_VERBOSE
 /*-------------------------------------------------.
 | yyexhaustedlab -- memory exhaustion comes here.  |
 `-------------------------------------------------*/
 yyexhaustedlab:
   yyerror (YY_("memory exhausted"));
   yyresult = 2;
   /* Fall through.  */
 #endif
 yyreturn:
   if (yychar != YYEMPTY)
      yydestruct ("Cleanup: discarding lookahead",
          yytoken, &yylval);
   /* Do not reclaim the symbols of the rule which action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK (yylen);
   YY_STACK_PRINT (yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct ("Cleanup: popping",
           yystos[*yyssp], yyvsp);
       YYPOPSTACK (1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE (yyss);
 #endif
 #if YYERROR_VERBOSE
   if (yymsg != yymsgbuf)
     YYSTACK_FREE (yymsg);
 #endif
   /* Make sure YYID is used.  */
   return YYID (yyresult);
 }
References nonterm(), rule(), stderr, YYSTYPE::string, term(), YYSTYPE::tree, tree(), void(), YY_, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerrlab1, yyerrok, yyerror(), yyerrstatus, YYFINAL, YYID, YYINITDEPTH, YYLAST, yylen, YYLEX, yylineno, yylloc, yylsp, yylval, YYMAXDEPTH, yyn, yynerrs, yynewstate, YYNTOKENS, yypact, YYPACT_NINF, yypgoto, YYPOPSTACK, yyr1, yyr2, yyresult, yyreturn, YYSIZE_T, yyss, yyalloc::yyss_alloc, yyssa, yyssp, YYSTACK_ALLOC, YYSTACK_ALLOC_MAXIMUM, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yystate, yystos, yytable, YYTABLE_NINF, YYTERROR, yytoken, YYTRANSLATE, yyvs, yyalloc::yyvs_alloc, yyvsa, and yyvsp.
yywarn()
void yywarn (char * fmt, ...)
Definition at line 1808 of file gram.c.
{
     va_list ap;
     va_start(ap, fmt);
     if (yylineno > 0)
         fprintf(stderr, "line %d: ", yylineno);
     fprintf(stderr, "warning: ");
     vfprintf(stderr, fmt, ap);
 }
References fmt, fprintf(), stderr, va_start, vfprintf(), and yylineno.
Referenced by get().
Variable Documentation
errcnt
int errcnt
Definition at line 1680 of file gram.c.
infp
FILE* infp
Definition at line 1681 of file gram.c.
Referenced by get(), and main().
outfp
FILE* outfp
Definition at line 1682 of file gram.c.
Referenced by get(), main(), and print().