ZEQ2-Lite: Tools/MinGW/include/string.h File Reference
string.h File Reference
#include <_mingw.h>
#include <stddef.h>
Macros
#define __need_NULL
#define __need_size_t
#define __need_wchar_t
#define _wcscmpi _wcsicmp
#define _WSTRING_DEFINED
Functions
_CRTIMP void *__cdecl __MINGW_NOTHROW _memccpy (void *, const void *, int, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW _memicmp (const void *, const void *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW _strcmpi (const char *, const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW _strdup (const char *) __MINGW_ATTRIB_MALLOC
_CRTIMP char *__cdecl __MINGW_NOTHROW _strerror (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _stricmp (const char *, const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _stricoll (const char *, const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW _strlwr (char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _strnicmp (const char *, const char *, size_t)
_CRTIMP char *__cdecl __MINGW_NOTHROW _strnset (char *, int, size_t)
_CRTIMP char *__cdecl __MINGW_NOTHROW _strrev (char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW _strset (char *, int)
_CRTIMP char *__cdecl __MINGW_NOTHROW _strupr (char *)
_CRTIMP void __cdecl __MINGW_NOTHROW _swab (const char *, char *, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsdup (const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsicmp (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsicoll (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcslwr (wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsnicmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsnset (wchar_t *, wchar_t, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsrev (wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsset (wchar_t *, wchar_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsupr (wchar_t *)
_CRTIMP void *__cdecl __MINGW_NOTHROW memccpy (void *, const void *, int, size_t)
_CRTIMP void *__cdecl __MINGW_NOTHROW memchr (const void *, int, size_t) __MINGW_ATTRIB_PURE
_CRTIMP int __cdecl __MINGW_NOTHROW memcmp (const void *, const void *, size_t) __MINGW_ATTRIB_PURE
_CRTIMP void *__cdecl __MINGW_NOTHROW memcpy (void *, const void *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW memicmp (const void *, const void *, size_t)
_CRTIMP void *__cdecl __MINGW_NOTHROW memmove (void *, const void *, size_t)
_CRTIMP void *__cdecl __MINGW_NOTHROW memset (void *, int, size_t)
int __cdecl __MINGW_NOTHROW strcasecmp (const char *, const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW strcat (char *, const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW strchr (const char *, int) __MINGW_ATTRIB_PURE
_CRTIMP int __cdecl __MINGW_NOTHROW strcmp (const char *, const char *) __MINGW_ATTRIB_PURE
_CRTIMP int __cdecl __MINGW_NOTHROW strcmpi (const char *, const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW strcoll (const char *, const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW strcpy (char *, const char *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW strcspn (const char *, const char *) __MINGW_ATTRIB_PURE
_CRTIMP char *__cdecl __MINGW_NOTHROW strdup (const char *) __MINGW_ATTRIB_MALLOC
_CRTIMP char *__cdecl __MINGW_NOTHROW strerror (int)
_CRTIMP int __cdecl __MINGW_NOTHROW stricmp (const char *, const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW stricoll (const char *, const char *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW strlen (const char *) __MINGW_ATTRIB_PURE
_CRTIMP char *__cdecl __MINGW_NOTHROW strlwr (char *)
int __cdecl __MINGW_NOTHROW strncasecmp (const char *, const char *, size_t)
_CRTIMP char *__cdecl __MINGW_NOTHROW strncat (char *, const char *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW strncmp (const char *, const char *, size_t) __MINGW_ATTRIB_PURE
_CRTIMP char *__cdecl __MINGW_NOTHROW strncpy (char *, const char *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW strnicmp (const char *, const char *, size_t)
_CRTIMP char *__cdecl __MINGW_NOTHROW strnset (char *, int, size_t)
_CRTIMP char *__cdecl __MINGW_NOTHROW strpbrk (const char *, const char *) __MINGW_ATTRIB_PURE
_CRTIMP char *__cdecl __MINGW_NOTHROW strrchr (const char *, int) __MINGW_ATTRIB_PURE
_CRTIMP char *__cdecl __MINGW_NOTHROW strrev (char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW strset (char *, int)
_CRTIMP size_t __cdecl __MINGW_NOTHROW strspn (const char *, const char *) __MINGW_ATTRIB_PURE
_CRTIMP char *__cdecl __MINGW_NOTHROW strstr (const char *, const char *) __MINGW_ATTRIB_PURE
_CRTIMP char *__cdecl __MINGW_NOTHROW strtok (char *, const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW strupr (char *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW strxfrm (char *, const char *, size_t)
_CRTIMP void __cdecl __MINGW_NOTHROW swab (const char *, char *, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcscat (wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcschr (const wchar_t *, wchar_t)
_CRTIMP int __cdecl __MINGW_NOTHROW wcscmp (const wchar_t *, const wchar_t *)
int __cdecl __MINGW_NOTHROW wcscmpi (const wchar_t *__ws1, const wchar_t *__ws2)
_CRTIMP int __cdecl __MINGW_NOTHROW wcscoll (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcscpy (wchar_t *, const wchar_t *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcscspn (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsdup (const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW wcsicmp (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW wcsicoll (const wchar_t *, const wchar_t *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcslen (const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcslwr (wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsncat (wchar_t *, const wchar_t *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW wcsncmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsncpy (wchar_t *, const wchar_t *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW wcsnicmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsnset (wchar_t *, wchar_t, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcspbrk (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsrchr (const wchar_t *, wchar_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsrev (wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsset (wchar_t *, wchar_t)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsspn (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsstr (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcstok (wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsupr (wchar_t *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsxfrm (wchar_t *, const wchar_t *, size_t)
Macro Definition Documentation
__need_NULL
#define __need_NULL
Definition at line 22 of file string.h.
__need_size_t
#define __need_size_t
Definition at line 20 of file string.h.
__need_wchar_t
#define __need_wchar_t
Definition at line 21 of file string.h.
_wcscmpi
#define _wcscmpi _wcsicmp
Definition at line 150 of file string.h.
_WSTRING_DEFINED
#define _WSTRING_DEFINED
Definition at line 192 of file string.h.
Function Documentation
_memccpy()
_CRTIMP void* __cdecl __MINGW_NOTHROW _memccpy (void * , const void * , int , size_t)
_memicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _memicmp (const void * , const void * , size_t)
_strcmpi()
_CRTIMP int __cdecl __MINGW_NOTHROW _strcmpi (const char * , const char *)
_strdup()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strdup (const char *)
_strerror()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strerror (const char *)
_stricmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _stricmp (const char * , const char *)
Referenced by strcasecmp().
_stricoll()
_CRTIMP int __cdecl __MINGW_NOTHROW _stricoll (const char * , const char *)
_strlwr()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strlwr (char *)
_strnicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _strnicmp (const char * , const char * , size_t)
Referenced by strncasecmp().
_strnset()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strnset (char * , int , size_t)
_strrev()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strrev (char *)
_strset()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strset (char * , int)
_strupr()
_CRTIMP char* __cdecl __MINGW_NOTHROW _strupr (char *)
_swab()
_CRTIMP void __cdecl __MINGW_NOTHROW _swab (const char * , char * , size_t)
_wcsdup()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsdup (const wchar_t *)
_wcsicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsicmp (const wchar_t * , const wchar_t *)
Referenced by wcscmpi().
_wcsicoll()
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsicoll (const wchar_t * , const wchar_t *)
_wcslwr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcslwr (wchar_t *)
_wcsnicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsnicmp (const wchar_t * , const wchar_t * , size_t)
_wcsnset()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsnset (wchar_t * , wchar_t , size_t)
_wcsrev()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsrev (wchar_t *)
_wcsset()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsset (wchar_t * , wchar_t)
_wcsupr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsupr (wchar_t *)
memccpy()
_CRTIMP void* __cdecl __MINGW_NOTHROW memccpy (void * , const void * , int , size_t)
memchr()
_CRTIMP void* __cdecl __MINGW_NOTHROW memchr (const void * , int , size_t)
memcmp()
_CRTIMP int __cdecl __MINGW_NOTHROW memcmp (const void * , const void * , size_t)
Referenced by CollapseMultitexture(), pcrecpp::StringPiece::compare(), NET_CompareBaseAdrMask(), NET_GetPacket(), pcrecpp::StringPiece::operator==(), R_LoadPNG(), pcrecpp::StringPiece::starts_with(), and SVC_BucketForAddress().
memcpy()
_CRTIMP void* __cdecl __MINGW_NOTHROW memcpy (void * , const void * , size_t)
Referenced by ArenaServers_LoadFavorites(), ArenaServers_Remove(), assemble_line(), blit2_32(), blit8_32(), blockcopy(), CG_Aura_ArrangeConvexHull(), CG_CopyClientAura(), CG_CopyUserWeaponGraphics(), CG_DrawActiveFrame(), CG_DrawStringExt(), CG_ImpactMark(), CG_ParseAnimationFile(), CG_Player(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CL_Ping_f(), CL_UpdateVisiblePings_f(), ConcatArgs(), CreatePath(), DecompressIDATs(), dst_insn_append(), ExtractFilePath(), ExtractLine(), funcdefn(), G_AddSpawnVarToken(), G_weapPhys_StoreBuffer(), hash_add_label(), loadWord(), MD5Final(), MD5Update(), MField_Draw(), move4_32(), move8_32(), mumble_set_context(), mumble_update_coordinates2(), NET_AddLocalAddress(), NET_OpenSocks(), NET_SetMulticast6(), ParseExpression(), PPC_AppendInstructions(), PPC_ComputeCode(), primary(), PSys_SpawnCachedSystem(), PSys_UpdateEmitters(), puttokens(), R_CalcBones(), R_LoadTGA(), RB_MDM_SurfaceAnim(), RotatePointAroundVector(), SNDDMA_AudioCallback(), SockadrToNetadr(), sparc_compute_code(), SV_ClientEnterWorld(), Sys_SendPacket(), Sys_StringToSockaddr(), UI_DrawString2(), and VM_CallCompiled().
memicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW memicmp (const void * , const void * , size_t)
memmove()
_CRTIMP void* __cdecl __MINGW_NOTHROW memmove (void * , const void * , size_t)
Definition at line 107 of file unix.c.
 {
     unsigned char *cdp, *csp;
     if (n<=0)
         return 0;
     cdp = dp;
     csp = (unsigned char *)sp;
     if (cdp < csp) {
         do {
             *cdp++ = *csp++;
         } while (--n);
     } else {
         cdp += n;
         csp += n;
         do {
             *--cdp = *--csp;
         } while (--n);
     }
     return 0;
 }
References sp.
Referenced by adjustrow(), blit4_32(), Cbuf_Execute(), CL_LoadConsoleHistory(), CL_NextDownload(), CollapseMultitexture(), Com_ReadFromPipe(), CON_Input(), Field_CharEvent(), Field_CompleteCommand(), Field_KeyDownEvent(), FinishShader(), foldline(), FS_ReplaceSeparators(), gettokens(), Info_RemoveKey(), MField_CharEvent(), MField_KeyDownEvent(), movetokenrow(), newhideset(), SV_DelBanEntryFromList(), and trigraph().
memset()
_CRTIMP void* __cdecl __MINGW_NOTHROW memset (void * , int , size_t)
Referenced by AddEarthquakeTremble(), ArenaServers_LoadFavorites(), ArenaServers_MenuInit(), ArenaServers_Remove(), ArenaServers_StartRefresh(), BuildOptimizedList(), BuildShaderStateConfig(), Camera_MenuInit(), CG_AddPlayerWeapon(), CG_AddTrailsToScene(), CG_AllocLocalEntity(), CG_AllocMark(), CG_Beam(), CG_CalcViewValues(), CG_ClearParticles(), CG_DamageBlendBlob(), CG_Draw3DLine(), CG_Draw3DModel(), CG_DrawBeamTable(), CG_FrameHist_Init(), CG_General(), CG_GetMilliseconds(), CG_Init(), CG_InitLocalEntities(), CG_InitMarkPolys(), CG_InitRadarBlips(), CG_InitTrails(), CG_Missile(), CG_Mover(), CG_NewClientInfo(), CG_ParseScores(), CG_Player(), CG_PlayerFloatSprite(), CG_Portal(), CG_RegisterClientAura(), CG_RegisterClientModelnameWithTiers(), CG_RegisterGraphics(), CG_ResetPlayerEntity(), CG_ServerCommand(), CG_weapGfx_Parse(), CG_weapGfx_ParseRemoteDefinition(), CG_weapGfx_ParseSoundFx(), CG_weapGfx_ParseTimedFx(), CG_weapGfx_ParseVoiceFx(), CG_weapGfx_StoreBuffer(), CG_WipeBeamTable(), ClientBegin(), ClientConnect(), ClientImpacts(), ClientThink_real(), Com_GetSystemEvent(), Com_InitPushEvent(), Controls_InitModel(), Controls_MenuInit(), Field_Clear(), G_FreeEntity(), G_InitGame(), G_LinkUserWeaponData(), G_TouchTriggers(), G_weapPhys_Parse(), G_weapPhys_ParseRemoteDefinition(), G_weapPhys_StoreBuffer(), IN_InitJoystick(), IN_JoyMove(), InGame_MenuInit(), labelhash_free(), LoadFileBlock(), main(), MD5Final(), MoveClientToIntermission(), mumble_link(), Music_MenuInit(), NET_AdrToString(), NET_GetLocalAddress(), NET_GetPacket(), NET_OpenSocks(), NET_StringToAdr(), Options_MenuInit(), OrderMesh(), PlayerModel_MenuInit(), PlayerModel_UpdateModel(), PmoveSingle(), Preferences_MenuInit(), PSys_InitCache(), PSys_InitConstraints(), PSys_InitEmitters(), PSys_InitForces(), PSys_InitParticles(), PSys_InitSystems(), PSys_ParseFile(), PSys_RenderSystems(), PSys_SpawnConstraint(), PSys_SpawnEmitter(), PSys_SpawnForce(), PSys_SpawnParticle(), PSys_SpawnSystem(), R_BloomInit(), R_CalcBones(), R_InitBloomTextures(), R_MDM_GetBoneTag(), reset(), RotatePointAroundVector(), setupTiers(), SNDDMA_AudioCallback(), SNDDMA_Init(), SpectatorThink(), StartServer_MenuInit(), SV_ClientEnterWorld(), Sys_SendPacket(), Sys_StringToSockaddr(), SystemSettings_MenuInit(), Team_InitGame(), TeamMain_MenuInit(), UI_ConfirmMenu_Style(), UI_CreditMenu(), UI_DrawPlayer(), UI_MainMenu(), UI_MenuLogo(), UI_MenuScene(), UI_Message(), UI_ParseAnimationFile(), UI_PlayerFloatSprite(), UI_PlayerInfo_SetModel(), UI_ServerInfoMenu(), Use_target_remove_powerups(), and VM_Compile().
strcasecmp()
int __cdecl __MINGW_NOTHROW strcasecmp (const char * __sz1, const char * __sz2)
Definition at line 98 of file string.h.
   {return _stricmp (__sz1, __sz2);}
References _stricmp().
strcat()
_CRTIMP char* __cdecl __MINGW_NOTHROW strcat (char * , const char *)
Referenced by appendDirToIncludeList(), ArenaServers_StartRefresh(), CG_Obituary(), CL_GetServerCommand(), Cmd_Args(), Cmd_ArgsFrom(), Cmd_CallTeamVote_f(), compose(), Con_Dump_f(), Controls_DrawKeyBinding(), DefaultExtension(), DefaultPath(), doinclude(), ExpandArg(), FS_GetModList(), G_RadarUpdateCS(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Key_Bind_f(), ParseStage(), PlayerModel_PicEvent(), PlayerModel_SetMenuItems(), PSys_InitCache(), Q_getwd(), ScanAndLoadShaderFiles(), SetQdirFromPath(), setupTiers(), SV_ConSay_f(), Text_Draw(), UI_LoadArenas(), UI_PlayerInfo_SetWeapon(), VM_Compile(), WriteMapFile(), and WriteVmFile().
strchr()
_CRTIMP char* __cdecl __MINGW_NOTHROW strchr (const char * , int)
Referenced by __attribute__(), assemble_line(), callsys(), CG_NewClientInfo(), CG_ServerCommand(), CL_NextDownload(), CL_ParseBinding(), CL_ServerStatusResponse(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), compose(), Cvar_ValidateString(), first(), FS_CreatePath(), G_ProcessIPBans(), Info_RemoveKey(), Info_RemoveKey_Big(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Info_Validate(), lcc_getopt(), main(), main_init(), NET_StringToAdr(), path2list(), R_LoadEntities(), R_RegisterMD3(), replace(), setupTiers(), strrep(), suffix(), SV_AddBanToList(), SV_DelBanFromList(), SV_ParseCIDRNotation(), SystemSettings_backChanges(), SystemSettings_GetAspectRatios(), SystemSettings_GetResolutions(), trace_init(), UI_RegisterClientModelname(), and yylex().
strcmp()
_CRTIMP int __cdecl __MINGW_NOTHROW strcmp (const char * , const char *)
Referenced by acaller(), appendDirToIncludeList(), ASM(), AssembleLine(), Camera_GetCvarDefault(), Camera_GetCvarValue(), CG_CustomSound(), CG_DrawChat(), CG_GetMilliseconds(), CG_Init(), CG_ParsePlaylist(), CG_ServerCommand(), CG_weapGfx_AddLinkRef(), CG_weapGfx_NextSym(), CG_weapGfx_Parse(), CheckParm(), CIN_PlayCinematic(), CL_ConfigstringModified(), CL_Connect_f(), CL_GetServerCommand(), CL_InitRef(), CL_MotdPacket(), CL_Ping_f(), CL_Reconnect_f(), CL_ServerInfoPacket(), CL_ServerStatus_f(), ClientConnect(), ClientUserinfoChanged(), CM_LoadMap(), Cmd_RemoveCommand(), COM_MatchToken(), Com_StartupVariable(), Controls_DrawPlayer(), Controls_GetCvarDefault(), Controls_GetCvarValue(), Cvar_Get(), Cvar_Set2(), Cvar_SetCheatState(), Cvar_Toggle_f(), emitkids(), emitnts(), emitrecalc(), EndOfScript(), find(), FixCoords(), funcdefn(), G_CallSpawn(), G_FindConfigstringIndex(), G_FindTeams(), G_weapPhys_AddLinkRef(), G_weapPhys_NextSym(), G_weapPhys_Parse(), G_weapPhys_ParseType(), get(), GetFlagForBone(), getop(), hashtable_symbol_exists(), Info_RemoveKey(), Info_RemoveKey_Big(), initinputs(), lcc_getopt(), LoadSMD(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), LoadSMD_ParseTriangles(), lookup(), lookup_label(), LookupSymbol(), main(), main_init(), MainMenu_DrawPlayer(), MatchToken(), NET_StringToAdr(), nullcheck(), opsort(), opt(), option(), parseflags(), ParseOptionFile(), parsereg(), ParseSkyParms(), ParseVector(), Pickup_Team(), PlayerModel_BuildList(), pragma(), prof_init(), progbeg(), R_AddIQMSurfaces(), R_AddMD3Surfaces(), R_FindImageFile(), R_GetTag(), R_IQMLerpTag(), R_MDM_AddAnimSurfaces(), R_MDM_GetBoneTag(), R_ScreenShot_f(), R_ScreenShotJPEG_f(), RE_GLSL_RegisterProgram(), RE_RegisterModel(), RE_RegisterSkin(), S_AL_Init(), stabline(), SV_DirectConnect(), SV_ExecuteClientCommand(), SV_GetChallenge(), SV_SetConfigstring(), SVC_RemoteCommand(), Sys_ParseArgs(), Sys_PlatformInit(), Think_SetupTrainTargets(), UI_ParseInfos(), unzStringFileNameCompare(), and VM_SymbolToValue().
strcmpi()
_CRTIMP int __cdecl __MINGW_NOTHROW strcmpi (const char * , const char *)
strcoll()
_CRTIMP int __cdecl __MINGW_NOTHROW strcoll (const char * , const char *)
strcpy()
_CRTIMP char* __cdecl __MINGW_NOTHROW strcpy (char * , const char *)
Referenced by AddRemap(), AddScriptToStack(), ArenaServers_DoRefresh(), ArenaServers_Go(), ArenaServers_LoadFavorites(), ArenaServers_MenuDraw(), ArenaServers_StartRefresh(), ASM(), Assemble(), CG_CheckChat(), CG_DrawChat(), CG_LoadClientInfo(), CG_LoadingClient(), CG_Obituary(), CIN_PlayCinematic(), CL_CheckForResend(), ClientUserinfoChanged(), Com_GetSystemEvent(), concat(), Controls_DrawKeyBinding(), Controls_DrawPlayer(), copystring(), CopyString(), DefaultPath(), DoAnims(), doinclude(), DoMeshes(), emitkids(), emitnts(), ExpandArg(), ExpandGamePath(), ExpandPath(), ExtractFileExtension(), FS_GetFileList(), FS_GetModList(), FS_LoadZipFile(), FS_ReturnPath(), genline(), GL_CheckErrors(), Info_RemoveKey_Big(), Info_SetValueForKey(), InitOpenGL(), LoadCFG(), LoadCFG_AddBoneToSet(), LoadCFG_Anim(), LoadCFG_Defaults(), LoadCFG_General(), LoadCFG_Mesh(), LoadCFG_Skeleton(), LoadSMD(), main(), MainMenu_DrawPlayer(), Music_MenuInit(), ParseOptionFile(), path2list(), PSys_InitCache(), Q_getwd(), R_CreateImage(), R_LoadEntities(), R_RegisterMD3(), S_Base_SoundList(), S_FindName(), SaveAnimation(), SaveMesh(), setobjname(), SetQdirFromPath(), SNDDMA_Init(), StartServer_Update(), stringf(), strsave(), SV_ConSay_f(), SVC_Status(), Sys_GetCurrentUser(), TeamplayInfoMessage(), Text_Draw(), UI_LoadArenas(), UI_ParseInfos(), UI_RegisterClientSkin(), VM_Compile(), WriteMapFile(), and WriteVmFile().
strcspn()
_CRTIMP size_t __cdecl __MINGW_NOTHROW strcspn (const char * , const char *)
strdup()
_CRTIMP char* __cdecl __MINGW_NOTHROW strdup (const char *)
strerror()
_CRTIMP char* __cdecl __MINGW_NOTHROW strerror (int)
Referenced by NET_ErrorString(), Q_mkdir(), SafeOpenRead(), and SafeOpenWrite().
stricmp()
_CRTIMP int __cdecl __MINGW_NOTHROW stricmp (const char * , const char *)
Referenced by LoadCFG(), LoadCFG_Anim(), LoadCFG_General(), LoadCFG_Mesh(), and LoadCFG_Skeleton().
stricoll()
_CRTIMP int __cdecl __MINGW_NOTHROW stricoll (const char * , const char *)
strlen()
_CRTIMP size_t __cdecl __MINGW_NOTHROW strlen (const char *)
Referenced by __attribute__(), Action_Init(), ArenaServers_Go(), ArenaServers_StartRefresh(), assemble_line(), Cbuf_AddText(), Cbuf_ExecuteText(), Cbuf_InsertText(), CG_BuildSpectatorString(), CG_DrawField(), CG_VoiceChatListForClient(), CL_ChangeReliableCommand(), CL_CheckForResend(), CL_ConfigstringModified(), CL_Connect_f(), CL_DemoCompleted(), CL_GetServerCommand(), CL_LoadConsoleHistory(), CL_LocalServers_f(), CL_NextDownload(), CL_ParseGamestate(), CL_Rcon_f(), CL_Reconnect_f(), CL_SaveConsoleHistory(), CL_ServerInfoPacket(), CL_ServerStatusResponse(), Cmd_Args_Sanitize(), Cmd_CallTeamVote_f(), Com_CharIsOneOfCharset(), COM_CompareExtension(), Com_Filter(), Com_GetSystemEvent(), Com_HexStrToInt(), Com_Printf(), Com_StringContains(), Com_TruncateLongString(), compose(), computekids(), computents(), Con_Dump_f(), CON_Hide(), CON_HistNext(), CON_HistPrev(), CON_Input(), CON_LogWrite(), CON_Print(), CON_Show(), concat(), ConcatArgs(), copystring(), CopyString(), Cvar_Update(), Cvar_WriteVariables(), DefaultExtension(), DeformText(), doinclude(), emitkids(), emitnts(), emitstring(), ExtractFileBase(), ExtractFileExtension(), ExtractFilePath(), Field_CharEvent(), Field_Complete(), Field_CompleteCommand(), Field_CustomDraw(), Field_FindFirstSeparator(), Field_KeyDownEvent(), Field_Paste(), Field_VariableSizeDraw(), FindMatches(), FS_AddGameDirectory(), FS_ComparePaks(), FS_FOpenFileReadDir(), FS_GetFileList(), FS_GetModList(), FS_IsExt(), FS_ListFilteredFiles(), FS_LoadZipFile(), FS_Printf(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), FS_ReferencedPakPureChecksums(), FS_ReplaceSeparators(), FS_SV_FileExists(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), G_AddSpawnVarToken(), G_LogPrintf(), G_NewString(), genline(), GLimp_DetectAvailableModes(), GLimp_HaveExtension(), GLimp_Init(), hash_add_label(), Hunk_Log(), Hunk_SmallLog(), IN_IsConsoleKey(), IN_TranslateSDLToQ3Key(), Info_RemoveKey(), Info_RemoveKey_Big(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Info_ValueForKey(), Key_StringToKeynum(), main(), MenuField_Init(), MField_CharEvent(), MField_Draw(), MField_KeyDownEvent(), MField_Paste(), mkstr(), MSG_WriteBigString(), MSG_WriteString(), mumble_set_description(), mumble_set_identity(), Music_MenuInit(), NET_OpenSocks(), NET_OutOfBandPrint(), parseAura(), parseTier(), path2list(), PlayerModel_BuildList(), PlayerModel_PicEvent(), PlayerModel_SetMenuItems(), Preferences_MenuInit(), PrintCvarMatches(), PrintMatches(), progbeg(), PSys_InitCache(), Q_strcat(), Q_stristr(), R_CreateImage(), R_IQMLerpTag(), R_LoadEntities(), R_LoadIQM(), R_LoadMD3(), R_MDM_AddAnimSurfaces(), RadioButton_Init(), RE_GLSL_RegisterProgram(), RE_RegisterModel(), RE_RegisterShader(), RE_RegisterShaderLightMap(), RE_RegisterShaderNoMip(), RE_RegisterSkin(), S_AL_Init(), S_Base_RegisterSound(), S_FindName(), ScanAndLoadShaderFiles(), SCR_DrawDemoRecording(), pcrecpp::StringPiece::set(), setobjname(), SetQdirFromPath(), setsource(), setup(), setup_kwtab(), Slider_Init(), SpinControl_Init(), strgtr(), stringf(), stringify(), StripExtension(), StripFilename(), strsave(), suffix(), SV_ConSay_f(), SV_DirectConnect(), SV_SendConfigstring(), SV_SendServerCommand(), SV_SpawnServer(), SV_Status_f(), SV_UserinfoChanged(), SV_WriteBans(), SVC_Info(), SVC_RemoteCommand(), SVC_Status(), Sys_AppendToExecBuffer(), Sys_Basename(), Sys_Dirname(), Sys_ListFiles(), Sys_ListFilteredFiles(), SystemSettings_SetMenuItems(), TeamplayInfoMessage(), UI_DrawString(), UI_LoadArenas(), UI_MainMenu(), UI_ParseInfos(), UI_ReadableSize(), unzLocateFile(), UpdateIPBans(), UpdateTournamentInfo(), VM_LoadSymbols(), WRITE_STRING(), yyerror(), and Z_LogZoneHeap().
strlwr()
_CRTIMP char* __cdecl __MINGW_NOTHROW strlwr (char *)
strncasecmp()
int __cdecl __MINGW_NOTHROW strncasecmp (const char * __sz1, const char * __sz2, size_t __sizeMaxCompare)
Definition at line 107 of file string.h.
   {return _strnicmp (__sz1, __sz2, __sizeMaxCompare);}
References _strnicmp().
strncat()
_CRTIMP char* __cdecl __MINGW_NOTHROW strncat (char * , const char * , size_t)
Referenced by CL_ServerInfoPacket(), myfopen(), and R_GLSL_LoadProgram().
strncmp()
_CRTIMP int __cdecl __MINGW_NOTHROW strncmp (const char * , const char * , size_t)
Referenced by ASM(), CL_UISystemCalls(), comparetokens(), dodefine(), emitrecalc(), help(), lookup(), lookuparg(), main(), main_init(), opt(), option(), prof_init(), R_CreateImage(), resynch(), suffix(), SV_SendServerCommand(), trace_init(), type_init(), and yylex().
strncpy()
_CRTIMP char* __cdecl __MINGW_NOTHROW strncpy (char * , const char * , size_t)
Referenced by appendstr(), builtin(), CG_ParsePlaylist(), CG_ShaderStateChanged(), CL_CgameSystemCalls(), CL_UISystemCalls(), compose(), doconcat(), doinclude(), first(), LoadSMD(), LoadSMD_ParseNodes(), LoadSMD_ParseTriangles(), newstring(), nexttok(), Parse(), parsearg(), path2list(), Q_strncpyz(), SaveAnimation(), SaveMesh(), SetQdirFromPath(), setsource(), SV_GameSystemCalls(), UpdatePaths(), and yylex().
strnicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW strnicmp (const char * , const char * , size_t)
strnset()
_CRTIMP char* __cdecl __MINGW_NOTHROW strnset (char * , int , size_t)
strpbrk()
_CRTIMP char* __cdecl __MINGW_NOTHROW strpbrk (const char * , const char *)
Referenced by Cmd_Args_Sanitize().
strrchr()
_CRTIMP char* __cdecl __MINGW_NOTHROW strrchr (const char * , int)
Referenced by basepath(), CG_LoadingClient(), CL_PlayDemo_f(), COM_DefaultExtension(), COM_GetExtension(), COM_StripExtension(), FS_IsDemoExt(), SV_WriteDownloadToClient(), and UpdatePaths().
strrev()
_CRTIMP char* __cdecl __MINGW_NOTHROW strrev (char *)
strset()
_CRTIMP char* __cdecl __MINGW_NOTHROW strset (char * , int)
strspn()
_CRTIMP size_t __cdecl __MINGW_NOTHROW strspn (const char * , const char *)
Referenced by nexttok(), and yylex().
strstr()
_CRTIMP char* __cdecl __MINGW_NOTHROW strstr (const char * , const char *)
Referenced by CG_ShaderStateChanged(), CIN_PlayCinematic(), CL_Frame(), FS_CheckDirTraversal(), FS_CreatePath(), FS_FileIsInPAK(), FS_FOpenFileReadDir(), FS_ReadFileDir(), G_SpawnGEntityFromSpawnVars(), initinputs(), opt(), PlayerModel_PicEvent(), PlayerModel_SetMenuItems(), RE_RegisterSkin(), SP_target_speaker(), SV_ExecuteClientMessage(), tempname(), and UI_LoadArenas().
strtok()
_CRTIMP char* __cdecl __MINGW_NOTHROW strtok (char * , const char *)
Referenced by Sys_GetClipboardData().
strupr()
_CRTIMP char* __cdecl __MINGW_NOTHROW strupr (char *)
Definition at line 562 of file cmdlib.c.
 {
     char    *in;
     in = start;
     while (*in)
     {
         *in = toupper(*in);
         in++;
     }
     return start;
 }
References in, and toupper().
strxfrm()
_CRTIMP size_t __cdecl __MINGW_NOTHROW strxfrm (char * , const char * , size_t)
swab()
_CRTIMP void __cdecl __MINGW_NOTHROW swab (const char * , char * , size_t)
wcscat()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcscat (wchar_t * , const wchar_t *)
wcschr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcschr (const wchar_t * , wchar_t)
wcscmp()
_CRTIMP int __cdecl __MINGW_NOTHROW wcscmp (const wchar_t * , const wchar_t *)
wcscmpi()
__CRT_INLINE int __cdecl __MINGW_NOTHROW wcscmpi (const wchar_t * __ws1, const wchar_t * __ws2)
Definition at line 176 of file string.h.
   {return _wcsicmp (__ws1, __ws2);}
References _wcsicmp().
wcscoll()
_CRTIMP int __cdecl __MINGW_NOTHROW wcscoll (const wchar_t * , const wchar_t *)
wcscpy()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcscpy (wchar_t * , const wchar_t *)
wcscspn()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcscspn (const wchar_t * , const wchar_t *)
wcsdup()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsdup (const wchar_t *)
wcsicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW wcsicmp (const wchar_t * , const wchar_t *)
wcsicoll()
_CRTIMP int __cdecl __MINGW_NOTHROW wcsicoll (const wchar_t * , const wchar_t *)
wcslen()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcslen (const wchar_t *)
wcslwr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcslwr (wchar_t *)
wcsncat()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsncat (wchar_t * , const wchar_t * , size_t)
wcsncmp()
_CRTIMP int __cdecl __MINGW_NOTHROW wcsncmp (const wchar_t * , const wchar_t * , size_t)
wcsncpy()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsncpy (wchar_t * , const wchar_t * , size_t)
wcsnicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW wcsnicmp (const wchar_t * , const wchar_t * , size_t)
wcsnset()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsnset (wchar_t * , wchar_t , size_t)
wcspbrk()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcspbrk (const wchar_t * , const wchar_t *)
wcsrchr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsrchr (const wchar_t * , wchar_t)
wcsrev()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsrev (wchar_t *)
wcsset()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsset (wchar_t * , wchar_t)
wcsspn()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsspn (const wchar_t * , const wchar_t *)
wcsstr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsstr (const wchar_t * , const wchar_t *)
wcstok()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcstok (wchar_t * , const wchar_t *)
wcsupr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsupr (wchar_t *)
wcsxfrm()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsxfrm (wchar_t * , const wchar_t * , size_t)