ZEQ2-Lite: Source/Engine/jpeg-8c/jcinit.c File Reference
jcinit.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define JPEG_INTERNALS
Functions
jinit_compress_master (j_compress_ptr cinfo)
Macro Definition Documentation
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 18 of file jcinit.c.
Function Documentation
jinit_compress_master()
jinit_compress_master (j_compress_ptr cinfo)
Definition at line 30 of file jcinit.c.
 {
   /* Initialize master control (includes parameter checking/processing) */
   jinit_c_master_control(cinfo, FALSE /* full compression */);
   /* Preprocessing */
   if (! cinfo->raw_data_in) {
     jinit_color_converter(cinfo);
     jinit_downsampler(cinfo);
     jinit_c_prep_controller(cinfo, FALSE /* never need full buffer here */);
   }
   /* Forward DCT */
   jinit_forward_dct(cinfo);
   /* Entropy encoding: either Huffman or arithmetic coding. */
   if (cinfo->arith_code)
     jinit_arith_encoder(cinfo);
   else {
     jinit_huff_encoder(cinfo);
   }
   /* Need a full-image coefficient buffer in any multi-pass mode. */
   jinit_c_coef_controller(cinfo,
         (boolean) (cinfo->num_scans > 1 || cinfo->optimize_coding));
   jinit_c_main_controller(cinfo, FALSE /* never need full buffer here */);
   jinit_marker_writer(cinfo);
   /* We can now tell the memory manager to allocate virtual arrays. */
   (*cinfo->mem->realize_virt_arrays) ((j_common_ptr) cinfo);
   /* Write the datastream header (SOI) immediately.
    * Frame and scan headers are postponed till later.
    * This lets application insert special markers after the SOI.
    */
   (*cinfo->marker->write_file_header) (cinfo);
 }
References FALSE, jinit_arith_encoder(), jinit_c_coef_controller(), jinit_c_main_controller(), jinit_c_master_control(), jinit_c_prep_controller(), jinit_color_converter(), jinit_downsampler(), jinit_forward_dct(), jinit_huff_encoder(), and jinit_marker_writer().
Referenced by jpeg_start_compress().