ZEQ2-Lite: Tools/MinGW/include/gdiplus/gdiplusmem.h File Reference
gdiplusmem.h File Reference
Functions
VOID *WINGDIPAPI GdipAlloc (size_t)
VOID WINGDIPAPI GdipFree (VOID *)
Function Documentation
GdipAlloc()
VOID* WINGDIPAPI GdipAlloc (size_t)
Referenced by FontCollection::GetFamilies(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), PathGradientBrush::GetSurroundColors(), Graphics::MeasureCharacterRanges(), GdiplusBase::operator new(), GdiplusBase::operator new[](), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), and PathGradientBrush::SetSurroundColors().
GdipFree()
VOID WINGDIPAPI GdipFree (VOID *)
Referenced by FontCollection::GetFamilies(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), PathGradientBrush::GetSurroundColors(), Graphics::MeasureCharacterRanges(), GdiplusBase::operator delete(), GdiplusBase::operator delete[](), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), and PathGradientBrush::SetSurroundColors().