ZEQ2-Lite: Game/Game/g_spawn.c File Reference
g_spawn.c File Reference
#include "g_local.h"
Data Structures
struct field_t
struct spawn_t
Macros
#define ADJUST_AREAPORTAL()
Enumerations
enum fieldtype_t {
F_INT, F_FLOAT, F_STRING, F_VECTOR,
F_ANGLEHACK
}
Functions
char * G_AddSpawnVarToken (const char *string)
qboolean G_CallSpawn (gentity_t *ent)
char * G_NewString (const char *string)
void G_ParseField (const char *key, const char *value, gentity_t *ent)
qboolean G_ParseSpawnVars (void)
void G_SpawnEntitiesFromString (void)
qboolean G_SpawnFloat (const char *key, const char *defaultString, float *out)
void G_SpawnGEntityFromSpawnVars (void)
qboolean G_SpawnInt (const char *key, const char *defaultString, int *out)
qboolean G_SpawnString (const char *key, const char *defaultString, char **out)
qboolean G_SpawnVector (const char *key, const char *defaultString, float *out)
void SP_func_bobbing (gentity_t *ent)
void SP_func_button (gentity_t *ent)
void SP_func_door (gentity_t *ent)
void SP_func_pendulum (gentity_t *ent)
void SP_func_plat (gentity_t *ent)
void SP_func_rotating (gentity_t *ent)
void SP_func_static (gentity_t *ent)
void SP_func_timer (gentity_t *self)
void SP_func_train (gentity_t *ent)
void SP_info_camp (gentity_t *self)
void SP_info_notnull (gentity_t *self)
void SP_info_null (gentity_t *self)
void SP_info_player_deathmatch (gentity_t *ent)
void SP_info_player_intermission (gentity_t *ent)
void SP_info_player_start (gentity_t *ent)
void SP_light (gentity_t *self)
void SP_misc_model (gentity_t *ent)
void SP_misc_portal_camera (gentity_t *ent)
void SP_misc_portal_surface (gentity_t *ent)
void SP_misc_teleporter_dest (gentity_t *self)
void SP_path_corner (gentity_t *self)
void SP_target_delay (gentity_t *ent)
void SP_target_give (gentity_t *ent)
void SP_target_kill (gentity_t *ent)
void SP_target_laser (gentity_t *self)
void SP_target_location (gentity_t *ent)
void SP_target_position (gentity_t *ent)
void SP_target_print (gentity_t *ent)
void SP_target_push (gentity_t *ent)
void SP_target_relay (gentity_t *ent)
void SP_target_remove_powerups (gentity_t *ent)
void SP_target_speaker (gentity_t *ent)
void SP_target_teleporter (gentity_t *ent)
void SP_trigger_always (gentity_t *ent)
void SP_trigger_hurt (gentity_t *ent)
void SP_trigger_multiple (gentity_t *ent)
void SP_trigger_push (gentity_t *ent)
void SP_trigger_teleport (gentity_t *ent)
void SP_worldspawn (void)
Variables
field_t fields []
spawn_t spawns []
Macro Definition Documentation
ADJUST_AREAPORTAL
#define ADJUST_AREAPORTAL ()
Value:
    if(ent->s.eType == ET_MOVER) \
    { \
        trap_LinkEntity(ent); \
        trap_AdjustAreaPortalState(ent, qtrue); \
    }
Definition at line 336 of file g_spawn.c.
Enumeration Type Documentation
fieldtype_t
enum fieldtype_t
Enumerator
F_INT
F_FLOAT
F_STRING
F_VECTOR
F_ANGLEHACK
Definition at line 77 of file g_spawn.c.
              {
     F_INT,
     F_FLOAT,
     F_STRING,
     F_VECTOR,
     F_ANGLEHACK
 } fieldtype_t;
Function Documentation
G_AddSpawnVarToken()
char* G_AddSpawnVarToken (const char * string)
Definition at line 427 of file g_spawn.c.
{
     int     l;
     char    *dest;
     l = strlen( string );
     if ( level.numSpawnVarChars + l + 1 > MAX_SPAWN_VARS_CHARS ) {
         G_Error( "G_AddSpawnVarToken: MAX_SPAWN_VARS" );
     }
     dest = level.spawnVarChars + level.numSpawnVarChars;
     memcpy( dest, string, l+1 );
     level.numSpawnVarChars += l + 1;
     return dest;
 }
References G_Error(), and MAX_SPAWN_VARS_CHARS.
Referenced by G_ParseSpawnVars().
G_CallSpawn()
qboolean G_CallSpawn (gentity_t * ent)
Definition at line 232 of file g_spawn.c.
{
     spawn_t *s;
     if ( !ent->classname ) {
         G_Printf ("G_CallSpawn: NULL classname\n");
         return qfalse;
     }
     // check normal spawn functions
     for ( s=spawns ; s->name ; s++ ) {
         if ( !strcmp(s->name, ent->classname) ) {
             // found it
             s->spawn(ent);
             return qtrue;
         }
     }
     G_Printf ("%s doesn't have a spawn function\n", ent->classname);
     return qfalse;
 }
References G_Printf(), spawn_t::name, qfalse, qtrue, and spawns.
Referenced by G_SpawnGEntityFromSpawnVars().
G_NewString()
char* G_NewString (const char * string)
Definition at line 259 of file g_spawn.c.
{
     char    *newb, *new_p;
     int     i,l;
     l = strlen(string) + 1;
     newb = G_Alloc( l );
     new_p = newb;
     // turn \n into a real linefeed
     for ( i=0 ; i< l ; i++ ) {
         if (string[i] == '\\' && i < l-1) {
             i++;
             if (string[i] == 'n') {
                 *new_p++ = '\n';
             } else {
                 *new_p++ = '\\';
             }
         } else {
             *new_p++ = string[i];
         }
     }
     return newb;
 }
References G_Alloc().
Referenced by G_ParseField().
G_ParseField()
void G_ParseField (const char * key, const char * value, gentity_t * ent)
Definition at line 297 of file g_spawn.c.
{
     field_t *f;
     byte    *b;
     float   v;
     vec3_t  vec;
     for ( f=fields ; f->name ; f++ ) {
         if ( !Q_stricmp(f->name, key) ) {
             // found it
             b = (byte *)ent;
             switch( f->type ) {
             case F_STRING:
                 *(char **)(b+f->ofs) = G_NewString (value);
                 break;
             case F_VECTOR:
                 sscanf (value, "%f %f %f", &vec[0], &vec[1], &vec[2]);
                 ((float *)(b+f->ofs))[0] = vec[0];
                 ((float *)(b+f->ofs))[1] = vec[1];
                 ((float *)(b+f->ofs))[2] = vec[2];
                 break;
             case F_INT:
                 *(int *)(b+f->ofs) = atoi(value);
                 break;
             case F_FLOAT:
                 *(float *)(b+f->ofs) = atof(value);
                 break;
             case F_ANGLEHACK:
                 v = atof(value);
                 ((float *)(b+f->ofs))[0] = 0;
                 ((float *)(b+f->ofs))[1] = v;
                 ((float *)(b+f->ofs))[2] = 0;
                 break;
             }
             return;
         }
     }
 }
References F_ANGLEHACK, F_FLOAT, F_INT, F_STRING, F_VECTOR, fields, G_NewString(), field_t::name, field_t::ofs, Q_stricmp(), field_t::type, and vec.
Referenced by G_SpawnGEntityFromSpawnVars().
G_ParseSpawnVars()
qboolean G_ParseSpawnVars (void)
Definition at line 454 of file g_spawn.c.
{
     char        keyname[MAX_TOKEN_CHARS];
     char        com_token[MAX_TOKEN_CHARS];
     level.numSpawnVars = 0;
     level.numSpawnVarChars = 0;
     // parse the opening brace
     if ( !trap_GetEntityToken( com_token, sizeof( com_token ) ) ) {
         // end of spawn string
         return qfalse;
     }
     if ( com_token[0] != '{' ) {
         G_Error( "G_ParseSpawnVars: found %s when expecting {",com_token );
     }
     // go through all the key / value pairs
     while ( 1 ) {
         // parse key
         if ( !trap_GetEntityToken( keyname, sizeof( keyname ) ) ) {
             G_Error( "G_ParseSpawnVars: EOF without closing brace" );
         }
         if ( keyname[0] == '}' ) {
             break;
         }
         // parse value
         if ( !trap_GetEntityToken( com_token, sizeof( com_token ) ) ) {
             G_Error( "G_ParseSpawnVars: EOF without closing brace" );
         }
         if ( com_token[0] == '}' ) {
             G_Error( "G_ParseSpawnVars: closing brace without data" );
         }
         if ( level.numSpawnVars == MAX_SPAWN_VARS ) {
             G_Error( "G_ParseSpawnVars: MAX_SPAWN_VARS" );
         }
         level.spawnVars[ level.numSpawnVars ][0] = G_AddSpawnVarToken( keyname );
         level.spawnVars[ level.numSpawnVars ][1] = G_AddSpawnVarToken( com_token );
         level.numSpawnVars++;
     }
     return qtrue;
 }
References com_token, G_AddSpawnVarToken(), G_Error(), MAX_SPAWN_VARS, MAX_TOKEN_CHARS, qfalse, qtrue, and trap_GetEntityToken().
Referenced by G_SpawnEntitiesFromString().
G_SpawnEntitiesFromString()
void G_SpawnEntitiesFromString (void)
Definition at line 563 of file g_spawn.c.
{
     // allow calls to G_Spawn*()
     level.spawning = qtrue;
     level.numSpawnVars = 0;
     // the worldspawn is not an actual entity, but it still
     // has a "spawn" function to perform any global setup
     // needed by a level (setting configstrings or cvars, etc)
     if ( !G_ParseSpawnVars() ) {
         G_Error( "SpawnEntities: no entities" );
     }
     SP_worldspawn();
     // parse ents
     while( G_ParseSpawnVars() ) {
         G_SpawnGEntityFromSpawnVars();
     }
     level.spawning = qfalse;            // any future calls to G_Spawn*() will be errors
 }
References G_Error(), G_ParseSpawnVars(), G_SpawnGEntityFromSpawnVars(), qfalse, qtrue, and SP_worldspawn().
Referenced by G_InitGame().
G_SpawnFloat()
qboolean G_SpawnFloat (const char * key, const char * defaultString, float * out)
Definition at line 45 of file g_spawn.c.
{
     char        *s;
     qboolean    present;
     present = G_SpawnString( key, defaultString, &s );
     *out = atof( s );
     return present;
 }
References G_SpawnString(), and out.
Referenced by InitMover(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_timer(), SP_misc_portal_camera(), SP_target_delay(), SP_target_speaker(), and SP_trigger_multiple().
G_SpawnGEntityFromSpawnVars()
void G_SpawnGEntityFromSpawnVars (void)
Definition at line 351 of file g_spawn.c.
{
     int         i;
     gentity_t   *ent;
     char        *s, *value, *gametypeName;
     static char *gametypeNames[] = {"ffa", "tournament", "single", "team", "ctf", "oneflag", "obelisk", "harvester"};
     // get the next free entity
     ent = G_Spawn();
     for ( i = 0 ; i < level.numSpawnVars ; i++ ) {
         G_ParseField( level.spawnVars[i][0], level.spawnVars[i][1], ent );
     }
     // check for "notsingle" flag
     if ( g_gametype.integer == GT_SINGLE_PLAYER ) {
         G_SpawnInt( "notsingle", "0", &i );
         if ( i ) {
             ADJUST_AREAPORTAL();
             G_FreeEntity( ent );
             return;
         }
     }
     // check for "notteam" flag (GT_FFA, GT_TOURNAMENT, GT_SINGLE_PLAYER)
     if ( g_gametype.integer >= GT_TEAM ) {
         G_SpawnInt( "notteam", "0", &i );
         if ( i ) {
             ADJUST_AREAPORTAL();
             G_FreeEntity( ent );
             return;
         }
     } else {
         G_SpawnInt( "notfree", "0", &i );
         if ( i ) {
             ADJUST_AREAPORTAL();
             G_FreeEntity( ent );
             return;
         }
     }
     G_SpawnInt( "notq3a", "0", &i );
     if ( i ) {
         ADJUST_AREAPORTAL();
         G_FreeEntity( ent );
         return;
     }
     if( G_SpawnString( "gametype", NULL, &value ) ) {
         if( g_gametype.integer >= GT_FFA && g_gametype.integer < GT_MAX_GAME_TYPE ) {
             gametypeName = gametypeNames[g_gametype.integer];
             s = strstr( value, gametypeName );
             if( !s ) {
                 ADJUST_AREAPORTAL();
                 G_FreeEntity( ent );
                 return;
             }
         }
     }
     // move editor origin to pos
     VectorCopy( ent->s.origin, ent->s.pos.trBase );
     VectorCopy( ent->s.origin, ent->r.currentOrigin );
     // if we didn't get a classname, don't bother spawning anything
     if ( !G_CallSpawn( ent ) ) {
         G_FreeEntity( ent );
     }
 }
References ADJUST_AREAPORTAL, G_CallSpawn(), G_FreeEntity(), g_gametype, G_ParseField(), G_Spawn(), G_SpawnInt(), G_SpawnString(), GT_FFA, GT_MAX_GAME_TYPE, GT_SINGLE_PLAYER, GT_TEAM, vmCvar_t::integer, NULL, and VectorCopy.
Referenced by G_SpawnEntitiesFromString().
G_SpawnInt()
qboolean G_SpawnInt (const char * key, const char * defaultString, int * out)
Definition at line 54 of file g_spawn.c.
{
     char        *s;
     qboolean    present;
     present = G_SpawnString( key, defaultString, &s );
     *out = atoi( s );
     return present;
 }
References G_SpawnString(), and out.
Referenced by G_SpawnGEntityFromSpawnVars(), SP_func_bobbing(), SP_func_door(), SP_func_pendulum(), and SP_func_plat().
G_SpawnString()
qboolean G_SpawnString (const char * key, const char * defaultString, char ** out)
Definition at line 26 of file g_spawn.c.
{
     int     i;
     if ( !level.spawning ) {
         *out = (char *)defaultString;
 //      G_Error( "G_SpawnString() called while not spawning" );
     }
     for ( i = 0 ; i < level.numSpawnVars ; i++ ) {
         if ( !Q_stricmp( key, level.spawnVars[i][0] ) ) {
             *out = level.spawnVars[i][1];
             return qtrue;
         }
     }
     *out = (char *)defaultString;
     return qfalse;
 }
References out, Q_stricmp(), qfalse, and qtrue.
Referenced by G_SpawnFloat(), G_SpawnGEntityFromSpawnVars(), G_SpawnInt(), G_SpawnVector(), InitMover(), SP_target_speaker(), and SP_worldspawn().
G_SpawnVector()
qboolean G_SpawnVector (const char * key, const char * defaultString, float * out)
Definition at line 63 of file g_spawn.c.
{
     char        *s;
     qboolean    present;
     present = G_SpawnString( key, defaultString, &s );
     sscanf( s, "%f %f %f", &out[0], &out[1], &out[2] );
     return present;
 }
References G_SpawnString(), and out.
Referenced by InitMover().
SP_func_bobbing()
void SP_func_bobbing (gentity_t * ent)
Definition at line 1488 of file g_mover.c.
{
     float       height;
     float       phase;
     G_SpawnFloat( "speed", "4", &ent->speed );
     G_SpawnFloat( "height", "32", &height );
     G_SpawnInt( "dmg", "2", &ent->damage );
     G_SpawnFloat( "phase", "0", &phase );
     trap_SetBrushModel( ent, ent->model );
     InitMover( ent );
     VectorCopy( ent->s.origin, ent->s.pos.trBase );
     VectorCopy( ent->s.origin, ent->r.currentOrigin );
     ent->s.pos.trDuration = ent->speed * 1000;
     ent->s.pos.trTime = ent->s.pos.trDuration * phase;
     ent->s.pos.trType = TR_SINE;
     // set the axis of bobbing
     if ( ent->spawnflags & 1 ) {
         ent->s.pos.trDelta[0] = height;
     } else if ( ent->spawnflags & 2 ) {
         ent->s.pos.trDelta[1] = height;
     } else {
         ent->s.pos.trDelta[2] = height;
     }
 }
References G_SpawnFloat(), G_SpawnInt(), InitMover(), TR_SINE, trap_SetBrushModel(), and VectorCopy.
SP_func_button()
void SP_func_button (gentity_t * ent)
Definition at line 1137 of file g_mover.c.
{
     vec3_t      abs_movedir;
     float       distance;
     vec3_t      size;
     float       lip;
     ent->sound1to2 = G_SoundIndex("sound/movers/switches/butn2.ogg");
     if ( !ent->speed ) {
         ent->speed = 40;
     }
     if ( !ent->wait ) {
         ent->wait = 1;
     }
     ent->wait *= 1000;
     // first position
     VectorCopy( ent->s.origin, ent->pos1 );
     // calculate second position
     trap_SetBrushModel( ent, ent->model );
     G_SpawnFloat( "lip", "4", &lip );
     G_SetMovedir( ent->s.angles, ent->movedir );
     abs_movedir[0] = fabs(ent->movedir[0]);
     abs_movedir[1] = fabs(ent->movedir[1]);
     abs_movedir[2] = fabs(ent->movedir[2]);
     VectorSubtract( ent->r.maxs, ent->r.mins, size );
     distance = abs_movedir[0] * size[0] + abs_movedir[1] * size[1] + abs_movedir[2] * size[2] - lip;
     VectorMA (ent->pos1, distance, ent->movedir, ent->pos2);
     if (ent->powerLevelTotal) {
         // shootable button
         ent->takedamage = qtrue;
     } else {
         // touchable button
         ent->touch = Touch_Button;
     }
     InitMover( ent );
 }
References G_SetMovedir(), G_SoundIndex(), G_SpawnFloat(), InitMover(), qtrue, Touch_Button(), trap_SetBrushModel(), VectorCopy, VectorMA(), and VectorSubtract.
SP_func_door()
void SP_func_door (gentity_t * ent)
Definition at line 885 of file g_mover.c.
{
     vec3_t  abs_movedir;
     float   distance;
     vec3_t  size;
     float   lip;
     ent->sound1to2 = ent->sound2to1 = G_SoundIndex("sound/movers/doors/dr1_strt.ogg");
     ent->soundPos1 = ent->soundPos2 = G_SoundIndex("sound/movers/doors/dr1_end.ogg");
     ent->blocked = Blocked_Door;
     // default speed of 400
     if (!ent->speed)
         ent->speed = 400;
     // default wait of 2 seconds
     if (!ent->wait)
         ent->wait = 2;
     ent->wait *= 1000;
     // default lip of 8 units
     G_SpawnFloat( "lip", "8", &lip );
     // default damage of 2 points
     G_SpawnInt( "dmg", "2", &ent->damage );
     // first position at start
     VectorCopy( ent->s.origin, ent->pos1 );
     // calculate second position
     trap_SetBrushModel( ent, ent->model );
     G_SetMovedir (ent->s.angles, ent->movedir);
     abs_movedir[0] = fabs(ent->movedir[0]);
     abs_movedir[1] = fabs(ent->movedir[1]);
     abs_movedir[2] = fabs(ent->movedir[2]);
     VectorSubtract( ent->r.maxs, ent->r.mins, size );
     distance = DotProduct( abs_movedir, size ) - lip;
     VectorMA( ent->pos1, distance, ent->movedir, ent->pos2 );
     // if "start_open", reverse position 1 and 2
     if ( ent->spawnflags & 1 ) {
         vec3_t  temp;
         VectorCopy( ent->pos2, temp );
         VectorCopy( ent->s.origin, ent->pos2 );
         VectorCopy( temp, ent->pos1 );
     }
     InitMover( ent );
     ent->nextthink = level.time + FRAMETIME;
     if ( ! (ent->flags & FL_TEAMSLAVE ) ) {
         int powerLevel;
         G_SpawnInt( "powerLevel", "0", &powerLevel );
         if ( powerLevel ) {
             ent->takedamage = qtrue;
         }
         if ( ent->targetname || powerLevel ) {
             // non touch/shoot doors
             ent->think = Think_MatchTeam;
         } else {
             ent->think = Think_SpawnNewDoorTrigger;
         }
     }
 }
References Blocked_Door(), DotProduct, FL_TEAMSLAVE, FRAMETIME, G_SetMovedir(), G_SoundIndex(), G_SpawnFloat(), G_SpawnInt(), InitMover(), qtrue, Think_MatchTeam(), Think_SpawnNewDoorTrigger(), trap_SetBrushModel(), VectorCopy, VectorMA(), and VectorSubtract.
SP_func_pendulum()
void SP_func_pendulum (gentity_t * ent)
Definition at line 1537 of file g_mover.c.
{
     float       freq;
     float       length;
     float       phase;
     float       speed;
     G_SpawnFloat( "speed", "30", &speed );
     G_SpawnInt( "dmg", "2", &ent->damage );
     G_SpawnFloat( "phase", "0", &phase );
     trap_SetBrushModel( ent, ent->model );
     // find pendulum length
     length = fabs( ent->r.mins[2] );
     if ( length < 8 ) {
         length = 8;
     }
     freq = 1 / ( M_PI * 2 ) * sqrt( 1000 / ( 3 * length ) );
     ent->s.pos.trDuration = ( 1000 / freq );
     InitMover( ent );
     VectorCopy( ent->s.origin, ent->s.pos.trBase );
     VectorCopy( ent->s.origin, ent->r.currentOrigin );
     VectorCopy( ent->s.angles, ent->s.apos.trBase );
     ent->s.apos.trDuration = 1000 / freq;
     ent->s.apos.trTime = ent->s.apos.trDuration * phase;
     ent->s.apos.trType = TR_SINE;
     ent->s.apos.trDelta[2] = speed;
 }
References G_SpawnFloat(), G_SpawnInt(), InitMover(), M_PI, TR_SINE, trap_SetBrushModel(), and VectorCopy.
SP_func_plat()
void SP_func_plat (gentity_t * ent)
Definition at line 1055 of file g_mover.c.
{
     float       lip, height;
     ent->sound1to2 = ent->sound2to1 = G_SoundIndex("sound/movers/plats/pt1_strt.ogg");
     ent->soundPos1 = ent->soundPos2 = G_SoundIndex("sound/movers/plats/pt1_end.ogg");
     VectorClear (ent->s.angles);
     G_SpawnFloat( "speed", "200", &ent->speed );
     G_SpawnInt( "dmg", "2", &ent->damage );
     G_SpawnFloat( "wait", "1", &ent->wait );
     G_SpawnFloat( "lip", "8", &lip );
     ent->wait = 1000;
     // create second position
     trap_SetBrushModel( ent, ent->model );
     if ( !G_SpawnFloat( "height", "0", &height ) ) {
         height = (ent->r.maxs[2] - ent->r.mins[2]) - lip;
     }
     // pos1 is the rest (bottom) position, pos2 is the top
     VectorCopy( ent->s.origin, ent->pos2 );
     VectorCopy( ent->pos2, ent->pos1 );
     ent->pos1[2] -= height;
     InitMover( ent );
     // touch function keeps the plat from returning while
     // a live player is standing on it
     ent->touch = Touch_Plat;
     ent->blocked = Blocked_Door;
     ent->parent = ent;  // so it can be treated as a door
     // spawn the trigger if one hasn't been custom made
     if ( !ent->targetname ) {
         SpawnPlatTrigger(ent);
     }
 }
References Blocked_Door(), G_SoundIndex(), G_SpawnFloat(), G_SpawnInt(), InitMover(), SpawnPlatTrigger(), Touch_Plat(), trap_SetBrushModel(), VectorClear, and VectorCopy.
SP_func_rotating()
void SP_func_rotating (gentity_t * ent)
Definition at line 1439 of file g_mover.c.
{
     if ( !ent->speed ) {
         ent->speed = 100;
     }
     // set the axis of rotation
     ent->s.apos.trType = TR_LINEAR;
     if ( ent->spawnflags & 4 ) {
         ent->s.apos.trDelta[2] = ent->speed;
     } else if ( ent->spawnflags & 8 ) {
         ent->s.apos.trDelta[0] = ent->speed;
     } else {
         ent->s.apos.trDelta[1] = ent->speed;
     }
     if (!ent->damage) {
         ent->damage = 2;
     }
     trap_SetBrushModel( ent, ent->model );
     InitMover( ent );
     VectorCopy( ent->s.origin, ent->s.pos.trBase );
     VectorCopy( ent->s.pos.trBase, ent->r.currentOrigin );
     VectorCopy( ent->s.apos.trBase, ent->r.currentAngles );
     trap_LinkEntity( ent );
 }
References InitMover(), TR_LINEAR, trap_LinkEntity(), trap_SetBrushModel(), and VectorCopy.
SP_func_static()
void SP_func_static (gentity_t * ent)
Definition at line 1411 of file g_mover.c.
{
     trap_SetBrushModel( ent, ent->model );
     InitMover( ent );
     VectorCopy( ent->s.origin, ent->s.pos.trBase );
     VectorCopy( ent->s.origin, ent->r.currentOrigin );
 }
References InitMover(), trap_SetBrushModel(), and VectorCopy.
SP_func_timer()
void SP_func_timer (gentity_t * self)
Definition at line 399 of file g_trigger.c.
{
     G_SpawnFloat( "random", "1", &self->random);
     G_SpawnFloat( "wait", "1", &self->wait );
     self->use = func_timer_use;
     self->think = func_timer_think;
     if ( self->random >= self->wait ) {
         self->random = self->wait - FRAMETIME;
         G_Printf( "func_timer at %s has random >= wait\n", vtos( self->s.origin ) );
     }
     if ( self->spawnflags & 1 ) {
         self->nextthink = level.time + FRAMETIME;
         self->activator = self;
     }
     self->r.svFlags = SVF_NOCLIENT;
 }
References FRAMETIME, func_timer_think(), func_timer_use(), G_Printf(), G_SpawnFloat(), SVF_NOCLIENT, and vtos().
SP_func_train()
void SP_func_train (gentity_t * ent)
Definition at line 1364 of file g_mover.c.
{
     VectorClear (self->s.angles);
     if (self->spawnflags & TRAIN_BLOCK_STOPS) {
         self->damage = 0;
     } else {
         if (!self->damage) {
             self->damage = 2;
         }
     }
     if ( !self->speed ) {
         self->speed = 100;
     }
     if ( !self->target ) {
         G_Printf ("func_train without a target at %s\n", vtos(self->r.absmin));
         G_FreeEntity( self );
         return;
     }
     trap_SetBrushModel( self, self->model );
     InitMover( self );
     self->reached = Reached_Train;
     // start trains on the second frame, to make sure their targets have had
     // a chance to spawn
     self->nextthink = level.time + FRAMETIME;
     self->think = Think_SetupTrainTargets;
 }
References FRAMETIME, G_FreeEntity(), G_Printf(), InitMover(), Reached_Train(), Think_SetupTrainTargets(), TRAIN_BLOCK_STOPS, trap_SetBrushModel(), VectorClear, and vtos().
SP_info_camp()
void SP_info_camp (gentity_t * self)
Definition at line 36 of file g_misc.c.
{
     G_SetOrigin( self, self->s.origin );
 }
References G_SetOrigin().
SP_info_notnull()
void SP_info_notnull (gentity_t * self)
Definition at line 53 of file g_misc.c.
{
     G_SetOrigin( self, self->s.origin );
 }
References G_SetOrigin().
SP_info_null()
void SP_info_null (gentity_t * self)
Definition at line 44 of file g_misc.c.
{
     G_FreeEntity( self );
 }
References G_FreeEntity().
SP_info_player_deathmatch()
void SP_info_player_deathmatch (gentity_t * ent)
Definition at line 36 of file g_client.c.
{
     int     i;
 }
Referenced by SP_info_player_start().
SP_info_player_intermission()
void SP_info_player_intermission (gentity_t * ent)
Definition at line 52 of file g_client.c.
{
 }
SP_info_player_start()
void SP_info_player_start (gentity_t * ent)
Definition at line 44 of file g_client.c.
{
     ent->classname = "info_player_deathmatch";
     SP_info_player_deathmatch( ent );
 }
References SP_info_player_deathmatch().
SP_light()
void SP_light (gentity_t * self)
Definition at line 65 of file g_misc.c.
{
     G_FreeEntity( self );
 }
References G_FreeEntity().
SP_misc_model()
void SP_misc_model (gentity_t * ent)
Definition at line 141 of file g_misc.c.
{
 #if 0
     ent->s.modelindex = G_ModelIndex( ent->model );
     VectorSet (ent->mins, -16, -16, -16);
     VectorSet (ent->maxs, 16, 16, 16);
     trap_LinkEntity (ent);
     G_SetOrigin( ent, ent->s.origin );
     VectorCopy( ent->s.angles, ent->s.apos.trBase );
 #else
     G_FreeEntity( ent );
 #endif
 }
References G_FreeEntity(), G_ModelIndex(), G_SetOrigin(), trap_LinkEntity(), VectorCopy, and VectorSet.
SP_misc_portal_camera()
void SP_misc_portal_camera (gentity_t * ent)
Definition at line 228 of file g_misc.c.
{
     float   roll;
     VectorClear( ent->r.mins );
     VectorClear( ent->r.maxs );
     trap_LinkEntity (ent);
     G_SpawnFloat( "roll", "0", &roll );
     ent->s.clientNum = roll/360.0 * 256;
 }
References G_SpawnFloat(), roll, trap_LinkEntity(), and VectorClear.
SP_misc_portal_surface()
void SP_misc_portal_surface (gentity_t * ent)
Definition at line 208 of file g_misc.c.
{
     VectorClear( ent->r.mins );
     VectorClear( ent->r.maxs );
     trap_LinkEntity (ent);
     ent->r.svFlags = SVF_PORTAL;
     ent->s.eType = ET_PORTAL;
     if ( !ent->target ) {
         VectorCopy( ent->s.origin, ent->s.origin2 );
     } else {
         ent->think = locateCamera;
         ent->nextthink = level.time + 100;
     }
 }
References ET_PORTAL, locateCamera(), SVF_PORTAL, trap_LinkEntity(), VectorClear, and VectorCopy.
SP_misc_teleporter_dest()
void SP_misc_teleporter_dest (gentity_t * self)
Definition at line 132 of file g_misc.c.
{
 }
SP_path_corner()
void SP_path_corner (gentity_t * self)
Definition at line 1341 of file g_mover.c.
{
     if ( !self->targetname ) {
         G_Printf ("path_corner with no targetname at %s\n", vtos(self->s.origin));
         G_FreeEntity( self );
         return;
     }
     // path corners don't need to be linked in
 }
References G_FreeEntity(), G_Printf(), and vtos().
SP_target_delay()
void SP_target_delay (gentity_t * ent)
Definition at line 71 of file g_target.c.
{
     // check delay for backwards compatability
     if ( !G_SpawnFloat( "delay", "0", &ent->wait ) ) {
         G_SpawnFloat( "wait", "1", &ent->wait );
     }
     if ( !ent->wait ) {
         ent->wait = 1;
     }
     ent->use = Use_Target_Delay;
 }
References G_SpawnFloat(), and Use_Target_Delay().
SP_target_give()
void SP_target_give (gentity_t * ent)
Definition at line 32 of file g_target.c.
{
     ent->use = Use_Target_Give;
 }
References Use_Target_Give().
SP_target_kill()
void SP_target_kill (gentity_t * ent)
Definition at line 338 of file g_target.c.
{
     self->use = target_kill_use;
 }
References target_kill_use().
SP_target_laser()
void SP_target_laser (gentity_t * self)
Definition at line 263 of file g_target.c.
 {
     // let everything else get spawned before we start firing
     self->think = target_laser_start;
     self->nextthink = level.time + FRAMETIME;
 }
References FRAMETIME, and target_laser_start().
SP_target_location()
void SP_target_location (gentity_t * ent)
Definition at line 387 of file g_target.c.
{
     self->think = target_location_linkup;
     self->nextthink = level.time + 200;  // Let them all spawn first
     G_SetOrigin( self, self->s.origin );
 }
References G_SetOrigin(), and target_location_linkup().
SP_target_position()
void SP_target_position (gentity_t * ent)
Definition at line 345 of file g_target.c.
{
     G_SetOrigin( self, self->s.origin );
 }
References G_SetOrigin().
SP_target_print()
void SP_target_print (gentity_t * ent)
Definition at line 117 of file g_target.c.
{
     ent->use = Use_Target_Print;
 }
References Use_Target_Print().
SP_target_push()
void SP_target_push (gentity_t * ent)
Definition at line 238 of file g_trigger.c.
{
     if (!self->speed) {
         self->speed = 1000;
     }
     G_SetMovedir (self->s.angles, self->s.origin2);
     VectorScale (self->s.origin2, self->speed, self->s.origin2);
     if ( self->spawnflags & 1 ) {
         self->noise_index = G_SoundIndex("sound/world/jumppad.ogg");
     } else {
         self->noise_index = G_SoundIndex("sound/misc/windfly.ogg");
     }
     if ( self->target ) {
         VectorCopy( self->s.origin, self->r.absmin );
         VectorCopy( self->s.origin, self->r.absmax );
         self->think = AimAtTarget;
         self->nextthink = level.time + FRAMETIME;
     }
     self->use = Use_target_push;
 }
References AimAtTarget(), FRAMETIME, G_SetMovedir(), G_SoundIndex(), Use_target_push(), VectorCopy, and VectorScale.
SP_target_relay()
void SP_target_relay (gentity_t * ent)
Definition at line 326 of file g_target.c.
{
     self->use = target_relay_use;
 }
References target_relay_use().
SP_target_remove_powerups()
void SP_target_remove_powerups (gentity_t * ent)
Definition at line 50 of file g_target.c.
{
     ent->use = Use_target_remove_powerups;
 }
References Use_target_remove_powerups().
SP_target_speaker()
void SP_target_speaker (gentity_t * ent)
Definition at line 154 of file g_target.c.
{
     char    buffer[MAX_QPATH];
     char    *s;
     G_SpawnFloat( "wait", "0", &ent->wait );
     G_SpawnFloat( "random", "0", &ent->random );
     if ( !G_SpawnString( "noise", "NOSOUND", &s ) ) {
         G_Error( "target_speaker without a noise key at %s", vtos( ent->s.origin ) );
     }
     // force all client reletive sounds to be "activator" speakers that
     // play on the entity that activates it
     if ( s[0] == '*' ) {
         ent->spawnflags |= 8;
     }
     if (!strstr( s, ".ogg" )) {
         Com_sprintf (buffer, sizeof(buffer), "%s.ogg", s );
     } else {
         Q_strncpyz( buffer, s, sizeof(buffer) );
     }
     ent->noise_index = G_SoundIndex(buffer);
     // a repeating speaker can be done completely client side
     ent->s.eType = ET_SPEAKER;
     ent->s.eventParm = ent->noise_index;
     ent->s.frame = ent->wait * 10;
     ent->s.clientNum = ent->random * 10;
     // check for prestarted looping sound
     if ( ent->spawnflags & 1 ) {
         ent->s.loopSound = ent->noise_index;
     }
     ent->use = Use_Target_Speaker;
     if (ent->spawnflags & 4) {
         ent->r.svFlags |= SVF_BROADCAST;
     }
     VectorCopy( ent->s.origin, ent->s.pos.trBase );
     // must link the entity so we get areas and clusters so
     // the server can determine who to send updates to
     trap_LinkEntity( ent );
 }
References Com_sprintf(), ET_SPEAKER, G_Error(), G_SoundIndex(), G_SpawnFloat(), G_SpawnString(), MAX_QPATH, Q_strncpyz(), SVF_BROADCAST, trap_LinkEntity(), Use_Target_Speaker(), VectorCopy, and vtos().
SP_target_teleporter()
void SP_target_teleporter (gentity_t * ent)
Definition at line 290 of file g_target.c.
{
     if (!self->targetname)
         G_Printf("untargeted %s at %s\n", self->classname, vtos(self->s.origin));
     self->use = target_teleporter_use;
 }
References G_Printf(), target_teleporter_use(), and vtos().
SP_trigger_always()
void SP_trigger_always (gentity_t * ent)
Definition at line 128 of file g_trigger.c.
{
     // we must have some delay to make sure our use targets are present
     ent->nextthink = level.time + 300;
     ent->think = trigger_always_think;
 }
References trigger_always_think().
SP_trigger_hurt()
void SP_trigger_hurt (gentity_t * ent)
Definition at line 355 of file g_trigger.c.
{
     InitTrigger (self);
     self->touch = hurt_touch;
 }
References hurt_touch(), and InitTrigger().
SP_trigger_multiple()
void SP_trigger_multiple (gentity_t * ent)
Definition at line 94 of file g_trigger.c.
{
     G_SpawnFloat( "wait", "0.5", &ent->wait );
     G_SpawnFloat( "random", "0", &ent->random );
     if ( ent->random >= ent->wait && ent->wait >= 0 ) {
         ent->random = ent->wait - FRAMETIME;
         G_Printf( "trigger_multiple has random >= wait\n" );
     }
     ent->touch = Touch_Multi;
     ent->use = Use_Multi;
     InitTrigger( ent );
     trap_LinkEntity (ent);
 }
References FRAMETIME, G_Printf(), G_SpawnFloat(), InitTrigger(), Touch_Multi(), trap_LinkEntity(), and Use_Multi().
SP_trigger_push()
void SP_trigger_push (gentity_t * ent)
Definition at line 199 of file g_trigger.c.
{
     InitTrigger (self);
     // unlike other triggers, we need to send this one to the client
     self->r.svFlags &= ~SVF_NOCLIENT;
     // make sure the client precaches this sound
     G_SoundIndex("sound/world/jumppad.ogg");
     self->s.eType = ET_PUSH_TRIGGER;
     self->touch = trigger_push_touch;
     self->think = AimAtTarget;
     self->nextthink = level.time + FRAMETIME;
     trap_LinkEntity (self);
 }
References AimAtTarget(), ET_PUSH_TRIGGER, FRAMETIME, G_SoundIndex(), InitTrigger(), SVF_NOCLIENT, trap_LinkEntity(), and trigger_push_touch().
SP_trigger_teleport()
void SP_trigger_teleport (gentity_t * ent)
Definition at line 301 of file g_trigger.c.
{
     InitTrigger (self);
     // unlike other triggers, we need to send this one to the client
     // unless is a spectator trigger
     if ( self->spawnflags & 1 ) {
         self->r.svFlags |= SVF_NOCLIENT;
     } else {
         self->r.svFlags &= ~SVF_NOCLIENT;
     }
     // make sure the client precaches this sound
     G_SoundIndex("sound/world/jumppad.ogg");
     self->s.eType = ET_TELEPORT_TRIGGER;
     self->touch = trigger_teleporter_touch;
     trap_LinkEntity (self);
 }
References ET_TELEPORT_TRIGGER, G_SoundIndex(), InitTrigger(), SVF_NOCLIENT, trap_LinkEntity(), and trigger_teleporter_touch().
SP_worldspawn()
void SP_worldspawn (void)
Definition at line 508 of file g_spawn.c.
{
     char    *s;
     G_SpawnString( "classname", "", &s );
     if ( Q_stricmp( s, "worldspawn" ) ) {
         G_Error( "SP_worldspawn: The first entity isn't 'worldspawn'" );
     }
     // make some data visible to connecting client
     trap_SetConfigstring( CS_GAME_VERSION, GAME_VERSION );
     trap_SetConfigstring( CS_LEVEL_START_TIME, va("%i", level.startTime ) );
 //  G_SpawnString( "music", "", &s );
 //  trap_SetConfigstring( CS_MUSIC, s );
     G_SpawnString( "message", "", &s );
     trap_SetConfigstring( CS_MESSAGE, s );              // map specific message
     trap_SetConfigstring( CS_MOTD, g_motd.string );     // message of the day
     G_SpawnString( "enableDust", "0", &s );
     trap_Cvar_Set( "g_enableDust", s );
     G_SpawnString( "enableBreath", "0", &s );
     trap_Cvar_Set( "g_enableBreath", s );
     g_entities[ENTITYNUM_WORLD].s.number = ENTITYNUM_WORLD;
     g_entities[ENTITYNUM_WORLD].r.ownerNum = ENTITYNUM_NONE;
     g_entities[ENTITYNUM_WORLD].classname = "worldspawn";
     g_entities[ENTITYNUM_NONE].s.number = ENTITYNUM_NONE;
     g_entities[ENTITYNUM_NONE].r.ownerNum = ENTITYNUM_NONE;
     g_entities[ENTITYNUM_NONE].classname = "nothing";
     // see if we want a warmup time
     trap_SetConfigstring( CS_WARMUP, "" );
     if ( g_restarted.integer ) {
         trap_Cvar_Set( "g_restarted", "0" );
         level.warmupTime = 0;
     } else if ( g_doWarmup.integer ) { // Turn it on
         level.warmupTime = -1;
         trap_SetConfigstring( CS_WARMUP, va("%i", level.warmupTime) );
         G_LogPrintf( "Warmup:\n" );
     }
 }
References CS_GAME_VERSION, CS_LEVEL_START_TIME, CS_MESSAGE, CS_MOTD, CS_WARMUP, ENTITYNUM_NONE, ENTITYNUM_WORLD, g_doWarmup, g_entities, G_Error(), G_LogPrintf(), g_motd, g_restarted, G_SpawnString(), GAME_VERSION, vmCvar_t::integer, Q_stricmp(), vmCvar_t::string, trap_Cvar_Set(), trap_SetConfigstring(), and va().
Referenced by G_SpawnEntitiesFromString().
Variable Documentation
fields
static void fields
Initial value:
= {
    {"classname", FOFS(classname), F_STRING},
    {"origin", FOFS(s.origin), F_VECTOR},
    {"model", FOFS(model), F_STRING},
    {"model2", FOFS(model2), F_STRING},
    {"spawnflags", FOFS(spawnflags), F_INT},
    {"speed", FOFS(speed), F_FLOAT},
    {"target", FOFS(target), F_STRING},
    {"targetname", FOFS(targetname), F_STRING},
    {"message", FOFS(message), F_STRING},
    {"team", FOFS(team), F_STRING},
    {"wait", FOFS(wait), F_FLOAT},
    {"random", FOFS(random), F_FLOAT},
    {"count", FOFS(count), F_INT},
    {"powerLevelTotal", FOFS(powerLevelTotal), F_INT},
    {"dmg", FOFS(damage), F_INT},
    {"angles", FOFS(s.angles), F_VECTOR},
    {"angle", FOFS(s.angles), F_ANGLEHACK},
    {"targetShaderName", FOFS(targetShaderName), F_STRING},
    {"targetShaderNewName", FOFS(targetShaderNewName), F_STRING},
    {NULL}
}
Definition at line 92 of file g_spawn.c.
Referenced by G_ParseField().
spawns
spawn_t spawns[]
Definition at line 166 of file g_spawn.c.
Referenced by G_CallSpawn().