ZEQ2-Lite: Tools/zMesh Exporter/scriplib.c File Reference
scriplib.c File Reference
#include "cmdlib.h"
#include "scriplib.h"
Data Structures
struct script_t
Macros
#define MAX_INCLUDES 8
Functions
void AddScriptToStack (const char *filename)
qboolean EndOfScript (qboolean crossline)
qboolean GetToken (qboolean crossline)
void LoadScriptFile (const char *filename)
void MatchToken (char *match)
void Parse1DMatrix (int x, vec_t *m)
void Parse2DMatrix (int y, int x, vec_t *m)
void Parse3DMatrix (int z, int y, int x, vec_t *m)
void ParseInt (int *in)
qboolean TokenAvailable (void)
void UnGetToken (void)
Variables
qboolean endofscript
script_t * script
int scriptline
script_t scriptstack [MAX_INCLUDES]
char token [MAXTOKEN]
qboolean tokenready
Macro Definition Documentation
MAX_INCLUDES
#define MAX_INCLUDES 8
Definition at line 41 of file scriplib.c.
Function Documentation
AddScriptToStack()
void AddScriptToStack (const char * filename)
Definition at line 55 of file scriplib.c.
{
     int            size;
     script++;
     if (script == &scriptstack[MAX_INCLUDES])
         Error ("Exceeded max of %i scripts loaded.",MAX_INCLUDES);
     strcpy (script->filename, filename);
     size = LoadFile (script->filename, (void **)&script->buffer);
     script->line = 1;
     script->script_p = script->buffer;
     script->end_p = script->buffer + size;
 }
References script_t::buffer, script_t::end_p, Error, script_t::filename, script_t::line, LoadFile(), MAX_INCLUDES, script, script_t::script_p, scriptstack, and strcpy().
Referenced by LoadScriptFile().
EndOfScript()
qboolean EndOfScript (qboolean crossline)
Definition at line 105 of file scriplib.c.
{
     if (!crossline)
         Error ("Line %i is incomplete\n",scriptline);
     if (!strcmp (script->filename, "memory buffer")) {
         endofscript = qtrue;
         return qfalse;
     }
     free (script->buffer);
     if (script == scriptstack+1) {
         endofscript = qtrue;
         return qfalse;
     }
     script--;
     scriptline = script->line;
     printf ("returning to %s\n", script->filename);
     return GetToken (crossline);
 }
References script_t::buffer, endofscript, Error, script_t::filename, free(), GetToken(), script_t::line, printf(), qfalse, qtrue, script, scriptline, scriptstack, and strcmp().
Referenced by GetToken().
GetToken()
qboolean GetToken (qboolean crossline)
Definition at line 130 of file scriplib.c.
{
     char    *token_p;
     if (tokenready) {
         // is a token already waiting?
         tokenready = qfalse;
         return qtrue;
     }
     if (script->script_p >= script->end_p)
         return EndOfScript (crossline);
 //
 // skip space
 //
 skipspace:
     while (*script->script_p <= 32) {
         if (script->script_p >= script->end_p)
             return EndOfScript (crossline);
         if (*script->script_p++ == '\n') {
             if (!crossline)
                 Error ("Line %i is incomplete\n",scriptline);
             scriptline = script->line++;
         }
     }
     if (script->script_p >= script->end_p)
         return EndOfScript (crossline);
     // ; # // comments
     if (*script->script_p == ';' || *script->script_p == '#'
         || ( script->script_p[0] == '/' && script->script_p[1] == '/') ) {
         if (!crossline)
             Error ("Line %i is incomplete\n",scriptline);
         while (*script->script_p++ != '\n')
             if (script->script_p >= script->end_p)
                 return EndOfScript (crossline);
         scriptline = script->line++;
         goto skipspace;
     }
     // /* */ comments
     if (script->script_p[0] == '/' && script->script_p[1] == '*') {
         if (!crossline)
             Error ("Line %i is incomplete\n",scriptline);
         script->script_p+=2;
         while (script->script_p[0] != '*' && script->script_p[1] != '/') {
             if ( *script->script_p == '\n' ) {
                 scriptline = script->line++;
             }
             script->script_p++;
             if (script->script_p >= script->end_p)
                 return EndOfScript (crossline);
         }
         script->script_p += 2;
         goto skipspace;
     }
 //
 // copy token
 //
     token_p = token;
     if (*script->script_p == '"') {
         // quoted token
         script->script_p++;
         while (*script->script_p != '"') {
             *token_p++ = *script->script_p++;
             if (script->script_p == script->end_p)
                 break;
             if (token_p == &token[MAXTOKEN])
                 Error ("Token too large on line %i\n",scriptline);
         }
         script->script_p++;
     } else {
         // regular token
         while ( *script->script_p > 32 && *script->script_p != ';') {
             *token_p++ = *script->script_p++;
             if (script->script_p == script->end_p)
                 break;
             if (token_p == &token[MAXTOKEN])
                 Error ("Token too large on line %i\n",scriptline);
         }
     }
     *token_p = 0;
     return qtrue;
 }
References script_t::end_p, EndOfScript(), Error, script_t::line, MAXTOKEN, qfalse, qtrue, script, script_t::script_p, scriptline, token, and tokenready.
Referenced by EndOfScript(), LoadCFG(), LoadCFG_Anim(), LoadCFG_General(), LoadCFG_Mesh(), LoadCFG_Skeleton(), LoadSMD(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), LoadSMD_ParseTriangles(), MatchToken(), Parse1DMatrix(), ParseInt(), and TokenAvailable().
LoadScriptFile()
void LoadScriptFile (const char * filename)
Definition at line 77 of file scriplib.c.
{
     script = scriptstack;
     AddScriptToStack (filename);
     endofscript = qfalse;
     tokenready = qfalse;
 }
References AddScriptToStack(), endofscript, qfalse, script, scriptstack, and tokenready.
Referenced by LoadCFG(), and LoadSMD().
MatchToken()
void MatchToken (char * match)
Definition at line 248 of file scriplib.c.
{
     GetToken( qtrue );
     if ( strcmp( token, match ) ) {
         Error( "MatchToken( \"%s\" ) failed at line %i", match, scriptline );
     }
 }
References Error, GetToken(), qtrue, scriptline, and strcmp().
Referenced by LoadSMD(), Parse2DMatrix(), and Parse3DMatrix().
Parse1DMatrix()
void Parse1DMatrix (int x, vec_t * m)
Definition at line 261 of file scriplib.c.
{
     int     i;
     for (i = 0 ; i < x ; i++) {
         GetToken( qfalse );
         m[i] = atof(token);
     }
 }
References atof(), GetToken(), m, and qfalse.
Referenced by Parse2DMatrix().
Parse2DMatrix()
void Parse2DMatrix (int y, int x, vec_t * m)
Definition at line 270 of file scriplib.c.
{
     int     i;
     MatchToken( "(" );
     for (i = 0 ; i < y ; i++) {
         Parse1DMatrix (x, m + i * x);
     }
     MatchToken( ")" );
 }
References m, MatchToken(), and Parse1DMatrix().
Referenced by Parse3DMatrix().
Parse3DMatrix()
void Parse3DMatrix (int z, int y, int x, vec_t * m)
Definition at line 282 of file scriplib.c.
{
     int     i;
     MatchToken( "(" );
     for (i = 0 ; i < z ; i++) {
         Parse2DMatrix (y, x, m + i * x*y);
     }
     MatchToken( ")" );
 }
References m, MatchToken(), and Parse2DMatrix().
ParseInt()
void ParseInt (int * in)
Definition at line 256 of file scriplib.c.
{
     GetToken( qfalse );
     *in = atoi(token);
 }
References atoi(), GetToken(), and qfalse.
Referenced by LoadSMD(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), and LoadSMD_ParseTriangles().
TokenAvailable()
qboolean TokenAvailable (void)
Definition at line 228 of file scriplib.c.
{
     int     oldLine;
     qboolean    r;
     oldLine = script->line;
     r = GetToken( qtrue );
     if ( !r ) {
         return qfalse;
     }
     UnGetToken();
     if ( oldLine == script->line ) {
         return qtrue;
     }
     return qfalse;
 }
References GetToken(), script_t::line, qfalse, qtrue, script, and UnGetToken().
UnGetToken()
void UnGetToken (void)
Definition at line 100 of file scriplib.c.
{
     tokenready = qtrue;
 }
References qtrue, and tokenready.
Referenced by TokenAvailable().
Variable Documentation
endofscript
qboolean endofscript
Definition at line 47 of file scriplib.c.
Referenced by EndOfScript(), and LoadScriptFile().
script
script_t* script
Definition at line 43 of file scriplib.c.
Referenced by AddScriptToStack(), EndOfScript(), GetToken(), LoadScriptFile(), and TokenAvailable().
scriptline
int scriptline
Definition at line 44 of file scriplib.c.
Referenced by EndOfScript(), GetToken(), and MatchToken().
scriptstack
script_t scriptstack[MAX_INCLUDES]
Definition at line 42 of file scriplib.c.
Referenced by AddScriptToStack(), EndOfScript(), and LoadScriptFile().
token
char token[MAXTOKEN]
Definition at line 46 of file scriplib.c.
Referenced by GetToken().
tokenready
qboolean tokenready
Definition at line 48 of file scriplib.c.
Referenced by GetToken(), LoadScriptFile(), and UnGetToken().