ZEQ2-Lite: Source/Game/CGame/cg_predict.c File Reference
cg_predict.c File Reference
#include "cg_local.h"
Functions
void CG_BuildSolidList (void)
static void CG_ClipMoveToEntities (const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask, trace_t *tr)
static void CG_InterpolatePlayerState (qboolean grabAngles)
int CG_PointContents (const vec3_t point, int passEntityNum)
void CG_PredictPlayerState (void)
void CG_SmoothTrace (trace_t *result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
static void CG_TouchItem (centity_t *cent)
static void CG_TouchTriggerPrediction (void)
void CG_Trace (trace_t *result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
Variables
static int cg_numSolidEntities
static int cg_numTriggerEntities
static pmove_t cg_pmove
static centity_t * cg_solidEntities [MAX_ENTITIES_IN_SNAPSHOT]
static centity_t * cg_triggerEntities [MAX_ENTITIES_IN_SNAPSHOT]
Function Documentation
CG_BuildSolidList()
void CG_BuildSolidList (void)
Definition at line 46 of file cg_predict.c.
{
     int         i;
     centity_t   *cent;
     snapshot_t  *snap;
     entityState_t   *ent;
     cg_numSolidEntities = 0;
     cg_numTriggerEntities = 0;
     if ( cg.nextSnap && !cg.nextFrameTeleport && !cg.thisFrameTeleport ) {
         snap = cg.nextSnap;
     } else {
         snap = cg.snap;
     }
     for ( i = 0 ; i < snap->numEntities ; i++ ) {
         cent = &cg_entities[ snap->entities[ i ].number ];
         ent = &cent->currentState;
         if ( ent->eType == ET_ITEM || ent->eType == ET_PUSH_TRIGGER || ent->eType == ET_TELEPORT_TRIGGER ) {
             cg_triggerEntities[cg_numTriggerEntities] = cent;
             cg_numTriggerEntities++;
             continue;
         }
         if ( cent->nextState.solid ) {
             cg_solidEntities[cg_numSolidEntities] = cent;
             cg_numSolidEntities++;
             continue;
         }
     }
 }
References cg, cg_entities, cg_numSolidEntities, cg_numTriggerEntities, cg_solidEntities, cg_triggerEntities, snapshot_t::entities, ET_ITEM, ET_PUSH_TRIGGER, ET_TELEPORT_TRIGGER, cg_t::nextFrameTeleport, cg_t::nextSnap, snapshot_t::numEntities, cg_t::snap, and cg_t::thisFrameTeleport.
Referenced by CG_SetInitialSnapshot(), and CG_SetNextSnap().
CG_ClipMoveToEntities()
static void CG_ClipMoveToEntities (const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask, trace_t * tr) static
Definition at line 85 of file cg_predict.c.
{
     int         i, x, zd, zu;
     trace_t     trace;
     entityState_t   *ent;
     clipHandle_t    cmodel;
     vec3_t      bmins, bmaxs;
     vec3_t      origin, angles;
     centity_t   *cent;
     for ( i = 0 ; i < cg_numSolidEntities ; i++ ) {
         cent = cg_solidEntities[ i ];
         ent = &cent->currentState;
         if ( ent->number == skipNumber ) {
             continue;
         }
         if ( ent->solid == SOLID_BMODEL ) {
             // special value for bmodel
             cmodel = trap_CM_InlineModel( ent->modelindex );
             VectorCopy( cent->lerpAngles, angles );
             BG_EvaluateTrajectory( &cent->currentState, &cent->currentState.pos, cg.physicsTime, origin );
         } else {
             // encoded bbox
             x = (ent->solid & 255);
             zd = ((ent->solid>>8) & 255);
             zu = ((ent->solid>>16) & 255) - 32;
             bmins[0] = bmins[1] = -x;
             bmaxs[0] = bmaxs[1] = x;
             bmins[2] = -zd;
             bmaxs[2] = zu;
             cmodel = trap_CM_TempBoxModel( bmins, bmaxs );
             VectorCopy( vec3_origin, angles );
             VectorCopy( cent->lerpOrigin, origin );
         }
         trap_CM_TransformedBoxTrace ( &trace, start, end,
             mins, maxs, cmodel,  mask, origin, angles);
         if (trace.allsolid || trace.fraction < tr->fraction) {
             trace.entityNum = ent->number;
             *tr = trace;
         } else if (trace.startsolid) {
             tr->startsolid = qtrue;
         }
         if ( tr->allsolid ) {
             return;
         }
     }
 }
References trace_t::allsolid, angles, BG_EvaluateTrajectory(), cg, cg_numSolidEntities, cg_solidEntities, trace_t::entityNum, trace_t::fraction, cg_t::physicsTime, qtrue, SOLID_BMODEL, trace_t::startsolid, tr, trap_CM_InlineModel(), trap_CM_TempBoxModel(), trap_CM_TransformedBoxTrace(), vec3_origin, and VectorCopy.
Referenced by CG_Trace().
CG_InterpolatePlayerState()
static void CG_InterpolatePlayerState (qboolean grabAngles) static
Definition at line 222 of file cg_predict.c.
{
     float           f;
     int             i;
     playerState_t   *out;
     snapshot_t      *prev, *next;
     out = &cg.predictedPlayerState;
     prev = cg.snap;
     next = cg.nextSnap;
     *out = cg.snap->ps;
     // if we are still allowing local input, short circuit the view angles
     if(grabAngles){
         usercmd_t   cmd;
         int cmdNum;
         cmdNum = trap_GetCurrentCmdNumber();
         trap_GetUserCmd(cmdNum,&cmd);
         PM_UpdateViewAngles(out,&cmd);
     }
     if(cg.nextFrameTeleport){return;}
     if(!next || next->serverTime <= prev->serverTime){return;}
     f = (float)( cg.time - prev->serverTime ) / ( next->serverTime - prev->serverTime );
     i = next->ps.bobCycle;
     if(i<prev->ps.bobCycle){i += 256;}
     out->bobCycle = prev->ps.bobCycle + f * ( i - prev->ps.bobCycle );
     for(i=0;i<3;i++){
         out->origin[i] = prev->ps.origin[i] + f * (next->ps.origin[i] - prev->ps.origin[i]);
         if(!grabAngles){
             out->viewangles[i] = LerpAngle(prev->ps.viewangles[i],next->ps.viewangles[i],f);
         }
         out->velocity[i] = prev->ps.velocity[i] + f * (next->ps.velocity[i] - prev->ps.velocity[i]);
     }
 }
References cg, LerpAngle(), cg_t::nextFrameTeleport, cg_t::nextSnap, out, PM_UpdateViewAngles(), cg_t::predictedPlayerState, snapshot_t::ps, snapshot_t::serverTime, cg_t::snap, cg_t::time, trap_GetCurrentCmdNumber(), and trap_GetUserCmd().
Referenced by CG_PredictPlayerState().
CG_PointContents()
int CG_PointContents (const vec3_t point, int passEntityNum)
Definition at line 180 of file cg_predict.c.
{
     int         i;
     entityState_t   *ent;
     centity_t   *cent;
     clipHandle_t cmodel;
     int         contents;
     contents = trap_CM_PointContents (point, 0);
     for ( i = 0 ; i < cg_numSolidEntities ; i++ ) {
         cent = cg_solidEntities[ i ];
         ent = &cent->currentState;
         if ( ent->number == passEntityNum ) {
             continue;
         }
         if (ent->solid != SOLID_BMODEL) { // special value for bmodel
             continue;
         }
         cmodel = trap_CM_InlineModel( ent->modelindex );
         if ( !cmodel ) {
             continue;
         }
         contents |= trap_CM_TransformedPointContents( point, cmodel, cent->lerpOrigin, cent->lerpAngles );
     }
     return contents;
 }
References cg_numSolidEntities, cg_solidEntities, SOLID_BMODEL, trap_CM_InlineModel(), trap_CM_PointContents(), and trap_CM_TransformedPointContents().
Referenced by CG_AddFragment(), CG_CalcFov(), CG_DrawActive(), CG_PlayerSplash(), and CG_PredictPlayerState().
CG_PredictPlayerState()
void CG_PredictPlayerState (void)
Definition at line 357 of file cg_predict.c.
{
     int         cmdNum, current;
     playerState_t   oldPlayerState;
     qboolean    moved;
     usercmd_t   oldestCmd;
     usercmd_t   latestCmd;
     cg.hyperspace = qfalse;
     if(!cg.validPPS){
         cg.validPPS = qtrue;
         cg.predictedPlayerState = cg.snap->ps;
     }
     if(cg.demoPlayback || (cg.snap->ps.pm_flags & PMF_FOLLOW) || cg.snap->ps.lockedTarget > 0) {
         CG_InterpolatePlayerState(qfalse);
         return;
     }
     cg_pmove.ps = &cg.predictedPlayerState;
     cg_pmove.trace = CG_Trace;
     cg_pmove.pointcontents = CG_PointContents;
     cg_pmove.tracemask = MASK_PLAYERSOLID;
     if(cg.snap->ps.persistant[PERS_TEAM] == TEAM_SPECTATOR ) {
         cg_pmove.tracemask &= ~CONTENTS_BODY;
     }
     cg_pmove.noFootsteps = ( cgs.dmflags & DF_NO_FOOTSTEPS ) > 0;
     oldPlayerState = cg.predictedPlayerState;
     current = trap_GetCurrentCmdNumber();
     // if we don't have the commands right after the snapshot, we
     // can't accurately predict a current position, so just freeze at
     // the last good position we had
     cmdNum = current - CMD_BACKUP + 1;
     trap_GetUserCmd( cmdNum, &oldestCmd );
     if (oldestCmd.serverTime > cg.snap->ps.commandTime && oldestCmd.serverTime < cg.time){
         if(cg_showmiss.integer){
             CG_Printf ("exceeded PACKET_BACKUP on commands\n");
         }
         return;
     }
     // get the latest command so we can know which commands are from previous map_restarts
     trap_GetUserCmd( current, &latestCmd );
     // get the most recent information we have, even if
     // the server time is beyond our current cg.time,
     // because predicted player positions are going to
     // be ahead of everything else anyway
     if ( cg.nextSnap && !cg.nextFrameTeleport && !cg.thisFrameTeleport ) {
         cg.predictedPlayerState = cg.nextSnap->ps;
         cg.physicsTime = cg.nextSnap->serverTime;
     } else {
         cg.predictedPlayerState = cg.snap->ps;
         cg.physicsTime = cg.snap->serverTime;
     }
     if ( pmove_msec.integer < 8 ) {
         trap_Cvar_Set("pmove_msec", "8");
     }
     else if (pmove_msec.integer > 33) {
         trap_Cvar_Set("pmove_msec", "33");
     }
     cg_pmove.pmove_fixed = pmove_fixed.integer;// | cg_pmove_fixed.integer;
     cg_pmove.pmove_msec = pmove_msec.integer;
     // run cmds
     moved = qfalse;
     for ( cmdNum = current - CMD_BACKUP + 1 ; cmdNum <= current ; cmdNum++ ) {
         // get the command
         trap_GetUserCmd( cmdNum, &cg_pmove.cmd );
         if ( cg_pmove.pmove_fixed ) {
             PM_UpdateViewAngles( cg_pmove.ps, &cg_pmove.cmd );
         }
         // don't do anything if the time is before the snapshot player time
         if ( cg_pmove.cmd.serverTime <= cg.predictedPlayerState.commandTime ) {
             continue;
         }
         // don't do anything if the command was from a previous map_restart
         if ( cg_pmove.cmd.serverTime > latestCmd.serverTime ) {
             continue;
         }
         // check for a prediction error from last frame
         // on a lan, this will often be the exact value
         // from the snapshot, but on a wan we will have
         // to predict several commands to get to the point
         // we want to compare
         if ( cg.predictedPlayerState.commandTime == oldPlayerState.commandTime ) {
             vec3_t  delta;
             float   len;
             if ( cg.thisFrameTeleport ) {
                 // a teleport will not cause an error decay
                 VectorClear( cg.predictedError );
                 if ( cg_showmiss.integer ) {
                     CG_Printf( "PredictionTeleport\n" );
                 }
                 cg.thisFrameTeleport = qfalse;
             } else {
                 vec3_t  adjusted;
                 CG_AdjustPositionForMover( cg.predictedPlayerState.origin,
                     cg.predictedPlayerState.groundEntityNum, cg.physicsTime, cg.oldTime, adjusted );
                 if ( cg_showmiss.integer ) {
                     if (!VectorCompare( oldPlayerState.origin, adjusted )) {
                         CG_Printf("prediction error\n");
                     }
                 }
                 VectorSubtract( oldPlayerState.origin, adjusted, delta );
                 len = VectorLength( delta );
                 if ( len > 0.1 ) {
                     if ( cg_showmiss.integer ) {
                         CG_Printf("Prediction miss: %f\n", len);
                     }
                     if ( cg_errorDecay.integer ) {
                         int     t;
                         float   f;
                         t = cg.time - cg.predictedErrorTime;
                         f = ( cg_errorDecay.value - t ) / cg_errorDecay.value;
                         if ( f < 0 ) {
                             f = 0;
                         }
                         if ( f > 0 && cg_showmiss.integer ) {
                             CG_Printf("Double prediction decay: %f\n", f);
                         }
                         VectorScale( cg.predictedError, f, cg.predictedError );
                     } else {
                         VectorClear( cg.predictedError );
                     }
                     VectorAdd( delta, cg.predictedError, cg.predictedError );
                     cg.predictedErrorTime = cg.oldTime;
                 }
             }
         }
         // don't predict gauntlet firing, which is only supposed to happen
         // when it actually inflicts damage
         cg_pmove.gauntletHit = qfalse;
         if ( cg_pmove.pmove_fixed ) {
             cg_pmove.cmd.serverTime = ((cg_pmove.cmd.serverTime + pmove_msec.integer-1) / pmove_msec.integer) * pmove_msec.integer;
         }
         Pmove (&cg_pmove);
         moved = qtrue;
         // add push trigger movement effects
         CG_TouchTriggerPrediction();
         // check for predictable events that changed from previous predictions
         //CG_CheckChangedPredictableEvents(&cg.predictedPlayerState);
     }
     if ( cg_showmiss.integer > 1 ) {
         CG_Printf( "[%i : %i] ", cg_pmove.cmd.serverTime, cg.time );
     }
     if ( !moved ) {
         if ( cg_showmiss.integer ) {
             CG_Printf( "not moved\n" );
         }
         return;
     }
     // adjust for the movement of the groundentity
     CG_AdjustPositionForMover(cg.predictedPlayerState.origin,cg.predictedPlayerState.groundEntityNum,cg.physicsTime, cg.time, cg.predictedPlayerState.origin);
     if(cg_showmiss.integer){
         if(cg.predictedPlayerState.eventSequence > oldPlayerState.eventSequence + MAX_PS_EVENTS){
             CG_Printf("WARNING: dropped event\n");
         }
     }
     // fire events and other transition triggered things
     CG_TransitionPlayerState(&cg.predictedPlayerState,&oldPlayerState);
     if ( cg_showmiss.integer ) {
         if (cg.eventSequence > cg.predictedPlayerState.eventSequence) {
             CG_Printf("WARNING: double event\n");
             cg.eventSequence = cg.predictedPlayerState.eventSequence;
         }
     }
     if(cg.snap->ps.lockedTarget > 0){
         CG_InterpolatePlayerState(qfalse);
         return;
     }
 }
References cg, CG_AdjustPositionForMover(), cg_errorDecay, CG_InterpolatePlayerState(), cg_pmove, CG_PointContents(), CG_Printf(), cg_showmiss, CG_TouchTriggerPrediction(), CG_Trace(), CG_TransitionPlayerState(), cgs, pmove_t::cmd, CMD_BACKUP, CONTENTS_BODY, current, cg_t::demoPlayback, DF_NO_FOOTSTEPS, cgs_t::dmflags, cg_t::eventSequence, pmove_t::gauntletHit, cg_t::hyperspace, vmCvar_t::integer, MASK_PLAYERSOLID, MAX_PS_EVENTS, cg_t::nextFrameTeleport, cg_t::nextSnap, pmove_t::noFootsteps, cg_t::oldTime, PERS_TEAM, cg_t::physicsTime, PM_UpdateViewAngles(), PMF_FOLLOW, Pmove(), pmove_t::pmove_fixed, pmove_fixed, pmove_t::pmove_msec, pmove_msec, pmove_t::pointcontents, cg_t::predictedError, cg_t::predictedErrorTime, cg_t::predictedPlayerState, snapshot_t::ps, pmove_t::ps, qfalse, qtrue, snapshot_t::serverTime, cg_t::snap, TEAM_SPECTATOR, cg_t::thisFrameTeleport, cg_t::time, pmove_t::trace, pmove_t::tracemask, trap_Cvar_Set(), trap_GetCurrentCmdNumber(), trap_GetUserCmd(), cg_t::validPPS, vmCvar_t::value, VectorAdd, VectorClear, VectorCompare(), VectorLength(), VectorScale, and VectorSubtract.
Referenced by CG_DrawActiveFrame().
CG_SmoothTrace()
void CG_SmoothTrace (trace_t * result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
Definition at line 162 of file cg_predict.c.
   {
     int physicsTime;
     physicsTime = cg.physicsTime;
     cg.physicsTime = cg.time;
     CG_Trace(result, start, mins, maxs, end, skipNumber, mask);
     cg.physicsTime = cg.time;
 }
References cg, CG_Trace(), cg_t::physicsTime, and cg_t::time.
CG_TouchItem()
static void CG_TouchItem (centity_t * cent) static
Definition at line 259 of file cg_predict.c.
{
     return;
 }
Referenced by CG_TouchTriggerPrediction().
CG_TouchTriggerPrediction()
static void CG_TouchTriggerPrediction (void) static
Definition at line 271 of file cg_predict.c.
{
     int         i;
     trace_t     trace;
     entityState_t   *ent;
     clipHandle_t cmodel;
     centity_t   *cent;
     qboolean    spectator;
     // dead clients don't activate triggers
     if ( cg.predictedPlayerState.powerLevel[plFatigue] <= 0 ) {
         return;
     }
     spectator = ( cg.predictedPlayerState.pm_type == PM_SPECTATOR );
     if ( cg.predictedPlayerState.pm_type != PM_NORMAL && !spectator ) {
         return;
     }
     for ( i = 0 ; i < cg_numTriggerEntities ; i++ ) {
         cent = cg_triggerEntities[ i ];
         ent = &cent->currentState;
         if ( ent->eType == ET_ITEM && !spectator ) {
             CG_TouchItem( cent );
             continue;
         }
         if ( ent->solid != SOLID_BMODEL ) {
             continue;
         }
         cmodel = trap_CM_InlineModel( ent->modelindex );
         if ( !cmodel ) {
             continue;
         }
         trap_CM_BoxTrace( &trace, cg.predictedPlayerState.origin, cg.predictedPlayerState.origin,
             cg_pmove.mins, cg_pmove.maxs, cmodel, -1 );
         if ( !trace.startsolid ) {
             continue;
         }
         if ( ent->eType == ET_TELEPORT_TRIGGER ) {
             cg.hyperspace = qtrue;
         } else if ( ent->eType == ET_PUSH_TRIGGER ) {
             BG_TouchJumpPad( &cg.predictedPlayerState, ent );
         }
     }
     // if we didn't touch a jump pad this pmove frame
     if ( cg.predictedPlayerState.jumppad_frame != cg.predictedPlayerState.pmove_framecount ) {
         cg.predictedPlayerState.jumppad_frame = 0;
         cg.predictedPlayerState.jumppad_ent = 0;
     }
 }
References BG_TouchJumpPad(), cg, cg_numTriggerEntities, cg_pmove, CG_TouchItem(), cg_triggerEntities, ET_ITEM, ET_PUSH_TRIGGER, ET_TELEPORT_TRIGGER, cg_t::hyperspace, pmove_t::maxs, pmove_t::mins, plFatigue, PM_NORMAL, PM_SPECTATOR, cg_t::predictedPlayerState, qtrue, SOLID_BMODEL, trace_t::startsolid, trap_CM_BoxTrace(), and trap_CM_InlineModel().
Referenced by CG_PredictPlayerState().
CG_Trace()
void CG_Trace (trace_t * result, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int skipNumber, int mask)
Definition at line 145 of file cg_predict.c.
{
     trace_t t;
     trap_CM_BoxTrace ( &t, start, end, mins, maxs, 0, mask);
     t.entityNum = t.fraction != 1.0 ? ENTITYNUM_WORLD : ENTITYNUM_NONE;
     // check all other solid models
     CG_ClipMoveToEntities (start, mins, maxs, end, skipNumber, mask, &t);
     *result = t;
 }
References CG_ClipMoveToEntities(), ENTITYNUM_NONE, ENTITYNUM_WORLD, and trap_CM_BoxTrace().
Referenced by CG_AddFragment(), CG_AuraStart(), CG_Camera(), CG_DrawCrosshair(), CG_PlayerDirtPush(), CG_PredictPlayerState(), CG_ScanForCrosshairEntity(), CG_SmoothTrace(), CG_UserMissileHitWall(), PSys_ApplyPlaneConstraint(), and PSys_UpdateEmitters().
Variable Documentation
cg_numSolidEntities
int cg_numSolidEntities static
Definition at line 32 of file cg_predict.c.
Referenced by CG_BuildSolidList(), CG_ClipMoveToEntities(), and CG_PointContents().
cg_numTriggerEntities
int cg_numTriggerEntities static
Definition at line 34 of file cg_predict.c.
Referenced by CG_BuildSolidList(), and CG_TouchTriggerPrediction().
cg_pmove
pmove_t cg_pmove static
Definition at line 30 of file cg_predict.c.
Referenced by CG_PredictPlayerState(), and CG_TouchTriggerPrediction().
cg_solidEntities
centity_t* cg_solidEntities[MAX_ENTITIES_IN_SNAPSHOT] static
Definition at line 33 of file cg_predict.c.
Referenced by CG_BuildSolidList(), CG_ClipMoveToEntities(), and CG_PointContents().
cg_triggerEntities
centity_t* cg_triggerEntities[MAX_ENTITIES_IN_SNAPSHOT] static
Definition at line 35 of file cg_predict.c.
Referenced by CG_BuildSolidList(), and CG_TouchTriggerPrediction().