ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/bits/stl_set.h File Reference
stl_set.h File Reference
#include <bits/concept_check.h>
#include <initializer_list>
Functions
namespace std _GLIBCXX_VISIBILITY (default)
Detailed Description
This is an internal header file, included by other library headers. Do not attempt to use it directly. @headername{set}
Definition in file stl_set.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace std _GLIBCXX_VISIBILITY (default)
A standard container made up of unique keys, which can be retrieved in logarithmic time.
Meets the requirements of a container, a reversible container, and an associative container (using unique keys).
Sets support bidirectional iterators.
Parameters
Key Type of key objects.
Compare Comparison function object type, defaults to less<Key>.
Alloc Allocator type, defaults to allocator<Key>.
The private tree data is declared exactly the same way for set and multiset; the distinction is made entirely in how the tree functions are called (*_unique versus *_equal, same as the standard).
Public typedefs.
Iterator-related typedefs.
Default constructor creates no elements.
Creates a set with no elements.
Parameters
comp Comparator to use.
a An allocator object.
Builds a set from a range.
Parameters
first An input iterator.
last An input iterator.
Create a set consisting of copies of the elements from [first,last). This is linear in N if the range is already sorted, and NlogN otherwise (where N is distance(first,last)).
Builds a set from a range.
Parameters
first An input iterator.
last An input iterator.
comp A comparison functor.
a An allocator object.
Create a set consisting of copies of the elements from [first,last). This is linear in N if the range is already sorted, and NlogN otherwise (where N is distance(first,last)).
Set copy constructor.
Parameters
x A set of identical element and allocator types.
The newly-created set uses a copy of the allocation object used by x.
Set assignment operator.
Parameters
x A set of identical element and allocator types.
All the elements of x are copied, but unlike the copy constructor, the allocator object is not copied.
Returns the comparison object with which the set was constructed.
Returns the comparison object with which the set was constructed.
Returns the allocator object with which the set was constructed.
Returns a read-only (constant) iterator that points to the first element in the set. Iteration is done in ascending order according to the keys.
Returns a read-only (constant) iterator that points one past the last element in the set. Iteration is done in ascending order according to the keys.
Returns a read-only (constant) iterator that points to the last element in the set. Iteration is done in descending order according to the keys.
Returns a read-only (constant) reverse iterator that points to the last pair in the set. Iteration is done in descending order according to the keys.
Returns true if the set is empty.
Returns the size of the set.
Returns the maximum size of the set.
Swaps data with another set.
Parameters
x A set of the same element and allocator types.
This exchanges the elements between two sets in constant time. (It is only swapping a pointer, an integer, and an instance of the Compare type (which itself is often stateless and empty), so it should be quite fast.) Note that the global std::swap() function is specialized such that std::swap(s1,s2) will feed to this function.
Attempts to insert an element into the set.
Parameters
x Element to be inserted.
Returns
A pair, of which the first element is an iterator that points to the possibly inserted element, and the second is a bool that is true if the element was actually inserted.
This function attempts to insert an element into the set. A set relies on unique keys and thus an element is only inserted if it is not already present in the set.
Insertion requires logarithmic time.
Attempts to insert an element into the set.
Parameters
position An iterator that serves as a hint as to where the element should be inserted.
x Element to be inserted.
Returns
An iterator that points to the element with key of x (may or may not be the element passed in).
This function is not concerned about whether the insertion took place, and thus does not return a boolean like the single-argument insert() does. Note that the first parameter is only a hint and can potentially improve the performance of the insertion process. A bad hint would cause no gains in efficiency.
For more on hinting, see: http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt07ch17.html
Insertion requires logarithmic time (if the hint is not taken).
A template function that attempts to insert a range of elements.
Parameters
first Iterator pointing to the start of the range to be inserted.
last Iterator pointing to the end of the range.
Complexity similar to that of the range constructor.
Erases an element from a set.
Parameters
position An iterator pointing to the element to be erased.
This function erases an element, pointed to by the given iterator, from a set. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Erases elements according to the provided key.
Parameters
x Key of element to be erased.
Returns
The number of elements erased.
This function erases all the elements located by the given key from a set. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Erases a [first,last) range of elements from a set.
Parameters
first Iterator pointing to the start of the range to be erased.
last Iterator pointing to the end of the range to be erased.
This function erases a sequence of elements from a set. Note that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Erases all elements in a set. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Finds the number of elements.
Parameters
x Element to located.
Returns
Number of elements with specified key.
This function only makes sense for multisets; for set the result will either be 0 (not present) or 1 (present).
Tries to locate an element in a set.
Parameters
x Element to be located.
Returns
Iterator pointing to sought-after element, or end() if not found.
This function takes a key and tries to locate the element with which the key matches. If successful the function returns an iterator pointing to the sought after element. If unsuccessful it returns the past-the-end (end()) iterator.
Finds the beginning of a subsequence matching given key.
Parameters
x Key to be located.
Returns
Iterator pointing to first element equal to or greater than key, or end().
This function returns the first element of a subsequence of elements that matches the given key. If unsuccessful it returns an iterator pointing to the first element that has a greater value than given key or end() if no such element exists.
Finds the end of a subsequence matching given key.
Parameters
x Key to be located.
Returns
Iterator pointing to the first element greater than key, or end().
Finds a subsequence matching given key.
Parameters
x Key to be located.
Returns
Pair of iterators that possibly points to the subsequence matching given key.
This function is equivalent to
std::make_pair(c.lower_bound(val),
               c.upper_bound(val))
(but is faster than making the calls separately).
This function probably only makes sense for multisets.
Set equality comparison.
Parameters
x A set.
y A set of the same type as x.
Returns
True iff the size and elements of the sets are equal.
This is an equivalence relation. It is linear in the size of the sets. Sets are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Set ordering relation.
Parameters
x A set.
y A set of the same type as x.
Returns
True iff x is lexicographically less than y.
This is a total ordering relation. It is linear in the size of the maps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Returns !(x == y).
Returns y < x.
Returns !(y < x)
Returns !(x < y)
See std::set::swap().
Definition at line 63 of file stl_set.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_CONTAINER
   template<typename _Key, typename _Compare = std::less<_Key>,
        typename _Alloc = std::allocator<_Key> >
     class set
     {
       // concept requirements
       typedef typename _Alloc::value_type                   _Alloc_value_type;
       __glibcxx_class_requires(_Key, _SGIAssignableConcept)
       __glibcxx_class_requires4(_Compare, bool, _Key, _Key,
                 _BinaryFunctionConcept)
       __glibcxx_class_requires2(_Key, _Alloc_value_type, _SameTypeConcept)
     public:
       // typedefs:
       typedef _Key     key_type;
       typedef _Key     value_type;
       typedef _Compare key_compare;
       typedef _Compare value_compare;
       typedef _Alloc   allocator_type;
     private:
       typedef typename _Alloc::template rebind<_Key>::other _Key_alloc_type;
       typedef _Rb_tree<key_type, value_type, _Identity<value_type>,
                key_compare, _Key_alloc_type> _Rep_type;
       _Rep_type _M_t;  // Red-black tree representing set.
     public:
       typedef typename _Key_alloc_type::pointer             pointer;
       typedef typename _Key_alloc_type::const_pointer       const_pointer;
       typedef typename _Key_alloc_type::reference           reference;
       typedef typename _Key_alloc_type::const_reference     const_reference;
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // DR 103. set::iterator is required to be modifiable,
       // but this allows modification of keys.
       typedef typename _Rep_type::const_iterator            iterator;
       typedef typename _Rep_type::const_iterator            const_iterator;
       typedef typename _Rep_type::const_reverse_iterator    reverse_iterator;
       typedef typename _Rep_type::const_reverse_iterator const_reverse_iterator;
       typedef typename _Rep_type::size_type                 size_type;
       typedef typename _Rep_type::difference_type           difference_type;
       // allocation/deallocation
       set()
       : _M_t() { }
       explicit
       set(const _Compare& __comp,
       const allocator_type& __a = allocator_type())
       : _M_t(__comp, __a) { }
       template<typename _InputIterator>
     set(_InputIterator __first, _InputIterator __last)
     : _M_t()
     { _M_t._M_insert_unique(__first, __last); }
       template<typename _InputIterator>
     set(_InputIterator __first, _InputIterator __last,
         const _Compare& __comp,
         const allocator_type& __a = allocator_type())
     : _M_t(__comp, __a)
     { _M_t._M_insert_unique(__first, __last); }
       set(const set& __x)
       : _M_t(__x._M_t) { }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       set(set&& __x)
       : _M_t(std::move(__x._M_t)) { }
       set(initializer_list<value_type> __l,
       const _Compare& __comp = _Compare(),
       const allocator_type& __a = allocator_type())
       : _M_t(__comp, __a)
       { _M_t._M_insert_unique(__l.begin(), __l.end()); }
 #endif
       set&
       operator=(const set& __x)
       {
     _M_t = __x._M_t;
     return *this;
       }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       set&
       operator=(set&& __x)
       {
     // NB: DR 1204.
     // NB: DR 675.
     this->clear();
     this->swap(__x);
         return *this;
       }
       set&
       operator=(initializer_list<value_type> __l)
       {
     this->clear();
     this->insert(__l.begin(), __l.end());
     return *this;
       }
 #endif
       // accessors:
       key_compare
       key_comp() const
       { return _M_t.key_comp(); }
       value_compare
       value_comp() const
       { return _M_t.key_comp(); }
       allocator_type
       get_allocator() const
       { return _M_t.get_allocator(); }
       iterator
       begin() const
       { return _M_t.begin(); }
       iterator
       end() const
       { return _M_t.end(); }
       reverse_iterator
       rbegin() const
       { return _M_t.rbegin(); }
       reverse_iterator
       rend() const
       { return _M_t.rend(); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       iterator
       cbegin() const
       { return _M_t.begin(); }
       iterator
       cend() const
       { return _M_t.end(); }
       reverse_iterator
       crbegin() const
       { return _M_t.rbegin(); }
       reverse_iterator
       crend() const
       { return _M_t.rend(); }
 #endif
       bool
       empty() const
       { return _M_t.empty(); }
       size_type
       size() const
       { return _M_t.size(); }
       size_type
       max_size() const
       { return _M_t.max_size(); }
       void
       swap(set& __x)
       { _M_t.swap(__x._M_t); }
       // insert/erase
       std::pair<iterator, bool>
       insert(const value_type& __x)
       {
     std::pair<typename _Rep_type::iterator, bool> __p =
       _M_t._M_insert_unique(__x);
     return std::pair<iterator, bool>(__p.first, __p.second);
       }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       std::pair<iterator, bool>
       insert(value_type&& __x)
       {
     std::pair<typename _Rep_type::iterator, bool> __p =
       _M_t._M_insert_unique(std::move(__x));
     return std::pair<iterator, bool>(__p.first, __p.second);
       }
 #endif
       iterator
       insert(const_iterator __position, const value_type& __x)
       { return _M_t._M_insert_unique_(__position, __x); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       iterator
       insert(const_iterator __position, value_type&& __x)
       { return _M_t._M_insert_unique_(__position, std::move(__x)); }
 #endif
       template<typename _InputIterator>
     void
     insert(_InputIterator __first, _InputIterator __last)
     { _M_t._M_insert_unique(__first, __last); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       void
       insert(initializer_list<value_type> __l)
       { this->insert(__l.begin(), __l.end()); }
 #endif
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // DR 130. Associative erase should return an iterator.
       iterator
       erase(const_iterator __position)
       { return _M_t.erase(__position); }
 #else
       void
       erase(iterator __position)
       { _M_t.erase(__position); }
 #endif
       size_type
       erase(const key_type& __x)
       { return _M_t.erase(__x); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // DR 130. Associative erase should return an iterator.
       iterator
       erase(const_iterator __first, const_iterator __last)
       { return _M_t.erase(__first, __last); }
 #else
       void
       erase(iterator __first, iterator __last)
       { _M_t.erase(__first, __last); }
 #endif
       void
       clear()
       { _M_t.clear(); }
       // set operations:
       size_type
       count(const key_type& __x) const
       { return _M_t.find(__x) == _M_t.end() ? 0 : 1; }
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // 214.  set::find() missing const overload
       iterator
       find(const key_type& __x)
       { return _M_t.find(__x); }
       const_iterator
       find(const key_type& __x) const
       { return _M_t.find(__x); }
       iterator
       lower_bound(const key_type& __x)
       { return _M_t.lower_bound(__x); }
       const_iterator
       lower_bound(const key_type& __x) const
       { return _M_t.lower_bound(__x); }
       iterator
       upper_bound(const key_type& __x)
       { return _M_t.upper_bound(__x); }
       const_iterator
       upper_bound(const key_type& __x) const
       { return _M_t.upper_bound(__x); }
       std::pair<iterator, iterator>
       equal_range(const key_type& __x)
       { return _M_t.equal_range(__x); }
       std::pair<const_iterator, const_iterator>
       equal_range(const key_type& __x) const
       { return _M_t.equal_range(__x); }
       template<typename _K1, typename _C1, typename _A1>
     friend bool
     operator==(const set<_K1, _C1, _A1>&, const set<_K1, _C1, _A1>&);
       template<typename _K1, typename _C1, typename _A1>
     friend bool
     operator<(const set<_K1, _C1, _A1>&, const set<_K1, _C1, _A1>&);
     };
   template<typename _Key, typename _Compare, typename _Alloc>
     inline bool
     operator==(const set<_Key, _Compare, _Alloc>& __x,
            const set<_Key, _Compare, _Alloc>& __y)
     { return __x._M_t == __y._M_t; }
   template<typename _Key, typename _Compare, typename _Alloc>
     inline bool
     operator<(const set<_Key, _Compare, _Alloc>& __x,
           const set<_Key, _Compare, _Alloc>& __y)
     { return __x._M_t < __y._M_t; }
   template<typename _Key, typename _Compare, typename _Alloc>
     inline bool
     operator!=(const set<_Key, _Compare, _Alloc>& __x,
            const set<_Key, _Compare, _Alloc>& __y)
     { return !(__x == __y); }
   template<typename _Key, typename _Compare, typename _Alloc>
     inline bool
     operator>(const set<_Key, _Compare, _Alloc>& __x,
           const set<_Key, _Compare, _Alloc>& __y)
     { return __y < __x; }
   template<typename _Key, typename _Compare, typename _Alloc>
     inline bool
     operator<=(const set<_Key, _Compare, _Alloc>& __x,
            const set<_Key, _Compare, _Alloc>& __y)
     { return !(__y < __x); }
   template<typename _Key, typename _Compare, typename _Alloc>
     inline bool
     operator>=(const set<_Key, _Compare, _Alloc>& __x,
            const set<_Key, _Compare, _Alloc>& __y)
     { return !(__x < __y); }
   template<typename _Key, typename _Compare, typename _Alloc>
     inline void
     swap(set<_Key, _Compare, _Alloc>& __x, set<_Key, _Compare, _Alloc>& __y)
     { __x.swap(__y); }
 _GLIBCXX_END_NAMESPACE_CONTAINER
 } //namespace std
References __glibcxx_class_requires, __glibcxx_class_requires2, __glibcxx_class_requires4, find(), move(), std::__exception_ptr::operator!=(), __gnu_debug::operator<(), __gnu_debug::operator<=(), std::__exception_ptr::operator==(), __gnu_debug::operator>(), __gnu_debug::operator>=(), and swap.