ZEQ2-Lite: SpeexPreprocessState: The Speex preprocessor
SpeexPreprocessState: The Speex preprocessor
This is the Speex preprocessor. The preprocess can do noise suppression, residual echo suppression (after using the echo canceller), automatic gain control (AGC) and voice activity detection (VAD).
Macros
#define SPEEX_PREPROCESS_GET_AGC 3
Get preprocessor Automatic Gain Control state.
#define SPEEX_PREPROCESS_GET_AGC_DECREMENT 29
Get maximal gain decrease in dB/second (int32)
#define SPEEX_PREPROCESS_GET_AGC_INCREMENT 27
Get maximal gain increase in dB/second (int32)
#define SPEEX_PREPROCESS_GET_AGC_LEVEL 7
Get preprocessor Automatic Gain Control level.
#define SPEEX_PREPROCESS_GET_AGC_LOUDNESS 33
Get loudness.
#define SPEEX_PREPROCESS_GET_AGC_MAX_GAIN 31
Get maximal gain in dB (int32)
#define SPEEX_PREPROCESS_GET_DENOISE 1
Get preprocessor denoiser state.
#define SPEEX_PREPROCESS_GET_DEREVERB 9
Get preprocessor dereverb state.
#define SPEEX_PREPROCESS_GET_DEREVERB_DECAY 13
Get preprocessor dereverb decay.
#define SPEEX_PREPROCESS_GET_DEREVERB_LEVEL 11
Get preprocessor dereverb level.
#define SPEEX_PREPROCESS_GET_ECHO_STATE 25
Get the corresponding echo canceller state.
#define SPEEX_PREPROCESS_GET_ECHO_SUPPRESS 21
Get maximum attenuation of the residual echo in dB (negative number)
#define SPEEX_PREPROCESS_GET_ECHO_SUPPRESS_ACTIVE 23
Get maximum attenuation of the residual echo in dB when near end is active (negative number)
#define SPEEX_PREPROCESS_GET_NOISE_SUPPRESS 19
Get maximum attenuation of the noise in dB (negative number)
#define SPEEX_PREPROCESS_GET_PROB_CONTINUE 17
Get probability required for the VAD to stay in the voice state (integer percent)
#define SPEEX_PREPROCESS_GET_PROB_START 15
Get probability required for the VAD to go from silence to voice.
#define SPEEX_PREPROCESS_GET_VAD 5
Get preprocessor Voice Activity Detection state.
#define SPEEX_PREPROCESS_SET_AGC 2
Set preprocessor Automatic Gain Control state.
#define SPEEX_PREPROCESS_SET_AGC_DECREMENT 28
Set maximal gain decrease in dB/second (int32)
#define SPEEX_PREPROCESS_SET_AGC_INCREMENT 26
Set maximal gain increase in dB/second (int32)
#define SPEEX_PREPROCESS_SET_AGC_LEVEL 6
Set preprocessor Automatic Gain Control level.
#define SPEEX_PREPROCESS_SET_AGC_MAX_GAIN 30
Set maximal gain in dB (int32)
#define SPEEX_PREPROCESS_SET_DENOISE 0
Set preprocessor denoiser state.
#define SPEEX_PREPROCESS_SET_DEREVERB 8
Set preprocessor dereverb state.
#define SPEEX_PREPROCESS_SET_DEREVERB_DECAY 12
Set preprocessor dereverb decay.
#define SPEEX_PREPROCESS_SET_DEREVERB_LEVEL 10
Set preprocessor dereverb level.
#define SPEEX_PREPROCESS_SET_ECHO_STATE 24
Set the corresponding echo canceller state so that residual echo suppression can be performed (NULL for no residual echo suppression)
#define SPEEX_PREPROCESS_SET_ECHO_SUPPRESS 20
Set maximum attenuation of the residual echo in dB (negative number)
#define SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE 22
Set maximum attenuation of the residual echo in dB when near end is active (negative number)
#define SPEEX_PREPROCESS_SET_NOISE_SUPPRESS 18
Set maximum attenuation of the noise in dB (negative number)
#define SPEEX_PREPROCESS_SET_PROB_CONTINUE 16
Set probability required for the VAD to stay in the voice state (integer percent)
#define SPEEX_PREPROCESS_SET_PROB_START 14
Set probability required for the VAD to go from silence to voice.
#define SPEEX_PREPROCESS_SET_VAD 4
Set preprocessor Voice Activity Detection state.
Functions
int speex_preprocess (SpeexPreprocessState *st, spx_int16_t *x, spx_int32_t *echo)
Preprocess a frame (deprecated, use speex_preprocess_run() instead)
int speex_preprocess_ctl (SpeexPreprocessState *st, int request, void *ptr)
Used like the ioctl function to control the preprocessor parameters.
void speex_preprocess_estimate_update (SpeexPreprocessState *st, spx_int16_t *x)
Update preprocessor state, but do not compute the output.
int speex_preprocess_run (SpeexPreprocessState *st, spx_int16_t *x)
Preprocess a frame.
void speex_preprocess_state_destroy (SpeexPreprocessState *st)
Destroys a preprocessor state.
SpeexPreprocessState * speex_preprocess_state_init (int frame_size, int sampling_rate)
Creates a new preprocessing state.
Detailed Description
This is the Speex preprocessor. The preprocess can do noise suppression, residual echo suppression (after using the echo canceller), automatic gain control (AGC) and voice activity detection (VAD).
Macro Definition Documentation
SPEEX_PREPROCESS_GET_AGC
#define SPEEX_PREPROCESS_GET_AGC 3
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get preprocessor Automatic Gain Control state.
Definition at line 106 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_AGC_DECREMENT
#define SPEEX_PREPROCESS_GET_AGC_DECREMENT 29
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get maximal gain decrease in dB/second (int32)
Definition at line 173 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_AGC_INCREMENT
#define SPEEX_PREPROCESS_GET_AGC_INCREMENT 27
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get maximal gain increase in dB/second (int32)
Definition at line 167 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_AGC_LEVEL
#define SPEEX_PREPROCESS_GET_AGC_LEVEL 7
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get preprocessor Automatic Gain Control level.
Definition at line 116 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_AGC_LOUDNESS
#define SPEEX_PREPROCESS_GET_AGC_LOUDNESS 33
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get loudness.
Definition at line 183 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_AGC_MAX_GAIN
#define SPEEX_PREPROCESS_GET_AGC_MAX_GAIN 31
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get maximal gain in dB (int32)
Definition at line 179 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_DENOISE
#define SPEEX_PREPROCESS_GET_DENOISE 1
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get preprocessor denoiser state.
Definition at line 101 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_DEREVERB
#define SPEEX_PREPROCESS_GET_DEREVERB 9
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get preprocessor dereverb state.
Definition at line 121 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_DEREVERB_DECAY
#define SPEEX_PREPROCESS_GET_DEREVERB_DECAY 13
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get preprocessor dereverb decay.
Definition at line 131 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_DEREVERB_LEVEL
#define SPEEX_PREPROCESS_GET_DEREVERB_LEVEL 11
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get preprocessor dereverb level.
Definition at line 126 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_ECHO_STATE
#define SPEEX_PREPROCESS_GET_ECHO_STATE 25
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get the corresponding echo canceller state.
Definition at line 161 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_ECHO_SUPPRESS
#define SPEEX_PREPROCESS_GET_ECHO_SUPPRESS 21
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get maximum attenuation of the residual echo in dB (negative number)
Definition at line 151 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_ECHO_SUPPRESS_ACTIVE
#define SPEEX_PREPROCESS_GET_ECHO_SUPPRESS_ACTIVE 23
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get maximum attenuation of the residual echo in dB when near end is active (negative number)
Definition at line 156 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_NOISE_SUPPRESS
#define SPEEX_PREPROCESS_GET_NOISE_SUPPRESS 19
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get maximum attenuation of the noise in dB (negative number)
Definition at line 146 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_PROB_CONTINUE
#define SPEEX_PREPROCESS_GET_PROB_CONTINUE 17
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get probability required for the VAD to stay in the voice state (integer percent)
Definition at line 141 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_PROB_START
#define SPEEX_PREPROCESS_GET_PROB_START 15
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get probability required for the VAD to go from silence to voice.
Definition at line 136 of file speex_preprocess.h.
SPEEX_PREPROCESS_GET_VAD
#define SPEEX_PREPROCESS_GET_VAD 5
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Get preprocessor Voice Activity Detection state.
Definition at line 111 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_AGC
#define SPEEX_PREPROCESS_SET_AGC 2
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set preprocessor Automatic Gain Control state.
Definition at line 104 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_AGC_DECREMENT
#define SPEEX_PREPROCESS_SET_AGC_DECREMENT 28
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set maximal gain decrease in dB/second (int32)
Definition at line 170 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_AGC_INCREMENT
#define SPEEX_PREPROCESS_SET_AGC_INCREMENT 26
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set maximal gain increase in dB/second (int32)
Definition at line 164 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_AGC_LEVEL
#define SPEEX_PREPROCESS_SET_AGC_LEVEL 6
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set preprocessor Automatic Gain Control level.
Definition at line 114 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_AGC_MAX_GAIN
#define SPEEX_PREPROCESS_SET_AGC_MAX_GAIN 30
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set maximal gain in dB (int32)
Definition at line 176 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_DENOISE
#define SPEEX_PREPROCESS_SET_DENOISE 0
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set preprocessor denoiser state.
Definition at line 99 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_DEREVERB
#define SPEEX_PREPROCESS_SET_DEREVERB 8
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set preprocessor dereverb state.
Definition at line 119 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_DEREVERB_DECAY
#define SPEEX_PREPROCESS_SET_DEREVERB_DECAY 12
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set preprocessor dereverb decay.
Definition at line 129 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_DEREVERB_LEVEL
#define SPEEX_PREPROCESS_SET_DEREVERB_LEVEL 10
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set preprocessor dereverb level.
Definition at line 124 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_ECHO_STATE
#define SPEEX_PREPROCESS_SET_ECHO_STATE 24
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set the corresponding echo canceller state so that residual echo suppression can be performed (NULL for no residual echo suppression)
Definition at line 159 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_ECHO_SUPPRESS
#define SPEEX_PREPROCESS_SET_ECHO_SUPPRESS 20
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set maximum attenuation of the residual echo in dB (negative number)
Definition at line 149 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE
#define SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE 22
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set maximum attenuation of the residual echo in dB when near end is active (negative number)
Definition at line 154 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_NOISE_SUPPRESS
#define SPEEX_PREPROCESS_SET_NOISE_SUPPRESS 18
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set maximum attenuation of the noise in dB (negative number)
Definition at line 144 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_PROB_CONTINUE
#define SPEEX_PREPROCESS_SET_PROB_CONTINUE 16
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set probability required for the VAD to stay in the voice state (integer percent)
Definition at line 139 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_PROB_START
#define SPEEX_PREPROCESS_SET_PROB_START 14
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set probability required for the VAD to go from silence to voice.
Definition at line 134 of file speex_preprocess.h.
SPEEX_PREPROCESS_SET_VAD
#define SPEEX_PREPROCESS_SET_VAD 4
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Set preprocessor Voice Activity Detection state.
Definition at line 109 of file speex_preprocess.h.
Function Documentation
speex_preprocess()
int speex_preprocess (SpeexPreprocessState * st, spx_int16_t * x, spx_int32_t * echo)
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Preprocess a frame (deprecated, use speex_preprocess_run() instead)
Definition at line 722 of file preprocess.c.
 {
    return speex_preprocess_run(st, x);
 }
References speex_preprocess_run().
speex_preprocess_ctl()
int speex_preprocess_ctl (SpeexPreprocessState * st, int request, void * ptr)
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Used like the ioctl function to control the preprocessor parameters.
Parameters
st Preprocessor state
request ioctl-type request (one of the SPEEX_PREPROCESS_* macros)
ptr Data exchanged to-from function
Returns
0 if no error, -1 if request in unknown
Definition at line 1048 of file preprocess.c.
 {
    int i;
    SpeexPreprocessState *st;
    st=(SpeexPreprocessState*)state;
    switch(request)
    {
    case SPEEX_PREPROCESS_SET_DENOISE:
       st->denoise_enabled = (*(spx_int32_t*)ptr);
       break;
    case SPEEX_PREPROCESS_GET_DENOISE:
       (*(spx_int32_t*)ptr) = st->denoise_enabled;
       break;
 #ifndef FIXED_POINT
    case SPEEX_PREPROCESS_SET_AGC:
       st->agc_enabled = (*(spx_int32_t*)ptr);
       break;
    case SPEEX_PREPROCESS_GET_AGC:
       (*(spx_int32_t*)ptr) = st->agc_enabled;
       break;
 #ifndef DISABLE_FLOAT_API
    case SPEEX_PREPROCESS_SET_AGC_LEVEL:
       st->agc_level = (*(float*)ptr);
       if (st->agc_level<1)
          st->agc_level=1;
       if (st->agc_level>32768)
          st->agc_level=32768;
       break;
    case SPEEX_PREPROCESS_GET_AGC_LEVEL:
       (*(float*)ptr) = st->agc_level;
       break;
 #endif /* #ifndef DISABLE_FLOAT_API */
    case SPEEX_PREPROCESS_SET_AGC_INCREMENT:
       st->max_increase_step = exp(0.11513f * (*(spx_int32_t*)ptr)*st->frame_size / st->sampling_rate);
       break;
    case SPEEX_PREPROCESS_GET_AGC_INCREMENT:
       (*(spx_int32_t*)ptr) = floor(.5+8.6858*log(st->max_increase_step)*st->sampling_rate/st->frame_size);
       break;
    case SPEEX_PREPROCESS_SET_AGC_DECREMENT:
       st->max_decrease_step = exp(0.11513f * (*(spx_int32_t*)ptr)*st->frame_size / st->sampling_rate);
       break;
    case SPEEX_PREPROCESS_GET_AGC_DECREMENT:
       (*(spx_int32_t*)ptr) = floor(.5+8.6858*log(st->max_decrease_step)*st->sampling_rate/st->frame_size);
       break;
    case SPEEX_PREPROCESS_SET_AGC_MAX_GAIN:
       st->max_gain = exp(0.11513f * (*(spx_int32_t*)ptr));
       break;
    case SPEEX_PREPROCESS_GET_AGC_MAX_GAIN:
       (*(spx_int32_t*)ptr) = floor(.5+8.6858*log(st->max_gain));
       break;
 #endif
    case SPEEX_PREPROCESS_SET_VAD:
       speex_warning("The VAD has been replaced by a hack pending a complete rewrite");
       st->vad_enabled = (*(spx_int32_t*)ptr);
       break;
    case SPEEX_PREPROCESS_GET_VAD:
       (*(spx_int32_t*)ptr) = st->vad_enabled;
       break;
    case SPEEX_PREPROCESS_SET_DEREVERB:
       st->dereverb_enabled = (*(spx_int32_t*)ptr);
       for (i=0;i<st->ps_size;i++)
          st->reverb_estimate[i]=0;
       break;
    case SPEEX_PREPROCESS_GET_DEREVERB:
       (*(spx_int32_t*)ptr) = st->dereverb_enabled;
       break;
    case SPEEX_PREPROCESS_SET_DEREVERB_LEVEL:
       /* FIXME: Re-enable when de-reverberation is actually enabled again */
       /*st->reverb_level = (*(float*)ptr);*/
       break;
    case SPEEX_PREPROCESS_GET_DEREVERB_LEVEL:
       /* FIXME: Re-enable when de-reverberation is actually enabled again */
       /*(*(float*)ptr) = st->reverb_level;*/
       break;
    case SPEEX_PREPROCESS_SET_DEREVERB_DECAY:
       /* FIXME: Re-enable when de-reverberation is actually enabled again */
       /*st->reverb_decay = (*(float*)ptr);*/
       break;
    case SPEEX_PREPROCESS_GET_DEREVERB_DECAY:
       /* FIXME: Re-enable when de-reverberation is actually enabled again */
       /*(*(float*)ptr) = st->reverb_decay;*/
       break;
    case SPEEX_PREPROCESS_SET_PROB_START:
       *(spx_int32_t*)ptr = MIN32(100,MAX32(0, *(spx_int32_t*)ptr));
       st->speech_prob_start = DIV32_16(MULT16_16(Q15ONE,*(spx_int32_t*)ptr), 100);
       break;
    case SPEEX_PREPROCESS_GET_PROB_START:
       (*(spx_int32_t*)ptr) = MULT16_16_Q15(st->speech_prob_start, 100);
       break;
    case SPEEX_PREPROCESS_SET_PROB_CONTINUE:
       *(spx_int32_t*)ptr = MIN32(100,MAX32(0, *(spx_int32_t*)ptr));
       st->speech_prob_continue = DIV32_16(MULT16_16(Q15ONE,*(spx_int32_t*)ptr), 100);
       break;
    case SPEEX_PREPROCESS_GET_PROB_CONTINUE:
       (*(spx_int32_t*)ptr) = MULT16_16_Q15(st->speech_prob_continue, 100);
       break;
    case SPEEX_PREPROCESS_SET_NOISE_SUPPRESS:
       st->noise_suppress = -ABS(*(spx_int32_t*)ptr);
       break;
    case SPEEX_PREPROCESS_GET_NOISE_SUPPRESS:
       (*(spx_int32_t*)ptr) = st->noise_suppress;
       break;
    case SPEEX_PREPROCESS_SET_ECHO_SUPPRESS:
       st->echo_suppress = -ABS(*(spx_int32_t*)ptr);
       break;
    case SPEEX_PREPROCESS_GET_ECHO_SUPPRESS:
       (*(spx_int32_t*)ptr) = st->echo_suppress;
       break;
    case SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE:
       st->echo_suppress_active = -ABS(*(spx_int32_t*)ptr);
       break;
    case SPEEX_PREPROCESS_GET_ECHO_SUPPRESS_ACTIVE:
       (*(spx_int32_t*)ptr) = st->echo_suppress_active;
       break;
    case SPEEX_PREPROCESS_SET_ECHO_STATE:
       st->echo_state = (SpeexEchoState*)ptr;
       break;
    case SPEEX_PREPROCESS_GET_ECHO_STATE:
       ptr = (void*)st->echo_state;
       break;
 #ifndef FIXED_POINT
    case SPEEX_PREPROCESS_GET_AGC_LOUDNESS:
       (*(spx_int32_t*)ptr) = pow(st->loudness, 1.0/LOUDNESS_EXP);
       break;
 #endif
    default:
       speex_warning_int("Unknown speex_preprocess_ctl request: ", request);
       return -1;
    }
    return 0;
 }
References ABS, DIV32_16, LOUDNESS_EXP, MAX32, MIN32, MULT16_16, MULT16_16_Q15, ptr(), Q15ONE, SPEEX_PREPROCESS_GET_AGC, SPEEX_PREPROCESS_GET_AGC_DECREMENT, SPEEX_PREPROCESS_GET_AGC_INCREMENT, SPEEX_PREPROCESS_GET_AGC_LEVEL, SPEEX_PREPROCESS_GET_AGC_LOUDNESS, SPEEX_PREPROCESS_GET_AGC_MAX_GAIN, SPEEX_PREPROCESS_GET_DENOISE, SPEEX_PREPROCESS_GET_DEREVERB, SPEEX_PREPROCESS_GET_DEREVERB_DECAY, SPEEX_PREPROCESS_GET_DEREVERB_LEVEL, SPEEX_PREPROCESS_GET_ECHO_STATE, SPEEX_PREPROCESS_GET_ECHO_SUPPRESS, SPEEX_PREPROCESS_GET_ECHO_SUPPRESS_ACTIVE, SPEEX_PREPROCESS_GET_NOISE_SUPPRESS, SPEEX_PREPROCESS_GET_PROB_CONTINUE, SPEEX_PREPROCESS_GET_PROB_START, SPEEX_PREPROCESS_GET_VAD, SPEEX_PREPROCESS_SET_AGC, SPEEX_PREPROCESS_SET_AGC_DECREMENT, SPEEX_PREPROCESS_SET_AGC_INCREMENT, SPEEX_PREPROCESS_SET_AGC_LEVEL, SPEEX_PREPROCESS_SET_AGC_MAX_GAIN, SPEEX_PREPROCESS_SET_DENOISE, SPEEX_PREPROCESS_SET_DEREVERB, SPEEX_PREPROCESS_SET_DEREVERB_DECAY, SPEEX_PREPROCESS_SET_DEREVERB_LEVEL, SPEEX_PREPROCESS_SET_ECHO_STATE, SPEEX_PREPROCESS_SET_ECHO_SUPPRESS, SPEEX_PREPROCESS_SET_ECHO_SUPPRESS_ACTIVE, SPEEX_PREPROCESS_SET_NOISE_SUPPRESS, SPEEX_PREPROCESS_SET_PROB_CONTINUE, SPEEX_PREPROCESS_SET_PROB_START, SPEEX_PREPROCESS_SET_VAD, speex_warning(), and speex_warning_int().
Referenced by CL_FirstSnapshot(), and main().
speex_preprocess_estimate_update()
void speex_preprocess_estimate_update (SpeexPreprocessState * st, spx_int16_t * x)
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Update preprocessor state, but do not compute the output.
Parameters
st Preprocessor state
x Audio sample vector (in only). Must be same size as specified in speex_preprocess_state_init().
Definition at line 1013 of file preprocess.c.
 {
    int i;
    int N = st->ps_size;
    int N3 = 2*N - st->frame_size;
    int M;
    spx_word32_t *ps=st->ps;
    M = st->nbands;
    st->min_count++;
    preprocess_analysis(st, x);
    update_noise_prob(st);
    for (i=1;i<N-1;i++)
    {
       if (!st->update_prob[i] || st->ps[i] < PSHR32(st->noise[i],NOISE_SHIFT))
       {
          st->noise[i] = MULT16_32_Q15(QCONST16(.95f,15),st->noise[i]) + MULT16_32_Q15(QCONST16(.05f,15),SHL32(st->ps[i],NOISE_SHIFT));
       }
    }
    for (i=0;i<N3;i++)
       st->outbuf[i] = MULT16_16_Q15(x[st->frame_size-N3+i],st->window[st->frame_size+i]);
    /* Save old power spectrum */
    for (i=0;i<N+M;i++)
       st->old_ps[i] = ps[i];
    for (i=0;i<N;i++)
       st->reverb_estimate[i] = MULT16_32_Q15(st->reverb_decay, st->reverb_estimate[i]);
 }
References M, MULT16_16_Q15, MULT16_32_Q15, NOISE_SHIFT, preprocess_analysis(), PSHR32, QCONST16, SHL32, and update_noise_prob().
speex_preprocess_run()
int speex_preprocess_run (SpeexPreprocessState * st, spx_int16_t * x)
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Preprocess a frame.
Parameters
st Preprocessor state
x Audio sample vector (in and out). Must be same size as specified in speex_preprocess_state_init().
Returns
Bool value for voice activity (1 for speech, 0 for noise/silence), ONLY if VAD turned on.
Definition at line 727 of file preprocess.c.
 {
    int i;
    int M;
    int N = st->ps_size;
    int N3 = 2*N - st->frame_size;
    int N4 = st->frame_size - N3;
    spx_word32_t *ps=st->ps;
    spx_word32_t Zframe;
    spx_word16_t Pframe;
    spx_word16_t beta, beta_1;
    spx_word16_t effective_echo_suppress;
    st->nb_adapt++;
    if (st->nb_adapt>20000)
       st->nb_adapt = 20000;
    st->min_count++;
    beta = MAX16(QCONST16(.03,15),DIV32_16(Q15_ONE,st->nb_adapt));
    beta_1 = Q15_ONE-beta;
    M = st->nbands;
    /* Deal with residual echo if provided */
    if (st->echo_state)
    {
       speex_echo_get_residual(st->echo_state, st->residual_echo, N);
 #ifndef FIXED_POINT
       /* If there are NaNs or ridiculous values, it'll show up in the DC and we just reset everything to zero */
       if (!(st->residual_echo[0] >=0 && st->residual_echo[0]<N*1e9f))
       {
          for (i=0;i<N;i++)
             st->residual_echo[i] = 0;
       }
 #endif
       for (i=0;i<N;i++)
          st->echo_noise[i] = MAX32(MULT16_32_Q15(QCONST16(.6f,15),st->echo_noise[i]), st->residual_echo[i]);
       filterbank_compute_bank32(st->bank, st->echo_noise, st->echo_noise+N);
    } else {
       for (i=0;i<N+M;i++)
          st->echo_noise[i] = 0;
    }
    preprocess_analysis(st, x);
    update_noise_prob(st);
    /* Noise estimation always updated for the 10 first frames */
    /*if (st->nb_adapt<10)
    {
       for (i=1;i<N-1;i++)
          st->update_prob[i] = 0;
    }
    */
    /* Update the noise estimate for the frequencies where it can be */
    for (i=0;i<N;i++)
    {
       if (!st->update_prob[i] || st->ps[i] < PSHR32(st->noise[i], NOISE_SHIFT))
          st->noise[i] = MAX32(EXTEND32(0),MULT16_32_Q15(beta_1,st->noise[i]) + MULT16_32_Q15(beta,SHL32(st->ps[i],NOISE_SHIFT)));
    }
    filterbank_compute_bank32(st->bank, st->noise, st->noise+N);
    /* Special case for first frame */
    if (st->nb_adapt==1)
       for (i=0;i<N+M;i++)
          st->old_ps[i] = ps[i];
    /* Compute a posteriori SNR */
    for (i=0;i<N+M;i++)
    {
       spx_word16_t gamma;
       /* Total noise estimate including residual echo and reverberation */
       spx_word32_t tot_noise = ADD32(ADD32(ADD32(EXTEND32(1), PSHR32(st->noise[i],NOISE_SHIFT)) , st->echo_noise[i]) , st->reverb_estimate[i]);
       /* A posteriori SNR = ps/noise - 1*/
       st->post[i] = SUB16(DIV32_16_Q8(ps[i],tot_noise), QCONST16(1.f,SNR_SHIFT));
       st->post[i]=MIN16(st->post[i], QCONST16(100.f,SNR_SHIFT));
       /* Computing update gamma = .1 + .9*(old/(old+noise))^2 */
       gamma = QCONST16(.1f,15)+MULT16_16_Q15(QCONST16(.89f,15),SQR16_Q15(DIV32_16_Q15(st->old_ps[i],ADD32(st->old_ps[i],tot_noise))));
       /* A priori SNR update = gamma*max(0,post) + (1-gamma)*old/noise */
       st->prior[i] = EXTRACT16(PSHR32(ADD32(MULT16_16(gamma,MAX16(0,st->post[i])), MULT16_16(Q15_ONE-gamma,DIV32_16_Q8(st->old_ps[i],tot_noise))), 15));
       st->prior[i]=MIN16(st->prior[i], QCONST16(100.f,SNR_SHIFT));
    }
    /*print_vec(st->post, N+M, "");*/
    /* Recursive average of the a priori SNR. A bit smoothed for the psd components */
    st->zeta[0] = PSHR32(ADD32(MULT16_16(QCONST16(.7f,15),st->zeta[0]), MULT16_16(QCONST16(.3f,15),st->prior[0])),15);
    for (i=1;i<N-1;i++)
       st->zeta[i] = PSHR32(ADD32(ADD32(ADD32(MULT16_16(QCONST16(.7f,15),st->zeta[i]), MULT16_16(QCONST16(.15f,15),st->prior[i])),
                            MULT16_16(QCONST16(.075f,15),st->prior[i-1])), MULT16_16(QCONST16(.075f,15),st->prior[i+1])),15);
    for (i=N-1;i<N+M;i++)
       st->zeta[i] = PSHR32(ADD32(MULT16_16(QCONST16(.7f,15),st->zeta[i]), MULT16_16(QCONST16(.3f,15),st->prior[i])),15);
    /* Speech probability of presence for the entire frame is based on the average filterbank a priori SNR */
    Zframe = 0;
    for (i=N;i<N+M;i++)
       Zframe = ADD32(Zframe, EXTEND32(st->zeta[i]));
    Pframe = QCONST16(.1f,15)+MULT16_16_Q15(QCONST16(.899f,15),qcurve(DIV32_16(Zframe,st->nbands)));
    effective_echo_suppress = EXTRACT16(PSHR32(ADD32(MULT16_16(SUB16(Q15_ONE,Pframe), st->echo_suppress), MULT16_16(Pframe, st->echo_suppress_active)),15));
    compute_gain_floor(st->noise_suppress, effective_echo_suppress, st->noise+N, st->echo_noise+N, st->gain_floor+N, M);
    /* Compute Ephraim & Malah gain speech probability of presence for each critical band (Bark scale)
       Technically this is actually wrong because the EM gaim assumes a slightly different probability
       distribution */
    for (i=N;i<N+M;i++)
    {
       /* See EM and Cohen papers*/
       spx_word32_t theta;
       /* Gain from hypergeometric function */
       spx_word32_t MM;
       /* Weiner filter gain */
       spx_word16_t prior_ratio;
       /* a priority probability of speech presence based on Bark sub-band alone */
       spx_word16_t P1;
       /* Speech absence a priori probability (considering sub-band and frame) */
       spx_word16_t q;
 #ifdef FIXED_POINT
       spx_word16_t tmp;
 #endif
       prior_ratio = PDIV32_16(SHL32(EXTEND32(st->prior[i]), 15), ADD16(st->prior[i], SHL32(1,SNR_SHIFT)));
       theta = MULT16_32_P15(prior_ratio, QCONST32(1.f,EXPIN_SHIFT)+SHL32(EXTEND32(st->post[i]),EXPIN_SHIFT-SNR_SHIFT));
       MM = hypergeom_gain(theta);
       /* Gain with bound */
       st->gain[i] = EXTRACT16(MIN32(Q15_ONE, MULT16_32_Q15(prior_ratio, MM)));
       /* Save old Bark power spectrum */
       st->old_ps[i] = MULT16_32_P15(QCONST16(.2f,15),st->old_ps[i]) + MULT16_32_P15(MULT16_16_P15(QCONST16(.8f,15),SQR16_Q15(st->gain[i])),ps[i]);
       P1 = QCONST16(.199f,15)+MULT16_16_Q15(QCONST16(.8f,15),qcurve (st->zeta[i]));
       q = Q15_ONE-MULT16_16_Q15(Pframe,P1);
 #ifdef FIXED_POINT
       theta = MIN32(theta, EXTEND32(32767));
 /*Q8*/tmp = MULT16_16_Q15((SHL32(1,SNR_SHIFT)+st->prior[i]),EXTRACT16(MIN32(Q15ONE,SHR32(spx_exp(-EXTRACT16(theta)),1))));
       tmp = MIN16(QCONST16(3.,SNR_SHIFT), tmp); /* Prevent overflows in the next line*/
 /*Q8*/tmp = EXTRACT16(PSHR32(MULT16_16(PDIV32_16(SHL32(EXTEND32(q),8),(Q15_ONE-q)),tmp),8));
       st->gain2[i]=DIV32_16(SHL32(EXTEND32(32767),SNR_SHIFT), ADD16(256,tmp));
 #else
       st->gain2[i]=1/(1.f + (q/(1.f-q))*(1+st->prior[i])*exp(-theta));
 #endif
    }
    /* Convert the EM gains and speech prob to linear frequency */
    filterbank_compute_psd16(st->bank,st->gain2+N, st->gain2);
    filterbank_compute_psd16(st->bank,st->gain+N, st->gain);
    /* Use 1 for linear gain resolution (best) or 0 for Bark gain resolution (faster) */
    if (1)
    {
       filterbank_compute_psd16(st->bank,st->gain_floor+N, st->gain_floor);
       /* Compute gain according to the Ephraim-Malah algorithm -- linear frequency */
       for (i=0;i<N;i++)
       {
          spx_word32_t MM;
          spx_word32_t theta;
          spx_word16_t prior_ratio;
          spx_word16_t tmp;
          spx_word16_t p;
          spx_word16_t g;
          /* Wiener filter gain */
          prior_ratio = PDIV32_16(SHL32(EXTEND32(st->prior[i]), 15), ADD16(st->prior[i], SHL32(1,SNR_SHIFT)));
          theta = MULT16_32_P15(prior_ratio, QCONST32(1.f,EXPIN_SHIFT)+SHL32(EXTEND32(st->post[i]),EXPIN_SHIFT-SNR_SHIFT));
          /* Optimal estimator for loudness domain */
          MM = hypergeom_gain(theta);
          /* EM gain with bound */
          g = EXTRACT16(MIN32(Q15_ONE, MULT16_32_Q15(prior_ratio, MM)));
          /* Interpolated speech probability of presence */
          p = st->gain2[i];
          /* Constrain the gain to be close to the Bark scale gain */
          if (MULT16_16_Q15(QCONST16(.333f,15),g) > st->gain[i])
             g = MULT16_16(3,st->gain[i]);
          st->gain[i] = g;
          /* Save old power spectrum */
          st->old_ps[i] = MULT16_32_P15(QCONST16(.2f,15),st->old_ps[i]) + MULT16_32_P15(MULT16_16_P15(QCONST16(.8f,15),SQR16_Q15(st->gain[i])),ps[i]);
          /* Apply gain floor */
          if (st->gain[i] < st->gain_floor[i])
             st->gain[i] = st->gain_floor[i];
          /* Exponential decay model for reverberation (unused) */
          /*st->reverb_estimate[i] = st->reverb_decay*st->reverb_estimate[i] + st->reverb_decay*st->reverb_level*st->gain[i]*st->gain[i]*st->ps[i];*/
          /* Take into account speech probability of presence (loudness domain MMSE estimator) */
          /* gain2 = [p*sqrt(gain)+(1-p)*sqrt(gain _floor) ]^2 */
          tmp = MULT16_16_P15(p,spx_sqrt(SHL32(EXTEND32(st->gain[i]),15))) + MULT16_16_P15(SUB16(Q15_ONE,p),spx_sqrt(SHL32(EXTEND32(st->gain_floor[i]),15)));
          st->gain2[i]=SQR16_Q15(tmp);
          /* Use this if you want a log-domain MMSE estimator instead */
          /*st->gain2[i] = pow(st->gain[i], p) * pow(st->gain_floor[i],1.f-p);*/
       }
    } else {
       for (i=N;i<N+M;i++)
       {
          spx_word16_t tmp;
          spx_word16_t p = st->gain2[i];
          st->gain[i] = MAX16(st->gain[i], st->gain_floor[i]);
          tmp = MULT16_16_P15(p,spx_sqrt(SHL32(EXTEND32(st->gain[i]),15))) + MULT16_16_P15(SUB16(Q15_ONE,p),spx_sqrt(SHL32(EXTEND32(st->gain_floor[i]),15)));
          st->gain2[i]=SQR16_Q15(tmp);
       }
       filterbank_compute_psd16(st->bank,st->gain2+N, st->gain2);
    }
    /* If noise suppression is off, don't apply the gain (but then why call this in the first place!) */
    if (!st->denoise_enabled)
    {
       for (i=0;i<N+M;i++)
          st->gain2[i]=Q15_ONE;
    }
    /* Apply computed gain */
    for (i=1;i<N;i++)
    {
       st->ft[2*i-1] = MULT16_16_P15(st->gain2[i],st->ft[2*i-1]);
       st->ft[2*i] = MULT16_16_P15(st->gain2[i],st->ft[2*i]);
    }
    st->ft[0] = MULT16_16_P15(st->gain2[0],st->ft[0]);
    st->ft[2*N-1] = MULT16_16_P15(st->gain2[N-1],st->ft[2*N-1]);
    /*FIXME: This *will* not work for fixed-point */
 #ifndef FIXED_POINT
    if (st->agc_enabled)
       speex_compute_agc(st, Pframe, st->ft);
 #endif
    /* Inverse FFT with 1/N scaling */
    spx_ifft(st->fft_lookup, st->ft, st->frame);
    /* Scale back to original (lower) amplitude */
    for (i=0;i<2*N;i++)
       st->frame[i] = PSHR16(st->frame[i], st->frame_shift);
    /*FIXME: This *will* not work for fixed-point */
 #ifndef FIXED_POINT
    if (st->agc_enabled)
    {
       float max_sample=0;
       for (i=0;i<2*N;i++)
          if (fabs(st->frame[i])>max_sample)
             max_sample = fabs(st->frame[i]);
       if (max_sample>28000.f)
       {
          float damp = 28000.f/max_sample;
          for (i=0;i<2*N;i++)
             st->frame[i] *= damp;
       }
    }
 #endif
    /* Synthesis window (for WOLA) */
    for (i=0;i<2*N;i++)
       st->frame[i] = MULT16_16_Q15(st->frame[i], st->window[i]);
    /* Perform overlap and add */
    for (i=0;i<N3;i++)
       x[i] = st->outbuf[i] + st->frame[i];
    for (i=0;i<N4;i++)
       x[N3+i] = st->frame[N3+i];
    /* Update outbuf */
    for (i=0;i<N3;i++)
       st->outbuf[i] = st->frame[st->frame_size+i];
    /* FIXME: This VAD is a kludge */
    if (st->vad_enabled)
    {
       if (Pframe > st->speech_prob_start || (st->was_speech && Pframe > st->speech_prob_continue))
       {
          st->was_speech=1;
          return 1;
       } else
       {
          st->was_speech=0;
          return 0;
       }
    } else {
       return 1;
    }
 }
References ADD16, ADD32, compute_gain_floor(), DIV32_16, DIV32_16_Q15, DIV32_16_Q8, EXTEND32, EXTRACT16, filterbank_compute_bank32(), filterbank_compute_psd16(), hypergeom_gain(), M, MAX16, MAX32, MIN16, MIN32, MULT16_16, MULT16_16_P15, MULT16_16_Q15, MULT16_32_P15, MULT16_32_Q15, NOISE_SHIFT, PDIV32_16, preprocess_analysis(), PSHR16, PSHR32, Q15_ONE, Q15ONE, QCONST16, QCONST32, qcurve(), SHL32, SHR32, SNR_SHIFT, speex_compute_agc(), speex_echo_get_residual(), spx_exp, spx_ifft(), spx_sqrt, SQR16_Q15, SUB16, and update_noise_prob().
Referenced by main(), and speex_preprocess().
speex_preprocess_state_destroy()
void speex_preprocess_state_destroy (SpeexPreprocessState * st)
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Destroys a preprocessor state.
Parameters
st Preprocessor state to destroy
Definition at line 533 of file preprocess.c.
 {
    speex_free(st->frame);
    speex_free(st->ft);
    speex_free(st->ps);
    speex_free(st->gain2);
    speex_free(st->gain_floor);
    speex_free(st->window);
    speex_free(st->noise);
    speex_free(st->reverb_estimate);
    speex_free(st->old_ps);
    speex_free(st->gain);
    speex_free(st->prior);
    speex_free(st->post);
 #ifndef FIXED_POINT
    speex_free(st->loudness_weight);
 #endif
    speex_free(st->echo_noise);
    speex_free(st->residual_echo);
    speex_free(st->S);
    speex_free(st->Smin);
    speex_free(st->Stmp);
    speex_free(st->update_prob);
    speex_free(st->zeta);
    speex_free(st->inbuf);
    speex_free(st->outbuf);
    spx_fft_destroy(st->fft_lookup);
    filterbank_destroy(st->bank);
    speex_free(st);
 }
References filterbank_destroy(), speex_free(), and spx_fft_destroy().
Referenced by CL_Disconnect(), and main().
speex_preprocess_state_init()
SpeexPreprocessState* speex_preprocess_state_init (int frame_size, int sampling_rate)
#include <Source/Engine/libspeex/include/speex/speex_preprocess.h>
Creates a new preprocessing state.
You MUST create one state per channel processed.
Parameters
frame_size Number of samples to process at one time (should correspond to 10-20 ms). Must be the same value as that used for the echo canceller for residual echo cancellation to work.
sampling_rate Sampling rate used for the input.
Returns
Newly created preprocessor state
Definition at line 394 of file preprocess.c.
 {
    int i;
    int N, N3, N4, M;
    SpeexPreprocessState *st = (SpeexPreprocessState *)speex_alloc(sizeof(SpeexPreprocessState));
    st->frame_size = frame_size;
    /* Round ps_size down to the nearest power of two */
 #if 0
    i=1;
    st->ps_size = st->frame_size;
    while(1)
    {
       if (st->ps_size & ~i)
       {
          st->ps_size &= ~i;
          i<<=1;
       } else {
          break;
       }
    }
    if (st->ps_size < 3*st->frame_size/4)
       st->ps_size = st->ps_size * 3 / 2;
 #else
    st->ps_size = st->frame_size;
 #endif
    N = st->ps_size;
    N3 = 2*N - st->frame_size;
    N4 = st->frame_size - N3;
    st->sampling_rate = sampling_rate;
    st->denoise_enabled = 1;
    st->vad_enabled = 0;
    st->dereverb_enabled = 0;
    st->reverb_decay = 0;
    st->reverb_level = 0;
    st->noise_suppress = NOISE_SUPPRESS_DEFAULT;
    st->echo_suppress = ECHO_SUPPRESS_DEFAULT;
    st->echo_suppress_active = ECHO_SUPPRESS_ACTIVE_DEFAULT;
    st->speech_prob_start = SPEECH_PROB_START_DEFAULT;
    st->speech_prob_continue = SPEECH_PROB_CONTINUE_DEFAULT;
    st->echo_state = NULL;
    st->nbands = NB_BANDS;
    M = st->nbands;
    st->bank = filterbank_new(M, sampling_rate, N, 1);
    st->frame = (spx_word16_t*)speex_alloc(2*N*sizeof(spx_word16_t));
    st->window = (spx_word16_t*)speex_alloc(2*N*sizeof(spx_word16_t));
    st->ft = (spx_word16_t*)speex_alloc(2*N*sizeof(spx_word16_t));
    st->ps = (spx_word32_t*)speex_alloc((N+M)*sizeof(spx_word32_t));
    st->noise = (spx_word32_t*)speex_alloc((N+M)*sizeof(spx_word32_t));
    st->echo_noise = (spx_word32_t*)speex_alloc((N+M)*sizeof(spx_word32_t));
    st->residual_echo = (spx_word32_t*)speex_alloc((N+M)*sizeof(spx_word32_t));
    st->reverb_estimate = (spx_word32_t*)speex_alloc((N+M)*sizeof(spx_word32_t));
    st->old_ps = (spx_word32_t*)speex_alloc((N+M)*sizeof(spx_word32_t));
    st->prior = (spx_word16_t*)speex_alloc((N+M)*sizeof(spx_word16_t));
    st->post = (spx_word16_t*)speex_alloc((N+M)*sizeof(spx_word16_t));
    st->gain = (spx_word16_t*)speex_alloc((N+M)*sizeof(spx_word16_t));
    st->gain2 = (spx_word16_t*)speex_alloc((N+M)*sizeof(spx_word16_t));
    st->gain_floor = (spx_word16_t*)speex_alloc((N+M)*sizeof(spx_word16_t));
    st->zeta = (spx_word16_t*)speex_alloc((N+M)*sizeof(spx_word16_t));
    st->S = (spx_word32_t*)speex_alloc(N*sizeof(spx_word32_t));
    st->Smin = (spx_word32_t*)speex_alloc(N*sizeof(spx_word32_t));
    st->Stmp = (spx_word32_t*)speex_alloc(N*sizeof(spx_word32_t));
    st->update_prob = (int*)speex_alloc(N*sizeof(int));
    st->inbuf = (spx_word16_t*)speex_alloc(N3*sizeof(spx_word16_t));
    st->outbuf = (spx_word16_t*)speex_alloc(N3*sizeof(spx_word16_t));
    conj_window(st->window, 2*N3);
    for (i=2*N3;i<2*st->ps_size;i++)
       st->window[i]=Q15_ONE;
    if (N4>0)
    {
       for (i=N3-1;i>=0;i--)
       {
          st->window[i+N3+N4]=st->window[i+N3];
          st->window[i+N3]=1;
       }
    }
    for (i=0;i<N+M;i++)
    {
       st->noise[i]=QCONST32(1.f,NOISE_SHIFT);
       st->reverb_estimate[i]=0;
       st->old_ps[i]=1;
       st->gain[i]=Q15_ONE;
       st->post[i]=SHL16(1, SNR_SHIFT);
       st->prior[i]=SHL16(1, SNR_SHIFT);
    }
    for (i=0;i<N;i++)
       st->update_prob[i] = 1;
    for (i=0;i<N3;i++)
    {
       st->inbuf[i]=0;
       st->outbuf[i]=0;
    }
 #ifndef FIXED_POINT
    st->agc_enabled = 0;
    st->agc_level = 8000;
    st->loudness_weight = (float*)speex_alloc(N*sizeof(float));
    for (i=0;i<N;i++)
    {
       float ff=((float)i)*.5*sampling_rate/((float)N);
       /*st->loudness_weight[i] = .5f*(1.f/(1.f+ff/8000.f))+1.f*exp(-.5f*(ff-3800.f)*(ff-3800.f)/9e5f);*/
       st->loudness_weight[i] = .35f-.35f*ff/16000.f+.73f*exp(-.5f*(ff-3800)*(ff-3800)/9e5f);
       if (st->loudness_weight[i]<.01f)
          st->loudness_weight[i]=.01f;
       st->loudness_weight[i] *= st->loudness_weight[i];
    }
    /*st->loudness = pow(AMP_SCALE*st->agc_level,LOUDNESS_EXP);*/
    st->loudness = 1e-15;
    st->agc_gain = 1;
    st->nb_loudness_adapt = 0;
    st->max_gain = 30;
    st->max_increase_step = exp(0.11513f * 12.*st->frame_size / st->sampling_rate);
    st->max_decrease_step = exp(-0.11513f * 40.*st->frame_size / st->sampling_rate);
    st->prev_loudness = 1;
    st->init_max = 1;
 #endif
    st->was_speech = 0;
    st->fft_lookup = spx_fft_init(2*N);
    st->nb_adapt=0;
    st->min_count=0;
    return st;
 }
References conj_window(), ECHO_SUPPRESS_ACTIVE_DEFAULT, ECHO_SUPPRESS_DEFAULT, filterbank_new(), M, NB_BANDS, NOISE_SHIFT, NOISE_SUPPRESS_DEFAULT, NULL, Q15_ONE, QCONST32, SHL16, SNR_SHIFT, SPEECH_PROB_CONTINUE_DEFAULT, SPEECH_PROB_START_DEFAULT, speex_alloc(), and spx_fft_init().
Referenced by CL_FirstSnapshot(), and main().