ZEQ2-Lite: Source/Engine/tools/asm/q3asm.c File Reference
q3asm.c File Reference
#include "../../../Shared/q_platform.h"
#include "cmdlib.h"
#include "mathlib.h"
#include "../../../Shared/qfiles.h"
#include "opstrings.h"
Data Structures
struct executableHeader_t
struct hashchain_s
struct hashtable_s
struct options_s
struct segment_t
struct sourceOps_t
struct symbol_s
Macros
#define ASM(O) int TryAssemble##O ()
#define ASM(O) if (TryAssemble##O ()) return;
#define atoi64 atoll
#define DEFAULT_HASHTABLE_SIZE 2048
#define INT64 long long int
#define MAX_ASM_FILES 256
#define MAX_IMAGE 0x400000
#define MAX_LINE_LENGTH 1024
#define NUM_SOURCE_OPS (sizeof(sourceOps) / sizeof(sourceOps[0]))
#define STAT(L)
#define ZERO_PAGE_SIZE 0
Enumerations
enum opcode_t {
OP_UNDEF, OP_IGNORE, OP_BREAK, OP_ENTER,
OP_LEAVE, OP_CALL, OP_PUSH, OP_POP,
OP_CONST, OP_LOCAL, OP_JUMP, OP_EQ,
OP_NE, OP_LTI, OP_LEI, OP_GTI,
OP_GEI, OP_LTU, OP_LEU, OP_GTU,
OP_GEU, OP_EQF, OP_NEF, OP_LTF,
OP_LEF, OP_GTF, OP_GEF, OP_LOAD1,
OP_LOAD2, OP_LOAD4, OP_STORE1, OP_STORE2,
OP_STORE4, OP_ARG, OP_BLOCK_COPY, OP_SEX8,
OP_SEX16, OP_NEGI, OP_ADD, OP_SUB,
OP_DIVI, OP_DIVU, OP_MODI, OP_MODU,
OP_MULI, OP_MULU, OP_BAND, OP_BOR,
OP_BXOR, OP_BCOM, OP_LSH, OP_RSHI,
OP_RSHU, OP_NEGF, OP_ADDF, OP_SUBF,
OP_DIVF, OP_MULF, OP_CVIF, OP_CVFI,
OP_UNDEF, OP_IGNORE, OP_BREAK, OP_ENTER,
OP_LEAVE, OP_CALL, OP_PUSH, OP_POP,
OP_CONST, OP_LOCAL, OP_JUMP, OP_EQ,
OP_NE, OP_LTI, OP_LEI, OP_GTI,
OP_GEI, OP_LTU, OP_LEU, OP_GTU,
OP_GEU, OP_EQF, OP_NEF, OP_LTF,
OP_LEF, OP_GTF, OP_GEF, OP_LOAD1,
OP_LOAD2, OP_LOAD4, OP_STORE1, OP_STORE2,
OP_STORE4, OP_ARG, OP_BLOCK_COPY, OP_SEX8,
OP_SEX16, OP_NEGI, OP_ADD, OP_SUB,
OP_DIVI, OP_DIVU, OP_MODI, OP_MODU,
OP_MULI, OP_MULU, OP_BAND, OP_BOR,
OP_BXOR, OP_BCOM, OP_LSH, OP_RSHI,
OP_RSHU, OP_NEGF, OP_ADDF, OP_SUBF,
OP_DIVF, OP_MULF, OP_CVIF, OP_CVFI
}
enum segmentName_t {
CODESEG, DATASEG, LITSEG, BSSSEG,
JTRGSEG, NUM_SEGMENTS
}
Functions
ASM (ADDRESS)
ASM (ADDRF)
ASM (ADDRL)
ASM (ALIGN)
ASM (ARG)
ASM (BSS)
ASM (BYTE)
ASM (CALL)
ASM (CODE)
ASM (DATA)
ASM (ENDPROC)
ASM (EQU)
ASM (EXPORT)
ASM (FILE)
ASM (IMPORT)
ASM (LABEL)
ASM (LINE)
ASM (LIT)
ASM (POP)
ASM (PROC)
ASM (RET)
ASM (SKIP)
static void Assemble (void)
static void AssembleLine (void)
static int atoiNoCap (const char *s)
static void CodeError (char *fmt,...)
static void DefineSymbol (char *sym, int value)
static void EmitByte (segment_t *seg, int v)
static void EmitInt (segment_t *seg, int v)
static char * ExtractLine (char *data)
static void HackToSegment (segmentName_t seg)
static unsigned int HashString (const char *key)
static void hashtable_add (hashtable_t *H, int hashvalue, void *datum)
static hashchain_t * hashtable_get (hashtable_t *H, int hashvalue)
static void hashtable_init (hashtable_t *H, int buckets)
static hashtable_t * hashtable_new (int buckets)
static void hashtable_stats (hashtable_t *H)
static int hashtable_symbol_exists (hashtable_t *H, int hash, char *sym)
void InitTables (void)
static int LookupSymbol (char *sym)
int main (int argc, char **argv)
static qboolean Parse (void)
static int ParseExpression (void)
static void ParseOptionFile (const char *filename)
static int ParseValue (void)
static int report (const char *fmt,...)
static void ShowHelp (char *argv0)
static void sort_symbols ()
static int symlist_cmp (const void *e1, const void *e2)
static int vreport (const char *fmt, va_list vp)
static void WriteMapFile (void)
static void WriteVmFile (void)
Variables
char * asmFileNames [MAX_ASM_FILES]
char * asmFiles [MAX_ASM_FILES]
int currentArgOffset
int currentArgs
int currentFileIndex
int currentFileLine
char * currentFileName
int currentLocals
segment_t * currentSegment
int errorCount
int instructionCount
symbol_t * lastSymbol = 0
char lineBuffer [MAX_LINE_LENGTH]
int lineParseOffset
int numAsmFiles
int numSymbols
int opcodesHash [NUM_SOURCE_OPS]
hashtable_t * optable
options_t options = { 0 }
char outputFilename [MAX_OS_PATH]
int passNumber
segment_t segment [NUM_SEGMENTS]
sourceOps_t sourceOps []
int stackSize = 0x10000
symbol_t * symbols
hashtable_t * symtable
int symtablelen = DEFAULT_HASHTABLE_SIZE
char token [MAX_LINE_LENGTH]
Macro Definition Documentation
ASM [1/2]
#define ASM (O) int TryAssemble##O ()
Definition at line 823 of file q3asm.c.
ASM [2/2]
#define ASM (O) if (TryAssemble##O ()) return;
Definition at line 823 of file q3asm.c.
atoi64
#define atoi64 atoll
Definition at line 423 of file q3asm.c.
DEFAULT_HASHTABLE_SIZE
#define DEFAULT_HASHTABLE_SIZE 2048
Definition at line 29 of file q3asm.c.
INT64
#define INT64 long long int
Definition at line 422 of file q3asm.c.
MAX_ASM_FILES
#define MAX_ASM_FILES 256
Definition at line 188 of file q3asm.c.
MAX_IMAGE
#define MAX_IMAGE 0x400000
Definition at line 138 of file q3asm.c.
MAX_LINE_LENGTH
#define MAX_LINE_LENGTH 1024
Definition at line 207 of file q3asm.c.
NUM_SOURCE_OPS
#define NUM_SOURCE_OPS (sizeof(sourceOps) / sizeof(sourceOps[0]))
Definition at line 223 of file q3asm.c.
STAT
#define STAT (L)
Definition at line 822 of file q3asm.c.
ZERO_PAGE_SIZE
#define ZERO_PAGE_SIZE 0
Definition at line 34 of file q3asm.c.
Enumeration Type Documentation
opcode_t
enum opcode_t
Enumerator
OP_UNDEF
OP_IGNORE
OP_BREAK
OP_ENTER
OP_LEAVE
OP_CALL
OP_PUSH
OP_POP
OP_CONST
OP_LOCAL
OP_JUMP
OP_EQ
OP_NE
OP_LTI
OP_LEI
OP_GTI
OP_GEI
OP_LTU
OP_LEU
OP_GTU
OP_GEU
OP_EQF
OP_NEF
OP_LTF
OP_LEF
OP_GTF
OP_GEF
OP_LOAD1
OP_LOAD2
OP_LOAD4
OP_STORE1
OP_STORE2
OP_STORE4
OP_ARG
OP_BLOCK_COPY
OP_SEX8
OP_SEX16
OP_NEGI
OP_ADD
OP_SUB
OP_DIVI
OP_DIVU
OP_MODI
OP_MODU
OP_MULI
OP_MULU
OP_BAND
OP_BOR
OP_BXOR
OP_BCOM
OP_LSH
OP_RSHI
OP_RSHU
OP_NEGF
OP_ADDF
OP_SUBF
OP_DIVF
OP_MULF
OP_CVIF
OP_CVFI
OP_UNDEF
OP_IGNORE
OP_BREAK
OP_ENTER
OP_LEAVE
OP_CALL
OP_PUSH
OP_POP
OP_CONST
OP_LOCAL
OP_JUMP
OP_EQ
OP_NE
OP_LTI
OP_LEI
OP_GTI
OP_GEI
OP_LTU
OP_LEU
OP_GTU
OP_GEU
OP_EQF
OP_NEF
OP_LTF
OP_LEF
OP_GTF
OP_GEF
OP_LOAD1
OP_LOAD2
OP_LOAD4
OP_STORE1
OP_STORE2
OP_STORE4
OP_ARG
OP_BLOCK_COPY
OP_SEX8
OP_SEX16
OP_NEGI
OP_ADD
OP_SUB
OP_DIVI
OP_DIVU
OP_MODI
OP_MODU
OP_MULI
OP_MULU
OP_BAND
OP_BOR
OP_BXOR
OP_BCOM
OP_LSH
OP_RSHI
OP_RSHU
OP_NEGF
OP_ADDF
OP_SUBF
OP_DIVF
OP_MULF
OP_CVIF
OP_CVFI
Definition at line 36 of file q3asm.c.
              {
     OP_UNDEF,
     OP_IGNORE,
     OP_BREAK,
     OP_ENTER,
     OP_LEAVE,
     OP_CALL,
     OP_PUSH,
     OP_POP,
     OP_CONST,
     OP_LOCAL,
     OP_JUMP,
     //-------------------
     OP_EQ,
     OP_NE,
     OP_LTI,
     OP_LEI,
     OP_GTI,
     OP_GEI,
     OP_LTU,
     OP_LEU,
     OP_GTU,
     OP_GEU,
     OP_EQF,
     OP_NEF,
     OP_LTF,
     OP_LEF,
     OP_GTF,
     OP_GEF,
     //-------------------
     OP_LOAD1,
     OP_LOAD2,
     OP_LOAD4,
     OP_STORE1,
     OP_STORE2,
     OP_STORE4,              // *(stack[top-1]) = stack[yop
     OP_ARG,
     OP_BLOCK_COPY,
     //-------------------
     OP_SEX8,
     OP_SEX16,
     OP_NEGI,
     OP_ADD,
     OP_SUB,
     OP_DIVI,
     OP_DIVU,
     OP_MODI,
     OP_MODU,
     OP_MULI,
     OP_MULU,
     OP_BAND,
     OP_BOR,
     OP_BXOR,
     OP_BCOM,
     OP_LSH,
     OP_RSHI,
     OP_RSHU,
     OP_NEGF,
     OP_ADDF,
     OP_SUBF,
     OP_DIVF,
     OP_MULF,
     OP_CVIF,
     OP_CVFI
 } opcode_t;
segmentName_t
enum segmentName_t
Enumerator
CODESEG
DATASEG
LITSEG
BSSSEG
JTRGSEG
NUM_SEGMENTS
Definition at line 129 of file q3asm.c.
              {
     CODESEG,
     DATASEG,    // initialized 32 bit data, will be byte swapped
     LITSEG,     // strings
     BSSSEG,     // 0 filled
     JTRGSEG,    // pseudo-segment that contains only jump table targets
     NUM_SEGMENTS
 } segmentName_t;
Function Documentation
ASM() [1/22]
ASM (ADDRESS)
Definition at line 973 of file q3asm.c.
 {
     int     v;
     if ( !strcmp( token, "address" ) ) {
 STAT("ADDRESS");
         Parse();
         v = ParseExpression();
 /* Addresses are 32 bits wide, and therefore go into data segment. */
         HackToSegment( DATASEG );
         EmitInt( currentSegment, v );
         if( passNumber == 1 && token[ 0 ] == '$' ) // crude test for labels
             EmitInt( &segment[ JTRGSEG ], v );
         return 1;
     }
     return 0;
 }
References currentSegment, DATASEG, EmitInt(), HackToSegment(), JTRGSEG, Parse(), ParseExpression(), passNumber, segment, and STAT.
ASM() [2/22]
ASM (ADDRF)
Definition at line 890 of file q3asm.c.
 {
     int     v;
     if ( !strncmp( token, "ADDRF", 5 ) ) {
 STAT("ADDRF");
         instructionCount++;
         Parse();
         v = ParseExpression();
         v = 16 + currentArgs + currentLocals + v;
         EmitByte( &segment[CODESEG], OP_LOCAL );
         EmitInt( &segment[CODESEG], v );
         return 1;
     }
     return 0;
 }
References CODESEG, currentArgs, currentLocals, EmitByte(), EmitInt(), instructionCount, OP_LOCAL, Parse(), ParseExpression(), segment, and STAT.
ASM() [3/22]
ASM (ADDRL)
Definition at line 907 of file q3asm.c.
 {
     int     v;
     if ( !strncmp( token, "ADDRL", 5 ) ) {
 STAT("ADDRL");
         instructionCount++;
         Parse();
         v = ParseExpression();
         v = 8 + currentArgs + v;
         EmitByte( &segment[CODESEG], OP_LOCAL );
         EmitInt( &segment[CODESEG], v );
         return 1;
     }
     return 0;
 }
References CODESEG, currentArgs, EmitByte(), EmitInt(), instructionCount, OP_LOCAL, Parse(), ParseExpression(), segment, and STAT.
ASM() [4/22]
ASM (ALIGN)
Definition at line 1081 of file q3asm.c.
 {
     int     v;
     if ( !strcmp( token, "align" ) ) {
 STAT("ALIGN");
         v = ParseValue();
         currentSegment->imageUsed = (currentSegment->imageUsed + v - 1 ) & ~( v - 1 );
         return 1;
     }
     return 0;
 }
References currentSegment, segment_t::imageUsed, ParseValue(), and STAT.
ASM() [5/22]
ASM (ARG)
Definition at line 846 of file q3asm.c.
 {
     if ( !strncmp( token, "ARG", 3 ) ) {
 STAT("ARG");
         EmitByte( &segment[CODESEG], OP_ARG );
         instructionCount++;
         if ( 8 + currentArgOffset >= 256 ) {
             CodeError( "currentArgOffset >= 256" );
             return 1;
         }
         EmitByte( &segment[CODESEG], 8 + currentArgOffset );
         currentArgOffset += 4;
         return 1;
     }
     return 0;
 }
References CodeError(), CODESEG, currentArgOffset, EmitByte(), instructionCount, OP_ARG, segment, and STAT.
ASM() [6/22]
ASM (BSS)
Definition at line 1019 of file q3asm.c.
 {
     if ( !strcmp( token, "bss" ) ) {
 STAT("BSS");
         currentSegment = &segment[BSSSEG];
         return 1;
     }
     return 0;
 }
References BSSSEG, currentSegment, segment, and STAT.
ASM() [7/22]
ASM (BYTE)
Definition at line 1105 of file q3asm.c.
 {
     int     i, v, v2;
     if ( !strcmp( token, "byte" ) ) {
 STAT("BYTE");
         v = ParseValue();
         v2 = ParseValue();
         if ( v == 1 ) {
 /* Character (1-byte) values go into lit(eral) segment. */
             HackToSegment( LITSEG );
         } else if ( v == 4 ) {
 /* 32-bit (4-byte) values go into data segment. */
             HackToSegment( DATASEG );
         } else if ( v == 2 ) {
 /* and 16-bit (2-byte) values will cause q3asm to barf. */
             CodeError( "16 bit initialized data not supported" );
         }
         // emit little endien
         for ( i = 0 ; i < v ; i++ ) {
             EmitByte( currentSegment, (v2 & 0xFF) ); /* paranoid ANDing  -PH */
             v2 >>= 8;
         }
         return 1;
     }
     return 0;
 }
References CodeError(), currentSegment, DATASEG, EmitByte(), HackToSegment(), LITSEG, ParseValue(), and STAT.
ASM() [8/22]
ASM (CALL)
Definition at line 833 of file q3asm.c.
 {
     if ( !strncmp( token, "CALL", 4 ) ) {
 STAT("CALL");
         EmitByte( &segment[CODESEG], OP_CALL );
         instructionCount++;
         currentArgOffset = 0;
         return 1;
     }
     return 0;
 }
References CODESEG, currentArgOffset, EmitByte(), instructionCount, OP_CALL, segment, and STAT.
ASM() [9/22]
ASM (CODE)
Definition at line 1009 of file q3asm.c.
 {
     if ( !strcmp( token, "code" ) ) {
 STAT("CODE");
         currentSegment = &segment[CODESEG];
         return 1;
     }
     return 0;
 }
References CODESEG, currentSegment, segment, and STAT.
ASM() [10/22]
ASM (DATA)
Definition at line 1029 of file q3asm.c.
 {
     if ( !strcmp( token, "data" ) ) {
 STAT("DATA");
         currentSegment = &segment[DATASEG];
         return 1;
     }
     return 0;
 }
References currentSegment, DATASEG, segment, and STAT.
ASM() [11/22]
ASM (ENDPROC)
Definition at line 951 of file q3asm.c.
 {
     if ( !strcmp( token, "endproc" ) ) {
 STAT("ENDPROC");
         Parse();                // skip the function name
         ParseValue();       // locals
         ParseValue();       // arg marshalling
         // all functions must leave something on the opstack
         instructionCount++;
         EmitByte( &segment[CODESEG], OP_PUSH );
         instructionCount++;
         EmitByte( &segment[CODESEG], OP_LEAVE );
         EmitInt( &segment[CODESEG], 8 + currentLocals + currentArgs );
         return 1;
     }
     return 0;
 }
References CODESEG, currentArgs, currentLocals, EmitByte(), EmitInt(), instructionCount, OP_LEAVE, OP_PUSH, Parse(), ParseValue(), segment, and STAT.
ASM() [12/22]
ASM (EQU)
Definition at line 1067 of file q3asm.c.
 {
     char    name[1024];
     if ( !strcmp( token, "equ" ) ) {
 STAT("EQU");
         Parse();
         strcpy( name, token );
         Parse();
         DefineSymbol( name, atoiNoCap(token) );
         return 1;
     }
     return 0;
 }
References atoiNoCap(), DefineSymbol(), Parse(), and STAT.
ASM() [13/22]
ASM (EXPORT)
Definition at line 991 of file q3asm.c.
 {
     if ( !strcmp( token, "export" ) ) {
 STAT("EXPORT");
         return 1;
     }
     return 0;
 }
References STAT.
ASM() [14/22]
ASM (FILE)
Definition at line 1058 of file q3asm.c.
 {
     if ( !strcmp( token, "file" ) ) {
 STAT("FILE");
         return 1;
     }
     return 0;
 }
References STAT.
ASM() [15/22]
ASM (IMPORT)
Definition at line 1000 of file q3asm.c.
 {
     if ( !strcmp( token, "import" ) ) {
 STAT("IMPORT");
         return 1;
     }
     return 0;
 }
References STAT.
ASM() [16/22]
ASM (LABEL)
Definition at line 1138 of file q3asm.c.
 {
     if ( !strncmp( token, "LABEL", 5 ) ) {
 STAT("LABEL");
         Parse();
         if ( currentSegment == &segment[CODESEG] ) {
             DefineSymbol( token, instructionCount );
         } else {
             DefineSymbol( token, currentSegment->imageUsed );
         }
         return 1;
     }
     return 0;
 }
References CODESEG, currentSegment, DefineSymbol(), segment_t::imageUsed, instructionCount, Parse(), segment, and STAT.
ASM() [17/22]
ASM (LINE)
Definition at line 1049 of file q3asm.c.
 {
     if ( !strcmp( token, "line" ) ) {
 STAT("LINE");
         return 1;
     }
     return 0;
 }
References STAT.
ASM() [18/22]
ASM (LIT)
Definition at line 1039 of file q3asm.c.
 {
     if ( !strcmp( token, "lit" ) ) {
 STAT("LIT");
         currentSegment = &segment[LITSEG];
         return 1;
     }
     return 0;
 }
References currentSegment, LITSEG, segment, and STAT.
ASM() [19/22]
ASM (POP)
Definition at line 878 of file q3asm.c.
 {
     if ( !strncmp( token, "pop", 3 ) ) {
 STAT("POP");
         EmitByte( &segment[CODESEG], OP_POP );
         instructionCount++;
         return 1;
     }
     return 0;
 }
References CODESEG, EmitByte(), instructionCount, OP_POP, segment, and STAT.
ASM() [20/22]
ASM (PROC)
Definition at line 923 of file q3asm.c.
 {
     char    name[1024];
     if ( !strcmp( token, "proc" ) ) {
 STAT("PROC");
         Parse();                    // function name
         strcpy( name, token );
         DefineSymbol( token, instructionCount ); // segment[CODESEG].imageUsed );
         currentLocals = ParseValue();   // locals
         currentLocals = ( currentLocals + 3 ) & ~3;
         currentArgs = ParseValue();     // arg marshalling
         currentArgs = ( currentArgs + 3 ) & ~3;
         if ( 8 + currentLocals + currentArgs >= 32767 ) {
             CodeError( "Locals > 32k in %s\n", name );
         }
         instructionCount++;
         EmitByte( &segment[CODESEG], OP_ENTER );
         EmitInt( &segment[CODESEG], 8 + currentLocals + currentArgs );
         return 1;
     }
     return 0;
 }
References CodeError(), CODESEG, currentArgs, currentLocals, DefineSymbol(), EmitByte(), EmitInt(), instructionCount, OP_ENTER, Parse(), ParseValue(), segment, and STAT.
ASM() [21/22]
ASM (RET)
Definition at line 864 of file q3asm.c.
 {
     if ( !strncmp( token, "RET", 3 ) ) {
 STAT("RET");
         EmitByte( &segment[CODESEG], OP_LEAVE );
         instructionCount++;
         EmitInt( &segment[CODESEG], 8 + currentLocals + currentArgs );
         return 1;
     }
     return 0;
 }
References CODESEG, currentArgs, currentLocals, EmitByte(), EmitInt(), instructionCount, OP_LEAVE, segment, and STAT.
ASM() [22/22]
ASM (SKIP)
Definition at line 1093 of file q3asm.c.
 {
     int     v;
     if ( !strcmp( token, "skip" ) ) {
 STAT("SKIP");
         v = ParseValue();
         currentSegment->imageUsed += v;
         return 1;
     }
     return 0;
 }
References currentSegment, segment_t::imageUsed, ParseValue(), and STAT.
Assemble()
static void Assemble (void) static
Definition at line 1427 of file q3asm.c.
{
     int     i;
     char    filename[MAX_OS_PATH];
     char        *ptr;
     report( "outputFilename: %s\n", outputFilename );
     for ( i = 0 ; i < numAsmFiles ; i++ ) {
         strcpy( filename, asmFileNames[ i ] );
         DefaultExtension( filename, ".asm" );
         LoadFile( filename, (void **)&asmFiles[i] );
     }
     // assemble
     for ( passNumber = 0 ; passNumber < 2 ; passNumber++ ) {
         segment[LITSEG].segmentBase = segment[DATASEG].imageUsed;
         segment[BSSSEG].segmentBase = segment[LITSEG].segmentBase + segment[LITSEG].imageUsed;
         segment[JTRGSEG].segmentBase = segment[BSSSEG].segmentBase + segment[BSSSEG].imageUsed;
         for ( i = 0 ; i < NUM_SEGMENTS ; i++ ) {
             segment[i].imageUsed = 0;
         }
         segment[DATASEG].imageUsed = 4;     // skip the 0 byte, so NULL pointers are fixed up properly
         instructionCount = 0;
         for ( i = 0 ; i < numAsmFiles ; i++ ) {
             currentFileIndex = i;
             currentFileName = asmFileNames[ i ];
             currentFileLine = 0;
             report("pass %i: %s\n", passNumber, currentFileName );
             fflush( NULL );
             ptr = asmFiles[i];
             while ( ptr ) {
                 ptr = ExtractLine( ptr );
                 AssembleLine();
             }
         }
         // align all segment
         for ( i = 0 ; i < NUM_SEGMENTS ; i++ ) {
             segment[i].imageUsed = (segment[i].imageUsed + 3) & ~3;
         }
         if (passNumber == 0) {
             sort_symbols();
         }
     }
     // reserve the stack in bss
     DefineSymbol( "_stackStart", segment[BSSSEG].imageUsed );
     segment[BSSSEG].imageUsed += stackSize;
     DefineSymbol( "_stackEnd", segment[BSSSEG].imageUsed );
     // write the image
     WriteVmFile();
     // write the map file even if there were errors
     if( options.writeMapFile ) {
         WriteMapFile();
     }
 }
References asmFileNames, asmFiles, AssembleLine(), BSSSEG, currentFileIndex, currentFileLine, currentFileName, DATASEG, DefaultExtension(), DefineSymbol(), ExtractLine(), segment_t::imageUsed, instructionCount, JTRGSEG, LITSEG, LoadFile(), MAX_OS_PATH, NULL, NUM_SEGMENTS, numAsmFiles, options, outputFilename, passNumber, ptr(), report(), segment, segment_t::segmentBase, sort_symbols(), stackSize, WriteMapFile(), and WriteVmFile().
Referenced by main().
AssembleLine()
static void AssembleLine (void) static
Definition at line 1161 of file q3asm.c.
{
     hashchain_t *hc;
     sourceOps_t *op;
     int     i;
     int     hash;
     Parse();
     if ( !token[0] ) {
         return;
     }
     hash = HashString( token );
 /*
   Opcode search using hash table.
   Since the opcodes stays mostly fixed, this may benefit even more from a tree.
   Always with the tree :)
  -PH
 */
     for (hc = hashtable_get(optable, hash); hc; hc = hc->next) {
         op = (sourceOps_t*)(hc->data);
         i = op - sourceOps;
         if ((hash == opcodesHash[i]) && (!strcmp(token, op->name))) {
             int     opcode;
             int     expression;
             if ( op->opcode == OP_UNDEF ) {
                 CodeError( "Undefined opcode: %s\n", token );
             }
             if ( op->opcode == OP_IGNORE ) {
                 return;     // we ignore most conversions
             }
             // sign extensions need to check next parm
             opcode = op->opcode;
             if ( opcode == OP_SEX8 ) {
                 Parse();
                 if ( token[0] == '1' ) {
                     opcode = OP_SEX8;
                 } else if ( token[0] == '2' ) {
                     opcode = OP_SEX16;
                 } else {
                     CodeError( "Bad sign extension: %s\n", token );
                     return;
                 }
             }
             // check for expression
             Parse();
             if ( token[0] && op->opcode != OP_CVIF
                     && op->opcode != OP_CVFI ) {
                 expression = ParseExpression();
                 // code like this can generate non-dword block copies:
                 // auto char buf[2] = " ";
                 // we are just going to round up.  This might conceivably
                 // be incorrect if other initialized chars follow.
                 if ( opcode == OP_BLOCK_COPY ) {
                     expression = ( expression + 3 ) & ~3;
                 }
                 EmitByte( &segment[CODESEG], opcode );
                 EmitInt( &segment[CODESEG], expression );
             } else {
                 EmitByte( &segment[CODESEG], opcode );
             }
             instructionCount++;
             return;
         }
     }
 /* This falls through if an assembly opcode is not found.  -PH */
 /* The following should be sorted in sequence of statistical frequency, most frequent first.  -PH */
 /*
 Empirical frequency statistics from FI 2001.01.23:
  109892 STAT ADDRL
   72188 STAT BYTE
   51150 STAT LINE
   50906 STAT ARG
   43704 STAT IMPORT
   34902 STAT LABEL
   32066 STAT ADDRF
   23704 STAT CALL
    7720 STAT POP
    7256 STAT RET
    5198 STAT ALIGN
    3292 STAT EXPORT
    2878 STAT PROC
    2878 STAT ENDPROC
    2812 STAT ADDRESS
     738 STAT SKIP
     374 STAT EQU
     280 STAT CODE
     176 STAT LIT
     102 STAT FILE
     100 STAT BSS
      68 STAT DATA
  -PH
 */
 #undef ASM
 #define ASM(O) if (TryAssemble##O ()) return;
     ASM(ADDRL)
     ASM(BYTE)
     ASM(LINE)
     ASM(ARG)
     ASM(IMPORT)
     ASM(LABEL)
     ASM(ADDRF)
     ASM(CALL)
     ASM(POP)
     ASM(RET)
     ASM(ALIGN)
     ASM(EXPORT)
     ASM(PROC)
     ASM(ENDPROC)
     ASM(ADDRESS)
     ASM(SKIP)
     ASM(EQU)
     ASM(CODE)
     ASM(LIT)
     ASM(FILE)
     ASM(BSS)
     ASM(DATA)
     CodeError( "Unknown token: %s\n", token );
 }
References ALIGN, ASM, BSS, CALL, CODE, CodeError(), CODESEG, DATA, EmitByte(), EmitInt(), EXPORT, hash(), HashString(), hashtable_get(), instructionCount, LIT, op, OP_BLOCK_COPY, OP_CVFI, OP_CVIF, OP_IGNORE, OP_SEX16, OP_SEX8, OP_UNDEF, opcodesHash, optable, Parse(), ParseExpression(), segment, and sourceOps.
Referenced by Assemble().
atoiNoCap()
static int atoiNoCap (const char * s) static
Definition at line 436 of file q3asm.c.
 {
   INT64 l;
   union {
     unsigned int u;
     signed int i;
   } retval;
   l = atoi64(s);
   /* Now smash to signed 32 bits accordingly. */
   if (l < 0) {
     retval.i = (int)l;
   } else {
     retval.u = (unsigned int)l;
   }
   return retval.i;  /* <- union hackage.  I feel dirty with this.  -PH */
 }
References atoi64, int(), and INT64.
Referenced by ASM(), main(), ParseExpression(), and ParseValue().
CodeError()
static void CodeError (char * fmt, ...) static
Definition at line 491 of file q3asm.c.
{
     va_list     argptr;
     errorCount++;
     fprintf( stderr, "%s:%i ", currentFileName, currentFileLine );
     va_start( argptr,fmt );
     vfprintf( stderr, fmt, argptr );
     va_end( argptr );
 }
References currentFileLine, currentFileName, errorCount, and fmt.
Referenced by ASM(), AssembleLine(), DefineSymbol(), ExtractLine(), and LookupSymbol().
DefineSymbol()
static void DefineSymbol (char * sym, int value) static
Definition at line 539 of file q3asm.c.
{
     /* Hand optimization by PhaethonH */
     symbol_t    *s;
     char        expanded[MAX_LINE_LENGTH];
     int         hash;
     if ( passNumber == 1 ) {
         return;
     }
     // add the file prefix to local symbols to guarantee unique
     if ( sym[0] == '$' ) {
         sprintf( expanded, "%s_%i", sym, currentFileIndex );
         sym = expanded;
     }
     hash = HashString( sym );
     if (hashtable_symbol_exists(symtable, hash, sym)) {
         CodeError( "Multiple definitions for %s\n", sym );
         return;
     }
     s = malloc( sizeof( *s ) );
     s->next = NULL;
     s->name = copystring( sym );
     s->hash = hash;
     s->value = value;
     s->segment = currentSegment;
     hashtable_add(symtable, hash, s);
 /*
   Hash table lookup already speeds up symbol lookup enormously.
   We postpone sorting until end of pass 0.
   Since we're not doing the insertion sort, lastSymbol should always
    wind up pointing to the end of list.
   This allows constant time for adding to the list.
  -PH
 */
     if (symbols == 0) {
         lastSymbol = symbols = s;
     } else {
         lastSymbol->next = s;
         lastSymbol = s;
     }
 }
References CodeError(), copystring(), currentFileIndex, currentSegment, hash(), HashString(), hashtable_add(), hashtable_symbol_exists(), lastSymbol, MAX_LINE_LENGTH, NULL, passNumber, symbols, and symtable.
Referenced by ASM(), Assemble(), and LookupSymbol().
EmitByte()
static void EmitByte (segment_t * seg, int v) static
Definition at line 508 of file q3asm.c.
{
     if ( seg->imageUsed >= MAX_IMAGE ) {
         Error( "MAX_IMAGE" );
     }
     seg->image[ seg->imageUsed ] = v;
     seg->imageUsed++;
 }
References Error(), segment_t::image, segment_t::imageUsed, and MAX_IMAGE.
Referenced by ASM(), and AssembleLine().
EmitInt()
static void EmitInt (segment_t * seg, int v) static
Definition at line 521 of file q3asm.c.
{
     if ( seg->imageUsed >= MAX_IMAGE - 4) {
         Error( "MAX_IMAGE" );
     }
     seg->image[ seg->imageUsed ] = v & 255;
     seg->image[ seg->imageUsed + 1 ] = ( v >> 8 ) & 255;
     seg->image[ seg->imageUsed + 2 ] = ( v >> 16 ) & 255;
     seg->image[ seg->imageUsed + 3 ] = ( v >> 24 ) & 255;
     seg->imageUsed += 4;
 }
References Error(), segment_t::image, segment_t::imageUsed, and MAX_IMAGE.
Referenced by ASM(), and AssembleLine().
ExtractLine()
static char* ExtractLine (char * data) static
Definition at line 643 of file q3asm.c.
{
 /* Goal:
      Given a string `data', extract one text line into buffer `lineBuffer' that
      is no longer than MAX_LINE_LENGTH characters long.  Return value is
      remainder of `data' that isn't part of `lineBuffer'.
  -PH
 */
     /* Hand-optimized by PhaethonH */
     char    *p, *q;
     currentFileLine++;
     lineParseOffset = 0;
     token[0] = 0;
     *lineBuffer = 0;
     p = q = data;
     if (!*q) {
         return NULL;
     }
     for ( ; !((*p == 0) || (*p == '\n')); p++)  /* nop */ ;
     if ((p - q) >= MAX_LINE_LENGTH) {
         CodeError( "MAX_LINE_LENGTH" );
         return data;
     }
     memcpy( lineBuffer, data, (p - data) );
     lineBuffer[(p - data)] = 0;
     p += (*p == '\n') ? 1 : 0;  /* Skip over final newline. */
     return p;
 }
References CodeError(), currentFileLine, lineBuffer, lineParseOffset, MAX_LINE_LENGTH, and NULL.
Referenced by Assemble().
HackToSegment()
static void HackToSegment (segmentName_t seg) static
Definition at line 803 of file q3asm.c.
{
     if ( currentSegment == &segment[seg] ) {
         return;
     }
     currentSegment = &segment[seg];
     if ( passNumber == 0 ) {
         lastSymbol->segment = currentSegment;
         lastSymbol->value = currentSegment->imageUsed;
     }
 }
References currentSegment, segment_t::imageUsed, lastSymbol, passNumber, and segment.
Referenced by ASM().
HashString()
static unsigned int HashString (const char * key) static
Definition at line 462 of file q3asm.c.
 {
     static unsigned long randbox[] = {
     0x49848f1bU, 0xe6255dbaU, 0x36da5bdcU, 0x47bf94e9U,
     0x8cbcce22U, 0x559fc06aU, 0xd268f536U, 0xe10af79aU,
     0xc1af4d69U, 0x1d2917b5U, 0xec4c304dU, 0x9ee5016cU,
     0x69232f74U, 0xfead7bb3U, 0xe9089ab6U, 0xf012f6aeU,
     };
     const char *str = key;
     unsigned int acc = 0;
     while (*str) {
     acc ^= randbox[(*str + acc) & 0xf];
     acc = (acc << 1) | (acc >> 31);
     acc &= 0xffffffffU;
     acc ^= randbox[((*str++ >> 4) + acc) & 0xf];
     acc = (acc << 2) | (acc >> 30);
     acc &= 0xffffffffU;
     }
     return abs(acc);
 }
References U.
Referenced by AssembleLine(), DefineSymbol(), InitTables(), and LookupSymbol().
hashtable_add()
static void hashtable_add (hashtable_t * H, int hashvalue, void * datum) static
Definition at line 267 of file q3asm.c.
 {
   hashchain_t *hc, **hb;
   hashvalue = (abs(hashvalue) % H->buckets);
   hb = &(H->table[hashvalue]);
   if (*hb == 0)
     {
       /* Empty bucket.  Create new one. */
       *hb = calloc(1, sizeof(**hb));
       hc = *hb;
     }
   else
     {
       /* Get hc to point to last node in chain. */
       for (hc = *hb; hc && hc->next; hc = hc->next);
       hc->next = calloc(1, sizeof(*hc));
       hc = hc->next;
     }
   hc->data = datum;
   hc->next = 0;
   return;
 }
References H.
Referenced by DefineSymbol(), and InitTables().
hashtable_get()
static hashchain_t* hashtable_get (hashtable_t * H, int hashvalue) static
Definition at line 291 of file q3asm.c.
 {
   hashvalue = (abs(hashvalue) % H->buckets);
   return (H->table[hashvalue]);
 }
References H.
Referenced by AssembleLine(), and LookupSymbol().
hashtable_init()
static void hashtable_init (hashtable_t * H, int buckets) static
Definition at line 249 of file q3asm.c.
 {
   H->buckets = buckets;
   H->table = calloc(H->buckets, sizeof(*(H->table)));
   return;
 }
References buckets, and H.
Referenced by hashtable_new().
hashtable_new()
static hashtable_t* hashtable_new (int buckets) static
Definition at line 256 of file q3asm.c.
 {
   hashtable_t *H;
   H = malloc(sizeof(hashtable_t));
   hashtable_init(H, buckets);
   return H;
 }
References buckets, H, and hashtable_init().
Referenced by InitTables().
hashtable_stats()
static void hashtable_stats (hashtable_t * H) static
Definition at line 297 of file q3asm.c.
 {
   int len, empties, longest, nodes;
   int i;
   float meanlen;
   hashchain_t *hc;
   report("Stats for hashtable %08X", H);
   empties = 0;
   longest = 0;
   nodes = 0;
   for (i = 0; i < H->buckets; i++)
     {
       if (H->table[i] == 0)
         { empties++; continue; }
       for (hc = H->table[i], len = 0; hc; hc = hc->next, len++);
       if (len > longest) { longest = len; }
       nodes += len;
     }
   meanlen = (float)(nodes) / (H->buckets - empties);
 #if 0
 /* Long stats display */
   report(" Total buckets: %d\n", H->buckets);
   report(" Total stored nodes: %d\n", nodes);
   report(" Longest chain: %d\n", longest);
   report(" Empty chains: %d\n", empties);
   report(" Mean non-empty chain length: %f\n", meanlen);
 #else //0
 /* Short stats display */
   report(", %d buckets, %d nodes", H->buckets, nodes);
   report("\n");
   report(" Longest chain: %d, empty chains: %d, mean non-empty: %f", longest, empties, meanlen);
 #endif //0
   report("\n");
 }
References H, and report().
Referenced by main().
hashtable_symbol_exists()
static int hashtable_symbol_exists (hashtable_t * H, int hash, char * sym) static
Definition at line 337 of file q3asm.c.
 {
   hashchain_t *hc;
   symbol_t *s;
   hash = (abs(hash) % H->buckets);
   hc = H->table[hash];
   if (hc == 0)
     {
       /* Empty chain means this symbol has not yet been defined. */
       return 0;
     }
   for (; hc; hc = hc->next)
     {
       s = (symbol_t*)hc->data;
 //      if ((hash == s->hash) && (strcmp(sym, s->name) == 0))
 /* We _already_ know the hash is the same.  That's why we're probing! */
       if (strcmp(sym, s->name) == 0)
         {
           /* Symbol collisions -- symbol already exists. */
           return 1;
         }
     }
   return 0;  /* Can't find collision. */
 }
References H, and hash().
Referenced by DefineSymbol().
InitTables()
void InitTables (void)
Definition at line 1298 of file q3asm.c.
{
     int i;
     symtable = hashtable_new(symtablelen);
     optable = hashtable_new(100);  /* There's hardly 100 opcodes anyway. */
     for ( i = 0 ; i < NUM_SOURCE_OPS ; i++ ) {
         opcodesHash[i] = HashString( sourceOps[i].name );
         hashtable_add(optable, opcodesHash[i], sourceOps + i);
     }
 }
References HashString(), hashtable_add(), hashtable_new(), NUM_SOURCE_OPS, opcodesHash, optable, sourceOps, symtable, and symtablelen.
Referenced by main().
LookupSymbol()
static int LookupSymbol (char * sym) static
Definition at line 595 of file q3asm.c.
{
     symbol_t    *s;
     char        expanded[MAX_LINE_LENGTH];
     int         hash;
     hashchain_t *hc;
     if ( passNumber == 0 ) {
         return 0;
     }
     // add the file prefix to local symbols to guarantee unique
     if ( sym[0] == '$' ) {
         sprintf( expanded, "%s_%i", sym, currentFileIndex );
         sym = expanded;
     }
     hash = HashString( sym );
 /*
   Hand optimization by PhaethonH
   Using a hash table with chain/bucket for lookups alone sped up q3asm by almost 3x for me.
  -PH
 */
     for (hc = hashtable_get(symtable, hash); hc; hc = hc->next) {
         s = (symbol_t*)hc->data;  /* ugly typecasting, but it's fast! */
         if ( (hash == s->hash) && !strcmp(sym, s->name) ) {
             return s->segment->segmentBase + s->value;
         }
     }
     CodeError( "error: symbol %s undefined\n", sym );
     passNumber = 0;
     DefineSymbol( sym, 0 ); // so more errors aren't printed
     passNumber = 1;
     return 0;
 }
References CodeError(), currentFileIndex, DefineSymbol(), hash(), HashString(), hashtable_get(), MAX_LINE_LENGTH, passNumber, and symtable.
Referenced by ParseExpression().
main()
int main (int argc, char ** argv)
Definition at line 1541 of file q3asm.c.
{
     int         i;
     double      start, end;
 //  _chdir( "/quake3/jccode/cgame/lccout" );    // hack for vc profiler
     if ( argc < 2 ) {
         ShowHelp( argv[0] );
     }
     start = I_FloatTime ();
     // default filename is "q3asm"
     strcpy( outputFilename, "q3asm" );
     numAsmFiles = 0;
     for ( i = 1 ; i < argc ; i++ ) {
         if ( argv[i][0] != '-' ) {
             break;
         }
         if( !strcmp( argv[ i ], "-h" ) ||
             !strcmp( argv[ i ], "--help" ) ||
             !strcmp( argv[ i ], "-?") ) {
             ShowHelp( argv[0] );
         }
         if ( !strcmp( argv[i], "-o" ) ) {
             if ( i == argc - 1 ) {
                 Error( "-o must preceed a filename" );
             }
 /* Timbo of Tremulous pointed out -o not working; stock ID q3asm folded in the change. Yay. */
             strcpy( outputFilename, argv[ i+1 ] );
             i++;
             continue;
         }
         if ( !strcmp( argv[i], "-f" ) ) {
             if ( i == argc - 1 ) {
                 Error( "-f must preceed a filename" );
             }
             ParseOptionFile( argv[ i+1 ] );
             i++;
             continue;
         }
         if (!strcmp(argv[i], "-b")) {
             if (i == argc - 1) {
                 Error("-b requires an argument");
             }
             i++;
             symtablelen = atoiNoCap(argv[i]);
             continue;
         }
         if( !strcmp( argv[ i ], "-v" ) ) {
 /* Verbosity option added by Timbo, 2002.09.14.
 By default (no -v option), q3asm remains silent except for critical errors.
 Verbosity turns on all messages, error or not.
 Motivation: not wanting to scrollback for pages to find asm error.
 */
             options.verbose = qtrue;
             continue;
         }
         if( !strcmp( argv[ i ], "-m" ) ) {
             options.writeMapFile = qtrue;
             continue;
         }
         if( !strcmp( argv[ i ], "-vq3" ) ) {
             options.vanillaQ3Compatibility = qtrue;
             continue;
         }
         Error( "Unknown option: %s", argv[i] );
     }
     // the rest of the command line args are asm files
     for ( ; i < argc ; i++ ) {
         asmFileNames[ numAsmFiles ] = copystring( argv[ i ] );
         numAsmFiles++;
     }
     // In some case it Segfault without this check
     if ( numAsmFiles == 0 ) {
         Error( "No file to assemble\n" );
     }
     InitTables();
     Assemble();
     {
         symbol_t *s;
         for ( i = 0, s = symbols ; s ; s = s->next, i++ ) /* nop */ ;
         if (options.verbose)
         {
             report("%d symbols defined\n", i);
             hashtable_stats(symtable);
             hashtable_stats(optable);
         }
     }
     end = I_FloatTime ();
     report ("%5.0f seconds elapsed\n", end-start);
     return errorCount;
 }
References asmFileNames, Assemble(), atoiNoCap(), copystring(), Error(), errorCount, hashtable_stats(), I_FloatTime(), InitTables(), numAsmFiles, optable, options, outputFilename, ParseOptionFile(), qtrue, report(), ShowHelp(), symbols, symtable, and symtablelen.
Parse()
static qboolean Parse (void) static
Definition at line 685 of file q3asm.c.
{
     /* Hand-optimized by PhaethonH */
     const char  *p, *q;
     /* Because lineParseOffset is only updated just before exit, this makes this code version somewhat harder to debug under a symbolic debugger. */
     *token = 0;  /* Clear token. */
     // skip whitespace
     for (p = lineBuffer + lineParseOffset; *p && (*p <= ' '); p++) /* nop */ ;
     // skip ; comments
     /* die on end-of-string */
     if ((*p == ';') || (*p == 0)) {
         lineParseOffset = p - lineBuffer;
         return qfalse;
     }
     q = p;  /* Mark the start of token. */
     /* Find separator first. */
     for ( ; *p > 32; p++) /* nop */ ;  /* XXX: unsafe assumptions. */
     /* *p now sits on separator.  Mangle other values accordingly. */
     strncpy(token, q, p - q);
     token[p - q] = 0;
     lineParseOffset = p - lineBuffer;
     return qtrue;
 }
References lineBuffer, lineParseOffset, qfalse, and qtrue.
Referenced by ASM(), AssembleLine(), and ParseValue().
ParseExpression()
static int ParseExpression (void) static
Definition at line 732 of file q3asm.c.
{
     /* Hand optimization, PhaethonH */
     int     i, j;
     char    sym[MAX_LINE_LENGTH];
     int     v;
     /* Skip over a leading minus. */
     for ( i = ((token[0] == '-') ? 1 : 0) ; i < MAX_LINE_LENGTH ; i++ ) {
         if ( token[i] == '+' || token[i] == '-' || token[i] == 0 ) {
             break;
         }
     }
     memcpy( sym, token, i );
     sym[i] = 0;
     switch (*sym) {  /* Resolve depending on first character. */
 /* Optimizing compilers can convert cases into "calculated jumps".  I think these are faster.  -PH */
         case '-':
         case '0': case '1': case '2': case '3': case '4':
         case '5': case '6': case '7': case '8': case '9':
             v = atoiNoCap(sym);
             break;
         default:
             v = LookupSymbol(sym);
             break;
     }
     // parse add / subtract offsets
     while ( token[i] != 0 ) {
         for ( j = i + 1 ; j < MAX_LINE_LENGTH ; j++ ) {
             if ( token[j] == '+' || token[j] == '-' || token[j] == 0 ) {
                 break;
             }
         }
         memcpy( sym, token+i+1, j-i-1 );
         sym[j-i-1] = 0;
         switch (token[i]) {
             case '+':
                 v += atoiNoCap(sym);
                 break;
             case '-':
                 v -= atoiNoCap(sym);
                 break;
         }
         i = j;
     }
     return v;
 }
References atoiNoCap(), LookupSymbol(), and MAX_LINE_LENGTH.
Referenced by ASM(), and AssembleLine().
ParseOptionFile()
static void ParseOptionFile (const char * filename) static
Definition at line 1494 of file q3asm.c.
{
     char        expanded[MAX_OS_PATH];
     char        *text, *text_p;
     strcpy( expanded, filename );
     DefaultExtension( expanded, ".q3asm" );
     LoadFile( expanded, (void **)&text );
     if ( !text ) {
         return;
     }
     text_p = text;
     while( ( text_p = COM_Parse( text_p ) ) != 0 ) {
         if ( !strcmp( com_token, "-o" ) ) {
             // allow output override in option file
             text_p = COM_Parse( text_p );
             if ( text_p ) {
                 strcpy( outputFilename, com_token );
             }
             continue;
         }
         asmFileNames[ numAsmFiles ] = copystring( com_token );
         numAsmFiles++;
     }
 }
References asmFileNames, COM_Parse(), com_token, copystring(), DefaultExtension(), LoadFile(), MAX_OS_PATH, numAsmFiles, and outputFilename.
Referenced by main().
ParseValue()
static int ParseValue (void) static
Definition at line 721 of file q3asm.c.
{
     Parse();
     return atoiNoCap( token );
 }
References atoiNoCap(), and Parse().
Referenced by ASM().
report()
static int report (const char * fmt, ...) static
Definition at line 236 of file q3asm.c.
 {
   va_list va;
   int retval;
   va_start(va, fmt);
   retval = vreport(fmt, va);
   va_end(va);
   return retval;
 }
References fmt, va(), and vreport().
Referenced by Assemble(), hashtable_stats(), main(), WriteMapFile(), and WriteVmFile().
ShowHelp()
static void ShowHelp (char * argv0) static
Definition at line 1522 of file q3asm.c.
{
     Error("Usage: %s [OPTION]... [FILES]...\n\
 Assemble LCC bytecode assembly to Q3VM bytecode.\n\
 \n\
   -o OUTPUT      Write assembled output to file OUTPUT.qvm\n\
   -f LISTFILE    Read options and list of files to assemble from LISTFILE.q3asm\n\
   -b BUCKETS     Set symbol hash table to BUCKETS buckets\n\
   -m             Generate a mapfile for each OUTPUT.qvm\n\
   -v             Verbose compilation report\n\
   -vq3           Produce a qvm file compatible with Q3 1.32b\n\
   -h --help -?   Show this help\n\
 ", argv0);
 }
References Error().
Referenced by main().
sort_symbols()
static void sort_symbols () static
Definition at line 383 of file q3asm.c.
 {
   int i, elems;
   symbol_t *s;
   symbol_t **symlist;
   if(!symbols)
     return;
 //crumb("sort_symbols: Constructing symlist array\n");
   for (elems = 0, s = symbols; s; s = s->next, elems++) /* nop */ ;
   symlist = malloc(elems * sizeof(symbol_t*));
   for (i = 0, s = symbols; s; s = s->next, i++)
     {
       symlist[i] = s;
     }
 //crumbf("sort_symbols: Quick-sorting %d symbols\n", elems);
   qsort(symlist, elems, sizeof(symbol_t*), symlist_cmp);
 //crumbf("sort_symbols: Reconstructing symbols list\n");
   s = symbols = symlist[0];
   for (i = 1; i < elems; i++)
     {
       s->next = symlist[i];
       s = s->next;
     }
   lastSymbol = s;
   s->next = 0;
 //crumbf("sort_symbols: verifying..."); fflush(stdout);
   for (i = 0, s = symbols; s; s = s->next, i++) /*nop*/ ;
 //crumbf(" %d elements\n", i);
   free(symlist);  /* d'oh.  no gc. */
 }
References lastSymbol, symbols, and symlist_cmp().
Referenced by Assemble().
symlist_cmp()
static int symlist_cmp (const void * e1, const void * e2) static
Definition at line 367 of file q3asm.c.
 {
   const symbol_t *a, *b;
   a = *(const symbol_t **)e1;
   b = *(const symbol_t **)e2;
 //crumb("Symbol comparison (1) %d  to  (2) %d\n", a->value, b->value);
   return ( a->value - b->value);
 }
Referenced by sort_symbols().
vreport()
static int vreport (const char * fmt, va_list vp) static
Definition at line 229 of file q3asm.c.
 {
   if (options.verbose != qtrue)
       return 0;
   return vprintf(fmt, vp);
 }
References fmt, options, qtrue, and vp.
Referenced by report().
WriteMapFile()
static void WriteMapFile (void) static
Definition at line 1316 of file q3asm.c.
{
     FILE        *f;
     symbol_t    *s;
     char        imageName[MAX_OS_PATH];
     int         seg;
     strcpy( imageName, outputFilename );
     StripExtension( imageName );
     strcat( imageName, ".map" );
     report( "Writing %s...\n", imageName );
     f = SafeOpenWrite( imageName );
     for ( seg = CODESEG ; seg <= BSSSEG ; seg++ ) {
         for ( s = symbols ; s ; s = s->next ) {
             if ( s->name[0] == '$' ) {
                 continue;   // skip locals
             }
             if ( &segment[seg] != s->segment ) {
                 continue;
             }
             fprintf( f, "%i %8x %s\n", seg, s->value, s->name );
         }
     }
     fclose( f );
 }
References BSSSEG, CODESEG, MAX_OS_PATH, outputFilename, report(), SafeOpenWrite(), segment, StripExtension(), and symbols.
Referenced by Assemble().
WriteVmFile()
static void WriteVmFile (void) static
Definition at line 1348 of file q3asm.c.
{
     char    imageName[MAX_OS_PATH];
     vmHeader_t  header;
     FILE    *f;
     int     headerSize;
     report( "%i total errors\n", errorCount );
     strcpy( imageName, outputFilename );
     StripExtension( imageName );
     strcat( imageName, ".qvm" );
     remove( imageName );
     report( "code segment: %7i\n", segment[CODESEG].imageUsed );
     report( "data segment: %7i\n", segment[DATASEG].imageUsed );
     report( "lit  segment: %7i\n", segment[LITSEG].imageUsed );
     report( "bss  segment: %7i\n", segment[BSSSEG].imageUsed );
     report( "instruction count: %i\n", instructionCount );
     if ( errorCount != 0 ) {
         report( "Not writing a file due to errors\n" );
         return;
     }
     if( !options.vanillaQ3Compatibility ) {
         header.vmMagic = VM_MAGIC_VER2;
         headerSize = sizeof( header );
     } else {
         header.vmMagic = VM_MAGIC;
         // Don't write the VM_MAGIC_VER2 bits when maintaining 1.32b compatibility.
         // (I know this isn't strictly correct due to padding, but then platforms
         // that pad wouldn't be able to write a correct header anyway).  Note: if
         // vmHeader_t changes, this needs to be adjusted too.
         headerSize = sizeof( header ) - sizeof( header.jtrgLength );
     }
     header.instructionCount = instructionCount;
     header.codeOffset = headerSize;
     header.codeLength = segment[CODESEG].imageUsed;
     header.dataOffset = header.codeOffset + segment[CODESEG].imageUsed;
     header.dataLength = segment[DATASEG].imageUsed;
     header.litLength = segment[LITSEG].imageUsed;
     header.bssLength = segment[BSSSEG].imageUsed;
     header.jtrgLength = segment[JTRGSEG].imageUsed;
     report( "Writing to %s\n", imageName );
 #ifdef Q3_BIG_ENDIAN
     {
         int i;
         // byte swap the header
         for ( i = 0 ; i < sizeof( vmHeader_t ) / 4 ; i++ ) {
             ((int *)&header)[i] = LittleLong( ((int *)&header)[i] );
         }
     }
 #endif
     CreatePath( imageName );
     f = SafeOpenWrite( imageName );
     SafeWrite( f, &header, headerSize );
     SafeWrite( f, &segment[CODESEG].image, segment[CODESEG].imageUsed );
     SafeWrite( f, &segment[DATASEG].image, segment[DATASEG].imageUsed );
     SafeWrite( f, &segment[LITSEG].image, segment[LITSEG].imageUsed );
     if( !options.vanillaQ3Compatibility ) {
         SafeWrite( f, &segment[JTRGSEG].image, segment[JTRGSEG].imageUsed );
     }
     fclose( f );
 }
References BSSSEG, CODESEG, CreatePath(), DATASEG, errorCount, segment_t::imageUsed, instructionCount, JTRGSEG, LITSEG, MAX_OS_PATH, options, outputFilename, report(), SafeOpenWrite(), SafeWrite(), segment, StripExtension(), VM_MAGIC, and VM_MAGIC_VER2.
Referenced by Assemble().
Variable Documentation
asmFileNames
char* asmFileNames[MAX_ASM_FILES]
Definition at line 191 of file q3asm.c.
Referenced by Assemble(), main(), and ParseOptionFile().
asmFiles
char* asmFiles[MAX_ASM_FILES]
Definition at line 190 of file q3asm.c.
Referenced by Assemble().
currentArgOffset
int currentArgOffset
Definition at line 205 of file q3asm.c.
Referenced by ASM().
currentArgs
int currentArgs
Definition at line 204 of file q3asm.c.
Referenced by ASM().
currentFileIndex
int currentFileIndex
Definition at line 193 of file q3asm.c.
Referenced by Assemble(), DefineSymbol(), and LookupSymbol().
currentFileLine
int currentFileLine
Definition at line 195 of file q3asm.c.
Referenced by Assemble(), CodeError(), and ExtractLine().
currentFileName
char* currentFileName
Definition at line 194 of file q3asm.c.
Referenced by Assemble(), and CodeError().
currentLocals
int currentLocals
Definition at line 203 of file q3asm.c.
Referenced by ASM().
currentSegment
segment_t* currentSegment
Definition at line 169 of file q3asm.c.
Referenced by ASM(), DefineSymbol(), and HackToSegment().
errorCount
int errorCount
Definition at line 174 of file q3asm.c.
Referenced by CodeError(), Com_Error(), main(), and WriteVmFile().
instructionCount
int instructionCount
Definition at line 212 of file q3asm.c.
Referenced by ASM(), Assemble(), AssembleLine(), VM_Compile(), VM_PrepareInterpreter(), and WriteVmFile().
lastSymbol
symbol_t* lastSymbol = 0
Definition at line 185 of file q3asm.c.
Referenced by DefineSymbol(), HackToSegment(), and sort_symbols().
lineBuffer
char lineBuffer[MAX_LINE_LENGTH]
Definition at line 208 of file q3asm.c.
Referenced by ExtractLine(), and Parse().
lineParseOffset
int lineParseOffset
Definition at line 209 of file q3asm.c.
Referenced by ExtractLine(), and Parse().
numAsmFiles
int numAsmFiles
Definition at line 189 of file q3asm.c.
Referenced by Assemble(), main(), and ParseOptionFile().
numSymbols
int numSymbols
Definition at line 173 of file q3asm.c.
opcodesHash
int opcodesHash[NUM_SOURCE_OPS]
Definition at line 225 of file q3asm.c.
Referenced by AssembleLine(), and InitTables().
optable
hashtable_t* optable
Definition at line 166 of file q3asm.c.
Referenced by AssembleLine(), InitTables(), and main().
options
options_t options = { 0 }
Definition at line 182 of file q3asm.c.
Referenced by Assemble(), main(), vreport(), and WriteVmFile().
outputFilename
char outputFilename[MAX_OS_PATH]
Definition at line 31 of file q3asm.c.
Referenced by Assemble(), main(), ParseOptionFile(), WriteMapFile(), and WriteVmFile().
passNumber
int passNumber
Definition at line 171 of file q3asm.c.
Referenced by ASM(), Assemble(), DefineSymbol(), HackToSegment(), and LookupSymbol().
segment
segment_t segment[NUM_SEGMENTS]
Definition at line 168 of file q3asm.c.
Referenced by ASM(), Assemble(), AssembleLine(), HackToSegment(), Main_MenuDraw(), VM_LoadSymbols(), WriteMapFile(), and WriteVmFile().
sourceOps
sourceOps_t sourceOps[]
Initial value:
= {
}
Definition at line 219 of file q3asm.c.
Referenced by AssembleLine(), and InitTables().
stackSize
int stackSize = 0x10000
Definition at line 198 of file q3asm.c.
Referenced by Assemble().
symbols
List symbols
Definition at line 184 of file q3asm.c.
Referenced by DefineSymbol(), main(), sort_symbols(), VM_LoadSymbols(), and WriteMapFile().
symtable
hashtable_t* symtable
Definition at line 165 of file q3asm.c.
Referenced by DefineSymbol(), InitTables(), LookupSymbol(), and main().
symtablelen
int symtablelen = DEFAULT_HASHTABLE_SIZE
Definition at line 164 of file q3asm.c.
Referenced by InitTables(), and main().
token
char token[MAX_LINE_LENGTH]
Definition at line 210 of file q3asm.c.
Referenced by CG_HeadModelVoiceChats(), CG_Music_ParsePlaylist(), CG_ParseAnimationFile(), CG_ParseVoiceChats(), CG_weapGfx_Parse(), CG_weapGfx_ParseRemoteDefinition(), CL_LoadConsoleHistory(), COM_MatchToken(), dclr1(), enumdcl(), FindShaderInShaderText(), G_weapPhys_Parse(), G_weapPhys_ParseCategories(), G_weapPhys_ParseDefinition(), G_weapPhys_ParseFields(), G_weapPhys_ParseImports(), G_weapPhys_ParseLinks(), G_weapPhys_ParseRemoteDefinition(), G_weapPhys_PreParseDefinitions(), GametypeBits(), IN_IsConsoleKey(), Parse1DMatrix(), parseAura(), ParseDeform(), ParseShader(), ParseSkyParms(), ParseSort(), ParseStage(), ParseSurfaceParm(), ParseTexMod(), parseTier(), ParseVector(), ParseWaveForm(), PSys_ParseConstraint(), PSys_ParseEmitter(), PSys_ParseFile(), PSys_ParseForce(), PSys_ParseParticleTemplate(), PSys_ParseSystem(), PSys_ParseVector(), R_GLSL_ParseProgram(), R_LoadEntities(), RE_RegisterSkin(), ScanAndLoadShaderFiles(), SkipBracedSection(), structdcl(), UI_ParseAnimationFile(), UI_ParseInfos(), and VM_LoadSymbols().