ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/bits/forward_list.h File Reference
forward_list.h File Reference
#include <memory>
#include <initializer_list>
Functions
namespace std _GLIBCXX_VISIBILITY (default)
Detailed Description
This is an internal header file, included by other library headers. Do not attempt to use it directly. @headername{forward_list}
Definition in file forward_list.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace std _GLIBCXX_VISIBILITY (default)
A helper basic node class for forward_list. This is just a linked list with nothing inside it. There are purely list shuffling utility methods here.
A helper node class for forward_list. This is just a linked list with a data value in each node. There is a sorting utility method.
A forward_list::iterator.
All the functions are op overloads.
A forward_list::const_iterator.
All the functions are op overloads.
Forward list iterator equality comparison.
Forward list iterator inequality comparison.
Base class for forward_list.
A standard container with linear time access to elements, and fixed time insertion/deletion at any point in the sequence.
Meets the requirements of a container, a sequence, including the optional sequence requirements with the exception of at and operator[].
This is a singly linked list. Traversal up the list requires linear time, but adding and removing elements (or nodes) is done in constant time, regardless of where the change takes place. Unlike std::vector and std::deque, random-access iterators are not provided, so subscripting ([]) access is not allowed. For algorithms which only need sequential access, this lack makes no difference.
Also unlike the other standard containers, std::forward_list provides specialized algorithms unique to linked lists, such as splicing, sorting, and in-place reversal.
A couple points on memory allocation for forward_list<Tp>:
First, we never actually allocate a Tp, we allocate Fwd_list_node<Tp>'s and trust [20.1.5]/4 to DTRT. This is to ensure that after elements from forward_list<X,Alloc1> are spliced into forward_list<X,Alloc2>, destroying the memory of the second list is a valid operation, i.e., Alloc1 giveth and Alloc2 taketh away.
Creates a forward_list with no elements.
Parameters
al An allocator object.
Copy constructor with allocator argument.
Parameters
list Input list to copy.
al An allocator object.
Move constructor with allocator argument.
Parameters
list Input list to move.
al An allocator object.
Creates a forward_list with default constructed elements.
Parameters
n The number of elements to initially create.
This constructor creates the forward_list with n default constructed elements.
Creates a forward_list with copies of an exemplar element.
Parameters
n The number of elements to initially create.
value An element to copy.
al An allocator object.
This constructor fills the forward_list with n copies of value.
Builds a forward_list from a range.
Parameters
first An input iterator.
last An input iterator.
al An allocator object.
Create a forward_list consisting of copies of the elements from [first,last). This is linear in N (where N is distance(first,last)).
The forward_list copy constructor.
Parameters
list A forward_list of identical element and allocator types.
The newly-created forward_list uses a copy of the allocation object used by list.
The forward_list move constructor.
Parameters
list A forward_list of identical element and allocator types.
The newly-created forward_list contains the exact contents of forward_list. The contents of list are a valid, but unspecified forward_list.
Builds a forward_list from an initializer_list
Parameters
il An initializer_list of value_type.
al An allocator object.
Create a forward_list consisting of copies of the elements in the initializer_list il. This is linear in il.size().
The forward_list dtor.
The forward_list assignment operator.
Parameters
list A forward_list of identical element and allocator types.
All the elements of list are copied, but unlike the copy constructor, the allocator object is not copied.
The forward_list move assignment operator.
Parameters
list A forward_list of identical element and allocator types.
The contents of list are moved into this forward_list (without copying). list is a valid, but unspecified forward_list
The forward_list initializer list assignment operator.
Parameters
il An initializer_list of value_type.
Replace the contents of the forward_list with copies of the elements in the initializer_list il. This is linear in il.size().
Assigns a range to a forward_list.
Parameters
first An input iterator.
last An input iterator.
This function fills a forward_list with copies of the elements in the range [first,last).
Note that the assignment completely changes the forward_list and that the resulting forward_list's size is the same as the number of elements assigned. Old data may be lost.
Assigns a given value to a forward_list.
Parameters
n Number of elements to be assigned.
val Value to be assigned.
This function fills a forward_list with n copies of the given value. Note that the assignment completely changes the forward_list and that the resulting forward_list's size is the same as the number of elements assigned. Old data may be lost.
Assigns an initializer_list to a forward_list.
Parameters
il An initializer_list of value_type.
Replace the contents of the forward_list with copies of the elements in the initializer_list il. This is linear in il.size().
Get a copy of the memory allocation object.
Returns a read/write iterator that points before the first element in the forward_list. Iteration is done in ordinary element order.
Returns a read-only (constant) iterator that points before the first element in the forward_list. Iteration is done in ordinary element order.
Returns a read/write iterator that points to the first element in the forward_list. Iteration is done in ordinary element order.
Returns a read-only (constant) iterator that points to the first element in the forward_list. Iteration is done in ordinary element order.
Returns a read/write iterator that points one past the last element in the forward_list. Iteration is done in ordinary element order.
Returns a read-only iterator that points one past the last element in the forward_list. Iteration is done in ordinary element order.
Returns a read-only (constant) iterator that points to the first element in the forward_list. Iteration is done in ordinary element order.
Returns a read-only (constant) iterator that points before the first element in the forward_list. Iteration is done in ordinary element order.
Returns a read-only (constant) iterator that points one past the last element in the forward_list. Iteration is done in ordinary element order.
Returns true if the forward_list is empty. (Thus begin() would equal end().)
Returns the largest possible size of forward_list.
Returns a read/write reference to the data at the first element of the forward_list.
Returns a read-only (constant) reference to the data at the first element of the forward_list.
Constructs object in forward_list at the front of the list.
Parameters
args Arguments.
This function will insert an object of type Tp constructed with Tp(std::forward<Args>(args)...) at the front of the list Due to the nature of a forward_list this operation can be done in constant time, and does not invalidate iterators and references.
Add data to the front of the forward_list.
Parameters
val Data to be added.
This is a typical stack operation. The function creates an element at the front of the forward_list and assigns the given data to it. Due to the nature of a forward_list this operation can be done in constant time, and does not invalidate iterators and references.
Removes first element.
This is a typical stack operation. It shrinks the forward_list by one. Due to the nature of a forward_list this operation can be done in constant time, and only invalidates iterators/references to the element being removed.
Note that no data is returned, and if the first element's data is needed, it should be retrieved before pop_front() is called.
Constructs object in forward_list after the specified iterator.
Parameters
pos A const_iterator into the forward_list.
args Arguments.
Returns
An iterator that points to the inserted data.
This function will insert an object of type T constructed with T(std::forward<Args>(args)...) after the specified location. Due to the nature of a forward_list this operation can be done in constant time, and does not invalidate iterators and references.
Inserts given value into forward_list after specified iterator.
Parameters
pos An iterator into the forward_list.
val Data to be inserted.
Returns
An iterator that points to the inserted data.
This function will insert a copy of the given value after the specified location. Due to the nature of a forward_list this operation can be done in constant time, and does not invalidate iterators and references.
Inserts a number of copies of given data into the forward_list.
Parameters
pos An iterator into the forward_list.
n Number of elements to be inserted.
val Data to be inserted.
Returns
An iterator pointing to the last inserted copy of val or pos if n == 0.
This function will insert a specified number of copies of the given data after the location specified by pos.
This operation is linear in the number of elements inserted and does not invalidate iterators and references.
Inserts a range into the forward_list.
Parameters
position An iterator into the forward_list.
first An input iterator.
last An input iterator.
Returns
An iterator pointing to the last inserted element or pos if first == last.
This function will insert copies of the data in the range [first,last) into the forward_list after the location specified by pos.
This operation is linear in the number of elements inserted and does not invalidate iterators and references.
Inserts the contents of an initializer_list into forward_list after the specified iterator.
Parameters
pos An iterator into the forward_list.
il An initializer_list of value_type.
Returns
An iterator pointing to the last inserted element or pos if il is empty.
This function will insert copies of the data in the initializer_list il into the forward_list before the location specified by pos.
This operation is linear in the number of elements inserted and does not invalidate iterators and references.
Removes the element pointed to by the iterator following pos.
Parameters
pos Iterator pointing before element to be erased.
Returns
An iterator pointing to the element following the one that was erased, or end() if no such element exists.
This function will erase the element at the given position and thus shorten the forward_list by one.
Due to the nature of a forward_list this operation can be done in constant time, and only invalidates iterators/references to the element being removed. The user is also cautioned that this function only erases the element, and that if the element is itself a pointer, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Remove a range of elements.
Parameters
pos Iterator pointing before the first element to be erased.
last Iterator pointing to one past the last element to be erased.
Returns
@last.
This function will erase the elements in the range (pos,last) and shorten the forward_list accordingly.
This operation is linear time in the size of the range and only invalidates iterators/references to the element being removed. The user is also cautioned that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Swaps data with another forward_list.
Parameters
list A forward_list of the same element and allocator types.
This exchanges the elements between two lists in constant time. Note that the global std::swap() function is specialized such that std::swap(l1,l2) will feed to this function.
Resizes the forward_list to the specified number of elements.
Parameters
sz Number of elements the forward_list should contain.
This function will resize the forward_list to the specified number of elements. If the number is smaller than the forward_list's current size the forward_list is truncated, otherwise the forward_list is extended and the new elements are default constructed.
Resizes the forward_list to the specified number of elements.
Parameters
sz Number of elements the forward_list should contain.
val Data with which new elements should be populated.
This function will resize the forward_list to the specified number of elements. If the number is smaller than the forward_list's current size the forward_list is truncated, otherwise the forward_list is extended and new elements are populated with given data.
Erases all the elements.
Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Insert contents of another forward_list.
Parameters
pos Iterator referencing the element to insert after.
list Source list.
The elements of list are inserted in constant time after the element referenced by pos. list becomes an empty list.
Requires this != x.
Insert element from another forward_list.
Parameters
pos Iterator referencing the element to insert after.
list Source list.
i Iterator referencing the element before the element to move.
Removes the element in list list referenced by i and inserts it into the current list after pos.
Insert range from another forward_list.
Parameters
pos Iterator referencing the element to insert after.
list Source list.
before Iterator referencing before the start of range in list.
last Iterator referencing the end of range in list.
Removes elements in the range (before,last) and inserts them after pos in constant time.
Undefined if pos is in (before,last).
Remove all elements equal to value.
Parameters
val The value to remove.
Removes every element in the list equal to value. Remaining elements stay in list order. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Remove all elements satisfying a predicate.
Parameters
pred Unary predicate function or object.
Removes every element in the list for which the predicate returns true. Remaining elements stay in list order. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Remove consecutive duplicate elements.
For each consecutive set of elements with the same value, remove all but the first one. Remaining elements stay in list order. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Remove consecutive elements satisfying a predicate.
Parameters
binary_pred Binary predicate function or object.
For each consecutive set of elements [first,last) that satisfy predicate(first,i) where i is an iterator in [first,last), remove all but the first one. Remaining elements stay in list order. Note that this function only erases the elements, and that if the elements themselves are pointers, the pointed-to memory is not touched in any way. Managing the pointer is the user's responsibility.
Merge sorted lists.
Parameters
list Sorted list to merge.
Assumes that both list and this list are sorted according to operator<(). Merges elements of list into this list in sorted order, leaving list empty when complete. Elements in this list precede elements in list that are equal.
Merge sorted lists according to comparison function.
Parameters
list Sorted list to merge.
comp Comparison function defining sort order.
Assumes that both list and this list are sorted according to comp. Merges elements of list into this list in sorted order, leaving list empty when complete. Elements in this list precede elements in list that are equivalent according to comp().
Sort the elements of the list.
Sorts the elements of this list in NlogN time. Equivalent elements remain in list order.
Sort the forward_list using a comparison function.
Sorts the elements of this list in NlogN time. Equivalent elements remain in list order.
Reverse the elements in list.
Reverse the order of elements in the list in linear time.
Forward list equality comparison.
Parameters
lx A forward_list
ly A forward_list of the same type as lx.
Returns
True iff the size and elements of the forward lists are equal.
This is an equivalence relation. It is linear in the size of the forward lists. Deques are considered equivalent if corresponding elements compare equal.
Forward list ordering relation.
Parameters
lx A forward_list.
ly A forward_list of the same type as lx.
Returns
True iff lx is lexicographically less than ly.
This is a total ordering relation. It is linear in the size of the forward lists. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Based on operator==
Based on operator<
Based on operator<
Based on operator<
See std::forward_list::swap().
Definition at line 38 of file forward_list.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_CONTAINER
   struct _Fwd_list_node_base
   {
     _Fwd_list_node_base() : _M_next(0) { }
     _Fwd_list_node_base* _M_next;
     _Fwd_list_node_base*
     _M_transfer_after(_Fwd_list_node_base* __begin)
     {
       _Fwd_list_node_base* __end = __begin;
       while (__end && __end->_M_next)
     __end = __end->_M_next;
       return _M_transfer_after(__begin, __end);
     }
     _Fwd_list_node_base*
     _M_transfer_after(_Fwd_list_node_base* __begin,
               _Fwd_list_node_base* __end)
     {
       _Fwd_list_node_base* __keep = __begin->_M_next;
       if (__end)
     {
       __begin->_M_next = __end->_M_next;
       __end->_M_next = _M_next;
     }
       else
     __begin->_M_next = 0;
       _M_next = __keep;
       return __end;
     }
     void
     _M_reverse_after()
     {
       _Fwd_list_node_base* __tail = _M_next;
       if (!__tail)
     return;
       while (_Fwd_list_node_base* __temp = __tail->_M_next)
     {
       _Fwd_list_node_base* __keep = _M_next;
       _M_next = __temp;
       __tail->_M_next = __temp->_M_next;
       _M_next->_M_next = __keep;
     }
     }
   };
   template<typename _Tp>
     struct _Fwd_list_node
     : public _Fwd_list_node_base
     {
       template<typename... _Args>
         _Fwd_list_node(_Args&&... __args)
         : _Fwd_list_node_base(),
           _M_value(std::forward<_Args>(__args)...) { }
       _Tp _M_value;
     };
   template<typename _Tp>
     struct _Fwd_list_iterator
     {
       typedef _Fwd_list_iterator<_Tp>            _Self;
       typedef _Fwd_list_node<_Tp>                _Node;
       typedef _Tp                                value_type;
       typedef _Tp*                               pointer;
       typedef _Tp&                               reference;
       typedef ptrdiff_t                          difference_type;
       typedef std::forward_iterator_tag          iterator_category;
       _Fwd_list_iterator()
       : _M_node() { }
       explicit
       _Fwd_list_iterator(_Fwd_list_node_base* __n)
       : _M_node(__n) { }
       reference
       operator*() const
       { return static_cast<_Node*>(this->_M_node)->_M_value; }
       pointer
       operator->() const
       { return std::__addressof(static_cast<_Node*>
                 (this->_M_node)->_M_value); }
       _Self&
       operator++()
       {
         _M_node = _M_node->_M_next;
         return *this;
       }
       _Self
       operator++(int)
       {
         _Self __tmp(*this);
         _M_node = _M_node->_M_next;
         return __tmp;
       }
       bool
       operator==(const _Self& __x) const
       { return _M_node == __x._M_node; }
       bool
       operator!=(const _Self& __x) const
       { return _M_node != __x._M_node; }
       _Self
       _M_next() const
       {
         if (_M_node)
           return _Fwd_list_iterator(_M_node->_M_next);
         else
           return _Fwd_list_iterator(0);
       }
       _Fwd_list_node_base* _M_node;
     };
   template<typename _Tp>
     struct _Fwd_list_const_iterator
     {
       typedef _Fwd_list_const_iterator<_Tp>      _Self;
       typedef const _Fwd_list_node<_Tp>          _Node;
       typedef _Fwd_list_iterator<_Tp>            iterator;
       typedef _Tp                                value_type;
       typedef const _Tp*                         pointer;
       typedef const _Tp&                         reference;
       typedef ptrdiff_t                          difference_type;
       typedef std::forward_iterator_tag          iterator_category;
       _Fwd_list_const_iterator()
       : _M_node() { }
       explicit
       _Fwd_list_const_iterator(const _Fwd_list_node_base* __n)
       : _M_node(__n) { }
       _Fwd_list_const_iterator(const iterator& __iter)
       : _M_node(__iter._M_node) { }
       reference
       operator*() const
       { return static_cast<_Node*>(this->_M_node)->_M_value; }
       pointer
       operator->() const
       { return std::__addressof(static_cast<_Node*>
                 (this->_M_node)->_M_value); }
       _Self&
       operator++()
       {
         _M_node = _M_node->_M_next;
         return *this;
       }
       _Self
       operator++(int)
       {
         _Self __tmp(*this);
         _M_node = _M_node->_M_next;
         return __tmp;
       }
       bool
       operator==(const _Self& __x) const
       { return _M_node == __x._M_node; }
       bool
       operator!=(const _Self& __x) const
       { return _M_node != __x._M_node; }
       _Self
       _M_next() const
       {
         if (this->_M_node)
           return _Fwd_list_const_iterator(_M_node->_M_next);
         else
           return _Fwd_list_const_iterator(0);
       }
       const _Fwd_list_node_base* _M_node;
     };
   template<typename _Tp>
     inline bool
     operator==(const _Fwd_list_iterator<_Tp>& __x,
                const _Fwd_list_const_iterator<_Tp>& __y)
     { return __x._M_node == __y._M_node; }
   template<typename _Tp>
     inline bool
     operator!=(const _Fwd_list_iterator<_Tp>& __x,
                const _Fwd_list_const_iterator<_Tp>& __y)
     { return __x._M_node != __y._M_node; }
   template<typename _Tp, typename _Alloc>
     struct _Fwd_list_base
     {
     protected:
       typedef typename _Alloc::template rebind<_Tp>::other _Tp_alloc_type;
       typedef typename _Alloc::template
         rebind<_Fwd_list_node<_Tp>>::other _Node_alloc_type;
       struct _Fwd_list_impl
       : public _Node_alloc_type
       {
         _Fwd_list_node_base _M_head;
         _Fwd_list_impl()
         : _Node_alloc_type(), _M_head()
         { }
         _Fwd_list_impl(const _Node_alloc_type& __a)
         : _Node_alloc_type(__a), _M_head()
         { }
       };
       _Fwd_list_impl _M_impl;
     public:
       typedef _Fwd_list_iterator<_Tp>                 iterator;
       typedef _Fwd_list_const_iterator<_Tp>           const_iterator;
       typedef _Fwd_list_node<_Tp>                     _Node;
       _Node_alloc_type&
       _M_get_Node_allocator()
       { return *static_cast<_Node_alloc_type*>(&this->_M_impl); }
       const _Node_alloc_type&
       _M_get_Node_allocator() const
       { return *static_cast<const _Node_alloc_type*>(&this->_M_impl); }
       _Fwd_list_base()
       : _M_impl() { }
       _Fwd_list_base(const _Alloc& __a)
       : _M_impl(__a) { }
       _Fwd_list_base(const _Fwd_list_base& __lst, const _Alloc& __a);
       _Fwd_list_base(_Fwd_list_base&& __lst, const _Alloc& __a)
       : _M_impl(__a)
       {
     this->_M_impl._M_head._M_next = __lst._M_impl._M_head._M_next;
     __lst._M_impl._M_head._M_next = 0;
       }
       _Fwd_list_base(_Fwd_list_base&& __lst)
       : _M_impl(__lst._M_get_Node_allocator())
       {
     this->_M_impl._M_head._M_next = __lst._M_impl._M_head._M_next;
     __lst._M_impl._M_head._M_next = 0;
       }
       ~_Fwd_list_base()
       { _M_erase_after(&_M_impl._M_head, 0); }
     protected:
       _Node*
       _M_get_node()
       { return _M_get_Node_allocator().allocate(1); }
       template<typename... _Args>
         _Node*
         _M_create_node(_Args&&... __args)
         {
           _Node* __node = this->_M_get_node();
           __try
             {
               _M_get_Node_allocator().construct(__node,
                                               std::forward<_Args>(__args)...);
               __node->_M_next = 0;
             }
           __catch(...)
             {
               this->_M_put_node(__node);
               __throw_exception_again;
             }
           return __node;
         }
       template<typename... _Args>
         _Fwd_list_node_base*
         _M_insert_after(const_iterator __pos, _Args&&... __args);
       void
       _M_put_node(_Node* __p)
       { _M_get_Node_allocator().deallocate(__p, 1); }
       _Fwd_list_node_base*
       _M_erase_after(_Fwd_list_node_base* __pos);
       _Fwd_list_node_base*
       _M_erase_after(_Fwd_list_node_base* __pos,
                      _Fwd_list_node_base* __last);
     };
   template<typename _Tp, typename _Alloc = allocator<_Tp> >
     class forward_list : private _Fwd_list_base<_Tp, _Alloc>
     {
     private:
       typedef _Fwd_list_base<_Tp, _Alloc>                  _Base;
       typedef _Fwd_list_node<_Tp>                          _Node;
       typedef _Fwd_list_node_base                          _Node_base;
       typedef typename _Base::_Tp_alloc_type               _Tp_alloc_type;
     public:
       // types:
       typedef _Tp                                          value_type;
       typedef typename _Tp_alloc_type::pointer             pointer;
       typedef typename _Tp_alloc_type::const_pointer       const_pointer;
       typedef typename _Tp_alloc_type::reference           reference;
       typedef typename _Tp_alloc_type::const_reference     const_reference;
       typedef _Fwd_list_iterator<_Tp>                      iterator;
       typedef _Fwd_list_const_iterator<_Tp>                const_iterator;
       typedef std::size_t                                  size_type;
       typedef std::ptrdiff_t                               difference_type;
       typedef _Alloc                                       allocator_type;
       // 23.2.3.1 construct/copy/destroy:
       explicit
       forward_list(const _Alloc& __al = _Alloc())
       : _Base(__al)
       { }
       forward_list(const forward_list& __list, const _Alloc& __al)
       : _Base(__list, __al)
       { }
       forward_list(forward_list&& __list, const _Alloc& __al)
       : _Base(std::move(__list), __al)
       { }
       explicit
       forward_list(size_type __n)
       : _Base()
       { _M_default_initialize(__n); }
       forward_list(size_type __n, const _Tp& __value,
                    const _Alloc& __al = _Alloc())
       : _Base(__al)
       { _M_fill_initialize(__n, __value); }
       template<typename _InputIterator>
         forward_list(_InputIterator __first, _InputIterator __last,
                      const _Alloc& __al = _Alloc())
         : _Base(__al)
         {
           // Check whether it's an integral type.  If so, it's not an iterator.
           typedef typename std::__is_integer<_InputIterator>::__type _Integral;
           _M_initialize_dispatch(__first, __last, _Integral());
         }
       forward_list(const forward_list& __list)
       : _Base(__list._M_get_Node_allocator())
       { _M_initialize_dispatch(__list.begin(), __list.end(), __false_type()); }
       forward_list(forward_list&& __list)
       : _Base(std::move(__list)) { }
       forward_list(std::initializer_list<_Tp> __il,
                    const _Alloc& __al = _Alloc())
       : _Base(__al)
       { _M_initialize_dispatch(__il.begin(), __il.end(), __false_type()); }
       ~forward_list()
       { }
       forward_list&
       operator=(const forward_list& __list);
       forward_list&
       operator=(forward_list&& __list)
       {
     // NB: DR 1204.
     // NB: DR 675.
     this->clear();
     this->swap(__list);
     return *this;
       }
       forward_list&
       operator=(std::initializer_list<_Tp> __il)
       {
         assign(__il);
         return *this;
       }
       template<typename _InputIterator>
         void
         assign(_InputIterator __first, _InputIterator __last)
         {
           clear();
           insert_after(cbefore_begin(), __first, __last);
         }
       void
       assign(size_type __n, const _Tp& __val)
       {
         clear();
         insert_after(cbefore_begin(), __n, __val);
       }
       void
       assign(std::initializer_list<_Tp> __il)
       {
         clear();
         insert_after(cbefore_begin(), __il);
       }
       allocator_type
       get_allocator() const
       { return this->_M_get_Node_allocator(); }
       // 23.2.3.2 iterators:
       iterator
       before_begin()
       { return iterator(&this->_M_impl._M_head); }
       const_iterator
       before_begin() const
       { return const_iterator(&this->_M_impl._M_head); }
       iterator
       begin()
       { return iterator(this->_M_impl._M_head._M_next); }
       const_iterator
       begin() const
       { return const_iterator(this->_M_impl._M_head._M_next); }
       iterator
       end()
       { return iterator(0); }
       const_iterator
       end() const
       { return const_iterator(0); }
       const_iterator
       cbegin() const
       { return const_iterator(this->_M_impl._M_head._M_next); }
       const_iterator
       cbefore_begin() const
       { return const_iterator(&this->_M_impl._M_head); }
       const_iterator
       cend() const
       { return const_iterator(0); }
       bool
       empty() const
       { return this->_M_impl._M_head._M_next == 0; }
       size_type
       max_size() const
       { return this->_M_get_Node_allocator().max_size(); }
       // 23.2.3.3 element access:
       reference
       front()
       {
         _Node* __front = static_cast<_Node*>(this->_M_impl._M_head._M_next);
         return __front->_M_value;
       }
       const_reference
       front() const
       {
         _Node* __front = static_cast<_Node*>(this->_M_impl._M_head._M_next);
         return __front->_M_value;
       }
       // 23.2.3.4 modiers:
       template<typename... _Args>
         void
         emplace_front(_Args&&... __args)
         { this->_M_insert_after(cbefore_begin(),
                                 std::forward<_Args>(__args)...); }
       void
       push_front(const _Tp& __val)
       { this->_M_insert_after(cbefore_begin(), __val); }
       void
       push_front(_Tp&& __val)
       { this->_M_insert_after(cbefore_begin(), std::move(__val)); }
       void
       pop_front()
       { this->_M_erase_after(&this->_M_impl._M_head); }
       template<typename... _Args>
         iterator
         emplace_after(const_iterator __pos, _Args&&... __args)
         { return iterator(this->_M_insert_after(__pos,
                                           std::forward<_Args>(__args)...)); }
       iterator
       insert_after(const_iterator __pos, const _Tp& __val)
       { return iterator(this->_M_insert_after(__pos, __val)); }
       iterator
       insert_after(const_iterator __pos, _Tp&& __val)
       { return iterator(this->_M_insert_after(__pos, std::move(__val))); }
       iterator
       insert_after(const_iterator __pos, size_type __n, const _Tp& __val);
       template<typename _InputIterator>
         iterator
         insert_after(const_iterator __pos,
                      _InputIterator __first, _InputIterator __last);
       iterator
       insert_after(const_iterator __pos, std::initializer_list<_Tp> __il);
       iterator
       erase_after(const_iterator __pos)
       { return iterator(this->_M_erase_after(const_cast<_Node_base*>
                          (__pos._M_node))); }
       iterator
       erase_after(const_iterator __pos, const_iterator __last)
       { return iterator(this->_M_erase_after(const_cast<_Node_base*>
                          (__pos._M_node),
                          const_cast<_Node_base*>
                          (__last._M_node))); }
       void
       swap(forward_list& __list)
       { std::swap(this->_M_impl._M_head._M_next,
           __list._M_impl._M_head._M_next); }
       void
       resize(size_type __sz);
       void
       resize(size_type __sz, const value_type& __val);
       void
       clear()
       { this->_M_erase_after(&this->_M_impl._M_head, 0); }
       // 23.2.3.5 forward_list operations:
       void
       splice_after(const_iterator __pos, forward_list&& __list)
       {
     if (!__list.empty())
       _M_splice_after(__pos, std::move(__list));
       }
       void
       splice_after(const_iterator __pos, forward_list&& __list,
                    const_iterator __i)
       {
     const_iterator __j = __i;
     ++__j;
     if (__pos == __i || __pos == __j)
       return;
     splice_after(__pos, std::move(__list), __i, __j);
       }
       void
       splice_after(const_iterator __pos, forward_list&& __list,
                    const_iterator __before, const_iterator __last);
       void
       remove(const _Tp& __val);
       template<typename _Pred>
         void
         remove_if(_Pred __pred);
       void
       unique()
       { this->unique(std::equal_to<_Tp>()); }
       template<typename _BinPred>
         void
         unique(_BinPred __binary_pred);
       void
       merge(forward_list&& __list)
       { this->merge(std::move(__list), std::less<_Tp>()); }
       template<typename _Comp>
         void
         merge(forward_list&& __list, _Comp __comp);
       void
       sort()
       { this->sort(std::less<_Tp>()); }
       template<typename _Comp>
         void
         sort(_Comp __comp);
       void
       reverse()
       { this->_M_impl._M_head._M_reverse_after(); }
     private:
       template<typename _Integer>
         void
         _M_initialize_dispatch(_Integer __n, _Integer __x, __true_type)
         { _M_fill_initialize(static_cast<size_type>(__n), __x); }
       // Called by the range constructor to implement [23.1.1]/9
       template<typename _InputIterator>
         void
         _M_initialize_dispatch(_InputIterator __first, _InputIterator __last,
                                __false_type);
       // Called by forward_list(n,v,a), and the range constructor when it
       // turns out to be the same thing.
       void
       _M_fill_initialize(size_type __n, const value_type& __value);
       // Called by splice_after and insert_after.
       iterator
       _M_splice_after(const_iterator __pos, forward_list&& __list);
       // Called by forward_list(n).
       void
       _M_default_initialize(size_type __n);
       // Called by resize(sz).
       void
       _M_default_insert_after(const_iterator __pos, size_type __n);
     };
   template<typename _Tp, typename _Alloc>
     bool
     operator==(const forward_list<_Tp, _Alloc>& __lx,
                const forward_list<_Tp, _Alloc>& __ly);
   template<typename _Tp, typename _Alloc>
     inline bool
     operator<(const forward_list<_Tp, _Alloc>& __lx,
               const forward_list<_Tp, _Alloc>& __ly)
     { return std::lexicographical_compare(__lx.cbegin(), __lx.cend(),
                       __ly.cbegin(), __ly.cend()); }
   template<typename _Tp, typename _Alloc>
     inline bool
     operator!=(const forward_list<_Tp, _Alloc>& __lx,
                const forward_list<_Tp, _Alloc>& __ly)
     { return !(__lx == __ly); }
   template<typename _Tp, typename _Alloc>
     inline bool
     operator>(const forward_list<_Tp, _Alloc>& __lx,
               const forward_list<_Tp, _Alloc>& __ly)
     { return (__ly < __lx); }
   template<typename _Tp, typename _Alloc>
     inline bool
     operator>=(const forward_list<_Tp, _Alloc>& __lx,
                const forward_list<_Tp, _Alloc>& __ly)
     { return !(__lx < __ly); }
   template<typename _Tp, typename _Alloc>
     inline bool
     operator<=(const forward_list<_Tp, _Alloc>& __lx,
                const forward_list<_Tp, _Alloc>& __ly)
     { return !(__ly < __lx); }
   template<typename _Tp, typename _Alloc>
     inline void
     swap(forward_list<_Tp, _Alloc>& __lx,
      forward_list<_Tp, _Alloc>& __ly)
     { __lx.swap(__ly); }
 _GLIBCXX_END_NAMESPACE_CONTAINER
 } // namespace std
References __catch, __throw_exception_again, __try, assign(), move(), std::__exception_ptr::operator!=(), __gnu_debug::operator<(), __gnu_debug::operator<=(), std::__exception_ptr::operator==(), __gnu_debug::operator>(), __gnu_debug::operator>=(), remove(), and swap.