ZEQ2-Lite: Source/Engine/renderer/qgl.h File Reference
qgl.h File Reference
#include <SDL_opengl.h>
Macros
#define qglAccum glAccum
#define qglAlphaFunc glAlphaFunc
#define qglAreTexturesResident glAreTexturesResident
#define qglArrayElement glArrayElement
#define qglBegin glBegin
#define qglBindTexture glBindTexture
#define qglBitmap glBitmap
#define qglBlendFunc glBlendFunc
#define qglCallList glCallList
#define qglCallLists glCallLists
#define qglClear glClear
#define qglClearAccum glClearAccum
#define qglClearColor glClearColor
#define qglClearDepth glClearDepth
#define qglClearIndex glClearIndex
#define qglClearStencil glClearStencil
#define qglClipPlane glClipPlane
#define qglColor3b glColor3b
#define qglColor3bv glColor3bv
#define qglColor3d glColor3d
#define qglColor3dv glColor3dv
#define qglColor3f glColor3f
#define qglColor3fv glColor3fv
#define qglColor3i glColor3i
#define qglColor3iv glColor3iv
#define qglColor3s glColor3s
#define qglColor3sv glColor3sv
#define qglColor3ub glColor3ub
#define qglColor3ubv glColor3ubv
#define qglColor3ui glColor3ui
#define qglColor3uiv glColor3uiv
#define qglColor3us glColor3us
#define qglColor3usv glColor3usv
#define qglColor4b glColor4b
#define qglColor4bv glColor4bv
#define qglColor4d glColor4d
#define qglColor4dv glColor4dv
#define qglColor4f glColor4f
#define qglColor4fv glColor4fv
#define qglColor4i glColor4i
#define qglColor4iv glColor4iv
#define qglColor4s glColor4s
#define qglColor4sv glColor4sv
#define qglColor4ub glColor4ub
#define qglColor4ubv glColor4ubv
#define qglColor4ui glColor4ui
#define qglColor4uiv glColor4uiv
#define qglColor4us glColor4us
#define qglColor4usv glColor4usv
#define qglColorMask glColorMask
#define qglColorMaterial glColorMaterial
#define qglColorPointer glColorPointer
#define qglCopyPixels glCopyPixels
#define qglCopyTexImage1D glCopyTexImage1D
#define qglCopyTexImage2D glCopyTexImage2D
#define qglCopyTexSubImage1D glCopyTexSubImage1D
#define qglCopyTexSubImage2D glCopyTexSubImage2D
#define qglCullFace glCullFace
#define qglDeleteLists glDeleteLists
#define qglDeleteTextures glDeleteTextures
#define qglDepthFunc glDepthFunc
#define qglDepthMask glDepthMask
#define qglDepthRange glDepthRange
#define qglDisable glDisable
#define qglDisableClientState glDisableClientState
#define qglDrawArrays glDrawArrays
#define qglDrawBuffer glDrawBuffer
#define qglDrawElements glDrawElements
#define qglDrawPixels glDrawPixels
#define qglEdgeFlag glEdgeFlag
#define qglEdgeFlagPointer glEdgeFlagPointer
#define qglEdgeFlagv glEdgeFlagv
#define qglEnable glEnable
#define qglEnableClientState glEnableClientState
#define qglEnd glEnd
#define qglEndList glEndList
#define qglEvalCoord1d glEvalCoord1d
#define qglEvalCoord1dv glEvalCoord1dv
#define qglEvalCoord1f glEvalCoord1f
#define qglEvalCoord1fv glEvalCoord1fv
#define qglEvalCoord2d glEvalCoord2d
#define qglEvalCoord2dv glEvalCoord2dv
#define qglEvalCoord2f glEvalCoord2f
#define qglEvalCoord2fv glEvalCoord2fv
#define qglEvalMesh1 glEvalMesh1
#define qglEvalMesh2 glEvalMesh2
#define qglEvalPoint1 glEvalPoint1
#define qglEvalPoint2 glEvalPoint2
#define qglFeedbackBuffer glFeedbackBuffer
#define qglFinish glFinish
#define qglFlush glFlush
#define qglFogf glFogf
#define qglFogfv glFogfv
#define qglFogi glFogi
#define qglFogiv glFogiv
#define qglFrontFace glFrontFace
#define qglFrustum glFrustum
#define qglGenLists glGenLists
#define qglGenTextures glGenTextures
#define qglGetBooleanv glGetBooleanv
#define qglGetClipPlane glGetClipPlane
#define qglGetDoublev glGetDoublev
#define qglGetError glGetError
#define qglGetFloatv glGetFloatv
#define qglGetIntegerv glGetIntegerv
#define qglGetLightfv glGetLightfv
#define qglGetLightiv glGetLightiv
#define qglGetMapdv glGetMapdv
#define qglGetMapfv glGetMapfv
#define qglGetMapiv glGetMapiv
#define qglGetMaterialfv glGetMaterialfv
#define qglGetMaterialiv glGetMaterialiv
#define qglGetPixelMapfv glGetPixelMapfv
#define qglGetPixelMapuiv glGetPixelMapuiv
#define qglGetPixelMapusv glGetPixelMapusv
#define qglGetPointerv glGetPointerv
#define qglGetPolygonStipple glGetPolygonStipple
#define qglGetString glGetString
#define qglGetTexGendv glGetTexGendv
#define qglGetTexGenfv glGetTexGenfv
#define qglGetTexGeniv glGetTexGeniv
#define qglGetTexImage glGetTexImage
#define qglGetTexLevelParameterfv glGetTexLevelParameterfv
#define qglGetTexLevelParameteriv glGetTexLevelParameteriv
#define qglGetTexParameterfv glGetTexParameterfv
#define qglGetTexParameteriv glGetTexParameteriv
#define qglHint glHint
#define qglIndexd glIndexd
#define qglIndexdv glIndexdv
#define qglIndexf glIndexf
#define qglIndexfv glIndexfv
#define qglIndexi glIndexi
#define qglIndexiv glIndexiv
#define qglIndexMask glIndexMask
#define qglIndexPointer glIndexPointer
#define qglIndexs glIndexs
#define qglIndexsv glIndexsv
#define qglIndexub glIndexub
#define qglIndexubv glIndexubv
#define qglInitNames glInitNames
#define qglInterleavedArrays glInterleavedArrays
#define qglIsEnabled glIsEnabled
#define qglIsList glIsList
#define qglIsTexture glIsTexture
#define qglLightf glLightf
#define qglLightfv glLightfv
#define qglLighti glLighti
#define qglLightiv glLightiv
#define qglLightModelf glLightModelf
#define qglLightModelfv glLightModelfv
#define qglLightModeli glLightModeli
#define qglLightModeliv glLightModeliv
#define qglLineStipple glLineStipple
#define qglLineWidth glLineWidth
#define qglListBase glListBase
#define qglLoadIdentity glLoadIdentity
#define qglLoadMatrixd glLoadMatrixd
#define qglLoadMatrixf glLoadMatrixf
#define qglLoadName glLoadName
#define qglLogicOp glLogicOp
#define qglMap1d glMap1d
#define qglMap1f glMap1f
#define qglMap2d glMap2d
#define qglMap2f glMap2f
#define qglMapGrid1d glMapGrid1d
#define qglMapGrid1f glMapGrid1f
#define qglMapGrid2d glMapGrid2d
#define qglMapGrid2f glMapGrid2f
#define qglMaterialf glMaterialf
#define qglMaterialfv glMaterialfv
#define qglMateriali glMateriali
#define qglMaterialiv glMaterialiv
#define qglMatrixMode glMatrixMode
#define qglMultMatrixd glMultMatrixd
#define qglMultMatrixf glMultMatrixf
#define qglNewList glNewList
#define qglNormal3b glNormal3b
#define qglNormal3bv glNormal3bv
#define qglNormal3d glNormal3d
#define qglNormal3dv glNormal3dv
#define qglNormal3f glNormal3f
#define qglNormal3fv glNormal3fv
#define qglNormal3i glNormal3i
#define qglNormal3iv glNormal3iv
#define qglNormal3s glNormal3s
#define qglNormal3sv glNormal3sv
#define qglNormalPointer glNormalPointer
#define qglOrtho glOrtho
#define qglPassThrough glPassThrough
#define qglPixelMapfv glPixelMapfv
#define qglPixelMapuiv glPixelMapuiv
#define qglPixelMapusv glPixelMapusv
#define qglPixelStoref glPixelStoref
#define qglPixelStorei glPixelStorei
#define qglPixelTransferf glPixelTransferf
#define qglPixelTransferi glPixelTransferi
#define qglPixelZoom glPixelZoom
#define qglPointSize glPointSize
#define qglPolygonMode glPolygonMode
#define qglPolygonOffset glPolygonOffset
#define qglPolygonStipple glPolygonStipple
#define qglPopAttrib glPopAttrib
#define qglPopClientAttrib glPopClientAttrib
#define qglPopMatrix glPopMatrix
#define qglPopName glPopName
#define qglPrioritizeTextures glPrioritizeTextures
#define qglPushAttrib glPushAttrib
#define qglPushClientAttrib glPushClientAttrib
#define qglPushMatrix glPushMatrix
#define qglPushName glPushName
#define qglRasterPos2d glRasterPos2d
#define qglRasterPos2dv glRasterPos2dv
#define qglRasterPos2f glRasterPos2f
#define qglRasterPos2fv glRasterPos2fv
#define qglRasterPos2i glRasterPos2i
#define qglRasterPos2iv glRasterPos2iv
#define qglRasterPos2s glRasterPos2s
#define qglRasterPos2sv glRasterPos2sv
#define qglRasterPos3d glRasterPos3d
#define qglRasterPos3dv glRasterPos3dv
#define qglRasterPos3f glRasterPos3f
#define qglRasterPos3fv glRasterPos3fv
#define qglRasterPos3i glRasterPos3i
#define qglRasterPos3iv glRasterPos3iv
#define qglRasterPos3s glRasterPos3s
#define qglRasterPos3sv glRasterPos3sv
#define qglRasterPos4d glRasterPos4d
#define qglRasterPos4dv glRasterPos4dv
#define qglRasterPos4f glRasterPos4f
#define qglRasterPos4fv glRasterPos4fv
#define qglRasterPos4i glRasterPos4i
#define qglRasterPos4iv glRasterPos4iv
#define qglRasterPos4s glRasterPos4s
#define qglRasterPos4sv glRasterPos4sv
#define qglReadBuffer glReadBuffer
#define qglReadPixels glReadPixels
#define qglRectd glRectd
#define qglRectdv glRectdv
#define qglRectf glRectf
#define qglRectfv glRectfv
#define qglRecti glRecti
#define qglRectiv glRectiv
#define qglRects glRects
#define qglRectsv glRectsv
#define qglRenderMode glRenderMode
#define qglRotated glRotated
#define qglRotatef glRotatef
#define qglScaled glScaled
#define qglScalef glScalef
#define qglScissor glScissor
#define qglSelectBuffer glSelectBuffer
#define qglShadeModel glShadeModel
#define qglStencilFunc glStencilFunc
#define qglStencilMask glStencilMask
#define qglStencilOp glStencilOp
#define qglTexCoord1d glTexCoord1d
#define qglTexCoord1dv glTexCoord1dv
#define qglTexCoord1f glTexCoord1f
#define qglTexCoord1fv glTexCoord1fv
#define qglTexCoord1i glTexCoord1i
#define qglTexCoord1iv glTexCoord1iv
#define qglTexCoord1s glTexCoord1s
#define qglTexCoord1sv glTexCoord1sv
#define qglTexCoord2d glTexCoord2d
#define qglTexCoord2dv glTexCoord2dv
#define qglTexCoord2f glTexCoord2f
#define qglTexCoord2fv glTexCoord2fv
#define qglTexCoord2i glTexCoord2i
#define qglTexCoord2iv glTexCoord2iv
#define qglTexCoord2s glTexCoord2s
#define qglTexCoord2sv glTexCoord2sv
#define qglTexCoord3d glTexCoord3d
#define qglTexCoord3dv glTexCoord3dv
#define qglTexCoord3f glTexCoord3f
#define qglTexCoord3fv glTexCoord3fv
#define qglTexCoord3i glTexCoord3i
#define qglTexCoord3iv glTexCoord3iv
#define qglTexCoord3s glTexCoord3s
#define qglTexCoord3sv glTexCoord3sv
#define qglTexCoord4d glTexCoord4d
#define qglTexCoord4dv glTexCoord4dv
#define qglTexCoord4f glTexCoord4f
#define qglTexCoord4fv glTexCoord4fv
#define qglTexCoord4i glTexCoord4i
#define qglTexCoord4iv glTexCoord4iv
#define qglTexCoord4s glTexCoord4s
#define qglTexCoord4sv glTexCoord4sv
#define qglTexCoordPointer glTexCoordPointer
#define qglTexEnvf glTexEnvf
#define qglTexEnvfv glTexEnvfv
#define qglTexEnvi glTexEnvi
#define qglTexEnviv glTexEnviv
#define qglTexGend glTexGend
#define qglTexGendv glTexGendv
#define qglTexGenf glTexGenf
#define qglTexGenfv glTexGenfv
#define qglTexGeni glTexGeni
#define qglTexGeniv glTexGeniv
#define qglTexImage1D glTexImage1D
#define qglTexImage2D glTexImage2D
#define qglTexParameterf glTexParameterf
#define qglTexParameterfv glTexParameterfv
#define qglTexParameteri glTexParameteri
#define qglTexParameteriv glTexParameteriv
#define qglTexSubImage1D glTexSubImage1D
#define qglTexSubImage2D glTexSubImage2D
#define qglTranslated glTranslated
#define qglTranslatef glTranslatef
#define qglVertex2d glVertex2d
#define qglVertex2dv glVertex2dv
#define qglVertex2f glVertex2f
#define qglVertex2fv glVertex2fv
#define qglVertex2i glVertex2i
#define qglVertex2iv glVertex2iv
#define qglVertex2s glVertex2s
#define qglVertex2sv glVertex2sv
#define qglVertex3d glVertex3d
#define qglVertex3dv glVertex3dv
#define qglVertex3f glVertex3f
#define qglVertex3fv glVertex3fv
#define qglVertex3i glVertex3i
#define qglVertex3iv glVertex3iv
#define qglVertex3s glVertex3s
#define qglVertex3sv glVertex3sv
#define qglVertex4d glVertex4d
#define qglVertex4dv glVertex4dv
#define qglVertex4f glVertex4f
#define qglVertex4fv glVertex4fv
#define qglVertex4i glVertex4i
#define qglVertex4iv glVertex4iv
#define qglVertex4s glVertex4s
#define qglVertex4sv glVertex4sv
#define qglVertexPointer glVertexPointer
#define qglViewport glViewport
Functions
GLhandleARB (APIENTRYP qglGetHandleARB)(GLenum pname)
GLvoid (APIENTRYP qglDeleteObjectARB)(GLhandleARB obj)
GLext.h
This file taken from "GLext.h" from the Jeff Molofee OpenGL tutorials.
It is included here because glext.h is not available on some systems. If you don't want this version included, simply define "NO_SDL_GLEXT"
GLint (APIENTRYP qglGetUniformLocationARB)(GLhandleARB programObj
void (APIENTRYP qglActiveTextureARB)(GLenum texture)
Variables
GLhandleARB attachedObj
GLsizei count
GLuint index
GLsizei GLsizei GLcharARB * infoLog
GLsizei const GLcharARB const GLint * length
GLint location
GLsizei maxCount
GLsizei maxLength
const GLcharARB * name
GLint GLenum GLboolean normalized
GLhandleARB obj
GLenum GLfloat * params
GLenum pname
GLint GLenum GLboolean GLsizei const GLvoid * pointer
GLfloat s
GLuint GLsizei GLsizei GLint * size
GLsizei GLsizei GLcharARB * source
GLint GLenum GLboolean GLsizei stride
GLsizei const GLcharARB ** string
GLfloat GLfloat t
GLsizei GLboolean transpose
GLuint GLsizei GLsizei GLint GLenum * type
GLfloat * v
GLfloat v0
GLfloat GLfloat v1
GLfloat GLfloat GLfloat v2
GLfloat GLfloat GLfloat GLfloat v3
GLsizei const GLfloat * value
GLubyte GLubyte GLubyte GLubyte w
GLubyte x
GLubyte GLubyte y
GLubyte GLubyte GLubyte z
Macro Definition Documentation
qglAccum
#define qglAccum glAccum
Definition at line 137 of file qgl.h.
qglAlphaFunc
#define qglAlphaFunc glAlphaFunc
Definition at line 138 of file qgl.h.
qglAreTexturesResident
#define qglAreTexturesResident glAreTexturesResident
Definition at line 139 of file qgl.h.
qglArrayElement
#define qglArrayElement glArrayElement
Definition at line 140 of file qgl.h.
qglBegin
#define qglBegin glBegin
Definition at line 141 of file qgl.h.
qglBindTexture
#define qglBindTexture glBindTexture
Definition at line 142 of file qgl.h.
qglBitmap
#define qglBitmap glBitmap
Definition at line 143 of file qgl.h.
qglBlendFunc
#define qglBlendFunc glBlendFunc
Definition at line 144 of file qgl.h.
qglCallList
#define qglCallList glCallList
Definition at line 145 of file qgl.h.
qglCallLists
#define qglCallLists glCallLists
Definition at line 146 of file qgl.h.
qglClear
#define qglClear glClear
Definition at line 147 of file qgl.h.
qglClearAccum
#define qglClearAccum glClearAccum
Definition at line 148 of file qgl.h.
qglClearColor
#define qglClearColor glClearColor
Definition at line 149 of file qgl.h.
qglClearDepth
#define qglClearDepth glClearDepth
Definition at line 150 of file qgl.h.
qglClearIndex
#define qglClearIndex glClearIndex
Definition at line 151 of file qgl.h.
qglClearStencil
#define qglClearStencil glClearStencil
Definition at line 152 of file qgl.h.
qglClipPlane
#define qglClipPlane glClipPlane
Definition at line 153 of file qgl.h.
qglColor3b
#define qglColor3b glColor3b
Definition at line 154 of file qgl.h.
qglColor3bv
#define qglColor3bv glColor3bv
Definition at line 155 of file qgl.h.
qglColor3d
#define qglColor3d glColor3d
Definition at line 156 of file qgl.h.
qglColor3dv
#define qglColor3dv glColor3dv
Definition at line 157 of file qgl.h.
qglColor3f
#define qglColor3f glColor3f
Definition at line 158 of file qgl.h.
qglColor3fv
#define qglColor3fv glColor3fv
Definition at line 159 of file qgl.h.
qglColor3i
#define qglColor3i glColor3i
Definition at line 160 of file qgl.h.
qglColor3iv
#define qglColor3iv glColor3iv
Definition at line 161 of file qgl.h.
qglColor3s
#define qglColor3s glColor3s
Definition at line 162 of file qgl.h.
qglColor3sv
#define qglColor3sv glColor3sv
Definition at line 163 of file qgl.h.
qglColor3ub
#define qglColor3ub glColor3ub
Definition at line 164 of file qgl.h.
qglColor3ubv
#define qglColor3ubv glColor3ubv
Definition at line 165 of file qgl.h.
qglColor3ui
#define qglColor3ui glColor3ui
Definition at line 166 of file qgl.h.
qglColor3uiv
#define qglColor3uiv glColor3uiv
Definition at line 167 of file qgl.h.
qglColor3us
#define qglColor3us glColor3us
Definition at line 168 of file qgl.h.
qglColor3usv
#define qglColor3usv glColor3usv
Definition at line 169 of file qgl.h.
qglColor4b
#define qglColor4b glColor4b
Definition at line 170 of file qgl.h.
qglColor4bv
#define qglColor4bv glColor4bv
Definition at line 171 of file qgl.h.
qglColor4d
#define qglColor4d glColor4d
Definition at line 172 of file qgl.h.
qglColor4dv
#define qglColor4dv glColor4dv
Definition at line 173 of file qgl.h.
qglColor4f
#define qglColor4f glColor4f
Definition at line 174 of file qgl.h.
qglColor4fv
#define qglColor4fv glColor4fv
Definition at line 175 of file qgl.h.
qglColor4i
#define qglColor4i glColor4i
Definition at line 176 of file qgl.h.
qglColor4iv
#define qglColor4iv glColor4iv
Definition at line 177 of file qgl.h.
qglColor4s
#define qglColor4s glColor4s
Definition at line 178 of file qgl.h.
qglColor4sv
#define qglColor4sv glColor4sv
Definition at line 179 of file qgl.h.
qglColor4ub
#define qglColor4ub glColor4ub
Definition at line 180 of file qgl.h.
qglColor4ubv
#define qglColor4ubv glColor4ubv
Definition at line 181 of file qgl.h.
qglColor4ui
#define qglColor4ui glColor4ui
Definition at line 182 of file qgl.h.
qglColor4uiv
#define qglColor4uiv glColor4uiv
Definition at line 183 of file qgl.h.
qglColor4us
#define qglColor4us glColor4us
Definition at line 184 of file qgl.h.
qglColor4usv
#define qglColor4usv glColor4usv
Definition at line 185 of file qgl.h.
qglColorMask
#define qglColorMask glColorMask
Definition at line 186 of file qgl.h.
qglColorMaterial
#define qglColorMaterial glColorMaterial
Definition at line 187 of file qgl.h.
qglColorPointer
#define qglColorPointer glColorPointer
Definition at line 188 of file qgl.h.
qglCopyPixels
#define qglCopyPixels glCopyPixels
Definition at line 189 of file qgl.h.
qglCopyTexImage1D
#define qglCopyTexImage1D glCopyTexImage1D
Definition at line 190 of file qgl.h.
qglCopyTexImage2D
#define qglCopyTexImage2D glCopyTexImage2D
Definition at line 191 of file qgl.h.
qglCopyTexSubImage1D
#define qglCopyTexSubImage1D glCopyTexSubImage1D
Definition at line 192 of file qgl.h.
qglCopyTexSubImage2D
#define qglCopyTexSubImage2D glCopyTexSubImage2D
Definition at line 193 of file qgl.h.
qglCullFace
#define qglCullFace glCullFace
Definition at line 194 of file qgl.h.
qglDeleteLists
#define qglDeleteLists glDeleteLists
Definition at line 195 of file qgl.h.
qglDeleteTextures
#define qglDeleteTextures glDeleteTextures
Definition at line 196 of file qgl.h.
qglDepthFunc
#define qglDepthFunc glDepthFunc
Definition at line 197 of file qgl.h.
qglDepthMask
#define qglDepthMask glDepthMask
Definition at line 198 of file qgl.h.
qglDepthRange
#define qglDepthRange glDepthRange
Definition at line 199 of file qgl.h.
qglDisable
#define qglDisable glDisable
Definition at line 200 of file qgl.h.
qglDisableClientState
#define qglDisableClientState glDisableClientState
Definition at line 201 of file qgl.h.
qglDrawArrays
#define qglDrawArrays glDrawArrays
Definition at line 202 of file qgl.h.
qglDrawBuffer
#define qglDrawBuffer glDrawBuffer
Definition at line 203 of file qgl.h.
qglDrawElements
#define qglDrawElements glDrawElements
Definition at line 204 of file qgl.h.
qglDrawPixels
#define qglDrawPixels glDrawPixels
Definition at line 205 of file qgl.h.
qglEdgeFlag
#define qglEdgeFlag glEdgeFlag
Definition at line 206 of file qgl.h.
qglEdgeFlagPointer
#define qglEdgeFlagPointer glEdgeFlagPointer
Definition at line 207 of file qgl.h.
qglEdgeFlagv
#define qglEdgeFlagv glEdgeFlagv
Definition at line 208 of file qgl.h.
qglEnable
#define qglEnable glEnable
Definition at line 209 of file qgl.h.
qglEnableClientState
#define qglEnableClientState glEnableClientState
Definition at line 210 of file qgl.h.
qglEnd
#define qglEnd glEnd
Definition at line 211 of file qgl.h.
qglEndList
#define qglEndList glEndList
Definition at line 212 of file qgl.h.
qglEvalCoord1d
#define qglEvalCoord1d glEvalCoord1d
Definition at line 213 of file qgl.h.
qglEvalCoord1dv
#define qglEvalCoord1dv glEvalCoord1dv
Definition at line 214 of file qgl.h.
qglEvalCoord1f
#define qglEvalCoord1f glEvalCoord1f
Definition at line 215 of file qgl.h.
qglEvalCoord1fv
#define qglEvalCoord1fv glEvalCoord1fv
Definition at line 216 of file qgl.h.
qglEvalCoord2d
#define qglEvalCoord2d glEvalCoord2d
Definition at line 217 of file qgl.h.
qglEvalCoord2dv
#define qglEvalCoord2dv glEvalCoord2dv
Definition at line 218 of file qgl.h.
qglEvalCoord2f
#define qglEvalCoord2f glEvalCoord2f
Definition at line 219 of file qgl.h.
qglEvalCoord2fv
#define qglEvalCoord2fv glEvalCoord2fv
Definition at line 220 of file qgl.h.
qglEvalMesh1
#define qglEvalMesh1 glEvalMesh1
Definition at line 221 of file qgl.h.
qglEvalMesh2
#define qglEvalMesh2 glEvalMesh2
Definition at line 222 of file qgl.h.
qglEvalPoint1
#define qglEvalPoint1 glEvalPoint1
Definition at line 223 of file qgl.h.
qglEvalPoint2
#define qglEvalPoint2 glEvalPoint2
Definition at line 224 of file qgl.h.
qglFeedbackBuffer
#define qglFeedbackBuffer glFeedbackBuffer
Definition at line 225 of file qgl.h.
qglFinish
#define qglFinish glFinish
Definition at line 226 of file qgl.h.
qglFlush
#define qglFlush glFlush
Definition at line 227 of file qgl.h.
qglFogf
#define qglFogf glFogf
Definition at line 228 of file qgl.h.
qglFogfv
#define qglFogfv glFogfv
Definition at line 229 of file qgl.h.
qglFogi
#define qglFogi glFogi
Definition at line 230 of file qgl.h.
qglFogiv
#define qglFogiv glFogiv
Definition at line 231 of file qgl.h.
qglFrontFace
#define qglFrontFace glFrontFace
Definition at line 232 of file qgl.h.
qglFrustum
#define qglFrustum glFrustum
Definition at line 233 of file qgl.h.
qglGenLists
#define qglGenLists glGenLists
Definition at line 234 of file qgl.h.
qglGenTextures
#define qglGenTextures glGenTextures
Definition at line 235 of file qgl.h.
qglGetBooleanv
#define qglGetBooleanv glGetBooleanv
Definition at line 236 of file qgl.h.
qglGetClipPlane
#define qglGetClipPlane glGetClipPlane
Definition at line 237 of file qgl.h.
qglGetDoublev
#define qglGetDoublev glGetDoublev
Definition at line 238 of file qgl.h.
qglGetError
#define qglGetError glGetError
Definition at line 239 of file qgl.h.
qglGetFloatv
#define qglGetFloatv glGetFloatv
Definition at line 240 of file qgl.h.
qglGetIntegerv
#define qglGetIntegerv glGetIntegerv
Definition at line 241 of file qgl.h.
qglGetLightfv
#define qglGetLightfv glGetLightfv
Definition at line 242 of file qgl.h.
qglGetLightiv
#define qglGetLightiv glGetLightiv
Definition at line 243 of file qgl.h.
qglGetMapdv
#define qglGetMapdv glGetMapdv
Definition at line 244 of file qgl.h.
qglGetMapfv
#define qglGetMapfv glGetMapfv
Definition at line 245 of file qgl.h.
qglGetMapiv
#define qglGetMapiv glGetMapiv
Definition at line 246 of file qgl.h.
qglGetMaterialfv
#define qglGetMaterialfv glGetMaterialfv
Definition at line 247 of file qgl.h.
qglGetMaterialiv
#define qglGetMaterialiv glGetMaterialiv
Definition at line 248 of file qgl.h.
qglGetPixelMapfv
#define qglGetPixelMapfv glGetPixelMapfv
Definition at line 249 of file qgl.h.
qglGetPixelMapuiv
#define qglGetPixelMapuiv glGetPixelMapuiv
Definition at line 250 of file qgl.h.
qglGetPixelMapusv
#define qglGetPixelMapusv glGetPixelMapusv
Definition at line 251 of file qgl.h.
qglGetPointerv
#define qglGetPointerv glGetPointerv
Definition at line 252 of file qgl.h.
qglGetPolygonStipple
#define qglGetPolygonStipple glGetPolygonStipple
Definition at line 253 of file qgl.h.
qglGetString
#define qglGetString glGetString
Definition at line 254 of file qgl.h.
qglGetTexGendv
#define qglGetTexGendv glGetTexGendv
Definition at line 255 of file qgl.h.
qglGetTexGenfv
#define qglGetTexGenfv glGetTexGenfv
Definition at line 256 of file qgl.h.
qglGetTexGeniv
#define qglGetTexGeniv glGetTexGeniv
Definition at line 257 of file qgl.h.
qglGetTexImage
#define qglGetTexImage glGetTexImage
Definition at line 258 of file qgl.h.
qglGetTexLevelParameterfv
#define qglGetTexLevelParameterfv glGetTexLevelParameterfv
Definition at line 259 of file qgl.h.
qglGetTexLevelParameteriv
#define qglGetTexLevelParameteriv glGetTexLevelParameteriv
Definition at line 260 of file qgl.h.
qglGetTexParameterfv
#define qglGetTexParameterfv glGetTexParameterfv
Definition at line 261 of file qgl.h.
qglGetTexParameteriv
#define qglGetTexParameteriv glGetTexParameteriv
Definition at line 262 of file qgl.h.
qglHint
#define qglHint glHint
Definition at line 263 of file qgl.h.
qglIndexd
#define qglIndexd glIndexd
Definition at line 266 of file qgl.h.
qglIndexdv
#define qglIndexdv glIndexdv
Definition at line 267 of file qgl.h.
qglIndexf
#define qglIndexf glIndexf
Definition at line 268 of file qgl.h.
qglIndexfv
#define qglIndexfv glIndexfv
Definition at line 269 of file qgl.h.
qglIndexi
#define qglIndexi glIndexi
Definition at line 270 of file qgl.h.
qglIndexiv
#define qglIndexiv glIndexiv
Definition at line 271 of file qgl.h.
qglIndexMask
#define qglIndexMask glIndexMask
Definition at line 264 of file qgl.h.
qglIndexPointer
#define qglIndexPointer glIndexPointer
Definition at line 265 of file qgl.h.
qglIndexs
#define qglIndexs glIndexs
Definition at line 272 of file qgl.h.
qglIndexsv
#define qglIndexsv glIndexsv
Definition at line 273 of file qgl.h.
qglIndexub
#define qglIndexub glIndexub
Definition at line 274 of file qgl.h.
qglIndexubv
#define qglIndexubv glIndexubv
Definition at line 275 of file qgl.h.
qglInitNames
#define qglInitNames glInitNames
Definition at line 276 of file qgl.h.
qglInterleavedArrays
#define qglInterleavedArrays glInterleavedArrays
Definition at line 277 of file qgl.h.
qglIsEnabled
#define qglIsEnabled glIsEnabled
Definition at line 278 of file qgl.h.
qglIsList
#define qglIsList glIsList
Definition at line 279 of file qgl.h.
qglIsTexture
#define qglIsTexture glIsTexture
Definition at line 280 of file qgl.h.
qglLightf
#define qglLightf glLightf
Definition at line 285 of file qgl.h.
qglLightfv
#define qglLightfv glLightfv
Definition at line 286 of file qgl.h.
qglLighti
#define qglLighti glLighti
Definition at line 287 of file qgl.h.
qglLightiv
#define qglLightiv glLightiv
Definition at line 288 of file qgl.h.
qglLightModelf
#define qglLightModelf glLightModelf
Definition at line 281 of file qgl.h.
qglLightModelfv
#define qglLightModelfv glLightModelfv
Definition at line 282 of file qgl.h.
qglLightModeli
#define qglLightModeli glLightModeli
Definition at line 283 of file qgl.h.
qglLightModeliv
#define qglLightModeliv glLightModeliv
Definition at line 284 of file qgl.h.
qglLineStipple
#define qglLineStipple glLineStipple
Definition at line 289 of file qgl.h.
qglLineWidth
#define qglLineWidth glLineWidth
Definition at line 290 of file qgl.h.
qglListBase
#define qglListBase glListBase
Definition at line 291 of file qgl.h.
qglLoadIdentity
#define qglLoadIdentity glLoadIdentity
Definition at line 292 of file qgl.h.
qglLoadMatrixd
#define qglLoadMatrixd glLoadMatrixd
Definition at line 293 of file qgl.h.
qglLoadMatrixf
#define qglLoadMatrixf glLoadMatrixf
Definition at line 294 of file qgl.h.
qglLoadName
#define qglLoadName glLoadName
Definition at line 295 of file qgl.h.
qglLogicOp
#define qglLogicOp glLogicOp
Definition at line 296 of file qgl.h.
qglMap1d
#define qglMap1d glMap1d
Definition at line 297 of file qgl.h.
qglMap1f
#define qglMap1f glMap1f
Definition at line 298 of file qgl.h.
qglMap2d
#define qglMap2d glMap2d
Definition at line 299 of file qgl.h.
qglMap2f
#define qglMap2f glMap2f
Definition at line 300 of file qgl.h.
qglMapGrid1d
#define qglMapGrid1d glMapGrid1d
Definition at line 301 of file qgl.h.
qglMapGrid1f
#define qglMapGrid1f glMapGrid1f
Definition at line 302 of file qgl.h.
qglMapGrid2d
#define qglMapGrid2d glMapGrid2d
Definition at line 303 of file qgl.h.
qglMapGrid2f
#define qglMapGrid2f glMapGrid2f
Definition at line 304 of file qgl.h.
qglMaterialf
#define qglMaterialf glMaterialf
Definition at line 305 of file qgl.h.
qglMaterialfv
#define qglMaterialfv glMaterialfv
Definition at line 306 of file qgl.h.
qglMateriali
#define qglMateriali glMateriali
Definition at line 307 of file qgl.h.
qglMaterialiv
#define qglMaterialiv glMaterialiv
Definition at line 308 of file qgl.h.
qglMatrixMode
#define qglMatrixMode glMatrixMode
Definition at line 309 of file qgl.h.
qglMultMatrixd
#define qglMultMatrixd glMultMatrixd
Definition at line 310 of file qgl.h.
qglMultMatrixf
#define qglMultMatrixf glMultMatrixf
Definition at line 311 of file qgl.h.
qglNewList
#define qglNewList glNewList
Definition at line 312 of file qgl.h.
qglNormal3b
#define qglNormal3b glNormal3b
Definition at line 313 of file qgl.h.
qglNormal3bv
#define qglNormal3bv glNormal3bv
Definition at line 314 of file qgl.h.
qglNormal3d
#define qglNormal3d glNormal3d
Definition at line 315 of file qgl.h.
qglNormal3dv
#define qglNormal3dv glNormal3dv
Definition at line 316 of file qgl.h.
qglNormal3f
#define qglNormal3f glNormal3f
Definition at line 317 of file qgl.h.
qglNormal3fv
#define qglNormal3fv glNormal3fv
Definition at line 318 of file qgl.h.
qglNormal3i
#define qglNormal3i glNormal3i
Definition at line 319 of file qgl.h.
qglNormal3iv
#define qglNormal3iv glNormal3iv
Definition at line 320 of file qgl.h.
qglNormal3s
#define qglNormal3s glNormal3s
Definition at line 321 of file qgl.h.
qglNormal3sv
#define qglNormal3sv glNormal3sv
Definition at line 322 of file qgl.h.
qglNormalPointer
#define qglNormalPointer glNormalPointer
Definition at line 323 of file qgl.h.
qglOrtho
#define qglOrtho glOrtho
Definition at line 324 of file qgl.h.
qglPassThrough
#define qglPassThrough glPassThrough
Definition at line 325 of file qgl.h.
qglPixelMapfv
#define qglPixelMapfv glPixelMapfv
Definition at line 326 of file qgl.h.
qglPixelMapuiv
#define qglPixelMapuiv glPixelMapuiv
Definition at line 327 of file qgl.h.
qglPixelMapusv
#define qglPixelMapusv glPixelMapusv
Definition at line 328 of file qgl.h.
qglPixelStoref
#define qglPixelStoref glPixelStoref
Definition at line 329 of file qgl.h.
qglPixelStorei
#define qglPixelStorei glPixelStorei
Definition at line 330 of file qgl.h.
qglPixelTransferf
#define qglPixelTransferf glPixelTransferf
Definition at line 331 of file qgl.h.
qglPixelTransferi
#define qglPixelTransferi glPixelTransferi
Definition at line 332 of file qgl.h.
qglPixelZoom
#define qglPixelZoom glPixelZoom
Definition at line 333 of file qgl.h.
qglPointSize
#define qglPointSize glPointSize
Definition at line 334 of file qgl.h.
qglPolygonMode
#define qglPolygonMode glPolygonMode
Definition at line 335 of file qgl.h.
qglPolygonOffset
#define qglPolygonOffset glPolygonOffset
Definition at line 336 of file qgl.h.
qglPolygonStipple
#define qglPolygonStipple glPolygonStipple
Definition at line 337 of file qgl.h.
qglPopAttrib
#define qglPopAttrib glPopAttrib
Definition at line 338 of file qgl.h.
qglPopClientAttrib
#define qglPopClientAttrib glPopClientAttrib
Definition at line 339 of file qgl.h.
qglPopMatrix
#define qglPopMatrix glPopMatrix
Definition at line 340 of file qgl.h.
qglPopName
#define qglPopName glPopName
Definition at line 341 of file qgl.h.
qglPrioritizeTextures
#define qglPrioritizeTextures glPrioritizeTextures
Definition at line 342 of file qgl.h.
qglPushAttrib
#define qglPushAttrib glPushAttrib
Definition at line 343 of file qgl.h.
qglPushClientAttrib
#define qglPushClientAttrib glPushClientAttrib
Definition at line 344 of file qgl.h.
qglPushMatrix
#define qglPushMatrix glPushMatrix
Definition at line 345 of file qgl.h.
qglPushName
#define qglPushName glPushName
Definition at line 346 of file qgl.h.
qglRasterPos2d
#define qglRasterPos2d glRasterPos2d
Definition at line 347 of file qgl.h.
qglRasterPos2dv
#define qglRasterPos2dv glRasterPos2dv
Definition at line 348 of file qgl.h.
qglRasterPos2f
#define qglRasterPos2f glRasterPos2f
Definition at line 349 of file qgl.h.
qglRasterPos2fv
#define qglRasterPos2fv glRasterPos2fv
Definition at line 350 of file qgl.h.
qglRasterPos2i
#define qglRasterPos2i glRasterPos2i
Definition at line 351 of file qgl.h.
qglRasterPos2iv
#define qglRasterPos2iv glRasterPos2iv
Definition at line 352 of file qgl.h.
qglRasterPos2s
#define qglRasterPos2s glRasterPos2s
Definition at line 353 of file qgl.h.
qglRasterPos2sv
#define qglRasterPos2sv glRasterPos2sv
Definition at line 354 of file qgl.h.
qglRasterPos3d
#define qglRasterPos3d glRasterPos3d
Definition at line 355 of file qgl.h.
qglRasterPos3dv
#define qglRasterPos3dv glRasterPos3dv
Definition at line 356 of file qgl.h.
qglRasterPos3f
#define qglRasterPos3f glRasterPos3f
Definition at line 357 of file qgl.h.
qglRasterPos3fv
#define qglRasterPos3fv glRasterPos3fv
Definition at line 358 of file qgl.h.
qglRasterPos3i
#define qglRasterPos3i glRasterPos3i
Definition at line 359 of file qgl.h.
qglRasterPos3iv
#define qglRasterPos3iv glRasterPos3iv
Definition at line 360 of file qgl.h.
qglRasterPos3s
#define qglRasterPos3s glRasterPos3s
Definition at line 361 of file qgl.h.
qglRasterPos3sv
#define qglRasterPos3sv glRasterPos3sv
Definition at line 362 of file qgl.h.
qglRasterPos4d
#define qglRasterPos4d glRasterPos4d
Definition at line 363 of file qgl.h.
qglRasterPos4dv
#define qglRasterPos4dv glRasterPos4dv
Definition at line 364 of file qgl.h.
qglRasterPos4f
#define qglRasterPos4f glRasterPos4f
Definition at line 365 of file qgl.h.
qglRasterPos4fv
#define qglRasterPos4fv glRasterPos4fv
Definition at line 366 of file qgl.h.
qglRasterPos4i
#define qglRasterPos4i glRasterPos4i
Definition at line 367 of file qgl.h.
qglRasterPos4iv
#define qglRasterPos4iv glRasterPos4iv
Definition at line 368 of file qgl.h.
qglRasterPos4s
#define qglRasterPos4s glRasterPos4s
Definition at line 369 of file qgl.h.
qglRasterPos4sv
#define qglRasterPos4sv glRasterPos4sv
Definition at line 370 of file qgl.h.
qglReadBuffer
#define qglReadBuffer glReadBuffer
Definition at line 371 of file qgl.h.
qglReadPixels
#define qglReadPixels glReadPixels
Definition at line 372 of file qgl.h.
qglRectd
#define qglRectd glRectd
Definition at line 373 of file qgl.h.
qglRectdv
#define qglRectdv glRectdv
Definition at line 374 of file qgl.h.
qglRectf
#define qglRectf glRectf
Definition at line 375 of file qgl.h.
qglRectfv
#define qglRectfv glRectfv
Definition at line 376 of file qgl.h.
qglRecti
#define qglRecti glRecti
Definition at line 377 of file qgl.h.
qglRectiv
#define qglRectiv glRectiv
Definition at line 378 of file qgl.h.
qglRects
#define qglRects glRects
Definition at line 379 of file qgl.h.
qglRectsv
#define qglRectsv glRectsv
Definition at line 380 of file qgl.h.
qglRenderMode
#define qglRenderMode glRenderMode
Definition at line 381 of file qgl.h.
qglRotated
#define qglRotated glRotated
Definition at line 382 of file qgl.h.
qglRotatef
#define qglRotatef glRotatef
Definition at line 383 of file qgl.h.
qglScaled
#define qglScaled glScaled
Definition at line 384 of file qgl.h.
qglScalef
#define qglScalef glScalef
Definition at line 385 of file qgl.h.
qglScissor
#define qglScissor glScissor
Definition at line 386 of file qgl.h.
qglSelectBuffer
#define qglSelectBuffer glSelectBuffer
Definition at line 387 of file qgl.h.
qglShadeModel
#define qglShadeModel glShadeModel
Definition at line 388 of file qgl.h.
qglStencilFunc
#define qglStencilFunc glStencilFunc
Definition at line 389 of file qgl.h.
qglStencilMask
#define qglStencilMask glStencilMask
Definition at line 390 of file qgl.h.
qglStencilOp
#define qglStencilOp glStencilOp
Definition at line 391 of file qgl.h.
qglTexCoord1d
#define qglTexCoord1d glTexCoord1d
Definition at line 392 of file qgl.h.
qglTexCoord1dv
#define qglTexCoord1dv glTexCoord1dv
Definition at line 393 of file qgl.h.
qglTexCoord1f
#define qglTexCoord1f glTexCoord1f
Definition at line 394 of file qgl.h.
qglTexCoord1fv
#define qglTexCoord1fv glTexCoord1fv
Definition at line 395 of file qgl.h.
qglTexCoord1i
#define qglTexCoord1i glTexCoord1i
Definition at line 396 of file qgl.h.
qglTexCoord1iv
#define qglTexCoord1iv glTexCoord1iv
Definition at line 397 of file qgl.h.
qglTexCoord1s
#define qglTexCoord1s glTexCoord1s
Definition at line 398 of file qgl.h.
qglTexCoord1sv
#define qglTexCoord1sv glTexCoord1sv
Definition at line 399 of file qgl.h.
qglTexCoord2d
#define qglTexCoord2d glTexCoord2d
Definition at line 400 of file qgl.h.
qglTexCoord2dv
#define qglTexCoord2dv glTexCoord2dv
Definition at line 401 of file qgl.h.
qglTexCoord2f
#define qglTexCoord2f glTexCoord2f
Definition at line 402 of file qgl.h.
qglTexCoord2fv
#define qglTexCoord2fv glTexCoord2fv
Definition at line 403 of file qgl.h.
qglTexCoord2i
#define qglTexCoord2i glTexCoord2i
Definition at line 404 of file qgl.h.
qglTexCoord2iv
#define qglTexCoord2iv glTexCoord2iv
Definition at line 405 of file qgl.h.
qglTexCoord2s
#define qglTexCoord2s glTexCoord2s
Definition at line 406 of file qgl.h.
qglTexCoord2sv
#define qglTexCoord2sv glTexCoord2sv
Definition at line 407 of file qgl.h.
qglTexCoord3d
#define qglTexCoord3d glTexCoord3d
Definition at line 408 of file qgl.h.
qglTexCoord3dv
#define qglTexCoord3dv glTexCoord3dv
Definition at line 409 of file qgl.h.
qglTexCoord3f
#define qglTexCoord3f glTexCoord3f
Definition at line 410 of file qgl.h.
qglTexCoord3fv
#define qglTexCoord3fv glTexCoord3fv
Definition at line 411 of file qgl.h.
qglTexCoord3i
#define qglTexCoord3i glTexCoord3i
Definition at line 412 of file qgl.h.
qglTexCoord3iv
#define qglTexCoord3iv glTexCoord3iv
Definition at line 413 of file qgl.h.
qglTexCoord3s
#define qglTexCoord3s glTexCoord3s
Definition at line 414 of file qgl.h.
qglTexCoord3sv
#define qglTexCoord3sv glTexCoord3sv
Definition at line 415 of file qgl.h.
qglTexCoord4d
#define qglTexCoord4d glTexCoord4d
Definition at line 416 of file qgl.h.
qglTexCoord4dv
#define qglTexCoord4dv glTexCoord4dv
Definition at line 417 of file qgl.h.
qglTexCoord4f
#define qglTexCoord4f glTexCoord4f
Definition at line 418 of file qgl.h.
qglTexCoord4fv
#define qglTexCoord4fv glTexCoord4fv
Definition at line 419 of file qgl.h.
qglTexCoord4i
#define qglTexCoord4i glTexCoord4i
Definition at line 420 of file qgl.h.
qglTexCoord4iv
#define qglTexCoord4iv glTexCoord4iv
Definition at line 421 of file qgl.h.
qglTexCoord4s
#define qglTexCoord4s glTexCoord4s
Definition at line 422 of file qgl.h.
qglTexCoord4sv
#define qglTexCoord4sv glTexCoord4sv
Definition at line 423 of file qgl.h.
qglTexCoordPointer
#define qglTexCoordPointer glTexCoordPointer
Definition at line 424 of file qgl.h.
qglTexEnvf
#define qglTexEnvf glTexEnvf
Definition at line 425 of file qgl.h.
qglTexEnvfv
#define qglTexEnvfv glTexEnvfv
Definition at line 426 of file qgl.h.
qglTexEnvi
#define qglTexEnvi glTexEnvi
Definition at line 427 of file qgl.h.
qglTexEnviv
#define qglTexEnviv glTexEnviv
Definition at line 428 of file qgl.h.
qglTexGend
#define qglTexGend glTexGend
Definition at line 429 of file qgl.h.
qglTexGendv
#define qglTexGendv glTexGendv
Definition at line 430 of file qgl.h.
qglTexGenf
#define qglTexGenf glTexGenf
Definition at line 431 of file qgl.h.
qglTexGenfv
#define qglTexGenfv glTexGenfv
Definition at line 432 of file qgl.h.
qglTexGeni
#define qglTexGeni glTexGeni
Definition at line 433 of file qgl.h.
qglTexGeniv
#define qglTexGeniv glTexGeniv
Definition at line 434 of file qgl.h.
qglTexImage1D
#define qglTexImage1D glTexImage1D
Definition at line 435 of file qgl.h.
qglTexImage2D
#define qglTexImage2D glTexImage2D
Definition at line 436 of file qgl.h.
qglTexParameterf
#define qglTexParameterf glTexParameterf
Definition at line 437 of file qgl.h.
qglTexParameterfv
#define qglTexParameterfv glTexParameterfv
Definition at line 438 of file qgl.h.
qglTexParameteri
#define qglTexParameteri glTexParameteri
Definition at line 439 of file qgl.h.
qglTexParameteriv
#define qglTexParameteriv glTexParameteriv
Definition at line 440 of file qgl.h.
qglTexSubImage1D
#define qglTexSubImage1D glTexSubImage1D
Definition at line 441 of file qgl.h.
qglTexSubImage2D
#define qglTexSubImage2D glTexSubImage2D
Definition at line 442 of file qgl.h.
qglTranslated
#define qglTranslated glTranslated
Definition at line 443 of file qgl.h.
qglTranslatef
#define qglTranslatef glTranslatef
Definition at line 444 of file qgl.h.
qglVertex2d
#define qglVertex2d glVertex2d
Definition at line 445 of file qgl.h.
qglVertex2dv
#define qglVertex2dv glVertex2dv
Definition at line 446 of file qgl.h.
qglVertex2f
#define qglVertex2f glVertex2f
Definition at line 447 of file qgl.h.
qglVertex2fv
#define qglVertex2fv glVertex2fv
Definition at line 448 of file qgl.h.
qglVertex2i
#define qglVertex2i glVertex2i
Definition at line 449 of file qgl.h.
qglVertex2iv
#define qglVertex2iv glVertex2iv
Definition at line 450 of file qgl.h.
qglVertex2s
#define qglVertex2s glVertex2s
Definition at line 451 of file qgl.h.
qglVertex2sv
#define qglVertex2sv glVertex2sv
Definition at line 452 of file qgl.h.
qglVertex3d
#define qglVertex3d glVertex3d
Definition at line 453 of file qgl.h.
qglVertex3dv
#define qglVertex3dv glVertex3dv
Definition at line 454 of file qgl.h.
qglVertex3f
#define qglVertex3f glVertex3f
Definition at line 455 of file qgl.h.
qglVertex3fv
#define qglVertex3fv glVertex3fv
Definition at line 456 of file qgl.h.
qglVertex3i
#define qglVertex3i glVertex3i
Definition at line 457 of file qgl.h.
qglVertex3iv
#define qglVertex3iv glVertex3iv
Definition at line 458 of file qgl.h.
qglVertex3s
#define qglVertex3s glVertex3s
Definition at line 459 of file qgl.h.
qglVertex3sv
#define qglVertex3sv glVertex3sv
Definition at line 460 of file qgl.h.
qglVertex4d
#define qglVertex4d glVertex4d
Definition at line 461 of file qgl.h.
qglVertex4dv
#define qglVertex4dv glVertex4dv
Definition at line 462 of file qgl.h.
qglVertex4f
#define qglVertex4f glVertex4f
Definition at line 463 of file qgl.h.
qglVertex4fv
#define qglVertex4fv glVertex4fv
Definition at line 464 of file qgl.h.
qglVertex4i
#define qglVertex4i glVertex4i
Definition at line 465 of file qgl.h.
qglVertex4iv
#define qglVertex4iv glVertex4iv
Definition at line 466 of file qgl.h.
qglVertex4s
#define qglVertex4s glVertex4s
Definition at line 467 of file qgl.h.
qglVertex4sv
#define qglVertex4sv glVertex4sv
Definition at line 468 of file qgl.h.
qglVertexPointer
#define qglVertexPointer glVertexPointer
Definition at line 469 of file qgl.h.
qglViewport
#define qglViewport glViewport
Definition at line 470 of file qgl.h.
Function Documentation
GLhandleARB()
GLhandleARB (APIENTRYP qglGetHandleARB)
GLint()
typedef GLint (APIENTRYP qglGetUniformLocationARB)
Referenced by InitOpenGL(), R_GLSL_LoadProgram(), RB_ReadPixels(), RB_TakeVideoFrameCmd(), and Upload32().
GLvoid()
GLvoid (APIENTRYP qglDeleteObjectARB)
void()
typedef void (APIENTRYP qglActiveTextureARB)
Referenced by dclparam(), emitasm(), initRoQ(), jitter_buffer_ctl(), Menu_CursorMoved(), printtree(), R_LoadJPG(), RE_SaveJPGToBuffer(), Sys_Dialog(), Sys_LoadGameDll(), vfprint(), write_tables_only(), and yyparse().
Variable Documentation
attachedObj
GLhandleARB attachedObj
Definition at line 45 of file qgl.h.
count
GLsizei GLsizei* count
Definition at line 39 of file qgl.h.
index
GLuint index
Definition at line 80 of file qgl.h.
infoLog
GLsizei GLsizei GLcharARB* infoLog
Definition at line 76 of file qgl.h.
length
GLuint GLsizei GLsizei* length
Definition at line 48 of file qgl.h.
location
GLint location
Definition at line 82 of file qgl.h.
maxCount
GLsizei maxCount
Definition at line 77 of file qgl.h.
maxLength
GLuint GLsizei maxLength
Definition at line 76 of file qgl.h.
name
const GLcharARB* name
Definition at line 79 of file qgl.h.
normalized
GLint GLenum GLboolean normalized
Definition at line 122 of file qgl.h.
obj
GLsizei GLsizei GLhandleARB* obj
Definition at line 51 of file qgl.h.
params
GLenum GLint* params
Definition at line 74 of file qgl.h.
pname
GLenum pname
Definition at line 74 of file qgl.h.
pointer
GLenum GLvoid** pointer
Definition at line 123 of file qgl.h.
s
GLfloat s
Definition at line 37 of file qgl.h.
size
GLuint GLsizei GLsizei GLint* size
Definition at line 81 of file qgl.h.
source
GLsizei GLsizei GLcharARB* source
Definition at line 85 of file qgl.h.
stride
GLint GLenum GLboolean GLsizei stride
Definition at line 123 of file qgl.h.
string
GLsizei const GLcharARB** string
Definition at line 47 of file qgl.h.
t
GLfloat GLfloat t
Definition at line 37 of file qgl.h.
transpose
GLsizei GLboolean transpose
Definition at line 71 of file qgl.h.
type
GLuint GLsizei GLsizei GLint GLenum* type
Definition at line 81 of file qgl.h.
v
const GLuint* v
Definition at line 99 of file qgl.h.
v0
GLdouble v0
Definition at line 55 of file qgl.h.
v1
GLdouble GLdouble v1
Definition at line 56 of file qgl.h.
v2
GLdouble GLdouble GLdouble v2
Definition at line 57 of file qgl.h.
v3
GLdouble GLdouble GLdouble GLdouble v3
Definition at line 58 of file qgl.h.
value
GLsizei GLboolean const GLfloat* value
Definition at line 63 of file qgl.h.
w
GLubyte GLubyte GLubyte GLubyte w
Definition at line 98 of file qgl.h.
x
GLubyte x
Definition at line 98 of file qgl.h.
y
GLubyte GLubyte y
Definition at line 98 of file qgl.h.
z
GLubyte GLubyte GLubyte z
Definition at line 98 of file qgl.h.