ZEQ2-Lite: Game/CGame/cg_view.c File Reference
cg_view.c File Reference
#include "cg_local.h"
Macros
#define CAMERA_BOUNDS 25
#define CAMERA_SIZE 4
#define MASK_CAMERACLIP (MASK_SOLID|CONTENTS_PLAYERCLIP)
#define NECK_LENGTH 8
#define WAVE_AMPLITUDE 1
#define WAVE_FREQUENCY 0.4
Functions
static void AddEarthquakeTremble (earthquake_t *quake)
void CG_AddBufferedSound (sfxHandle_t sfx)
void CG_AddEarthquake (const vec3_t origin, float radius, float duration, float fadeIn, float fadeOut, float amplitude)
void CG_AdjustEarthquakes (const vec3_t delta)
static int CG_CalcFov (void)
static int CG_CalcViewValues (void)
static void CG_CalcVrect (void)
void CG_Camera (centity_t *cent)
static void CG_DamageBlendBlob (void)
void CG_DrawActiveFrame (int serverTime, stereoFrame_t stereoView, qboolean demoPlayback)
static void CG_PlayBufferedSounds (void)
static void CG_PowerupTimerSounds (void)
static void CG_StepOffset (void)
qboolean CG_WorldCoordToScreenCoordFloat (vec3_t worldCoord, float *x, float *y)
qboolean CG_WorldCoordToScreenCoordVec (vec3_t world, vec2_t screen)
void CG_ZoomDown_f (void)
void CG_ZoomUp_f (void)
Variables
vec3_t cameraCurAng
vec3_t cameraCurLoc
int cameraLastFrame
Macro Definition Documentation
CAMERA_BOUNDS
#define CAMERA_BOUNDS 25
Definition at line 138 of file cg_view.c.
CAMERA_SIZE
#define CAMERA_SIZE 4
Definition at line 28 of file cg_view.c.
MASK_CAMERACLIP
#define MASK_CAMERACLIP (MASK_SOLID|CONTENTS_PLAYERCLIP)
Definition at line 27 of file cg_view.c.
NECK_LENGTH
#define NECK_LENGTH 8
Definition at line 137 of file cg_view.c.
WAVE_AMPLITUDE
#define WAVE_AMPLITUDE 1
Definition at line 298 of file cg_view.c.
WAVE_FREQUENCY
#define WAVE_FREQUENCY 0.4
Definition at line 299 of file cg_view.c.
Function Documentation
AddEarthquakeTremble()
static void AddEarthquakeTremble (earthquake_t * quake) static
Definition at line 514 of file cg_view.c.
{
     int time;
     float a;
     const float offsetAmplitude = 0.2;
     const float angleAmplitude = 0.2;
     if(quake){
         if(cg.time >= quake->endTime){
             memset(quake, 0, sizeof(*quake));
             return;
         }
         if(quake->radius > 0){
             float distance;
             distance = Distance(cg.refdef.vieworg, quake->origin);
             if(distance >= quake->radius) return;
             a = 1 - (distance / quake->radius);
         }
         else{
             a = 1;
         }
         time = cg.time - quake->startTime;
         a *= quake->amplitude / 100;
         if(time < quake->fadeInTime){
             a *= (float)time / (float)(quake->fadeInTime);
         }
         else if(cg.time > quake->endTime - quake->fadeOutTime){
             a *= (float)(quake->endTime - cg.time) / (float)(quake->fadeOutTime);
         }
     }
     else{
         a = cg.additionalTremble;
     }
     cg.refdef.vieworg[0] += offsetAmplitude * a * crandom();
     cg.refdef.vieworg[1] += offsetAmplitude * a * crandom();
     cg.refdef.vieworg[2] += offsetAmplitude * a * crandom();
     cg.refdefViewAngles[YAW] += angleAmplitude * a * crandom();
     cg.refdefViewAngles[PITCH] += angleAmplitude * a * crandom();
     cg.refdefViewAngles[ROLL] += angleAmplitude * a * crandom();
 }
References cg_t::additionalTremble, earthquake_t::amplitude, cg, crandom, Distance(), earthquake_t::endTime, earthquake_t::fadeInTime, earthquake_t::fadeOutTime, earthquake_t::origin, PITCH, earthquake_t::radius, cg_t::refdef, cg_t::refdefViewAngles, ROLL, earthquake_t::startTime, cg_t::time, refdef_t::vieworg, and YAW.
Referenced by CG_CalcViewValues(), and CG_Camera().
CG_AddBufferedSound()
void CG_AddBufferedSound (sfxHandle_t sfx)
Definition at line 658 of file cg_view.c.
{
     if(!sfx )
         return;
     cg.soundBuffer[cg.soundBufferIn] = sfx;
     cg.soundBufferIn = (cg.soundBufferIn + 1) % MAX_SOUNDBUFFER;
     if(cg.soundBufferIn == cg.soundBufferOut){
         cg.soundBufferOut++;
     }
 }
References cg, MAX_SOUNDBUFFER, cg_t::soundBuffer, cg_t::soundBufferIn, and cg_t::soundBufferOut.
CG_AddEarthquake()
void CG_AddEarthquake (const vec3_t origin, float radius, float duration, float fadeIn, float fadeOut, float amplitude)
Definition at line 439 of file cg_view.c.
  {
     int i;
     // So camera dosn't make your head explode from too much shaking ...
     if(amplitude > 1500 ){
         amplitude = 1500;
     }
     if(duration <= 0){
         float a;
         a = amplitude / 100;
         if(radius > 0){
             float distance;
             distance = Distance(cg.refdef.vieworg, origin);
             if(distance >= radius) return;
             a *= 1 - (distance / radius);
         }
         cg.additionalTremble += a;
         return;
     }
     for (i = 0; i < MAX_EARTHQUAKES; i++){
         earthquake_t* quake;
         quake = &cg.earthquakes[i];
         if(quake->startTime) continue;
         quake->startTime = cg.time;
         quake->endTime = (int) floor(cg.time + 1000 * duration + 0.5);
         quake->fadeInTime = (int) floor(1000 * fadeIn + 0.5);
         quake->fadeOutTime = (int) floor(1000 * fadeOut + 0.5);
         quake->amplitude = amplitude;
         VectorCopy(origin, quake->origin);
         quake->radius = radius;
         break;
     }
 }
References cg_t::additionalTremble, earthquake_t::amplitude, cg, Distance(), cg_t::earthquakes, earthquake_t::endTime, earthquake_t::fadeInTime, earthquake_t::fadeOutTime, int(), MAX_EARTHQUAKES, earthquake_t::origin, earthquake_t::radius, cg_t::refdef, earthquake_t::startTime, cg_t::time, VectorCopy, and refdef_t::vieworg.
Referenced by CG_AuraStart(), CG_EntityEvent(), CG_MakeUserExplosion(), CG_Missile(), and CG_Player().
CG_AdjustEarthquakes()
void CG_AdjustEarthquakes (const vec3_t delta)
Definition at line 493 of file cg_view.c.
{
     int i;
     for (i = 0; i < MAX_EARTHQUAKES; i++){
         earthquake_t* quake;
         quake = &cg.earthquakes[i];
         if(!quake->startTime) continue;
         if(quake->radius <= 0) continue;
         VectorAdd(quake->origin, delta, quake->origin);
     }
 }
References cg, cg_t::earthquakes, MAX_EARTHQUAKES, earthquake_t::origin, earthquake_t::radius, earthquake_t::startTime, and VectorAdd.
CG_CalcFov()
static int CG_CalcFov (void) static
Definition at line 301 of file cg_view.c.
{
     float   x;
     float   phase;
     float   v;
     int     contents;
     float   fov_x, fov_y;
     float   zoomFov;
     float   f;
     int     inwater;
     if(cg.predictedPlayerState.pm_type == PM_INTERMISSION ){
         // if in intermission, use a fixed value
         fov_x = 90;
     } else{
         // user selectable
         if(cgs.dmflags & DF_FIXED_FOV ){
             // dmflag to prevent wide fov for all clients
             fov_x = 90;
         } else{
             fov_x = cg_fov.value;
             if(fov_x < 1 ){
                 fov_x = 1;
             } else if(fov_x > 160 ){
                 fov_x = 160;
             }
         }
         // account for zooms
         zoomFov = cg_zoomFov.value;
         if(zoomFov < 1 ){
             zoomFov = 1;
         } else if(zoomFov > 160 ){
             zoomFov = 160;
         }
         if(cg.zoomed ){
             f = (cg.time - cg.zoomTime ) / (float)ZOOM_TIME;
             if(f > 1.0 ){
                 fov_x = zoomFov;
             } else{
                 fov_x = fov_x + f * (zoomFov - fov_x);
             }
         } else{
             f = (cg.time - cg.zoomTime ) / (float)ZOOM_TIME;
             if(f > 1.0 ){
                 fov_x = fov_x;
             } else{
                 fov_x = zoomFov + f * (fov_x - zoomFov);
             }
         }
     }
     x = cg.refdef.width / tan(fov_x / 360 * M_PI);
     fov_y = atan2(cg.refdef.height, x);
     fov_y = fov_y * 360 / M_PI;
     // warp if underwater
     contents = CG_PointContents(cg.refdef.vieworg, -1);
     if(contents & (CONTENTS_WATER | CONTENTS_SLIME | CONTENTS_LAVA ) ){
         phase = cg.time / 1000.0 * WAVE_FREQUENCY * M_PI * 2;
         v = WAVE_AMPLITUDE * sin(phase);
         fov_x += v;
         fov_y -= v;
         inwater = qtrue;
     }
     else{
         inwater = qfalse;
     }
     // set it
     cg.refdef.fov_x = fov_x;
     cg.refdef.fov_y = fov_y;
     if(!cg.zoomed ){
         cg.zoomSensitivity = 1;
     } else{
         cg.zoomSensitivity = cg.refdef.fov_y / 75.0;
     }
     return inwater;
 }
References cg, cg_fov, CG_PointContents(), cg_zoomFov, cgs, CONTENTS_LAVA, CONTENTS_SLIME, CONTENTS_WATER, DF_FIXED_FOV, cgs_t::dmflags, refdef_t::fov_x, refdef_t::fov_y, refdef_t::height, M_PI, PM_INTERMISSION, cg_t::predictedPlayerState, qfalse, qtrue, cg_t::refdef, cg_t::time, vmCvar_t::value, refdef_t::vieworg, WAVE_AMPLITUDE, WAVE_FREQUENCY, refdef_t::width, ZOOM_TIME, cg_t::zoomed, cg_t::zoomSensitivity, and cg_t::zoomTime.
Referenced by CG_CalcViewValues().
CG_CalcViewValues()
static int CG_CalcViewValues (void) static
Definition at line 567 of file cg_view.c.
{
     playerState_t   *ps;
     memset(&cg.refdef, 0, sizeof(cg.refdef ));
     CG_CalcVrect();
     ps = &cg.predictedPlayerState;
     if(ps->pm_type == PM_INTERMISSION){
         VectorCopy(ps->origin, cg.refdef.vieworg);
         VectorCopy(ps->viewangles, cg.refdefViewAngles);
         AnglesToAxis(cg.refdefViewAngles, cg.refdef.viewaxis);
         return CG_CalcFov();
     }
     cg.bobcycle = (ps->bobCycle & 128 ) >> 7;
     cg.bobfracsin = fabs(sin((ps->bobCycle & 127 ) / 127.0 * M_PI ));
     cg.xyspeed = sqrt(ps->velocity[0] * ps->velocity[0] +
         ps->velocity[1] * ps->velocity[1]);
     VectorCopy(ps->origin, cg.refdef.vieworg);
     VectorCopy(ps->viewangles, cg.refdefViewAngles);
     if(cg_cameraOrbit.integer){
         if(cg.time > cg.nextOrbitTime){
             cg.nextOrbitTime = cg.time + cg_cameraOrbitDelay.integer;
             cg_thirdPersonAngle.value += cg_cameraOrbit.value;
         }
     }
     if(cg_errorDecay.value > 0){
         int     t;
         float   f;
         t = cg.time - cg.predictedErrorTime;
         f = (cg_errorDecay.value - t ) / cg_errorDecay.value;
         if(f > 0 && f < 1 ){
             VectorMA(cg.refdef.vieworg, f, cg.predictedError, cg.refdef.vieworg);
         } else{
             cg.predictedErrorTime = 0;
         }
     }
 #if EARTHQUAKE_SYSTEM   // JUHOX: add earthquakes
     {
         int i;
         for (i = 0; i < MAX_EARTHQUAKES; i++){
             earthquake_t* quake;
             quake = &cg.earthquakes[i];
             if(!quake->startTime) continue;
             AddEarthquakeTremble(quake);
         }
         AddEarthquakeTremble(NULL); // additional tremble
     }
 #endif
     // position eye reletive to origin
     AnglesToAxis(cg.refdefViewAngles, cg.refdef.viewaxis);
     if(cg.hyperspace ){
         cg.refdef.rdflags |= RDF_NOWORLDMODEL | RDF_HYPERSPACE;
     }
     // field of view
     return CG_CalcFov();
 }
References AddEarthquakeTremble(), AnglesToAxis(), cg_t::bobcycle, cg_t::bobfracsin, cg, CG_CalcFov(), CG_CalcVrect(), cg_cameraOrbit, cg_cameraOrbitDelay, cg_errorDecay, cg_thirdPersonAngle, cg_t::earthquakes, cg_t::hyperspace, vmCvar_t::integer, M_PI, MAX_EARTHQUAKES, cg_t::nextOrbitTime, NULL, PM_INTERMISSION, cg_t::predictedError, cg_t::predictedErrorTime, cg_t::predictedPlayerState, RDF_HYPERSPACE, RDF_NOWORLDMODEL, refdef_t::rdflags, cg_t::refdef, cg_t::refdefViewAngles, earthquake_t::startTime, cg_t::time, vmCvar_t::value, VectorCopy, VectorMA(), refdef_t::viewaxis, refdef_t::vieworg, and cg_t::xyspeed.
Referenced by CG_DrawActiveFrame().
CG_CalcVrect()
static void CG_CalcVrect (void) static
Definition at line 37 of file cg_view.c.
{
     int     size;
     // the intermission should allways be full screen
     if(cg.snap->ps.pm_type == PM_INTERMISSION ){
         size = 100;
     } else{
         // bound normal viewsize
         if(cg_viewsize.integer < 30){
             trap_Cvar_Set ("cg_viewsize","30");
             size = 30;
         } else if(cg_viewsize.integer > 100){
             trap_Cvar_Set ("cg_viewsize","100");
             size = 100;
         } else{
             size = cg_viewsize.integer;
         }
     }
     cg.refdef.width = cgs.glconfig.vidWidth*size/100;
     cg.refdef.width &= ~1;
     cg.refdef.height = cgs.glconfig.vidHeight*size/100;
     cg.refdef.height &= ~1;
     cg.refdef.x = (cgs.glconfig.vidWidth - cg.refdef.width)/2;
     cg.refdef.y = (cgs.glconfig.vidHeight - cg.refdef.height)/2;
 }
References cg, cg_viewsize, cgs, cgs_t::glconfig, refdef_t::height, vmCvar_t::integer, PM_INTERMISSION, snapshot_t::ps, cg_t::refdef, cg_t::snap, trap_Cvar_Set(), glconfig_t::vidHeight, glconfig_t::vidWidth, refdef_t::width, refdef_t::x, and refdef_t::y.
Referenced by CG_CalcViewValues().
CG_Camera()
void CG_Camera (centity_t * cent)
Definition at line 142 of file cg_view.c.
{
     static vec3_t   cameramins = { -CAMERA_SIZE, -CAMERA_SIZE, -CAMERA_SIZE };
     static vec3_t   cameramaxs = { CAMERA_SIZE, CAMERA_SIZE, CAMERA_SIZE };
     vec3_t          view, right, forward, up, overrideAngles, overrideOrg, focusAngles, focusPoint, tagForwardAngles, locdiff, angdiff, diff;
     int             i,clientNum,cameraRange,cameraAngle,cameraSlide,cameraHeight;
     float           lerpFactor = 0.0, lerpTime, ratio, forwardScale, sideScale, focusDist;
     orientation_t   tagOrient,tagOrient2;
     trace_t         trace;
     clientInfo_t    *ci;
     tierConfig_cg   *tier;
     playerState_t   *ps;
     centity_t       targetEntity;
     char            targetTag[256];
     ps = &cg.snap->ps;
     clientNum = cent->currentState.clientNum;
     if(clientNum != ps->clientNum){return;}
     ci = &cgs.clientinfo[clientNum];
     tier = &ci->tierConfig[ci->tierCurrent];
     cameraAngle = cg_thirdPersonAngle.value;
     cameraSlide = cg_thirdPersonSlide.value + ci->tierConfig[ci->tierCurrent].cameraOffset[0];
     cameraHeight = cg_thirdPersonHeight.value + ci->tierConfig[ci->tierCurrent].cameraOffset[1];
     cameraRange = cg_thirdPersonRange.value + ci->tierConfig[ci->tierCurrent].cameraOffset[2];
     if(cg_thirdPersonCamera.value <= 0){
         if(CG_GetTagOrientationFromPlayerEntity(cent,"tag_eyes",&tagOrient)){
             VectorCopy(tagOrient.origin, cg.refdef.vieworg);
         }
         else if(CG_GetTagOrientationFromPlayerEntity(cent,"tag_head",&tagOrient)){
             VectorCopy(tagOrient.origin, cg.refdef.vieworg);
             cg.refdef.vieworg[2] -= NECK_LENGTH;
             AngleVectors(cg.refdefViewAngles, forward, NULL, up);
             VectorMA(cg.refdef.vieworg, 3, forward, cg.refdef.vieworg);
             VectorMA(cg.refdef.vieworg, NECK_LENGTH, up, cg.refdef.vieworg);
         }
         else{
             cg.refdef.vieworg[2] += cg.predictedPlayerState.viewheight;
         }
     }
     else if(cg_thirdPersonCamera.value >= 1){
         if(CG_GetTagOrientationFromPlayerEntity(cent, "tag_cam", &tagOrient)){
             if(!cent->pe.camera.animation->continuous){
                 VectorCopy(cent->lerpOrigin,tagOrient.origin);
                 tagOrient.origin[2] += cg.predictedPlayerState.viewheight;
             }
             else if(!((cent->currentState.weaponstate == WEAPON_GUIDING)
                 || (cent->currentState.weaponstate == WEAPON_ALTGUIDING)
                 || (cent->currentState.playerBitFlags & usingSoar))){
                     if(CG_GetTagOrientationFromPlayerEntity(cent, "tag_camTar", &tagOrient2)){
                     VectorSubtract(tagOrient2.origin, tagOrient.origin, forward);
                     VectorNormalize(forward);
                     vectoangles(forward, tagForwardAngles);
                     cg.refdefViewAngles[YAW] = tagForwardAngles[YAW];
                     cg.refdefViewAngles[PITCH] = tagForwardAngles[PITCH];
                 }
             }
             if((cg_beamControl.value == 0) && ((cent->currentState.weaponstate == WEAPON_GUIDING)
                 || (cent->currentState.weaponstate == WEAPON_ALTGUIDING)) && (cg.guide_view)){
                     float oldRoll;
                     VectorSubtract(cg.guide_target, tagOrient.origin, forward);
                     VectorNormalize(forward);
                     oldRoll = cg.refdefViewAngles[ROLL];
                     vectoangles(forward, cg.refdefViewAngles);
                     cg.refdefViewAngles[ROLL] = oldRoll;
                     VectorCopy(tagOrient.origin,cg.guide_target);
                     cg.guide_view = qfalse;
             }
             VectorCopy(cg.refdefViewAngles, overrideAngles);
             VectorCopy(tagOrient.origin, overrideOrg);
             cg.refdef.vieworg[2] += cg.predictedPlayerState.viewheight;
             VectorCopy(cg.refdefViewAngles, focusAngles);
             AngleVectors(focusAngles, forward, NULL, NULL);
             VectorMA(tagOrient.origin, 512, forward, focusPoint);
             VectorCopy(tagOrient.origin, view);
             AngleVectors(cg.refdefViewAngles, forward, right, up);
             if(!cent->pe.camera.animation->continuous){
                 VectorMA(view,cameraSlide,right,view);
                 view[2] += cameraHeight;
                 forwardScale = cos(cameraAngle / 180 * M_PI);
                 sideScale = sin(cameraAngle / 180 * M_PI);
                 VectorMA(view, -cameraRange * forwardScale, forward, view);
                 VectorMA(view, -cameraRange * sideScale, right, view);
                 cg.refdefViewAngles[YAW] -= cameraAngle;
             }
             CG_Trace(&trace, cg.refdef.vieworg, cameramins, cameramaxs, view, clientNum, MASK_CAMERACLIP);
             if(trace.fraction != 1.0){VectorCopy(trace.endpos, cg.refdef.vieworg);}
             else{VectorCopy(view, cg.refdef.vieworg);}
             if((cent->currentState.playerBitFlags & usingSoar) || (cg_thirdPersonCamera.value >= 5)){
                 if(cameraLastFrame == 0 || cameraLastFrame > cg.time){
                     VectorCopy(cg.refdef.vieworg, cameraCurLoc);
                     cameraLastFrame = cg.time;
                 }
                 else{
                     if(cg_thirdPersonCameraDamp.value != 0.0){lerpFactor = cg_thirdPersonCameraDamp.value;}
                     if(lerpFactor>=1.0 || cg.thisFrameTeleport || cent->currentState.playerBitFlags & usingZanzoken){
                             VectorCopy(cg.refdef.vieworg, cameraCurLoc);
                     }
                     else if(lerpFactor>=0.0){
                         VectorSubtract(cg.refdef.vieworg, cameraCurLoc, locdiff);
                         lerpFactor = 1.0-lerpFactor;
                         VectorMA(cg.refdef.vieworg, -lerpFactor, locdiff, cameraCurLoc);
                     }
                     CG_Trace(&trace, cg.refdef.vieworg, cameramins, cameramaxs, cameraCurLoc, cg.snap->ps.clientNum, MASK_CAMERACLIP);
                     if(trace.fraction < 1.0){VectorCopy( trace.endpos, cameraCurLoc );}
                 }
                 if(cg_thirdPersonCamera.value >= 6){
                     VectorMA(view, 500, forward, cameraCurAng);
                     VectorSubtract(cameraCurAng, cameraCurLoc, diff);
                     {
                         float dist = VectorNormalize(diff);
                         if(!dist || (diff[0] == 0 || diff[1] == 0)){
                             VectorCopy( forward, diff );
                         }
                     }
                     vectoangles(diff, cg.refdefViewAngles);
                 }
                 VectorCopy(cameraCurLoc, cg.refdef.vieworg);
                 cameraLastFrame = cg.time;
             }
             else{VectorCopy(cg.refdef.vieworg, cameraCurLoc);}
             AnglesToAxis(cg.refdefViewAngles, cg.refdef.viewaxis);
         }
     }
     for(i = 0;i < MAX_EARTHQUAKES;i++){
         earthquake_t* quake;
         quake = &cg.earthquakes[i];
         if(!quake->startTime){continue;}
         AddEarthquakeTremble(quake);
     }
     AddEarthquakeTremble(NULL);
 }
References AddEarthquakeTremble(), AnglesToAxis(), AngleVectors(), CAMERA_SIZE, cameraCurAng, cameraCurLoc, cameraLastFrame, tierConfig_cg::cameraOffset, cg, cg_beamControl, CG_GetTagOrientationFromPlayerEntity(), cg_thirdPersonAngle, cg_thirdPersonCamera, cg_thirdPersonCameraDamp, cg_thirdPersonHeight, cg_thirdPersonRange, cg_thirdPersonSlide, CG_Trace(), cgs, cgs_t::clientinfo, diff, cg_t::earthquakes, trace_t::endpos, forward, trace_t::fraction, cg_t::guide_target, cg_t::guide_view, M_PI, MASK_CAMERACLIP, MAX_EARTHQUAKES, NECK_LENGTH, NULL, orientation_t::origin, PITCH, cg_t::predictedPlayerState, snapshot_t::ps, qfalse, cg_t::refdef, cg_t::refdefViewAngles, right, ROLL, cg_t::snap, earthquake_t::startTime, cg_t::thisFrameTeleport, clientInfo_t::tierConfig, clientInfo_t::tierCurrent, cg_t::time, up, usingSoar, usingZanzoken, vmCvar_t::value, vectoangles(), VectorCopy, VectorMA(), VectorNormalize(), VectorSubtract, refdef_t::viewaxis, refdef_t::vieworg, WEAPON_ALTGUIDING, WEAPON_GUIDING, and YAW.
Referenced by CG_Player().
CG_DamageBlendBlob()
static void CG_DamageBlendBlob (void) static
Definition at line 391 of file cg_view.c.
{
     int         t;
     int         maxTime;
     refEntity_t     ent;
     if(!cg.damageValue ){
         return;
     }
     //if(cg.cameraMode){
     //  return;
     //}
     // ragePro systems can't fade blends, so don't obscure the screen
     if ( cgs.glconfig.hardwareType == GLHW_RAGEPRO ) {
         return;
     }
     maxTime = DAMAGE_TIME;
     t = cg.time - cg.damageTime;
     if(t <= 0 || t >= maxTime ){
         return;
     }
     memset(&ent, 0, sizeof(ent ));
     ent.reType = RT_SPRITE;
     ent.renderfx = RF_FIRST_PERSON;
     VectorMA(cg.refdef.vieworg, 8, cg.refdef.viewaxis[0], ent.origin);
     VectorMA(ent.origin, cg.damageX * -8, cg.refdef.viewaxis[1], ent.origin);
     VectorMA(ent.origin, cg.damageY * 8, cg.refdef.viewaxis[2], ent.origin);
     ent.radius = cg.damageValue * 3;
     ent.customShader = cgs.media.viewBloodShader;
     ent.shaderRGBA[0] = 255;
     ent.shaderRGBA[1] = 255;
     ent.shaderRGBA[2] = 255;
     ent.shaderRGBA[3] = 200 * (1.0 - ((float)t / maxTime));
     trap_R_AddRefEntityToScene(&ent);
 }
References cg, cgs, refEntity_t::customShader, DAMAGE_TIME, cg_t::damageTime, cg_t::damageValue, cg_t::damageX, cg_t::damageY, cgs_t::glconfig, GLHW_RAGEPRO, glconfig_t::hardwareType, cgs_t::media, refEntity_t::origin, refEntity_t::radius, cg_t::refdef, refEntity_t::renderfx, refEntity_t::reType, RF_FIRST_PERSON, RT_SPRITE, refEntity_t::shaderRGBA, cg_t::time, trap_R_AddRefEntityToScene(), VectorMA(), refdef_t::viewaxis, cgMedia_t::viewBloodShader, and refdef_t::vieworg.
Referenced by CG_DrawActiveFrame().
CG_DrawActiveFrame()
void CG_DrawActiveFrame (int serverTime, stereoFrame_t stereoView, qboolean demoPlayback)
Definition at line 693 of file cg_view.c.
{
     int     inwater;
     float   attenuation;
     char    var[MAX_TOKEN_CHARS];
     cg.time = serverTime;
     cg.demoPlayback = demoPlayback;
     // update cvars
     CG_UpdateCvars();
     // if we are only updating the screen as a loading
     // pacifier, don't even try to read snapshots
     if(cg.infoScreenText[0] != 0 ){
         CG_DrawInformation();
         return;
     }
     // any looped sounds will be respecified as entities
     // are added to the render list
     trap_S_ClearLoopingSounds(qfalse);
     // clear all the render lists
     trap_R_ClearScene();
     // set up cg.snap and possibly cg.nextSnap
     CG_ProcessSnapshots();
     // if we haven't received any snapshots yet, all
     // we can draw is the information screen
     if(!cg.snap || (cg.snap->snapFlags & SNAPFLAG_NOT_ACTIVE ) ){
         CG_DrawInformation();
         return;
     }
     if(cg.tierSelect > -1)  {
         switch(cg.tierSelectionMode) {
             case 1:
                 cg.tierCurrent--;
                 break;
             case 2:
                 cg.tierCurrent++;
                 break;
             default:
                 cg.tierCurrent = cg.tierSelect;
                 break;
         }
     }
     // let the client system know what our weapon and zoom settings are
     trap_SetUserCmdValue(cg.weaponDesired > 0 ? cg.weaponDesired : cg.weaponSelect, cg.zoomSensitivity, cg.tierCurrent, cg.weaponSelectionMode, cg.tierSelectionMode);
     // this counter will be bumped for every valid scene we generate
     cg.clientFrame++;
     // update cg.predictedPlayerState
     CG_PredictPlayerState();
     // decide on third person view
     cg.renderingThirdPerson = cg_thirdPerson.integer ||
                              (cg.snap->ps.powerLevel[plFatigue] <= 0) ||
                              (cg.snap->ps.bitFlags & isCrashed) ||
                              (cg.snap->ps.weaponstate == WEAPON_GUIDING) ||
                              (cg.snap->ps.weaponstate == WEAPON_ALTGUIDING);
     // END ADDING
     // build cg.refdef
     inwater = CG_CalcViewValues();
 #if EARTHQUAKE_SYSTEM
     cg.additionalTremble = 0;   // JUHOX
 #endif
     // first person blend blobs, done after AnglesToAxis
     if(!cg.renderingThirdPerson ){
         CG_DamageBlendBlob();
     }
     // build the render lists
     if(!cg.hyperspace ){
         CG_FrameHist_NextFrame();
         CG_AddPacketEntities();         // adter calcViewValues, so predicted player state is correct
         CG_AddBeamTables();
         CG_AddTrailsToScene();
         CG_AddMarks();
         CG_AddParticles ();
         CG_AddLocalEntities();
         CG_AddParticleSystems();
     }
     //CG_AddViewWeapon(&cg.predictedPlayerState);
     // add buffered sounds
     CG_PlayBufferedSounds();
     // play buffered voice chats
     CG_PlayBufferedVoiceChats();
     // finish up the rest of the refdef
     cg.refdef.time = cg.time;
     memcpy(cg.refdef.areamask, cg.snap->areamask, sizeof(cg.refdef.areamask ));
     // warning sounds when powerup is wearing off
     CG_PowerupTimerSounds();
     attenuation = cg_soundAttenuation.value; // 0.0001f; // Quake 3 default was 0.0008f;
     // update audio positions
     trap_S_Respatialize(cg.snap->ps.clientNum, cg.refdef.vieworg, cg.refdef.viewaxis, inwater, attenuation);
     if(stereoView != STEREO_RIGHT ){
         cg.frametime = cg.time - cg.oldTime;
         if(cg.frametime < 0 ){
             cg.frametime = 0;
         }
         cg.oldTime = cg.time;
     }
     if(cg_timescale.value != cg_timescaleFadeEnd.value){
         if(cg_timescale.value < cg_timescaleFadeEnd.value){
             cg_timescale.value += cg_timescaleFadeSpeed.value * ((float)cg.frametime) / 1000;
             if(cg_timescale.value > cg_timescaleFadeEnd.value)
                 cg_timescale.value = cg_timescaleFadeEnd.value;
         }
         else{
             cg_timescale.value -= cg_timescaleFadeSpeed.value * ((float)cg.frametime) / 1000;
             if(cg_timescale.value < cg_timescaleFadeEnd.value)
                 cg_timescale.value = cg_timescaleFadeEnd.value;
         }
         if(cg_timescaleFadeSpeed.value){
             trap_Cvar_Set("timescale", va("%f", cg_timescale.value));
         }
     }
     // actually issue the rendering calls
     CG_DrawActive(stereoView);
     CG_CheckMusic();
     trap_Cvar_VariableStringBuffer("cl_paused", var, sizeof(var ));
     cgs.clientPaused = atoi(var);
     if(cg_stats.integer ){
         CG_Printf("cg.clientFrame:%i\n", cg.clientFrame);
     }
 }
References cg_t::additionalTremble, snapshot_t::areamask, refdef_t::areamask, attenuation, cg, CG_AddBeamTables(), CG_AddLocalEntities(), CG_AddMarks(), CG_AddPacketEntities(), CG_AddParticles(), CG_AddParticleSystems(), CG_AddTrailsToScene(), CG_CalcViewValues(), CG_CheckMusic(), CG_DamageBlendBlob(), CG_DrawActive(), CG_DrawInformation(), CG_FrameHist_NextFrame(), CG_PlayBufferedSounds(), CG_PlayBufferedVoiceChats(), CG_PowerupTimerSounds(), CG_PredictPlayerState(), CG_Printf(), CG_ProcessSnapshots(), cg_soundAttenuation, cg_stats, cg_thirdPerson, cg_timescale, cg_timescaleFadeEnd, cg_timescaleFadeSpeed, CG_UpdateCvars(), cgs, cg_t::clientFrame, cgs_t::clientPaused, cg_t::demoPlayback, cg_t::frametime, cg_t::hyperspace, cg_t::infoScreenText, vmCvar_t::integer, isCrashed, MAX_TOKEN_CHARS, cg_t::oldTime, plFatigue, snapshot_t::ps, qfalse, cg_t::refdef, cg_t::renderingThirdPerson, cg_t::snap, SNAPFLAG_NOT_ACTIVE, snapshot_t::snapFlags, STEREO_RIGHT, cg_t::tierCurrent, cg_t::tierSelect, cg_t::tierSelectionMode, refdef_t::time, cg_t::time, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_R_ClearScene(), trap_S_ClearLoopingSounds(), trap_S_Respatialize(), trap_SetUserCmdValue(), va(), vmCvar_t::value, refdef_t::viewaxis, refdef_t::vieworg, WEAPON_ALTGUIDING, WEAPON_GUIDING, cg_t::weaponDesired, cg_t::weaponSelect, cg_t::weaponSelectionMode, and cg_t::zoomSensitivity.
Referenced by vmMain().
CG_PlayBufferedSounds()
static void CG_PlayBufferedSounds (void) static
Definition at line 673 of file cg_view.c.
{
     if(cg.soundTime < cg.time ){
         if(cg.soundBufferOut != cg.soundBufferIn && cg.soundBuffer[cg.soundBufferOut]){
             trap_S_StartLocalSound(cg.soundBuffer[cg.soundBufferOut], CHAN_ANNOUNCER);
             cg.soundBuffer[cg.soundBufferOut] = 0;
             cg.soundBufferOut = (cg.soundBufferOut + 1) % MAX_SOUNDBUFFER;
             cg.soundTime = cg.time + 750;
         }
     }
 }
References cg, CHAN_ANNOUNCER, MAX_SOUNDBUFFER, cg_t::soundBuffer, cg_t::soundBufferIn, cg_t::soundBufferOut, cg_t::soundTime, cg_t::time, and trap_S_StartLocalSound().
Referenced by CG_DrawActiveFrame().
CG_PowerupTimerSounds()
static void CG_PowerupTimerSounds (void) static
Definition at line 634 of file cg_view.c.
{
     int     i;
     int     t;
     // powerup timers going away
     for (i = 0 ; i < MAX_POWERUPS ; i++ ){
         t = cg.snap->ps.powerups[i];
         if(t <= cg.time ){
             continue;
         }
         if(t - cg.time >= POWERUP_BLINKS * POWERUP_BLINK_TIME ){
             continue;
         }
         if((t - cg.time ) / POWERUP_BLINK_TIME != (t - cg.oldTime ) / POWERUP_BLINK_TIME ){
             trap_S_StartSound(NULL, cg.snap->ps.clientNum, CHAN_ITEM, cgs.media.wearOffSound);
         }
     }
 }
References cg, cgs, CHAN_ITEM, MAX_POWERUPS, cgs_t::media, NULL, cg_t::oldTime, POWERUP_BLINK_TIME, POWERUP_BLINKS, snapshot_t::ps, cg_t::snap, cg_t::time, trap_S_StartSound(), and cgMedia_t::wearOffSound.
Referenced by CG_DrawActiveFrame().
CG_StepOffset()
static void CG_StepOffset (void) static
Definition at line 123 of file cg_view.c.
{
     int     timeDelta;
     // smooth out stair climbing
     timeDelta = cg.time - cg.stepTime;
     if(timeDelta < STEP_TIME ){
         cg.refdef.vieworg[2] -= cg.stepChange
             * (STEP_TIME - timeDelta) / STEP_TIME;
     }
 }
References cg, cg_t::refdef, STEP_TIME, cg_t::stepChange, cg_t::stepTime, cg_t::time, and refdef_t::vieworg.
CG_WorldCoordToScreenCoordFloat()
qboolean CG_WorldCoordToScreenCoordFloat (vec3_t worldCoord, float * x, float * y)
Definition at line 80 of file cg_view.c.
{
     float xcenter, ycenter;
     vec3_t local, transformed;
     vec3_t vforward;
     vec3_t vright;
     vec3_t vup;
     float xzi;
     float yzi;
     xcenter = 640.0f / 2.0f;//gives screen coords in virtual 640x480, to be adjusted when drawn
     ycenter = 480.0f / 2.0f;//gives screen coords in virtual 640x480, to be adjusted when drawn
     AngleVectors(cg.refdefViewAngles, vforward, vright, vup);
     VectorSubtract(worldCoord, cg.refdef.vieworg, local);
     transformed[0] = DotProduct(local,vright);
     transformed[1] = DotProduct(local,vup);
     transformed[2] = DotProduct(local,vforward);
     // Make sure Z is not negative.
     if(transformed[2] < 0.01f){
         return qfalse;
     }
     xzi = xcenter / transformed[2] * ( 96.0f / cg.refdef.fov_x);
     yzi = ycenter / transformed[2] * (102.0f / cg.refdef.fov_y);
     *x = xcenter + xzi * transformed[0];
     *y = ycenter - yzi * transformed[1];
     return qtrue;
 }
References AngleVectors(), cg, DotProduct, refdef_t::fov_x, refdef_t::fov_y, local, qfalse, qtrue, cg_t::refdef, cg_t::refdefViewAngles, VectorSubtract, and refdef_t::vieworg.
Referenced by CG_DrawCrosshair(), and CG_WorldCoordToScreenCoordVec().
CG_WorldCoordToScreenCoordVec()
qboolean CG_WorldCoordToScreenCoordVec (vec3_t world, vec2_t screen)
Definition at line 115 of file cg_view.c.
{
     return CG_WorldCoordToScreenCoordFloat(world, &screen[0], &screen[1]);
 }
References CG_WorldCoordToScreenCoordFloat(), and screen.
Referenced by CG_Aura_GetHullPoints().
CG_ZoomDown_f()
void CG_ZoomDown_f (void)
Definition at line 274 of file cg_view.c.
{
     if(cg.zoomed ){
         return;
     }
     cg.zoomed = qtrue;
     cg.zoomTime = cg.time;
 }
References cg, qtrue, cg_t::time, cg_t::zoomed, and cg_t::zoomTime.
CG_ZoomUp_f()
void CG_ZoomUp_f (void)
Definition at line 282 of file cg_view.c.
{
     if(!cg.zoomed ){
         return;
     }
     cg.zoomed = qfalse;
     cg.zoomTime = cg.time;
 }
References cg, qfalse, cg_t::time, cg_t::zoomed, and cg_t::zoomTime.
Variable Documentation
cameraCurAng
vec3_t cameraCurAng
Definition at line 140 of file cg_view.c.
Referenced by CG_Camera().
cameraCurLoc
vec3_t cameraCurLoc
Definition at line 139 of file cg_view.c.
Referenced by CG_Camera().
cameraLastFrame
int cameraLastFrame
Definition at line 141 of file cg_view.c.
Referenced by CG_Camera().