ZEQ2-Lite: Tools/zMesh Exporter/mathlib.c File Reference
mathlib.c File Reference
#include "cmdlib.h"
#include "mathlib.h"
Functions
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
void AnglesToMatrix (vec3_t in, vec3_t out[3])
void ClearBounds (vec3_t mins, vec3_t maxs)
vec_t ColorNormalize (const vec3_t in, vec3_t out)
void CrossProduct (const vec3_t v1, const vec3_t v2, vec3_t cross)
void MakeNormalVectors (vec3_t forward, vec3_t right, vec3_t up)
void MatrixInvert (vec3_t m[3], vec3_t inv[3])
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
void OldVectorInverseRotate (vec3_t v, float r[3][3], vec3_t d)
void PerpendicularVector (vec3_t dst, const vec3_t src)
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
vec_t Q_rint (vec_t in)
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
qboolean VectorCompare (const vec3_t v1, const vec3_t v2)
void VectorInverseRotate (vec3_t v, float r[3][3], vec3_t d)
double VectorLength (const vec3_t v)
void VectorMA (const vec3_t va, double scale, const vec3_t vb, vec3_t vc)
vec_t VectorNormalize (const vec3_t in, vec3_t out)
void VectorRotate (vec3_t v, float r[3][3], vec3_t d)
Variables
vec3_t vec3_origin = {0,0,0}
Function Documentation
AddPointToBounds()
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 217 of file mathlib.c.
{
     int     i;
     vec_t   val;
     for (i=0 ; i<3 ; i++) {
         val = v[i];
         if (val < mins[i])
             mins[i] = val;
         if (val > maxs[i])
             maxs[i] = val;
     }
 }
References val.
Referenced by CM_GeneratePatchCollide(), FixCoords(), ParseTriSurf(), R_CreateSurfaceGridMesh(), R_MarkFragments(), RE_AddPolyToScene(), and Think_SpawnNewDoorTrigger().
AnglesToMatrix()
void AnglesToMatrix (vec3_t in, vec3_t out[3])
Definition at line 59 of file mathlib.c.
{
     vec_t sr, sp, sy, cr, cp, cy;
     sy = sin(in[2]);
     cy = cos(in[2]);
     sp = sin(in[1]);
     cp = cos(in[1]);
     sr = sin(in[0]);
     cr = cos(in[0]);
     out[0][0] = cp*cy;
     out[1][0] = cp*sy;
     out[2][0] = -sp;
     out[0][1] = sr*sp*cy+cr*-sy;
     out[1][1] = sr*sp*sy+cr*cy;
     out[2][1] = sr*cp;
     out[0][2] = (cr*sp*cy+-sr*-sy);
     out[1][2] = (cr*sp*sy+-sr*cy);
     out[2][2] = cr*cp;
 }
References cos(), cp, cr, cy, out, sin(), sp, sr, and sy.
Referenced by LoadSMD_ParseSkeleton().
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 212 of file mathlib.c.
{
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
Referenced by CM_GeneratePatchCollide(), LoadSMD_ParseSkeleton(), ParseTriSurf(), R_AddWorldSurfaces(), R_CreateSurfaceGridMesh(), and R_MarkFragments().
ColorNormalize()
vec_t ColorNormalize (const vec3_t in, vec3_t out)
Definition at line 191 of file mathlib.c.
{
     float   max, scale;
     max = in[0];
     if (in[1] > max)
         max = in[1];
     if (in[2] > max)
         max = in[2];
     if (max == 0) {
         out[0] = out[1] = out[2] = 1.0;
         return 0;
     }
     scale = 1.0 / max;
     VectorScale (in, scale, out);
     return max;
 }
References max, out, and VectorScale.
CrossProduct()
void CrossProduct (const vec3_t v1, const vec3_t v2, vec3_t cross)
Definition at line 168 of file mathlib.c.
{
     cross[0] = v1[1]*v2[2] - v1[2]*v2[1];
     cross[1] = v1[2]*v2[0] - v1[0]*v2[2];
     cross[2] = v1[0]*v2[1] - v1[1]*v2[0];
 }
Referenced by AddWindingToConvexHull(), Autosprite2Deform(), BaseWindingForPlane(), CG_AddScorePlum(), CG_Aura_DrawInnerSpike(), CG_Aura_DrawSpike(), CG_Aura_SetHullAttributes(), CG_BezierVerts(), CG_DrawLine(), CG_DrawLineRGBA(), CG_GetTrailVerts(), CG_ImpactMark(), CG_LerpSpike(), CG_Portal(), CheckWinding(), CM_AddFacetBevels(), CM_PlaneFromPoints(), ComputeNormal(), DebugLine(), DeformText(), DistancePointLine(), MakeMeshNormals(), MakeNormalVectors(), PlaneFromPoints(), PM_SlideMove(), PSys_AccumulateParticle(), R_GetPortalOrientations(), R_MarkFragments(), RB_DrawSun(), RB_ShadowTessEnd(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RotateAroundDirection(), RotatePointAroundVector(), WindingArea(), and WindingPlane().
MakeNormalVectors()
void MakeNormalVectors (vec3_t forward, vec3_t right, vec3_t up)
Definition at line 44 of file mathlib.c.
{
     float       d;
     // this rotate and negate guarantees a vector
     // not colinear with the original
     right[1] = -forward[0];
     right[2] = forward[1];
     right[0] = forward[2];
     d = DotProduct (right, forward);
     VectorMA (right, -d, forward, right);
     VectorNormalize (right, right);
     CrossProduct (right, forward, up);
 }
References CrossProduct(), DotProduct, forward, right, up, VectorMA, and VectorNormalize().
MatrixInvert()
void MatrixInvert (vec3_t m[3], vec3_t inv[3])
Definition at line 92 of file mathlib.c.
 {
     int i,j;
     vec3_t cofactors[3];
     float determinant;
         cofactors[0][0]= m[1][1] * m[2][2] - m[2][1] * m[1][2];
         cofactors[0][1]= -(m[1][0] * m[2][2] - m[1][2] * m[2][0]);
         cofactors[0][2]= m[1][0] * m[2][1] - m[2][0] * m[1][1];
         cofactors[1][0]= -(m[0][1] * m[2][2] - m[0][2] * m[2][1]);
         cofactors[1][1]= m[0][0] * m[2][2] - m[0][2] * m[2][0];
         cofactors[1][2]= -(m[0][0] * m[2][1] - m[2][0] * m[0][1]);
         cofactors[2][0]= m[0][1] * m[1][2] - m[0][2] * m[1][1];
         cofactors[2][1]= -(m[0][0] * m[1][2] - m[1][0] * m[0][2]);
         cofactors[2][2]= m[0][0] * m[1][1] - m[1][0] * m[0][1];
         determinant = m[0][0] * cofactors[0][0] + m[0][1] * cofactors[0][1] + m[0][2] * m[0][2];
         for(i=0;i<3;i++)
         {
             for(j=0;j<3;j++)
             {
                 inv[i][j] = cofactors[j][i]/determinant;
             }
         }
 }
References m.
Referenced by VectorInverseRotate().
MatrixMultiply()
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
Definition at line 80 of file mathlib.c.
{
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] + in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] + in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] + in1[0][2] * in2[2][2];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] + in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] + in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] + in1[1][2] * in2[2][2];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] + in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] + in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] + in1[2][2] * in2[2][2];
 }
References out.
Referenced by RotatePointAroundVector().
OldVectorInverseRotate()
void OldVectorInverseRotate (vec3_t v, float r[3][3], vec3_t d)
Definition at line 124 of file mathlib.c.
{
     d[0] = v[0] * r[0][0] + v[1] * r[1][0] + v[2] * r[2][0];
     d[1] = v[0] * r[0][1] + v[1] * r[1][1] + v[2] * r[2][1];
     d[2] = v[0] * r[0][2] + v[1] * r[1][2] + v[2] * r[2][2];
 }
PerpendicularVector()
void PerpendicularVector (vec3_t dst, const vec3_t src)
Definition at line 265 of file mathlib.c.
{
     int pos;
     int i;
     float minelem = 1.0F;
     vec3_t tempvec;
     /*
     ** find the smallest magnitude axially aligned vector
     */
     for ( pos = 0, i = 0; i < 3; i++ )  {
         if ( fabs( src[i] ) < minelem ) {
             pos = i;
             minelem = fabs( src[i] );
         }
     }
     tempvec[0] = tempvec[1] = tempvec[2] = 0.0F;
     tempvec[pos] = 1.0F;
     /*
     ** project the point onto the plane defined by src
     */
     ProjectPointOnPlane( dst, tempvec, src );
     /*
     ** normalize the result
     */
     VectorNormalize( dst, dst );
 }
References fabs(), ProjectPointOnPlane(), and VectorNormalize().
Referenced by RotatePointAroundVector().
ProjectPointOnPlane()
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
Definition at line 244 of file mathlib.c.
{
     float d;
     vec3_t n;
     float inv_denom;
     inv_denom = 1.0F / DotProduct( normal, normal );
     d = DotProduct( normal, p ) * inv_denom;
     n[0] = normal[0] * inv_denom;
     n[1] = normal[1] * inv_denom;
     n[2] = normal[2] * inv_denom;
     dst[0] = p[0] - d * n[0];
     dst[1] = p[1] - d * n[1];
     dst[2] = p[2] - d * n[2];
 }
References assert, DotProduct, and Q_fabs().
Referenced by PerpendicularVector().
Q_rint()
vec_t Q_rint (vec_t in)
Definition at line 158 of file mathlib.c.
{
     return floor (in + 0.5);
 }
References floor().
RadiusFromBounds()
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
Definition at line 230 of file mathlib.c.
{
     int     i;
     vec3_t  corner;
     float   a, b;
     for (i=0 ; i<3 ; i++) {
         a = fabs( mins[i] );
         b = fabs( maxs[i] );
         corner[i] = a > b ? a : b;
     }
     return VectorLength (corner);
 }
References fabs(), and VectorLength().
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 301 of file mathlib.c.
{
     float   m[3][3];
     float   im[3][3];
     float   zrot[3][3];
     float   tmpmat[3][3];
     float   rot[3][3];
     int i;
     vec3_t vr, vup, vf;
     float   rad;
     vf[0] = dir[0];
     vf[1] = dir[1];
     vf[2] = dir[2];
     PerpendicularVector( vr, dir );
     CrossProduct( vr, vf, vup );
     m[0][0] = vr[0];
     m[1][0] = vr[1];
     m[2][0] = vr[2];
     m[0][1] = vup[0];
     m[1][1] = vup[1];
     m[2][1] = vup[2];
     m[0][2] = vf[0];
     m[1][2] = vf[1];
     m[2][2] = vf[2];
     memcpy( im, m, sizeof( im ) );
     im[0][1] = m[1][0];
     im[0][2] = m[2][0];
     im[1][0] = m[0][1];
     im[1][2] = m[2][1];
     im[2][0] = m[0][2];
     im[2][1] = m[1][2];
     memset( zrot, 0, sizeof( zrot ) );
     zrot[0][0] = zrot[1][1] = zrot[2][2] = 1.0F;
     rad = DEG2RAD( degrees );
     zrot[0][0] = cos( rad );
     zrot[0][1] = sin( rad );
     zrot[1][0] = -sin( rad );
     zrot[1][1] = cos( rad );
     MatrixMultiply( m, zrot, tmpmat );
     MatrixMultiply( tmpmat, im, rot );
     for ( i = 0; i < 3; i++ ) {
         dst[i] = rot[i][0] * point[0] + rot[i][1] * point[1] + rot[i][2] * point[2];
     }
 }
References cos(), CrossProduct(), DEG2RAD, dir, m, MatrixMultiply(), memcpy(), memset(), PerpendicularVector(), and sin().
VectorCompare()
qboolean VectorCompare (const vec3_t v1, const vec3_t v2)
Definition at line 148 of file mathlib.c.
{
     int     i;
     for (i=0 ; i<3 ; i++)
         if (fabs(v1[i]-v2[i]) > EQUAL_EPSILON)
             return qfalse;
     return qtrue;
 }
References EQUAL_EPSILON, fabs(), qfalse, and qtrue.
Referenced by CG_PredictPlayerState(), G_SetMovedir(), InitTrigger(), LoadSMD_ParseTriangles(), R_BonesStillValid(), R_GLSL_SetUniform_AmbientLight(), R_GLSL_SetUniform_DirectedLight(), R_GLSL_SetUniform_DynamicLight(), R_GLSL_SetUniform_LightDirection(), and R_GLSL_SetUniform_ViewOrigin().
VectorInverseRotate()
void VectorInverseRotate (vec3_t v, float r[3][3], vec3_t d)
Definition at line 118 of file mathlib.c.
{
     vec3_t inv[3];
     MatrixInvert(r,inv);
     VectorRotate(v,inv,d);
 }
References MatrixInvert(), and VectorRotate().
Referenced by FixCoords(), LoadSMD_ParseTriangles(), and SaveMesh().
VectorLength()
double VectorLength (const vec3_t v)
Definition at line 136 of file mathlib.c.
{
     int     i;
     double  length;
     length = 0;
     for (i=0 ; i< 3 ; i++)
         length += v[i]*v[i];
     length = sqrt (length);     // FIXME
     return length;
 }
References sqrt().
Referenced by AutospriteDeform(), CG_AddPlayerWeapon(), CG_AddScorePlum(), CG_AddTrailsToScene(), CG_DamageFeedback(), CG_DrawRadarBlips(), CG_LerpSpike(), CG_PredictPlayerState(), CG_TrailFunc_FadeTail(), CheckWinding(), CM_NeedsSubdivision(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), ComputeColors(), ComputeEdgeCollapseCost(), DistancePointLine(), DistancePointToLine(), Fire_UserWeapon(), G_BounceUserMissile(), G_ImpactUserWeapon(), G_PushUserMissile(), G_UserRadiusDamage(), InitMover(), ParseMesh(), PM_AirMove(), PM_CheckHover(), PM_ContinueLegsAnim(), PM_Crash(), PM_DashMove(), PM_FlyMove(), PM_ForceLegsAnim(), PM_Friction(), PM_NoclipMove(), PM_StartLegsAnim(), PM_WalkMove(), PM_Weapon(), PSys_ApplyPlaneConstraint(), PSys_UpdateOrientation(), R_ComputeIQMFogNum(), R_CreateSurfaceGridMesh(), R_RotateForEntity(), R_SetupEntityLighting(), RadiusFromBounds(), Reached_Train(), SelectNearestDeathmatchSpawnPoint(), SelectRandomFurthestSpawnPoint(), Think_CylinderHoming(), Think_Guided(), Think_Homing(), and WindingArea().
VectorMA()
void VectorMA (const vec3_t va, double scale, const vec3_t vb, vec3_t vc)
Definition at line 162 of file mathlib.c.
{
     vc[0] = va[0] + scale*vb[0];
     vc[1] = va[1] + scale*vb[1];
     vc[2] = va[2] + scale*vb[2];
 }
References va().
Referenced by MakeNormalVectors().
VectorNormalize()
vec_t VectorNormalize (const vec3_t in, vec3_t out)
Definition at line 174 of file mathlib.c.
{
     vec_t   length, ilength;
     length = sqrt (in[0]*in[0] + in[1]*in[1] + in[2]*in[2]);
     if (length == 0) {
         VectorClear (out);
         return 0;
     }
     ilength = 1.0/length;
     out[0] = in[0]*ilength;
     out[1] = in[1]*ilength;
     out[2] = in[2]*ilength;
     return length;
 }
References out, sqrt(), and VectorClear.
Referenced by AimAtTarget(), Autosprite2Deform(), BG_EvaluateTrajectory(), BG_EvaluateTrajectoryDelta(), CG_AddScorePlum(), CG_AddTrailsToScene(), CG_Aura_DrawInnerSpike(), CG_Aura_DrawSpike(), CG_Aura_MarkRootPoint(), CG_Aura_SetHullAttributes(), CG_BeamTableUpdate(), CG_BezierMidPoints(), CG_BezierVerts(), CG_BubbleTrail(), CG_Camera(), CG_DirtPush(), CG_DrawLine(), CG_DrawLineRGBA(), CG_GetTrailVerts(), CG_LerpSpike(), CG_LerpTrails(), CG_MakeUserExplosion(), CG_TessCount(), CG_Tracer(), CG_WaterRipple(), CG_WaterSplash(), CM_AddFacetBevels(), CM_PlaneFromPoints(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), ComputeNormal(), DebugLine(), Fire_UserWeapon(), FixCoords(), G_BounceProjectile(), G_PushUserMissile(), G_UserWeaponDamage(), locateCamera(), MakeNormalVectors(), ParseShader(), PerpendicularVector(), PM_AirMove(), PM_CheckJump(), PM_CheckKnockback(), PM_CheckZanzoken(), PM_DashMove(), PM_FlyMove(), PM_NoclipMove(), PM_SlideMove(), PM_WalkMove(), PSys_AccumulateParticle(), PSys_ApplyDistanceConstraint(), PSys_ApplyDistanceMaxConstraint(), PSys_ApplyDistanceMinConstraint(), PSys_UpdateEmitters(), R_InitSkyTexCoords(), R_LerpTag(), R_SetupEntityLighting(), R_SubdividePatchToGrid(), RaySphereIntersections(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), RE_LoadWorldMap(), S_SpatializeOrigin(), SaveMesh(), Think_CylinderHoming(), Think_Guided(), Think_Homing(), Think_NormalMissileBurnPlayer(), Think_NormalMissileRidePlayer(), Think_NormalMissileStruggle(), and Think_NormalMissileStrugglePlayer().
VectorRotate()
void VectorRotate (vec3_t v, float r[3][3], vec3_t d)
Definition at line 130 of file mathlib.c.
{
     d[0] = v[0] * r[0][0] + v[1] * r[0][1] + v[2] * r[0][2];
     d[1] = v[0] * r[1][0] + v[1] * r[1][1] + v[2] * r[1][2];
     d[2] = v[0] * r[2][0] + v[1] * r[2][1] + v[2] * r[2][2];
 }
Referenced by VectorInverseRotate().
Variable Documentation
vec3_origin
vec3_t vec3_origin = {0,0,0}
Definition at line 34 of file mathlib.c.
Referenced by AddSkyPolygon(), AutospriteDeform(), BaseWindingForPlane(), CanDamage(), CG_AddPlayerWeapon(), CG_Aura_AddSounds(), CG_ClipMoveToEntities(), CG_DamageFeedback(), CG_EntityEffects(), CG_EntityEvent(), CG_Player(), CG_Portal(), CM_AddFacetBevels(), CM_BoxTrace(), CM_DrawDebugSurface(), CM_Trace(), CM_TransformedBoxTrace(), CM_ValidateFacet(), FindIntermissionPoint(), G_TryPushingProxMine(), InitTrigger(), MainMenu_DrawPlayer(), PM_NoclipMove(), R_GetPortalOrientations(), R_LoadFogs(), R_MirrorViewBySurface(), RB_AddQuadStampExt(), RB_SurfaceSprite(), SelectCTFSpawnPoint(), SelectInitialSpawnPoint(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_EntityContact(), SV_PointContents(), SV_Trace(), and WindingCenter().