ZEQ2-Lite: Font Class Reference
Font Class Reference
#include <gdiplusheaders.h>
Public Member Functions
Font (const FontFamily *family, REAL emSize, INT style=FontStyleRegular, Unit unit=UnitPoint)
Font (const WCHAR *familyName, REAL emSize, INT style=FontStyleRegular, Unit unit=UnitPoint, const FontCollection *fontCollection=NULL)
Font (HDC hdc)
Font (HDC hdc, const LOGFONTA *logfont)
Font (HDC hdc, const LOGFONTW *logfont)
Font (HDC hdc, HFONT hfont)
~Font ()
Font * Clone () const
Status GetFamily (FontFamily *family) const
REAL GetHeight (const Graphics *graphics) const
REAL GetHeight (REAL dpi) const
Status GetLastStatus () const
Status GetLogFontA (const Graphics *graphics, LOGFONTA *logfontA) const
Status GetLogFontW (const Graphics *graphics, LOGFONTW *logfontW) const
REAL GetSize () const
INT GetStyle () const
Unit GetUnit () const
BOOL IsAvailable () const
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Font (const Font &)
Font (GpFont *font, Status status)
Font & operator= (const Font &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpFont * nativeFont
Friends
class Graphics
Detailed Description
Definition at line 328 of file gdiplusheaders.h.
Constructor & Destructor Documentation
Font() [1/8]
__inline__ Font::Font (const FontFamily * family, REAL emSize, INT style = FontStyleRegular, Unit unit = UnitPoint)
Definition at line 744 of file gdiplusimpl.h.
                                           :
         nativeFont(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateFont(
             family ? family->nativeFontFamily : NULL,
             emSize, style, unit, &nativeFont);
 }
References GdipCreateFont(), lastStatus, nativeFont, FontFamily::nativeFontFamily, and NULL.
Referenced by Clone().
Font() [2/8]
__inline__ Font::Font (HDC hdc, HFONT hfont)
Definition at line 753 of file gdiplusimpl.h.
                                          :
     nativeFont(NULL), lastStatus(Ok)
 {
     LOGFONTW logfont;
     if (GetObject(hfont, sizeof logfont, &logfont)) {
         lastStatus = DllExports::GdipCreateFontFromLogfontW(
                 hdc, &logfont, &nativeFont);
     } else {
         lastStatus = DllExports::GdipCreateFontFromDC(
                 hdc, &nativeFont);
     }
 }
References GdipCreateFontFromDC(), GdipCreateFontFromLogfontW(), GetObject, lastStatus, and nativeFont.
Font() [3/8]
__inline__ Font::Font (HDC hdc, const LOGFONTA * logfont)
Definition at line 766 of file gdiplusimpl.h.
                                                      :
     nativeFont(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateFontFromLogfontA(
             hdc, logfont, &nativeFont);
 }
References GdipCreateFontFromLogfontA(), lastStatus, and nativeFont.
Font() [4/8]
__inline__ Font::Font (HDC hdc, const LOGFONTW * logfont)
Definition at line 773 of file gdiplusimpl.h.
                                                      :
     nativeFont(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateFontFromLogfontW(
             hdc, logfont, &nativeFont);
 }
References GdipCreateFontFromLogfontW(), lastStatus, and nativeFont.
Font() [5/8]
__inline__ Font::Font (HDC hdc)
Definition at line 780 of file gdiplusimpl.h.
                             :
     nativeFont(NULL), lastStatus(Ok)
 {
     lastStatus = DllExports::GdipCreateFontFromDC(hdc, &nativeFont);
 }
References GdipCreateFontFromDC(), lastStatus, and nativeFont.
Font() [6/8]
__inline__ Font::Font (const WCHAR * familyName, REAL emSize, INT style = FontStyleRegular, Unit unit = UnitPoint, const FontCollection * fontCollection = NULL)
Definition at line 786 of file gdiplusimpl.h.
                                                         :
         nativeFont(NULL), lastStatus(Ok)
 {
     GpFontFamily *nativeFamily = NULL;
     lastStatus = DllExports::GdipCreateFontFamilyFromName(
             familyName,
             fontCollection ? fontCollection->nativeFontCollection : NULL,
             &nativeFamily);
     if (nativeFamily) {
         lastStatus = DllExports::GdipCreateFont(
                 nativeFamily, emSize, style, unit, &nativeFont);
         DllExports::GdipDeleteFontFamily(nativeFamily);
     }
 }
References GdipCreateFont(), GdipCreateFontFamilyFromName(), GdipDeleteFontFamily(), lastStatus, nativeFont, FontCollection::nativeFontCollection, and NULL.
~Font()
__inline__ Font::~Font ()
Definition at line 803 of file gdiplusimpl.h.
 {
     DllExports::GdipDeleteFont(nativeFont);
 }
References GdipDeleteFont(), and nativeFont.
Font() [7/8]
Font::Font (GpFont * font, Status status) inline private
Definition at line 366 of file gdiplusheaders.h.
                                      :
         nativeFont(font), lastStatus(status) {}
Font() [8/8]
Font::Font (const Font &) private
Member Function Documentation
Clone()
__inline__ Font * Font::Clone () const
Definition at line 808 of file gdiplusimpl.h.
 {
     GpFont *cloneFont = NULL;
     Status status = updateStatus(DllExports::GdipCloneFont(
             nativeFont, &cloneFont));
     if (status == Ok) {
         Font *result = new Font(cloneFont, lastStatus);
         if (!result) {
             DllExports::GdipDeleteFont(cloneFont);
             lastStatus = OutOfMemory;
         }
         return result;
     } else {
         return NULL;
     }
 }
References Font(), GdipCloneFont(), GdipDeleteFont(), lastStatus, nativeFont, NULL, Ok, OutOfMemory, and updateStatus().
GetFamily()
__inline__ Status Font::GetFamily (FontFamily * family) const
Definition at line 825 of file gdiplusimpl.h.
 {
     if (!family) return lastStatus = InvalidParameter;
     // FIXME: do we need to call GdipDeleteFontFamily first?
     return family->lastStatus = updateStatus(DllExports::GdipGetFamily(
             nativeFont, &family->nativeFontFamily));
 }
References GdipGetFamily(), InvalidParameter, lastStatus, FontFamily::lastStatus, nativeFont, FontFamily::nativeFontFamily, and updateStatus().
GetHeight() [1/2]
__inline__ REAL Font::GetHeight (const Graphics * graphics) const
Definition at line 833 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetFontHeight(
             nativeFont, graphics ? graphics->nativeGraphics : NULL,
             &result));
     return result;
 }
References GdipGetFontHeight(), nativeFont, Graphics::nativeGraphics, NULL, and updateStatus().
GetHeight() [2/2]
__inline__ REAL Font::GetHeight (REAL dpi) const
Definition at line 842 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetFontHeightGivenDPI(
             nativeFont, dpi, &result));
     return result;
 }
References GdipGetFontHeightGivenDPI(), nativeFont, and updateStatus().
GetLastStatus()
Status Font::GetLastStatus () const inline
Definition at line 356 of file gdiplusheaders.h.
     {
         return lastStatus;
     }
References lastStatus.
GetLogFontA()
__inline__ Status Font::GetLogFontA (const Graphics * graphics, LOGFONTA * logfontA) const
Definition at line 850 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetLogFontA(
             nativeFont, graphics ? graphics->nativeGraphics : NULL,
             logfontA));
 }
References GdipGetLogFontA(), nativeFont, Graphics::nativeGraphics, NULL, and updateStatus().
GetLogFontW()
__inline__ Status Font::GetLogFontW (const Graphics * graphics, LOGFONTW * logfontW) const
Definition at line 858 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetLogFontW(
             nativeFont, graphics ? graphics->nativeGraphics : NULL,
             logfontW));
 }
References GdipGetLogFontW(), nativeFont, Graphics::nativeGraphics, NULL, and updateStatus().
GetSize()
__inline__ REAL Font::GetSize () const
Definition at line 866 of file gdiplusimpl.h.
 {
     REAL result = 0.0;
     updateStatus(DllExports::GdipGetFontSize(nativeFont, &result));
     return result;
 }
References GdipGetFontSize(), nativeFont, and updateStatus().
GetStyle()
__inline__ INT Font::GetStyle () const
Definition at line 873 of file gdiplusimpl.h.
 {
     INT result = FontStyleRegular;
     updateStatus(DllExports::GdipGetFontStyle(nativeFont, &result));
     return result;
 }
References FontStyleRegular, GdipGetFontStyle(), nativeFont, and updateStatus().
GetUnit()
__inline__ Unit Font::GetUnit () const
Definition at line 880 of file gdiplusimpl.h.
 {
     Unit result = UnitPoint;
     updateStatus(DllExports::GdipGetFontUnit(nativeFont, &result));
     return result;
 }
References GdipGetFontUnit(), nativeFont, UnitPoint, and updateStatus().
IsAvailable()
BOOL Font::IsAvailable () const inline
Definition at line 360 of file gdiplusheaders.h.
     {
         return nativeFont != NULL;
     }
References nativeFont, and NULL.
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Font& Font::operator= (const Font &) private
updateStatus()
Status Font::updateStatus (Status newStatus) const inline private
Definition at line 371 of file gdiplusheaders.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by Clone(), GetFamily(), GetHeight(), GetLogFontA(), GetLogFontW(), GetSize(), GetStyle(), and GetUnit().
Friends And Related Function Documentation
Graphics
friend class Graphics friend
Definition at line 330 of file gdiplusheaders.h.
Field Documentation
lastStatus
Status Font::lastStatus mutable private
Definition at line 378 of file gdiplusheaders.h.
Referenced by Clone(), Font(), GetFamily(), GetLastStatus(), and updateStatus().
nativeFont
GpFont* Font::nativeFont private
Definition at line 377 of file gdiplusheaders.h.
Referenced by Clone(), Graphics::DrawDriverString(), Graphics::DrawString(), Font(), GetFamily(), GetHeight(), GetLogFontA(), GetLogFontW(), GetSize(), GetStyle(), GetUnit(), IsAvailable(), Graphics::MeasureCharacterRanges(), Graphics::MeasureDriverString(), Graphics::MeasureString(), and ~Font().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdiplusheaders.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h