ZEQ2-Lite: Source/Game/UI/ui_team.c File Reference
ui_team.c File Reference
#include "ui_local.h"
Data Structures
struct teammain_t
Macros
#define ID_JOINBLUE 101
#define ID_JOINGAME 102
#define ID_JOINRED 100
#define ID_SPECTATE 103
#define TEAMMAIN_FRAME "interface/art/cut_frame"
Functions
void TeamMain_Cache (void)
static void TeamMain_MenuEvent (void *ptr, int event)
void TeamMain_MenuInit (void)
void UI_TeamMainMenu (void)
Variables
static teammain_t s_teammain
Macro Definition Documentation
ID_JOINBLUE
#define ID_JOINBLUE 101
Definition at line 33 of file ui_team.c.
ID_JOINGAME
#define ID_JOINGAME 102
Definition at line 34 of file ui_team.c.
ID_JOINRED
#define ID_JOINRED 100
Definition at line 32 of file ui_team.c.
ID_SPECTATE
#define ID_SPECTATE 103
Definition at line 35 of file ui_team.c.
TEAMMAIN_FRAME
#define TEAMMAIN_FRAME "interface/art/cut_frame"
Definition at line 30 of file ui_team.c.
Function Documentation
TeamMain_Cache()
void TeamMain_Cache (void)
Definition at line 188 of file ui_team.c.
{
     trap_R_RegisterShaderNoMip( TEAMMAIN_FRAME );
 }
References TEAMMAIN_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by TeamMain_MenuInit().
TeamMain_MenuEvent()
static void TeamMain_MenuEvent (void * ptr, int event) static
Definition at line 55 of file ui_team.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch( ((menucommon_s*)ptr)->id ) {
     case ID_JOINRED:
         trap_Cmd_ExecuteText( EXEC_APPEND, "cmd team red\n" );
         UI_ForceMenuOff();
         break;
     case ID_JOINBLUE:
         trap_Cmd_ExecuteText( EXEC_APPEND, "cmd team blue\n" );
         UI_ForceMenuOff();
         break;
     case ID_JOINGAME:
         trap_Cmd_ExecuteText( EXEC_APPEND, "cmd team free\n" );
         UI_ForceMenuOff();
         break;
     case ID_SPECTATE:
         trap_Cmd_ExecuteText( EXEC_APPEND, "cmd team spectator\n" );
         UI_ForceMenuOff();
         break;
     }
 }
References EXEC_APPEND, ID_JOINBLUE, ID_JOINGAME, ID_JOINRED, ID_SPECTATE, ptr(), QM_ACTIVATED, trap_Cmd_ExecuteText(), and UI_ForceMenuOff().
Referenced by TeamMain_MenuInit().
TeamMain_MenuInit()
void TeamMain_MenuInit (void)
Definition at line 89 of file ui_team.c.
{
     int     y;
     int     gametype;
     char    info[MAX_INFO_STRING];
     memset( &s_teammain, 0, sizeof(s_teammain) );
     TeamMain_Cache();
     s_teammain.menu.wrapAround = qtrue;
     s_teammain.menu.fullscreen = qfalse;
     s_teammain.frame.generic.type   = MTYPE_BITMAP;
     s_teammain.frame.generic.flags  = QMF_INACTIVE;
     s_teammain.frame.generic.name   = TEAMMAIN_FRAME;
     s_teammain.frame.generic.x      = 142;
     s_teammain.frame.generic.y      = 118;
     s_teammain.frame.width          = 359;
     s_teammain.frame.height         = 256;
     y = 194;
     s_teammain.joinred.generic.type     = MTYPE_PTEXT;
     s_teammain.joinred.generic.flags    = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_teammain.joinred.generic.id       = ID_JOINRED;
     s_teammain.joinred.generic.callback = TeamMain_MenuEvent;
     s_teammain.joinred.generic.x        = 320;
     s_teammain.joinred.generic.y        = y;
     s_teammain.joinred.string           = "JOIN RED";
     s_teammain.joinred.style            = UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW;
     s_teammain.joinred.color            = colorWhite;
     y += 20;
     s_teammain.joinblue.generic.type     = MTYPE_PTEXT;
     s_teammain.joinblue.generic.flags    = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_teammain.joinblue.generic.id       = ID_JOINBLUE;
     s_teammain.joinblue.generic.callback = TeamMain_MenuEvent;
     s_teammain.joinblue.generic.x        = 320;
     s_teammain.joinblue.generic.y        = y;
     s_teammain.joinblue.string           = "JOIN BLUE";
     s_teammain.joinblue.style            = UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW;
     s_teammain.joinblue.color            = colorWhite;
     y += 20;
     s_teammain.joingame.generic.type     = MTYPE_PTEXT;
     s_teammain.joingame.generic.flags    = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_teammain.joingame.generic.id       = ID_JOINGAME;
     s_teammain.joingame.generic.callback = TeamMain_MenuEvent;
     s_teammain.joingame.generic.x        = 320;
     s_teammain.joingame.generic.y        = y;
     s_teammain.joingame.string           = "JOIN GAME";
     s_teammain.joingame.style            = UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW;
     s_teammain.joingame.color            = colorWhite;
     y += 20;
     s_teammain.spectate.generic.type     = MTYPE_PTEXT;
     s_teammain.spectate.generic.flags    = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_teammain.spectate.generic.id       = ID_SPECTATE;
     s_teammain.spectate.generic.callback = TeamMain_MenuEvent;
     s_teammain.spectate.generic.x        = 320;
     s_teammain.spectate.generic.y        = y;
     s_teammain.spectate.string           = "SPECTATE";
     s_teammain.spectate.style            = UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW;
     s_teammain.spectate.color            = colorWhite;
     y += 20;
     trap_GetConfigString(CS_SERVERINFO, info, MAX_INFO_STRING);
     gametype = atoi( Info_ValueForKey( info,"g_gametype" ) );
     // set initial states
     switch( gametype ) {
     case GT_SINGLE_PLAYER:
     case GT_FFA:
     case GT_STRUGGLE:
     case GT_TOURNAMENT:
         s_teammain.joinred.generic.flags  |= QMF_GRAYED;
         s_teammain.joinblue.generic.flags |= QMF_GRAYED;
         break;
     default:
     case GT_TEAM:
     case GT_CTF:
         s_teammain.joingame.generic.flags |= QMF_GRAYED;
         break;
     }
     Menu_AddItem( &s_teammain.menu, (void*) &s_teammain.frame );
     Menu_AddItem( &s_teammain.menu, (void*) &s_teammain.joinred );
     Menu_AddItem( &s_teammain.menu, (void*) &s_teammain.joinblue );
     Menu_AddItem( &s_teammain.menu, (void*) &s_teammain.joingame );
     Menu_AddItem( &s_teammain.menu, (void*) &s_teammain.spectate );
 }
References menucommon_s::callback, menutext_s::color, colorWhite, CS_SERVERINFO, menucommon_s::flags, teammain_t::frame, menubitmap_s::generic, menutext_s::generic, GT_CTF, GT_FFA, GT_SINGLE_PLAYER, GT_STRUGGLE, GT_TEAM, GT_TOURNAMENT, menubitmap_s::height, menucommon_s::id, ID_JOINBLUE, ID_JOINGAME, ID_JOINRED, ID_SPECTATE, info, Info_ValueForKey(), teammain_t::joinblue, teammain_t::joingame, teammain_t::joinred, MAX_INFO_STRING, teammain_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_PTEXT, menucommon_s::name, qfalse, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_INACTIVE, QMF_PULSEIFFOCUS, qtrue, s_teammain, teammain_t::spectate, menutext_s::string, menutext_s::style, TeamMain_Cache(), TEAMMAIN_FRAME, TeamMain_MenuEvent(), trap_GetConfigString(), menucommon_s::type, UI_CENTER, UI_DROPSHADOW, UI_SMALLFONT, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by UI_TeamMainMenu().
UI_TeamMainMenu()
void UI_TeamMainMenu (void)
Definition at line 198 of file ui_team.c.
{
     TeamMain_MenuInit();
     UI_PushMenu ( &s_teammain.menu );
 }
References teammain_t::menu, s_teammain, TeamMain_MenuInit(), and UI_PushMenu().
Referenced by InGame_Event().
Variable Documentation
s_teammain
teammain_t s_teammain static
Definition at line 48 of file ui_team.c.
Referenced by TeamMain_MenuInit(), and UI_TeamMainMenu().