ZEQ2-Lite: Game/Game/g_misc.c File Reference
g_misc.c File Reference
#include "g_local.h"
Functions
void locateCamera (gentity_t *ent)
void SP_info_camp (gentity_t *self)
void SP_info_notnull (gentity_t *self)
void SP_info_null (gentity_t *self)
void SP_light (gentity_t *self)
void SP_misc_model (gentity_t *ent)
void SP_misc_portal_camera (gentity_t *ent)
void SP_misc_portal_surface (gentity_t *ent)
void SP_misc_teleporter_dest (gentity_t *ent)
void TeleportPlayer (gentity_t *player, vec3_t origin, vec3_t angles)
Function Documentation
locateCamera()
void locateCamera (gentity_t * ent)
Definition at line 158 of file g_misc.c.
{
     vec3_t      dir;
     gentity_t   *target;
     gentity_t   *owner;
     owner = G_PickTarget( ent->target );
     if ( !owner ) {
         G_Printf( "Couldn't find target for misc_portal_surface\n" );
         G_FreeEntity( ent );
         return;
     }
     ent->r.ownerNum = owner->s.number;
     // frame holds the rotate speed
     if ( owner->spawnflags & 1 ) {
         ent->s.frame = 25;
     } else if ( owner->spawnflags & 2 ) {
         ent->s.frame = 75;
     }
     // swing camera ?
     if ( owner->spawnflags & 4 ) {
         // set to 0 for no rotation at all
         ent->s.powerups = 0;
     }
     else {
         ent->s.powerups = 1;
     }
     // clientNum holds the rotate offset
     ent->s.clientNum = owner->s.clientNum;
     VectorCopy( owner->s.origin, ent->s.origin2 );
     // see if the portal_camera has a target
     target = G_PickTarget( owner->target );
     if ( target ) {
         VectorSubtract( target->s.origin, owner->s.origin, dir );
         VectorNormalize( dir );
     } else {
         G_SetMovedir( owner->s.angles, dir );
     }
     ent->s.eventParm = DirToByte( dir );
 }
References dir, DirToByte(), G_FreeEntity(), G_PickTarget(), G_Printf(), G_SetMovedir(), VectorCopy, VectorNormalize(), and VectorSubtract.
Referenced by SP_misc_portal_surface().
SP_info_camp()
void SP_info_camp (gentity_t * self)
Definition at line 36 of file g_misc.c.
{
     G_SetOrigin( self, self->s.origin );
 }
References G_SetOrigin().
SP_info_notnull()
void SP_info_notnull (gentity_t * self)
Definition at line 53 of file g_misc.c.
{
     G_SetOrigin( self, self->s.origin );
 }
References G_SetOrigin().
SP_info_null()
void SP_info_null (gentity_t * self)
Definition at line 44 of file g_misc.c.
{
     G_FreeEntity( self );
 }
References G_FreeEntity().
SP_light()
void SP_light (gentity_t * self)
Definition at line 65 of file g_misc.c.
{
     G_FreeEntity( self );
 }
References G_FreeEntity().
SP_misc_model()
void SP_misc_model (gentity_t * ent)
Definition at line 141 of file g_misc.c.
{
 #if 0
     ent->s.modelindex = G_ModelIndex( ent->model );
     VectorSet (ent->mins, -16, -16, -16);
     VectorSet (ent->maxs, 16, 16, 16);
     trap_LinkEntity (ent);
     G_SetOrigin( ent, ent->s.origin );
     VectorCopy( ent->s.angles, ent->s.apos.trBase );
 #else
     G_FreeEntity( ent );
 #endif
 }
References G_FreeEntity(), G_ModelIndex(), G_SetOrigin(), trap_LinkEntity(), VectorCopy, and VectorSet.
SP_misc_portal_camera()
void SP_misc_portal_camera (gentity_t * ent)
Definition at line 228 of file g_misc.c.
{
     float   roll;
     VectorClear( ent->r.mins );
     VectorClear( ent->r.maxs );
     trap_LinkEntity (ent);
     G_SpawnFloat( "roll", "0", &roll );
     ent->s.clientNum = roll/360.0 * 256;
 }
References G_SpawnFloat(), roll, trap_LinkEntity(), and VectorClear.
SP_misc_portal_surface()
void SP_misc_portal_surface (gentity_t * ent)
Definition at line 208 of file g_misc.c.
{
     VectorClear( ent->r.mins );
     VectorClear( ent->r.maxs );
     trap_LinkEntity (ent);
     ent->r.svFlags = SVF_PORTAL;
     ent->s.eType = ET_PORTAL;
     if ( !ent->target ) {
         VectorCopy( ent->s.origin, ent->s.origin2 );
     } else {
         ent->think = locateCamera;
         ent->nextthink = level.time + 100;
     }
 }
References ET_PORTAL, locateCamera(), SVF_PORTAL, trap_LinkEntity(), VectorClear, and VectorCopy.
SP_misc_teleporter_dest()
void SP_misc_teleporter_dest (gentity_t * ent)
Definition at line 132 of file g_misc.c.
{
 }
TeleportPlayer()
void TeleportPlayer (gentity_t * player, vec3_t origin, vec3_t angles)
Definition at line 79 of file g_misc.c.
{
     gentity_t   *tent;
     qboolean noAngles;
     noAngles = (angles[0] > 999999.0);
     // use temp events at source and destination to prevent the effect
     // from getting dropped by a second player event
     if ( player->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         tent = G_TempEntity( player->client->ps.origin, EV_PLAYER_TELEPORT_OUT );
         tent->s.clientNum = player->s.clientNum;
         tent = G_TempEntity( origin, EV_PLAYER_TELEPORT_IN );
         tent->s.clientNum = player->s.clientNum;
     }
     // unlink to make sure it can't possibly interfere with G_KillBox
     trap_UnlinkEntity (player);
     VectorCopy ( origin, player->client->ps.origin );
     player->client->ps.origin[2] += 1;
     if (!noAngles) {
     // spit the player out
     AngleVectors( angles, player->client->ps.velocity, NULL, NULL );
     VectorScale( player->client->ps.velocity, 400, player->client->ps.velocity );
     player->client->ps.pm_time = 160;       // hold time
     player->client->ps.pm_flags |= PMF_TIME_KNOCKBACK;
     // set angles
     SetClientViewAngle(player, angles);
     }
     // toggle the teleport bit so the client knows to not lerp
     player->client->ps.eFlags ^= EF_TELEPORT_BIT;
     // kill anything at the destination
     if ( player->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         G_KillBox (player);
     }
     // save results of pmove
     BG_PlayerStateToEntityState( &player->client->ps, &player->s,qtrue );
     // use the precise origin for linking
     VectorCopy( player->client->ps.origin, player->r.currentOrigin );
     if ( player->client->sess.sessionTeam != TEAM_SPECTATOR ) {
         trap_LinkEntity (player);
     }
 }
References angles, AngleVectors(), BG_PlayerStateToEntityState(), EF_TELEPORT_BIT, EV_PLAYER_TELEPORT_IN, EV_PLAYER_TELEPORT_OUT, G_KillBox(), G_TempEntity(), NULL, PMF_TIME_KNOCKBACK, qtrue, SetClientViewAngle(), TEAM_SPECTATOR, trap_LinkEntity(), trap_UnlinkEntity(), VectorCopy, and VectorScale.
Referenced by Cmd_SetViewpos_f(), target_teleporter_use(), Touch_DoorTriggerSpectator(), and trigger_teleporter_touch().