ZEQ2-Lite: Engine/libspeex/filterbank.c File Reference
filterbank.c File Reference
Converting between psd and filterbank.
#include "filterbank.h"
#include "arch.h"
#include <math.h>
#include "math_approx.h"
#include "os_support.h"
Macros
#define toBARK(n) (13.1f*atan(.00074f*(n))+2.24f*atan((n)*(n)*1.85e-8f)+1e-4f*(n))
#define toMEL(n) (2595.f*log10(1.f+(n)/700.f))
Functions
void filterbank_compute_bank (FilterBank *bank, float *ps, float *mel)
void filterbank_compute_bank32 (FilterBank *bank, spx_word32_t *ps, spx_word32_t *mel)
void filterbank_compute_psd (FilterBank *bank, float *mel, float *ps)
void filterbank_compute_psd16 (FilterBank *bank, spx_word16_t *mel, spx_word16_t *ps)
void filterbank_destroy (FilterBank *bank)
FilterBank * filterbank_new (int banks, spx_word32_t sampling, int len, int type)
void filterbank_psy_smooth (FilterBank *bank, float *ps, float *mask)
Detailed Description
Converting between psd and filterbank.
Definition in file filterbank.c.
Macro Definition Documentation
toBARK
#define toBARK (n) (13.1f*atan(.00074f*(n))+2.24f*atan((n)*(n)*1.85e-8f)+1e-4f*(n))
Definition at line 49 of file filterbank.c.
toMEL
#define toMEL (n) (2595.f*log10(1.f+(n)/700.f))
Definition at line 52 of file filterbank.c.
Function Documentation
filterbank_compute_bank()
void filterbank_compute_bank (FilterBank * bank, float * ps, float * mel)
Definition at line 173 of file filterbank.c.
 {
    int i;
    for (i=0;i<bank->nb_banks;i++)
       mel[i] = 0;
    for (i=0;i<bank->len;i++)
    {
       int id = bank->bank_left[i];
       mel[id] += bank->filter_left[i]*ps[i];
       id = bank->bank_right[i];
       mel[id] += bank->filter_right[i]*ps[i];
    }
    for (i=0;i<bank->nb_banks;i++)
       mel[i] *= bank->scaling[i];
 }
References FilterBank::bank_left, FilterBank::bank_right, FilterBank::filter_left, FilterBank::filter_right, FilterBank::len, FilterBank::nb_banks, and FilterBank::scaling.
Referenced by filterbank_psy_smooth().
filterbank_compute_bank32()
void filterbank_compute_bank32 (FilterBank * bank, spx_word32_t * ps, spx_word32_t * mel)
Definition at line 134 of file filterbank.c.
 {
    int i;
    for (i=0;i<bank->nb_banks;i++)
       mel[i] = 0;
    for (i=0;i<bank->len;i++)
    {
       int id;
       id = bank->bank_left[i];
       mel[id] += MULT16_32_P15(bank->filter_left[i],ps[i]);
       id = bank->bank_right[i];
       mel[id] += MULT16_32_P15(bank->filter_right[i],ps[i]);
    }
    /* Think I can safely disable normalisation that for fixed-point (and probably float as well) */
 #ifndef FIXED_POINT
    /*for (i=0;i<bank->nb_banks;i++)
       mel[i] = MULT16_32_P15(Q15(bank->scaling[i]),mel[i]);
    */
 #endif
 }
References FilterBank::bank_left, FilterBank::bank_right, FilterBank::filter_left, FilterBank::filter_right, FilterBank::len, MULT16_32_P15, and FilterBank::nb_banks.
Referenced by preprocess_analysis(), and speex_preprocess_run().
filterbank_compute_psd()
void filterbank_compute_psd (FilterBank * bank, float * mel, float * ps)
Definition at line 190 of file filterbank.c.
 {
    int i;
    for (i=0;i<bank->len;i++)
    {
       int id = bank->bank_left[i];
       ps[i] = mel[id]*bank->filter_left[i];
       id = bank->bank_right[i];
       ps[i] += mel[id]*bank->filter_right[i];
    }
 }
References FilterBank::bank_left, FilterBank::bank_right, FilterBank::filter_left, FilterBank::filter_right, and FilterBank::len.
Referenced by filterbank_psy_smooth().
filterbank_compute_psd16()
void filterbank_compute_psd16 (FilterBank * bank, spx_word16_t * mel, spx_word16_t * ps)
Definition at line 156 of file filterbank.c.
 {
    int i;
    for (i=0;i<bank->len;i++)
    {
       spx_word32_t tmp;
       int id1, id2;
       id1 = bank->bank_left[i];
       id2 = bank->bank_right[i];
       tmp = MULT16_16(mel[id1],bank->filter_left[i]);
       tmp += MULT16_16(mel[id2],bank->filter_right[i]);
       ps[i] = EXTRACT16(PSHR32(tmp,15));
    }
 }
References FilterBank::bank_left, FilterBank::bank_right, EXTRACT16, FilterBank::filter_left, FilterBank::filter_right, FilterBank::len, MULT16_16, and PSHR32.
Referenced by speex_preprocess_run().
filterbank_destroy()
void filterbank_destroy (FilterBank * bank)
Definition at line 122 of file filterbank.c.
 {
    speex_free(bank->bank_left);
    speex_free(bank->bank_right);
    speex_free(bank->filter_left);
    speex_free(bank->filter_right);
 #ifndef FIXED_POINT
    speex_free(bank->scaling);
 #endif
    speex_free(bank);
 }
References FilterBank::bank_left, FilterBank::bank_right, FilterBank::filter_left, FilterBank::filter_right, FilterBank::scaling, and speex_free().
Referenced by speex_preprocess_state_destroy().
filterbank_new()
FilterBank* filterbank_new (int banks, spx_word32_t sampling, int len, int type)
Definition at line 54 of file filterbank.c.
 {
    FilterBank *bank;
    spx_word32_t df;
    spx_word32_t max_mel, mel_interval;
    int i;
    int id1;
    int id2;
    df = DIV32(SHL32(sampling,15),MULT16_16(2,len));
    max_mel = toBARK(EXTRACT16(sampling/2));
    mel_interval = PDIV32(max_mel,banks-1);
    bank = (FilterBank*)speex_alloc(sizeof(FilterBank));
    bank->nb_banks = banks;
    bank->len = len;
    bank->bank_left = (int*)speex_alloc(len*sizeof(int));
    bank->bank_right = (int*)speex_alloc(len*sizeof(int));
    bank->filter_left = (spx_word16_t*)speex_alloc(len*sizeof(spx_word16_t));
    bank->filter_right = (spx_word16_t*)speex_alloc(len*sizeof(spx_word16_t));
    /* Think I can safely disable normalisation that for fixed-point (and probably float as well) */
 #ifndef FIXED_POINT
    bank->scaling = (float*)speex_alloc(banks*sizeof(float));
 #endif
    for (i=0;i<len;i++)
    {
       spx_word16_t curr_freq;
       spx_word32_t mel;
       spx_word16_t val;
       curr_freq = EXTRACT16(MULT16_32_P15(i,df));
       mel = toBARK(curr_freq);
       if (mel > max_mel)
          break;
 #ifdef FIXED_POINT
       id1 = DIV32(mel,mel_interval);
 #else
       id1 = (int)(floor(mel/mel_interval));
 #endif
       if (id1>banks-2)
       {
          id1 = banks-2;
          val = Q15_ONE;
       } else {
          val = DIV32_16(mel - id1*mel_interval,EXTRACT16(PSHR32(mel_interval,15)));
       }
       id2 = id1+1;
       bank->bank_left[i] = id1;
       bank->filter_left[i] = SUB16(Q15_ONE,val);
       bank->bank_right[i] = id2;
       bank->filter_right[i] = val;
    }
    /* Think I can safely disable normalisation for fixed-point (and probably float as well) */
 #ifndef FIXED_POINT
    for (i=0;i<bank->nb_banks;i++)
       bank->scaling[i] = 0;
    for (i=0;i<bank->len;i++)
    {
       int id = bank->bank_left[i];
       bank->scaling[id] += bank->filter_left[i];
       id = bank->bank_right[i];
       bank->scaling[id] += bank->filter_right[i];
    }
    for (i=0;i<bank->nb_banks;i++)
       bank->scaling[i] = Q15_ONE/(bank->scaling[i]);
 #endif
    return bank;
 }
References FilterBank::bank_left, FilterBank::bank_right, DIV32, DIV32_16, EXTRACT16, FilterBank::filter_left, FilterBank::filter_right, int(), FilterBank::len, MULT16_16, MULT16_32_P15, FilterBank::nb_banks, PDIV32, PSHR32, Q15_ONE, FilterBank::scaling, SHL32, speex_alloc(), SUB16, toBARK, and val.
Referenced by speex_preprocess_state_init().
filterbank_psy_smooth()
void filterbank_psy_smooth (FilterBank * bank, float * ps, float * mask)
Definition at line 202 of file filterbank.c.
 {
    /* Low freq slope: 14 dB/Bark*/
    /* High freq slope: 9 dB/Bark*/
    /* Noise vs tone: 5 dB difference */
    /* FIXME: Temporary kludge */
    float bark[100];
    int i;
    /* Assumes 1/3 Bark resolution */
    float decay_low = 0.34145f;
    float decay_high = 0.50119f;
    filterbank_compute_bank(bank, ps, bark);
    for (i=1;i<bank->nb_banks;i++)
    {
       /*float decay_high = 13-1.6*log10(bark[i-1]);
       decay_high = pow(10,(-decay_high/30.f));*/
       bark[i] = bark[i] + decay_high*bark[i-1];
    }
    for (i=bank->nb_banks-2;i>=0;i--)
    {
       bark[i] = bark[i] + decay_low*bark[i+1];
    }
    filterbank_compute_psd(bank, bark, mask);
 }
References filterbank_compute_bank(), filterbank_compute_psd(), and FilterBank::nb_banks.