ZEQ2-Lite: Metafile Class Reference
Metafile Class Reference
#include <gdiplusmetafile.h>
Public Member Functions
Metafile (const WCHAR *filename)
Metafile (const WCHAR *filename, const WmfPlaceableFileHeader *wmfPlaceableFileHeader)
Metafile (const WCHAR *filename, HDC referenceHdc, const Rect &frameRect, MetafileFrameUnit frameUnit=MetafileFrameUnitGdi, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
Metafile (const WCHAR *filename, HDC referenceHdc, const RectF &frameRect, MetafileFrameUnit frameUnit=MetafileFrameUnitGdi, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
Metafile (const WCHAR *filename, HDC referenceHdc, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
Metafile (HDC referenceHdc, const Rect &frameRect, MetafileFrameUnit frameUnit=MetafileFrameUnitGdi, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
Metafile (HDC referenceHdc, const RectF &frameRect, MetafileFrameUnit frameUnit=MetafileFrameUnitGdi, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
Metafile (HDC referenceHdc, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
Metafile (HENHMETAFILE hEmf, BOOL deleteEmf=FALSE)
Metafile (HMETAFILE hWmf, const WmfPlaceableFileHeader *wmfPlaceableFileHeader, BOOL deleteWmf=FALSE)
Metafile (IStream *stream)
Metafile (IStream *stream, HDC referenceHdc, const Rect &frameRect, MetafileFrameUnit frameUnit=MetafileFrameUnitGdi, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
Metafile (IStream *stream, HDC referenceHdc, const RectF &frameRect, MetafileFrameUnit frameUnit=MetafileFrameUnitGdi, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
Metafile (IStream *stream, HDC referenceHdc, EmfType type=EmfTypeEmfPlusDual, const WCHAR *description=NULL)
virtual ~Metafile ()
virtual Metafile * Clone () const
Status FindFirstItem (ImageItemData *item)
Status FindNextItem (ImageItemData *item)
Status GetAllPropertyItems (UINT totalBufferSize, UINT numProperties, PropertyItem *allItems)
Status GetBounds (RectF *srcRect, Unit *srcUnit)
UINT GetDownLevelRasterizationLimit () const
Status GetEncoderParameterList (const CLSID *clsidEncoder, UINT size, EncoderParameters *buffer)
UINT GetEncoderParameterListSize (const CLSID *clsidEncoder)
UINT GetFlags ()
UINT GetFrameCount (const GUID *dimensionID)
UINT GetFrameDimensionsCount ()
Status GetFrameDimensionsList (GUID *dimensionIDs, UINT count)
UINT GetHeight ()
HENHMETAFILE GetHENHMETAFILE ()
REAL GetHorizontalResolution ()
Status GetItemData (ImageItemData *item)
Status GetLastStatus () const
Status GetMetafileHeader (MetafileHeader *header) const
Status GetPalette (ColorPalette *palette, INT size)
INT GetPaletteSize ()
Status GetPhysicalDimension (SizeF *size)
PixelFormat GetPixelFormat ()
UINT GetPropertyCount ()
Status GetPropertyIdList (UINT numOfProperty, PROPID *list)
Status GetPropertyItem (PROPID propId, UINT propSize, PropertyItem *buffer)
UINT GetPropertyItemSize (PROPID propId)
Status GetPropertySize (UINT *totalBufferSize, UINT *numProperties)
Status GetRawFormat (GUID *format)
Image * GetThumbnailImage (UINT thumbWidth, UINT thumbHeight, GetThumbnailImageAbort callback, VOID *callbackData)
ImageType GetType () const
REAL GetVerticalResolution ()
UINT GetWidth ()
Status PlayRecord (EmfPlusRecordType recordType, UINT flags, UINT dataSize, const BYTE *data) const
Status RemovePropertyItem (PROPID propId)
Status RotateFlip (RotateFlipType rotateFlipType)
Status Save (const WCHAR *filename, const CLSID *clsidEncoder, const EncoderParameters *encoderParams)
Status Save (IStream *stream, const CLSID *clsidEncoder, const EncoderParameters *encoderParams)
Status SaveAdd (const EncoderParameters *encoderParams)
Status SaveAdd (Image *newImage, const EncoderParameters *encoderParams)
Status SelectActiveFrame (const GUID *dimensionID, UINT frameIndex)
Status SetAbort (GdiplusAbort *pIAbort)
Status SetDownLevelRasterizationLimit (UINT limitDpi)
Status SetPalette (const ColorPalette *palette)
Status SetPropertyItem (const PropertyItem *item)
Static Public Member Functions
static UINT EmfToWmfBits (HENHMETAFILE hEmf, UINT cbData16, LPBYTE pData16, INT iMapMode=MM_ANISOTROPIC, EmfToWmfBitsFlags eFlags=EmfToWmfBitsFlagsDefault)
static Image * FromFile (const WCHAR *filename, BOOL useEmbeddedColorManagement=FALSE)
static Image * FromStream (IStream *stream, BOOL useEmbeddedColorManagement=FALSE)
static Status GetMetafileHeader (const WCHAR *filename, MetafileHeader *header)
static Status GetMetafileHeader (HENHMETAFILE hEmf, MetafileHeader *header)
static Status GetMetafileHeader (IStream *stream, MetafileHeader *header)
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Metafile (const Metafile &)
Metafile (GpImage *image, Status status)
Metafile & operator= (const Metafile &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpImage * nativeImage
Detailed Description
Definition at line 33 of file gdiplusmetafile.h.
Constructor & Destructor Documentation
Metafile() [1/16]
Metafile::Metafile (HMETAFILE hWmf, const WmfPlaceableFileHeader * wmfPlaceableFileHeader, BOOL deleteWmf = FALSE) inline
Definition at line 69 of file gdiplusmetafile.h.
                                    : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipCreateMetafileFromWmf(
                 hWmf, deleteWmf, wmfPlaceableFileHeader,
                 &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipCreateMetafileFromWmf(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [2/16]
Metafile::Metafile (HENHMETAFILE hEmf, BOOL deleteEmf = FALSE) inline
Definition at line 79 of file gdiplusmetafile.h.
                                                        : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipCreateMetafileFromEmf(
                 hEmf, deleteEmf, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipCreateMetafileFromEmf(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [3/16]
Metafile::Metafile (const WCHAR * filename) inline
Definition at line 86 of file gdiplusmetafile.h.
                                    : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipCreateMetafileFromFile(
                 filename, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipCreateMetafileFromFile(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [4/16]
Metafile::Metafile (const WCHAR * filename, const WmfPlaceableFileHeader * wmfPlaceableFileHeader) inline
Definition at line 93 of file gdiplusmetafile.h.
                                                                  :
             Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipCreateMetafileFromWmfFile(
                 filename, wmfPlaceableFileHeader,
                 &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipCreateMetafileFromWmfFile(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [5/16]
Metafile::Metafile (IStream * stream) inline
Definition at line 103 of file gdiplusmetafile.h.
                              : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipCreateMetafileFromStream(
                 stream, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipCreateMetafileFromStream(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [6/16]
Metafile::Metafile (HDC referenceHdc, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 110 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafile(
                 referenceHdc, type, NULL, MetafileFrameUnitGdi,
                 description, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafile(), Image::lastStatus, MetafileFrameUnitGdi, Image::nativeImage, and NULL.
Metafile() [7/16]
Metafile::Metafile (HDC referenceHdc, const RectF & frameRect, MetafileFrameUnit frameUnit = MetafileFrameUnitGdi, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 119 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafile(
                 referenceHdc, type, &frameRect, frameUnit,
                 description, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafile(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [8/16]
Metafile::Metafile (HDC referenceHdc, const Rect & frameRect, MetafileFrameUnit frameUnit = MetafileFrameUnitGdi, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 130 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafileI(
                 referenceHdc, type, &frameRect, frameUnit,
                 description, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafileI(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [9/16]
Metafile::Metafile (const WCHAR * filename, HDC referenceHdc, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 141 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafileFileName(
                 filename, referenceHdc, type, NULL,
                 MetafileFrameUnitGdi, description,
                 &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafileFileName(), Image::lastStatus, MetafileFrameUnitGdi, Image::nativeImage, and NULL.
Metafile() [10/16]
Metafile::Metafile (const WCHAR * filename, HDC referenceHdc, const RectF & frameRect, MetafileFrameUnit frameUnit = MetafileFrameUnitGdi, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 152 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafileFileName(
                 filename, referenceHdc, type, &frameRect,
                 frameUnit, description, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafileFileName(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [11/16]
Metafile::Metafile (const WCHAR * filename, HDC referenceHdc, const Rect & frameRect, MetafileFrameUnit frameUnit = MetafileFrameUnitGdi, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 164 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafileFileNameI(
                 filename, referenceHdc, type, &frameRect,
                 frameUnit, description, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafileFileNameI(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [12/16]
Metafile::Metafile (IStream * stream, HDC referenceHdc, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 176 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafileStream(
                 stream, referenceHdc, type, NULL,
                 MetafileFrameUnitGdi, description,
                 &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafileStream(), Image::lastStatus, MetafileFrameUnitGdi, Image::nativeImage, and NULL.
Metafile() [13/16]
Metafile::Metafile (IStream * stream, HDC referenceHdc, const RectF & frameRect, MetafileFrameUnit frameUnit = MetafileFrameUnitGdi, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 187 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafileStream(
                 stream, referenceHdc, type, &frameRect,
                 frameUnit, description, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafileStream(), Image::lastStatus, Image::nativeImage, and NULL.
Metafile() [14/16]
Metafile::Metafile (IStream * stream, HDC referenceHdc, const Rect & frameRect, MetafileFrameUnit frameUnit = MetafileFrameUnitGdi, EmfType type = EmfTypeEmfPlusDual, const WCHAR * description = NULL) inline
Definition at line 198 of file gdiplusmetafile.h.
                                             : Image(NULL, Ok)
     {
         GpMetafile *nativeMetafile = NULL;
         lastStatus = DllExports::GdipRecordMetafileStreamI(
                 stream, referenceHdc, type, &frameRect,
                 frameUnit, description, &nativeMetafile);
         nativeImage = nativeMetafile;
     }
References GdipRecordMetafileStreamI(), Image::lastStatus, Image::nativeImage, and NULL.
~Metafile()
virtual Metafile::~Metafile () inline virtual
Definition at line 209 of file gdiplusmetafile.h.
     {
     }
Metafile() [15/16]
Metafile::Metafile (GpImage * image, Status status) inline private
Definition at line 300 of file gdiplusmetafile.h.
 : Image(image, status) {}
Metafile() [16/16]
Metafile::Metafile (const Metafile &) private
Member Function Documentation
Clone()
virtual Metafile* Metafile::Clone () const inline virtual
Reimplemented from Image.
Definition at line 212 of file gdiplusmetafile.h.
     {
         GpImage *cloneImage = NULL;
         Status status = updateStatus(DllExports::GdipCloneImage(
                 nativeImage, &cloneImage));
         if (status == Ok) {
             Metafile *result = new Metafile(cloneImage, lastStatus);
             if (!result) {
                 DllExports::GdipDisposeImage(cloneImage);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneImage(), GdipDisposeImage(), Image::lastStatus, Image::Metafile, Image::nativeImage, NULL, Ok, OutOfMemory, and Image::updateStatus().
EmfToWmfBits()
static UINT Metafile::EmfToWmfBits (HENHMETAFILE hEmf, UINT cbData16, LPBYTE pData16, INT iMapMode = MM_ANISOTROPIC, EmfToWmfBitsFlags eFlags = EmfToWmfBitsFlagsDefault) inline static
Definition at line 36 of file gdiplusmetafile.h.
     {
         return DllExports::GdipEmfToWmfBits(hEmf,
                 cbData16, pData16, iMapMode, eFlags);
     }
References GdipEmfToWmfBits().
FindFirstItem()
__inline__ Status Image::FindFirstItem (ImageItemData * item) inherited
Definition at line 79 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipFindFirstImageItem b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipFindFirstImageItem(
             nativeImage, item));
 }
References GdipFindFirstImageItem(), Image::nativeImage, and Image::updateStatus().
FindNextItem()
__inline__ Status Image::FindNextItem (ImageItemData * item) inherited
Definition at line 86 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipFindFirstImageItem b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipFindNextImageItem(
             nativeImage, item));
 }
References GdipFindNextImageItem(), Image::nativeImage, and Image::updateStatus().
FromFile()
__inline__ Image * Image::FromFile (const WCHAR * filename, BOOL useEmbeddedColorManagement = FALSE) static inherited
Definition at line 43 of file gdiplusimpl.h.
 {
     return new Image(filename, useEmbeddedColorManagement);
 }
References Image::Image().
FromStream()
__inline__ Image * Image::FromStream (IStream * stream, BOOL useEmbeddedColorManagement = FALSE) static inherited
Definition at line 49 of file gdiplusimpl.h.
 {
     return new Image(stream, useEmbeddedColorManagement);
 }
References Image::Image().
GetAllPropertyItems()
__inline__ Status Image::GetAllPropertyItems (UINT totalBufferSize, UINT numProperties, PropertyItem * allItems) inherited
Definition at line 93 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetAllPropertyItems(
             nativeImage, totalBufferSize, numProperties, allItems));
 }
References GdipGetAllPropertyItems(), Image::nativeImage, and Image::updateStatus().
GetBounds()
__inline__ Status Image::GetBounds (RectF * srcRect, Unit * srcUnit) inherited
Definition at line 100 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImageBounds(
             nativeImage, srcRect, srcUnit));
 }
References GdipGetImageBounds(), Image::nativeImage, and Image::updateStatus().
GetDownLevelRasterizationLimit()
UINT Metafile::GetDownLevelRasterizationLimit () const inline
Definition at line 267 of file gdiplusmetafile.h.
     {
         UINT result = 0;
         updateStatus(DllExports::GdipGetMetafileDownLevelRasterizationLimit(
                 (GpMetafile*) nativeImage, &result));
         return result;
     }
References GdipGetMetafileDownLevelRasterizationLimit(), Image::nativeImage, and Image::updateStatus().
GetEncoderParameterList()
__inline__ Status Image::GetEncoderParameterList (const CLSID * clsidEncoder, UINT size, EncoderParameters * buffer) inherited
Definition at line 106 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetEncoderParameterList(
             nativeImage, clsidEncoder, size, buffer));
 }
References GdipGetEncoderParameterList(), Image::nativeImage, and Image::updateStatus().
GetEncoderParameterListSize()
__inline__ UINT Image::GetEncoderParameterListSize (const CLSID * clsidEncoder) inherited
Definition at line 113 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetEncoderParameterListSize(
             nativeImage, clsidEncoder, &result));
     return result;
 }
References GdipGetEncoderParameterListSize(), Image::nativeImage, and Image::updateStatus().
GetFlags()
__inline__ UINT Image::GetFlags () inherited
Definition at line 121 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageFlags(nativeImage, &result));
     return result;
 }
References GdipGetImageFlags(), Image::nativeImage, and Image::updateStatus().
GetFrameCount()
__inline__ UINT Image::GetFrameCount (const GUID * dimensionID) inherited
Definition at line 128 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipImageGetFrameCount(
             nativeImage, dimensionID, &result));
     return result;
 }
References GdipImageGetFrameCount(), Image::nativeImage, and Image::updateStatus().
GetFrameDimensionsCount()
__inline__ UINT Image::GetFrameDimensionsCount () inherited
Definition at line 136 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipImageGetFrameDimensionsCount(
             nativeImage, &result));
     return result;
 }
References GdipImageGetFrameDimensionsCount(), Image::nativeImage, and Image::updateStatus().
GetFrameDimensionsList()
__inline__ Status Image::GetFrameDimensionsList (GUID * dimensionIDs, UINT count) inherited
Definition at line 144 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageGetFrameDimensionsList(
             nativeImage, dimensionIDs, count));
 }
References GdipImageGetFrameDimensionsList(), Image::nativeImage, and Image::updateStatus().
GetHeight()
__inline__ UINT Image::GetHeight () inherited
Definition at line 150 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageHeight(nativeImage, &result));
     return result;
 }
References GdipGetImageHeight(), Image::nativeImage, and Image::updateStatus().
GetHENHMETAFILE()
HENHMETAFILE Metafile::GetHENHMETAFILE () inline
Definition at line 274 of file gdiplusmetafile.h.
     {
         HENHMETAFILE result = NULL;
         updateStatus(DllExports::GdipGetHemfFromMetafile(
                 (GpMetafile*) nativeImage, &result));
         return result;
     }
References GdipGetHemfFromMetafile(), Image::nativeImage, NULL, and Image::updateStatus().
GetHorizontalResolution()
__inline__ REAL Image::GetHorizontalResolution () inherited
Definition at line 157 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetImageHorizontalResolution(
             nativeImage, &result));
     return result;
 }
References GdipGetImageHorizontalResolution(), Image::nativeImage, and Image::updateStatus().
GetItemData()
__inline__ Status Image::GetItemData (ImageItemData * item) inherited
Definition at line 165 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipGetImageItemData b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipGetImageItemData(
             nativeImage, item));
 }
References GdipGetImageItemData(), Image::nativeImage, and Image::updateStatus().
GetLastStatus()
Status Image::GetLastStatus () const inline inherited
Definition at line 133 of file gdiplusheaders.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References Image::lastStatus, and Ok.
GetMetafileHeader() [1/4]
static Status Metafile::GetMetafileHeader (const WCHAR * filename, MetafileHeader * header) inline static
Definition at line 44 of file gdiplusmetafile.h.
     {
         return DllExports::GdipGetMetafileHeaderFromFile(
                 filename, header);
     }
References GdipGetMetafileHeaderFromFile().
GetMetafileHeader() [2/4]
static Status Metafile::GetMetafileHeader (HENHMETAFILE hEmf, MetafileHeader * header) inline static
Definition at line 63 of file gdiplusmetafile.h.
     {
         return DllExports::GdipGetMetafileHeaderFromEmf(hEmf, header);
     }
References GdipGetMetafileHeaderFromEmf().
GetMetafileHeader() [3/4]
static Status Metafile::GetMetafileHeader (IStream * stream, MetafileHeader * header) inline static
Definition at line 50 of file gdiplusmetafile.h.
     {
         return DllExports::GdipGetMetafileHeaderFromStream(
                 stream, header);
     }
References GdipGetMetafileHeaderFromStream().
GetMetafileHeader() [4/4]
Status Metafile::GetMetafileHeader (MetafileHeader * header) const inline
Definition at line 281 of file gdiplusmetafile.h.
     {
         return updateStatus(DllExports::GdipGetMetafileHeaderFromMetafile(
                 (GpMetafile*) nativeImage, header));
     }
References GdipGetMetafileHeaderFromMetafile(), Image::nativeImage, and Image::updateStatus().
GetPalette()
__inline__ Status Image::GetPalette (ColorPalette * palette, INT size) inherited
Definition at line 172 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImagePalette(
             nativeImage, palette, size));
 }
References GdipGetImagePalette(), Image::nativeImage, and Image::updateStatus().
GetPaletteSize()
__inline__ INT Image::GetPaletteSize () inherited
Definition at line 178 of file gdiplusimpl.h.
 {
     INT result = 0;
     updateStatus(DllExports::GdipGetImagePaletteSize(nativeImage, &result));
     return result;
 }
References GdipGetImagePaletteSize(), Image::nativeImage, and Image::updateStatus().
GetPhysicalDimension()
__inline__ Status Image::GetPhysicalDimension (SizeF * size) inherited
Definition at line 185 of file gdiplusimpl.h.
 {
     if (!size) return lastStatus = InvalidParameter;
     return updateStatus(DllExports::GdipGetImageDimension(
             nativeImage, &size->Width, &size->Height));
 }
References GdipGetImageDimension(), InvalidParameter, Image::lastStatus, Image::nativeImage, and Image::updateStatus().
GetPixelFormat()
__inline__ PixelFormat Image::GetPixelFormat () inherited
Definition at line 192 of file gdiplusimpl.h.
 {
     PixelFormat result = (PixelFormat) 0;
     updateStatus(DllExports::GdipGetImagePixelFormat(nativeImage, &result));
     return result;
 }
References GdipGetImagePixelFormat(), Image::nativeImage, and Image::updateStatus().
GetPropertyCount()
__inline__ UINT Image::GetPropertyCount () inherited
Definition at line 199 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetPropertyCount(nativeImage, &result));
     return result;
 }
References GdipGetPropertyCount(), Image::nativeImage, and Image::updateStatus().
GetPropertyIdList()
__inline__ Status Image::GetPropertyIdList (UINT numOfProperty, PROPID * list) inherited
Definition at line 206 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertyIdList(
             nativeImage, numOfProperty, list));
 }
References GdipGetPropertyIdList(), Image::nativeImage, and Image::updateStatus().
GetPropertyItem()
__inline__ Status Image::GetPropertyItem (PROPID propId, UINT propSize, PropertyItem * buffer) inherited
Definition at line 212 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertyItem(
             nativeImage, propId, propSize, buffer));
 }
References GdipGetPropertyItem(), Image::nativeImage, and Image::updateStatus().
GetPropertyItemSize()
__inline__ UINT Image::GetPropertyItemSize (PROPID propId) inherited
Definition at line 219 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetPropertyItemSize(
             nativeImage, propId, &result));
     return result;
 }
References GdipGetPropertyItemSize(), Image::nativeImage, and Image::updateStatus().
GetPropertySize()
__inline__ Status Image::GetPropertySize (UINT * totalBufferSize, UINT * numProperties) inherited
Definition at line 227 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertySize(
             nativeImage, totalBufferSize, numProperties));
 }
References GdipGetPropertySize(), Image::nativeImage, and Image::updateStatus().
GetRawFormat()
__inline__ Status Image::GetRawFormat (GUID * format) inherited
Definition at line 234 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImageRawFormat(
             nativeImage, format));
 }
References GdipGetImageRawFormat(), Image::nativeImage, and Image::updateStatus().
GetThumbnailImage()
__inline__ Image * Image::GetThumbnailImage (UINT thumbWidth, UINT thumbHeight, GetThumbnailImageAbort callback, VOID * callbackData) inherited
Definition at line 240 of file gdiplusimpl.h.
 {
     GpImage *thumbImage = NULL;
     Status status = updateStatus(DllExports::GdipGetImageThumbnail(
             nativeImage, thumbWidth, thumbHeight, &thumbImage,
             callback, callbackData));
     if (status == Ok) {
         Image *result = new Image(thumbImage, Ok);
         if (!result) {
             DllExports::GdipDisposeImage(thumbImage);
             lastStatus = OutOfMemory;
         }
         return result;
     } else {
         return NULL;
     }
 }
References GdipDisposeImage(), GdipGetImageThumbnail(), Image::Image(), Image::lastStatus, Image::nativeImage, NULL, Ok, OutOfMemory, and Image::updateStatus().
GetType()
__inline__ ImageType Image::GetType () const inherited
Definition at line 260 of file gdiplusimpl.h.
 {
     ImageType result = ImageTypeUnknown;
     updateStatus(DllExports::GdipGetImageType(nativeImage, &result));
     return result;
 }
References GdipGetImageType(), ImageTypeUnknown, Image::nativeImage, and Image::updateStatus().
GetVerticalResolution()
__inline__ REAL Image::GetVerticalResolution () inherited
Definition at line 267 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetImageVerticalResolution(
             nativeImage, &result));
     return result;
 }
References GdipGetImageVerticalResolution(), Image::nativeImage, and Image::updateStatus().
GetWidth()
__inline__ UINT Image::GetWidth () inherited
Definition at line 275 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageWidth(nativeImage, &result));
     return result;
 }
References GdipGetImageWidth(), Image::nativeImage, and Image::updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Metafile& Metafile::operator= (const Metafile &) private
PlayRecord()
Status Metafile::PlayRecord (EmfPlusRecordType recordType, UINT flags, UINT dataSize, const BYTE * data) const inline
Definition at line 286 of file gdiplusmetafile.h.
     {
         return updateStatus(DllExports::GdipPlayMetafileRecord(
                 (GpMetafile*) nativeImage,
                 recordType, flags, dataSize, data));
     }
References GdipPlayMetafileRecord(), Image::nativeImage, and Image::updateStatus().
RemovePropertyItem()
__inline__ Status Image::RemovePropertyItem (PROPID propId) inherited
Definition at line 282 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipRemovePropertyItem(
             nativeImage, propId));
 }
References GdipRemovePropertyItem(), Image::nativeImage, and Image::updateStatus().
RotateFlip()
__inline__ Status Image::RotateFlip (RotateFlipType rotateFlipType) inherited
Definition at line 288 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageRotateFlip(
             nativeImage, rotateFlipType));
 }
References GdipImageRotateFlip(), Image::nativeImage, and Image::updateStatus().
Save() [1/2]
__inline__ Status Image::Save (const WCHAR * filename, const CLSID * clsidEncoder, const EncoderParameters * encoderParams) inherited
Definition at line 294 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveImageToFile(
             nativeImage, filename, clsidEncoder, encoderParams));
 }
References GdipSaveImageToFile(), Image::nativeImage, and Image::updateStatus().
Save() [2/2]
__inline__ Status Image::Save (IStream * stream, const CLSID * clsidEncoder, const EncoderParameters * encoderParams) inherited
Definition at line 301 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveImageToStream(
             nativeImage, stream, clsidEncoder, encoderParams));
 }
References GdipSaveImageToStream(), Image::nativeImage, and Image::updateStatus().
SaveAdd() [1/2]
__inline__ Status Image::SaveAdd (const EncoderParameters * encoderParams) inherited
Definition at line 308 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveAdd(
             nativeImage, encoderParams));
 }
References GdipSaveAdd(), Image::nativeImage, and Image::updateStatus().
SaveAdd() [2/2]
__inline__ Status Image::SaveAdd (Image * newImage, const EncoderParameters * encoderParams) inherited
Definition at line 314 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveAddImage(
             nativeImage,
             newImage ? newImage->nativeImage : NULL,
             encoderParams));
 }
References GdipSaveAddImage(), Image::nativeImage, NULL, and Image::updateStatus().
SelectActiveFrame()
__inline__ Status Image::SelectActiveFrame (const GUID * dimensionID, UINT frameIndex) inherited
Definition at line 323 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageSelectActiveFrame(
             nativeImage, dimensionID, frameIndex));
 }
References GdipImageSelectActiveFrame(), Image::nativeImage, and Image::updateStatus().
SetAbort()
__inline__ Status Image::SetAbort (GdiplusAbort * pIAbort) inherited
Definition at line 330 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipImageSetAbort because it isn't exported in 1.0
     return updateStatus(DllExports::GdipImageSetAbort(
             nativeImage, pIAbort));
 }
References GdipImageSetAbort(), Image::nativeImage, and Image::updateStatus().
SetDownLevelRasterizationLimit()
Status Metafile::SetDownLevelRasterizationLimit (UINT limitDpi) inline
Definition at line 293 of file gdiplusmetafile.h.
     {
         return updateStatus(DllExports::GdipSetMetafileDownLevelRasterizationLimit(
                 (GpMetafile*) nativeImage, limitDpi));
     }
References GdipSetMetafileDownLevelRasterizationLimit(), Image::nativeImage, and Image::updateStatus().
SetPalette()
__inline__ Status Image::SetPalette (const ColorPalette * palette) inherited
Definition at line 337 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetImagePalette(
             nativeImage, palette));
 }
References GdipSetImagePalette(), Image::nativeImage, and Image::updateStatus().
SetPropertyItem()
__inline__ Status Image::SetPropertyItem (const PropertyItem * item) inherited
Definition at line 343 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetPropertyItem(nativeImage, item));
 }
References GdipSetPropertyItem(), Image::nativeImage, and Image::updateStatus().
updateStatus()
Status Image::updateStatus (Status newStatus) const inline private inherited
Definition at line 146 of file gdiplusheaders.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References Image::lastStatus, and Ok.
Referenced by Image::Clone(), Bitmap::Clone(), Clone(), Bitmap::ConvertFormat(), Image::FindFirstItem(), Image::FindNextItem(), Image::GetAllPropertyItems(), Image::GetBounds(), GetDownLevelRasterizationLimit(), Image::GetEncoderParameterList(), Image::GetEncoderParameterListSize(), Image::GetFlags(), Image::GetFrameCount(), Image::GetFrameDimensionsCount(), Image::GetFrameDimensionsList(), Bitmap::GetHBITMAP(), Image::GetHeight(), GetHENHMETAFILE(), Bitmap::GetHICON(), Bitmap::GetHistogram(), Bitmap::GetHistogramSize(), Image::GetHorizontalResolution(), Image::GetItemData(), GetMetafileHeader(), Image::GetPalette(), Image::GetPaletteSize(), Image::GetPhysicalDimension(), Bitmap::GetPixel(), Image::GetPixelFormat(), Image::GetPropertyCount(), Image::GetPropertyIdList(), Image::GetPropertyItem(), Image::GetPropertyItemSize(), Image::GetPropertySize(), Image::GetRawFormat(), Image::GetThumbnailImage(), Image::GetType(), Image::GetVerticalResolution(), Image::GetWidth(), Bitmap::LockBits(), PlayRecord(), Image::RemovePropertyItem(), Image::RotateFlip(), Image::Save(), Image::SaveAdd(), Image::SelectActiveFrame(), Image::SetAbort(), SetDownLevelRasterizationLimit(), Image::SetPalette(), Bitmap::SetPixel(), Image::SetPropertyItem(), Bitmap::SetResolution(), and Bitmap::UnlockBits().
Field Documentation
lastStatus
Status Image::lastStatus mutable private inherited
Definition at line 153 of file gdiplusheaders.h.
Referenced by Bitmap::Bitmap(), Image::Clone(), Bitmap::Clone(), Clone(), Image::GetLastStatus(), Image::GetPhysicalDimension(), Image::GetThumbnailImage(), Image::Image(), Metafile(), and Image::updateStatus().
nativeImage
GpImage* Image::nativeImage private inherited
Definition at line 152 of file gdiplusheaders.h.
Referenced by Bitmap::Bitmap(), CachedBitmap::CachedBitmap(), Image::Clone(), Bitmap::Clone(), Clone(), Bitmap::ConvertFormat(), Graphics::EnumerateMetafile(), Image::FindFirstItem(), Image::FindNextItem(), Image::GetAllPropertyItems(), Image::GetBounds(), GetDownLevelRasterizationLimit(), Image::GetEncoderParameterList(), Image::GetEncoderParameterListSize(), Image::GetFlags(), Image::GetFrameCount(), Image::GetFrameDimensionsCount(), Image::GetFrameDimensionsList(), Bitmap::GetHBITMAP(), Image::GetHeight(), GetHENHMETAFILE(), Bitmap::GetHICON(), Bitmap::GetHistogram(), Image::GetHorizontalResolution(), Image::GetItemData(), GetMetafileHeader(), Image::GetPalette(), Image::GetPaletteSize(), Image::GetPhysicalDimension(), Bitmap::GetPixel(), Image::GetPixelFormat(), Image::GetPropertyCount(), Image::GetPropertyIdList(), Image::GetPropertyItem(), Image::GetPropertyItemSize(), Image::GetPropertySize(), Image::GetRawFormat(), Image::GetThumbnailImage(), Image::GetType(), Image::GetVerticalResolution(), Image::GetWidth(), Image::Image(), Bitmap::InitializePalette(), Bitmap::LockBits(), Metafile(), PlayRecord(), Image::RemovePropertyItem(), Image::RotateFlip(), Image::Save(), Image::SaveAdd(), Image::SelectActiveFrame(), Image::SetAbort(), SetDownLevelRasterizationLimit(), Image::SetPalette(), Bitmap::SetPixel(), Image::SetPropertyItem(), Bitmap::SetResolution(), Bitmap::UnlockBits(), and Image::~Image().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusmetafile.h