ZEQ2-Lite: Source/Engine/jpeg-8c/jdatadst.c File Reference
jdatadst.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jerror.h"
Data Structures
struct my_destination_mgr
struct my_mem_destination_mgr
Macros
#define OUTPUT_BUF_SIZE 4096 /* choose an efficiently fwrite'able size */
Typedefs
typedef my_destination_mgr * my_dest_ptr
typedef my_mem_destination_mgr * my_mem_dest_ptr
Functions
empty_mem_output_buffer (j_compress_ptr cinfo)
empty_output_buffer (j_compress_ptr cinfo)
init_destination (j_compress_ptr cinfo)
init_mem_destination (j_compress_ptr cinfo)
jpeg_mem_dest (j_compress_ptr cinfo, unsigned char **outbuffer, unsigned long *outsize)
jpeg_stdio_dest (j_compress_ptr cinfo, FILE *outfile)
term_destination (j_compress_ptr cinfo)
term_mem_destination (j_compress_ptr cinfo)
Macro Definition Documentation
OUTPUT_BUF_SIZE
#define OUTPUT_BUF_SIZE 4096 /* choose an efficiently fwrite'able size */
Definition at line 40 of file jdatadst.c.
Typedef Documentation
my_dest_ptr
typedef my_destination_mgr* my_dest_ptr
Definition at line 38 of file jdatadst.c.
my_mem_dest_ptr
typedef my_mem_destination_mgr* my_mem_dest_ptr
Definition at line 55 of file jdatadst.c.
Function Documentation
empty_mem_output_buffer()
empty_mem_output_buffer (j_compress_ptr cinfo)
Definition at line 123 of file jdatadst.c.
 {
   size_t nextsize;
   JOCTET * nextbuffer;
   my_mem_dest_ptr dest = (my_mem_dest_ptr) cinfo->dest;
   /* Try to allocate new buffer with double size */
   nextsize = dest->bufsize * 2;
   nextbuffer = malloc(nextsize);
   if (nextbuffer == NULL)
     ERREXIT1(cinfo, JERR_OUT_OF_MEMORY, 10);
   MEMCOPY(nextbuffer, dest->buffer, dest->bufsize);
   if (dest->newbuffer != NULL)
     free(dest->newbuffer);
   dest->newbuffer = nextbuffer;
   dest->pub.next_output_byte = nextbuffer + dest->bufsize;
   dest->pub.free_in_buffer = dest->bufsize;
   dest->buffer = nextbuffer;
   dest->bufsize = nextsize;
   return TRUE;
 }
References my_mem_destination_mgr::buffer, my_mem_destination_mgr::bufsize, ERREXIT1, jpeg_destination_mgr::free_in_buffer, MEMCOPY, my_mem_destination_mgr::newbuffer, jpeg_destination_mgr::next_output_byte, NULL, my_mem_destination_mgr::pub, and TRUE.
Referenced by jpeg_mem_dest().
empty_output_buffer()
empty_output_buffer (j_compress_ptr cinfo)
Definition at line 108 of file jdatadst.c.
 {
   my_dest_ptr dest = (my_dest_ptr) cinfo->dest;
   if (JFWRITE(dest->outfile, dest->buffer, OUTPUT_BUF_SIZE) !=
       (size_t) OUTPUT_BUF_SIZE)
     ERREXIT(cinfo, JERR_FILE_WRITE);
   dest->pub.next_output_byte = dest->buffer;
   dest->pub.free_in_buffer = OUTPUT_BUF_SIZE;
   return TRUE;
 }
References my_destination_mgr::buffer, ERREXIT, jpeg_destination_mgr::free_in_buffer, JFWRITE, jpeg_destination_mgr::next_output_byte, my_destination_mgr::outfile, OUTPUT_BUF_SIZE, my_destination_mgr::pub, and TRUE.
Referenced by jpeg_stdio_dest().
init_destination()
init_destination (j_compress_ptr cinfo)
Definition at line 64 of file jdatadst.c.
 {
   my_dest_ptr dest = (my_dest_ptr) cinfo->dest;
   /* Allocate the output buffer --- it will be released when done with image */
   dest->buffer = (JOCTET *)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                   OUTPUT_BUF_SIZE * SIZEOF(JOCTET));
   dest->pub.next_output_byte = dest->buffer;
   dest->pub.free_in_buffer = OUTPUT_BUF_SIZE;
 }
References my_destination_mgr::buffer, jpeg_destination_mgr::free_in_buffer, JPOOL_IMAGE, jpeg_destination_mgr::next_output_byte, OUTPUT_BUF_SIZE, my_destination_mgr::pub, and SIZEOF.
Referenced by jpeg_stdio_dest().
init_mem_destination()
init_mem_destination (j_compress_ptr cinfo)
Definition at line 78 of file jdatadst.c.
 {
   /* no work necessary here */
 }
Referenced by jpeg_mem_dest().
jpeg_mem_dest()
jpeg_mem_dest (j_compress_ptr cinfo, unsigned char ** outbuffer, unsigned long * outsize)
Definition at line 232 of file jdatadst.c.
 {
   my_mem_dest_ptr dest;
   if (outbuffer == NULL || outsize == NULL) /* sanity check */
     ERREXIT(cinfo, JERR_BUFFER_SIZE);
   /* The destination object is made permanent so that multiple JPEG images
    * can be written to the same buffer without re-executing jpeg_mem_dest.
    */
   if (cinfo->dest == NULL) {    /* first time for this JPEG object? */
     cinfo->dest = (struct jpeg_destination_mgr *)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_PERMANENT,
                   SIZEOF(my_mem_destination_mgr));
   }
   dest = (my_mem_dest_ptr) cinfo->dest;
   dest->pub.init_destination = init_mem_destination;
   dest->pub.empty_output_buffer = empty_mem_output_buffer;
   dest->pub.term_destination = term_mem_destination;
   dest->outbuffer = outbuffer;
   dest->outsize = outsize;
   dest->newbuffer = NULL;
   if (*outbuffer == NULL || *outsize == 0) {
     /* Allocate initial buffer */
     dest->newbuffer = *outbuffer = malloc(OUTPUT_BUF_SIZE);
     if (dest->newbuffer == NULL)
       ERREXIT1(cinfo, JERR_OUT_OF_MEMORY, 10);
     *outsize = OUTPUT_BUF_SIZE;
   }
   dest->pub.next_output_byte = dest->buffer = *outbuffer;
   dest->pub.free_in_buffer = dest->bufsize = *outsize;
 }
References my_mem_destination_mgr::buffer, my_mem_destination_mgr::bufsize, empty_mem_output_buffer(), ERREXIT, ERREXIT1, jpeg_destination_mgr::free_in_buffer, init_mem_destination(), JPOOL_PERMANENT, my_mem_destination_mgr::newbuffer, jpeg_destination_mgr::next_output_byte, NULL, my_mem_destination_mgr::outbuffer, outbuffer, OUTPUT_BUF_SIZE, my_mem_destination_mgr::outsize, outsize, my_mem_destination_mgr::pub, SIZEOF, and term_mem_destination().
jpeg_stdio_dest()
jpeg_stdio_dest (j_compress_ptr cinfo, FILE * outfile)
Definition at line 196 of file jdatadst.c.
 {
   my_dest_ptr dest;
   /* The destination object is made permanent so that multiple JPEG images
    * can be written to the same file without re-executing jpeg_stdio_dest.
    * This makes it dangerous to use this manager and a different destination
    * manager serially with the same JPEG object, because their private object
    * sizes may be different.  Caveat programmer.
    */
   if (cinfo->dest == NULL) {    /* first time for this JPEG object? */
     cinfo->dest = (struct jpeg_destination_mgr *)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_PERMANENT,
                   SIZEOF(my_destination_mgr));
   }
   dest = (my_dest_ptr) cinfo->dest;
   dest->pub.init_destination = init_destination;
   dest->pub.empty_output_buffer = empty_output_buffer;
   dest->pub.term_destination = term_destination;
   dest->outfile = outfile;
 }
References empty_output_buffer(), init_destination(), JPOOL_PERMANENT, NULL, my_destination_mgr::outfile, outfile, my_destination_mgr::pub, SIZEOF, and term_destination().
term_destination()
term_destination (j_compress_ptr cinfo)
Definition at line 163 of file jdatadst.c.
 {
   my_dest_ptr dest = (my_dest_ptr) cinfo->dest;
   size_t datacount = OUTPUT_BUF_SIZE - dest->pub.free_in_buffer;
   /* Write any data remaining in the buffer */
   if (datacount > 0) {
     if (JFWRITE(dest->outfile, dest->buffer, datacount) != datacount)
       ERREXIT(cinfo, JERR_FILE_WRITE);
   }
   fflush(dest->outfile);
   /* Make sure we wrote the output file OK */
   if (ferror(dest->outfile))
     ERREXIT(cinfo, JERR_FILE_WRITE);
 }
References my_destination_mgr::buffer, ERREXIT, jpeg_destination_mgr::free_in_buffer, JFWRITE, my_destination_mgr::outfile, OUTPUT_BUF_SIZE, and my_destination_mgr::pub.
Referenced by jpeg_stdio_dest().
term_mem_destination()
term_mem_destination (j_compress_ptr cinfo)
Definition at line 180 of file jdatadst.c.
 {
   my_mem_dest_ptr dest = (my_mem_dest_ptr) cinfo->dest;
   *dest->outbuffer = dest->buffer;
   *dest->outsize = dest->bufsize - dest->pub.free_in_buffer;
 }
References my_mem_destination_mgr::buffer, my_mem_destination_mgr::bufsize, jpeg_destination_mgr::free_in_buffer, my_mem_destination_mgr::outbuffer, my_mem_destination_mgr::outsize, and my_mem_destination_mgr::pub.
Referenced by jpeg_mem_dest().