ZEQ2-Lite: Game/CGame/cg_drawtools.c File Reference
cg_drawtools.c File Reference
#include "cg_local.h"
Macros
#define PROPB_GAP_WIDTH 4
#define PROPB_HEIGHT 36
#define PROPB_SPACE_WIDTH 12
Functions
void CG_AdjustFrom640 (float *x, float *y, float *w, float *h, qboolean stretch)
void CG_ColorForHealth (vec4_t hcolor)
void CG_DrawBigString (int x, int y, const char *s, float alpha)
void CG_DrawBigStringColor (int x, int y, const char *s, vec4_t color)
void CG_DrawChar (int x, int y, int width, int height, int ch)
void CG_DrawMediumStringColor (int x, int y, const char *s, vec4_t color)
void CG_DrawPic (qboolean stretch, float x, float y, float width, float height, qhandle_t hShader)
void CG_DrawRect (float x, float y, float width, float height, float size, const float *color)
void CG_DrawSides (float x, float y, float w, float h, float size)
void CG_DrawSmallString (int x, int y, const char *s, float alpha)
void CG_DrawSmallStringColor (int x, int y, const char *s, vec4_t color)
void CG_DrawSmallStringCustom (int x, int y, int w, int h, const char *s, float alpha, int spacing)
void CG_DrawSmallStringHalfHeight (int x, int y, const char *s, float alpha)
void CG_DrawStringExt (int spacing, int x, int y, const char *string, const float *setColor, qboolean forceColor, qboolean shadow, int charWidth, int charHeight, int maxChars)
int CG_DrawStrlen (const char *str)
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
float * CG_FadeColor (int startMsec, int totalMsec, int fadeTime)
void CG_FillRect (float x, float y, float width, float height, const float *color)
void CG_GetColorForHealth (int powerLevel, int armor, vec4_t hcolor)
float * CG_TeamColor (int team)
void CG_TileClear (void)
static void CG_TileClearBox (int x, int y, int w, int h, qhandle_t hShader)
void UI_DrawBannerString (int x, int y, const char *str, int style, vec4_t color)
static void UI_DrawBannerString2 (int x, int y, const char *str, vec4_t color)
void UI_DrawProportionalString (int x, int y, const char *str, int style, vec4_t color)
static void UI_DrawProportionalString2 (int x, int y, const char *str, vec4_t color, float sizeScale, qhandle_t charset)
float UI_ProportionalSizeScale (int style)
int UI_ProportionalStringWidth (const char *str)
Variables
static int propMap [128][3]
static int propMapB [26][3]
Macro Definition Documentation
PROPB_GAP_WIDTH
#define PROPB_GAP_WIDTH 4
Definition at line 607 of file cg_drawtools.c.
PROPB_HEIGHT
#define PROPB_HEIGHT 36
Definition at line 609 of file cg_drawtools.c.
PROPB_SPACE_WIDTH
#define PROPB_SPACE_WIDTH 12
Definition at line 608 of file cg_drawtools.c.
Function Documentation
CG_AdjustFrom640()
void CG_AdjustFrom640 (float * x, float * y, float * w, float * h, qboolean stretch)
Definition at line 33 of file cg_drawtools.c.
{
         float offset = 1.33333333333333 + ((cgs.screenXScale/cgs.screenYScale) - 1.0);
         float width = *w;
         float height = *h;
         stretch = qtrue;
         *x *= cgs.screenXScale;
         *y *= cgs.screenYScale;
         *w *= stretch ? cgs.screenXScale : offset;
         *h *= stretch ? cgs.screenYScale : offset;
         if(!stretch){
             //*x -= *x - width;
             //*y -= height -*h;
         }
         //*x = (*x * cgs.screenXScale) - (*w - width);
         //*y = (*y * cgs.screenYScale) - (*h - height);
 }
References cgs, qtrue, cgs_t::screenXScale, and cgs_t::screenYScale.
Referenced by CG_Draw3DModel(), CG_DrawChar(), CG_DrawPic(), CG_DrawSides(), CG_DrawTopBottom(), and CG_FillRect().
CG_ColorForHealth()
void CG_ColorForHealth (vec4_t hcolor)
Definition at line 451 of file cg_drawtools.c.
{
 //  CG_GetColorForHealth( cg.snap->ps.powerLevel[current],
 //      cg.snap->ps.stats[STAT_ARMOR], hcolor );
     CG_GetColorForHealth( cg.snap->ps.powerLevel[plCurrent],
         0, hcolor );
 }
References cg, CG_GetColorForHealth(), plCurrent, snapshot_t::ps, and cg_t::snap.
Referenced by CG_DrawCrosshair().
CG_DrawBigString()
void CG_DrawBigString (int x, int y, const char * s, float alpha)
Definition at line 221 of file cg_drawtools.c.
{
     float   color[4];
     color[0] = color[1] = color[2] = 1.0;
     color[3] = alpha;
     CG_DrawStringExt(-1, x, y, s, color, qfalse, qtrue, BIGCHAR_WIDTH, BIGCHAR_HEIGHT, 0 );
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, CG_DrawStringExt(), qfalse, and qtrue.
Referenced by CG_DrawCrosshairNames(), CG_DrawDisconnect(), CG_DrawFPS(), CG_DrawSnapshot(), CG_DrawSpectator(), CG_DrawTimer(), and CG_DrawWarmup().
CG_DrawBigStringColor()
void CG_DrawBigStringColor (int x, int y, const char * s, vec4_t color)
Definition at line 229 of file cg_drawtools.c.
{
     CG_DrawStringExt(-1, x, y, s, color, qtrue, qtrue, BIGCHAR_WIDTH, BIGCHAR_HEIGHT, 0 );
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, CG_DrawStringExt(), and qtrue.
CG_DrawChar()
void CG_DrawChar (int x, int y, int width, int height, int ch)
Definition at line 125 of file cg_drawtools.c.
{
     int row, col;
     float frow, fcol;
     float size;
     float   ax, ay, aw, ah;
     ch &= 255;
     if ( ch == ' ' ) {
         return;
     }
     ax = x;
     ay = y;
     aw = width;
     ah = height;
     CG_AdjustFrom640( &ax, &ay, &aw, &ah, qtrue);
     row = ch>>4;
     col = ch&15;
     frow = row*0.0625;
     fcol = col*0.0625;
     size = 0.0625;
     trap_R_DrawStretchPic( ax, ay, aw, ah,
                        fcol, frow,
                        fcol + size, frow + size,
                        cgs.media.charsetShader );
 }
References CG_AdjustFrom640(), cgs, cgMedia_t::charsetShader, cgs_t::media, qtrue, and trap_R_DrawStretchPic().
Referenced by CG_DrawStringExt().
CG_DrawMediumStringColor()
void CG_DrawMediumStringColor (int x, int y, const char * s, vec4_t color)
Definition at line 261 of file cg_drawtools.c.
{
     CG_DrawStringExt(-1, x, y, s, color, qtrue, qtrue, MEDIUMCHAR_WIDTH, MEDIUMCHAR_HEIGHT, 0 );
 }
References CG_DrawStringExt(), MEDIUMCHAR_HEIGHT, MEDIUMCHAR_WIDTH, and qtrue.
Referenced by CG_DrawWeaponSelectQuarterFan().
CG_DrawPic()
void CG_DrawPic (qboolean stretch, float x, float y, float width, float height, qhandle_t hShader)
Definition at line 111 of file cg_drawtools.c.
{
     CG_AdjustFrom640( &x, &y, &width, &height,stretch);
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
References CG_AdjustFrom640(), and trap_R_DrawStretchPic().
Referenced by CG_CheckChat(), CG_DrawCrosshair(), CG_DrawDisconnect(), CG_DrawField(), CG_DrawHead(), CG_DrawHorGauge(), CG_DrawHUD(), CG_DrawInformation(), CG_DrawLoadingIcons(), CG_DrawRadarBlips(), CG_DrawScreenEffects(), CG_DrawScripted2D(), CG_DrawStatusBar(), CG_DrawVertGauge(), CG_DrawWeaponSelectHorCenterBar(), and CG_DrawWeaponSelectQuarterFan().
CG_DrawRect()
void CG_DrawRect (float x, float y, float width, float height, float size, const float * color)
Definition at line 93 of file cg_drawtools.c.
{
     trap_R_SetColor( color );
   CG_DrawTopBottom(x, y, width, height, size);
   CG_DrawSides(x, y, width, height, size);
     trap_R_SetColor( NULL );
 }
References CG_DrawSides(), CG_DrawTopBottom(), NULL, and trap_R_SetColor().
Referenced by CG_DrawActive(), and CG_DrawScreenFlash().
CG_DrawSides()
void CG_DrawSides (float x, float y, float w, float h, float size)
Definition at line 73 of file cg_drawtools.c.
{
     CG_AdjustFrom640( &x, &y, &w, &h,qtrue);
     size *= cgs.screenXScale;
     trap_R_DrawStretchPic( x, y, size, h, 0, 0, 0, 0, cgs.media.whiteShader );
     trap_R_DrawStretchPic( x + w - size, y, size, h, 0, 0, 0, 0, cgs.media.whiteShader );
 }
References CG_AdjustFrom640(), cgs, cgs_t::media, qtrue, cgs_t::screenXScale, trap_R_DrawStretchPic(), and cgMedia_t::whiteShader.
Referenced by CG_DrawRect().
CG_DrawSmallString()
void CG_DrawSmallString (int x, int y, const char * s, float alpha)
Definition at line 233 of file cg_drawtools.c.
{
     float   color[4];
     color[0] = color[1] = color[2] = 1.0;
     color[3] = alpha;
     CG_DrawStringExt(-1, x, y, s, color, qfalse, qtrue, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT, 0 );
 }
References CG_DrawStringExt(), qfalse, qtrue, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by CG_DrawTeamVote(), and CG_DrawVote().
CG_DrawSmallStringColor()
void CG_DrawSmallStringColor (int x, int y, const char * s, vec4_t color)
Definition at line 257 of file cg_drawtools.c.
{
     CG_DrawStringExt(-1, x, y, s, color, qtrue, qtrue, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT, 0 );
 }
References CG_DrawStringExt(), qtrue, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
CG_DrawSmallStringCustom()
void CG_DrawSmallStringCustom (int x, int y, int w, int h, const char * s, float alpha, int spacing)
Definition at line 241 of file cg_drawtools.c.
{
     float   color[4];
     color[0] = color[1] = color[2] = 1.0;
     color[3] = alpha;
     CG_DrawStringExt(spacing, x, y, s, color, qfalse, qtrue, w, h, 0 );
 }
References CG_DrawStringExt(), qfalse, and qtrue.
Referenced by CG_CheckChat(), and CG_DrawLoadingIcons().
CG_DrawSmallStringHalfHeight()
void CG_DrawSmallStringHalfHeight (int x, int y, const char * s, float alpha)
Definition at line 249 of file cg_drawtools.c.
{
     float   color[4];
     color[0] = color[1] = color[2] = 1.0;
     color[3] = alpha;
     CG_DrawStringExt(-1, x, y, s, color, qfalse, qtrue, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT / 2, 0 );
 }
References CG_DrawStringExt(), qfalse, qtrue, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by CG_DrawHUD(), and CG_DrawScoreboard().
CG_DrawStringExt()
void CG_DrawStringExt (int spacing, int x, int y, const char * string, const float * setColor, qboolean forceColor, qboolean shadow, int charWidth, int charHeight, int maxChars)
Definition at line 167 of file cg_drawtools.c.
{
     vec4_t      color;
     const char  *s;
     int         xx;
     int         cnt;
     if (maxChars <= 0)
         maxChars = 32767; // do them all!
     spacing = spacing == -1 ? charWidth : spacing;
     // draw the drop shadow
     if (shadow) {
         color[0] = color[1] = color[2] = 0;
         color[3] = 0.5;
         trap_R_SetColor( color );
         s = string;
         xx = x;
         cnt = 0;
         while ( *s && cnt < maxChars) {
             if ( Q_IsColorString( s ) ) {
                 s += 2;
                 continue;
             }
             CG_DrawChar( xx + 1, y + 1, charWidth, charHeight, *s );
             cnt++;
             xx += spacing;
             s++;
         }
     }
     // draw the colored text
     s = string;
     xx = x;
     cnt = 0;
     trap_R_SetColor( setColor );
     while ( *s && cnt < maxChars) {
         if ( Q_IsColorString( s ) ) {
             if ( !forceColor ) {
                 memcpy( color, g_color_table[ColorIndex(*(s+1))], sizeof( color ) );
                 color[3] = setColor[3];
                 trap_R_SetColor( color );
             }
             s += 2;
             continue;
         }
         CG_DrawChar( xx, y, charWidth, charHeight, *s );
         xx += spacing;
         cnt++;
         s++;
     }
     trap_R_SetColor( NULL );
 }
References CG_DrawChar(), ColorIndex, g_color_table, NULL, Q_IsColorString, trap_R_SetColor(), and xx.
Referenced by CG_DrawBigString(), CG_DrawBigStringColor(), CG_DrawCenterString(), CG_DrawMediumStringColor(), CG_DrawSmallString(), CG_DrawSmallStringColor(), CG_DrawSmallStringCustom(), CG_DrawSmallStringHalfHeight(), and CG_DrawWarmup().
CG_DrawStrlen()
int CG_DrawStrlen (const char * str)
Definition at line 272 of file cg_drawtools.c.
{
     const char *s = str;
     int count = 0;
     while ( *s ) {
         if ( Q_IsColorString( s ) ) {
             s += 2;
         } else {
             count++;
             s++;
         }
     }
     return count;
 }
References Q_IsColorString.
Referenced by CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawDisconnect(), CG_DrawFPS(), CG_DrawSnapshot(), CG_DrawTimer(), CG_DrawWarmup(), and CG_DrawWeaponSelectHorCenterBar().
CG_DrawTopBottom()
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
Definition at line 80 of file cg_drawtools.c.
{
     CG_AdjustFrom640( &x, &y, &w, &h,qtrue);
     size *= cgs.screenYScale;
     trap_R_DrawStretchPic( x, y, w, size, 0, 0, 0, 0, cgs.media.whiteShader );
     trap_R_DrawStretchPic( x, y + h - size, w, size, 0, 0, 0, 0, cgs.media.whiteShader );
 }
References CG_AdjustFrom640(), cgs, cgs_t::media, qtrue, cgs_t::screenYScale, trap_R_DrawStretchPic(), and cgMedia_t::whiteShader.
Referenced by CG_DrawRect().
CG_FadeColor()
float* CG_FadeColor (int startMsec, int totalMsec, int fadeTime)
Definition at line 352 of file cg_drawtools.c.
{
     static vec4_t       color;
     int         t;
     if ( startMsec == 0 ) {
         return NULL;
     }
     t = cg.time - startMsec;
     if ( t >= totalMsec ) {
         return NULL;
     }
     // fade out
     if ( totalMsec - t < fadeTime ) {
         color[3] = ( totalMsec - t ) * 1.0/fadeTime;
     } else {
         color[3] = 1.0;
     }
     color[0] = color[1] = color[2] = 1;
     return color;
 }
References cg, NULL, and cg_t::time.
Referenced by CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawScreenFlash(), CG_DrawWeaponSelectHorCenterBar(), and CG_DrawWeaponSelectQuarterFan().
CG_FillRect()
void CG_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 57 of file cg_drawtools.c.
{
     trap_R_SetColor( color );
     CG_AdjustFrom640( &x, &y, &width, &height,qtrue);
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 0, 0, cgs.media.whiteShader );
     trap_R_SetColor( NULL );
 }
References CG_AdjustFrom640(), cgs, cgs_t::media, NULL, qtrue, trap_R_DrawStretchPic(), trap_R_SetColor(), and cgMedia_t::whiteShader.
CG_GetColorForHealth()
void CG_GetColorForHealth (int powerLevel, int armor, vec4_t hcolor)
Definition at line 408 of file cg_drawtools.c.
{
     int     count;
     int     max;
     // calculate the total points of damage that can
     // be sustained at the current powerLevel / armor level
     if ( powerLevel <= 0 ) {
         VectorClear( hcolor );  // black
         hcolor[3] = 1;
         return;
     }
     count = armor;
     max = powerLevel * ARMOR_PROTECTION / ( 1.0 - ARMOR_PROTECTION );
     if ( max < count ) {
         count = max;
     }
     powerLevel += count;
     // set the color based on powerLevel
     hcolor[0] = 1.0;
     hcolor[3] = 1.0;
     if ( powerLevel >= 100 ) {
         hcolor[2] = 1.0;
     } else if ( powerLevel < 66 ) {
         hcolor[2] = 0;
     } else {
         hcolor[2] = ( powerLevel - 66 ) / 33.0;
     }
     if ( powerLevel > 60 ) {
         hcolor[1] = 1.0;
     } else if ( powerLevel < 30 ) {
         hcolor[1] = 0;
     } else {
         hcolor[1] = ( powerLevel - 30 ) / 30.0;
     }
 }
References ARMOR_PROTECTION, and VectorClear.
Referenced by CG_ColorForHealth().
CG_TeamColor()
float* CG_TeamColor (int team)
Definition at line 383 of file cg_drawtools.c.
{
     static vec4_t   red = {1, 0.2f, 0.2f, 1};
     static vec4_t   blue = {0.2f, 0.2f, 1, 1};
     static vec4_t   other = {1, 1, 1, 1};
     static vec4_t   spectator = {0.7f, 0.7f, 0.7f, 1};
     switch ( team ) {
     case TEAM_RED:
         return red;
     case TEAM_BLUE:
         return blue;
     case TEAM_SPECTATOR:
         return spectator;
     default:
         return other;
     }
 }
References TEAM_BLUE, TEAM_RED, and TEAM_SPECTATOR.
CG_TileClear()
void CG_TileClear (void)
Definition at line 315 of file cg_drawtools.c.
{
     int     top, bottom, left, right;
     int     w, h;
     w = cgs.glconfig.vidWidth;
     h = cgs.glconfig.vidHeight;
     if ( cg.refdef.x == 0 && cg.refdef.y == 0 &&
         cg.refdef.width == w && cg.refdef.height == h ) {
         return;     // full screen rendering
     }
     top = cg.refdef.y;
     bottom = top + cg.refdef.height-1;
     left = cg.refdef.x;
     right = left + cg.refdef.width-1;
     // clear above view screen
     CG_TileClearBox( 0, 0, w, top, cgs.media.backTileShader );
     // clear below view screen
     CG_TileClearBox( 0, bottom, w, h - bottom, cgs.media.backTileShader );
     // clear left of view screen
     CG_TileClearBox( 0, top, left, bottom - top + 1, cgs.media.backTileShader );
     // clear right of view screen
     CG_TileClearBox( right, top, w - right, bottom - top + 1, cgs.media.backTileShader );
 }
References cgMedia_t::backTileShader, cg, CG_TileClearBox(), cgs, cgs_t::glconfig, refdef_t::height, cgs_t::media, cg_t::refdef, right, glconfig_t::vidHeight, glconfig_t::vidWidth, refdef_t::width, refdef_t::x, and refdef_t::y.
Referenced by CG_DrawActive().
CG_TileClearBox()
static void CG_TileClearBox (int x, int y, int w, int h, qhandle_t hShader) static
Definition at line 296 of file cg_drawtools.c.
{
     float   s1, t1, s2, t2;
     s1 = x/64.0;
     t1 = y/64.0;
     s2 = (x+w)/64.0;
     t2 = (y+h)/64.0;
     trap_R_DrawStretchPic( x, y, w, h, s1, t1, s2, t2, hShader );
 }
References trap_R_DrawStretchPic().
Referenced by CG_TileClear().
UI_DrawBannerString()
void UI_DrawBannerString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 659 of file cg_drawtools.c.
{
     const char *    s;
     int             ch;
     int             width;
     vec4_t          drawcolor;
     // find the width of the drawn text
     s = str;
     width = 0;
     while ( *s ) {
         ch = *s;
         if ( ch == ' ' ) {
             width += PROPB_SPACE_WIDTH;
         }
         else if ( ch >= 'A' && ch <= 'Z' ) {
             width += propMapB[ch - 'A'][2] + PROPB_GAP_WIDTH;
         }
         s++;
     }
     width -= PROPB_GAP_WIDTH;
     switch( style & UI_FORMATMASK ) {
         case UI_CENTER:
             x -= width / 2;
             break;
         case UI_RIGHT:
             x -= width;
             break;
         case UI_LEFT:
         default:
             break;
     }
     if ( style & UI_DROPSHADOW ) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawBannerString2( x+1, y+1, str, drawcolor );
     }
     UI_DrawBannerString2( x, y, str, color );
 }
Referenced by BText_Draw().
UI_DrawBannerString2()
static void UI_DrawBannerString2 (int x, int y, const char * str, vec4_t color) static
Definition at line 616 of file cg_drawtools.c.
 {
     const char* s;
     unsigned char   ch;
     float   ax;
     float   ay;
     float   aw;
     float   ah;
     float   frow;
     float   fcol;
     float   fwidth;
     float   fheight;
     // draw the colored text
     trap_R_SetColor( color );
     ax = x * cgs.screenXScale + cgs.screenXBias;
     ay = y * cgs.screenYScale;
     s = str;
     while ( *s )
     {
         ch = *s & 127;
         if ( ch == ' ' ) {
             ax += ((float)PROPB_SPACE_WIDTH + (float)PROPB_GAP_WIDTH)* cgs.screenXScale;
         }
         else if ( ch >= 'A' && ch <= 'Z' ) {
             ch -= 'A';
             fcol = (float)propMapB[ch][0] / 256.0f;
             frow = (float)propMapB[ch][1] / 256.0f;
             fwidth = (float)propMapB[ch][2] / 256.0f;
             fheight = (float)PROPB_HEIGHT / 256.0f;
             aw = (float)propMapB[ch][2] * cgs.screenXScale;
             ah = (float)PROPB_HEIGHT * cgs.screenYScale;
             trap_R_DrawStretchPic( ax, ay, aw, ah, fcol, frow, fcol+fwidth, frow+fheight, cgs.media.charsetPropB );
             ax += (aw + (float)PROPB_GAP_WIDTH * cgs.screenXScale);
         }
         s++;
     }
     trap_R_SetColor( NULL );
 }
References cgs, cgMedia_t::charsetPropB, cgs_t::media, NULL, PROPB_GAP_WIDTH, PROPB_HEIGHT, PROPB_SPACE_WIDTH, propMapB, cgs_t::screenXBias, cgs_t::screenXScale, cgs_t::screenYScale, trap_R_DrawStretchPic(), and trap_R_SetColor().
Referenced by UI_DrawBannerString().
UI_DrawProportionalString()
void UI_DrawProportionalString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 789 of file cg_drawtools.c.
{
     vec4_t  drawcolor;
     int     width;
     float   sizeScale;
     sizeScale = UI_ProportionalSizeScale( style );
     switch( style & UI_FORMATMASK ) {
         case UI_CENTER:
             width = UI_ProportionalStringWidth( str ) * sizeScale;
             x -= width / 2;
             break;
         case UI_RIGHT:
             width = UI_ProportionalStringWidth( str ) * sizeScale;
             x -= width;
             break;
         case UI_LEFT:
         default:
             break;
     }
     if ( style & UI_DROPSHADOW ) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x+1, y+1, str, drawcolor, sizeScale, cgs.media.charsetProp );
     }
     if ( style & UI_INVERSE ) {
         drawcolor[0] = color[0] * 0.8;
         drawcolor[1] = color[1] * 0.8;
         drawcolor[2] = color[2] * 0.8;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x, y, str, drawcolor, sizeScale, cgs.media.charsetProp );
         return;
     }
     if ( style & UI_PULSE ) {
         drawcolor[0] = color[0] * 0.8;
         drawcolor[1] = color[1] * 0.8;
         drawcolor[2] = color[2] * 0.8;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x, y, str, color, sizeScale, cgs.media.charsetProp );
         drawcolor[0] = color[0];
         drawcolor[1] = color[1];
         drawcolor[2] = color[2];
         drawcolor[3] = 0.5 + 0.5 * sin( cg.time / PULSE_DIVISOR );
         UI_DrawProportionalString2( x, y, str, drawcolor, sizeScale, cgs.media.charsetPropGlow );
         return;
     }
     UI_DrawProportionalString2( x, y, str, color, sizeScale, cgs.media.charsetProp );
 }
Referenced by ConfirmMenu_Draw(), Controls_ResetDefaults_Draw(), MessageMenu_Draw(), PlayerModel_DrawPlayer(), PText_Draw(), UI_CreditMenu_Draw(), and UI_DisplayDownloadInfo().
UI_DrawProportionalString2()
static void UI_DrawProportionalString2 (int x, int y, const char * str, vec4_t color, float sizeScale, qhandle_t charset) static
Definition at line 726 of file cg_drawtools.c.
 {
     const char* s;
     unsigned char   ch;
     float   ax;
     float   ay;
     float   aw;
     float   ah;
     float   frow;
     float   fcol;
     float   fwidth;
     float   fheight;
     // draw the colored text
     trap_R_SetColor( color );
     ax = x * cgs.screenXScale + cgs.screenXBias;
     ay = y * cgs.screenYScale;
     s = str;
     while ( *s )
     {
         ch = *s & 127;
         if ( ch == ' ' ) {
             aw = (float)PROP_SPACE_WIDTH * cgs.screenXScale * sizeScale;
         } else if ( propMap[ch][2] != -1 ) {
             fcol = (float)propMap[ch][0] / 256.0f;
             frow = (float)propMap[ch][1] / 256.0f;
             fwidth = (float)propMap[ch][2] / 256.0f;
             fheight = (float)PROP_HEIGHT / 256.0f;
             aw = (float)propMap[ch][2] * cgs.screenXScale * sizeScale;
             ah = (float)PROP_HEIGHT * cgs.screenYScale * sizeScale;
             trap_R_DrawStretchPic( ax, ay, aw, ah, fcol, frow, fcol+fwidth, frow+fheight, charset );
         } else {
             aw = 0;
         }
         ax += (aw + (float)PROP_GAP_WIDTH * cgs.screenXScale * sizeScale);
         s++;
     }
     trap_R_SetColor( NULL );
 }
References cgs, NULL, PROP_GAP_WIDTH, PROP_HEIGHT, PROP_SPACE_WIDTH, propMap, cgs_t::screenXBias, cgs_t::screenXScale, cgs_t::screenYScale, trap_R_DrawStretchPic(), and trap_R_SetColor().
Referenced by UI_DrawProportionalString().
UI_ProportionalSizeScale()
float UI_ProportionalSizeScale (int style)
Definition at line 775 of file cg_drawtools.c.
{
     if(  style & UI_SMALLFONT ) {
         return 0.75;
     }
     return 1.00;
 }
Referenced by PText_Init(), UI_DisplayDownloadInfo(), and UI_DrawProportionalString().
UI_ProportionalStringWidth()
int UI_ProportionalStringWidth (const char * str)
Definition at line 704 of file cg_drawtools.c.
{
     const char *    s;
     int             ch;
     int             charWidth;
     int             width;
     s = str;
     width = 0;
     while ( *s ) {
         ch = *s & 127;
         charWidth = propMap[ch][2];
         if ( charWidth != -1 ) {
             width += charWidth;
             width += PROP_GAP_WIDTH;
         }
         s++;
     }
     width -= PROP_GAP_WIDTH;
     return width;
 }
Referenced by PText_Init(), UI_ConfirmMenu_Style(), UI_DisplayDownloadInfo(), UI_DrawProportionalString(), and UI_Message().
Variable Documentation
propMap
int propMap[128][3] static
Definition at line 465 of file cg_drawtools.c.
Referenced by UI_DrawProportionalString2(), and UI_ProportionalStringWidth().
propMapB
int propMapB[26][3] static
Definition at line 575 of file cg_drawtools.c.
Referenced by UI_DrawBannerString(), and UI_DrawBannerString2().