ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/ext/concurrence.h File Reference
concurrence.h File Reference
#include <exception>
#include <bits/gthr.h>
#include <bits/functexcept.h>
#include <bits/cpp_type_traits.h>
#include <ext/type_traits.h>
Functions
namespace __gnu_cxx _GLIBCXX_VISIBILITY (default)
Detailed Description
This file is a GNU extension to the Standard C++ Library.
Definition in file concurrence.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace __gnu_cxx _GLIBCXX_VISIBILITY (default)
Scoped lock idiom.
Definition at line 41 of file concurrence.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
   // Available locking policies:
   // _S_single    single-threaded code that doesn't need to be locked.
   // _S_mutex     multi-threaded code that requires additional support
   //              from gthr.h or abstraction layers in concurrence.h.
   // _S_atomic    multi-threaded code using atomic operations.
   enum _Lock_policy { _S_single, _S_mutex, _S_atomic };
   // Compile time constant that indicates prefered locking policy in
   // the current configuration.
   static const _Lock_policy __default_lock_policy =
 #ifdef __GTHREADS
 #if (defined(__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2) \
      && defined(__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4))
   _S_atomic;
 #else
   _S_mutex;
 #endif
 #else
   _S_single;
 #endif
   // NB: As this is used in libsupc++, need to only depend on
   // exception. No stdexception classes, no use of std::string.
   class __concurrence_lock_error : public std::exception
   {
   public:
     virtual char const*
     what() const throw()
     { return "__gnu_cxx::__concurrence_lock_error"; }
   };
   class __concurrence_unlock_error : public std::exception
   {
   public:
     virtual char const*
     what() const throw()
     { return "__gnu_cxx::__concurrence_unlock_error"; }
   };
   class __concurrence_broadcast_error : public std::exception
   {
   public:
     virtual char const*
     what() const throw()
     { return "__gnu_cxx::__concurrence_broadcast_error"; }
   };
   class __concurrence_wait_error : public std::exception
   {
   public:
     virtual char const*
     what() const throw()
     { return "__gnu_cxx::__concurrence_wait_error"; }
   };
   // Substitute for concurrence_error object in the case of -fno-exceptions.
   inline void
   __throw_concurrence_lock_error()
   {
 #if __EXCEPTIONS
     throw __concurrence_lock_error();
 #else
     __builtin_abort();
 #endif
   }
   inline void
   __throw_concurrence_unlock_error()
   {
 #if __EXCEPTIONS
     throw __concurrence_unlock_error();
 #else
     __builtin_abort();
 #endif
   }
 #ifdef __GTHREAD_HAS_COND
   inline void
   __throw_concurrence_broadcast_error()
   {
 #if __EXCEPTIONS
     throw __concurrence_broadcast_error();
 #else
     __builtin_abort();
 #endif
   }
   inline void
   __throw_concurrence_wait_error()
   {
 #if __EXCEPTIONS
     throw __concurrence_wait_error();
 #else
     __builtin_abort();
 #endif
   }
 #endif
   class __mutex
   {
   private:
     __gthread_mutex_t _M_mutex;
     __mutex(const __mutex&);
     __mutex& operator=(const __mutex&);
   public:
     __mutex()
     {
 #if __GTHREADS
       if (__gthread_active_p())
     {
 #if defined __GTHREAD_MUTEX_INIT
       __gthread_mutex_t __tmp = __GTHREAD_MUTEX_INIT;
       _M_mutex = __tmp;
 #else
       __GTHREAD_MUTEX_INIT_FUNCTION(&_M_mutex);
 #endif
     }
 #endif
     }
 #if __GTHREADS && ! defined __GTHREAD_MUTEX_INIT
     ~__mutex()
     {
       if (__gthread_active_p())
     __gthread_mutex_destroy(&_M_mutex);
     }
 #endif
     void lock()
     {
 #if __GTHREADS
       if (__gthread_active_p())
     {
       if (__gthread_mutex_lock(&_M_mutex) != 0)
         __throw_concurrence_lock_error();
     }
 #endif
     }
     void unlock()
     {
 #if __GTHREADS
       if (__gthread_active_p())
     {
       if (__gthread_mutex_unlock(&_M_mutex) != 0)
         __throw_concurrence_unlock_error();
     }
 #endif
     }
     __gthread_mutex_t* gthread_mutex(void)
       { return &_M_mutex; }
   };
   class __recursive_mutex
   {
   private:
     __gthread_recursive_mutex_t _M_mutex;
     __recursive_mutex(const __recursive_mutex&);
     __recursive_mutex& operator=(const __recursive_mutex&);
   public:
     __recursive_mutex()
     {
 #if __GTHREADS
       if (__gthread_active_p())
     {
 #if defined __GTHREAD_RECURSIVE_MUTEX_INIT
       __gthread_recursive_mutex_t __tmp = __GTHREAD_RECURSIVE_MUTEX_INIT;
       _M_mutex = __tmp;
 #else
       __GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION(&_M_mutex);
 #endif
     }
 #endif
     }
 #if __GTHREADS && ! defined __GTHREAD_RECURSIVE_MUTEX_INIT
     ~__recursive_mutex()
     {
       if (__gthread_active_p())
     _S_destroy(&_M_mutex);
     }
 #endif
     void lock()
     {
 #if __GTHREADS
       if (__gthread_active_p())
     {
       if (__gthread_recursive_mutex_lock(&_M_mutex) != 0)
         __throw_concurrence_lock_error();
     }
 #endif
     }
     void unlock()
     {
 #if __GTHREADS
       if (__gthread_active_p())
     {
       if (__gthread_recursive_mutex_unlock(&_M_mutex) != 0)
         __throw_concurrence_unlock_error();
     }
 #endif
     }
     __gthread_recursive_mutex_t* gthread_recursive_mutex(void)
     { return &_M_mutex; }
 #if __GTHREADS && ! defined __GTHREAD_RECURSIVE_MUTEX_INIT
     // FIXME: gthreads doesn't define __gthread_recursive_mutex_destroy
     // so we need to obtain a __gthread_mutex_t to destroy
   private:
     template<typename _Mx, typename _Rm>
       static void
       _S_destroy_win32(_Mx* __mx, _Rm const* __rmx)
       {
         __mx->counter = __rmx->counter;
         __mx->sema = __rmx->sema;
         __gthread_mutex_destroy(__mx);
       }
     // matches a gthr-win32.h recursive mutex
     template<typename _Rm>
       static typename __enable_if<sizeof(&_Rm::sema), void>::__type
       _S_destroy(_Rm* __mx)
       {
         __gthread_mutex_t __tmp;
         _S_destroy_win32(&__tmp, __mx);
       }
     // matches a recursive mutex with a member 'actual'
     template<typename _Rm>
       static typename __enable_if<sizeof(&_Rm::actual), void>::__type
       _S_destroy(_Rm* __mx)
       { __gthread_mutex_destroy(&__mx->actual); }
     // matches when there's only one mutex type
     template<typename _Rm>
       static typename
       __enable_if<std::__are_same<_Rm, __gthread_mutex_t>::__value,
         void>::__type
       _S_destroy(_Rm* __mx)
       { __gthread_mutex_destroy(__mx); }
 #endif
   };
   // Acquire the mutex here with a constructor call, then release with
   // the destructor call in accordance with RAII style.
   class __scoped_lock
   {
   public:
     typedef __mutex __mutex_type;
   private:
     __mutex_type& _M_device;
     __scoped_lock(const __scoped_lock&);
     __scoped_lock& operator=(const __scoped_lock&);
   public:
     explicit __scoped_lock(__mutex_type& __name) : _M_device(__name)
     { _M_device.lock(); }
     ~__scoped_lock() throw()
     { _M_device.unlock(); }
   };
 #ifdef __GTHREAD_HAS_COND
   class __cond
   {
   private:
     __gthread_cond_t _M_cond;
     __cond(const __cond&);
     __cond& operator=(const __cond&);
   public:
     __cond()
     {
 #if __GTHREADS
       if (__gthread_active_p())
     {
 #if defined __GTHREAD_COND_INIT
       __gthread_cond_t __tmp = __GTHREAD_COND_INIT;
       _M_cond = __tmp;
 #else
       __GTHREAD_COND_INIT_FUNCTION(&_M_cond);
 #endif
     }
 #endif
     }
 #if __GTHREADS && ! defined __GTHREAD_COND_INIT
     ~__cond()
     {
       if (__gthread_active_p())
     __gthread_cond_destroy(&_M_cond);
     }
 #endif
     void broadcast()
     {
 #if __GTHREADS
       if (__gthread_active_p())
     {
       if (__gthread_cond_broadcast(&_M_cond) != 0)
         __throw_concurrence_broadcast_error();
     }
 #endif
     }
     void wait(__mutex *mutex)
     {
 #if __GTHREADS
       {
       if (__gthread_cond_wait(&_M_cond, mutex->gthread_mutex()) != 0)
         __throw_concurrence_wait_error();
       }
 #endif
     }
     void wait_recursive(__recursive_mutex *mutex)
     {
 #if __GTHREADS
       {
       if (__gthread_cond_wait_recursive(&_M_cond,
                         mutex->gthread_recursive_mutex())
           != 0)
         __throw_concurrence_wait_error();
       }
 #endif
     }
   };
 #endif
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References __gthread_active_p(), __gthread_cond_broadcast(), __gthread_cond_destroy(), __GTHREAD_COND_INIT, __gthread_cond_wait(), __gthread_cond_wait_recursive(), __gthread_mutex_destroy(), __GTHREAD_MUTEX_INIT, __GTHREAD_MUTEX_INIT_FUNCTION, __gthread_mutex_lock(), __gthread_mutex_unlock(), __GTHREAD_RECURSIVE_MUTEX_INIT, __GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION, __gthread_recursive_mutex_lock(), __gthread_recursive_mutex_unlock(), __gthread_recursive_mutex_t::counter, and wait().