ZEQ2-Lite: Source/Engine/libspeex/lsp.h File Reference
lsp.h File Reference
Line Spectral Pair (LSP) functions.
#include "arch.h"
Functions
int lpc_to_lsp (spx_coef_t *a, int lpcrdr, spx_lsp_t *freq, int nb, spx_word16_t delta, char *stack)
void lsp_enforce_margin (spx_lsp_t *lsp, int len, spx_word16_t margin)
void lsp_interpolate (spx_lsp_t *old_lsp, spx_lsp_t *new_lsp, spx_lsp_t *interp_lsp, int len, int subframe, int nb_subframes)
void lsp_to_lpc (spx_lsp_t *freq, spx_coef_t *ak, int lpcrdr, char *stack)
Detailed Description
Line Spectral Pair (LSP) functions.
Definition in file lsp.h.
Function Documentation
lpc_to_lsp()
int lpc_to_lsp (spx_coef_t * a, int lpcrdr, spx_lsp_t * freq, int nb, spx_word16_t delta, char * stack)
Definition at line 219 of file lsp.c.
 {
     spx_word16_t temp_xr,xl,xr,xm=0;
     spx_word32_t psuml,psumr,psumm,temp_psumr/*,temp_qsumr*/;
     int i,j,m,flag,k;
     VARDECL(spx_word32_t *Q);                   /* ptrs for memory allocation       */
     VARDECL(spx_word32_t *P);
     VARDECL(spx_word16_t *Q16);         /* ptrs for memory allocation       */
     VARDECL(spx_word16_t *P16);
     spx_word32_t *px;                   /* ptrs of respective P'(z) & Q'(z) */
     spx_word32_t *qx;
     spx_word32_t *p;
     spx_word32_t *q;
     spx_word16_t *pt;                   /* ptr used for cheb_poly_eval()
                 whether P' or Q'            */
     int roots=0;                /* DR 8/2/94: number of roots found     */
     flag = 1;                   /*  program is searching for a root when,
                 1 else has found one            */
     m = lpcrdr/2;               /* order of P'(z) & Q'(z) polynomials   */
     /* Allocate memory space for polynomials */
     ALLOC(Q, (m+1), spx_word32_t);
     ALLOC(P, (m+1), spx_word32_t);
     /* determine P'(z)'s and Q'(z)'s coefficients where
       P'(z) = P(z)/(1 + z^(-1)) and Q'(z) = Q(z)/(1-z^(-1)) */
     px = P;                      /* initialise ptrs             */
     qx = Q;
     p = px;
     q = qx;
 #ifdef FIXED_POINT
     *px++ = LPC_SCALING;
     *qx++ = LPC_SCALING;
     for(i=0;i<m;i++){
        *px++ = SUB32(ADD32(EXTEND32(a[i]),EXTEND32(a[lpcrdr-i-1])), *p++);
        *qx++ = ADD32(SUB32(EXTEND32(a[i]),EXTEND32(a[lpcrdr-i-1])), *q++);
     }
     px = P;
     qx = Q;
     for(i=0;i<m;i++)
     {
        /*if (fabs(*px)>=32768)
           speex_warning_int("px", *px);
        if (fabs(*qx)>=32768)
        speex_warning_int("qx", *qx);*/
        *px = PSHR32(*px,2);
        *qx = PSHR32(*qx,2);
        px++;
        qx++;
     }
     /* The reason for this lies in the way cheb_poly_eva() is implemented for fixed-point */
     P[m] = PSHR32(P[m],3);
     Q[m] = PSHR32(Q[m],3);
 #else
     *px++ = LPC_SCALING;
     *qx++ = LPC_SCALING;
     for(i=0;i<m;i++){
        *px++ = (a[i]+a[lpcrdr-1-i]) - *p++;
        *qx++ = (a[i]-a[lpcrdr-1-i]) + *q++;
     }
     px = P;
     qx = Q;
     for(i=0;i<m;i++){
        *px = 2**px;
        *qx = 2**qx;
        px++;
        qx++;
     }
 #endif
     px = P;                 /* re-initialise ptrs           */
     qx = Q;
     /* now that we have computed P and Q convert to 16 bits to
        speed up cheb_poly_eval */
     ALLOC(P16, m+1, spx_word16_t);
     ALLOC(Q16, m+1, spx_word16_t);
     for (i=0;i<m+1;i++)
     {
        P16[i] = P[i];
        Q16[i] = Q[i];
     }
     /* Search for a zero in P'(z) polynomial first and then alternate to Q'(z).
     Keep alternating between the two polynomials as each zero is found  */
     xr = 0;                 /* initialise xr to zero        */
     xl = FREQ_SCALE;                /* start at point xl = 1        */
     for(j=0;j<lpcrdr;j++){
     if(j&1)             /* determines whether P' or Q' is eval. */
         pt = Q16;
     else
         pt = P16;
     psuml = cheb_poly_eva(pt,xl,m,stack);   /* evals poly. at xl    */
     flag = 1;
     while(flag && (xr >= -FREQ_SCALE)){
            spx_word16_t dd;
            /* Modified by JMV to provide smaller steps around x=+-1 */
 #ifdef FIXED_POINT
            dd = MULT16_16_Q15(delta,SUB16(FREQ_SCALE, MULT16_16_Q14(MULT16_16_Q14(xl,xl),14000)));
            if (psuml<512 && psuml>-512)
               dd = PSHR16(dd,1);
 #else
            dd=delta*(1-.9*xl*xl);
            if (fabs(psuml)<.2)
               dd *= .5;
 #endif
            xr = SUB16(xl, dd);                          /* interval spacing     */
         psumr = cheb_poly_eva(pt,xr,m,stack);/* poly(xl-delta_x)    */
         temp_psumr = psumr;
         temp_xr = xr;
     /* if no sign change increment xr and re-evaluate poly(xr). Repeat til
     sign change.
     if a sign change has occurred the interval is bisected and then
     checked again for a sign change which determines in which
     interval the zero lies in.
     If there is no sign change between poly(xm) and poly(xl) set interval
     between xm and xr else set interval between xl and xr and repeat till
     root is located within the specified limits             */
         if(SIGN_CHANGE(psumr,psuml))
             {
         roots++;
         psumm=psuml;
         for(k=0;k<=nb;k++){
 #ifdef FIXED_POINT
             xm = ADD16(PSHR16(xl,1),PSHR16(xr,1));          /* bisect the interval  */
 #else
                     xm = .5*(xl+xr);            /* bisect the interval  */
 #endif
             psumm=cheb_poly_eva(pt,xm,m,stack);
             /*if(psumm*psuml>0.)*/
             if(!SIGN_CHANGE(psumm,psuml))
                     {
             psuml=psumm;
             xl=xm;
             } else {
             psumr=psumm;
             xr=xm;
             }
         }
            /* once zero is found, reset initial interval to xr  */
            freq[j] = X2ANGLE(xm);
            xl = xm;
            flag = 0;            /* reset flag for next search   */
         }
         else{
         psuml=temp_psumr;
         xl=temp_xr;
         }
     }
     }
     return(roots);
 }
References ADD16, ADD32, ALLOC, cheb_poly_eva(), EXTEND32, FREQ_SCALE, LPC_SCALING, m, MULT16_16_Q14, MULT16_16_Q15, P, PSHR16, PSHR32, SIGN_CHANGE, SUB16, SUB32, VARDECL, and X2ANGLE.
Referenced by nb_encode(), and sb_encode().
lsp_enforce_margin()
void lsp_enforce_margin (spx_lsp_t * lsp, int len, spx_word16_t margin)
Definition at line 628 of file lsp.c.
 {
    int i;
    if (lsp[0]<LSP_SCALING*margin)
       lsp[0]=LSP_SCALING*margin;
    if (lsp[len-1]>LSP_SCALING*(M_PI-margin))
       lsp[len-1]=LSP_SCALING*(M_PI-margin);
    for (i=1;i<len-1;i++)
    {
       if (lsp[i]<lsp[i-1]+LSP_SCALING*margin)
          lsp[i]=lsp[i-1]+LSP_SCALING*margin;
       if (lsp[i]>lsp[i+1]-LSP_SCALING*margin)
          lsp[i]= .5f* (lsp[i] + lsp[i+1]-LSP_SCALING*margin);
    }
 }
References LSP_SCALING, and M_PI.
Referenced by nb_decode(), nb_encode(), sb_decode(), and sb_encode().
lsp_interpolate()
void lsp_interpolate (spx_lsp_t * old_lsp, spx_lsp_t * new_lsp, spx_lsp_t * interp_lsp, int len, int subframe, int nb_subframes)
Definition at line 646 of file lsp.c.
 {
    int i;
    float tmp = (1.0f + subframe)/nb_subframes;
    for (i=0;i<len;i++)
    {
       interp_lsp[i] = (1-tmp)*old_lsp[i] + tmp*new_lsp[i];
    }
 }
Referenced by nb_decode(), nb_encode(), sb_decode(), and sb_encode().
lsp_to_lpc()
void lsp_to_lpc (spx_lsp_t * freq, spx_coef_t * ak, int lpcrdr, char * stack)
Definition at line 522 of file lsp.c.
 {
     int i,j;
     float xout1,xout2,xin1,xin2;
     VARDECL(float *Wp);
     float *pw,*n1,*n2,*n3,*n4=NULL;
     VARDECL(float *x_freq);
     int m = lpcrdr>>1;
     ALLOC(Wp, 4*m+2, float);
     pw = Wp;
     /* initialise contents of array */
     for(i=0;i<=4*m+1;i++){          /* set contents of buffer to 0 */
     *pw++ = 0.0;
     }
     /* Set pointers up */
     pw = Wp;
     xin1 = 1.0;
     xin2 = 1.0;
     ALLOC(x_freq, lpcrdr, float);
     for (i=0;i<lpcrdr;i++)
        x_freq[i] = ANGLE2X(freq[i]);
     /* reconstruct P(z) and Q(z) by  cascading second order
       polynomials in form 1 - 2xz(-1) +z(-2), where x is the
       LSP coefficient */
     for(j=0;j<=lpcrdr;j++){
        int i2=0;
     for(i=0;i<m;i++,i2+=2){
         n1 = pw+(i*4);
         n2 = n1 + 1;
         n3 = n2 + 1;
         n4 = n3 + 1;
         xout1 = xin1 - 2.f*x_freq[i2] * *n1 + *n2;
         xout2 = xin2 - 2.f*x_freq[i2+1] * *n3 + *n4;
         *n2 = *n1;
         *n4 = *n3;
         *n1 = xin1;
         *n3 = xin2;
         xin1 = xout1;
         xin2 = xout2;
     }
     xout1 = xin1 + *(n4+1);
     xout2 = xin2 - *(n4+2);
     if (j>0)
        ak[j-1] = (xout1 + xout2)*0.5f;
     *(n4+1) = xin1;
     *(n4+2) = xin2;
     xin1 = 0.0;
     xin2 = 0.0;
     }
 }
References ALLOC, ANGLE2X, m, NULL, pw(), and VARDECL.
Referenced by nb_decode(), nb_encode(), sb_decode(), and sb_encode().