ZEQ2-Lite: SpeexEchoState: Acoustic echo canceller
SpeexEchoState: Acoustic echo canceller
This is the acoustic echo canceller module.
Data Structures
class SpeexEchoState
Macros
#define SPEEX_ECHO_GET_FRAME_SIZE 3
Obtain frame size used by the AEC.
#define SPEEX_ECHO_GET_SAMPLING_RATE 25
Get sampling rate.
#define SPEEX_ECHO_SET_SAMPLING_RATE 24
Set sampling rate.
Functions
void speex_echo_cancel (SpeexEchoState *st, const spx_int16_t *rec, const spx_int16_t *play, spx_int16_t *out, spx_int32_t *Yout)
Performs echo cancellation a frame (deprecated)
void speex_echo_cancellation (SpeexEchoState *st, const spx_int16_t *rec, const spx_int16_t *play, spx_int16_t *out)
Performs echo cancellation a frame, based on the audio sent to the speaker (no delay is added to playback in this form)
void speex_echo_capture (SpeexEchoState *st, const spx_int16_t *rec, spx_int16_t *out)
Perform echo cancellation using internal playback buffer, which is delayed by two frames to account for the delay introduced by most soundcards (but it could be off!)
int speex_echo_ctl (SpeexEchoState *st, int request, void *ptr)
Used like the ioctl function to control the echo canceller parameters.
void speex_echo_playback (SpeexEchoState *st, const spx_int16_t *play)
Let the echo canceller know that a frame was just queued to the soundcard.
void speex_echo_state_destroy (SpeexEchoState *st)
Destroys an echo canceller state.
SpeexEchoState * speex_echo_state_init (int frame_size, int filter_length)
Creates a new echo canceller state.
void speex_echo_state_reset (SpeexEchoState *st)
Reset the echo canceller to its original state.
Detailed Description
This is the acoustic echo canceller module.
Macro Definition Documentation
SPEEX_ECHO_GET_FRAME_SIZE
#define SPEEX_ECHO_GET_FRAME_SIZE 3
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Obtain frame size used by the AEC.
Definition at line 47 of file speex_echo.h.
SPEEX_ECHO_GET_SAMPLING_RATE
#define SPEEX_ECHO_GET_SAMPLING_RATE 25
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Get sampling rate.
Definition at line 52 of file speex_echo.h.
SPEEX_ECHO_SET_SAMPLING_RATE
#define SPEEX_ECHO_SET_SAMPLING_RATE 24
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Set sampling rate.
Definition at line 50 of file speex_echo.h.
Function Documentation
speex_echo_cancel()
void speex_echo_cancel (SpeexEchoState * st, const spx_int16_t * in, const spx_int16_t * far_end, spx_int16_t * out, spx_int32_t * Yout)
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Performs echo cancellation a frame (deprecated)
Performs echo cancellation a frame (deprecated)
Definition at line 640 of file mdf.c.
 {
    speex_echo_cancellation(st, in, far_end, out);
 }
References out, and speex_echo_cancellation().
speex_echo_cancellation()
void speex_echo_cancellation (SpeexEchoState * st, const spx_int16_t * in, const spx_int16_t * far_end, spx_int16_t * out)
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Performs echo cancellation a frame, based on the audio sent to the speaker (no delay is added to playback in this form)
Parameters
st Echo canceller state
rec Signal from the microphone (near end + far end echo)
play Signal played to the speaker (received from far end)
out Returns near-end signal with echo removed
Performs echo cancellation a frame, based on the audio sent to the speaker (no delay is added to playback in this form)
Definition at line 646 of file mdf.c.
 {
    int i,j;
    int N,M;
    spx_word32_t Syy,See,Sxx,Sdd, Sff;
 #ifdef TWO_PATH
    spx_word32_t Dbf;
    int update_foreground;
 #endif
    spx_word32_t Sey;
    spx_word16_t ss, ss_1;
    spx_float_t Pey = FLOAT_ONE, Pyy=FLOAT_ONE;
    spx_float_t alpha, alpha_1;
    spx_word16_t RER;
    spx_word32_t tmp32;
    N = st->window_size;
    M = st->M;
    st->cancel_count++;
 #ifdef FIXED_POINT
    ss=DIV32_16(11469,M);
    ss_1 = SUB16(32767,ss);
 #else
    ss=.35/M;
    ss_1 = 1-ss;
 #endif
    /* Apply a notch filter to make sure DC doesn't end up causing problems */
    filter_dc_notch16(in, st->notch_radius, st->input, st->frame_size, st->notch_mem);
    /* Copy input data to buffer and apply pre-emphasis */
    for (i=0;i<st->frame_size;i++)
    {
       spx_word32_t tmp32;
       tmp32 = SUB32(EXTEND32(far_end[i]), EXTEND32(MULT16_16_P15(st->preemph, st->memX)));
 #ifdef FIXED_POINT
       /* If saturation occurs here, we need to freeze adaptation for M+1 frames (not just one) */
       if (tmp32 > 32767)
       {
          tmp32 = 32767;
          st->saturated = M+1;
       }
       if (tmp32 < -32767)
       {
          tmp32 = -32767;
          st->saturated = M+1;
       }
 #endif
       st->x[i+st->frame_size] = EXTRACT16(tmp32);
       st->memX = far_end[i];
       tmp32 = SUB32(EXTEND32(st->input[i]), EXTEND32(MULT16_16_P15(st->preemph, st->memD)));
 #ifdef FIXED_POINT
       if (tmp32 > 32767)
       {
          tmp32 = 32767;
          if (st->saturated == 0)
             st->saturated = 1;
       }
       if (tmp32 < -32767)
       {
          tmp32 = -32767;
          if (st->saturated == 0)
             st->saturated = 1;
       }
 #endif
       st->memD = st->input[i];
       st->input[i] = tmp32;
    }
    /* Shift memory: this could be optimized eventually*/
    for (j=M-1;j>=0;j--)
    {
       for (i=0;i<N;i++)
          st->X[(j+1)*N+i] = st->X[j*N+i];
    }
    /* Convert x (far end) to frequency domain */
    spx_fft(st->fft_table, st->x, &st->X[0]);
    for (i=0;i<N;i++)
       st->last_y[i] = st->x[i];
    Sxx = mdf_inner_prod(st->x+st->frame_size, st->x+st->frame_size, st->frame_size);
    for (i=0;i<st->frame_size;i++)
       st->x[i] = st->x[i+st->frame_size];
    /* From here on, the top part of x is used as scratch space */
 #ifdef TWO_PATH
    /* Compute foreground filter */
    spectral_mul_accum16(st->X, st->foreground, st->Y, N, M);
    spx_ifft(st->fft_table, st->Y, st->e);
    for (i=0;i<st->frame_size;i++)
       st->e[i] = SUB16(st->input[i], st->e[i+st->frame_size]);
    Sff = mdf_inner_prod(st->e, st->e, st->frame_size);
 #endif
    /* Adjust proportional adaption rate */
    mdf_adjust_prop (st->W, N, M, st->prop);
    /* Compute weight gradient */
    if (st->saturated == 0)
    {
       for (j=M-1;j>=0;j--)
       {
          weighted_spectral_mul_conj(st->power_1, FLOAT_SHL(PSEUDOFLOAT(st->prop[j]),-15), &st->X[(j+1)*N], st->E, st->PHI, N);
          for (i=0;i<N;i++)
             st->W[j*N+i] = ADD32(st->W[j*N+i], st->PHI[i]);
       }
    } else {
       st->saturated--;
    }
    /* Update weight to prevent circular convolution (MDF / AUMDF) */
    for (j=0;j<M;j++)
    {
       /* This is a variant of the Alternatively Updated MDF (AUMDF) */
       /* Remove the "if" to make this an MDF filter */
       if (j==0 || st->cancel_count%(M-1) == j-1)
       {
 #ifdef FIXED_POINT
          for (i=0;i<N;i++)
             st->wtmp2[i] = EXTRACT16(PSHR32(st->W[j*N+i],NORMALIZE_SCALEDOWN+16));
          spx_ifft(st->fft_table, st->wtmp2, st->wtmp);
          for (i=0;i<st->frame_size;i++)
          {
             st->wtmp[i]=0;
          }
          for (i=st->frame_size;i<N;i++)
          {
             st->wtmp[i]=SHL16(st->wtmp[i],NORMALIZE_SCALEUP);
          }
          spx_fft(st->fft_table, st->wtmp, st->wtmp2);
          /* The "-1" in the shift is a sort of kludge that trades less efficient update speed for decrease noise */
          for (i=0;i<N;i++)
             st->W[j*N+i] -= SHL32(EXTEND32(st->wtmp2[i]),16+NORMALIZE_SCALEDOWN-NORMALIZE_SCALEUP-1);
 #else
          spx_ifft(st->fft_table, &st->W[j*N], st->wtmp);
          for (i=st->frame_size;i<N;i++)
          {
             st->wtmp[i]=0;
          }
          spx_fft(st->fft_table, st->wtmp, &st->W[j*N]);
 #endif
       }
    }
    /* Compute filter response Y */
    spectral_mul_accum(st->X, st->W, st->Y, N, M);
    spx_ifft(st->fft_table, st->Y, st->y);
 #ifdef TWO_PATH
    /* Difference in response, this is used to estimate the variance of our residual power estimate */
    for (i=0;i<st->frame_size;i++)
       st->e[i] = SUB16(st->e[i+st->frame_size], st->y[i+st->frame_size]);
    Dbf = 10+mdf_inner_prod(st->e, st->e, st->frame_size);
 #endif
    for (i=0;i<st->frame_size;i++)
       st->e[i] = SUB16(st->input[i], st->y[i+st->frame_size]);
    See = mdf_inner_prod(st->e, st->e, st->frame_size);
 #ifndef TWO_PATH
    Sff = See;
 #endif
 #ifdef TWO_PATH
    /* Logic for updating the foreground filter */
    /* For two time windows, compute the mean of the energy difference, as well as the variance */
    st->Davg1 = ADD32(MULT16_32_Q15(QCONST16(.6f,15),st->Davg1), MULT16_32_Q15(QCONST16(.4f,15),SUB32(Sff,See)));
    st->Davg2 = ADD32(MULT16_32_Q15(QCONST16(.85f,15),st->Davg2), MULT16_32_Q15(QCONST16(.15f,15),SUB32(Sff,See)));
    st->Dvar1 = FLOAT_ADD(FLOAT_MULT(VAR1_SMOOTH, st->Dvar1), FLOAT_MUL32U(MULT16_32_Q15(QCONST16(.4f,15),Sff), MULT16_32_Q15(QCONST16(.4f,15),Dbf)));
    st->Dvar2 = FLOAT_ADD(FLOAT_MULT(VAR2_SMOOTH, st->Dvar2), FLOAT_MUL32U(MULT16_32_Q15(QCONST16(.15f,15),Sff), MULT16_32_Q15(QCONST16(.15f,15),Dbf)));
    /* Equivalent float code:
    st->Davg1 = .6*st->Davg1 + .4*(Sff-See);
    st->Davg2 = .85*st->Davg2 + .15*(Sff-See);
    st->Dvar1 = .36*st->Dvar1 + .16*Sff*Dbf;
    st->Dvar2 = .7225*st->Dvar2 + .0225*Sff*Dbf;
    */
    update_foreground = 0;
    /* Check if we have a statistically significant reduction in the residual echo */
    /* Note that this is *not* Gaussian, so we need to be careful about the longer tail */
    if (FLOAT_GT(FLOAT_MUL32U(SUB32(Sff,See),ABS32(SUB32(Sff,See))), FLOAT_MUL32U(Sff,Dbf)))
       update_foreground = 1;
    else if (FLOAT_GT(FLOAT_MUL32U(st->Davg1, ABS32(st->Davg1)), FLOAT_MULT(VAR1_UPDATE,(st->Dvar1))))
       update_foreground = 1;
    else if (FLOAT_GT(FLOAT_MUL32U(st->Davg2, ABS32(st->Davg2)), FLOAT_MULT(VAR2_UPDATE,(st->Dvar2))))
       update_foreground = 1;
    /* Do we update? */
    if (update_foreground)
    {
       st->Davg1 = st->Davg2 = 0;
       st->Dvar1 = st->Dvar2 = FLOAT_ZERO;
       /* Copy background filter to foreground filter */
       for (i=0;i<N*M;i++)
          st->foreground[i] = EXTRACT16(PSHR32(st->W[i],16));
       /* Apply a smooth transition so as to not introduce blocking artifacts */
       for (i=0;i<st->frame_size;i++)
          st->e[i+st->frame_size] = MULT16_16_Q15(st->window[i+st->frame_size],st->e[i+st->frame_size]) + MULT16_16_Q15(st->window[i],st->y[i+st->frame_size]);
    } else {
       int reset_background=0;
       /* Otherwise, check if the background filter is significantly worse */
       if (FLOAT_GT(FLOAT_MUL32U(NEG32(SUB32(Sff,See)),ABS32(SUB32(Sff,See))), FLOAT_MULT(VAR_BACKTRACK,FLOAT_MUL32U(Sff,Dbf))))
          reset_background = 1;
       if (FLOAT_GT(FLOAT_MUL32U(NEG32(st->Davg1), ABS32(st->Davg1)), FLOAT_MULT(VAR_BACKTRACK,st->Dvar1)))
          reset_background = 1;
       if (FLOAT_GT(FLOAT_MUL32U(NEG32(st->Davg2), ABS32(st->Davg2)), FLOAT_MULT(VAR_BACKTRACK,st->Dvar2)))
          reset_background = 1;
       if (reset_background)
       {
          /* Copy foreground filter to background filter */
          for (i=0;i<N*M;i++)
             st->W[i] = SHL32(EXTEND32(st->foreground[i]),16);
          /* We also need to copy the output so as to get correct adaptation */
          for (i=0;i<st->frame_size;i++)
             st->y[i+st->frame_size] = st->e[i+st->frame_size];
          for (i=0;i<st->frame_size;i++)
             st->e[i] = SUB16(st->input[i], st->y[i+st->frame_size]);
          See = Sff;
          st->Davg1 = st->Davg2 = 0;
          st->Dvar1 = st->Dvar2 = FLOAT_ZERO;
       }
    }
 #endif
    /* Compute error signal (for the output with de-emphasis) */
    for (i=0;i<st->frame_size;i++)
    {
       spx_word32_t tmp_out;
 #ifdef TWO_PATH
       tmp_out = SUB32(EXTEND32(st->input[i]), EXTEND32(st->e[i+st->frame_size]));
 #else
       tmp_out = SUB32(EXTEND32(st->input[i]), EXTEND32(st->y[i+st->frame_size]));
 #endif
       /* Saturation */
       if (tmp_out>32767)
          tmp_out = 32767;
       else if (tmp_out<-32768)
          tmp_out = -32768;
       tmp_out = ADD32(tmp_out, EXTEND32(MULT16_16_P15(st->preemph, st->memE)));
       /* This is an arbitrary test for saturation in the microphone signal */
       if (in[i] <= -32000 || in[i] >= 32000)
       {
          tmp_out = 0;
          if (st->saturated == 0)
             st->saturated = 1;
       }
       out[i] = (spx_int16_t)tmp_out;
       st->memE = tmp_out;
    }
 #ifdef DUMP_ECHO_CANCEL_DATA
    dump_audio(in, far_end, out, st->frame_size);
 #endif
    /* Compute error signal (filter update version) */
    for (i=0;i<st->frame_size;i++)
    {
       st->e[i+st->frame_size] = st->e[i];
       st->e[i] = 0;
    }
    /* Compute a bunch of correlations */
    Sey = mdf_inner_prod(st->e+st->frame_size, st->y+st->frame_size, st->frame_size);
    Syy = mdf_inner_prod(st->y+st->frame_size, st->y+st->frame_size, st->frame_size);
    Sdd = mdf_inner_prod(st->input, st->input, st->frame_size);
    /*printf ("%f %f %f %f\n", Sff, See, Syy, Sdd, st->update_cond);*/
    /* Do some sanity check */
    if (!(Syy>=0 && Sxx>=0 && See >= 0)
 #ifndef FIXED_POINT
        || !(Sff < N*1e9 && Syy < N*1e9 && Sxx < N*1e9)
 #endif
       )
    {
       /* Things have gone really bad */
       st->screwed_up += 50;
       for (i=0;i<st->frame_size;i++)
          out[i] = 0;
    } else if (SHR32(Sff, 2) > ADD32(Sdd, SHR32(MULT16_16(N, 10000),6)))
    {
       /* AEC seems to add lots of echo instead of removing it, let's see if it will improve */
       st->screwed_up++;
    } else {
       /* Everything's fine */
       st->screwed_up=0;
    }
    if (st->screwed_up>=50)
    {
       speex_warning("The echo canceller started acting funny and got slapped (reset). It swears it will behave now.");
       speex_echo_state_reset(st);
       return;
    }
    /* Add a small noise floor to make sure not to have problems when dividing */
    See = MAX32(See, SHR32(MULT16_16(N, 100),6));
    /* Convert error to frequency domain */
    spx_fft(st->fft_table, st->e, st->E);
    for (i=0;i<st->frame_size;i++)
       st->y[i] = 0;
    spx_fft(st->fft_table, st->y, st->Y);
    /* Compute power spectrum of far end (X), error (E) and filter response (Y) */
    power_spectrum(st->E, st->Rf, N);
    power_spectrum(st->Y, st->Yf, N);
    power_spectrum(st->X, st->Xf, N);
    /* Smooth far end energy estimate over time */
    for (j=0;j<=st->frame_size;j++)
       st->power[j] = MULT16_32_Q15(ss_1,st->power[j]) + 1 + MULT16_32_Q15(ss,st->Xf[j]);
    /* Enable this to compute the power based only on the tail (would need to compute more
       efficiently to make this really useful */
    if (0)
    {
       float scale2 = .5f/M;
       for (j=0;j<=st->frame_size;j++)
          st->power[j] = 100;
       for (i=0;i<M;i++)
       {
          power_spectrum(&st->X[i*N], st->Xf, N);
          for (j=0;j<=st->frame_size;j++)
             st->power[j] += scale2*st->Xf[j];
       }
    }
    /* Compute filtered spectra and (cross-)correlations */
    for (j=st->frame_size;j>=0;j--)
    {
       spx_float_t Eh, Yh;
       Eh = PSEUDOFLOAT(st->Rf[j] - st->Eh[j]);
       Yh = PSEUDOFLOAT(st->Yf[j] - st->Yh[j]);
       Pey = FLOAT_ADD(Pey,FLOAT_MULT(Eh,Yh));
       Pyy = FLOAT_ADD(Pyy,FLOAT_MULT(Yh,Yh));
 #ifdef FIXED_POINT
       st->Eh[j] = MAC16_32_Q15(MULT16_32_Q15(SUB16(32767,st->spec_average),st->Eh[j]), st->spec_average, st->Rf[j]);
       st->Yh[j] = MAC16_32_Q15(MULT16_32_Q15(SUB16(32767,st->spec_average),st->Yh[j]), st->spec_average, st->Yf[j]);
 #else
       st->Eh[j] = (1-st->spec_average)*st->Eh[j] + st->spec_average*st->Rf[j];
       st->Yh[j] = (1-st->spec_average)*st->Yh[j] + st->spec_average*st->Yf[j];
 #endif
    }
    Pyy = FLOAT_SQRT(Pyy);
    Pey = FLOAT_DIVU(Pey,Pyy);
    /* Compute correlation updatete rate */
    tmp32 = MULT16_32_Q15(st->beta0,Syy);
    if (tmp32 > MULT16_32_Q15(st->beta_max,See))
       tmp32 = MULT16_32_Q15(st->beta_max,See);
    alpha = FLOAT_DIV32(tmp32, See);
    alpha_1 = FLOAT_SUB(FLOAT_ONE, alpha);
    /* Update correlations (recursive average) */
    st->Pey = FLOAT_ADD(FLOAT_MULT(alpha_1,st->Pey) , FLOAT_MULT(alpha,Pey));
    st->Pyy = FLOAT_ADD(FLOAT_MULT(alpha_1,st->Pyy) , FLOAT_MULT(alpha,Pyy));
    if (FLOAT_LT(st->Pyy, FLOAT_ONE))
       st->Pyy = FLOAT_ONE;
    /* We don't really hope to get better than 33 dB (MIN_LEAK-3dB) attenuation anyway */
    if (FLOAT_LT(st->Pey, FLOAT_MULT(MIN_LEAK,st->Pyy)))
       st->Pey = FLOAT_MULT(MIN_LEAK,st->Pyy);
    if (FLOAT_GT(st->Pey, st->Pyy))
       st->Pey = st->Pyy;
    /* leak_estimate is the linear regression result */
    st->leak_estimate = FLOAT_EXTRACT16(FLOAT_SHL(FLOAT_DIVU(st->Pey, st->Pyy),14));
    /* This looks like a stupid bug, but it's right (because we convert from Q14 to Q15) */
    if (st->leak_estimate > 16383)
       st->leak_estimate = 32767;
    else
       st->leak_estimate = SHL16(st->leak_estimate,1);
    /*printf ("%f\n", st->leak_estimate);*/
    /* Compute Residual to Error Ratio */
 #ifdef FIXED_POINT
    tmp32 = MULT16_32_Q15(st->leak_estimate,Syy);
    tmp32 = ADD32(SHR32(Sxx,13), ADD32(tmp32, SHL32(tmp32,1)));
    /* Check for y in e (lower bound on RER) */
    {
       spx_float_t bound = PSEUDOFLOAT(Sey);
       bound = FLOAT_DIVU(FLOAT_MULT(bound, bound), PSEUDOFLOAT(ADD32(1,Syy)));
       if (FLOAT_GT(bound, PSEUDOFLOAT(See)))
          tmp32 = See;
       else if (tmp32 < FLOAT_EXTRACT32(bound))
          tmp32 = FLOAT_EXTRACT32(bound);
    }
    if (tmp32 > SHR32(See,1))
       tmp32 = SHR32(See,1);
    RER = FLOAT_EXTRACT16(FLOAT_SHL(FLOAT_DIV32(tmp32,See),15));
 #else
    RER = (.0001*Sxx + 3.*MULT16_32_Q15(st->leak_estimate,Syy)) / See;
    /* Check for y in e (lower bound on RER) */
    if (RER < Sey*Sey/(1+See*Syy))
       RER = Sey*Sey/(1+See*Syy);
    if (RER > .5)
       RER = .5;
 #endif
    /* We consider that the filter has had minimal adaptation if the following is true*/
    if (!st->adapted && st->sum_adapt > SHL32(EXTEND32(M),15) && MULT16_32_Q15(st->leak_estimate,Syy) > MULT16_32_Q15(QCONST16(.03f,15),Syy))
    {
       st->adapted = 1;
    }
    if (st->adapted)
    {
       /* Normal learning rate calculation once we're past the minimal adaptation phase */
       for (i=0;i<=st->frame_size;i++)
       {
          spx_word32_t r, e;
          /* Compute frequency-domain adaptation mask */
          r = MULT16_32_Q15(st->leak_estimate,SHL32(st->Yf[i],3));
          e = SHL32(st->Rf[i],3)+1;
 #ifdef FIXED_POINT
          if (r>SHR32(e,1))
             r = SHR32(e,1);
 #else
          if (r>.5*e)
             r = .5*e;
 #endif
          r = MULT16_32_Q15(QCONST16(.7,15),r) + MULT16_32_Q15(QCONST16(.3,15),(spx_word32_t)(MULT16_32_Q15(RER,e)));
          /*st->power_1[i] = adapt_rate*r/(e*(1+st->power[i]));*/
          st->power_1[i] = FLOAT_SHL(FLOAT_DIV32_FLOAT(r,FLOAT_MUL32U(e,st->power[i]+10)),WEIGHT_SHIFT+16);
       }
    } else {
       /* Temporary adaption rate if filter is not yet adapted enough */
       spx_word16_t adapt_rate=0;
       if (Sxx > SHR32(MULT16_16(N, 1000),6))
       {
          tmp32 = MULT16_32_Q15(QCONST16(.25f, 15), Sxx);
 #ifdef FIXED_POINT
          if (tmp32 > SHR32(See,2))
             tmp32 = SHR32(See,2);
 #else
          if (tmp32 > .25*See)
             tmp32 = .25*See;
 #endif
          adapt_rate = FLOAT_EXTRACT16(FLOAT_SHL(FLOAT_DIV32(tmp32, See),15));
       }
       for (i=0;i<=st->frame_size;i++)
          st->power_1[i] = FLOAT_SHL(FLOAT_DIV32(EXTEND32(adapt_rate),ADD32(st->power[i],10)),WEIGHT_SHIFT+1);
       /* How much have we adapted so far? */
       st->sum_adapt = ADD32(st->sum_adapt,adapt_rate);
    }
    /* Save residual echo so it can be used by the nonlinear processor */
    if (st->adapted)
    {
       /* If the filter is adapted, take the filtered echo */
       for (i=0;i<st->frame_size;i++)
          st->last_y[i] = st->last_y[st->frame_size+i];
       for (i=0;i<st->frame_size;i++)
          st->last_y[st->frame_size+i] = in[i]-out[i];
    } else {
       /* If filter isn't adapted yet, all we can do is take the far end signal directly */
       /* moved earlier: for (i=0;i<N;i++)
       st->last_y[i] = st->x[i];*/
    }
 }
References ABS32, ADD32, DIV32_16, EXTEND32, EXTRACT16, filter_dc_notch16(), FLOAT_ADD, FLOAT_DIV32, FLOAT_DIV32_FLOAT, FLOAT_DIVU, FLOAT_EXTRACT16, FLOAT_EXTRACT32, FLOAT_GT, FLOAT_LT, FLOAT_MUL32U, FLOAT_MULT, FLOAT_ONE, FLOAT_SHL, FLOAT_SQRT, FLOAT_SUB, FLOAT_ZERO, M, MAC16_32_Q15, MAX32, mdf_adjust_prop(), mdf_inner_prod(), MIN_LEAK, MULT16_16, MULT16_16_P15, MULT16_16_Q15, MULT16_32_Q15, NEG32, out, power_spectrum(), PSEUDOFLOAT, PSHR32, QCONST16, SHL16, SHL32, SHR32, spectral_mul_accum(), spectral_mul_accum16, speex_echo_state_reset(), speex_warning(), spx_fft(), spx_float_t, spx_ifft(), SUB16, SUB32, TWO_PATH, VAR1_SMOOTH, VAR1_UPDATE, VAR2_SMOOTH, VAR2_UPDATE, VAR_BACKTRACK, WEIGHT_SHIFT, and weighted_spectral_mul_conj().
Referenced by main(), speex_echo_cancel(), and speex_echo_capture().
speex_echo_capture()
void speex_echo_capture (SpeexEchoState * st, const spx_int16_t * rec, spx_int16_t * out)
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Perform echo cancellation using internal playback buffer, which is delayed by two frames to account for the delay introduced by most soundcards (but it could be off!)
Parameters
st Echo canceller state
rec Signal from the microphone (near end + far end echo)
out Returns near-end signal with echo removed
Definition at line 590 of file mdf.c.
 {
    int i;
    /*speex_warning_int("capture with fill level ", st->play_buf_pos/st->frame_size);*/
    st->play_buf_started = 1;
    if (st->play_buf_pos>=st->frame_size)
    {
       speex_echo_cancellation(st, rec, st->play_buf, out);
       st->play_buf_pos -= st->frame_size;
       for (i=0;i<st->play_buf_pos;i++)
          st->play_buf[i] = st->play_buf[i+st->frame_size];
    } else {
       speex_warning("No playback frame available (your application is buggy and/or got xruns)");
       if (st->play_buf_pos!=0)
       {
          speex_warning("internal playback buffer corruption?");
          st->play_buf_pos = 0;
       }
       for (i=0;i<st->frame_size;i++)
          out[i] = rec[i];
    }
 }
References out, speex_echo_cancellation(), and speex_warning().
speex_echo_ctl()
int speex_echo_ctl (SpeexEchoState * st, int request, void * ptr)
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Used like the ioctl function to control the echo canceller parameters.
Parameters
st Echo canceller state
request ioctl-type request (one of the SPEEX_ECHO_* macros)
ptr Data exchanged to-from function
Returns
0 if no error, -1 if request in unknown
Definition at line 1144 of file mdf.c.
 {
    switch(request)
    {
       case SPEEX_ECHO_GET_FRAME_SIZE:
          (*(int*)ptr) = st->frame_size;
          break;
       case SPEEX_ECHO_SET_SAMPLING_RATE:
          st->sampling_rate = (*(int*)ptr);
          st->spec_average = DIV32_16(SHL32(EXTEND32(st->frame_size), 15), st->sampling_rate);
 #ifdef FIXED_POINT
          st->beta0 = DIV32_16(SHL32(EXTEND32(st->frame_size), 16), st->sampling_rate);
          st->beta_max = DIV32_16(SHL32(EXTEND32(st->frame_size), 14), st->sampling_rate);
 #else
          st->beta0 = (2.0f*st->frame_size)/st->sampling_rate;
          st->beta_max = (.5f*st->frame_size)/st->sampling_rate;
 #endif
          if (st->sampling_rate<12000)
             st->notch_radius = QCONST16(.9, 15);
          else if (st->sampling_rate<24000)
             st->notch_radius = QCONST16(.982, 15);
          else
             st->notch_radius = QCONST16(.992, 15);
          break;
       case SPEEX_ECHO_GET_SAMPLING_RATE:
          (*(int*)ptr) = st->sampling_rate;
          break;
       default:
          speex_warning_int("Unknown speex_echo_ctl request: ", request);
          return -1;
    }
    return 0;
 }
References DIV32_16, EXTEND32, ptr(), QCONST16, SHL32, SPEEX_ECHO_GET_FRAME_SIZE, SPEEX_ECHO_GET_SAMPLING_RATE, SPEEX_ECHO_SET_SAMPLING_RATE, and speex_warning_int().
Referenced by main().
speex_echo_playback()
void speex_echo_playback (SpeexEchoState * st, const spx_int16_t * play)
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Let the echo canceller know that a frame was just queued to the soundcard.
Parameters
st Echo canceller state
play Signal played to the speaker (received from far end)
Definition at line 613 of file mdf.c.
 {
    /*speex_warning_int("playback with fill level ", st->play_buf_pos/st->frame_size);*/
    if (!st->play_buf_started)
    {
       speex_warning("discarded first playback frame");
       return;
    }
    if (st->play_buf_pos<=PLAYBACK_DELAY*st->frame_size)
    {
       int i;
       for (i=0;i<st->frame_size;i++)
          st->play_buf[st->play_buf_pos+i] = play[i];
       st->play_buf_pos += st->frame_size;
       if (st->play_buf_pos <= (PLAYBACK_DELAY-1)*st->frame_size)
       {
          speex_warning("Auto-filling the buffer (your application is buggy and/or got xruns)");
          for (i=0;i<st->frame_size;i++)
             st->play_buf[st->play_buf_pos+i] = play[i];
          st->play_buf_pos += st->frame_size;
       }
    } else {
       speex_warning("Had to discard a playback frame (your application is buggy and/or got xruns)");
    }
 }
References PLAYBACK_DELAY, and speex_warning().
speex_echo_state_destroy()
void speex_echo_state_destroy (SpeexEchoState * st)
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Destroys an echo canceller state.
Parameters
st Echo canceller state
Definition at line 548 of file mdf.c.
 {
    spx_fft_destroy(st->fft_table);
    speex_free(st->e);
    speex_free(st->x);
    speex_free(st->input);
    speex_free(st->y);
    speex_free(st->last_y);
    speex_free(st->Yf);
    speex_free(st->Rf);
    speex_free(st->Xf);
    speex_free(st->Yh);
    speex_free(st->Eh);
    speex_free(st->X);
    speex_free(st->Y);
    speex_free(st->E);
    speex_free(st->W);
 #ifdef TWO_PATH
    speex_free(st->foreground);
 #endif
    speex_free(st->PHI);
    speex_free(st->power);
    speex_free(st->power_1);
    speex_free(st->window);
    speex_free(st->prop);
    speex_free(st->wtmp);
 #ifdef FIXED_POINT
    speex_free(st->wtmp2);
 #endif
    speex_free(st->play_buf);
    speex_free(st);
 #ifdef DUMP_ECHO_CANCEL_DATA
    fclose(rFile);
    fclose(pFile);
    fclose(oFile);
    rFile = pFile = oFile = NULL;
 #endif
 }
References NULL, speex_free(), and spx_fft_destroy().
Referenced by main().
speex_echo_state_init()
SpeexEchoState* speex_echo_state_init (int frame_size, int filter_length)
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Creates a new echo canceller state.
Parameters
frame_size Number of samples to process at one time (should correspond to 10-20 ms)
filter_length Number of samples of echo to cancel (should generally correspond to 100-500 ms)
Returns
Newly-created echo canceller state
Definition at line 381 of file mdf.c.
 {
    int i,N,M;
    SpeexEchoState *st = (SpeexEchoState *)speex_alloc(sizeof(SpeexEchoState));
 #ifdef DUMP_ECHO_CANCEL_DATA
    if (rFile || pFile || oFile)
       speex_fatal("Opening dump files twice");
    rFile = fopen("aec_rec.sw", "wb");
    pFile = fopen("aec_play.sw", "wb");
    oFile = fopen("aec_out.sw", "wb");
 #endif
    st->frame_size = frame_size;
    st->window_size = 2*frame_size;
    N = st->window_size;
    M = st->M = (filter_length+st->frame_size-1)/frame_size;
    st->cancel_count=0;
    st->sum_adapt = 0;
    st->saturated = 0;
    st->screwed_up = 0;
    /* This is the default sampling rate */
    st->sampling_rate = 8000;
    st->spec_average = DIV32_16(SHL32(EXTEND32(st->frame_size), 15), st->sampling_rate);
 #ifdef FIXED_POINT
    st->beta0 = DIV32_16(SHL32(EXTEND32(st->frame_size), 16), st->sampling_rate);
    st->beta_max = DIV32_16(SHL32(EXTEND32(st->frame_size), 14), st->sampling_rate);
 #else
    st->beta0 = (2.0f*st->frame_size)/st->sampling_rate;
    st->beta_max = (.5f*st->frame_size)/st->sampling_rate;
 #endif
    st->leak_estimate = 0;
    st->fft_table = spx_fft_init(N);
    st->e = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
    st->x = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
    st->input = (spx_word16_t*)speex_alloc(st->frame_size*sizeof(spx_word16_t));
    st->y = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
    st->last_y = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
    st->Yf = (spx_word32_t*)speex_alloc((st->frame_size+1)*sizeof(spx_word32_t));
    st->Rf = (spx_word32_t*)speex_alloc((st->frame_size+1)*sizeof(spx_word32_t));
    st->Xf = (spx_word32_t*)speex_alloc((st->frame_size+1)*sizeof(spx_word32_t));
    st->Yh = (spx_word32_t*)speex_alloc((st->frame_size+1)*sizeof(spx_word32_t));
    st->Eh = (spx_word32_t*)speex_alloc((st->frame_size+1)*sizeof(spx_word32_t));
    st->X = (spx_word16_t*)speex_alloc((M+1)*N*sizeof(spx_word16_t));
    st->Y = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
    st->E = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
    st->W = (spx_word32_t*)speex_alloc(M*N*sizeof(spx_word32_t));
 #ifdef TWO_PATH
    st->foreground = (spx_word16_t*)speex_alloc(M*N*sizeof(spx_word16_t));
 #endif
    st->PHI = (spx_word32_t*)speex_alloc(N*sizeof(spx_word32_t));
    st->power = (spx_word32_t*)speex_alloc((frame_size+1)*sizeof(spx_word32_t));
    st->power_1 = (spx_float_t*)speex_alloc((frame_size+1)*sizeof(spx_float_t));
    st->window = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
    st->prop = (spx_word16_t*)speex_alloc(M*sizeof(spx_word16_t));
    st->wtmp = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
 #ifdef FIXED_POINT
    st->wtmp2 = (spx_word16_t*)speex_alloc(N*sizeof(spx_word16_t));
    for (i=0;i<N>>1;i++)
    {
       st->window[i] = (16383-SHL16(spx_cos(DIV32_16(MULT16_16(25736,i<<1),N)),1));
       st->window[N-i-1] = st->window[i];
    }
 #else
    for (i=0;i<N;i++)
       st->window[i] = .5-.5*cos(2*M_PI*i/N);
 #endif
    for (i=0;i<=st->frame_size;i++)
       st->power_1[i] = FLOAT_ONE;
    for (i=0;i<N*M;i++)
       st->W[i] = 0;
    {
       spx_word32_t sum = 0;
       /* Ratio of ~10 between adaptation rate of first and last block */
       spx_word16_t decay = SHR32(spx_exp(NEG16(DIV32_16(QCONST16(2.4,11),M))),1);
       st->prop[0] = QCONST16(.7, 15);
       sum = EXTEND32(st->prop[0]);
       for (i=1;i<M;i++)
       {
          st->prop[i] = MULT16_16_Q15(st->prop[i-1], decay);
          sum = ADD32(sum, EXTEND32(st->prop[i]));
       }
       for (i=M-1;i>=0;i--)
       {
          st->prop[i] = DIV32(MULT16_16(QCONST16(.8,15), st->prop[i]),sum);
       }
    }
    st->memX=st->memD=st->memE=0;
    st->preemph = QCONST16(.9,15);
    if (st->sampling_rate<12000)
       st->notch_radius = QCONST16(.9, 15);
    else if (st->sampling_rate<24000)
       st->notch_radius = QCONST16(.982, 15);
    else
       st->notch_radius = QCONST16(.992, 15);
    st->notch_mem[0] = st->notch_mem[1] = 0;
    st->adapted = 0;
    st->Pey = st->Pyy = FLOAT_ONE;
 #ifdef TWO_PATH
    st->Davg1 = st->Davg2 = 0;
    st->Dvar1 = st->Dvar2 = FLOAT_ZERO;
 #endif
    st->play_buf = (spx_int16_t*)speex_alloc((PLAYBACK_DELAY+1)*st->frame_size*sizeof(spx_int16_t));
    st->play_buf_pos = PLAYBACK_DELAY*st->frame_size;
    st->play_buf_started = 0;
    return st;
 }
References ADD32, DIV32, DIV32_16, EXTEND32, FLOAT_ONE, M, M_PI, MULT16_16, MULT16_16_Q15, NEG16, QCONST16, SHL16, SHL32, SHR32, speex_alloc(), speex_fatal, spx_cos(), spx_exp, spx_fft_init(), and spx_float_t.
Referenced by main().
speex_echo_state_reset()
void speex_echo_state_reset (SpeexEchoState * st)
#include <Source/Engine/libspeex/include/speex/speex_echo.h>
Reset the echo canceller to its original state.
Parameters
st Echo canceller state
Reset the echo canceller to its original state.
Definition at line 498 of file mdf.c.
 {
    int i, M, N;
    st->cancel_count=0;
    st->screwed_up = 0;
    N = st->window_size;
    M = st->M;
    for (i=0;i<N*M;i++)
       st->W[i] = 0;
 #ifdef TWO_PATH
    for (i=0;i<N*M;i++)
       st->foreground[i] = 0;
 #endif
    for (i=0;i<N*(M+1);i++)
       st->X[i] = 0;
    for (i=0;i<=st->frame_size;i++)
    {
       st->power[i] = 0;
       st->power_1[i] = FLOAT_ONE;
       st->Eh[i] = 0;
       st->Yh[i] = 0;
    }
    for (i=0;i<st->frame_size;i++)
    {
       st->last_y[i] = 0;
    }
    for (i=0;i<N;i++)
    {
       st->E[i] = 0;
       st->x[i] = 0;
    }
    st->notch_mem[0] = st->notch_mem[1] = 0;
    st->memX=st->memD=st->memE=0;
    st->saturated = 0;
    st->adapted = 0;
    st->sum_adapt = 0;
    st->Pey = st->Pyy = FLOAT_ONE;
 #ifdef TWO_PATH
    st->Davg1 = st->Davg2 = 0;
    st->Dvar1 = st->Dvar2 = FLOAT_ZERO;
 #endif
    for (i=0;i<3*st->frame_size;i++)
       st->play_buf[i] = 0;
    st->play_buf_pos = PLAYBACK_DELAY*st->frame_size;
    st->play_buf_started = 0;
 }
References FLOAT_ONE, FLOAT_ZERO, M, PLAYBACK_DELAY, and TWO_PATH.
Referenced by speex_echo_cancellation().