ZEQ2-Lite: Game/Game/g_mem.c File Reference
g_mem.c File Reference
#include "g_local.h"
Macros
#define POOLSIZE (256 * 1024)
Functions
void * G_Alloc (int size)
void G_InitMemory (void)
void Svcmd_GameMem_f (void)
Variables
static int allocPoint
static char memoryPool [POOLSIZE]
Macro Definition Documentation
POOLSIZE
#define POOLSIZE (256 * 1024)
Definition at line 31 of file g_mem.c.
Function Documentation
G_Alloc()
void* G_Alloc (int size)
Definition at line 36 of file g_mem.c.
{
     char    *p;
     if ( g_debugAlloc.integer ) {
         G_Printf( "G_Alloc of %i bytes (%i left)\n", size, POOLSIZE - allocPoint - ( ( size + 31 ) & ~31 ) );
     }
     if ( allocPoint + size > POOLSIZE ) {
       G_Error( "G_Alloc: failed on allocation of %i bytes\n", size );
         return NULL;
     }
     p = &memoryPool[allocPoint];
     allocPoint += ( size + 31 ) & ~31;
     return p;
 }
References allocPoint, g_debugAlloc, G_Error(), G_Printf(), vmCvar_t::integer, memoryPool, NULL, and POOLSIZE.
Referenced by G_NewString().
G_InitMemory()
void G_InitMemory (void)
Definition at line 55 of file g_mem.c.
{
     allocPoint = 0;
 }
References allocPoint.
Referenced by G_InitGame().
Svcmd_GameMem_f()
void Svcmd_GameMem_f (void)
Definition at line 59 of file g_mem.c.
{
     G_Printf( "Game memory status: %i out of %i bytes allocated\n", allocPoint, POOLSIZE );
 }
References allocPoint, G_Printf(), and POOLSIZE.
Referenced by ConsoleCommand().
Variable Documentation
allocPoint
int allocPoint static
Definition at line 34 of file g_mem.c.
Referenced by G_Alloc(), G_InitMemory(), and Svcmd_GameMem_f().
memoryPool
char memoryPool[POOLSIZE] static
Definition at line 33 of file g_mem.c.
Referenced by G_Alloc().