ZEQ2-Lite: Source/Engine/tools/lcc/src/symbolic.c File Reference
symbolic.c File Reference
#include <time.h>
#include <ctype.h>
#include "c.h"
Macros
#define ANCHOR(attr, code) do { const char *yytag="a"; if (html) { printf("<a " #attr "=\""); code; print("\">"); }
#define BEGIN(tag) do { const char *yytag=yyBEGIN(#tag);
#define END yyEND(yytag); } while (0)
#define I(f) s_##f
#define ITEM BEGIN(li)
#define NEWLINE print(html ? "<br>\n" : "\n")
#define START BEGIN(LI)
#define xx(field, code) ITEM; if (!html) print(" "); print(#field "="); code; END
#define xx(field, code) ITEM; print(#field "="); code; END
Functions
static void I() address (Symbol q, Symbol p, long n)
static void I() blockbeg (Env *e)
static void I() blockend (Env *e)
static void I() defaddress (Symbol p)
static void I() defconst (int suffix, int size, Value v)
static void I() defstring (int len, char *s)
static void I() defsymbol (Symbol p)
static void I() emit (Node p)
static void emitCoord (Coordinate src)
static void emitString (int len, const char *s)
static void emitSymbol (Symbol p)
static void emitSymRef (Symbol p)
static void I() export (Symbol p)
static void I() function (Symbol f, Symbol caller[], Symbol callee[], int ncalls)
static Node I() gen (Node p)
static void I() global (Symbol p)
static void I() import (Symbol p)
static void I() local (Symbol p)
static void I() progbeg (int argc, char *argv[])
static void I() progend (void)
static void I() segment (int s)
static void I() space (int n)
static void I() stabblock (int brace, int lev, Symbol *p)
static void I() stabend (Coordinate *cp, Symbol p, Coordinate **cpp, Symbol *sp, Symbol *stab)
static void I() stabfend (Symbol p, int lineno)
static void I() stabinit (char *file, int argc, char *argv[])
static void I() stabline (Coordinate *cp)
static void I() stabsym (Symbol p)
static void I() stabtype (Symbol p)
static int visit (Node p, int n)
static const char * yyBEGIN (const char *tag)
static void yyEND (const char *tag)
Variables
static int html = 0
static int maxoff
static int off
Interface symbolic64IR
Interface symbolicIR
static Node * tail
static int uid = 0
static int verbose = 0
Macro Definition Documentation
ANCHOR
#define ANCHOR (attr, code) do { const char *yytag="a"; if (html) { printf("<a " #attr "=\""); code; print("\">"); }
Definition at line 27 of file symbolic.c.
BEGIN
#define BEGIN (tag) do { const char *yytag=yyBEGIN(#tag);
Definition at line 23 of file symbolic.c.
END
#define END yyEND(yytag); } while (0)
Definition at line 24 of file symbolic.c.
I
#define I (f) s_##f
Definition at line 5 of file symbolic.c.
ITEM
#define ITEM BEGIN(li)
Definition at line 25 of file symbolic.c.
NEWLINE
#define NEWLINE print(html ? "<br>\n" : "\n")
Definition at line 28 of file symbolic.c.
START
#define START BEGIN(LI)
Definition at line 26 of file symbolic.c.
xx [1/2]
#define xx (field, code) ITEM; if (!html) print(" "); print(#field "="); code; END
xx [2/2]
#define xx (field, code) ITEM; print(#field "="); code; END
Function Documentation
address()
static void I() address (Symbol q, Symbol p, long n) static
Definition at line 90 of file symbolic.c.
{
     q->name = stringf("%s%s%D", p->name, n > 0 ? "+" : "", n);
     (*IR->defsymbol)(q);
     START; print("address "); emitSymbol(q); END;
 }
References emitSymbol(), END, IR, print(), START, and stringf().
blockbeg()
static void I() blockbeg (Env * e) static
Definition at line 97 of file symbolic.c.
{
     e->offset = off;
     START; print("blockbeg off=%d", off); END;
 }
References END, off, print(), and START.
blockend()
static void I() blockend (Env * e) static
Definition at line 103 of file symbolic.c.
{
     if (off > maxoff)
         maxoff = off;
     START; print("blockend off=%d", off); END;
     off = e->offset;
 }
References END, maxoff, off, print(), and START.
defaddress()
static void I() defaddress (Symbol p) static
Definition at line 111 of file symbolic.c.
{
     START; print("defaddress "); emitSymRef(p); END;
 }
References emitSymRef(), END, print(), and START.
defconst()
static void I() defconst (int suffix, int size, Value v) static
Definition at line 116 of file symbolic.c.
{
     START;
     print("defconst ");
     switch (suffix) {
     case I:
         print("int.%d ", size);
         BEGIN(code);
         if (size > sizeof (int))
             print("%D", v.i);
         else
             print("%d", (int)v.i);
         END;
         break;
     case U:
         print("unsigned.%d ", size);
         BEGIN(code);
         if (size > sizeof (unsigned))
             print("%U", v.u);
         else
             print("%u", (unsigned)v.u);
         END;
         break;
     case P: print("void*.%d ", size); BEGIN(code); print("%p", v.p); END; break;
     case F: print("float.%d ", size); BEGIN(code); print("%g", (double)v.d); END; break;
     default: assert(0);
     }
     END;
 }
References BEGIN, END, F, I, P, print(), START, suffix(), and U.
defstring()
static void I() defstring (int len, char * s) static
Definition at line 146 of file symbolic.c.
{
     START; print("defstring ");
     BEGIN(code); print("\""); emitString(len, s); print("\""); END;
     END;
 }
References BEGIN, emitString(), END, print(), and START.
defsymbol()
static void I() defsymbol (Symbol p) static
Definition at line 153 of file symbolic.c.
{
     if (p->x.name == NULL)
         p->x.name = stringd(++uid);
 }
References NULL, stringd(), and uid.
emit()
static void I() emit (Node p) static
Definition at line 159 of file symbolic.c.
{
     ITEM;
     if (!html)
         print(" ");
     for (; p; p = p->x.next) {
         if (p->op == LABEL+V) {
             assert(p->syms[0]);
             ANCHOR(name,print("%s", p->syms[0]->x.name));
             BEGIN(code); print("%s", p->syms[0]->name); END;
             END;
             print(":");
         } else {
             int i;
             if (p->x.listed) {
                 BEGIN(strong); print("%d", p->x.inst); END; print("'");
                 print(" %s", opname(p->op));
             } else
                 print("%d. %s", p->x.inst, opname(p->op));
             if (p->count > 1)
                 print(" count=%d", p->count);
             for (i = 0; i < NELEMS(p->kids) && p->kids[i]; i++)
                 print(" #%d", p->kids[i]->x.inst);
             if (generic(p->op) == CALL && p->syms[0] && p->syms[0]->type)
                 print(" {%t}", p->syms[0]->type);
             else
                 for (i = 0; i < NELEMS(p->syms) && p->syms[i]; i++) {
                     print(" ");
                     if (p->syms[i]->scope == CONSTANTS)
                         print(p->syms[i]->name);
                     else
                         emitSymRef(p->syms[i]);
                 }
         }
         NEWLINE;
     }
     END;
 }
References ANCHOR, BEGIN, CALL, CONSTANTS, emitSymRef(), END, html, ITEM, NELEMS, NEWLINE, opname(), print(), and V.
emitCoord()
static void emitCoord (Coordinate src) static
Definition at line 30 of file symbolic.c.
{
     if (src.file && *src.file) {
         ANCHOR(href,print("%s", src.file)); print("%s", src.file); END;
         print(":");
     }
     print("%d.%d", src.y, src.x);
 }
References ANCHOR, END, and print().
Referenced by emitSymbol().
emitString()
static void emitString (int len, const char * s) static
Definition at line 38 of file symbolic.c.
{
     for ( ; len-- > 0; s++)
         if (*s == '&' && html)
             print("&amp;");
         else if (*s == '<' && html)
             print("&lt;");
         else if (*s == '>' && html)
             print("&lt;");
         else if (*s == '"' || *s == '\\')
             print("\\%c", *s);
         else if (*s >= ' ' && *s < 0177)
             print("%c", *s);
         else
             print("\\%d%d%d", (*s>>6)&3, (*s>>3)&7, *s&7);
 }
References html, and print().
Referenced by defstring(), and progbeg().
emitSymbol()
static void emitSymbol (Symbol p) static
Definition at line 59 of file symbolic.c.
{
     (*IR->defsymbol)(p);
     ANCHOR(name,print("%s", p->x.name)); BEGIN(code); print("%s", p->name); END; END;
     BEGIN(ul);
 #define xx(field,code) ITEM; if (!html) print(" "); print(#field "="); code; END
     if (verbose && (src.y || src.x))
         xx(src,emitCoord(p->src));
     xx(type,print("%t", p->type));
     xx(sclass,print("%k", p->sclass));
     switch (p->scope) {
     case CONSTANTS: xx(scope,print("CONSTANTS")); break;
     case LABELS:    xx(scope,print("LABELS"));    break;
     case GLOBAL:    xx(scope,print("GLOBAL"));    break;
     case PARAM:     xx(scope,print("PARAM"));     break;
     case LOCAL:     xx(scope,print("LOCAL"));     break;
     default:
         if (p->scope > LOCAL)
             xx(scope,print("LOCAL+%d", p->scope-LOCAL));
         else
             xx(scope,print("%d", p->scope));
     }
     if (p->scope >= PARAM && p->sclass != STATIC)
         xx(offset,print("%d", p->x.offset));
     xx(ref,print("%f", p->ref));
     if (p->temporary && p->u.t.cse)
         xx(u.t.cse,print("%p", p->u.t.cse));
     END;
 #undef xx
 }
References ANCHOR, BEGIN, CONSTANTS, emitCoord(), END, GLOBAL, IR, LABELS, LOCAL, PARAM, print(), verbose, and xx.
Referenced by address(), function(), global(), and local().
emitSymRef()
static void emitSymRef (Symbol p) static
Definition at line 54 of file symbolic.c.
{
     (*IR->defsymbol)(p);
     ANCHOR(href,print("#%s", p->x.name)); BEGIN(code); print("%s", p->name); END; END;
 }
References ANCHOR, BEGIN, END, IR, and print().
Referenced by defaddress(), emit(), export(), import(), and stabend().
export()
static void I() export (Symbol p) static
Definition at line 198 of file symbolic.c.
{
     START; print("export "); emitSymRef(p); END;
 }
References emitSymRef(), END, print(), and START.
function()
static void I() function (Symbol f, Symbol caller[], Symbol callee[], int ncalls) static
Definition at line 203 of file symbolic.c.
{
     int i;
     (*IR->defsymbol)(f);
     off = 0;
     for (i = 0; caller[i] && callee[i]; i++) {
         off = roundup(off, caller[i]->type->align);
         caller[i]->x.offset = callee[i]->x.offset = off;
         off += caller[i]->type->size;
     }
     if (!html) {
         print("function ");
         emitSymbol(f);
         print(" ncalls=%d\n", ncalls);
         for (i = 0; caller[i]; i++)
             START; print("caller "); emitSymbol(caller[i]); END;
         for (i = 0; callee[i]; i++)
             START; print("callee "); emitSymbol(callee[i]); END;
     } else {
         START;
         print("function");
         BEGIN(UL);
 #define xx(field,code) ITEM; print(#field "="); code; END
         xx(f,emitSymbol(f));
         xx(ncalls,print("%d", ncalls));
         if (caller[0]) {
             ITEM; print("caller"); BEGIN(OL);
             for (i = 0; caller[i]; i++)
                 ITEM; emitSymbol(caller[i]); END;
             END; END;
             ITEM; print("callee"); BEGIN(OL);
             for (i = 0; callee[i]; i++)
                 ITEM; emitSymbol(callee[i]); END;
             END; END;
         } else {
             xx(caller,BEGIN(em); print("empty"); END);
             xx(callee,BEGIN(em); print("empty"); END);
         }
         END;
         END;
     }
     maxoff = off = 0;
     gencode(caller, callee);
     if (html)
         START; print("emitcode"); BEGIN(ul); emitcode(); END; END;
     else
         emitcode();
     START; print("maxoff=%d", maxoff); END;
 #undef xx
 }
References Type::align, BEGIN, emitcode(), emitSymbol(), END, gencode(), html, IR, ITEM, maxoff, off, print(), roundup, START, and xx.
gen()
static Node I() gen (Node p) static
Definition at line 267 of file symbolic.c.
{
     int n;
     Node nodelist;
     tail = &nodelist;
     for (n = 0; p; p = p->link) {
         switch (generic(p->op)) {   /* check for valid forest */
         case CALL:
             assert(IR->wants_dag || p->count == 0);
             break;
         case ARG:
         case ASGN: case JUMP: case LABEL: case RET:
         case EQ: case GE: case GT: case LE: case LT: case NE:
             assert(p->count == 0);
             break;
         case INDIR:
             assert(IR->wants_dag && p->count > 0);
             break;
         default:
             assert(0);
         }
         check(p);
         p->x.listed = 1;
         n = visit(p, n);
     }
     *tail = 0;
     return nodelist;
 }
References ASGN, CALL, check(), EQ, GT, IR, LT, tail, and visit().
global()
static void I() global (Symbol p) static
Definition at line 297 of file symbolic.c.
{
     START; print("global "); emitSymbol(p); END;
 }
References emitSymbol(), END, print(), and START.
import()
static void I() import (Symbol p) static
Definition at line 302 of file symbolic.c.
{
     START; print("import "); emitSymRef(p); END;
 }
References emitSymRef(), END, print(), and START.
local()
static void I() local (Symbol p) static
Definition at line 307 of file symbolic.c.
{
     if (p->temporary)
         p->name = stringf("t%s", p->name);
     (*IR->defsymbol)(p);
     off = roundup(off, p->type->align);
     p->x.offset = off;
     off += p->type->size;
     START; print(p->temporary ? "temporary " : "local "); emitSymbol(p); END;
 }
References emitSymbol(), END, IR, off, print(), roundup, START, and stringf().
progbeg()
static void I() progbeg (int argc, char * argv[]) static
Definition at line 318 of file symbolic.c.
{
     int i;
     for (i = 1; i < argc; i++)
         if (strcmp(argv[i], "-v") == 0)
             verbose++;
         else if (strcmp(argv[i], "-html") == 0)
             html++;
     if (html) {
         print("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n");
         print("<html>");
         BEGIN(head);
         if (firstfile && *firstfile)
             BEGIN(title); emitString(strlen(firstfile), firstfile); END;
         print("<link rev=made href=\"mailto:drh@microsoft.com\">\n");
         END;
         print("<body>\n");
         if (firstfile && *firstfile)
             BEGIN(h1); emitString(strlen(firstfile), firstfile); END;
         BEGIN(P); BEGIN(em);
         print("Links lead from uses of identifiers and labels to their definitions.");
         END; END;
         print("<ul>\n");
         START;
         print("progbeg");
         BEGIN(ol);
         for (i = 1; i < argc; i++) {
             ITEM;
             BEGIN(code); print("\""); emitString(strlen(argv[i]), argv[i]); print("\""); END;
             END;
         }
         END;
         END;
     }
 }
References BEGIN, emitString(), END, firstfile, head, html, ITEM, P, print(), START, and verbose.
progend()
static void I() progend (void) static
Definition at line 355 of file symbolic.c.
{
     START; print("progend"); END;
     if (html) {
         time_t t;
         print("</ul>\n");
         time(&t);
         print("<hr><address>%s</address>\n", ctime(&t));
         print("</body></html>\n");
     }
 }
References END, html, print(), and START.
segment()
static void I() segment (int s) static
Definition at line 367 of file symbolic.c.
{
     START; print("segment %s", &"text\0bss\0.data\0lit\0.sym\0."[5*s-5]); END;
 }
References END, print(), and START.
space()
static void I() space (int n) static
Definition at line 372 of file symbolic.c.
{
     START; print("space %d", n); END;
 }
References END, print(), and START.
stabblock()
static void I() stabblock (int brace, int lev, Symbol * p) static
Definition at line 376 of file symbolic.c.
 {}
stabend()
static void I() stabend (Coordinate * cp, Symbol p, Coordinate ** cpp, Symbol * sp, Symbol * stab) static
Definition at line 379 of file symbolic.c.
{
     int i;
     if (p)
         emitSymRef(p);
     print("\n");
     if (cpp && sp)
         for (i = 0; cpp[i] && sp[i]; i++) {
             print("%w.%d: ", cpp[i], cpp[i]->x);
             emitSymRef(sp[i]);
             print("\n");
         }
 }
References cpp, emitSymRef(), print(), and sp.
stabfend()
static void I() stabfend (Symbol p, int lineno) static
Definition at line 393 of file symbolic.c.
 {}
stabinit()
static void I() stabinit (char * file, int argc, char * argv[]) static
Definition at line 394 of file symbolic.c.
 {}
stabline()
static void I() stabline (Coordinate * cp) static
Definition at line 397 of file symbolic.c.
{
     if (cp->file)
         print("%s:", cp->file);
     print("%d.%d:\n", cp->y, cp->x);
 }
References cp, and print().
stabsym()
static void I() stabsym (Symbol p) static
Definition at line 403 of file symbolic.c.
 {}
stabtype()
static void I() stabtype (Symbol p) static
Definition at line 404 of file symbolic.c.
 {}
visit()
static int visit (Node p, int n) static
Definition at line 255 of file symbolic.c.
{
     if (p && p->x.inst == 0) {
         p->x.inst = ++n;
         n = visit(p->kids[0], n);
         n = visit(p->kids[1], n);
         *tail = p;
         tail = &p->x.next;
     }
     return n;
 }
References tail.
Referenced by gen().
yyBEGIN()
static const char* yyBEGIN (const char * tag) static
Definition at line 10 of file symbolic.c.
{
     if (html)
         print("<%s>", tag);
     return tag;
 }
References html, and print().
yyEND()
static void yyEND (const char * tag) static
Definition at line 16 of file symbolic.c.
{
     if (html)
         print("</%s>", tag);
     if (isupper(*tag))
         print("\n");
 }
References html, and print().
Variable Documentation
html
int html = 0 static
Definition at line 8 of file symbolic.c.
Referenced by emit(), emitString(), function(), progbeg(), progend(), yyBEGIN(), and yyEND().
maxoff
int maxoff static
Definition at line 8 of file symbolic.c.
Referenced by blockend(), and function().
off
int off static
Definition at line 8 of file symbolic.c.
Referenced by blockbeg(), blockend(), emit_condjump(), emit_jmp(), fields(), function(), local(), RB_CalcBulgeVertexes(), RB_CalcDeformVertexes(), sparc_compute_code(), and sparc_push_data().
symbolic64IR
Interface symbolic64IR
Definition at line 451 of file symbolic.c.
symbolicIR
Interface symbolicIR
Definition at line 406 of file symbolic.c.
tail
Node* tail static
Definition at line 7 of file symbolic.c.
Referenced by gen(), and visit().
uid
int uid = 0 static
Definition at line 8 of file symbolic.c.
Referenced by defsymbol().
verbose
int verbose = 0 static
Definition at line 8 of file symbolic.c.
Referenced by emitSymbol(), and progbeg().