ZEQ2-Lite: __gnu_profile::__trace_vector_to_list Class Reference
__gnu_profile::__trace_vector_to_list Class Reference
Vector-to-list instrumentation producer.
#include <profiler_vector_to_list.h>
Public Member Functions
__trace_vector_to_list ()
~__trace_vector_to_list ()
void __add_object (__object_t object, __vector2list_info __info)
void __collect_warnings (__warning_vector_t &__warnings)
void __destruct (const void *__obj)
__vector2list_info * __find (const void *__obj)
__vector2list_info * __get_object_info (__object_t __object)
void __insert (__object_t __obj, __stack_t __stack)
void __invalid_operator (const void *__obj)
float __list_cost (std::size_t __shift, std::size_t __iterate, std::size_t __resize)
void __opr_find (const void *__obj, std::size_t __size)
void __opr_insert (const void *__obj, std::size_t __pos, std::size_t __num)
void __opr_iterate (const void *__obj, std::size_t __num)
void __resize (const void *__obj, std::size_t __from, std::size_t __to)
void __retire_object (__object_t __object)
float __vector_cost (std::size_t __shift, std::size_t __iterate, std::size_t __resize)
void __write (FILE *__f)
Protected Attributes
const char * __id
Private Types
typedef _GLIBCXX_IMPL_UNORDERED_MAP< __object_t, __vector2list_info > __object_table_t
typedef _GLIBCXX_IMPL_UNORDERED_MAP< __stack_t, __vector2list_stack_info, __stack_hash, __stack_hash > __stack_table_t
Private Attributes
__object_table_t __object_table
__gnu_cxx::__mutex __object_table_lock
__stack_table_t __stack_table
std::size_t __stack_table_byte_size
__gnu_cxx::__mutex __stack_table_lock
Detailed Description
Vector-to-list instrumentation producer.
Definition at line 165 of file profiler_vector_to_list.h.
Member Typedef Documentation
__object_table_t
typedef _GLIBCXX_IMPL_UNORDERED_MAP<__object_t, __vector2list_info > __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__object_table_t private inherited
Definition at line 211 of file profiler_trace.h.
__stack_table_t
typedef _GLIBCXX_IMPL_UNORDERED_MAP<__stack_t, __vector2list_stack_info , __stack_hash, __stack_hash> __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__stack_table_t private inherited
Definition at line 214 of file profiler_trace.h.
Constructor & Destructor Documentation
__trace_vector_to_list()
__gnu_profile::__trace_vector_to_list::__trace_vector_to_list () inline
Definition at line 169 of file profiler_vector_to_list.h.
     : __trace_base<__vector2list_info, __vector2list_stack_info>()
     { __id = "vector-to-list"; }
References __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__id.
~__trace_vector_to_list()
__gnu_profile::__trace_vector_to_list::~__trace_vector_to_list () inline
Definition at line 173 of file profiler_vector_to_list.h.
 { }
Member Function Documentation
__add_object()
void __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__add_object (__object_t object, __vector2list_info __info) inherited
Definition at line 238 of file profiler_trace.h.
     {
       if (__max_mem() == 0
       || __object_table.size() * sizeof(__object_info) <= __max_mem())
     {
       this->__object_table_lock.lock();
       __object_table.insert(typename __object_table_t::
                 value_type(__object, __info));
       this->__object_table_lock.unlock();
     }
     }
__collect_warnings()
void __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__collect_warnings (__warning_vector_t & __warnings) inherited
Definition at line 226 of file profiler_trace.h.
     {
       for (typename __stack_table_t::iterator __it
          = __stack_table.begin(); __it != __stack_table.end(); ++__it)
     __warnings.push_back(__warning_data((*__it).second.__magnitude(),
                         (*__it).first, __id,
                         (*__it).second.__advice()));
     }
__destruct()
void __gnu_profile::__trace_vector_to_list::__destruct (const void * __obj) inline
Definition at line 182 of file profiler_vector_to_list.h.
     {
       if (!__is_on())
     return;
       __vector2list_info* __res = __get_object_info(__obj);
       if (!__res)
     return;
       float __vc = __vector_cost(__res->__shift_count(), __res->__iterate(),
                  __res->__resize());
       float __lc = __list_cost(__res->__shift_count(), __res->__iterate(),
                    __res->__resize());
       __res->__set_vector_cost(__vc);
       __res->__set_list_cost(__lc);
       __retire_object(__obj);
     }
References __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__get_object_info(), __gnu_profile::__is_on(), __gnu_profile::__vector2list_info::__iterate(), __list_cost(), __gnu_profile::__vector2list_info::__resize(), __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__retire_object(), __gnu_profile::__vector2list_info::__set_list_cost(), __gnu_profile::__vector2list_info::__set_vector_cost(), __gnu_profile::__vector2list_info::__shift_count(), and __vector_cost().
__find()
__vector2list_info* __gnu_profile::__trace_vector_to_list::__find (const void * __obj)
__get_object_info()
__vector2list_info * __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__get_object_info (__object_t __object) inherited
Definition at line 253 of file profiler_trace.h.
     {
       // XXX: Revisit this to see if we can decrease mutex spans.
       // Without this mutex, the object table could be rehashed during an
       // insertion on another thread, which could result in a segfault.
       this->__object_table_lock.lock();
       typename __object_table_t::iterator __object_it
     =  __object_table.find(__object);
       if (__object_it == __object_table.end())
     {
       this->__object_table_lock.unlock();
       return 0;
     }
       else
     {
       this->__object_table_lock.unlock();
       return &__object_it->second;
     }
     }
__insert()
void __gnu_profile::__trace_vector_to_list::__insert (__object_t __obj, __stack_t __stack) inline
Definition at line 177 of file profiler_vector_to_list.h.
     { __add_object(__obj, __vector2list_info(__stack)); }
References __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__add_object().
__invalid_operator()
void __gnu_profile::__trace_vector_to_list::__invalid_operator (const void * __obj) inline
Definition at line 223 of file profiler_vector_to_list.h.
     {
       __vector2list_info* __res = __get_object_info(__obj);
       if (__res)
     __res->__set_invalid();
     }
References __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__get_object_info(), and __gnu_profile::__vector2list_info::__set_invalid().
__list_cost()
float __gnu_profile::__trace_vector_to_list::__list_cost (std::size_t __shift, std::size_t __iterate, std::size_t __resize) inline
Definition at line 251 of file profiler_vector_to_list.h.
     {
       return (__shift
           * _GLIBCXX_PROFILE_DATA(__list_shift_cost_factor).__value
           + __iterate
           * _GLIBCXX_PROFILE_DATA(__list_iterate_cost_factor).__value
           + __resize
           * _GLIBCXX_PROFILE_DATA(__list_resize_cost_factor).__value);
     }
References __resize(), and _GLIBCXX_PROFILE_DATA.
Referenced by __destruct().
__opr_find()
void __gnu_profile::__trace_vector_to_list::__opr_find (const void * __obj, std::size_t __size) inline
Definition at line 263 of file profiler_vector_to_list.h.
     {
       __vector2list_info* __res = __get_object_info(__obj);
       if (__res)
     __res->__opr_find(__size);
     }
References __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__get_object_info(), __gnu_profile::__vector2list_info::__opr_find(), and __gnu_profile::__size().
__opr_insert()
void __gnu_profile::__trace_vector_to_list::__opr_insert (const void * __obj, std::size_t __pos, std::size_t __num) inline
Definition at line 207 of file profiler_vector_to_list.h.
     {
       __vector2list_info* __res = __get_object_info(__obj);
       if (__res)
     __res->__opr_insert(__pos, __num);
     }
References __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__get_object_info(), and __gnu_profile::__vector2list_info::__opr_insert().
__opr_iterate()
void __gnu_profile::__trace_vector_to_list::__opr_iterate (const void * __obj, std::size_t __num) inline
Definition at line 215 of file profiler_vector_to_list.h.
     {
       __vector2list_info* __res = __get_object_info(__obj);
       if (__res)
     __res->__opr_iterate(__num);
     }
References __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__get_object_info(), and __gnu_profile::__vector2list_info::__opr_iterate().
__resize()
void __gnu_profile::__trace_vector_to_list::__resize (const void * __obj, std::size_t __from, std::size_t __to) inline
Definition at line 231 of file profiler_vector_to_list.h.
     {
       __vector2list_info* __res = __get_object_info(__obj);
       if (__res)
     __res->__resize(__from, __to);
     }
References __gnu_profile::__trace_base< __vector2list_info, __vector2list_stack_info >::__get_object_info(), and __gnu_profile::__vector2list_info::__resize().
Referenced by __list_cost(), and __vector_cost().
__retire_object()
void __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__retire_object (__object_t __object) inherited
Definition at line 277 of file profiler_trace.h.
     {
       this->__object_table_lock.lock();
       this->__stack_table_lock.lock();
       typename __object_table_t::iterator __object_it
     = __object_table.find(__object);
       if (__object_it != __object_table.end())
     {
       const __object_info& __info = __object_it->second;
       const __stack_t& __stack = __info.__stack();
       typename __stack_table_t::iterator __stack_it
         = __stack_table.find(__stack);
       if (__stack_it == __stack_table.end())
         {
           // First occurence of this call context.
           if (__max_mem() == 0 || __stack_table_byte_size < __max_mem())
         {
           __stack_table_byte_size
             += (sizeof(__instruction_address_t) * __size(__stack)
             + sizeof(__stack) + sizeof(__stack_info));
           __stack_table.insert(make_pair(__stack,
                          __stack_info(__info)));
         }
         }
       else
         {
           // Merge object info into info summary for this call context.
           __stack_it->second.__merge(__info);
           delete __stack;
         }
       __object_table.erase(__object);
     }
       this->__object_table_lock.unlock();
       this->__stack_table_lock.unlock();
     }
__vector_cost()
float __gnu_profile::__trace_vector_to_list::__vector_cost (std::size_t __shift, std::size_t __iterate, std::size_t __resize) inline
Definition at line 239 of file profiler_vector_to_list.h.
     {
       return (__shift
           * _GLIBCXX_PROFILE_DATA(__vector_shift_cost_factor).__value
           + __iterate
           * _GLIBCXX_PROFILE_DATA(__vector_iterate_cost_factor).__value
           + __resize
           * _GLIBCXX_PROFILE_DATA(__vector_resize_cost_factor).__value);
     }
References __resize(), and _GLIBCXX_PROFILE_DATA.
Referenced by __destruct().
__write()
void __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__write (FILE * __f) inherited
Definition at line 319 of file profiler_trace.h.
     {
       for (typename __stack_table_t::iterator __it
          = __stack_table.begin(); __it != __stack_table.end(); ++__it)
     if (__it->second.__is_valid())
       {
         std::fprintf(__f, __id);
         std::fprintf(__f, "|");
         __gnu_profile::__write(__f, __it->first);
         std::fprintf(__f, "|");
         __it->second.__write(__f);
       }
     }
Field Documentation
__id
const char* __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__id protected inherited
Definition at line 220 of file profiler_trace.h.
__object_table
__object_table_t __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__object_table private inherited
Definition at line 215 of file profiler_trace.h.
__object_table_lock
__gnu_cxx::__mutex __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__object_table_lock private inherited
Definition at line 208 of file profiler_trace.h.
__stack_table
__stack_table_t __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__stack_table private inherited
Definition at line 216 of file profiler_trace.h.
__stack_table_byte_size
std::size_t __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__stack_table_byte_size private inherited
Definition at line 217 of file profiler_trace.h.
__stack_table_lock
__gnu_cxx::__mutex __gnu_profile::__trace_base< __vector2list_info , __vector2list_stack_info >::__stack_table_lock private inherited
Definition at line 209 of file profiler_trace.h.
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/profile/impl/profiler_vector_to_list.h