ZEQ2-Lite: Speex encoder and decoder
Speex encoder and decoder
This is the Speex codec itself.
Data Structures
struct SpeexMode
Struct defining a Speex mode.
Macros
#define SPEEX_GET_ABR 33
Get Average Bit-Rate (ABR) setting (in bps)
#define SPEEX_GET_ACTIVITY 47
Get "activity level" of the last decoded frame, i.e.
#define SPEEX_GET_BITRATE 19
Get current bit-rate used by the encoder or decoder.
#define SPEEX_GET_COMPLEXITY 17
Get current complexity of the encoder (0-10)
#define SPEEX_GET_DTX 35
Get DTX status (1 for on, 0 for off)
#define SPEEX_GET_ENH 1
Get enhancement state (decoder only)
#define SPEEX_GET_FRAME_SIZE 3
Obtain frame size used by encoder/decoder.
#define SPEEX_GET_HIGH_MODE 11
Get current high-band mode in use (wideband only)
#define SPEEX_GET_HIGHPASS 45
Get status of input/output high-pass filtering.
#define SPEEX_GET_LOOKAHEAD 39
Returns the lookahead used by Speex.
#define SPEEX_GET_LOW_MODE 9
Get current low-band mode in use (wideband only)
#define SPEEX_GET_MODE 7
Get current sub-mode in use.
#define SPEEX_GET_PF 1
Equivalent to SPEEX_GET_ENH.
#define SPEEX_GET_PLC_TUNING 41
Gets tuning for PLC.
#define SPEEX_GET_RELATIVE_QUALITY 29
Get VBR info (mostly used internally)
#define SPEEX_GET_SAMPLING_RATE 25
Get sampling rate used in bit-rate computation.
#define SPEEX_GET_SUBMODE_ENCODING 37
Get submode encoding in each frame.
#define SPEEX_GET_VAD 31
Get VAD status (1 for on, 0 for off)
#define SPEEX_GET_VBR 13
Get VBR status (1 for on, 0 for off)
#define SPEEX_GET_VBR_MAX_BITRATE 43
Gets the max bit-rate allowed in VBR mode.
#define SPEEX_GET_VBR_QUALITY 15
Get current quality value for VBR encoding (0-10)
#define SPEEX_LIB_GET_EXTRA_VERSION 7
Get extra Speex version.
#define SPEEX_LIB_GET_MAJOR_VERSION 1
Get major Speex version.
#define SPEEX_LIB_GET_MICRO_VERSION 5
Get micro Speex version.
#define SPEEX_LIB_GET_MINOR_VERSION 3
Get minor Speex version.
#define speex_lib_get_mode(mode) ((mode)==SPEEX_MODEID_NB ? &speex_nb_mode : speex_lib_get_mode (mode))
#define SPEEX_LIB_GET_VERSION_STRING 9
Get Speex version string.
#define SPEEX_MODE_FRAME_SIZE 0
Query the frame size of a mode.
#define SPEEX_MODEID_NB 0
modeID for the defined narrowband mode
#define SPEEX_MODEID_UWB 2
modeID for the defined ultra-wideband mode
#define SPEEX_MODEID_WB 1
modeID for the defined wideband mode
#define SPEEX_NB_MODES 3
Number of defined modes in Speex.
#define SPEEX_RESET_STATE 26
Reset the encoder/decoder memories to zero.
#define SPEEX_SET_ABR 32
Set Average Bit-Rate (ABR) to n bits per seconds.
#define SPEEX_SET_BITRATE 18
Set bit-rate used by the encoder (or lower)
#define SPEEX_SET_COMPLEXITY 16
Set complexity of the encoder (0-10)
#define SPEEX_SET_DTX 34
Set DTX status (1 for on, 0 for off)
#define SPEEX_SET_ENH 0
Set enhancement on/off (decoder only)
#define SPEEX_SET_HANDLER 20
Define a handler function for in-band Speex request.
#define SPEEX_SET_HIGH_MODE 10
Set high-band sub-mode to use (wideband only)
#define SPEEX_SET_HIGHPASS 44
Turn on/off input/output high-pass filtering.
#define SPEEX_SET_LOW_MODE 8
Set low-band sub-mode to use (wideband only)
#define SPEEX_SET_MODE 6
Get current quality setting.
#define SPEEX_SET_PF 0
Equivalent to SPEEX_SET_ENH.
#define SPEEX_SET_PLC_TUNING 40
Sets tuning for packet-loss concealment (expected loss rate)
#define SPEEX_SET_QUALITY 4
Set quality value.
#define SPEEX_SET_SAMPLING_RATE 24
Set sampling rate used in bit-rate computation.
#define SPEEX_SET_SUBMODE_ENCODING 36
Set submode encoding in each frame (1 for yes, 0 for no, setting to no breaks the standard)
#define SPEEX_SET_USER_HANDLER 22
Define a handler function for in-band user-defined request.
#define SPEEX_SET_VAD 30
Set VAD status (1 for on, 0 for off)
#define SPEEX_SET_VBR 12
Set VBR on (1) or off (0)
#define SPEEX_SET_VBR_MAX_BITRATE 42
Sets the max bit-rate allowed in VBR mode.
#define SPEEX_SET_VBR_QUALITY 14
Set quality value for VBR encoding (0-10)
#define SPEEX_SUBMODE_BITS_PER_FRAME 1
Query the size of an encoded frame for a particular sub-mode.
Typedefs
typedef int(* decode_func) (void *state, SpeexBits *bits, void *out)
Main decoding function.
typedef int(* decoder_ctl_func) (void *state, int request, void *ptr)
Function for controlling the decoder options.
typedef void(* decoder_destroy_func) (void *st)
Decoder state destruction function.
typedef void *(* decoder_init_func) (const struct SpeexMode *mode)
Decoder state initialization function.
typedef int(* encode_func) (void *state, void *in, SpeexBits *bits)
Main encoding function.
typedef int(* encoder_ctl_func) (void *state, int request, void *ptr)
Function for controlling the encoder options.
typedef void(* encoder_destroy_func) (void *st)
Encoder state destruction function.
typedef void *(* encoder_init_func) (const struct SpeexMode *mode)
Encoder state initialization function.
typedef int(* mode_query_func) (const void *mode, int request, void *ptr)
Query function for a mode.
Functions
int speex_decode (void *state, SpeexBits *bits, float *out)
Uses an existing decoder state to decode one frame of speech from bit-stream bits.
int speex_decode_int (void *state, SpeexBits *bits, spx_int16_t *out)
Uses an existing decoder state to decode one frame of speech from bit-stream bits.
int speex_decoder_ctl (void *state, int request, void *ptr)
Used like the ioctl function to control the encoder parameters.
void speex_decoder_destroy (void *state)
Frees all resources associated to an existing decoder state.
void * speex_decoder_init (const SpeexMode *mode)
Returns a handle to a newly created decoder state structure.
int speex_encode (void *state, float *in, SpeexBits *bits)
Uses an existing encoder state to encode one frame of speech pointed to by "in".
int speex_encode_int (void *state, spx_int16_t *in, SpeexBits *bits)
Uses an existing encoder state to encode one frame of speech pointed to by "in".
int speex_encoder_ctl (void *state, int request, void *ptr)
Used like the ioctl function to control the encoder parameters.
void speex_encoder_destroy (void *state)
Frees all resources associated to an existing Speex encoder state.
void * speex_encoder_init (const SpeexMode *mode)
Returns a handle to a newly created Speex encoder state structure.
int speex_lib_ctl (int request, void *ptr)
Functions for controlling the behavior of libspeex.
const SpeexMode * speex_lib_get_mode (int mode)
Obtain one of the modes available.
int speex_mode_query (const SpeexMode *mode, int request, void *ptr)
Query function for mode information.
Variables
const SpeexMode *const speex_mode_list [SPEEX_NB_MODES]
List of all modes available.
const SpeexMode speex_nb_mode
Default narrowband mode.
const SpeexMode speex_uwb_mode
Default "ultra-wideband" mode.
const SpeexMode speex_wb_mode
Default wideband mode.
Detailed Description
This is the Speex codec itself.
Macro Definition Documentation
SPEEX_GET_ABR
#define SPEEX_GET_ABR 33
#include <Engine/libspeex/include/speex/speex.h>
Get Average Bit-Rate (ABR) setting (in bps)
Definition at line 127 of file speex.h.
SPEEX_GET_ACTIVITY
#define SPEEX_GET_ACTIVITY 47
#include <Engine/libspeex/include/speex/speex.h>
Get "activity level" of the last decoded frame, i.e.
how much damage we cause if we remove the frame
Definition at line 160 of file speex.h.
SPEEX_GET_BITRATE
#define SPEEX_GET_BITRATE 19
#include <Engine/libspeex/include/speex/speex.h>
Get current bit-rate used by the encoder or decoder.
Definition at line 99 of file speex.h.
SPEEX_GET_COMPLEXITY
#define SPEEX_GET_COMPLEXITY 17
#include <Engine/libspeex/include/speex/speex.h>
Get current complexity of the encoder (0-10)
Definition at line 94 of file speex.h.
SPEEX_GET_DTX
#define SPEEX_GET_DTX 35
#include <Engine/libspeex/include/speex/speex.h>
Get DTX status (1 for on, 0 for off)
Definition at line 132 of file speex.h.
SPEEX_GET_ENH
#define SPEEX_GET_ENH 1
#include <Engine/libspeex/include/speex/speex.h>
Get enhancement state (decoder only)
Definition at line 55 of file speex.h.
SPEEX_GET_FRAME_SIZE
#define SPEEX_GET_FRAME_SIZE 3
#include <Engine/libspeex/include/speex/speex.h>
Obtain frame size used by encoder/decoder.
Definition at line 59 of file speex.h.
SPEEX_GET_HIGH_MODE
#define SPEEX_GET_HIGH_MODE 11
#include <Engine/libspeex/include/speex/speex.h>
Get current high-band mode in use (wideband only)
Definition at line 79 of file speex.h.
SPEEX_GET_HIGHPASS
#define SPEEX_GET_HIGHPASS 45
#include <Engine/libspeex/include/speex/speex.h>
Get status of input/output high-pass filtering.
Definition at line 156 of file speex.h.
SPEEX_GET_LOOKAHEAD
#define SPEEX_GET_LOOKAHEAD 39
#include <Engine/libspeex/include/speex/speex.h>
Returns the lookahead used by Speex.
Definition at line 141 of file speex.h.
SPEEX_GET_LOW_MODE
#define SPEEX_GET_LOW_MODE 9
#include <Engine/libspeex/include/speex/speex.h>
Get current low-band mode in use (wideband only)
Definition at line 74 of file speex.h.
SPEEX_GET_MODE
#define SPEEX_GET_MODE 7
#include <Engine/libspeex/include/speex/speex.h>
Get current sub-mode in use.
Definition at line 69 of file speex.h.
SPEEX_GET_PF
#define SPEEX_GET_PF 1
#include <Engine/libspeex/include/speex/speex.h>
Equivalent to SPEEX_GET_ENH.
Definition at line 167 of file speex.h.
SPEEX_GET_PLC_TUNING
#define SPEEX_GET_PLC_TUNING 41
#include <Engine/libspeex/include/speex/speex.h>
Gets tuning for PLC.
Definition at line 146 of file speex.h.
SPEEX_GET_RELATIVE_QUALITY
#define SPEEX_GET_RELATIVE_QUALITY 29
#include <Engine/libspeex/include/speex/speex.h>
Get VBR info (mostly used internally)
Definition at line 116 of file speex.h.
SPEEX_GET_SAMPLING_RATE
#define SPEEX_GET_SAMPLING_RATE 25
#include <Engine/libspeex/include/speex/speex.h>
Get sampling rate used in bit-rate computation.
Definition at line 110 of file speex.h.
SPEEX_GET_SUBMODE_ENCODING
#define SPEEX_GET_SUBMODE_ENCODING 37
#include <Engine/libspeex/include/speex/speex.h>
Get submode encoding in each frame.
Definition at line 137 of file speex.h.
SPEEX_GET_VAD
#define SPEEX_GET_VAD 31
#include <Engine/libspeex/include/speex/speex.h>
Get VAD status (1 for on, 0 for off)
Definition at line 122 of file speex.h.
SPEEX_GET_VBR
#define SPEEX_GET_VBR 13
#include <Engine/libspeex/include/speex/speex.h>
Get VBR status (1 for on, 0 for off)
Definition at line 84 of file speex.h.
SPEEX_GET_VBR_MAX_BITRATE
#define SPEEX_GET_VBR_MAX_BITRATE 43
#include <Engine/libspeex/include/speex/speex.h>
Gets the max bit-rate allowed in VBR mode.
Definition at line 151 of file speex.h.
SPEEX_GET_VBR_QUALITY
#define SPEEX_GET_VBR_QUALITY 15
#include <Engine/libspeex/include/speex/speex.h>
Get current quality value for VBR encoding (0-10)
Definition at line 89 of file speex.h.
SPEEX_LIB_GET_EXTRA_VERSION
#define SPEEX_LIB_GET_EXTRA_VERSION 7
#include <Engine/libspeex/include/speex/speex.h>
Get extra Speex version.
Definition at line 188 of file speex.h.
SPEEX_LIB_GET_MAJOR_VERSION
#define SPEEX_LIB_GET_MAJOR_VERSION 1
#include <Engine/libspeex/include/speex/speex.h>
Get major Speex version.
Definition at line 182 of file speex.h.
SPEEX_LIB_GET_MICRO_VERSION
#define SPEEX_LIB_GET_MICRO_VERSION 5
#include <Engine/libspeex/include/speex/speex.h>
Get micro Speex version.
Definition at line 186 of file speex.h.
SPEEX_LIB_GET_MINOR_VERSION
#define SPEEX_LIB_GET_MINOR_VERSION 3
#include <Engine/libspeex/include/speex/speex.h>
Get minor Speex version.
Definition at line 184 of file speex.h.
speex_lib_get_mode
#define speex_lib_get_mode (mode) ((mode)==SPEEX_MODEID_NB ? &speex_nb_mode : speex_lib_get_mode (mode))
#include <Engine/libspeex/include/speex/speex.h>
Definition at line 416 of file speex.h.
SPEEX_LIB_GET_VERSION_STRING
#define SPEEX_LIB_GET_VERSION_STRING 9
#include <Engine/libspeex/include/speex/speex.h>
Get Speex version string.
Definition at line 190 of file speex.h.
SPEEX_MODE_FRAME_SIZE
#define SPEEX_MODE_FRAME_SIZE 0
#include <Engine/libspeex/include/speex/speex.h>
Query the frame size of a mode.
Definition at line 174 of file speex.h.
SPEEX_MODEID_NB
#define SPEEX_MODEID_NB 0
#include <Engine/libspeex/include/speex/speex.h>
modeID for the defined narrowband mode
Definition at line 207 of file speex.h.
SPEEX_MODEID_UWB
#define SPEEX_MODEID_UWB 2
#include <Engine/libspeex/include/speex/speex.h>
modeID for the defined ultra-wideband mode
Definition at line 213 of file speex.h.
SPEEX_MODEID_WB
#define SPEEX_MODEID_WB 1
#include <Engine/libspeex/include/speex/speex.h>
modeID for the defined wideband mode
Definition at line 210 of file speex.h.
SPEEX_NB_MODES
#define SPEEX_NB_MODES 3
#include <Engine/libspeex/include/speex/speex.h>
Number of defined modes in Speex.
Definition at line 204 of file speex.h.
SPEEX_RESET_STATE
#define SPEEX_RESET_STATE 26
#include <Engine/libspeex/include/speex/speex.h>
Reset the encoder/decoder memories to zero.
Definition at line 113 of file speex.h.
SPEEX_SET_ABR
#define SPEEX_SET_ABR 32
#include <Engine/libspeex/include/speex/speex.h>
Set Average Bit-Rate (ABR) to n bits per seconds.
Definition at line 125 of file speex.h.
SPEEX_SET_BITRATE
#define SPEEX_SET_BITRATE 18
#include <Engine/libspeex/include/speex/speex.h>
Set bit-rate used by the encoder (or lower)
Definition at line 97 of file speex.h.
SPEEX_SET_COMPLEXITY
#define SPEEX_SET_COMPLEXITY 16
#include <Engine/libspeex/include/speex/speex.h>
Set complexity of the encoder (0-10)
Definition at line 92 of file speex.h.
SPEEX_SET_DTX
#define SPEEX_SET_DTX 34
#include <Engine/libspeex/include/speex/speex.h>
Set DTX status (1 for on, 0 for off)
Definition at line 130 of file speex.h.
SPEEX_SET_ENH
#define SPEEX_SET_ENH 0
#include <Engine/libspeex/include/speex/speex.h>
Set enhancement on/off (decoder only)
Definition at line 53 of file speex.h.
SPEEX_SET_HANDLER
#define SPEEX_SET_HANDLER 20
#include <Engine/libspeex/include/speex/speex.h>
Define a handler function for in-band Speex request.
Definition at line 102 of file speex.h.
SPEEX_SET_HIGH_MODE
#define SPEEX_SET_HIGH_MODE 10
#include <Engine/libspeex/include/speex/speex.h>
Set high-band sub-mode to use (wideband only)
Definition at line 77 of file speex.h.
SPEEX_SET_HIGHPASS
#define SPEEX_SET_HIGHPASS 44
#include <Engine/libspeex/include/speex/speex.h>
Turn on/off input/output high-pass filtering.
Definition at line 154 of file speex.h.
SPEEX_SET_LOW_MODE
#define SPEEX_SET_LOW_MODE 8
#include <Engine/libspeex/include/speex/speex.h>
Set low-band sub-mode to use (wideband only)
Definition at line 72 of file speex.h.
SPEEX_SET_MODE
#define SPEEX_SET_MODE 6
#include <Engine/libspeex/include/speex/speex.h>
Get current quality setting.
Set sub-mode to use
Definition at line 67 of file speex.h.
SPEEX_SET_PF
#define SPEEX_SET_PF 0
#include <Engine/libspeex/include/speex/speex.h>
Equivalent to SPEEX_SET_ENH.
Definition at line 165 of file speex.h.
SPEEX_SET_PLC_TUNING
#define SPEEX_SET_PLC_TUNING 40
#include <Engine/libspeex/include/speex/speex.h>
Sets tuning for packet-loss concealment (expected loss rate)
Definition at line 144 of file speex.h.
SPEEX_SET_QUALITY
#define SPEEX_SET_QUALITY 4
#include <Engine/libspeex/include/speex/speex.h>
Set quality value.
Definition at line 62 of file speex.h.
SPEEX_SET_SAMPLING_RATE
#define SPEEX_SET_SAMPLING_RATE 24
#include <Engine/libspeex/include/speex/speex.h>
Set sampling rate used in bit-rate computation.
Definition at line 108 of file speex.h.
SPEEX_SET_SUBMODE_ENCODING
#define SPEEX_SET_SUBMODE_ENCODING 36
#include <Engine/libspeex/include/speex/speex.h>
Set submode encoding in each frame (1 for yes, 0 for no, setting to no breaks the standard)
Definition at line 135 of file speex.h.
SPEEX_SET_USER_HANDLER
#define SPEEX_SET_USER_HANDLER 22
#include <Engine/libspeex/include/speex/speex.h>
Define a handler function for in-band user-defined request.
Definition at line 105 of file speex.h.
SPEEX_SET_VAD
#define SPEEX_SET_VAD 30
#include <Engine/libspeex/include/speex/speex.h>
Set VAD status (1 for on, 0 for off)
Definition at line 119 of file speex.h.
SPEEX_SET_VBR
#define SPEEX_SET_VBR 12
#include <Engine/libspeex/include/speex/speex.h>
Set VBR on (1) or off (0)
Definition at line 82 of file speex.h.
SPEEX_SET_VBR_MAX_BITRATE
#define SPEEX_SET_VBR_MAX_BITRATE 42
#include <Engine/libspeex/include/speex/speex.h>
Sets the max bit-rate allowed in VBR mode.
Definition at line 149 of file speex.h.
SPEEX_SET_VBR_QUALITY
#define SPEEX_SET_VBR_QUALITY 14
#include <Engine/libspeex/include/speex/speex.h>
Set quality value for VBR encoding (0-10)
Definition at line 87 of file speex.h.
SPEEX_SUBMODE_BITS_PER_FRAME
#define SPEEX_SUBMODE_BITS_PER_FRAME 1
#include <Engine/libspeex/include/speex/speex.h>
Query the size of an encoded frame for a particular sub-mode.
Definition at line 177 of file speex.h.
Typedef Documentation
decode_func
typedef int(* decode_func) (void *state, SpeexBits *bits, void *out)
#include <Engine/libspeex/include/speex/speex.h>
Main decoding function.
Definition at line 239 of file speex.h.
decoder_ctl_func
typedef int(* decoder_ctl_func) (void *state, int request, void *ptr)
#include <Engine/libspeex/include/speex/speex.h>
Function for controlling the decoder options.
Definition at line 242 of file speex.h.
decoder_destroy_func
typedef void(* decoder_destroy_func) (void *st)
#include <Engine/libspeex/include/speex/speex.h>
Decoder state destruction function.
Definition at line 236 of file speex.h.
decoder_init_func
typedef void*(* decoder_init_func) (const struct SpeexMode *mode)
#include <Engine/libspeex/include/speex/speex.h>
Decoder state initialization function.
Definition at line 233 of file speex.h.
encode_func
typedef int(* encode_func) (void *state, void *in, SpeexBits *bits)
#include <Engine/libspeex/include/speex/speex.h>
Main encoding function.
Definition at line 227 of file speex.h.
encoder_ctl_func
typedef int(* encoder_ctl_func) (void *state, int request, void *ptr)
#include <Engine/libspeex/include/speex/speex.h>
Function for controlling the encoder options.
Definition at line 230 of file speex.h.
encoder_destroy_func
typedef void(* encoder_destroy_func) (void *st)
#include <Engine/libspeex/include/speex/speex.h>
Encoder state destruction function.
Definition at line 224 of file speex.h.
encoder_init_func
typedef void*(* encoder_init_func) (const struct SpeexMode *mode)
#include <Engine/libspeex/include/speex/speex.h>
Encoder state initialization function.
Definition at line 221 of file speex.h.
mode_query_func
typedef int(* mode_query_func) (const void *mode, int request, void *ptr)
#include <Engine/libspeex/include/speex/speex.h>
Query function for a mode.
Definition at line 246 of file speex.h.
Function Documentation
speex_decode()
int speex_decode (void * state, SpeexBits * bits, float * out)
#include <Engine/libspeex/include/speex/speex.h>
Uses an existing decoder state to decode one frame of speech from bit-stream bits.
The output speech is saved written to out.
Parameters
state Decoder state
bits Bit-stream from which to decode the frame (NULL if the packet was lost)
out Where to write the decoded frame
Returns
return status (0 for no error, -1 for end of stream, -2 corrupt stream)
Definition at line 152 of file speex.c.
 {
    return (*((SpeexMode**)state))->dec(state, bits, out);
 }
References bits(), and out.
speex_decode_int()
int speex_decode_int (void * state, SpeexBits * bits, spx_int16_t * out)
#include <Engine/libspeex/include/speex/speex.h>
Uses an existing decoder state to decode one frame of speech from bit-stream bits.
The output speech is saved written to out.
Parameters
state Decoder state
bits Bit-stream from which to decode the frame (NULL if the packet was lost)
out Where to write the decoded frame
Returns
return status (0 for no error, -1 for end of stream, -2 corrupt stream)
Definition at line 157 of file speex.c.
 {
    int i;
    spx_int32_t N;
    float float_out[MAX_IN_SAMPLES];
    int ret;
    speex_decoder_ctl(state, SPEEX_GET_FRAME_SIZE, &N);
    ret = (*((SpeexMode**)state))->dec(state, bits, float_out);
    for (i=0;i<N;i++)
    {
       if (float_out[i]>32767.f)
          out[i] = 32767;
       else if (float_out[i]<-32768.f)
          out[i] = -32768;
       else
          out[i] = (spx_int16_t)floor(.5+float_out[i]);
    }
    return ret;
 }
References bits(), MAX_IN_SAMPLES, out, speex_decoder_ctl(), and SPEEX_GET_FRAME_SIZE.
Referenced by main().
speex_decoder_ctl()
int speex_decoder_ctl (void * state, int request, void * ptr)
#include <Engine/libspeex/include/speex/speex.h>
Used like the ioctl function to control the encoder parameters.
Parameters
state Decoder state
request ioctl-type request (one of the SPEEX_* macros)
ptr Data exchanged to-from function
Returns
0 if no error, -1 if request in unknown, -2 for invalid parameter
Definition at line 185 of file speex.c.
 {
    return (*((SpeexMode**)state))->dec_ctl(state, request, ptr);
 }
References ptr().
Referenced by main(), sb_decode(), sb_decoder_ctl(), sb_decoder_init(), speex_decode_int(), and speex_std_enh_request_handler().
speex_decoder_destroy()
void speex_decoder_destroy (void * state)
#include <Engine/libspeex/include/speex/speex.h>
Frees all resources associated to an existing decoder state.
Parameters
state State to be destroyed
Definition at line 66 of file speex.c.
 {
    (*((SpeexMode**)state))->dec_destroy(state);
 }
Referenced by CL_Disconnect(), main(), and sb_decoder_destroy().
speex_decoder_init()
void* speex_decoder_init (const SpeexMode * mode)
#include <Engine/libspeex/include/speex/speex.h>
Returns a handle to a newly created decoder state structure.
For now, the mode argument can be &nb_mode or &wb_mode . In the future, more modes may be added. Note that for now if you have more than one channels to decode, you need one state per channel.
Parameters
mode Speex mode (one of speex_nb_mode or speex_wb_mode)
Returns
A newly created decoder state or NULL if state allocation fails
Definition at line 56 of file speex.c.
 {
    return mode->dec_init(mode);
 }
Referenced by CL_FirstSnapshot(), main(), and sb_decoder_init().
speex_encode()
int speex_encode (void * state, float * in, SpeexBits * bits)
#include <Engine/libspeex/include/speex/speex.h>
Uses an existing encoder state to encode one frame of speech pointed to by "in".
The encoded bit-stream is saved in "bits".
Parameters
state Encoder state
in Frame that will be encoded with a +-2^15 range. This data MAY be overwritten by the encoder and should be considered uninitialised after the call.
bits Bit-stream where the data will be written
Returns
0 if frame needs not be transmitted (DTX only), 1 otherwise
Definition at line 136 of file speex.c.
 {
    return (*((SpeexMode**)state))->enc(state, in, bits);
 }
References bits().
speex_encode_int()
int speex_encode_int (void * state, spx_int16_t * in, SpeexBits * bits)
#include <Engine/libspeex/include/speex/speex.h>
Uses an existing encoder state to encode one frame of speech pointed to by "in".
The encoded bit-stream is saved in "bits".
Parameters
state Encoder state
in Frame that will be encoded with a +-2^15 range
bits Bit-stream where the data will be written
Returns
0 if frame needs not be transmitted (DTX only), 1 otherwise
Definition at line 141 of file speex.c.
 {
    int i;
    spx_int32_t N;
    float float_in[MAX_IN_SAMPLES];
    speex_encoder_ctl(state, SPEEX_GET_FRAME_SIZE, &N);
    for (i=0;i<N;i++)
       float_in[i] = in[i];
    return (*((SpeexMode**)state))->enc(state, float_in, bits);
 }
References bits(), MAX_IN_SAMPLES, speex_encoder_ctl(), and SPEEX_GET_FRAME_SIZE.
Referenced by main().
speex_encoder_ctl()
int speex_encoder_ctl (void * state, int request, void * ptr)
#include <Engine/libspeex/include/speex/speex.h>
Used like the ioctl function to control the encoder parameters.
Parameters
state Encoder state
request ioctl-type request (one of the SPEEX_* macros)
ptr Data exchanged to-from function
Returns
0 if no error, -1 if request in unknown, -2 for invalid parameter
Definition at line 180 of file speex.c.
 {
    return (*((SpeexMode**)state))->enc_ctl(state, request, ptr);
 }
References ptr().
Referenced by CL_FirstSnapshot(), main(), nb_encode(), nb_encoder_ctl(), sb_encode(), sb_encoder_ctl(), sb_encoder_init(), speex_encode_int(), speex_std_high_mode_request_handler(), speex_std_low_mode_request_handler(), speex_std_mode_request_handler(), speex_std_vbr_quality_request_handler(), and speex_std_vbr_request_handler().
speex_encoder_destroy()
void speex_encoder_destroy (void * state)
#include <Engine/libspeex/include/speex/speex.h>
Frees all resources associated to an existing Speex encoder state.
Parameters
state Encoder state to be destroyed
Definition at line 61 of file speex.c.
 {
    (*((SpeexMode**)state))->enc_destroy(state);
 }
Referenced by CL_Disconnect(), main(), and sb_encoder_destroy().
speex_encoder_init()
void* speex_encoder_init (const SpeexMode * mode)
#include <Engine/libspeex/include/speex/speex.h>
Returns a handle to a newly created Speex encoder state structure.
For now, the "mode" argument can be &nb_mode or &wb_mode . In the future, more modes may be added. Note that for now if you have more than one channels to encode, you need one state per channel.
Parameters
mode The mode to use (either speex_nb_mode or speex_wb.mode)
Returns
A newly created encoder state or NULL if state allocation fails
Definition at line 51 of file speex.c.
 {
    return mode->enc_init(mode);
 }
Referenced by CL_FirstSnapshot(), main(), and sb_encoder_init().
speex_lib_ctl()
int speex_lib_ctl (int request, void * ptr)
#include <Engine/libspeex/include/speex/speex.h>
Functions for controlling the behavior of libspeex.
Parameters
request ioctl-type request (one of the SPEEX_LIB_* macros)
ptr Data exchanged to-from function
Returns
0 if no error, -1 if request in unknown, -2 for invalid parameter
Definition at line 218 of file speex.c.
 {
    switch (request)
    {
       case SPEEX_LIB_GET_MAJOR_VERSION:
          *((int*)ptr) = SPEEX_MAJOR_VERSION;
          break;
       case SPEEX_LIB_GET_MINOR_VERSION:
          *((int*)ptr) = SPEEX_MINOR_VERSION;
          break;
       case SPEEX_LIB_GET_MICRO_VERSION:
          *((int*)ptr) = SPEEX_MICRO_VERSION;
          break;
       case SPEEX_LIB_GET_EXTRA_VERSION:
          *((const char**)ptr) = SPEEX_EXTRA_VERSION;
          break;
       case SPEEX_LIB_GET_VERSION_STRING:
          *((const char**)ptr) = SPEEX_VERSION;
          break;
       /*case SPEEX_LIB_SET_ALLOC_FUNC:
          break;
       case SPEEX_LIB_GET_ALLOC_FUNC:
          break;
       case SPEEX_LIB_SET_FREE_FUNC:
          break;
       case SPEEX_LIB_GET_FREE_FUNC:
          break;*/
       default:
          speex_warning_int("Unknown wb_mode_query request: ", request);
          return -1;
    }
    return 0;
 }
References ptr(), SPEEX_EXTRA_VERSION, SPEEX_LIB_GET_EXTRA_VERSION, SPEEX_LIB_GET_MAJOR_VERSION, SPEEX_LIB_GET_MICRO_VERSION, SPEEX_LIB_GET_MINOR_VERSION, SPEEX_LIB_GET_VERSION_STRING, SPEEX_MAJOR_VERSION, SPEEX_MICRO_VERSION, SPEEX_MINOR_VERSION, SPEEX_VERSION, and speex_warning_int().
speex_lib_get_mode()
const SpeexMode* speex_lib_get_mode (int mode)
#include <Engine/libspeex/include/speex/speex.h>
Obtain one of the modes available.
Definition at line 292 of file modes_wb.c.
 {
    if (mode < 0 || mode >= SPEEX_NB_MODES) return NULL;
    return speex_mode_list[mode];
 }
References NULL, speex_mode_list, and SPEEX_NB_MODES.
speex_mode_query()
int speex_mode_query (const SpeexMode * mode, int request, void * ptr)
#include <Engine/libspeex/include/speex/speex.h>
Query function for mode information.
Parameters
mode Speex mode
request ioctl-type request (one of the SPEEX_* macros)
ptr Data exchanged to-from function
Returns
0 if no error, -1 if request in unknown, -2 for invalid parameter
Definition at line 358 of file modes.c.
 {
    return mode->query(mode->mode, request, ptr);
 }
References ptr().
Referenced by speex_init_header().
Variable Documentation
speex_mode_list
const SpeexMode* const speex_mode_list[SPEEX_NB_MODES]
#include <Engine/libspeex/include/speex/speex.h>
List of all modes available.
Definition at line 55 of file modes_wb.c.
Referenced by speex_lib_get_mode().
speex_nb_mode
const SpeexMode speex_nb_mode
#include <Engine/libspeex/include/speex/speex.h>
Default narrowband mode.
Definition at line 340 of file modes.c.
Referenced by CL_FirstSnapshot().
speex_uwb_mode
const SpeexMode speex_uwb_mode
#include <Engine/libspeex/include/speex/speex.h>
Default "ultra-wideband" mode.
Definition at line 273 of file modes_wb.c.
speex_wb_mode
const SpeexMode speex_wb_mode
#include <Engine/libspeex/include/speex/speex.h>
Default wideband mode.
Definition at line 203 of file modes_wb.c.