ZEQ2-Lite: __gnu_debug Namespace Reference
__gnu_debug Namespace Reference
GNU debug classes for public use.
Data Structures
struct __is_safe_random_iterator
struct __is_safe_random_iterator< _Safe_iterator< _Iterator, _Sequence > >
class _After_nth_from
A function object that returns true when the given random access iterator is at least n steps away from the given iterator.
struct _BeforeBeginHelper
Helper struct to deal with sequence offering a before_begin iterator.
class _Equal_to
A simple function object that returns true if the passed-in value is equal to the stored value.
class _Error_formatter
class _Not_equal_to
A simple function object that returns true if the passed-in value is not equal to the stored value.
class _Safe_iterator
Safe iterator wrapper.
class _Safe_iterator_base
Basic functionality for a safe iterator.
class _Safe_sequence
Base class for constructing a safe sequence type that tracks iterators that reference it.
class _Safe_sequence_base
Base class that supports tracking of iterators that reference a sequence.
struct _Siter_base
Enumerations
enum _Debug_msg_id {
__msg_valid_range, __msg_insert_singular, __msg_insert_different, __msg_erase_bad,
__msg_erase_different, __msg_subscript_oob, __msg_empty, __msg_unpartitioned,
__msg_unpartitioned_pred, __msg_unsorted, __msg_unsorted_pred, __msg_not_heap,
__msg_not_heap_pred, __msg_bad_bitset_write, __msg_bad_bitset_read, __msg_bad_bitset_flip,
__msg_self_splice, __msg_splice_alloc, __msg_splice_bad, __msg_splice_other,
__msg_splice_overlap, __msg_init_singular, __msg_init_copy_singular, __msg_init_const_singular,
__msg_copy_singular, __msg_bad_deref, __msg_bad_inc, __msg_bad_dec,
__msg_iter_subscript_oob, __msg_advance_oob, __msg_retreat_oob, __msg_iter_compare_bad,
__msg_compare_different, __msg_iter_order_bad, __msg_order_different, __msg_distance_bad,
__msg_distance_different, __msg_deref_istream, __msg_inc_istream, __msg_output_ostream,
__msg_deref_istreambuf, __msg_inc_istreambuf, __msg_insert_after_end, __msg_erase_after_bad,
__msg_valid_range2
}
Functions
template<typename _Iterator >
_Siter_base< _Iterator >::iterator_type __base (_Iterator __it)
Helper function to extract base iterator of random access safe iterator in order to reduce performance impact of debug mode.
template<typename _Iterator >
bool __check_dereferenceable (_Iterator &)
Assume that some arbitrary iterator is dereferenceable, because we can't prove that it isn't.
template<typename _Iterator , typename _Sequence >
bool __check_dereferenceable (const _Safe_iterator< _Iterator, _Sequence > &__x)
Safe iterators know if they are singular.
template<typename _Tp >
bool __check_dereferenceable (const _Tp *__ptr)
Non-NULL pointers are dereferenceable.
template<typename _ForwardIterator , typename _Tp >
bool __check_partitioned_lower (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _ForwardIterator , typename _Tp , typename _Pred >
bool __check_partitioned_lower (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value, _Pred __pred)
template<typename _ForwardIterator , typename _Tp >
bool __check_partitioned_upper (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _ForwardIterator , typename _Tp , typename _Pred >
bool __check_partitioned_upper (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value, _Pred __pred)
template<typename _Iterator >
bool __check_singular (_Iterator &)
template<typename _Iterator , typename _Sequence >
bool __check_singular (const _Safe_iterator< _Iterator, _Sequence > &__x)
Safe iterators know if they are singular.
template<typename _Tp >
bool __check_singular (const _Tp *__ptr)
Non-NULL pointers are nonsingular.
bool __check_singular_aux (const _Safe_iterator_base *__x)
Iterators that derive from _Safe_iterator_base but that aren't _Safe_iterators can be determined singular or non-singular via _Safe_iterator_base.
bool __check_singular_aux (const void *)
template<typename _InputIterator >
bool __check_sorted (const _InputIterator &__first, const _InputIterator &__last)
template<typename _InputIterator , typename _Predicate >
bool __check_sorted (const _InputIterator &__first, const _InputIterator &__last, _Predicate __pred)
template<typename _ForwardIterator , typename _Predicate >
bool __check_sorted_aux (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, std::forward_iterator_tag)
template<typename _ForwardIterator >
bool __check_sorted_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag)
template<typename _InputIterator , typename _Predicate >
bool __check_sorted_aux (const _InputIterator &, const _InputIterator &, _Predicate, std::input_iterator_tag)
template<typename _InputIterator >
bool __check_sorted_aux (const _InputIterator &, const _InputIterator &, std::input_iterator_tag)
template<typename _InputIterator1 , typename _InputIterator2 >
bool __check_sorted_set (const _InputIterator1 &__first, const _InputIterator1 &__last, const _InputIterator2 &)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Predicate >
bool __check_sorted_set (const _InputIterator1 &__first, const _InputIterator1 &__last, const _InputIterator2 &, _Predicate __pred)
template<typename _InputIterator , typename _Predicate >
bool __check_sorted_set_aux (const _InputIterator &, const _InputIterator &, _Predicate, std::__false_type)
template<typename _InputIterator >
bool __check_sorted_set_aux (const _InputIterator &, const _InputIterator &, std::__false_type)
template<typename _InputIterator , typename _Predicate >
bool __check_sorted_set_aux (const _InputIterator &__first, const _InputIterator &__last, _Predicate __pred, std::__true_type)
template<typename _InputIterator >
bool __check_sorted_set_aux (const _InputIterator &__first, const _InputIterator &__last, std::__true_type)
template<typename _CharT >
const _CharT * __check_string (const _CharT *__s)
Checks that __s is non-NULL and then returns __s.
template<typename _CharT , typename _Integer >
const _CharT * __check_string (const _CharT *__s, const _Integer &__n __attribute__((__unused__)))
Checks that __s is non-NULL or __n == 0, and then returns __s.
template<typename _InputIterator >
_InputIterator __check_valid_range (const _InputIterator &__first, const _InputIterator &__last __attribute__((__unused__)))
template<typename _InputIterator >
bool __valid_range (const _InputIterator &__first, const _InputIterator &__last)
Don't know what these iterators are, or if they are even iterators (we may get an integral type for InputIterator), so see if they are integral and pass them on to the next phase otherwise.
template<typename _Iterator , typename _Sequence >
bool __valid_range (const _Safe_iterator< _Iterator, _Sequence > &__first, const _Safe_iterator< _Iterator, _Sequence > &__last)
Safe iterators know how to check if they form a valid range.
template<typename _InputIterator >
bool __valid_range_aux (const _InputIterator &__first, const _InputIterator &__last, std::__false_type)
We have iterators, so figure out what kind of iterators that are to see if we can check the range ahead of time.
template<typename _Integral >
bool __valid_range_aux (const _Integral &, const _Integral &, std::__true_type)
We say that integral types for a valid range, and defer to other routines to realize what to do with integral types instead of iterators.
template<typename _InputIterator >
bool __valid_range_aux2 (const _InputIterator &, const _InputIterator &, std::input_iterator_tag)
Can't test for a valid range with input iterators, because iteration may be destructive.
template<typename _RandomAccessIterator >
bool __valid_range_aux2 (const _RandomAccessIterator &__first, const _RandomAccessIterator &__last, std::random_access_iterator_tag)
If the distance between two random access iterators is nonnegative, assume the range is valid.
template<typename _Iterator , typename _Sequence >
bool operator!= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence >
bool operator!= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence >
_Safe_iterator< _Iterator, _Sequence > operator+ (typename _Safe_iterator< _Iterator, _Sequence >::difference_type __n, const _Safe_iterator< _Iterator, _Sequence > &__i)
template<typename _Iterator , typename _Sequence >
_Safe_iterator< _Iterator, _Sequence >::difference_type operator- (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence >
_Safe_iterator< _IteratorL, _Sequence >::difference_type operator- (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence >
bool operator< (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence >
bool operator< (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence >
bool operator<= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence >
bool operator<= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence >
bool operator== (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence >
bool operator== (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence >
bool operator> (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence >
bool operator> (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
template<typename _Iterator , typename _Sequence >
bool operator>= (const _Safe_iterator< _Iterator, _Sequence > &__lhs, const _Safe_iterator< _Iterator, _Sequence > &__rhs)
template<typename _IteratorL , typename _IteratorR , typename _Sequence >
bool operator>= (const _Safe_iterator< _IteratorL, _Sequence > &__lhs, const _Safe_iterator< _IteratorR, _Sequence > &__rhs)
Detailed Description
GNU debug classes for public use.
Enumeration Type Documentation
_Debug_msg_id
enum __gnu_debug::_Debug_msg_id
Enumerator
__msg_valid_range
__msg_insert_singular
__msg_insert_different
__msg_erase_bad
__msg_erase_different
__msg_subscript_oob
__msg_empty
__msg_unpartitioned
__msg_unpartitioned_pred
__msg_unsorted
__msg_unsorted_pred
__msg_not_heap
__msg_not_heap_pred
__msg_bad_bitset_write
__msg_bad_bitset_read
__msg_bad_bitset_flip
__msg_self_splice
__msg_splice_alloc
__msg_splice_bad
__msg_splice_other
__msg_splice_overlap
__msg_init_singular
__msg_init_copy_singular
__msg_init_const_singular
__msg_copy_singular
__msg_bad_deref
__msg_bad_inc
__msg_bad_dec
__msg_iter_subscript_oob
__msg_advance_oob
__msg_retreat_oob
__msg_iter_compare_bad
__msg_compare_different
__msg_iter_order_bad
__msg_order_different
__msg_distance_bad
__msg_distance_different
__msg_deref_istream
__msg_inc_istream
__msg_output_ostream
__msg_deref_istreambuf
__msg_inc_istreambuf
__msg_insert_after_end
__msg_erase_after_bad
__msg_valid_range2
Definition at line 52 of file formatter.h.
   {
     // General checks
     __msg_valid_range,
     __msg_insert_singular,
     __msg_insert_different,
     __msg_erase_bad,
     __msg_erase_different,
     __msg_subscript_oob,
     __msg_empty,
     __msg_unpartitioned,
     __msg_unpartitioned_pred,
     __msg_unsorted,
     __msg_unsorted_pred,
     __msg_not_heap,
     __msg_not_heap_pred,
     // std::bitset checks
     __msg_bad_bitset_write,
     __msg_bad_bitset_read,
     __msg_bad_bitset_flip,
     // std::list checks
     __msg_self_splice,
     __msg_splice_alloc,
     __msg_splice_bad,
     __msg_splice_other,
     __msg_splice_overlap,
     // iterator checks
     __msg_init_singular,
     __msg_init_copy_singular,
     __msg_init_const_singular,
     __msg_copy_singular,
     __msg_bad_deref,
     __msg_bad_inc,
     __msg_bad_dec,
     __msg_iter_subscript_oob,
     __msg_advance_oob,
     __msg_retreat_oob,
     __msg_iter_compare_bad,
     __msg_compare_different,
     __msg_iter_order_bad,
     __msg_order_different,
     __msg_distance_bad,
     __msg_distance_different,
     // istream_iterator
     __msg_deref_istream,
     __msg_inc_istream,
     // ostream_iterator
     __msg_output_ostream,
     // istreambuf_iterator
     __msg_deref_istreambuf,
     __msg_inc_istreambuf,
     // forward_list
     __msg_insert_after_end,
     __msg_erase_after_bad,
     __msg_valid_range2
   };
Function Documentation
__base()
template<typename _Iterator > _Siter_base<_Iterator>::iterator_type __gnu_debug::__base (_Iterator __it) inline
Helper function to extract base iterator of random access safe iterator in order to reduce performance impact of debug mode.
Limited to random access iterator because it is the only category for which it is possible to check for correct iterators order in the __valid_range function thanks to the < operator.
Definition at line 683 of file safe_iterator.h.
     { return _Siter_base<_Iterator>::_S_base(__it); }
Referenced by _GLIBCXX_VISIBILITY().
__check_dereferenceable() [1/3]
template<typename _Iterator > bool __gnu_debug::__check_dereferenceable (_Iterator &) inline
Assume that some arbitrary iterator is dereferenceable, because we can't prove that it isn't.
Definition at line 70 of file functions.h.
     { return true; }
__check_dereferenceable() [2/3]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__check_dereferenceable (const _Safe_iterator< _Iterator, _Sequence > & __x) inline
Safe iterators know if they are singular.
Definition at line 82 of file functions.h.
     { return __x._M_dereferenceable(); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_dereferenceable().
__check_dereferenceable() [3/3]
template<typename _Tp > bool __gnu_debug::__check_dereferenceable (const _Tp * __ptr) inline
Non-NULL pointers are dereferenceable.
Definition at line 76 of file functions.h.
     { return __ptr; }
__check_partitioned_lower() [1/2]
template<typename _ForwardIterator , typename _Tp > bool __gnu_debug::__check_partitioned_lower (_ForwardIterator __first, _ForwardIterator __last, const _Tp & __value) inline
Definition at line 333 of file functions.h.
     {
       while (__first != __last && *__first < __value)
     ++__first;
       while (__first != __last && !(*__first < __value))
     ++__first;
       return __first == __last;
     }
__check_partitioned_lower() [2/2]
template<typename _ForwardIterator , typename _Tp , typename _Pred > bool __gnu_debug::__check_partitioned_lower (_ForwardIterator __first, _ForwardIterator __last, const _Tp & __value, _Pred __pred) inline
Definition at line 358 of file functions.h.
     {
       while (__first != __last && bool(__pred(*__first, __value)))
     ++__first;
       while (__first != __last && !bool(__pred(*__first, __value)))
     ++__first;
       return __first == __last;
     }
__check_partitioned_upper() [1/2]
template<typename _ForwardIterator , typename _Tp > bool __gnu_debug::__check_partitioned_upper (_ForwardIterator __first, _ForwardIterator __last, const _Tp & __value) inline
Definition at line 345 of file functions.h.
     {
       while (__first != __last && !(__value < *__first))
     ++__first;
       while (__first != __last && __value < *__first)
     ++__first;
       return __first == __last;
     }
__check_partitioned_upper() [2/2]
template<typename _ForwardIterator , typename _Tp , typename _Pred > bool __gnu_debug::__check_partitioned_upper (_ForwardIterator __first, _ForwardIterator __last, const _Tp & __value, _Pred __pred) inline
Definition at line 371 of file functions.h.
     {
       while (__first != __last && !bool(__pred(__value, *__first)))
     ++__first;
       while (__first != __last && bool(__pred(__value, *__first)))
     ++__first;
       return __first == __last;
     }
__check_singular() [1/3]
template<typename _Iterator > bool __gnu_debug::__check_singular (_Iterator & __x) inline
Definition at line 51 of file functions.h.
     { return __check_singular_aux(&__x); }
References __check_singular_aux().
Referenced by __gnu_debug::_Error_formatter::_Parameter::_Parameter().
__check_singular() [2/3]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__check_singular (const _Safe_iterator< _Iterator, _Sequence > & __x) inline
Safe iterators know if they are singular.
Definition at line 63 of file functions.h.
     { return __x._M_singular(); }
__check_singular() [3/3]
template<typename _Tp > bool __gnu_debug::__check_singular (const _Tp * __ptr) inline
Non-NULL pointers are nonsingular.
Definition at line 57 of file functions.h.
     { return __ptr == 0; }
__check_singular_aux() [1/2]
bool __gnu_debug::__check_singular_aux (const _Safe_iterator_base * __x) inline
Iterators that derive from _Safe_iterator_base but that aren't _Safe_iterators can be determined singular or non-singular via _Safe_iterator_base.
Definition at line 62 of file safe_iterator.h.
   { return __x->_M_singular(); }
References __gnu_debug::_Safe_iterator_base::_M_singular().
__check_singular_aux() [2/2]
bool __gnu_debug::__check_singular_aux (const void *) inline
Definition at line 45 of file functions.h.
 { return false; }
Referenced by __check_singular().
__check_sorted() [1/2]
template<typename _InputIterator > bool __gnu_debug::__check_sorted (const _InputIterator & __first, const _InputIterator & __last) inline
Definition at line 239 of file functions.h.
     {
       typedef typename std::iterator_traits<_InputIterator>::iterator_category
         _Category;
       // Verify that the < operator for elements in the sequence is a
       // StrictWeakOrdering by checking that it is irreflexive.
       __glibcxx_assert(__first == __last || !(*__first < *__first));
       return __check_sorted_aux(__first, __last, _Category());
     }
References __check_sorted_aux().
Referenced by __check_sorted_set_aux().
__check_sorted() [2/2]
template<typename _InputIterator , typename _Predicate > bool __gnu_debug::__check_sorted (const _InputIterator & __first, const _InputIterator & __last, _Predicate __pred) inline
Definition at line 253 of file functions.h.
     {
       typedef typename std::iterator_traits<_InputIterator>::iterator_category
         _Category;
       // Verify that the predicate is StrictWeakOrdering by checking that it
       // is irreflexive.
       __glibcxx_assert(__first == __last || !__pred(*__first, *__first));
       return __check_sorted_aux(__first, __last, __pred, _Category());
     }
References __check_sorted_aux().
__check_sorted_aux() [1/4]
template<typename _ForwardIterator , typename _Predicate > bool __gnu_debug::__check_sorted_aux (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, std::forward_iterator_tag) inline
Definition at line 222 of file functions.h.
     {
       if (__first == __last)
         return true;
       _ForwardIterator __next = __first;
       for (++__next; __next != __last; __first = __next, ++__next)
         if (__pred(*__next, *__first))
           return false;
       return true;
     }
__check_sorted_aux() [2/4]
template<typename _ForwardIterator > bool __gnu_debug::__check_sorted_aux (_ForwardIterator __first, _ForwardIterator __last, std::forward_iterator_tag) inline
Definition at line 196 of file functions.h.
     {
       if (__first == __last)
         return true;
       _ForwardIterator __next = __first;
       for (++__next; __next != __last; __first = __next, ++__next)
         if (*__next < *__first)
           return false;
       return true;
     }
__check_sorted_aux() [3/4]
template<typename _InputIterator , typename _Predicate > bool __gnu_debug::__check_sorted_aux (const _InputIterator & , const _InputIterator & , _Predicate , std::input_iterator_tag) inline
Definition at line 214 of file functions.h.
     { return true; }
__check_sorted_aux() [4/4]
template<typename _InputIterator > bool __gnu_debug::__check_sorted_aux (const _InputIterator & , const _InputIterator & , std::input_iterator_tag) inline
Definition at line 188 of file functions.h.
     { return true; }
Referenced by __check_sorted().
__check_sorted_set() [1/2]
template<typename _InputIterator1 , typename _InputIterator2 > bool __gnu_debug::__check_sorted_set (const _InputIterator1 & __first, const _InputIterator1 & __last, const _InputIterator2 &) inline
Definition at line 297 of file functions.h.
     {
       typedef typename std::iterator_traits<_InputIterator1>::value_type
     _ValueType1;
       typedef typename std::iterator_traits<_InputIterator2>::value_type
     _ValueType2;
       typedef typename std::__are_same<_ValueType1, _ValueType2>::__type
     _SameType;
       return __check_sorted_set_aux(__first, __last, _SameType());
     }
References __check_sorted_set_aux().
__check_sorted_set() [2/2]
template<typename _InputIterator1 , typename _InputIterator2 , typename _Predicate > bool __gnu_debug::__check_sorted_set (const _InputIterator1 & __first, const _InputIterator1 & __last, const _InputIterator2 & , _Predicate __pred) inline
Definition at line 314 of file functions.h.
     {
       typedef typename std::iterator_traits<_InputIterator1>::value_type
     _ValueType1;
       typedef typename std::iterator_traits<_InputIterator2>::value_type
     _ValueType2;
       typedef typename std::__are_same<_ValueType1, _ValueType2>::__type
     _SameType;
       return __check_sorted_set_aux(__first, __last, __pred, _SameType());
    }
References __check_sorted_set_aux().
__check_sorted_set_aux() [1/4]
template<typename _InputIterator , typename _Predicate > bool __gnu_debug::__check_sorted_set_aux (const _InputIterator & , const _InputIterator & , _Predicate , std::__false_type) inline
Definition at line 289 of file functions.h.
     { return true; }
__check_sorted_set_aux() [2/4]
template<typename _InputIterator > bool __gnu_debug::__check_sorted_set_aux (const _InputIterator & , const _InputIterator & , std::__false_type) inline
Definition at line 275 of file functions.h.
     { return true; }
__check_sorted_set_aux() [3/4]
template<typename _InputIterator , typename _Predicate > bool __gnu_debug::__check_sorted_set_aux (const _InputIterator & __first, const _InputIterator & __last, _Predicate __pred, std::__true_type) inline
Definition at line 282 of file functions.h.
     { return __check_sorted(__first, __last, __pred); }
References __check_sorted().
__check_sorted_set_aux() [4/4]
template<typename _InputIterator > bool __gnu_debug::__check_sorted_set_aux (const _InputIterator & __first, const _InputIterator & __last, std::__true_type) inline
Definition at line 268 of file functions.h.
     { return __check_sorted(__first, __last); }
References __check_sorted().
Referenced by __check_sorted_set().
__check_string() [1/2]
template<typename _CharT > const _CharT* __gnu_debug::__check_string (const _CharT * __s) inline
Checks that __s is non-NULL and then returns __s.
Definition at line 176 of file functions.h.
     {
 #ifdef _GLIBCXX_DEBUG_PEDANTIC
       __glibcxx_assert(__s != 0);
 #endif
       return __s;
     }
__check_string() [2/2]
template<typename _CharT , typename _Integer > const _CharT* __gnu_debug::__check_string (const _CharT * __s, const _Integer &__n __attribute__(__unused__)) inline
Checks that __s is non-NULL or __n == 0, and then returns __s.
Definition at line 164 of file functions.h.
     {
 #ifdef _GLIBCXX_DEBUG_PEDANTIC
       __glibcxx_assert(__s != 0 || __n == 0);
 #endif
       return __s;
     }
__check_valid_range()
template<typename _InputIterator > _InputIterator __gnu_debug::__check_valid_range (const _InputIterator & __first, const _InputIterator &__last __attribute__(__unused__)) inline
Definition at line 153 of file functions.h.
     {
       __glibcxx_check_valid_range(__first, __last);
       return __first;
     }
References __glibcxx_check_valid_range.
Referenced by _GLIBCXX_VISIBILITY().
__valid_range() [1/2]
template<typename _InputIterator > bool __gnu_debug::__valid_range (const _InputIterator & __first, const _InputIterator & __last) inline
Don't know what these iterators are, or if they are even iterators (we may get an integral type for InputIterator), so see if they are integral and pass them on to the next phase otherwise.
Definition at line 134 of file functions.h.
     {
       typedef typename std::__is_integer<_InputIterator>::__type _Integral;
       return __valid_range_aux(__first, __last, _Integral());
     }
References __valid_range_aux().
__valid_range() [2/2]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::__valid_range (const _Safe_iterator< _Iterator, _Sequence > & __first, const _Safe_iterator< _Iterator, _Sequence > & __last) inline
Safe iterators know how to check if they form a valid range.
Definition at line 143 of file functions.h.
     { return __first._M_valid_range(__last); }
References __gnu_debug::_Safe_iterator< _Iterator, _Sequence >::_M_valid_range().
__valid_range_aux() [1/2]
template<typename _InputIterator > bool __gnu_debug::__valid_range_aux (const _InputIterator & __first, const _InputIterator & __last, std::__false_type) inline
We have iterators, so figure out what kind of iterators that are to see if we can check the range ahead of time.
Definition at line 119 of file functions.h.
   {
     typedef typename std::iterator_traits<_InputIterator>::iterator_category
       _Category;
     return __valid_range_aux2(__first, __last, _Category());
   }
References __valid_range_aux2().
__valid_range_aux() [2/2]
template<typename _Integral > bool __gnu_debug::__valid_range_aux (const _Integral & , const _Integral & , std::__true_type) inline
We say that integral types for a valid range, and defer to other routines to realize what to do with integral types instead of iterators.
Definition at line 111 of file functions.h.
     { return true; }
Referenced by __valid_range().
__valid_range_aux2() [1/2]
template<typename _InputIterator > bool __gnu_debug::__valid_range_aux2 (const _InputIterator & , const _InputIterator & , std::input_iterator_tag) inline
Can't test for a valid range with input iterators, because iteration may be destructive.
So we just assume that the range is valid.
Definition at line 101 of file functions.h.
     { return true; }
__valid_range_aux2() [2/2]
template<typename _RandomAccessIterator > bool __gnu_debug::__valid_range_aux2 (const _RandomAccessIterator & __first, const _RandomAccessIterator & __last, std::random_access_iterator_tag) inline
If the distance between two random access iterators is nonnegative, assume the range is valid.
Definition at line 90 of file functions.h.
     { return __last - __first >= 0; }
Referenced by __valid_range_aux().
operator!=() [1/2]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::operator!= (const _Safe_iterator< _Iterator, _Sequence > & __lhs, const _Safe_iterator< _Iterator, _Sequence > & __rhs) inline
Definition at line 471 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_compare_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_compare_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() != __rhs.base();
     }
References __msg_compare_different, __msg_iter_compare_bad, and _GLIBCXX_DEBUG_VERIFY.
operator!=() [2/2]
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool __gnu_debug::operator!= (const _Safe_iterator< _IteratorL, _Sequence > & __lhs, const _Safe_iterator< _IteratorR, _Sequence > & __rhs) inline
Definition at line 455 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_compare_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_compare_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() != __rhs.base();
     }
References __msg_compare_different, __msg_iter_compare_bad, and _GLIBCXX_DEBUG_VERIFY.
operator+()
template<typename _Iterator , typename _Sequence > _Safe_iterator<_Iterator, _Sequence> __gnu_debug::operator+ (typename _Safe_iterator< _Iterator, _Sequence >::difference_type __n, const _Safe_iterator< _Iterator, _Sequence > & __i) inline
Definition at line 651 of file safe_iterator.h.
     { return __i + __n; }
operator-() [1/2]
template<typename _Iterator , typename _Sequence > _Safe_iterator<_Iterator, _Sequence>::difference_type __gnu_debug::operator- (const _Safe_iterator< _Iterator, _Sequence > & __lhs, const _Safe_iterator< _Iterator, _Sequence > & __rhs) inline
Definition at line 635 of file safe_iterator.h.
      {
        _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                  _M_message(__msg_distance_bad)
                  ._M_iterator(__lhs, "lhs")
                  ._M_iterator(__rhs, "rhs"));
        _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                  _M_message(__msg_distance_different)
                  ._M_iterator(__lhs, "lhs")
                  ._M_iterator(__rhs, "rhs"));
        return __lhs.base() - __rhs.base();
      }
References __msg_distance_bad, __msg_distance_different, and _GLIBCXX_DEBUG_VERIFY.
operator-() [2/2]
template<typename _IteratorL , typename _IteratorR , typename _Sequence > _Safe_iterator<_IteratorL, _Sequence>::difference_type __gnu_debug::operator- (const _Safe_iterator< _IteratorL, _Sequence > & __lhs, const _Safe_iterator< _IteratorR, _Sequence > & __rhs) inline
Definition at line 619 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_distance_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_distance_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() - __rhs.base();
     }
References __msg_distance_bad, __msg_distance_different, and _GLIBCXX_DEBUG_VERIFY.
operator<() [1/2]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::operator< (const _Safe_iterator< _Iterator, _Sequence > & __lhs, const _Safe_iterator< _Iterator, _Sequence > & __rhs) inline
Definition at line 503 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_order_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_order_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() < __rhs.base();
     }
References __msg_iter_order_bad, __msg_order_different, and _GLIBCXX_DEBUG_VERIFY.
operator<() [2/2]
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool __gnu_debug::operator< (const _Safe_iterator< _IteratorL, _Sequence > & __lhs, const _Safe_iterator< _IteratorR, _Sequence > & __rhs) inline
Definition at line 487 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_order_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_order_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() < __rhs.base();
     }
References __msg_iter_order_bad, __msg_order_different, and _GLIBCXX_DEBUG_VERIFY.
Referenced by _GLIBCXX_VISIBILITY().
operator<=() [1/2]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::operator<= (const _Safe_iterator< _Iterator, _Sequence > & __lhs, const _Safe_iterator< _Iterator, _Sequence > & __rhs) inline
Definition at line 535 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_order_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_order_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() <= __rhs.base();
     }
References __msg_iter_order_bad, __msg_order_different, and _GLIBCXX_DEBUG_VERIFY.
operator<=() [2/2]
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool __gnu_debug::operator<= (const _Safe_iterator< _IteratorL, _Sequence > & __lhs, const _Safe_iterator< _IteratorR, _Sequence > & __rhs) inline
Definition at line 519 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_order_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_order_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() <= __rhs.base();
     }
References __msg_iter_order_bad, __msg_order_different, and _GLIBCXX_DEBUG_VERIFY.
Referenced by _GLIBCXX_VISIBILITY().
operator==() [1/2]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::operator== (const _Safe_iterator< _Iterator, _Sequence > & __lhs, const _Safe_iterator< _Iterator, _Sequence > & __rhs) inline
Definition at line 439 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_compare_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_compare_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() == __rhs.base();
     }
References __msg_compare_different, __msg_iter_compare_bad, and _GLIBCXX_DEBUG_VERIFY.
operator==() [2/2]
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool __gnu_debug::operator== (const _Safe_iterator< _IteratorL, _Sequence > & __lhs, const _Safe_iterator< _IteratorR, _Sequence > & __rhs) inline
Definition at line 423 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_compare_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_compare_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() == __rhs.base();
     }
References __msg_compare_different, __msg_iter_compare_bad, and _GLIBCXX_DEBUG_VERIFY.
operator>() [1/2]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::operator> (const _Safe_iterator< _Iterator, _Sequence > & __lhs, const _Safe_iterator< _Iterator, _Sequence > & __rhs) inline
Definition at line 567 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_order_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_order_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() > __rhs.base();
     }
References __msg_iter_order_bad, __msg_order_different, and _GLIBCXX_DEBUG_VERIFY.
operator>() [2/2]
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool __gnu_debug::operator> (const _Safe_iterator< _IteratorL, _Sequence > & __lhs, const _Safe_iterator< _IteratorR, _Sequence > & __rhs) inline
Definition at line 551 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_order_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_order_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() > __rhs.base();
     }
References __msg_iter_order_bad, __msg_order_different, and _GLIBCXX_DEBUG_VERIFY.
Referenced by _GLIBCXX_VISIBILITY().
operator>=() [1/2]
template<typename _Iterator , typename _Sequence > bool __gnu_debug::operator>= (const _Safe_iterator< _Iterator, _Sequence > & __lhs, const _Safe_iterator< _Iterator, _Sequence > & __rhs) inline
Definition at line 599 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_order_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_order_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() >= __rhs.base();
     }
References __msg_iter_order_bad, __msg_order_different, and _GLIBCXX_DEBUG_VERIFY.
operator>=() [2/2]
template<typename _IteratorL , typename _IteratorR , typename _Sequence > bool __gnu_debug::operator>= (const _Safe_iterator< _IteratorL, _Sequence > & __lhs, const _Safe_iterator< _IteratorR, _Sequence > & __rhs) inline
Definition at line 583 of file safe_iterator.h.
     {
       _GLIBCXX_DEBUG_VERIFY(! __lhs._M_singular() && ! __rhs._M_singular(),
                 _M_message(__msg_iter_order_bad)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       _GLIBCXX_DEBUG_VERIFY(__lhs._M_can_compare(__rhs),
                 _M_message(__msg_order_different)
                 ._M_iterator(__lhs, "lhs")
                 ._M_iterator(__rhs, "rhs"));
       return __lhs.base() >= __rhs.base();
     }
References __msg_iter_order_bad, __msg_order_different, and _GLIBCXX_DEBUG_VERIFY.
Referenced by _GLIBCXX_VISIBILITY().