ZEQ2-Lite: Game/CGame/cg_music.h File Reference
cg_music.h File Reference
Data Structures
struct musicSystem
Macros
#define MUSICTYPES 10
Enumerations
enum trackTypes {
battle, idle, idleWater, idleDanger,
struggle, standoff, standoffDanger, victoryGood,
victoryEvil, transform
}
Functions
void CG_CheckMusic (void)
void CG_FadeNext (void)
int CG_GetMilliseconds (char *)
void CG_NextTrack (void)
void CG_ParsePlaylist (void)
void CG_PlayTransformTrack (void)
void CG_StartMusic (void)
Macro Definition Documentation
MUSICTYPES
#define MUSICTYPES 10
Definition at line 1 of file cg_music.h.
Enumeration Type Documentation
trackTypes
enum trackTypes
Enumerator
battle
idle
idleWater
idleDanger
struggle
standoff
standoffDanger
victoryGood
victoryEvil
transform
Definition at line 18 of file cg_music.h.
              {
     battle,
     idle,
     idleWater,
     idleDanger,
     struggle,
     standoff,
     standoffDanger,
     victoryGood,
     victoryEvil,
     transform
 }trackTypes;
Function Documentation
CG_CheckMusic()
void CG_CheckMusic (void)
Definition at line 2 of file cg_music.c.
{
     playerState_t *ps;
     clientInfo_t *ci;
     tierConfig_cg *tier;
     ps = &cg.predictedPlayerState;
     ci = &cgs.clientinfo[ps->clientNum];
     tier = &ci->tierConfig[ci->tierCurrent];
     if(!cgs.music.started){
         CG_StartMusic();
     }
     if(ps->bitFlags & isTransforming){
         if(cgs.music.currentType != 9){
             char var[8];
             cgs.music.currentType = 9;
             if(tier->transformMusic[0]){
                 CG_PlayTransformTrack();
             }
             else{
                 CG_NextTrack();
             }
             trap_Cvar_VariableStringBuffer("cg_playTransformTrackToEnd", var, sizeof(var));
             if(atoi(var)){
                 cgs.music.playToEnd = qtrue;
             }
         }
     }
     else if(ps->bitFlags & isStruggling){
         if(cgs.music.currentType != 4){
             cgs.music.currentType = 4;
             CG_NextTrack();
         }
     }
     else if(!(ps->bitFlags & isUnsafe)){
         if(ps->bitFlags & isTargeted || ps->lockedTarget > 0){
             if(ps->powerLevel[plHealth] < (ps->powerLevel[plMaximum] * 0.4)){
                 if(cgs.music.currentType != 6){
                     cgs.music.currentType = 6;
                     CG_NextTrack();
                 }
             }
             else if(cgs.music.currentType != 5){
                 cgs.music.currentType = 5;
                 CG_NextTrack();
             }
         }
         else{
             if(ps->powerLevel[plHealth] < (ps->powerLevel[plMaximum] * 0.4)){
                 if(cgs.music.currentType != 3){
                     cgs.music.currentType = 3;
                     CG_FadeNext();
                 }
             }
             else if(ps->bitFlags & underWater){
                 if(cgs.music.currentType != 2){
                     cgs.music.currentType = 2;
                     CG_NextTrack();
                 }
             }
             else if(cgs.music.currentType != 1){
                 cgs.music.currentType = 1;
                 CG_FadeNext();
             }
         }
     }
     else if(cgs.music.currentType != 0){
         cgs.music.currentType = 0;
         CG_NextTrack();
     }
     if(cg.time > cgs.music.endTime){
         int difference = (cg.time - cgs.music.endTime);
         float percent = 0.0;
         if(difference < cgs.music.fadeAmount){
             percent = 1.0 - ((float)difference / (float)cgs.music.fadeAmount);
             trap_Cvar_Set("s_musicvolume",va("%f",percent * cg_music.value));
         }
         else{
             cgs.music.fading = qfalse;
             cgs.music.playToEnd = qfalse;
             CG_NextTrack();
         }
     }
 }
References atoi(), cg, CG_FadeNext(), cg_music, CG_NextTrack(), CG_PlayTransformTrack(), CG_StartMusic(), cgs, cgs_t::clientinfo, musicSystem::currentType, musicSystem::endTime, musicSystem::fadeAmount, musicSystem::fading, isStruggling, isTargeted, isTransforming, isUnsafe, cgs_t::music, musicSystem::playToEnd, plHealth, plMaximum, cg_t::predictedPlayerState, qfalse, qtrue, musicSystem::started, clientInfo_t::tierConfig, clientInfo_t::tierCurrent, cg_t::time, tierConfig_cg::transformMusic, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), underWater, va(), and vmCvar_t::value.
Referenced by CG_DrawActiveFrame().
CG_FadeNext()
void CG_FadeNext (void)
Definition at line 169 of file cg_music.c.
                       {
     if(!cgs.music.playToEnd){
         cgs.music.fading = qtrue;
         cgs.music.endTime = cg.time;
     }
 }
References cg, cgs, musicSystem::endTime, musicSystem::fading, cgs_t::music, musicSystem::playToEnd, qtrue, and cg_t::time.
Referenced by CG_CheckMusic().
CG_GetMilliseconds()
int CG_GetMilliseconds (char *)
Definition at line 85 of file cg_music.c.
{
     int index,compareIndex;
     int amount;
     char current[8];
     int i;
     index = 0;
     compareIndex = 0;
     amount = 0;
     while(1){
         if(index > Q_PrintStrlen(time)){break;}
         current[compareIndex] = time[index];
         if(strcmp(&current[index],":") == 0){
             amount += atoi(current) * 60 * 1000;
             compareIndex = -1;
             memset(current,0,8);
         }
         ++index;
         ++compareIndex;
     }
     amount += atoi(current) * 1000;
     return amount;
 }
References atoi(), current, memset(), Q_PrintStrlen(), strcmp(), and time().
Referenced by CG_ParsePlaylist(), and parseTier().
CG_NextTrack()
void CG_NextTrack (void)
Definition at line 175 of file cg_music.c.
{
     int nextIndex;
     int typeSize;
     char *path;
     int i;
     int duration;
     if(cgs.music.fading || cgs.music.playToEnd){return;}
     typeSize = cgs.music.typeSize[cgs.music.currentType];
     nextIndex = (cgs.music.currentIndex + 1 < typeSize) ? cgs.music.currentIndex + 1 : 0;
     if(cgs.music.random){
         nextIndex = fabs(crandom()) * typeSize;
     }
     if(nextIndex == cgs.music.lastTrack[cgs.music.currentType]){nextIndex += 1;}
     if(nextIndex < 0){nextIndex = typeSize-1;}
     if(nextIndex >= typeSize){nextIndex = 0;}
     path = va("music/%s",cgs.music.playlist[cgs.music.currentType][nextIndex]);
     duration = cgs.music.trackLength[cgs.music.currentType][nextIndex];
     //CG_Printf("Playing type %i | track %i.  Next track in %i seconds.\n",cgs.music.currentType,nextIndex,duration/1000);
     if(duration > 300000){duration = 300000;}
     cgs.music.endTime = cg.time + duration - cgs.music.fadeAmount;
     cgs.music.lastTrack[cgs.music.currentType] = nextIndex;
     trap_S_StartBackgroundTrack(path,path);
     trap_Cvar_Set("s_musicvolume",va("%f",cg_music.value));
 }
References cg, cg_music, cgs, crandom, musicSystem::currentIndex, musicSystem::currentType, musicSystem::endTime, fabs(), musicSystem::fadeAmount, musicSystem::fading, musicSystem::lastTrack, cgs_t::music, musicSystem::playlist, musicSystem::playToEnd, musicSystem::random, cg_t::time, musicSystem::trackLength, trap_Cvar_Set(), trap_S_StartBackgroundTrack(), musicSystem::typeSize, va(), and vmCvar_t::value.
Referenced by CG_CheckMusic().
CG_ParsePlaylist()
void CG_ParsePlaylist (void)
Definition at line 107 of file cg_music.c.
{
     fileHandle_t playlist;
     char *token,*parse,*name;
     char first,last;
     int trackIndex,typeIndex;
     int fileLength;
     char fileContents[32000];
     //char *strdup(const char *);
     trackIndex = 0;
     typeIndex = -1;
     cgs.music.currentIndex = -1;
     cgs.music.fadeAmount = 0;
     cgs.music.started = qtrue;
     cgs.music.random = qfalse;
     if(trap_FS_FOpenFile("music/playlist.cfg",0,FS_READ)>0){
         fileLength = trap_FS_FOpenFile("music/playlist.cfg",&playlist,FS_READ);
         trap_FS_Read(fileContents,fileLength,playlist);
         fileContents[fileLength] = 0;
         trap_FS_FCloseFile(playlist);
         parse = fileContents;
         while(1){
             token = COM_Parse(&parse);
             if(!token[0]){break;}
             first = token[0];
             last = token[Q_PrintStrlen(token)-1];
             last = *(va("%c",last));  // Psyco Fix?!
             if(!Q_stricmp(token,"type")){
                 token = COM_Parse(&parse);
                 if(!token[0]){break;}
                 if(!Q_stricmp(token,"random")){
                     cgs.music.random = qtrue;
                 }
             }
             else if(!Q_stricmp(token,"fade")){
                 token = COM_Parse(&parse);
                 if(!token[0]){break;}
                 cgs.music.fadeAmount = CG_GetMilliseconds(token);
             }
             else if(strcmp(&last,"{") == 0){
                 cgs.music.lastTrack[typeIndex] = -1;
                 ++typeIndex;
                 //CG_Printf("Music Type [%i]\n",typeIndex);
             }
             else if(strcmp(&first,"}") == 0){
                 cgs.music.typeSize[typeIndex] = trackIndex;
                 trackIndex = 0;
             }
             else{
                 static char temp[16][32][256];
                 strncpy(temp[typeIndex][trackIndex],token,256-1);
                 cgs.music.playlist[typeIndex][trackIndex] = temp[typeIndex][trackIndex];
                 cgs.music.trackLength[typeIndex][trackIndex] = CG_GetMilliseconds(COM_Parse(&parse));
                 //cgs.music.hasPlayed[typeIndex][trackIndex] = qfalse;
                 //CG_Printf("  Track %i is %i seconds\n",trackIndex,cgs.music.trackLength[typeIndex][trackIndex]/1000);
                 ++trackIndex;
             }
         }
     }
 }
References CG_GetMilliseconds(), cgs, COM_Parse(), musicSystem::currentIndex, musicSystem::fadeAmount, FS_READ, musicSystem::lastTrack, cgs_t::music, musicSystem::playlist, Q_PrintStrlen(), Q_stricmp(), qfalse, qtrue, musicSystem::random, musicSystem::started, strcmp(), strncpy(), token, musicSystem::trackLength, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), musicSystem::typeSize, and va().
Referenced by CG_StartMusic().
CG_PlayTransformTrack()
void CG_PlayTransformTrack (void)
Definition at line 199 of file cg_music.c.
{
     playerState_t   *ps;
     clientInfo_t    *ci;
     tierConfig_cg   *tier;
     char    *path;
     int     duration;
     ps = &cg.predictedPlayerState;
     ci = &cgs.clientinfo[ps->clientNum];
     tier = &ci->tierConfig[ci->tierCurrent];
     path = va("music/%s",tier->transformMusic);
     duration = tier->transformMusicLength;
     if(duration > 300000){duration = 300000;}
     cgs.music.endTime = cg.time + duration - cgs.music.fadeAmount;
     trap_S_StartBackgroundTrack(path,path);
     trap_Cvar_Set("s_musicvolume",va("%f",cg_music.value));
 }
References cg, cg_music, cgs, cgs_t::clientinfo, musicSystem::endTime, musicSystem::fadeAmount, cgs_t::music, cg_t::predictedPlayerState, clientInfo_t::tierConfig, clientInfo_t::tierCurrent, cg_t::time, tierConfig_cg::transformMusic, tierConfig_cg::transformMusicLength, trap_Cvar_Set(), trap_S_StartBackgroundTrack(), va(), and vmCvar_t::value.
Referenced by CG_CheckMusic().
CG_StartMusic()
void CG_StartMusic (void)
Definition at line 166 of file cg_music.c.
{
     CG_ParsePlaylist();
 }
References CG_ParsePlaylist().
Referenced by CG_CheckMusic().