ZEQ2-Lite: Source/Engine/tools/lcc/src/types.c File Reference
types.c File Reference
#include "c.h"
#include <float.h>
Data Structures
struct entry
Macros
#define xx(name)
#define xx(name, type)
#define xx(t) if (ty->size == t->size) return t
#define xx(ty) if (size == (ty)->size) return ty;
#define xx(v, name, op, metrics) v=xxinit(op,name,IR->metrics)
#define xx(v, t) if (v==NULL && t->size==voidptype->size && t->align==voidptype->align) v=t
Functions
Type array (Type ty, int n, int a)
Type atop (Type ty)
Type btot (int op, int size)
Type compose (Type ty1, Type ty2)
Type deref (Type ty)
int eqtype (Type ty1, Type ty2, int ret)
Field fieldlist (Type ty)
Field fieldref (const char *name, Type ty)
Type freturn (Type ty)
Type ftype (Type rty, Type ty)
Type func (Type ty, Type *proto, int style)
int hasproto (Type ty)
static Field isfield (const char *, Field)
Field newfield (char *name, Type ty, Type fty)
Type newstruct (int op, char *tag)
void outtype (Type ty, FILE *f)
void printdecl (Symbol p, Type ty)
void printproto (Symbol p, Symbol callee[])
void printtype (Type ty, int fd)
Type promote (Type ty)
static void prtype (Type ty, FILE *f, int indent, unsigned mark)
Type ptr (Type ty)
Type qual (int op, Type ty)
void rmtypes (int lev)
Type signedint (Type ty)
int ttob (Type ty)
static Type type (int, Type, int, int, void *)
void type_init (int argc, char *argv[])
char * typestring (Type ty, char *str)
int variadic (Type ty)
static Type xxinit (int op, char *name, Metrics m)
Variables
Type charptype
Type chartype
Type doubletype
Type floattype
Type funcptype
Type inttype
Type longdouble
Type longlong
Type longtype
static int maxlevel
static Symbol pointersym
Type shorttype
Type signedchar
Type signedptr
static struct entry * typetable [128]
Type unsignedchar
Type unsignedlong
Type unsignedlonglong
Type unsignedptr
Type unsignedshort
Type unsignedtype
Type voidptype
Type voidtype
Type widechar
Macro Definition Documentation
xx [1/6]
#define xx (name)
Value:
        else if (sscanf(argv[i], "-" #name "=%d,%d,%d", &size, &align, &outofline) == 3) { \
            IR->name.size = size; IR->name.align = align; \
            IR->name.outofline = outofline; }
xx [2/6]
#define xx (name, type)
Value:
        if (strcmp(argv[i], "-wchar_t=" #name) == 0) \
            widechar = type;
xx [3/6]
#define xx (t) if (ty->size == t->size) return t
xx [4/6]
#define xx (ty) if (size == (ty)->size) return ty;
xx [5/6]
#define xx (v, name, op, metrics) v=xxinit(op,name,IR->metrics)
xx [6/6]
#define xx (v, t) if (v==NULL && t->size==voidptype->size && t->align==voidptype->align) v=t
Function Documentation
array()
Type array (Type ty, int n, int a)
Definition at line 202 of file types.c.
{
     assert(ty);
     if (isfunc(ty)) {
         error("illegal type `array of %t'\n", ty);
         return array(inttype, n, 0);
     }
     if (isarray(ty) && ty->size == 0)
         error("missing array size\n");
     if (ty->size == 0) {
         if (unqual(ty) == voidtype)
             error("illegal type `array of %t'\n", ty);
         else if (Aflag >= 2)
             warning("declaring type array of %t' is undefined\n", ty);
     } else if (n > INT_MAX/ty->size) {
         error("size of `array of %t' exceeds %d bytes\n",
             ty, INT_MAX);
         n = 1;
     }
     return type(ARRAY, ty, n*ty->size,
         a ? a : ty->align, NULL);
 }
References Aflag, error(), INT_MAX, inttype, isarray, isfunc, NULL, type(), unqual, voidtype, and warning().
Referenced by bbcall(), bbentry(), bbvars(), compose(), dcllocal(), dclr(), doglobal(), field(), gettok(), initializer(), ltov(), mkstr(), prof_init(), and swcode().
atop()
Type atop (Type ty)
Definition at line 224 of file types.c.
                    {
     if (isarray(ty))
         return ptr(ty->type);
     error("type error: %s\n", "array expected");
     return ptr(ty);
 }
References error(), isarray, and ptr().
Referenced by consttree(), cvtconst(), dclparam(), nullcall(), and pointer().
btot()
Type btot (int op, int size)
Definition at line 447 of file types.c.
{
 #define xx(ty) if (size == (ty)->size) return ty;
     switch (optype(op)) {
     case F:
         xx(floattype);
         xx(doubletype);
         xx(longdouble);
         assert(0); return 0;
     case I:
         if (chartype->op == INT)
             xx(chartype);
         xx(signedchar);
         xx(shorttype);
         xx(inttype);
         xx(longtype);
         xx(longlong);
         assert(0); return 0;
     case U:
         if (chartype->op == UNSIGNED)
             xx(chartype);
         xx(unsignedchar);
         xx(unsignedshort);
         xx(unsignedtype);
         xx(unsignedlong);
         xx(unsignedlonglong);
         assert(0); return 0;
     case P:
         xx(voidptype);
         xx(funcptype);
         assert(0); return 0;
     }
 #undef xx
     assert(0); return 0;
 }
References chartype, doubletype, F, floattype, funcptype, I, INT, inttype, longdouble, longlong, longtype, op, optype, P, shorttype, signedchar, U, unsignedchar, unsignedlong, unsignedlonglong, unsignedshort, unsignedtype, voidptype, and xx.
Referenced by newtemp(), and visit().
compose()
Type compose (Type ty1, Type ty2)
Definition at line 390 of file types.c.
{
     if (ty1 == ty2)
         return ty1;
     assert(ty1->op == ty2->op);
     switch (ty1->op) {
     case POINTER:
         return ptr(compose(ty1->type, ty2->type));
     case CONST+VOLATILE:
         return qual(CONST, qual(VOLATILE,
             compose(ty1->type, ty2->type)));
     case CONST: case VOLATILE:
         return qual(ty1->op, compose(ty1->type, ty2->type));
     case ARRAY:    { Type ty = compose(ty1->type, ty2->type);
              if (ty1->size && ((ty1->type->size && ty2->size == 0) || ty1->size == ty2->size))
                 return array(ty, ty1->size/ty1->type->size, ty1->align);
              if (ty2->size && ty2->type->size && ty1->size == 0)
                 return array(ty, ty2->size/ty2->type->size, ty2->align);
              return array(ty, 0, 0);    }
     case FUNCTION: { Type *p1  = ty1->u.f.proto, *p2 = ty2->u.f.proto;
              Type ty   = compose(ty1->type, ty2->type);
              List tlist = NULL;
              if (p1 == NULL && p2 == NULL)
                 return func(ty, NULL, 1);
              if (p1 && p2 == NULL)
                 return func(ty, p1, ty1->u.f.oldstyle);
              if (p2 && p1 == NULL)
                 return func(ty, p2, ty2->u.f.oldstyle);
              for ( ; *p1 && *p2; p1++, p2++) {
                 Type ty = compose(unqual(*p1), unqual(*p2));
                 if (isconst(*p1)    || isconst(*p2))
                     ty = qual(CONST, ty);
                 if (isvolatile(*p1) || isvolatile(*p2))
                     ty = qual(VOLATILE, ty);
                 tlist = append(ty, tlist);
              }
              assert(*p1 == NULL && *p2 == NULL);
              return func(ty, ltov(&tlist, PERM), 0); }
     }
     assert(0); return NULL;
 }
References append(), array(), func(), isconst, isvolatile, ltov(), NULL, p1, p2, PERM, ptr(), qual(), and unqual.
deref()
Type deref (Type ty)
Definition at line 195 of file types.c.
                     {
     if (isptr(ty))
         ty = ty->type;
     else
         error("type error: %s\n", "pointer expected");
     return isenum(ty) ? unqual(ty)->type : ty;
 }
References error(), isenum, isptr, and unqual.
Referenced by field(), and rvalue().
eqtype()
int eqtype (Type ty1, Type ty2, int ret)
Definition at line 312 of file types.c.
{
     if (ty1 == ty2)
         return 1;
     if (ty1->op != ty2->op)
         return 0;
     switch (ty1->op) {
     case ENUM: case UNION: case STRUCT:
     case UNSIGNED: case INT: case FLOAT:
         return 0;
     case POINTER:  return eqtype(ty1->type, ty2->type, 1);
     case VOLATILE: case CONST+VOLATILE:
     case CONST:    return eqtype(ty1->type, ty2->type, 1);
     case ARRAY:    if (eqtype(ty1->type, ty2->type, 1)) {
                 if (ty1->size == ty2->size)
                     return 1;
                 if (ty1->size == 0 || ty2->size == 0)
                     return ret;
                }
                return 0;
     case FUNCTION: if (eqtype(ty1->type, ty2->type, 1)) {
                 Type *p1 = ty1->u.f.proto, *p2 = ty2->u.f.proto;
                 if (p1 == p2)
                     return 1;
                 if (p1 && p2) {
                     for ( ; *p1 && *p2; p1++, p2++)
                     if (eqtype(unqual(*p1), unqual(*p2), 1) == 0)
                         return 0;
                 if (*p1 == NULL && *p2 == NULL)
                     return 1;
                 } else {
                     if (variadic(p1 ? ty1 : ty2))
                     return 0;
                 if (p1 == NULL)
                     p1 = p2;
                 for ( ; *p1; p1++) {
                     Type ty = unqual(*p1);
                     if (promote(ty) != (isenum(ty) ? ty->type : ty))
                         return 0;
                 }
                 return 1;
                 }
                }
                return 0;
     }
     assert(0); return 0;
 }
References INT, isenum, NULL, p1, p2, promote(), unqual, and variadic().
Referenced by assign(), compatible(), condtree(), constant(), dclglobal(), dcllocal(), eqtree(), funcdefn(), and primary().
fieldlist()
Field fieldlist (Type ty)
Definition at line 497 of file types.c.
{
     return ty->u.sym->u.s.flist;
 }
fieldref()
Field fieldref (const char * name, Type ty)
Definition at line 502 of file types.c.
{
     Field p = isfield(name, unqual(ty)->u.sym->u.s.flist);
     if (p && xref) {
         Symbol q;
         assert(unqual(ty)->u.sym->u.s.ftab);
         q = lookup(name, unqual(ty)->u.sym->u.s.ftab);
         assert(q);
         use(q, src);
     }
     return p;
 }
References isfield(), lookup(), unqual, use(), and xref.
Referenced by field().
freturn()
Type freturn (Type ty)
Definition at line 256 of file types.c.
                       {
     if (isfunc(ty))
         return ty->type;
     error("type error: %s\n", "function expected");
     return inttype;
 }
References error(), inttype, and isfunc.
Referenced by call(), compound(), funcdefn(), printproto(), retcode(), statement(), tracefinis(), tracereturn(), and vcall().
ftype()
Type ftype (Type rty, Type ty)
Definition at line 516 of file types.c.
{
     List list = append(ty, NULL);
     list = append(voidtype, list);
     return func(rty, ltov(&list, PERM), 0);
 }
References append(), func(), ltov(), NULL, PERM, and voidtype.
Referenced by bbentry(), bbexit(), and trace_init().
func()
Type func (Type ty, Type * proto, int style)
Definition at line 248 of file types.c.
{
     if (ty && (isarray(ty) || isfunc(ty)))
         error("illegal return type `%t'\n", ty);
     ty = type(FUNCTION, ty, 0, 0, NULL);
     ty->u.f.proto = proto;
     ty->u.f.oldstyle = style;
     return ty;
 }
References error(), isarray, isfunc, NULL, and type().
Referenced by attach(), compose(), dclr(), ftype(), funcdefn(), main_init(), postfix(), primary(), printproto(), and type_init().
hasproto()
int hasproto (Type ty)
Definition at line 481 of file types.c.
                       {
     if (ty == 0)
         return 1;
     switch (ty->op) {
     case CONST: case VOLATILE: case CONST+VOLATILE: case POINTER:
     case ARRAY:
         return hasproto(ty->type);
     case FUNCTION:
         return hasproto(ty->type) && ty->u.f.proto;
     case STRUCT: case UNION:
     case VOID:   case FLOAT: case ENUM:  case INT: case UNSIGNED:
         return 1;
     }
     assert(0); return 0;
 }
References INT.
Referenced by decl(), fields(), parameters(), and typename().
isfield()
static Field isfield (const char * name, Field flist) static
Definition at line 524 of file types.c.
{
     for ( ; flist; flist = flist->link)
         if (flist->name == name)
             break;
     return flist;
 }
Referenced by fieldref().
newfield()
Field newfield (char * name, Type ty, Type fty)
Definition at line 292 of file types.c.
{
     Field p, *q = &ty->u.sym->u.s.flist;
     if (name == NULL)
         name = stringd(genlabel(1));
     for (p = *q; p; q = &p->link, p = *q)
         if (p->name == name)
             error("duplicate field name `%s' in `%t'\n",
                 name, ty);
     NEW0(p, PERM);
     *q = p;
     p->name = name;
     p->type = fty;
     if (xref) {                         /* omit */
         if (ty->u.sym->u.s.ftab == NULL)            /* omit */
             ty->u.sym->u.s.ftab = table(NULL, level);   /* omit */
         install(name, &ty->u.sym->u.s.ftab, 0, PERM)->src = src;/* omit */
     }                               /* omit */
     return p;
 }
References error(), genlabel(), install(), NEW0, NULL, PERM, stringd(), and xref.
Referenced by fields().
newstruct()
Type newstruct (int op, char * tag)
Definition at line 271 of file types.c.
{
     Symbol p;
     assert(tag);
     if (*tag == 0)
         tag = stringd(genlabel(1));
     else
         if ((p = lookup(tag, types)) != NULL && (p->scope == level
         || (p->scope == PARAM && level == PARAM+1))) {
             if (p->type->op == op && !p->defined)
                 return p->type;
             error("redefinition of `%s' previously defined at %w\n",
                 p->name, &p->src);
         }
     p = install(tag, &types, level, PERM);
     p->type = type(op, NULL, 0, 0, p);
     if (p->scope > maxlevel)
         maxlevel = p->scope;
     p->src = src;
     return p->type;
 }
References error(), genlabel(), install(), lookup(), maxlevel, NULL, op, PARAM, PERM, stringd(), type(), and types.
Referenced by enumdcl(), and structdcl().
outtype()
void outtype (Type ty, FILE * f)
Definition at line 532 of file types.c.
{
     switch (ty->op) {
     case CONST+VOLATILE: case CONST: case VOLATILE:
         fprint(f, "%k %t", ty->op, ty->type);
         break;
     case STRUCT: case UNION: case ENUM:
         assert(ty->u.sym);
         if (ty->size == 0)
             fprint(f, "incomplete ");
         assert(ty->u.sym->name);
         if (*ty->u.sym->name >= '1' && *ty->u.sym->name <= '9') {
             Symbol p = findtype(ty);
             if (p == 0)
                 fprint(f, "%k defined at %w", ty->op, &ty->u.sym->src);
             else
                 fprint(f, p->name);
         } else {
             fprint(f, "%k %s", ty->op, ty->u.sym->name);
             if (ty->size == 0)
                 fprint(f, " defined at %w", &ty->u.sym->src);
         }
         break;
     case VOID: case FLOAT: case INT: case UNSIGNED:
         fprint(f, ty->u.sym->name);
         break;
     case POINTER:
         fprint(f, "pointer to %t", ty->type);
         break;
     case FUNCTION:
         fprint(f, "%t function", ty->type);
         if (ty->u.f.proto && ty->u.f.proto[0]) {
             int i;
             fprint(f, "(%t", ty->u.f.proto[0]);
             for (i = 1; ty->u.f.proto[i]; i++)
                 if (ty->u.f.proto[i] == voidtype)
                     fprint(f, ",...");
                 else
                     fprint(f, ",%t", ty->u.f.proto[i]);
             fprint(f, ")");
         } else if (ty->u.f.proto && ty->u.f.proto[0] == 0)
             fprint(f, "(void)");
         break;
     case ARRAY:
         if (ty->size > 0 && ty->type && ty->type->size > 0) {
             fprint(f, "array %d", ty->size/ty->type->size);
             while (ty->type && isarray(ty->type) && ty->type->type->size > 0) {
                 ty = ty->type;
                 fprint(f, ",%d", ty->size/ty->type->size);
             }
         } else
             fprint(f, "incomplete array");
         if (ty->type)
             fprint(f, " of %t", ty->type);
         break;
     default: assert(0);
     }
 }
References findtype(), fprint(), INT, isarray, and voidtype.
Referenced by vfprint().
printdecl()
void printdecl (Symbol p, Type ty)
Definition at line 592 of file types.c.
{
     switch (p->sclass) {
     case AUTO:
         fprint(stderr, "%s;\n", typestring(ty, p->name));
         break;
     case STATIC: case EXTERN:
         fprint(stderr, "%k %s;\n", p->sclass, typestring(ty, p->name));
         break;
     case TYPEDEF: case ENUM:
         break;
     default: assert(0);
     }
 }
References EXTERN, fprint(), and typestring().
Referenced by doglobal(), and printproto().
printproto()
void printproto (Symbol p, Symbol callee[])
Definition at line 607 of file types.c.
{
     if (p->type->u.f.proto)
         printdecl(p, p->type);
     else {
         int i;
         List list = 0;
         if (callee[0] == 0)
             list = append(voidtype, list);
         else
             for (i = 0; callee[i]; i++)
                 list = append(callee[i]->type, list);
         printdecl(p, func(freturn(p->type), ltov(&list, PERM), 0));
     }
 }
References append(), freturn(), func(), ltov(), PERM, printdecl(), and voidtype.
Referenced by funcdefn().
printtype()
void printtype (Type ty, int fd)
Definition at line 684 of file types.c.
{
     static unsigned mark;
     prtype(ty, fd == 1 ? stdout : stderr, 0, ++mark);
     fprint(fd == 1 ? stdout : stderr, "\n");
 }
References fprint(), and prtype().
promote()
Type promote (Type ty)
Definition at line 358 of file types.c.
                       {
     ty = unqual(ty);
     switch (ty->op) {
     case ENUM:
         return inttype;
     case INT:
         if (ty->size < inttype->size)
             return inttype;
         break;
     case UNSIGNED:
         if (ty->size < inttype->size)
             return inttype;
         if (ty->size < unsignedtype->size)
             return unsignedtype;
         break;
     case FLOAT:
         if (ty->size < doubletype->size)
             return doubletype;
     }
     return ty;
 }
References doubletype, INT, inttype, unqual, and unsignedtype.
Referenced by addtree(), call(), calltree(), eqtype(), funcdefn(), retcode(), shtree(), subtree(), swstmt(), tracevalue(), and unary().
prtype()
static void prtype (Type ty, FILE * f, int indent, unsigned mark) static
Definition at line 623 of file types.c.
{
     switch (ty->op) {
     default:
         fprint(f, "(%d %d %d [%p])", ty->op, ty->size, ty->align, ty->u.sym);
         break;
     case FLOAT: case INT: case UNSIGNED: case VOID:
         fprint(f, "(%k %d %d [\"%s\"])", ty->op, ty->size, ty->align, ty->u.sym->name);
         break;
     case CONST+VOLATILE: case CONST: case VOLATILE: case POINTER: case ARRAY:
         fprint(f, "(%k %d %d ", ty->op, ty->size, ty->align);
         prtype(ty->type, f, indent+1, mark);
         fprint(f, ")");
         break;
     case STRUCT: case UNION:
         fprint(f, "(%k %d %d [\"%s\"]", ty->op, ty->size, ty->align, ty->u.sym->name);
         if (ty->x.marked != mark) {
             Field p;
             ty->x.marked = mark;
             for (p = ty->u.sym->u.s.flist; p; p = p->link) {
                 fprint(f, "\n%I", indent+1);
                 prtype(p->type, f, indent+1, mark);
                 fprint(f, " %s@%d", p->name, p->offset);
                 if (p->lsb)
                     fprint(f, ":%d..%d",
                         fieldsize(p) + fieldright(p), fieldright(p));
             }
             fprint(f, "\n%I", indent);
         }
         fprint(f, ")");
         break;
     case ENUM:
         fprint(f, "(%k %d %d [\"%s\"]", ty->op, ty->size, ty->align, ty->u.sym->name);
         if (ty->x.marked != mark) {
             int i;
             Symbol *p = ty->u.sym->u.idlist;
             ty->x.marked = mark;
             for (i = 0; p[i] != NULL; i++)
                 fprint(f, "%I%s=%d\n", indent+1, p[i]->name, p[i]->u.value);
         }
         fprint(f, ")");
         break;
     case FUNCTION:
         fprint(f, "(%k %d %d ", ty->op, ty->size, ty->align);
         prtype(ty->type, f, indent+1, mark);
         if (ty->u.f.proto) {
             int i;
             fprint(f, "\n%I{", indent+1);
             for (i = 0; ty->u.f.proto[i]; i++) {
                 if (i > 0)
                     fprint(f, "%I", indent+2);
                 prtype(ty->u.f.proto[i], f, indent+2, mark);
                 fprint(f, "\n");
             }
             fprint(f, "%I}", indent+1);
         }
         fprint(f, ")");
         break;
     }
 }
References fieldright, fieldsize, fprint(), INT, and NULL.
Referenced by printtype().
ptr()
Type ptr (Type ty)
Definition at line 191 of file types.c.
                   {
     return type(POINTER, ty, IR->ptrmetric.size,
         IR->ptrmetric.align, pointersym);
 }
References IR, pointersym, and type().
Referenced by access_virt_barray(), access_virt_sarray(), ArenaServers_Event(), Assemble(), atop(), bbcall(), call(), Camera_MenuEvent(), CG_DrawField(), CG_HeadModelVoiceChats(), CG_ParseVoiceChats(), CG_ServerCommand(), Com_Filter(), Com_QueueEvent(), compose(), compound(), condtree(), ConfirmMenu_Event(), Controls_ActionEvent(), Controls_MenuEvent(), create_colormap(), dclparam(), dclr(), do_barray_io(), do_sarray_io(), DoSyscall(), EmitPtr(), expand_right_edge(), field(), funcdefn(), GLimp_HaveExtension(), idtree(), InGame_Event(), jitter_buffer_ctl(), jzero_far(), lsp_quant(), lsp_weight_quant(), Main_MenuEvent(), Menu_SetCursorToItem(), Music_MenuEvent(), nb_decoder_ctl(), nb_encoder_ctl(), nb_mode_query(), Options_Event(), pitch_gain_search_3tap_vq(), PlayerModel_MenuEvent(), PlayerModel_PicEvent(), pointer(), postfix(), Preferences_Event(), prescan_quantize(), R_Init(), RB_IQMSurfaceAnim(), resampler_basic_direct_double(), resampler_basic_direct_single(), resampler_basic_interpolate_double(), resampler_basic_interpolate_single(), sb_decoder_ctl(), sb_encoder_ctl(), ServerInfo_Event(), speex_decoder_ctl(), speex_echo_ctl(), speex_encoder_ctl(), speex_free(), speex_free_scratch(), speex_header_free(), speex_lib_ctl(), speex_mode_query(), speex_preprocess_ctl(), speex_realloc(), StartServer_MapEvent(), StartServer_MenuEvent(), SystemSettings_Event(), TeamMain_MenuEvent(), trace_init(), type_init(), unary(), VM_CallCompiled(), wb_mode_query(), Z_Free(), Z_LogZoneHeap(), and zcfree().
qual()
Type qual (int op, Type ty)
Definition at line 230 of file types.c.
{
     if (isarray(ty))
         ty = type(ARRAY, qual(op, ty->type), ty->size,
             ty->align, NULL);
     else if (isfunc(ty))
         warning("qualified function type ignored\n");
     else if ((isconst(ty)    && op == CONST)
     ||       (isvolatile(ty) && op == VOLATILE))
         error("illegal type `%k %t'\n", op, ty);
     else {
         if (isqual(ty)) {
             op += ty->op;
             ty = ty->type;
         }
         ty = type(op, ty, ty->size, ty->align, NULL);
     }
     return ty;
 }
References error(), isarray, isconst, isfunc, isqual, isvolatile, NULL, op, type(), and warning().
Referenced by compose(), condtree(), dcllocal(), dclr(), field(), sb_encoder_ctl(), specifier(), speex_std_vbr_quality_request_handler(), trace_init(), unary(), and vbr_analysis().
rmtypes()
void rmtypes (int lev)
Definition at line 171 of file types.c.
                       {
     if (maxlevel >= lev) {
         int i;
         maxlevel = 0;
         for (i = 0; i < NELEMS(typetable); i++) {
             struct entry *tn, **tq = &typetable[i];
             while ((tn = *tq) != NULL)
                 if (tn->type.op == FUNCTION)
                     tq = &tn->link;
                 else if (tn->type.u.sym && tn->type.u.sym->scope >= lev)
                     *tq = tn->link;
                 else {
                     if (tn->type.u.sym && tn->type.u.sym->scope > maxlevel)
                         maxlevel = tn->type.u.sym->scope;
                     tq = &tn->link;
                 }
         }
     }
 }
References entry::link, maxlevel, NELEMS, NULL, Type::op, Type::sym, entry::type, typetable, and Type::u.
Referenced by exitscope().
signedint()
Type signedint (Type ty)
Definition at line 379 of file types.c.
{
     if (ty->op == INT)
         return ty;
     assert(ty->op == UNSIGNED);
 #define xx(t) if (ty->size == t->size) return t
     xx(inttype);
     xx(longtype);
     xx(longlong);
 #undef xx
     assert(0); return NULL;
 }
References INT, inttype, longlong, longtype, NULL, and xx.
Referenced by cast(), cmp(), and swcode().
ttob()
int ttob (Type ty)
Definition at line 430 of file types.c.
                   {
     switch (ty->op) {
     case CONST: case VOLATILE: case CONST+VOLATILE:
         return ttob(ty->type);
     case VOID: case INT: case UNSIGNED: case FLOAT:
         return ty->op + sizeop(ty->size);
     case POINTER:
         return POINTER + sizeop(voidptype->size);
     case FUNCTION:
         return POINTER + sizeop(funcptype->size);
     case ARRAY: case STRUCT: case UNION:
         return STRUCT;
     case ENUM:
         return INT + sizeop(inttype->size);
     }
     assert(0); return INT;
 }
References funcptype, INT, inttype, sizeop, and voidptype.
Referenced by asgnnode(), defsymbol(), jump(), listnodes(), and tmpnode().
type()
static Type type (int op, Type ty, int size, int align, void * sym) static
Definition at line 67 of file types.c.
{
     unsigned h = (op^((unsigned long)ty>>3))
 &(NELEMS(typetable)-1);
     struct entry *tn;
     if (op != FUNCTION && (op != ARRAY || size > 0))
         for (tn = typetable[h]; tn; tn = tn->link)
             if (tn->type.op    == op   && tn->type.type  == ty
             &&  tn->type.size  == size && tn->type.align == align
             &&  tn->type.u.sym == sym)
                 return &tn->type;
     NEW0(tn, PERM);
     tn->type.op = op;
     tn->type.type = ty;
     tn->type.size = size;
     tn->type.align = align;
     tn->type.u.sym = sym;
     tn->link = typetable[h];
     typetable[h] = tn;
     return &tn->type;
 }
References Type::align, entry::link, long(), NELEMS, NEW0, op, Type::op, PERM, Type::size, entry::sym, Type::sym, Type::type, entry::type, typetable, and Type::u.
Referenced by array(), func(), newstruct(), ptr(), qual(), type_init(), and xxinit().
type_init()
void type_init (int argc, char * argv[])
Definition at line 88 of file types.c.
{
     static int inited;
     int i;
     if (inited)
         return;
     inited = 1;
     if (!IR)
         return;
     for (i = 1; i < argc; i++) {
         int size, align, outofline;
         if (strncmp(argv[i], "-unsigned_char=", 15) == 0)
             IR->unsigned_char = argv[i][15] - '0';
 #define xx(name) \
         else if (sscanf(argv[i], "-" #name "=%d,%d,%d", &size, &align, &outofline) == 3) { \
             IR->name.size = size; IR->name.align = align; \
             IR->name.outofline = outofline; }
     xx(charmetric)
     xx(shortmetric)
     xx(intmetric)
     xx(longmetric)
     xx(longlongmetric)
     xx(floatmetric)
     xx(doublemetric)
     xx(longdoublemetric)
     xx(ptrmetric)
     xx(structmetric)
 #undef xx
     }
 #define xx(v,name,op,metrics) v=xxinit(op,name,IR->metrics)
     xx(chartype,        "char",              IR->unsigned_char ? UNSIGNED : INT,charmetric);
     xx(doubletype,      "double",            FLOAT,   doublemetric);
     xx(floattype,       "float",             FLOAT,   floatmetric);
     xx(inttype,         "int",               INT,     intmetric);
     xx(longdouble,      "long double",       FLOAT,   longdoublemetric);
     xx(longtype,        "long int",          INT,     longmetric);
     xx(longlong,        "long long int",     INT,     longlongmetric);
     xx(shorttype,       "short",             INT,     shortmetric);
     xx(signedchar,      "signed char",       INT,     charmetric);
     xx(unsignedchar,    "unsigned char",     UNSIGNED,charmetric);
     xx(unsignedlong,    "unsigned long",     UNSIGNED,longmetric);
     xx(unsignedshort,   "unsigned short",    UNSIGNED,shortmetric);
     xx(unsignedtype,    "unsigned int",      UNSIGNED,intmetric);
     xx(unsignedlonglong,"unsigned long long",UNSIGNED,longlongmetric);
 #undef xx
     {
         Symbol p;
         p = install(string("void"), &types, GLOBAL, PERM);
         voidtype = type(VOID, NULL, 0, 0, p);
         p->type = voidtype;
     }
     pointersym = install(string("T*"), &types, GLOBAL, PERM);
     pointersym->addressed = IR->ptrmetric.outofline;
     pointersym->u.limits.max.p = (void*)ones(8*IR->ptrmetric.size);
     pointersym->u.limits.min.p = 0;
     voidptype = ptr(voidtype);
     funcptype = ptr(func(voidtype, NULL, 1));
     charptype = ptr(chartype);
 #define xx(v,t) if (v==NULL && t->size==voidptype->size && t->align==voidptype->align) v=t
     xx(unsignedptr,unsignedshort);
     xx(unsignedptr,unsignedtype);
     xx(unsignedptr,unsignedlong);
     xx(unsignedptr,unsignedlonglong);
     if (unsignedptr == NULL)
         unsignedptr = type(UNSIGNED, NULL, voidptype->size, voidptype->align, voidptype->u.sym);
     xx(signedptr,shorttype);
     xx(signedptr,inttype);
     xx(signedptr,longtype);
     xx(signedptr,longlong);
     if (signedptr == NULL)
         signedptr = type(INT, NULL, voidptype->size, voidptype->align, voidptype->u.sym);
 #undef xx
     widechar = unsignedshort;
     for (i = 0; i < argc; i++) {
 #define xx(name,type) \
         if (strcmp(argv[i], "-wchar_t=" #name) == 0) \
             widechar = type;
         xx(unsigned_char,unsignedchar)
         xx(unsigned_int,unsignedtype)
         xx(unsigned_short,unsignedshort)
     }
 #undef xx
 }
References charptype, chartype, doubletype, floattype, func(), funcptype, GLOBAL, install(), INT, inttype, IR, longdouble, longlong, longtype, NULL, ones, PERM, pointersym, ptr(), shorttype, signedchar, signedptr, type(), types, unsignedchar, unsignedlong, unsignedlonglong, unsignedptr, unsignedshort, unsignedtype, voidptype, voidtype, widechar, and xx.
Referenced by init(), main_init(), prof_init(), and trace_init().
typestring()
char* typestring (Type ty, char * str)
Definition at line 691 of file types.c.
{
     for ( ; ty; ty = ty->type) {
         Symbol p;
         switch (ty->op) {
         case CONST+VOLATILE: case CONST: case VOLATILE:
             if (isptr(ty->type))
                 str = stringf("%k %s", ty->op, str);
             else
                 return stringf("%k %s", ty->op, typestring(ty->type, str));
             break;
         case STRUCT: case UNION: case ENUM:
             assert(ty->u.sym);
             if ((p = findtype(ty)) != NULL)
                 return *str ? stringf("%s %s", p->name, str) : p->name;
             if (*ty->u.sym->name >= '1' && *ty->u.sym->name <= '9')
                 warning("unnamed %k in prototype\n", ty->op);
             if (*str)
                 return stringf("%k %s %s", ty->op, ty->u.sym->name, str);
             else
                 return stringf("%k %s", ty->op, ty->u.sym->name);
         case VOID: case FLOAT: case INT: case UNSIGNED:
             return *str ? stringf("%s %s", ty->u.sym->name, str) : ty->u.sym->name;
         case POINTER:
             if (!ischar(ty->type) && (p = findtype(ty)) != NULL)
                 return *str ? stringf("%s %s", p->name, str) : p->name;
             str = stringf(isarray(ty->type) || isfunc(ty->type) ? "(*%s)" : "*%s", str);
             break;
         case FUNCTION:
             if ((p = findtype(ty)) != NULL)
                 return *str ? stringf("%s %s", p->name, str) : p->name;
             if (ty->u.f.proto == 0)
                 str = stringf("%s()", str);
             else if (ty->u.f.proto[0]) {
                 int i;
                 str = stringf("%s(%s", str, typestring(ty->u.f.proto[0], ""));
                 for (i = 1; ty->u.f.proto[i]; i++)
                     if (ty->u.f.proto[i] == voidtype)
                         str = stringf("%s, ...", str);
                     else
                         str = stringf("%s, %s", str, typestring(ty->u.f.proto[i], ""));
                 str = stringf("%s)", str);
             } else
                 str = stringf("%s(void)", str);
             break;
         case ARRAY:
             if ((p = findtype(ty)) != NULL)
                 return *str ? stringf("%s %s", p->name, str) : p->name;
             if (ty->type && ty->type->size > 0)
                 str = stringf("%s[%d]", str, ty->size/ty->type->size);
             else
                 str = stringf("%s[]", str);
             break;
         default: assert(0);
         }
     }
     assert(0); return 0;
 }
References findtype(), INT, isarray, ischar, isfunc, isptr, NULL, stringf(), voidtype, and warning().
Referenced by funcdefn(), printdecl(), and tracevalue().
variadic()
int variadic (Type ty)
Definition at line 262 of file types.c.
                       {
     if (isfunc(ty) && ty->u.f.proto) {
         int i;
         for (i = 0; ty->u.f.proto[i]; i++)
             ;
         return i > 1 && ty->u.f.proto[i-1] == voidtype;
     }
     return 0;
 }
References isfunc, and voidtype.
Referenced by eqtype(), funcdefn(), and tracecall().
xxinit()
static Type xxinit (int op, char * name, Metrics m) static
Definition at line 38 of file types.c.
{
     Symbol p = install(string(name), &types, GLOBAL, PERM);
     Type ty = type(op, 0, m.size, m.align, p);
     assert(ty->align == 0 || ty->size%ty->align == 0);
     p->type = ty;
     p->addressed = m.outofline;
     switch (ty->op) {
     case INT:
         p->u.limits.max.i = ones(8*ty->size)>>1;
         p->u.limits.min.i = -p->u.limits.max.i - 1;
         break;
     case UNSIGNED:
         p->u.limits.max.u = ones(8*ty->size);
         p->u.limits.min.u = 0;
         break;
     case FLOAT:
         if (ty->size == sizeof (float))
             p->u.limits.max.d =  FLT_MAX;
         else if (ty->size == sizeof (double))
             p->u.limits.max.d =  DBL_MAX;
         else
             p->u.limits.max.d = LDBL_MAX;
         p->u.limits.min.d = -p->u.limits.max.d;
         break;
     default: assert(0);
     }
     return ty;
 }
References GLOBAL, install(), INT, m, ones, op, PERM, type(), and types.
Variable Documentation
charptype
Type charptype
Definition at line 31 of file types.c.
Referenced by bbvars(), funcdefn(), tracefinis(), and type_init().
chartype
Type chartype
Definition at line 16 of file types.c.
Referenced by btot(), gettok(), initializer(), mkstr(), trace_init(), tracevalue(), type_init(), and vtoa().
doubletype
Type doubletype
Definition at line 17 of file types.c.
Referenced by binary(), btot(), fcon(), gettok(), promote(), and type_init().
floattype
Type floattype
Definition at line 18 of file types.c.
Referenced by binary(), btot(), fcon(), gettok(), and type_init().
funcptype
Type funcptype
Definition at line 30 of file types.c.
Referenced by btot(), idtree(), ttob(), and type_init().
inttype
Type inttype
Definition at line 19 of file types.c.
Referenced by addtree(), andtree(), array(), asgntree(), assign(), bbentry(), bbexit(), bbincr(), binary(), bittree(), btot(), call(), cast(), cmptree(), cond(), condtree(), enumdcl(), eqtree(), field(), fields(), freturn(), funcdefn(), genconst(), gettok(), icon(), initchar(), initfields(), initvalue(), intconst(), intexpr(), listnodes(), multree(), nullcall(), nullcheck(), parameters(), postfix(), primary(), promote(), shtree(), signedint(), simplify(), specifier(), subtree(), super(), swstmt(), trace_init(), tracecall(), tracevalue(), ttob(), type_init(), unary(), and value().
longdouble
Type longdouble
Definition at line 20 of file types.c.
Referenced by binary(), btot(), cast(), fcon(), specifier(), tracevalue(), and type_init().
longlong
Type longlong
Definition at line 22 of file types.c.
Referenced by binary(), btot(), signedint(), specifier(), and type_init().
longtype
Type longtype
Definition at line 21 of file types.c.
Referenced by binary(), btot(), icon(), signedint(), simplify(), specifier(), subtree(), tracevalue(), and type_init().
maxlevel
int maxlevel static
Definition at line 12 of file types.c.
Referenced by newstruct(), and rmtypes().
pointersym
Symbol pointersym static
Definition at line 14 of file types.c.
Referenced by ptr(), and type_init().
shorttype
Type shorttype
Definition at line 23 of file types.c.
Referenced by btot(), specifier(), and type_init().
signedchar
Type signedchar
Definition at line 24 of file types.c.
Referenced by btot(), specifier(), tracevalue(), type_init(), and vtoa().
signedptr
Type signedptr
Definition at line 35 of file types.c.
Referenced by addtree(), subtree(), and type_init().
typetable
struct entry * typetable[128] static
Referenced by rmtypes(), and type().
unsignedchar
Type unsignedchar
Definition at line 25 of file types.c.
Referenced by btot(), initfields(), specifier(), tracevalue(), type_init(), and vtoa().
unsignedlong
Type unsignedlong
Definition at line 26 of file types.c.
Referenced by binary(), btot(), cast(), icon(), specifier(), swcode(), tracevalue(), type_init(), and unary().
unsignedlonglong
Type unsignedlonglong
Definition at line 27 of file types.c.
Referenced by binary(), btot(), specifier(), and type_init().
unsignedptr
Type unsignedptr
Definition at line 34 of file types.c.
Referenced by cmptree(), eqtree(), subtree(), super(), swcode(), and type_init().
unsignedshort
Type unsignedshort
Definition at line 28 of file types.c.
Referenced by btot(), specifier(), and type_init().
unsignedtype
Type unsignedtype
Definition at line 29 of file types.c.
Referenced by bbcall(), bbfunc(), bbvars(), binary(), btot(), cast(), cmptree(), fields(), icon(), initfields(), listnodes(), prof_init(), promote(), specifier(), super(), tracevalue(), and type_init().
voidptype
Type voidptype
Definition at line 32 of file types.c.
Referenced by asgnnode(), bbcall(), bbentry(), bbexit(), btot(), condtree(), defpointer(), idtree(), jump(), listnodes(), main_init(), nullcall(), nullcheck(), swcode(), tmpnode(), ttob(), and type_init().
voidtype
Type voidtype
Definition at line 33 of file types.c.
Referenced by array(), asgntree(), bbentry(), bbexit(), call(), condtree(), ftype(), funcdefn(), gettok(), lvalue(), nullcheck(), outtype(), parameters(), postfix(), printproto(), root1(), statement(), swcode(), tracereturn(), type_init(), typestring(), unary(), value(), variadic(), vcall(), and vfprint().
widechar
Type widechar
Definition at line 36 of file types.c.
Referenced by backslash(), doconst(), gettok(), initializer(), printtoken(), and type_init().