ZEQ2-Lite: InstalledFontCollection Class Reference
InstalledFontCollection Class Reference
#include <gdiplusheaders.h>
Public Member Functions
InstalledFontCollection ()
virtual ~InstalledFontCollection ()
Status GetFamilies (INT numSought, FontFamily *families, INT *numFound) const
INT GetFamilyCount () const
Status GetLastStatus () const
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpFontCollection * nativeFontCollection
Detailed Description
Definition at line 466 of file gdiplusheaders.h.
Constructor & Destructor Documentation
InstalledFontCollection()
__inline__ InstalledFontCollection::InstalledFontCollection ()
Definition at line 1079 of file gdiplusimpl.h.
 {
     lastStatus = DllExports::GdipNewInstalledFontCollection(
             &nativeFontCollection);
 }
References GdipNewInstalledFontCollection(), FontCollection::lastStatus, and FontCollection::nativeFontCollection.
~InstalledFontCollection()
virtual InstalledFontCollection::~InstalledFontCollection () inline virtual
Definition at line 470 of file gdiplusheaders.h.
 {}
Member Function Documentation
GetFamilies()
__inline__ Status FontCollection::GetFamilies (INT numSought, FontFamily * families, INT * numFound) const inherited
Definition at line 895 of file gdiplusimpl.h.
 {
     if (numSought <= 0 || !families || !numFound)
         return lastStatus = InvalidParameter;
     for (int i = 0; i < numSought; ++i) {
         families[i].nativeFontFamily = NULL;
         families[i].lastStatus = FontFamilyNotFound;
     }
     *numFound = 0;
     GpFontFamily **nativeFamilyArray = (GpFontFamily**)
         DllExports::GdipAlloc(numSought * sizeof (GpFontFamily*));
     if (!nativeFamilyArray)
         return lastStatus = OutOfMemory;
     Status status = updateStatus(DllExports::GdipGetFontCollectionFamilyList(
             nativeFontCollection, numSought, nativeFamilyArray,
             numFound));
     // FIXME: must the native GpFontFamily objects be cloned? Seems so.
     // (if this is not done, the "Creating a Private Font Collection"
     // example crashes on "delete[] pFontFamily")
     if (status == Ok) {
         for (int i = 0; i < *numFound; ++i) {
             families[i].lastStatus =
                 updateStatus(DllExports::GdipCloneFontFamily(
                     nativeFamilyArray[i],
                     &families[i].nativeFontFamily));
         }
     }
     DllExports::GdipFree(nativeFamilyArray);
     return status;
 }
References FontFamilyNotFound, GdipAlloc(), GdipCloneFontFamily(), GdipFree(), GdipGetFontCollectionFamilyList(), InvalidParameter, FontCollection::lastStatus, FontFamily::lastStatus, FontCollection::nativeFontCollection, FontFamily::nativeFontFamily, NULL, Ok, OutOfMemory, and FontCollection::updateStatus().
GetFamilyCount()
__inline__ INT FontCollection::GetFamilyCount () const inherited
Definition at line 933 of file gdiplusimpl.h.
 {
     INT result = 0;
     updateStatus(DllExports::GdipGetFontCollectionFamilyCount(
             nativeFontCollection, &result));
     return result;
 }
References GdipGetFontCollectionFamilyCount(), FontCollection::nativeFontCollection, and FontCollection::updateStatus().
GetLastStatus()
Status FontCollection::GetLastStatus () const inline inherited
Definition at line 396 of file gdiplusheaders.h.
     {
         return lastStatus;
     }
References FontCollection::lastStatus.
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
updateStatus()
Status FontCollection::updateStatus (Status newStatus) const inline private inherited
Definition at line 405 of file gdiplusheaders.h.
     {
         return lastStatus = newStatus;
     }
References FontCollection::lastStatus.
Referenced by PrivateFontCollection::AddFontFile(), PrivateFontCollection::AddMemoryFont(), FontCollection::GetFamilies(), and FontCollection::GetFamilyCount().
Field Documentation
lastStatus
Status FontCollection::lastStatus mutable private inherited
Definition at line 411 of file gdiplusheaders.h.
Referenced by FontCollection::GetFamilies(), FontCollection::GetLastStatus(), InstalledFontCollection(), PrivateFontCollection::PrivateFontCollection(), and FontCollection::updateStatus().
nativeFontCollection
GpFontCollection* FontCollection::nativeFontCollection private inherited
Definition at line 410 of file gdiplusheaders.h.
Referenced by PrivateFontCollection::AddFontFile(), PrivateFontCollection::AddMemoryFont(), Font::Font(), FontFamily::FontFamily(), FontCollection::GetFamilies(), FontCollection::GetFamilyCount(), InstalledFontCollection(), PrivateFontCollection::PrivateFontCollection(), and PrivateFontCollection::~PrivateFontCollection().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdiplusheaders.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h