ZEQ2-Lite: Source/Engine/null/null_client.c File Reference
null_client.c File Reference
#include "../../Shared/q_shared.h"
#include "../../Shared/qcommon.h"
Functions
void CL_CharEvent (int key)
void CL_ConsolePrint (char *txt)
void CL_Disconnect (qboolean showMainMenu)
void CL_FlushMemory (void)
void CL_ForwardCommandToServer (const char *string)
void CL_Frame (int msec)
qboolean CL_GameCommand (void)
void CL_Init (void)
void CL_InitKeyCommands (void)
void CL_InitRef (void)
void CL_JoystickEvent (int axis, int value, int time)
void CL_KeyEvent (int key, qboolean down, unsigned time)
void CL_MapLoading (void)
void CL_MouseEvent (int dx, int dy, int time)
void CL_PacketEvent (netadr_t from, msg_t *msg)
void CL_Shutdown (char *finalmsg, qboolean disconnect, qboolean quit)
void CL_ShutdownAll (qboolean shutdownRef)
void CL_Snd_Shutdown (void)
void CL_StartHunkUsers (qboolean rendererOnly)
void Key_WriteBindings (fileHandle_t f)
qboolean UI_GameCommand (void)
Variables
cvar_t * cl_shownet
Function Documentation
CL_CharEvent()
void CL_CharEvent (int key)
Definition at line 48 of file null_client.c.
{
 }
References CA_DISCONNECTED, chatField, clc, Field_CharEvent(), g_consoleField, K_CHAR_FLAG, Key_GetCatcher(), KEYCATCH_CONSOLE, KEYCATCH_MESSAGE, KEYCATCH_UI, qtrue, clientConnection_t::state, UI_KEY_EVENT, uivm, and VM_Call().
CL_ConsolePrint()
void CL_ConsolePrint (char * txt)
Definition at line 71 of file null_client.c.
{
 }
References cl_noprint, cls, console_t::color, COLOR_WHITE, ColorIndex, con, Con_CheckResize(), Con_Linefeed(), console_t::current, console_t::initialized, console_t::linewidth, NUM_CON_TIMES, Q_IsColorString, Q_strncmp(), qfalse, qtrue, clientStatic_t::realtime, console_t::text, console_t::times, console_t::totallines, and console_t::x.
CL_Disconnect()
void CL_Disconnect (qboolean showMainMenu)
Definition at line 51 of file null_client.c.
{
 }
References CA_CONNECTED, CA_DISCONNECTED, CL_AddReliableCommand(), CL_ClearState(), CL_CloseAVI(), cl_connectedToPureServer, CL_OldGame(), CL_StopRecord_f(), CL_UpdateGUID(), CL_VideoRecording(), CL_WritePacket(), clc, Cmd_RemoveCommand(), com_cl_running, Com_Memset, Com_Printf(), Cvar_Set(), clientConnection_t::demofile, clientConnection_t::demorecording, clientConnection_t::download, clientConnection_t::downloadName, clientConnection_t::downloadTempName, FS_FCloseFile(), FS_PureServerSetLoadedPaks(), MAX_CLIENTS, mumble_islinked(), mumble_unlink(), noGameRestart, NULL, qfalse, qtrue, S_ClearSoundBuffer(), SCR_StopCinematic(), SCR_UpdateScreen(), speex_bits_destroy(), speex_decoder_destroy(), speex_encoder_destroy(), speex_preprocess_state_destroy(), clientConnection_t::state, UI_SET_ACTIVE_MENU, UIMENU_NONE, uivm, and VM_Call().
CL_FlushMemory()
void CL_FlushMemory (void)
Definition at line 80 of file null_client.c.
 {
 }
References CL_ClearMemory(), CL_StartHunkUsers(), and qfalse.
CL_ForwardCommandToServer()
void CL_ForwardCommandToServer (const char * string)
Definition at line 68 of file null_client.c.
{
 }
References CA_CONNECTED, CL_AddReliableCommand(), clc, Cmd_Argc(), Cmd_Argv(), Com_Printf(), clientConnection_t::demoplaying, qfalse, S_COLOR_WHITE, and clientConnection_t::state.
CL_Frame()
void CL_Frame (int msec)
Definition at line 42 of file null_client.c.
{
 }
References CA_ACTIVE, CA_DISCONNECTED, Cbuf_ExecuteText(), cl, cl_autoRecordDemo, cl_aviFrameRate, CL_CheckForResend(), CL_CheckTimeout(), CL_CheckUserinfo(), CL_cURL_PerformDownload(), cl_forceavidemo, CL_SendCmd(), CL_SetCGameTime(), CL_StopRecord_f(), CL_TakeVideoFrame(), cl_timegraph, CL_VideoRecording(), clc, cls, com_cl_running, Com_RealTime(), COM_SkipPath(), COM_StripExtension(), com_sv_running, com_timescale, Con_RunConsole(), clientConnection_t::demoplaying, clientConnection_t::demorecording, EXEC_NOW, clientStatic_t::framecount, clientStatic_t::frametime, int(), Key_GetCatcher(), KEYCATCH_UI, clientActive_t::mapname, MAX_OSPATH, MAX_QPATH, Q_strncpyz(), clientStatic_t::realFrametime, clientStatic_t::realtime, S_StopAllSounds(), S_Update(), SCR_DebugGraph(), SCR_RunCinematic(), SCR_UpdateScreen(), clientConnection_t::servername, clientConnection_t::state, UI_SET_ACTIVE_MENU, UIMENU_MAIN, uivm, va(), and VM_Call().
CL_GameCommand()
qboolean CL_GameCommand (void)
Definition at line 57 of file null_client.c.
{
   return qfalse;
 }
References CG_CONSOLE_COMMAND, cgvm, qfalse, and VM_Call().
CL_Init()
void CL_Init (void)
Definition at line 32 of file null_client.c.
                      {
     cl_shownet = Cvar_Get ("cl_shownet", "0", CVAR_TEMP );
 }
References CA_DISCONNECTED, cl_activeAction, cl_allowDownload, cl_anglespeedkey, cl_autoRecordDemo, cl_aviFrameRate, cl_aviMotionJpeg, CL_ClearState(), CL_Clientinfo_f(), CL_CompleteDemoName(), CL_CompleteRcon(), CL_Configstrings_f(), CL_Connect_f(), cl_consoleKeys, cl_conXOffset, CL_Disconnect_f(), cl_forceavidemo, CL_ForwardToServer_f(), cl_freelook, cl_freezeDemo, CL_GenerateQKey(), CL_GlobalServers_f(), cl_guidServerUniq, cl_inGameVideo, CL_InitInput(), CL_InitRef(), cl_lanForcePackets, CL_LocalServers_f(), cl_maxpackets, cl_motdString, cl_mouseAccel, cl_mouseAccelOffset, cl_mouseAccelStyle, cl_noprint, CL_OpenedPK3List_f(), cl_packetdup, CL_Ping_f(), cl_pitchspeed, CL_PlayCinematic_f(), CL_PlayDemo_f(), CL_Rcon_f(), CL_Reconnect_f(), CL_Record_f(), CL_ReferencedPK3List_f(), cl_run, cl_sensitivity, CL_ServerStatus_f(), cl_serverStatusResendTime, CL_SetModel_f(), CL_ShowIP_f(), cl_showMouseRate, cl_shownet, cl_showSend, cl_showTimeDelta, CL_Snd_Restart_f(), CL_StopRecord_f(), CL_StopVideo_f(), cl_timedemo, cl_timedemoLog, cl_timeNudge, cl_timeout, CL_UpdateGUID(), CL_Vid_Restart_f(), CL_Video_f(), cl_yawspeed, clc, cls, Cmd_AddCommand(), Cmd_SetCommandCompletionFunc(), com_fullyInitialized, Com_Printf(), Con_Init(), CVAR_ARCHIVE, Cvar_CheckRange(), Cvar_Get(), CVAR_LATCH, CVAR_ROM, Cvar_Set(), CVAR_TEMP, CVAR_USERINFO, Cvar_VariableIntegerValue(), j_forward, j_forward_axis, j_pitch, j_pitch_axis, j_side, j_side_axis, j_up, j_up_axis, j_yaw, j_yaw_axis, m_filter, m_forward, m_pitch, m_side, m_yaw, MAX_JOYSTICK_AXIS, NULL, clientStatic_t::oldGameSet, qfalse, qtrue, rcon_client_password, rconAddress, clientStatic_t::realtime, S_COLOR_YELLOW, SCR_Init(), and clientConnection_t::state.
CL_InitKeyCommands()
void CL_InitKeyCommands (void)
Definition at line 77 of file null_client.c.
{
 }
References Cmd_AddCommand(), Cmd_SetCommandCompletionFunc(), Key_Bind_f(), Key_Bindlist_f(), Key_CompleteBind(), Key_CompleteUnbind(), Key_Unbind_f(), and Key_Unbindall_f().
CL_InitRef()
void CL_InitRef (void)
Definition at line 91 of file null_client.c.
 {
 }
References Cbuf_ExecuteText(), refimport_t::CIN_PlayCinematic, CIN_PlayCinematic(), refimport_t::CIN_RunCinematic, CIN_RunCinematic(), refimport_t::CIN_UploadCinematic, CIN_UploadCinematic(), CL_RefMalloc(), CL_ScaledMilliseconds(), refimport_t::CL_WriteAVIVideoFrame, CL_WriteAVIVideoFrame(), CM_ClusterPVS(), refimport_t::CM_ClusterPVS, refimport_t::CM_DrawDebugSurface, CM_DrawDebugSurface(), refimport_t::Cmd_AddCommand, Cmd_AddCommand(), refimport_t::Cmd_Argc, Cmd_Argc(), refimport_t::Cmd_Argv, Cmd_Argv(), refimport_t::Cmd_ExecuteText, refimport_t::Cmd_RemoveCommand, Cmd_RemoveCommand(), Com_Error(), Com_Printf(), Com_sprintf(), CVAR_ARCHIVE, refimport_t::Cvar_CheckRange, Cvar_CheckRange(), Cvar_ForceReset(), refimport_t::Cvar_Get, Cvar_Get(), CVAR_LATCH, refimport_t::Cvar_Set, Cvar_Set(), refimport_t::Cvar_SetValue, Cvar_SetValue(), Cvar_VariableIntegerValue(), refimport_t::Cvar_VariableIntegerValue, ERR_FATAL, refimport_t::Free, refimport_t::FS_FileExists, FS_FileExists(), refimport_t::FS_FileIsInPAK, FS_FileIsInPAK(), refimport_t::FS_FreeFile, FS_FreeFile(), refimport_t::FS_FreeFileList, FS_FreeFileList(), refimport_t::FS_ListFiles, FS_ListFiles(), refimport_t::FS_ReadFile, FS_ReadFile(), refimport_t::FS_WriteFile, FS_WriteFile(), refimport_t::ftol, GetRefAPI(), refimport_t::Hunk_Alloc, Hunk_Alloc, refimport_t::Hunk_AllocateTempMemory, Hunk_AllocateTempMemory(), Hunk_AllocDebug(), refimport_t::Hunk_FreeTempMemory, Hunk_FreeTempMemory(), IN_Init(), refimport_t::IN_Init, IN_Restart(), refimport_t::IN_Restart, IN_Shutdown(), refimport_t::IN_Shutdown, refimport_t::Malloc, MAX_OSPATH, refimport_t::Milliseconds, Q_ftol, qfalse, re, REF_API_VERSION, ri, Sys_GLimpInit(), refimport_t::Sys_GLimpInit, Sys_GLimpSafeInit(), refimport_t::Sys_GLimpSafeInit, Sys_LibraryError, Sys_LoadDll(), Sys_LoadFunction, Sys_LoadLibrary, refimport_t::Sys_LowPhysicalMemory, Sys_LowPhysicalMemory(), refimport_t::Sys_SetEnv, Sys_SetEnv(), and Z_Free().
CL_JoystickEvent()
void CL_JoystickEvent (int axis, int value, int time)
Definition at line 74 of file null_client.c.
{
 }
References cl, Com_Error(), ERR_DROP, clientActive_t::joystickAxis, and MAX_JOYSTICK_AXIS.
CL_KeyEvent()
void CL_KeyEvent (int key, qboolean down, unsigned time)
Definition at line 61 of file null_client.c.
{
 }
References CL_KeyDownEvent(), and CL_KeyUpEvent().
CL_MapLoading()
void CL_MapLoading (void)
Definition at line 54 of file null_client.c.
{
 }
References CA_CHALLENGING, CA_CONNECTED, CA_DISCONNECTED, cl, CL_CheckForResend(), CL_Disconnect(), clc, cls, com_cl_running, com_dedicated, Com_Memset, Con_Close(), clientConnection_t::connectTime, Cvar_Set(), clientActive_t::gameState, Key_SetCatcher(), KEYCATCH_CONSOLE, clientConnection_t::lastPacketSentTime, NA_UNSPEC, NET_StringToAdr(), Q_stricmp(), Q_strncpyz(), qtrue, RETRANSMIT_TIMEOUT, SCR_UpdateScreen(), clientConnection_t::serverAddress, clientConnection_t::serverMessage, clientConnection_t::servername, clientConnection_t::state, and clientStatic_t::updateInfoString.
CL_MouseEvent()
void CL_MouseEvent (int dx, int dy, int time)
Definition at line 36 of file null_client.c.
{
 }
References CG_MOUSE_EVENT, cgvm, cl, Key_GetCatcher(), KEYCATCH_CGAME, KEYCATCH_UI, clientActive_t::mouseDx, clientActive_t::mouseDy, clientActive_t::mouseIndex, UI_MOUSE_EVENT, uivm, and VM_Call().
CL_PacketEvent()
void CL_PacketEvent (netadr_t from, msg_t * msg)
Definition at line 45 of file null_client.c.
{
 }
References CA_CONNECTED, CL_ConnectionlessPacket(), CL_Netchan_Process(), CL_ParseServerMessage(), CL_WriteDemoMessage(), clc, cls, Com_DPrintf(), Com_Printf(), msg_t::cursize, msg_t::data, clientConnection_t::demorecording, clientConnection_t::demowaiting, clientConnection_t::lastPacketTime, NET_AdrToStringwPort(), NET_CompareAdr(), clientConnection_t::netchan, msg_t::readcount, clientStatic_t::realtime, netchan_t::remoteAddress, clientConnection_t::serverMessageSequence, and clientConnection_t::state.
CL_Shutdown()
void CL_Shutdown (char * finalmsg, qboolean disconnect, qboolean quit)
Definition at line 28 of file null_client.c.
 {
 }
References CL_ClearMemory(), CL_Disconnect(), CL_ShutdownInput(), CL_Snd_Shutdown(), cls, Cmd_RemoveCommand(), com_cl_running, Com_Memset, Com_Printf(), Con_Shutdown(), Cvar_Set(), Key_SetCatcher(), noGameRestart, qfalse, and qtrue.
CL_ShutdownAll()
void CL_ShutdownAll (qboolean shutdownRef)
Definition at line 84 of file null_client.c.
 {
 }
References clientStatic_t::cgameStarted, CL_CloseAVI(), CL_cURL_Shutdown(), CL_ShutdownCGame(), CL_ShutdownRef(), CL_ShutdownUI(), CL_StopRecord_f(), CL_VideoRecording(), clc, cls, clientConnection_t::demorecording, qfalse, re, clientStatic_t::rendererStarted, S_DisableSounds(), refexport_t::Shutdown, clientStatic_t::soundRegistered, and clientStatic_t::uiStarted.
CL_Snd_Shutdown()
void CL_Snd_Shutdown (void)
Definition at line 95 of file null_client.c.
 {
 }
References cls, qfalse, S_Shutdown(), and clientStatic_t::soundStarted.
CL_StartHunkUsers()
void CL_StartHunkUsers (qboolean rendererOnly)
Definition at line 88 of file null_client.c.
{
 }
References CL_InitRenderer(), CL_InitUI(), cls, com_cl_running, com_dedicated, qtrue, clientStatic_t::rendererStarted, S_BeginRegistration(), S_Init(), clientStatic_t::soundRegistered, clientStatic_t::soundStarted, and clientStatic_t::uiStarted.
Key_WriteBindings()
void Key_WriteBindings (fileHandle_t f)
Definition at line 39 of file null_client.c.
{
 }
References FS_Printf(), Key_KeynumToString(), keys, and MAX_KEYS.
UI_GameCommand()
qboolean UI_GameCommand (void)
Definition at line 64 of file null_client.c.
{
     return qfalse;
 }
References cls, qfalse, clientStatic_t::realtime, UI_CONSOLE_COMMAND, uivm, and VM_Call().
Variable Documentation
cl_shownet
cvar_t* cl_shownet
Definition at line 26 of file null_client.c.
Referenced by CL_Init(), MSG_ReadDeltaEntity(), and MSG_ReadDeltaPlayerstate().