ZEQ2-Lite: Source/Engine/jpeg-8c/jdmainct.c File Reference
jdmainct.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_main_controller
Macros
#define CTX_POSTPONED_ROW 2 /* feeding postponed row group */
#define CTX_PREPARE_FOR_IMCU 0 /* need to prepare for MCU row */
#define CTX_PROCESS_IMCU 1 /* feeding iMCU to postprocessor */
#define JPEG_INTERNALS
Typedefs
typedef my_main_controller * my_main_ptr
Functions
jinit_d_main_controller (j_decompress_ptr cinfo, boolean need_full_buffer)
make_funny_pointers (j_decompress_ptr cinfo)
METHODDEF (void)
process_data_context_main (j_decompress_ptr cinfo, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
process_data_crank_post (j_decompress_ptr cinfo, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
process_data_simple_main (j_decompress_ptr cinfo, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail)
set_bottom_pointers (j_decompress_ptr cinfo)
set_wraparound_pointers (j_decompress_ptr cinfo)
start_pass_main (j_decompress_ptr cinfo, J_BUF_MODE pass_mode)
Macro Definition Documentation
CTX_POSTPONED_ROW
#define CTX_POSTPONED_ROW 2 /* feeding postponed row group */
Definition at line 139 of file jdmainct.c.
CTX_PREPARE_FOR_IMCU
#define CTX_PREPARE_FOR_IMCU 0 /* need to prepare for MCU row */
Definition at line 137 of file jdmainct.c.
CTX_PROCESS_IMCU
#define CTX_PROCESS_IMCU 1 /* feeding iMCU to postprocessor */
Definition at line 138 of file jdmainct.c.
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 16 of file jdmainct.c.
Typedef Documentation
my_main_ptr
typedef my_main_controller* my_main_ptr
Definition at line 134 of file jdmainct.c.
Function Documentation
jinit_d_main_controller()
jinit_d_main_controller (j_decompress_ptr cinfo, boolean need_full_buffer)
Definition at line 476 of file jdmainct.c.
 {
   my_main_ptr main_ptr;
   int ci, rgroup, ngroups;
   jpeg_component_info *compptr;
   main_ptr = (my_main_ptr)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 SIZEOF(my_main_controller));
   cinfo->main = (struct jpeg_d_main_controller *) main_ptr;
   main_ptr->pub.start_pass = start_pass_main;
   if (need_full_buffer)     /* shouldn't happen */
     ERREXIT(cinfo, JERR_BAD_BUFFER_MODE);
   /* Allocate the workspace.
    * ngroups is the number of row groups we need.
    */
   if (cinfo->upsample->need_context_rows) {
     if (cinfo->min_DCT_v_scaled_size < 2) /* unsupported, see comments above */
       ERREXIT(cinfo, JERR_NOTIMPL);
     alloc_funny_pointers(cinfo); /* Alloc space for xbuffer[] lists */
     ngroups = cinfo->min_DCT_v_scaled_size + 2;
   } else {
     ngroups = cinfo->min_DCT_v_scaled_size;
   }
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     rgroup = (compptr->v_samp_factor * compptr->DCT_v_scaled_size) /
       cinfo->min_DCT_v_scaled_size; /* height of a row group of component */
     main_ptr->buffer[ci] = (*cinfo->mem->alloc_sarray)
             ((j_common_ptr) cinfo, JPOOL_IMAGE,
              compptr->width_in_blocks * compptr->DCT_h_scaled_size,
              (JDIMENSION) (rgroup * ngroups));
   }
 }
References my_main_controller::buffer, compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, ERREXIT, JPOOL_IMAGE, need_full_buffer, my_main_controller::pub, SIZEOF, start_pass_main(), jpeg_component_info::v_samp_factor, and jpeg_component_info::width_in_blocks.
Referenced by master_selection().
make_funny_pointers()
make_funny_pointers (j_decompress_ptr cinfo)
Definition at line 195 of file jdmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   int ci, i, rgroup;
   int M = cinfo->min_DCT_v_scaled_size;
   jpeg_component_info *compptr;
   JSAMPARRAY buf, xbuf0, xbuf1;
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     rgroup = (compptr->v_samp_factor * compptr->DCT_v_scaled_size) /
       cinfo->min_DCT_v_scaled_size; /* height of a row group of component */
     xbuf0 = main_ptr->xbuffer[0][ci];
     xbuf1 = main_ptr->xbuffer[1][ci];
     /* First copy the workspace pointers as-is */
     buf = main_ptr->buffer[ci];
     for (i = 0; i < rgroup * (M + 2); i++) {
       xbuf0[i] = xbuf1[i] = buf[i];
     }
     /* In the second list, put the last four row groups in swapped order */
     for (i = 0; i < rgroup * 2; i++) {
       xbuf1[rgroup*(M-2) + i] = buf[rgroup*M + i];
       xbuf1[rgroup*M + i] = buf[rgroup*(M-2) + i];
     }
     /* The wraparound pointers at top and bottom will be filled later
      * (see set_wraparound_pointers, below).  Initially we want the "above"
      * pointers to duplicate the first actual data line.  This only needs
      * to happen in xbuffer[0].
      */
     for (i = 0; i < rgroup; i++) {
       xbuf0[i - rgroup] = xbuf0[0];
     }
   }
 }
References my_main_controller::buffer, compptr, jpeg_component_info::DCT_v_scaled_size, M, jpeg_component_info::v_samp_factor, and my_main_controller::xbuffer.
Referenced by start_pass_main().
METHODDEF()
METHODDEF (void)
Definition at line 143 of file jdmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   int ci, rgroup;
   int M = cinfo->min_DCT_v_scaled_size;
   jpeg_component_info *compptr;
   JSAMPARRAY xbuf;
   /* Get top-level space for component array pointers.
    * We alloc both arrays with one call to save a few cycles.
    */
   main_ptr->xbuffer[0] = (JSAMPIMAGE)
     (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                 cinfo->num_components * 2 * SIZEOF(JSAMPARRAY));
   main_ptr->xbuffer[1] = main_ptr->xbuffer[0] + cinfo->num_components;
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     rgroup = (compptr->v_samp_factor * compptr->DCT_v_scaled_size) /
       cinfo->min_DCT_v_scaled_size; /* height of a row group of component */
     /* Get space for pointer lists --- M+4 row groups in each list.
      * We alloc both pointer lists with one call to save a few cycles.
      */
     xbuf = (JSAMPARRAY)
       (*cinfo->mem->alloc_small) ((j_common_ptr) cinfo, JPOOL_IMAGE,
                   2 * (rgroup * (M + 4)) * SIZEOF(JSAMPROW));
     xbuf += rgroup;     /* want one row group at negative offsets */
     main_ptr->xbuffer[0][ci] = xbuf;
     xbuf += rgroup * (M + 4);
     main_ptr->xbuffer[1][ci] = xbuf;
   }
 }
process_data_context_main()
process_data_context_main (j_decompress_ptr cinfo, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 385 of file jdmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   /* Read input data if we haven't filled the main buffer yet */
   if (! main_ptr->buffer_full) {
     if (! (*cinfo->coef->decompress_data) (cinfo,
                        main_ptr->xbuffer[main_ptr->whichptr]))
       return;           /* suspension forced, can do nothing more */
     main_ptr->buffer_full = TRUE;   /* OK, we have an iMCU row to work with */
     main_ptr->iMCU_row_ctr++;   /* count rows received */
   }
   /* Postprocessor typically will not swallow all the input data it is handed
    * in one call (due to filling the output buffer first).  Must be prepared
    * to exit and restart.  This switch lets us keep track of how far we got.
    * Note that each case falls through to the next on successful completion.
    */
   switch (main_ptr->context_state) {
   case CTX_POSTPONED_ROW:
     /* Call postprocessor using previously set pointers for postponed row */
     (*cinfo->post->post_process_data) (cinfo, main_ptr->xbuffer[main_ptr->whichptr],
             &main_ptr->rowgroup_ctr, main_ptr->rowgroups_avail,
             output_buf, out_row_ctr, out_rows_avail);
     if (main_ptr->rowgroup_ctr < main_ptr->rowgroups_avail)
       return;           /* Need to suspend */
     main_ptr->context_state = CTX_PREPARE_FOR_IMCU;
     if (*out_row_ctr >= out_rows_avail)
       return;           /* Postprocessor exactly filled output buf */
     /*FALLTHROUGH*/
   case CTX_PREPARE_FOR_IMCU:
     /* Prepare to process first M-1 row groups of this iMCU row */
     main_ptr->rowgroup_ctr = 0;
     main_ptr->rowgroups_avail = (JDIMENSION) (cinfo->min_DCT_v_scaled_size - 1);
     /* Check for bottom of image: if so, tweak pointers to "duplicate"
      * the last sample row, and adjust rowgroups_avail to ignore padding rows.
      */
     if (main_ptr->iMCU_row_ctr == cinfo->total_iMCU_rows)
       set_bottom_pointers(cinfo);
     main_ptr->context_state = CTX_PROCESS_IMCU;
     /*FALLTHROUGH*/
   case CTX_PROCESS_IMCU:
     /* Call postprocessor using previously set pointers */
     (*cinfo->post->post_process_data) (cinfo, main_ptr->xbuffer[main_ptr->whichptr],
             &main_ptr->rowgroup_ctr, main_ptr->rowgroups_avail,
             output_buf, out_row_ctr, out_rows_avail);
     if (main_ptr->rowgroup_ctr < main_ptr->rowgroups_avail)
       return;           /* Need to suspend */
     /* After the first iMCU, change wraparound pointers to normal state */
     if (main_ptr->iMCU_row_ctr == 1)
       set_wraparound_pointers(cinfo);
     /* Prepare to load new iMCU row using other xbuffer list */
     main_ptr->whichptr ^= 1;    /* 0=>1 or 1=>0 */
     main_ptr->buffer_full = FALSE;
     /* Still need to process last row group of this iMCU row, */
     /* which is saved at index M+1 of the other xbuffer */
     main_ptr->rowgroup_ctr = (JDIMENSION) (cinfo->min_DCT_v_scaled_size + 1);
     main_ptr->rowgroups_avail = (JDIMENSION) (cinfo->min_DCT_v_scaled_size + 2);
     main_ptr->context_state = CTX_POSTPONED_ROW;
   }
 }
References my_main_controller::buffer_full, my_main_controller::context_state, CTX_POSTPONED_ROW, CTX_PREPARE_FOR_IMCU, CTX_PROCESS_IMCU, FALSE, my_main_controller::iMCU_row_ctr, output_buf, my_main_controller::rowgroup_ctr, my_main_controller::rowgroups_avail, set_bottom_pointers(), set_wraparound_pointers(), TRUE, my_main_controller::whichptr, and my_main_controller::xbuffer.
Referenced by start_pass_main().
process_data_crank_post()
process_data_crank_post (j_decompress_ptr cinfo, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 459 of file jdmainct.c.
 {
   (*cinfo->post->post_process_data) (cinfo, (JSAMPIMAGE) NULL,
                      (JDIMENSION *) NULL, (JDIMENSION) 0,
                      output_buf, out_row_ctr, out_rows_avail);
 }
References NULL, and output_buf.
Referenced by start_pass_main().
process_data_simple_main()
process_data_simple_main (j_decompress_ptr cinfo, JSAMPARRAY output_buf, JDIMENSION * out_row_ctr, JDIMENSION out_rows_avail)
Definition at line 345 of file jdmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   JDIMENSION rowgroups_avail;
   /* Read input data if we haven't filled the main buffer yet */
   if (! main_ptr->buffer_full) {
     if (! (*cinfo->coef->decompress_data) (cinfo, main_ptr->buffer))
       return;           /* suspension forced, can do nothing more */
     main_ptr->buffer_full = TRUE;   /* OK, we have an iMCU row to work with */
   }
   /* There are always min_DCT_scaled_size row groups in an iMCU row. */
   rowgroups_avail = (JDIMENSION) cinfo->min_DCT_v_scaled_size;
   /* Note: at the bottom of the image, we may pass extra garbage row groups
    * to the postprocessor.  The postprocessor has to check for bottom
    * of image anyway (at row resolution), so no point in us doing it too.
    */
   /* Feed the postprocessor */
   (*cinfo->post->post_process_data) (cinfo, main_ptr->buffer,
                      &main_ptr->rowgroup_ctr, rowgroups_avail,
                      output_buf, out_row_ctr, out_rows_avail);
   /* Has postprocessor consumed all the data yet? If so, mark buffer empty */
   if (main_ptr->rowgroup_ctr >= rowgroups_avail) {
     main_ptr->buffer_full = FALSE;
     main_ptr->rowgroup_ctr = 0;
   }
 }
References my_main_controller::buffer, my_main_controller::buffer_full, FALSE, output_buf, my_main_controller::rowgroup_ctr, and TRUE.
Referenced by start_pass_main().
set_bottom_pointers()
set_bottom_pointers (j_decompress_ptr cinfo)
Definition at line 266 of file jdmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   int ci, i, rgroup, iMCUheight, rows_left;
   jpeg_component_info *compptr;
   JSAMPARRAY xbuf;
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     /* Count sample rows in one iMCU row and in one row group */
     iMCUheight = compptr->v_samp_factor * compptr->DCT_v_scaled_size;
     rgroup = iMCUheight / cinfo->min_DCT_v_scaled_size;
     /* Count nondummy sample rows remaining for this component */
     rows_left = (int) (compptr->downsampled_height % (JDIMENSION) iMCUheight);
     if (rows_left == 0) rows_left = iMCUheight;
     /* Count nondummy row groups.  Should get same answer for each component,
      * so we need only do it once.
      */
     if (ci == 0) {
       main_ptr->rowgroups_avail = (JDIMENSION) ((rows_left-1) / rgroup + 1);
     }
     /* Duplicate the last real sample row rgroup*2 times; this pads out the
      * last partial rowgroup and ensures at least one full rowgroup of context.
      */
     xbuf = main_ptr->xbuffer[main_ptr->whichptr][ci];
     for (i = 0; i < rgroup * 2; i++) {
       xbuf[rows_left + i] = xbuf[rows_left-1];
     }
   }
 }
References compptr, jpeg_component_info::DCT_v_scaled_size, jpeg_component_info::downsampled_height, int(), my_main_controller::rowgroups_avail, jpeg_component_info::v_samp_factor, my_main_controller::whichptr, and my_main_controller::xbuffer.
Referenced by process_data_context_main().
set_wraparound_pointers()
set_wraparound_pointers (j_decompress_ptr cinfo)
Definition at line 238 of file jdmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   int ci, i, rgroup;
   int M = cinfo->min_DCT_v_scaled_size;
   jpeg_component_info *compptr;
   JSAMPARRAY xbuf0, xbuf1;
   for (ci = 0, compptr = cinfo->comp_info; ci < cinfo->num_components;
        ci++, compptr++) {
     rgroup = (compptr->v_samp_factor * compptr->DCT_v_scaled_size) /
       cinfo->min_DCT_v_scaled_size; /* height of a row group of component */
     xbuf0 = main_ptr->xbuffer[0][ci];
     xbuf1 = main_ptr->xbuffer[1][ci];
     for (i = 0; i < rgroup; i++) {
       xbuf0[i - rgroup] = xbuf0[rgroup*(M+1) + i];
       xbuf1[i - rgroup] = xbuf1[rgroup*(M+1) + i];
       xbuf0[rgroup*(M+2) + i] = xbuf0[i];
       xbuf1[rgroup*(M+2) + i] = xbuf1[i];
     }
   }
 }
References compptr, jpeg_component_info::DCT_v_scaled_size, M, jpeg_component_info::v_samp_factor, and my_main_controller::xbuffer.
Referenced by process_data_context_main().
start_pass_main()
start_pass_main (j_decompress_ptr cinfo, J_BUF_MODE pass_mode)
Definition at line 307 of file jdmainct.c.
 {
   my_main_ptr main_ptr = (my_main_ptr) cinfo->main;
   switch (pass_mode) {
   case JBUF_PASS_THRU:
     if (cinfo->upsample->need_context_rows) {
       main_ptr->pub.process_data = process_data_context_main;
       make_funny_pointers(cinfo); /* Create the xbuffer[] lists */
       main_ptr->whichptr = 0;   /* Read first iMCU row into xbuffer[0] */
       main_ptr->context_state = CTX_PREPARE_FOR_IMCU;
       main_ptr->iMCU_row_ctr = 0;
     } else {
       /* Simple case with no context needed */
       main_ptr->pub.process_data = process_data_simple_main;
     }
     main_ptr->buffer_full = FALSE;  /* Mark buffer empty */
     main_ptr->rowgroup_ctr = 0;
     break;
 #ifdef QUANT_2PASS_SUPPORTED
   case JBUF_CRANK_DEST:
     /* For last pass of 2-pass quantization, just crank the postprocessor */
     main_ptr->pub.process_data = process_data_crank_post;
     break;
 #endif
   default:
     ERREXIT(cinfo, JERR_BAD_BUFFER_MODE);
     break;
   }
 }
References my_main_controller::buffer_full, my_main_controller::context_state, CTX_PREPARE_FOR_IMCU, ERREXIT, FALSE, my_main_controller::iMCU_row_ctr, JBUF_CRANK_DEST, JBUF_PASS_THRU, make_funny_pointers(), process_data_context_main(), process_data_crank_post(), process_data_simple_main(), my_main_controller::pub, my_main_controller::rowgroup_ctr, and my_main_controller::whichptr.
Referenced by jinit_c_main_controller(), and jinit_d_main_controller().