ZEQ2-Lite: pcrecpp::RE_Options Class Reference
pcrecpp::RE_Options Class Reference
#include <pcrecpp.h>
Public Member Functions
RE_Options ()
RE_Options (int option_flags)
int all_options () const
bool caseless () const
bool dollar_endonly () const
bool dotall () const
bool extended () const
bool extra () const
int match_limit () const
int match_limit_recursion () const
bool multiline () const
bool no_auto_capture () const
RE_Options & set_all_options (int opt)
RE_Options & set_caseless (bool x)
RE_Options & set_dollar_endonly (bool x)
RE_Options & set_dotall (bool x)
RE_Options & set_extended (bool x)
RE_Options & set_extra (bool x)
RE_Options & set_match_limit (int limit)
RE_Options & set_match_limit_recursion (int limit)
RE_Options & set_multiline (bool x)
RE_Options & set_no_auto_capture (bool x)
RE_Options & set_ungreedy (bool x)
RE_Options & set_utf8 (bool x)
bool ungreedy () const
bool utf8 () const
Private Attributes
int all_options_
int match_limit_
int match_limit_recursion_
Detailed Description
Definition at line 355 of file pcrecpp.h.
Constructor & Destructor Documentation
RE_Options() [1/2]
pcrecpp::RE_Options::RE_Options () inline
Definition at line 358 of file pcrecpp.h.
 : match_limit_(0), match_limit_recursion_(0), all_options_(0) {}
RE_Options() [2/2]
pcrecpp::RE_Options::RE_Options (int option_flags) inline
Definition at line 368 of file pcrecpp.h.
                                : match_limit_(0), match_limit_recursion_(0),
                                  all_options_(option_flags) {}
Member Function Documentation
all_options()
int pcrecpp::RE_Options::all_options () const inline
Definition at line 452 of file pcrecpp.h.
{
     return all_options_ ;
   }
caseless()
bool pcrecpp::RE_Options::caseless () const inline
Definition at line 385 of file pcrecpp.h.
{
     return PCRE_IS_SET(PCRE_CASELESS);
   }
References PCRE_CASELESS, and PCRE_IS_SET.
dollar_endonly()
bool pcrecpp::RE_Options::dollar_endonly () const inline
Definition at line 413 of file pcrecpp.h.
{
     return PCRE_IS_SET(PCRE_DOLLAR_ENDONLY);
   }
References PCRE_DOLLAR_ENDONLY, and PCRE_IS_SET.
dotall()
bool pcrecpp::RE_Options::dotall () const inline
Definition at line 399 of file pcrecpp.h.
                       {
     return PCRE_IS_SET(PCRE_DOTALL);
   }
References PCRE_DOTALL, and PCRE_IS_SET.
extended()
bool pcrecpp::RE_Options::extended () const inline
Definition at line 406 of file pcrecpp.h.
{
     return PCRE_IS_SET(PCRE_EXTENDED);
   }
References PCRE_EXTENDED, and PCRE_IS_SET.
extra()
bool pcrecpp::RE_Options::extra () const inline
Definition at line 420 of file pcrecpp.h.
                      {
     return PCRE_IS_SET(PCRE_EXTRA);
   }
References PCRE_EXTRA, and PCRE_IS_SET.
match_limit()
int pcrecpp::RE_Options::match_limit () const inline
Definition at line 373 of file pcrecpp.h.
 { return match_limit_; };
match_limit_recursion()
int pcrecpp::RE_Options::match_limit_recursion () const inline
Definition at line 379 of file pcrecpp.h.
 { return match_limit_recursion_; };
multiline()
bool pcrecpp::RE_Options::multiline () const inline
Definition at line 392 of file pcrecpp.h.
{
     return PCRE_IS_SET(PCRE_MULTILINE);
   }
References PCRE_IS_SET, and PCRE_MULTILINE.
no_auto_capture()
bool pcrecpp::RE_Options::no_auto_capture () const inline
Definition at line 441 of file pcrecpp.h.
{
     return PCRE_IS_SET(PCRE_NO_AUTO_CAPTURE);
   }
References PCRE_IS_SET, and PCRE_NO_AUTO_CAPTURE.
set_all_options()
RE_Options& pcrecpp::RE_Options::set_all_options (int opt) inline
Definition at line 448 of file pcrecpp.h.
{
     all_options_ = opt;
     return *this;
   }
References opt().
set_caseless()
RE_Options& pcrecpp::RE_Options::set_caseless (bool x) inline
Definition at line 388 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_CASELESS);
   }
References PCRE_CASELESS, and PCRE_SET_OR_CLEAR.
Referenced by pcrecpp::CASELESS().
set_dollar_endonly()
RE_Options& pcrecpp::RE_Options::set_dollar_endonly (bool x) inline
Definition at line 416 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_DOLLAR_ENDONLY);
   }
References PCRE_DOLLAR_ENDONLY, and PCRE_SET_OR_CLEAR.
set_dotall()
RE_Options& pcrecpp::RE_Options::set_dotall (bool x) inline
Definition at line 402 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_DOTALL);
   }
References PCRE_DOTALL, and PCRE_SET_OR_CLEAR.
Referenced by pcrecpp::DOTALL().
set_extended()
RE_Options& pcrecpp::RE_Options::set_extended (bool x) inline
Definition at line 409 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_EXTENDED);
   }
References PCRE_EXTENDED, and PCRE_SET_OR_CLEAR.
Referenced by pcrecpp::EXTENDED().
set_extra()
RE_Options& pcrecpp::RE_Options::set_extra (bool x) inline
Definition at line 423 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_EXTRA);
   }
References PCRE_EXTRA, and PCRE_SET_OR_CLEAR.
set_match_limit()
RE_Options& pcrecpp::RE_Options::set_match_limit (int limit) inline
Definition at line 374 of file pcrecpp.h.
{
     match_limit_ = limit;
     return *this;
   }
References limit.
set_match_limit_recursion()
RE_Options& pcrecpp::RE_Options::set_match_limit_recursion (int limit) inline
Definition at line 380 of file pcrecpp.h.
{
     match_limit_recursion_ = limit;
     return *this;
   }
References limit.
set_multiline()
RE_Options& pcrecpp::RE_Options::set_multiline (bool x) inline
Definition at line 395 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_MULTILINE);
   }
References PCRE_MULTILINE, and PCRE_SET_OR_CLEAR.
Referenced by pcrecpp::MULTILINE().
set_no_auto_capture()
RE_Options& pcrecpp::RE_Options::set_no_auto_capture (bool x) inline
Definition at line 444 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_NO_AUTO_CAPTURE);
   }
References PCRE_NO_AUTO_CAPTURE, and PCRE_SET_OR_CLEAR.
set_ungreedy()
RE_Options& pcrecpp::RE_Options::set_ungreedy (bool x) inline
Definition at line 430 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_UNGREEDY);
   }
References PCRE_SET_OR_CLEAR, and PCRE_UNGREEDY.
set_utf8()
RE_Options& pcrecpp::RE_Options::set_utf8 (bool x) inline
Definition at line 437 of file pcrecpp.h.
{
     PCRE_SET_OR_CLEAR(x, PCRE_UTF8);
   }
References PCRE_SET_OR_CLEAR, and PCRE_UTF8.
Referenced by pcrecpp::UTF8().
ungreedy()
bool pcrecpp::RE_Options::ungreedy () const inline
Definition at line 427 of file pcrecpp.h.
{
     return PCRE_IS_SET(PCRE_UNGREEDY);
   }
References PCRE_IS_SET, and PCRE_UNGREEDY.
utf8()
bool pcrecpp::RE_Options::utf8 () const inline
Definition at line 434 of file pcrecpp.h.
                     {
     return PCRE_IS_SET(PCRE_UTF8);
   }
References PCRE_IS_SET, and PCRE_UTF8.
Field Documentation
all_options_
int pcrecpp::RE_Options::all_options_ private
Definition at line 461 of file pcrecpp.h.
match_limit_
int pcrecpp::RE_Options::match_limit_ private
Definition at line 459 of file pcrecpp.h.
match_limit_recursion_
int pcrecpp::RE_Options::match_limit_recursion_ private
Definition at line 460 of file pcrecpp.h.
The documentation for this class was generated from the following file:
Tools/MinGW/include/pcrecpp.h