ZEQ2-Lite: Matrix Class Reference
Matrix Class Reference
#include <gdiplusmatrix.h>
Public Member Functions
Matrix ()
Matrix (const Rect &rect, const Point *dstplg)
Matrix (const RectF &rect, const PointF *dstplg)
Matrix (REAL m11, REAL m12, REAL m21, REAL m22, REAL dx, REAL dy)
~Matrix ()
Matrix * Clone () const
BOOL Equals (const Matrix *matrix) const
Status GetElements (REAL *m) const
Status GetLastStatus () const
Status Invert ()
BOOL IsIdentity () const
BOOL IsInvertible () const
Status Multiply (const Matrix *matrix, MatrixOrder order=MatrixOrderPrepend)
REAL OffsetX () const
REAL OffsetY () const
Status Reset ()
Status Rotate (REAL angle, MatrixOrder order=MatrixOrderPrepend)
Status RotateAt (REAL angle, const PointF &center, MatrixOrder order=MatrixOrderPrepend)
Status Scale (REAL scaleX, REAL scaleY, MatrixOrder order=MatrixOrderPrepend)
Status SetElements (REAL m11, REAL m12, REAL m21, REAL m22, REAL dx, REAL dy)
Status Shear (REAL shearX, REAL shearY, MatrixOrder order=MatrixOrderPrepend)
Status TransformPoints (Point *pts, INT count=1) const
Status TransformPoints (PointF *pts, INT count=1) const
Status TransformVectors (Point *pts, INT count=1) const
Status TransformVectors (PointF *pts, INT count=1) const
Status Translate (REAL offsetX, REAL offsetY, MatrixOrder order=MatrixOrderPrepend)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Matrix (const Matrix &)
Matrix (GpMatrix *matrix, Status status)
Matrix & operator= (const Matrix &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpMatrix * nativeMatrix
Friends
class Graphics
class GraphicsPath
class LinearGradientBrush
class PathGradientBrush
class Pen
class Region
class TextureBrush
Detailed Description
Definition at line 36 of file gdiplusmatrix.h.
Constructor & Destructor Documentation
Matrix() [1/6]
Matrix::Matrix () inline
Definition at line 47 of file gdiplusmatrix.h.
             : nativeMatrix(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreateMatrix(&nativeMatrix);
     }
References GdipCreateMatrix(), lastStatus, and nativeMatrix.
Referenced by Clone().
Matrix() [2/6]
Matrix::Matrix (REAL m11, REAL m12, REAL m21, REAL m22, REAL dx, REAL dy) inline
Definition at line 51 of file gdiplusmatrix.h.
                                                                     :
             nativeMatrix(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreateMatrix2(
                 m11, m12, m21, m22, dx, dy,
                 &nativeMatrix);
     }
References GdipCreateMatrix2(), lastStatus, and nativeMatrix.
Matrix() [3/6]
Matrix::Matrix (const RectF & rect, const PointF * dstplg) inline
Definition at line 58 of file gdiplusmatrix.h.
                                                    :
             nativeMatrix(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreateMatrix3(
                 &rect, dstplg, &nativeMatrix);
     }
References GdipCreateMatrix3(), lastStatus, and nativeMatrix.
Matrix() [4/6]
Matrix::Matrix (const Rect & rect, const Point * dstplg) inline
Definition at line 64 of file gdiplusmatrix.h.
                                                  :
             nativeMatrix(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreateMatrix3I(
                 &rect, dstplg, &nativeMatrix);
     }
References GdipCreateMatrix3I(), lastStatus, and nativeMatrix.
~Matrix()
Matrix::~Matrix () inline
Definition at line 70 of file gdiplusmatrix.h.
     {
         DllExports::GdipDeleteMatrix(nativeMatrix);
     }
References GdipDeleteMatrix(), and nativeMatrix.
Matrix() [5/6]
Matrix::Matrix (GpMatrix * matrix, Status status) inline private
Definition at line 223 of file gdiplusmatrix.h.
                                            :
         nativeMatrix(matrix), lastStatus(status) {}
Matrix() [6/6]
Matrix::Matrix (const Matrix &) private
Member Function Documentation
Clone()
Matrix* Matrix::Clone () const inline
Definition at line 74 of file gdiplusmatrix.h.
     {
         GpMatrix *cloneMatrix = NULL;
         Status status = updateStatus(DllExports::GdipCloneMatrix(
                 nativeMatrix, &cloneMatrix));
         if (status == Ok) {
             Matrix *result = new Matrix(cloneMatrix, lastStatus);
             if (!result) {
                 DllExports::GdipDeleteMatrix(cloneMatrix);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneMatrix(), GdipDeleteMatrix(), lastStatus, Matrix(), nativeMatrix, NULL, Ok, OutOfMemory, and updateStatus().
Equals()
BOOL Matrix::Equals (const Matrix * matrix) const inline
Definition at line 91 of file gdiplusmatrix.h.
     {
         BOOL result;
         updateStatus(DllExports::GdipIsMatrixEqual(
                 nativeMatrix,
                 matrix ? matrix->nativeMatrix : NULL, &result));
         return result;
     }
References GdipIsMatrixEqual(), nativeMatrix, NULL, and updateStatus().
GetElements()
Status Matrix::GetElements (REAL * m) const inline
Definition at line 99 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipGetMatrixElements(
                 nativeMatrix, m));
     }
References GdipGetMatrixElements(), m, nativeMatrix, and updateStatus().
GetLastStatus()
Status Matrix::GetLastStatus () const inline
Definition at line 104 of file gdiplusmatrix.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
Referenced by RotateAt().
Invert()
Status Matrix::Invert () inline
Definition at line 110 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipInvertMatrix(nativeMatrix));
     }
References GdipInvertMatrix(), nativeMatrix, and updateStatus().
IsIdentity()
BOOL Matrix::IsIdentity () const inline
Definition at line 114 of file gdiplusmatrix.h.
     {
         BOOL result;
         updateStatus(DllExports::GdipIsMatrixIdentity(
                 nativeMatrix, &result));
         return result;
     }
References GdipIsMatrixIdentity(), nativeMatrix, and updateStatus().
IsInvertible()
BOOL Matrix::IsInvertible () const inline
Definition at line 121 of file gdiplusmatrix.h.
     {
         BOOL result;
         updateStatus(DllExports::GdipIsMatrixInvertible(
                 nativeMatrix, &result));
         return result;
     }
References GdipIsMatrixInvertible(), nativeMatrix, and updateStatus().
Multiply()
Status Matrix::Multiply (const Matrix * matrix, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 128 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipMultiplyMatrix(
                 nativeMatrix,
                 matrix ? matrix->nativeMatrix : NULL, order));
     }
References GdipMultiplyMatrix(), nativeMatrix, NULL, and updateStatus().
Referenced by RotateAt().
OffsetX()
REAL Matrix::OffsetX () const inline
Definition at line 135 of file gdiplusmatrix.h.
     {
         REAL m[6];
         updateStatus(DllExports::GdipGetMatrixElements(nativeMatrix, m));
         return m[4];
     }
References GdipGetMatrixElements(), m, nativeMatrix, and updateStatus().
OffsetY()
REAL Matrix::OffsetY () const inline
Definition at line 141 of file gdiplusmatrix.h.
     {
         REAL m[6];
         updateStatus(DllExports::GdipGetMatrixElements(nativeMatrix, m));
         return m[5];
     }
References GdipGetMatrixElements(), m, nativeMatrix, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Matrix& Matrix::operator= (const Matrix &) private
Reset()
Status Matrix::Reset () inline
Definition at line 147 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipSetMatrixElements(
                 nativeMatrix,
                 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f));
     }
References GdipSetMatrixElements(), nativeMatrix, and updateStatus().
Rotate()
Status Matrix::Rotate (REAL angle, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 153 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipRotateMatrix(
                 nativeMatrix, angle, order));
     }
References GdipRotateMatrix(), nativeMatrix, and updateStatus().
RotateAt()
Status Matrix::RotateAt (REAL angle, const PointF & center, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 158 of file gdiplusmatrix.h.
     {
         REAL angleRadian = angle * GDIP_MATRIX_PI / 180.0f;
         REAL cosAngle = ::cos(angleRadian);
         REAL sinAngle = ::sin(angleRadian);
         REAL x = center.X;
         REAL y = center.Y;
         Matrix matrix2(cosAngle, sinAngle, -sinAngle, cosAngle,
                 x * (1.0f-cosAngle) + y * sinAngle,
                 -x * sinAngle + y * (1.0f-cosAngle));
         Status status = matrix2.GetLastStatus();
         if (status == Ok) {
             return Multiply(&matrix2, order);
         } else {
             return lastStatus = status;
         }
     }
References cos(), GDIP_MATRIX_PI, GetLastStatus(), lastStatus, Multiply(), Ok, sin(), PointF::X, and PointF::Y.
Scale()
Status Matrix::Scale (REAL scaleX, REAL scaleY, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 177 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipScaleMatrix(
                 nativeMatrix, scaleX, scaleY, order));
     }
References GdipScaleMatrix(), nativeMatrix, and updateStatus().
SetElements()
Status Matrix::SetElements (REAL m11, REAL m12, REAL m21, REAL m22, REAL dx, REAL dy) inline
Definition at line 183 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipSetMatrixElements(
                 nativeMatrix, m11, m12, m21, m22, dx, dy));
     }
References GdipSetMatrixElements(), nativeMatrix, and updateStatus().
Shear()
Status Matrix::Shear (REAL shearX, REAL shearY, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 189 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipShearMatrix(
                 nativeMatrix, shearX, shearY, order));
     }
References GdipShearMatrix(), nativeMatrix, and updateStatus().
TransformPoints() [1/2]
Status Matrix::TransformPoints (Point * pts, INT count = 1) const inline
Definition at line 200 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipTransformMatrixPointsI(
                 nativeMatrix, pts, count));
     }
References GdipTransformMatrixPointsI(), nativeMatrix, and updateStatus().
TransformPoints() [2/2]
Status Matrix::TransformPoints (PointF * pts, INT count = 1) const inline
Definition at line 195 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipTransformMatrixPoints(
                 nativeMatrix, pts, count));
     }
References GdipTransformMatrixPoints(), nativeMatrix, and updateStatus().
TransformVectors() [1/2]
Status Matrix::TransformVectors (Point * pts, INT count = 1) const inline
Definition at line 210 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipVectorTransformMatrixPointsI(
                 nativeMatrix, pts, count));
     }
References GdipVectorTransformMatrixPointsI(), nativeMatrix, and updateStatus().
TransformVectors() [2/2]
Status Matrix::TransformVectors (PointF * pts, INT count = 1) const inline
Definition at line 205 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipVectorTransformMatrixPoints(
                 nativeMatrix, pts, count));
     }
References GdipVectorTransformMatrixPoints(), nativeMatrix, and updateStatus().
Translate()
Status Matrix::Translate (REAL offsetX, REAL offsetY, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 215 of file gdiplusmatrix.h.
     {
         return updateStatus(DllExports::GdipTranslateMatrix(
                 nativeMatrix, offsetX, offsetY, order));
     }
References GdipTranslateMatrix(), nativeMatrix, and updateStatus().
updateStatus()
Status Matrix::updateStatus (Status newStatus) const inline private
Definition at line 228 of file gdiplusmatrix.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by Clone(), Equals(), GetElements(), Invert(), IsIdentity(), IsInvertible(), Multiply(), OffsetX(), OffsetY(), Reset(), Rotate(), Scale(), SetElements(), Shear(), TransformPoints(), TransformVectors(), and Translate().
Friends And Related Function Documentation
Graphics
friend class Graphics friend
Definition at line 38 of file gdiplusmatrix.h.
GraphicsPath
friend class GraphicsPath friend
Definition at line 39 of file gdiplusmatrix.h.
LinearGradientBrush
friend class LinearGradientBrush friend
Definition at line 40 of file gdiplusmatrix.h.
PathGradientBrush
friend class PathGradientBrush friend
Definition at line 41 of file gdiplusmatrix.h.
Pen
friend class Pen friend
Definition at line 42 of file gdiplusmatrix.h.
Region
friend class Region friend
Definition at line 43 of file gdiplusmatrix.h.
TextureBrush
friend class TextureBrush friend
Definition at line 44 of file gdiplusmatrix.h.
Field Documentation
lastStatus
Status Matrix::lastStatus mutable private
Definition at line 235 of file gdiplusmatrix.h.
Referenced by Clone(), GetLastStatus(), Matrix(), RotateAt(), and updateStatus().
nativeMatrix
GpMatrix* Matrix::nativeMatrix private
Definition at line 234 of file gdiplusmatrix.h.
Referenced by Clone(), Equals(), GetElements(), Invert(), IsIdentity(), IsInvertible(), Matrix(), Multiply(), OffsetX(), OffsetY(), Reset(), Rotate(), Scale(), SetElements(), Shear(), TransformPoints(), TransformVectors(), Translate(), and ~Matrix().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusmatrix.h