ZEQ2-Lite: JitterBuffer: Adaptive jitter buffer
JitterBuffer: Adaptive jitter buffer
This is the jitter buffer that reorders UDP/RTP packets and adjusts the buffer size to maintain good quality and low latency.
Data Structures
struct JitterBufferPacket
Definition of an incoming packet.
Macros
#define JITTER_BUFFER_BAD_ARGUMENT -2
Invalid argument.
#define JITTER_BUFFER_GET_AVAILABLE_COUNT 3
Get the amount of available packets currently buffered.
#define JITTER_BUFFER_GET_AVALIABLE_COUNT 3
Included because of an early misspelling (will remove in next release)
#define JITTER_BUFFER_GET_CONCEALMENT_SIZE 9
#define JITTER_BUFFER_GET_DELAY_STEP 7
#define JITTER_BUFFER_GET_DESTROY_CALLBACK 5
#define JITTER_BUFFER_GET_LATE_COST 13
#define JITTER_BUFFER_GET_MARGIN 1
Get minimum amount of extra buffering required (margin)
#define JITTER_BUFFER_GET_MAX_LATE_RATE 11
#define JITTER_BUFFER_INSERTION 2
A "fake" packet is meant to be inserted here to increase buffering.
#define JITTER_BUFFER_INTERNAL_ERROR -1
There was an error in the jitter buffer.
#define JITTER_BUFFER_MISSING 1
Packet is lost or is late.
#define JITTER_BUFFER_OK 0
Packet has been retrieved.
#define JITTER_BUFFER_SET_CONCEALMENT_SIZE 8
Tell the jitter buffer to only do concealment in multiples of the size parameter provided.
#define JITTER_BUFFER_SET_DELAY_STEP 6
Tell the jitter buffer to only adjust the delay in multiples of the step parameter provided.
#define JITTER_BUFFER_SET_DESTROY_CALLBACK 4
Assign a function to destroy unused packet.
#define JITTER_BUFFER_SET_LATE_COST 12
Equivalent cost of one percent late packet in timestamp units.
#define JITTER_BUFFER_SET_MARGIN 0
Set minimum amount of extra buffering required (margin)
#define JITTER_BUFFER_SET_MAX_LATE_RATE 10
Absolute max amount of loss that can be tolerated regardless of the delay.
Functions
int jitter_buffer_ctl (JitterBuffer *jitter, int request, void *ptr)
Used like the ioctl function to control the jitter buffer parameters.
void jitter_buffer_destroy (JitterBuffer *jitter)
Destroys jitter buffer.
int jitter_buffer_get (JitterBuffer *jitter, JitterBufferPacket *packet, spx_int32_t desired_span, spx_int32_t *start_offset)
Get one packet from the jitter buffer.
int jitter_buffer_get_another (JitterBuffer *jitter, JitterBufferPacket *packet)
Used right after jitter_buffer_get() to obtain another packet that would have the same timestamp.
int jitter_buffer_get_pointer_timestamp (JitterBuffer *jitter)
Get pointer timestamp of jitter buffer.
JitterBuffer * jitter_buffer_init (int step_size)
Initialises jitter buffer.
void jitter_buffer_put (JitterBuffer *jitter, const JitterBufferPacket *packet)
Put one packet into the jitter buffer.
void jitter_buffer_remaining_span (JitterBuffer *jitter, spx_uint32_t rem)
Telling the jitter buffer about the remaining data in the application buffer.
void jitter_buffer_reset (JitterBuffer *jitter)
Restores jitter buffer to its original state.
void jitter_buffer_tick (JitterBuffer *jitter)
Advance by one tick.
int jitter_buffer_update_delay (JitterBuffer *jitter, JitterBufferPacket *packet, spx_int32_t *start_offset)
Variables
char * JitterBufferPacket::data
Data bytes contained in the packet.
spx_uint32_t JitterBufferPacket::len
Length of the packet in bytes.
spx_uint16_t JitterBufferPacket::sequence
RTP Sequence number if available (0 otherwise)
spx_uint32_t JitterBufferPacket::span
Time covered by the packet (same units as timestamp)
spx_uint32_t JitterBufferPacket::timestamp
Timestamp for the packet.
spx_uint32_t JitterBufferPacket::user_data
Put whatever data you like here (it's ignored by the jitter buffer)
Detailed Description
This is the jitter buffer that reorders UDP/RTP packets and adjusts the buffer size to maintain good quality and low latency.
Macro Definition Documentation
JITTER_BUFFER_BAD_ARGUMENT
#define JITTER_BUFFER_BAD_ARGUMENT -2
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Invalid argument.
Definition at line 78 of file speex_jitter.h.
JITTER_BUFFER_GET_AVAILABLE_COUNT
#define JITTER_BUFFER_GET_AVAILABLE_COUNT 3
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Get the amount of available packets currently buffered.
Definition at line 88 of file speex_jitter.h.
JITTER_BUFFER_GET_AVALIABLE_COUNT
#define JITTER_BUFFER_GET_AVALIABLE_COUNT 3
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Included because of an early misspelling (will remove in next release)
Definition at line 90 of file speex_jitter.h.
JITTER_BUFFER_GET_CONCEALMENT_SIZE
#define JITTER_BUFFER_GET_CONCEALMENT_SIZE 9
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Definition at line 105 of file speex_jitter.h.
JITTER_BUFFER_GET_DELAY_STEP
#define JITTER_BUFFER_GET_DELAY_STEP 7
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Definition at line 101 of file speex_jitter.h.
JITTER_BUFFER_GET_DESTROY_CALLBACK
#define JITTER_BUFFER_GET_DESTROY_CALLBACK 5
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Definition at line 96 of file speex_jitter.h.
JITTER_BUFFER_GET_LATE_COST
#define JITTER_BUFFER_GET_LATE_COST 13
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Definition at line 114 of file speex_jitter.h.
JITTER_BUFFER_GET_MARGIN
#define JITTER_BUFFER_GET_MARGIN 1
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Get minimum amount of extra buffering required (margin)
Definition at line 84 of file speex_jitter.h.
JITTER_BUFFER_GET_MAX_LATE_RATE
#define JITTER_BUFFER_GET_MAX_LATE_RATE 11
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Definition at line 110 of file speex_jitter.h.
JITTER_BUFFER_INSERTION
#define JITTER_BUFFER_INSERTION 2
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
A "fake" packet is meant to be inserted here to increase buffering.
Definition at line 74 of file speex_jitter.h.
JITTER_BUFFER_INTERNAL_ERROR
#define JITTER_BUFFER_INTERNAL_ERROR -1
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
There was an error in the jitter buffer.
Definition at line 76 of file speex_jitter.h.
JITTER_BUFFER_MISSING
#define JITTER_BUFFER_MISSING 1
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Packet is lost or is late.
Definition at line 72 of file speex_jitter.h.
JITTER_BUFFER_OK
#define JITTER_BUFFER_OK 0
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Packet has been retrieved.
Definition at line 70 of file speex_jitter.h.
JITTER_BUFFER_SET_CONCEALMENT_SIZE
#define JITTER_BUFFER_SET_CONCEALMENT_SIZE 8
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Tell the jitter buffer to only do concealment in multiples of the size parameter provided.
Definition at line 104 of file speex_jitter.h.
JITTER_BUFFER_SET_DELAY_STEP
#define JITTER_BUFFER_SET_DELAY_STEP 6
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Tell the jitter buffer to only adjust the delay in multiples of the step parameter provided.
Definition at line 99 of file speex_jitter.h.
JITTER_BUFFER_SET_DESTROY_CALLBACK
#define JITTER_BUFFER_SET_DESTROY_CALLBACK 4
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Assign a function to destroy unused packet.
When setting that, the jitter buffer no longer copies packet data.
Definition at line 94 of file speex_jitter.h.
JITTER_BUFFER_SET_LATE_COST
#define JITTER_BUFFER_SET_LATE_COST 12
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Equivalent cost of one percent late packet in timestamp units.
Definition at line 113 of file speex_jitter.h.
JITTER_BUFFER_SET_MARGIN
#define JITTER_BUFFER_SET_MARGIN 0
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Set minimum amount of extra buffering required (margin)
Definition at line 82 of file speex_jitter.h.
JITTER_BUFFER_SET_MAX_LATE_RATE
#define JITTER_BUFFER_SET_MAX_LATE_RATE 10
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Absolute max amount of loss that can be tolerated regardless of the delay.
Typical loss should be half of that or less.
Definition at line 109 of file speex_jitter.h.
Function Documentation
jitter_buffer_ctl()
int jitter_buffer_ctl (JitterBuffer * jitter, int request, void * ptr)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Used like the ioctl function to control the jitter buffer parameters.
Parameters
jitter Jitter buffer state
request ioctl-type request (one of the JITTER_BUFFER_* macros)
ptr Data exchanged to-from function
Returns
0 if no error, -1 if request in unknown
Definition at line 780 of file jitter.c.
 {
    int count, i;
    switch(request)
    {
       case JITTER_BUFFER_SET_MARGIN:
          jitter->buffer_margin = *(spx_int32_t*)ptr;
          break;
       case JITTER_BUFFER_GET_MARGIN:
          *(spx_int32_t*)ptr = jitter->buffer_margin;
          break;
       case JITTER_BUFFER_GET_AVALIABLE_COUNT:
          count = 0;
          for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
          {
             if (jitter->packets[i].data && LE32(jitter->pointer_timestamp, jitter->packets[i].timestamp))
             {
                count++;
             }
          }
          *(spx_int32_t*)ptr = count;
          break;
       case JITTER_BUFFER_SET_DESTROY_CALLBACK:
          jitter->destroy = (void (*) (void *))ptr;
          break;
       case JITTER_BUFFER_GET_DESTROY_CALLBACK:
          *(void (**) (void *))ptr = jitter->destroy;
          break;
       case JITTER_BUFFER_SET_DELAY_STEP:
          jitter->delay_step = *(spx_int32_t*)ptr;
          break;
       case JITTER_BUFFER_GET_DELAY_STEP:
          *(spx_int32_t*)ptr = jitter->delay_step;
          break;
       case JITTER_BUFFER_SET_CONCEALMENT_SIZE:
          jitter->concealment_size = *(spx_int32_t*)ptr;
          break;
       case JITTER_BUFFER_GET_CONCEALMENT_SIZE:
          *(spx_int32_t*)ptr = jitter->concealment_size;
          break;
       case JITTER_BUFFER_SET_MAX_LATE_RATE:
          jitter->max_late_rate = *(spx_int32_t*)ptr;
          jitter->window_size = 100*TOP_DELAY/jitter->max_late_rate;
          jitter->subwindow_size = jitter->window_size/MAX_BUFFERS;
          break;
       case JITTER_BUFFER_GET_MAX_LATE_RATE:
          *(spx_int32_t*)ptr = jitter->max_late_rate;
          break;
       case JITTER_BUFFER_SET_LATE_COST:
          jitter->latency_tradeoff = *(spx_int32_t*)ptr;
          break;
       case JITTER_BUFFER_GET_LATE_COST:
          *(spx_int32_t*)ptr = jitter->latency_tradeoff;
          break;
       default:
          speex_warning_int("Unknown jitter_buffer_ctl request: ", request);
          return -1;
    }
    return 0;
 }
References JITTER_BUFFER_GET_AVALIABLE_COUNT, JITTER_BUFFER_GET_CONCEALMENT_SIZE, JITTER_BUFFER_GET_DELAY_STEP, JITTER_BUFFER_GET_DESTROY_CALLBACK, JITTER_BUFFER_GET_LATE_COST, JITTER_BUFFER_GET_MARGIN, JITTER_BUFFER_GET_MAX_LATE_RATE, JITTER_BUFFER_SET_CONCEALMENT_SIZE, JITTER_BUFFER_SET_DELAY_STEP, JITTER_BUFFER_SET_DESTROY_CALLBACK, JITTER_BUFFER_SET_LATE_COST, JITTER_BUFFER_SET_MARGIN, JITTER_BUFFER_SET_MAX_LATE_RATE, LE32, MAX_BUFFERS, ptr(), SPEEX_JITTER_MAX_BUFFER_SIZE, speex_warning_int(), TOP_DELAY, and void().
Referenced by jitter_buffer_init().
jitter_buffer_destroy()
void jitter_buffer_destroy (JitterBuffer * jitter)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Destroys jitter buffer.
Parameters
jitter Jitter buffer state
Destroys jitter buffer.
Definition at line 328 of file jitter.c.
 {
    jitter_buffer_reset(jitter);
    speex_free(jitter);
 }
References jitter_buffer_reset(), and speex_free().
jitter_buffer_get()
int jitter_buffer_get (JitterBuffer * jitter, JitterBufferPacket * packet, spx_int32_t desired_span, spx_int32_t * start_offset)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Get one packet from the jitter buffer.
Parameters
jitter Jitter buffer state
packet Returned packet
desired_span Number of samples (or units) we wish to get from the buffer (no guarantee)
current_timestamp Timestamp for the returned packet
Definition at line 462 of file jitter.c.
 {
    int i;
    unsigned int j;
    //int incomplete = 0;
    spx_int16_t opt;
    if (start_offset != NULL)
       *start_offset = 0;
    /* Syncing on the first call */
    if (jitter->reset_state)
    {
       int found = 0;
       /* Find the oldest packet */
       spx_uint32_t oldest=0;
       for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
       {
          if (jitter->packets[i].data && (!found || LT32(jitter->packets[i].timestamp,oldest)))
          {
             oldest = jitter->packets[i].timestamp;
             found = 1;
          }
       }
       if (found)
       {
          jitter->reset_state=0;
          jitter->pointer_timestamp = oldest;
          jitter->next_stop = oldest;
       } else {
          packet->timestamp = 0;
          packet->span = jitter->interp_requested;
          return JITTER_BUFFER_MISSING;
       }
    }
    jitter->last_returned_timestamp = jitter->pointer_timestamp;
    if (jitter->interp_requested != 0)
    {
       packet->timestamp = jitter->pointer_timestamp;
       packet->span = jitter->interp_requested;
       /* Increment the pointer because it got decremented in the delay update */
       jitter->pointer_timestamp += jitter->interp_requested;
       packet->len = 0;
       /*fprintf (stderr, "Deferred interpolate\n");*/
       jitter->interp_requested = 0;
       jitter->buffered = packet->span - desired_span;
       return JITTER_BUFFER_INSERTION;
    }
    /* Searching for the packet that fits best */
    /* Search the buffer for a packet with the right timestamp and spanning the whole current chunk */
    for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
    {
       if (jitter->packets[i].data && jitter->packets[i].timestamp==jitter->pointer_timestamp && GE32(jitter->packets[i].timestamp+jitter->packets[i].span,jitter->pointer_timestamp+desired_span))
          break;
    }
    /* If no match, try for an "older" packet that still spans (fully) the current chunk */
    if (i==SPEEX_JITTER_MAX_BUFFER_SIZE)
    {
       for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
       {
          if (jitter->packets[i].data && LE32(jitter->packets[i].timestamp, jitter->pointer_timestamp) && GE32(jitter->packets[i].timestamp+jitter->packets[i].span,jitter->pointer_timestamp+desired_span))
             break;
       }
    }
    /* If still no match, try for an "older" packet that spans part of the current chunk */
    if (i==SPEEX_JITTER_MAX_BUFFER_SIZE)
    {
       for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
       {
          if (jitter->packets[i].data && LE32(jitter->packets[i].timestamp, jitter->pointer_timestamp) && GT32(jitter->packets[i].timestamp+jitter->packets[i].span,jitter->pointer_timestamp))
             break;
       }
    }
    /* If still no match, try for earliest packet possible */
    if (i==SPEEX_JITTER_MAX_BUFFER_SIZE)
    {
       int found = 0;
       spx_uint32_t best_time=0;
       int best_span=0;
       int besti=0;
       for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
       {
          /* check if packet starts within current chunk */
          if (jitter->packets[i].data && LT32(jitter->packets[i].timestamp,jitter->pointer_timestamp+desired_span) && GE32(jitter->packets[i].timestamp,jitter->pointer_timestamp))
          {
             if (!found || LT32(jitter->packets[i].timestamp,best_time) || (jitter->packets[i].timestamp==best_time && GT32(jitter->packets[i].span,best_span)))
             {
                best_time = jitter->packets[i].timestamp;
                best_span = jitter->packets[i].span;
                besti = i;
                found = 1;
             }
          }
       }
       if (found)
       {
          i=besti;
          //incomplete = 1;
          /*fprintf (stderr, "incomplete: %d %d %d %d\n", jitter->packets[i].timestamp, jitter->pointer_timestamp, chunk_size, jitter->packets[i].span);*/
       }
    }
    /* If we find something */
    if (i!=SPEEX_JITTER_MAX_BUFFER_SIZE)
    {
       spx_int32_t offset;
       /* We (obviously) haven't lost this packet */
       jitter->lost_count = 0;
       /* In this case, 0 isn't as a valid timestamp */
       if (jitter->arrival[i] != 0)
       {
          update_timings(jitter, ((spx_int32_t)jitter->packets[i].timestamp) - ((spx_int32_t)jitter->arrival[i]) - jitter->buffer_margin);
       }
       /* Copy packet */
       if (jitter->destroy)
       {
          packet->data = jitter->packets[i].data;
          packet->len = jitter->packets[i].len;
       } else {
          if (jitter->packets[i].len > packet->len)
          {
             speex_warning_int("jitter_buffer_get(): packet too large to fit. Size is", jitter->packets[i].len);
          } else {
             packet->len = jitter->packets[i].len;
          }
          for (j=0;j<packet->len;j++)
             packet->data[j] = jitter->packets[i].data[j];
          /* Remove packet */
          speex_free(jitter->packets[i].data);
       }
       jitter->packets[i].data = NULL;
       /* Set timestamp and span (if requested) */
       offset = (spx_int32_t)jitter->packets[i].timestamp-(spx_int32_t)jitter->pointer_timestamp;
       if (start_offset != NULL)
          *start_offset = offset;
       else if (offset != 0)
          speex_warning_int("jitter_buffer_get() discarding non-zero start_offset", offset);
       packet->timestamp = jitter->packets[i].timestamp;
       jitter->last_returned_timestamp = packet->timestamp;
       packet->span = jitter->packets[i].span;
       packet->sequence = jitter->packets[i].sequence;
       packet->user_data = jitter->packets[i].user_data;
       /* Point to the end of the current packet */
       jitter->pointer_timestamp = jitter->packets[i].timestamp+jitter->packets[i].span;
       jitter->buffered = packet->span - desired_span;
       if (start_offset != NULL)
          jitter->buffered += *start_offset;
       return JITTER_BUFFER_OK;
    }
    /* If we haven't found anything worth returning */
    /*fprintf (stderr, "not found\n");*/
    jitter->lost_count++;
    /*fprintf (stderr, "m");*/
    /*fprintf (stderr, "lost_count = %d\n", jitter->lost_count);*/
    opt = compute_opt_delay(jitter);
    /* Should we force an increase in the buffer or just do normal interpolation? */
    if (opt < 0)
    {
       /* Need to increase buffering */
       /* Shift histogram to compensate */
       shift_timings(jitter, -opt);
       packet->timestamp = jitter->pointer_timestamp;
       packet->span = -opt;
       /* Don't move the pointer_timestamp forward */
       packet->len = 0;
       jitter->buffered = packet->span - desired_span;
       return JITTER_BUFFER_INSERTION;
       /*jitter->pointer_timestamp -= jitter->delay_step;*/
       /*fprintf (stderr, "Forced to interpolate\n");*/
    } else {
       /* Normal packet loss */
       packet->timestamp = jitter->pointer_timestamp;
       desired_span = ROUND_DOWN(desired_span, jitter->concealment_size);
       packet->span = desired_span;
       jitter->pointer_timestamp += desired_span;
       packet->len = 0;
       jitter->buffered = packet->span - desired_span;
       return JITTER_BUFFER_MISSING;
       /*fprintf (stderr, "Normal loss\n");*/
    }
 }
References compute_opt_delay(), GE32, GT32, JITTER_BUFFER_INSERTION, JITTER_BUFFER_MISSING, JITTER_BUFFER_OK, LE32, LT32, NULL, opt(), ROUND_DOWN, shift_timings(), speex_free(), SPEEX_JITTER_MAX_BUFFER_SIZE, speex_warning_int(), and update_timings().
jitter_buffer_get_another()
int jitter_buffer_get_another (JitterBuffer * jitter, JitterBufferPacket * packet)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Used right after jitter_buffer_get() to obtain another packet that would have the same timestamp.
This is mainly useful for media where a single "frame" can be split into several packets.
Parameters
jitter Jitter buffer state
packet Returned packet
Definition at line 677 of file jitter.c.
 {
    int i, j;
    for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
    {
       if (jitter->packets[i].data && jitter->packets[i].timestamp==jitter->last_returned_timestamp)
          break;
    }
    if (i!=SPEEX_JITTER_MAX_BUFFER_SIZE)
    {
       /* Copy packet */
       packet->len = jitter->packets[i].len;
       if (jitter->destroy)
       {
          packet->data = jitter->packets[i].data;
       } else {
          for (j=0;j<packet->len;j++)
             packet->data[j] = jitter->packets[i].data[j];
          /* Remove packet */
          speex_free(jitter->packets[i].data);
       }
       jitter->packets[i].data = NULL;
       packet->timestamp = jitter->packets[i].timestamp;
       packet->span = jitter->packets[i].span;
       packet->sequence = jitter->packets[i].sequence;
       packet->user_data = jitter->packets[i].user_data;
       return JITTER_BUFFER_OK;
    } else {
       packet->data = NULL;
       packet->len = 0;
       packet->span = 0;
       return JITTER_BUFFER_MISSING;
    }
 }
References JITTER_BUFFER_MISSING, JITTER_BUFFER_OK, NULL, speex_free(), and SPEEX_JITTER_MAX_BUFFER_SIZE.
jitter_buffer_get_pointer_timestamp()
int jitter_buffer_get_pointer_timestamp (JitterBuffer * jitter)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Get pointer timestamp of jitter buffer.
Parameters
jitter Jitter buffer state
Definition at line 746 of file jitter.c.
 {
    return jitter->pointer_timestamp;
 }
jitter_buffer_init()
JitterBuffer* jitter_buffer_init (int step_size)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Initialises jitter buffer.
Parameters
step_size Starting value for the size of concleanment packets and delay adjustment steps. Can be changed at any time using JITTER_BUFFER_SET_DELAY_STEP and JITTER_BUFFER_GET_CONCEALMENT_SIZE.
Returns
Newly created jitter buffer state
Initialises jitter buffer.
Definition at line 272 of file jitter.c.
 {
    JitterBuffer *jitter = (JitterBuffer*)speex_alloc(sizeof(JitterBuffer));
    if (jitter)
    {
       int i;
       spx_int32_t tmp;
       for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
          jitter->packets[i].data=NULL;
       jitter->delay_step = step_size;
       jitter->concealment_size = step_size;
       /*FIXME: Should this be 0 or 1?*/
       jitter->buffer_margin = 0;
       jitter->late_cutoff = 50;
       jitter->destroy = NULL;
       jitter->latency_tradeoff = 0;
       jitter->auto_adjust = 1;
       tmp = 4;
       jitter_buffer_ctl(jitter, JITTER_BUFFER_SET_MAX_LATE_RATE, &tmp);
       jitter_buffer_reset(jitter);
    }
    return jitter;
 }
References jitter_buffer_ctl(), jitter_buffer_reset(), JITTER_BUFFER_SET_MAX_LATE_RATE, NULL, speex_alloc(), and SPEEX_JITTER_MAX_BUFFER_SIZE.
jitter_buffer_put()
void jitter_buffer_put (JitterBuffer * jitter, const JitterBufferPacket * packet)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Put one packet into the jitter buffer.
Parameters
jitter Jitter buffer state
packet Incoming packet
Definition at line 368 of file jitter.c.
 {
    int i,j;
    int late;
    /*fprintf (stderr, "put packet %d %d\n", timestamp, span);*/
    /* Cleanup buffer (remove old packets that weren't played) */
    if (!jitter->reset_state)
    {
       for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
       {
          /* Make sure we don't discard a "just-late" packet in case we want to play it next (if we interpolate). */
          if (jitter->packets[i].data && LE32(jitter->packets[i].timestamp + jitter->packets[i].span, jitter->pointer_timestamp))
          {
             /*fprintf (stderr, "cleaned (not played)\n");*/
             if (jitter->destroy)
                jitter->destroy(jitter->packets[i].data);
             else
                speex_free(jitter->packets[i].data);
             jitter->packets[i].data = NULL;
          }
       }
    }
    /*fprintf(stderr, "arrival: %d %d %d\n", packet->timestamp, jitter->next_stop, jitter->pointer_timestamp);*/
    /* Check if packet is late (could still be useful though) */
    if (!jitter->reset_state && LT32(packet->timestamp, jitter->next_stop))
    {
       update_timings(jitter, ((spx_int32_t)packet->timestamp) - ((spx_int32_t)jitter->next_stop) - jitter->buffer_margin);
       late = 1;
    } else {
       late = 0;
    }
    /* Only insert the packet if it's not hopelessly late (i.e. totally useless) */
    if (jitter->reset_state || GE32(packet->timestamp+packet->span+jitter->delay_step, jitter->pointer_timestamp))
    {
       /*Find an empty slot in the buffer*/
       for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
       {
          if (jitter->packets[i].data==NULL)
             break;
       }
       /*No place left in the buffer, need to make room for it by discarding the oldest packet */
       if (i==SPEEX_JITTER_MAX_BUFFER_SIZE)
       {
          int earliest=jitter->packets[0].timestamp;
          i=0;
          for (j=1;j<SPEEX_JITTER_MAX_BUFFER_SIZE;j++)
          {
             if (!jitter->packets[i].data || LT32(jitter->packets[j].timestamp,earliest))
             {
                earliest = jitter->packets[j].timestamp;
                i=j;
             }
          }
          if (jitter->destroy)
             jitter->destroy(jitter->packets[i].data);
          else
             speex_free(jitter->packets[i].data);
          jitter->packets[i].data=NULL;
          if (jitter->lost_count>20)
          {
             jitter_buffer_reset(jitter);
          }
          /*fprintf (stderr, "Buffer is full, discarding earliest frame %d (currently at %d)\n", timestamp, jitter->pointer_timestamp);*/
       }
       /* Copy packet in buffer */
       if (jitter->destroy)
       {
          jitter->packets[i].data = packet->data;
       } else {
          jitter->packets[i].data=(char*)speex_alloc(packet->len);
          for (j=0;j<packet->len;j++)
             jitter->packets[i].data[j]=packet->data[j];
       }
       jitter->packets[i].timestamp=packet->timestamp;
       jitter->packets[i].span=packet->span;
       jitter->packets[i].len=packet->len;
       jitter->packets[i].sequence=packet->sequence;
       jitter->packets[i].user_data=packet->user_data;
       if (jitter->reset_state || late)
          jitter->arrival[i] = 0;
       else
          jitter->arrival[i] = jitter->next_stop;
    }
 }
References GE32, jitter_buffer_reset(), LE32, LT32, NULL, speex_alloc(), speex_free(), SPEEX_JITTER_MAX_BUFFER_SIZE, and update_timings().
jitter_buffer_remaining_span()
void jitter_buffer_remaining_span (JitterBuffer * jitter, spx_uint32_t rem)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Telling the jitter buffer about the remaining data in the application buffer.
Parameters
jitter Jitter buffer state
rem Amount of data buffered by the application (timestamp units)
Definition at line 767 of file jitter.c.
 {
    /* Automatically-adjust the buffering delay if requested */
    if (jitter->auto_adjust)
       _jitter_buffer_update_delay(jitter, NULL, NULL);
    if (jitter->buffered < 0)
       speex_warning_int("jitter buffer sees negative buffering, your code might be broken. Value is ", jitter->buffered);
    jitter->next_stop = jitter->pointer_timestamp - rem;
 }
References _jitter_buffer_update_delay(), NULL, and speex_warning_int().
jitter_buffer_reset()
void jitter_buffer_reset (JitterBuffer * jitter)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Restores jitter buffer to its original state.
Parameters
jitter Jitter buffer state
Restores jitter buffer to its original state.
Definition at line 297 of file jitter.c.
 {
    int i;
    for (i=0;i<SPEEX_JITTER_MAX_BUFFER_SIZE;i++)
    {
       if (jitter->packets[i].data)
       {
          if (jitter->destroy)
             jitter->destroy(jitter->packets[i].data);
          else
             speex_free(jitter->packets[i].data);
          jitter->packets[i].data = NULL;
       }
    }
    /* Timestamp is actually undefined at this point */
    jitter->pointer_timestamp = 0;
    jitter->next_stop = 0;
    jitter->reset_state = 1;
    jitter->lost_count = 0;
    jitter->buffered = 0;
    jitter->auto_tradeoff = 32000;
    for (i=0;i<MAX_BUFFERS;i++)
    {
       tb_init(&jitter->_tb[i]);
       jitter->timeBuffers[i] = &jitter->_tb[i];
    }
    /*fprintf (stderr, "reset\n");*/
 }
References MAX_BUFFERS, NULL, speex_free(), SPEEX_JITTER_MAX_BUFFER_SIZE, and tb_init().
Referenced by jitter_buffer_destroy(), jitter_buffer_init(), and jitter_buffer_put().
jitter_buffer_tick()
void jitter_buffer_tick (JitterBuffer * jitter)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Advance by one tick.
Parameters
jitter Jitter buffer state
Definition at line 751 of file jitter.c.
 {
    /* Automatically-adjust the buffering delay if requested */
    if (jitter->auto_adjust)
       _jitter_buffer_update_delay(jitter, NULL, NULL);
    if (jitter->buffered >= 0)
    {
       jitter->next_stop = jitter->pointer_timestamp - jitter->buffered;
    } else {
       jitter->next_stop = jitter->pointer_timestamp;
       speex_warning_int("jitter buffer sees negative buffering, your code might be broken. Value is ", jitter->buffered);
    }
    jitter->buffered = 0;
 }
References _jitter_buffer_update_delay(), NULL, and speex_warning_int().
jitter_buffer_update_delay()
int jitter_buffer_update_delay (JitterBuffer * jitter, JitterBufferPacket * packet, spx_int32_t * start_offset)
#include <Source/Engine/libspeex/include/speex/speex_jitter.h>
Definition at line 736 of file jitter.c.
 {
    /* If the programmer calls jitter_buffer_update_delay() directly,
       automatically disable auto-adjustment */
    jitter->auto_adjust = 0;
    return _jitter_buffer_update_delay(jitter, packet, start_offset);
 }
References _jitter_buffer_update_delay().
Variable Documentation
data
char* JitterBufferPacket::data
Data bytes contained in the packet.
Definition at line 61 of file speex_jitter.h.
len
spx_uint32_t JitterBufferPacket::len
Length of the packet in bytes.
Definition at line 62 of file speex_jitter.h.
sequence
spx_uint16_t JitterBufferPacket::sequence
RTP Sequence number if available (0 otherwise)
Definition at line 65 of file speex_jitter.h.
span
spx_uint32_t JitterBufferPacket::span
Time covered by the packet (same units as timestamp)
Definition at line 64 of file speex_jitter.h.
timestamp
spx_uint32_t JitterBufferPacket::timestamp
Timestamp for the packet.
Definition at line 63 of file speex_jitter.h.
user_data
spx_uint32_t JitterBufferPacket::user_data
Put whatever data you like here (it's ignored by the jitter buffer)
Definition at line 66 of file speex_jitter.h.