ZEQ2-Lite: Source/Engine/tools/asm/mathlib.h File Reference
mathlib.h File Reference
#include <math.h>
Macros
#define DEG2RAD(a) (((a) * Q_PI) / 180.0F)
#define DotProduct(x, y) (x[0]*y[0]+x[1]*y[1]+x[2]*y[2])
#define EQUAL_EPSILON 0.001
#define PLANE_NON_AXIAL 3
#define PLANE_X 0
#define PLANE_Y 1
#define PLANE_Z 2
#define Q_PI 3.14159265358979323846
#define RAD2DEG(a) (((a) * 180.0f) / Q_PI)
#define SIDE_BACK 1
#define SIDE_CROSS -2
#define SIDE_FRONT 0
#define SIDE_ON 2
#define VectorAdd(a, b, c) {c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];}
#define VectorClear(x) {x[0] = x[1] = x[2] = 0;}
#define VectorCopy(a, b) {b[0]=a[0];b[1]=a[1];b[2]=a[2];}
#define VectorNegate(x) {x[0]=-x[0];x[1]=-x[1];x[2]=-x[2];}
#define VectorScale(a, b, c) {c[0]=b*a[0];c[1]=b*a[1];c[2]=b*a[2];}
#define VectorSubtract(a, b, c) {c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];}
Typedefs
typedef vec_t vec2_t[3]
typedef vec_t vec3_t[3]
typedef vec_t vec4_t[4]
typedef float vec_t
Functions
vec_t _DotProduct (vec3_t v1, vec3_t v2)
void _VectorAdd (vec3_t va, vec3_t vb, vec3_t out)
void _VectorCopy (vec3_t in, vec3_t out)
void _VectorScale (vec3_t v, vec_t scale, vec3_t out)
void _VectorSubtract (vec3_t va, vec3_t vb, vec3_t out)
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
void ClearBounds (vec3_t mins, vec3_t maxs)
vec_t ColorNormalize (const vec3_t in, vec3_t out)
void CrossProduct (const vec3_t v1, const vec3_t v2, vec3_t cross)
void NormalToLatLong (const vec3_t normal, byte bytes[2])
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
int PlaneTypeForNormal (vec3_t normal)
vec_t Q_rint (vec_t in)
void Vec10Copy (vec_t *in, vec_t *out)
qboolean VectorCompare (const vec3_t v1, const vec3_t v2)
void VectorInverse (vec3_t v)
double VectorLength (const vec3_t v)
void VectorMA (const vec3_t va, double scale, const vec3_t vb, vec3_t vc)
vec_t VectorNormalize (const vec3_t in, vec3_t out)
Variables
vec3_t vec3_origin
Macro Definition Documentation
DEG2RAD
#define DEG2RAD (a) (((a) * Q_PI) / 180.0F)
Definition at line 44 of file mathlib.h.
DotProduct
#define DotProduct (x, y) (x[0]*y[0]+x[1]*y[1]+x[2]*y[2])
Definition at line 60 of file mathlib.h.
EQUAL_EPSILON
#define EQUAL_EPSILON 0.001
Definition at line 49 of file mathlib.h.
PLANE_NON_AXIAL
#define PLANE_NON_AXIAL 3
Definition at line 56 of file mathlib.h.
PLANE_X
#define PLANE_X 0
Definition at line 53 of file mathlib.h.
PLANE_Y
#define PLANE_Y 1
Definition at line 54 of file mathlib.h.
PLANE_Z
#define PLANE_Z 2
Definition at line 55 of file mathlib.h.
Q_PI
#define Q_PI 3.14159265358979323846
Definition at line 43 of file mathlib.h.
RAD2DEG
#define RAD2DEG (a) (((a) * 180.0f) / Q_PI)
Definition at line 45 of file mathlib.h.
SIDE_BACK
#define SIDE_BACK 1
Definition at line 40 of file mathlib.h.
SIDE_CROSS
#define SIDE_CROSS -2
Definition at line 41 of file mathlib.h.
SIDE_FRONT
#define SIDE_FRONT 0
Definition at line 38 of file mathlib.h.
SIDE_ON
#define SIDE_ON 2
Definition at line 39 of file mathlib.h.
VectorAdd
#define VectorAdd (a, b, c) {c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];}
Definition at line 62 of file mathlib.h.
VectorClear
#define VectorClear (x) {x[0] = x[1] = x[2] = 0;}
Definition at line 65 of file mathlib.h.
VectorCopy
#define VectorCopy (a, b) {b[0]=a[0];b[1]=a[1];b[2]=a[2];}
Definition at line 63 of file mathlib.h.
VectorNegate
#define VectorNegate (x) {x[0]=-x[0];x[1]=-x[1];x[2]=-x[2];}
Definition at line 66 of file mathlib.h.
VectorScale
#define VectorScale (a, b, c) {c[0]=b*a[0];c[1]=b*a[1];c[2]=b*a[2];}
Definition at line 64 of file mathlib.h.
VectorSubtract
#define VectorSubtract (a, b, c) {c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];}
Definition at line 61 of file mathlib.h.
Typedef Documentation
vec2_t
typedef vec_t vec2_t[3]
Definition at line 34 of file mathlib.h.
vec3_t
typedef vec_t vec3_t[3]
Definition at line 35 of file mathlib.h.
vec4_t
typedef vec_t vec4_t[4]
Definition at line 36 of file mathlib.h.
vec_t
typedef float vec_t
Definition at line 32 of file mathlib.h.
Function Documentation
_DotProduct()
vec_t _DotProduct (vec3_t v1, vec3_t v2)
Definition at line 917 of file q_math.c.
{
     return v1[0]*v2[0] + v1[1]*v2[1] + v1[2]*v2[2];
 }
_VectorAdd()
void _VectorAdd (vec3_t va, vec3_t vb, vec3_t out)
Definition at line 927 of file q_math.c.
{
     out[0] = veca[0]+vecb[0];
     out[1] = veca[1]+vecb[1];
     out[2] = veca[2]+vecb[2];
 }
_VectorCopy()
void _VectorCopy (vec3_t in, vec3_t out)
Definition at line 933 of file q_math.c.
{
     out[0] = in[0];
     out[1] = in[1];
     out[2] = in[2];
 }
_VectorScale()
void _VectorScale (vec3_t v, vec_t scale, vec3_t out)
Definition at line 939 of file q_math.c.
{
     out[0] = in[0]*scale;
     out[1] = in[1]*scale;
     out[2] = in[2]*scale;
 }
_VectorSubtract()
void _VectorSubtract (vec3_t va, vec3_t vb, vec3_t out)
Definition at line 921 of file q_math.c.
{
     out[0] = veca[0]-vecb[0];
     out[1] = veca[1]-vecb[1];
     out[2] = veca[2]-vecb[2];
 }
AddPointToBounds()
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 798 of file q_math.c.
{
     if ( v[0] < mins[0] ) {
         mins[0] = v[0];
     }
     if ( v[0] > maxs[0]) {
         maxs[0] = v[0];
     }
     if ( v[1] < mins[1] ) {
         mins[1] = v[1];
     }
     if ( v[1] > maxs[1]) {
         maxs[1] = v[1];
     }
     if ( v[2] < mins[2] ) {
         mins[2] = v[2];
     }
     if ( v[2] > maxs[2]) {
         maxs[2] = v[2];
     }
 }
Referenced by CM_GeneratePatchCollide(), ParseTriSurf(), R_CreateSurfaceGridMesh(), R_MarkFragments(), RE_AddPolyToScene(), and Think_SpawnNewDoorTrigger().
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 793 of file q_math.c.
{
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
Referenced by CM_GeneratePatchCollide(), ParseTriSurf(), R_AddWorldSurfaces(), R_CreateSurfaceGridMesh(), and R_MarkFragments().
ColorNormalize()
vec_t ColorNormalize (const vec3_t in, vec3_t out)
CrossProduct()
void CrossProduct (const vec3_t v1, const vec3_t v2, vec3_t cross)
Referenced by AddWindingToConvexHull(), Autosprite2Deform(), BaseWindingForPlane(), CG_AddScorePlum(), CG_Aura_DrawInnerSpike(), CG_Aura_DrawSpike(), CG_Aura_SetHullAttributes(), CG_BezierVerts(), CG_DrawLine(), CG_DrawLineRGBA(), CG_GetTrailVerts(), CG_ImpactMark(), CG_LerpSpike(), CG_Portal(), CheckWinding(), CM_AddFacetBevels(), CM_PlaneFromPoints(), DebugLine(), DeformText(), DistancePointLine(), MakeMeshNormals(), MakeNormalVectors(), PlaneFromPoints(), PM_SlideMove(), PSys_AccumulateParticle(), R_GetPortalOrientations(), R_MarkFragments(), RB_DrawSun(), RB_ShadowTessEnd(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RotateAroundDirection(), RotatePointAroundVector(), WindingArea(), and WindingPlane().
NormalToLatLong()
void NormalToLatLong (const vec3_t normal, byte bytes[2])
PlaneFromPoints()
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
Definition at line 270 of file q_math.c.
{
     vec3_t  d1, d2;
     VectorSubtract( b, a, d1 );
     VectorSubtract( c, a, d2 );
     CrossProduct( d2, d1, plane );
     if ( VectorNormalize( plane ) == 0 ) {
         return qfalse;
     }
     plane[3] = DotProduct( a, plane );
     return qtrue;
 }
Referenced by R_PlaneForSurface().
PlaneTypeForNormal()
int PlaneTypeForNormal (vec3_t normal)
Referenced by CMod_LoadPlanes(), ParseFace(), and R_LoadPlanes().
Q_rint()
vec_t Q_rint (vec_t in)
Vec10Copy()
void Vec10Copy (vec_t * in, vec_t * out)
VectorCompare()
qboolean VectorCompare (const vec3_t v1, const vec3_t v2)
Referenced by CG_PredictPlayerState(), G_SetMovedir(), InitTrigger(), R_BonesStillValid(), R_GLSL_SetUniform_AmbientLight(), R_GLSL_SetUniform_DirectedLight(), R_GLSL_SetUniform_DynamicLight(), R_GLSL_SetUniform_LightDirection(), and R_GLSL_SetUniform_ViewOrigin().
VectorInverse()
void VectorInverse (vec3_t v)
Referenced by BG_LerpQuadraticSplineDelta(), CG_Aura_BuildTailPoint(), CreateRotationMatrix(), G_CreateRotationMatrix(), and R_MarkFragments().
VectorLength()
double VectorLength (const vec3_t v)
Referenced by AutospriteDeform(), CG_AddPlayerWeapon(), CG_AddScorePlum(), CG_AddTrailsToScene(), CG_DamageFeedback(), CG_DrawRadarBlips(), CG_LerpSpike(), CG_PredictPlayerState(), CG_TrailFunc_FadeTail(), CheckWinding(), CM_NeedsSubdivision(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), ComputeColors(), DistancePointLine(), DistancePointToLine(), Fire_UserWeapon(), G_BounceUserMissile(), G_ImpactUserWeapon(), G_PushUserMissile(), G_UserRadiusDamage(), InitMover(), ParseMesh(), PM_AirMove(), PM_CheckHover(), PM_ContinueLegsAnim(), PM_Crash(), PM_DashMove(), PM_FlyMove(), PM_ForceLegsAnim(), PM_Friction(), PM_NoclipMove(), PM_StartLegsAnim(), PM_WalkMove(), PM_Weapon(), PSys_ApplyPlaneConstraint(), PSys_UpdateOrientation(), R_ComputeIQMFogNum(), R_CreateSurfaceGridMesh(), R_RotateForEntity(), R_SetupEntityLighting(), RadiusFromBounds(), Reached_Train(), SelectNearestDeathmatchSpawnPoint(), SelectRandomFurthestSpawnPoint(), Think_CylinderHoming(), Think_Guided(), Think_Homing(), and WindingArea().
VectorMA()
void VectorMA (const vec3_t va, double scale, const vec3_t vb, vec3_t vc)
Referenced by Autosprite2Deform(), BaseWindingForPlane(), BG_EvaluateTrajectory(), BG_EvaluateTrajectoryDelta(), CalcMuzzlePoint(), CalcMuzzlePointOrigin(), CG_AddScorePlum(), CG_Aura_BuildTailPoint(), CG_Aura_DrawInnerSpike(), CG_Aura_DrawSpike(), CG_Aura_MarkRootPoint(), CG_AuraStart(), CG_BezierVerts(), CG_BreathPuffs(), CG_BubblesTrail(), CG_BubbleTrail(), CG_CalcMuzzlePoint(), CG_CalcViewValues(), CG_Camera(), CG_DamageBlendBlob(), CG_DrawCrosshair(), CG_DrawLine(), CG_DrawLineRGBA(), CG_GetTagOrientationFromPlayerEntityCameraModel(), CG_GetTagOrientationFromPlayerEntityHeadModel(), CG_GetTagOrientationFromPlayerEntityLegsModel(), CG_GetTagOrientationFromPlayerEntityTorsoModel(), CG_GetTagPosition(), CG_GetTrailVerts(), CG_InnerAuraSpikes(), CG_LerpSpike(), CG_LerpTrails(), CG_PositionEntityOnTag(), CG_PositionRotatedEntityOnTag(), CG_ReflectVelocity(), CG_ScanForCrosshairEntity(), CG_Tracer(), CM_EdgePlaneNum(), CM_ProjectPointOntoVector(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), DebugLine(), DeformText(), DoRailCore(), DrawNormals(), Fire_UserWeapon(), G_BounceUserMissile(), G_CheckProxMinePosition(), G_HoldUserMissile(), MakeNormalVectors(), PM_CheckDirection(), PM_NoclipMove(), PM_SlideMove(), PM_VerifyTrace(), PodiumPlacementThink(), PSys_AccumulateParticle(), PSys_ApplyDistanceConstraint(), PSys_ApplyDistanceMaxConstraint(), PSys_ApplyDistanceMinConstraint(), PSys_ApplyPlaneConstraint(), PSys_UpdateEmitters(), PSys_UpdateOrientation(), R_CalcBone(), R_CalcBoneLerp(), R_ComputeIQMFogNum(), R_CullLocalBox(), R_GetPortalOrientations(), R_MarkFragments(), R_MirrorPoint(), R_MirrorVector(), R_SetupEntityLighting(), R_SetupEntityLightingGrid(), R_SetupFrustum(), RaySphereIntersections(), RB_ProjectionShadowDeform(), RB_ShadowTessEnd(), RB_SurfaceSprite(), SP_func_button(), SP_func_door(), SpawnModelOnVictoryPad(), SpawnPodium(), Think_CylinderHoming(), Think_Homing(), UI_PositionEntityOnTag(), UI_PositionRotatedEntityOnTag(), and UserHitscan_Fire().
VectorNormalize()
vec_t VectorNormalize (const vec3_t in, vec3_t out)
Referenced by AimAtTarget(), Autosprite2Deform(), BG_EvaluateTrajectory(), BG_EvaluateTrajectoryDelta(), CG_AddScorePlum(), CG_AddTrailsToScene(), CG_Aura_DrawInnerSpike(), CG_Aura_DrawSpike(), CG_Aura_MarkRootPoint(), CG_Aura_SetHullAttributes(), CG_BeamTableUpdate(), CG_BezierMidPoints(), CG_BezierVerts(), CG_BubbleTrail(), CG_Camera(), CG_DirtPush(), CG_DrawLine(), CG_DrawLineRGBA(), CG_GetTrailVerts(), CG_LerpSpike(), CG_LerpTrails(), CG_MakeUserExplosion(), CG_TessCount(), CG_Tracer(), CG_WaterRipple(), CG_WaterSplash(), CM_AddFacetBevels(), CM_PlaneFromPoints(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), DebugLine(), Fire_UserWeapon(), G_PushUserMissile(), G_UserWeaponDamage(), locateCamera(), ParseShader(), PM_AirMove(), PM_CheckJump(), PM_CheckKnockback(), PM_CheckZanzoken(), PM_DashMove(), PM_FlyMove(), PM_NoclipMove(), PM_SlideMove(), PM_WalkMove(), PSys_AccumulateParticle(), PSys_ApplyDistanceConstraint(), PSys_ApplyDistanceMaxConstraint(), PSys_ApplyDistanceMinConstraint(), PSys_UpdateEmitters(), R_InitSkyTexCoords(), R_LerpTag(), R_SetupEntityLighting(), R_SubdividePatchToGrid(), RaySphereIntersections(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), RE_LoadWorldMap(), S_SpatializeOrigin(), Think_CylinderHoming(), Think_Guided(), Think_Homing(), Think_NormalMissileBurnPlayer(), Think_NormalMissileRidePlayer(), Think_NormalMissileStruggle(), and Think_NormalMissileStrugglePlayer().
Variable Documentation
vec3_origin
vec3_t vec3_origin
Definition at line 34 of file q_math.c.
Referenced by AddSkyPolygon(), AutospriteDeform(), BaseWindingForPlane(), CanDamage(), CG_AddPlayerWeapon(), CG_Aura_AddSounds(), CG_ClipMoveToEntities(), CG_DamageFeedback(), CG_EntityEffects(), CG_EntityEvent(), CG_Player(), CG_Portal(), CM_AddFacetBevels(), CM_BoxTrace(), CM_DrawDebugSurface(), CM_Trace(), CM_TransformedBoxTrace(), CM_ValidateFacet(), FindIntermissionPoint(), G_TryPushingProxMine(), InitTrigger(), MainMenu_DrawPlayer(), PM_NoclipMove(), R_GetPortalOrientations(), R_LoadFogs(), R_MirrorViewBySurface(), RB_AddQuadStampExt(), RB_SurfaceSprite(), SelectCTFSpawnPoint(), SelectInitialSpawnPoint(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_EntityContact(), SV_PointContents(), SV_Trace(), and WindingCenter().