ZEQ2-Lite: Tools/MinGW/include/wchar.h File Reference
wchar.h File Reference
#include <_mingw.h>
#include <stddef.h>
#include <wctype.h>
#include <sys/types.h>
#include <stdint.h>
Data Structures
struct _iobuf
struct _stat
struct _wfinddata_t
struct _wfinddatai64_t
struct stat
struct tm
Macros
#define __need_NULL
#define __need_size_t
#define __need_wchar_t
#define __need_wint_t
#define __VALIST char*
#define _FILE_DEFINED
#define _FSIZE_T_DEFINED
#define _STAT_DEFINED
#define _TM_DEFINED
#define _wcscmpi _wcsicmp
#define _WDIRECT_DEFINED
#define _WFINDDATA_T_DEFINED
#define _WIO_DEFINED
#define _WLOCALE_DEFINED
#define _WPROCESS_DEFINED
#define _WSTAT_DEFINED
#define _WSTDIO_DEFINED
#define _WSTDLIB_DEFINED
#define _WSTRING_DEFINED
#define _WTIME_DEFINED
#define WCHAR_MAX 0xffff
#define WCHAR_MIN 0
#define WEOF (wchar_t)(0xFFFF)
Typedefs
typedef unsigned long _fsize_t
typedef wchar_t _Wint_t
typedef int mbstate_t
Functions
_CRTIMP int __cdecl __MINGW_NOTHROW _snwprintf (wchar_t *, size_t, const wchar_t *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW _vsnwprintf (wchar_t *, size_t, const wchar_t *, __VALIST)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsdup (const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsicmp (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsicoll (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcslwr (wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsnicmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsnset (wchar_t *, wchar_t, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsrev (wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsset (wchar_t *, wchar_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wcsupr (wchar_t *)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecl (const wchar_t *, const wchar_t *,...)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecle (const wchar_t *, const wchar_t *,...)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexeclp (const wchar_t *, const wchar_t *,...)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexeclpe (const wchar_t *, const wchar_t *,...)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecv (const wchar_t *, const wchar_t *const *)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecve (const wchar_t *, const wchar_t *const *, const wchar_t *const *)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecvp (const wchar_t *, const wchar_t *const *)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecvpe (const wchar_t *, const wchar_t *const *, const wchar_t *const *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW _wsetlocale (int, const wchar_t *)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnl (int, const wchar_t *, const wchar_t *,...)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnle (int, const wchar_t *, const wchar_t *,...)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnlp (int, const wchar_t *, const wchar_t *,...)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnlpe (int, const wchar_t *, const wchar_t *,...)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnv (int, const wchar_t *, const wchar_t *const *)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnve (int, const wchar_t *, const wchar_t *const *, const wchar_t *const *)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnvp (int, const wchar_t *, const wchar_t *const *)
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnvpe (int, const wchar_t *, const wchar_t *const *, const wchar_t *const *)
wint_t __cdecl __MINGW_NOTHROW btowc (int)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fgetwc (FILE *)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fputwc (wchar_t, FILE *)
int __cdecl __MINGW_NOTHROW fwide (FILE *, int)
__CRT_INLINE int __cdecl __MINGW_NOTHROW fwide (FILE *__UNUSED_PARAM(stream), int mode)
_CRTIMP int __cdecl __MINGW_NOTHROW fwprintf (FILE *, const wchar_t *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW fwscanf (FILE *, const wchar_t *,...)
size_t __cdecl __MINGW_NOTHROW mbrlen (const char *__restrict__, size_t, mbstate_t *__restrict__)
size_t __cdecl __MINGW_NOTHROW mbrtowc (wchar_t *__restrict__, const char *__restrict__, size_t, mbstate_t *__restrict__)
int __cdecl __MINGW_NOTHROW mbsinit (const mbstate_t *)
__CRT_INLINE int __cdecl __MINGW_NOTHROW mbsinit (const mbstate_t *__UNUSED_PARAM(ps))
size_t __cdecl __MINGW_NOTHROW mbsrtowcs (wchar_t *__restrict__, const char **__restrict__, size_t, mbstate_t *__restrict__)
int __cdecl __MINGW_NOTHROW snwprintf (wchar_t *, size_t, const wchar_t *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW swprintf (wchar_t *, const wchar_t *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW swscanf (const wchar_t *, const wchar_t *,...)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW ungetwc (wchar_t, FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW vfwprintf (FILE *, const wchar_t *, __VALIST)
int __cdecl __MINGW_NOTHROW vfwscanf (FILE *__restrict__, const wchar_t *__restrict__, __VALIST)
int __cdecl __MINGW_NOTHROW vsnwprintf (wchar_t *, size_t, const wchar_t *, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW vswprintf (wchar_t *, const wchar_t *, __VALIST)
int __cdecl __MINGW_NOTHROW vswscanf (const wchar_t *__restrict__, const wchar_t *__restrict__, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW vwprintf (const wchar_t *, __VALIST)
int __cdecl __MINGW_NOTHROW vwscanf (const wchar_t *__restrict__, __VALIST)
size_t __cdecl __MINGW_NOTHROW wcrtomb (char *__restrict__, wchar_t, mbstate_t *__restrict__)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcscat (wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcschr (const wchar_t *, wchar_t)
_CRTIMP int __cdecl __MINGW_NOTHROW wcscmp (const wchar_t *, const wchar_t *)
int __cdecl __MINGW_NOTHROW wcscmpi (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW wcscoll (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcscpy (wchar_t *, const wchar_t *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcscspn (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsdup (const wchar_t *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsftime (wchar_t *, size_t, const wchar_t *, const struct tm *)
_CRTIMP int __cdecl __MINGW_NOTHROW wcsicmp (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW wcsicoll (const wchar_t *, const wchar_t *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcslen (const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcslwr (wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsncat (wchar_t *, const wchar_t *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW wcsncmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsncpy (wchar_t *, const wchar_t *, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW wcsnicmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsnset (wchar_t *, wchar_t, size_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcspbrk (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsrchr (const wchar_t *, wchar_t)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsrev (wchar_t *)
size_t __cdecl __MINGW_NOTHROW wcsrtombs (char *__restrict__, const wchar_t **__restrict__, size_t, mbstate_t *__restrict__)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsset (wchar_t *, wchar_t)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsspn (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsstr (const wchar_t *, const wchar_t *)
_CRTIMP double __cdecl __MINGW_NOTHROW wcstod (const wchar_t *, wchar_t **)
float __cdecl __MINGW_NOTHROW wcstof (const wchar_t *__restrict__, wchar_t **__restrict__)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcstok (wchar_t *, const wchar_t *)
_CRTIMP long __cdecl __MINGW_NOTHROW wcstol (const wchar_t *, wchar_t **, int)
long double __cdecl __MINGW_NOTHROW wcstold (const wchar_t *__restrict__, wchar_t **__restrict__)
long long __cdecl __MINGW_NOTHROW wcstoll (const wchar_t *__restrict__, wchar_t **__restrict__, int)
_CRTIMP unsigned long __cdecl __MINGW_NOTHROW wcstoul (const wchar_t *, wchar_t **, int)
unsigned long long __cdecl __MINGW_NOTHROW wcstoull (const wchar_t *__restrict__, wchar_t **__restrict__, int)
_CRTIMP wchar_t *__cdecl __MINGW_NOTHROW wcsupr (wchar_t *)
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsxfrm (wchar_t *, const wchar_t *, size_t)
int __cdecl __MINGW_NOTHROW wctob (wint_t)
wchar_t *__cdecl __MINGW_NOTHROW wmemchr (const wchar_t *, wchar_t, size_t)
int wmemcmp (const wchar_t *, const wchar_t *, size_t)
wchar_t *__cdecl __MINGW_NOTHROW wmemcpy (wchar_t *__restrict__, const wchar_t *__restrict__, size_t)
wchar_t *__cdecl __MINGW_NOTHROW wmemmove (wchar_t *s1, const wchar_t *, size_t)
wchar_t *__cdecl __MINGW_NOTHROW wmemset (wchar_t *, wchar_t, size_t)
_CRTIMP int __cdecl __MINGW_NOTHROW wprintf (const wchar_t *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW wscanf (const wchar_t *,...)
Macro Definition Documentation
__need_NULL
#define __need_NULL
Definition at line 25 of file wchar.h.
__need_size_t
#define __need_size_t
Definition at line 22 of file wchar.h.
__need_wchar_t
#define __need_wchar_t
Definition at line 24 of file wchar.h.
__need_wint_t
#define __need_wint_t
Definition at line 23 of file wchar.h.
__VALIST
#define __VALIST char*
Definition at line 34 of file wchar.h.
_FILE_DEFINED
#define _FILE_DEFINED
Definition at line 67 of file wchar.h.
_FSIZE_T_DEFINED
#define _FSIZE_T_DEFINED
Definition at line 338 of file wchar.h.
_STAT_DEFINED
#define _STAT_DEFINED
Definition at line 581 of file wchar.h.
_TM_DEFINED
#define _TM_DEFINED
Definition at line 98 of file wchar.h.
_wcscmpi
#define _wcscmpi _wcsicmp
Definition at line 241 of file wchar.h.
_WDIRECT_DEFINED
#define _WDIRECT_DEFINED
Definition at line 459 of file wchar.h.
_WFINDDATA_T_DEFINED
#define _WFINDDATA_T_DEFINED
Definition at line 397 of file wchar.h.
_WIO_DEFINED
#define _WIO_DEFINED
Definition at line 447 of file wchar.h.
_WLOCALE_DEFINED
#define _WLOCALE_DEFINED
Definition at line 612 of file wchar.h.
_WPROCESS_DEFINED
#define _WPROCESS_DEFINED
Definition at line 635 of file wchar.h.
_WSTAT_DEFINED
#define _WSTAT_DEFINED
Definition at line 607 of file wchar.h.
_WSTDIO_DEFINED
#define _WSTDIO_DEFINED
Definition at line 160 of file wchar.h.
_WSTDLIB_DEFINED
#define _WSTDLIB_DEFINED
Definition at line 180 of file wchar.h.
_WSTRING_DEFINED
#define _WSTRING_DEFINED
Definition at line 283 of file wchar.h.
_WTIME_DEFINED
#define _WTIME_DEFINED
Definition at line 208 of file wchar.h.
WCHAR_MAX
#define WCHAR_MAX 0xffff
Definition at line 54 of file wchar.h.
WCHAR_MIN
#define WCHAR_MIN 0
Definition at line 53 of file wchar.h.
WEOF
#define WEOF (wchar_t)(0xFFFF)
Definition at line 57 of file wchar.h.
Typedef Documentation
_fsize_t
typedef unsigned long _fsize_t
Definition at line 337 of file wchar.h.
_Wint_t
typedef wchar_t _Wint_t
Definition at line 292 of file wchar.h.
mbstate_t
typedef int mbstate_t
Definition at line 295 of file wchar.h.
Function Documentation
_snwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW _snwprintf (wchar_t * , size_t , const wchar_t * , ...)
_vsnwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW _vsnwprintf (wchar_t * , size_t , const wchar_t * , __VALIST)
Referenced by vsnwprintf().
_wcsdup()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsdup (const wchar_t *)
_wcsicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsicmp (const wchar_t * , const wchar_t *)
Referenced by wcscmpi().
_wcsicoll()
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsicoll (const wchar_t * , const wchar_t *)
_wcslwr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcslwr (wchar_t *)
_wcsnicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _wcsnicmp (const wchar_t * , const wchar_t * , size_t)
_wcsnset()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsnset (wchar_t * , wchar_t , size_t)
_wcsrev()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsrev (wchar_t *)
_wcsset()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsset (wchar_t * , wchar_t)
_wcsupr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wcsupr (wchar_t *)
_wexecl()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecl (const wchar_t * , const wchar_t * , ...)
_wexecle()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecle (const wchar_t * , const wchar_t * , ...)
_wexeclp()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexeclp (const wchar_t * , const wchar_t * , ...)
_wexeclpe()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexeclpe (const wchar_t * , const wchar_t * , ...)
_wexecv()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecv (const wchar_t * , const wchar_t *const *)
_wexecve()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecve (const wchar_t * , const wchar_t *const * , const wchar_t *const *)
_wexecvp()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecvp (const wchar_t * , const wchar_t *const *)
_wexecvpe()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wexecvpe (const wchar_t * , const wchar_t *const * , const wchar_t *const *)
_wsetlocale()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW _wsetlocale (int , const wchar_t *)
_wspawnl()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnl (int , const wchar_t * , const wchar_t * , ...)
_wspawnle()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnle (int , const wchar_t * , const wchar_t * , ...)
_wspawnlp()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnlp (int , const wchar_t * , const wchar_t * , ...)
_wspawnlpe()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnlpe (int , const wchar_t * , const wchar_t * , ...)
_wspawnv()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnv (int , const wchar_t * , const wchar_t *const *)
_wspawnve()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnve (int , const wchar_t * , const wchar_t *const * , const wchar_t *const *)
_wspawnvp()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnvp (int , const wchar_t * , const wchar_t *const *)
_wspawnvpe()
_CRTIMP intptr_t __cdecl __MINGW_NOTHROW _wspawnvpe (int , const wchar_t * , const wchar_t *const * , const wchar_t *const *)
btowc()
wint_t __cdecl __MINGW_NOTHROW btowc (int)
fgetwc()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fgetwc (FILE *)
fputwc()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fputwc (wchar_t , FILE *)
fwide() [1/2]
int __cdecl __MINGW_NOTHROW fwide (FILE * , int)
fwide() [2/2]
__CRT_INLINE int __cdecl __MINGW_NOTHROW fwide (FILE * __UNUSED_PARAMstream, int mode)
Definition at line 314 of file wchar.h.
   {return mode;} /* Nothing to do  */
fwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW fwprintf (FILE * , const wchar_t * , ...)
fwscanf()
_CRTIMP int __cdecl __MINGW_NOTHROW fwscanf (FILE * , const wchar_t * , ...)
mbrlen()
size_t __cdecl __MINGW_NOTHROW mbrlen (const char * __restrict__, size_t , mbstate_t * __restrict__)
mbrtowc()
size_t __cdecl __MINGW_NOTHROW mbrtowc (wchar_t * __restrict__, const char * __restrict__, size_t , mbstate_t * __restrict__)
mbsinit() [1/2]
int __cdecl __MINGW_NOTHROW mbsinit (const mbstate_t *)
mbsinit() [2/2]
__CRT_INLINE int __cdecl __MINGW_NOTHROW mbsinit (const mbstate_t * __UNUSED_PARAMps)
Definition at line 317 of file wchar.h.
   {return 1;}
mbsrtowcs()
size_t __cdecl __MINGW_NOTHROW mbsrtowcs (wchar_t * __restrict__, const char ** __restrict__, size_t , mbstate_t * __restrict__)
snwprintf()
int __cdecl __MINGW_NOTHROW snwprintf (wchar_t * , size_t , const wchar_t * , ...)
swprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW swprintf (wchar_t * , const wchar_t * , ...)
swscanf()
_CRTIMP int __cdecl __MINGW_NOTHROW swscanf (const wchar_t * , const wchar_t * , ...)
ungetwc()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW ungetwc (wchar_t , FILE *)
vfwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vfwprintf (FILE * , const wchar_t * , __VALIST)
vfwscanf()
int __cdecl __MINGW_NOTHROW vfwscanf (FILE * __restrict__, const wchar_t * __restrict__, __VALIST)
vsnwprintf()
int __cdecl __MINGW_NOTHROW vsnwprintf (wchar_t * s, size_t n, const wchar_t * format, __VALIST arg)
Definition at line 150 of file wchar.h.
   { return _vsnwprintf ( s, n, format, arg);}
References _vsnwprintf().
vswprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vswprintf (wchar_t * , const wchar_t * , __VALIST)
vswscanf()
int __cdecl __MINGW_NOTHROW vswscanf (const wchar_t * __restrict__, const wchar_t * __restrict__, __VALIST)
vwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vwprintf (const wchar_t * , __VALIST)
vwscanf()
int __cdecl __MINGW_NOTHROW vwscanf (const wchar_t * __restrict__, __VALIST)
wcrtomb()
size_t __cdecl __MINGW_NOTHROW wcrtomb (char * __restrict__, wchar_t , mbstate_t * __restrict__)
wcscat()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcscat (wchar_t * , const wchar_t *)
wcschr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcschr (const wchar_t * , wchar_t)
wcscmp()
_CRTIMP int __cdecl __MINGW_NOTHROW wcscmp (const wchar_t * , const wchar_t *)
wcscmpi()
int __cdecl __MINGW_NOTHROW wcscmpi (const wchar_t * __ws1, const wchar_t * __ws2)
Definition at line 267 of file wchar.h.
   {return _wcsicmp (__ws1, __ws2);}
References _wcsicmp().
wcscoll()
_CRTIMP int __cdecl __MINGW_NOTHROW wcscoll (const wchar_t * , const wchar_t *)
wcscpy()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcscpy (wchar_t * , const wchar_t *)
wcscspn()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcscspn (const wchar_t * , const wchar_t *)
wcsdup()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsdup (const wchar_t *)
wcsftime()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsftime (wchar_t * , size_t , const wchar_t * , const struct tm *)
wcsicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW wcsicmp (const wchar_t * , const wchar_t *)
wcsicoll()
_CRTIMP int __cdecl __MINGW_NOTHROW wcsicoll (const wchar_t * , const wchar_t *)
wcslen()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcslen (const wchar_t *)
wcslwr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcslwr (wchar_t *)
wcsncat()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsncat (wchar_t * , const wchar_t * , size_t)
wcsncmp()
_CRTIMP int __cdecl __MINGW_NOTHROW wcsncmp (const wchar_t * , const wchar_t * , size_t)
wcsncpy()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsncpy (wchar_t * , const wchar_t * , size_t)
wcsnicmp()
_CRTIMP int __cdecl __MINGW_NOTHROW wcsnicmp (const wchar_t * , const wchar_t * , size_t)
wcsnset()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsnset (wchar_t * , wchar_t , size_t)
wcspbrk()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcspbrk (const wchar_t * , const wchar_t *)
wcsrchr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsrchr (const wchar_t * , wchar_t)
wcsrev()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsrev (wchar_t *)
wcsrtombs()
size_t __cdecl __MINGW_NOTHROW wcsrtombs (char * __restrict__, const wchar_t ** __restrict__, size_t , mbstate_t * __restrict__)
wcsset()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsset (wchar_t * , wchar_t)
wcsspn()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsspn (const wchar_t * , const wchar_t *)
wcsstr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsstr (const wchar_t * , const wchar_t *)
wcstod()
_CRTIMP double __cdecl __MINGW_NOTHROW wcstod (const wchar_t * , wchar_t **)
wcstof()
float __cdecl __MINGW_NOTHROW wcstof (const wchar_t * __restrict__, wchar_t ** __restrict__)
wcstok()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcstok (wchar_t * , const wchar_t *)
wcstol()
_CRTIMP long __cdecl __MINGW_NOTHROW wcstol (const wchar_t * , wchar_t ** , int)
wcstold()
long double __cdecl __MINGW_NOTHROW wcstold (const wchar_t * __restrict__, wchar_t ** __restrict__)
wcstoll()
long long __cdecl __MINGW_NOTHROW wcstoll (const wchar_t * __restrict__, wchar_t ** __restrict__, int)
wcstoul()
_CRTIMP unsigned long __cdecl __MINGW_NOTHROW wcstoul (const wchar_t * , wchar_t ** , int)
wcstoull()
unsigned long long __cdecl __MINGW_NOTHROW wcstoull (const wchar_t * __restrict__, wchar_t ** __restrict__, int)
wcsupr()
_CRTIMP wchar_t* __cdecl __MINGW_NOTHROW wcsupr (wchar_t *)
wcsxfrm()
_CRTIMP size_t __cdecl __MINGW_NOTHROW wcsxfrm (wchar_t * , const wchar_t * , size_t)
wctob()
int __cdecl __MINGW_NOTHROW wctob (wint_t)
wmemchr()
wchar_t* __cdecl __MINGW_NOTHROW wmemchr (const wchar_t * , wchar_t , size_t)
wmemcmp()
int wmemcmp (const wchar_t * , const wchar_t * , size_t)
wmemcpy()
wchar_t* __cdecl __MINGW_NOTHROW wmemcpy (wchar_t * __restrict__, const wchar_t * __restrict__, size_t)
wmemmove()
wchar_t* __cdecl __MINGW_NOTHROW wmemmove (wchar_t * s1, const wchar_t * , size_t)
wmemset()
wchar_t* __cdecl __MINGW_NOTHROW wmemset (wchar_t * , wchar_t , size_t)
wprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW wprintf (const wchar_t * , ...)
wscanf()
_CRTIMP int __cdecl __MINGW_NOTHROW wscanf (const wchar_t * , ...)