ZEQ2-Lite: StringFormat Class Reference
StringFormat Class Reference
#include <gdiplusstringformat.h>
Public Member Functions
StringFormat (const StringFormat *format)
StringFormat (INT formatFlags=0, LANGID language=LANG_NEUTRAL)
~StringFormat ()
StringFormat * Clone () const
StringAlignment GetAlignment () const
LANGID GetDigitSubstitutionLanguage () const
StringDigitSubstitute GetDigitSubstitutionMethod () const
INT GetFormatFlags () const
HotkeyPrefix GetHotkeyPrefix () const
Status GetLastStatus () const
StringAlignment GetLineAlignment () const
INT GetMeasurableCharacterRangeCount () const
INT GetTabStopCount () const
Status GetTabStops (INT count, REAL *firstTabOffset, REAL *tabStops)
StringTrimming GetTrimming () const
Status SetAlignment (StringAlignment align)
Status SetDigitSubstitution (LANGID language, StringDigitSubstitute substitute)
Status SetFormatFlags (INT flags)
Status SetHotkeyPrefix (HotkeyPrefix hotkeyPrefix)
Status SetLineAlignment (StringAlignment align)
Status SetMeasurableCharacterRanges (INT rangeCount, const CharacterRange *ranges)
Status SetTabStops (REAL firstTabOffset, INT count, const REAL *tabStops)
Status SetTrimming (StringTrimming trimming)
Static Public Member Functions
static const StringFormat * GenericDefault ()
static const StringFormat * GenericTypographic ()
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
StringFormat (const StringFormat &)
StringFormat (GpStringFormat *stringFormat, Status status)
StringFormat & operator= (const StringFormat &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpStringFormat * nativeStringFormat
Friends
class Graphics
class GraphicsPath
Detailed Description
Definition at line 33 of file gdiplusstringformat.h.
Constructor & Destructor Documentation
StringFormat() [1/4]
StringFormat::StringFormat (INT formatFlags = 0, LANGID language = LANG_NEUTRAL) inline
Definition at line 42 of file gdiplusstringformat.h.
                                                                      :
             nativeStringFormat(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreateStringFormat(
                 formatFlags, language, &nativeStringFormat);
     }
References GdipCreateStringFormat(), lastStatus, and nativeStringFormat.
Referenced by Clone(), GenericDefault(), and GenericTypographic().
StringFormat() [2/4]
StringFormat::StringFormat (const StringFormat * format) inline
Definition at line 48 of file gdiplusstringformat.h.
                                             :
             nativeStringFormat(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCloneStringFormat(
                 format ? format->nativeStringFormat : NULL,
                 &nativeStringFormat);
     }
References GdipCloneStringFormat(), lastStatus, nativeStringFormat, and NULL.
~StringFormat()
StringFormat::~StringFormat () inline
Definition at line 55 of file gdiplusstringformat.h.
     {
         DllExports::GdipDeleteStringFormat(nativeStringFormat);
     }
References GdipDeleteStringFormat(), and nativeStringFormat.
StringFormat() [3/4]
StringFormat::StringFormat (GpStringFormat * stringFormat, Status status) inline private
Definition at line 199 of file gdiplusstringformat.h.
                                                              :
         nativeStringFormat(stringFormat), lastStatus(status) {}
StringFormat() [4/4]
StringFormat::StringFormat (const StringFormat &) private
Member Function Documentation
Clone()
StringFormat* StringFormat::Clone () const inline
Definition at line 59 of file gdiplusstringformat.h.
     {
         GpStringFormat *cloneStringFormat = NULL;
         Status status = updateStatus(DllExports::GdipCloneStringFormat(
                 nativeStringFormat, &cloneStringFormat));
         if (status == Ok) {
             StringFormat *result = new StringFormat(
                     cloneStringFormat, lastStatus);
             if (!result) {
                 DllExports::GdipDeleteStringFormat(cloneStringFormat);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneStringFormat(), GdipDeleteStringFormat(), lastStatus, nativeStringFormat, NULL, Ok, OutOfMemory, StringFormat(), and updateStatus().
GenericDefault()
const __inline__ StringFormat * StringFormat::GenericDefault () static
Definition at line 221 of file gdiplusstringformat.h.
 {
     if (!_GdipStringFormatCachedGenericDefault) {
         GpStringFormat *nativeStringFormat = 0;
         Status status = DllExports::GdipStringFormatGetGenericDefault(
                 &nativeStringFormat);
         if (status == Ok && nativeStringFormat) {
             _GdipStringFormatCachedGenericDefault = (void*)
                 new StringFormat(nativeStringFormat, Ok);
         }
     }
     return (StringFormat*) _GdipStringFormatCachedGenericDefault;
 }
References _GdipStringFormatCachedGenericDefault, GdipStringFormatGetGenericDefault(), nativeStringFormat, Ok, and StringFormat().
GenericTypographic()
const __inline__ StringFormat * StringFormat::GenericTypographic () static
Definition at line 235 of file gdiplusstringformat.h.
 {
     if (!_GdipStringFormatCachedGenericTypographic) {
         GpStringFormat *nativeStringFormat = 0;
         Status status = DllExports::GdipStringFormatGetGenericTypographic(
                 &nativeStringFormat);
         if (status == Ok && nativeStringFormat) {
             _GdipStringFormatCachedGenericTypographic = (void*)
                 new StringFormat(nativeStringFormat, Ok);
         }
     }
     return (StringFormat*) _GdipStringFormatCachedGenericTypographic;
 }
References _GdipStringFormatCachedGenericTypographic, GdipStringFormatGetGenericTypographic(), nativeStringFormat, Ok, and StringFormat().
GetAlignment()
StringAlignment StringFormat::GetAlignment () const inline
Definition at line 77 of file gdiplusstringformat.h.
     {
         StringAlignment result = StringAlignmentNear;
         updateStatus(DllExports::GdipGetStringFormatAlign(
                 nativeStringFormat, &result));
         return result;
     }
References GdipGetStringFormatAlign(), nativeStringFormat, StringAlignmentNear, and updateStatus().
GetDigitSubstitutionLanguage()
LANGID StringFormat::GetDigitSubstitutionLanguage () const inline
Definition at line 84 of file gdiplusstringformat.h.
     {
         LANGID result = 0;
         StringDigitSubstitute method;
         updateStatus(DllExports::GdipGetStringFormatDigitSubstitution(
                 nativeStringFormat, &result, &method));
         return result;
     }
References GdipGetStringFormatDigitSubstitution(), nativeStringFormat, and updateStatus().
GetDigitSubstitutionMethod()
StringDigitSubstitute StringFormat::GetDigitSubstitutionMethod () const inline
Definition at line 92 of file gdiplusstringformat.h.
     {
         LANGID language;
         StringDigitSubstitute result = StringDigitSubstituteUser;
         updateStatus(DllExports::GdipGetStringFormatDigitSubstitution(
                 nativeStringFormat, &language, &result));
         return result;
     }
References GdipGetStringFormatDigitSubstitution(), nativeStringFormat, StringDigitSubstituteUser, and updateStatus().
GetFormatFlags()
INT StringFormat::GetFormatFlags () const inline
Definition at line 100 of file gdiplusstringformat.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetStringFormatFlags(
                 nativeStringFormat, &result));
         return result;
     }
References GdipGetStringFormatFlags(), nativeStringFormat, and updateStatus().
GetHotkeyPrefix()
HotkeyPrefix StringFormat::GetHotkeyPrefix () const inline
Definition at line 107 of file gdiplusstringformat.h.
     {
         HotkeyPrefix result = HotkeyPrefixNone;
         updateStatus(DllExports::GdipGetStringFormatHotkeyPrefix(
                 nativeStringFormat, (INT*) &result));
         return result;
     }
References GdipGetStringFormatHotkeyPrefix(), HotkeyPrefixNone, nativeStringFormat, and updateStatus().
GetLastStatus()
Status StringFormat::GetLastStatus () const inline
Definition at line 114 of file gdiplusstringformat.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetLineAlignment()
StringAlignment StringFormat::GetLineAlignment () const inline
Definition at line 120 of file gdiplusstringformat.h.
     {
         StringAlignment result = StringAlignmentNear;
         updateStatus(DllExports::GdipGetStringFormatLineAlign(
                 nativeStringFormat, &result));
         return result;
     }
References GdipGetStringFormatLineAlign(), nativeStringFormat, StringAlignmentNear, and updateStatus().
GetMeasurableCharacterRangeCount()
INT StringFormat::GetMeasurableCharacterRangeCount () const inline
Definition at line 127 of file gdiplusstringformat.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetStringFormatMeasurableCharacterRangeCount(
                 nativeStringFormat, &result));
         return result;
     }
References GdipGetStringFormatMeasurableCharacterRangeCount(), nativeStringFormat, and updateStatus().
GetTabStopCount()
INT StringFormat::GetTabStopCount () const inline
Definition at line 134 of file gdiplusstringformat.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetStringFormatTabStopCount(
                 nativeStringFormat, &result));
         return result;
     }
References GdipGetStringFormatTabStopCount(), nativeStringFormat, and updateStatus().
GetTabStops()
Status StringFormat::GetTabStops (INT count, REAL * firstTabOffset, REAL * tabStops) inline
Definition at line 141 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipGetStringFormatTabStops(
                 nativeStringFormat, count,
                 firstTabOffset, tabStops));
     }
References GdipGetStringFormatTabStops(), nativeStringFormat, and updateStatus().
GetTrimming()
StringTrimming StringFormat::GetTrimming () const inline
Definition at line 147 of file gdiplusstringformat.h.
     {
         StringTrimming result = StringTrimmingNone;
         updateStatus(DllExports::GdipGetStringFormatTrimming(
                 nativeStringFormat, &result));
         return result;
     }
References GdipGetStringFormatTrimming(), nativeStringFormat, StringTrimmingNone, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
StringFormat& StringFormat::operator= (const StringFormat &) private
SetAlignment()
Status StringFormat::SetAlignment (StringAlignment align) inline
Definition at line 154 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipSetStringFormatAlign(
                 nativeStringFormat, align));
     }
References GdipSetStringFormatAlign(), nativeStringFormat, and updateStatus().
SetDigitSubstitution()
Status StringFormat::SetDigitSubstitution (LANGID language, StringDigitSubstitute substitute) inline
Definition at line 159 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipSetStringFormatDigitSubstitution(
                 nativeStringFormat, language, substitute));
     }
References GdipSetStringFormatDigitSubstitution(), nativeStringFormat, and updateStatus().
SetFormatFlags()
Status StringFormat::SetFormatFlags (INT flags) inline
Definition at line 165 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipSetStringFormatFlags(
                 nativeStringFormat, flags));
     }
References GdipSetStringFormatFlags(), nativeStringFormat, and updateStatus().
SetHotkeyPrefix()
Status StringFormat::SetHotkeyPrefix (HotkeyPrefix hotkeyPrefix) inline
Definition at line 170 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipSetStringFormatHotkeyPrefix(
                 nativeStringFormat, (INT) hotkeyPrefix));
     }
References GdipSetStringFormatHotkeyPrefix(), nativeStringFormat, and updateStatus().
SetLineAlignment()
Status StringFormat::SetLineAlignment (StringAlignment align) inline
Definition at line 175 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipSetStringFormatLineAlign(
                 nativeStringFormat, align));
     }
References GdipSetStringFormatLineAlign(), nativeStringFormat, and updateStatus().
SetMeasurableCharacterRanges()
Status StringFormat::SetMeasurableCharacterRanges (INT rangeCount, const CharacterRange * ranges) inline
Definition at line 180 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipSetStringFormatMeasurableCharacterRanges(
                 nativeStringFormat, rangeCount, ranges));
     }
References GdipSetStringFormatMeasurableCharacterRanges(), nativeStringFormat, and updateStatus().
SetTabStops()
Status StringFormat::SetTabStops (REAL firstTabOffset, INT count, const REAL * tabStops) inline
Definition at line 186 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipSetStringFormatTabStops(
                 nativeStringFormat, firstTabOffset,
                 count, tabStops));
     }
References GdipSetStringFormatTabStops(), nativeStringFormat, and updateStatus().
SetTrimming()
Status StringFormat::SetTrimming (StringTrimming trimming) inline
Definition at line 192 of file gdiplusstringformat.h.
     {
         return updateStatus(DllExports::GdipSetStringFormatTrimming(
                 nativeStringFormat, trimming));
     }
References GdipSetStringFormatTrimming(), nativeStringFormat, and updateStatus().
updateStatus()
Status StringFormat::updateStatus (Status newStatus) const inline private
Definition at line 204 of file gdiplusstringformat.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by Clone(), GetAlignment(), GetDigitSubstitutionLanguage(), GetDigitSubstitutionMethod(), GetFormatFlags(), GetHotkeyPrefix(), GetLineAlignment(), GetMeasurableCharacterRangeCount(), GetTabStopCount(), GetTabStops(), GetTrimming(), SetAlignment(), SetDigitSubstitution(), SetFormatFlags(), SetHotkeyPrefix(), SetLineAlignment(), SetMeasurableCharacterRanges(), SetTabStops(), and SetTrimming().
Friends And Related Function Documentation
Graphics
friend class Graphics friend
Definition at line 35 of file gdiplusstringformat.h.
GraphicsPath
friend class GraphicsPath friend
Definition at line 36 of file gdiplusstringformat.h.
Field Documentation
lastStatus
Status StringFormat::lastStatus mutable private
Definition at line 211 of file gdiplusstringformat.h.
Referenced by Clone(), GetLastStatus(), StringFormat(), and updateStatus().
nativeStringFormat
GpStringFormat* StringFormat::nativeStringFormat private
Definition at line 210 of file gdiplusstringformat.h.
Referenced by Clone(), GenericDefault(), GenericTypographic(), GetAlignment(), GetDigitSubstitutionLanguage(), GetDigitSubstitutionMethod(), GetFormatFlags(), GetHotkeyPrefix(), GetLineAlignment(), GetMeasurableCharacterRangeCount(), GetTabStopCount(), GetTabStops(), GetTrimming(), SetAlignment(), SetDigitSubstitution(), SetFormatFlags(), SetHotkeyPrefix(), SetLineAlignment(), SetMeasurableCharacterRanges(), SetTabStops(), SetTrimming(), StringFormat(), and ~StringFormat().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusstringformat.h