ZEQ2-Lite: Source/Engine/SDL12/include/SDL_active.h File Reference
SDL_active.h File Reference
#include "SDL_stdinc.h"
#include "SDL_error.h"
#include "begin_code.h"
#include "close_code.h"
The available application states
#define SDL_APPACTIVE 0x04
The application is active.
#define SDL_APPINPUTFOCUS 0x02
The app has input focus.
#define SDL_APPMOUSEFOCUS 0x01
The app has mouse coverage.
DECLSPEC Uint8 SDLCALL SDL_GetAppState (void)
This function returns the current state of the application, which is a bitwise combination of SDL_APPMOUSEFOCUS, SDL_APPINPUTFOCUS, and SDL_APPACTIVE.
Detailed Description
Include file for SDL application focus event handling
Definition in file SDL_active.h.
Macro Definition Documentation
SDL_APPACTIVE
#define SDL_APPACTIVE 0x04
The application is active.
Definition at line 44 of file SDL_active.h.
SDL_APPINPUTFOCUS
#define SDL_APPINPUTFOCUS 0x02
The app has input focus.
Definition at line 43 of file SDL_active.h.
SDL_APPMOUSEFOCUS
#define SDL_APPMOUSEFOCUS 0x01
The app has mouse coverage.
Definition at line 42 of file SDL_active.h.
Function Documentation
SDL_GetAppState()
DECLSPEC Uint8 SDLCALL SDL_GetAppState (void)
This function returns the current state of the application, which is a bitwise combination of SDL_APPMOUSEFOCUS, SDL_APPINPUTFOCUS, and SDL_APPACTIVE.
If SDL_APPACTIVE is set, then the user is able to see your application, otherwise it has been iconified or disabled.
Referenced by IN_DeactivateMouse(), IN_Frame(), and IN_Init().