ZEQ2-Lite: Source/Engine/libspeex/fixed_debug.h File Reference
fixed_debug.h File Reference
Fixed-point operations with debugging.
#include <stdio.h>
Macros
#define ADD16(a, b) _ADD16(a, b, __FILE__, __LINE__)
#define ADD32(a, b) _ADD32(a, b, __FILE__, __LINE__)
#define ADD64(a, b) (MIPS_INC(a)+(b))
#define DIV32(a, b) _DIV32(a, b, __FILE__, __LINE__)
#define DIV32_16(a, b) _DIV32_16(a, b, __FILE__, __LINE__)
#define EXTEND32(x) _EXTEND32(x, __FILE__, __LINE__)
#define EXTRACT16(x) _EXTRACT16(x, __FILE__, __LINE__)
#define MAC16_16(c, a, b) (spx_mips--,ADD32((c),MULT16_16((a),(b))))
#define MAC16_16_P13(c, a, b) (EXTRACT16(ADD32((c),SHR32(ADD32(4096,MULT16_16((a),(b))),13))))
#define MAC16_16_Q11(c, a, b) (EXTRACT16(ADD16((c),EXTRACT16(SHR32(MULT16_16((a),(b)),11)))))
#define MAC16_16_Q13(c, a, b) (EXTRACT16(ADD16((c),EXTRACT16(SHR32(MULT16_16((a),(b)),13)))))
#define MAC16_32_Q11(c, a, b) ADD32((c),MULT16_32_Q11((a),(b)))
#define MAC16_32_Q15(c, a, b) ADD32((c),MULT16_32_Q15((a),(b)))
#define MIPS_INC spx_mips++,
#define MULT16_16(a, b) _MULT16_16(a, b, __FILE__, __LINE__)
#define MULT16_32_P15(a, b) MULT16_32_PX(a,b,15)
#define MULT16_32_Q11(a, b) MULT16_32_QX(a,b,11)
#define MULT16_32_Q12(a, b) MULT16_32_QX(a,b,12)
#define MULT16_32_Q13(a, b) MULT16_32_QX(a,b,13)
#define MULT16_32_Q14(a, b) MULT16_32_QX(a,b,14)
#define MULT16_32_Q15(a, b) MULT16_32_QX(a,b,15)
#define MULT16_32_QX(a, b, Q) _MULT16_32_QX(a, b, Q, __FILE__, __LINE__)
#define PDIV32(a, b) DIV32(ADD32((a),(b)>>1),b)
#define PDIV32_16(a, b) DIV32_16(ADD32((a),(b)>>1),b)
#define PSHR16(a, shift) (SHR16(ADD16((a),((1<<((shift))>>1))),shift))
#define PSHR32(a, shift) (SHR32(ADD32((a),((1<<((shift))>>1))),shift))
#define QCONST16(x, bits) ((spx_word16_t)(.5+(x)*(((spx_word32_t)1)<<(bits))))
#define QCONST32(x, bits) ((spx_word32_t)(.5+(x)*(((spx_word32_t)1)<<(bits))))
#define SATURATE16(x, a) (((x)>(a) ? (a) : (x)<-(a) ? -(a) : (x)))
#define SATURATE32(x, a) (((x)>(a) ? (a) : (x)<-(a) ? -(a) : (x)))
#define SHL16(a, shift) _SHL16(a, shift, __FILE__, __LINE__)
#define SHR16(a, shift) _SHR16(a, shift, __FILE__, __LINE__)
#define SUB16(a, b) _SUB16(a, b, __FILE__, __LINE__)
#define VERIFY_INT(x) ((x)<=2147483647LL&&(x)>=-2147483648LL)
#define VERIFY_SHORT(x) ((x)<=32767&&(x)>=-32768)
#define VSHR32(a, shift) (((shift)>0) ? SHR32(a, shift) : SHL32(a, -(shift)))
Functions
static short _ADD16 (int a, int b, char *file, int line)
static int _ADD32 (long long a, long long b, char *file, int line)
static int _DIV32 (long long a, long long b, char *file, int line)
static int _DIV32_16 (long long a, long long b, char *file, int line)
static int _EXTEND32 (int x, char *file, int line)
static short _EXTRACT16 (int x, char *file, int line)
static int _MULT16_16 (int a, int b, char *file, int line)
static int _MULT16_32_QX (int a, long long b, int Q, char *file, int line)
static short _SHL16 (int a, int shift, char *file, int line)
static short _SHR16 (int a, int shift, char *file, int line)
static short _SUB16 (int a, int b, char *file, int line)
static short MULT16_16_16 (int a, int b)
static short MULT16_16_P13 (int a, int b)
static short MULT16_16_P14 (int a, int b)
static short MULT16_16_P15 (int a, int b)
static int MULT16_16_Q11_32 (int a, int b)
static short MULT16_16_Q13 (int a, int b)
static short MULT16_16_Q14 (int a, int b)
static short MULT16_16_Q15 (int a, int b)
static int MULT16_32_PX (int a, long long b, int Q)
static short NEG16 (int x)
static int NEG32 (long long x)
static int SATURATE (int a, int b)
static int SHL32 (long long a, int shift)
static int SHR32 (long long a, int shift)
static int SUB32 (long long a, long long b)
Variables
long long spx_mips
Detailed Description
Fixed-point operations with debugging.
Definition in file fixed_debug.h.
Macro Definition Documentation
ADD16
#define ADD16 (a, b) _ADD16(a, b, __FILE__, __LINE__)
Definition at line 173 of file fixed_debug.h.
ADD32
#define ADD32 (a, b) _ADD32(a, b, __FILE__, __LINE__)
Definition at line 205 of file fixed_debug.h.
ADD64
#define ADD64 (a, b) (MIPS_INC(a)+(b))
Definition at line 236 of file fixed_debug.h.
DIV32
#define DIV32 (a, b) _DIV32(a, b, __FILE__, __LINE__)
Definition at line 464 of file fixed_debug.h.
DIV32_16
#define DIV32_16 (a, b) _DIV32_16(a, b, __FILE__, __LINE__)
Definition at line 437 of file fixed_debug.h.
EXTEND32
#define EXTEND32 (x) _EXTEND32(x, __FILE__, __LINE__)
Definition at line 90 of file fixed_debug.h.
EXTRACT16
#define EXTRACT16 (x) _EXTRACT16(x, __FILE__, __LINE__)
Definition at line 77 of file fixed_debug.h.
MAC16_16
#define MAC16_16 (c, a, b) (spx_mips--,ADD32((c),MULT16_16((a),(b))))
Definition at line 268 of file fixed_debug.h.
MAC16_16_P13
#define MAC16_16_P13 (c, a, b) (EXTRACT16(ADD32((c),SHR32(ADD32(4096,MULT16_16((a),(b))),13))))
Definition at line 271 of file fixed_debug.h.
MAC16_16_Q11
#define MAC16_16_Q11 (c, a, b) (EXTRACT16(ADD16((c),EXTRACT16(SHR32(MULT16_16((a),(b)),11)))))
Definition at line 269 of file fixed_debug.h.
MAC16_16_Q13
#define MAC16_16_Q13 (c, a, b) (EXTRACT16(ADD16((c),EXTRACT16(SHR32(MULT16_16((a),(b)),13)))))
Definition at line 270 of file fixed_debug.h.
MAC16_32_Q11
#define MAC16_32_Q11 (c, a, b) ADD32((c),MULT16_32_Q11((a),(b)))
Definition at line 309 of file fixed_debug.h.
MAC16_32_Q15
#define MAC16_32_Q15 (c, a, b) ADD32((c),MULT16_32_Q15((a),(b)))
Definition at line 315 of file fixed_debug.h.
MIPS_INC
#define MIPS_INC spx_mips++,
Definition at line 41 of file fixed_debug.h.
MULT16_16
#define MULT16_16 (a, b) _MULT16_16(a, b, __FILE__, __LINE__)
Definition at line 253 of file fixed_debug.h.
MULT16_32_P15
#define MULT16_32_P15 (a, b) MULT16_32_PX(a,b,15)
Definition at line 314 of file fixed_debug.h.
MULT16_32_Q11
#define MULT16_32_Q11 (a, b) MULT16_32_QX(a,b,11)
Definition at line 308 of file fixed_debug.h.
MULT16_32_Q12
#define MULT16_32_Q12 (a, b) MULT16_32_QX(a,b,12)
Definition at line 310 of file fixed_debug.h.
MULT16_32_Q13
#define MULT16_32_Q13 (a, b) MULT16_32_QX(a,b,13)
Definition at line 311 of file fixed_debug.h.
MULT16_32_Q14
#define MULT16_32_Q14 (a, b) MULT16_32_QX(a,b,14)
Definition at line 312 of file fixed_debug.h.
MULT16_32_Q15
#define MULT16_32_Q15 (a, b) MULT16_32_QX(a,b,15)
Definition at line 313 of file fixed_debug.h.
MULT16_32_QX
#define MULT16_32_QX (a, b, Q) _MULT16_32_QX(a, b, Q, __FILE__, __LINE__)
Definition at line 274 of file fixed_debug.h.
PDIV32
#define PDIV32 (a, b) DIV32(ADD32((a),(b)>>1),b)
Definition at line 484 of file fixed_debug.h.
PDIV32_16
#define PDIV32_16 (a, b) DIV32_16(ADD32((a),(b)>>1),b)
Definition at line 485 of file fixed_debug.h.
PSHR16
#define PSHR16 (a, shift) (SHR16(ADD16((a),((1<<((shift))>>1))),shift))
Definition at line 163 of file fixed_debug.h.
PSHR32
#define PSHR32 (a, shift) (SHR32(ADD32((a),((1<<((shift))>>1))),shift))
Definition at line 164 of file fixed_debug.h.
QCONST16
#define QCONST16 (x, bits) ((spx_word16_t)(.5+(x)*(((spx_word32_t)1)<<(bits))))
Definition at line 43 of file fixed_debug.h.
QCONST32
#define QCONST32 (x, bits) ((spx_word32_t)(.5+(x)*(((spx_word32_t)1)<<(bits))))
Definition at line 44 of file fixed_debug.h.
SATURATE16
#define SATURATE16 (x, a) (((x)>(a) ? (a) : (x)<-(a) ? -(a) : (x)))
Definition at line 167 of file fixed_debug.h.
SATURATE32
#define SATURATE32 (x, a) (((x)>(a) ? (a) : (x)<-(a) ? -(a) : (x)))
Definition at line 168 of file fixed_debug.h.
SHL16
#define SHL16 (a, shift) _SHL16(a, shift, __FILE__, __LINE__)
Definition at line 117 of file fixed_debug.h.
SHR16
#define SHR16 (a, shift) _SHR16(a, shift, __FILE__, __LINE__)
Definition at line 103 of file fixed_debug.h.
SUB16
#define SUB16 (a, b) _SUB16(a, b, __FILE__, __LINE__)
Definition at line 190 of file fixed_debug.h.
VERIFY_INT
#define VERIFY_INT (x) ((x)<=2147483647LL&&(x)>=-2147483648LL)
Definition at line 48 of file fixed_debug.h.
VERIFY_SHORT
#define VERIFY_SHORT (x) ((x)<=32767&&(x)>=-32768)
Definition at line 47 of file fixed_debug.h.
VSHR32
#define VSHR32 (a, shift) (((shift)>0) ? SHR32(a, shift) : SHL32(a, -(shift)))
Definition at line 165 of file fixed_debug.h.
Function Documentation
_ADD16()
static short _ADD16 (int a, int b, char * file, int line) inline static
Definition at line 174 of file fixed_debug.h.
 {
    int res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "ADD16: inputs are not short: %d %d in %s: line %d\n", a, b, file, line);
    }
    res = a+b;
    if (!VERIFY_SHORT(res))
    {
       fprintf (stderr, "ADD16: output is not short: %d+%d=%d in %s: line %d\n", a,b,res, file, line);
    }
    spx_mips++;
    return res;
 }
References line, spx_mips, and VERIFY_SHORT.
_ADD32()
static int _ADD32 (long long a, long long b, char * file, int line) inline static
Definition at line 206 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_INT(a) || !VERIFY_INT(b))
    {
       fprintf (stderr, "ADD32: inputs are not int: %d %d in %s: line %d\n", (int)a, (int)b, file, line);
    }
    res = a+b;
    if (!VERIFY_INT(res))
    {
       fprintf (stderr, "ADD32: output is not int: %d in %s: line %d\n", (int)res, file, line);
    }
    spx_mips++;
    return res;
 }
References line, spx_mips, and VERIFY_INT.
_DIV32()
static int _DIV32 (long long a, long long b, char * file, int line) inline static
Definition at line 465 of file fixed_debug.h.
 {
    long long res;
    if (b==0)
    {
       fprintf(stderr, "DIV32: divide by zero: %d/%d in %s: line %d\n", (int)a, (int)b, file, line);
       return 0;
    }
    if (!VERIFY_INT(a) || !VERIFY_INT(b))
    {
       fprintf (stderr, "DIV32: inputs are not int/short: %d %d in %s: line %d\n", (int)a, (int)b, file, line);
    }
    res = a/b;
    if (!VERIFY_INT(res))
       fprintf (stderr, "DIV32: output is not int: %d in %s: line %d\n", (int)res, file, line);
    spx_mips+=36;
    return res;
 }
References line, spx_mips, and VERIFY_INT.
_DIV32_16()
static int _DIV32_16 (long long a, long long b, char * file, int line) inline static
Definition at line 439 of file fixed_debug.h.
 {
    long long res;
    if (b==0)
    {
       fprintf(stderr, "DIV32_16: divide by zero: %d/%d in %s: line %d\n", (int)a, (int)b, file, line);
       return 0;
    }
    if (!VERIFY_INT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "DIV32_16: inputs are not int/short: %d %d in %s: line %d\n", (int)a, (int)b, file, line);
    }
    res = a/b;
    if (!VERIFY_SHORT(res))
    {
       fprintf (stderr, "DIV32_16: output is not short: %d / %d = %d in %s: line %d\n", (int)a,(int)b,(int)res, file, line);
       if (res>32767)
          res = 32767;
       if (res<-32768)
          res = -32768;
    }
    spx_mips+=20;
    return res;
 }
References line, spx_mips, VERIFY_INT, and VERIFY_SHORT.
_EXTEND32()
static int _EXTEND32 (int x, char * file, int line) inline static
Definition at line 91 of file fixed_debug.h.
 {
    int res;
    if (!VERIFY_SHORT(x))
    {
       fprintf (stderr, "EXTEND32: input is not short: %d in %s: line %d\n", x, file, line);
    }
    res = x;
    spx_mips++;
    return res;
 }
References line, spx_mips, and VERIFY_SHORT.
_EXTRACT16()
static short _EXTRACT16 (int x, char * file, int line) inline static
Definition at line 78 of file fixed_debug.h.
 {
    int res;
    if (!VERIFY_SHORT(x))
    {
       fprintf (stderr, "EXTRACT16: input is not short: %d in %s: line %d\n", x, file, line);
    }
    res = x;
    spx_mips++;
    return res;
 }
References line, spx_mips, and VERIFY_SHORT.
_MULT16_16()
static int _MULT16_16 (int a, int b, char * file, int line) inline static
Definition at line 254 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16: inputs are not short: %d %d in %s: line %d\n", a, b, file, line);
    }
    res = ((long long)a)*b;
    if (!VERIFY_INT(res))
       fprintf (stderr, "MULT16_16: output is not int: %d in %s: line %d\n", (int)res, file, line);
    spx_mips++;
    return res;
 }
References file, line, long(), spx_mips, VERIFY_INT, and VERIFY_SHORT.
_MULT16_32_QX()
static int _MULT16_32_QX (int a, long long b, int Q, char * file, int line) inline static
Definition at line 275 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_INT(b))
    {
       fprintf (stderr, "MULT16_32_Q%d: inputs are not short+int: %d %d in %s: line %d\n", Q, (int)a, (int)b, file, line);
    }
    if (ABS32(b)>=(1<<(15+Q)))
       fprintf (stderr, "MULT16_32_Q%d: second operand too large: %d %d in %s: line %d\n", Q, (int)a, (int)b, file, line);
    res = (((long long)a)*(long long)b) >> Q;
    if (!VERIFY_INT(res))
       fprintf (stderr, "MULT16_32_Q%d: output is not int: %d*%d=%d in %s: line %d\n", Q, (int)a, (int)b,(int)res, file, line);
    spx_mips+=5;
    return res;
 }
References ABS32, file, int(), line, long(), spx_mips, VERIFY_INT, and VERIFY_SHORT.
_SHL16()
static short _SHL16 (int a, int shift, char * file, int line) inline static
Definition at line 118 of file fixed_debug.h.
 {
    int res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(shift))
    {
       fprintf (stderr, "SHL16: inputs are not short: %d %d in %s: line %d\n", a, shift, file, line);
    }
    res = a<<shift;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "SHL16: output is not short: %d in %s: line %d\n", res, file, line);
    spx_mips++;
    return res;
 }
References line, spx_mips, and VERIFY_SHORT.
_SHR16()
static short _SHR16 (int a, int shift, char * file, int line) inline static
Definition at line 104 of file fixed_debug.h.
 {
    int res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(shift))
    {
       fprintf (stderr, "SHR16: inputs are not short: %d >> %d in %s: line %d\n", a, shift, file, line);
    }
    res = a>>shift;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "SHR16: output is not short: %d in %s: line %d\n", res, file, line);
    spx_mips++;
    return res;
 }
References line, spx_mips, and VERIFY_SHORT.
_SUB16()
static short _SUB16 (int a, int b, char * file, int line) inline static
Definition at line 191 of file fixed_debug.h.
 {
    int res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "SUB16: inputs are not short: %d %d in %s: line %d\n", a, b, file, line);
    }
    res = a-b;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "SUB16: output is not short: %d in %s: line %d\n", res, file, line);
    spx_mips++;
    return res;
 }
References line, spx_mips, and VERIFY_SHORT.
MULT16_16_16()
static short MULT16_16_16 (int a, int b) inline static
Definition at line 239 of file fixed_debug.h.
 {
    int res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16_16: inputs are not short: %d %d\n", a, b);
    }
    res = a*b;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "MULT16_16_16: output is not short: %d\n", res);
    spx_mips++;
    return res;
 }
References spx_mips, and VERIFY_SHORT.
MULT16_16_P13()
static short MULT16_16_P13 (int a, int b) inline static
Definition at line 385 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16_P13: inputs are not short: %d %d\n", a, b);
    }
    res = ((long long)a)*b;
    res += 4096;
    if (!VERIFY_INT(res))
       fprintf (stderr, "MULT16_16_P13: overflow: %d*%d=%d\n", a, b, (int)res);
    res >>= 13;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "MULT16_16_P13: output is not short: %d*%d=%d\n", a, b, (int)res);
    spx_mips+=4;
    return res;
 }
References long(), spx_mips, VERIFY_INT, and VERIFY_SHORT.
MULT16_16_P14()
static short MULT16_16_P14 (int a, int b) inline static
Definition at line 402 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16_P14: inputs are not short: %d %d\n", a, b);
    }
    res = ((long long)a)*b;
    res += 8192;
    if (!VERIFY_INT(res))
       fprintf (stderr, "MULT16_16_P14: overflow: %d*%d=%d\n", a, b, (int)res);
    res >>= 14;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "MULT16_16_P14: output is not short: %d*%d=%d\n", a, b, (int)res);
    spx_mips+=4;
    return res;
 }
References long(), spx_mips, VERIFY_INT, and VERIFY_SHORT.
MULT16_16_P15()
static short MULT16_16_P15 (int a, int b) inline static
Definition at line 419 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16_P15: inputs are not short: %d %d\n", a, b);
    }
    res = ((long long)a)*b;
    res += 16384;
    if (!VERIFY_INT(res))
       fprintf (stderr, "MULT16_16_P15: overflow: %d*%d=%d\n", a, b, (int)res);
    res >>= 15;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "MULT16_16_P15: output is not short: %d*%d=%d\n", a, b, (int)res);
    spx_mips+=4;
    return res;
 }
References long(), spx_mips, VERIFY_INT, and VERIFY_SHORT.
MULT16_16_Q11_32()
static int MULT16_16_Q11_32 (int a, int b) inline static
Definition at line 326 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16_Q11: inputs are not short: %d %d\n", a, b);
    }
    res = ((long long)a)*b;
    res >>= 11;
    if (!VERIFY_INT(res))
       fprintf (stderr, "MULT16_16_Q11: output is not short: %d*%d=%d\n", (int)a, (int)b, (int)res);
    spx_mips+=3;
    return res;
 }
References int(), long(), spx_mips, VERIFY_INT, and VERIFY_SHORT.
MULT16_16_Q13()
static short MULT16_16_Q13 (int a, int b) inline static
Definition at line 340 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16_Q13: inputs are not short: %d %d\n", a, b);
    }
    res = ((long long)a)*b;
    res >>= 13;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "MULT16_16_Q13: output is not short: %d*%d=%d\n", a, b, (int)res);
    spx_mips+=3;
    return res;
 }
References long(), spx_mips, and VERIFY_SHORT.
MULT16_16_Q14()
static short MULT16_16_Q14 (int a, int b) inline static
Definition at line 354 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16_Q14: inputs are not short: %d %d\n", a, b);
    }
    res = ((long long)a)*b;
    res >>= 14;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "MULT16_16_Q14: output is not short: %d\n", (int)res);
    spx_mips+=3;
    return res;
 }
References long(), spx_mips, and VERIFY_SHORT.
MULT16_16_Q15()
static short MULT16_16_Q15 (int a, int b) inline static
Definition at line 368 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_SHORT(b))
    {
       fprintf (stderr, "MULT16_16_Q15: inputs are not short: %d %d\n", a, b);
    }
    res = ((long long)a)*b;
    res >>= 15;
    if (!VERIFY_SHORT(res))
    {
       fprintf (stderr, "MULT16_16_Q15: output is not short: %d\n", (int)res);
    }
    spx_mips+=3;
    return res;
 }
References long(), spx_mips, and VERIFY_SHORT.
MULT16_32_PX()
static int MULT16_32_PX (int a, long long b, int Q) inline static
Definition at line 291 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_SHORT(a) || !VERIFY_INT(b))
    {
       fprintf (stderr, "MULT16_32_P%d: inputs are not short+int: %d %d\n", Q, (int)a, (int)b);
    }
    if (ABS32(b)>=(1<<(15+Q)))
       fprintf (stderr, "MULT16_32_Q%d: second operand too large: %d %d\n", Q, (int)a, (int)b);
    res = ((((long long)a)*(long long)b) + ((1<<Q)>>1))>> Q;
    if (!VERIFY_INT(res))
       fprintf (stderr, "MULT16_32_P%d: output is not int: %d*%d=%d\n", Q, (int)a, (int)b,(int)res);
    spx_mips+=5;
    return res;
 }
References ABS32, int(), long(), spx_mips, VERIFY_INT, and VERIFY_SHORT.
NEG16()
static short NEG16 (int x) inline static
Definition at line 50 of file fixed_debug.h.
 {
    int res;
    if (!VERIFY_SHORT(x))
    {
       fprintf (stderr, "NEG16: input is not short: %d\n", (int)x);
    }
    res = -x;
    if (!VERIFY_SHORT(res))
       fprintf (stderr, "NEG16: output is not short: %d\n", (int)res);
    spx_mips++;
    return res;
 }
References spx_mips, and VERIFY_SHORT.
NEG32()
static int NEG32 (long long x) inline static
Definition at line 63 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_INT(x))
    {
       fprintf (stderr, "NEG16: input is not int: %d\n", (int)x);
    }
    res = -x;
    if (!VERIFY_INT(res))
       fprintf (stderr, "NEG16: output is not int: %d\n", (int)res);
    spx_mips++;
    return res;
 }
References spx_mips, and VERIFY_INT.
SATURATE()
static int SATURATE (int a, int b) inline static
Definition at line 317 of file fixed_debug.h.
 {
    if (a>b)
       a=b;
    if (a<-b)
       a = -b;
    return a;
 }
SHL32()
static int SHL32 (long long a, int shift) inline static
Definition at line 147 of file fixed_debug.h.
 {
    long long  res;
    if (!VERIFY_INT(a) || !VERIFY_SHORT(shift))
    {
       fprintf (stderr, "SHL32: inputs are not int: %d %d\n", (int)a, shift);
    }
    res = a<<shift;
    if (!VERIFY_INT(res))
    {
       fprintf (stderr, "SHL32: output is not int: %d\n", (int)res);
    }
    spx_mips++;
    return res;
 }
References spx_mips, VERIFY_INT, and VERIFY_SHORT.
SHR32()
static int SHR32 (long long a, int shift) inline static
Definition at line 132 of file fixed_debug.h.
 {
    long long  res;
    if (!VERIFY_INT(a) || !VERIFY_SHORT(shift))
    {
       fprintf (stderr, "SHR32: inputs are not int: %d %d\n", (int)a, shift);
    }
    res = a>>shift;
    if (!VERIFY_INT(res))
    {
       fprintf (stderr, "SHR32: output is not int: %d\n", (int)res);
    }
    spx_mips++;
    return res;
 }
References spx_mips, VERIFY_INT, and VERIFY_SHORT.
SUB32()
static int SUB32 (long long a, long long b) inline static
Definition at line 222 of file fixed_debug.h.
 {
    long long res;
    if (!VERIFY_INT(a) || !VERIFY_INT(b))
    {
       fprintf (stderr, "SUB32: inputs are not int: %d %d\n", (int)a, (int)b);
    }
    res = a-b;
    if (!VERIFY_INT(res))
       fprintf (stderr, "SUB32: output is not int: %d\n", (int)res);
    spx_mips++;
    return res;
 }
References spx_mips, and VERIFY_INT.
Variable Documentation
spx_mips
long long spx_mips
Referenced by _ADD16(), _ADD32(), _DIV32(), _DIV32_16(), _EXTEND32(), _EXTRACT16(), _MULT16_16(), _MULT16_32_QX(), _SHL16(), _SHR16(), _SUB16(), main(), MULT16_16_16(), MULT16_16_P13(), MULT16_16_P14(), MULT16_16_P15(), MULT16_16_Q11_32(), MULT16_16_Q13(), MULT16_16_Q14(), MULT16_16_Q15(), MULT16_32_PX(), NEG16(), NEG32(), SHL32(), SHR32(), and SUB32().