ZEQ2-Lite: Source/Engine/tools/lcc/src/sym.c File Reference
sym.c File Reference
#include "c.h"
#include <stdio.h>
Data Structures
struct Table::entry
struct Table
Macros
#define equalp(x) v.x == p->sym.u.c.v.x
#define HASHSIZE NELEMS(((Table)0)->buckets)
Functions
Symbol allsymbols (Table tp)
Symbol constant (Type ty, Value v)
void enterscope (void)
void exitscope (void)
Symbol findlabel (int lab)
Symbol findtype (Type ty)
void foreach (Table tp, int lev, void(*apply)(Symbol, void *), void *cl)
Symbol genident (int scls, Type ty, int lev)
int genlabel (int n)
Symbol install (const char *name, Table *tpp, int level, int arena)
Symbol intconst (int n)
void locus (Table tp, Coordinate *cp)
Symbol lookup (const char *name, Table tp)
Symbol mkstr (char *str)
Symbol mksymbol (int sclass, const char *name, Type ty)
Symbol newtemp (int sclass, int tc, int size)
Symbol relocate (const char *name, Table src, Table dst)
Table table (Table tp, int level)
Symbol temporary (int scls, Type ty)
void use (Symbol p, Coordinate src)
char * vtoa (Type ty, Value v)
Variables
static struct table cns = { CONSTANTS }
Table constants = &cns
static struct table ext = { GLOBAL }
Table externals = &ext
Table globals = &ids
Table identifiers = &ids
static struct table ids = { GLOBAL }
Table labels
int level = GLOBAL
List loci
List symbols
static int tempid
Table types = &tys
static struct table tys = { GLOBAL }
Macro Definition Documentation
equalp
#define equalp (x) v.x == p->sym.u.c.v.x
Definition at line 5 of file sym.c.
HASHSIZE
#define HASHSIZE NELEMS(((Table)0)->buckets)
Definition at line 16 of file sym.c.
Function Documentation
allsymbols()
Symbol allsymbols (Table tp)
Definition at line 235 of file sym.c.
{
     return tp->all;
 }
Referenced by locus().
constant()
Symbol constant (Type ty, Value v)
Definition at line 164 of file sym.c.
{
     struct entry *p;
     unsigned h = v.u&(HASHSIZE-1);
     ty = unqual(ty);
     for (p = constants->buckets[h]; p; p = p->link)
         if (eqtype(ty, p->sym.type, 1))
             switch (ty->op) {
             case INT:      if (equalp(i)) return &p->sym; break;
             case UNSIGNED: if (equalp(u)) return &p->sym; break;
             case FLOAT:    if (equalp(d)) return &p->sym; break;
             case FUNCTION: if (equalp(g)) return &p->sym; break;
             case ARRAY:
             case POINTER:  if (equalp(p)) return &p->sym; break;
             default: assert(0);
             }
     NEW0(p, PERM);
     p->sym.name = vtoa(ty, v);
     p->sym.scope = CONSTANTS;
     p->sym.type = ty;
     p->sym.sclass = STATIC;
     p->sym.u.c.v = v;
     p->link = constants->buckets[h];
     p->sym.up = constants->all;
     constants->all = &p->sym;
     constants->buckets[h] = p;
     if (ty->u.sym && !ty->u.sym->addressed)
         (*IR->defsymbol)(&p->sym);
     p->sym.defined = 1;
     return &p->sym;
 }
References constants, CONSTANTS, eqtype(), equalp, HASHSIZE, INT, IR, NEW0, PERM, unqual, and vtoa().
Referenced by cvtconst(), intconst(), listnodes(), mkstr(), and primary().
enterscope()
void enterscope (void)
Definition at line 57 of file sym.c.
                       {
     if (++level == LOCAL)
         tempid = 0;
 }
References LOCAL, and tempid.
Referenced by compound(), dclr1(), and funcdefn().
exitscope()
void exitscope (void)
Definition at line 61 of file sym.c.
                      {
     rmtypes(level);
     if (types->level == level)
         types = types->previous;
     if (identifiers->level == level) {
         if (Aflag >= 2) {
             int n = 0;
             Symbol p;
             for (p = identifiers->all; p && p->scope == level; p = p->up)
                 if (++n > 127) {
                     warning("more than 127 identifiers declared in a block\n");
                     break;
                 }
         }
         identifiers = identifiers->previous;
     }
     assert(level >= GLOBAL);
     --level;
 }
References Aflag, GLOBAL, identifiers, level, rmtypes(), types, and warning().
Referenced by compound(), decl(), exitparams(), and funcdefn().
findlabel()
Symbol findlabel (int lab)
Definition at line 145 of file sym.c.
{
     struct entry *p;
     unsigned h = lab&(HASHSIZE-1);
     for (p = labels->buckets[h]; p; p = p->link)
         if (lab == p->sym.u.l.label)
             return &p->sym;
     NEW0(p, FUNC);
     p->sym.name = stringd(lab);
     p->sym.scope = LABELS;
     p->sym.up = labels->all;
     labels->all = &p->sym;
     p->link = labels->buckets[h];
     labels->buckets[h] = p;
     p->sym.generated = 1;
     p->sym.u.l.label = lab;
     (*IR->defsymbol)(&p->sym);
     return &p->sym;
 }
References FUNC, HASHSIZE, IR, labels, LABELS, NEW0, and stringd().
Referenced by branch(), caselabel(), definelab(), dostmt(), forstmt(), ifstmt(), jump(), labelnode(), listnodes(), statement(), swstmt(), and whilestmt().
findtype()
Symbol findtype (Type ty)
Definition at line 252 of file sym.c.
{
     Table tp = identifiers;
     int i;
     struct entry *p;
     assert(tp);
     do
         for (i = 0; i < HASHSIZE; i++)
             for (p = tp->buckets[i]; p; p = p->link)
                 if (p->sym.type == ty && p->sym.sclass == TYPEDEF)
                     return &p->sym;
     while ((tp = tp->previous) != NULL);
     return NULL;
 }
References HASHSIZE, identifiers, and NULL.
Referenced by outtype(), and typestring().
foreach()
void foreach (Table tp, int lev, void(*)(Symbol, void *) apply, void * cl)
Definition at line 42 of file sym.c.
{
     assert(tp);
     while (tp && tp->level > lev)
         tp = tp->previous;
     if (tp && tp->level == lev) {
         Symbol p;
         Coordinate sav;
         sav = src;
         for (p = tp->all; p && p->scope == lev; p = p->up) {
             src = p->src;
             (*apply)(p, cl);
         }
         src = sav;
     }
 }
References cl.
genident()
Symbol genident (int scls, Type ty, int lev)
Definition at line 201 of file sym.c.
{
     Symbol p;
     NEW0(p, lev >= LOCAL ? FUNC : PERM);
     p->name = stringd(genlabel(1));
     p->scope = lev;
     p->sclass = scls;
     p->type = ty;
     p->generated = 1;
     if (lev == GLOBAL)
         (*IR->defsymbol)(p);
     return p;
 }
References FUNC, genlabel(), GLOBAL, IR, LOCAL, NEW0, PERM, and stringd().
Referenced by bbcall(), bbentry(), bbvars(), compound(), condtree(), cvtconst(), dcllocal(), funcdefn(), mkstr(), primary(), prof_init(), retcode(), swcode(), swstmt(), and tracecall().
genlabel()
int genlabel (int n)
Definition at line 139 of file sym.c.
                     {
     static int label = 1;
     label += n;
     return label - n;
 }
Referenced by addrtree(), defsymbol(), fields(), funcdefn(), genident(), listnodes(), newfield(), newstruct(), statement(), stmtlabel(), and swcode().
install()
Symbol install (const char * name, Table * tpp, int level, int arena)
Definition at line 80 of file sym.c.
{
     Table tp = *tpp;
     struct entry *p;
     unsigned h = (unsigned long)name&(HASHSIZE-1);
     assert(level == 0 || level >= tp->level);
     if (level > 0 && tp->level < level)
         tp = *tpp = table(tp, level);
     NEW0(p, arena);
     p->sym.name = (char *)name;
     p->sym.scope = level;
     p->sym.up = tp->all;
     tp->all = &p->sym;
     p->link = tp->buckets[h];
     tp->buckets[h] = p;
     return &p->sym;
 }
References arena, HASHSIZE, level, long(), NEW0, and table().
Referenced by mksymbol().
intconst()
Symbol intconst (int n)
Definition at line 195 of file sym.c.
{
     Value v;
     v.i = n;
     return constant(inttype, v);
 }
References constant(), and inttype.
Referenced by asgnnode(), docall(), and listnodes().
locus()
void locus (Table tp, Coordinate * cp)
Definition at line 239 of file sym.c.
{
     loci    = append(cp, loci);
     symbols = append(allsymbols(tp), symbols);
 }
References allsymbols(), append(), cp, loci, and symbols.
Referenced by definept().
lookup()
Symbol lookup (const char * name, Table tp)
Definition at line 127 of file sym.c.
{
     struct entry *p;
     unsigned h = (unsigned long)name&(HASHSIZE-1);
     assert(tp);
     do
         for (p = tp->buckets[h]; p; p = p->link)
             if (name == p->sym.name)
                 return &p->sym;
     while ((tp = tp->previous) != NULL);
     return NULL;
 }
References HASHSIZE, long(), and NULL.
mkstr()
Symbol mkstr (char * str)
Definition at line 268 of file sym.c.
{
     Value v;
     Symbol p;
     v.p = str;
     p = constant(array(chartype, strlen(v.p) + 1, 0), v);
     if (p->u.c.loc == NULL)
         p->u.c.loc = genident(STATIC, p->type, GLOBAL);
     return p;
 }
References array(), chartype, constant(), genident(), GLOBAL, and NULL.
Referenced by bbcall(), bbfile(), bbfunc(), nullcall(), nullcheck(), tracefinis(), and tracevalue().
mksymbol()
Symbol mksymbol (int sclass, const char * name, Type ty)
Definition at line 280 of file sym.c.
{
     Symbol p;
     if (sclass == EXTERN)
         p = install(string(name), &globals, GLOBAL, PERM);
     else {
         NEW0(p, PERM);
         p->name = string(name);
         p->scope = GLOBAL;
     }
     p->sclass = sclass;
     p->type = ty;
     (*IR->defsymbol)(p);
     p->defined = 1;
     return p;
 }
References EXTERN, GLOBAL, globals, install(), IR, NEW0, and PERM.
Referenced by bbcall(), bbentry(), bbexit(), and trace_init().
newtemp()
Symbol newtemp (int sclass, int tc, int size)
Definition at line 227 of file sym.c.
{
     Symbol p = temporary(sclass, btot(tc, size));
     (*IR->local)(p);
     p->defined = 1;
     return p;
 }
References btot(), IR, and temporary().
Referenced by spillr().
relocate()
Symbol relocate (const char * name, Table src, Table dst)
Definition at line 97 of file sym.c.
{
     struct entry *p, **q;
     Symbol *r;
     unsigned h = (unsigned long)name&(HASHSIZE-1);
     for (q = &src->buckets[h]; *q; q = &(*q)->link)
         if (name == (*q)->sym.name)
             break;
     assert(*q);
     /*
      Remove the entry from src's hash chain
       and from its list of all symbols.
     */
     p = *q;
     *q = (*q)->link;
     for (r = &src->all; *r && *r != &p->sym; r = &(*r)->up)
         ;
     assert(*r == &p->sym);
     *r = p->sym.up;
     /*
      Insert the entry into dst's hash chain
       and into its list of all symbols.
       Return the symbol-table entry.
     */
     p->link = dst->buckets[h];
     dst->buckets[h] = p;
     p->sym.up = dst->all;
     dst->all = &p->sym;
     return &p->sym;
 }
References HASHSIZE, and long().
Referenced by dclglobal().
table()
Table table (Table tp, int level)
Definition at line 32 of file sym.c.
{
     Table new;
     NEW0(new, FUNC);
     new->previous = tp;
     new->level = level;
     if (tp)
         new->all = tp->all;
     return new;
 }
References FUNC, level, and NEW0.
Referenced by install().
temporary()
Symbol temporary (int scls, Type ty)
Definition at line 215 of file sym.c.
{
     Symbol p;
     NEW0(p, FUNC);
     p->name = stringd(++tempid);
     p->scope = level < LOCAL ? LOCAL : level;
     p->sclass = scls;
     p->type = ty;
     p->temporary = 1;
     p->generated = 1;
     return p;
 }
References FUNC, level, LOCAL, NEW0, stringd(), and tempid.
Referenced by call(), CG_ImpactMark(), newtemp(), nullcheck(), and visit().
use()
void use (Symbol p, Coordinate src)
Definition at line 244 of file sym.c.
{
     Coordinate *cp;
     NEW(cp, PERM);
     *cp = src;
     p->uses = append(cp, p->uses);
 }
References append(), cp, NEW, and PERM.
Referenced by enumdcl(), fieldref(), funcdefn(), pragma(), primary(), specifier(), statement(), and structdcl().
vtoa()
char* vtoa (Type ty, Value v)
Definition at line 298 of file sym.c.
{
     ty = unqual(ty);
     switch (ty->op) {
     case INT:      return stringd(v.i);
     case UNSIGNED: return stringf((v.u&~0x7FFF) ? "0x%X" : "%U", v.u);
     case FLOAT:    return stringf("%g", (double)v.d);
     case ARRAY:
         if (ty->type == chartype || ty->type == signedchar
         ||  ty->type == unsignedchar)
             return v.p;
         return stringf("%p", v.p);
     case POINTER:  return stringf("%p", v.p);
     case FUNCTION: return stringf("%p", v.g);
     }
     assert(0); return NULL;
 }
References chartype, INT, NULL, signedchar, stringd(), stringf(), unqual, and unsignedchar.
Referenced by constant(), printtoken(), and printtree1().
Variable Documentation
cns
struct table cns = { CONSTANTS } static
Definition at line 18 of file sym.c.
constants
Table constants = &cns
Definition at line 22 of file sym.c.
Referenced by constant(), and finalize().
ext
struct table ext = { GLOBAL } static
Definition at line 19 of file sym.c.
Referenced by COM_CompareExtension(), Field_CompleteFilename(), FS_FilenameCompletion(), FS_IsExt(), GLimp_HaveExtension(), PPC_PrepareJump(), R_LoadImage(), RE_RegisterModel(), and S_CodecGetSound().
externals
Table externals = &ext
Definition at line 23 of file sym.c.
Referenced by dclglobal(), dcllocal(), finalize(), and primary().
globals
Table globals = &ids
Definition at line 25 of file sym.c.
Referenced by dclglobal(), dcllocal(), main_init(), and mksymbol().
identifiers
Table identifiers = &ids
Definition at line 24 of file sym.c.
Referenced by compound(), dclglobal(), dcllocal(), dclparam(), decl(), definept(), enumdcl(), exitscope(), finalize(), findtype(), funcdefn(), gettok(), main(), and primary().
ids
struct table ids = { GLOBAL } static
Definition at line 20 of file sym.c.
labels
Table labels
Definition at line 27 of file sym.c.
Referenced by findlabel(), and funcdefn().
level
int level = GLOBAL
Definition at line 28 of file sym.c.
Referenced by exitscope(), install(), table(), and temporary().
loci
List loci
Definition at line 30 of file sym.c.
Referenced by locus(), and main().
symbols
List symbols
Definition at line 30 of file sym.c.
Referenced by locus().
tempid
int tempid static
Definition at line 29 of file sym.c.
Referenced by enterscope(), and temporary().
types
Table types = &tys
Definition at line 26 of file sym.c.
Referenced by compound(), enumdcl(), exitscope(), main(), newstruct(), structdcl(), type_init(), and xxinit().
tys
struct table tys = { GLOBAL } static
Definition at line 21 of file sym.c.