ZEQ2-Lite: Game/CGame/cg_snapshot.c File Reference
cg_snapshot.c File Reference
#include "cg_local.h"
Functions
void CG_ProcessSnapshots (void)
static snapshot_t * CG_ReadNextSnapshot (void)
static void CG_ResetEntity (centity_t *cent)
void CG_SetInitialSnapshot (snapshot_t *snap)
static void CG_SetNextSnap (snapshot_t *snap)
static void CG_StopMover (centity_t *cent)
static void CG_TransitionEntity (centity_t *cent)
static void CG_TransitionSnapshot (void)
Function Documentation
CG_ProcessSnapshots()
void CG_ProcessSnapshots (void)
Definition at line 310 of file cg_snapshot.c.
{
     snapshot_t      *snap;
     int             n;
     // see what the latest snapshot the client system has is
     trap_GetCurrentSnapshotNumber( &n, &cg.latestSnapshotTime );
     if ( n != cg.latestSnapshotNum ) {
         if ( n < cg.latestSnapshotNum ) {
             // this should never happen
             CG_Error( "CG_ProcessSnapshots: n < cg.latestSnapshotNum" );
         }
         cg.latestSnapshotNum = n;
     }
     // If we have yet to receive a snapshot, check for it.
     // Once we have gotten the first snapshot, cg.snap will
     // always have valid data for the rest of the game
     while ( !cg.snap ) {
         snap = CG_ReadNextSnapshot();
         if ( !snap ) {
             // we can't continue until we get a snapshot
             return;
         }
         // set our weapon selection to what
         // the playerstate is currently using
         if ( !( snap->snapFlags & SNAPFLAG_NOT_ACTIVE ) ) {
             CG_SetInitialSnapshot( snap );
         }
     }
     // loop until we either have a valid nextSnap with a serverTime
     // greater than cg.time to interpolate towards, or we run
     // out of available snapshots
     do {
         // if we don't have a nextframe, try and read a new one in
         if ( !cg.nextSnap ) {
             snap = CG_ReadNextSnapshot();
             // if we still don't have a nextframe, we will just have to
             // extrapolate
             if ( !snap ) {
                 break;
             }
             CG_SetNextSnap( snap );
             // if time went backwards, we have a level restart
             if ( cg.nextSnap->serverTime < cg.snap->serverTime ) {
                 CG_Error( "CG_ProcessSnapshots: Server time went backwards" );
             }
         }
         // if our time is < nextFrame's, we have a nice interpolating state
         if ( cg.time >= cg.snap->serverTime && cg.time < cg.nextSnap->serverTime ) {
             break;
         }
         // we have passed the transition from nextFrame to frame
         CG_TransitionSnapshot();
     } while ( 1 );
     // assert our valid conditions upon exiting
     if ( cg.snap == NULL ) {
         CG_Error( "CG_ProcessSnapshots: cg.snap == NULL" );
     }
     if ( cg.time < cg.snap->serverTime ) {
         // this can happen right after a vid_restart
         cg.time = cg.snap->serverTime;
     }
     if ( cg.nextSnap != NULL && cg.nextSnap->serverTime <= cg.time ) {
         CG_Error( "CG_ProcessSnapshots: cg.nextSnap->serverTime <= cg.time" );
     }
 }
References cg, CG_Error(), CG_ReadNextSnapshot(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_TransitionSnapshot(), cg_t::latestSnapshotNum, cg_t::latestSnapshotTime, cg_t::nextSnap, NULL, snapshot_t::serverTime, cg_t::snap, SNAPFLAG_NOT_ACTIVE, snapshot_t::snapFlags, cg_t::time, and trap_GetCurrentSnapshotNumber().
Referenced by CG_DrawActiveFrame().
CG_ReadNextSnapshot()
static snapshot_t* CG_ReadNextSnapshot (void) static
Definition at line 252 of file cg_snapshot.c.
{
     qboolean    r;
     snapshot_t  *dest;
     if ( cg.latestSnapshotNum > cgs.processedSnapshotNum + 1000 ) {
         CG_Printf( "WARNING: CG_ReadNextSnapshot: way out of range, %i > %i\n",
             cg.latestSnapshotNum, cgs.processedSnapshotNum );
     }
     while ( cgs.processedSnapshotNum < cg.latestSnapshotNum ) {
         // decide which of the two slots to load it into
         if ( cg.snap == &cg.activeSnapshots[0] ) {
             dest = &cg.activeSnapshots[1];
         } else {
             dest = &cg.activeSnapshots[0];
         }
         // try to read the snapshot from the client system
         cgs.processedSnapshotNum++;
         r = trap_GetSnapshot( cgs.processedSnapshotNum, dest );
         // FIXME: why would trap_GetSnapshot return a snapshot with the same server time
         if ( cg.snap && r && dest->serverTime == cg.snap->serverTime ) {
             //continue;
         }
         // if it succeeded, return
         if ( r ) {
             return dest;
         }
         // If there are additional snapshots, continue trying to
         // read them.
     }
     // nothing left to read
     return NULL;
 }
References cg_t::activeSnapshots, cg, CG_Printf(), cgs, cg_t::latestSnapshotNum, NULL, cgs_t::processedSnapshotNum, snapshot_t::serverTime, cg_t::snap, and trap_GetSnapshot().
Referenced by CG_ProcessSnapshots().
CG_ResetEntity()
static void CG_ResetEntity (centity_t * cent) static
Definition at line 35 of file cg_snapshot.c.
{
     // if the previous snapshot this entity was updated in is at least
     // an event window back in time then we can reset the previous event
     if ( cent->snapShotTime < cg.time - EVENT_VALID_MSEC ) {
         cent->previousEvent = 0;
     }
     cent->trailTime = cg.snap->serverTime;
     VectorCopy (cent->currentState.origin, cent->lerpOrigin);
     VectorCopy (cent->currentState.angles, cent->lerpAngles);
     if ( cent->currentState.eType == ET_PLAYER ) {
         CG_ResetPlayerEntity( cent );
     }
 }
References cg, CG_ResetPlayerEntity(), ET_PLAYER, EVENT_VALID_MSEC, snapshot_t::serverTime, cg_t::snap, cg_t::time, and VectorCopy.
Referenced by CG_SetInitialSnapshot(), and CG_TransitionEntity().
CG_SetInitialSnapshot()
void CG_SetInitialSnapshot (snapshot_t * snap)
Definition at line 86 of file cg_snapshot.c.
{
     int             i;
     centity_t       *cent;
     entityState_t   *state;
     cg.snap = snap;
     BG_PlayerStateToEntityState( &snap->ps, &cg_entities[ snap->ps.clientNum ].currentState, qfalse );
     // sort out solid entities
     CG_BuildSolidList();
     CG_ExecuteNewServerCommands( snap->serverCommandSequence );
     // set our local weapon selection pointer to
     // what the server has indicated the current weapon is
     CG_Respawn();
     for ( i = 0 ; i < cg.snap->numEntities ; i++ ) {
         state = &cg.snap->entities[ i ];
         cent = &cg_entities[ state->number ];
         memcpy(&cent->currentState, state, sizeof(entityState_t));
         //cent->currentState = *state;
         cent->interpolate = qfalse;
         cent->currentValid = qtrue;
         CG_ResetEntity( cent );
         // check for events
         CG_CheckEvents( cent );
     }
 }
References BG_PlayerStateToEntityState(), cg, CG_BuildSolidList(), CG_CheckEvents(), cg_entities, CG_ExecuteNewServerCommands(), CG_ResetEntity(), CG_Respawn(), snapshot_t::entities, memcpy(), snapshot_t::numEntities, snapshot_t::ps, qfalse, qtrue, snapshot_t::serverCommandSequence, and cg_t::snap.
Referenced by CG_ProcessSnapshots().
CG_SetNextSnap()
static void CG_SetNextSnap (snapshot_t * snap) static
Definition at line 192 of file cg_snapshot.c.
{
     int                 num;
     entityState_t       *es;
     centity_t           *cent;
     cg.nextSnap = snap;
     BG_PlayerStateToEntityState( &snap->ps, &cg_entities[ snap->ps.clientNum ].nextState, qfalse );
     cg_entities[ cg.snap->ps.clientNum ].interpolate = qtrue;
     // check for extrapolation errors
     for ( num = 0 ; num < snap->numEntities ; num++ ) {
         es = &snap->entities[num];
         cent = &cg_entities[ es->number ];
         memcpy(&cent->nextState, es, sizeof(entityState_t));
         //cent->nextState = *es;
         // if this frame is a teleport, or the entity wasn't in the
         // previous frame, don't interpolate
         if ( !cent->currentValid || ( ( cent->currentState.eFlags ^ es->eFlags ) & EF_TELEPORT_BIT )  ) {
             cent->interpolate = qfalse;
         } else {
             cent->interpolate = qtrue;
         }
     }
     // if the next frame is a teleport for the playerstate, we
     // can't interpolate during demos
     if ( cg.snap && ( ( snap->ps.eFlags ^ cg.snap->ps.eFlags ) & EF_TELEPORT_BIT ) ) {
         cg.nextFrameTeleport = qtrue;
     } else {
         cg.nextFrameTeleport = qfalse;
     }
     // if changing follow mode, don't interpolate
     if ( cg.nextSnap->ps.clientNum != cg.snap->ps.clientNum ) {
         cg.nextFrameTeleport = qtrue;
     }
     // if changing server restarts, don't interpolate
     if ( ( cg.nextSnap->snapFlags ^ cg.snap->snapFlags ) & SNAPFLAG_SERVERCOUNT ) {
         cg.nextFrameTeleport = qtrue;
     }
     // sort out solid entities
     CG_BuildSolidList();
 }
References BG_PlayerStateToEntityState(), cg, CG_BuildSolidList(), cg_entities, EF_TELEPORT_BIT, snapshot_t::entities, memcpy(), cg_t::nextFrameTeleport, cg_t::nextSnap, snapshot_t::numEntities, snapshot_t::ps, qfalse, qtrue, cg_t::snap, SNAPFLAG_SERVERCOUNT, and snapshot_t::snapFlags.
Referenced by CG_ProcessSnapshots().
CG_StopMover()
static void CG_StopMover (centity_t * cent) static
Definition at line 179 of file cg_snapshot.c.
{
     cent->currentState.pos.trType = TR_STATIONARY;
     VectorCopy(cent->lerpOrigin, cent->currentState.pos.trBase);
     VectorClear(cent->currentState.pos.trDelta);
 }
References TR_STATIONARY, VectorClear, and VectorCopy.
CG_TransitionEntity()
static void CG_TransitionEntity (centity_t * cent) static
Definition at line 58 of file cg_snapshot.c.
{
     cent->currentState = cent->nextState;
     cent->currentValid = qtrue;
     // reset if the entity wasn't in the last frame or was teleported
     if ( !cent->interpolate ) {
         CG_ResetEntity( cent );
     }
     // clear the next state.  if will be set by the next CG_SetNextSnap
     cent->interpolate = qfalse;
     // check for events
     CG_CheckEvents( cent );
 }
References CG_CheckEvents(), CG_ResetEntity(), qfalse, and qtrue.
Referenced by CG_TransitionSnapshot().
CG_TransitionSnapshot()
static void CG_TransitionSnapshot (void) static
Definition at line 128 of file cg_snapshot.c.
{
     centity_t           *cent;
     snapshot_t          *oldFrame;
     int                 i;
     if(!cg.snap){CG_Error( "CG_TransitionSnapshot: NULL cg.snap");}
     if(!cg.nextSnap){CG_Error( "CG_TransitionSnapshot: NULL cg.nextSnap");}
     // execute any server string commands before transitioning entities
     CG_ExecuteNewServerCommands( cg.nextSnap->serverCommandSequence );
     // if we had a map_restart, set everthing with initial
     if(!cg.snap){}
     // clear the currentValid flag for all entities in the existing snapshot
     for(i = 0 ; i < cg.snap->numEntities ; i++){
         cent = &cg_entities[cg.snap->entities[ i ].number];
         cent->currentValid = qfalse;
     }
     // move nextSnap to snap and do the transitions
     oldFrame = cg.snap;
     cg.snap = cg.nextSnap;
     BG_PlayerStateToEntityState( &cg.snap->ps, &cg_entities[ cg.snap->ps.clientNum ].currentState, qfalse );
     cg_entities[ cg.snap->ps.clientNum ].interpolate = qfalse;
     for ( i = 0 ; i < cg.snap->numEntities ; i++ ) {
         cent = &cg_entities[ cg.snap->entities[ i ].number ];
         CG_TransitionEntity( cent );
         // remember time of snapshot this entity was last updated in
         cent->snapShotTime = cg.snap->serverTime;
     }
     cg.nextSnap = NULL;
     // check for playerstate transition events
     if(oldFrame){
         playerState_t   *ops, *ps;
         ops = &oldFrame->ps;
         ps = &cg.snap->ps;
         // teleporting checks are irrespective of prediction
         if((ps->eFlags ^ ops->eFlags) & EF_TELEPORT_BIT){
             cg.thisFrameTeleport = qtrue;   // will be cleared by prediction code
         }
         // if we are not doing client side movement prediction for any
         // reason, then the client events and view changes will be issued now
         if (cg.demoPlayback || (cg.snap->ps.pm_flags & PMF_FOLLOW) || cg_nopredict.integer || cg_synchronousClients.integer || cg.snap->ps.lockedTarget){
             CG_TransitionPlayerState( ps, ops );
         }
     }
 }
References BG_PlayerStateToEntityState(), cg, cg_entities, CG_Error(), CG_ExecuteNewServerCommands(), cg_nopredict, cg_synchronousClients, CG_TransitionEntity(), CG_TransitionPlayerState(), cg_t::demoPlayback, EF_TELEPORT_BIT, snapshot_t::entities, vmCvar_t::integer, cg_t::nextSnap, NULL, snapshot_t::numEntities, oldFrame, ops, PMF_FOLLOW, snapshot_t::ps, qfalse, qtrue, snapshot_t::serverCommandSequence, snapshot_t::serverTime, cg_t::snap, and cg_t::thisFrameTeleport.
Referenced by CG_ProcessSnapshots().