ZEQ2-Lite: __gnu_profile::__warn Struct Reference
__gnu_profile::__warn Struct Reference
#include <profiler_trace.h>
Public Member Functions
__warn (FILE *__f)
void operator() (const __warning_data &__info)
Data Fields
FILE * __file
Detailed Description
Definition at line 419 of file profiler_trace.h.
Constructor & Destructor Documentation
__warn()
__gnu_profile::__warn::__warn (FILE * __f) inline
Definition at line 423 of file profiler_trace.h.
     { __file = __f; }
References __file.
Member Function Documentation
operator()()
void __gnu_profile::__warn::operator() (const __warning_data & __info) inline
Definition at line 427 of file profiler_trace.h.
     {
       std::fprintf(__file,  __info.__warning_id);
       std::fprintf(__file, ": improvement = %d",
            __log_magnitude(__info.__magnitude));
       std::fprintf(__file, ": call stack = ");
       __gnu_profile::__write(__file, __info.__context);
       std::fprintf(__file, ": advice = %s\n",
            __info.__warning_message.c_str());
     }
References __gnu_profile::__warning_data::__context, __file, __gnu_profile::__log_magnitude(), __gnu_profile::__warning_data::__magnitude, __gnu_profile::__warning_data::__warning_id, __gnu_profile::__warning_data::__warning_message, __gnu_profile::__write(), and fprintf().
Field Documentation
__file
FILE* __gnu_profile::__warn::__file
Definition at line 421 of file profiler_trace.h.
Referenced by __warn(), and operator()().
The documentation for this struct was generated from the following file:
Tools/MinGW/include/c++/4.6.1/profile/impl/profiler_trace.h