ZEQ2-Lite: Engine/server/sv_ccmds.c File Reference
sv_ccmds.c File Reference
#include "server.h"
Functions
static void SV_AddBanToList (qboolean isexception)
void SV_AddOperatorCommands (void)
static void SV_BanAddr_f (void)
static void SV_BanDel_f (void)
static void SV_CompleteMapName (char *args, int argNum)
static void SV_ConSay_f (void)
static qboolean SV_DelBanEntryFromList (int index)
static void SV_DelBanFromList (qboolean isexception)
static void SV_DumpUser_f (void)
static void SV_ExceptAddr_f (void)
static void SV_ExceptDel_f (void)
static void SV_FlushBans_f (void)
static client_t * SV_GetPlayerByHandle (void)
static client_t * SV_GetPlayerByNum (void)
void SV_Heartbeat_f (void)
static void SV_Kick_f (void)
static void SV_KickNum_f (void)
static void SV_KillServer_f (void)
static void SV_ListBans_f (void)
static void SV_Map_f (void)
static void SV_MapRestart_f (void)
static qboolean SV_ParseCIDRNotation (netadr_t *dest, int *mask, char *adrstr)
static void SV_RehashBans_f (void)
void SV_RemoveOperatorCommands (void)
static void SV_Serverinfo_f (void)
static void SV_Status_f (void)
static void SV_Systeminfo_f (void)
static void SV_WriteBans (void)
Function Documentation
SV_AddBanToList()
static void SV_AddBanToList (qboolean isexception) static
Definition at line 590 of file sv_ccmds.c.
 {
     char *banstring;
     char addy2[NET_ADDRSTRMAXLEN];
     netadr_t ip;
     int index, argc, mask;
     serverBan_t *curban;
     argc = Cmd_Argc();
     if(argc < 2 || argc > 3)
     {
         Com_Printf ("Usage: %s (ip[/subnet] | clientnum [subnet])\n", Cmd_Argv(0));
         return;
     }
     if(serverBansCount > ARRAY_LEN(serverBans))
     {
         Com_Printf ("Error: Maximum number of bans/exceptions exceeded.\n");
         return;
     }
     banstring = Cmd_Argv(1);
     if(strchr(banstring, '.') || strchr(banstring, ':'))
     {
         // This is an ip address, not a client num.
         if(SV_ParseCIDRNotation(&ip, &mask, banstring))
         {
             Com_Printf("Error: Invalid address %s\n", banstring);
             return;
         }
     }
     else
     {
         client_t *cl;
         // client num.
         if(!com_sv_running->integer)
         {
             Com_Printf("Server is not running.\n");
             return;
         }
         cl = SV_GetPlayerByNum();
         if(!cl)
         {
             Com_Printf("Error: Playernum %s does not exist.\n", Cmd_Argv(1));
             return;
         }
         ip = cl->netchan.remoteAddress;
         if(argc == 3)
         {
             mask = atoi(Cmd_Argv(2));
             if(ip.type == NA_IP)
             {
                 if(mask < 1 || mask > 32)
                     mask = 32;
             }
             else
             {
                 if(mask < 1 || mask > 128)
                     mask = 128;
             }
         }
         else
             mask = (ip.type == NA_IP6) ? 128 : 32;
     }
     if(ip.type != NA_IP && ip.type != NA_IP6)
     {
         Com_Printf("Error: Can ban players connected via the internet only.\n");
         return;
     }
     // first check whether a conflicting ban exists that would supersede the new one.
     for(index = 0; index < serverBansCount; index++)
     {
         curban = &serverBans[index];
         if(curban->subnet <= mask)
         {
             if((curban->isexception || !isexception) && NET_CompareBaseAdrMask(curban->ip, ip, curban->subnet))
             {
                 Q_strncpyz(addy2, NET_AdrToString(ip), sizeof(addy2));
                 Com_Printf("Error: %s %s/%d supersedes %s %s/%d\n", curban->isexception ? "Exception" : "Ban",
                        NET_AdrToString(curban->ip), curban->subnet,
                        isexception ? "exception" : "ban", addy2, mask);
                 return;
             }
         }
         if(curban->subnet >= mask)
         {
             if(!curban->isexception && isexception && NET_CompareBaseAdrMask(curban->ip, ip, mask))
             {
                 Q_strncpyz(addy2, NET_AdrToString(curban->ip), sizeof(addy2));
                 Com_Printf("Error: %s %s/%d supersedes already existing %s %s/%d\n", isexception ? "Exception" : "Ban",
                        NET_AdrToString(ip), mask,
                        curban->isexception ? "exception" : "ban", addy2, curban->subnet);
                 return;
             }
         }
     }
     // now delete bans that are superseded by the new one
     index = 0;
     while(index < serverBansCount)
     {
         curban = &serverBans[index];
         if(curban->subnet > mask && (!curban->isexception || isexception) && NET_CompareBaseAdrMask(curban->ip, ip, mask))
             SV_DelBanEntryFromList(index);
         else
             index++;
     }
     serverBans[serverBansCount].ip = ip;
     serverBans[serverBansCount].subnet = mask;
     serverBans[serverBansCount].isexception = isexception;
     serverBansCount++;
     SV_WriteBans();
     Com_Printf("Added %s: %s/%d\n", isexception ? "ban exception" : "ban",
            NET_AdrToString(ip), mask);
 }
References ARRAY_LEN, cl, Cmd_Argc(), Cmd_Argv(), Com_Printf(), com_sv_running, serverBan_t::ip, serverBan_t::isexception, NA_IP, NA_IP6, NET_ADDRSTRMAXLEN, NET_AdrToString(), NET_CompareBaseAdrMask(), Q_strncpyz(), serverBans, serverBansCount, serverBan_t::subnet, SV_DelBanEntryFromList(), SV_GetPlayerByNum(), SV_ParseCIDRNotation(), SV_WriteBans(), and netadr_t::type.
Referenced by SV_BanAddr_f(), and SV_ExceptAddr_f().
SV_AddOperatorCommands()
void SV_AddOperatorCommands (void)
Definition at line 1128 of file sv_ccmds.c.
{
     static qboolean initialized;
     if ( initialized ) {
         return;
     }
     initialized = qtrue;
     Cmd_AddCommand ("heartbeat", SV_Heartbeat_f);
     Cmd_AddCommand ("kick", SV_Kick_f);
     Cmd_AddCommand ("clientkick", SV_KickNum_f);
     Cmd_AddCommand ("status", SV_Status_f);
     Cmd_AddCommand ("serverinfo", SV_Serverinfo_f);
     Cmd_AddCommand ("systeminfo", SV_Systeminfo_f);
     Cmd_AddCommand ("dumpuser", SV_DumpUser_f);
     Cmd_AddCommand ("map_restart", SV_MapRestart_f);
     Cmd_AddCommand ("sectorlist", SV_SectorList_f);
     Cmd_AddCommand ("map", SV_Map_f);
     Cmd_SetCommandCompletionFunc( "map", SV_CompleteMapName );
 #ifndef PRE_RELEASE_DEMO
     Cmd_AddCommand ("devmap", SV_Map_f);
     Cmd_SetCommandCompletionFunc( "devmap", SV_CompleteMapName );
     Cmd_AddCommand ("spmap", SV_Map_f);
     Cmd_SetCommandCompletionFunc( "spmap", SV_CompleteMapName );
     Cmd_AddCommand ("spdevmap", SV_Map_f);
     Cmd_SetCommandCompletionFunc( "spdevmap", SV_CompleteMapName );
 #endif
     Cmd_AddCommand ("killserver", SV_KillServer_f);
     if( com_dedicated->integer ) {
         Cmd_AddCommand ("say", SV_ConSay_f);
     }
     Cmd_AddCommand("rehashbans", SV_RehashBans_f);
     Cmd_AddCommand("listbans", SV_ListBans_f);
     Cmd_AddCommand("banaddr", SV_BanAddr_f);
     Cmd_AddCommand("exceptaddr", SV_ExceptAddr_f);
     Cmd_AddCommand("bandel", SV_BanDel_f);
     Cmd_AddCommand("exceptdel", SV_ExceptDel_f);
     Cmd_AddCommand("flushbans", SV_FlushBans_f);
 }
References Cmd_AddCommand(), Cmd_SetCommandCompletionFunc(), com_dedicated, qtrue, SV_BanAddr_f(), SV_BanDel_f(), SV_CompleteMapName(), SV_ConSay_f(), SV_DumpUser_f(), SV_ExceptAddr_f(), SV_ExceptDel_f(), SV_FlushBans_f(), SV_Heartbeat_f(), SV_Kick_f(), SV_KickNum_f(), SV_KillServer_f(), SV_ListBans_f(), SV_Map_f(), SV_MapRestart_f(), SV_RehashBans_f(), SV_SectorList_f(), SV_Serverinfo_f(), SV_Status_f(), and SV_Systeminfo_f().
Referenced by SV_Init().
SV_BanAddr_f()
static void SV_BanAddr_f (void) static
Definition at line 868 of file sv_ccmds.c.
 {
     SV_AddBanToList(qfalse);
 }
References qfalse, and SV_AddBanToList().
Referenced by SV_AddOperatorCommands().
SV_BanDel_f()
static void SV_BanDel_f (void) static
Definition at line 878 of file sv_ccmds.c.
 {
     SV_DelBanFromList(qfalse);
 }
References qfalse, and SV_DelBanFromList().
Referenced by SV_AddOperatorCommands().
SV_CompleteMapName()
static void SV_CompleteMapName (char * args, int argNum) static
Definition at line 1117 of file sv_ccmds.c.
{
     if( argNum == 2 ) {
         Field_CompleteFilename( "maps", "bsp", qtrue, qfalse );
     }
 }
References Field_CompleteFilename(), qfalse, and qtrue.
Referenced by SV_AddOperatorCommands().
SV_ConSay_f()
static void SV_ConSay_f (void) static
Definition at line 1003 of file sv_ccmds.c.
{
     char    *p;
     char    text[1024];
     // make sure server is running
     if ( !com_sv_running->integer ) {
         Com_Printf( "Server is not running.\n" );
         return;
     }
     if ( Cmd_Argc () < 2 ) {
         return;
     }
     strcpy (text, "console: ");
     p = Cmd_Args();
     if ( *p == '"' ) {
         p++;
         p[strlen(p)-1] = 0;
     }
     strcat(text, p);
     SV_SendServerCommand(NULL, "chat \"%s\"", text);
 }
References Cmd_Argc(), Cmd_Args(), Com_Printf(), com_sv_running, NULL, and SV_SendServerCommand().
Referenced by SV_AddOperatorCommands().
SV_DelBanEntryFromList()
static qboolean SV_DelBanEntryFromList (int index) static
Definition at line 522 of file sv_ccmds.c.
 {
     if(index == serverBansCount - 1)
         serverBansCount--;
     else if(index < ARRAY_LEN(serverBans) - 1)
     {
         memmove(serverBans + index, serverBans + index + 1, (serverBansCount - index - 1) * sizeof(*serverBans));
         serverBansCount--;
     }
     else
         return qtrue;
     return qfalse;
 }
References ARRAY_LEN, memmove(), qfalse, qtrue, serverBans, and serverBansCount.
Referenced by SV_AddBanToList(), and SV_DelBanFromList().
SV_DelBanFromList()
static void SV_DelBanFromList (qboolean isexception) static
Definition at line 733 of file sv_ccmds.c.
 {
     int index, count = 0, todel, mask;
     netadr_t ip;
     char *banstring;
     if(Cmd_Argc() != 2)
     {
         Com_Printf ("Usage: %s (ip[/subnet] | num)\n", Cmd_Argv(0));
         return;
     }
     banstring = Cmd_Argv(1);
     if(strchr(banstring, '.') || strchr(banstring, ':'))
     {
         serverBan_t *curban;
         if(SV_ParseCIDRNotation(&ip, &mask, banstring))
         {
             Com_Printf("Error: Invalid address %s\n", banstring);
             return;
         }
         index = 0;
         while(index < serverBansCount)
         {
             curban = &serverBans[index];
             if(curban->isexception == isexception       &&
                curban->subnet >= mask           &&
                NET_CompareBaseAdrMask(curban->ip, ip, mask))
             {
                 Com_Printf("Deleting %s %s/%d\n",
                        isexception ? "exception" : "ban",
                        NET_AdrToString(curban->ip), curban->subnet);
                 SV_DelBanEntryFromList(index);
             }
             else
                 index++;
         }
     }
     else
     {
         todel = atoi(Cmd_Argv(1));
         if(todel < 1 || todel > serverBansCount)
         {
             Com_Printf("Error: Invalid ban number given\n");
             return;
         }
         for(index = 0; index < serverBansCount; index++)
         {
             if(serverBans[index].isexception == isexception)
             {
                 count++;
                 if(count == todel)
                 {
                     Com_Printf("Deleting %s %s/%d\n",
                        isexception ? "exception" : "ban",
                        NET_AdrToString(serverBans[index].ip), serverBans[index].subnet);
                     SV_DelBanEntryFromList(index);
                     break;
                 }
             }
         }
     }
     SV_WriteBans();
 }
References Cmd_Argc(), Cmd_Argv(), Com_Printf(), serverBan_t::ip, serverBan_t::isexception, NET_AdrToString(), NET_CompareBaseAdrMask(), serverBans, serverBansCount, serverBan_t::subnet, SV_DelBanEntryFromList(), SV_ParseCIDRNotation(), and SV_WriteBans().
Referenced by SV_BanDel_f(), and SV_ExceptDel_f().
SV_DumpUser_f()
static void SV_DumpUser_f (void) static
Definition at line 1076 of file sv_ccmds.c.
{
     client_t    *cl;
     // make sure server is running
     if ( !com_sv_running->integer ) {
         Com_Printf( "Server is not running.\n" );
         return;
     }
     if ( Cmd_Argc() != 2 ) {
         Com_Printf ("Usage: dumpuser <userid>\n");
         return;
     }
     cl = SV_GetPlayerByHandle();
     if ( !cl ) {
         return;
     }
     Com_Printf( "userinfo\n" );
     Com_Printf( "--------\n" );
     Info_Print( cl->userinfo );
 }
References cl, Cmd_Argc(), Com_Printf(), com_sv_running, Info_Print(), and SV_GetPlayerByHandle().
Referenced by SV_AddOperatorCommands().
SV_ExceptAddr_f()
static void SV_ExceptAddr_f (void) static
Definition at line 873 of file sv_ccmds.c.
 {
     SV_AddBanToList(qtrue);
 }
References qtrue, and SV_AddBanToList().
Referenced by SV_AddOperatorCommands().
SV_ExceptDel_f()
static void SV_ExceptDel_f (void) static
Definition at line 883 of file sv_ccmds.c.
 {
     SV_DelBanFromList(qtrue);
 }
References qtrue, and SV_DelBanFromList().
Referenced by SV_AddOperatorCommands().
SV_FlushBans_f()
static void SV_FlushBans_f (void) static
Definition at line 858 of file sv_ccmds.c.
 {
     serverBansCount = 0;
     // empty the ban file.
     SV_WriteBans();
     Com_Printf("All bans and exceptions have been deleted.\n");
 }
References Com_Printf(), serverBansCount, and SV_WriteBans().
Referenced by SV_AddOperatorCommands().
SV_GetPlayerByHandle()
static client_t* SV_GetPlayerByHandle (void) static
Definition at line 42 of file sv_ccmds.c.
{
     client_t    *cl;
     int         i;
     char        *s;
     char        cleanName[64];
     // make sure server is running
     if ( !com_sv_running->integer ) {
         return NULL;
     }
     if ( Cmd_Argc() < 2 ) {
         Com_Printf( "No player specified.\n" );
         return NULL;
     }
     s = Cmd_Argv(1);
     // Check whether this is a numeric player handle
     for(i = 0; s[i] >= '0' && s[i] <= '9'; i++);
     if(!s[i])
     {
         int plid = atoi(s);
         // Check for numeric playerid match
         if(plid >= 0 && plid < sv_maxclients->integer)
         {
             cl = &svs.clients[plid];
             if(cl->state)
                 return cl;
         }
     }
     // check for a name match
     for ( i=0, cl=svs.clients ; i < sv_maxclients->integer ; i++,cl++ ) {
         if ( !cl->state ) {
             continue;
         }
         if ( !Q_stricmp( cl->name, s ) ) {
             return cl;
         }
         Q_strncpyz( cleanName, cl->name, sizeof(cleanName) );
         Q_CleanStr( cleanName );
         if ( !Q_stricmp( cleanName, s ) ) {
             return cl;
         }
     }
     Com_Printf( "Player %s is not on the server\n", s );
     return NULL;
 }
References cl, serverStatic_t::clients, Cmd_Argc(), Cmd_Argv(), Com_Printf(), com_sv_running, NULL, Q_CleanStr(), Q_stricmp(), Q_strncpyz(), and svs.
Referenced by SV_DumpUser_f(), and SV_Kick_f().
SV_GetPlayerByNum()
static client_t* SV_GetPlayerByNum (void) static
Definition at line 105 of file sv_ccmds.c.
{
     client_t    *cl;
     int         i;
     int         idnum;
     char        *s;
     // make sure server is running
     if ( !com_sv_running->integer ) {
         return NULL;
     }
     if ( Cmd_Argc() < 2 ) {
         Com_Printf( "No player specified.\n" );
         return NULL;
     }
     s = Cmd_Argv(1);
     for (i = 0; s[i]; i++) {
         if (s[i] < '0' || s[i] > '9') {
             Com_Printf( "Bad slot number: %s\n", s);
             return NULL;
         }
     }
     idnum = atoi( s );
     if ( idnum < 0 || idnum >= sv_maxclients->integer ) {
         Com_Printf( "Bad client slot: %i\n", idnum );
         return NULL;
     }
     cl = &svs.clients[idnum];
     if ( !cl->state ) {
         Com_Printf( "Client %i is not active\n", idnum );
         return NULL;
     }
     return cl;
 }
References cl, serverStatic_t::clients, Cmd_Argc(), Cmd_Argv(), Com_Printf(), com_sv_running, NULL, sv_maxclients, and svs.
Referenced by SV_AddBanToList(), and SV_KickNum_f().
SV_Heartbeat_f()
void SV_Heartbeat_f (void)
Definition at line 1038 of file sv_ccmds.c.
{
     svs.nextHeartbeatTime = -9999999;
 }
References serverStatic_t::nextHeartbeatTime, and svs.
Referenced by SV_AddOperatorCommands(), SV_DirectConnect(), SV_DropClient(), and SV_SpawnServer().
SV_Kick_f()
static void SV_Kick_f (void) static
Definition at line 357 of file sv_ccmds.c.
{
     client_t    *cl;
     int         i;
     // make sure server is running
     if ( !com_sv_running->integer ) {
         Com_Printf( "Server is not running.\n" );
         return;
     }
     if ( Cmd_Argc() != 2 ) {
         Com_Printf ("Usage: kick <player name>\nkick all = kick everyone\n");
         return;
     }
     cl = SV_GetPlayerByHandle();
     if ( !cl ) {
         for ( i=0, cl=svs.clients ; i < sv_maxclients->integer ; i++,cl++ ) {
             if ( !cl->state ) {
                 continue;
             }
             if( cl->netchan.remoteAddress.type == NA_LOOPBACK ) {
                 continue;
             }
             SV_DropClient( cl, "was kicked" );
             cl->lastPacketTime = svs.time;  // in case there is a funny zombie
             }
         }
         return;
     if( cl->netchan.remoteAddress.type == NA_LOOPBACK ) {
         SV_SendServerCommand(NULL, "print \"%s\"", "Cannot kick host player\n");
         return;
     }
     SV_DropClient( cl, "was kicked" );
     cl->lastPacketTime = svs.time;  // in case there is a funny zombie
 }
References cl, serverStatic_t::clients, Cmd_Argc(), Com_Printf(), com_sv_running, NA_LOOPBACK, NULL, SV_DropClient(), SV_GetPlayerByHandle(), SV_SendServerCommand(), svs, and serverStatic_t::time.
Referenced by SV_AddOperatorCommands().
SV_KickNum_f()
static void SV_KickNum_f (void) static
Definition at line 895 of file sv_ccmds.c.
{
     client_t    *cl;
     // make sure server is running
     if ( !com_sv_running->integer ) {
         Com_Printf( "Server is not running.\n" );
         return;
     }
     if ( Cmd_Argc() != 2 ) {
         Com_Printf ("Usage: kicknum <client number>\n");
         return;
     }
     cl = SV_GetPlayerByNum();
     if ( !cl ) {
         return;
     }
     if( cl->netchan.remoteAddress.type == NA_LOOPBACK ) {
         SV_SendServerCommand(NULL, "print \"%s\"", "Cannot kick host player\n");
         return;
     }
     SV_DropClient( cl, "was kicked" );
     cl->lastPacketTime = svs.time;  // in case there is a funny zombie
 }
References cl, Cmd_Argc(), Com_Printf(), com_sv_running, NA_LOOPBACK, NULL, SV_DropClient(), SV_GetPlayerByNum(), SV_SendServerCommand(), svs, and serverStatic_t::time.
Referenced by SV_AddOperatorCommands().
SV_KillServer_f()
static void SV_KillServer_f (void) static
Definition at line 1106 of file sv_ccmds.c.
{
     SV_Shutdown( "killserver" );
 }
References SV_Shutdown().
Referenced by SV_AddOperatorCommands().
SV_ListBans_f()
static void SV_ListBans_f (void) static
Definition at line 819 of file sv_ccmds.c.
 {
     int index, count;
     serverBan_t *ban;
     // List all bans
     for(index = count = 0; index < serverBansCount; index++)
     {
         ban = &serverBans[index];
         if(!ban->isexception)
         {
             count++;
             Com_Printf("Ban #%d: %s/%d\n", count,
                     NET_AdrToString(ban->ip), ban->subnet);
         }
     }
     // List all exceptions
     for(index = count = 0; index < serverBansCount; index++)
     {
         ban = &serverBans[index];
         if(ban->isexception)
         {
             count++;
             Com_Printf("Except #%d: %s/%d\n", count,
                     NET_AdrToString(ban->ip), ban->subnet);
         }
     }
 }
References Com_Printf(), serverBan_t::ip, serverBan_t::isexception, NET_AdrToString(), serverBans, serverBansCount, and serverBan_t::subnet.
Referenced by SV_AddOperatorCommands().
SV_Map_f()
static void SV_Map_f (void) static
Definition at line 153 of file sv_ccmds.c.
{
     char        *cmd;
     char        *map;
     qboolean    cheat;
     char        expanded[MAX_QPATH];
     char        mapname[MAX_QPATH];
     map = Cmd_Argv(1);
     if ( !map ) {
         return;
     }
     // make sure the level exists before trying to change, so that
     // a typo at the server console won't end the game
     Com_sprintf (expanded, sizeof(expanded), "maps/%s.bsp", map);
     if ( FS_ReadFile (expanded, NULL) == -1 ) {
         Com_Printf ("Can't find map %s\n", expanded);
         return;
     }
     // force latched values to get set
     Cvar_Get ("g_gametype", "0", CVAR_SERVERINFO | CVAR_USERINFO | CVAR_LATCH );
     cmd = Cmd_Argv(0);
     if( Q_stricmpn( cmd, "sp", 2 ) == 0 ) {
         Cvar_SetValue( "g_gametype", GT_SINGLE_PLAYER );
         Cvar_SetValue( "g_doWarmup", 0 );
         // may not set sv_maxclients directly, always set latched
         Cvar_SetLatched( "sv_maxclients", "8" );
         cmd += 2;
         if (!Q_stricmp( cmd, "devmap" ) ) {
             cheat = qtrue;
         } else {
             cheat = qfalse;
         }
     }
     else {
         if ( !Q_stricmp( cmd, "devmap" ) ) {
             cheat = qtrue;
         } else {
             cheat = qfalse;
         }
         if( sv_gametype->integer == GT_SINGLE_PLAYER ) {
             Cvar_SetValue( "g_gametype", GT_FFA );
         }
     }
     // save the map name here cause on a map restart we reload the q3config.cfg
     // and thus nuke the arguments of the map command
     Q_strncpyz(mapname, map, sizeof(mapname));
     // start up the map
     SV_SpawnServer( mapname );
     // set the cheat value
     // if the level was started with "map <levelname>", then
     // cheats will not be allowed.  If started with "devmap <levelname>"
     // then cheats will be allowed
     if ( cheat ) {
         Cvar_Set( "sv_cheats", "1" );
     } else {
         Cvar_Set( "sv_cheats", "0" );
     }
 }
References Cmd_Argv(), Com_Printf(), Com_sprintf(), Cvar_Get(), CVAR_LATCH, CVAR_SERVERINFO, Cvar_Set(), Cvar_SetLatched(), Cvar_SetValue(), CVAR_USERINFO, FS_ReadFile(), GT_FFA, GT_SINGLE_PLAYER, map, MAX_QPATH, NULL, Q_stricmp(), Q_stricmpn(), Q_strncpyz(), qfalse, qtrue, sv_gametype, and SV_SpawnServer().
Referenced by SV_AddOperatorCommands().
SV_MapRestart_f()
static void SV_MapRestart_f (void) static
Definition at line 226 of file sv_ccmds.c.
{
     int         i;
     client_t    *client;
     char        *denied;
     int         delay;
     // make sure we aren't restarting twice in the same frame
     if ( com_frameTime == sv.serverId ) {
         return;
     }
     // make sure server is running
     if ( !com_sv_running->integer ) {
         Com_Printf( "Server is not running.\n" );
         return;
     }
     if ( sv.restartTime ) {
         return;
     }
     if (Cmd_Argc() > 1 ) {
         delay = atoi( Cmd_Argv(1) );
     }
     else {
         delay = 5;
     }
     if( delay && !Cvar_VariableValue("g_doWarmup") ) {
         sv.restartTime = sv.time + delay * 1000;
         SV_SetConfigstring( CS_WARMUP, va("%i", sv.restartTime) );
         return;
     }
     // check for changes in variables that can't just be restarted
     // check for maxclients change
     if ( sv_maxclients->modified || sv_gametype->modified ) {
         char    mapname[MAX_QPATH];
         Com_Printf( "variable change -- restarting.\n" );
         // restart the map the slow way
         Q_strncpyz( mapname, Cvar_VariableString( "mapname" ), sizeof( mapname ) );
         SV_SpawnServer( mapname );
         return;
     }
     // toggle the server bit so clients can detect that a
     // map_restart has happened
     svs.snapFlagServerBit ^= SNAPFLAG_SERVERCOUNT;
     // generate a new serverid
     // TTimo - don't update restartedserverId there, otherwise we won't deal correctly with multiple map_restart
     sv.serverId = com_frameTime;
     Cvar_Set( "sv_serverid", va("%i", sv.serverId ) );
     // if a map_restart occurs while a client is changing maps, we need
     // to give them the correct time so that when they finish loading
     // they don't violate the backwards time check in cl_cgame.c
     for (i=0 ; i<sv_maxclients->integer ; i++) {
         if (svs.clients[i].state == CS_PRIMED) {
             svs.clients[i].oldServerTime = sv.restartTime;
         }
     }
     // reset all the vm data in place without changing memory allocation
     // note that we do NOT set sv.state = SS_LOADING, so configstrings that
     // had been changed from their default values will generate broadcast updates
     sv.state = SS_LOADING;
     sv.restarting = qtrue;
     SV_RestartGameProgs();
     // run a few frames to allow everything to settle
     for (i = 0; i < 3; i++)
     {
         VM_Call (gvm, GAME_RUN_FRAME, sv.time);
         sv.time += 100;
         svs.time += 100;
     }
     sv.state = SS_GAME;
     sv.restarting = qfalse;
     // connect and begin all the clients
     for (i=0 ; i<sv_maxclients->integer ; i++) {
         client = &svs.clients[i];
         // send the new gamestate to all connected clients
         if ( client->state < CS_CONNECTED) {
             continue;
         }
         // add the map_restart command
         SV_AddServerCommand( client, "map_restart\n" );
         // connect the client again, without the firstTime flag
         denied = VM_ExplicitArgPtr( gvm, VM_Call( gvm, GAME_CLIENT_CONNECT, i, qfalse) );
         if ( denied ) {
             // this generally shouldn't happen, because the client
             // was connected before the level change
             SV_DropClient( client, denied );
             Com_Printf( "SV_MapRestart_f(%d): dropped client %i - denied!\n", delay, i );
             continue;
         }
         if(client->state == CS_ACTIVE)
             SV_ClientEnterWorld(client, &client->lastUsercmd);
         else
         {
             // If we don't reset client->lastUsercmd and are restarting during map load,
             // the client will hang because we'll use the last Usercmd from the previous map,
             // which is wrong obviously.
             SV_ClientEnterWorld(client, NULL);
         }
     }
     // run another frame to allow things to look at all the players
     VM_Call (gvm, GAME_RUN_FRAME, sv.time);
     sv.time += 100;
     svs.time += 100;
 }
References serverStatic_t::clients, Cmd_Argc(), Cmd_Argv(), com_frameTime, Com_Printf(), com_sv_running, CS_ACTIVE, CS_CONNECTED, CS_PRIMED, CS_WARMUP, Cvar_Set(), Cvar_VariableString(), Cvar_VariableValue(), GAME_CLIENT_CONNECT, GAME_RUN_FRAME, gvm, MAX_QPATH, NULL, Q_strncpyz(), qfalse, qtrue, server_t::restarting, server_t::restartTime, server_t::serverId, SNAPFLAG_SERVERCOUNT, serverStatic_t::snapFlagServerBit, SS_GAME, SS_LOADING, server_t::state, sv, SV_AddServerCommand(), SV_ClientEnterWorld(), SV_DropClient(), sv_gametype, sv_maxclients, SV_RestartGameProgs(), SV_SetConfigstring(), SV_SpawnServer(), svs, server_t::time, serverStatic_t::time, va(), VM_Call(), and VM_ExplicitArgPtr().
Referenced by SV_AddOperatorCommands().
SV_ParseCIDRNotation()
static qboolean SV_ParseCIDRNotation (netadr_t * dest, int * mask, char * adrstr) static
Definition at line 545 of file sv_ccmds.c.
 {
     char *suffix;
     suffix = strchr(adrstr, '/');
     if(suffix)
     {
         *suffix = '\0';
         suffix++;
     }
     if(!NET_StringToAdr(adrstr, dest, NA_UNSPEC))
         return qtrue;
     if(suffix)
     {
         *mask = atoi(suffix);
         if(dest->type == NA_IP)
         {
             if(*mask < 1 || *mask > 32)
                 *mask = 32;
         }
         else
         {
             if(*mask < 1 || *mask > 128)
                 *mask = 128;
         }
     }
     else if(dest->type == NA_IP)
         *mask = 32;
     else
         *mask = 128;
     return qfalse;
 }
References NA_IP, NA_UNSPEC, NET_StringToAdr(), qfalse, qtrue, suffix(), and netadr_t::type.
Referenced by SV_AddBanToList(), and SV_DelBanFromList().
SV_RehashBans_f()
static void SV_RehashBans_f (void) static
Definition at line 403 of file sv_ccmds.c.
 {
     int index, filelen;
     fileHandle_t readfrom;
     char *textbuf, *curpos, *maskpos, *newlinepos, *endpos;
     char filepath[MAX_QPATH];
     serverBansCount = 0;
     if(!sv_banFile->string || !*sv_banFile->string)
         return;
     Com_sprintf(filepath, sizeof(filepath), "%s/%s", FS_GetCurrentGameDir(), sv_banFile->string);
     if((filelen = FS_SV_FOpenFileRead(filepath, &readfrom)) >= 0)
     {
         if(filelen < 2)
         {
             // Don't bother if file is too short.
             FS_FCloseFile(readfrom);
             return;
         }
         curpos = textbuf = Z_Malloc(filelen);
         filelen = FS_Read(textbuf, filelen, readfrom);
         FS_FCloseFile(readfrom);
         endpos = textbuf + filelen;
         for(index = 0; index < SERVER_MAXBANS && curpos + 2 < endpos; index++)
         {
             // find the end of the address string
             for(maskpos = curpos + 2; maskpos < endpos && *maskpos != ' '; maskpos++);
             if(maskpos + 1 >= endpos)
                 break;
             *maskpos = '\0';
             maskpos++;
             // find the end of the subnet specifier
             for(newlinepos = maskpos; newlinepos < endpos && *newlinepos != '\n'; newlinepos++);
             if(newlinepos >= endpos)
                 break;
             *newlinepos = '\0';
             if(NET_StringToAdr(curpos + 2, &serverBans[index].ip, NA_UNSPEC))
             {
                 serverBans[index].isexception = (curpos[0] != '0');
                 serverBans[index].subnet = atoi(maskpos);
                 if(serverBans[index].ip.type == NA_IP &&
                    (serverBans[index].subnet < 1 || serverBans[index].subnet > 32))
                 {
                     serverBans[index].subnet = 32;
                 }
                 else if(serverBans[index].ip.type == NA_IP6 &&
                     (serverBans[index].subnet < 1 || serverBans[index].subnet > 128))
                 {
                     serverBans[index].subnet = 128;
                 }
             }
             curpos = newlinepos + 1;
         }
         serverBansCount = index;
         Z_Free(textbuf);
     }
 }
References Com_sprintf(), FS_FCloseFile(), FS_GetCurrentGameDir(), FS_Read(), FS_SV_FOpenFileRead(), serverBan_t::isexception, MAX_QPATH, NA_IP, NA_IP6, NA_UNSPEC, NET_StringToAdr(), SERVER_MAXBANS, serverBans, serverBansCount, serverBan_t::subnet, sv_banFile, Z_Free(), and Z_Malloc.
Referenced by SV_AddOperatorCommands().
SV_RemoveOperatorCommands()
void SV_RemoveOperatorCommands (void)
Definition at line 1174 of file sv_ccmds.c.
{
 #if 0
     // removing these won't let the server start again
     Cmd_RemoveCommand ("heartbeat");
     Cmd_RemoveCommand ("kick");
     Cmd_RemoveCommand ("banUser");
     Cmd_RemoveCommand ("banClient");
     Cmd_RemoveCommand ("status");
     Cmd_RemoveCommand ("serverinfo");
     Cmd_RemoveCommand ("systeminfo");
     Cmd_RemoveCommand ("dumpuser");
     Cmd_RemoveCommand ("map_restart");
     Cmd_RemoveCommand ("sectorlist");
     Cmd_RemoveCommand ("say");
 #endif
 }
References Cmd_RemoveCommand().
Referenced by SV_Shutdown().
SV_Serverinfo_f()
static void SV_Serverinfo_f (void) static
Definition at line 1050 of file sv_ccmds.c.
{
     Com_Printf ("Server info settings:\n");
     Info_Print ( Cvar_InfoString( CVAR_SERVERINFO ) );
 }
References Com_Printf(), Cvar_InfoString(), CVAR_SERVERINFO, and Info_Print().
Referenced by SV_AddOperatorCommands().
SV_Status_f()
static void SV_Status_f (void) static
Definition at line 927 of file sv_ccmds.c.
{
     int         i, j, l;
     client_t    *cl;
     playerState_t   *ps;
     const char      *s;
     int         ping;
     // make sure server is running
     if ( !com_sv_running->integer ) {
         Com_Printf( "Server is not running.\n" );
         return;
     }
     Com_Printf ("map: %s\n", sv_mapname->string );
     Com_Printf ("num score ping name            lastmsg address               qport rate\n");
     Com_Printf ("--- ----- ---- --------------- ------- --------------------- ----- -----\n");
     for (i=0,cl=svs.clients ; i < sv_maxclients->integer ; i++,cl++)
     {
         if (!cl->state)
             continue;
         Com_Printf ("%3i ", i);
         ps = SV_GameClientNum( i );
         Com_Printf ("%5i ", ps->persistant[PERS_SCORE]);
         if (cl->state == CS_CONNECTED)
             Com_Printf ("CNCT ");
         else if (cl->state == CS_ZOMBIE)
             Com_Printf ("ZMBI ");
         else
         {
             ping = cl->ping < 9999 ? cl->ping : 9999;
             Com_Printf ("%4i ", ping);
         }
         Com_Printf ("%s", cl->name);
         // TTimo adding a ^7 to reset the color
         // NOTE: colored names in status breaks the padding (WONTFIX)
         Com_Printf ("^7");
         l = 14 - strlen(cl->name);
         j = 0;
         do
         {
             Com_Printf (" ");
             j++;
         } while(j < l);
         Com_Printf ("%7i ", svs.time - cl->lastPacketTime );
         s = NET_AdrToString( cl->netchan.remoteAddress );
         Com_Printf ("%s", s);
         l = 22 - strlen(s);
         j = 0;
         do
         {
             Com_Printf(" ");
             j++;
         } while(j < l);
         Com_Printf ("%5i", cl->netchan.qport);
         Com_Printf (" %5i", cl->rate);
         Com_Printf ("\n");
     }
     Com_Printf ("\n");
 }
References cl, serverStatic_t::clients, Com_Printf(), com_sv_running, CS_CONNECTED, CS_ZOMBIE, NET_AdrToString(), PERS_SCORE, SV_GameClientNum(), sv_mapname, svs, and serverStatic_t::time.
Referenced by SV_AddOperatorCommands().
SV_Systeminfo_f()
static void SV_Systeminfo_f (void) static
Definition at line 1063 of file sv_ccmds.c.
{
     Com_Printf ("System info settings:\n");
     Info_Print ( Cvar_InfoString_Big( CVAR_SYSTEMINFO ) );
 }
References Com_Printf(), Cvar_InfoString_Big(), CVAR_SYSTEMINFO, and Info_Print().
Referenced by SV_AddOperatorCommands().
SV_WriteBans()
static void SV_WriteBans (void) static
Definition at line 485 of file sv_ccmds.c.
 {
     int index;
     fileHandle_t writeto;
     char filepath[MAX_QPATH];
     if(!sv_banFile->string || !*sv_banFile->string)
         return;
     Com_sprintf(filepath, sizeof(filepath), "%s/%s", FS_GetCurrentGameDir(), sv_banFile->string);
     if((writeto = FS_SV_FOpenFileWrite(filepath)))
     {
         char writebuf[128];
         serverBan_t *curban;
         for(index = 0; index < serverBansCount; index++)
         {
             curban = &serverBans[index];
             Com_sprintf(writebuf, sizeof(writebuf), "%d %s %d\n",
                     curban->isexception, NET_AdrToString(curban->ip), curban->subnet);
             FS_Write(writebuf, strlen(writebuf), writeto);
         }
         FS_FCloseFile(writeto);
     }
 }
References Com_sprintf(), FS_FCloseFile(), FS_GetCurrentGameDir(), FS_SV_FOpenFileWrite(), FS_Write(), serverBan_t::ip, serverBan_t::isexception, MAX_QPATH, NET_AdrToString(), serverBans, serverBansCount, serverBan_t::subnet, and sv_banFile.
Referenced by SV_AddBanToList(), SV_DelBanFromList(), and SV_FlushBans_f().