ZEQ2-Lite: Engine/null/null_main.c File Reference
null_main.c File Reference
#include <errno.h>
#include <stdio.h>
#include "../../Shared/qcommon.h"
Functions
void main (int argc, char **argv)
void Sys_BeginStreamedFile (FILE *f, int readAhead)
void Sys_EarlyOutput (char *string)
void Sys_EndStreamedFile (FILE *f)
void Sys_Error (char *error,...)
void Sys_FindClose (void)
char * Sys_FindFirst (char *path, unsigned musthave, unsigned canthave)
char * Sys_FindNext (unsigned musthave, unsigned canthave)
char * Sys_GetClipboardData (void)
void * Sys_GetGameAPI (void *parms)
void Sys_Init (void)
int Sys_Milliseconds (void)
void Sys_Mkdir (char *path)
void Sys_mkdir (const char *path)
void Sys_Quit (void)
int Sys_StreamedRead (void *buffer, int size, int count, FILE *f)
void Sys_StreamSeek (FILE *f, int offset, int origin)
void Sys_UnloadGame (void)
Variables
int sys_curtime
Function Documentation
main()
void main (int argc, char ** argv)
Definition at line 108 of file null_main.c.
{
     Com_Init (argc, argv);
     while (1) {
         Com_Frame( );
     }
 }
References Com_Frame(), and Com_Init().
Sys_BeginStreamedFile()
void Sys_BeginStreamedFile (FILE * f, int readAhead)
Definition at line 33 of file null_main.c.
{
 }
Sys_EarlyOutput()
void Sys_EarlyOutput (char * string)
Definition at line 103 of file null_main.c.
{
     printf( "%s", string );
 }
Sys_EndStreamedFile()
void Sys_EndStreamedFile (FILE * f)
Definition at line 36 of file null_main.c.
{
 }
Sys_Error()
void Sys_Error (char * error, ...)
Definition at line 54 of file null_main.c.
{
     va_list     argptr;
     printf ("Sys_Error: ");
     va_start (argptr,error);
     vprintf (error,argptr);
     va_end (argptr);
     printf ("\n");
     exit (1);
 }
References error().
Referenced by Com_Error(), and Com_Init().
Sys_FindClose()
void Sys_FindClose (void)
Definition at line 96 of file null_main.c.
{
 }
Sys_FindFirst()
char* Sys_FindFirst (char * path, unsigned musthave, unsigned canthave)
Definition at line 88 of file null_main.c.
{
     return NULL;
 }
References NULL.
Sys_FindNext()
char* Sys_FindNext (unsigned musthave, unsigned canthave)
Definition at line 92 of file null_main.c.
{
     return NULL;
 }
References NULL.
Sys_GetClipboardData()
char* Sys_GetClipboardData (void)
Definition at line 77 of file null_main.c.
{
     return NULL;
 }
Referenced by CL_GetClipboardData(), and Field_Paste().
Sys_GetGameAPI()
void* Sys_GetGameAPI (void * parms)
Definition at line 73 of file null_main.c.
{
     return NULL;
 }
References NULL.
Sys_Init()
void Sys_Init (void)
Definition at line 99 of file null_main.c.
{
 }
Referenced by Com_Init().
Sys_Milliseconds()
int Sys_Milliseconds (void)
Definition at line 81 of file null_main.c.
{
     return 0;
 }
Referenced by CL_CgameSystemCalls(), CL_DemoCompleted(), CL_GetFreePing(), CL_GetPing(), CL_InitCGame(), CL_Ping_f(), CL_ScaledMilliseconds(), CL_ServerInfoPacket(), CL_SetCGameTime(), CL_UISystemCalls(), CL_UpdateVisiblePings_f(), Com_Error(), Com_Frame(), Com_GetSystemEvent(), Com_QueueEvent(), Com_RunAndTimeServerPacket(), Com_TimeVal(), Com_TouchMemory(), IN_Frame(), IN_ProcessEvents(), main(), NET_FlushPacketQueue(), NET_QueuePacket(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_Frame(), SV_GameSystemCalls(), SV_RateMsec(), SV_SendQueuedPackets(), SVC_BucketForAddress(), and SVC_RateLimit().
Sys_Mkdir()
void Sys_Mkdir (char * path)
Definition at line 85 of file null_main.c.
{
 }
Referenced by FS_CreatePath().
Sys_mkdir()
void Sys_mkdir (const char * path)
Definition at line 51 of file null_main.c.
{
 }
Sys_Quit()
void Sys_Quit (void)
Definition at line 66 of file null_main.c.
                      {
     exit (0);
 }
Referenced by Com_Quit_f().
Sys_StreamedRead()
int Sys_StreamedRead (void * buffer, int size, int count, FILE * f)
Definition at line 39 of file null_main.c.
{
     return fread( buffer, size, count, f );
 }
References fread().
Sys_StreamSeek()
void Sys_StreamSeek (FILE * f, int offset, int origin)
Definition at line 43 of file null_main.c.
{
     fseek( f, offset, origin );
 }
Sys_UnloadGame()
void Sys_UnloadGame (void)
Definition at line 70 of file null_main.c.
{
 }
Variable Documentation
sys_curtime
int sys_curtime
Definition at line 28 of file null_main.c.
Referenced by Sys_Milliseconds().