ZEQ2-Lite: Shared/msg.c File Reference
msg.c File Reference
#include "q_shared.h"
#include "qcommon.h"
Data Structures
struct netField_t
Macros
#define CM_ANGLE1 (1<<0)
#define CM_ANGLE2 (1<<1)
#define CM_ANGLE3 (1<<2)
#define CM_BUTTONS (1<<6)
#define CM_FORWARD (1<<3)
#define CM_SIDE (1<<4)
#define CM_UP (1<<5)
#define CM_WEAPON (1<<7)
#define FLOAT_INT_BIAS (1<<(FLOAT_INT_BITS-1))
#define FLOAT_INT_BITS 13
#define LOG(x) if(cl_shownet->integer == 4) { Com_Printf("%s ", x); };
#define NETF(x) #x,(size_t)&((entityState_t*)0)->x
#define PSF(x) #x,(size_t)&((playerState_t*)0)->x
Functions
void MSG_BeginReading (msg_t *msg)
void MSG_BeginReadingOOB (msg_t *msg)
void MSG_Bitstream (msg_t *buf)
void MSG_Clear (msg_t *buf)
void MSG_Copy (msg_t *buf, byte *data, int length, msg_t *src)
int MSG_HashKey (const char *string, int maxlen)
void MSG_Init (msg_t *buf, byte *data, int length)
void MSG_initHuffman (void)
void MSG_InitOOB (msg_t *buf, byte *data, int length)
int MSG_LookaheadByte (msg_t *msg)
float MSG_ReadAngle16 (msg_t *msg)
char * MSG_ReadBigString (msg_t *msg)
int MSG_ReadBits (msg_t *msg, int bits)
int MSG_ReadByte (msg_t *msg)
int MSG_ReadChar (msg_t *msg)
void MSG_ReadData (msg_t *msg, void *data, int len)
int MSG_ReadDelta (msg_t *msg, int oldV, int bits)
void MSG_ReadDeltaEntity (msg_t *msg, entityState_t *from, entityState_t *to, int number)
float MSG_ReadDeltaFloat (msg_t *msg, float oldV)
int MSG_ReadDeltaKey (msg_t *msg, int key, int oldV, int bits)
float MSG_ReadDeltaKeyFloat (msg_t *msg, int key, float oldV)
void MSG_ReadDeltaPlayerstate (msg_t *msg, playerState_t *from, playerState_t *to)
void MSG_ReadDeltaUsercmd (msg_t *msg, usercmd_t *from, usercmd_t *to)
void MSG_ReadDeltaUsercmdKey (msg_t *msg, int key, usercmd_t *from, usercmd_t *to)
float MSG_ReadFloat (msg_t *msg)
int MSG_ReadLong (msg_t *msg)
int MSG_ReadShort (msg_t *msg)
char * MSG_ReadString (msg_t *msg)
char * MSG_ReadStringLine (msg_t *msg)
void MSG_ReportChangeVectors_f (void)
void MSG_WriteAngle (msg_t *sb, float f)
void MSG_WriteAngle16 (msg_t *sb, float f)
void MSG_WriteBigString (msg_t *sb, const char *s)
void MSG_WriteBits (msg_t *msg, int value, int bits)
void MSG_WriteByte (msg_t *sb, int c)
void MSG_WriteChar (msg_t *sb, int c)
void MSG_WriteData (msg_t *buf, const void *data, int length)
void MSG_WriteDelta (msg_t *msg, int oldV, int newV, int bits)
void MSG_WriteDeltaEntity (msg_t *msg, struct entityState_s *from, struct entityState_s *to, qboolean force)
void MSG_WriteDeltaFloat (msg_t *msg, float oldV, float newV)
void MSG_WriteDeltaKey (msg_t *msg, int key, int oldV, int newV, int bits)
void MSG_WriteDeltaKeyFloat (msg_t *msg, int key, float oldV, float newV)
void MSG_WriteDeltaPlayerstate (msg_t *msg, struct playerState_s *from, struct playerState_s *to)
void MSG_WriteDeltaUsercmd (msg_t *msg, usercmd_t *from, usercmd_t *to)
void MSG_WriteDeltaUsercmdKey (msg_t *msg, int key, usercmd_t *from, usercmd_t *to)
void MSG_WriteFloat (msg_t *sb, float f)
void MSG_WriteLong (msg_t *sb, int c)
void MSG_WriteShort (msg_t *sb, int c)
void MSG_WriteString (msg_t *sb, const char *s)
Variables
cvar_t * cl_shownet
netField_t entityStateFields []
int kbitmask [32]
int msg_hData [256]
static huffman_t msgHuff
static qboolean msgInit = qfalse
int oldsize = 0
int overflows
int pcount [256]
netField_t playerStateFields []
Macro Definition Documentation
CM_ANGLE1
#define CM_ANGLE1 (1<<0)
Definition at line 670 of file msg.c.
CM_ANGLE2
#define CM_ANGLE2 (1<<1)
Definition at line 671 of file msg.c.
CM_ANGLE3
#define CM_ANGLE3 (1<<2)
Definition at line 672 of file msg.c.
CM_BUTTONS
#define CM_BUTTONS (1<<6)
Definition at line 676 of file msg.c.
CM_FORWARD
#define CM_FORWARD (1<<3)
Definition at line 673 of file msg.c.
CM_SIDE
#define CM_SIDE (1<<4)
Definition at line 674 of file msg.c.
CM_UP
#define CM_UP (1<<5)
Definition at line 675 of file msg.c.
CM_WEAPON
#define CM_WEAPON (1<<7)
Definition at line 677 of file msg.c.
FLOAT_INT_BIAS
#define FLOAT_INT_BIAS (1<<(FLOAT_INT_BITS-1))
Definition at line 925 of file msg.c.
FLOAT_INT_BITS
#define FLOAT_INT_BITS 13
Definition at line 924 of file msg.c.
LOG
#define LOG (x) if(cl_shownet->integer == 4) { Com_Printf("%s ", x); };
Definition at line 565 of file msg.c.
NETF
#define NETF (x) #x,(size_t)&((entityState_t*)0)->x
Definition at line 844 of file msg.c.
PSF
#define PSF (x) #x,(size_t)&((playerState_t*)0)->x
Definition at line 1181 of file msg.c.
Function Documentation
MSG_BeginReading()
void MSG_BeginReading (msg_t * msg)
Definition at line 74 of file msg.c.
{
     msg->readcount = 0;
     msg->bit = 0;
     msg->oob = qfalse;
 }
References msg_t::bit, msg_t::oob, qfalse, and msg_t::readcount.
MSG_BeginReadingOOB()
void MSG_BeginReadingOOB (msg_t * msg)
Definition at line 80 of file msg.c.
{
     msg->readcount = 0;
     msg->bit = 0;
     msg->oob = qtrue;
 }
References msg_t::bit, msg_t::oob, qtrue, and msg_t::readcount.
Referenced by CL_ConnectionlessPacket(), Netchan_Process(), SV_ConnectionlessPacket(), and SV_PacketEvent().
MSG_Bitstream()
void MSG_Bitstream (msg_t * buf)
Definition at line 70 of file msg.c.
{
     buf->oob = qfalse;
 }
References qfalse.
Referenced by CL_ParseServerMessage(), CL_Record_f(), CL_WritePacket(), and SV_ExecuteClientMessage().
MSG_Clear()
void MSG_Clear (msg_t * buf)
Definition at line 63 of file msg.c.
{
     buf->cursize = 0;
     buf->overflowed = qfalse;
     buf->bit = 0;                   //<- in bits
 }
References qfalse.
Referenced by SV_SendClientSnapshot().
MSG_Copy()
void MSG_Copy (msg_t * buf, byte * data, int length, msg_t * src)
Definition at line 86 of file msg.c.
 {
     if (length<src->cursize) {
         Com_Error( ERR_DROP, "MSG_Copy: can't copy into a smaller msg_t buffer");
     }
     Com_Memcpy(buf, src, sizeof(msg_t));
     buf->data = data;
     Com_Memcpy(buf->data, src->data, src->cursize);
 }
References Com_Error(), Com_Memcpy, and ERR_DROP.
Referenced by SV_Netchan_Transmit().
MSG_HashKey()
int MSG_HashKey (const char * string, int maxlen)
Definition at line 541 of file msg.c.
{
     int hash, i;
     hash = 0;
     for (i = 0; i < maxlen && string[i] != '\0'; i++) {
         if (string[i] & 0x80 || string[i] == '%')
             hash += '.' * (119 + i);
         else
             hash += string[i] * (119 + i);
     }
     hash = (hash ^ (hash >> 10) ^ (hash >> 20));
     return hash;
 }
References hash().
Referenced by CL_WritePacket(), and SV_UserMove().
MSG_Init()
void MSG_Init (msg_t * buf, byte * data, int length)
Definition at line 44 of file msg.c.
{
     if (!msgInit) {
         MSG_initHuffman();
     }
     Com_Memset (buf, 0, sizeof(*buf));
     buf->data = data;
     buf->maxsize = length;
 }
References Com_Memset, MSG_initHuffman(), and msgInit.
Referenced by CL_ReadDemoMessage(), CL_Record_f(), CL_WritePacket(), Com_EventLoop(), NET_Event(), SV_SendClientGameState(), SV_SendClientSnapshot(), and SV_SendDownloadMessages().
MSG_initHuffman()
void MSG_initHuffman (void)
Definition at line 2029 of file msg.c.
{
     int i,j;
     msgInit = qtrue;
     Huff_Init(&msgHuff);
     for(i=0;i<256;i++) {
         for (j=0;j<msg_hData[i];j++) {
             Huff_addRef(&msgHuff.compressor,    (byte)i);           // Do update
             Huff_addRef(&msgHuff.decompressor,  (byte)i);           // Do update
         }
     }
 }
References huffman_t::compressor, huffman_t::decompressor, Huff_addRef(), Huff_Init(), msg_hData, msgHuff, msgInit, and qtrue.
Referenced by MSG_Init(), and MSG_InitOOB().
MSG_InitOOB()
void MSG_InitOOB (msg_t * buf, byte * data, int length)
Definition at line 53 of file msg.c.
{
     if (!msgInit) {
         MSG_initHuffman();
     }
     Com_Memset (buf, 0, sizeof(*buf));
     buf->data = data;
     buf->maxsize = length;
     buf->oob = qtrue;
 }
References Com_Memset, MSG_initHuffman(), msgInit, and qtrue.
Referenced by Netchan_Transmit(), and Netchan_TransmitNextFragment().
MSG_LookaheadByte()
int MSG_LookaheadByte (msg_t * msg)
Definition at line 399 of file msg.c.
{
     const int bloc = Huff_getBloc();
     const int readcount = msg->readcount;
     const int bit = msg->bit;
     int c = MSG_ReadByte(msg);
     Huff_setBloc(bloc);
     msg->readcount = readcount;
     msg->bit = bit;
     return c;
 }
References msg_t::bit, bloc, Huff_getBloc(), Huff_setBloc(), MSG_ReadByte(), and msg_t::readcount.
MSG_ReadAngle16()
float MSG_ReadAngle16 (msg_t * msg)
Definition at line 527 of file msg.c.
{
     return SHORT2ANGLE(MSG_ReadShort(msg));
 }
References MSG_ReadShort(), and SHORT2ANGLE.
MSG_ReadBigString()
char* MSG_ReadBigString (msg_t * msg)
Definition at line 471 of file msg.c.
{
     static char string[BIG_INFO_STRING];
     int     l,c;
     l = 0;
     do {
         c = MSG_ReadByte(msg);      // use ReadByte so -1 is out of bounds
         if ( c == -1 || c == 0 ) {
             break;
         }
         // translate all fmt spec to avoid crash bugs
         if ( c == '%' ) {
             c = '.';
         }
         // don't allow higher ascii values
         if ( c > 127 ) {
             c = '.';
         }
         string[l] = c;
         l++;
     } while (l < sizeof(string)-1);
     string[l] = 0;
     return string;
 }
References BIG_INFO_STRING, and MSG_ReadByte().
Referenced by CL_ParseGamestate().
MSG_ReadBits()
int MSG_ReadBits (msg_t * msg, int bits)
Definition at line 189 of file msg.c.
{
     int         value;
     int         get;
     qboolean    sgn;
     int         i, nbits;
 //  FILE*   fp;
     value = 0;
     if ( bits < 0 ) {
         bits = -bits;
         sgn = qtrue;
     } else {
         sgn = qfalse;
     }
     if (msg->oob) {
         if(bits==8)
         {
             value = msg->data[msg->readcount];
             msg->readcount += 1;
             msg->bit += 8;
         }
         else if(bits==16)
         {
             short temp;
             CopyLittleShort(&temp, &msg->data[msg->readcount]);
             value = temp;
             msg->readcount += 2;
             msg->bit += 16;
         }
         else if(bits==32)
         {
             CopyLittleLong(&value, &msg->data[msg->readcount]);
             msg->readcount += 4;
             msg->bit += 32;
         }
         else
             Com_Error(ERR_DROP, "can't read %d bits", bits);
     } else {
         nbits = 0;
         if (bits&7) {
             nbits = bits&7;
             for(i=0;i<nbits;i++) {
                 value |= (Huff_getBit(msg->data, &msg->bit)<<i);
             }
             bits = bits - nbits;
         }
         if (bits) {
 //          fp = fopen("c:\\netchan.bin", "a");
             for(i=0;i<bits;i+=8) {
                 Huff_offsetReceive (msgHuff.decompressor.tree, &get, msg->data, &msg->bit);
 //              fwrite(&get, 1, 1, fp);
                 value |= (get<<(i+nbits));
             }
 //          fclose(fp);
         }
         msg->readcount = (msg->bit>>3)+1;
     }
     if ( sgn ) {
         if ( value & ( 1 << ( bits - 1 ) ) ) {
             value |= -1 ^ ( ( 1 << bits ) - 1 );
         }
     }
     return value;
 }
References msg_t::bit, bits(), Com_Error(), msg_t::data, huffman_t::decompressor, ERR_DROP, get(), Huff_getBit(), Huff_offsetReceive(), msgHuff, msg_t::oob, qfalse, qtrue, msg_t::readcount, and huff_t::tree.
Referenced by CL_ParseGamestate(), CL_ParsePacketEntities(), MSG_ReadByte(), MSG_ReadChar(), MSG_ReadDelta(), MSG_ReadDeltaEntity(), MSG_ReadDeltaFloat(), MSG_ReadDeltaKey(), MSG_ReadDeltaKeyFloat(), MSG_ReadDeltaPlayerstate(), MSG_ReadDeltaUsercmd(), MSG_ReadDeltaUsercmdKey(), MSG_ReadFloat(), MSG_ReadLong(), and MSG_ReadShort().
MSG_ReadByte()
int MSG_ReadByte (msg_t * msg)
Definition at line 389 of file msg.c.
{
     int c;
     c = (unsigned char)MSG_ReadBits( msg, 8 );
     if ( msg->readcount > msg->cursize ) {
         c = -1;
     }
     return c;
 }
References msg_t::cursize, MSG_ReadBits(), and msg_t::readcount.
Referenced by CL_ParseGamestate(), CL_ParseServerMessage(), CL_ParseSnapshot(), MSG_LookaheadByte(), MSG_ReadBigString(), MSG_ReadData(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_ReadString(), MSG_ReadStringLine(), SV_ExecuteClientMessage(), and SV_UserMove().
MSG_ReadChar()
int MSG_ReadChar (msg_t * msg)
Definition at line 378 of file msg.c.
{
     int c;
     c = (signed char)MSG_ReadBits( msg, 8 );
     if ( msg->readcount > msg->cursize ) {
         c = -1;
     }
     return c;
 }
References msg_t::cursize, MSG_ReadBits(), and msg_t::readcount.
MSG_ReadData()
void MSG_ReadData (msg_t * msg, void * data, int len)
Definition at line 531 of file msg.c.
{
     int     i;
     for (i=0 ; i<len ; i++) {
         ((byte *)data)[i] = MSG_ReadByte (msg);
     }
 }
References MSG_ReadByte().
Referenced by CL_ParseDownload(), and CL_ParseSnapshot().
MSG_ReadDelta()
int MSG_ReadDelta (msg_t * msg, int oldV, int bits)
Definition at line 576 of file msg.c.
{
     if ( MSG_ReadBits( msg, 1 ) ) {
         return MSG_ReadBits( msg, bits );
     }
     return oldV;
 }
References bits(), and MSG_ReadBits().
Referenced by MSG_ReadDeltaUsercmd().
MSG_ReadDeltaEntity()
void MSG_ReadDeltaEntity (msg_t * msg, entityState_t * from, entityState_t * to, int number)
Definition at line 1055 of file msg.c.
{
     int         i, lc;
     int         numFields;
     netField_t  *field;
     int         *fromF, *toF;
     int         print;
     int         trunc;
     int         startBit, endBit;
     if ( number < 0 || number >= MAX_GENTITIES) {
         Com_Error( ERR_DROP, "Bad delta entity number: %i", number );
     }
     if ( msg->bit == 0 ) {
         startBit = msg->readcount * 8 - GENTITYNUM_BITS;
     } else {
         startBit = ( msg->readcount - 1 ) * 8 + msg->bit - GENTITYNUM_BITS;
     }
     // check for a remove
     if ( MSG_ReadBits( msg, 1 ) == 1 ) {
         Com_Memset( to, 0, sizeof( *to ) );
         to->number = MAX_GENTITIES - 1;
         if ( cl_shownet->integer >= 2 || cl_shownet->integer == -1 ) {
             Com_Printf( "%3i: #%-3i remove\n", msg->readcount, number );
         }
         return;
     }
     // check for no delta
     if ( MSG_ReadBits( msg, 1 ) == 0 ) {
         *to = *from;
         to->number = number;
         return;
     }
     numFields = ARRAY_LEN( entityStateFields );
     lc = MSG_ReadByte(msg);
     if ( lc > numFields || lc < 0 ) {
         Com_Error( ERR_DROP, "invalid entityState field count" );
     }
     // shownet 2/3 will interleave with other printed info, -1 will
     // just print the delta records`
     if ( cl_shownet->integer >= 2 || cl_shownet->integer == -1 ) {
         print = 1;
         Com_Printf( "%3i: #%-3i ", msg->readcount, to->number );
     } else {
         print = 0;
     }
     to->number = number;
     for ( i = 0, field = entityStateFields ; i < lc ; i++, field++ ) {
         fromF = (int *)( (byte *)from + field->offset );
         toF = (int *)( (byte *)to + field->offset );
         if ( ! MSG_ReadBits( msg, 1 ) ) {
             // no change
             *toF = *fromF;
         } else {
             if ( field->bits == 0 ) {
                 // float
                 if ( MSG_ReadBits( msg, 1 ) == 0 ) {
                         *(float *)toF = 0.0f;
                 } else {
                     if ( MSG_ReadBits( msg, 1 ) == 0 ) {
                         // integral float
                         trunc = MSG_ReadBits( msg, FLOAT_INT_BITS );
                         // bias to allow equal parts positive and negative
                         trunc -= FLOAT_INT_BIAS;
                         *(float *)toF = trunc;
                         if ( print ) {
                             Com_Printf( "%s:%i ", field->name, trunc );
                         }
                     } else {
                         // full floating point value
                         *toF = MSG_ReadBits( msg, 32 );
                         if ( print ) {
                             Com_Printf( "%s:%f ", field->name, *(float *)toF );
                         }
                     }
                 }
             } else {
                 if ( MSG_ReadBits( msg, 1 ) == 0 ) {
                     *toF = 0;
                 } else {
                     // integer
                     *toF = MSG_ReadBits( msg, field->bits );
                     if ( print ) {
                         Com_Printf( "%s:%i ", field->name, *toF );
                     }
                 }
             }
 //          pcount[i]++;
         }
     }
     for ( i = lc, field = &entityStateFields[lc] ; i < numFields ; i++, field++ ) {
         fromF = (int *)( (byte *)from + field->offset );
         toF = (int *)( (byte *)to + field->offset );
         // no change
         *toF = *fromF;
     }
     if ( print ) {
         if ( msg->bit == 0 ) {
             endBit = msg->readcount * 8 - GENTITYNUM_BITS;
         } else {
             endBit = ( msg->readcount - 1 ) * 8 + msg->bit - GENTITYNUM_BITS;
         }
         Com_Printf( " (%i bits)\n", endBit - startBit  );
     }
 }
References ARRAY_LEN, msg_t::bit, cl_shownet, Com_Error(), Com_Memset, Com_Printf(), entityStateFields, ERR_DROP, field(), FLOAT_INT_BIAS, FLOAT_INT_BITS, GENTITYNUM_BITS, MAX_GENTITIES, MSG_ReadBits(), MSG_ReadByte(), Field::name, Field::offset, print(), and msg_t::readcount.
Referenced by CL_DeltaEntity(), and CL_ParseGamestate().
MSG_ReadDeltaFloat()
float MSG_ReadDeltaFloat (msg_t * msg, float oldV)
Definition at line 594 of file msg.c.
{
     if ( MSG_ReadBits( msg, 1 ) ) {
         floatint_t fi;
         fi.i = MSG_ReadBits( msg, 32 );
         return fi.f;
     }
     return oldV;
 }
References floatint_t::f, floatint_t::i, and MSG_ReadBits().
MSG_ReadDeltaKey()
int MSG_ReadDeltaKey (msg_t * msg, int key, int oldV, int bits)
Definition at line 632 of file msg.c.
{
     if ( MSG_ReadBits( msg, 1 ) ) {
         return MSG_ReadBits( msg, bits ) ^ (key & kbitmask[bits]);
     }
     return oldV;
 }
References bits(), kbitmask, and MSG_ReadBits().
Referenced by MSG_ReadDeltaUsercmdKey().
MSG_ReadDeltaKeyFloat()
float MSG_ReadDeltaKeyFloat (msg_t * msg, int key, float oldV)
Definition at line 650 of file msg.c.
{
     if ( MSG_ReadBits( msg, 1 ) ) {
         floatint_t fi;
         fi.i = MSG_ReadBits( msg, 32 ) ^ key;
         return fi.f;
     }
     return oldV;
 }
References floatint_t::f, floatint_t::i, and MSG_ReadBits().
MSG_ReadDeltaPlayerstate()
void MSG_ReadDeltaPlayerstate (msg_t * msg, playerState_t * from, playerState_t * to)
Definition at line 1546 of file msg.c.
{
     int         i, lc;
     int         bits;
     netField_t  *field;
     int         numFields;
     int         startBit, endBit;
     int         print;
     int         *fromF, *toF;
     int         trunc;
     playerState_t   dummy;
     if ( !from ) {
         from = &dummy;
         Com_Memset( &dummy, 0, sizeof( dummy ) );
     }
     *to = *from;
     if ( msg->bit == 0 ) {
         startBit = msg->readcount * 8 - GENTITYNUM_BITS;
     } else {
         startBit = ( msg->readcount - 1 ) * 8 + msg->bit - GENTITYNUM_BITS;
     }
     // shownet 2/3 will interleave with other printed info, -2 will
     // just print the delta records
     if ( cl_shownet->integer >= 2 || cl_shownet->integer == -2 ) {
         print = 1;
         Com_Printf( "%3i: playerstate ", msg->readcount );
     } else {
         print = 0;
     }
     numFields = ARRAY_LEN( playerStateFields );
     lc = MSG_ReadByte(msg);
     for ( i = 0, field = playerStateFields ; i < lc ; i++, field++ ) {
         fromF = (int *)( (byte *)from + field->offset );
         toF = (int *)( (byte *)to + field->offset );
         if ( ! MSG_ReadBits( msg, 1 ) ) {
             // no change
             *toF = *fromF;
         } else {
             if ( field->bits == 0 ) {
                 // float
                 if ( MSG_ReadBits( msg, 1 ) == 0 ) {
                     // integral float
                     trunc = MSG_ReadBits( msg, FLOAT_INT_BITS );
                     // bias to allow equal parts positive and negative
                     trunc -= FLOAT_INT_BIAS;
                     *(float *)toF = trunc;
                     if ( print ) {
                         Com_Printf( "%s:%i ", field->name, trunc );
                     }
                 } else {
                     // full floating point value
                     *toF = MSG_ReadBits( msg, 32 );
                     if ( print ) {
                         Com_Printf( "%s:%f ", field->name, *(float *)toF );
                     }
                 }
             } else {
                 // integer
                 *toF = MSG_ReadBits( msg, field->bits );
                 if ( print ) {
                     Com_Printf( "%s:%i ", field->name, *toF );
                 }
             }
         }
     }
     for ( i=lc,field = &playerStateFields[lc];i<numFields; i++, field++) {
         fromF = (int *)( (byte *)from + field->offset );
         toF = (int *)( (byte *)to + field->offset );
         // no change
         *toF = *fromF;
     }
     // read the arrays
     if (MSG_ReadBits( msg, 1 ) ) {
         // parse stats
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_STATS");
             bits = MSG_ReadBits (msg, MAX_STATS);
             for (i=0 ; i<MAX_STATS ; i++) {
                 if (bits & (1<<i) ) {
                     to->stats[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse locked stats
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_LOCKED_STATS");
             bits = MSG_ReadBits (msg, MAX_LOCKED_STATS);
             for (i=0 ; i<MAX_LOCKED_STATS ; i++) {
                 if (bits & (1<<i) ) {
                     to->lockonData[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse persistant stats
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_PERSISTANT");
             bits = MSG_ReadBits (msg, MAX_PERSISTANT);
             for (i=0 ; i<MAX_PERSISTANT ; i++) {
                 if (bits & (1<<i) ) {
                     to->persistant[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse ammo
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_SKILLS");
             bits = MSG_ReadBits (msg, MAX_WEAPONS);
             for (i=0 ; i<MAX_WEAPONS ; i++) {
                 if (bits & (1<<i) ) {
                     to->currentSkill[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse powerups
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_POWERUPS");
             bits = MSG_ReadBits (msg, MAX_POWERUPS);
             for (i=0 ; i<MAX_POWERUPS ; i++) {
                 if (bits & (1<<i) ) {
                     to->powerups[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse timers
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_TIMERS");
             bits = MSG_ReadBits (msg, MAX_TIMERS);
             for (i=0 ; i<MAX_TIMERS ; i++) {
                 if (bits & (1<<i) ) {
                     to->timers[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse cooldown
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_COOLDOWN");
             bits = MSG_ReadBits (msg, MAX_COOLDOWN);
             for (i=0 ; i<MAX_COOLDOWN ; i++) {
                 if (bits & (1<<i) ) {
                     to->cooldownTimers[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse sequence
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_SEQUENCE");
             bits = MSG_ReadBits (msg, MAX_SEQUENCE);
             for (i=0 ; i<MAX_SEQUENCE ; i++) {
                 if (bits & (1<<i) ) {
                     to->sequenceTimers[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse measure
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_MEASURE");
             bits = MSG_ReadBits (msg, MAX_MEASURES);
             for (i=0 ; i<MAX_MEASURES ; i++) {
                 if (bits & (1<<i) ) {
                     to->measureTimers[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse powerlevel
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_POWERLEVEL");
             bits = MSG_ReadBits (msg, MAX_POWERSTATS);
             for (i=0 ; i<MAX_POWERSTATS ; i++) {
                 if (bits & (1<<i) ) {
                     to->powerLevel[i] = MSG_ReadShort(msg);
                 }
             }
         }
         // parse base stats
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_BASESTATS");
             bits = MSG_ReadBits (msg, MAX_BASESTATS);
             for (i=0 ; i<MAX_BASESTATS ; i++) {
                 if (bits & (1<<i) ) {
                     to->baseStats[i] = MSG_ReadFloat(msg);
                 }
             }
         }
         // parse buffers
         if ( MSG_ReadBits( msg, 1 ) ) {
             LOG("PS_RBUFFERS");
             bits = MSG_ReadBits (msg, MAX_RBUFFERS);
             for (i=0 ; i<MAX_RBUFFERS ; i++) {
                 if (bits & (1<<i) ) {
                     to->buffers[i] = MSG_ReadFloat(msg);
                 }
             }
         }
     }
     if ( print ) {
         if ( msg->bit == 0 ) {
             endBit = msg->readcount * 8 - GENTITYNUM_BITS;
         } else {
             endBit = ( msg->readcount - 1 ) * 8 + msg->bit - GENTITYNUM_BITS;
         }
         Com_Printf( " (%i bits)\n", endBit - startBit  );
     }
 }
References ARRAY_LEN, msg_t::bit, bits(), cl_shownet, Com_Memset, Com_Printf(), field(), FLOAT_INT_BIAS, FLOAT_INT_BITS, GENTITYNUM_BITS, LOG, MAX_BASESTATS, MAX_COOLDOWN, MAX_LOCKED_STATS, MAX_MEASURES, MAX_PERSISTANT, MAX_POWERSTATS, MAX_POWERUPS, MAX_RBUFFERS, MAX_SEQUENCE, MAX_STATS, MAX_TIMERS, MAX_WEAPONS, MSG_ReadBits(), MSG_ReadByte(), MSG_ReadFloat(), MSG_ReadShort(), Field::name, Field::offset, playerStateFields, print(), and msg_t::readcount.
Referenced by CL_ParseSnapshot().
MSG_ReadDeltaUsercmd()
void MSG_ReadDeltaUsercmd (msg_t * msg, usercmd_t * from, usercmd_t * to)
Definition at line 711 of file msg.c.
{
     if ( MSG_ReadBits( msg, 1 ) ) {
         to->serverTime = from->serverTime + MSG_ReadBits( msg, 8 );
     } else {
         to->serverTime = MSG_ReadBits( msg, 32 );
     }
     to->angles[0] = MSG_ReadDelta( msg, from->angles[0], 16);
     to->angles[1] = MSG_ReadDelta( msg, from->angles[1], 16);
     to->angles[2] = MSG_ReadDelta( msg, from->angles[2], 16);
     to->forwardmove = MSG_ReadDelta( msg, from->forwardmove, 8);
     to->rightmove = MSG_ReadDelta( msg, from->rightmove, 8);
     to->upmove = MSG_ReadDelta( msg, from->upmove, 8);
     to->buttons = MSG_ReadDelta( msg, from->buttons, 16);
     to->weapon = MSG_ReadDelta( msg, from->weapon, 8);
     to->tier = MSG_ReadDelta( msg, from->tier, 8);
     to->weaponSelectionMode = MSG_ReadDelta( msg, from->weaponSelectionMode, 8);
     to->tierSelectionMode = MSG_ReadDelta( msg, from->tierSelectionMode, 8);
 }
References MSG_ReadBits(), and MSG_ReadDelta().
MSG_ReadDeltaUsercmdKey()
void MSG_ReadDeltaUsercmdKey (msg_t * msg, int key, usercmd_t * from, usercmd_t * to)
Definition at line 779 of file msg.c.
{
     if ( MSG_ReadBits( msg, 1 ) ) {
         to->serverTime = from->serverTime + MSG_ReadBits( msg, 8 );
     } else {
         to->serverTime = MSG_ReadBits( msg, 32 );
     }
     if ( MSG_ReadBits( msg, 1 ) ) {
         key ^= to->serverTime;
         to->angles[0] = MSG_ReadDeltaKey( msg, key, from->angles[0], 16);
         to->angles[1] = MSG_ReadDeltaKey( msg, key, from->angles[1], 16);
         to->angles[2] = MSG_ReadDeltaKey( msg, key, from->angles[2], 16);
         to->forwardmove = MSG_ReadDeltaKey( msg, key, from->forwardmove, 8);
         to->rightmove = MSG_ReadDeltaKey( msg, key, from->rightmove, 8);
         to->upmove = MSG_ReadDeltaKey( msg, key, from->upmove, 8);
         to->buttons = MSG_ReadDeltaKey( msg, key, from->buttons, 16);
         to->weapon = MSG_ReadDeltaKey( msg, key, from->weapon, 8);
         to->tier = MSG_ReadDeltaKey( msg, key, from->tier, 8);
         to->weaponSelectionMode = MSG_ReadDeltaKey( msg, key, from->weaponSelectionMode, 8);
         to->tierSelectionMode = MSG_ReadDeltaKey( msg, key, from->tierSelectionMode, 8);
     } else {
         to->angles[0] = from->angles[0];
         to->angles[1] = from->angles[1];
         to->angles[2] = from->angles[2];
         to->forwardmove = from->forwardmove;
         to->rightmove = from->rightmove;
         to->upmove = from->upmove;
         to->buttons = from->buttons;
         to->weapon = from->weapon;
         to->tier = from->tier;
         to->weaponSelectionMode = from->weaponSelectionMode;
         to->tierSelectionMode = from->tierSelectionMode;
     }
 }
References MSG_ReadBits(), and MSG_ReadDeltaKey().
Referenced by SV_UserMove().
MSG_ReadFloat()
float MSG_ReadFloat (msg_t * msg)
Definition at line 432 of file msg.c.
{
     floatint_t dat;
     dat.i = MSG_ReadBits( msg, 32 );
     if ( msg->readcount > msg->cursize ) {
         dat.f = -1;
     }
     return dat.f;
 }
References msg_t::cursize, floatint_t::f, floatint_t::i, MSG_ReadBits(), and msg_t::readcount.
Referenced by MSG_ReadDeltaPlayerstate().
MSG_ReadLong()
int MSG_ReadLong (msg_t * msg)
Definition at line 421 of file msg.c.
{
     int c;
     c = MSG_ReadBits( msg, 32 );
     if ( msg->readcount > msg->cursize ) {
         c = -1;
     }
     return c;
 }
References msg_t::cursize, MSG_ReadBits(), and msg_t::readcount.
Referenced by CL_ConnectionlessPacket(), CL_ParseCommandString(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParseServerMessage(), CL_ParseSnapshot(), Netchan_Process(), SV_ClientCommand(), SV_ConnectionlessPacket(), SV_ExecuteClientMessage(), and SV_PacketEvent().
MSG_ReadShort()
int MSG_ReadShort (msg_t * msg)
Definition at line 410 of file msg.c.
{
     int c;
     c = (short)MSG_ReadBits( msg, 16 );
     if ( msg->readcount > msg->cursize ) {
         c = -1;
     }
     return c;
 }
References msg_t::cursize, MSG_ReadBits(), and msg_t::readcount.
Referenced by CL_ParseDownload(), CL_ParseGamestate(), MSG_ReadAngle16(), MSG_ReadDeltaPlayerstate(), Netchan_Process(), and SV_PacketEvent().
MSG_ReadString()
char* MSG_ReadString (msg_t * msg)
Definition at line 443 of file msg.c.
{
     static char string[MAX_STRING_CHARS];
     int     l,c;
     l = 0;
     do {
         c = MSG_ReadByte(msg);      // use ReadByte so -1 is out of bounds
         if ( c == -1 || c == 0 ) {
             break;
         }
         // translate all fmt spec to avoid crash bugs
         if ( c == '%' ) {
             c = '.';
         }
         // don't allow higher ascii values
         if ( c > 127 ) {
             c = '.';
         }
         string[l] = c;
         l++;
     } while (l < sizeof(string)-1);
     string[l] = 0;
     return string;
 }
References MAX_STRING_CHARS, and MSG_ReadByte().
Referenced by CL_ConnectionlessPacket(), CL_ParseCommandString(), CL_ParseDownload(), CL_ServerInfoPacket(), and SV_ClientCommand().
MSG_ReadStringLine()
char* MSG_ReadStringLine (msg_t * msg)
Definition at line 499 of file msg.c.
{
     static char string[MAX_STRING_CHARS];
     int     l,c;
     l = 0;
     do {
         c = MSG_ReadByte(msg);      // use ReadByte so -1 is out of bounds
         if (c == -1 || c == 0 || c == '\n') {
             break;
         }
         // translate all fmt spec to avoid crash bugs
         if ( c == '%' ) {
             c = '.';
         }
         // don't allow higher ascii values
         if ( c > 127 ) {
             c = '.';
         }
         string[l] = c;
         l++;
     } while (l < sizeof(string)-1);
     string[l] = 0;
     return string;
 }
References MAX_STRING_CHARS, and MSG_ReadByte().
Referenced by CL_ConnectionlessPacket(), CL_ServerStatusResponse(), and SV_ConnectionlessPacket().
MSG_ReportChangeVectors_f()
void MSG_ReportChangeVectors_f (void)
Definition at line 828 of file msg.c.
{
     int i;
     for(i=0;i<256;i++) {
         if (pcount[i]) {
             Com_Printf("%d used %d\n", i, pcount[i]);
         }
     }
 }
References Com_Printf(), and pcount.
Referenced by Com_Init().
MSG_WriteAngle()
void MSG_WriteAngle (msg_t * sb, float f)
Definition at line 362 of file msg.c.
{
     MSG_WriteByte (sb, (int)(f*256/360) & 255);
 }
References MSG_WriteByte().
MSG_WriteAngle16()
void MSG_WriteAngle16 (msg_t * sb, float f)
Definition at line 366 of file msg.c.
{
     MSG_WriteShort (sb, ANGLE2SHORT(f));
 }
References ANGLE2SHORT, and MSG_WriteShort().
MSG_WriteBigString()
void MSG_WriteBigString (msg_t * sb, const char * s)
Definition at line 336 of file msg.c.
{
     if ( !s ) {
         MSG_WriteData (sb, "", 1);
     } else {
         int     l,i;
         char    string[BIG_INFO_STRING];
         l = strlen( s );
         if ( l >= BIG_INFO_STRING ) {
             Com_Printf( "MSG_WriteString: BIG_INFO_STRING" );
             MSG_WriteData (sb, "", 1);
             return;
         }
         Q_strncpyz( string, s, sizeof( string ) );
         // get rid of 0x80+ and '%' chars, because old clients don't like them
         for ( i = 0 ; i < l ; i++ ) {
             if ( ((byte *)string)[i] > 127 || string[i] == '%' ) {
                 string[i] = '.';
             }
         }
         MSG_WriteData (sb, string, l+1);
     }
 }
References BIG_INFO_STRING, Com_Printf(), MSG_WriteData(), and Q_strncpyz().
Referenced by CL_Record_f(), and SV_SendClientGameState().
MSG_WriteBits()
void MSG_WriteBits (msg_t * msg, int value, int bits)
Definition at line 107 of file msg.c.
{
     int i;
 //  FILE*   fp;
     oldsize += bits;
     // this isn't an exact overflow check, but close enough
     if ( msg->maxsize - msg->cursize < 4 ) {
         msg->overflowed = qtrue;
         return;
     }
     if ( bits == 0 || bits < -31 || bits > 32 ) {
         Com_Error( ERR_DROP, "MSG_WriteBits: bad bits %i", bits );
     }
     // check for overflows
     if ( bits != 32 ) {
         if ( bits > 0 ) {
             if ( value > ( ( 1 << bits ) - 1 ) || value < 0 ) {
                 overflows++;
             }
         } else {
             int r;
             r = 1 << (bits-1);
             if ( value >  r - 1 || value < -r ) {
                 overflows++;
             }
         }
     }
     if ( bits < 0 ) {
         bits = -bits;
     }
     if (msg->oob) {
         if(bits==8)
         {
             msg->data[msg->cursize] = value;
             msg->cursize += 1;
             msg->bit += 8;
         }
         else if(bits==16)
         {
             short temp = value;
             CopyLittleShort(&msg->data[msg->cursize], &temp);
             msg->cursize += 2;
             msg->bit += 16;
         }
         else if(bits==32)
         {
             CopyLittleLong(&msg->data[msg->cursize], &value);
             msg->cursize += 4;
             msg->bit += 32;
         }
         else
             Com_Error(ERR_DROP, "can't write %d bits", bits);
     } else {
 //      fp = fopen("c:\\netchan.bin", "a");
         value &= (0xffffffff>>(32-bits));
         if (bits&7) {
             int nbits;
             nbits = bits&7;
             for(i=0;i<nbits;i++) {
                 Huff_putBit((value&1), msg->data, &msg->bit);
                 value = (value>>1);
             }
             bits = bits - nbits;
         }
         if (bits) {
             for(i=0;i<bits;i+=8) {
 //              fwrite(bp, 1, 1, fp);
                 Huff_offsetTransmit (&msgHuff.compressor, (value&0xff), msg->data, &msg->bit);
                 value = (value>>8);
             }
         }
         msg->cursize = (msg->bit>>3)+1;
 //      fclose(fp);
     }
 }
References msg_t::bit, bits(), Com_Error(), huffman_t::compressor, msg_t::cursize, msg_t::data, ERR_DROP, Huff_offsetTransmit(), Huff_putBit(), msg_t::maxsize, msgHuff, oldsize, msg_t::oob, msg_t::overflowed, overflows, and qtrue.
Referenced by MSG_WriteByte(), MSG_WriteChar(), MSG_WriteDelta(), MSG_WriteDeltaEntity(), MSG_WriteDeltaFloat(), MSG_WriteDeltaKey(), MSG_WriteDeltaKeyFloat(), MSG_WriteDeltaPlayerstate(), MSG_WriteDeltaUsercmd(), MSG_WriteDeltaUsercmdKey(), MSG_WriteFloat(), MSG_WriteLong(), MSG_WriteShort(), and SV_EmitPacketEntities().
MSG_WriteByte()
void MSG_WriteByte (msg_t * sb, int c)
Definition at line 275 of file msg.c.
{
 #ifdef PARANOID
     if (c < 0 || c > 255)
         Com_Error (ERR_FATAL, "MSG_WriteByte: range error");
 #endif
     MSG_WriteBits( sb, c, 8 );
 }
References Com_Error(), ERR_FATAL, and MSG_WriteBits().
Referenced by CL_Netchan_Transmit(), CL_Record_f(), CL_WritePacket(), MSG_WriteAngle(), MSG_WriteData(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), SV_Netchan_Transmit(), SV_SendClientGameState(), SV_SendDownloadMessages(), SV_UpdateServerCommandsToClient(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
MSG_WriteChar()
void MSG_WriteChar (msg_t * sb, int c)
Definition at line 266 of file msg.c.
{
 #ifdef PARANOID
     if (c < -128 || c > 127)
         Com_Error (ERR_FATAL, "MSG_WriteChar: range error");
 #endif
     MSG_WriteBits( sb, c, 8 );
 }
References Com_Error(), ERR_FATAL, and MSG_WriteBits().
MSG_WriteData()
void MSG_WriteData (msg_t * buf, const void * data, int length)
Definition at line 284 of file msg.c.
{
     int i;
     for(i=0;i<length;i++) {
         MSG_WriteByte(buf, ((byte *)data)[i]);
     }
 }
References MSG_WriteByte().
Referenced by CL_WritePacket(), MSG_WriteBigString(), MSG_WriteString(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
MSG_WriteDelta()
void MSG_WriteDelta (msg_t * msg, int oldV, int newV, int bits)
Definition at line 567 of file msg.c.
{
     if ( oldV == newV ) {
         MSG_WriteBits( msg, 0, 1 );
         return;
     }
     MSG_WriteBits( msg, 1, 1 );
     MSG_WriteBits( msg, newV, bits );
 }
References bits(), and MSG_WriteBits().
Referenced by MSG_WriteDeltaUsercmd().
MSG_WriteDeltaEntity()
void MSG_WriteDeltaEntity (msg_t * msg, struct entityState_s * from, struct entityState_s * to, qboolean force)
Definition at line 938 of file msg.c.
{
     int         i, lc;
     int         numFields;
     netField_t  *field;
     int         trunc;
     float       fullFloat;
     int         *fromF, *toF;
     numFields = ARRAY_LEN( entityStateFields );
     // all fields should be 32 bits to avoid any compiler packing issues
     // the "number" field is not part of the field list
     // if this assert fails, someone added a field to the entityState_t
     // struct without updating the message fields
     assert( numFields + 1 == sizeof( *from )/4 );
     // a NULL to is a delta remove message
     if ( to == NULL ) {
         if ( from == NULL ) {
             return;
         }
         MSG_WriteBits( msg, from->number, GENTITYNUM_BITS );
         MSG_WriteBits( msg, 1, 1 );
         return;
     }
     if ( to->number < 0 || to->number >= MAX_GENTITIES ) {
         Com_Error (ERR_FATAL, "MSG_WriteDeltaEntity: Bad entity number: %i", to->number );
     }
     lc = 0;
     // build the change vector as bytes so it is endien independent
     for ( i = 0, field = entityStateFields ; i < numFields ; i++, field++ ) {
         fromF = (int *)( (byte *)from + field->offset );
         toF = (int *)( (byte *)to + field->offset );
         if ( *fromF != *toF ) {
             lc = i+1;
         }
     }
     if ( lc == 0 ) {
         // nothing at all changed
         if ( !force ) {
             return;     // nothing at all
         }
         // write two bits for no change
         MSG_WriteBits( msg, to->number, GENTITYNUM_BITS );
         MSG_WriteBits( msg, 0, 1 );     // not removed
         MSG_WriteBits( msg, 0, 1 );     // no delta
         return;
     }
     MSG_WriteBits( msg, to->number, GENTITYNUM_BITS );
     MSG_WriteBits( msg, 0, 1 );         // not removed
     MSG_WriteBits( msg, 1, 1 );         // we have a delta
     MSG_WriteByte( msg, lc );   // # of changes
     oldsize += numFields;
     for ( i = 0, field = entityStateFields ; i < lc ; i++, field++ ) {
         fromF = (int *)( (byte *)from + field->offset );
         toF = (int *)( (byte *)to + field->offset );
         if ( *fromF == *toF ) {
             MSG_WriteBits( msg, 0, 1 ); // no change
             continue;
         }
         MSG_WriteBits( msg, 1, 1 ); // changed
         if ( field->bits == 0 ) {
             // float
             fullFloat = *(float *)toF;
             trunc = (int)fullFloat;
             if (fullFloat == 0.0f) {
                     MSG_WriteBits( msg, 0, 1 );
                     oldsize += FLOAT_INT_BITS;
             } else {
                 MSG_WriteBits( msg, 1, 1 );
                 if ( trunc == fullFloat && trunc + FLOAT_INT_BIAS >= 0 &&
                     trunc + FLOAT_INT_BIAS < ( 1 << FLOAT_INT_BITS ) ) {
                     // send as small integer
                     MSG_WriteBits( msg, 0, 1 );
                     MSG_WriteBits( msg, trunc + FLOAT_INT_BIAS, FLOAT_INT_BITS );
                 } else {
                     // send as full floating point value
                     MSG_WriteBits( msg, 1, 1 );
                     MSG_WriteBits( msg, *toF, 32 );
                 }
             }
         } else {
             if (*toF == 0) {
                 MSG_WriteBits( msg, 0, 1 );
             } else {
                 MSG_WriteBits( msg, 1, 1 );
                 // integer
                 MSG_WriteBits( msg, *toF, field->bits );
             }
         }
     }
 }
References ARRAY_LEN, Com_Error(), entityStateFields, ERR_FATAL, field(), FLOAT_INT_BIAS, FLOAT_INT_BITS, GENTITYNUM_BITS, int(), MAX_GENTITIES, MSG_WriteBits(), MSG_WriteByte(), NULL, entityState_s::number, Field::offset, and oldsize.
Referenced by CL_Record_f(), SV_EmitPacketEntities(), and SV_SendClientGameState().
MSG_WriteDeltaFloat()
void MSG_WriteDeltaFloat (msg_t * msg, float oldV, float newV)
Definition at line 583 of file msg.c.
{
     floatint_t fi;
     if ( oldV == newV ) {
         MSG_WriteBits( msg, 0, 1 );
         return;
     }
     fi.f = newV;
     MSG_WriteBits( msg, 1, 1 );
     MSG_WriteBits( msg, fi.i, 32 );
 }
References floatint_t::f, floatint_t::i, and MSG_WriteBits().
MSG_WriteDeltaKey()
void MSG_WriteDeltaKey (msg_t * msg, int key, int oldV, int newV, int bits)
Definition at line 623 of file msg.c.
{
     if ( oldV == newV ) {
         MSG_WriteBits( msg, 0, 1 );
         return;
     }
     MSG_WriteBits( msg, 1, 1 );
     MSG_WriteBits( msg, newV ^ key, bits );
 }
References bits(), and MSG_WriteBits().
Referenced by MSG_WriteDeltaUsercmdKey().
MSG_WriteDeltaKeyFloat()
void MSG_WriteDeltaKeyFloat (msg_t * msg, int key, float oldV, float newV)
Definition at line 639 of file msg.c.
{
     floatint_t fi;
     if ( oldV == newV ) {
         MSG_WriteBits( msg, 0, 1 );
         return;
     }
     fi.f = newV;
     MSG_WriteBits( msg, 1, 1 );
     MSG_WriteBits( msg, fi.i ^ key, 32 );
 }
References floatint_t::f, floatint_t::i, and MSG_WriteBits().
MSG_WriteDeltaPlayerstate()
void MSG_WriteDeltaPlayerstate (msg_t * msg, struct playerState_s * from, struct playerState_s * to)
Definition at line 1261 of file msg.c.
{
     int             i;
     playerState_t   dummy;
     int             statsbits;
     int             persistantbits;
     int             skillbits;
     int             powerupbits;
     int             timerbits;
     int             cooldownbits;
     int             sequencebits;
     int             measurebits;
     int             powerlevelbits;
     int             basestatsbits;
     int             bufferbits;
     int             lockedbits;
     int             numFields;
     netField_t      *field;
     int             *fromF, *toF;
     float           fullFloat;
     int             trunc, lc;
     if (!from) {
         from = &dummy;
         Com_Memset (&dummy, 0, sizeof(dummy));
     }
     numFields = ARRAY_LEN( playerStateFields );
     lc = 0;
     for ( i = 0, field = playerStateFields ; i < numFields ; i++, field++ ) {
         fromF = (int *)( (byte *)from + field->offset );
         toF = (int *)( (byte *)to + field->offset );
         if ( *fromF != *toF ) {
             lc = i+1;
         }
     }
     MSG_WriteByte( msg, lc );   // # of changes
     oldsize += numFields - lc;
     for ( i = 0, field = playerStateFields ; i < lc ; i++, field++ ) {
         fromF = (int *)( (byte *)from + field->offset );
         toF = (int *)( (byte *)to + field->offset );
         if ( *fromF == *toF ) {
             MSG_WriteBits( msg, 0, 1 ); // no change
             continue;
         }
         MSG_WriteBits( msg, 1, 1 ); // changed
 //      pcount[i]++;
         if ( field->bits == 0 ) {
             // float
             fullFloat = *(float *)toF;
             trunc = (int)fullFloat;
             if ( trunc == fullFloat && trunc + FLOAT_INT_BIAS >= 0 &&
                 trunc + FLOAT_INT_BIAS < ( 1 << FLOAT_INT_BITS ) ) {
                 // send as small integer
                 MSG_WriteBits( msg, 0, 1 );
                 MSG_WriteBits( msg, trunc + FLOAT_INT_BIAS, FLOAT_INT_BITS );
             } else {
                 // send as full floating point value
                 MSG_WriteBits( msg, 1, 1 );
                 MSG_WriteBits( msg, *toF, 32 );
             }
         } else {
             // integer
             MSG_WriteBits( msg, *toF, field->bits );
         }
     }
     //
     // send the arrays
     //
     statsbits = 0;
     for (i=0 ; i<MAX_STATS ; i++) {
         if (to->stats[i] != from->stats[i]) {
             statsbits |= 1<<i;
         }
     }
     lockedbits = 0;
     for (i=0 ; i<MAX_LOCKED_STATS ; i++) {
         if (to->lockonData[i] != from->lockonData[i]) {
             lockedbits |= 1<<i;
         }
     }
     persistantbits = 0;
     for (i=0 ; i<MAX_PERSISTANT ; i++) {
         if (to->persistant[i] != from->persistant[i]) {
             persistantbits |= 1<<i;
         }
     }
     skillbits = 0;
     for (i=0 ; i<MAX_WEAPONS ; i++) {
         if (to->currentSkill[i] != from->currentSkill[i]) {
             skillbits |= 1<<i;
         }
     }
     powerupbits = 0;
     for (i=0 ; i<MAX_POWERUPS ; i++) {
         if (to->powerups[i] != from->powerups[i]) {
             powerupbits |= 1<<i;
         }
     }
     timerbits = 0;
     for (i=0 ; i<MAX_TIMERS ; i++) {
         if (to->timers[i] != from->timers[i]) {
             timerbits |= 1<<i;
         }
     }
     cooldownbits = 0;
     for (i=0 ; i<MAX_COOLDOWN ; i++) {
         if (to->cooldownTimers[i] != from->cooldownTimers[i]) {
             cooldownbits |= 1<<i;
         }
     }
     sequencebits = 0;
     for (i=0 ; i<MAX_SEQUENCE ; i++) {
         if (to->sequenceTimers[i] != from->sequenceTimers[i]) {
             sequencebits |= 1<<i;
         }
     }
     measurebits = 0;
     for (i=0 ; i<MAX_MEASURES ; i++) {
         if (to->measureTimers[i] != from->measureTimers[i]) {
             measurebits |= 1<<i;
         }
     }
     powerlevelbits = 0;
     for (i=0 ; i<MAX_POWERSTATS ; i++) {
         if (to->powerLevel[i] != from->powerLevel[i]) {
             powerlevelbits |= 1<<i;
         }
     }
     basestatsbits = 0;
     for (i=0 ; i<MAX_BASESTATS ; i++) {
         if (to->baseStats[i] != from->baseStats[i]) {
             basestatsbits |= 1<<i;
         }
     }
     bufferbits = 0;
     for (i=0 ; i<MAX_RBUFFERS ; i++) {
         if (to->buffers[i] != from->buffers[i]) {
             bufferbits |= 1<<i;
         }
     }
     if (!statsbits && !persistantbits && !skillbits && !lockedbits && !powerupbits && !timerbits && !powerlevelbits && !basestatsbits && !cooldownbits && !sequencebits && !measurebits && !bufferbits) {
         MSG_WriteBits( msg, 0, 1 ); // no change
         oldsize += 8;
         return;
     }
     MSG_WriteBits( msg, 1, 1 ); // changed
     if ( statsbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, statsbits, MAX_STATS );
         for (i=0 ; i<MAX_STATS ; i++)
             if (statsbits & (1<<i) )
                 MSG_WriteShort (msg, to->stats[i]);
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( lockedbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, lockedbits, MAX_LOCKED_STATS );
         for (i=0 ; i<MAX_LOCKED_STATS ; i++)
             if (lockedbits & (1<<i) )
                 MSG_WriteShort (msg, to->lockonData[i]);
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( persistantbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, persistantbits, MAX_PERSISTANT );
         for (i=0 ; i<MAX_PERSISTANT ; i++)
             if (persistantbits & (1<<i) )
                 MSG_WriteShort (msg, to->persistant[i]);
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( skillbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, skillbits, MAX_WEAPONS );
         for (i=0 ; i<MAX_WEAPONS ; i++)
             if (skillbits & (1<<i) )
                 MSG_WriteShort (msg, to->currentSkill[i]);
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( powerupbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, powerupbits, MAX_POWERUPS );
         for (i=0 ; i<MAX_POWERUPS ; i++)
             if (powerupbits & (1<<i) )
                 MSG_WriteShort( msg, to->powerups[i] );
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( timerbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, timerbits, MAX_TIMERS );
         for (i=0 ; i<MAX_TIMERS ; i++)
             if (timerbits & (1<<i) )
                 MSG_WriteShort( msg, to->timers[i] );
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( cooldownbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, cooldownbits, MAX_COOLDOWN );
         for (i=0 ; i<MAX_COOLDOWN ; i++)
             if (cooldownbits & (1<<i) )
                 MSG_WriteShort( msg, to->cooldownTimers[i] );
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( sequencebits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, sequencebits, MAX_SEQUENCE );
         for (i=0 ; i<MAX_SEQUENCE ; i++)
             if (sequencebits & (1<<i) )
                 MSG_WriteShort( msg, to->sequenceTimers[i] );
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( measurebits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, measurebits, MAX_MEASURES );
         for (i=0 ; i<MAX_MEASURES ; i++)
             if (measurebits & (1<<i) )
                 MSG_WriteShort( msg, to->measureTimers[i] );
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( powerlevelbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, powerlevelbits, MAX_POWERSTATS );
         for (i=0 ; i<MAX_POWERSTATS ; i++)
             if (powerlevelbits & (1<<i) )
                 MSG_WriteShort( msg, to->powerLevel[i] );
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( basestatsbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, basestatsbits, MAX_BASESTATS );
         for (i=0 ; i<MAX_BASESTATS ; i++)
             if (basestatsbits & (1<<i) )
                 MSG_WriteFloat( msg, to->baseStats[i] );
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
     if ( bufferbits ) {
         MSG_WriteBits( msg, 1, 1 ); // changed
         MSG_WriteBits( msg, bufferbits, MAX_RBUFFERS );
         for (i=0 ; i<MAX_RBUFFERS ; i++)
             if (bufferbits & (1<<i) )
                 MSG_WriteFloat( msg, to->buffers[i] );
     } else {
         MSG_WriteBits( msg, 0, 1 ); // no change
     }
 }
References ARRAY_LEN, playerState::baseStats, playerState::buffers, Com_Memset, playerState::cooldownTimers, playerState::currentSkill, field(), FLOAT_INT_BIAS, FLOAT_INT_BITS, int(), playerState::lockonData, MAX_BASESTATS, MAX_COOLDOWN, MAX_LOCKED_STATS, MAX_MEASURES, MAX_PERSISTANT, MAX_POWERSTATS, MAX_POWERUPS, MAX_RBUFFERS, MAX_SEQUENCE, MAX_STATS, MAX_TIMERS, MAX_WEAPONS, playerState::measureTimers, MSG_WriteBits(), MSG_WriteByte(), MSG_WriteFloat(), MSG_WriteShort(), Field::offset, oldsize, playerState::persistant, playerStateFields, playerState::powerLevel, playerState::powerups, playerState::sequenceTimers, playerState::stats, and playerState::timers.
Referenced by SV_WriteSnapshotToClient().
MSG_WriteDeltaUsercmd()
void MSG_WriteDeltaUsercmd (msg_t * msg, usercmd_t * from, usercmd_t * to)
Definition at line 684 of file msg.c.
{
     if ( to->serverTime - from->serverTime < 256 ) {
         MSG_WriteBits( msg, 1, 1 );
         MSG_WriteBits( msg, to->serverTime - from->serverTime, 8 );
     } else {
         MSG_WriteBits( msg, 0, 1 );
         MSG_WriteBits( msg, to->serverTime, 32 );
     }
     MSG_WriteDelta( msg, from->angles[0], to->angles[0], 16 );
     MSG_WriteDelta( msg, from->angles[1], to->angles[1], 16 );
     MSG_WriteDelta( msg, from->angles[2], to->angles[2], 16 );
     MSG_WriteDelta( msg, from->forwardmove, to->forwardmove, 8 );
     MSG_WriteDelta( msg, from->rightmove, to->rightmove, 8 );
     MSG_WriteDelta( msg, from->upmove, to->upmove, 8 );
     MSG_WriteDelta( msg, from->buttons, to->buttons, 16 );
     MSG_WriteDelta( msg, from->weapon, to->weapon, 8 );
     MSG_WriteDelta( msg, from->tier, to->tier, 8 );
     MSG_WriteDelta( msg, from->weaponSelectionMode, to->weaponSelectionMode, 8 );
     MSG_WriteDelta( msg, from->tierSelectionMode, to->tierSelectionMode, 8 );
 }
References MSG_WriteBits(), and MSG_WriteDelta().
MSG_WriteDeltaUsercmdKey()
void MSG_WriteDeltaUsercmdKey (msg_t * msg, int key, usercmd_t * from, usercmd_t * to)
Definition at line 735 of file msg.c.
{
     if ( to->serverTime - from->serverTime < 256 ) {
         MSG_WriteBits( msg, 1, 1 );
         MSG_WriteBits( msg, to->serverTime - from->serverTime, 8 );
     } else {
         MSG_WriteBits( msg, 0, 1 );
         MSG_WriteBits( msg, to->serverTime, 32 );
     }
     if (from->angles[0] == to->angles[0] &&
         from->angles[1] == to->angles[1] &&
         from->angles[2] == to->angles[2] &&
         from->forwardmove == to->forwardmove &&
         from->rightmove == to->rightmove &&
         from->upmove == to->upmove &&
         from->buttons == to->buttons &&
         from->weapon == to->weapon &&
         from->tier == to->tier &&
         from->weaponSelectionMode == to->weaponSelectionMode &&
         from->tierSelectionMode == to->tierSelectionMode) {
             MSG_WriteBits( msg, 0, 1 );             // no change
             oldsize += 7;
             return;
     }
     key ^= to->serverTime;
     MSG_WriteBits( msg, 1, 1 );
     MSG_WriteDeltaKey( msg, key, from->angles[0], to->angles[0], 16 );
     MSG_WriteDeltaKey( msg, key, from->angles[1], to->angles[1], 16 );
     MSG_WriteDeltaKey( msg, key, from->angles[2], to->angles[2], 16 );
     MSG_WriteDeltaKey( msg, key, from->forwardmove, to->forwardmove, 8 );
     MSG_WriteDeltaKey( msg, key, from->rightmove, to->rightmove, 8 );
     MSG_WriteDeltaKey( msg, key, from->upmove, to->upmove, 8 );
     MSG_WriteDeltaKey( msg, key, from->buttons, to->buttons, 16 );
     MSG_WriteDeltaKey( msg, key, from->weapon, to->weapon, 8 );
     MSG_WriteDeltaKey( msg, key, from->tier, to->tier, 8 );
     MSG_WriteDeltaKey( msg, key, from->weaponSelectionMode, to->weaponSelectionMode, 8 );
     MSG_WriteDeltaKey( msg, key, from->tierSelectionMode, to->tierSelectionMode, 8 );
 }
References MSG_WriteBits(), MSG_WriteDeltaKey(), and oldsize.
Referenced by CL_WritePacket().
MSG_WriteFloat()
void MSG_WriteFloat (msg_t * sb, float f)
Definition at line 304 of file msg.c.
{
     floatint_t dat;
     dat.f = f;
     MSG_WriteBits( sb, dat.i, 32 );
 }
References floatint_t::f, floatint_t::i, and MSG_WriteBits().
Referenced by MSG_WriteDeltaPlayerstate().
MSG_WriteLong()
void MSG_WriteLong (msg_t * sb, int c)
Definition at line 300 of file msg.c.
{
     MSG_WriteBits( sb, c, 32 );
 }
References MSG_WriteBits().
Referenced by CL_Record_f(), CL_WritePacket(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_SendClientGameState(), SV_SendClientSnapshot(), SV_SendDownloadMessages(), SV_UpdateServerCommandsToClient(), SV_WriteDownloadToClient(), and SV_WriteSnapshotToClient().
MSG_WriteShort()
void MSG_WriteShort (msg_t * sb, int c)
Definition at line 291 of file msg.c.
{
 #ifdef PARANOID
     if (c < ((short)0x8000) || c > (short)0x7fff)
         Com_Error (ERR_FATAL, "MSG_WriteShort: range error");
 #endif
     MSG_WriteBits( sb, c, 16 );
 }
References Com_Error(), ERR_FATAL, and MSG_WriteBits().
Referenced by CL_Record_f(), CL_WritePacket(), MSG_WriteAngle16(), MSG_WriteDeltaPlayerstate(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_SendClientGameState(), and SV_WriteDownloadToClient().
MSG_WriteString()
void MSG_WriteString (msg_t * sb, const char * s)
Definition at line 310 of file msg.c.
{
     if ( !s ) {
         MSG_WriteData (sb, "", 1);
     } else {
         int     l,i;
         char    string[MAX_STRING_CHARS];
         l = strlen( s );
         if ( l >= MAX_STRING_CHARS ) {
             Com_Printf( "MSG_WriteString: MAX_STRING_CHARS" );
             MSG_WriteData (sb, "", 1);
             return;
         }
         Q_strncpyz( string, s, sizeof( string ) );
         // get rid of 0x80+ and '%' chars, because old clients don't like them
         for ( i = 0 ; i < l ; i++ ) {
             if ( ((byte *)string)[i] > 127 || string[i] == '%' ) {
                 string[i] = '.';
             }
         }
         MSG_WriteData (sb, string, l+1);
     }
 }
References Com_Printf(), MAX_STRING_CHARS, MSG_WriteData(), and Q_strncpyz().
Referenced by CL_WritePacket(), SV_UpdateServerCommandsToClient(), and SV_WriteDownloadToClient().
Variable Documentation
cl_shownet
cvar_t* cl_shownet
Definition at line 72 of file cl_main.c.
Referenced by CL_Init(), CL_ParsePacketEntities(), CL_ParseServerMessage(), CL_ParseSnapshot(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), and SHOWNET().
entityStateFields
netField_t entityStateFields[]
Definition at line 846 of file msg.c.
Referenced by MSG_ReadDeltaEntity(), and MSG_WriteDeltaEntity().
kbitmask
int kbitmask[32]
Initial value:
= {
    0x00000001, 0x00000003, 0x00000007, 0x0000000F,
    0x0000001F, 0x0000003F, 0x0000007F, 0x000000FF,
    0x000001FF, 0x000003FF, 0x000007FF, 0x00000FFF,
    0x00001FFF, 0x00003FFF, 0x00007FFF, 0x0000FFFF,
    0x0001FFFF, 0x0003FFFF, 0x0007FFFF, 0x000FFFFF,
    0x001FFFFf, 0x003FFFFF, 0x007FFFFF, 0x00FFFFFF,
    0x01FFFFFF, 0x03FFFFFF, 0x07FFFFFF, 0x0FFFFFFF,
    0x1FFFFFFF, 0x3FFFFFFF, 0x7FFFFFFF, 0xFFFFFFFF,
}
Definition at line 612 of file msg.c.
Referenced by MSG_ReadDeltaKey().
msg_hData
int msg_hData[256]
Definition at line 1770 of file msg.c.
Referenced by MSG_initHuffman().
msgHuff
huffman_t msgHuff static
Definition at line 25 of file msg.c.
Referenced by MSG_initHuffman(), MSG_ReadBits(), and MSG_WriteBits().
msgInit
qboolean msgInit = qfalse static
Definition at line 27 of file msg.c.
Referenced by MSG_Init(), MSG_initHuffman(), and MSG_InitOOB().
oldsize
int oldsize = 0
Definition at line 40 of file msg.c.
Referenced by MSG_WriteBits(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), and MSG_WriteDeltaUsercmdKey().
overflows
int overflows
Definition at line 104 of file msg.c.
Referenced by MSG_WriteBits().
pcount
int pcount[256]
Definition at line 29 of file msg.c.
Referenced by MSG_ReportChangeVectors_f().
playerStateFields
netField_t playerStateFields[]
Definition at line 1183 of file msg.c.
Referenced by MSG_ReadDeltaPlayerstate(), and MSG_WriteDeltaPlayerstate().