ZEQ2-Lite: Source/Game/UI/ui_local.h File Reference
ui_local.h File Reference
#include "../../Shared/q_shared.h"
#include "../../Engine/renderer/tr_types.h"
#include "ui_public.h"
#include "../../Engine/client/keycodes.h"
#include "../Game/bg_public.h"
Data Structures
struct _tag_menuframework
struct lerpFrame_t
struct menuaction_s
struct menubitmap_s
struct menucommon_s
struct menufield_s
struct menulist_s
struct menuradiobutton_s
struct menuslider_s
struct menutext_s
struct mfield_t
struct playerInfo_t
struct uiStatic_t
Macros
#define LCOLUMN_OFFSET (-BIGCHAR_WIDTH)
#define MAX_EDIT_LINE 256
#define MAX_FAVORITESERVERS 16
#define MAX_MENUDEPTH 8
#define MAX_MENUITEMS 96
#define MTYPE_ACTION 2
#define MTYPE_BITMAP 6
#define MTYPE_BTEXT 10
#define MTYPE_FIELD 4
#define MTYPE_NULL 0
#define MTYPE_PTEXT 9
#define MTYPE_RADIOBUTTON 5
#define MTYPE_SCROLLLIST 8
#define MTYPE_SLIDER 1
#define MTYPE_SPINCONTROL 3
#define MTYPE_TEXT 7
#define PLAYER_MODEL_SPEED 1.25
#define QM_ACTIVATED 3
#define QM_GOTFOCUS 1
#define QM_LOSTFOCUS 2
#define QMF_BLINK ((unsigned int) 0x00000001)
#define QMF_CENTER_JUSTIFY ((unsigned int) 0x00000008)
#define QMF_GRAYED ((unsigned int) 0x00002000)
#define QMF_HASMOUSEFOCUS ((unsigned int) 0x00000200)
#define QMF_HIDDEN ((unsigned int) 0x00001000)
#define QMF_HIGHLIGHT ((unsigned int) 0x00000040)
#define QMF_HIGHLIGHT_IF_FOCUS ((unsigned int) 0x00000080)
#define QMF_INACTIVE ((unsigned int) 0x00004000)
#define QMF_LEFT_JUSTIFY ((unsigned int) 0x00000004)
#define QMF_LOWERCASE ((unsigned int) 0x00040000)
#define QMF_MOUSEONLY ((unsigned int) 0x00000800)
#define QMF_NODEFAULTINIT ((unsigned int) 0x00008000)
#define QMF_NOONOFFTEXT ((unsigned int) 0x00000400)
#define QMF_NUMBERSONLY ((unsigned int) 0x00000020)
#define QMF_OWNERDRAW ((unsigned int) 0x00010000)
#define QMF_PULSE ((unsigned int) 0x00020000)
#define QMF_PULSEIFFOCUS ((unsigned int) 0x00000100)
#define QMF_RIGHT_JUSTIFY ((unsigned int) 0x00000010)
#define QMF_SILENT ((unsigned int) 0x00100000)
#define QMF_SMALLFONT ((unsigned int) 0x00000002)
#define QMF_TINYFONT ((unsigned int) 0x00200000)
#define QMF_UPPERCASE ((unsigned int) 0x00080000)
#define RCOLUMN_OFFSET (BIGCHAR_WIDTH)
#define SLIDER_RANGE 10
#define UI_API_VERSION 4
Typedefs
typedef void(* voidfunc_f) (void)
Enumerations
enum awardType_t {
AWARD_ACCURACY, AWARD_IMPRESSIVE, AWARD_EXCELLENT, AWARD_GAUNTLET,
AWARD_FRAGS, AWARD_PERFECT
}
Functions
void ArenaServers_Cache (void)
void Bitmap_Draw (menubitmap_s *b)
void Bitmap_Init (menubitmap_s *b)
void Camera_Cache (void)
void ConfirmMenu_Cache (void)
void Controls_Cache (void)
void InGame_Cache (void)
void MainMenu_Cache (void)
sfxHandle_t Menu_ActivateItem (menuframework_s *s, menucommon_s *item)
void Menu_AddItem (menuframework_s *menu, void *item)
void Menu_AdjustCursor (menuframework_s *menu, int dir)
void Menu_Cache (void)
void Menu_Common (int amount)
sfxHandle_t Menu_DefaultKey (menuframework_s *s, int key)
void Menu_Draw (menuframework_s *menu)
void Menu_Focus (menucommon_s *m)
void Menu_Frame (void)
void * Menu_ItemAtCursor (menuframework_s *m)
void Menu_SetCursor (menuframework_s *s, int cursor)
void Menu_SetCursorToItem (menuframework_s *m, void *ptr)
void Menu_Side (void)
void MenuField_Draw (menufield_s *f)
void MenuField_Init (menufield_s *m)
sfxHandle_t MenuField_Key (menufield_s *m, int *key)
void MField_CharEvent (mfield_t *edit, int ch)
void MField_Clear (mfield_t *edit)
void MField_Draw (mfield_t *edit, int x, int y, int style, vec4_t color)
void MField_KeyDownEvent (mfield_t *edit, int key)
void PlayerModel_Cache (void)
void PlayerSettings_Cache (void)
void Preferences_Cache (void)
void ScrollList_Draw (menulist_s *l)
sfxHandle_t ScrollList_Key (menulist_s *l, int key)
void ServerInfo_Cache (void)
void SpecifyLeague_Cache (void)
void SpecifyServer_Cache (void)
void StartServer_Cache (void)
void SystemSettings_Cache (void)
void TeamMain_Cache (void)
int trap_Argc (void)
void trap_Argv (int n, char *buffer, int bufferLength)
int trap_CM_LerpTag (orientation_t *tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char *tagName)
void trap_Cmd_ExecuteText (int exec_when, const char *text)
void trap_Cvar_Create (const char *var_name, const char *var_value, int flags)
void trap_Cvar_InfoStringBuffer (int bit, char *buffer, int bufsize)
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
void trap_Cvar_Reset (const char *name)
void trap_Cvar_Set (const char *var_name, const char *value)
void trap_Cvar_SetValue (const char *var_name, float value)
void trap_Cvar_Update (vmCvar_t *vmCvar)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
float trap_Cvar_VariableValue (const char *var_name)
void trap_Error (const char *string)
void trap_FS_FCloseFile (fileHandle_t f)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
void trap_GetClientState (uiClientState_t *state)
void trap_GetClipboardData (char *buf, int bufsize)
int trap_GetConfigString (int index, char *buff, int buffsize)
void trap_GetGlconfig (glconfig_t *glconfig)
void trap_Key_ClearStates (void)
void trap_Key_GetBindingBuf (int keynum, char *buf, int buflen)
int trap_Key_GetCatcher (void)
qboolean trap_Key_GetOverstrikeMode (void)
qboolean trap_Key_IsDown (int keynum)
void trap_Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
void trap_Key_SetBinding (int keynum, const char *binding)
void trap_Key_SetCatcher (int catcher)
void trap_Key_SetOverstrikeMode (qboolean state)
void trap_LAN_ClearPing (int n)
void trap_LAN_GetPing (int n, char *buf, int buflen, int *pingtime)
void trap_LAN_GetPingInfo (int n, char *buf, int buflen)
int trap_LAN_GetPingQueueCount (void)
void trap_LAN_GetServerAddressString (int source, int n, char *buf, int buflen)
int trap_LAN_GetServerCount (int source)
void trap_LAN_GetServerInfo (int source, int n, char *buf, int buflen)
int trap_LAN_ServerStatus (const char *serverAddress, char *serverStatus, int maxLen)
int trap_MemoryRemaining (void)
int trap_Milliseconds (void)
void trap_Print (const char *string)
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
void trap_R_AddRefEntityToScene (const refEntity_t *re)
void trap_R_ClearScene (void)
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
qhandle_t trap_R_RegisterModel (const char *name)
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
qhandle_t trap_R_RegisterSkin (const char *name)
void trap_R_RenderScene (const refdef_t *fd)
void trap_R_SetColor (const float *rgba)
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
void trap_S_StartBackgroundTrack (const char *intro, const char *loop)
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
void trap_S_StopBackgroundTrack (void)
void trap_UpdateScreen (void)
void UI_AdjustFrom640 (float *x, float *y, float *w, float *h)
void UI_ArenaServersMenu (void)
char * UI_Argv (int arg)
void UI_CameraMenu (void)
float UI_ClampCvar (float min, float max, float value)
void UI_ConfirmMenu (const char *question, void(*draw)(void), void(*action)(qboolean result))
void UI_ConfirmMenu_Style (const char *question, int style, void(*draw)(void), void(*action)(qboolean result))
qboolean UI_ConsoleCommand (int realTime)
void UI_ControlsMenu (void)
void UI_CreditMenu (void)
qboolean UI_CursorInRect (int x, int y, int width, int height)
char * UI_Cvar_VariableString (const char *var_name)
void UI_DrawBackPic (qboolean drawPic)
void UI_DrawBannerString (int x, int y, const char *str, int style, vec4_t color)
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
void UI_DrawConnectScreen (qboolean overlay)
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
void UI_DrawNamedPic (float x, float y, float width, float height, const char *picname)
void UI_DrawPlayer (float x, float y, float w, float h, playerInfo_t *pi, int time)
void UI_DrawProportionalString (int x, int y, const char *str, int style, vec4_t color)
void UI_DrawProportionalString_AutoWrapped (int x, int ystart, int xmax, int ystep, const char *str, int style, vec4_t color)
void UI_DrawRect (float x, float y, float width, float height, const float *color)
void UI_DrawString (int x, int y, const char *str, int style, vec4_t color)
int UI_DrawStrlen (const char *str)
void UI_DrawTextBox (int x, int y, int width, int lines)
void UI_FillRect (float x, float y, float width, float height, const float *color)
void UI_ForceMenuOff (void)
const char * UI_GetArenaInfoByMap (const char *map)
const char * UI_GetArenaInfoByNumber (int num)
int UI_GetNumArenas (void)
const char * UI_GetSpecialArenaInfo (const char *tag)
void UI_InGameMenu (void)
void UI_Init (void)
void UI_InitGameinfo (void)
qboolean UI_IsFullscreen (void)
void UI_KeyEvent (int key, int down)
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
void UI_MainMenu (void)
void UI_MenuLogo (void)
void UI_MenuScene (void)
void UI_Message (const char **lines)
void UI_MouseEvent (int dx, int dy)
void UI_MusicMenu (void)
void UI_MusicMenu_Cache (void)
void UI_PlayerInfo_SetInfo (playerInfo_t *pi, int legsAnim, int torsoAnim, vec3_t viewAngles, vec3_t moveAngles, weapon_t weaponNum, qboolean chat)
void UI_PlayerInfo_SetModel (playerInfo_t *pi, const char *model)
void UI_PlayerModelMenu (void)
void UI_PlayerSettingsMenu (void)
void UI_PopMenu (void)
void UI_PreferencesMenu (void)
float UI_ProportionalSizeScale (int style)
int UI_ProportionalStringWidth (const char *str)
void UI_PushMenu (menuframework_s *menu)
void UI_Refresh (int realtime)
qboolean UI_RegisterClientModelname (playerInfo_t *pi, const char *modelSkinName)
void UI_RegisterCvars (void)
void UI_ServerInfoMenu (void)
void UI_SetActiveMenu (uiMenuCommand_t menu)
void UI_SetColor (const float *rgba)
void UI_SetupMenu (void)
void UI_SetupMenu_Cache (void)
void UI_Shutdown (void)
void UI_SpecifyLeagueMenu (void)
void UI_SpecifyServerMenu (void)
void UI_StartDemoLoop (void)
void UI_StartServerMenu (void)
void UI_SystemSettingsMenu (void)
void UI_TeamMainMenu (void)
void UI_TeamOrdersMenu (void)
void UI_TeamOrdersMenu_Cache (void)
void UI_TeamOrdersMenu_f (void)
void UI_UpdateCvars (void)
void UI_UpdateScreen (void)
Variables
vec4_t color_black
vec4_t color_blue
vec4_t color_dim
vec4_t color_orange
vec4_t color_red
vec4_t color_silver
vec4_t color_white
vec4_t color_yellow
vec4_t list_color
vec4_t listbar_color
qboolean m_entersound
vec4_t menu_black_color
sfxHandle_t menu_buzz_sound
vec4_t menu_dark_color
vec4_t menu_dim_color
sfxHandle_t menu_exit_sound
vec4_t menu_grayed_color
vec4_t menu_highlight_color
sfxHandle_t menu_in_sound
sfxHandle_t menu_move_sound
sfxHandle_t menu_null_sound
sfxHandle_t menu_out_sound
vec4_t menu_red_color
vec4_t menu_text_color
vec4_t name_color
vmCvar_t s_mastermusicvolume
vec4_t text_color_disabled
vec4_t text_color_highlight
vec4_t text_color_normal
vmCvar_t ui_brassTime
vmCvar_t ui_browserGameType
vmCvar_t ui_browserMaster
vmCvar_t ui_browserShowEmpty
vmCvar_t ui_browserShowFull
vmCvar_t ui_browserSortKey
vmCvar_t ui_drawCrosshair
vmCvar_t ui_drawCrosshairNames
vmCvar_t ui_ffa_breakLimitRate
vmCvar_t ui_ffa_fraglimit
vmCvar_t ui_ffa_powerlevel
vmCvar_t ui_ffa_powerlevelMaximum
vmCvar_t ui_ffa_timelimit
vmCvar_t ui_marks
char * ui_medalNames []
char * ui_medalPicNames []
char * ui_medalSounds []
vmCvar_t ui_server1
vmCvar_t ui_server10
vmCvar_t ui_server11
vmCvar_t ui_server12
vmCvar_t ui_server13
vmCvar_t ui_server14
vmCvar_t ui_server15
vmCvar_t ui_server16
vmCvar_t ui_server2
vmCvar_t ui_server3
vmCvar_t ui_server4
vmCvar_t ui_server5
vmCvar_t ui_server6
vmCvar_t ui_server7
vmCvar_t ui_server8
vmCvar_t ui_server9
uiStatic_t uis
Macro Definition Documentation
LCOLUMN_OFFSET
#define LCOLUMN_OFFSET (-BIGCHAR_WIDTH)
Definition at line 82 of file ui_local.h.
MAX_EDIT_LINE
#define MAX_EDIT_LINE 256
Definition at line 85 of file ui_local.h.
MAX_FAVORITESERVERS
#define MAX_FAVORITESERVERS 16
Definition at line 398 of file ui_local.h.
MAX_MENUDEPTH
#define MAX_MENUDEPTH 8
Definition at line 87 of file ui_local.h.
MAX_MENUITEMS
#define MAX_MENUITEMS 96
Definition at line 88 of file ui_local.h.
MTYPE_ACTION
#define MTYPE_ACTION 2
Definition at line 92 of file ui_local.h.
MTYPE_BITMAP
#define MTYPE_BITMAP 6
Definition at line 96 of file ui_local.h.
MTYPE_BTEXT
#define MTYPE_BTEXT 10
Definition at line 100 of file ui_local.h.
MTYPE_FIELD
#define MTYPE_FIELD 4
Definition at line 94 of file ui_local.h.
MTYPE_NULL
#define MTYPE_NULL 0
Definition at line 90 of file ui_local.h.
MTYPE_PTEXT
#define MTYPE_PTEXT 9
Definition at line 99 of file ui_local.h.
MTYPE_RADIOBUTTON
#define MTYPE_RADIOBUTTON 5
Definition at line 95 of file ui_local.h.
MTYPE_SCROLLLIST
#define MTYPE_SCROLLLIST 8
Definition at line 98 of file ui_local.h.
MTYPE_SLIDER
#define MTYPE_SLIDER 1
Definition at line 91 of file ui_local.h.
MTYPE_SPINCONTROL
#define MTYPE_SPINCONTROL 3
Definition at line 93 of file ui_local.h.
MTYPE_TEXT
#define MTYPE_TEXT 7
Definition at line 97 of file ui_local.h.
PLAYER_MODEL_SPEED
#define PLAYER_MODEL_SPEED 1.25
Definition at line 75 of file ui_local.h.
QM_ACTIVATED
#define QM_ACTIVATED 3
Definition at line 128 of file ui_local.h.
QM_GOTFOCUS
#define QM_GOTFOCUS 1
Definition at line 126 of file ui_local.h.
QM_LOSTFOCUS
#define QM_LOSTFOCUS 2
Definition at line 127 of file ui_local.h.
QMF_BLINK
#define QMF_BLINK ((unsigned int) 0x00000001)
Definition at line 102 of file ui_local.h.
QMF_CENTER_JUSTIFY
#define QMF_CENTER_JUSTIFY ((unsigned int) 0x00000008)
Definition at line 105 of file ui_local.h.
QMF_GRAYED
#define QMF_GRAYED ((unsigned int) 0x00002000)
Definition at line 115 of file ui_local.h.
QMF_HASMOUSEFOCUS
#define QMF_HASMOUSEFOCUS ((unsigned int) 0x00000200)
Definition at line 111 of file ui_local.h.
QMF_HIDDEN
#define QMF_HIDDEN ((unsigned int) 0x00001000)
Definition at line 114 of file ui_local.h.
QMF_HIGHLIGHT
#define QMF_HIGHLIGHT ((unsigned int) 0x00000040)
Definition at line 108 of file ui_local.h.
QMF_HIGHLIGHT_IF_FOCUS
#define QMF_HIGHLIGHT_IF_FOCUS ((unsigned int) 0x00000080)
Definition at line 109 of file ui_local.h.
QMF_INACTIVE
#define QMF_INACTIVE ((unsigned int) 0x00004000)
Definition at line 116 of file ui_local.h.
QMF_LEFT_JUSTIFY
#define QMF_LEFT_JUSTIFY ((unsigned int) 0x00000004)
Definition at line 104 of file ui_local.h.
QMF_LOWERCASE
#define QMF_LOWERCASE ((unsigned int) 0x00040000)
Definition at line 120 of file ui_local.h.
QMF_MOUSEONLY
#define QMF_MOUSEONLY ((unsigned int) 0x00000800)
Definition at line 113 of file ui_local.h.
QMF_NODEFAULTINIT
#define QMF_NODEFAULTINIT ((unsigned int) 0x00008000)
Definition at line 117 of file ui_local.h.
QMF_NOONOFFTEXT
#define QMF_NOONOFFTEXT ((unsigned int) 0x00000400)
Definition at line 112 of file ui_local.h.
QMF_NUMBERSONLY
#define QMF_NUMBERSONLY ((unsigned int) 0x00000020)
Definition at line 107 of file ui_local.h.
QMF_OWNERDRAW
#define QMF_OWNERDRAW ((unsigned int) 0x00010000)
Definition at line 118 of file ui_local.h.
QMF_PULSE
#define QMF_PULSE ((unsigned int) 0x00020000)
Definition at line 119 of file ui_local.h.
QMF_PULSEIFFOCUS
#define QMF_PULSEIFFOCUS ((unsigned int) 0x00000100)
Definition at line 110 of file ui_local.h.
QMF_RIGHT_JUSTIFY
#define QMF_RIGHT_JUSTIFY ((unsigned int) 0x00000010)
Definition at line 106 of file ui_local.h.
QMF_SILENT
#define QMF_SILENT ((unsigned int) 0x00100000)
Definition at line 122 of file ui_local.h.
QMF_SMALLFONT
#define QMF_SMALLFONT ((unsigned int) 0x00000002)
Definition at line 103 of file ui_local.h.
QMF_TINYFONT
#define QMF_TINYFONT ((unsigned int) 0x00200000)
Definition at line 123 of file ui_local.h.
QMF_UPPERCASE
#define QMF_UPPERCASE ((unsigned int) 0x00080000)
Definition at line 121 of file ui_local.h.
RCOLUMN_OFFSET
#define RCOLUMN_OFFSET (BIGCHAR_WIDTH)
Definition at line 81 of file ui_local.h.
SLIDER_RANGE
#define SLIDER_RANGE 10
Definition at line 84 of file ui_local.h.
UI_API_VERSION
#define UI_API_VERSION 4
Definition at line 32 of file ui_local.h.
Typedef Documentation
voidfunc_f
typedef void(* voidfunc_f) (void)
Definition at line 36 of file ui_local.h.
Enumeration Type Documentation
awardType_t
enum awardType_t
Enumerator
AWARD_ACCURACY
AWARD_IMPRESSIVE
AWARD_EXCELLENT
AWARD_GAUNTLET
AWARD_FRAGS
AWARD_PERFECT
Definition at line 664 of file ui_local.h.
              {
     AWARD_ACCURACY,
     AWARD_IMPRESSIVE,
     AWARD_EXCELLENT,
     AWARD_GAUNTLET,
     AWARD_FRAGS,
     AWARD_PERFECT
 } awardType_t;
Function Documentation
ArenaServers_Cache()
void ArenaServers_Cache (void)
Definition at line 1503 of file ui_servers2.c.
{
     trap_R_RegisterShaderNoMip( ART_REMOVE0 );
     trap_R_RegisterShaderNoMip( ART_REMOVE1 );
     trap_R_RegisterShaderNoMip( ART_ARROWS0  );
     trap_R_RegisterShaderNoMip( ART_ARROWS_UP );
     trap_R_RegisterShaderNoMip( ART_ARROWS_DOWN );
 }
References ART_ARROWS0, ART_ARROWS_DOWN, ART_ARROWS_UP, ART_REMOVE0, ART_REMOVE1, and trap_R_RegisterShaderNoMip().
Referenced by ArenaServers_MenuInit().
Bitmap_Draw()
void Bitmap_Draw (menubitmap_s * b)
Definition at line 281 of file ui_qmenu.c.
 {
     float   x;
     float   y;
     float   w;
     float   h;
     vec4_t  tempcolor;
     float*  color;
     x = b->generic.x;
     y = b->generic.y;
     w = b->width;
     h = b->height;
     if (b->generic.flags & QMF_RIGHT_JUSTIFY)
     {
         x = x - w;
     }
     else if (b->generic.flags & QMF_CENTER_JUSTIFY)
     {
         x = x - w/2;
     }
     // used to refresh shader
     if (b->generic.name && !b->shader)
     {
         b->shader = trap_R_RegisterShaderNoMip( b->generic.name );
         if (!b->shader && b->errorpic)
             b->shader = trap_R_RegisterShaderNoMip( b->errorpic );
     }
     if (b->generic.flags & QMF_GRAYED)
     {
         if (b->shader)
         {
             trap_R_SetColor( colorMdGrey );
             UI_DrawHandlePic( x, y, w, h, b->shader );
             trap_R_SetColor( NULL );
         }
     }
     else
     {
         if (b->shader)
             UI_DrawHandlePic( x, y, w, h, b->shader );
         if (  ( (b->generic.flags & QMF_PULSE)
             || (b->generic.flags & QMF_PULSEIFFOCUS) )
               && (Menu_ItemAtCursor( b->generic.parent ) == b))
         {
             if (b->focuscolor)
             {
                 tempcolor[0] = b->focuscolor[0];
                 tempcolor[1] = b->focuscolor[1];
                 tempcolor[2] = b->focuscolor[2];
                 color        = tempcolor;
             }
             else
                 color = pulse_color;
             color[3] = 0.5+0.5*sin(uis.realtime/PULSE_DIVISOR);
             trap_R_SetColor( color );
             trap_R_SetColor( NULL );
         }
         else if ((b->generic.flags & QMF_HIGHLIGHT) || ((b->generic.flags & QMF_HIGHLIGHT_IF_FOCUS) && (Menu_ItemAtCursor( b->generic.parent ) == b)))
         {
             if (b->focuscolor)
             {
                 trap_R_SetColor( b->focuscolor );
                 trap_R_SetColor( NULL );
             }
         }
     }
 }
References colorMdGrey, Menu_ItemAtCursor(), NULL, pulse_color, PULSE_DIVISOR, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_HIGHLIGHT, QMF_HIGHLIGHT_IF_FOCUS, QMF_PULSE, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, uiStatic_t::realtime, trap_R_RegisterShaderNoMip(), trap_R_SetColor(), UI_DrawHandlePic(), and uis.
Referenced by Menu_Draw().
Bitmap_Init()
void Bitmap_Init (menubitmap_s * b)
Definition at line 241 of file ui_qmenu.c.
 {
     int x;
     int y;
     int w;
     int h;
     x = b->generic.x;
     y = b->generic.y;
     w = b->width;
     h = b->height;
     if( w < 0 ) {
         w = -w;
     }
     if( h < 0 ) {
         h = -h;
     }
     if (b->generic.flags & QMF_RIGHT_JUSTIFY)
     {
         x = x - w;
     }
     else if (b->generic.flags & QMF_CENTER_JUSTIFY)
     {
         x = x - w/2;
     }
     b->generic.left   = x;
     b->generic.right  = x + w;
     b->generic.top    = y;
     b->generic.bottom = y + h;
     b->shader      = 0;
 }
References QMF_CENTER_JUSTIFY, and QMF_RIGHT_JUSTIFY.
Referenced by Menu_AddItem().
Camera_Cache()
void Camera_Cache (void)
Definition at line 286 of file ui_camera.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
 }
References ART_BACK0, ART_BACK1, and trap_R_RegisterShaderNoMip().
Referenced by Camera_MenuInit().
ConfirmMenu_Cache()
void ConfirmMenu_Cache (void)
Definition at line 164 of file ui_confirm.c.
{
     trap_R_RegisterShaderNoMip( ART_CONFIRM_FRAME );
 }
References ART_CONFIRM_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by UI_ConfirmMenu_Style(), and UI_Message().
Controls_Cache()
void Controls_Cache (void)
Definition at line 1190 of file ui_controls2.c.
 { }
Referenced by Controls_MenuInit().
InGame_Cache()
void InGame_Cache (void)
Definition at line 244 of file ui_ingame.c.
{
     trap_R_RegisterShaderNoMip( INGAME_FRAME );
 }
References INGAME_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by InGame_MenuInit().
MainMenu_Cache()
void MainMenu_Cache (void)
Definition at line 207 of file ui_menu.c.
 {}
Referenced by UI_MainMenu().
Menu_ActivateItem()
sfxHandle_t Menu_ActivateItem (menuframework_s * s, menucommon_s * item)
Definition at line 1549 of file ui_qmenu.c.
{
     if ( item->callback ) {
         item->callback( item, QM_ACTIVATED );
         if( !( item->flags & QMF_SILENT ) ) {
             return menu_move_sound;
         }
     }
     return 0;
 }
References menucommon_s::callback, menucommon_s::flags, menu_move_sound, QM_ACTIVATED, and QMF_SILENT.
Referenced by Menu_DefaultKey().
Menu_AddItem()
void Menu_AddItem (menuframework_s * menu, void * item)
Definition at line 1248 of file ui_qmenu.c.
 {
     menucommon_s    *itemptr;
     if (menu->nitems >= MAX_MENUITEMS)
         trap_Error ("Menu_AddItem: excessive items");
     menu->items[menu->nitems] = item;
     ((menucommon_s*)menu->items[menu->nitems])->parent        = menu;
     ((menucommon_s*)menu->items[menu->nitems])->menuPosition  = menu->nitems;
     ((menucommon_s*)menu->items[menu->nitems])->flags        &= ~QMF_HASMOUSEFOCUS;
     // perform any item specific initializations
     itemptr = (menucommon_s*)item;
     if (!(itemptr->flags & QMF_NODEFAULTINIT))
     {
         switch (itemptr->type)
         {
             case MTYPE_ACTION:
                 Action_Init((menuaction_s*)item);
                 break;
             case MTYPE_FIELD:
                 MenuField_Init((menufield_s*)item);
                 break;
             case MTYPE_SPINCONTROL:
                 SpinControl_Init((menulist_s*)item);
                 break;
             case MTYPE_RADIOBUTTON:
                 RadioButton_Init((menuradiobutton_s*)item);
                 break;
             case MTYPE_SLIDER:
                 Slider_Init((menuslider_s*)item);
                 break;
             case MTYPE_BITMAP:
                 Bitmap_Init((menubitmap_s*)item);
                 break;
             case MTYPE_TEXT:
                 Text_Init((menutext_s*)item);
                 break;
             case MTYPE_SCROLLLIST:
                 ScrollList_Init((menulist_s*)item);
                 break;
             case MTYPE_PTEXT:
                 PText_Init((menutext_s*)item);
                 break;
             case MTYPE_BTEXT:
                 BText_Init((menutext_s*)item);
                 break;
             default:
                 trap_Error( va("Menu_Init: unknown type %d", itemptr->type) );
         }
     }
     menu->nitems++;
 }
References Action_Init(), Bitmap_Init(), BText_Init(), menucommon_s::flags, MAX_MENUITEMS, MenuField_Init(), MTYPE_ACTION, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_PTEXT, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, MTYPE_TEXT, PText_Init(), QMF_HASMOUSEFOCUS, QMF_NODEFAULTINIT, RadioButton_Init(), ScrollList_Init(), Slider_Init(), SpinControl_Init(), Text_Init(), trap_Error(), menucommon_s::type, and va().
Referenced by ArenaServers_MenuInit(), Camera_MenuInit(), Controls_MenuInit(), InGame_MenuInit(), Music_MenuInit(), Options_MenuInit(), PlayerModel_MenuInit(), Preferences_MenuInit(), StartServer_MenuInit(), SystemSettings_MenuInit(), TeamMain_MenuInit(), UI_ConfirmMenu_Style(), UI_DrawConnectScreen(), UI_MainMenu(), UI_Message(), and UI_ServerInfoMenu().
Menu_AdjustCursor()
void Menu_AdjustCursor (menuframework_s * menu, int dir)
Definition at line 1386 of file ui_qmenu.c.
{
     menucommon_s    *item = NULL;
     qboolean        wrapped = qfalse;
 wrap:
     while ( m->cursor >= 0 && m->cursor < m->nitems ) {
         item = ( menucommon_s * ) m->items[m->cursor];
         if (( item->flags & (QMF_GRAYED|QMF_MOUSEONLY|QMF_INACTIVE) ) ) {
             m->cursor += dir;
         }
         else {
             break;
         }
     }
     if ( dir == 1 ) {
         if ( m->cursor >= m->nitems ) {
             if ( m->wrapAround ) {
                 if ( wrapped ) {
                     m->cursor = m->cursor_prev;
                     return;
                 }
                 m->cursor = 0;
                 wrapped = qtrue;
                 goto wrap;
             }
             m->cursor = m->cursor_prev;
         }
     }
     else {
         if ( m->cursor < 0 ) {
             if ( m->wrapAround ) {
                 if ( wrapped ) {
                     m->cursor = m->cursor_prev;
                     return;
                 }
                 m->cursor = m->nitems - 1;
                 wrapped = qtrue;
                 goto wrap;
             }
             m->cursor = m->cursor_prev;
         }
     }
 }
References dir, menucommon_s::flags, m, NULL, qfalse, QMF_GRAYED, QMF_INACTIVE, QMF_MOUSEONLY, and qtrue.
Referenced by Menu_DefaultKey().
Menu_Cache()
void Menu_Cache (void)
Definition at line 1692 of file ui_qmenu.c.
                      {
     uis.charset         = trap_R_RegisterShaderNoMip("consoleFont");
     uis.charsetProp     = trap_R_RegisterShaderNoMip("interface/fonts/font1.png");
     uis.charsetPropGlow = trap_R_RegisterShaderNoMip("interface/fonts/font1Glow.png");
     uis.charsetPropB    = trap_R_RegisterShaderNoMip("interface/fonts/font2.png");
     uis.cursor          = trap_R_RegisterShaderNoMip("interface/menu/cursor.png");
     uis.rb_on           = trap_R_RegisterShaderNoMip("interface/art/switch_on");
     uis.rb_off          = trap_R_RegisterShaderNoMip("interface/art/switch_off");
     uis.whiteShader = trap_R_RegisterShaderNoMip("white");
     uis.menuBackShader  = trap_R_RegisterShaderNoMip("menuback");
     uis.logoShader  = trap_R_RegisterShaderNoMip("zeq2litelogo");
     uis.sceneModel = trap_R_RegisterModel("interface/menu/earthBattle.md3");
     uis.logoModel = trap_R_RegisterModel("interface/menu/logo.md3");
     uis.menuSide    = trap_R_RegisterShaderNoMip("menuSide");
     uis.menuFrame   = trap_R_RegisterShaderNoMip("menuFrame");
     uis.blobShadow  = trap_R_RegisterShaderNoMip("blobShadow");
     uis.nameArea    = trap_R_RegisterShaderNoMip("nameArea");
     uis.menuButton1 = trap_R_RegisterShaderNoMip("mainButton1");
     uis.menuButton2 = trap_R_RegisterShaderNoMip("mainButton2");
     uis.menuButton3 = trap_R_RegisterShaderNoMip("mainButton3");
     uis.menuButton4 = trap_R_RegisterShaderNoMip("mainButton4");
     uis.menuButton5 = trap_R_RegisterShaderNoMip("mainButton5");
     uis.menuButton6 = trap_R_RegisterShaderNoMip("mainButton6");
     menu_in_sound   = trap_S_RegisterSound( "interface/menu/click.ogg", qfalse );
     menu_move_sound = trap_S_RegisterSound( "interface/menu/hover.ogg", qfalse );
     menu_out_sound  = trap_S_RegisterSound( "interface/menu/back.ogg", qfalse );
     menu_buzz_sound = trap_S_RegisterSound( "interface/menu/cancel.ogg", qfalse );
     menu_exit_sound = trap_S_RegisterSound( "interface/menu/exit.ogg", qfalse );
     menu_null_sound = -1;
     sliderBar = trap_R_RegisterShaderNoMip( "interface/art/slider2" );
     sliderButton = trap_R_RegisterShaderNoMip( "interface/art/sliderbutton" );
 }
References uiStatic_t::blobShadow, uiStatic_t::charset, uiStatic_t::charsetProp, uiStatic_t::charsetPropB, uiStatic_t::charsetPropGlow, uiStatic_t::cursor, uiStatic_t::logoModel, uiStatic_t::logoShader, menu_buzz_sound, menu_exit_sound, menu_in_sound, menu_move_sound, menu_null_sound, menu_out_sound, uiStatic_t::menuBackShader, uiStatic_t::menuButton1, uiStatic_t::menuButton2, uiStatic_t::menuButton3, uiStatic_t::menuButton4, uiStatic_t::menuButton5, uiStatic_t::menuButton6, uiStatic_t::menuFrame, uiStatic_t::menuSide, uiStatic_t::nameArea, qfalse, uiStatic_t::rb_off, uiStatic_t::rb_on, uiStatic_t::sceneModel, sliderBar, sliderButton, trap_R_RegisterModel(), trap_R_RegisterShaderNoMip(), trap_S_RegisterSound(), uis, and uiStatic_t::whiteShader.
Referenced by UI_DrawConnectScreen(), and UI_Init().
Menu_Common()
void Menu_Common (int amount)
Definition at line 2 of file ui_shared.c.
{
     int current;
     int x = 16;
     int y = 112;
     current = 1;
     UI_MenuLogo();
     while(current < amount+1){
         if(current == 1){UI_DrawHandlePic(x,y,124,34,uis.menuButton1);}
         if(current == 2){UI_DrawHandlePic(x,y,109,34,uis.menuButton2);}
         if(current == 3){UI_DrawHandlePic(x,y,102,34,uis.menuButton3);}
         if(current == 4){UI_DrawHandlePic(x,y,102,34,uis.menuButton4);}
         if(current == 5){UI_DrawHandlePic(x,y,109,34,uis.menuButton5);}
         if(current == 6){UI_DrawHandlePic(x,y,124,34,uis.menuButton6);}
         y += 38;
         current += 1;
     }
 }
References current, uiStatic_t::menuButton1, uiStatic_t::menuButton2, uiStatic_t::menuButton3, uiStatic_t::menuButton4, uiStatic_t::menuButton5, uiStatic_t::menuButton6, UI_DrawHandlePic(), UI_MenuLogo(), and uis.
Referenced by UI_Refresh().
Menu_DefaultKey()
sfxHandle_t Menu_DefaultKey (menuframework_s * s, int key)
Definition at line 1565 of file ui_qmenu.c.
 {
     sfxHandle_t     sound = 0;
     menucommon_s    *item;
     int             cursor_prev;
     // menu system keys
     switch ( key )
     {
         case K_MOUSE2:
         case K_ESCAPE:
             UI_PopMenu();
             return menu_out_sound;
     }
     if (!m || !m->nitems)
         return 0;
     // route key stimulus to widget
     item = Menu_ItemAtCursor( m );
     if (item && !(item->flags & (QMF_GRAYED|QMF_INACTIVE)))
     {
         switch (item->type)
         {
             case MTYPE_SPINCONTROL:
                 sound = SpinControl_Key( (menulist_s*)item, key );
                 break;
             case MTYPE_RADIOBUTTON:
                 sound = RadioButton_Key( (menuradiobutton_s*)item, key );
                 break;
             case MTYPE_SLIDER:
                 sound = Slider_Key( (menuslider_s*)item, key );
                 break;
             case MTYPE_SCROLLLIST:
                 sound = ScrollList_Key( (menulist_s*)item, key );
                 break;
             case MTYPE_FIELD:
                 sound = MenuField_Key( (menufield_s*)item, &key );
                 break;
         }
         if (sound) {
             // key was handled
             return sound;
         }
     }
     // default handling
     switch ( key ){
         case K_F11:
             uis.debug ^= 1;
             break;
         case K_F12:
             trap_Cmd_ExecuteText(EXEC_APPEND, "screenshot\n");
             break;
         case K_KP_UPARROW:
         case K_UPARROW:
             cursor_prev    = m->cursor;
             m->cursor_prev = m->cursor;
             m->cursor--;
             Menu_AdjustCursor( m, -1 );
             if ( cursor_prev != m->cursor ) {
                 Menu_CursorMoved( m );
                 sound = menu_move_sound;
             }
             break;
         case K_TAB:
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
             cursor_prev    = m->cursor;
             m->cursor_prev = m->cursor;
             m->cursor++;
             Menu_AdjustCursor( m, 1 );
             if ( cursor_prev != m->cursor ) {
                 Menu_CursorMoved( m );
                 sound = menu_move_sound;
             }
             break;
         case K_MOUSE1:
         case K_MOUSE3:
             if (item)
                 if ((item->flags & QMF_HASMOUSEFOCUS) && !(item->flags & (QMF_GRAYED|QMF_INACTIVE)))
                     return (Menu_ActivateItem( m, item ));
             break;
         case K_JOY1:
         case K_JOY2:
         case K_JOY3:
         case K_JOY4:
         case K_AUX1:
         case K_AUX2:
         case K_AUX3:
         case K_AUX4:
         case K_AUX5:
         case K_AUX6:
         case K_AUX7:
         case K_AUX8:
         case K_AUX9:
         case K_AUX10:
         case K_AUX11:
         case K_AUX12:
         case K_AUX13:
         case K_AUX14:
         case K_AUX15:
         case K_AUX16:
         case K_KP_ENTER:
         case K_ENTER:
             if (item)
                 if (!(item->flags & (QMF_MOUSEONLY|QMF_GRAYED|QMF_INACTIVE)))
                     return (Menu_ActivateItem( m, item ));
             break;
     }
     return sound;
 }
References uiStatic_t::debug, EXEC_APPEND, menucommon_s::flags, K_AUX1, K_AUX10, K_AUX11, K_AUX12, K_AUX13, K_AUX14, K_AUX15, K_AUX16, K_AUX2, K_AUX3, K_AUX4, K_AUX5, K_AUX6, K_AUX7, K_AUX8, K_AUX9, K_DOWNARROW, K_ENTER, K_ESCAPE, K_F11, K_F12, K_JOY1, K_JOY2, K_JOY3, K_JOY4, K_KP_DOWNARROW, K_KP_ENTER, K_KP_UPARROW, K_MOUSE1, K_MOUSE2, K_MOUSE3, K_TAB, K_UPARROW, m, Menu_ActivateItem(), Menu_AdjustCursor(), Menu_CursorMoved(), Menu_ItemAtCursor(), menu_move_sound, menu_out_sound, MenuField_Key(), MTYPE_FIELD, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, QMF_GRAYED, QMF_HASMOUSEFOCUS, QMF_INACTIVE, QMF_MOUSEONLY, RadioButton_Key(), ScrollList_Key(), Slider_Key(), SpinControl_Key(), trap_Cmd_ExecuteText(), menucommon_s::type, UI_PopMenu(), and uis.
Referenced by ArenaServers_MenuKey(), ConfirmMenu_Key(), Controls_MenuKey(), PlayerModel_MenuKey(), ServerInfo_MenuKey(), UI_KeyEvent(), and UI_MusicMenu_Key().
Menu_Draw()
void Menu_Draw (menuframework_s * menu)
Definition at line 1436 of file ui_qmenu.c.
 {
     int             i;
     menucommon_s    *itemptr;
     // draw menu
     for (i=0; i<menu->nitems; i++)
     {
         itemptr = (menucommon_s*)menu->items[i];
         if (itemptr->flags & QMF_HIDDEN)
             continue;
         if (itemptr->ownerdraw)
         {
             // total subclassing, owner draws everything
             itemptr->ownerdraw( itemptr );
         }
         else
         {
             switch (itemptr->type)
             {
                 case MTYPE_RADIOBUTTON:
                     RadioButton_Draw( (menuradiobutton_s*)itemptr );
                     break;
                 case MTYPE_FIELD:
                     MenuField_Draw( (menufield_s*)itemptr );
                     break;
                 case MTYPE_SLIDER:
                     Slider_Draw( (menuslider_s*)itemptr );
                     break;
                 case MTYPE_SPINCONTROL:
                     SpinControl_Draw( (menulist_s*)itemptr );
                     break;
                 case MTYPE_ACTION:
                     Action_Draw( (menuaction_s*)itemptr );
                     break;
                 case MTYPE_BITMAP:
                     Bitmap_Draw( (menubitmap_s*)itemptr );
                     break;
                 case MTYPE_TEXT:
                     Text_Draw( (menutext_s*)itemptr );
                     break;
                 case MTYPE_SCROLLLIST:
                     ScrollList_Draw( (menulist_s*)itemptr );
                     break;
                 case MTYPE_PTEXT:
                     PText_Draw( (menutext_s*)itemptr );
                     break;
                 case MTYPE_BTEXT:
                     BText_Draw( (menutext_s*)itemptr );
                     break;
                 default:
                     trap_Error( va("Menu_Draw: unknown type %d", itemptr->type) );
             }
         }
 #ifndef NDEBUG
         if( uis.debug ) {
             int x;
             int y;
             int w;
             int h;
             if( !( itemptr->flags & QMF_INACTIVE ) ) {
                 x = itemptr->left;
                 y = itemptr->top;
                 w = itemptr->right - itemptr->left + 1;
                 h = itemptr->bottom - itemptr->top + 1;
                 if (itemptr->flags & QMF_HASMOUSEFOCUS) {
                     UI_DrawRect(x, y, w, h, colorYellow );
                 }
                 else {
                     UI_DrawRect(x, y, w, h, colorWhite );
                 }
             }
         }
 #endif
     }
     itemptr = Menu_ItemAtCursor( menu );
     if ( itemptr && itemptr->statusbar)
         itemptr->statusbar( ( void * ) itemptr );
 }
References Action_Draw(), Bitmap_Draw(), menucommon_s::bottom, BText_Draw(), colorWhite, colorYellow, uiStatic_t::debug, menucommon_s::flags, menucommon_s::left, Menu_ItemAtCursor(), MenuField_Draw(), MTYPE_ACTION, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_PTEXT, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, MTYPE_TEXT, menucommon_s::ownerdraw, PText_Draw(), QMF_HASMOUSEFOCUS, QMF_HIDDEN, QMF_INACTIVE, RadioButton_Draw(), menucommon_s::right, ScrollList_Draw(), Slider_Draw(), SpinControl_Draw(), menucommon_s::statusbar, Text_Draw(), menucommon_s::top, trap_Error(), menucommon_s::type, UI_DrawRect(), uis, and va().
Referenced by ArenaServers_MenuDraw(), ConfirmMenu_Draw(), Main_MenuDraw(), MessageMenu_Draw(), Preferences_MenuDraw(), ServerInfo_MenuDraw(), SystemSettings_MenuDraw(), and UI_Refresh().
Menu_Focus()
void Menu_Focus (menucommon_s * m)
Menu_Frame()
void Menu_Frame (void)
Definition at line 19 of file ui_shared.c.
                      {
     UI_DrawHandlePic(147,113,367,310,uis.menuFrame);
 }
References uiStatic_t::menuFrame, UI_DrawHandlePic(), and uis.
Referenced by UI_Refresh().
Menu_ItemAtCursor()
void* Menu_ItemAtCursor (menuframework_s * m)
Definition at line 1536 of file ui_qmenu.c.
 {
     if ( m->cursor < 0 || m->cursor >= m->nitems )
         return NULL;
     return m->items[m->cursor];
 }
References m, and NULL.
Referenced by ArenaServers_MenuKey(), Bitmap_Draw(), Controls_DrawKeyBinding(), Menu_DefaultKey(), Menu_Draw(), MenuField_Draw(), PlayerModel_MenuKey(), PText_Draw(), and UI_MusicMenu_Key().
Menu_SetCursor()
void Menu_SetCursor (menuframework_s * s, int cursor)
Definition at line 1346 of file ui_qmenu.c.
 {
     if (((menucommon_s*)(m->items[cursor]))->flags & (QMF_GRAYED|QMF_INACTIVE))
     {
         // cursor can't go there
         return;
     }
     m->cursor_prev = m->cursor;
     m->cursor      = cursor;
     Menu_CursorMoved( m );
 }
References m, Menu_CursorMoved(), QMF_GRAYED, and QMF_INACTIVE.
Referenced by Menu_SetCursorToItem(), PlayerModel_MenuKey(), UI_MouseEvent(), and UI_PushMenu().
Menu_SetCursorToItem()
void Menu_SetCursorToItem (menuframework_s * m, void * ptr)
Definition at line 1365 of file ui_qmenu.c.
 {
     int i;
     for (i=0; i<m->nitems; i++)
     {
         if (m->items[i] == ptr)
         {
             Menu_SetCursor( m, i );
             return;
         }
     }
 }
References m, Menu_SetCursor(), and ptr().
Referenced by UI_ConfirmMenu_Style(), UI_ControlsMenu(), UI_Message(), UI_PlayerModelMenu(), UI_PreferencesMenu(), and UI_SystemSettingsMenu().
Menu_Side()
void Menu_Side (void)
Definition at line 22 of file ui_shared.c.
 {}
Referenced by UI_Refresh().
MenuField_Draw()
void MenuField_Draw (menufield_s * f)
Definition at line 340 of file ui_mfield.c.
 {
     int     x;
     int     y;
     int     w;
     int     h;
     int     style;
     qboolean focus;
     float   *color;
     x = f->generic.x;
     y = f->generic.y;
     if (f->generic.flags & QMF_SMALLFONT)
     {
         w = 6;
         h = 12;
         style = UI_TINYFONT|UI_DROPSHADOW;
     }
     else
     {
         w = BIGCHAR_WIDTH;
         h = BIGCHAR_HEIGHT;
         style = UI_BIGFONT|UI_DROPSHADOW;
     }
     if (Menu_ItemAtCursor( f->generic.parent ) == f) {
         focus = qtrue;
         style |= UI_PULSE;
     }
     else {
         focus = qfalse;
     }
     if (f->generic.flags & QMF_GRAYED)
         color = text_color_disabled;
     else if (focus)
         color = text_color_highlight;
     else
         color = text_color_normal;
     if ( focus )
     {
         // draw cursor
         UI_FillRect( f->generic.left, f->generic.top, f->generic.right-f->generic.left+1, f->generic.bottom-f->generic.top+1, listbar_color );
         UI_DrawChar( x, y, 13, UI_CENTER|UI_BLINK|style|UI_DROPSHADOW, color);
     }
     if ( f->generic.name ) {
         UI_DrawString( x - w, y, f->generic.name, style|UI_RIGHT, color );
     }
     MField_Draw( &f->field, x + w, y, style, color );
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, menucommon_s::bottom, menufield_s::field, menucommon_s::flags, menufield_s::generic, menucommon_s::left, listbar_color, Menu_ItemAtCursor(), MField_Draw(), menucommon_s::name, menucommon_s::parent, qfalse, QMF_GRAYED, QMF_SMALLFONT, qtrue, menucommon_s::right, text_color_disabled, text_color_highlight, text_color_normal, menucommon_s::top, UI_BIGFONT, UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawString(), UI_DROPSHADOW, UI_FillRect(), UI_PULSE, UI_RIGHT, UI_TINYFONT, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_Draw().
MenuField_Init()
void MenuField_Init (menufield_s * m)
Definition at line 299 of file ui_mfield.c.
{
     int l;
     int w;
     int h;
     MField_Clear( &m->field );
     if (m->generic.flags & QMF_SMALLFONT)
     {
         w = 6;
         h = 12;
     }
     else if (m->generic.flags & QMF_TINYFONT)
     {
         w = 6;
         h = 12;
     }
     else
     {
         w = BIGCHAR_WIDTH;
         h = BIGCHAR_HEIGHT;
     }
     if (m->generic.name) {
         l = (strlen( m->generic.name )+1) * w;
     }
     else {
         l = 0;
     }
     m->generic.left   = m->generic.x - l;
     m->generic.top    = m->generic.y;
     m->generic.right  = m->generic.x + w + m->field.widthInChars*w;
     m->generic.bottom = m->generic.y + h;
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, m, MField_Clear(), QMF_SMALLFONT, and QMF_TINYFONT.
Referenced by Menu_AddItem().
MenuField_Key()
sfxHandle_t MenuField_Key (menufield_s * m, int * key)
Definition at line 400 of file ui_mfield.c.
 {
     int keycode;
     keycode = *key;
     switch ( keycode )
     {
         case K_KP_ENTER:
         case K_ENTER:
         case K_JOY1:
         case K_JOY2:
         case K_JOY3:
         case K_JOY4:
             // have enter go to next cursor point
             *key = K_TAB;
             break;
         case K_TAB:
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
         case K_KP_UPARROW:
         case K_UPARROW:
             break;
         default:
             if ( keycode & K_CHAR_FLAG )
             {
                 keycode &= ~K_CHAR_FLAG;
                 if ((m->generic.flags & QMF_UPPERCASE) && Q_islower( keycode ))
                     keycode -= 'a' - 'A';
                 else if ((m->generic.flags & QMF_LOWERCASE) && Q_isupper( keycode ))
                     keycode -= 'A' - 'a';
                 else if ((m->generic.flags & QMF_NUMBERSONLY) && Q_isalpha( keycode ))
                     return (menu_buzz_sound);
                 MField_CharEvent( &m->field, keycode);
             }
             else
                 MField_KeyDownEvent( &m->field, keycode );
             break;
     }
     return (0);
 }
References K_CHAR_FLAG, K_DOWNARROW, K_ENTER, K_JOY1, K_JOY2, K_JOY3, K_JOY4, K_KP_DOWNARROW, K_KP_ENTER, K_KP_UPARROW, K_TAB, K_UPARROW, m, menu_buzz_sound, MField_CharEvent(), MField_KeyDownEvent(), Q_isalpha(), Q_islower(), Q_isupper(), QMF_LOWERCASE, QMF_NUMBERSONLY, and QMF_UPPERCASE.
Referenced by Menu_DefaultKey().
MField_CharEvent()
void MField_CharEvent (mfield_t * edit, int ch)
Definition at line 210 of file ui_mfield.c.
{
     int     len;
     if ( ch == 'v' - 'a' + 1 ) {    // ctrl-v is paste
         MField_Paste( edit );
         return;
     }
     if ( ch == 'c' - 'a' + 1 ) {    // ctrl-c clears the field
         MField_Clear( edit );
         return;
     }
     len = strlen( edit->buffer );
     if ( ch == 'h' - 'a' + 1 )  {   // ctrl-h is backspace
         if ( edit->cursor > 0 ) {
             memmove( edit->buffer + edit->cursor - 1,
                 edit->buffer + edit->cursor, len + 1 - edit->cursor );
             edit->cursor--;
             if ( edit->cursor < edit->scroll )
             {
                 edit->scroll--;
             }
         }
         return;
     }
     if ( ch == 'a' - 'a' + 1 ) {    // ctrl-a is home
         edit->cursor = 0;
         edit->scroll = 0;
         return;
     }
     if ( ch == 'e' - 'a' + 1 ) {    // ctrl-e is end
         edit->cursor = len;
         edit->scroll = edit->cursor - edit->widthInChars + 1;
         if (edit->scroll < 0)
             edit->scroll = 0;
         return;
     }
     //
     // ignore any other non printable chars
     //
     if ( ch < 32 ) {
         return;
     }
     if ( !trap_Key_GetOverstrikeMode() ) {
         if ((edit->cursor == MAX_EDIT_LINE - 1) || (edit->maxchars && edit->cursor >= edit->maxchars))
             return;
     } else {
         // insert mode
         if (( len == MAX_EDIT_LINE - 1 ) || (edit->maxchars && len >= edit->maxchars))
             return;
         memmove( edit->buffer + edit->cursor + 1, edit->buffer + edit->cursor, len + 1 - edit->cursor );
     }
     edit->buffer[edit->cursor] = ch;
     if (!edit->maxchars || edit->cursor < edit->maxchars-1)
         edit->cursor++;
     if ( edit->cursor >= edit->widthInChars )
     {
         edit->scroll++;
     }
     if ( edit->cursor == len + 1) {
         edit->buffer[edit->cursor] = 0;
     }
 }
References mfield_t::buffer, mfield_t::cursor, MAX_EDIT_LINE, mfield_t::maxchars, memmove(), MField_Clear(), MField_Paste(), mfield_t::scroll, trap_Key_GetOverstrikeMode(), and mfield_t::widthInChars.
Referenced by MenuField_Key(), and MField_Paste().
MField_Clear()
void MField_Clear (mfield_t * edit)
Definition at line 288 of file ui_mfield.c.
{
     edit->buffer[0] = 0;
     edit->cursor = 0;
     edit->scroll = 0;
 }
References mfield_t::buffer, mfield_t::cursor, and mfield_t::scroll.
Referenced by MenuField_Init(), and MField_CharEvent().
MField_Draw()
void MField_Draw (mfield_t * edit, int x, int y, int style, vec4_t color)
Definition at line 33 of file ui_mfield.c.
{
     int     len;
     int     charw;
     int     drawLen;
     int     prestep;
     int     cursorChar;
     char    str[MAX_STRING_CHARS];
     drawLen = edit->widthInChars;
     len     = strlen( edit->buffer ) + 1;
     // guarantee that cursor will be visible
     if ( len <= drawLen ) {
         prestep = 0;
     } else {
         if ( edit->scroll + drawLen > len ) {
             edit->scroll = len - drawLen;
             if ( edit->scroll < 0 ) {
                 edit->scroll = 0;
             }
         }
         prestep = edit->scroll;
     }
     if ( prestep + drawLen > len ) {
         drawLen = len - prestep;
     }
     // extract <drawLen> characters from the field at <prestep>
     if ( drawLen >= MAX_STRING_CHARS ) {
         trap_Error( "drawLen >= MAX_STRING_CHARS" );
     }
     memcpy( str, edit->buffer + prestep, drawLen );
     str[ drawLen ] = 0;
     UI_DrawString( x, y, str, style, color );
     // draw the cursor
     if (!(style & UI_PULSE)) {
         return;
     }
     if ( trap_Key_GetOverstrikeMode() ) {
         cursorChar = 11;
     } else {
         cursorChar = 10;
     }
     style &= ~UI_PULSE;
     style |= UI_BLINK;
     if (style & UI_SMALLFONT)
     {
         charw = SMALLCHAR_WIDTH;
     }
     else if (style & UI_TINYFONT){
         charw = 6;
     }
     else if (style & UI_GIANTFONT)
     {
         charw = GIANTCHAR_WIDTH;
     }
     else
     {
         charw = BIGCHAR_WIDTH;
     }
     if (style & UI_CENTER)
     {
         len = strlen(str);
         x = x - len*charw/2;
     }
     else if (style & UI_RIGHT)
     {
         len = strlen(str);
         x = x - len*charw;
     }
     UI_DrawChar( x + ( edit->cursor - prestep ) * charw, y, cursorChar, style & ~(UI_CENTER|UI_RIGHT|UI_DROPSHADOW), color );
 }
References BIGCHAR_WIDTH, mfield_t::buffer, mfield_t::cursor, GIANTCHAR_WIDTH, MAX_STRING_CHARS, mfield_t::scroll, SMALLCHAR_WIDTH, trap_Error(), trap_Key_GetOverstrikeMode(), UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawString(), UI_DROPSHADOW, UI_GIANTFONT, UI_PULSE, UI_RIGHT, UI_SMALLFONT, UI_TINYFONT, and mfield_t::widthInChars.
Referenced by MenuField_Draw(), and UI_DrawConnectScreen().
MField_KeyDownEvent()
void MField_KeyDownEvent (mfield_t * edit, int key)
Definition at line 142 of file ui_mfield.c.
{
     int     len;
     // shift-insert is paste
     if ( ( ( key == K_INS ) || ( key == K_KP_INS ) ) && trap_Key_IsDown( K_SHIFT ) ) {
         MField_Paste( edit );
         return;
     }
     len = strlen( edit->buffer );
     if ( key == K_DEL || key == K_KP_DEL ) {
         if ( edit->cursor < len ) {
             memmove( edit->buffer + edit->cursor,
                 edit->buffer + edit->cursor + 1, len - edit->cursor );
         }
         return;
     }
     if ( key == K_RIGHTARROW || key == K_KP_RIGHTARROW )
     {
         if ( edit->cursor < len ) {
             edit->cursor++;
         }
         if ( edit->cursor >= edit->scroll + edit->widthInChars && edit->cursor <= len )
         {
             edit->scroll++;
         }
         return;
     }
     if ( key == K_LEFTARROW || key == K_KP_LEFTARROW )
     {
         if ( edit->cursor > 0 ) {
             edit->cursor--;
         }
         if ( edit->cursor < edit->scroll )
         {
             edit->scroll--;
         }
         return;
     }
     if ( key == K_HOME || key == K_KP_HOME || ( tolower(key) == 'a' && trap_Key_IsDown( K_CTRL ) ) ) {
         edit->cursor = 0;
         edit->scroll = 0;
         return;
     }
     if ( key == K_END || key == K_KP_END || ( tolower(key) == 'e' && trap_Key_IsDown( K_CTRL ) ) ) {
         edit->cursor = len;
         edit->scroll = len - edit->widthInChars + 1;
         if (edit->scroll < 0)
             edit->scroll = 0;
         return;
     }
     if ( key == K_INS || key == K_KP_INS ) {
         trap_Key_SetOverstrikeMode( !trap_Key_GetOverstrikeMode() );
         return;
     }
 }
References mfield_t::buffer, mfield_t::cursor, K_CTRL, K_DEL, K_END, K_HOME, K_INS, K_KP_DEL, K_KP_END, K_KP_HOME, K_KP_INS, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_RIGHTARROW, K_SHIFT, memmove(), MField_Paste(), mfield_t::scroll, trap_Key_GetOverstrikeMode(), trap_Key_IsDown(), trap_Key_SetOverstrikeMode(), and mfield_t::widthInChars.
Referenced by MenuField_Key().
PlayerModel_Cache()
void PlayerModel_Cache (void)
Definition at line 704 of file ui_playermodel.c.
 {
     int i;
     for( i = 0; playermodel_artlist[i]; i++ ) {
         trap_R_RegisterShaderNoMip( playermodel_artlist[i] );
     }
     PlayerModel_BuildList();
     for( i = 0; i < s_playermodel.nummodels; i++ ) {
         trap_R_RegisterShaderNoMip( s_playermodel.modelnames[i] );
     }
 }
References playermodel_t::modelnames, playermodel_t::nummodels, playermodel_artlist, PlayerModel_BuildList(), s_playermodel, and trap_R_RegisterShaderNoMip().
Referenced by PlayerModel_MenuInit().
PlayerSettings_Cache()
void PlayerSettings_Cache (void)
Preferences_Cache()
void Preferences_Cache (void)
Definition at line 573 of file ui_preferences.c.
{
     int n;
     trap_R_RegisterShaderNoMip(ART_FRAMEL);
     trap_R_RegisterShaderNoMip(ART_FRAMER);
     trap_R_RegisterShaderNoMip(ART_BACK0);
     trap_R_RegisterShaderNoMip(ART_BACK1);
     trap_R_RegisterShaderNoMip(ART_ACCEPT0);
     trap_R_RegisterShaderNoMip(ART_ACCEPT1);
     for(n=0;n<NUM_CROSSHAIRS;n++){
         s_preferences.crosshairShader[n] = trap_R_RegisterShaderNoMip( va("crosshair%c", 'a' + n ) );
     }
 }
References ART_ACCEPT0, ART_ACCEPT1, ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, preferences_t::crosshairShader, NUM_CROSSHAIRS, s_preferences, trap_R_RegisterShaderNoMip(), and va().
Referenced by Preferences_MenuInit().
ScrollList_Draw()
void ScrollList_Draw (menulist_s * l)
Definition at line 1184 of file ui_qmenu.c.
 {
     int         x;
     int         u;
     int         y;
     int         i;
     int         base;
     int         column;
     float*      color;
     qboolean    hasfocus;
     int         style;
     hasfocus = (l->generic.parent->cursor == l->generic.menuPosition);
     x = l->generic.x;
     for( column = 0; column < l->columns; column++ ) {
         y = l->generic.y;
         base = l->top + column * l->height;
         for( i = base; i < base + l->height; i++) {
             if (i >= l->numitems)
                 break;
             if (i == l->curvalue)
             {
                 u = x - 2;
                 if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                     u -= (l->width * SMALLCHAR_WIDTH) / 2 + 1;
                 }
                 UI_FillRect(u,y,l->width*SMALLCHAR_WIDTH,SMALLCHAR_HEIGHT+2,listbar_color);
                 color = text_color_highlight;
                 if (hasfocus)
                     style = UI_PULSE|UI_LEFT|UI_SMALLFONT|UI_DROPSHADOW;
                 else
                     style = UI_LEFT|UI_SMALLFONT|UI_DROPSHADOW;
             }
             else
             {
                 color = text_color_normal;
                 style = UI_LEFT|UI_SMALLFONT|UI_DROPSHADOW;
             }
             if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                 style |= UI_CENTER|UI_DROPSHADOW;
             }
             UI_DrawString(
                 x,
                 y,
                 l->itemnames[i],
                 style,
                 color);
             y += SMALLCHAR_HEIGHT;
         }
         x += (l->width + l->seperation) * SMALLCHAR_WIDTH;
     }
 }
References menulist_s::columns, menulist_s::curvalue, menucommon_s::flags, menulist_s::generic, menulist_s::height, menulist_s::itemnames, listbar_color, menucommon_s::menuPosition, menulist_s::numitems, menucommon_s::parent, QMF_CENTER_JUSTIFY, menulist_s::seperation, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, text_color_highlight, text_color_normal, menulist_s::top, UI_CENTER, UI_DrawString(), UI_DROPSHADOW, UI_FillRect(), UI_LEFT, UI_PULSE, UI_SMALLFONT, menulist_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_Draw().
ScrollList_Key()
sfxHandle_t ScrollList_Key (menulist_s * l, int key)
Definition at line 903 of file ui_qmenu.c.
 {
     int x;
     int y;
     int w;
     int i;
     int j;
     int c;
     int cursorx;
     int cursory;
     int column;
     int index;
     switch (key)
     {
         case K_MOUSE1:
             if (l->generic.flags & QMF_HASMOUSEFOCUS)
             {
                 // check scroll region
                 x = l->generic.x;
                 y = l->generic.y;
                 w = ( (l->width + l->seperation) * l->columns - l->seperation) * SMALLCHAR_WIDTH;
                 if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                     x -= w / 2;
                 }
                 if (UI_CursorInRect( x, y, w, l->height*SMALLCHAR_HEIGHT ))
                 {
                     cursorx = (uis.cursorx - x)/SMALLCHAR_WIDTH;
                     column = cursorx / (l->width + l->seperation);
                     cursory = (uis.cursory - y)/SMALLCHAR_HEIGHT;
                     index = column * l->height + cursory;
                     if (l->top + index < l->numitems)
                     {
                         l->oldvalue = l->curvalue;
                         l->curvalue = l->top + index;
                         if (l->oldvalue != l->curvalue && l->generic.callback)
{
                             l->generic.callback( l, QM_GOTFOCUS );
                             return (menu_move_sound);
                         }
                     }
                 }
                 // absorbed, silent sound effect
                 return (menu_null_sound);
             }
             break;
         case K_KP_HOME:
         case K_HOME:
             l->oldvalue = l->curvalue;
             l->curvalue = 0;
             l->top      = 0;
             if (l->oldvalue != l->curvalue && l->generic.callback)
             {
                 l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_KP_END:
         case K_END:
             l->oldvalue = l->curvalue;
             l->curvalue = l->numitems-1;
             if( l->columns > 1 ) {
                 c = (l->curvalue / l->height + 1) * l->height;
                 l->top = c - (l->columns * l->height);
             }
             else {
                 l->top = l->curvalue - (l->height - 1);
             }
             if (l->top < 0)
                 l->top = 0;
             if (l->oldvalue != l->curvalue && l->generic.callback)
             {
                 l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_PGUP:
         case K_KP_PGUP:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->curvalue > 0)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue -= l->height-1;
                 if (l->curvalue < 0)
                     l->curvalue = 0;
                 l->top = l->curvalue;
                 if (l->top < 0)
                     l->top = 0;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_PGDN:
         case K_KP_PGDN:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->curvalue < l->numitems-1)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue += l->height-1;
                 if (l->curvalue > l->numitems-1)
                     l->curvalue = l->numitems-1;
                 l->top = l->curvalue - (l->height-1);
                 if (l->top < 0)
                     l->top = 0;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_KP_UPARROW:
         case K_UPARROW:
             if( l->curvalue == 0 ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue--;
             if( l->curvalue < l->top ) {
                 if( l->columns == 1 ) {
                     l->top--;
                 }
                 else {
                     l->top -= l->height;
                 }
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return (menu_move_sound);
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
             if( l->curvalue == l->numitems - 1 ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue++;
             if( l->curvalue >= l->top + l->columns * l->height ) {
                 if( l->columns == 1 ) {
                     l->top++;
                 }
                 else {
                     l->top += l->height;
                 }
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
         case K_KP_LEFTARROW:
         case K_LEFTARROW:
             if( l->columns == 1 ) {
                 return menu_null_sound;
             }
             if( l->curvalue < l->height ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue -= l->height;
             if( l->curvalue < l->top ) {
                 l->top -= l->height;
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
         case K_KP_RIGHTARROW:
         case K_RIGHTARROW:
             if( l->columns == 1 ) {
                 return menu_null_sound;
             }
             c = l->curvalue + l->height;
             if( c >= l->numitems ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue = c;
             if( l->curvalue > l->top + l->columns * l->height - 1 ) {
                 l->top += l->height;
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
     }
     // cycle look for ascii key inside list items
     if ( !Q_isprint( key ) )
         return (0);
     // force to lower for case insensitive compare
     if ( Q_isupper( key ) )
     {
         key -= 'A' - 'a';
     }
     // iterate list items
     for (i=1; i<=l->numitems; i++)
     {
         j = (l->curvalue + i) % l->numitems;
         c = l->itemnames[j][0];
         if ( Q_isupper( c ) )
         {
             c -= 'A' - 'a';
         }
         if (c == key)
         {
             // set current item, mimic windows listbox scroll behavior
             if (j < l->top)
             {
                 // behind top most item, set this as new top
                 l->top = j;
             }
             else if (j > l->top+l->height-1)
             {
                 // past end of list box, do page down
                 l->top = (j+1) - l->height;
             }
             if (l->curvalue != j)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue = j;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return ( menu_move_sound );
             }
             return (menu_buzz_sound);
         }
     }
     return (menu_buzz_sound);
 }
References menucommon_s::callback, menulist_s::columns, uiStatic_t::cursorx, uiStatic_t::cursory, menulist_s::curvalue, menucommon_s::flags, menulist_s::generic, menulist_s::height, menulist_s::itemnames, K_DOWNARROW, K_END, K_HOME, K_KP_DOWNARROW, K_KP_END, K_KP_HOME, K_KP_LEFTARROW, K_KP_PGDN, K_KP_PGUP, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_MOUSE1, K_PGDN, K_PGUP, K_RIGHTARROW, K_UPARROW, menu_buzz_sound, menu_move_sound, menu_null_sound, menulist_s::numitems, menulist_s::oldvalue, Q_isprint(), Q_isupper(), QM_GOTFOCUS, QMF_CENTER_JUSTIFY, QMF_HASMOUSEFOCUS, menulist_s::seperation, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, menulist_s::top, UI_CursorInRect(), uis, menulist_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by ArenaServers_Event(), Menu_DefaultKey(), and Music_MenuEvent().
ServerInfo_Cache()
void ServerInfo_Cache (void)
Definition at line 168 of file ui_serverinfo.c.
 {
     int i;
     // touch all our pics
     for (i=0; ;i++)
     {
         if (!serverinfo_artlist[i])
             break;
         trap_R_RegisterShaderNoMip(serverinfo_artlist[i]);
     }
 }
References serverinfo_artlist, and trap_R_RegisterShaderNoMip().
Referenced by UI_ServerInfoMenu().
SpecifyLeague_Cache()
void SpecifyLeague_Cache (void)
SpecifyServer_Cache()
void SpecifyServer_Cache (void)
StartServer_Cache()
void StartServer_Cache (void)
Definition at line 653 of file ui_startserver.c.
 {
     int             i;
     const char      *info;
     qboolean        precache;
     char            picname[64];
     char            mapname[ MAX_NAMELENGTH ];
     trap_R_RegisterShaderNoMip( GAMESERVER_BACK0 );
     trap_R_RegisterShaderNoMip( GAMESERVER_BACK1 );
     trap_R_RegisterShaderNoMip( GAMESERVER_NEXT0 );
     trap_R_RegisterShaderNoMip( GAMESERVER_NEXT1 );
     trap_R_RegisterShaderNoMip( GAMESERVER_FRAMEL );
     trap_R_RegisterShaderNoMip( GAMESERVER_FRAMER );
     trap_R_RegisterShaderNoMip( GAMESERVER_SELECT );
     trap_R_RegisterShaderNoMip( GAMESERVER_FIGHT0 );
     trap_R_RegisterShaderNoMip( GAMESERVER_FIGHT1 );
     trap_R_RegisterShaderNoMip( GAMESERVER_SELECTED );
     trap_R_RegisterShaderNoMip( GAMESERVER_UNKNOWNMAP );
     trap_R_RegisterShaderNoMip( GAMESERVER_ARROWSL );
     trap_R_RegisterShaderNoMip( GAMESERVER_ARROWSR );
     precache = trap_Cvar_VariableValue("com_buildscript");
     if( precache ) {
         for( i = 0; i < UI_GetNumArenas(); i++ ) {
             info = UI_GetArenaInfoByNumber( i );
             Q_strncpyz( mapname, Info_ValueForKey( info, "map"), MAX_NAMELENGTH );
             Q_strupr( mapname );
             Com_sprintf( picname, sizeof(picname), "maps/%s", mapname );
             trap_R_RegisterShaderNoMip(picname);
         }
     }
 }
References Com_sprintf(), GAMESERVER_ARROWSL, GAMESERVER_ARROWSR, GAMESERVER_BACK0, GAMESERVER_BACK1, GAMESERVER_FIGHT0, GAMESERVER_FIGHT1, GAMESERVER_FRAMEL, GAMESERVER_FRAMER, GAMESERVER_NEXT0, GAMESERVER_NEXT1, GAMESERVER_SELECT, GAMESERVER_SELECTED, GAMESERVER_UNKNOWNMAP, info, Info_ValueForKey(), MAX_NAMELENGTH, Q_strncpyz(), Q_strupr(), trap_Cvar_VariableValue(), trap_R_RegisterShaderNoMip(), UI_GetArenaInfoByNumber(), and UI_GetNumArenas().
Referenced by StartServer_MenuInit().
SystemSettings_Cache()
void SystemSettings_Cache (void)
Definition at line 1204 of file ui_system.c.
{
     trap_R_RegisterShaderNoMip( SYSTEMSETTINGS_FRAMEL );
     trap_R_RegisterShaderNoMip( SYSTEMSETTINGS_FRAMER );
     trap_R_RegisterShaderNoMip( SYSTEMSETTINGS_BACK0 );
     trap_R_RegisterShaderNoMip( SYSTEMSETTINGS_BACK1 );
     trap_R_RegisterShaderNoMip( SYSTEMSETTINGS_ACCEPT0 );
     trap_R_RegisterShaderNoMip( SYSTEMSETTINGS_ACCEPT1 );
 }
References SYSTEMSETTINGS_ACCEPT0, SYSTEMSETTINGS_ACCEPT1, SYSTEMSETTINGS_BACK0, SYSTEMSETTINGS_BACK1, SYSTEMSETTINGS_FRAMEL, SYSTEMSETTINGS_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by SystemSettings_MenuInit().
TeamMain_Cache()
void TeamMain_Cache (void)
Definition at line 188 of file ui_team.c.
{
     trap_R_RegisterShaderNoMip( TEAMMAIN_FRAME );
 }
References TEAMMAIN_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by TeamMain_MenuInit().
trap_Argc()
int trap_Argc (void)
Definition at line 76 of file cg_syscalls.c.
{
     return syscall( CG_ARGC );
 }
References CG_ARGC, G_ARGC, and UI_ARGC.
trap_Argv()
void trap_Argv (int n, char * buffer, int bufferLength)
Definition at line 80 of file cg_syscalls.c.
{
     syscall( CG_ARGV, n, buffer, bufferLength );
 }
References CG_ARGV, G_ARGV, and UI_ARGV.
trap_CM_LerpTag()
int trap_CM_LerpTag (orientation_t * tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char * tagName)
Definition at line 177 of file ui_syscalls.c.
{
     return syscall( UI_CM_LERPTAG, tag, mod, startFrame, endFrame, PASSFLOAT(frac), tagName );
 }
References PASSFLOAT(), and UI_CM_LERPTAG.
Referenced by UI_PositionEntityOnTag(), and UI_PositionRotatedEntityOnTag().
trap_Cmd_ExecuteText()
void trap_Cmd_ExecuteText (int exec_when, const char * text)
Definition at line 101 of file ui_syscalls.c.
{
     syscall( UI_CMD_EXECUTETEXT, exec_when, text );
 }
References UI_CMD_EXECUTETEXT.
Referenced by ArenaServers_DoRefresh(), ArenaServers_Go(), ArenaServers_StartRefresh(), Bloom_ApplyChanges(), Controls_SetConfig(), InGame_Event(), InGame_RestartAction(), Menu_DefaultKey(), Music_MenuEvent(), StartServer_Start(), SystemSettings_backChanges(), SystemSettings_Event(), TeamMain_MenuEvent(), UI_CreditMenu_Key(), UI_KeyConnect(), and UI_StartDemoLoop().
trap_Cvar_Create()
void trap_Cvar_Create (const char * var_name, const char * var_value, int flags)
Definition at line 85 of file ui_syscalls.c.
{
     syscall( UI_CVAR_CREATE, var_name, var_value, flags );
 }
References UI_CVAR_CREATE.
trap_Cvar_InfoStringBuffer()
void trap_Cvar_InfoStringBuffer (int bit, char * buffer, int bufsize)
Definition at line 89 of file ui_syscalls.c.
{
     syscall( UI_CVAR_INFOSTRINGBUFFER, bit, buffer, bufsize );
 }
References UI_CVAR_INFOSTRINGBUFFER.
trap_Cvar_Register()
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
Definition at line 60 of file cg_syscalls.c.
{
     syscall( CG_CVAR_REGISTER, vmCvar, varName, defaultValue, flags );
 }
References CG_CVAR_REGISTER, G_CVAR_REGISTER, and UI_CVAR_REGISTER.
trap_Cvar_Reset()
void trap_Cvar_Reset (const char * name)
Definition at line 81 of file ui_syscalls.c.
{
     syscall( UI_CVAR_RESET, name );
 }
References UI_CVAR_RESET.
Referenced by Camera_InitCvars(), and Controls_InitCvars().
trap_Cvar_Set()
void trap_Cvar_Set (const char * var_name, const char * value)
Definition at line 68 of file cg_syscalls.c.
{
     syscall( CG_CVAR_SET, var_name, value );
 }
References CG_CVAR_SET, G_CVAR_SET, and UI_CVAR_SET.
trap_Cvar_SetValue()
void trap_Cvar_SetValue (const char * var_name, float value)
Definition at line 77 of file ui_syscalls.c.
{
     syscall( UI_CVAR_SETVALUE, var_name, PASSFLOAT( value ) );
 }
References PASSFLOAT(), and UI_CVAR_SETVALUE.
Referenced by ArenaServers_Event(), Camera_InitCvars(), Camera_SetConfig(), Controls_InitCvars(), Preferences_Event(), StartServer_MenuEvent(), StartServer_Start(), SystemSettings_backChanges(), and SystemSettings_Event().
trap_Cvar_Update()
void trap_Cvar_Update (vmCvar_t * vmCvar)
Definition at line 64 of file cg_syscalls.c.
{
     syscall( CG_CVAR_UPDATE, vmCvar );
 }
References CG_CVAR_UPDATE, G_CVAR_UPDATE, and UI_CVAR_UPDATE.
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
Definition at line 72 of file cg_syscalls.c.
{
     syscall( CG_CVAR_VARIABLESTRINGBUFFER, var_name, buffer, bufsize );
 }
References CG_CVAR_VARIABLESTRINGBUFFER, G_CVAR_VARIABLE_STRING_BUFFER, and UI_CVAR_VARIABLESTRINGBUFFER.
trap_Cvar_VariableValue()
float trap_Cvar_VariableValue (const char * var_name)
Definition at line 67 of file ui_syscalls.c.
{
     floatint_t fi;
     fi.i = syscall( UI_CVAR_VARIABLEVALUE, var_name );
     return fi.f;
 }
References floatint_t::f, floatint_t::i, and UI_CVAR_VARIABLEVALUE.
trap_Error()
void trap_Error (const char * string)
Definition at line 49 of file cg_syscalls.c.
 {
     syscall(CG_ERROR, fmt);
     // shut up GCC warning about returning functions, because we know better
     exit(1);
 }
References CG_ERROR, fmt, G_ERROR, and UI_ERROR.
trap_FS_FCloseFile()
void trap_FS_FCloseFile (fileHandle_t f)
Definition at line 100 of file cg_syscalls.c.
{
     syscall( CG_FS_FCLOSEFILE, f );
 }
References CG_FS_FCLOSEFILE, G_FS_FCLOSE_FILE, and UI_FS_FCLOSEFILE.
trap_FS_FOpenFile()
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
Definition at line 88 of file cg_syscalls.c.
{
     return syscall( CG_FS_FOPENFILE, qpath, f, mode );
 }
References CG_FS_FOPENFILE, G_FS_FOPEN_FILE, and UI_FS_FOPENFILE.
trap_FS_GetFileList()
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
Definition at line 104 of file cg_syscalls.c.
{
     return syscall( CG_FS_GETFILELIST, path, extension, listbuf, bufsize );
 }
References CG_FS_GETFILELIST, G_FS_GETFILELIST, and UI_FS_GETFILELIST.
trap_FS_Read()
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
Definition at line 92 of file cg_syscalls.c.
{
     syscall( CG_FS_READ, buffer, len, f );
 }
References CG_FS_READ, G_FS_READ, and UI_FS_READ.
trap_FS_Seek()
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
trap_FS_Write()
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
Definition at line 96 of file cg_syscalls.c.
{
     syscall( CG_FS_WRITE, buffer, len, f );
 }
References CG_FS_WRITE, G_FS_WRITE, and UI_FS_WRITE.
trap_GetClientState()
void trap_GetClientState (uiClientState_t * state)
Definition at line 229 of file ui_syscalls.c.
{
     syscall( UI_GETCLIENTSTATE, state );
 }
References UI_GETCLIENTSTATE.
Referenced by Options_MenuInit(), UI_ConfirmMenu_Style(), UI_DrawConnectScreen(), and UI_Message().
trap_GetClipboardData()
void trap_GetClipboardData (char * buf, int bufsize)
Definition at line 225 of file ui_syscalls.c.
{
     syscall( UI_GETCLIPBOARDDATA, buf, bufsize );
 }
References UI_GETCLIPBOARDDATA.
Referenced by MField_Paste().
trap_GetConfigString()
int trap_GetConfigString (int index, char * buff, int buffsize)
Definition at line 237 of file ui_syscalls.c.
{
     return syscall( UI_GETCONFIGSTRING, index, buff, buffsize );
 }
References UI_GETCONFIGSTRING.
Referenced by TeamMain_MenuInit(), and UI_ServerInfoMenu().
trap_GetGlconfig()
void trap_GetGlconfig (glconfig_t * glconfig)
Definition at line 311 of file cg_syscalls.c.
{
     syscall( CG_GETGLCONFIG, glconfig );
 }
References CG_GETGLCONFIG, and UI_GETGLCONFIG.
trap_Key_ClearStates()
void trap_Key_ClearStates (void)
Definition at line 213 of file ui_syscalls.c.
{
     syscall( UI_KEY_CLEARSTATES );
 }
References UI_KEY_CLEARSTATES.
Referenced by UI_ForceMenuOff().
trap_Key_GetBindingBuf()
void trap_Key_GetBindingBuf (int keynum, char * buf, int buflen)
Definition at line 193 of file ui_syscalls.c.
{
     syscall( UI_KEY_GETBINDINGBUF, keynum, buf, buflen );
 }
References UI_KEY_GETBINDINGBUF.
Referenced by Controls_GetKeyAssignment().
trap_Key_GetCatcher()
int trap_Key_GetCatcher (void)
Definition at line 359 of file cg_syscalls.c.
{
     return syscall( CG_KEY_GETCATCHER );
 }
References CG_KEY_GETCATCHER, and UI_KEY_GETCATCHER.
trap_Key_GetOverstrikeMode()
qboolean trap_Key_GetOverstrikeMode (void)
Definition at line 205 of file ui_syscalls.c.
{
     return syscall( UI_KEY_GETOVERSTRIKEMODE );
 }
References UI_KEY_GETOVERSTRIKEMODE.
Referenced by MainMenu_DrawName(), MField_CharEvent(), MField_Draw(), and MField_KeyDownEvent().
trap_Key_IsDown()
qboolean trap_Key_IsDown (int keynum)
Definition at line 355 of file cg_syscalls.c.
{
     return syscall( CG_KEY_ISDOWN, keynum );
 }
References CG_KEY_ISDOWN, and UI_KEY_ISDOWN.
trap_Key_KeynumToStringBuf()
void trap_Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
Definition at line 189 of file ui_syscalls.c.
{
     syscall( UI_KEY_KEYNUMTOSTRINGBUF, keynum, buf, buflen );
 }
References UI_KEY_KEYNUMTOSTRINGBUF.
Referenced by Controls_DrawKeyBinding().
trap_Key_SetBinding()
void trap_Key_SetBinding (int keynum, const char * binding)
Definition at line 197 of file ui_syscalls.c.
{
     syscall( UI_KEY_SETBINDING, keynum, binding );
 }
References UI_KEY_SETBINDING.
Referenced by Controls_MenuKey(), and Controls_SetConfig().
trap_Key_SetCatcher()
void trap_Key_SetCatcher (int catcher)
Definition at line 363 of file cg_syscalls.c.
{
     syscall( CG_KEY_SETCATCHER, catcher );
 }
References CG_KEY_SETCATCHER, and UI_KEY_SETCATCHER.
trap_Key_SetOverstrikeMode()
void trap_Key_SetOverstrikeMode (qboolean state)
Definition at line 209 of file ui_syscalls.c.
{
     syscall( UI_KEY_SETOVERSTRIKEMODE, state );
 }
References UI_KEY_SETOVERSTRIKEMODE.
Referenced by MField_KeyDownEvent().
trap_LAN_ClearPing()
void trap_LAN_ClearPing (int n)
Definition at line 277 of file ui_syscalls.c.
{
     syscall( UI_LAN_CLEARPING, n );
 }
References UI_LAN_CLEARPING.
Referenced by ArenaServers_DoRefresh(), and ArenaServers_StartRefresh().
trap_LAN_GetPing()
void trap_LAN_GetPing (int n, char * buf, int buflen, int * pingtime)
Definition at line 281 of file ui_syscalls.c.
{
     syscall( UI_LAN_GETPING, n, buf, buflen, pingtime );
 }
References UI_LAN_GETPING.
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetPingInfo()
void trap_LAN_GetPingInfo (int n, char * buf, int buflen)
Definition at line 285 of file ui_syscalls.c.
{
     syscall( UI_LAN_GETPINGINFO, n, buf, buflen );
 }
References UI_LAN_GETPINGINFO.
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetPingQueueCount()
int trap_LAN_GetPingQueueCount (void)
Definition at line 257 of file ui_syscalls.c.
{
     return syscall( UI_LAN_GETPINGQUEUECOUNT );
 }
References UI_LAN_GETPINGQUEUECOUNT.
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetServerAddressString()
void trap_LAN_GetServerAddressString (int source, int n, char * buf, int buflen)
Definition at line 245 of file ui_syscalls.c.
{
     syscall( UI_LAN_GETSERVERADDRESSSTRING, source, n, buf, buflen );
 }
References UI_LAN_GETSERVERADDRESSSTRING.
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetServerCount()
int trap_LAN_GetServerCount (int source)
Definition at line 241 of file ui_syscalls.c.
{
     return syscall( UI_LAN_GETSERVERCOUNT, source );
 }
References UI_LAN_GETSERVERCOUNT.
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetServerInfo()
void trap_LAN_GetServerInfo (int source, int n, char * buf, int buflen)
Definition at line 249 of file ui_syscalls.c.
{
     syscall( UI_LAN_GETSERVERINFO, source, n, buf, buflen );
 }
References UI_LAN_GETSERVERINFO.
trap_LAN_ServerStatus()
int trap_LAN_ServerStatus (const char * serverAddress, char * serverStatus, int maxLen)
Definition at line 261 of file ui_syscalls.c.
{
     return syscall( UI_LAN_SERVERSTATUS, serverAddress, serverStatus, maxLen );
 }
References UI_LAN_SERVERSTATUS.
trap_MemoryRemaining()
int trap_MemoryRemaining (void)
Definition at line 351 of file cg_syscalls.c.
{
     return syscall( CG_MEMORY_REMAINING );
 }
References CG_MEMORY_REMAINING, and UI_MEMORY_REMAINING.
trap_Milliseconds()
int trap_Milliseconds (void)
Definition at line 56 of file cg_syscalls.c.
{
     return syscall( CG_MILLISECONDS );
 }
References CG_MILLISECONDS, G_MILLISECONDS, and UI_MILLISECONDS.
trap_Print()
void trap_Print (const char * string)
Definition at line 45 of file cg_syscalls.c.
{
     syscall( CG_PRINT, fmt );
 }
References CG_PRINT, fmt, and UI_PRINT.
trap_R_AddLightToScene()
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
Definition at line 277 of file cg_syscalls.c.
{
     syscall( CG_R_ADDLIGHTTOSCENE, org, PASSFLOAT(intensity), PASSFLOAT(r), PASSFLOAT(g), PASSFLOAT(b) );
 }
References CG_R_ADDLIGHTTOSCENE, PASSFLOAT(), and UI_R_ADDLIGHTTOSCENE.
trap_R_AddPolyToScene()
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
Definition at line 261 of file cg_syscalls.c.
{
     syscall( CG_R_ADDPOLYTOSCENE, hShader, numVerts, verts );
 }
References CG_R_ADDPOLYTOSCENE, numVerts, and UI_R_ADDPOLYTOSCENE.
trap_R_AddRefEntityToScene()
void trap_R_AddRefEntityToScene (const refEntity_t * re)
Definition at line 257 of file cg_syscalls.c.
{
     syscall( CG_R_ADDREFENTITYTOSCENE, re );
 }
References CG_R_ADDREFENTITYTOSCENE, re, and UI_R_ADDREFENTITYTOSCENE.
trap_R_ClearScene()
void trap_R_ClearScene (void)
Definition at line 253 of file cg_syscalls.c.
{
     syscall( CG_R_CLEARSCENE );
 }
References CG_R_CLEARSCENE, and UI_R_CLEARSCENE.
trap_R_DrawStretchPic()
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Definition at line 293 of file cg_syscalls.c.
{
     syscall( CG_R_DRAWSTRETCHPIC, PASSFLOAT(x), PASSFLOAT(y), PASSFLOAT(w), PASSFLOAT(h), PASSFLOAT(s1), PASSFLOAT(t1), PASSFLOAT(s2), PASSFLOAT(t2), hShader );
 }
References CG_R_DRAWSTRETCHPIC, PASSFLOAT(), and UI_R_DRAWSTRETCHPIC.
trap_R_RegisterModel()
qhandle_t trap_R_RegisterModel (const char * name)
Definition at line 233 of file cg_syscalls.c.
{
     return syscall( CG_R_REGISTERMODEL, name );
 }
References CG_R_REGISTERMODEL, and UI_R_REGISTERMODEL.
trap_R_RegisterShaderNoMip()
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
Definition at line 245 of file cg_syscalls.c.
{
     return syscall( CG_R_REGISTERSHADERNOMIP, name );
 }
References CG_R_REGISTERSHADERNOMIP, and UI_R_REGISTERSHADERNOMIP.
trap_R_RegisterSkin()
qhandle_t trap_R_RegisterSkin (const char * name)
Definition at line 237 of file cg_syscalls.c.
{
     return syscall( CG_R_REGISTERSKIN, name );
 }
References CG_R_REGISTERSKIN, and UI_R_REGISTERSKIN.
trap_R_RenderScene()
void trap_R_RenderScene (const refdef_t * fd)
Definition at line 285 of file cg_syscalls.c.
{
     syscall( CG_R_RENDERSCENE, fd );
 }
References CG_R_RENDERSCENE, and UI_R_RENDERSCENE.
trap_R_SetColor()
void trap_R_SetColor (const float * rgba)
Definition at line 289 of file cg_syscalls.c.
{
     syscall( CG_R_SETCOLOR, rgba );
 }
References CG_R_SETCOLOR, and UI_R_SETCOLOR.
trap_S_RegisterSound()
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
Definition at line 221 of file cg_syscalls.c.
{
     return syscall(CG_S_REGISTERSOUND,sample,compressed);
 }
References CG_S_REGISTERSOUND, and UI_S_REGISTERSOUND.
trap_S_StartBackgroundTrack()
void trap_S_StartBackgroundTrack (const char * intro, const char * loop)
Definition at line 225 of file cg_syscalls.c.
{
     syscall( CG_S_STARTBACKGROUNDTRACK, intro, loop );
 }
References CG_S_STARTBACKGROUNDTRACK, and UI_S_STARTBACKGROUNDTRACK.
trap_S_StartLocalSound()
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
Definition at line 193 of file cg_syscalls.c.
{
     syscall( CG_S_STARTLOCALSOUND, sfx, channelNum );
 }
References CG_S_STARTLOCALSOUND, and UI_S_STARTLOCALSOUND.
trap_S_StopBackgroundTrack()
void trap_S_StopBackgroundTrack (void)
Definition at line 391 of file cg_syscalls.c.
{
     syscall( CG_S_STOPBACKGROUNDTRACK );
 }
References CG_S_STOPBACKGROUNDTRACK, and UI_S_STOPBACKGROUNDTRACK.
trap_UpdateScreen()
void trap_UpdateScreen (void)
Definition at line 124 of file cg_syscalls.c.
{
     syscall( CG_UPDATESCREEN );
 }
References CG_UPDATESCREEN, and UI_UPDATESCREEN.
UI_AdjustFrom640()
void UI_AdjustFrom640 (float * x, float * y, float * w, float * h)
Definition at line 984 of file ui_atoms.c.
{
     qboolean stretch = qtrue;
     *x *= uis.scaleX;
     *y *= uis.scaleY;
     *w *= stretch ? uis.scaleX : 1.6;
     *h *= stretch ? uis.scaleY : 1.6;
 }
References qtrue, uiStatic_t::scaleX, uiStatic_t::scaleY, and uis.
Referenced by UI_DrawBackPic(), UI_DrawConnectScreen(), UI_DrawHandlePic(), UI_DrawNamedPic(), UI_DrawPlayer(), UI_DrawRect(), UI_FillRect(), UI_MenuLogo(), and UI_MenuScene().
UI_ArenaServersMenu()
void UI_ArenaServersMenu (void)
Definition at line 1517 of file ui_servers2.c.
{
     //trap_S_StopBackgroundTrack();
     //trap_S_StartBackgroundTrack("music/yamamoto/menu02.ogg", "music/yamamoto/menu02.ogg");
     ArenaServers_MenuInit();
     UI_PushMenu( &g_arenaservers.menu );
 }
References ArenaServers_MenuInit(), g_arenaservers, arenaservers_t::menu, and UI_PushMenu().
Referenced by Main_MenuEvent().
UI_Argv()
char* UI_Argv (int arg)
Definition at line 918 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Argv( arg, buffer, sizeof( buffer ) );
     return buffer;
 }
References MAX_STRING_CHARS, and trap_Argv().
UI_CameraMenu()
void UI_CameraMenu (void)
Definition at line 297 of file ui_camera.c.
{
     Camera_MenuInit();
     UI_PushMenu( &s_camera.menu );
 }
References Camera_MenuInit(), camera_t::menu, s_camera, and UI_PushMenu().
Referenced by InGame_Event().
UI_ClampCvar()
float UI_ClampCvar (float min, float max, float value)
Definition at line 60 of file ui_atoms.c.
 {
     if ( value < min ) return min;
     if ( value > max ) return max;
     return value;
 }
Referenced by Camera_GetConfig().
UI_ConfirmMenu()
void UI_ConfirmMenu (const char * question, void(*)(void) draw, void(*)(qboolean result) action)
Definition at line 243 of file ui_confirm.c.
{
     UI_ConfirmMenu_Style(question, UI_CENTER|UI_INVERSE, draw, action);
 }
References UI_CENTER, UI_ConfirmMenu_Style(), and UI_INVERSE.
Referenced by InGame_Event().
UI_ConfirmMenu_Style()
void UI_ConfirmMenu_Style (const char * question, int style, void(*)(void) draw, void(*)(qboolean result) action)
Definition at line 174 of file ui_confirm.c.
{
     uiClientState_t cstate;
     int n1, n2, n3;
     int l1, l2, l3;
     uis.menuamount = 0;
     // zero set all our globals
     memset( &s_confirm, 0, sizeof(s_confirm) );
     ConfirmMenu_Cache();
     n1 = UI_ProportionalStringWidth( "YES/NO" );
     n2 = UI_ProportionalStringWidth( "YES" ) + PROP_GAP_WIDTH;
     n3 = UI_ProportionalStringWidth( "/" )  + PROP_GAP_WIDTH;
     l1 = 320 - ( n1 / 2 );
     l2 = l1 + n2;
     l3 = l2 + n3;
     s_confirm.slashX = l2;
     s_confirm.question = question;
     s_confirm.draw = draw;
     s_confirm.action = action;
     s_confirm.style = style;
     s_confirm.menu.draw       = ConfirmMenu_Draw;
     s_confirm.menu.key        = ConfirmMenu_Key;
     s_confirm.menu.wrapAround = qtrue;
     trap_GetClientState( &cstate );
     if ( cstate.connState >= CA_CONNECTED ) {
         s_confirm.menu.fullscreen = qfalse;
     }
     else {
         s_confirm.menu.fullscreen = qtrue;
     }
     s_confirm.yes.generic.type      = MTYPE_PTEXT;
     s_confirm.yes.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.yes.generic.callback  = ConfirmMenu_Event;
     s_confirm.yes.generic.id        = ID_CONFIRM_YES;
     s_confirm.yes.generic.x         = l1;
     s_confirm.yes.generic.y         = 264;
     s_confirm.yes.string            = "YES";
     s_confirm.yes.color             = color_white;
     s_confirm.yes.style             = UI_LEFT|UI_DROPSHADOW;
     s_confirm.no.generic.type       = MTYPE_PTEXT;
     s_confirm.no.generic.flags      = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.no.generic.callback   = ConfirmMenu_Event;
     s_confirm.no.generic.id         = ID_CONFIRM_NO;
     s_confirm.no.generic.x          = l3;
     s_confirm.no.generic.y          = 264;
     s_confirm.no.string             = "NO";
     s_confirm.no.color              = color_white;
     s_confirm.no.style              = UI_LEFT|UI_DROPSHADOW;
     Menu_AddItem( &s_confirm.menu,  &s_confirm.yes );
     Menu_AddItem( &s_confirm.menu,  &s_confirm.no );
     UI_PushMenu( &s_confirm.menu );
     Menu_SetCursorToItem( &s_confirm.menu, &s_confirm.no );
 }
References confirmMenu_t::action, CA_CONNECTED, menucommon_s::callback, menutext_s::color, color_white, ConfirmMenu_Cache(), ConfirmMenu_Draw(), ConfirmMenu_Event(), ConfirmMenu_Key(), uiClientState_t::connState, confirmMenu_t::draw, menucommon_s::flags, menutext_s::generic, menucommon_s::id, ID_CONFIRM_NO, ID_CONFIRM_YES, confirmMenu_t::menu, Menu_AddItem(), Menu_SetCursorToItem(), uiStatic_t::menuamount, MTYPE_PTEXT, confirmMenu_t::no, PROP_GAP_WIDTH, qfalse, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, confirmMenu_t::question, s_confirm, confirmMenu_t::slashX, menutext_s::string, confirmMenu_t::style, menutext_s::style, trap_GetClientState(), menucommon_s::type, UI_DROPSHADOW, UI_LEFT, UI_ProportionalStringWidth(), UI_PushMenu(), uis, menucommon_s::x, menucommon_s::y, and confirmMenu_t::yes.
Referenced by UI_ConfirmMenu().
UI_ConsoleCommand()
qboolean UI_ConsoleCommand (int realTime)
Definition at line 950 of file ui_atoms.c.
{
     char    *cmd;
     //cmd = UI_Argv(0);
     //Menu_Cache();
     return qfalse;
 }
References qfalse.
Referenced by vmMain().
UI_ControlsMenu()
void UI_ControlsMenu (void)
Definition at line 1197 of file ui_controls2.c.
{
     Controls_MenuInit();
     uis.menuamount = 4;
     uis.hideEarth = qtrue;
     uis.showFrame = qtrue;
     UI_PushMenu( &s_controls.menu );
     Menu_SetCursorToItem(&s_controls.menu,&s_controls.controls);
 }
References controls_t::controls, Controls_MenuInit(), uiStatic_t::hideEarth, controls_t::menu, Menu_SetCursorToItem(), uiStatic_t::menuamount, qtrue, s_controls, uiStatic_t::showFrame, UI_PushMenu(), and uis.
Referenced by Main_MenuEvent(), Preferences_Event(), and SystemSettings_Event().
UI_CreditMenu()
void UI_CreditMenu (void)
Definition at line 107 of file ui_credits.c.
{
     uis.menuamount = 0;
     trap_S_StopBackgroundTrack();
     trap_S_StartBackgroundTrack("music/credits.ogg", "music/credits.ogg");
     trap_S_StartLocalSound( menu_exit_sound, CHAN_LOCAL_SOUND );
     memset( &s_credits, 0 ,sizeof(s_credits) );
     s_credits.menu.draw = UI_CreditMenu_Draw;
     s_credits.menu.key = UI_CreditMenu_Key;
     s_credits.menu.fullscreen = qtrue;
     UI_PushMenu ( &s_credits.menu );
 }
References CHAN_LOCAL_SOUND, creditsmenu_t::menu, menu_exit_sound, uiStatic_t::menuamount, qtrue, s_credits, trap_S_StartBackgroundTrack(), trap_S_StartLocalSound(), trap_S_StopBackgroundTrack(), UI_CreditMenu_Draw(), UI_CreditMenu_Key(), UI_PushMenu(), and uis.
Referenced by InGame_QuitAction(), and Main_MenuEvent().
UI_CursorInRect()
qboolean UI_CursorInRect (int x, int y, int width, int height)
Definition at line 1287 of file ui_atoms.c.
 {
     if (uis.cursorx < x ||
         uis.cursory < y ||
         uis.cursorx > x+width ||
         uis.cursory > y+height)
         return qfalse;
     return qtrue;
 }
References uiStatic_t::cursorx, uiStatic_t::cursory, qfalse, qtrue, and uis.
Referenced by ScrollList_Key().
UI_Cvar_VariableString()
char* UI_Cvar_VariableString (const char * var_name)
Definition at line 927 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Cvar_VariableStringBuffer( var_name, buffer, sizeof( buffer ) );
     return buffer;
 }
References MAX_STRING_CHARS, and trap_Cvar_VariableStringBuffer().
Referenced by Controls_InitModel(), StartServer_SetMenuItems(), SystemSettings_GetResolutions(), SystemSettings_SetMenuItems(), and UI_MainMenu().
UI_DrawBackPic()
void UI_DrawBackPic (qboolean drawPic)
Definition at line 1231 of file ui_atoms.c.
{
     float x, y, w, h;
     if (!drawPic) {
         UI_FillRect(0, 0, 640, 480, colorBlack);
     }
     else {
         x = 0;
         y = 0;
         w = 640;
         h = 480;
         UI_AdjustFrom640(&x, &y, &w, &h);
         trap_R_DrawStretchPic(x, y, w, h, 0, 0, 1, 768.0/1024.0, uis.menuBackShader);
     }
 }
References colorBlack, uiStatic_t::menuBackShader, trap_R_DrawStretchPic(), UI_AdjustFrom640(), UI_FillRect(), and uis.
Referenced by UI_DrawConnectScreen().
UI_DrawBannerString()
void UI_DrawBannerString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 659 of file cg_drawtools.c.
{
     const char *    s;
     int             ch;
     int             width;
     vec4_t          drawcolor;
     // find the width of the drawn text
     s = str;
     width = 0;
     while ( *s ) {
         ch = *s;
         if ( ch == ' ' ) {
             width += PROPB_SPACE_WIDTH;
         }
         else if ( ch >= 'A' && ch <= 'Z' ) {
             width += propMapB[ch - 'A'][2] + PROPB_GAP_WIDTH;
         }
         s++;
     }
     width -= PROPB_GAP_WIDTH;
     switch( style & UI_FORMATMASK ) {
         case UI_CENTER:
             x -= width / 2;
             break;
         case UI_RIGHT:
             x -= width;
             break;
         case UI_LEFT:
         default:
             break;
     }
     if ( style & UI_DROPSHADOW ) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawBannerString2( x+1, y+1, str, drawcolor );
     }
     UI_DrawBannerString2( x, y, str, color );
 }
References PROPB_GAP_WIDTH, PROPB_SPACE_WIDTH, propMapB, UI_CENTER, UI_DrawBannerString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_LEFT, and UI_RIGHT.
Referenced by BText_Draw().
UI_DrawChar()
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
Definition at line 790 of file ui_atoms.c.
 {
     char    buff[2];
     buff[0] = ch;
     buff[1] = '\0';
     UI_DrawString( x, y, buff, style, color );
 }
References UI_DrawString().
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MainMenu_DrawName(), MenuField_Draw(), MField_Draw(), RadioButton_Draw(), and SpinControl_Draw().
UI_DrawConnectScreen()
void UI_DrawConnectScreen (qboolean overlay)
Definition at line 162 of file ui_connect.c.
{
     char            *s;
     float x,y,w,h;
     qhandle_t       text,dots;
     uiClientState_t cstate;
     char            info[MAX_INFO_VALUE];
     Menu_Cache();
     if(!overlay){
         UI_SetColor( color_white );
         UI_DrawBackPic(qtrue);
         UI_MenuScene();
     }
     trap_GetClientState( &cstate );
     info[0] = '\0';
 #if 0
     // display password field
     if ( passwordNeeded ) {
         s_ingame_menu.x = SCREEN_WIDTH * 0.50 - 128;
         s_ingame_menu.nitems = 0;
         s_ingame_menu.wrapAround = qtrue;
         passwordField.generic.type = MTYPE_FIELD;
         passwordField.generic.name = "Password:";
         passwordField.generic.callback = 0;
         passwordField.generic.x     = 10;
         passwordField.generic.y     = 180;
         Field_Clear( &passwordField.field );
         passwordField.width = 256;
         passwordField.field.widthInChars = 16;
         Q_strncpyz( passwordField.field.buffer, Cvar_VariableString("password"),
             sizeof(passwordField.field.buffer) );
         Menu_AddItem( &s_ingame_menu, ( void * ) &s_customize_player_action );
         MField_Draw( &passwordField );
     }
 #endif
     if ( lastConnState > cstate.connState ) {
         lastLoadingText[0] = '\0';
     }
     lastConnState = cstate.connState;
     text = trap_R_RegisterShaderNoMip("connecting");
     dots = trap_R_RegisterShaderNoMip("dots");
     x = 0;
     y = 18;
     w = 127;
     h = 64;
     UI_AdjustFrom640(&x,&y,&w,&h);
     switch ( cstate.connState ) {
         case CA_CONNECTING:
             text = trap_R_RegisterShaderNoMip("searching");
             trap_R_DrawStretchPic(x,y,w,h, 0, 0, 1, 1, text);
             x = 70;
             y = 52;
             w = 8;
             h = 4;
             break;
         case CA_CHALLENGING:
             trap_R_DrawStretchPic(x,y,w,h, 0, 0, 1, 1, text);
             x = -100;
             y = -100;
             w = 0;
             h = 0;
             break;
         case CA_CONNECTED: {
             char downloadName[MAX_INFO_VALUE];
                 trap_Cvar_VariableStringBuffer( "cl_downloadName", downloadName, sizeof(downloadName) );
                 if (*downloadName) {
                     UI_DisplayDownloadInfo( downloadName );
                     return;
                 }
             }
             trap_R_DrawStretchPic(x,y,w,h, 0, 0, 1, 1, text);
             x = -100;
             y = -100;
             w = 0;
             h = 0;
             break;
         break;
     default:
         return;
     }
     UI_AdjustFrom640(&x,&y,&w,&h);
     trap_R_DrawStretchPic(x,y,w,h, 0, 0, 1, 1, dots);
     //UI_DrawProportionalString( 320, 128, s, UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW, color_white );
     // password required / connection rejected information goes here
 }
References mfield_t::buffer, CA_CHALLENGING, CA_CONNECTED, CA_CONNECTING, menucommon_s::callback, color_white, uiClientState_t::connState, Cvar_VariableString(), menufield_s::field, Field_Clear(), menufield_s::generic, info, lastConnState, lastLoadingText, MAX_INFO_VALUE, Menu_AddItem(), Menu_Cache(), MField_Draw(), MTYPE_FIELD, menucommon_s::name, passwordField, passwordNeeded, Q_strncpyz(), qtrue, SCREEN_WIDTH, trap_Cvar_VariableStringBuffer(), trap_GetClientState(), trap_R_DrawStretchPic(), trap_R_RegisterShaderNoMip(), menucommon_s::type, UI_AdjustFrom640(), UI_DisplayDownloadInfo(), UI_DrawBackPic(), UI_MenuScene(), UI_SetColor(), mfield_t::widthInChars, menucommon_s::x, and menucommon_s::y.
Referenced by vmMain().
UI_DrawHandlePic()
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
Definition at line 998 of file ui_atoms.c.
{
     float   s0;
     float   s1;
     float   t0;
     float   t1;
     if( w < 0 ) {   // flip about vertical
         w  = -w;
         s0 = 1;
         s1 = 0;
     }
     else {
         s0 = 0;
         s1 = 1;
     }
     if( h < 0 ) {   // flip about horizontal
         h  = -h;
         t0 = 1;
         t1 = 0;
     }
     else {
         t0 = 0;
         t1 = 1;
     }
     UI_AdjustFrom640( &x, &y, &w, &h );
     trap_R_DrawStretchPic( x, y, w, h, s0, t0, s1, t1, hShader );
 }
References trap_R_DrawStretchPic(), and UI_AdjustFrom640().
Referenced by Bitmap_Draw(), Crosshair_Draw(), Main_MenuDraw(), Menu_Common(), Menu_Frame(), RadioButton_Draw(), Slider_Draw(), StartServer_LevelshotDraw(), and UI_Refresh().
UI_DrawNamedPic()
void UI_DrawNamedPic (float x, float y, float width, float height, const char * picname)
Definition at line 992 of file ui_atoms.c.
{
     qhandle_t   hShader;
     hShader = trap_R_RegisterShaderNoMip( picname );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
References trap_R_DrawStretchPic(), trap_R_RegisterShaderNoMip(), and UI_AdjustFrom640().
Referenced by ConfirmMenu_Draw(), and MessageMenu_Draw().
UI_DrawPlayer()
void UI_DrawPlayer (float x, float y, float w, float h, playerInfo_t * pi, int time)
Definition at line 843 of file ui_players.c.
{
     refdef_t        refdef;
     refEntity_t     legs;
     refEntity_t     torso;
     refEntity_t     head;
     refEntity_t     gun;
     refEntity_t     barrel;
     refEntity_t     flash;
     vec3_t          origin;
     int             renderfx;
     vec3_t          mins = {-16, -16, -24};
     vec3_t          maxs = {16, 16, 32};
     float           len;
     float           xx;
     if ( !pi->legsModel || !pi->torsoModel || !pi->headModel || !pi->animations[0].numFrames ) {
         return;
     }
     dp_realtime = time;
     if ( pi->pendingWeapon != -1 && dp_realtime > pi->weaponTimer ) {
         pi->weapon = pi->pendingWeapon;
         pi->lastWeapon = pi->pendingWeapon;
         pi->pendingWeapon = -1;
         pi->weaponTimer = 0;
     }
     UI_AdjustFrom640( &x, &y, &w, &h );
     y -= jumpHeight;
     memset( &refdef, 0, sizeof( refdef ) );
     memset( &legs, 0, sizeof(legs) );
     memset( &torso, 0, sizeof(torso) );
     memset( &head, 0, sizeof(head) );
     refdef.rdflags = RDF_NOWORLDMODEL;
     AxisClear( refdef.viewaxis );
     refdef.x = x;
     refdef.y = y;
     refdef.width = w;
     refdef.height = h;
     refdef.fov_x = (int)((float)refdef.width / 640.0f * 35.0f);
     xx = refdef.width / tan( refdef.fov_x / 360 * M_PI );
     refdef.fov_y = atan2( refdef.height, xx );
     refdef.fov_y *= ( 360 / M_PI );
     // calculate distance so the player nearly fills the box
     len = 0.6 * ( maxs[2] - mins[2] );
     origin[0] = len / tan( DEG2RAD(refdef.fov_x) * 0.5 );
     origin[1] = 0.5 * ( mins[1] + maxs[1] );
     origin[2] = -0.5 * ( mins[2] + maxs[2] );
     refdef.time = dp_realtime;
     trap_R_ClearScene();
     // get the rotation information
     UI_PlayerAngles( pi, legs.axis, torso.axis, head.axis );
     // get the animation state (after rotation, to allow feet shuffle)
     UI_PlayerAnimation( pi, &legs.oldframe, &legs.frame, &legs.backlerp,
          &torso.oldframe, &torso.frame, &torso.backlerp,
          &head.oldframe, &head.frame, &head.backlerp);
     renderfx = RF_LIGHTING_ORIGIN | RF_NOSHADOW;
     //
     // add the legs
     //
     legs.hModel = pi->legsModel;
     legs.customSkin = pi->legsSkin;
     VectorCopy( origin, legs.origin );
     VectorCopy( origin, legs.lightingOrigin );
     legs.renderfx = renderfx;
     VectorCopy (legs.origin, legs.oldorigin);
     trap_R_AddRefEntityToScene( &legs );
     if (!legs.hModel) {
         return;
     }
     //
     // add the torso
     //
     torso.hModel = pi->torsoModel;
     if (!torso.hModel) {
         return;
     }
     torso.customSkin = pi->torsoSkin;
     VectorCopy( origin, torso.lightingOrigin );
     UI_PositionRotatedEntityOnTag( &torso, &legs, pi->legsModel, "tag_torso");
     torso.renderfx = renderfx;
     trap_R_AddRefEntityToScene( &torso );
     //
     // add the head
     //
     head.hModel = pi->headModel;
     if (!head.hModel) {
         return;
     }
     head.customSkin = pi->headSkin;
     VectorCopy( origin, head.lightingOrigin );
     UI_PositionRotatedEntityOnTag( &head, &torso, pi->torsoModel, "tag_head");
     head.renderfx = renderfx;
     trap_R_AddRefEntityToScene( &head );
 /*
     //
     // add the gun
     //
     if ( pi->currentWeapon != WP_NONE ) {
         memset( &gun, 0, sizeof(gun) );
         gun.hModel = pi->weaponModel;
         VectorCopy( origin, gun.lightingOrigin );
         UI_PositionEntityOnTag( &gun, &torso, pi->torsoModel, "tag_weapon");
         gun.renderfx = renderfx;
         trap_R_AddRefEntityToScene( &gun );
     }
     //
     // add the spinning barrel
     //
     if ( pi->realWeapon == WP_MACHINEGUN || pi->realWeapon == WP_GAUNTLET || pi->realWeapon == WP_BFG ) {
         vec3_t  angles;
         memset( &barrel, 0, sizeof(barrel) );
         VectorCopy( origin, barrel.lightingOrigin );
         barrel.renderfx = renderfx;
         barrel.hModel = pi->barrelModel;
         angles[YAW] = 0;
         angles[PITCH] = 0;
         angles[ROLL] = UI_MachinegunSpinAngle( pi );
         if( pi->realWeapon == WP_GAUNTLET || pi->realWeapon == WP_BFG ) {
             angles[PITCH] = angles[ROLL];
             angles[ROLL] = 0;
         }
         AnglesToAxis( angles, barrel.axis );
         UI_PositionRotatedEntityOnTag( &barrel, &gun, pi->weaponModel, "tag_barrel");
         trap_R_AddRefEntityToScene( &barrel );
     }
     //
     // add muzzle flash
     //
     if ( dp_realtime <= pi->muzzleFlashTime ) {
         if ( pi->flashModel ) {
             memset( &flash, 0, sizeof(flash) );
             flash.hModel = pi->flashModel;
             VectorCopy( origin, flash.lightingOrigin );
             UI_PositionEntityOnTag( &flash, &gun, pi->weaponModel, "tag_flash");
             flash.renderfx = renderfx;
             trap_R_AddRefEntityToScene( &flash );
         }
         // make a dlight for the flash
         if ( pi->flashDlightColor[0] || pi->flashDlightColor[1] || pi->flashDlightColor[2] ) {
             trap_R_AddLightToScene( flash.origin, 200 + (rand()&31), pi->flashDlightColor[0],
                 pi->flashDlightColor[1], pi->flashDlightColor[2] );
         }
     }
 */
     //
     // add the chat icon
     //
     if ( pi->chat ) {
         UI_PlayerFloatSprite( pi, origin, trap_R_RegisterShaderNoMip( "chatBubble" ) );
     }
     //
     // add an accent light
     //
     origin[0] -= 0;//100;   // + = behind, - = in front
     origin[1] += 100;   // + = left, - = right
     origin[2] += 0;//100;   // + = above, - = below
     trap_R_AddLightToScene( origin, 500, 1.0, 1.0, 1.0 );
 /*
     origin[0] -= 100;
     origin[1] -= 100;
     origin[2] -= 100;
     trap_R_AddLightToScene( origin, 500, 1.0, 0.0, 0.0 );
 */
     trap_R_RenderScene( &refdef );
 }
References playerInfo_t::animations, refEntity_t::axis, AxisClear(), refEntity_t::backlerp, playerInfo_t::chat, refEntity_t::customSkin, DEG2RAD, dp_realtime, refdef_t::fov_x, refdef_t::fov_y, refEntity_t::frame, head, playerInfo_t::headModel, playerInfo_t::headSkin, refdef_t::height, refEntity_t::hModel, int(), jumpHeight, playerInfo_t::lastWeapon, playerInfo_t::legsModel, playerInfo_t::legsSkin, refEntity_t::lightingOrigin, M_PI, refEntity_t::oldframe, refEntity_t::oldorigin, refEntity_t::origin, playerInfo_t::pendingWeapon, RDF_NOWORLDMODEL, refdef_t::rdflags, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, RF_NOSHADOW, refdef_t::time, playerInfo_t::torsoModel, playerInfo_t::torsoSkin, trap_R_AddLightToScene(), trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RegisterShaderNoMip(), trap_R_RenderScene(), UI_AdjustFrom640(), UI_PlayerAngles(), UI_PlayerAnimation(), UI_PlayerFloatSprite(), UI_PositionRotatedEntityOnTag(), VectorCopy, refdef_t::viewaxis, playerInfo_t::weapon, playerInfo_t::weaponTimer, refdef_t::width, refdef_t::x, xx, and refdef_t::y.
Referenced by Controls_DrawPlayer(), MainMenu_DrawPlayer(), and PlayerModel_DrawPlayer().
UI_DrawProportionalString()
void UI_DrawProportionalString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 789 of file cg_drawtools.c.
{
     vec4_t  drawcolor;
     int     width;
     float   sizeScale;
     sizeScale = UI_ProportionalSizeScale( style );
     switch( style & UI_FORMATMASK ) {
         case UI_CENTER:
             width = UI_ProportionalStringWidth( str ) * sizeScale;
             x -= width / 2;
             break;
         case UI_RIGHT:
             width = UI_ProportionalStringWidth( str ) * sizeScale;
             x -= width;
             break;
         case UI_LEFT:
         default:
             break;
     }
     if ( style & UI_DROPSHADOW ) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x+1, y+1, str, drawcolor, sizeScale, cgs.media.charsetProp );
     }
     if ( style & UI_INVERSE ) {
         drawcolor[0] = color[0] * 0.8;
         drawcolor[1] = color[1] * 0.8;
         drawcolor[2] = color[2] * 0.8;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x, y, str, drawcolor, sizeScale, cgs.media.charsetProp );
         return;
     }
     if ( style & UI_PULSE ) {
         drawcolor[0] = color[0] * 0.8;
         drawcolor[1] = color[1] * 0.8;
         drawcolor[2] = color[2] * 0.8;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x, y, str, color, sizeScale, cgs.media.charsetProp );
         drawcolor[0] = color[0];
         drawcolor[1] = color[1];
         drawcolor[2] = color[2];
         drawcolor[3] = 0.5 + 0.5 * sin( cg.time / PULSE_DIVISOR );
         UI_DrawProportionalString2( x, y, str, drawcolor, sizeScale, cgs.media.charsetPropGlow );
         return;
     }
     UI_DrawProportionalString2( x, y, str, color, sizeScale, cgs.media.charsetProp );
 }
References cg, cgs, uiStatic_t::charsetProp, cgMedia_t::charsetProp, cgMedia_t::charsetPropGlow, cgs_t::media, PULSE_DIVISOR, cg_t::time, UI_CENTER, UI_DrawProportionalString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_INVERSE, UI_LEFT, UI_ProportionalSizeScale(), UI_ProportionalStringWidth(), UI_PULSE, UI_RIGHT, and uis.
Referenced by ConfirmMenu_Draw(), Controls_ResetDefaults_Draw(), MessageMenu_Draw(), PlayerModel_DrawPlayer(), PText_Draw(), UI_CreditMenu_Draw(), and UI_DisplayDownloadInfo().
UI_DrawProportionalString_AutoWrapped()
void UI_DrawProportionalString_AutoWrapped (int x, int ystart, int xmax, int ystep, const char * str, int style, vec4_t color)
UI_DrawRect()
void UI_DrawRect (float x, float y, float width, float height, const float * color)
Definition at line 1051 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, 1, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x, y, 1, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x, y + height - 1, width, 1, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x + width - 1, y, 1, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_SetColor( NULL );
 }
References NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), UI_AdjustFrom640(), uis, and uiStatic_t::whiteShader.
Referenced by Menu_Draw(), and UI_DrawTextBox().
UI_DrawString()
void UI_DrawString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 707 of file ui_atoms.c.
 {
     int     len;
     int     charw;
     int     charh;
     vec4_t  newcolor;
     vec4_t  lowlight;
     float   *drawcolor;
     vec4_t  dropcolor;
     if( !str ) {
         return;
     }
     if ((style & UI_BLINK) && ((uis.realtime/BLINK_DIVISOR) & 1))
         return;
     if (style & UI_SMALLFONT)
     {
         charw = SMALLCHAR_WIDTH;
         charh = SMALLCHAR_HEIGHT;
     }
     else if (style & UI_TINYFONT)
     {
         charw = 6;
         charh = 12;
     }
     else if (style & UI_GIANTFONT)
     {
         charw = GIANTCHAR_WIDTH;
         charh = GIANTCHAR_HEIGHT;
     }
     else
     {
         charw = BIGCHAR_WIDTH;
         charh = BIGCHAR_HEIGHT;
     }
     drawcolor = color;
     switch (style & UI_FORMATMASK)
     {
         case UI_CENTER:
             // center justify at x
             // JUHOX: use UI_DrawStrlen() instead of strlen
 #if 0
             len = strlen(str);
 #else
             len = UI_DrawStrlen(str);
 #endif
             x   = x - len*(charw*0.7)/2;
             break;
         case UI_RIGHT:
             // right justify at x
             // JUHOX: use UI_DrawStrlen() instead of strlen
 #if 0
             len = strlen(str);
 #else
             len = UI_DrawStrlen(str);
 #endif
             x   = x - len*(charw*0.7);
             break;
         default:
             // left justify at x
             break;
     }
     if ( style & UI_DROPSHADOW )
     {
         dropcolor[0] = dropcolor[1] = dropcolor[2] = 0;
         dropcolor[3] = 0.7;
         UI_DrawString2(x+1,y+1,str,dropcolor,charw,charh);
     }
     UI_DrawString2(x,y,str,drawcolor,charw,charh);
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, BLINK_DIVISOR, GIANTCHAR_HEIGHT, GIANTCHAR_WIDTH, uiStatic_t::realtime, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, UI_BLINK, UI_CENTER, UI_DrawString2(), UI_DrawStrlen(), UI_DROPSHADOW, UI_FORMATMASK, UI_GIANTFONT, UI_RIGHT, UI_SMALLFONT, UI_TINYFONT, and uis.
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), MField_Draw(), RadioButton_Draw(), ScrollList_Draw(), ServerInfo_MenuDraw(), Slider_Draw(), SpinControl_Draw(), StartServer_LevelshotDraw(), Text_Draw(), UI_DrawChar(), and UI_Refresh().
UI_DrawStrlen()
int UI_DrawStrlen (const char * str)
Definition at line 686 of file ui_atoms.c.
{
     const char *s = str;
     int count = 0;
     while (*s) {
         if (Q_IsColorString(s)) {
             s += 2;
         } else {
             count++;
             s++;
         }
     }
     return count;
 }
References Q_IsColorString.
Referenced by UI_DrawString().
UI_DrawTextBox()
void UI_DrawTextBox (int x, int y, int width, int lines)
Definition at line 1281 of file ui_atoms.c.
 {
     UI_FillRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorBlack );
     UI_DrawRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorWhite );
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, colorBlack, colorWhite, UI_DrawRect(), and UI_FillRect().
UI_FillRect()
void UI_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 1035 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_SetColor( NULL );
 }
References NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), UI_AdjustFrom640(), uis, and uiStatic_t::whiteShader.
Referenced by Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), ScrollList_Draw(), StartServer_LevelshotDraw(), UI_DrawBackPic(), and UI_DrawTextBox().
UI_ForceMenuOff()
void UI_ForceMenuOff (void)
Definition at line 151 of file ui_atoms.c.
 {
     uis.menusp     = 0;
     uis.activemenu = NULL;
     trap_Key_SetCatcher( trap_Key_GetCatcher() & ~KEYCATCH_UI );
     trap_Key_ClearStates();
     trap_Cvar_Set( "cl_paused", "0" );
 }
References uiStatic_t::activemenu, KEYCATCH_UI, uiStatic_t::menusp, NULL, trap_Cvar_Set(), trap_Key_ClearStates(), trap_Key_GetCatcher(), trap_Key_SetCatcher(), and uis.
Referenced by SystemSettings_Event(), TeamMain_MenuEvent(), UI_PopMenu(), and UI_SetActiveMenu().
UI_GetArenaInfoByMap()
const char* UI_GetArenaInfoByMap (const char * map)
Definition at line 282 of file ui_gameinfo.c.
{
     int         n;
     for( n = 0; n < ui_numArenas; n++ ) {
         if( Q_stricmp( Info_ValueForKey( ui_arenaInfos[n], "map" ), map ) == 0 ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
References Info_ValueForKey(), NULL, Q_stricmp(), ui_arenaInfos, and ui_numArenas.
UI_GetArenaInfoByNumber()
const char* UI_GetArenaInfoByNumber (int num)
Definition at line 257 of file ui_gameinfo.c.
{
     int     n;
     char    *value;
     if( num < 0 || num >= ui_numArenas ) {
         //trap_Print( va( S_COLOR_RED "Invalid arena number: %i\n", num ) );
         return NULL;
     }
     for( n = 0; n < ui_numArenas; n++ ) {
         value = Info_ValueForKey( ui_arenaInfos[n], "num" );
         if( *value && atoi(value) == num ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
References Info_ValueForKey(), NULL, ui_arenaInfos, and ui_numArenas.
Referenced by StartServer_Cache(), StartServer_GametypeEvent(), StartServer_LevelshotDraw(), StartServer_Start(), and StartServer_Update().
UI_GetNumArenas()
int UI_GetNumArenas (void)
Definition at line 317 of file ui_gameinfo.c.
{
     return ui_numArenas;
 }
References ui_numArenas.
Referenced by StartServer_Cache(), and StartServer_GametypeEvent().
UI_GetSpecialArenaInfo()
const char* UI_GetSpecialArenaInfo (const char * tag)
Definition at line 300 of file ui_gameinfo.c.
{
     int         n;
     for( n = 0; n < ui_numArenas; n++ ) {
         if( Q_stricmp( Info_ValueForKey( ui_arenaInfos[n], "special" ), tag ) == 0 ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
References Info_ValueForKey(), NULL, Q_stricmp(), ui_arenaInfos, and ui_numArenas.
UI_InGameMenu()
void UI_InGameMenu (void)
Definition at line 254 of file ui_ingame.c.
{
     // force as top level menu
     uis.menusp = 0;
     // set menu cursor to a nice location
     uis.cursorx = 320;
     uis.cursory = 240;
     InGame_MenuInit();
     UI_PushMenu( &s_ingame.menu );
 }
References uiStatic_t::cursorx, uiStatic_t::cursory, InGame_MenuInit(), ingamemenu_t::menu, uiStatic_t::menusp, s_ingame, UI_PushMenu(), and uis.
Referenced by UI_SetActiveMenu().
UI_Init()
void UI_Init (void)
Definition at line 969 of file ui_atoms.c.
                      {
     UI_RegisterCvars();
     UI_InitGameinfo();
     trap_GetGlconfig( &uis.glconfig );
     uis.scaleX = uis.glconfig.vidWidth / 640.0;
     uis.scaleY = uis.glconfig.vidHeight / 480.0;
     Menu_Cache();
     uis.activemenu = NULL;
     uis.menusp = 0;
 }
References uiStatic_t::activemenu, uiStatic_t::glconfig, Menu_Cache(), uiStatic_t::menusp, NULL, uiStatic_t::scaleX, uiStatic_t::scaleY, trap_GetGlconfig(), UI_InitGameinfo(), UI_RegisterCvars(), uis, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by vmMain().
UI_InitGameinfo()
void UI_InitGameinfo (void)
Definition at line 326 of file ui_gameinfo.c.
{
     UI_InitMemory();
     UI_LoadArenas();
     uis.menuamount = 0;
     uis.demoversion = qfalse;
 }
References uiStatic_t::demoversion, uiStatic_t::menuamount, qfalse, UI_InitMemory(), UI_LoadArenas(), and uis.
Referenced by UI_Init().
UI_IsFullscreen()
qboolean UI_IsFullscreen (void)
Definition at line 800 of file ui_atoms.c.
{
     if ( uis.activemenu && ( trap_Key_GetCatcher() & KEYCATCH_UI ) ) {
         return uis.activemenu->fullscreen;
     }
     return qfalse;
 }
References uiStatic_t::activemenu, KEYCATCH_UI, qfalse, trap_Key_GetCatcher(), and uis.
Referenced by vmMain().
UI_KeyEvent()
void UI_KeyEvent (int key, int down)
Definition at line 834 of file ui_atoms.c.
{
     sfxHandle_t     s;
     if (!uis.activemenu) {
         return;
     }
     if (!down) {
         return;
     }
     if (uis.activemenu->key)
         s = uis.activemenu->key( key );
     else
         s = Menu_DefaultKey( uis.activemenu, key );
     if ((s > 0) && (s != menu_null_sound))
         trap_S_StartLocalSound( s, CHAN_LOCAL_SOUND );
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, Menu_DefaultKey(), menu_null_sound, trap_S_StartLocalSound(), and uis.
Referenced by vmMain().
UI_LerpColor()
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
Definition at line 166 of file ui_atoms.c.
 {
     int i;
     // lerp and clamp each component
     for (i=0; i<4; i++)
     {
         c[i] = a[i] + t*(b[i]-a[i]);
         if (c[i] < 0)
             c[i] = 0;
         else if (c[i] > 1.0)
             c[i] = 1.0;
     }
 }
UI_MainMenu()
void UI_MainMenu (void)
Definition at line 253 of file ui_menu.c.
{
     qboolean teamArena = qfalse;
     int     style = UI_LEFT | UI_DROPSHADOW | UI_TINYFONT;
     trap_S_StopBackgroundTrack();
     trap_S_StartBackgroundTrack("music/menu.ogg", "music/menu.ogg");
     trap_Cvar_Set( "sv_killserver", "1" );
     // set menu cursor to a nice location
     uis.cursorx = 320;
     uis.cursory = 240;
     memset( &s_main, 0 ,sizeof(mainmenu_t) );
     memset( &s_errorMessage, 0 ,sizeof(errorMessage_t) );
     // com_errorMessage would need that too
     MainMenu_Cache();
     trap_Cvar_VariableStringBuffer( "com_errorMessage", s_errorMessage.errorMessage, sizeof(s_errorMessage.errorMessage) );
     if (strlen(s_errorMessage.errorMessage))
     {
         s_errorMessage.menu.draw = Main_MenuDraw;
         s_errorMessage.menu.key = ErrorMessage_Key;
         s_errorMessage.menu.fullscreen = qtrue;
         s_errorMessage.menu.wrapAround = qtrue;
         s_errorMessage.menu.showlogo = qtrue;
         trap_Key_SetCatcher( KEYCATCH_UI );
         uis.menusp = 0;
         UI_PushMenu ( &s_errorMessage.menu );
         return;
     }
     s_main.menu.draw = Main_MenuDraw;
     s_main.menu.fullscreen = qtrue;
     s_main.menu.wrapAround = qtrue;
     s_main.menu.showlogo = qtrue;
     s_main.multiplayer.generic.type         = MTYPE_PTEXT;
     s_main.multiplayer.generic.flags        = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.multiplayer.generic.x            = multiXpos;
     s_main.multiplayer.generic.y            = multiYpos;
     s_main.multiplayer.generic.id           = ID_MULTIPLAYER;
     s_main.multiplayer.generic.callback     = Main_MenuEvent;
     s_main.multiplayer.string               = "PLAY";
     s_main.multiplayer.color                = color_white;
     s_main.multiplayer.style                = style;
     s_main.setup.generic.type               = MTYPE_PTEXT;
     s_main.setup.generic.flags              = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.setup.generic.x                  = setupXpos;
     s_main.setup.generic.y                  = setupYpos;
     s_main.setup.generic.id                 = ID_SETUP;
     s_main.setup.generic.callback           = Main_MenuEvent;
     s_main.setup.string                     = "SETUP";
     s_main.setup.color                      = color_white;
     s_main.setup.style                      = style;
     s_main.exit.generic.type                = MTYPE_PTEXT;
     s_main.exit.generic.flags               = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.exit.generic.x                   = exitXpos;
     s_main.exit.generic.y                   = exitYpos;
     s_main.exit.generic.id                  = ID_EXIT;
     s_main.exit.generic.callback            = Main_MenuEvent;
     s_main.exit.string                      = "EXIT";
     s_main.exit.color                       = color_white;
     s_main.exit.style                       = style;
     s_main.name.generic.type                = MTYPE_FIELD;
     s_main.name.generic.flags               = QMF_NODEFAULTINIT;
     s_main.name.generic.ownerdraw           = MainMenu_DrawName;
     s_main.name.field.widthInChars          = 14;
     s_main.name.field.maxchars              = 14;
     s_main.name.generic.x                   = 454;
     s_main.name.generic.y                   = 405;
     s_main.name.generic.left                = 474;
     s_main.name.generic.top                 = 430;
     s_main.name.generic.right               = 610;
     s_main.name.generic.bottom              = 455;
     s_main.player.generic.type              = MTYPE_BITMAP;
     s_main.player.generic.flags             = QMF_SILENT;
     s_main.player.generic.ownerdraw         = MainMenu_DrawPlayer;
     s_main.player.generic.id                = ID_MODEL;
     s_main.player.generic.callback          = Main_MenuEvent;
     s_main.player.generic.x                 = 380;
     s_main.player.generic.y                 = aspectRatioCorrectedY(-118);
     s_main.player.width                     = 320;
     s_main.player.height                    = 810;
     Menu_AddItem( &s_main.menu, &s_main.multiplayer );
     Menu_AddItem( &s_main.menu, &s_main.setup );
     Menu_AddItem( &s_main.menu, &s_main.exit );
     Menu_AddItem( &s_main.menu, &s_main.name );
     Q_strncpyz(s_main.name.field.buffer,UI_Cvar_VariableString("name"),sizeof(s_main.name.field.buffer) );
     Menu_AddItem( &s_main.menu, &s_main.player );
     trap_Key_SetCatcher( KEYCATCH_UI );
     uis.menusp = 0;
     UI_PushMenu ( &s_main.menu );
 }
References aspectRatioCorrectedY(), menucommon_s::bottom, mfield_t::buffer, menucommon_s::callback, menutext_s::color, color_white, uiStatic_t::cursorx, uiStatic_t::cursory, errorMessage_t::errorMessage, ErrorMessage_Key(), mainmenu_t::exit, exitXpos, exitYpos, menufield_s::field, menucommon_s::flags, menufield_s::generic, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_EXIT, ID_MODEL, ID_MULTIPLAYER, ID_SETUP, KEYCATCH_UI, menucommon_s::left, Main_MenuDraw(), Main_MenuEvent(), MainMenu_Cache(), MainMenu_DrawName(), MainMenu_DrawPlayer(), mfield_t::maxchars, mainmenu_t::menu, errorMessage_t::menu, Menu_AddItem(), uiStatic_t::menusp, MTYPE_BITMAP, MTYPE_FIELD, MTYPE_PTEXT, mainmenu_t::multiplayer, multiXpos, multiYpos, mainmenu_t::name, menucommon_s::ownerdraw, mainmenu_t::player, Q_strncpyz(), qfalse, QMF_LEFT_JUSTIFY, QMF_NODEFAULTINIT, QMF_PULSEIFFOCUS, QMF_SILENT, qtrue, menucommon_s::right, s_errorMessage, s_main, mainmenu_t::setup, setupXpos, setupYpos, menutext_s::string, menutext_s::style, menucommon_s::top, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Key_SetCatcher(), trap_S_StartBackgroundTrack(), trap_S_StopBackgroundTrack(), menucommon_s::type, UI_Cvar_VariableString(), UI_DROPSHADOW, UI_LEFT, UI_PushMenu(), UI_TINYFONT, uis, menubitmap_s::width, mfield_t::widthInChars, menucommon_s::x, and menucommon_s::y.
Referenced by ErrorMessage_Key(), and UI_SetActiveMenu().
UI_MenuLogo()
void UI_MenuLogo (void)
Definition at line 1154 of file ui_atoms.c.
{
     refdef_t        refdef;
     refEntity_t     ent;
     vec3_t          origin;
     vec3_t          angles;
     float           adjust;
     float           x, y, w, h;
     float           xx;
     vec3_t          mins = {-128, -128, -128};
     vec3_t          maxs = {128, 128, 128};
     float           len;
     // setup the refdef
     memset( &refdef, 0, sizeof( refdef ) );
     refdef.rdflags = RDF_NOWORLDMODEL;
     AxisClear( refdef.viewaxis );
     x = -19;
     y = -28;
     w = 205;
     h = 153;
     UI_AdjustFrom640( &x, &y, &w, &h );
     refdef.x = x;
     refdef.y = y;
     refdef.width = w;
     refdef.height = h;
     //adjust = 1.0f * sin( (float)uis.realtime / 5000 );
     refdef.fov_x = (int)((float)refdef.width / 640.0f * 35.0f);
     xx = refdef.width / tan( refdef.fov_x / 360 * M_PI );
     refdef.fov_y = atan2( refdef.height, xx );
     refdef.fov_y *= ( 360 / M_PI );
     /*
     refdef.fov_x = 20 + adjust;
     refdef.fov_y = 15 + adjust;
     */
     refdef.time = uis.realtime;
     // calculate distance so the scene fills the box
     len = 0.5 * ( maxs[2] - mins[2] );
     origin[0] = len / tan( DEG2RAD(refdef.fov_x) * 0.5 );
     origin[1] = 0.5 * ( mins[1] + maxs[1] );
     origin[2] = -0.5 * ( mins[2] + maxs[2] );
 /*
     origin[0] = 640; //z depth
     origin[1] = 0; //x depth
     origin[2] = 0; //y depth
 */
     trap_R_ClearScene();
     // add the model
     memset( &ent, 0, sizeof(ent) );
     adjust = -2.5f * sin( (float)uis.realtime / 5000 );
     VectorSet( angles, 0, 180 + adjust, 0 );
     AnglesToAxis( angles, ent.axis );
     ent.hModel = uis.logoModel;
     VectorCopy( origin, ent.origin );
     VectorCopy( origin, ent.lightingOrigin );
     ent.renderfx = RF_LIGHTING_ORIGIN | RF_NOSHADOW;
     VectorCopy( ent.origin, ent.oldorigin );
     trap_R_AddRefEntityToScene( &ent );
     trap_R_RenderScene( &refdef );
 }
References angles, AnglesToAxis(), refEntity_t::axis, AxisClear(), DEG2RAD, refdef_t::fov_x, refdef_t::fov_y, refdef_t::height, refEntity_t::hModel, int(), refEntity_t::lightingOrigin, uiStatic_t::logoModel, M_PI, refEntity_t::oldorigin, refEntity_t::origin, RDF_NOWORLDMODEL, refdef_t::rdflags, uiStatic_t::realtime, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, RF_NOSHADOW, refdef_t::time, trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RenderScene(), UI_AdjustFrom640(), uis, VectorCopy, VectorSet, refdef_t::viewaxis, refdef_t::width, refdef_t::x, xx, and refdef_t::y.
Referenced by Menu_Common().
UI_MenuScene()
void UI_MenuScene (void)
Definition at line 1077 of file ui_atoms.c.
{
     refdef_t        refdef;
     refEntity_t     ent;
     vec3_t          origin;
     vec3_t          angles;
     float           adjust;
     float           x, y, w, h;
     float           xx;
     vec3_t          mins = {-128, -128, -128};
     vec3_t          maxs = {128, 128, 128};
     float           len;
     // setup the refdef
     memset( &refdef, 0, sizeof( refdef ) );
     refdef.rdflags = RDF_NOWORLDMODEL;
     AxisClear( refdef.viewaxis );
     x = 0;
     y = 0;
     w = 640;
     h = 480;
     UI_AdjustFrom640( &x, &y, &w, &h );
     refdef.x = x;
     refdef.y = y;
     refdef.width = w;
     refdef.height = h;
     //adjust = 1.0f * sin( (float)uis.realtime / 5000 );
     refdef.fov_x = (int)((float)refdef.width / 640.0f * 35.0f);
     xx = refdef.width / tan( refdef.fov_x / 360 * M_PI );
     refdef.fov_y = atan2( refdef.height, xx );
     refdef.fov_y *= ( 360 / M_PI );
     /*
     refdef.fov_x = 20 + adjust;
     refdef.fov_y = 15 + adjust;
     */
     refdef.time = uis.realtime;
     // calculate distance so the scene fills the box
     len = 0.5 * ( maxs[2] - mins[2] );
     origin[0] = len / tan( DEG2RAD(refdef.fov_x) * 0.5 );
     origin[1] = 0.5 * ( mins[1] + maxs[1] );
     origin[2] = -0.5 * ( mins[2] + maxs[2] );
 /*
     origin[0] = 640; //z depth
     origin[1] = 0; //x depth
     origin[2] = 0; //y depth
 */
     trap_R_ClearScene();
     // add the model
     memset( &ent, 0, sizeof(ent) );
     adjust = 2.5f * sin( (float)uis.realtime / 5000 );
     VectorSet( angles, 0, 180 + adjust, 0 );
     AnglesToAxis( angles, ent.axis );
     ent.hModel = uis.sceneModel;
     VectorCopy( origin, ent.origin );
     VectorCopy( origin, ent.lightingOrigin );
     ent.renderfx = RF_LIGHTING_ORIGIN | RF_NOSHADOW;
     VectorCopy( ent.origin, ent.oldorigin );
     trap_R_AddRefEntityToScene( &ent );
     trap_R_RenderScene( &refdef );
 }
References angles, AnglesToAxis(), refEntity_t::axis, AxisClear(), DEG2RAD, refdef_t::fov_x, refdef_t::fov_y, refdef_t::height, refEntity_t::hModel, int(), refEntity_t::lightingOrigin, M_PI, refEntity_t::oldorigin, refEntity_t::origin, RDF_NOWORLDMODEL, refdef_t::rdflags, uiStatic_t::realtime, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, RF_NOSHADOW, uiStatic_t::sceneModel, refdef_t::time, trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RenderScene(), UI_AdjustFrom640(), uis, VectorCopy, VectorSet, refdef_t::viewaxis, refdef_t::width, refdef_t::x, xx, and refdef_t::y.
Referenced by UI_DrawConnectScreen(), and UI_Refresh().
UI_Message()
void UI_Message (const char ** lines)
Definition at line 253 of file ui_confirm.c.
{
     uiClientState_t cstate;
     int n1, l1;
     // zero set all our globals
     memset( &s_confirm, 0, sizeof(s_confirm) );
     ConfirmMenu_Cache();
     n1 = UI_ProportionalStringWidth( "OK" );
     l1 = 320 - ( n1 / 2 );
     s_confirm.lines = lines;
     s_confirm.style = UI_CENTER|UI_INVERSE|UI_SMALLFONT;
     s_confirm.menu.draw       = MessageMenu_Draw;
     s_confirm.menu.key        = ConfirmMenu_Key;
     s_confirm.menu.wrapAround = qtrue;
     trap_GetClientState( &cstate );
     if ( cstate.connState >= CA_CONNECTED ) {
         s_confirm.menu.fullscreen = qfalse;
     }
     else {
         s_confirm.menu.fullscreen = qtrue;
     }
     s_confirm.yes.generic.type      = MTYPE_PTEXT;
     s_confirm.yes.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.yes.generic.callback  = ConfirmMenu_Event;
     s_confirm.yes.generic.id        = ID_CONFIRM_YES;
     s_confirm.yes.generic.x         = l1;
     s_confirm.yes.generic.y         = 280;
     s_confirm.yes.string            = "OK";
     s_confirm.yes.color             = color_red;
     s_confirm.yes.style             = UI_LEFT;
     Menu_AddItem( &s_confirm.menu,  &s_confirm.yes );
     UI_PushMenu( &s_confirm.menu );
     Menu_SetCursorToItem( &s_confirm.menu, &s_confirm.yes );
 }
References CA_CONNECTED, menucommon_s::callback, menutext_s::color, color_red, ConfirmMenu_Cache(), ConfirmMenu_Event(), ConfirmMenu_Key(), uiClientState_t::connState, menucommon_s::flags, menutext_s::generic, menucommon_s::id, ID_CONFIRM_YES, confirmMenu_t::lines, confirmMenu_t::menu, Menu_AddItem(), Menu_SetCursorToItem(), MessageMenu_Draw(), MTYPE_PTEXT, qfalse, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s_confirm, menutext_s::string, confirmMenu_t::style, menutext_s::style, trap_GetClientState(), menucommon_s::type, UI_CENTER, UI_INVERSE, UI_LEFT, UI_ProportionalStringWidth(), UI_PushMenu(), UI_SMALLFONT, menucommon_s::x, menucommon_s::y, and confirmMenu_t::yes.
UI_MouseEvent()
void UI_MouseEvent (int dx, int dy)
Definition at line 859 of file ui_atoms.c.
 {
     int             i;
     menucommon_s*   m;
     if (!uis.activemenu)
         return;
     // update mouse screen position
     uis.cursorx += dx;
     if (uis.cursorx < 0)
         uis.cursorx = 0;
     else if (uis.cursorx > SCREEN_WIDTH)
         uis.cursorx = SCREEN_WIDTH;
     uis.cursory += dy;
     if (uis.cursory < 0)
         uis.cursory = 0;
     else if (uis.cursory > SCREEN_HEIGHT)
         uis.cursory = SCREEN_HEIGHT;
     // region test the active menu items
     for (i=0; i<uis.activemenu->nitems; i++)
     {
         m = (menucommon_s*)uis.activemenu->items[i];
         if (m->flags & (QMF_GRAYED|QMF_INACTIVE))
             continue;
         if ((uis.cursorx < m->left) ||
             (uis.cursorx > m->right) ||
             (uis.cursory < m->top) ||
             (uis.cursory > m->bottom))
         {
             // cursor out of item bounds
             continue;
         }
         // set focus to item at cursor
         if (uis.activemenu->cursor != i)
         {
             Menu_SetCursor( uis.activemenu, i );
             ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor_prev]))->flags &= ~QMF_HASMOUSEFOCUS;
             if ( !(((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags & QMF_SILENT ) ) {
                 trap_S_StartLocalSound( menu_move_sound, CHAN_LOCAL_SOUND );
             }
         }
         ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags |= QMF_HASMOUSEFOCUS;
         return;
     }
     if (uis.activemenu->nitems > 0) {
         // out of any region
         ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags &= ~QMF_HASMOUSEFOCUS;
     }
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, uiStatic_t::cursorx, uiStatic_t::cursory, m, menu_move_sound, Menu_SetCursor(), QMF_GRAYED, QMF_HASMOUSEFOCUS, QMF_INACTIVE, QMF_SILENT, SCREEN_HEIGHT, SCREEN_WIDTH, trap_S_StartLocalSound(), and uis.
Referenced by vmMain().
UI_MusicMenu()
void UI_MusicMenu (void)
Definition at line 263 of file ui_music.c.
{
     Music_MenuInit();
     UI_PushMenu( &s_music.menu );
 }
References music_t::menu, Music_MenuInit(), s_music, and UI_PushMenu().
UI_MusicMenu_Cache()
void UI_MusicMenu_Cache (void)
UI_PlayerInfo_SetInfo()
void UI_PlayerInfo_SetInfo (playerInfo_t * pi, int legsAnim, int torsoAnim, vec3_t viewAngles, vec3_t moveAngles, weapon_t weaponNum, qboolean chat)
Definition at line 1320 of file ui_players.c.
{
     int         currentAnim;
     weapon_t    weaponNum;
     pi->chat = chat;
     // view angles
     VectorCopy( viewAngles, pi->viewAngles );
     // move angles
     VectorCopy( moveAngles, pi->moveAngles );
     if ( pi->newModel ) {
         pi->newModel = qfalse;
         jumpHeight = 0;
         pi->pendingLegsAnim = 0;
         UI_ForceLegsAnim( pi, legsAnim );
         pi->legs.yawAngle = viewAngles[YAW];
         pi->legs.yawing = qfalse;
         pi->pendingTorsoAnim = 0;
         UI_ForceTorsoAnim( pi, torsoAnim );
         pi->torso.yawAngle = viewAngles[YAW];
         pi->torso.yawing = qfalse;
 /*
         pi->pendingHeadAnim = 0;
         UI_ForceHeadAnim( pi, headAnim );
         pi->head.yawAngle = viewAngles[YAW];
         pi->head.yawing = qfalse;
 */
         if ( weaponNumber != -1 ) {
             pi->weapon = weaponNumber;
             pi->currentWeapon = weaponNumber;
             pi->lastWeapon = weaponNumber;
             pi->pendingWeapon = -1;
             pi->weaponTimer = 0;
             UI_PlayerInfo_SetWeapon( pi, pi->weapon );
         }
         return;
     }
     // weapon
     if ( weaponNumber == -1 ) {
         pi->pendingWeapon = -1;
         pi->weaponTimer = 0;
     }
     else if ( weaponNumber != WP_NONE ) {
         pi->pendingWeapon = weaponNumber;
         pi->weaponTimer = dp_realtime + UI_TIMER_WEAPON_DELAY;
     }
     weaponNum = pi->lastWeapon;
     pi->weapon = weaponNum;
     if ( torsoAnim == ANIM_DEATH_GROUND || legsAnim == ANIM_DEATH_GROUND ) {
         torsoAnim = legsAnim = ANIM_DEATH_GROUND;
         pi->weapon = pi->currentWeapon = WP_NONE;
         UI_PlayerInfo_SetWeapon( pi, pi->weapon );
         jumpHeight = 0;
         pi->pendingLegsAnim = 0;
         UI_ForceLegsAnim( pi, legsAnim );
         pi->pendingTorsoAnim = 0;
         UI_ForceTorsoAnim( pi, torsoAnim );
         return;
     }
     // leg animation
     currentAnim = pi->legsAnim & ~ANIM_TOGGLEBIT;
     if ( legsAnim != ANIM_JUMP_UP && ( currentAnim == ANIM_JUMP_UP || currentAnim == ANIM_LAND_UP ) ) {
         pi->pendingLegsAnim = legsAnim;
     }
     else if ( legsAnim != currentAnim ) {
         jumpHeight = 0;
         pi->pendingLegsAnim = 0;
         UI_ForceLegsAnim( pi, legsAnim );
     }
 /*
     // torso animation
     if ( torsoAnim == ANIM_IDLE || torsoAnim == ANIM_IDLE_LOCKED ) {
         if ( weaponNum == WP_NONE || weaponNum == WP_GAUNTLET ) {
             torsoAnim = ANIM_IDLE;
         }
         else {
             torsoAnim = ANIM_IDLE;
         }
     }
     if ( torsoAnim == ANIM_ATTACK || torsoAnim == ANIM_ATTACK2 ) {
         if ( weaponNum == WP_NONE || weaponNum == WP_GAUNTLET ) {
             torsoAnim = ANIM_ATTACK2;
         }
         else {
             torsoAnim = ANIM_ATTACK;
         }
         pi->muzzleFlashTime = dp_realtime + UI_TIMER_MUZZLE_FLASH;
         //FIXME play firing sound here
     }
 */
     currentAnim = pi->torsoAnim & ~ANIM_TOGGLEBIT;
 /*
     if ( weaponNum != pi->currentWeapon || currentAnim == ANIM_RAISE || currentAnim == ANIM_DROP ) {
         pi->pendingTorsoAnim = torsoAnim;
     }
     else if ( ( currentAnim == ANIM_GESTURE || currentAnim == ANIM_ATTACK ) && ( torsoAnim != currentAnim ) ) {
         pi->pendingTorsoAnim = torsoAnim;
     }
     else */if ( torsoAnim != currentAnim ) {
         pi->pendingTorsoAnim = 0;
         UI_ForceTorsoAnim( pi, torsoAnim );
     }
 }
References ANIM_DEATH_GROUND, ANIM_JUMP_UP, ANIM_LAND_UP, ANIM_TOGGLEBIT, playerInfo_t::chat, playerInfo_t::currentWeapon, dp_realtime, jumpHeight, playerInfo_t::lastWeapon, playerInfo_t::legs, playerInfo_t::legsAnim, playerInfo_t::moveAngles, playerInfo_t::newModel, playerInfo_t::pendingLegsAnim, playerInfo_t::pendingTorsoAnim, playerInfo_t::pendingWeapon, qfalse, playerInfo_t::torso, playerInfo_t::torsoAnim, UI_ForceLegsAnim(), UI_ForceTorsoAnim(), UI_PlayerInfo_SetWeapon(), UI_TIMER_WEAPON_DELAY, VectorCopy, playerInfo_t::viewAngles, playerInfo_t::weapon, playerInfo_t::weaponTimer, WP_NONE, YAW, lerpFrame_t::yawAngle, and lerpFrame_t::yawing.
Referenced by Controls_UpdateModel(), MainMenu_DrawPlayer(), and PlayerModel_UpdateModel().
UI_PlayerInfo_SetModel()
void UI_PlayerInfo_SetModel (playerInfo_t * pi, const char * model)
Definition at line 1301 of file ui_players.c.
{
     memset( pi, 0, sizeof(*pi) );
     UI_RegisterClientModelname( pi, model );
     pi->weapon = WP_MACHINEGUN;
     pi->currentWeapon = pi->weapon;
     pi->lastWeapon = pi->weapon;
     pi->pendingWeapon = -1;
     pi->weaponTimer = 0;
     pi->chat = qfalse;
     pi->newModel = qtrue;
     UI_PlayerInfo_SetWeapon( pi, pi->weapon );
 }
References playerInfo_t::chat, playerInfo_t::currentWeapon, playerInfo_t::lastWeapon, playerInfo_t::newModel, playerInfo_t::pendingWeapon, qfalse, qtrue, UI_PlayerInfo_SetWeapon(), UI_RegisterClientModelname(), playerInfo_t::weapon, playerInfo_t::weaponTimer, and WP_MACHINEGUN.
Referenced by Controls_DrawPlayer(), Controls_InitModel(), MainMenu_DrawPlayer(), and PlayerModel_UpdateModel().
UI_PlayerModelMenu()
void UI_PlayerModelMenu (void)
Definition at line 718 of file ui_playermodel.c.
 {
     PlayerModel_MenuInit();
     uis.menuamount = 1;
     uis.showFrame = qfalse;
     uis.hideEarth = qtrue;
     UI_PushMenu( &s_playermodel.menu );
     Menu_SetCursorToItem( &s_playermodel.menu, &s_playermodel.pics[s_playermodel.selectedmodel % MAX_MODELSPERPAGE] );
 }
References uiStatic_t::hideEarth, MAX_MODELSPERPAGE, playermodel_t::menu, Menu_SetCursorToItem(), uiStatic_t::menuamount, playermodel_t::pics, PlayerModel_MenuInit(), qfalse, qtrue, s_playermodel, playermodel_t::selectedmodel, uiStatic_t::showFrame, UI_PushMenu(), and uis.
Referenced by InGame_Event(), and Main_MenuEvent().
UI_PlayerSettingsMenu()
void UI_PlayerSettingsMenu (void)
UI_PopMenu()
void UI_PopMenu (void)
Definition at line 133 of file ui_atoms.c.
 {
     trap_S_StartLocalSound( menu_out_sound, CHAN_LOCAL_SOUND );
     uis.menusp--;
     if (uis.menusp < 0)
         trap_Error ("UI_PopMenu: menu stack underflow");
     if (uis.menusp) {
         uis.activemenu = uis.stack[uis.menusp-1];
         uis.firstdraw = qtrue;
     }
     else {
         UI_ForceMenuOff ();
     }
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, uiStatic_t::firstdraw, menu_out_sound, uiStatic_t::menusp, qtrue, uiStatic_t::stack, trap_Error(), trap_S_StartLocalSound(), UI_ForceMenuOff(), and uis.
Referenced by ArenaServers_Event(), Camera_MenuEvent(), ConfirmMenu_Event(), Controls_MenuEvent(), InGame_QuitAction(), InGame_RestartAction(), Menu_DefaultKey(), Music_MenuEvent(), Options_Event(), PlayerModel_MenuEvent(), Preferences_Event(), ServerInfo_Event(), StartServer_MenuEvent(), and SystemSettings_Event().
UI_PreferencesMenu()
void UI_PreferencesMenu (void)
Definition at line 588 of file ui_preferences.c.
{
     uis.menuamount = 4;
     uis.hideEarth = qtrue;
     uis.showFrame = qtrue;
     Preferences_MenuInit();
     UI_PushMenu( &s_preferences.menu );
     Menu_SetCursorToItem(&s_preferences.menu,&s_preferences.general);
 }
References preferences_t::general, uiStatic_t::hideEarth, preferences_t::menu, Menu_SetCursorToItem(), uiStatic_t::menuamount, Preferences_MenuInit(), qtrue, s_preferences, uiStatic_t::showFrame, UI_PushMenu(), and uis.
Referenced by Controls_MenuEvent(), and SystemSettings_Event().
UI_ProportionalSizeScale()
float UI_ProportionalSizeScale (int style)
Definition at line 775 of file cg_drawtools.c.
{
     if(  style & UI_SMALLFONT ) {
         return 0.75;
     }
     return 1.00;
 }
References PROP_SMALL_SIZE_SCALE, UI_SMALLFONT, and UI_TINYFONT.
Referenced by PText_Init(), UI_DisplayDownloadInfo(), and UI_DrawProportionalString().
UI_ProportionalStringWidth()
int UI_ProportionalStringWidth (const char * str)
Definition at line 704 of file cg_drawtools.c.
{
     const char *    s;
     int             ch;
     int             charWidth;
     int             width;
     s = str;
     width = 0;
     while ( *s ) {
         ch = *s & 127;
         charWidth = propMap[ch][2];
         if ( charWidth != -1 ) {
             width += charWidth;
             width += PROP_GAP_WIDTH;
         }
         s++;
     }
     width -= PROP_GAP_WIDTH;
     return width;
 }
References PROP_GAP_WIDTH, and propMap.
Referenced by PText_Init(), UI_ConfirmMenu_Style(), UI_DisplayDownloadInfo(), UI_DrawProportionalString(), and UI_Message().
UI_PushMenu()
void UI_PushMenu (menuframework_s * menu)
Definition at line 81 of file ui_atoms.c.
 {
     int             i;
     menucommon_s*   item;
     // avoid stacking menus invoked by hotkeys
     for (i=0 ; i<uis.menusp ; i++)
     {
         if (uis.stack[i] == menu){
             uis.menusp = i;
             break;
         }
     }
     if (i == uis.menusp)
     {
         if (uis.menusp >= MAX_MENUDEPTH)
             trap_Error("UI_PushMenu: menu stack overflow");
         uis.stack[uis.menusp++] = menu;
     }
     uis.activemenu = menu;
     // default cursor position
     menu->cursor      = 0;
     menu->cursor_prev = 0;
     m_entersound = qtrue;
     trap_Key_SetCatcher( KEYCATCH_UI );
     // force first available item to have focus
     for (i=0; i<menu->nitems; i++)
     {
         item = (menucommon_s *)menu->items[i];
         if (!(item->flags & (QMF_GRAYED|QMF_MOUSEONLY|QMF_INACTIVE)))
         {
             menu->cursor_prev = -1;
             Menu_SetCursor( menu, i );
             break;
         }
     }
     uis.firstdraw = qtrue;
 }
References uiStatic_t::activemenu, uiStatic_t::firstdraw, menucommon_s::flags, KEYCATCH_UI, m_entersound, MAX_MENUDEPTH, Menu_SetCursor(), uiStatic_t::menusp, QMF_GRAYED, QMF_INACTIVE, QMF_MOUSEONLY, qtrue, uiStatic_t::stack, trap_Error(), trap_Key_SetCatcher(), and uis.
Referenced by UI_ArenaServersMenu(), UI_CameraMenu(), UI_ConfirmMenu_Style(), UI_ControlsMenu(), UI_CreditMenu(), UI_InGameMenu(), UI_MainMenu(), UI_Message(), UI_MusicMenu(), UI_PlayerModelMenu(), UI_PreferencesMenu(), UI_ServerInfoMenu(), UI_StartServerMenu(), UI_SystemConfigMenu(), UI_SystemSettingsMenu(), and UI_TeamMainMenu().
UI_Refresh()
void UI_Refresh (int realtime)
Definition at line 1251 of file ui_atoms.c.
{
     uis.frametime = realtime - uis.realtime;
     uis.realtime  = realtime;
     if(!( trap_Key_GetCatcher() & KEYCATCH_UI)){
         return;
     }
     UI_UpdateCvars();
     if(uis.activemenu){
         if (uis.activemenu->fullscreen){
             if(!uis.hideBack){UI_DrawHandlePic( 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, uis.menuBackShader);}
             if(!uis.hideEarth){UI_MenuScene();}
             if(uis.showFrame){Menu_Frame();}
             if(uis.showSide){Menu_Side();}
             Menu_Common(uis.menuamount);
         }
         if(uis.activemenu->draw){uis.activemenu->draw();}
         else{Menu_Draw(uis.activemenu);}
     }
     UI_SetColor(NULL);
     UI_DrawHandlePic( uis.cursorx-16, uis.cursory-16, 32, 32, uis.cursor);
     if (uis.debug){
         UI_DrawString( 0, 0, va("(%d,%d)",uis.cursorx,uis.cursory), UI_LEFT|UI_SMALLFONT|UI_DROPSHADOW, colorRed );
     }
     if (m_entersound){
         trap_S_StartLocalSound( menu_in_sound, CHAN_LOCAL_SOUND );
         m_entersound = qfalse;
     }
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, colorRed, uiStatic_t::cursor, uiStatic_t::cursorx, uiStatic_t::cursory, uiStatic_t::debug, uiStatic_t::frametime, uiStatic_t::hideBack, uiStatic_t::hideEarth, KEYCATCH_UI, m_entersound, Menu_Common(), Menu_Draw(), Menu_Frame(), menu_in_sound, Menu_Side(), uiStatic_t::menuamount, uiStatic_t::menuBackShader, NULL, qfalse, uiStatic_t::realtime, SCREEN_HEIGHT, SCREEN_WIDTH, uiStatic_t::showFrame, uiStatic_t::showSide, trap_Key_GetCatcher(), trap_S_StartLocalSound(), UI_DrawHandlePic(), UI_DrawString(), UI_DROPSHADOW, UI_LEFT, UI_MenuScene(), UI_SetColor(), UI_SMALLFONT, UI_UpdateCvars(), uis, and va().
Referenced by vmMain().
UI_RegisterClientModelname()
qboolean UI_RegisterClientModelname (playerInfo_t * pi, const char * modelSkinName)
Definition at line 1228 of file ui_players.c.
{
     char        modelName[MAX_QPATH];
     char        skinName[MAX_QPATH];
     char        filename[MAX_QPATH];
     char        *slash;
     pi->torsoModel = 0;
     pi->headModel = 0;
     if ( !modelSkinName[0] ) {
         return qfalse;
     }
     Q_strncpyz( modelName, modelSkinName, sizeof( modelName ) );
     slash = strchr( modelName, '/' );
     if ( !slash ) {
         // modelName did not include a skin name
         Q_strncpyz( skinName, "default", sizeof( skinName ) );
     } else {
         Q_strncpyz( skinName, slash + 1, sizeof( skinName ) );
         // truncate modelName
         *slash = 0;
     }
     // load cmodels before models so filecache works
     if ( !pi->legsModel ) {
         Com_sprintf( filename, sizeof( filename ), "players//%s/Tier1/%s/Legs.md3", modelName , skinName );
         pi->legsModel = trap_R_RegisterModel( filename );
         if ( !pi->legsModel ) {
             //Com_Printf( "Failed to load model file %s\n", filename );
             return qfalse;
         }
         Com_sprintf( filename, sizeof( filename ), "players//%s/Tier1/%s/Torso.md3", modelName , skinName );
         pi->torsoModel = trap_R_RegisterModel( filename );
         if ( !pi->torsoModel ) {
             //Com_Printf( "Failed to load model file %s\n", filename );
             return qfalse;
         }
         Com_sprintf( filename, sizeof( filename ), "players//%s/Tier1/%s/Head.md3", modelName , skinName );
         pi->headModel = trap_R_RegisterModel( filename );
         if ( !pi->headModel ) {
             //Com_Printf( "Failed to load model file %s\n", filename );
             return qfalse;
         }
     }
     // if any skins failed to load, fall back to default
     if ( !UI_RegisterClientSkin( pi, modelName, skinName ) ) {
         if ( !UI_RegisterClientSkin( pi, modelName, "default" ) ) {
             //Com_Printf( "Failed to load skin file: %s : %s\n", modelName, skinName );
             return qfalse;
         }
     }
     // load the animations
     Com_sprintf( filename, sizeof( filename ), "players//%s/animation.cfg", modelName );
     if ( !UI_ParseAnimationFile( filename, pi->animations, pi ) ) {
         //Com_Printf( "Failed to load animation file %s\n", filename );
         return qfalse;
     }
     return qtrue;
 }
References playerInfo_t::animations, Com_sprintf(), playerInfo_t::headModel, playerInfo_t::legsModel, MAX_QPATH, Q_strncpyz(), qfalse, qtrue, playerInfo_t::torsoModel, trap_R_RegisterModel(), UI_ParseAnimationFile(), and UI_RegisterClientSkin().
Referenced by UI_PlayerInfo_SetModel().
UI_RegisterCvars()
void UI_RegisterCvars (void)
Definition at line 185 of file ui_main.c.
{
     int         i;
     cvarTable_t *cv;
     for ( i = 0, cv = cvarTable ; i < cvarTableSize ; i++, cv++ ) {
         trap_Cvar_Register( cv->vmCvar, cv->cvarName, cv->defaultString, cv->cvarFlags );
     }
 }
References cvarTable_t::cvarFlags, cvarTable_t::cvarName, cvarTable, cvarTableSize, cvarTable_t::defaultString, trap_Cvar_Register(), and cvarTable_t::vmCvar.
Referenced by UI_Init().
UI_ServerInfoMenu()
void UI_ServerInfoMenu (void)
Definition at line 186 of file ui_serverinfo.c.
 {
     const char      *s;
     char            key[MAX_INFO_KEY];
     char            value[MAX_INFO_VALUE];
     // zero set all our globals
     memset( &s_serverinfo, 0 ,sizeof(serverinfo_t) );
     ServerInfo_Cache();
     uis.menuamount = 0;
     s_serverinfo.menu.draw       = ServerInfo_MenuDraw;
     s_serverinfo.menu.key        = ServerInfo_MenuKey;
     s_serverinfo.menu.wrapAround = qtrue;
     s_serverinfo.menu.fullscreen = qtrue;
     s_serverinfo.banner.generic.type  = MTYPE_BTEXT;
     s_serverinfo.banner.generic.x     = 320;
     s_serverinfo.banner.generic.y     = 16;
     s_serverinfo.banner.string        = "SERVER INFO";
     s_serverinfo.banner.color         = color_white;
     s_serverinfo.banner.style         = UI_CENTER|UI_DROPSHADOW;
     s_serverinfo.framel.generic.type  = MTYPE_BITMAP;
     s_serverinfo.framel.generic.name  = SERVERINFO_FRAMEL;
     s_serverinfo.framel.generic.flags = QMF_INACTIVE;
     s_serverinfo.framel.generic.x     = 0;
     s_serverinfo.framel.generic.y     = 78;
     s_serverinfo.framel.width         = 256;
     s_serverinfo.framel.height        = 329;
     s_serverinfo.framer.generic.type  = MTYPE_BITMAP;
     s_serverinfo.framer.generic.name  = SERVERINFO_FRAMER;
     s_serverinfo.framer.generic.flags = QMF_INACTIVE;
     s_serverinfo.framer.generic.x     = 376;
     s_serverinfo.framer.generic.y     = 76;
     s_serverinfo.framer.width         = 256;
     s_serverinfo.framer.height        = 334;
     s_serverinfo.add.generic.type     = MTYPE_PTEXT;
     s_serverinfo.add.generic.flags    = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_serverinfo.add.generic.callback = ServerInfo_Event;
     s_serverinfo.add.generic.id       = ID_ADD;
     s_serverinfo.add.generic.x        = 320;
     s_serverinfo.add.generic.y        = 371;
     s_serverinfo.add.string           = "ADD TO FAVORITES";
     s_serverinfo.add.style            = UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW;
     s_serverinfo.add.color            = color_white;
     if( trap_Cvar_VariableValue( "sv_running" ) ) {
         s_serverinfo.add.generic.flags |= QMF_GRAYED;
     }
     s_serverinfo.back.generic.type     = MTYPE_BITMAP;
     s_serverinfo.back.generic.name     = SERVERINFO_BACK0;
     s_serverinfo.back.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_serverinfo.back.generic.callback = ServerInfo_Event;
     s_serverinfo.back.generic.id       = ID_BACK;
     s_serverinfo.back.generic.x        = 0;
     s_serverinfo.back.generic.y        = 480-64;
     s_serverinfo.back.width            = 128;
     s_serverinfo.back.height           = 64;
     s_serverinfo.back.focuspic         = SERVERINFO_BACK1;
     trap_GetConfigString( CS_SERVERINFO, s_serverinfo.info, MAX_INFO_STRING );
     s_serverinfo.numlines = 0;
     s = s_serverinfo.info;
     while ( s ) {
         Info_NextPair( &s, key, value );
         if ( !key[0] ) {
             break;
         }
         s_serverinfo.numlines++;
     }
     if (s_serverinfo.numlines > 16)
         s_serverinfo.numlines = 16;
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.add );
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.back );
     UI_PushMenu( &s_serverinfo.menu );
 }
References serverinfo_t::add, serverinfo_t::back, serverinfo_t::banner, menucommon_s::callback, menutext_s::color, color_white, CS_SERVERINFO, menucommon_s::flags, menubitmap_s::focuspic, serverinfo_t::framel, serverinfo_t::framer, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_ADD, ID_BACK, serverinfo_t::info, Info_NextPair(), MAX_INFO_KEY, MAX_INFO_STRING, MAX_INFO_VALUE, serverinfo_t::menu, Menu_AddItem(), uiStatic_t::menuamount, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, menucommon_s::name, serverinfo_t::numlines, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s_serverinfo, SERVERINFO_BACK0, SERVERINFO_BACK1, ServerInfo_Cache(), ServerInfo_Event(), SERVERINFO_FRAMEL, SERVERINFO_FRAMER, ServerInfo_MenuDraw(), ServerInfo_MenuKey(), menutext_s::string, menutext_s::style, trap_Cvar_VariableValue(), trap_GetConfigString(), menucommon_s::type, UI_CENTER, UI_DROPSHADOW, UI_PushMenu(), UI_SMALLFONT, uis, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
UI_SetActiveMenu()
void UI_SetActiveMenu (uiMenuCommand_t menu)
Definition at line 808 of file ui_atoms.c.
{
     //Menu_Cache();
     switch(menu){
         case UIMENU_NONE:
             UI_ForceMenuOff();
             return;
         case UIMENU_MAIN:
             UI_MainMenu();
             return;
         case UIMENU_INGAME:
             trap_Cvar_Set("cl_paused","1");
             UI_InGameMenu();
             return;
         case UIMENU_TEAM:
         case UIMENU_POSTGAME:
         default:
           Com_Printf("UI_SetActiveMenu: bad enum %d\n", menu );
           break;
     }
 }
References Com_Printf(), trap_Cvar_Set(), UI_ForceMenuOff(), UI_InGameMenu(), UI_MainMenu(), UIMENU_INGAME, UIMENU_MAIN, UIMENU_NONE, UIMENU_POSTGAME, and UIMENU_TEAM.
Referenced by vmMain().
UI_SetColor()
void UI_SetColor (const float * rgba)
Definition at line 1064 of file ui_atoms.c.
{
     trap_R_SetColor( rgba );
 }
References trap_R_SetColor().
Referenced by Slider_Draw(), UI_DrawConnectScreen(), and UI_Refresh().
UI_SetupMenu()
void UI_SetupMenu (void)
UI_SetupMenu_Cache()
void UI_SetupMenu_Cache (void)
UI_Shutdown()
void UI_Shutdown (void)
Definition at line 962 of file ui_atoms.c.
 {}
Referenced by vmMain().
UI_SpecifyLeagueMenu()
void UI_SpecifyLeagueMenu (void)
UI_SpecifyServerMenu()
void UI_SpecifyServerMenu (void)
UI_StartDemoLoop()
void UI_StartDemoLoop (void)
Definition at line 72 of file ui_atoms.c.
{
     trap_Cmd_ExecuteText( EXEC_APPEND, "d1\n" );
 }
References EXEC_APPEND, and trap_Cmd_ExecuteText().
UI_StartServerMenu()
void UI_StartServerMenu (void)
Definition at line 696 of file ui_startserver.c.
{
     uis.menuamount = 2;
     uis.hideEarth = qtrue;
     uis.showFrame = qtrue;
     StartServer_MenuInit();
     UI_PushMenu( &s_startserver.menu );
 }
References uiStatic_t::hideEarth, startserver_t::menu, uiStatic_t::menuamount, qtrue, s_startserver, uiStatic_t::showFrame, StartServer_MenuInit(), UI_PushMenu(), and uis.
Referenced by ArenaServers_Event().
UI_SystemSettingsMenu()
void UI_SystemSettingsMenu (void)
Definition at line 1219 of file ui_system.c.
{
     uis.menuamount = 4;
     uis.hideEarth = qtrue;
     uis.showFrame = qtrue;
     SystemSettings_MenuInit();
     UI_PushMenu( &s_systemsettings.menu );
     Menu_SetCursorToItem(&s_systemsettings.menu,&s_systemsettings.system);
 }
References uiStatic_t::hideEarth, systemsettings_t::menu, Menu_SetCursorToItem(), uiStatic_t::menuamount, qtrue, s_systemsettings, uiStatic_t::showFrame, systemsettings_t::system, SystemSettings_MenuInit(), UI_PushMenu(), and uis.
Referenced by Controls_MenuEvent(), InGame_Event(), and Preferences_Event().
UI_TeamMainMenu()
void UI_TeamMainMenu (void)
Definition at line 198 of file ui_team.c.
{
     TeamMain_MenuInit();
     UI_PushMenu ( &s_teammain.menu );
 }
References teammain_t::menu, s_teammain, TeamMain_MenuInit(), and UI_PushMenu().
Referenced by InGame_Event().
UI_TeamOrdersMenu()
void UI_TeamOrdersMenu (void)
UI_TeamOrdersMenu_Cache()
void UI_TeamOrdersMenu_Cache (void)
UI_TeamOrdersMenu_f()
void UI_TeamOrdersMenu_f (void)
UI_UpdateCvars()
void UI_UpdateCvars (void)
Definition at line 199 of file ui_main.c.
{
     int         i;
     cvarTable_t *cv;
     for ( i = 0, cv = cvarTable ; i < cvarTableSize ; i++, cv++ ) {
         trap_Cvar_Update( cv->vmCvar );
     }
 }
References cvarTable, cvarTableSize, trap_Cvar_Update(), and cvarTable_t::vmCvar.
Referenced by UI_Refresh().
UI_UpdateScreen()
void UI_UpdateScreen (void)
Definition at line 1068 of file ui_atoms.c.
{
     trap_UpdateScreen();
 }
References trap_UpdateScreen().
Variable Documentation
color_black
vec4_t color_black
Definition at line 42 of file ui_qmenu.c.
color_blue
vec4_t color_blue
Definition at line 45 of file ui_qmenu.c.
color_dim
vec4_t color_dim
Definition at line 50 of file ui_qmenu.c.
color_orange
vec4_t color_orange
Definition at line 47 of file ui_qmenu.c.
Referenced by StartServer_LevelshotDraw().
color_red
vec4_t color_red
Definition at line 48 of file ui_qmenu.c.
Referenced by MessageMenu_Draw(), and UI_Message().
color_silver
vec4_t color_silver
Definition at line 49 of file ui_qmenu.c.
Referenced by ArenaServers_MenuInit(), Controls_MenuInit(), PlayerModel_MenuInit(), Preferences_MenuInit(), and SystemSettings_MenuInit().
color_white
vec4_t color_white
Definition at line 43 of file ui_qmenu.c.
Referenced by ArenaServers_MenuInit(), Camera_MenuInit(), ConfirmMenu_Draw(), InGame_MenuInit(), MainMenu_DrawName(), Music_MenuInit(), Options_MenuInit(), PlayerModel_DrawPlayer(), PlayerModel_MenuInit(), ServerInfo_MenuDraw(), StartServer_MenuInit(), UI_ConfirmMenu_Style(), UI_CreditMenu_Draw(), UI_DisplayDownloadInfo(), UI_DrawConnectScreen(), UI_MainMenu(), and UI_ServerInfoMenu().
color_yellow
vec4_t color_yellow
Definition at line 44 of file ui_qmenu.c.
Referenced by Controls_ResetDefaults_Draw().
list_color
vec4_t list_color
listbar_color
vec4_t listbar_color
Definition at line 57 of file ui_qmenu.c.
Referenced by Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), and ScrollList_Draw().
m_entersound
qboolean m_entersound
Definition at line 31 of file ui_atoms.c.
Referenced by UI_PushMenu(), and UI_Refresh().
menu_black_color
vec4_t menu_black_color
menu_buzz_sound
sfxHandle_t menu_buzz_sound
Definition at line 33 of file ui_qmenu.c.
Referenced by Menu_Cache(), MenuField_Key(), PlayerModel_MenuKey(), ScrollList_Key(), Slider_Key(), and SpinControl_Key().
menu_dark_color
vec4_t menu_dark_color
menu_dim_color
vec4_t menu_dim_color
Definition at line 41 of file ui_qmenu.c.
menu_exit_sound
sfxHandle_t menu_exit_sound
Definition at line 35 of file ui_qmenu.c.
Referenced by Menu_Cache(), and UI_CreditMenu().
menu_grayed_color
vec4_t menu_grayed_color
menu_highlight_color
vec4_t menu_highlight_color
menu_in_sound
sfxHandle_t menu_in_sound
Definition at line 30 of file ui_qmenu.c.
Referenced by Menu_Cache(), and UI_Refresh().
menu_move_sound
sfxHandle_t menu_move_sound
Definition at line 31 of file ui_qmenu.c.
Referenced by ArenaServers_MenuKey(), Menu_ActivateItem(), Menu_Cache(), Menu_DefaultKey(), PlayerModel_MenuKey(), RadioButton_Key(), ScrollList_Key(), Slider_Key(), SpinControl_Key(), and UI_MouseEvent().
menu_null_sound
sfxHandle_t menu_null_sound
Definition at line 34 of file ui_qmenu.c.
Referenced by ErrorMessage_Key(), Menu_Cache(), ScrollList_Key(), and UI_KeyEvent().
menu_out_sound
sfxHandle_t menu_out_sound
Definition at line 32 of file ui_qmenu.c.
Referenced by Controls_MenuKey(), Menu_Cache(), Menu_DefaultKey(), and UI_PopMenu().
menu_red_color
vec4_t menu_red_color
menu_text_color
vec4_t menu_text_color
Definition at line 40 of file ui_qmenu.c.
Referenced by Action_Draw(), and ArenaServers_MenuInit().
name_color
vec4_t name_color
s_mastermusicvolume
vmCvar_t s_mastermusicvolume
Definition at line 136 of file ui_main.c.
text_color_disabled
vec4_t text_color_disabled
Definition at line 54 of file ui_qmenu.c.
Referenced by Action_Draw(), BText_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), PText_Draw(), RadioButton_Draw(), Slider_Draw(), SpinControl_Draw(), and Text_Draw().
text_color_highlight
vec4_t text_color_highlight
Definition at line 56 of file ui_qmenu.c.
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MainMenu_DrawName(), MenuField_Draw(), RadioButton_Draw(), ScrollList_Draw(), Slider_Draw(), and SpinControl_Draw().
text_color_normal
vec4_t text_color_normal
Definition at line 55 of file ui_qmenu.c.
Referenced by ArenaServers_MenuInit(), Controls_MenuInit(), Crosshair_Draw(), MainMenu_DrawName(), MenuField_Draw(), PlayerModel_MenuInit(), RadioButton_Draw(), ScrollList_Draw(), ServerInfo_MenuDraw(), Slider_Draw(), SpinControl_Draw(), and StartServer_MenuInit().
ui_brassTime
vmCvar_t ui_brassTime
Definition at line 114 of file ui_main.c.
ui_browserGameType
vmCvar_t ui_browserGameType
Definition at line 109 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserMaster
vmCvar_t ui_browserMaster
Definition at line 108 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserShowEmpty
vmCvar_t ui_browserShowEmpty
Definition at line 112 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserShowFull
vmCvar_t ui_browserShowFull
Definition at line 111 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserSortKey
vmCvar_t ui_browserSortKey
Definition at line 110 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_drawCrosshair
vmCvar_t ui_drawCrosshair
Definition at line 115 of file ui_main.c.
ui_drawCrosshairNames
vmCvar_t ui_drawCrosshairNames
Definition at line 116 of file ui_main.c.
ui_ffa_breakLimitRate
vmCvar_t ui_ffa_breakLimitRate
Definition at line 104 of file ui_main.c.
ui_ffa_fraglimit
vmCvar_t ui_ffa_fraglimit
Definition at line 100 of file ui_main.c.
ui_ffa_powerlevel
vmCvar_t ui_ffa_powerlevel
Definition at line 102 of file ui_main.c.
ui_ffa_powerlevelMaximum
vmCvar_t ui_ffa_powerlevelMaximum
Definition at line 103 of file ui_main.c.
ui_ffa_timelimit
vmCvar_t ui_ffa_timelimit
Definition at line 101 of file ui_main.c.
ui_marks
vmCvar_t ui_marks
Definition at line 117 of file ui_main.c.
ui_medalNames
char* ui_medalNames[]
ui_medalPicNames
char* ui_medalPicNames[]
ui_medalSounds
char* ui_medalSounds[]
ui_server1
vmCvar_t ui_server1
Definition at line 119 of file ui_main.c.
ui_server10
vmCvar_t ui_server10
Definition at line 128 of file ui_main.c.
ui_server11
vmCvar_t ui_server11
Definition at line 129 of file ui_main.c.
ui_server12
vmCvar_t ui_server12
Definition at line 130 of file ui_main.c.
ui_server13
vmCvar_t ui_server13
Definition at line 131 of file ui_main.c.
ui_server14
vmCvar_t ui_server14
Definition at line 132 of file ui_main.c.
ui_server15
vmCvar_t ui_server15
Definition at line 133 of file ui_main.c.
ui_server16
vmCvar_t ui_server16
Definition at line 134 of file ui_main.c.
ui_server2
vmCvar_t ui_server2
Definition at line 120 of file ui_main.c.
ui_server3
vmCvar_t ui_server3
Definition at line 121 of file ui_main.c.
ui_server4
vmCvar_t ui_server4
Definition at line 122 of file ui_main.c.
ui_server5
vmCvar_t ui_server5
Definition at line 123 of file ui_main.c.
ui_server6
vmCvar_t ui_server6
Definition at line 124 of file ui_main.c.
ui_server7
vmCvar_t ui_server7
Definition at line 125 of file ui_main.c.
ui_server8
vmCvar_t ui_server8
Definition at line 126 of file ui_main.c.
ui_server9
vmCvar_t ui_server9
Definition at line 127 of file ui_main.c.
uis
uiStatic_t uis
Definition at line 30 of file ui_atoms.c.
Referenced by ArenaServers_DoRefresh(), ArenaServers_MenuDraw(), ArenaServers_MenuInit(), ArenaServers_StartRefresh(), Bitmap_Draw(), ConfirmMenu_Draw(), Controls_DrawPlayer(), Main_MenuDraw(), MainMenu_DrawPlayer(), Menu_Cache(), Menu_Common(), Menu_DefaultKey(), Menu_Draw(), Menu_Frame(), PlayerModel_DrawPlayer(), RadioButton_Draw(), ScrollList_Key(), Slider_Key(), SystemSettings_MenuInit(), UI_AdjustFrom640(), UI_ConfirmMenu_Style(), UI_ControlsMenu(), UI_CreditMenu(), UI_CursorInRect(), UI_DisplayDownloadInfo(), UI_DrawBackPic(), UI_DrawBannerString2(), UI_DrawProportionalString(), UI_DrawProportionalString2(), UI_DrawRect(), UI_DrawString(), UI_DrawString2(), UI_FillRect(), UI_ForceMenuOff(), UI_InGameMenu(), UI_Init(), UI_InitGameinfo(), UI_IsFullscreen(), UI_KeyEvent(), UI_MainMenu(), UI_MenuLogo(), UI_MenuScene(), UI_MouseEvent(), UI_PlayerAnimation(), UI_PlayerModelMenu(), UI_PopMenu(), UI_PreferencesMenu(), UI_PushMenu(), UI_Refresh(), UI_ServerInfoMenu(), UI_StartServerMenu(), UI_SwingAngles(), UI_SystemConfigMenu(), and UI_SystemSettingsMenu().