ZEQ2-Lite: Source/Game/Game/g_userweapons.h File Reference
g_userweapons.h File Reference
Data Structures
struct g_userWeapon_t
Typedefs
typedef g_userWeapon_t g_userWeaponParseBuffer_t
Enumerations
enum userWeaponHoming_t {
HOM_NONE, HOM_PROX, HOM_GUIDED, HOM_REGULAR,
HOM_ARCH, HOM_DRUNKEN, HOM_CYLINDER
}
enum userWeaponType_t {
skillTypeMISSILE, skillTypeBEAM, skillTypeHITSCAN, skillTypeTRIGGER,
skillTypeNONE
}
Functions
g_userWeapon_t * G_FindUserAltWeaponData (int clientNum, int weaponNum)
g_userWeapon_t * G_FindUserAltWeaponSpawnData (int clientNum, int weaponNum)
g_userWeapon_t * G_FindUserWeaponData (int clientNum, int weaponNum)
int * G_FindUserWeaponMask (int clientNum)
g_userWeapon_t * G_FindUserWeaponSpawnData (int clientNum, int weaponNum)
void G_LinkUserWeaponData (playerState_t *ps)
Typedef Documentation
g_userWeaponParseBuffer_t
typedef g_userWeapon_t g_userWeaponParseBuffer_t
Definition at line 101 of file g_userweapons.h.
Enumeration Type Documentation
userWeaponHoming_t
enum userWeaponHoming_t
Enumerator
HOM_NONE
HOM_PROX
HOM_GUIDED
HOM_REGULAR
HOM_ARCH
HOM_DRUNKEN
HOM_CYLINDER
Definition at line 8 of file g_userweapons.h.
             {
     HOM_NONE,       //  Attack doesn't home in any way.
     HOM_PROX,       //  As soon as a target enters homing range the attack detonates.
     HOM_GUIDED,     //  Attack is guided by the player. ( NOTE: Bots will use a special kind of homing. )
     HOM_REGULAR,    //  Attack can pickup targets within its range and vision.
     HOM_ARCH,       //  Attack will arch outwards and curve back inwards towards opponents registered location.
     HOM_DRUNKEN,    //  Attack will wobble around drunkenly
     HOM_CYLINDER    //  Attack can only pickup targets in a cylinder, extending downwards from
                     //  a little below its current position. ( NOTE: A little below, to prevent
                     //  turning into horizontal travel.)
                     //  FIXME: Do we really need this special case for Kakusan Ha?
                     //  NOTE:  We probably do...
 }userWeaponHoming_t;
userWeaponType_t
enum userWeaponType_t
Enumerator
skillTypeMISSILE
skillTypeBEAM
skillTypeHITSCAN
skillTypeTRIGGER
skillTypeNONE
Definition at line 1 of file g_userweapons.h.
             {
     skillTypeMISSILE,   //  Default missile type; ki blasts, discs, etc.
     skillTypeBEAM,      //  Beam type
     skillTypeHITSCAN,   //  Rail- / lightninggun style hitscan attack
     skillTypeTRIGGER,   //  For redirecting an existing weapon.
     skillTypeNONE       //  Useful for self-healing, since it spawns nothing.
 }userWeaponType_t;
Function Documentation
G_FindUserAltWeaponData()
g_userWeapon_t* G_FindUserAltWeaponData (int clientNum, int weaponNum)
Definition at line 40 of file g_userweapons.c.
{
     return &weaponPhysicsDatabase[clientNum][weaponNum - 1 + ALTWEAPON_OFFSET];
 }
References ALTWEAPON_OFFSET, and weaponPhysicsDatabase.
Referenced by Fire_UserWeapon(), and G_LinkUserWeaponData().
G_FindUserAltWeaponSpawnData()
g_userWeapon_t* G_FindUserAltWeaponSpawnData (int clientNum, int weaponNum)
Definition at line 49 of file g_userweapons.c.
{
     return &weaponPhysicsDatabase[clientNum][weaponNum - 1 + ALTSPAWN_OFFSET];
 }
References ALTSPAWN_OFFSET, and weaponPhysicsDatabase.
G_FindUserWeaponData()
g_userWeapon_t* G_FindUserWeaponData (int clientNum, int weaponNum)
Definition at line 22 of file g_userweapons.c.
{
     return &weaponPhysicsDatabase[clientNum][weaponNum - 1];
 }
References weaponPhysicsDatabase.
Referenced by Fire_UserWeapon(), G_CheckSkills(), G_LinkUserWeaponData(), and G_weapPhys_StoreBuffer().
G_FindUserWeaponMask()
int* G_FindUserWeaponMask (int clientNum)
Definition at line 13 of file g_userweapons.c.
{
     return &weaponPhysicsMasks[clientNum];
 }
References weaponPhysicsMasks.
Referenced by ClientSpawn(), ClientUserinfoChanged(), and G_weapPhys_Parse().
G_FindUserWeaponSpawnData()
g_userWeapon_t* G_FindUserWeaponSpawnData (int clientNum, int weaponNum)
Definition at line 31 of file g_userweapons.c.
{
     return &weaponPhysicsDatabase[clientNum][weaponNum - 1 + SPAWN_OFFSET];
 }
References SPAWN_OFFSET, and weaponPhysicsDatabase.
G_LinkUserWeaponData()
void G_LinkUserWeaponData (playerState_t * ps)
Definition at line 106 of file g_userweapons.c.
{
     g_userWeapon_t  *weaponSettings;
     g_userWeapon_t  *alt_weaponSettings;
     // Prevent reading below bound of array pointed to by weaponSettings.
     if ( ps->weapon == WP_NONE ) {
         memset(ps->currentSkill, 0, sizeof(ps->currentSkill) );
         return;
     }
     // NOTE: This function will NEVER be able to be called with a weapon that
     //       was not defined, so the next statement is SAFE.
     weaponSettings = G_FindUserWeaponData( ps->clientNum, ps->weapon );
     ps->currentSkill[WPSTAT_NUMCHECK] = ps->weapon;
     ps->currentSkill[WPSTAT_POWER] = weaponSettings->damage_damage;
     ps->currentSkill[WPSTAT_POWERLEVELCOST] = weaponSettings->costs_powerLevel;
     ps->currentSkill[WPSTAT_MAXIMUMCOST] = weaponSettings->costs_maximum;
     ps->currentSkill[WPSTAT_HEALTHCOST] = weaponSettings->costs_health;
     ps->currentSkill[WPSTAT_FATIGUECOST] = weaponSettings->costs_fatigue;
     ps->currentSkill[WPSTAT_CHRGTIME] = weaponSettings->costs_chargeTime;
     ps->currentSkill[WPSTAT_CHRGREADY] = weaponSettings->costs_chargeReady;
     ps->currentSkill[WPSTAT_COOLTIME] = weaponSettings->costs_cooldownTime;
     ps->currentSkill[WPSTAT_RESTRICT_MOVEMENT] = weaponSettings->restrict_movement;
     ps->currentSkill[WPSTAT_BITFLAGS] = weaponSettings->general_bitflags;
     ps->currentSkill[WPSTAT_RESTRICT_MOVEMENT] = weaponSettings->restrict_movement;
     // Set the ready state of a charged weapon
     if ( ( ps->stats[stChargePercentPrimary] >= weaponSettings->costs_chargeReady ) && ( ps->currentSkill[WPSTAT_BITFLAGS] & WPF_NEEDSCHARGE ) ) {
         ps->currentSkill[WPSTAT_BITFLAGS] |= WPF_READY;
     } else {
         ps->currentSkill[WPSTAT_BITFLAGS] &= ~WPF_READY;
     }
     // Guided trajectories and beams should use WEAPON_GUIDING state
     if ( weaponSettings->homing_type == HOM_GUIDED || weaponSettings->general_type == skillTypeBEAM ) {
         ps->currentSkill[WPSTAT_BITFLAGS] |= WPF_GUIDED;
     }
     // Only attempt to link altfire weapon when it exists.
     if (ps->currentSkill[WPSTAT_BITFLAGS] & WPF_ALTWEAPONPRESENT) {
         alt_weaponSettings = G_FindUserAltWeaponData( ps->clientNum, ps->weapon );
         ps->currentSkill[WPSTAT_ALT_POWER] = alt_weaponSettings->damage_damage;
         ps->currentSkill[WPSTAT_ALT_POWERLEVELCOST] = alt_weaponSettings->costs_powerLevel;
         ps->currentSkill[WPSTAT_ALT_MAXIMUMCOST] = alt_weaponSettings->costs_maximum;
         ps->currentSkill[WPSTAT_ALT_HEALTHCOST] = alt_weaponSettings->costs_health;
         ps->currentSkill[WPSTAT_ALT_FATIGUECOST] = alt_weaponSettings->costs_fatigue;
         ps->currentSkill[WPSTAT_ALT_CHRGTIME] = alt_weaponSettings->costs_chargeTime;
         ps->currentSkill[WPSTAT_ALT_CHRGREADY] = alt_weaponSettings->costs_chargeReady;
         ps->currentSkill[WPSTAT_ALT_COOLTIME] = alt_weaponSettings->costs_cooldownTime;
         ps->currentSkill[WPSTAT_ALT_RESTRICT_MOVEMENT] = alt_weaponSettings->restrict_movement;
         ps->currentSkill[WPSTAT_ALT_BITFLAGS] = alt_weaponSettings->general_bitflags;
         ps->currentSkill[WPSTAT_ALT_RESTRICT_MOVEMENT] = alt_weaponSettings->restrict_movement;
         // Guided trajectories and beams should use WEAPON_GUIDING state
         if ( alt_weaponSettings->homing_type == HOM_GUIDED || alt_weaponSettings->general_type == skillTypeBEAM ) {
             ps->currentSkill[WPSTAT_ALT_BITFLAGS] |= WPF_GUIDED;
         }
         // Set the ready state of a charged altfire weapon
         if ( ( ps->stats[stChargePercentSecondary] >= alt_weaponSettings->costs_chargeReady ) && ( ps->currentSkill[WPSTAT_ALT_BITFLAGS] & WPF_NEEDSCHARGE ) ) {
             ps->currentSkill[WPSTAT_ALT_BITFLAGS] |= WPF_READY;
         } else {
             ps->currentSkill[WPSTAT_ALT_BITFLAGS] &= ~WPF_READY;
         }
     }
 }
References g_userWeapon_t::costs_chargeReady, g_userWeapon_t::costs_chargeTime, g_userWeapon_t::costs_cooldownTime, g_userWeapon_t::costs_fatigue, g_userWeapon_t::costs_health, g_userWeapon_t::costs_maximum, g_userWeapon_t::costs_powerLevel, g_userWeapon_t::damage_damage, G_FindUserAltWeaponData(), G_FindUserWeaponData(), g_userWeapon_t::general_bitflags, g_userWeapon_t::general_type, HOM_GUIDED, g_userWeapon_t::homing_type, g_userWeapon_t::restrict_movement, skillTypeBEAM, stChargePercentPrimary, stChargePercentSecondary, WP_NONE, WPF_ALTWEAPONPRESENT, WPF_GUIDED, WPF_NEEDSCHARGE, WPF_READY, WPSTAT_ALT_BITFLAGS, WPSTAT_ALT_CHRGREADY, WPSTAT_ALT_CHRGTIME, WPSTAT_ALT_COOLTIME, WPSTAT_ALT_FATIGUECOST, WPSTAT_ALT_HEALTHCOST, WPSTAT_ALT_MAXIMUMCOST, WPSTAT_ALT_POWER, WPSTAT_ALT_POWERLEVELCOST, WPSTAT_ALT_RESTRICT_MOVEMENT, WPSTAT_BITFLAGS, WPSTAT_CHRGREADY, WPSTAT_CHRGTIME, WPSTAT_COOLTIME, WPSTAT_FATIGUECOST, WPSTAT_HEALTHCOST, WPSTAT_MAXIMUMCOST, WPSTAT_NUMCHECK, WPSTAT_POWER, WPSTAT_POWERLEVELCOST, and WPSTAT_RESTRICT_MOVEMENT.
Referenced by ClientThink_real().