ZEQ2-Lite: Engine/libspeex/buffer.c File Reference
buffer.c File Reference
#include "os_support.h"
#include "arch.h"
#include <speex/speex_buffer.h>
Data Structures
struct SpeexBuffer
Functions
void speex_buffer_destroy (SpeexBuffer *st)
int speex_buffer_get_available (SpeexBuffer *st)
SpeexBuffer * speex_buffer_init (int size)
int speex_buffer_read (SpeexBuffer *st, void *_data, int len)
int speex_buffer_resize (SpeexBuffer *st, int len)
int speex_buffer_write (SpeexBuffer *st, void *_data, int len)
int speex_buffer_writezeros (SpeexBuffer *st, int len)
Function Documentation
speex_buffer_destroy()
void speex_buffer_destroy (SpeexBuffer * st)
Definition at line 62 of file buffer.c.
 {
    speex_free(st->data);
    speex_free(st);
 }
References speex_free().
speex_buffer_get_available()
int speex_buffer_get_available (SpeexBuffer * st)
Definition at line 159 of file buffer.c.
 {
    return st->available;
 }
speex_buffer_init()
SpeexBuffer* speex_buffer_init (int size)
Definition at line 51 of file buffer.c.
 {
    SpeexBuffer *st = speex_alloc(sizeof(SpeexBuffer));
    st->data = speex_alloc(size);
    st->size = size;
    st->read_ptr = 0;
    st->write_ptr = 0;
    st->available = 0;
    return st;
 }
References speex_alloc().
speex_buffer_read()
int speex_buffer_read (SpeexBuffer * st, void * _data, int len)
Definition at line 132 of file buffer.c.
 {
    int end, end1;
    char *data = _data;
    if (len > st->available)
    {
       SPEEX_MEMSET(data+st->available, 0, st->size-st->available);
       len = st->available;
    }
    end = st->read_ptr + len;
    end1 = end;
    if (end1 > st->size)
       end1 = st->size;
    SPEEX_COPY(data, st->data + st->read_ptr, end1 - st->read_ptr);
    if (end > st->size)
    {
       end -= st->size;
       SPEEX_COPY(data+end1 - st->read_ptr, st->data, end);
    }
    st->available -= len;
    st->read_ptr += len;
    if (st->read_ptr > st->size)
       st->read_ptr -= st->size;
    return len;
 }
References SPEEX_COPY, and SPEEX_MEMSET.
speex_buffer_resize()
int speex_buffer_resize (SpeexBuffer * st, int len)
Definition at line 164 of file buffer.c.
 {
    int old_len = st->size;
    if (len > old_len)
    {
       st->data = speex_realloc(st->data, len);
       /* FIXME: move data/pointers properly for growing the buffer */
    } else {
       /* FIXME: move data/pointers properly for shrinking the buffer */
       st->data = speex_realloc(st->data, len);
    }
    return len;
 }
References speex_realloc().
speex_buffer_write()
int speex_buffer_write (SpeexBuffer * st, void * _data, int len)
Definition at line 68 of file buffer.c.
 {
    int end;
    int end1;
    char *data = _data;
    if (len > st->size)
    {
       data += len-st->size;
       len = st->size;
    }
    end = st->write_ptr + len;
    end1 = end;
    if (end1 > st->size)
       end1 = st->size;
    SPEEX_COPY(st->data + st->write_ptr, data, end1 - st->write_ptr);
    if (end > st->size)
    {
       end -= st->size;
       SPEEX_COPY(st->data, data+end1 - st->write_ptr, end);
    }
    st->available += len;
    if (st->available > st->size)
    {
       st->available = st->size;
       st->read_ptr = st->write_ptr;
    }
    st->write_ptr += len;
    if (st->write_ptr > st->size)
       st->write_ptr -= st->size;
    return len;
 }
References SPEEX_COPY.
speex_buffer_writezeros()
int speex_buffer_writezeros (SpeexBuffer * st, int len)
Definition at line 100 of file buffer.c.
 {
    /* This is almost the same as for speex_buffer_write() but using
    SPEEX_MEMSET() instead of SPEEX_COPY(). Update accordingly. */
    int end;
    int end1;
    if (len > st->size)
    {
       len = st->size;
    }
    end = st->write_ptr + len;
    end1 = end;
    if (end1 > st->size)
       end1 = st->size;
    SPEEX_MEMSET(st->data + st->write_ptr, 0, end1 - st->write_ptr);
    if (end > st->size)
    {
       end -= st->size;
       SPEEX_MEMSET(st->data, 0, end);
    }
    st->available += len;
    if (st->available > st->size)
    {
       st->available = st->size;
       st->read_ptr = st->write_ptr;
    }
    st->write_ptr += len;
    if (st->write_ptr > st->size)
       st->write_ptr -= st->size;
    return len;
 }
References SPEEX_MEMSET.