ZEQ2-Lite: Policy-Based Data Structures
Policy-Based Data Structures
Data Structures
class __gnu_pbds::basic_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, Tag, Policy_TL, Allocator >
An abstract basic hash-based associative container.
class __gnu_pbds::basic_tree< Key, Mapped, Tag, Node_Update, Policy_Tl, Allocator >
An abstract basic tree-like (tree, trie) associative container.
class __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >
A concrete collision-chaining hash-based associative container.
class __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >
An abstract basic associative container.
class __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >
A concrete general-probing hash-based associative container.
class __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >
A list-update based associative container.
class __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >
A concrete basic tree-based associative container.
class __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >
A concrete basic trie-based associative container.
Macros
#define PB_DS_BASE_C_DEC detail::container_base_dispatch<Key, Mapped, Tag, Policy_Tl, Allocator>::type
#define PB_DS_BASE_C_DEC
#define PB_DS_BASE_C_DEC
#define PB_DS_BASE_C_DEC
#define PB_DS_BASE_C_DEC container_base<Key, Mapped, Tag, Policy_Tl, Allocator>
#define PB_DS_BASE_C_DEC
#define PB_DS_BASE_C_DEC
#define PB_DS_BASE_C_DEC
#define PB_DS_CLASS_NAME container_base
#define PB_DS_CLASS_NAME basic_hash_table
#define PB_DS_CLASS_NAME basic_tree
#define PB_DS_TREE_NODE_AND_IT_TRAITS_C_DEC detail::tree_traits<Key, Mapped,Cmp_Fn,Node_Update,Tag, Allocator>
#define PB_DS_TRIE_NODE_AND_ITS_TRAITS detail::trie_traits<Key,Mapped,E_Access_Traits,Node_Update,Tag,Allocator>
Typedefs
typedef Allocator __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::allocator
typedef Allocator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::allocator_type
typedef PB_DS_BASE_C_DEC __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::base_type
typedef PB_DS_BASE_C_DEC __gnu_pbds::basic_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, Tag, Policy_TL, Allocator >::base_type
typedef PB_DS_BASE_C_DEC __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::base_type
typedef PB_DS_BASE_C_DEC __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::base_type
typedef PB_DS_BASE_C_DEC __gnu_pbds::basic_tree< Key, Mapped, Tag, Node_Update, Policy_Tl, Allocator >::base_type
typedef PB_DS_BASE_C_DEC __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::base_type
typedef PB_DS_BASE_C_DEC __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::base_type
typedef PB_DS_BASE_C_DEC __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::base_type
typedef Cmp_Fn __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::cmp_fn
typedef Comb_Hash_Fn __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::comb_hash_fn
typedef Comb_Probe_Fn __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::comb_probe_fn
typedef base_type::const_iterator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_iterator
typedef key_rebind::const_pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_key_pointer
typedef key_rebind::const_reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_key_reference
typedef mapped_rebind::const_pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_mapped_pointer
typedef mapped_rebind::const_reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_mapped_reference
typedef base_type::const_point_iterator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_point_iterator
typedef value_rebind::const_pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_pointer
typedef value_rebind::const_reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_reference
typedef Tag __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::container_category
typedef allocator_type::difference_type __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::difference_type
typedef E_Access_Traits __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::e_access_traits
typedef Eq_Fn __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::eq_fn
typedef Eq_Fn __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::eq_fn
typedef Eq_Fn __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::eq_fn
typedef Hash_Fn __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::hash_fn
typedef Hash_Fn __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::hash_fn
typedef base_type::iterator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::iterator
typedef key_rebind::pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::key_pointer
typedef allocator_type::template rebind< key_type >::other __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::key_rebind
typedef key_rebind::reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::key_reference
typedef allocator_type::template rebind< Key >::other::value_type __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::key_type
typedef mapped_rebind::pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::mapped_pointer
typedef allocator_type::template rebind< mapped_type >::other __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::mapped_rebind
typedef mapped_rebind::reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::mapped_reference
typedef Mapped __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::mapped_type
typedef Node_Update __gnu_pbds::basic_tree< Key, Mapped, Tag, Node_Update, Policy_Tl, Allocator >::node_update
typedef base_type::point_iterator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::point_iterator
typedef value_rebind::pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::pointer
typedef Probe_Fn __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::probe_fn
typedef value_rebind::reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::reference
typedef Resize_Policy __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::resize_policy
typedef Resize_Policy __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::resize_policy
typedef allocator_type::size_type __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::size_type
typedef Update_Policy __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::update_policy
typedef allocator_type::template rebind< value_type >::other __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::value_rebind
typedef base_type::value_type __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::value_type
Functions
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table ()
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const cc_hash_table &other)
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const hash_fn &h)
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const hash_fn &h, const eq_fn &e)
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const hash_fn &h, const eq_fn &e, const comb_hash_fn &ch)
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const hash_fn &h, const eq_fn &e, const comb_hash_fn &ch, const resize_policy &rp)
template<typename It >
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last)
template<typename It >
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last, const hash_fn &h)
template<typename It >
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last, const hash_fn &h, const eq_fn &e)
template<typename It >
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last, const hash_fn &h, const eq_fn &e, const comb_hash_fn &ch)
template<typename It >
__gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last, const hash_fn &h, const eq_fn &e, const comb_hash_fn &ch, const resize_policy &rp)
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table ()
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const gp_hash_table &other)
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn &h)
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn &h, const eq_fn &e)
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn &h, const eq_fn &e, const comb_probe_fn &cp)
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn &h, const eq_fn &e, const comb_probe_fn &cp, const probe_fn &p)
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn &h, const eq_fn &e, const comb_probe_fn &cp, const probe_fn &p, const resize_policy &rp)
template<typename It >
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last)
template<typename It >
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn &h)
template<typename It >
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn &h, const eq_fn &e)
template<typename It >
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn &h, const eq_fn &e, const comb_probe_fn &cp)
template<typename It >
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn &h, const eq_fn &e, const comb_probe_fn &cp, const probe_fn &p)
template<typename It >
__gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn &h, const eq_fn &e, const comb_probe_fn &cp, const probe_fn &p, const resize_policy &rp)
__gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::list_update ()
__gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::list_update (const list_update &other)
template<typename It >
__gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::list_update (It first, It last)
__gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree ()
__gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree (const cmp_fn &c)
__gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree (const tree &other)
template<typename It >
__gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree (It first, It last)
template<typename It >
__gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree (It first, It last, const cmp_fn &c)
__gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie ()
__gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie (const e_access_traits &t)
__gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie (const trie &other)
template<typename It >
__gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie (It first, It last)
template<typename It >
__gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie (It first, It last, const e_access_traits &t)
virtual __gnu_pbds::basic_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, Tag, Policy_TL, Allocator >::~basic_hash_table ()
virtual __gnu_pbds::basic_tree< Key, Mapped, Tag, Node_Update, Policy_Tl, Allocator >::~basic_tree ()
virtual __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::~cc_hash_table ()
virtual __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::~container_base ()
virtual __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::~gp_hash_table ()
virtual __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::~list_update ()
virtual __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::~tree ()
virtual __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::~trie ()
basic_hash_table & __gnu_pbds::basic_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, Tag, Policy_TL, Allocator >::operator= (const base_type &)
cc_hash_table & __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::operator= (const cc_hash_table &other)
gp_hash_table & __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::operator= (const gp_hash_table &other)
list_update & __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::operator= (const list_update &other)
tree & __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::operator= (const tree &other)
trie & __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::operator= (const trie &other)
void __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::swap (cc_hash_table &other)
void __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::swap (gp_hash_table &other)
void __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::swap (list_update &other)
void __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::swap (tree &other)
void __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::swap (trie &other)
Detailed Description
This is a library of policy-based elementary data structures: associative containers and priority queues. It is designed for high-performance, flexibility, semantic safety, and conformance to the corresponding containers in std (except for some points where it differs by design).
For details, see: http://gcc.gnu.org/onlinedocs/libstdc++/ext/pb_ds/index.html
Macro Definition Documentation
PB_DS_BASE_C_DEC [1/8]
#define PB_DS_BASE_C_DEC detail::container_base_dispatch<Key, Mapped, Tag, Policy_Tl, Allocator>::type
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 644 of file assoc_container.hpp.
PB_DS_BASE_C_DEC [2/8]
#define PB_DS_BASE_C_DEC
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Value:
  container_base<Key, Mapped, Tag, typename __gnu_cxx::typelist::append< \
  typename __gnu_cxx::typelist::create4<Hash_Fn, Eq_Fn, Resize_Policy, detail::integral_constant<int, Store_Hash> >::type, Policy_TL>::type, Allocator>
Definition at line 644 of file assoc_container.hpp.
PB_DS_BASE_C_DEC [3/8]
#define PB_DS_BASE_C_DEC
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Value:
  basic_hash_table<Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, \
           cc_hash_tag, \
      typename __gnu_cxx::typelist::create1<Comb_Hash_Fn>::type, Allocator>
Definition at line 644 of file assoc_container.hpp.
PB_DS_BASE_C_DEC [4/8]
#define PB_DS_BASE_C_DEC
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Value:
  basic_hash_table<Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, \
           gp_hash_tag, \
           typename __gnu_cxx::typelist::create2<Comb_Probe_Fn, Probe_Fn>::type, Allocator>
Definition at line 644 of file assoc_container.hpp.
PB_DS_BASE_C_DEC [5/8]
#define PB_DS_BASE_C_DEC container_base<Key, Mapped, Tag, Policy_Tl, Allocator>
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 644 of file assoc_container.hpp.
PB_DS_BASE_C_DEC [6/8]
#define PB_DS_BASE_C_DEC
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Value:
  basic_tree<Key,Mapped,Tag,typename PB_DS_TREE_NODE_AND_IT_TRAITS_C_DEC::node_update, \
         typename __gnu_cxx::typelist::create2<Cmp_Fn, PB_DS_TREE_NODE_AND_IT_TRAITS_C_DEC >::type, Allocator>
Definition at line 644 of file assoc_container.hpp.
PB_DS_BASE_C_DEC [7/8]
#define PB_DS_BASE_C_DEC
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Value:
  basic_tree<Key,Mapped,Tag, typename PB_DS_TRIE_NODE_AND_ITS_TRAITS::node_update, \
         typename __gnu_cxx::typelist::create2<E_Access_Traits, PB_DS_TRIE_NODE_AND_ITS_TRAITS >::type, Allocator>
Definition at line 644 of file assoc_container.hpp.
PB_DS_BASE_C_DEC [8/8]
#define PB_DS_BASE_C_DEC
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Value:
  container_base<Key, Mapped, list_update_tag, \
         typename __gnu_cxx::typelist::create2<Eq_Fn, Update_Policy>::type, Allocator>
Definition at line 644 of file assoc_container.hpp.
PB_DS_CLASS_NAME [1/3]
#define PB_DS_CLASS_NAME container_base
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 489 of file assoc_container.hpp.
PB_DS_CLASS_NAME [2/3]
#define PB_DS_CLASS_NAME basic_hash_table
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 489 of file assoc_container.hpp.
PB_DS_CLASS_NAME [3/3]
#define PB_DS_CLASS_NAME basic_tree
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 489 of file assoc_container.hpp.
PB_DS_TREE_NODE_AND_IT_TRAITS_C_DEC
#define PB_DS_TREE_NODE_AND_IT_TRAITS_C_DEC detail::tree_traits<Key, Mapped,Cmp_Fn,Node_Update,Tag, Allocator>
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 497 of file assoc_container.hpp.
PB_DS_TRIE_NODE_AND_ITS_TRAITS
#define PB_DS_TRIE_NODE_AND_ITS_TRAITS detail::trie_traits<Key,Mapped,E_Access_Traits,Node_Update,Tag,Allocator>
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 568 of file assoc_container.hpp.
Typedef Documentation
allocator
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> typedef Allocator __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::allocator
Definition at line 662 of file assoc_container.hpp.
allocator_type
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef Allocator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::allocator_type
Definition at line 84 of file assoc_container.hpp.
base_type [1/8]
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef PB_DS_BASE_C_DEC __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::base_type private
Definition at line 80 of file assoc_container.hpp.
base_type [2/8]
template<typename Key , typename Mapped , typename Hash_Fn , typename Eq_Fn , typename Resize_Policy , bool Store_Hash, typename Tag , typename Policy_TL , typename Allocator > typedef PB_DS_BASE_C_DEC __gnu_pbds::basic_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, Tag, Policy_TL, Allocator >::base_type private
Definition at line 147 of file assoc_container.hpp.
base_type [3/8]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef PB_DS_BASE_C_DEC __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::base_type private
Definition at line 183 of file assoc_container.hpp.
base_type [4/8]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef PB_DS_BASE_C_DEC __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::base_type private
Definition at line 321 of file assoc_container.hpp.
base_type [5/8]
template<typename Key , typename Mapped , typename Tag , typename Node_Update , typename Policy_Tl , typename Allocator > typedef PB_DS_BASE_C_DEC __gnu_pbds::basic_tree< Key, Mapped, Tag, Node_Update, Policy_Tl, Allocator >::base_type private
Definition at line 480 of file assoc_container.hpp.
base_type [6/8]
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> typedef PB_DS_BASE_C_DEC __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::base_type private
Definition at line 513 of file assoc_container.hpp.
base_type [7/8]
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> typedef PB_DS_BASE_C_DEC __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::base_type private
Definition at line 589 of file assoc_container.hpp.
base_type [8/8]
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> typedef PB_DS_BASE_C_DEC __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::base_type private
Definition at line 657 of file assoc_container.hpp.
cmp_fn
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> typedef Cmp_Fn __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::cmp_fn
Definition at line 517 of file assoc_container.hpp.
comb_hash_fn
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Comb_Hash_Fn __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::comb_hash_fn
Definition at line 189 of file assoc_container.hpp.
comb_probe_fn
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Comb_Probe_Fn __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::comb_probe_fn
Definition at line 326 of file assoc_container.hpp.
const_iterator
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef base_type::const_iterator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_iterator
Definition at line 114 of file assoc_container.hpp.
const_key_pointer
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef key_rebind::const_pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_key_pointer
Definition at line 94 of file assoc_container.hpp.
const_key_reference
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef key_rebind::const_reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_key_reference
Definition at line 92 of file assoc_container.hpp.
const_mapped_pointer
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef mapped_rebind::const_pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_mapped_pointer
Definition at line 102 of file assoc_container.hpp.
const_mapped_reference
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef mapped_rebind::const_reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_mapped_reference
Definition at line 100 of file assoc_container.hpp.
const_point_iterator
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef base_type::const_point_iterator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_point_iterator
Definition at line 116 of file assoc_container.hpp.
const_pointer
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef value_rebind::const_pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_pointer
Definition at line 110 of file assoc_container.hpp.
const_reference
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef value_rebind::const_reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::const_reference
Definition at line 108 of file assoc_container.hpp.
container_category
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef Tag __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::container_category
Definition at line 83 of file assoc_container.hpp.
difference_type
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef allocator_type::difference_type __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::difference_type
Definition at line 86 of file assoc_container.hpp.
e_access_traits
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> typedef E_Access_Traits __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::e_access_traits
Definition at line 593 of file assoc_container.hpp.
eq_fn [1/3]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Eq_Fn __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::eq_fn
Definition at line 187 of file assoc_container.hpp.
eq_fn [2/3]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Eq_Fn __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::eq_fn
Definition at line 325 of file assoc_container.hpp.
eq_fn [3/3]
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> typedef Eq_Fn __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::eq_fn
Definition at line 660 of file assoc_container.hpp.
hash_fn [1/2]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Hash_Fn __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::hash_fn
Definition at line 186 of file assoc_container.hpp.
hash_fn [2/2]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Hash_Fn __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::hash_fn
Definition at line 324 of file assoc_container.hpp.
iterator
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef base_type::iterator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::iterator
Definition at line 113 of file assoc_container.hpp.
key_pointer
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef key_rebind::pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::key_pointer
Definition at line 93 of file assoc_container.hpp.
key_rebind
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef allocator_type::template rebind<key_type>::other __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::key_rebind
Definition at line 90 of file assoc_container.hpp.
key_reference
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef key_rebind::reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::key_reference
Definition at line 91 of file assoc_container.hpp.
key_type
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef allocator_type::template rebind<Key>::other::value_type __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::key_type
Definition at line 89 of file assoc_container.hpp.
mapped_pointer
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef mapped_rebind::pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::mapped_pointer
Definition at line 101 of file assoc_container.hpp.
mapped_rebind
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef allocator_type::template rebind<mapped_type>::other __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::mapped_rebind
Definition at line 98 of file assoc_container.hpp.
mapped_reference
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef mapped_rebind::reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::mapped_reference
Definition at line 99 of file assoc_container.hpp.
mapped_type
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef Mapped __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::mapped_type
Definition at line 97 of file assoc_container.hpp.
node_update
template<typename Key , typename Mapped , typename Tag , typename Node_Update , typename Policy_Tl , typename Allocator > typedef Node_Update __gnu_pbds::basic_tree< Key, Mapped, Tag, Node_Update, Policy_Tl, Allocator >::node_update
Definition at line 483 of file assoc_container.hpp.
point_iterator
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef base_type::point_iterator __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::point_iterator
Definition at line 115 of file assoc_container.hpp.
pointer
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef value_rebind::pointer __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::pointer
Definition at line 109 of file assoc_container.hpp.
probe_fn
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Probe_Fn __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::probe_fn
Definition at line 327 of file assoc_container.hpp.
reference
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef value_rebind::reference __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::reference
Definition at line 107 of file assoc_container.hpp.
resize_policy [1/2]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Resize_Policy __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::resize_policy
Definition at line 188 of file assoc_container.hpp.
resize_policy [2/2]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> typedef Resize_Policy __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::resize_policy
Definition at line 328 of file assoc_container.hpp.
size_type
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef allocator_type::size_type __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::size_type
Definition at line 85 of file assoc_container.hpp.
update_policy
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> typedef Update_Policy __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::update_policy
Definition at line 661 of file assoc_container.hpp.
value_rebind
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef allocator_type::template rebind<value_type>::other __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::value_rebind
Definition at line 106 of file assoc_container.hpp.
value_type
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > typedef base_type::value_type __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::value_type
Definition at line 105 of file assoc_container.hpp.
Function Documentation
cc_hash_table() [1/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table () inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 192 of file assoc_container.hpp.
 { }
cc_hash_table() [2/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 277 of file assoc_container.hpp.
     : base_type((const base_type&)other)
     { }
cc_hash_table() [3/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const hash_fn & h) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 196 of file assoc_container.hpp.
     : base_type(h) { }
cc_hash_table() [4/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const hash_fn & h, const eq_fn & e) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 203 of file assoc_container.hpp.
     : base_type(h, e) { }
cc_hash_table() [5/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const hash_fn & h, const eq_fn & e, const comb_hash_fn & ch) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 211 of file assoc_container.hpp.
     : base_type(h, e, ch) { }
cc_hash_table() [6/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (const hash_fn & h, const eq_fn & e, const comb_hash_fn & ch, const resize_policy & rp) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 220 of file assoc_container.hpp.
     : base_type(h, e, ch, rp) { }
cc_hash_table() [7/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 228 of file assoc_container.hpp.
     { base_type::copy_from_range(first, last); }
cc_hash_table() [8/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last, const hash_fn & h) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 235 of file assoc_container.hpp.
     : base_type(h)
     { copy_from_range(first, last); }
cc_hash_table() [9/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last, const hash_fn & h, const eq_fn & e) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 246 of file assoc_container.hpp.
     : base_type(h, e)
     { copy_from_range(first, last); }
cc_hash_table() [10/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last, const hash_fn & h, const eq_fn & e, const comb_hash_fn & ch) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 258 of file assoc_container.hpp.
     : base_type(h, e, ch)
     { copy_from_range(first, last); }
cc_hash_table() [11/11]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::cc_hash_table (It first, It last, const hash_fn & h, const eq_fn & e, const comb_hash_fn & ch, const resize_policy & rp) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 272 of file assoc_container.hpp.
     : base_type(h, e, ch, rp)
     { copy_from_range(first, last); }
gp_hash_table() [1/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table () inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 331 of file assoc_container.hpp.
 { }
gp_hash_table() [2/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 445 of file assoc_container.hpp.
     : base_type((const base_type&)other)
     { }
gp_hash_table() [3/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn & h) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 335 of file assoc_container.hpp.
     : base_type(h) { }
gp_hash_table() [4/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn & h, const eq_fn & e) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 342 of file assoc_container.hpp.
     : base_type(h, e) { }
gp_hash_table() [5/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn & h, const eq_fn & e, const comb_probe_fn & cp) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 350 of file assoc_container.hpp.
     : base_type(h, e, cp) { }
gp_hash_table() [6/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn & h, const eq_fn & e, const comb_probe_fn & cp, const probe_fn & p) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 359 of file assoc_container.hpp.
     : base_type(h, e, cp, p) { }
gp_hash_table() [7/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (const hash_fn & h, const eq_fn & e, const comb_probe_fn & cp, const probe_fn & p, const resize_policy & rp) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 370 of file assoc_container.hpp.
     : base_type(h, e, cp, p, rp) { }
gp_hash_table() [8/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 378 of file assoc_container.hpp.
     { base_type::copy_from_range(first, last); }
gp_hash_table() [9/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn & h) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 386 of file assoc_container.hpp.
     : base_type(h)
     { base_type::copy_from_range(first, last); }
gp_hash_table() [10/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn & h, const eq_fn & e) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 397 of file assoc_container.hpp.
     : base_type(h, e)
     { base_type::copy_from_range(first, last); }
gp_hash_table() [11/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn & h, const eq_fn & e, const comb_probe_fn & cp) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 409 of file assoc_container.hpp.
     : base_type(h, e, cp)
     { base_type::copy_from_range(first, last); }
gp_hash_table() [12/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn & h, const eq_fn & e, const comb_probe_fn & cp, const probe_fn & p) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 423 of file assoc_container.hpp.
     : base_type(h, e, cp, p)
     { base_type::copy_from_range(first, last); }
gp_hash_table() [13/13]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::gp_hash_table (It first, It last, const hash_fn & h, const eq_fn & e, const comb_probe_fn & cp, const probe_fn & p, const resize_policy & rp) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 439 of file assoc_container.hpp.
     : base_type(h, e, cp, p, rp)
     { base_type::copy_from_range(first, last); }
list_update() [1/3]
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::list_update () inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 664 of file assoc_container.hpp.
 { }
list_update() [2/3]
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::list_update (const list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 673 of file assoc_container.hpp.
     : base_type((const base_type&)other) { }
list_update() [3/3]
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> template<typename It > __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::list_update (It first, It last) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 670 of file assoc_container.hpp.
     { base_type::copy_from_range(first, last); }
tree() [1/5]
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree () inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 519 of file assoc_container.hpp.
 { }
tree() [2/5]
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree (const cmp_fn & c) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 523 of file assoc_container.hpp.
     : base_type(c) { }
tree() [3/5]
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree (const tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 542 of file assoc_container.hpp.
     : base_type((const base_type&)other) { }
tree() [4/5]
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree (It first, It last) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 530 of file assoc_container.hpp.
     { base_type::copy_from_range(first, last); }
tree() [5/5]
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::tree (It first, It last, const cmp_fn & c) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 538 of file assoc_container.hpp.
       : base_type(c)
     { base_type::copy_from_range(first, last); }
trie() [1/5]
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie () inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 595 of file assoc_container.hpp.
 { }
trie() [2/5]
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie (const e_access_traits & t) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 600 of file assoc_container.hpp.
     : base_type(t) { }
trie() [3/5]
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie (const trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 618 of file assoc_container.hpp.
     : base_type((const base_type&)other) { }
trie() [4/5]
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie (It first, It last) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 607 of file assoc_container.hpp.
     { base_type::copy_from_range(first, last); }
trie() [5/5]
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> template<typename It > __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::trie (It first, It last, const e_access_traits & t) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 614 of file assoc_container.hpp.
     : base_type(t)
     { base_type::copy_from_range(first, last); }
~basic_hash_table()
template<typename Key , typename Mapped , typename Hash_Fn , typename Eq_Fn , typename Resize_Policy , bool Store_Hash, typename Tag , typename Policy_TL , typename Allocator > virtual __gnu_pbds::basic_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, Tag, Policy_TL, Allocator >::~basic_hash_table () inline virtual
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 151 of file assoc_container.hpp.
 { }
~basic_tree()
template<typename Key , typename Mapped , typename Tag , typename Node_Update , typename Policy_Tl , typename Allocator > virtual __gnu_pbds::basic_tree< Key, Mapped, Tag, Node_Update, Policy_Tl, Allocator >::~basic_tree () inline virtual
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 486 of file assoc_container.hpp.
 { }
~cc_hash_table()
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> virtual __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::~cc_hash_table () inline virtual
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 282 of file assoc_container.hpp.
 { }
~container_base()
template<typename Key , typename Mapped , typename Tag , typename Policy_Tl , typename Allocator > virtual __gnu_pbds::container_base< Key, Mapped, Tag, Policy_Tl, Allocator >::~container_base () inline virtual
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 119 of file assoc_container.hpp.
 { }
~gp_hash_table()
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> virtual __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::~gp_hash_table () inline virtual
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 450 of file assoc_container.hpp.
 { }
~list_update()
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> virtual __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::~list_update () inline virtual
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 677 of file assoc_container.hpp.
 { }
~tree()
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> virtual __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::~tree () inline virtual
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 546 of file assoc_container.hpp.
 { }
~trie()
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> virtual __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::~trie () inline virtual
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 622 of file assoc_container.hpp.
 { }
operator=() [1/6]
template<typename Key , typename Mapped , typename Hash_Fn , typename Eq_Fn , typename Resize_Policy , bool Store_Hash, typename Tag , typename Policy_TL , typename Allocator > basic_hash_table& __gnu_pbds::basic_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, Tag, Policy_TL, Allocator >::operator= (const base_type &) private
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
operator=() [2/6]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> cc_hash_table& __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::operator= (const cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 285 of file assoc_container.hpp.
     {
       if (this != &other)
     {
       cc_hash_table tmp(other);
       swap(tmp);
     }
       return *this;
     }
References __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::swap(), and tmp.
operator=() [3/6]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> gp_hash_table& __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::operator= (const gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 453 of file assoc_container.hpp.
     {
       if (this != &other)
     {
       gp_hash_table tmp(other);
       swap(tmp);
     }
       return *this;
     }
References __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::swap(), and tmp.
operator=() [4/6]
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> list_update& __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::operator= (const list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 680 of file assoc_container.hpp.
     {
       if (this !=& other)
     {
       list_update tmp(other);
       swap(tmp);
     }
       return *this;
     }
References __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::swap(), and tmp.
operator=() [5/6]
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> tree& __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::operator= (const tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 549 of file assoc_container.hpp.
     {
       if (this != &other)
     {
       tree tmp(other);
       swap(tmp);
     }
       return *this;
     }
References __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::swap(), and tmp.
operator=() [6/6]
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> trie& __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::operator= (const trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 625 of file assoc_container.hpp.
     {
       if (this != &other)
     {
       trie tmp(other);
       swap(tmp);
     }
       return *this;
     }
References __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::swap(), and tmp.
swap() [1/5]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> void __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::swap (cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 296 of file assoc_container.hpp.
     { base_type::swap(other); }
References swap.
Referenced by __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >::operator=().
swap() [2/5]
template<typename Key , typename Mapped , typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Probe_Fn = detail::default_comb_hash_fn::type, typename Probe_Fn = typename detail::default_probe_fn<Comb_Probe_Fn>::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Probe_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> void __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::swap (gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 464 of file assoc_container.hpp.
     { base_type::swap(other); }
References swap.
Referenced by __gnu_pbds::gp_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Probe_Fn, Probe_Fn, Resize_Policy, Store_Hash, Allocator >::operator=().
swap() [3/5]
template<typename Key , typename Mapped , class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> void __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::swap (list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 691 of file assoc_container.hpp.
     { base_type::swap(other); }
References swap.
Referenced by __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >::operator=().
swap() [4/5]
template<typename Key , typename Mapped , typename Cmp_Fn = std::less<Key>, typename Tag = rb_tree_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename Cmp_Fn_, typename Allocator_ > class Node_Update = __gnu_pbds::null_tree_node_update, typename Allocator = std::allocator<char>> void __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::swap (tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 560 of file assoc_container.hpp.
     { base_type::swap(other); }
References swap.
Referenced by __gnu_pbds::tree< Key, Mapped, Cmp_Fn, Tag, Node_Update, Allocator >::operator=().
swap() [5/5]
template<typename Key , typename Mapped , typename E_Access_Traits = typename detail::default_trie_e_access_traits<Key>::type, typename Tag = pat_trie_tag, template< typename Const_Node_Iterator, typename Node_Iterator, typename E_Access_Traits_, typename Allocator_ > class Node_Update = null_trie_node_update, typename Allocator = std::allocator<char>> void __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::swap (trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator > & other) inline
#include <Tools/MinGW/include/c++/4.6.1/ext/pb_ds/assoc_container.hpp>
Definition at line 636 of file assoc_container.hpp.
     { base_type::swap(other); }
References swap.
Referenced by __gnu_pbds::trie< Key, Mapped, E_Access_Traits, Tag, Node_Update, Allocator >::operator=().