ZEQ2-Lite: Tools/MinGW/include/stdio.h File Reference
stdio.h File Reference
#include <_mingw.h>
#include <stddef.h>
#include <stdarg.h>
Data Structures
struct _iobuf
Macros
#define __mingw_stdio_redirect__(F) __cdecl __MINGW_NOTHROW __mingw_##F
#define __mingw_stdio_redirect__(F) __cdecl __MINGW_NOTHROW __msvcrt_##F
#define __need___va_list
#define __need_NULL
#define __need_size_t
#define __need_wchar_t
#define __need_wint_t
#define __VALIST char*
#define _FILE_DEFINED
#define _fileno(__F) ((__F)->_file)
#define _IOEOF 0x0010 /* EOF reached on read */
#define _IOERR 0x0020 /* I/O error from system */
#define _IOFBF 0x0000 /* full buffered */
#define _IOLBF 0x0040 /* line buffered */
#define _IOMYBUF 0x0008 /* stdio malloc()'d buffer */
#define _IONBF 0x0004 /* not buffered */
#define _IOREAD 1 /* currently reading */
#define _IORW 0x0080 /* opened as "r+w" */
#define _IOSTRG 0x0040 /* Strange or no file descriptor */
#define _IOWRT 2 /* currently writing */
#define _P_tmpdir "\\"
#define _wP_tmpdir L"\\"
#define _WSTDIO_DEFINED
#define BUFSIZ 512
#define EOF (-1)
#define feof(__F) ((__F)->_flag & _IOEOF)
#define ferror(__F) ((__F)->_flag & _IOERR)
#define FILENAME_MAX (260)
#define fileno(__F) ((__F)->_file)
#define FOPEN_MAX (20)
#define L_tmpnam (16)
#define P_tmpdir _P_tmpdir
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_SET 0
#define stderr (&_iob[STDERR_FILENO])
#define STDERR_FILENO 2
#define stdin (&_iob[STDIN_FILENO])
#define STDIN_FILENO 0
#define stdout (&_iob[STDOUT_FILENO])
#define STDOUT_FILENO 1
#define TMP_MAX 32767
Typedefs
typedef long fpos_t
Functions
_CRTIMP int __cdecl __MINGW_NOTHROW _fcloseall (void)
_CRTIMP FILE *__cdecl __MINGW_NOTHROW _fdopen (int, const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _fgetchar (void)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW _fgetwchar (void)
_CRTIMP int __cdecl __MINGW_NOTHROW _filbuf (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW _fileno (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW _flsbuf (int, FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW _flushall (void)
_CRTIMP int __cdecl __MINGW_NOTHROW _fputchar (int)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW _fputwchar (wint_t)
_CRTIMP FILE *__cdecl __MINGW_NOTHROW _fsopen (const char *, const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _getw (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW _pclose (FILE *)
_CRTIMP FILE *__cdecl __MINGW_NOTHROW _popen (const char *, const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _putw (int, FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW _rmtmp (void)
_CRTIMP int __cdecl __MINGW_NOTHROW _snprintf (char *, size_t, const char *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW _snwprintf (wchar_t *, size_t, const wchar_t *,...)
_CRTIMP char *__cdecl __MINGW_NOTHROW _tempnam (const char *, const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _unlink (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _vscprintf (const char *, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW _vscwprintf (const wchar_t *, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW _vsnprintf (char *, size_t, const char *, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW _vsnwprintf (wchar_t *, size_t, const wchar_t *, __VALIST)
_CRTIMP void __cdecl __MINGW_NOTHROW clearerr (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW fclose (FILE *)
_CRTIMP FILE *__cdecl __MINGW_NOTHROW fdopen (int, const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW feof (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW ferror (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW fflush (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW fgetc (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW fgetchar (void)
_CRTIMP int __cdecl __MINGW_NOTHROW fgetpos (FILE *, fpos_t *)
_CRTIMP char *__cdecl __MINGW_NOTHROW fgets (char *, int, FILE *)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fgetwc (FILE *)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fgetwchar (void)
_CRTIMP int __cdecl __MINGW_NOTHROW fileno (FILE *)
_CRTIMP FILE *__cdecl __MINGW_NOTHROW fopen (const char *, const char *)
int __mingw_stdio_redirect__() fprintf (FILE *, const char *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW fputc (int, FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW fputchar (int)
_CRTIMP int __cdecl __MINGW_NOTHROW fputs (const char *, FILE *)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fputwc (wchar_t, FILE *)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fputwchar (wint_t)
_CRTIMP size_t __cdecl __MINGW_NOTHROW fread (void *, size_t, size_t, FILE *)
_CRTIMP FILE *__cdecl __MINGW_NOTHROW freopen (const char *, const char *, FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW fscanf (FILE *, const char *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW fseek (FILE *, long, int)
_CRTIMP int __cdecl __MINGW_NOTHROW fsetpos (FILE *, const fpos_t *)
_CRTIMP long __cdecl __MINGW_NOTHROW ftell (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW fwprintf (FILE *, const wchar_t *,...)
_CRTIMP size_t __cdecl __MINGW_NOTHROW fwrite (const void *, size_t, size_t, FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW fwscanf (FILE *, const wchar_t *,...)
__CRT_INLINE int __cdecl __MINGW_NOTHROW getc (FILE *__F)
__CRT_INLINE int __cdecl __MINGW_NOTHROW getchar (void)
_CRTIMP char *__cdecl __MINGW_NOTHROW gets (char *)
_CRTIMP int __cdecl __MINGW_NOTHROW getw (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW pclose (FILE *)
_CRTIMP void __cdecl __MINGW_NOTHROW perror (const char *)
_CRTIMP FILE *__cdecl __MINGW_NOTHROW popen (const char *, const char *)
int __mingw_stdio_redirect__() printf (const char *,...)
__CRT_INLINE int __cdecl __MINGW_NOTHROW putc (int __c, FILE *__F)
__CRT_INLINE int __cdecl __MINGW_NOTHROW putchar (int __c)
_CRTIMP int __cdecl __MINGW_NOTHROW puts (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW putw (int, FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW remove (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW rename (const char *, const char *)
_CRTIMP void __cdecl __MINGW_NOTHROW rewind (FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW rmtmp (void)
_CRTIMP int __cdecl __MINGW_NOTHROW scanf (const char *,...)
_CRTIMP void __cdecl __MINGW_NOTHROW setbuf (FILE *, char *)
_CRTIMP int __cdecl __MINGW_NOTHROW setvbuf (FILE *, char *, int, size_t)
int __mingw_stdio_redirect__() snprintf (char *, size_t, const char *,...)
int __cdecl __MINGW_NOTHROW snwprintf (wchar_t *s, size_t n, const wchar_t *format,...)
int __mingw_stdio_redirect__() sprintf (char *, const char *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW sscanf (const char *, const char *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW swprintf (wchar_t *, const wchar_t *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW swscanf (const wchar_t *, const wchar_t *,...)
_CRTIMP char *__cdecl __MINGW_NOTHROW tempnam (const char *, const char *)
_CRTIMP FILE *__cdecl __MINGW_NOTHROW tmpfile (void)
_CRTIMP char *__cdecl __MINGW_NOTHROW tmpnam (char *)
_CRTIMP int __cdecl __MINGW_NOTHROW ungetc (int, FILE *)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW ungetwc (wchar_t, FILE *)
_CRTIMP int __cdecl __MINGW_NOTHROW unlink (const char *)
int __mingw_stdio_redirect__() vfprintf (FILE *, const char *, __VALIST)
int __cdecl __MINGW_NOTHROW vfscanf (FILE *__restrict__, const char *__restrict__, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW vfwprintf (FILE *, const wchar_t *, __VALIST)
int __cdecl __MINGW_NOTHROW vfwscanf (FILE *__restrict__, const wchar_t *__restrict__, __VALIST)
int __mingw_stdio_redirect__() vprintf (const char *, __VALIST)
int __cdecl __MINGW_NOTHROW vscanf (const char *__restrict__, __VALIST)
int __mingw_stdio_redirect__() vsnprintf (char *, size_t, const char *, __VALIST)
int __cdecl __MINGW_NOTHROW vsnwprintf (wchar_t *s, size_t n, const wchar_t *format, __VALIST arg)
int __mingw_stdio_redirect__() vsprintf (char *, const char *, __VALIST)
int __cdecl __MINGW_NOTHROW vsscanf (const char *__restrict__, const char *__restrict__, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW vswprintf (wchar_t *, const wchar_t *, __VALIST)
int __cdecl __MINGW_NOTHROW vswscanf (const wchar_t *__restrict__, const wchar_t *__restrict__, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW vwprintf (const wchar_t *, __VALIST)
int __cdecl __MINGW_NOTHROW vwscanf (const wchar_t *__restrict__, __VALIST)
_CRTIMP int __cdecl __MINGW_NOTHROW wprintf (const wchar_t *,...)
_CRTIMP int __cdecl __MINGW_NOTHROW wscanf (const wchar_t *,...)
Variables
__MINGW_IMPORT FILE _iob []
Macro Definition Documentation
__mingw_stdio_redirect__ [1/2]
#define __mingw_stdio_redirect__ (F) __cdecl __MINGW_NOTHROW __mingw_##F
Definition at line 306 of file stdio.h.
__mingw_stdio_redirect__ [2/2]
#define __mingw_stdio_redirect__ (F) __cdecl __MINGW_NOTHROW __msvcrt_##F
Definition at line 306 of file stdio.h.
__need___va_list
#define __need___va_list
Definition at line 27 of file stdio.h.
__need_NULL
#define __need_NULL
Definition at line 23 of file stdio.h.
__need_size_t
#define __need_size_t
Definition at line 22 of file stdio.h.
__need_wchar_t
#define __need_wchar_t
Definition at line 24 of file stdio.h.
__need_wint_t
#define __need_wint_t
Definition at line 25 of file stdio.h.
__VALIST
#define __VALIST char*
Definition at line 116 of file stdio.h.
_FILE_DEFINED
#define _FILE_DEFINED
Definition at line 128 of file stdio.h.
_fileno
#define _fileno (__F) ((__F)->_file)
Definition at line 528 of file stdio.h.
_IOEOF
#define _IOEOF 0x0010 /* EOF reached on read */
Definition at line 91 of file stdio.h.
_IOERR
#define _IOERR 0x0020 /* I/O error from system */
Definition at line 92 of file stdio.h.
_IOFBF
#define _IOFBF 0x0000 /* full buffered */
Definition at line 86 of file stdio.h.
_IOLBF
#define _IOLBF 0x0040 /* line buffered */
Definition at line 87 of file stdio.h.
_IOMYBUF
#define _IOMYBUF 0x0008 /* stdio malloc()'d buffer */
Definition at line 90 of file stdio.h.
_IONBF
#define _IONBF 0x0004 /* not buffered */
Definition at line 88 of file stdio.h.
_IOREAD
#define _IOREAD 1 /* currently reading */
Definition at line 33 of file stdio.h.
_IORW
#define _IORW 0x0080 /* opened as "r+w" */
Definition at line 35 of file stdio.h.
_IOSTRG
#define _IOSTRG 0x0040 /* Strange or no file descriptor */
Definition at line 93 of file stdio.h.
_IOWRT
#define _IOWRT 2 /* currently writing */
Definition at line 34 of file stdio.h.
_P_tmpdir
#define _P_tmpdir "\\"
Definition at line 72 of file stdio.h.
_wP_tmpdir
#define _wP_tmpdir L"\\"
Definition at line 76 of file stdio.h.
_WSTDIO_DEFINED
#define _WSTDIO_DEFINED
Definition at line 619 of file stdio.h.
BUFSIZ
#define BUFSIZ 512
Definition at line 101 of file stdio.h.
EOF
#define EOF (-1)
Definition at line 47 of file stdio.h.
feof
#define feof (__F) ((__F)->_flag & _IOEOF)
Definition at line 476 of file stdio.h.
ferror
#define ferror (__F) ((__F)->_flag & _IOERR)
Definition at line 477 of file stdio.h.
FILENAME_MAX
#define FILENAME_MAX (260)
Definition at line 55 of file stdio.h.
fileno
#define fileno (__F) ((__F)->_file)
Definition at line 530 of file stdio.h.
FOPEN_MAX
#define FOPEN_MAX (20)
Definition at line 62 of file stdio.h.
L_tmpnam
#define L_tmpnam (16)
Definition at line 84 of file stdio.h.
P_tmpdir
#define P_tmpdir _P_tmpdir
Definition at line 74 of file stdio.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 107 of file stdio.h.
SEEK_END
#define SEEK_END 2
Definition at line 108 of file stdio.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 106 of file stdio.h.
stderr
#define stderr (&_iob[STDERR_FILENO])
Definition at line 160 of file stdio.h.
STDERR_FILENO
#define STDERR_FILENO 2
Definition at line 44 of file stdio.h.
stdin
#define stdin (&_iob[STDIN_FILENO])
Definition at line 158 of file stdio.h.
STDIN_FILENO
#define STDIN_FILENO 0
Definition at line 42 of file stdio.h.
stdout
#define stdout (&_iob[STDOUT_FILENO])
Definition at line 159 of file stdio.h.
STDOUT_FILENO
#define STDOUT_FILENO 1
Definition at line 43 of file stdio.h.
TMP_MAX
#define TMP_MAX 32767
Definition at line 65 of file stdio.h.
Typedef Documentation
fpos_t
typedef long fpos_t
Definition at line 457 of file stdio.h.
Function Documentation
_fcloseall()
_CRTIMP int __cdecl __MINGW_NOTHROW _fcloseall (void)
_fdopen()
_CRTIMP FILE* __cdecl __MINGW_NOTHROW _fdopen (int , const char *)
_fgetchar()
_CRTIMP int __cdecl __MINGW_NOTHROW _fgetchar (void)
_fgetwchar()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW _fgetwchar (void)
_filbuf()
_CRTIMP int __cdecl __MINGW_NOTHROW _filbuf (FILE *)
Referenced by getc(), and getchar().
_fileno()
_CRTIMP int __cdecl __MINGW_NOTHROW _fileno (FILE *)
_flsbuf()
_CRTIMP int __cdecl __MINGW_NOTHROW _flsbuf (int , FILE *)
Referenced by putc(), and putchar().
_flushall()
_CRTIMP int __cdecl __MINGW_NOTHROW _flushall (void)
_fputchar()
_CRTIMP int __cdecl __MINGW_NOTHROW _fputchar (int)
_fputwchar()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW _fputwchar (wint_t)
_fsopen()
_CRTIMP FILE* __cdecl __MINGW_NOTHROW _fsopen (const char * , const char * , int)
_getw()
_CRTIMP int __cdecl __MINGW_NOTHROW _getw (FILE *)
_pclose()
_CRTIMP int __cdecl __MINGW_NOTHROW _pclose (FILE *)
_popen()
_CRTIMP FILE* __cdecl __MINGW_NOTHROW _popen (const char * , const char *)
_putw()
_CRTIMP int __cdecl __MINGW_NOTHROW _putw (int , FILE *)
_rmtmp()
_CRTIMP int __cdecl __MINGW_NOTHROW _rmtmp (void)
_snprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW _snprintf (char * , size_t , const char * , ...)
_snwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW _snwprintf (wchar_t * , size_t , const wchar_t * , ...)
_tempnam()
_CRTIMP char* __cdecl __MINGW_NOTHROW _tempnam (const char * , const char *)
_unlink()
_CRTIMP int __cdecl __MINGW_NOTHROW _unlink (const char *)
_vscprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW _vscprintf (const char * , __VALIST)
_vscwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW _vscwprintf (const wchar_t * , __VALIST)
_vsnprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW _vsnprintf (char * , size_t , const char * , __VALIST)
_vsnwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW _vsnwprintf (wchar_t * , size_t , const wchar_t * , __VALIST)
Referenced by vsnwprintf().
clearerr()
_CRTIMP void __cdecl __MINGW_NOTHROW clearerr (FILE *)
fclose()
_CRTIMP int __cdecl __MINGW_NOTHROW fclose (FILE *)
Referenced by __gnu_profile::__report(), __gnu_profile::__set_trace_path(), __gnu_profile::__write_cost_factors(), fclose_file_func(), FileExists(), FS_FCloseFile(), FS_FileInPathExists(), FS_FOpenFileReadDir(), FS_Shutdown(), LoadFile(), LoadFileBlock(), LoadSourceFile(), main(), main_init(), process(), SaveFile(), speex_echo_state_destroy(), stabend(), stabline(), Sys_RandomBytes(), Sys_WritePIDFile(), TryLoadFile(), VM_Compile(), WriteMapFile(), and WriteVmFile().
fdopen()
_CRTIMP FILE* __cdecl __MINGW_NOTHROW fdopen (int , const char *)
feof()
_CRTIMP int __cdecl __MINGW_NOTHROW feof (FILE *)
Referenced by fillbuf(), and main().
ferror()
_CRTIMP int __cdecl __MINGW_NOTHROW ferror (FILE *)
Referenced by ferror_file_func(), and term_destination().
fflush()
_CRTIMP int __cdecl __MINGW_NOTHROW fflush (FILE *)
Referenced by _GLIBCXX_VISIBILITY(), Assemble(), error(), FS_Flush(), FS_Write(), main(), peektokens(), spawn(), term_destination(), and VM_Compile().
fgetc()
_CRTIMP int __cdecl __MINGW_NOTHROW fgetc (FILE *)
fgetchar()
_CRTIMP int __cdecl __MINGW_NOTHROW fgetchar (void)
fgetpos()
_CRTIMP int __cdecl __MINGW_NOTHROW fgetpos (FILE * , fpos_t *)
fgets()
_CRTIMP char* __cdecl __MINGW_NOTHROW fgets (char * , int , FILE *)
Referenced by get(), and stabline().
fgetwc()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fgetwc (FILE *)
fgetwchar()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fgetwchar (void)
fileno()
_CRTIMP int __cdecl __MINGW_NOTHROW fileno (FILE *)
Referenced by Sys_Mkfifo().
fopen()
_CRTIMP FILE* __cdecl __MINGW_NOTHROW fopen (const char * , const char *)
Referenced by __gnu_profile::__open_output_file(), FileExists(), fopen_file_func(), FS_FileInPathExists(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_Startup(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), LoadSourceFile(), main(), main_init(), myfopen(), process(), SafeOpenRead(), SafeOpenWrite(), speex_echo_state_init(), stabline(), Sys_Mkfifo(), Sys_RandomBytes(), Sys_WritePIDFile(), TryLoadFile(), VM_Compile(), and VM_LogSyscalls().
fprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW fprintf (FILE * , const char * , ...)
Referenced by __attribute__(), __gnu_profile::__env_to_size_t(), __gnu_profile::__open_output_file(), __gnu_profile::__container_size_info::__write(), __gnu_profile::__vector2list_info::__write(), __gnu_profile::__hashfunc_info::__write(), __gnu_profile::__list2vector_info::__write(), __gnu_profile::__list2slist_info::__write(), __gnu_profile::__write(), __gnu_profile::__map2umap_info::__write(), __gnu_profile::__trace_base< __list2slist_info, __list2slist_stack_info >::__write(), _ADD16(), _ADD32(), _DIV32(), _DIV32_16(), _EXTEND32(), _EXTRACT16(), _MULT16_16(), _MULT16_32_QX(), _SHL16(), _SHR16(), _speex_fatal(), _speex_putc(), _SUB16(), callsys(), CodeError(), error(), FS_FOpenFileRead(), help(), main(), MULT16_16_16(), MULT16_16_P13(), MULT16_16_P14(), MULT16_16_P15(), MULT16_16_Q11_32(), MULT16_16_Q13(), MULT16_16_Q14(), MULT16_16_Q15(), MULT16_32_PX(), NEG16(), NEG32(), __gnu_profile::__warn::operator()(), __gnu_profile::__cost_factor_writer::operator()(), opt(), option(), output_message(), peektokens(), prhideset(), print(), rm(), setup(), SHL32(), SHR32(), spawn(), speex_notify(), speex_warning(), speex_warning_int(), SUB32(), Sys_ParseArgs(), Sys_SigHandler(), Sys_WritePIDFile(), VM_LogSyscalls(), WriteMapFile(), yyerror(), and yywarn().
fputc()
_CRTIMP int __cdecl __MINGW_NOTHROW fputc (int , FILE *)
Referenced by __attribute__(), error(), and vfprint().
fputchar()
_CRTIMP int __cdecl __MINGW_NOTHROW fputchar (int)
fputs()
_CRTIMP int __cdecl __MINGW_NOTHROW fputs (const char * , FILE *)
Referenced by CON_Print(), emitasm(), get(), outs(), print(), and Sys_AnsiColorPrint().
fputwc()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fputwc (wchar_t , FILE *)
fputwchar()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW fputwchar (wint_t)
fread()
_CRTIMP size_t __cdecl __MINGW_NOTHROW fread (void * , size_t , size_t , FILE *)
freopen()
_CRTIMP FILE* __cdecl __MINGW_NOTHROW freopen (const char * , const char * , FILE *)
Referenced by main_init().
fscanf()
_CRTIMP int __cdecl __MINGW_NOTHROW fscanf (FILE * , const char * , ...)
fseek()
_CRTIMP int __cdecl __MINGW_NOTHROW fseek (FILE * , long , int)
Referenced by _GLIBCXX_VISIBILITY(), _ov_header_fseek_wrap(), filelength(), FS_fplength(), FS_Seek(), fseek_file_func(), Q_filelength(), and Sys_StreamSeek().
fsetpos()
_CRTIMP int __cdecl __MINGW_NOTHROW fsetpos (FILE * , const fpos_t *)
ftell()
_CRTIMP long __cdecl __MINGW_NOTHROW ftell (FILE *)
Referenced by _GLIBCXX_VISIBILITY(), filelength(), FS_FOpenFileByMode(), FS_fplength(), FS_FTell(), ftell_file_func(), Q_filelength(), SaveAnimation(), and SaveMesh().
fwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW fwprintf (FILE * , const wchar_t * , ...)
fwrite()
_CRTIMP size_t __cdecl __MINGW_NOTHROW fwrite (const void * , size_t , size_t , FILE *)
fwscanf()
_CRTIMP int __cdecl __MINGW_NOTHROW fwscanf (FILE * , const wchar_t * , ...)
getc()
__CRT_INLINE int __cdecl __MINGW_NOTHROW getc (FILE * __F)
Definition at line 372 of file stdio.h.
 {
   return (--__F->_cnt >= 0)
     ?  (int) (unsigned char) *__F->_ptr++
     : _filbuf (__F);
 }
References __F, _filbuf(), and int.
Referenced by _GLIBCXX_VISIBILITY(), getd(), getstr(), and main().
getchar()
__CRT_INLINE int __cdecl __MINGW_NOTHROW getchar (void)
Definition at line 386 of file stdio.h.
 {
   return (--stdin->_cnt >= 0)
     ?  (int) (unsigned char) *stdin->_ptr++
     : _filbuf (stdin);
 }
References _filbuf(), int, and stdin.
gets()
_CRTIMP char* __cdecl __MINGW_NOTHROW gets (char *)
getw()
_CRTIMP int __cdecl __MINGW_NOTHROW getw (FILE *)
pclose()
_CRTIMP int __cdecl __MINGW_NOTHROW pclose (FILE *)
perror()
_CRTIMP void __cdecl __MINGW_NOTHROW perror (const char *)
Referenced by callsys(), and spawn().
popen()
_CRTIMP FILE* __cdecl __MINGW_NOTHROW popen (const char * , const char *)
printf()
_CRTIMP int __cdecl __MINGW_NOTHROW printf (const char * , ...)
Referenced by _GLIBCXX_VISIBILITY(), _printf(), asm_instruction(), DoAnims(), DoMeshes(), dumptree(), EndOfScript(), FixCoords(), labelhash_free(), LoadCFG_Anim(), LoadCFG_General(), LoadCFG_Mesh(), LoadCFG_Print(), LoadCFG_Skeleton(), LoadSMD(), LoadSMD_ParseNodes(), LoadSMD_ParseSkeleton(), LoadSMD_ParseTriangles(), main(), OrderMesh(), print_vec(), PrintUsage(), ProgressiveMesh(), pw(), SaveAnimation(), SaveMesh(), Sys_EarlyOutput(), Sys_Error(), and VM_CallCompiled().
putc()
__CRT_INLINE int __cdecl __MINGW_NOTHROW putc (int __c, FILE * __F)
Definition at line 379 of file stdio.h.
 {
   return (--__F->_cnt >= 0)
     ?  (int) (unsigned char) (*__F->_ptr++ = (char)__c)
     :  _flsbuf (__c, __F);
 }
References __F, _flsbuf(), and int.
Referenced by _GLIBCXX_VISIBILITY(), main(), print(), and vfprint().
putchar()
__CRT_INLINE int __cdecl __MINGW_NOTHROW putchar (int __c)
Definition at line 393 of file stdio.h.
 {
   return (--stdout->_cnt >= 0)
     ?  (int) (unsigned char) (*stdout->_ptr++ = (char)__c)
     :  _flsbuf (__c, stdout);}
References _flsbuf(), int, and stdout.
Referenced by _GLIBCXX_VISIBILITY(), and emitasm().
puts()
_CRTIMP int __cdecl __MINGW_NOTHROW puts (const char *)
putw()
_CRTIMP int __cdecl __MINGW_NOTHROW putw (int , FILE *)
remove()
_CRTIMP int __cdecl __MINGW_NOTHROW remove (const char *)
rename()
_CRTIMP int __cdecl __MINGW_NOTHROW rename (const char * , const char *)
rewind()
_CRTIMP void __cdecl __MINGW_NOTHROW rewind (FILE *)
Referenced by main(), and stabline().
rmtmp()
_CRTIMP int __cdecl __MINGW_NOTHROW rmtmp (void)
scanf()
_CRTIMP int __cdecl __MINGW_NOTHROW scanf (const char * , ...)
setbuf()
_CRTIMP void __cdecl __MINGW_NOTHROW setbuf (FILE * , char *)
Referenced by main().
setvbuf()
_CRTIMP int __cdecl __MINGW_NOTHROW setvbuf (FILE * , char * , int , size_t)
Referenced by FS_ForceFlush().
snprintf()
int __cdecl __MINGW_NOTHROW snprintf (char * , size_t , const char * , ...)
Referenced by mumble_link().
snwprintf()
int __cdecl __MINGW_NOTHROW snwprintf (wchar_t * s, size_t n, const wchar_t * format, ...)
sprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW sprintf (char * , const char * , ...)
Referenced by CL_GlobalServers_f(), computekids(), computents(), DefineSymbol(), exists(), ExpandGamePath(), ExpandPath(), ExpandPathAndArchive(), format_message(), LookupSymbol(), SCR_DrawDemoRecording(), and vfprint().
sscanf()
_CRTIMP int __cdecl __MINGW_NOTHROW sscanf (const char * , const char * , ...)
Referenced by CL_ServerStatusResponse(), G_ParseField(), G_ReadSessionData(), G_SpawnVector(), jinit_memory_mgr(), and R_LoadEntities().
swprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW swprintf (wchar_t * , const wchar_t * , ...)
swscanf()
_CRTIMP int __cdecl __MINGW_NOTHROW swscanf (const wchar_t * , const wchar_t * , ...)
tempnam()
_CRTIMP char* __cdecl __MINGW_NOTHROW tempnam (const char * , const char *)
tmpfile()
_CRTIMP FILE* __cdecl __MINGW_NOTHROW tmpfile (void)
tmpnam()
_CRTIMP char* __cdecl __MINGW_NOTHROW tmpnam (char *)
ungetc()
_CRTIMP int __cdecl __MINGW_NOTHROW ungetc (int , FILE *)
Referenced by _GLIBCXX_VISIBILITY().
ungetwc()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW ungetwc (wchar_t , FILE *)
Referenced by _GLIBCXX_VISIBILITY().
unlink()
_CRTIMP int __cdecl __MINGW_NOTHROW unlink (const char *)
vfprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vfprintf (FILE * , const char * , __VALIST)
Referenced by __attribute__(), CodeError(), yyerror(), and yywarn().
vfscanf()
int __cdecl __MINGW_NOTHROW vfscanf (FILE * __restrict__, const char * __restrict__, __VALIST)
vfwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vfwprintf (FILE * , const wchar_t * , __VALIST)
vfwscanf()
int __cdecl __MINGW_NOTHROW vfwscanf (FILE * __restrict__, const wchar_t * __restrict__, __VALIST)
vprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vprintf (const char * , __VALIST)
Referenced by Error(), qprintf(), Sys_Error(), and vreport().
vscanf()
int __cdecl __MINGW_NOTHROW vscanf (const char * __restrict__, __VALIST)
vsnprintf()
int __cdecl __MINGW_NOTHROW vsnprintf (char * , size_t , const char * , __VALIST)
vsnwprintf()
__CRT_INLINE int __cdecl __MINGW_NOTHROW vsnwprintf (wchar_t * s, size_t n, const wchar_t * format, __VALIST arg)
Definition at line 609 of file stdio.h.
   { return _vsnwprintf ( s, n, format, arg);}
References _vsnwprintf().
vsprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vsprintf (char * , const char * , __VALIST)
Referenced by _printf(), and stringf().
vsscanf()
int __cdecl __MINGW_NOTHROW vsscanf (const char * __restrict__, const char * __restrict__, __VALIST)
vswprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vswprintf (wchar_t * , const wchar_t * , __VALIST)
vswscanf()
int __cdecl __MINGW_NOTHROW vswscanf (const wchar_t * __restrict__, const wchar_t * __restrict__, __VALIST)
vwprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW vwprintf (const wchar_t * , __VALIST)
vwscanf()
int __cdecl __MINGW_NOTHROW vwscanf (const wchar_t * __restrict__, __VALIST)
wprintf()
_CRTIMP int __cdecl __MINGW_NOTHROW wprintf (const wchar_t * , ...)
wscanf()
_CRTIMP int __cdecl __MINGW_NOTHROW wscanf (const wchar_t * , ...)
Variable Documentation
_iob
__MINGW_IMPORT FILE _iob[]
Definition at line 154 of file stdio.h.