ZEQ2-Lite: Source/Shared/vm_x86_64_assembler.c File Reference
vm_x86_64_assembler.c File Reference
#include "vm_local.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <inttypes.h>
Data Structures
struct arg_t
struct hashentry
struct memref_t
struct op_t
struct opparam_t
Macros
#define _ISOC99_SOURCE
#define crap(fmt, args...)
#define CRAP_INVALID_ARGS crap("invalid arguments %s, %s", argtype2str(arg1.type),argtype2str(arg2.type));
#define debug(fmt, args...)
#define LABELLEN 32
Typedefs
typedef void(* emitfunc) (const char *op, arg_t arg1, arg_t arg2, void *data)
typedef uint16_t u16
typedef uint32_t u32
typedef uint64_t u64
typedef uint8_t u8
Enumerations
enum { REX_W = 0x08, REX_R = 0x04, REX_X = 0x02, REX_B = 0x01 }
enum {
MODRM_MOD_00 = 0x00, MODRM_MOD_01 = 0x01 << 6, MODRM_MOD_10 = 0x02 << 6, MODRM_MOD_11 = 0x03 << 6,
MODRM_RM_SIB = 0x04
}
enum argtype_t {
T_NONE = 0x00, T_REGISTER = 0x01, T_IMMEDIATE = 0x02, T_MEMORY = 0x04,
T_LABEL = 0x08, T_ABSOLUTE = 0x80
}
enum modrm_sib_t { MODRM_SIB = 0, MODRM_NOSIB = 0x3 }
enum reg_t {
R_8 = 0x100, R_16 = 0x200, R_64 = 0x800, R_MSZ = 0xF00,
R_XMM = 0x2000, R_EAX = 0x00, R_EBX = 0x03, R_ECX = 0x01,
R_EDX = 0x02, R_ESI = 0x06, R_EDI = 0x07, R_ESP = 0x04,
R_RAX = R_EAX | R_64, R_RBX = R_EBX | R_64, R_RCX = R_ECX | R_64, R_RDX = R_EDX | R_64,
R_RSI = R_ESI | R_64, R_RDI = R_EDI | R_64, R_RSP = R_ESP | R_64, R_R8 = 0x08 | R_64,
R_R9 = 0x09 | R_64, R_R10 = 0x0A | R_64, R_R15 = 0x0F | R_64, R_AL = R_EAX | R_8,
R_AX = R_EAX | R_16, R_BL = R_EBX | R_8, R_CL = R_ECX | R_8, R_XMM0 = 0x00 | R_XMM,
R_MGP = 0x0F
}
enum token_t { TOK_LABEL = 0x80, TOK_INT = 0x81, TOK_END = 0x82, TOK_INVALID = 0x83 }
Functions
static __attribute__ ((noreturn))
static const char * argtype2str (argtype_t t)
void assemble_line (const char *input, size_t len)
size_t assembler_get_code_size (void)
void assembler_init (int pass)
void assembler_set_output (char *buf)
static void compute_rexmodrmsib (u8 *rex_r, u8 *modrm_r, u8 *sib_r, arg_t *arg1, arg_t *arg2)
static void emit1 (unsigned char v)
static void emit2 (u16 v)
static void emit4 (u32 v)
static void emit8 (u64 v)
static void emit_call (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_condjump (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_jmp (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_mov (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_op_rm (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_op_rm_cl (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_opreg (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_opsingle (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_opsingle16 (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_subaddand (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static void emit_twobyte (const char *mnemonic, arg_t arg1, arg_t arg2, void *data)
static op_t * getop (const char *n)
static void hash_add_label (const char *label, unsigned address)
static unsigned hashkey (const char *string, unsigned len)
static int iss16 (int64_t v)
static int iss32 (int64_t v)
static int iss8 (int64_t v)
static int isu16 (u64 v)
static int isu32 (u64 v)
static int isu8 (u64 v)
static void labelhash_free (void)
static unsigned lookup_label (const char *label)
static void maybe_emit_displacement (arg_t *arg)
static unsigned char nexttok (const char **str, char *label, u64 *val)
static int opsort (const void *A, const void *B)
static arg_t parsearg (const char **str)
static reg_t parsereg (const char *str)
Variables
static unsigned assembler_pass
static unsigned compiledOfs
static const char * cur_line
static FILE * fout
static struct hashentry * labelhash [1021]
static op_t ops []
static int ops_sorted = 0
static char * out
static opparam_t params_add = { subcode: 0, rmcode: 0x01, }
static opparam_t params_addss = { xmmprefix: 0xf3, mrcode: 0x58 }
static opparam_t params_and = { subcode: 4, rmcode: 0x21, }
static opparam_t params_cmp = { subcode: 7, rmcode: 0x39, mrcode: 0x3b, }
static opparam_t params_cvtsi2ss = { xmmprefix: 0xf3, rmcode: 0x2a }
static opparam_t params_cvttss2si = { xmmprefix: 0xf3, rmcode: 0x2c }
static opparam_t params_dec = { subcode: 1, rcode: 0xff, rcode8: 0xfe, }
static opparam_t params_div = { subcode: 6, rcode: 0xf7, rcode8: 0xf6, }
static opparam_t params_divss = { xmmprefix: 0xf3, mrcode: 0x5e }
static opparam_t params_idiv = { subcode: 7, rcode: 0xf7, rcode8: 0xf6, }
static opparam_t params_imul = { subcode: 5, rcode: 0xf7, rcode8: 0xf6, }
static opparam_t params_movss = { xmmprefix: 0xf3, mrcode: 0x10, rmcode: 0x11 }
static opparam_t params_mul = { subcode: 4, rcode: 0xf7, rcode8: 0xf6, }
static opparam_t params_mulss = { xmmprefix: 0xf3, mrcode: 0x59 }
static opparam_t params_neg = { subcode: 3, rcode: 0xf7, rcode8: 0xf6, }
static opparam_t params_not = { subcode: 2, rcode: 0xf7, rcode8: 0xf6, }
static opparam_t params_or = { subcode: 1, rmcode: 0x09, }
static opparam_t params_sar = { subcode: 7, rcode: 0xd3, rcode8: 0xd2, }
static opparam_t params_shl = { subcode: 4, rcode: 0xd3, rcode8: 0xd2, }
static opparam_t params_shr = { subcode: 5, rcode: 0xd3, rcode8: 0xd2, }
static opparam_t params_sub = { subcode: 5, rmcode: 0x29, }
static opparam_t params_subss = { xmmprefix: 0xf3, mrcode: 0x5c }
static opparam_t params_ucomiss = { mrcode: 0x2e }
static opparam_t params_xor = { subcode: 6, rmcode: 0x31, }
Macro Definition Documentation
_ISOC99_SOURCE
#define _ISOC99_SOURCE
Definition at line 23 of file vm_x86_64_assembler.c.
crap
#define crap (fmt, args...)
Value:
    do { \
    _crap(__FUNCTION__, fmt, ##args); \
} while(0)
Definition at line 53 of file vm_x86_64_assembler.c.
CRAP_INVALID_ARGS
#define CRAP_INVALID_ARGS crap("invalid arguments %s, %s", argtype2str(arg1.type),argtype2str(arg2.type));
Definition at line 57 of file vm_x86_64_assembler.c.
debug
#define debug (fmt, args...)
Definition at line 62 of file vm_x86_64_assembler.c.
LABELLEN
#define LABELLEN 32
Definition at line 194 of file vm_x86_64_assembler.c.
Typedef Documentation
emitfunc
typedef void(* emitfunc) (const char *op, arg_t arg1, arg_t arg2, void *data)
Definition at line 207 of file vm_x86_64_assembler.c.
u16
typedef uint16_t u16
Definition at line 41 of file vm_x86_64_assembler.c.
u32
typedef uint32_t u32
Definition at line 42 of file vm_x86_64_assembler.c.
u64
typedef uint64_t u64
Definition at line 43 of file vm_x86_64_assembler.c.
u8
typedef uint8_t u8
Definition at line 40 of file vm_x86_64_assembler.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
REX_W
REX_R
REX_X
REX_B
Definition at line 117 of file vm_x86_64_assembler.c.
      {
     REX_W = 0x08,
     REX_R = 0x04,
     REX_X = 0x02,
     REX_B = 0x01,
 };
anonymous enum
anonymous enum
Enumerator
MODRM_MOD_00
MODRM_MOD_01
MODRM_MOD_10
MODRM_MOD_11
MODRM_RM_SIB
Definition at line 124 of file vm_x86_64_assembler.c.
      {
     MODRM_MOD_00 = 0x00,
     MODRM_MOD_01 = 0x01 << 6,
     MODRM_MOD_10 = 0x02 << 6,
     MODRM_MOD_11 = 0x03 << 6,
     MODRM_RM_SIB = 0x04,
 };
argtype_t
enum argtype_t
Enumerator
T_NONE
T_REGISTER
T_IMMEDIATE
T_MEMORY
T_LABEL
T_ABSOLUTE
Definition at line 132 of file vm_x86_64_assembler.c.
 {
     T_NONE      = 0x00,
     T_REGISTER  = 0x01,
     T_IMMEDIATE = 0x02,
     T_MEMORY    = 0x04,
     T_LABEL     = 0x08,
     T_ABSOLUTE  = 0x80
 } argtype_t;
modrm_sib_t
enum modrm_sib_t
Enumerator
MODRM_SIB
MODRM_NOSIB
Definition at line 174 of file vm_x86_64_assembler.c.
              {
     MODRM_SIB = 0,
     MODRM_NOSIB = 0x3,
 } modrm_sib_t;
reg_t
enum reg_t
Enumerator
R_8
R_16
R_64
R_MSZ
R_XMM
R_EAX
R_EBX
R_ECX
R_EDX
R_ESI
R_EDI
R_ESP
R_RAX
R_RBX
R_RCX
R_RDX
R_RSI
R_RDI
R_RSP
R_R8
R_R9
R_R10
R_R15
R_AL
R_AX
R_BL
R_CL
R_XMM0
R_MGP
Definition at line 142 of file vm_x86_64_assembler.c.
              {
     R_8   = 0x100,
     R_16  = 0x200,
     R_64  = 0x800,
     R_MSZ = 0xF00,  // size mask
     R_XMM = 0x2000, // xmm register. year, sucks
     R_EAX =  0x00,
     R_EBX =  0x03,
     R_ECX =  0x01,
     R_EDX =  0x02,
     R_ESI =  0x06,
     R_EDI =  0x07,
     R_ESP =  0x04,
     R_RAX =  R_EAX | R_64,
     R_RBX =  R_EBX | R_64,
     R_RCX =  R_ECX | R_64,
     R_RDX =  R_EDX | R_64,
     R_RSI =  R_ESI | R_64,
     R_RDI =  R_EDI | R_64,
     R_RSP =  R_ESP | R_64,
     R_R8  =  0x08  | R_64,
     R_R9  =  0x09  | R_64,
     R_R10 =  0x0A  | R_64,
     R_R15 =  0x0F  | R_64,
     R_AL  =  R_EAX | R_8,
     R_AX  =  R_EAX | R_16,
     R_BL  =  R_EBX | R_8,
     R_CL  =  R_ECX | R_8,
     R_XMM0 = 0x00  | R_XMM,
     R_MGP =  0x0F, // mask for general purpose registers
 } reg_t;
token_t
enum token_t
Enumerator
TOK_LABEL
TOK_INT
TOK_END
TOK_INVALID
Definition at line 1140 of file vm_x86_64_assembler.c.
              {
     TOK_LABEL = 0x80,
     TOK_INT = 0x81,
     TOK_END = 0x82,
     TOK_INVALID = 0x83,
 } token_t;
Function Documentation
__attribute__()
static __attribute__ ((noreturn)) static
Definition at line 65 of file vm_x86_64_assembler.c.
 {
     va_list ap;
     fprintf(stderr, "%s() - ", func);
     va_start(ap, fmt);
     vfprintf(stderr, fmt, ap);
     va_end(ap);
     fputc('\n', stderr);
     if(cur_line && cur_line[0])
         fprintf(stderr, "-> %s\n", cur_line);
     exit(1);
 }
References cur_line, and fmt.
argtype2str()
static const char* argtype2str (argtype_t t) static
Definition at line 334 of file vm_x86_64_assembler.c.
 {
     switch(t)
     {
         case T_NONE: return "none";
         case T_REGISTER: return "register";
         case T_IMMEDIATE: return "immediate";
         case T_MEMORY: return "memory";
         case T_LABEL: return "label";
         default: crap("invalid type");
     }
     /* not reached */
     return T_NONE;
 }
References crap, T_IMMEDIATE, T_LABEL, T_MEMORY, T_NONE, and T_REGISTER.
assemble_line()
void assemble_line (const char * input, size_t len)
Definition at line 1339 of file vm_x86_64_assembler.c.
 {
     char line[4096];
     char* s;
     op_t* o;
     char* opn;
     arg_t arg1, arg2;
     arg1.type = T_NONE;
     arg2.type = T_NONE;
     opn = NULL;
     o = NULL;
     if(len < 1)
         return;
     if(len >= sizeof(line))
         crap("line too long");
     memcpy(line, input, sizeof(line));
     cur_line = input;
     if(line[len-1] == '\n') line[--len] = 0;
     if(line[len-1] == ':')
     {
         line[--len] = 0;
         if(assembler_pass)
             debug("%s: 0x%x\n", line, compiledOfs);
         else
             hash_add_label(line, compiledOfs);
     }
     else
     {
         opn = line;
         s = strchr(line, ' ');
         if(s)
         {
             *s++ = 0;
             arg1 = parsearg((const char**)&s);
             if(*s)
             {
                 if(*s != ',')
                     crap("expected ',', got '%c'", *s);
                 ++s;
                 arg2 = parsearg((const char**)&s);
             }
         }
         if(!opn)
         {
             crap("no operator in %s", line);
         }
         o = getop(opn);
         if(!o)
         {
             crap("cannot handle op %s", opn);
         }
         o->func(opn, arg1, arg2, o->data);
         if(assembler_pass)
             debug("   - %s%s", cur_line, cur_line[strlen(cur_line)-1]=='\n'?"":"\n");
     }
 }
References assembler_pass, compiledOfs, crap, cur_line, op_t::data, debug, op_t::func, getop(), hash_add_label(), line, NULL, parsearg(), and T_NONE.
Referenced by __attribute__().
assembler_get_code_size()
size_t assembler_get_code_size (void)
Definition at line 1329 of file vm_x86_64_assembler.c.
 {
     return compiledOfs;
 }
References compiledOfs.
Referenced by VM_Compile().
assembler_init()
void assembler_init (int pass)
Definition at line 1313 of file vm_x86_64_assembler.c.
 {
     compiledOfs = 0;
     assembler_pass = pass;
     if(!pass)
     {
         labelhash_free();
         cur_line = NULL;
     }
     if(!ops_sorted)
     {
         ops_sorted = 1;
         qsort(ops, ARRAY_LEN(ops)-1, sizeof(ops[0]), opsort);
     }
 }
References ARRAY_LEN, assembler_pass, compiledOfs, cur_line, labelhash_free(), NULL, ops, ops_sorted, opsort(), and pass.
Referenced by VM_Compile().
assembler_set_output()
void assembler_set_output (char * buf)
Definition at line 1334 of file vm_x86_64_assembler.c.
 {
     out = buf;
 }
References out.
Referenced by VM_Compile().
compute_rexmodrmsib()
static void compute_rexmodrmsib (u8 * rex_r, u8 * modrm_r, u8 * sib_r, arg_t * arg1, arg_t * arg2) static
Definition at line 397 of file vm_x86_64_assembler.c.
 {
     u8 rex = 0;
     u8 modrm = 0;
     u8 sib = 0;
     if((arg1->type == T_REGISTER && arg2->type == T_REGISTER)
     && ((arg1->v.reg & R_MSZ) != (arg2->v.reg & R_MSZ))
     && !((arg1->v.reg & R_XMM) || (arg2->v.reg & R_XMM)))
         crap("both registers must be of same width");
     if((arg1->type == T_REGISTER && arg1->v.reg & R_64)
     || (arg2->type == T_REGISTER && arg2->v.reg & R_64))
     {
         rex |= REX_W;
     }
     if(arg1->type == T_REGISTER)
     {
         if((arg1->v.reg & R_MGP) > 0x07)
             rex |= REX_R;
         modrm |= (arg1->v.reg & 0x07) << 3;
     }
     if(arg2->type == T_REGISTER)
     {
         if((arg2->v.reg & R_MGP) > 0x07)
             rex |= REX_B;
         modrm |= (arg2->v.reg & 0x07);
     }
     if(arg2->type == T_MEMORY)
     {
         if((arg2->v.mem.basetype == T_REGISTER && !(arg2->v.mem.base.reg & R_64))
         || (arg2->v.mem.indextype == T_REGISTER && !(arg2->v.mem.index.reg & R_64)))
         {
             crap("only 64bit base/index registers are %x %x", arg2->v.mem.base.reg, arg2->v.mem.index.reg);
         }
         if(arg2->v.mem.indextype == T_REGISTER)
         {
             modrm |= MODRM_RM_SIB;
             if(!arg2->v.mem.disp)
             {
                 modrm |= MODRM_MOD_00;
             }
             else if(iss8(arg2->v.mem.disp))
             {
                 modrm |= MODRM_MOD_01;
             }
             else if(isu32(arg2->v.mem.disp))
             {
                 modrm |= MODRM_MOD_10;
             }
             else
             {
                 crap("invalid displacement");
             }
             if((arg2->v.mem.index.reg & R_MGP) > 0x07)
                 rex |= REX_X;
             if((arg2->v.mem.base.reg & R_MGP) > 0x07)
                 rex |= REX_B;
             if(arg2->v.mem.basetype != T_REGISTER)
                 crap("base must be register");
             switch(arg2->v.mem.scale)
             {
                 case 1: break;
                 case 2: sib |= 1 << 6; break;
                 case 4: sib |= 2 << 6; break;
                 case 8: sib |= 3 << 6; break;
             }
             sib |= (arg2->v.mem.index.reg & 0x07) << 3;
             sib |= (arg2->v.mem.base.reg & 0x07);
         }
         else if(arg2->v.mem.indextype == T_NONE)
         {
             if(!arg2->v.mem.disp)
             {
                 modrm |= MODRM_MOD_00;
             }
             else if(iss8(arg2->v.mem.disp))
             {
                 modrm |= MODRM_MOD_01;
             }
             else if(isu32(arg2->v.mem.disp))
             {
                 modrm |= MODRM_MOD_10;
             }
             else
             {
                 crap("invalid displacement");
             }
             if(arg2->v.mem.basetype != T_REGISTER)
                 crap("todo: base != register");
             if((arg2->v.mem.base.reg & R_MGP) > 0x07)
                 rex |= REX_B;
             modrm |= arg2->v.mem.base.reg & 0x07;
         }
         else
         {
             crap("invalid indextype");
         }
     }
     else
     {
         modrm |= MODRM_MOD_11;
     }
     if(rex)
         rex |= 0x40; // XXX
     *rex_r = rex;
     *modrm_r = modrm;
     *sib_r = sib;
 }
References crap, iss8(), isu32(), MODRM_MOD_00, MODRM_MOD_01, MODRM_MOD_10, MODRM_MOD_11, MODRM_RM_SIB, R_64, R_MGP, R_MSZ, R_XMM, REX_B, REX_R, REX_W, REX_X, T_MEMORY, T_NONE, and T_REGISTER.
Referenced by emit_call(), emit_jmp(), emit_mov(), emit_op_rm(), emit_op_rm_cl(), emit_subaddand(), and emit_twobyte().
emit1()
static void emit1 (unsigned char v) static
Definition at line 78 of file vm_x86_64_assembler.c.
 {
     int writecnt;
     if(assembler_pass)
     {
         out[compiledOfs++] = v;
         if(fout)
             writecnt = fwrite(&v, 1, 1, fout);
         debug("%02hx ", v);
     }
     else
     {
         ++compiledOfs;
     }
 }
References assembler_pass, compiledOfs, debug, fout, fwrite(), and out.
Referenced by emit2(), emit4(), emit_call(), emit_condjump(), emit_jmp(), emit_mov(), emit_op_rm(), emit_op_rm_cl(), emit_opreg(), emit_opsingle(), emit_opsingle16(), emit_subaddand(), emit_twobyte(), and maybe_emit_displacement().
emit2()
static void emit2 (u16 v) inline static
Definition at line 97 of file vm_x86_64_assembler.c.
 {
     emit1(v&0xFF);
     emit1((v>>8)&0xFF);
 }
References emit1().
Referenced by emit_mov().
emit4()
static void emit4 (u32 v) inline static
Definition at line 103 of file vm_x86_64_assembler.c.
 {
     emit1(v&0xFF);
     emit1((v>>8)&0xFF);
     emit1((v>>16)&0xFF);
     emit1((v>>24)&0xFF);
 }
References emit1().
Referenced by emit8(), emit_call(), emit_jmp(), emit_mov(), emit_subaddand(), and maybe_emit_displacement().
emit8()
static void emit8 (u64 v) inline static
Definition at line 111 of file vm_x86_64_assembler.c.
 {
     emit4(v&0xFFFFFFFF);
     emit4((v>>32)&0xFFFFFFFF);
 }
References emit4().
Referenced by emit_mov().
emit_call()
static void emit_call (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 861 of file vm_x86_64_assembler.c.
 {
     u8 rex, modrm, sib;
     if((arg1.type != T_REGISTER && arg1.type != T_IMMEDIATE) || arg2.type != T_NONE)
         CRAP_INVALID_ARGS;
     if(arg1.type == T_REGISTER)
     {
         if(!arg1.absolute)
             crap("call must be absolute");
         if((arg1.v.reg & R_64) != R_64)
             crap("register must be 64bit");
         arg1.v.reg ^= R_64; // no rex required for call
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg2, &arg1);
         modrm |= 0x2 << 3;
         if(rex) emit1(rex);
         emit1(0xff);
         emit1(modrm);
     }
     else
     {
         if(!isu32(arg1.v.imm))
             crap("must be 32bit argument");
         emit1(0xe8);
         emit4(arg1.v.imm);
     }
 }
References compute_rexmodrmsib(), crap, CRAP_INVALID_ARGS, emit1(), emit4(), isu32(), R_64, T_IMMEDIATE, T_NONE, and T_REGISTER.
emit_condjump()
static void emit_condjump (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 799 of file vm_x86_64_assembler.c.
 {
     unsigned off;
     int disp;
     unsigned char opcode = (unsigned char)(((uint64_t)data)&0xFF);
     if(arg1.type != T_LABEL || arg2.type != T_NONE)
         crap("%s: argument must be label", mnemonic);
     emit1(opcode);
     off = lookup_label(arg1.v.label);
     disp = off-(compiledOfs+1);
     if(assembler_pass && abs(disp) > 127)
         crap("cannot jump that far (%x -> %x = %x)", compiledOfs, off, disp);
     emit1(disp);
 }
References assembler_pass, compiledOfs, crap, emit1(), lookup_label(), off, T_LABEL, and T_NONE.
emit_jmp()
static void emit_jmp (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 818 of file vm_x86_64_assembler.c.
 {
     if((arg1.type != T_LABEL && arg1.type != T_REGISTER && arg1.type != T_MEMORY) || arg2.type != T_NONE)
         CRAP_INVALID_ARGS;
     if(arg1.type == T_LABEL)
     {
         unsigned off;
         int disp;
         off = lookup_label(arg1.v.label);
         disp = off-(compiledOfs+5);
         emit1(0xe9);
         emit4(disp);
     }
     else
     {
         u8 rex, modrm, sib;
         if(arg1.type == T_REGISTER)
         {
             if(!arg1.absolute)
                 crap("jmp must be absolute");
             if((arg1.v.reg & R_64) != R_64)
                 crap("register must be 64bit");
             arg1.v.reg ^= R_64; // no rex required for call
         }
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg2, &arg1);
         modrm |= 0x4 << 3;
         if(rex) emit1(rex);
         emit1(0xff);
         emit1(modrm);
         if((modrm & 0x07) == MODRM_RM_SIB)
             emit1(sib);
         maybe_emit_displacement(&arg1);
     }
 }
References compiledOfs, compute_rexmodrmsib(), crap, CRAP_INVALID_ARGS, emit1(), emit4(), lookup_label(), maybe_emit_displacement(), MODRM_RM_SIB, off, R_64, T_LABEL, T_MEMORY, T_NONE, and T_REGISTER.
emit_mov()
static void emit_mov (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 620 of file vm_x86_64_assembler.c.
 {
     u8 rex = 0;
     u8 modrm = 0;
     u8 sib = 0;
     if(arg1.type == T_IMMEDIATE && arg2.type == T_REGISTER)
     {
         u8 op = 0xb8;
         if(arg2.v.reg & R_8)
         {
             if(!iss8(arg1.v.imm))
                 crap("value too large for 8bit register");
             op = 0xb0;
         }
         else if(arg2.v.reg & R_16)
         {
             if(!isu16(arg1.v.imm))
                 crap("value too large for 16bit register");
             emit1(0x66);
         }
         else if(!(arg2.v.reg & R_64))
         {
             if(!isu32(arg1.v.imm))
                 crap("value too large for 32bit register");
         }
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg1, &arg2);
         if(rex) emit1(rex);
         op |= (arg2.v.reg & 0x07);
         emit1(op);
         if(arg2.v.reg & R_8) emit1(arg1.v.imm);
         else if(arg2.v.reg & R_16) emit2(arg1.v.imm);
         else if(arg2.v.reg & R_64) emit8(arg1.v.imm);
         else emit4(arg1.v.imm);
     }
     else if(arg1.type == T_IMMEDIATE && arg2.type == T_MEMORY)
     {
         if(!iss32(arg1.v.imm))
         {
             crap("only 32bit immediates supported");
         }
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg1, &arg2);
         if(rex) emit1(rex);
         emit1(0xc7); // mov reg/mem, imm
         emit1(modrm);
         if((modrm & 0x07) == MODRM_RM_SIB)
             emit1(sib);
         emit4(arg1.v.imm);
     }
     else if(arg1.type == T_REGISTER && arg2.type == T_REGISTER) // XXX: same as next
     {
         if(arg1.type != T_REGISTER || arg2.type != T_REGISTER)
             crap("both args must be registers");
         if((arg1.v.reg & R_MSZ) != (arg2.v.reg & R_MSZ))
             crap("both registers must be same width");
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg1, &arg2);
         if(rex) emit1(rex);
         emit1(0x89); // mov reg reg/mem,
         emit1(modrm);
     }
     else if(arg1.type == T_REGISTER && arg2.type == T_MEMORY)
     {
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg1, &arg2);
         if(arg1.v.reg & R_16)
             emit1(0x66);
         if(rex) emit1(rex);
         if(arg1.v.reg & R_8)
             emit1(0x88); // mov reg reg/mem,
         else
             emit1(0x89); // mov reg reg/mem,
         emit1(modrm);
         if((modrm & 0x07) == MODRM_RM_SIB)
             emit1(sib);
         maybe_emit_displacement(&arg2);
     }
     else if(arg1.type == T_MEMORY && arg2.type == T_REGISTER)
     {
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg2, &arg1);
         if(arg2.v.reg & R_16)
             emit1(0x66);
         if(rex) emit1(rex);
         if(arg2.v.reg & R_8)
             emit1(0x8a); // mov reg/mem, reg
         else
             emit1(0x8b); // mov reg/mem, reg
         emit1(modrm);
         if((modrm & 0x07) == MODRM_RM_SIB)
             emit1(sib);
         maybe_emit_displacement(&arg1);
     }
     else
         CRAP_INVALID_ARGS;
 }
References compute_rexmodrmsib(), crap, CRAP_INVALID_ARGS, emit1(), emit2(), emit4(), emit8(), iss32(), iss8(), isu16(), isu32(), maybe_emit_displacement(), MODRM_RM_SIB, op, R_16, R_64, R_8, R_MSZ, T_IMMEDIATE, T_MEMORY, and T_REGISTER.
emit_op_rm()
static void emit_op_rm (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 560 of file vm_x86_64_assembler.c.
 {
     u8 rex, modrm, sib;
     opparam_t* params = data;
     if((arg1.type != T_REGISTER && arg1.type != T_MEMORY) || arg2.type != T_NONE)
         CRAP_INVALID_ARGS;
     compute_rexmodrmsib(&rex, &modrm, &sib, &arg2, &arg1);
     modrm |= params->subcode << 3;
     if(arg1.v.reg & R_16)
         emit1(0x66);
     if(rex) emit1(rex);
     if(arg1.v.reg & R_8)
         emit1(params->rcode8); // op reg8/mem8,
     else
         emit1(params->rcode); // op reg/mem,
     emit1(modrm);
     if((modrm & 0x07) == MODRM_RM_SIB)
         emit1(sib);
     maybe_emit_displacement(&arg1);
 }
References compute_rexmodrmsib(), CRAP_INVALID_ARGS, emit1(), maybe_emit_displacement(), MODRM_RM_SIB, R_16, R_8, T_MEMORY, T_NONE, and T_REGISTER.
emit_op_rm_cl()
static void emit_op_rm_cl (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 588 of file vm_x86_64_assembler.c.
 {
     u8 rex, modrm, sib;
     opparam_t* params = data;
     if(arg2.type != T_REGISTER || arg1.type != T_REGISTER)
         CRAP_INVALID_ARGS;
     if((arg1.v.reg & R_MGP) != R_ECX && !(arg1.v.reg & R_8))
         crap("only cl register is valid");
     arg1.type = T_NONE; // don't complain, we know it's cl anyways
     compute_rexmodrmsib(&rex, &modrm, &sib, &arg1, &arg2);
     modrm |= params->subcode << 3;
     if(arg2.v.reg & R_16)
         emit1(0x66);
     if(rex) emit1(rex);
     if(arg2.v.reg & R_8)
         emit1(params->rcode8); // op reg8/mem8,
     else
         emit1(params->rcode); // op reg/mem,
     emit1(modrm);
     if((modrm & 0x07) == MODRM_RM_SIB)
         emit1(sib);
     maybe_emit_displacement(&arg2);
 }
References compute_rexmodrmsib(), crap, CRAP_INVALID_ARGS, emit1(), maybe_emit_displacement(), MODRM_RM_SIB, R_16, R_8, R_ECX, R_MGP, T_NONE, and T_REGISTER.
emit_opreg()
static void emit_opreg (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 544 of file vm_x86_64_assembler.c.
 {
     u8 op = (u8)((uint64_t) data);
     if(arg1.type != T_REGISTER || arg2.type != T_NONE)
         CRAP_INVALID_ARGS;
     if((arg1.v.reg & R_MGP) > 0x07)
         emit1(0x40 | REX_B);
     op |= (arg1.v.reg & 0x07);
     emit1(op);
 }
References CRAP_INVALID_ARGS, emit1(), op, R_MGP, REX_B, T_NONE, and T_REGISTER.
emit_opsingle()
static void emit_opsingle (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 381 of file vm_x86_64_assembler.c.
 {
     u8 op = (u8)((uint64_t) data);
     if(arg1.type != T_NONE || arg2.type != T_NONE)
         CRAP_INVALID_ARGS;
     emit1(op);
 }
References CRAP_INVALID_ARGS, emit1(), op, and T_NONE.
Referenced by emit_opsingle16().
emit_opsingle16()
static void emit_opsingle16 (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 391 of file vm_x86_64_assembler.c.
 {
     emit1(0x66);
     emit_opsingle(mnemonic, arg1, arg2, data);
 }
References emit1(), and emit_opsingle().
emit_subaddand()
static void emit_subaddand (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 732 of file vm_x86_64_assembler.c.
 {
     u8 rex = 0;
     u8 modrm = 0;
     u8 sib = 0;
     opparam_t* params = data;
     if(arg1.type == T_IMMEDIATE && arg2.type == T_REGISTER)
     {
         if(!iss32(arg1.v.imm))
         {
             crap("only 8 and 32 bit immediates supported");
         }
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg1, &arg2);
         modrm |= params->subcode << 3;
         if(rex) emit1(rex);
         if(arg2.v.reg & R_8)
         {
             emit1(0x80); // sub reg8/mem8, imm8
             emit1(modrm);
             emit1(arg1.v.imm & 0xFF);
         }
         else if(iss8(arg1.v.imm))
         {
             emit1(0x83); // sub reg/mem, imm8
             emit1(modrm);
             emit1(arg1.v.imm & 0xFF);
         }
         else
         {
             emit1(0x81); // sub reg/mem, imm32
             emit1(modrm);
             emit4(arg1.v.imm);
         }
     }
     else if(arg1.type == T_REGISTER && (arg2.type == T_MEMORY || arg2.type == T_REGISTER))
     {
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg1, &arg2);
         if(rex) emit1(rex);
         emit1(params->rmcode); // sub reg/mem, reg
         emit1(modrm);
         if(arg2.type == T_MEMORY && (modrm & 0x07) == MODRM_RM_SIB)
             emit1(sib);
         maybe_emit_displacement(&arg2);
     }
     else if(arg1.type == T_MEMORY && arg2.type == T_REGISTER && params->mrcode)
     {
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg2, &arg1);
         if(rex) emit1(rex);
         emit1(params->mrcode); // sub reg, reg/mem
         emit1(modrm);
         if((modrm & 0x07) == MODRM_RM_SIB)
             emit1(sib);
         maybe_emit_displacement(&arg1);
     }
     else
         CRAP_INVALID_ARGS;
 }
References compute_rexmodrmsib(), crap, CRAP_INVALID_ARGS, emit1(), emit4(), iss32(), iss8(), maybe_emit_displacement(), MODRM_RM_SIB, R_8, T_IMMEDIATE, T_MEMORY, and T_REGISTER.
emit_twobyte()
static void emit_twobyte (const char * mnemonic, arg_t arg1, arg_t arg2, void * data) static
Definition at line 896 of file vm_x86_64_assembler.c.
 {
     u8 rex, modrm, sib;
     opparam_t* params = data;
     if(arg1.type == T_REGISTER && (arg2.type == T_MEMORY || arg2.type == T_REGISTER))
     {
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg1, &arg2);
         if(params->xmmprefix) emit1(params->xmmprefix);
         if(rex) emit1(rex);
         emit1(0x0f);
         emit1(params->rmcode); // sub reg/mem, reg
         emit1(modrm);
         if((modrm & 0x07) == MODRM_RM_SIB)
             emit1(sib);
         maybe_emit_displacement(&arg2);
     }
     else if(arg1.type == T_MEMORY && arg2.type == T_REGISTER && params->mrcode)
     {
         compute_rexmodrmsib(&rex, &modrm, &sib, &arg2, &arg1);
         if(params->xmmprefix) emit1(params->xmmprefix);
         if(rex) emit1(rex);
         emit1(0x0f);
         emit1(params->mrcode); // sub reg, reg/mem
         emit1(modrm);
         if((modrm & 0x07) == MODRM_RM_SIB)
             emit1(sib);
         maybe_emit_displacement(&arg1);
     }
     else
         CRAP_INVALID_ARGS;
 }
References compute_rexmodrmsib(), CRAP_INVALID_ARGS, emit1(), maybe_emit_displacement(), MODRM_RM_SIB, T_MEMORY, and T_REGISTER.
getop()
static op_t* getop (const char * n) static
Definition at line 1019 of file vm_x86_64_assembler.c.
 {
 #if 0
     op_t* o = ops;
     while(o->mnemonic)
     {
         if(!strcmp(o->mnemonic, n))
             return o;
         ++o;
     }
 #else
     unsigned int m, t, b;
     int r;
     t = ARRAY_LEN(ops)-1;
     r = m = -1;
     do
     {
         if(r < 0)
             b = m + 1;
         else
             t = m - 1;
         m = ((t - b) >> 1) + b;
         if((r = strcmp(ops[m].mnemonic, n)) == 0)
             return &ops[m];
     } while(b <= t && t);
 #endif
     return NULL;
 }
References ARRAY_LEN, m, op_t::mnemonic, NULL, and ops.
Referenced by assemble_line().
hash_add_label()
static void hash_add_label (const char * label, unsigned address) static
Definition at line 271 of file vm_x86_64_assembler.c.
 {
     struct hashentry* h;
     unsigned i = hashkey(label, -1U);
     int labellen;
     i %= ARRAY_LEN(labelhash);
     h = Z_Malloc(sizeof(struct hashentry));
     labellen = strlen(label) + 1;
     h->label = Z_Malloc(labellen);
     memcpy(h->label, label, labellen);
     h->address = address;
     h->next = labelhash[i];
     labelhash[i] = h;
 }
References hashentry::address, ARRAY_LEN, hashkey(), hashentry::label, labelhash, hashentry::next, U, and Z_Malloc.
Referenced by assemble_line().
hashkey()
static unsigned hashkey (const char * string, unsigned len) static
Definition at line 252 of file vm_x86_64_assembler.c.
{
     unsigned register hash, i;
     hash = 0;
     for (i = 0; i < len && string[i] != '\0'; ++i) {
         hash += string[i] * (119 + i);
     }
     hash = (hash ^ (hash >> 10) ^ (hash >> 20));
     return hash;
 }
References hash().
Referenced by hash_add_label(), and lookup_label().
iss16()
static int iss16 (int64_t v) inline static
Definition at line 361 of file vm_x86_64_assembler.c.
 {
     return (SHRT_MIN <= v && v <= SHRT_MAX);
 }
iss32()
static int iss32 (int64_t v) inline static
Definition at line 371 of file vm_x86_64_assembler.c.
 {
     return (INT_MIN <= v && v <= INT_MAX);
 }
References INT_MAX.
Referenced by emit_mov(), and emit_subaddand().
iss8()
static int iss8 (int64_t v) inline static
Definition at line 351 of file vm_x86_64_assembler.c.
 {
     return (SCHAR_MIN <= v && v <= SCHAR_MAX);
 }
Referenced by compute_rexmodrmsib(), emit_mov(), emit_subaddand(), and maybe_emit_displacement().
isu16()
static int isu16 (u64 v) inline static
Definition at line 366 of file vm_x86_64_assembler.c.
 {
     return (v <= USHRT_MAX);
 }
Referenced by emit_mov().
isu32()
static int isu32 (u64 v) inline static
Definition at line 376 of file vm_x86_64_assembler.c.
 {
     return (v <= UINT_MAX);
 }
Referenced by compute_rexmodrmsib(), emit_call(), emit_mov(), and maybe_emit_displacement().
isu8()
static int isu8 (u64 v) inline static
Definition at line 356 of file vm_x86_64_assembler.c.
 {
     return (v <= UCHAR_MAX);
 }
labelhash_free()
static void labelhash_free (void) static
Definition at line 304 of file vm_x86_64_assembler.c.
 {
     struct hashentry* h;
     unsigned i;
     unsigned z = 0, min = -1U, max = 0, t = 0;
     for ( i = 0; i < ARRAY_LEN(labelhash); ++i)
     {
         unsigned n = 0;
         h = labelhash[i];
         while(h)
         {
             struct hashentry* next = h->next;
             Z_Free(h->label);
             Z_Free(h);
             h = next;
             ++n;
         }
         t+=n;
         if(!n) ++z;
         //else printf("%u\n", n);
         min = MIN(min, n);
         max = MAX(max, n);
     }
     printf("total %u, hsize %"PRIu64", zero %u, min %u, max %u\n", t, ARRAY_LEN(labelhash), z, min, max);
     memset(labelhash, 0, sizeof(labelhash));
 }
References ARRAY_LEN, hashentry::label, labelhash, MAX, MIN, hashentry::next, U, and Z_Free().
Referenced by assembler_init().
lookup_label()
static unsigned lookup_label (const char * label) static
Definition at line 289 of file vm_x86_64_assembler.c.
 {
     struct hashentry* h;
     unsigned i = hashkey(label, -1U);
     i %= ARRAY_LEN(labelhash);
     for(h = labelhash[i]; h; h = h->next )
     {
         if(!strcmp(h->label, label))
             return h->address;
     }
     if(assembler_pass)
         crap("label %s undefined", label);
     return 0;
 }
References hashentry::address, ARRAY_LEN, assembler_pass, crap, hashkey(), hashentry::label, labelhash, hashentry::next, and U.
Referenced by emit_condjump(), and emit_jmp().
maybe_emit_displacement()
static void maybe_emit_displacement (arg_t * arg) static
Definition at line 521 of file vm_x86_64_assembler.c.
 {
     if(arg->type != T_MEMORY)
         return;
     if(arg->v.mem.disp)
     {
         if(iss8(arg->v.mem.disp))
         {
             emit1((u8)arg->v.mem.disp);
         }
         else if(isu32(arg->v.mem.disp))
         {
             emit4(arg->v.mem.disp);
         }
         else
         {
             crap("invalid displacement");
         }
     }
 }
References crap, memref_t::disp, emit1(), emit4(), iss8(), isu32(), arg_t::mem, T_MEMORY, arg_t::type, and arg_t::v.
Referenced by emit_jmp(), emit_mov(), emit_op_rm(), emit_op_rm_cl(), emit_subaddand(), and emit_twobyte().
nexttok()
static unsigned char nexttok (const char ** str, char * label, u64 * val) static
Definition at line 1147 of file vm_x86_64_assembler.c.
 {
     const char* s = *str;
     if(label) *label = 0;
     if(val) *val = 0;
     while(*s && *s == ' ') ++s;
     if(!*s)
     {
         return TOK_END;
     }
     else if(*s == '$' || *s == '*' || *s == '%' || *s == '-' || *s == ')' || *s == '(' || *s == ',')
     {
         *str = s+1;
         return *s;
     }
     else if(*s >= 'a' && *s <= 'z')
     {
         size_t a = strspn(s+1, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_");
         if(a+1 >= LABELLEN)
             crap("label %s too long", s);
         if(label)
         {
             strncpy(label, s, a+1);
             label[a+1] = 0;
         }
         *str = s+a+1;
         return TOK_LABEL;
     }
     else if(*s >= '0' && *s <= '9')
     {
         char* endptr = NULL;
         u64 v = strtoull(s, &endptr, 0);
         if(endptr && (endptr-s == 0))
             crap("invalid integer %s", s);
         if(val) *val = v;
         *str = endptr;
         return TOK_INT;
     }
     crap("can't parse '%s'", *str);
     return TOK_INVALID;
 }
References crap, hashentry::label, LABELLEN, NULL, TOK_END, TOK_INT, TOK_INVALID, TOK_LABEL, and val.
Referenced by parsearg().
opsort()
static int opsort (const void * A, const void * B) static
Definition at line 1012 of file vm_x86_64_assembler.c.
 {
     const op_t* a = A;
     const op_t* b = B;
     return strcmp(a->mnemonic, b->mnemonic);
 }
References A, and B.
Referenced by assembler_init().
parsearg()
static arg_t parsearg (const char ** str) static
Definition at line 1192 of file vm_x86_64_assembler.c.
 {
     arg_t arg;
     const char* s = *str;
     char label[20];
     u64 val;
     int negative = 1;
     unsigned ttype;
     arg.type = T_NONE;
     arg.absolute = 0;
     while(*s && *s == ' ') ++s;
     switch(nexttok(&s, label, &val))
     {
         case '$' :
             ttype = nexttok(&s, NULL, &val);
             if(ttype == '-')
             {
                 negative = -1;
                 ttype = nexttok(&s, NULL, &val);
             }
             if(ttype != TOK_INT)
                 crap("expected integer");
             arg.type = T_IMMEDIATE;
             arg.v.imm = negative * val;
             break;
         case '*' :
             if((ttype = nexttok(&s, NULL, NULL)) != '%')
             {
                 if(ttype == '(')
                     goto tok_memory;
                 crap("expected '%%'");
             }
             arg.absolute = 1;
             /* fall through */
         case '%' :
             if(nexttok(&s, label, &val) != TOK_LABEL)
                 crap("expected label");
             arg.type = T_REGISTER;
             arg.v.reg = parsereg(label);
             break;
         case TOK_LABEL:
             arg.type = T_LABEL;
             strncpy(arg.v.label, label, LABELLEN);
             break;
         case '-':
             negative = -1;
             if(nexttok(&s, NULL, &val) != TOK_INT)
                 crap("expected integer");
             /* fall through */
         case TOK_INT:
             if(nexttok(&s, label, NULL) != '(')
                 crap("expected '('"); // mov to/from fixed address not supported
             /* fall through */
         case '(':
 tok_memory:
             arg.type = T_MEMORY;
             arg.v.mem.indextype = T_NONE;
             arg.v.mem.disp = negative * val;
             ttype = nexttok(&s, label, &val);
             if(ttype == '%' && nexttok(&s, label, &val) != TOK_LABEL)
             {
                 crap("expected register");
             }
             if (ttype == '%')
             {
                 arg.v.mem.basetype = T_REGISTER;
                 arg.v.mem.base.reg = parsereg(label);
             }
             else if (ttype == TOK_INT)
             {
                 arg.v.mem.basetype = T_IMMEDIATE;
                 arg.v.mem.base.imm = val;
             }
             if((ttype = nexttok(&s, NULL, NULL)) == ',')
             {
                 ttype = nexttok(&s, label, &val);
                 if(ttype == '%' && nexttok(&s, label, &val) != TOK_LABEL)
                 {
                     crap("expected register");
                 }
                 if (ttype == '%')
                 {
                     arg.v.mem.indextype = T_REGISTER;
                     arg.v.mem.index.reg = parsereg(label);
                 }
                 else if (ttype == TOK_INT)
                 {
                     crap("index must be register");
                     arg.v.mem.indextype = T_IMMEDIATE;
                     arg.v.mem.index.imm = val;
                 }
                 if(nexttok(&s, NULL, NULL) != ',')
                     crap("expected ','");
                 if(nexttok(&s, NULL, &val) != TOK_INT)
                     crap("expected integer");
                 if(val != 1 && val != 2 && val != 4 && val != 8)
                     crap("scale must 1, 2, 4 or 8");
                 arg.v.mem.scale = val;
                 ttype = nexttok(&s, NULL, NULL);
             }
             if(ttype != ')')
             {
                 crap("expected ')' or ','");
             }
             break;
         default:
             crap("invalid token %hu in %s", *(unsigned char*)s, *str);
             break;
     }
     *str = s;
     return arg;
 }
References arg_t::absolute, memref_t::base, memref_t::basetype, crap, memref_t::disp, memref_t::imm, arg_t::imm, memref_t::index, memref_t::indextype, arg_t::label, hashentry::label, LABELLEN, arg_t::mem, nexttok(), NULL, parsereg(), memref_t::reg, arg_t::reg, memref_t::scale, T_IMMEDIATE, T_LABEL, T_MEMORY, T_NONE, T_REGISTER, TOK_INT, TOK_LABEL, arg_t::type, arg_t::v, and val.
Referenced by assemble_line().
parsereg()
static reg_t parsereg (const char * str) static
Definition at line 1054 of file vm_x86_64_assembler.c.
 {
     const char* s = str;
     if(*s == 'a' && s[1] == 'l' && !s[2])
     {
         return R_AL;
     }
     else if(*s == 'a' && s[1] == 'x' && !s[2])
     {
         return R_AX;
     }
     if(*s == 'b' && s[1] == 'l' && !s[2])
     {
         return R_BL;
     }
     if(*s == 'c' && s[1] == 'l' && !s[2])
     {
         return R_CL;
     }
     if(*s == 'x')
     {
         if(!strcmp(s, "xmm0"))
             return R_XMM0;
     }
     else if(*s == 'r' && s[1])
     {
         ++s;
         if(s[1] == 'x')
         {
             switch(*s++)
             {
                 case 'a': return R_RAX;
                 case 'b': return R_RBX;
                 case 'c': return R_RCX;
                 case 'd': return R_RDX;
             }
         }
         else if(s[1] == 'i')
         {
             switch(*s++)
             {
                 case 's': return R_RSI;
                 case 'd': return R_RDI;
             }
         }
         else if(s[0] == 's' && s[1] == 'p' && !s[2])
         {
             return R_RSP;
         }
         else if(*s == '8' && !s[1])
             return R_R8;
         else if(*s == '9' && !s[1])
             return R_R9;
         else if(*s == '1' && s[1] == '0')
             return R_R10;
         else if(*s == '1' && s[1] == '5')
             return R_R15;
     }
     else if(*s == 'e' && s[1])
     {
         ++s;
         if(s[1] == 'x')
         {
             switch(*s++)
             {
                 case 'a': return R_EAX;
                 case 'b': return R_EBX;
                 case 'c': return R_ECX;
                 case 'd': return R_EDX;
             }
         }
         else if(s[1] == 'i')
         {
             switch(*s++)
             {
                 case 's': return R_ESI;
                 case 'd': return R_EDI;
             }
         }
     }
     crap("invalid register %s", str);
     return 0;
 }
References crap, R_AL, R_AX, R_BL, R_CL, R_EAX, R_EBX, R_ECX, R_EDI, R_EDX, R_ESI, R_R10, R_R15, R_R8, R_R9, R_RAX, R_RBX, R_RCX, R_RDI, R_RDX, R_RSI, R_RSP, and R_XMM0.
Referenced by parsearg().
Variable Documentation
assembler_pass
unsigned assembler_pass static
Definition at line 47 of file vm_x86_64_assembler.c.
Referenced by assemble_line(), assembler_init(), emit1(), emit_condjump(), and lookup_label().
compiledOfs
unsigned compiledOfs static
Definition at line 46 of file vm_x86_64_assembler.c.
Referenced by assemble_line(), assembler_get_code_size(), assembler_init(), emit1(), emit_condjump(), and emit_jmp().
cur_line
const char* cur_line static
Definition at line 49 of file vm_x86_64_assembler.c.
Referenced by __attribute__(), assemble_line(), and assembler_init().
fout
FILE* fout static
Definition at line 51 of file vm_x86_64_assembler.c.
Referenced by add_bit(), emit1(), Huff_offsetTransmit(), Huff_putBit(), Huff_transmit(), kiss_fft(), kiss_fft_stride(), main(), and send().
labelhash
struct hashentry* labelhash[1021] static
Definition at line 268 of file vm_x86_64_assembler.c.
Referenced by hash_add_label(), labelhash_free(), and lookup_label().
ops
op_t ops[] static
Definition at line 935 of file vm_x86_64_assembler.c.
Referenced by assembler_init(), and getop().
ops_sorted
int ops_sorted = 0 static
Definition at line 934 of file vm_x86_64_assembler.c.
Referenced by assembler_init().
out
char* out static
Definition at line 45 of file vm_x86_64_assembler.c.
Referenced by _VectorAdd(), _VectorCopy(), _VectorScale(), _VectorSubtract(), assembler_set_output(), AxisCopy(), BuildShaderStateConfig(), CG_AdjustPositionForMover(), CG_InterpolatePlayerState(), ClientCleanName(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadLeafSurfaces(), CMod_LoadNodes(), CMod_LoadPlanes(), CMod_LoadShaders(), CMod_LoadSubmodels(), COM_Compress(), COM_StripExtension(), CON_LogRead(), copy4(), CopyString(), decodeMuLaw(), decodeWavelet(), emit1(), encodeMuLaw(), encodeWavelet(), filter_dc_notch16(), FloatSwap(), G_SpawnFloat(), G_SpawnInt(), G_SpawnString(), G_SpawnVector(), GlobalVectorToLocal(), inflate(), inflate_fast(), inflateSync(), init_error_limit(), LerpDrawVert(), LocalAddScaledMatrixTransformVector(), LocalAddScaledMatrixTransformVectorFullTranslate(), LocalAddScaledMatrixTransformVectorTranslate(), LocalMatrixTransformVector(), LocalMatrixTransformVectorTranslate(), LocalScaledMatrixTransformVector(), LocalScaledMatrixTransformVectorFullTranslate(), LocalScaledMatrixTransformVectorTranslate(), LocalVectorMA(), Matrix34Multiply(), Matrix4Copy(), Matrix4Multiply(), MatrixMultiply(), mdfour(), mdfour_result(), myGlMultMatrix(), nb_decode(), nb_decode_lost(), NormalizeColor(), NXPutc(), PM_ClipVelocity(), Q_getwd(), R_ColorShiftLightingBytes(), R_LoadFogs(), R_LoadJPG(), R_LoadLightmaps(), R_LoadMarksurfaces(), R_LoadNodesAndLeafs(), R_LoadPCX(), R_LoadPlanes(), R_LoadShaders(), R_LoadSubmodels(), R_LoadSurfaces(), R_MipMap(), R_MirrorPoint(), R_MirrorVector(), RE_RegisterFont(), RE_SaveJPG(), resampler_basic_direct_double(), resampler_basic_direct_single(), resampler_basic_interpolate_double(), resampler_basic_interpolate_single(), ResampleTexture(), S_AdpcmEncodeSound(), S_AdpcmGetSamples(), S_Base_AddLoopingSound(), S_TransferPaintBuffer(), sb_decode(), sb_decode_lost(), SetPlaneSignbits(), SLerp_Normal(), speex_decode(), speex_decode_int(), speex_decode_native(), speex_echo_cancel(), speex_echo_cancellation(), speex_echo_capture(), speex_resampler_process_float(), speex_resampler_process_int(), speex_resampler_process_interleaved_float(), speex_resampler_process_interleaved_int(), speex_resampler_process_native(), spx_fft(), spx_fft_float(), spx_ifft(), spx_ifft_float(), updatewindow(), Vector4Scale(), VectorNormalize2(), VectorPieceWiseMultiply(), and VectorRotate().
params_add
opparam_t params_add = { subcode: 0, rmcode: 0x01, } static
Definition at line 224 of file vm_x86_64_assembler.c.
params_addss
opparam_t params_addss = { xmmprefix: 0xf3, mrcode: 0x58 } static
Definition at line 243 of file vm_x86_64_assembler.c.
params_and
opparam_t params_and = { subcode: 4, rmcode: 0x21, } static
Definition at line 226 of file vm_x86_64_assembler.c.
params_cmp
opparam_t params_cmp = { subcode: 7, rmcode: 0x39, mrcode: 0x3b, } static
Definition at line 229 of file vm_x86_64_assembler.c.
params_cvtsi2ss
opparam_t params_cvtsi2ss = { xmmprefix: 0xf3, rmcode: 0x2a } static
Definition at line 241 of file vm_x86_64_assembler.c.
params_cvttss2si
opparam_t params_cvttss2si = { xmmprefix: 0xf3, rmcode: 0x2c } static
Definition at line 242 of file vm_x86_64_assembler.c.
params_dec
opparam_t params_dec = { subcode: 1, rcode: 0xff, rcode8: 0xfe, } static
Definition at line 230 of file vm_x86_64_assembler.c.
params_div
opparam_t params_div = { subcode: 6, rcode: 0xf7, rcode8: 0xf6, } static
Definition at line 235 of file vm_x86_64_assembler.c.
params_divss
opparam_t params_divss = { xmmprefix: 0xf3, mrcode: 0x5e } static
Definition at line 244 of file vm_x86_64_assembler.c.
params_idiv
opparam_t params_idiv = { subcode: 7, rcode: 0xf7, rcode8: 0xf6, } static
Definition at line 234 of file vm_x86_64_assembler.c.
params_imul
opparam_t params_imul = { subcode: 5, rcode: 0xf7, rcode8: 0xf6, } static
Definition at line 236 of file vm_x86_64_assembler.c.
params_movss
opparam_t params_movss = { xmmprefix: 0xf3, mrcode: 0x10, rmcode: 0x11 } static
Definition at line 245 of file vm_x86_64_assembler.c.
params_mul
opparam_t params_mul = { subcode: 4, rcode: 0xf7, rcode8: 0xf6, } static
Definition at line 237 of file vm_x86_64_assembler.c.
params_mulss
opparam_t params_mulss = { xmmprefix: 0xf3, mrcode: 0x59 } static
Definition at line 246 of file vm_x86_64_assembler.c.
params_neg
opparam_t params_neg = { subcode: 3, rcode: 0xf7, rcode8: 0xf6, } static
Definition at line 238 of file vm_x86_64_assembler.c.
params_not
opparam_t params_not = { subcode: 2, rcode: 0xf7, rcode8: 0xf6, } static
Definition at line 239 of file vm_x86_64_assembler.c.
params_or
opparam_t params_or = { subcode: 1, rmcode: 0x09, } static
Definition at line 225 of file vm_x86_64_assembler.c.
params_sar
opparam_t params_sar = { subcode: 7, rcode: 0xd3, rcode8: 0xd2, } static
Definition at line 231 of file vm_x86_64_assembler.c.
params_shl
opparam_t params_shl = { subcode: 4, rcode: 0xd3, rcode8: 0xd2, } static
Definition at line 232 of file vm_x86_64_assembler.c.
params_shr
opparam_t params_shr = { subcode: 5, rcode: 0xd3, rcode8: 0xd2, } static
Definition at line 233 of file vm_x86_64_assembler.c.
params_sub
opparam_t params_sub = { subcode: 5, rmcode: 0x29, } static
Definition at line 227 of file vm_x86_64_assembler.c.
params_subss
opparam_t params_subss = { xmmprefix: 0xf3, mrcode: 0x5c } static
Definition at line 247 of file vm_x86_64_assembler.c.
params_ucomiss
opparam_t params_ucomiss = { mrcode: 0x2e } static
Definition at line 248 of file vm_x86_64_assembler.c.
params_xor
opparam_t params_xor = { subcode: 6, rmcode: 0x31, } static
Definition at line 228 of file vm_x86_64_assembler.c.