ZEQ2-Lite: Image Class Reference
Image Class Reference
#include <gdiplusheaders.h>
Public Member Functions
Image (const WCHAR *filename, BOOL useEmbeddedColorManagement=FALSE)
Image (IStream *stream, BOOL useEmbeddedColorManagement=FALSE)
virtual ~Image ()
virtual Image * Clone () const
Status FindFirstItem (ImageItemData *item)
Status FindNextItem (ImageItemData *item)
Status GetAllPropertyItems (UINT totalBufferSize, UINT numProperties, PropertyItem *allItems)
Status GetBounds (RectF *srcRect, Unit *srcUnit)
Status GetEncoderParameterList (const CLSID *clsidEncoder, UINT size, EncoderParameters *buffer)
UINT GetEncoderParameterListSize (const CLSID *clsidEncoder)
UINT GetFlags ()
UINT GetFrameCount (const GUID *dimensionID)
UINT GetFrameDimensionsCount ()
Status GetFrameDimensionsList (GUID *dimensionIDs, UINT count)
UINT GetHeight ()
REAL GetHorizontalResolution ()
Status GetItemData (ImageItemData *item)
Status GetLastStatus () const
Status GetPalette (ColorPalette *palette, INT size)
INT GetPaletteSize ()
Status GetPhysicalDimension (SizeF *size)
PixelFormat GetPixelFormat ()
UINT GetPropertyCount ()
Status GetPropertyIdList (UINT numOfProperty, PROPID *list)
Status GetPropertyItem (PROPID propId, UINT propSize, PropertyItem *buffer)
UINT GetPropertyItemSize (PROPID propId)
Status GetPropertySize (UINT *totalBufferSize, UINT *numProperties)
Status GetRawFormat (GUID *format)
Image * GetThumbnailImage (UINT thumbWidth, UINT thumbHeight, GetThumbnailImageAbort callback, VOID *callbackData)
ImageType GetType () const
REAL GetVerticalResolution ()
UINT GetWidth ()
Status RemovePropertyItem (PROPID propId)
Status RotateFlip (RotateFlipType rotateFlipType)
Status Save (const WCHAR *filename, const CLSID *clsidEncoder, const EncoderParameters *encoderParams)
Status Save (IStream *stream, const CLSID *clsidEncoder, const EncoderParameters *encoderParams)
Status SaveAdd (const EncoderParameters *encoderParams)
Status SaveAdd (Image *newImage, const EncoderParameters *encoderParams)
Status SelectActiveFrame (const GUID *dimensionID, UINT frameIndex)
Status SetAbort (GdiplusAbort *pIAbort)
Status SetPalette (const ColorPalette *palette)
Status SetPropertyItem (const PropertyItem *item)
Static Public Member Functions
static Image * FromFile (const WCHAR *filename, BOOL useEmbeddedColorManagement=FALSE)
static Image * FromStream (IStream *stream, BOOL useEmbeddedColorManagement=FALSE)
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Image (const Image &)
Image (GpImage *image, Status status)
Image & operator= (const Image &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpImage * nativeImage
Friends
class Bitmap
class CachedBitmap
class Graphics
class Metafile
class TextureBrush
Detailed Description
Definition at line 51 of file gdiplusheaders.h.
Constructor & Destructor Documentation
Image() [1/4]
__inline__ Image::Image (const WCHAR * filename, BOOL useEmbeddedColorManagement = FALSE)
Definition at line 55 of file gdiplusimpl.h.
                                                                              :
     nativeImage(NULL), lastStatus(Ok)
 {
     if (useEmbeddedColorManagement) {
         lastStatus = DllExports::GdipLoadImageFromFileICM(
                 filename, &nativeImage);
     } else {
         lastStatus = DllExports::GdipLoadImageFromFile(
                 filename, &nativeImage);
     }
 }
References GdipLoadImageFromFile(), GdipLoadImageFromFileICM(), lastStatus, and nativeImage.
Referenced by Clone(), FromFile(), FromStream(), and GetThumbnailImage().
Image() [2/4]
__inline__ Image::Image (IStream * stream, BOOL useEmbeddedColorManagement = FALSE)
Definition at line 67 of file gdiplusimpl.h.
                                                                        :
     nativeImage(NULL), lastStatus(Ok)
 {
     if (useEmbeddedColorManagement) {
         lastStatus = DllExports::GdipLoadImageFromStreamICM(
                 stream, &nativeImage);
     } else {
         lastStatus = DllExports::GdipLoadImageFromStream(
                 stream, &nativeImage);
     }
 }
References GdipLoadImageFromStream(), GdipLoadImageFromStreamICM(), lastStatus, and nativeImage.
~Image()
virtual Image::~Image () inline virtual
Definition at line 68 of file gdiplusheaders.h.
     {
         DllExports::GdipDisposeImage(nativeImage);
     }
References GdipDisposeImage(), and nativeImage.
Image() [3/4]
Image::Image (GpImage * image, Status status) inline private
Definition at line 141 of file gdiplusheaders.h.
                                         :
         nativeImage(image), lastStatus(status) {}
Image() [4/4]
Image::Image (const Image &) private
Member Function Documentation
Clone()
virtual Image* Image::Clone () const inline virtual
Reimplemented in Metafile, and Bitmap.
Definition at line 72 of file gdiplusheaders.h.
     {
         GpImage *cloneImage = NULL;
         Status status = updateStatus(DllExports::GdipCloneImage(
                 nativeImage, &cloneImage));
         if (status == Ok) {
             Image *result = new Image(cloneImage, lastStatus);
             if (!result) {
                 DllExports::GdipDisposeImage(cloneImage);
                 lastStatus = OutOfMemory;
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneImage(), GdipDisposeImage(), Image(), lastStatus, nativeImage, NULL, Ok, OutOfMemory, and updateStatus().
FindFirstItem()
__inline__ Status Image::FindFirstItem (ImageItemData * item)
Definition at line 79 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipFindFirstImageItem b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipFindFirstImageItem(
             nativeImage, item));
 }
References GdipFindFirstImageItem(), nativeImage, and updateStatus().
FindNextItem()
__inline__ Status Image::FindNextItem (ImageItemData * item)
Definition at line 86 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipFindFirstImageItem b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipFindNextImageItem(
             nativeImage, item));
 }
References GdipFindNextImageItem(), nativeImage, and updateStatus().
FromFile()
__inline__ Image * Image::FromFile (const WCHAR * filename, BOOL useEmbeddedColorManagement = FALSE) static
Definition at line 43 of file gdiplusimpl.h.
 {
     return new Image(filename, useEmbeddedColorManagement);
 }
References Image().
FromStream()
__inline__ Image * Image::FromStream (IStream * stream, BOOL useEmbeddedColorManagement = FALSE) static
Definition at line 49 of file gdiplusimpl.h.
 {
     return new Image(stream, useEmbeddedColorManagement);
 }
References Image().
GetAllPropertyItems()
__inline__ Status Image::GetAllPropertyItems (UINT totalBufferSize, UINT numProperties, PropertyItem * allItems)
Definition at line 93 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetAllPropertyItems(
             nativeImage, totalBufferSize, numProperties, allItems));
 }
References GdipGetAllPropertyItems(), nativeImage, and updateStatus().
GetBounds()
__inline__ Status Image::GetBounds (RectF * srcRect, Unit * srcUnit)
Definition at line 100 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImageBounds(
             nativeImage, srcRect, srcUnit));
 }
References GdipGetImageBounds(), nativeImage, and updateStatus().
GetEncoderParameterList()
__inline__ Status Image::GetEncoderParameterList (const CLSID * clsidEncoder, UINT size, EncoderParameters * buffer)
Definition at line 106 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetEncoderParameterList(
             nativeImage, clsidEncoder, size, buffer));
 }
References GdipGetEncoderParameterList(), nativeImage, and updateStatus().
GetEncoderParameterListSize()
__inline__ UINT Image::GetEncoderParameterListSize (const CLSID * clsidEncoder)
Definition at line 113 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetEncoderParameterListSize(
             nativeImage, clsidEncoder, &result));
     return result;
 }
References GdipGetEncoderParameterListSize(), nativeImage, and updateStatus().
GetFlags()
__inline__ UINT Image::GetFlags ()
Definition at line 121 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageFlags(nativeImage, &result));
     return result;
 }
References GdipGetImageFlags(), nativeImage, and updateStatus().
GetFrameCount()
__inline__ UINT Image::GetFrameCount (const GUID * dimensionID)
Definition at line 128 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipImageGetFrameCount(
             nativeImage, dimensionID, &result));
     return result;
 }
References GdipImageGetFrameCount(), nativeImage, and updateStatus().
GetFrameDimensionsCount()
__inline__ UINT Image::GetFrameDimensionsCount ()
Definition at line 136 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipImageGetFrameDimensionsCount(
             nativeImage, &result));
     return result;
 }
References GdipImageGetFrameDimensionsCount(), nativeImage, and updateStatus().
GetFrameDimensionsList()
__inline__ Status Image::GetFrameDimensionsList (GUID * dimensionIDs, UINT count)
Definition at line 144 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageGetFrameDimensionsList(
             nativeImage, dimensionIDs, count));
 }
References GdipImageGetFrameDimensionsList(), nativeImage, and updateStatus().
GetHeight()
__inline__ UINT Image::GetHeight ()
Definition at line 150 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageHeight(nativeImage, &result));
     return result;
 }
References GdipGetImageHeight(), nativeImage, and updateStatus().
GetHorizontalResolution()
__inline__ REAL Image::GetHorizontalResolution ()
Definition at line 157 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetImageHorizontalResolution(
             nativeImage, &result));
     return result;
 }
References GdipGetImageHorizontalResolution(), nativeImage, and updateStatus().
GetItemData()
__inline__ Status Image::GetItemData (ImageItemData * item)
Definition at line 165 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipGetImageItemData b/c it isn't exported in 1.0
     return updateStatus(DllExports::GdipGetImageItemData(
             nativeImage, item));
 }
References GdipGetImageItemData(), nativeImage, and updateStatus().
GetLastStatus()
Status Image::GetLastStatus () const inline
Definition at line 133 of file gdiplusheaders.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetPalette()
__inline__ Status Image::GetPalette (ColorPalette * palette, INT size)
Definition at line 172 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImagePalette(
             nativeImage, palette, size));
 }
References GdipGetImagePalette(), nativeImage, and updateStatus().
GetPaletteSize()
__inline__ INT Image::GetPaletteSize ()
Definition at line 178 of file gdiplusimpl.h.
 {
     INT result = 0;
     updateStatus(DllExports::GdipGetImagePaletteSize(nativeImage, &result));
     return result;
 }
References GdipGetImagePaletteSize(), nativeImage, and updateStatus().
GetPhysicalDimension()
__inline__ Status Image::GetPhysicalDimension (SizeF * size)
Definition at line 185 of file gdiplusimpl.h.
 {
     if (!size) return lastStatus = InvalidParameter;
     return updateStatus(DllExports::GdipGetImageDimension(
             nativeImage, &size->Width, &size->Height));
 }
References GdipGetImageDimension(), InvalidParameter, lastStatus, nativeImage, and updateStatus().
GetPixelFormat()
__inline__ PixelFormat Image::GetPixelFormat ()
Definition at line 192 of file gdiplusimpl.h.
 {
     PixelFormat result = (PixelFormat) 0;
     updateStatus(DllExports::GdipGetImagePixelFormat(nativeImage, &result));
     return result;
 }
References GdipGetImagePixelFormat(), nativeImage, and updateStatus().
GetPropertyCount()
__inline__ UINT Image::GetPropertyCount ()
Definition at line 199 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetPropertyCount(nativeImage, &result));
     return result;
 }
References GdipGetPropertyCount(), nativeImage, and updateStatus().
GetPropertyIdList()
__inline__ Status Image::GetPropertyIdList (UINT numOfProperty, PROPID * list)
Definition at line 206 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertyIdList(
             nativeImage, numOfProperty, list));
 }
References GdipGetPropertyIdList(), nativeImage, and updateStatus().
GetPropertyItem()
__inline__ Status Image::GetPropertyItem (PROPID propId, UINT propSize, PropertyItem * buffer)
Definition at line 212 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertyItem(
             nativeImage, propId, propSize, buffer));
 }
References GdipGetPropertyItem(), nativeImage, and updateStatus().
GetPropertyItemSize()
__inline__ UINT Image::GetPropertyItemSize (PROPID propId)
Definition at line 219 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetPropertyItemSize(
             nativeImage, propId, &result));
     return result;
 }
References GdipGetPropertyItemSize(), nativeImage, and updateStatus().
GetPropertySize()
__inline__ Status Image::GetPropertySize (UINT * totalBufferSize, UINT * numProperties)
Definition at line 227 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetPropertySize(
             nativeImage, totalBufferSize, numProperties));
 }
References GdipGetPropertySize(), nativeImage, and updateStatus().
GetRawFormat()
__inline__ Status Image::GetRawFormat (GUID * format)
Definition at line 234 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipGetImageRawFormat(
             nativeImage, format));
 }
References GdipGetImageRawFormat(), nativeImage, and updateStatus().
GetThumbnailImage()
__inline__ Image * Image::GetThumbnailImage (UINT thumbWidth, UINT thumbHeight, GetThumbnailImageAbort callback, VOID * callbackData)
Definition at line 240 of file gdiplusimpl.h.
 {
     GpImage *thumbImage = NULL;
     Status status = updateStatus(DllExports::GdipGetImageThumbnail(
             nativeImage, thumbWidth, thumbHeight, &thumbImage,
             callback, callbackData));
     if (status == Ok) {
         Image *result = new Image(thumbImage, Ok);
         if (!result) {
             DllExports::GdipDisposeImage(thumbImage);
             lastStatus = OutOfMemory;
         }
         return result;
     } else {
         return NULL;
     }
 }
References GdipDisposeImage(), GdipGetImageThumbnail(), Image(), lastStatus, nativeImage, NULL, Ok, OutOfMemory, and updateStatus().
GetType()
__inline__ ImageType Image::GetType () const
Definition at line 260 of file gdiplusimpl.h.
 {
     ImageType result = ImageTypeUnknown;
     updateStatus(DllExports::GdipGetImageType(nativeImage, &result));
     return result;
 }
References GdipGetImageType(), ImageTypeUnknown, nativeImage, and updateStatus().
GetVerticalResolution()
__inline__ REAL Image::GetVerticalResolution ()
Definition at line 267 of file gdiplusimpl.h.
 {
     REAL result = 0.0f;
     updateStatus(DllExports::GdipGetImageVerticalResolution(
             nativeImage, &result));
     return result;
 }
References GdipGetImageVerticalResolution(), nativeImage, and updateStatus().
GetWidth()
__inline__ UINT Image::GetWidth ()
Definition at line 275 of file gdiplusimpl.h.
 {
     UINT result = 0;
     updateStatus(DllExports::GdipGetImageWidth(nativeImage, &result));
     return result;
 }
References GdipGetImageWidth(), nativeImage, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Image& Image::operator= (const Image &) private
RemovePropertyItem()
__inline__ Status Image::RemovePropertyItem (PROPID propId)
Definition at line 282 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipRemovePropertyItem(
             nativeImage, propId));
 }
References GdipRemovePropertyItem(), nativeImage, and updateStatus().
RotateFlip()
__inline__ Status Image::RotateFlip (RotateFlipType rotateFlipType)
Definition at line 288 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageRotateFlip(
             nativeImage, rotateFlipType));
 }
References GdipImageRotateFlip(), nativeImage, and updateStatus().
Save() [1/2]
__inline__ Status Image::Save (const WCHAR * filename, const CLSID * clsidEncoder, const EncoderParameters * encoderParams)
Definition at line 294 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveImageToFile(
             nativeImage, filename, clsidEncoder, encoderParams));
 }
References GdipSaveImageToFile(), nativeImage, and updateStatus().
Save() [2/2]
__inline__ Status Image::Save (IStream * stream, const CLSID * clsidEncoder, const EncoderParameters * encoderParams)
Definition at line 301 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveImageToStream(
             nativeImage, stream, clsidEncoder, encoderParams));
 }
References GdipSaveImageToStream(), nativeImage, and updateStatus().
SaveAdd() [1/2]
__inline__ Status Image::SaveAdd (const EncoderParameters * encoderParams)
Definition at line 308 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveAdd(
             nativeImage, encoderParams));
 }
References GdipSaveAdd(), nativeImage, and updateStatus().
SaveAdd() [2/2]
__inline__ Status Image::SaveAdd (Image * newImage, const EncoderParameters * encoderParams)
Definition at line 314 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSaveAddImage(
             nativeImage,
             newImage ? newImage->nativeImage : NULL,
             encoderParams));
 }
References GdipSaveAddImage(), nativeImage, NULL, and updateStatus().
SelectActiveFrame()
__inline__ Status Image::SelectActiveFrame (const GUID * dimensionID, UINT frameIndex)
Definition at line 323 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipImageSelectActiveFrame(
             nativeImage, dimensionID, frameIndex));
 }
References GdipImageSelectActiveFrame(), nativeImage, and updateStatus().
SetAbort()
__inline__ Status Image::SetAbort (GdiplusAbort * pIAbort)
Definition at line 330 of file gdiplusimpl.h.
 {
     // FIXME: can't test GdipImageSetAbort because it isn't exported in 1.0
     return updateStatus(DllExports::GdipImageSetAbort(
             nativeImage, pIAbort));
 }
References GdipImageSetAbort(), nativeImage, and updateStatus().
SetPalette()
__inline__ Status Image::SetPalette (const ColorPalette * palette)
Definition at line 337 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetImagePalette(
             nativeImage, palette));
 }
References GdipSetImagePalette(), nativeImage, and updateStatus().
SetPropertyItem()
__inline__ Status Image::SetPropertyItem (const PropertyItem * item)
Definition at line 343 of file gdiplusimpl.h.
 {
     return updateStatus(DllExports::GdipSetPropertyItem(nativeImage, item));
 }
References GdipSetPropertyItem(), nativeImage, and updateStatus().
updateStatus()
Status Image::updateStatus (Status newStatus) const inline private
Definition at line 146 of file gdiplusheaders.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by Clone(), Bitmap::Clone(), Metafile::Clone(), Bitmap::ConvertFormat(), FindFirstItem(), FindNextItem(), GetAllPropertyItems(), GetBounds(), Metafile::GetDownLevelRasterizationLimit(), GetEncoderParameterList(), GetEncoderParameterListSize(), GetFlags(), GetFrameCount(), GetFrameDimensionsCount(), GetFrameDimensionsList(), Bitmap::GetHBITMAP(), GetHeight(), Metafile::GetHENHMETAFILE(), Bitmap::GetHICON(), Bitmap::GetHistogram(), Bitmap::GetHistogramSize(), GetHorizontalResolution(), GetItemData(), Metafile::GetMetafileHeader(), GetPalette(), GetPaletteSize(), GetPhysicalDimension(), Bitmap::GetPixel(), GetPixelFormat(), GetPropertyCount(), GetPropertyIdList(), GetPropertyItem(), GetPropertyItemSize(), GetPropertySize(), GetRawFormat(), GetThumbnailImage(), GetType(), GetVerticalResolution(), GetWidth(), Bitmap::LockBits(), Metafile::PlayRecord(), RemovePropertyItem(), RotateFlip(), Save(), SaveAdd(), SelectActiveFrame(), SetAbort(), Metafile::SetDownLevelRasterizationLimit(), SetPalette(), Bitmap::SetPixel(), SetPropertyItem(), Bitmap::SetResolution(), and Bitmap::UnlockBits().
Friends And Related Function Documentation
Bitmap
friend class Bitmap friend
Definition at line 53 of file gdiplusheaders.h.
Referenced by Bitmap::Clone(), Bitmap::FromBITMAPINFO(), Bitmap::FromDirectDrawSurface7(), Bitmap::FromFile(), Bitmap::FromHBITMAP(), Bitmap::FromHICON(), Bitmap::FromResource(), and Bitmap::FromStream().
CachedBitmap
friend class CachedBitmap friend
Definition at line 55 of file gdiplusheaders.h.
Graphics
friend class Graphics friend
Definition at line 56 of file gdiplusheaders.h.
Metafile
friend class Metafile friend
Definition at line 54 of file gdiplusheaders.h.
Referenced by Metafile::Clone().
TextureBrush
friend class TextureBrush friend
Definition at line 57 of file gdiplusheaders.h.
Field Documentation
lastStatus
Status Image::lastStatus mutable private
Definition at line 153 of file gdiplusheaders.h.
Referenced by Bitmap::Bitmap(), Clone(), Bitmap::Clone(), Metafile::Clone(), GetLastStatus(), GetPhysicalDimension(), GetThumbnailImage(), Image(), Metafile::Metafile(), and updateStatus().
nativeImage
GpImage* Image::nativeImage private
Definition at line 152 of file gdiplusheaders.h.
Referenced by Bitmap::Bitmap(), CachedBitmap::CachedBitmap(), Clone(), Bitmap::Clone(), Metafile::Clone(), Bitmap::ConvertFormat(), Graphics::EnumerateMetafile(), FindFirstItem(), FindNextItem(), GetAllPropertyItems(), GetBounds(), Metafile::GetDownLevelRasterizationLimit(), GetEncoderParameterList(), GetEncoderParameterListSize(), GetFlags(), GetFrameCount(), GetFrameDimensionsCount(), GetFrameDimensionsList(), Bitmap::GetHBITMAP(), GetHeight(), Metafile::GetHENHMETAFILE(), Bitmap::GetHICON(), Bitmap::GetHistogram(), GetHorizontalResolution(), GetItemData(), Metafile::GetMetafileHeader(), GetPalette(), GetPaletteSize(), GetPhysicalDimension(), Bitmap::GetPixel(), GetPixelFormat(), GetPropertyCount(), GetPropertyIdList(), GetPropertyItem(), GetPropertyItemSize(), GetPropertySize(), GetRawFormat(), GetThumbnailImage(), GetType(), GetVerticalResolution(), GetWidth(), Image(), Bitmap::InitializePalette(), Bitmap::LockBits(), Metafile::Metafile(), Metafile::PlayRecord(), RemovePropertyItem(), RotateFlip(), Save(), SaveAdd(), SelectActiveFrame(), SetAbort(), Metafile::SetDownLevelRasterizationLimit(), SetPalette(), Bitmap::SetPixel(), SetPropertyItem(), Bitmap::SetResolution(), Bitmap::UnlockBits(), and ~Image().
The documentation for this class was generated from the following files:
Tools/MinGW/include/gdiplus/gdiplusheaders.h
Tools/MinGW/include/gdiplus/gdiplusimpl.h