ZEQ2-Lite: Engine/tools/lcc/src/error.c File Reference
error.c File Reference
#include "c.h"
#include "token.h"
Macros
#define xx(a, b, c, d, e, f, g) f,
#define yy(a, b, c, d, e, f, g) f,
Functions
void error (const char *fmt,...)
void expect (int tok)
int fatal (const char *name, const char *fmt, int n)
static void printtoken (void)
void skipto (int tok, char set[])
void test (int tok, char set[])
void warning (const char *fmt,...)
Variables
int errcnt = 0
int errlimit = 20
char kind []
int wflag
Macro Definition Documentation
xx
#define xx (a, b, c, d, e, f, g) f,
yy
#define yy (a, b, c, d, e, f, g) f,
Function Documentation
error()
void error (const char * fmt, ...)
Definition at line 33 of file error.c.
{
     va_list ap;
     if (errcnt++ >= errlimit) {
         errcnt = -1;
         error("too many errors\n");
         exit(1);
     }
     va_start(ap, fmt);
     if (firstfile != file && firstfile && *firstfile)
         fprint(stderr, "%s: ", firstfile);
     fprint(stderr, "%w: ", &src);
     vfprint(stderr, NULL, fmt, ap);
     va_end(ap);
 }
References errcnt, errlimit, exit(), firstfile, fmt, fprint(), NULL, stderr, va_end, va_start, and vfprint().
Referenced by expect(), fatal(), skipto(), and warning().
expect()
void expect (int tok)
Definition at line 24 of file error.c.
                      {
     if (t == tok)
         t = gettok();
     else {
         error("syntax error; found");
         printtoken();
         fprint(stderr, " expecting `%k'\n", tok);
     }
 }
References error(), fprint(), gettok(), printtoken(), and stderr.
Referenced by call(), compound(), dcllocal(), dclr1(), dostmt(), expr1(), forstmt(), funcdefn(), ifstmt(), parameters(), statement(), stmtlabel(), swstmt(), test(), unary(), and whilestmt().
fatal()
int fatal (const char * name, const char * fmt, int n)
Definition at line 74 of file error.c.
{
     print("\n");
     errcnt = -1;
     error("compiler error in %s--", name);
     fprint(stderr, fmt, n);
     exit(EXIT_FAILURE);
     return 0;
 }
References errcnt, error(), exit(), EXIT_FAILURE, fmt, fprint(), print(), and stderr.
printtoken()
static void printtoken (void) static
Definition at line 84 of file error.c.
{
     switch (t) {
     case ID: fprint(stderr, " `%s'", token); break;
     case ICON:
         fprint(stderr, " `%s'", vtoa(tsym->type, tsym->u.c.v));
         break;
     case SCON: {
         int i, n;
         if (ischar(tsym->type->type)) {
             char *s = tsym->u.c.v.p;
             n = tsym->type->size;
             fprint(stderr, " \"");
             for (i = 0; i < 20 && i < n && *s; s++, i++)
                 if (*s < ' ' || *s >= 0177)
                     fprint(stderr, "\\%o", *s);
                 else
                     fprint(stderr, "%c", *s);
         } else {    /* wchar_t string */
             unsigned int *s = tsym->u.c.v.p;
             assert(tsym->type->type->size == widechar->size);
             n = tsym->type->size/widechar->size;
             fprint(stderr, " L\"");
             for (i = 0; i < 20 && i < n && *s; s++, i++)
                 if (*s < ' ' || *s >= 0177)
                     fprint(stderr, "\\x%x", *s);
                 else
                     fprint(stderr, "%c", *s);
         }
         if (i < n)
             fprint(stderr, " ...");
         else
             fprint(stderr, "\"");
         break;
         }
     case FCON:
         fprint(stderr, " `%S'", token, (char*)cp - token);
         break;
     case '`': case '\'': fprint(stderr, " \"%k\"", t); break;
     default: fprint(stderr, " `%k'", t);
     }
 }
References assert, cp, fprint(), ID, ischar, stderr, tsym, vtoa(), and widechar.
Referenced by expect(), and skipto().
skipto()
void skipto (int tok, char set[])
Definition at line 49 of file error.c.
{
     int n;
     char *s;
     assert(set);
     for (n = 0; t != EOI && t != tok; t = gettok()) {
         for (s = set; *s && kind[t] != *s; s++)
             ;
         if (kind[t] == *s)
             break;
         if (n++ == 0)
             error("skipping");
         if (n <= 8)
             printtoken();
         else if (n == 9)
             fprint(stderr, " ...");
     }
     if (n > 8) {
         fprint(stderr, " up to");
         printtoken();
     }
     if (n > 0)
         fprint(stderr, "\n");
 }
References assert, error(), fprint(), gettok(), kind, printtoken(), and stderr.
Referenced by initializer(), parameters(), statement(), and test().
test()
void test (int tok, char set[])
Definition at line 14 of file error.c.
{
     if (t == tok)
         t = gettok();
     else {
         expect(tok);
         skipto(tok, set);
         if (t == tok)
             t = gettok();
     }
 }
References expect(), gettok(), and skipto().
Referenced by CG_TargetCommand_f(), decl(), enumdcl(), expr(), expr1(), fields(), forstmt(), initend(), initializer(), statement(), and structdcl().
warning()
void warning (const char * fmt, ...)
Definition at line 127 of file error.c.
{
     va_list ap;
     va_start(ap, fmt);
     if (wflag == 0) {
         errcnt--;
         error("warning: ");
         vfprint(stderr, NULL, fmt, ap);
     }
     va_end(ap);
 }
References errcnt, error(), fmt, NULL, stderr, va_end, va_start, vfprint(), and wflag.
Referenced by addd(), addi(), array(), assign(), backslash(), branch(), call(), caselabel(), cast(), CG_DrawRadarBlips(), checkref(), code(), conditional(), cput(), dclglobal(), dcllocal(), dclparam(), dclr(), decl(), divd(), divi(), enumdcl(), exitscope(), expr2(), fcon(), fields(), funcdefn(), gettok(), icon(), initfields(), lvalue(), muld(), muli(), parameters(), primary(), program(), qual(), resynch(), retcode(), root1(), scon(), simplify(), specifier(), statement(), swcode(), swstmt(), typename(), typestring(), and unary().
Variable Documentation
errcnt
int errcnt = 0
Definition at line 5 of file error.c.
Referenced by error(), fatal(), and warning().
errlimit
int errlimit = 20
Definition at line 6 of file error.c.
Referenced by error(), and main_init().
kind
char kind[]
Initial value:
= {
#define xx(a,b,c,d,e,f,g)
#define yy(a,b,c,d,e,f,g)
}
Definition at line 7 of file error.c.
Referenced by code(), compound(), dclr1(), decl(), forstmt(), funcdefn(), parameters(), program(), reachable(), skipto(), and statement().
wflag
int wflag
Definition at line 12 of file error.c.
Referenced by main_init(), and warning().