ZEQ2-Lite: Source/Shared/q_math.c File Reference
q_math.c File Reference
#include "q_shared.h"
Functions
vec_t _DotProduct (const vec3_t v1, const vec3_t v2)
void _VectorAdd (const vec3_t veca, const vec3_t vecb, vec3_t out)
void _VectorCopy (const vec3_t in, vec3_t out)
void _VectorMA (const vec3_t veca, float scale, const vec3_t vecb, vec3_t vecc)
void _VectorScale (const vec3_t in, vec_t scale, vec3_t out)
void _VectorSubtract (const vec3_t veca, const vec3_t vecb, vec3_t out)
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
float AngleDelta (float angle1, float angle2)
float AngleMod (float a)
float AngleNormalize180 (float angle)
float AngleNormalize360 (float angle)
void AnglesSubtract (vec3_t v1, vec3_t v2, vec3_t v3)
void AnglesToAxis (const vec3_t angles, vec3_t axis[3])
void AnglesToQuat (const vec3_t angles, vec4_t quat)
float AngleSubtract (float a1, float a2)
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
void AxisClear (vec3_t axis[3])
void AxisCopy (vec3_t in[3], vec3_t out[3])
void AxisToAngles (vec3_t axis[3], vec3_t angles)
qboolean BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
qboolean BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
qboolean BoundsIntersectSphere (const vec3_t mins, const vec3_t maxs, const vec3_t origin, vec_t radius)
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s *p)
void ByteToDir (int b, vec3_t dir)
signed char ClampChar (int i)
signed short ClampShort (int i)
void ClearBounds (vec3_t mins, vec3_t maxs)
unsigned ColorBytes3 (float r, float g, float b)
unsigned ColorBytes4 (float r, float g, float b, float a)
float Det_2D (const vec2_t in1, const vec2_t in2)
int DirToByte (vec3_t dir)
float Distance_2D (const vec2_t in1, const vec2_t in2)
float DistancePointLine (const vec3_t point, const vec3_t line)
float DistancePointToLine (const vec3_t point, const vec3_t lineBase, const vec3_t lineDelta)
float DotProduct_2D (const vec2_t in1, const vec2_t in2)
double hack_acos (double x)
double hack_asin (double x)
float LerpAngle (float from, float to, float frac)
void MakeNormalVectors (const vec3_t forward, vec3_t right, vec3_t up)
qboolean Matrix4Compare (const float a[16], const float b[16])
void Matrix4Copy (const float in[16], float out[16])
void Matrix4Multiply (const float a[16], const float b[16], float out[16])
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
float NormalizeColor (const vec3_t in, vec3_t out)
void PerpendicularVector (vec3_t dst, const vec3_t src)
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
qboolean PointsSameSide_2D (const vec2_t lineBase, const vec2_t lineDelta, const vec2_t point1, const vec2_t point2)
void ProjectPointOnLine (const vec3_t src, const vec3_t lpt1, const vec3_t lpt2, vec3_t prjct)
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
float Q_acos (float c)
float Q_angle2D (const vec2_t in1, const vec2_t in2)
float Q_crandom (int *seed)
float Q_fabs (float f)
float Q_hypot (float a, float b)
int Q_isnan (float x)
int Q_log2 (int val)
int Q_rand (int *seed)
float Q_random (int *seed)
float Q_rsqrt (float number)
int Q_Sign (const float a)
void QuatMul (const vec4_t q1, const vec4_t q2, vec4_t res)
void QuatToAngles (const vec4_t q, vec3_t a)
void QuatToAxis (vec4_t q, vec3_t axis[3])
void QuatToVector (vec4_t q, vec3_t outVec)
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
void RotateAroundDirection (vec3_t axis[3], float yaw)
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
void SetPlaneSignbits (cplane_t *out)
void vectoangles (const vec3_t value1, vec3_t angles)
void Vector4Scale (const vec4_t in, vec_t scale, vec4_t out)
vec_t VectorNormalize (vec3_t v)
vec_t VectorNormalize2 (const vec3_t v, vec3_t out)
void VectorPieceWiseMultiply (const vec3_t in1, const vec3_t in2, vec3_t out)
void VectorPllComponent (const vec3_t A, const vec3_t B, vec3_t Pll)
void VectorRotate (vec3_t in, vec3_t matrix[3], vec3_t out)
Variables
vec3_t axisDefault [3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } }
vec3_t bytedirs [NUMVERTEXNORMALS]
vec4_t colorBlack = {0, 0, 0, 1}
vec4_t colorBlue = {0, 0, 1, 1}
vec4_t colorCyan = {0, 1, 1, 1}
vec4_t colorDkGrey = {0.25, 0.25, 0.25, 1}
vec4_t colorGreen = {0, 1, 0, 1}
vec4_t colorLtGrey = {0.75, 0.75, 0.75, 1}
vec4_t colorMagenta = {1, 0, 1, 1}
vec4_t colorMdGrey = {0.5, 0.5, 0.5, 1}
vec4_t colorRed = {1, 0, 0, 1}
vec4_t colorWhite = {1, 1, 1, 1}
vec4_t colorYellow = {1, 1, 0, 1}
vec4_t g_color_table [8]
double hack_acostable []
vec3_t vec3_origin = {0,0,0}
Function Documentation
_DotProduct()
vec_t _DotProduct (const vec3_t v1, const vec3_t v2)
Definition at line 917 of file q_math.c.
{
     return v1[0]*v2[0] + v1[1]*v2[1] + v1[2]*v2[2];
 }
_VectorAdd()
void _VectorAdd (const vec3_t veca, const vec3_t vecb, vec3_t out)
Definition at line 927 of file q_math.c.
{
     out[0] = veca[0]+vecb[0];
     out[1] = veca[1]+vecb[1];
     out[2] = veca[2]+vecb[2];
 }
References out.
_VectorCopy()
void _VectorCopy (const vec3_t in, vec3_t out)
Definition at line 933 of file q_math.c.
{
     out[0] = in[0];
     out[1] = in[1];
     out[2] = in[2];
 }
References out.
_VectorMA()
void _VectorMA (const vec3_t veca, float scale, const vec3_t vecb, vec3_t vecc)
Definition at line 910 of file q_math.c.
{
     vecc[0] = veca[0] + scale*vecb[0];
     vecc[1] = veca[1] + scale*vecb[1];
     vecc[2] = veca[2] + scale*vecb[2];
 }
_VectorScale()
void _VectorScale (const vec3_t in, vec_t scale, vec3_t out)
Definition at line 939 of file q_math.c.
{
     out[0] = in[0]*scale;
     out[1] = in[1]*scale;
     out[2] = in[2]*scale;
 }
References out.
_VectorSubtract()
void _VectorSubtract (const vec3_t veca, const vec3_t vecb, vec3_t out)
Definition at line 921 of file q_math.c.
{
     out[0] = veca[0]-vecb[0];
     out[1] = veca[1]-vecb[1];
     out[2] = veca[2]-vecb[2];
 }
References out.
AddPointToBounds()
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 798 of file q_math.c.
{
     if ( v[0] < mins[0] ) {
         mins[0] = v[0];
     }
     if ( v[0] > maxs[0]) {
         maxs[0] = v[0];
     }
     if ( v[1] < mins[1] ) {
         mins[1] = v[1];
     }
     if ( v[1] > maxs[1]) {
         maxs[1] = v[1];
     }
     if ( v[2] < mins[2] ) {
         mins[2] = v[2];
     }
     if ( v[2] > maxs[2]) {
         maxs[2] = v[2];
     }
 }
Referenced by CM_GeneratePatchCollide(), ParseTriSurf(), R_CreateSurfaceGridMesh(), R_MarkFragments(), RE_AddPolyToScene(), and Think_SpawnNewDoorTrigger().
AngleDelta()
float AngleDelta (float angle1, float angle2)
Definition at line 669 of file q_math.c.
{
     return AngleNormalize180( angle1 - angle2 );
 }
References AngleNormalize180().
AngleMod()
float AngleMod (float a)
Definition at line 628 of file q_math.c.
{
     a = (360.0/65536) * ((int)(a*(65536/360.0)) & 65535);
     return a;
 }
Referenced by CG_PlayerAngles(), CG_SwingAngles(), UI_PlayerAngles(), and UI_SwingAngles().
AngleNormalize180()
float AngleNormalize180 (float angle)
Definition at line 653 of file q_math.c.
{
     angle = AngleNormalize360( angle );
     if ( angle > 180.0 ) {
         angle -= 360.0;
     }
     return angle;
 }
References AngleNormalize360().
Referenced by AngleDelta(), BG_TouchJumpPad(), PM_UpdateViewAngles(), R_CalcBone(), and R_CalcBoneLerp().
AngleNormalize360()
float AngleNormalize360 (float angle)
Definition at line 641 of file q_math.c.
{
     return (360.0 / 65536) * ((int)(angle * (65536 / 360.0)) & 65535);
 }
References int().
Referenced by AngleNormalize180().
AnglesSubtract()
void AnglesSubtract (vec3_t v1, vec3_t v2, vec3_t v3)
Definition at line 621 of file q_math.c.
{
     v3[0] = AngleSubtract( v1[0], v2[0] );
     v3[1] = AngleSubtract( v1[1], v2[1] );
     v3[2] = AngleSubtract( v1[2], v2[2] );
 }
References AngleSubtract().
Referenced by CG_PlayerAngles(), and UI_PlayerAngles().
AnglesToAxis()
void AnglesToAxis (const vec3_t angles, vec3_t axis[3])
Definition at line 467 of file q_math.c.
{
     vec3_t  right;
     // angle vectors returns "right" instead of "y axis"
     AngleVectors( angles, axis[0], right, axis[2] );
     VectorSubtract( vec3_origin, right, axis[1] );
 }
References angles, AngleVectors(), right, vec3_origin, and VectorSubtract.
Referenced by CG_AddFragment(), CG_AddPacketEntities(), CG_AddPlayerWeapon(), CG_CalcViewValues(), CG_Camera(), CG_Draw3DModel(), CG_General(), CG_Missile(), CG_Mover(), CG_PlayerAngles(), CG_ScorePlum(), PSys_RenderSystems(), PSys_UpdateOrientation(), R_CalcBone(), R_CalcBoneLerp(), UI_MenuLogo(), UI_MenuScene(), and UI_PlayerAngles().
AnglesToQuat()
void AnglesToQuat (const vec3_t angles, vec4_t quat)
Definition at line 1233 of file q_math.c.
{
     vec3_t a;
     float cr, cp, cy, sr, sp, sy, cpcy, spsy;
     a[PITCH] = (M_PI/360.0) * angles[PITCH];
     a[YAW] = (M_PI/360.0) * angles[YAW];
     a[ROLL] = (M_PI/360.0) * angles[ROLL];
     cr = cos(a[ROLL]);
     cp = cos(a[PITCH]);
     cy = cos(a[YAW]);
     sr = sin(a[ROLL]);
     sp = sin(a[PITCH]);
     sy = sin(a[YAW]);
     cpcy = cp * cy;
     spsy = sp * sy;
     quat[0] = cr * cpcy + sr * spsy; // w
     quat[1] = sr * cpcy - cr * spsy; // x
     quat[2] = cr * sp * cy + sr * cp * sy; // y
     quat[3] = cr * cp * sy - sr * sp * cy; // z
 }
References angles, cp, cr, cy, M_PI, PITCH, ROLL, sp, sr, sy, and YAW.
Referenced by CG_Missile(), and PM_UpdateViewAngles().
AngleSubtract()
float AngleSubtract (float a1, float a2)
Definition at line 607 of file q_math.c.
{
     float   a;
     a = a1 - a2;
     while ( a > 180 ) {
         a -= 360;
     }
     while ( a < -180 ) {
         a += 360;
     }
     return a;
 }
Referenced by AnglesSubtract(), CG_SwingAngles(), and UI_SwingAngles().
AngleVectors()
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
Definition at line 1143 of file q_math.c.
{
     float       angle;
     static float        sr, sp, sy, cr, cp, cy;
     // static to help MS compiler fp bugs
     angle = angles[YAW] * (M_PI*2 / 360);
     sy = sin(angle);
     cy = cos(angle);
     angle = angles[PITCH] * (M_PI*2 / 360);
     sp = sin(angle);
     cp = cos(angle);
     angle = angles[ROLL] * (M_PI*2 / 360);
     sr = sin(angle);
     cr = cos(angle);
     if (forward)
     {
         forward[0] = cp*cy;
         forward[1] = cp*sy;
         forward[2] = -sp;
     }
     if (right)
     {
         right[0] = (-1*sr*sp*cy+-1*cr*-sy);
         right[1] = (-1*sr*sp*sy+-1*cr*cy);
         right[2] = -1*sr*cp;
     }
     if (up)
     {
         up[0] = (cr*sp*cy+-sr*-sy);
         up[1] = (cr*sp*sy+-sr*cy);
         up[2] = cr*cp;
     }
 }
References angles, cp, cr, cy, forward, M_PI, PITCH, right, ROLL, sp, sr, sy, up, and YAW.
Referenced by AnglesToAxis(), CG_Camera(), CG_DamageFeedback(), CG_DrawCrosshair(), CG_ScanForCrosshairEntity(), CG_WorldCoordToScreenCoordFloat(), CM_TransformedPointContents(), CreateRotationMatrix(), FireWeapon(), G_CreateRotationMatrix(), G_PushUserMissile(), G_RunUserMissile(), G_SetMovedir(), G_TryPushingProxMine(), PM_UpdateViewAngles(), PM_VerifyTrace(), PmoveSingle(), PodiumPlacementThink(), SpawnModelOnVictoryPad(), SpawnPodium(), SV_GameSystemCalls(), TeleportPlayer(), Think_Guided(), Think_NormalMissileBurnPlayer(), Think_NormalMissileRidePlayer(), Think_NormalMissileStrugglePlayer(), and UI_MovedirAdjustment().
AxisClear()
void AxisClear (vec3_t axis[3])
Definition at line 475 of file q_math.c.
{
     axis[0][0] = 1;
     axis[0][1] = 0;
     axis[0][2] = 0;
     axis[1][0] = 0;
     axis[1][1] = 1;
     axis[1][2] = 0;
     axis[2][0] = 0;
     axis[2][1] = 0;
     axis[2][2] = 1;
 }
Referenced by CG_AddPlayerWeapon(), CG_Beam(), CG_BigLightningEffect(), CG_DirtPush(), CG_Draw3DModel(), CG_GetTagOrientationFromPlayerEntityCameraModel(), CG_GetTagOrientationFromPlayerEntityHeadModel(), CG_GetTagOrientationFromPlayerEntityLegsModel(), CG_GetTagOrientationFromPlayerEntityTorsoModel(), CG_LightningEffect(), CG_MakeExplosion(), CG_MakeUserExplosion(), CG_PowerMeleeEffect(), CG_PowerStruggleEffect(), CG_SpawnEffect(), CG_SpeedMeleeEffect(), CG_TrailFunc_SpiralBeam(), CG_WaterRipple(), CG_WaterSplash(), PSys_RenderSystems(), PSys_SpawnCachedSystem(), R_IQMLerpTag(), R_LerpTag(), UI_DrawPlayer(), UI_MenuLogo(), and UI_MenuScene().
AxisCopy()
void AxisCopy (vec3_t in[3], vec3_t out[3])
Definition at line 487 of file q_math.c.
{
     VectorCopy( in[0], out[0] );
     VectorCopy( in[1], out[1] );
     VectorCopy( in[2], out[2] );
 }
References out, and VectorCopy.
Referenced by CG_AddPlayerWeapon(), CG_LaunchExplode(), PSys_SpawnCachedSystem(), PSys_UpdateEmitters(), and R_GetPortalOrientations().
AxisToAngles()
void AxisToAngles (vec3_t axis[3], vec3_t angles)
Definition at line 418 of file q_math.c.
{
     float length1;
     float yaw, pitch, roll = 0.0f;
     if ( axis[0][1] == 0 && axis[0][0] == 0 ) {
         yaw = 0;
         if ( axis[0][2] > 0 ) {
             pitch = 90;
         }
         else {
             pitch = 270;
         }
     }
     else {
         if ( axis[0][0] ) {
             yaw = ( atan2 ( axis[0][1], axis[0][0] ) * 180 / M_PI );
         }
         else if ( axis[0][1] > 0 ) {
             yaw = 90;
         }
         else {
             yaw = 270;
         }
         if ( yaw < 0 ) {
             yaw += 360;
         }
         length1 = sqrt ( axis[0][0]*axis[0][0] + axis[0][1]*axis[0][1] );
         pitch = ( atan2(axis[0][2], length1) * 180 / M_PI );
         if ( pitch < 0 ) {
             pitch += 360;
         }
         roll = ( atan2( axis[1][2], axis[2][2] ) * 180 / M_PI );
         if ( roll < 0 ) {
             roll += 360;
         }
     }
     angles[PITCH] = -pitch;
     angles[YAW] = yaw;
     angles[ROLL] = roll;
 }
References angles, M_PI, PITCH, ROLL, and YAW.
BoundsIntersect()
qboolean BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
Definition at line 821 of file q_math.c.
 {
     if ( maxs[0] < mins2[0] ||
         maxs[1] < mins2[1] ||
         maxs[2] < mins2[2] ||
         mins[0] > maxs2[0] ||
         mins[1] > maxs2[1] ||
         mins[2] > maxs2[2])
     {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoundsIntersectPoint()
qboolean BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
Definition at line 853 of file q_math.c.
 {
     if ( origin[0] > maxs[0] ||
         origin[0] < mins[0] ||
         origin[1] > maxs[1] ||
         origin[1] < mins[1] ||
         origin[2] > maxs[2] ||
         origin[2] < mins[2])
     {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoundsIntersectSphere()
qboolean BoundsIntersectSphere (const vec3_t mins, const vec3_t maxs, const vec3_t origin, vec_t radius)
Definition at line 837 of file q_math.c.
 {
     if ( origin[0] - radius > maxs[0] ||
         origin[0] + radius < mins[0] ||
         origin[1] - radius > maxs[1] ||
         origin[1] + radius < mins[1] ||
         origin[2] - radius > maxs[2] ||
         origin[2] + radius < mins[2])
     {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoxOnPlaneSide()
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s * p)
Definition at line 736 of file q_math.c.
 {
     float   dist[2];
     int     sides, b, i;
     // fast axial cases
     if (p->type < 3)
     {
         if (p->dist <= emins[p->type])
             return 1;
         if (p->dist >= emaxs[p->type])
             return 2;
         return 3;
     }
     // general case
     dist[0] = dist[1] = 0;
     if (p->signbits < 8) // >= 8: default case is original code (dist[0]=dist[1]=0)
     {
         for (i=0 ; i<3 ; i++)
         {
             b = (p->signbits >> i) & 1;
             dist[ b] += p->normal[i]*emaxs[i];
             dist[!b] += p->normal[i]*emins[i];
         }
     }
     sides = 0;
     if (dist[0] >= p->dist)
         sides = 1;
     if (dist[1] < p->dist)
         sides |= 2;
     return sides;
 }
Referenced by CM_BoxLeafnums_r(), R_BoxSurfaces_r(), and R_RecursiveWorldNode().
ByteToDir()
void ByteToDir (int b, vec3_t dir)
Definition at line 210 of file q_math.c.
{
     if ( b < 0 || b >= NUMVERTEXNORMALS ) {
         VectorCopy( vec3_origin, dir );
         return;
     }
     VectorCopy (bytedirs[b], dir);
 }
References bytedirs, dir, NUMVERTEXNORMALS, vec3_origin, and VectorCopy.
Referenced by CG_EntityEvent(), and CG_Portal().
ClampChar()
signed char ClampChar (int i)
Definition at line 165 of file q_math.c.
{
     if ( i < -128 ) {
         return -128;
     }
     if ( i > 127 ) {
         return 127;
     }
     return i;
 }
Referenced by CL_JoystickMove(), CL_KeyMove(), and CL_MouseMove().
ClampShort()
signed short ClampShort (int i)
Definition at line 175 of file q_math.c.
{
     if ( i < -32768 ) {
         return -32768;
     }
     if ( i > 0x7fff ) {
         return 0x7fff;
     }
     return i;
 }
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 793 of file q_math.c.
{
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
Referenced by CM_GeneratePatchCollide(), ParseTriSurf(), R_AddWorldSurfaces(), R_CreateSurfaceGridMesh(), and R_MarkFragments().
ColorBytes3()
unsigned ColorBytes3 (float r, float g, float b)
Definition at line 219 of file q_math.c.
{
     unsigned    i;
     ( (byte *)&i )[0] = r * 255;
     ( (byte *)&i )[1] = g * 255;
     ( (byte *)&i )[2] = b * 255;
     return i;
 }
ColorBytes4()
unsigned ColorBytes4 (float r, float g, float b, float a)
Definition at line 229 of file q_math.c.
{
     unsigned    i;
     ( (byte *)&i )[0] = r * 255;
     ( (byte *)&i )[1] = g * 255;
     ( (byte *)&i )[2] = b * 255;
     ( (byte *)&i )[3] = a * 255;
     return i;
 }
Referenced by R_LoadFogs(), and RB_HazePass().
Det_2D()
float Det_2D (const vec2_t in1, const vec2_t in2)
Definition at line 1494 of file q_math.c.
{
     return in1[0]*in2[1] - in1[1]*in2[0];
 }
Referenced by PointsSameSide_2D().
DirToByte()
int DirToByte (vec3_t dir)
Definition at line 187 of file q_math.c.
{
     int     i, best;
     float   d, bestd;
     if ( !dir ) {
         return 0;
     }
     bestd = 0;
     best = 0;
     for (i=0 ; i<NUMVERTEXNORMALS ; i++)
     {
         d = DotProduct (dir, bytedirs[i]);
         if (d > bestd)
         {
             bestd = d;
             best = i;
         }
     }
     return best;
 }
References bytedirs, dir, DotProduct, and NUMVERTEXNORMALS.
Referenced by G_ExplodeUserWeapon(), G_ImpactUserWeapon(), locateCamera(), and UserHitscan_Fire().
Distance_2D()
float Distance_2D (const vec2_t in1, const vec2_t in2)
Definition at line 1550 of file q_math.c.
{
     float temp1, temp2;
     temp1 = in1[0] - in2[0];
     temp1 *= temp1;
     temp2 = in1[1] - in2[1];
     temp2 *= temp2;
     return Q_fabs( sqrt( temp1 + temp2 ) );
 }
References Q_fabs().
DistancePointLine()
float DistancePointLine (const vec3_t point, const vec3_t line)
Definition at line 1483 of file q_math.c.
{
     vec3_t cross, neg_point;
     float dist;
     VectorScale(point, -1, neg_point);
     CrossProduct(line, neg_point, cross);
     dist = VectorLength(cross) / VectorLength(line);
     return dist;
 }
References CrossProduct(), line, VectorLength(), and VectorScale.
DistancePointToLine()
float DistancePointToLine (const vec3_t point, const vec3_t lineBase, const vec3_t lineDelta)
Definition at line 1582 of file q_math.c.
{
     vec3_t pointDelta, Pll, Perp;
     VectorSubtract( point, lineBase, pointDelta );
     VectorPllComponent( pointDelta, lineDelta, Pll );
     VectorSubtract( pointDelta, Pll, Perp );
     return VectorLength( Perp );
 }
References VectorLength(), VectorPllComponent(), and VectorSubtract.
Referenced by PSys_ApplyFalloff().
DotProduct_2D()
float DotProduct_2D (const vec2_t in1, const vec2_t in2)
Definition at line 1498 of file q_math.c.
{
     return in1[0]*in2[0] + in1[1]*in2[1];
 }
Referenced by Q_angle2D().
hack_acos()
double hack_acos (double x)
Definition at line 1455 of file q_math.c.
{
     int index;
     if (x < -1)
         x = -1;
     if (x > 1)
         x = 1;
     index = (float) (1.0 + x) * 511.9;
     return hack_acostable[index];
 }
References hack_acostable.
Referenced by hack_asin(), and Q_angle2D().
hack_asin()
double hack_asin (double x)
Definition at line 1467 of file q_math.c.
 {
     return (hack_acos(x) - 0.5 * M_PI);
 }
References hack_acos(), and M_PI.
Referenced by QuatToAngles().
LerpAngle()
float LerpAngle (float from, float to, float frac)
Definition at line 585 of file q_math.c.
{
     float   a;
     if ( to - from > 180 ) {
         to -= 360;
     }
     if ( to - from < -180 ) {
         to += 360;
     }
     a = from + frac * (to - from);
     return a;
 }
Referenced by CG_InterpolateEntityPosition(), and CG_InterpolatePlayerState().
MakeNormalVectors()
void MakeNormalVectors (const vec3_t forward, vec3_t right, vec3_t up)
Definition at line 524 of file q_math.c.
{
     float       d;
     // this rotate and negate guarantees a vector
     // not colinear with the original
     right[1] = -forward[0];
     right[2] = forward[1];
     right[0] = forward[2];
     d = DotProduct (right, forward);
     VectorMA (right, -d, forward, right);
     VectorNormalize (right);
     CrossProduct (right, forward, up);
 }
References CrossProduct(), DotProduct, forward, right, up, VectorMA(), and VectorNormalize().
Referenced by BG_EvaluateTrajectory(), CG_AuraStart(), CG_MakeUserExplosion(), CG_UserMissileHitWall(), PSys_UpdateEmitters(), PSys_UpdateOrientation(), and RB_SurfaceRailRings().
Matrix4Compare()
qboolean Matrix4Compare (const float a[16], const float b[16])
Definition at line 988 of file q_math.c.
 {
     int i;
     for ( i = 0; i < 16; i++ )
         if ( a[i] != b[i] )
             return qfalse;
     return qtrue;
 }
References qfalse, and qtrue.
Referenced by R_GLSL_SetUniform_ModelViewMatrix(), R_GLSL_SetUniform_ModelViewProjectionMatrix(), and R_GLSL_SetUniform_ProjectionMatrix().
Matrix4Copy()
void Matrix4Copy (const float in[16], float out[16])
Definition at line 1004 of file q_math.c.
 {
 #if id386_sse && defined __GNUC__ && 0
     asm volatile
     (
     "movups         (%%edx),        %%xmm0\n"
     "movups         0x10(%%edx),    %%xmm1\n"
     "movups         0x20(%%edx),    %%xmm2\n"
     "movups         0x30(%%edx),    %%xmm3\n"
     "movups         %%xmm0,         (%%eax)\n"
     "movups         %%xmm1,         0x10(%%eax)\n"
     "movups         %%xmm2,         0x20(%%eax)\n"
     "movups         %%xmm3,         0x30(%%eax)\n"
     :
     : "a"( out ), "d"( in )
     : "memory"
         );
 #elif id386_3dnow && defined __GNUC__
     asm volatile
     (
     "femms\n"
     "movq           (%%edx),        %%mm0\n"
     "movq           8(%%edx),       %%mm1\n"
     "movq           16(%%edx),      %%mm2\n"
     "movq           24(%%edx),      %%mm3\n"
     "movq           32(%%edx),      %%mm4\n"
     "movq           40(%%edx),      %%mm5\n"
     "movq           48(%%edx),      %%mm6\n"
     "movq           56(%%edx),      %%mm7\n"
     "movq           %%mm0,          (%%eax)\n"
     "movq           %%mm1,          8(%%eax)\n"
     "movq           %%mm2,          16(%%eax)\n"
     "movq           %%mm3,          24(%%eax)\n"
     "movq           %%mm4,          32(%%eax)\n"
     "movq           %%mm5,          40(%%eax)\n"
     "movq           %%mm6,          48(%%eax)\n"
     "movq           %%mm7,          56(%%eax)\n"
     "femms\n"
     :
     : "a"(out), "d"(in)
     : "memory"
     );
 #else
         out[ 0] = in[ 0];       out[ 4] = in[ 4];       out[ 8] = in[ 8];       out[12] = in[12];
         out[ 1] = in[ 1];       out[ 5] = in[ 5];       out[ 9] = in[ 9];       out[13] = in[13];
         out[ 2] = in[ 2];       out[ 6] = in[ 6];       out[10] = in[10];       out[14] = in[14];
         out[ 3] = in[ 3];       out[ 7] = in[ 7];       out[11] = in[11];       out[15] = in[15];
 #endif
 }
References out.
Referenced by R_GLSL_SetUniform_ModelViewMatrix(), R_GLSL_SetUniform_ModelViewProjectionMatrix(), R_GLSL_SetUniform_ProjectionMatrix(), RB_BeginDrawingView(), RB_RenderDrawSurfList(), and SetViewportAndScissor().
Matrix4Multiply()
void Matrix4Multiply (const float a[16], const float b[16], float out[16])
Definition at line 1061 of file q_math.c.
 {
 #if id386_sse
     int             i;
     __m128          _t0, _t1, _t2, _t3, _t4, _t5, _t6, _t7;
     _t4 = _mm_loadu_ps(&a[0]);
     _t5 = _mm_loadu_ps(&a[4]);
     _t6 = _mm_loadu_ps(&a[8]);
     _t7 = _mm_loadu_ps(&a[12]);
     for(i = 0; i < 4; i++)
     {
         _t0 = _mm_load1_ps(&b[i * 4 + 0]);
         _t0 = _mm_mul_ps(_t4, _t0);
         _t1 = _mm_load1_ps(&b[i * 4 + 1]);
         _t1 = _mm_mul_ps(_t5, _t1);
         _t2 = _mm_load1_ps(&b[i * 4 + 2]);
         _t2 = _mm_mul_ps(_t6, _t2);
         _t3 = _mm_load1_ps(&b[i * 4 + 3]);
         _t3 = _mm_mul_ps(_t7, _t3);
         _t1 = _mm_add_ps(_t0, _t1);
         _t2 = _mm_add_ps(_t1, _t2);
         _t3 = _mm_add_ps(_t2, _t3);
         _mm_storeu_ps(&out[i * 4], _t3);
     }
 #else
         out[ 0] = b[ 0]*a[ 0] + b[ 1]*a[ 4] + b[ 2]*a[ 8] + b[ 3]*a[12];
         out[ 1] = b[ 0]*a[ 1] + b[ 1]*a[ 5] + b[ 2]*a[ 9] + b[ 3]*a[13];
         out[ 2] = b[ 0]*a[ 2] + b[ 1]*a[ 6] + b[ 2]*a[10] + b[ 3]*a[14];
         out[ 3] = b[ 0]*a[ 3] + b[ 1]*a[ 7] + b[ 2]*a[11] + b[ 3]*a[15];
         out[ 4] = b[ 4]*a[ 0] + b[ 5]*a[ 4] + b[ 6]*a[ 8] + b[ 7]*a[12];
         out[ 5] = b[ 4]*a[ 1] + b[ 5]*a[ 5] + b[ 6]*a[ 9] + b[ 7]*a[13];
         out[ 6] = b[ 4]*a[ 2] + b[ 5]*a[ 6] + b[ 6]*a[10] + b[ 7]*a[14];
         out[ 7] = b[ 4]*a[ 3] + b[ 5]*a[ 7] + b[ 6]*a[11] + b[ 7]*a[15];
         out[ 8] = b[ 8]*a[ 0] + b[ 9]*a[ 4] + b[10]*a[ 8] + b[11]*a[12];
         out[ 9] = b[ 8]*a[ 1] + b[ 9]*a[ 5] + b[10]*a[ 9] + b[11]*a[13];
         out[10] = b[ 8]*a[ 2] + b[ 9]*a[ 6] + b[10]*a[10] + b[11]*a[14];
         out[11] = b[ 8]*a[ 3] + b[ 9]*a[ 7] + b[10]*a[11] + b[11]*a[15];
         out[12] = b[12]*a[ 0] + b[13]*a[ 4] + b[14]*a[ 8] + b[15]*a[12];
         out[13] = b[12]*a[ 1] + b[13]*a[ 5] + b[14]*a[ 9] + b[15]*a[13];
         out[14] = b[12]*a[ 2] + b[13]*a[ 6] + b[14]*a[10] + b[15]*a[14];
         out[15] = b[12]*a[ 3] + b[13]*a[ 7] + b[14]*a[11] + b[15]*a[15];
 #endif
 }
References out.
Referenced by RB_BeginDrawingView(), RB_DrawSun(), RB_RenderDrawSurfList(), RB_SetGL2D(), RB_ShadowFinish(), and SetViewportAndScissor().
MatrixMultiply()
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
Definition at line 1121 of file q_math.c.
{
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] +
                 in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] +
                 in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] +
                 in1[0][2] * in2[2][2];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] +
                 in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] +
                 in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] +
                 in1[1][2] * in2[2][2];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] +
                 in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] +
                 in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] +
                 in1[2][2] * in2[2][2];
 }
References out.
Referenced by CG_AddPlayerWeapon(), CG_GetTagOrientation(), CG_GetTagOrientationFromPlayerEntityCameraModel(), CG_GetTagOrientationFromPlayerEntityHeadModel(), CG_GetTagOrientationFromPlayerEntityLegsModel(), CG_GetTagOrientationFromPlayerEntityTorsoModel(), CG_PositionEntityOnTag(), CG_PositionRotatedEntityOnTag(), RotatePointAroundVector(), SV_GameSystemCalls(), UI_PositionEntityOnTag(), and UI_PositionRotatedEntityOnTag().
NormalizeColor()
float NormalizeColor (const vec3_t in, vec3_t out)
Definition at line 240 of file q_math.c.
{
     float   max;
     max = in[0];
     if ( in[1] > max ) {
         max = in[1];
     }
     if ( in[2] > max ) {
         max = in[2];
     }
     if ( !max ) {
         VectorClear( out );
     } else {
         out[0] = in[0] / max;
         out[1] = in[1] / max;
         out[2] = in[2] / max;
     }
     return max;
 }
References out, and VectorClear.
Referenced by RB_CalcDynamicColor(), and RB_CalcUniformColor().
PerpendicularVector()
void PerpendicularVector (vec3_t dst, const vec3_t src)
Definition at line 1181 of file q_math.c.
 {
     int pos;
     int i;
     float minelem = 1.0F;
     vec3_t tempvec;
     /*
     ** find the smallest magnitude axially aligned vector
     */
     for ( pos = 0, i = 0; i < 3; i++ )
     {
         if ( fabs( src[i] ) < minelem )
         {
             pos = i;
             minelem = fabs( src[i] );
         }
     }
     tempvec[0] = tempvec[1] = tempvec[2] = 0.0F;
     tempvec[pos] = 1.0F;
     /*
     ** project the point onto the plane defined by src
     */
     ProjectPointOnPlane( dst, tempvec, src );
     /*
     ** normalize the result
     */
     VectorNormalize( dst );
 }
References ProjectPointOnPlane(), and VectorNormalize().
Referenced by CG_ImpactMark(), CG_Portal(), R_GetPortalOrientations(), RB_DrawSun(), RB_SurfaceBeam(), RotateAroundDirection(), RotatePointAroundVector(), and SV_GameSystemCalls().
PlaneFromPoints()
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
Definition at line 270 of file q_math.c.
{
     vec3_t  d1, d2;
     VectorSubtract( b, a, d1 );
     VectorSubtract( c, a, d2 );
     CrossProduct( d2, d1, plane );
     if ( VectorNormalize( plane ) == 0 ) {
         return qfalse;
     }
     plane[3] = DotProduct( a, plane );
     return qtrue;
 }
References CrossProduct(), DotProduct, qfalse, qtrue, VectorNormalize(), and VectorSubtract.
Referenced by R_PlaneForSurface().
PointsSameSide_2D()
qboolean PointsSameSide_2D (const vec2_t lineBase, const vec2_t lineDelta, const vec2_t point1, const vec2_t point2)
Definition at line 1502 of file q_math.c.
{
     float det1, det2;
     vec2_t point1Delta, point2Delta;
     point1Delta[0] = point1[0] - lineBase[0];
     point1Delta[1] = point1[1] - lineBase[1];
     point2Delta[0] = point2[0] - lineBase[0];
     point2Delta[1] = point2[1] - lineBase[1];
     det1 = Det_2D( lineDelta, point1Delta );
     det2 = Det_2D( lineDelta, point2Delta );
     if ( (det1 < 0) && (det2 < 0) ) {
         return qtrue;
     }
     if ( (det1 > 0) && (det2 > 0) ) {
         return qtrue;
     }
     if ( (det1 == 0) || (det2 == 0) ) {
         return qtrue;
     }
     return qfalse;
 }
References Det_2D(), qfalse, and qtrue.
ProjectPointOnLine()
void ProjectPointOnLine (const vec3_t src, const vec3_t lpt1, const vec3_t lpt2, vec3_t prjct)
Definition at line 1572 of file q_math.c.
{
     vec3_t lpt1_src, lpt1_lpt2;
     VectorSubtract( lpt2, lpt1, lpt1_lpt2 );
     VectorSubtract( src,  lpt1, lpt1_src  );
     VectorPllComponent( lpt1_src, lpt1_lpt2, prjct );
     VectorAdd( prjct, lpt1, prjct );
 }
References VectorAdd, VectorPllComponent(), and VectorSubtract.
Referenced by CG_Aura_MarkRootPoint().
ProjectPointOnPlane()
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
Definition at line 493 of file q_math.c.
 {
     float d;
     vec3_t n;
     float inv_denom;
     inv_denom =  DotProduct( normal, normal );
 #ifndef Q3_VM
     assert( Q_fabs(inv_denom) != 0.0f ); // zero vectors get here
 #endif
     inv_denom = 1.0f / inv_denom;
     d = DotProduct( normal, p ) * inv_denom;
     n[0] = normal[0] * inv_denom;
     n[1] = normal[1] * inv_denom;
     n[2] = normal[2] * inv_denom;
     dst[0] = p[0] - d * n[0];
     dst[1] = p[1] - d * n[1];
     dst[2] = p[2] - d * n[2];
 }
References DotProduct, and Q_fabs().
Referenced by PerpendicularVector().
Q_acos()
float Q_acos (float c)
Definition at line 1624 of file q_math.c.
                       {
     float angle;
     angle = acos(c);
     if (angle > M_PI) {
         return (float)M_PI;
     }
     if (angle < -M_PI) {
         return (float)M_PI;
     }
     return angle;
 }
References M_PI.
Referenced by CL_CgameSystemCalls(), and R_InitSkyTexCoords().
Q_angle2D()
float Q_angle2D (const vec2_t in1, const vec2_t in2)
Definition at line 1529 of file q_math.c.
{
     vec3_t  temp1, temp2;
     vec2_t  out1, out2;
     // Do it this way to make use of the vec3_t normalize function
     temp1[0] = in1[0];
     temp1[1] = in1[1];
     temp2[0] = in2[0];
     temp2[1] = in2[1];
     temp1[2] = temp2[2] = 0;
     VectorNormalize( temp1 );
     VectorNormalize( temp2 );
     out1[0] = temp1[0];
     out1[1] = temp1[1];
     out2[0] = temp2[0];
     out2[1] = temp2[1];
     return (hack_acos( DotProduct_2D( out1, out2 ) ));
 }
References DotProduct_2D(), hack_acos(), and VectorNormalize().
Q_crandom()
float Q_crandom (int * seed)
Definition at line 159 of file q_math.c.
{
     return 2.0 * ( Q_random( seed ) - 0.5 );
 }
References Q_random().
Q_fabs()
float Q_fabs (float f)
Definition at line 569 of file q_math.c.
{
     floatint_t fi;
     fi.f = f;
     fi.i &= 0x7FFFFFFF;
     return fi.f;
 }
References floatint_t::f, and floatint_t::i.
Referenced by Distance_2D(), ProjectDlightTexture_scalar(), ProjectPointOnPlane(), ProjectRadius(), R_CalcBone(), R_CalcBoneLerp(), and UI_MovedirAdjustment().
Q_hypot()
float Q_hypot (float a, float b)
Definition at line 1562 of file q_math.c.
{
   return sqrt(a*a + b*b);
 }
Referenced by CG_Aura_ArrangeConvexHull().
Q_isnan()
int Q_isnan (float x)
Definition at line 1220 of file q_math.c.
 {
     floatint_t fi;
     fi.f = x;
     fi.ui &= 0x7FFFFFFF;
     fi.ui = 0x7F800000 - fi.ui;
     return (int)( (unsigned int)fi.ui >> 31 );
 }
References floatint_t::f, int(), and floatint_t::ui.
Referenced by RE_AddRefEntityToScene().
Q_log2()
int Q_log2 (int val)
Definition at line 953 of file q_math.c.
                       {
     int answer;
     answer = 0;
     while ( ( val>>=1 ) != 0 ) {
         answer++;
     }
     return answer;
 }
References val.
Q_rand()
int Q_rand (int * seed)
Definition at line 150 of file q_math.c.
{
     *seed = (69069 * *seed + 1);
     return *seed;
 }
Referenced by Q_random().
Q_random()
float Q_random (int * seed)
Definition at line 155 of file q_math.c.
{
     return ( Q_rand( seed ) & 0xffff ) / (float)0x10000;
 }
References Q_rand().
Referenced by CG_SmokePuff(), CG_WaterBubble(), PM_CheckBlink(), PM_CheckJump(), PM_Melee(), and Q_crandom().
Q_rsqrt()
float Q_rsqrt (float number)
Definition at line 553 of file q_math.c.
 {
     floatint_t t;
     float x2, y;
     const float threehalfs = 1.5F;
     x2 = number * 0.5F;
     t.f  = number;
     t.i  = 0x5f3759df - ( t.i >> 1 );               // what the fuck?
     y  = t.f;
     y  = y * ( threehalfs - ( x2 * y * y ) );   // 1st iteration
 //  y  = y * ( threehalfs - ( x2 * y * y ) );   // 2nd iteration, this can be removed
     return y;
 }
Referenced by RB_CalcSpecularAlpha(), and VectorNormalizeFast().
Q_Sign()
int Q_Sign (const float a)
Definition at line 1597 of file q_math.c.
{
     if ( a > 0 )
         return 1;
     if ( a < 0 )
         return -1;
     return 0;
 }
QuatMul()
void QuatMul (const vec4_t q1, const vec4_t q2, vec4_t res)
Definition at line 1305 of file q_math.c.
{
     float A, B, C, D, E, F, G, H;
     A = (q1[0] + q1[1])*(q2[0] + q2[1]);
     B = (q1[3] - q1[2])*(q2[2] - q2[3]);
     C = (q1[0] - q1[1])*(q2[2] + q2[3]);
     D = (q1[2] + q1[3])*(q2[0] - q2[1]);
     E = (q1[1] + q1[3])*(q2[1] + q2[2]);
     F = (q1[1] - q1[3])*(q2[1] - q2[2]);
     G = (q1[0] + q1[2])*(q2[0] - q2[3]);
     H = (q1[0] - q1[2])*(q2[0] + q2[3]);
     res[0] = B + (H - E - F + G)*0.5;
     res[1] = A - (E + F + G + H)*0.5;
     res[2] = C + (E - F + G - H)*0.5;
     res[3] = D + (E - F - G + H)*0.5;
 }
References A, B, C, D, F, G, and H.
Referenced by CG_Missile(), and PM_UpdateViewAngles().
QuatToAngles()
void QuatToAngles (const vec4_t q, vec3_t a)
Definition at line 1472 of file q_math.c.
{
     vec4_t q2;
     q2[0] = q[0]*q[0];
     q2[1] = q[1]*q[1];
     q2[2] = q[2]*q[2];
     q2[3] = q[3]*q[3];
     a[ROLL] = (180.0/M_PI)*atan2 (2*(q[2]*q[3] + q[1]*q[0]) , (-q2[1] - q2[2] + q2[3] + q2[0]));
     a[PITCH] = -1 * (180.0/M_PI)* hack_asin( -2*(q[1]*q[3] - q[2]*q[0]) );
     a[YAW] = (180.0/M_PI)*atan2 (2*(q[1]*q[2] + q[3]*q[0]) , (q2[1] - q2[2] - q2[3] + q2[0]));
 }
References hack_asin(), M_PI, PITCH, ROLL, and YAW.
Referenced by PM_UpdateViewAngles().
QuatToAxis()
void QuatToAxis (vec4_t q, vec3_t axis[3])
Definition at line 1257 of file q_math.c.
{
     float wx, wy, wz, xx, yy, yz, xy, xz, zz, x2, y2, z2;
     x2 = q[1] + q[1];
     y2 = q[2] + q[2];
     z2 = q[3] + q[3];
     xx = q[1] * x2;
     xy = q[1] * y2;
     xz = q[1] * z2;
     yy = q[2] * y2;
     yz = q[2] * z2;
     zz = q[3] * z2;
     wx = q[0] * x2;
     wy = q[0] * y2;
     wz = q[0] * z2;
     axis[0][0] = 1.0 - (yy + zz);
     axis[1][0] = xy - wz;
     axis[2][0] = xz + wy;
     axis[0][1] = xy + wz;
     axis[1][1] = 1.0 - (xx + zz);
     axis[2][1] = yz - wx;
     axis[0][2] = xz - wy;
     axis[1][2] = yz + wx;
     axis[2][2] = 1.0 - (xx + yy);
 }
References xx, and yy.
Referenced by CG_Missile().
QuatToVector()
void QuatToVector (vec4_t q, vec3_t outVec)
Definition at line 1288 of file q_math.c.
{
     float wy, wz, yy, xy, xz, zz, y2, z2;
     y2 = q[2] + q[2];
     z2 = q[3] + q[3];
     xy = q[1] * y2;
     xz = q[1] * z2;
     yy = q[2] * y2;
     zz = q[3] * z2;
     wy = q[0] * y2;
     wz = q[0] * z2;
     outVec[0] = 1.0 - (yy + zz);
     outVec[1] = xy + wz;
     outVec[2] = xz - wy;
 }
References yy.
RadiusFromBounds()
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
Definition at line 778 of file q_math.c.
{
     int     i;
     vec3_t  corner;
     float   a, b;
     for (i=0 ; i<3 ; i++) {
         a = fabs( mins[i] );
         b = fabs( maxs[i] );
         corner[i] = a > b ? a : b;
     }
     return VectorLength (corner);
 }
References VectorLength().
Referenced by G_MoverPush(), R_ComputeLOD(), and SV_LinkEntity().
RotateAroundDirection()
void RotateAroundDirection (vec3_t axis[3], float yaw)
Definition at line 352 of file q_math.c.
{
     // create an arbitrary axis[1]
     PerpendicularVector( axis[1], axis[0] );
     // rotate it around axis[0] by yaw
     if ( yaw ) {
         vec3_t  temp;
         VectorCopy( axis[1], temp );
         RotatePointAroundVector( axis[1], axis[0], temp, yaw );
     }
     // cross to get axis[2]
     CrossProduct( axis[0], axis[1], axis[2] );
 }
References CrossProduct(), PerpendicularVector(), RotatePointAroundVector(), and VectorCopy.
Referenced by BG_EvaluateTrajectory(), CG_MakeExplosion(), CG_MakeUserExplosion(), CG_Missile(), CG_TrailFunc_SpiralBeam_Helper(), CG_WaterSplash(), and PSys_UpdateEmitters().
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 291 of file q_math.c.
{
     float   m[3][3];
     float   im[3][3];
     float   zrot[3][3];
     float   tmpmat[3][3];
     float   rot[3][3];
     int i;
     vec3_t vr, vup, vf;
     float   rad;
     vf[0] = dir[0];
     vf[1] = dir[1];
     vf[2] = dir[2];
     PerpendicularVector( vr, dir );
     CrossProduct( vr, vf, vup );
     m[0][0] = vr[0];
     m[1][0] = vr[1];
     m[2][0] = vr[2];
     m[0][1] = vup[0];
     m[1][1] = vup[1];
     m[2][1] = vup[2];
     m[0][2] = vf[0];
     m[1][2] = vf[1];
     m[2][2] = vf[2];
     memcpy( im, m, sizeof( im ) );
     im[0][1] = m[1][0];
     im[0][2] = m[2][0];
     im[1][0] = m[0][1];
     im[1][2] = m[2][1];
     im[2][0] = m[0][2];
     im[2][1] = m[1][2];
     memset( zrot, 0, sizeof( zrot ) );
     zrot[0][0] = zrot[1][1] = zrot[2][2] = 1.0F;
     rad = DEG2RAD( degrees );
     zrot[0][0] = cos( rad );
     zrot[0][1] = sin( rad );
     zrot[1][0] = -sin( rad );
     zrot[1][1] = cos( rad );
     MatrixMultiply( m, zrot, tmpmat );
     MatrixMultiply( tmpmat, im, rot );
     for ( i = 0; i < 3; i++ ) {
         dst[i] = rot[i][0] * point[0] + rot[i][1] * point[1] + rot[i][2] * point[2];
     }
 }
References CrossProduct(), DEG2RAD, dir, m, MatrixMultiply(), and PerpendicularVector().
Referenced by CG_DrawRadarBlips(), CG_ImpactMark(), Fire_UserWeapon(), R_GetPortalOrientations(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), and RotateAroundDirection().
SetPlaneSignbits()
void SetPlaneSignbits (cplane_t * out)
Definition at line 682 of file q_math.c.
{
     int bits, j;
     // for fast box on planeside test
     bits = 0;
     for (j=0 ; j<3 ; j++) {
         if (out->normal[j] < 0) {
             bits |= 1<<j;
         }
     }
     out->signbits = bits;
 }
References bits(), and out.
Referenced by CM_InitBoxHull(), ParseFace(), and R_SetupFrustum().
vectoangles()
void vectoangles (const vec3_t value1, vec3_t angles)
Definition at line 371 of file q_math.c.
{
     float   forward;
     float   yaw, pitch;
     if ( value1[1] == 0 && value1[0] == 0 ) {
         yaw = 0;
         if ( value1[2] > 0 ) {
             pitch = 90;
         }
         else {
             pitch = 270;
         }
     }
     else {
         if ( value1[0] ) {
             yaw = ( atan2 ( value1[1], value1[0] ) * 180 / M_PI );
         }
         else if ( value1[1] > 0 ) {
             yaw = 90;
         }
         else {
             yaw = 270;
         }
         if ( yaw < 0 ) {
             yaw += 360;
         }
         forward = sqrt ( value1[0]*value1[0] + value1[1]*value1[1] );
         pitch = ( atan2(value1[2], forward) * 180 / M_PI );
         if ( pitch < 0 ) {
             pitch += 360;
         }
     }
     angles[PITCH] = -pitch;
     angles[YAW] = yaw;
     angles[ROLL] = 0;
 }
References angles, forward, M_PI, PITCH, ROLL, and YAW.
Referenced by BG_TouchJumpPad(), CG_Camera(), CG_Missile(), FindIntermissionPoint(), Fire_UserWeapon(), G_LocationImpact(), G_PushUserMissile(), P_DamageFeedback(), PM_UpdateViewAngles(), PodiumPlacementThink(), SpawnModelOnVictoryPad(), and Think_Guided().
Vector4Scale()
void Vector4Scale (const vec4_t in, vec_t scale, vec4_t out)
Definition at line 945 of file q_math.c.
{
     out[0] = in[0]*scale;
     out[1] = in[1]*scale;
     out[2] = in[2]*scale;
     out[3] = in[3]*scale;
 }
References out.
VectorNormalize()
vec_t VectorNormalize (vec3_t v)
Definition at line 869 of file q_math.c.
{
     // NOTE: TTimo - Apple G4 altivec source uses double?
     float   length, ilength;
     length = v[0]*v[0] + v[1]*v[1] + v[2]*v[2];
     if ( length ) {
         /* writing it this way allows gcc to recognize that rsqrt can be used */
         ilength = 1/(float)sqrt (length);
         /* sqrt(length) = length * (1 / sqrt(length)) */
         length *= ilength;
         v[0] *= ilength;
         v[1] *= ilength;
         v[2] *= ilength;
     }
     return length;
 }
Referenced by MakeNormalVectors(), PerpendicularVector(), PlaneFromPoints(), and Q_angle2D().
VectorNormalize2()
vec_t VectorNormalize2 (const vec3_t v, vec3_t out)
Definition at line 888 of file q_math.c.
{
     float   length, ilength;
     length = v[0]*v[0] + v[1]*v[1] + v[2]*v[2];
     if (length)
     {
         /* writing it this way allows gcc to recognize that rsqrt can be used */
         ilength = 1/(float)sqrt (length);
         /* sqrt(length) = length * (1 / sqrt(length)) */
         length *= ilength;
         out[0] = v[0]*ilength;
         out[1] = v[1]*ilength;
         out[2] = v[2]*ilength;
     } else {
         VectorClear( out );
     }
     return length;
 }
References out, and VectorClear.
Referenced by AddWindingToConvexHull(), BaseWindingForPlane(), BG_EvaluateTrajectory(), CG_Aura_BuildTailPoint(), CG_AuraStart(), CG_ImpactMark(), CG_Missile(), CG_TrailFunc_SpiralBeam_Helper(), CG_UserMissileHitWall(), CheckWinding(), MakeMeshNormals(), PM_CheckJump(), PM_CheckKnockback(), PM_CheckZanzoken(), PM_GroundTrace(), PM_SlideMove(), PM_UpdateViewAngles(), PSys_UpdateOrientation(), R_MarkFragments(), R_SetupEntityLightingGrid(), RemoveColinearPoints(), and WindingPlane().
VectorPieceWiseMultiply()
void VectorPieceWiseMultiply (const vec3_t in1, const vec3_t in2, vec3_t out)
Definition at line 1591 of file q_math.c.
{
     out[0] = in1[0] * in2[0];
     out[1] = in1[1] * in2[1];
     out[2] = in1[2] * in2[2];
 }
References out.
Referenced by CG_AddPlayerWeapon(), and CG_Missile().
VectorPllComponent()
void VectorPllComponent (const vec3_t A, const vec3_t B, vec3_t Pll)
Definition at line 1566 of file q_math.c.
{
     Pll[0] = DotProduct(A, B) * B[0] / ( B[0] * B[0] + B[1] * B[1] + B[2] * B[2] );
     Pll[1] = DotProduct(A, B) * B[1] / ( B[0] * B[0] + B[1] * B[1] + B[2] * B[2] );
     Pll[2] = DotProduct(A, B) * B[2] / ( B[0] * B[0] + B[1] * B[1] + B[2] * B[2] );
 }
References A, B, and DotProduct.
Referenced by CG_LerpSpike(), DistancePointToLine(), and ProjectPointOnLine().
VectorRotate()
void VectorRotate (vec3_t in, vec3_t matrix[3], vec3_t out)
Definition at line 540 of file q_math.c.
 {
     out[0] = DotProduct( in, matrix[0] );
     out[1] = DotProduct( in, matrix[1] );
     out[2] = DotProduct( in, matrix[2] );
 }
References DotProduct, and out.
Referenced by S_SpatializeOrigin().
Variable Documentation
axisDefault
vec3_t axisDefault[3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } }
Definition at line 35 of file q_math.c.
Referenced by CG_LaunchExplode().
bytedirs
vec3_t bytedirs[NUMVERTEXNORMALS]
Definition at line 63 of file q_math.c.
Referenced by ByteToDir(), and DirToByte().
colorBlack
vec4_t colorBlack = {0, 0, 0, 1}
Definition at line 38 of file q_math.c.
Referenced by StartServer_LevelshotDraw(), UI_DrawBackPic(), and UI_DrawTextBox().
colorBlue
vec4_t colorBlue = {0, 0, 1, 1}
Definition at line 41 of file q_math.c.
colorCyan
vec4_t colorCyan = {0, 1, 1, 1}
Definition at line 44 of file q_math.c.
colorDkGrey
vec4_t colorDkGrey = {0.25, 0.25, 0.25, 1}
Definition at line 48 of file q_math.c.
colorGreen
vec4_t colorGreen = {0, 1, 0, 1}
Definition at line 40 of file q_math.c.
colorLtGrey
vec4_t colorLtGrey = {0.75, 0.75, 0.75, 1}
Definition at line 46 of file q_math.c.
colorMagenta
vec4_t colorMagenta = {1, 0, 1, 1}
Definition at line 43 of file q_math.c.
colorMdGrey
vec4_t colorMdGrey = {0.5, 0.5, 0.5, 1}
Definition at line 47 of file q_math.c.
Referenced by Bitmap_Draw().
colorRed
vec4_t colorRed = {1, 0, 0, 1}
Definition at line 39 of file q_math.c.
Referenced by PlayerModel_MenuInit(), and UI_Refresh().
colorWhite
vec4_t colorWhite = {1, 1, 1, 1}
Definition at line 45 of file q_math.c.
Referenced by CG_DrawWarmup(), Menu_Draw(), RE_SetColor(), TeamMain_MenuInit(), and UI_DrawTextBox().
colorYellow
vec4_t colorYellow = {1, 1, 0, 1}
Definition at line 42 of file q_math.c.
Referenced by Menu_Draw().
g_color_table
vec4_t g_color_table[8]
Initial value:
=
    {
    {0.0, 0.0, 0.0, 1.0},
    {1.0, 0.0, 0.0, 1.0},
    {0.0, 1.0, 0.0, 1.0},
    {1.0, 1.0, 0.0, 1.0},
    {0.0, 0.0, 1.0, 1.0},
    {0.0, 1.0, 1.0, 1.0},
    {1.0, 0.0, 1.0, 1.0},
    {1.0, 1.0, 1.0, 1.0},
    }
Definition at line 50 of file q_math.c.
Referenced by CG_DrawStringExt(), Con_DrawNotify(), Con_DrawSolidConsole(), MainMenu_DrawName(), SCR_DrawCustomString(), SCR_DrawDebugGraph(), SCR_DrawDemoRecording(), SCR_DrawScreenField(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), and UI_DrawString2().
hack_acostable
double hack_acostable[]
Definition at line 1324 of file q_math.c.
Referenced by hack_acos().
vec3_origin
vec3_t vec3_origin = {0,0,0}
Definition at line 34 of file q_math.c.
Referenced by AddSkyPolygon(), AnglesToAxis(), AutospriteDeform(), BaseWindingForPlane(), ByteToDir(), CanDamage(), CG_AddPlayerWeapon(), CG_Aura_AddSounds(), CG_ClipMoveToEntities(), CG_DamageFeedback(), CG_EntityEffects(), CG_EntityEvent(), CG_Player(), CG_Portal(), CM_AddFacetBevels(), CM_BoxTrace(), CM_DrawDebugSurface(), CM_Trace(), CM_TransformedBoxTrace(), CM_ValidateFacet(), FindIntermissionPoint(), G_TryPushingProxMine(), InitTrigger(), MainMenu_DrawPlayer(), PM_NoclipMove(), R_GetPortalOrientations(), R_LoadFogs(), R_MirrorViewBySurface(), RB_AddQuadStampExt(), RB_SurfaceSprite(), SelectCTFSpawnPoint(), SelectInitialSpawnPoint(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_EntityContact(), SV_PointContents(), SV_Trace(), and WindingCenter().