ZEQ2-Lite: Engine/tools/lcc/src/gen.c File Reference
gen.c File Reference
#include "c.h"
Macros
#define ck(i) return (i) ? 0 : LBURG_MAX
#define readsreg(p) (generic((p)->op)==INDIR && (p)->kids[0]->op==VREG+P)
#define relink(a, b) ((b)->x.prev = (a), (a)->x.next = (b))
#define setsrc(d)
Functions
static Symbol askfixedreg (Symbol)
static Symbol askreg (Symbol rs, unsigned rmask[])
static Symbol askreg (Symbol, unsigned *)
int askregvar (Symbol p, Symbol regs)
void blkcopy (int dreg, int doff, int sreg, int soff, int size, int tmp[])
static void blkunroll (int, int, int, int, int, int, int[])
void blockbeg (Env *e)
void blockend (Env *e)
static void docall (Node)
static void dumpcover (Node, int, int)
static void dumpregs (char *, char *, char *)
static void dumprule (int)
static void dumptree (Node)
void emit (Node p)
static unsigned emitasm (Node, int)
Node gen (Node forest)
static void genreload (Node, Symbol, int)
static void genspill (Symbol, Node, Symbol)
static Symbol getreg (Symbol s, unsigned mask[], Node p)
static Symbol getreg (Symbol, unsigned *, Node)
int getregnum (Node p)
static int getrule (Node, int)
static void linearize (Node, Node)
int mayrecalc (Node p)
int mkactual (int align, int size)
void mkauto (Symbol p)
Symbol mkreg (char *fmt, int n, int mask, int set)
Symbol mkwildcard (Symbol *syms)
int move (Node p)
static int moveself (Node)
int notarget (Node p)
void parseflags (int argc, char *argv[])
static void prelabel (Node)
static Node * prune (Node p, Node pp[])
static Node * prune (Node, Node *)
static void putreg (Symbol)
static void ralloc (Node)
int range (Node p, int lo, int hi)
static void reduce (Node, int)
unsigned regloc (Symbol p)
static int reprune (Node *, int, int, Node)
static int requate (Node)
static Node reuse (Node, int)
static void rewrite (Node)
void rtarget (Node p, int n, Symbol r)
void setreg (Node p, Symbol r)
void spill (unsigned mask, int n, Node here)
static Symbol spillee (Symbol, unsigned mask[], Node)
static void spillr (Symbol, Node)
static int uses (Node, Regnode)
Variables
int argoffset
int bflag = 0
int dalign
int dflag = 0
unsigned(* emitter)(Node, int) = emitasm
int framesize
unsigned freemask [2]
Node head
int maxargoffset
int maxoffset
static char NeedsReg []
int offset
int salign
int swap
unsigned tmask [2]
unsigned usedmask [2]
unsigned vmask [2]
Macro Definition Documentation
ck
#define ck (i) return (i) ? 0 : LBURG_MAX
Definition at line 251 of file gen.c.
readsreg
#define readsreg (p) (generic((p)->op)==INDIR && (p)->kids[0]->op==VREG+P)
Definition at line 4 of file gen.c.
relink
#define relink (a, b) ((b)->x.prev = (a), (a)->x.next = (b))
Definition at line 10 of file gen.c.
setsrc
#define setsrc (d)
Value:
    ((d) && (d)->x.regnode && \
    (d)->x.regnode->set == src->x.regnode->set && \
    (d)->x.regnode->mask&src->x.regnode->mask)
Definition at line 6 of file gen.c.
Function Documentation
askfixedreg()
static Symbol askfixedreg (Symbol s) static
Definition at line 533 of file gen.c.
{
     Regnode r = s->x.regnode;
     int n = r->set;
     if (r->mask&~freemask[n])
         return NULL;
     else {
         freemask[n] &= ~r->mask;
         usedmask[n] |=  r->mask;
         return s;
     }
 }
References freemask, NULL, Regnode::set, and usedmask.
Referenced by askreg().
askreg() [1/2]
static Symbol askreg (Symbol rs, unsigned rmask[]) static
Definition at line 545 of file gen.c.
{
     int i;
     if (rs->x.wildcard == NULL)
         return askfixedreg(rs);
     for (i = 31; i >= 0; i--) {
         Symbol r = rs->x.wildcard[i];
         if (r != NULL
         && !(r->x.regnode->mask&~rmask[r->x.regnode->set])
         && askfixedreg(r))
             return r;
     }
     return NULL;
 }
References askfixedreg(), and NULL.
askreg() [2/2]
static Symbol askreg (Symbol , unsigned *) static
Referenced by askregvar(), and getreg().
askregvar()
int askregvar (Symbol p, Symbol regs)
Definition at line 572 of file gen.c.
{
     Symbol r;
     assert(p);
     if (p->sclass != REGISTER)
         return 0;
     else if (!isscalar(p->type)) {
         p->sclass = AUTO;
         return 0;
     }
     else if (p->temporary) {
         p->x.name = "?";
         return 1;
     }
     else if ((r = askreg(regs, vmask)) != NULL) {
         p->x.regnode = r->x.regnode;
         p->x.regnode->vbl = p;
         p->x.name = r->x.name;
         debug(dumpregs("(allocating %s to symbol %s)\n", p->x.name, p->name));
         return 1;
     }
     else {
         p->sclass = AUTO;
         return 0;
     }
 }
References askreg(), debug, dumpregs(), isscalar, NULL, and vmask.
blkcopy()
void blkcopy (int dreg, int doff, int sreg, int soff, int size, int tmp[])
Definition at line 129 of file gen.c.
{
     assert(size >= 0);
     if (size == 0)
         return;
     else if (size <= 2)
         blkunroll(size, dreg, doff, sreg, soff, size, tmp);
     else if (size == 3) {
         blkunroll(2, dreg, doff,   sreg, soff,   2, tmp);
         blkunroll(1, dreg, doff+2, sreg, soff+2, 1, tmp);
     }
     else if (size <= 16) {
         blkunroll(4, dreg, doff, sreg, soff, size&~3, tmp);
         blkcopy(dreg, doff+(size&~3),
                     sreg, soff+(size&~3), size&3, tmp);
     }
     else
         (*IR->x.blkloop)(dreg, doff, sreg, soff, size, tmp);
 }
References blkunroll(), and IR.
blkunroll()
static void blkunroll (int k, int dreg, int doff, int sreg, int soff, int size, int tmp[]) static
Definition at line 147 of file gen.c.
{
     int i;
     assert(IR->x.max_unaligned_load);
     if (k > IR->x.max_unaligned_load
     && (k > salign || k > dalign))
         k = IR->x.max_unaligned_load;
     for (i = 0; i+k < size; i += 2*k) {
         (*IR->x.blkfetch)(k, soff+i,   sreg, tmp[0]);
         (*IR->x.blkfetch)(k, soff+i+k, sreg, tmp[1]);
         (*IR->x.blkstore)(k, doff+i,   dreg, tmp[0]);
         (*IR->x.blkstore)(k, doff+i+k, dreg, tmp[1]);
     }
     if (i < size) {
         (*IR->x.blkfetch)(k, i+soff, sreg, tmp[0]);
         (*IR->x.blkstore)(k, i+doff, dreg, tmp[0]);
     }
 }
References dalign, IR, and salign.
Referenced by blkcopy().
blockbeg()
void blockbeg (Env * e)
Definition at line 104 of file gen.c.
                       {
     e->offset = offset;
     e->freemask[IREG] = freemask[IREG];
     e->freemask[FREG] = freemask[FREG];
 }
References freemask, Env::freemask, FREG, IREG, offset, and Env::offset.
blockend()
void blockend (Env * e)
Definition at line 109 of file gen.c.
                       {
     if (offset > maxoffset)
         maxoffset = offset;
     offset = e->offset;
     freemask[IREG] = e->freemask[IREG];
     freemask[FREG] = e->freemask[FREG];
 }
References freemask, Env::freemask, FREG, IREG, maxoffset, offset, and Env::offset.
docall()
static void docall (Node p) static
Definition at line 122 of file gen.c.
{
     p->syms[1] = p->syms[0];
     p->syms[0] = intconst(argoffset);
     if (argoffset > maxargoffset)
         maxargoffset = argoffset;
     argoffset = 0;
 }
References argoffset, intconst(), and maxargoffset.
Referenced by gen().
dumpcover()
static void dumpcover (Node p, int nt, int in) static
Definition at line 307 of file gen.c.
{
     int rulenum, i;
     short *nts;
     Node kids[10];
     p = reuse(p, nt);
     rulenum = getrule(p, nt);
     nts = IR->x._nts[rulenum];
     fprint(stderr, "dumpcover(%x) = ", p);
     for (i = 0; i < in; i++)
         fprint(stderr, " ");
     dumprule(rulenum);
     (*IR->x._kids)(p, rulenum, kids);
     for (i = 0; nts[i]; i++)
         dumpcover(kids[i], nts[i], in+1);
 }
References dumprule(), fprint(), getrule(), IR, nts, and reuse().
Referenced by rewrite().
dumpregs()
static void dumpregs (char * msg, char * a, char * b) static
Definition at line 814 of file gen.c.
{
     fprint(stderr, msg, a, b);
     fprint(stderr, "(free[0]=%x)\n", freemask[0]);
     fprint(stderr, "(free[1]=%x)\n", freemask[1]);
 }
References fprint(), and freemask.
Referenced by askregvar(), putreg(), and ralloc().
dumprule()
static void dumprule (int rulenum) static
Definition at line 324 of file gen.c.
{
     assert(rulenum);
     fprint(stderr, "%s / %s", IR->x._string[rulenum],
         IR->x._templates[rulenum]);
     if (!IR->x._isinstruction[rulenum])
         fprint(stderr, "\n");
 }
References fprint(), and IR.
Referenced by dumpcover().
dumptree()
static void dumptree (Node p) static
Definition at line 265 of file gen.c.
{
     if (p->op == VREG+P && p->syms[0]) {
         fprint(stderr, "VREGP(%s)", p->syms[0]->name);
         return;
     } else if (generic(p->op) == LOAD) {
         fprint(stderr, "LOAD(");
         dumptree(p->kids[0]);
         fprint(stderr, ")");
         return;
     }
     fprint(stderr, "%s(", opname(p->op));
     switch (generic(p->op)) {
     case CNST: case LABEL:
     case ADDRG: case ADDRF: case ADDRL:
         if (p->syms[0])
             fprint(stderr, "%s", p->syms[0]->name);
         break;
     case RET:
         if (p->kids[0])
             dumptree(p->kids[0]);
         break;
     case CVF: case CVI: case CVP: case CVU: case JUMP:
     case ARG: case BCOM: case NEG: case INDIR:
         dumptree(p->kids[0]);
         break;
     case CALL:
         if (optype(p->op) != B) {
             dumptree(p->kids[0]);
             break;
         }
         /* else fall thru */
     case EQ: case NE: case GT: case GE: case LE: case LT:
     case ASGN: case BOR: case BAND: case BXOR: case RSH: case LSH:
     case ADD: case SUB:  case DIV: case MUL: case MOD:
         dumptree(p->kids[0]);
         fprint(stderr, ", ");
         dumptree(p->kids[1]);
         break;
     default: assert(0);
     }
     fprint(stderr, ")");
 }
References ADD, ASGN, B, CALL, DIV, EQ, fprint(), GT, LOAD, LSH, LT, MOD, opname(), optype, P, RSH, SUB, and VREG.
Referenced by genreload(), genspill(), and rewrite().
emit()
void emit (Node p)
Definition at line 368 of file gen.c.
                   {
     for (; p; p = p->x.next) {
         assert(p->x.registered);
         if ((p->x.equatable && requate(p)) || moveself(p))
             ;
         else
             (*emitter)(p, p->x.inst);
         p->x.emitted = 1;
     }
 }
References emitter, moveself(), and requate().
emitasm()
static unsigned emitasm (Node p, int nt) static
Definition at line 331 of file gen.c.
{
     int rulenum;
     short *nts;
     char *fmt;
     Node kids[10];
     p = reuse(p, nt);
     rulenum = getrule(p, nt);
     nts = IR->x._nts[rulenum];
     fmt = IR->x._templates[rulenum];
     assert(fmt);
     if (IR->x._isinstruction[rulenum] && p->x.emitted)
         print("%s", p->syms[RX]->x.name);
     else if (*fmt == '#')
         (*IR->x.emit2)(p);
     else {
         if (*fmt == '?') {
             fmt++;
             assert(p->kids[0]);
             if (p->syms[RX] == p->x.kids[0]->syms[RX])
                 while (*fmt++ != '\n')
                     ;
         }
         for ((*IR->x._kids)(p, rulenum, kids); *fmt; fmt++)
             if (*fmt != '%')
                 (void)putchar(*fmt);
             else if (*++fmt == 'F')
                 print("%d", framesize);
             else if (*fmt >= '0' && *fmt <= '9')
                 emitasm(kids[*fmt - '0'], nts[*fmt - '0']);
             else if (*fmt >= 'a' && *fmt < 'a' + NELEMS(p->syms))
                 fputs(p->syms[*fmt - 'a']->x.name, stdout);
             else
                 (void)putchar(*fmt);
     }
     return 0;
 }
References fmt, framesize, getrule(), IR, NELEMS, nts, print(), reuse(), RX, and void().
gen()
Node gen (Node forest)
Definition at line 479 of file gen.c.
                       {
     int i;
     struct node sentinel;
     Node dummy, p;
     head = forest;
     for (p = forest; p; p = p->link) {
         assert(p->count == 0);
         if (generic(p->op) == CALL)
             docall(p);
         else if (   generic(p->op) == ASGN
         && generic(p->kids[1]->op) == CALL)
             docall(p->kids[1]);
         else if (generic(p->op) == ARG)
             (*IR->x.doarg)(p);
         rewrite(p);
         p->x.listed = 1;
     }
     for (p = forest; p; p = p->link)
         prune(p, &dummy);
     relink(&sentinel, &sentinel);
     for (p = forest; p; p = p->link)
         linearize(p, &sentinel);
     forest = sentinel.x.next;
     assert(forest);
     sentinel.x.next->x.prev = NULL;
     sentinel.x.prev->x.next = NULL;
     for (p = forest; p; p = p->x.next)
         for (i = 0; i < NELEMS(p->x.kids) && p->x.kids[i]; i++) {
             assert(p->x.kids[i]->syms[RX]);
             if (p->x.kids[i]->syms[RX]->temporary) {
                 p->x.kids[i]->x.prevuse =
                     p->x.kids[i]->syms[RX]->x.lastuse;
                 p->x.kids[i]->syms[RX]->x.lastuse = p->x.kids[i];
             }
         }
     for (p = forest; p; p = p->x.next) {
         ralloc(p);
         if (p->x.listed && NeedsReg[opindex(p->op)]
         && (*IR->x.rmap)(opkind(p->op))) {
             assert(generic(p->op) == CALL || generic(p->op) == LOAD);
             putreg(p->syms[RX]);
         }
     }
     return forest;
 }
References ASGN, CALL, docall(), forest, head, IR, linearize(), LOAD, NeedsReg, NELEMS, Xnode::next, NULL, opindex, opkind, Xnode::prev, prune(), putreg(), ralloc(), relink, rewrite(), RX, and Node::x.
genreload()
static void genreload (Node p, Symbol tmp, int i) static
Definition at line 755 of file gen.c.
{
     Node q;
     int ty;
     debug(fprint(stderr, "(replacing %x with a reload from %s)\n", p->x.kids[i], tmp->x.name));
     debug(fprint(stderr, "(genreload: "));
     debug(dumptree(p->x.kids[i]));
     debug(fprint(stderr, ")\n"));
     ty = opkind(p->x.kids[i]->op);
     q = newnode(ADDRL+P + sizeop(IR->ptrmetric.size), NULL, NULL, tmp);
     p->x.kids[i] = newnode(INDIR + ty, q, NULL, NULL);
     rewrite(p->x.kids[i]);
     prune(p->x.kids[i], &q);
     reprune(&p->kids[1], reprune(&p->kids[0], 0, i, p), i, p);
     prune(p, &q);
     linearize(p->x.kids[i], p);
 }
References debug, dumptree(), fprint(), IR, linearize(), newnode(), NULL, opkind, P, prune(), reprune(), rewrite(), and sizeop.
Referenced by spillr().
genspill()
static void genspill (Symbol r, Node last, Symbol tmp) static
Definition at line 726 of file gen.c.
{
     Node p, q;
     Symbol s;
     unsigned ty;
     debug(fprint(stderr, "(spilling %s to local %s)\n", r->x.name, tmp->x.name));
     debug(fprint(stderr, "(genspill: "));
     debug(dumptree(last));
     debug(fprint(stderr, ")\n"));
     ty = opkind(last->op);
     NEW0(s, FUNC);
     s->sclass = REGISTER;
     s->name = s->x.name = r->x.name;
     s->x.regnode = r->x.regnode;
     q = newnode(ADDRL+P + sizeop(IR->ptrmetric.size), NULL, NULL, s);
     q = newnode(INDIR + ty, q, NULL, NULL);
     p = newnode(ADDRL+P + sizeop(IR->ptrmetric.size), NULL, NULL, tmp);
     p = newnode(ASGN + ty, p, q, NULL);
     p->x.spills = 1;
     rewrite(p);
     prune(p, &q);
     q = last->x.next;
     linearize(p, q);
     for (p = last->x.next; p != q; p = p->x.next) {
         ralloc(p);
         assert(!p->x.listed || !NeedsReg[opindex(p->op)] || !(*IR->x.rmap)(opkind(p->op)));
     }
 }
References ASGN, debug, dumptree(), fprint(), FUNC, IR, linearize(), NeedsReg, NEW0, newnode(), NULL, opindex, opkind, P, prune(), ralloc(), rewrite(), and sizeop.
Referenced by spillr().
getreg() [1/2]
static Symbol getreg (Symbol s, unsigned mask[], Node p) static
Definition at line 560 of file gen.c.
{
     Symbol r = askreg(s, mask);
     if (r == NULL) {
         r = spillee(s, mask, p);
         assert(r && r->x.regnode);
         spill(r->x.regnode->mask, r->x.regnode->set, p);
         r = askreg(s, mask);
     }
     assert(r && r->x.regnode);
     r->x.regnode->vbl = NULL;
     return r;
 }
References askreg(), NULL, spill(), and spillee().
getreg() [2/2]
static Symbol getreg (Symbol , unsigned * , Node) static
Referenced by ralloc().
getregnum()
int getregnum (Node p)
Definition at line 820 of file gen.c.
                       {
     assert(p && p->syms[RX] && p->syms[RX]->x.regnode);
     return p->syms[RX]->x.regnode->number;
 }
References RX.
getrule()
static int getrule (Node p, int nt) static
Definition at line 174 of file gen.c.
{
     int rulenum;
     assert(p);
     rulenum = (*IR->x._rule)(p->x.state, nt);
     if (!rulenum) {
         fprint(stderr, "(%x->op=%s at %w is corrupt.)\n", p, opname(p->op), &src);
         assert(0);
     }
     return rulenum;
 }
References fprint(), IR, entry::nt, and opname().
Referenced by dumpcover(), emitasm(), ralloc(), and reduce().
linearize()
static void linearize (Node p, Node next) static
Definition at line 598 of file gen.c.
{
     int i;
     for (i = 0; i < NELEMS(p->x.kids) && p->x.kids[i]; i++)
         linearize(p->x.kids[i], next);
     relink(next->x.prev, p);
     relink(p, next);
     debug(fprint(stderr, "(listing %x)\n", p));
 }
References debug, fprint(), NELEMS, and relink.
Referenced by gen(), genreload(), and genspill().
mayrecalc()
int mayrecalc (Node p)
Definition at line 219 of file gen.c.
                       {
     int op;
     assert(p && p->syms[RX]);
     if (p->syms[RX]->u.t.cse == NULL)
         return 0;
     op = generic(p->syms[RX]->u.t.cse->op);
     if (op == CNST || op == ADDRF || op == ADDRG || op == ADDRL) {
         p->x.mayrecalc = 1;
         return 1;
     } else
         return 0;
 }
References NULL, op, and RX.
mkactual()
int mkactual (int align, int size)
Definition at line 116 of file gen.c.
{
     int n = roundup(argoffset, align);
     argoffset = n + size;
     return n;
 }
References argoffset, and roundup.
mkauto()
void mkauto (Symbol p)
Definition at line 98 of file gen.c.
                       {
     assert(p->sclass == AUTO);
     offset = roundup(offset + p->type->size, p->type->align);
     p->x.offset = -offset;
     p->x.name = stringd(-offset);
 }
References offset, roundup, and stringd().
mkreg()
Symbol mkreg (char * fmt, int n, int mask, int set)
Definition at line 79 of file gen.c.
{
     Symbol p;
     NEW0(p, PERM);
     p->name = p->x.name = stringf(fmt, n);
     NEW0(p->x.regnode, PERM);
     p->x.regnode->number = n;
     p->x.regnode->mask = mask<<n;
     p->x.regnode->set = set;
     return p;
 }
References fmt, NEW0, PERM, and stringf().
mkwildcard()
Symbol mkwildcard (Symbol * syms)
Definition at line 90 of file gen.c.
{
     Symbol p;
     NEW0(p, PERM);
     p->name = p->x.name = "wildcard";
     p->x.wildcard = syms;
     return p;
 }
References NEW0, and PERM.
move()
int move (Node p)
Definition at line 382 of file gen.c.
                  {
     p->x.copy = 1;
     return 1;
 }
Referenced by CG_BubbleTrail(), CG_SwingAngles(), G_MoverPush(), G_MoverTeam(), G_TryPushingEntity(), G_TryPushingProxMine(), InitMover(), Reached_Train(), and UI_SwingAngles().
moveself()
static int moveself (Node p) static
Definition at line 378 of file gen.c.
{
     return p->x.copy
     && p->syms[RX]->x.name == p->x.kids[0]->syms[RX]->x.name;
 }
References RX.
Referenced by emit(), and requate().
notarget()
int notarget (Node p)
Definition at line 525 of file gen.c.
                      {
     return p->syms[RX]->x.wildcard ? 0 : LBURG_MAX;
 }
References LBURG_MAX, and RX.
parseflags()
void parseflags (int argc, char * argv[])
Definition at line 165 of file gen.c.
{
     int i;
     for (i = 0; i < argc; i++)
         if (strcmp(argv[i], "-d") == 0)
             dflag = 1;
         else if (strcmp(argv[i], "-b") == 0)    /* omit */
             bflag = 1;          /* omit */
 }
References bflag, and dflag.
prelabel()
static void prelabel (Node p) static
Definition at line 421 of file gen.c.
{
     if (p == NULL)
         return;
     prelabel(p->kids[0]);
     prelabel(p->kids[1]);
     if (NeedsReg[opindex(p->op)])
         setreg(p, (*IR->x.rmap)(opkind(p->op)));
     switch (generic(p->op)) {
     case ADDRF: case ADDRL:
         if (p->syms[0]->sclass == REGISTER)
             p->op = VREG+P;
         break;
     case INDIR:
         if (p->kids[0]->op == VREG+P)
             setreg(p, p->kids[0]->syms[0]);
         break;
     case ASGN:
         if (p->kids[0]->op == VREG+P)
             rtarget(p, 1, p->kids[0]->syms[0]);
         break;
     case CVI: case CVU: case CVP:
         if (optype(p->op) != F
         &&  opsize(p->op) <= p->syms[0]->u.c.v.i)
             p->op = LOAD + opkind(p->op);
         break;
     }
     (IR->x.target)(p);
 }
References ASGN, F, IR, LOAD, NeedsReg, NULL, opindex, opkind, opsize, optype, P, rtarget(), setreg(), and VREG.
Referenced by rewrite().
prune() [1/2]
static Node* prune (Node p, Node pp[]) static
Definition at line 232 of file gen.c.
{
     if (p == NULL)
         return pp;
     p->x.kids[0] = p->x.kids[1] = p->x.kids[2] = NULL;
     if (p->x.inst == 0)
         return prune(p->kids[1], prune(p->kids[0], pp));
     else if (p->syms[RX] && p->syms[RX]->temporary
     && p->syms[RX]->x.usecount < 2) {
         p->x.inst = 0;
         debug(fprint(stderr, "(clobbering %s)\n", p->syms[RX]->name));
         return prune(p->kids[1], prune(p->kids[0], pp));
     }
     else {
         prune(p->kids[1], prune(p->kids[0], &p->x.kids[0]));
         *pp = p;
         return pp + 1;
     }
 }
References debug, fprint(), NULL, prune(), and RX.
prune() [2/2]
static Node* prune (Node , Node *) static
Referenced by gen(), genreload(), genspill(), and prune().
putreg()
static void putreg (Symbol r) static
Definition at line 528 of file gen.c.
{
     assert(r && r->x.regnode);
     freemask[r->x.regnode->set] |= r->x.regnode->mask;
     debug(dumpregs("(freeing %s)\n", r->x.name, NULL));
 }
References debug, dumpregs(), freemask, and NULL.
Referenced by gen(), ralloc(), and spillr().
ralloc()
static void ralloc (Node p) static
Definition at line 607 of file gen.c.
{
     int i;
     unsigned mask[2];
     mask[0] = tmask[0];
     mask[1] = tmask[1];
     assert(p);
     debug(fprint(stderr, "(rallocing %x)\n", p));
     for (i = 0; i < NELEMS(p->x.kids) && p->x.kids[i]; i++) {
         Node kid = p->x.kids[i];
         Symbol r = kid->syms[RX];
         assert(r && kid->x.registered);
         if (r->sclass != REGISTER && r->x.lastuse == kid)
             putreg(r);
     }
     if (!p->x.registered && NeedsReg[opindex(p->op)]
     && (*IR->x.rmap)(opkind(p->op))) {
         Symbol sym = p->syms[RX], set = sym;
         assert(sym);
         if (sym->temporary)
             set = (*IR->x.rmap)(opkind(p->op));
         assert(set);
         if (set->sclass != REGISTER) {
             Symbol r;
             if (*IR->x._templates[getrule(p, p->x.inst)] == '?')
                 for (i = 1; i < NELEMS(p->x.kids) && p->x.kids[i]; i++) {
                     Symbol r = p->x.kids[i]->syms[RX];
                     assert(p->x.kids[i]->x.registered);
                     assert(r && r->x.regnode);
                     assert(sym->x.wildcard || sym != r);
                     mask[r->x.regnode->set] &= ~r->x.regnode->mask;
                 }
             r = getreg(set, mask, p);
             if (sym->temporary) {
                 Node q;
                 r->x.lastuse = sym->x.lastuse;
                 for (q = sym->x.lastuse; q; q = q->x.prevuse) {
                     q->syms[RX] = r;
                     q->x.registered = 1;
                     if (sym->u.t.cse && q->x.copy)
                         q->x.equatable = 1;
                 }
             } else {
                 p->syms[RX] = r;
                 r->x.lastuse = p;
             }
             debug(dumpregs("(allocating %s to node %x)\n", r->x.name, (char *) p));
         }
     }
     p->x.registered = 1;
     (*IR->x.clobber)(p);
 }
References debug, dumpregs(), fprint(), getreg(), getrule(), IR, NeedsReg, NELEMS, opindex, opkind, putreg(), RX, and tmask.
Referenced by gen(), and genspill().
range()
int range (Node p, int lo, int hi)
Definition at line 253 of file gen.c.
{
     Symbol s = p->syms[0];
     switch (specific(p->op)) {
     case ADDRF+P:
     case ADDRL+P: ck(s->x.offset >= lo && s->x.offset <= hi);
     case CNST+I:  ck(s->u.c.v.i  >= lo && s->u.c.v.i  <= hi);
     case CNST+U:  ck(s->u.c.v.u  >= lo && s->u.c.v.u  <= hi);
     case CNST+P:  ck(s->u.c.v.p  == 0  && lo <= 0 && hi >= 0);
     }
     return LBURG_MAX;
 }
References ck, I, LBURG_MAX, P, specific, and U.
reduce()
static void reduce (Node p, int nt) static
Definition at line 185 of file gen.c.
{
     int rulenum, i;
     short *nts;
     Node kids[10];
     p = reuse(p, nt);
     rulenum = getrule(p, nt);
     nts = IR->x._nts[rulenum];
     (*IR->x._kids)(p, rulenum, kids);
     for (i = 0; nts[i]; i++)
         reduce(kids[i], nts[i]);
     if (IR->x._isinstruction[rulenum]) {
         assert(p->x.inst == 0 || p->x.inst == nt);
         p->x.inst = nt;
         if (p->syms[RX] && p->syms[RX]->temporary) {
             debug(fprint(stderr, "(using %s)\n", p->syms[RX]->name));
             p->syms[RX]->x.usecount++;
         }
     }
 }
References debug, fprint(), getrule(), IR, entry::nt, nts, reuse(), and RX.
Referenced by rewrite().
regloc()
unsigned regloc (Symbol p)
Definition at line 826 of file gen.c.
{
     assert(p && p->sclass == REGISTER && p->sclass == REGISTER && p->x.regnode);
     return p->x.regnode->set<<8 | p->x.regnode->number;
 }
reprune()
static int reprune (Node * pp, int k, int n, Node p) static
Definition at line 772 of file gen.c.
{
     struct node x, *q = *pp;
     if (q == NULL || k > n)
         return k;
     else if (q->x.inst == 0)
         return reprune(&q->kids[1],
             reprune(&q->kids[0], k, n, p), n, p);
     if (k == n) {
         debug(fprint(stderr, "(reprune changes %x from %x to %x)\n", pp, *pp, p->x.kids[n]));
         *pp = p->x.kids[n];
         x = *p;
         (IR->x.target)(&x);
     }
     return k + 1;
 }
References debug, fprint(), IR, and NULL.
Referenced by genreload().
requate()
static int requate (Node q) static
Definition at line 386 of file gen.c.
{
     Symbol src = q->x.kids[0]->syms[RX];
     Symbol tmp = q->syms[RX];
     Node p;
     int n = 0;
     debug(fprint(stderr, "(requate(%x): tmp=%s src=%s)\n", q, tmp->x.name, src->x.name));
     for (p = q->x.next; p; p = p->x.next)
         if (p->x.copy && p->syms[RX] == src
         &&  p->x.kids[0]->syms[RX] == tmp)
             debug(fprint(stderr, "(requate arm 0 at %x)\n", p)),
             p->syms[RX] = tmp;
         else if (setsrc(p->syms[RX]) && !moveself(p) && !readsreg(p))
             return 0;
         else if (p->x.spills)
             return 0;
         else if (generic(p->op) == CALL && p->x.next)
             return 0;
         else if (p->op == LABEL+V && p->x.next)
             return 0;
         else if (p->syms[RX] == tmp && readsreg(p))
             debug(fprint(stderr, "(requate arm 5 at %x)\n", p)),
             n++;
         else if (p->syms[RX] == tmp)
             break;
     debug(fprint(stderr, "(requate arm 7 at %x)\n", p));
     assert(n > 0);
     for (p = q->x.next; p; p = p->x.next)
         if (p->syms[RX] == tmp && readsreg(p)) {
             p->syms[RX] = src;
             if (--n <= 0)
                 break;
         }
     return 1;
 }
References CALL, debug, fprint(), moveself(), readsreg, RX, setsrc, and V.
Referenced by emit().
reuse()
static Node reuse (Node p, int nt) static
Definition at line 205 of file gen.c.
{
     struct _state {
         short cost[1];
     };
     Symbol r = p->syms[RX];
     if (generic(p->op) == INDIR && p->kids[0]->op == VREG+P
     && r->u.t.cse && p->x.mayrecalc
     && ((struct _state*)r->u.t.cse->x.state)->cost[nt] == 0)
         return r->u.t.cse;
     else
         return p;
 }
References P, RX, and VREG.
Referenced by dumpcover(), emitasm(), and reduce().
rewrite()
static void rewrite (Node p) static
Definition at line 470 of file gen.c.
{
     assert(p->x.inst == 0);
     prelabel(p);
     debug(dumptree(p));
     debug(fprint(stderr, "\n"));
     (*IR->x._label)(p);
     debug(dumpcover(p, 1, 0));
     reduce(p, 1);
 }
References debug, dumpcover(), dumptree(), fprint(), IR, prelabel(), and reduce().
Referenced by gen(), genreload(), and genspill().
rtarget()
void rtarget (Node p, int n, Symbol r)
Definition at line 452 of file gen.c.
{
     Node q = p->kids[n];
     assert(q);
     assert(r);
     assert(r->sclass == REGISTER || !r->x.wildcard);
     assert(q->syms[RX]);
     if (r != q->syms[RX] && !q->syms[RX]->x.wildcard) {
         q = newnode(LOAD + opkind(q->op),
             q, NULL, q->syms[0]);
         if (r->u.t.cse == p->kids[n])
             r->u.t.cse = q;
         p->kids[n] = p->x.kids[n] = q;
         q->x.kids[0] = q->kids[0];
     }
     setreg(q, r);
     debug(fprint(stderr, "(targeting %x->x.kids[%d]=%x to %s)\n", p, n, p->kids[n], r->x.name));
 }
References debug, fprint(), LOAD, newnode(), NULL, opkind, RX, and setreg().
Referenced by prelabel().
setreg()
void setreg (Node p, Symbol r)
Definition at line 449 of file gen.c.
{
     p->syms[RX] = r;
 }
References RX.
Referenced by prelabel(), and rtarget().
spill()
void spill (unsigned mask, int n, Node here)
Definition at line 788 of file gen.c.
{
     int i;
     Node p;
     here->x.spills = 1;
     usedmask[n] |= mask;
     if (mask&~freemask[n]) {
         assert( /* It makes no sense for a node to clobber() its target. */
             here->x.registered == 0 || /* call isn't coming through clobber() */
             here->syms[RX] == NULL ||
             here->syms[RX]->x.regnode == NULL ||
             here->syms[RX]->x.regnode->set != n ||
             (here->syms[RX]->x.regnode->mask&mask) == 0
         );
         for (p = here; p; p = p->x.next)
             for (i = 0; i < NELEMS(p->x.kids) && p->x.kids[i]; i++) {
                 Symbol r = p->x.kids[i]->syms[RX];
                 assert(r);
                 if (p->x.kids[i]->x.registered && r->x.regnode->set == n
                 && r->x.regnode->mask&mask)
                     spillr(r, here);
             }
     }
 }
References freemask, NELEMS, NULL, RX, spillr(), and usedmask.
Referenced by getreg().
spillee()
static Symbol spillee (Symbol set, unsigned mask[], Node here) static
Definition at line 659 of file gen.c.
{
     Symbol bestreg = NULL;
     int bestdist = -1, i;
     assert(set);
     if (!set->x.wildcard)
         bestreg = set;
     else {
         for (i = 31; i >= 0; i--) {
             Symbol ri = set->x.wildcard[i];
             if (
                 ri != NULL &&
                 ri->x.lastuse &&
                 (ri->x.regnode->mask&tmask[ri->x.regnode->set]&mask[ri->x.regnode->set])
             ) {
                 Regnode rn = ri->x.regnode;
                 Node q = here;
                 int dist = 0;
                 for (; q && !uses(q, rn); q = q->x.next)
                     dist++;
                 if (q && dist > bestdist) {
                     bestdist = dist;
                     bestreg = ri;
                 }
             }
         }
     }
     assert(bestreg); /* Must be able to spill something. Reconfigure the register allocator
         to ensure that we can allocate a register for all nodes without spilling
         the node's necessary input regs. */
     assert(bestreg->x.regnode->vbl == NULL); /* Can't spill register variables because
         the reload site might be in other blocks. Reconfigure the register allocator
         to ensure that this register is never allocated to a variable. */
     return bestreg;
 }
References NULL, ri, tmask, and uses().
Referenced by getreg().
spillr()
static void spillr (Symbol r, Node here) static
Definition at line 707 of file gen.c.
{
     int i;
     Symbol tmp;
     Node p = r->x.lastuse;
     assert(p);
     while (p->x.prevuse)
         assert(r == p->syms[RX]),
         p = p->x.prevuse;
     assert(p->x.registered && !readsreg(p));
     tmp = newtemp(AUTO, optype(p->op), opsize(p->op));
     genspill(r, p, tmp);
     for (p = here->x.next; p; p = p->x.next)
         for (i = 0; i < NELEMS(p->x.kids) && p->x.kids[i]; i++) {
             Node k = p->x.kids[i];
             if (k->x.registered && k->syms[RX] == r)
                 genreload(p, tmp, i);
         }
     putreg(r);
 }
References genreload(), genspill(), NELEMS, newtemp(), opsize, optype, putreg(), readsreg, and RX.
Referenced by spill().
uses()
static int uses (Node p, Regnode rn) static
Definition at line 694 of file gen.c.
{
     int i;
     for (i = 0; i < NELEMS(p->x.kids); i++)
         if (
             p->x.kids[i] &&
             p->x.kids[i]->x.registered &&
             rn->set == p->x.kids[i]->syms[RX]->x.regnode->set &&
             (rn->mask&p->x.kids[i]->syms[RX]->x.regnode->mask)
         )
             return 1;
     return 0;
 }
References Regnode::mask, NELEMS, RX, and Regnode::set.
Referenced by spillee().
Variable Documentation
argoffset
int argoffset
Definition at line 45 of file gen.c.
Referenced by docall(), function(), gen02(), and mkactual().
bflag
int bflag = 0
Definition at line 50 of file gen.c.
Referenced by parseflags().
dalign
int dalign
Definition at line 49 of file gen.c.
Referenced by blkunroll().
dflag
int dflag = 0
Definition at line 51 of file gen.c.
Referenced by parseflags().
emitter
unsigned(* emitter) (Node, int) = emitasm
Definition at line 55 of file gen.c.
Referenced by emit(), PSys_FreeEmitter(), PSys_FreeSystem(), PSys_SpawnCachedSystem(), PSys_SpawnEmitter(), and PSys_UpdateEmitters().
framesize
int framesize
Definition at line 44 of file gen.c.
Referenced by emitasm().
freemask
unsigned freemask[2]
Definition at line 75 of file gen.c.
Referenced by askfixedreg(), blockbeg(), blockend(), dumpregs(), putreg(), and spill().
head
Node head
Definition at line 73 of file gen.c.
Referenced by CG_BreathPuffs(), CG_BubblesTrail(), CG_InnerAuraSpikes(), CG_Player(), CG_PlayerAngles(), CG_PlayerAnimation(), gen(), inflateGetHeader(), Info_NextPair(), progbeg(), S_Base_Respatialize(), swstmt(), UI_DrawPlayer(), UI_PlayerAngles(), and UI_PlayerAnimation().
maxargoffset
int maxargoffset
Definition at line 47 of file gen.c.
Referenced by docall().
maxoffset
int maxoffset
Definition at line 42 of file gen.c.
Referenced by blockend().
NeedsReg
char NeedsReg[] static
Initial value:
= {
    0,
    1,
    0, 0,
    1,
    0, 0, 1, 1,
    1, 0, 1, 1,
    1,
    1,
    0,
    1, 1, 1,
    1, 1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1,
    0, 0, 0, 0, 0, 0,
    0, 0
}
Definition at line 56 of file gen.c.
Referenced by gen(), genspill(), prelabel(), and ralloc().
offset
int offset
Definition at line 40 of file gen.c.
Referenced by blockbeg(), blockend(), and mkauto().
salign
int salign
Definition at line 49 of file gen.c.
Referenced by blkunroll().
swap
int swap
Definition at line 53 of file gen.c.
Referenced by defconst(), and Hunk_SwapBanks().
tmask
unsigned tmask[2]
Definition at line 77 of file gen.c.
Referenced by ralloc(), and spillee().
usedmask
unsigned usedmask[2]
Definition at line 76 of file gen.c.
Referenced by askfixedreg(), and spill().
vmask
unsigned vmask[2]
Definition at line 78 of file gen.c.
Referenced by askregvar().