ZEQ2-Lite: Tools/MinGW/include/ocidl.h File Reference
ocidl.h File Reference
#include <ole2.h>
Data Structures
struct tagCADWORD
struct tagCALPOLESTR
struct tagCAUUID
struct tagCONNECTDATA
struct tagCONTROLINFO
struct tagLICINFO
struct tagPOINTF
struct tagPROPBAG2
struct tagPROPPAGEINFO
struct tagQACONTAINER
struct tagQACONTROL
Macros
#define INTERFACE IOleControl
#define INTERFACE IOleControlSite
#define INTERFACE ISimpleFrameSite
#define INTERFACE IErrorLog
#define INTERFACE IPropertyBag
#define INTERFACE IPropertyBag2
#define INTERFACE IPersistPropertyBag
#define INTERFACE IPersistPropertyBag2
#define INTERFACE IPersistStreamInit
#define INTERFACE IPersistMemory
#define INTERFACE IPropertyNotifySink
#define INTERFACE IProvideClassInfo
#define INTERFACE IProvideClassInfo2
#define INTERFACE IConnectionPointContainer
#define INTERFACE IEnumConnectionPoints
#define INTERFACE IConnectionPoint
#define INTERFACE IEnumConnections
#define INTERFACE IClassFactory2
#define INTERFACE ISpecifyPropertyPages
#define INTERFACE IPerPropertyBrowsing
#define INTERFACE IPropertyPageSite
#define INTERFACE IPropertyPage
#define INTERFACE IPropertyPage2
#define INTERFACE IFont
#define INTERFACE IFontDisp
#define INTERFACE IPicture
#define INTERFACE IPictureDisp
#define INTERFACE IOleInPlaceSiteEx
#define INTERFACE IObjectWithSite
#define INTERFACE IOleInPlaceSiteWindowless
#define INTERFACE IAdviseSinkEx
#define INTERFACE IPointerInactive
#define INTERFACE IOleUndoUnit
#define INTERFACE IOleParentUndoUnit
#define INTERFACE IEnumOleUndoUnits
#define INTERFACE IOleUndoManager
#define INTERFACE IQuickActivate
Typedefs
typedef struct CADWORD * LPCADWORD
typedef struct CALPOLESTR * LPCALPOLESTR
typedef struct CAUUID * LPCAUUID
typedef struct CONNECTDATA * LPCONNECTDATA
typedef _COM_interface IConnectionPoint * LPCONNECTIONPOINT
typedef struct CONTROLINFO * LPCONTROLINFO
typedef _COM_interface IEnumConnectionPoints * LPENUMCONNECTIONPOINTS
typedef _COM_interface IEnumConnections * LPENUMCONNECTIONS
typedef _COM_interface IErrorLog * LPERRORLOG
typedef _COM_interface IFont * LPFONT
typedef _COM_interface IFontDisp * LPFONTDISP
typedef struct LICINFO * LPLICINFO
typedef _COM_interface IOleUndoManager * LPOLEUNDOMANAGER
typedef struct POINTF * LPPOINTF
typedef _COM_interface IPropertyBag * LPPROPERTYBAG
typedef _COM_interface IPropertyBag2 * LPPROPERTYBAG2
typedef _COM_interface IPropertyPageSite * LPPROPERTYPAGESITE
typedef struct PROPPAGEINFO * LPPROPPAGEINFO
typedef TEXTMETRICOLE * LPTEXTMETRICOLE
typedef DWORD OLE_COLOR
typedef UINT OLE_HANDLE
typedef long OLE_XPOS_HIMETRIC
typedef long OLE_XSIZE_HIMETRIC
typedef long OLE_YPOS_HIMETRIC
typedef long OLE_YSIZE_HIMETRIC
typedef TEXTMETRICW TEXTMETRICOLE
Enumerations
enum tagPROPBAG2_TYPE {
PROPBAG2_TYPE_UNDEFINED = 0, PROPBAG2_TYPE_DATA = 1, PROPBAG2_TYPE_URL = 2, PROPBAG2_TYPE_OBJECT = 3,
PROPBAG2_TYPE_STREAM = 4, PROPBAG2_TYPE_STORAGE = 5, PROPBAG2_TYPE_MONIKER = 6
}
enum tagQACONTAINERFLAGS {
QACONTAINER_SHOWHATCHING = 1, QACONTAINER_SHOWGRABHANDLES = 2, QACONTAINER_USERMODE = 4, QACONTAINER_DISPLAYASDEFAULT = 8,
QACONTAINER_UIDEAD = 16, QACONTAINER_AUTOCLIP = 32, QACONTAINER_MESSAGEREFLECT = 64, QACONTAINER_SUPPORTSMNEMONICS = 128
}
enum tagREADYSTATE {
READYSTATE_UNINITIALIZED = 0, READYSTATE_LOADING = 1, READYSTATE_LOADED = 2, READYSTATE_INTERACTIVE = 3,
READYSTATE_COMPLETE = 4
}
Functions
DECLARE_INTERFACE_ (IAdviseSinkEx, IUnknown)
DECLARE_INTERFACE_ (IClassFactory2, IClassFactory)
DECLARE_INTERFACE_ (IConnectionPoint, IUnknown)
DECLARE_INTERFACE_ (IConnectionPointContainer, IUnknown)
DECLARE_INTERFACE_ (IEnumConnectionPoints, IUnknown)
DECLARE_INTERFACE_ (IEnumConnections, IUnknown)
DECLARE_INTERFACE_ (IEnumOleUndoUnits, IUnknown)
DECLARE_INTERFACE_ (IErrorLog, IUnknown)
DECLARE_INTERFACE_ (IFont, IUnknown)
DECLARE_INTERFACE_ (IFontDisp, IDispatch)
DECLARE_INTERFACE_ (IObjectWithSite, IUnknown)
DECLARE_INTERFACE_ (IOleControl, IUnknown)
DECLARE_INTERFACE_ (IOleControlSite, IUnknown)
DECLARE_INTERFACE_ (IOleInPlaceSiteEx, IOleInPlaceSite)
DECLARE_INTERFACE_ (IOleInPlaceSiteWindowless, IOleInPlaceSiteEx)
DECLARE_INTERFACE_ (IOleParentUndoUnit, IOleUndoUnit)
DECLARE_INTERFACE_ (IOleUndoManager, IUnknown)
DECLARE_INTERFACE_ (IOleUndoUnit, IUnknown)
DECLARE_INTERFACE_ (IPerPropertyBrowsing, IUnknown)
DECLARE_INTERFACE_ (IPersistMemory, IPersist)
DECLARE_INTERFACE_ (IPersistPropertyBag, IPersist)
DECLARE_INTERFACE_ (IPersistPropertyBag2, IPersist)
DECLARE_INTERFACE_ (IPersistStreamInit, IPersist)
DECLARE_INTERFACE_ (IPicture, IUnknown)
DECLARE_INTERFACE_ (IPictureDisp, IDispatch)
DECLARE_INTERFACE_ (IPointerInactive, IUnknown)
DECLARE_INTERFACE_ (IPropertyBag, IUnknown)
DECLARE_INTERFACE_ (IPropertyBag2, IUnknown)
DECLARE_INTERFACE_ (IPropertyNotifySink, IUnknown)
DECLARE_INTERFACE_ (IPropertyPage, IUnknown)
DECLARE_INTERFACE_ (IPropertyPage2, IPropertyPage)
DECLARE_INTERFACE_ (IPropertyPageSite, IUnknown)
DECLARE_INTERFACE_ (IProvideClassInfo, IUnknown)
DECLARE_INTERFACE_ (IProvideClassInfo2, IProvideClassInfo)
DECLARE_INTERFACE_ (IQuickActivate, IUnknown)
DECLARE_INTERFACE_ (ISimpleFrameSite, IUnknown)
DECLARE_INTERFACE_ (ISpecifyPropertyPages, IUnknown)
Variables
const EXTERN_C IID IID_IAdviseSinkEx
const EXTERN_C IID IID_IClassFactory2
const EXTERN_C IID IID_IConnectionPoint
const EXTERN_C IID IID_IConnectionPointContainer
const EXTERN_C IID IID_IEnumConnectionPoints
const EXTERN_C IID IID_IEnumConnections
const EXTERN_C IID IID_IEnumOleUndoUnits
const EXTERN_C IID IID_IErrorLog
const EXTERN_C IID IID_IFont
const EXTERN_C IID IID_IFontDisp
const EXTERN_C IID IID_IObjectWithSite
const EXTERN_C IID IID_IOleControl
const EXTERN_C IID IID_IOleControlSite
const EXTERN_C IID IID_IOleInPlaceSiteEx
const EXTERN_C IID IID_IOleInPlaceSiteWindowless
const EXTERN_C IID IID_IOleParentUndoUnit
const EXTERN_C IID IID_IOleUndoManager
const EXTERN_C IID IID_IOleUndoUnit
const EXTERN_C IID IID_IPerPropertyBrowsing
const EXTERN_C IID IID_IPersistMemory
const EXTERN_C IID IID_IPersistPropertyBag
const EXTERN_C IID IID_IPersistPropertyBag2
const EXTERN_C IID IID_IPersistStreamInit
const EXTERN_C IID IID_IPicture
const EXTERN_C IID IID_IPictureDisp
const EXTERN_C IID IID_IPointerInactive
const EXTERN_C IID IID_IPropertyBag
const EXTERN_C IID IID_IPropertyBag2
const EXTERN_C IID IID_IPropertyNotifySink
const EXTERN_C IID IID_IPropertyPage
const EXTERN_C IID IID_IPropertyPage2
const EXTERN_C IID IID_IPropertyPageSite
const EXTERN_C IID IID_IProvideClassInfo
const EXTERN_C IID IID_IProvideClassInfo2
const EXTERN_C IID IID_IQuickActivate
const EXTERN_C IID IID_ISimpleFrameSite
const EXTERN_C IID IID_ISpecifyPropertyPages
Macro Definition Documentation
INTERFACE [1/37]
#define INTERFACE IOleControl
Definition at line 841 of file ocidl.h.
INTERFACE [2/37]
#define INTERFACE IOleControlSite
Definition at line 841 of file ocidl.h.
INTERFACE [3/37]
#define INTERFACE ISimpleFrameSite
Definition at line 841 of file ocidl.h.
INTERFACE [4/37]
#define INTERFACE IErrorLog
Definition at line 841 of file ocidl.h.
INTERFACE [5/37]
#define INTERFACE IPropertyBag
Definition at line 841 of file ocidl.h.
INTERFACE [6/37]
#define INTERFACE IPropertyBag2
Definition at line 841 of file ocidl.h.
INTERFACE [7/37]
#define INTERFACE IPersistPropertyBag
Definition at line 841 of file ocidl.h.
INTERFACE [8/37]
#define INTERFACE IPersistPropertyBag2
Definition at line 841 of file ocidl.h.
INTERFACE [9/37]
#define INTERFACE IPersistStreamInit
Definition at line 841 of file ocidl.h.
INTERFACE [10/37]
#define INTERFACE IPersistMemory
Definition at line 841 of file ocidl.h.
INTERFACE [11/37]
#define INTERFACE IPropertyNotifySink
Definition at line 841 of file ocidl.h.
INTERFACE [12/37]
#define INTERFACE IProvideClassInfo
Definition at line 841 of file ocidl.h.
INTERFACE [13/37]
#define INTERFACE IProvideClassInfo2
Definition at line 841 of file ocidl.h.
INTERFACE [14/37]
#define INTERFACE IConnectionPointContainer
Definition at line 841 of file ocidl.h.
INTERFACE [15/37]
#define INTERFACE IEnumConnectionPoints
Definition at line 841 of file ocidl.h.
INTERFACE [16/37]
#define INTERFACE IConnectionPoint
Definition at line 841 of file ocidl.h.
INTERFACE [17/37]
#define INTERFACE IEnumConnections
Definition at line 841 of file ocidl.h.
INTERFACE [18/37]
#define INTERFACE IClassFactory2
Definition at line 841 of file ocidl.h.
INTERFACE [19/37]
#define INTERFACE ISpecifyPropertyPages
Definition at line 841 of file ocidl.h.
INTERFACE [20/37]
#define INTERFACE IPerPropertyBrowsing
Definition at line 841 of file ocidl.h.
INTERFACE [21/37]
#define INTERFACE IPropertyPageSite
Definition at line 841 of file ocidl.h.
INTERFACE [22/37]
#define INTERFACE IPropertyPage
Definition at line 841 of file ocidl.h.
INTERFACE [23/37]
#define INTERFACE IPropertyPage2
Definition at line 841 of file ocidl.h.
INTERFACE [24/37]
#define INTERFACE IFont
Definition at line 841 of file ocidl.h.
INTERFACE [25/37]
#define INTERFACE IFontDisp
Definition at line 841 of file ocidl.h.
INTERFACE [26/37]
#define INTERFACE IPicture
Definition at line 841 of file ocidl.h.
INTERFACE [27/37]
#define INTERFACE IPictureDisp
Definition at line 841 of file ocidl.h.
INTERFACE [28/37]
#define INTERFACE IOleInPlaceSiteEx
Definition at line 841 of file ocidl.h.
INTERFACE [29/37]
#define INTERFACE IObjectWithSite
Definition at line 841 of file ocidl.h.
INTERFACE [30/37]
#define INTERFACE IOleInPlaceSiteWindowless
Definition at line 841 of file ocidl.h.
INTERFACE [31/37]
#define INTERFACE IAdviseSinkEx
Definition at line 841 of file ocidl.h.
INTERFACE [32/37]
#define INTERFACE IPointerInactive
Definition at line 841 of file ocidl.h.
INTERFACE [33/37]
#define INTERFACE IOleUndoUnit
Definition at line 841 of file ocidl.h.
INTERFACE [34/37]
#define INTERFACE IOleParentUndoUnit
Definition at line 841 of file ocidl.h.
INTERFACE [35/37]
#define INTERFACE IEnumOleUndoUnits
Definition at line 841 of file ocidl.h.
INTERFACE [36/37]
#define INTERFACE IOleUndoManager
Definition at line 841 of file ocidl.h.
INTERFACE [37/37]
#define INTERFACE IQuickActivate
Definition at line 841 of file ocidl.h.
Typedef Documentation
LPCADWORD
typedef struct CADWORD* LPCADWORD
LPCALPOLESTR
typedef struct CALPOLESTR* LPCALPOLESTR
LPCAUUID
typedef struct CAUUID* LPCAUUID
LPCONNECTDATA
typedef struct CONNECTDATA* LPCONNECTDATA
LPCONNECTIONPOINT
typedef _COM_interface IConnectionPoint* LPCONNECTIONPOINT
Definition at line 17 of file ocidl.h.
LPCONTROLINFO
typedef struct CONTROLINFO* LPCONTROLINFO
LPENUMCONNECTIONPOINTS
typedef _COM_interface IEnumConnectionPoints* LPENUMCONNECTIONPOINTS
Definition at line 18 of file ocidl.h.
LPENUMCONNECTIONS
typedef _COM_interface IEnumConnections* LPENUMCONNECTIONS
Definition at line 16 of file ocidl.h.
LPERRORLOG
typedef _COM_interface IErrorLog* LPERRORLOG
Definition at line 13 of file ocidl.h.
LPFONT
typedef _COM_interface IFont* LPFONT
Definition at line 20 of file ocidl.h.
LPFONTDISP
typedef _COM_interface IFontDisp* LPFONTDISP
Definition at line 21 of file ocidl.h.
LPLICINFO
typedef struct LICINFO* LPLICINFO
LPOLEUNDOMANAGER
typedef _COM_interface IOleUndoManager* LPOLEUNDOMANAGER
Definition at line 22 of file ocidl.h.
LPPOINTF
typedef struct POINTF* LPPOINTF
LPPROPERTYBAG
typedef _COM_interface IPropertyBag* LPPROPERTYBAG
Definition at line 14 of file ocidl.h.
LPPROPERTYBAG2
typedef _COM_interface IPropertyBag2* LPPROPERTYBAG2
Definition at line 15 of file ocidl.h.
LPPROPERTYPAGESITE
typedef _COM_interface IPropertyPageSite* LPPROPERTYPAGESITE
Definition at line 19 of file ocidl.h.
LPPROPPAGEINFO
typedef struct PROPPAGEINFO* LPPROPPAGEINFO
LPTEXTMETRICOLE
typedef TEXTMETRICOLE* LPTEXTMETRICOLE
Definition at line 29 of file ocidl.h.
OLE_COLOR
typedef DWORD OLE_COLOR
Definition at line 30 of file ocidl.h.
OLE_HANDLE
typedef UINT OLE_HANDLE
Definition at line 31 of file ocidl.h.
OLE_XPOS_HIMETRIC
typedef long OLE_XPOS_HIMETRIC
Definition at line 32 of file ocidl.h.
OLE_XSIZE_HIMETRIC
typedef long OLE_XSIZE_HIMETRIC
Definition at line 34 of file ocidl.h.
OLE_YPOS_HIMETRIC
typedef long OLE_YPOS_HIMETRIC
Definition at line 33 of file ocidl.h.
OLE_YSIZE_HIMETRIC
typedef long OLE_YSIZE_HIMETRIC
Definition at line 35 of file ocidl.h.
TEXTMETRICOLE
typedef TEXTMETRICW TEXTMETRICOLE
Definition at line 25 of file ocidl.h.
Enumeration Type Documentation
tagPROPBAG2_TYPE
enum tagPROPBAG2_TYPE
Enumerator
PROPBAG2_TYPE_UNDEFINED
PROPBAG2_TYPE_DATA
PROPBAG2_TYPE_URL
PROPBAG2_TYPE_OBJECT
PROPBAG2_TYPE_STREAM
PROPBAG2_TYPE_STORAGE
PROPBAG2_TYPE_MONIKER
Definition at line 44 of file ocidl.h.
{
     PROPBAG2_TYPE_UNDEFINED = 0,
     PROPBAG2_TYPE_DATA = 1,
     PROPBAG2_TYPE_URL = 2,
     PROPBAG2_TYPE_OBJECT = 3,
     PROPBAG2_TYPE_STREAM = 4,
     PROPBAG2_TYPE_STORAGE = 5,
     PROPBAG2_TYPE_MONIKER = 6
 } PROPBAG2_TYPE;
tagQACONTAINERFLAGS
enum tagQACONTAINERFLAGS
Enumerator
QACONTAINER_SHOWHATCHING
QACONTAINER_SHOWGRABHANDLES
QACONTAINER_USERMODE
QACONTAINER_DISPLAYASDEFAULT
QACONTAINER_UIDEAD
QACONTAINER_AUTOCLIP
QACONTAINER_MESSAGEREFLECT
QACONTAINER_SUPPORTSMNEMONICS
Definition at line 62 of file ocidl.h.
 {
     QACONTAINER_SHOWHATCHING = 1,
     QACONTAINER_SHOWGRABHANDLES = 2,
     QACONTAINER_USERMODE = 4,
     QACONTAINER_DISPLAYASDEFAULT = 8,
     QACONTAINER_UIDEAD = 16,
     QACONTAINER_AUTOCLIP = 32,
     QACONTAINER_MESSAGEREFLECT = 64,
     QACONTAINER_SUPPORTSMNEMONICS = 128
 } QACONTAINERFLAGS;
tagREADYSTATE
enum tagREADYSTATE
Enumerator
READYSTATE_UNINITIALIZED
READYSTATE_LOADING
READYSTATE_LOADED
READYSTATE_INTERACTIVE
READYSTATE_COMPLETE
Definition at line 37 of file ocidl.h.
{
     READYSTATE_UNINITIALIZED = 0,
     READYSTATE_LOADING = 1,
     READYSTATE_LOADED = 2,
     READYSTATE_INTERACTIVE = 3,
     READYSTATE_COMPLETE = 4
 } READYSTATE;
Function Documentation
DECLARE_INTERFACE_() [1/37]
DECLARE_INTERFACE_ (IAdviseSinkEx , IUnknown)
Definition at line 744 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD_(void,OnDataChange)(THIS_ FORMATETC*,STGMEDIUM*) PURE;
     STDMETHOD_(void,OnViewChange)(THIS_ DWORD,LONG) PURE;
     STDMETHOD_(void,OnRename)(THIS_ IMoniker*) PURE;
     STDMETHOD_(void,OnSave)(THIS) PURE;
     STDMETHOD_(void,OnClose)(THIS) PURE;
     STDMETHOD(OnViewStatusChange)(THIS_ DWORD) PURE;
 };
References LONG, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [2/37]
DECLARE_INTERFACE_ (IClassFactory2 , IClassFactory)
Definition at line 465 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(CreateInstance)(THIS_ LPUNKNOWN,REFIID,PVOID*) PURE;
     STDMETHOD(LockServer)(THIS_ BOOL) PURE;
     STDMETHOD(GetLicInfo)(THIS_ LPLICINFO) PURE;
     STDMETHOD(RequestLicKey)(THIS_ DWORD,BSTR*) PURE;
     STDMETHOD(CreateInstanceLic)(THIS_ LPUNKNOWN,LPUNKNOWN,REFIID,BSTR,PVOID*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [3/37]
DECLARE_INTERFACE_ (IConnectionPoint , IUnknown)
Definition at line 415 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetConnectionInterface)(THIS_ IID*) PURE;
     STDMETHOD(GetConnectionPointContainer)(THIS_ IConnectionPointContainer**) PURE;
     STDMETHOD(Advise)(THIS_ LPUNKNOWN,PDWORD) PURE;
     STDMETHOD(Unadvise)(THIS_ DWORD) PURE;
     STDMETHOD(EnumConnections)(THIS_ LPENUMCONNECTIONS*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [4/37]
DECLARE_INTERFACE_ (IConnectionPointContainer , IUnknown)
Definition at line 381 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(EnumConnectionPoints)(THIS_ LPENUMCONNECTIONPOINTS*) PURE;
     STDMETHOD(FindConnectionPoint)(THIS_ REFIID,LPCONNECTIONPOINT*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [5/37]
DECLARE_INTERFACE_ (IEnumConnectionPoints , IUnknown)
Definition at line 401 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Next)(THIS_ ULONG,LPCONNECTIONPOINT*,ULONG*) PURE;
     STDMETHOD(Skip)(THIS_ ULONG) PURE;
     STDMETHOD(Reset)(THIS) PURE;
     STDMETHOD(Clone)(THIS_ LPENUMCONNECTIONPOINTS*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [6/37]
DECLARE_INTERFACE_ (IEnumConnections , IUnknown)
Definition at line 441 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Next)(THIS_ ULONG,LPCONNECTDATA,PULONG) PURE;
     STDMETHOD(Skip)(THIS_ ULONG) PURE;
     STDMETHOD(Reset)(THIS) PURE;
     STDMETHOD(Clone)(THIS_ LPENUMCONNECTIONS*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [7/37]
DECLARE_INTERFACE_ (IEnumOleUndoUnits , IUnknown)
Definition at line 806 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Next)(THIS_ ULONG,IOleUndoUnit**,ULONG*) PURE;
     STDMETHOD(Skip)(THIS_ ULONG) PURE;
     STDMETHOD(Reset)(THIS) PURE;
     STDMETHOD(Clone)(THIS_ IEnumOleUndoUnits**) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [8/37]
DECLARE_INTERFACE_ (IErrorLog , IUnknown)
Definition at line 199 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(AddError)(THIS_ LPCOLESTR,LPEXCEPINFO) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [9/37]
DECLARE_INTERFACE_ (IFont , IUnknown)
Definition at line 562 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(get_Name)(THIS_ BSTR*) PURE;
     STDMETHOD(put_Name)(THIS_ BSTR) PURE;
     STDMETHOD(get_Size)(THIS_ CY*) PURE;
     STDMETHOD(put_Size)(THIS_ CY) PURE;
     STDMETHOD(get_Bold)(THIS_ BOOL*) PURE;
     STDMETHOD(put_Bold)(THIS_ BOOL) PURE;
     STDMETHOD(get_Italic)(THIS_ BOOL*) PURE;
     STDMETHOD(put_Italic)(THIS_ BOOL) PURE;
     STDMETHOD(get_Underline)(THIS_ BOOL*) PURE;
     STDMETHOD(put_Underline)(THIS_ BOOL) PURE;
     STDMETHOD(get_Strikethrough)(THIS_ BOOL*) PURE;
     STDMETHOD(put_Strikethrough)(THIS_ BOOL) PURE;
     STDMETHOD(get_Weight)(THIS_ short*) PURE;
     STDMETHOD(put_Weight)(THIS_ short) PURE;
     STDMETHOD(get_Charset)(THIS_ short*) PURE;
     STDMETHOD(put_Charset)(THIS_ short) PURE;
     STDMETHOD(get_hFont)(THIS_ HFONT*) PURE;
     STDMETHOD(Clone)(THIS_ IFont**) PURE;
     STDMETHOD(IsEqual)(THIS_ IFont*) PURE;
     STDMETHOD(SetRatio)(THIS_ long,long) PURE;
     STDMETHOD(QueryTextMetrics)(THIS_ LPTEXTMETRICOLE) PURE;
     STDMETHOD(AddRefHfont)(THIS_ HFONT) PURE;
     STDMETHOD(ReleaseHfont)(THIS_ HFONT) PURE;
     STDMETHOD(SetHdc)(THIS_ HDC) PURE;
 };
References long(), PURE, short, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [10/37]
DECLARE_INTERFACE_ (IFontDisp , IDispatch)
Definition at line 596 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetTypeInfoCount)(THIS_ UINT*) PURE;
     STDMETHOD(GetTypeInfo)(THIS_ UINT,LCID,LPTYPEINFO*) PURE;
     STDMETHOD(GetIDsOfNames)(THIS_ REFIID,LPOLESTR*,UINT,LCID,DISPID*) PURE;
     STDMETHOD(Invoke)(THIS_ DISPID,REFIID,LCID,WORD,DISPPARAMS*,VARIANT*,EXCEPINFO*,UINT*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [11/37]
DECLARE_INTERFACE_ (IObjectWithSite , IUnknown)
Definition at line 693 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(SetSite)(THIS_ IUnknown*) PURE;
     STDMETHOD(GetSite)(THIS_ REFIID, void**) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [12/37]
DECLARE_INTERFACE_ (IOleControl , IUnknown)
Definition at line 143 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetControlInfo)(THIS_ LPCONTROLINFO) PURE;
     STDMETHOD(OnMnemonic)(THIS_ LPMSG) PURE;
     STDMETHOD(OnAmbientPropertyChange)(THIS_ DISPID) PURE;
     STDMETHOD(FreezeEvents)(THIS_ BOOL) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [13/37]
DECLARE_INTERFACE_ (IOleControlSite , IUnknown)
Definition at line 157 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(OnControlInfoChanged)(THIS) PURE;
     STDMETHOD(LockInPlaceActive)(THIS_ BOOL) PURE;
     STDMETHOD(GetExtendedControl)(THIS_ LPDISPATCH*) PURE;
     STDMETHOD(TransformCoords)(THIS_ POINTL*,POINTF*,DWORD) PURE;
     STDMETHOD(TranslateAccelerator)(THIS_ LPMSG,DWORD) PURE;
     STDMETHOD(OnFocus)(THIS_ BOOL) PURE;
     STDMETHOD(ShowPropertyFrame)(THIS) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, THIS_, and TranslateAccelerator.
DECLARE_INTERFACE_() [14/37]
DECLARE_INTERFACE_ (IOleInPlaceSiteEx , IOleInPlaceSite)
Definition at line 668 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetWindow)(THIS_ HWND*) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
     STDMETHOD(CanInPlaceActivate)(THIS) PURE;
     STDMETHOD(OnInPlaceActivate)(THIS) PURE;
     STDMETHOD(OnUIActivate)(THIS) PURE;
     STDMETHOD(GetWindowContext)(THIS_ IOleInPlaceFrame**,IOleInPlaceUIWindow**,LPRECT,LPRECT,LPOLEINPLACEFRAMEINFO) PURE;
     STDMETHOD(Scroll)(THIS_ SIZE) PURE;
     STDMETHOD(OnUIDeactivate)(THIS_ BOOL) PURE;
     STDMETHOD(OnInPlaceDeactivate)(THIS) PURE;
     STDMETHOD(DiscardUndoState)(THIS) PURE;
     STDMETHOD(DeactivateAndUndo)(THIS) PURE;
     STDMETHOD(OnPosRectChange)(THIS_ LPCRECT) PURE;
     STDMETHOD(OnInPlaceActivateEx)(THIS_ BOOL*,DWORD) PURE;
     STDMETHOD(OnInPlaceDeactivateEx)(THIS_ BOOL) PURE;
     STDMETHOD(RequestUIActivate)(THIS) PURE;
 };
References GetWindow(), HWND, LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [15/37]
DECLARE_INTERFACE_ (IOleInPlaceSiteWindowless , IOleInPlaceSiteEx)
Definition at line 705 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetWindow)(THIS_ HWND*) PURE;
     STDMETHOD(ContextSensitiveHelp)(THIS_ BOOL) PURE;
     STDMETHOD(CanInPlaceActivate)(THIS) PURE;
     STDMETHOD(OnInPlaceActivate)(THIS) PURE;
     STDMETHOD(OnUIActivate)(THIS) PURE;
     STDMETHOD(GetWindowContext)(THIS_ IOleInPlaceFrame**,IOleInPlaceUIWindow**,LPRECT,LPRECT,LPOLEINPLACEFRAMEINFO) PURE;
     STDMETHOD(Scroll)(THIS_ SIZE) PURE;
     STDMETHOD(OnUIDeactivate)(THIS_ BOOL) PURE;
     STDMETHOD(OnInPlaceDeactivate)(THIS) PURE;
     STDMETHOD(DiscardUndoState)(THIS) PURE;
     STDMETHOD(DeactivateAndUndo)(THIS) PURE;
     STDMETHOD(OnPosRectChange)(THIS_ LPCRECT) PURE;
     STDMETHOD(OnInPlaceActivateEx)(THIS_ BOOL*,DWORD) PURE;
     STDMETHOD(OnInPlaceDeactivateEx)(THIS_ BOOL) PURE;
     STDMETHOD(RequestUIActivate)(THIS) PURE;
     STDMETHOD(CanWindowlessActivate)(THIS) PURE;
     STDMETHOD(GetCapture)(THIS) PURE;
     STDMETHOD(SetCapture)(THIS_ BOOL) PURE;
     STDMETHOD(GetFocus)(THIS) PURE;
     STDMETHOD(SetFocus)(THIS_ BOOL) PURE;
     STDMETHOD(GetDC)(THIS_ LPCRECT,DWORD,HDC*) PURE;
     STDMETHOD(ReleaseDC)(THIS_ HDC) PURE;
     STDMETHOD(InvalidateRect)(THIS_ LPCRECT,BOOL) PURE;
     STDMETHOD(InvalidateRgn)(THIS_ HRGN,BOOL) PURE;
     STDMETHOD(ScrollRect)(THIS_ INT,INT,LPCRECT,LPCRECT) PURE;
     STDMETHOD(AdjustRect)(THIS_ LPCRECT) PURE;
     STDMETHOD(OnDefWindowMessage)(THIS_ UINT,WPARAM,LPARAM,LRESULT*) PURE;
 };
References GetCapture(), GetDC(), GetFocus(), GetWindow(), HWND, INT, InvalidateRect(), InvalidateRgn(), LPCRECT, PURE, ReleaseDC(), SetCapture(), SetFocus(), STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [16/37]
DECLARE_INTERFACE_ (IOleParentUndoUnit , IOleUndoUnit)
Definition at line 787 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Do)(THIS_ LPOLEUNDOMANAGER) PURE;
     STDMETHOD(GetDescription)(THIS_ BSTR*) PURE;
     STDMETHOD(GetUnitType)(THIS_ CLSID*,LONG*) PURE;
     STDMETHOD(OnNextAdd)(THIS) PURE;
     STDMETHOD(Open)(THIS_ IOleParentUndoUnit*) PURE;
     STDMETHOD(Close)(THIS_ IOleParentUndoUnit*,BOOL) PURE;
     STDMETHOD(Add)(THIS_ IOleUndoUnit*) PURE;
     STDMETHOD(FindUnit)(THIS_ IOleUndoUnit*) PURE;
     STDMETHOD(GetParentState)(THIS_ DWORD*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [17/37]
DECLARE_INTERFACE_ (IOleUndoManager , IUnknown)
Definition at line 820 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Open)(THIS_ IOleParentUndoUnit*) PURE;
     STDMETHOD(Close)(THIS_ IOleParentUndoUnit*,BOOL) PURE;
     STDMETHOD(Add)(THIS_ IOleUndoUnit*) PURE;
     STDMETHOD(GetOpenParentState)(THIS_ DWORD*) PURE;
     STDMETHOD(DiscardFrom)(THIS_ IOleUndoUnit*) PURE;
     STDMETHOD(UndoTo)(THIS_ IOleUndoUnit*) PURE;
     STDMETHOD(RedoTo)(THIS_ IOleUndoUnit*) PURE;
     STDMETHOD(EnumUndoable)(THIS_ IEnumOleUndoUnits**) PURE;
     STDMETHOD(EnumRedoable)(THIS_ IEnumOleUndoUnits**) PURE;
     STDMETHOD(GetLastUndoDescription)(THIS_ BSTR*) PURE;
     STDMETHOD(GetLastRedoDescription)(THIS_ BSTR*) PURE;
     STDMETHOD(Enable)(THIS_ BOOL) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [18/37]
DECLARE_INTERFACE_ (IOleUndoUnit , IUnknown)
Definition at line 773 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Do)(THIS_ LPOLEUNDOMANAGER) PURE;
     STDMETHOD(GetDescription)(THIS_ BSTR*) PURE;
     STDMETHOD(GetUnitType)(THIS_ CLSID*,LONG*) PURE;
     STDMETHOD(OnNextAdd)(THIS) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [19/37]
DECLARE_INTERFACE_ (IPerPropertyBrowsing , IUnknown)
Definition at line 491 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetDisplayString)(THIS_ DISPID,BSTR*) PURE;
     STDMETHOD(MapPropertyToPage)(THIS_ DISPID,LPCLSID) PURE;
     STDMETHOD(GetPredefinedStrings)(THIS_ DISPID,CALPOLESTR*,CADWORD*) PURE;
     STDMETHOD(GetPredefinedValue)(THIS_ DISPID,DWORD,VARIANT*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [20/37]
DECLARE_INTERFACE_ (IPersistMemory , IPersist)
Definition at line 322 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetClassID)(THIS_ LPCLSID) PURE;
     STDMETHOD(IsDirty)(THIS) PURE;
     STDMETHOD(Load)(THIS_ PVOID,ULONG) PURE;
     STDMETHOD(Save)(THIS_ PVOID,BOOL,ULONG) PURE;
     STDMETHOD(GetSizeMax)(THIS_ PULONG) PURE;
     STDMETHOD(InitNew)(THIS) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [21/37]
DECLARE_INTERFACE_ (IPersistPropertyBag , IPersist)
Definition at line 256 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetClassID)(THIS_ LPCLSID) PURE;
     STDMETHOD(InitNew)(THIS) PURE;
     STDMETHOD(Load)(THIS_ LPPROPERTYBAG,LPERRORLOG) PURE;
     STDMETHOD(Save)(THIS_ LPPROPERTYBAG,BOOL,BOOL) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [22/37]
DECLARE_INTERFACE_ (IPersistPropertyBag2 , IPersist)
Definition at line 280 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetClassID)(THIS_ LPCLSID) PURE;
     STDMETHOD(InitNew)(THIS) PURE;
     STDMETHOD(Load)(THIS_ LPPROPERTYBAG2,LPERRORLOG) PURE;
     STDMETHOD(Save)(THIS_ LPPROPERTYBAG2,BOOL,BOOL) PURE;
     STDMETHOD(IsDirty)(THIS) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [23/37]
DECLARE_INTERFACE_ (IPersistStreamInit , IPersist)
Definition at line 306 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetClassID)(THIS_ LPCLSID) PURE;
     STDMETHOD(IsDirty)(THIS) PURE;
     STDMETHOD(Load)(THIS_ LPSTREAM) PURE;
     STDMETHOD(Save)(THIS_ LPSTREAM,BOOL) PURE;
     STDMETHOD(GetSizeMax)(THIS_ PULARGE_INTEGER) PURE;
     STDMETHOD(InitNew)(THIS) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [24/37]
DECLARE_INTERFACE_ (IPicture , IUnknown)
Definition at line 610 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(get_Handle)(THIS_ OLE_HANDLE*) PURE;
     STDMETHOD(get_hPal)(THIS_ OLE_HANDLE*) PURE;
     STDMETHOD(get_Type)(THIS_ short*) PURE;
     STDMETHOD(get_Width)(THIS_ OLE_XSIZE_HIMETRIC*) PURE;
     STDMETHOD(get_Height)(THIS_ OLE_YSIZE_HIMETRIC*) PURE;
     STDMETHOD(Render)(THIS_ HDC,long,long,long,long,OLE_XPOS_HIMETRIC,OLE_YPOS_HIMETRIC,OLE_XSIZE_HIMETRIC,OLE_YSIZE_HIMETRIC,LPCRECT) PURE;
     STDMETHOD(set_hPal)(THIS_ OLE_HANDLE) PURE;
     STDMETHOD(get_CurDC)(THIS_ HDC*) PURE;
     STDMETHOD(SelectPicture)(THIS_ HDC,HDC*,OLE_HANDLE*) PURE;
     STDMETHOD(get_KeepOriginalFormat)(THIS_ BOOL*) PURE;
     STDMETHOD(put_KeepOriginalFormat)(THIS_ BOOL) PURE;
     STDMETHOD(PictureChanged)(THIS) PURE;
     STDMETHOD(SaveAsFile)(THIS_ LPSTREAM,BOOL,LONG*) PURE;
     STDMETHOD(get_Attributes)(THIS_ PDWORD) PURE;
 };
References long(), LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [25/37]
DECLARE_INTERFACE_ (IPictureDisp , IDispatch)
Definition at line 654 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetTypeInfoCount)(THIS_ UINT*) PURE;
     STDMETHOD(GetTypeInfo)(THIS_ UINT,LCID,LPTYPEINFO*) PURE;
     STDMETHOD(GetIDsOfNames)(THIS_ REFIID,LPOLESTR*,UINT,LCID,DISPID*) PURE;
     STDMETHOD(Invoke)(THIS_ DISPID,REFIID,LCID,WORD,DISPPARAMS*,VARIANT*,EXCEPINFO*,UINT*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [26/37]
DECLARE_INTERFACE_ (IPointerInactive , IUnknown)
Definition at line 760 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetActivationPolicy)(THIS_ DWORD*) PURE;
     STDMETHOD(OnInactiveMouseMove)(THIS_ LPCRECT,LONG,LONG,DWORD) PURE;
     STDMETHOD(OnInactiveSetCursor)(THIS_ LPCRECT,LONG,LONG,DWORD,BOOL) PURE;
 };
References LONG, LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [27/37]
DECLARE_INTERFACE_ (IPropertyBag , IUnknown)
Definition at line 210 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Read)(THIS_ LPCOLESTR,LPVARIANT,LPERRORLOG) PURE;
     STDMETHOD(Write)(THIS_ LPCOLESTR,LPVARIANT) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [28/37]
DECLARE_INTERFACE_ (IPropertyBag2 , IUnknown)
Definition at line 230 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(Read)(THIS_ ULONG,PROPBAG2*,LPERRORLOG,VARIANT*,HRESULT*) PURE;
     STDMETHOD(Write)(THIS_ ULONG,PROPBAG2*,VARIANT*) PURE;
     STDMETHOD(CountProperties)(THIS_ ULONG*) PURE;
     STDMETHOD(GetPropertyInfo)(THIS_ ULONG,ULONG,PROPBAG2*,ULONG*) PURE;
     STDMETHOD(LoadObject)(THIS_ LPCOLESTR,DWORD,IUnknown*,LPERRORLOG) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [29/37]
DECLARE_INTERFACE_ (IPropertyNotifySink , IUnknown)
Definition at line 338 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(OnChanged)(THIS_ DISPID) PURE;
     STDMETHOD(OnRequestEdit)(THIS_ DISPID) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [30/37]
DECLARE_INTERFACE_ (IPropertyPage , IUnknown)
Definition at line 519 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(SetPageSite)(THIS_ LPPROPERTYPAGESITE) PURE;
     STDMETHOD(Activate)(THIS_ HWND,LPCRECT,BOOL) PURE;
     STDMETHOD(Deactivate)(THIS) PURE;
     STDMETHOD(GetPageInfo)(THIS_ LPPROPPAGEINFO) PURE;
     STDMETHOD(SetObjects)(THIS_ ULONG,LPUNKNOWN*) PURE;
     STDMETHOD(Show)(THIS_ UINT) PURE;
     STDMETHOD(Move)(THIS_ LPCRECT) PURE;
     STDMETHOD(IsPageDirty)(THIS) PURE;
     STDMETHOD(Apply)(THIS) PURE;
     STDMETHOD(Help)(THIS_ LPCOLESTR) PURE;
     STDMETHOD(TranslateAccelerator)(THIS_ LPMSG) PURE;
 };
References HWND, LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, THIS_, and TranslateAccelerator.
DECLARE_INTERFACE_() [31/37]
DECLARE_INTERFACE_ (IPropertyPage2 , IPropertyPage)
Definition at line 540 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(SetPageSite)(THIS_ LPPROPERTYPAGESITE) PURE;
     STDMETHOD(Activate)(THIS_ HWND,LPCRECT,BOOL) PURE;
     STDMETHOD(Deactivate)(THIS) PURE;
     STDMETHOD(GetPageInfo)(THIS_ LPPROPPAGEINFO) PURE;
     STDMETHOD(SetObjects)(THIS_ ULONG,LPUNKNOWN*) PURE;
     STDMETHOD(Show)(THIS_ UINT) PURE;
     STDMETHOD(Move)(THIS_ LPCRECT) PURE;
     STDMETHOD(IsPageDirty)(THIS) PURE;
     STDMETHOD(Apply)(THIS) PURE;
     STDMETHOD(Help)(THIS_ LPCOLESTR) PURE;
     STDMETHOD(TranslateAccelerator)(THIS_ LPMSG) PURE;
     STDMETHOD(EditProperty)(THIS_ DISPID) PURE;
 };
References HWND, LPCRECT, PURE, STDMETHOD, STDMETHOD_, THIS, THIS_, and TranslateAccelerator.
DECLARE_INTERFACE_() [32/37]
DECLARE_INTERFACE_ (IPropertyPageSite , IUnknown)
Definition at line 505 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(OnStatusChange)(THIS_ DWORD) PURE;
     STDMETHOD(GetLocaleID)(THIS_ LCID*) PURE;
     STDMETHOD(GetPageContainer)(THIS_ LPUNKNOWN*) PURE;
     STDMETHOD(TranslateAccelerator)(THIS_ LPMSG) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, THIS_, and TranslateAccelerator.
DECLARE_INTERFACE_() [33/37]
DECLARE_INTERFACE_ (IProvideClassInfo , IUnknown)
Definition at line 358 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetClassInfo)(THIS_ LPTYPEINFO*) PURE;
 };
References GetClassInfo, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [34/37]
DECLARE_INTERFACE_ (IProvideClassInfo2 , IProvideClassInfo)
Definition at line 369 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetClassInfo)(THIS_ LPTYPEINFO*) PURE;
     STDMETHOD(GetGUID)(THIS_ DWORD,GUID*) PURE;
 };
References GetClassInfo, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [35/37]
DECLARE_INTERFACE_ (IQuickActivate , IUnknown)
Definition at line 842 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(QuickActivate)(THIS_ QACONTAINER*,QACONTROL*) PURE;
     STDMETHOD(SetContentExtent)(THIS_ LPSIZEL) PURE;
     STDMETHOD(GetContentExtent)(THIS_ LPSIZEL) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [36/37]
DECLARE_INTERFACE_ (ISimpleFrameSite , IUnknown)
Definition at line 187 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(PreMessageFilter)(THIS_ HWND,UINT,WPARAM,LPARAM,LRESULT*,PDWORD) PURE;
     STDMETHOD(PostMessageFilter)(THIS_ HWND,UINT,WPARAM,LPARAM,LRESULT*,DWORD) PURE;
 };
References HWND, PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [37/37]
DECLARE_INTERFACE_ (ISpecifyPropertyPages , IUnknown)
Definition at line 480 of file ocidl.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,PVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(GetPages)(THIS_ CAUUID*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
Variable Documentation
IID_IAdviseSinkEx
const EXTERN_C IID IID_IAdviseSinkEx
Definition at line 739 of file ocidl.h.
IID_IClassFactory2
const EXTERN_C IID IID_IClassFactory2
Definition at line 450 of file ocidl.h.
IID_IConnectionPoint
const EXTERN_C IID IID_IConnectionPoint
Definition at line 410 of file ocidl.h.
IID_IConnectionPointContainer
const EXTERN_C IID IID_IConnectionPointContainer
Definition at line 376 of file ocidl.h.
IID_IEnumConnectionPoints
const EXTERN_C IID IID_IEnumConnectionPoints
Definition at line 388 of file ocidl.h.
IID_IEnumConnections
const EXTERN_C IID IID_IEnumConnections
Definition at line 425 of file ocidl.h.
IID_IEnumOleUndoUnits
const EXTERN_C IID IID_IEnumOleUndoUnits
Definition at line 801 of file ocidl.h.
IID_IErrorLog
const EXTERN_C IID IID_IErrorLog
Definition at line 194 of file ocidl.h.
IID_IFont
const EXTERN_C IID IID_IFont
Definition at line 557 of file ocidl.h.
IID_IFontDisp
const EXTERN_C IID IID_IFontDisp
Definition at line 591 of file ocidl.h.
IID_IObjectWithSite
const EXTERN_C IID IID_IObjectWithSite
Definition at line 688 of file ocidl.h.
IID_IOleControl
const EXTERN_C IID IID_IOleControl
Definition at line 141 of file ocidl.h.
IID_IOleControlSite
const EXTERN_C IID IID_IOleControlSite
Definition at line 152 of file ocidl.h.
IID_IOleInPlaceSiteEx
const EXTERN_C IID IID_IOleInPlaceSiteEx
Definition at line 663 of file ocidl.h.
IID_IOleInPlaceSiteWindowless
const EXTERN_C IID IID_IOleInPlaceSiteWindowless
Definition at line 700 of file ocidl.h.
IID_IOleParentUndoUnit
const EXTERN_C IID IID_IOleParentUndoUnit
Definition at line 782 of file ocidl.h.
IID_IOleUndoManager
const EXTERN_C IID IID_IOleUndoManager
Definition at line 815 of file ocidl.h.
IID_IOleUndoUnit
const EXTERN_C IID IID_IOleUndoUnit
Definition at line 768 of file ocidl.h.
IID_IPerPropertyBrowsing
const EXTERN_C IID IID_IPerPropertyBrowsing
Definition at line 486 of file ocidl.h.
IID_IPersistMemory
const EXTERN_C IID IID_IPersistMemory
Definition at line 317 of file ocidl.h.
IID_IPersistPropertyBag
const EXTERN_C IID IID_IPersistPropertyBag
Definition at line 240 of file ocidl.h.
IID_IPersistPropertyBag2
const EXTERN_C IID IID_IPersistPropertyBag2
Definition at line 265 of file ocidl.h.
IID_IPersistStreamInit
const EXTERN_C IID IID_IPersistStreamInit
Definition at line 290 of file ocidl.h.
IID_IPicture
const EXTERN_C IID IID_IPicture
Definition at line 605 of file ocidl.h.
IID_IPictureDisp
const EXTERN_C IID IID_IPictureDisp
Definition at line 629 of file ocidl.h.
IID_IPointerInactive
const EXTERN_C IID IID_IPointerInactive
Definition at line 755 of file ocidl.h.
IID_IPropertyBag
const EXTERN_C IID IID_IPropertyBag
Definition at line 205 of file ocidl.h.
IID_IPropertyBag2
const EXTERN_C IID IID_IPropertyBag2
Definition at line 217 of file ocidl.h.
IID_IPropertyNotifySink
const EXTERN_C IID IID_IPropertyNotifySink
Definition at line 333 of file ocidl.h.
IID_IPropertyPage
const EXTERN_C IID IID_IPropertyPage
Definition at line 514 of file ocidl.h.
IID_IPropertyPage2
const EXTERN_C IID IID_IPropertyPage2
Definition at line 535 of file ocidl.h.
IID_IPropertyPageSite
const EXTERN_C IID IID_IPropertyPageSite
Definition at line 500 of file ocidl.h.
IID_IProvideClassInfo
const EXTERN_C IID IID_IProvideClassInfo
Definition at line 345 of file ocidl.h.
IID_IProvideClassInfo2
const EXTERN_C IID IID_IProvideClassInfo2
Definition at line 364 of file ocidl.h.
IID_IQuickActivate
const EXTERN_C IID IID_IQuickActivate
Definition at line 837 of file ocidl.h.
IID_ISimpleFrameSite
const EXTERN_C IID IID_ISimpleFrameSite
Definition at line 169 of file ocidl.h.
IID_ISpecifyPropertyPages
const EXTERN_C IID IID_ISpecifyPropertyPages
Definition at line 475 of file ocidl.h.