ZEQ2-Lite: Source/Engine/client/cl_main.c File Reference
cl_main.c File Reference
#include "client.h"
#include <limits.h>
#include "../sys/sys_local.h"
#include "../sys/sys_loadlib.h"
Data Structures
struct serverStatus_s
Macros
#define MAX_RCON_MESSAGE 1024
#define MAX_SERVERSPERPACKET 256
Functions
static __attribute__ ((format(printf, 2, 3)))
void CL_AddReliableCommand (const char *cmd, qboolean isDisconnectCmd)
void CL_BeginDownload (const char *localName, const char *remoteName)
void CL_ChangeReliableCommand (void)
void CL_CheckForResend (void)
qboolean CL_CheckPaused (void)
void CL_CheckTimeout (void)
void CL_CheckUserinfo (void)
void CL_ClearMemory (qboolean shutdownRef)
void CL_ClearPing (int n)
void CL_ClearState (void)
void CL_Clientinfo_f (void)
static void CL_CompleteDemoName (char *args, int argNum)
static void CL_CompleteRcon (char *args, int argNum)
void CL_Configstrings_f (void)
void CL_Connect_f (void)
void CL_ConnectionlessPacket (netadr_t from, msg_t *msg)
void CL_DemoCompleted (void)
void CL_DemoFilename (int number, char *fileName)
static float CL_DemoFrameDurationSDev (void)
void CL_Disconnect (qboolean showMainMenu)
void CL_Disconnect_f (void)
void CL_DisconnectPacket (netadr_t from)
void CL_DownloadsComplete (void)
void CL_FlushMemory (void)
void CL_ForwardCommandToServer (const char *string)
void CL_ForwardToServer_f (void)
void CL_Frame (int msec)
static void CL_GenerateQKey (void)
ping_t * CL_GetFreePing (void)
void CL_GetPing (int n, char *buf, int buflen, int *pingtime)
void CL_GetPingInfo (int n, char *buf, int buflen)
int CL_GetPingQueueCount (void)
serverStatus_t * CL_GetServerStatus (netadr_t from)
void CL_GlobalServers_f (void)
void CL_Init (void)
void CL_InitDownloads (void)
void CL_InitRef (void)
void CL_InitRenderer (void)
void CL_InitServerInfo (serverInfo_t *server, netadr_t *address)
void CL_LocalServers_f (void)
void CL_MapLoading (void)
void CL_MotdPacket (netadr_t from)
void CL_NextDemo (void)
void CL_NextDownload (void)
static void CL_OldGame (void)
void CL_OpenedPK3List_f (void)
void CL_PacketEvent (netadr_t from, msg_t *msg)
void CL_Ping_f (void)
void CL_PlayDemo_f (void)
void CL_Rcon_f (void)
void CL_ReadDemoMessage (void)
void CL_Reconnect_f (void)
void CL_Record_f (void)
void CL_ReferencedPK3List_f (void)
void * CL_RefMalloc (int size)
void CL_RequestMotd (void)
void CL_ResetPureClientAtServer (void)
int CL_ScaledMilliseconds (void)
void CL_SendPureChecksums (void)
void CL_ServerInfoPacket (netadr_t from, msg_t *msg)
void CL_ServersResponsePacket (const netadr_t *from, msg_t *msg, qboolean extended)
int CL_ServerStatus (char *serverAddress, char *serverStatusString, int maxLen)
void CL_ServerStatus_f (void)
void CL_ServerStatusResponse (netadr_t from, msg_t *msg)
void CL_SetModel_f (void)
static void CL_SetServerInfo (serverInfo_t *server, const char *info, int ping)
static void CL_SetServerInfoByAddress (netadr_t from, const char *info, int ping)
void CL_ShowIP_f (void)
void CL_Shutdown (char *finalmsg, qboolean disconnect, qboolean quit)
void CL_ShutdownAll (qboolean shutdownRef)
void CL_ShutdownRef (void)
void CL_Snd_Restart_f (void)
void CL_Snd_Shutdown (void)
void CL_StartDemoLoop (void)
void CL_StartHunkUsers (qboolean rendererOnly)
void CL_StopRecord_f (void)
void CL_StopVideo_f (void)
static void CL_UpdateGUID (const char *prefix, int prefix_len)
qboolean CL_UpdateVisiblePings_f (int source)
void CL_Vid_Restart_f (void)
void CL_Video_f (void)
static int CL_WalkDemoExt (char *arg, char *name, int *demofile)
void CL_WriteDemoMessage (msg_t *msg, int headerBytes)
Variables
vm_t * cgvm
clientActive_t cl
cvar_t * cl_activeAction
cvar_t * cl_allowDownload
cvar_t * cl_autoRecordDemo
cvar_t * cl_aviFrameRate
cvar_t * cl_aviMotionJpeg
cvar_t * cl_consoleKeys
cvar_t * cl_conXOffset
cvar_t * cl_debugMove
cvar_t * cl_forceavidemo
cvar_t * cl_freelook
cvar_t * cl_freezeDemo
cvar_t * cl_guidServerUniq
cvar_t * cl_inGameVideo
cvar_t * cl_lanForcePackets
cvar_t * cl_maxpackets
cvar_t * cl_motdString
cvar_t * cl_mouseAccel
cvar_t * cl_mouseAccelOffset
cvar_t * cl_mouseAccelStyle
cvar_t * cl_nodelta
cvar_t * cl_noprint
cvar_t * cl_packetdup
ping_t cl_pinglist [MAX_PINGREQUESTS]
cvar_t * cl_sensitivity
serverStatus_t cl_serverStatusList [MAX_SERVERSTATUSREQUESTS]
cvar_t * cl_serverStatusResendTime
cvar_t * cl_showMouseRate
cvar_t * cl_shownet
cvar_t * cl_showSend
cvar_t * cl_showTimeDelta
cvar_t * cl_timedemo
cvar_t * cl_timedemoLog
cvar_t * cl_timeNudge
cvar_t * cl_timeout
cvar_t * cl_trn
clientConnection_t clc
clientStatic_t cls
static char demoName [MAX_QPATH]
cvar_t * j_forward
cvar_t * j_forward_axis
cvar_t * j_pitch
cvar_t * j_pitch_axis
cvar_t * j_side
cvar_t * j_side_axis
cvar_t * j_up
cvar_t * j_up_axis
cvar_t * j_yaw
cvar_t * j_yaw_axis
cvar_t * m_filter
cvar_t * m_forward
cvar_t * m_pitch
cvar_t * m_side
cvar_t * m_yaw
static int noGameRestart = qfalse
cvar_t * rcon_client_password
cvar_t * rconAddress
refexport_t re
int serverStatusCount
Macro Definition Documentation
MAX_RCON_MESSAGE
#define MAX_RCON_MESSAGE 1024
Definition at line 1686 of file cl_main.c.
MAX_SERVERSPERPACKET
#define MAX_SERVERSPERPACKET 256
Definition at line 2353 of file cl_main.c.
Function Documentation
__attribute__()
static __attribute__ ((format(printf, 2, 3))) static
Definition at line 2957 of file cl_main.c.
{
     va_list     argptr;
     char        msg[MAXPRINTMSG];
     va_start (argptr,fmt);
     Q_vsnprintf (msg, sizeof(msg), fmt, argptr);
     va_end (argptr);
     if ( print_level == PRINT_ALL ) {
         Com_Printf ("%s", msg);
     } else if ( print_level == PRINT_WARNING ) {
         Com_Printf (S_COLOR_YELLOW "%s", msg);      // yellow
     } else if ( print_level == PRINT_DEVELOPER ) {
         Com_DPrintf (S_COLOR_RED "%s", msg);        // red
     }
 }
References Com_DPrintf(), Com_Printf(), fmt, MAXPRINTMSG, PRINT_ALL, PRINT_DEVELOPER, PRINT_WARNING, Q_vsnprintf, S_COLOR_RED, and S_COLOR_YELLOW.
CL_AddReliableCommand()
void CL_AddReliableCommand (const char * cmd, qboolean isDisconnectCmd)
Definition at line 556 of file cl_main.c.
 {
     int unacknowledged = clc.reliableSequence - clc.reliableAcknowledge;
     // if we would be losing an old command that hasn't been acknowledged,
     // we must drop the connection
     // also leave one slot open for the disconnect command in this case.
     if ((isDisconnectCmd && unacknowledged > MAX_RELIABLE_COMMANDS) ||
         (!isDisconnectCmd && unacknowledged >= MAX_RELIABLE_COMMANDS))
     {
         if(com_errorEntered)
             return;
         else
             Com_Error(ERR_DROP, "Client command overflow");
     }
     Q_strncpyz(clc.reliableCommands[++clc.reliableSequence & (MAX_RELIABLE_COMMANDS - 1)],
            cmd, sizeof(*clc.reliableCommands));
 }
References clc, Com_Error(), com_errorEntered, ERR_DROP, MAX_RELIABLE_COMMANDS, Q_strncpyz(), clientConnection_t::reliableAcknowledge, clientConnection_t::reliableCommands, and clientConnection_t::reliableSequence.
Referenced by CL_BeginDownload(), CL_CgameSystemCalls(), CL_CheckUserinfo(), CL_Disconnect(), CL_DownloadsComplete(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_ParseDownload(), CL_ResetPureClientAtServer(), CL_SendPureChecksums(), and Message_Key().
CL_BeginDownload()
void CL_BeginDownload (const char * localName, const char * remoteName)
Definition at line 2022 of file cl_main.c.
{
     Com_DPrintf("***** CL_BeginDownload *****\n"
                 "Localname: %s\n"
                 "Remotename: %s\n"
                 "****************************\n", localName, remoteName);
     Q_strncpyz ( clc.downloadName, localName, sizeof(clc.downloadName) );
     Com_sprintf( clc.downloadTempName, sizeof(clc.downloadTempName), "%s.tmp", localName );
     // Set so UI gets access to it
     Cvar_Set( "cl_downloadName", remoteName );
     Cvar_Set( "cl_downloadSize", "0" );
     Cvar_Set( "cl_downloadCount", "0" );
     Cvar_SetValue( "cl_downloadTime", cls.realtime );
     clc.downloadBlock = 0; // Starting new file
     clc.downloadCount = 0;
     CL_AddReliableCommand(va("download %s", remoteName), qfalse);
 }
References CL_AddReliableCommand(), clc, cls, Com_DPrintf(), Com_sprintf(), Cvar_Set(), Cvar_SetValue(), clientConnection_t::downloadBlock, clientConnection_t::downloadCount, clientConnection_t::downloadName, clientConnection_t::downloadTempName, Q_strncpyz(), qfalse, clientStatic_t::realtime, and va().
Referenced by CL_NextDownload().
CL_ChangeReliableCommand()
void CL_ChangeReliableCommand (void)
Definition at line 582 of file cl_main.c.
{
     int index, l;
     index = clc.reliableSequence & ( MAX_RELIABLE_COMMANDS - 1 );
     l = strlen(clc.reliableCommands[ index ]);
     if ( l >= MAX_STRING_CHARS - 1 ) {
         l = MAX_STRING_CHARS - 2;
     }
     clc.reliableCommands[ index ][ l ] = '\n';
     clc.reliableCommands[ index ][ l+1 ] = '\0';
 }
References clc, MAX_RELIABLE_COMMANDS, MAX_STRING_CHARS, clientConnection_t::reliableCommands, and clientConnection_t::reliableSequence.
CL_CheckForResend()
void CL_CheckForResend (void)
Definition at line 2196 of file cl_main.c.
{
     int     port, i;
     char    info[MAX_INFO_STRING];
     char    data[MAX_INFO_STRING];
     // don't send anything if playing back a demo
     if ( clc.demoplaying ) {
         return;
     }
     // resend if we haven't gotten a reply yet
     if ( clc.state != CA_CONNECTING && clc.state != CA_CHALLENGING ) {
         return;
     }
     if ( cls.realtime - clc.connectTime < RETRANSMIT_TIMEOUT ) {
         return;
     }
     clc.connectTime = cls.realtime; // for retransmit requests
     clc.connectPacketCount++;
     switch ( clc.state ) {
     case CA_CONNECTING:
         // The challenge request shall be followed by a client challenge so no malicious server can hijack this connection.
         // Add the gamename so the server knows we're running the correct game or can reject the client
         // with a meaningful message
         Com_sprintf(data, sizeof(data), "getchallenge %d %s", clc.challenge, com_gamename->string);
         NET_OutOfBandPrint(NS_CLIENT, clc.serverAddress, "%s", data);
         break;
     case CA_CHALLENGING:
         // sending back the challenge
         port = Cvar_VariableValue ("net_qport");
         Q_strncpyz( info, Cvar_InfoString( CVAR_USERINFO ), sizeof( info ) );
 #ifdef LEGACY_PROTOCOL
         if(com_legacyprotocol->integer == com_protocol->integer)
             clc.compat = qtrue;
         if(clc.compat)
             Info_SetValueForKey(info, "protocol", va("%i", com_legacyprotocol->integer));
         else
 #endif
             Info_SetValueForKey(info, "protocol", va("%i", com_protocol->integer));
         Info_SetValueForKey( info, "qport", va("%i", port ) );
         Info_SetValueForKey( info, "challenge", va("%i", clc.challenge ) );
         strcpy(data, "connect ");
     // TTimo adding " " around the userinfo string to avoid truncated userinfo on the server
     //   (Com_TokenizeString tokenizes around spaces)
     data[8] = '"';
         for(i=0;i<strlen(info);i++) {
             data[9+i] = info[i];    // + (clc.challenge)&0x3;
         }
     data[9+i] = '"';
         data[10+i] = 0;
     // NOTE TTimo don't forget to set the right data length!
         NET_OutOfBandData( NS_CLIENT, clc.serverAddress, (byte *) &data[0], i+10 );
         // the most current userinfo has been sent, so watch for any
         // newer changes to userinfo variables
         cvar_modifiedFlags &= ~CVAR_USERINFO;
         break;
     default:
         Com_Error( ERR_FATAL, "CL_CheckForResend: bad clc.state" );
     }
 }
References CA_CHALLENGING, CA_CONNECTING, clientConnection_t::challenge, clc, cls, Com_Error(), com_gamename, com_protocol, Com_sprintf(), clientConnection_t::connectPacketCount, clientConnection_t::connectTime, Cvar_InfoString(), cvar_modifiedFlags, CVAR_USERINFO, Cvar_VariableValue(), clientConnection_t::demoplaying, ERR_FATAL, info, Info_SetValueForKey(), MAX_INFO_STRING, NET_OutOfBandData(), NET_OutOfBandPrint(), NS_CLIENT, Q_strncpyz(), qtrue, clientStatic_t::realtime, RETRANSMIT_TIMEOUT, clientConnection_t::serverAddress, clientConnection_t::state, and va().
Referenced by CL_Frame(), and CL_MapLoading().
CL_CheckPaused()
qboolean CL_CheckPaused (void)
Definition at line 2771 of file cl_main.c.
 {
     // if cl_paused->modified is set, the cvar has only been changed in
     // this frame. Keep paused in this frame to ensure the server doesn't
     // lag behind.
     if(cl_paused->integer || cl_paused->modified)
         return qtrue;
     return qfalse;
 }
References cl_paused, qfalse, and qtrue.
Referenced by CL_CheckTimeout(), CL_CheckUserinfo(), and CL_SetCGameTime().
CL_CheckTimeout()
void CL_CheckTimeout (void)
Definition at line 2748 of file cl_main.c.
{
     //
     // check timeout
     //
     if ( ( !CL_CheckPaused() || !sv_paused->integer )
         && clc.state >= CA_CONNECTED && clc.state != CA_CINEMATIC
         && cls.realtime - clc.lastPacketTime > cl_timeout->value*1000) {
         if (++cl.timeoutcount > 5) {    // timeoutcount saves debugger
             Com_Printf ("\nServer connection timed out.\n");
             CL_Disconnect( qtrue );
             return;
         }
     } else {
         cl.timeoutcount = 0;
     }
 }
References CA_CINEMATIC, CA_CONNECTED, cl, CL_CheckPaused(), CL_Disconnect(), cl_timeout, clc, cls, Com_Printf(), clientConnection_t::lastPacketTime, qtrue, clientStatic_t::realtime, clientConnection_t::state, sv_paused, and clientActive_t::timeoutcount.
Referenced by CL_Frame().
CL_CheckUserinfo()
void CL_CheckUserinfo (void)
Definition at line 2790 of file cl_main.c.
{
     // don't add reliable commands when not yet connected
     if(clc.state < CA_CONNECTED)
         return;
     // don't overflow the reliable command buffer when paused
     if(CL_CheckPaused())
         return;
     // send a reliable userinfo update if needed
     if(cvar_modifiedFlags & CVAR_USERINFO)
     {
         cvar_modifiedFlags &= ~CVAR_USERINFO;
         CL_AddReliableCommand(va("userinfo \"%s\"", Cvar_InfoString( CVAR_USERINFO ) ), qfalse);
     }
 }
References CA_CONNECTED, CL_AddReliableCommand(), CL_CheckPaused(), clc, Cvar_InfoString(), cvar_modifiedFlags, CVAR_USERINFO, qfalse, clientConnection_t::state, and va().
Referenced by CL_Frame().
CL_ClearMemory()
void CL_ClearMemory (qboolean shutdownRef)
Definition at line 1229 of file cl_main.c.
 {
     // shutdown all the client stuff
     CL_ShutdownAll(shutdownRef);
     // if not running a server clear the whole hunk
     if ( !com_sv_running->integer ) {
         // clear the whole hunk
         Hunk_Clear();
         // clear collision map data
         CM_ClearMap();
     }
     else {
         // clear all the client data on the hunk
         Hunk_ClearToMark();
     }
 }
References CL_ShutdownAll(), CM_ClearMap(), com_sv_running, Hunk_Clear(), and Hunk_ClearToMark().
Referenced by CL_FlushMemory(), and CL_Shutdown().
CL_ClearPing()
void CL_ClearPing (int n)
Definition at line 4136 of file cl_main.c.
 {
     if (n < 0 || n >= MAX_PINGREQUESTS)
         return;
     cl_pinglist[n].adr.port = 0;
 }
References ping_t::adr, cl_pinglist, MAX_PINGREQUESTS, and netadr_t::port.
Referenced by CL_UpdateVisiblePings_f(), and LAN_ClearPing().
CL_ClearState()
void CL_ClearState (void)
Definition at line 1316 of file cl_main.c.
{
 //  S_StopAllSounds();
     Com_Memset( &cl, 0, sizeof( cl ) );
 }
References cl, and Com_Memset.
Referenced by CL_Disconnect(), CL_Init(), and CL_ParseGamestate().
CL_Clientinfo_f()
void CL_Clientinfo_f (void)
Definition at line 1929 of file cl_main.c.
{
     Com_Printf( "--------- Client Information ---------\n" );
     Com_Printf( "state: %i\n", clc.state );
     Com_Printf( "Server: %s\n", clc.servername );
     Com_Printf ("User info settings:\n");
     Info_Print( Cvar_InfoString( CVAR_USERINFO ) );
     Com_Printf( "--------------------------------------\n" );
 }
References clc, Com_Printf(), Cvar_InfoString(), CVAR_USERINFO, Info_Print(), clientConnection_t::servername, and clientConnection_t::state.
Referenced by CL_Init().
CL_CompleteDemoName()
static void CL_CompleteDemoName (char * args, int argNum) static
Definition at line 1039 of file cl_main.c.
 {
     if( argNum == 2 )
     {
         char demoExt[ 16 ];
         Com_sprintf(demoExt, sizeof(demoExt), ".%s%d", DEMOEXT, com_protocol->integer);
         Field_CompleteFilename( "demos", demoExt, qtrue, qtrue );
     }
 }
References com_protocol, Com_sprintf(), DEMOEXT, Field_CompleteFilename(), and qtrue.
Referenced by CL_Init().
CL_CompleteRcon()
static void CL_CompleteRcon (char * args, int argNum) static
Definition at line 1693 of file cl_main.c.
 {
     if( argNum == 2 )
     {
         // Skip "rcon "
         char *p = Com_SkipTokens( args, 1, " " );
         if( p > args )
             Field_CompleteCommand( p, qtrue, qtrue );
     }
 }
References args, Com_SkipTokens(), Field_CompleteCommand(), and qtrue.
Referenced by CL_Init().
CL_Configstrings_f()
void CL_Configstrings_f (void)
Definition at line 1906 of file cl_main.c.
{
     int     i;
     int     ofs;
     if ( clc.state != CA_ACTIVE ) {
         Com_Printf( "Not connected to a server.\n");
         return;
     }
     for ( i = 0 ; i < MAX_CONFIGSTRINGS ; i++ ) {
         ofs = cl.gameState.stringOffsets[ i ];
         if ( !ofs ) {
             continue;
         }
         Com_Printf( "%4i: %s\n", i, cl.gameState.stringData + ofs );
     }
 }
References CA_ACTIVE, cl, clc, Com_Printf(), clientActive_t::gameState, MAX_CONFIGSTRINGS, clientConnection_t::state, gameState_t::stringData, and gameState_t::stringOffsets.
Referenced by CL_Init().
CL_Connect_f()
void CL_Connect_f (void)
Definition at line 1600 of file cl_main.c.
{
     char    *server;
     const char  *serverString;
     int argc = Cmd_Argc();
     netadrtype_t family = NA_UNSPEC;
     if ( argc != 2 && argc != 3 ) {
         Com_Printf( "usage: connect [-4|-6] server\n");
         return;
     }
     if(argc == 2)
         server = Cmd_Argv(1);
     else
     {
         if(!strcmp(Cmd_Argv(1), "-4"))
             family = NA_IP;
         else if(!strcmp(Cmd_Argv(1), "-6"))
             family = NA_IP6;
         else
             Com_Printf( "warning: only -4 or -6 as address type understood.\n");
         server = Cmd_Argv(2);
     }
     Cvar_Set("ui_singlePlayerActive", "0");
     // fire a message off to the motd server
     CL_RequestMotd();
     // clear any previous "server full" type messages
     clc.serverMessage[0] = 0;
     if ( com_sv_running->integer && !strcmp( server, "localhost" ) ) {
         // if running a local server, kill it
         SV_Shutdown( "Server quit" );
     }
     // make sure a local server is killed
     Cvar_Set( "sv_killserver", "1" );
     SV_Frame( 0 );
     noGameRestart = qtrue;
     CL_Disconnect( qtrue );
     Con_Close();
     Q_strncpyz( clc.servername, server, sizeof(clc.servername) );
     if (!NET_StringToAdr(clc.servername, &clc.serverAddress, family) ) {
         Com_Printf ("Bad server address\n");
         clc.state = CA_DISCONNECTED;
         return;
     }
     if (clc.serverAddress.port == 0) {
         clc.serverAddress.port = BigShort( PORT_SERVER );
     }
     serverString = NET_AdrToStringwPort(clc.serverAddress);
     Com_Printf( "%s resolved to %s\n", clc.servername, serverString);
     if( cl_guidServerUniq->integer )
         CL_UpdateGUID( serverString, strlen( serverString ) );
     else
         CL_UpdateGUID( NULL, 0 );
     // if we aren't playing on a lan, we need to authenticate
     // with the cd key
     if(NET_IsLocalAddress(clc.serverAddress))
         clc.state = CA_CHALLENGING;
     else
     {
         clc.state = CA_CONNECTING;
         // Set a client challenge number that ideally is mirrored back by the server.
         clc.challenge = ((rand() << 16) ^ rand()) ^ Com_Milliseconds();
     }
     Key_SetCatcher( 0 );
     clc.connectTime = -99999;   // CL_CheckForResend() will fire immediately
     clc.connectPacketCount = 0;
     // server connection string
     Cvar_Set( "cl_currentServerAddress", server );
 }
References CA_CHALLENGING, CA_CONNECTING, CA_DISCONNECTED, clientConnection_t::challenge, CL_Disconnect(), cl_guidServerUniq, CL_RequestMotd(), CL_UpdateGUID(), clc, Cmd_Argc(), Cmd_Argv(), Com_Milliseconds(), Com_Printf(), com_sv_running, Con_Close(), clientConnection_t::connectPacketCount, clientConnection_t::connectTime, Cvar_Set(), Key_SetCatcher(), NA_IP, NA_IP6, NA_UNSPEC, NET_AdrToStringwPort(), NET_IsLocalAddress(), NET_StringToAdr(), noGameRestart, NULL, netadr_t::port, PORT_SERVER, Q_strncpyz(), qtrue, clientConnection_t::serverAddress, clientConnection_t::serverMessage, clientConnection_t::servername, clientConnection_t::state, SV_Frame(), and SV_Shutdown().
Referenced by CL_Init().
CL_ConnectionlessPacket()
void CL_ConnectionlessPacket (netadr_t from, msg_t * msg)
Definition at line 2483 of file cl_main.c.
{
     char    *s;
     char    *c;
     int challenge = 0;
     MSG_BeginReadingOOB( msg );
     MSG_ReadLong( msg );    // skip the -1
     s = MSG_ReadStringLine( msg );
     Cmd_TokenizeString( s );
     c = Cmd_Argv(0);
     Com_DPrintf ("CL packet %s: %s\n", NET_AdrToStringwPort(from), c);
     // challenge from the server we are connecting to
     if (!Q_stricmp(c, "challengeResponse"))
     {
         char *strver;
         int ver;
         if (clc.state != CA_CONNECTING)
         {
             Com_DPrintf("Unwanted challenge response received. Ignored.\n");
             return;
         }
         c = Cmd_Argv(2);
         if(*c)
             challenge = atoi(c);
         strver = Cmd_Argv(3);
         if(*strver)
         {
             ver = atoi(strver);
             if(ver != com_protocol->integer)
             {
 #ifdef LEGACY_PROTOCOL
                 if(com_legacyprotocol->integer > 0)
                 {
                     // Server is ioq3 but has a different protocol than we do.
                     // Fall back to idq3 protocol.
                     clc.compat = qtrue;
                     Com_Printf(S_COLOR_YELLOW "Warning: Server reports protocol version %d, "
                            "we have %d. Trying legacy protocol %d.\n",
                            ver, com_protocol->integer, com_legacyprotocol->integer);
                 }
                 else
 #endif
                 {
                     Com_Printf(S_COLOR_YELLOW "Warning: Server reports protocol version %d, we have %d. "
                            "Trying anyways.\n", ver, com_protocol->integer);
                 }
             }
         }
 #ifdef LEGACY_PROTOCOL
         else
             clc.compat = qtrue;
         if(clc.compat)
         {
             if(!NET_CompareAdr(from, clc.serverAddress))
             {
                 // This challenge response is not coming from the expected address.
                 // Check whether we have a matching client challenge to prevent
                 // connection hi-jacking.
                 if(!*c || challenge != clc.challenge)
                 {
                     Com_DPrintf("Challenge response received from unexpected source. Ignored.\n");
                     return;
                 }
             }
         }
         else
 #endif
         {
             if(!*c || challenge != clc.challenge)
             {
                 Com_Printf("Bad challenge for challengeResponse. Ignored.\n");
                 return;
             }
         }
         // start sending challenge response instead of challenge request packets
         clc.challenge = atoi(Cmd_Argv(1));
         clc.state = CA_CHALLENGING;
         clc.connectPacketCount = 0;
         clc.connectTime = -99999;
         // take this address as the new server address.  This allows
         // a server proxy to hand off connections to multiple servers
         clc.serverAddress = from;
         Com_DPrintf ("challengeResponse: %d\n", clc.challenge);
         return;
     }
     // server connection
     if ( !Q_stricmp(c, "connectResponse") ) {
         if ( clc.state >= CA_CONNECTED ) {
             Com_Printf ("Dup connect received. Ignored.\n");
             return;
         }
         if ( clc.state != CA_CHALLENGING ) {
             Com_Printf ("connectResponse packet while not connecting. Ignored.\n");
             return;
         }
         if ( !NET_CompareAdr( from, clc.serverAddress ) ) {
             Com_Printf( "connectResponse from wrong address. Ignored.\n" );
             return;
         }
 #ifdef LEGACY_PROTOCOL
         if(!clc.compat)
 #endif
         {
             c = Cmd_Argv(1);
             if(*c)
                 challenge = atoi(c);
             else
             {
                 Com_Printf("Bad connectResponse received. Ignored.\n");
                 return;
             }
             if(challenge != clc.challenge)
             {
                 Com_Printf("ConnectResponse with bad challenge received. Ignored.\n");
                 return;
             }
         }
 #ifdef LEGACY_PROTOCOL
         Netchan_Setup(NS_CLIENT, &clc.netchan, from, Cvar_VariableValue("net_qport"),
                   clc.challenge, clc.compat);
 #else
         Netchan_Setup(NS_CLIENT, &clc.netchan, from, Cvar_VariableValue("net_qport"),
                   clc.challenge, qfalse);
 #endif
         clc.state = CA_CONNECTED;
         clc.lastPacketSentTime = -9999;     // send first packet immediately
         return;
     }
     // server responding to an info broadcast
     if ( !Q_stricmp(c, "infoResponse") ) {
         CL_ServerInfoPacket( from, msg );
         return;
     }
     // server responding to a get playerlist
     if ( !Q_stricmp(c, "statusResponse") ) {
         CL_ServerStatusResponse( from, msg );
         return;
     }
     // echo request from server
     if ( !Q_stricmp(c, "echo") ) {
         NET_OutOfBandPrint( NS_CLIENT, from, "%s", Cmd_Argv(1) );
         return;
     }
     // global MOTD from id
     if ( !Q_stricmp(c, "motd") ) {
         CL_MotdPacket( from );
         return;
     }
     // echo request from server
     if(!Q_stricmp(c, "print")){
         s = MSG_ReadString( msg );
         Q_strncpyz( clc.serverMessage, s, sizeof( clc.serverMessage ) );
         Com_Printf( "%s", s );
         return;
     }
     // list of servers sent back by a master server (classic)
     if ( !Q_strncmp(c, "getserversResponse", 18) ) {
         CL_ServersResponsePacket( &from, msg, qfalse );
         return;
     }
     // list of servers sent back by a master server (extended)
     if ( !Q_strncmp(c, "getserversExtResponse", 21) ) {
         CL_ServersResponsePacket( &from, msg, qtrue );
         return;
     }
     Com_DPrintf ("Unknown connectionless packet command.\n");
 }
References CA_CHALLENGING, CA_CONNECTED, CA_CONNECTING, clientConnection_t::challenge, CL_MotdPacket(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_ServerStatusResponse(), clc, Cmd_Argv(), Cmd_TokenizeString(), Com_DPrintf(), Com_Printf(), com_protocol, clientConnection_t::connectPacketCount, clientConnection_t::connectTime, Cvar_VariableValue(), clientConnection_t::lastPacketSentTime, MSG_BeginReadingOOB(), MSG_ReadLong(), MSG_ReadString(), MSG_ReadStringLine(), NET_AdrToStringwPort(), NET_CompareAdr(), NET_OutOfBandPrint(), clientConnection_t::netchan, Netchan_Setup(), NS_CLIENT, Q_stricmp(), Q_strncmp(), Q_strncpyz(), qfalse, qtrue, S_COLOR_YELLOW, clientConnection_t::serverAddress, clientConnection_t::serverMessage, and clientConnection_t::state.
Referenced by CL_PacketEvent().
CL_DemoCompleted()
void CL_DemoCompleted (void)
Definition at line 858 of file cl_main.c.
 {
     char buffer[ MAX_STRING_CHARS ];
     if( cl_timedemo && cl_timedemo->integer )
     {
         int time;
         time = Sys_Milliseconds() - clc.timeDemoStart;
         if( time > 0 )
         {
             // Millisecond times are frame durations:
             // minimum/average/maximum/std deviation
             Com_sprintf( buffer, sizeof( buffer ),
                     "%i frames %3.1f seconds %3.1f fps %d.0/%.1f/%d.0/%.1f ms\n",
                     clc.timeDemoFrames,
                     time/1000.0,
                     clc.timeDemoFrames*1000.0 / time,
                     clc.timeDemoMinDuration,
                     time / (float)clc.timeDemoFrames,
                     clc.timeDemoMaxDuration,
                     CL_DemoFrameDurationSDev( ) );
             Com_Printf( "%s", buffer );
             // Write a log of all the frame durations
             if( cl_timedemoLog && strlen( cl_timedemoLog->string ) > 0 )
             {
                 int i;
                 int numFrames;
                 fileHandle_t f;
                 if( ( clc.timeDemoFrames - 1 ) > MAX_TIMEDEMO_DURATIONS )
                     numFrames = MAX_TIMEDEMO_DURATIONS;
                 else
                     numFrames = clc.timeDemoFrames - 1;
                 f = FS_FOpenFileWrite( cl_timedemoLog->string );
                 if( f )
                 {
                     FS_Printf( f, "# %s", buffer );
                     for( i = 0; i < numFrames; i++ )
                         FS_Printf( f, "%d\n", clc.timeDemoDurations[ i ] );
                     FS_FCloseFile( f );
                     Com_Printf( "%s written\n", cl_timedemoLog->string );
                 }
                 else
                 {
                     Com_Printf( "Couldn't open %s for writing\n",
                             cl_timedemoLog->string );
                 }
             }
         }
     }
     CL_Disconnect( qtrue );
     CL_NextDemo();
 }
References CL_DemoFrameDurationSDev(), CL_Disconnect(), CL_NextDemo(), cl_timedemo, cl_timedemoLog, clc, Com_Printf(), Com_sprintf(), FS_FCloseFile(), FS_FOpenFileWrite(), FS_Printf(), MAX_STRING_CHARS, MAX_TIMEDEMO_DURATIONS, qtrue, Sys_Milliseconds(), clientConnection_t::timeDemoDurations, clientConnection_t::timeDemoFrames, clientConnection_t::timeDemoMaxDuration, clientConnection_t::timeDemoMinDuration, and clientConnection_t::timeDemoStart.
Referenced by CL_ReadDemoMessage().
CL_DemoFilename()
void CL_DemoFilename (int number, char * fileName)
Definition at line 656 of file cl_main.c.
{
     int     a,b,c,d;
     if(number < 0 || number > 9999)
         number = 9999;
     a = number / 1000;
     number -= a*1000;
     b = number / 100;
     number -= b*100;
     c = number / 10;
     number -= c*10;
     d = number;
     Com_sprintf( fileName, MAX_OSPATH, "demo%i%i%i%i"
         , a, b, c, d );
 }
References Com_sprintf(), and MAX_OSPATH.
Referenced by CL_Record_f().
CL_DemoFrameDurationSDev()
static float CL_DemoFrameDurationSDev (void) static
Definition at line 826 of file cl_main.c.
 {
     int i;
     int numFrames;
     float mean = 0.0f;
     float variance = 0.0f;
     if( ( clc.timeDemoFrames - 1 ) > MAX_TIMEDEMO_DURATIONS )
         numFrames = MAX_TIMEDEMO_DURATIONS;
     else
         numFrames = clc.timeDemoFrames - 1;
     for( i = 0; i < numFrames; i++ )
         mean += clc.timeDemoDurations[ i ];
     mean /= numFrames;
     for( i = 0; i < numFrames; i++ )
     {
         float x = clc.timeDemoDurations[ i ];
         variance += ( ( x - mean ) * ( x - mean ) );
     }
     variance /= numFrames;
     return sqrt( variance );
 }
References clc, MAX_TIMEDEMO_DURATIONS, clientConnection_t::timeDemoDurations, and clientConnection_t::timeDemoFrames.
Referenced by CL_DemoCompleted().
CL_Disconnect()
void CL_Disconnect (qboolean showMainMenu)
Definition at line 1366 of file cl_main.c.
{
     if ( !com_cl_running || !com_cl_running->integer ) {
         return;
     }
     // shutting down the client so enter full screen ui mode
     Cvar_Set("r_uiFullScreen", "1");
     if ( clc.demorecording ) {
         CL_StopRecord_f ();
     }
     if (clc.download) {
         FS_FCloseFile( clc.download );
         clc.download = 0;
     }
     *clc.downloadTempName = *clc.downloadName = 0;
     Cvar_Set( "cl_downloadName", "" );
 #ifdef USE_MUMBLE
     if (cl_useMumble->integer && mumble_islinked()) {
         Com_Printf("Mumble: Unlinking from Mumble application\n");
         mumble_unlink();
     }
 #endif
 #ifdef USE_VOIP
     if (cl_voipSend->integer) {
         int tmp = cl_voipUseVAD->integer;
         cl_voipUseVAD->integer = 0;  // disable this for a moment.
         clc.voipOutgoingDataSize = 0;  // dump any pending VoIP transmission.
         Cvar_Set("cl_voipSend", "0");
         CL_CaptureVoip();  // clean up any state...
         cl_voipUseVAD->integer = tmp;
     }
     if (clc.speexInitialized) {
         int i;
         speex_bits_destroy(&clc.speexEncoderBits);
         speex_encoder_destroy(clc.speexEncoder);
         speex_preprocess_state_destroy(clc.speexPreprocessor);
         for (i = 0; i < MAX_CLIENTS; i++) {
             speex_bits_destroy(&clc.speexDecoderBits[i]);
             speex_decoder_destroy(clc.speexDecoder[i]);
         }
     }
     Cmd_RemoveCommand ("voip");
 #endif
     if ( clc.demofile ) {
         FS_FCloseFile( clc.demofile );
         clc.demofile = 0;
     }
     if ( uivm && showMainMenu ) {
         VM_Call( uivm, UI_SET_ACTIVE_MENU, UIMENU_NONE );
     }
     SCR_StopCinematic ();
     S_ClearSoundBuffer();
     // send a disconnect message to the server
     // send it a few times in case one is dropped
     if ( clc.state >= CA_CONNECTED ) {
         CL_AddReliableCommand("disconnect", qtrue);
         CL_WritePacket();
         CL_WritePacket();
         CL_WritePacket();
     }
     // Remove pure paks
     FS_PureServerSetLoadedPaks("", "");
     CL_ClearState ();
     // wipe the client connection
     Com_Memset( &clc, 0, sizeof( clc ) );
     clc.state = CA_DISCONNECTED;
     // allow cheats locally
     Cvar_Set( "sv_cheats", "1" );
     // not connected to a pure server anymore
     cl_connectedToPureServer = qfalse;
 #ifdef USE_VOIP
     // not connected to voip server anymore.
     clc.voipEnabled = qfalse;
 #endif
     // Stop recording any video
     if( CL_VideoRecording( ) ) {
         // Finish rendering current frame
         SCR_UpdateScreen( );
         CL_CloseAVI( );
     }
     CL_UpdateGUID( NULL, 0 );
     if(!noGameRestart)
         CL_OldGame();
     else
         noGameRestart = qfalse;
 }
Referenced by CL_CheckTimeout(), CL_Connect_f(), CL_DemoCompleted(), CL_DisconnectPacket(), CL_MapLoading(), CL_PlayDemo_f(), CL_Shutdown(), Com_Error(), Com_GameRestart(), and SV_Shutdown().
CL_Disconnect_f()
void CL_Disconnect_f (void)
Definition at line 1570 of file cl_main.c.
{
     SCR_StopCinematic();
     Cvar_Set("ui_singlePlayerActive", "0");
     if ( clc.state != CA_DISCONNECTED && clc.state != CA_CINEMATIC ) {
         Com_Error (ERR_DISCONNECT, "Disconnected from server");
     }
 }
References CA_CINEMATIC, CA_DISCONNECTED, clc, Com_Error(), Cvar_Set(), ERR_DISCONNECT, SCR_StopCinematic(), and clientConnection_t::state.
Referenced by CL_Init(), and CL_KeyDownEvent().
CL_DisconnectPacket()
void CL_DisconnectPacket (netadr_t from)
Definition at line 2280 of file cl_main.c.
{
     if ( clc.state < CA_CONNECTING ) {
         return;
     }
     // if not from our server, ignore it
     if ( !NET_CompareAdr( from, clc.netchan.remoteAddress ) ) {
         return;
     }
     // if we have received packets within three seconds, ignore it
     // (it might be a malicious spoof)
     if ( cls.realtime - clc.lastPacketTime < 3000 ) {
         return;
     }
     // drop the connection
     Com_Printf( "Server disconnected for unknown reason\n" );
     Cvar_Set("com_errorMessage", "Server disconnected for unknown reason\n" );
     CL_Disconnect( qtrue );
 }
References CA_CONNECTING, CL_Disconnect(), clc, cls, Com_Printf(), Cvar_Set(), clientConnection_t::lastPacketTime, NET_CompareAdr(), clientConnection_t::netchan, qtrue, clientStatic_t::realtime, netchan_t::remoteAddress, and clientConnection_t::state.
CL_DownloadsComplete()
void CL_DownloadsComplete (void)
Definition at line 1948 of file cl_main.c.
{
 #ifdef USE_CURL
     // if we downloaded with cURL
     if(clc.cURLUsed) {
         clc.cURLUsed = qfalse;
         CL_cURL_Shutdown();
         if( clc.cURLDisconnected ) {
             if(clc.downloadRestart) {
                 FS_Restart(clc.checksumFeed);
                 clc.downloadRestart = qfalse;
             }
             clc.cURLDisconnected = qfalse;
             CL_Reconnect_f();
             return;
         }
     }
 #endif
     // if we downloaded files we need to restart the file system
     if (clc.downloadRestart) {
         clc.downloadRestart = qfalse;
         FS_Restart(clc.checksumFeed); // We possibly downloaded a pak, restart the file system to load it
         // inform the server so we get new gamestate info
         CL_AddReliableCommand("donedl", qfalse);
         // by sending the donedl command we request a new gamestate
         // so we don't want to load stuff yet
         return;
     }
     // let the client game init and load data
     clc.state = CA_LOADING;
     // Pump the loop, this may change gamestate!
     Com_EventLoop();
     // if the gamestate was changed by calling Com_EventLoop
     // then we loaded everything already and we don't want to do it again.
     if ( clc.state != CA_LOADING ) {
         return;
     }
     // starting to load a map so we get out of full screen ui mode
     Cvar_Set("r_uiFullScreen", "0");
     // flush client memory and start loading stuff
     // this will also (re)load the UI
     // if this is a local client then only the client part of the hunk
     // will be cleared, note that this is done after the hunk mark has been set
     CL_FlushMemory();
     // initialize the CGame
     cls.cgameStarted = qtrue;
     CL_InitCGame();
     // set pure checksums
     CL_SendPureChecksums();
     CL_WritePacket();
     CL_WritePacket();
     CL_WritePacket();
 }
References CA_LOADING, clientStatic_t::cgameStarted, clientConnection_t::checksumFeed, CL_AddReliableCommand(), CL_cURL_Shutdown(), CL_FlushMemory(), CL_InitCGame(), CL_Reconnect_f(), CL_SendPureChecksums(), CL_WritePacket(), clc, cls, Com_EventLoop(), Cvar_Set(), clientConnection_t::downloadRestart, FS_Restart(), qfalse, qtrue, and clientConnection_t::state.
Referenced by CL_InitDownloads(), and CL_NextDownload().
CL_FlushMemory()
void CL_FlushMemory (void)
Definition at line 1256 of file cl_main.c.
 {
     CL_ClearMemory(qfalse);
     CL_StartHunkUsers(qfalse);
 }
Referenced by CL_DownloadsComplete(), Com_Error(), and Com_Frame().
CL_ForwardCommandToServer()
void CL_ForwardCommandToServer (const char * string)
Definition at line 1482 of file cl_main.c.
{
     char    *cmd;
     cmd = Cmd_Argv(0);
     // ignore key up commands
     if ( cmd[0] == '-' ) {
         return;
     }
     if ( clc.demoplaying || clc.state < CA_CONNECTED || cmd[0] == '+' ) {
         Com_Printf ("Unknown command \"%s" S_COLOR_WHITE "\"\n", cmd);
         return;
     }
     if ( Cmd_Argc() > 1 ) {
         CL_AddReliableCommand(string, qfalse);
     } else {
         CL_AddReliableCommand(cmd, qfalse);
     }
 }
Referenced by Cmd_ExecuteString().
CL_ForwardToServer_f()
void CL_ForwardToServer_f (void)
Definition at line 1553 of file cl_main.c.
{
     if ( clc.state != CA_ACTIVE || clc.demoplaying ) {
         Com_Printf ("Not connected to a server.\n");
         return;
     }
     // don't forward the first argument
     if ( Cmd_Argc() > 1 ) {
         CL_AddReliableCommand(Cmd_Args(), qfalse);
     }
 }
References CA_ACTIVE, CL_AddReliableCommand(), clc, Cmd_Argc(), Cmd_Args(), Com_Printf(), clientConnection_t::demoplaying, qfalse, and clientConnection_t::state.
Referenced by CL_Init().
CL_Frame()
void CL_Frame (int msec)
Definition at line 2813 of file cl_main.c.
{
     if ( !com_cl_running->integer ) {
         return;
     }
 #ifdef USE_CURL
     if(clc.downloadCURLM) {
         CL_cURL_PerformDownload();
         // we can't process frames normally when in disconnected
         // download mode since the ui vm expects clc.state to be
         // CA_CONNECTED
         if(clc.cURLDisconnected) {
             cls.realFrametime = msec;
             cls.frametime = msec;
             cls.realtime += cls.frametime;
             SCR_UpdateScreen();
             S_Update();
             Con_RunConsole();
             cls.framecount++;
             return;
         }
     }
 #endif
     if ( clc.state == CA_DISCONNECTED && !( Key_GetCatcher( ) & KEYCATCH_UI )
         && !com_sv_running->integer && uivm ) {
         // if disconnected, bring up the menu
         S_StopAllSounds();
         VM_Call( uivm, UI_SET_ACTIVE_MENU, UIMENU_MAIN );
     }
     // if recording an avi, lock to a fixed fps
     if ( CL_VideoRecording( ) && cl_aviFrameRate->integer && msec) {
         // save the current screen
         if ( clc.state == CA_ACTIVE || cl_forceavidemo->integer) {
             CL_TakeVideoFrame( );
             // fixed time for next frame'
             msec = (int)ceil( (1000.0f / cl_aviFrameRate->value) * com_timescale->value );
             if (msec == 0) {
                 msec = 1;
             }
         }
     }
     if( cl_autoRecordDemo->integer ) {
         if( clc.state == CA_ACTIVE && !clc.demorecording && !clc.demoplaying ) {
             // If not recording a demo, and we should be, start one
             qtime_t now;
             char        *nowString;
             char        *p;
             char        mapName[ MAX_QPATH ];
             char        serverName[ MAX_OSPATH ];
             Com_RealTime( &now );
             nowString = va( "%04d%02d%02d%02d%02d%02d",
                     1900 + now.tm_year,
                     1 + now.tm_mon,
                     now.tm_mday,
                     now.tm_hour,
                     now.tm_min,
                     now.tm_sec );
             Q_strncpyz( serverName, clc.servername, MAX_OSPATH );
             // Replace the ":" in the address as it is not a valid
             // file name character
             p = strstr( serverName, ":" );
             if( p ) {
                 *p = '.';
             }
             Q_strncpyz( mapName, COM_SkipPath( cl.mapname ), sizeof( cl.mapname ) );
             COM_StripExtension(mapName, mapName, sizeof(mapName));
             Cbuf_ExecuteText( EXEC_NOW,
                     va( "record %s-%s-%s", nowString, serverName, mapName ) );
         }
         else if( clc.state != CA_ACTIVE && clc.demorecording ) {
             // Recording, but not CA_ACTIVE, so stop recording
             CL_StopRecord_f( );
         }
     }
     // save the msec before checking pause
     cls.realFrametime = msec;
     // decide the simulation time
     cls.frametime = msec;
     cls.realtime += cls.frametime;
     if ( cl_timegraph->integer ) {
         SCR_DebugGraph ( cls.realFrametime * 0.25 );
     }
     // see if we need to update any userinfo
     CL_CheckUserinfo();
     // if we haven't gotten a packet in a long time,
     // drop the connection
     CL_CheckTimeout();
     // send intentions now
     CL_SendCmd();
     // resend a connection request if necessary
     CL_CheckForResend();
     // decide on the serverTime to render
     CL_SetCGameTime();
     // update the screen
     SCR_UpdateScreen();
     // update audio
     S_Update();
 #ifdef USE_VOIP
     CL_CaptureVoip();
 #endif
 #ifdef USE_MUMBLE
     CL_UpdateMumble();
 #endif
     // advance local effects for next frame
     SCR_RunCinematic();
     Con_RunConsole();
     cls.framecount++;
 }
Referenced by Com_Frame().
CL_GenerateQKey()
static void CL_GenerateQKey (void) static
Definition at line 3276 of file cl_main.c.
 {
     int len = 0;
     unsigned char buff[ QKEY_SIZE ];
     fileHandle_t f;
     len = FS_SV_FOpenFileRead( QKEY_FILE, &f );
     FS_FCloseFile( f );
     if( len == QKEY_SIZE ) {
         Com_Printf( "QKEY found.\n" );
         return;
     }
     else {
         if( len > 0 ) {
             Com_Printf( "QKEY file size != %d, regenerating\n",
                 QKEY_SIZE );
         }
         Com_Printf( "QKEY building random string\n" );
         Com_RandomBytes( buff, sizeof(buff) );
         f = FS_SV_FOpenFileWrite( QKEY_FILE );
         if( !f ) {
             Com_Printf( "QKEY could not open %s for write\n",
                 QKEY_FILE );
             return;
         }
         FS_Write( buff, sizeof(buff), f );
         FS_FCloseFile( f );
         Com_Printf( "QKEY generated\n" );
     }
 }
References Com_Printf(), Com_RandomBytes(), FS_FCloseFile(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_Write(), QKEY_FILE, and QKEY_SIZE.
Referenced by CL_Init().
CL_GetFreePing()
ping_t* CL_GetFreePing (void)
Definition at line 4172 of file cl_main.c.
 {
     ping_t* pingptr;
     ping_t* best;
     int     oldest;
     int     i;
     int     time;
     pingptr = cl_pinglist;
     for (i=0; i<MAX_PINGREQUESTS; i++, pingptr++ )
     {
         // find free ping slot
         if (pingptr->adr.port)
         {
             if (!pingptr->time)
             {
                 if (Sys_Milliseconds() - pingptr->start < 500)
                 {
                     // still waiting for response
                     continue;
                 }
             }
             else if (pingptr->time < 500)
             {
                 // results have not been queried
                 continue;
             }
         }
         // clear it
         pingptr->adr.port = 0;
         return (pingptr);
     }
     // use oldest entry
     pingptr = cl_pinglist;
     best    = cl_pinglist;
     oldest  = INT_MIN;
     for (i=0; i<MAX_PINGREQUESTS; i++, pingptr++ )
     {
         // scan for oldest
         time = Sys_Milliseconds() - pingptr->start;
         if (time > oldest)
         {
             oldest = time;
             best   = pingptr;
         }
     }
     return (best);
 }
References ping_t::adr, cl_pinglist, MAX_PINGREQUESTS, netadr_t::port, ping_t::start, Sys_Milliseconds(), and ping_t::time.
Referenced by CL_Ping_f().
CL_GetPing()
void CL_GetPing (int n, char * buf, int buflen, int * pingtime)
Definition at line 4075 of file cl_main.c.
 {
     const char  *str;
     int     time;
     int     maxPing;
     if (n < 0 || n >= MAX_PINGREQUESTS || !cl_pinglist[n].adr.port)
     {
         // empty or invalid slot
         buf[0]    = '\0';
         *pingtime = 0;
         return;
     }
     str = NET_AdrToStringwPort( cl_pinglist[n].adr );
     Q_strncpyz( buf, str, buflen );
     time = cl_pinglist[n].time;
     if (!time)
     {
         // check for timeout
         time = Sys_Milliseconds() - cl_pinglist[n].start;
         maxPing = Cvar_VariableIntegerValue( "cl_maxPing" );
         if( maxPing < 100 ) {
             maxPing = 100;
         }
         if (time < maxPing)
         {
             // not timed out yet
             time = 0;
         }
     }
     CL_SetServerInfoByAddress(cl_pinglist[n].adr, cl_pinglist[n].info, cl_pinglist[n].time);
     *pingtime = time;
 }
References cl_pinglist, CL_SetServerInfoByAddress(), Cvar_VariableIntegerValue(), info, MAX_PINGREQUESTS, NET_AdrToStringwPort(), Q_strncpyz(), ping_t::start, Sys_Milliseconds(), and ping_t::time.
Referenced by CL_UpdateVisiblePings_f(), and LAN_GetPing().
CL_GetPingInfo()
void CL_GetPingInfo (int n, char * buf, int buflen)
Definition at line 4118 of file cl_main.c.
 {
     if (n < 0 || n >= MAX_PINGREQUESTS || !cl_pinglist[n].adr.port)
     {
         // empty or invalid slot
         if (buflen)
             buf[0] = '\0';
         return;
     }
     Q_strncpyz( buf, cl_pinglist[n].info, buflen );
 }
References cl_pinglist, info, MAX_PINGREQUESTS, and Q_strncpyz().
Referenced by LAN_GetPingInfo().
CL_GetPingQueueCount()
int CL_GetPingQueueCount (void)
Definition at line 4149 of file cl_main.c.
 {
     int     i;
     int     count;
     ping_t* pingptr;
     count   = 0;
     pingptr = cl_pinglist;
     for (i=0; i<MAX_PINGREQUESTS; i++, pingptr++ ) {
         if (pingptr->adr.port) {
             count++;
         }
     }
     return (count);
 }
References ping_t::adr, cl_pinglist, MAX_PINGREQUESTS, and netadr_t::port.
Referenced by CL_UpdateVisiblePings_f(), and LAN_GetPingQueueCount().
CL_GetServerStatus()
serverStatus_t* CL_GetServerStatus (netadr_t from)
Definition at line 3769 of file cl_main.c.
{
     int i, oldest, oldestTime;
     for (i = 0; i < MAX_SERVERSTATUSREQUESTS; i++) {
         if ( NET_CompareAdr( from, cl_serverStatusList[i].address ) ) {
             return &cl_serverStatusList[i];
         }
     }
     for (i = 0; i < MAX_SERVERSTATUSREQUESTS; i++) {
         if ( cl_serverStatusList[i].retrieved ) {
             return &cl_serverStatusList[i];
         }
     }
     oldest = -1;
     oldestTime = 0;
     for (i = 0; i < MAX_SERVERSTATUSREQUESTS; i++) {
         if (oldest == -1 || cl_serverStatusList[i].startTime < oldestTime) {
             oldest = i;
             oldestTime = cl_serverStatusList[i].startTime;
         }
     }
     if (oldest != -1) {
         return &cl_serverStatusList[oldest];
     }
     serverStatusCount++;
     return &cl_serverStatusList[serverStatusCount & (MAX_SERVERSTATUSREQUESTS-1)];
 }
References cl_serverStatusList, MAX_SERVERSTATUSREQUESTS, NET_CompareAdr(), and serverStatusCount.
Referenced by CL_ServerStatus(), and CL_ServerStatus_f().
CL_GlobalServers_f()
void CL_GlobalServers_f (void)
Definition at line 4002 of file cl_main.c.
{
     netadr_t    to;
     int         count, i, masterNum;
     char        command[1024], *masteraddress;
     if ((count = Cmd_Argc()) < 3 || (masterNum = atoi(Cmd_Argv(1))) < 0 || masterNum > MAX_MASTER_SERVERS - 1)
     {
         Com_Printf("usage: globalservers <master# 0-%d> <protocol> [keywords]\n", MAX_MASTER_SERVERS - 1);
         return;
     }
     sprintf(command, "sv_master%d", masterNum + 1);
     masteraddress = Cvar_VariableString(command);
     if(!*masteraddress)
     {
         Com_Printf( "CL_GlobalServers_f: Error: No master server address given.\n");
         return;
     }
     // reset the list, waiting for response
     // -1 is used to distinguish a "no response"
     i = NET_StringToAdr(masteraddress, &to, NA_UNSPEC);
     if(!i)
     {
         Com_Printf( "CL_GlobalServers_f: Error: could not resolve address of master %s\n", masteraddress);
         return;
     }
     else if(i == 2)
         to.port = BigShort(PORT_MASTER);
     Com_Printf("Requesting servers from master %s...\n", masteraddress);
     cls.numglobalservers = -1;
     cls.pingUpdateSource = AS_GLOBAL;
     // Use the extended query for IPv6 masters
     if (to.type == NA_IP6 || to.type == NA_MULTICAST6)
     {
         int v4enabled = Cvar_VariableIntegerValue("net_enabled") & NET_ENABLEV4;
         if(v4enabled)
         {
             Com_sprintf(command, sizeof(command), "getserversExt %s %s",
                 com_gamename->string, Cmd_Argv(2));
         }
         else
         {
             Com_sprintf(command, sizeof(command), "getserversExt %s %s ipv6",
                 com_gamename->string, Cmd_Argv(2));
         }
     }
     else
         Com_sprintf(command, sizeof(command), "getservers %s %s",
             com_gamename->string, Cmd_Argv(2));
     for (i=3; i < count; i++)
     {
         Q_strcat(command, sizeof(command), " ");
         Q_strcat(command, sizeof(command), Cmd_Argv(i));
     }
     NET_OutOfBandPrint( NS_SERVER, to, "%s", command );
 }
References AS_GLOBAL, cls, Cmd_Argc(), Cmd_Argv(), com_gamename, Com_Printf(), Com_sprintf(), Cvar_VariableIntegerValue(), Cvar_VariableString(), MAX_MASTER_SERVERS, NA_IP6, NA_MULTICAST6, NA_UNSPEC, NET_ENABLEV4, NET_OutOfBandPrint(), NET_StringToAdr(), NS_SERVER, clientStatic_t::numglobalservers, clientStatic_t::pingUpdateSource, netadr_t::port, PORT_MASTER, Q_strcat(), and netadr_t::type.
Referenced by CL_Init().
CL_Init()
void CL_Init (void)
Definition at line 3314 of file cl_main.c.
                      {
     Com_Printf( "----- Client Initialization -----\n" );
     Con_Init ();
     if(!com_fullyInitialized)
     {
         CL_ClearState();
         clc.state = CA_DISCONNECTED;    // no longer CA_UNINITIALIZED
         cls.oldGameSet = qfalse;
     }
     cls.realtime = 0;
     CL_InitInput ();
     //
     // register our variables
     //
     cl_noprint = Cvar_Get( "cl_noprint", "0", 0 );
 #ifdef UPDATE_SERVER_NAME
     cl_motd = Cvar_Get ("cl_motd", "1", 0);
 #endif
     cl_timeout = Cvar_Get ("cl_timeout", "200", 0);
     cl_timeNudge = Cvar_Get ("cl_timeNudge", "0", CVAR_TEMP );
     cl_shownet = Cvar_Get ("cl_shownet", "0", CVAR_TEMP );
     cl_showSend = Cvar_Get ("cl_showSend", "0", CVAR_TEMP );
     cl_showTimeDelta = Cvar_Get ("cl_showTimeDelta", "0", CVAR_TEMP );
     cl_freezeDemo = Cvar_Get ("cl_freezeDemo", "0", CVAR_TEMP );
     rcon_client_password = Cvar_Get ("rconPassword", "", CVAR_TEMP );
     cl_activeAction = Cvar_Get( "activeAction", "", CVAR_TEMP );
     cl_timedemo = Cvar_Get ("timedemo", "0", 0);
     cl_timedemoLog = Cvar_Get ("cl_timedemoLog", "", CVAR_ARCHIVE);
     cl_autoRecordDemo = Cvar_Get ("cl_autoRecordDemo", "0", CVAR_ARCHIVE);
     cl_aviFrameRate = Cvar_Get ("cl_aviFrameRate", "25", CVAR_ARCHIVE);
     cl_aviMotionJpeg = Cvar_Get ("cl_aviMotionJpeg", "1", CVAR_ARCHIVE);
     cl_forceavidemo = Cvar_Get ("cl_forceavidemo", "0", 0);
     rconAddress = Cvar_Get ("rconAddress", "", 0);
     cl_yawspeed = Cvar_Get ("cl_yawspeed", "140", CVAR_ARCHIVE);
     cl_pitchspeed = Cvar_Get ("cl_pitchspeed", "140", CVAR_ARCHIVE);
     cl_anglespeedkey = Cvar_Get ("cl_anglespeedkey", "1.5", 0);
     cl_maxpackets = Cvar_Get ("cl_maxpackets", "30", CVAR_ARCHIVE );
     cl_packetdup = Cvar_Get ("cl_packetdup", "1", CVAR_ARCHIVE );
     cl_run = Cvar_Get ("cl_run", "1", CVAR_ARCHIVE);
     cl_sensitivity = Cvar_Get ("sensitivity", "5", CVAR_ARCHIVE);
     cl_mouseAccel = Cvar_Get ("cl_mouseAccel", "0", CVAR_ARCHIVE);
     cl_freelook = Cvar_Get( "cl_freelook", "1", CVAR_ARCHIVE );
     // 0: legacy mouse acceleration
     // 1: new implementation
     cl_mouseAccelStyle = Cvar_Get( "cl_mouseAccelStyle", "0", CVAR_ARCHIVE );
     // offset for the power function (for style 1, ignored otherwise)
     // this should be set to the max rate value
     cl_mouseAccelOffset = Cvar_Get( "cl_mouseAccelOffset", "5", CVAR_ARCHIVE );
     Cvar_CheckRange(cl_mouseAccelOffset, 0.001f, 50000.0f, qfalse);
     cl_showMouseRate = Cvar_Get ("cl_showmouserate", "0", 0);
     cl_allowDownload = Cvar_Get ("cl_allowDownload", "0", CVAR_ARCHIVE);
 #ifdef USE_CURL_DLOPEN
     cl_cURLLib = Cvar_Get("cl_cURLLib", DEFAULT_CURL_LIB, CVAR_ARCHIVE);
 #endif
     cl_conXOffset = Cvar_Get ("cl_conXOffset", "0", 0);
 #ifdef MACOS_X
     // In game video is REALLY slow in Mac OS X right now due to driver slowness
     cl_inGameVideo = Cvar_Get ("r_inGameVideo", "0", CVAR_ARCHIVE);
 #else
     cl_inGameVideo = Cvar_Get ("r_inGameVideo", "1", CVAR_ARCHIVE);
 #endif
     cl_serverStatusResendTime = Cvar_Get ("cl_serverStatusResendTime", "750", 0);
     m_pitch = Cvar_Get ("m_pitch", "0.022", CVAR_ARCHIVE);
     m_yaw = Cvar_Get ("m_yaw", "0.022", CVAR_ARCHIVE);
     m_forward = Cvar_Get ("m_forward", "0.25", CVAR_ARCHIVE);
     m_side = Cvar_Get ("m_side", "0.25", CVAR_ARCHIVE);
 #ifdef MACOS_X
     // Input is jittery on OS X w/o this
     m_filter = Cvar_Get ("m_filter", "1", CVAR_ARCHIVE);
 #else
     m_filter = Cvar_Get ("m_filter", "0", CVAR_ARCHIVE);
 #endif
     j_pitch =        Cvar_Get ("j_pitch",        "0.022", CVAR_ARCHIVE);
     j_yaw =          Cvar_Get ("j_yaw",          "-0.022", CVAR_ARCHIVE);
     j_forward =      Cvar_Get ("j_forward",      "-0.25", CVAR_ARCHIVE);
     j_side =         Cvar_Get ("j_side",         "0.25", CVAR_ARCHIVE);
     j_up =           Cvar_Get ("j_up",           "1", CVAR_ARCHIVE);
     j_pitch_axis =   Cvar_Get ("j_pitch_axis",   "3", CVAR_ARCHIVE);
     j_yaw_axis =     Cvar_Get ("j_yaw_axis",     "4", CVAR_ARCHIVE);
     j_forward_axis = Cvar_Get ("j_forward_axis", "1", CVAR_ARCHIVE);
     j_side_axis =    Cvar_Get ("j_side_axis",    "0", CVAR_ARCHIVE);
     j_up_axis =      Cvar_Get ("j_up_axis",      "2", CVAR_ARCHIVE);
     Cvar_CheckRange(j_pitch_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     Cvar_CheckRange(j_yaw_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     Cvar_CheckRange(j_forward_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     Cvar_CheckRange(j_side_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     Cvar_CheckRange(j_up_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     cl_motdString = Cvar_Get( "cl_motdString", "", CVAR_ROM );
     Cvar_Get( "cl_maxPing", "800", CVAR_ARCHIVE );
     cl_lanForcePackets = Cvar_Get ("cl_lanForcePackets", "1", CVAR_ARCHIVE);
     cl_guidServerUniq = Cvar_Get ("cl_guidServerUniq", "1", CVAR_ARCHIVE);
     // ~ and `, as keys and characters
     cl_consoleKeys = Cvar_Get( "cl_consoleKeys", "~ ` 0x7e 0x60", CVAR_ARCHIVE);
     // userinfo
     Cvar_Get ("name", "UnnamedPlayer", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("rate", "25000", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("snaps", "20", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("model", "sarge", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("headmodel", "sarge", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("team_model", "james", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("team_headmodel", "*james", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("teamtask", "0", CVAR_USERINFO );
     Cvar_Get ("password", "", CVAR_USERINFO);
     Cvar_Get ("cg_predictItems", "1", CVAR_USERINFO | CVAR_ARCHIVE );
 #ifdef USE_MUMBLE
     cl_useMumble = Cvar_Get ("cl_useMumble", "0", CVAR_ARCHIVE | CVAR_LATCH);
     cl_mumbleScale = Cvar_Get ("cl_mumbleScale", "0.0254", CVAR_ARCHIVE);
 #endif
 #ifdef USE_VOIP
     cl_voipSend = Cvar_Get ("cl_voipSend", "0", 0);
     cl_voipSendTarget = Cvar_Get ("cl_voipSendTarget", "spatial", 0);
     cl_voipGainDuringCapture = Cvar_Get ("cl_voipGainDuringCapture", "0.2", CVAR_ARCHIVE);
     cl_voipCaptureMult = Cvar_Get ("cl_voipCaptureMult", "2.0", CVAR_ARCHIVE);
     cl_voipUseVAD = Cvar_Get ("cl_voipUseVAD", "0", CVAR_ARCHIVE);
     cl_voipVADThreshold = Cvar_Get ("cl_voipVADThreshold", "0.25", CVAR_ARCHIVE);
     cl_voipShowMeter = Cvar_Get ("cl_voipShowMeter", "1", CVAR_ARCHIVE);
     // This is a protocol version number.
     cl_voip = Cvar_Get ("cl_voip", "1", CVAR_USERINFO | CVAR_ARCHIVE | CVAR_LATCH);
     Cvar_CheckRange( cl_voip, 0, 1, qtrue );
     // If your data rate is too low, you'll get Connection Interrupted warnings
     //  when VoIP packets arrive, even if you have a broadband connection.
     //  This might work on rates lower than 25000, but for safety's sake, we'll
     //  just demand it. Who doesn't have at least a DSL line now, anyhow? If
     //  you don't, you don't need VoIP.  :)
     if ((cl_voip->integer) && (Cvar_VariableIntegerValue("rate") < 25000)) {
         Com_Printf(S_COLOR_YELLOW "Your network rate is too slow for VoIP.\n");
         Com_Printf("Set 'Data Rate' to 'LAN/Cable/xDSL' in 'Setup/System/Network' and restart.\n");
         Com_Printf("Until then, VoIP is disabled.\n");
         Cvar_Set("cl_voip", "0");
     }
 #endif
     // cgame might not be initialized before menu is used
     Cvar_Get ("cg_viewsize", "100", CVAR_ARCHIVE );
     // Make sure cg_stereoSeparation is zero as that variable is deprecated and should not be used anymore.
     Cvar_Get ("cg_stereoSeparation", "0", CVAR_ROM);
     //
     // register our commands
     //
     Cmd_AddCommand ("cmd", CL_ForwardToServer_f);
     Cmd_AddCommand ("configstrings", CL_Configstrings_f);
     Cmd_AddCommand ("clientinfo", CL_Clientinfo_f);
     Cmd_AddCommand ("snd_restart", CL_Snd_Restart_f);
     Cmd_AddCommand ("vid_restart", CL_Vid_Restart_f);
     Cmd_AddCommand ("disconnect", CL_Disconnect_f);
     Cmd_AddCommand ("record", CL_Record_f);
     Cmd_AddCommand ("demo", CL_PlayDemo_f);
     Cmd_SetCommandCompletionFunc( "demo", CL_CompleteDemoName );
     Cmd_AddCommand ("cinematic", CL_PlayCinematic_f);
     Cmd_AddCommand ("stoprecord", CL_StopRecord_f);
     Cmd_AddCommand ("connect", CL_Connect_f);
     Cmd_AddCommand ("reconnect", CL_Reconnect_f);
     Cmd_AddCommand ("localservers", CL_LocalServers_f);
     Cmd_AddCommand ("globalservers", CL_GlobalServers_f);
     Cmd_AddCommand ("rcon", CL_Rcon_f);
     Cmd_SetCommandCompletionFunc( "rcon", CL_CompleteRcon );
     Cmd_AddCommand ("ping", CL_Ping_f );
     Cmd_AddCommand ("serverstatus", CL_ServerStatus_f );
     Cmd_AddCommand ("showip", CL_ShowIP_f );
     Cmd_AddCommand ("fs_openedList", CL_OpenedPK3List_f );
     Cmd_AddCommand ("fs_referencedList", CL_ReferencedPK3List_f );
     Cmd_AddCommand ("model", CL_SetModel_f );
     Cmd_AddCommand ("video", CL_Video_f );
     Cmd_AddCommand ("stopvideo", CL_StopVideo_f );
     CL_InitRef();
     SCR_Init ();
 //  Cbuf_Execute ();
     Cvar_Set( "cl_running", "1" );
     CL_GenerateQKey();
     Cvar_Get( "cl_guid", "", CVAR_USERINFO | CVAR_ROM );
     CL_UpdateGUID( NULL, 0 );
     Com_Printf( "----- Client Initialization Complete -----\n" );
 }
Referenced by Com_GameRestart(), and Com_Init().
CL_InitDownloads()
void CL_InitDownloads (void)
Definition at line 2153 of file cl_main.c.
{
   char missingfiles[1024];
   if ( !(cl_allowDownload->integer & DLF_ENABLE) )
   {
     // autodownload is disabled on the client
     // but it's possible that some referenced files on the server are missing
     if (FS_ComparePaks( missingfiles, sizeof( missingfiles ), qfalse ) )
     {
       // NOTE TTimo I would rather have that printed as a modal message box
       //   but at this point while joining the game we don't know wether we will successfully join or not
       Com_Printf( "\nWARNING: You are missing some files referenced by the server:\n%s"
                   "You might not be able to join the game\n"
                   "Go to the setting menu to turn on autodownload, or get the file elsewhere\n\n", missingfiles );
     }
   }
   else if ( FS_ComparePaks( clc.downloadList, sizeof( clc.downloadList ) , qtrue ) ) {
     Com_Printf("Need paks: %s\n", clc.downloadList );
         if ( *clc.downloadList ) {
             // if autodownloading is not enabled on the server
             clc.state = CA_CONNECTED;
             *clc.downloadTempName = *clc.downloadName = 0;
             Cvar_Set( "cl_downloadName", "" );
             CL_NextDownload();
             return;
         }
     }
     CL_DownloadsComplete();
 }
References CA_CONNECTED, cl_allowDownload, CL_DownloadsComplete(), CL_NextDownload(), clc, Com_Printf(), Cvar_Set(), DLF_ENABLE, clientConnection_t::downloadList, clientConnection_t::downloadName, clientConnection_t::downloadTempName, FS_ComparePaks(), qfalse, qtrue, and clientConnection_t::state.
Referenced by CL_ParseGamestate().
CL_InitRef()
void CL_InitRef (void)
Definition at line 3071 of file cl_main.c.
{
     refimport_t ri;
     refexport_t *ret;
 #ifdef USE_RENDERER_DLOPEN
     GetRefAPI_t     GetRefAPI;
     char            dllName[MAX_OSPATH];
 #endif
     Com_Printf( "----- Initializing Renderer ----\n" );
 #ifdef USE_RENDERER_DLOPEN
     cl_renderer = Cvar_Get("cl_renderer", "opengl1", CVAR_ARCHIVE | CVAR_LATCH);
     Com_sprintf(dllName, sizeof(dllName), "renderer_%s_" ARCH_STRING DLL_EXT, cl_renderer->string);
     if(!(rendererLib = Sys_LoadDll(dllName, qfalse)) && strcmp(cl_renderer->string, cl_renderer->resetString))
     {
         Cvar_ForceReset("cl_renderer");
         Com_sprintf(dllName, sizeof(dllName), "renderer_opengl1_" ARCH_STRING DLL_EXT);
         rendererLib = Sys_LoadLibrary(dllName);
     }
     if(!rendererLib)
     {
         Com_Printf("failed:\n\"%s\"\n", Sys_LibraryError());
         Com_Error(ERR_FATAL, "Failed to load renderer");
     }
     GetRefAPI = Sys_LoadFunction(rendererLib, "GetRefAPI");
     if(!GetRefAPI)
     {
         Com_Error(ERR_FATAL, "Can't load symbol GetRefAPI: '%s'",  Sys_LibraryError());
     }
 #endif
     ri.Cmd_AddCommand = Cmd_AddCommand;
     ri.Cmd_RemoveCommand = Cmd_RemoveCommand;
     ri.Cmd_Argc = Cmd_Argc;
     ri.Cmd_Argv = Cmd_Argv;
     ri.Cmd_ExecuteText = Cbuf_ExecuteText;
     ri.Printf = CL_RefPrintf;
     ri.Error = Com_Error;
     ri.Milliseconds = CL_ScaledMilliseconds;
     ri.Malloc = CL_RefMalloc;
     ri.Free = Z_Free;
 #ifdef HUNK_DEBUG
     ri.Hunk_AllocDebug = Hunk_AllocDebug;
 #else
     ri.Hunk_Alloc = Hunk_Alloc;
 #endif
     ri.Hunk_AllocateTempMemory = Hunk_AllocateTempMemory;
     ri.Hunk_FreeTempMemory = Hunk_FreeTempMemory;
     ri.CM_ClusterPVS = CM_ClusterPVS;
     ri.CM_DrawDebugSurface = CM_DrawDebugSurface;
     ri.FS_ReadFile = FS_ReadFile;
     ri.FS_FreeFile = FS_FreeFile;
     ri.FS_WriteFile = FS_WriteFile;
     ri.FS_FreeFileList = FS_FreeFileList;
     ri.FS_ListFiles = FS_ListFiles;
     ri.FS_FileIsInPAK = FS_FileIsInPAK;
     ri.FS_FileExists = FS_FileExists;
     ri.Cvar_Get = Cvar_Get;
     ri.Cvar_Set = Cvar_Set;
     ri.Cvar_SetValue = Cvar_SetValue;
     ri.Cvar_CheckRange = Cvar_CheckRange;
     ri.Cvar_VariableIntegerValue = Cvar_VariableIntegerValue;
     // cinematic stuff
     ri.CIN_UploadCinematic = CIN_UploadCinematic;
     ri.CIN_PlayCinematic = CIN_PlayCinematic;
     ri.CIN_RunCinematic = CIN_RunCinematic;
     ri.CL_WriteAVIVideoFrame = CL_WriteAVIVideoFrame;
     ri.IN_Init = IN_Init;
     ri.IN_Shutdown = IN_Shutdown;
     ri.IN_Restart = IN_Restart;
     ri.ftol = Q_ftol;
     ri.Sys_SetEnv = Sys_SetEnv;
     ri.Sys_GLimpSafeInit = Sys_GLimpSafeInit;
     ri.Sys_GLimpInit = Sys_GLimpInit;
     ri.Sys_LowPhysicalMemory = Sys_LowPhysicalMemory;
     ret = GetRefAPI( REF_API_VERSION, &ri );
 #if defined __USEA3D && defined __A3D_GEOM
     hA3Dg_ExportRenderGeom (ret);
 #endif
     Com_Printf( "-------------------------------\n");
     if ( !ret ) {
         Com_Error (ERR_FATAL, "Couldn't initialize refresh" );
     }
     re = *ret;
     // unpause so the cgame definately gets a snapshot and renders a frame
     Cvar_Set( "cl_paused", "0" );
 }
Referenced by CL_Init(), and CL_Vid_Restart_f().
CL_InitRenderer()
void CL_InitRenderer (void)
Definition at line 2994 of file cl_main.c.
{
     // this sets up the renderer and calls R_Init
     re.BeginRegistration( &cls.glconfig );
     // load character sets
     cls.charSetShader = re.RegisterShader( "consoleFont" );
     cls.whiteShader = re.RegisterShader( "white" );
     cls.consoleShader = re.RegisterShader( "console" );
     cls.chatInputShader = re.RegisterShader("chatInput");
     g_console_field_width = cls.glconfig.vidWidth / SMALLCHAR_WIDTH - 2;
     g_consoleField.widthInChars = g_console_field_width;
 }
References refexport_t::BeginRegistration, clientStatic_t::charSetShader, clientStatic_t::chatInputShader, cls, clientStatic_t::consoleShader, g_console_field_width, g_consoleField, clientStatic_t::glconfig, re, refexport_t::RegisterShader, SMALLCHAR_WIDTH, glconfig_t::vidWidth, clientStatic_t::whiteShader, and field_t::widthInChars.
Referenced by CL_StartHunkUsers().
CL_InitServerInfo()
void CL_InitServerInfo (serverInfo_t * server, netadr_t * address)
Definition at line 2339 of file cl_main.c.
{
     server->adr = *address;
     server->clients = 0;
     server->hostName[0] = '\0';
     server->mapName[0] = '\0';
     server->maxClients = 0;
     server->maxPing = 0;
     server->minPing = 0;
     server->ping = -1;
     server->game[0] = '\0';
     server->gameType = 0;
     server->netType = 0;
 }
References serverInfo_t::adr, serverInfo_t::clients, serverInfo_t::game, serverInfo_t::gameType, serverInfo_t::hostName, serverInfo_t::mapName, serverInfo_t::maxClients, serverInfo_t::maxPing, serverInfo_t::minPing, serverInfo_t::netType, and serverInfo_t::ping.
Referenced by CL_ServersResponsePacket(), and CL_UpdateVisiblePings_f().
CL_LocalServers_f()
void CL_LocalServers_f (void)
Definition at line 3958 of file cl_main.c.
{
     char        *message;
     int         i, j;
     netadr_t    to;
     Com_Printf( "Scanning for servers on the local network...\n");
     // reset the list, waiting for response
     cls.numlocalservers = 0;
     cls.pingUpdateSource = AS_LOCAL;
     for (i = 0; i < MAX_OTHER_SERVERS; i++) {
         qboolean b = cls.localServers[i].visible;
         Com_Memset(&cls.localServers[i], 0, sizeof(cls.localServers[i]));
         cls.localServers[i].visible = b;
     }
     Com_Memset( &to, 0, sizeof( to ) );
     // The 'xxx' in the message is a challenge that will be echoed back
     // by the server.  We don't care about that here, but master servers
     // can use that to prevent spoofed server responses from invalid ip
     message = "\377\377\377\377getinfo xxx";
     // send each message twice in case one is dropped
     for ( i = 0 ; i < 2 ; i++ ) {
         // send a broadcast packet on each server port
         // we support multiple server ports so a single machine
         // can nicely run multiple servers
         for ( j = 0 ; j < NUM_SERVER_PORTS ; j++ ) {
             to.port = BigShort( (short)(PORT_SERVER + j) );
             to.type = NA_BROADCAST;
             NET_SendPacket( NS_CLIENT, strlen( message ), message, to );
             to.type = NA_MULTICAST6;
             NET_SendPacket( NS_CLIENT, strlen( message ), message, to );
         }
     }
 }
References AS_LOCAL, cls, Com_Memset, Com_Printf(), clientStatic_t::localServers, MAX_OTHER_SERVERS, NA_BROADCAST, NA_MULTICAST6, NET_SendPacket(), NS_CLIENT, NUM_SERVER_PORTS, clientStatic_t::numlocalservers, clientStatic_t::pingUpdateSource, netadr_t::port, PORT_SERVER, netadr_t::type, and serverInfo_t::visible.
Referenced by CL_Init().
CL_MapLoading()
void CL_MapLoading (void)
Definition at line 1271 of file cl_main.c.
{
     if ( com_dedicated->integer ) {
         clc.state = CA_DISCONNECTED;
         Key_SetCatcher( KEYCATCH_CONSOLE );
         return;
     }
     if ( !com_cl_running->integer ) {
         return;
     }
     Con_Close();
     Key_SetCatcher( 0 );
     // if we are already connected to the local host, stay connected
     if ( clc.state >= CA_CONNECTED && !Q_stricmp( clc.servername, "localhost" ) ) {
         clc.state = CA_CONNECTED;       // so the connect screen is drawn
         Com_Memset( cls.updateInfoString, 0, sizeof( cls.updateInfoString ) );
         Com_Memset( clc.serverMessage, 0, sizeof( clc.serverMessage ) );
         Com_Memset( &cl.gameState, 0, sizeof( cl.gameState ) );
         clc.lastPacketSentTime = -9999;
         SCR_UpdateScreen();
     } else {
         // clear nextmap so the cinematic shutdown doesn't execute it
         Cvar_Set( "nextmap", "" );
         CL_Disconnect( qtrue );
         Q_strncpyz( clc.servername, "localhost", sizeof(clc.servername) );
         clc.state = CA_CHALLENGING;     // so the connect screen is drawn
         Key_SetCatcher( 0 );
         SCR_UpdateScreen();
         clc.connectTime = -RETRANSMIT_TIMEOUT;
         NET_StringToAdr( clc.servername, &clc.serverAddress, NA_UNSPEC);
         // we don't need a challenge on the localhost
         CL_CheckForResend();
     }
 }
Referenced by SV_SpawnServer().
CL_MotdPacket()
void CL_MotdPacket (netadr_t from)
Definition at line 2309 of file cl_main.c.
{
 #ifdef UPDATE_SERVER_NAME
     char    *challenge;
     char    *info;
     // if not from our server, ignore it
     if ( !NET_CompareAdr( from, cls.updateServer ) ) {
         return;
     }
     info = Cmd_Argv(1);
     // check challenge
     challenge = Info_ValueForKey( info, "challenge" );
     if ( strcmp( challenge, cls.updateChallenge ) ) {
         return;
     }
     challenge = Info_ValueForKey( info, "motd" );
     Q_strncpyz( cls.updateInfoString, info, sizeof( cls.updateInfoString ) );
     Cvar_Set( "cl_motdString", challenge );
 #endif
 }
References cls, Cmd_Argv(), Cvar_Set(), info, Info_ValueForKey(), NET_CompareAdr(), Q_strncpyz(), clientStatic_t::updateChallenge, clientStatic_t::updateInfoString, and clientStatic_t::updateServer.
Referenced by CL_ConnectionlessPacket().
CL_NextDemo()
void CL_NextDemo (void)
Definition at line 1168 of file cl_main.c.
{
     char    v[MAX_STRING_CHARS];
     Q_strncpyz( v, Cvar_VariableString ("nextdemo"), sizeof(v) );
     v[MAX_STRING_CHARS-1] = 0;
     Com_DPrintf("CL_NextDemo: %s\n", v );
     if (!v[0]) {
         return;
     }
     Cvar_Set ("nextdemo","");
     Cbuf_AddText (v);
     Cbuf_AddText ("\n");
     Cbuf_Execute();
 }
References Cbuf_AddText(), Cbuf_Execute(), Com_DPrintf(), Cvar_Set(), Cvar_VariableString(), MAX_STRING_CHARS, and Q_strncpyz().
Referenced by CL_DemoCompleted().
CL_NextDownload()
void CL_NextDownload (void)
Definition at line 2051 of file cl_main.c.
 {
     char *s;
     char *remoteName, *localName;
     qboolean useCURL = qfalse;
     // A download has finished, check whether this matches a referenced checksum
     if(*clc.downloadName)
     {
         char *zippath = FS_BuildOSPath(Cvar_VariableString("fs_homepath"), clc.downloadName, "");
         zippath[strlen(zippath)-1] = '\0';
         if(!FS_CompareZipChecksum(zippath))
             Com_Error(ERR_DROP, "Incorrect checksum for file: %s", clc.downloadName);
     }
     *clc.downloadTempName = *clc.downloadName = 0;
     Cvar_Set("cl_downloadName", "");
     // We are looking to start a download here
     if (*clc.downloadList) {
         s = clc.downloadList;
         // format is:
         //  @remotename@localname@remotename@localname, etc.
         if (*s == '@')
             s++;
         remoteName = s;
         if ( (s = strchr(s, '@')) == NULL ) {
             CL_DownloadsComplete();
             return;
         }
         *s++ = 0;
         localName = s;
         if ( (s = strchr(s, '@')) != NULL )
             *s++ = 0;
         else
             s = localName + strlen(localName); // point at the nul byte
 #ifdef USE_CURL
         if(!(cl_allowDownload->integer & DLF_NO_REDIRECT)) {
             if(clc.sv_allowDownload & DLF_NO_REDIRECT) {
                 Com_Printf("WARNING: server does not "
                     "allow download redirection "
                     "(sv_allowDownload is %d)\n",
                     clc.sv_allowDownload);
             }
             else if(!*clc.sv_dlURL) {
                 Com_Printf("WARNING: server allows "
                     "download redirection, but does not "
                     "have sv_dlURL set\n");
             }
             else if(!CL_cURL_Init()) {
                 Com_Printf("WARNING: could not load "
                     "cURL library\n");
             }
             else {
                 CL_cURL_BeginDownload(localName, va("%s/%s",
                     clc.sv_dlURL, remoteName));
                 useCURL = qtrue;
             }
         }
         else if(!(clc.sv_allowDownload & DLF_NO_REDIRECT)) {
             Com_Printf("WARNING: server allows download "
                 "redirection, but it disabled by client "
                 "configuration (cl_allowDownload is %d)\n",
                 cl_allowDownload->integer);
         }
 #endif /* USE_CURL */
         if(!useCURL) {
             if((cl_allowDownload->integer & DLF_NO_UDP)) {
                 Com_Error(ERR_DROP, "UDP Downloads are "
                     "disabled on your client. "
                     "(cl_allowDownload is %d)",
                     cl_allowDownload->integer);
                 return;
             }
             else {
                 CL_BeginDownload( localName, remoteName );
             }
         }
         clc.downloadRestart = qtrue;
         // move over the rest
         memmove( clc.downloadList, s, strlen(s) + 1);
         return;
     }
     CL_DownloadsComplete();
 }
References cl_allowDownload, CL_BeginDownload(), CL_cURL_BeginDownload(), CL_cURL_Init(), CL_DownloadsComplete(), clc, Com_Error(), Com_Printf(), Cvar_Set(), Cvar_VariableString(), DLF_NO_REDIRECT, DLF_NO_UDP, clientConnection_t::downloadList, clientConnection_t::downloadName, clientConnection_t::downloadRestart, clientConnection_t::downloadTempName, ERR_DROP, FS_BuildOSPath(), FS_CompareZipChecksum(), memmove(), NULL, qfalse, qtrue, clientConnection_t::sv_allowDownload, clientConnection_t::sv_dlURL, and va().
Referenced by CL_InitDownloads(), and CL_ParseDownload().
CL_OldGame()
static void CL_OldGame (void) static
Definition at line 1345 of file cl_main.c.
 {
     if(cls.oldGameSet)
     {
         // change back to previous fs_game
         cls.oldGameSet = qfalse;
         Cvar_Set2("fs_game", cls.oldGame, qtrue);
         FS_ConditionalRestart(clc.checksumFeed, qfalse);
     }
 }
References clientConnection_t::checksumFeed, clc, cls, Cvar_Set2(), FS_ConditionalRestart(), clientStatic_t::oldGame, clientStatic_t::oldGameSet, qfalse, and qtrue.
Referenced by CL_Disconnect().
CL_OpenedPK3List_f()
void CL_OpenedPK3List_f (void)
Definition at line 1888 of file cl_main.c.
{
     Com_Printf("Opened PK3 Names: %s\n", FS_LoadedPakNames());
 }
References Com_Printf(), and FS_LoadedPakNames().
Referenced by CL_Init().
CL_PacketEvent()
void CL_PacketEvent (netadr_t from, msg_t * msg)
Definition at line 2689 of file cl_main.c.
{
     int     headerBytes;
     clc.lastPacketTime = cls.realtime;
     if ( msg->cursize >= 4 && *(int *)msg->data == -1 ) {
         CL_ConnectionlessPacket( from, msg );
         return;
     }
     if ( clc.state < CA_CONNECTED ) {
         return;     // can't be a valid sequenced packet
     }
     if ( msg->cursize < 4 ) {
         Com_Printf ("%s: Runt packet\n", NET_AdrToStringwPort( from ));
         return;
     }
     //
     // packet from server
     //
     if ( !NET_CompareAdr( from, clc.netchan.remoteAddress ) ) {
         Com_DPrintf ("%s:sequenced packet without connection\n"
             , NET_AdrToStringwPort( from ) );
         // FIXME: send a client disconnect?
         return;
     }
     if (!CL_Netchan_Process( &clc.netchan, msg) ) {
         return;     // out of order, duplicated, etc
     }
     // the header is different lengths for reliable and unreliable messages
     headerBytes = msg->readcount;
     // track the last message received so it can be returned in
     // client messages, allowing the server to detect a dropped
     // gamestate
     clc.serverMessageSequence = LittleLong( *(int *)msg->data );
     clc.lastPacketTime = cls.realtime;
     CL_ParseServerMessage( msg );
     //
     // we don't know if it is ok to save a demo message until
     // after we have parsed the frame
     //
     if ( clc.demorecording && !clc.demowaiting ) {
         CL_WriteDemoMessage( msg, headerBytes );
     }
 }
Referenced by Com_EventLoop(), and NET_Event().
CL_Ping_f()
void CL_Ping_f (void)
Definition at line 4229 of file cl_main.c.
{
     netadr_t    to;
     ping_t*     pingptr;
     char*       server;
     int         argc;
     netadrtype_t    family = NA_UNSPEC;
     argc = Cmd_Argc();
     if ( argc != 2 && argc != 3 ) {
         Com_Printf( "usage: ping [-4|-6] server\n");
         return;
     }
     if(argc == 2)
         server = Cmd_Argv(1);
     else
     {
         if(!strcmp(Cmd_Argv(1), "-4"))
             family = NA_IP;
         else if(!strcmp(Cmd_Argv(1), "-6"))
             family = NA_IP6;
         else
             Com_Printf( "warning: only -4 or -6 as address type understood.\n");
         server = Cmd_Argv(2);
     }
     Com_Memset( &to, 0, sizeof(netadr_t) );
     if ( !NET_StringToAdr( server, &to, family ) ) {
         return;
     }
     pingptr = CL_GetFreePing();
     memcpy( &pingptr->adr, &to, sizeof (netadr_t) );
     pingptr->start = Sys_Milliseconds();
     pingptr->time  = 0;
     CL_SetServerInfoByAddress(pingptr->adr, NULL, 0);
     NET_OutOfBandPrint( NS_CLIENT, to, "getinfo xxx" );
 }
References ping_t::adr, CL_GetFreePing(), CL_SetServerInfoByAddress(), Cmd_Argc(), Cmd_Argv(), Com_Memset, Com_Printf(), NA_IP, NA_IP6, NA_UNSPEC, NET_OutOfBandPrint(), NET_StringToAdr(), NS_CLIENT, NULL, ping_t::start, Sys_Milliseconds(), and ping_t::time.
Referenced by CL_Init().
CL_PlayDemo_f()
void CL_PlayDemo_f (void)
Definition at line 1058 of file cl_main.c.
{
     char        name[MAX_OSPATH];
     char        *arg, *ext_test;
     int         protocol, i;
     char        retry[MAX_OSPATH];
     if (Cmd_Argc() != 2) {
         Com_Printf ("demo <demoname>\n");
         return;
     }
     // make sure a local server is killed
     // 2 means don't force disconnect of local client
     Cvar_Set( "sv_killserver", "2" );
     // open the demo file
     arg = Cmd_Argv(1);
     CL_Disconnect( qtrue );
     // check for an extension .DEMOEXT_?? (?? is protocol)
     ext_test = strrchr(arg, '.');
     if(ext_test && !Q_stricmpn(ext_test + 1, DEMOEXT, ARRAY_LEN(DEMOEXT) - 1))
     {
         protocol = atoi(ext_test + ARRAY_LEN(DEMOEXT));
         for(i = 0; demo_protocols[i]; i++)
         {
             if(demo_protocols[i] == protocol)
                 break;
         }
         if(demo_protocols[i] || protocol == com_protocol->integer
 #ifdef LEGACY_PROTOCOL
            || protocol == com_legacyprotocol->integer
 #endif
           )
         {
             Com_sprintf(name, sizeof(name), "demos/%s", arg);
             FS_FOpenFileRead(name, &clc.demofile, qtrue);
         }
         else
         {
             int len;
             Com_Printf("Protocol %d not supported for demos\n", protocol);
             len = ext_test - arg;
             if(len >= ARRAY_LEN(retry))
                 len = ARRAY_LEN(retry) - 1;
             Q_strncpyz(retry, arg, len + 1);
             retry[len] = '\0';
             protocol = CL_WalkDemoExt(retry, name, &clc.demofile);
         }
     }
     else
         protocol = CL_WalkDemoExt(arg, name, &clc.demofile);
     if (!clc.demofile) {
         Com_Error( ERR_DROP, "couldn't open %s", name);
         return;
     }
     Q_strncpyz( clc.demoName, Cmd_Argv(1), sizeof( clc.demoName ) );
     Con_Close();
     clc.state = CA_CONNECTED;
     clc.demoplaying = qtrue;
     Q_strncpyz( clc.servername, Cmd_Argv(1), sizeof( clc.servername ) );
 #ifdef LEGACY_PROTOCOL
     if(protocol <= com_legacyprotocol->integer)
         clc.compat = qtrue;
     else
         clc.compat = qfalse;
 #endif
     // read demo messages until connected
     while ( clc.state >= CA_CONNECTED && clc.state < CA_PRIMED ) {
         CL_ReadDemoMessage();
     }
     // don't get the first snapshot this frame, to prevent the long
     // time from the gamestate load from messing causing a time skip
     clc.firstDemoFrameSkipped = qfalse;
 }
References ARRAY_LEN, CA_CONNECTED, CA_PRIMED, CL_Disconnect(), CL_ReadDemoMessage(), CL_WalkDemoExt(), clc, Cmd_Argc(), Cmd_Argv(), Com_Error(), Com_Printf(), com_protocol, Com_sprintf(), Con_Close(), Cvar_Set(), demo_protocols, DEMOEXT, clientConnection_t::demofile, clientConnection_t::demoName, clientConnection_t::demoplaying, ERR_DROP, clientConnection_t::firstDemoFrameSkipped, FS_FOpenFileRead(), MAX_OSPATH, Q_stricmpn(), Q_strncpyz(), qfalse, qtrue, clientConnection_t::servername, and clientConnection_t::state.
Referenced by CL_Init().
CL_Rcon_f()
void CL_Rcon_f (void)
Definition at line 1713 of file cl_main.c.
{
     char    message[MAX_RCON_MESSAGE];
     netadr_t    to;
     if ( !rcon_client_password->string ) {
         Com_Printf ("You must set 'rconpassword' before\n"
                     "issuing an rcon command.\n");
         return;
     }
     message[0] = -1;
     message[1] = -1;
     message[2] = -1;
     message[3] = -1;
     message[4] = 0;
     Q_strcat (message, MAX_RCON_MESSAGE, "rcon ");
     Q_strcat (message, MAX_RCON_MESSAGE, rcon_client_password->string);
     Q_strcat (message, MAX_RCON_MESSAGE, " ");
     // https://zerowing.idsoftware.com/bugzilla/show_bug.cgi?id=543
     Q_strcat (message, MAX_RCON_MESSAGE, Cmd_Cmd()+5);
     if ( clc.state >= CA_CONNECTED ) {
         to = clc.netchan.remoteAddress;
     } else {
         if (!strlen(rconAddress->string)) {
             Com_Printf ("You must either be connected,\n"
                         "or set the 'rconAddress' cvar\n"
                         "to issue rcon commands\n");
             return;
         }
         NET_StringToAdr (rconAddress->string, &to, NA_UNSPEC);
         if (to.port == 0) {
             to.port = BigShort (PORT_SERVER);
         }
     }
     NET_SendPacket (NS_CLIENT, strlen(message)+1, message, to);
 }
References CA_CONNECTED, clc, Cmd_Cmd(), Com_Printf(), MAX_RCON_MESSAGE, NA_UNSPEC, NET_SendPacket(), NET_StringToAdr(), clientConnection_t::netchan, NS_CLIENT, netadr_t::port, PORT_SERVER, Q_strcat(), rcon_client_password, rconAddress, netchan_t::remoteAddress, and clientConnection_t::state.
Referenced by CL_Init().
CL_ReadDemoMessage()
void CL_ReadDemoMessage (void)
Definition at line 923 of file cl_main.c.
{
     int         r;
     msg_t       buf;
     byte        bufData[ MAX_MSGLEN ];
     int         s;
     if ( !clc.demofile ) {
         CL_DemoCompleted ();
         return;
     }
     // get the sequence number
     r = FS_Read( &s, 4, clc.demofile);
     if ( r != 4 ) {
         CL_DemoCompleted ();
         return;
     }
     clc.serverMessageSequence = LittleLong( s );
     // init the message
     MSG_Init( &buf, bufData, sizeof( bufData ) );
     // get the length
     r = FS_Read (&buf.cursize, 4, clc.demofile);
     if ( r != 4 ) {
         CL_DemoCompleted ();
         return;
     }
     buf.cursize = LittleLong( buf.cursize );
     if ( buf.cursize == -1 ) {
         CL_DemoCompleted ();
         return;
     }
     if ( buf.cursize > buf.maxsize ) {
         Com_Error (ERR_DROP, "CL_ReadDemoMessage: demoMsglen > MAX_MSGLEN");
     }
     r = FS_Read( buf.data, buf.cursize, clc.demofile );
     if ( r != buf.cursize ) {
         Com_Printf( "Demo file was truncated.\n");
         CL_DemoCompleted ();
         return;
     }
     clc.lastPacketTime = cls.realtime;
     buf.readcount = 0;
     CL_ParseServerMessage( &buf );
 }
References CL_DemoCompleted(), CL_ParseServerMessage(), clc, cls, Com_Error(), Com_Printf(), clientConnection_t::demofile, ERR_DROP, FS_Read(), clientConnection_t::lastPacketTime, MAX_MSGLEN, MSG_Init(), clientStatic_t::realtime, and clientConnection_t::serverMessageSequence.
Referenced by CL_PlayDemo_f(), and CL_SetCGameTime().
CL_Reconnect_f()
void CL_Reconnect_f (void)
Definition at line 1585 of file cl_main.c.
{
     if ( !strlen( clc.servername ) || !strcmp( clc.servername, "localhost" ) ) {
         Com_Printf( "Can't reconnect to localhost.\n" );
         return;
     }
     Cvar_Set("ui_singlePlayerActive", "0");
     Cbuf_AddText( va("connect %s\n", clc.servername ) );
 }
References Cbuf_AddText(), clc, Com_Printf(), Cvar_Set(), clientConnection_t::servername, and va().
Referenced by CL_DownloadsComplete(), and CL_Init().
CL_Record_f()
void CL_Record_f (void)
Definition at line 684 of file cl_main.c.
{
     char        name[MAX_OSPATH];
     byte        bufData[MAX_MSGLEN];
     msg_t   buf;
     int         i;
     int         len;
     entityState_t   *ent;
     entityState_t   nullstate;
     char        *s;
     if ( Cmd_Argc() > 2 ) {
         Com_Printf ("record <demoname>\n");
         return;
     }
     if ( clc.demorecording ) {
         if (!clc.spDemoRecording) {
             Com_Printf ("Already recording.\n");
         }
         return;
     }
     if ( clc.state != CA_ACTIVE ) {
         Com_Printf ("You must be in a level to record.\n");
         return;
     }
   // sync 0 doesn't prevent recording, so not forcing it off .. everyone does g_sync 1 ; record ; g_sync 0 ..
     if ( NET_IsLocalAddress( clc.serverAddress ) && !Cvar_VariableValue( "g_synchronousClients" ) ) {
         Com_Printf (S_COLOR_YELLOW "WARNING: You should set 'g_synchronousClients 1' for smoother demo recording\n");
     }
     if ( Cmd_Argc() == 2 ) {
         s = Cmd_Argv(1);
         Q_strncpyz( demoName, s, sizeof( demoName ) );
 #ifdef LEGACY_PROTOCOL
         if(clc.compat)
             Com_sprintf(name, sizeof(name), "demos/%s.%s%d", demoName, DEMOEXT, com_legacyprotocol->integer);
         else
 #endif
             Com_sprintf(name, sizeof(name), "demos/%s.%s%d", demoName, DEMOEXT, com_protocol->integer);
     } else {
         int     number;
         // scan for a free demo name
         for ( number = 0 ; number <= 9999 ; number++ ) {
             CL_DemoFilename( number, demoName );
 #ifdef LEGACY_PROTOCOL
             if(clc.compat)
                 Com_sprintf(name, sizeof(name), "demos/%s.%s%d", demoName, DEMOEXT, com_legacyprotocol->integer);
             else
 #endif
                 Com_sprintf(name, sizeof(name), "demos/%s.%s%d", demoName, DEMOEXT, com_protocol->integer);
             if (!FS_FileExists(name))
                 break;  // file doesn't exist
         }
     }
     // open the demo file
     Com_Printf ("recording to %s.\n", name);
     clc.demofile = FS_FOpenFileWrite( name );
     if ( !clc.demofile ) {
         Com_Printf ("ERROR: couldn't open.\n");
         return;
     }
     clc.demorecording = qtrue;
     Q_strncpyz( clc.demoName, demoName, sizeof( clc.demoName ) );
     // don't start saving messages until a non-delta compressed message is received
     clc.demowaiting = qtrue;
     // write out the gamestate message
     MSG_Init (&buf, bufData, sizeof(bufData));
     MSG_Bitstream(&buf);
     // NOTE, MRE: all server->client messages now acknowledge
     MSG_WriteLong( &buf, clc.reliableSequence );
     MSG_WriteByte (&buf, svc_gamestate);
     MSG_WriteLong (&buf, clc.serverCommandSequence );
     // configstrings
     for ( i = 0 ; i < MAX_CONFIGSTRINGS ; i++ ) {
         if ( !cl.gameState.stringOffsets[i] ) {
             continue;
         }
         s = cl.gameState.stringData + cl.gameState.stringOffsets[i];
         MSG_WriteByte (&buf, svc_configstring);
         MSG_WriteShort (&buf, i);
         MSG_WriteBigString (&buf, s);
     }
     // baselines
     Com_Memset (&nullstate, 0, sizeof(nullstate));
     for ( i = 0; i < MAX_GENTITIES ; i++ ) {
         ent = &cl.entityBaselines[i];
         if ( !ent->number ) {
             continue;
         }
         MSG_WriteByte (&buf, svc_baseline);
         MSG_WriteDeltaEntity (&buf, &nullstate, ent, qtrue );
     }
     MSG_WriteByte( &buf, svc_EOF );
     // finished writing the gamestate stuff
     // write the client num
     MSG_WriteLong(&buf, clc.clientNum);
     // write the checksum feed
     MSG_WriteLong(&buf, clc.checksumFeed);
     // finished writing the client packet
     MSG_WriteByte( &buf, svc_EOF );
     // write it to the demo file
     len = LittleLong( clc.serverMessageSequence - 1 );
     FS_Write (&len, 4, clc.demofile);
     len = LittleLong (buf.cursize);
     FS_Write (&len, 4, clc.demofile);
     FS_Write (buf.data, buf.cursize, clc.demofile);
     // the rest of the demo file will be copied from net messages
 }
References CA_ACTIVE, clientConnection_t::checksumFeed, cl, CL_DemoFilename(), clc, clientConnection_t::clientNum, Cmd_Argc(), Cmd_Argv(), Com_Memset, Com_Printf(), com_protocol, Com_sprintf(), Cvar_VariableValue(), DEMOEXT, clientConnection_t::demofile, clientConnection_t::demoName, demoName, clientConnection_t::demorecording, clientConnection_t::demowaiting, clientActive_t::entityBaselines, FS_FileExists(), FS_FOpenFileWrite(), FS_Write(), clientActive_t::gameState, MAX_CONFIGSTRINGS, MAX_GENTITIES, MAX_MSGLEN, MAX_OSPATH, MSG_Bitstream(), MSG_Init(), MSG_WriteBigString(), MSG_WriteByte(), MSG_WriteDeltaEntity(), MSG_WriteLong(), MSG_WriteShort(), NET_IsLocalAddress(), Q_strncpyz(), qtrue, clientConnection_t::reliableSequence, S_COLOR_YELLOW, clientConnection_t::serverAddress, clientConnection_t::serverCommandSequence, clientConnection_t::serverMessageSequence, clientConnection_t::spDemoRecording, clientConnection_t::state, gameState_t::stringData, gameState_t::stringOffsets, svc_baseline, svc_configstring, svc_EOF, and svc_gamestate.
Referenced by CL_Init().
CL_ReferencedPK3List_f()
void CL_ReferencedPK3List_f (void)
Definition at line 1897 of file cl_main.c.
{
     Com_Printf("Referenced PK3 Names: %s\n", FS_ReferencedPakNames());
 }
References Com_Printf(), and FS_ReferencedPakNames().
Referenced by CL_Init().
CL_RefMalloc()
void* CL_RefMalloc (int size)
Definition at line 3058 of file cl_main.c.
{
     return Z_TagMalloc( size, TAG_RENDERER );
 }
References TAG_RENDERER, and Z_TagMalloc.
Referenced by CL_InitRef().
CL_RequestMotd()
void CL_RequestMotd (void)
Definition at line 1510 of file cl_main.c.
{
 #ifdef UPDATE_SERVER_NAME
     char        info[MAX_INFO_STRING];
     if ( !cl_motd->integer ) {
         return;
     }
     Com_Printf( "Resolving %s\n", UPDATE_SERVER_NAME );
     if ( !NET_StringToAdr( UPDATE_SERVER_NAME, &cls.updateServer, NA_IP ) ) {
         Com_Printf( "Couldn't resolve address\n" );
         return;
     }
     cls.updateServer.port = BigShort( PORT_UPDATE );
     Com_Printf( "%s resolved to %i.%i.%i.%i:%i\n", UPDATE_SERVER_NAME,
         cls.updateServer.ip[0], cls.updateServer.ip[1],
         cls.updateServer.ip[2], cls.updateServer.ip[3],
         BigShort( cls.updateServer.port ) );
     info[0] = 0;
     Com_sprintf( cls.updateChallenge, sizeof( cls.updateChallenge ), "%i", ((rand() << 16) ^ rand()) ^ Com_Milliseconds());
     Info_SetValueForKey( info, "challenge", cls.updateChallenge );
     Info_SetValueForKey( info, "renderer", cls.glconfig.renderer_string );
     Info_SetValueForKey( info, "version", com_version->string );
     NET_OutOfBandPrint( NS_CLIENT, cls.updateServer, "getmotd \"%s\"\n", info );
 #endif
 }
References cls, Com_Milliseconds(), Com_Printf(), Com_sprintf(), com_version, clientStatic_t::glconfig, info, Info_SetValueForKey(), netadr_t::ip, MAX_INFO_STRING, NA_IP, NET_OutOfBandPrint(), NET_StringToAdr(), NS_CLIENT, netadr_t::port, PORT_UPDATE, glconfig_t::renderer_string, clientStatic_t::updateChallenge, and clientStatic_t::updateServer.
Referenced by CL_Connect_f().
CL_ResetPureClientAtServer()
void CL_ResetPureClientAtServer (void)
Definition at line 1775 of file cl_main.c.
{
     CL_AddReliableCommand("vdr", qfalse);
 }
References CL_AddReliableCommand(), and qfalse.
Referenced by CL_Vid_Restart_f().
CL_ScaledMilliseconds()
int CL_ScaledMilliseconds (void)
Definition at line 3062 of file cl_main.c.
{
     return Sys_Milliseconds()*com_timescale->value;
 }
References com_timescale, and Sys_Milliseconds().
Referenced by CIN_RunCinematic(), CL_InitRef(), RoQ_init(), and RoQInterrupt().
CL_SendPureChecksums()
void CL_SendPureChecksums (void)
Definition at line 1761 of file cl_main.c.
{
     char cMsg[MAX_INFO_VALUE];
     // if we are pure we need to send back a command with our referenced pk3 checksums
     Com_sprintf(cMsg, sizeof(cMsg), "cp %d %s", cl.serverId, FS_ReferencedPakPureChecksums());
     CL_AddReliableCommand(cMsg, qfalse);
 }
References cl, CL_AddReliableCommand(), Com_sprintf(), FS_ReferencedPakPureChecksums(), MAX_INFO_VALUE, qfalse, and clientActive_t::serverId.
Referenced by CL_DownloadsComplete(), and CL_Vid_Restart_f().
CL_ServerInfoPacket()
void CL_ServerInfoPacket (netadr_t from, msg_t * msg)
Definition at line 3643 of file cl_main.c.
{
     int     i, type;
     char    info[MAX_INFO_STRING];
     char    *infoString;
     int     prot;
     char    *gamename;
     qboolean gameMismatch;
     infoString = MSG_ReadString( msg );
     // if this isn't the correct gamename, ignore it
     gamename = Info_ValueForKey( infoString, "gamename" );
 #ifdef LEGACY_PROTOCOL
     // gamename is optional for legacy protocol
     if (com_legacyprotocol->integer && !*gamename)
         gameMismatch = qfalse;
     else
 #endif
         gameMismatch = !*gamename || strcmp(gamename, com_gamename->string) != 0;
     if (gameMismatch)
     {
         Com_DPrintf( "Game mismatch in info packet: %s\n", infoString );
         return;
     }
     // if this isn't the correct protocol version, ignore it
     prot = atoi( Info_ValueForKey( infoString, "protocol" ) );
     if(prot != com_protocol->integer
 #ifdef LEGACY_PROTOCOL
        && prot != com_legacyprotocol->integer
 #endif
       )
     {
         Com_DPrintf( "Different protocol info packet: %s\n", infoString );
         return;
     }
     // iterate servers waiting for ping response
     for (i=0; i<MAX_PINGREQUESTS; i++)
     {
         if ( cl_pinglist[i].adr.port && !cl_pinglist[i].time && NET_CompareAdr( from, cl_pinglist[i].adr ) )
         {
             // calc ping time
             cl_pinglist[i].time = Sys_Milliseconds() - cl_pinglist[i].start;
             Com_DPrintf( "ping time %dms from %s\n", cl_pinglist[i].time, NET_AdrToString( from ) );
             // save of info
             Q_strncpyz( cl_pinglist[i].info, infoString, sizeof( cl_pinglist[i].info ) );
             // tack on the net type
             // NOTE: make sure these types are in sync with the netnames strings in the UI
             switch (from.type)
             {
                 case NA_BROADCAST:
                 case NA_IP:
                     type = 1;
                     break;
                 case NA_IP6:
                     type = 2;
                     break;
                 default:
                     type = 0;
                     break;
             }
             Info_SetValueForKey( cl_pinglist[i].info, "nettype", va("%d", type) );
             CL_SetServerInfoByAddress(from, infoString, cl_pinglist[i].time);
             return;
         }
     }
     // if not just sent a local broadcast or pinging local servers
     if (cls.pingUpdateSource != AS_LOCAL) {
         return;
     }
     for ( i = 0 ; i < MAX_OTHER_SERVERS ; i++ ) {
         // empty slot
         if ( cls.localServers[i].adr.port == 0 ) {
             break;
         }
         // avoid duplicate
         if ( NET_CompareAdr( from, cls.localServers[i].adr ) ) {
             return;
         }
     }
     if ( i == MAX_OTHER_SERVERS ) {
         Com_DPrintf( "MAX_OTHER_SERVERS hit, dropping infoResponse\n" );
         return;
     }
     // add this to the list
     cls.numlocalservers = i+1;
     cls.localServers[i].adr = from;
     cls.localServers[i].clients = 0;
     cls.localServers[i].hostName[0] = '\0';
     cls.localServers[i].mapName[0] = '\0';
     cls.localServers[i].maxClients = 0;
     cls.localServers[i].maxPing = 0;
     cls.localServers[i].minPing = 0;
     cls.localServers[i].ping = -1;
     cls.localServers[i].game[0] = '\0';
     cls.localServers[i].gameType = 0;
     cls.localServers[i].netType = from.type;
     cls.localServers[i].g_humanplayers = 0;
     cls.localServers[i].g_needpass = 0;
     Q_strncpyz( info, MSG_ReadString( msg ), MAX_INFO_STRING );
     if (strlen(info)) {
         if (info[strlen(info)-1] != '\n') {
             strncat(info, "\n", sizeof(info) - 1);
         }
         Com_Printf( "%s: %s", NET_AdrToStringwPort( from ), info );
     }
 }
References serverInfo_t::adr, AS_LOCAL, cl_pinglist, CL_SetServerInfoByAddress(), serverInfo_t::clients, cls, Com_DPrintf(), com_gamename, Com_Printf(), com_protocol, serverInfo_t::g_humanplayers, serverInfo_t::g_needpass, serverInfo_t::game, serverInfo_t::gameType, serverInfo_t::hostName, info, Info_SetValueForKey(), Info_ValueForKey(), clientStatic_t::localServers, serverInfo_t::mapName, MAX_INFO_STRING, MAX_OTHER_SERVERS, MAX_PINGREQUESTS, serverInfo_t::maxClients, serverInfo_t::maxPing, serverInfo_t::minPing, MSG_ReadString(), NA_BROADCAST, NA_IP, NA_IP6, NET_AdrToString(), NET_AdrToStringwPort(), NET_CompareAdr(), serverInfo_t::netType, clientStatic_t::numlocalservers, serverInfo_t::ping, clientStatic_t::pingUpdateSource, netadr_t::port, Q_strncpyz(), qfalse, ping_t::start, Sys_Milliseconds(), ping_t::time, netadr_t::type, and va().
Referenced by CL_ConnectionlessPacket().
CL_ServersResponsePacket()
void CL_ServersResponsePacket (const netadr_t * from, msg_t * msg, qboolean extended)
Definition at line 2360 of file cl_main.c.
{
     int             i, j, count, total;
     netadr_t addresses[MAX_SERVERSPERPACKET];
     int             numservers;
     byte*           buffptr;
     byte*           buffend;
     Com_Printf("CL_ServersResponsePacket\n");
     if (cls.numglobalservers == -1) {
         // state to detect lack of servers or lack of response
         cls.numglobalservers = 0;
         cls.numGlobalServerAddresses = 0;
     }
     // parse through server response string
     numservers = 0;
     buffptr    = msg->data;
     buffend    = buffptr + msg->cursize;
     // advance to initial token
     do
     {
         if(*buffptr == '\\' || (extended && *buffptr == '/'))
             break;
         buffptr++;
     } while (buffptr < buffend);
     while (buffptr + 1 < buffend)
     {
         // IPv4 address
         if (*buffptr == '\\')
         {
             buffptr++;
             if (buffend - buffptr < sizeof(addresses[numservers].ip) + sizeof(addresses[numservers].port) + 1)
                 break;
             for(i = 0; i < sizeof(addresses[numservers].ip); i++)
                 addresses[numservers].ip[i] = *buffptr++;
             addresses[numservers].type = NA_IP;
         }
         // IPv6 address, if it's an extended response
         else if (extended && *buffptr == '/')
         {
             buffptr++;
             if (buffend - buffptr < sizeof(addresses[numservers].ip6) + sizeof(addresses[numservers].port) + 1)
                 break;
             for(i = 0; i < sizeof(addresses[numservers].ip6); i++)
                 addresses[numservers].ip6[i] = *buffptr++;
             addresses[numservers].type = NA_IP6;
             addresses[numservers].scope_id = from->scope_id;
         }
         else
             // syntax error!
             break;
         // parse out port
         addresses[numservers].port = (*buffptr++) << 8;
         addresses[numservers].port += *buffptr++;
         addresses[numservers].port = BigShort( addresses[numservers].port );
         // syntax check
         if (*buffptr != '\\' && *buffptr != '/')
             break;
         numservers++;
         if (numservers >= MAX_SERVERSPERPACKET)
             break;
     }
     count = cls.numglobalservers;
     for (i = 0; i < numservers && count < MAX_GLOBAL_SERVERS; i++) {
         // build net address
         serverInfo_t *server = &cls.globalServers[count];
         // Tequila: It's possible to have sent many master server requests. Then
         // we may receive many times the same addresses from the master server.
         // We just avoid to add a server if it is still in the global servers list.
         for (j = 0; j < count; j++)
         {
             if (NET_CompareAdr(cls.globalServers[j].adr, addresses[i]))
                 break;
         }
         if (j < count)
             continue;
         CL_InitServerInfo( server, &addresses[i] );
         // advance to next slot
         count++;
     }
     // if getting the global list
     if ( count >= MAX_GLOBAL_SERVERS && cls.numGlobalServerAddresses < MAX_GLOBAL_SERVERS )
     {
         // if we couldn't store the servers in the main list anymore
         for (; i < numservers && cls.numGlobalServerAddresses < MAX_GLOBAL_SERVERS; i++)
         {
             // just store the addresses in an additional list
             cls.globalServerAddresses[cls.numGlobalServerAddresses++] = addresses[i];
         }
     }
     cls.numglobalservers = count;
     total = count + cls.numGlobalServerAddresses;
     Com_Printf("%d servers parsed (total %d)\n", numservers, total);
 }
References serverInfo_t::adr, CL_InitServerInfo(), cls, Com_Printf(), msg_t::cursize, msg_t::data, clientStatic_t::globalServerAddresses, clientStatic_t::globalServers, netadr_t::ip, netadr_t::ip6, MAX_GLOBAL_SERVERS, MAX_SERVERSPERPACKET, NA_IP, NA_IP6, NET_CompareAdr(), clientStatic_t::numGlobalServerAddresses, clientStatic_t::numglobalservers, netadr_t::port, netadr_t::scope_id, and netadr_t::type.
Referenced by CL_ConnectionlessPacket().
CL_ServerStatus()
int CL_ServerStatus (char * serverAddress, char * serverStatusString, int maxLen)
Definition at line 3802 of file cl_main.c.
{
     int i;
     netadr_t    to;
     serverStatus_t *serverStatus;
     // if no server address then reset all server status requests
     if ( !serverAddress ) {
         for (i = 0; i < MAX_SERVERSTATUSREQUESTS; i++) {
             cl_serverStatusList[i].address.port = 0;
             cl_serverStatusList[i].retrieved = qtrue;
         }
         return qfalse;
     }
     // get the address
     if ( !NET_StringToAdr( serverAddress, &to, NA_UNSPEC) ) {
         return qfalse;
     }
     serverStatus = CL_GetServerStatus( to );
     // if no server status string then reset the server status request for this address
     if ( !serverStatusString ) {
         serverStatus->retrieved = qtrue;
         return qfalse;
     }
     // if this server status request has the same address
     if ( NET_CompareAdr( to, serverStatus->address) ) {
         // if we recieved an response for this server status request
         if (!serverStatus->pending) {
             Q_strncpyz(serverStatusString, serverStatus->string, maxLen);
             serverStatus->retrieved = qtrue;
             serverStatus->startTime = 0;
             return qtrue;
         }
         // resend the request regularly
         else if ( serverStatus->startTime < Com_Milliseconds() - cl_serverStatusResendTime->integer ) {
             serverStatus->print = qfalse;
             serverStatus->pending = qtrue;
             serverStatus->retrieved = qfalse;
             serverStatus->time = 0;
             serverStatus->startTime = Com_Milliseconds();
             NET_OutOfBandPrint( NS_CLIENT, to, "getstatus" );
             return qfalse;
         }
     }
     // if retrieved
     else if ( serverStatus->retrieved ) {
         serverStatus->address = to;
         serverStatus->print = qfalse;
         serverStatus->pending = qtrue;
         serverStatus->retrieved = qfalse;
         serverStatus->startTime = Com_Milliseconds();
         serverStatus->time = 0;
         NET_OutOfBandPrint( NS_CLIENT, to, "getstatus" );
         return qfalse;
     }
     return qfalse;
 }
References CL_GetServerStatus(), cl_serverStatusList, cl_serverStatusResendTime, Com_Milliseconds(), MAX_SERVERSTATUSREQUESTS, NA_UNSPEC, NET_CompareAdr(), NET_OutOfBandPrint(), NET_StringToAdr(), NS_CLIENT, Q_strncpyz(), qfalse, and qtrue.
Referenced by LAN_GetServerStatus().
CL_ServerStatus_f()
void CL_ServerStatus_f (void)
Definition at line 4383 of file cl_main.c.
{
     netadr_t    to, *toptr = NULL;
     char        *server;
     serverStatus_t *serverStatus;
     int         argc;
     netadrtype_t    family = NA_UNSPEC;
     argc = Cmd_Argc();
     if ( argc != 2 && argc != 3 )
     {
         if (clc.state != CA_ACTIVE || clc.demoplaying)
         {
             Com_Printf ("Not connected to a server.\n");
             Com_Printf( "usage: serverstatus [-4|-6] server\n");
             return;
         }
         toptr = &clc.serverAddress;
     }
     if(!toptr)
     {
         Com_Memset( &to, 0, sizeof(netadr_t) );
         if(argc == 2)
             server = Cmd_Argv(1);
         else
         {
             if(!strcmp(Cmd_Argv(1), "-4"))
                 family = NA_IP;
             else if(!strcmp(Cmd_Argv(1), "-6"))
                 family = NA_IP6;
             else
                 Com_Printf( "warning: only -4 or -6 as address type understood.\n");
             server = Cmd_Argv(2);
         }
         toptr = &to;
         if ( !NET_StringToAdr( server, toptr, family ) )
             return;
     }
     NET_OutOfBandPrint( NS_CLIENT, *toptr, "getstatus" );
     serverStatus = CL_GetServerStatus( *toptr );
     serverStatus->address = *toptr;
     serverStatus->print = qtrue;
     serverStatus->pending = qtrue;
 }
References CA_ACTIVE, CL_GetServerStatus(), clc, Cmd_Argc(), Cmd_Argv(), Com_Memset, Com_Printf(), clientConnection_t::demoplaying, NA_IP, NA_IP6, NA_UNSPEC, NET_OutOfBandPrint(), NET_StringToAdr(), NS_CLIENT, NULL, qtrue, clientConnection_t::serverAddress, and clientConnection_t::state.
Referenced by CL_Init().
CL_ServerStatusResponse()
void CL_ServerStatusResponse (netadr_t from, msg_t * msg)
Definition at line 3865 of file cl_main.c.
{
     char    *s;
     char    info[MAX_INFO_STRING];
     int     i, l, score, ping;
     int     len;
     serverStatus_t *serverStatus;
     serverStatus = NULL;
     for (i = 0; i < MAX_SERVERSTATUSREQUESTS; i++) {
         if ( NET_CompareAdr( from, cl_serverStatusList[i].address ) ) {
             serverStatus = &cl_serverStatusList[i];
             break;
         }
     }
     // if we didn't request this server status
     if (!serverStatus) {
         return;
     }
     s = MSG_ReadStringLine( msg );
     len = 0;
     Com_sprintf(&serverStatus->string[len], sizeof(serverStatus->string)-len, "%s", s);
     if (serverStatus->print) {
         Com_Printf("Server settings:\n");
         // print cvars
         while (*s) {
             for (i = 0; i < 2 && *s; i++) {
                 if (*s == '\\')
                     s++;
                 l = 0;
                 while (*s) {
                     info[l++] = *s;
                     if (l >= MAX_INFO_STRING-1)
                         break;
                     s++;
                     if (*s == '\\') {
                         break;
                     }
                 }
                 info[l] = '\0';
                 if (i) {
                     Com_Printf("%s\n", info);
                 }
                 else {
                     Com_Printf("%-24s", info);
                 }
             }
         }
     }
     len = strlen(serverStatus->string);
     Com_sprintf(&serverStatus->string[len], sizeof(serverStatus->string)-len, "\\");
     if (serverStatus->print) {
         Com_Printf("\nPlayers:\n");
         Com_Printf("num: score: ping: name:\n");
     }
     for (i = 0, s = MSG_ReadStringLine( msg ); *s; s = MSG_ReadStringLine( msg ), i++) {
         len = strlen(serverStatus->string);
         Com_sprintf(&serverStatus->string[len], sizeof(serverStatus->string)-len, "\\%s", s);
         if (serverStatus->print) {
             score = ping = 0;
             sscanf(s, "%d %d", &score, &ping);
             s = strchr(s, ' ');
             if (s)
                 s = strchr(s+1, ' ');
             if (s)
                 s++;
             else
                 s = "unknown";
             Com_Printf("%-2d   %-3d    %-3d   %s\n", i, score, ping, s );
         }
     }
     len = strlen(serverStatus->string);
     Com_sprintf(&serverStatus->string[len], sizeof(serverStatus->string)-len, "\\");
     serverStatus->time = Com_Milliseconds();
     serverStatus->address = from;
     serverStatus->pending = qfalse;
     if (serverStatus->print) {
         serverStatus->retrieved = qtrue;
     }
 }
References cl_serverStatusList, Com_Milliseconds(), Com_Printf(), Com_sprintf(), info, MAX_INFO_STRING, MAX_SERVERSTATUSREQUESTS, MSG_ReadStringLine(), NET_CompareAdr(), NULL, qfalse, and qtrue.
Referenced by CL_ConnectionlessPacket().
CL_SetModel_f()
void CL_SetModel_f (void)
Definition at line 3182 of file cl_main.c.
{
     char    *arg;
     char    name[256];
     arg = Cmd_Argv( 1 );
     if (arg[0]) {
         Cvar_Set( "model", arg );
         Cvar_Set( "headmodel", arg );
     } else {
         Cvar_VariableStringBuffer( "model", name, sizeof(name) );
         Com_Printf("model is set to %s\n", name);
     }
 }
References Cmd_Argv(), Com_Printf(), Cvar_Set(), and Cvar_VariableStringBuffer().
Referenced by CL_Init().
CL_SetServerInfo()
static void CL_SetServerInfo (serverInfo_t * server, const char * info, int ping) static
Definition at line 3596 of file cl_main.c.
{
     if (server) {
         if (info) {
             server->clients = atoi(Info_ValueForKey(info, "clients"));
             Q_strncpyz(server->hostName,Info_ValueForKey(info, "hostname"), MAX_NAME_LENGTH);
             Q_strncpyz(server->mapName, Info_ValueForKey(info, "mapname"), MAX_NAME_LENGTH);
             server->maxClients = atoi(Info_ValueForKey(info, "sv_maxclients"));
             Q_strncpyz(server->game,Info_ValueForKey(info, "game"), MAX_NAME_LENGTH);
             server->gameType = atoi(Info_ValueForKey(info, "gametype"));
             server->netType = atoi(Info_ValueForKey(info, "nettype"));
             server->minPing = atoi(Info_ValueForKey(info, "minping"));
             server->maxPing = atoi(Info_ValueForKey(info, "maxping"));
             server->g_humanplayers = atoi(Info_ValueForKey(info, "g_humanplayers"));
             server->g_needpass = atoi(Info_ValueForKey(info, "g_needpass"));
         }
         server->ping = ping;
     }
 }
References serverInfo_t::clients, serverInfo_t::g_humanplayers, serverInfo_t::g_needpass, serverInfo_t::game, serverInfo_t::gameType, serverInfo_t::hostName, info, Info_ValueForKey(), serverInfo_t::mapName, MAX_NAME_LENGTH, serverInfo_t::maxClients, serverInfo_t::maxPing, serverInfo_t::minPing, serverInfo_t::netType, serverInfo_t::ping, and Q_strncpyz().
Referenced by CL_SetServerInfoByAddress().
CL_SetServerInfoByAddress()
static void CL_SetServerInfoByAddress (netadr_t from, const char * info, int ping) static
Definition at line 3615 of file cl_main.c.
{
     int i;
     for (i = 0; i < MAX_OTHER_SERVERS; i++) {
         if (NET_CompareAdr(from, cls.localServers[i].adr)) {
             CL_SetServerInfo(&cls.localServers[i], info, ping);
         }
     }
     for (i = 0; i < MAX_GLOBAL_SERVERS; i++) {
         if (NET_CompareAdr(from, cls.globalServers[i].adr)) {
             CL_SetServerInfo(&cls.globalServers[i], info, ping);
         }
     }
     for (i = 0; i < MAX_OTHER_SERVERS; i++) {
         if (NET_CompareAdr(from, cls.favoriteServers[i].adr)) {
             CL_SetServerInfo(&cls.favoriteServers[i], info, ping);
         }
     }
 }
References serverInfo_t::adr, CL_SetServerInfo(), cls, clientStatic_t::favoriteServers, clientStatic_t::globalServers, info, clientStatic_t::localServers, MAX_GLOBAL_SERVERS, MAX_OTHER_SERVERS, and NET_CompareAdr().
Referenced by CL_GetPing(), CL_Ping_f(), and CL_ServerInfoPacket().
CL_ShowIP_f()
void CL_ShowIP_f (void)
Definition at line 4440 of file cl_main.c.
{
     Sys_ShowIP();
 }
References Sys_ShowIP().
Referenced by CL_Init().
CL_Shutdown()
void CL_Shutdown (char * finalmsg, qboolean disconnect, qboolean quit)
Definition at line 3534 of file cl_main.c.
 {
     static qboolean recursive = qfalse;
     // check whether the client is running at all.
     if(!(com_cl_running && com_cl_running->integer))
         return;
     Com_Printf( "----- Client Shutdown (%s) -----\n", finalmsg );
     if ( recursive ) {
         Com_Printf( "WARNING: Recursive shutdown\n" );
         return;
     }
     recursive = qtrue;
     noGameRestart = quit;
     if(disconnect)
         CL_Disconnect(qtrue);
     CL_ClearMemory(qtrue);
     CL_Snd_Shutdown();
     Cmd_RemoveCommand ("cmd");
     Cmd_RemoveCommand ("configstrings");
     Cmd_RemoveCommand ("clientinfo");
     Cmd_RemoveCommand ("snd_restart");
     Cmd_RemoveCommand ("vid_restart");
     Cmd_RemoveCommand ("disconnect");
     Cmd_RemoveCommand ("record");
     Cmd_RemoveCommand ("demo");
     Cmd_RemoveCommand ("cinematic");
     Cmd_RemoveCommand ("stoprecord");
     Cmd_RemoveCommand ("connect");
     Cmd_RemoveCommand ("reconnect");
     Cmd_RemoveCommand ("localservers");
     Cmd_RemoveCommand ("globalservers");
     Cmd_RemoveCommand ("rcon");
     Cmd_RemoveCommand ("ping");
     Cmd_RemoveCommand ("serverstatus");
     Cmd_RemoveCommand ("showip");
     Cmd_RemoveCommand ("fs_openedList");
     Cmd_RemoveCommand ("fs_referencedList");
     Cmd_RemoveCommand ("model");
     Cmd_RemoveCommand ("video");
     Cmd_RemoveCommand ("stopvideo");
     CL_ShutdownInput();
     Con_Shutdown();
     Cvar_Set( "cl_running", "0" );
     recursive = qfalse;
     Com_Memset( &cls, 0, sizeof( cls ) );
     Key_SetCatcher( 0 );
     Com_Printf( "-----------------------\n" );
 }
Referenced by Com_Error(), Com_GameRestart(), Com_Quit_f(), and Sys_SigHandler().
CL_ShutdownAll()
void CL_ShutdownAll (qboolean shutdownRef)
Definition at line 1192 of file cl_main.c.
 {
     if(CL_VideoRecording())
         CL_CloseAVI();
     if(clc.demorecording)
         CL_StopRecord_f();
 #ifdef USE_CURL
     CL_cURL_Shutdown();
 #endif
     // clear sounds
     S_DisableSounds();
     // shutdown CGame
     CL_ShutdownCGame();
     // shutdown UI
     CL_ShutdownUI();
     // shutdown the renderer
     if(shutdownRef)
         CL_ShutdownRef();
     else if(re.Shutdown)
         re.Shutdown(qfalse);        // don't destroy window or context
     cls.uiStarted = qfalse;
     cls.cgameStarted = qfalse;
     cls.rendererStarted = qfalse;
     cls.soundRegistered = qfalse;
 }
Referenced by CL_ClearMemory(), and SV_SpawnServer().
CL_ShutdownRef()
void CL_ShutdownRef (void)
Definition at line 2981 of file cl_main.c.
{
     if ( !re.Shutdown ) {
         return;
     }
     re.Shutdown( qtrue );
     Com_Memset( &re, 0, sizeof( re ) );
 }
References Com_Memset, qtrue, re, and refexport_t::Shutdown.
Referenced by CL_ShutdownAll(), and CL_Vid_Restart_f().
CL_Snd_Restart_f()
void CL_Snd_Restart_f (void)
Definition at line 1875 of file cl_main.c.
 {
     CL_Snd_Shutdown();
     // sound will be reinitialized by vid_restart
     CL_Vid_Restart_f();
 }
References CL_Snd_Shutdown(), and CL_Vid_Restart_f().
Referenced by CL_Init().
CL_Snd_Shutdown()
void CL_Snd_Shutdown (void)
Definition at line 1860 of file cl_main.c.
 {
     S_Shutdown();
     cls.soundStarted = qfalse;
 }
Referenced by CL_Shutdown(), and CL_Snd_Restart_f().
CL_StartDemoLoop()
void CL_StartDemoLoop (void)
Definition at line 1154 of file cl_main.c.
{
     // start the demo loop again
     Cbuf_AddText ("d1\n");
     Key_SetCatcher( 0 );
 }
References Cbuf_AddText(), and Key_SetCatcher().
CL_StartHunkUsers()
void CL_StartHunkUsers (qboolean rendererOnly)
Definition at line 3015 of file cl_main.c.
{
     if (!com_cl_running) {
         return;
     }
     if ( !com_cl_running->integer ) {
         return;
     }
     if ( !cls.rendererStarted ) {
         cls.rendererStarted = qtrue;
         CL_InitRenderer();
     }
     if ( rendererOnly ) {
         return;
     }
     if ( !cls.soundStarted ) {
         cls.soundStarted = qtrue;
         S_Init();
     }
     if ( !cls.soundRegistered ) {
         cls.soundRegistered = qtrue;
         S_BeginRegistration();
     }
     if( com_dedicated->integer ) {
         return;
     }
     if ( !cls.uiStarted ) {
         cls.uiStarted = qtrue;
         CL_InitUI();
     }
 }
Referenced by CL_FlushMemory(), CL_Vid_Restart_f(), Com_GameRestart(), Com_Init(), and SV_SpawnServer().
CL_StopRecord_f()
void CL_StopRecord_f (void)
Definition at line 632 of file cl_main.c.
{
     int     len;
     if ( !clc.demorecording ) {
         Com_Printf ("Not recording a demo.\n");
         return;
     }
     // finish up
     len = -1;
     FS_Write (&len, 4, clc.demofile);
     FS_Write (&len, 4, clc.demofile);
     FS_FCloseFile (clc.demofile);
     clc.demofile = 0;
     clc.demorecording = qfalse;
     clc.spDemoRecording = qfalse;
     Com_Printf ("Stopped demo.\n");
 }
References clc, Com_Printf(), clientConnection_t::demofile, clientConnection_t::demorecording, FS_FCloseFile(), FS_Write(), qfalse, and clientConnection_t::spDemoRecording.
Referenced by CL_Disconnect(), CL_Frame(), CL_Init(), CL_ParseGamestate(), CL_ShutdownAll(), and CL_Vid_Restart_f().
CL_StopVideo_f()
void CL_StopVideo_f (void)
Definition at line 3263 of file cl_main.c.
 {
   CL_CloseAVI( );
 }
References CL_CloseAVI().
Referenced by CL_Init().
CL_UpdateGUID()
static void CL_UpdateGUID (const char * prefix, int prefix_len) static
Definition at line 1330 of file cl_main.c.
 {
     fileHandle_t f;
     int len;
     len = FS_SV_FOpenFileRead( QKEY_FILE, &f );
     FS_FCloseFile( f );
     if( len != QKEY_SIZE )
         Cvar_Set( "cl_guid", "" );
     else
         Cvar_Set( "cl_guid", Com_MD5File( QKEY_FILE, QKEY_SIZE,
             prefix, prefix_len ) );
 }
References Com_MD5File(), Cvar_Set(), FS_FCloseFile(), FS_SV_FOpenFileRead(), prefix, QKEY_FILE, and QKEY_SIZE.
Referenced by CL_Connect_f(), CL_Disconnect(), and CL_Init().
CL_UpdateVisiblePings_f()
qboolean CL_UpdateVisiblePings_f (int source)
Definition at line 4279 of file cl_main.c.
{
     int         slots, i;
     char        buff[MAX_STRING_CHARS];
     int         pingTime;
     int         max;
     qboolean status = qfalse;
     if (source < 0 || source > AS_FAVORITES) {
         return qfalse;
     }
     cls.pingUpdateSource = source;
     slots = CL_GetPingQueueCount();
     if (slots < MAX_PINGREQUESTS) {
         serverInfo_t *server = NULL;
         switch (source) {
             case AS_LOCAL :
                 server = &cls.localServers[0];
                 max = cls.numlocalservers;
             break;
             case AS_GLOBAL :
                 server = &cls.globalServers[0];
                 max = cls.numglobalservers;
             break;
             case AS_FAVORITES :
                 server = &cls.favoriteServers[0];
                 max = cls.numfavoriteservers;
             break;
             default:
                 return qfalse;
         }
         for (i = 0; i < max; i++) {
             if (server[i].visible) {
                 if (server[i].ping == -1) {
                     int j;
                     if (slots >= MAX_PINGREQUESTS) {
                         break;
                     }
                     for (j = 0; j < MAX_PINGREQUESTS; j++) {
                         if (!cl_pinglist[j].adr.port) {
                             continue;
                         }
                         if (NET_CompareAdr( cl_pinglist[j].adr, server[i].adr)) {
                             // already on the list
                             break;
                         }
                     }
                     if (j >= MAX_PINGREQUESTS) {
                         status = qtrue;
                         for (j = 0; j < MAX_PINGREQUESTS; j++) {
                             if (!cl_pinglist[j].adr.port) {
                                 break;
                             }
                         }
                         memcpy(&cl_pinglist[j].adr, &server[i].adr, sizeof(netadr_t));
                         cl_pinglist[j].start = Sys_Milliseconds();
                         cl_pinglist[j].time = 0;
                         NET_OutOfBandPrint( NS_CLIENT, cl_pinglist[j].adr, "getinfo xxx" );
                         slots++;
                     }
                 }
                 // if the server has a ping higher than cl_maxPing or
                 // the ping packet got lost
                 else if (server[i].ping == 0) {
                     // if we are updating global servers
                     if (source == AS_GLOBAL) {
                         //
                         if ( cls.numGlobalServerAddresses > 0 ) {
                             // overwrite this server with one from the additional global servers
                             cls.numGlobalServerAddresses--;
                             CL_InitServerInfo(&server[i], &cls.globalServerAddresses[cls.numGlobalServerAddresses]);
                             // NOTE: the server[i].visible flag stays untouched
                         }
                     }
                 }
             }
         }
     }
     if (slots) {
         status = qtrue;
     }
     for (i = 0; i < MAX_PINGREQUESTS; i++) {
         if (!cl_pinglist[i].adr.port) {
             continue;
         }
         CL_GetPing( i, buff, MAX_STRING_CHARS, &pingTime );
         if (pingTime != 0) {
             CL_ClearPing(i);
             status = qtrue;
         }
     }
     return status;
 }
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, CL_ClearPing(), CL_GetPing(), CL_GetPingQueueCount(), CL_InitServerInfo(), cl_pinglist, cls, clientStatic_t::favoriteServers, clientStatic_t::globalServerAddresses, clientStatic_t::globalServers, clientStatic_t::localServers, MAX_PINGREQUESTS, MAX_STRING_CHARS, NET_CompareAdr(), NET_OutOfBandPrint(), NS_CLIENT, NULL, clientStatic_t::numfavoriteservers, clientStatic_t::numGlobalServerAddresses, clientStatic_t::numglobalservers, clientStatic_t::numlocalservers, clientStatic_t::pingUpdateSource, qfalse, qtrue, ping_t::start, Sys_Milliseconds(), and ping_t::time.
Referenced by LAN_UpdateVisiblePings().
CL_Vid_Restart_f()
void CL_Vid_Restart_f (void)
Definition at line 1789 of file cl_main.c.
{
     // Settings may have changed so stop recording now
     if( CL_VideoRecording( ) ) {
         CL_CloseAVI( );
     }
     if(clc.demorecording)
         CL_StopRecord_f();
     // don't let them loop during the restart
     S_StopAllSounds();
     if(!FS_ConditionalRestart(clc.checksumFeed, qtrue))
     {
         // if not running a server clear the whole hunk
         if(com_sv_running->integer)
         {
             // clear all the client data on the hunk
             Hunk_ClearToMark();
         }
         else
         {
             // clear the whole hunk
             Hunk_Clear();
         }
         // shutdown the UI
         CL_ShutdownUI();
         // shutdown the CGame
         CL_ShutdownCGame();
         // shutdown the renderer and clear the renderer interface
         CL_ShutdownRef();
         // client is no longer pure untill new checksums are sent
         CL_ResetPureClientAtServer();
         // clear pak references
         FS_ClearPakReferences( FS_UI_REF | FS_CGAME_REF );
         // reinitialize the filesystem if the game directory or checksum has changed
         cls.rendererStarted = qfalse;
         cls.uiStarted = qfalse;
         cls.cgameStarted = qfalse;
         cls.soundRegistered = qfalse;
         // unpause so the cgame definately gets a snapshot and renders a frame
         Cvar_Set("cl_paused", "0");
         // initialize the renderer interface
         CL_InitRef();
         // startup all the client stuff
         CL_StartHunkUsers(qfalse);
         // start the cgame if connected
         if(clc.state > CA_CONNECTED && clc.state != CA_CINEMATIC)
         {
             cls.cgameStarted = qtrue;
             CL_InitCGame();
             // send pure checksums
             CL_SendPureChecksums();
         }
     }
 }
References CA_CINEMATIC, CA_CONNECTED, clientStatic_t::cgameStarted, clientConnection_t::checksumFeed, CL_CloseAVI(), CL_InitCGame(), CL_InitRef(), CL_ResetPureClientAtServer(), CL_SendPureChecksums(), CL_ShutdownCGame(), CL_ShutdownRef(), CL_ShutdownUI(), CL_StartHunkUsers(), CL_StopRecord_f(), CL_VideoRecording(), clc, cls, com_sv_running, Cvar_Set(), clientConnection_t::demorecording, FS_CGAME_REF, FS_ClearPakReferences(), FS_ConditionalRestart(), FS_UI_REF, Hunk_Clear(), Hunk_ClearToMark(), qfalse, qtrue, clientStatic_t::rendererStarted, S_StopAllSounds(), clientStatic_t::soundRegistered, clientConnection_t::state, and clientStatic_t::uiStarted.
Referenced by CL_Init(), and CL_Snd_Restart_f().
CL_Video_f()
void CL_Video_f (void)
Definition at line 3208 of file cl_main.c.
 {
   char  filename[ MAX_OSPATH ];
   int   i, last;
   if( !clc.demoplaying )
   {
     Com_Printf( "The video command can only be used when playing back demos\n" );
     return;
   }
   if( Cmd_Argc( ) == 2 )
   {
     // explicit filename
     Com_sprintf( filename, MAX_OSPATH, "videos/%s.avi", Cmd_Argv( 1 ) );
   }
   else
   {
     // scan for a free filename
     for( i = 0; i <= 9999; i++ )
     {
       int a, b, c, d;
       last = i;
       a = last / 1000;
       last -= a * 1000;
       b = last / 100;
       last -= b * 100;
       c = last / 10;
       last -= c * 10;
       d = last;
       Com_sprintf( filename, MAX_OSPATH, "videos/video%d%d%d%d.avi",
           a, b, c, d );
       if( !FS_FileExists( filename ) )
         break; // file doesn't exist
     }
     if( i > 9999 )
     {
       Com_Printf( S_COLOR_RED "ERROR: no free file names to create video\n" );
       return;
     }
   }
   CL_OpenAVIForWriting( filename );
 }
References CL_OpenAVIForWriting(), clc, Cmd_Argc(), Cmd_Argv(), Com_Printf(), Com_sprintf(), clientConnection_t::demoplaying, FS_FileExists(), MAX_OSPATH, and S_COLOR_RED.
Referenced by CL_Init().
CL_WalkDemoExt()
static int CL_WalkDemoExt (char * arg, char * name, int * demofile) static
Definition at line 976 of file cl_main.c.
 {
     int i = 0;
     *demofile = 0;
 #ifdef LEGACY_PROTOCOL
     if(com_legacyprotocol->integer > 0)
     {
         Com_sprintf(name, MAX_OSPATH, "demos/%s.%s%d", arg, DEMOEXT, com_legacyprotocol->integer);
         FS_FOpenFileRead(name, demofile, qtrue);
         if (*demofile)
         {
             Com_Printf("Demo file: %s\n", name);
             return com_legacyprotocol->integer;
         }
     }
     if(com_protocol->integer != com_legacyprotocol->integer)
 #endif
     {
         Com_sprintf(name, MAX_OSPATH, "demos/%s.%s%d", arg, DEMOEXT, com_protocol->integer);
         FS_FOpenFileRead(name, demofile, qtrue);
         if (*demofile)
         {
             Com_Printf("Demo file: %s\n", name);
             return com_protocol->integer;
         }
     }
     Com_Printf("Not found: %s\n", name);
     while(demo_protocols[i])
     {
 #ifdef LEGACY_PROTOCOL
         if(demo_protocols[i] == com_legacyprotocol->integer)
             continue;
 #endif
         if(demo_protocols[i] == com_protocol->integer)
             continue;
         Com_sprintf (name, MAX_OSPATH, "demos/%s.%s%d", arg, DEMOEXT, demo_protocols[i]);
         FS_FOpenFileRead( name, demofile, qtrue );
         if (*demofile)
         {
             Com_Printf("Demo file: %s\n", name);
             return demo_protocols[i];
         }
         else
             Com_Printf("Not found: %s\n", name);
         i++;
     }
     return -1;
 }
References Com_Printf(), com_protocol, Com_sprintf(), demo_protocols, DEMOEXT, FS_FOpenFileRead(), MAX_OSPATH, and qtrue.
Referenced by CL_PlayDemo_f().
CL_WriteDemoMessage()
void CL_WriteDemoMessage (msg_t * msg, int headerBytes)
Definition at line 610 of file cl_main.c.
{
     int     len, swlen;
     // write the packet sequence
     len = clc.serverMessageSequence;
     swlen = LittleLong( len );
     FS_Write (&swlen, 4, clc.demofile);
     // skip the packet sequencing information
     len = msg->cursize - headerBytes;
     swlen = LittleLong(len);
     FS_Write (&swlen, 4, clc.demofile);
     FS_Write ( msg->data + headerBytes, len, clc.demofile );
 }
References clc, msg_t::cursize, msg_t::data, clientConnection_t::demofile, FS_Write(), and clientConnection_t::serverMessageSequence.
Referenced by CL_PacketEvent(), and CL_WritePacket().
Variable Documentation
cgvm
vm_t* cgvm
Definition at line 126 of file cl_main.c.
Referenced by CL_CGameRendering(), CL_GameCommand(), CL_InitCGame(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MouseEvent(), CL_ShutdownCGame(), Con_MessageMode3_f(), and Con_MessageMode4_f().
cl
clientActive_t cl
Definition at line 123 of file cl_main.c.
Referenced by attach(), CalculateRanks(), CG_EntityEffects(), CL_AdjustAngles(), CL_AdjustTimeDelta(), CL_CGameRendering(), CL_CheckTimeout(), CL_ClearState(), CL_ConfigstringModified(), CL_Configstrings_f(), CL_CreateCmd(), CL_CreateNewCommands(), CL_DeltaEntity(), CL_FinishMove(), CL_FirstSnapshot(), CL_Frame(), CL_GetCurrentCmdNumber(), CL_GetCurrentSnapshotNumber(), CL_GetGameState(), CL_GetParseEntityState(), CL_GetServerCommand(), CL_GetSnapshot(), CL_GetUserCmd(), CL_InitCGame(), CL_JoystickEvent(), CL_JoystickMove(), CL_MapLoading(), CL_MouseEvent(), CL_MouseMove(), CL_ParseGamestate(), CL_ParsePacketEntities(), CL_ParseServerInfo(), CL_ParseSnapshot(), CL_ReadyToSendPacket(), CL_Record_f(), CL_SendPureChecksums(), CL_SetCGameTime(), CL_SetUserCmdValue(), CL_SystemInfoChanged(), CL_WritePacket(), ClientForString(), ClientNumberFromString(), Com_Frame(), Con_DrawNotify(), cput(), ExitLevel(), foreach(), GetClientState(), GetConfigString(), IN_CenterView(), LogExit(), oldparam(), Pickup_Team(), scon(), SpectatorClientEndFrame(), SV_AddBanToList(), SV_BeginDownload_f(), SV_CalcPings(), SV_CheckPaused(), SV_CheckTimeouts(), SV_ClientCommand(), SV_ClientThink(), SV_CloseDownload(), SV_DirectConnect(), SV_Disconnect_f(), SV_DoneDownload_f(), SV_DumpUser_f(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_FinalMessage(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Kick_f(), SV_KickNum_f(), SV_NextDownload_f(), SV_PacketEvent(), SV_ResetPureClient_f(), SV_SendDownloadMessages(), SV_SendQueuedMessages(), SV_SendServerCommand(), SV_Status_f(), SV_StopDownload_f(), SV_UpdateUserinfo_f(), SV_UserinfoChanged(), SV_UserMove(), SV_VerifyPaks_f(), SV_WriteDownloadToClient(), SVC_Status(), Svcmd_ForceTeam_f(), typestab(), and wcput().
cl_activeAction
cvar_t* cl_activeAction
Definition at line 106 of file cl_main.c.
Referenced by CL_FirstSnapshot(), and CL_Init().
cl_allowDownload
cvar_t* cl_allowDownload
Definition at line 110 of file cl_main.c.
Referenced by CL_Init(), CL_InitDownloads(), and CL_NextDownload().
cl_autoRecordDemo
cvar_t* cl_autoRecordDemo
Definition at line 76 of file cl_main.c.
Referenced by CL_Frame(), CL_Init(), and CL_ParseGamestate().
cl_aviFrameRate
cvar_t* cl_aviFrameRate
Definition at line 77 of file cl_main.c.
Referenced by CL_Frame(), CL_Init(), CL_OpenAVIForWriting(), and S_GetSoundtime().
cl_aviMotionJpeg
cvar_t* cl_aviMotionJpeg
Definition at line 78 of file cl_main.c.
Referenced by CL_Init(), and CL_OpenAVIForWriting().
cl_consoleKeys
cvar_t* cl_consoleKeys
Definition at line 121 of file cl_main.c.
Referenced by CL_Init(), and IN_IsConsoleKey().
cl_conXOffset
cvar_t* cl_conXOffset
Definition at line 111 of file cl_main.c.
Referenced by CL_Init().
cl_debugMove
cvar_t* cl_debugMove
Definition at line 55 of file cl_main.c.
Referenced by CL_CreateCmd(), CL_InitInput(), and SCR_DrawScreenField().
cl_forceavidemo
cvar_t* cl_forceavidemo
Definition at line 79 of file cl_main.c.
Referenced by CL_Frame(), and CL_Init().
cl_freelook
cvar_t* cl_freelook
Definition at line 81 of file cl_main.c.
Referenced by CL_Init(), CL_MouseMove(), and IN_MLookUp().
cl_freezeDemo
cvar_t* cl_freezeDemo
Definition at line 70 of file cl_main.c.
Referenced by CL_Init(), and CL_SetCGameTime().
cl_guidServerUniq
cvar_t* cl_guidServerUniq
Definition at line 119 of file cl_main.c.
Referenced by CL_Connect_f(), and CL_Init().
cl_inGameVideo
cvar_t* cl_inGameVideo
Definition at line 112 of file cl_main.c.
Referenced by CIN_PlayCinematic(), CIN_UploadCinematic(), and CL_Init().
cl_lanForcePackets
cvar_t* cl_lanForcePackets
Definition at line 117 of file cl_main.c.
Referenced by CL_Init(), and CL_ReadyToSendPacket().
cl_maxpackets
cvar_t* cl_maxpackets
Definition at line 66 of file cl_main.c.
Referenced by CL_Init(), and CL_ReadyToSendPacket().
cl_motdString
cvar_t* cl_motdString
Definition at line 108 of file cl_main.c.
Referenced by CL_Init().
cl_mouseAccel
cvar_t* cl_mouseAccel
Definition at line 84 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_mouseAccelOffset
cvar_t* cl_mouseAccelOffset
Definition at line 85 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_mouseAccelStyle
cvar_t* cl_mouseAccelStyle
Definition at line 86 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_nodelta
cvar_t* cl_nodelta
Definition at line 54 of file cl_main.c.
Referenced by CL_InitInput(), and CL_WritePacket().
cl_noprint
cvar_t* cl_noprint
Definition at line 57 of file cl_main.c.
Referenced by CL_ConsolePrint(), and CL_Init().
cl_packetdup
cvar_t* cl_packetdup
Definition at line 67 of file cl_main.c.
Referenced by CL_Init(), and CL_WritePacket().
cl_pinglist
ping_t cl_pinglist[MAX_PINGREQUESTS]
Definition at line 134 of file cl_main.c.
Referenced by CL_ClearPing(), CL_GetFreePing(), CL_GetPing(), CL_GetPingInfo(), CL_GetPingQueueCount(), CL_ServerInfoPacket(), and CL_UpdateVisiblePings_f().
cl_sensitivity
cvar_t* cl_sensitivity
Definition at line 82 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_serverStatusList
serverStatus_t cl_serverStatusList[MAX_SERVERSTATUSREQUESTS]
Definition at line 146 of file cl_main.c.
Referenced by CL_GetServerStatus(), CL_ServerStatus(), and CL_ServerStatusResponse().
cl_serverStatusResendTime
cvar_t* cl_serverStatusResendTime
Definition at line 114 of file cl_main.c.
Referenced by CL_Init(), and CL_ServerStatus().
cl_showMouseRate
cvar_t* cl_showMouseRate
Definition at line 87 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_shownet
cvar_t* cl_shownet
Definition at line 72 of file cl_main.c.
Referenced by CL_Init(), CL_ParsePacketEntities(), CL_ParseServerMessage(), CL_ParseSnapshot(), and SHOWNET().
cl_showSend
cvar_t* cl_showSend
Definition at line 73 of file cl_main.c.
Referenced by CL_Init(), CL_SendCmd(), and CL_WritePacket().
cl_showTimeDelta
cvar_t* cl_showTimeDelta
Definition at line 69 of file cl_main.c.
Referenced by CL_AdjustTimeDelta(), and CL_Init().
cl_timedemo
cvar_t* cl_timedemo
Definition at line 74 of file cl_main.c.
Referenced by CL_DemoCompleted(), CL_Init(), and CL_SetCGameTime().
cl_timedemoLog
cvar_t* cl_timedemoLog
Definition at line 75 of file cl_main.c.
Referenced by CL_DemoCompleted(), and CL_Init().
cl_timeNudge
cvar_t* cl_timeNudge
Definition at line 68 of file cl_main.c.
Referenced by CL_Init(), and CL_SetCGameTime().
cl_timeout
cvar_t* cl_timeout
Definition at line 65 of file cl_main.c.
Referenced by CL_CheckTimeout(), and CL_Init().
cl_trn
cvar_t* cl_trn
Definition at line 115 of file cl_main.c.
clc
clientConnection_t clc
Definition at line 124 of file cl_main.c.
Referenced by CIN_PlayCinematic(), CIN_RunCinematic(), CIN_StopCinematic(), CL_AddReliableCommand(), CL_AdjustTimeDelta(), CL_BeginDownload(), CL_CGameRendering(), CL_ChangeReliableCommand(), CL_CharEvent(), CL_CheckForResend(), CL_CheckTimeout(), CL_CheckUserinfo(), CL_Clientinfo_f(), CL_Configstrings_f(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_CreateNewCommands(), CL_DemoCompleted(), CL_DemoFrameDurationSDev(), CL_Disconnect(), CL_Disconnect_f(), CL_DisconnectPacket(), CL_DownloadsComplete(), CL_FirstSnapshot(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_Frame(), CL_GetServerCommand(), CL_Init(), CL_InitCGame(), CL_InitDownloads(), CL_InitUI(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MapLoading(), CL_NextDownload(), CL_OldGame(), CL_PacketEvent(), CL_ParseCommandString(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParseServerInfo(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_PlayCinematic_f(), CL_PlayDemo_f(), CL_Rcon_f(), CL_ReadDemoMessage(), CL_ReadyToSendPacket(), CL_Reconnect_f(), CL_Record_f(), CL_SendCmd(), CL_ServerStatus_f(), CL_SetCGameTime(), CL_ShutdownAll(), CL_StopRecord_f(), CL_SystemInfoChanged(), CL_Vid_Restart_f(), CL_Video_f(), CL_WriteDemoMessage(), CL_WritePacket(), Con_DrawConsole(), Con_DrawInput(), CON_Input(), Con_ToggleConsole_f(), Console_Key(), GetClientState(), IN_Frame(), Message_Key(), RoQShutdown(), SCR_DrawDemoRecording(), and SCR_DrawScreenField().
cls
clientStatic_t cls
Definition at line 125 of file cl_main.c.
Referenced by CL_AdjustAngles(), CL_AdjustTimeDelta(), CL_BeginDownload(), CL_CheckForResend(), CL_CheckTimeout(), CL_ConsolePrint(), CL_DisconnectPacket(), CL_DownloadsComplete(), CL_FirstSnapshot(), CL_Frame(), CL_GetGlconfig(), CL_GlobalServers_f(), CL_Init(), CL_InitRenderer(), CL_InitUI(), CL_JoystickMove(), CL_LocalServers_f(), CL_MapLoading(), CL_MotdPacket(), CL_OldGame(), CL_OpenAVIForWriting(), CL_PacketEvent(), CL_ParseGamestate(), CL_ParseSnapshot(), CL_ReadDemoMessage(), CL_ReadyToSendPacket(), CL_RequestMotd(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_SetCGameTime(), CL_SetServerInfoByAddress(), CL_Shutdown(), CL_ShutdownAll(), CL_ShutdownCGame(), CL_ShutdownUI(), CL_Snd_Shutdown(), CL_StartHunkUsers(), CL_UpdateVisiblePings_f(), CL_Vid_Restart_f(), CL_WritePacket(), Con_DrawNotify(), Con_DrawSolidConsole(), Con_Linefeed(), Con_RunConsole(), Field_CustomDraw(), Field_VariableSizeDraw(), GetClientState(), IN_DeactivateMouse(), LAN_AddServer(), LAN_GetServerAddressString(), LAN_GetServerCount(), LAN_GetServerInfo(), LAN_GetServerPing(), LAN_GetServerPtr(), LAN_LoadCachedServers(), LAN_MarkServerVisible(), LAN_RemoveServer(), LAN_ResetPings(), LAN_SaveServersToCache(), LAN_ServerIsVisible(), readQuadInfo(), S_Base_AddLoopingSound(), SCR_AdjustFrom640(), SCR_DrawChar(), SCR_DrawDebugGraph(), SCR_DrawScreenField(), SCR_DrawSmallChar(), SCR_FillRect(), SCR_UpdateScreen(), specifier(), and UI_GameCommand().
demoName
char demoName[MAX_QPATH] static
Definition at line 683 of file cl_main.c.
Referenced by CL_Record_f().
j_forward
cvar_t* j_forward
Definition at line 97 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_forward_axis
cvar_t* j_forward_axis
Definition at line 102 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_pitch
cvar_t* j_pitch
Definition at line 95 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_pitch_axis
cvar_t* j_pitch_axis
Definition at line 100 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_side
cvar_t* j_side
Definition at line 98 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_side_axis
cvar_t* j_side_axis
Definition at line 103 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_up
cvar_t* j_up
Definition at line 99 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_up_axis
cvar_t* j_up_axis
Definition at line 104 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_yaw
cvar_t* j_yaw
Definition at line 96 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_yaw_axis
cvar_t* j_yaw_axis
Definition at line 101 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
m_filter
cvar_t* m_filter
Definition at line 93 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
m_forward
cvar_t* m_forward
Definition at line 91 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
m_pitch
cvar_t* m_pitch
Definition at line 89 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
m_side
cvar_t* m_side
Definition at line 92 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
m_yaw
cvar_t* m_yaw
Definition at line 90 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
noGameRestart
int noGameRestart = qfalse static
Definition at line 153 of file cl_main.c.
Referenced by CL_Connect_f(), CL_Disconnect(), and CL_Shutdown().
rcon_client_password
cvar_t* rcon_client_password
Definition at line 62 of file cl_main.c.
Referenced by CL_Init(), and CL_Rcon_f().
rconAddress
cvar_t* rconAddress
Definition at line 63 of file cl_main.c.
Referenced by CL_Init(), and CL_Rcon_f().
re
refexport_t re
Definition at line 129 of file cl_main.c.
Referenced by CG_AddFadeAlpha(), CG_AddFadeNo(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddMoveScaleFade(), CG_AddScaleFade(), CG_AddScaleFadeRGB(), CG_AddScorePlum(), CG_AddSpriteExplosion(), CG_AuraSpike(), CG_BigLightningEffect(), CG_BubbleTrail(), CG_DirtPush(), CG_LaunchExplode(), CG_LightningEffect(), CG_PowerMeleeEffect(), CG_PowerStruggleEffect(), CG_ScorePlum(), CG_SmokePuff(), CG_SpawnEffect(), CG_SpeedMeleeEffect(), CG_TrailFunc_SpiralBeam(), CG_WaterBubble(), CG_WaterRipple(), CG_WaterSplash(), CIN_DrawCinematic(), CIN_UploadCinematic(), CL_CgameSystemCalls(), CL_InitCGame(), CL_InitRef(), CL_InitRenderer(), CL_ShutdownAll(), CL_ShutdownRef(), CL_TakeVideoFrame(), CL_UISystemCalls(), Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), GetRefAPI(), SCR_DrawChar(), SCR_DrawCustomString(), SCR_DrawDebugGraph(), SCR_DrawNamedPic(), SCR_DrawPic(), SCR_DrawScreenField(), SCR_DrawSmallChar(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), SCR_FillRect(), SCR_UpdateScreen(), and trap_R_AddRefEntityToScene().
serverStatusCount
int serverStatusCount
Definition at line 147 of file cl_main.c.
Referenced by CL_GetServerStatus().