ZEQ2-Lite: Source/Engine/jpeg-8c/jutils.c File Reference
jutils.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define FMEMCOPY(dest, src, size) MEMCOPY(dest,src,size)
#define FMEMZERO(target, size) MEMZERO(target,size)
#define JPEG_INTERNALS
Functions
jcopy_block_row (JBLOCKROW input_row, JBLOCKROW output_row, JDIMENSION num_blocks)
jcopy_sample_rows (JSAMPARRAY input_array, int source_row, JSAMPARRAY output_array, int dest_row, int num_rows, JDIMENSION num_cols)
jdiv_round_up (long a, long b)
jround_up (long a, long b)
jzero_far (void FAR *target, size_t bytestozero)
Variables
const int jpeg_natural_order [DCTSIZE2+16]
const int jpeg_natural_order2 [2 *2+16]
const int jpeg_natural_order3 [3 *3+16]
const int jpeg_natural_order4 [4 *4+16]
const int jpeg_natural_order5 [5 *5+16]
const int jpeg_natural_order6 [6 *6+16]
const int jpeg_natural_order7 [7 *7+16]
Macro Definition Documentation
FMEMCOPY
#define FMEMCOPY (dest, src, size) MEMCOPY(dest,src,size)
Definition at line 152 of file jutils.c.
FMEMZERO
#define FMEMZERO (target, size) MEMZERO(target,size)
Definition at line 153 of file jutils.c.
JPEG_INTERNALS
#define JPEG_INTERNALS
Definition at line 15 of file jutils.c.
Function Documentation
jcopy_block_row()
jcopy_block_row (JBLOCKROW input_row, JBLOCKROW output_row, JDIMENSION num_blocks)
Definition at line 197 of file jutils.c.
 {
 #ifdef FMEMCOPY
   FMEMCOPY(output_row, input_row, num_blocks * (DCTSIZE2 * SIZEOF(JCOEF)));
 #else
   register JCOEFPTR inptr, outptr;
   register long count;
   inptr = (JCOEFPTR) input_row;
   outptr = (JCOEFPTR) output_row;
   for (count = (long) num_blocks * DCTSIZE2; count > 0; count--) {
     *outptr++ = *inptr++;
   }
 #endif
 }
References DCTSIZE2, FMEMCOPY, num_blocks, output_row, and SIZEOF.
Referenced by decompress_smooth_data().
jcopy_sample_rows()
jcopy_sample_rows (JSAMPARRAY input_array, int source_row, JSAMPARRAY output_array, int dest_row, int num_rows, JDIMENSION num_cols)
Definition at line 163 of file jutils.c.
 {
   register JSAMPROW inptr, outptr;
 #ifdef FMEMCOPY
   register size_t count = (size_t) (num_cols * SIZEOF(JSAMPLE));
 #else
   register JDIMENSION count;
 #endif
   register int row;
   input_array += source_row;
   output_array += dest_row;
   for (row = num_rows; row > 0; row--) {
     inptr = *input_array++;
     outptr = *output_array++;
 #ifdef FMEMCOPY
     FMEMCOPY(outptr, inptr, count);
 #else
     for (count = num_cols; count > 0; count--)
       *outptr++ = *inptr++; /* needn't bother with GETJSAMPLE() here */
 #endif
   }
 }
References dest_row, FMEMCOPY, num_cols, num_rows, output_array, SIZEOF, and source_row.
Referenced by expand_bottom_edge(), fullsize_downsample(), grayscale_convert(), h2v2_upsample(), int_upsample(), merged_2v_upsample(), and pre_process_context().
jdiv_round_up()
jdiv_round_up (long a, long b)
Definition at line 124 of file jutils.c.
 {
   return (a + b - 1L) / b;
 }
Referenced by initial_setup(), jpeg_calc_jpeg_dimensions(), jpeg_calc_output_dimensions(), and per_scan_setup().
jround_up()
jround_up (long a, long b)
Definition at line 133 of file jutils.c.
 {
   a += b - 1L;
   return a - (a % b);
 }
Referenced by jinit_c_coef_controller(), jinit_c_main_controller(), jinit_d_coef_controller(), jinit_d_post_controller(), and jinit_upsampler().
jzero_far()
jzero_far (void FAR * target, size_t bytestozero)
Definition at line 217 of file jutils.c.
 {
 #ifdef FMEMZERO
   FMEMZERO(target, bytestozero);
 #else
   register char FAR * ptr = (char FAR *) target;
   register size_t count;
   for (count = bytestozero; count > 0; count--) {
     *ptr++ = 0;
   }
 #endif
 }
References bytestozero, FAR, FMEMZERO, and ptr().
Referenced by access_virt_barray(), access_virt_sarray(), compress_data(), compress_first_pass(), decompress_onepass(), quantize_fs_dither(), quantize_ord_dither(), start_pass_1_quant(), start_pass_2_quant(), and transencode_coef_controller().
Variable Documentation
jpeg_natural_order
const int jpeg_natural_order[DCTSIZE2+16]
Initial value:
= {
  0,  1,  8, 16,  9,  2,  3, 10,
 17, 24, 32, 25, 18, 11,  4,  5,
 12, 19, 26, 33, 40, 48, 41, 34,
 27, 20, 13,  6,  7, 14, 21, 28,
 35, 42, 49, 56, 57, 50, 43, 36,
 29, 22, 15, 23, 30, 37, 44, 51,
 58, 59, 52, 45, 38, 31, 39, 46,
 53, 60, 61, 54, 47, 55, 62, 63,
 63, 63, 63, 63, 63, 63, 63, 63,
 63, 63, 63, 63, 63, 63, 63, 63
}
Definition at line 54 of file jutils.c.
Referenced by decode_mcu(), get_dqt(), initial_setup(), and jpeg_CreateCompress().
jpeg_natural_order2
const int jpeg_natural_order2[2 *2+16]
Initial value:
= {
  0,  1,  8,  9,
 63, 63, 63, 63, 63, 63, 63, 63,
 63, 63, 63, 63, 63, 63, 63, 63
}
Definition at line 112 of file jutils.c.
Referenced by get_dqt(), and initial_setup().
jpeg_natural_order3
const int jpeg_natural_order3[3 *3+16]
Initial value:
= {
  0,  1,  8, 16,  9,  2, 10, 17,
 18,
 63, 63, 63, 63, 63, 63, 63, 63,
 63, 63, 63, 63, 63, 63, 63, 63
}
Definition at line 105 of file jutils.c.
Referenced by get_dqt(), and initial_setup().
jpeg_natural_order4
const int jpeg_natural_order4[4 *4+16]
Initial value:
= {
  0,  1,  8, 16,  9,  2,  3, 10,
 17, 24, 25, 18, 11, 19, 26, 27,
 63, 63, 63, 63, 63, 63, 63, 63,
 63, 63, 63, 63, 63, 63, 63, 63
}
Definition at line 98 of file jutils.c.
Referenced by get_dqt(), and initial_setup().
jpeg_natural_order5
const int jpeg_natural_order5[5 *5+16]
Initial value:
= {
  0,  1,  8, 16,  9,  2,  3, 10,
 17, 24, 32, 25, 18, 11,  4, 12,
 19, 26, 33, 34, 27, 20, 28, 35,
 36,
 63, 63, 63, 63, 63, 63, 63, 63,
 63, 63, 63, 63, 63, 63, 63, 63
}
Definition at line 89 of file jutils.c.
Referenced by get_dqt(), and initial_setup().
jpeg_natural_order6
const int jpeg_natural_order6[6 *6+16]
Initial value:
= {
  0,  1,  8, 16,  9,  2,  3, 10,
 17, 24, 32, 25, 18, 11,  4,  5,
 12, 19, 26, 33, 40, 41, 34, 27,
 20, 13, 21, 28, 35, 42, 43, 36,
 29, 37, 44, 45,
 63, 63, 63, 63, 63, 63, 63, 63,
 63, 63, 63, 63, 63, 63, 63, 63
}
Definition at line 79 of file jutils.c.
Referenced by get_dqt(), and initial_setup().
jpeg_natural_order7
const int jpeg_natural_order7[7 *7+16]
Initial value:
= {
  0,  1,  8, 16,  9,  2,  3, 10,
 17, 24, 32, 25, 18, 11,  4,  5,
 12, 19, 26, 33, 40, 48, 41, 34,
 27, 20, 13,  6, 14, 21, 28, 35,
 42, 49, 50, 43, 36, 29, 22, 30,
 37, 44, 51, 52, 45, 38, 46, 53,
 54,
 63, 63, 63, 63, 63, 63, 63, 63,
 63, 63, 63, 63, 63, 63, 63, 63
}
Definition at line 67 of file jutils.c.
Referenced by get_dqt(), and initial_setup().