ZEQ2-Lite: Source/Game/UI/ui_servers2.c File Reference
ui_servers2.c File Reference
#include "ui_local.h"
Data Structures
struct arenaservers_t
struct pinglist_t
struct servernode_s
struct table_t
Macros
#define ART_ARROWS0 "interface/art/arrows_vert_0"
#define ART_ARROWS_DOWN "interface/art/arrows_vert_bot"
#define ART_ARROWS_UP "interface/art/arrows_vert_top"
#define ART_OPBACKGROUND "interface/art/optionBackground"
#define ART_REMOVE0 "interface/art/delete_0"
#define ART_REMOVE1 "interface/art/delete_1"
#define ART_SERVERENTRY "interface/art/serverBackground"
#define ART_SERVERENTRYSELECTED "interface/art/serverBackgroundSelected"
#define GAMES_ALL 0
#define GAMES_STRUGGLE 1
#define GR_LETTERS 31
#define GR_LOGO 30
#define ID_BACK 18
#define ID_CONNECT 19
#define ID_CREATE 20
#define ID_GAMETYPE 11
#define ID_LATENCY 26
#define ID_LIST 15
#define ID_MAPNAME 24
#define ID_MASTER 10
#define ID_NAME 23
#define ID_PLAYERS 25
#define ID_REFRESH 21
#define ID_REMOVE 22
#define ID_SCROLL_DOWN 17
#define ID_SCROLL_UP 16
#define ID_SHOW_EMPTY 14
#define ID_SHOW_FULL 13
#define ID_SORTKEY 12
#define MAX_ADDRESSLENGTH 64
#define MAX_GLOBALSERVERS 128
#define MAX_HOSTNAMELENGTH 41
#define MAX_LEAGUELENGTH 28
#define MAX_LISTBOXITEMS 128
#define MAX_LISTBOXWIDTH 86
#define MAX_LOCALSERVERS 128
#define MAX_MAPNAMELENGTH 16
#define MAX_PINGREQUESTS 32
#define MAX_STATUSLENGTH 86
#define SORT_CLIENTS 2
#define SORT_GAME 3
#define SORT_HOST 0
#define SORT_MAP 1
#define SORT_PING 4
#define UIAS_FAVORITES 6
#define UIAS_GLOBAL1 1
#define UIAS_GLOBAL2 2
#define UIAS_GLOBAL3 3
#define UIAS_GLOBAL4 4
#define UIAS_GLOBAL5 5
#define UIAS_LOCAL 0
Functions
void ArenaServers_Cache (void)
static int QDECL ArenaServers_Compare (const void *arg1, const void *arg2)
static void ArenaServers_DoRefresh (void)
static void ArenaServers_Event (void *ptr, int event)
static void ArenaServers_Go (void)
static void ArenaServers_Insert (char *adrstr, char *info, int pingtime)
void ArenaServers_InsertFavorites (void)
void ArenaServers_LoadFavorites (void)
static int ArenaServers_MaxPing (void)
static void ArenaServers_MenuDraw (void)
static void ArenaServers_MenuInit (void)
static sfxHandle_t ArenaServers_MenuKey (int key)
static void ArenaServers_Remove (void)
void ArenaServers_SaveChanges (void)
int ArenaServers_SetType (int type)
void ArenaServers_Sort (int type)
int ArenaServers_SourceForLAN (void)
static void ArenaServers_StartRefresh (void)
static void ArenaServers_StopRefresh (void)
static void ArenaServers_UpdateMenu (void)
void strrep (char *str, char old, char new)
void UI_ArenaServersMenu (void)
Variables
static arenaservers_t g_arenaservers
static int g_emptyservers
static servernode_t g_favoriteserverlist [MAX_FAVORITESERVERS]
static int g_fullservers
static int g_gametype
static servernode_t g_globalserverlist [MAX_GLOBALSERVERS]
static servernode_t g_localserverlist [MAX_LOCALSERVERS]
static int g_numfavoriteservers
static int g_numglobalservers
static int g_numlocalservers
static int g_servertype
static int g_sortkey
static char * gamenames []
static const char * master_items []
static char * netnames []
static char quake3worldMessage [] = ""
qboolean readPort
static const char * servertype_items []
static const char * sortkey_items []
qboolean updateAddress
Macro Definition Documentation
ART_ARROWS0
#define ART_ARROWS0 "interface/art/arrows_vert_0"
Definition at line 46 of file ui_servers2.c.
ART_ARROWS_DOWN
#define ART_ARROWS_DOWN "interface/art/arrows_vert_bot"
Definition at line 48 of file ui_servers2.c.
ART_ARROWS_UP
#define ART_ARROWS_UP "interface/art/arrows_vert_top"
Definition at line 47 of file ui_servers2.c.
ART_OPBACKGROUND
#define ART_OPBACKGROUND "interface/art/optionBackground"
Definition at line 51 of file ui_servers2.c.
ART_REMOVE0
#define ART_REMOVE0 "interface/art/delete_0"
Definition at line 49 of file ui_servers2.c.
ART_REMOVE1
#define ART_REMOVE1 "interface/art/delete_1"
Definition at line 50 of file ui_servers2.c.
ART_SERVERENTRY
#define ART_SERVERENTRY "interface/art/serverBackground"
Definition at line 52 of file ui_servers2.c.
ART_SERVERENTRYSELECTED
#define ART_SERVERENTRYSELECTED "interface/art/serverBackgroundSelected"
Definition at line 53 of file ui_servers2.c.
GAMES_ALL
#define GAMES_ALL 0
Definition at line 90 of file ui_servers2.c.
GAMES_STRUGGLE
#define GAMES_STRUGGLE 1
Definition at line 91 of file ui_servers2.c.
GR_LETTERS
#define GR_LETTERS 31
Definition at line 74 of file ui_servers2.c.
GR_LOGO
#define GR_LOGO 30
Definition at line 73 of file ui_servers2.c.
ID_BACK
#define ID_BACK 18
Definition at line 63 of file ui_servers2.c.
ID_CONNECT
#define ID_CONNECT 19
Definition at line 64 of file ui_servers2.c.
ID_CREATE
#define ID_CREATE 20
Definition at line 65 of file ui_servers2.c.
ID_GAMETYPE
#define ID_GAMETYPE 11
Definition at line 56 of file ui_servers2.c.
ID_LATENCY
#define ID_LATENCY 26
Definition at line 71 of file ui_servers2.c.
ID_LIST
#define ID_LIST 15
Definition at line 60 of file ui_servers2.c.
ID_MAPNAME
#define ID_MAPNAME 24
Definition at line 69 of file ui_servers2.c.
ID_MASTER
#define ID_MASTER 10
Definition at line 55 of file ui_servers2.c.
ID_NAME
#define ID_NAME 23
Definition at line 68 of file ui_servers2.c.
ID_PLAYERS
#define ID_PLAYERS 25
Definition at line 70 of file ui_servers2.c.
ID_REFRESH
#define ID_REFRESH 21
Definition at line 66 of file ui_servers2.c.
ID_REMOVE
#define ID_REMOVE 22
Definition at line 67 of file ui_servers2.c.
ID_SCROLL_DOWN
#define ID_SCROLL_DOWN 17
Definition at line 62 of file ui_servers2.c.
ID_SCROLL_UP
#define ID_SCROLL_UP 16
Definition at line 61 of file ui_servers2.c.
ID_SHOW_EMPTY
#define ID_SHOW_EMPTY 14
Definition at line 59 of file ui_servers2.c.
ID_SHOW_FULL
#define ID_SHOW_FULL 13
Definition at line 58 of file ui_servers2.c.
ID_SORTKEY
#define ID_SORTKEY 12
Definition at line 57 of file ui_servers2.c.
MAX_ADDRESSLENGTH
#define MAX_ADDRESSLENGTH 64
Definition at line 37 of file ui_servers2.c.
MAX_GLOBALSERVERS
#define MAX_GLOBALSERVERS 128
Definition at line 35 of file ui_servers2.c.
MAX_HOSTNAMELENGTH
#define MAX_HOSTNAMELENGTH 41
Definition at line 38 of file ui_servers2.c.
MAX_LEAGUELENGTH
#define MAX_LEAGUELENGTH 28
Definition at line 43 of file ui_servers2.c.
MAX_LISTBOXITEMS
#define MAX_LISTBOXITEMS 128
Definition at line 40 of file ui_servers2.c.
MAX_LISTBOXWIDTH
#define MAX_LISTBOXWIDTH 86
Definition at line 44 of file ui_servers2.c.
MAX_LOCALSERVERS
#define MAX_LOCALSERVERS 128
Definition at line 41 of file ui_servers2.c.
MAX_MAPNAMELENGTH
#define MAX_MAPNAMELENGTH 16
Definition at line 39 of file ui_servers2.c.
MAX_PINGREQUESTS
#define MAX_PINGREQUESTS 32
Definition at line 36 of file ui_servers2.c.
MAX_STATUSLENGTH
#define MAX_STATUSLENGTH 86
Definition at line 42 of file ui_servers2.c.
SORT_CLIENTS
#define SORT_CLIENTS 2
Definition at line 86 of file ui_servers2.c.
SORT_GAME
#define SORT_GAME 3
Definition at line 87 of file ui_servers2.c.
SORT_HOST
#define SORT_HOST 0
Definition at line 84 of file ui_servers2.c.
SORT_MAP
#define SORT_MAP 1
Definition at line 85 of file ui_servers2.c.
SORT_PING
#define SORT_PING 4
Definition at line 88 of file ui_servers2.c.
UIAS_FAVORITES
#define UIAS_FAVORITES 6
Definition at line 82 of file ui_servers2.c.
UIAS_GLOBAL1
#define UIAS_GLOBAL1 1
Definition at line 77 of file ui_servers2.c.
UIAS_GLOBAL2
#define UIAS_GLOBAL2 2
Definition at line 78 of file ui_servers2.c.
UIAS_GLOBAL3
#define UIAS_GLOBAL3 3
Definition at line 79 of file ui_servers2.c.
UIAS_GLOBAL4
#define UIAS_GLOBAL4 4
Definition at line 80 of file ui_servers2.c.
UIAS_GLOBAL5
#define UIAS_GLOBAL5 5
Definition at line 81 of file ui_servers2.c.
UIAS_LOCAL
#define UIAS_LOCAL 0
Definition at line 76 of file ui_servers2.c.
Function Documentation
ArenaServers_Cache()
void ArenaServers_Cache (void)
Definition at line 1503 of file ui_servers2.c.
{
     trap_R_RegisterShaderNoMip( ART_REMOVE0 );
     trap_R_RegisterShaderNoMip( ART_REMOVE1 );
     trap_R_RegisterShaderNoMip( ART_ARROWS0  );
     trap_R_RegisterShaderNoMip( ART_ARROWS_UP );
     trap_R_RegisterShaderNoMip( ART_ARROWS_DOWN );
 }
References ART_ARROWS0, ART_ARROWS_DOWN, ART_ARROWS_UP, ART_REMOVE0, ART_REMOVE1, and trap_R_RegisterShaderNoMip().
Referenced by ArenaServers_MenuInit().
ArenaServers_Compare()
static int QDECL ArenaServers_Compare (const void * arg1, const void * arg2) static
Definition at line 242 of file ui_servers2.c.
{
     float           f1;
     float           f2;
     servernode_t*   t1;
     servernode_t*   t2;
     t1 = (servernode_t *)arg1;
     t2 = (servernode_t *)arg2;
     switch( g_sortkey ) {
     case SORT_HOST:
         return Q_stricmp( t1->hostname, t2->hostname );
     case SORT_MAP:
         return Q_stricmp( t1->mapname, t2->mapname );
     case SORT_CLIENTS:
         f1 = t1->maxclients - t1->numclients;
         if( f1 < 0 ) {
             f1 = 0;
         }
         f2 = t2->maxclients - t2->numclients;
         if( f2 < 0 ) {
             f2 = 0;
         }
         if( f1 < f2 ) {
             return 1;
         }
         if( f1 == f2 ) {
             return 0;
         }
         return -1;
     case SORT_PING:
         if( t1->pingtime < t2->pingtime ) {
             return -1;
         }
         if( t1->pingtime > t2->pingtime ) {
             return 1;
         }
         return Q_stricmp( t1->hostname, t2->hostname );
     }
     return 0;
 }
References f1, f2, g_sortkey, Q_stricmp(), SORT_CLIENTS, SORT_HOST, SORT_MAP, and SORT_PING.
Referenced by ArenaServers_Sort(), ArenaServers_StopRefresh(), and ArenaServers_UpdateMenu().
ArenaServers_DoRefresh()
static void ArenaServers_DoRefresh (void) static
Definition at line 770 of file ui_servers2.c.
 {
     int     i;
     int     j;
     int     time;
     int     maxPing;
     char    adrstr[MAX_ADDRESSLENGTH];
     char    info[MAX_INFO_STRING];
     if (uis.realtime < g_arenaservers.refreshtime)
     {
       if (g_servertype != UIAS_FAVORITES) {
             if (g_servertype == UIAS_LOCAL) {
                 if (!trap_LAN_GetServerCount(AS_LOCAL)) {
                     return;
                 }
             }
             if (trap_LAN_GetServerCount(ArenaServers_SourceForLAN()) < 0) {
               // still waiting for response
               return;
             }
       }
     }
     if (uis.realtime < g_arenaservers.nextpingtime)
     {
         // wait for time trigger
         return;
     }
     // trigger at 10Hz intervals
     g_arenaservers.nextpingtime = uis.realtime + 10;
     // process ping results
     maxPing = ArenaServers_MaxPing();
     for (i=0; i<MAX_PINGREQUESTS; i++)
     {
         trap_LAN_GetPing( i, adrstr, MAX_ADDRESSLENGTH, &time );
         if (!adrstr[0])
         {
             // ignore empty or pending pings
             continue;
         }
         // find ping result in our local list
         for (j=0; j<MAX_PINGREQUESTS; j++)
             if (!Q_stricmp( adrstr, g_arenaservers.pinglist[j].adrstr ))
                 break;
         if (j < MAX_PINGREQUESTS)
         {
             // found it
             if (!time)
             {
                 time = uis.realtime - g_arenaservers.pinglist[j].start;
                 if (time < maxPing)
                 {
                     // still waiting
                     continue;
                 }
             }
             if (time > maxPing)
             {
                 // stale it out
                 info[0] = '\0';
                 time    = maxPing;
             }
             else
             {
                 trap_LAN_GetPingInfo( i, info, MAX_INFO_STRING );
             }
             // insert ping results
             ArenaServers_Insert( adrstr, info, time );
             // clear this query from internal list
             g_arenaservers.pinglist[j].adrstr[0] = '\0';
         }
         // clear this query from external list
         trap_LAN_ClearPing( i );
     }
     // get results of servers query
     // counts can increase as servers respond
     if (g_servertype == UIAS_FAVORITES) {
       g_arenaservers.numqueriedservers = g_arenaservers.numfavoriteaddresses;
     } else {
       g_arenaservers.numqueriedservers = trap_LAN_GetServerCount(ArenaServers_SourceForLAN());
     }
 //  if (g_arenaservers.numqueriedservers > g_arenaservers.maxservers)
 //      g_arenaservers.numqueriedservers = g_arenaservers.maxservers;
     // send ping requests in reasonable bursts
     // iterate ping through all found servers
     for (i=0; i<MAX_PINGREQUESTS && g_arenaservers.currentping < g_arenaservers.numqueriedservers; i++)
     {
         if (trap_LAN_GetPingQueueCount() >= MAX_PINGREQUESTS)
         {
             // ping queue is full
             break;
         }
         // find empty slot
         for (j=0; j<MAX_PINGREQUESTS; j++)
             if (!g_arenaservers.pinglist[j].adrstr[0])
                 break;
         if (j >= MAX_PINGREQUESTS)
             // no empty slots available yet - wait for timeout
             break;
         // get an address to ping
         if (g_servertype == UIAS_FAVORITES) {
           strcpy( adrstr, g_arenaservers.favoriteaddresses[g_arenaservers.currentping] );
         } else {
           trap_LAN_GetServerAddressString(ArenaServers_SourceForLAN(), g_arenaservers.currentping, adrstr, MAX_ADDRESSLENGTH );
         }
         strcpy( g_arenaservers.pinglist[j].adrstr, adrstr );
         g_arenaservers.pinglist[j].start = uis.realtime;
         trap_Cmd_ExecuteText( EXEC_NOW, va( "ping %s\n", adrstr )  );
         // advance to next server
         g_arenaservers.currentping++;
     }
     if (!trap_LAN_GetPingQueueCount())
     {
         // all pings completed
         ArenaServers_StopRefresh();
         return;
     }
     // update the user interface with ping status
     ArenaServers_UpdateMenu();
 }
References pinglist_t::adrstr, ArenaServers_Insert(), ArenaServers_MaxPing(), ArenaServers_SourceForLAN(), ArenaServers_StopRefresh(), ArenaServers_UpdateMenu(), AS_LOCAL, arenaservers_t::currentping, EXEC_NOW, arenaservers_t::favoriteaddresses, g_arenaservers, g_servertype, info, MAX_ADDRESSLENGTH, MAX_INFO_STRING, MAX_PINGREQUESTS, arenaservers_t::nextpingtime, arenaservers_t::numfavoriteaddresses, arenaservers_t::numqueriedservers, arenaservers_t::pinglist, Q_stricmp(), uiStatic_t::realtime, arenaservers_t::refreshtime, pinglist_t::start, trap_Cmd_ExecuteText(), trap_LAN_ClearPing(), trap_LAN_GetPing(), trap_LAN_GetPingInfo(), trap_LAN_GetPingQueueCount(), trap_LAN_GetServerAddressString(), trap_LAN_GetServerCount(), UIAS_FAVORITES, UIAS_LOCAL, uis, and va().
Referenced by ArenaServers_MenuDraw().
ArenaServers_Event()
static void ArenaServers_Event (void * ptr, int event) static
Definition at line 1085 of file ui_servers2.c.
{
     int     id;
     char    buff[256];
     id = ((menucommon_s*)ptr)->id;
     if( event != QM_ACTIVATED && id != ID_LIST ) {
         return;
     }
     switch( id ) {
     case ID_MASTER:
         g_arenaservers.master.curvalue = ArenaServers_SetType(g_arenaservers.master.curvalue);
         trap_Cvar_SetValue( "ui_browserMaster", g_arenaservers.master.curvalue);
         break;
     case ID_GAMETYPE:
         trap_Cvar_SetValue( "ui_browserGameType", g_arenaservers.gametype.curvalue );
         g_gametype = g_arenaservers.gametype.curvalue;
         ArenaServers_UpdateMenu();
         break;
     case ID_SORTKEY:
         trap_Cvar_SetValue( "ui_browserSortKey", g_arenaservers.sortkey.curvalue );
         ArenaServers_Sort( g_arenaservers.sortkey.curvalue );
         ArenaServers_UpdateMenu();
         break;
     case ID_SHOW_FULL:
         trap_Cvar_SetValue( "ui_browserShowFull", g_arenaservers.showfull.curvalue );
         g_fullservers = g_arenaservers.showfull.curvalue;
         ArenaServers_UpdateMenu();
         break;
     case ID_SHOW_EMPTY:
         trap_Cvar_SetValue( "ui_browserShowEmpty", g_arenaservers.showempty.curvalue );
         g_emptyservers = g_arenaservers.showempty.curvalue;
         ArenaServers_UpdateMenu();
         break;
     case ID_LIST:
         break;
     case ID_SCROLL_UP:
         ScrollList_Key( &g_arenaservers.list, K_UPARROW );
         break;
     case ID_SCROLL_DOWN:
         ScrollList_Key( &g_arenaservers.list, K_DOWNARROW );
         break;
     case ID_CONNECT:
         ArenaServers_Go();
         break;
     case ID_CREATE:
         UI_StartServerMenu();
         break;
     case ID_REFRESH:
         ArenaServers_StartRefresh();
         break;
     case ID_BACK:
         ArenaServers_StopRefresh();
         ArenaServers_SaveChanges();
         UI_PopMenu();
         break;
     case ID_REMOVE:
         ArenaServers_Remove();
         ArenaServers_UpdateMenu();
         break;
     }
 }
References ArenaServers_Go(), ArenaServers_Remove(), ArenaServers_SaveChanges(), ArenaServers_SetType(), ArenaServers_Sort(), ArenaServers_StartRefresh(), ArenaServers_StopRefresh(), ArenaServers_UpdateMenu(), menulist_s::curvalue, menuradiobutton_s::curvalue, g_arenaservers, g_emptyservers, g_fullservers, g_gametype, arenaservers_t::gametype, ID_BACK, ID_CONNECT, ID_CREATE, ID_GAMETYPE, ID_LIST, ID_MASTER, ID_REFRESH, ID_REMOVE, ID_SCROLL_DOWN, ID_SCROLL_UP, ID_SHOW_EMPTY, ID_SHOW_FULL, ID_SORTKEY, K_DOWNARROW, K_UPARROW, arenaservers_t::list, arenaservers_t::master, ptr(), QM_ACTIVATED, ScrollList_Key(), arenaservers_t::showempty, arenaservers_t::showfull, arenaservers_t::sortkey, trap_Cvar_SetValue(), UI_PopMenu(), and UI_StartServerMenu().
Referenced by ArenaServers_MenuInit().
ArenaServers_Go()
static void ArenaServers_Go (void) static
Definition at line 318 of file ui_servers2.c.
{
     servernode_t* servernode;
     char buff[256];
     if(g_arenaservers.domain.field.buffer[0]){
         strcpy(buff,g_arenaservers.domain.field.buffer);
         if(g_arenaservers.port.field.buffer[0]){
             Com_sprintf( buff+strlen(buff), 128, ":%s", g_arenaservers.port.field.buffer );
         }
         trap_Cmd_ExecuteText(EXEC_APPEND,va("connect %s\n",buff));
     }
 }
References mfield_t::buffer, Com_sprintf(), arenaservers_t::domain, EXEC_APPEND, menufield_s::field, g_arenaservers, arenaservers_t::port, trap_Cmd_ExecuteText(), and va().
Referenced by ArenaServers_Event().
ArenaServers_Insert()
static void ArenaServers_Insert (char * adrstr, char * info, int pingtime) static
Definition at line 547 of file ui_servers2.c.
 {
     servernode_t*   servernodeptr;
     char*           s;
     int             i;
     if ((pingtime >= ArenaServers_MaxPing()) && (g_servertype != UIAS_FAVORITES))
     {
         // slow global or local servers do not get entered
         return;
     }
     if (*g_arenaservers.numservers >= g_arenaservers.maxservers) {
         // list full;
         servernodeptr = g_arenaservers.serverlist+(*g_arenaservers.numservers)-1;
     } else {
         // next slot
         servernodeptr = g_arenaservers.serverlist+(*g_arenaservers.numservers);
         (*g_arenaservers.numservers)++;
     }
     Q_strncpyz( servernodeptr->adrstr, adrstr, MAX_ADDRESSLENGTH );
     Q_strncpyz( servernodeptr->hostname, Info_ValueForKey( info, "hostname"), MAX_HOSTNAMELENGTH );
     Q_CleanStr( servernodeptr->hostname );
     Q_strupr( servernodeptr->hostname );
     Q_strncpyz( servernodeptr->mapname, Info_ValueForKey( info, "mapname"), MAX_MAPNAMELENGTH );
     Q_CleanStr( servernodeptr->mapname );
     Q_strupr( servernodeptr->mapname );
     servernodeptr->numclients = atoi( Info_ValueForKey( info, "clients") );
     servernodeptr->maxclients = atoi( Info_ValueForKey( info, "sv_maxclients") );
     servernodeptr->pingtime   = pingtime;
     servernodeptr->minPing    = atoi( Info_ValueForKey( info, "minPing") );
     servernodeptr->maxPing    = atoi( Info_ValueForKey( info, "maxPing") );
     s = Info_ValueForKey( info, "nettype" );
     for (i=0; ;i++)
     {
         if (!netnames[i])
         {
             servernodeptr->nettype = 0;
             break;
         }
         else if (!Q_stricmp( netnames[i], s ))
         {
             servernodeptr->nettype = i;
             break;
         }
     }
     servernodeptr->nettype = atoi(Info_ValueForKey(info, "nettype"));
     if (servernodeptr->nettype < 0 || servernodeptr->nettype >= ARRAY_LEN(netnames) - 1) {
         servernodeptr->nettype = 0;
     }
     s = Info_ValueForKey( info, "game");
     i = atoi( Info_ValueForKey( info, "gametype") );
     if( i < 0 ) {
         i = 0;
     }
     else if( i > 11 ) {
         i = 12;
     }
     if( *s ) {
         servernodeptr->gametype = i;//-1;
         Q_strncpyz( servernodeptr->gamename, s, sizeof(servernodeptr->gamename) );
     }
     else {
         servernodeptr->gametype = i;
         Q_strncpyz( servernodeptr->gamename, gamenames[i], sizeof(servernodeptr->gamename) );
     }
 }
References ArenaServers_MaxPing(), ARRAY_LEN, g_arenaservers, g_servertype, gamenames, info, Info_ValueForKey(), MAX_ADDRESSLENGTH, MAX_HOSTNAMELENGTH, MAX_MAPNAMELENGTH, arenaservers_t::maxservers, netnames, arenaservers_t::numservers, Q_CleanStr(), Q_stricmp(), Q_strncpyz(), Q_strupr(), arenaservers_t::serverlist, and UIAS_FAVORITES.
Referenced by ArenaServers_DoRefresh(), and ArenaServers_InsertFavorites().
ArenaServers_InsertFavorites()
void ArenaServers_InsertFavorites (void)
Definition at line 632 of file ui_servers2.c.
 {
     int     i;
     int     j;
     char    info[MAX_INFO_STRING];
     // resync existing results with new or deleted cvars
     info[0] = '\0';
     Info_SetValueForKey( info, "hostname", "No Response" );
     for (i=0; i<g_arenaservers.numfavoriteaddresses; i++)
     {
         // find favorite address in refresh list
         for (j=0; j<g_numfavoriteservers; j++)
             if (!Q_stricmp(g_arenaservers.favoriteaddresses[i],g_favoriteserverlist[j].adrstr))
                 break;
         if ( j >= g_numfavoriteservers)
         {
             // not in list, add it
             ArenaServers_Insert( g_arenaservers.favoriteaddresses[i], info, ArenaServers_MaxPing() );
         }
     }
 }
References ArenaServers_Insert(), ArenaServers_MaxPing(), arenaservers_t::favoriteaddresses, g_arenaservers, g_favoriteserverlist, g_numfavoriteservers, info, Info_SetValueForKey(), MAX_INFO_STRING, arenaservers_t::numfavoriteaddresses, and Q_stricmp().
Referenced by ArenaServers_StopRefresh().
ArenaServers_LoadFavorites()
void ArenaServers_LoadFavorites (void)
Definition at line 664 of file ui_servers2.c.
 {
     int             i;
     int             j;
     int             numtempitems;
     char            adrstr[MAX_ADDRESSLENGTH];
     servernode_t    templist[MAX_FAVORITESERVERS];
     qboolean        found;
     found        = qfalse;
     // copy the old
     memcpy( templist, g_favoriteserverlist, sizeof(servernode_t)*MAX_FAVORITESERVERS );
     numtempitems = g_numfavoriteservers;
     // clear the current for sync
     memset( g_favoriteserverlist, 0, sizeof(servernode_t)*MAX_FAVORITESERVERS );
     g_numfavoriteservers = 0;
     // resync existing results with new or deleted cvars
     for (i=0; i<MAX_FAVORITESERVERS; i++)
     {
         trap_Cvar_VariableStringBuffer( va("server%d",i+1), adrstr, MAX_ADDRESSLENGTH );
         if (!adrstr[0])
             continue;
         // quick sanity check to avoid slow domain name resolving
         // first character must be numeric
         if (adrstr[0] < '0' || adrstr[0] > '9')
             continue;
         // favorite server addresses must be maintained outside refresh list
         // this mimics local and global netadr's stored in client
         // these can be fetched to fill ping list
         strcpy( g_arenaservers.favoriteaddresses[g_numfavoriteservers], adrstr );
         // find this server in the old list
         for (j=0; j<numtempitems; j++)
             if (!Q_stricmp( templist[j].adrstr, adrstr ))
                 break;
         if (j < numtempitems)
         {
             // found server - add exisiting results
             memcpy( &g_favoriteserverlist[g_numfavoriteservers], &templist[j], sizeof(servernode_t) );
             found = qtrue;
         }
         else
         {
             // add new server
             Q_strncpyz( g_favoriteserverlist[g_numfavoriteservers].adrstr, adrstr, MAX_ADDRESSLENGTH );
             g_favoriteserverlist[g_numfavoriteservers].pingtime = ArenaServers_MaxPing();
         }
         g_numfavoriteservers++;
     }
     g_arenaservers.numfavoriteaddresses = g_numfavoriteservers;
     if (!found)
     {
         // no results were found, reset server list
         // list will be automatically refreshed when selected
         g_numfavoriteservers = 0;
     }
 }
References ArenaServers_MaxPing(), arenaservers_t::favoriteaddresses, g_arenaservers, g_favoriteserverlist, g_numfavoriteservers, MAX_ADDRESSLENGTH, MAX_FAVORITESERVERS, arenaservers_t::numfavoriteaddresses, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, trap_Cvar_VariableStringBuffer(), and va().
Referenced by ArenaServers_MenuInit().
ArenaServers_MaxPing()
static int ArenaServers_MaxPing (void) static
Definition at line 226 of file ui_servers2.c.
{
     int     maxPing;
     maxPing = (int)trap_Cvar_VariableValue( "cl_maxPing" );
     if( maxPing < 100 ) {
         maxPing = 100;
     }
     return maxPing;
 }
References int(), and trap_Cvar_VariableValue().
Referenced by ArenaServers_DoRefresh(), ArenaServers_Insert(), ArenaServers_InsertFavorites(), and ArenaServers_LoadFavorites().
ArenaServers_MenuDraw()
static void ArenaServers_MenuDraw (void) static
Definition at line 1179 of file ui_servers2.c.
{
     char* addressString = g_arenaservers.domain.field.buffer;
     char* portString = g_arenaservers.port.field.buffer;
     int serverIndex;
     servernode_t*   serverNode;
     if(g_arenaservers.refreshservers){ArenaServers_DoRefresh();}
     serverIndex = g_arenaservers.list.curvalue;
     serverNode = g_arenaservers.table[serverIndex].servernode;
     uis.menuamount = 4;
     uis.hideEarth = qtrue;
     uis.showFrame = qfalse;
     if(g_arenaservers.list.generic.flags & QMF_HASMOUSEFOCUS && serverNode){
         char* split = serverNode->adrstr;
         strrep(split,':',' ');
         strcpy(addressString,COM_Parse(&split));
         strcpy(portString,COM_Parse(&split));
     }
     Menu_Draw(&g_arenaservers.menu);
 }
References ArenaServers_DoRefresh(), mfield_t::buffer, COM_Parse(), menulist_s::curvalue, arenaservers_t::domain, menufield_s::field, menucommon_s::flags, g_arenaservers, menulist_s::generic, uiStatic_t::hideEarth, arenaservers_t::list, arenaservers_t::menu, Menu_Draw(), uiStatic_t::menuamount, arenaservers_t::port, qfalse, QMF_HASMOUSEFOCUS, qtrue, arenaservers_t::refreshservers, table_t::servernode, uiStatic_t::showFrame, strrep(), arenaservers_t::table, and uis.
Referenced by ArenaServers_MenuInit().
ArenaServers_MenuInit()
static void ArenaServers_MenuInit (void) static
Definition at line 1233 of file ui_servers2.c.
{
     int         i;
     int         y;
     int         value;
     static char statusbuffer[MAX_STATUSLENGTH];
     // zero set all our globals
     memset( &g_arenaservers, 0 ,sizeof(arenaservers_t) );
     ArenaServers_Cache();
     uis.menuamount = 0;
     g_arenaservers.menu.fullscreen = qtrue;
     g_arenaservers.menu.wrapAround = qtrue;
     g_arenaservers.menu.draw       = ArenaServers_MenuDraw;
     g_arenaservers.menu.key        = ArenaServers_MenuKey;
     g_arenaservers.banner.generic.type  = MTYPE_BTEXT;
     g_arenaservers.banner.generic.flags = QMF_CENTER_JUSTIFY;
     g_arenaservers.banner.generic.x     = 320;
     g_arenaservers.banner.generic.y     = 16;
     g_arenaservers.banner.string        = "ZEQII LITE SERVERS";
     g_arenaservers.banner.style         = UI_CENTER|UI_DROPSHADOW;
     g_arenaservers.banner.color         = color_white;
     y = 30;
     g_arenaservers.master.generic.type          = MTYPE_SPINCONTROL;
     g_arenaservers.master.generic.name          = "Servers:";
     g_arenaservers.master.generic.flags         = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     g_arenaservers.master.generic.callback      = ArenaServers_Event;
     g_arenaservers.master.generic.id            = ID_MASTER;
     g_arenaservers.master.generic.x             = 290;
     g_arenaservers.master.generic.y             = y;
     g_arenaservers.master.itemnames             = master_items;
     y += SMALLCHAR_HEIGHT;
     g_arenaservers.sortkey.generic.type         = MTYPE_SPINCONTROL;
     g_arenaservers.sortkey.generic.name         = "Sort By:";
     g_arenaservers.sortkey.generic.flags        = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     g_arenaservers.sortkey.generic.callback     = ArenaServers_Event;
     g_arenaservers.sortkey.generic.id           = ID_SORTKEY;
     g_arenaservers.sortkey.generic.x            = 290;
     g_arenaservers.sortkey.generic.y            = y;
     g_arenaservers.sortkey.itemnames            = sortkey_items;
     y += 3 * SMALLCHAR_HEIGHT;
     g_arenaservers.list.generic.type            = MTYPE_SCROLLLIST;
     g_arenaservers.list.generic.flags           = QMF_HIGHLIGHT_IF_FOCUS;
     g_arenaservers.list.generic.id              = ID_LIST;
     g_arenaservers.list.generic.callback        = ArenaServers_Event;
     g_arenaservers.list.generic.x               = 150;
     g_arenaservers.list.generic.y               = 112;
     g_arenaservers.list.width                   = MAX_LISTBOXWIDTH;
     g_arenaservers.list.height                  = 11;
     g_arenaservers.list.itemnames               = (const char **)g_arenaservers.items;
     for( i = 0; i < MAX_LISTBOXITEMS; i++ ) {
         g_arenaservers.items[i] = g_arenaservers.table[i].buff;
     }
     g_arenaservers.arrows.generic.type          = MTYPE_BITMAP;
     g_arenaservers.arrows.generic.name          = ART_ARROWS0;
     g_arenaservers.arrows.generic.flags         = QMF_LEFT_JUSTIFY|QMF_INACTIVE;
     g_arenaservers.arrows.generic.callback      = ArenaServers_Event;
     g_arenaservers.arrows.generic.x             = 512+48;
     g_arenaservers.arrows.generic.y             = 180-64+16;
     g_arenaservers.arrows.width                 = 64;
     g_arenaservers.arrows.height                = 128;
     g_arenaservers.up.generic.type              = MTYPE_BITMAP;
     g_arenaservers.up.generic.flags             = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     g_arenaservers.up.generic.callback          = ArenaServers_Event;
     g_arenaservers.up.generic.id                = ID_SCROLL_UP;
     g_arenaservers.up.generic.x                 = 512+48;
     g_arenaservers.up.generic.y                 = 180-64+16;
     g_arenaservers.up.width                     = 64;
     g_arenaservers.up.height                    = 64;
     g_arenaservers.up.focuspic                  = ART_ARROWS_UP;
     g_arenaservers.down.generic.type            = MTYPE_BITMAP;
     g_arenaservers.down.generic.flags           = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     g_arenaservers.down.generic.callback        = ArenaServers_Event;
     g_arenaservers.down.generic.id              = ID_SCROLL_DOWN;
     g_arenaservers.down.generic.x               = 512+48;
     g_arenaservers.down.generic.y               = 480+16;
     g_arenaservers.down.width                   = 64;
     g_arenaservers.down.height                  = 64;
     g_arenaservers.down.focuspic                = ART_ARROWS_DOWN;
     y = 440;
     g_arenaservers.status.generic.type      = MTYPE_TEXT;
     g_arenaservers.status.generic.x         = 320;
     g_arenaservers.status.generic.y         = y;
     g_arenaservers.status.string            = statusbuffer;
     g_arenaservers.status.style             = UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW;
     g_arenaservers.status.color             = menu_text_color;
     y += SMALLCHAR_HEIGHT;
     g_arenaservers.statusbar.generic.type   = MTYPE_TEXT;
     g_arenaservers.statusbar.generic.x      = 320;
     g_arenaservers.statusbar.generic.y      = y;
     g_arenaservers.statusbar.string         = "";
     g_arenaservers.statusbar.style          = UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW;
     g_arenaservers.statusbar.color          = text_color_normal;
     g_arenaservers.go.generic.type      = MTYPE_PTEXT;
     g_arenaservers.go.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.go.generic.id        = ID_CONNECT;
     g_arenaservers.go.generic.callback  = ArenaServers_Event;
     g_arenaservers.go.generic.x         = 28;
     g_arenaservers.go.generic.y         = 119;
     g_arenaservers.go.string            = "FIGHT!";
     g_arenaservers.go.style             = UI_LEFT | UI_DROPSHADOW | UI_TINYFONT;
     g_arenaservers.go.color             = color_silver;
     y+=38;
     g_arenaservers.create.generic.type      = MTYPE_PTEXT;
     g_arenaservers.create.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.create.generic.id        = ID_CREATE;
     g_arenaservers.create.generic.callback  = ArenaServers_Event;
     g_arenaservers.create.generic.x         = 28;
     g_arenaservers.create.generic.y         = 157;
     g_arenaservers.create.string            = "CREATE";
     g_arenaservers.create.style             = UI_LEFT | UI_DROPSHADOW | UI_TINYFONT;
     g_arenaservers.create.color             = color_silver;
     y+=38;
     g_arenaservers.refresh.generic.type     = MTYPE_PTEXT;
     g_arenaservers.refresh.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.refresh.generic.id       = ID_REFRESH;
     g_arenaservers.refresh.generic.callback = ArenaServers_Event;
     g_arenaservers.refresh.generic.x        = 28;
     g_arenaservers.refresh.generic.y        = 195;
     g_arenaservers.refresh.string           = "REFRESH";
     g_arenaservers.refresh.style            = UI_LEFT | UI_DROPSHADOW | UI_TINYFONT;
     g_arenaservers.refresh.color            = color_silver;
     y+=38;
     g_arenaservers.back.generic.type        = MTYPE_PTEXT;
     g_arenaservers.back.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.back.generic.id          = ID_BACK;
     g_arenaservers.back.generic.callback    = ArenaServers_Event;
     g_arenaservers.back.generic.x           = 28;
     g_arenaservers.back.generic.y           = 233;
     g_arenaservers.back.string              = "BACK";
     g_arenaservers.back.style               = UI_LEFT | UI_DROPSHADOW | UI_TINYFONT;
     g_arenaservers.back.color               = color_silver;
     y+=38;
     g_arenaservers.remove.generic.type      = MTYPE_BITMAP;
     g_arenaservers.remove.generic.name      = ART_REMOVE0;
     g_arenaservers.remove.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.remove.generic.callback  = ArenaServers_Event;
     g_arenaservers.remove.generic.id        = ID_REMOVE;
     g_arenaservers.remove.generic.x         = 512;
     g_arenaservers.remove.generic.y         = 86;
     g_arenaservers.remove.width             = 96;
     g_arenaservers.remove.height            = 48;
     g_arenaservers.remove.focuspic          = ART_REMOVE1;
     g_arenaservers.name.generic.type        = MTYPE_TEXT;
     g_arenaservers.name.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.name.generic.id          = ID_NAME;
     g_arenaservers.name.generic.callback    = ArenaServers_Event;
     g_arenaservers.name.string              = "Name";
     g_arenaservers.name.generic.x           = 150;
     g_arenaservers.name.generic.y           = 90;
     g_arenaservers.name.style               = UI_LEFT | UI_DROPSHADOW | UI_SMALLFONT;
     g_arenaservers.name.color               = color_silver;
     g_arenaservers.mapname.generic.type         = MTYPE_TEXT;
     g_arenaservers.mapname.generic.flags        = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.mapname.generic.id           = ID_MAPNAME;
     g_arenaservers.mapname.generic.callback     = ArenaServers_Event;
     g_arenaservers.mapname.string               = "Map Name";
     g_arenaservers.mapname.generic.x            = 370;
     g_arenaservers.mapname.generic.y            = 90;
     g_arenaservers.mapname.style                = UI_LEFT | UI_DROPSHADOW | UI_SMALLFONT;
     g_arenaservers.mapname.color                = color_silver;
     g_arenaservers.players.generic.type     = MTYPE_TEXT;
     g_arenaservers.players.generic.flags        = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.players.generic.id           = ID_NAME;
     g_arenaservers.players.generic.callback = ArenaServers_Event;
     g_arenaservers.players.string               = "Players";
     g_arenaservers.players.generic.x            = 460;
     g_arenaservers.players.generic.y            = 90;
     g_arenaservers.players.style                = UI_LEFT | UI_DROPSHADOW | UI_SMALLFONT;
     g_arenaservers.players.color                = color_silver;
     g_arenaservers.latency.generic.type     = MTYPE_TEXT;
     g_arenaservers.latency.generic.flags        = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     g_arenaservers.latency.generic.id           = ID_NAME;
     g_arenaservers.latency.generic.callback = ArenaServers_Event;
     g_arenaservers.latency.string               = "Latency";
     g_arenaservers.latency.generic.x            = 520;
     g_arenaservers.latency.generic.y            = 90;
     g_arenaservers.latency.style                = UI_LEFT | UI_DROPSHADOW | UI_SMALLFONT;
     g_arenaservers.latency.color                = color_silver;
     y = 30;
     g_arenaservers.domain.generic.type       = MTYPE_FIELD;
     g_arenaservers.domain.generic.name       = "Address:";
     g_arenaservers.domain.generic.flags      = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     g_arenaservers.domain.generic.x          = 450;
     g_arenaservers.domain.generic.y          = y;
     g_arenaservers.domain.field.widthInChars = 15;
     g_arenaservers.domain.field.maxchars     = 15;
     y += SMALLCHAR_HEIGHT;
     g_arenaservers.port.generic.type       = MTYPE_FIELD;
     g_arenaservers.port.generic.name        = "Port:";
     g_arenaservers.port.generic.flags       = QMF_PULSEIFFOCUS|QMF_SMALLFONT|QMF_NUMBERSONLY;
     g_arenaservers.port.generic.x           = 450;
     g_arenaservers.port.generic.y           = y;
     g_arenaservers.port.field.widthInChars = 6;
     g_arenaservers.port.field.maxchars     = 5;
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.master );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.sortkey );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.list );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.status );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.statusbar );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.arrows );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.up );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.down );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.go );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.create );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.refresh );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.back );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.remove );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.name );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.mapname );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.players );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.latency );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.domain );
     Menu_AddItem( &g_arenaservers.menu, (void*) &g_arenaservers.port );
     Com_sprintf( g_arenaservers.port.field.buffer, 6, "%i", 27960 );
     ArenaServers_LoadFavorites();
     g_arenaservers.master.curvalue = g_servertype = Com_Clamp( 0, 1, ui_browserMaster.integer );
     g_gametype = Com_Clamp( 0, 4, ui_browserGameType.integer );
     g_arenaservers.gametype.curvalue = g_gametype;
     g_sortkey = Com_Clamp( 0, 4, ui_browserSortKey.integer );
     g_arenaservers.sortkey.curvalue = g_sortkey;
     g_fullservers = Com_Clamp( 0, 1, ui_browserShowFull.integer );
     g_arenaservers.showfull.curvalue = g_fullservers;
     g_emptyservers = Com_Clamp( 0, 1, ui_browserShowEmpty.integer );
     g_arenaservers.showempty.curvalue = g_emptyservers;
     // force to initial state and refresh
     g_arenaservers.master.curvalue = g_servertype = ArenaServers_SetType(g_servertype);
     trap_Cvar_Register(NULL, "debug_protocol", "", 0 );
 }
References ArenaServers_Cache(), ArenaServers_Event(), ArenaServers_LoadFavorites(), ArenaServers_MenuDraw(), ArenaServers_MenuKey(), ArenaServers_SetType(), arenaservers_t::arrows, ART_ARROWS0, ART_ARROWS_DOWN, ART_ARROWS_UP, ART_REMOVE0, ART_REMOVE1, arenaservers_t::back, arenaservers_t::banner, table_t::buff, mfield_t::buffer, menucommon_s::callback, menutext_s::color, color_silver, color_white, Com_Clamp(), Com_sprintf(), arenaservers_t::create, menulist_s::curvalue, menuradiobutton_s::curvalue, arenaservers_t::domain, arenaservers_t::down, menufield_s::field, menucommon_s::flags, menubitmap_s::focuspic, g_arenaservers, g_emptyservers, g_fullservers, g_gametype, g_servertype, g_sortkey, arenaservers_t::gametype, menufield_s::generic, menulist_s::generic, menubitmap_s::generic, menutext_s::generic, arenaservers_t::go, menulist_s::height, menubitmap_s::height, menucommon_s::id, ID_BACK, ID_CONNECT, ID_CREATE, ID_LIST, ID_MAPNAME, ID_MASTER, ID_NAME, ID_REFRESH, ID_REMOVE, ID_SCROLL_DOWN, ID_SCROLL_UP, ID_SORTKEY, vmCvar_t::integer, menulist_s::itemnames, arenaservers_t::items, arenaservers_t::latency, arenaservers_t::list, arenaservers_t::mapname, arenaservers_t::master, master_items, MAX_LISTBOXITEMS, MAX_LISTBOXWIDTH, MAX_STATUSLENGTH, mfield_t::maxchars, arenaservers_t::menu, Menu_AddItem(), menu_text_color, uiStatic_t::menuamount, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_PTEXT, MTYPE_SCROLLLIST, MTYPE_SPINCONTROL, MTYPE_TEXT, menucommon_s::name, arenaservers_t::name, NULL, arenaservers_t::players, arenaservers_t::port, QMF_CENTER_JUSTIFY, QMF_HIGHLIGHT_IF_FOCUS, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_MOUSEONLY, QMF_NUMBERSONLY, QMF_PULSEIFFOCUS, QMF_SMALLFONT, qtrue, arenaservers_t::refresh, arenaservers_t::remove, arenaservers_t::showempty, arenaservers_t::showfull, SMALLCHAR_HEIGHT, arenaservers_t::sortkey, sortkey_items, arenaservers_t::status, arenaservers_t::statusbar, menutext_s::string, menutext_s::style, arenaservers_t::table, text_color_normal, trap_Cvar_Register(), menucommon_s::type, ui_browserGameType, ui_browserMaster, ui_browserShowEmpty, ui_browserShowFull, ui_browserSortKey, UI_CENTER, UI_DROPSHADOW, UI_LEFT, UI_SMALLFONT, UI_TINYFONT, uis, arenaservers_t::up, menulist_s::width, menubitmap_s::width, mfield_t::widthInChars, menucommon_s::x, and menucommon_s::y.
Referenced by UI_ArenaServersMenu().
ArenaServers_MenuKey()
static sfxHandle_t ArenaServers_MenuKey (int key) static
Definition at line 1205 of file ui_servers2.c.
{
     if( key == K_SPACE  && g_arenaservers.refreshservers ) {
         ArenaServers_StopRefresh();
         return menu_move_sound;
     }
     if( ( key == K_DEL || key == K_KP_DEL ) && ( g_servertype == UIAS_FAVORITES ) &&
         ( Menu_ItemAtCursor( &g_arenaservers.menu) == &g_arenaservers.list ) ) {
         ArenaServers_Remove();
         ArenaServers_UpdateMenu();
         return menu_move_sound;
     }
     if( key == K_MOUSE2 || key == K_ESCAPE ) {
         ArenaServers_StopRefresh();
         ArenaServers_SaveChanges();
     }
     return Menu_DefaultKey( &g_arenaservers.menu, key );
 }
References ArenaServers_Remove(), ArenaServers_SaveChanges(), ArenaServers_StopRefresh(), ArenaServers_UpdateMenu(), g_arenaservers, g_servertype, K_DEL, K_ESCAPE, K_KP_DEL, K_MOUSE2, K_SPACE, arenaservers_t::list, arenaservers_t::menu, Menu_DefaultKey(), Menu_ItemAtCursor(), menu_move_sound, arenaservers_t::refreshservers, and UIAS_FAVORITES.
Referenced by ArenaServers_MenuInit().
ArenaServers_Remove()
static void ArenaServers_Remove (void) static
Definition at line 486 of file ui_servers2.c.
 {
     int             i;
     servernode_t*   servernodeptr;
     table_t*        tableptr;
     if (!g_arenaservers.list.numitems)
         return;
     // remove selected item from display list
     // items are in scattered order due to sort and cull
     // perform delete on list box contents, resync all lists
     tableptr      = &g_arenaservers.table[g_arenaservers.list.curvalue];
     servernodeptr = tableptr->servernode;
     // find address in master list
     for (i=0; i<g_arenaservers.numfavoriteaddresses; i++)
     {
         if (!Q_stricmp(g_arenaservers.favoriteaddresses[i],servernodeptr->adrstr))
         {
             // delete address from master list
             if (i < g_arenaservers.numfavoriteaddresses-1)
             {
                 // shift items up
                 memcpy( &g_arenaservers.favoriteaddresses[i], &g_arenaservers.favoriteaddresses[i+1], (g_arenaservers.numfavoriteaddresses - i - 1)* MAX_ADDRESSLENGTH );
             }
             g_arenaservers.numfavoriteaddresses--;
             memset( &g_arenaservers.favoriteaddresses[g_arenaservers.numfavoriteaddresses], 0, MAX_ADDRESSLENGTH );
             break;
         }
     }
     // find address in server list
     for (i=0; i<g_numfavoriteservers; i++)
     {
         if (&g_favoriteserverlist[i] == servernodeptr)
         {
             // delete address from server list
             if (i < g_numfavoriteservers-1)
             {
                 // shift items up
                 memcpy( &g_favoriteserverlist[i], &g_favoriteserverlist[i+1], (g_numfavoriteservers - i - 1)*sizeof(servernode_t));
             }
             g_numfavoriteservers--;
             memset( &g_favoriteserverlist[ g_numfavoriteservers ], 0, sizeof(servernode_t));
             break;
         }
     }
     g_arenaservers.numqueriedservers = g_arenaservers.numfavoriteaddresses;
     g_arenaservers.currentping       = g_arenaservers.numfavoriteaddresses;
 }
References arenaservers_t::currentping, menulist_s::curvalue, arenaservers_t::favoriteaddresses, g_arenaservers, g_favoriteserverlist, g_numfavoriteservers, arenaservers_t::list, MAX_ADDRESSLENGTH, arenaservers_t::numfavoriteaddresses, menulist_s::numitems, arenaservers_t::numqueriedservers, Q_stricmp(), table_t::servernode, and arenaservers_t::table.
Referenced by ArenaServers_Event(), and ArenaServers_MenuKey().
ArenaServers_SaveChanges()
void ArenaServers_SaveChanges (void)
Definition at line 986 of file ui_servers2.c.
 {
     int i;
     for (i=0; i<g_arenaservers.numfavoriteaddresses; i++)
         trap_Cvar_Set( va("server%d",i+1), g_arenaservers.favoriteaddresses[i] );
     for (; i<MAX_FAVORITESERVERS; i++)
         trap_Cvar_Set( va("server%d",i+1), "" );
 }
References arenaservers_t::favoriteaddresses, g_arenaservers, MAX_FAVORITESERVERS, arenaservers_t::numfavoriteaddresses, trap_Cvar_Set(), and va().
Referenced by ArenaServers_Event(), and ArenaServers_MenuKey().
ArenaServers_SetType()
int ArenaServers_SetType (int type)
Definition at line 1018 of file ui_servers2.c.
 {
     if(type >= UIAS_GLOBAL1 && type <= UIAS_GLOBAL5)
     {
         char masterstr[2], cvarname[sizeof("sv_master1")];
         while(type <= UIAS_GLOBAL5)
         {
             Com_sprintf(cvarname, sizeof(cvarname), "sv_master%d", type);
             trap_Cvar_VariableStringBuffer(cvarname, masterstr, sizeof(masterstr));
             if(*masterstr)
                 break;
             type++;
         }
     }
     g_servertype = type;
     switch( type ) {
     default:
     case UIAS_LOCAL:
         g_arenaservers.remove.generic.flags |= (QMF_INACTIVE|QMF_HIDDEN);
         g_arenaservers.serverlist = g_localserverlist;
         g_arenaservers.numservers = &g_numlocalservers;
         g_arenaservers.maxservers = MAX_LOCALSERVERS;
         break;
     case UIAS_GLOBAL1:
     case UIAS_GLOBAL2:
     case UIAS_GLOBAL3:
     case UIAS_GLOBAL4:
     case UIAS_GLOBAL5:
         g_arenaservers.remove.generic.flags |= (QMF_INACTIVE|QMF_HIDDEN);
         g_arenaservers.serverlist = g_globalserverlist;
         g_arenaservers.numservers = &g_numglobalservers;
         g_arenaservers.maxservers = MAX_GLOBALSERVERS;
         break;
     case UIAS_FAVORITES:
         g_arenaservers.remove.generic.flags &= ~(QMF_INACTIVE|QMF_HIDDEN);
         g_arenaservers.serverlist = g_favoriteserverlist;
         g_arenaservers.numservers = &g_numfavoriteservers;
         g_arenaservers.maxservers = MAX_FAVORITESERVERS;
         break;
     }
     if( !*g_arenaservers.numservers ) {
         ArenaServers_StartRefresh();
     }
     else {
         // avoid slow operation, use existing results
         g_arenaservers.currentping       = *g_arenaservers.numservers;
         g_arenaservers.numqueriedservers = *g_arenaservers.numservers;
         ArenaServers_UpdateMenu();
         //strcpy(g_arenaservers.status.string,"hit refresh to update");
     }
     return type;
 }
References ArenaServers_StartRefresh(), ArenaServers_UpdateMenu(), Com_sprintf(), arenaservers_t::currentping, menucommon_s::flags, g_arenaservers, g_favoriteserverlist, g_globalserverlist, g_localserverlist, g_numfavoriteservers, g_numglobalservers, g_numlocalservers, g_servertype, menubitmap_s::generic, MAX_FAVORITESERVERS, MAX_GLOBALSERVERS, MAX_LOCALSERVERS, arenaservers_t::maxservers, arenaservers_t::numqueriedservers, arenaservers_t::numservers, QMF_HIDDEN, QMF_INACTIVE, arenaservers_t::remove, arenaservers_t::serverlist, trap_Cvar_VariableStringBuffer(), UIAS_FAVORITES, UIAS_GLOBAL1, UIAS_GLOBAL2, UIAS_GLOBAL3, UIAS_GLOBAL4, UIAS_GLOBAL5, and UIAS_LOCAL.
Referenced by ArenaServers_Event(), and ArenaServers_MenuInit().
ArenaServers_Sort()
void ArenaServers_Sort (int type)
Definition at line 1003 of file ui_servers2.c.
{
     if( g_sortkey == type ) {
         return;
     }
     g_sortkey = type;
     qsort( g_arenaservers.serverlist, *g_arenaservers.numservers, sizeof( servernode_t ), ArenaServers_Compare);
 }
References ArenaServers_Compare(), g_arenaservers, g_sortkey, arenaservers_t::numservers, and arenaservers_t::serverlist.
Referenced by ArenaServers_Event().
ArenaServers_SourceForLAN()
int ArenaServers_SourceForLAN (void)
Definition at line 297 of file ui_servers2.c.
{
     switch( g_servertype ) {
     default:
     case UIAS_LOCAL:
         return AS_LOCAL;
     case UIAS_GLOBAL1:
     case UIAS_GLOBAL2:
     case UIAS_GLOBAL3:
     case UIAS_GLOBAL4:
     case UIAS_GLOBAL5:
         return AS_GLOBAL;
     case UIAS_FAVORITES:
         return AS_FAVORITES;
     }
 }
References AS_FAVORITES, AS_GLOBAL, AS_LOCAL, g_servertype, UIAS_FAVORITES, UIAS_GLOBAL1, UIAS_GLOBAL2, UIAS_GLOBAL3, UIAS_GLOBAL4, UIAS_GLOBAL5, and UIAS_LOCAL.
Referenced by ArenaServers_DoRefresh().
ArenaServers_StartRefresh()
static void ArenaServers_StartRefresh (void) static
Definition at line 918 of file ui_servers2.c.
 {
     int     i;
     char    myargs[32], protocol[32];
     memset( g_arenaservers.serverlist, 0, g_arenaservers.maxservers*sizeof(table_t) );
     for (i=0; i<MAX_PINGREQUESTS; i++)
     {
         g_arenaservers.pinglist[i].adrstr[0] = '\0';
         trap_LAN_ClearPing( i );
     }
     g_arenaservers.refreshservers    = qtrue;
     g_arenaservers.currentping       = 0;
     g_arenaservers.nextpingtime      = 0;
     *g_arenaservers.numservers       = 0;
     g_arenaservers.numqueriedservers = 0;
     // allow max 5 seconds for responses
     g_arenaservers.refreshtime = uis.realtime + 5000;
     // place menu in zeroed state
     ArenaServers_UpdateMenu();
     if( g_servertype == UIAS_LOCAL ) {
         trap_Cmd_ExecuteText( EXEC_APPEND, "localservers\n" );
         return;
     }
     if( g_servertype >= UIAS_GLOBAL1 && g_servertype <= UIAS_GLOBAL5 ) {
         switch( g_arenaservers.gametype.curvalue ) {
         default:
         case GAMES_ALL:
             myargs[0] = 0;
             break;
         case GAMES_STRUGGLE:
             strcpy( myargs, " struggle" );
             break;
         }
         if (g_emptyservers) {
             strcat(myargs, " empty");
         }
         if (g_fullservers) {
             strcat(myargs, " full");
         }
         protocol[0] = '\0';
         trap_Cvar_VariableStringBuffer( "debug_protocol", protocol, sizeof(protocol) );
         if (strlen(protocol)) {
             trap_Cmd_ExecuteText( EXEC_APPEND, va( "globalservers %d %s%s\n", g_servertype - 1, protocol, myargs ));
         }
         else {
             trap_Cmd_ExecuteText( EXEC_APPEND, va( "globalservers %d %d%s\n", g_servertype - 1, (int)trap_Cvar_VariableValue( "protocol" ), myargs ) );
         }
     }
 }
References pinglist_t::adrstr, ArenaServers_UpdateMenu(), arenaservers_t::currentping, menulist_s::curvalue, EXEC_APPEND, g_arenaservers, g_emptyservers, g_fullservers, g_servertype, GAMES_ALL, GAMES_STRUGGLE, arenaservers_t::gametype, MAX_PINGREQUESTS, arenaservers_t::maxservers, arenaservers_t::nextpingtime, arenaservers_t::numqueriedservers, arenaservers_t::numservers, arenaservers_t::pinglist, qtrue, uiStatic_t::realtime, arenaservers_t::refreshservers, arenaservers_t::refreshtime, arenaservers_t::serverlist, trap_Cmd_ExecuteText(), trap_Cvar_VariableStringBuffer(), trap_Cvar_VariableValue(), trap_LAN_ClearPing(), UIAS_GLOBAL1, UIAS_GLOBAL5, UIAS_LOCAL, uis, and va().
Referenced by ArenaServers_Event(), and ArenaServers_SetType().
ArenaServers_StopRefresh()
static void ArenaServers_StopRefresh (void) static
Definition at line 737 of file ui_servers2.c.
 {
     if (!g_arenaservers.refreshservers)
         // not currently refreshing
         return;
     g_arenaservers.refreshservers = qfalse;
     if (g_servertype == UIAS_FAVORITES)
     {
         // nonresponsive favorites must be shown
         ArenaServers_InsertFavorites();
     }
     // final tally
     if (g_arenaservers.numqueriedservers >= 0)
     {
         g_arenaservers.currentping       = *g_arenaservers.numservers;
         g_arenaservers.numqueriedservers = *g_arenaservers.numservers;
     }
     // sort
     qsort( g_arenaservers.serverlist, *g_arenaservers.numservers, sizeof( servernode_t ), ArenaServers_Compare);
     ArenaServers_UpdateMenu();
 }
References ArenaServers_Compare(), ArenaServers_InsertFavorites(), ArenaServers_UpdateMenu(), arenaservers_t::currentping, g_arenaservers, g_servertype, arenaservers_t::numqueriedservers, arenaservers_t::numservers, qfalse, arenaservers_t::refreshservers, arenaservers_t::serverlist, and UIAS_FAVORITES.
Referenced by ArenaServers_DoRefresh(), ArenaServers_Event(), and ArenaServers_MenuKey().
ArenaServers_UpdateMenu()
static void ArenaServers_UpdateMenu (void) static
Definition at line 333 of file ui_servers2.c.
{
     int             i;
     int             j;
     int             count;
     char*           buff;
     servernode_t*   servernodeptr;
     table_t*        tableptr;
     char            *pingColor;
     if( g_arenaservers.numqueriedservers > 0 ) {
         // servers found
         if( g_arenaservers.refreshservers && ( g_arenaservers.currentping <= g_arenaservers.numqueriedservers ) ) {
             // show progress
             //Com_sprintf( g_arenaservers.status.string, MAX_STATUSLENGTH, "%d of %d ZEQ2-Lite Servers.", g_arenaservers.currentping, g_arenaservers.numqueriedservers);
             //g_arenaservers.statusbar.string  = "Press SPACE to stop";
             qsort( g_arenaservers.serverlist, *g_arenaservers.numservers, sizeof( servernode_t ), ArenaServers_Compare);
         }
         else {
             // all servers pinged - enable controls
             g_arenaservers.master.generic.flags     &= ~QMF_GRAYED;
             //g_arenaservers.gametype.generic.flags &= ~QMF_GRAYED;
             g_arenaservers.sortkey.generic.flags    &= ~QMF_GRAYED;
             //g_arenaservers.showempty.generic.flags&= ~QMF_GRAYED;
             //g_arenaservers.showfull.generic.flags &= ~QMF_GRAYED;
             g_arenaservers.list.generic.flags       &= ~QMF_GRAYED;
             g_arenaservers.refresh.generic.flags    &= ~QMF_GRAYED;
             g_arenaservers.go.generic.flags         &= ~QMF_GRAYED;
             // update status bar
             /*
             if( g_servertype >= UIAS_GLOBAL1 && g_servertype <= UIAS_GLOBAL5 ) {
                 g_arenaservers.statusbar.string = quake3worldMessage;
             }
             else {
                 g_arenaservers.statusbar.string = "";
             }
             */
         }
     }
     else {
         // no servers found
         if( g_arenaservers.refreshservers ) {
             //strcpy( g_arenaservers.status.string,"Scanning For Servers." );
             //g_arenaservers.statusbar.string = "Press SPACE to stop";
             // disable controls during refresh
             g_arenaservers.master.generic.flags     |= QMF_GRAYED;
             //g_arenaservers.gametype.generic.flags |= QMF_GRAYED;
             g_arenaservers.sortkey.generic.flags    |= QMF_GRAYED;
             //g_arenaservers.showempty.generic.flags|= QMF_GRAYED;
             //g_arenaservers.showfull.generic.flags |= QMF_GRAYED;
             g_arenaservers.list.generic.flags       |= QMF_GRAYED;
             g_arenaservers.refresh.generic.flags    |= QMF_GRAYED;
             g_arenaservers.go.generic.flags         |= QMF_GRAYED;
         }
         else {
             if( g_arenaservers.numqueriedservers < 0 ) {
                 //strcpy(g_arenaservers.status.string,"No Response From Master Server." );
             }
             else {
                 //strcpy(g_arenaservers.status.string,"No Servers Found." );
             }
             // update status bar
             if( g_servertype >= UIAS_GLOBAL1 && g_servertype <= UIAS_GLOBAL5 ) {
                 g_arenaservers.statusbar.string = quake3worldMessage;
             }
             else {
                 g_arenaservers.statusbar.string = "";
             }
             // end of refresh - set control state
             g_arenaservers.master.generic.flags     &= ~QMF_GRAYED;
             //g_arenaservers.gametype.generic.flags &= ~QMF_GRAYED;
             g_arenaservers.sortkey.generic.flags    &= ~QMF_GRAYED;
             //g_arenaservers.showempty.generic.flags    &= ~QMF_GRAYED;
             //g_arenaservers.showfull.generic.flags &= ~QMF_GRAYED;
             g_arenaservers.list.generic.flags       |= QMF_GRAYED;
             g_arenaservers.refresh.generic.flags    &= ~QMF_GRAYED;
             g_arenaservers.go.generic.flags         |= QMF_GRAYED;
         }
         // zero out list box
         g_arenaservers.list.numitems = 0;
         g_arenaservers.list.curvalue = 0;
         g_arenaservers.list.top      = 0;
         return;
     }
     // build list box strings - apply culling filters
     servernodeptr = g_arenaservers.serverlist;
     count         = *g_arenaservers.numservers;
     for( i = 0, j = 0; i < count; i++, servernodeptr++ ) {
         tableptr = &g_arenaservers.table[j];
         tableptr->servernode = servernodeptr;
         buff = tableptr->buff;
         // can only cull valid results
         if( !g_emptyservers && !servernodeptr->numclients ) {
             continue;
         }
         if( !g_fullservers && ( servernodeptr->numclients == servernodeptr->maxclients ) ) {
             continue;
         }
         switch( g_gametype ) {
         case GAMES_ALL:
             break;
         case GAMES_STRUGGLE:
             if( servernodeptr->gametype != GT_STRUGGLE ) {
                 continue;
             }
             break;
         }
         if( servernodeptr->pingtime < servernodeptr->minPing ) {
             pingColor = S_COLOR_BLUE;
         }
         else if( servernodeptr->maxPing && servernodeptr->pingtime > servernodeptr->maxPing ) {
             pingColor = S_COLOR_BLUE;
         }
         else if( servernodeptr->pingtime < 200 ) {
             pingColor = S_COLOR_GREEN;
         }
         else if( servernodeptr->pingtime < 400 ) {
             pingColor = S_COLOR_YELLOW;
         }
         else {
             pingColor = S_COLOR_RED;
         }
         Com_sprintf( buff, MAX_LISTBOXWIDTH,"%-39.39s %-15.9s %2d/%2d %s%8d " S_COLOR_YELLOW "",
             servernodeptr->hostname, servernodeptr->mapname, servernodeptr->numclients,
             servernodeptr->maxclients, pingColor, servernodeptr->pingtime);
         j++;
     }
     g_arenaservers.list.numitems = j;
     g_arenaservers.list.curvalue = 0;
     g_arenaservers.list.top      = 0;
 }
References ArenaServers_Compare(), table_t::buff, Com_sprintf(), arenaservers_t::currentping, menulist_s::curvalue, menucommon_s::flags, g_arenaservers, g_emptyservers, g_fullservers, g_gametype, g_servertype, GAMES_ALL, GAMES_STRUGGLE, menulist_s::generic, menutext_s::generic, arenaservers_t::go, GT_STRUGGLE, arenaservers_t::list, arenaservers_t::master, MAX_LISTBOXWIDTH, menulist_s::numitems, arenaservers_t::numqueriedservers, arenaservers_t::numservers, QMF_GRAYED, quake3worldMessage, arenaservers_t::refresh, arenaservers_t::refreshservers, S_COLOR_BLUE, S_COLOR_GREEN, S_COLOR_RED, S_COLOR_YELLOW, arenaservers_t::serverlist, table_t::servernode, arenaservers_t::sortkey, arenaservers_t::statusbar, menutext_s::string, arenaservers_t::table, menulist_s::top, UIAS_GLOBAL1, and UIAS_GLOBAL5.
Referenced by ArenaServers_DoRefresh(), ArenaServers_Event(), ArenaServers_MenuKey(), ArenaServers_SetType(), ArenaServers_StartRefresh(), and ArenaServers_StopRefresh().
strrep()
void strrep (char * str, char old, char new)
Definition at line 1169 of file ui_servers2.c.
{
     char *pos;
     while(1){
         pos = strchr(str, old);
         if (pos == NULL){
             break;
         }
         *pos = new;
     }
 }
References NULL.
Referenced by ArenaServers_MenuDraw().
UI_ArenaServersMenu()
void UI_ArenaServersMenu (void)
Definition at line 1517 of file ui_servers2.c.
{
     //trap_S_StopBackgroundTrack();
     //trap_S_StartBackgroundTrack("music/yamamoto/menu02.ogg", "music/yamamoto/menu02.ogg");
     ArenaServers_MenuInit();
     UI_PushMenu( &g_arenaservers.menu );
 }
References ArenaServers_MenuInit(), g_arenaservers, arenaservers_t::menu, and UI_PushMenu().
Referenced by Main_MenuEvent().
Variable Documentation
g_arenaservers
arenaservers_t g_arenaservers static
Definition at line 203 of file ui_servers2.c.
Referenced by ArenaServers_DoRefresh(), ArenaServers_Event(), ArenaServers_Go(), ArenaServers_Insert(), ArenaServers_InsertFavorites(), ArenaServers_LoadFavorites(), ArenaServers_MenuDraw(), ArenaServers_MenuInit(), ArenaServers_MenuKey(), ArenaServers_Remove(), ArenaServers_SaveChanges(), ArenaServers_SetType(), ArenaServers_Sort(), ArenaServers_StartRefresh(), ArenaServers_StopRefresh(), ArenaServers_UpdateMenu(), and UI_ArenaServersMenu().
g_emptyservers
int g_emptyservers static
Definition at line 215 of file ui_servers2.c.
Referenced by ArenaServers_Event(), ArenaServers_MenuInit(), ArenaServers_StartRefresh(), and ArenaServers_UpdateMenu().
g_favoriteserverlist
servernode_t g_favoriteserverlist[MAX_FAVORITESERVERS] static
Definition at line 210 of file ui_servers2.c.
Referenced by ArenaServers_InsertFavorites(), ArenaServers_LoadFavorites(), ArenaServers_Remove(), and ArenaServers_SetType().
g_fullservers
int g_fullservers static
Definition at line 216 of file ui_servers2.c.
Referenced by ArenaServers_Event(), ArenaServers_MenuInit(), ArenaServers_StartRefresh(), and ArenaServers_UpdateMenu().
g_gametype
int g_gametype static
Definition at line 213 of file ui_servers2.c.
Referenced by ArenaServers_Event(), ArenaServers_MenuInit(), and ArenaServers_UpdateMenu().
g_globalserverlist
servernode_t g_globalserverlist[MAX_GLOBALSERVERS] static
Definition at line 206 of file ui_servers2.c.
Referenced by ArenaServers_SetType().
g_localserverlist
servernode_t g_localserverlist[MAX_LOCALSERVERS] static
Definition at line 208 of file ui_servers2.c.
Referenced by ArenaServers_SetType().
g_numfavoriteservers
int g_numfavoriteservers static
Definition at line 211 of file ui_servers2.c.
Referenced by ArenaServers_InsertFavorites(), ArenaServers_LoadFavorites(), ArenaServers_Remove(), and ArenaServers_SetType().
g_numglobalservers
int g_numglobalservers static
Definition at line 207 of file ui_servers2.c.
Referenced by ArenaServers_SetType().
g_numlocalservers
int g_numlocalservers static
Definition at line 209 of file ui_servers2.c.
Referenced by ArenaServers_SetType().
g_servertype
int g_servertype static
Definition at line 212 of file ui_servers2.c.
Referenced by ArenaServers_DoRefresh(), ArenaServers_Insert(), ArenaServers_MenuInit(), ArenaServers_MenuKey(), ArenaServers_SetType(), ArenaServers_SourceForLAN(), ArenaServers_StartRefresh(), ArenaServers_StopRefresh(), and ArenaServers_UpdateMenu().
g_sortkey
int g_sortkey static
Definition at line 214 of file ui_servers2.c.
Referenced by ArenaServers_Compare(), ArenaServers_MenuInit(), and ArenaServers_Sort().
gamenames
char* gamenames[] static
Initial value:
= {
    "ZEQ2-Lite",
    "???",
    NULL
}
Definition at line 114 of file ui_servers2.c.
Referenced by ArenaServers_Insert().
master_items
const char* master_items[] static
Initial value:
= {
    "Local",
    "Internet",
    NULL
}
Definition at line 93 of file ui_servers2.c.
Referenced by ArenaServers_MenuInit().
netnames
char* netnames[] static
Initial value:
= {
    "??? ",
    "UDP ",
    "UDP6",
    NULL
}
Definition at line 120 of file ui_servers2.c.
Referenced by ArenaServers_Insert().
quake3worldMessage
char quake3worldMessage[] = "" static
Definition at line 127 of file ui_servers2.c.
Referenced by ArenaServers_UpdateMenu().
readPort
qboolean readPort
Definition at line 218 of file ui_servers2.c.
servertype_items
const char* servertype_items[] static
Initial value:
= {
    "Struggle",
    NULL
}
Definition at line 99 of file ui_servers2.c.
sortkey_items
const char* sortkey_items[] static
Initial value:
= {
    "Server Name",
    "Map Name",
    "Open Player Spots",
    "Game Type",
    "Ping Time",
    NULL
}
Definition at line 105 of file ui_servers2.c.
Referenced by ArenaServers_MenuInit().
updateAddress
qboolean updateAddress
Definition at line 217 of file ui_servers2.c.