ZEQ2-Lite: Source/Engine/libspeex/mdf.c File Reference
mdf.c File Reference
#include "arch.h"
#include "speex/speex_echo.h"
#include "fftwrap.h"
#include "pseudofloat.h"
#include "math_approx.h"
#include "os_support.h"
Data Structures
struct SpeexEchoState
Speex echo cancellation state.
Macros
#define PLAYBACK_DELAY 2
#define spectral_mul_accum16 spectral_mul_accum
#define TOP16(x) (x)
#define TWO_PATH
#define WEIGHT_SHIFT 0
Functions
static void filter_dc_notch16 (const spx_int16_t *in, spx_word16_t radius, spx_word16_t *out, int len, spx_mem_t *mem)
static void mdf_adjust_prop (const spx_word32_t *W, int N, int M, spx_word16_t *prop)
static spx_word32_t mdf_inner_prod (const spx_word16_t *x, const spx_word16_t *y, int len)
static void power_spectrum (const spx_word16_t *X, spx_word32_t *ps, int N)
Compute power spectrum of a half-complex (packed) vector.
static void spectral_mul_accum (const spx_word16_t *X, const spx_word32_t *Y, spx_word16_t *acc, int N, int M)
Compute cross-power spectrum of a half-complex (packed) vectors and add to acc.
void speex_echo_cancel (SpeexEchoState *st, const spx_int16_t *in, const spx_int16_t *far_end, spx_int16_t *out, spx_int32_t *Yout)
Performs echo cancellation on a frame (deprecated, last arg now ignored)
void speex_echo_cancellation (SpeexEchoState *st, const spx_int16_t *in, const spx_int16_t *far_end, spx_int16_t *out)
Performs echo cancellation on a frame.
void speex_echo_capture (SpeexEchoState *st, const spx_int16_t *rec, spx_int16_t *out)
Perform echo cancellation using internal playback buffer, which is delayed by two frames to account for the delay introduced by most soundcards (but it could be off!)
int speex_echo_ctl (SpeexEchoState *st, int request, void *ptr)
Used like the ioctl function to control the echo canceller parameters.
void speex_echo_get_residual (SpeexEchoState *st, spx_word32_t *Yout, int len)
void speex_echo_playback (SpeexEchoState *st, const spx_int16_t *play)
Let the echo canceller know that a frame was just queued to the soundcard.
void speex_echo_state_destroy (SpeexEchoState *st)
Destroys an echo canceller state.
SpeexEchoState * speex_echo_state_init (int frame_size, int filter_length)
Creates a new echo canceller state.
void speex_echo_state_reset (SpeexEchoState *st)
Resets echo canceller state.
static void weighted_spectral_mul_conj (const spx_float_t *w, const spx_float_t p, const spx_word16_t *X, const spx_word16_t *Y, spx_word32_t *prod, int N)
Compute weighted cross-power spectrum of a half-complex (packed) vector with conjugate.
Variables
static const spx_float_t MIN_LEAK = .005f
static const spx_float_t VAR1_SMOOTH = .36f
static const spx_float_t VAR1_UPDATE = .5f
static const spx_float_t VAR2_SMOOTH = .7225f
static const spx_float_t VAR2_UPDATE = .25f
static const spx_float_t VAR_BACKTRACK = 4.f
Macro Definition Documentation
PLAYBACK_DELAY
#define PLAYBACK_DELAY 2
Definition at line 120 of file mdf.c.
spectral_mul_accum16
#define spectral_mul_accum16 spectral_mul_accum
Definition at line 313 of file mdf.c.
TOP16
#define TOP16 (x) (x)
Definition at line 116 of file mdf.c.
TWO_PATH
#define TWO_PATH
Definition at line 93 of file mdf.c.
WEIGHT_SHIFT
#define WEIGHT_SHIFT 0
Definition at line 88 of file mdf.c.
Function Documentation
filter_dc_notch16()
static void filter_dc_notch16 (const spx_int16_t * in, spx_word16_t radius, spx_word16_t * out, int len, spx_mem_t * mem) inline static
Definition at line 185 of file mdf.c.
 {
    int i;
    spx_word16_t den2;
 #ifdef FIXED_POINT
    den2 = MULT16_16_Q15(radius,radius) + MULT16_16_Q15(QCONST16(.7,15),MULT16_16_Q15(32767-radius,32767-radius));
 #else
    den2 = radius*radius + .7*(1-radius)*(1-radius);
 #endif
    /*printf ("%d %d %d %d %d %d\n", num[0], num[1], num[2], den[0], den[1], den[2]);*/
    for (i=0;i<len;i++)
    {
       spx_word16_t vin = in[i];
       spx_word32_t vout = mem[0] + SHL32(EXTEND32(vin),15);
 #ifdef FIXED_POINT
       mem[0] = mem[1] + SHL32(SHL32(-EXTEND32(vin),15) + MULT16_32_Q15(radius,vout),1);
 #else
       mem[0] = mem[1] + 2*(-vin + radius*vout);
 #endif
       mem[1] = SHL32(EXTEND32(vin),15) - MULT16_32_Q15(den2,vout);
       out[i] = SATURATE32(PSHR32(MULT16_32_Q15(radius,vout),15),32767);
    }
 }
References EXTEND32, MULT16_16_Q15, MULT16_32_Q15, out, PSHR32, QCONST16, SATURATE32, and SHL32.
Referenced by speex_echo_cancellation().
mdf_adjust_prop()
static void mdf_adjust_prop (const spx_word32_t * W, int N, int M, spx_word16_t * prop) inline static
Definition at line 333 of file mdf.c.
 {
    int i, j;
    spx_word16_t max_sum = 1;
    spx_word32_t prop_sum = 1;
    for (i=0;i<M;i++)
    {
       spx_word32_t tmp = 1;
       for (j=0;j<N;j++)
          tmp += MULT16_16(EXTRACT16(SHR32(W[i*N+j],18)), EXTRACT16(SHR32(W[i*N+j],18)));
 #ifdef FIXED_POINT
       /* Just a security in case an overflow were to occur */
       tmp = MIN32(ABS32(tmp), 536870912);
 #endif
       prop[i] = spx_sqrt(tmp);
       if (prop[i] > max_sum)
          max_sum = prop[i];
    }
    for (i=0;i<M;i++)
    {
       prop[i] += MULT16_16_Q15(QCONST16(.1f,15),max_sum);
       prop_sum += EXTEND32(prop[i]);
    }
    for (i=0;i<M;i++)
    {
       prop[i] = DIV32(MULT16_16(QCONST16(.99f,15), prop[i]),prop_sum);
       /*printf ("%f ", prop[i]);*/
    }
    /*printf ("\n");*/
 }
References ABS32, DIV32, EXTEND32, EXTRACT16, M, MIN32, MULT16_16, MULT16_16_Q15, QCONST16, SHR32, and spx_sqrt.
Referenced by speex_echo_cancellation().
mdf_inner_prod()
static spx_word32_t mdf_inner_prod (const spx_word16_t * x, const spx_word16_t * y, int len) inline static
Definition at line 210 of file mdf.c.
 {
    spx_word32_t sum=0;
    len >>= 1;
    while(len--)
    {
       spx_word32_t part=0;
       part = MAC16_16(part,*x++,*y++);
       part = MAC16_16(part,*x++,*y++);
       /* HINT: If you had a 40-bit accumulator, you could shift only at the end */
       sum = ADD32(sum,SHR32(part,6));
    }
    return sum;
 }
References ADD32, MAC16_16, and SHR32.
Referenced by speex_echo_cancellation().
power_spectrum()
static void power_spectrum (const spx_word16_t * X, spx_word32_t * ps, int N) inline static
Compute power spectrum of a half-complex (packed) vector.
Definition at line 226 of file mdf.c.
 {
    int i, j;
    ps[0]=MULT16_16(X[0],X[0]);
    for (i=1,j=1;i<N-1;i+=2,j++)
    {
       ps[j] =  MULT16_16(X[i],X[i]) + MULT16_16(X[i+1],X[i+1]);
    }
    ps[j]=MULT16_16(X[i],X[i]);
 }
References MULT16_16, and X.
Referenced by speex_echo_cancellation(), and speex_echo_get_residual().
spectral_mul_accum()
static void spectral_mul_accum (const spx_word16_t * X, const spx_word32_t * Y, spx_word16_t * acc, int N, int M) inline static
Compute cross-power spectrum of a half-complex (packed) vectors and add to acc.
Definition at line 295 of file mdf.c.
 {
    int i,j;
    for (i=0;i<N;i++)
       acc[i] = 0;
    for (j=0;j<M;j++)
    {
       acc[0] += X[0]*Y[0];
       for (i=1;i<N-1;i+=2)
       {
          acc[i] += (X[i]*Y[i] - X[i+1]*Y[i+1]);
          acc[i+1] += (X[i+1]*Y[i] + X[i]*Y[i+1]);
       }
       acc[i] += X[i]*Y[i];
       X += N;
       Y += N;
    }
 }
References M, and X.
Referenced by speex_echo_cancellation().
speex_echo_get_residual()
void speex_echo_get_residual (SpeexEchoState * st, spx_word32_t * Yout, int len)
Definition at line 1111 of file mdf.c.
 {
    int i;
    spx_word16_t leak2;
    int N;
    N = st->window_size;
    /* Apply hanning window (should pre-compute it)*/
    for (i=0;i<N;i++)
       st->y[i] = MULT16_16_Q15(st->window[i],st->last_y[i]);
    /* Compute power spectrum of the echo */
    spx_fft(st->fft_table, st->y, st->Y);
    power_spectrum(st->Y, residual_echo, N);
 #ifdef FIXED_POINT
    if (st->leak_estimate > 16383)
       leak2 = 32767;
    else
       leak2 = SHL16(st->leak_estimate, 1);
 #else
    if (st->leak_estimate>.5)
       leak2 = 1;
    else
       leak2 = 2*st->leak_estimate;
 #endif
    /* Estimate residual echo */
    for (i=0;i<=st->frame_size;i++)
       residual_echo[i] = (spx_int32_t)MULT16_32_Q15(leak2,residual_echo[i]);
 }
References MULT16_16_Q15, MULT16_32_Q15, power_spectrum(), SHL16, and spx_fft().
Referenced by speex_preprocess_run().
weighted_spectral_mul_conj()
static void weighted_spectral_mul_conj (const spx_float_t * w, const spx_float_t p, const spx_word16_t * X, const spx_word16_t * Y, spx_word32_t * prod, int N) inline static
Compute weighted cross-power spectrum of a half-complex (packed) vector with conjugate.
Definition at line 317 of file mdf.c.
 {
    int i, j;
    spx_float_t W;
    W = FLOAT_AMULT(p, w[0]);
    prod[0] = FLOAT_MUL32(W,MULT16_16(X[0],Y[0]));
    for (i=1,j=1;i<N-1;i+=2,j++)
    {
       W = FLOAT_AMULT(p, w[j]);
       prod[i] = FLOAT_MUL32(W,MAC16_16(MULT16_16(X[i],Y[i]), X[i+1],Y[i+1]));
       prod[i+1] = FLOAT_MUL32(W,MAC16_16(MULT16_16(-X[i+1],Y[i]), X[i],Y[i+1]));
    }
    W = FLOAT_AMULT(p, w[j]);
    prod[i] = FLOAT_MUL32(W,MULT16_16(X[i],Y[i]));
 }
References FLOAT_AMULT, FLOAT_MUL32, MAC16_16, MULT16_16, spx_float_t, and X.
Referenced by speex_echo_cancellation().
Variable Documentation
MIN_LEAK
const spx_float_t MIN_LEAK = .005f static
Definition at line 108 of file mdf.c.
Referenced by speex_echo_cancellation().
VAR1_SMOOTH
const spx_float_t VAR1_SMOOTH = .36f static
Definition at line 111 of file mdf.c.
Referenced by speex_echo_cancellation().
VAR1_UPDATE
const spx_float_t VAR1_UPDATE = .5f static
Definition at line 113 of file mdf.c.
Referenced by speex_echo_cancellation().
VAR2_SMOOTH
const spx_float_t VAR2_SMOOTH = .7225f static
Definition at line 112 of file mdf.c.
Referenced by speex_echo_cancellation().
VAR2_UPDATE
const spx_float_t VAR2_UPDATE = .25f static
Definition at line 114 of file mdf.c.
Referenced by speex_echo_cancellation().
VAR_BACKTRACK
const spx_float_t VAR_BACKTRACK = 4.f static
Definition at line 115 of file mdf.c.
Referenced by speex_echo_cancellation().