ZEQ2-Lite: __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator > Class Template Reference
__gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator > Class Template Reference
#include <node_iterators.hpp>
Public Types
typedef e_access_traits::const_iterator const_e_iterator
typedef Allocator::template rebind< metadata_type >::other::const_reference const_metadata_reference
typedef value_type const_reference
typedef trivial_iterator_difference_type difference_type
typedef E_Access_Traits e_access_traits
typedef trivial_iterator_tag iterator_category
typedef Node::metadata_type metadata_type
typedef value_type reference
typedef Allocator::size_type size_type
typedef Const_Iterator value_type
Public Member Functions
pat_trie_const_node_it_ (node_pointer p_nd=0, const_e_access_traits_pointer p_traits=0)
PB_DS_PAT_TRIE_CONST_NODE_ITERATOR_C_DEC get_child (size_type i) const
const_metadata_reference get_metadata () const
size_type num_children () const
bool operator!= (const PB_DS_PAT_TRIE_CONST_NODE_ITERATOR_C_DEC &other) const
const_reference operator* () const
bool operator== (const PB_DS_PAT_TRIE_CONST_NODE_ITERATOR_C_DEC &other) const
std::pair< const_e_iterator, const_e_iterator > valid_prefix () const
Data Fields
node_pointer m_p_nd
const_e_access_traits_pointer m_p_traits
Protected Types
typedef Allocator::template rebind< E_Access_Traits >::other::const_pointer const_e_access_traits_pointer
typedef Allocator::template rebind< Internal_Node >::other::const_pointer const_internal_node_pointer
typedef Allocator::template rebind< Leaf >::other::const_pointer const_leaf_pointer
typedef Allocator::template rebind< Internal_Node >::other::pointer internal_node_pointer
typedef Allocator::template rebind< Leaf >::other::pointer leaf_pointer
typedef Allocator::template rebind< Node >::other::pointer node_pointer
Private Member Functions
E_Access_Traits::const_iterator pref_begin () const
E_Access_Traits::const_iterator pref_end () const
Friends
class PB_DS_CLASS_C_DEC
Detailed Description
template<typename Node, class Leaf, class Head, class Internal_Node, class Const_Iterator, class Iterator, class E_Access_Traits, class Allocator>
class __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >
Definition at line 82 of file node_iterators.hpp.
Member Typedef Documentation
const_e_access_traits_pointer
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Allocator::template rebind< E_Access_Traits>::other::const_pointer __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::const_e_access_traits_pointer protected
Definition at line 113 of file node_iterators.hpp.
const_e_iterator
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef e_access_traits::const_iterator __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::const_e_iterator
Definition at line 166 of file node_iterators.hpp.
const_internal_node_pointer
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Allocator::template rebind< Internal_Node>::other::const_pointer __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::const_internal_node_pointer protected
Definition at line 108 of file node_iterators.hpp.
const_leaf_pointer
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Allocator::template rebind< Leaf>::other::const_pointer __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::const_leaf_pointer protected
Definition at line 93 of file node_iterators.hpp.
const_metadata_reference
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Allocator::template rebind< metadata_type>::other::const_reference __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::const_metadata_reference
Definition at line 175 of file node_iterators.hpp.
const_reference
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef value_type __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::const_reference
Definition at line 160 of file node_iterators.hpp.
difference_type
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef trivial_iterator_difference_type __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::difference_type
Definition at line 151 of file node_iterators.hpp.
e_access_traits
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef E_Access_Traits __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::e_access_traits
Definition at line 163 of file node_iterators.hpp.
internal_node_pointer
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Allocator::template rebind< Internal_Node>::other::pointer __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::internal_node_pointer protected
Definition at line 103 of file node_iterators.hpp.
iterator_category
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef trivial_iterator_tag __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::iterator_category
Definition at line 148 of file node_iterators.hpp.
leaf_pointer
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Allocator::template rebind< Leaf>::other::pointer __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::leaf_pointer protected
Definition at line 98 of file node_iterators.hpp.
metadata_type
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Node::metadata_type __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::metadata_type
Definition at line 169 of file node_iterators.hpp.
node_pointer
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Allocator::template rebind< Node>::other::pointer __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::node_pointer protected
Definition at line 88 of file node_iterators.hpp.
reference
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef value_type __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::reference
Definition at line 157 of file node_iterators.hpp.
size_type
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Allocator::size_type __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::size_type
Definition at line 145 of file node_iterators.hpp.
value_type
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > typedef Const_Iterator __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::value_type
Definition at line 154 of file node_iterators.hpp.
Constructor & Destructor Documentation
pat_trie_const_node_it_()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pat_trie_const_node_it_ (node_pointer p_nd = 0, const_e_access_traits_pointer p_traits = 0) inline
Definition at line 183 of file node_iterators.hpp.
       : m_p_nd(const_cast<node_pointer>(p_nd)), m_p_traits(p_traits)
       { }
Member Function Documentation
get_child()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > PB_DS_PAT_TRIE_CONST_NODE_ITERATOR_C_DEC __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::get_child (size_type i) const inline
Definition at line 220 of file node_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(m_p_nd->m_type == pat_trie_internal_node_type);
     typename Internal_Node::iterator it =
       static_cast<internal_node_pointer>(m_p_nd)->begin();
     std::advance(it, i);
     return PB_DS_PAT_TRIE_CONST_NODE_ITERATOR_C_DEC(*it, m_p_traits);
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd, __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_traits, __gnu_pbds::detail::pat_trie_internal_node_type, and PB_DS_PAT_TRIE_CONST_NODE_ITERATOR_C_DEC.
get_metadata()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > const_metadata_reference __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::get_metadata () const inline
Definition at line 204 of file node_iterators.hpp.
       { return m_p_nd->get_metadata(); }
References __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd.
num_children()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > size_type __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::num_children () const inline
Definition at line 209 of file node_iterators.hpp.
       {
     if (m_p_nd->m_type == pat_trie_leaf_node_type)
       return 0;
     _GLIBCXX_DEBUG_ASSERT(m_p_nd->m_type == pat_trie_internal_node_type);
     return std::distance(static_cast<internal_node_pointer>(m_p_nd)->begin(),  static_cast<internal_node_pointer>(m_p_nd)->end());
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd, __gnu_pbds::detail::pat_trie_internal_node_type, and __gnu_pbds::detail::pat_trie_leaf_node_type.
Referenced by __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::operator*().
operator!=()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > bool __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::operator!= (const PB_DS_PAT_TRIE_CONST_NODE_ITERATOR_C_DEC & other) const inline
Definition at line 237 of file node_iterators.hpp.
       { return m_p_nd != other.m_p_nd; }
References __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd.
operator*()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > const_reference __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::operator* () const inline
Definition at line 196 of file node_iterators.hpp.
       {
     _GLIBCXX_DEBUG_ASSERT(num_children() == 0);
     return Const_Iterator(m_p_nd);
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd, and __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::num_children().
operator==()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > bool __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::operator== (const PB_DS_PAT_TRIE_CONST_NODE_ITERATOR_C_DEC & other) const inline
Definition at line 232 of file node_iterators.hpp.
       { return (m_p_nd == other.m_p_nd); }
References __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd.
pref_begin()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > E_Access_Traits::const_iterator __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pref_begin () const inline private
Definition at line 117 of file node_iterators.hpp.
       {
     if (m_p_nd->m_type == pat_trie_leaf_node_type)
       return (m_p_traits->begin(
                     m_p_traits->extract_key(
                                 static_cast<const_leaf_pointer>(m_p_nd)->value())));
     _GLIBCXX_DEBUG_ASSERT(m_p_nd->m_type == pat_trie_internal_node_type);
     return (static_cast<const_internal_node_pointer>(m_p_nd)->pref_b_it());
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd, __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_traits, __gnu_pbds::detail::pat_trie_internal_node_type, and __gnu_pbds::detail::pat_trie_leaf_node_type.
Referenced by __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::valid_prefix().
pref_end()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > E_Access_Traits::const_iterator __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pref_end () const inline private
Definition at line 130 of file node_iterators.hpp.
       {
     if (m_p_nd->m_type == pat_trie_leaf_node_type)
       return (m_p_traits->end(
                   m_p_traits->extract_key(
                               static_cast<const_leaf_pointer>(m_p_nd)->value())));
     _GLIBCXX_DEBUG_ASSERT(m_p_nd->m_type == pat_trie_internal_node_type);
     return (static_cast<const_internal_node_pointer>(m_p_nd)->pref_e_it());
       }
References _GLIBCXX_DEBUG_ASSERT, __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd, __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_traits, __gnu_pbds::detail::pat_trie_internal_node_type, and __gnu_pbds::detail::pat_trie_leaf_node_type.
Referenced by __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::valid_prefix().
valid_prefix()
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > std::pair<const_e_iterator, const_e_iterator> __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::valid_prefix () const inline
Definition at line 190 of file node_iterators.hpp.
       { return std::make_pair(pref_begin(), pref_end()); }
References __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pref_begin(), and __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pref_end().
Friends And Related Function Documentation
PB_DS_CLASS_C_DEC
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > friend class PB_DS_CLASS_C_DEC friend
Definition at line 242 of file node_iterators.hpp.
Field Documentation
m_p_nd
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > node_pointer __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_nd
Definition at line 245 of file node_iterators.hpp.
Referenced by __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::get_child(), __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::get_metadata(), __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::num_children(), __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::operator!=(), __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::operator*(), __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::operator==(), __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pref_begin(), and __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pref_end().
m_p_traits
template<typename Node , class Leaf , class Head , class Internal_Node , class Const_Iterator , class Iterator , class E_Access_Traits , class Allocator > const_e_access_traits_pointer __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::m_p_traits
Definition at line 247 of file node_iterators.hpp.
Referenced by __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::get_child(), __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pref_begin(), and __gnu_pbds::detail::pat_trie_const_node_it_< Node, Leaf, Head, Internal_Node, Const_Iterator, Iterator, E_Access_Traits, Allocator >::pref_end().
The documentation for this class was generated from the following file:
Tools/MinGW/include/c++/4.6.1/ext/pb_ds/detail/pat_trie_/node_iterators.hpp