ZEQ2-Lite: Source/Engine/SDL12/include/SDL_cpuinfo.h File Reference
SDL_cpuinfo.h File Reference
#include "SDL_stdinc.h"
#include "begin_code.h"
#include "close_code.h"
Functions
DECLSPEC SDL_bool SDLCALL SDL_Has3DNow (void)
This function returns true if the CPU has 3DNow features.
DECLSPEC SDL_bool SDLCALL SDL_Has3DNowExt (void)
This function returns true if the CPU has 3DNow! Ext.
DECLSPEC SDL_bool SDLCALL SDL_HasAltiVec (void)
This function returns true if the CPU has AltiVec features.
DECLSPEC SDL_bool SDLCALL SDL_HasMMX (void)
This function returns true if the CPU has MMX features.
DECLSPEC SDL_bool SDLCALL SDL_HasMMXExt (void)
This function returns true if the CPU has MMX Ext.
DECLSPEC SDL_bool SDLCALL SDL_HasRDTSC (void)
This function returns true if the CPU has the RDTSC instruction.
DECLSPEC SDL_bool SDLCALL SDL_HasSSE (void)
This function returns true if the CPU has SSE features.
DECLSPEC SDL_bool SDLCALL SDL_HasSSE2 (void)
This function returns true if the CPU has SSE2 features.
Detailed Description
CPU feature detection for SDL
Definition in file SDL_cpuinfo.h.
Function Documentation
SDL_Has3DNow()
DECLSPEC SDL_bool SDLCALL SDL_Has3DNow (void)
This function returns true if the CPU has 3DNow features.
Referenced by Sys_GetProcessorFeatures().
SDL_Has3DNowExt()
DECLSPEC SDL_bool SDLCALL SDL_Has3DNowExt (void)
This function returns true if the CPU has 3DNow! Ext.
features
Referenced by Sys_GetProcessorFeatures().
SDL_HasAltiVec()
DECLSPEC SDL_bool SDLCALL SDL_HasAltiVec (void)
This function returns true if the CPU has AltiVec features.
Referenced by Sys_GetProcessorFeatures().
SDL_HasMMX()
DECLSPEC SDL_bool SDLCALL SDL_HasMMX (void)
This function returns true if the CPU has MMX features.
Referenced by Sys_GetProcessorFeatures().
SDL_HasMMXExt()
DECLSPEC SDL_bool SDLCALL SDL_HasMMXExt (void)
This function returns true if the CPU has MMX Ext.
features
Referenced by Sys_GetProcessorFeatures().
SDL_HasRDTSC()
DECLSPEC SDL_bool SDLCALL SDL_HasRDTSC (void)
This function returns true if the CPU has the RDTSC instruction.
Referenced by Sys_GetProcessorFeatures().
SDL_HasSSE()
DECLSPEC SDL_bool SDLCALL SDL_HasSSE (void)
This function returns true if the CPU has SSE features.
Referenced by Sys_GetProcessorFeatures().
SDL_HasSSE2()
DECLSPEC SDL_bool SDLCALL SDL_HasSSE2 (void)
This function returns true if the CPU has SSE2 features.
Referenced by Sys_GetProcessorFeatures().