ZEQ2-Lite: Source/Engine/client/snd_public.h File Reference
snd_public.h File Reference
Functions
void S_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void S_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void S_BeginRegistration (void)
void S_ClearLoopingSounds (qboolean killall)
void S_ClearSoundBuffer (void)
void S_DisableSounds (void)
void S_DisplayFreeMemory (void)
void S_Init (void)
void S_RawSamples (int stream, int samples, int rate, int width, int channels, const byte *data, float volume, int entityNum)
sfxHandle_t S_RegisterSound (const char *sample, qboolean compressed)
void S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater, float attenuation)
void S_Shutdown (void)
void S_StartBackgroundTrack (const char *intro, const char *loop)
void S_StartLocalSound (sfxHandle_t sfx, int channelNum)
void S_StartSound (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx)
void S_StopAllSounds (void)
void S_StopBackgroundTrack (void)
void S_StopLoopingSound (int entityNum)
void S_Update (void)
void S_UpdateBackgroundTrack (void)
void S_UpdateEntityPosition (int entityNum, const vec3_t origin)
void SNDDMA_Activate (void)
Function Documentation
S_AddLoopingSound()
void S_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
Definition at line 167 of file snd_main.c.
 {
     if( si.AddLoopingSound ) {
         si.AddLoopingSound( entityNum, origin, velocity, sfx );
     }
 }
References soundInterface_t::AddLoopingSound, and si.
Referenced by CL_CgameSystemCalls().
S_AddRealLoopingSound()
void S_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
Definition at line 180 of file snd_main.c.
 {
     if( si.AddRealLoopingSound ) {
         si.AddRealLoopingSound( entityNum, origin, velocity, sfx );
     }
 }
References soundInterface_t::AddRealLoopingSound, and si.
Referenced by CL_CgameSystemCalls().
S_BeginRegistration()
void S_BeginRegistration (void)
Definition at line 273 of file snd_main.c.
 {
     if( si.BeginRegistration ) {
         si.BeginRegistration( );
     }
 }
References soundInterface_t::BeginRegistration, and si.
Referenced by CL_StartHunkUsers().
S_ClearLoopingSounds()
void S_ClearLoopingSounds (qboolean killall)
Definition at line 155 of file snd_main.c.
 {
     if( si.ClearLoopingSounds ) {
         si.ClearLoopingSounds( killall );
     }
 }
References soundInterface_t::ClearLoopingSounds, and si.
Referenced by CL_CgameSystemCalls().
S_ClearSoundBuffer()
void S_ClearSoundBuffer (void)
Definition at line 299 of file snd_main.c.
 {
     if( si.ClearSoundBuffer ) {
         si.ClearSoundBuffer( );
     }
 }
S_DisableSounds()
void S_DisableSounds (void)
Definition at line 261 of file snd_main.c.
 {
     if( si.DisableSounds ) {
         si.DisableSounds( );
     }
 }
References soundInterface_t::DisableSounds, and si.
Referenced by CL_ShutdownAll().
S_DisplayFreeMemory()
void S_DisplayFreeMemory (void)
Definition at line 265 of file snd_mem.c.
{
     Com_Printf("%d bytes free sound buffer memory, %d total used\n", inUse, totalInUse);
 }
References Com_Printf(), inUse, and totalInUse.
Referenced by S_Base_SoundList().
S_Init()
void S_Init (void)
Definition at line 468 of file snd_main.c.
 {
     cvar_t      *cv;
     qboolean    started = qfalse;
     Com_Printf( "------ Initializing Sound ------\n" );
     s_volume = Cvar_Get( "s_volume", "0.8", CVAR_ARCHIVE );
     s_musicVolume = Cvar_Get( "s_musicvolume", "0.25", CVAR_ARCHIVE );
     s_muted = Cvar_Get("s_muted", "0", CVAR_ROM);
     s_doppler = Cvar_Get( "s_doppler", "1", CVAR_ARCHIVE );
     s_backend = Cvar_Get( "s_backend", "", CVAR_ROM );
     s_muteWhenMinimized = Cvar_Get( "s_muteWhenMinimized", "0", CVAR_ARCHIVE );
     s_muteWhenUnfocused = Cvar_Get( "s_muteWhenUnfocused", "0", CVAR_ARCHIVE );
     cv = Cvar_Get( "s_initsound", "1", 0 );
     if( !cv->integer ) {
         Com_Printf( "Sound disabled.\n" );
     } else {
         S_CodecInit( );
         Cmd_AddCommand( "play", S_Play_f );
         Cmd_AddCommand( "music", S_Music_f );
         Cmd_AddCommand( "stopmusic", S_StopMusic_f );
         Cmd_AddCommand( "s_list", S_SoundList );
         Cmd_AddCommand( "s_stop", S_StopAllSounds );
         Cmd_AddCommand( "s_info", S_SoundInfo );
         cv = Cvar_Get( "s_useOpenAL", "1", CVAR_ARCHIVE );
         if( cv->integer ) {
             //OpenAL
             started = S_AL_Init( &si );
             Cvar_Set( "s_backend", "OpenAL" );
         }
         if( !started ) {
             started = S_Base_Init( &si );
             Cvar_Set( "s_backend", "base" );
         }
         if( started ) {
             if( !S_ValidSoundInterface( &si ) ) {
                 Com_Error( ERR_FATAL, "Sound interface invalid" );
             }
             S_SoundInfo( );
             Com_Printf( "Sound initialization successful.\n" );
         } else {
             Com_Printf( "Sound initialization failed.\n" );
         }
     }
     Com_Printf( "--------------------------------\n");
 }
References Cmd_AddCommand(), Com_Error(), Com_Printf(), CVAR_ARCHIVE, Cvar_Get(), CVAR_ROM, Cvar_Set(), ERR_FATAL, qfalse, S_AL_Init(), s_backend, S_Base_Init(), S_CodecInit(), s_doppler, S_Music_f(), s_musicVolume, s_muted, s_muteWhenMinimized, s_muteWhenUnfocused, S_Play_f(), S_SoundInfo(), S_SoundList(), S_StopAllSounds(), S_StopMusic_f(), S_ValidSoundInterface(), s_volume, si, and started.
Referenced by CL_StartHunkUsers().
S_RawSamples()
void S_RawSamples (int stream, int samples, int rate, int width, int channels, const byte * data, float volume, int entityNum)
Definition at line 131 of file snd_main.c.
 {
     if(si.RawSamples)
         si.RawSamples(stream, samples, rate, width, channels, data, volume, entityNum);
 }
References soundInterface_t::RawSamples, si, and volume.
Referenced by RoQInterrupt().
S_RegisterSound()
sfxHandle_t S_RegisterSound (const char * sample, qboolean compressed)
Definition at line 285 of file snd_main.c.
 {
     if( si.RegisterSound ) {
         return si.RegisterSound( sample, compressed );
     } else {
         return 0;
     }
 }
References soundInterface_t::RegisterSound, and si.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
S_Respatialize()
void S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater, float attenuation)
Definition at line 205 of file snd_main.c.
 {
     if( si.Respatialize ) {
         si.Respatialize( entityNum, origin, axis, inwater, attenuation );
     }
 }
References attenuation, soundInterface_t::Respatialize, and si.
Referenced by CL_CgameSystemCalls().
S_Shutdown()
void S_Shutdown (void)
Definition at line 529 of file snd_main.c.
 {
     if( si.Shutdown ) {
         si.Shutdown( );
     }
     Com_Memset( &si, 0, sizeof( soundInterface_t ) );
     Cmd_RemoveCommand( "play" );
     Cmd_RemoveCommand( "music");
     Cmd_RemoveCommand( "stopmusic");
     Cmd_RemoveCommand( "s_list" );
     Cmd_RemoveCommand( "s_stop" );
     Cmd_RemoveCommand( "s_info" );
     S_CodecShutdown( );
 }
References Cmd_RemoveCommand(), Com_Memset, S_CodecShutdown(), soundInterface_t::Shutdown, and si.
Referenced by CL_Snd_Shutdown().
S_StartBackgroundTrack()
void S_StartBackgroundTrack (const char * intro, const char * loop)
Definition at line 107 of file snd_main.c.
 {
     if( si.StartBackgroundTrack ) {
         si.StartBackgroundTrack( intro, loop );
     }
 }
References si, and soundInterface_t::StartBackgroundTrack.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
S_StartLocalSound()
void S_StartLocalSound (sfxHandle_t sfx, int channelNum)
Definition at line 95 of file snd_main.c.
 {
     if( si.StartLocalSound ) {
         si.StartLocalSound( sfx, channelNum );
     }
 }
References si, and soundInterface_t::StartLocalSound.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
S_StartSound()
void S_StartSound (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx)
Definition at line 83 of file snd_main.c.
 {
     if( si.StartSound ) {
         si.StartSound( origin, entnum, entchannel, sfx );
     }
 }
References si, and soundInterface_t::StartSound.
Referenced by CL_CgameSystemCalls().
S_StopAllSounds()
void S_StopAllSounds (void)
Definition at line 143 of file snd_main.c.
 {
     if( si.StopAllSounds ) {
         si.StopAllSounds( );
     }
 }
References si, and soundInterface_t::StopAllSounds.
Referenced by CL_Frame(), CL_KeyDownEvent(), CL_PlayCinematic_f(), CL_Vid_Restart_f(), S_Init(), SCR_DrawScreenField(), and SCR_StopCinematic().
S_StopBackgroundTrack()
void S_StopBackgroundTrack (void)
Definition at line 119 of file snd_main.c.
 {
     if( si.StopBackgroundTrack ) {
         si.StopBackgroundTrack( );
     }
 }
References si, and soundInterface_t::StopBackgroundTrack.
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
S_StopLoopingSound()
void S_StopLoopingSound (int entityNum)
Definition at line 193 of file snd_main.c.
 {
     if( si.StopLoopingSound ) {
         si.StopLoopingSound( entityNum );
     }
 }
References si, and soundInterface_t::StopLoopingSound.
Referenced by CL_CgameSystemCalls().
S_Update()
void S_Update (void)
Definition at line 230 of file snd_main.c.
 {
     if(s_muted->integer)
     {
         if(!(s_muteWhenMinimized->integer && com_minimized->integer) &&
            !(s_muteWhenUnfocused->integer && com_unfocused->integer))
         {
             s_muted->integer = qfalse;
             s_muted->modified = qtrue;
         }
     }
     else
     {
         if((s_muteWhenMinimized->integer && com_minimized->integer) ||
            (s_muteWhenUnfocused->integer && com_unfocused->integer))
         {
             s_muted->integer = qtrue;
             s_muted->modified = qtrue;
         }
     }
     if( si.Update ) {
         si.Update( );
     }
 }
References com_minimized, com_unfocused, qfalse, qtrue, s_muted, s_muteWhenMinimized, s_muteWhenUnfocused, si, and soundInterface_t::Update.
Referenced by CL_Frame(), and RoQInterrupt().
S_UpdateBackgroundTrack()
void S_UpdateBackgroundTrack (void)
Definition at line 1354 of file snd_dma.c.
{
     int     bufferSamples;
     int     fileSamples;
     byte    raw[30000];     // just enough to fit in a mac stack frame
     int     fileBytes;
     int     r;
     if(!s_backgroundStream) {
         return;
     }
     // don't bother playing anything if musicvolume is 0
     if ( s_musicVolume->value <= 0 ) {
         return;
     }
     // see how many samples should be copied into the raw buffer
     if ( s_rawend[0] < s_soundtime ) {
         s_rawend[0] = s_soundtime;
     }
     while ( s_rawend[0] < s_soundtime + MAX_RAW_SAMPLES ) {
         bufferSamples = MAX_RAW_SAMPLES - (s_rawend[0] - s_soundtime);
         // decide how much data needs to be read from the file
         fileSamples = bufferSamples * s_backgroundStream->info.rate / dma.speed;
         if (!fileSamples)
             return;
         // our max buffer size
         fileBytes = fileSamples * (s_backgroundStream->info.width * s_backgroundStream->info.channels);
         if ( fileBytes > sizeof(raw) ) {
             fileBytes = sizeof(raw);
             fileSamples = fileBytes / (s_backgroundStream->info.width * s_backgroundStream->info.channels);
         }
         // Read
         r = S_CodecReadStream(s_backgroundStream, fileBytes, raw);
         if(r < fileBytes)
         {
             fileBytes = r;
             fileSamples = r / (s_backgroundStream->info.width * s_backgroundStream->info.channels);
         }
         if(r > 0)
         {
             // add to raw buffer
             S_Base_RawSamples(0, fileSamples, s_backgroundStream->info.rate,
                 s_backgroundStream->info.width, s_backgroundStream->info.channels, raw, s_musicVolume->value, -1);
         }
         else
         {
             // loop
             if(s_backgroundLoop[0])
             {
                 S_CodecCloseStream(s_backgroundStream);
                 s_backgroundStream = NULL;
                 S_Base_StartBackgroundTrack( s_backgroundLoop, s_backgroundLoop );
                 if(!s_backgroundStream)
                     return;
             }
             else
             {
                 S_Base_StopBackgroundTrack();
                 return;
             }
         }
     }
 }
References dma, MAX_RAW_SAMPLES, NULL, s_backgroundLoop, s_backgroundStream, S_Base_RawSamples(), S_Base_StartBackgroundTrack(), S_Base_StopBackgroundTrack(), S_CodecCloseStream(), S_CodecReadStream(), s_musicVolume, s_rawend, s_soundtime, and dma_t::speed.
Referenced by S_Base_Update().
S_UpdateEntityPosition()
void S_UpdateEntityPosition (int entityNum, const vec3_t origin)
Definition at line 218 of file snd_main.c.
 {
     if( si.UpdateEntityPosition ) {
         si.UpdateEntityPosition( entityNum, origin );
     }
 }
References si, and soundInterface_t::UpdateEntityPosition.
Referenced by CL_CgameSystemCalls().
SNDDMA_Activate()
void SNDDMA_Activate (void)