ZEQ2-Lite: Source/Engine/tools/lcc/src/trace.c File Reference
trace.c File Reference
#include "c.h"
Functions
static void appendstr (char *str)
void trace_init (int argc, char *argv[])
static void tracecall (Symbol printer, Symbol f)
static void tracefinis (Symbol printer)
static void tracereturn (Symbol printer, Symbol f, Tree e)
static void tracevalue (Tree e, int lev)
Variables
static Tree args
static char * fmt
static char * fmtend
static char * fp
static Symbol frameno
Function Documentation
appendstr()
static void appendstr (char * str) static
Definition at line 9 of file trace.c.
{
     do
         if (fp == fmtend) {
             if (fp) {
                 char *s = allocate(2*(fmtend - fmt), FUNC);
                 strncpy(s, fmt, fmtend - fmt);
                 fp = s + (fmtend - fmt);
                 fmtend = s + 2*(fmtend - fmt);
                 fmt = s;
             } else {
                 fp = fmt = allocate(80, FUNC);
                 fmtend = fmt + 80;
             }
         }
     while ((*fp++ = *str++) != 0);
     fp--;
 }
References allocate(), fmt, fmtend, fp, and FUNC.
Referenced by tracecall(), tracereturn(), and tracevalue().
trace_init()
void trace_init (int argc, char * argv[])
Definition at line 162 of file trace.c.
{
     int i;
     static int inited;
     if (inited)
         return;
     inited = 1;
     type_init(argc, argv);
     if (IR)
         for (i = 1; i < argc; i++)
             if (strncmp(argv[i], "-t", 2) == 0 &&  strchr(argv[i], '=') == NULL) {
                 Symbol printer = mksymbol(EXTERN,
                     argv[i][2] ? &argv[i][2] : "printf",
                 ftype(inttype, ptr(qual(CONST, chartype))));
                 printer->defined = 0;
                 attach((Apply)tracecall,   printer, &events.entry);
                 attach((Apply)tracereturn, printer, &events.returns);
                 break;
             }
 }
References attach(), chartype, Events::entry, events, EXTERN, ftype(), inttype, IR, mksymbol(), NULL, ptr(), qual(), Events::returns, tracecall(), tracereturn(), and type_init().
Referenced by init().
tracecall()
static void tracecall (Symbol printer, Symbol f) static
Definition at line 125 of file trace.c.
{
     int i;
     Symbol counter = genident(STATIC, inttype, GLOBAL);
     defglobal(counter, BSS);
     (*IR->space)(counter->type->size);
     frameno = genident(AUTO, inttype, level);
     addlocal(frameno);
     appendstr(f->name); appendstr("#");
     tracevalue(asgn(frameno, incr(INCR, idtree(counter), consttree(1, inttype))), 0);
     appendstr("(");
     for (i = 0; f->u.f.callee[i]; i++) {
         if (i)
             appendstr(",");
         appendstr(f->u.f.callee[i]->name); appendstr("=");
         tracevalue(idtree(f->u.f.callee[i]), 0);
     }
     if (variadic(f->type))
         appendstr(",...");
     appendstr(") called\n");
     tracefinis(printer);
 }
References addlocal(), appendstr(), asgn(), BSS, consttree(), defglobal(), frameno, genident(), GLOBAL, idtree(), incr(), inttype, IR, tracefinis(), tracevalue(), and variadic().
Referenced by trace_init().
tracefinis()
static void tracefinis (Symbol printer) static
Definition at line 110 of file trace.c.
{
     Tree *ap;
     Symbol p;
     *fp = 0;
     p = mkstr(string(fmt));
     for (ap = &args; *ap; ap = &(*ap)->kids[1])
         ;
     *ap = tree(ARG+P, charptype, pointer(idtree(p->u.c.loc)), 0);
     walk(calltree(pointer(idtree(printer)), freturn(printer->type), args, NULL), 0, 0);
     args = 0;
     fp = fmtend = 0;
 }
References args, calltree(), charptype, fmt, fmtend, fp, freturn(), idtree(), mkstr(), NULL, P, tree(), and walk().
Referenced by tracecall(), and tracereturn().
tracereturn()
static void tracereturn (Symbol printer, Symbol f, Tree e) static
Definition at line 149 of file trace.c.
{
     appendstr(f->name); appendstr("#");
     tracevalue(idtree(frameno), 0);
     appendstr(" returned");
     if (freturn(f->type) != voidtype && e) {
         appendstr(" ");
         tracevalue(e, 0);
     }
     appendstr("\n");
     tracefinis(printer);
 }
References appendstr(), frameno, freturn(), idtree(), tracefinis(), tracevalue(), and voidtype.
Referenced by trace_init().
tracevalue()
static void tracevalue (Tree e, int lev) static
Definition at line 28 of file trace.c.
{
     Type ty = unqual(e->type);
     switch (ty->op) {
     case INT:
         if (ty == chartype || ty == signedchar)
             appendstr("'\\x%02x'");
         else if (ty == longtype)
             appendstr("0x%ld");
         else
             appendstr("0x%d");
         break;
     case UNSIGNED:
         if (ty == chartype || ty == unsignedchar)
             appendstr("'\\x%02x'");
         else if (ty == unsignedlong)
             appendstr("0x%lx");
         else
             appendstr("0x%x");
         break;
     case FLOAT:
         if (ty == longdouble)
             appendstr("%Lg");
         else
             appendstr("%g");
         break;
     case POINTER:
         if (unqual(ty->type) == chartype
         ||  unqual(ty->type) == signedchar
         ||  unqual(ty->type) == unsignedchar) {
             static Symbol null;
             if (null == NULL)
                 null = mkstr("(null)");
             tracevalue(cast(e, unsignedtype), lev + 1);
             appendstr(" \"%.30s\"");
             e = condtree(e, e, pointer(idtree(null->u.c.loc)));
         } else {
             appendstr("("); appendstr(typestring(ty, "")); appendstr(")0x%x");
         }
         break;
     case STRUCT: {
         Field q;
         appendstr("("); appendstr(typestring(ty, "")); appendstr("){");
         for (q = ty->u.sym->u.s.flist; q; q = q->link) {
             appendstr(q->name); appendstr("=");
             tracevalue(field(addrof(e), q->name), lev + 1);
             if (q->link)
                 appendstr(",");
         }
         appendstr("}");
         return;
         }
     case UNION:
         appendstr("("); appendstr(typestring(ty, "")); appendstr("){...}");
         return;
     case ARRAY:
         if (lev && ty->type->size > 0) {
             int i;
             e = pointer(e);
             appendstr("{");
             for (i = 0; i < ty->size/ty->type->size; i++) {
                 Tree p = (*optree['+'])(ADD, e, consttree(i, inttype));
                 if (isptr(p->type) && isarray(p->type->type))
                     p = retype(p, p->type->type);
                 else
                     p = rvalue(p);
                 if (i)
                     appendstr(",");
                 tracevalue(p, lev + 1);
             }
             appendstr("}");
         } else
             appendstr(typestring(ty, ""));
         return;
     default:
         assert(0);
     }
     e = cast(e, promote(ty));
     args = tree(mkop(ARG,e->type), e->type, e, args);
 }
References ADD, addrof(), appendstr(), args, cast(), chartype, condtree(), consttree(), field(), idtree(), INT, inttype, isarray, isptr, longdouble, longtype, mkop, mkstr(), NULL, optree, promote(), retype(), rvalue(), signedchar, tree(), typestring(), unqual, unsignedchar, unsignedlong, and unsignedtype.
Referenced by tracecall(), and tracereturn().
Variable Documentation
args
Tree args static
Definition at line 5 of file trace.c.
Referenced by asmcall(), call(), callAsmCall(), calltree(), CL_CgameSystemCalls(), CL_CompleteRcon(), CL_UISystemCalls(), Cmd_CompleteArgument(), Cvar_CompleteCvarName(), dclr1(), dodefine(), DoSyscall(), Key_CompleteBind(), Key_CompleteUnbind(), SV_GameSystemCalls(), tracefinis(), tracevalue(), vcall(), VM_AsmCall(), VM_Call(), VM_CallCompiled(), VM_CallInterpreted(), VM_DllSyscall(), and VM_LogSyscalls().
fmt
char* fmt static
Definition at line 4 of file trace.c.
Referenced by __attribute__(), appendstr(), CodeError(), Com_DPrintf(), Com_Error(), Com_Printf(), Com_sprintf(), emitasm(), error(), fatal(), fprint(), FS_Printf(), G_Error(), G_LogPrintf(), G_Printf(), mkreg(), print(), report(), SNDDMA_PrintAudiospec(), stringf(), SV_SendServerCommand(), tracefinis(), trap_Error(), trap_Print(), trap_Printf(), vfprint(), vreport(), warning(), yyerror(), and yywarn().
fmtend
char * fmtend static
Definition at line 4 of file trace.c.
Referenced by appendstr(), and tracefinis().
fp
char * fp static
Definition at line 4 of file trace.c.
Referenced by appendstr(), and tracefinis().
frameno
Symbol frameno static
Definition at line 6 of file trace.c.
Referenced by tracecall(), and tracereturn().