ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/i686-pc-mingw32/bits/gthr-default.h File Reference
gthr-default.h File Reference
#include <errno.h>
#include <windows.h>
Data Structures
struct __gthread_mutex_t
struct __gthread_once_t
struct __gthread_recursive_mutex_t
Macros
#define ___GLIBCXX_UNUSED_PARAM(x) x
#define __GTHR_W32_InterlockedCompareExchange InterlockedCompareExchange
#define __GTHREAD_MUTEX_INIT_DEFAULT {-1, 0}
#define __GTHREAD_MUTEX_INIT_FUNCTION __gthread_mutex_init_function
#define __GTHREAD_ONCE_INIT {0, -1}
#define __GTHREAD_RECURSIVE_MUTEX_INIT_DEFAULT {-1, 0, 0, 0}
#define __GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION __gthread_recursive_mutex_init_function
#define __GTHREADS 1
#define CONST_CAST2(TOTYPE, FROMTYPE, X) ((__extension__(union {FROMTYPE _q; TOTYPE _nq;})(X))._nq)
Typedefs
typedef unsigned long __gthread_key_t
Functions
static int __gthread_active_p (void)
static void * __gthread_getspecific (__gthread_key_t __key)
static int __gthread_key_create (__gthread_key_t *__key, void(*__dtor)(void *) __attribute__((unused)))
static int __gthread_key_delete (__gthread_key_t __key)
static void __gthread_mutex_destroy (__gthread_mutex_t *__mutex)
static void __gthread_mutex_init_function (__gthread_mutex_t *__mutex)
static int __gthread_mutex_lock (__gthread_mutex_t *__mutex)
static int __gthread_mutex_trylock (__gthread_mutex_t *__mutex)
static int __gthread_mutex_unlock (__gthread_mutex_t *__mutex)
static int __gthread_once (__gthread_once_t *__once, void(*__func)(void))
static void __gthread_recursive_mutex_init_function (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_lock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_trylock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_recursive_mutex_unlock (__gthread_recursive_mutex_t *__mutex)
static int __gthread_setspecific (__gthread_key_t __key, const void *__ptr)
Macro Definition Documentation
___GLIBCXX_UNUSED_PARAM
#define ___GLIBCXX_UNUSED_PARAM (x) x
Definition at line 76 of file gthr-default.h.
__GTHR_W32_InterlockedCompareExchange
#define __GTHR_W32_InterlockedCompareExchange InterlockedCompareExchange
Definition at line 398 of file gthr-default.h.
__GTHREAD_MUTEX_INIT_DEFAULT
#define __GTHREAD_MUTEX_INIT_DEFAULT {-1, 0}
Definition at line 364 of file gthr-default.h.
__GTHREAD_MUTEX_INIT_FUNCTION
#define __GTHREAD_MUTEX_INIT_FUNCTION __gthread_mutex_init_function
Definition at line 363 of file gthr-default.h.
__GTHREAD_ONCE_INIT
#define __GTHREAD_ONCE_INIT {0, -1}
Definition at line 362 of file gthr-default.h.
__GTHREAD_RECURSIVE_MUTEX_INIT_DEFAULT
#define __GTHREAD_RECURSIVE_MUTEX_INIT_DEFAULT {-1, 0, 0, 0}
Definition at line 367 of file gthr-default.h.
__GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION
#define __GTHREAD_RECURSIVE_MUTEX_INIT_FUNCTION __gthread_recursive_mutex_init_function
Definition at line 365 of file gthr-default.h.
__GTHREADS
#define __GTHREADS 1
Definition at line 68 of file gthr-default.h.
CONST_CAST2
#define CONST_CAST2 (TOTYPE, FROMTYPE, X) ((__extension__(union {FROMTYPE _q; TOTYPE _nq;})(X))._nq)
Definition at line 34 of file gthr-default.h.
Typedef Documentation
__gthread_key_t
typedef unsigned long __gthread_key_t
Definition at line 343 of file gthr-default.h.
Function Documentation
__gthread_active_p()
static int __gthread_active_p (void) inline static
Definition at line 402 of file gthr-default.h.
 {
 #ifdef MINGW32_SUPPORTS_MT_EH
   return _CRT_MT;
 #else
   return 1;
 #endif
 }
Referenced by __gthread_mutex_destroy(), __gthread_mutex_lock(), __gthread_mutex_trylock(), __gthread_mutex_unlock(), __gthread_once(), __gthread_recursive_mutex_init_function(), __gthread_recursive_mutex_lock(), __gthread_recursive_mutex_trylock(), __gthread_recursive_mutex_unlock(), and _GLIBCXX_VISIBILITY().
__gthread_getspecific()
static void* __gthread_getspecific (__gthread_key_t __key) inline static
Definition at line 604 of file gthr-default.h.
 {
   DWORD __lasterror;
   void *__ptr;
   __lasterror = GetLastError ();
   __ptr = TlsGetValue (__key);
   SetLastError (__lasterror);
   return __ptr;
 }
References GetLastError(), SetLastError(), and TlsGetValue().
__gthread_key_create()
static int __gthread_key_create (__gthread_key_t * __key, void(*)(void *) __attribute__ __dtor((unused))) inline static
Definition at line 578 of file gthr-default.h.
 {
   int __status = 0;
   DWORD __tls_index = TlsAlloc ();
   if (__tls_index != 0xFFFFFFFF)
     {
       *__key = __tls_index;
 #ifdef MINGW32_SUPPORTS_MT_EH
       /* Mingw runtime will run the dtors in reverse order for each thread
          when the thread exits.  */
       __status = __mingwthr_key_dtor (*__key, __dtor);
 #endif
     }
   else
     __status = (int) GetLastError ();
   return __status;
 }
References GetLastError(), int, and TlsAlloc().
__gthread_key_delete()
static int __gthread_key_delete (__gthread_key_t __key) inline static
Definition at line 598 of file gthr-default.h.
 {
   return (TlsFree (__key) != 0) ? 0 : (int) GetLastError ();
 }
References GetLastError(), int, and TlsFree().
__gthread_mutex_destroy()
static void __gthread_mutex_destroy (__gthread_mutex_t * __mutex) inline static
Definition at line 635 of file gthr-default.h.
 {
   CloseHandle ((HANDLE) __mutex->sema);
 }
References CloseHandle(), and __gthread_mutex_t::sema.
Referenced by _GLIBCXX_VISIBILITY().
__gthread_mutex_init_function()
static void __gthread_mutex_init_function (__gthread_mutex_t * __mutex) inline static
Definition at line 628 of file gthr-default.h.
 {
   __mutex->counter = -1;
   __mutex->sema = CreateSemaphore (NULL, 0, 65535, NULL);
 }
References __gthread_mutex_t::counter, CreateSemaphore, NULL, and __gthread_mutex_t::sema.
__gthread_mutex_lock()
static int __gthread_mutex_lock (__gthread_mutex_t * __mutex) inline static
Definition at line 641 of file gthr-default.h.
 {
   int __status = 0;
   if (__gthread_active_p ())
     {
       if (InterlockedIncrement (&__mutex->counter) == 0 ||
       WaitForSingleObject (__mutex->sema, INFINITE) == WAIT_OBJECT_0)
     __status = 0;
       else
     {
       /* WaitForSingleObject returns WAIT_FAILED, and we can only do
          some best-effort cleanup here.  */
       InterlockedDecrement (&__mutex->counter);
       __status = 1;
     }
     }
   return __status;
 }
References __gthread_active_p(), __gthread_mutex_t::counter, INFINITE, InterlockedDecrement(), InterlockedIncrement(), __gthread_mutex_t::sema, WAIT_OBJECT_0, and WaitForSingleObject().
Referenced by _GLIBCXX_VISIBILITY().
__gthread_mutex_trylock()
static int __gthread_mutex_trylock (__gthread_mutex_t * __mutex) inline static
Definition at line 662 of file gthr-default.h.
 {
   int __status = 0;
   if (__gthread_active_p ())
     {
       if (__GTHR_W32_InterlockedCompareExchange (&__mutex->counter, 0, -1) < 0)
     __status = 0;
       else
     __status = 1;
     }
   return __status;
 }
References __GTHR_W32_InterlockedCompareExchange, __gthread_active_p(), and __gthread_mutex_t::counter.
__gthread_mutex_unlock()
static int __gthread_mutex_unlock (__gthread_mutex_t * __mutex) inline static
Definition at line 677 of file gthr-default.h.
 {
   if (__gthread_active_p ())
     {
       if (InterlockedDecrement (&__mutex->counter) >= 0)
     return ReleaseSemaphore (__mutex->sema, 1, NULL) ? 0 : 1;
     }
   return 0;
 }
References __gthread_active_p(), __gthread_mutex_t::counter, InterlockedDecrement(), NULL, ReleaseSemaphore(), and __gthread_mutex_t::sema.
Referenced by _GLIBCXX_VISIBILITY().
__gthread_once()
static int __gthread_once (__gthread_once_t * __once, void(*)(void) __func) inline static
Definition at line 545 of file gthr-default.h.
 {
   if (! __gthread_active_p ())
     return -1;
   else if (__once == NULL || __func == NULL)
     return EINVAL;
   if (! __once->done)
     {
       if (InterlockedIncrement (&(__once->started)) == 0)
     {
       (*__func) ();
       __once->done = TRUE;
     }
       else
     {
       /* Another thread is currently executing the code, so wait for it
          to finish; yield the CPU in the meantime.  If performance
          does become an issue, the solution is to use an Event that
          we wait on here (and set above), but that implies a place to
          create the event before this routine is called.  */
       while (! __once->done)
         Sleep (0);
     }
     }
   return 0;
 }
References __gthread_active_p(), __gthread_once_t::done, EINVAL, InterlockedIncrement(), NULL, Sleep(), __gthread_once_t::started, and TRUE.
__gthread_recursive_mutex_init_function()
static void __gthread_recursive_mutex_init_function (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 688 of file gthr-default.h.
 {
   __mutex->counter = -1;
   __mutex->depth = 0;
   __mutex->owner = 0;
   __mutex->sema = CreateSemaphore (NULL, 0, 65535, NULL);
 }
References __gthread_recursive_mutex_t::counter, CreateSemaphore, __gthread_recursive_mutex_t::depth, NULL, __gthread_recursive_mutex_t::owner, and __gthread_recursive_mutex_t::sema.
__gthread_recursive_mutex_lock()
static int __gthread_recursive_mutex_lock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 697 of file gthr-default.h.
 {
   if (__gthread_active_p ())
     {
       DWORD __me = GetCurrentThreadId();
       if (InterlockedIncrement (&__mutex->counter) == 0)
     {
       __mutex->depth = 1;
       __mutex->owner = __me;
     }
       else if (__mutex->owner == __me)
     {
       InterlockedDecrement (&__mutex->counter);
       ++(__mutex->depth);
     }
       else if (WaitForSingleObject (__mutex->sema, INFINITE) == WAIT_OBJECT_0)
     {
       __mutex->depth = 1;
       __mutex->owner = __me;
     }
       else
     {
       /* WaitForSingleObject returns WAIT_FAILED, and we can only do
          some best-effort cleanup here.  */
       InterlockedDecrement (&__mutex->counter);
       return 1;
     }
     }
   return 0;
 }
References __gthread_active_p(), __gthread_recursive_mutex_t::counter, __gthread_recursive_mutex_t::depth, GetCurrentThreadId(), INFINITE, InterlockedDecrement(), InterlockedIncrement(), __gthread_recursive_mutex_t::owner, __gthread_recursive_mutex_t::sema, WAIT_OBJECT_0, and WaitForSingleObject().
Referenced by _GLIBCXX_VISIBILITY().
__gthread_recursive_mutex_trylock()
static int __gthread_recursive_mutex_trylock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 729 of file gthr-default.h.
 {
   if (__gthread_active_p ())
     {
       DWORD __me = GetCurrentThreadId();
       if (__GTHR_W32_InterlockedCompareExchange (&__mutex->counter, 0, -1) < 0)
     {
       __mutex->depth = 1;
       __mutex->owner = __me;
     }
       else if (__mutex->owner == __me)
     ++(__mutex->depth);
       else
     return 1;
     }
   return 0;
 }
References __GTHR_W32_InterlockedCompareExchange, __gthread_active_p(), __gthread_recursive_mutex_t::counter, __gthread_recursive_mutex_t::depth, GetCurrentThreadId(), and __gthread_recursive_mutex_t::owner.
__gthread_recursive_mutex_unlock()
static int __gthread_recursive_mutex_unlock (__gthread_recursive_mutex_t * __mutex) inline static
Definition at line 748 of file gthr-default.h.
 {
   if (__gthread_active_p ())
     {
       --(__mutex->depth);
       if (__mutex->depth == 0)
     {
       __mutex->owner = 0;
       if (InterlockedDecrement (&__mutex->counter) >= 0)
         return ReleaseSemaphore (__mutex->sema, 1, NULL) ? 0 : 1;
     }
     }
   return 0;
 }
References __gthread_active_p(), __gthread_recursive_mutex_t::counter, __gthread_recursive_mutex_t::depth, InterlockedDecrement(), NULL, __gthread_recursive_mutex_t::owner, ReleaseSemaphore(), and __gthread_recursive_mutex_t::sema.
Referenced by _GLIBCXX_VISIBILITY().
__gthread_setspecific()
static int __gthread_setspecific (__gthread_key_t __key, const void * __ptr) inline static
Definition at line 619 of file gthr-default.h.
 {
   if (TlsSetValue (__key, CONST_CAST2(void *, const void *, __ptr)) != 0)
     return 0;
   else
     return GetLastError ();
 }
References CONST_CAST2, GetLastError(), and TlsSetValue().