ZEQ2-Lite: PathGradientBrush Class Reference
PathGradientBrush Class Reference
#include <gdipluspath.h>
Public Member Functions
PathGradientBrush (const GraphicsPath *path)
PathGradientBrush (const Point *points, INT count, WrapMode wrapMode=WrapModeClamp)
PathGradientBrush (const PointF *points, INT count, WrapMode wrapMode=WrapModeClamp)
virtual PathGradientBrush * Clone () const
Status GetBlend (REAL *blendFactors, REAL *blendPositions, INT count) const
INT GetBlendCount () const
Status GetCenterColor (Color *color) const
Status GetCenterPoint (Point *point) const
Status GetCenterPoint (PointF *point) const
Status GetFocusScales (REAL *xScale, REAL *yScale) const
BOOL GetGammaCorrection () const
INT GetInterpolationColorCount () const
Status GetInterpolationColors (Color *presetColors, REAL *blendPositions, INT count) const
Status GetLastStatus () const
INT GetPointCount () const
Status GetRectangle (Rect *rect) const
Status GetRectangle (RectF *rect) const
INT GetSurroundColorCount () const
Status GetSurroundColors (Color *colors, INT *count)
Status GetTransform (Matrix *matrix) const
BrushType GetType () const
WrapMode GetWrapMode () const
Status MultiplyTransform (const Matrix *matrix, MatrixOrder order=MatrixOrderPrepend)
Status ResetTransform ()
Status RotateTransform (REAL angle, MatrixOrder order=MatrixOrderPrepend)
Status ScaleTransform (REAL sx, REAL sy, MatrixOrder order=MatrixOrderPrepend)
Status SetBlend (REAL *blendFactors, REAL *blendPositions, INT count)
Status SetBlendBellShape (REAL focus, REAL scale=1.0f)
Status SetBlendTriangularShape (REAL focus, REAL scale=1.0f)
Status SetCenterColor (const Color &color)
Status SetCenterPoint (const Point &point)
Status SetCenterPoint (const PointF &point)
Status SetFocusScales (REAL xScale, REAL yScale)
Status SetGammaCorrection (BOOL useGammaCorrection)
Status SetInterpolationColors (const Color *presetColors, REAL *blendPositions, INT count)
Status SetSurroundColors (const Color *colors, INT *count)
Status SetTransform (const Matrix *matrix)
Status SetWrapMode (WrapMode wrapMode)
Status TranslateTransform (REAL dx, REAL dy, MatrixOrder order=MatrixOrderPrepend)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
PathGradientBrush (const PathGradientBrush &)
PathGradientBrush (GpBrush *brush, Status status)
PathGradientBrush & operator= (const PathGradientBrush &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpBrush * nativeBrush
Detailed Description
Definition at line 652 of file gdipluspath.h.
Constructor & Destructor Documentation
PathGradientBrush() [1/5]
PathGradientBrush::PathGradientBrush (const PointF * points, INT count, WrapMode wrapMode = WrapModeClamp) inline
Definition at line 655 of file gdipluspath.h.
     {
         GpPathGradient *nativePathGradient = NULL;
         lastStatus = DllExports::GdipCreatePathGradient(
                 points, count, wrapMode, &nativePathGradient);
         nativeBrush = nativePathGradient;
     }
References GdipCreatePathGradient(), Brush::lastStatus, Brush::nativeBrush, and NULL.
PathGradientBrush() [2/5]
PathGradientBrush::PathGradientBrush (const Point * points, INT count, WrapMode wrapMode = WrapModeClamp) inline
Definition at line 663 of file gdipluspath.h.
     {
         GpPathGradient *nativePathGradient = NULL;
         lastStatus = DllExports::GdipCreatePathGradientI(
                 points, count, wrapMode, &nativePathGradient);
         nativeBrush = nativePathGradient;
     }
References GdipCreatePathGradientI(), Brush::lastStatus, Brush::nativeBrush, and NULL.
PathGradientBrush() [3/5]
PathGradientBrush::PathGradientBrush (const GraphicsPath * path) inline
Definition at line 671 of file gdipluspath.h.
     {
         GpPathGradient *nativePathGradient = NULL;
         lastStatus = DllExports::GdipCreatePathGradientFromPath(
                 path ? path->nativePath : NULL,
                 &nativePathGradient);
         nativeBrush = nativePathGradient;
     }
References GdipCreatePathGradientFromPath(), Brush::lastStatus, Brush::nativeBrush, GraphicsPath::nativePath, and NULL.
PathGradientBrush() [4/5]
PathGradientBrush::PathGradientBrush (GpBrush * brush, Status status) inline private
Definition at line 957 of file gdipluspath.h.
 : Brush(brush, status) {}
PathGradientBrush() [5/5]
PathGradientBrush::PathGradientBrush (const PathGradientBrush &) private
Member Function Documentation
Clone()
virtual PathGradientBrush* PathGradientBrush::Clone () const inline virtual
Reimplemented from Brush.
Definition at line 679 of file gdipluspath.h.
     {
         GpBrush *cloneBrush = NULL;
         Status status = updateStatus(DllExports::GdipCloneBrush(
                 nativeBrush, &cloneBrush));
         if (status == Ok) {
             PathGradientBrush *result =
                 new PathGradientBrush(cloneBrush, lastStatus);
             if (!result) {
                 DllExports::GdipDeleteBrush(cloneBrush);
                 updateStatus(OutOfMemory);
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneBrush(), GdipDeleteBrush(), Brush::lastStatus, Brush::nativeBrush, NULL, Ok, OutOfMemory, Brush::PathGradientBrush, and Brush::updateStatus().
GetBlend()
Status PathGradientBrush::GetBlend (REAL * blendFactors, REAL * blendPositions, INT count) const inline
Definition at line 697 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathGradientBlend(
                 (GpPathGradient*) nativeBrush,
                 blendFactors, blendPositions, count));
     }
References GdipGetPathGradientBlend(), Brush::nativeBrush, and Brush::updateStatus().
GetBlendCount()
INT PathGradientBrush::GetBlendCount () const inline
Definition at line 704 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetPathGradientBlendCount(
                 (GpPathGradient*) nativeBrush, &result));
         return result;
     }
References GdipGetPathGradientBlendCount(), Brush::nativeBrush, and Brush::updateStatus().
GetCenterColor()
Status PathGradientBrush::GetCenterColor (Color * color) const inline
Definition at line 711 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathGradientCenterColor(
                 (GpPathGradient*) nativeBrush,
                 color ? &color->Value : NULL));
     }
References GdipGetPathGradientCenterColor(), Brush::nativeBrush, NULL, Brush::updateStatus(), and Color::Value.
GetCenterPoint() [1/2]
Status PathGradientBrush::GetCenterPoint (Point * point) const inline
Definition at line 722 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathGradientCenterPointI(
                 (GpPathGradient*) nativeBrush, point));
     }
References GdipGetPathGradientCenterPointI(), Brush::nativeBrush, and Brush::updateStatus().
GetCenterPoint() [2/2]
Status PathGradientBrush::GetCenterPoint (PointF * point) const inline
Definition at line 717 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathGradientCenterPoint(
                 (GpPathGradient*) nativeBrush, point));
     }
References GdipGetPathGradientCenterPoint(), Brush::nativeBrush, and Brush::updateStatus().
GetFocusScales()
Status PathGradientBrush::GetFocusScales (REAL * xScale, REAL * yScale) const inline
Definition at line 727 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathGradientFocusScales(
                 (GpPathGradient*) nativeBrush, xScale, yScale));
     }
References GdipGetPathGradientFocusScales(), Brush::nativeBrush, and Brush::updateStatus().
GetGammaCorrection()
BOOL PathGradientBrush::GetGammaCorrection () const inline
Definition at line 732 of file gdipluspath.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipGetPathGradientGammaCorrection(
                 (GpPathGradient*) nativeBrush, &result));
         return result;
     }
References FALSE, GdipGetPathGradientGammaCorrection(), Brush::nativeBrush, and Brush::updateStatus().
GetInterpolationColorCount()
INT PathGradientBrush::GetInterpolationColorCount () const inline
Definition at line 744 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetPathGradientPresetBlendCount(
                 (GpPathGradient*) nativeBrush, &result));
         return result;
     }
References GdipGetPathGradientPresetBlendCount(), Brush::nativeBrush, and Brush::updateStatus().
GetInterpolationColors()
Status PathGradientBrush::GetInterpolationColors (Color * presetColors, REAL * blendPositions, INT count) const inline
Definition at line 751 of file gdipluspath.h.
     {
         if (!presetColors || count <= 0)
             return lastStatus = InvalidParameter;
         ARGB *presetArgb =
             (ARGB*) DllExports::GdipAlloc(count * sizeof(ARGB));
         if (!presetArgb)
             return lastStatus = OutOfMemory;
         Status status = updateStatus(DllExports::GdipGetPathGradientPresetBlend(
                 (GpPathGradient*) nativeBrush,
                 presetArgb, blendPositions, count));
         for (INT i = 0; i < count; ++i) {
             presetColors[i].SetValue(presetArgb[i]);
         }
         DllExports::GdipFree((void*) presetArgb);
         return status;
     }
References GdipAlloc(), GdipFree(), GdipGetPathGradientPresetBlend(), InvalidParameter, Brush::lastStatus, Brush::nativeBrush, OutOfMemory, and Brush::updateStatus().
GetLastStatus()
Status Brush::GetLastStatus () const inline inherited
Definition at line 54 of file gdiplusbrush.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References Brush::lastStatus, and Ok.
GetPointCount()
INT PathGradientBrush::GetPointCount () const inline
Definition at line 771 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetPathGradientPointCount(
                 (GpPathGradient*) nativeBrush, &result));
         return result;
     }
References GdipGetPathGradientPointCount(), Brush::nativeBrush, and Brush::updateStatus().
GetRectangle() [1/2]
Status PathGradientBrush::GetRectangle (Rect * rect) const inline
Definition at line 783 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathGradientRectI(
                 (GpPathGradient*) nativeBrush, rect));
     }
References GdipGetPathGradientRectI(), Brush::nativeBrush, and Brush::updateStatus().
GetRectangle() [2/2]
Status PathGradientBrush::GetRectangle (RectF * rect) const inline
Definition at line 778 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathGradientRect(
                 (GpPathGradient*) nativeBrush, rect));
     }
References GdipGetPathGradientRect(), Brush::nativeBrush, and Brush::updateStatus().
GetSurroundColorCount()
INT PathGradientBrush::GetSurroundColorCount () const inline
Definition at line 788 of file gdipluspath.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetPathGradientSurroundColorCount(
                 (GpPathGradient*) nativeBrush, &result));
         return result;
     }
References GdipGetPathGradientSurroundColorCount(), Brush::nativeBrush, and Brush::updateStatus().
GetSurroundColors()
Status PathGradientBrush::GetSurroundColors (Color * colors, INT * count) inline
Definition at line 795 of file gdipluspath.h.
     {
         if (!colors || !count || *count <= 0)
             return lastStatus = InvalidParameter;
         ARGB *colorsArgb =
             (ARGB*) DllExports::GdipAlloc(*count * sizeof(ARGB));
         if (!colorsArgb)
             return lastStatus = OutOfMemory;
         Status status = updateStatus(DllExports::GdipGetPathGradientSurroundColorsWithCount(
                 (GpPathGradient*) nativeBrush,
                 colorsArgb, count));
         for (INT i = 0; i < *count; ++i) {
             colors[i].SetValue(colorsArgb[i]);
         }
         DllExports::GdipFree((void*) colorsArgb);
         return status;
     }
References GdipAlloc(), GdipFree(), GdipGetPathGradientSurroundColorsWithCount(), InvalidParameter, Brush::lastStatus, Brush::nativeBrush, OutOfMemory, and Brush::updateStatus().
GetTransform()
Status PathGradientBrush::GetTransform (Matrix * matrix) const inline
Definition at line 814 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipGetPathGradientTransform(
                 (GpPathGradient*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipGetPathGradientTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
GetType()
BrushType Brush::GetType () const inline inherited
Definition at line 60 of file gdiplusbrush.h.
     {
         BrushType result = BrushTypeSolidColor;
         updateStatus(DllExports::GdipGetBrushType(nativeBrush, &result));
         return result;
     }
References BrushTypeSolidColor, GdipGetBrushType(), Brush::nativeBrush, and Brush::updateStatus().
GetWrapMode()
WrapMode PathGradientBrush::GetWrapMode () const inline
Definition at line 820 of file gdipluspath.h.
     {
         WrapMode result = WrapModeTile;
         updateStatus(DllExports::GdipGetPathGradientWrapMode(
                 (GpPathGradient*) nativeBrush, &result));
         return result;
     }
References GdipGetPathGradientWrapMode(), Brush::nativeBrush, Brush::updateStatus(), and WrapModeTile.
MultiplyTransform()
Status PathGradientBrush::MultiplyTransform (const Matrix * matrix, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 827 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipMultiplyPathGradientTransform(
                 (GpPathGradient*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL, order));
     }
References GdipMultiplyPathGradientTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
PathGradientBrush& PathGradientBrush::operator= (const PathGradientBrush &) private
ResetTransform()
Status PathGradientBrush::ResetTransform () inline
Definition at line 834 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipResetPathGradientTransform(
                 (GpPathGradient*) nativeBrush));
     }
References GdipResetPathGradientTransform(), Brush::nativeBrush, and Brush::updateStatus().
RotateTransform()
Status PathGradientBrush::RotateTransform (REAL angle, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 839 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipRotatePathGradientTransform(
                 (GpPathGradient*) nativeBrush, angle, order));
     }
References GdipRotatePathGradientTransform(), Brush::nativeBrush, and Brush::updateStatus().
ScaleTransform()
Status PathGradientBrush::ScaleTransform (REAL sx, REAL sy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 845 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipScalePathGradientTransform(
                 (GpPathGradient*) nativeBrush, sx, sy, order));
     }
References GdipScalePathGradientTransform(), Brush::nativeBrush, sy, and Brush::updateStatus().
SetBlend()
Status PathGradientBrush::SetBlend (REAL * blendFactors, REAL * blendPositions, INT count) inline
Definition at line 851 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientBlend(
                 (GpPathGradient*) nativeBrush,
                 blendFactors, blendPositions, count));
     }
References GdipSetPathGradientBlend(), Brush::nativeBrush, and Brush::updateStatus().
SetBlendBellShape()
Status PathGradientBrush::SetBlendBellShape (REAL focus, REAL scale = 1.0f) inline
Definition at line 857 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientSigmaBlend(
                 (GpPathGradient*) nativeBrush, focus, scale));
     }
References GdipSetPathGradientSigmaBlend(), Brush::nativeBrush, and Brush::updateStatus().
SetBlendTriangularShape()
Status PathGradientBrush::SetBlendTriangularShape (REAL focus, REAL scale = 1.0f) inline
Definition at line 862 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientLinearBlend(
                 (GpPathGradient*) nativeBrush, focus, scale));
     }
References GdipSetPathGradientLinearBlend(), Brush::nativeBrush, and Brush::updateStatus().
SetCenterColor()
Status PathGradientBrush::SetCenterColor (const Color & color) inline
Definition at line 867 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientCenterColor(
                 (GpPathGradient*) nativeBrush,
                 color.GetValue()));
     }
References GdipSetPathGradientCenterColor(), Brush::nativeBrush, and Brush::updateStatus().
SetCenterPoint() [1/2]
Status PathGradientBrush::SetCenterPoint (const Point & point) inline
Definition at line 878 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientCenterPointI(
                 (GpPathGradient*) nativeBrush, &point));
     }
References GdipSetPathGradientCenterPointI(), Brush::nativeBrush, and Brush::updateStatus().
SetCenterPoint() [2/2]
Status PathGradientBrush::SetCenterPoint (const PointF & point) inline
Definition at line 873 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientCenterPoint(
                 (GpPathGradient*) nativeBrush, &point));
     }
References GdipSetPathGradientCenterPoint(), Brush::nativeBrush, and Brush::updateStatus().
SetFocusScales()
Status PathGradientBrush::SetFocusScales (REAL xScale, REAL yScale) inline
Definition at line 883 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientFocusScales(
                 (GpPathGradient*) nativeBrush, xScale, yScale));
     }
References GdipSetPathGradientFocusScales(), Brush::nativeBrush, and Brush::updateStatus().
SetGammaCorrection()
Status PathGradientBrush::SetGammaCorrection (BOOL useGammaCorrection) inline
Definition at line 888 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientGammaCorrection(
                 (GpPathGradient*) nativeBrush,
                 useGammaCorrection));
     }
References GdipSetPathGradientGammaCorrection(), Brush::nativeBrush, and Brush::updateStatus().
SetInterpolationColors()
Status PathGradientBrush::SetInterpolationColors (const Color * presetColors, REAL * blendPositions, INT count) inline
Definition at line 899 of file gdipluspath.h.
     {
         if (!presetColors || count <= 0)
             return lastStatus = InvalidParameter;
         ARGB *presetArgb =
             (ARGB*) DllExports::GdipAlloc(count * sizeof(ARGB));
         if (!presetArgb)
             return lastStatus = OutOfMemory;
         for (INT i = 0; i < count; ++i) {
             presetArgb[i] = presetColors[i].GetValue();
         }
         Status status = updateStatus(DllExports::GdipSetPathGradientPresetBlend(
                 (GpPathGradient*) nativeBrush,
                 presetArgb, blendPositions, count));
         DllExports::GdipFree((void*) presetArgb);
         return status;
     }
References GdipAlloc(), GdipFree(), GdipSetPathGradientPresetBlend(), InvalidParameter, Brush::lastStatus, Brush::nativeBrush, OutOfMemory, and Brush::updateStatus().
SetSurroundColors()
Status PathGradientBrush::SetSurroundColors (const Color * colors, INT * count) inline
Definition at line 919 of file gdipluspath.h.
     {
         if (!colors || !count || *count <= 0)
             return lastStatus = InvalidParameter;
         ARGB *colorsArgb =
             (ARGB*) DllExports::GdipAlloc(*count * sizeof(ARGB));
         if (!colorsArgb)
             return lastStatus = OutOfMemory;
         for (INT i = 0; i < *count; ++i) {
             colorsArgb[i] = colors[i].GetValue();
         }
         Status status = updateStatus(DllExports::GdipSetPathGradientSurroundColorsWithCount(
                 (GpPathGradient*) nativeBrush,
                 colorsArgb, count));
         DllExports::GdipFree((void*) colorsArgb);
         return status;
     }
References GdipAlloc(), GdipFree(), GdipSetPathGradientSurroundColorsWithCount(), InvalidParameter, Brush::lastStatus, Brush::nativeBrush, OutOfMemory, and Brush::updateStatus().
SetTransform()
Status PathGradientBrush::SetTransform (const Matrix * matrix) inline
Definition at line 938 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientTransform(
                 (GpPathGradient*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipSetPathGradientTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
SetWrapMode()
Status PathGradientBrush::SetWrapMode (WrapMode wrapMode) inline
Definition at line 944 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipSetPathGradientWrapMode(
                 (GpPathGradient*) nativeBrush, wrapMode));
     }
References GdipSetPathGradientWrapMode(), Brush::nativeBrush, and Brush::updateStatus().
TranslateTransform()
Status PathGradientBrush::TranslateTransform (REAL dx, REAL dy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 949 of file gdipluspath.h.
     {
         return updateStatus(DllExports::GdipTranslatePathGradientTransform(
                 (GpPathGradient*) nativeBrush, dx, dy, order));
     }
References GdipTranslatePathGradientTransform(), Brush::nativeBrush, and Brush::updateStatus().
updateStatus()
Status Brush::updateStatus (Status newStatus) const inline private inherited
Definition at line 74 of file gdiplusbrush.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References Brush::lastStatus, and Ok.
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), TextureBrush::Clone(), Clone(), HatchBrush::GetBackgroundColor(), LinearGradientBrush::GetBlend(), GetBlend(), LinearGradientBrush::GetBlendCount(), GetBlendCount(), GetCenterColor(), GetCenterPoint(), SolidBrush::GetColor(), GetFocusScales(), HatchBrush::GetForegroundColor(), LinearGradientBrush::GetGammaCorrection(), GetGammaCorrection(), HatchBrush::GetHatchStyle(), LinearGradientBrush::GetInterpolationColorCount(), GetInterpolationColorCount(), LinearGradientBrush::GetInterpolationColors(), GetInterpolationColors(), LinearGradientBrush::GetLinearColors(), GetPointCount(), LinearGradientBrush::GetRectangle(), GetRectangle(), GetSurroundColorCount(), GetSurroundColors(), LinearGradientBrush::GetTransform(), GetTransform(), TextureBrush::GetTransfrom(), Brush::GetType(), LinearGradientBrush::GetWrapMode(), TextureBrush::GetWrapMode(), GetWrapMode(), LinearGradientBrush::MultiplyTransform(), TextureBrush::MultiplyTransform(), MultiplyTransform(), LinearGradientBrush::ResetTransform(), TextureBrush::ResetTransform(), ResetTransform(), LinearGradientBrush::RotateTranform(), TextureBrush::RotateTransform(), RotateTransform(), LinearGradientBrush::ScaleTransform(), TextureBrush::ScaleTransform(), ScaleTransform(), LinearGradientBrush::SetBlend(), SetBlend(), LinearGradientBrush::SetBlendBellShape(), SetBlendBellShape(), LinearGradientBrush::SetBlendTriangularShape(), SetBlendTriangularShape(), SetCenterColor(), SetCenterPoint(), SolidBrush::SetColor(), SetFocusScales(), LinearGradientBrush::SetGammaCorrection(), SetGammaCorrection(), LinearGradientBrush::SetInterpolationColors(), SetInterpolationColors(), LinearGradientBrush::SetLinearColors(), SetSurroundColors(), LinearGradientBrush::SetTransform(), TextureBrush::SetTransform(), SetTransform(), LinearGradientBrush::SetWrapMode(), TextureBrush::SetWrapMode(), SetWrapMode(), LinearGradientBrush::TranslateTransform(), TextureBrush::TranslateTransform(), and TranslateTransform().
Field Documentation
lastStatus
Status Brush::lastStatus mutable private inherited
Definition at line 81 of file gdiplusbrush.h.
Referenced by Brush::Clone(), HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), TextureBrush::Clone(), Clone(), LinearGradientBrush::GetInterpolationColors(), GetInterpolationColors(), Brush::GetLastStatus(), LinearGradientBrush::GetLinearColors(), GetSurroundColors(), HatchBrush::HatchBrush(), LinearGradientBrush::LinearGradientBrush(), PathGradientBrush(), LinearGradientBrush::SetInterpolationColors(), SetInterpolationColors(), SetSurroundColors(), SolidBrush::SolidBrush(), TextureBrush::TextureBrush(), and Brush::updateStatus().
nativeBrush
GpBrush* Brush::nativeBrush private inherited
Definition at line 80 of file gdiplusbrush.h.
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), TextureBrush::Clone(), Clone(), Graphics::DrawDriverString(), Graphics::DrawString(), Graphics::FillClosedCurve(), Graphics::FillEllipse(), Graphics::FillPath(), Graphics::FillPie(), Graphics::FillPolygon(), Graphics::FillRectangle(), Graphics::FillRectangles(), Graphics::FillRegion(), HatchBrush::GetBackgroundColor(), LinearGradientBrush::GetBlend(), GetBlend(), LinearGradientBrush::GetBlendCount(), GetBlendCount(), GetCenterColor(), GetCenterPoint(), SolidBrush::GetColor(), GetFocusScales(), HatchBrush::GetForegroundColor(), LinearGradientBrush::GetGammaCorrection(), GetGammaCorrection(), HatchBrush::GetHatchStyle(), LinearGradientBrush::GetInterpolationColorCount(), GetInterpolationColorCount(), LinearGradientBrush::GetInterpolationColors(), GetInterpolationColors(), LinearGradientBrush::GetLinearColors(), GetPointCount(), LinearGradientBrush::GetRectangle(), GetRectangle(), GetSurroundColorCount(), GetSurroundColors(), LinearGradientBrush::GetTransform(), GetTransform(), TextureBrush::GetTransfrom(), Brush::GetType(), LinearGradientBrush::GetWrapMode(), TextureBrush::GetWrapMode(), GetWrapMode(), HatchBrush::HatchBrush(), LinearGradientBrush::LinearGradientBrush(), LinearGradientBrush::MultiplyTransform(), TextureBrush::MultiplyTransform(), MultiplyTransform(), PathGradientBrush(), Pen::Pen(), LinearGradientBrush::ResetTransform(), TextureBrush::ResetTransform(), ResetTransform(), LinearGradientBrush::RotateTranform(), TextureBrush::RotateTransform(), RotateTransform(), LinearGradientBrush::ScaleTransform(), TextureBrush::ScaleTransform(), ScaleTransform(), LinearGradientBrush::SetBlend(), SetBlend(), LinearGradientBrush::SetBlendBellShape(), SetBlendBellShape(), LinearGradientBrush::SetBlendTriangularShape(), SetBlendTriangularShape(), Pen::SetBrush(), SetCenterColor(), SetCenterPoint(), SolidBrush::SetColor(), SetFocusScales(), LinearGradientBrush::SetGammaCorrection(), SetGammaCorrection(), LinearGradientBrush::SetInterpolationColors(), SetInterpolationColors(), LinearGradientBrush::SetLinearColors(), SetSurroundColors(), LinearGradientBrush::SetTransform(), TextureBrush::SetTransform(), SetTransform(), LinearGradientBrush::SetWrapMode(), TextureBrush::SetWrapMode(), SetWrapMode(), SolidBrush::SolidBrush(), TextureBrush::TextureBrush(), LinearGradientBrush::TranslateTransform(), TextureBrush::TranslateTransform(), TranslateTransform(), and Brush::~Brush().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdipluspath.h