ZEQ2-Lite: Source/Game/CGame/cg_weapGfxParser.h File Reference
cg_weapGfxParser.h File Reference
#include "cg_local.h"
Data Structures
struct cg_weapGfxDefinitionRef_t
struct cg_weapGfxField_t
struct cg_weapGfxImportRef_t
struct cg_weapGfxLinkRef_t
struct cg_weapGfxParser_t
struct cg_weapGfxScanner_t
struct cg_weapGfxToken_t
Macros
#define MAX_DEFINES 64
#define MAX_IMPORTS 16
#define MAX_LINKS 6
#define MAX_RECURSION_DEPTH 5
#define MAX_SCRIPT_LENGTH 8192
#define MAX_TOKENSTRING_LENGTH MAX_QPATH
#define TOKEN_CATEGORY 21
#define TOKEN_CLOSEBLOCK 2
#define TOKEN_CLOSERANGE 6
#define TOKEN_CLOSEVECTOR 4
#define TOKEN_COLON 13
#define TOKEN_EOF 0
#define TOKEN_EQUALS 11
#define TOKEN_FALSE 15
#define TOKEN_FIELD 20
#define TOKEN_FLOAT 18
#define TOKEN_IMPORT 7
#define TOKEN_INTEGER 17
#define TOKEN_NULL 16
#define TOKEN_OPENBLOCK 1
#define TOKEN_OPENRANGE 5
#define TOKEN_OPENVECTOR 3
#define TOKEN_PLUS 12
#define TOKEN_PRIVATE 10
#define TOKEN_PROTECTED 9
#define TOKEN_PUBLIC 8
#define TOKEN_STRING 19
#define TOKEN_TRUE 14
#define TOKEN_WEAPON 22
Enumerations
enum cg_weapGfxAccessLvls_t {
LVL_PUBLIC, LVL_PROTECTED, LVL_PRIVATE, LVL_PUBLIC,
LVL_PROTECTED, LVL_PRIVATE
}
enum cg_weapGfxCategoryIndex_t {
CAT_CHARGE, CAT_EXPLOSION, CAT_STRUGGLE, CAT_MISSILE,
CAT_FLASH, CAT_TRAIL, CAT_HUD, CAT_CHARGE,
CAT_EXPLOSION, CAT_STRUGGLE, CAT_MISSILE, CAT_FLASH,
CAT_TRAIL, CAT_HUD
}
enum cg_weapGfxError_t {
ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, ERROR_PREMATURE_EOF, ERROR_STRING_TOOBIG,
ERROR_TOKEN_TOOBIG, ERROR_UNKNOWN_SYMBOL, ERROR_UNEXPECTED_SYMBOL, ERROR_STRING_EXPECTED,
ERROR_INTEGER_EXPECTED, ERROR_FLOAT_EXPECTED, ERROR_IMPORTS_EXCEEDED, ERROR_IMPORT_REDEFINED,
ERROR_IMPORT_DOUBLED, ERROR_IMPORT_UNDEFINED, ERROR_REDEFINE_IMPORT_AS_DEFINITION, ERROR_DEFINITIONS_EXCEEDED,
ERROR_DEFINITION_REDEFINED, ERROR_DEFINITION_UNDEFINED, ERROR_LINK_BOUNDS, ERROR_LINK_REDEFINED,
ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INVERTED_RANGE, ERROR_OVER_MAXBOUND, ERROR_UNDER_MINBOUND,
ERROR_OVER_MAXVECTORELEMS, ERROR_MAX_RECURSION, ERROR_INHERITING_PRIVATE, ERROR_IMPORTING_NON_PUBLIC,
ERROR_OVERRIDING_WITH_HIGHER_ACCESS, ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, ERROR_PREMATURE_EOF,
ERROR_STRING_TOOBIG, ERROR_TOKEN_TOOBIG, ERROR_UNKNOWN_SYMBOL, ERROR_UNEXPECTED_SYMBOL,
ERROR_STRING_EXPECTED, ERROR_INTEGER_EXPECTED, ERROR_FLOAT_EXPECTED, ERROR_IMPORTS_EXCEEDED,
ERROR_IMPORT_REDEFINED, ERROR_IMPORT_DOUBLED, ERROR_IMPORT_UNDEFINED, ERROR_REDEFINE_IMPORT_AS_DEFINITION,
ERROR_DEFINITIONS_EXCEEDED, ERROR_DEFINITION_REDEFINED, ERROR_DEFINITION_UNDEFINED, ERROR_LINK_BOUNDS,
ERROR_LINK_REDEFINED, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INVERTED_RANGE, ERROR_OVER_MAXBOUND,
ERROR_UNDER_MINBOUND, ERROR_OVER_MAXVECTORELEMS, ERROR_MAX_RECURSION, ERROR_INHERITING_PRIVATE,
ERROR_IMPORTING_NON_PUBLIC, ERROR_OVERRIDING_WITH_HIGHER_ACCESS
}
Functions
qboolean CG_weapGfx_AddDefinitionRef (cg_weapGfxParser_t *parser, char *refname, char *pos, int line, cg_weapGfxAccessLvls_t accessLvl, qboolean hasSuper, char *supername)
qboolean CG_weapGfx_AddImportRef (cg_weapGfxParser_t *parser, char *refname, char *filename, char *defname)
qboolean CG_weapGfx_AddLinkRef (cg_weapGfxParser_t *parser, int index, char *pri_refname, char *sec_refname)
qboolean CG_weapGfx_CheckPrematureEOF (cg_weapGfxScanner_t *scanner, cg_weapGfxToken_t *token)
qboolean CG_weapGfx_ErrorHandle (cg_weapGfxError_t errorNr, cg_weapGfxScanner_t *scanner, char *string1, char *string2)
int CG_weapGfx_FindDefinitionRef (cg_weapGfxParser_t *parser, char *refname)
int CG_weapGfx_FindImportRef (cg_weapGfxParser_t *parser, char *refname)
qboolean CG_weapGfx_LoadFile (cg_weapGfxScanner_t *scanner, char *filename)
qboolean CG_weapGfx_NextSym (cg_weapGfxScanner_t *scanner, cg_weapGfxToken_t *token)
qboolean CG_weapGfx_ParseAnimationRange (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseDisplayName (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseDlight (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseDummy (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseDuration (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseIcon (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseLoopFx (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseLoopParticles (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseMarkShader (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseMarkSize (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseModel (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseOnceFx (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseParticles (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseRockDebris (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseShader (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseShockwave (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseSize (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseSkin (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseSmokeParticles (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseSoundFx (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseSpin (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseSpiralOffset (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseSpiralShader (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseSpiralSize (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseTagTo (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseTimedFx (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
qboolean CG_weapGfx_ParseVoiceFx (cg_weapGfxParser_t *parser, cg_weapGfxCategoryIndex_t category, int field)
Variables
char * cg_weapGfxCategories []
cg_weapGfxField_t cg_weapGfxFields []
Macro Definition Documentation
MAX_DEFINES
#define MAX_DEFINES 64
Definition at line 7 of file cg_weapGfxParser.h.
MAX_IMPORTS
#define MAX_IMPORTS 16
Definition at line 6 of file cg_weapGfxParser.h.
MAX_LINKS
#define MAX_LINKS 6
Definition at line 8 of file cg_weapGfxParser.h.
MAX_RECURSION_DEPTH
#define MAX_RECURSION_DEPTH 5
Definition at line 9 of file cg_weapGfxParser.h.
MAX_SCRIPT_LENGTH
#define MAX_SCRIPT_LENGTH 8192
Definition at line 10 of file cg_weapGfxParser.h.
MAX_TOKENSTRING_LENGTH
#define MAX_TOKENSTRING_LENGTH MAX_QPATH
Definition at line 11 of file cg_weapGfxParser.h.
TOKEN_CATEGORY
#define TOKEN_CATEGORY 21
Definition at line 34 of file cg_weapGfxParser.h.
TOKEN_CLOSEBLOCK
#define TOKEN_CLOSEBLOCK 2
Definition at line 15 of file cg_weapGfxParser.h.
TOKEN_CLOSERANGE
#define TOKEN_CLOSERANGE 6
Definition at line 19 of file cg_weapGfxParser.h.
TOKEN_CLOSEVECTOR
#define TOKEN_CLOSEVECTOR 4
Definition at line 17 of file cg_weapGfxParser.h.
TOKEN_COLON
#define TOKEN_COLON 13
Definition at line 26 of file cg_weapGfxParser.h.
TOKEN_EOF
#define TOKEN_EOF 0
Definition at line 13 of file cg_weapGfxParser.h.
TOKEN_EQUALS
#define TOKEN_EQUALS 11
Definition at line 24 of file cg_weapGfxParser.h.
TOKEN_FALSE
#define TOKEN_FALSE 15
Definition at line 28 of file cg_weapGfxParser.h.
TOKEN_FIELD
#define TOKEN_FIELD 20
Definition at line 33 of file cg_weapGfxParser.h.
TOKEN_FLOAT
#define TOKEN_FLOAT 18
Definition at line 31 of file cg_weapGfxParser.h.
TOKEN_IMPORT
#define TOKEN_IMPORT 7
Definition at line 20 of file cg_weapGfxParser.h.
TOKEN_INTEGER
#define TOKEN_INTEGER 17
Definition at line 30 of file cg_weapGfxParser.h.
TOKEN_NULL
#define TOKEN_NULL 16
Definition at line 29 of file cg_weapGfxParser.h.
TOKEN_OPENBLOCK
#define TOKEN_OPENBLOCK 1
Definition at line 14 of file cg_weapGfxParser.h.
TOKEN_OPENRANGE
#define TOKEN_OPENRANGE 5
Definition at line 18 of file cg_weapGfxParser.h.
TOKEN_OPENVECTOR
#define TOKEN_OPENVECTOR 3
Definition at line 16 of file cg_weapGfxParser.h.
TOKEN_PLUS
#define TOKEN_PLUS 12
Definition at line 25 of file cg_weapGfxParser.h.
TOKEN_PRIVATE
#define TOKEN_PRIVATE 10
Definition at line 23 of file cg_weapGfxParser.h.
TOKEN_PROTECTED
#define TOKEN_PROTECTED 9
Definition at line 22 of file cg_weapGfxParser.h.
TOKEN_PUBLIC
#define TOKEN_PUBLIC 8
Definition at line 21 of file cg_weapGfxParser.h.
TOKEN_STRING
#define TOKEN_STRING 19
Definition at line 32 of file cg_weapGfxParser.h.
TOKEN_TRUE
#define TOKEN_TRUE 14
Definition at line 27 of file cg_weapGfxParser.h.
TOKEN_WEAPON
#define TOKEN_WEAPON 22
Definition at line 35 of file cg_weapGfxParser.h.
Enumeration Type Documentation
cg_weapGfxAccessLvls_t
enum cg_weapGfxAccessLvls_t
Enumerator
LVL_PUBLIC
LVL_PROTECTED
LVL_PRIVATE
LVL_PUBLIC
LVL_PROTECTED
LVL_PRIVATE
Definition at line 88 of file cg_weapGfxParser.h.
 {LVL_PUBLIC,LVL_PROTECTED,LVL_PRIVATE}cg_weapGfxAccessLvls_t;
cg_weapGfxCategoryIndex_t
enum cg_weapGfxCategoryIndex_t
Enumerator
CAT_CHARGE
CAT_EXPLOSION
CAT_STRUGGLE
CAT_MISSILE
CAT_FLASH
CAT_TRAIL
CAT_HUD
CAT_CHARGE
CAT_EXPLOSION
CAT_STRUGGLE
CAT_MISSILE
CAT_FLASH
CAT_TRAIL
CAT_HUD
Definition at line 110 of file cg_weapGfxParser.h.
             {
     CAT_CHARGE,
     CAT_EXPLOSION,
     CAT_STRUGGLE,
     CAT_MISSILE,
     CAT_FLASH,
     CAT_TRAIL,
     CAT_HUD
 }cg_weapGfxCategoryIndex_t;
cg_weapGfxError_t
enum cg_weapGfxError_t
Enumerator
ERROR_FILE_NOTFOUND
ERROR_FILE_TOOBIG
ERROR_PREMATURE_EOF
ERROR_STRING_TOOBIG
ERROR_TOKEN_TOOBIG
ERROR_UNKNOWN_SYMBOL
ERROR_UNEXPECTED_SYMBOL
ERROR_STRING_EXPECTED
ERROR_INTEGER_EXPECTED
ERROR_FLOAT_EXPECTED
ERROR_IMPORTS_EXCEEDED
ERROR_IMPORT_REDEFINED
ERROR_IMPORT_DOUBLED
ERROR_IMPORT_UNDEFINED
ERROR_REDEFINE_IMPORT_AS_DEFINITION
ERROR_DEFINITIONS_EXCEEDED
ERROR_DEFINITION_REDEFINED
ERROR_DEFINITION_UNDEFINED
ERROR_LINK_BOUNDS
ERROR_LINK_REDEFINED
ERROR_FIELD_NOT_IN_CATEGORY
ERROR_INVERTED_RANGE
ERROR_OVER_MAXBOUND
ERROR_UNDER_MINBOUND
ERROR_OVER_MAXVECTORELEMS
ERROR_MAX_RECURSION
ERROR_INHERITING_PRIVATE
ERROR_IMPORTING_NON_PUBLIC
ERROR_OVERRIDING_WITH_HIGHER_ACCESS
ERROR_FILE_NOTFOUND
ERROR_FILE_TOOBIG
ERROR_PREMATURE_EOF
ERROR_STRING_TOOBIG
ERROR_TOKEN_TOOBIG
ERROR_UNKNOWN_SYMBOL
ERROR_UNEXPECTED_SYMBOL
ERROR_STRING_EXPECTED
ERROR_INTEGER_EXPECTED
ERROR_FLOAT_EXPECTED
ERROR_IMPORTS_EXCEEDED
ERROR_IMPORT_REDEFINED
ERROR_IMPORT_DOUBLED
ERROR_IMPORT_UNDEFINED
ERROR_REDEFINE_IMPORT_AS_DEFINITION
ERROR_DEFINITIONS_EXCEEDED
ERROR_DEFINITION_REDEFINED
ERROR_DEFINITION_UNDEFINED
ERROR_LINK_BOUNDS
ERROR_LINK_REDEFINED
ERROR_FIELD_NOT_IN_CATEGORY
ERROR_INVERTED_RANGE
ERROR_OVER_MAXBOUND
ERROR_UNDER_MINBOUND
ERROR_OVER_MAXVECTORELEMS
ERROR_MAX_RECURSION
ERROR_INHERITING_PRIVATE
ERROR_IMPORTING_NON_PUBLIC
ERROR_OVERRIDING_WITH_HIGHER_ACCESS
Definition at line 37 of file cg_weapGfxParser.h.
              {
     ERROR_FILE_NOTFOUND,
     ERROR_FILE_TOOBIG,
     ERROR_PREMATURE_EOF,
     ERROR_STRING_TOOBIG,
     ERROR_TOKEN_TOOBIG,
     ERROR_UNKNOWN_SYMBOL,
     ERROR_UNEXPECTED_SYMBOL,
     ERROR_STRING_EXPECTED,
     ERROR_INTEGER_EXPECTED,
     ERROR_FLOAT_EXPECTED,
     ERROR_IMPORTS_EXCEEDED,
     ERROR_IMPORT_REDEFINED,
     ERROR_IMPORT_DOUBLED,
     ERROR_IMPORT_UNDEFINED,
     ERROR_REDEFINE_IMPORT_AS_DEFINITION,
     ERROR_DEFINITIONS_EXCEEDED,
     ERROR_DEFINITION_REDEFINED,
     ERROR_DEFINITION_UNDEFINED,
     ERROR_LINK_BOUNDS,
     ERROR_LINK_REDEFINED,
     ERROR_FIELD_NOT_IN_CATEGORY,
     ERROR_INVERTED_RANGE,
     ERROR_OVER_MAXBOUND,
     ERROR_UNDER_MINBOUND,
     ERROR_OVER_MAXVECTORELEMS,
     ERROR_MAX_RECURSION,
     ERROR_INHERITING_PRIVATE,
     ERROR_IMPORTING_NON_PUBLIC,
     ERROR_OVERRIDING_WITH_HIGHER_ACCESS
 } cg_weapGfxError_t;
Function Documentation
CG_weapGfx_AddDefinitionRef()
qboolean CG_weapGfx_AddDefinitionRef (cg_weapGfxParser_t * parser, char * refname, char * pos, int line, cg_weapGfxAccessLvls_t accessLvl, qboolean hasSuper, char * supername)
Definition at line 141 of file cg_weapGfxAttributes.c.
{
     cg_weapGfxDefinitionRef_t   *defList;
     cg_weapGfxScanner_t         *scanner;
     int i;
     defList = parser->definitionRef;
     scanner = &parser->scanner;
     if ( CG_weapGfx_FindImportRef( parser, refname ) ) {
         CG_weapGfx_ErrorHandle( ERROR_REDEFINE_IMPORT_AS_DEFINITION, scanner, refname, NULL );
         return qfalse;
     }
     i = 0;
     while ( i < MAX_DEFINES ) {
         if ( defList[i].active ) {
             if ( !Q_stricmp( refname, defList[i].refname ) ) {
                 CG_weapGfx_ErrorHandle( ERROR_DEFINITION_REDEFINED, scanner, refname, NULL );
                 return qfalse;
             }
             i++;
         } else {
             break;
         }
     }
     if ( i == MAX_DEFINES ) {
         CG_weapGfx_ErrorHandle( ERROR_DEFINITIONS_EXCEEDED, scanner, NULL, NULL );
         return qfalse;
     }
     Q_strncpyz( defList[i].refname,   refname,   sizeof(defList[i].refname  ) );
     Q_strncpyz( defList[i].supername, supername, sizeof(defList[i].supername) );
     defList[i].accessLvl = accessLvl;
     defList[i].hasSuper = hasSuper;
     defList[i].active = qtrue;
     defList[i].scannerPos = pos;
     defList[i].scannerLine = line;
     // Handle some verbose output
     if ( cg_verboseParse.integer ) {
         CG_Printf("Added definition '%s' to attribute list.\n", defList[i].refname );
     }
     return qtrue;
 }
References cg_weapGfxDefinitionRef_t::accessLvl, cg_weapGfxDefinitionRef_t::active, CG_Printf(), cg_verboseParse, CG_weapGfx_ErrorHandle(), CG_weapGfx_FindImportRef(), cg_weapGfxParser_t::definitionRef, ERROR_DEFINITION_REDEFINED, ERROR_DEFINITIONS_EXCEEDED, ERROR_REDEFINE_IMPORT_AS_DEFINITION, cg_weapGfxDefinitionRef_t::hasSuper, vmCvar_t::integer, line, MAX_DEFINES, NULL, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, cg_weapGfxParser_t::scanner, cg_weapGfxDefinitionRef_t::scannerLine, and cg_weapGfxDefinitionRef_t::scannerPos.
Referenced by CG_weapGfx_PreParseDefinitions().
CG_weapGfx_AddImportRef()
qboolean CG_weapGfx_AddImportRef (cg_weapGfxParser_t * parser, char * refname, char * filename, char * defname)
Definition at line 46 of file cg_weapGfxAttributes.c.
{
     cg_weapGfxImportRef_t   *importList;
     cg_weapGfxScanner_t     *scanner;
     int i;
     importList = parser->importRef;
     scanner = &parser->scanner;
     i = 0;
     while ( i < MAX_IMPORTS ) {
         if ( importList[i].active ) {
             if ( !Q_stricmp( refname, importList[i].refname ) ) {
                 CG_weapGfx_ErrorHandle( ERROR_IMPORT_REDEFINED, scanner, refname, NULL );
                 return qfalse;
             }
             if ( !Q_stricmp( filename, importList[i].filename ) && !Q_stricmp( defname, importList[i].defname ) ) {
                 CG_weapGfx_ErrorHandle( ERROR_IMPORT_DOUBLED, scanner, refname, NULL );
                 return qfalse;
             }
             i++;
         } else {
             break;
         }
     }
     if ( i == MAX_IMPORTS ) {
         CG_weapGfx_ErrorHandle( ERROR_IMPORTS_EXCEEDED, scanner, NULL, NULL );
         return qfalse;
     }
     Q_strncpyz( importList[i].refname,  refname,  sizeof(importList[i].refname ) );
     Q_strncpyz( importList[i].filename, filename, sizeof(importList[i].filename) );
     Q_strncpyz( importList[i].defname,  defname,  sizeof(importList[i].defname ) );
     importList[i].active = qtrue;
     // Handle some verbose output
     if ( cg_verboseParse.integer ) {
         CG_Printf("Added import '%s' to attribute list.\n", importList[i].refname );
     }
     return qtrue;
 }
References cg_weapGfxImportRef_t::active, CG_Printf(), cg_verboseParse, CG_weapGfx_ErrorHandle(), ERROR_IMPORT_DOUBLED, ERROR_IMPORT_REDEFINED, ERROR_IMPORTS_EXCEEDED, cg_weapGfxParser_t::importRef, vmCvar_t::integer, MAX_IMPORTS, NULL, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, and cg_weapGfxParser_t::scanner.
Referenced by CG_weapGfx_ParseImports().
CG_weapGfx_AddLinkRef()
qboolean CG_weapGfx_AddLinkRef (cg_weapGfxParser_t * parser, int index, char * pri_refname, char * sec_refname)
Definition at line 200 of file cg_weapGfxAttributes.c.
{
     cg_weapGfxLinkRef_t *linkList;
     cg_weapGfxScanner_t *scanner;
     int true_index;
     linkList = parser->linkRef;
     scanner = &parser->scanner;
     true_index = index - 1; // The script parses 1 as the first weapon, but arrays start at 0.
     if ( ( true_index < 0 ) || ( true_index > MAX_LINKS ) ) {
         CG_weapGfx_ErrorHandle( ERROR_LINK_BOUNDS, scanner, NULL, NULL );
         return qfalse;
     }
     if ( linkList[true_index].active ) {
         CG_weapGfx_ErrorHandle( ERROR_LINK_REDEFINED, scanner, NULL, NULL );
         return qfalse;
     }
     Q_strncpyz( linkList[true_index].pri_refname,  pri_refname,  sizeof(linkList[true_index].pri_refname ) );
     Q_strncpyz( linkList[true_index].sec_refname,  sec_refname,  sizeof(linkList[true_index].sec_refname ) );
     linkList[true_index].active = qtrue;
         // Handle some verbose output
     if ( cg_verboseParse.integer ) {
         if ( !strcmp( linkList[true_index].sec_refname, "" ) ) {
             CG_Printf("Added link '%s' to attribute list.\n", linkList[true_index].pri_refname );
         } else {
             CG_Printf("Added link '%s | %s' to attribute list.\n", linkList[true_index].pri_refname, linkList[true_index].sec_refname );
         }
     }
     return qtrue;
 }
References cg_weapGfxLinkRef_t::active, CG_Printf(), cg_verboseParse, CG_weapGfx_ErrorHandle(), ERROR_LINK_BOUNDS, ERROR_LINK_REDEFINED, vmCvar_t::integer, cg_weapGfxParser_t::linkRef, MAX_LINKS, NULL, Q_strncpyz(), qfalse, qtrue, and cg_weapGfxParser_t::scanner.
Referenced by CG_weapGfx_ParseLinks().
CG_weapGfx_CheckPrematureEOF()
qboolean CG_weapGfx_CheckPrematureEOF (cg_weapGfxScanner_t * scanner, cg_weapGfxToken_t * token)
Definition at line 292 of file cg_weapGfxScanner.c.
{
     if(CG_weapGfx_NextSym(scanner,token)){return qtrue;}
     return token->tokenSym == TOKEN_EOF ? CG_weapGfx_ErrorHandle(ERROR_PREMATURE_EOF,scanner,NULL,NULL) : qfalse;
 }
References CG_weapGfx_ErrorHandle(), CG_weapGfx_NextSym(), ERROR_PREMATURE_EOF, NULL, qfalse, qtrue, and TOKEN_EOF.
CG_weapGfx_ErrorHandle()
qboolean CG_weapGfx_ErrorHandle (cg_weapGfxError_t errorNr, cg_weapGfxScanner_t * scanner, char * string1, char * string2)
Definition at line 35 of file cg_weapGfxScanner.c.
{
     char* file = scanner->filename;
     // <-- Internally we start from 0, for the user we start from 1
     int line = scanner->line + 1;
     if(errorNr == ERROR_FILE_NOTFOUND){CG_Printf("%s: File not found.\n",file);}
     else if(errorNr == ERROR_FILE_TOOBIG){CG_Printf("%s: File exceeds maximum script length.\n",file);}
     else if(errorNr == ERROR_PREMATURE_EOF){CG_Printf("%s(%i): Premature end of file.\n",file,line);}
     else if(errorNr == ERROR_STRING_TOOBIG){CG_Printf("%s(%i): String exceeds limit of %i characters.\n",file,line,MAX_TOKENSTRING_LENGTH);}
     else if(errorNr == ERROR_TOKEN_TOOBIG){CG_Printf("%s(%i): Symbol exceeds limit of %i characters.\n",file,line,MAX_TOKENSTRING_LENGTH);}
     else if(errorNr == ERROR_UNKNOWN_SYMBOL){CG_Printf("%s(%i): Unknown symbol '%s' encountered.\n",file,line,string1);}
     else if(errorNr == ERROR_UNEXPECTED_SYMBOL){
         if(!string2){CG_Printf("%s(%i): Unexpected symbol '%s' found.\n",file,line,string1);}
         else{CG_Printf("%s(%i): Unexpected symbol '%s' found, expected '%s'.\n",file,line,string1,string2);}
     }
     else if(errorNr == ERROR_STRING_EXPECTED){CG_Printf("%s(%i): String expected. '%s' is not a string or is missing quotes.\n",file,line,string1);}
     else if(errorNr == ERROR_INTEGER_EXPECTED){CG_Printf("%s(%i): Integer expected, but '%s' found.\n",file,line,string1);}
     else if(errorNr == ERROR_FLOAT_EXPECTED){CG_Printf("%s(%i): Float or integer expected, but '%s' found.\n",file,line,string1);}
     else if(errorNr == ERROR_IMPORTS_EXCEEDED){CG_Printf("%s(%i): Trying to exceed maximum number of %i imports.\n",file,line,MAX_IMPORTS);}
     else if(errorNr == ERROR_IMPORT_REDEFINED){CG_Printf("%s(%i): Trying to redefine previously defined import definition '%s'.\n",file,line,string1);}
     else if(errorNr == ERROR_IMPORT_DOUBLED){CG_Printf("%s(%i): Trying to duplicate a previously imported definition under the new name '%s'.\n",file,line,string1);}
     else if(errorNr == ERROR_IMPORT_UNDEFINED){CG_Printf("%s(%i): Undefined import '%s' being referenced.\n",file,line,string1);}
     else if(errorNr == ERROR_DEFINITIONS_EXCEEDED){CG_Printf("%s(%i): Trying to exceed maximum number of %i weapon definitions.\n",file,line,MAX_DEFINES);}
     else if(errorNr == ERROR_DEFINITION_REDEFINED){CG_Printf("%s(%i): Trying to redefine previously defined weapon definition '%s'.\n",file,line,string1);}
     else if(errorNr == ERROR_DEFINITION_UNDEFINED){CG_Printf("%s(%i): Undefined weapon definition '%s' being referenced.\n",file,line,string1);}
     else if(errorNr == ERROR_REDEFINE_IMPORT_AS_DEFINITION){CG_Printf("%s(%i): Trying to redefine previously defined import definition '%s' as a local weapon definition.\n",file,line,string1);}
     else if(errorNr == ERROR_LINK_BOUNDS){CG_Printf("%s(%i): Weapon link out of bounds. Must be in range [1..6].\n",file,line);}
     else if(errorNr == ERROR_LINK_REDEFINED){CG_Printf("%s(%i): Trying to redefine a previously defined weapon link number.\n",file,line);}
     else if(errorNr == ERROR_FIELD_NOT_IN_CATEGORY){CG_Printf("%s(%i): Field '%s' is not supported by category '%s'.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_INVERTED_RANGE){CG_Printf("%s(%i): This range doesn't allow end value '%s' to be larger than start value '%s'.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_OVER_MAXBOUND){CG_Printf("%s(%i): Value '%s' is larger than maximum bound of %s.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_UNDER_MINBOUND){CG_Printf("%s(%i): Value '%s' is smaller than minimum bound of %s.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_OVER_MAXVECTORELEMS){CG_Printf("%s(%i): Element '%s' exceeds maximum storage capacity of %s elements in vector.\n",file,line,string1,string2);}
     else if(errorNr == ERROR_MAX_RECURSION){CG_Printf("%s: Compiler is trying to read beyond maximum recursion depth %i for overriding.\n",file,MAX_RECURSION_DEPTH);}
     else if(errorNr == ERROR_INHERITING_PRIVATE){CG_Printf("%s: Private definition '%s' can not be inherited.\n",file,string1);}
     else if(errorNr == ERROR_IMPORTING_NON_PUBLIC){CG_Printf("%s: Non-public definition '%s' can not be imported for local use.\n",file,string1);}
     else if(errorNr == ERROR_OVERRIDING_WITH_HIGHER_ACCESS){CG_Printf("%s: Definition '%s' may not be declared with higher access than its superclass.\n",file,string1);}
     else{CG_Printf("WEAPONSCRIPT ERROR: Unknown error occured.\n");}
     return qfalse;
 }
References CG_Printf(), ERROR_DEFINITION_REDEFINED, ERROR_DEFINITION_UNDEFINED, ERROR_DEFINITIONS_EXCEEDED, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, ERROR_FLOAT_EXPECTED, ERROR_IMPORT_DOUBLED, ERROR_IMPORT_REDEFINED, ERROR_IMPORT_UNDEFINED, ERROR_IMPORTING_NON_PUBLIC, ERROR_IMPORTS_EXCEEDED, ERROR_INHERITING_PRIVATE, ERROR_INTEGER_EXPECTED, ERROR_INVERTED_RANGE, ERROR_LINK_BOUNDS, ERROR_LINK_REDEFINED, ERROR_MAX_RECURSION, ERROR_OVER_MAXBOUND, ERROR_OVER_MAXVECTORELEMS, ERROR_OVERRIDING_WITH_HIGHER_ACCESS, ERROR_PREMATURE_EOF, ERROR_REDEFINE_IMPORT_AS_DEFINITION, ERROR_STRING_EXPECTED, ERROR_STRING_TOOBIG, ERROR_TOKEN_TOOBIG, ERROR_UNDER_MINBOUND, ERROR_UNEXPECTED_SYMBOL, ERROR_UNKNOWN_SYMBOL, cg_weapGfxScanner_t::filename, cg_weapGfxScanner_t::line, line, MAX_DEFINES, MAX_IMPORTS, MAX_RECURSION_DEPTH, MAX_TOKENSTRING_LENGTH, and qfalse.
Referenced by CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_LoadFile(), and CG_weapGfx_NextSym().
CG_weapGfx_FindDefinitionRef()
int CG_weapGfx_FindDefinitionRef (cg_weapGfxParser_t * parser, char * refname)
Definition at line 104 of file cg_weapGfxAttributes.c.
{
     cg_weapGfxDefinitionRef_t   *defList;
     cg_weapGfxScanner_t         *scanner;
     int i;
     int retval;
     defList = parser->definitionRef;
     scanner = &parser->scanner;
     for ( i = 0; i < MAX_DEFINES; i++ ) {
         if ( !defList[i].active ) {
             break;
         }
         if ( !Q_stricmp( refname, defList[i].refname ) ) {
             return i + 1;
         }
     }
     retval = CG_weapGfx_FindImportRef( parser, refname );
     if ( !retval ) {
         CG_weapGfx_ErrorHandle( ERROR_DEFINITION_UNDEFINED, scanner, refname, NULL );
         return qfalse;
     } else {
         return retval + MAX_DEFINES; // So we can seperate a local ref from an import
     }
 }
References CG_weapGfx_ErrorHandle(), CG_weapGfx_FindImportRef(), cg_weapGfxParser_t::definitionRef, ERROR_DEFINITION_UNDEFINED, MAX_DEFINES, NULL, Q_stricmp(), qfalse, and cg_weapGfxParser_t::scanner.
Referenced by CG_weapGfx_ParseDefinition(), CG_weapGfx_ParseLinks(), CG_weapGfx_ParseRemoteDefinition(), and CG_weapGfx_PreParseDefinitions().
CG_weapGfx_FindImportRef()
int CG_weapGfx_FindImportRef (cg_weapGfxParser_t * parser, char * refname)
Definition at line 16 of file cg_weapGfxAttributes.c.
{
     cg_weapGfxImportRef_t   *importList;
     cg_weapGfxScanner_t     *scanner;
     int i;
     importList = parser->importRef;
     scanner = &parser->scanner;
     for ( i = 0; i < MAX_IMPORTS; i++ ) {
         if ( !importList[i].active ) {
             return qfalse;
         }
         if ( !Q_stricmp( refname, importList[i].refname ) ) {
             return i + 1;
         }
     }
     return qfalse;
 }
References cg_weapGfxParser_t::importRef, MAX_IMPORTS, Q_stricmp(), qfalse, and cg_weapGfxParser_t::scanner.
Referenced by CG_weapGfx_AddDefinitionRef(), and CG_weapGfx_FindDefinitionRef().
CG_weapGfx_LoadFile()
qboolean CG_weapGfx_LoadFile (cg_weapGfxScanner_t * scanner, char * filename)
Definition at line 296 of file cg_weapGfxScanner.c.
{
     int len;
     qhandle_t file;
     Q_strncpyz(scanner->filename,filename,sizeof(scanner->filename));
     len = trap_FS_FOpenFile( filename, &file, FS_READ );
     if(!file){
         return CG_weapGfx_ErrorHandle(ERROR_FILE_NOTFOUND,scanner,filename,NULL);
     }
     if(len >= sizeof(char) * MAX_SCRIPT_LENGTH - 1){
         trap_FS_FCloseFile(file);
         return CG_weapGfx_ErrorHandle(ERROR_FILE_TOOBIG,scanner,NULL,NULL);
     }
     trap_FS_Read(scanner->script,len,file);
     trap_FS_FCloseFile(file);
     scanner->script[len] = '\0';
     scanner->line = 0;
     scanner->pos = scanner->script;
     if(cg_verboseParse.integer){
         CG_Printf("Scriptfile '%s' has been read into memory.\n",filename);
     }
     return qtrue;
 }
References CG_Printf(), cg_verboseParse, CG_weapGfx_ErrorHandle(), ERROR_FILE_NOTFOUND, ERROR_FILE_TOOBIG, file, cg_weapGfxScanner_t::filename, FS_READ, vmCvar_t::integer, cg_weapGfxScanner_t::line, MAX_SCRIPT_LENGTH, NULL, cg_weapGfxScanner_t::pos, Q_strncpyz(), qtrue, cg_weapGfxScanner_t::script, trap_FS_FCloseFile(), trap_FS_FOpenFile(), and trap_FS_Read().
CG_weapGfx_NextSym()
qboolean CG_weapGfx_NextSym (cg_weapGfxScanner_t * scanner, cg_weapGfxToken_t * token)
Definition at line 74 of file cg_weapGfxScanner.c.
{
     // Skip non-relevant characters
     while(1){
         // Leading whitespace
         while(*scanner->pos <= ' '){
             if(!*scanner->pos){break;}
             if(*scanner->pos == '\n'){scanner->line++;}
             scanner->pos++;
         }
         if(scanner->pos[0] == '/' && scanner->pos[1] == '/' ) {
             scanner->pos += 2;
             while(*scanner->pos && *scanner->pos != '\n') {
                 scanner->pos++;
             }
         }
         else if(scanner->pos[0] == '/' && scanner->pos[1] == '*'){
             scanner->pos += 2;
             while(*scanner->pos && (scanner->pos[0] != '*' || scanner->pos[1] != '/')){
                 scanner->pos++;
             }
             if(*scanner->pos){scanner->pos += 2;}
         }
         else{break;}
     }
     if(*scanner->pos == '\"'){
         int len = 0;
         scanner->pos++;
         while(1){
             if(!(*scanner->pos)){
                 return CG_weapGfx_ErrorHandle(ERROR_PREMATURE_EOF,scanner,NULL,NULL);
             }
             if(*scanner->pos == '\n'){scanner->line++;}
             if(*scanner->pos == '\"') {
                 scanner->pos++;
                 break;
             }
             if(len < MAX_TOKENSTRING_LENGTH-1 && *scanner->pos >= ' '){
                 token->stringval[len] = *scanner->pos;
                 len++;
             }
             else{
                 return CG_weapGfx_ErrorHandle(ERROR_STRING_TOOBIG,scanner,NULL,NULL);
             }
             scanner->pos++;
         }
         token->stringval[len] = '\0';
         token->tokenSym = TOKEN_STRING;
         return qtrue;
     }
     if(*scanner->pos >= '0' && *scanner->pos <= '9'){
         int len = 0;
         qboolean dot = qfalse;
         do{
             if(len < (MAX_TOKENSTRING_LENGTH-1)){
                 token->stringval[len] = *scanner->pos;
                 len++;
             }
             else{
                 return CG_weapGfx_ErrorHandle(ERROR_TOKEN_TOOBIG,scanner,NULL,NULL);
             }
             scanner->pos++;
             if(*scanner->pos == '.' && !dot){
                 dot = qtrue;
                 if(len < MAX_TOKENSTRING_LENGTH-1){
                     token->stringval[len] = *scanner->pos;
                     len++;
                 }
                 else{
                     return CG_weapGfx_ErrorHandle(ERROR_TOKEN_TOOBIG,scanner,NULL,NULL);
                 }
                 scanner->pos++;
             }
         }
         while(*scanner->pos >= '0' && *scanner->pos <= '9');
         token->tokenSym = dot ? TOKEN_FLOAT : TOKEN_INTEGER;
         token->stringval[len] = '\0';
         token->floatval = atof(token->stringval);
         token->intval = ceil(token->floatval);
         return qtrue;
     }
     switch(*scanner->pos){
         case '=':
             scanner->pos++;
             token->stringval[0] = '=';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_EQUALS;
             return qtrue;
         break;
         case '+':
             scanner->pos++;
             token->stringval[0] = '+';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_PLUS;
             return qtrue;
         break;
         case '|':
             scanner->pos++;
             token->stringval[0] = '|';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_COLON;
             return qtrue;
         break;
         case '{':
             scanner->pos++;
             token->stringval[0] = '{';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_OPENBLOCK;
             return qtrue;
         break;
         case '}':
             scanner->pos++;
             token->stringval[0] = '}';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_CLOSEBLOCK;
             return qtrue;
         break;
         case '(':
             scanner->pos++;
             token->stringval[0] = '(';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_OPENVECTOR;
             return qtrue;
         break;
         case ')':
             scanner->pos++;
             token->stringval[0] = ')';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_CLOSEVECTOR;
             return qtrue;
         break;
         case '[':
             scanner->pos++;
             token->stringval[0] = '[';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_OPENRANGE;
             return qtrue;
         break;
         case ']':
             scanner->pos++;
             token->stringval[0] = ']';
             token->stringval[1] = '\0';
             token->tokenSym = TOKEN_CLOSERANGE;
             return qtrue;
         break;
     }
     // Handle keywords
     {
         int len = 0;
         int i;
         while(*scanner->pos >= 'a' && *scanner->pos <= 'z' || *scanner->pos >= 'A' && *scanner->pos <= 'Z'){
             if(len > MAX_TOKENSTRING_LENGTH-1){
                 return CG_weapGfx_ErrorHandle(ERROR_TOKEN_TOOBIG,scanner,NULL,NULL);
             }
             token->stringval[len] = *scanner->pos;
             len++;
             scanner->pos++;
         }
         token->stringval[len] = '\0';
         // Check if the keyword is a category.
         for(i=0;strcmp(cg_weapGfxCategories[i],"");i++){
             if(!Q_stricmp(cg_weapGfxCategories[i],token->stringval)){
                 token->identifierIndex = i;
                 token->tokenSym = TOKEN_CATEGORY;
                 return qtrue;
             }
         }
         // Check if the keyword is a field.
         for(i=0;strcmp(cg_weapGfxFields[i].fieldname,"");i++){
             // NOTE:
             // Need to do this comparison case independantly. Q_stricmp is case
             // independant, so use this instead of standard library function strcmp.
             if(!Q_stricmp(cg_weapGfxFields[i].fieldname,token->stringval)){
                 token->identifierIndex = i;
                 token->tokenSym = TOKEN_FIELD;
                 return qtrue;
             }
         }
         // Check if the keyword is 'import', 'private', 'protected', 'public',
         // 'weapon', 'true', 'false', or 'null'.
         if(!Q_stricmp(token->stringval,"import")){
             token->tokenSym = TOKEN_IMPORT;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"private")){
             token->tokenSym = TOKEN_PRIVATE;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"protected")){
             token->tokenSym = TOKEN_PROTECTED;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"public")){
             token->tokenSym = TOKEN_PUBLIC;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"weapon")){
             token->tokenSym = TOKEN_WEAPON;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"true")){
             token->tokenSym = TOKEN_TRUE;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"false")){
             token->tokenSym = TOKEN_FALSE;
             return qtrue;
         }
         if(!Q_stricmp(token->stringval,"null")){
             token->tokenSym = TOKEN_NULL;
             return qtrue;
         }
     }
     if(*scanner->pos == '\0'){
         token->tokenSym = TOKEN_EOF;
         return qfalse;
     }
     return CG_weapGfx_ErrorHandle(ERROR_UNKNOWN_SYMBOL,scanner,token->stringval,NULL);
 }
References CG_weapGfx_ErrorHandle(), cg_weapGfxCategories, cg_weapGfxFields, ERROR_PREMATURE_EOF, ERROR_STRING_TOOBIG, ERROR_TOKEN_TOOBIG, ERROR_UNKNOWN_SYMBOL, cg_weapGfxScanner_t::line, MAX_TOKENSTRING_LENGTH, NULL, cg_weapGfxScanner_t::pos, Q_stricmp(), qfalse, qtrue, TOKEN_CATEGORY, TOKEN_CLOSEBLOCK, TOKEN_CLOSERANGE, TOKEN_CLOSEVECTOR, TOKEN_COLON, TOKEN_EOF, TOKEN_EQUALS, TOKEN_FALSE, TOKEN_FIELD, TOKEN_FLOAT, TOKEN_IMPORT, TOKEN_INTEGER, TOKEN_NULL, TOKEN_OPENBLOCK, TOKEN_OPENRANGE, TOKEN_OPENVECTOR, TOKEN_PLUS, TOKEN_PRIVATE, TOKEN_PROTECTED, TOKEN_PUBLIC, TOKEN_STRING, TOKEN_TRUE, and TOKEN_WEAPON.
Referenced by CG_weapGfx_CheckPrematureEOF().
CG_weapGfx_ParseAnimationRange()
qboolean CG_weapGfx_ParseAnimationRange (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 173 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_CHARGE){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_INTEGER){
         if(token->intval > 100){return CG_weapGfx_ErrorHandle(ERROR_OVER_MAXBOUND,scanner,token->stringval,"100");}
         if(token->intval < 0){return CG_weapGfx_ErrorHandle(ERROR_UNDER_MINBOUND,scanner,token->stringval,"0");}
         cg_weapGfxBuffer.chargeStartPct = token->intval;
         cg_weapGfxBuffer.chargeEndPct = token->intval;
     }
     else if(token->tokenSym == TOKEN_OPENRANGE){
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         if(token->tokenSym != TOKEN_INTEGER){
             return CG_weapGfx_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
         }
         if(token->intval > 100){return CG_weapGfx_ErrorHandle(ERROR_OVER_MAXBOUND,scanner,token->stringval,"100");}
         if(token->intval < 0){return CG_weapGfx_ErrorHandle(ERROR_UNDER_MINBOUND,scanner,token->stringval,"0");}
         cg_weapGfxBuffer.chargeStartPct = token->intval;
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         if(token->tokenSym != TOKEN_INTEGER){return CG_weapGfx_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);}
         // NOTE: This is the only range that must NOT be inverted.
         if(token->intval < cg_weapGfxBuffer.chargeStartPct){
             return CG_weapGfx_ErrorHandle(ERROR_INVERTED_RANGE,scanner,token->stringval,va("%d",cg_weapGfxBuffer.chargeStartPct));
         }
         if(token->intval > 100){return CG_weapGfx_ErrorHandle(ERROR_OVER_MAXBOUND,scanner,token->stringval,"100");}
         if(token->intval < 0){return CG_weapGfx_ErrorHandle(ERROR_UNDER_MINBOUND,scanner,token->stringval,"0");}
         cg_weapGfxBuffer.chargeEndPct = token->intval;
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         if(token->tokenSym != TOKEN_CLOSERANGE){
             return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,"]");
         }
     }
     else{
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,NULL);
     }
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeEndPct, cg_userWeaponParseBuffer_t::chargeStartPct, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, ERROR_INVERTED_RANGE, ERROR_OVER_MAXBOUND, ERROR_UNDER_MINBOUND, ERROR_UNEXPECTED_SYMBOL, NULL, qfalse, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_CLOSERANGE, TOKEN_INTEGER, TOKEN_OPENRANGE, and va().
CG_weapGfx_ParseDisplayName()
qboolean CG_weapGfx_ParseDisplayName (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 706 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_HUD){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(cg_weapGfxBuffer.weaponName,token->stringval,sizeof(cg_weapGfxBuffer.missileTrailSpiralShader));
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_HUD, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::missileTrailSpiralShader, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, TOKEN_STRING, and cg_userWeaponParseBuffer_t::weaponName.
CG_weapGfx_ParseDlight()
qboolean CG_weapGfx_ParseDlight (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 257 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     float* floatField;
     vec3_t* colorField;
     vec3_t RGB;
     int channel;
     if(category != CAT_CHARGE && category != CAT_EXPLOSION && category != CAT_MISSILE && category != CAT_FLASH){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym != TOKEN_OPENVECTOR){
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,"(");
     }
     if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
     for(channel=0;channel<3;++channel){
         if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
             return CG_weapGfx_ErrorHandle(ERROR_FLOAT_EXPECTED,scanner,token->stringval,NULL);
         }
         if(token->floatval > 1.0f){return CG_weapGfx_ErrorHandle(ERROR_OVER_MAXBOUND,scanner,token->stringval,"1.0");}
         if(token->floatval < 0.0f){return CG_weapGfx_ErrorHandle(ERROR_UNDER_MINBOUND,scanner,token->stringval,"0.0");}
         RGB[channel] = token->floatval;
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
     }
     if(token->tokenSym != TOKEN_CLOSEVECTOR){
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,")");
     }
     if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
     if(category == CAT_CHARGE){
         if(token->tokenSym == TOKEN_INTEGER || token->tokenSym == TOKEN_FLOAT){
             cg_weapGfxBuffer.chargeDlightStartRadius = token->floatval;
             cg_weapGfxBuffer.chargeDlightEndRadius = token->floatval;
         }
         else if(token->tokenSym == TOKEN_OPENRANGE){
             int range;
             if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
             for(range=0;range<2;++range){
                 floatField = range == 0 ? &cg_weapGfxBuffer.chargeDlightStartRadius : &cg_weapGfxBuffer.chargeDlightEndRadius;
                 if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
                     return CG_weapGfx_ErrorHandle(ERROR_FLOAT_EXPECTED,scanner,token->stringval,NULL);
                 }
                 *floatField = token->floatval;
                 if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
             }
             if(token->tokenSym != TOKEN_CLOSERANGE){
                 return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,"]");
             }
         }
         else{
             return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,NULL);
         }
         VectorCopy(RGB,cg_weapGfxBuffer.chargeDlightColor);
     }
     else{
         if(category == CAT_EXPLOSION){
             floatField = &cg_weapGfxBuffer.explosionDlightRadius;
             colorField = &cg_weapGfxBuffer.explosionDlightColor;
         }
         else if(category == CAT_MISSILE){
             floatField = &cg_weapGfxBuffer.missileDlightRadius;
             colorField = &cg_weapGfxBuffer.missileDlightColor;
         }
         else if(category == CAT_FLASH){
             floatField = &cg_weapGfxBuffer.flashDlightRadius;
             colorField = &cg_weapGfxBuffer.flashDlightColor;
         }
         if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
             return CG_weapGfx_ErrorHandle(ERROR_FLOAT_EXPECTED,scanner,token->stringval,NULL);
         }
         *floatField = token->floatval;
         VectorCopy(RGB,*colorField);
     }
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CAT_EXPLOSION, CAT_FLASH, CAT_MISSILE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeDlightColor, cg_userWeaponParseBuffer_t::chargeDlightEndRadius, cg_userWeaponParseBuffer_t::chargeDlightStartRadius, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FLOAT_EXPECTED, ERROR_OVER_MAXBOUND, ERROR_UNDER_MINBOUND, ERROR_UNEXPECTED_SYMBOL, cg_userWeaponParseBuffer_t::explosionDlightColor, cg_userWeaponParseBuffer_t::explosionDlightRadius, cg_userWeaponParseBuffer_t::flashDlightColor, cg_userWeaponParseBuffer_t::flashDlightRadius, cg_userWeaponParseBuffer_t::missileDlightColor, cg_userWeaponParseBuffer_t::missileDlightRadius, NULL, qfalse, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_CLOSERANGE, TOKEN_CLOSEVECTOR, TOKEN_FLOAT, TOKEN_INTEGER, TOKEN_OPENRANGE, TOKEN_OPENVECTOR, and VectorCopy.
CG_weapGfx_ParseDummy()
qboolean CG_weapGfx_ParseDummy (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 104 of file cg_weapGfxParser.c.
 {return qfalse;}
References qfalse.
CG_weapGfx_ParseDuration()
qboolean CG_weapGfx_ParseDuration (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 514 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_EXPLOSION){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym != TOKEN_INTEGER){
         return CG_weapGfx_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
     }
     cg_weapGfxBuffer.explosionTime = token->intval;
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_EXPLOSION, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, cg_userWeaponParseBuffer_t::explosionTime, NULL, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, and TOKEN_INTEGER.
CG_weapGfx_ParseIcon()
qboolean CG_weapGfx_ParseIcon (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 690 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_HUD){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(cg_weapGfxBuffer.weaponIcon,token->stringval,sizeof(cg_weapGfxBuffer.missileTrailSpiralShader));
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_HUD, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::missileTrailSpiralShader, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, TOKEN_STRING, and cg_userWeaponParseBuffer_t::weaponIcon.
CG_weapGfx_ParseLoopFx()
qboolean CG_weapGfx_ParseLoopFx (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 443 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     char* sound;
     if(category == CAT_CHARGE){sound = cg_weapGfxBuffer.chargeLoopSound;}
     else if(category == CAT_MISSILE){sound = cg_weapGfxBuffer.missileSound;}
     else if(category == CAT_FLASH){sound = cg_weapGfxBuffer.firingSound;}
     else{
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(sound,token->stringval,MAX_QPATH);
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CAT_FLASH, CAT_MISSILE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeLoopSound, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::firingSound, MAX_QPATH, cg_userWeaponParseBuffer_t::missileSound, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseLoopParticles()
qboolean CG_weapGfx_ParseLoopParticles (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 609 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     char* systemField;
     if(category == CAT_CHARGE){systemField = cg_weapGfxBuffer.chargeParticleSystem;}
     else if(category == CAT_FLASH){systemField = cg_weapGfxBuffer.firingParticleSystem;}
     else{
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(systemField,token->stringval,MAX_QPATH);
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CAT_FLASH, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeParticleSystem, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::firingParticleSystem, MAX_QPATH, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseMarkShader()
qboolean CG_weapGfx_ParseMarkShader (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 551 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_EXPLOSION){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(cg_weapGfxBuffer.markShader,token->stringval,sizeof(cg_weapGfxBuffer.markShader));
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_EXPLOSION, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::markShader, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseMarkSize()
qboolean CG_weapGfx_ParseMarkSize (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 567 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_EXPLOSION){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
         return CG_weapGfx_ErrorHandle(ERROR_FLOAT_EXPECTED,scanner,token->stringval,NULL);
     }
     cg_weapGfxBuffer.markSize = token->floatval;
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_EXPLOSION, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FLOAT_EXPECTED, cg_userWeaponParseBuffer_t::markSize, NULL, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_FLOAT, and TOKEN_INTEGER.
CG_weapGfx_ParseModel()
qboolean CG_weapGfx_ParseModel (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 106 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     char* weaponField;
     if(category == CAT_CHARGE){weaponField = cg_weapGfxBuffer.chargeModel;}
     else if(category == CAT_EXPLOSION){weaponField = cg_weapGfxBuffer.explosionModel;}
     else if(category == CAT_STRUGGLE){weaponField = cg_weapGfxBuffer.missileStruggleModel;}
     else if(category == CAT_MISSILE){weaponField = cg_weapGfxBuffer.missileModel;}
     else if(category == CAT_FLASH){weaponField = cg_weapGfxBuffer.flashModel;}
     else{
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(weaponField,token->stringval,MAX_QPATH);
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CAT_EXPLOSION, CAT_FLASH, CAT_MISSILE, CAT_STRUGGLE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeModel, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::explosionModel, cg_userWeaponParseBuffer_t::flashModel, MAX_QPATH, cg_userWeaponParseBuffer_t::missileModel, cg_userWeaponParseBuffer_t::missileStruggleModel, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseOnceFx()
qboolean CG_weapGfx_ParseOnceFx (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 498 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_FLASH){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(cg_weapGfxBuffer.flashOnceSound,token->stringval,sizeof(cg_weapGfxBuffer.flashOnceSound));
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_FLASH, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::flashOnceSound, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseParticles()
qboolean CG_weapGfx_ParseParticles (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 628 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     char* systemField;
     if(category == CAT_EXPLOSION){systemField = cg_weapGfxBuffer.explosionParticleSystem;}
     else if(category == CAT_MISSILE){systemField = cg_weapGfxBuffer.missileParticleSystem;}
     else if(category == CAT_FLASH){systemField = cg_weapGfxBuffer.flashParticleSystem;}
     else{
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(systemField,token->stringval,MAX_QPATH);
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_EXPLOSION, CAT_FLASH, CAT_MISSILE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::explosionParticleSystem, cg_userWeaponParseBuffer_t::flashParticleSystem, MAX_QPATH, cg_userWeaponParseBuffer_t::missileParticleSystem, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseRockDebris()
qboolean CG_weapGfx_ParseRockDebris (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 580 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_EXPLOSION){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
         return CG_weapGfx_ErrorHandle(ERROR_FLOAT_EXPECTED,scanner,token->stringval,NULL);
     }
     cg_weapGfxBuffer.noRockDebris = token->intval;
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_EXPLOSION, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FLOAT_EXPECTED, cg_userWeaponParseBuffer_t::noRockDebris, NULL, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_FLOAT, and TOKEN_INTEGER.
CG_weapGfx_ParseShader()
qboolean CG_weapGfx_ParseShader (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 150 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     char* weaponField;
     if(category == CAT_CHARGE){weaponField = cg_weapGfxBuffer.chargeShader;}
     else if(category == CAT_EXPLOSION){weaponField = cg_weapGfxBuffer.explosionShader;}
     else if(category == CAT_STRUGGLE){weaponField = cg_weapGfxBuffer.missileStruggleShader;}
     else if(category == CAT_MISSILE){weaponField = cg_weapGfxBuffer.missileShader;}
     else if(category == CAT_FLASH){weaponField = cg_weapGfxBuffer.flashShader;}
     else if(category == CAT_TRAIL){weaponField = cg_weapGfxBuffer.missileTrailShader;}
     else{
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(weaponField,token->stringval,MAX_QPATH);
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CAT_EXPLOSION, CAT_FLASH, CAT_MISSILE, CAT_STRUGGLE, CAT_TRAIL, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeShader, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::explosionShader, cg_userWeaponParseBuffer_t::flashShader, MAX_QPATH, cg_userWeaponParseBuffer_t::missileShader, cg_userWeaponParseBuffer_t::missileStruggleShader, cg_userWeaponParseBuffer_t::missileTrailShader, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseShockwave()
qboolean CG_weapGfx_ParseShockwave (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 527 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_EXPLOSION){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         Q_strncpyz(cg_weapGfxBuffer.shockwaveModel,"",sizeof(cg_weapGfxBuffer.shockwaveModel));
         Q_strncpyz(cg_weapGfxBuffer.shockwaveSkin,"",sizeof(cg_weapGfxBuffer.shockwaveSkin));
     }
     else if(token->tokenSym == TOKEN_STRING){
         Q_strncpyz(cg_weapGfxBuffer.shockwaveModel,token->stringval,sizeof(cg_weapGfxBuffer.shockwaveModel));
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         if(token->tokenSym != TOKEN_STRING){
             return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
         }
         Q_strncpyz(cg_weapGfxBuffer.shockwaveSkin,token->stringval,sizeof(cg_weapGfxBuffer.shockwaveSkin));
     }
     else{
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_EXPLOSION, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, NULL, Q_strncpyz(), qfalse, cg_weapGfxParser_t::scanner, cg_userWeaponParseBuffer_t::shockwaveModel, cg_userWeaponParseBuffer_t::shockwaveSkin, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseSize()
qboolean CG_weapGfx_ParseSize (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 213 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     float* size;
     if(category == CAT_CHARGE){
         if(token->tokenSym == TOKEN_INTEGER || token->tokenSym == TOKEN_FLOAT){
             cg_weapGfxBuffer.chargeStartsize = token->floatval;
             cg_weapGfxBuffer.chargeEndsize = token->floatval;
         }
         else if(token->tokenSym == TOKEN_OPENRANGE){
             int range;
             if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
             for(range=0;range<2;++range){
                 size = range == 0 ? &cg_weapGfxBuffer.chargeStartsize : &cg_weapGfxBuffer.chargeEndsize;
                 if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
                     return CG_weapGfx_ErrorHandle(ERROR_FLOAT_EXPECTED,scanner,token->stringval,NULL);
                 }
                 *size = token->floatval;
                 if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
             }
             if(token->tokenSym != TOKEN_CLOSERANGE){
                 return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,"]");
             }
         }
         else{
             return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,NULL);
         }
     }
     else{
         if(category == CAT_EXPLOSION){size = &cg_weapGfxBuffer.explosionSize;}
         else if(category == CAT_MISSILE){size = &cg_weapGfxBuffer.missileSize;}
         else if(category == CAT_TRAIL){size = &cg_weapGfxBuffer.missileTrailRadius;}
         else if(category == CAT_FLASH){size = &cg_weapGfxBuffer.flashSize;}
         else{
             return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
         }
         if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
             return CG_weapGfx_ErrorHandle(ERROR_FLOAT_EXPECTED,scanner,token->stringval,NULL);
         }
         *size = token->floatval;
     }
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CAT_EXPLOSION, CAT_FLASH, CAT_MISSILE, CAT_TRAIL, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeEndsize, cg_userWeaponParseBuffer_t::chargeStartsize, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FLOAT_EXPECTED, ERROR_UNEXPECTED_SYMBOL, cg_userWeaponParseBuffer_t::explosionSize, cg_userWeaponParseBuffer_t::flashSize, cg_userWeaponParseBuffer_t::missileSize, cg_userWeaponParseBuffer_t::missileTrailRadius, NULL, qfalse, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_CLOSERANGE, TOKEN_FLOAT, TOKEN_INTEGER, and TOKEN_OPENRANGE.
CG_weapGfx_ParseSkin()
qboolean CG_weapGfx_ParseSkin (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 128 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     char* weaponField;
     if(category == CAT_CHARGE){weaponField = cg_weapGfxBuffer.chargeSkin;}
     else if(category == CAT_EXPLOSION){weaponField = cg_weapGfxBuffer.explosionSkin;}
     else if(category == CAT_STRUGGLE){weaponField = cg_weapGfxBuffer.missileStruggleSkin;}
     else if(category == CAT_MISSILE){weaponField = cg_weapGfxBuffer.missileSkin;}
     else if(category == CAT_FLASH){weaponField = cg_weapGfxBuffer.flashSkin;}
     else{
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(weaponField,token->stringval,MAX_QPATH);
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CAT_EXPLOSION, CAT_FLASH, CAT_MISSILE, CAT_STRUGGLE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeSkin, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::explosionSkin, cg_userWeaponParseBuffer_t::flashSkin, MAX_QPATH, cg_userWeaponParseBuffer_t::missileSkin, cg_userWeaponParseBuffer_t::missileStruggleSkin, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseSmokeParticles()
qboolean CG_weapGfx_ParseSmokeParticles (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 593 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_EXPLOSION){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(cg_weapGfxBuffer.smokeParticleSystem,token->stringval,sizeof(cg_weapGfxBuffer.smokeParticleSystem));
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_EXPLOSION, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_userWeaponParseBuffer_t::smokeParticleSystem, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseSoundFx()
qboolean CG_weapGfx_ParseSoundFx (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 377 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     int maximumSounds = category == CAT_EXPLOSION ? MAX_EXPLOSION_SOUNDS : MAX_FLASH_SOUNDS;
     int index = 0;
     char (*sound)[MAX_QPATH];
     if(category == CAT_EXPLOSION){sound = cg_weapGfxBuffer.explosionSound;}
     else if(category == CAT_FLASH){sound = cg_weapGfxBuffer.flashSound;}
     else{
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     memset(sound,0,MAX_QPATH * maximumSounds);
     if(token->tokenSym == TOKEN_STRING){
         Q_strncpyz(sound[0],token->stringval,MAX_QPATH);
     }
     else if(token->tokenSym == TOKEN_OPENVECTOR){
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         while(token->tokenSym == TOKEN_STRING){
             if(index >= maximumSounds){
                 return CG_weapGfx_ErrorHandle(ERROR_OVER_MAXVECTORELEMS,scanner,token->stringval,va("%d",maximumSounds));
             }
             Q_strncpyz(sound[index],token->stringval,MAX_QPATH);
             index++;
             if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         }
         if(token->tokenSym != TOKEN_CLOSEVECTOR){
             return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,")");
         }
     }
     else if(token->tokenSym != TOKEN_NULL){
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,NULL);
     }
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_EXPLOSION, CAT_FLASH, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_OVER_MAXVECTORELEMS, ERROR_UNEXPECTED_SYMBOL, cg_userWeaponParseBuffer_t::explosionSound, cg_userWeaponParseBuffer_t::flashSound, MAX_EXPLOSION_SOUNDS, MAX_FLASH_SOUNDS, MAX_QPATH, NULL, Q_strncpyz(), qfalse, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_CLOSEVECTOR, TOKEN_NULL, TOKEN_OPENVECTOR, TOKEN_STRING, and va().
CG_weapGfx_ParseSpin()
qboolean CG_weapGfx_ParseSpin (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 331 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     vec3_t  spin;
     int axis;
     if(category != CAT_CHARGE && category != CAT_MISSILE){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym != TOKEN_OPENVECTOR){
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,"(");
     }
     if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
     for(axis=0;axis<3;++axis){
         if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
             return CG_weapGfx_ErrorHandle(ERROR_FLOAT_EXPECTED,scanner,token->stringval,NULL);
         }
         spin[axis] = token->floatval;
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
     }
     if(token->tokenSym != TOKEN_CLOSEVECTOR){
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,")");
     }
     if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
     if(category == CAT_CHARGE){VectorCopy(spin,cg_weapGfxBuffer.chargeSpin);}
     if(category == CAT_MISSILE){VectorCopy(spin,cg_weapGfxBuffer.missileSpin);}
     return qtrue;
 }
References CAT_CHARGE, CAT_MISSILE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeSpin, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_FLOAT_EXPECTED, ERROR_UNEXPECTED_SYMBOL, cg_userWeaponParseBuffer_t::missileSpin, NULL, qfalse, qtrue, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_CLOSEVECTOR, TOKEN_FLOAT, TOKEN_INTEGER, TOKEN_OPENVECTOR, and VectorCopy.
CG_weapGfx_ParseSpiralOffset()
qboolean CG_weapGfx_ParseSpiralOffset (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 677 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_TRAIL){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
         return CG_weapGfx_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
     }
     cg_weapGfxBuffer.missileTrailSpiralOffset = token->floatval;
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_TRAIL, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, cg_userWeaponParseBuffer_t::missileTrailSpiralOffset, NULL, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_FLOAT, and TOKEN_INTEGER.
CG_weapGfx_ParseSpiralShader()
qboolean CG_weapGfx_ParseSpiralShader (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 648 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_TRAIL){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym == TOKEN_NULL){
         *token->stringval = '\0';
     }
     else if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(cg_weapGfxBuffer.missileTrailSpiralShader,token->stringval,sizeof(cg_weapGfxBuffer.missileTrailSpiralShader));
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_TRAIL, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, cg_userWeaponParseBuffer_t::missileTrailSpiralShader, NULL, Q_strncpyz(), cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_NULL, and TOKEN_STRING.
CG_weapGfx_ParseSpiralSize()
qboolean CG_weapGfx_ParseSpiralSize (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 664 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_TRAIL){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     if(token->tokenSym != TOKEN_INTEGER && token->tokenSym != TOKEN_FLOAT){
         return CG_weapGfx_ErrorHandle(ERROR_INTEGER_EXPECTED,scanner,token->stringval,NULL);
     }
     cg_weapGfxBuffer.missileTrailSpiralRadius = token->floatval;
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_TRAIL, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_INTEGER_EXPECTED, cg_userWeaponParseBuffer_t::missileTrailSpiralRadius, NULL, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_FLOAT, and TOKEN_INTEGER.
CG_weapGfx_ParseTagTo()
qboolean CG_weapGfx_ParseTagTo (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 360 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     if(category != CAT_CHARGE){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     // FIXME: When later on we can specify two tags, we will have to be able to pass
     //        'null' for the 2nd one, to disable the 2nd tag, or to the 1st to change
     //        the 2nd tag into the first.
     if(token->tokenSym != TOKEN_STRING){
         return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
     }
     Q_strncpyz(cg_weapGfxBuffer.chargeTag[0],token->stringval,sizeof(cg_weapGfxBuffer.chargeTag[0]));
     if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
     return qtrue;
 }
References CAT_CHARGE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeTag, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_STRING_EXPECTED, NULL, Q_strncpyz(), qfalse, qtrue, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, and TOKEN_STRING.
CG_weapGfx_ParseTimedFx()
qboolean CG_weapGfx_ParseTimedFx (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 463 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     int i=0;
     if(category != CAT_CHARGE){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     memset(cg_weapGfxBuffer.chargeVoice,0,sizeof(chargeVoiceParseBuffer_t) * MAX_CHARGE_VOICES);
     // Don't have to do anything but blank it out and advance the token, if 'null' was passed.
     if(token->tokenSym == TOKEN_NULL){
         return CG_weapGfx_CheckPrematureEOF(scanner,token);
     }
     if(token->tokenSym != TOKEN_OPENVECTOR){
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,"(");
     }
     if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
     while(token->tokenSym == TOKEN_INTEGER){
         if(i >= MAX_CHARGE_VOICES){return CG_weapGfx_ErrorHandle(ERROR_OVER_MAXVECTORELEMS,scanner,token->stringval,va("%d",MAX_CHARGE_VOICES));}
         if(token->intval > 100){return CG_weapGfx_ErrorHandle(ERROR_OVER_MAXBOUND,scanner,token->stringval,"100");}
         if(token->intval < 0){return CG_weapGfx_ErrorHandle(ERROR_UNDER_MINBOUND,scanner,token->stringval,"0");}
         cg_weapGfxBuffer.chargeVoice[i].startPct = token->intval;
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         if(token->tokenSym != TOKEN_STRING){
             return CG_weapGfx_ErrorHandle(ERROR_STRING_EXPECTED,scanner,token->stringval,NULL);
         }
         Q_strncpyz(cg_weapGfxBuffer.chargeVoice[i].voice,token->stringval,sizeof(cg_weapGfxBuffer.chargeVoice[i].voice));
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         i++;
     }
     if(token->tokenSym != TOKEN_CLOSEVECTOR){
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,NULL);
     }
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_CHARGE, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, cg_userWeaponParseBuffer_t::chargeVoice, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_OVER_MAXBOUND, ERROR_OVER_MAXVECTORELEMS, ERROR_STRING_EXPECTED, ERROR_UNDER_MINBOUND, ERROR_UNEXPECTED_SYMBOL, MAX_CHARGE_VOICES, NULL, Q_strncpyz(), qfalse, cg_weapGfxParser_t::scanner, chargeVoiceParseBuffer_t::startPct, cg_weapGfxParser_t::token, TOKEN_CLOSEVECTOR, TOKEN_INTEGER, TOKEN_NULL, TOKEN_OPENVECTOR, TOKEN_STRING, va(), and chargeVoiceParseBuffer_t::voice.
CG_weapGfx_ParseVoiceFx()
qboolean CG_weapGfx_ParseVoiceFx (cg_weapGfxParser_t * parser, cg_weapGfxCategoryIndex_t category, int field)
Definition at line 412 of file cg_weapGfxParser.c.
{
     cg_weapGfxScanner_t* scanner = &parser->scanner;
     cg_weapGfxToken_t* token = &parser->token;
     int index = 0;
     if(category != CAT_FLASH){
         return CG_weapGfx_ErrorHandle(ERROR_FIELD_NOT_IN_CATEGORY,scanner,cg_weapGfxFields[field].fieldname,cg_weapGfxCategories[category]);
     }
     memset(cg_weapGfxBuffer.voiceSound,0,MAX_QPATH * MAX_FLASH_VOICES);
     if(token->tokenSym == TOKEN_STRING){
         Q_strncpyz(cg_weapGfxBuffer.voiceSound[0],token->stringval,sizeof(cg_weapGfxBuffer.voiceSound[0]));
     }
     else if(token->tokenSym == TOKEN_OPENVECTOR){
         if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         while(token->tokenSym == TOKEN_STRING){
             if(index >= MAX_FLASH_VOICES){
                 return CG_weapGfx_ErrorHandle(ERROR_OVER_MAXVECTORELEMS,scanner,token->stringval,va("%d",MAX_FLASH_VOICES));
             }
             Q_strncpyz(cg_weapGfxBuffer.voiceSound[index],token->stringval,sizeof(cg_weapGfxBuffer.voiceSound[index]));
             index++;
             if(!CG_weapGfx_CheckPrematureEOF(scanner,token)){return qfalse;}
         }
         if(token->tokenSym != TOKEN_CLOSEVECTOR){
             return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,")");
         }
     }
     else if(token->tokenSym != TOKEN_NULL) {
         return CG_weapGfx_ErrorHandle(ERROR_UNEXPECTED_SYMBOL,scanner,token->stringval,NULL);
     }
     return CG_weapGfx_CheckPrematureEOF(scanner,token);
 }
References CAT_FLASH, CG_weapGfx_CheckPrematureEOF(), CG_weapGfx_ErrorHandle(), cg_weapGfxBuffer, cg_weapGfxCategories, cg_weapGfxFields, ERROR_FIELD_NOT_IN_CATEGORY, ERROR_OVER_MAXVECTORELEMS, ERROR_UNEXPECTED_SYMBOL, MAX_FLASH_VOICES, MAX_QPATH, NULL, Q_strncpyz(), qfalse, cg_weapGfxParser_t::scanner, cg_weapGfxParser_t::token, TOKEN_CLOSEVECTOR, TOKEN_NULL, TOKEN_OPENVECTOR, TOKEN_STRING, va(), and cg_userWeaponParseBuffer_t::voiceSound.
Variable Documentation
cg_weapGfxCategories
char* cg_weapGfxCategories[]
Definition at line 4 of file cg_weapGfxScanner.c.
Referenced by CG_weapGfx_NextSym().
cg_weapGfxFields
cg_weapGfxField_t cg_weapGfxFields[]
Definition at line 5 of file cg_weapGfxScanner.c.
Referenced by CG_weapGfx_NextSym().