ZEQ2-Lite: Tools/MinGW/include/ctype.h File Reference
ctype.h File Reference
#include <_mingw.h>
#include <stddef.h>
Macros
#define __ISCTYPE(c, mask) (MB_CUR_MAX == 1 ? (_pctype[c] & mask) : _isctype(c, mask))
#define __need_wchar_t
#define __need_wint_t
#define __WCTYPE_INLINES_DEFINED
#define _ALPHA 0x0103
#define _BLANK 0x0040
#define _CONTROL 0x0020
#define _DIGIT 0x0004
#define _HEX 0x0080
#define _LEADBYTE 0x8000
#define _LOWER 0x0002
#define _pctype _pctype_dll
#define _PUNCT 0x0010
#define _SPACE 0x0008 /* HT LF VT FF CR SP */
#define _UPPER 0x0001
#define _WCTYPE_T_DEFINED
#define MB_CUR_MAX __mb_cur_max_dll
#define WEOF (wchar_t)(0xFFFF)
Typedefs
typedef wchar_t wctype_t
Functions
int __cdecl __MINGW_NOTHROW __isascii (int)
int __cdecl __MINGW_NOTHROW __iscsym (int)
int __cdecl __MINGW_NOTHROW __iscsymf (int)
int __cdecl __MINGW_NOTHROW __toascii (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _isctype (int, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _tolower (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _toupper (int)
_CRTIMP int __cdecl __MINGW_NOTHROW is_wctype (wint_t, wctype_t)
_CRTIMP int __cdecl __MINGW_NOTHROW isalnum (int)
_CRTIMP int __cdecl __MINGW_NOTHROW isalpha (int)
int __cdecl __MINGW_NOTHROW isascii (int)
int __cdecl __MINGW_NOTHROW isblank (int)
_CRTIMP int __cdecl __MINGW_NOTHROW iscntrl (int)
int __cdecl __MINGW_NOTHROW iscsym (int)
int __cdecl __MINGW_NOTHROW iscsymf (int)
_CRTIMP int __cdecl __MINGW_NOTHROW isdigit (int)
_CRTIMP int __cdecl __MINGW_NOTHROW isgraph (int)
_CRTIMP int __cdecl __MINGW_NOTHROW isleadbyte (int)
_CRTIMP int __cdecl __MINGW_NOTHROW islower (int)
_CRTIMP int __cdecl __MINGW_NOTHROW isprint (int)
_CRTIMP int __cdecl __MINGW_NOTHROW ispunct (int)
_CRTIMP int __cdecl __MINGW_NOTHROW isspace (int)
_CRTIMP int __cdecl __MINGW_NOTHROW isupper (int)
_CRTIMP int __cdecl __MINGW_NOTHROW iswalnum (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswalpha (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswascii (wint_t)
int __cdecl __MINGW_NOTHROW iswblank (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswcntrl (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswctype (wint_t, wctype_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswdigit (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswgraph (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswlower (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswprint (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswpunct (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswspace (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswupper (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW iswxdigit (wint_t)
_CRTIMP int __cdecl __MINGW_NOTHROW isxdigit (int)
int __cdecl __MINGW_NOTHROW toascii (int)
_CRTIMP int __cdecl __MINGW_NOTHROW tolower (int)
_CRTIMP int __cdecl __MINGW_NOTHROW toupper (int)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW towlower (wint_t)
_CRTIMP wint_t __cdecl __MINGW_NOTHROW towupper (wint_t)
Variables
__MINGW_IMPORT int __mb_cur_max_dll
__MINGW_IMPORT unsigned short _ctype []
__MINGW_IMPORT unsigned short * _pctype_dll
Macro Definition Documentation
__ISCTYPE
#define __ISCTYPE (c, mask) (MB_CUR_MAX == 1 ? (_pctype[c] & mask) : _isctype(c, mask))
Definition at line 153 of file ctype.h.
__need_wchar_t
#define __need_wchar_t
Definition at line 17 of file ctype.h.
__need_wint_t
#define __need_wint_t
Definition at line 18 of file ctype.h.
__WCTYPE_INLINES_DEFINED
#define __WCTYPE_INLINES_DEFINED
Definition at line 223 of file ctype.h.
_ALPHA
#define _ALPHA 0x0103
Definition at line 40 of file ctype.h.
_BLANK
#define _BLANK 0x0040
Definition at line 36 of file ctype.h.
_CONTROL
#define _CONTROL 0x0020
Definition at line 33 of file ctype.h.
_DIGIT
#define _DIGIT 0x0004
Definition at line 30 of file ctype.h.
_HEX
#define _HEX 0x0080
Definition at line 37 of file ctype.h.
_LEADBYTE
#define _LEADBYTE 0x8000
Definition at line 38 of file ctype.h.
_LOWER
#define _LOWER 0x0002
Definition at line 29 of file ctype.h.
_pctype
#define _pctype _pctype_dll
Definition at line 118 of file ctype.h.
_PUNCT
#define _PUNCT 0x0010
Definition at line 32 of file ctype.h.
_SPACE
#define _SPACE 0x0008 /* HT LF VT FF CR SP */
Definition at line 31 of file ctype.h.
_UPPER
#define _UPPER 0x0001
Definition at line 28 of file ctype.h.
_WCTYPE_T_DEFINED
#define _WCTYPE_T_DEFINED
Definition at line 189 of file ctype.h.
MB_CUR_MAX
#define MB_CUR_MAX __mb_cur_max_dll
Definition at line 94 of file ctype.h.
WEOF
#define WEOF (wchar_t)(0xFFFF)
Definition at line 184 of file ctype.h.
Typedef Documentation
wctype_t
typedef wchar_t wctype_t
Definition at line 188 of file ctype.h.
Function Documentation
__isascii()
__CRT_INLINE int __cdecl __MINGW_NOTHROW __isascii (int c)
Definition at line 252 of file ctype.h.
 {return ((c & ~0x7F) == 0);}
__iscsym()
__CRT_INLINE int __cdecl __MINGW_NOTHROW __iscsym (int c)
Definition at line 255 of file ctype.h.
 {return  (isalnum(c) || (c == '_'));}
References isalnum().
__iscsymf()
__CRT_INLINE int __cdecl __MINGW_NOTHROW __iscsymf (int c)
Definition at line 254 of file ctype.h.
 {return (isalpha(c) || (c == '_'));}
References isalpha().
__toascii()
__CRT_INLINE int __cdecl __MINGW_NOTHROW __toascii (int c)
Definition at line 253 of file ctype.h.
 {return (c & 0x7F);}
_isctype()
_CRTIMP int __cdecl __MINGW_NOTHROW _isctype (int , int)
_tolower()
__CRT_INLINE int __cdecl __MINGW_NOTHROW _tolower (int c)
Definition at line 173 of file ctype.h.
 {return ( c -'A'+'a');}
_toupper()
__CRT_INLINE int __cdecl __MINGW_NOTHROW _toupper (int c)
Definition at line 174 of file ctype.h.
 {return ( c -'a'+'A');}
is_wctype()
_CRTIMP int __cdecl __MINGW_NOTHROW is_wctype (wint_t , wctype_t)
isalnum()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isalnum (int c)
Definition at line 154 of file ctype.h.
 {return __ISCTYPE(c, (_ALPHA|_DIGIT));}
References __ISCTYPE, _ALPHA, and _DIGIT.
Referenced by __iscsym().
isalpha()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isalpha (int c)
Definition at line 155 of file ctype.h.
 {return __ISCTYPE(c, _ALPHA);}
References __ISCTYPE, and _ALPHA.
Referenced by __iscsymf(), and yylex().
isascii()
int __cdecl __MINGW_NOTHROW isascii (int)
isblank()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isblank (int c)
Definition at line 168 of file ctype.h.
   {return (__ISCTYPE(c, _BLANK) || c == '\t');}
References __ISCTYPE, and _BLANK.
iscntrl()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iscntrl (int c)
Definition at line 156 of file ctype.h.
 {return __ISCTYPE(c, _CONTROL);}
References __ISCTYPE, and _CONTROL.
iscsym()
int __cdecl __MINGW_NOTHROW iscsym (int)
iscsymf()
int __cdecl __MINGW_NOTHROW iscsymf (int)
isdigit()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isdigit (int c)
Definition at line 157 of file ctype.h.
 {return __ISCTYPE(c, _DIGIT);}
References __ISCTYPE, and _DIGIT.
Referenced by compose(), and yylex().
isgraph()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isgraph (int c)
Definition at line 158 of file ctype.h.
 {return __ISCTYPE(c, (_PUNCT|_ALPHA|_DIGIT));}
References __ISCTYPE, _ALPHA, _DIGIT, and _PUNCT.
isleadbyte()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isleadbyte (int c)
Definition at line 236 of file ctype.h.
 {return (_pctype[(unsigned char)(c)] & _LEADBYTE);}
References _LEADBYTE, and _pctype.
islower()
__CRT_INLINE int __cdecl __MINGW_NOTHROW islower (int c)
Definition at line 159 of file ctype.h.
 {return __ISCTYPE(c, _LOWER);}
References __ISCTYPE, and _LOWER.
isprint()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isprint (int c)
Definition at line 160 of file ctype.h.
 {return __ISCTYPE(c, (_BLANK|_PUNCT|_ALPHA|_DIGIT));}
References __ISCTYPE, _ALPHA, _BLANK, _DIGIT, and _PUNCT.
Referenced by yylex().
ispunct()
__CRT_INLINE int __cdecl __MINGW_NOTHROW ispunct (int c)
Definition at line 161 of file ctype.h.
 {return __ISCTYPE(c, _PUNCT);}
References __ISCTYPE, and _PUNCT.
isspace()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isspace (int c)
Definition at line 162 of file ctype.h.
 {return __ISCTYPE(c, _SPACE);}
References __ISCTYPE, and _SPACE.
Referenced by CL_ParseBinding(), and yylex().
isupper()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isupper (int c)
Definition at line 163 of file ctype.h.
 {return __ISCTYPE(c, _UPPER);}
References __ISCTYPE, and _UPPER.
Referenced by yyEND().
iswalnum()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswalnum (wint_t wc)
Definition at line 224 of file ctype.h.
 {return (iswctype(wc,_ALPHA|_DIGIT));}
References _ALPHA, _DIGIT, and iswctype().
iswalpha()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswalpha (wint_t wc)
Definition at line 225 of file ctype.h.
 {return (iswctype(wc,_ALPHA));}
References _ALPHA, and iswctype().
iswascii()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswascii (wint_t wc)
Definition at line 226 of file ctype.h.
 {return ((wc & ~0x7F) ==0);}
iswblank()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswblank (wint_t wc)
Definition at line 239 of file ctype.h.
   {return (iswctype(wc,_BLANK) || wc == L'\t');}
References _BLANK, and iswctype().
iswcntrl()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswcntrl (wint_t wc)
Definition at line 227 of file ctype.h.
 {return (iswctype(wc,_CONTROL));}
References _CONTROL, and iswctype().
iswctype()
_CRTIMP int __cdecl __MINGW_NOTHROW iswctype (wint_t , wctype_t)
Referenced by iswalnum(), iswalpha(), iswblank(), iswcntrl(), iswdigit(), iswgraph(), iswlower(), iswprint(), iswpunct(), iswspace(), iswupper(), and iswxdigit().
iswdigit()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswdigit (wint_t wc)
Definition at line 228 of file ctype.h.
 {return (iswctype(wc,_DIGIT));}
References _DIGIT, and iswctype().
iswgraph()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswgraph (wint_t wc)
Definition at line 229 of file ctype.h.
 {return (iswctype(wc,_PUNCT|_ALPHA|_DIGIT));}
References _ALPHA, _DIGIT, _PUNCT, and iswctype().
iswlower()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswlower (wint_t wc)
Definition at line 230 of file ctype.h.
 {return (iswctype(wc,_LOWER));}
References _LOWER, and iswctype().
iswprint()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswprint (wint_t wc)
Definition at line 231 of file ctype.h.
 {return (iswctype(wc,_BLANK|_PUNCT|_ALPHA|_DIGIT));}
References _ALPHA, _BLANK, _DIGIT, _PUNCT, and iswctype().
iswpunct()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswpunct (wint_t wc)
Definition at line 232 of file ctype.h.
 {return (iswctype(wc,_PUNCT));}
References _PUNCT, and iswctype().
iswspace()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswspace (wint_t wc)
Definition at line 233 of file ctype.h.
 {return (iswctype(wc,_SPACE));}
References _SPACE, and iswctype().
iswupper()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswupper (wint_t wc)
Definition at line 234 of file ctype.h.
 {return (iswctype(wc,_UPPER));}
References _UPPER, and iswctype().
iswxdigit()
__CRT_INLINE int __cdecl __MINGW_NOTHROW iswxdigit (wint_t wc)
Definition at line 235 of file ctype.h.
 {return (iswctype(wc,_HEX));}
References _HEX, and iswctype().
isxdigit()
__CRT_INLINE int __cdecl __MINGW_NOTHROW isxdigit (int c)
Definition at line 164 of file ctype.h.
 {return __ISCTYPE(c, _HEX);}
References __ISCTYPE, and _HEX.
toascii()
int __cdecl __MINGW_NOTHROW toascii (int)
tolower()
_CRTIMP int __cdecl __MINGW_NOTHROW tolower (int)
Referenced by Com_HexStrToInt(), Console_Key(), Field_KeyDownEvent(), FindMatches(), FS_HashFileName(), generateHashValue(), MField_KeyDownEvent(), Q_strlwr(), S_HashSFXName(), and strlower().
toupper()
_CRTIMP int __cdecl __MINGW_NOTHROW toupper (int)
Referenced by Com_Filter(), Com_StringContains(), CreatePath(), Q_strupr(), and strupr().
towlower()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW towlower (wint_t)
towupper()
_CRTIMP wint_t __cdecl __MINGW_NOTHROW towupper (wint_t)
Variable Documentation
__mb_cur_max_dll
__MINGW_IMPORT int __mb_cur_max_dll
Definition at line 95 of file ctype.h.
_ctype
__MINGW_IMPORT unsigned short _ctype[]
Definition at line 112 of file ctype.h.
_pctype_dll
__MINGW_IMPORT unsigned short* _pctype_dll
Definition at line 117 of file ctype.h.