ZEQ2-Lite: Source/Engine/renderer/tr_shade_calc.c File Reference
tr_shade_calc.c File Reference
#include "tr_local.h"
Macros
#define WAVEVALUE(table, base, amplitude, phase, freq) ((base) + table[ ri.ftol((((phase) + tess.shaderTime * (freq)) * FUNCTABLE_SIZE)) & FUNCTABLE_MASK ] * (amplitude))
Functions
static void Autosprite2Deform (void)
static void AutospriteDeform (void)
void DeformText (const char *text)
static float EvalWaveForm (const waveForm_t *wf)
static float EvalWaveFormClamped (const waveForm_t *wf)
static void GlobalVectorToLocal (const vec3_t in, vec3_t out)
void RB_CalcAlphaFromEntity (unsigned char *dstColors)
void RB_CalcAlphaFromOneMinusEntity (unsigned char *dstColors)
void RB_CalcBulgeVertexes (deformStage_t *ds)
void RB_CalcColorFromEntity (unsigned char *dstColors)
void RB_CalcColorFromOneMinusEntity (unsigned char *dstColors)
void RB_CalcDeformNormals (deformStage_t *ds)
void RB_CalcDeformVertexes (deformStage_t *ds)
void RB_CalcDiffuseColor (unsigned char *colors)
static void RB_CalcDiffuseColor_scalar (unsigned char *colors)
void RB_CalcDynamicColor (unsigned char *colors)
void RB_CalcEnvironmentCelShadeTexCoords (float *st)
void RB_CalcEnvironmentTexCoords (float *st)
void RB_CalcFogTexCoords (float *st)
void RB_CalcHazeTexCoords (float *st)
void RB_CalcModulateAlphasByFog (unsigned char *colors)
void RB_CalcModulateColorsByFog (unsigned char *colors)
void RB_CalcModulateRGBAsByFog (unsigned char *colors)
void RB_CalcMoveVertexes (deformStage_t *ds)
void RB_CalcRotateTexCoords (float degsPerSecond, float *st)
void RB_CalcScaleTexCoords (const float scale[2], float *st)
void RB_CalcScrollTexCoords (const float scrollSpeed[2], float *st)
void RB_CalcSpecularAlpha (unsigned char *alphas)
void RB_CalcStretchTexCoords (const waveForm_t *wf, float *st)
void RB_CalcTransformTexCoords (const texModInfo_t *tmi, float *st)
void RB_CalcTurbulentTexCoords (const waveForm_t *wf, float *st)
void RB_CalcUniformColor (unsigned char *colors)
void RB_CalcWaveAlpha (const waveForm_t *wf, unsigned char *dstColors)
void RB_CalcWaveColor (const waveForm_t *wf, unsigned char *dstColors)
void RB_DeformTessGeometry (void)
static float * TableForFunc (genFunc_t func)
Variables
int edgeVerts [6][2]
vec3_t lightOrigin = { -960, 1980, 96 }
Macro Definition Documentation
WAVEVALUE
#define WAVEVALUE (table, base, amplitude, phase, freq) ((base) + table[ ri.ftol((((phase) + tess.shaderTime * (freq)) * FUNCTABLE_SIZE)) & FUNCTABLE_MASK ] * (amplitude))
Definition at line 30 of file tr_shade_calc.c.
Function Documentation
Autosprite2Deform()
static void Autosprite2Deform (void) static
Definition at line 432 of file tr_shade_calc.c.
{
     int     i, j, k;
     int     indexes;
     float   *xyz;
     vec3_t  forward;
     if ( tess.numVertexes & 3 ) {
         ri.Printf( PRINT_WARNING, "Autosprite2 shader %s had odd vertex count", tess.shader->name );
     }
     if ( tess.numIndexes != ( tess.numVertexes >> 2 ) * 6 ) {
         ri.Printf( PRINT_WARNING, "Autosprite2 shader %s had odd index count", tess.shader->name );
     }
     if ( backEnd.currentEntity != &tr.worldEntity ) {
         GlobalVectorToLocal( backEnd.viewParms.or.axis[0], forward );
     } else {
         VectorCopy( backEnd.viewParms.or.axis[0], forward );
     }
     // this is a lot of work for two triangles...
     // we could precalculate a lot of it is an issue, but it would mess up
     // the shader abstraction
     for ( i = 0, indexes = 0 ; i < tess.numVertexes ; i+=4, indexes+=6 ) {
         float   lengths[2];
         int     nums[2];
         vec3_t  mid[2];
         vec3_t  major, minor;
         float   *v1, *v2;
         // find the midpoint
         xyz = tess.xyz[i];
         // identify the two shortest edges
         nums[0] = nums[1] = 0;
         lengths[0] = lengths[1] = 999999;
         for ( j = 0 ; j < 6 ; j++ ) {
             float   l;
             vec3_t  temp;
             v1 = xyz + 4 * edgeVerts[j][0];
             v2 = xyz + 4 * edgeVerts[j][1];
             VectorSubtract( v1, v2, temp );
             l = DotProduct( temp, temp );
             if ( l < lengths[0] ) {
                 nums[1] = nums[0];
                 lengths[1] = lengths[0];
                 nums[0] = j;
                 lengths[0] = l;
             } else if ( l < lengths[1] ) {
                 nums[1] = j;
                 lengths[1] = l;
             }
         }
         for ( j = 0 ; j < 2 ; j++ ) {
             v1 = xyz + 4 * edgeVerts[nums[j]][0];
             v2 = xyz + 4 * edgeVerts[nums[j]][1];
             mid[j][0] = 0.5f * (v1[0] + v2[0]);
             mid[j][1] = 0.5f * (v1[1] + v2[1]);
             mid[j][2] = 0.5f * (v1[2] + v2[2]);
         }
         // find the vector of the major axis
         VectorSubtract( mid[1], mid[0], major );
         // cross this with the view direction to get minor axis
         CrossProduct( major, forward, minor );
         VectorNormalize( minor );
         // re-project the points
         for ( j = 0 ; j < 2 ; j++ ) {
             float   l;
             v1 = xyz + 4 * edgeVerts[nums[j]][0];
             v2 = xyz + 4 * edgeVerts[nums[j]][1];
             l = 0.5 * sqrt( lengths[j] );
             // we need to see which direction this edge
             // is used to determine direction of projection
             for ( k = 0 ; k < 5 ; k++ ) {
                 if ( tess.indexes[ indexes + k ] == i + edgeVerts[nums[j]][0]
                     && tess.indexes[ indexes + k + 1 ] == i + edgeVerts[nums[j]][1] ) {
                     break;
                 }
             }
             if ( k == 5 ) {
                 VectorMA( mid[j], l, minor, v1 );
                 VectorMA( mid[j], -l, minor, v2 );
             } else {
                 VectorMA( mid[j], -l, minor, v1 );
                 VectorMA( mid[j], l, minor, v2 );
             }
         }
     }
 }
References orientationr_t::axis, backEnd, CrossProduct(), backEndState_t::currentEntity, DotProduct, edgeVerts, forward, GlobalVectorToLocal(), indexes, viewParms_t::or, PRINT_WARNING, ri, tess, tr, VectorCopy, VectorMA(), VectorNormalize(), VectorSubtract, backEndState_t::viewParms, and trGlobals_t::worldEntity.
Referenced by RB_DeformTessGeometry().
AutospriteDeform()
static void AutospriteDeform (void) static
Definition at line 352 of file tr_shade_calc.c.
{
     int     i;
     int     oldVerts;
     float   *xyz;
     vec3_t  mid, delta;
     float   radius;
     vec3_t  left, up;
     vec3_t  leftDir, upDir;
     if ( tess.numVertexes & 3 ) {
         ri.Printf( PRINT_WARNING, "Autosprite shader %s had odd vertex count\n", tess.shader->name );
     }
     if ( tess.numIndexes != ( tess.numVertexes >> 2 ) * 6 ) {
         ri.Printf( PRINT_WARNING, "Autosprite shader %s had odd index count\n", tess.shader->name );
     }
     oldVerts = tess.numVertexes;
     tess.numVertexes = 0;
     tess.numIndexes = 0;
     if ( backEnd.currentEntity != &tr.worldEntity ) {
         GlobalVectorToLocal( backEnd.viewParms.or.axis[1], leftDir );
         GlobalVectorToLocal( backEnd.viewParms.or.axis[2], upDir );
     } else {
         VectorCopy( backEnd.viewParms.or.axis[1], leftDir );
         VectorCopy( backEnd.viewParms.or.axis[2], upDir );
     }
     for ( i = 0 ; i < oldVerts ; i+=4 ) {
         // find the midpoint
         xyz = tess.xyz[i];
         mid[0] = 0.25f * (xyz[0] + xyz[4] + xyz[8] + xyz[12]);
         mid[1] = 0.25f * (xyz[1] + xyz[5] + xyz[9] + xyz[13]);
         mid[2] = 0.25f * (xyz[2] + xyz[6] + xyz[10] + xyz[14]);
         VectorSubtract( xyz, mid, delta );
         radius = VectorLength( delta ) * 0.707f;        // / sqrt(2)
         VectorScale( leftDir, radius, left );
         VectorScale( upDir, radius, up );
         if ( backEnd.viewParms.isMirror ) {
             VectorSubtract( vec3_origin, left, left );
         }
       // compensate for scale in the axes if necessary
     if ( backEnd.currentEntity->e.nonNormalizedAxes ) {
       float axisLength;
           axisLength = VectorLength( backEnd.currentEntity->e.axis[0] );
         if ( !axisLength ) {
             axisLength = 0;
         } else {
             axisLength = 1.0f / axisLength;
         }
       VectorScale(left, axisLength, left);
       VectorScale(up, axisLength, up);
     }
         RB_AddQuadStamp( mid, left, up, tess.vertexColors[i] );
     }
 }
References orientationr_t::axis, refEntity_t::axis, backEnd, backEndState_t::currentEntity, trRefEntity_t::e, GlobalVectorToLocal(), viewParms_t::isMirror, refEntity_t::nonNormalizedAxes, viewParms_t::or, PRINT_WARNING, RB_AddQuadStamp(), ri, tess, tr, up, vec3_origin, VectorCopy, VectorLength(), VectorScale, VectorSubtract, backEndState_t::viewParms, and trGlobals_t::worldEntity.
Referenced by RB_DeformTessGeometry().
DeformText()
void DeformText (const char * text)
Definition at line 265 of file tr_shade_calc.c.
{
     int     i;
     vec3_t  origin, width, height;
     int     len;
     int     ch;
     byte    color[4];
     float   bottom, top;
     vec3_t  mid;
     height[0] = 0;
     height[1] = 0;
     height[2] = -1;
     CrossProduct( tess.normal[0], height, width );
     // find the midpoint of the box
     VectorClear( mid );
     bottom = 999999;
     top = -999999;
     for ( i = 0 ; i < 4 ; i++ ) {
         VectorAdd( tess.xyz[i], mid, mid );
         if ( tess.xyz[i][2] < bottom ) {
             bottom = tess.xyz[i][2];
         }
         if ( tess.xyz[i][2] > top ) {
             top = tess.xyz[i][2];
         }
     }
     VectorScale( mid, 0.25f, origin );
     // determine the individual character size
     height[0] = 0;
     height[1] = 0;
     height[2] = ( top - bottom ) * 0.5f;
     VectorScale( width, height[2] * -0.75f, width );
     // determine the starting position
     len = strlen( text );
     VectorMA( origin, (len-1), width, origin );
     // clear the shader indexes
     tess.numIndexes = 0;
     tess.numVertexes = 0;
     color[0] = color[1] = color[2] = color[3] = 255;
     // draw each character
     for ( i = 0 ; i < len ; i++ ) {
         ch = text[i];
         ch &= 255;
         if ( ch != ' ' ) {
             int     row, col;
             float   frow, fcol, size;
             row = ch>>4;
             col = ch&15;
             frow = row*0.0625f;
             fcol = col*0.0625f;
             size = 0.0625f;
             RB_AddQuadStampExt( origin, width, height, color, fcol, frow, fcol + size, frow + size );
         }
         VectorMA( origin, -2, width, origin );
     }
 }
References CrossProduct(), RB_AddQuadStampExt(), tess, VectorAdd, VectorClear, VectorMA(), and VectorScale.
Referenced by RB_DeformTessGeometry().
EvalWaveForm()
static float EvalWaveForm (const waveForm_t * wf) static
Definition at line 60 of file tr_shade_calc.c.
 {
     float   *table;
     table = TableForFunc( wf->func );
     return WAVEVALUE( table, wf->base, wf->amplitude, wf->phase, wf->frequency );
 }
References waveForm_t::amplitude, waveForm_t::base, waveForm_t::frequency, waveForm_t::func, waveForm_t::phase, TableForFunc(), and WAVEVALUE.
Referenced by EvalWaveFormClamped(), RB_CalcDeformVertexes(), RB_CalcStretchTexCoords(), and RB_CalcWaveColor().
EvalWaveFormClamped()
static float EvalWaveFormClamped (const waveForm_t * wf) static
Definition at line 69 of file tr_shade_calc.c.
 {
     float glow  = EvalWaveForm( wf );
     if ( glow < 0 )
     {
         return 0;
     }
     if ( glow > 1 )
     {
         return 1;
     }
     return glow;
 }
References EvalWaveForm().
Referenced by RB_CalcWaveAlpha().
GlobalVectorToLocal()
static void GlobalVectorToLocal (const vec3_t in, vec3_t out) static
Definition at line 338 of file tr_shade_calc.c.
{
     out[0] = DotProduct( in, backEnd.or.axis[0] );
     out[1] = DotProduct( in, backEnd.or.axis[1] );
     out[2] = DotProduct( in, backEnd.or.axis[2] );
 }
References orientationr_t::axis, backEnd, DotProduct, backEndState_t::or, and out.
Referenced by Autosprite2Deform(), and AutospriteDeform().
RB_CalcAlphaFromEntity()
void RB_CalcAlphaFromEntity (unsigned char * dstColors)
Definition at line 644 of file tr_shade_calc.c.
 {
     int i;
     if ( !backEnd.currentEntity )
         return;
     dstColors += 3;
     for ( i = 0; i < tess.numVertexes; i++, dstColors += 4 )
     {
         *dstColors = backEnd.currentEntity->e.shaderRGBA[3];
     }
 }
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, refEntity_t::shaderRGBA, and tess.
Referenced by ComputeColors().
RB_CalcAlphaFromOneMinusEntity()
void RB_CalcAlphaFromOneMinusEntity (unsigned char * dstColors)
Definition at line 662 of file tr_shade_calc.c.
 {
     int i;
     if ( !backEnd.currentEntity )
         return;
     dstColors += 3;
     for ( i = 0; i < tess.numVertexes; i++, dstColors += 4 )
     {
         *dstColors = 0xff - backEnd.currentEntity->e.shaderRGBA[3];
     }
 }
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, refEntity_t::shaderRGBA, and tess.
Referenced by ComputeColors().
RB_CalcBulgeVertexes()
void RB_CalcBulgeVertexes (deformStage_t * ds)
Definition at line 204 of file tr_shade_calc.c.
{
     int i;
     const float *st = ( const float * ) tess.texCoords[0];
     float       *xyz = ( float * ) tess.xyz;
     float       *normal = ( float * ) tess.normal;
     float       now;
     now = backEnd.refdef.time * ds->bulgeSpeed * 0.001f;
     for ( i = 0; i < tess.numVertexes; i++, xyz += 4, st += 4, normal += 4 ) {
         int     off;
         float scale;
         off = (float)( FUNCTABLE_SIZE / (M_PI*2) ) * ( st[0] * ds->bulgeWidth + now );
         scale = tr.sinTable[ off & FUNCTABLE_MASK ] * ds->bulgeHeight;
         xyz[0] += normal[0] * scale;
         xyz[1] += normal[1] * scale;
         xyz[2] += normal[2] * scale;
     }
 }
References backEnd, deformStage_t::bulgeHeight, deformStage_t::bulgeSpeed, deformStage_t::bulgeWidth, FUNCTABLE_MASK, FUNCTABLE_SIZE, M_PI, off, backEndState_t::refdef, trGlobals_t::sinTable, tess, trRefdef_t::time, and tr.
Referenced by RB_DeformTessGeometry().
RB_CalcColorFromEntity()
void RB_CalcColorFromEntity (unsigned char * dstColors)
Definition at line 598 of file tr_shade_calc.c.
 {
     int i;
     int *pColors = ( int * ) dstColors;
     int c;
     if ( !backEnd.currentEntity )
         return;
     c = * ( int * ) backEnd.currentEntity->e.shaderRGBA;
     for ( i = 0; i < tess.numVertexes; i++, pColors++ )
     {
         *pColors = c;
     }
 }
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, refEntity_t::shaderRGBA, and tess.
Referenced by ComputeColors().
RB_CalcColorFromOneMinusEntity()
void RB_CalcColorFromOneMinusEntity (unsigned char * dstColors)
Definition at line 618 of file tr_shade_calc.c.
 {
     int i;
     int *pColors = ( int * ) dstColors;
     unsigned char invModulate[4];
     int c;
     if ( !backEnd.currentEntity )
         return;
     invModulate[0] = 255 - backEnd.currentEntity->e.shaderRGBA[0];
     invModulate[1] = 255 - backEnd.currentEntity->e.shaderRGBA[1];
     invModulate[2] = 255 - backEnd.currentEntity->e.shaderRGBA[2];
     invModulate[3] = 255 - backEnd.currentEntity->e.shaderRGBA[3];  // this trashes alpha, but the AGEN block fixes it
     c = * ( int * ) invModulate;
     for ( i = 0; i < tess.numVertexes; i++, pColors++ )
     {
         *pColors = c;
     }
 }
References backEnd, backEndState_t::currentEntity, trRefEntity_t::e, refEntity_t::shaderRGBA, and tess.
Referenced by ComputeColors().
RB_CalcDeformNormals()
void RB_CalcDeformNormals (deformStage_t * ds)
Definition at line 172 of file tr_shade_calc.c.
{
     int i;
     float   scale;
     float   *xyz = ( float * ) tess.xyz;
     float   *normal = ( float * ) tess.normal;
     for ( i = 0; i < tess.numVertexes; i++, xyz += 4, normal += 4 ) {
         scale = 0.98f;
         scale = R_NoiseGet4f( xyz[0] * scale, xyz[1] * scale, xyz[2] * scale,
             tess.shaderTime * ds->deformationWave.frequency );
         normal[ 0 ] += ds->deformationWave.amplitude * scale;
         scale = 0.98f;
         scale = R_NoiseGet4f( 100 + xyz[0] * scale, xyz[1] * scale, xyz[2] * scale,
             tess.shaderTime * ds->deformationWave.frequency );
         normal[ 1 ] += ds->deformationWave.amplitude * scale;
         scale = 0.98f;
         scale = R_NoiseGet4f( 200 + xyz[0] * scale, xyz[1] * scale, xyz[2] * scale,
             tess.shaderTime * ds->deformationWave.frequency );
         normal[ 2 ] += ds->deformationWave.amplitude * scale;
         VectorNormalizeFast( normal );
     }
 }
References waveForm_t::amplitude, deformStage_t::deformationWave, waveForm_t::frequency, R_NoiseGet4f(), tess, and VectorNormalizeFast().
Referenced by RB_DeformTessGeometry().
RB_CalcDeformVertexes()
void RB_CalcDeformVertexes (deformStage_t * ds)
Definition at line 121 of file tr_shade_calc.c.
 {
     int i;
     vec3_t  offset;
     float   scale;
     float   *xyz = ( float * ) tess.xyz;
     float   *normal = ( float * ) tess.normal;
     float   *table;
     if ( ds->deformationWave.frequency == 0 )
     {
         scale = EvalWaveForm( &ds->deformationWave );
         for ( i = 0; i < tess.numVertexes; i++, xyz += 4, normal += 4 )
         {
             VectorScale( normal, scale, offset );
             xyz[0] += offset[0];
             xyz[1] += offset[1];
             xyz[2] += offset[2];
         }
     }
     else
     {
         table = TableForFunc( ds->deformationWave.func );
         for ( i = 0; i < tess.numVertexes; i++, xyz += 4, normal += 4 )
         {
             float off = ( xyz[0] + xyz[1] + xyz[2] ) * ds->deformationSpread;
             scale = WAVEVALUE( table, ds->deformationWave.base,
                 ds->deformationWave.amplitude,
                 ds->deformationWave.phase + off,
                 ds->deformationWave.frequency );
             VectorScale( normal, scale, offset );
             xyz[0] += offset[0];
             xyz[1] += offset[1];
             xyz[2] += offset[2];
         }
     }
 }
References waveForm_t::amplitude, waveForm_t::base, deformStage_t::deformationSpread, deformStage_t::deformationWave, EvalWaveForm(), waveForm_t::frequency, waveForm_t::func, off, waveForm_t::phase, TableForFunc(), tess, VectorScale, and WAVEVALUE.
Referenced by RB_DeformTessGeometry().
RB_CalcDiffuseColor()
void RB_CalcDiffuseColor (unsigned char * colors)
Definition at line 1289 of file tr_shade_calc.c.
 {
 #if idppc_altivec
     if (com_altivec->integer) {
         // must be in a seperate function or G3 systems will crash.
         RB_CalcDiffuseColor_altivec( colors );
         return;
     }
 #endif
     RB_CalcDiffuseColor_scalar( colors );
 }
References com_altivec, and RB_CalcDiffuseColor_scalar().
Referenced by ComputeColors(), and RB_StageIteratorVertexLitTexture().
RB_CalcDiffuseColor_scalar()
static void RB_CalcDiffuseColor_scalar (unsigned char * colors) static
Definition at line 1240 of file tr_shade_calc.c.
 {
     int             i, j;
     float           *v, *normal;
     float           incoming;
     trRefEntity_t   *ent;
     int             ambientLightInt;
     vec3_t          ambientLight;
     vec3_t          lightDir;
     vec3_t          directedLight;
     int             numVertexes;
     ent = backEnd.currentEntity;
     ambientLightInt = ent->ambientLightInt;
     VectorCopy( ent->ambientLight, ambientLight );
     VectorCopy( ent->directedLight, directedLight );
     VectorCopy( ent->lightDir, lightDir );
     v = tess.xyz[0];
     normal = tess.normal[0];
     numVertexes = tess.numVertexes;
     for (i = 0 ; i < numVertexes ; i++, v += 4, normal += 4) {
         incoming = DotProduct (normal, lightDir);
         if ( incoming <= 0 ) {
             *(int *)&colors[i*4] = ambientLightInt;
             continue;
         }
         j = ri.ftol(ambientLight[0] + incoming * directedLight[0]);
         if ( j > 255 ) {
             j = 255;
         }
         colors[i*4+0] = j;
         j = ri.ftol(ambientLight[1] + incoming * directedLight[1]);
         if ( j > 255 ) {
             j = 255;
         }
         colors[i*4+1] = j;
         j = ri.ftol(ambientLight[2] + incoming * directedLight[2]);
         if ( j > 255 ) {
             j = 255;
         }
         colors[i*4+2] = j;
         colors[i*4+3] = 255;
     }
 }
References trRefEntity_t::ambientLight, trRefEntity_t::ambientLightInt, backEnd, backEndState_t::currentEntity, trRefEntity_t::directedLight, DotProduct, refimport_t::ftol, trRefEntity_t::lightDir, ri, tess, and VectorCopy.
Referenced by RB_CalcDiffuseColor().
RB_CalcDynamicColor()
void RB_CalcDynamicColor (unsigned char * colors)
Definition at line 1344 of file tr_shade_calc.c.
 {
     int             i;
     trRefEntity_t   *ent;
     vec4_t          dynamic;
     int             numVertexes;
     float           normalize;
     ent = backEnd.currentEntity;
     VectorCopy( ent->dynamicLight, dynamic );
     normalize = NormalizeColor( dynamic, dynamic );
     if ( normalize > 255 ) normalize = 255;
     VectorScale( dynamic, normalize, dynamic );
     dynamic[3] = 255;
     numVertexes = tess.numVertexes;
     for (i = 0 ; i < numVertexes ; i++ ) {
         colors[i*4+0] = dynamic[0];
         colors[i*4+1] = dynamic[1];
         colors[i*4+2] = dynamic[2];
         colors[i*4+3] = dynamic[3];
     }
 }
References backEnd, backEndState_t::currentEntity, dynamic(), trRefEntity_t::dynamicLight, NormalizeColor(), tess, VectorCopy, and VectorScale.
Referenced by ComputeColors().
RB_CalcEnvironmentCelShadeTexCoords()
void RB_CalcEnvironmentCelShadeTexCoords (float * st)
Definition at line 972 of file tr_shade_calc.c.
 {
     int    i;
     float  *v, *normal;
     vec3_t lightDir;
     float  d;
     normal = tess.normal[0];
     v = tess.xyz[0];
     // Calculate only once
 //  VectorCopy( backEnd.currentEntity->lightDir, lightDir );
 //  if ( backEnd.currentEntity == &tr.worldEntity )
 //      VectorSubtract( lightOrigin, v, lightDir );
 //  else
         VectorCopy( backEnd.currentEntity->lightDir, lightDir );
     VectorNormalizeFast( lightDir );
     for (i = 0 ; i < tess.numVertexes ; i++, v += 4, normal += 4, st += 2 ) {
         d= DotProduct( normal, lightDir );
         st[0] = 0.5 + d * 0.5;
         st[1] = 0.5;
     }
 }
References backEnd, backEndState_t::currentEntity, DotProduct, trRefEntity_t::lightDir, tess, VectorCopy, and VectorNormalizeFast().
Referenced by ComputeTexCoords().
RB_CalcEnvironmentTexCoords()
void RB_CalcEnvironmentTexCoords (float * st)
Definition at line 940 of file tr_shade_calc.c.
 {
     int         i;
     float       *v, *normal;
     vec3_t      viewer, reflected;
     float       d;
     v = tess.xyz[0];
     normal = tess.normal[0];
     for (i = 0 ; i < tess.numVertexes ; i++, v += 4, normal += 4, st += 2 )
     {
         VectorSubtract (backEnd.or.viewOrigin, v, viewer);
         VectorNormalizeFast (viewer);
         d = DotProduct (normal, viewer);
         reflected[0] = normal[0]*2*d - viewer[0];
         reflected[1] = normal[1]*2*d - viewer[1];
         reflected[2] = normal[2]*2*d - viewer[2];
         st[0] = 0.5 + reflected[1] * 0.5;
         st[1] = 0.5 - reflected[2] * 0.5;
     }
 }
References backEnd, DotProduct, backEndState_t::or, tess, VectorNormalizeFast(), VectorSubtract, and orientationr_t::viewOrigin.
Referenced by ComputeTexCoords().
RB_CalcFogTexCoords()
void RB_CalcFogTexCoords (float * st)
Definition at line 808 of file tr_shade_calc.c.
{
     int         i;
     float       *v;
     float       s, t;
     float       eyeT;
     qboolean    eyeOutside;
     fog_t       *fog;
     vec3_t      local;
     vec4_t      fogDistanceVector, fogDepthVector = {0, 0, 0, 0};
     fog = tr.world->fogs + tess.fogNum;
     // all fogging distance is based on world Z units
     VectorSubtract( backEnd.or.origin, backEnd.viewParms.or.origin, local );
     fogDistanceVector[0] = -backEnd.or.modelMatrix[2];
     fogDistanceVector[1] = -backEnd.or.modelMatrix[6];
     fogDistanceVector[2] = -backEnd.or.modelMatrix[10];
     fogDistanceVector[3] = DotProduct( local, backEnd.viewParms.or.axis[0] );
     // scale the fog vectors based on the fog's thickness
     fogDistanceVector[0] *= fog->tcScale;
     fogDistanceVector[1] *= fog->tcScale;
     fogDistanceVector[2] *= fog->tcScale;
     fogDistanceVector[3] *= fog->tcScale;
     // rotate the gradient vector for this orientation
     if ( fog->hasSurface ) {
         fogDepthVector[0] = fog->surface[0] * backEnd.or.axis[0][0] +
             fog->surface[1] * backEnd.or.axis[0][1] + fog->surface[2] * backEnd.or.axis[0][2];
         fogDepthVector[1] = fog->surface[0] * backEnd.or.axis[1][0] +
             fog->surface[1] * backEnd.or.axis[1][1] + fog->surface[2] * backEnd.or.axis[1][2];
         fogDepthVector[2] = fog->surface[0] * backEnd.or.axis[2][0] +
             fog->surface[1] * backEnd.or.axis[2][1] + fog->surface[2] * backEnd.or.axis[2][2];
         fogDepthVector[3] = -fog->surface[3] + DotProduct( backEnd.or.origin, fog->surface );
         eyeT = DotProduct( backEnd.or.viewOrigin, fogDepthVector ) + fogDepthVector[3];
     } else {
         eyeT = 1;   // non-surface fog always has eye inside
     }
     // see if the viewpoint is outside
     // this is needed for clipping distance even for constant fog
     if ( eyeT < 0 ) {
         eyeOutside = qtrue;
     } else {
         eyeOutside = qfalse;
     }
     fogDistanceVector[3] += 1.0/512;
     // calculate density for each point
     for (i = 0, v = tess.xyz[0] ; i < tess.numVertexes ; i++, v += 4) {
         // calculate the length in fog
         s = DotProduct( v, fogDistanceVector ) + fogDistanceVector[3];
         t = DotProduct( v, fogDepthVector ) + fogDepthVector[3];
         // partially clipped fogs use the T axis
         if ( eyeOutside ) {
             if ( t < 1.0 ) {
                 t = 1.0/32; // point is outside, so no fogging
             } else {
                 t = 1.0/32 + 30.0/32 * t / ( t - eyeT );    // cut the distance at the fog plane
             }
         } else {
             if ( t < 0 ) {
                 t = 1.0/32; // point is outside, so no fogging
             } else {
                 t = 31.0/32;
             }
         }
         st[0] = s;
         st[1] = t;
         st += 2;
     }
 }
References orientationr_t::axis, backEnd, DotProduct, world_t::fogs, fog_t::hasSurface, local, orientationr_t::modelMatrix, viewParms_t::or, backEndState_t::or, orientationr_t::origin, qfalse, qtrue, fog_t::surface, fog_t::tcScale, tess, tr, VectorSubtract, orientationr_t::viewOrigin, backEndState_t::viewParms, and trGlobals_t::world.
Referenced by ComputeTexCoords(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), RB_CalcModulateRGBAsByFog(), RB_FogPass(), and RB_HazePass().
RB_CalcHazeTexCoords()
void RB_CalcHazeTexCoords (float * st)
Definition at line 895 of file tr_shade_calc.c.
{
     int         i;
     float       *v;
     float       s, t;
     vec3_t      local;
     vec4_t      hazeDistanceVector, hazeDepthVector;
     // all fogging distance is based on world Z units
     VectorSubtract( backEnd.or.origin, backEnd.viewParms.or.origin, local );
     hazeDistanceVector[0] = -backEnd.or.modelMatrix[2];
     hazeDistanceVector[1] = -backEnd.or.modelMatrix[6];
     hazeDistanceVector[2] = -backEnd.or.modelMatrix[10];
     hazeDistanceVector[3] = DotProduct( local, backEnd.viewParms.or.axis[0] );
     /*
     // scale the haze vectors based on the haze's thickness
     hazeDistanceVector[0] *= fog->tcScale;
     hazeDistanceVector[1] *= fog->tcScale;
     hazeDistanceVector[2] *= fog->tcScale;
     hazeDistanceVector[3] *= fog->tcScale;
     */
     hazeDistanceVector[3] += 1.0/512;
     // calculate density for each point
     for (i = 0, v = tess.xyz[0] ; i < tess.numVertexes ; i++, v += 4) {
         // calculate the length in haze
         s = DotProduct( v, hazeDistanceVector ) + hazeDistanceVector[3];
         t = DotProduct( v, hazeDepthVector ) + hazeDepthVector[3];
         if ( t < 0 ) {
             t = 1.0/32; // point is outside, so no hazing
         } else {
             t = 31.0/32;
         }
         st[0] = s;
         st[1] = t;
         st += 2;
     }
 }
References orientationr_t::axis, backEnd, DotProduct, local, orientationr_t::modelMatrix, viewParms_t::or, backEndState_t::or, orientationr_t::origin, tess, VectorSubtract, and backEndState_t::viewParms.
RB_CalcModulateAlphasByFog()
void RB_CalcModulateAlphasByFog (unsigned char * colors)
Definition at line 754 of file tr_shade_calc.c.
{
     int     i;
     float   texCoords[SHADER_MAX_VERTEXES][2];
     // calculate texcoords so we can derive density
     // this is not wasted, because it would only have
     // been previously called if the surface was opaque
     RB_CalcFogTexCoords( texCoords[0] );
     for ( i = 0; i < tess.numVertexes; i++, colors += 4 ) {
         float f = 1.0 - R_FogFactor( texCoords[i][0], texCoords[i][1] );
         colors[3] *= f;
     }
 }
References R_FogFactor(), RB_CalcFogTexCoords(), SHADER_MAX_VERTEXES, and tess.
Referenced by ComputeColors().
RB_CalcModulateColorsByFog()
void RB_CalcModulateColorsByFog (unsigned char * colors)
Definition at line 734 of file tr_shade_calc.c.
{
     int     i;
     float   texCoords[SHADER_MAX_VERTEXES][2];
     // calculate texcoords so we can derive density
     // this is not wasted, because it would only have
     // been previously called if the surface was opaque
     RB_CalcFogTexCoords( texCoords[0] );
     for ( i = 0; i < tess.numVertexes; i++, colors += 4 ) {
         float f = 1.0 - R_FogFactor( texCoords[i][0], texCoords[i][1] );
         colors[0] *= f;
         colors[1] *= f;
         colors[2] *= f;
     }
 }
References R_FogFactor(), RB_CalcFogTexCoords(), SHADER_MAX_VERTEXES, and tess.
Referenced by ComputeColors(), and RB_RenderFlare().
RB_CalcModulateRGBAsByFog()
void RB_CalcModulateRGBAsByFog (unsigned char * colors)
Definition at line 772 of file tr_shade_calc.c.
{
     int     i;
     float   texCoords[SHADER_MAX_VERTEXES][2];
     // calculate texcoords so we can derive density
     // this is not wasted, because it would only have
     // been previously called if the surface was opaque
     RB_CalcFogTexCoords( texCoords[0] );
     for ( i = 0; i < tess.numVertexes; i++, colors += 4 ) {
         float f = 1.0 - R_FogFactor( texCoords[i][0], texCoords[i][1] );
         colors[0] *= f;
         colors[1] *= f;
         colors[2] *= f;
         colors[3] *= f;
     }
 }
References R_FogFactor(), RB_CalcFogTexCoords(), SHADER_MAX_VERTEXES, and tess.
Referenced by ComputeColors().
RB_CalcMoveVertexes()
void RB_CalcMoveVertexes (deformStage_t * ds)
Definition at line 235 of file tr_shade_calc.c.
{
     int         i;
     float       *xyz;
     float       *table;
     float       scale;
     vec3_t      offset;
     table = TableForFunc( ds->deformationWave.func );
     scale = WAVEVALUE( table, ds->deformationWave.base,
         ds->deformationWave.amplitude,
         ds->deformationWave.phase,
         ds->deformationWave.frequency );
     VectorScale( ds->moveVector, scale, offset );
     xyz = ( float * ) tess.xyz;
     for ( i = 0; i < tess.numVertexes; i++, xyz += 4 ) {
         VectorAdd( xyz, offset, xyz );
     }
 }
References waveForm_t::amplitude, waveForm_t::base, deformStage_t::deformationWave, waveForm_t::frequency, waveForm_t::func, deformStage_t::moveVector, waveForm_t::phase, TableForFunc(), tess, VectorAdd, VectorScale, and WAVEVALUE.
Referenced by RB_DeformTessGeometry().
RB_CalcRotateTexCoords()
void RB_CalcRotateTexCoords (float degsPerSecond, float * st)
Definition at line 1076 of file tr_shade_calc.c.
 {
     float timeScale = tess.shaderTime;
     float degs;
     int index;
     float sinValue, cosValue;
     texModInfo_t tmi;
     degs = -degsPerSecond * timeScale;
     index = degs * ( FUNCTABLE_SIZE / 360.0f );
     sinValue = tr.sinTable[ index & FUNCTABLE_MASK ];
     cosValue = tr.sinTable[ ( index + FUNCTABLE_SIZE / 4 ) & FUNCTABLE_MASK ];
     tmi.matrix[0][0] = cosValue;
     tmi.matrix[1][0] = -sinValue;
     tmi.translate[0] = 0.5 - 0.5 * cosValue + 0.5 * sinValue;
     tmi.matrix[0][1] = sinValue;
     tmi.matrix[1][1] = cosValue;
     tmi.translate[1] = 0.5 - 0.5 * sinValue - 0.5 * cosValue;
     RB_CalcTransformTexCoords( &tmi, st );
 }
References FUNCTABLE_MASK, FUNCTABLE_SIZE, texModInfo_t::matrix, RB_CalcTransformTexCoords(), trGlobals_t::sinTable, tess, tr, and texModInfo_t::translate.
Referenced by ComputeTexCoords().
RB_CalcScaleTexCoords()
void RB_CalcScaleTexCoords (const float scale[2], float * st)
Definition at line 1021 of file tr_shade_calc.c.
 {
     int i;
     for ( i = 0; i < tess.numVertexes; i++, st += 2 )
     {
         st[0] *= scale[0];
         st[1] *= scale[1];
     }
 }
References tess.
Referenced by ComputeTexCoords().
RB_CalcScrollTexCoords()
void RB_CalcScrollTexCoords (const float scrollSpeed[2], float * st)
Definition at line 1035 of file tr_shade_calc.c.
 {
     int i;
     float timeScale = tess.shaderTime;
     float adjustedScrollS, adjustedScrollT;
     adjustedScrollS = scrollSpeed[0] * timeScale;
     adjustedScrollT = scrollSpeed[1] * timeScale;
     // clamp so coordinates don't continuously get larger, causing problems
     // with hardware limits
     adjustedScrollS = adjustedScrollS - floor( adjustedScrollS );
     adjustedScrollT = adjustedScrollT - floor( adjustedScrollT );
     for ( i = 0; i < tess.numVertexes; i++, st += 2 )
     {
         st[0] += adjustedScrollS;
         st[1] += adjustedScrollT;
     }
 }
References tess.
Referenced by ComputeTexCoords().
RB_CalcSpecularAlpha()
void RB_CalcSpecularAlpha (unsigned char * alphas)
Definition at line 1108 of file tr_shade_calc.c.
{
     int         i;
     float       *v, *normal;
     vec3_t      viewer,  reflected;
     float       l, d;
     int         b;
     vec3_t      lightDir;
     int         numVertexes;
     v = tess.xyz[0];
     normal = tess.normal[0];
     alphas += 3;
     numVertexes = tess.numVertexes;
     for (i = 0 ; i < numVertexes ; i++, v += 4, normal += 4, alphas += 4) {
         float ilength;
         if ( backEnd.currentEntity == &tr.worldEntity )
             VectorSubtract( lightOrigin, v, lightDir );
         else
             VectorCopy( backEnd.currentEntity->lightDir, lightDir );
 //      ilength = Q_rsqrt( DotProduct( lightDir, lightDir ) );
         VectorNormalizeFast( lightDir );
         // calculate the specular color
         d = DotProduct (normal, lightDir);
 //      d *= ilength;
         // we don't optimize for the d < 0 case since this tends to
         // cause visual artifacts such as faceted "snapping"
         reflected[0] = normal[0]*2*d - lightDir[0];
         reflected[1] = normal[1]*2*d - lightDir[1];
         reflected[2] = normal[2]*2*d - lightDir[2];
         VectorSubtract (backEnd.or.viewOrigin, v, viewer);
         ilength = Q_rsqrt( DotProduct( viewer, viewer ) );
         l = DotProduct (reflected, viewer);
         l *= ilength;
         if (l < 0) {
             b = 0;
         } else {
             l = l*l;
             l = l*l;
             b = l * 255;
             if (b > 255) {
                 b = 255;
             }
         }
         *alphas = b;
     }
 }
References backEnd, backEndState_t::currentEntity, DotProduct, trRefEntity_t::lightDir, lightOrigin, backEndState_t::or, Q_rsqrt(), tess, tr, VectorCopy, VectorNormalizeFast(), VectorSubtract, orientationr_t::viewOrigin, and trGlobals_t::worldEntity.
Referenced by ComputeColors().
RB_CalcStretchTexCoords()
void RB_CalcStretchTexCoords (const waveForm_t * wf, float * st)
Definition at line 89 of file tr_shade_calc.c.
 {
     float p;
     texModInfo_t tmi;
     p = 1.0f / EvalWaveForm( wf );
     tmi.matrix[0][0] = p;
     tmi.matrix[1][0] = 0;
     tmi.translate[0] = 0.5f - 0.5f * p;
     tmi.matrix[0][1] = 0;
     tmi.matrix[1][1] = p;
     tmi.translate[1] = 0.5f - 0.5f * p;
     RB_CalcTransformTexCoords( &tmi, st );
 }
References EvalWaveForm(), texModInfo_t::matrix, RB_CalcTransformTexCoords(), and texModInfo_t::translate.
Referenced by ComputeTexCoords().
RB_CalcTransformTexCoords()
void RB_CalcTransformTexCoords (const texModInfo_t * tmi, float * st)
Definition at line 1059 of file tr_shade_calc.c.
 {
     int i;
     for ( i = 0; i < tess.numVertexes; i++, st += 2 )
     {
         float s = st[0];
         float t = st[1];
         st[0] = s * tmi->matrix[0][0] + t * tmi->matrix[1][0] + tmi->translate[0];
         st[1] = s * tmi->matrix[0][1] + t * tmi->matrix[1][1] + tmi->translate[1];
     }
 }
References texModInfo_t::matrix, tess, and texModInfo_t::translate.
Referenced by ComputeTexCoords(), RB_CalcRotateTexCoords(), and RB_CalcStretchTexCoords().
RB_CalcTurbulentTexCoords()
void RB_CalcTurbulentTexCoords (const waveForm_t * wf, float * st)
Definition at line 1001 of file tr_shade_calc.c.
 {
     int i;
     float now;
     now = ( wf->phase + tess.shaderTime * wf->frequency );
     for ( i = 0; i < tess.numVertexes; i++, st += 2 )
     {
         float s = st[0];
         float t = st[1];
         st[0] = s + tr.sinTable[ ( ( int ) ( ( ( tess.xyz[i][0] + tess.xyz[i][2] )* 1.0/128 * 0.125 + now ) * FUNCTABLE_SIZE ) ) & ( FUNCTABLE_MASK ) ] * wf->amplitude;
         st[1] = t + tr.sinTable[ ( ( int ) ( ( tess.xyz[i][1] * 1.0/128 * 0.125 + now ) * FUNCTABLE_SIZE ) ) & ( FUNCTABLE_MASK ) ] * wf->amplitude;
     }
 }
References waveForm_t::amplitude, waveForm_t::frequency, FUNCTABLE_MASK, FUNCTABLE_SIZE, int(), waveForm_t::phase, trGlobals_t::sinTable, tess, and tr.
Referenced by ComputeTexCoords().
RB_CalcUniformColor()
void RB_CalcUniformColor (unsigned char * colors)
Definition at line 1307 of file tr_shade_calc.c.
 {
     int             i;
     trRefEntity_t   *ent;
     vec3_t          ambientLight;
 //  vec3_t          directedLight;
     vec4_t          uniformLight;
     int             numVertexes;
     float           normalize;
     ent = backEnd.currentEntity;
     VectorCopy( ent->ambientLight, ambientLight );
 //  VectorCopy( ent->directedLight, directedLight );
     VectorAdd( ambientLight, ambientLight/*directedLight*/, uniformLight );
     normalize = NormalizeColor( uniformLight, uniformLight );
     if ( normalize > 255 ) normalize = 255;
     VectorScale( uniformLight, normalize, uniformLight );
     uniformLight[3] = 255;
     numVertexes = tess.numVertexes;
     for (i = 0 ; i < numVertexes ; i++ ) {
         colors[i*4+0] = uniformLight[0];
         colors[i*4+1] = uniformLight[1];
         colors[i*4+2] = uniformLight[2];
         colors[i*4+3] = uniformLight[3];
     }
 }
References trRefEntity_t::ambientLight, backEnd, backEndState_t::currentEntity, NormalizeColor(), tess, VectorAdd, VectorCopy, and VectorScale.
Referenced by ComputeColors().
RB_CalcWaveAlpha()
void RB_CalcWaveAlpha (const waveForm_t * wf, unsigned char * dstColors)
Definition at line 715 of file tr_shade_calc.c.
 {
     int i;
     int v;
     float glow;
     glow = EvalWaveFormClamped( wf );
     v = 255 * glow;
     for ( i = 0; i < tess.numVertexes; i++, dstColors += 4 )
     {
         dstColors[3] = v;
     }
 }
References EvalWaveFormClamped(), and tess.
Referenced by ComputeColors().
RB_CalcWaveColor()
void RB_CalcWaveColor (const waveForm_t * wf, unsigned char * dstColors)
Definition at line 680 of file tr_shade_calc.c.
 {
     int i;
     int v;
     float glow;
     int *colors = ( int * ) dstColors;
     byte    color[4];
   if ( wf->func == GF_NOISE ) {
         glow = wf->base + R_NoiseGet4f( 0, 0, 0, ( tess.shaderTime + wf->phase ) * wf->frequency ) * wf->amplitude;
     } else {
         glow = EvalWaveForm( wf ) * tr.identityLight;
     }
     if ( glow < 0 ) {
         glow = 0;
     }
     else if ( glow > 1 ) {
         glow = 1;
     }
     v = ri.ftol(255 * glow);
     color[0] = color[1] = color[2] = v;
     color[3] = 255;
     v = *(int *)color;
     for ( i = 0; i < tess.numVertexes; i++, colors++ ) {
         *colors = v;
     }
 }
References waveForm_t::amplitude, waveForm_t::base, EvalWaveForm(), waveForm_t::frequency, refimport_t::ftol, waveForm_t::func, GF_NOISE, trGlobals_t::identityLight, waveForm_t::phase, R_NoiseGet4f(), ri, tess, and tr.
Referenced by ComputeColors().
RB_DeformTessGeometry()
void RB_DeformTessGeometry (void)
Definition at line 541 of file tr_shade_calc.c.
{
     int     i;
     deformStage_t   *ds;
     for ( i = 0 ; i < tess.shader->numDeforms ; i++ ) {
         ds = &tess.shader->deforms[ i ];
         switch ( ds->deformation ) {
         case DEFORM_NONE:
             break;
         case DEFORM_NORMALS:
             RB_CalcDeformNormals( ds );
             break;
         case DEFORM_WAVE:
             RB_CalcDeformVertexes( ds );
             break;
         case DEFORM_BULGE:
             RB_CalcBulgeVertexes( ds );
             break;
         case DEFORM_MOVE:
             RB_CalcMoveVertexes( ds );
             break;
         case DEFORM_PROJECTION_SHADOW:
             RB_ProjectionShadowDeform();
             break;
         case DEFORM_AUTOSPRITE:
             AutospriteDeform();
             break;
         case DEFORM_AUTOSPRITE2:
             Autosprite2Deform();
             break;
         case DEFORM_TEXT0:
         case DEFORM_TEXT1:
         case DEFORM_TEXT2:
         case DEFORM_TEXT3:
         case DEFORM_TEXT4:
         case DEFORM_TEXT5:
         case DEFORM_TEXT6:
         case DEFORM_TEXT7:
             DeformText( backEnd.refdef.text[ds->deformation - DEFORM_TEXT0] );
             break;
         }
     }
 }
References Autosprite2Deform(), AutospriteDeform(), backEnd, DEFORM_AUTOSPRITE, DEFORM_AUTOSPRITE2, DEFORM_BULGE, DEFORM_MOVE, DEFORM_NONE, DEFORM_NORMALS, DEFORM_PROJECTION_SHADOW, DEFORM_TEXT0, DEFORM_TEXT1, DEFORM_TEXT2, DEFORM_TEXT3, DEFORM_TEXT4, DEFORM_TEXT5, DEFORM_TEXT6, DEFORM_TEXT7, DEFORM_WAVE, deformStage_t::deformation, DeformText(), RB_CalcBulgeVertexes(), RB_CalcDeformNormals(), RB_CalcDeformVertexes(), RB_CalcMoveVertexes(), RB_ProjectionShadowDeform(), backEndState_t::refdef, tess, and trRefdef_t::text.
Referenced by RB_StageIteratorGeneric().
TableForFunc()
static float* TableForFunc (genFunc_t func) static
Definition at line 32 of file tr_shade_calc.c.
 {
     switch ( func )
     {
     case GF_SIN:
         return tr.sinTable;
     case GF_TRIANGLE:
         return tr.triangleTable;
     case GF_SQUARE:
         return tr.squareTable;
     case GF_SAWTOOTH:
         return tr.sawToothTable;
     case GF_INVERSE_SAWTOOTH:
         return tr.inverseSawToothTable;
     case GF_NONE:
     default:
         break;
     }
     ri.Error( ERR_DROP, "TableForFunc called with invalid function '%d' in shader '%s'", func, tess.shader->name );
     return NULL;
 }
References ERR_DROP, GF_INVERSE_SAWTOOTH, GF_NONE, GF_SAWTOOTH, GF_SIN, GF_SQUARE, GF_TRIANGLE, trGlobals_t::inverseSawToothTable, NULL, ri, trGlobals_t::sawToothTable, trGlobals_t::sinTable, trGlobals_t::squareTable, tess, tr, and trGlobals_t::triangleTable.
Referenced by EvalWaveForm(), RB_CalcDeformVertexes(), and RB_CalcMoveVertexes().
Variable Documentation
edgeVerts
int edgeVerts[6][2]
Initial value:
= {
    { 0, 1 },
    { 0, 2 },
    { 0, 3 },
    { 1, 2 },
    { 1, 3 },
    { 2, 3 }
}
Definition at line 423 of file tr_shade_calc.c.
Referenced by Autosprite2Deform().
lightOrigin
vec3_t lightOrigin = { -960, 1980, 96 }
Definition at line 971 of file tr_shade_calc.c.
Referenced by R_SetupEntityLighting(), R_SetupEntityLightingGrid(), and RB_CalcSpecularAlpha().