ZEQ2-Lite: Source/Engine/tools/lcc/cpp/nlist.c File Reference
nlist.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cpp.h"
Data Structures
struct kwtab
Macros
#define NLSIZE 128
Functions
Nlist * lookup (Token *tp, int install)
void setup_kwtab (void)
Variables
int Cplusplus
Nlist * kwdefined
struct kwtab kwtab []
unsigned long namebit [077+1]
static Nlist * nlist [NLSIZE]
Nlist * np
char * optarg
int optind
int verbose
char wd [128]
Macro Definition Documentation
NLSIZE
#define NLSIZE 128
Definition at line 13 of file nlist.c.
Function Documentation
lookup()
Nlist* lookup (Token * tp, int install)
Definition at line 73 of file nlist.c.
 {
     unsigned int h;
     Nlist *np;
     uchar *cp, *cpe;
     h = 0;
     for (cp=tp->t, cpe=cp+tp->len; cp<cpe; )
         h += *cp++;
     h %= NLSIZE;
     np = nlist[h];
     while (np) {
         if (*tp->t==*np->name && tp->len==np->len
          && strncmp((char*)tp->t, (char*)np->name, tp->len)==0)
             return np;
         np = np->next;
     }
     if (install) {
         np = new(Nlist);
         np->vp = NULL;
         np->ap = NULL;
         np->flag = 0;
         np->val = 0;
         np->len = tp->len;
         np->name = newstring(tp->t, tp->len, 0);
         np->next = nlist[h];
         nlist[h] = np;
         quickset(tp->t[0], tp->len>1? tp->t[1]:0);
         return np;
     }
     return NULL;
 }
References cp, install(), newstring(), NLSIZE, np, NULL, and quickset.
Referenced by control(), dclglobal(), dcllocal(), dclparam(), decl(), doadefine(), dodefine(), enumdcl(), eval(), expandrow(), fieldref(), funcdefn(), gettok(), newstruct(), primary(), setup_kwtab(), statement(), stmtlabel(), structdcl(), and tokval().
setup_kwtab()
void setup_kwtab (void)
Definition at line 49 of file nlist.c.
 {
     struct kwtab *kp;
     Nlist *np;
     Token t;
     static Token deftoken[1] = {{ NAME, 0, 0, 0, 7, (uchar*)"defined" }};
     static Tokenrow deftr = { deftoken, deftoken, deftoken+1, 1 };
     for (kp=kwtab; kp->kw; kp++) {
         t.t = (uchar*)kp->kw;
         t.len = strlen(kp->kw);
         np = lookup(&t, 1);
         np->flag = kp->flag;
         np->val = kp->val;
         if (np->val == KDEFINED) {
             kwdefined = np;
             np->val = NAME;
             np->vp = &deftr;
             np->ap = 0;
         }
     }
 }
References kwtab::flag, KDEFINED, kwtab::kw, kwdefined, lookup(), NAME, np, and kwtab::val.
Referenced by setup().
Variable Documentation
Cplusplus
int Cplusplus
Definition at line 13 of file unix.c.
Referenced by setup().
kwdefined
Nlist* kwdefined
Definition at line 10 of file nlist.c.
Referenced by eval(), and setup_kwtab().
kwtab
struct kwtab kwtab[]
Initial value:
= {
    {"if",      KIF,        ISKW},
    {"ifdef",   KIFDEF,     ISKW},
    {"ifndef",  KIFNDEF,    ISKW},
    {"elif",        KELIF,      ISKW},
    {"else",        KELSE,      ISKW},
    {"endif",   KENDIF,     ISKW},
    {"include", KINCLUDE,   ISKW},
    {"define",  KDEFINE,    ISKW},
    {"undef",   KUNDEF,     ISKW},
    {"line",        KLINE,      ISKW},
    {"warning", KWARNING,   ISKW},
    {"error",   KERROR,     ISKW},
    {"pragma",  KPRAGMA,    ISKW},
    {"eval",        KEVAL,      ISKW},
    {"defined", KDEFINED,   ISDEFINED+ISUNCHANGE},
    {"__LINE__",    KLINENO,    ISMAC+ISUNCHANGE},
    {"__FILE__",    KFILE,      ISMAC+ISUNCHANGE},
    {"__DATE__",    KDATE,      ISMAC+ISUNCHANGE},
    {"__TIME__",    KTIME,      ISMAC+ISUNCHANGE},
    {"__STDC__",    KSTDC,      ISUNCHANGE},
    {NULL}
}
namebit
unsigned long namebit[077+1]
Definition at line 45 of file nlist.c.
nlist
Nlist* nlist[NLSIZE] static
Definition at line 15 of file nlist.c.
np
Nlist* np
Definition at line 46 of file nlist.c.
Referenced by checkhideset(), control(), doadefine(), dodefine(), eval(), expand(), expandrow(), inserths(), lookup(), newhideset(), prhideset(), setup_kwtab(), substargs(), and tokval().
optarg
char* optarg
Definition at line 8 of file getopt.c.
optind
int optind
Definition at line 6 of file getopt.c.
verbose
int verbose
Definition at line 159 of file cmdlib.c.
Referenced by puttokens(), qprintf(), and setup().
wd
char wd[128]
Definition at line 11 of file nlist.c.
Referenced by genline().