ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/bits/stl_stack.h File Reference
stl_stack.h File Reference
#include <bits/concept_check.h>
#include <debug/debug.h>
Functions
namespace std _GLIBCXX_VISIBILITY (default)
Detailed Description
This is an internal header file, included by other library headers. Do not attempt to use it directly. @headername{stack}
Definition in file stl_stack.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace std _GLIBCXX_VISIBILITY (default)
A standard container giving FILO behavior.
Meets many of the requirements of a container, but does not define anything to do with iterators. Very few of the other standard container interfaces are defined.
This is not a true container, but an adaptor. It holds another container, and provides a wrapper interface to that container. The wrapper is what enforces strict first-in-last-out stack behavior.
The second template parameter defines the type of the underlying sequence/container. It defaults to std::deque, but it can be any type that supports back, push_back, and pop_front, such as std::list, std::vector, or an appropriate user-defined type.
Members not found in normal containers are container_type, which is a typedef for the second Sequence parameter, and push, pop, and top, which are standard stack/FILO operations.
Default constructor creates no elements.
Returns true if the stack is empty.
Returns the number of elements in the stack.
Returns a read/write reference to the data at the first element of the stack.
Returns a read-only (constant) reference to the data at the first element of the stack.
Add data to the top of the stack.
Parameters
x Data to be added.
This is a typical stack operation. The function creates an element at the top of the stack and assigns the given data to it. The time complexity of the operation depends on the underlying sequence.
Removes first element.
This is a typical stack operation. It shrinks the stack by one. The time complexity of the operation depends on the underlying sequence.
Note that no data is returned, and if the first element's data is needed, it should be retrieved before pop() is called.
Stack equality comparison.
Parameters
x A stack.
y A stack of the same type as x.
Returns
True iff the size and elements of the stacks are equal.
This is an equivalence relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, and stacks are considered equivalent if their sequences compare equal.
Stack ordering relation.
Parameters
x A stack.
y A stack of the same type as x.
Returns
True iff x is lexicographically less than y.
This is an total ordering relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, the elements must be comparable with <, and std::lexicographical_compare() is usually used to make the determination.
Based on operator==
Based on operator<
Based on operator<
Based on operator<
Definition at line 64 of file stl_stack.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
   template<typename _Tp, typename _Sequence = deque<_Tp> >
     class stack
     {
       // concept requirements
       typedef typename _Sequence::value_type _Sequence_value_type;
       __glibcxx_class_requires(_Tp, _SGIAssignableConcept)
       __glibcxx_class_requires(_Sequence, _BackInsertionSequenceConcept)
       __glibcxx_class_requires2(_Tp, _Sequence_value_type, _SameTypeConcept)
       template<typename _Tp1, typename _Seq1>
         friend bool
         operator==(const stack<_Tp1, _Seq1>&, const stack<_Tp1, _Seq1>&);
       template<typename _Tp1, typename _Seq1>
         friend bool
         operator<(const stack<_Tp1, _Seq1>&, const stack<_Tp1, _Seq1>&);
     public:
       typedef typename _Sequence::value_type                value_type;
       typedef typename _Sequence::reference                 reference;
       typedef typename _Sequence::const_reference           const_reference;
       typedef typename _Sequence::size_type                 size_type;
       typedef          _Sequence                            container_type;
     protected:
       //  See queue::c for notes on this name.
       _Sequence c;
     public:
       // XXX removed old def ctor, added def arg to this one to match 14882
 #ifndef __GXX_EXPERIMENTAL_CXX0X__
       explicit
       stack(const _Sequence& __c = _Sequence())
       : c(__c) { }
 #else
       explicit
       stack(const _Sequence& __c)
       : c(__c) { }
       explicit
       stack(_Sequence&& __c = _Sequence())
       : c(std::move(__c)) { }
 #endif
       bool
       empty() const
       { return c.empty(); }
       size_type
       size() const
       { return c.size(); }
       reference
       top()
       {
     __glibcxx_requires_nonempty();
     return c.back();
       }
       const_reference
       top() const
       {
     __glibcxx_requires_nonempty();
     return c.back();
       }
       void
       push(const value_type& __x)
       { c.push_back(__x); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       void
       push(value_type&& __x)
       { c.push_back(std::move(__x)); }
       template<typename... _Args>
         void
         emplace(_Args&&... __args)
     { c.emplace_back(std::forward<_Args>(__args)...); }
 #endif
       void
       pop()
       {
     __glibcxx_requires_nonempty();
     c.pop_back();
       }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       void
       swap(stack& __s)
       {
     using std::swap;
     swap(c, __s.c);
       }
 #endif
     };
   template<typename _Tp, typename _Seq>
     inline bool
     operator==(const stack<_Tp, _Seq>& __x, const stack<_Tp, _Seq>& __y)
     { return __x.c == __y.c; }
   template<typename _Tp, typename _Seq>
     inline bool
     operator<(const stack<_Tp, _Seq>& __x, const stack<_Tp, _Seq>& __y)
     { return __x.c < __y.c; }
   template<typename _Tp, typename _Seq>
     inline bool
     operator!=(const stack<_Tp, _Seq>& __x, const stack<_Tp, _Seq>& __y)
     { return !(__x == __y); }
   template<typename _Tp, typename _Seq>
     inline bool
     operator>(const stack<_Tp, _Seq>& __x, const stack<_Tp, _Seq>& __y)
     { return __y < __x; }
   template<typename _Tp, typename _Seq>
     inline bool
     operator<=(const stack<_Tp, _Seq>& __x, const stack<_Tp, _Seq>& __y)
     { return !(__y < __x); }
   template<typename _Tp, typename _Seq>
     inline bool
     operator>=(const stack<_Tp, _Seq>& __x, const stack<_Tp, _Seq>& __y)
     { return !(__x < __y); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
   template<typename _Tp, typename _Seq>
     inline void
     swap(stack<_Tp, _Seq>& __x, stack<_Tp, _Seq>& __y)
     { __x.swap(__y); }
   template<typename _Tp, typename _Seq, typename _Alloc>
     struct uses_allocator<stack<_Tp, _Seq>, _Alloc>
     : public uses_allocator<_Seq, _Alloc>::type { };
 #endif
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References __glibcxx_class_requires, __glibcxx_class_requires2, __glibcxx_requires_nonempty, move(), std::__exception_ptr::operator!=(), __gnu_debug::operator<(), __gnu_debug::operator<=(), std::__exception_ptr::operator==(), __gnu_debug::operator>(), __gnu_debug::operator>=(), push(), and swap.