ZEQ2-Lite: Tools/MinGW/include/search.h File Reference
search.h File Reference
#include <_mingw.h>
Data Structures
struct entry
Macros
#define _SIZE_T_DEFINED
Typedefs
typedef unsigned int size_t
Enumerations
enum ACTION { FIND, ENTER }
enum VISIT { preorder, postorder, endorder, leaf }
Functions
_CRTIMP void *__cdecl _lfind (const void *, const void *, unsigned int *, unsigned int, int(*)(const void *, const void *))
_CRTIMP void *__cdecl _lsearch (const void *, void *, unsigned int *, unsigned int, int(*)(const void *, const void *))
_CRTIMP void *__cdecl bsearch (const void *, const void *, size_t, size_t, int(*)(const void *, const void *))
_CRTIMP void *__cdecl lfind (const void *, const void *, unsigned int *, unsigned int, int(*)(const void *, const void *))
_CRTIMP void *__cdecl lsearch (const void *, void *, unsigned int *, unsigned int, int(*)(const void *, const void *))
_CRTIMP void __cdecl qsort (void *, size_t, size_t, int(*)(const void *, const void *))
void *__cdecl tdelete (const void *__restrict__, void **__restrict__, int(*)(const void *, const void *)) __MINGW_ATTRIB_NONNULL(1) __MINGW_ATTRIB_NONNULL(3)
void *__cdecl tfind (const void *, void *const *, int(*)(const void *, const void *)) __MINGW_ATTRIB_NONNULL(1) __MINGW_ATTRIB_NONNULL(3)
void *__cdecl tsearch (const void *, void **, int(*)(const void *, const void *)) __MINGW_ATTRIB_NONNULL(1) __MINGW_ATTRIB_NONNULL(3)
void __cdecl twalk (const void *, void(*)(const void *, VISIT, int))
Macro Definition Documentation
_SIZE_T_DEFINED
#define _SIZE_T_DEFINED
Definition at line 37 of file search.h.
Typedef Documentation
size_t
typedef unsigned int size_t
Definition at line 36 of file search.h.
Enumeration Type Documentation
ACTION
enum ACTION
Enumerator
FIND
ENTER
Definition at line 63 of file search.h.
              {
     FIND,
     ENTER
 } ACTION;
VISIT
enum VISIT
Enumerator
preorder
postorder
endorder
leaf
Definition at line 68 of file search.h.
              {
     preorder,
     postorder,
     endorder,
     leaf
 } VISIT;
Function Documentation
_lfind()
_CRTIMP void* __cdecl _lfind (const void * , const void * , unsigned int * , unsigned int , int(*)(const void *, const void *))
_lsearch()
_CRTIMP void* __cdecl _lsearch (const void * , void * , unsigned int * , unsigned int , int(*)(const void *, const void *))
bsearch()
_CRTIMP void* __cdecl bsearch (const void * , const void * , size_t , size_t , int(*)(const void *, const void *))
lfind()
_CRTIMP void* __cdecl lfind (const void * , const void * , unsigned int * , unsigned int , int(*)(const void *, const void *))
lsearch()
_CRTIMP void* __cdecl lsearch (const void * , void * , unsigned int * , unsigned int , int(*)(const void *, const void *))
qsort()
_CRTIMP void __cdecl qsort (void * , size_t , size_t , int(*)(const void *, const void *))
Referenced by ArenaServers_Sort(), ArenaServers_StopRefresh(), ArenaServers_UpdateMenu(), assembler_init(), CalculateRanks(), FS_AddGameDirectory(), GLimp_DetectAvailableModes(), process(), sort_symbols(), SV_BuildClientSnapshot(), TeamplayInfoMessage(), and VM_VmProfile_f().
tdelete()
void* __cdecl tdelete (const void * __restrict__, void ** __restrict__, int(*)(const void *, const void *))
tfind()
void* __cdecl tfind (const void * , void *const * , int(*)(const void *, const void *))
tsearch()
void* __cdecl tsearch (const void * , void ** , int(*)(const void *, const void *))
twalk()
void __cdecl twalk (const void * , void(*)(const void *, VISIT, int))