ZEQ2-Lite: Source/Engine/client/snd_local.h File Reference
snd_local.h File Reference
#include "../../Shared/q_shared.h"
#include "../../Shared/qcommon.h"
#include "snd_public.h"
Data Structures
struct adpcm_state
struct channel_t
struct dma_t
struct loopSound_s
struct portable_samplepair_t
struct sfx_s
struct sndBuffer_s
struct soundInterface_t
struct wavinfo_t
Macros
#define MAX_CHANNELS 96
#define MAX_DOPPLER_SCALE 50.0f
#define MAX_RAW_SAMPLES 16384
#define MAX_RAW_STREAMS (MAX_CLIENTS * 2 + 1)
#define NXStream byte
#define PAINTBUFFER_SIZE 4096
#define SENTINEL_MULAW_FOUR_BIT_RUN 126
#define SENTINEL_MULAW_ZERO_RUN 127
#define SND_CHUNK_SIZE 1024
#define SND_CHUNK_SIZE_BYTE (SND_CHUNK_SIZE*2)
#define SND_CHUNK_SIZE_FLOAT (SND_CHUNK_SIZE/2)
#define START_SAMPLE_IMMEDIATE 0x7fffffff
#define WAV_FORMAT_PCM 1
Typedefs
typedef int srcHandle_t
Enumerations
enum alSrcPriority_t {
SRCPRI_AMBIENT = 0, SRCPRI_ENTITY, SRCPRI_ONESHOT, SRCPRI_LOCAL,
SRCPRI_STREAM
}
Functions
void decodeWavelet (sndBuffer *stream, short *packets)
void encodeMuLaw (sfx_t *sfx, short *packets)
void encodeWavelet (sfx_t *sfx, short *packets)
void S_AdpcmEncodeSound (sfx_t *sfx, short *samples)
void S_AdpcmGetSamples (sndBuffer *chunk, short *to)
int S_AdpcmMemoryNeeded (const wavinfo_t *info)
qboolean S_AL_Init (soundInterface_t *si)
qboolean S_Base_Init (soundInterface_t *si)
void S_FreeOldestSound (void)
qboolean S_LoadSound (sfx_t *sfx)
void S_memoryLoad (sfx_t *sfx)
void S_PaintChannels (int endtime)
void S_Spatialize (channel_t *ch)
void SND_free (sndBuffer *v)
sndBuffer * SND_malloc (void)
void SND_setup (void)
void SND_shutdown (void)
void SNDDMA_BeginPainting (void)
int SNDDMA_GetDMAPos (void)
qboolean SNDDMA_Init (void)
void SNDDMA_Shutdown (void)
void SNDDMA_Submit (void)
Variables
dma_t dma
vec3_t listener_forward
vec3_t listener_right
vec3_t listener_up
channel_t loop_channels [MAX_CHANNELS]
short mulawToShort [256]
int numLoopChannels
channel_t s_channels [MAX_CHANNELS]
cvar_t * s_doppler
cvar_t * s_musicVolume
cvar_t * s_muted
int s_paintedtime
int s_rawend [MAX_RAW_STREAMS]
portable_samplepair_t s_rawsamples [MAX_RAW_STREAMS][MAX_RAW_SAMPLES]
cvar_t * s_testsound
cvar_t * s_volume
short * sfxScratchBuffer
int sfxScratchIndex
sfx_t * sfxScratchPointer
Macro Definition Documentation
MAX_CHANNELS
#define MAX_CHANNELS 96
Definition at line 177 of file snd_local.h.
MAX_DOPPLER_SCALE
#define MAX_DOPPLER_SCALE 50.0f
Definition at line 75 of file snd_local.h.
MAX_RAW_SAMPLES
#define MAX_RAW_SAMPLES 16384
Definition at line 189 of file snd_local.h.
MAX_RAW_STREAMS
#define MAX_RAW_STREAMS (MAX_CLIENTS * 2 + 1)
Definition at line 190 of file snd_local.h.
NXStream
#define NXStream byte
Definition at line 227 of file snd_local.h.
PAINTBUFFER_SIZE
#define PAINTBUFFER_SIZE 4096
Definition at line 29 of file snd_local.h.
SENTINEL_MULAW_FOUR_BIT_RUN
#define SENTINEL_MULAW_FOUR_BIT_RUN 126
Definition at line 223 of file snd_local.h.
SENTINEL_MULAW_ZERO_RUN
#define SENTINEL_MULAW_ZERO_RUN 127
Definition at line 222 of file snd_local.h.
SND_CHUNK_SIZE
#define SND_CHUNK_SIZE 1024
Definition at line 31 of file snd_local.h.
SND_CHUNK_SIZE_BYTE
#define SND_CHUNK_SIZE_BYTE (SND_CHUNK_SIZE*2)
Definition at line 33 of file snd_local.h.
SND_CHUNK_SIZE_FLOAT
#define SND_CHUNK_SIZE_FLOAT (SND_CHUNK_SIZE/2)
Definition at line 32 of file snd_local.h.
START_SAMPLE_IMMEDIATE
#define START_SAMPLE_IMMEDIATE 0x7fffffff
Definition at line 73 of file snd_local.h.
WAV_FORMAT_PCM
#define WAV_FORMAT_PCM 1
Definition at line 109 of file snd_local.h.
Typedef Documentation
srcHandle_t
typedef int srcHandle_t
Definition at line 251 of file snd_local.h.
Enumeration Type Documentation
alSrcPriority_t
enum alSrcPriority_t
Enumerator
SRCPRI_AMBIENT
SRCPRI_ENTITY
SRCPRI_ONESHOT
SRCPRI_LOCAL
SRCPRI_STREAM
Definition at line 242 of file snd_local.h.
 {
     SRCPRI_AMBIENT = 0, // Ambient sound effects
     SRCPRI_ENTITY,          // Entity sound effects
     SRCPRI_ONESHOT,         // One-shot sounds
     SRCPRI_LOCAL,               // Local sounds
     SRCPRI_STREAM               // Streams (music, cutscenes)
 } alSrcPriority_t;
Function Documentation
decodeWavelet()
void decodeWavelet (sndBuffer * stream, short * packets)
Definition at line 171 of file snd_wavelet.c.
{
     float           wksp[4097];
     int             i;
     byte            *out;
     int size = chunk->size;
     out = (byte *)chunk->sndChunk;
     for(i=0;i<size;i++) {
         wksp[i] = mulawToShort[out[i]];
     }
     wt1(wksp, size, -1);
     if (!to) return;
     for(i=0; i<size; i++) {
         to[i] = wksp[i];
     }
 }
References mulawToShort, out, and wt1().
Referenced by S_PaintChannelFromWavelet().
encodeMuLaw()
void encodeMuLaw (sfx_t * sfx, short * packets)
Definition at line 193 of file snd_wavelet.c.
{
     int     i, samples, size, grade, poop;
     sndBuffer       *newchunk, *chunk;
     byte            *out;
     if (!madeTable) {
         for (i=0;i<256;i++) {
             mulawToShort[i] = (float)MuLawDecode((byte)i);
         }
         madeTable = qtrue;
     }
     chunk = NULL;
     samples = sfx->soundLength;
     grade = 0;
     while(samples>0) {
         size = samples;
         if (size>(SND_CHUNK_SIZE*2)) {
             size = (SND_CHUNK_SIZE*2);
         }
         newchunk = SND_malloc();
         if (sfx->soundData == NULL) {
             sfx->soundData = newchunk;
         } else {
             chunk->next = newchunk;
         }
         chunk = newchunk;
         out = (byte *)chunk->sndChunk;
         for(i=0; i<size; i++) {
             poop = packets[0]+grade;
             if (poop>32767) {
                 poop = 32767;
             } else if (poop<-32768) {
                 poop = -32768;
             }
             out[i] = MuLawEncode((short)poop);
             grade = poop - mulawToShort[out[i]];
             packets++;
         }
         chunk->size = size;
         samples -= size;
     }
 }
References madeTable, MuLawDecode(), MuLawEncode(), mulawToShort, NULL, out, qtrue, SND_CHUNK_SIZE, and SND_malloc().
Referenced by S_LoadSound().
encodeWavelet()
void encodeWavelet (sfx_t * sfx, short * packets)
Definition at line 121 of file snd_wavelet.c.
{
     float   wksp[4097], temp;
     int     i, samples, size;
     sndBuffer       *newchunk, *chunk;
     byte            *out;
     if (!madeTable) {
         for (i=0;i<256;i++) {
             mulawToShort[i] = (float)MuLawDecode((byte)i);
         }
         madeTable = qtrue;
     }
     chunk = NULL;
     samples = sfx->soundLength;
     while(samples>0) {
         size = samples;
         if (size>(SND_CHUNK_SIZE*2)) {
             size = (SND_CHUNK_SIZE*2);
         }
         if (size<4) {
             size = 4;
         }
         newchunk = SND_malloc();
         if (sfx->soundData == NULL) {
             sfx->soundData = newchunk;
         } else {
             chunk->next = newchunk;
         }
         chunk = newchunk;
         for(i=0; i<size; i++) {
             wksp[i] = *packets;
             packets++;
         }
         wt1(wksp, size, 1);
         out = (byte *)chunk->sndChunk;
         for(i=0;i<size;i++) {
             temp = wksp[i];
             if (temp > 32767) temp = 32767; else if (temp<-32768) temp = -32768;
             out[i] = MuLawEncode((short)temp);
         }
         chunk->size = size;
         samples -= size;
     }
 }
References madeTable, MuLawDecode(), MuLawEncode(), mulawToShort, NULL, out, qtrue, SND_CHUNK_SIZE, SND_malloc(), and wt1().
Referenced by S_LoadSound().
S_AdpcmEncodeSound()
void S_AdpcmEncodeSound (sfx_t * sfx, short * samples)
Definition at line 290 of file snd_adpcm.c.
{
     adpcm_state_t   state;
     int             inOffset;
     int             count;
     int             n;
     sndBuffer       *newchunk, *chunk;
     byte            *out;
     inOffset = 0;
     count = sfx->soundLength;
     state.index = 0;
     state.sample = samples[0];
     chunk = NULL;
     while( count ) {
         n = count;
         if( n > SND_CHUNK_SIZE_BYTE*2 ) {
             n = SND_CHUNK_SIZE_BYTE*2;
         }
         newchunk = SND_malloc();
         if (sfx->soundData == NULL) {
             sfx->soundData = newchunk;
         } else {
             chunk->next = newchunk;
         }
         chunk = newchunk;
         // output the header
         chunk->adpcm.index  = state.index;
         chunk->adpcm.sample = state.sample;
         out = (byte *)chunk->sndChunk;
         // encode the samples
         S_AdpcmEncode( samples + inOffset, (char *) out, n, &state );
         inOffset += n;
         count -= n;
     }
 }
References NULL, out, S_AdpcmEncode(), SND_CHUNK_SIZE_BYTE, and SND_malloc().
Referenced by S_LoadSound().
S_AdpcmGetSamples()
void S_AdpcmGetSamples (sndBuffer * chunk, short * to)
Definition at line 271 of file snd_adpcm.c.
{
     adpcm_state_t   state;
     byte            *out;
     // get the starting state from the block header
     state.index = chunk->adpcm.index;
     state.sample = chunk->adpcm.sample;
     out = (byte *)chunk->sndChunk;
     // get samples
     S_AdpcmDecode((char *) out, to, SND_CHUNK_SIZE_BYTE*2, &state );
 }
References out, S_AdpcmDecode(), and SND_CHUNK_SIZE_BYTE.
Referenced by S_PaintChannelFromADPCM(), and S_PaintChannelFromWavelet().
S_AdpcmMemoryNeeded()
int S_AdpcmMemoryNeeded (const wavinfo_t * info)
Definition at line 237 of file snd_adpcm.c.
{
     float   scale;
     int     scaledSampleCount;
     int     sampleMemory;
     int     blockCount;
     int     headerMemory;
     // determine scale to convert from input sampling rate to desired sampling rate
     scale = (float)info->rate / dma.speed;
     // calc number of samples at playback sampling rate
     scaledSampleCount = info->samples / scale;
     // calc memory need to store those samples using ADPCM at 4 bits per sample
     sampleMemory = scaledSampleCount / 2;
     // calc number of sample blocks needed of PAINTBUFFER_SIZE
     blockCount = scaledSampleCount / PAINTBUFFER_SIZE;
     if( scaledSampleCount % PAINTBUFFER_SIZE ) {
         blockCount++;
     }
     // calc memory needed to store the block headers
     headerMemory = blockCount * sizeof(adpcm_state_t);
     return sampleMemory + headerMemory;
 }
References dma, info, PAINTBUFFER_SIZE, and dma_t::speed.
S_AL_Init()
qboolean S_AL_Init (soundInterface_t * si)
Definition at line 2383 of file snd_openal.c.
 {
 #ifdef USE_OPENAL
     const char* device = NULL;
     const char* inputdevice = NULL;
     int i;
     if( !si ) {
         return qfalse;
     }
     for (i = 0; i < MAX_RAW_STREAMS; i++) {
         streamSourceHandles[i] = -1;
         streamPlaying[i] = qfalse;
         streamSources[i] = 0;
     }
     // New console variables
     s_alPrecache = Cvar_Get( "s_alPrecache", "1", CVAR_ARCHIVE );
     s_alGain = Cvar_Get( "s_alGain", "1.0", CVAR_ARCHIVE );
     s_alSources = Cvar_Get( "s_alSources", "96", CVAR_ARCHIVE );
     s_alDopplerFactor = Cvar_Get( "s_alDopplerFactor", "1.0", CVAR_ARCHIVE );
     s_alDopplerSpeed = Cvar_Get( "s_alDopplerSpeed", "2200", CVAR_ARCHIVE );
     s_alMinDistance = Cvar_Get( "s_alMinDistance", "120", CVAR_CHEAT );
     s_alMaxDistance = Cvar_Get("s_alMaxDistance", "1024", CVAR_CHEAT);
     s_alRolloff = Cvar_Get( "s_alRolloff", "2", CVAR_CHEAT);
     s_alGraceDistance = Cvar_Get("s_alGraceDistance", "512", CVAR_CHEAT);
     s_alDriver = Cvar_Get( "s_alDriver", ALDRIVER_DEFAULT, CVAR_ARCHIVE | CVAR_LATCH );
     s_alInputDevice = Cvar_Get( "s_alInputDevice", "", CVAR_ARCHIVE | CVAR_LATCH );
     s_alDevice = Cvar_Get("s_alDevice", "", CVAR_ARCHIVE | CVAR_LATCH);
     // Load QAL
     if( !QAL_Init( s_alDriver->string ) )
     {
         Com_Printf( "Failed to load library: \"%s\".\n", s_alDriver->string );
         return qfalse;
     }
     device = s_alDevice->string;
     if(device && !*device)
         device = NULL;
     inputdevice = s_alInputDevice->string;
     if(inputdevice && !*inputdevice)
         inputdevice = NULL;
     // Device enumeration support
     enumeration_all_ext = qalcIsExtensionPresent(NULL, "ALC_ENUMERATE_ALL_EXT");
     enumeration_ext = qalcIsExtensionPresent(NULL, "ALC_ENUMERATION_EXT");
     if(enumeration_ext || enumeration_all_ext)
     {
         char devicenames[16384] = "";
         const char *devicelist;
 #ifdef _WIN32
         const char *defaultdevice;
 #endif
         int curlen;
         // get all available devices + the default device name.
         if(enumeration_all_ext)
         {
             devicelist = qalcGetString(NULL, ALC_ALL_DEVICES_SPECIFIER);
 #ifdef _WIN32
             defaultdevice = qalcGetString(NULL, ALC_DEFAULT_ALL_DEVICES_SPECIFIER);
 #endif
         }
         else
         {
             // We don't have ALC_ENUMERATE_ALL_EXT but normal enumeration.
             devicelist = qalcGetString(NULL, ALC_DEVICE_SPECIFIER);
 #ifdef _WIN32
             defaultdevice = qalcGetString(NULL, ALC_DEFAULT_DEVICE_SPECIFIER);
 #endif
             enumeration_ext = qtrue;
         }
 #ifdef _WIN32
         // check whether the default device is generic hardware. If it is, change to
         // Generic Software as that one works more reliably with various sound systems.
         // If it's not, use OpenAL's default selection as we don't want to ignore
         // native hardware acceleration.
         if(!device && defaultdevice && !strcmp(defaultdevice, "Generic Hardware"))
             device = "Generic Software";
 #endif
         // dump a list of available devices to a cvar for the user to see.
         if(devicelist)
         {
             while((curlen = strlen(devicelist)))
             {
                 Q_strcat(devicenames, sizeof(devicenames), devicelist);
                 Q_strcat(devicenames, sizeof(devicenames), "\n");
                 devicelist += curlen + 1;
             }
         }
         else
             devicelist = "";
         s_alAvailableDevices = Cvar_Get("s_alAvailableDevices", devicenames, CVAR_ROM | CVAR_NORESTART);
     }
     alDevice = qalcOpenDevice(device);
     if( !alDevice && device )
     {
         Com_Printf( "Failed to open OpenAL device '%s', trying default.\n", device );
         alDevice = qalcOpenDevice(NULL);
     }
     if( !alDevice )
     {
         QAL_Shutdown( );
         Com_Printf( "Failed to open OpenAL device.\n" );
         return qfalse;
     }
     // Create OpenAL context
     alContext = qalcCreateContext( alDevice, NULL );
     if( !alContext )
     {
         QAL_Shutdown( );
         qalcCloseDevice( alDevice );
         Com_Printf( "Failed to create OpenAL context.\n" );
         return qfalse;
     }
     qalcMakeContextCurrent( alContext );
     // Initialize sources, buffers, music
     S_AL_BufferInit( );
     S_AL_SrcInit( );
     // Set up OpenAL parameters (doppler, etc)
     qalDistanceModel(AL_INVERSE_DISTANCE_CLAMPED);
     qalDopplerFactor( s_alDopplerFactor->value );
     qalDopplerVelocity( s_alDopplerSpeed->value );
 #ifdef USE_VOIP
     // !!! FIXME: some of these alcCaptureOpenDevice() values should be cvars.
     // !!! FIXME: add support for capture device enumeration.
     // !!! FIXME: add some better error reporting.
     s_alCapture = Cvar_Get( "s_alCapture", "1", CVAR_ARCHIVE | CVAR_LATCH );
     if (!s_alCapture->integer)
     {
         Com_Printf("OpenAL capture support disabled by user ('+set s_alCapture 1' to enable)\n");
     }
 #if USE_MUMBLE
     else if (cl_useMumble->integer)
     {
         Com_Printf("OpenAL capture support disabled for Mumble support\n");
     }
 #endif
     else
     {
 #ifdef MACOS_X
         // !!! FIXME: Apple has a 1.1-compliant OpenAL, which includes
         // !!! FIXME:  capture support, but they don't list it in the
         // !!! FIXME:  extension string. We need to check the version string,
         // !!! FIXME:  then the extension string, but that's too much trouble,
         // !!! FIXME:  so we'll just check the function pointer for now.
         if (qalcCaptureOpenDevice == NULL)
 #else
         if (!qalcIsExtensionPresent(NULL, "ALC_EXT_capture"))
 #endif
         {
             Com_Printf("No ALC_EXT_capture support, can't record audio.\n");
         }
         else
         {
             char inputdevicenames[16384] = "";
             const char *inputdevicelist;
             const char *defaultinputdevice;
             int curlen;
             capture_ext = qtrue;
             // get all available input devices + the default input device name.
             inputdevicelist = qalcGetString(NULL, ALC_CAPTURE_DEVICE_SPECIFIER);
             defaultinputdevice = qalcGetString(NULL, ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER);
             // dump a list of available devices to a cvar for the user to see.
             while((curlen = strlen(inputdevicelist)))
             {
                 Q_strcat(inputdevicenames, sizeof(inputdevicenames), inputdevicelist);
                 Q_strcat(inputdevicenames, sizeof(inputdevicenames), "\n");
                 inputdevicelist += curlen + 1;
             }
             s_alAvailableInputDevices = Cvar_Get("s_alAvailableInputDevices", inputdevicenames, CVAR_ROM | CVAR_NORESTART);
             // !!! FIXME: 8000Hz is what Speex narrowband mode needs, but we
             // !!! FIXME:  should probably open the capture device after
             // !!! FIXME:  initializing Speex so we can change to wideband
             // !!! FIXME:  if we like.
             Com_Printf("OpenAL default capture device is '%s'\n", defaultinputdevice);
             alCaptureDevice = qalcCaptureOpenDevice(inputdevice, 8000, AL_FORMAT_MONO16, 4096);
             if( !alCaptureDevice && inputdevice )
             {
                 Com_Printf( "Failed to open OpenAL Input device '%s', trying default.\n", inputdevice );
                 alCaptureDevice = qalcCaptureOpenDevice(NULL, 8000, AL_FORMAT_MONO16, 4096);
             }
             Com_Printf( "OpenAL capture device %s.\n",
                     (alCaptureDevice == NULL) ? "failed to open" : "opened");
         }
     }
 #endif
     si->Shutdown = S_AL_Shutdown;
     si->StartSound = S_AL_StartSound;
     si->StartLocalSound = S_AL_StartLocalSound;
     si->StartBackgroundTrack = S_AL_StartBackgroundTrack;
     si->StopBackgroundTrack = S_AL_StopBackgroundTrack;
     si->RawSamples = S_AL_RawSamples;
     si->StopAllSounds = S_AL_StopAllSounds;
     si->ClearLoopingSounds = S_AL_ClearLoopingSounds;
     si->AddLoopingSound = S_AL_AddLoopingSound;
     si->AddRealLoopingSound = S_AL_AddRealLoopingSound;
     si->StopLoopingSound = S_AL_StopLoopingSound;
     si->Respatialize = S_AL_Respatialize;
     si->UpdateEntityPosition = S_AL_UpdateEntityPosition;
     si->Update = S_AL_Update;
     si->DisableSounds = S_AL_DisableSounds;
     si->BeginRegistration = S_AL_BeginRegistration;
     si->RegisterSound = S_AL_RegisterSound;
     si->ClearSoundBuffer = S_AL_ClearSoundBuffer;
     si->SoundInfo = S_AL_SoundInfo;
     si->SoundList = S_AL_SoundList;
 #ifdef USE_VOIP
     si->StartCapture = S_AL_StartCapture;
     si->AvailableCaptureSamples = S_AL_AvailableCaptureSamples;
     si->Capture = S_AL_Capture;
     si->StopCapture = S_AL_StopCapture;
     si->MasterGain = S_AL_MasterGain;
 #endif
     return qtrue;
 #else
     return qfalse;
 #endif
 }
References soundInterface_t::AddLoopingSound, soundInterface_t::AddRealLoopingSound, AL_FORMAT_MONO16, AL_INVERSE_DISTANCE_CLAMPED, ALC_ALL_DEVICES_SPECIFIER, ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER, ALC_CAPTURE_DEVICE_SPECIFIER, ALC_DEFAULT_ALL_DEVICES_SPECIFIER, ALC_DEFAULT_DEVICE_SPECIFIER, ALC_DEVICE_SPECIFIER, soundInterface_t::BeginRegistration, soundInterface_t::ClearLoopingSounds, soundInterface_t::ClearSoundBuffer, Com_Printf(), CVAR_ARCHIVE, CVAR_CHEAT, Cvar_Get(), CVAR_LATCH, CVAR_NORESTART, CVAR_ROM, soundInterface_t::DisableSounds, MAX_RAW_STREAMS, NULL, Q_strcat(), QAL_Init(), QAL_Shutdown(), qalcCaptureOpenDevice, qalcCloseDevice, qalcCreateContext, qalcGetString, qalcIsExtensionPresent, qalcMakeContextCurrent, qalcOpenDevice, qalDistanceModel, qalDopplerFactor, qalDopplerVelocity, qfalse, qtrue, soundInterface_t::RawSamples, soundInterface_t::RegisterSound, soundInterface_t::Respatialize, soundInterface_t::Shutdown, si, soundInterface_t::SoundInfo, soundInterface_t::SoundList, soundInterface_t::StartBackgroundTrack, soundInterface_t::StartLocalSound, soundInterface_t::StartSound, soundInterface_t::StopAllSounds, soundInterface_t::StopBackgroundTrack, soundInterface_t::StopLoopingSound, soundInterface_t::Update, and soundInterface_t::UpdateEntityPosition.
Referenced by S_Init().
S_Base_Init()
qboolean S_Base_Init (soundInterface_t * si)
Definition at line 1486 of file snd_dma.c.
{
     qboolean    r;
     if( !si ) {
         return qfalse;
     }
     s_mixahead = Cvar_Get ("s_mixahead", "0.2", CVAR_ARCHIVE);
     s_mixPreStep = Cvar_Get ("s_mixPreStep", "0.05", CVAR_ARCHIVE);
     s_show = Cvar_Get ("s_show", "0", CVAR_CHEAT);
     s_testsound = Cvar_Get ("s_testsound", "0", CVAR_CHEAT);
     r = SNDDMA_Init();
     if ( r ) {
         s_soundStarted = 1;
         s_soundMuted = 1;
 //      s_numSfx = 0;
         Com_Memset(sfxHash, 0, sizeof(sfx_t *)*LOOP_HASH);
         s_soundtime = 0;
         s_paintedtime = 0;
         S_Base_StopAllSounds( );
     } else {
         return qfalse;
     }
     si->Shutdown = S_Base_Shutdown;
     si->StartSound = S_Base_StartSound;
     si->StartLocalSound = S_Base_StartLocalSound;
     si->StartBackgroundTrack = S_Base_StartBackgroundTrack;
     si->StopBackgroundTrack = S_Base_StopBackgroundTrack;
     si->RawSamples = S_Base_RawSamples;
     si->StopAllSounds = S_Base_StopAllSounds;
     si->ClearLoopingSounds = S_Base_ClearLoopingSounds;
     si->AddLoopingSound = S_Base_AddLoopingSound;
     si->AddRealLoopingSound = S_Base_AddRealLoopingSound;
     si->StopLoopingSound = S_Base_StopLoopingSound;
     si->Respatialize = S_Base_Respatialize;
     si->UpdateEntityPosition = S_Base_UpdateEntityPosition;
     si->Update = S_Base_Update;
     si->DisableSounds = S_Base_DisableSounds;
     si->BeginRegistration = S_Base_BeginRegistration;
     si->RegisterSound = S_Base_RegisterSound;
     si->ClearSoundBuffer = S_Base_ClearSoundBuffer;
     si->SoundInfo = S_Base_SoundInfo;
     si->SoundList = S_Base_SoundList;
 #ifdef USE_VOIP
     si->StartCapture = S_Base_StartCapture;
     si->AvailableCaptureSamples = S_Base_AvailableCaptureSamples;
     si->Capture = S_Base_Capture;
     si->StopCapture = S_Base_StopCapture;
     si->MasterGain = S_Base_MasterGain;
 #endif
     return qtrue;
 }
References soundInterface_t::AddLoopingSound, soundInterface_t::AddRealLoopingSound, soundInterface_t::BeginRegistration, soundInterface_t::ClearLoopingSounds, soundInterface_t::ClearSoundBuffer, Com_Memset, CVAR_ARCHIVE, CVAR_CHEAT, Cvar_Get(), soundInterface_t::DisableSounds, LOOP_HASH, qfalse, qtrue, soundInterface_t::RawSamples, soundInterface_t::RegisterSound, soundInterface_t::Respatialize, S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_BeginRegistration(), S_Base_ClearLoopingSounds(), S_Base_ClearSoundBuffer(), S_Base_DisableSounds(), S_Base_RawSamples(), S_Base_RegisterSound(), S_Base_Respatialize(), S_Base_Shutdown(), S_Base_SoundInfo(), S_Base_SoundList(), S_Base_StartBackgroundTrack(), S_Base_StartLocalSound(), S_Base_StartSound(), S_Base_StopAllSounds(), S_Base_StopBackgroundTrack(), S_Base_StopLoopingSound(), S_Base_Update(), S_Base_UpdateEntityPosition(), s_mixahead, s_mixPreStep, s_paintedtime, s_show, s_soundMuted, s_soundStarted, s_soundtime, s_testsound, sfxHash, soundInterface_t::Shutdown, si, SNDDMA_Init(), soundInterface_t::SoundInfo, soundInterface_t::SoundList, soundInterface_t::StartBackgroundTrack, soundInterface_t::StartLocalSound, soundInterface_t::StartSound, soundInterface_t::StopAllSounds, soundInterface_t::StopBackgroundTrack, soundInterface_t::StopLoopingSound, soundInterface_t::Update, and soundInterface_t::UpdateEntityPosition.
Referenced by S_Init().
S_FreeOldestSound()
void S_FreeOldestSound (void)
Definition at line 1433 of file snd_dma.c.
{
     int i, oldest, used;
     sfx_t   *sfx;
     sndBuffer   *buffer, *nbuffer;
     oldest = Com_Milliseconds();
     used = 0;
     for (i=1 ; i < s_numSfx ; i++) {
         sfx = &s_knownSfx[i];
         if (sfx->inMemory && sfx->lastTimeUsed<oldest) {
             used = i;
             oldest = sfx->lastTimeUsed;
         }
     }
     sfx = &s_knownSfx[used];
     Com_DPrintf("S_FreeOldestSound: freeing sound %s\n", sfx->soundName);
     buffer = sfx->soundData;
     while(buffer != NULL) {
         nbuffer = buffer->next;
         SND_free(buffer);
         buffer = nbuffer;
     }
     sfx->inMemory = qfalse;
     sfx->soundData = NULL;
 }
References Com_DPrintf(), Com_Milliseconds(), NULL, qfalse, s_knownSfx, s_numSfx, and SND_free().
Referenced by SND_malloc().
S_LoadSound()
qboolean S_LoadSound (sfx_t * sfx)
Definition at line 204 of file snd_mem.c.
 {
     byte    *data;
     short   *samples;
     snd_info_t  info;
 //  int     size;
     // player specific sounds are never directly loaded
     if ( sfx->soundName[0] == '*') {
         return qfalse;
     }
     // load it in
     data = S_CodecLoad(sfx->soundName, &info);
     if(!data)
         return qfalse;
     if ( info.width == 1 ) {
         Com_DPrintf(S_COLOR_YELLOW "WARNING: %s is a 8 bit wav file\n", sfx->soundName);
     }
     samples = Hunk_AllocateTempMemory(info.samples * sizeof(short) * 2);
     sfx->lastTimeUsed = Com_Milliseconds()+1;
     // each of these compression schemes works just fine
     // but the 16bit quality is much nicer and with a local
     // install assured we can rely upon the sound memory
     // manager to do the right thing for us and page
     // sound in as needed
     if( sfx->soundCompressed == qtrue) {
         sfx->soundCompressionMethod = 1;
         sfx->soundData = NULL;
         sfx->soundLength = ResampleSfxRaw( samples, info.rate, info.width, info.samples, data + info.dataofs );
         S_AdpcmEncodeSound(sfx, samples);
 #if 0
     } else if (info.samples>(SND_CHUNK_SIZE*16) && info.width >1) {
         sfx->soundCompressionMethod = 3;
         sfx->soundData = NULL;
         sfx->soundLength = ResampleSfxRaw( samples, info.rate, info.width, info.samples, (data + info.dataofs) );
         encodeMuLaw( sfx, samples);
     } else if (info.samples>(SND_CHUNK_SIZE*6400) && info.width >1) {
         sfx->soundCompressionMethod = 2;
         sfx->soundData = NULL;
         sfx->soundLength = ResampleSfxRaw( samples, info.rate, info.width, info.samples, (data + info.dataofs) );
         encodeWavelet( sfx, samples);
 #endif
     } else {
         sfx->soundCompressionMethod = 0;
         sfx->soundLength = info.samples;
         sfx->soundData = NULL;
         ResampleSfx( sfx, info.rate, info.width, data + info.dataofs, qfalse );
     }
     Hunk_FreeTempMemory(samples);
     Hunk_FreeTempMemory(data);
     return qtrue;
 }
References Com_DPrintf(), Com_Milliseconds(), encodeMuLaw(), encodeWavelet(), Hunk_AllocateTempMemory(), Hunk_FreeTempMemory(), info, NULL, qfalse, qtrue, ResampleSfx(), ResampleSfxRaw(), S_AdpcmEncodeSound(), S_CodecLoad(), S_COLOR_YELLOW, and SND_CHUNK_SIZE.
Referenced by S_memoryLoad().
S_memoryLoad()
void S_memoryLoad (sfx_t * sfx)
Definition at line 400 of file snd_dma.c.
{
     // load the sound file
     if ( !S_LoadSound ( sfx ) ) {
 //      Com_Printf( S_COLOR_YELLOW "WARNING: couldn't load sound: %s\n", sfx->soundName );
         sfx->defaultSound = qtrue;
     }
     sfx->inMemory = qtrue;
 }
References qtrue, and S_LoadSound().
Referenced by S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_RegisterSound(), and S_Base_StartSound().
S_PaintChannels()
void S_PaintChannels (int endtime)
Definition at line 631 of file snd_mix.c.
{
     int     i;
     int     end;
     int     stream;
     channel_t *ch;
     sfx_t   *sc;
     int     ltime, count;
     int     sampleOffset;
     if(s_muted->integer)
         snd_vol = 0;
     else
         snd_vol = s_volume->value*255;
 //Com_Printf ("%i to %i\n", s_paintedtime, endtime);
     while ( s_paintedtime < endtime ) {
         // if paintbuffer is smaller than DMA buffer
         // we may need to fill it multiple times
         end = endtime;
         if ( endtime - s_paintedtime > PAINTBUFFER_SIZE ) {
             end = s_paintedtime + PAINTBUFFER_SIZE;
         }
         // clear the paint buffer and mix any raw samples...
         Com_Memset(paintbuffer, 0, sizeof (paintbuffer));
         for (stream = 0; stream < MAX_RAW_STREAMS; stream++) {
             if ( s_rawend[stream] >= s_paintedtime ) {
                 // copy from the streaming sound source
                 const portable_samplepair_t *rawsamples = s_rawsamples[stream];
                 const int stop = (end < s_rawend[stream]) ? end : s_rawend[stream];
                 for ( i = s_paintedtime ; i < stop ; i++ ) {
                     const int s = i&(MAX_RAW_SAMPLES-1);
                     paintbuffer[i-s_paintedtime].left += rawsamples[s].left;
                     paintbuffer[i-s_paintedtime].right += rawsamples[s].right;
                 }
             }
         }
         // paint in the channels.
         ch = s_channels;
         for ( i = 0; i < MAX_CHANNELS ; i++, ch++ ) {
             if ( !ch->thesfx || (ch->leftvol<0.25 && ch->rightvol<0.25 )) {
                 continue;
             }
             ltime = s_paintedtime;
             sc = ch->thesfx;
             sampleOffset = ltime - ch->startSample;
             count = end - ltime;
             if ( sampleOffset + count > sc->soundLength ) {
                 count = sc->soundLength - sampleOffset;
             }
             if ( count > 0 ) {
                 if( sc->soundCompressionMethod == 1) {
                     S_PaintChannelFromADPCM     (ch, sc, count, sampleOffset, ltime - s_paintedtime);
                 } else if( sc->soundCompressionMethod == 2) {
                     S_PaintChannelFromWavelet   (ch, sc, count, sampleOffset, ltime - s_paintedtime);
                 } else if( sc->soundCompressionMethod == 3) {
                     S_PaintChannelFromMuLaw (ch, sc, count, sampleOffset, ltime - s_paintedtime);
                 } else {
                     S_PaintChannelFrom16        (ch, sc, count, sampleOffset, ltime - s_paintedtime);
                 }
             }
         }
         // paint in the looped channels.
         ch = loop_channels;
         for ( i = 0; i < numLoopChannels ; i++, ch++ ) {
             if ( !ch->thesfx || (!ch->leftvol && !ch->rightvol )) {
                 continue;
             }
             ltime = s_paintedtime;
             sc = ch->thesfx;
             if (sc->soundData==NULL || sc->soundLength==0) {
                 continue;
             }
             // we might have to make two passes if it
             // is a looping sound effect and the end of
             // the sample is hit
             do {
                 sampleOffset = (ltime % sc->soundLength);
                 count = end - ltime;
                 if ( sampleOffset + count > sc->soundLength ) {
                     count = sc->soundLength - sampleOffset;
                 }
                 if ( count > 0 ) {
                     if( sc->soundCompressionMethod == 1) {
                         S_PaintChannelFromADPCM     (ch, sc, count, sampleOffset, ltime - s_paintedtime);
                     } else if( sc->soundCompressionMethod == 2) {
                         S_PaintChannelFromWavelet   (ch, sc, count, sampleOffset, ltime - s_paintedtime);
                     } else if( sc->soundCompressionMethod == 3) {
                         S_PaintChannelFromMuLaw     (ch, sc, count, sampleOffset, ltime - s_paintedtime);
                     } else {
                         S_PaintChannelFrom16        (ch, sc, count, sampleOffset, ltime - s_paintedtime);
                     }
                     ltime += count;
                 }
             } while ( ltime < end);
         }
         // transfer out according to DMA format
         S_TransferPaintBuffer( end );
         s_paintedtime = end;
     }
 }
References Com_Memset, portable_samplepair_t::left, channel_t::leftvol, loop_channels, MAX_CHANNELS, MAX_RAW_SAMPLES, MAX_RAW_STREAMS, NULL, numLoopChannels, paintbuffer, PAINTBUFFER_SIZE, portable_samplepair_t::right, channel_t::rightvol, s_channels, s_muted, S_PaintChannelFrom16(), S_PaintChannelFromADPCM(), S_PaintChannelFromMuLaw(), S_PaintChannelFromWavelet(), s_paintedtime, s_rawend, s_rawsamples, S_TransferPaintBuffer(), s_volume, snd_vol, channel_t::startSample, and channel_t::thesfx.
Referenced by S_Update_().
S_Spatialize()
void S_Spatialize (channel_t * ch)
SND_free()
void SND_free (sndBuffer * v)
Definition at line 54 of file snd_mem.c.
{
     *(sndBuffer **)v = freelist;
     freelist = (sndBuffer*)v;
     inUse += sizeof(sndBuffer);
 }
References freelist, and inUse.
Referenced by S_FreeOldestSound().
SND_malloc()
sndBuffer* SND_malloc (void)
Definition at line 60 of file snd_mem.c.
{
     sndBuffer *v;
 redo:
     if (freelist == NULL) {
         S_FreeOldestSound();
         goto redo;
     }
     inUse -= sizeof(sndBuffer);
     totalInUse += sizeof(sndBuffer);
     v = freelist;
     freelist = *(sndBuffer **)freelist;
     v->next = NULL;
     return v;
 }
References freelist, inUse, NULL, S_FreeOldestSound(), and totalInUse.
Referenced by encodeMuLaw(), encodeWavelet(), ResampleSfx(), S_AdpcmEncodeSound(), and S_DefaultSound().
SND_setup()
void SND_setup (void)
Definition at line 77 of file snd_mem.c.
                      {
     sndBuffer *p, *q;
     cvar_t  *cv;
     int scs;
     cv = Cvar_Get( "com_soundMegs", DEF_COMSOUNDMEGS, CVAR_LATCH | CVAR_ARCHIVE );
     scs = (cv->integer*1536);
     buffer = malloc(scs*sizeof(sndBuffer) );
     // allocate the stack based hunk allocator
     sfxScratchBuffer = malloc(SND_CHUNK_SIZE * sizeof(short) * 4);  //Hunk_Alloc(SND_CHUNK_SIZE * sizeof(short) * 4);
     sfxScratchPointer = NULL;
     inUse = scs*sizeof(sndBuffer);
     p = buffer;;
     q = p + scs;
     while (--q > p)
         *(sndBuffer **)q = q-1;
     *(sndBuffer **)q = NULL;
     freelist = p + scs - 1;
     Com_Printf("Sound memory manager started\n");
 }
References buffer, Com_Printf(), CVAR_ARCHIVE, Cvar_Get(), CVAR_LATCH, DEF_COMSOUNDMEGS, freelist, inUse, NULL, sfxScratchBuffer, sfxScratchPointer, and SND_CHUNK_SIZE.
Referenced by S_Base_BeginRegistration().
SND_shutdown()
void SND_shutdown (void)
Definition at line 103 of file snd_mem.c.
 {
         free(sfxScratchBuffer);
         free(buffer);
 }
References sfxScratchBuffer.
Referenced by S_Base_Shutdown().
SNDDMA_BeginPainting()
void SNDDMA_BeginPainting (void)
Definition at line 43 of file null_snddma.c.
 {
 }
References SDL_LockAudio().
Referenced by S_Base_ClearSoundBuffer(), and S_Update_().
SNDDMA_GetDMAPos()
int SNDDMA_GetDMAPos (void)
Definition at line 34 of file null_snddma.c.
 {
     return 0;
 }
References dmapos.
Referenced by S_GetSoundtime().
SNDDMA_Init()
qboolean SNDDMA_Init (void)
Definition at line 29 of file null_snddma.c.
 {
     return qfalse;
 }
References AUDIO_S16SYS, AUDIO_U8, dma_t::buffer, dma_t::channels, SDL_AudioSpec::channels, Com_Printf(), CVAR_ARCHIVE, Cvar_Get(), desired, dma, dmapos, dmasize, SDL_AudioSpec::format, SDL_AudioSpec::freq, int(), NULL, qfalse, qtrue, s_sdlBits, s_sdlChannels, s_sdlDevSamps, s_sdlMixSamps, s_sdlSpeed, dma_t::samplebits, dma_t::samples, SDL_AudioSpec::samples, SDL_AudioDriverName(), SDL_GetError(), SDL_Init(), SDL_INIT_AUDIO, SDL_OpenAudio(), SDL_PauseAudio(), SDL_QuitSubSystem(), SDL_WasInit(), snd_inited, SNDDMA_AudioCallback(), SNDDMA_PrintAudiospec(), dma_t::speed, dma_t::submission_chunk, and val.
Referenced by S_Base_Init().
SNDDMA_Shutdown()
void SNDDMA_Shutdown (void)
Definition at line 39 of file null_snddma.c.
 {
 }
References dma_t::buffer, Com_Printf(), dma, dmapos, dmasize, NULL, qfalse, SDL_CloseAudio(), SDL_INIT_AUDIO, SDL_PauseAudio(), SDL_QuitSubSystem(), and snd_inited.
Referenced by S_Base_Shutdown().
SNDDMA_Submit()
void SNDDMA_Submit (void)
Definition at line 47 of file null_snddma.c.
 {
 }
References SDL_UnlockAudio().
Referenced by S_Base_ClearSoundBuffer(), and S_Update_().
Variable Documentation
dma
dma_t dma
Definition at line 61 of file snd_dma.c.
Referenced by CL_OpenAVIForWriting(), ResampleSfx(), ResampleSfxRaw(), S_AdpcmMemoryNeeded(), S_Base_ClearSoundBuffer(), S_Base_RawSamples(), S_Base_SoundInfo(), S_GetSoundtime(), S_SpatializeOrigin(), S_TransferPaintBuffer(), S_TransferStereo16(), S_Update_(), S_UpdateBackgroundTrack(), SNDDMA_AudioCallback(), SNDDMA_Init(), and SNDDMA_Shutdown().
listener_forward
vec3_t listener_forward
listener_right
vec3_t listener_right
listener_up
vec3_t listener_up
loop_channels
channel_t loop_channels[MAX_CHANNELS]
Definition at line 55 of file snd_dma.c.
Referenced by S_AddLoopSounds(), S_Base_ClearSoundBuffer(), and S_PaintChannels().
mulawToShort
short mulawToShort[256]
Definition at line 111 of file snd_wavelet.c.
Referenced by decodeMuLaw(), decodeWavelet(), encodeMuLaw(), encodeWavelet(), and S_PaintChannelFromMuLaw().
numLoopChannels
int numLoopChannels
Definition at line 56 of file snd_dma.c.
Referenced by S_AddLoopSounds(), S_Base_ClearLoopingSounds(), S_Base_ClearSoundBuffer(), and S_PaintChannels().
s_channels
channel_t s_channels[MAX_CHANNELS]
Definition at line 54 of file snd_dma.c.
Referenced by S_Base_RawSamples(), S_Base_Respatialize(), S_Base_StartSound(), S_Base_Update(), S_ByteSwapRawSamples(), S_ChannelSetup(), S_PaintChannels(), and S_ScanChannelStarts().
s_doppler
cvar_t* s_doppler
Definition at line 32 of file snd_main.c.
Referenced by S_Base_AddLoopingSound(), and S_Init().
s_musicVolume
cvar_t* s_musicVolume
Definition at line 31 of file snd_main.c.
Referenced by S_Init(), and S_UpdateBackgroundTrack().
s_muted
cvar_t* s_muted
Definition at line 30 of file snd_main.c.
Referenced by S_Base_RawSamples(), S_Init(), S_PaintChannels(), and S_Update().
s_paintedtime
int s_paintedtime
Definition at line 68 of file snd_dma.c.
Referenced by S_Base_Init(), S_Base_StartSound(), S_Base_Update(), S_GetSoundtime(), S_PaintChannels(), S_ScanChannelStarts(), S_TransferPaintBuffer(), and S_TransferStereo16().
s_rawend
int s_rawend[MAX_RAW_STREAMS]
Definition at line 87 of file snd_dma.c.
Referenced by CIN_PlayCinematic(), RoQInterrupt(), S_Base_ClearSoundBuffer(), S_Base_RawSamples(), S_Base_StopBackgroundTrack(), S_PaintChannels(), and S_UpdateBackgroundTrack().
s_rawsamples
portable_samplepair_t s_rawsamples[MAX_RAW_STREAMS][MAX_RAW_SAMPLES]
Definition at line 88 of file snd_dma.c.
Referenced by S_Base_RawSamples(), and S_PaintChannels().
s_testsound
cvar_t* s_testsound
Definition at line 79 of file snd_dma.c.
Referenced by S_Base_Init(), and S_TransferPaintBuffer().
s_volume
cvar_t* s_volume
Definition at line 29 of file snd_main.c.
Referenced by S_Base_RawSamples(), S_Init(), and S_PaintChannels().
sfxScratchBuffer
short* sfxScratchBuffer
Definition at line 50 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), S_PaintChannelFromWavelet(), SND_setup(), and SND_shutdown().
sfxScratchIndex
int sfxScratchIndex
Definition at line 52 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), and S_PaintChannelFromWavelet().
sfxScratchPointer
sfx_t* sfxScratchPointer
Definition at line 51 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), S_PaintChannelFromWavelet(), and SND_setup().