ZEQ2-Lite: Engine/libspeex/quant_lsp.h File Reference
quant_lsp.h File Reference
LSP vector quantization.
#include <speex/speex_bits.h>
#include "arch.h"
Macros
#define MAX_LSP_SIZE 20
#define NB_CDBK_SIZE 64
#define NB_CDBK_SIZE_HIGH1 64
#define NB_CDBK_SIZE_HIGH2 64
#define NB_CDBK_SIZE_LOW1 64
#define NB_CDBK_SIZE_LOW2 64
Functions
void lsp_quant_high (spx_lsp_t *lsp, spx_lsp_t *qlsp, int order, SpeexBits *bits)
void lsp_quant_lbr (spx_lsp_t *lsp, spx_lsp_t *qlsp, int order, SpeexBits *bits)
void lsp_quant_nb (spx_lsp_t *lsp, spx_lsp_t *qlsp, int order, SpeexBits *bits)
void lsp_unquant_high (spx_lsp_t *lsp, int order, SpeexBits *bits)
void lsp_unquant_lbr (spx_lsp_t *lsp, int order, SpeexBits *bits)
void lsp_unquant_nb (spx_lsp_t *lsp, int order, SpeexBits *bits)
Variables
const signed char cdbk_nb []
const signed char cdbk_nb_high1 []
const signed char cdbk_nb_high2 []
const signed char cdbk_nb_low1 []
const signed char cdbk_nb_low2 []
Detailed Description
LSP vector quantization.
Definition in file quant_lsp.h.
Macro Definition Documentation
MAX_LSP_SIZE
#define MAX_LSP_SIZE 20
Definition at line 41 of file quant_lsp.h.
NB_CDBK_SIZE
#define NB_CDBK_SIZE 64
Definition at line 43 of file quant_lsp.h.
NB_CDBK_SIZE_HIGH1
#define NB_CDBK_SIZE_HIGH1 64
Definition at line 46 of file quant_lsp.h.
NB_CDBK_SIZE_HIGH2
#define NB_CDBK_SIZE_HIGH2 64
Definition at line 47 of file quant_lsp.h.
NB_CDBK_SIZE_LOW1
#define NB_CDBK_SIZE_LOW1 64
Definition at line 44 of file quant_lsp.h.
NB_CDBK_SIZE_LOW2
#define NB_CDBK_SIZE_LOW2 64
Definition at line 45 of file quant_lsp.h.
Function Documentation
lsp_quant_high()
void lsp_quant_high (spx_lsp_t * lsp, spx_lsp_t * qlsp, int order, SpeexBits * bits)
Definition at line 319 of file quant_lsp.c.
 {
    int i;
    int id;
    spx_word16_t quant_weight[10];
    for (i=0;i<order;i++)
       qlsp[i]=lsp[i];
    compute_quant_weights(qlsp, quant_weight, order);
    /*   quant_weight[0] = 10/(qlsp[1]-qlsp[0]);
    quant_weight[order-1] = 10/(qlsp[order-1]-qlsp[order-2]);
    for (i=1;i<order-1;i++)
    {
       tmp1 = 10/(qlsp[i]-qlsp[i-1]);
       tmp2 = 10/(qlsp[i+1]-qlsp[i]);
       quant_weight[i] = tmp1 > tmp2 ? tmp1 : tmp2;
       }*/
    for (i=0;i<order;i++)
       qlsp[i]=SUB16(qlsp[i],LSP_LINEAR_HIGH(i));
 #ifndef FIXED_POINT
    for (i=0;i<order;i++)
       qlsp[i] = qlsp[i]*LSP_SCALE;
 #endif
    id = lsp_quant(qlsp, high_lsp_cdbk, 64, order);
    speex_bits_pack(bits, id, 6);
    for (i=0;i<order;i++)
       qlsp[i]*=2;
    id = lsp_weight_quant(qlsp, quant_weight, high_lsp_cdbk2, 64, order);
    speex_bits_pack(bits, id, 6);
 #ifdef FIXED_POINT
    for (i=0;i<order;i++)
       qlsp[i] = PSHR16(qlsp[i],1);
 #else
    for (i=0;i<order;i++)
       qlsp[i] = qlsp[i]*0.0019531;
 #endif
    for (i=0;i<order;i++)
       qlsp[i]=lsp[i]-qlsp[i];
 }
References bits(), compute_quant_weights(), high_lsp_cdbk, high_lsp_cdbk2, LSP_LINEAR_HIGH, lsp_quant(), LSP_SCALE, lsp_weight_quant(), PSHR16, speex_bits_pack(), and SUB16.
lsp_quant_lbr()
void lsp_quant_lbr (spx_lsp_t * lsp, spx_lsp_t * qlsp, int order, SpeexBits * bits)
Definition at line 242 of file quant_lsp.c.
 {
    int i;
    int id;
    spx_word16_t quant_weight[10];
    for (i=0;i<order;i++)
       qlsp[i]=lsp[i];
    compute_quant_weights(qlsp, quant_weight, order);
    for (i=0;i<order;i++)
       qlsp[i]=SUB16(qlsp[i],LSP_LINEAR(i));
 #ifndef FIXED_POINT
    for (i=0;i<order;i++)
       qlsp[i]=qlsp[i]*LSP_SCALE;
 #endif
    id = lsp_quant(qlsp, cdbk_nb, NB_CDBK_SIZE, order);
    speex_bits_pack(bits, id, 6);
    for (i=0;i<order;i++)
       qlsp[i]*=2;
    id = lsp_weight_quant(qlsp, quant_weight, cdbk_nb_low1, NB_CDBK_SIZE_LOW1, 5);
    speex_bits_pack(bits, id, 6);
    id = lsp_weight_quant(qlsp+5, quant_weight+5, cdbk_nb_high1, NB_CDBK_SIZE_HIGH1, 5);
    speex_bits_pack(bits, id, 6);
 #ifdef FIXED_POINT
    for (i=0;i<order;i++)
       qlsp[i] = PSHR16(qlsp[i],1);
 #else
    for (i=0;i<order;i++)
       qlsp[i] = qlsp[i]*0.0019531;
 #endif
    for (i=0;i<order;i++)
       qlsp[i]=lsp[i]-qlsp[i];
 }
References bits(), cdbk_nb, cdbk_nb_high1, cdbk_nb_low1, compute_quant_weights(), LSP_LINEAR, lsp_quant(), LSP_SCALE, lsp_weight_quant(), NB_CDBK_SIZE, NB_CDBK_SIZE_HIGH1, NB_CDBK_SIZE_LOW1, PSHR16, speex_bits_pack(), and SUB16.
lsp_quant_nb()
void lsp_quant_nb (spx_lsp_t * lsp, spx_lsp_t * qlsp, int order, SpeexBits * bits)
Definition at line 159 of file quant_lsp.c.
 {
    int i;
    int id;
    spx_word16_t quant_weight[10];
    for (i=0;i<order;i++)
       qlsp[i]=lsp[i];
    compute_quant_weights(qlsp, quant_weight, order);
    for (i=0;i<order;i++)
       qlsp[i]=SUB16(qlsp[i],LSP_LINEAR(i));
 #ifndef FIXED_POINT
    for (i=0;i<order;i++)
       qlsp[i] = LSP_SCALE*qlsp[i];
 #endif
    id = lsp_quant(qlsp, cdbk_nb, NB_CDBK_SIZE, order);
    speex_bits_pack(bits, id, 6);
    for (i=0;i<order;i++)
       qlsp[i]*=2;
    id = lsp_weight_quant(qlsp, quant_weight, cdbk_nb_low1, NB_CDBK_SIZE_LOW1, 5);
    speex_bits_pack(bits, id, 6);
    for (i=0;i<5;i++)
       qlsp[i]*=2;
    id = lsp_weight_quant(qlsp, quant_weight, cdbk_nb_low2, NB_CDBK_SIZE_LOW2, 5);
    speex_bits_pack(bits, id, 6);
    id = lsp_weight_quant(qlsp+5, quant_weight+5, cdbk_nb_high1, NB_CDBK_SIZE_HIGH1, 5);
    speex_bits_pack(bits, id, 6);
    for (i=5;i<10;i++)
       qlsp[i]*=2;
    id = lsp_weight_quant(qlsp+5, quant_weight+5, cdbk_nb_high2, NB_CDBK_SIZE_HIGH2, 5);
    speex_bits_pack(bits, id, 6);
 #ifdef FIXED_POINT
    for (i=0;i<order;i++)
       qlsp[i]=PSHR16(qlsp[i],2);
 #else
    for (i=0;i<order;i++)
       qlsp[i]=qlsp[i] * .00097656;
 #endif
    for (i=0;i<order;i++)
       qlsp[i]=lsp[i]-qlsp[i];
 }
References bits(), cdbk_nb, cdbk_nb_high1, cdbk_nb_high2, cdbk_nb_low1, cdbk_nb_low2, compute_quant_weights(), LSP_LINEAR, lsp_quant(), LSP_SCALE, lsp_weight_quant(), NB_CDBK_SIZE, NB_CDBK_SIZE_HIGH1, NB_CDBK_SIZE_HIGH2, NB_CDBK_SIZE_LOW1, NB_CDBK_SIZE_LOW2, PSHR16, speex_bits_pack(), and SUB16.
lsp_unquant_high()
void lsp_unquant_high (spx_lsp_t * lsp, int order, SpeexBits * bits)
Definition at line 366 of file quant_lsp.c.
 {
    int i, id;
    for (i=0;i<order;i++)
       lsp[i]=LSP_LINEAR_HIGH(i);
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<order;i++)
       lsp[i] += LSP_DIV_256(high_lsp_cdbk[id*order+i]);
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<order;i++)
       lsp[i] += LSP_DIV_512(high_lsp_cdbk2[id*order+i]);
 }
References bits(), high_lsp_cdbk, high_lsp_cdbk2, LSP_DIV_256, LSP_DIV_512, LSP_LINEAR_HIGH, and speex_bits_unpack_unsigned().
lsp_unquant_lbr()
void lsp_unquant_lbr (spx_lsp_t * lsp, int order, SpeexBits * bits)
Definition at line 283 of file quant_lsp.c.
 {
    int i, id;
    for (i=0;i<order;i++)
       lsp[i]=LSP_LINEAR(i);
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<10;i++)
       lsp[i] += LSP_DIV_256(cdbk_nb[id*10+i]);
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<5;i++)
       lsp[i] += LSP_DIV_512(cdbk_nb_low1[id*5+i]);
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<5;i++)
       lsp[i+5] += LSP_DIV_512(cdbk_nb_high1[id*5+i]);
 }
References bits(), cdbk_nb, cdbk_nb_high1, cdbk_nb_low1, LSP_DIV_256, LSP_DIV_512, LSP_LINEAR, and speex_bits_unpack_unsigned().
lsp_unquant_nb()
void lsp_unquant_nb (spx_lsp_t * lsp, int order, SpeexBits * bits)
Definition at line 213 of file quant_lsp.c.
 {
    int i, id;
    for (i=0;i<order;i++)
       lsp[i]=LSP_LINEAR(i);
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<10;i++)
       lsp[i] = ADD32(lsp[i], LSP_DIV_256(cdbk_nb[id*10+i]));
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<5;i++)
       lsp[i] = ADD16(lsp[i], LSP_DIV_512(cdbk_nb_low1[id*5+i]));
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<5;i++)
       lsp[i] = ADD32(lsp[i], LSP_DIV_1024(cdbk_nb_low2[id*5+i]));
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<5;i++)
       lsp[i+5] = ADD32(lsp[i+5], LSP_DIV_512(cdbk_nb_high1[id*5+i]));
    id=speex_bits_unpack_unsigned(bits, 6);
    for (i=0;i<5;i++)
       lsp[i+5] = ADD32(lsp[i+5], LSP_DIV_1024(cdbk_nb_high2[id*5+i]));
 }
References ADD16, ADD32, bits(), cdbk_nb, cdbk_nb_high1, cdbk_nb_high2, cdbk_nb_low1, cdbk_nb_low2, LSP_DIV_1024, LSP_DIV_256, LSP_DIV_512, LSP_LINEAR, and speex_bits_unpack_unsigned().
Variable Documentation
cdbk_nb
const signed char cdbk_nb[]
Definition at line 32 of file lsp_tables_nb.c.
Referenced by lsp_quant_lbr(), lsp_quant_nb(), lsp_unquant_lbr(), and lsp_unquant_nb().
cdbk_nb_high1
const signed char cdbk_nb_high1[]
Definition at line 230 of file lsp_tables_nb.c.
Referenced by lsp_quant_lbr(), lsp_quant_nb(), lsp_unquant_lbr(), and lsp_unquant_nb().
cdbk_nb_high2
const signed char cdbk_nb_high2[]
Definition at line 296 of file lsp_tables_nb.c.
Referenced by lsp_quant_nb(), and lsp_unquant_nb().
cdbk_nb_low1
const signed char cdbk_nb_low1[]
Definition at line 98 of file lsp_tables_nb.c.
Referenced by lsp_quant_lbr(), lsp_quant_nb(), lsp_unquant_lbr(), and lsp_unquant_nb().
cdbk_nb_low2
const signed char cdbk_nb_low2[]
Definition at line 164 of file lsp_tables_nb.c.
Referenced by lsp_quant_nb(), and lsp_unquant_nb().