ZEQ2-Lite: Source/Engine/renderer/tr_bloom.c File Reference
tr_bloom.c File Reference
#include "tr_local.h"
Functions
static void R_Bloom_BackupScreen (void)
static void R_Bloom_DrawEffect (void)
static void R_Bloom_InitTextures (void)
static void ID_INLINE R_Bloom_Quad (int width, int height, float texX, float texY, float texWidth, float texHeight)
static void R_Bloom_RestoreScreen (void)
static void R_Bloom_WarsowEffect (void)
void R_BloomInit (void)
void R_BloomScreen (void)
void R_InitBloomTextures (void)
Variables
struct {
struct {
int height
float readH
float readW
image_t * texture
int width
} effect
struct {
int height
float readH
float readW
image_t * texture
int width
} screen
qboolean started
struct {
int height
int width
} work
} bloom
static float Diamond4x [4][4]
static float Diamond6x [6][6]
static float Diamond8x [8][8]
static cvar_t * r_bloom
static cvar_t * r_bloom_alpha
static cvar_t * r_bloom_darken
static cvar_t * r_bloom_debug
static cvar_t * r_bloom_diamond_size
static cvar_t * r_bloom_intensity
static cvar_t * r_bloom_sample_size
Function Documentation
R_Bloom_BackupScreen()
static void R_Bloom_BackupScreen (void) static
Definition at line 289 of file tr_bloom.c.
{
     GL_Bind( bloom.screen.texture );
     qglCopyTexSubImage2D( GL_TEXTURE_2D, 0, 0, 0, 0, 0, glConfig.vidWidth, glConfig.vidHeight );
 }
References bloom, GL_Bind(), glConfig, qglCopyTexSubImage2D, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by R_BloomScreen().
R_Bloom_DrawEffect()
static void R_Bloom_DrawEffect (void) static
Definition at line 187 of file tr_bloom.c.
 {
     GL_Bind( bloom.effect.texture );
     if( !r_bloom_debug->integer )
         GL_State( GLS_DEPTHTEST_DISABLE | GLS_SRCBLEND_ONE | GLS_DSTBLEND_ONE );
     else
         GL_State( GLS_DEPTHTEST_DISABLE );
     qglColor4f( r_bloom_alpha->value, r_bloom_alpha->value, r_bloom_alpha->value, 1.0f );
     R_Bloom_Quad( glConfig.vidWidth, glConfig.vidHeight, 0, 0, bloom.effect.readW, bloom.effect.readW );
 }
References bloom, GL_Bind(), GL_State(), glConfig, GLS_DEPTHTEST_DISABLE, GLS_DSTBLEND_ONE, GLS_SRCBLEND_ONE, qglColor4f, r_bloom_alpha, r_bloom_debug, R_Bloom_Quad(), glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by R_BloomScreen().
R_Bloom_InitTextures()
static void R_Bloom_InitTextures (void) static
Definition at line 122 of file tr_bloom.c.
 {
     byte    *data;
     // find closer power of 2 to screen size
     for (bloom.screen.width = 1;bloom.screen.width< glConfig.vidWidth;bloom.screen.width *= 2);
     for (bloom.screen.height = 1;bloom.screen.height < glConfig.vidHeight;bloom.screen.height *= 2);
     bloom.screen.readW = glConfig.vidWidth / (float)bloom.screen.width;
     bloom.screen.readH = glConfig.vidHeight / (float)bloom.screen.height;
     // find closer power of 2 to effect size
     bloom.work.width = r_bloom_sample_size->integer;
     bloom.work.height = bloom.work.width * ( glConfig.vidWidth / glConfig.vidHeight );
     for (bloom.effect.width = 1;bloom.effect.width < bloom.work.width;bloom.effect.width *= 2);
     for (bloom.effect.height = 1;bloom.effect.height < bloom.work.height;bloom.effect.height *= 2);
     bloom.effect.readW = bloom.work.width / (float)bloom.effect.width;
     bloom.effect.readH = bloom.work.height / (float)bloom.effect.height;
     // disable blooms if we can't handle a texture of that size
     if( bloom.screen.width > glConfig.maxTextureSize ||
         bloom.screen.height > glConfig.maxTextureSize ||
         bloom.effect.width > glConfig.maxTextureSize ||
         bloom.effect.height > glConfig.maxTextureSize ||
         bloom.work.width > glConfig.vidWidth ||
         bloom.work.height > glConfig.vidHeight
     ) {
         ri.Cvar_Set( "r_bloom", "0" );
         Com_Printf( S_COLOR_YELLOW"WARNING: 'R_InitBloomTextures' too high resolution for light bloom, effect disabled\n" );
         return;
     }
     data = ri.Hunk_AllocateTempMemory( bloom.screen.width * bloom.screen.height * 4 );
     Com_Memset( data, 0, bloom.screen.width * bloom.screen.height * 4 );
     bloom.screen.texture = R_CreateImage( "***bloom screen texture***", data, bloom.screen.width, bloom.screen.height, qfalse, qfalse, GL_CLAMP_TO_EDGE);
     ri.Hunk_FreeTempMemory( data );
     data = ri.Hunk_AllocateTempMemory( bloom.effect.width * bloom.effect.height * 4 );
     Com_Memset( data, 0, bloom.effect.width * bloom.effect.height * 4 );
     bloom.effect.texture = R_CreateImage( "***bloom effect texture***", data, bloom.effect.width, bloom.effect.height, qfalse, qfalse, GL_CLAMP_TO_EDGE);
     ri.Hunk_FreeTempMemory( data );
     bloom.started = qtrue;
 }
References bloom, Com_Memset, Com_Printf(), refimport_t::Cvar_Set, GL_CLAMP_TO_EDGE, glConfig, refimport_t::Hunk_AllocateTempMemory, refimport_t::Hunk_FreeTempMemory, glconfig_t::maxTextureSize, qfalse, qtrue, r_bloom_sample_size, R_CreateImage(), ri, S_COLOR_YELLOW, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by R_BloomScreen(), and R_InitBloomTextures().
R_Bloom_Quad()
static void ID_INLINE R_Bloom_Quad (int width, int height, float texX, float texY, float texWidth, float texHeight) static
Definition at line 90 of file tr_bloom.c.
{
     int x = 0;
     int y = 0;
     x = 0;
     y += glConfig.vidHeight - height;
     width += x;
     height += y;
     texWidth += texX;
     texHeight += texY;
     qglBegin( GL_QUADS );
     qglTexCoord2f(  texX,                       texHeight   );
     qglVertex2f(    x,                          y   );
     qglTexCoord2f(  texX,                       texY    );
     qglVertex2f(    x,                          height  );
     qglTexCoord2f(  texWidth,                   texY    );
     qglVertex2f(    width,                      height  );
     qglTexCoord2f(  texWidth,                   texHeight   );
     qglVertex2f(    width,                      y   );
     qglEnd ();
 }
References glConfig, height, qglBegin, qglEnd, qglTexCoord2f, qglVertex2f, and glconfig_t::vidHeight.
Referenced by R_Bloom_DrawEffect(), R_Bloom_RestoreScreen(), and R_Bloom_WarsowEffect().
R_Bloom_RestoreScreen()
static void R_Bloom_RestoreScreen (void) static
Definition at line 299 of file tr_bloom.c.
{
     GL_State( GLS_DEPTHTEST_DISABLE | GLS_SRCBLEND_ONE | GLS_DSTBLEND_ZERO );
     GL_Bind( bloom.screen.texture );
     qglColor4f( 1, 1, 1, 1 );
     R_Bloom_Quad( bloom.work.width, bloom.work.height, 0, 0,
         bloom.work.width / (float)bloom.screen.width,
         bloom.work.height / (float)bloom.screen.height );
 }
References bloom, GL_Bind(), GL_State(), GLS_DEPTHTEST_DISABLE, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_ONE, qglColor4f, and R_Bloom_Quad().
Referenced by R_BloomScreen().
R_Bloom_WarsowEffect()
static void R_Bloom_WarsowEffect (void) static
Definition at line 204 of file tr_bloom.c.
 {
     int     i, j, k;
     float   intensity, scale, *diamond;
     qglColor4f( 1.0f, 1.0f, 1.0f, 1.0f );
     //Take the backup texture and downscale it
     GL_Bind( bloom.screen.texture );
     GL_State( GLS_DEPTHTEST_DISABLE | GLS_SRCBLEND_ONE | GLS_DSTBLEND_ZERO );
     R_Bloom_Quad( bloom.work.width, bloom.work.height, 0, 0, bloom.screen.readW, bloom.screen.readH );
     //Copy downscaled framebuffer into a texture
     GL_Bind( bloom.effect.texture );
     qglCopyTexSubImage2D( GL_TEXTURE_2D, 0, 0, 0, 0, 0, bloom.work.width, bloom.work.height );
     // darkening passes with repeated filter
     if( r_bloom_darken->integer ) {
         int i;
         GL_State( GLS_DEPTHTEST_DISABLE | GLS_SRCBLEND_DST_COLOR | GLS_DSTBLEND_ZERO );
         for( i = 0; i < r_bloom_darken->integer; i++ ) {
             R_Bloom_Quad( bloom.work.width, bloom.work.height,
                 0, 0,
                 bloom.effect.readW, bloom.effect.readH );
         }
         qglCopyTexSubImage2D( GL_TEXTURE_2D, 0, 0, 0, 0, 0, bloom.work.width, bloom.work.height );
     }
     /* Copy the result to the effect texture */
     GL_Bind( bloom.effect.texture );
     qglCopyTexSubImage2D( GL_TEXTURE_2D, 0, 0, 0, 0, 0, bloom.work.width, bloom.work.height );
     // bluring passes, warsow uses a repeated semi blend on a selectable diamond grid
     qglColor4f( 1.0f, 1.0f, 1.0f, 1.0f );
     GL_State( GLS_DEPTHTEST_DISABLE | GLS_SRCBLEND_ONE | GLS_DSTBLEND_ONE_MINUS_SRC_COLOR );
     if( r_bloom_diamond_size->integer > 7 || r_bloom_diamond_size->integer <= 3 ) {
         if( r_bloom_diamond_size->integer != 8 )
             ri.Cvar_Set( "r_bloom_diamond_size", "8" );
     } else if( r_bloom_diamond_size->integer > 5 ) {
         if( r_bloom_diamond_size->integer != 6 )
             ri.Cvar_Set( "r_bloom_diamond_size", "6" );
     } else if( r_bloom_diamond_size->integer > 3 ) {
         if( r_bloom_diamond_size->integer != 4 )
             ri.Cvar_Set( "r_bloom_diamond_size", "4" );
     }
     switch( r_bloom_diamond_size->integer ) {
         case 4:
             k = 2;
             diamond = &Diamond4x[0][0];
             scale = r_bloom_intensity->value * 0.8f;
             break;
         case 6:
             k = 3;
             diamond = &Diamond6x[0][0];
             scale = r_bloom_intensity->value * 0.5f;
             break;
         default:
 //      case 8:
             k = 4;
             diamond = &Diamond8x[0][0];
             scale = r_bloom_intensity->value * 0.3f;
             break;
     }
     for( i = 0; i < r_bloom_diamond_size->integer; i++ ) {
         for( j = 0; j < r_bloom_diamond_size->integer; j++, diamond++ ) {
             float x, y;
             intensity =  *diamond * scale;
             if( intensity < 0.01f )
                 continue;
             qglColor4f( intensity, intensity, intensity, 1.0 );
             x = (i - k) * ( 2 / 640.0f ) * bloom.effect.readW;
             y = (j - k) * ( 2 / 480.0f ) * bloom.effect.readH;
             R_Bloom_Quad( bloom.work.width, bloom.work.height, x, y, bloom.effect.readW, bloom.effect.readH );
         }
     }
     qglCopyTexSubImage2D( GL_TEXTURE_2D, 0, 0, 0, 0, 0, bloom.work.width, bloom.work.height );
 }
References bloom, refimport_t::Cvar_Set, Diamond4x, Diamond6x, Diamond8x, GL_Bind(), GL_State(), GLS_DEPTHTEST_DISABLE, GLS_DSTBLEND_ONE_MINUS_SRC_COLOR, GLS_DSTBLEND_ZERO, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_ONE, qglColor4f, qglCopyTexSubImage2D, r_bloom_darken, r_bloom_diamond_size, r_bloom_intensity, R_Bloom_Quad(), and ri.
Referenced by R_BloomScreen().
R_BloomInit()
void R_BloomInit (void)
Definition at line 439 of file tr_bloom.c.
{
     memset( &bloom, 0, sizeof( bloom ));
     r_bloom = ri.Cvar_Get( "r_bloom", "1", CVAR_ARCHIVE );
     r_bloom_alpha = ri.Cvar_Get( "r_bloom_alpha", "0.5", CVAR_ARCHIVE );
     r_bloom_diamond_size = ri.Cvar_Get( "r_bloom_diamond_size", "8", CVAR_ARCHIVE );
     r_bloom_intensity = ri.Cvar_Get( "r_bloom_intensity", "0.5", CVAR_ARCHIVE );
     r_bloom_darken = ri.Cvar_Get( "r_bloom_darken", "32", CVAR_ARCHIVE );
     r_bloom_sample_size = ri.Cvar_Get( "r_bloom_sample_size", "256", CVAR_ARCHIVE|CVAR_LATCH );
 //  r_bloom_fast_sample = ri.Cvar_Get( "r_bloom_fast_sample", "0", CVAR_ARCHIVE|CVAR_LATCH );
     r_bloom_debug = ri.Cvar_Get( "r_bloom_debug", "0", 0 );
 }
References bloom, CVAR_ARCHIVE, refimport_t::Cvar_Get, CVAR_LATCH, r_bloom, r_bloom_alpha, r_bloom_darken, r_bloom_debug, r_bloom_diamond_size, r_bloom_intensity, r_bloom_sample_size, and ri.
R_BloomScreen()
void R_BloomScreen (void)
Definition at line 394 of file tr_bloom.c.
 {
     if( !r_bloom->integer )
         return;
     if ( backEnd.doneBloom )
         return;
     if ( !backEnd.doneSurfaces )
         return;
     backEnd.doneBloom = qtrue;
     if( !bloom.started ) {
         R_Bloom_InitTextures();
         if( !bloom.started )
             return;
     }
     if ( !backEnd.projection2D )
         RB_SetGL2D();
 #if 0
     // set up full screen workspace
     GL_TexEnv( GL_MODULATE );
     qglScissor( 0, 0, glConfig.vidWidth, glConfig.vidHeight );
     qglViewport( 0, 0, glConfig.vidWidth, glConfig.vidHeight );
     qglMatrixMode( GL_PROJECTION );
     qglLoadIdentity ();
     qglOrtho( 0, glConfig.vidWidth, glConfig.vidHeight, 0, 0, 1 );
     qglMatrixMode( GL_MODELVIEW );
     qglLoadIdentity ();
     GL_Cull( CT_TWO_SIDED );
 #endif
     qglColor4f( 1, 1, 1, 1 );
     //Backup the old screen in a texture
     R_Bloom_BackupScreen();
     // create the bloom texture using one of a few methods
     R_Bloom_WarsowEffect ();
 //  R_Bloom_CreateEffect();
     // restore the screen-backup to the screen
     R_Bloom_RestoreScreen();
     // Do the final pass using the bloom texture for the final effect
     R_Bloom_DrawEffect ();
 }
References backEnd, bloom, CT_TWO_SIDED, backEndState_t::doneBloom, backEndState_t::doneSurfaces, GL_Cull(), GL_TexEnv(), glConfig, backEndState_t::projection2D, qglColor4f, qglLoadIdentity, qglMatrixMode, qglOrtho, qglScissor, qglViewport, qtrue, r_bloom, R_Bloom_BackupScreen(), R_Bloom_DrawEffect(), R_Bloom_InitTextures(), R_Bloom_RestoreScreen(), R_Bloom_WarsowEffect(), RB_SetGL2D(), glconfig_t::vidHeight, and glconfig_t::vidWidth.
R_InitBloomTextures()
void R_InitBloomTextures (void)
Definition at line 174 of file tr_bloom.c.
 {
     if( !r_bloom->integer )
         return;
     memset( &bloom, 0, sizeof( bloom ));
     R_Bloom_InitTextures ();
 }
References bloom, r_bloom, and R_Bloom_InitTextures().
Variable Documentation
bloom
struct { ... } bloom
Referenced by R_Bloom_BackupScreen(), R_Bloom_DrawEffect(), R_Bloom_InitTextures(), R_Bloom_RestoreScreen(), R_Bloom_WarsowEffect(), R_BloomInit(), R_BloomScreen(), and R_InitBloomTextures().
Diamond4x
float Diamond4x[4][4] static
Initial value:
=
{
    { 0.3f, 0.4f, 0.4f, 0.3f, },
    { 0.4f, 0.9f, 0.9f, 0.4f, },
    { 0.4f, 0.9f, 0.9f, 0.4f, },
    { 0.3f, 0.4f, 0.4f, 0.3f  }
}
Definition at line 64 of file tr_bloom.c.
Referenced by R_Bloom_WarsowEffect().
Diamond6x
float Diamond6x[6][6] static
Initial value:
=
{
    { 0.0f, 0.0f, 0.1f, 0.1f, 0.0f, 0.0f, },
    { 0.0f, 0.3f, 0.5f, 0.5f, 0.3f, 0.0f, },
    { 0.1f, 0.5f, 0.9f, 0.9f, 0.5f, 0.1f, },
    { 0.1f, 0.5f, 0.9f, 0.9f, 0.5f, 0.1f, },
    { 0.0f, 0.3f, 0.5f, 0.5f, 0.3f, 0.0f, },
    { 0.0f, 0.0f, 0.1f, 0.1f, 0.0f, 0.0f  }
}
Definition at line 54 of file tr_bloom.c.
Referenced by R_Bloom_WarsowEffect().
Diamond8x
float Diamond8x[8][8] static
Initial value:
=
{
    { 0.0f, 0.0f, 0.0f, 0.1f, 0.1f, 0.0f, 0.0f, 0.0f, },
    { 0.0f, 0.0f, 0.2f, 0.3f, 0.3f, 0.2f, 0.0f, 0.0f, },
    { 0.0f, 0.2f, 0.4f, 0.6f, 0.6f, 0.4f, 0.2f, 0.0f, },
    { 0.1f, 0.3f, 0.6f, 0.9f, 0.9f, 0.6f, 0.3f, 0.1f, },
    { 0.1f, 0.3f, 0.6f, 0.9f, 0.9f, 0.6f, 0.3f, 0.1f, },
    { 0.0f, 0.2f, 0.4f, 0.6f, 0.6f, 0.4f, 0.2f, 0.0f, },
    { 0.0f, 0.0f, 0.2f, 0.3f, 0.3f, 0.2f, 0.0f, 0.0f, },
    { 0.0f, 0.0f, 0.0f, 0.1f, 0.1f, 0.0f, 0.0f, 0.0f  }
}
Definition at line 42 of file tr_bloom.c.
Referenced by R_Bloom_WarsowEffect().
effect
struct { ... } effect
height
int height
Definition at line 75 of file tr_bloom.c.
r_bloom
cvar_t* r_bloom static
Definition at line 25 of file tr_bloom.c.
Referenced by R_BloomInit(), R_BloomScreen(), and R_InitBloomTextures().
r_bloom_alpha
cvar_t* r_bloom_alpha static
Definition at line 28 of file tr_bloom.c.
Referenced by R_Bloom_DrawEffect(), and R_BloomInit().
r_bloom_darken
cvar_t* r_bloom_darken static
Definition at line 29 of file tr_bloom.c.
Referenced by R_Bloom_WarsowEffect(), and R_BloomInit().
r_bloom_debug
cvar_t* r_bloom_debug static
Definition at line 32 of file tr_bloom.c.
Referenced by R_Bloom_DrawEffect(), and R_BloomInit().
r_bloom_diamond_size
cvar_t* r_bloom_diamond_size static
Definition at line 31 of file tr_bloom.c.
Referenced by R_Bloom_WarsowEffect(), and R_BloomInit().
r_bloom_intensity
cvar_t* r_bloom_intensity static
Definition at line 30 of file tr_bloom.c.
Referenced by R_Bloom_WarsowEffect(), and R_BloomInit().
r_bloom_sample_size
cvar_t* r_bloom_sample_size static
Definition at line 26 of file tr_bloom.c.
Referenced by R_Bloom_InitTextures(), and R_BloomInit().
readH
float readH
Definition at line 76 of file tr_bloom.c.
readW
float readW
Definition at line 76 of file tr_bloom.c.
screen
struct { ... } screen
started
qboolean started
Definition at line 86 of file tr_bloom.c.
texture
image_t* texture
Definition at line 74 of file tr_bloom.c.
width
int width
Definition at line 75 of file tr_bloom.c.
work
struct { ... } work