ZEQ2-Lite: Source/Engine/renderer/tr_public.h File Reference
tr_public.h File Reference
#include "tr_types.h"
Data Structures
struct refexport_t
struct refimport_t
Macros
#define REF_API_VERSION 8
Functions
refexport_t * GetRefAPI (int apiVersion, refimport_t *rimp)
Macro Definition Documentation
REF_API_VERSION
#define REF_API_VERSION 8
Definition at line 27 of file tr_public.h.
Function Documentation
GetRefAPI()
refexport_t* GetRefAPI (int apiVersion, refimport_t * rimp)
Definition at line 1351 of file tr_init.c.
{
 #endif
     static refexport_t  re;
     ri = *rimp;
     Com_Memset( &re, 0, sizeof( re ) );
     if ( apiVersion != REF_API_VERSION ) {
         ri.Printf(PRINT_ALL, "Mismatched REF_API_VERSION: expected %i, got %i\n",
             REF_API_VERSION, apiVersion );
         return NULL;
     }
     // the RE_ functions are Renderer Entry points
     re.Shutdown = RE_Shutdown;
     re.BeginRegistration = RE_BeginRegistration;
     re.RegisterModel = RE_RegisterModel;
     re.RegisterSkin = RE_RegisterSkin;
     re.RegisterShader = RE_RegisterShader;
     re.RegisterShaderNoMip = RE_RegisterShaderNoMip;
     re.LoadWorld = RE_LoadWorldMap;
     re.SetWorldVisData = RE_SetWorldVisData;
     re.EndRegistration = RE_EndRegistration;
     re.BeginFrame = RE_BeginFrame;
     re.EndFrame = RE_EndFrame;
     re.MarkFragments = R_MarkFragments;
     re.LerpTag = R_LerpTag;
     re.ModelBounds = R_ModelBounds;
     re.ClearScene = RE_ClearScene;
     re.AddRefEntityToScene = RE_AddRefEntityToScene;
     re.AddPolyToScene = RE_AddPolyToScene;
     re.LightForPoint = R_LightForPoint;
     re.AddFogToScene = RE_AddFogToScene;
     re.AddLightToScene = RE_AddLightToScene;
     re.AddAdditiveLightToScene = RE_AddAdditiveLightToScene;
     re.RenderScene = RE_RenderScene;
     re.SetColor = RE_SetColor;
     re.DrawStretchPic = RE_StretchPic;
     re.DrawStretchRaw = RE_StretchRaw;
     re.UploadCinematic = RE_UploadCinematic;
     re.RegisterFont = RE_RegisterFont;
     re.RemapShader = R_RemapShader;
     re.GetEntityToken = R_GetEntityToken;
     re.inPVS = R_inPVS;
     re.TakeVideoFrame = RE_TakeVideoFrame;
     return &re;
 }
References refexport_t::AddAdditiveLightToScene, refexport_t::AddFogToScene, refexport_t::AddLightToScene, refexport_t::AddPolyToScene, refexport_t::AddRefEntityToScene, refexport_t::BeginFrame, refexport_t::BeginRegistration, refexport_t::ClearScene, Com_Memset, refexport_t::DrawStretchPic, refexport_t::DrawStretchRaw, refexport_t::EndFrame, refexport_t::EndRegistration, refexport_t::GetEntityToken, refexport_t::inPVS, refexport_t::LerpTag, refexport_t::LightForPoint, refexport_t::LoadWorld, refexport_t::MarkFragments, refexport_t::ModelBounds, NULL, PRINT_ALL, R_GetEntityToken(), R_inPVS(), R_LerpTag(), R_LightForPoint(), R_MarkFragments(), R_ModelBounds(), R_RemapShader(), re, RE_AddAdditiveLightToScene(), RE_AddFogToScene(), RE_AddLightToScene(), RE_AddPolyToScene(), RE_AddRefEntityToScene(), RE_BeginFrame(), RE_BeginRegistration(), RE_ClearScene(), RE_EndFrame(), RE_EndRegistration(), RE_LoadWorldMap(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterShader(), RE_RegisterShaderNoMip(), RE_RegisterSkin(), RE_RenderScene(), RE_SetColor(), RE_SetWorldVisData(), RE_Shutdown(), RE_StretchPic(), RE_StretchRaw(), RE_TakeVideoFrame(), RE_UploadCinematic(), REF_API_VERSION, refexport_t::RegisterFont, refexport_t::RegisterModel, refexport_t::RegisterShader, refexport_t::RegisterShaderNoMip, refexport_t::RegisterSkin, refexport_t::RemapShader, refexport_t::RenderScene, ri, refexport_t::SetColor, refexport_t::SetWorldVisData, refexport_t::Shutdown, refexport_t::TakeVideoFrame, and refexport_t::UploadCinematic.
Referenced by CL_InitRef().