ZEQ2-Lite: Engine/tools/lcc/src/config.h File Reference
config.h File Reference
Data Structures
struct Env
struct Regnode
struct Xinterface
struct Xnode
struct Xsymbol
Macros
#define debug(x) (void)(dflag&&((x),0))
#define LBURG_MAX SHRT_MAX
Enumerations
enum { IREG =0, FREG =1 }
enum { RX =2 }
enum { VREG =(44<<4) }
Functions
int askregvar (Symbol, Symbol)
void blkcopy (int, int, int, int, int, int[])
void blockbeg (Env *)
void blockend (Env *)
void emit (Node)
unsigned emitbin (Node, int)
Node gen (Node)
int getregnum (Node)
int mayrecalc (Node)
int mkactual (int, int)
void mkauto (Symbol)
Symbol mkreg (char *, int, int, int)
Symbol mkwildcard (Symbol *)
int move (Node)
int notarget (Node)
void parseflags (int, char **)
int range (Node, int, int)
unsigned regloc (Symbol)
void rtarget (Node, int, Symbol)
void setreg (Node, Symbol)
void spill (unsigned, int, Node)
int widens (Node)
Variables
int argoffset
int bflag
int dalign
int dflag
int framesize
unsigned freemask []
int maxargoffset
int maxoffset
int offset
int salign
int swap
unsigned tmask []
unsigned usedmask []
unsigned vmask []
Macro Definition Documentation
debug
#define debug (x) (void)(dflag&&((x),0))
Definition at line 101 of file config.h.
LBURG_MAX
#define LBURG_MAX SHRT_MAX
Definition at line 86 of file config.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IREG
FREG
Definition at line 70 of file config.h.
 { IREG=0, FREG=1 };
anonymous enum
anonymous enum
Enumerator
RX
Definition at line 80 of file config.h.
 { RX=2 };
anonymous enum
anonymous enum
Enumerator
VREG
Definition at line 88 of file config.h.
 { VREG=(44<<4) };
Function Documentation
askregvar()
int askregvar (Symbol , Symbol)
Definition at line 572 of file gen.c.
{
     Symbol r;
     assert(p);
     if (p->sclass != REGISTER)
         return 0;
     else if (!isscalar(p->type)) {
         p->sclass = AUTO;
         return 0;
     }
     else if (p->temporary) {
         p->x.name = "?";
         return 1;
     }
     else if ((r = askreg(regs, vmask)) != NULL) {
         p->x.regnode = r->x.regnode;
         p->x.regnode->vbl = p;
         p->x.name = r->x.name;
         debug(dumpregs("(allocating %s to symbol %s)\n", p->x.name, p->name));
         return 1;
     }
     else {
         p->sclass = AUTO;
         return 0;
     }
 }
References askreg(), debug, dumpregs(), isscalar, NULL, and vmask.
blkcopy()
void blkcopy (int , int , int , int , int , int [])
Definition at line 129 of file gen.c.
{
     assert(size >= 0);
     if (size == 0)
         return;
     else if (size <= 2)
         blkunroll(size, dreg, doff, sreg, soff, size, tmp);
     else if (size == 3) {
         blkunroll(2, dreg, doff,   sreg, soff,   2, tmp);
         blkunroll(1, dreg, doff+2, sreg, soff+2, 1, tmp);
     }
     else if (size <= 16) {
         blkunroll(4, dreg, doff, sreg, soff, size&~3, tmp);
         blkcopy(dreg, doff+(size&~3),
                     sreg, soff+(size&~3), size&3, tmp);
     }
     else
         (*IR->x.blkloop)(dreg, doff, sreg, soff, size, tmp);
 }
References blkunroll(), and IR.
blockbeg()
void blockbeg (Env *)
Definition at line 104 of file gen.c.
                       {
     e->offset = offset;
     e->freemask[IREG] = freemask[IREG];
     e->freemask[FREG] = freemask[FREG];
 }
References freemask, Env::freemask, FREG, IREG, offset, and Env::offset.
blockend()
void blockend (Env *)
Definition at line 109 of file gen.c.
                       {
     if (offset > maxoffset)
         maxoffset = offset;
     offset = e->offset;
     freemask[IREG] = e->freemask[IREG];
     freemask[FREG] = e->freemask[FREG];
 }
References freemask, Env::freemask, FREG, IREG, maxoffset, offset, and Env::offset.
emit()
void emit (Node)
Definition at line 368 of file gen.c.
                   {
     for (; p; p = p->x.next) {
         assert(p->x.registered);
         if ((p->x.equatable && requate(p)) || moveself(p))
             ;
         else
             (*emitter)(p, p->x.inst);
         p->x.emitted = 1;
     }
 }
References emitter, moveself(), and requate().
emitbin()
unsigned emitbin (Node , int)
gen()
Node gen (Node)
Definition at line 479 of file gen.c.
                       {
     int i;
     struct node sentinel;
     Node dummy, p;
     head = forest;
     for (p = forest; p; p = p->link) {
         assert(p->count == 0);
         if (generic(p->op) == CALL)
             docall(p);
         else if (   generic(p->op) == ASGN
         && generic(p->kids[1]->op) == CALL)
             docall(p->kids[1]);
         else if (generic(p->op) == ARG)
             (*IR->x.doarg)(p);
         rewrite(p);
         p->x.listed = 1;
     }
     for (p = forest; p; p = p->link)
         prune(p, &dummy);
     relink(&sentinel, &sentinel);
     for (p = forest; p; p = p->link)
         linearize(p, &sentinel);
     forest = sentinel.x.next;
     assert(forest);
     sentinel.x.next->x.prev = NULL;
     sentinel.x.prev->x.next = NULL;
     for (p = forest; p; p = p->x.next)
         for (i = 0; i < NELEMS(p->x.kids) && p->x.kids[i]; i++) {
             assert(p->x.kids[i]->syms[RX]);
             if (p->x.kids[i]->syms[RX]->temporary) {
                 p->x.kids[i]->x.prevuse =
                     p->x.kids[i]->syms[RX]->x.lastuse;
                 p->x.kids[i]->syms[RX]->x.lastuse = p->x.kids[i];
             }
         }
     for (p = forest; p; p = p->x.next) {
         ralloc(p);
         if (p->x.listed && NeedsReg[opindex(p->op)]
         && (*IR->x.rmap)(opkind(p->op))) {
             assert(generic(p->op) == CALL || generic(p->op) == LOAD);
             putreg(p->syms[RX]);
         }
     }
     return forest;
 }
References ASGN, CALL, docall(), forest, head, IR, linearize(), LOAD, NeedsReg, NELEMS, Xnode::next, NULL, opindex, opkind, Xnode::prev, prune(), putreg(), ralloc(), relink, rewrite(), RX, and Node::x.
getregnum()
int getregnum (Node)
Definition at line 820 of file gen.c.
                       {
     assert(p && p->syms[RX] && p->syms[RX]->x.regnode);
     return p->syms[RX]->x.regnode->number;
 }
References RX.
mayrecalc()
int mayrecalc (Node)
Definition at line 219 of file gen.c.
                       {
     int op;
     assert(p && p->syms[RX]);
     if (p->syms[RX]->u.t.cse == NULL)
         return 0;
     op = generic(p->syms[RX]->u.t.cse->op);
     if (op == CNST || op == ADDRF || op == ADDRG || op == ADDRL) {
         p->x.mayrecalc = 1;
         return 1;
     } else
         return 0;
 }
References NULL, op, and RX.
mkactual()
int mkactual (int , int)
Definition at line 116 of file gen.c.
{
     int n = roundup(argoffset, align);
     argoffset = n + size;
     return n;
 }
References argoffset, and roundup.
mkauto()
void mkauto (Symbol)
Definition at line 98 of file gen.c.
                       {
     assert(p->sclass == AUTO);
     offset = roundup(offset + p->type->size, p->type->align);
     p->x.offset = -offset;
     p->x.name = stringd(-offset);
 }
References offset, roundup, and stringd().
mkreg()
Symbol mkreg (char * , int , int , int)
Definition at line 79 of file gen.c.
{
     Symbol p;
     NEW0(p, PERM);
     p->name = p->x.name = stringf(fmt, n);
     NEW0(p->x.regnode, PERM);
     p->x.regnode->number = n;
     p->x.regnode->mask = mask<<n;
     p->x.regnode->set = set;
     return p;
 }
References fmt, NEW0, PERM, and stringf().
mkwildcard()
Symbol mkwildcard (Symbol *)
Definition at line 90 of file gen.c.
{
     Symbol p;
     NEW0(p, PERM);
     p->name = p->x.name = "wildcard";
     p->x.wildcard = syms;
     return p;
 }
References NEW0, and PERM.
move()
int move (Node)
Definition at line 382 of file gen.c.
                  {
     p->x.copy = 1;
     return 1;
 }
Referenced by CG_BubbleTrail(), CG_SwingAngles(), G_MoverPush(), G_MoverTeam(), G_TryPushingEntity(), G_TryPushingProxMine(), InitMover(), Reached_Train(), and UI_SwingAngles().
notarget()
int notarget (Node)
Definition at line 525 of file gen.c.
                      {
     return p->syms[RX]->x.wildcard ? 0 : LBURG_MAX;
 }
References LBURG_MAX, and RX.
parseflags()
void parseflags (int , char **)
range()
int range (Node , int , int)
Definition at line 253 of file gen.c.
{
     Symbol s = p->syms[0];
     switch (specific(p->op)) {
     case ADDRF+P:
     case ADDRL+P: ck(s->x.offset >= lo && s->x.offset <= hi);
     case CNST+I:  ck(s->u.c.v.i  >= lo && s->u.c.v.i  <= hi);
     case CNST+U:  ck(s->u.c.v.u  >= lo && s->u.c.v.u  <= hi);
     case CNST+P:  ck(s->u.c.v.p  == 0  && lo <= 0 && hi >= 0);
     }
     return LBURG_MAX;
 }
References ck, I, LBURG_MAX, P, specific, and U.
regloc()
unsigned regloc (Symbol)
Definition at line 826 of file gen.c.
{
     assert(p && p->sclass == REGISTER && p->sclass == REGISTER && p->x.regnode);
     return p->x.regnode->set<<8 | p->x.regnode->number;
 }
rtarget()
void rtarget (Node , int , Symbol)
Definition at line 452 of file gen.c.
{
     Node q = p->kids[n];
     assert(q);
     assert(r);
     assert(r->sclass == REGISTER || !r->x.wildcard);
     assert(q->syms[RX]);
     if (r != q->syms[RX] && !q->syms[RX]->x.wildcard) {
         q = newnode(LOAD + opkind(q->op),
             q, NULL, q->syms[0]);
         if (r->u.t.cse == p->kids[n])
             r->u.t.cse = q;
         p->kids[n] = p->x.kids[n] = q;
         q->x.kids[0] = q->kids[0];
     }
     setreg(q, r);
     debug(fprint(stderr, "(targeting %x->x.kids[%d]=%x to %s)\n", p, n, p->kids[n], r->x.name));
 }
References debug, fprint(), LOAD, newnode(), NULL, opkind, RX, and setreg().
Referenced by prelabel().
setreg()
void setreg (Node , Symbol)
Definition at line 449 of file gen.c.
{
     p->syms[RX] = r;
 }
References RX.
Referenced by prelabel(), and rtarget().
spill()
void spill (unsigned , int , Node)
Definition at line 788 of file gen.c.
{
     int i;
     Node p;
     here->x.spills = 1;
     usedmask[n] |= mask;
     if (mask&~freemask[n]) {
         assert( /* It makes no sense for a node to clobber() its target. */
             here->x.registered == 0 || /* call isn't coming through clobber() */
             here->syms[RX] == NULL ||
             here->syms[RX]->x.regnode == NULL ||
             here->syms[RX]->x.regnode->set != n ||
             (here->syms[RX]->x.regnode->mask&mask) == 0
         );
         for (p = here; p; p = p->x.next)
             for (i = 0; i < NELEMS(p->x.kids) && p->x.kids[i]; i++) {
                 Symbol r = p->x.kids[i]->syms[RX];
                 assert(r);
                 if (p->x.kids[i]->x.registered && r->x.regnode->set == n
                 && r->x.regnode->mask&mask)
                     spillr(r, here);
             }
     }
 }
References freemask, NELEMS, NULL, RX, spillr(), and usedmask.
Referenced by getreg().
widens()
int widens (Node)
Variable Documentation
argoffset
int argoffset
Definition at line 45 of file gen.c.
Referenced by docall(), function(), gen02(), and mkactual().
bflag
int bflag
Definition at line 50 of file gen.c.
Referenced by parseflags().
dalign
int dalign
Definition at line 49 of file gen.c.
Referenced by blkunroll().
dflag
int dflag
Definition at line 42 of file config.h.
framesize
int framesize
Definition at line 44 of file gen.c.
Referenced by emitasm().
freemask
unsigned freemask[]
Definition at line 75 of file gen.c.
Referenced by askfixedreg(), blockbeg(), blockend(), dumpregs(), putreg(), and spill().
maxargoffset
int maxargoffset
Definition at line 41 of file config.h.
Referenced by function(), and gen02().
maxoffset
int maxoffset
Definition at line 46 of file config.h.
Referenced by function().
offset
int offset
Definition at line 40 of file gen.c.
Referenced by blockbeg(), blockend(), and mkauto().
salign
int salign
Definition at line 43 of file config.h.
swap
int swap
Definition at line 53 of file gen.c.
Referenced by defconst(), and Hunk_SwapBanks().
tmask
unsigned tmask[]
Definition at line 77 of file gen.c.
Referenced by ralloc(), and spillee().
usedmask
unsigned usedmask[]
Definition at line 45 of file config.h.
vmask
unsigned vmask[]
Definition at line 48 of file config.h.