ZEQ2-Lite: Source/Engine/libspeex/sb_celp.h File Reference
sb_celp.h File Reference
Sub-band CELP mode used for wideband encoding.
#include "modes.h"
#include <speex/speex_bits.h>
#include "nb_celp.h"
Data Structures
struct SBDecState
Structure representing the full state of the sub-band decoder.
struct SBEncState
Structure representing the full state of the sub-band encoder.
Functions
int sb_decode (void *state, SpeexBits *bits, void *out)
Decodes one frame.
int sb_decoder_ctl (void *state, int request, void *ptr)
void sb_decoder_destroy (void *state)
De-allocates decoder state resources.
void * sb_decoder_init (const SpeexMode *m)
Initializes decoder state.
int sb_encode (void *state, void *in, SpeexBits *bits)
Encodes one frame.
int sb_encoder_ctl (void *state, int request, void *ptr)
void sb_encoder_destroy (void *state)
De-allocates encoder state resources.
void * sb_encoder_init (const SpeexMode *m)
Initializes encoder state.
Detailed Description
Sub-band CELP mode used for wideband encoding.
Definition in file sb_celp.h.
Function Documentation
sb_decode()
int sb_decode (void * state, SpeexBits * bits, void * out)
Decodes one frame.
Definition at line 873 of file sb_celp.c.
 {
    int i, sub;
    SBDecState *st;
    int wideband;
    int ret;
    char *stack;
    VARDECL(spx_word32_t *low_pi_gain);
    VARDECL(spx_word16_t *low_exc_rms);
    VARDECL(spx_coef_t *ak);
    VARDECL(spx_lsp_t *qlsp);
    VARDECL(spx_lsp_t *interp_qlsp);
    spx_int32_t dtx;
    const SpeexSBMode *mode;
    spx_word16_t *out = (spx_word16_t*)vout;
    spx_word16_t *low_innov_alias;
    spx_word32_t exc_ener_sum = 0;
    st = (SBDecState*)state;
    stack=st->stack;
    mode = (const SpeexSBMode*)(st->mode->mode);
    low_innov_alias = out+st->frame_size;
    speex_decoder_ctl(st->st_low, SPEEX_SET_INNOVATION_SAVE, low_innov_alias);
    /* Decode the low-band */
    ret = speex_decode_native(st->st_low, bits, out);
    speex_decoder_ctl(st->st_low, SPEEX_GET_DTX_STATUS, &dtx);
    /* If error decoding the narrowband part, propagate error */
    if (ret!=0)
    {
       return ret;
    }
    if (!bits)
    {
       sb_decode_lost(st, out, dtx, stack);
       return 0;
    }
    if (st->encode_submode)
    {
       /*Check "wideband bit"*/
       if (speex_bits_remaining(bits)>0)
          wideband = speex_bits_peek(bits);
       else
          wideband = 0;
       if (wideband)
       {
          /*Regular wideband frame, read the submode*/
          wideband = speex_bits_unpack_unsigned(bits, 1);
          st->submodeID = speex_bits_unpack_unsigned(bits, SB_SUBMODE_BITS);
       } else
       {
          /*Was a narrowband frame, set "null submode"*/
          st->submodeID = 0;
       }
       if (st->submodeID != 0 && st->submodes[st->submodeID] == NULL)
       {
          speex_notify("Invalid mode encountered. The stream is corrupted.");
          return -2;
       }
    }
    /* If null mode (no transmission), just set a couple things to zero*/
    if (st->submodes[st->submodeID] == NULL)
    {
       if (dtx)
       {
          sb_decode_lost(st, out, 1, stack);
          return 0;
       }
       for (i=0;i<st->frame_size;i++)
          out[st->frame_size+i]=VERY_SMALL;
       st->first=1;
       /* Final signal synthesis from excitation */
       iir_mem16(out+st->frame_size, st->interp_qlpc, out+st->frame_size, st->frame_size, st->lpcSize, st->mem_sp, stack);
       qmf_synth(out, out+st->frame_size, h0, out, st->full_frame_size, QMF_ORDER, st->g0_mem, st->g1_mem, stack);
       return 0;
    }
    ALLOC(low_pi_gain, st->nbSubframes, spx_word32_t);
    ALLOC(low_exc_rms, st->nbSubframes, spx_word16_t);
    speex_decoder_ctl(st->st_low, SPEEX_GET_PI_GAIN, low_pi_gain);
    speex_decoder_ctl(st->st_low, SPEEX_GET_EXC, low_exc_rms);
    ALLOC(qlsp, st->lpcSize, spx_lsp_t);
    ALLOC(interp_qlsp, st->lpcSize, spx_lsp_t);
    SUBMODE(lsp_unquant)(qlsp, st->lpcSize, bits);
    if (st->first)
    {
       for (i=0;i<st->lpcSize;i++)
          st->old_qlsp[i] = qlsp[i];
    }
    ALLOC(ak, st->lpcSize, spx_coef_t);
    for (sub=0;sub<st->nbSubframes;sub++)
    {
       VARDECL(spx_word32_t *exc);
       spx_word16_t *innov_save=NULL;
       spx_word16_t *sp;
       spx_word16_t filter_ratio;
       spx_word16_t el=0;
       int offset;
       spx_word32_t rl=0,rh=0;
       offset = st->subframeSize*sub;
       sp=out+st->frame_size+offset;
       ALLOC(exc, st->subframeSize, spx_word32_t);
       /* Pointer for saving innovation */
       if (st->innov_save)
       {
          innov_save = st->innov_save+2*offset;
          SPEEX_MEMSET(innov_save, 0, 2*st->subframeSize);
       }
       /* LSP interpolation */
       lsp_interpolate(st->old_qlsp, qlsp, interp_qlsp, st->lpcSize, sub, st->nbSubframes);
       lsp_enforce_margin(interp_qlsp, st->lpcSize, LSP_MARGIN);
       /* LSP to LPC */
       lsp_to_lpc(interp_qlsp, ak, st->lpcSize, stack);
       /* Calculate reponse ratio between the low and high filter in the middle
          of the band (4000 Hz) */
          st->pi_gain[sub]=LPC_SCALING;
          rh = LPC_SCALING;
          for (i=0;i<st->lpcSize;i+=2)
          {
             rh += ak[i+1] - ak[i];
             st->pi_gain[sub] += ak[i] + ak[i+1];
          }
          rl = low_pi_gain[sub];
 #ifdef FIXED_POINT
          filter_ratio=EXTRACT16(SATURATE(PDIV32(SHL32(ADD32(rl,82),7),ADD32(82,rh)),32767));
 #else
          filter_ratio=(rl+.01)/(rh+.01);
 #endif
       SPEEX_MEMSET(exc, 0, st->subframeSize);
       if (!SUBMODE(innovation_unquant))
       {
          spx_word32_t g;
          int quant;
          quant = speex_bits_unpack_unsigned(bits, 5);
          g= spx_exp(MULT16_16(QCONST16(.125f,11),(quant-10)));
          g = PDIV32(g, filter_ratio);
          for (i=0;i<st->subframeSize;i+=2)
          {
             exc[i]=SHL32(MULT16_32_P15(MULT16_16_Q15(mode->folding_gain,low_innov_alias[offset+i]),SHL32(g,6)),SIG_SHIFT);
             exc[i+1]=NEG32(SHL32(MULT16_32_P15(MULT16_16_Q15(mode->folding_gain,low_innov_alias[offset+i+1]),SHL32(g,6)),SIG_SHIFT));
          }
       } else {
          spx_word16_t gc;
          spx_word32_t scale;
          int qgc = speex_bits_unpack_unsigned(bits, 4);
          el = low_exc_rms[sub];
          gc = MULT16_16_Q15(QCONST16(0.87360,15),gc_quant_bound[qgc]);
          if (st->subframeSize==80)
             gc = MULT16_16_P14(QCONST16(1.4142f,14),gc);
          scale = SHL32(PDIV32(SHL32(MULT16_16(gc, el),3), filter_ratio),SIG_SHIFT-3);
          SUBMODE(innovation_unquant)(exc, SUBMODE(innovation_params), st->subframeSize,
                                      bits, stack, &st->seed);
          signal_mul(exc,exc,scale,st->subframeSize);
          if (SUBMODE(double_codebook)) {
             char *tmp_stack=stack;
             VARDECL(spx_sig_t *innov2);
             ALLOC(innov2, st->subframeSize, spx_sig_t);
             SPEEX_MEMSET(innov2, 0, st->subframeSize);
             SUBMODE(innovation_unquant)(innov2, SUBMODE(innovation_params), st->subframeSize,
                                         bits, stack, &st->seed);
             signal_mul(innov2, innov2, MULT16_32_P15(QCONST16(0.4f,15),scale), st->subframeSize);
             for (i=0;i<st->subframeSize;i++)
                exc[i] = ADD32(exc[i],innov2[i]);
             stack = tmp_stack;
          }
       }
       if (st->innov_save)
       {
          for (i=0;i<st->subframeSize;i++)
             innov_save[2*i]=EXTRACT16(PSHR32(exc[i],SIG_SHIFT));
       }
       iir_mem16(st->excBuf, st->interp_qlpc, sp, st->subframeSize, st->lpcSize,
                st->mem_sp, stack);
       for (i=0;i<st->subframeSize;i++)
          st->excBuf[i]=EXTRACT16(PSHR32(exc[i],SIG_SHIFT));
       for (i=0;i<st->lpcSize;i++)
          st->interp_qlpc[i] = ak[i];
       st->exc_rms[sub] = compute_rms16(st->excBuf, st->subframeSize);
       exc_ener_sum = ADD32(exc_ener_sum, DIV32(MULT16_16(st->exc_rms[sub],st->exc_rms[sub]), st->nbSubframes));
    }
    st->last_ener = spx_sqrt(exc_ener_sum);
    qmf_synth(out, out+st->frame_size, h0, out, st->full_frame_size, QMF_ORDER, st->g0_mem, st->g1_mem, stack);
    for (i=0;i<st->lpcSize;i++)
       st->old_qlsp[i] = qlsp[i];
    st->first=0;
    return 0;
 }
References ADD32, ALLOC, bits(), compute_rms16(), DIV32, SBDecState::encode_submode, SBDecState::exc_rms, SBDecState::excBuf, EXTRACT16, SBDecState::first, SBDecState::frame_size, SBDecState::full_frame_size, SBDecState::g0_mem, SBDecState::g1_mem, gc_quant_bound, h0, iir_mem16(), SBDecState::innov_save, SBDecState::interp_qlpc, SBDecState::last_ener, LPC_SCALING, SBDecState::lpcSize, lsp_enforce_margin(), lsp_interpolate(), LSP_MARGIN, lsp_to_lpc(), SBDecState::mem_sp, SBDecState::mode, SpeexMode::mode, MULT16_16, MULT16_16_P14, MULT16_16_Q15, MULT16_32_P15, SBDecState::nbSubframes, NEG32, NULL, SBDecState::old_qlsp, out, PDIV32, SBDecState::pi_gain, PSHR32, QCONST16, QMF_ORDER, qmf_synth(), SATURATE, sb_decode_lost(), SB_SUBMODE_BITS, SBDecState::seed, SHL32, signal_mul(), sp, speex_bits_peek(), speex_bits_remaining(), speex_bits_unpack_unsigned(), speex_decode_native(), speex_decoder_ctl(), SPEEX_GET_DTX_STATUS, SPEEX_GET_EXC, SPEEX_GET_PI_GAIN, SPEEX_MEMSET, speex_notify(), SPEEX_SET_INNOVATION_SAVE, spx_exp, spx_sqrt, SBDecState::st_low, SBDecState::stack, SBDecState::subframeSize, SUBMODE, SBDecState::submodeID, SBDecState::submodes, VARDECL, and VERY_SMALL.
sb_decoder_ctl()
int sb_decoder_ctl (void * state, int request, void * ptr)
Definition at line 1360 of file sb_celp.c.
 {
    SBDecState *st;
    st=(SBDecState*)state;
    switch(request)
    {
    case SPEEX_SET_HIGH_MODE:
       st->submodeID = (*(spx_int32_t*)ptr);
       break;
    case SPEEX_SET_LOW_MODE:
       speex_decoder_ctl(st->st_low, SPEEX_SET_LOW_MODE, ptr);
       break;
    case SPEEX_GET_LOW_MODE:
       speex_decoder_ctl(st->st_low, SPEEX_GET_LOW_MODE, ptr);
       break;
    case SPEEX_GET_FRAME_SIZE:
       (*(spx_int32_t*)ptr) = st->full_frame_size;
       break;
    case SPEEX_SET_ENH:
       speex_decoder_ctl(st->st_low, request, ptr);
       st->lpc_enh_enabled = *((spx_int32_t*)ptr);
       break;
    case SPEEX_GET_ENH:
       *((spx_int32_t*)ptr) = st->lpc_enh_enabled;
       break;
    case SPEEX_SET_MODE:
    case SPEEX_SET_QUALITY:
       {
          spx_int32_t nb_qual;
          int quality = (*(spx_int32_t*)ptr);
          if (quality < 0)
             quality = 0;
          if (quality > 10)
             quality = 10;
          st->submodeID = ((const SpeexSBMode*)(st->mode->mode))->quality_map[quality];
          nb_qual = ((const SpeexSBMode*)(st->mode->mode))->low_quality_map[quality];
          speex_decoder_ctl(st->st_low, SPEEX_SET_MODE, &nb_qual);
       }
       break;
    case SPEEX_GET_BITRATE:
       speex_decoder_ctl(st->st_low, request, ptr);
       if (st->submodes[st->submodeID])
          (*(spx_int32_t*)ptr) += st->sampling_rate*SUBMODE(bits_per_frame)/st->full_frame_size;
       else
          (*(spx_int32_t*)ptr) += st->sampling_rate*(SB_SUBMODE_BITS+1)/st->full_frame_size;
       break;
    case SPEEX_SET_SAMPLING_RATE:
       {
          spx_int32_t tmp=(*(spx_int32_t*)ptr);
          st->sampling_rate = tmp;
          tmp>>=1;
          speex_decoder_ctl(st->st_low, SPEEX_SET_SAMPLING_RATE, &tmp);
       }
       break;
    case SPEEX_GET_SAMPLING_RATE:
       (*(spx_int32_t*)ptr)=st->sampling_rate;
       break;
    case SPEEX_SET_HANDLER:
       speex_decoder_ctl(st->st_low, SPEEX_SET_HANDLER, ptr);
       break;
    case SPEEX_SET_USER_HANDLER:
       speex_decoder_ctl(st->st_low, SPEEX_SET_USER_HANDLER, ptr);
       break;
    case SPEEX_RESET_STATE:
       {
          int i;
          for (i=0;i<2*st->lpcSize;i++)
             st->mem_sp[i]=0;
          for (i=0;i<QMF_ORDER;i++)
             st->g0_mem[i]=st->g1_mem[i]=0;
          st->last_ener=0;
       }
       break;
    case SPEEX_SET_SUBMODE_ENCODING:
       st->encode_submode = (*(spx_int32_t*)ptr);
       speex_decoder_ctl(st->st_low, SPEEX_SET_SUBMODE_ENCODING, ptr);
       break;
    case SPEEX_GET_SUBMODE_ENCODING:
       (*(spx_int32_t*)ptr) = st->encode_submode;
       break;
    case SPEEX_GET_LOOKAHEAD:
       speex_decoder_ctl(st->st_low, SPEEX_GET_LOOKAHEAD, ptr);
       (*(spx_int32_t*)ptr) = 2*(*(spx_int32_t*)ptr);
       break;
    case SPEEX_SET_HIGHPASS:
       speex_decoder_ctl(st->st_low, SPEEX_SET_HIGHPASS, ptr);
       break;
    case SPEEX_GET_HIGHPASS:
       speex_decoder_ctl(st->st_low, SPEEX_GET_HIGHPASS, ptr);
       break;
    case SPEEX_GET_ACTIVITY:
       speex_decoder_ctl(st->st_low, SPEEX_GET_ACTIVITY, ptr);
       break;
    case SPEEX_GET_PI_GAIN:
       {
          int i;
          spx_word32_t *g = (spx_word32_t*)ptr;
          for (i=0;i<st->nbSubframes;i++)
             g[i]=st->pi_gain[i];
       }
       break;
    case SPEEX_GET_EXC:
       {
          int i;
          for (i=0;i<st->nbSubframes;i++)
             ((spx_word16_t*)ptr)[i] = st->exc_rms[i];
       }
       break;
    case SPEEX_GET_DTX_STATUS:
       speex_decoder_ctl(st->st_low, SPEEX_GET_DTX_STATUS, ptr);
       break;
    case SPEEX_SET_INNOVATION_SAVE:
       st->innov_save = (spx_word16_t*)ptr;
       break;
    case SPEEX_SET_WIDEBAND:
       speex_decoder_ctl(st->st_low, SPEEX_SET_WIDEBAND, ptr);
       break;
    case SPEEX_GET_STACK:
       *((char**)ptr) = st->stack;
       break;
    default:
       speex_warning_int("Unknown nb_ctl request: ", request);
       return -1;
    }
    return 0;
 }
References SBDecState::encode_submode, SBDecState::exc_rms, SBDecState::full_frame_size, SBDecState::g0_mem, SBDecState::g1_mem, SBDecState::innov_save, SBDecState::last_ener, SBDecState::lpc_enh_enabled, SBDecState::lpcSize, SBDecState::mem_sp, SBDecState::mode, SpeexMode::mode, SBDecState::nbSubframes, SBDecState::pi_gain, ptr(), QMF_ORDER, quality, quality_map, SBDecState::sampling_rate, SB_SUBMODE_BITS, speex_decoder_ctl(), SPEEX_GET_ACTIVITY, SPEEX_GET_BITRATE, SPEEX_GET_DTX_STATUS, SPEEX_GET_ENH, SPEEX_GET_EXC, SPEEX_GET_FRAME_SIZE, SPEEX_GET_HIGHPASS, SPEEX_GET_LOOKAHEAD, SPEEX_GET_LOW_MODE, SPEEX_GET_PI_GAIN, SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_GET_SUBMODE_ENCODING, SPEEX_RESET_STATE, SPEEX_SET_ENH, SPEEX_SET_HANDLER, SPEEX_SET_HIGH_MODE, SPEEX_SET_HIGHPASS, SPEEX_SET_INNOVATION_SAVE, SPEEX_SET_LOW_MODE, SPEEX_SET_MODE, SPEEX_SET_QUALITY, SPEEX_SET_SAMPLING_RATE, SPEEX_SET_SUBMODE_ENCODING, SPEEX_SET_USER_HANDLER, SPEEX_SET_WIDEBAND, speex_warning_int(), SBDecState::st_low, SBDecState::stack, SUBMODE, SBDecState::submodeID, and SBDecState::submodes.
sb_decoder_destroy()
void sb_decoder_destroy (void * state)
De-allocates decoder state resources.
Definition at line 814 of file sb_celp.c.
 {
    SBDecState *st;
    st = (SBDecState*)state;
    speex_decoder_destroy(st->st_low);
 #if !(defined(VAR_ARRAYS) || defined (USE_ALLOCA))
    /*speex_free_scratch(st->stack);*/
 #endif
    speex_free(st->g0_mem);
    speex_free(st->g1_mem);
    speex_free(st->excBuf);
    speex_free(st->old_qlsp);
    speex_free(st->interp_qlpc);
    speex_free(st->pi_gain);
    speex_free(st->exc_rms);
    speex_free(st->mem_sp);
    speex_free(state);
 }
References SBDecState::exc_rms, SBDecState::excBuf, SBDecState::g0_mem, SBDecState::g1_mem, SBDecState::interp_qlpc, SBDecState::mem_sp, SBDecState::old_qlsp, SBDecState::pi_gain, speex_decoder_destroy(), speex_free(), and SBDecState::st_low.
sb_decoder_init()
void* sb_decoder_init (const SpeexMode * m)
Initializes decoder state.
Definition at line 755 of file sb_celp.c.
 {
    spx_int32_t tmp;
    SBDecState *st;
    const SpeexSBMode *mode;
    st = (SBDecState*)speex_alloc(sizeof(SBDecState));
    if (!st)
       return NULL;
    st->mode = m;
    mode=(const SpeexSBMode*)m->mode;
    st->encode_submode = 1;
    st->st_low = speex_decoder_init(mode->nb_mode);
 #if defined(VAR_ARRAYS) || defined (USE_ALLOCA)
    st->stack = NULL;
 #else
    /*st->stack = (char*)speex_alloc_scratch(SB_DEC_STACK);*/
    speex_decoder_ctl(st->st_low, SPEEX_GET_STACK, &st->stack);
 #endif
    st->full_frame_size = 2*mode->frameSize;
    st->frame_size = mode->frameSize;
    st->subframeSize = mode->subframeSize;
    st->nbSubframes = mode->frameSize/mode->subframeSize;
    st->lpcSize=mode->lpcSize;
    speex_decoder_ctl(st->st_low, SPEEX_GET_SAMPLING_RATE, &st->sampling_rate);
    st->sampling_rate*=2;
    tmp=1;
    speex_decoder_ctl(st->st_low, SPEEX_SET_WIDEBAND, &tmp);
    st->submodes=mode->submodes;
    st->submodeID=mode->defaultSubmode;
    st->first=1;
    st->g0_mem = (spx_word16_t*)speex_alloc((QMF_ORDER)*sizeof(spx_word16_t));
    st->g1_mem = (spx_word16_t*)speex_alloc((QMF_ORDER)*sizeof(spx_word16_t));
    st->excBuf = (spx_word16_t*)speex_alloc((st->subframeSize)*sizeof(spx_word16_t));
    st->old_qlsp = (spx_lsp_t*)speex_alloc((st->lpcSize)*sizeof(spx_lsp_t));
    st->interp_qlpc = (spx_coef_t*)speex_alloc(st->lpcSize*sizeof(spx_coef_t));
    st->pi_gain = (spx_word32_t*)speex_alloc((st->nbSubframes)*sizeof(spx_word32_t));
    st->exc_rms = (spx_word16_t*)speex_alloc((st->nbSubframes)*sizeof(spx_word16_t));
    st->mem_sp = (spx_mem_t*)speex_alloc((2*st->lpcSize)*sizeof(spx_mem_t));
    st->innov_save = NULL;
    st->lpc_enh_enabled=0;
    st->seed = 1000;
 #ifdef ENABLE_VALGRIND
    VALGRIND_MAKE_READABLE(st, (st->stack-(char*)st));
 #endif
    return st;
 }
References SBDecState::encode_submode, SBDecState::exc_rms, SBDecState::excBuf, SBDecState::first, SBDecState::frame_size, SBDecState::full_frame_size, SBDecState::g0_mem, SBDecState::g1_mem, SBDecState::innov_save, SBDecState::interp_qlpc, SBDecState::lpc_enh_enabled, SBDecState::lpcSize, m, SBDecState::mem_sp, SBDecState::mode, SBDecState::nbSubframes, NULL, SBDecState::old_qlsp, SBDecState::pi_gain, QMF_ORDER, SBDecState::sampling_rate, SBDecState::seed, speex_alloc(), speex_decoder_ctl(), speex_decoder_init(), SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_SET_WIDEBAND, SBDecState::st_low, SBDecState::stack, SBDecState::subframeSize, SBDecState::submodeID, and SBDecState::submodes.
sb_encode()
int sb_encode (void * state, void * in, SpeexBits * bits)
Encodes one frame.
Definition at line 304 of file sb_celp.c.
 {
    SBEncState *st;
    int i, roots, sub;
    char *stack;
    VARDECL(spx_mem_t *mem);
    VARDECL(spx_sig_t *innov);
    VARDECL(spx_word16_t *target);
    VARDECL(spx_word16_t *syn_resp);
    VARDECL(spx_word32_t *low_pi_gain);
    spx_word16_t *low;
    spx_word16_t *high;
    VARDECL(spx_word16_t *low_exc_rms);
    VARDECL(spx_word16_t *low_innov_rms);
    const SpeexSBMode *mode;
    spx_int32_t dtx;
    spx_word16_t *in = (spx_word16_t*)vin;
    spx_word16_t e_low=0, e_high=0;
    VARDECL(spx_coef_t *lpc);
    VARDECL(spx_coef_t *interp_lpc);
    VARDECL(spx_coef_t *bw_lpc1);
    VARDECL(spx_coef_t *bw_lpc2);
    VARDECL(spx_lsp_t *lsp);
    VARDECL(spx_lsp_t *qlsp);
    VARDECL(spx_lsp_t *interp_lsp);
    VARDECL(spx_lsp_t *interp_qlsp);
    st = (SBEncState*)state;
    stack=st->stack;
    mode = (const SpeexSBMode*)(st->mode->mode);
    low = in;
    high = in+st->frame_size;
    /* High-band buffering / sync with low band */
    /* Compute the two sub-bands by filtering with QMF h0*/
    qmf_decomp(in, h0, low, high, st->full_frame_size, QMF_ORDER, st->h0_mem, stack);
 #ifndef DISABLE_VBR
    if (st->vbr_enabled || st->vad_enabled)
    {
       /* Need to compute things here before the signal is trashed by the encoder */
       /*FIXME: Are the two signals (low, high) in sync? */
       e_low = compute_rms16(low, st->frame_size);
       e_high = compute_rms16(high, st->frame_size);
    }
 #endif /* #ifndef DISABLE_VBR */
    ALLOC(low_innov_rms, st->nbSubframes, spx_word16_t);
    speex_encoder_ctl(st->st_low, SPEEX_SET_INNOVATION_SAVE, low_innov_rms);
    /* Encode the narrowband part*/
    speex_encode_native(st->st_low, low, bits);
    high = high - (st->windowSize-st->frame_size);
    SPEEX_COPY(high, st->high, st->windowSize-st->frame_size);
    SPEEX_COPY(st->high, &high[st->frame_size], st->windowSize-st->frame_size);
    ALLOC(low_pi_gain, st->nbSubframes, spx_word32_t);
    ALLOC(low_exc_rms, st->nbSubframes, spx_word16_t);
    speex_encoder_ctl(st->st_low, SPEEX_GET_PI_GAIN, low_pi_gain);
    speex_encoder_ctl(st->st_low, SPEEX_GET_EXC, low_exc_rms);
    speex_encoder_ctl(st->st_low, SPEEX_GET_LOW_MODE, &dtx);
    if (dtx==0)
       dtx=1;
    else
       dtx=0;
    ALLOC(lpc, st->lpcSize, spx_coef_t);
    ALLOC(interp_lpc, st->lpcSize, spx_coef_t);
    ALLOC(bw_lpc1, st->lpcSize, spx_coef_t);
    ALLOC(bw_lpc2, st->lpcSize, spx_coef_t);
    ALLOC(lsp, st->lpcSize, spx_lsp_t);
    ALLOC(qlsp, st->lpcSize, spx_lsp_t);
    ALLOC(interp_lsp, st->lpcSize, spx_lsp_t);
    ALLOC(interp_qlsp, st->lpcSize, spx_lsp_t);
    {
       VARDECL(spx_word16_t *autocorr);
       VARDECL(spx_word16_t *w_sig);
       ALLOC(autocorr, st->lpcSize+1, spx_word16_t);
       ALLOC(w_sig, st->windowSize, spx_word16_t);
       /* Window for analysis */
       /* FIXME: This is a kludge */
       if (st->subframeSize==80)
       {
          for (i=0;i<st->windowSize;i++)
             w_sig[i] = EXTRACT16(SHR32(MULT16_16(high[i],st->window[i>>1]),SIG_SHIFT));
       } else {
          for (i=0;i<st->windowSize;i++)
             w_sig[i] = EXTRACT16(SHR32(MULT16_16(high[i],st->window[i]),SIG_SHIFT));
       }
       /* Compute auto-correlation */
       _spx_autocorr(w_sig, autocorr, st->lpcSize+1, st->windowSize);
       autocorr[0] = ADD16(autocorr[0],MULT16_16_Q15(autocorr[0],st->lpc_floor)); /* Noise floor in auto-correlation domain */
       /* Lag windowing: equivalent to filtering in the power-spectrum domain */
       for (i=0;i<st->lpcSize+1;i++)
          autocorr[i] = MULT16_16_Q14(autocorr[i],st->lagWindow[i]);
       /* Levinson-Durbin */
       _spx_lpc(lpc, autocorr, st->lpcSize);
    }
    /* LPC to LSPs (x-domain) transform */
    roots=lpc_to_lsp (lpc, st->lpcSize, lsp, 10, LSP_DELTA1, stack);
    if (roots!=st->lpcSize)
    {
       roots = lpc_to_lsp (lpc, st->lpcSize, lsp, 10, LSP_DELTA2, stack);
       if (roots!=st->lpcSize) {
          /*If we can't find all LSP's, do some damage control and use a flat filter*/
          for (i=0;i<st->lpcSize;i++)
          {
             lsp[i]=st->old_lsp[i];
          }
       }
    }
 #ifndef DISABLE_VBR
    /* VBR code */
    if ((st->vbr_enabled || st->vad_enabled) && !dtx)
    {
       float ratio;
       if (st->abr_enabled)
       {
          float qual_change=0;
          if (st->abr_drift2 * st->abr_drift > 0)
          {
             /* Only adapt if long-term and short-term drift are the same sign */
             qual_change = -.00001*st->abr_drift/(1+st->abr_count);
             if (qual_change>.1)
                qual_change=.1;
             if (qual_change<-.1)
                qual_change=-.1;
          }
          st->vbr_quality += qual_change;
          if (st->vbr_quality>10)
             st->vbr_quality=10;
          if (st->vbr_quality<0)
             st->vbr_quality=0;
       }
       ratio = 2*log((1.f+e_high)/(1.f+e_low));
       speex_encoder_ctl(st->st_low, SPEEX_GET_RELATIVE_QUALITY, &st->relative_quality);
       if (ratio<-4)
          ratio=-4;
       if (ratio>2)
          ratio=2;
       /*if (ratio>-2)*/
       if (st->vbr_enabled)
       {
          spx_int32_t modeid;
          modeid = mode->nb_modes-1;
          st->relative_quality+=1.0*(ratio+2);
      if (st->relative_quality<-1)
             st->relative_quality=-1;
          while (modeid)
          {
             int v1;
             float thresh;
             v1=(int)floor(st->vbr_quality);
             if (v1==10)
                thresh = mode->vbr_thresh[modeid][v1];
             else
                thresh = (st->vbr_quality-v1)   * mode->vbr_thresh[modeid][v1+1] +
                         (1+v1-st->vbr_quality) * mode->vbr_thresh[modeid][v1];
             if (st->relative_quality >= thresh && st->sampling_rate*st->submodes[modeid]->bits_per_frame/st->full_frame_size <= st->vbr_max_high)
                break;
             modeid--;
          }
          speex_encoder_ctl(state, SPEEX_SET_HIGH_MODE, &modeid);
          if (st->abr_enabled)
          {
             spx_int32_t bitrate;
             speex_encoder_ctl(state, SPEEX_GET_BITRATE, &bitrate);
             st->abr_drift+=(bitrate-st->abr_enabled);
             st->abr_drift2 = .95*st->abr_drift2 + .05*(bitrate-st->abr_enabled);
             st->abr_count += 1.0;
          }
       } else {
          /* VAD only */
          int modeid;
          if (st->relative_quality<2.0)
             modeid=1;
          else
             modeid=st->submodeSelect;
          /*speex_encoder_ctl(state, SPEEX_SET_MODE, &mode);*/
          st->submodeID=modeid;
       }
       /*fprintf (stderr, "%f %f\n", ratio, low_qual);*/
    }
 #endif /* #ifndef DISABLE_VBR */
    if (st->encode_submode)
    {
       speex_bits_pack(bits, 1, 1);
       if (dtx)
          speex_bits_pack(bits, 0, SB_SUBMODE_BITS);
       else
          speex_bits_pack(bits, st->submodeID, SB_SUBMODE_BITS);
    }
    /* If null mode (no transmission), just set a couple things to zero*/
    if (dtx || st->submodes[st->submodeID] == NULL)
    {
       for (i=0;i<st->frame_size;i++)
          high[i]=VERY_SMALL;
       for (i=0;i<st->lpcSize;i++)
          st->mem_sw[i]=0;
       st->first=1;
       /* Final signal synthesis from excitation */
       iir_mem16(high, st->interp_qlpc, high, st->frame_size, st->lpcSize, st->mem_sp, stack);
       if (dtx)
          return 0;
       else
          return 1;
    }
    /* LSP quantization */
    SUBMODE(lsp_quant)(lsp, qlsp, st->lpcSize, bits);
    if (st->first)
    {
       for (i=0;i<st->lpcSize;i++)
          st->old_lsp[i] = lsp[i];
       for (i=0;i<st->lpcSize;i++)
          st->old_qlsp[i] = qlsp[i];
    }
    ALLOC(mem, st->lpcSize, spx_mem_t);
    ALLOC(syn_resp, st->subframeSize, spx_word16_t);
    ALLOC(innov, st->subframeSize, spx_sig_t);
    ALLOC(target, st->subframeSize, spx_word16_t);
    for (sub=0;sub<st->nbSubframes;sub++)
    {
       VARDECL(spx_word16_t *exc);
       VARDECL(spx_word16_t *res);
       VARDECL(spx_word16_t *sw);
       spx_word16_t *sp;
       spx_word16_t filter_ratio;     /*Q7*/
       int offset;
       spx_word32_t rl, rh;           /*Q13*/
       spx_word16_t eh=0;
       offset = st->subframeSize*sub;
       sp=high+offset;
       ALLOC(exc, st->subframeSize, spx_word16_t);
       ALLOC(res, st->subframeSize, spx_word16_t);
       ALLOC(sw, st->subframeSize, spx_word16_t);
       /* LSP interpolation (quantized and unquantized) */
       lsp_interpolate(st->old_lsp, lsp, interp_lsp, st->lpcSize, sub, st->nbSubframes);
       lsp_interpolate(st->old_qlsp, qlsp, interp_qlsp, st->lpcSize, sub, st->nbSubframes);
       lsp_enforce_margin(interp_lsp, st->lpcSize, LSP_MARGIN);
       lsp_enforce_margin(interp_qlsp, st->lpcSize, LSP_MARGIN);
       lsp_to_lpc(interp_lsp, interp_lpc, st->lpcSize,stack);
       lsp_to_lpc(interp_qlsp, st->interp_qlpc, st->lpcSize, stack);
       bw_lpc(st->gamma1, interp_lpc, bw_lpc1, st->lpcSize);
       bw_lpc(st->gamma2, interp_lpc, bw_lpc2, st->lpcSize);
       /* Compute mid-band (4000 Hz for wideband) response of low-band and high-band
          filters */
       st->pi_gain[sub]=LPC_SCALING;
       rh = LPC_SCALING;
       for (i=0;i<st->lpcSize;i+=2)
       {
          rh += st->interp_qlpc[i+1] - st->interp_qlpc[i];
          st->pi_gain[sub] += st->interp_qlpc[i] + st->interp_qlpc[i+1];
       }
       rl = low_pi_gain[sub];
 #ifdef FIXED_POINT
       filter_ratio=EXTRACT16(SATURATE(PDIV32(SHL32(ADD32(rl,82),7),ADD32(82,rh)),32767));
 #else
       filter_ratio=(rl+.01)/(rh+.01);
 #endif
       /* Compute "real excitation" */
       fir_mem16(sp, st->interp_qlpc, exc, st->subframeSize, st->lpcSize, st->mem_sp2, stack);
       /* Compute energy of low-band and high-band excitation */
       eh = compute_rms16(exc, st->subframeSize);
       if (!SUBMODE(innovation_quant)) {/* 1 for spectral folding excitation, 0 for stochastic */
          spx_word32_t g;   /*Q7*/
          spx_word16_t el;  /*Q0*/
          el = low_innov_rms[sub];
          /* Gain to use if we want to use the low-band excitation for high-band */
          g=PDIV32(MULT16_16(filter_ratio,eh),EXTEND32(ADD16(1,el)));
 #if 0
          {
             char *tmp_stack=stack;
             float *tmp_sig;
             float g2;
             ALLOC(tmp_sig, st->subframeSize, spx_sig_t);
             for (i=0;i<st->lpcSize;i++)
                mem[i]=st->mem_sp[i];
             iir_mem2(st->low_innov+offset, st->interp_qlpc, tmp_sig, st->subframeSize, st->lpcSize, mem);
             g2 = compute_rms(sp, st->subframeSize)/(.01+compute_rms(tmp_sig, st->subframeSize));
             /*fprintf (stderr, "gains: %f %f\n", g, g2);*/
             g = g2;
             stack = tmp_stack;
          }
 #endif
          /*print_vec(&g, 1, "gain factor");*/
          /* Gain quantization */
          {
             int quant = scal_quant(g, fold_quant_bound, 32);
             /*speex_warning_int("tata", quant);*/
             if (quant<0)
                quant=0;
             if (quant>31)
                quant=31;
             speex_bits_pack(bits, quant, 5);
          }
          if (st->innov_rms_save)
          {
             st->innov_rms_save[sub] = eh;
          }
          st->exc_rms[sub] = eh;
       } else {
          spx_word16_t gc;       /*Q7*/
          spx_word32_t scale;    /*Q14*/
          spx_word16_t el;       /*Q0*/
          el = low_exc_rms[sub]; /*Q0*/
          gc = PDIV32_16(MULT16_16(filter_ratio,1+eh),1+el);
          /* This is a kludge that cleans up a historical bug */
          if (st->subframeSize==80)
             gc = MULT16_16_P15(QCONST16(0.70711f,15),gc);
          /*printf ("%f %f %f %f\n", el, eh, filter_ratio, gc);*/
          {
             int qgc = scal_quant(gc, gc_quant_bound, 16);
             speex_bits_pack(bits, qgc, 4);
             gc = MULT16_16_Q15(QCONST16(0.87360,15),gc_quant_bound[qgc]);
          }
          if (st->subframeSize==80)
             gc = MULT16_16_P14(QCONST16(1.4142f,14), gc);
          scale = SHL32(MULT16_16(PDIV32_16(SHL32(EXTEND32(gc),SIG_SHIFT-6),filter_ratio),(1+el)),6);
          compute_impulse_response(st->interp_qlpc, bw_lpc1, bw_lpc2, syn_resp, st->subframeSize, st->lpcSize, stack);
          /* Reset excitation */
          for (i=0;i<st->subframeSize;i++)
             res[i]=VERY_SMALL;
          /* Compute zero response (ringing) of A(z/g1) / ( A(z/g2) * Aq(z) ) */
          for (i=0;i<st->lpcSize;i++)
             mem[i]=st->mem_sp[i];
          iir_mem16(res, st->interp_qlpc, res, st->subframeSize, st->lpcSize, mem, stack);
          for (i=0;i<st->lpcSize;i++)
             mem[i]=st->mem_sw[i];
          filter_mem16(res, bw_lpc1, bw_lpc2, res, st->subframeSize, st->lpcSize, mem, stack);
          /* Compute weighted signal */
          for (i=0;i<st->lpcSize;i++)
             mem[i]=st->mem_sw[i];
          filter_mem16(sp, bw_lpc1, bw_lpc2, sw, st->subframeSize, st->lpcSize, mem, stack);
          /* Compute target signal */
          for (i=0;i<st->subframeSize;i++)
             target[i]=SUB16(sw[i],res[i]);
          signal_div(target, target, scale, st->subframeSize);
          /* Reset excitation */
          SPEEX_MEMSET(innov, 0, st->subframeSize);
          /*print_vec(target, st->subframeSize, "\ntarget");*/
          SUBMODE(innovation_quant)(target, st->interp_qlpc, bw_lpc1, bw_lpc2,
                                    SUBMODE(innovation_params), st->lpcSize, st->subframeSize,
                                    innov, syn_resp, bits, stack, st->complexity, SUBMODE(double_codebook));
          /*print_vec(target, st->subframeSize, "after");*/
          signal_mul(innov, innov, scale, st->subframeSize);
          if (SUBMODE(double_codebook)) {
             char *tmp_stack=stack;
             VARDECL(spx_sig_t *innov2);
             ALLOC(innov2, st->subframeSize, spx_sig_t);
             SPEEX_MEMSET(innov2, 0, st->subframeSize);
             for (i=0;i<st->subframeSize;i++)
                target[i]=MULT16_16_P13(QCONST16(2.5f,13), target[i]);
             SUBMODE(innovation_quant)(target, st->interp_qlpc, bw_lpc1, bw_lpc2,
                                       SUBMODE(innovation_params), st->lpcSize, st->subframeSize,
                                       innov2, syn_resp, bits, stack, st->complexity, 0);
             signal_mul(innov2, innov2, MULT16_32_P15(QCONST16(0.4f,15),scale), st->subframeSize);
             for (i=0;i<st->subframeSize;i++)
                innov[i] = ADD32(innov[i],innov2[i]);
             stack = tmp_stack;
          }
          for (i=0;i<st->subframeSize;i++)
             exc[i] = PSHR32(innov[i],SIG_SHIFT);
          if (st->innov_rms_save)
          {
             st->innov_rms_save[sub] = MULT16_16_Q15(QCONST16(.70711f, 15), compute_rms(innov, st->subframeSize));
          }
          st->exc_rms[sub] = compute_rms16(exc, st->subframeSize);
       }
       /*Keep the previous memory*/
       for (i=0;i<st->lpcSize;i++)
          mem[i]=st->mem_sp[i];
       /* Final signal synthesis from excitation */
       iir_mem16(exc, st->interp_qlpc, sp, st->subframeSize, st->lpcSize, st->mem_sp, stack);
       /* Compute weighted signal again, from synthesized speech (not sure it's the right thing) */
       filter_mem16(sp, bw_lpc1, bw_lpc2, sw, st->subframeSize, st->lpcSize, st->mem_sw, stack);
    }
    for (i=0;i<st->lpcSize;i++)
       st->old_lsp[i] = lsp[i];
    for (i=0;i<st->lpcSize;i++)
       st->old_qlsp[i] = qlsp[i];
    st->first=0;
    return 1;
 }
References _spx_autocorr(), _spx_lpc(), SBEncState::abr_count, SBEncState::abr_drift, SBEncState::abr_drift2, SBEncState::abr_enabled, ADD16, ADD32, ALLOC, bits(), SpeexSubmode::bits_per_frame, bw_lpc(), SBEncState::complexity, compute_impulse_response(), compute_rms(), compute_rms16(), SBEncState::encode_submode, SBEncState::exc_rms, EXTEND32, EXTRACT16, filter_mem16(), fir_mem16(), SBEncState::first, fold_quant_bound, SBEncState::frame_size, SBEncState::full_frame_size, SBEncState::gamma1, SBEncState::gamma2, gc_quant_bound, h0, SBEncState::h0_mem, SBEncState::high, iir_mem16(), SBEncState::innov_rms_save, int(), SBEncState::interp_qlpc, SBEncState::lagWindow, SBEncState::lpc_floor, LPC_SCALING, lpc_to_lsp(), SBEncState::lpcSize, LSP_DELTA1, LSP_DELTA2, lsp_enforce_margin(), lsp_interpolate(), LSP_MARGIN, lsp_quant(), lsp_to_lpc(), SBEncState::mem_sp, SBEncState::mem_sp2, SBEncState::mem_sw, SBEncState::mode, SpeexMode::mode, MULT16_16, MULT16_16_P13, MULT16_16_P14, MULT16_16_P15, MULT16_16_Q14, MULT16_16_Q15, MULT16_32_P15, SBEncState::nbSubframes, NULL, SBEncState::old_lsp, SBEncState::old_qlsp, PDIV32, PDIV32_16, SBEncState::pi_gain, PSHR32, QCONST16, qmf_decomp(), QMF_ORDER, SBEncState::relative_quality, SBEncState::sampling_rate, SATURATE, SB_SUBMODE_BITS, scal_quant(), SHL32, SHR32, signal_div(), signal_mul(), sp, speex_bits_pack(), SPEEX_COPY, speex_encode_native(), speex_encoder_ctl(), SPEEX_GET_BITRATE, SPEEX_GET_EXC, SPEEX_GET_LOW_MODE, SPEEX_GET_PI_GAIN, SPEEX_GET_RELATIVE_QUALITY, SPEEX_MEMSET, SPEEX_SET_HIGH_MODE, SPEEX_SET_INNOVATION_SAVE, SBEncState::st_low, SBEncState::stack, SUB16, SBEncState::subframeSize, SUBMODE, SBEncState::submodeID, SBEncState::submodes, SBEncState::submodeSelect, SBEncState::vad_enabled, VARDECL, SBEncState::vbr_enabled, SBEncState::vbr_max_high, SBEncState::vbr_quality, VERY_SMALL, SBEncState::window, and SBEncState::windowSize.
sb_encoder_ctl()
int sb_encoder_ctl (void * state, int request, void * ptr)
Definition at line 1101 of file sb_celp.c.
 {
    SBEncState *st;
    st=(SBEncState*)state;
    switch(request)
    {
    case SPEEX_GET_FRAME_SIZE:
       (*(spx_int32_t*)ptr) = st->full_frame_size;
       break;
    case SPEEX_SET_HIGH_MODE:
       st->submodeSelect = st->submodeID = (*(spx_int32_t*)ptr);
       break;
    case SPEEX_SET_LOW_MODE:
       speex_encoder_ctl(st->st_low, SPEEX_SET_LOW_MODE, ptr);
       break;
    case SPEEX_SET_DTX:
       speex_encoder_ctl(st->st_low, SPEEX_SET_DTX, ptr);
       break;
    case SPEEX_GET_DTX:
       speex_encoder_ctl(st->st_low, SPEEX_GET_DTX, ptr);
       break;
    case SPEEX_GET_LOW_MODE:
       speex_encoder_ctl(st->st_low, SPEEX_GET_LOW_MODE, ptr);
       break;
    case SPEEX_SET_MODE:
       speex_encoder_ctl(st, SPEEX_SET_QUALITY, ptr);
       break;
 #ifndef DISABLE_VBR
    case SPEEX_SET_VBR:
       st->vbr_enabled = (*(spx_int32_t*)ptr);
       speex_encoder_ctl(st->st_low, SPEEX_SET_VBR, ptr);
       break;
    case SPEEX_GET_VBR:
       (*(spx_int32_t*)ptr) = st->vbr_enabled;
       break;
    case SPEEX_SET_VAD:
       st->vad_enabled = (*(spx_int32_t*)ptr);
       speex_encoder_ctl(st->st_low, SPEEX_SET_VAD, ptr);
       break;
    case SPEEX_GET_VAD:
       (*(spx_int32_t*)ptr) = st->vad_enabled;
       break;
 #endif /* #ifndef DISABLE_VBR */
 #if !defined(DISABLE_VBR) && !defined(DISABLE_FLOAT_API)
    case SPEEX_SET_VBR_QUALITY:
       {
          spx_int32_t q;
          float qual = (*(float*)ptr)+.6;
          st->vbr_quality = (*(float*)ptr);
          if (qual>10)
             qual=10;
          q=(int)floor(.5+*(float*)ptr);
          if (q>10)
             q=10;
          speex_encoder_ctl(st->st_low, SPEEX_SET_VBR_QUALITY, &qual);
          speex_encoder_ctl(state, SPEEX_SET_QUALITY, &q);
          break;
       }
    case SPEEX_GET_VBR_QUALITY:
       (*(float*)ptr) = st->vbr_quality;
       break;
 #endif /* #if !defined(DISABLE_VBR) && !defined(DISABLE_FLOAT_API) */
 #ifndef DISABLE_VBR
    case SPEEX_SET_ABR:
       st->abr_enabled = (*(spx_int32_t*)ptr);
       st->vbr_enabled = st->abr_enabled!=0;
       speex_encoder_ctl(st->st_low, SPEEX_SET_VBR, &st->vbr_enabled);
       if (st->vbr_enabled)
       {
          spx_int32_t i=10, rate, target;
          float vbr_qual;
          target = (*(spx_int32_t*)ptr);
          while (i>=0)
          {
             speex_encoder_ctl(st, SPEEX_SET_QUALITY, &i);
             speex_encoder_ctl(st, SPEEX_GET_BITRATE, &rate);
             if (rate <= target)
                break;
             i--;
          }
          vbr_qual=i;
          if (vbr_qual<0)
             vbr_qual=0;
          speex_encoder_ctl(st, SPEEX_SET_VBR_QUALITY, &vbr_qual);
          st->abr_count=0;
          st->abr_drift=0;
          st->abr_drift2=0;
       }
       break;
    case SPEEX_GET_ABR:
       (*(spx_int32_t*)ptr) = st->abr_enabled;
       break;
 #endif /* #ifndef DISABLE_VBR */
    case SPEEX_SET_QUALITY:
       {
          spx_int32_t nb_qual;
          int quality = (*(spx_int32_t*)ptr);
          if (quality < 0)
             quality = 0;
          if (quality > 10)
             quality = 10;
          st->submodeSelect = st->submodeID = ((const SpeexSBMode*)(st->mode->mode))->quality_map[quality];
          nb_qual = ((const SpeexSBMode*)(st->mode->mode))->low_quality_map[quality];
          speex_encoder_ctl(st->st_low, SPEEX_SET_MODE, &nb_qual);
       }
       break;
    case SPEEX_SET_COMPLEXITY:
       speex_encoder_ctl(st->st_low, SPEEX_SET_COMPLEXITY, ptr);
       st->complexity = (*(spx_int32_t*)ptr);
       if (st->complexity<1)
          st->complexity=1;
       break;
    case SPEEX_GET_COMPLEXITY:
       (*(spx_int32_t*)ptr) = st->complexity;
       break;
    case SPEEX_SET_BITRATE:
       {
          spx_int32_t i=10;
          spx_int32_t rate, target;
          target = (*(spx_int32_t*)ptr);
          while (i>=0)
          {
             speex_encoder_ctl(st, SPEEX_SET_QUALITY, &i);
             speex_encoder_ctl(st, SPEEX_GET_BITRATE, &rate);
             if (rate <= target)
                break;
             i--;
          }
       }
       break;
    case SPEEX_GET_BITRATE:
       speex_encoder_ctl(st->st_low, request, ptr);
       /*fprintf (stderr, "before: %d\n", (*(int*)ptr));*/
       if (st->submodes[st->submodeID])
          (*(spx_int32_t*)ptr) += st->sampling_rate*SUBMODE(bits_per_frame)/st->full_frame_size;
       else
          (*(spx_int32_t*)ptr) += st->sampling_rate*(SB_SUBMODE_BITS+1)/st->full_frame_size;
       /*fprintf (stderr, "after: %d\n", (*(int*)ptr));*/
       break;
    case SPEEX_SET_SAMPLING_RATE:
       {
          spx_int32_t tmp=(*(spx_int32_t*)ptr);
          st->sampling_rate = tmp;
          tmp>>=1;
          speex_encoder_ctl(st->st_low, SPEEX_SET_SAMPLING_RATE, &tmp);
       }
       break;
    case SPEEX_GET_SAMPLING_RATE:
       (*(spx_int32_t*)ptr)=st->sampling_rate;
       break;
    case SPEEX_RESET_STATE:
       {
          int i;
          st->first = 1;
          for (i=0;i<st->lpcSize;i++)
             st->old_lsp[i]= DIV32(MULT16_16(QCONST16(3.1415927f, LSP_SHIFT), i+1), st->lpcSize+1);
          for (i=0;i<st->lpcSize;i++)
             st->mem_sw[i]=st->mem_sp[i]=st->mem_sp2[i]=0;
          for (i=0;i<QMF_ORDER;i++)
             st->h0_mem[i]=st->h1_mem[i]=0;
       }
       break;
    case SPEEX_SET_SUBMODE_ENCODING:
       st->encode_submode = (*(spx_int32_t*)ptr);
       speex_encoder_ctl(st->st_low, SPEEX_SET_SUBMODE_ENCODING, ptr);
       break;
    case SPEEX_GET_SUBMODE_ENCODING:
       (*(spx_int32_t*)ptr) = st->encode_submode;
       break;
    case SPEEX_GET_LOOKAHEAD:
       speex_encoder_ctl(st->st_low, SPEEX_GET_LOOKAHEAD, ptr);
       (*(spx_int32_t*)ptr) = 2*(*(spx_int32_t*)ptr) + QMF_ORDER - 1;
       break;
    case SPEEX_SET_PLC_TUNING:
       speex_encoder_ctl(st->st_low, SPEEX_SET_PLC_TUNING, ptr);
       break;
    case SPEEX_GET_PLC_TUNING:
       speex_encoder_ctl(st->st_low, SPEEX_GET_PLC_TUNING, ptr);
       break;
 #ifndef DISABLE_VBR
    case SPEEX_SET_VBR_MAX_BITRATE:
       {
          st->vbr_max = (*(spx_int32_t*)ptr);
          if (SPEEX_SET_VBR_MAX_BITRATE<1)
          {
             speex_encoder_ctl(st->st_low, SPEEX_SET_VBR_MAX_BITRATE, &st->vbr_max);
             st->vbr_max_high = 17600;
          } else {
             spx_int32_t low_rate;
             if (st->vbr_max >= 42200)
             {
                st->vbr_max_high = 17600;
             } else if (st->vbr_max >= 27800)
             {
                st->vbr_max_high = 9600;
             } else if (st->vbr_max > 20600)
             {
                st->vbr_max_high = 5600;
             } else {
                st->vbr_max_high = 1800;
             }
             if (st->subframeSize==80)
                st->vbr_max_high = 1800;
             low_rate = st->vbr_max - st->vbr_max_high;
             speex_encoder_ctl(st->st_low, SPEEX_SET_VBR_MAX_BITRATE, &low_rate);
          }
       }
       break;
    case SPEEX_GET_VBR_MAX_BITRATE:
       (*(spx_int32_t*)ptr) = st->vbr_max;
       break;
 #endif /* #ifndef DISABLE_VBR */
    case SPEEX_SET_HIGHPASS:
       speex_encoder_ctl(st->st_low, SPEEX_SET_HIGHPASS, ptr);
       break;
    case SPEEX_GET_HIGHPASS:
       speex_encoder_ctl(st->st_low, SPEEX_GET_HIGHPASS, ptr);
       break;
    /* This is all internal stuff past this point */
    case SPEEX_GET_PI_GAIN:
       {
          int i;
          spx_word32_t *g = (spx_word32_t*)ptr;
          for (i=0;i<st->nbSubframes;i++)
             g[i]=st->pi_gain[i];
       }
       break;
    case SPEEX_GET_EXC:
       {
          int i;
          for (i=0;i<st->nbSubframes;i++)
             ((spx_word16_t*)ptr)[i] = st->exc_rms[i];
       }
       break;
 #ifndef DISABLE_VBR
    case SPEEX_GET_RELATIVE_QUALITY:
       (*(float*)ptr)=st->relative_quality;
       break;
 #endif /* #ifndef DISABLE_VBR */
    case SPEEX_SET_INNOVATION_SAVE:
       st->innov_rms_save = (spx_word16_t*)ptr;
       break;
    case SPEEX_SET_WIDEBAND:
       speex_encoder_ctl(st->st_low, SPEEX_SET_WIDEBAND, ptr);
       break;
    case SPEEX_GET_STACK:
       *((char**)ptr) = st->stack;
       break;
    default:
       speex_warning_int("Unknown nb_ctl request: ", request);
       return -1;
    }
    return 0;
 }
References SBEncState::abr_count, SBEncState::abr_drift, SBEncState::abr_drift2, SBEncState::abr_enabled, SBEncState::complexity, DIV32, SBEncState::encode_submode, SBEncState::exc_rms, SBEncState::first, SBEncState::full_frame_size, SBEncState::h0_mem, SBEncState::h1_mem, SBEncState::innov_rms_save, int(), SBEncState::lpcSize, SBEncState::mem_sp, SBEncState::mem_sp2, SBEncState::mem_sw, SBEncState::mode, SpeexMode::mode, MULT16_16, SBEncState::nbSubframes, SBEncState::old_lsp, SBEncState::pi_gain, ptr(), QCONST16, QMF_ORDER, qual(), quality, quality_map, SBEncState::relative_quality, SBEncState::sampling_rate, SB_SUBMODE_BITS, speex_encoder_ctl(), SPEEX_GET_ABR, SPEEX_GET_BITRATE, SPEEX_GET_COMPLEXITY, SPEEX_GET_DTX, SPEEX_GET_EXC, SPEEX_GET_FRAME_SIZE, SPEEX_GET_HIGHPASS, SPEEX_GET_LOOKAHEAD, SPEEX_GET_LOW_MODE, SPEEX_GET_PI_GAIN, SPEEX_GET_PLC_TUNING, SPEEX_GET_RELATIVE_QUALITY, SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_GET_SUBMODE_ENCODING, SPEEX_GET_VAD, SPEEX_GET_VBR, SPEEX_GET_VBR_MAX_BITRATE, SPEEX_GET_VBR_QUALITY, SPEEX_RESET_STATE, SPEEX_SET_ABR, SPEEX_SET_BITRATE, SPEEX_SET_COMPLEXITY, SPEEX_SET_DTX, SPEEX_SET_HIGH_MODE, SPEEX_SET_HIGHPASS, SPEEX_SET_INNOVATION_SAVE, SPEEX_SET_LOW_MODE, SPEEX_SET_MODE, SPEEX_SET_PLC_TUNING, SPEEX_SET_QUALITY, SPEEX_SET_SAMPLING_RATE, SPEEX_SET_SUBMODE_ENCODING, SPEEX_SET_VAD, SPEEX_SET_VBR, SPEEX_SET_VBR_MAX_BITRATE, SPEEX_SET_VBR_QUALITY, SPEEX_SET_WIDEBAND, speex_warning_int(), SBEncState::st_low, SBEncState::stack, SBEncState::subframeSize, SUBMODE, SBEncState::submodeID, SBEncState::submodes, SBEncState::submodeSelect, SBEncState::vad_enabled, SBEncState::vbr_enabled, SBEncState::vbr_max, SBEncState::vbr_max_high, and SBEncState::vbr_quality.
sb_encoder_destroy()
void sb_encoder_destroy (void * state)
De-allocates encoder state resources.
Definition at line 275 of file sb_celp.c.
 {
    SBEncState *st=(SBEncState*)state;
    speex_encoder_destroy(st->st_low);
 #if !(defined(VAR_ARRAYS) || defined (USE_ALLOCA))
    /*speex_free_scratch(st->stack);*/
 #endif
    speex_free(st->high);
    speex_free(st->h0_mem);
    speex_free(st->h1_mem);
    speex_free(st->old_lsp);
    speex_free(st->old_qlsp);
    speex_free(st->interp_qlpc);
    speex_free(st->pi_gain);
    speex_free(st->exc_rms);
    speex_free(st->mem_sp);
    speex_free(st->mem_sp2);
    speex_free(st->mem_sw);
    speex_free(st);
 }
References SBEncState::exc_rms, SBEncState::h0_mem, SBEncState::h1_mem, SBEncState::high, SBEncState::interp_qlpc, SBEncState::mem_sp, SBEncState::mem_sp2, SBEncState::mem_sw, SBEncState::old_lsp, SBEncState::old_qlsp, SBEncState::pi_gain, speex_encoder_destroy(), speex_free(), and SBEncState::st_low.
sb_encoder_init()
void* sb_encoder_init (const SpeexMode * m)
Initializes encoder state.
Definition at line 190 of file sb_celp.c.
 {
    int i;
    spx_int32_t tmp;
    SBEncState *st;
    const SpeexSBMode *mode;
    st = (SBEncState*)speex_alloc(sizeof(SBEncState));
    if (!st)
       return NULL;
    st->mode = m;
    mode = (const SpeexSBMode*)m->mode;
    st->st_low = speex_encoder_init(mode->nb_mode);
 #if defined(VAR_ARRAYS) || defined (USE_ALLOCA)
    st->stack = NULL;
 #else
    /*st->stack = (char*)speex_alloc_scratch(SB_ENC_STACK);*/
    speex_encoder_ctl(st->st_low, SPEEX_GET_STACK, &st->stack);
 #endif
    st->full_frame_size = 2*mode->frameSize;
    st->frame_size = mode->frameSize;
    st->subframeSize = mode->subframeSize;
    st->nbSubframes = mode->frameSize/mode->subframeSize;
    st->windowSize = st->frame_size+st->subframeSize;
    st->lpcSize=mode->lpcSize;
    st->encode_submode = 1;
    st->submodes=mode->submodes;
    st->submodeSelect = st->submodeID=mode->defaultSubmode;
    tmp=9;
    speex_encoder_ctl(st->st_low, SPEEX_SET_QUALITY, &tmp);
    tmp=1;
    speex_encoder_ctl(st->st_low, SPEEX_SET_WIDEBAND, &tmp);
    st->lpc_floor = mode->lpc_floor;
    st->gamma1=mode->gamma1;
    st->gamma2=mode->gamma2;
    st->first=1;
    st->high=(spx_word16_t*)speex_alloc((st->windowSize-st->frame_size)*sizeof(spx_word16_t));
    st->h0_mem=(spx_word16_t*)speex_alloc((QMF_ORDER)*sizeof(spx_word16_t));
    st->h1_mem=(spx_word16_t*)speex_alloc((QMF_ORDER)*sizeof(spx_word16_t));
    st->window= lpc_window;
    st->lagWindow = lag_window;
    st->old_lsp = (spx_lsp_t*)speex_alloc(st->lpcSize*sizeof(spx_lsp_t));
    st->old_qlsp = (spx_lsp_t*)speex_alloc(st->lpcSize*sizeof(spx_lsp_t));
    st->interp_qlpc = (spx_coef_t*)speex_alloc(st->lpcSize*sizeof(spx_coef_t));
    st->pi_gain = (spx_word32_t*)speex_alloc((st->nbSubframes)*sizeof(spx_word32_t));
    st->exc_rms = (spx_word16_t*)speex_alloc((st->nbSubframes)*sizeof(spx_word16_t));
    st->innov_rms_save = NULL;
    st->mem_sp = (spx_mem_t*)speex_alloc((st->lpcSize)*sizeof(spx_mem_t));
    st->mem_sp2 = (spx_mem_t*)speex_alloc((st->lpcSize)*sizeof(spx_mem_t));
    st->mem_sw = (spx_mem_t*)speex_alloc((st->lpcSize)*sizeof(spx_mem_t));
    for (i=0;i<st->lpcSize;i++)
       st->old_lsp[i]= DIV32(MULT16_16(QCONST16(3.1415927f, LSP_SHIFT), i+1), st->lpcSize+1);
 #ifndef DISABLE_VBR
    st->vbr_quality = 8;
    st->vbr_enabled = 0;
    st->vbr_max = 0;
    st->vbr_max_high = 20000;  /* We just need a big value here */
    st->vad_enabled = 0;
    st->abr_enabled = 0;
    st->relative_quality=0;
 #endif /* #ifndef DISABLE_VBR */
    st->complexity=2;
    speex_encoder_ctl(st->st_low, SPEEX_GET_SAMPLING_RATE, &st->sampling_rate);
    st->sampling_rate*=2;
 #ifdef ENABLE_VALGRIND
    VALGRIND_MAKE_READABLE(st, (st->stack-(char*)st));
 #endif
    return st;
 }
References SBEncState::abr_enabled, SBEncState::complexity, DIV32, SBEncState::encode_submode, SBEncState::exc_rms, SBEncState::first, SBEncState::frame_size, SBEncState::full_frame_size, SBEncState::gamma1, SBEncState::gamma2, SBEncState::h0_mem, SBEncState::h1_mem, SBEncState::high, SBEncState::innov_rms_save, SBEncState::interp_qlpc, lag_window, SBEncState::lagWindow, SBEncState::lpc_floor, lpc_window, SBEncState::lpcSize, m, SBEncState::mem_sp, SBEncState::mem_sp2, SBEncState::mem_sw, SBEncState::mode, MULT16_16, SBEncState::nbSubframes, NULL, SBEncState::old_lsp, SBEncState::old_qlsp, SBEncState::pi_gain, QCONST16, QMF_ORDER, SBEncState::relative_quality, SBEncState::sampling_rate, speex_alloc(), speex_encoder_ctl(), speex_encoder_init(), SPEEX_GET_SAMPLING_RATE, SPEEX_GET_STACK, SPEEX_SET_QUALITY, SPEEX_SET_WIDEBAND, SBEncState::st_low, SBEncState::stack, SBEncState::subframeSize, SBEncState::submodeID, SBEncState::submodes, SBEncState::submodeSelect, SBEncState::vad_enabled, SBEncState::vbr_enabled, SBEncState::vbr_max, SBEncState::vbr_max_high, SBEncState::vbr_quality, SBEncState::window, and SBEncState::windowSize.