ZEQ2-Lite: Tools/MinGW/include/math.h File Reference
math.h File Reference
#include <_mingw.h>
Data Structures
struct _complex
struct _exception
Macros
#define __MINGW_FPCLASS_DEFINED 1
#define _DOMAIN 1 /* domain error in argument */
#define _FPCLASS_ND 0x0010 /* Negative Denormal */
#define _FPCLASS_NINF 0x0004 /* Negative Infinity */
#define _FPCLASS_NN 0x0008 /* Negative Normal */
#define _FPCLASS_NZ 0x0020 /* Negative Zero */
#define _FPCLASS_PD 0x0080 /* Positive Denormal */
#define _FPCLASS_PINF 0x0200 /* Positive Infinity */
#define _FPCLASS_PN 0x0100 /* Positive Normal */
#define _FPCLASS_PZ 0x0040 /* Positive Zero */
#define _FPCLASS_QNAN 0x0002 /* Quiet "Not a Number" */
#define _FPCLASS_SNAN 0x0001 /* Signaling "Not a Number" */
#define _nan() nan("")
#define _nanf() nanf("")
#define _nanl() nanl("")
#define _OVERFLOW 3 /* range overflow */
#define _PLOSS 6 /* partial loss of precision */
#define _SING 2 /* singularity */
#define _TLOSS 5 /* total loss of precision */
#define _UNDERFLOW 4 /* range underflow */
#define DOMAIN _DOMAIN
#define FP_ILOGB0 ((int)0x80000000)
#define FP_ILOGBNAN ((int)0x80000000)
#define FP_INFINITE (FP_NAN | FP_NORMAL)
#define FP_NAN 0x0100
#define FP_NDENORM _FPCLASS_ND
#define FP_NINF _FPCLASS_NINF
#define FP_NNORM _FPCLASS_NN
#define FP_NORMAL 0x0400
#define FP_NZERO _FPCLASS_NZ
#define FP_PDENORM _FPCLASS_PD
#define FP_PINF _FPCLASS_PINF
#define FP_PNORM _FPCLASS_PN
#define FP_PZERO _FPCLASS_PZ
#define FP_QNAN _FPCLASS_QNAN
#define FP_SNAN _FPCLASS_SNAN
#define FP_SUBNORMAL (FP_NORMAL | FP_ZERO)
#define FP_ZERO 0x4000
#define fpclassify(x)
#define HUGE_VAL _HUGE_dll
#define HUGE_VALF __INFF
#define HUGE_VALL __INFL
#define INFINITY HUGE_VALF
#define isfinite(x) ((fpclassify(x) & FP_NAN) == 0)
#define isgreater(x, y)
#define isgreaterequal(x, y)
#define isinf(x) (fpclassify(x) == FP_INFINITE)
#define isless(x, y)
#define islessequal(x, y)
#define islessgreater(x, y)
#define isnan(x)
#define isnormal(x) (fpclassify(x) == FP_NORMAL)
#define isunordered(x, y)
#define M_1_PI 0.31830988618379067154
#define M_2_PI 0.63661977236758134308
#define M_2_SQRTPI 1.12837916709551257390
#define M_E 2.7182818284590452354
#define M_LN10 2.30258509299404568402
#define M_LN2 0.69314718055994530942
#define M_LOG10E 0.43429448190325182765
#define M_LOG2E 1.4426950408889634074
#define M_PI 3.14159265358979323846
#define M_PI_2 1.57079632679489661923
#define M_PI_4 0.78539816339744830962
#define M_SQRT1_2 0.70710678118654752440
#define M_SQRT2 1.41421356237309504880
#define NAN __QNAN
#define OVERFLOW _OVERFLOW
#define PLOSS _PLOSS
#define signbit(x)
#define SING _SING
#define TLOSS _TLOSS
#define UNDERFLOW _UNDERFLOW
Typedefs
typedef long double double_t
typedef long double float_t
Functions
int __cdecl __fp_unordered_compare (long double, long double)
int __cdecl __fpclassify (double)
int __cdecl __fpclassifyf (float)
int __cdecl __fpclassifyl (long double)
int __cdecl __isnan (double)
int __cdecl __isnanf (float)
int __cdecl __isnanl (long double)
int __cdecl __signbit (double)
int __cdecl __signbitf (float)
int __cdecl __signbitl (long double)
_CRTIMP double __cdecl _cabs (struct _complex)
_CRTIMP double __cdecl _chgsign (double)
_CRTIMP double __cdecl _copysign (double, double)
_CRTIMP int __cdecl _finite (double)
_CRTIMP int __cdecl _fpclass (double)
_CRTIMP double __cdecl _hypot (double, double)
_CRTIMP int __cdecl _isnan (double)
_CRTIMP double __cdecl _j0 (double)
_CRTIMP double __cdecl _j1 (double)
_CRTIMP double __cdecl _jn (int, double)
_CRTIMP double __cdecl _logb (double)
_CRTIMP int __cdecl _matherr (struct _exception *)
_CRTIMP double __cdecl _nextafter (double, double)
_CRTIMP double __cdecl _scalb (double, long)
_CRTIMP double __cdecl _y0 (double)
_CRTIMP double __cdecl _y1 (double)
_CRTIMP double __cdecl _yn (int, double)
_CRTIMP double __cdecl acos (double)
float __cdecl acosf (float)
double __cdecl acosh (double)
float __cdecl acoshf (float)
long double __cdecl acoshl (long double)
long double __cdecl acosl (long double)
_CRTIMP double __cdecl asin (double)
float __cdecl asinf (float)
double __cdecl asinh (double)
float __cdecl asinhf (float)
long double __cdecl asinhl (long double)
long double __cdecl asinl (long double)
_CRTIMP double __cdecl atan (double)
_CRTIMP double __cdecl atan2 (double, double)
float __cdecl atan2f (float, float)
long double __cdecl atan2l (long double, long double)
float __cdecl atanf (float)
double __cdecl atanh (double)
float __cdecl atanhf (float)
long double __cdecl atanhl (long double)
long double __cdecl atanl (long double)
double __cdecl cbrt (double)
float __cdecl cbrtf (float)
long double __cdecl cbrtl (long double)
_CRTIMP double __cdecl ceil (double)
float __cdecl ceilf (float)
long double __cdecl ceill (long double)
_CRTIMP double __cdecl chgsign (double)
double __cdecl copysign (double, double)
float __cdecl copysignf (float, float)
long double __cdecl copysignl (long double, long double)
_CRTIMP double __cdecl cos (double)
float __cdecl cosf (float)
_CRTIMP double __cdecl cosh (double)
float __cdecl coshf (float)
long double __cdecl coshl (long double)
long double __cdecl cosl (long double)
double __cdecl erf (double)
double __cdecl erfc (double)
float __cdecl erfcf (float)
long double __cdecl erfcl (long double)
float __cdecl erff (float)
long double __cdecl erfl (long double)
_CRTIMP double __cdecl exp (double)
double __cdecl exp2 (double)
float __cdecl exp2f (float)
long double __cdecl exp2l (long double)
float __cdecl expf (float)
long double __cdecl expl (long double)
double __cdecl expm1 (double)
float __cdecl expm1f (float)
long double __cdecl expm1l (long double)
_CRTIMP double __cdecl fabs (double)
float __cdecl fabsf (float x)
long double __cdecl fabsl (long double x)
double __cdecl fdim (double x, double y)
float __cdecl fdimf (float x, float y)
long double __cdecl fdiml (long double x, long double y)
_CRTIMP int __cdecl finite (double)
_CRTIMP double __cdecl floor (double)
float __cdecl floorf (float)
long double __cdecl floorl (long double)
double __cdecl fma (double, double, double)
float __cdecl fmaf (float, float, float)
long double __cdecl fmal (long double, long double, long double)
double __cdecl fmax (double, double)
float __cdecl fmaxf (float, float)
long double __cdecl fmaxl (long double, long double)
double __cdecl fmin (double, double)
float __cdecl fminf (float, float)
long double __cdecl fminl (long double, long double)
_CRTIMP double __cdecl fmod (double, double)
float __cdecl fmodf (float, float)
long double __cdecl fmodl (long double, long double)
_CRTIMP int __cdecl fpclass (double)
_CRTIMP double __cdecl frexp (double, int *)
float __cdecl frexpf (float, int *)
long double __cdecl frexpl (long double, int *)
double __cdecl hypot (double, double)
float __cdecl hypotf (float, float)
long double __cdecl hypotl (long double, long double)
int __cdecl ilogb (double)
int __cdecl ilogbf (float)
int __cdecl ilogbl (long double)
_CRTIMP double __cdecl j0 (double)
_CRTIMP double __cdecl j1 (double)
_CRTIMP double __cdecl jn (int, double)
_CRTIMP double __cdecl ldexp (double, int)
float __cdecl ldexpf (float, int)
long double __cdecl ldexpl (long double, int)
double __cdecl lgamma (double)
float __cdecl lgammaf (float)
long double __cdecl lgammal (long double)
long long __cdecl llrint (double)
long long __cdecl llrintf (float)
long long __cdecl llrintl (long double)
long long __cdecl llround (double)
long long __cdecl llroundf (float)
long long __cdecl llroundl (long double)
_CRTIMP double __cdecl log (double)
_CRTIMP double __cdecl log10 (double)
float __cdecl log10f (float)
long double __cdecl log10l (long double)
double __cdecl log1p (double)
float __cdecl log1pf (float)
long double __cdecl log1pl (long double)
double __cdecl log2 (double)
float __cdecl log2f (float)
long double __cdecl log2l (long double)
double __cdecl logb (double)
float __cdecl logbf (float)
long double __cdecl logbl (long double)
float __cdecl logf (float)
long double __cdecl logl (long double)
long __cdecl lrint (double)
long __cdecl lrintf (float)
long __cdecl lrintl (long double)
long __cdecl lround (double)
long __cdecl lroundf (float)
long __cdecl lroundl (long double)
_CRTIMP double __cdecl modf (double, double *)
float __cdecl modff (float, float *)
long double __cdecl modfl (long double, long double *)
double __cdecl nan (const char *tagp)
float __cdecl nanf (const char *tagp)
long double __cdecl nanl (const char *tagp)
double __cdecl nearbyint (double)
float __cdecl nearbyintf (float)
long double __cdecl nearbyintl (long double)
double __cdecl nextafter (double, double)
float __cdecl nextafterf (float, float)
long double __cdecl nextafterl (long double, long double)
double __cdecl nexttoward (double, long double)
float __cdecl nexttowardf (float, long double)
long double __cdecl nexttowardl (long double, long double)
_CRTIMP double __cdecl pow (double, double)
float __cdecl powf (float, float)
long double __cdecl powl (long double, long double)
double __cdecl remainder (double, double)
float __cdecl remainderf (float, float)
long double __cdecl remainderl (long double, long double)
double __cdecl remquo (double, double, int *)
float __cdecl remquof (float, float, int *)
long double __cdecl remquol (long double, long double, int *)
double __cdecl rint (double)
float __cdecl rintf (float)
long double __cdecl rintl (long double)
double __cdecl round (double)
float __cdecl roundf (float)
long double __cdecl roundl (long double)
double __cdecl scalbln (double, long)
float __cdecl scalblnf (float, long)
long double __cdecl scalblnl (long double, long)
double __cdecl scalbn (double, int)
float __cdecl scalbnf (float, int)
long double __cdecl scalbnl (long double, int)
_CRTIMP double __cdecl sin (double)
float __cdecl sinf (float)
_CRTIMP double __cdecl sinh (double)
float __cdecl sinhf (float)
long double __cdecl sinhl (long double)
long double __cdecl sinl (long double)
_CRTIMP double __cdecl sqrt (double)
float __cdecl sqrtf (float)
long double __cdecl sqrtl (long double)
_CRTIMP double __cdecl tan (double)
float __cdecl tanf (float)
_CRTIMP double __cdecl tanh (double)
float __cdecl tanhf (float)
long double __cdecl tanhl (long double)
long double __cdecl tanl (long double)
double __cdecl tgamma (double)
float __cdecl tgammaf (float)
long double __cdecl tgammal (long double)
double __cdecl trunc (double)
float __cdecl truncf (float)
long double __cdecl truncl (long double)
_CRTIMP double __cdecl y0 (double)
_CRTIMP double __cdecl y1 (double)
_CRTIMP double __cdecl yn (int, double)
Variables
const float __INFF
const long double __INFL
const double __QNAN
__MINGW_IMPORT double _HUGE_dll
Macro Definition Documentation
__MINGW_FPCLASS_DEFINED
#define __MINGW_FPCLASS_DEFINED 1
Definition at line 72 of file math.h.
_DOMAIN
#define _DOMAIN 1 /* domain error in argument */
Definition at line 26 of file math.h.
_FPCLASS_ND
#define _FPCLASS_ND 0x0010 /* Negative Denormal */
Definition at line 78 of file math.h.
_FPCLASS_NINF
#define _FPCLASS_NINF 0x0004 /* Negative Infinity */
Definition at line 76 of file math.h.
_FPCLASS_NN
#define _FPCLASS_NN 0x0008 /* Negative Normal */
Definition at line 77 of file math.h.
_FPCLASS_NZ
#define _FPCLASS_NZ 0x0020 /* Negative Zero */
Definition at line 79 of file math.h.
_FPCLASS_PD
#define _FPCLASS_PD 0x0080 /* Positive Denormal */
Definition at line 81 of file math.h.
_FPCLASS_PINF
#define _FPCLASS_PINF 0x0200 /* Positive Infinity */
Definition at line 83 of file math.h.
_FPCLASS_PN
#define _FPCLASS_PN 0x0100 /* Positive Normal */
Definition at line 82 of file math.h.
_FPCLASS_PZ
#define _FPCLASS_PZ 0x0040 /* Positive Zero */
Definition at line 80 of file math.h.
_FPCLASS_QNAN
#define _FPCLASS_QNAN 0x0002 /* Quiet "Not a Number" */
Definition at line 75 of file math.h.
_FPCLASS_SNAN
#define _FPCLASS_SNAN 0x0001 /* Signaling "Not a Number" */
Definition at line 74 of file math.h.
_nan
#define _nan () nan("")
Definition at line 815 of file math.h.
_nanf
#define _nanf () nanf("")
Definition at line 816 of file math.h.
_nanl
#define _nanl () nanl("")
Definition at line 817 of file math.h.
_OVERFLOW
#define _OVERFLOW 3 /* range overflow */
Definition at line 28 of file math.h.
_PLOSS
#define _PLOSS 6 /* partial loss of precision */
Definition at line 31 of file math.h.
_SING
#define _SING 2 /* singularity */
Definition at line 27 of file math.h.
_TLOSS
#define _TLOSS 5 /* total loss of precision */
Definition at line 30 of file math.h.
_UNDERFLOW
#define _UNDERFLOW 4 /* range underflow */
Definition at line 29 of file math.h.
DOMAIN
#define DOMAIN _DOMAIN
Definition at line 40 of file math.h.
FP_ILOGB0
#define FP_ILOGB0 ((int)0x80000000)
Definition at line 535 of file math.h.
FP_ILOGBNAN
#define FP_ILOGBNAN ((int)0x80000000)
Definition at line 536 of file math.h.
FP_INFINITE
#define FP_INFINITE (FP_NAN | FP_NORMAL)
Definition at line 341 of file math.h.
FP_NAN
#define FP_NAN 0x0100
Definition at line 339 of file math.h.
FP_NDENORM
#define FP_NDENORM _FPCLASS_ND
Definition at line 277 of file math.h.
FP_NINF
#define FP_NINF _FPCLASS_NINF
Definition at line 275 of file math.h.
FP_NNORM
#define FP_NNORM _FPCLASS_NN
Definition at line 281 of file math.h.
FP_NORMAL
#define FP_NORMAL 0x0400
Definition at line 340 of file math.h.
FP_NZERO
#define FP_NZERO _FPCLASS_NZ
Definition at line 279 of file math.h.
FP_PDENORM
#define FP_PDENORM _FPCLASS_PD
Definition at line 278 of file math.h.
FP_PINF
#define FP_PINF _FPCLASS_PINF
Definition at line 276 of file math.h.
FP_PNORM
#define FP_PNORM _FPCLASS_PN
Definition at line 282 of file math.h.
FP_PZERO
#define FP_PZERO _FPCLASS_PZ
Definition at line 280 of file math.h.
FP_QNAN
#define FP_QNAN _FPCLASS_QNAN
Definition at line 274 of file math.h.
FP_SNAN
#define FP_SNAN _FPCLASS_SNAN
Definition at line 273 of file math.h.
FP_SUBNORMAL
#define FP_SUBNORMAL (FP_NORMAL | FP_ZERO)
Definition at line 343 of file math.h.
FP_ZERO
#define FP_ZERO 0x4000
Definition at line 342 of file math.h.
fpclassify
#define fpclassify (x)
Value:
               (sizeof (x) == sizeof (float) ? __fpclassifyf (x)      \
               : sizeof (x) == sizeof (double) ? __fpclassify (x) \
               : __fpclassifyl (x))
Definition at line 366 of file math.h.
HUGE_VAL
#define HUGE_VAL _HUGE_dll
Definition at line 127 of file math.h.
HUGE_VALF
#define HUGE_VALF __INFF
Definition at line 306 of file math.h.
HUGE_VALL
#define HUGE_VALL __INFL
Definition at line 308 of file math.h.
INFINITY
#define INFINITY HUGE_VALF
Definition at line 309 of file math.h.
isfinite
#define isfinite (x) ((fpclassify(x) & FP_NAN) == 0)
Definition at line 371 of file math.h.
isgreater
#define isgreater (x, y)
Value:
               ((__fp_unordered_compare(x, y) \
               & 0x4500) == 0)
Definition at line 889 of file math.h.
isgreaterequal
#define isgreaterequal (x, y)
Value:
                               ((__fp_unordered_compare (x, y) \
                               & FP_INFINITE) == 0)
Definition at line 893 of file math.h.
isinf
#define isinf (x) (fpclassify(x) == FP_INFINITE)
Definition at line 374 of file math.h.
isless
#define isless (x, y)
Value:
                       ((__fp_unordered_compare (y, x) \
                       & 0x4500) == 0)
Definition at line 891 of file math.h.
islessequal
#define islessequal (x, y)
Value:
                ((__fp_unordered_compare(y, x) \
                & FP_INFINITE) == 0)
Definition at line 895 of file math.h.
islessgreater
#define islessgreater (x, y)
Value:
                  ((__fp_unordered_compare(x, y) \
                  & FP_SUBNORMAL) == 0)
Definition at line 897 of file math.h.
isnan
#define isnan (x)
Value:
          (sizeof (x) == sizeof (float) ? __isnanf (x)  \
          : sizeof (x) == sizeof (double) ? __isnan (x) \
          : __isnanl (x))
Definition at line 411 of file math.h.
isnormal
#define isnormal (x) (fpclassify(x) == FP_NORMAL)
Definition at line 416 of file math.h.
isunordered
#define isunordered (x, y)
Value:
                ((__fp_unordered_compare(x, y) \
                & 0x4500) == 0x4500)
Definition at line 899 of file math.h.
M_1_PI
#define M_1_PI 0.31830988618379067154
Definition at line 61 of file math.h.
M_2_PI
#define M_2_PI 0.63661977236758134308
Definition at line 62 of file math.h.
M_2_SQRTPI
#define M_2_SQRTPI 1.12837916709551257390
Definition at line 63 of file math.h.
M_E
#define M_E 2.7182818284590452354
Definition at line 53 of file math.h.
M_LN10
#define M_LN10 2.30258509299404568402
Definition at line 57 of file math.h.
M_LN2
#define M_LN2 0.69314718055994530942
Definition at line 56 of file math.h.
M_LOG10E
#define M_LOG10E 0.43429448190325182765
Definition at line 55 of file math.h.
M_LOG2E
#define M_LOG2E 1.4426950408889634074
Definition at line 54 of file math.h.
M_PI
#define M_PI 3.14159265358979323846
Definition at line 58 of file math.h.
M_PI_2
#define M_PI_2 1.57079632679489661923
Definition at line 59 of file math.h.
M_PI_4
#define M_PI_4 0.78539816339744830962
Definition at line 60 of file math.h.
M_SQRT1_2
#define M_SQRT1_2 0.70710678118654752440
Definition at line 65 of file math.h.
M_SQRT2
#define M_SQRT2 1.41421356237309504880
Definition at line 64 of file math.h.
NAN
#define NAN __QNAN
Definition at line 311 of file math.h.
OVERFLOW
#define OVERFLOW _OVERFLOW
Definition at line 42 of file math.h.
PLOSS
#define PLOSS _PLOSS
Definition at line 45 of file math.h.
signbit
#define signbit (x)
Value:
            (sizeof (x) == sizeof (float) ? __signbitf (x)  \
            : sizeof (x) == sizeof (double) ? __signbit (x) \
            : __signbitl (x))
Definition at line 442 of file math.h.
SING
#define SING _SING
Definition at line 41 of file math.h.
TLOSS
#define TLOSS _TLOSS
Definition at line 44 of file math.h.
UNDERFLOW
#define UNDERFLOW _UNDERFLOW
Definition at line 43 of file math.h.
Typedef Documentation
double_t
typedef long double double_t
Definition at line 329 of file math.h.
float_t
typedef long double float_t
Definition at line 328 of file math.h.
Function Documentation
__fp_unordered_compare()
__CRT_INLINE int __cdecl __fp_unordered_compare (long double x, long double y)
Definition at line 881 of file math.h.
{
   unsigned short retval;
   __asm__ ("fucom %%st(1);"
        "fnstsw;": "=a" (retval) : "t" (x), "u" (y));
   return retval;
 }
__fpclassify()
int __cdecl __fpclassify (double)
__fpclassifyf()
int __cdecl __fpclassifyf (float)
__fpclassifyl()
__CRT_INLINE int __cdecl __fpclassifyl (long double x)
Definition at line 359 of file math.h.
{
   unsigned short sw;
   __asm__ ("fxam; fstsw %%ax;" : "=a" (sw): "t" (x));
   return sw & (FP_NAN | FP_NORMAL | FP_ZERO );
 }
References FP_NAN, FP_NORMAL, and FP_ZERO.
__isnan()
__CRT_INLINE int __cdecl __isnan (double _x)
Definition at line 383 of file math.h.
 {
   unsigned short sw;
   __asm__ ("fxam;"
        "fstsw %%ax": "=a" (sw) : "t" (_x));
   return (sw & (FP_NAN | FP_NORMAL | FP_INFINITE | FP_ZERO | FP_SUBNORMAL))
     == FP_NAN;
 }
References FP_INFINITE, FP_NAN, FP_NORMAL, FP_SUBNORMAL, and FP_ZERO.
Referenced by _GLIBCXX_VISIBILITY().
__isnanf()
__CRT_INLINE int __cdecl __isnanf (float _x)
Definition at line 392 of file math.h.
 {
   unsigned short sw;
   __asm__ ("fxam;"
         "fstsw %%ax": "=a" (sw) : "t" (_x));
   return (sw & (FP_NAN | FP_NORMAL | FP_INFINITE | FP_ZERO | FP_SUBNORMAL))
     == FP_NAN;
 }
References FP_INFINITE, FP_NAN, FP_NORMAL, FP_SUBNORMAL, and FP_ZERO.
__isnanl()
__CRT_INLINE int __cdecl __isnanl (long double _x)
Definition at line 401 of file math.h.
 {
   unsigned short sw;
   __asm__ ("fxam;"
         "fstsw %%ax": "=a" (sw) : "t" (_x));
   return (sw & (FP_NAN | FP_NORMAL | FP_INFINITE | FP_ZERO | FP_SUBNORMAL))
     == FP_NAN;
 }
References FP_INFINITE, FP_NAN, FP_NORMAL, FP_SUBNORMAL, and FP_ZERO.
__signbit()
__CRT_INLINE int __cdecl __signbit (double x)
Definition at line 423 of file math.h.
{
   unsigned short stw;
   __asm__ ( "fxam; fstsw %%ax;": "=a" (stw) : "t" (x));
   return (stw & 0x0200) != 0;
 }
__signbitf()
__CRT_INLINE int __cdecl __signbitf (float x)
Definition at line 429 of file math.h.
{
   unsigned short stw;
   __asm__ ("fxam; fstsw %%ax;": "=a" (stw) : "t" (x));
   return (stw & 0x0200) != 0;
 }
__signbitl()
__CRT_INLINE int __cdecl __signbitl (long double x)
Definition at line 435 of file math.h.
{
   unsigned short stw;
   __asm__ ("fxam; fstsw %%ax;": "=a" (stw) : "t" (x));
   return (stw & 0x0200) != 0;
 }
_cabs()
_CRTIMP double __cdecl _cabs (struct _complex)
_chgsign()
_CRTIMP double __cdecl _chgsign (double)
_copysign()
_CRTIMP double __cdecl _copysign (double , double)
_finite()
_CRTIMP int __cdecl _finite (double)
_fpclass()
_CRTIMP int __cdecl _fpclass (double)
_hypot()
_CRTIMP double __cdecl _hypot (double , double)
_isnan()
_CRTIMP int __cdecl _isnan (double)
_j0()
_CRTIMP double __cdecl _j0 (double)
_j1()
_CRTIMP double __cdecl _j1 (double)
_jn()
_CRTIMP double __cdecl _jn (int , double)
_logb()
_CRTIMP double __cdecl _logb (double)
_matherr()
_CRTIMP int __cdecl _matherr (struct _exception *)
_nextafter()
_CRTIMP double __cdecl _nextafter (double , double)
_scalb()
_CRTIMP double __cdecl _scalb (double , long)
_y0()
_CRTIMP double __cdecl _y0 (double)
_y1()
_CRTIMP double __cdecl _y1 (double)
_yn()
_CRTIMP double __cdecl _yn (int , double)
acos()
_CRTIMP double __cdecl acos (double)
Referenced by _GLIBCXX_VISIBILITY(), and Q_acos().
acosf()
float __cdecl acosf (float)
acosh()
double __cdecl acosh (double)
acoshf()
float __cdecl acoshf (float)
acoshl()
long double __cdecl acoshl (long double)
acosl()
long double __cdecl acosl (long double)
asin()
_CRTIMP double __cdecl asin (double)
Referenced by _GLIBCXX_VISIBILITY().
asinf()
float __cdecl asinf (float)
asinh()
double __cdecl asinh (double)
asinhf()
float __cdecl asinhf (float)
asinhl()
long double __cdecl asinhl (long double)
asinl()
long double __cdecl asinl (long double)
atan()
_CRTIMP double __cdecl atan (double)
Referenced by _GLIBCXX_VISIBILITY().
atan2()
_CRTIMP double __cdecl atan2 (double , double)
Referenced by _GLIBCXX_VISIBILITY(), AxisToAngles(), CG_CalcFov(), CL_CgameSystemCalls(), CL_UISystemCalls(), QuatToAngles(), SV_GameSystemCalls(), UI_DrawPlayer(), UI_MenuLogo(), UI_MenuScene(), vectoangles(), and vectoyaw().
atan2f()
float __cdecl atan2f (float , float)
atan2l()
long double __cdecl atan2l (long double , long double)
atanf()
float __cdecl atanf (float)
atanh()
double __cdecl atanh (double)
atanhf()
float __cdecl atanhf (float)
atanhl()
long double __cdecl atanhl (long double)
atanl()
long double __cdecl atanl (long double)
cbrt()
double __cdecl cbrt (double)
cbrtf()
float __cdecl cbrtf (float)
cbrtl()
long double __cdecl cbrtl (long double)
ceil()
_CRTIMP double __cdecl ceil (double)
Referenced by CG_weapGfx_NextSym(), CL_CgameSystemCalls(), CL_Frame(), CL_UISystemCalls(), CL_WriteAVIAudioFrame(), DrawSkyBox(), FillCloudBox(), G_RadarUpdateCS(), G_weapPhys_NextSym(), R_LoadLightGrid(), S_GetSoundtime(), and SV_GameSystemCalls().
ceilf()
float __cdecl ceilf (float)
ceill()
long double __cdecl ceill (long double)
chgsign()
_CRTIMP double __cdecl chgsign (double)
copysign()
double __cdecl copysign (double , double)
copysignf()
float __cdecl copysignf (float , float)
copysignl()
long double __cdecl copysignl (long double , long double)
cos()
_CRTIMP double __cdecl cos (double)
Referenced by _GLIBCXX_VISIBILITY(), AnglesToMatrix(), AnglesToQuat(), AngleVectors(), BG_EvaluateTrajectory(), BG_EvaluateTrajectoryDelta(), CG_AddParticleToScene(), CG_Camera(), CG_DrawStatusBarHead(), CG_DrawWeaponSelectQuarterFan(), CL_CgameSystemCalls(), CL_UISystemCalls(), DoRailDiscs(), dradbg(), dradfg(), drfti1(), LocalAngleVector(), ParseShader(), RB_SurfaceSprite(), Matrix::RotateAt(), RotatePointAroundVector(), speex_echo_state_init(), SV_GameSystemCalls(), and Think_Homing().
cosf()
float __cdecl cosf (float)
cosh()
_CRTIMP double __cdecl cosh (double)
Referenced by _GLIBCXX_VISIBILITY(), and coshf().
coshf()
__CRT_INLINE float __cdecl coshf (float x)
Definition at line 478 of file math.h.
   {return (float) cosh (x);}
References cosh().
coshl()
long double __cdecl coshl (long double)
cosl()
long double __cdecl cosl (long double)
erf()
double __cdecl erf (double)
erfc()
double __cdecl erfc (double)
erfcf()
float __cdecl erfcf (float)
erfcl()
long double __cdecl erfcl (long double)
erff()
float __cdecl erff (float)
erfl()
long double __cdecl erfl (long double)
exp()
_CRTIMP double __cdecl exp (double)
Referenced by _GLIBCXX_VISIBILITY(), compute_gain_floor(), expf(), nb_decode(), nb_encode(), R_InitFogTable(), speex_preprocess_ctl(), speex_preprocess_run(), speex_preprocess_state_init(), and speex_std_stereo_request_handler().
exp2()
double __cdecl exp2 (double)
exp2f()
float __cdecl exp2f (float)
exp2l()
long double __cdecl exp2l (long double)
expf()
__CRT_INLINE float __cdecl expf (float x)
Definition at line 510 of file math.h.
   {return (float) exp (x);}
References exp().
expl()
long double __cdecl expl (long double)
expm1()
double __cdecl expm1 (double)
expm1f()
float __cdecl expm1f (float)
expm1l()
long double __cdecl expm1l (long double)
fabs()
_CRTIMP double __cdecl fabs (double)
Referenced by AddSkyPolygon(), BaseWindingForPlane(), BG_TouchJumpPad(), CG_CalcViewValues(), CG_CustomSound(), CG_NextTrack(), CG_SwingAngles(), CL_MouseMove(), CM_DistanceFromLineSquared(), CM_DrawDebugSurface(), CM_PlaneEqual(), CM_PositionTestInPatchCollide(), CM_SnapVector(), CM_Trace(), CM_TraceThroughPatchCollide(), GLimp_CompareModes(), LoadSMD_ParseTriangles(), lpc_to_lsp(), PerpendicularVector(), ProjectRadius(), R_FixSharedVertexLodError_r(), R_MergedHeightPoints(), R_MergedWidthPoints(), R_StitchPatches(), RadiusFromBounds(), sinc(), SP_func_button(), SP_func_door(), SP_func_pendulum(), speex_encode_stereo(), speex_encode_stereo_int(), speex_preprocess_run(), Touch_DoorTriggerSpectator(), UI_SwingAngles(), vbr_analysis(), and VectorCompare().
fabsf()
float __cdecl fabsf (float x)
fabsl()
long double __cdecl fabsl (long double x)
fdim()
double __cdecl fdim (double x, double y)
fdimf()
float __cdecl fdimf (float x, float y)
fdiml()
long double __cdecl fdiml (long double x, long double y)
finite()
_CRTIMP int __cdecl finite (double)
floor()
_CRTIMP double __cdecl floor (double)
Referenced by CG_AddEarthquake(), CG_AddParticleToScene(), CG_TessCount(), CL_CgameSystemCalls(), CL_UISystemCalls(), compute_func(), DrawSkyBox(), FillCloudBox(), filterbank_new(), HSVtoRGB(), hypergeom_gain(), nb_encode(), Q_rint(), R_LoadLightGrid(), R_NoiseGet4f(), R_SetupEntityLightingGrid(), RB_CalcScrollTexCoords(), sb_encode(), sb_encoder_ctl(), speex_decode_int(), speex_encode_stereo(), speex_encode_stereo_int(), speex_preprocess_ctl(), and SV_GameSystemCalls().
floorf()
float __cdecl floorf (float)
floorl()
long double __cdecl floorl (long double)
fma()
double __cdecl fma (double , double , double)
fmaf()
float __cdecl fmaf (float , float , float)
fmal()
long double __cdecl fmal (long double , long double , long double)
fmax()
double __cdecl fmax (double , double)
fmaxf()
float __cdecl fmaxf (float , float)
fmaxl()
long double __cdecl fmaxl (long double , long double)
fmin()
double __cdecl fmin (double , double)
fminf()
float __cdecl fminf (float , float)
fminl()
long double __cdecl fminl (long double , long double)
fmod()
_CRTIMP double __cdecl fmod (double , double)
fmodf()
float __cdecl fmodf (float , float)
fmodl()
long double __cdecl fmodl (long double , long double)
fpclass()
_CRTIMP int __cdecl fpclass (double)
frexp()
_CRTIMP double __cdecl frexp (double , int *)
Referenced by frexpf().
frexpf()
__CRT_INLINE float __cdecl frexpf (float x, int * expn)
Definition at line 529 of file math.h.
   {return (float) frexp (x, expn);}
References frexp().
frexpl()
long double __cdecl frexpl (long double , int *)
hypot()
double __cdecl hypot (double , double)
Referenced by hypotf().
hypotf()
__CRT_INLINE float __cdecl hypotf (float x, float y)
Definition at line 629 of file math.h.
   { return (float) hypot (x, y);}
References hypot().
hypotl()
long double __cdecl hypotl (long double , long double)
ilogb()
int __cdecl ilogb (double)
ilogbf()
int __cdecl ilogbf (float)
ilogbl()
int __cdecl ilogbl (long double)
j0()
_CRTIMP double __cdecl j0 (double)
j1()
_CRTIMP double __cdecl j1 (double)
jn()
_CRTIMP double __cdecl jn (int , double)
ldexp()
_CRTIMP double __cdecl ldexp (double , int)
Referenced by ldexpf().
ldexpf()
__CRT_INLINE float __cdecl ldexpf (float x, int expn)
Definition at line 544 of file math.h.
   {return (float) ldexp (x, expn);}
References ldexp().
ldexpl()
long double __cdecl ldexpl (long double , int)
lgamma()
double __cdecl lgamma (double)
lgammaf()
float __cdecl lgammaf (float)
lgammal()
long double __cdecl lgammal (long double)
llrint()
__CRT_INLINE long long __cdecl llrint (double x)
Definition at line 743 of file math.h.
 {
   long long retval;
   __asm__ __volatile__
     ("fistpll %0"  : "=m" (retval) : "t" (x) : "st");
   return retval;
 }
llrintf()
__CRT_INLINE long long __cdecl llrintf (float x)
Definition at line 751 of file math.h.
 {
   long long retval;
   __asm__ __volatile__
     ("fistpll %0"  : "=m" (retval) : "t" (x) : "st");
   return retval;
 }
llrintl()
__CRT_INLINE long long __cdecl llrintl (long double x)
Definition at line 759 of file math.h.
 {
   long long retval;
   __asm__ __volatile__
     ("fistpll %0"  : "=m" (retval) : "t" (x) : "st");
   return retval;
 }
llround()
long long __cdecl llround (double)
llroundf()
long long __cdecl llroundf (float)
llroundl()
long long __cdecl llroundl (long double)
log()
_CRTIMP double __cdecl log (double)
Referenced by _GLIBCXX_VISIBILITY(), nb_decoder_ctl(), nb_encode(), sb_encode(), speex_encode_stereo(), speex_encode_stereo_int(), speex_preprocess_ctl(), vbr_analysis(), and vbr_init().
log10()
_CRTIMP double __cdecl log10 (double)
Referenced by _GLIBCXX_VISIBILITY(), and main().
log10f()
float __cdecl log10f (float)
log10l()
long double __cdecl log10l (long double)
log1p()
double __cdecl log1p (double)
log1pf()
float __cdecl log1pf (float)
log1pl()
long double __cdecl log1pl (long double)
log2()
double __cdecl log2 (double)
log2f()
float __cdecl log2f (float)
log2l()
long double __cdecl log2l (long double)
logb()
__CRT_INLINE double __cdecl logb (double x)
Definition at line 576 of file math.h.
 {
   double res;
   __asm__ ("fxtract\n\t"
        "fstp    %%st" : "=t" (res) : "0" (x));
   return res;
 }
logbf()
__CRT_INLINE float __cdecl logbf (float x)
Definition at line 584 of file math.h.
 {
   float res;
   __asm__ ("fxtract\n\t"
        "fstp    %%st" : "=t" (res) : "0" (x));
   return res;
 }
logbl()
__CRT_INLINE long double __cdecl logbl (long double x)
Definition at line 592 of file math.h.
 {
   long double res;
   __asm__ ("fxtract\n\t"
        "fstp    %%st" : "=t" (res) : "0" (x));
   return res;
 }
logf()
float __cdecl logf (float)
logl()
long double __cdecl logl (long double)
lrint()
__CRT_INLINE long __cdecl lrint (double x)
Definition at line 719 of file math.h.
 {
   long retval;
   __asm__ __volatile__
     ("fistpl %0"  : "=m" (retval) : "t" (x) : "st");
   return retval;
 }
lrintf()
__CRT_INLINE long __cdecl lrintf (float x)
Definition at line 727 of file math.h.
 {
   long retval;
   __asm__ __volatile__
     ("fistpl %0"  : "=m" (retval) : "t" (x) : "st");
   return retval;
 }
lrintl()
__CRT_INLINE long __cdecl lrintl (long double x)
Definition at line 735 of file math.h.
 {
   long retval;
   __asm__ __volatile__
     ("fistpl %0"  : "=m" (retval) : "t" (x) : "st");
   return retval;
 }
lround()
long __cdecl lround (double)
lroundf()
long __cdecl lroundf (float)
lroundl()
long __cdecl lroundl (long double)
modf()
_CRTIMP double __cdecl modf (double , double *)
modff()
float __cdecl modff (float , float *)
modfl()
long double __cdecl modfl (long double , long double *)
nan()
double __cdecl nan (const char * tagp)
nanf()
float __cdecl nanf (const char * tagp)
nanl()
long double __cdecl nanl (const char * tagp)
nearbyint()
double __cdecl nearbyint (double)
nearbyintf()
float __cdecl nearbyintf (float)
nearbyintl()
long double __cdecl nearbyintl (long double)
nextafter()
double __cdecl nextafter (double , double)
nextafterf()
float __cdecl nextafterf (float , float)
nextafterl()
long double __cdecl nextafterl (long double , long double)
nexttoward()
double __cdecl nexttoward (double , long double)
nexttowardf()
float __cdecl nexttowardf (float , long double)
nexttowardl()
long double __cdecl nexttowardl (long double , long double)
pow()
_CRTIMP double __cdecl pow (double , double)
Referenced by _GLIBCXX_VISIBILITY(), powf(), R_InitFogTable(), R_SetColorMappings(), speex_compute_agc(), speex_preprocess_ctl(), vbr_analysis(), and vbr_init().
powf()
__CRT_INLINE float __cdecl powf (float x, float y)
Definition at line 637 of file math.h.
   {return (float) pow (x, y);}
References pow().
Referenced by CL_MouseMove().
powl()
long double __cdecl powl (long double , long double)
remainder()
double __cdecl remainder (double , double)
Referenced by FS_Seek().
remainderf()
float __cdecl remainderf (float , float)
remainderl()
long double __cdecl remainderl (long double , long double)
remquo()
double __cdecl remquo (double , double , int *)
remquof()
float __cdecl remquof (float , float , int *)
remquol()
long double __cdecl remquol (long double , long double , int *)
rint()
__CRT_INLINE double __cdecl rint (double x)
Definition at line 698 of file math.h.
 {
   double retval;
   __asm__ ("frndint;": "=t" (retval) : "0" (x));
   return retval;
 }
rintf()
__CRT_INLINE float __cdecl rintf (float x)
Definition at line 705 of file math.h.
 {
   float retval;
   __asm__ ("frndint;" : "=t" (retval) : "0" (x) );
   return retval;
 }
rintl()
__CRT_INLINE long double __cdecl rintl (long double x)
Definition at line 712 of file math.h.
 {
   long double retval;
   __asm__ ("frndint;" : "=t" (retval) : "0" (x) );
   return retval;
 }
round()
double __cdecl round (double)
roundf()
float __cdecl roundf (float)
roundl()
long double __cdecl roundl (long double)
scalbln()
double __cdecl scalbln (double , long)
scalblnf()
float __cdecl scalblnf (float , long)
scalblnl()
long double __cdecl scalblnl (long double , long)
scalbn()
double __cdecl scalbn (double , int)
scalbnf()
float __cdecl scalbnf (float , int)
scalbnl()
long double __cdecl scalbnl (long double , int)
sin()
_CRTIMP double __cdecl sin (double)
Referenced by _GLIBCXX_VISIBILITY(), AnglesToMatrix(), AnglesToQuat(), AngleVectors(), BG_EvaluateTrajectory(), Bitmap_Draw(), CG_AddParticleToScene(), CG_AddScorePlum(), CG_AddZEQExplosion(), CG_CalcFov(), CG_CalculateWeaponPosition(), CG_CalcViewValues(), CG_Camera(), CG_DrawActive(), CG_DrawWeaponSelectQuarterFan(), CL_CgameSystemCalls(), CL_UISystemCalls(), DoRailDiscs(), dradbg(), dradfg(), drfti1(), LocalAngleVector(), ParseShader(), R_GetPortalOrientations(), R_Init(), RB_SurfaceSprite(), Matrix::RotateAt(), RotatePointAroundVector(), S_TransferPaintBuffer(), sinc(), SV_GameSystemCalls(), UI_DrawProportionalString(), UI_LegsSequencing(), UI_MenuLogo(), and UI_MenuScene().
sinf()
float __cdecl sinf (float)
sinh()
_CRTIMP double __cdecl sinh (double)
Referenced by _GLIBCXX_VISIBILITY(), and sinhf().
sinhf()
__CRT_INLINE float __cdecl sinhf (float x)
Definition at line 471 of file math.h.
   {return (float) sinh (x);}
References sinh().
sinhl()
long double __cdecl sinhl (long double)
sinl()
long double __cdecl sinl (long double)
sqrt()
_CRTIMP double __cdecl sqrt (double)
Referenced by _GLIBCXX_VISIBILITY(), AimAtTarget(), Autosprite2Deform(), AxisToAngles(), CG_AddParticleToScene(), CG_BubblesTrail(), CG_CalcViewValues(), CG_InnerAuraSpikes(), CG_Player(), CG_PlayerSplash(), CL_CgameSystemCalls(), CL_DemoFrameDurationSDev(), CL_MouseMove(), CL_UISystemCalls(), compute_gain_floor(), compute_rms(), Distance_2D(), Fire_UserWeapon(), hypergeom_gain(), PM_CmdScale(), PM_Footsteps(), PM_Land(), PSys_ApplyFalloff(), Q_hypot(), R_InitSkyTexCoords(), R_SetFarClip(), R_SetupFrustum(), R_SubdividePatchToGrid(), RaySphereIntersections(), RB_RenderFlare(), SP_func_pendulum(), speex_compute_agc(), SV_GameSystemCalls(), vectoangles(), VectorLength(), VectorNormalize(), and VectorNormalize2().
sqrtf()
float __cdecl sqrtf (float)
sqrtl()
long double __cdecl sqrtl (long double)
tan()
_CRTIMP double __cdecl tan (double)
Referenced by _GLIBCXX_VISIBILITY(), CG_CalcFov(), R_SetupProjection(), UI_DrawPlayer(), UI_MenuLogo(), and UI_MenuScene().
tanf()
float __cdecl tanf (float)
tanh()
_CRTIMP double __cdecl tanh (double)
Referenced by _GLIBCXX_VISIBILITY(), and tanhf().
tanhf()
__CRT_INLINE float __cdecl tanhf (float x)
Definition at line 485 of file math.h.
   {return (float) tanh (x);}
References tanh().
tanhl()
long double __cdecl tanhl (long double)
tanl()
long double __cdecl tanl (long double)
tgamma()
double __cdecl tgamma (double)
tgammaf()
float __cdecl tgammaf (float)
tgammal()
long double __cdecl tgammal (long double)
trunc()
double __cdecl trunc (double)
Referenced by _GLIBCXX_VISIBILITY(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_WriteDeltaEntity(), and MSG_WriteDeltaPlayerstate().
truncf()
float __cdecl truncf (float)
truncl()
long double __cdecl truncl (long double)
y0()
_CRTIMP double __cdecl y0 (double)
Referenced by decodeCodeBook(), pitch_xcorr(), qmf_synth(), and VectorArrayNormalize().
y1()
_CRTIMP double __cdecl y1 (double)
Referenced by GraphicsPath::AddBezier(), GraphicsPath::AddLine(), compute_impulse_response(), decodeCodeBook(), Graphics::DrawBezier(), Graphics::DrawLine(), pitch_xcorr(), qmf_decomp(), qmf_synth(), and VectorArrayNormalize().
yn()
_CRTIMP double __cdecl yn (int , double)
Variable Documentation
__INFF
const float __INFF
__INFL
const long double __INFL
__QNAN
const double __QNAN
_HUGE_dll
__MINGW_IMPORT double _HUGE_dll
Definition at line 126 of file math.h.