ZEQ2-Lite: Source/Engine/renderer/tr_shade.c File Reference
tr_shade.c File Reference
#include "tr_local.h"
Functions
static void ComputeColors (shaderStage_t *pStage)
static void ComputeTexCoords (shaderStage_t *pStage)
static void DrawBBoxes (shaderCommands_t *input)
static void DrawMultitextured (shaderCommands_t *input, int stage)
static void DrawNormals (shaderCommands_t *input)
static void DrawTris (shaderCommands_t *input)
static void ProjectDlightTexture (void)
static void ProjectDlightTexture_scalar (void)
static void APIENTRY R_ArrayElementDiscrete (GLint index)
static void R_BindAnimatedImage (textureBundle_t *bundle)
static void R_DrawElements (int numIndexes, const glIndex_t *indexes)
static void R_DrawStripElements (int numIndexes, const glIndex_t *indexes, void(APIENTRY *element)(GLint))
void RB_BeginSurface (shader_t *shader, int fogNum)
void RB_EndSurface (void)
static void RB_FogPass (void)
static void RB_GLSL_IterateStagesGeneric (shaderCommands_t *input)
void RB_GLSL_StageIteratorGeneric (void)
void RB_GLSL_StageIteratorLightmappedMultitexture (void)
void RB_GLSL_StageIteratorVertexLitTexture (void)
static void RB_HazePass (void)
static void RB_IterateStagesGeneric (shaderCommands_t *input)
static void RB_OutlinesPass (void)
void RB_StageIteratorGeneric (void)
void RB_StageIteratorLightmappedMultitexture (void)
void RB_StageIteratorVertexLitTexture (void)
Variables
static int c_begins
static int c_vertexes
static qboolean setArraysOnce
shaderCommands_t tess
Function Documentation
ComputeColors()
static void ComputeColors (shaderStage_t * pStage) static
Definition at line 937 of file tr_shade.c.
 {
     int     i;
     //
     // rgbGen
     //
     switch ( pStage->rgbGen )
     {
         case CGEN_IDENTITY:
             Com_Memset( tess.svars.colors, 0xff, tess.numVertexes * 4 );
             break;
         default:
         case CGEN_IDENTITY_LIGHTING:
             Com_Memset( tess.svars.colors, tr.identityLightByte, tess.numVertexes * 4 );
             break;
         case CGEN_LIGHTING_DIFFUSE:
             RB_CalcDiffuseColor( ( unsigned char * ) tess.svars.colors );
             break;
         case CGEN_LIGHTING_UNIFORM:
             RB_CalcUniformColor( ( unsigned char * ) tess.svars.colors );
             break;
         case CGEN_LIGHTING_DYNAMIC:
             RB_CalcDynamicColor( ( unsigned char * ) tess.svars.colors );
             break;
         case CGEN_EXACT_VERTEX:
             Com_Memcpy( tess.svars.colors, tess.vertexColors, tess.numVertexes * sizeof( tess.vertexColors[0] ) );
             break;
         case CGEN_CONST:
             for ( i = 0; i < tess.numVertexes; i++ ) {
                 *(int *)tess.svars.colors[i] = *(int *)pStage->constantColor;
             }
             break;
         case CGEN_VERTEX:
             if ( tr.identityLight == 1 )
             {
                 Com_Memcpy( tess.svars.colors, tess.vertexColors, tess.numVertexes * sizeof( tess.vertexColors[0] ) );
             }
             else
             {
                 for ( i = 0; i < tess.numVertexes; i++ )
                 {
                     tess.svars.colors[i][0] = tess.vertexColors[i][0] * tr.identityLight;
                     tess.svars.colors[i][1] = tess.vertexColors[i][1] * tr.identityLight;
                     tess.svars.colors[i][2] = tess.vertexColors[i][2] * tr.identityLight;
                     tess.svars.colors[i][3] = tess.vertexColors[i][3];
                 }
             }
             break;
         case CGEN_ONE_MINUS_VERTEX:
             if ( tr.identityLight == 1 )
             {
                 for ( i = 0; i < tess.numVertexes; i++ )
                 {
                     tess.svars.colors[i][0] = 255 - tess.vertexColors[i][0];
                     tess.svars.colors[i][1] = 255 - tess.vertexColors[i][1];
                     tess.svars.colors[i][2] = 255 - tess.vertexColors[i][2];
                 }
             }
             else
             {
                 for ( i = 0; i < tess.numVertexes; i++ )
                 {
                     tess.svars.colors[i][0] = ( 255 - tess.vertexColors[i][0] ) * tr.identityLight;
                     tess.svars.colors[i][1] = ( 255 - tess.vertexColors[i][1] ) * tr.identityLight;
                     tess.svars.colors[i][2] = ( 255 - tess.vertexColors[i][2] ) * tr.identityLight;
                 }
             }
             break;
         case CGEN_FOG:
             {
                 fog_t       *fog;
                 fog = tr.world->fogs + tess.fogNum;
                 for ( i = 0; i < tess.numVertexes; i++ ) {
                     * ( int * )&tess.svars.colors[i] = fog->colorInt;
                 }
             }
             break;
         case CGEN_WAVEFORM:
             RB_CalcWaveColor( &pStage->rgbWave, ( unsigned char * ) tess.svars.colors );
             break;
         case CGEN_ENTITY:
             RB_CalcColorFromEntity( ( unsigned char * ) tess.svars.colors );
             break;
         case CGEN_ONE_MINUS_ENTITY:
             RB_CalcColorFromOneMinusEntity( ( unsigned char * ) tess.svars.colors );
             break;
     }
     //
     // alphaGen
     //
     switch ( pStage->alphaGen )
     {
     case AGEN_SKIP:
         break;
     case AGEN_IDENTITY:
         if ( pStage->rgbGen != CGEN_IDENTITY ) {
             if ( ( pStage->rgbGen == CGEN_VERTEX && tr.identityLight != 1 ) ||
                  pStage->rgbGen != CGEN_VERTEX ) {
                 for ( i = 0; i < tess.numVertexes; i++ ) {
                     tess.svars.colors[i][3] = 0xff;
                 }
             }
         }
         break;
     case AGEN_CONST:
         if ( pStage->rgbGen != CGEN_CONST ) {
             for ( i = 0; i < tess.numVertexes; i++ ) {
                 tess.svars.colors[i][3] = pStage->constantColor[3];
             }
         }
         break;
     case AGEN_WAVEFORM:
         RB_CalcWaveAlpha( &pStage->alphaWave, ( unsigned char * ) tess.svars.colors );
         break;
     case AGEN_LIGHTING_SPECULAR:
         RB_CalcSpecularAlpha( ( unsigned char * ) tess.svars.colors );
         break;
     case AGEN_ENTITY:
         RB_CalcAlphaFromEntity( ( unsigned char * ) tess.svars.colors );
         break;
     case AGEN_ONE_MINUS_ENTITY:
         RB_CalcAlphaFromOneMinusEntity( ( unsigned char * ) tess.svars.colors );
         break;
     case AGEN_VERTEX:
         if ( pStage->rgbGen != CGEN_VERTEX ) {
             for ( i = 0; i < tess.numVertexes; i++ ) {
                 tess.svars.colors[i][3] = tess.vertexColors[i][3];
             }
         }
         break;
     case AGEN_ONE_MINUS_VERTEX:
         for ( i = 0; i < tess.numVertexes; i++ )
         {
             tess.svars.colors[i][3] = 255 - tess.vertexColors[i][3];
         }
         break;
     case AGEN_PORTAL:
         {
             unsigned char alpha;
             for ( i = 0; i < tess.numVertexes; i++ )
             {
                 float len;
                 vec3_t v;
                 VectorSubtract( tess.xyz[i], backEnd.viewParms.or.origin, v );
                 len = VectorLength( v );
                 len /= tess.shader->portalRange;
                 if ( len < 0 )
                 {
                     alpha = 0;
                 }
                 else if ( len > 1 )
                 {
                     alpha = 0xff;
                 }
                 else
                 {
                     alpha = len * 0xff;
                 }
                 tess.svars.colors[i][3] = alpha;
             }
         }
         break;
     }
     //
     // fog adjustment for colors to fade out as fog increases
     //
     if ( tess.fogNum )
     {
         switch ( pStage->adjustColorsForFog )
         {
         case ACFF_MODULATE_RGB:
             RB_CalcModulateColorsByFog( ( unsigned char * ) tess.svars.colors );
             break;
         case ACFF_MODULATE_ALPHA:
             RB_CalcModulateAlphasByFog( ( unsigned char * ) tess.svars.colors );
             break;
         case ACFF_MODULATE_RGBA:
             RB_CalcModulateRGBAsByFog( ( unsigned char * ) tess.svars.colors );
             break;
         case ACFF_NONE:
             break;
         }
     }
     // if in greyscale rendering mode turn all color values into greyscale.
     if(r_greyscale->integer)
     {
         int scale;
         for(i = 0; i < tess.numVertexes; i++)
         {
             scale = LUMA(tess.svars.colors[i][0], tess.svars.colors[i][1], tess.svars.colors[i][2]);
             tess.svars.colors[i][0] = tess.svars.colors[i][1] = tess.svars.colors[i][2] = scale;
         }
     }
     else if(r_greyscale->value)
     {
         float scale;
         for(i = 0; i < tess.numVertexes; i++)
         {
             scale = LUMA(tess.svars.colors[i][0], tess.svars.colors[i][1], tess.svars.colors[i][2]);
             tess.svars.colors[i][0] = LERP(tess.svars.colors[i][0], scale, r_greyscale->value);
             tess.svars.colors[i][1] = LERP(tess.svars.colors[i][1], scale, r_greyscale->value);
             tess.svars.colors[i][2] = LERP(tess.svars.colors[i][2], scale, r_greyscale->value);
         }
     }
 }
References ACFF_MODULATE_ALPHA, ACFF_MODULATE_RGB, ACFF_MODULATE_RGBA, ACFF_NONE, shaderStage_t::adjustColorsForFog, AGEN_CONST, AGEN_ENTITY, AGEN_IDENTITY, AGEN_LIGHTING_SPECULAR, AGEN_ONE_MINUS_ENTITY, AGEN_ONE_MINUS_VERTEX, AGEN_PORTAL, AGEN_SKIP, AGEN_VERTEX, AGEN_WAVEFORM, shaderStage_t::alphaGen, shaderStage_t::alphaWave, backEnd, CGEN_CONST, CGEN_ENTITY, CGEN_EXACT_VERTEX, CGEN_FOG, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_LIGHTING_DYNAMIC, CGEN_LIGHTING_UNIFORM, CGEN_ONE_MINUS_ENTITY, CGEN_ONE_MINUS_VERTEX, CGEN_VERTEX, CGEN_WAVEFORM, fog_t::colorInt, Com_Memcpy, Com_Memset, shaderStage_t::constantColor, world_t::fogs, trGlobals_t::identityLight, trGlobals_t::identityLightByte, LERP, LUMA, viewParms_t::or, orientationr_t::origin, r_greyscale, RB_CalcAlphaFromEntity(), RB_CalcAlphaFromOneMinusEntity(), RB_CalcColorFromEntity(), RB_CalcColorFromOneMinusEntity(), RB_CalcDiffuseColor(), RB_CalcDynamicColor(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), RB_CalcModulateRGBAsByFog(), RB_CalcSpecularAlpha(), RB_CalcUniformColor(), RB_CalcWaveAlpha(), RB_CalcWaveColor(), shaderStage_t::rgbGen, shaderStage_t::rgbWave, tess, tr, VectorLength(), VectorSubtract, backEndState_t::viewParms, and trGlobals_t::world.
Referenced by RB_IterateStagesGeneric().
ComputeTexCoords()
static void ComputeTexCoords (shaderStage_t * pStage) static
Definition at line 1160 of file tr_shade.c.
{
     int     i;
     int     b;
     for ( b = 0; b < NUM_TEXTURE_BUNDLES; b++ ) {
         int tm;
         //
         // generate the texture coordinates
         //
         switch ( pStage->bundle[b].tcGen )
         {
         case TCGEN_IDENTITY:
             Com_Memset( tess.svars.texcoords[b], 0, sizeof( float ) * 2 * tess.numVertexes );
             break;
         case TCGEN_TEXTURE:
             for ( i = 0 ; i < tess.numVertexes ; i++ ) {
                 tess.svars.texcoords[b][i][0] = tess.texCoords[i][0][0];
                 tess.svars.texcoords[b][i][1] = tess.texCoords[i][0][1];
             }
             break;
         case TCGEN_LIGHTMAP:
             for ( i = 0 ; i < tess.numVertexes ; i++ ) {
                 tess.svars.texcoords[b][i][0] = tess.texCoords[i][1][0];
                 tess.svars.texcoords[b][i][1] = tess.texCoords[i][1][1];
             }
             break;
         case TCGEN_VECTOR:
             for ( i = 0 ; i < tess.numVertexes ; i++ ) {
                 tess.svars.texcoords[b][i][0] = DotProduct( tess.xyz[i], pStage->bundle[b].tcGenVectors[0] );
                 tess.svars.texcoords[b][i][1] = DotProduct( tess.xyz[i], pStage->bundle[b].tcGenVectors[1] );
             }
             break;
         case TCGEN_FOG:
             RB_CalcFogTexCoords( ( float * ) tess.svars.texcoords[b] );
             break;
         case TCGEN_ENVIRONMENT_MAPPED:
             RB_CalcEnvironmentTexCoords( ( float * ) tess.svars.texcoords[b] );
             break;
         case TCGEN_ENVIRONMENT_CELSHADE_MAPPED:
             RB_CalcEnvironmentCelShadeTexCoords( ( float * ) tess.svars.texcoords[b] );
             break;
         case TCGEN_BAD:
             return;
         }
         //
         // alter texture coordinates
         //
         for ( tm = 0; tm < pStage->bundle[b].numTexMods ; tm++ ) {
             switch ( pStage->bundle[b].texMods[tm].type )
             {
             case TMOD_NONE:
                 tm = TR_MAX_TEXMODS;        // break out of for loop
                 break;
             case TMOD_TURBULENT:
                 RB_CalcTurbulentTexCoords( &pStage->bundle[b].texMods[tm].wave,
                                          ( float * ) tess.svars.texcoords[b] );
                 break;
             case TMOD_ENTITY_TRANSLATE:
                 RB_CalcScrollTexCoords( backEnd.currentEntity->e.shaderTexCoord,
                                      ( float * ) tess.svars.texcoords[b] );
                 break;
             case TMOD_SCROLL:
                 RB_CalcScrollTexCoords( pStage->bundle[b].texMods[tm].scroll,
                                          ( float * ) tess.svars.texcoords[b] );
                 break;
             case TMOD_SCALE:
                 RB_CalcScaleTexCoords( pStage->bundle[b].texMods[tm].scale,
                                      ( float * ) tess.svars.texcoords[b] );
                 break;
             case TMOD_STRETCH:
                 RB_CalcStretchTexCoords( &pStage->bundle[b].texMods[tm].wave,
                                        ( float * ) tess.svars.texcoords[b] );
                 break;
             case TMOD_TRANSFORM:
                 RB_CalcTransformTexCoords( &pStage->bundle[b].texMods[tm],
                                          ( float * ) tess.svars.texcoords[b] );
                 break;
             case TMOD_ROTATE:
                 RB_CalcRotateTexCoords( pStage->bundle[b].texMods[tm].rotateSpeed,
                                         ( float * ) tess.svars.texcoords[b] );
                 break;
             default:
                 ri.Error( ERR_DROP, "ERROR: unknown texmod '%d' in shader '%s'", pStage->bundle[b].texMods[tm].type, tess.shader->name );
                 break;
             }
         }
     }
 }
References backEnd, shaderStage_t::bundle, Com_Memset, backEndState_t::currentEntity, DotProduct, trRefEntity_t::e, ERR_DROP, NUM_TEXTURE_BUNDLES, textureBundle_t::numTexMods, RB_CalcEnvironmentCelShadeTexCoords(), RB_CalcEnvironmentTexCoords(), RB_CalcFogTexCoords(), RB_CalcRotateTexCoords(), RB_CalcScaleTexCoords(), RB_CalcScrollTexCoords(), RB_CalcStretchTexCoords(), RB_CalcTransformTexCoords(), RB_CalcTurbulentTexCoords(), ri, texModInfo_t::rotateSpeed, texModInfo_t::scale, texModInfo_t::scroll, refEntity_t::shaderTexCoord, textureBundle_t::tcGen, TCGEN_BAD, TCGEN_ENVIRONMENT_CELSHADE_MAPPED, TCGEN_ENVIRONMENT_MAPPED, TCGEN_FOG, TCGEN_IDENTITY, TCGEN_LIGHTMAP, TCGEN_TEXTURE, TCGEN_VECTOR, textureBundle_t::tcGenVectors, tess, textureBundle_t::texMods, TMOD_ENTITY_TRANSLATE, TMOD_NONE, TMOD_ROTATE, TMOD_SCALE, TMOD_SCROLL, TMOD_STRETCH, TMOD_TRANSFORM, TMOD_TURBULENT, TR_MAX_TEXMODS, texModInfo_t::type, and texModInfo_t::wave.
Referenced by RB_IterateStagesGeneric().
DrawBBoxes()
static void DrawBBoxes (shaderCommands_t * input) static
Definition at line 315 of file tr_shade.c.
{
     GL_Bind( tr.whiteImage );
 //  qglColor3f (1,1,1);
     qglColor4f ( 0, 0, 0, 0.5f );
     GL_State( GLS_POLYMODE_LINE | GLS_DEPTHMASK_TRUE );
     qglDepthRange( 0, 0 );
     qglDisableClientState (GL_COLOR_ARRAY);
     qglDisableClientState (GL_TEXTURE_COORD_ARRAY);
     qglVertexPointer (3, GL_FLOAT, 16, input->xyz); // padded for SIMD
     if (qglLockArraysEXT) {
         qglLockArraysEXT(0, input->numVertexes);
         GLimp_LogComment( "glLockArraysEXT\n" );
     }
     R_DrawElements( input->numIndexes, input->indexes );
     if (qglUnlockArraysEXT) {
         qglUnlockArraysEXT();
         GLimp_LogComment( "glUnlockArraysEXT\n" );
     }
     qglDepthRange( 0, 1 );
 }
References GL_Bind(), GL_State(), GLimp_LogComment(), GLS_DEPTHMASK_TRUE, GLS_POLYMODE_LINE, qglColor4f, qglDepthRange, qglDisableClientState, qglLockArraysEXT, qglUnlockArraysEXT, qglVertexPointer, R_DrawElements(), tr, and trGlobals_t::whiteImage.
Referenced by RB_EndSurface().
DrawMultitextured()
static void DrawMultitextured (shaderCommands_t * input, int stage) static
Definition at line 382 of file tr_shade.c.
{
     shaderStage_t   *pStage;
     pStage = tess.xstages[stage];
     GL_State( pStage->stateBits );
     // this is an ugly hack to work around a GeForce driver
     // bug with multitexture and clip planes
     if ( backEnd.viewParms.isPortal ) {
         qglPolygonMode( GL_FRONT_AND_BACK, GL_FILL );
     }
     //
     // base
     //
     GL_SelectTexture( 0 );
     qglTexCoordPointer( 2, GL_FLOAT, 0, input->svars.texcoords[0] );
     R_BindAnimatedImage( &pStage->bundle[0] );
     //
     // lightmap/secondary pass
     //
     GL_SelectTexture( 1 );
     qglEnable( GL_TEXTURE_2D );
     qglEnableClientState( GL_TEXTURE_COORD_ARRAY );
     if ( r_lightmap->integer ) {
         GL_TexEnv( GL_REPLACE );
     } else {
         GL_TexEnv( tess.shader->multitextureEnv );
     }
     qglTexCoordPointer( 2, GL_FLOAT, 0, input->svars.texcoords[1] );
     R_BindAnimatedImage( &pStage->bundle[1] );
     R_DrawElements( input->numIndexes, input->indexes );
     //
     // disable texturing on TEXTURE1, then select TEXTURE0
     //
     //qglDisableClientState( GL_TEXTURE_COORD_ARRAY );
     qglDisable( GL_TEXTURE_2D );
     GL_SelectTexture( 0 );
 }
References backEnd, shaderStage_t::bundle, GL_SelectTexture(), GL_State(), GL_TexEnv(), viewParms_t::isPortal, qglDisable, qglEnable, qglEnableClientState, qglPolygonMode, qglTexCoordPointer, R_BindAnimatedImage(), R_DrawElements(), r_lightmap, shaderStage_t::stateBits, tess, and backEndState_t::viewParms.
Referenced by RB_IterateStagesGeneric().
DrawNormals()
static void DrawNormals (shaderCommands_t * input) static
Definition at line 288 of file tr_shade.c.
{
     int     i;
     vec3_t  temp;
     GL_Bind( tr.whiteImage );
     qglColor3f (1,1,1);
     qglDepthRange( 0, 0 );  // never occluded
     GL_State( GLS_POLYMODE_LINE | GLS_DEPTHMASK_TRUE );
     qglBegin (GL_LINES);
     for (i = 0 ; i < input->numVertexes ; i++) {
         qglVertex3fv (input->xyz[i]);
         VectorMA (input->xyz[i], 2, input->normal[i], temp);
         qglVertex3fv (temp);
     }
     qglEnd ();
     qglDepthRange( 0, 1 );
 }
References GL_Bind(), GL_State(), GLS_DEPTHMASK_TRUE, GLS_POLYMODE_LINE, qglBegin, qglColor3f, qglDepthRange, qglEnd, qglVertex3fv, tr, VectorMA, and trGlobals_t::whiteImage.
Referenced by RB_EndSurface().
DrawTris()
static void DrawTris (shaderCommands_t * input) static
Definition at line 254 of file tr_shade.c.
{
     GL_Bind( tr.whiteImage );
     qglColor3f (1,1,1);
     GL_State( GLS_POLYMODE_LINE | GLS_DEPTHMASK_TRUE );
     qglDepthRange( 0, 0 );
     qglDisableClientState (GL_COLOR_ARRAY);
     qglDisableClientState (GL_TEXTURE_COORD_ARRAY);
     qglVertexPointer (3, GL_FLOAT, 16, input->xyz); // padded for SIMD
     if (qglLockArraysEXT) {
         qglLockArraysEXT(0, input->numVertexes);
         GLimp_LogComment( "glLockArraysEXT\n" );
     }
     R_DrawElements( input->numIndexes, input->indexes );
     if (qglUnlockArraysEXT) {
         qglUnlockArraysEXT();
         GLimp_LogComment( "glUnlockArraysEXT\n" );
     }
     qglDepthRange( 0, 1 );
 }
References GL_Bind(), GL_State(), GLimp_LogComment(), GLS_DEPTHMASK_TRUE, GLS_POLYMODE_LINE, qglColor3f, qglDepthRange, qglDisableClientState, qglLockArraysEXT, qglUnlockArraysEXT, qglVertexPointer, R_DrawElements(), tr, and trGlobals_t::whiteImage.
Referenced by RB_EndSurface().
ProjectDlightTexture()
static void ProjectDlightTexture (void) static
Definition at line 774 of file tr_shade.c.
{
 #if idppc_altivec
     if (com_altivec->integer) {
         // must be in a seperate function or G3 systems will crash.
         ProjectDlightTexture_altivec();
         return;
     }
 #endif
     ProjectDlightTexture_scalar();
 }
References com_altivec, and ProjectDlightTexture_scalar().
Referenced by RB_GLSL_StageIteratorGeneric(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
ProjectDlightTexture_scalar()
static void ProjectDlightTexture_scalar (void) static
Definition at line 622 of file tr_shade.c.
{
     int     i, l;
     vec3_t  origin;
     float   *texCoords;
     byte    *colors;
     byte    clipBits[SHADER_MAX_VERTEXES];
     float   texCoordsArray[SHADER_MAX_VERTEXES][2];
     byte    colorArray[SHADER_MAX_VERTEXES][4];
     unsigned    hitIndexes[SHADER_MAX_INDEXES];
     int     numIndexes;
     float   scale;
     float   radius;
     vec3_t  floatColor;
     float   modulate = 0.0f;
     if ( !backEnd.refdef.num_dlights ) {
         return;
     }
     for ( l = 0 ; l < backEnd.refdef.num_dlights ; l++ ) {
         dlight_t    *dl;
         if ( !( tess.dlightBits & ( 1 << l ) ) ) {
             continue;   // this surface definately doesn't have any of this light
         }
         texCoords = texCoordsArray[0];
         colors = colorArray[0];
         dl = &backEnd.refdef.dlights[l];
         VectorCopy( dl->transformed, origin );
         radius = dl->radius;
         scale = 1.0f / radius;
         if(r_greyscale->integer)
         {
             float luminance;
             luminance = LUMA(dl->color[0], dl->color[1], dl->color[2]) * 255.0f;
             floatColor[0] = floatColor[1] = floatColor[2] = luminance;
         }
         else if(r_greyscale->value)
         {
             float luminance;
             luminance = LUMA(dl->color[0], dl->color[1], dl->color[2]) * 255.0f;
             floatColor[0] = LERP(dl->color[0] * 255.0f, luminance, r_greyscale->value);
             floatColor[1] = LERP(dl->color[1] * 255.0f, luminance, r_greyscale->value);
             floatColor[2] = LERP(dl->color[2] * 255.0f, luminance, r_greyscale->value);
         }
         else
         {
             floatColor[0] = dl->color[0] * 255.0f;
             floatColor[1] = dl->color[1] * 255.0f;
             floatColor[2] = dl->color[2] * 255.0f;
         }
         for ( i = 0 ; i < tess.numVertexes ; i++, texCoords += 2, colors += 4 ) {
             int     clip = 0;
             vec3_t  dist;
             VectorSubtract( origin, tess.xyz[i], dist );
             backEnd.pc.c_dlightVertexes++;
             texCoords[0] = 0.5f + dist[0] * scale;
             texCoords[1] = 0.5f + dist[1] * scale;
             if( !r_dlightBacks->integer &&
                     // dist . tess.normal[i]
                     ( dist[0] * tess.normal[i][0] +
                     dist[1] * tess.normal[i][1] +
                     dist[2] * tess.normal[i][2] ) < 0.0f ) {
                 clip = 63;
             } else {
                 if ( texCoords[0] < 0.0f ) {
                     clip |= 1;
                 } else if ( texCoords[0] > 1.0f ) {
                     clip |= 2;
                 }
                 if ( texCoords[1] < 0.0f ) {
                     clip |= 4;
                 } else if ( texCoords[1] > 1.0f ) {
                     clip |= 8;
                 }
                 texCoords[0] = texCoords[0];
                 texCoords[1] = texCoords[1];
                 // modulate the strength based on the height and color
                 if ( dist[2] > radius ) {
                     clip |= 16;
                     modulate = 0.0f;
                 } else if ( dist[2] < -radius ) {
                     clip |= 32;
                     modulate = 0.0f;
                 } else {
                     dist[2] = Q_fabs(dist[2]);
                     if ( dist[2] < radius * 0.5f ) {
                         modulate = 1.0f;
                     } else {
                         modulate = 2.0f * (radius - dist[2]) * scale;
                     }
                 }
             }
             clipBits[i] = clip;
             colors[0] = ri.ftol(floatColor[0] * modulate);
             colors[1] = ri.ftol(floatColor[1] * modulate);
             colors[2] = ri.ftol(floatColor[2] * modulate);
             colors[3] = 255;
         }
         // build a list of triangles that need light
         numIndexes = 0;
         for ( i = 0 ; i < tess.numIndexes ; i += 3 ) {
             int     a, b, c;
             a = tess.indexes[i];
             b = tess.indexes[i+1];
             c = tess.indexes[i+2];
             if ( clipBits[a] & clipBits[b] & clipBits[c] ) {
                 continue;   // not lighted
             }
             hitIndexes[numIndexes] = a;
             hitIndexes[numIndexes+1] = b;
             hitIndexes[numIndexes+2] = c;
             numIndexes += 3;
         }
         if ( !numIndexes ) {
             continue;
         }
         qglEnableClientState( GL_TEXTURE_COORD_ARRAY );
         qglTexCoordPointer( 2, GL_FLOAT, 0, texCoordsArray[0] );
         qglEnableClientState( GL_COLOR_ARRAY );
         qglColorPointer( 4, GL_UNSIGNED_BYTE, 0, colorArray );
         GL_Bind( tr.dlightImage );
         // include GLS_DEPTHFUNC_EQUAL so alpha tested surfaces don't add light
         // where they aren't rendered
         if ( dl->additive ) {
             GL_State( GLS_SRCBLEND_ONE | GLS_DSTBLEND_ONE | GLS_DEPTHFUNC_EQUAL );
         }
         else {
             GL_State( GLS_SRCBLEND_DST_COLOR | GLS_DSTBLEND_ONE | GLS_DEPTHFUNC_EQUAL );
         }
         R_DrawElements( numIndexes, hitIndexes );
         backEnd.pc.c_totalIndexes += numIndexes;
         backEnd.pc.c_dlightIndexes += numIndexes;
     }
 }
References backEnd, backEndCounters_t::c_dlightIndexes, backEndCounters_t::c_dlightVertexes, backEndCounters_t::c_totalIndexes, trGlobals_t::dlightImage, trRefdef_t::dlights, refimport_t::ftol, GL_Bind(), GL_State(), GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_ONE, LERP, LUMA, trRefdef_t::num_dlights, backEndState_t::pc, Q_fabs(), qglColorPointer, qglEnableClientState, qglTexCoordPointer, r_dlightBacks, R_DrawElements(), r_greyscale, backEndState_t::refdef, ri, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, tess, tr, VectorCopy, and VectorSubtract.
Referenced by ProjectDlightTexture().
R_ArrayElementDiscrete()
static void APIENTRY R_ArrayElementDiscrete (GLint index) static
Definition at line 43 of file tr_shade.c.
{
     qglColor4ubv( tess.svars.colors[ index ] );
     if ( glState.currenttmu ) {
         qglMultiTexCoord2fARB( 0, tess.svars.texcoords[ 0 ][ index ][0], tess.svars.texcoords[ 0 ][ index ][1] );
         qglMultiTexCoord2fARB( 1, tess.svars.texcoords[ 1 ][ index ][0], tess.svars.texcoords[ 1 ][ index ][1] );
     } else {
         qglTexCoord2fv( tess.svars.texcoords[ 0 ][ index ] );
     }
     qglVertex3fv( tess.xyz[ index ] );
 }
References glstate_t::currenttmu, glState, qglColor4ubv, qglMultiTexCoord2fARB, qglTexCoord2fv, qglVertex3fv, and tess.
Referenced by R_DrawElements().
R_BindAnimatedImage()
static void R_BindAnimatedImage (textureBundle_t * bundle) static
Definition at line 220 of file tr_shade.c.
{
     int     index;
     if ( bundle->isVideoMap ) {
         ri.CIN_RunCinematic(bundle->videoMapHandle);
         ri.CIN_UploadCinematic(bundle->videoMapHandle);
         return;
     }
     if ( bundle->numImageAnimations <= 1 ) {
         GL_Bind( bundle->image[0] );
         return;
     }
     // it is necessary to do this messy calc to make sure animations line up
     // exactly with waveforms of the same frequency
     index = ri.ftol(tess.shaderTime * bundle->imageAnimationSpeed * FUNCTABLE_SIZE);
     index >>= FUNCTABLE_SIZE2;
     if ( index < 0 ) {
         index = 0;  // may happen with shader time offsets
     }
     index %= bundle->numImageAnimations;
     GL_Bind( bundle->image[ index ] );
 }
References refimport_t::CIN_RunCinematic, refimport_t::CIN_UploadCinematic, refimport_t::ftol, FUNCTABLE_SIZE, FUNCTABLE_SIZE2, GL_Bind(), textureBundle_t::image, textureBundle_t::imageAnimationSpeed, textureBundle_t::isVideoMap, textureBundle_t::numImageAnimations, ri, tess, and textureBundle_t::videoMapHandle.
Referenced by DrawMultitextured(), RB_GLSL_IterateStagesGeneric(), RB_IterateStagesGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
R_DrawElements()
static void R_DrawElements (int numIndexes, const glIndex_t * indexes) static
Definition at line 166 of file tr_shade.c.
{
     int     primitives;
     primitives = r_primitives->integer;
     // default is to use triangles if compiled vertex arrays are present
     if ( primitives == 0 ) {
         if ( qglLockArraysEXT ) {
             primitives = 2;
         } else {
             primitives = 1;
         }
     }
     if ( primitives == 2 ) {
         qglDrawElements( GL_TRIANGLES,
                         numIndexes,
                         GL_INDEX_TYPE,
                         indexes );
         return;
     }
     if ( primitives == 1 ) {
         R_DrawStripElements( numIndexes,  indexes, qglArrayElement );
         return;
     }
     if ( primitives == 3 ) {
         R_DrawStripElements( numIndexes,  indexes, R_ArrayElementDiscrete );
         return;
     }
     // anything else will cause no drawing
 }
References GL_INDEX_TYPE, indexes, qglArrayElement, qglDrawElements, qglLockArraysEXT, R_ArrayElementDiscrete(), R_DrawStripElements(), and r_primitives.
Referenced by DrawBBoxes(), DrawMultitextured(), DrawTris(), ProjectDlightTexture_scalar(), RB_FogPass(), RB_GLSL_IterateStagesGeneric(), RB_HazePass(), RB_IterateStagesGeneric(), RB_OutlinesPass(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
R_DrawStripElements()
static void R_DrawStripElements (int numIndexes, const glIndex_t * indexes, void(APIENTRY *element)(GLint)) static
Definition at line 62 of file tr_shade.c.
{
     int i;
     int last[3] = { -1, -1, -1 };
     qboolean even;
     c_begins++;
     if ( numIndexes <= 0 ) {
         return;
     }
     qglBegin( GL_TRIANGLE_STRIP );
     // prime the strip
     element( indexes[0] );
     element( indexes[1] );
     element( indexes[2] );
     c_vertexes += 3;
     last[0] = indexes[0];
     last[1] = indexes[1];
     last[2] = indexes[2];
     even = qfalse;
     for ( i = 3; i < numIndexes; i += 3 )
     {
         // odd numbered triangle in potential strip
         if ( !even )
         {
             // check previous triangle to see if we're continuing a strip
             if ( ( indexes[i+0] == last[2] ) && ( indexes[i+1] == last[1] ) )
             {
                 element( indexes[i+2] );
                 c_vertexes++;
                 assert( indexes[i+2] < tess.numVertexes );
                 even = qtrue;
             }
             // otherwise we're done with this strip so finish it and start
             // a new one
             else
             {
                 qglEnd();
                 qglBegin( GL_TRIANGLE_STRIP );
                 c_begins++;
                 element( indexes[i+0] );
                 element( indexes[i+1] );
                 element( indexes[i+2] );
                 c_vertexes += 3;
                 even = qfalse;
             }
         }
         else
         {
             // check previous triangle to see if we're continuing a strip
             if ( ( last[2] == indexes[i+1] ) && ( last[0] == indexes[i+0] ) )
             {
                 element( indexes[i+2] );
                 c_vertexes++;
                 even = qfalse;
             }
             // otherwise we're done with this strip so finish it and start
             // a new one
             else
             {
                 qglEnd();
                 qglBegin( GL_TRIANGLE_STRIP );
                 c_begins++;
                 element( indexes[i+0] );
                 element( indexes[i+1] );
                 element( indexes[i+2] );
                 c_vertexes += 3;
                 even = qfalse;
             }
         }
         // cache the last three vertices
         last[0] = indexes[i+0];
         last[1] = indexes[i+1];
         last[2] = indexes[i+2];
     }
     qglEnd();
 }
References c_begins, c_vertexes, indexes, qfalse, qglBegin, qglEnd, qtrue, and tess.
Referenced by R_DrawElements().
RB_BeginSurface()
void RB_BeginSurface (shader_t * shader, int fogNum)
Definition at line 351 of file tr_shade.c.
{
     shader_t *state = (shader->remappedShader) ? shader->remappedShader : shader;
     tess.numIndexes = 0;
     tess.numVertexes = 0;
     tess.shader = state;
     tess.fogNum = fogNum;
     tess.dlightBits = 0;        // will be OR'd in by surface functions
     tess.xstages = state->stages;
     tess.numPasses = state->numUnfoggedPasses;
     tess.currentStageIteratorFunc = state->optimalStageIteratorFunc;
     tess.shaderTime = backEnd.refdef.floatTime - tess.shader->timeOffset;
     if (tess.shader->clampTime && tess.shaderTime >= tess.shader->clampTime) {
         tess.shaderTime = tess.shader->clampTime;
     }
 }
References backEnd, trRefdef_t::floatTime, backEndState_t::refdef, and tess.
Referenced by RB_CheckOverflow(), RB_DrawSun(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_StretchPic(), RB_SurfaceGrid(), and SurfIsOffscreen().
RB_EndSurface()
void RB_EndSurface (void)
Definition at line 1962 of file tr_shade.c.
{
     shaderCommands_t *input;
     input = &tess;
     if (input->numIndexes == 0) {
         return;
     }
     if (input->indexes[SHADER_MAX_INDEXES-1] != 0) {
         ri.Error (ERR_DROP, "RB_EndSurface() - SHADER_MAX_INDEXES hit");
     }
     if (input->xyz[SHADER_MAX_VERTEXES-1][0] != 0) {
         ri.Error (ERR_DROP, "RB_EndSurface() - SHADER_MAX_VERTEXES hit");
     }
     if ( tess.shader == tr.shadowShader ) {
         RB_ShadowTessEnd();
         return;
     }
     // for debugging of sort order issues, stop rendering after a given sort value
     if ( r_debugSort->integer && r_debugSort->integer < tess.shader->sort ) {
         return;
     }
     //
     // update performance counters
     //
     backEnd.pc.c_shaders++;
     backEnd.pc.c_vertexes += tess.numVertexes;
     backEnd.pc.c_indexes += tess.numIndexes;
     backEnd.pc.c_totalIndexes += tess.numIndexes * tess.numPasses;
     //
     // call off to shader specific tess end function
     //
     tess.currentStageIteratorFunc();
     //
     // draw debugging stuff
     //
     if ( r_showtris->integer ) {
         DrawTris (input);
     }
     if ( r_shownormals->integer ) {
         DrawNormals (input);
     }
     if ( r_showbboxes->integer ) {
         DrawBBoxes (input);
     }
     // clear shader so we can tell we don't have any unclosed surfaces
     tess.numIndexes = 0;
     GLimp_LogComment( "----------\n" );
 }
References backEnd, backEndCounters_t::c_indexes, backEndCounters_t::c_shaders, backEndCounters_t::c_totalIndexes, backEndCounters_t::c_vertexes, DrawBBoxes(), DrawNormals(), DrawTris(), ERR_DROP, GLimp_LogComment(), backEndState_t::pc, r_debugSort, r_showbboxes, r_shownormals, r_showtris, RB_ShadowTessEnd(), ri, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, trGlobals_t::shadowShader, tess, and tr.
Referenced by RB_CheckOverflow(), RB_ClearDepth(), RB_DrawSun(), RB_DrawSurfs(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_StretchPic(), RB_SurfaceGrid(), and RB_SwapBuffers().
RB_FogPass()
static void RB_FogPass (void) static
Definition at line 793 of file tr_shade.c.
{
     fog_t       *fog;
     int         i;
     qglEnableClientState( GL_COLOR_ARRAY );
     qglColorPointer( 4, GL_UNSIGNED_BYTE, 0, tess.svars.colors );
     qglEnableClientState( GL_TEXTURE_COORD_ARRAY);
     qglTexCoordPointer( 2, GL_FLOAT, 0, tess.svars.texcoords[0] );
     fog = tr.world->fogs + tess.fogNum;
     for ( i = 0; i < tess.numVertexes; i++ ) {
         * ( int * )&tess.svars.colors[i] = fog->colorInt;
     }
     RB_CalcFogTexCoords( ( float * ) tess.svars.texcoords[0] );
     GL_Bind( tr.fogImage );
     if ( tess.shader->fogPass == FP_EQUAL ) {
         GL_State( GLS_SRCBLEND_SRC_ALPHA | GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA | GLS_DEPTHFUNC_EQUAL );
     } else {
         GL_State( GLS_SRCBLEND_SRC_ALPHA | GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA );
     }
     R_DrawElements( tess.numIndexes, tess.indexes );
 }
References fog_t::colorInt, trGlobals_t::fogImage, world_t::fogs, FP_EQUAL, GL_Bind(), GL_State(), GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_SRCBLEND_SRC_ALPHA, qglColorPointer, qglEnableClientState, qglTexCoordPointer, R_DrawElements(), RB_CalcFogTexCoords(), tess, tr, and trGlobals_t::world.
Referenced by RB_GLSL_StageIteratorGeneric(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
RB_GLSL_IterateStagesGeneric()
static void RB_GLSL_IterateStagesGeneric (shaderCommands_t * input) static
Definition at line 1641 of file tr_shade.c.
{
     int stage;
     for(stage = 0; stage < MAX_SHADER_STAGES; stage++) {
         shaderStage_t   *pStage = tess.xstages[stage];
         glslProgram_t   *program;
         if (!pStage || pStage->program == tr.skipProgram)
             break;
         /* set state */
         GL_State(pStage->stateBits);
         /*
          * this is an ugly hack to work around a GeForce driver
          * bug with multitexture and clip planes
          */
         if (backEnd.viewParms.isPortal)
             qglPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
         if (pStage->program)
             /* use specified program */
             R_GLSL_UseProgram(pStage->program);
         else
             /* use default program */
             R_GLSL_UseProgram(tr.defaultProgram);
         program = tr.programs[glState.currentProgram];
         /* alphaGen */
         if (program->u_AlphaGen > -1)
             R_GLSL_SetUniform_AlphaGen(program, pStage->alphaGen);
         /* ambient light */
         if (program->u_AmbientLight > -1)
             R_GLSL_SetUniform_AmbientLight(program, backEnd.currentEntity->ambientLight);
         /* dynamic light */
         if (program->u_DynamicLight > -1)
             R_GLSL_SetUniform_DynamicLight(program, backEnd.currentEntity->dynamicLight);
         /* light distance */
         if (program->u_LightDistance > -1)
             R_GLSL_SetUniform_LightDistance(program, backEnd.currentEntity->lightDistance);
         /* rgbGen */
         if (program->u_ColorGen > -1)
             R_GLSL_SetUniform_ColorGen(program, pStage->rgbGen);
         /* constant color */
         if (program->u_ConstantColor > -1)
             R_GLSL_SetUniform_ConstantColor(program, pStage->constantColor);
         /* directed light */
         if (program->u_DirectedLight > -1)
             R_GLSL_SetUniform_DirectedLight(program, backEnd.currentEntity->directedLight);
         /* entity color */
         if (program->u_EntityColor > -1)
             R_GLSL_SetUniform_EntityColor(program, backEnd.currentEntity->e.shaderRGBA);
         /* fog color */
         if (program->u_FogColor > -1 && tess.fogNum)
             R_GLSL_SetUniform_FogColor(program, (tr.world->fogs + tess.fogNum)->colorInt);
         /* greyscale */
         if (program->u_Greyscale > -1)
             R_GLSL_SetUniform_Greyscale(program, r_greyscale->integer);
         /* identity light */
         if (program->u_IdentityLight > -1)
             R_GLSL_SetUniform_IdentityLight(program, tr.identityLight);
         /* light direction */
         if (program->u_LightDirection > -1)
             R_GLSL_SetUniform_LightDirection(program, backEnd.currentEntity->lightDir);
         /* model view matrix */
         if (program->u_ModelViewMatrix > -1)
             R_GLSL_SetUniform_ModelViewMatrix(program, glState.currentModelViewMatrix);
         /* model view projection matrix */
         if (program->u_ModelViewProjectionMatrix > -1)
             R_GLSL_SetUniform_ModelViewProjectionMatrix(program, glState.currentModelViewProjectionMatrix);
         /* projection matrix */
         if (program->u_ProjectionMatrix > -1)
             R_GLSL_SetUniform_ProjectionMatrix(program, glState.currentProjectionMatrix);
         /* texture coordinates 0 */
         if (program->u_TCGen0 > -1)
             R_GLSL_SetUniform_TCGen0(program, pStage->bundle[0].tcGen);
         /* texture coordinates 1 */
         if (program->u_TCGen1 > -1)
             R_GLSL_SetUniform_TCGen1(program, pStage->bundle[1].tcGen);
         /* tex env */
         if (program->u_TexEnv > -1) {
             if (r_lightmap->integer)
                 R_GLSL_SetUniform_TexEnv(program, GL_REPLACE);
             else
                 R_GLSL_SetUniform_TexEnv(program, input->shader->multitextureEnv);
         }
         /* texture unit 0 */
         if (program->u_Texture0 > -1 && pStage->bundle[0].image[0]) {
             GL_SelectTexture(0);
             if (pStage->bundle[0].vertexLightmap && ((r_vertexLight->integer && !r_uiFullScreen->integer) || glConfig.hardwareType == GLHW_PERMEDIA2) && r_lightmap->integer)
                 GL_Bind(tr.whiteImage);
             else
                 R_BindAnimatedImage(&pStage->bundle[0]);
         }
         /* texture unit 1 */
         if (program->u_Texture1 > -1 && pStage->bundle[1].image[0]) {
             GL_SelectTexture(1);
             qglEnable(GL_TEXTURE_2D);
             R_BindAnimatedImage(&pStage->bundle[1]);
         }
         /* texture unit 2 */
         if (program->u_Texture2 > -1 && pStage->bundle[2].image[0]) {
             GL_SelectTexture(2);
             qglEnable(GL_TEXTURE_2D);
             R_BindAnimatedImage(&pStage->bundle[2]);
         }
         /* texture unit 3 */
         if (program->u_Texture3 > -1 && pStage->bundle[3].image[0]) {
             GL_SelectTexture(3);
             qglEnable(GL_TEXTURE_2D);
             R_BindAnimatedImage(&pStage->bundle[3]);
         }
         /* texture unit 4 */
         if (program->u_Texture4 > -1 && pStage->bundle[4].image[0]) {
             GL_SelectTexture(4);
             qglEnable(GL_TEXTURE_2D);
             R_BindAnimatedImage(&pStage->bundle[4]);
         }
         /* texture unit 5 */
         if (program->u_Texture5 > -1 && pStage->bundle[5].image[0]) {
             GL_SelectTexture(5);
             qglEnable(GL_TEXTURE_2D);
             R_BindAnimatedImage(&pStage->bundle[5]);
         }
         /* texture unit 6 */
         if (program->u_Texture6 > -1 && pStage->bundle[6].image[0]) {
             GL_SelectTexture(6);
             qglEnable(GL_TEXTURE_2D);
             R_BindAnimatedImage(&pStage->bundle[6]);
         }
         /* texture unit 7 */
         if (program->u_Texture7 > -1 && pStage->bundle[7].image[0]) {
             GL_SelectTexture(7);
             qglEnable(GL_TEXTURE_2D);
             R_BindAnimatedImage(&pStage->bundle[7]);
         }
         /* time */
         if (program->u_Time > -1)
             R_GLSL_SetUniform_Time(program, input->shaderTime);
         /* view origin */
         if (program->u_ViewOrigin > -1)
             R_GLSL_SetUniform_ViewOrigin(program, backEnd.or.viewOrigin);
         /* draw */
         R_DrawElements(input->numIndexes, input->indexes);
         /* disable texture unit 7 */
         if (program->u_Texture7 > -1)
             qglDisable(GL_TEXTURE_2D);
         /* disable texture unit 6 */
         if (program->u_Texture6 > -1) {
             GL_SelectTexture(6);
             qglDisable(GL_TEXTURE_2D);
         }
         /* disable texture unit 5 */
         if (program->u_Texture5 > -1) {
             GL_SelectTexture(5);
             qglDisable(GL_TEXTURE_2D);
         }
         /* disable texture unit 4 */
         if (program->u_Texture4 > -1) {
             GL_SelectTexture(4);
             qglDisable(GL_TEXTURE_2D);
         }
         /* disable texture unit 3 */
         if (program->u_Texture3 > -1) {
             GL_SelectTexture(3);
             qglDisable(GL_TEXTURE_2D);
         }
         /* disable texture unit 2 */
         if (program->u_Texture2 > -1) {
             GL_SelectTexture(2);
             qglDisable(GL_TEXTURE_2D);
         }
         /* disable texture unit 1 */
         if (program->u_Texture1 > -1) {
             GL_SelectTexture(1);
             qglDisable(GL_TEXTURE_2D);
             qglDisableClientState(GL_TEXTURE_COORD_ARRAY);
         }
         /* switch to texture unit 0 */
         GL_SelectTexture(0);
         /* allow skipping out to show just lightmaps during development */
         if (r_lightmap->integer && (pStage->bundle[0].isLightmap || pStage->bundle[1].isLightmap || pStage->bundle[0].vertexLightmap))
             break;
     }
     /* switch to standard rendering pipeline */
     R_GLSL_UseProgram(0);
 }
References shaderStage_t::alphaGen, trRefEntity_t::ambientLight, backEnd, shaderStage_t::bundle, shaderStage_t::constantColor, backEndState_t::currentEntity, glstate_t::currentModelViewMatrix, glstate_t::currentModelViewProjectionMatrix, glstate_t::currentProgram, glstate_t::currentProjectionMatrix, trGlobals_t::defaultProgram, trRefEntity_t::directedLight, trRefEntity_t::dynamicLight, trRefEntity_t::e, world_t::fogs, GL_Bind(), GL_SelectTexture(), GL_State(), glConfig, GLHW_PERMEDIA2, glState, glconfig_t::hardwareType, trGlobals_t::identityLight, textureBundle_t::image, textureBundle_t::isLightmap, viewParms_t::isPortal, trRefEntity_t::lightDir, trRefEntity_t::lightDistance, MAX_SHADER_STAGES, backEndState_t::or, shaderStage_t::program, trGlobals_t::programs, qglDisable, qglDisableClientState, qglEnable, qglPolygonMode, R_BindAnimatedImage(), R_DrawElements(), R_GLSL_SetUniform_AlphaGen(), R_GLSL_SetUniform_AmbientLight(), R_GLSL_SetUniform_ColorGen(), R_GLSL_SetUniform_ConstantColor(), R_GLSL_SetUniform_DirectedLight(), R_GLSL_SetUniform_DynamicLight(), R_GLSL_SetUniform_EntityColor(), R_GLSL_SetUniform_FogColor(), R_GLSL_SetUniform_Greyscale(), R_GLSL_SetUniform_IdentityLight(), R_GLSL_SetUniform_LightDirection(), R_GLSL_SetUniform_LightDistance(), R_GLSL_SetUniform_ModelViewMatrix(), R_GLSL_SetUniform_ModelViewProjectionMatrix(), R_GLSL_SetUniform_ProjectionMatrix(), R_GLSL_SetUniform_TCGen0(), R_GLSL_SetUniform_TCGen1(), R_GLSL_SetUniform_TexEnv(), R_GLSL_SetUniform_Time(), R_GLSL_SetUniform_ViewOrigin(), R_GLSL_UseProgram(), r_greyscale, r_lightmap, r_uiFullScreen, r_vertexLight, shaderStage_t::rgbGen, refEntity_t::shaderRGBA, trGlobals_t::skipProgram, shaderStage_t::stateBits, textureBundle_t::tcGen, tess, tr, textureBundle_t::vertexLightmap, orientationr_t::viewOrigin, backEndState_t::viewParms, trGlobals_t::whiteImage, and trGlobals_t::world.
Referenced by RB_GLSL_StageIteratorGeneric().
RB_GLSL_StageIteratorGeneric()
void RB_GLSL_StageIteratorGeneric (void)
Definition at line 1873 of file tr_shade.c.
{
     shaderCommands_t    *input;
     input = &tess;
     /* log this call */
     if (r_logFile->integer) {
         /* don't just call LogComment, or we will get a call to va() every frame! */
         GLimp_LogComment(va("--- R_GLSL_StageIteratorGeneric( %s ) ---\n", input->shader->name));
     }
     /* set face culling appropiately */
     GL_Cull(input->shader->cullType);
     /* set polygon offset if necessary */
     if (input->shader->polygonOffset) {
         qglEnable(GL_POLYGON_OFFSET_FILL);
         qglPolygonOffset(r_offsetFactor->value, r_offsetUnits->value);
     }
     /* set vertex color array */
     qglEnableClientState(GL_COLOR_ARRAY);
     qglColorPointer(4, GL_UNSIGNED_BYTE, 0, input->vertexColors);
     /* set texture coordinate array 0 */
     GL_SelectTexture(0);
     qglEnableClientState(GL_TEXTURE_COORD_ARRAY);
     qglTexCoordPointer(2, GL_FLOAT, 16, input->texCoords[0][0]);
     /* set texture coordinate array 1 */
     GL_SelectTexture(1);
     qglEnableClientState(GL_TEXTURE_COORD_ARRAY);
     qglTexCoordPointer(2, GL_FLOAT, 16, input->texCoords[0][1]);
     /* set vertex normal array */
     qglEnableClientState(GL_NORMAL_ARRAY);
     qglNormalPointer(GL_FLOAT, 16, input->normal);
     /* lock XYZ */
     qglVertexPointer(3, GL_FLOAT, 16, input->xyz); /* padded SIMD */
     if (qglLockArraysEXT) {
         qglLockArraysEXT(0, input->numVertexes);
         GLimp_LogComment("glLockArraysEXT\n");
     }
     RB_GLSL_IterateStagesGeneric(input);
     /* now do any dynamic lighting needed */
     if (input->dlightBits && input->shader->sort <= SS_OPAQUE && !(input->shader->surfaceFlags & (SURF_NODLIGHT | SURF_SKY)))
         ProjectDlightTexture();
     // <-- RiO_Outlines: now do outlines
     RB_OutlinesPass();
     // -->
     /* now do fog */
     if (input->fogNum && input->shader->fogPass)
         RB_FogPass(); // TODO: uses svars which aren't set, so move to program
     /* unlock arrays */
     if (qglUnlockArraysEXT) {
         qglUnlockArraysEXT();
         GLimp_LogComment("glUnlockArraysExt\n");
     }
     /* reset polygon offset */
     if (input->shader->polygonOffset)
         qglDisable(GL_POLYGON_OFFSET_FILL);
 }
References GL_Cull(), GL_SelectTexture(), GLimp_LogComment(), ProjectDlightTexture(), qglColorPointer, qglDisable, qglEnable, qglEnableClientState, qglLockArraysEXT, qglNormalPointer, qglPolygonOffset, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, r_logFile, r_offsetFactor, r_offsetUnits, RB_FogPass(), RB_GLSL_IterateStagesGeneric(), RB_OutlinesPass(), SS_OPAQUE, SURF_NODLIGHT, SURF_SKY, tess, and va().
Referenced by ComputeStageIteratorFunc().
RB_GLSL_StageIteratorLightmappedMultitexture()
void RB_GLSL_StageIteratorLightmappedMultitexture (void)
Definition at line 1955 of file tr_shade.c.
{
     RB_StageIteratorLightmappedMultitexture(); // TODO: placeholder
 }
References RB_StageIteratorLightmappedMultitexture().
Referenced by ComputeStageIteratorFunc().
RB_GLSL_StageIteratorVertexLitTexture()
void RB_GLSL_StageIteratorVertexLitTexture (void)
Definition at line 1947 of file tr_shade.c.
{
     RB_StageIteratorVertexLitTexture(); // TODO: placeholder
 }
References RB_StageIteratorVertexLitTexture().
Referenced by ComputeStageIteratorFunc().
RB_HazePass()
static void RB_HazePass (void) static
Definition at line 830 of file tr_shade.c.
{
     int         i;
     unsigned int color[3], colorInt;
     // TODO; Get color from worlspawn. Use black for now.
     color[0] = 0;
     color[1] = 0;
     color[2] = 0;
     colorInt = ColorBytes4( color[0] * tr.identityLight, color[1] * tr.identityLight, color[2] * tr.identityLight, 1.0 );
     qglEnableClientState( GL_COLOR_ARRAY );
     qglColorPointer( 4, GL_UNSIGNED_BYTE, 0, tess.svars.colors );
     qglEnableClientState( GL_TEXTURE_COORD_ARRAY);
     qglTexCoordPointer( 2, GL_FLOAT, 0, tess.svars.texcoords[0] );
     //fog = tr.world->fogs + tess.fogNum;
     for ( i = 0; i < tess.numVertexes; i++ ) {
         * ( int * )&tess.svars.colors[i] = colorInt;
     }
     RB_CalcFogTexCoords( ( float * ) tess.svars.texcoords[0] );
     GL_Bind( tr.fogImage );
     if ( tess.shader->fogPass == FP_EQUAL ) {
         GL_State( GLS_SRCBLEND_SRC_ALPHA | GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA | GLS_DEPTHFUNC_EQUAL );
     } else {
         GL_State( GLS_SRCBLEND_SRC_ALPHA | GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA );
     }
     R_DrawElements( tess.numIndexes, tess.indexes );
 }
References ColorBytes4(), trGlobals_t::fogImage, FP_EQUAL, GL_Bind(), GL_State(), GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_SRCBLEND_SRC_ALPHA, trGlobals_t::identityLight, qglColorPointer, qglEnableClientState, qglTexCoordPointer, R_DrawElements(), RB_CalcFogTexCoords(), tess, and tr.
RB_IterateStagesGeneric()
static void RB_IterateStagesGeneric (shaderCommands_t * input) static
Definition at line 1262 of file tr_shade.c.
 {
     int stage;
     for ( stage = 0; stage < MAX_SHADER_STAGES; stage++ )
     {
         shaderStage_t *pStage = tess.xstages[stage];
         if ( !pStage )
         {
             break;
         }
         qglTexEnvf(GL_TEXTURE_FILTER_CONTROL,GL_TEXTURE_LOD_BIAS,r_mipBias->value + pStage->mipBias);
         ComputeColors( pStage );
         ComputeTexCoords( pStage );
         if ( !setArraysOnce )
         {
             qglEnableClientState( GL_COLOR_ARRAY );
             qglColorPointer( 4, GL_UNSIGNED_BYTE, 0, input->svars.colors );
         }
         //
         // do multitexture
         //
         if ( pStage->bundle[1].image[0] != 0 )
         {
             DrawMultitextured( input, stage );
         }
         else
         {
             if ( !setArraysOnce )
             {
                 qglTexCoordPointer( 2, GL_FLOAT, 0, input->svars.texcoords[0] );
             }
             //
             // set state
             //
             if ( pStage->bundle[0].vertexLightmap && ( (r_vertexLight->integer && !r_uiFullScreen->integer) || glConfig.hardwareType == GLHW_PERMEDIA2 ) && r_lightmap->integer )
             {
                 GL_Bind( tr.whiteImage );
             }
             else
                 R_BindAnimatedImage( &pStage->bundle[0] );
             GL_State( pStage->stateBits );
             //
             // draw
             //
             R_DrawElements( input->numIndexes, input->indexes );
         }
         // allow skipping out to show just lightmaps during development
         if ( r_lightmap->integer && ( pStage->bundle[0].isLightmap || pStage->bundle[1].isLightmap || pStage->bundle[0].vertexLightmap ) )
         {
             break;
         }
     }
 }
References shaderStage_t::bundle, ComputeColors(), ComputeTexCoords(), DrawMultitextured(), GL_Bind(), GL_State(), GL_TEXTURE_FILTER_CONTROL, GL_TEXTURE_LOD_BIAS, glConfig, GLHW_PERMEDIA2, glconfig_t::hardwareType, textureBundle_t::image, textureBundle_t::isLightmap, MAX_SHADER_STAGES, shaderStage_t::mipBias, qglColorPointer, qglEnableClientState, qglTexCoordPointer, qglTexEnvf, R_BindAnimatedImage(), R_DrawElements(), r_lightmap, r_mipBias, r_uiFullScreen, r_vertexLight, setArraysOnce, shaderStage_t::stateBits, tess, tr, textureBundle_t::vertexLightmap, and trGlobals_t::whiteImage.
Referenced by RB_StageIteratorGeneric().
RB_OutlinesPass()
static void RB_OutlinesPass (void) static
Definition at line 875 of file tr_shade.c.
{
     float   outlinesAlpha;
     int     outlineType;
     int     outlineState;
     qboolean outlineAlias;
     outlinesAlpha   = r_outlinesAlpha->value;
     if (!tess.shader->hasOutlines){return;}
     GL_Bind( tr.whiteImage );
     qglColor4f( 0, 0, 0, outlinesAlpha );
     outlineState = GLS_POLYMODE_LINE;
     GL_State( outlineState | GLS_DEPTHMASK_TRUE | GLS_SRCBLEND_SRC_ALPHA | GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA );
     if(r_outlinesSmooth->value){qglEnable(GL_LINE_SMOOTH);}
     if(r_outlinesType->value == 1){
         qglLineStipple(r_outlinesPatternFactor->value,r_outlinesPattern->value);
         qglEnable(GL_LINE_STIPPLE);
     }
     if(r_outlinesType->value == 2){
         qglEnable(GL_DEPTH_TEST);
         qglEnable(GL_POLYGON_OFFSET_FILL);
         qglBlendFunc (GL_ZERO, GL_ONE);
         qglEnable(GL_CULL_FACE);
         qglPolygonMode(GL_FRONT_AND_BACK,GL_FILL);
     }
     else{
         qglPolygonMode(GL_BACK,GL_LINE);
         qglLineWidth(r_outlines->value + 1);
     }
     qglCullFace(GL_BACK);
     qglDisableClientState( GL_COLOR_ARRAY );
     qglDisableClientState( GL_TEXTURE_COORD_ARRAY );
     qglVertexPointer (3, GL_FLOAT, 16, tess.xyz);   // padded for SIMD
     if (qglLockArraysEXT) {
         qglLockArraysEXT(0, tess.numVertexes);
         GLimp_LogComment( "glLockArraysEXT\n" );
     }
     R_DrawElements( tess.numIndexes, tess.indexes );
     if (qglUnlockArraysEXT) {
         qglUnlockArraysEXT();
         GLimp_LogComment( "glUnlockArraysEXT\n" );
     }
     // FIX: Must reset these manually or renderer will b0rk!
     qglCullFace(GL_FRONT);
     qglLineWidth(1);
     if(r_outlinesSmooth->value){qglDisable(GL_LINE_SMOOTH);}
     if(r_outlinesType->value == 1){
         qglDisable(GL_LINE_STIPPLE);
     }
     if(r_outlinesType->value == 2){
         qglDisable(GL_CULL_FACE);
         qglDisable(GL_DEPTH_TEST);
         qglDisable(GL_POLYGON_OFFSET_FILL);
     }
 }
References GL_Bind(), GL_State(), GLimp_LogComment(), GLS_DEPTHMASK_TRUE, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_POLYMODE_LINE, GLS_SRCBLEND_SRC_ALPHA, qglBlendFunc, qglColor4f, qglCullFace, qglDisable, qglDisableClientState, qglEnable, qglLineStipple, qglLineWidth, qglLockArraysEXT, qglPolygonMode, qglUnlockArraysEXT, qglVertexPointer, R_DrawElements(), r_outlines, r_outlinesAlpha, r_outlinesPattern, r_outlinesPatternFactor, r_outlinesSmooth, r_outlinesType, tess, tr, and trGlobals_t::whiteImage.
Referenced by RB_GLSL_StageIteratorGeneric(), RB_StageIteratorGeneric(), RB_StageIteratorLightmappedMultitexture(), and RB_StageIteratorVertexLitTexture().
RB_StageIteratorGeneric()
void RB_StageIteratorGeneric (void)
Definition at line 1327 of file tr_shade.c.
 {
     shaderCommands_t *input;
     shader_t        *shader;
     input = &tess;
     shader = input->shader;
     RB_DeformTessGeometry();
     //
     // log this call
     //
     if ( r_logFile->integer )
     {
         // don't just call LogComment, or we will get
         // a call to va() every frame!
         GLimp_LogComment( va("--- RB_StageIteratorGeneric( %s ) ---\n", tess.shader->name) );
     }
     //
     // set face culling appropriately
     //
     GL_Cull( shader->cullType );
     // set polygon offset if necessary
     if ( shader->polygonOffset )
     {
         qglEnable( GL_POLYGON_OFFSET_FILL );
         qglPolygonOffset( r_offsetFactor->value, r_offsetUnits->value );
     }
     //
     // if there is only a single pass then we can enable color
     // and texture arrays before we compile, otherwise we need
     // to avoid compiling those arrays since they will change
     // during multipass rendering
     //
     if ( tess.numPasses > 1 || shader->multitextureEnv )
     {
         setArraysOnce = qfalse;
         qglDisableClientState (GL_COLOR_ARRAY);
         qglDisableClientState (GL_TEXTURE_COORD_ARRAY);
     }
     else
     {
         setArraysOnce = qtrue;
         qglEnableClientState( GL_COLOR_ARRAY);
         qglColorPointer( 4, GL_UNSIGNED_BYTE, 0, tess.svars.colors );
         qglEnableClientState( GL_TEXTURE_COORD_ARRAY);
         qglTexCoordPointer( 2, GL_FLOAT, 0, tess.svars.texcoords[0] );
     }
     //
     // lock XYZ
     //
     qglVertexPointer (3, GL_FLOAT, 16, input->xyz); // padded for SIMD
     if (qglLockArraysEXT)
     {
         qglLockArraysEXT(0, input->numVertexes);
         GLimp_LogComment( "glLockArraysEXT\n" );
     }
     //
     // enable color and texcoord arrays after the lock if necessary
     //
     if ( !setArraysOnce )
     {
         qglEnableClientState( GL_TEXTURE_COORD_ARRAY );
         qglEnableClientState( GL_COLOR_ARRAY );
     }
     //
     // call shader function
     //
     RB_IterateStagesGeneric( input );
     //
     // now do any dynamic lighting needed
     //
     if ( tess.dlightBits && tess.shader->sort <= SS_OPAQUE
         && !(tess.shader->surfaceFlags & (SURF_NODLIGHT | SURF_SKY) ) ) {
         ProjectDlightTexture();
     }
     // <-- RiO_Outlines: now do outlines
     RB_OutlinesPass();
     // -->
     //
     // now do fog
     //
     if ( tess.fogNum && tess.shader->fogPass ) {
         RB_FogPass();
     }
     //
     // unlock arrays
     //
     if (qglUnlockArraysEXT)
     {
         qglUnlockArraysEXT();
         GLimp_LogComment( "glUnlockArraysEXT\n" );
     }
     //
     // reset polygon offset
     //
     if ( shader->polygonOffset )
     {
         qglDisable( GL_POLYGON_OFFSET_FILL );
     }
 }
References GL_Cull(), GLimp_LogComment(), ProjectDlightTexture(), qfalse, qglColorPointer, qglDisable, qglDisableClientState, qglEnable, qglEnableClientState, qglLockArraysEXT, qglPolygonOffset, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, qtrue, r_logFile, r_offsetFactor, r_offsetUnits, RB_DeformTessGeometry(), RB_FogPass(), RB_IterateStagesGeneric(), RB_OutlinesPass(), setArraysOnce, SS_OPAQUE, SURF_NODLIGHT, SURF_SKY, tess, and va().
Referenced by ComputeStageIteratorFunc(), R_ShaderList_f(), and RB_StageIteratorSky().
RB_StageIteratorLightmappedMultitexture()
void RB_StageIteratorLightmappedMultitexture (void)
Definition at line 1529 of file tr_shade.c.
{
     shaderCommands_t *input;
     shader_t        *shader;
     input = &tess;
     shader = input->shader;
     //
     // log this call
     //
     if ( r_logFile->integer ) {
         // don't just call LogComment, or we will get
         // a call to va() every frame!
         GLimp_LogComment( va("--- RB_StageIteratorLightmappedMultitexture( %s ) ---\n", tess.shader->name) );
     }
     //
     // set face culling appropriately
     //
     GL_Cull( shader->cullType );
     //
     // set color, pointers, and lock
     //
     GL_State( GLS_DEFAULT );
     qglVertexPointer( 3, GL_FLOAT, 16, input->xyz );
 #ifdef REPLACE_MODE
     qglDisableClientState( GL_COLOR_ARRAY );
     qglColor3f( 1, 1, 1 );
     qglShadeModel( GL_FLAT );
 #else
     qglEnableClientState( GL_COLOR_ARRAY );
     qglColorPointer( 4, GL_UNSIGNED_BYTE, 0, tess.constantColor255 );
 #endif
     //
     // select base stage
     //
     GL_SelectTexture( 0 );
     qglEnableClientState( GL_TEXTURE_COORD_ARRAY );
     R_BindAnimatedImage( &tess.xstages[0]->bundle[0] );
     qglTexCoordPointer( 2, GL_FLOAT, 16, tess.texCoords[0][0] );
     //
     // configure second stage
     //
     GL_SelectTexture( 1 );
     qglEnable( GL_TEXTURE_2D );
     if ( r_lightmap->integer ) {
         GL_TexEnv( GL_REPLACE );
     } else {
         GL_TexEnv( GL_MODULATE );
     }
     R_BindAnimatedImage( &tess.xstages[0]->bundle[1] );
     qglEnableClientState( GL_TEXTURE_COORD_ARRAY );
     qglTexCoordPointer( 2, GL_FLOAT, 16, tess.texCoords[0][1] );
     //
     // lock arrays
     //
     if ( qglLockArraysEXT ) {
         qglLockArraysEXT(0, input->numVertexes);
         GLimp_LogComment( "glLockArraysEXT\n" );
     }
     R_DrawElements( input->numIndexes, input->indexes );
     //
     // disable texturing on TEXTURE1, then select TEXTURE0
     //
     qglDisable( GL_TEXTURE_2D );
     qglDisableClientState( GL_TEXTURE_COORD_ARRAY );
     GL_SelectTexture( 0 );
 #ifdef REPLACE_MODE
     GL_TexEnv( GL_MODULATE );
     qglShadeModel( GL_SMOOTH );
 #endif
     //
     // now do any dynamic lighting needed
     //
     if ( tess.dlightBits && tess.shader->sort <= SS_OPAQUE ) {
         ProjectDlightTexture();
     }
     // <-- RiO_Outlines: now do outlines
     RB_OutlinesPass();
     // -->
     //
     // now do fog
     //
     if ( tess.fogNum && tess.shader->fogPass ) {
         RB_FogPass();
     }
     //
     // unlock arrays
     //
     if ( qglUnlockArraysEXT ) {
         qglUnlockArraysEXT();
         GLimp_LogComment( "glUnlockArraysEXT\n" );
     }
 }
References GL_Cull(), GL_SelectTexture(), GL_State(), GL_TexEnv(), GLimp_LogComment(), GLS_DEFAULT, ProjectDlightTexture(), qglColor3f, qglColorPointer, qglDisable, qglDisableClientState, qglEnable, qglEnableClientState, qglLockArraysEXT, qglShadeModel, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, R_BindAnimatedImage(), R_DrawElements(), r_lightmap, r_logFile, RB_FogPass(), RB_OutlinesPass(), SS_OPAQUE, tess, and va().
Referenced by ComputeStageIteratorFunc(), and R_ShaderList_f().
RB_StageIteratorVertexLitTexture()
void RB_StageIteratorVertexLitTexture (void)
Definition at line 1447 of file tr_shade.c.
 {
     shaderCommands_t *input;
     shader_t        *shader;
     input = &tess;
     shader = input->shader;
     //
     // compute colors
     //
     RB_CalcDiffuseColor( ( unsigned char * ) tess.svars.colors );
     //
     // log this call
     //
     if ( r_logFile->integer )
     {
         // don't just call LogComment, or we will get
         // a call to va() every frame!
         GLimp_LogComment( va("--- RB_StageIteratorVertexLitTexturedUnfogged( %s ) ---\n", tess.shader->name) );
     }
     //
     // set face culling appropriately
     //
     GL_Cull( shader->cullType );
     //
     // set arrays and lock
     //
     qglEnableClientState( GL_COLOR_ARRAY);
     qglEnableClientState( GL_TEXTURE_COORD_ARRAY);
     qglColorPointer( 4, GL_UNSIGNED_BYTE, 0, tess.svars.colors );
     qglTexCoordPointer( 2, GL_FLOAT, 16, tess.texCoords[0][0] );
     qglVertexPointer (3, GL_FLOAT, 16, input->xyz);
     if ( qglLockArraysEXT )
     {
         qglLockArraysEXT(0, input->numVertexes);
         GLimp_LogComment( "glLockArraysEXT\n" );
     }
     //
     // call special shade routine
     //
     R_BindAnimatedImage( &tess.xstages[0]->bundle[0] );
     GL_State( tess.xstages[0]->stateBits );
     R_DrawElements( input->numIndexes, input->indexes );
     //
     // now do any dynamic lighting needed
     //
     if ( tess.dlightBits && tess.shader->sort <= SS_OPAQUE ) {
         ProjectDlightTexture();
     }
     // <-- RiO_Outlines: now do outlines
     RB_OutlinesPass();
     // -->
     //
     // now do fog
     //
     if ( tess.fogNum && tess.shader->fogPass ) {
         RB_FogPass();
     }
     //
     // unlock arrays
     //
     if (qglUnlockArraysEXT)
     {
         qglUnlockArraysEXT();
         GLimp_LogComment( "glUnlockArraysEXT\n" );
     }
 }
References GL_Cull(), GL_State(), GLimp_LogComment(), ProjectDlightTexture(), qglColorPointer, qglEnableClientState, qglLockArraysEXT, qglTexCoordPointer, qglUnlockArraysEXT, qglVertexPointer, R_BindAnimatedImage(), R_DrawElements(), r_logFile, RB_CalcDiffuseColor(), RB_FogPass(), RB_OutlinesPass(), SS_OPAQUE, tess, and va().
Referenced by ComputeStageIteratorFunc(), and R_ShaderList_f().
Variable Documentation
c_begins
int c_begins static
Definition at line 61 of file tr_shade.c.
Referenced by R_DrawStripElements().
c_vertexes
int c_vertexes static
Definition at line 60 of file tr_shade.c.
Referenced by R_DrawStripElements().
setArraysOnce
qboolean setArraysOnce static
Definition at line 212 of file tr_shade.c.
Referenced by RB_IterateStagesGeneric(), and RB_StageIteratorGeneric().
tess
shaderCommands_t tess
Definition at line 211 of file tr_shade.c.
Referenced by Autosprite2Deform(), AutospriteDeform(), DeformText(), DoRailCore(), DoRailDiscs(), FillCloudySkySide(), LerpMeshVertexes_scalar(), R_BuildCloudData(), R_Init(), R_RenderShadowEdges(), RB_AddQuadStampExt(), RB_CalcAlphaFromEntity(), RB_CalcAlphaFromOneMinusEntity(), RB_CalcBulgeVertexes(), RB_CalcColorFromEntity(), RB_CalcColorFromOneMinusEntity(), RB_CalcDeformNormals(), RB_CalcDeformVertexes(), RB_CalcDiffuseColor_scalar(), RB_CalcDynamicColor(), RB_CalcEnvironmentCelShadeTexCoords(), RB_CalcEnvironmentTexCoords(), RB_CalcFogTexCoords(), RB_CalcHazeTexCoords(), RB_CalcModulateAlphasByFog(), RB_CalcModulateColorsByFog(), RB_CalcModulateRGBAsByFog(), RB_CalcMoveVertexes(), RB_CalcRotateTexCoords(), RB_CalcScaleTexCoords(), RB_CalcScrollTexCoords(), RB_CalcSpecularAlpha(), RB_CalcTransformTexCoords(), RB_CalcTurbulentTexCoords(), RB_CalcUniformColor(), RB_CalcWaveAlpha(), RB_CalcWaveColor(), RB_CheckOverflow(), RB_ClearDepth(), RB_DeformTessGeometry(), RB_DrawSun(), RB_DrawSurfs(), RB_IQMSurfaceAnim(), RB_MDM_SurfaceAnim(), RB_ProjectionShadowDeform(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_ShadowTessEnd(), RB_StageIteratorSky(), RB_StretchPic(), RB_SurfaceFace(), RB_SurfaceFlare(), RB_SurfaceGrid(), RB_SurfaceMesh(), RB_SurfacePolychain(), RB_SurfaceTriangles(), RB_SwapBuffers(), SurfIsOffscreen(), and TableForFunc().