ZEQ2-Lite: Tools/MinGW/include/sys/time.h File Reference
time.h File Reference
#include <time.h>
Data Structures
struct LPTIMEVAL
struct timezone
Macros
#define _TIMEVAL_DEFINED
#define timerclear(tvp) (tvp)->tv_sec = (tvp)->tv_usec = 0
#define timercmp(tvp, uvp, cmp)
#define timerisset(tvp) ((tvp)->tv_sec || (tvp)->tv_usec)
Functions
int __cdecl __MINGW_NOTHROW gettimeofday (struct timeval *__restrict__, void *__restrict__)
Macro Definition Documentation
_TIMEVAL_DEFINED
#define _TIMEVAL_DEFINED
Definition at line 10 of file time.h.
timerclear
#define timerclear (tvp) (tvp)->tv_sec = (tvp)->tv_usec = 0
Definition at line 20 of file time.h.
timercmp
#define timercmp (tvp, uvp, cmp)
Value:
    (((tvp)->tv_sec != (uvp)->tv_sec) ? \
    ((tvp)->tv_sec cmp (uvp)->tv_sec) : \
    ((tvp)->tv_usec cmp (uvp)->tv_usec))
Definition at line 16 of file time.h.
timerisset
#define timerisset (tvp) ((tvp)->tv_sec || (tvp)->tv_usec)
Definition at line 15 of file time.h.
Function Documentation
gettimeofday()
int __cdecl __MINGW_NOTHROW gettimeofday (struct timeval * __restrict__, void * __restrict__)
Referenced by GetTickCount(), I_FloatTime(), Sys_Milliseconds(), and VM_Compile().