ZEQ2-Lite: Engine/libspeex/testdenoise.c File Reference
testdenoise.c File Reference
#include <speex/speex_preprocess.h>
#include <stdio.h>
Macros
#define NN 160
Functions
int main ()
Macro Definition Documentation
NN
#define NN 160
Definition at line 8 of file testdenoise.c.
Function Documentation
main()
int main ()
Definition at line 10 of file testdenoise.c.
 {
    short in[NN];
    int i;
    SpeexPreprocessState *st;
    int count=0;
    float f;
    st = speex_preprocess_state_init(NN, 8000);
    i=1;
    speex_preprocess_ctl(st, SPEEX_PREPROCESS_SET_DENOISE, &i);
    i=0;
    speex_preprocess_ctl(st, SPEEX_PREPROCESS_SET_AGC, &i);
    f=8000;
    speex_preprocess_ctl(st, SPEEX_PREPROCESS_SET_AGC_LEVEL, &f);
    i=0;
    speex_preprocess_ctl(st, SPEEX_PREPROCESS_SET_DEREVERB, &i);
    f=.0;
    speex_preprocess_ctl(st, SPEEX_PREPROCESS_SET_DEREVERB_DECAY, &f);
    f=.0;
    speex_preprocess_ctl(st, SPEEX_PREPROCESS_SET_DEREVERB_LEVEL, &f);
    while (1)
    {
       int vad;
       fread(in, sizeof(short), NN, stdin);
       if (feof(stdin))
          break;
       vad = speex_preprocess_run(st, in);
       /*fprintf (stderr, "%d\n", vad);*/
       fwrite(in, sizeof(short), NN, stdout);
       count++;
    }
    speex_preprocess_state_destroy(st);
    return 0;
 }
References fread(), fwrite(), NN, speex_preprocess_ctl(), speex_preprocess_run(), SPEEX_PREPROCESS_SET_AGC, SPEEX_PREPROCESS_SET_AGC_LEVEL, SPEEX_PREPROCESS_SET_DENOISE, SPEEX_PREPROCESS_SET_DEREVERB, SPEEX_PREPROCESS_SET_DEREVERB_DECAY, SPEEX_PREPROCESS_SET_DEREVERB_LEVEL, speex_preprocess_state_destroy(), and speex_preprocess_state_init().