ZEQ2-Lite: Tools/zMesh Exporter/mathlib.h File Reference
mathlib.h File Reference
#include <math.h>
Macros
#define DEG2RAD(a) (((a) * Q_PI) / 180.0F)
#define DotProduct(x, y) (x[0]*y[0]+x[1]*y[1]+x[2]*y[2])
#define EQUAL_EPSILON 0.001
#define Q_PI 3.14159265358979323846
#define RAD2DEG(a) (((a) * 180.0f) / Q_PI)
#define VectorAdd(a, b, c) {c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];}
#define VectorClear(x) {x[0] = x[1] = x[2] = 0;}
#define VectorCopy(a, b) {b[0]=a[0];b[1]=a[1];b[2]=a[2];}
#define VectorNegate(x) {x[0]=-x[0];x[1]=-x[1];x[2]=-x[2];}
#define VectorScale(a, b, c) {c[0]=b*a[0];c[1]=b*a[1];c[2]=b*a[2];}
#define VectorSubtract(a, b, c) {c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];}
Typedefs
typedef vec_t vec2_t[3]
typedef vec_t vec3_t[3]
typedef vec_t vec4_t[4]
typedef float vec_t
Functions
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
void AnglesToMatrix (vec3_t in, vec3_t out[3])
void ClearBounds (vec3_t mins, vec3_t maxs)
vec_t ColorNormalize (const vec3_t in, vec3_t out)
void CrossProduct (const vec3_t v1, const vec3_t v2, vec3_t cross)
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
vec_t Q_rint (vec_t in)
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
qboolean VectorCompare (const vec3_t v1, const vec3_t v2)
void VectorInverseRotate (vec3_t v, float r[3][3], vec3_t d)
double VectorLength (const vec3_t v)
void VectorMA (const vec3_t va, double scale, const vec3_t vb, vec3_t vc)
vec_t VectorNormalize (const vec3_t in, vec3_t out)
void VectorRotate (vec3_t v, float r[3][3], vec3_t d)
Variables
vec3_t vec3_origin
Macro Definition Documentation
DEG2RAD
#define DEG2RAD (a) (((a) * Q_PI) / 180.0F)
Definition at line 39 of file mathlib.h.
DotProduct
#define DotProduct (x, y) (x[0]*y[0]+x[1]*y[1]+x[2]*y[2])
Definition at line 46 of file mathlib.h.
EQUAL_EPSILON
#define EQUAL_EPSILON 0.001
Definition at line 44 of file mathlib.h.
Q_PI
#define Q_PI 3.14159265358979323846
Definition at line 38 of file mathlib.h.
RAD2DEG
#define RAD2DEG (a) (((a) * 180.0f) / Q_PI)
Definition at line 40 of file mathlib.h.
VectorAdd
#define VectorAdd (a, b, c) {c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];}
Definition at line 48 of file mathlib.h.
VectorClear
#define VectorClear (x) {x[0] = x[1] = x[2] = 0;}
Definition at line 51 of file mathlib.h.
VectorCopy
#define VectorCopy (a, b) {b[0]=a[0];b[1]=a[1];b[2]=a[2];}
Definition at line 49 of file mathlib.h.
VectorNegate
#define VectorNegate (x) {x[0]=-x[0];x[1]=-x[1];x[2]=-x[2];}
Definition at line 52 of file mathlib.h.
VectorScale
#define VectorScale (a, b, c) {c[0]=b*a[0];c[1]=b*a[1];c[2]=b*a[2];}
Definition at line 50 of file mathlib.h.
VectorSubtract
#define VectorSubtract (a, b, c) {c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];}
Definition at line 47 of file mathlib.h.
Typedef Documentation
vec2_t
typedef vec_t vec2_t[3]
Definition at line 34 of file mathlib.h.
vec3_t
typedef vec_t vec3_t[3]
Definition at line 35 of file mathlib.h.
vec4_t
typedef vec_t vec4_t[4]
Definition at line 36 of file mathlib.h.
vec_t
typedef float vec_t
Definition at line 32 of file mathlib.h.
Function Documentation
AddPointToBounds()
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 798 of file q_math.c.
{
     if ( v[0] < mins[0] ) {
         mins[0] = v[0];
     }
     if ( v[0] > maxs[0]) {
         maxs[0] = v[0];
     }
     if ( v[1] < mins[1] ) {
         mins[1] = v[1];
     }
     if ( v[1] > maxs[1]) {
         maxs[1] = v[1];
     }
     if ( v[2] < mins[2] ) {
         mins[2] = v[2];
     }
     if ( v[2] > maxs[2]) {
         maxs[2] = v[2];
     }
 }
References val.
AnglesToMatrix()
void AnglesToMatrix (vec3_t in, vec3_t out[3])
Definition at line 59 of file mathlib.c.
{
     vec_t sr, sp, sy, cr, cp, cy;
     sy = sin(in[2]);
     cy = cos(in[2]);
     sp = sin(in[1]);
     cp = cos(in[1]);
     sr = sin(in[0]);
     cr = cos(in[0]);
     out[0][0] = cp*cy;
     out[1][0] = cp*sy;
     out[2][0] = -sp;
     out[0][1] = sr*sp*cy+cr*-sy;
     out[1][1] = sr*sp*sy+cr*cy;
     out[2][1] = sr*cp;
     out[0][2] = (cr*sp*cy+-sr*-sy);
     out[1][2] = (cr*sp*sy+-sr*cy);
     out[2][2] = cr*cp;
 }
References cos(), cp, cr, cy, out, sin(), sp, sr, and sy.
Referenced by LoadSMD_ParseSkeleton().
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 793 of file q_math.c.
{
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
ColorNormalize()
vec_t ColorNormalize (const vec3_t in, vec3_t out)
Definition at line 191 of file mathlib.c.
{
     float   max, scale;
     max = in[0];
     if (in[1] > max)
         max = in[1];
     if (in[2] > max)
         max = in[2];
     if (max == 0) {
         out[0] = out[1] = out[2] = 1.0;
         return 0;
     }
     scale = 1.0 / max;
     VectorScale (in, scale, out);
     return max;
 }
References max, out, and VectorScale.
CrossProduct()
void CrossProduct (const vec3_t v1, const vec3_t v2, vec3_t cross)
Definition at line 168 of file mathlib.c.
{
     cross[0] = v1[1]*v2[2] - v1[2]*v2[1];
     cross[1] = v1[2]*v2[0] - v1[0]*v2[2];
     cross[2] = v1[0]*v2[1] - v1[1]*v2[0];
 }
Referenced by MakeNormalVectors(), and RotatePointAroundVector().
MatrixMultiply()
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
Definition at line 1121 of file q_math.c.
{
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] +
                 in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] +
                 in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] +
                 in1[0][2] * in2[2][2];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] +
                 in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] +
                 in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] +
                 in1[1][2] * in2[2][2];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] +
                 in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] +
                 in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] +
                 in1[2][2] * in2[2][2];
 }
References out.
Referenced by CG_AddPlayerWeapon(), CG_GetTagOrientation(), CG_GetTagOrientationFromPlayerEntityCameraModel(), CG_GetTagOrientationFromPlayerEntityHeadModel(), CG_GetTagOrientationFromPlayerEntityLegsModel(), CG_GetTagOrientationFromPlayerEntityTorsoModel(), CG_PositionEntityOnTag(), CG_PositionRotatedEntityOnTag(), LoadSMD_ParseSkeleton(), RotatePointAroundVector(), SV_GameSystemCalls(), UI_PositionEntityOnTag(), and UI_PositionRotatedEntityOnTag().
Q_rint()
vec_t Q_rint (vec_t in)
Definition at line 158 of file mathlib.c.
{
     return floor (in + 0.5);
 }
References floor().
RadiusFromBounds()
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
Definition at line 778 of file q_math.c.
{
     int     i;
     vec3_t  corner;
     float   a, b;
     for (i=0 ; i<3 ; i++) {
         a = fabs( mins[i] );
         b = fabs( maxs[i] );
         corner[i] = a > b ? a : b;
     }
     return VectorLength (corner);
 }
References fabs(), and VectorLength().
Referenced by FixCoords(), G_MoverPush(), R_ComputeLOD(), and SV_LinkEntity().
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 291 of file q_math.c.
{
     float   m[3][3];
     float   im[3][3];
     float   zrot[3][3];
     float   tmpmat[3][3];
     float   rot[3][3];
     int i;
     vec3_t vr, vup, vf;
     float   rad;
     vf[0] = dir[0];
     vf[1] = dir[1];
     vf[2] = dir[2];
     PerpendicularVector( vr, dir );
     CrossProduct( vr, vf, vup );
     m[0][0] = vr[0];
     m[1][0] = vr[1];
     m[2][0] = vr[2];
     m[0][1] = vup[0];
     m[1][1] = vup[1];
     m[2][1] = vup[2];
     m[0][2] = vf[0];
     m[1][2] = vf[1];
     m[2][2] = vf[2];
     memcpy( im, m, sizeof( im ) );
     im[0][1] = m[1][0];
     im[0][2] = m[2][0];
     im[1][0] = m[0][1];
     im[1][2] = m[2][1];
     im[2][0] = m[0][2];
     im[2][1] = m[1][2];
     memset( zrot, 0, sizeof( zrot ) );
     zrot[0][0] = zrot[1][1] = zrot[2][2] = 1.0F;
     rad = DEG2RAD( degrees );
     zrot[0][0] = cos( rad );
     zrot[0][1] = sin( rad );
     zrot[1][0] = -sin( rad );
     zrot[1][1] = cos( rad );
     MatrixMultiply( m, zrot, tmpmat );
     MatrixMultiply( tmpmat, im, rot );
     for ( i = 0; i < 3; i++ ) {
         dst[i] = rot[i][0] * point[0] + rot[i][1] * point[1] + rot[i][2] * point[2];
     }
 }
References cos(), CrossProduct(), DEG2RAD, dir, m, MatrixMultiply(), memcpy(), memset(), PerpendicularVector(), and sin().
Referenced by CG_DrawRadarBlips(), CG_ImpactMark(), Fire_UserWeapon(), R_GetPortalOrientations(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), and RotateAroundDirection().
VectorCompare()
qboolean VectorCompare (const vec3_t v1, const vec3_t v2)
Definition at line 148 of file mathlib.c.
{
     int     i;
     for (i=0 ; i<3 ; i++)
         if (fabs(v1[i]-v2[i]) > EQUAL_EPSILON)
             return qfalse;
     return qtrue;
 }
References EQUAL_EPSILON, fabs(), qfalse, and qtrue.
VectorInverseRotate()
void VectorInverseRotate (vec3_t v, float r[3][3], vec3_t d)
Definition at line 118 of file mathlib.c.
{
     vec3_t inv[3];
     MatrixInvert(r,inv);
     VectorRotate(v,inv,d);
 }
References MatrixInvert(), and VectorRotate().
Referenced by FixCoords(), LoadSMD_ParseTriangles(), and SaveMesh().
VectorLength()
double VectorLength (const vec3_t v)
Definition at line 136 of file mathlib.c.
{
     int     i;
     double  length;
     length = 0;
     for (i=0 ; i< 3 ; i++)
         length += v[i]*v[i];
     length = sqrt (length);     // FIXME
     return length;
 }
References sqrt().
Referenced by RadiusFromBounds().
VectorMA()
void VectorMA (const vec3_t va, double scale, const vec3_t vb, vec3_t vc)
Definition at line 162 of file mathlib.c.
{
     vc[0] = va[0] + scale*vb[0];
     vc[1] = va[1] + scale*vb[1];
     vc[2] = va[2] + scale*vb[2];
 }
References va().
Referenced by MakeNormalVectors().
VectorNormalize()
vec_t VectorNormalize (const vec3_t in, vec3_t out)
Definition at line 174 of file mathlib.c.
{
     vec_t   length, ilength;
     length = sqrt (in[0]*in[0] + in[1]*in[1] + in[2]*in[2]);
     if (length == 0) {
         VectorClear (out);
         return 0;
     }
     ilength = 1.0/length;
     out[0] = in[0]*ilength;
     out[1] = in[1]*ilength;
     out[2] = in[2]*ilength;
     return length;
 }
References out, sqrt(), and VectorClear.
Referenced by MakeNormalVectors(), and PerpendicularVector().
VectorRotate()
void VectorRotate (vec3_t v, float r[3][3], vec3_t d)
Definition at line 130 of file mathlib.c.
{
     d[0] = v[0] * r[0][0] + v[1] * r[0][1] + v[2] * r[0][2];
     d[1] = v[0] * r[1][0] + v[1] * r[1][1] + v[2] * r[1][2];
     d[2] = v[0] * r[2][0] + v[1] * r[2][1] + v[2] * r[2][2];
 }
Referenced by VectorInverseRotate().
Variable Documentation
vec3_origin
vec3_t vec3_origin
Definition at line 34 of file q_math.c.
Referenced by AnglesToAxis(), and ByteToDir().