ZEQ2-Lite: Graphics Class Reference
Graphics Class Reference
#include <gdiplusgraphics.h>
Public Member Functions
Graphics (HDC hdc)
Graphics (HDC hdc, HANDLE hdevice)
Graphics (HWND hwnd, BOOL icm=FALSE)
Graphics (Image *image)
~Graphics ()
Status AddMetafileComment (const BYTE *data, UINT sizeData)
GraphicsContainer BeginContainer ()
GraphicsContainer BeginContainer (const Rect &dstrect, const Rect &srcrect, Unit unit)
GraphicsContainer BeginContainer (const RectF &dstrect, const RectF &srcrect, Unit unit)
Status Clear (const Color &color)
Status DrawArc (const Pen *pen, const Rect &rect, REAL startAngle, REAL sweepAngle)
Status DrawArc (const Pen *pen, const RectF &rect, REAL startAngle, REAL sweepAngle)
Status DrawArc (const Pen *pen, INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle)
Status DrawArc (const Pen *pen, REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle)
Status DrawBezier (const Pen *pen, const Point &pt1, const Point &pt2, const Point &pt3, const Point &pt4)
Status DrawBezier (const Pen *pen, const PointF &pt1, const PointF &pt2, const PointF &pt3, const PointF &pt4)
Status DrawBezier (const Pen *pen, INT x1, INT y1, INT x2, INT y2, INT x3, INT y3, INT x4, INT y4)
Status DrawBezier (const Pen *pen, REAL x1, REAL y1, REAL x2, REAL y2, REAL x3, REAL y3, REAL x4, REAL y4)
Status DrawBeziers (const Pen *pen, const Point *points, INT count)
Status DrawBeziers (const Pen *pen, const PointF *points, INT count)
Status DrawCachedBitmap (CachedBitmap *cb, INT x, INT y)
Status DrawClosedCurve (const Pen *pen, const Point *points, INT count)
Status DrawClosedCurve (const Pen *pen, const Point *points, INT count, REAL tension)
Status DrawClosedCurve (const Pen *pen, const PointF *points, INT count)
Status DrawClosedCurve (const Pen *pen, const PointF *points, INT count, REAL tension)
Status DrawCurve (const Pen *pen, const Point *points, INT count)
Status DrawCurve (const Pen *pen, const Point *points, INT count, INT offset, INT numberOfSegments, REAL tension)
Status DrawCurve (const Pen *pen, const Point *points, INT count, REAL tension)
Status DrawCurve (const Pen *pen, const PointF *points, INT count)
Status DrawCurve (const Pen *pen, const PointF *points, INT count, INT offset, INT numberOfSegments, REAL tension)
Status DrawCurve (const Pen *pen, const PointF *points, INT count, REAL tension)
Status DrawDriverString (const UINT16 *text, INT length, const Font *font, const Brush *brush, const PointF *positions, INT flags, const Matrix *matrix)
Status DrawEllipse (const Pen *pen, const Rect &rect)
Status DrawEllipse (const Pen *pen, const RectF &rect)
Status DrawEllipse (const Pen *pen, INT x, INT y, INT width, INT height)
Status DrawEllipse (const Pen *pen, REAL x, REAL y, REAL width, REAL height)
Status DrawImage (Image *image, const Point &point)
Status DrawImage (Image *image, const Point *destPoints, INT count)
Status DrawImage (Image *image, const Point *destPoints, INT count, INT srcx, INT srcy, INT srcwidth, INT srcheight, Unit srcUnit, const ImageAttributes *imageAttributes=NULL, DrawImageAbort callback=NULL, VOID *callbackData=NULL)
Status DrawImage (Image *image, const PointF &point)
Status DrawImage (Image *image, const PointF *destPoints, INT count)
Status DrawImage (Image *image, const PointF *destPoints, INT count, REAL srcx, REAL srcy, REAL srcwidth, REAL srcheight, Unit srcUnit, const ImageAttributes *imageAttributes=NULL, DrawImageAbort callback=NULL, VOID *callbackData=NULL)
Status DrawImage (Image *image, const Rect &destRect, INT srcx, INT srcy, INT srcwidth, INT srcheight, Unit srcUnit, const ImageAttributes *imageAttributes=NULL, DrawImageAbort callback=NULL, VOID *callbackData=NULL)
Status DrawImage (Image *image, const Rect &rect)
Status DrawImage (Image *image, const RectF &destRect, const RectF &sourceRect, Unit srcUnit, const ImageAttributes *imageAttributes=NULL)
Status DrawImage (Image *image, const RectF &destRect, REAL srcx, REAL srcy, REAL srcwidth, REAL srcheight, Unit srcUnit, const ImageAttributes *imageAttributes=NULL, DrawImageAbort callback=NULL, VOID *callbackData=NULL)
Status DrawImage (Image *image, const RectF &rect)
Status DrawImage (Image *image, INT x, INT y)
Status DrawImage (Image *image, INT x, INT y, INT srcx, INT srcy, INT srcwidth, INT srcheight, Unit srcUnit)
Status DrawImage (Image *image, INT x, INT y, INT width, INT height)
Status DrawImage (Image *image, REAL x, REAL y)
Status DrawImage (Image *image, REAL x, REAL y, REAL srcx, REAL srcy, REAL srcwidth, REAL srcheight, Unit srcUnit)
Status DrawImage (Image *image, REAL x, REAL y, REAL width, REAL height)
Status DrawLine (const Pen *pen, const Point &pt1, const Point &pt2)
Status DrawLine (const Pen *pen, const PointF &pt1, const PointF &pt2)
Status DrawLine (const Pen *pen, INT x1, INT y1, INT x2, INT y2)
Status DrawLine (const Pen *pen, REAL x1, REAL y1, REAL x2, REAL y2)
Status DrawLines (const Pen *pen, const Point *points, INT count)
Status DrawLines (const Pen *pen, const PointF *points, INT count)
Status DrawPath (const Pen *pen, const GraphicsPath *path)
Status DrawPie (const Pen *pen, const Rect &rect, REAL startAngle, REAL sweepAngle)
Status DrawPie (const Pen *pen, const RectF &rect, REAL startAngle, REAL sweepAngle)
Status DrawPie (const Pen *pen, INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle)
Status DrawPie (const Pen *pen, REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle)
Status DrawPolygon (const Pen *pen, const Point *points, INT count)
Status DrawPolygon (const Pen *pen, const PointF *points, INT count)
Status DrawRectangle (const Pen *pen, const Rect &rect)
Status DrawRectangle (const Pen *pen, const RectF &rect)
Status DrawRectangle (const Pen *pen, INT x, INT y, INT width, INT height)
Status DrawRectangle (const Pen *pen, REAL x, REAL y, REAL width, REAL height)
Status DrawRectangles (const Pen *pen, const Rect *rects, INT count)
Status DrawRectangles (const Pen *pen, const RectF *rects, INT count)
Status DrawString (const WCHAR *string, INT length, const Font *font, const PointF &origin, const Brush *brush)
Status DrawString (const WCHAR *string, INT length, const Font *font, const PointF &origin, const StringFormat *stringFormat, const Brush *brush)
Status DrawString (const WCHAR *string, INT length, const Font *font, const RectF &layoutRect, const StringFormat *stringFormat, const Brush *brush)
Status EndContainer (GraphicsContainer state)
Status EnumerateMetafile (const Metafile *metafile, const Point &destPoint, const Rect &srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const Point &destPoint, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const Point *destPoints, INT count, const Rect &srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const Point *destPoints, INT count, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const PointF &destPoint, const RectF &srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const PointF &destPoint, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const PointF *destPoints, INT count, const RectF &srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const PointF *destPoints, INT count, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const Rect &destRect, const Rect &srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const Rect &destRect, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const RectF &destRect, const RectF &srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status EnumerateMetafile (const Metafile *metafile, const RectF &destRect, EnumerateMetafileProc callback, VOID *callbackData=NULL, ImageAttributes *imageAttributes=NULL)
Status ExcludeClip (const Rect &rect)
Status ExcludeClip (const RectF &rect)
Status ExcludeClip (const Region *region)
Status FillClosedCurve (const Brush *brush, const Point *points, INT count)
Status FillClosedCurve (const Brush *brush, const Point *points, INT count, FillMode fillMode, REAL tension=0.5f)
Status FillClosedCurve (const Brush *brush, const PointF *points, INT count)
Status FillClosedCurve (const Brush *brush, const PointF *points, INT count, FillMode fillMode, REAL tension=0.5f)
Status FillEllipse (const Brush *brush, const Rect &rect)
Status FillEllipse (const Brush *brush, const RectF &rect)
Status FillEllipse (const Brush *brush, INT x, INT y, INT width, INT height)
Status FillEllipse (const Brush *brush, REAL x, REAL y, REAL width, REAL height)
Status FillPath (const Brush *brush, const GraphicsPath *path)
Status FillPie (const Brush *brush, const Rect &rect, REAL startAngle, REAL sweepAngle)
Status FillPie (const Brush *brush, const RectF &rect, REAL startAngle, REAL sweepAngle)
Status FillPie (const Brush *brush, INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle)
Status FillPie (const Brush *brush, REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle)
Status FillPolygon (const Brush *brush, const Point *points, INT count)
Status FillPolygon (const Brush *brush, const Point *points, INT count, FillMode fillMode)
Status FillPolygon (const Brush *brush, const PointF *points, INT count)
Status FillPolygon (const Brush *brush, const PointF *points, INT count, FillMode fillMode)
Status FillRectangle (const Brush *brush, const Rect &rect)
Status FillRectangle (const Brush *brush, const RectF &rect)
Status FillRectangle (const Brush *brush, INT x, INT y, INT width, INT height)
Status FillRectangle (const Brush *brush, REAL x, REAL y, REAL width, REAL height)
Status FillRectangles (const Brush *brush, const Rect *rects, INT count)
Status FillRectangles (const Brush *brush, const RectF *rects, INT count)
Status FillRegion (const Brush *brush, const Region *region)
VOID Flush (FlushIntention intention=FlushIntentionFlush)
Status GetClip (Region *region) const
Status GetClipBounds (Rect *rect) const
Status GetClipBounds (RectF *rect) const
CompositingMode GetCompositingMode () const
CompositingQuality GetCompositingQuality () const
REAL GetDpiX () const
REAL GetDpiY () const
HDC GetHDC ()
InterpolationMode GetInterpolationMode () const
Status GetLastStatus () const
Status GetNearestColor (Color *color) const
REAL GetPageScale () const
Unit GetPageUnit () const
PixelOffsetMode GetPixelOffsetMode () const
Status GetRenderingOrigin (INT *x, INT *y) const
SmoothingMode GetSmoothingMode () const
UINT GetTextContrast () const
TextRenderingHint GetTextRenderingHint () const
Status GetTransform (Matrix *matrix) const
Status GetVisibleClipBounds (Rect *rect) const
Status GetVisibleClipBounds (RectF *rect) const
Status IntersectClip (const Rect &rect)
Status IntersectClip (const RectF &rect)
Status IntersectClip (const Region *region)
BOOL IsClipEmpty () const
BOOL IsVisible (const Point &point) const
BOOL IsVisible (const PointF &point) const
BOOL IsVisible (const Rect &rect) const
BOOL IsVisible (const RectF &rect) const
BOOL IsVisible (INT x, INT y) const
BOOL IsVisible (INT x, INT y, INT width, INT height) const
BOOL IsVisible (REAL x, REAL y) const
BOOL IsVisible (REAL x, REAL y, REAL width, REAL height) const
BOOL IsVisibleClipEmpty () const
Status MeasureCharacterRanges (const WCHAR *string, INT length, const Font *font, const RectF &layoutRect, const StringFormat *stringFormat, INT regionCount, Region *regions) const
Status MeasureDriverString (const UINT16 *text, INT length, const Font *font, const PointF *positions, INT flags, const Matrix *matrix, RectF *boundingBox) const
Status MeasureString (const WCHAR *string, INT length, const Font *font, const PointF &origin, const StringFormat *stringFormat, RectF *boundingBox) const
Status MeasureString (const WCHAR *string, INT length, const Font *font, const PointF &origin, RectF *boundingBox) const
Status MeasureString (const WCHAR *string, INT length, const Font *font, const RectF &layoutRect, const StringFormat *stringFormat, RectF *boundingBox, INT *codepointsFitted=NULL, INT *linesFitted=NULL) const
Status MeasureString (const WCHAR *string, INT length, const Font *font, const RectF &layoutRect, RectF *boundingBox) const
Status MeasureString (const WCHAR *string, INT length, const Font *font, const SizeF &layoutRectSize, const StringFormat *stringFormat, SizeF *size, INT *codepointsFitted=NULL, INT *linesFitted=NULL) const
Status MultiplyTransform (const Matrix *matrix, MatrixOrder order=MatrixOrderPrepend)
VOID ReleaseHDC (HDC hdc)
Status ResetClip ()
Status ResetTransform ()
Status Restore (GraphicsState state)
Status RotateTransform (REAL angle, MatrixOrder order=MatrixOrderPrepend)
GraphicsState Save () const
Status ScaleTransform (REAL sx, REAL sy, MatrixOrder order=MatrixOrderPrepend)
VOID SetAbort ()
Status SetClip (const Graphics *g, CombineMode combineMode=CombineModeReplace)
Status SetClip (const GraphicsPath *path, CombineMode combineMode=CombineModeReplace)
Status SetClip (const Rect &rect, CombineMode combineMode=CombineModeReplace)
Status SetClip (const RectF &rect, CombineMode combineMode=CombineModeReplace)
Status SetClip (const Region *region, CombineMode combineMode=CombineModeReplace)
Status SetClip (HRGN hRgn, CombineMode combineMode=CombineModeReplace)
Status SetCompositingMode (CompositingMode compositingMode)
Status SetCompositingQuality (CompositingQuality compositingQuality)
Status SetInterpolationMode (InterpolationMode interpolationMode)
Status SetPageScale (REAL scale)
Status SetPageUnit (Unit unit)
Status SetPixelOffsetMode (PixelOffsetMode pixelOffsetMode)
Status SetRenderingOrigin (INT x, INT y)
Status SetSmoothingMode (SmoothingMode smoothingMode)
Status SetTextContrast (UINT contrast)
Status SetTextRenderingHint (TextRenderingHint textRenderingHint)
Status SetTransform (const Matrix *matrix)
Status TransformPoints (CoordinateSpace destSpace, CoordinateSpace srcSpace, Point *pts, INT count) const
Status TransformPoints (CoordinateSpace destSpace, CoordinateSpace srcSpace, PointF *pts, INT count) const
Status TranslateClip (INT dx, INT dy)
Status TranslateClip (REAL dx, REAL dy)
Status TranslateTransform (REAL dx, REAL dy, MatrixOrder order=MatrixOrderPrepend)
Static Public Member Functions
static Graphics * FromHDC (HDC hdc)
static Graphics * FromHDC (HDC hdc, HANDLE hdevice)
static Graphics * FromHWND (HWND hwnd, BOOL icm=FALSE)
static Graphics * FromImage (Image *image)
static HPALETTE GetHalftonePalette ()
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
Graphics (const Graphics &)
Graphics & operator= (const Graphics &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpGraphics * nativeGraphics
Friends
class Bitmap
class CachedBitmap
class Font
class GraphicsPath
class Metafile
class Region
Detailed Description
Definition at line 33 of file gdiplusgraphics.h.
Constructor & Destructor Documentation
Graphics() [1/5]
Graphics::Graphics (Image * image) inline
Definition at line 64 of file gdiplusgraphics.h.
                           : nativeGraphics(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipGetImageGraphicsContext(
                 image ? image->nativeImage : NULL,
                 &nativeGraphics);
     }
References GdipGetImageGraphicsContext(), lastStatus, nativeGraphics, and NULL.
Referenced by FromHDC(), FromHWND(), and FromImage().
Graphics() [2/5]
Graphics::Graphics (HDC hdc) inline
Definition at line 70 of file gdiplusgraphics.h.
                      : nativeGraphics(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreateFromHDC(
                 hdc, &nativeGraphics);
     }
References GdipCreateFromHDC(), lastStatus, and nativeGraphics.
Graphics() [3/5]
Graphics::Graphics (HDC hdc, HANDLE hdevice) inline
Definition at line 75 of file gdiplusgraphics.h.
                                      : nativeGraphics(NULL), lastStatus(Ok)
     {
         lastStatus = DllExports::GdipCreateFromHDC2(
                 hdc, hdevice, &nativeGraphics);
     }
References GdipCreateFromHDC2(), lastStatus, and nativeGraphics.
Graphics() [4/5]
Graphics::Graphics (HWND hwnd, BOOL icm = FALSE) inline
Definition at line 80 of file gdiplusgraphics.h.
                                          :
         nativeGraphics(NULL), lastStatus(Ok)
     {
         if (icm) {
             lastStatus = DllExports::GdipCreateFromHWNDICM(
                     hwnd, &nativeGraphics);
         } else {
             lastStatus = DllExports::GdipCreateFromHWND(
                     hwnd, &nativeGraphics);
         }
     }
References GdipCreateFromHWND(), GdipCreateFromHWNDICM(), lastStatus, and nativeGraphics.
~Graphics()
Graphics::~Graphics () inline
Definition at line 91 of file gdiplusgraphics.h.
     {
         DllExports::GdipDeleteGraphics(nativeGraphics);
     }
References GdipDeleteGraphics(), and nativeGraphics.
Graphics() [5/5]
Graphics::Graphics (const Graphics &) private
Member Function Documentation
AddMetafileComment()
Status Graphics::AddMetafileComment (const BYTE * data, UINT sizeData) inline
Definition at line 96 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipComment(
                 nativeGraphics, sizeData, data));
     }
References GdipComment(), nativeGraphics, and updateStatus().
BeginContainer() [1/3]
GraphicsContainer Graphics::BeginContainer () inline
Definition at line 101 of file gdiplusgraphics.h.
     {
         GraphicsContainer result = 0;
         updateStatus(DllExports::GdipBeginContainer2(
                 nativeGraphics, &result));
         return result;
     }
References GdipBeginContainer2(), nativeGraphics, and updateStatus().
BeginContainer() [2/3]
GraphicsContainer Graphics::BeginContainer (const Rect & dstrect, const Rect & srcrect, Unit unit) inline
Definition at line 117 of file gdiplusgraphics.h.
     {
         GraphicsContainer result = 0;
         updateStatus(DllExports::GdipBeginContainerI(
                 nativeGraphics, &dstrect, &srcrect, unit,
                 &result));
         return result;
     }
References GdipBeginContainerI(), nativeGraphics, and updateStatus().
BeginContainer() [3/3]
GraphicsContainer Graphics::BeginContainer (const RectF & dstrect, const RectF & srcrect, Unit unit) inline
Definition at line 108 of file gdiplusgraphics.h.
     {
         GraphicsContainer result = 0;
         updateStatus(DllExports::GdipBeginContainer(
                 nativeGraphics, &dstrect, &srcrect, unit,
                 &result));
         return result;
     }
References GdipBeginContainer(), nativeGraphics, and updateStatus().
Clear()
Status Graphics::Clear (const Color & color) inline
Definition at line 126 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGraphicsClear(
                 nativeGraphics, color.GetValue()));
     }
References GdipGraphicsClear(), nativeGraphics, and updateStatus().
DrawArc() [1/4]
Status Graphics::DrawArc (const Pen * pen, const Rect & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 153 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawArcI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipDrawArcI(), Rect::Height, nativeGraphics, Pen::nativePen, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
DrawArc() [2/4]
Status Graphics::DrawArc (const Pen * pen, const RectF & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 145 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawArc(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipDrawArc(), RectF::Height, nativeGraphics, Pen::nativePen, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
DrawArc() [3/4]
Status Graphics::DrawArc (const Pen * pen, INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle) inline
Definition at line 138 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawArcI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipDrawArcI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawArc() [4/4]
Status Graphics::DrawArc (const Pen * pen, REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle) inline
Definition at line 131 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawArc(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipDrawArc(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawBezier() [1/4]
Status Graphics::DrawBezier (const Pen * pen, const Point & pt1, const Point & pt2, const Point & pt3, const Point & pt4) inline
Definition at line 186 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawBezierI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 pt1.X, pt1.Y, pt2.X, pt2.Y,
                 pt3.X, pt3.Y, pt4.X, pt4.Y));
     }
References GdipDrawBezierI(), nativeGraphics, Pen::nativePen, NULL, updateStatus(), Point::X, and Point::Y.
DrawBezier() [2/4]
Status Graphics::DrawBezier (const Pen * pen, const PointF & pt1, const PointF & pt2, const PointF & pt3, const PointF & pt4) inline
Definition at line 177 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawBezier(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 pt1.X, pt1.Y, pt2.X, pt2.Y,
                 pt3.X, pt3.Y, pt4.X, pt4.Y));
     }
References GdipDrawBezier(), nativeGraphics, Pen::nativePen, NULL, updateStatus(), PointF::X, and PointF::Y.
DrawBezier() [3/4]
Status Graphics::DrawBezier (const Pen * pen, INT x1, INT y1, INT x2, INT y2, INT x3, INT y3, INT x4, INT y4) inline
Definition at line 169 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawBezierI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x1, y1, x2, y2, x3, y3, x4, y4));
     }
References GdipDrawBezierI(), nativeGraphics, Pen::nativePen, NULL, updateStatus(), and y1().
DrawBezier() [4/4]
Status Graphics::DrawBezier (const Pen * pen, REAL x1, REAL y1, REAL x2, REAL y2, REAL x3, REAL y3, REAL x4, REAL y4) inline
Definition at line 161 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawBezier(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x1, y1, x2, y2, x3, y3, x4, y4));
     }
References GdipDrawBezier(), nativeGraphics, Pen::nativePen, NULL, updateStatus(), and y1().
DrawBeziers() [1/2]
Status Graphics::DrawBeziers (const Pen * pen, const Point * points, INT count) inline
Definition at line 201 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawBeziersI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawBeziersI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawBeziers() [2/2]
Status Graphics::DrawBeziers (const Pen * pen, const PointF * points, INT count) inline
Definition at line 195 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawBeziers(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawBeziers(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawCachedBitmap()
Status Graphics::DrawCachedBitmap (CachedBitmap * cb, INT x, INT y) inline
Definition at line 207 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawCachedBitmap(
                 nativeGraphics,
                 cb ? cb->nativeCachedBitmap : NULL,
                 x, y));
     }
References GdipDrawCachedBitmap(), CachedBitmap::nativeCachedBitmap, nativeGraphics, NULL, and updateStatus().
DrawClosedCurve() [1/4]
Status Graphics::DrawClosedCurve (const Pen * pen, const Point * points, INT count) inline
Definition at line 220 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawClosedCurveI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawClosedCurveI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawClosedCurve() [2/4]
Status Graphics::DrawClosedCurve (const Pen * pen, const Point * points, INT count, REAL tension) inline
Definition at line 233 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawClosedCurve2I(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count, tension));
     }
References GdipDrawClosedCurve2I(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawClosedCurve() [3/4]
Status Graphics::DrawClosedCurve (const Pen * pen, const PointF * points, INT count) inline
Definition at line 214 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawClosedCurve(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawClosedCurve(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawClosedCurve() [4/4]
Status Graphics::DrawClosedCurve (const Pen * pen, const PointF * points, INT count, REAL tension) inline
Definition at line 226 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawClosedCurve2(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count, tension));
     }
References GdipDrawClosedCurve2(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawCurve() [1/6]
Status Graphics::DrawCurve (const Pen * pen, const Point * points, INT count) inline
Definition at line 246 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawCurveI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawCurveI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawCurve() [2/6]
Status Graphics::DrawCurve (const Pen * pen, const Point * points, INT count, INT offset, INT numberOfSegments, REAL tension) inline
Definition at line 274 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawCurve3I(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count, offset,
                 numberOfSegments, tension));
     }
References GdipDrawCurve3I(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawCurve() [3/6]
Status Graphics::DrawCurve (const Pen * pen, const Point * points, INT count, REAL tension) inline
Definition at line 259 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawCurve2I(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count, tension));
     }
References GdipDrawCurve2I(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawCurve() [4/6]
Status Graphics::DrawCurve (const Pen * pen, const PointF * points, INT count) inline
Definition at line 240 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawCurve(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawCurve(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawCurve() [5/6]
Status Graphics::DrawCurve (const Pen * pen, const PointF * points, INT count, INT offset, INT numberOfSegments, REAL tension) inline
Definition at line 266 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawCurve3(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count, offset,
                 numberOfSegments, tension));
     }
References GdipDrawCurve3(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawCurve() [6/6]
Status Graphics::DrawCurve (const Pen * pen, const PointF * points, INT count, REAL tension) inline
Definition at line 252 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawCurve2(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count, tension));
     }
References GdipDrawCurve2(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawDriverString()
Status Graphics::DrawDriverString (const UINT16 * text, INT length, const Font * font, const Brush * brush, const PointF * positions, INT flags, const Matrix * matrix) inline
Definition at line 282 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawDriverString(
                 nativeGraphics, text, length,
                 font ? font->nativeFont : NULL,
                 brush ? brush->nativeBrush : NULL,
                 positions, flags,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipDrawDriverString(), Brush::nativeBrush, Font::nativeFont, nativeGraphics, NULL, and updateStatus().
DrawEllipse() [1/4]
Status Graphics::DrawEllipse (const Pen * pen, const Rect & rect) inline
Definition at line 313 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawEllipseI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipDrawEllipseI(), Rect::Height, nativeGraphics, Pen::nativePen, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
DrawEllipse() [2/4]
Status Graphics::DrawEllipse (const Pen * pen, const RectF & rect) inline
Definition at line 307 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawEllipse(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipDrawEllipse(), RectF::Height, nativeGraphics, Pen::nativePen, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
DrawEllipse() [3/4]
Status Graphics::DrawEllipse (const Pen * pen, INT x, INT y, INT width, INT height) inline
Definition at line 301 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawEllipseI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x, y, width, height));
     }
References GdipDrawEllipseI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawEllipse() [4/4]
Status Graphics::DrawEllipse (const Pen * pen, REAL x, REAL y, REAL width, REAL height) inline
Definition at line 294 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawEllipse(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x, y, width, height));
     }
References GdipDrawEllipse(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawImage() [1/17]
Status Graphics::DrawImage (Image * image, const Point & point) inline
Definition at line 340 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 point.X, point.Y));
     }
References GdipDrawImageI(), nativeGraphics, NULL, updateStatus(), Point::X, and Point::Y.
DrawImage() [2/17]
Status Graphics::DrawImage (Image * image, const Point * destPoints, INT count) inline
Definition at line 382 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImagePointsI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 destPoints, count));
     }
References GdipDrawImagePointsI(), nativeGraphics, NULL, and updateStatus().
DrawImage() [3/17]
Status Graphics::DrawImage (Image * image, const Point * destPoints, INT count, INT srcx, INT srcy, INT srcwidth, INT srcheight, Unit srcUnit, const ImageAttributes * imageAttributes = NULL, DrawImageAbort callback = NULL, VOID * callbackData = NULL) inline
Definition at line 468 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImagePointsRectI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 destPoints, count,
                 srcx, srcy, srcwidth, srcheight, srcUnit,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL,
                 callback, callbackData));
     }
References GdipDrawImagePointsRectI(), nativeGraphics, NULL, and updateStatus().
DrawImage() [4/17]
Status Graphics::DrawImage (Image * image, const PointF & point) inline
Definition at line 333 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImage(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 point.X, point.Y));
     }
References GdipDrawImage(), nativeGraphics, NULL, updateStatus(), PointF::X, and PointF::Y.
DrawImage() [5/17]
Status Graphics::DrawImage (Image * image, const PointF * destPoints, INT count) inline
Definition at line 375 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImagePoints(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 destPoints, count));
     }
References GdipDrawImagePoints(), nativeGraphics, NULL, and updateStatus().
DrawImage() [6/17]
Status Graphics::DrawImage (Image * image, const PointF * destPoints, INT count, REAL srcx, REAL srcy, REAL srcwidth, REAL srcheight, Unit srcUnit, const ImageAttributes * imageAttributes = NULL, DrawImageAbort callback = NULL, VOID * callbackData = NULL) inline
Definition at line 453 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImagePointsRect(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 destPoints, count,
                 srcx, srcy, srcwidth, srcheight, srcUnit,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL,
                 callback, callbackData));
     }
References GdipDrawImagePointsRect(), nativeGraphics, NULL, and updateStatus().
DrawImage() [7/17]
Status Graphics::DrawImage (Image * image, const Rect & destRect, INT srcx, INT srcy, INT srcwidth, INT srcheight, Unit srcUnit, const ImageAttributes * imageAttributes = NULL, DrawImageAbort callback = NULL, VOID * callbackData = NULL) inline
Definition at line 423 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageRectRectI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 destRect.X, destRect.Y,
                 destRect.Width, destRect.Height,
                 srcx, srcy, srcwidth, srcheight, srcUnit,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL,
                 callback, callbackData));
     }
References GdipDrawImageRectRectI(), Rect::Height, nativeGraphics, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
DrawImage() [8/17]
Status Graphics::DrawImage (Image * image, const Rect & rect) inline
Definition at line 368 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageRectI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipDrawImageRectI(), Rect::Height, nativeGraphics, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
DrawImage() [9/17]
Status Graphics::DrawImage (Image * image, const RectF & destRect, const RectF & sourceRect, Unit srcUnit, const ImageAttributes * imageAttributes = NULL) inline
Definition at line 439 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageRectRectI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 destRect.X, destRect.Y,
                 destRect.Width, destRect.Height,
                 sourceRect.X, sourceRect.Y,
                 sourceRect.Width, sourceRect.Height, srcUnit,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL,
                 NULL, NULL));
     }
References GdipDrawImageRectRectI(), RectF::Height, nativeGraphics, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
DrawImage() [10/17]
Status Graphics::DrawImage (Image * image, const RectF & destRect, REAL srcx, REAL srcy, REAL srcwidth, REAL srcheight, Unit srcUnit, const ImageAttributes * imageAttributes = NULL, DrawImageAbort callback = NULL, VOID * callbackData = NULL) inline
Definition at line 407 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageRectRect(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 destRect.X, destRect.Y,
                 destRect.Width, destRect.Height,
                 srcx, srcy, srcwidth, srcheight, srcUnit,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL,
                 callback, callbackData));
     }
References GdipDrawImageRectRect(), RectF::Height, nativeGraphics, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
DrawImage() [11/17]
Status Graphics::DrawImage (Image * image, const RectF & rect) inline
Definition at line 361 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageRect(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipDrawImageRect(), RectF::Height, nativeGraphics, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
DrawImage() [12/17]
Status Graphics::DrawImage (Image * image, INT x, INT y) inline
Definition at line 326 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 x, y));
     }
References GdipDrawImageI(), nativeGraphics, NULL, and updateStatus().
DrawImage() [13/17]
Status Graphics::DrawImage (Image * image, INT x, INT y, INT srcx, INT srcy, INT srcwidth, INT srcheight, Unit srcUnit) inline
Definition at line 398 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImagePointRectI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 x, y, srcx, srcy, srcwidth, srcheight,
                 srcUnit));
     }
References GdipDrawImagePointRectI(), nativeGraphics, NULL, and updateStatus().
DrawImage() [14/17]
Status Graphics::DrawImage (Image * image, INT x, INT y, INT width, INT height) inline
Definition at line 354 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageRectI(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 x, y, width, height));
     }
References GdipDrawImageRectI(), nativeGraphics, NULL, and updateStatus().
DrawImage() [15/17]
Status Graphics::DrawImage (Image * image, REAL x, REAL y) inline
Definition at line 319 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImage(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 x, y));
     }
References GdipDrawImage(), nativeGraphics, NULL, and updateStatus().
DrawImage() [16/17]
Status Graphics::DrawImage (Image * image, REAL x, REAL y, REAL srcx, REAL srcy, REAL srcwidth, REAL srcheight, Unit srcUnit) inline
Definition at line 389 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImagePointRect(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 x, y, srcx, srcy, srcwidth, srcheight,
                 srcUnit));
     }
References GdipDrawImagePointRect(), nativeGraphics, NULL, and updateStatus().
DrawImage() [17/17]
Status Graphics::DrawImage (Image * image, REAL x, REAL y, REAL width, REAL height) inline
Definition at line 347 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawImageRect(
                 nativeGraphics,
                 image ? image->nativeImage : NULL,
                 x, y, width, height));
     }
References GdipDrawImageRect(), nativeGraphics, NULL, and updateStatus().
DrawLine() [1/4]
Status Graphics::DrawLine (const Pen * pen, const Point & pt1, const Point & pt2) inline
Definition at line 515 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawLineI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 pt1.X, pt1.Y, pt2.X, pt2.Y));
     }
References GdipDrawLineI(), nativeGraphics, Pen::nativePen, NULL, updateStatus(), Point::X, and Point::Y.
DrawLine() [2/4]
Status Graphics::DrawLine (const Pen * pen, const PointF & pt1, const PointF & pt2) inline
Definition at line 509 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawLine(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 pt1.X, pt1.Y, pt2.X, pt2.Y));
     }
References GdipDrawLine(), nativeGraphics, Pen::nativePen, NULL, updateStatus(), PointF::X, and PointF::Y.
DrawLine() [3/4]
Status Graphics::DrawLine (const Pen * pen, INT x1, INT y1, INT x2, INT y2) inline
Definition at line 503 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawLineI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x1, y1, x2, y2));
     }
References GdipDrawLineI(), nativeGraphics, Pen::nativePen, NULL, updateStatus(), and y1().
DrawLine() [4/4]
Status Graphics::DrawLine (const Pen * pen, REAL x1, REAL y1, REAL x2, REAL y2) inline
Definition at line 497 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawLine(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x1, y1, x2, y2));
     }
References GdipDrawLine(), nativeGraphics, Pen::nativePen, NULL, updateStatus(), and y1().
DrawLines() [1/2]
Status Graphics::DrawLines (const Pen * pen, const Point * points, INT count) inline
Definition at line 527 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawLinesI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawLinesI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawLines() [2/2]
Status Graphics::DrawLines (const Pen * pen, const PointF * points, INT count) inline
Definition at line 521 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawLines(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawLines(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawPath()
Status Graphics::DrawPath (const Pen * pen, const GraphicsPath * path) inline
Definition at line 533 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawPath(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 path ? path->nativePath : NULL));
     }
References GdipDrawPath(), nativeGraphics, GraphicsPath::nativePath, Pen::nativePen, NULL, and updateStatus().
DrawPie() [1/4]
Status Graphics::DrawPie (const Pen * pen, const Rect & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 561 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawPieI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipDrawPieI(), Rect::Height, nativeGraphics, Pen::nativePen, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
DrawPie() [2/4]
Status Graphics::DrawPie (const Pen * pen, const RectF & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 553 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawPie(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipDrawPie(), RectF::Height, nativeGraphics, Pen::nativePen, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
DrawPie() [3/4]
Status Graphics::DrawPie (const Pen * pen, INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle) inline
Definition at line 546 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawPieI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipDrawPieI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawPie() [4/4]
Status Graphics::DrawPie (const Pen * pen, REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle) inline
Definition at line 539 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawPie(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipDrawPie(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawPolygon() [1/2]
Status Graphics::DrawPolygon (const Pen * pen, const Point * points, INT count) inline
Definition at line 575 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawPolygonI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawPolygonI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawPolygon() [2/2]
Status Graphics::DrawPolygon (const Pen * pen, const PointF * points, INT count) inline
Definition at line 569 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawPolygon(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 points, count));
     }
References GdipDrawPolygon(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawRectangle() [1/4]
Status Graphics::DrawRectangle (const Pen * pen, const Rect & rect) inline
Definition at line 601 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawRectangleI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipDrawRectangleI(), Rect::Height, nativeGraphics, Pen::nativePen, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
DrawRectangle() [2/4]
Status Graphics::DrawRectangle (const Pen * pen, const RectF & rect) inline
Definition at line 595 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawRectangle(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipDrawRectangle(), RectF::Height, nativeGraphics, Pen::nativePen, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
DrawRectangle() [3/4]
Status Graphics::DrawRectangle (const Pen * pen, INT x, INT y, INT width, INT height) inline
Definition at line 588 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawRectangleI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x, y, width, height));
     }
References GdipDrawRectangleI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawRectangle() [4/4]
Status Graphics::DrawRectangle (const Pen * pen, REAL x, REAL y, REAL width, REAL height) inline
Definition at line 581 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawRectangle(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 x, y, width, height));
     }
References GdipDrawRectangle(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawRectangles() [1/2]
Status Graphics::DrawRectangles (const Pen * pen, const Rect * rects, INT count) inline
Definition at line 613 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawRectanglesI(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rects, count));
     }
References GdipDrawRectanglesI(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawRectangles() [2/2]
Status Graphics::DrawRectangles (const Pen * pen, const RectF * rects, INT count) inline
Definition at line 607 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawRectangles(
                 nativeGraphics, pen ? pen->nativePen : NULL,
                 rects, count));
     }
References GdipDrawRectangles(), nativeGraphics, Pen::nativePen, NULL, and updateStatus().
DrawString() [1/3]
Status Graphics::DrawString (const WCHAR * string, INT length, const Font * font, const PointF & origin, const Brush * brush) inline
Definition at line 619 of file gdiplusgraphics.h.
     {
         RectF layoutRect(origin.X, origin.Y, 0.0f, 0.0f);
         return updateStatus(DllExports::GdipDrawString(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 &layoutRect, NULL,
                 brush ? brush->nativeBrush : NULL));
     }
References GdipDrawString(), Brush::nativeBrush, Font::nativeFont, nativeGraphics, NULL, and updateStatus().
DrawString() [2/3]
Status Graphics::DrawString (const WCHAR * string, INT length, const Font * font, const PointF & origin, const StringFormat * stringFormat, const Brush * brush) inline
Definition at line 629 of file gdiplusgraphics.h.
     {
         RectF layoutRect(origin.X, origin.Y, 0.0f, 0.0f);
         return updateStatus(DllExports::GdipDrawString(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 &layoutRect,
                 stringFormat ? stringFormat->nativeStringFormat : NULL,
                 brush ? brush->nativeBrush : NULL));
     }
References GdipDrawString(), Brush::nativeBrush, Font::nativeFont, nativeGraphics, NULL, stringFormat, and updateStatus().
DrawString() [3/3]
Status Graphics::DrawString (const WCHAR * string, INT length, const Font * font, const RectF & layoutRect, const StringFormat * stringFormat, const Brush * brush) inline
Definition at line 641 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipDrawString(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 &layoutRect,
                 stringFormat ? stringFormat->nativeStringFormat : NULL,
                 brush ? brush->nativeBrush : NULL));
     }
References GdipDrawString(), Brush::nativeBrush, Font::nativeFont, nativeGraphics, NULL, stringFormat, and updateStatus().
EndContainer()
Status Graphics::EndContainer (GraphicsContainer state) inline
Definition at line 652 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEndContainer(
                 nativeGraphics, state));
     }
References GdipEndContainer(), nativeGraphics, and updateStatus().
EnumerateMetafile() [1/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const Point & destPoint, const Rect & srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 743 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileSrcRectDestPointI(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destPoint, srcRect, srcUnit,
                 callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [2/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const Point & destPoint, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 669 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileDestPointI(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destPoint, callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [3/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const Point * destPoints, INT count, const Rect & srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 799 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileSrcRectDestPointsI(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destPoints, count, srcRect, srcUnit,
                 callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [4/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const Point * destPoints, INT count, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 717 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileDestPointsI(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destPoints, count, callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References GdipEnumerateMetafileDestPointsI(), nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [5/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const PointF & destPoint, const RectF & srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 729 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileSrcRectDestPoint(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destPoint, srcRect, srcUnit,
                 callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [6/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const PointF & destPoint, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 657 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileDestPoint(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destPoint, callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [7/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const PointF * destPoints, INT count, const RectF & srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 785 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileSrcRectDestPoints(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destPoints, count, srcRect, srcUnit,
                 callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [8/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const PointF * destPoints, INT count, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 705 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileDestPoints(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destPoints, count, callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References GdipEnumerateMetafileDestPoints(), nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [9/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const Rect & destRect, const Rect & srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 771 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileSrcRectDestRectI(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destRect, srcRect, srcUnit,
                 callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [10/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const Rect & destRect, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 693 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileDestRectI(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destRect, callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [11/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const RectF & destRect, const RectF & srcRect, Unit srcUnit, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 757 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileSrcRectDestRect(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destRect, srcRect, srcUnit,
                 callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
EnumerateMetafile() [12/12]
Status Graphics::EnumerateMetafile (const Metafile * metafile, const RectF & destRect, EnumerateMetafileProc callback, VOID * callbackData = NULL, ImageAttributes * imageAttributes = NULL) inline
Definition at line 681 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipEnumerateMetafileDestRect(
                 nativeGraphics,
                 metafile ? ((GpMetafile*) metafile->nativeImage) : NULL,
                 destRect, callback, callbackData,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL));
     }
References nativeGraphics, Image::nativeImage, NULL, and updateStatus().
ExcludeClip() [1/3]
Status Graphics::ExcludeClip (const Rect & rect) inline
Definition at line 820 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRectI(
                 nativeGraphics,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 CombineModeExclude));
     }
References CombineModeExclude, GdipSetClipRectI(), Rect::Height, nativeGraphics, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
ExcludeClip() [2/3]
Status Graphics::ExcludeClip (const RectF & rect) inline
Definition at line 813 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRect(
                 nativeGraphics,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 CombineModeExclude));
     }
References CombineModeExclude, GdipSetClipRect(), RectF::Height, nativeGraphics, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
ExcludeClip() [3/3]
Status Graphics::ExcludeClip (const Region * region) inline
Definition at line 827 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRegion(
                 nativeGraphics,
                 region ? region->nativeRegion : NULL,
                 CombineModeExclude));
     }
References CombineModeExclude, GdipSetClipRegion(), nativeGraphics, Region::nativeRegion, NULL, and updateStatus().
FillClosedCurve() [1/4]
Status Graphics::FillClosedCurve (const Brush * brush, const Point * points, INT count) inline
Definition at line 842 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillClosedCurveI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 points, count));
     }
References GdipFillClosedCurveI(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillClosedCurve() [2/4]
Status Graphics::FillClosedCurve (const Brush * brush, const Point * points, INT count, FillMode fillMode, REAL tension = 0.5f) inline
Definition at line 859 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillClosedCurve2I(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 points, count, tension, fillMode));
     }
References GdipFillClosedCurve2I(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillClosedCurve() [3/4]
Status Graphics::FillClosedCurve (const Brush * brush, const PointF * points, INT count) inline
Definition at line 834 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillClosedCurve(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 points, count));
     }
References GdipFillClosedCurve(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillClosedCurve() [4/4]
Status Graphics::FillClosedCurve (const Brush * brush, const PointF * points, INT count, FillMode fillMode, REAL tension = 0.5f) inline
Definition at line 850 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillClosedCurve2(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 points, count, tension, fillMode));
     }
References GdipFillClosedCurve2(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillEllipse() [1/4]
Status Graphics::FillEllipse (const Brush * brush, const Rect & rect) inline
Definition at line 891 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillEllipseI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipFillEllipseI(), Rect::Height, Brush::nativeBrush, nativeGraphics, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
FillEllipse() [2/4]
Status Graphics::FillEllipse (const Brush * brush, const RectF & rect) inline
Definition at line 884 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillEllipse(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipFillEllipse(), RectF::Height, Brush::nativeBrush, nativeGraphics, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
FillEllipse() [3/4]
Status Graphics::FillEllipse (const Brush * brush, INT x, INT y, INT width, INT height) inline
Definition at line 876 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillEllipseI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 x, y, width, height));
     }
References GdipFillEllipseI(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillEllipse() [4/4]
Status Graphics::FillEllipse (const Brush * brush, REAL x, REAL y, REAL width, REAL height) inline
Definition at line 868 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillEllipse(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 x, y, width, height));
     }
References GdipFillEllipse(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillPath()
Status Graphics::FillPath (const Brush * brush, const GraphicsPath * path) inline
Definition at line 898 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPath(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 path ? path->nativePath : NULL));
     }
References GdipFillPath(), Brush::nativeBrush, nativeGraphics, GraphicsPath::nativePath, NULL, and updateStatus().
FillPie() [1/4]
Status Graphics::FillPie (const Brush * brush, const Rect & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 931 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPieI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipFillPieI(), Rect::Height, Brush::nativeBrush, nativeGraphics, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
FillPie() [2/4]
Status Graphics::FillPie (const Brush * brush, const RectF & rect, REAL startAngle, REAL sweepAngle) inline
Definition at line 922 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPie(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 startAngle, sweepAngle));
     }
References GdipFillPie(), RectF::Height, Brush::nativeBrush, nativeGraphics, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
FillPie() [3/4]
Status Graphics::FillPie (const Brush * brush, INT x, INT y, INT width, INT height, REAL startAngle, REAL sweepAngle) inline
Definition at line 914 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPieI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipFillPieI(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillPie() [4/4]
Status Graphics::FillPie (const Brush * brush, REAL x, REAL y, REAL width, REAL height, REAL startAngle, REAL sweepAngle) inline
Definition at line 905 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPie(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 x, y, width, height, startAngle, sweepAngle));
     }
References GdipFillPie(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillPolygon() [1/4]
Status Graphics::FillPolygon (const Brush * brush, const Point * points, INT count) inline
Definition at line 947 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPolygonI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 points, count, FillModeAlternate));
     }
References FillModeAlternate, GdipFillPolygonI(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillPolygon() [2/4]
Status Graphics::FillPolygon (const Brush * brush, const Point * points, INT count, FillMode fillMode) inline
Definition at line 962 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPolygonI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 points, count, fillMode));
     }
References GdipFillPolygonI(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillPolygon() [3/4]
Status Graphics::FillPolygon (const Brush * brush, const PointF * points, INT count) inline
Definition at line 940 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPolygon(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 points, count, FillModeAlternate));
     }
References FillModeAlternate, GdipFillPolygon(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillPolygon() [4/4]
Status Graphics::FillPolygon (const Brush * brush, const PointF * points, INT count, FillMode fillMode) inline
Definition at line 954 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillPolygon(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 points, count, fillMode));
     }
References GdipFillPolygon(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillRectangle() [1/4]
Status Graphics::FillRectangle (const Brush * brush, const Rect & rect) inline
Definition at line 993 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillRectangleI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipFillRectangleI(), Rect::Height, Brush::nativeBrush, nativeGraphics, NULL, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
FillRectangle() [2/4]
Status Graphics::FillRectangle (const Brush * brush, const RectF & rect) inline
Definition at line 986 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillRectangle(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 rect.X, rect.Y, rect.Width, rect.Height));
     }
References GdipFillRectangle(), RectF::Height, Brush::nativeBrush, nativeGraphics, NULL, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
FillRectangle() [3/4]
Status Graphics::FillRectangle (const Brush * brush, INT x, INT y, INT width, INT height) inline
Definition at line 978 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillRectangleI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 x, y, width, height));
     }
References GdipFillRectangleI(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillRectangle() [4/4]
Status Graphics::FillRectangle (const Brush * brush, REAL x, REAL y, REAL width, REAL height) inline
Definition at line 970 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillRectangle(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 x, y, width, height));
     }
References GdipFillRectangle(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillRectangles() [1/2]
Status Graphics::FillRectangles (const Brush * brush, const Rect * rects, INT count) inline
Definition at line 1007 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillRectanglesI(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 rects, count));
     }
References GdipFillRectanglesI(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillRectangles() [2/2]
Status Graphics::FillRectangles (const Brush * brush, const RectF * rects, INT count) inline
Definition at line 1000 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillRectangles(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 rects, count));
     }
References GdipFillRectangles(), Brush::nativeBrush, nativeGraphics, NULL, and updateStatus().
FillRegion()
Status Graphics::FillRegion (const Brush * brush, const Region * region) inline
Definition at line 1014 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipFillRegion(
                 nativeGraphics,
                 brush ? brush->nativeBrush : NULL,
                 region ? region->nativeRegion : NULL));
     }
References GdipFillRegion(), Brush::nativeBrush, nativeGraphics, Region::nativeRegion, NULL, and updateStatus().
Flush()
VOID Graphics::Flush (FlushIntention intention = FlushIntentionFlush) inline
Definition at line 1021 of file gdiplusgraphics.h.
     {
         updateStatus(DllExports::GdipFlush(nativeGraphics, intention));
     }
References GdipFlush(), nativeGraphics, and updateStatus().
FromHDC() [1/2]
static Graphics* Graphics::FromHDC (HDC hdc) inline static
Definition at line 43 of file gdiplusgraphics.h.
     {
         return new Graphics(hdc);
     }
References Graphics().
FromHDC() [2/2]
static Graphics* Graphics::FromHDC (HDC hdc, HANDLE hdevice) inline static
Definition at line 47 of file gdiplusgraphics.h.
     {
         return new Graphics(hdc, hdevice);
     }
References Graphics().
FromHWND()
static Graphics* Graphics::FromHWND (HWND hwnd, BOOL icm = FALSE) inline static
Definition at line 51 of file gdiplusgraphics.h.
     {
         return new Graphics(hwnd, icm);
     }
References Graphics().
FromImage()
static Graphics* Graphics::FromImage (Image * image) inline static
Definition at line 55 of file gdiplusgraphics.h.
     {
         return new Graphics(image);
     }
References Graphics().
GetClip()
Status Graphics::GetClip (Region * region) const inline
Definition at line 1025 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGetClip(
                 nativeGraphics,
                 region ? region->nativeRegion : NULL));
     }
References GdipGetClip(), nativeGraphics, Region::nativeRegion, NULL, and updateStatus().
GetClipBounds() [1/2]
Status Graphics::GetClipBounds (Rect * rect) const inline
Definition at line 1036 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGetClipBoundsI(
                 nativeGraphics, rect));
     }
References GdipGetClipBoundsI(), nativeGraphics, and updateStatus().
GetClipBounds() [2/2]
Status Graphics::GetClipBounds (RectF * rect) const inline
Definition at line 1031 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGetClipBounds(
                 nativeGraphics, rect));
     }
References GdipGetClipBounds(), nativeGraphics, and updateStatus().
GetCompositingMode()
CompositingMode Graphics::GetCompositingMode () const inline
Definition at line 1041 of file gdiplusgraphics.h.
     {
         CompositingMode result = CompositingModeSourceOver;
         updateStatus(DllExports::GdipGetCompositingMode(
                 nativeGraphics, &result));
         return result;
     }
References CompositingModeSourceOver, GdipGetCompositingMode(), nativeGraphics, and updateStatus().
GetCompositingQuality()
CompositingQuality Graphics::GetCompositingQuality () const inline
Definition at line 1048 of file gdiplusgraphics.h.
     {
         CompositingQuality result = CompositingQualityDefault;
         updateStatus(DllExports::GdipGetCompositingQuality(
                 nativeGraphics, &result));
         return result;
     }
References CompositingQualityDefault, GdipGetCompositingQuality(), nativeGraphics, and updateStatus().
GetDpiX()
REAL Graphics::GetDpiX () const inline
Definition at line 1055 of file gdiplusgraphics.h.
     {
         REAL result = 0.0f;
         updateStatus(DllExports::GdipGetDpiX(nativeGraphics, &result));
         return result;
     }
References GdipGetDpiX(), nativeGraphics, and updateStatus().
GetDpiY()
REAL Graphics::GetDpiY () const inline
Definition at line 1061 of file gdiplusgraphics.h.
     {
         REAL result = 0.0f;
         updateStatus(DllExports::GdipGetDpiY(nativeGraphics, &result));
         return result;
     }
References GdipGetDpiY(), nativeGraphics, and updateStatus().
GetHalftonePalette()
static HPALETTE Graphics::GetHalftonePalette () inline static
Definition at line 59 of file gdiplusgraphics.h.
     {
         return DllExports::GdipCreateHalftonePalette();
     }
References GdipCreateHalftonePalette().
GetHDC()
HDC Graphics::GetHDC () inline
Definition at line 1067 of file gdiplusgraphics.h.
     {
         HDC result = NULL;
         updateStatus(DllExports::GdipGetDC(nativeGraphics, &result));
         return result;
     }
References GdipGetDC(), nativeGraphics, NULL, and updateStatus().
GetInterpolationMode()
InterpolationMode Graphics::GetInterpolationMode () const inline
Definition at line 1073 of file gdiplusgraphics.h.
     {
         InterpolationMode result = InterpolationModeDefault;
         updateStatus(DllExports::GdipGetInterpolationMode(
                 nativeGraphics, &result));
         return result;
     }
References GdipGetInterpolationMode(), InterpolationModeDefault, nativeGraphics, and updateStatus().
GetLastStatus()
Status Graphics::GetLastStatus () const inline
Definition at line 1080 of file gdiplusgraphics.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References lastStatus, and Ok.
GetNearestColor()
Status Graphics::GetNearestColor (Color * color) const inline
Definition at line 1086 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGetNearestColor(
                 nativeGraphics, color ? &color->Value : NULL));
     }
References GdipGetNearestColor(), nativeGraphics, NULL, updateStatus(), and Color::Value.
GetPageScale()
REAL Graphics::GetPageScale () const inline
Definition at line 1091 of file gdiplusgraphics.h.
     {
         REAL result = 0.0f;
         updateStatus(DllExports::GdipGetPageScale(
                 nativeGraphics, &result));
         return result;
     }
References GdipGetPageScale(), nativeGraphics, and updateStatus().
GetPageUnit()
Unit Graphics::GetPageUnit () const inline
Definition at line 1098 of file gdiplusgraphics.h.
     {
         Unit result = UnitWorld;
         updateStatus(DllExports::GdipGetPageUnit(
                 nativeGraphics, &result));
         return result;
     }
References GdipGetPageUnit(), nativeGraphics, UnitWorld, and updateStatus().
GetPixelOffsetMode()
PixelOffsetMode Graphics::GetPixelOffsetMode () const inline
Definition at line 1105 of file gdiplusgraphics.h.
     {
         PixelOffsetMode result = PixelOffsetModeDefault;
         updateStatus(DllExports::GdipGetPixelOffsetMode(
                 nativeGraphics, &result));
         return result;
     }
References GdipGetPixelOffsetMode(), nativeGraphics, PixelOffsetModeDefault, and updateStatus().
GetRenderingOrigin()
Status Graphics::GetRenderingOrigin (INT * x, INT * y) const inline
Definition at line 1112 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGetRenderingOrigin(
                 nativeGraphics, x, y));
     }
References GdipGetRenderingOrigin(), nativeGraphics, and updateStatus().
GetSmoothingMode()
SmoothingMode Graphics::GetSmoothingMode () const inline
Definition at line 1117 of file gdiplusgraphics.h.
     {
         SmoothingMode result = SmoothingModeDefault;
         updateStatus(DllExports::GdipGetSmoothingMode(
                 nativeGraphics, &result));
         return result;
     }
References GdipGetSmoothingMode(), nativeGraphics, SmoothingModeDefault, and updateStatus().
GetTextContrast()
UINT Graphics::GetTextContrast () const inline
Definition at line 1124 of file gdiplusgraphics.h.
     {
         UINT result = 0;
         updateStatus(DllExports::GdipGetTextContrast(
                 nativeGraphics, &result));
         return result;
     }
References GdipGetTextContrast(), nativeGraphics, and updateStatus().
GetTextRenderingHint()
TextRenderingHint Graphics::GetTextRenderingHint () const inline
Definition at line 1131 of file gdiplusgraphics.h.
     {
         TextRenderingHint result = TextRenderingHintSystemDefault;
         updateStatus(DllExports::GdipGetTextRenderingHint(
                 nativeGraphics, &result));
         return result;
     }
References GdipGetTextRenderingHint(), nativeGraphics, TextRenderingHintSystemDefault, and updateStatus().
GetTransform()
Status Graphics::GetTransform (Matrix * matrix) const inline
Definition at line 1138 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGetWorldTransform(
                 nativeGraphics,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipGetWorldTransform(), nativeGraphics, NULL, and updateStatus().
GetVisibleClipBounds() [1/2]
Status Graphics::GetVisibleClipBounds (Rect * rect) const inline
Definition at line 1149 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGetVisibleClipBoundsI(
                 nativeGraphics, rect));
     }
References GdipGetVisibleClipBoundsI(), nativeGraphics, and updateStatus().
GetVisibleClipBounds() [2/2]
Status Graphics::GetVisibleClipBounds (RectF * rect) const inline
Definition at line 1144 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipGetVisibleClipBounds(
                 nativeGraphics, rect));
     }
References GdipGetVisibleClipBounds(), nativeGraphics, and updateStatus().
IntersectClip() [1/3]
Status Graphics::IntersectClip (const Rect & rect) inline
Definition at line 1161 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRectI(
                 nativeGraphics,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 CombineModeIntersect));
     }
References CombineModeIntersect, GdipSetClipRectI(), Rect::Height, nativeGraphics, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
IntersectClip() [2/3]
Status Graphics::IntersectClip (const RectF & rect) inline
Definition at line 1154 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRect(
                 nativeGraphics,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 CombineModeIntersect));
     }
References CombineModeIntersect, GdipSetClipRect(), RectF::Height, nativeGraphics, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
IntersectClip() [3/3]
Status Graphics::IntersectClip (const Region * region) inline
Definition at line 1168 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRegion(
                 nativeGraphics,
                 region ? region->nativeRegion : NULL,
                 CombineModeIntersect));
     }
References CombineModeIntersect, GdipSetClipRegion(), nativeGraphics, Region::nativeRegion, NULL, and updateStatus().
IsClipEmpty()
BOOL Graphics::IsClipEmpty () const inline
Definition at line 1175 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsClipEmpty(
                 nativeGraphics, &result));
         return result;
     }
References FALSE, GdipIsClipEmpty(), nativeGraphics, and updateStatus().
IsVisible() [1/8]
BOOL Graphics::IsVisible (const Point & point) const inline
Definition at line 1203 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisiblePointI(
                 nativeGraphics, point.X, point.Y, &result));
         return result;
     }
References FALSE, GdipIsVisiblePointI(), nativeGraphics, updateStatus(), Point::X, and Point::Y.
IsVisible() [2/8]
BOOL Graphics::IsVisible (const PointF & point) const inline
Definition at line 1196 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisiblePoint(
                 nativeGraphics, point.X, point.Y, &result));
         return result;
     }
References FALSE, GdipIsVisiblePoint(), nativeGraphics, updateStatus(), PointF::X, and PointF::Y.
IsVisible() [3/8]
BOOL Graphics::IsVisible (const Rect & rect) const inline
Definition at line 1232 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisibleRectI(
                 nativeGraphics, rect.X, rect.Y,
                 rect.Width, rect.Height, &result));
         return result;
     }
References FALSE, GdipIsVisibleRectI(), Rect::Height, nativeGraphics, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
IsVisible() [4/8]
BOOL Graphics::IsVisible (const RectF & rect) const inline
Definition at line 1224 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisibleRect(
                 nativeGraphics, rect.X, rect.Y,
                 rect.Width, rect.Height, &result));
         return result;
     }
References FALSE, GdipIsVisibleRect(), RectF::Height, nativeGraphics, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
IsVisible() [5/8]
BOOL Graphics::IsVisible (INT x, INT y) const inline
Definition at line 1189 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisiblePointI(
                 nativeGraphics, x, y, &result));
         return result;
     }
References FALSE, GdipIsVisiblePointI(), nativeGraphics, and updateStatus().
IsVisible() [6/8]
BOOL Graphics::IsVisible (INT x, INT y, INT width, INT height) const inline
Definition at line 1217 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisibleRectI(
                 nativeGraphics, x, y, width, height, &result));
         return result;
     }
References FALSE, GdipIsVisibleRectI(), nativeGraphics, and updateStatus().
IsVisible() [7/8]
BOOL Graphics::IsVisible (REAL x, REAL y) const inline
Definition at line 1182 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisiblePoint(
                 nativeGraphics, x, y, &result));
         return result;
     }
References FALSE, GdipIsVisiblePoint(), nativeGraphics, and updateStatus().
IsVisible() [8/8]
BOOL Graphics::IsVisible (REAL x, REAL y, REAL width, REAL height) const inline
Definition at line 1210 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisibleRect(
                 nativeGraphics, x, y, width, height, &result));
         return result;
     }
References FALSE, GdipIsVisibleRect(), nativeGraphics, and updateStatus().
IsVisibleClipEmpty()
BOOL Graphics::IsVisibleClipEmpty () const inline
Definition at line 1240 of file gdiplusgraphics.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipIsVisibleClipEmpty(
                 nativeGraphics, &result));
         return result;
     }
References FALSE, GdipIsVisibleClipEmpty(), nativeGraphics, and updateStatus().
MeasureCharacterRanges()
Status Graphics::MeasureCharacterRanges (const WCHAR * string, INT length, const Font * font, const RectF & layoutRect, const StringFormat * stringFormat, INT regionCount, Region * regions) const inline
Definition at line 1247 of file gdiplusgraphics.h.
     {
         if (regionCount <= 0 || !regions)
             return lastStatus = InvalidParameter;
         GpRegion **nativeRegionArray = (GpRegion**)
             DllExports::GdipAlloc(regionCount * sizeof(GpRegion*));
         if (!nativeRegionArray)
             return lastStatus = OutOfMemory;
         for (int i = 0; i < regionCount; ++i) {
             nativeRegionArray[i] = regions[i].nativeRegion;
         }
         Status status = updateStatus(DllExports::GdipMeasureCharacterRanges(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 layoutRect,
                 stringFormat ? stringFormat->nativeStringFormat : NULL,
                 regionCount, nativeRegionArray));
         DllExports::GdipFree(nativeRegionArray);
         return status;
     }
References GdipAlloc(), GdipFree(), InvalidParameter, lastStatus, Font::nativeFont, nativeGraphics, Region::nativeRegion, NULL, OutOfMemory, stringFormat, and updateStatus().
MeasureDriverString()
Status Graphics::MeasureDriverString (const UINT16 * text, INT length, const Font * font, const PointF * positions, INT flags, const Matrix * matrix, RectF * boundingBox) const inline
Definition at line 1271 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipMeasureDriverString(
                 nativeGraphics, text, length,
                 font ? font->nativeFont : NULL,
                 positions, flags,
                 matrix ? matrix->nativeMatrix : NULL,
                 boundingBox));
     }
References GdipMeasureDriverString(), Font::nativeFont, nativeGraphics, NULL, and updateStatus().
MeasureString() [1/5]
Status Graphics::MeasureString (const WCHAR * string, INT length, const Font * font, const PointF & origin, const StringFormat * stringFormat, RectF * boundingBox) const inline
Definition at line 1332 of file gdiplusgraphics.h.
     {
         RectF layoutRect(origin, SizeF(0.0f, 0.0f));
         return updateStatus(DllExports::GdipMeasureString(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 &layoutRect,
                 stringFormat ? stringFormat->nativeStringFormat : NULL,
                 boundingBox, NULL, NULL));
     }
References GdipMeasureString(), Font::nativeFont, nativeGraphics, NULL, stringFormat, and updateStatus().
MeasureString() [2/5]
Status Graphics::MeasureString (const WCHAR * string, INT length, const Font * font, const PointF & origin, RectF * boundingBox) const inline
Definition at line 1322 of file gdiplusgraphics.h.
     {
         RectF layoutRect(origin, SizeF(0.0f, 0.0f));
         return updateStatus(DllExports::GdipMeasureString(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 &layoutRect, NULL, boundingBox, NULL, NULL));
     }
References GdipMeasureString(), Font::nativeFont, nativeGraphics, NULL, and updateStatus().
MeasureString() [3/5]
Status Graphics::MeasureString (const WCHAR * string, INT length, const Font * font, const RectF & layoutRect, const StringFormat * stringFormat, RectF * boundingBox, INT * codepointsFitted = NULL, INT * linesFitted = NULL) const inline
Definition at line 1291 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipMeasureString(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 &layoutRect,
                 stringFormat ? stringFormat->nativeStringFormat : NULL,
                 boundingBox, codepointsFitted, linesFitted));
     }
References GdipMeasureString(), Font::nativeFont, nativeGraphics, NULL, stringFormat, and updateStatus().
MeasureString() [4/5]
Status Graphics::MeasureString (const WCHAR * string, INT length, const Font * font, const RectF & layoutRect, RectF * boundingBox) const inline
Definition at line 1282 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipMeasureString(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 &layoutRect, NULL, boundingBox, NULL, NULL));
     }
References GdipMeasureString(), Font::nativeFont, nativeGraphics, NULL, and updateStatus().
MeasureString() [5/5]
Status Graphics::MeasureString (const WCHAR * string, INT length, const Font * font, const SizeF & layoutRectSize, const StringFormat * stringFormat, SizeF * size, INT * codepointsFitted = NULL, INT * linesFitted = NULL) const inline
Definition at line 1304 of file gdiplusgraphics.h.
     {
         if (!size) return lastStatus = InvalidParameter;
         RectF layoutRect(PointF(0.0f, 0.0f), layoutRectSize);
         RectF boundingBox;
         Status status = updateStatus(DllExports::GdipMeasureString(
                 nativeGraphics, string, length,
                 font ? font->nativeFont : NULL,
                 &layoutRect,
                 stringFormat ? stringFormat->nativeStringFormat : NULL,
                 &boundingBox, codepointsFitted, linesFitted));
         boundingBox.GetSize(size);
         return status;
     }
References GdipMeasureString(), InvalidParameter, lastStatus, Font::nativeFont, nativeGraphics, NULL, stringFormat, and updateStatus().
MultiplyTransform()
Status Graphics::MultiplyTransform (const Matrix * matrix, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 1345 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipMultiplyWorldTransform(
                 nativeGraphics,
                 matrix ? matrix->nativeMatrix : NULL, order));
     }
References GdipMultiplyWorldTransform(), nativeGraphics, NULL, and updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
Graphics& Graphics::operator= (const Graphics &) private
ReleaseHDC()
VOID Graphics::ReleaseHDC (HDC hdc) inline
Definition at line 1352 of file gdiplusgraphics.h.
     {
         updateStatus(DllExports::GdipReleaseDC(nativeGraphics, hdc));
     }
References GdipReleaseDC(), nativeGraphics, and updateStatus().
ResetClip()
Status Graphics::ResetClip () inline
Definition at line 1356 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipResetClip(nativeGraphics));
     }
References GdipResetClip(), nativeGraphics, and updateStatus().
ResetTransform()
Status Graphics::ResetTransform () inline
Definition at line 1360 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipResetWorldTransform(
                 nativeGraphics));
     }
References GdipResetWorldTransform(), nativeGraphics, and updateStatus().
Restore()
Status Graphics::Restore (GraphicsState state) inline
Definition at line 1365 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipRestoreGraphics(
                 nativeGraphics, state));
     }
References GdipRestoreGraphics(), nativeGraphics, and updateStatus().
RotateTransform()
Status Graphics::RotateTransform (REAL angle, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 1370 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipRotateWorldTransform(
                 nativeGraphics, angle, order));
     }
References GdipRotateWorldTransform(), nativeGraphics, and updateStatus().
Save()
GraphicsState Graphics::Save () const inline
Definition at line 1376 of file gdiplusgraphics.h.
     {
         GraphicsState result = 0;
         updateStatus(DllExports::GdipSaveGraphics(
                 nativeGraphics, &result));
         return result;
     }
References GdipSaveGraphics(), nativeGraphics, and updateStatus().
ScaleTransform()
Status Graphics::ScaleTransform (REAL sx, REAL sy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 1383 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipScaleWorldTransform(
                 nativeGraphics, sx, sy, order));
     }
References GdipScaleWorldTransform(), nativeGraphics, sy, and updateStatus().
SetAbort()
VOID Graphics::SetAbort () inline
Definition at line 1389 of file gdiplusgraphics.h.
     {
         updateStatus(NotImplemented);
     }
References NotImplemented, and updateStatus().
SetClip() [1/6]
Status Graphics::SetClip (const Graphics * g, CombineMode combineMode = CombineModeReplace) inline
Definition at line 1393 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipGraphics(
                 nativeGraphics, g ? g->nativeGraphics : NULL,
                 combineMode));
     }
References GdipSetClipGraphics(), nativeGraphics, NULL, and updateStatus().
SetClip() [2/6]
Status Graphics::SetClip (const GraphicsPath * path, CombineMode combineMode = CombineModeReplace) inline
Definition at line 1416 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipPath(
                 nativeGraphics,
                 path ? path->nativePath : NULL,
                 combineMode));
     }
References GdipSetClipPath(), nativeGraphics, GraphicsPath::nativePath, NULL, and updateStatus().
SetClip() [3/6]
Status Graphics::SetClip (const Rect & rect, CombineMode combineMode = CombineModeReplace) inline
Definition at line 1408 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRectI(
                 nativeGraphics,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 combineMode));
     }
References GdipSetClipRectI(), Rect::Height, nativeGraphics, updateStatus(), Rect::Width, Rect::X, and Rect::Y.
SetClip() [4/6]
Status Graphics::SetClip (const RectF & rect, CombineMode combineMode = CombineModeReplace) inline
Definition at line 1400 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRect(
                 nativeGraphics,
                 rect.X, rect.Y, rect.Width, rect.Height,
                 combineMode));
     }
References GdipSetClipRect(), RectF::Height, nativeGraphics, updateStatus(), RectF::Width, RectF::X, and RectF::Y.
SetClip() [5/6]
Status Graphics::SetClip (const Region * region, CombineMode combineMode = CombineModeReplace) inline
Definition at line 1424 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipRegion(
                 nativeGraphics,
                 region ? region->nativeRegion : NULL,
                 combineMode));
     }
References GdipSetClipRegion(), nativeGraphics, Region::nativeRegion, NULL, and updateStatus().
SetClip() [6/6]
Status Graphics::SetClip (HRGN hRgn, CombineMode combineMode = CombineModeReplace) inline
Definition at line 1432 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetClipHrgn(
                 nativeGraphics, hRgn, combineMode));
     }
References GdipSetClipHrgn(), nativeGraphics, and updateStatus().
SetCompositingMode()
Status Graphics::SetCompositingMode (CompositingMode compositingMode) inline
Definition at line 1437 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetCompositingMode(
                 nativeGraphics, compositingMode));
     }
References GdipSetCompositingMode(), nativeGraphics, and updateStatus().
SetCompositingQuality()
Status Graphics::SetCompositingQuality (CompositingQuality compositingQuality) inline
Definition at line 1442 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetCompositingQuality(
                 nativeGraphics, compositingQuality));
     }
References GdipSetCompositingQuality(), nativeGraphics, and updateStatus().
SetInterpolationMode()
Status Graphics::SetInterpolationMode (InterpolationMode interpolationMode) inline
Definition at line 1447 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetInterpolationMode(
                 nativeGraphics, interpolationMode));
     }
References GdipSetInterpolationMode(), nativeGraphics, and updateStatus().
SetPageScale()
Status Graphics::SetPageScale (REAL scale) inline
Definition at line 1452 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetPageScale(
                 nativeGraphics, scale));
     }
References GdipSetPageScale(), nativeGraphics, and updateStatus().
SetPageUnit()
Status Graphics::SetPageUnit (Unit unit) inline
Definition at line 1457 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetPageUnit(
                 nativeGraphics, unit));
     }
References GdipSetPageUnit(), nativeGraphics, and updateStatus().
SetPixelOffsetMode()
Status Graphics::SetPixelOffsetMode (PixelOffsetMode pixelOffsetMode) inline
Definition at line 1462 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetPixelOffsetMode(
                 nativeGraphics, pixelOffsetMode));
     }
References GdipSetPixelOffsetMode(), nativeGraphics, and updateStatus().
SetRenderingOrigin()
Status Graphics::SetRenderingOrigin (INT x, INT y) inline
Definition at line 1467 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetRenderingOrigin(
                 nativeGraphics, x, y));
     }
References GdipSetRenderingOrigin(), nativeGraphics, and updateStatus().
SetSmoothingMode()
Status Graphics::SetSmoothingMode (SmoothingMode smoothingMode) inline
Definition at line 1472 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetSmoothingMode(
                 nativeGraphics, smoothingMode));
     }
References GdipSetSmoothingMode(), nativeGraphics, and updateStatus().
SetTextContrast()
Status Graphics::SetTextContrast (UINT contrast) inline
Definition at line 1477 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetTextContrast(
                 nativeGraphics, contrast));
     }
References GdipSetTextContrast(), nativeGraphics, and updateStatus().
SetTextRenderingHint()
Status Graphics::SetTextRenderingHint (TextRenderingHint textRenderingHint) inline
Definition at line 1482 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetTextRenderingHint(
                 nativeGraphics, textRenderingHint));
     }
References GdipSetTextRenderingHint(), nativeGraphics, and updateStatus().
SetTransform()
Status Graphics::SetTransform (const Matrix * matrix) inline
Definition at line 1487 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipSetWorldTransform(
                 nativeGraphics,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipSetWorldTransform(), nativeGraphics, NULL, and updateStatus().
TransformPoints() [1/2]
Status Graphics::TransformPoints (CoordinateSpace destSpace, CoordinateSpace srcSpace, Point * pts, INT count) const inline
Definition at line 1501 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipTransformPointsI(
                 nativeGraphics, destSpace, srcSpace,
                 pts, count));
     }
References GdipTransformPointsI(), nativeGraphics, and updateStatus().
TransformPoints() [2/2]
Status Graphics::TransformPoints (CoordinateSpace destSpace, CoordinateSpace srcSpace, PointF * pts, INT count) const inline
Definition at line 1493 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipTransformPoints(
                 nativeGraphics, destSpace, srcSpace,
                 pts, count));
     }
References GdipTransformPoints(), nativeGraphics, and updateStatus().
TranslateClip() [1/2]
Status Graphics::TranslateClip (INT dx, INT dy) inline
Definition at line 1514 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipTranslateClipI(
                 nativeGraphics, dx, dy));
     }
References GdipTranslateClipI(), nativeGraphics, and updateStatus().
TranslateClip() [2/2]
Status Graphics::TranslateClip (REAL dx, REAL dy) inline
Definition at line 1509 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipTranslateClip(
                 nativeGraphics, dx, dy));
     }
References GdipTranslateClip(), nativeGraphics, and updateStatus().
TranslateTransform()
Status Graphics::TranslateTransform (REAL dx, REAL dy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 1519 of file gdiplusgraphics.h.
     {
         return updateStatus(DllExports::GdipTranslateWorldTransform(
                 nativeGraphics, dx, dy, order));
     }
References GdipTranslateWorldTransform(), nativeGraphics, and updateStatus().
updateStatus()
Status Graphics::updateStatus (Status newStatus) const inline private
Definition at line 1530 of file gdiplusgraphics.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References lastStatus, and Ok.
Referenced by AddMetafileComment(), BeginContainer(), Clear(), DrawArc(), DrawBezier(), DrawBeziers(), DrawCachedBitmap(), DrawClosedCurve(), DrawCurve(), DrawDriverString(), DrawEllipse(), DrawImage(), DrawLine(), DrawLines(), DrawPath(), DrawPie(), DrawPolygon(), DrawRectangle(), DrawRectangles(), DrawString(), EndContainer(), EnumerateMetafile(), ExcludeClip(), FillClosedCurve(), FillEllipse(), FillPath(), FillPie(), FillPolygon(), FillRectangle(), FillRectangles(), FillRegion(), Flush(), GetClip(), GetClipBounds(), GetCompositingMode(), GetCompositingQuality(), GetDpiX(), GetDpiY(), GetHDC(), GetInterpolationMode(), GetNearestColor(), GetPageScale(), GetPageUnit(), GetPixelOffsetMode(), GetRenderingOrigin(), GetSmoothingMode(), GetTextContrast(), GetTextRenderingHint(), GetTransform(), GetVisibleClipBounds(), IntersectClip(), IsClipEmpty(), IsVisible(), IsVisibleClipEmpty(), MeasureCharacterRanges(), MeasureDriverString(), MeasureString(), MultiplyTransform(), ReleaseHDC(), ResetClip(), ResetTransform(), Restore(), RotateTransform(), Save(), ScaleTransform(), SetAbort(), SetClip(), SetCompositingMode(), SetCompositingQuality(), SetInterpolationMode(), SetPageScale(), SetPageUnit(), SetPixelOffsetMode(), SetRenderingOrigin(), SetSmoothingMode(), SetTextContrast(), SetTextRenderingHint(), SetTransform(), TransformPoints(), TranslateClip(), and TranslateTransform().
Friends And Related Function Documentation
Bitmap
friend class Bitmap friend
Definition at line 35 of file gdiplusgraphics.h.
CachedBitmap
friend class CachedBitmap friend
Definition at line 36 of file gdiplusgraphics.h.
Font
friend class Font friend
Definition at line 37 of file gdiplusgraphics.h.
GraphicsPath
friend class GraphicsPath friend
Definition at line 38 of file gdiplusgraphics.h.
Metafile
friend class Metafile friend
Definition at line 39 of file gdiplusgraphics.h.
Region
friend class Region friend
Definition at line 40 of file gdiplusgraphics.h.
Field Documentation
lastStatus
Status Graphics::lastStatus mutable private
Definition at line 1537 of file gdiplusgraphics.h.
Referenced by GetLastStatus(), Graphics(), MeasureCharacterRanges(), MeasureString(), and updateStatus().
nativeGraphics
GpGraphics* Graphics::nativeGraphics private
Definition at line 1536 of file gdiplusgraphics.h.
Referenced by AddMetafileComment(), BeginContainer(), Bitmap::Bitmap(), CachedBitmap::CachedBitmap(), Clear(), DrawArc(), DrawBezier(), DrawBeziers(), DrawCachedBitmap(), DrawClosedCurve(), DrawCurve(), DrawDriverString(), DrawEllipse(), DrawImage(), DrawLine(), DrawLines(), DrawPath(), DrawPie(), DrawPolygon(), DrawRectangle(), DrawRectangles(), DrawString(), EndContainer(), EnumerateMetafile(), Region::Equals(), ExcludeClip(), FillClosedCurve(), FillEllipse(), FillPath(), FillPie(), FillPolygon(), FillRectangle(), FillRectangles(), FillRegion(), Flush(), Region::GetBounds(), GetClip(), GetClipBounds(), GetCompositingMode(), GetCompositingQuality(), GetDpiX(), GetDpiY(), GetHDC(), Font::GetHeight(), Region::GetHRGN(), GetInterpolationMode(), Font::GetLogFontA(), Font::GetLogFontW(), GetNearestColor(), GetPageScale(), GetPageUnit(), GetPixelOffsetMode(), GetRenderingOrigin(), GetSmoothingMode(), GetTextContrast(), GetTextRenderingHint(), GetTransform(), GetVisibleClipBounds(), Graphics(), IntersectClip(), IsClipEmpty(), Region::IsEmpty(), Region::IsInfinite(), Region::IsVisible(), IsVisible(), IsVisibleClipEmpty(), MeasureCharacterRanges(), MeasureDriverString(), MeasureString(), MultiplyTransform(), ReleaseHDC(), ResetClip(), ResetTransform(), Restore(), RotateTransform(), Save(), ScaleTransform(), SetClip(), SetCompositingMode(), SetCompositingQuality(), SetInterpolationMode(), SetPageScale(), SetPageUnit(), SetPixelOffsetMode(), SetRenderingOrigin(), SetSmoothingMode(), SetTextContrast(), SetTextRenderingHint(), SetTransform(), TransformPoints(), TranslateClip(), TranslateTransform(), and ~Graphics().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusgraphics.h