ZEQ2-Lite: Source/Engine/tools/lcc/src/output.c File Reference
output.c File Reference
#include "c.h"
#include "token.h"
Macros
#define xx(a, b, c, d, e, f, g) g,
#define yy(a, b, c, d, e, f, g) g,
Functions
void fprint (FILE *f, const char *fmt,...)
static char * outd (long n, FILE *f, char *bp)
static char * outs (const char *str, FILE *f, char *bp)
static char * outu (unsigned long n, int base, FILE *f, char *bp)
void print (const char *fmt,...)
char * stringf (const char *fmt,...)
void vfprint (FILE *f, char *bp, const char *fmt, va_list ap)
Macro Definition Documentation
xx
#define xx (a, b, c, d, e, f, g) g,
yy
#define yy (a, b, c, d, e, f, g) g,
Function Documentation
fprint()
void fprint (FILE * f, const char * fmt, ...)
Definition at line 47 of file output.c.
{
     va_list ap;
     va_start(ap, fmt);
     vfprint(f, NULL, fmt, ap);
     va_end(ap);
 }
References fmt, NULL, and vfprint().
Referenced by dumpcover(), dumpregs(), dumprule(), dumptree(), error(), expect(), fatal(), genreload(), genspill(), getrule(), linearize(), main(), main_init(), outtype(), printdag(), printdecl(), printnode(), printtoken(), printtree1(), printtype(), prtype(), prune(), ralloc(), reduce(), reprune(), requate(), rewrite(), rtarget(), and skipto().
outd()
static char* outd (long n, FILE * f, char * bp) static
Definition at line 13 of file output.c.
{
     unsigned long m;
     char buf[25], *s = buf + sizeof buf;
     *--s = '\0';
     if (n < 0)
         m = -n;
     else
         m = n;
     do
         *--s = m%10 + '0';
     while ((m /= 10) != 0);
     if (n < 0)
         *--s = '-';
     return outs(s, f, bp);
 }
References bp, m, and outs().
Referenced by vfprint().
outs()
static char* outs (const char * str, FILE * f, char * bp) static
Definition at line 4 of file output.c.
{
     if (f)
         fputs(str, f);
     else
         while ((*bp = *str++))
             bp++;
     return bp;
 }
References bp.
Referenced by outd(), outu(), and vfprint().
outu()
static char* outu (unsigned long n, int base, FILE * f, char * bp) static
Definition at line 30 of file output.c.
{
     char buf[25], *s = buf + sizeof buf;
     *--s = '\0';
     do
         *--s = "0123456789abcdef"[n%base];
     while ((n /= base) != 0);
     return outs(s, f, bp);
 }
References bp, and outs().
Referenced by vfprint().
print()
void print (const char * fmt, ...)
Definition at line 39 of file output.c.
{
     va_list ap;
     va_start(ap, fmt);
     vfprint(stdout, NULL, fmt, ap);
     va_end(ap);
 }
References fmt, NULL, and vfprint().
stringf()
char* stringf (const char * fmt, ...)
Definition at line 56 of file output.c.
{
     char buf[1024];
     va_list ap;
     va_start(ap, fmt);
     vfprint(NULL, buf, fmt, ap);
     va_end(ap);
     return string(buf);
 }
References fmt, NULL, strsave(), and vfprint().
vfprint()
void vfprint (FILE * f, char * bp, const char * fmt, va_list ap)
Definition at line 67 of file output.c.
{
     for (; *fmt; fmt++)
         if (*fmt == '%')
             switch (*++fmt) {
             case 'd': bp = outd(va_arg(ap, int), f, bp); break;
             case 'D': bp = outd(va_arg(ap, long), f, bp); break;
             case 'U': bp = outu(va_arg(ap, unsigned long), 10, f, bp); break;
             case 'u': bp = outu(va_arg(ap, unsigned), 10, f, bp); break;
             case 'o': bp = outu(va_arg(ap, unsigned), 8, f, bp); break;
             case 'X': bp = outu(va_arg(ap, unsigned long), 16, f, bp); break;
             case 'x': bp = outu(va_arg(ap, unsigned), 16, f, bp); break;
             case 'f': case 'e':
             case 'g': {
                     static char format[] = "%f";
                     char buf[128];
                     format[1] = *fmt;
                     sprintf(buf, format, va_arg(ap, double));
                     bp = outs(buf, f, bp);
                   }
 ; break;
             case 's': bp = outs(va_arg(ap, char *), f, bp); break;
             case 'p': {
                 void *p = va_arg(ap, void *);
                 if (p)
                     bp = outs("0x", f, bp);
                 bp = outu((unsigned long)p, 16, f, bp);
                 break;
                   }
             case 'c': if (f) fputc(va_arg(ap, int), f); else *bp++ = va_arg(ap, int); break;
             case 'S': { char *s = va_arg(ap, char *);
                     int n = va_arg(ap, int);
                     if (s) {
                         for ( ; n-- > 0; s++)
                             if (f) (void)putc(*s, f); else *bp++ = *s;
                     }
  } break;
             case 'k': { int t = va_arg(ap, int);
                     static char *tokens[] = {
 #define xx(a,b,c,d,e,f,g) g,
 #define yy(a,b,c,d,e,f,g) g,
 #include "token.h"
                     };
                     assert(tokens[t&0177]);
                     bp = outs(tokens[t&0177], f, bp);
  } break;
             case 't': { Type ty = va_arg(ap, Type);
                     assert(f);
                     outtype(ty ? ty : voidtype, f);
  } break;
             case 'w': { Coordinate *p = va_arg(ap, Coordinate *);
                     if (p->file && *p->file) {
                         bp = outs(p->file, f, bp);
                         bp = outs(":", f, bp);
                     }
                     bp = outd(p->y, f, bp);
  } break;
             case 'I': { int n = va_arg(ap, int);
                     while (--n >= 0)
                         if (f) (void)putc(' ', f); else *bp++ = ' ';
  } break;
             default:  if (f) (void)putc(*fmt, f); else *bp++ = *fmt; break;
             }
         else if (f)
             (void)putc(*fmt, f);
         else
             *bp++ = *fmt;
     if (!f)
         *bp = '\0';
 }
References bp, fmt, outd(), outs(), outtype(), outu(), void(), and voidtype.
Referenced by error(), fprint(), print(), stringf(), and warning().