ZEQ2-Lite: Tools/MinGW/include/gdiplus/gdiplusimagecodec.h File Reference
gdiplusimagecodec.h File Reference
Functions
static __inline__ GpStatus GetImageDecoders (UINT numDecoders, UINT size, ImageCodecInfo *decoders)
static __inline__ GpStatus GetImageDecodersSize (UINT *numDecoders, UINT *size)
static __inline__ GpStatus GetImageEncoders (UINT numEncoders, UINT size, ImageCodecInfo *encoders)
static __inline__ GpStatus GetImageEncodersSize (UINT *numEncoders, UINT *size)
Function Documentation
GetImageDecoders()
static __inline__ GpStatus GetImageDecoders (UINT numDecoders, UINT size, ImageCodecInfo * decoders) static
Definition at line 29 of file gdiplusimagecodec.h.
 {
     #ifdef __cplusplus
     return DllExports::GdipGetImageDecoders(numDecoders, size, decoders);
     #else
     return GdipGetImageDecoders(numDecoders, size, decoders);
     #endif
 }
References GdipGetImageDecoders().
GetImageDecodersSize()
static __inline__ GpStatus GetImageDecodersSize (UINT * numDecoders, UINT * size) static
Definition at line 39 of file gdiplusimagecodec.h.
 {
     #ifdef __cplusplus
     return DllExports::GdipGetImageDecodersSize(numDecoders, size);
     #else
     return GdipGetImageDecodersSize(numDecoders, size);
     #endif
 }
References GdipGetImageDecodersSize().
GetImageEncoders()
static __inline__ GpStatus GetImageEncoders (UINT numEncoders, UINT size, ImageCodecInfo * encoders) static
Definition at line 48 of file gdiplusimagecodec.h.
 {
     #ifdef __cplusplus
     return DllExports::GdipGetImageEncoders(numEncoders, size, encoders);
     #else
     return GdipGetImageEncoders(numEncoders, size, encoders);
     #endif
 }
References GdipGetImageEncoders().
GetImageEncodersSize()
static __inline__ GpStatus GetImageEncodersSize (UINT * numEncoders, UINT * size) static
Definition at line 58 of file gdiplusimagecodec.h.
 {
     #ifdef __cplusplus
     return DllExports::GdipGetImageEncodersSize(numEncoders, size);
     #else
     return GdipGetImageEncodersSize(numEncoders, size);
     #endif
 }
References GdipGetImageEncodersSize().