ZEQ2-Lite: Source/Engine/tools/lcc/etc/lcc.c File Reference
lcc.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <ctype.h>
#include <signal.h>
#include <unistd.h>
Data Structures
struct List
Macros
#define _P_WAIT 0
#define TEMPDIR "/tmp"
#define xx(v) if ((s = getenv(#v))) fprintf(stderr, #v "=%s\n", s)
Functions
static void * alloc (int)
static List append (char *, List)
char * basename (char *)
static int callsys (char **av)
static int callsys (char *[])
static int compile (char *, char *)
static void compose (char *[], List, List, List)
char * concat (char *, char *)
static void error (char *, char *)
static char * exists (char *)
static int filename (char *, char *)
static List find (char *, List)
static char * first (char *)
int fork (void)
int getpid (void)
static void help (void)
static void initinputs (void)
static void interrupt (int)
int main (int, char *[])
static void opt (char *)
int option (char *)
static List path2list (const char *)
char * replace (const char *, int, int)
static void rm (List)
static int spawn (const char *cmdname, char **argv)
char * stringf (const char *,...)
char * strsave (const char *)
int suffix (char *, char *[], int)
char * tempname (char *)
void UpdatePaths (const char *lccBinary)
int wait (int *)
Variables
static int ac
static List alist
char * as []
static char ** av
static int cflag
static List clist
char * com []
char * cpp []
static int Eflag
static int errcnt
static List ilist
char * include []
char inputs []
static List lccinputs
char * ld []
static List llist [2]
static char * outfile
static List plist
static char * progname
static char rcsid [] = "Id: dummy rcsid"
static List rmlist
static int Sflag = 1
char * suffixes []
char * tempdir = TEMPDIR
static int verbose
Macro Definition Documentation
_P_WAIT
#define _P_WAIT 0
Definition at line 281 of file lcc.c.
TEMPDIR
#define TEMPDIR "/tmp"
Definition at line 17 of file lcc.c.
xx
#define xx (v) if ((s = getenv(#v))) fprintf(stderr, #v "=%s\n", s)
Function Documentation
alloc()
static void * alloc (int n) static
Definition at line 176 of file lcc.c.
{
     static char *avail, *limit;
     n = (n + sizeof(char *) - 1)&~(sizeof(char *) - 1);
     if (n >= limit - avail) {
         avail = malloc(n + 4*1024);
         assert(avail);
         limit = avail + n + 4*1024;
     }
     avail += n;
     return avail - n;
 }
References limit.
Referenced by append(), compose(), concat(), main(), strsave(), VM_LoadQVM(), and yylex().
append()
static List append (char * str, List list) static
Definition at line 190 of file lcc.c.
{
     List p = alloc(sizeof *p);
     p->str = str;
     if (list) {
         p->link = list->link;
         list->link = p;
     } else
         p->link = p;
     return p;
 }
References alloc(), and List::link.
Referenced by attach(), bbfile(), bbincr(), compile(), compose(), compound(), dcllocal(), enumdcl(), filename(), ftype(), initinputs(), locus(), main(), opt(), parameters(), path2list(), printproto(), prof_init(), tempname(), and use().
basename()
char * basename (char * name)
Definition at line 203 of file lcc.c.
{
     char *s, *b, *t = 0;
     for (b = s = name; *s; s++)
         if (*s == '/' || *s == '\\') {
             b = s + 1;
             t = 0;
         } else if (*s == '.')
             t = s;
     s = strsave(b);
     if (t)
         s[t-b] = 0;
     return s;
 }
References strsave().
Referenced by filename(), FS_LoadZipFile(), opt(), and Sys_Basename().
callsys() [1/2]
static int callsys (char ** av) static
Definition at line 315 of file lcc.c.
{
     int i, status = 0;
     static char **argv;
     static int argc;
     char *executable;
     for (i = 0; av[i] != NULL; i++)
         ;
     if (i + 1 > argc) {
         argc = i + 1;
         if (argv == NULL)
             argv = malloc(argc*sizeof *argv);
         else
             argv = realloc(argv, argc*sizeof *argv);
         assert(argv);
     }
     for (i = 0; status == 0 && av[i] != NULL; ) {
         int j = 0;
         char *s = NULL;
         for ( ; av[i] != NULL && (s = strchr(av[i], '\n')) == NULL; i++)
             argv[j++] = av[i];
         if (s != NULL) {
             if (s > av[i])
                 argv[j++] = stringf("%.*s", s - av[i], av[i]);
             if (s[1] != '\0')
                 av[i] = s + 1;
             else
                 i++;
         }
         argv[j] = NULL;
         executable = strsave( argv[0] );
         argv[0] = stringf( "\"%s\"", argv[0] );
         if (verbose > 0) {
             int k;
             fprintf(stderr, "%s", argv[0]);
             for (k = 1; argv[k] != NULL; k++)
                 fprintf(stderr, " %s", argv[k]);
             fprintf(stderr, "\n");
         }
         if (verbose < 2)
             status = spawn(executable, argv);
         if (status == -1) {
             fprintf(stderr, "%s: ", progname);
             perror(argv[0]);
         }
     }
     return status;
 }
References av, NULL, progname, spawn(), stringf(), strsave(), and verbose.
callsys() [2/2]
static int callsys (char * []) static
Referenced by compile(), filename(), and main().
compile()
static int compile (char * src, char * dst) static
Definition at line 375 of file lcc.c.
{
     compose(com, clist, append(src, 0), append(dst, 0));
     return callsys(av);
 }
References append(), av, callsys(), clist, com, and compose().
Referenced by filename().
compose()
static void compose (char * cmd[], List a, List b, List c) static
Definition at line 381 of file lcc.c.
{
     int i, j;
     List lists[3];
     lists[0] = a;
     lists[1] = b;
     lists[2] = c;
     for (i = j = 0; cmd[i]; i++) {
         char *s = strchr(cmd[i], '$');
         if (s && isdigit(s[1])) {
             int k = s[1] - '0';
             assert(k >=1 && k <= 3);
             if ((b = lists[k-1])) {
                 b = b->link;
                 av[j] = alloc(strlen(cmd[i]) + strlen(b->str) - 1);
                 strncpy(av[j], cmd[i], s - cmd[i]);
                 av[j][s-cmd[i]] = '\0';
                 strcat(av[j], b->str);
                 strcat(av[j++], s + 2);
                 while (b != lists[k-1]) {
                     b = b->link;
                     assert(j < ac);
                     av[j++] = b->str;
                 };
             }
         } else if (*cmd[i]) {
             assert(j < ac);
             av[j++] = cmd[i];
         }
     }
     av[j] = NULL;
 }
References ac, alloc(), av, and NULL.
Referenced by compile(), dclglobal(), dcllocal(), filename(), and main().
concat()
char* concat (char * s1, char * s2)
Definition at line 365 of file lcc.c.
{
     int n = strlen(s1);
     char *s = alloc(n + strlen(s2) + 1);
     strcpy(s, s1);
     strcpy(s + n, s2);
     return s;
 }
References alloc().
Referenced by filename(), initinputs(), main(), opt(), option(), and UpdatePaths().
error()
static void error (char * fmt, char * msg) static
Definition at line 415 of file lcc.c.
{
     fprintf(stderr, "%s: ", progname);
     fprintf(stderr, fmt, msg);
     fprintf(stderr, "\n");
     errcnt++;
 }
References errcnt, fmt, and progname.
Referenced by main(), and opt().
exists()
static char * exists (char * name) static
Definition at line 423 of file lcc.c.
{
     List b;
     if ( (name[0] == '/' || name[0] == '\\' || name[2] == ':')
     && access(name, 4) == 0)
         return name;
     if (!(name[0] == '/' || name[0] == '\\' || name[2] == ':')
     && (b = lccinputs))
         do {
             b = b->link;
             if (b->str[0]) {
                 char buf[1024];
                 sprintf(buf, "%s/%s", b->str, name);
                 if (access(buf, 4) == 0)
                     return strsave(buf);
             } else if (access(name, 4) == 0)
                 return name;
         } while (b != lccinputs);
     if (verbose > 1)
         return name;
     return 0;
 }
References lccinputs, strsave(), and verbose.
Referenced by main().
filename()
static int filename (char * name, char * base) static
Definition at line 460 of file lcc.c.
{
     int status = 0;
     static char *stemp, *itemp;
     if (base == 0)
         base = basename(name);
     switch (suffix(name, suffixes, 4)) {
     case 0: /* C source files */
         compose(cpp, plist, append(name, 0), 0);
         if (Eflag) {
             status = callsys(av);
             break;
         }
         if (itemp == NULL)
             itemp = tempname(first(suffixes[1]));
         compose(cpp, plist, append(name, 0), append(itemp, 0));
         status = callsys(av);
         if (status == 0)
             return filename(itemp, base);
         break;
     case 1: /* preprocessed source files */
         if (Eflag)
             break;
         if (Sflag)
             status = compile(name, outfile ? outfile : concat(base, first(suffixes[2])));
         else if ((status = compile(name, stemp?stemp:(stemp=tempname(first(suffixes[2]))))) == 0)
             return filename(stemp, base);
         break;
     case 2: /* assembly language files */
         if (Eflag)
             break;
         if (!Sflag) {
             char *ofile;
             if (cflag && outfile)
                 ofile = outfile;
             else if (cflag)
                 ofile = concat(base, first(suffixes[3]));
             else
                 ofile = tempname(first(suffixes[3]));
             compose(as, alist, append(name, 0), append(ofile, 0));
             status = callsys(av);
             if (!find(ofile, llist[1]))
                 llist[1] = append(ofile, llist[1]);
         }
         break;
     case 3: /* object files */
         if (!find(name, llist[1]))
             llist[1] = append(name, llist[1]);
         break;
     default:
         if (Eflag) {
             compose(cpp, plist, append(name, 0), 0);
             status = callsys(av);
         }
         llist[1] = append(name, llist[1]);
         break;
     }
     if (status)
         errcnt++;
     return status;
 }
References alist, append(), as, av, basename(), callsys(), cflag, compile(), compose(), concat(), cpp, Eflag, errcnt, find(), first(), llist, NULL, outfile, plist, Sflag, suffix(), suffixes, and tempname().
Referenced by main().
find()
static List find (char * str, List list) static
Definition at line 523 of file lcc.c.
{
     List b;
     if ((b = list))
         do {
             if (strcmp(str, b->str) == 0)
                 return b;
         } while ((b = b->link) != list);
     return 0;
 }
Referenced by filename(), path2list(), and Q_stristr().
first()
static char* first (char * list) static
Definition at line 447 of file lcc.c.
{
     char *s = strchr(list, ';');
     if (s) {
         char buf[1024];
         strncpy(buf, list, s-list);
         buf[s-list] = '\0';
         return strsave(buf);
     } else
         return list;
 }
References list(), and strsave().
Referenced by filename(), main(), and opt().
fork()
int fork (void)
Referenced by spawn(), and Sys_Exec().
getpid()
int getpid (void)
Referenced by Sys_PID(), and tempname().
help()
static void help (void) static
Definition at line 535 of file lcc.c.
{
     static char *msgs[] = {
 "", " [ option | file ]...\n",
 "   except for -l, options are processed left-to-right before files\n",
 "   unrecognized options are taken to be linker options\n",
 "-A warn about nonANSI usage; 2nd -A warns more\n",
 "-b emit expression-level profiling code; see bprint(1)\n",
 #ifdef sparc
 "-Bstatic -Bdynamic specify static or dynamic libraries\n",
 #endif
 "-Bdir/ use the compiler named `dir/rcc'\n",
 "-c compile only\n",
 "-dn    set switch statement density to `n'\n",
 "-Dname -Dname=def  define the preprocessor symbol `name'\n",
 "-E run only the preprocessor on the named C programs and unsuffixed files\n",
 "-g produce symbol table information for debuggers\n",
 "-help or -?    print this message\n",
 "-Idir  add `dir' to the beginning of the list of #include directories\n",
 "-lx    search library `x'\n",
 "-N do not search the standard directories for #include files\n",
 "-n emit code to check for dereferencing zero pointers\n",
 "-O is ignored\n",
 "-o file    leave the output in `file'\n",
 "-P print ANSI-style declarations for globals\n",
 "-p -pg emit profiling code; see prof(1) and gprof(1)\n",
 "-S compile to assembly language\n",
 #ifdef linux
 "-static    specify static libraries (default is dynamic)\n",
 #endif
 "-t -tname  emit function tracing calls to printf or to `name'\n",
 "-target name   is ignored\n",
 "-tempdir=dir   place temporary files in `dir/'", "\n"
 "-Uname undefine the preprocessor symbol `name'\n",
 "-v show commands as they are executed; 2nd -v suppresses execution\n",
 "-w suppress warnings\n",
 "-Woarg specify system-specific `arg'\n",
 "-W[pfal]arg    pass `arg' to the preprocessor, compiler, assembler, or linker\n",
     0 };
     int i;
     char *s;
     msgs[0] = progname;
     for (i = 0; msgs[i]; i++) {
         fprintf(stderr, "%s", msgs[i]);
         if (strncmp("-tempdir", msgs[i], 8) == 0 && tempdir)
             fprintf(stderr, "; default=%s", tempdir);
     }
 #define xx(v) if ((s = getenv(#v))) fprintf(stderr, #v "=%s\n", s)
     xx(LCCINPUTS);
     xx(LCCDIR);
 #undef xx
 }
References progname, tempdir, and xx.
Referenced by main(), and opt().
initinputs()
static void initinputs (void) static
Definition at line 589 of file lcc.c.
{
     char *s = getenv("LCCINPUTS");
     List b;
     if (s == 0 || (s = inputs)[0] == 0)
         s = ".";
     if (s) {
         lccinputs = path2list(s);
         if ((b = lccinputs))
             do {
                 b = b->link;
                 if (strcmp(b->str, ".") != 0) {
                     ilist = append(concat("-I", b->str), ilist);
                     if (strstr(com[1], "win32") == NULL)
                         llist[0] = append(concat("-L", b->str), llist[0]);
                 } else
                     b->str = "";
             } while (b != lccinputs);
     }
 }
References append(), com, concat(), ilist, inputs, lccinputs, llist, NULL, and path2list().
Referenced by main().
interrupt()
static void interrupt (int n) static
Definition at line 611 of file lcc.c.
{
     rm(rmlist);
     exit(n = 100);
 }
References rm(), and rmlist.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 78 of file lcc.c.
{
     int i, j, nf;
     progname = argv[0];
     UpdatePaths( progname );
     ac = argc + 50;
     av = alloc(ac*sizeof(char *));
     if (signal(SIGINT, SIG_IGN) != SIG_IGN)
         signal(SIGINT, interrupt);
     if (signal(SIGTERM, SIG_IGN) != SIG_IGN)
         signal(SIGTERM, interrupt);
 #ifdef SIGHUP
     if (signal(SIGHUP, SIG_IGN) != SIG_IGN)
         signal(SIGHUP, interrupt);
 #endif
     if (getenv("TMP"))
         tempdir = getenv("TMP");
     else if (getenv("TEMP"))
         tempdir = getenv("TEMP");
     else if (getenv("TMPDIR"))
         tempdir = getenv("TMPDIR");
     assert(tempdir);
     i = strlen(tempdir);
     for (; (i > 0 && tempdir[i-1] == '/') || tempdir[i-1] == '\\'; i--)
         tempdir[i-1] = '\0';
     if (argc <= 1) {
         help();
         exit(0);
     }
     plist = append("-D__LCC__", 0);
     initinputs();
     if (getenv("LCCDIR"))
         option(stringf("-lccdir=%s", getenv("LCCDIR")));
     for (nf = 0, i = j = 1; i < argc; i++) {
         if (strcmp(argv[i], "-o") == 0) {
             if (++i < argc) {
                 if (suffix(argv[i], suffixes, 2) >= 0) {
                     error("-o would overwrite %s", argv[i]);
                     exit(8);
                 }
                 outfile = argv[i];
                 continue;
             } else {
                 error("unrecognized option `%s'", argv[i-1]);
                 exit(8);
             }
         } else if (strcmp(argv[i], "-target") == 0) {
             if (argv[i+1] && *argv[i+1] != '-')
                 i++;
             continue;
         } else if (*argv[i] == '-' && argv[i][1] != 'l') {
             opt(argv[i]);
             continue;
         } else if (*argv[i] != '-' && suffix(argv[i], suffixes, 3) >= 0)
             nf++;
         argv[j++] = argv[i];
     }
     if ((cflag || Sflag) && outfile && nf != 1) {
         fprintf(stderr, "%s: -o %s ignored\n", progname, outfile);
         outfile = 0;
     }
     argv[j] = 0;
     for (i = 0; include[i]; i++)
         plist = append(include[i], plist);
     if (ilist) {
         List b = ilist;
         do {
             b = b->link;
             plist = append(b->str, plist);
         } while (b != ilist);
     }
     ilist = 0;
     for (i = 1; argv[i]; i++)
         if (*argv[i] == '-')
             opt(argv[i]);
         else {
             char *name = exists(argv[i]);
             if (name) {
                 if (strcmp(name, argv[i]) != 0
                 || (nf > 1 && suffix(name, suffixes, 3) >= 0))
                     fprintf(stderr, "%s:\n", name);
                 filename(name, 0);
             } else
                 error("can't find `%s'", argv[i]);
         }
     if (errcnt == 0 && !Eflag && !Sflag && !cflag && llist[1]) {
         compose(ld, llist[0], llist[1],
             append(outfile ? outfile : concat("a", first(suffixes[4])), 0));
         if (callsys(av))
             errcnt++;
     }
     rm(rmlist);
     return errcnt ? EXIT_FAILURE : EXIT_SUCCESS;
 }
opt()
static void opt (char * arg) static
Definition at line 617 of file lcc.c.
{
     switch (arg[1]) {   /* multi-character options */
     case 'W':   /* -Wxarg */
         if (arg[2] && arg[3])
             switch (arg[2]) {
             case 'o':
                 if (option(&arg[3]))
                     return;
                 break;
             case 'p':
                 plist = append(&arg[3], plist);
                 return;
             case 'f':
                 if (strcmp(&arg[3], "-C") || option("-b")) {
                     clist = append(&arg[3], clist);
                     return;
                 }
                 break; /* and fall thru */
             case 'a':
                 alist = append(&arg[3], alist);
                 return;
             case 'l':
                 llist[0] = append(&arg[3], llist[0]);
                 return;
             }
         fprintf(stderr, "%s: %s ignored\n", progname, arg);
         return;
     case 'd':   /* -dn */
         arg[1] = 's';
         clist = append(arg, clist);
         return;
     case 't':   /* -t -tname -tempdir=dir */
         if (strncmp(arg, "-tempdir=", 9) == 0)
             tempdir = arg + 9;
         else
             clist = append(arg, clist);
         return;
     case 'p':   /* -p -pg */
         if (option(arg))
             clist = append(arg, clist);
         else
             fprintf(stderr, "%s: %s ignored\n", progname, arg);
         return;
     case 'D':   /* -Dname -Dname=def */
     case 'U':   /* -Uname */
     case 'I':   /* -Idir */
         plist = append(arg, plist);
         return;
     case 'B':   /* -Bdir -Bstatic -Bdynamic */
 #ifdef sparc
         if (strcmp(arg, "-Bstatic") == 0 || strcmp(arg, "-Bdynamic") == 0)
             llist[1] = append(arg, llist[1]);
         else
 #endif
         {
         static char *path;
         if (path)
             error("-B overwrites earlier option", 0);
         path = arg + 2;
         if (strstr(com[1], "win32") != NULL)
             com[0] = concat(replace(path, '/', '\\'), concat("rcc", first(suffixes[4])));
         else
             com[0] = concat(path, "rcc");
         if (path[0] == 0)
             error("missing directory in -B option", 0);
         }
         return;
     case 'h':
         if (strcmp(arg, "-help") == 0) {
             static int printed = 0;
     case '?':
             if (!printed)
                 help();
             printed = 1;
             return;
         }
 #ifdef linux
     case 's':
         if (strcmp(arg,"-static") == 0) {
             if (!option(arg))
                 fprintf(stderr, "%s: %s ignored\n", progname, arg);
             return;
         }
 #endif
     }
     if (arg[2] == 0)
         switch (arg[1]) {   /* single-character options */
         case 'S':
             Sflag++;
             return;
         case 'O':
             fprintf(stderr, "%s: %s ignored\n", progname, arg);
             return;
         case 'A': case 'n': case 'w': case 'P':
             clist = append(arg, clist);
             return;
         case 'g': case 'b':
             if (option(arg))
                 clist = append(arg[1] == 'g' ? "-g2" : arg, clist);
             else
                 fprintf(stderr, "%s: %s ignored\n", progname, arg);
             return;
         case 'G':
             if (option(arg)) {
                 clist = append("-g3", clist);
                 llist[0] = append("-N", llist[0]);
             } else
                 fprintf(stderr, "%s: %s ignored\n", progname, arg);
             return;
         case 'E':
             Eflag++;
             return;
         case 'c':
             cflag++;
             return;
         case 'N':
             if (strcmp(basename(cpp[0]), "gcc-cpp") == 0)
                 plist = append("-nostdinc", plist);
             include[0] = 0;
             ilist = 0;
             return;
         case 'v':
             if (verbose++ == 0) {
                 if (strcmp(basename(cpp[0]), "gcc-cpp") == 0)
                     plist = append(arg, plist);
                 clist = append(arg, clist);
                 fprintf(stderr, "%s %s\n", progname, rcsid);
             }
             return;
         }
     if (cflag || Sflag || Eflag)
         fprintf(stderr, "%s: %s ignored\n", progname, arg);
     else
         llist[1] = append(arg, llist[1]);
 }
References alist, append(), basename(), cflag, clist, com, concat(), cpp, Eflag, error(), first(), help(), ilist, include, llist, NULL, option(), plist, printed(), progname, rcsid, replace(), Sflag, suffixes, tempdir, and verbose.
Referenced by _jitter_buffer_update_delay(), compute_opt_delay(), jitter_buffer_get(), and main().
option()
int option (char *)
Definition at line 50 of file bytecode.c.
                       {
     if (strncmp(arg, "-lccdir=", 8) == 0) {
         cpp[0] = concat(&arg[8], "/q3cpp" BINEXT);
         include[0] = concat("-I", concat(&arg[8], "/include"));
         com[0] = concat(&arg[8], "/q3rcc" BINEXT);
     } else if (strcmp(arg, "-p") == 0 || strcmp(arg, "-pg") == 0) {
         fprintf( stderr, "no profiling supported, %s ignored.\n", arg);
     } else if (strcmp(arg, "-b") == 0)
         ;
     else if (strcmp(arg, "-g") == 0)
         fprintf( stderr, "no debugging supported, %s ignored.\n", arg);
     else if (strncmp(arg, "-ld=", 4) == 0 || strcmp(arg, "-static") == 0) {
         fprintf( stderr, "no linking supported, %s ignored.\n", arg);
     } else
         return 0;
     return 1;
 }
References BINEXT, com, concat(), cpp, and include.
Referenced by main(), opt(), and PM_Melee().
path2list()
static List path2list (const char * path) static
Definition at line 754 of file lcc.c.
{
     List list = NULL;
     char sep = ':';
     if (path == NULL)
         return NULL;
     if (strchr(path, ';'))
         sep = ';';
     while (*path) {
         char *p, buf[512];
         if ((p = strchr(path, sep))) {
             assert(p - path < sizeof buf);
             strncpy(buf, path, p - path);
             buf[p-path] = '\0';
         } else {
             assert(strlen(path) < sizeof buf);
             strcpy(buf, path);
         }
         if (!find(buf, list))
             list = append(strsave(buf), list);
         if (p == 0)
             break;
         path = p + 1;
     }
     return list;
 }
References append(), find(), list(), NULL, and strsave().
Referenced by initinputs().
replace()
char * replace (const char * str, int from, int to)
Definition at line 782 of file lcc.c.
{
     char *s = strsave(str), *p = s;
     for ( ; (p = strchr(p, from)) != NULL; p++)
         *p = to;
     return s;
 }
References NULL, and strsave().
Referenced by CG_DrawChat(), opt(), and tempname().
rm()
static void rm (List list) static
Definition at line 791 of file lcc.c.
{
     if (list) {
         List b = list;
         if (verbose)
             fprintf(stderr, "rm");
         do {
             if (verbose)
                 fprintf(stderr, " %s", b->str);
             if (verbose < 2)
                 remove(b->str);
         } while ((b = b->link) != list);
         if (verbose)
             fprintf(stderr, "\n");
     }
 }
References list(), and verbose.
Referenced by interrupt(), and main().
spawn()
static int spawn (const char * cmdname, char ** argv) static
Definition at line 287 of file lcc.c.
{
     int pid, n, status;
     switch (pid = fork()) {
     case -1:
         fprintf(stderr, "%s: no more processes\n", progname);
         return 100;
     case 0:
         // TTimo removing hardcoded paths, searching in $PATH
         execvp(cmdname, argv);
         fprintf(stderr, "%s: ", progname);
         perror(cmdname);
         fflush(stdout);
         exit(100);
     }
     while ((n = wait(&status)) != pid && n != -1)
         ;
     if (n == -1)
         status = -1;
     if (status&0377) {
         fprintf(stderr, "%s: fatal error in %s\n", progname, cmdname);
         status |= 0400;
     }
     return (status>>8)&0377;
 }
References fork(), progname, and wait().
Referenced by callsys().
stringf()
char * stringf (const char * fmt, ...)
Definition at line 813 of file lcc.c.
{
     char buf[1024];
     va_list ap;
     va_start(ap, fmt);
     vsprintf(buf, fmt, ap);
     va_end(ap);
     return strsave(buf);
 }
Referenced by address(), callsys(), dclparam(), defsymbol(), funcname(), function(), local(), main(), mkreg(), opname(), tempname(), typestring(), and vtoa().
strsave()
char * strsave (const char * str)
Definition at line 808 of file lcc.c.
{
     return strcpy(alloc(strlen(str)+1), str);
 }
References alloc().
Referenced by basename(), callsys(), exists(), first(), path2list(), replace(), and stringf().
suffix()
int suffix (char * name, char * tails[], int n)
Definition at line 824 of file lcc.c.
{
     int i, len = strlen(name);
     for (i = 0; i < n; i++) {
         char *s = tails[i], *t;
         for ( ; (t = strchr(s, ';')); s = t + 1) {
             int m = t - s;
             if (len > m && strncmp(&name[len-m], s, m) == 0)
                 return i;
         }
         if (*s) {
             int m = strlen(s);
             if (len > m && strncmp(&name[len-m], s, m) == 0)
                 return i;
         }
     }
     return -1;
 }
References m.
Referenced by defconst(), emittest(), filename(), main(), SV_ParseCIDRNotation(), and tempname().
tempname()
char * tempname (char * suffix)
Definition at line 844 of file lcc.c.
{
     static int n;
     char *name = stringf("%s/lcc%d%d%s", tempdir, getpid(), n++, suffix);
     if (strstr(com[1], "win32") != NULL)
         name = replace(name, '/', '\\');
     rmlist = append(name, rmlist);
     return name;
 }
References append(), com, getpid(), NULL, replace(), rmlist, stringf(), suffix(), and tempdir.
Referenced by filename().
UpdatePaths()
void UpdatePaths (const char * lccBinary)
Definition at line 33 of file bytecode.c.
 {
     char basepath[ 1024 ];
     char *p;
     strncpy( basepath, lccBinary, 1024 );
     p = strrchr( basepath, PATH_SEP );
     if( p )
     {
         *( p + 1 ) = '\0';
         cpp[ 0 ] = concat( basepath, "q3cpp" BINEXT );
         com[ 0 ] = concat( basepath, "q3rcc" BINEXT );
     }
 }
References basepath(), BINEXT, com, concat(), and cpp.
Referenced by main().
wait()
int wait (int *)
Referenced by spawn(), and Sys_Exec().
Variable Documentation
ac
int ac static
Definition at line 70 of file lcc.c.
Referenced by _spx_autocorr(), _spx_lpc(), compose(), main(), and PPC_ComputeCode().
alist
List alist static
Definition at line 64 of file lcc.c.
Referenced by filename(), and opt().
as
char * as[]
Definition at line 55 of file lcc.c.
Referenced by filename().
av
char** av static
Definition at line 71 of file lcc.c.
Referenced by AddSkyPolygon(), callsys(), compile(), compose(), filename(), and main().
cflag
int cflag static
Definition at line 61 of file lcc.c.
Referenced by filename(), main(), and opt().
clist
List clist static
Definition at line 65 of file lcc.c.
Referenced by compile(), and opt().
com
char * com[]
Definition at line 55 of file lcc.c.
Referenced by compile(), initinputs(), opt(), and tempname().
cpp
char* cpp[]
Definition at line 15 of file bytecode.c.
Referenced by filename(), opt(), option(), stabend(), and UpdatePaths().
Eflag
int Eflag static
Definition at line 59 of file lcc.c.
Referenced by filename(), main(), and opt().
errcnt
int errcnt static
Definition at line 58 of file lcc.c.
Referenced by emitcode(), error(), filename(), gencode(), listnodes(), and main().
ilist
List ilist static
Definition at line 67 of file lcc.c.
Referenced by initinputs(), main(), and opt().
include
char * include[]
Definition at line 55 of file lcc.c.
Referenced by main(), and opt().
inputs
char inputs[]
Definition at line 55 of file lcc.c.
Referenced by initinputs().
lccinputs
List lccinputs static
Definition at line 74 of file lcc.c.
Referenced by exists(), and initinputs().
ld
char * ld[]
Definition at line 55 of file lcc.c.
Referenced by main().
llist
List llist[2] static
Definition at line 63 of file lcc.c.
Referenced by filename(), initinputs(), main(), and opt().
outfile
char* outfile static
Definition at line 69 of file lcc.c.
Referenced by filename(), and main().
plist
List plist static
Definition at line 66 of file lcc.c.
Referenced by filename(), main(), and opt().
progname
char* progname static
Definition at line 73 of file lcc.c.
Referenced by callsys(), error(), help(), main(), opt(), and spawn().
rcsid
char rcsid[] = "Id: dummy rcsid" static
Definition at line 5 of file lcc.c.
Referenced by opt().
rmlist
List rmlist static
Definition at line 68 of file lcc.c.
Referenced by interrupt(), main(), and tempname().
Sflag
int Sflag = 1 static
Definition at line 60 of file lcc.c.
Referenced by filename(), main(), and opt().
suffixes
char * suffixes[]
Definition at line 55 of file lcc.c.
Referenced by filename(), main(), and opt().
tempdir
char* tempdir = TEMPDIR
Definition at line 72 of file lcc.c.
Referenced by help(), main(), opt(), and tempname().
verbose
int verbose static
Definition at line 62 of file lcc.c.
Referenced by callsys(), exists(), opt(), and rm().