ZEQ2-Lite: Exceptions
Exceptions
Namespaces
std::__exception_ptr
Data Structures
class std::__exception_ptr::exception_ptr
An opaque pointer to an arbitrary exception.
Typedefs
typedef void(exception_ptr::* std::__exception_ptr::exception_ptr::__safe_bool) ()
Functions
std::__exception_ptr::exception_ptr::exception_ptr () throw ()
std::__exception_ptr::exception_ptr::exception_ptr (__safe_bool) throw ()
std::__exception_ptr::exception_ptr::exception_ptr (const exception_ptr &) throw ()
std::__exception_ptr::exception_ptr::exception_ptr (void *__e) throw ()
std::__exception_ptr::exception_ptr::~exception_ptr () throw ()
const class type_info * std::__exception_ptr::exception_ptr::__cxa_exception_type () const __attribute__((__pure__)) throw ()
namespace std _GLIBCXX_VISIBILITY (default)
void std::__exception_ptr::exception_ptr::_M_addref () throw ()
void * std::__exception_ptr::exception_ptr::_M_get () const __attribute__((__pure__)) throw ()
void std::__exception_ptr::exception_ptr::_M_release () throw ()
template<typename _Ex >
exception_ptr std::copy_exception (_Ex __ex) throw ()
Obtain an exception_ptr pointing to a copy of the supplied object.
exception_ptr std::current_exception () throw ()
Obtain an exception_ptr to the currently handled exception.
template<typename _Ex >
exception_ptr std::make_exception_ptr (_Ex __ex) throw ()
Obtain an exception_ptr pointing to a copy of the supplied object.
bool std::__exception_ptr::operator!= (const exception_ptr &, const exception_ptr &) __attribute__((__pure__)) throw ()
exception_ptr & std::__exception_ptr::exception_ptr::operator= (const exception_ptr &) throw ()
bool std::__exception_ptr::operator== (const exception_ptr &, const exception_ptr &) __attribute__((__pure__)) throw ()
void std::rethrow_exception (exception_ptr) __attribute__((__noreturn__))
Throw the object pointed to by the exception_ptr.
void std::__exception_ptr::exception_ptr::swap (exception_ptr &) throw ()
void std::__exception_ptr::swap (exception_ptr &__lhs, exception_ptr &__rhs)
Variables
void * std::__exception_ptr::exception_ptr::_M_exception_object
Friends
bool std::__exception_ptr::exception_ptr::operator== (const exception_ptr &, const exception_ptr &) __attribute__((__pure__)) throw ()
exception_ptr std::__exception_ptr::exception_ptr::std::current_exception () throw ()
void std::__exception_ptr::exception_ptr::std::rethrow_exception (exception_ptr)
Detailed Description
Typedef Documentation
__safe_bool
typedef void(exception_ptr::* std::__exception_ptr::exception_ptr::__safe_bool) ()
Definition at line 101 of file exception_ptr.h.
Function Documentation
exception_ptr() [1/4]
std::__exception_ptr::exception_ptr::exception_ptr () throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
exception_ptr() [2/4]
std::__exception_ptr::exception_ptr::exception_ptr (__safe_bool) throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
exception_ptr() [3/4]
std::__exception_ptr::exception_ptr::exception_ptr (const exception_ptr &) throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
exception_ptr() [4/4]
std::__exception_ptr::exception_ptr::exception_ptr (void * __e) throw () explicit private
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
~exception_ptr()
std::__exception_ptr::exception_ptr::~exception_ptr () throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
__cxa_exception_type()
const class type_info* std::__exception_ptr::exception_ptr::__cxa_exception_type () const throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
_GLIBCXX_VISIBILITY()
namespace std _GLIBCXX_VISIBILITY (default)
#include <Tools/MinGW/include/c++/4.6.1/bits/ios_base.h>
The base of the I/O class hierarchy.
This class defines everything that can be defined about I/O that does not depend on the type of characters being input or output. Most people will only see ios_base when they need to specify the full name of the various I/O flags (e.g., the openmodes).
These are thrown to indicate problems with io.
27.4.2.1.1 Class ios_base::failure
This is a bitmask type.
_Ios_Fmtflags is implementation-defined, but it is valid to perform bitwise operations on these values and expect the Right Thing to happen. Defined objects of type fmtflags are:
boolalpha
dec
fixed
hex
internal
left
oct
right
scientific
showbase
showpoint
showpos
skipws
unitbuf
uppercase
adjustfield
basefield
floatfield
Insert/extract bool in alphabetic rather than numeric format.
Converts integer input or generates integer output in decimal base.
Generate floating-point output in fixed-point notation.
Converts integer input or generates integer output in hexadecimal base.
Adds fill characters at a designated internal point in certain generated output, or identical to right if no such point is designated.
Adds fill characters on the right (final positions) of certain generated output. (I.e., the thing you print is flush left.)
Converts integer input or generates integer output in octal base.
Adds fill characters on the left (initial positions) of certain generated output. (I.e., the thing you print is flush right.)
Generates floating-point output in scientific notation.
Generates a prefix indicating the numeric base of generated integer output.
Generates a decimal-point character unconditionally in generated floating-point output.
Generates a + sign in non-negative generated numeric output.
Skips leading white space before certain input operations.
Flushes output after each output operation.
Replaces certain lowercase letters with their uppercase equivalents in generated output.
A mask of left|right|internal. Useful for the 2-arg form of setf.
A mask of dec|oct|hex. Useful for the 2-arg form of setf.
A mask of scientific|fixed. Useful for the 2-arg form of setf.
This is a bitmask type.
_Ios_Iostate is implementation-defined, but it is valid to perform bitwise operations on these values and expect the Right Thing to happen. Defined objects of type iostate are:
badbit
eofbit
failbit
goodbit
Indicates a loss of integrity in an input or output sequence (such as an irrecoverable read error from a file).
Indicates that an input operation reached the end of an input sequence.
Indicates that an input operation failed to read the expected characters, or that an output operation failed to generate the desired characters.
Indicates all is well.
This is a bitmask type.
_Ios_Openmode is implementation-defined, but it is valid to perform bitwise operations on these values and expect the Right Thing to happen. Defined objects of type openmode are:
app
ate
binary
in
out
trunc
Seek to end before each write.
Open and seek to end immediately after opening.
Perform input and output in binary mode (as opposed to text mode). This is probably not what you think it is; see http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch27s02.html
Open for input. Default for ifstream and fstream.
Open for output. Default for ofstream and fstream.
Open for input. Default for ofstream.
This is an enumerated type.
_Ios_Seekdir is implementation-defined. Defined values of type seekdir are:
beg
cur, equivalent to SEEK_CUR in the C standard library.
end, equivalent to SEEK_END in the C standard library.
Request a seek relative to the beginning of the stream.
Request a seek relative to the current position within the sequence.
Request a seek relative to the current end of the sequence.
The set of events that may be passed to an event callback.
erase_event is used during ~ios() and copyfmt(). imbue_event is used during imbue(). copyfmt_event is used during copyfmt().
The type of an event callback function.
Parameters
event One of the members of the event enum.
ios_base Reference to the ios_base object.
int The integer provided when the callback was registered.
Event callbacks are user defined functions that get called during several ios_base and basic_ios functions, specifically imbue(), copyfmt(), and ~ios().
Add the callback __fn with parameter __index.
Parameters
__fn The function to add.
__index The integer to pass to the function when invoked.
Registers a function as an event callback with an integer parameter to be passed to the function when invoked. Multiple copies of the function are allowed. If there are multiple callbacks, they are invoked in the order they were registered.
Access to format flags.
Returns
The format control flags for both input and output.
Setting new format flags all at once.
Parameters
fmtfl The new flags to set.
Returns
The previous format control flags.
This function overwrites all the format flags with fmtfl.
Setting new format flags.
Parameters
fmtfl Additional flags to set.
Returns
The previous format control flags.
This function sets additional flags in format control. Flags that were previously set remain set.
Setting new format flags.
Parameters
fmtfl Additional flags to set.
mask The flags mask for fmtfl.
Returns
The previous format control flags.
This function clears mask in the format flags, then sets fmtfl & mask. An example mask is ios_base::adjustfield.
Clearing format flags.
Parameters
mask The flags to unset.
This function clears mask in the format flags.
Flags access.
Returns
The precision to generate on certain output operations.
Be careful if you try to give a definition of precision here; see DR 189.
Changing flags.
Parameters
prec The new precision value.
Returns
The previous value of precision().
Flags access.
Returns
The minimum field width to generate on output operations.
Minimum field width refers to the number of characters.
Changing flags.
Parameters
wide The new width value.
Returns
The previous value of width().
Interaction with the standard C I/O objects.
Parameters
sync Whether to synchronize or not.
Returns
True if the standard streams were previously synchronized.
The synchronization referred to is only that between the standard C facilities (e.g., stdout) and the standard C++ objects (e.g., cout). User-declared streams are unaffected. See http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt11ch28s02.html
Setting a new locale.
Parameters
loc The new locale.
Returns
The previous locale.
Sets the new locale for this stream, and then invokes each callback with imbue_event.
Locale access
Returns
A copy of the current locale.
If imbue(loc) has previously been called, then this function returns loc. Otherwise, it returns a copy of std::locale(), the global C++ locale.
Locale access
Returns
A reference to the current locale.
Like getloc above, but returns a reference instead of generating a copy.
Access to unique indices.
Returns
An integer different from all previous calls.
This function returns a unique integer every time it is called. It can be used for any purpose, but is primarily intended to be a unique index for the iword and pword functions. The expectation is that an application calls xalloc in order to obtain an index in the iword and pword arrays that can be used without fear of conflict.
The implementation maintains a static variable that is incremented and returned on each invocation. xalloc is guaranteed to return an index that is safe to use in the iword and pword arrays.
Access to integer array.
Parameters
__ix Index into the array.
Returns
A reference to an integer associated with the index.
The iword function provides access to an array of integers that can be used for any purpose. The array grows as required to hold the supplied index. All integers in the array are initialized to 0.
The implementation reserves several indices. You should use xalloc to obtain an index that is safe to use. Also note that since the array can grow dynamically, it is not safe to hold onto the reference.
Access to void pointer array.
Parameters
__ix Index into the array.
Returns
A reference to a void* associated with the index.
The pword function provides access to an array of pointers that can be used for any purpose. The array grows as required to hold the supplied index. All pointers in the array are initialized to 0.
The implementation reserves several indices. You should use xalloc to obtain an index that is safe to use. Also note that since the array can grow dynamically, it is not safe to hold onto the reference.
Invokes each callback with erase_event. Destroys local storage.
Note that the ios_base object for the standard streams never gets destroyed. As a result, any callbacks registered with the standard streams will not get invoked with erase_event (unless copyfmt is used).
Calls base.setf(ios_base::boolalpha).
Calls base.unsetf(ios_base::boolalpha).
Calls base.setf(ios_base::showbase).
Calls base.unsetf(ios_base::showbase).
Calls base.setf(ios_base::showpoint).
Calls base.unsetf(ios_base::showpoint).
Calls base.setf(ios_base::showpos).
Calls base.unsetf(ios_base::showpos).
Calls base.setf(ios_base::skipws).
Calls base.unsetf(ios_base::skipws).
Calls base.setf(ios_base::uppercase).
Calls base.unsetf(ios_base::uppercase).
Calls base.setf(ios_base::unitbuf).
Calls base.unsetf(ios_base::unitbuf).
Calls base.setf(ios_base::internal, ios_base::adjustfield).
Calls base.setf(ios_base::left, ios_base::adjustfield).
Calls base.setf(ios_base::right, ios_base::adjustfield).
Calls base.setf(ios_base::dec, ios_base::basefield).
Calls base.setf(ios_base::hex, ios_base::basefield).
Calls base.setf(ios_base::oct, ios_base::basefield).
Calls base.setf(ios_base::fixed, ios_base::floatfield).
Calls base.setf(ios_base::scientific, ios_base::floatfield).
Exception possibly thrown by shared_ptr.
static_pointer_cast
const_pointer_cast
dynamic_pointer_cast
std::hash specialization for __shared_ptr.
Thown by exception safety machinery.
Base class for checking address and label information about allocations. Create a std::map between the allocated address (void*) and a datum for annotations, which are a pair of numbers corresponding to label and allocated size.
Base struct for condition policy.
Requires a public member function with the signature void throw_conditionally()
Base class for incremental control and throw.
Never enter the condition.
Always enter the condition.
Enter the nth condition.
Base class for random probability control and throw.
Group condition.
Never enter the condition.
Always enter the condition.
Class with exception generation control. Intended to be used as a value_type in templatized code.
Note: Destructor not allowed to throw.
Type throwing via limit condition.
Type throwing via random condition.
Allocator class with logging and exception generation control. Intended to be used as an allocator_type in templatized code.
Note: Deallocate not allowed to throw.
Allocator throwing via limit condition.
Allocator throwing via random condition.
Exception possibly thrown by shared_ptr.
Definition at line 45 of file ios_base.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
   // The following definitions of bitmask types are enums, not ints,
   // as permitted (but not required) in the standard, in order to provide
   // better type safety in iostream calls.  A side effect is that
   // expressions involving them are no longer compile-time constants.
   enum _Ios_Fmtflags
     {
       _S_boolalpha  = 1L << 0,
       _S_dec        = 1L << 1,
       _S_fixed      = 1L << 2,
       _S_hex        = 1L << 3,
       _S_internal   = 1L << 4,
       _S_left       = 1L << 5,
       _S_oct        = 1L << 6,
       _S_right      = 1L << 7,
       _S_scientific     = 1L << 8,
       _S_showbase   = 1L << 9,
       _S_showpoint  = 1L << 10,
       _S_showpos    = 1L << 11,
       _S_skipws     = 1L << 12,
       _S_unitbuf    = 1L << 13,
       _S_uppercase  = 1L << 14,
       _S_adjustfield    = _S_left | _S_right | _S_internal,
       _S_basefield  = _S_dec | _S_oct | _S_hex,
       _S_floatfield     = _S_scientific | _S_fixed,
       _S_ios_fmtflags_end = 1L << 16
     };
   inline _GLIBCXX_CONSTEXPR _Ios_Fmtflags
   operator&(_Ios_Fmtflags __a, _Ios_Fmtflags __b)
   { return _Ios_Fmtflags(static_cast<int>(__a) & static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Fmtflags
   operator|(_Ios_Fmtflags __a, _Ios_Fmtflags __b)
   { return _Ios_Fmtflags(static_cast<int>(__a) | static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Fmtflags
   operator^(_Ios_Fmtflags __a, _Ios_Fmtflags __b)
   { return _Ios_Fmtflags(static_cast<int>(__a) ^ static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Fmtflags
   operator~(_Ios_Fmtflags __a)
   { return _Ios_Fmtflags(~static_cast<int>(__a)); }
   inline const _Ios_Fmtflags&
   operator|=(_Ios_Fmtflags& __a, _Ios_Fmtflags __b)
   { return __a = __a | __b; }
   inline const _Ios_Fmtflags&
   operator&=(_Ios_Fmtflags& __a, _Ios_Fmtflags __b)
   { return __a = __a & __b; }
   inline const _Ios_Fmtflags&
   operator^=(_Ios_Fmtflags& __a, _Ios_Fmtflags __b)
   { return __a = __a ^ __b; }
   enum _Ios_Openmode
     {
       _S_app        = 1L << 0,
       _S_ate        = 1L << 1,
       _S_bin        = 1L << 2,
       _S_in         = 1L << 3,
       _S_out        = 1L << 4,
       _S_trunc      = 1L << 5,
       _S_ios_openmode_end = 1L << 16
     };
   inline _GLIBCXX_CONSTEXPR _Ios_Openmode
   operator&(_Ios_Openmode __a, _Ios_Openmode __b)
   { return _Ios_Openmode(static_cast<int>(__a) & static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Openmode
   operator|(_Ios_Openmode __a, _Ios_Openmode __b)
   { return _Ios_Openmode(static_cast<int>(__a) | static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Openmode
   operator^(_Ios_Openmode __a, _Ios_Openmode __b)
   { return _Ios_Openmode(static_cast<int>(__a) ^ static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Openmode
   operator~(_Ios_Openmode __a)
   { return _Ios_Openmode(~static_cast<int>(__a)); }
   inline const _Ios_Openmode&
   operator|=(_Ios_Openmode& __a, _Ios_Openmode __b)
   { return __a = __a | __b; }
   inline const _Ios_Openmode&
   operator&=(_Ios_Openmode& __a, _Ios_Openmode __b)
   { return __a = __a & __b; }
   inline const _Ios_Openmode&
   operator^=(_Ios_Openmode& __a, _Ios_Openmode __b)
   { return __a = __a ^ __b; }
   enum _Ios_Iostate
     {
       _S_goodbit        = 0,
       _S_badbit         = 1L << 0,
       _S_eofbit         = 1L << 1,
       _S_failbit        = 1L << 2,
       _S_ios_iostate_end = 1L << 16
     };
   inline _GLIBCXX_CONSTEXPR _Ios_Iostate
   operator&(_Ios_Iostate __a, _Ios_Iostate __b)
   { return _Ios_Iostate(static_cast<int>(__a) & static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Iostate
   operator|(_Ios_Iostate __a, _Ios_Iostate __b)
   { return _Ios_Iostate(static_cast<int>(__a) | static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Iostate
   operator^(_Ios_Iostate __a, _Ios_Iostate __b)
   { return _Ios_Iostate(static_cast<int>(__a) ^ static_cast<int>(__b)); }
   inline _GLIBCXX_CONSTEXPR _Ios_Iostate
   operator~(_Ios_Iostate __a)
   { return _Ios_Iostate(~static_cast<int>(__a)); }
   inline const _Ios_Iostate&
   operator|=(_Ios_Iostate& __a, _Ios_Iostate __b)
   { return __a = __a | __b; }
   inline const _Ios_Iostate&
   operator&=(_Ios_Iostate& __a, _Ios_Iostate __b)
   { return __a = __a & __b; }
   inline const  _Ios_Iostate&
   operator^=(_Ios_Iostate& __a, _Ios_Iostate __b)
   { return __a = __a ^ __b; }
   enum _Ios_Seekdir
     {
       _S_beg = 0,
       _S_cur = _GLIBCXX_STDIO_SEEK_CUR,
       _S_end = _GLIBCXX_STDIO_SEEK_END,
       _S_ios_seekdir_end = 1L << 16
     };
   // 27.4.2  Class ios_base
   class ios_base
   {
   public:
     class failure : public exception
     {
     public:
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // 48.  Use of non-existent exception constructor
       explicit
       failure(const string& __str) throw();
       // This declaration is not useless:
       // http://gcc.gnu.org/onlinedocs/gcc-4.3.2/gcc/Vague-Linkage.html
       virtual
       ~failure() throw();
       virtual const char*
       what() const throw();
     private:
       string _M_msg;
     };
     // 27.4.2.1.2  Type ios_base::fmtflags
     typedef _Ios_Fmtflags fmtflags;
     static const fmtflags boolalpha =   _S_boolalpha;
     static const fmtflags dec =         _S_dec;
     static const fmtflags fixed =       _S_fixed;
     static const fmtflags hex =         _S_hex;
     static const fmtflags internal =    _S_internal;
     static const fmtflags left =        _S_left;
     static const fmtflags oct =         _S_oct;
     static const fmtflags right =       _S_right;
     static const fmtflags scientific =  _S_scientific;
     static const fmtflags showbase =    _S_showbase;
     static const fmtflags showpoint =   _S_showpoint;
     static const fmtflags showpos =     _S_showpos;
     static const fmtflags skipws =      _S_skipws;
     static const fmtflags unitbuf =     _S_unitbuf;
     static const fmtflags uppercase =   _S_uppercase;
     static const fmtflags adjustfield = _S_adjustfield;
     static const fmtflags basefield =   _S_basefield;
     static const fmtflags floatfield =  _S_floatfield;
     // 27.4.2.1.3  Type ios_base::iostate
     typedef _Ios_Iostate iostate;
     static const iostate badbit =   _S_badbit;
     static const iostate eofbit =   _S_eofbit;
     static const iostate failbit =  _S_failbit;
     static const iostate goodbit =  _S_goodbit;
     // 27.4.2.1.4  Type ios_base::openmode
     typedef _Ios_Openmode openmode;
     static const openmode app =     _S_app;
     static const openmode ate =     _S_ate;
     static const openmode binary =  _S_bin;
     static const openmode in =      _S_in;
     static const openmode out =     _S_out;
     static const openmode trunc =   _S_trunc;
     // 27.4.2.1.5  Type ios_base::seekdir
     typedef _Ios_Seekdir seekdir;
     static const seekdir beg =      _S_beg;
     static const seekdir cur =      _S_cur;
     static const seekdir end =      _S_end;
     // Annex D.6
     typedef int io_state;
     typedef int open_mode;
     typedef int seek_dir;
     typedef std::streampos streampos;
     typedef std::streamoff streamoff;
     // Callbacks;
     enum event
     {
       erase_event,
       imbue_event,
       copyfmt_event
     };
     typedef void (*event_callback) (event, ios_base&, int);
     void
     register_callback(event_callback __fn, int __index);
   protected:
     streamsize      _M_precision;
     streamsize      _M_width;
     fmtflags        _M_flags;
     iostate     _M_exception;
     iostate     _M_streambuf_state;
     // 27.4.2.6  Members for callbacks
     // 27.4.2.6  ios_base callbacks
     struct _Callback_list
     {
       // Data Members
       _Callback_list*       _M_next;
       ios_base::event_callback  _M_fn;
       int           _M_index;
       _Atomic_word      _M_refcount;  // 0 means one reference.
       _Callback_list(ios_base::event_callback __fn, int __index,
              _Callback_list* __cb)
       : _M_next(__cb), _M_fn(__fn), _M_index(__index), _M_refcount(0) { }
       void
       _M_add_reference() { __gnu_cxx::__atomic_add_dispatch(&_M_refcount, 1); }
       // 0 => OK to delete.
       int
       _M_remove_reference()
       {
         // Be race-detector-friendly.  For more info see bits/c++config.
         _GLIBCXX_SYNCHRONIZATION_HAPPENS_BEFORE(&_M_refcount);
         int __res = __gnu_cxx::__exchange_and_add_dispatch(&_M_refcount, -1);
         if (__res == 0)
           {
             _GLIBCXX_SYNCHRONIZATION_HAPPENS_AFTER(&_M_refcount);
           }
         return __res;
       }
     };
      _Callback_list*    _M_callbacks;
     void
     _M_call_callbacks(event __ev) throw();
     void
     _M_dispose_callbacks(void) throw();
     // 27.4.2.5  Members for iword/pword storage
     struct _Words
     {
       void* _M_pword;
       long  _M_iword;
       _Words() : _M_pword(0), _M_iword(0) { }
     };
     // Only for failed iword/pword calls.
     _Words      _M_word_zero;
     // Guaranteed storage.
     // The first 5 iword and pword slots are reserved for internal use.
     enum { _S_local_word_size = 8 };
     _Words      _M_local_word[_S_local_word_size];
     // Allocated storage.
     int         _M_word_size;
     _Words*     _M_word;
     _Words&
     _M_grow_words(int __index, bool __iword);
     // Members for locale and locale caching.
     locale      _M_ios_locale;
     void
     _M_init() throw();
   public:
     // 27.4.2.1.6  Class ios_base::Init
     // Used to initialize standard streams. In theory, g++ could use
     // -finit-priority to order this stuff correctly without going
     // through these machinations.
     class Init
     {
       friend class ios_base;
     public:
       Init();
       ~Init();
     private:
       static _Atomic_word   _S_refcount;
       static bool       _S_synced_with_stdio;
     };
     // [27.4.2.2] fmtflags state functions
     fmtflags
     flags() const
     { return _M_flags; }
     fmtflags
     flags(fmtflags __fmtfl)
     {
       fmtflags __old = _M_flags;
       _M_flags = __fmtfl;
       return __old;
     }
     fmtflags
     setf(fmtflags __fmtfl)
     {
       fmtflags __old = _M_flags;
       _M_flags |= __fmtfl;
       return __old;
     }
     fmtflags
     setf(fmtflags __fmtfl, fmtflags __mask)
     {
       fmtflags __old = _M_flags;
       _M_flags &= ~__mask;
       _M_flags |= (__fmtfl & __mask);
       return __old;
     }
     void
     unsetf(fmtflags __mask)
     { _M_flags &= ~__mask; }
     streamsize
     precision() const
     { return _M_precision; }
     streamsize
     precision(streamsize __prec)
     {
       streamsize __old = _M_precision;
       _M_precision = __prec;
       return __old;
     }
     streamsize
     width() const
     { return _M_width; }
     streamsize
     width(streamsize __wide)
     {
       streamsize __old = _M_width;
       _M_width = __wide;
       return __old;
     }
     // [27.4.2.4] ios_base static members
     static bool
     sync_with_stdio(bool __sync = true);
     // [27.4.2.3] ios_base locale functions
     locale
     imbue(const locale& __loc) throw();
     locale
     getloc() const
     { return _M_ios_locale; }
     const locale&
     _M_getloc() const
     { return _M_ios_locale; }
     // [27.4.2.5] ios_base storage functions
     static int
     xalloc() throw();
     long&
     iword(int __ix)
     {
       _Words& __word = (__ix < _M_word_size)
             ? _M_word[__ix] : _M_grow_words(__ix, true);
       return __word._M_iword;
     }
     void*&
     pword(int __ix)
     {
       _Words& __word = (__ix < _M_word_size)
             ? _M_word[__ix] : _M_grow_words(__ix, false);
       return __word._M_pword;
     }
     // Destructor
     virtual ~ios_base();
   protected:
     ios_base() throw ();
   // _GLIBCXX_RESOLVE_LIB_DEFECTS
   // 50.  Copy constructor and assignment operator of ios_base
   private:
     ios_base(const ios_base&);
     ios_base&
     operator=(const ios_base&);
   };
   // [27.4.5.1] fmtflags manipulators
   inline ios_base&
   boolalpha(ios_base& __base)
   {
     __base.setf(ios_base::boolalpha);
     return __base;
   }
   inline ios_base&
   noboolalpha(ios_base& __base)
   {
     __base.unsetf(ios_base::boolalpha);
     return __base;
   }
   inline ios_base&
   showbase(ios_base& __base)
   {
     __base.setf(ios_base::showbase);
     return __base;
   }
   inline ios_base&
   noshowbase(ios_base& __base)
   {
     __base.unsetf(ios_base::showbase);
     return __base;
   }
   inline ios_base&
   showpoint(ios_base& __base)
   {
     __base.setf(ios_base::showpoint);
     return __base;
   }
   inline ios_base&
   noshowpoint(ios_base& __base)
   {
     __base.unsetf(ios_base::showpoint);
     return __base;
   }
   inline ios_base&
   showpos(ios_base& __base)
   {
     __base.setf(ios_base::showpos);
     return __base;
   }
   inline ios_base&
   noshowpos(ios_base& __base)
   {
     __base.unsetf(ios_base::showpos);
     return __base;
   }
   inline ios_base&
   skipws(ios_base& __base)
   {
     __base.setf(ios_base::skipws);
     return __base;
   }
   inline ios_base&
   noskipws(ios_base& __base)
   {
     __base.unsetf(ios_base::skipws);
     return __base;
   }
   inline ios_base&
   uppercase(ios_base& __base)
   {
     __base.setf(ios_base::uppercase);
     return __base;
   }
   inline ios_base&
   nouppercase(ios_base& __base)
   {
     __base.unsetf(ios_base::uppercase);
     return __base;
   }
   inline ios_base&
   unitbuf(ios_base& __base)
   {
      __base.setf(ios_base::unitbuf);
      return __base;
   }
   inline ios_base&
   nounitbuf(ios_base& __base)
   {
      __base.unsetf(ios_base::unitbuf);
      return __base;
   }
   // [27.4.5.2] adjustfield manipulators
   inline ios_base&
   internal(ios_base& __base)
   {
      __base.setf(ios_base::internal, ios_base::adjustfield);
      return __base;
   }
   inline ios_base&
   left(ios_base& __base)
   {
     __base.setf(ios_base::left, ios_base::adjustfield);
     return __base;
   }
   inline ios_base&
   right(ios_base& __base)
   {
     __base.setf(ios_base::right, ios_base::adjustfield);
     return __base;
   }
   // [27.4.5.3] basefield manipulators
   inline ios_base&
   dec(ios_base& __base)
   {
     __base.setf(ios_base::dec, ios_base::basefield);
     return __base;
   }
   inline ios_base&
   hex(ios_base& __base)
   {
     __base.setf(ios_base::hex, ios_base::basefield);
     return __base;
   }
   inline ios_base&
   oct(ios_base& __base)
   {
     __base.setf(ios_base::oct, ios_base::basefield);
     return __base;
   }
   // [27.4.5.4] floatfield manipulators
   inline ios_base&
   fixed(ios_base& __base)
   {
     __base.setf(ios_base::fixed, ios_base::floatfield);
     return __base;
   }
   inline ios_base&
   scientific(ios_base& __base)
   {
     __base.setf(ios_base::scientific, ios_base::floatfield);
     return __base;
   }
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References __gnu_debug::__base(), _GLIBCXX_STDIO_SEEK_CUR, _GLIBCXX_STDIO_SEEK_END, binary(), fixed(), int, out, right, seekdir(), trunc(), and void().
_M_addref()
void std::__exception_ptr::exception_ptr::_M_addref () throw () private
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
_M_get()
void* std::__exception_ptr::exception_ptr::_M_get () const throw () private
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
_M_release()
void std::__exception_ptr::exception_ptr::_M_release () throw () private
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
copy_exception()
template<typename _Ex > exception_ptr std::copy_exception (_Ex __ex) throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
Obtain an exception_ptr pointing to a copy of the supplied object.
Definition at line 162 of file exception_ptr.h.
     {
       __try
     {
 #ifdef __EXCEPTIONS
       throw __ex;
 #endif
     }
       __catch(...)
     {
       return current_exception();
     }
     }
References __catch, __try, and std::current_exception().
current_exception()
exception_ptr std::current_exception () throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
Obtain an exception_ptr to the currently handled exception.
If there is none, or the currently handled exception is foreign, return the null value.
Referenced by std::copy_exception().
make_exception_ptr()
template<typename _Ex > exception_ptr std::make_exception_ptr (_Ex __ex) throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
Obtain an exception_ptr pointing to a copy of the supplied object.
Definition at line 181 of file exception_ptr.h.
     { return std::copy_exception<_Ex>(__ex); }
operator!=()
bool std::__exception_ptr::operator!= (const exception_ptr & , const exception_ptr &) throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
Referenced by _GLIBCXX_VISIBILITY().
operator=()
exception_ptr& std::__exception_ptr::exception_ptr::operator= (const exception_ptr &) throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
operator==()
bool std::__exception_ptr::operator== (const exception_ptr & , const exception_ptr &) throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
Referenced by _GLIBCXX_VISIBILITY().
rethrow_exception()
void std::rethrow_exception (exception_ptr)
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
Throw the object pointed to by the exception_ptr.
swap() [1/2]
void std::__exception_ptr::exception_ptr::swap (exception_ptr &) throw ()
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
swap() [2/2]
void std::__exception_ptr::swap (exception_ptr & __lhs, exception_ptr & __rhs) inline
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
Definition at line 153 of file exception_ptr.h.
     { __lhs.swap(__rhs); }
Variable Documentation
_M_exception_object
void* std::__exception_ptr::exception_ptr::_M_exception_object private
Definition at line 75 of file exception_ptr.h.
Friends
operator==
bool operator== (const exception_ptr & , const exception_ptr &) throw () friend
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
std::current_exception
exception_ptr std::current_exception () throw () friend
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>
std::rethrow_exception
void std::rethrow_exception (exception_ptr) friend
#include <Tools/MinGW/include/c++/4.6.1/bits/exception_ptr.h>