ZEQ2-Lite: LinearGradientBrush Class Reference
LinearGradientBrush Class Reference
#include <gdiplusbrush.h>
Public Member Functions
LinearGradientBrush (const Point &point1, const Point &point2, const Color &color1, const Color &color2)
LinearGradientBrush (const PointF &point1, const PointF &point2, const Color &color1, const Color &color2)
LinearGradientBrush (const Rect &rect, const Color &color1, const Color &color2, LinearGradientMode mode)
LinearGradientBrush (const Rect &rect, const Color &color1, const Color &color2, REAL angle, BOOL isAngleScalable=FALSE)
LinearGradientBrush (const RectF &rect, const Color &color1, const Color &color2, LinearGradientMode mode)
LinearGradientBrush (const RectF &rect, const Color &color1, const Color &color2, REAL angle, BOOL isAngleScalable=FALSE)
virtual LinearGradientBrush * Clone () const
Status GetBlend (REAL *blendFactors, REAL *blendPositions, INT count) const
INT GetBlendCount () const
BOOL GetGammaCorrection () const
INT GetInterpolationColorCount () const
Status GetInterpolationColors (Color *presetColors, REAL *blendPositions, INT count) const
Status GetLastStatus () const
Status GetLinearColors (Color *colors) const
Status GetRectangle (Rect *rect) const
Status GetRectangle (RectF *rect) const
Status GetTransform (Matrix *matrix) const
BrushType GetType () const
WrapMode GetWrapMode () const
Status MultiplyTransform (const Matrix *matrix, MatrixOrder order=MatrixOrderPrepend)
Status ResetTransform ()
Status RotateTranform (REAL angle, MatrixOrder order=MatrixOrderPrepend)
Status ScaleTransform (REAL sx, REAL sy, MatrixOrder order=MatrixOrderPrepend)
Status SetBlend (const REAL *blendFactors, const REAL *blendPositions, INT count)
Status SetBlendBellShape (REAL focus, REAL scale=1.0f)
Status SetBlendTriangularShape (REAL focus, REAL scale=1.0f)
Status SetGammaCorrection (BOOL useGammaCorrection)
Status SetInterpolationColors (const Color *presetColors, const REAL *blendPositions, INT count)
Status SetLinearColors (const Color &color1, const Color &color2)
Status SetTransform (const Matrix *matrix)
Status SetWrapMode (WrapMode wrapMode)
Status TranslateTransform (REAL dx, REAL dy, MatrixOrder order=MatrixOrderPrepend)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
LinearGradientBrush (const LinearGradientBrush &brush)
LinearGradientBrush (GpBrush *brush, Status status)
LinearGradientBrush & operator= (const LinearGradientBrush &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpBrush * nativeBrush
Detailed Description
Definition at line 141 of file gdiplusbrush.h.
Constructor & Destructor Documentation
LinearGradientBrush() [1/8]
LinearGradientBrush::LinearGradientBrush (const PointF & point1, const PointF & point2, const Color & color1, const Color & color2) inline
Definition at line 144 of file gdiplusbrush.h.
     {
         GpLineGradient *nativeLineGradient = NULL;
         lastStatus = DllExports::GdipCreateLineBrush(
                 &point1, &point2,
                 color1.GetValue(), color2.GetValue(),
                 WrapModeTile, &nativeLineGradient);
         nativeBrush = nativeLineGradient;
     }
References GdipCreateLineBrush(), Brush::lastStatus, Brush::nativeBrush, NULL, and WrapModeTile.
LinearGradientBrush() [2/8]
LinearGradientBrush::LinearGradientBrush (const Point & point1, const Point & point2, const Color & color1, const Color & color2) inline
Definition at line 154 of file gdiplusbrush.h.
     {
         GpLineGradient *nativeLineGradient = NULL;
         lastStatus = DllExports::GdipCreateLineBrushI(
                 &point1, &point2,
                 color1.GetValue(), color2.GetValue(),
                 WrapModeTile, &nativeLineGradient);
         nativeBrush = nativeLineGradient;
     }
References GdipCreateLineBrushI(), Brush::lastStatus, Brush::nativeBrush, NULL, and WrapModeTile.
LinearGradientBrush() [3/8]
LinearGradientBrush::LinearGradientBrush (const RectF & rect, const Color & color1, const Color & color2, LinearGradientMode mode) inline
Definition at line 164 of file gdiplusbrush.h.
     {
         GpLineGradient *nativeLineGradient = NULL;
         lastStatus = DllExports::GdipCreateLineBrushFromRect(
                 &rect, color1.GetValue(), color2.GetValue(),
                 mode, WrapModeTile, &nativeLineGradient);
         nativeBrush = nativeLineGradient;
     }
References GdipCreateLineBrushFromRect(), Brush::lastStatus, Brush::nativeBrush, NULL, and WrapModeTile.
LinearGradientBrush() [4/8]
LinearGradientBrush::LinearGradientBrush (const Rect & rect, const Color & color1, const Color & color2, LinearGradientMode mode) inline
Definition at line 173 of file gdiplusbrush.h.
     {
         GpLineGradient *nativeLineGradient = NULL;
         lastStatus = DllExports::GdipCreateLineBrushFromRectI(
                 &rect, color1.GetValue(), color2.GetValue(),
                 mode, WrapModeTile, &nativeLineGradient);
         nativeBrush = nativeLineGradient;
     }
References GdipCreateLineBrushFromRectI(), Brush::lastStatus, Brush::nativeBrush, NULL, and WrapModeTile.
LinearGradientBrush() [5/8]
LinearGradientBrush::LinearGradientBrush (const RectF & rect, const Color & color1, const Color & color2, REAL angle, BOOL isAngleScalable = FALSE) inline
Definition at line 182 of file gdiplusbrush.h.
     {
         GpLineGradient *nativeLineGradient = NULL;
         lastStatus = DllExports::GdipCreateLineBrushFromRectWithAngle(
                 &rect, color1.GetValue(), color2.GetValue(),
                 angle, isAngleScalable, WrapModeTile,
                 &nativeLineGradient);
         nativeBrush = nativeLineGradient;
     }
References GdipCreateLineBrushFromRectWithAngle(), Brush::lastStatus, Brush::nativeBrush, NULL, and WrapModeTile.
LinearGradientBrush() [6/8]
LinearGradientBrush::LinearGradientBrush (const Rect & rect, const Color & color1, const Color & color2, REAL angle, BOOL isAngleScalable = FALSE) inline
Definition at line 193 of file gdiplusbrush.h.
     {
         GpLineGradient *nativeLineGradient = NULL;
         lastStatus = DllExports::GdipCreateLineBrushFromRectWithAngleI(
                 &rect, color1.GetValue(), color2.GetValue(),
                 angle, isAngleScalable, WrapModeTile,
                 &nativeLineGradient);
         nativeBrush = nativeLineGradient;
     }
References GdipCreateLineBrushFromRectWithAngleI(), Brush::lastStatus, Brush::nativeBrush, NULL, and WrapModeTile.
LinearGradientBrush() [7/8]
LinearGradientBrush::LinearGradientBrush (GpBrush * brush, Status status) inline private
Definition at line 397 of file gdiplusbrush.h.
 : Brush(brush, status) {}
LinearGradientBrush() [8/8]
LinearGradientBrush::LinearGradientBrush (const LinearGradientBrush & brush) private
Member Function Documentation
Clone()
virtual LinearGradientBrush* LinearGradientBrush::Clone () const inline virtual
Reimplemented from Brush.
Definition at line 204 of file gdiplusbrush.h.
     {
         GpBrush *cloneBrush = NULL;
         Status status = updateStatus(DllExports::GdipCloneBrush(
                 nativeBrush, &cloneBrush));
         if (status == Ok) {
             LinearGradientBrush *result =
                 new LinearGradientBrush(cloneBrush, lastStatus);
             if (!result) {
                 DllExports::GdipDeleteBrush(cloneBrush);
                 updateStatus(OutOfMemory);
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneBrush(), GdipDeleteBrush(), Brush::lastStatus, Brush::LinearGradientBrush, Brush::nativeBrush, NULL, Ok, OutOfMemory, and Brush::updateStatus().
GetBlend()
Status LinearGradientBrush::GetBlend (REAL * blendFactors, REAL * blendPositions, INT count) const inline
Definition at line 222 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipGetLineBlend(
                 (GpLineGradient*) nativeBrush,
                 blendFactors, blendPositions, count));
     }
References GdipGetLineBlend(), Brush::nativeBrush, and Brush::updateStatus().
GetBlendCount()
INT LinearGradientBrush::GetBlendCount () const inline
Definition at line 229 of file gdiplusbrush.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetLineBlendCount(
                 (GpLineGradient*) nativeBrush, &result));
         return result;
     }
References GdipGetLineBlendCount(), Brush::nativeBrush, and Brush::updateStatus().
GetGammaCorrection()
BOOL LinearGradientBrush::GetGammaCorrection () const inline
Definition at line 236 of file gdiplusbrush.h.
     {
         BOOL result = FALSE;
         updateStatus(DllExports::GdipGetLineGammaCorrection(
                 (GpLineGradient*) nativeBrush, &result));
         return result;
     }
References FALSE, GdipGetLineGammaCorrection(), Brush::nativeBrush, and Brush::updateStatus().
GetInterpolationColorCount()
INT LinearGradientBrush::GetInterpolationColorCount () const inline
Definition at line 243 of file gdiplusbrush.h.
     {
         INT result = 0;
         updateStatus(DllExports::GdipGetLinePresetBlendCount(
                 (GpLineGradient*) nativeBrush, &result));
         return result;
     }
References GdipGetLinePresetBlendCount(), Brush::nativeBrush, and Brush::updateStatus().
GetInterpolationColors()
Status LinearGradientBrush::GetInterpolationColors (Color * presetColors, REAL * blendPositions, INT count) const inline
Definition at line 250 of file gdiplusbrush.h.
     {
         if (!presetColors || count <= 0)
             return lastStatus = InvalidParameter;
         ARGB *presetArgb =
             (ARGB*) DllExports::GdipAlloc(count * sizeof(ARGB));
         if (!presetArgb)
             return lastStatus = OutOfMemory;
         Status status = updateStatus(DllExports::GdipGetLinePresetBlend(
                 (GpLineGradient*) nativeBrush, presetArgb,
                 blendPositions, count));
         for (INT i = 0; i < count; ++i) {
             presetColors[i].SetValue(presetArgb[i]);
         }
         DllExports::GdipFree((void*) presetArgb);
         return status;
     }
References GdipAlloc(), GdipFree(), GdipGetLinePresetBlend(), InvalidParameter, Brush::lastStatus, Brush::nativeBrush, OutOfMemory, and Brush::updateStatus().
GetLastStatus()
Status Brush::GetLastStatus () const inline inherited
Definition at line 54 of file gdiplusbrush.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References Brush::lastStatus, and Ok.
GetLinearColors()
Status LinearGradientBrush::GetLinearColors (Color * colors) const inline
Definition at line 270 of file gdiplusbrush.h.
     {
         if (!colors) return lastStatus = InvalidParameter;
         ARGB colorsArgb[2];
         Status status = updateStatus(DllExports::GdipGetLineColors(
                 (GpLineGradient*) nativeBrush, colorsArgb));
         colors[0].SetValue(colorsArgb[0]);
         colors[1].SetValue(colorsArgb[1]);
         return status;
     }
References GdipGetLineColors(), InvalidParameter, Brush::lastStatus, Brush::nativeBrush, and Brush::updateStatus().
GetRectangle() [1/2]
Status LinearGradientBrush::GetRectangle (Rect * rect) const inline
Definition at line 286 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipGetLineRectI(
                 (GpLineGradient*) nativeBrush, rect));
     }
References GdipGetLineRectI(), Brush::nativeBrush, and Brush::updateStatus().
GetRectangle() [2/2]
Status LinearGradientBrush::GetRectangle (RectF * rect) const inline
Definition at line 281 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipGetLineRect(
                 (GpLineGradient*) nativeBrush, rect));
     }
References GdipGetLineRect(), Brush::nativeBrush, and Brush::updateStatus().
GetTransform()
Status LinearGradientBrush::GetTransform (Matrix * matrix) const inline
Definition at line 291 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipGetLineTransform(
                 (GpLineGradient*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipGetLineTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
GetType()
BrushType Brush::GetType () const inline inherited
Definition at line 60 of file gdiplusbrush.h.
     {
         BrushType result = BrushTypeSolidColor;
         updateStatus(DllExports::GdipGetBrushType(nativeBrush, &result));
         return result;
     }
References BrushTypeSolidColor, GdipGetBrushType(), Brush::nativeBrush, and Brush::updateStatus().
GetWrapMode()
WrapMode LinearGradientBrush::GetWrapMode () const inline
Definition at line 297 of file gdiplusbrush.h.
     {
         WrapMode wrapMode = WrapModeTile;
         updateStatus(DllExports::GdipGetLineWrapMode(
                 (GpLineGradient*) nativeBrush, &wrapMode));
         return wrapMode;
     }
References GdipGetLineWrapMode(), Brush::nativeBrush, Brush::updateStatus(), and WrapModeTile.
MultiplyTransform()
Status LinearGradientBrush::MultiplyTransform (const Matrix * matrix, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 304 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipMultiplyLineTransform(
                 (GpLineGradient*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL, order));
     }
References GdipMultiplyLineTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
LinearGradientBrush& LinearGradientBrush::operator= (const LinearGradientBrush &) private
ResetTransform()
Status LinearGradientBrush::ResetTransform () inline
Definition at line 311 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipResetLineTransform(
                 (GpLineGradient*) nativeBrush));
     }
References GdipResetLineTransform(), Brush::nativeBrush, and Brush::updateStatus().
RotateTranform()
Status LinearGradientBrush::RotateTranform (REAL angle, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 316 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipRotateLineTransform(
                 (GpLineGradient*) nativeBrush, angle, order));
     }
References GdipRotateLineTransform(), Brush::nativeBrush, and Brush::updateStatus().
ScaleTransform()
Status LinearGradientBrush::ScaleTransform (REAL sx, REAL sy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 321 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipScaleLineTransform(
                 (GpLineGradient*) nativeBrush, sx, sy, order));
     }
References GdipScaleLineTransform(), Brush::nativeBrush, sy, and Brush::updateStatus().
SetBlend()
Status LinearGradientBrush::SetBlend (const REAL * blendFactors, const REAL * blendPositions, INT count) inline
Definition at line 327 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetLineBlend(
                 (GpLineGradient*) nativeBrush,
                 blendFactors, blendPositions, count));
     }
References GdipSetLineBlend(), Brush::nativeBrush, and Brush::updateStatus().
SetBlendBellShape()
Status LinearGradientBrush::SetBlendBellShape (REAL focus, REAL scale = 1.0f) inline
Definition at line 334 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetLineSigmaBlend(
                 (GpLineGradient*) nativeBrush,
                 focus, scale));
     }
References GdipSetLineSigmaBlend(), Brush::nativeBrush, and Brush::updateStatus().
SetBlendTriangularShape()
Status LinearGradientBrush::SetBlendTriangularShape (REAL focus, REAL scale = 1.0f) inline
Definition at line 340 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetLineLinearBlend(
                 (GpLineGradient*) nativeBrush,
                 focus, scale));
     }
References GdipSetLineLinearBlend(), Brush::nativeBrush, and Brush::updateStatus().
SetGammaCorrection()
Status LinearGradientBrush::SetGammaCorrection (BOOL useGammaCorrection) inline
Definition at line 346 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetLineGammaCorrection(
                 (GpLineGradient*) nativeBrush,
                 useGammaCorrection));
     }
References GdipSetLineGammaCorrection(), Brush::nativeBrush, and Brush::updateStatus().
SetInterpolationColors()
Status LinearGradientBrush::SetInterpolationColors (const Color * presetColors, const REAL * blendPositions, INT count) inline
Definition at line 352 of file gdiplusbrush.h.
     {
         if (!presetColors || count < 0)
             return lastStatus = InvalidParameter;
         ARGB *presetArgb =
             (ARGB*) DllExports::GdipAlloc(count * sizeof(ARGB));
         if (!presetArgb)
             return lastStatus = OutOfMemory;
         for (INT i = 0; i < count; ++i) {
             presetArgb[i] = presetColors[i].GetValue();
         }
         Status status = updateStatus(DllExports::GdipSetLinePresetBlend(
                 (GpLineGradient*) nativeBrush,
                 presetArgb, blendPositions, count));
         DllExports::GdipFree((void*) presetArgb);
         return status;
     }
References GdipAlloc(), GdipFree(), GdipSetLinePresetBlend(), InvalidParameter, Brush::lastStatus, Brush::nativeBrush, OutOfMemory, and Brush::updateStatus().
SetLinearColors()
Status LinearGradientBrush::SetLinearColors (const Color & color1, const Color & color2) inline
Definition at line 372 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetLineColors(
                 (GpLineGradient*) nativeBrush,
                 color1.GetValue(), color2.GetValue()));
     }
References GdipSetLineColors(), Brush::nativeBrush, and Brush::updateStatus().
SetTransform()
Status LinearGradientBrush::SetTransform (const Matrix * matrix) inline
Definition at line 378 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetLineTransform(
                 (GpLineGradient*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipSetLineTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
SetWrapMode()
Status LinearGradientBrush::SetWrapMode (WrapMode wrapMode) inline
Definition at line 384 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetLineWrapMode(
                 (GpLineGradient*) nativeBrush, wrapMode));
     }
References GdipSetLineWrapMode(), Brush::nativeBrush, and Brush::updateStatus().
TranslateTransform()
Status LinearGradientBrush::TranslateTransform (REAL dx, REAL dy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 389 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipTranslateLineTransform(
                 (GpLineGradient*) nativeBrush, dx, dy, order));
     }
References GdipTranslateLineTransform(), Brush::nativeBrush, and Brush::updateStatus().
updateStatus()
Status Brush::updateStatus (Status newStatus) const inline private inherited
Definition at line 74 of file gdiplusbrush.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References Brush::lastStatus, and Ok.
Referenced by HatchBrush::Clone(), Clone(), SolidBrush::Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), HatchBrush::GetBackgroundColor(), GetBlend(), PathGradientBrush::GetBlend(), GetBlendCount(), PathGradientBrush::GetBlendCount(), PathGradientBrush::GetCenterColor(), PathGradientBrush::GetCenterPoint(), SolidBrush::GetColor(), PathGradientBrush::GetFocusScales(), HatchBrush::GetForegroundColor(), GetGammaCorrection(), PathGradientBrush::GetGammaCorrection(), HatchBrush::GetHatchStyle(), GetInterpolationColorCount(), PathGradientBrush::GetInterpolationColorCount(), GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), GetLinearColors(), PathGradientBrush::GetPointCount(), GetRectangle(), PathGradientBrush::GetRectangle(), PathGradientBrush::GetSurroundColorCount(), PathGradientBrush::GetSurroundColors(), GetTransform(), PathGradientBrush::GetTransform(), TextureBrush::GetTransfrom(), Brush::GetType(), GetWrapMode(), TextureBrush::GetWrapMode(), PathGradientBrush::GetWrapMode(), MultiplyTransform(), TextureBrush::MultiplyTransform(), PathGradientBrush::MultiplyTransform(), ResetTransform(), TextureBrush::ResetTransform(), PathGradientBrush::ResetTransform(), RotateTranform(), TextureBrush::RotateTransform(), PathGradientBrush::RotateTransform(), ScaleTransform(), TextureBrush::ScaleTransform(), PathGradientBrush::ScaleTransform(), SetBlend(), PathGradientBrush::SetBlend(), SetBlendBellShape(), PathGradientBrush::SetBlendBellShape(), SetBlendTriangularShape(), PathGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetCenterColor(), PathGradientBrush::SetCenterPoint(), SolidBrush::SetColor(), PathGradientBrush::SetFocusScales(), SetGammaCorrection(), PathGradientBrush::SetGammaCorrection(), SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), SetLinearColors(), PathGradientBrush::SetSurroundColors(), SetTransform(), TextureBrush::SetTransform(), PathGradientBrush::SetTransform(), SetWrapMode(), TextureBrush::SetWrapMode(), PathGradientBrush::SetWrapMode(), TranslateTransform(), TextureBrush::TranslateTransform(), and PathGradientBrush::TranslateTransform().
Field Documentation
lastStatus
Status Brush::lastStatus mutable private inherited
Definition at line 81 of file gdiplusbrush.h.
Referenced by Brush::Clone(), HatchBrush::Clone(), Clone(), SolidBrush::Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), Brush::GetLastStatus(), GetLinearColors(), PathGradientBrush::GetSurroundColors(), HatchBrush::HatchBrush(), LinearGradientBrush(), PathGradientBrush::PathGradientBrush(), SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), PathGradientBrush::SetSurroundColors(), SolidBrush::SolidBrush(), TextureBrush::TextureBrush(), and Brush::updateStatus().
nativeBrush
GpBrush* Brush::nativeBrush private inherited
Definition at line 80 of file gdiplusbrush.h.
Referenced by HatchBrush::Clone(), Clone(), SolidBrush::Clone(), TextureBrush::Clone(), PathGradientBrush::Clone(), Graphics::DrawDriverString(), Graphics::DrawString(), Graphics::FillClosedCurve(), Graphics::FillEllipse(), Graphics::FillPath(), Graphics::FillPie(), Graphics::FillPolygon(), Graphics::FillRectangle(), Graphics::FillRectangles(), Graphics::FillRegion(), HatchBrush::GetBackgroundColor(), GetBlend(), PathGradientBrush::GetBlend(), GetBlendCount(), PathGradientBrush::GetBlendCount(), PathGradientBrush::GetCenterColor(), PathGradientBrush::GetCenterPoint(), SolidBrush::GetColor(), PathGradientBrush::GetFocusScales(), HatchBrush::GetForegroundColor(), GetGammaCorrection(), PathGradientBrush::GetGammaCorrection(), HatchBrush::GetHatchStyle(), GetInterpolationColorCount(), PathGradientBrush::GetInterpolationColorCount(), GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), GetLinearColors(), PathGradientBrush::GetPointCount(), GetRectangle(), PathGradientBrush::GetRectangle(), PathGradientBrush::GetSurroundColorCount(), PathGradientBrush::GetSurroundColors(), GetTransform(), PathGradientBrush::GetTransform(), TextureBrush::GetTransfrom(), Brush::GetType(), GetWrapMode(), TextureBrush::GetWrapMode(), PathGradientBrush::GetWrapMode(), HatchBrush::HatchBrush(), LinearGradientBrush(), MultiplyTransform(), TextureBrush::MultiplyTransform(), PathGradientBrush::MultiplyTransform(), PathGradientBrush::PathGradientBrush(), Pen::Pen(), ResetTransform(), TextureBrush::ResetTransform(), PathGradientBrush::ResetTransform(), RotateTranform(), TextureBrush::RotateTransform(), PathGradientBrush::RotateTransform(), ScaleTransform(), TextureBrush::ScaleTransform(), PathGradientBrush::ScaleTransform(), SetBlend(), PathGradientBrush::SetBlend(), SetBlendBellShape(), PathGradientBrush::SetBlendBellShape(), SetBlendTriangularShape(), PathGradientBrush::SetBlendTriangularShape(), Pen::SetBrush(), PathGradientBrush::SetCenterColor(), PathGradientBrush::SetCenterPoint(), SolidBrush::SetColor(), PathGradientBrush::SetFocusScales(), SetGammaCorrection(), PathGradientBrush::SetGammaCorrection(), SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), SetLinearColors(), PathGradientBrush::SetSurroundColors(), SetTransform(), TextureBrush::SetTransform(), PathGradientBrush::SetTransform(), SetWrapMode(), TextureBrush::SetWrapMode(), PathGradientBrush::SetWrapMode(), SolidBrush::SolidBrush(), TextureBrush::TextureBrush(), TranslateTransform(), TextureBrush::TranslateTransform(), PathGradientBrush::TranslateTransform(), and Brush::~Brush().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusbrush.h