ZEQ2-Lite: Allocators
Allocators
Functions
namespace __gnu_cxx _GLIBCXX_VISIBILITY (default)
Detailed Description
Classes encapsulating memory operations.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace __gnu_cxx _GLIBCXX_VISIBILITY (default)
#include <Tools/MinGW/include/c++/4.6.1/ext/array_allocator.h>
Base class.
An allocator that uses previously allocated memory. This memory can be externally, globally, or otherwise allocated.
A meta-allocator with debugging bits, as per [20.4].
This is precisely the allocator defined in the C++ Standard.
all allocation calls operator new
all deallocation calls operator delete
An example allocator which uses a non-standard pointer type.
This allocator specifies that containers use a 'relative pointer' as it's pointer type. (See ext/pointer.h) Memory allocation in this example is still performed using std::allocator.
An allocator that uses malloc.
This is precisely the allocator defined in the C++ Standard.
all allocation calls malloc
all deallocation calls free
Base class for pool object.
Data describing the underlying memory pool, parameterized on threading support.
Specialization for single thread.
Policy for shared __pool objects.
Policy for individual __pool objects.
Base class for _Tp dependent member functions.
This is a fixed size (power of 2) allocator which - when compiled with thread support - will maintain one freelist per size per thread plus a global one. Steps are taken to limit the per thread freelist sizes (by returning excess back to the global list).
Further details: http://gcc.gnu.org/onlinedocs/libstdc++/manual/bk01pt12ch32.html
An allocator that uses global new, as per [20.4].
This is precisely the allocator defined in the C++ Standard.
all allocation calls operator new
all deallocation calls operator delete
Base class for __pool_alloc.
Uses various allocators to fulfill underlying requests (and makes as few requests as possible when in default high-speed pool mode).
Important implementation properties: 0. If globally mandated, then allocate objects from new
If the clients request an object of size > _S_max_bytes, the resulting object will be obtained directly from new
In all other cases, we allocate an object of size exactly _S_round_up(requested_size). Thus the client has enough size information that we can return the object to the proper free list without permanently losing part of the object.
Allocator using a memory pool with a single lock.
Definition at line 39 of file array_allocator.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
  using std::size_t;
  using std::ptrdiff_t;
  template<typename _Tp>
     class array_allocator_base
     {
     public:
       typedef size_t        size_type;
       typedef ptrdiff_t     difference_type;
       typedef _Tp*          pointer;
       typedef const _Tp*    const_pointer;
       typedef _Tp&          reference;
       typedef const _Tp&    const_reference;
       typedef _Tp           value_type;
       pointer
       address(reference __x) const { return std::__addressof(__x); }
       const_pointer
       address(const_reference __x) const { return std::__addressof(__x); }
       void
       deallocate(pointer, size_type)
       {
     // Does nothing.
       }
       size_type
       max_size() const throw()
       { return size_t(-1) / sizeof(_Tp); }
       // _GLIBCXX_RESOLVE_LIB_DEFECTS
       // 402. wrong new expression in [some_] allocator::construct
       void
       construct(pointer __p, const _Tp& __val)
       { ::new((void *)__p) value_type(__val); }
 #ifdef __GXX_EXPERIMENTAL_CXX0X__
       template<typename... _Args>
         void
         construct(pointer __p, _Args&&... __args)
     { ::new((void *)__p) _Tp(std::forward<_Args>(__args)...); }
 #endif
       void
       destroy(pointer __p) { __p->~_Tp(); }
     };
   template<typename _Tp, typename _Array = std::tr1::array<_Tp, 1> >
     class array_allocator : public array_allocator_base<_Tp>
     {
     public:
       typedef size_t        size_type;
       typedef ptrdiff_t     difference_type;
       typedef _Tp*          pointer;
       typedef const _Tp*    const_pointer;
       typedef _Tp&          reference;
       typedef const _Tp&    const_reference;
       typedef _Tp           value_type;
       typedef _Array        array_type;
     private:
       array_type*   _M_array;
       size_type     _M_used;
     public:
      template<typename _Tp1, typename _Array1 = _Array>
         struct rebind
         { typedef array_allocator<_Tp1, _Array1> other; };
       array_allocator(array_type* __array = 0) throw()
       : _M_array(__array), _M_used(size_type()) { }
       array_allocator(const array_allocator& __o)  throw()
       : _M_array(__o._M_array), _M_used(__o._M_used) { }
       template<typename _Tp1, typename _Array1>
         array_allocator(const array_allocator<_Tp1, _Array1>&) throw()
     : _M_array(0), _M_used(size_type()) { }
       ~array_allocator() throw() { }
       pointer
       allocate(size_type __n, const void* = 0)
       {
     if (_M_array == 0 || _M_used + __n > _M_array->size())
       std::__throw_bad_alloc();
     pointer __ret = _M_array->begin() + _M_used;
     _M_used += __n;
     return __ret;
       }
     };
   template<typename _Tp, typename _Array>
     inline bool
     operator==(const array_allocator<_Tp, _Array>&,
            const array_allocator<_Tp, _Array>&)
     { return true; }
   template<typename _Tp, typename _Array>
     inline bool
     operator!=(const array_allocator<_Tp, _Array>&,
            const array_allocator<_Tp, _Array>&)
     { return false; }
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References allocate(), construct(), deallocate(), new, std::__exception_ptr::operator!=(), and std::__exception_ptr::operator==().