ZEQ2-Lite: __gnu_profile::__reentrance_guard Struct Reference
__gnu_profile::__reentrance_guard Struct Reference
Reentrance guard.
#include <profiler.h>
Public Member Functions
__reentrance_guard ()
~__reentrance_guard ()
Static Public Member Functions
static bool __get_in ()
static bool & __inside ()
Detailed Description
Reentrance guard.
Mechanism to protect all __gnu_profile operations against recursion, multithreaded and exception reentrance.
Definition at line 65 of file profiler.h.
Constructor & Destructor Documentation
__reentrance_guard()
__gnu_profile::__reentrance_guard::__reentrance_guard () inline
Definition at line 86 of file profiler.h.
 { }
~__reentrance_guard()
__gnu_profile::__reentrance_guard::~__reentrance_guard () inline
Definition at line 87 of file profiler.h.
 { __inside() = false; }
References __inside().
Member Function Documentation
__get_in()
static bool __gnu_profile::__reentrance_guard::__get_in () inline static
Definition at line 68 of file profiler.h.
     {
       if (__inside() == true)
     return false;
       else
     {
       __inside() = true;
       return true;
     }
     }
References __inside().
__inside()
static bool& __gnu_profile::__reentrance_guard::__inside () inline static
Definition at line 80 of file profiler.h.
     {
       static __thread bool _S_inside(false);
       return _S_inside;
     }
Referenced by __get_in(), and ~__reentrance_guard().
The documentation for this struct was generated from the following file:
Tools/MinGW/include/c++/4.6.1/profile/impl/profiler.h