ZEQ2-Lite: Tools/MinGW/include/io.h File Reference
io.h File Reference
#include <_mingw.h>
#include <sys/types.h>
Data Structures
struct _finddata_t
struct _finddatai64_t
struct _wfinddata_t
struct _wfinddatai64_t
Macros
#define _A_ARCH 0x00000020
#define _A_HIDDEN 0x00000002
#define _A_NORMAL 0x00000000
#define _A_RDONLY 0x00000001
#define _A_SUBDIR 0x00000010
#define _A_SYSTEM 0x00000004
#define _A_VOLID 0x00000008
#define _FSIZE_T_DEFINED
#define _INTPTR_T_DEFINED
#define _WFINDDATA_T_DEFINED
#define _WIO_DEFINED
#define F_OK 0 /* Check for file existence */
#define FILENAME_MAX (260)
#define HANDLE_MAX FOPEN_MAX
#define R_OK 4 /* Check for read permission */
#define W_OK 2 /* Check for write permission */
#define X_OK 1 /* MS access() doesn't check for execute permission. */
Typedefs
typedef unsigned long _fsize_t
typedef int intptr_t
Functions
_CRTIMP int __cdecl __MINGW_NOTHROW _access (const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _chdir (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _chmod (const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _chsize (int, long)
_CRTIMP int __cdecl __MINGW_NOTHROW _close (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _commit (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _creat (const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _dup (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _dup2 (int, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _eof (int)
_CRTIMP long __cdecl __MINGW_NOTHROW _filelength (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _findclose (long)
_CRTIMP long __cdecl __MINGW_NOTHROW _findfirst (const char *, struct _finddata_t *)
_CRTIMP int __cdecl __MINGW_NOTHROW _findnext (long, struct _finddata_t *)
_CRTIMP long __cdecl __MINGW_NOTHROW _get_osfhandle (int)
_CRTIMP char *__cdecl __MINGW_NOTHROW _getcwd (char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _isatty (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _locking (int, int, long)
_CRTIMP long __cdecl __MINGW_NOTHROW _lseek (int, long, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _mkdir (const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW _mktemp (char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _open (const char *, int,...)
_CRTIMP int __cdecl __MINGW_NOTHROW _open_osfhandle (intptr_t, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _pipe (int *, unsigned int, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _read (int, void *, unsigned int)
_CRTIMP int __cdecl __MINGW_NOTHROW _rmdir (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _setmode (int, int)
_CRTIMP int __cdecl __MINGW_NOTHROW _sopen (const char *, int, int,...)
_CRTIMP long __cdecl __MINGW_NOTHROW _tell (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _umask (int)
_CRTIMP int __cdecl __MINGW_NOTHROW _unlink (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW _write (int, const void *, unsigned int)
_CRTIMP int __cdecl __MINGW_NOTHROW access (const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW chdir (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW chmod (const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW chsize (int, long)
_CRTIMP int __cdecl __MINGW_NOTHROW close (int)
_CRTIMP int __cdecl __MINGW_NOTHROW creat (const char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW dup (int)
_CRTIMP int __cdecl __MINGW_NOTHROW dup2 (int, int)
_CRTIMP int __cdecl __MINGW_NOTHROW eof (int)
_CRTIMP long __cdecl __MINGW_NOTHROW filelength (int)
_CRTIMP char *__cdecl __MINGW_NOTHROW getcwd (char *, int)
_CRTIMP int __cdecl __MINGW_NOTHROW isatty (int)
_CRTIMP long __cdecl __MINGW_NOTHROW lseek (int, long, int)
_CRTIMP int __cdecl __MINGW_NOTHROW mkdir (const char *)
_CRTIMP char *__cdecl __MINGW_NOTHROW mktemp (char *)
_CRTIMP int __cdecl __MINGW_NOTHROW open (const char *, int,...)
_CRTIMP int __cdecl __MINGW_NOTHROW read (int, void *, unsigned int)
_CRTIMP int __cdecl __MINGW_NOTHROW remove (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW rename (const char *, const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW rmdir (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW setmode (int, int)
_CRTIMP int __cdecl __MINGW_NOTHROW sopen (const char *, int, int,...)
_CRTIMP long __cdecl __MINGW_NOTHROW tell (int)
_CRTIMP int __cdecl __MINGW_NOTHROW umask (int)
_CRTIMP int __cdecl __MINGW_NOTHROW unlink (const char *)
_CRTIMP int __cdecl __MINGW_NOTHROW write (int, const void *, unsigned int)
Macro Definition Documentation
_A_ARCH
#define _A_ARCH 0x00000020
Definition at line 31 of file io.h.
_A_HIDDEN
#define _A_HIDDEN 0x00000002
Definition at line 27 of file io.h.
_A_NORMAL
#define _A_NORMAL 0x00000000
Definition at line 25 of file io.h.
_A_RDONLY
#define _A_RDONLY 0x00000001
Definition at line 26 of file io.h.
_A_SUBDIR
#define _A_SUBDIR 0x00000010
Definition at line 30 of file io.h.
_A_SYSTEM
#define _A_SYSTEM 0x00000004
Definition at line 28 of file io.h.
_A_VOLID
#define _A_VOLID 0x00000008
Definition at line 29 of file io.h.
_FSIZE_T_DEFINED
#define _FSIZE_T_DEFINED
Definition at line 47 of file io.h.
_INTPTR_T_DEFINED
#define _INTPTR_T_DEFINED
Definition at line 37 of file io.h.
_WFINDDATA_T_DEFINED
#define _WFINDDATA_T_DEFINED
Definition at line 185 of file io.h.
_WIO_DEFINED
#define _WIO_DEFINED
Definition at line 431 of file io.h.
F_OK
#define F_OK 0 /* Check for file existence */
Definition at line 322 of file io.h.
FILENAME_MAX
#define FILENAME_MAX (260)
Definition at line 56 of file io.h.
HANDLE_MAX
#define HANDLE_MAX FOPEN_MAX
Definition at line 318 of file io.h.
R_OK
#define R_OK 4 /* Check for read permission */
Definition at line 327 of file io.h.
W_OK
#define W_OK 2 /* Check for write permission */
Definition at line 326 of file io.h.
X_OK
#define X_OK 1 /* MS access() doesn't check for execute permission. */
Definition at line 325 of file io.h.
Typedef Documentation
_fsize_t
typedef unsigned long _fsize_t
Definition at line 46 of file io.h.
intptr_t
typedef int intptr_t
Definition at line 41 of file io.h.
Function Documentation
_access()
_CRTIMP int __cdecl __MINGW_NOTHROW _access (const char * , int)
_chdir()
_CRTIMP int __cdecl __MINGW_NOTHROW _chdir (const char *)
_chmod()
_CRTIMP int __cdecl __MINGW_NOTHROW _chmod (const char * , int)
_chsize()
_CRTIMP int __cdecl __MINGW_NOTHROW _chsize (int , long)
Referenced by ftruncate().
_close()
_CRTIMP int __cdecl __MINGW_NOTHROW _close (int)
_commit()
_CRTIMP int __cdecl __MINGW_NOTHROW _commit (int)
_creat()
_CRTIMP int __cdecl __MINGW_NOTHROW _creat (const char * , int)
_dup()
_CRTIMP int __cdecl __MINGW_NOTHROW _dup (int)
_dup2()
_CRTIMP int __cdecl __MINGW_NOTHROW _dup2 (int , int)
_eof()
_CRTIMP int __cdecl __MINGW_NOTHROW _eof (int)
_filelength()
_CRTIMP long __cdecl __MINGW_NOTHROW _filelength (int)
_findclose()
_CRTIMP int __cdecl __MINGW_NOTHROW _findclose (long)
Referenced by Sys_ListFiles(), and Sys_ListFilteredFiles().
_findfirst()
_CRTIMP long __cdecl __MINGW_NOTHROW _findfirst (const char * , struct _finddata_t *)
Referenced by Sys_ListFiles(), and Sys_ListFilteredFiles().
_findnext()
_CRTIMP int __cdecl __MINGW_NOTHROW _findnext (long , struct _finddata_t *)
Referenced by Sys_ListFiles(), and Sys_ListFilteredFiles().
_get_osfhandle()
_CRTIMP long __cdecl __MINGW_NOTHROW _get_osfhandle (int)
_getcwd()
_CRTIMP char* __cdecl __MINGW_NOTHROW _getcwd (char * , int)
Referenced by Q_getwd(), and Sys_Cwd().
_isatty()
_CRTIMP int __cdecl __MINGW_NOTHROW _isatty (int)
_locking()
_CRTIMP int __cdecl __MINGW_NOTHROW _locking (int , int , long)
_lseek()
_CRTIMP long __cdecl __MINGW_NOTHROW _lseek (int , long , int)
_mkdir()
_CRTIMP int __cdecl __MINGW_NOTHROW _mkdir (const char *)
Referenced by Q_mkdir().
_mktemp()
_CRTIMP char* __cdecl __MINGW_NOTHROW _mktemp (char *)
_open()
_CRTIMP int __cdecl __MINGW_NOTHROW _open (const char * , int , ...)
_open_osfhandle()
_CRTIMP int __cdecl __MINGW_NOTHROW _open_osfhandle (intptr_t , int)
_pipe()
_CRTIMP int __cdecl __MINGW_NOTHROW _pipe (int * , unsigned int , int)
_read()
_CRTIMP int __cdecl __MINGW_NOTHROW _read (int , void * , unsigned int)
_rmdir()
_CRTIMP int __cdecl __MINGW_NOTHROW _rmdir (const char *)
_setmode()
_CRTIMP int __cdecl __MINGW_NOTHROW _setmode (int , int)
_sopen()
_CRTIMP int __cdecl __MINGW_NOTHROW _sopen (const char * , int , int , ...)
_tell()
_CRTIMP long __cdecl __MINGW_NOTHROW _tell (int)
_umask()
_CRTIMP int __cdecl __MINGW_NOTHROW _umask (int)
_unlink()
_CRTIMP int __cdecl __MINGW_NOTHROW _unlink (const char *)
_write()
_CRTIMP int __cdecl __MINGW_NOTHROW _write (int , const void * , unsigned int)
access()
_CRTIMP int __cdecl __MINGW_NOTHROW access (const char * , int)
Referenced by exists().
chdir()
_CRTIMP int __cdecl __MINGW_NOTHROW chdir (const char *)
chmod()
_CRTIMP int __cdecl __MINGW_NOTHROW chmod (const char * , int)
chsize()
_CRTIMP int __cdecl __MINGW_NOTHROW chsize (int , long)
close()
_CRTIMP int __cdecl __MINGW_NOTHROW close (int)
Referenced by _GLIBCXX_VISIBILITY(), DECLARE_INTERFACE_(), mumble_link(), Sys_ErrorDialog(), and unsetsource().
creat()
_CRTIMP int __cdecl __MINGW_NOTHROW creat (const char * , int)
Referenced by setup().
dup()
_CRTIMP int __cdecl __MINGW_NOTHROW dup (int)
Referenced by CL_ConfigstringModified().
dup2()
_CRTIMP int __cdecl __MINGW_NOTHROW dup2 (int , int)
Referenced by setup().
eof()
_CRTIMP int __cdecl __MINGW_NOTHROW eof (int)
Referenced by _GLIBCXX_VISIBILITY().
filelength()
_CRTIMP long __cdecl __MINGW_NOTHROW filelength (int)
getcwd()
_CRTIMP char* __cdecl __MINGW_NOTHROW getcwd (char * , int)
Referenced by Q_getwd(), and Sys_Cwd().
isatty()
_CRTIMP int __cdecl __MINGW_NOTHROW isatty (int)
Referenced by Sys_PlatformInit().
lseek()
_CRTIMP long __cdecl __MINGW_NOTHROW lseek (int , long , int)
mkdir()
_CRTIMP int __cdecl __MINGW_NOTHROW mkdir (const char *)
Referenced by Q_mkdir(), and Sys_Mkdir().
mktemp()
_CRTIMP char* __cdecl __MINGW_NOTHROW mktemp (char *)
open()
_CRTIMP int __cdecl __MINGW_NOTHROW open (const char * , int , ...)
Referenced by _GLIBCXX_VISIBILITY(), CM_AdjustAreaPortalState(), DECLARE_INTERFACE_(), doinclude(), setup(), SV_AdjustAreaPortalState(), Sys_ErrorDialog(), and trap_AdjustAreaPortalState().
read()
_CRTIMP int __cdecl __MINGW_NOTHROW read (int , void * , unsigned int)
Referenced by Com_ReadFromPipe(), CON_FlushIn(), CON_Input(), fillbuf(), and FS_Read().
remove()
_CRTIMP int __cdecl __MINGW_NOTHROW remove (const char *)
Referenced by __attribute__(), _GLIBCXX_VISIBILITY(), FS_HomeRemove(), FS_Remove(), rm(), and WriteVmFile().
rename()
_CRTIMP int __cdecl __MINGW_NOTHROW rename (const char * , const char *)
Referenced by FS_Rename(), and FS_SV_Rename().
rmdir()
_CRTIMP int __cdecl __MINGW_NOTHROW rmdir (const char *)
setmode()
_CRTIMP int __cdecl __MINGW_NOTHROW setmode (int , int)
sopen()
_CRTIMP int __cdecl __MINGW_NOTHROW sopen (const char * , int , int , ...)
tell()
_CRTIMP long __cdecl __MINGW_NOTHROW tell (int)
umask()
_CRTIMP int __cdecl __MINGW_NOTHROW umask (int)
unlink()
_CRTIMP int __cdecl __MINGW_NOTHROW unlink (const char *)
write()
_CRTIMP int __cdecl __MINGW_NOTHROW write (int , const void * , unsigned int)
Referenced by CON_Back(), CON_Input(), CON_Show(), DECLARE_INTERFACE_(), doinclude(), flushout(), inflate_fast(), puttokens(), and Sys_ErrorDialog().