ZEQ2-Lite: Engine/server/sv_game.c File Reference
sv_game.c File Reference
#include "server.h"
Functions
static int FloatAsInt (float f)
void SV_AdjustAreaPortalState (sharedEntity_t *ent, qboolean open)
qboolean SV_EntityContact (vec3_t mins, vec3_t maxs, const sharedEntity_t *gEnt, int capsule)
playerState_t * SV_GameClientNum (int num)
qboolean SV_GameCommand (void)
void SV_GameDropClient (int clientNum, const char *reason)
void SV_GameSendServerCommand (int clientNum, const char *text)
intptr_t SV_GameSystemCalls (intptr_t *args)
sharedEntity_t * SV_GEntityForSvEntity (svEntity_t *svEnt)
sharedEntity_t * SV_GentityNum (int num)
void SV_GetServerinfo (char *buffer, int bufferSize)
void SV_GetUsercmd (int clientNum, usercmd_t *cmd)
void SV_InitGameProgs (void)
static void SV_InitGameVM (qboolean restart)
qboolean SV_inPVS (const vec3_t p1, const vec3_t p2)
qboolean SV_inPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
void SV_LocateGameData (sharedEntity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *clients, int sizeofGameClient)
int SV_NumForGentity (sharedEntity_t *ent)
void SV_RestartGameProgs (void)
void SV_SetBrushModel (sharedEntity_t *ent, const char *name)
void SV_ShutdownGameProgs (void)
svEntity_t * SV_SvEntityForGentity (sharedEntity_t *gEnt)
Function Documentation
FloatAsInt()
static int FloatAsInt (float f) static
Definition at line 275 of file sv_game.c.
{
     floatint_t fi;
     fi.f = f;
     return fi.i;
 }
References floatint_t::f, and floatint_t::i.
Referenced by SV_GameSystemCalls().
SV_AdjustAreaPortalState()
void SV_AdjustAreaPortalState (sharedEntity_t * ent, qboolean open)
Definition at line 197 of file sv_game.c.
{
     svEntity_t  *svEnt;
     svEnt = SV_SvEntityForGentity( ent );
     if ( svEnt->areanum2 == -1 ) {
         return;
     }
     CM_AdjustAreaPortalState( svEnt->areanum, svEnt->areanum2, open );
 }
References CM_AdjustAreaPortalState(), and SV_SvEntityForGentity().
Referenced by SV_GameSystemCalls().
SV_EntityContact()
qboolean SV_EntityContact (vec3_t mins, vec3_t maxs, const sharedEntity_t * gEnt, int capsule)
Definition at line 213 of file sv_game.c.
{
     const float *origin, *angles;
     clipHandle_t    ch;
     trace_t         trace;
     // check for exact collision
     origin = gEnt->r.currentOrigin;
     angles = gEnt->r.currentAngles;
     ch = SV_ClipHandleForEntity( gEnt );
     CM_TransformedBoxTrace ( &trace, vec3_origin, vec3_origin, mins, maxs,
         ch, -1, origin, angles, capsule );
     return trace.startsolid;
 }
References angles, CM_TransformedBoxTrace(), entityShared_t::currentAngles, entityShared_t::currentOrigin, sharedEntity_t::r, trace_t::startsolid, SV_ClipHandleForEntity(), and vec3_origin.
Referenced by SV_GameSystemCalls().
SV_GameClientNum()
playerState_t* SV_GameClientNum (int num)
Definition at line 44 of file sv_game.c.
{
     playerState_t   *ps;
     ps = (playerState_t *)((byte *)sv.gameClients + sv.gameClientSize*(num));
     return ps;
 }
SV_GameCommand()
qboolean SV_GameCommand (void)
Definition at line 560 of file sv_game.c.
{
     if ( sv.state != SS_GAME ) {
         return qfalse;
     }
     return VM_Call( gvm, GAME_CONSOLE_COMMAND );
 }
Referenced by Cmd_ExecuteString().
SV_GameDropClient()
void SV_GameDropClient (int clientNum, const char * reason)
Definition at line 92 of file sv_game.c.
{
     if ( clientNum < 0 || clientNum >= sv_maxclients->integer ) {
         return;
     }
     SV_DropClient( svs.clients + clientNum, reason );
 }
References serverStatic_t::clients, SV_DropClient(), sv_maxclients, and svs.
Referenced by SV_GameSystemCalls().
SV_GameSendServerCommand()
void SV_GameSendServerCommand (int clientNum, const char * text)
Definition at line 73 of file sv_game.c.
{
     if ( clientNum == -1 ) {
         SV_SendServerCommand( NULL, "%s", text );
     } else {
         if ( clientNum < 0 || clientNum >= sv_maxclients->integer ) {
             return;
         }
         SV_SendServerCommand( svs.clients + clientNum, "%s", text );
     }
 }
References serverStatic_t::clients, NULL, sv_maxclients, SV_SendServerCommand(), and svs.
Referenced by SV_GameSystemCalls().
SV_GameSystemCalls()
intptr_t SV_GameSystemCalls (intptr_t * args)
Definition at line 288 of file sv_game.c.
{
     switch( args[0] ) {
     case G_PRINT:
         Com_Printf( "%s", (const char*)VMA(1) );
         return 0;
     case G_ERROR:
         Com_Error( ERR_DROP, "%s", (const char*)VMA(1) );
         return 0;
     case G_MILLISECONDS:
         return Sys_Milliseconds();
     case G_CVAR_REGISTER:
         Cvar_Register( VMA(1), VMA(2), VMA(3), args[4] );
         return 0;
     case G_CVAR_UPDATE:
         Cvar_Update( VMA(1) );
         return 0;
     case G_CVAR_SET:
         Cvar_SetSafe( (const char *)VMA(1), (const char *)VMA(2) );
         return 0;
     case G_CVAR_VARIABLE_INTEGER_VALUE:
         return Cvar_VariableIntegerValue( (const char *)VMA(1) );
     case G_CVAR_VARIABLE_STRING_BUFFER:
         Cvar_VariableStringBuffer( VMA(1), VMA(2), args[3] );
         return 0;
     case G_ARGC:
         return Cmd_Argc();
     case G_ARGV:
         Cmd_ArgvBuffer( args[1], VMA(2), args[3] );
         return 0;
     case G_SEND_CONSOLE_COMMAND:
         Cbuf_ExecuteText( args[1], VMA(2) );
         return 0;
     case G_FS_FOPEN_FILE:
         return FS_FOpenFileByMode( VMA(1), VMA(2), args[3] );
     case G_FS_READ:
         FS_Read2( VMA(1), args[2], args[3] );
         return 0;
     case G_FS_WRITE:
         FS_Write( VMA(1), args[2], args[3] );
         return 0;
     case G_FS_FCLOSE_FILE:
         FS_FCloseFile( args[1] );
         return 0;
     case G_FS_GETFILELIST:
         return FS_GetFileList( VMA(1), VMA(2), VMA(3), args[4] );
     case G_LOCATE_GAME_DATA:
         SV_LocateGameData( VMA(1), args[2], args[3], VMA(4), args[5] );
         return 0;
     case G_DROP_CLIENT:
         SV_GameDropClient( args[1], VMA(2) );
         return 0;
     case G_SEND_SERVER_COMMAND:
         SV_GameSendServerCommand( args[1], VMA(2) );
         return 0;
     case G_LINKENTITY:
         SV_LinkEntity( VMA(1) );
         return 0;
     case G_UNLINKENTITY:
         SV_UnlinkEntity( VMA(1) );
         return 0;
     case G_ENTITIES_IN_BOX:
         return SV_AreaEntities( VMA(1), VMA(2), VMA(3), args[4] );
     case G_ENTITY_CONTACT:
         return SV_EntityContact( VMA(1), VMA(2), VMA(3), /*int capsule*/ qfalse );
     case G_ENTITY_CONTACTCAPSULE:
         return SV_EntityContact( VMA(1), VMA(2), VMA(3), /*int capsule*/ qtrue );
     case G_TRACE:
         SV_Trace( VMA(1), VMA(2), VMA(3), VMA(4), VMA(5), args[6], args[7], /*int capsule*/ qfalse );
         return 0;
     case G_TRACECAPSULE:
         SV_Trace( VMA(1), VMA(2), VMA(3), VMA(4), VMA(5), args[6], args[7], /*int capsule*/ qtrue );
         return 0;
     case G_POINT_CONTENTS:
         return SV_PointContents( VMA(1), args[2] );
     case G_SET_BRUSH_MODEL:
         SV_SetBrushModel( VMA(1), VMA(2) );
         return 0;
     case G_IN_PVS:
         return SV_inPVS( VMA(1), VMA(2) );
     case G_IN_PVS_IGNORE_PORTALS:
         return SV_inPVSIgnorePortals( VMA(1), VMA(2) );
     case G_SET_CONFIGSTRING:
         SV_SetConfigstring( args[1], VMA(2) );
         return 0;
     case G_GET_CONFIGSTRING:
         SV_GetConfigstring( args[1], VMA(2), args[3] );
         return 0;
     case G_SET_USERINFO:
         SV_SetUserinfo( args[1], VMA(2) );
         return 0;
     case G_GET_USERINFO:
         SV_GetUserinfo( args[1], VMA(2), args[3] );
         return 0;
     case G_GET_SERVERINFO:
         SV_GetServerinfo( VMA(1), args[2] );
         return 0;
     case G_ADJUST_AREA_PORTAL_STATE:
         SV_AdjustAreaPortalState( VMA(1), args[2] );
         return 0;
     case G_AREAS_CONNECTED:
         return CM_AreasConnected( args[1], args[2] );
     case G_GET_USERCMD:
         SV_GetUsercmd( args[1], VMA(2) );
         return 0;
     case G_GET_ENTITY_TOKEN:
         {
             const char  *s;
             s = COM_Parse( &sv.entityParsePoint );
             Q_strncpyz( VMA(1), s, args[2] );
             if ( !sv.entityParsePoint && !s[0] ) {
                 return qfalse;
             } else {
                 return qtrue;
             }
         }
     case G_REAL_TIME:
         return Com_RealTime( VMA(1) );
     case G_SNAPVECTOR:
         Q_SnapVector(VMA(1));
         return 0;
         //====================================
     case TRAP_MEMSET:
         Com_Memset( VMA(1), args[2], args[3] );
         return 0;
     case TRAP_MEMCPY:
         Com_Memcpy( VMA(1), VMA(2), args[3] );
         return 0;
     case TRAP_STRNCPY:
         strncpy( VMA(1), VMA(2), args[3] );
         return args[1];
     case TRAP_SIN:
         return FloatAsInt( sin( VMF(1) ) );
     case TRAP_COS:
         return FloatAsInt( cos( VMF(1) ) );
     case TRAP_ATAN2:
         return FloatAsInt( atan2( VMF(1), VMF(2) ) );
     case TRAP_SQRT:
         return FloatAsInt( sqrt( VMF(1) ) );
     case TRAP_MATRIXMULTIPLY:
         MatrixMultiply( VMA(1), VMA(2), VMA(3) );
         return 0;
     case TRAP_ANGLEVECTORS:
         AngleVectors( VMA(1), VMA(2), VMA(3), VMA(4) );
         return 0;
     case TRAP_PERPENDICULARVECTOR:
         PerpendicularVector( VMA(1), VMA(2) );
         return 0;
     case TRAP_FLOOR:
         return FloatAsInt( floor( VMF(1) ) );
     case TRAP_CEIL:
         return FloatAsInt( ceil( VMF(1) ) );
     default:
         Com_Error( ERR_DROP, "Bad game system trap: %ld", (long int) args[0] );
     }
     return 0;
 }
References AngleVectors(), args, Cbuf_ExecuteText(), CM_AreasConnected(), Cmd_Argc(), Cmd_ArgvBuffer(), Com_Error(), Com_Memcpy, Com_Memset, COM_Parse(), Com_Printf(), Com_RealTime(), Cvar_Register(), Cvar_SetSafe(), Cvar_Update(), Cvar_VariableIntegerValue(), Cvar_VariableStringBuffer(), server_t::entityParsePoint, ERR_DROP, FloatAsInt(), FS_FCloseFile(), FS_FOpenFileByMode(), FS_GetFileList(), FS_Read2(), FS_Write(), G_ADJUST_AREA_PORTAL_STATE, G_AREAS_CONNECTED, G_ARGC, G_ARGV, G_CVAR_REGISTER, G_CVAR_SET, G_CVAR_UPDATE, G_CVAR_VARIABLE_INTEGER_VALUE, G_CVAR_VARIABLE_STRING_BUFFER, G_DROP_CLIENT, G_ENTITIES_IN_BOX, G_ENTITY_CONTACT, G_ENTITY_CONTACTCAPSULE, G_ERROR, G_FS_FCLOSE_FILE, G_FS_FOPEN_FILE, G_FS_GETFILELIST, G_FS_READ, G_FS_WRITE, G_GET_CONFIGSTRING, G_GET_ENTITY_TOKEN, G_GET_SERVERINFO, G_GET_USERCMD, G_GET_USERINFO, G_IN_PVS, G_IN_PVS_IGNORE_PORTALS, G_LINKENTITY, G_LOCATE_GAME_DATA, G_MILLISECONDS, G_POINT_CONTENTS, G_PRINT, G_REAL_TIME, G_SEND_CONSOLE_COMMAND, G_SEND_SERVER_COMMAND, G_SET_BRUSH_MODEL, G_SET_CONFIGSTRING, G_SET_USERINFO, G_SNAPVECTOR, G_TRACE, G_TRACECAPSULE, G_UNLINKENTITY, MatrixMultiply(), PerpendicularVector(), Q_SnapVector, Q_strncpyz(), qfalse, qtrue, sv, SV_AdjustAreaPortalState(), SV_AreaEntities(), SV_EntityContact(), SV_GameDropClient(), SV_GameSendServerCommand(), SV_GetConfigstring(), SV_GetServerinfo(), SV_GetUsercmd(), SV_GetUserinfo(), SV_inPVS(), SV_inPVSIgnorePortals(), SV_LinkEntity(), SV_LocateGameData(), SV_PointContents(), SV_SetBrushModel(), SV_SetConfigstring(), SV_SetUserinfo(), SV_Trace(), SV_UnlinkEntity(), Sys_Milliseconds(), TRAP_ANGLEVECTORS, TRAP_ATAN2, TRAP_CEIL, TRAP_COS, TRAP_FLOOR, TRAP_MATRIXMULTIPLY, TRAP_MEMCPY, TRAP_MEMSET, TRAP_PERPENDICULARVECTOR, TRAP_SIN, TRAP_SQRT, TRAP_STRNCPY, VMA, and VMF.
Referenced by SV_InitGameProgs().
SV_GEntityForSvEntity()
sharedEntity_t* SV_GEntityForSvEntity (svEntity_t * svEnt)
Definition at line 59 of file sv_game.c.
{
     int     num;
     num = svEnt - sv.svEntities;
     return SV_GentityNum( num );
 }
SV_GentityNum()
sharedEntity_t* SV_GentityNum (int num)
Definition at line 36 of file sv_game.c.
{
     sharedEntity_t *ent;
     ent = (sharedEntity_t *)((byte *)sv.gentities + sv.gentitySize*(num));
     return ent;
 }
Referenced by SV_GEntityForSvEntity().
SV_GetServerinfo()
void SV_GetServerinfo (char * buffer, int bufferSize)
Definition at line 236 of file sv_game.c.
{
     if ( bufferSize < 1 ) {
         Com_Error( ERR_DROP, "SV_GetServerinfo: bufferSize == %i", bufferSize );
     }
     Q_strncpyz( buffer, Cvar_InfoString( CVAR_SERVERINFO ), bufferSize );
 }
References Com_Error(), Cvar_InfoString(), CVAR_SERVERINFO, ERR_DROP, and Q_strncpyz().
Referenced by SV_GameSystemCalls().
SV_GetUsercmd()
void SV_GetUsercmd (int clientNum, usercmd_t * cmd)
Definition at line 266 of file sv_game.c.
{
     if ( clientNum < 0 || clientNum >= sv_maxclients->integer ) {
         Com_Error( ERR_DROP, "SV_GetUsercmd: bad clientNum:%i", clientNum );
     }
     *cmd = svs.clients[clientNum].lastUsercmd;
 }
References serverStatic_t::clients, Com_Error(), ERR_DROP, sv_maxclients, and svs.
Referenced by SV_GameSystemCalls().
SV_InitGameProgs()
void SV_InitGameProgs (void)
Definition at line 540 of file sv_game.c.
{
     cvar_t  *var;
     // load the dll or bytecode
     gvm = VM_Create( "game", SV_GameSystemCalls, Cvar_VariableValue( "vm_game" ) );
     if ( !gvm ) {
         Com_Error( ERR_FATAL, "VM_Create on game failed" );
     }
     SV_InitGameVM( qfalse );
 }
SV_InitGameVM()
static void SV_InitGameVM (qboolean restart) static
Definition at line 489 of file sv_game.c.
{
     int     i;
     // start the entity parsing at the beginning
     sv.entityParsePoint = CM_EntityString();
     // clear all gentity pointers that might still be set from
     // a previous level
     // https://zerowing.idsoftware.com/bugzilla/show_bug.cgi?id=522
     //   now done before GAME_INIT call
     for ( i = 0 ; i < sv_maxclients->integer ; i++ ) {
         svs.clients[i].gentity = NULL;
     }
     // use the current msec count for a random seed
     // init for this gamestate
     VM_Call (gvm, GAME_INIT, sv.time, Com_Milliseconds(), restart);
 }
References serverStatic_t::clients, CM_EntityString(), Com_Milliseconds(), server_t::entityParsePoint, GAME_INIT, gvm, NULL, sv, sv_maxclients, svs, server_t::time, and VM_Call().
Referenced by SV_InitGameProgs(), and SV_RestartGameProgs().
SV_inPVS()
qboolean SV_inPVS (const vec3_t p1, const vec3_t p2)
Definition at line 142 of file sv_game.c.
 {
     int     leafnum;
     int     cluster;
     int     area1, area2;
     byte    *mask;
     leafnum = CM_PointLeafnum (p1);
     cluster = CM_LeafCluster (leafnum);
     area1 = CM_LeafArea (leafnum);
     mask = CM_ClusterPVS (cluster);
     leafnum = CM_PointLeafnum (p2);
     cluster = CM_LeafCluster (leafnum);
     area2 = CM_LeafArea (leafnum);
     if ( mask && (!(mask[cluster>>3] & (1<<(cluster&7)) ) ) )
         return qfalse;
     if (!CM_AreasConnected (area1, area2))
         return qfalse;      // a door blocks sight
     return qtrue;
 }
Referenced by SV_GameSystemCalls().
SV_inPVSIgnorePortals()
qboolean SV_inPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Definition at line 172 of file sv_game.c.
 {
     int     leafnum;
     int     cluster;
     byte    *mask;
     leafnum = CM_PointLeafnum (p1);
     cluster = CM_LeafCluster (leafnum);
     mask = CM_ClusterPVS (cluster);
     leafnum = CM_PointLeafnum (p2);
     cluster = CM_LeafCluster (leafnum);
     if ( mask && (!(mask[cluster>>3] & (1<<(cluster&7)) ) ) )
         return qfalse;
     return qtrue;
 }
References CM_ClusterPVS(), CM_LeafCluster(), CM_PointLeafnum(), p1, p2, qfalse, and qtrue.
Referenced by SV_GameSystemCalls().
SV_LocateGameData()
void SV_LocateGameData (sharedEntity_t * gEnts, int numGEntities, int sizeofGEntity_t, playerState_t * clients, int sizeofGameClient)
Definition at line 249 of file sv_game.c.
{
     sv.gentities = gEnts;
     sv.gentitySize = sizeofGEntity_t;
     sv.num_entities = numGEntities;
     sv.gameClients = clients;
     sv.gameClientSize = sizeofGameClient;
 }
References server_t::gameClients, server_t::gameClientSize, server_t::gentities, server_t::gentitySize, server_t::num_entities, and sv.
Referenced by SV_GameSystemCalls().
SV_NumForGentity()
int SV_NumForGentity (sharedEntity_t * ent)
Definition at line 28 of file sv_game.c.
{
     int     num;
     num = ( (byte *)ent - (byte *)sv.gentities ) / sv.gentitySize;
     return num;
 }
SV_RestartGameProgs()
void SV_RestartGameProgs (void)
Definition at line 517 of file sv_game.c.
{
     if ( !gvm ) {
         return;
     }
     VM_Call( gvm, GAME_SHUTDOWN, qtrue );
     // do a restart instead of a free
     gvm = VM_Restart(gvm, qtrue);
     if ( !gvm ) {
         Com_Error( ERR_FATAL, "VM_Restart on game failed" );
     }
     SV_InitGameVM( qtrue );
 }
SV_SetBrushModel()
void SV_SetBrushModel (sharedEntity_t * ent, const char * name)
Definition at line 107 of file sv_game.c.
{
     clipHandle_t    h;
     vec3_t          mins, maxs;
     if (!name) {
         Com_Error( ERR_DROP, "SV_SetBrushModel: NULL" );
     }
     if (name[0] != '*') {
         Com_Error( ERR_DROP, "SV_SetBrushModel: %s isn't a brush model", name );
     }
     ent->s.modelindex = atoi( name + 1 );
     h = CM_InlineModel( ent->s.modelindex );
     CM_ModelBounds( h, mins, maxs );
     VectorCopy (mins, ent->r.mins);
     VectorCopy (maxs, ent->r.maxs);
     ent->r.bmodel = qtrue;
     ent->r.contents = -1;       // we don't know exactly what is in the brushes
     SV_LinkEntity( ent );       // FIXME: remove
 }
References entityShared_t::bmodel, CM_InlineModel(), CM_ModelBounds(), Com_Error(), entityShared_t::contents, ERR_DROP, entityShared_t::maxs, entityShared_t::mins, qtrue, sharedEntity_t::r, sharedEntity_t::s, SV_LinkEntity(), and VectorCopy.
Referenced by SV_GameSystemCalls().
SV_ShutdownGameProgs()
void SV_ShutdownGameProgs (void)
Definition at line 473 of file sv_game.c.
{
     if ( !gvm ) {
         return;
     }
     VM_Call( gvm, GAME_SHUTDOWN, qfalse );
     VM_Free( gvm );
     gvm = NULL;
 }
SV_SvEntityForGentity()
svEntity_t* SV_SvEntityForGentity (sharedEntity_t * gEnt)
Definition at line 52 of file sv_game.c.
{
     if ( !gEnt || gEnt->s.number < 0 || gEnt->s.number >= MAX_GENTITIES ) {
         Com_Error( ERR_DROP, "SV_SvEntityForGentity: bad gEnt" );
     }
     return &sv.svEntities[ gEnt->s.number ];
 }
Referenced by SV_AdjustAreaPortalState().