ZEQ2-Lite: Source/Game/UI/ui_music.c File Reference
ui_music.c File Reference
#include "ui_local.h"
Data Structures
struct music_t
Macros
#define ARROWS_HEIGHT 48
#define ARROWS_WIDTH 128
#define ART_ARROWLEFT "interface/art/arrows_horz_left"
#define ART_ARROWRIGHT "interface/art/arrows_horz_right"
#define ART_ARROWS "interface/art/arrows_horz_0"
#define ART_BACK0 "interface/art/back_0"
#define ART_BACK1 "interface/art/back_1"
#define ART_FRAMEL "interface/art/frame2_l"
#define ART_FRAMER "interface/art/frame1_r"
#define ART_GO0 "interface/art/play_0"
#define ART_GO1 "interface/art/play_1"
#define ID_BACK 29
#define ID_GO 30
#define ID_LEFT 33
#define ID_LIST 31
#define ID_RIGHT 32
#define MAX_MUSIC 128
#define NAMEBUFSIZE (MAX_MUSIC * 16)
Functions
void Music_Cache (void)
static void Music_MenuEvent (void *ptr, int event)
static void Music_MenuInit (void)
void UI_MusicMenu (void)
static sfxHandle_t UI_MusicMenu_Key (int key)
Variables
static music_t s_music
Macro Definition Documentation
ARROWS_HEIGHT
#define ARROWS_HEIGHT 48
Definition at line 32 of file ui_music.c.
ARROWS_WIDTH
#define ARROWS_WIDTH 128
Definition at line 31 of file ui_music.c.
ART_ARROWLEFT
#define ART_ARROWLEFT "interface/art/arrows_horz_left"
Definition at line 19 of file ui_music.c.
ART_ARROWRIGHT
#define ART_ARROWRIGHT "interface/art/arrows_horz_right"
Definition at line 20 of file ui_music.c.
ART_ARROWS
#define ART_ARROWS "interface/art/arrows_horz_0"
Definition at line 18 of file ui_music.c.
ART_BACK0
#define ART_BACK0 "interface/art/back_0"
Definition at line 12 of file ui_music.c.
ART_BACK1
#define ART_BACK1 "interface/art/back_1"
Definition at line 13 of file ui_music.c.
ART_FRAMEL
#define ART_FRAMEL "interface/art/frame2_l"
Definition at line 16 of file ui_music.c.
ART_FRAMER
#define ART_FRAMER "interface/art/frame1_r"
Definition at line 17 of file ui_music.c.
ART_GO0
#define ART_GO0 "interface/art/play_0"
Definition at line 14 of file ui_music.c.
ART_GO1
#define ART_GO1 "interface/art/play_1"
Definition at line 15 of file ui_music.c.
ID_BACK
#define ID_BACK 29
Definition at line 25 of file ui_music.c.
ID_GO
#define ID_GO 30
Definition at line 26 of file ui_music.c.
ID_LEFT
#define ID_LEFT 33
Definition at line 29 of file ui_music.c.
ID_LIST
#define ID_LIST 31
Definition at line 27 of file ui_music.c.
ID_RIGHT
#define ID_RIGHT 32
Definition at line 28 of file ui_music.c.
MAX_MUSIC
#define MAX_MUSIC 128
Definition at line 22 of file ui_music.c.
NAMEBUFSIZE
#define NAMEBUFSIZE (MAX_MUSIC * 16)
Definition at line 23 of file ui_music.c.
Function Documentation
Music_Cache()
void Music_Cache (void)
Definition at line 107 of file ui_music.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_GO0 );
     trap_R_RegisterShaderNoMip( ART_GO1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_ARROWS );
     trap_R_RegisterShaderNoMip( ART_ARROWLEFT );
     trap_R_RegisterShaderNoMip( ART_ARROWRIGHT );
 }
References ART_ARROWLEFT, ART_ARROWRIGHT, ART_ARROWS, ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, ART_GO0, ART_GO1, and trap_R_RegisterShaderNoMip().
Referenced by Music_MenuInit().
Music_MenuEvent()
static void Music_MenuEvent (void * ptr, int event) static
Definition at line 62 of file ui_music.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch( ((menucommon_s*)ptr)->id ) {
     case ID_GO:
 //      UI_ForceMenuOff ();
         trap_Cmd_ExecuteText( EXEC_APPEND, va( "music music/%s\n",
                                 s_music.list.itemnames[s_music.list.curvalue]) );
         break;
     case ID_BACK:
         UI_PopMenu();
         break;
     case ID_LEFT:
         ScrollList_Key( &s_music.list, K_LEFTARROW );
         break;
     case ID_RIGHT:
         ScrollList_Key( &s_music.list, K_RIGHTARROW );
         break;
     }
 }
References menulist_s::curvalue, EXEC_APPEND, ID_BACK, ID_GO, ID_LEFT, ID_RIGHT, menulist_s::itemnames, K_LEFTARROW, K_RIGHTARROW, music_t::list, ptr(), QM_ACTIVATED, s_music, ScrollList_Key(), trap_Cmd_ExecuteText(), UI_PopMenu(), and va().
Referenced by Music_MenuInit().
Music_MenuInit()
static void Music_MenuInit (void) static
Definition at line 124 of file ui_music.c.
{
     int     i;
     int     len;
     char    *musicname, extension[32];
     memset( &s_music, 0 ,sizeof(music_t) );
     s_music.menu.key = UI_MusicMenu_Key;
     Music_Cache();
     s_music.menu.fullscreen = qfalse;
     s_music.menu.wrapAround = qtrue;
     s_music.banner.generic.type     = MTYPE_BTEXT;
     s_music.banner.generic.x        = 320;
     s_music.banner.generic.y        = 16;
     s_music.banner.string           = "MUSIC";
     s_music.banner.color            = color_white;
     s_music.banner.style            = UI_CENTER|UI_DROPSHADOW;
     s_music.framel.generic.type     = MTYPE_BITMAP;
     s_music.framel.generic.name     = ART_FRAMEL;
     s_music.framel.generic.flags    = QMF_INACTIVE;
     s_music.framel.generic.x        = 0;
     s_music.framel.generic.y        = 78;
     s_music.framel.width            = 256;
     s_music.framel.height           = 329;
     s_music.framer.generic.type     = MTYPE_BITMAP;
     s_music.framer.generic.name     = ART_FRAMER;
     s_music.framer.generic.flags    = QMF_INACTIVE;
     s_music.framer.generic.x        = 376;
     s_music.framer.generic.y        = 46;
     s_music.framer.width            = 256;
     s_music.framer.height           = 334;
     s_music.arrows.generic.type     = MTYPE_BITMAP;
     s_music.arrows.generic.name     = ART_ARROWS;
     s_music.arrows.generic.flags    = QMF_INACTIVE;
     s_music.arrows.generic.x        = 315-ARROWS_WIDTH/2;
     s_music.arrows.generic.y        = 343;
     s_music.arrows.width            = ARROWS_WIDTH;
     s_music.arrows.height           = ARROWS_HEIGHT;
     s_music.left.generic.type       = MTYPE_BITMAP;
     s_music.left.generic.flags      = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     s_music.left.generic.x          = 315-ARROWS_WIDTH/2;
     s_music.left.generic.y          = 343;
     s_music.left.generic.id         = ID_LEFT;
     s_music.left.generic.callback   = Music_MenuEvent;
     s_music.left.width              = ARROWS_WIDTH/2;
     s_music.left.height             = ARROWS_HEIGHT;
     s_music.left.focuspic           = ART_ARROWLEFT;
     s_music.right.generic.type      = MTYPE_BITMAP;
     s_music.right.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     s_music.right.generic.x         = 315;
     s_music.right.generic.y         = 343;
     s_music.right.generic.id        = ID_RIGHT;
     s_music.right.generic.callback  = Music_MenuEvent;
     s_music.right.width             = ARROWS_WIDTH/2;
     s_music.right.height            = ARROWS_HEIGHT;
     s_music.right.focuspic          = ART_ARROWRIGHT;
     s_music.back.generic.type       = MTYPE_BITMAP;
     s_music.back.generic.name       = ART_BACK0;
     s_music.back.generic.flags      = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_music.back.generic.id         = ID_BACK;
     s_music.back.generic.callback   = Music_MenuEvent;
     s_music.back.generic.x          = 103;
     s_music.back.generic.y          = 330;
     s_music.back.width              = 128;
     s_music.back.height             = 64;
     s_music.back.focuspic           = ART_BACK1;
     s_music.go.generic.type         = MTYPE_BITMAP;
     s_music.go.generic.name         = ART_GO0;
     s_music.go.generic.flags        = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_music.go.generic.id           = ID_GO;
     s_music.go.generic.callback     = Music_MenuEvent;
     s_music.go.generic.x            = 541;
     s_music.go.generic.y            = 330;
     s_music.go.width                = 128;
     s_music.go.height               = 64;
     s_music.go.focuspic             = ART_GO1;
     s_music.list.generic.type       = MTYPE_SCROLLLIST;
     s_music.list.generic.flags      = QMF_PULSEIFFOCUS;
     s_music.list.generic.callback   = Music_MenuEvent;
     s_music.list.generic.id         = ID_LIST;
     s_music.list.generic.x          = 10;//118;
     s_music.list.generic.y          = 100;
     s_music.list.width              = 16;
     s_music.list.height             = 14;
     s_music.list.numitems           = trap_FS_GetFileList( "music", "ogg", s_music.names, NAMEBUFSIZE );
     s_music.list.itemnames          = (const char **)s_music.musiclist;
     s_music.list.columns            = 4;//3;
     if (!s_music.list.numitems) {
         strcpy( s_music.names, "No Music Found." );
         s_music.list.numitems = 1;
         //degenerate case, not selectable
         s_music.go.generic.flags |= (QMF_INACTIVE|QMF_HIDDEN);
     }
     else if (s_music.list.numitems > MAX_MUSIC)
         s_music.list.numitems = MAX_MUSIC;
     musicname = s_music.names;
     for ( i = 0; i < s_music.list.numitems; i++ ) {
         s_music.list.itemnames[i] = musicname;
         // strip extension
         len = strlen( musicname );
         if (!Q_stricmp(musicname +  len - 4,".ogg"))
             musicname[len-4] = '\0';
         Q_strupr(musicname);
         musicname += len + 1;
     }
     Menu_AddItem( &s_music.menu, &s_music.banner );
     Menu_AddItem( &s_music.menu, &s_music.framel );
     Menu_AddItem( &s_music.menu, &s_music.framer );
     Menu_AddItem( &s_music.menu, &s_music.list );
     Menu_AddItem( &s_music.menu, &s_music.arrows );
     Menu_AddItem( &s_music.menu, &s_music.left );
     Menu_AddItem( &s_music.menu, &s_music.right );
     Menu_AddItem( &s_music.menu, &s_music.back );
     Menu_AddItem( &s_music.menu, &s_music.go );
 }
References music_t::arrows, ARROWS_HEIGHT, ARROWS_WIDTH, ART_ARROWLEFT, ART_ARROWRIGHT, ART_ARROWS, ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, ART_GO0, ART_GO1, music_t::back, music_t::banner, menucommon_s::callback, menutext_s::color, color_white, menulist_s::columns, menucommon_s::flags, menubitmap_s::focuspic, music_t::framel, music_t::framer, menulist_s::generic, menubitmap_s::generic, menutext_s::generic, music_t::go, menulist_s::height, menubitmap_s::height, menucommon_s::id, ID_BACK, ID_GO, ID_LEFT, ID_LIST, ID_RIGHT, menulist_s::itemnames, music_t::left, music_t::list, MAX_MUSIC, music_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_SCROLLLIST, Music_Cache(), Music_MenuEvent(), music_t::musiclist, menucommon_s::name, NAMEBUFSIZE, music_t::names, menulist_s::numitems, Q_stricmp(), Q_strupr(), qfalse, QMF_HIDDEN, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_MOUSEONLY, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, qtrue, music_t::right, s_music, menutext_s::string, menutext_s::style, trap_FS_GetFileList(), menucommon_s::type, UI_CENTER, UI_DROPSHADOW, UI_MusicMenu_Key(), menulist_s::width, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by UI_MusicMenu().
UI_MusicMenu()
void UI_MusicMenu (void)
Definition at line 263 of file ui_music.c.
{
     Music_MenuInit();
     UI_PushMenu( &s_music.menu );
 }
References music_t::menu, Music_MenuInit(), s_music, and UI_PushMenu().
UI_MusicMenu_Key()
static sfxHandle_t UI_MusicMenu_Key (int key) static
Definition at line 94 of file ui_music.c.
{
     menucommon_s    *item;
     item = Menu_ItemAtCursor( &s_music.menu );
     return Menu_DefaultKey( &s_music.menu, key );
 }
References music_t::menu, Menu_DefaultKey(), Menu_ItemAtCursor(), and s_music.
Referenced by Music_MenuInit().
Variable Documentation
s_music
music_t s_music static
Definition at line 54 of file ui_music.c.
Referenced by Music_MenuEvent(), Music_MenuInit(), UI_MusicMenu(), and UI_MusicMenu_Key().