ZEQ2-Lite: Source/Engine/client/cl_scrn.c File Reference
cl_scrn.c File Reference
#include "client.h"
Functions
void SCR_AdjustFrom640 (float *x, float *y, float *w, float *h)
void SCR_DebugGraph (float value)
void SCR_DrawBigString (int x, int y, const char *s, float alpha, qboolean noColorEscape)
void SCR_DrawBigStringColor (int x, int y, const char *s, vec4_t color, qboolean noColorEscape)
static void SCR_DrawChar (int x, int y, float size, int ch)
void SCR_DrawCustomString (int spacing, int x, int y, const char *string)
void SCR_DrawDebugGraph (void)
void SCR_DrawDemoRecording (void)
void SCR_DrawNamedPic (float x, float y, float width, float height, const char *picname)
void SCR_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
void SCR_DrawScreenField (stereoFrame_t stereoFrame)
void SCR_DrawSmallChar (int x, int y, int ch)
void SCR_DrawSmallStringExt (int x, int y, const char *string, float *setColor, qboolean forceColor, qboolean noColorEscape)
void SCR_DrawStringExt (int x, int y, float size, const char *string, float *setColor, qboolean forceColor, qboolean noColorEscape)
void SCR_FillRect (float x, float y, float width, float height, const float *color)
int SCR_GetBigStringWidth (const char *str)
void SCR_Init (void)
static int SCR_Strlen (const char *str)
void SCR_UpdateScreen (void)
Variables
cvar_t * cl_debuggraph
cvar_t * cl_graphheight
cvar_t * cl_graphscale
cvar_t * cl_graphshift
cvar_t * cl_timegraph
static int current
qboolean scr_initialized
static float values [1024]
Function Documentation
SCR_AdjustFrom640()
void SCR_AdjustFrom640 (float * x, float * y, float * w, float * h)
Definition at line 59 of file cl_scrn.c.
{
     float   xscale;
     float   yscale;
 #if 0
         // adjust for wide screens
         if ( cls.glconfig.vidWidth * 480 > cls.glconfig.vidHeight * 640 ) {
             *x += 0.5 * ( cls.glconfig.vidWidth - ( cls.glconfig.vidHeight * 640 / 480 ) );
         }
 #endif
     // scale for screen sizes
     xscale = cls.glconfig.vidWidth / 640.0;
     yscale = cls.glconfig.vidHeight / 480.0;
     if ( x ) {
         *x *= xscale;
     }
     if ( y ) {
         *y *= yscale;
     }
     if ( w ) {
         *w *= xscale;
     }
     if ( h ) {
         *h *= yscale;
     }
 }
References cls, clientStatic_t::glconfig, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by CIN_DrawCinematic(), Con_DrawSolidConsole(), SCR_DrawChar(), SCR_DrawNamedPic(), SCR_DrawPic(), and SCR_FillRect().
SCR_DebugGraph()
void SCR_DebugGraph (float value)
Definition at line 446 of file cl_scrn.c.
 {
     values[current] = value;
     current = (current + 1) % ARRAY_LEN(values);
 }
References ARRAY_LEN, and current.
Referenced by CL_CreateCmd(), and CL_Frame().
SCR_DrawBigString()
void SCR_DrawBigString (int x, int y, const char * s, float alpha, qboolean noColorEscape)
Definition at line 284 of file cl_scrn.c.
{
     float   color[4];
     color[0] = color[1] = color[2] = 1.0;
     color[3] = alpha;
     SCR_DrawStringExt( x, y, BIGCHAR_WIDTH, s, color, qfalse, noColorEscape );
 }
References BIGCHAR_WIDTH, qfalse, and SCR_DrawStringExt().
Referenced by Field_CustomDraw(), and Field_VariableSizeDraw().
SCR_DrawBigStringColor()
void SCR_DrawBigStringColor (int x, int y, const char * s, vec4_t color, qboolean noColorEscape)
Definition at line 292 of file cl_scrn.c.
{
     SCR_DrawStringExt( x, y, BIGCHAR_WIDTH, s, color, qtrue, noColorEscape );
 }
References BIGCHAR_WIDTH, qtrue, and SCR_DrawStringExt().
SCR_DrawChar()
static void SCR_DrawChar (int x, int y, float size, int ch) static
Definition at line 122 of file cl_scrn.c.
{
     int row, col;
     float frow, fcol;
     float   ax, ay, aw, ah;
     ch &= 255;
     if ( ch == ' ' ) {
         return;
     }
     if ( y < -size ) {
         return;
     }
     ax = x;
     ay = y;
     aw = size;
     ah = size;
     SCR_AdjustFrom640( &ax, &ay, &aw, &ah );
     row = ch>>4;
     col = ch&15;
     frow = row*0.0625;
     fcol = col*0.0625;
     size = 0.0625;
     re.DrawStretchPic( ax, ay, aw, ah,
                        fcol, frow,
                        fcol + size, frow + size,
                        cls.charSetShader );
 }
References clientStatic_t::charSetShader, cls, refexport_t::DrawStretchPic, re, and SCR_AdjustFrom640().
Referenced by SCR_DrawCustomString(), and SCR_DrawStringExt().
SCR_DrawCustomString()
void SCR_DrawCustomString (int spacing, int x, int y, const char * string)
Definition at line 200 of file cl_scrn.c.
{
     vec4_t      color,shadow;
     const char  *s;
     int         xx;
     int size = 10;
     shadow[0] = shadow[1] = shadow[2] = 0;
     shadow[3] = 0.7;
     color[0] = color[1] = color[2] = color[3] = 1.0;
     re.SetColor(shadow);
     s = string;
     xx = x;
     while ( *s ) {
         if (Q_IsColorString( s ) ) {
             s += 2;
             continue;
         }
         SCR_DrawChar( xx+1, y+1, size, *s );
         xx += spacing;
         s++;
     }
     // draw the colored text
     s = string;
     xx = x;
     re.SetColor(color );
     while ( *s ) {
         if (Q_IsColorString( s ) ) {
             Com_Memcpy(shadow, g_color_table[ColorIndex(*(s+1))], sizeof( shadow ) );
             shadow[3] = 0.7;
             re.SetColor(shadow);
             s += 2;
             continue;
         }
         SCR_DrawChar( xx, y, size, *s );
         xx += spacing;
         s++;
     }
     re.SetColor(NULL);
 }
References ColorIndex, Com_Memcpy, g_color_table, NULL, Q_IsColorString, re, SCR_DrawChar(), refexport_t::SetColor, and xx.
Referenced by Con_DrawNotify(), and Field_CustomDraw().
SCR_DrawDebugGraph()
void SCR_DrawDebugGraph (void)
Definition at line 457 of file cl_scrn.c.
 {
     int     a, x, y, w, i, h;
     float   v;
     //
     // draw the graph
     //
     w = cls.glconfig.vidWidth;
     x = 0;
     y = cls.glconfig.vidHeight;
     re.SetColor( g_color_table[0] );
     re.DrawStretchPic(x, y - cl_graphheight->integer,
         w, cl_graphheight->integer, 0, 0, 0, 0, cls.whiteShader );
     re.SetColor( NULL );
     for (a=0 ; a<w ; a++)
     {
         i = (ARRAY_LEN(values)+current-1-(a % ARRAY_LEN(values))) % ARRAY_LEN(values);
         v = values[i];
         v = v * cl_graphscale->integer + cl_graphshift->integer;
         if (v < 0)
             v += cl_graphheight->integer * (1+(int)(-v / cl_graphheight->integer));
         h = (int)v % cl_graphheight->integer;
         re.DrawStretchPic( x+w-1-a, y - h, 1, h, 0, 0, 0, 0, cls.whiteShader );
     }
 }
References ARRAY_LEN, cl_graphheight, cl_graphscale, cl_graphshift, cls, current, refexport_t::DrawStretchPic, g_color_table, clientStatic_t::glconfig, int(), NULL, re, refexport_t::SetColor, glconfig_t::vidHeight, glconfig_t::vidWidth, and clientStatic_t::whiteShader.
Referenced by SCR_DrawScreenField().
SCR_DrawDemoRecording()
void SCR_DrawDemoRecording (void)
Definition at line 370 of file cl_scrn.c.
{
     char    string[1024];
     int     pos;
     if ( !clc.demorecording ) {
         return;
     }
     if ( clc.spDemoRecording ) {
         return;
     }
     pos = FS_FTell( clc.demofile );
     sprintf( string, "RECORDING %s: %ik", clc.demoName, pos / 1024 );
     SCR_DrawStringExt( 320 - strlen( string ) * 4, 20, 8, string, g_color_table[7], qtrue, qfalse );
 }
References clc, clientConnection_t::demofile, clientConnection_t::demoName, clientConnection_t::demorecording, FS_FTell(), g_color_table, qfalse, qtrue, SCR_DrawStringExt(), and clientConnection_t::spDemoRecording.
Referenced by SCR_DrawScreenField().
SCR_DrawNamedPic()
void SCR_DrawNamedPic (float x, float y, float width, float height, const char * picname)
Definition at line 41 of file cl_scrn.c.
{
     qhandle_t   hShader;
     assert( width != 0 );
     hShader = re.RegisterShader( picname );
     SCR_AdjustFrom640( &x, &y, &width, &height );
     re.DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
References refexport_t::DrawStretchPic, re, refexport_t::RegisterShader, and SCR_AdjustFrom640().
SCR_DrawPic()
void SCR_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
Definition at line 111 of file cl_scrn.c.
{
     SCR_AdjustFrom640( &x, &y, &width, &height );
     re.DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
References refexport_t::DrawStretchPic, re, and SCR_AdjustFrom640().
Referenced by Con_DrawNotify(), and Con_DrawSolidConsole().
SCR_DrawScreenField()
void SCR_DrawScreenField (stereoFrame_t stereoFrame)
Definition at line 513 of file cl_scrn.c.
{
     qboolean uiFullscreen;
     re.BeginFrame( stereoFrame );
     uiFullscreen = (uivm && VM_Call( uivm, UI_IS_FULLSCREEN ));
     // wide aspect ratio screens need to have the sides cleared
     // unless they are displaying game renderings
     if ( uiFullscreen || (clc.state != CA_ACTIVE && clc.state != CA_CINEMATIC) ) {
         if ( cls.glconfig.vidWidth * 480 > cls.glconfig.vidHeight * 640 ) {
             re.SetColor( g_color_table[0] );
             re.DrawStretchPic( 0, 0, cls.glconfig.vidWidth, cls.glconfig.vidHeight, 0, 0, 0, 0, cls.whiteShader );
             re.SetColor( NULL );
         }
     }
     // if the menu is going to cover the entire screen, we
     // don't need to render anything under it
     if ( uivm && !uiFullscreen ) {
         switch( clc.state ) {
         default:
             Com_Error( ERR_FATAL, "SCR_DrawScreenField: bad clc.state" );
             break;
         case CA_CINEMATIC:
             SCR_DrawCinematic();
             break;
         case CA_DISCONNECTED:
             // force menu up
             S_StopAllSounds();
             VM_Call( uivm, UI_SET_ACTIVE_MENU, UIMENU_MAIN );
             break;
         case CA_CONNECTING:
         case CA_CHALLENGING:
         case CA_CONNECTED:
             // connecting clients will only show the connection dialog
             // refresh to update the time
             VM_Call( uivm, UI_REFRESH, cls.realtime );
             VM_Call( uivm, UI_DRAW_CONNECT_SCREEN, qfalse );
             break;
         case CA_LOADING:
         case CA_PRIMED:
             // draw the game information screen and loading progress
             CL_CGameRendering(stereoFrame);
             // also draw the connection information, so it doesn't
             // flash away too briefly on local or lan games
             // refresh to update the time
             VM_Call( uivm, UI_REFRESH, cls.realtime );
             VM_Call( uivm, UI_DRAW_CONNECT_SCREEN, qtrue );
             break;
         case CA_ACTIVE:
             // always supply STEREO_CENTER as vieworg offset is now done by the engine.
             CL_CGameRendering(stereoFrame);
             SCR_DrawDemoRecording();
 #ifdef USE_VOIP
             SCR_DrawVoipMeter();
 #endif
             break;
         }
     }
     // the menu draws next
     if ( Key_GetCatcher( ) & KEYCATCH_UI && uivm ) {
         VM_Call( uivm, UI_REFRESH, cls.realtime );
     }
     // console draws next
     Con_DrawConsole ();
     // debug graph can be drawn on top of anything
     if ( cl_debuggraph->integer || cl_timegraph->integer || cl_debugMove->integer ) {
         SCR_DrawDebugGraph ();
     }
 }
References refexport_t::BeginFrame, CA_ACTIVE, CA_CHALLENGING, CA_CINEMATIC, CA_CONNECTED, CA_CONNECTING, CA_DISCONNECTED, CA_LOADING, CA_PRIMED, CL_CGameRendering(), cl_debuggraph, cl_debugMove, cl_timegraph, clc, cls, Com_Error(), Con_DrawConsole(), refexport_t::DrawStretchPic, ERR_FATAL, g_color_table, clientStatic_t::glconfig, Key_GetCatcher(), KEYCATCH_UI, NULL, qfalse, qtrue, re, clientStatic_t::realtime, S_StopAllSounds(), SCR_DrawCinematic(), SCR_DrawDebugGraph(), SCR_DrawDemoRecording(), refexport_t::SetColor, clientConnection_t::state, UI_DRAW_CONNECT_SCREEN, UI_IS_FULLSCREEN, UI_REFRESH, UI_SET_ACTIVE_MENU, UIMENU_MAIN, uivm, glconfig_t::vidHeight, glconfig_t::vidWidth, VM_Call(), and clientStatic_t::whiteShader.
Referenced by SCR_UpdateScreen().
SCR_DrawSmallChar()
void SCR_DrawSmallChar (int x, int y, int ch)
Definition at line 160 of file cl_scrn.c.
{
     int row, col;
     float frow, fcol;
     float size;
     ch &= 255;
     if ( ch == ' ' ) {
         return;
     }
     if ( y < -SMALLCHAR_HEIGHT ) {
         return;
     }
     row = ch>>4;
     col = ch&15;
     frow = row*0.0625;
     fcol = col*0.0625;
     size = 0.0625;
     re.DrawStretchPic( x, y, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT,
                        fcol, frow,
                        fcol + size, frow + size,
                        cls.charSetShader );
 }
References clientStatic_t::charSetShader, cls, refexport_t::DrawStretchPic, re, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by Con_DrawInput(), Con_DrawSolidConsole(), Field_VariableSizeDraw(), and SCR_DrawSmallStringExt().
SCR_DrawSmallStringExt()
void SCR_DrawSmallStringExt (int x, int y, const char * string, float * setColor, qboolean forceColor, qboolean noColorEscape)
Definition at line 305 of file cl_scrn.c.
{
     vec4_t      color;
     const char  *s;
     int         xx;
     // draw the colored text
     s = string;
     xx = x;
     re.SetColor( setColor );
     while ( *s ) {
         if ( Q_IsColorString( s ) ) {
             if ( !forceColor ) {
                 Com_Memcpy( color, g_color_table[ColorIndex(*(s+1))], sizeof( color ) );
                 color[3] = setColor[3];
                 re.SetColor( color );
             }
             if ( !noColorEscape ) {
                 s += 2;
                 continue;
             }
         }
         SCR_DrawSmallChar( xx, y, *s );
         xx += SMALLCHAR_WIDTH;
         s++;
     }
     re.SetColor( NULL );
 }
References ColorIndex, Com_Memcpy, g_color_table, NULL, Q_IsColorString, re, SCR_DrawSmallChar(), refexport_t::SetColor, SMALLCHAR_WIDTH, and xx.
Referenced by Field_VariableSizeDraw().
SCR_DrawStringExt()
void SCR_DrawStringExt (int x, int y, float size, const char * string, float * setColor, qboolean forceColor, qboolean noColorEscape)
Definition at line 239 of file cl_scrn.c.
{
     vec4_t      color;
     const char  *s;
     int         xx;
     // draw the drop shadow
     color[0] = color[1] = color[2] = 0;
     color[3] = 0.7;
     re.SetColor( color );
     s = string;
     xx = x;
     while ( *s ) {
         if ( !noColorEscape && Q_IsColorString( s ) ) {
             s += 2;
             continue;
         }
         SCR_DrawChar( xx+2, y+2, size, *s );
         xx += size;
         s++;
     }
     // draw the colored text
     s = string;
     xx = x;
     re.SetColor( setColor );
     while ( *s ) {
         if ( !noColorEscape && Q_IsColorString( s ) ) {
             if ( !forceColor ) {
                 Com_Memcpy( color, g_color_table[ColorIndex(*(s+1))], sizeof( color ) );
                 color[3] = setColor[3];
                 re.SetColor( color );
             }
             s += 2;
             continue;
         }
         SCR_DrawChar( xx, y, size, *s );
         xx += size;
         s++;
     }
     re.SetColor( NULL );
 }
References ColorIndex, Com_Memcpy, g_color_table, NULL, Q_IsColorString, re, SCR_DrawChar(), refexport_t::SetColor, and xx.
Referenced by SCR_DrawBigString(), SCR_DrawBigStringColor(), and SCR_DrawDemoRecording().
SCR_FillRect()
void SCR_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 94 of file cl_scrn.c.
{
     re.SetColor( color );
     SCR_AdjustFrom640( &x, &y, &width, &height );
     re.DrawStretchPic( x, y, width, height, 0, 0, 0, 0, cls.whiteShader );
     re.SetColor( NULL );
 }
References cls, refexport_t::DrawStretchPic, NULL, re, SCR_AdjustFrom640(), refexport_t::SetColor, and clientStatic_t::whiteShader.
Referenced by Con_DrawSolidConsole().
SCR_GetBigStringWidth()
int SCR_GetBigStringWidth (const char * str)
Definition at line 358 of file cl_scrn.c.
{
     return SCR_Strlen( str ) * BIGCHAR_WIDTH;
 }
References BIGCHAR_WIDTH, and SCR_Strlen().
SCR_Init()
void SCR_Init (void)
Definition at line 493 of file cl_scrn.c.
                       {
     cl_timegraph = Cvar_Get ("timegraph", "0", CVAR_CHEAT);
     cl_debuggraph = Cvar_Get ("debuggraph", "0", CVAR_CHEAT);
     cl_graphheight = Cvar_Get ("graphheight", "32", CVAR_CHEAT);
     cl_graphscale = Cvar_Get ("graphscale", "1", CVAR_CHEAT);
     cl_graphshift = Cvar_Get ("graphshift", "0", CVAR_CHEAT);
     scr_initialized = qtrue;
 }
References cl_debuggraph, cl_graphheight, cl_graphscale, cl_graphshift, cl_timegraph, CVAR_CHEAT, Cvar_Get(), qtrue, and scr_initialized.
Referenced by CL_Init().
SCR_Strlen()
static int SCR_Strlen (const char * str) static
Definition at line 339 of file cl_scrn.c.
{
     const char *s = str;
     int count = 0;
     while ( *s ) {
         if ( Q_IsColorString( s ) ) {
             s += 2;
         } else {
             count++;
             s++;
         }
     }
     return count;
 }
References Q_IsColorString.
Referenced by SCR_GetBigStringWidth().
SCR_UpdateScreen()
void SCR_UpdateScreen (void)
Definition at line 597 of file cl_scrn.c.
{
     static int  recursive;
     if ( !scr_initialized ) {
         return;             // not initialized yet
     }
     if ( ++recursive > 2 ) {
         Com_Error( ERR_FATAL, "SCR_UpdateScreen: recursively called" );
     }
     recursive = 1;
     // If there is no VM, there are also no rendering commands issued. Stop the renderer in
     // that case.
     if( uivm || com_dedicated->integer )
     {
         // XXX
         int in_anaglyphMode = Cvar_VariableIntegerValue("r_anaglyphMode");
         // if running in stereo, we need to draw the frame twice
         if ( cls.glconfig.stereoEnabled || in_anaglyphMode) {
             SCR_DrawScreenField( STEREO_LEFT );
             SCR_DrawScreenField( STEREO_RIGHT );
         } else {
             SCR_DrawScreenField( STEREO_CENTER );
         }
         if ( com_speeds->integer ) {
             re.EndFrame( &time_frontend, &time_backend );
         } else {
             re.EndFrame( NULL, NULL );
         }
     }
     recursive = 0;
 }
References cls, com_dedicated, Com_Error(), com_speeds, Cvar_VariableIntegerValue(), refexport_t::EndFrame, ERR_FATAL, clientStatic_t::glconfig, NULL, re, SCR_DrawScreenField(), scr_initialized, STEREO_CENTER, STEREO_LEFT, STEREO_RIGHT, glconfig_t::stereoEnabled, time_backend, time_frontend, and uivm.
Referenced by CL_CgameSystemCalls(), CL_Disconnect(), CL_Frame(), CL_MapLoading(), CL_UISystemCalls(), and Console_Key().
Variable Documentation
cl_debuggraph
cvar_t* cl_debuggraph
Definition at line 29 of file cl_scrn.c.
Referenced by SCR_DrawScreenField(), and SCR_Init().
cl_graphheight
cvar_t* cl_graphheight
Definition at line 30 of file cl_scrn.c.
Referenced by SCR_DrawDebugGraph(), and SCR_Init().
cl_graphscale
cvar_t* cl_graphscale
Definition at line 31 of file cl_scrn.c.
Referenced by SCR_DrawDebugGraph(), and SCR_Init().
cl_graphshift
cvar_t* cl_graphshift
Definition at line 32 of file cl_scrn.c.
Referenced by SCR_DrawDebugGraph(), and SCR_Init().
cl_timegraph
cvar_t* cl_timegraph
Definition at line 28 of file cl_scrn.c.
Referenced by CL_Frame(), SCR_DrawScreenField(), and SCR_Init().
current
int current static
Definition at line 438 of file cl_scrn.c.
Referenced by CG_Draw2D_f(), CG_DrawScripted2D(), CG_InterpolateEntityPosition(), CG_PredictPlayerState(), Menu_Common(), PM_CheckSequences(), PM_CheckSpecificSequences(), SCR_DebugGraph(), and SCR_DrawDebugGraph().
scr_initialized
qboolean scr_initialized
Definition at line 26 of file cl_scrn.c.
Referenced by SCR_Init(), and SCR_UpdateScreen().
values
float values[1024] static
Definition at line 439 of file cl_scrn.c.