ZEQ2-Lite: Source/Engine/zlib/zutil.c File Reference
zutil.c File Reference
#include "zutil.h"
Data Structures
struct internal_state
Functions
voidp calloc OF ((uInt items, uInt size))
voidp malloc OF ((uInt size))
void free OF ((voidpf ptr))
voidpf zcalloc (voidpf opaque, unsigned items, unsigned size)
void zcfree (voidpf opaque, voidpf ptr)
const char *ZEXPORT zError (int err)
uLong ZEXPORT zlibCompileFlags ()
const char *ZEXPORT zlibVersion ()
int zmemcmp (Bytef *s1, const Bytef *s2, uInt len) const
void zmemcpy (Bytef *dest, const Bytef *source, uInt len)
void zmemzero (Bytef *dest, uInt len)
Variables
const char *const z_errmsg [10]
Function Documentation
OF() [1/3]
voidp calloc OF ((uInt items, uInt size))
OF() [2/3]
voidp malloc OF ((uInt size))
OF() [3/3]
void free OF ((voidpf ptr))
zcalloc()
voidpf zcalloc (voidpf opaque, unsigned items, unsigned size)
Definition at line 300 of file zutil.c.
 {
     if (opaque) items += size - size; /* make compiler happy */
     return sizeof(uInt) > 2 ? (voidpf)malloc(items * size) :
                               (voidpf)calloc(items, size);
 }
Referenced by inflateInit2_().
zcfree()
void zcfree (voidpf opaque, voidpf ptr)
Definition at line 310 of file zutil.c.
 {
     free(ptr);
     if (opaque) return; /* make compiler happy */
 }
References ptr().
Referenced by inflateInit2_().
zError()
const char* ZEXPORT zError (int err)
Definition at line 133 of file zutil.c.
 {
     return ERR_MSG(err);
 }
References ERR_MSG.
zlibCompileFlags()
uLong ZEXPORT zlibCompileFlags ()
Definition at line 32 of file zutil.c.
 {
     uLong flags;
     flags = 0;
     switch (sizeof(uInt)) {
     case 2:     break;
     case 4:     flags += 1;     break;
     case 8:     flags += 2;     break;
     default:    flags += 3;
     }
     switch (sizeof(uLong)) {
     case 2:     break;
     case 4:     flags += 1 << 2;        break;
     case 8:     flags += 2 << 2;        break;
     default:    flags += 3 << 2;
     }
     switch (sizeof(voidpf)) {
     case 2:     break;
     case 4:     flags += 1 << 4;        break;
     case 8:     flags += 2 << 4;        break;
     default:    flags += 3 << 4;
     }
     switch (sizeof(z_off_t)) {
     case 2:     break;
     case 4:     flags += 1 << 6;        break;
     case 8:     flags += 2 << 6;        break;
     default:    flags += 3 << 6;
     }
 #ifdef DEBUG
     flags += 1 << 8;
 #endif
 #if defined(ASMV) || defined(ASMINF)
     flags += 1 << 9;
 #endif
 #ifdef ZLIB_WINAPI
     flags += 1 << 10;
 #endif
 #ifdef BUILDFIXED
     flags += 1 << 12;
 #endif
 #ifdef DYNAMIC_CRC_TABLE
     flags += 1 << 13;
 #endif
 #ifdef NO_GZCOMPRESS
     flags += 1L << 16;
 #endif
 #ifdef NO_GZIP
     flags += 1L << 17;
 #endif
 #ifdef PKZIP_BUG_WORKAROUND
     flags += 1L << 20;
 #endif
 #ifdef FASTEST
     flags += 1L << 21;
 #endif
 #ifdef STDC
 #  ifdef NO_vsnprintf
         flags += 1L << 25;
 #    ifdef HAS_vsprintf_void
         flags += 1L << 26;
 #    endif
 #  else
 #    ifdef HAS_vsnprintf_void
         flags += 1L << 26;
 #    endif
 #  endif
 #else
         flags += 1L << 24;
 #  ifdef NO_snprintf
         flags += 1L << 25;
 #    ifdef HAS_sprintf_void
         flags += 1L << 26;
 #    endif
 #  else
 #    ifdef HAS_snprintf_void
         flags += 1L << 26;
 #    endif
 #  endif
 #endif
     return flags;
 }
References z_off_t.
zlibVersion()
const char* ZEXPORT zlibVersion ()
Definition at line 27 of file zutil.c.
 {
     return ZLIB_VERSION;
 }
References ZLIB_VERSION.
zmemcmp()
int zmemcmp (Bytef* s1, const Bytef* s2, uInt len) const
Definition at line 160 of file zutil.c.
 {
     uInt j;
     for (j = 0; j < len; j++) {
         if (s1[j] != s2[j]) return 2*(s1[j] > s2[j])-1;
     }
     return 0;
 }
zmemcpy()
void zmemcpy (Bytef* dest, const Bytef* source, uInt len)
Definition at line 149 of file zutil.c.
 {
     if (len == 0) return;
     do {
         *dest++ = *source++; /* ??? to be unrolled */
     } while (--len != 0);
 }
Referenced by inflate(), inflateCopy(), inflateSetDictionary(), and updatewindow().
zmemzero()
void zmemzero (Bytef* dest, uInt len)
Definition at line 173 of file zutil.c.
 {
     if (len == 0) return;
     do {
         *dest++ = 0;  /* ??? to be unrolled */
     } while (--len != 0);
 }
Variable Documentation
z_errmsg
const char* const z_errmsg[10]
Initial value:
= {
"need dictionary",
"stream end",
"",
"file error",
"stream error",
"data error",
"insufficient memory",
"buffer error",
"incompatible version",
""}
Definition at line 14 of file zutil.c.