name: SVN Update
on:
  schedule:
    - cron: '0 10 1 */4 *' # quarterly
  push:
    branches:
      - "*"

jobs:
  svn-update:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install subversion git gh jq # openssl

    - name: Checkout ZEQ2-Lite SVN
      working-directory: ${{github.workspace}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        git clone --single-branch --depth 1 https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/LegendaryGuard/ZEQ2-Lite.git
        cd ZEQ2-Lite
        # ls -l
        if [ -d Source ]; then rm -r Source; fi
        # ls -l
        svn checkout https://zeq2.com/SVN/Source/ Source
        git config --global user.name "GitHub CI SVN Updates"
        git config --global user.email "<>"
        sudo chmod 777 svn_update.sh
        ./svn_update.sh
        # openssl rand -base64 12 > HASH
