ZEQ2-Lite: Tools/MinGW/include/c++/4.6.1/i686-pc-mingw32/bits/basic_file.h File Reference
basic_file.h File Reference
#include <bits/c++config.h>
#include <bits/c++io.h>
#include <ios>
Functions
namespace std _GLIBCXX_VISIBILITY (default)
Detailed Description
This is an internal header file, included by other library headers. Do not attempt to use it directly. @headername{ios}
Definition in file basic_file.h.
Function Documentation
_GLIBCXX_VISIBILITY()
namespace std _GLIBCXX_VISIBILITY (default)
Definition at line 44 of file basic_file.h.
 {
 _GLIBCXX_BEGIN_NAMESPACE_VERSION
   // Generic declaration.
   template<typename _CharT>
     class __basic_file;
   // Specialization.
   template<>
     class __basic_file<char>
     {
       // Underlying data source/sink.
       __c_file*     _M_cfile;
       // True iff we opened _M_cfile, and thus must close it ourselves.
       bool      _M_cfile_created;
     public:
       __basic_file(__c_lock* __lock = 0) throw ();
       __basic_file*
       open(const char* __name, ios_base::openmode __mode, int __prot = 0664);
       __basic_file*
       sys_open(__c_file* __file, ios_base::openmode);
       __basic_file*
       sys_open(int __fd, ios_base::openmode __mode) throw ();
       __basic_file*
       close();
       _GLIBCXX_PURE bool
       is_open() const throw ();
       _GLIBCXX_PURE int
       fd() throw ();
       _GLIBCXX_PURE __c_file*
       file() throw ();
       ~__basic_file();
       streamsize
       xsputn(const char* __s, streamsize __n);
       streamsize
       xsputn_2(const char* __s1, streamsize __n1,
            const char* __s2, streamsize __n2);
       streamsize
       xsgetn(char* __s, streamsize __n);
       streamoff
       seekoff(streamoff __off, ios_base::seekdir __way) throw ();
       int
       sync();
       streamsize
       showmanyc();
     };
 _GLIBCXX_END_NAMESPACE_VERSION
 } // namespace
References _GLIBCXX_PURE, close(), file, open(), and seekdir().