ZEQ2-Lite: Tools/MinGW/include/amvideo.h File Reference
amvideo.h File Reference
#include <ddraw.h>
#include <strmif.h>
Data Structures
struct _AM_FRAMESTEP_STEP
struct tag_TRUECOLORINFO
struct tagAnalogVideoInfo
struct tagMPEG1VIDEOINFO
struct tagVIDEOINFO
struct tagVIDEOINFOHEADER
Macros
#define AMDDS_ ALL 0x00FF
#define AMDDS_DCIPS 0x0001
#define AMDDS_DEFAULT 0x00FF
#define AMDDS_NONE 0x0000
#define AMDDS_PRIMARY (AMDDS_DCIPS|AMDDS_PS)
#define AMDDS_PS 0x0002
#define AMDDS_RGB (AMDDS_RGBOFF|AMDDS_RGBOVR|AMDDS_RGBFLP)
#define AMDDS_RGBFLP 0x0040
#define AMDDS_RGBOFF 0x0010
#define AMDDS_RGBOVR 0x0004
#define AMDDS_YUV (AMDDS_YUVOFF|AMDDS_YUVOVR|AMDDS_YUVFLP)
#define AMDDS_YUVFLP 0x0080
#define AMDDS_YUVOFF 0x0020
#define AMDDS_YUVOVR 0x0008
#define BIT_MASKS_MATCH(pbmi1, pbmi2) ((pbmi1)->dwBitMasks[0] == (pbmi2)->dwBitMasks[0] && (pbmi1)->dwBitMasks[1] == (pbmi2)->dwBitMasks[1] && (pbmi1)->dwBitMasks[2] == (pbmi2)->dwBitMasks[2])
#define INTERFACE IDirectDrawVideo
#define INTERFACE IQualProp
#define INTERFACE IFullScreenVideo
#define INTERFACE IFullScreenVideoEx
#define PALETTE_ENTRIES(pbmi) (1 << (pbmi)->bmiHeader.biBitCount)
#define PALETTISED(pbmi) ((pbmi)->bmiHeader.biBitCount <= 8)
#define RESET_MASKS(pbmi) (ZeroMemory((PVOID)(pbmi)->dwBitFields,3*sizeof(DWORD)))
#define RESET_PALETTE(pbmi) (ZeroMemory((PVOID)(pbmi)->bmiColors,256*sizeof(RGBQUAD)));
#define SIZE_EGA_PALETTE (16*sizeof(RGBQUAD))
#define SIZE_MASKS (3*sizeof(DWORD))
#define SIZE_PALETTE (256*sizeof(RGBQUAD))
Enumerations
enum AM_PROPERTY_FRAMESTEP { AM_PROPERTY_FRAMESTEP_STEP = 1, AM_PROPERTY_FRAMESTEP_CANCEL = 2, AM_PROPERTY_FRAMESTEP_CANSTEP = 3, AM_PROPERTY_FRAMESTEP_CANSTEPMULTIPLE = 4 }
Functions
DECLARE_INTERFACE_ (IDirectDrawVideo, IUnknown)
DECLARE_INTERFACE_ (IFullScreenVideo, IUnknown)
DECLARE_INTERFACE_ (IFullScreenVideoEx, IFullScreenVideo)
DECLARE_INTERFACE_ (IQualProp, IUnknown)
Macro Definition Documentation
AMDDS_
#define AMDDS_ ALL 0x00FF
Definition at line 23 of file amvideo.h.
AMDDS_DCIPS
#define AMDDS_DCIPS 0x0001
Definition at line 15 of file amvideo.h.
AMDDS_DEFAULT
#define AMDDS_DEFAULT 0x00FF
Definition at line 24 of file amvideo.h.
AMDDS_NONE
#define AMDDS_NONE 0x0000
Definition at line 14 of file amvideo.h.
AMDDS_PRIMARY
#define AMDDS_PRIMARY (AMDDS_DCIPS|AMDDS_PS)
Definition at line 27 of file amvideo.h.
AMDDS_PS
#define AMDDS_PS 0x0002
Definition at line 16 of file amvideo.h.
AMDDS_RGB
#define AMDDS_RGB (AMDDS_RGBOFF|AMDDS_RGBOVR|AMDDS_RGBFLP)
Definition at line 26 of file amvideo.h.
AMDDS_RGBFLP
#define AMDDS_RGBFLP 0x0040
Definition at line 21 of file amvideo.h.
AMDDS_RGBOFF
#define AMDDS_RGBOFF 0x0010
Definition at line 19 of file amvideo.h.
AMDDS_RGBOVR
#define AMDDS_RGBOVR 0x0004
Definition at line 17 of file amvideo.h.
AMDDS_YUV
#define AMDDS_YUV (AMDDS_YUVOFF|AMDDS_YUVOVR|AMDDS_YUVFLP)
Definition at line 25 of file amvideo.h.
AMDDS_YUVFLP
#define AMDDS_YUVFLP 0x0080
Definition at line 22 of file amvideo.h.
AMDDS_YUVOFF
#define AMDDS_YUVOFF 0x0020
Definition at line 20 of file amvideo.h.
AMDDS_YUVOVR
#define AMDDS_YUVOVR 0x0008
Definition at line 18 of file amvideo.h.
BIT_MASKS_MATCH
#define BIT_MASKS_MATCH (pbmi1, pbmi2) ((pbmi1)->dwBitMasks[0] == (pbmi2)->dwBitMasks[0] && (pbmi1)->dwBitMasks[1] == (pbmi2)->dwBitMasks[1] && (pbmi1)->dwBitMasks[2] == (pbmi2)->dwBitMasks[2])
Definition at line 28 of file amvideo.h.
INTERFACE [1/4]
#define INTERFACE IDirectDrawVideo
Definition at line 146 of file amvideo.h.
INTERFACE [2/4]
#define INTERFACE IQualProp
Definition at line 146 of file amvideo.h.
INTERFACE [3/4]
#define INTERFACE IFullScreenVideo
Definition at line 146 of file amvideo.h.
INTERFACE [4/4]
#define INTERFACE IFullScreenVideoEx
Definition at line 146 of file amvideo.h.
PALETTE_ENTRIES
#define PALETTE_ENTRIES (pbmi) (1 << (pbmi)->bmiHeader.biBitCount)
Definition at line 30 of file amvideo.h.
PALETTISED
#define PALETTISED (pbmi) ((pbmi)->bmiHeader.biBitCount <= 8)
Definition at line 29 of file amvideo.h.
RESET_MASKS
#define RESET_MASKS (pbmi) (ZeroMemory((PVOID)(pbmi)->dwBitFields,3*sizeof(DWORD)))
Definition at line 31 of file amvideo.h.
RESET_PALETTE
#define RESET_PALETTE (pbmi) (ZeroMemory((PVOID)(pbmi)->bmiColors,256*sizeof(RGBQUAD)));
Definition at line 32 of file amvideo.h.
SIZE_EGA_PALETTE
#define SIZE_EGA_PALETTE (16*sizeof(RGBQUAD))
Definition at line 33 of file amvideo.h.
SIZE_MASKS
#define SIZE_MASKS (3*sizeof(DWORD))
Definition at line 34 of file amvideo.h.
SIZE_PALETTE
#define SIZE_PALETTE (256*sizeof(RGBQUAD))
Definition at line 35 of file amvideo.h.
Enumeration Type Documentation
AM_PROPERTY_FRAMESTEP
enum AM_PROPERTY_FRAMESTEP
Enumerator
AM_PROPERTY_FRAMESTEP_STEP
AM_PROPERTY_FRAMESTEP_CANCEL
AM_PROPERTY_FRAMESTEP_CANSTEP
AM_PROPERTY_FRAMESTEP_CANSTEPMULTIPLE
Definition at line 36 of file amvideo.h.
              {
     AM_PROPERTY_FRAMESTEP_STEP = 1,
     AM_PROPERTY_FRAMESTEP_CANCEL = 2,
     AM_PROPERTY_FRAMESTEP_CANSTEP = 3,
     AM_PROPERTY_FRAMESTEP_CANSTEPMULTIPLE = 4
 } AM_PROPERTY_FRAMESTEP;
Function Documentation
DECLARE_INTERFACE_() [1/4]
DECLARE_INTERFACE_ (IDirectDrawVideo , IUnknown)
Definition at line 84 of file amvideo.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,LPVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(CanUseOverlayStretch)(THIS_ long*) PURE;
     STDMETHOD(CanUseScanLine)(THIS_ long*) PURE;
     STDMETHOD(GetCaps)(THIS_ DDCAPS*) PURE;
     STDMETHOD(GetDirectDraw)(THIS_ LPDIRECTDRAW*) PURE;
     STDMETHOD(GetEmulatedCaps)(THIS_ DDCAPS*) PURE;
     STDMETHOD(GetFourCCCodes)(THIS_ DWORD*,DWORD*) PURE;
     STDMETHOD(GetSurfaceDesc)(THIS_ DDSURFACEDESC*) PURE;
     STDMETHOD(GetSurfaceType)(THIS_ DWORD*) PURE;
     STDMETHOD(GetSwitches)(THIS_ DWORD*) PURE;
     STDMETHOD(SetDefault)(THIS) PURE;
     STDMETHOD(SetDirectDraw)(THIS_ LPDIRECTDRAW) PURE;
     STDMETHOD(SetSwitches)(THIS_ DWORD) PURE;
     STDMETHOD(UseOverlayStretch)(THIS_ long) PURE;
     STDMETHOD(UseScanLine)(THIS_ long) PURE;
     STDMETHOD(UseWhenFullScreen)(THIS_ long) PURE;
     STDMETHOD(WillUseFullScreen)(THIS_ long*) PURE;
 };
References long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [2/4]
DECLARE_INTERFACE_ (IFullScreenVideo , IUnknown)
Definition at line 122 of file amvideo.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,LPVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(CountModes)(THIS_ long*) PURE;
     STDMETHOD(GetCaption)(THIS_ BSTR*) PURE;
     STDMETHOD(GetClipFactor)(THIS_ long*) PURE;
     STDMETHOD(GetCurrentMode)(THIS_ long*) PURE;
     STDMETHOD(GetMessageDrain)(THIS_ HWND*) PURE;
     STDMETHOD(GetModeInfo)(THIS_ long,long*,long*,long*) PURE;
     STDMETHOD(GetMonitor)(THIS_ long*) PURE;
     STDMETHOD(HideOnDeactivate)(THIS_ long) PURE;
     STDMETHOD(IsHideOnDeactivate)(THIS) PURE;
     STDMETHOD(IsModeAvailable)(THIS_ long) PURE;
     STDMETHOD(IsModeEnabled)(THIS_ long) PURE;
     STDMETHOD(SetCaption)(THIS_ BSTR) PURE;
     STDMETHOD(SetClipFactor)(THIS_ long) PURE;
     STDMETHOD(SetDefault)(THIS) PURE;
     STDMETHOD(SetEnabled)(THIS_ long,long) PURE;
     STDMETHOD(SetMessageDrain)(THIS_ HWND) PURE;
     STDMETHOD(SetMonitor)(THIS_ long) PURE;
 };
References HWND, long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [3/4]
DECLARE_INTERFACE_ (IFullScreenVideoEx , IFullScreenVideo)
Definition at line 147 of file amvideo.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID, LPVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(CountModes)(THIS_ long*) PURE;
     STDMETHOD(GetAcceleratorTable)(THIS_ HWND*,HACCEL*) PURE;
     STDMETHOD(GetCaption)(THIS_ BSTR*) PURE;
     STDMETHOD(GetClipFactor)(THIS_ long*) PURE;
     STDMETHOD(GetCurrentMode)(THIS_ long*) PURE;
     STDMETHOD(GetMessageDrain)(THIS_ HWND*) PURE;
     STDMETHOD(GetModeInfo)(THIS_ long,long*,long*,long*) PURE;
     STDMETHOD(GetMonitor)(THIS_ long*) PURE;
     STDMETHOD(HideOnDeactivate)(THIS_ long) PURE;
     STDMETHOD(IsHideOnDeactivate)(THIS) PURE;
     STDMETHOD(IsKeepPixelAspectRatio)(THIS_ long*) PURE;
     STDMETHOD(IsModeAvailable)(THIS_ long) PURE;
     STDMETHOD(IsModeEnabled)(THIS_ long) PURE;
     STDMETHOD(KeepPixelAspectRatio)(THIS_ long) PURE;
     STDMETHOD(SetAcceleratorTable)(THIS_ HWND,HACCEL) PURE;
     STDMETHOD(SetCaption)(THIS_ BSTR) PURE;
     STDMETHOD(SetClipFactor)(THIS_ long) PURE;
     STDMETHOD(SetDefault)(THIS) PURE;
     STDMETHOD(SetEnabled)(THIS_ long,long) PURE;
     STDMETHOD(SetMessageDrain)(THIS_ HWND) PURE;
     STDMETHOD(SetMonitor)(THIS_ long) PURE;
 };
References HWND, long(), PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.
DECLARE_INTERFACE_() [4/4]
DECLARE_INTERFACE_ (IQualProp , IUnknown)
Definition at line 108 of file amvideo.h.
 {
     STDMETHOD(QueryInterface)(THIS_ REFIID,LPVOID*) PURE;
     STDMETHOD_(ULONG,AddRef)(THIS) PURE;
     STDMETHOD_(ULONG,Release)(THIS) PURE;
     STDMETHOD(get_AvgFrameRate)(THIS_ int*) PURE;
     STDMETHOD(get_AvgSyncOffset)(THIS_ int*) PURE;
     STDMETHOD(get_DevSyncOffset)(THIS_ int*) PURE;
     STDMETHOD(get_FramesDrawn)(THIS_ int*) PURE;
     STDMETHOD(get_FramesDroppedInRenderer)(THIS_ int*) PURE;
     STDMETHOD(get_Jitter)(THIS_ int*) PURE;
 };
References PURE, STDMETHOD, STDMETHOD_, THIS, and THIS_.