ZEQ2-Lite: Source/Engine/libspeex/preprocess.c File Reference
preprocess.c File Reference
#include <math.h>
#include "speex/speex_preprocess.h"
#include "speex/speex_echo.h"
#include "arch.h"
#include "fftwrap.h"
#include "filterbank.h"
#include "math_approx.h"
#include "os_support.h"
Data Structures
struct SpeexPreprocessState
Speex pre-processor state.
Macros
#define AMP_SCALE .001f
#define AMP_SCALE_1 1000.f
#define DIV32_16_Q15(a, b) ((a)/(b))
#define DIV32_16_Q8(a, b) ((a)/(b))
#define ECHO_SUPPRESS_ACTIVE_DEFAULT -15
#define ECHO_SUPPRESS_DEFAULT -40
#define EXPIN_SCALING 1.f
#define EXPIN_SCALING_1 1.f
#define EXPOUT_SCALING_1 1.f
#define FRAC_SCALING 1.f
#define FRAC_SCALING_1 1.f
#define FRAC_SHIFT 0
#define LOUDNESS_EXP 5.f
#define NB_BANDS 24
#define NOISE_OVERCOMPENS 1.
#define NOISE_SHIFT 0
#define NOISE_SUPPRESS_DEFAULT -15
#define NULL 0
#define SNR_SCALING 1.f
#define SNR_SCALING_1 1.f
#define SNR_SHIFT 0
#define SPEECH_PROB_CONTINUE_DEFAULT QCONST16(0.20f,15)
#define SPEECH_PROB_START_DEFAULT QCONST16(0.35f,15)
#define SQR(x) ((x)*(x))
#define SQR16(x) (MULT16_16((x),(x)))
#define SQR16_Q15(x) (MULT16_16_Q15((x),(x)))
Functions
static void compute_gain_floor (int noise_suppress, int effective_echo_suppress, spx_word32_t *noise, spx_word32_t *echo, spx_word16_t *gain_floor, int len)
static void conj_window (spx_word16_t *w, int len)
static spx_word32_t hypergeom_gain (spx_word32_t xx)
static void preprocess_analysis (SpeexPreprocessState *st, spx_int16_t *x)
static spx_word16_t qcurve (spx_word16_t x)
static void speex_compute_agc (SpeexPreprocessState *st, spx_word16_t Pframe, spx_word16_t *ft)
void speex_echo_get_residual (SpeexEchoState *st, spx_word32_t *Yout, int len)
int speex_preprocess (SpeexPreprocessState *st, spx_int16_t *x, spx_int32_t *echo)
Preprocess a frame (deprecated, use speex_preprocess_run() instead)
int speex_preprocess_ctl (SpeexPreprocessState *state, int request, void *ptr)
Used like the ioctl function to control the preprocessor parameters.
void speex_preprocess_estimate_update (SpeexPreprocessState *st, spx_int16_t *x)
Update preprocessor state, but do not compute the output.
int speex_preprocess_run (SpeexPreprocessState *st, spx_int16_t *x)
Preprocess a frame.
void speex_preprocess_state_destroy (SpeexPreprocessState *st)
Destroys a preprocessor state.
SpeexPreprocessState * speex_preprocess_state_init (int frame_size, int sampling_rate)
Creates a new preprocessing state.
static void update_noise_prob (SpeexPreprocessState *st)
Macro Definition Documentation
AMP_SCALE
#define AMP_SCALE .001f
Definition at line 76 of file preprocess.c.
AMP_SCALE_1
#define AMP_SCALE_1 1000.f
Definition at line 77 of file preprocess.c.
DIV32_16_Q15
#define DIV32_16_Q15 (a, b) ((a)/(b))
Definition at line 165 of file preprocess.c.
DIV32_16_Q8
#define DIV32_16_Q8 (a, b) ((a)/(b))
Definition at line 164 of file preprocess.c.
ECHO_SUPPRESS_ACTIVE_DEFAULT
#define ECHO_SUPPRESS_ACTIVE_DEFAULT -15
Definition at line 85 of file preprocess.c.
ECHO_SUPPRESS_DEFAULT
#define ECHO_SUPPRESS_DEFAULT -40
Definition at line 84 of file preprocess.c.
EXPIN_SCALING
#define EXPIN_SCALING 1.f
Definition at line 174 of file preprocess.c.
EXPIN_SCALING_1
#define EXPIN_SCALING_1 1.f
Definition at line 175 of file preprocess.c.
EXPOUT_SCALING_1
#define EXPOUT_SCALING_1 1.f
Definition at line 176 of file preprocess.c.
FRAC_SCALING
#define FRAC_SCALING 1.f
Definition at line 169 of file preprocess.c.
FRAC_SCALING_1
#define FRAC_SCALING_1 1.f
Definition at line 170 of file preprocess.c.
FRAC_SHIFT
#define FRAC_SHIFT 0
Definition at line 171 of file preprocess.c.
LOUDNESS_EXP
#define LOUDNESS_EXP 5.f
Definition at line 75 of file preprocess.c.
NB_BANDS
#define NB_BANDS 24
Definition at line 79 of file preprocess.c.
NOISE_OVERCOMPENS
#define NOISE_OVERCOMPENS 1.
Definition at line 718 of file preprocess.c.
NOISE_SHIFT
#define NOISE_SHIFT 0
Definition at line 172 of file preprocess.c.
NOISE_SUPPRESS_DEFAULT
#define NOISE_SUPPRESS_DEFAULT -15
Definition at line 83 of file preprocess.c.
NULL
#define NULL 0
Definition at line 88 of file preprocess.c.
SNR_SCALING
#define SNR_SCALING 1.f
Definition at line 166 of file preprocess.c.
SNR_SCALING_1
#define SNR_SCALING_1 1.f
Definition at line 167 of file preprocess.c.
SNR_SHIFT
#define SNR_SHIFT 0
Definition at line 168 of file preprocess.c.
SPEECH_PROB_CONTINUE_DEFAULT
#define SPEECH_PROB_CONTINUE_DEFAULT QCONST16(0.20f,15)
Definition at line 82 of file preprocess.c.
SPEECH_PROB_START_DEFAULT
#define SPEECH_PROB_START_DEFAULT QCONST16(0.35f,15)
Definition at line 81 of file preprocess.c.
SQR
#define SQR (x) ((x)*(x))
Definition at line 91 of file preprocess.c.
SQR16
#define SQR16 (x) (MULT16_16((x),(x)))
Definition at line 92 of file preprocess.c.
SQR16_Q15
#define SQR16_Q15 (x) (MULT16_16_Q15((x),(x)))
Definition at line 93 of file preprocess.c.
Function Documentation
compute_gain_floor()
static void compute_gain_floor (int noise_suppress, int effective_echo_suppress, spx_word32_t * noise, spx_word32_t * echo, spx_word16_t * gain_floor, int len) static
Definition at line 379 of file preprocess.c.
 {
    int i;
    float echo_floor;
    float noise_floor;
    noise_floor = exp(.2302585f*noise_suppress);
    echo_floor = exp(.2302585f*effective_echo_suppress);
    /* Compute the gain floor based on different floors for the background noise and residual echo */
    for (i=0;i<len;i++)
       gain_floor[i] = FRAC_SCALING*sqrt(noise_floor*PSHR32(noise[i],NOISE_SHIFT) + echo_floor*echo[i])/sqrt(1+PSHR32(noise[i],NOISE_SHIFT) + echo[i]);
 }
References FRAC_SCALING, NOISE_SHIFT, and PSHR32.
Referenced by speex_preprocess_run().
conj_window()
static void conj_window (spx_word16_t * w, int len) static
Definition at line 254 of file preprocess.c.
 {
    int i;
    for (i=0;i<len;i++)
    {
       spx_word16_t tmp;
 #ifdef FIXED_POINT
       spx_word16_t x = DIV32_16(MULT16_16(32767,i),len);
 #else
       spx_word16_t x = DIV32_16(MULT16_16(QCONST16(4.f,13),i),len);
 #endif
       int inv=0;
       if (x<QCONST16(1.f,13))
       {
       } else if (x<QCONST16(2.f,13))
       {
          x=QCONST16(2.f,13)-x;
          inv=1;
       } else if (x<QCONST16(3.f,13))
       {
          x=x-QCONST16(2.f,13);
          inv=1;
       } else {
          x=QCONST16(2.f,13)-x+QCONST16(2.f,13); /* 4 - x */
       }
       x = MULT16_16_Q14(QCONST16(1.271903f,14), x);
       tmp = SQR16_Q15(QCONST16(.5f,15)-MULT16_16_P15(QCONST16(.5f,15),spx_cos_norm(SHL32(EXTEND32(x),2))));
       if (inv)
          tmp=SUB16(Q15_ONE,tmp);
       w[i]=spx_sqrt(SHL32(EXTEND32(tmp),15));
    }
 }
References DIV32_16, EXTEND32, MULT16_16, MULT16_16_P15, MULT16_16_Q14, Q15_ONE, QCONST16, SHL32, spx_cos_norm, spx_sqrt, SQR16_Q15, and SUB16.
Referenced by speex_preprocess_state_init().
hypergeom_gain()
static spx_word32_t hypergeom_gain (spx_word32_t xx) inline static
Definition at line 354 of file preprocess.c.
 {
    int ind;
    float integer, frac;
    float x;
    static const float table[21] = {
       0.82157f, 1.02017f, 1.20461f, 1.37534f, 1.53363f, 1.68092f, 1.81865f,
       1.94811f, 2.07038f, 2.18638f, 2.29688f, 2.40255f, 2.50391f, 2.60144f,
       2.69551f, 2.78647f, 2.87458f, 2.96015f, 3.04333f, 3.12431f, 3.20326f};
       x = EXPIN_SCALING_1*xx;
       integer = floor(2*x);
       ind = (int)integer;
       if (ind<0)
          return FRAC_SCALING;
       if (ind>19)
          return FRAC_SCALING*(1+.1296/x);
       frac = 2*x-integer;
       return FRAC_SCALING*((1-frac)*table[ind] + frac*table[ind+1])/sqrt(x+.0001f);
 }
References EXPIN_SCALING_1, FRAC_SCALING, int(), and xx.
Referenced by speex_preprocess_run().
preprocess_analysis()
static void preprocess_analysis (SpeexPreprocessState * st, spx_int16_t * x) static
Definition at line 619 of file preprocess.c.
 {
    int i;
    int N = st->ps_size;
    int N3 = 2*N - st->frame_size;
    int N4 = st->frame_size - N3;
    spx_word32_t *ps=st->ps;
    /* 'Build' input frame */
    for (i=0;i<N3;i++)
       st->frame[i]=st->inbuf[i];
    for (i=0;i<st->frame_size;i++)
       st->frame[N3+i]=x[i];
    /* Update inbuf */
    for (i=0;i<N3;i++)
       st->inbuf[i]=x[N4+i];
    /* Windowing */
    for (i=0;i<2*N;i++)
       st->frame[i] = MULT16_16_Q15(st->frame[i], st->window[i]);
 #ifdef FIXED_POINT
    {
       spx_word16_t max_val=0;
       for (i=0;i<2*N;i++)
          max_val = MAX16(max_val, ABS16(st->frame[i]));
       st->frame_shift = 14-spx_ilog2(EXTEND32(max_val));
       for (i=0;i<2*N;i++)
          st->frame[i] = SHL16(st->frame[i], st->frame_shift);
    }
 #endif
    /* Perform FFT */
    spx_fft(st->fft_lookup, st->frame, st->ft);
    /* Power spectrum */
    ps[0]=MULT16_16(st->ft[0],st->ft[0]);
    for (i=1;i<N;i++)
       ps[i]=MULT16_16(st->ft[2*i-1],st->ft[2*i-1]) + MULT16_16(st->ft[2*i],st->ft[2*i]);
    for (i=0;i<N;i++)
       st->ps[i] = PSHR32(st->ps[i], 2*st->frame_shift);
    filterbank_compute_bank32(st->bank, ps, ps+N);
 }
References ABS16, EXTEND32, filterbank_compute_bank32(), MAX16, MULT16_16, MULT16_16_Q15, PSHR32, SHL16, spx_fft(), and spx_ilog2().
Referenced by speex_preprocess_estimate_update(), and speex_preprocess_run().
qcurve()
static spx_word16_t qcurve (spx_word16_t x) inline static
Definition at line 374 of file preprocess.c.
 {
    return 1.f/(1.f+.15f/(SNR_SCALING_1*x));
 }
References SNR_SCALING_1.
Referenced by speex_preprocess_run().
speex_compute_agc()
static void speex_compute_agc (SpeexPreprocessState * st, spx_word16_t Pframe, spx_word16_t * ft) static
Definition at line 569 of file preprocess.c.
 {
    int i;
    int N = st->ps_size;
    float target_gain;
    float loudness=1.f;
    float rate;
    for (i=2;i<N;i++)
    {
       loudness += 2.f*N*st->ps[i]* st->loudness_weight[i];
    }
    loudness=sqrt(loudness);
       /*if (loudness < 2*pow(st->loudness, 1.0/LOUDNESS_EXP) &&
    loudness*2 > pow(st->loudness, 1.0/LOUDNESS_EXP))*/
    if (Pframe>.3f)
    {
       st->nb_loudness_adapt++;
       /*rate=2.0f*Pframe*Pframe/(1+st->nb_loudness_adapt);*/
       rate = .03*Pframe*Pframe;
       st->loudness = (1-rate)*st->loudness + (rate)*pow(AMP_SCALE*loudness, LOUDNESS_EXP);
       st->loudness_accum = (1-rate)*st->loudness_accum + rate;
       if (st->init_max < st->max_gain && st->nb_adapt > 20)
          st->init_max *= 1.f + .1f*Pframe*Pframe;
    }
    /*printf ("%f %f %f %f\n", Pframe, loudness, pow(st->loudness, 1.0f/LOUDNESS_EXP), st->loudness2);*/
    target_gain = AMP_SCALE*st->agc_level*pow(st->loudness/(1e-4+st->loudness_accum), -1.0f/LOUDNESS_EXP);
    if ((Pframe>.5  && st->nb_adapt > 20) || target_gain < st->agc_gain)
    {
       if (target_gain > st->max_increase_step*st->agc_gain)
          target_gain = st->max_increase_step*st->agc_gain;
       if (target_gain < st->max_decrease_step*st->agc_gain && loudness < 10*st->prev_loudness)
          target_gain = st->max_decrease_step*st->agc_gain;
       if (target_gain > st->max_gain)
          target_gain = st->max_gain;
       if (target_gain > st->init_max)
          target_gain = st->init_max;
       st->agc_gain = target_gain;
    }
    /*fprintf (stderr, "%f %f %f\n", loudness, (float)AMP_SCALE_1*pow(st->loudness, 1.0f/LOUDNESS_EXP), st->agc_gain);*/
    for (i=0;i<2*N;i++)
       ft[i] *= st->agc_gain;
    st->prev_loudness = loudness;
 }
References AMP_SCALE, and LOUDNESS_EXP.
Referenced by speex_preprocess_run().
speex_echo_get_residual()
void speex_echo_get_residual (SpeexEchoState * st, spx_word32_t * Yout, int len)
Definition at line 1111 of file mdf.c.
 {
    int i;
    spx_word16_t leak2;
    int N;
    N = st->window_size;
    /* Apply hanning window (should pre-compute it)*/
    for (i=0;i<N;i++)
       st->y[i] = MULT16_16_Q15(st->window[i],st->last_y[i]);
    /* Compute power spectrum of the echo */
    spx_fft(st->fft_table, st->y, st->Y);
    power_spectrum(st->Y, residual_echo, N);
 #ifdef FIXED_POINT
    if (st->leak_estimate > 16383)
       leak2 = 32767;
    else
       leak2 = SHL16(st->leak_estimate, 1);
 #else
    if (st->leak_estimate>.5)
       leak2 = 1;
    else
       leak2 = 2*st->leak_estimate;
 #endif
    /* Estimate residual echo */
    for (i=0;i<=st->frame_size;i++)
       residual_echo[i] = (spx_int32_t)MULT16_32_Q15(leak2,residual_echo[i]);
 }
References MULT16_16_Q15, MULT16_32_Q15, power_spectrum(), SHL16, and spx_fft().
Referenced by speex_preprocess_run().
update_noise_prob()
static void update_noise_prob (SpeexPreprocessState * st) static
Definition at line 665 of file preprocess.c.
 {
    int i;
    int min_range;
    int N = st->ps_size;
    for (i=1;i<N-1;i++)
       st->S[i] =  MULT16_32_Q15(QCONST16(.8f,15),st->S[i]) + MULT16_32_Q15(QCONST16(.05f,15),st->ps[i-1])
                       + MULT16_32_Q15(QCONST16(.1f,15),st->ps[i]) + MULT16_32_Q15(QCONST16(.05f,15),st->ps[i+1]);
    st->S[0] =  MULT16_32_Q15(QCONST16(.8f,15),st->S[0]) + MULT16_32_Q15(QCONST16(.2f,15),st->ps[0]);
    st->S[N-1] =  MULT16_32_Q15(QCONST16(.8f,15),st->S[N-1]) + MULT16_32_Q15(QCONST16(.2f,15),st->ps[N-1]);
    if (st->nb_adapt==1)
    {
       for (i=0;i<N;i++)
          st->Smin[i] = st->Stmp[i] = 0;
    }
    if (st->nb_adapt < 100)
       min_range = 15;
    else if (st->nb_adapt < 1000)
       min_range = 50;
    else if (st->nb_adapt < 10000)
       min_range = 150;
    else
       min_range = 300;
    if (st->min_count > min_range)
    {
       st->min_count = 0;
       for (i=0;i<N;i++)
       {
          st->Smin[i] = MIN32(st->Stmp[i], st->S[i]);
          st->Stmp[i] = st->S[i];
       }
    } else {
       for (i=0;i<N;i++)
       {
          st->Smin[i] = MIN32(st->Smin[i], st->S[i]);
          st->Stmp[i] = MIN32(st->Stmp[i], st->S[i]);
       }
    }
    for (i=0;i<N;i++)
    {
       if (MULT16_32_Q15(QCONST16(.4f,15),st->S[i]) > ADD32(st->Smin[i],EXTEND32(20)))
          st->update_prob[i] = 1;
       else
          st->update_prob[i] = 0;
       /*fprintf (stderr, "%f ", st->S[i]/st->Smin[i]);*/
       /*fprintf (stderr, "%f ", st->update_prob[i]);*/
    }
 }
References ADD32, EXTEND32, MIN32, MULT16_32_Q15, and QCONST16.
Referenced by speex_preprocess_estimate_update(), and speex_preprocess_run().