ZEQ2-Lite: Source/Engine/tools/lcc/src/enode.c File Reference
enode.c File Reference
#include "c.h"
#include "token.h"
Macros
#define isvoidptr(ty) (isptr(ty) && unqual(ty->type) == voidtype)
#define xx(a, b, c, d, e, f, g) e,
#define yy(a, b, c, d, e, f, g) e,
Functions
Tree addrof (Tree p)
static Tree addtree (int, Tree, Tree)
static Tree andtree (int, Tree, Tree)
Tree asgn (Symbol p, Tree e)
Tree asgntree (int op, Tree l, Tree r)
Type assign (Type xty, Tree e)
Tree bittree (int op, Tree l, Tree r)
Tree call (Tree f, Type fty, Coordinate src)
Tree calltree (Tree f, Type ty, Tree args, Symbol t3)
static Tree cmptree (int, Tree, Tree)
Tree cnsttree (Type ty,...)
static int compatible (Type, Type)
Tree condtree (Tree e, Tree l, Tree r)
Tree consttree (unsigned n, Type ty)
Tree eqtree (int op, Tree l, Tree r)
int iscallb (Tree e)
static int isnullptr (Tree e)
static Tree multree (int, Tree, Tree)
Tree shtree (int op, Tree l, Tree r)
static Tree subtree (int, Tree, Tree)
void typeerror (int op, Tree l, Tree r)
Tree vcall (Symbol func, Type ty,...)
Variables
Tree(* optree [])(int, Tree, Tree)
Macro Definition Documentation
isvoidptr
#define isvoidptr (ty) (isptr(ty) && unqual(ty->type) == voidtype)
Definition at line 11 of file enode.c.
xx
#define xx (a, b, c, d, e, f, g) e,
yy
#define yy (a, b, c, d, e, f, g) e,
Function Documentation
addrof()
Tree addrof (Tree p)
Definition at line 389 of file enode.c.
                     {
     Tree q = p;
     for (;;)
         switch (generic(q->op)) {
         case RIGHT:
             assert(q->kids[0] || q->kids[1]);
             q = q->kids[1] ? q->kids[1] : q->kids[0];
             continue;
         case ASGN:
             q = q->kids[1];
             continue;
         case COND: {
             Symbol t1 = q->u.sym;
             q->u.sym = 0;
             q = idtree(t1);
             /* fall thru */
             }
         case INDIR:
             if (p == q)
                 return q->kids[0];
             q = q->kids[0];
             return tree(RIGHT, q->type, root(p), q);
         default:
             error("addressable object required\n");
             return value(p);
         }
 }
References ASGN, COND, error(), idtree(), RIGHT, root(), and tree().
Referenced by call(), calltree(), postfix(), and tracevalue().
addtree()
static Tree addtree (int op, Tree l, Tree r) static
Definition at line 149 of file enode.c.
{
     Type ty = inttype;
     if (isarith(l->type) && isarith(r->type)) {
         ty = binary(l->type, r->type);
         l = cast(l, ty);
         r = cast(r, ty);
     } else if (isptr(l->type) && isint(r->type))
         return addtree(ADD, r, l);
     else if (  isptr(r->type) && isint(l->type)
     && !isfunc(r->type->type))
         {
             long n;
             ty = unqual(r->type);
             n = unqual(ty->type)->size;
             if (n == 0)
                 error("unknown size for type `%t'\n", ty->type);
             l = cast(l, promote(l->type));
             if (n > 1)
                 l = multree(MUL, cnsttree(signedptr, n), l);
             if (YYcheck && !isaddrop(r->op))        /* omit */
                 return nullcall(ty, YYcheck, r, l); /* omit */
             return simplify(ADD, ty, l, r);
         }
     else
         typeerror(op, l, r);
     return simplify(op, ty, l, r);
 }
References ADD, binary(), cast(), cnsttree(), error(), inttype, isaddrop, isarith, isfunc, isint, isptr, Symbol::l, multree(), nullcall(), op, promote(), signedptr, simplify(), typeerror(), unqual, and YYcheck.
andtree()
static Tree andtree (int op, Tree l, Tree r) static
Definition at line 419 of file enode.c.
{
     if (!isscalar(l->type) || !isscalar(r->type))
         typeerror(op, l, r);
     return simplify(op, inttype, cond(l), cond(r));
 }
References cond(), inttype, isscalar, Symbol::l, op, simplify(), and typeerror().
asgn()
Tree asgn (Symbol p, Tree e)
Definition at line 426 of file enode.c.
{
     if (isarray(p->type))
         e = tree(ASGN+B, p->type, idtree(p),
             tree(INDIR+B, e->type, e, NULL));
     else {
         Type ty = p->type;
         p->type = unqual(p->type);
         if (isstruct(p->type) && p->type->u.sym->u.s.cfields) {
             p->type->u.sym->u.s.cfields = 0;
             e = asgntree(ASGN, idtree(p), e);
             p->type->u.sym->u.s.cfields = 1;
         } else
             e = asgntree(ASGN, idtree(p), e);
         p->type = ty;
     }
     return e;
 }
References ASGN, asgntree(), B, idtree(), isarray, isstruct, NULL, tree(), and unqual.
Referenced by bbcall(), call(), condtree(), dcllocal(), gencode(), nullcheck(), retcode(), swstmt(), and tracecall().
asgntree()
Tree asgntree (int op, Tree l, Tree r)
Definition at line 287 of file enode.c.
{
     Type aty, ty;
     r = pointer(r);
     ty = assign(l->type, r);
     if (ty)
         r = cast(r, ty);
     else {
         typeerror(ASGN, l, r);
         if (r->type == voidtype)
             r = retype(r, inttype);
         ty = r->type;
     }
     if (l->op != FIELD)
         l = lvalue(l);
     aty = l->type;
     if (isptr(aty))
         aty = unqual(aty)->type;
     if ( isconst(aty)
     ||  (isstruct(aty) && unqual(aty)->u.sym->u.s.cfields)) {
         if (isaddrop(l->op)
         && !l->u.sym->computed && !l->u.sym->generated)
             error("assignment to const identifier `%s'\n",
                 l->u.sym->name);
         else
             error("assignment to const location\n");
     }
     if (l->op == FIELD) {
         long n = 8*l->u.field->type->size - fieldsize(l->u.field);
         if (n > 0 && isunsigned(l->u.field->type))
             r = bittree(BAND, r,
                 cnsttree(r->type, (unsigned long)fieldmask(l->u.field)));
         else if (n > 0) {
             if (r->op == CNST+I) {
                 n = r->u.v.i;
                 if (n&(1<<(fieldsize(l->u.field)-1)))
                     n |= ~0UL<<fieldsize(l->u.field);
                 r = cnsttree(r->type, n);
             } else
                 r = shtree(RSH,
                     shtree(LSH, r, cnsttree(inttype, n)),
                     cnsttree(inttype, n));
         }
     }
     if (isstruct(ty) && isaddrop(l->op) && iscallb(r))
         return tree(RIGHT, ty,
             tree(CALL+B, ty, r->kids[0]->kids[0], l),
             idtree(l->u.sym));
     return tree(mkop(op,ty), ty, l, r);
 }
References ASGN, assign(), B, bittree(), CALL, cast(), cnsttree(), error(), FIELD, fieldmask, fieldsize, I, idtree(), inttype, isaddrop, iscallb(), isconst, isptr, isstruct, isunsigned, Symbol::l, LSH, lvalue(), mkop, op, retype(), RIGHT, RSH, shtree(), tree(), typeerror(), Symbol::u, unqual, and voidtype.
Referenced by asgn().
assign()
Type assign (Type xty, Tree e)
Definition at line 249 of file enode.c.
{
     Type yty = unqual(e->type);
     xty = unqual(xty);
     if (isenum(xty))
         xty = xty->type;
     if (xty->size == 0 || yty->size == 0)
         return NULL;
     if ( (isarith(xty) && isarith(yty))
     ||  (isstruct(xty) && xty == yty))
         return xty;
     if (isptr(xty) && isnullptr(e))
         return xty;
     if (((isvoidptr(xty) && isptr(yty))
       || (isptr(xty)     && isvoidptr(yty)))
     && (  (isconst(xty->type)    || !isconst(yty->type))
        && (isvolatile(xty->type) || !isvolatile(yty->type))))
         return xty;
     if ((isptr(xty) && isptr(yty)
         && eqtype(unqual(xty->type), unqual(yty->type), 1))
     &&  (  (isconst(xty->type)    || !isconst(yty->type))
         && (isvolatile(xty->type) || !isvolatile(yty->type))))
         return xty;
     if (isptr(xty) && isptr(yty)
     && (  (isconst(xty->type)    || !isconst(yty->type))
        && (isvolatile(xty->type) || !isvolatile(yty->type)))) {
         Type lty = unqual(xty->type), rty = unqual(yty->type);
         if ((isenum(lty) && rty == inttype)
         ||  (isenum(rty) && lty == inttype)) {
             if (Aflag >= 1)
                 warning("assignment between `%t' and `%t' is compiler-dependent\n",
                     xty, yty);
             return xty;
         }
     }
     return NULL;
 }
References Aflag, eqtype(), inttype, isarith, isconst, isenum, isnullptr(), isptr, isstruct, isvoidptr, isvolatile, NULL, unqual, and warning().
Referenced by asgntree(), call(), initializer(), initvalue(), and retcode().
bittree()
Tree bittree (int op, Tree l, Tree r)
Definition at line 445 of file enode.c.
{
     Type ty = inttype;
     if (isint(l->type) && isint(r->type)) {
         ty = binary(l->type, r->type);
         l = cast(l, ty);
         r = cast(r, ty);
     } else
         typeerror(op, l, r);
     return simplify(op, ty, l, r);
 }
References binary(), cast(), inttype, isint, Symbol::l, op, simplify(), and typeerror().
Referenced by asgntree().
call()
Tree call (Tree f, Type fty, Coordinate src)
Definition at line 19 of file enode.c.
{
     int n = 0;
     Tree args = NULL, r = NULL, e;
     Type *proto, rty = unqual(freturn(fty));
     Symbol t3 = NULL;
     if (fty->u.f.oldstyle)
         proto = NULL;
     else
         proto = fty->u.f.proto;
     if (hascall(f))
         r = f;
     if (isstruct(rty))
         {
             t3 = temporary(AUTO, unqual(rty));
             if (rty->size == 0)
                 error("illegal use of incomplete type `%t'\n", rty);
         }
     if (t != ')')
         for (;;) {
             Tree q = pointer(expr1(0));
             if (proto && *proto && *proto != voidtype)
                 {
                     Type aty;
                     q = value(q);
                     aty = assign(*proto, q);
                     if (aty)
                         q = cast(q, aty);
                     else
                         error("type error in argument %d to %s; found `%t' expected `%t'\n", n + 1, funcname(f),
                             q->type, *proto);
                     if ((isint(q->type) || isenum(q->type))
                     && q->type->size != inttype->size)
                         q = cast(q, promote(q->type));
                     ++proto;
                 }
             else
                 {
                     if (!fty->u.f.oldstyle && *proto == NULL)
                         error("too many arguments to %s\n", funcname(f));
                     q = value(q);
                     if (isarray(q->type) || q->type->size == 0)
                         error("type error in argument %d to %s; `%t' is illegal\n", n + 1, funcname(f), q->type);
                     else
                         q = cast(q, promote(q->type));
                 }
             if (!IR->wants_argb && isstruct(q->type)) {
                 if (iscallb(q))
                     q = addrof(q);
                 else {
                     Symbol t1 = temporary(AUTO, unqual(q->type));
                     q = asgn(t1, q);
                     q = tree(RIGHT, ptr(t1->type),
                         root(q), lvalue(idtree(t1)));
                 }
             }
             if (q->type->size == 0)
                 q->type = inttype;
             if (hascall(q))
                 r = r ? tree(RIGHT, voidtype, r, q) : q;
             args = tree(mkop(ARG, q->type), q->type, q, args);
             n++;
             if (Aflag >= 2 && n == 32)
                 warning("more than 31 arguments in a call to %s\n",
                     funcname(f));
             if (t != ',')
                 break;
             t = gettok();
         }
     expect(')');
     if (proto && *proto && *proto != voidtype)
         error("insufficient number of arguments to %s\n",
             funcname(f));
     if (r)
         args = tree(RIGHT, voidtype, r, args);
     e = calltree(f, rty, args, t3);
     if (events.calls)
         apply(events.calls, &src, &e);
     return e;
 }
References addrof(), Aflag, apply(), args, asgn(), assign(), Events::calls, calltree(), cast(), error(), events, expect(), expr1(), Symbol::f, freturn(), funcname(), gettok(), hascall(), idtree(), inttype, IR, isarray, iscallb(), isenum, isint, isstruct, lvalue(), mkop, NULL, promote(), ptr(), RIGHT, root(), temporary(), tree(), unqual, voidtype, and warning().
Referenced by asmcall(), postfix(), and VM_CallCompiled().
calltree()
Tree calltree (Tree f, Type ty, Tree args, Symbol t3)
Definition at line 101 of file enode.c.
{
     Tree p;
     if (args)
         f = tree(RIGHT, f->type, args, f);
     if (isstruct(ty))
         assert(t3),
         p = tree(RIGHT, ty,
             tree(CALL+B, ty, f, addrof(idtree(t3))),
             idtree(t3));
     else {
         Type rty = ty;
         if (isenum(ty))
             rty = unqual(ty)->type;
         if (!isfloat(rty))
             rty = promote(rty);
         p = tree(mkop(CALL, rty), rty, f, NULL);
         if (isptr(ty) || p->type->size > ty->size)
             p = cast(p, ty);
     }
     return p;
 }
References addrof(), args, B, CALL, cast(), Symbol::f, idtree(), isenum, isfloat, isptr, isstruct, mkop, NULL, promote(), RIGHT, tree(), and unqual.
Referenced by call(), tracefinis(), and vcall().
cmptree()
static Tree cmptree (int op, Tree l, Tree r) static
Definition at line 201 of file enode.c.
{
     Type ty;
     if (isarith(l->type) && isarith(r->type)) {
         ty = binary(l->type, r->type);
         l = cast(l, ty);
         r = cast(r, ty);
     } else if (compatible(l->type, r->type)) {
         ty = unsignedptr;
         l = cast(l, ty);
         r = cast(r, ty);
     } else {
         ty = unsignedtype;
         typeerror(op, l, r);
     }
     return simplify(mkop(op,ty), inttype, l, r);
 }
References binary(), cast(), compatible(), inttype, isarith, Symbol::l, mkop, op, simplify(), typeerror(), unsignedptr, and unsignedtype.
Referenced by eqtree().
cnsttree()
Tree cnsttree (Type ty, ...)
Definition at line 179 of file enode.c.
{
     Tree p = tree(mkop(CNST,ty), ty, NULL, NULL);
     va_list ap;
     va_start(ap, ty);
     switch (ty->op) {
     case INT:     p->u.v.i = va_arg(ap, long); break;
     case UNSIGNED:p->u.v.u = va_arg(ap, unsigned long)&ones(8*ty->size); break;
     case FLOAT:   p->u.v.d = va_arg(ap, double); break;
     case POINTER: p->u.v.p = va_arg(ap, void *); break;
     default: assert(0);
     }
     va_end(ap);
     return p;
 }
References INT, mkop, NULL, ones, and tree().
Referenced by addtree(), asgntree(), cast(), cmp(), consttree(), funcdefn(), listnodes(), nullcall(), nullcheck(), primary(), simplify(), subtree(), swcode(), and unary().
compatible()
static int compatible (Type ty1, Type ty2) static
Definition at line 218 of file enode.c.
{
     return isptr(ty1) && !isfunc(ty1->type)
         && isptr(ty2) && !isfunc(ty2->type)
         && eqtype(unqual(ty1->type), unqual(ty2->type), 0);
 }
References eqtype(), isfunc, isptr, and unqual.
Referenced by cmptree(), and subtree().
condtree()
Tree condtree (Tree e, Tree l, Tree r)
Definition at line 337 of file enode.c.
{
     Symbol t1;
     Type ty, xty = l->type, yty = r->type;
     Tree p;
     if (isarith(xty) && isarith(yty))
         ty = binary(xty, yty);
     else if (eqtype(xty, yty, 1))
         ty = unqual(xty);
     else if (isptr(xty)   && isnullptr(r))
         ty = xty;
     else if (isnullptr(l) && isptr(yty))
         ty = yty;
     else if ((isptr(xty) && !isfunc(xty->type) && isvoidptr(yty))
     ||       (isptr(yty) && !isfunc(yty->type) && isvoidptr(xty)))
         ty = voidptype;
     else if ((isptr(xty) && isptr(yty)
          && eqtype(unqual(xty->type), unqual(yty->type), 1)))
         ty = xty;
     else {
         typeerror(COND, l, r);
         return consttree(0, inttype);
     }
     if (isptr(ty)) {
         ty = unqual(unqual(ty)->type);
         if ((isptr(xty) && isconst(unqual(xty)->type))
         ||  (isptr(yty) && isconst(unqual(yty)->type)))
             ty = qual(CONST, ty);
         if ((isptr(xty) && isvolatile(unqual(xty)->type))
         ||  (isptr(yty) && isvolatile(unqual(yty)->type)))
             ty = qual(VOLATILE, ty);
         ty = ptr(ty);
     }
     switch (e->op) {
     case CNST+I: return cast(e->u.v.i != 0   ? l : r, ty);
     case CNST+U: return cast(e->u.v.u != 0   ? l : r, ty);
     case CNST+P: return cast(e->u.v.p != 0   ? l : r, ty);
     case CNST+F: return cast(e->u.v.d != 0.0 ? l : r, ty);
     }
     if (ty != voidtype && ty->size > 0) {
         t1 = genident(REGISTER, unqual(ty), level);
     /*  t1 = temporary(REGISTER, unqual(ty)); */
         l = asgn(t1, l);
         r = asgn(t1, r);
     } else
         t1 = NULL;
     p = tree(COND, ty, cond(e),
         tree(RIGHT, ty, root(l), root(r)));
     p->u.sym = t1;
     return p;
 }
References asgn(), binary(), cast(), COND, cond(), consttree(), eqtype(), F, genident(), I, inttype, isarith, isconst, isfunc, isnullptr(), isptr, isvoidptr, isvolatile, Symbol::l, NULL, P, ptr(), qual(), RIGHT, root(), tree(), typeerror(), U, unqual, voidptype, and voidtype.
Referenced by cast(), expr2(), tracevalue(), and value().
consttree()
Tree consttree (unsigned n, Type ty)
Definition at line 195 of file enode.c.
{
     if (isarray(ty))
         ty = atop(ty);
     else assert(isint(ty));
     return cnsttree(ty, (unsigned long)n);
 }
References atop(), cnsttree(), isarray, and isint.
Referenced by condtree().
eqtree()
Tree eqtree (int op, Tree l, Tree r)
Definition at line 231 of file enode.c.
{
     Type xty = l->type, yty = r->type;
     if ((isptr(xty) && isnullptr(r))
     ||  (isptr(xty) && !isfunc(xty->type) && isvoidptr(yty))
     ||  (isptr(xty) && isptr(yty)
         && eqtype(unqual(xty->type), unqual(yty->type), 1))) {
         Type ty = unsignedptr;
         l = cast(l, ty);
         r = cast(r, ty);
         return simplify(mkop(op,ty), inttype, l, r);
     }
     if ((isptr(yty) && isnullptr(l))
     ||  (isptr(yty) && !isfunc(yty->type) && isvoidptr(xty)))
         return eqtree(op, r, l);
     return cmptree(op, l, r);
 }
References cast(), cmptree(), eqtype(), inttype, isfunc, isnullptr(), isptr, isvoidptr, Symbol::l, mkop, op, simplify(), unqual, and unsignedptr.
iscallb()
int iscallb (Tree e)
Definition at line 141 of file enode.c.
                     {
     return e->op == RIGHT && e->kids[0] && e->kids[1]
         && e->kids[0]->op == CALL+B
         && e->kids[1]->op == INDIR+B
         && isaddrop(e->kids[1]->kids[0]->op)
         && e->kids[1]->kids[0]->u.sym->temporary;
 }
References B, CALL, isaddrop, and RIGHT.
Referenced by asgntree(), call(), and retcode().
isnullptr()
static int isnullptr (Tree e) static
Definition at line 223 of file enode.c.
{
     Type ty = unqual(e->type);
     return generic(e->op) == CNST
         && ((ty->op == INT      && e->u.v.i == 0)
          || (ty->op == UNSIGNED && e->u.v.u == 0)
          || (isvoidptr(ty)      && e->u.v.p == NULL));
 }
References INT, isvoidptr, NULL, and unqual.
Referenced by assign(), condtree(), and eqtree().
multree()
static Tree multree (int op, Tree l, Tree r) static
Definition at line 458 of file enode.c.
{
     Type ty = inttype;
     if (isarith(l->type) && isarith(r->type)) {
         ty = binary(l->type, r->type);
         l = cast(l, ty);
         r = cast(r, ty);
     } else
         typeerror(op, l, r);
     return simplify(op, ty, l, r);
 }
References binary(), cast(), inttype, isarith, Symbol::l, op, simplify(), and typeerror().
Referenced by addtree(), and subtree().
shtree()
Tree shtree (int op, Tree l, Tree r)
Definition at line 471 of file enode.c.
{
     Type ty = inttype;
     if (isint(l->type) && isint(r->type)) {
         ty = promote(l->type);
         l = cast(l, ty);
         r = cast(r, inttype);
     } else
         typeerror(op, l, r);
     return simplify(op, ty, l, r);
 }
References cast(), inttype, isint, Symbol::l, op, promote(), simplify(), and typeerror().
Referenced by asgntree(), and listnodes().
subtree()
static Tree subtree (int op, Tree l, Tree r) static
Definition at line 484 of file enode.c.
{
     long n;
     Type ty = inttype;
     if (isarith(l->type) && isarith(r->type)) {
         ty = binary(l->type, r->type);
         l = cast(l, ty);
         r = cast(r, ty);
     } else if (isptr(l->type) && !isfunc(l->type->type) && isint(r->type)) {
         ty = unqual(l->type);
         n = unqual(ty->type)->size;
         if (n == 0)
             error("unknown size for type `%t'\n", ty->type);
         r = cast(r, promote(r->type));
         if (n > 1)
             r = multree(MUL, cnsttree(signedptr, n), r);
         if (isunsigned(r->type))
             r = cast(r, unsignedptr);
         else
             r = cast(r, signedptr);
         return simplify(SUB+P, ty, l, r);
     } else if (compatible(l->type, r->type)) {
         ty = unqual(l->type);
         n = unqual(ty->type)->size;
         if (n == 0)
             error("unknown size for type `%t'\n", ty->type);
         l = simplify(SUB+U, unsignedptr,
             cast(l, unsignedptr), cast(r, unsignedptr));
         return simplify(DIV+I, longtype,
             cast(l, longtype), cnsttree(longtype, n));
     } else
         typeerror(op, l, r);
     return simplify(op, ty, l, r);
 }
References binary(), cast(), cnsttree(), compatible(), DIV, error(), I, inttype, isarith, isfunc, isint, isptr, isunsigned, Symbol::l, longtype, multree(), op, P, promote(), signedptr, simplify(), SUB, typeerror(), U, unqual, and unsignedptr.
typeerror()
void typeerror (int op, Tree l, Tree r)
Definition at line 520 of file enode.c.
{
     int i;
     static struct { int op; char *name; } ops[] = {
         {ASGN, "="},    {INDIR, "*"},   {NEG,  "-"},
         {ADD,  "+"},    {SUB,   "-"},   {LSH,  "<<"},
         {MOD,  "%"},    {RSH,   ">>"},  {BAND, "&"},
         {BCOM, "~"},    {BOR,   "|"},   {BXOR, "^"},
         {DIV,  "/"},    {MUL,   "*"},   {EQ,   "=="},
         {GE,   ">="},   {GT,    ">"},   {LE,   "<="},
         {LT,   "<"},    {NE,    "!="},  {AND,  "&&"},
         {NOT,  "!"},    {OR,    "||"},  {COND, "?:"},
         {0, 0}
     };
     op = generic(op);
     for (i = 0; ops[i].op; i++)
         if (op == ops[i].op)
             break;
     assert(ops[i].name);
     if (r)
         error("operands of %s have illegal types `%t' and `%t'\n",
             ops[i].name, l->type, r->type);
     else
         error("operand of unary %s has illegal type `%t'\n", ops[i].name,
             l->type);
 }
References ADD, AND, ASGN, COND, DIV, EQ, error(), GT, Symbol::l, LSH, LT, MOD, NOT, op, ops, OR, RSH, and SUB.
Referenced by addtree(), andtree(), asgntree(), bittree(), cmptree(), condtree(), multree(), shtree(), subtree(), and unary().
vcall()
Tree vcall (Symbol func, Type ty, ...)
Definition at line 123 of file enode.c.
{
     va_list ap;
     Tree args = NULL, e, f = pointer(idtree(func)), r = NULL;
     assert(isfunc(func->type));
     if (ty == NULL)
         ty = freturn(func->type);
     va_start(ap, ty);
     while ((e = va_arg(ap, Tree)) != NULL) {
         if (hascall(e))
             r = r == NULL ? e : tree(RIGHT, voidtype, r, e);
         args = tree(mkop(ARG, e->type), e->type, e, args);
     }
     va_end(ap);
     if (r != NULL)
         args = tree(RIGHT, voidtype, r, args);
     return calltree(f, ty, args, NULL);
 }
References args, calltree(), Symbol::f, freturn(), hascall(), idtree(), isfunc, mkop, NULL, RIGHT, tree(), and voidtype.
Referenced by bbentry(), bbexit(), nullcall(), and nullcheck().
Variable Documentation
optree
Tree(* optree[])(int, Tree, Tree)
Initial value:
= {
#define xx(a,b,c,d,e,f,g)
#define yy(a,b,c,d,e,f,g)
}
Definition at line 14 of file enode.c.
Referenced by bbincr(), cast(), cond(), expr3(), incr(), postfix(), swcode(), and tracevalue().