ZEQ2-Lite: TextureBrush Class Reference
TextureBrush Class Reference
#include <gdiplusbrush.h>
Public Member Functions
TextureBrush (Image *image, const Rect &dstRect, ImageAttributes *imageAttributes=NULL)
TextureBrush (Image *image, const RectF &dstRect, ImageAttributes *imageAttributes=NULL)
TextureBrush (Image *image, WrapMode wrapMode, const Rect &dstRect)
TextureBrush (Image *image, WrapMode wrapMode, const RectF &dstRect)
TextureBrush (Image *image, WrapMode wrapMode, INT dstX, INT dstY, INT dstWidth, INT dstHeight)
TextureBrush (Image *image, WrapMode wrapMode, REAL dstX, REAL dstY, REAL dstWidth, REAL dstHeight)
TextureBrush (Image *image, WrapMode wrapMode=WrapModeTile)
virtual TextureBrush * Clone () const
Status GetLastStatus () const
Status GetTransfrom (Matrix *matrix) const
BrushType GetType () const
WrapMode GetWrapMode () const
Status MultiplyTransform (const Matrix *matrix, MatrixOrder order=MatrixOrderPrepend)
Status ResetTransform ()
Status RotateTransform (REAL angle, MatrixOrder order=MatrixOrderPrepend)
Status ScaleTransform (REAL sx, REAL sy, MatrixOrder order=MatrixOrderPrepend)
Status SetTransform (const Matrix *matrix)
Status SetWrapMode (WrapMode wrapMode)
Status TranslateTransform (REAL dx, REAL dy, MatrixOrder order=MatrixOrderPrepend)
Static Public Member Functions
static void operator delete (void *in_pVoid)
static void operator delete[] (void *in_pVoid)
static void * operator new (size_t in_size)
static void * operator new[] (size_t in_size)
Private Member Functions
TextureBrush (const TextureBrush &)
TextureBrush (GpBrush *brush, Status status)
TextureBrush & operator= (const TextureBrush &)
Status updateStatus (Status newStatus) const
Private Attributes
Status lastStatus
GpBrush * nativeBrush
Detailed Description
Definition at line 448 of file gdiplusbrush.h.
Constructor & Destructor Documentation
TextureBrush() [1/9]
TextureBrush::TextureBrush (Image * image, WrapMode wrapMode = WrapModeTile) inline
Definition at line 451 of file gdiplusbrush.h.
     {
         GpTexture *nativeTexture = NULL;
         lastStatus = DllExports::GdipCreateTexture(
                 image ? image->nativeImage : NULL,
                 wrapMode, &nativeTexture);
         nativeBrush = nativeTexture;
     }
References GdipCreateTexture(), Brush::lastStatus, Brush::nativeBrush, and NULL.
TextureBrush() [2/9]
TextureBrush::TextureBrush (Image * image, WrapMode wrapMode, REAL dstX, REAL dstY, REAL dstWidth, REAL dstHeight) inline
Definition at line 459 of file gdiplusbrush.h.
     {
         GpTexture *nativeTexture = NULL;
         lastStatus = DllExports::GdipCreateTexture2(
                 image ? image->nativeImage : NULL,
                 wrapMode, dstX, dstY, dstWidth, dstHeight,
                 &nativeTexture);
         nativeBrush = nativeTexture;
     }
References GdipCreateTexture2(), Brush::lastStatus, Brush::nativeBrush, and NULL.
TextureBrush() [3/9]
TextureBrush::TextureBrush (Image * image, WrapMode wrapMode, INT dstX, INT dstY, INT dstWidth, INT dstHeight) inline
Definition at line 469 of file gdiplusbrush.h.
     {
         GpTexture *nativeTexture = NULL;
         lastStatus = DllExports::GdipCreateTexture2I(
                 image ? image->nativeImage : NULL,
                 wrapMode, dstX, dstY, dstWidth, dstHeight,
                 &nativeTexture);
         nativeBrush = nativeTexture;
     }
References GdipCreateTexture2I(), Brush::lastStatus, Brush::nativeBrush, and NULL.
TextureBrush() [4/9]
TextureBrush::TextureBrush (Image * image, WrapMode wrapMode, const RectF & dstRect) inline
Definition at line 479 of file gdiplusbrush.h.
     {
         GpTexture *nativeTexture = NULL;
         lastStatus = DllExports::GdipCreateTexture2(
                 image ? image->nativeImage : NULL, wrapMode,
                 dstRect.X, dstRect.Y,
                 dstRect.Width, dstRect.Height, &nativeTexture);
         nativeBrush = nativeTexture;
     }
References GdipCreateTexture2(), RectF::Height, Brush::lastStatus, Brush::nativeBrush, NULL, RectF::Width, RectF::X, and RectF::Y.
TextureBrush() [5/9]
TextureBrush::TextureBrush (Image * image, WrapMode wrapMode, const Rect & dstRect) inline
Definition at line 488 of file gdiplusbrush.h.
     {
         GpTexture *nativeTexture = NULL;
         lastStatus = DllExports::GdipCreateTexture2I(
                 image ? image->nativeImage : NULL, wrapMode,
                 dstRect.X, dstRect.Y,
                 dstRect.Width, dstRect.Height, &nativeTexture);
         nativeBrush = nativeTexture;
     }
References GdipCreateTexture2I(), Rect::Height, Brush::lastStatus, Brush::nativeBrush, NULL, Rect::Width, Rect::X, and Rect::Y.
TextureBrush() [6/9]
TextureBrush::TextureBrush (Image * image, const RectF & dstRect, ImageAttributes * imageAttributes = NULL) inline
Definition at line 497 of file gdiplusbrush.h.
     {
         GpTexture *nativeTexture = NULL;
         lastStatus = DllExports::GdipCreateTextureIA(
                 image ? image->nativeImage : NULL,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL,
                 dstRect.X, dstRect.Y,
                 dstRect.Width, dstRect.Height, &nativeTexture);
         nativeBrush = nativeTexture;
     }
References GdipCreateTextureIA(), RectF::Height, Brush::lastStatus, Brush::nativeBrush, NULL, RectF::Width, RectF::X, and RectF::Y.
TextureBrush() [7/9]
TextureBrush::TextureBrush (Image * image, const Rect & dstRect, ImageAttributes * imageAttributes = NULL) inline
Definition at line 508 of file gdiplusbrush.h.
     {
         GpTexture *nativeTexture = NULL;
         lastStatus = DllExports::GdipCreateTextureIAI(
                 image ? image->nativeImage : NULL,
                 imageAttributes ? imageAttributes->nativeImageAttributes : NULL,
                 dstRect.X, dstRect.Y,
                 dstRect.Width, dstRect.Height, &nativeTexture);
         nativeBrush = nativeTexture;
     }
References GdipCreateTextureIAI(), Rect::Height, Brush::lastStatus, Brush::nativeBrush, NULL, Rect::Width, Rect::X, and Rect::Y.
TextureBrush() [8/9]
TextureBrush::TextureBrush (GpBrush * brush, Status status) inline private
Definition at line 601 of file gdiplusbrush.h.
 : Brush(brush, status) {}
TextureBrush() [9/9]
TextureBrush::TextureBrush (const TextureBrush &) private
Member Function Documentation
Clone()
virtual TextureBrush* TextureBrush::Clone () const inline virtual
Reimplemented from Brush.
Definition at line 519 of file gdiplusbrush.h.
     {
         GpBrush *cloneBrush = NULL;
         Status status = updateStatus(DllExports::GdipCloneBrush(
                 nativeBrush, &cloneBrush));
         if (status == Ok) {
             TextureBrush *result =
                 new TextureBrush(cloneBrush, lastStatus);
             if (!result) {
                 DllExports::GdipDeleteBrush(cloneBrush);
                 updateStatus(OutOfMemory);
             }
             return result;
         } else {
             return NULL;
         }
     }
References GdipCloneBrush(), GdipDeleteBrush(), Brush::lastStatus, Brush::nativeBrush, NULL, Ok, OutOfMemory, Brush::TextureBrush, and Brush::updateStatus().
GetLastStatus()
Status Brush::GetLastStatus () const inline inherited
Definition at line 54 of file gdiplusbrush.h.
     {
         Status result = lastStatus;
         lastStatus = Ok;
         return result;
     }
References Brush::lastStatus, and Ok.
GetTransfrom()
Status TextureBrush::GetTransfrom (Matrix * matrix) const inline
Definition at line 545 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipGetTextureTransform(
                 (GpTexture*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipGetTextureTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
GetType()
BrushType Brush::GetType () const inline inherited
Definition at line 60 of file gdiplusbrush.h.
     {
         BrushType result = BrushTypeSolidColor;
         updateStatus(DllExports::GdipGetBrushType(nativeBrush, &result));
         return result;
     }
References BrushTypeSolidColor, GdipGetBrushType(), Brush::nativeBrush, and Brush::updateStatus().
GetWrapMode()
WrapMode TextureBrush::GetWrapMode () const inline
Definition at line 551 of file gdiplusbrush.h.
     {
         WrapMode result = WrapModeTile;
         updateStatus(DllExports::GdipGetTextureWrapMode(
                 (GpTexture*) nativeBrush, &result));
         return result;
     }
References GdipGetTextureWrapMode(), Brush::nativeBrush, Brush::updateStatus(), and WrapModeTile.
MultiplyTransform()
Status TextureBrush::MultiplyTransform (const Matrix * matrix, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 558 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipMultiplyTextureTransform(
                 (GpTexture*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL, order));
     }
References GdipMultiplyTextureTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
operator delete()
static void GdiplusBase::operator delete (void * in_pVoid) inline static inherited
Definition at line 44 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator delete[]()
static void GdiplusBase::operator delete[] (void * in_pVoid) inline static inherited
Definition at line 48 of file gdiplusbase.h.
     {
         DllExports::GdipFree(in_pVoid);
     }
References GdipFree().
operator new()
static void* GdiplusBase::operator new (size_t in_size) inline static inherited
Definition at line 36 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator new[]()
static void* GdiplusBase::operator new[] (size_t in_size) inline static inherited
Definition at line 40 of file gdiplusbase.h.
     {
         return DllExports::GdipAlloc(in_size);
     }
References GdipAlloc().
operator=()
TextureBrush& TextureBrush::operator= (const TextureBrush &) private
ResetTransform()
Status TextureBrush::ResetTransform () inline
Definition at line 565 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipResetTextureTransform(
                 (GpTexture*) nativeBrush));
     }
References GdipResetTextureTransform(), Brush::nativeBrush, and Brush::updateStatus().
RotateTransform()
Status TextureBrush::RotateTransform (REAL angle, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 570 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipRotateTextureTransform(
                 (GpTexture*) nativeBrush, angle, order));
     }
References GdipRotateTextureTransform(), Brush::nativeBrush, and Brush::updateStatus().
ScaleTransform()
Status TextureBrush::ScaleTransform (REAL sx, REAL sy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 576 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipScaleTextureTransform(
                 (GpTexture*) nativeBrush, sx, sy, order));
     }
References GdipScaleTextureTransform(), Brush::nativeBrush, sy, and Brush::updateStatus().
SetTransform()
Status TextureBrush::SetTransform (const Matrix * matrix) inline
Definition at line 582 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetTextureTransform(
                 (GpTexture*) nativeBrush,
                 matrix ? matrix->nativeMatrix : NULL));
     }
References GdipSetTextureTransform(), Brush::nativeBrush, NULL, and Brush::updateStatus().
SetWrapMode()
Status TextureBrush::SetWrapMode (WrapMode wrapMode) inline
Definition at line 588 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipSetTextureWrapMode(
                 (GpTexture*) nativeBrush, wrapMode));
     }
References GdipSetTextureWrapMode(), Brush::nativeBrush, and Brush::updateStatus().
TranslateTransform()
Status TextureBrush::TranslateTransform (REAL dx, REAL dy, MatrixOrder order = MatrixOrderPrepend) inline
Definition at line 593 of file gdiplusbrush.h.
     {
         return updateStatus(DllExports::GdipTranslateTextureTransform(
                 (GpTexture*) nativeBrush, dx, dy, order));
     }
References GdipTranslateTextureTransform(), Brush::nativeBrush, and Brush::updateStatus().
updateStatus()
Status Brush::updateStatus (Status newStatus) const inline private inherited
Definition at line 74 of file gdiplusbrush.h.
     {
         if (newStatus != Ok) lastStatus = newStatus;
         return newStatus;
     }
References Brush::lastStatus, and Ok.
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), Clone(), PathGradientBrush::Clone(), HatchBrush::GetBackgroundColor(), LinearGradientBrush::GetBlend(), PathGradientBrush::GetBlend(), LinearGradientBrush::GetBlendCount(), PathGradientBrush::GetBlendCount(), PathGradientBrush::GetCenterColor(), PathGradientBrush::GetCenterPoint(), SolidBrush::GetColor(), PathGradientBrush::GetFocusScales(), HatchBrush::GetForegroundColor(), LinearGradientBrush::GetGammaCorrection(), PathGradientBrush::GetGammaCorrection(), HatchBrush::GetHatchStyle(), LinearGradientBrush::GetInterpolationColorCount(), PathGradientBrush::GetInterpolationColorCount(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetPointCount(), LinearGradientBrush::GetRectangle(), PathGradientBrush::GetRectangle(), PathGradientBrush::GetSurroundColorCount(), PathGradientBrush::GetSurroundColors(), LinearGradientBrush::GetTransform(), PathGradientBrush::GetTransform(), GetTransfrom(), Brush::GetType(), LinearGradientBrush::GetWrapMode(), GetWrapMode(), PathGradientBrush::GetWrapMode(), LinearGradientBrush::MultiplyTransform(), MultiplyTransform(), PathGradientBrush::MultiplyTransform(), LinearGradientBrush::ResetTransform(), ResetTransform(), PathGradientBrush::ResetTransform(), LinearGradientBrush::RotateTranform(), RotateTransform(), PathGradientBrush::RotateTransform(), LinearGradientBrush::ScaleTransform(), ScaleTransform(), PathGradientBrush::ScaleTransform(), LinearGradientBrush::SetBlend(), PathGradientBrush::SetBlend(), LinearGradientBrush::SetBlendBellShape(), PathGradientBrush::SetBlendBellShape(), LinearGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetCenterColor(), PathGradientBrush::SetCenterPoint(), SolidBrush::SetColor(), PathGradientBrush::SetFocusScales(), LinearGradientBrush::SetGammaCorrection(), PathGradientBrush::SetGammaCorrection(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), LinearGradientBrush::SetLinearColors(), PathGradientBrush::SetSurroundColors(), LinearGradientBrush::SetTransform(), SetTransform(), PathGradientBrush::SetTransform(), LinearGradientBrush::SetWrapMode(), SetWrapMode(), PathGradientBrush::SetWrapMode(), LinearGradientBrush::TranslateTransform(), TranslateTransform(), and PathGradientBrush::TranslateTransform().
Field Documentation
lastStatus
Status Brush::lastStatus mutable private inherited
Definition at line 81 of file gdiplusbrush.h.
Referenced by Brush::Clone(), HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), Clone(), PathGradientBrush::Clone(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), Brush::GetLastStatus(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetSurroundColors(), HatchBrush::HatchBrush(), LinearGradientBrush::LinearGradientBrush(), PathGradientBrush::PathGradientBrush(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), PathGradientBrush::SetSurroundColors(), SolidBrush::SolidBrush(), TextureBrush(), and Brush::updateStatus().
nativeBrush
GpBrush* Brush::nativeBrush private inherited
Definition at line 80 of file gdiplusbrush.h.
Referenced by HatchBrush::Clone(), LinearGradientBrush::Clone(), SolidBrush::Clone(), Clone(), PathGradientBrush::Clone(), Graphics::DrawDriverString(), Graphics::DrawString(), Graphics::FillClosedCurve(), Graphics::FillEllipse(), Graphics::FillPath(), Graphics::FillPie(), Graphics::FillPolygon(), Graphics::FillRectangle(), Graphics::FillRectangles(), Graphics::FillRegion(), HatchBrush::GetBackgroundColor(), LinearGradientBrush::GetBlend(), PathGradientBrush::GetBlend(), LinearGradientBrush::GetBlendCount(), PathGradientBrush::GetBlendCount(), PathGradientBrush::GetCenterColor(), PathGradientBrush::GetCenterPoint(), SolidBrush::GetColor(), PathGradientBrush::GetFocusScales(), HatchBrush::GetForegroundColor(), LinearGradientBrush::GetGammaCorrection(), PathGradientBrush::GetGammaCorrection(), HatchBrush::GetHatchStyle(), LinearGradientBrush::GetInterpolationColorCount(), PathGradientBrush::GetInterpolationColorCount(), LinearGradientBrush::GetInterpolationColors(), PathGradientBrush::GetInterpolationColors(), LinearGradientBrush::GetLinearColors(), PathGradientBrush::GetPointCount(), LinearGradientBrush::GetRectangle(), PathGradientBrush::GetRectangle(), PathGradientBrush::GetSurroundColorCount(), PathGradientBrush::GetSurroundColors(), LinearGradientBrush::GetTransform(), PathGradientBrush::GetTransform(), GetTransfrom(), Brush::GetType(), LinearGradientBrush::GetWrapMode(), GetWrapMode(), PathGradientBrush::GetWrapMode(), HatchBrush::HatchBrush(), LinearGradientBrush::LinearGradientBrush(), LinearGradientBrush::MultiplyTransform(), MultiplyTransform(), PathGradientBrush::MultiplyTransform(), PathGradientBrush::PathGradientBrush(), Pen::Pen(), LinearGradientBrush::ResetTransform(), ResetTransform(), PathGradientBrush::ResetTransform(), LinearGradientBrush::RotateTranform(), RotateTransform(), PathGradientBrush::RotateTransform(), LinearGradientBrush::ScaleTransform(), ScaleTransform(), PathGradientBrush::ScaleTransform(), LinearGradientBrush::SetBlend(), PathGradientBrush::SetBlend(), LinearGradientBrush::SetBlendBellShape(), PathGradientBrush::SetBlendBellShape(), LinearGradientBrush::SetBlendTriangularShape(), PathGradientBrush::SetBlendTriangularShape(), Pen::SetBrush(), PathGradientBrush::SetCenterColor(), PathGradientBrush::SetCenterPoint(), SolidBrush::SetColor(), PathGradientBrush::SetFocusScales(), LinearGradientBrush::SetGammaCorrection(), PathGradientBrush::SetGammaCorrection(), LinearGradientBrush::SetInterpolationColors(), PathGradientBrush::SetInterpolationColors(), LinearGradientBrush::SetLinearColors(), PathGradientBrush::SetSurroundColors(), LinearGradientBrush::SetTransform(), SetTransform(), PathGradientBrush::SetTransform(), LinearGradientBrush::SetWrapMode(), SetWrapMode(), PathGradientBrush::SetWrapMode(), SolidBrush::SolidBrush(), TextureBrush(), LinearGradientBrush::TranslateTransform(), TranslateTransform(), PathGradientBrush::TranslateTransform(), and Brush::~Brush().
The documentation for this class was generated from the following file:
Tools/MinGW/include/gdiplus/gdiplusbrush.h