ZEQ2-Lite: Source/Engine/tools/lcc/src/string.c File Reference
string.c File Reference
#include "c.h"
Data Structures
struct string
Functions
char * string (const char *str)
char * stringd (long n)
char * stringn (const char *str, int len)
Variables
static struct string * buckets [1024]
static int scatter []
Function Documentation
string()
char* string (const char * str)
Definition at line 63 of file string.c.
{
     const char *s;
     for (s = str; *s; s++)
         ;
     return stringn(str, s - str);
 }
References string::str, and stringn().
stringd()
char* stringd (long n)
Definition at line 70 of file string.c.
                       {
     char str[25], *s = str + sizeof (str);
     unsigned long m;
     if (n == LONG_MIN)
         m = (unsigned long)LONG_MAX + 1;
     else if (n < 0)
         m = -n;
     else
         m = n;
     do
         *--s = m%10 + '0';
     while ((m /= 10) != 0);
     if (n < 0)
         *--s = '-';
     return stringn(s, str + sizeof (str) - s);
 }
References long(), m, string::str, and stringn().
Referenced by addrtree(), defsymbol(), fields(), findlabel(), genident(), mkauto(), newfield(), newstruct(), opname(), parameters(), temporary(), and vtoa().
stringn()
char* stringn (const char * str, int len)
Definition at line 87 of file string.c.
{
     int i;
     unsigned int h;
     const char *end;
     struct string *p;
     assert(str);
     for (h = 0, i = len, end = str; i > 0; i--)
         h = (h<<1) + scatter[*(unsigned char *)end++];
     h &= NELEMS(buckets)-1;
     for (p = buckets[h]; p; p = p->link)
         if (len == p->len) {
             const char *s1 = str;
             char *s2 = p->str;
             do {
                 if (s1 == end)
                     return p->str;
             } while (*s1++ == *s2++);
         }
     {
         static char *next, *strlimit;
         if (len + 1 >= strlimit - next) {
             int n = len + 4*1024;
             next = allocate(n, PERM);
             strlimit = next + n;
         }
         NEW(p, PERM);
         p->len = len;
         for (p->str = next; str < end; )
             *next++ = *str++;
         *next++ = 0;
         p->link = buckets[h];
         buckets[h] = p;
         return p->str;
     }
 }
References allocate(), buckets, NELEMS, NEW, PERM, scatter, and string::str.
Referenced by gettok(), main_init(), primary(), resynch(), string(), and stringd().
Variable Documentation
buckets
struct string * buckets[1024] static
Referenced by stringn().
scatter
int scatter[] static
Definition at line 9 of file string.c.
Referenced by stringn().